### ISSUE TITLE
NewSerializerWithOptions yaml for v2beta2 HPA cannot be applied with ValidationError

### ISSUE THREAD

**Issue by zeleena** [kubernetes/kubernetes#100021]
#### What happened:

Serializing a v2beta2 HorizontalPodAutoscaler with `NewSerializerWithOptions` (and `NewYAMLSerializer`) produces yaml that cannot be applied due to a ValidationError on the `conditions` field which is under the _optional_ field `status`.

#### What you expected to happen:

A valid HPA serialized with `NewSerializerWithOptions` should be able to be applied to the cluster with no validation errors, without filling out the optional `status` field.

Other valid objects (such as Namespaces and Deployments) can be applied directly, without filling out their optional `status` fields.

#### How to reproduce it (as minimally and precisely as possible):

Run this to generate the serialized yaml (same outcome with both `NewSerializerWithOptions` and `NewYAMLSerializer` functions)
```
package main

import (
  "os"

  autoscalingv2beta2 "k8s.io/api/autoscaling/v2beta2"
  metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
  "k8s.io/apimachinery/pkg/runtime/serializer/json"
  "k8s.io/client-go/kubernetes/scheme"
)

func main() {
  hpa := autoscalingv2beta2.HorizontalPodAutoscaler{
    TypeMeta: metav1.TypeMeta{
      Kind: "HorizontalPodAutoscaler",
      APIVersion: "autoscaling/v2beta2",
    },
    ObjectMeta: metav1.ObjectMeta{
      Name: "hpatest",
      Namespace: "test",
    },
  }

  //encoder := json.NewYAMLSerializer(json.DefaultMetaFactory, scheme.Scheme, scheme.Scheme)
  encoder := json.NewSerializerWithOptions(json.DefaultMetaFactory, scheme.Scheme, scheme.Scheme, json.SerializerOptions{Yaml: true,})
  encoder.Encode(&hpa, os.Stdout)
}
```

Running the go code should yield this yaml:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: hpatest
  namespace: test
spec:
  maxReplicas: 0
  scaleTargetRef:
    kind: ""
    name: ""
status:
  conditions: null
  currentMetrics: null
  currentReplicas: 0
  desiredReplicas: 0
```

Writing the above yaml to a file hpa.yaml and applying it (with `kubectl apply -f hpa.yaml`) will result in:

```
error: error validating "hpa.yaml": error validating data: ValidationError(HorizontalPodAutoscaler.status): missing required field "conditions" in io.k8s.api.autoscaling.v2beta2.HorizontalPodAutoscalerStatus; if you choose to ignore these errors, turn validation off with --validate=false
```

#### Environment:
- Kubernetes version (use `kubectl version`): Server: v1.20.2, Client: v1.20.4
- go version: go1.16 darwin/amd64
- go.mod has:
```
require (
  k8s.io/api v0.17.0
  k8s.io/apimachinery v0.17.0
  k8s.io/client-go v0.17.0
)
```
cc @ashleykasim 
cc @paulnivin
