### ISSUE TITLE
Deployment ReadyReplica status does not reflect real state 

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#100192]
This is discovered through flaky test issue #100047 

The test first create a deployment with 2 replicas using Anghost image. And then the deployment is patched with a different image Pause and replica number changed from 2 to 1. But the following happens

1. the new pod comes up with the new image fails to start successfully, enter crash loop.
2. the old pod has to continue to run due to RollingUpdateStrategy 25% max unavailable, 25% max surge

In this case, strictly speaking, the patch update failed, there is no pod running with the updated image. But the deployment ReadyReplica is changed updated to 1 (it goes through a number of changes, terminating one old pod, create two new pods, and immediately delete one of the two new pods). The deployment spec container image is also changed from Anghost to Pause. 

The following is the check from the test will pass.
```
deployment.Status.ReadyReplicas == testDeploymentMinimumReplicas &&
deployment.Spec.Template.Spec.Containers[0].Image == testDeploymentPatchImage
```

Is it reasonable to update number of ReadyReplica to 1? Or it should be 0 to reflect that no pod is ready with correct image updated? In this case, what is the correct checking to make sure deployment is actually running in the expected state?

**Comment by jingxu97** [comment]
cc @liggitt @msau42

**Comment by liggitt** [comment]
I think UpdatedReplicas is the status field indicating pods reflecting the current template

**Comment by liggitt** [comment]
ReadyReplicas refers to the count of pods whose readiness checks (if defined) are passing

**Comment by jingxu97** [comment]
> I think UpdatedReplicas is the status field indicating pods reflecting the current template

So is it better to add the check UpdatedReplicas == Desired too in the test?

**Comment by liggitt** [comment]
I not quite sure what the intent of the test was, but if it was to make sure the new spec was effectively running pods, I think so.

**Comment by jingxu97** [comment]
I tested this scenario manually and it shows that UpdatedReplicas is also changed actually. One status field can indicate there is some issue for this deployment is unavailableReplicas is set to 1. So to make sure this deployment is patched successfully, I think we could check unavailableReplicas > 0.

During first step, deployment has two replicas which are running successfully
```
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2021-03-15T17:17:15Z"
      lastUpdateTime: "2021-03-15T17:17:15Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-03-15T17:17:13Z"
      lastUpdateTime: "2021-03-15T17:17:15Z"
      message: ReplicaSet "nginx-7877c69465" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
```

The second step, deployment updated to one replicas but the new pod failed to running.
The status of deployment is 
```
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2021-03-15T17:24:39Z"
      lastUpdateTime: "2021-03-15T17:24:39Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-03-15T17:24:37Z"
      lastUpdateTime: "2021-03-15T17:28:52Z"
      message: ReplicaSet "nginx-6865554d44" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 2
    unavailableReplicas: 1
    updatedReplicas: 1
```
