### ISSUE TITLE
Network Policy accepts 2 cidrs in one ipBlock

### ISSUE THREAD

**Issue by dean-alphafx** [kubernetes/kubernetes#100213]
#### What happened:
When adding to 2 cidrs to the ipBlock in a network policy, it is accepted as valid when it's clearly not.

#### What you expected to happen:
See an error stating the format is invalid.

#### How to reproduce it (as minimally and precisely as possible):
1. Create a default network policy to block all egress/ingres.
2. Create a network policy with the following egress rules:
`
  - to:
    - ipBlock:
        cidr: 8.8.8.8/32
        cidr: 8.8.4.4/32
    ports:
    - protocol: tcp
`
3. telnet 8.8.8.8 32 (it may or may not work)
4. telnet 8.8.4.4 32 (it may or may not work)

#### Anything else we need to know?:
Correct format is the following:
`
  - to:
    - ipBlock:
        cidr: 8.8.8.8/32
  - ipBlock:
        cidr: 8.8.4.4/32
    ports:
    - protocol: tcp
`
#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.4
- Cloud provider or hardware configuration: ec2-instances
- OS (e.g: `cat /etc/os-release`): 18.04.1-Ubuntu
- Kernel (e.g. `uname -a`): Linux cks-master 5.4.0-1037-aws #39~18.04.1-Ubuntu SMP Fri Jan 15 02:48:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: telnet
- Network plugin and version (if this is a network-related bug): coredns:1.7.0
- Others:

**Comment by aojea** [comment]
@jayunit100 @rikatz this seems a good one for the netpol crew ;)

**Comment by jayunit100** [comment]
We'll look at it tomorrow unless matt gets to it first

**Comment by mattfenwick** [comment]
Just checked with kubeval -- kubeval reports this as an invalid policy under strict mode:

```
kubeval --strict policy.yaml
WARN - policy.yaml contains an invalid NetworkPolicy (y.allow-all-ingress) - to: Additional property to is not allowed
```

Same problem for me on KinD -- kube accepts the policy, but then silently drops the second 
```
➜  kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:08:32Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

➜  kubectl create -f policy.yaml
networkpolicy.networking.k8s.io/allow-all-ingress created

➜ kubectl get netpol -o yaml
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-all-ingress
    namespace: default
  spec:
    ingress:
    - from:
      - ipBlock:
          cidr: 8.8.4.4/32
      ports:
      - protocol: TCP
    podSelector:
      matchLabels:
        pod: c
    policyTypes:
    - Ingress
```

@jayunit100 @rikatz looks like we need to add some validation on the kubernetes side.

**Comment by dean-alphafx** [comment]
Odd @mattfenwick, `kubeval --strict` doesn't even complain for me:
```
root@cks-master:~# cat broke_np.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: backend
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - ipBlock:
        cidr: 8.8.4.4/32
        cidr: 1.1.1.1/32
        cidr: 8.8.8.8/32
        cidr: 2.2.2.2/32
    ports:
    - protocol: TCP
      port: 53
root@cks-master:~# ./kubeval --strict broke_np.yaml
PASS - broke_np.yaml contains a valid NetworkPolicy (default.backend)
```

**Comment by mattfenwick** [comment]
Ah good call @dean-alphafx , I made a boneheaded mistake and put a different policy into kubeval!!

Retrying with the right policy, I got the same result as you.  I think we need to report a kubeval bug too!

For solving this, [yaml.UnmarshalStrict](https://pkg.go.dev/sigs.k8s.io/yaml#UnmarshalStrict) does handle this correctly in one of my projects, maybe we could use that.

**Comment by mattfenwick** [comment]
Reported this on kubeval over at https://github.com/instrumenta/kubeval/issues/273 !

**Comment by solomonope** [comment]
I would like to work on this

**Comment by mattfenwick** [comment]
@solomonope will hand off to you :) :) lmk if you need anything from me !!!

**Comment by mattfenwick** [comment]
Can also use dry-run to see this behavior:

```
kubectl create --dry-run=client -f policy.yaml -o yaml
```

**Comment by rikatz** [comment]
@solomonope The main problem here seems in the network policy validation -> https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/validation/validation.go#L190

Definition of an IPBlock:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/types.go#L158-L161

If you need some guidance, please let me know as well :)

@mattfenwick I'm thinking a bit here, I don't know actually what's the behavior of the API should be if you insert multiple strings in a struct that should receive only one.

Like:

```golang
type Blo struct {
    MyString string
}
```

For what I can see here, what's happening actually is that the double declaration of the CIDR (which is a single field inside the IPBlock struct) is being overwritten because you can only declare once.

Do you remember other case in Kubernetes API that accepts a string, and you do a double declaration? Like, what happens if I create a Pod object, and insert the 'image' field twice? Should test before assume that a validation can solve this problem :)

**Comment by rikatz** [comment]
yeap, just concluding, this is the correct behavior of the API, as an example, when I create the following deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  replicas: 2 
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        image: nginx1
        name: nginx
        resources: {}
```

I repeat replicas and the image fields twice, so the last value the field have is the one that counts:

```
kubectl  get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   0/3     3            0           55s
``` 

IMO the behavior is right, and there's no correction that can be made on validation as the part is a struct containing a string. Anyway, waiting for some more thoughts here :)
