### ISSUE TITLE
ipBlock.cidr does not block connection on the node where the pod is running?

### ISSUE THREAD

**Issue by tanvp112** [kubernetes/kubernetes#100247]
Hi, I have a 1.20.4 cluster with 1 master & 2 worker nodes with calico (3.18) vxlan network. I deployed 5 nginx to kube-public like this:

```
NAME                     READY   STATUS    RESTARTS   AGE     IP             NODE        
nginx-59864f8d64-pgjfw   1/1     Running   1          7h37m   10.10.45.222   worker1
nginx-59864f8d64-wl22m   1/1     Running   1          7h37m   10.10.45.221   worker1
nginx-59864f8d64-5c48m   1/1     Running   1          7h37m   10.10.58.202   worker2
nginx-59864f8d64-wnvcn   1/1     Running   1          7h37m   10.10.58.203   worker2
nginx-59864f8d64-nvn2c   1/1     Running   1          7h37m   10.10.58.204   worker2

NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
nginx     ClusterIP   10.96.184.228   <none>        80/TCP,8080/TCP   8h
```

As master1 is tainted, nginx is deployed to worker1 & worker2 as expected. There is a service (10.96.184.228) front for the nginx pods. I then deployed a k8s NetworkPolicy like this:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-nginx
  namespace: kube-public
spec:
  policyTypes:
  - Ingress
  - Egress
  podSelector: {}
  ingress:
  - from:
    - ipBlock:
        cidr: 172.16.1.10/32
  egress:
  - to:
    - ipBlock:
        cidr: 172.16.1.10/32
```

172.16.1.10 is the node (master1) IP address. The intention is to allow ONLY master1 to communicate with nginx pods running on workers node. The following is the test result running a for loop 100 times accessing the service (10.96.184.228), pod (10.10.45.222) running on worker1 node and pod (10.10.58.202) running on worker2.

```
Action                            Result
curl 10.96.184.228 on master1     All calls succeeded.
curl 10.96.184.228 on worker1     *Partially succeed
curl 10.96.184.228 on worker2     *Partially succeed
curl 10.10.45.222 on worker1      *Succeed as pod (10.10.45.222) runs on node worker1*
curl 10.10.58.202 on worker1      Denied
curl 10.10.45.222 on worker2      Denied
curl 10.10.58.202 on worker2      *Succeed as pod (10.10.58.202) runs on node worker2*

exec into 10.10.45.222 and curl ALL other nginx pods    All denied
Start a busybox and curl ALL other nginx pods           All denied
```

Clearly, the network policy has no effect when the connection was made on the same node as the pod is running; be it a direct connect (eg. curl) or routed by kube-proxy (eg. via service). 

Is this behavior expected?

/sig network
