### ISSUE TITLE
RoleBinding: keda-auth-reader should be in kube-system namespace

### ISSUE THREAD

**Issue by hopik007** [kubernetes/kubernetes#100340]
#### What happened:
During deploying Keda 2.1.0  issue when metric pod starting:

_W0317 16:10:21.774104       1 requestheader_controller.go:193] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'_

#### What is defined in manifest:
In your manifest is for version > 2.0 is defined:

``` 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-auth-reader
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.1.0
  name: keda-auth-reader
  namespace: keda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: keda
``` 

#### How to fixed:

In RoleBinding should be namespace: kube-system not keda:

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-auth-reader
    app.kubernetes.io/part-of: keda-operator
    app.kubernetes.io/version: 2.1.0
  name: keda-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: keda
