### ISSUE TITLE
[kubeadm] etcd upgrade failure when ImageTag contains build metadata

### ISSUE THREAD

**Issue by jr0d** [kubernetes/kubernetes#100349]
<!-- Please use this template while reporting a bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!

If the matter is security related, please disclose it privately via https://kubernetes.io/security/
-->
# Greetings!

#### What happened:
When attempting to upgrade kubernetes using kubeadm upgrade apply, kubeadm fails to parse an etcd imagetag containing build metadata in the form of `version_metadata` as a valid semver.

An example upgrade produces an error similar to:
```
[upgrade/apply] FATAL: failed comparing the current etcd version "v3.4.13_patch.0" to the desired one "3.4.13-0": could not parse pre-release/metadata (_patch.0) in version "v3.4.13_fips"
```
Note this will occur even if the etcd version is unchanged. 

#### What you expected to happen:
The `_` should be converted to a `+` character. This pattern is used to support custom kubernetes images, for instance kube-apiserver:v1.20.4+patch.0 will be converted to imagetag v1.20.4_patch.0 when running make quick-release-images. 

#### How to reproduce it (as minimally and precisely as possible):
Add the following to kubeadm-config.yaml:
```
etcd:                                                                                                                                                                                                                                                                                                                                                  
  local:                                                                                                                                                                                                                                                                                                                                               
    imageRepository: "custom"                                                                                                                                                                                                                                                                                                                      
    imageTag: "v3.4.13_patch.0"
```

Install kubernetes. Then upgrade kubernetes with kubeadm upgrade apply. 

#### Anything else we need to know?:
I have tested a fix for this issue and will PR shortly.

#### Environment:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A
