### ISSUE TITLE
pause container has seccomp=unconfined if pod were specified docker/default annotation

### ISSUE THREAD

**Issue by YanzhaoLi** [kubernetes/kubernetes#100374]
#### What happened:
The Pod yaml is:
```
  kind: Pod
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
```
The `/pause` container for this pod has `seccomp=unconfined`

#### What you expected to happen:

IMO, as this [pr](https://github.com/kubernetes/kubernetes/pull/90948) shows, pod sandbox should always have `seccomp=runtime/default`

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.4
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): ubuntu16.04
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
