### ISSUE TITLE
how to close serviceaccount/token fuction

### ISSUE THREAD

**Issue by pyjlwc2016** [kubernetes/kubernetes#100366]
2021/03/18 16:40:53 Using namespace: kube-system
2021/03/18 16:40:53 Using in-cluster config to connect to apiserver
2021/03/18 16:40:53 Could not init in cluster config: open /var/run/secrets/kubernetes.io/serviceaccount/token: The system cannot find the path specified.
panic: could not create client config

**Comment by NovaHe** [comment]
Maybe [automountServiceAccountToken](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) can help you 
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
automountServiceAccountToken: false
```
