### ISSUE TITLE
Using service principal to mount azure file as a persistent volume

### ISSUE THREAD

**Issue by LeeDustin** [kubernetes/kubernetes#100391]
Currently the standard way of setting the PV on static azure files, i.e. create storage account and fileshare, create secret using the account name and secret of the storage account, then create the PV as below:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage
  labels:
    usage: storage
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - mfsymlinks
    - nobrl
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: sharefile
    readOnly: false
```

I am now wondering whether I can use service principal instead of the azure secret using storage account name and key to access the azure files. 

Using secret means having access to the whole storage account, but if we can use service principal we can restrict access to only part of the storage account, i.e. azure files in this case.
