### ISSUE TITLE
aws: Failed to mount partition on NVMe volume

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#100499]
#### What happened:
When using a AWS EBS PV or on-line volume with a partition on a Nitro machine, the volume is available as NVMe device. Kubelet is not able to format & mount the partition:

```
Warning  FailedMount  13s  kubelet  (combined from similar events): MountVolume.MountDevice failed for volume "inline" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-0140cff45bc3ecdbc --scope -- mount -t xfs -o defaults /dev/nvme1n1 /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-0140cff45bc3ecdbc
Output: Running scope as unit: run-r2e3e07eb3da648abb45fcd8c4151a9a9.scope
mount: /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-0140cff45bc3ecdbc: wrong fs type, bad option, bad superblock on /dev/nvme1n1, missing codepage or helper program, or other error.
```

It seems to me that AWS EBS volume plugin does not support partitions at all.

#### What you expected to happen:
The partition is mounted.

#### How to reproduce it (as minimally and precisely as possible):
Using an in-line volume with this pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: inline
spec:
  containers:
  - name: inline
    image: centos:7
    args:
    - sleep
    - '99999'
    securityContext:
      privileged: true
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/mnt/storage"
      name: inline
  volumes:
  - name: inline
    awsElasticBlockStore:
      fsType: xfs
      volumeID: vol-072b2b73e088c43b5
      partition: 1
```
