### ISSUE TITLE
[CINDER] /kubelet/plugins/kubernetes.io/cinder/ doesn't exist

### ISSUE THREAD

**Issue by rootmout** [kubernetes/kubernetes#100594]
#### What happened:
I try to use cinder volumes in my k8s cluster that is in an openstack cluster.
The volume is correctly created by cinder, the pvc is bound and the pod try to mount the volume that should have `/var/lib/kubelet/pods/<pod-id>/volumes/kubernetes.io~cinder/pvc-<pvc-id>` as path. However, he isn't existing on concerned node, and I get the following error (describe pod): 

```
Mounting command: mount
Mounting arguments:  -o bind /var/lib/kubelet/plugins/kubernetes.io/cinder/mounts/3d8c3492-7e52-44ac-afb0-7af534f98d00 /var/lib/kubelet/pods/258ccfcc-9d2e-4c70-9d0b-e33bed6e01b6/volumes/kubernetes.io~cinder/pvc-33748850-f2d9-4dca-addc-193ce9c521c7
Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/cinder/mounts/3d8c3492-7e52-44ac-afb0-7af534f98d00 does not exist
```

Others pods seems ok, csi-cinder-nodeplugin container has access to /var/lib/kubelet directory.

#### What you expected to happen:
The created schould be present on node to allow my pod to connect to it.

#### How to reproduce it (as minimally and precisely as possible):
Into a k8s cluster that has been created by openstack magnum, run the yaml file below

#### Anything else we need to know?:

My Yaml file:
```
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/cinder

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.19.8
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - mountPath: "/var/www/html"
          name: webroot
  volumes:
    - name: webroot
      persistentVolumeClaim:
        claimName: myclaim

```
(This is just a test ofc, there is nothing interesting to mount the nginx webroot ^^)

#### Environment: 
- Kubernetes version (use `kubectl version`):
 ```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Openstack
- OS (e.g: `cat /etc/os-release`):
```
NAME=Fedora
VERSION="33.20210217.3.0 (CoreOS)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora CoreOS 33.20210217.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='33.20210217.3.0'
```
- Kernel (e.g. `uname -a`):
```
Linux amsterdam-test-lx5tobtlfrbi-node-2 5.10.12-200.fc33.x86_64 #1 SMP Mon Feb 1 02:40:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

Thks for your help!
