### ISSUE TITLE
BUG: pods getting scheduled when any one matchExpressions getting satisfied while defining multiple matchExpressions

### ISSUE THREAD

**Issue by Aqilmirza** [kubernetes/kubernetes#100661]
As per defines in kubernetes documentation [https://v1-19.docs.kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/] that - `If you specify multiple matchExpressions associated with nodeSelectorTerms, then the pod can be scheduled onto a node only if all matchExpressions is satisfied.`

However, pods getting scheduled on nodes even if any one of the "matchExpressions" getting satisfied

Spec using 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: etcdctl
  name: etcdctl
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: etcdctl
  template:
    metadata:
      labels:
        app: etcdctl
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - etcd
            - matchExpressions:
              - key: node.kubernetes.io/role
                operator: In
                values:
                - etcd
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - args:
        - -c
        - 'trap: TERM INT; (while true; do sleep 5m; done) & wait'
        command:
        - sh
        env:
        - name: ETCDCTL_API
          value: "3"
        - name: ETCDCTL_ENDPOINTS
        - name: ETCDCTL_CACERT
          value: /etc/kubernetes/certs/kubernetes_ca.pem
        - name: ETCDCTL_KEY
          value: /etc/kubernetes/certs/etcd_server.key
        - name: ETCDCTL_CERT
          value: /etc/kubernetes/certs/etcd_server.pem
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        image: "{{image}}"
        imagePullPolicy: IfNotPresent
        name: etcdctl
        readinessProbe:
          exec:
            command:
            - etcdctl
            - endpoint
            - status
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/certs
          name: tls-certificates
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      dnsPolicy: ClusterFirst
      hostNetwork: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/kubernetes/certs
          type: ""
        name: tls-certificates
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
```

I don't have any pod with etcd label; however this is still getting scheduled on all workers as they have linux label defined

Kubernetes version using: 1.19

Steps to reproduce:
- Apply above manifest or any manifest with multiple  matchExpressions in nodeSelectorTerms.
- pods will get schedule even if any one will get satisfied 

```
Aqil-MBP:k8s-infrastructure beig$ kubectl --kubeconfig=kubeconfig.yaml get nodes --show-labels
NAME                           STATUS   ROLES    AGE     VERSION              LABELS
ip-10-10-11-107.ec2.internal   Ready    worker   6d4h    v1.19.7              beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=c5.2xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1a,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-10-11-107.ec2.internal,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.kubernetes.io/instance-lifecycle=spot,node.kubernetes.io/instance-type=c5.2xlarge,node.kubernetes.io/role=worker,topology.ebs.csi.aws.com/zone=us-east-1a,topology.kubernetes.io/region=us-east-1,topology.kubernetes.io/zone=us-east-1a
ip-10-10-11-172.ec2.internal   Ready    worker   4d4h    v1.19.7              beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=c5.2xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1a,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-10-11-172.ec2.internal,kubernetes.io/os=linux,node-role.kubernetes.io/worker=,node.kubernetes.io/instance-lifecycle=spot,node.kubernetes.io/instance-type=c5.2xlarge,node.kubernetes.io/role=worker,topology.ebs.csi.aws.com/zone=us-east-1a,topology.kubernetes.io/region=us-east-1,topology.kubernetes.io/zone=us-east-1a
ip-10-10-11-40.ec2.internal    Ready    <none>   4d1h    v1.19.6-eks-49a6c0   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=c5.2xlarge,beta.kubernetes.io/os=windows,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1a,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-10-11-40.ec2.internal,kubernetes.io/os=windows,node.kubernetes.io/instance-type=c5.2xlarge,node.kubernetes.io/windows-build=10.0.17763,topology.kubernetes.io/region=us-east-1,topology.kubernetes.io/zone=us-east-1a
```

**Comment by tanjing2020** [comment]
Reference use case： TestNodeAffinityPriority
multiple nodeSelectorTerms：then the pod can be scheduled onto a node if one of the nodeSelectorTerms can be satisfied
~~
name: "Pod with multiple NodeSelectorTerms ORed in affinity, matches the node's labels and will schedule onto the node",
			pod: &v1.Pod{
				Spec: v1.PodSpec{
					Affinity: &v1.Affinity{
						NodeAffinity: &v1.NodeAffinity{
							RequiredDuringSchedulingIgnoredDuringExecution: &v1.NodeSelector{
								NodeSelectorTerms: []v1.NodeSelectorTerm{
									{
										MatchExpressions: []v1.NodeSelectorRequirement{
											{
												Key:      "foo",
												Operator: v1.NodeSelectorOpIn,
												Values:   []string{"bar", "value2"},
											},
										},
									},
									{
										MatchExpressions: []v1.NodeSelectorRequirement{
											{
												Key:      "diffkey",
												Operator: v1.NodeSelectorOpIn,
												Values:   []string{"wrong", "value2"},
											},
										},
									},
								},
							},
						},
					},
				},
			},

~~

multiple matchExpressions：the pod can be scheduled onto a node only if all matchExpressions is satisfied
~~
name: "Pod with multiple matchExpressions ANDed that doesn't match the existing node",
			pod: &v1.Pod{
				Spec: v1.PodSpec{
					Affinity: &v1.Affinity{
						NodeAffinity: &v1.NodeAffinity{
							RequiredDuringSchedulingIgnoredDuringExecution: &v1.NodeSelector{
								NodeSelectorTerms: []v1.NodeSelectorTerm{
									{
										MatchExpressions: []v1.NodeSelectorRequirement{
											{
												Key:      "GPU",
												Operator: v1.NodeSelectorOpExists,
											}, {
												Key:      "GPU",
												Operator: v1.NodeSelectorOpIn,
												Values:   []string{"AMD", "INTER"},
											},
										},
									},
								},
							},
						},
					},
				},
			},
~~

**Comment by CaoDonghui123** [comment]
you need to change the yaml file to this

```
 spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - etcd
              - key: node.kubernetes.io/role
                operator: In
                values:
                - etcd
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
```
