### ISSUE TITLE
conntrack entries not cleared when switching service endpoints

### ISSUE THREAD

**Issue by wdec** [kubernetes/kubernetes#100698]
#### What happened:

When running a single-leader/follower pod-setup front-ended by a k8s service, upon the switchover of the leader pod corresponding to a change in the service endpoints, established TCP sessions to the leader do not get disconnected. The conntract rules for the established TCP sessions are not cleared.
This is a serious problem for leader/follower based setups with long living sessions.

#### What you expected to happen:

Upon a change of the end-point, all iptables translation rules for the service get flushed (or at least those for the removed endpoint)

#### How to reproduce it (as minimally and precisely as possible):

Best done manually:
1. Create 2 pods A and B running any TCP test service, 
2. Create service X with endpoint X' selector, adding only pod IP A into the endpoint.
3. Establish and maintain open a TCP connection to service X from another client pod (eg telnet). 
4. Verify that the TCP session is open in pod A using netstat -atn
5. Delete the endpoint X` or service X.
6. Create service X with endpoint X' mapping, adding only pod IP B into the endpoint.
7. Establish another session from the client pod to X.

After the above, perform step 4 in pod A and B. The expected result is that the 1st TCP session should not be visible in pod A and instead pod B should now have 2 TCP sessions. The result is that the 1st TCP remains connected to pod A, while the 2nd goes to pod B.

The 1st session is also visible on the host visible using conntrack -L

#### Environment:
- Kubernetes version (use `kubectl version`):
- 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

Cisco UCS 220B

- OS (e.g: `cat /etc/os-release`):

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):

Linux 172-25-87-82-hybrid.cisco.com 4.15.0-137-generic #141-Ubuntu SMP Fri Feb 19 13:46:27 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

none

- Network plugin and version (if this is a network-related bug):

Calico

- Others:

The setup is a 3 node cluster. Issue is seen irrespective of whether IPVS and IPTables mode is used. Pod A and B are on different nodes. Client pod is on the same node as Pod A, but pod location has not been observed to matter.

Some sample spec files:

Service.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    cluster-name: postgres
  name: postgres
  namespace: default
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Endpoint.yaml
```
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  labels:
    app: postgres
    cluster-name: postgres
subsets:
- addresses:
  - ip: <pod address>
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
```
