### ISSUE TITLE
kubeadm v1.20.5 generate wrong kube-proxy configmap on rhel 8.2

### ISSUE THREAD

**Issue by mzyfree** [kubernetes/kubernetes#100767]
#### What happened:
run command to deploy v1.20.5 kube-proxy:
```
kubeadm init  --config=./kubeadm_config.yml phase addon kube-proxy 
```
kubeadm config file
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: "v1.20.5"
controlPlaneEndpoint: "192.168.205.100"
imageRepository: "matrix-registry.h3c.com:8088/matrix"
etcd:
 external:
  endpoints:
  - "http://192.168.205.30:2379"
apiServer:
  certSANs:
  - 192.168.205.100
  - 127.0.0.1
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster
  - kubernetes.default.svc.cluster.local
  extraArgs:
    advertise-address: "192.168.205.100"
    token-auth-file: /etc/kubernetes/pki/token.csv
    service-node-port-range: 1-65535
    v: "2"
    logtostderr: "true"
    tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  extraVolumes:
  - name: kube-apiserver-log
    hostPath: /var/log/matrix-diag/Matrix/kube-apiserver
    mountPath: /var/log/matrix-diag/Matrix/kube-apiserver
    pathType: DirectoryOrCreate
    readOnly: false
networking:
  podSubnet: 177.177.0.0/16
  serviceSubnet: 10.96.0.0/16
controllerManager:
  extraArgs:
    v: "4"
    logtostderr: "true"
    experimental-cluster-signing-duration: "1752000h0m0s"
  extraVolumes:
  - name: kube-controller-manager-log
    hostPath: /var/log/matrix-diag/Matrix/kube-controller-manager
    mountPath: /var/log/matrix-diag/Matrix/kube-controller-manager
    pathType: DirectoryOrCreate
    readOnly: false
scheduler:
  extraArgs:
    v: "4"
    logtostderr: "true"
  extraVolumes:
  - name: kube-scheduler-log
    hostPath: /var/log/matrix-diag/Matrix/kube-scheduler
    mountPath: /var/log/matrix-diag/Matrix/kube-scheduler
    pathType: DirectoryOrCreate
    readOnly: false
dns:
  type: CoreDNS
  imageTag: 1.6.9
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "192.168.205.100"

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 300
```
kube-proxy configmap has never been init.
```
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    bindAddressHardFail: false
    clientConnection:
      acceptContentTypes: ""
      burst: 0
      contentType: ""
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 0
    clusterCIDR: 177.177.0.0/16
    configSyncPeriod: 0s
    conntrack:
      maxPerCore: null
      min: null
      tcpCloseWaitTimeout: null
      tcpEstablishedTimeout: null
    detectLocalMode: ""
    enableProfiling: false
    healthzBindAddress: ""
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: null
      minSyncPeriod: 0s
      syncPeriod: 0s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: ""
      strictARP: false
      syncPeriod: 0s
      tcpFinTimeout: 0s
      tcpTimeout: 0s
      udpTimeout: 0s
    kind: KubeProxyConfiguration
    metricsBindAddress: ""
    mode: ""
    nodePortAddresses: null
    oomScoreAdj: null
    portRange: ""
    showHiddenMetricsForVersion: ""
    udpIdleTimeout: 0s
    winkernel:
      enableDSR: false
      networkName: ""
      sourceVip: ""
  kubeconfig.conf: |-
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://192.168.205.100:6443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
```
And the kube-proxy can not build any iptable rules between service and endpoint even if there exists some backend endpoints.
endpoints
```
[root@node30 k8s]# kubectl get ep -A
NAMESPACE     NAME                     ENDPOINTS                                                    AGE
default       kubernetes               192.168.205.100:6443                                         16h
kube-system   grafana-service          177.177.143.136:3000                                         16h
kube-system   heapster                 177.177.143.135:8082                                         16h                                                      16h
kube-system   influxdb-relay-service   177.177.143.134:9096                                         16h
kube-system   influxdb-service         177.177.143.132:8086                                         16h
kube-system   influxdb-service1        177.177.143.132:8086                                         16h
kube-system   kube-dns                 177.177.143.129:53,177.177.143.129:53,177.177.143.129:9153   16h
kube-system   kubernetes-dashboard     177.177.143.130:8443                                         16h
```
But no iptable rules:
```
[root@node30 k8s]# iptables -nvL KUBE-SERVICES -t filter
Chain KUBE-SERVICES (2 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 REJECT     udp  --  *      *       0.0.0.0/0            10.96.0.10           /* kube-system/kube-dns:dns has no endpoints */ udp dpt:53 reject-with icmp-port-unreachable
    0     0 REJECT     tcp  --  *      *       0.0.0.0/0            10.96.0.10           /* kube-system/kube-dns:dns-tcp has no endpoints */ tcp dpt:53 reject-with icmp-port-unreachable
    0     0 REJECT     tcp  --  *      *       0.0.0.0/0            10.96.0.10           /* kube-system/kube-dns:metrics has no endpoints */ tcp dpt:9153 reject-with icmp-port-unreachable
    0     0 REJECT     tcp  --  *      *       0.0.0.0/0            10.96.25.206         /* kube-system/influxdb-service1:db has no endpoints */ tcp dpt:8086 reject-with icmp-port-unreachable
    0     0 REJECT     tcp  --  *      *       0.0.0.0/0            10.96.109.0          /* kube-system/influxdb-service:db has no endpoints */ tcp dpt:8086 reject-with icmp-port-unreachable
```

#### What you expected to happen:
kube-proxy is ok and function well.

#### How to reproduce it (as minimally and precisely as possible):
use the command and config file above.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
[root@node30 k8s]# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
[root@node30 k8s]# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
```
- Kernel (e.g. `uname -a`):
```
[root@node30 k8s]# uname -a
Linux node30 4.18.0-193.el8.x86_64 #1 SMP Fri Mar 27 14:35:58 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
calico:v3.15.1
multu:v3.2.0
- Others:
