### ISSUE TITLE
Kubernetes CronJob - Multiple CronJob configuration is not working

### ISSUE THREAD

**Issue by abhihome-github** [kubernetes/kubernetes#100974]
I have to run two CronJobs in Kubernetes (AWS-EKS) and I have below configuration. When I apply the template, only one CronJob is getting created. The one that gets created is always the second one. So it looks like the first one is getting overwritten by the second. I am unable to figure out what am I doing wrong.
```
# Source: deploy-k8s-app/templates/multicron.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: commercial
spec:
  schedule: '5/15 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      activeDeadlineSeconds: 900
      template:
        metadata:
          labels:
            app: my-app
          name: my-app
          namespace: commercial
        spec:
          containers:
          - env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/my-app"
            - name: IS_JACOCO_ENABLED
              value: "false"
            - name: SPRING_PROFILES_ACTIVE
              value: "int-dc4"
            - name: METRICS_ADDRESS
              value: "NA"
            - name: APP_MODULE
              value: "expand"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms256M -Xmx512M"
            image: "xxxxx.dkr.ecr.us-east-1.amazonaws.com/my-ecr:my-app-latest-10"
            imagePullPolicy: IfNotPresent
            name: my-app
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            resources:
              limits:
                cpu: 160m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
            - name: apps-logs
              mountPath: /var/log/containers
            - name: fluentdconf
              mountPath: /fluentd/etc
          - name: fluentd
            image: fluent/fluentd-kubernetes-daemonset:v1.11.2-debian-cloudwatch-1.0
            env:
            - name: REGION
              value: us-east-1
            - name: AWS_REGION
              value: us-east-1
            - name: CLUSTER_NAME
              value: MY-EKS-Cluster
            - name: CI_VERSION
              value: "k8s/1.0.1"
            - name: LOG_GROUP_NAME
              value: /aws/containerinsights/MY-EKS-Cluster/springapp
            resources:
              limits:
                cpu: 160m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
            - name: fluentdconf
              mountPath: /fluentd/etc
            - name: apps-logs
              mountPath: /var/log/containers
          volumes:
            - name: fluentdconf
              configMap:
                name: fluentd-spring-config
            - name: apps-logs
              emptyDir: {}
            - name: my-app-shared
              emptyDir: {}
          restartPolicy: OnFailure
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: my-app
  name: my-app-addl
  namespace: commercial
spec:
  schedule: '15/30 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      activeDeadlineSeconds: 1800
      template:
        metadata:
          labels:
            app: my-app
          name: my-app
          namespace: commercial
        spec:
          containers:
          - env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/my-app"
            - name: IS_JACOCO_ENABLED
              value: "false"
            - name: SPRING_PROFILES_ACTIVE
              value: "int-dc4"
            - name: METRICS_ADDRESS
              value: "NA"
            - name: APP_MODULE
              value: "expand"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms256M -Xmx512M"
            image: "xxxxx.dkr.ecr.us-east-1.amazonaws.com/my-ecr:my-app-latest-10"
            imagePullPolicy: IfNotPresent
            name: my-app
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            resources:
              limits:
                cpu: 160m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
            - name: apps-logs
              mountPath: /var/log/containers
            - name: fluentdconf
              mountPath: /fluentd/etc
          - name: fluentd
            image: fluent/fluentd-kubernetes-daemonset:v1.11.2-debian-cloudwatch-1.0
            env:
            - name: REGION
              value: us-east-1
            - name: AWS_REGION
              value: us-east-1
            - name: CLUSTER_NAME
              value: MY-EKS-Cluster
            - name: CI_VERSION
              value: "k8s/1.0.1"
            - name: LOG_GROUP_NAME
              value: /aws/containerinsights/MY-EKS-Cluster/springapp
            resources:
              limits:
                cpu: 160m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
            - name: fluentdconf
              mountPath: /fluentd/etc
            - name: apps-logs
              mountPath: /var/log/containers
          volumes:
            - name: fluentdconf
              configMap:
                name: fluentd-spring-config
            - name: apps-logs
              emptyDir: {}
            - name: my-app-shared
              emptyDir: {}
          restartPolicy: OnFailure
```
```
kubectl apply -f multicron.yaml
cronjob.batch/my-app-addl created
```

(Expectation: Two CronJobs to be created. Actual: Only one is created, and that is the second one)

```
kubectl get cronjob -n commercial
NAME            SCHEDULE        SUSPEND   ACTIVE   LAST SCHEDULE   AGE
my-app-addl     15/30 * * * *   False     0        <none>          9s
```

(Expectation: Two CronJobs to be created. Actual: Only one is created, and that is the second one)

Thanks! Abhilash

**Comment by tiagomeireles** [comment]
YAML uses three dashes (`---`) to separate documents. The following should work.

i.e

```
---
# Source: deploy-k8s-app/templates/multicron.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: commercial
spec:
  schedule: '5/15 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      activeDeadlineSeconds: 900
      template:
        metadata:
          labels:
            app: my-app
          name: my-app
          namespace: commercial
        spec:
          containers:
          - env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/my-app"
            - name: IS_JACOCO_ENABLED
              value: "false"
            - name: SPRING_PROFILES_ACTIVE
              value: "int-dc4"
            - name: METRICS_ADDRESS
              value: "NA"
            - name: APP_MODULE
              value: "expand"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms256M -Xmx512M"
            image: "xxxxx.dkr.ecr.us-east-1.amazonaws.com/my-ecr:my-app-latest-10"
            imagePullPolicy: IfNotPresent
            name: my-app
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            resources:
              limits:
                cpu: 160m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
            - name: apps-logs
              mountPath: /var/log/containers
            - name: fluentdconf
              mountPath: /fluentd/etc
          - name: fluentd
            image: fluent/fluentd-kubernetes-daemonset:v1.11.2-debian-cloudwatch-1.0
            env:
            - name: REGION
              value: us-east-1
            - name: AWS_REGION
              value: us-east-1
            - name: CLUSTER_NAME
              value: MY-EKS-Cluster
            - name: CI_VERSION
              value: "k8s/1.0.1"
            - name: LOG_GROUP_NAME
              value: /aws/containerinsights/MY-EKS-Cluster/springapp
            resources:
              limits:
                cpu: 160m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
            - name: fluentdconf
              mountPath: /fluentd/etc
            - name: apps-logs
              mountPath: /var/log/containers
          volumes:
            - name: fluentdconf
              configMap:
                name: fluentd-spring-config
            - name: apps-logs
              emptyDir: {}
            - name: my-app-shared
              emptyDir: {}
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: my-app
  name: my-app-addl
  namespace: commercial
spec:
  schedule: '15/30 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      activeDeadlineSeconds: 1800
      template:
        metadata:
          labels:
            app: my-app
          name: my-app
          namespace: commercial
        spec:
          containers:
          - env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/my-app"
            - name: IS_JACOCO_ENABLED
              value: "false"
            - name: SPRING_PROFILES_ACTIVE
              value: "int-dc4"
            - name: METRICS_ADDRESS
              value: "NA"
            - name: APP_MODULE
              value: "expand"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms256M -Xmx512M"
            image: "xxxxx.dkr.ecr.us-east-1.amazonaws.com/my-ecr:my-app-latest-10"
            imagePullPolicy: IfNotPresent
            name: my-app
            ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            resources:
              limits:
                cpu: 160m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
            - name: apps-logs
              mountPath: /var/log/containers
            - name: fluentdconf
              mountPath: /fluentd/etc
          - name: fluentd
            image: fluent/fluentd-kubernetes-daemonset:v1.11.2-debian-cloudwatch-1.0
            env:
            - name: REGION
              value: us-east-1
            - name: AWS_REGION
              value: us-east-1
            - name: CLUSTER_NAME
              value: MY-EKS-Cluster
            - name: CI_VERSION
              value: "k8s/1.0.1"
            - name: LOG_GROUP_NAME
              value: /aws/containerinsights/MY-EKS-Cluster/springapp
            resources:
              limits:
                cpu: 160m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 256Mi
            volumeMounts:
            - name: fluentdconf
              mountPath: /fluentd/etc
            - name: apps-logs
              mountPath: /var/log/containers
          volumes:
            - name: fluentdconf
              configMap:
                name: fluentd-spring-config
            - name: apps-logs
              emptyDir: {}
            - name: my-app-shared
              emptyDir: {}
          restartPolicy: OnFailure
```
