### ISSUE TITLE
kubectl 1.21 no ingress

### ISSUE THREAD

**Issue by Raffa50** [kubernetes/kubernetes#100971]
#### What happened: trying to deploy an ingress.yaml with kubectl apply -f ingress.yaml
got error: **no matches for kind "Ingress" in version "networking.k8s.io/v1"**

#### How to reproduce it (as minimally and precisely as possible):
deploy an ingress.yaml:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clientweb-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
spec:
  rules:
    - host: ethernial.com
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: clientweb-service
                port: 
                  number: 80
  tls:
  - hosts:
    - ethernial.com
    - www.ethernial.com
    secretName: ethernial-tls-secret
```

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.0
- Cloud provider or hardware configuration: Premises
- OS (e.g: `cat /etc/os-release`): Windows10
- Kernel (e.g. `uname -a`): NA
- Install tools: kubectl, kubentates installed on windows10 docker wsl2
- Network plugin and version (if this is a network-related bug): ingress-nginx, metallb
