### ISSUE TITLE
Cronjob's successfulJobsHistoryLimit has no effect when launching job by hand

### ISSUE THREAD

**Issue by hatharom** [kubernetes/kubernetes#100927]
Tested with kubernetes server+client versions of 1.19.3 and 1.20.0

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  namespace: myjob
spec:
  schedule: "* * 10 * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
`kubectl create -f mycron.yaml`

When the cronjob triggered by the crontab then it creates the job and removes it after completion successfully.

However when creating the job manually:

`kubectl create job -n myjob --from=cronjob/hello hello-job`

**Expected:**
After completion the job should be removed

**Actual**
The job remains there:

```
NAME            COMPLETIONS   DURATION   AGE
hello-job           1/1           2s     6m
```

 The logs doesnt show any suspicious, except that this line is missing from the kube controller:      
` 1 event.go:291] "Event occurred" object="myjob/hello" kind="CronJob" apiVersion="batch/v1beta1" type="Normal" reason="SuccessfulDelete" message="Deleted job hello-job"`

**Comment by wzshiming** [comment]
``` log
NAME                         READY   STATUS              RESTARTS   AGE
pod/hello-1617948480-jfc8g   0/1     ContainerCreating   0          0s
pod/hello-job-rc4dm          0/1     Completed           0          106s
```

The `Pod` created by `CronJob` has a different naming rule from the `Pod` created by manually

**Comment by wzshiming** [comment]
This should be a feature, it seems reasonable.

**Comment by hatharom** [comment]
Thanks your answer. So it is not supported at the moment.

It seems ownerReference has been set, but controller not.

```
  ownerReferences:
  - apiVersion: batch/v1beta1
    kind: CronJob
    name: hello
    uid: bb567067-3bd4-4e5f-9ca2-071010013727
```

However it seems to work when I use a very old client version (namely 1.15.5)
Described the problem in more detail: 
https://stackoverflow.com/questions/67007089/kubernetes-doesnt-remove-completed-jobs-for-a-cronjob
