### ISSUE TITLE
Empty pod containerStatuses.lastState field

### ISSUE THREAD

**Issue by ns-rwong** [kubernetes/kubernetes#101044]
#### What happened:
we noticed that it's possible for a pod to have a restarted container, but an empty (`{}`) `.status.containerStatuses.lastState` field.  here is an example (notice _restartCount: 4_ but _lastState: {}_):
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-04-12T19:36:07Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-04-12T19:46:46Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-04-12T19:46:46Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-04-12T19:36:07Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://d713579d5f94d6e81348d1e603b4e09f93cb6efce77f326aaf452ced0d2347bc
    image: node:15.14.0-alpine3.10
    imageID: docker-pullable://node@sha256:379de8e7f044780ac6bb53500923ce5e702c7384b470eb9f862d5a7d10e629cf
    lastState: {}
    name: exit
    ready: true
    restartCount: 4
    started: true
    state:
      running:
        startedAt: "2021-04-12T19:46:45Z"
  hostIP: ...
  phase: Running
  podIP: ...
  podIPs:
  - ip: ...
  qosClass: BestEffort
  startTime: "2021-04-12T19:36:07Z"
```

#### What you expected to happen:
i expected that whenever a pod container has restarted, the associated `.status.containerStatuses.lastState` field to always have a value ( indicating details like exit code, etc) like the following:
```
 containerStatuses:
  - containerID: docker://3cf73d2cc385993717a8d40bbb3487d0a9f8951ac6cbf99f250859bd2a57dcd1
    image: node:15.14.0-alpine3.10
    imageID: docker-pullable://node@sha256:379de8e7f044780ac6bb53500923ce5e702c7384b470eb9f862d5a7d10e629cf
    lastState:
      terminated:
        containerID: docker://3812625be37b5ef48b2387e1d56ced520b55c60733af845a0b49d6ebc0007563
        exitCode: 0
        finishedAt: "2021-04-12T19:45:26Z"
        reason: Completed
        startedAt: "2021-04-12T19:45:16Z"
    name: exit
    ready: true
    restartCount: 3
    started: true
    state:
      running:
        startedAt: "2021-04-12T19:45:58Z"
```

#### How to reproduce it (as minimally and precisely as possible):
It can be hard to reproduce this but I was able to do so a few times with the following:
1. create a few replicasets that all have a single container that can be triggered to exit 0.  i used a node server that exits 0 whenever it receives a HTTP request: 
```
      containers:
      - name: exit
        image: node:15.14.0-alpine3.10
        imagePullPolicy: IfNotPresent
        command: ["node", "-e", "const http=require('http'); http.createServer( (req, res) => {res.end(); process.exit(0)}).listen(8080)"]
```

2. in a continuous loop, trigger the pods to exit.  i just used a few shell scripts issuing a HTTP requests to my node servers.
3. check for pods that have containers with a restartCount > 0 but have an empty lastState.  i used:
```
kubectl get pods -o json  | jq '.items[] | select((.status.containerStatuses[0].restartCount > 0) and (.status.containerStatuses[0].lastState == {})) | .status.containerStatuses | .meta.name'
```

#### Anything else we need to know?:
The example output above shows this happening with a restartCount > 1 (3 and 4), but we have found that it happens even if the restartCount is only 1. 

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14", GitCommit:"f238f5142728be4033c37aa0ad69bf806090beae", GitTreeState:"clean", BuildDate:"2020-11-11T13:11:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-gke.2800", GitCommit:"4ef0543cc59f482d118ae33397108118ec80d447", GitTreeState:"clean", BuildDate:"2021-02-20T01:42:15Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
GKE

**Comment by pacoxu** [comment]
Actually, the EOL of v1.17 is 2021-01-30.
Can this be reproduced in 1.18+?
/sig node

**Comment by ns-rwong** [comment]
> Actually, the EOL of v1.17 is 2021-01-30.
> Can this be reproduced in 1.18+?
> /sig node

@pacoxu 
yes, i can reproduce this in v1.18.17-gke.100

**Comment by fedebongio** [comment]
It sounds more like sig node
/remove-sig api-machinery

**Comment by SergeyKanzhelev** [comment]
@ns-rwong I understand this is the bug. Are you trying to troubleshoot the container failure? Are you following https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/ or some other flow? Have you been able to get the exit code from logs as a workaround?

Also related PR that will make things easier: https://github.com/kubernetes/kubernetes/pull/99880

**Comment by ns-rwong** [comment]
hey @SergeyKanzhelev, we have a controller that is trying to perform an action based on the exit code.  i'll look at https://github.com/kubernetes/kubernetes/pull/99880 but is the container status field meant to be reliable?

**Comment by Dragoncell** [comment]
@ns-rwong Do you still have the issues for the container exit status in latest GKE version ? 

I am try to reproducing it in 1.19.9-gke.1900, but not able to. 
Below were reproduction steps I did:  
Steps 1. create the 1.19 cluster 
Steps 2: create the deployment of below spec:
```
spec:
      containers:
      - name: exit
        image: node:15.14.0-alpine3.10
        imagePullPolicy: IfNotPresent 
        command: ["node", "-e", "const http=require('http'); http.createServer( (req, res) => {res.end(); process.exit(0)}).listen(8080)"]
        ports:
        - containerPort: 8080
```

step 3: ssh into node, and do http curl connection to pod_ip:port and repeated several times

step 4: observe the pod status, but the lastState terminated status was always there and containers the exit code.
