### ISSUE TITLE
Double dollar signs in a container's args or env section are incorrectly treated as escape characters

### ISSUE THREAD

**Issue by MartinKanters** [kubernetes/kubernetes#101137]
#### What happened:
I'm trying to pass two dollar sign in the args or env fields of a pod, but they are reduced to one dollar sign. 

#### What you expected to happen:
The two dollar signs should be propagated to the container.

#### How to reproduce it (as minimally and precisely as possible):
1. Apply this pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dollar-dollar-example
  namespace: default
spec:
  containers:
    - name: client-container
      image: k8s.gcr.io/busybox
      env: 
      - name: DOLLAR_DOLLAR_ENV
        value: "$$"
      command: ["sh", "-c"]
      args: 
      - "echo 'dollar dollar from args: $$';
         echo 'dollar dollar from env:' $DOLLAR_DOLLAR_ENV"
```
2. Check logs
```
kubectl logs dollar-dollar-example
dollar dollar from args: $
dollar dollar from env: $
```
#### Anything else we need to know?:
Kubernetes can [expand variables](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#container-v1-core) used in the args and env section with the following syntax: $(var). $$(var) is a way of escaping this variable, resulting in it not being expanded. I don't think '$$' should be regarded as something to be escaped, though.
Here's the [expansion code](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/third_party/forked/golang/expansion/expand.go#L38), I believe.

I can take a shot at fixing it, but I first want to know for sure that this is not intended behavior.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-22T19:05:30Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"14f897abdc7b57f0850da68bd5959c9ee14ce2fe", GitTreeState:"clean", BuildDate:"2021-01-22T17:29:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): 
Ubuntu over WSL
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
```
- Kernel (e.g. `uname -a`):
`Linux MartinK 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Other info:
This issue was found during debugging what we first thought to be a Tekton issue: https://github.com/tektoncd/pipeline/issues/3871.
