### ISSUE TITLE
Kubectl kustomize conundrum

### ISSUE THREAD

**Issue by Sabyasachi2k** [kubernetes/kubernetes#101199]
So we are using kustomize to patch a yaml file and with kubectl version 1.20.0 it works fine . the moment we use with kubectl 1.21 it gives the error

command executed
kubectl kustomize > test.yaml

```
Error: no matches for IdId ~G_v1_ServiceAccount|reloader|reloader-reloader; failed to find unique target for patch ~G_v1_ServiceAccount|reloader-reloader
```
here is are all the files
resource.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-namespace: "default"
    meta.helm.sh/release-name: "reloader"
  labels:
    app: reloader-reloader
    chart: "reloader-v0.0.77"
    release: "reloader"
    heritage: "Tiller"
    app.kubernetes.io/managed-by: "Tiller"
  name: reloader-reloader

---
```
patch.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-namespace: "default"
    meta.helm.sh/release-name: "reloader"
  labels:
    app: reloader-reloader
    release: "reloader"
  name: reloader-reloader
  namespace: reloader
---
```
here is the kustomization file
kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader
resources:
  - resource.yaml
patchesStrategicMerge:
  - patches.yaml
```

Has something changed? Or are we totally off

**Comment by navist2020** [comment]
Hi @Sabyasachi2k ,I found this error is becaz of that your `resource.yaml` and `patches.yaml` belong to different namespace，one is default and the other is reloader. But in the code it seems not allow to transform NS attribute.
https://github.com/kubernetes/kubernetes/blob/f1e51ceb3c58da272bc0fc68e200db6fd12121dd/vendor/sigs.k8s.io/kustomize/api/resid/resid.go#L95-L97
As you can see, you must ensure that the NS and GVK of the two files are the same.
@neolit123  Do we want the NS to be unpatch in kustomize?

**Comment by Sabyasachi2k** [comment]
Hi @navist2020 ,
OK so that means we cannot patch the ns along with the other elements? Would this allow patching the ns in case of ClusterBinding? If so then I guess we can live with that.
we could do kubectl kustomize -n reloader > test.yaml

**Comment by neolit123** [comment]
> So we are using kustomize to patch a yaml file and with kubectl version 1.20.0 it works fine . the moment we use with kubectl 1.21 it gives the error

+ 

> @neolit123 Do we want the NS to be unpatch in kustomize?

i don't know why this behavior changed.

can you pass `target` for a patch?

```
target:
  kind: ServiceAccount
```

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md

**Comment by Sabyasachi2k** [comment]
> > So we are using kustomize to patch a yaml file and with kubectl version 1.20.0 it works fine . the moment we use with kubectl 1.21 it gives the error
> 
> `+`
> 
> > @neolit123 Do we want the NS to be unpatch in kustomize?
> 
> i don't know why this behavior changed.
> 
> can you pass `target` for a patch?
> 
> ```
> target:
>   kind: ServiceAccount
> ```
> 
> https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md

Wonder if that is even possible using patchesStrategicMerge option. I am not sure it is though but could be wrong

**Comment by navist2020** [comment]
Yes,if you modify the `kustomization.yaml` as follow:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloader
resources:
- resource.yaml
patches:
- path: patches.yaml
  target:
    kind: ServiceAccount
```
This can run normally in my cluster.
