### ISSUE TITLE
DaemonSet controller can adopt ControllerRevisions in other namespaces

### ISSUE THREAD

**Issue by evertrain** [kubernetes/kubernetes#101249]
#### What happened:
DaemonSet A can adopt orphan ControllerRevision resources of Daemonset B in other namespaces.

It can happen if DaemonSet A and B has the same "Spec.Selector" field.

#### What you expected to happen:
DaemonSet Controller should only adopt ControllerRevision in it's own namespace.

#### How to reproduce it (as minimally and precisely as possible):
1. create DaemonSet testns1/test-ds-in-testns1

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-ds-in-testns1
  namespace: testns1
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
```

2.  create DaemonSet testns2/test-ds-in-testns2, having same spec.selector with testns1/test-ds-in-testns1

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-ds-in-testns2
  namespace: testns2
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
```

3.  kubectl delete ds test-ds-in-testns1 -n testns1 --cascade=false
4.  kubectl label ds  test-ds-in-testns2 -n testns2 a=1 // to ensure this ds enqueue
5.  kubectl get controllerrevision -n testns1 -o wide
```
NAME                            CONTROLLER                          REVISION   AGE
test-ds-in-testns1-796898b788   daemonset.apps/test-ds-in-testns2   1          2m24s
```

#### Anything else we need to know?:
If this situation meets the case which is fixed by this [PR](https://github.com/kubernetes/kubernetes/pull/92743),  
unexpected deletions of A's children(Pods, ControllerRevisions and so on)  may happen, which can be much serious.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.16.3-594
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
