### ISSUE TITLE
validatingwebhookconfigurations can't set ownerReferences

### ISSUE THREAD

**Issue by NovaHe** [kubernetes/kubernetes#101220]
#### What happened:

I want to delete ValidatingWebhookConfiguration when ns is deleted. so I set  ValidatingWebhookConfigurationconfig/webhook.serving.knative.dev's `ownerReferences` to namespace/serving-tests  . but validatingwebhookconfigurations can't set ownerReferences

/kind bug
#### What you expected to happen:

Delete ValidatingWebhookConfiguration when ns is deleted

#### How to reproduce it (as minimally and precisely as possible):
1. create namespace serving-tests and get namespace/serving-tests uid
```bash
kubectl create namespace serving-tests
kubectl get namespace serving-tests -o yaml |grep uid
```
2. `kubectl apply -f test.yaml`the following configuration(**modify namespace/serving-tests uid**)：
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  generation: 5
  labels:
    serving.knative.dev/release: devel
  name: config.webhook.serving.knative.dev
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Namespace
    name: serving-tests
    uid: abd4a354-d02c-40f6-80bb-95238080eaad  # modify namespace/serving-tests uid
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNEekNDQWNHZ0F3SUJBZ0lSQVBmN1VNV0JMTk9tMkZBN1RUQlFYMzh3QlFZREsyVndNRHd4RkRBU0JnTlYKQkFvVEMydHVZWFJwZG1VdVpHVjJNU1F3SWdZRFZRUURFeHQzWldKb2IyOXJMbXR1WVhScGRtVXRjMlZ5ZG1sdQpaeTV6ZG1Nd0hoY05NakV3TkRFMk1UQXdNakkzV2hjTk1qRXdOREl6TVRBd01qSTNXakE4TVJRd0VnWURWUVFLCkV3dHJibUYwYVhabExtUmxkakVrTUNJR0ExVUVBeE1iZDJWaWFHOXZheTVyYm1GMGFYWmxMWE5sY25acGJtY3UKYzNaak1Db3dCUVlESzJWd0F5RUFCMHhyM1BnSUZoOUJKTVNxeGd1OGRyMGt6TlJyRkQxc25KY0hYdjBsOTdpagpnZGN3Z2RRd0RnWURWUjBQQVFIL0JBUURBZ0tFTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGCkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlN5U3gxTk5DODhTT2hEMm5LbXp4LzEKNmtiZG1UQnpCZ05WSFJFRWJEQnFnZ2QzWldKb2IyOXJnaGQzWldKb2IyOXJMbXR1WVhScGRtVXRjMlZ5ZG1sdQpaNEliZDJWaWFHOXZheTVyYm1GMGFYWmxMWE5sY25acGJtY3VjM1pqZ2lsM1pXSm9iMjlyTG10dVlYUnBkbVV0CmMyVnlkbWx1Wnk1emRtTXVZMngxYzNSbGNpNXNiMk5oYkRBRkJnTXJaWEFEUVFEdXB5dmt6bk5YZzN3V2NETzkKaUNjM2cvTzgvclBDTERZeGYzV0hIZDBYRUUzNlE1Slh1L293SHFadGVQK0tBVXFRc3RpNUNnRkl5QTQ4QnQ3WgptejRCCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook
      namespace: knative-serving
      path: /config-validation
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: config.webhook.serving.knative.dev
  namespaceSelector:
    matchExpressions:
    - key: serving.knative.dev/release
      operator: Exists
  objectSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configmaps/*
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 10
```
3. cat `validatingwebhookconfiguration`，the validatingwebhookconfiguration is created successfully, but `ownerReferences` the field is empty

```bash
kubectl get validatingwebhookconfiguration config.webhook.serving.knative.dev -o json | jq .metadata.ownerReferences
```

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux master1 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:
