### ISSUE TITLE
Pod in terminating state is still receiving requests

### ISSUE THREAD

**Issue by NavindrenBaskaran** [kubernetes/kubernetes#101219]
#### What happened:
As stated in the documentation [here](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) pods that are terminating will not be receiving traffic.

What we're seeing here is completely opposite, in where the pods which are terminating are still receiving requests.

#### What you expected to happen:
Pods which are terminating should gradually stop receiving requests.

#### How to reproduce it (as minimally and precisely as possible):

1. Deploy a server.
```
apiVersion: v1
kind: Service
metadata:
  name: <redacted>
  labels:
    app.kubernetes.io/name: <redacted>
    app.kubernetes.io/component: server
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: <redacted>
    app.kubernetes.io/component: server
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: <redacted>
  labels:
    app.kubernetes.io/name: <redacted>
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: <redacted>
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: <redacted>
        app.kubernetes.io/component: server
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "2"
        searches:
          - svc.cluster.local
      terminationGracePeriodSeconds: 600
      containers:
        - name: server
          imagePullPolicy: IfNotPresent
          image: <redacted>:latest
          lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh", "-c", "sleep 600;bundle exec passenger stop"]
          command: ["bundle", "exec", "passenger", "start"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /okcomputer
              port: http
          resources:
            requests:
              cpu: 2
              memory: 6.75Gi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: <redacted>-autoscaler
  labels:
    app.kubernetes.io/name: <redacted>-autoscaler
    app.kubernetes.io/component: server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <redacted>
  minReplicas: 2
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: <redacted>
  labels:
    app.kubernetes.io/instance: <redacted>
    app.kubernetes.io/part-of: <redacted>
spec:
  prefix: /
  host: <redacted>
  service: <redacted>
  timeout_ms: 60000
  bypass_auth: true
  add_response_headers:
    x-content-type-options:
      append: False
      value: nosniff
```
2. Send requests to the server's public endpoint (set route in AWS route53).
3. Trigger pod deletion via `kubeclt delete pod <pod-name>`.
4. Observe pod logs.

#### Anything else we need to know?:

Pods events
```
$ kubectl get event --field-selector involvedObject.name=<redacted>-66dcff9b66-tnxbn
LAST SEEN   TYPE      REASON              OBJECT                                  MESSAGE
11m         Warning   Unhealthy           pod/<redacted>-66dcff9b66-tnxbn   Readiness probe failed: Get http://11.0.169.166:80/okcomputer: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
10m         Normal    Killing             pod/<redacted>-66dcff9b66-tnxbn   Stopping container server
```

Pod Logs 
[logs.txt](https://github.com/kubernetes/kubernetes/files/6330436/logs.txt)

From the event we could observe that it takes 10 minutes for pod termination (because terminationGracePeriodSeconds is set to 600 and also in the preStop hook we sleep for 600 seconds) and from the logs we could see that the pod was still receiving requests until its terminated.

The pod which is created to replace the terminating pod begins to receive traffic only when the terminating pod is forcefully deleted.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19
- Cloud provider or hardware configuration: AWS ( EKS, Kubernetes Version 1.17)
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS"
- Kernel (e.g. `uname -a`): Linux ip-11-0-137-152 5.4.0-1035-aws #37~18.04.1-Ubuntu SMP Wed Jan 6 22:31:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
