### ISSUE TITLE
When more than one config map is mounted as a volume in a pod, updating the configmap content does not update the mounted volume in the pod

### ISSUE THREAD

**Issue by brunzefb** [kubernetes/kubernetes#101349]
#### What happened:
Normally, when one mounts a configmap as a volume in a pod, updating the content of the configmap updates the volume content in the pod.  This works fine with a single configmap.  When two configmaps are mounted as volumes on separate mountpoints, updating the configmap contents does not update the mounted volume content in the pod. 

#### What you expected to happen:
Mounting multiple configmaps to multiple volumes should work.  Updating any configmap should update the content of the volume in the pod.

#### How to reproduce it (as minimally and precisely as possible):
1. Apply two configmaps as follows:
 ```
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: special-config1
    namespace: default
  data:
    SPECIAL_LEVEL: very
    SPECIAL_TYPE: charm
----
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: special-config2
    namespace: default
  data:
    SPECIAL_LEVEL: tres
    SPECIAL_TYPE: charmant
```
2. Apply a pod configuration
```
    apiVersion: v1
    kind: Pod
    metadata:
      name: dapi-test-pod
    spec:
      containers:
        - name: test-container
          image: k8s.gcr.io/busybox
          command: ["tail", "-f", "/dev/null"]
          volumeMounts:
            - name: config-volume1
              mountPath: /etc/config1
            - name: config-volume2
              mountPath: /etc/config2
      volumes:
        - name: config-volume1
          configMap:
            name: special-config1
        - name: config-volume2
          configMap:
            name: special-config2
      restartPolicy: Never
```
3. Verify mounted configmap1
```
    k exec -it dapi-test-pod -- sh
    / # cat /etc/config1/SPECIAL_LEVEL && echo
    very
```
4. Exit the pod
5. Edit the configmap using `k edit configmap special-config1`, change SPECIAL_LEVEL value to very2
6. Check if the mounted volume for configmap1 has changed contents on the pod
```
    k exec -it dapi-test-pod -- sh  
    / # cat /etc/config1/SPECIAL_LEVEL && echo
    very
    / # 
```
I would have expected to see very2, since that is what the configmap value in k8s is.
#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
/sig storage
