### ISSUE TITLE
The Ingress "test-ffff" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "^~/*.txt$": must be an absolute path

### ISSUE THREAD

**Issue by goudai** [kubernetes/kubernetes#101322]
# Create ingress 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: test-ffff
  namespace: default
spec:
  rules:
    - host: 'test-ffff.sxxx.com'
      http:
        paths:
          - backend:
              serviceName: xxx
              servicePort: 8006
            path: ^~/*.txt$
          - backend:
              serviceName: xxx
              servicePort: 80
  tls:
    - hosts:
        - 'test-ffff.xxx.com'
      secretName: xxx-certs1
```
# Error Msg
The Ingress "test-ffff" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "^~/*.txt$": must be an absolute path

- Kubernetes version (use `kubectl version`): V1.14.2
