### ISSUE TITLE
The field stabilizationWindowSeconds in HPA does to follow the fixed time specifications

### ISSUE THREAD

**Issue by hui-maker** [kubernetes/kubernetes#101371]
#### What happened:
Per my understanding the field `stabilizationWindowSeconds` in HPA, indicates the amount of time the HPA controller should consider previous recommendations to prevent flapping of the number of replicas. 
For example: If I set `stabilizationWindowSeconds: 300` against Pods scaling down policy under behavior section, it indicates the HPA controller will waiting for at latest 5 mins later for scaling down Pods, if picked the largest recommendation value for 5 mins above the target.
But I observed that the timing of scaling down Pods does not follow the fixed time specifications in `stabilizationWindowSeconds: 300`. It will not waiting for at latest 5 mins for pod scaling down, but will down scaling about 1-2 mins around later, once current value above the target.

#### What you expected to happen:
I expected timing of scaling up/down Pods later than the fixed time specifications in `stabilizationWindowSeconds`. Means will not scaling up/down Pods before the fixed time specifications in `stabilizationWindowSeconds` is up
#### How to reproduce it (as minimally and precisely as possible):
Create a HPA against one deployment with the same behavior as defined
#### Anything else we need to know?:
Part of configuration in HPA

```
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60         
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
```
#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Red Hat Enterprise Linux Server 7.9
- Kernel (e.g. `uname -a`): Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by CaoDonghui123** [comment]
/assign 
I will try to reproduce it first

**Comment by CaoDonghui123** [comment]
It works fine in my version 

> haptest-nginx   Deployment/hpatest   0%/50%    2         6         6          113m
> haptest-nginx   Deployment/hpatest   16%/50%   2         6         6          113m
> haptest-nginx   Deployment/hpatest   0%/50%    2         6         6          114m
> haptest-nginx   Deployment/hpatest   16%/50%   2         6         6          116m
> haptest-nginx   Deployment/hpatest   0%/50%    2         6         6          117m
> haptest-nginx   Deployment/hpatest   0%/50%    2         6         6          117m
> haptest-nginx   Deployment/hpatest   20%/50%   2         6         5          118m
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by hui-maker** [comment]
Hi @CaoDonghui123 : Thanks for your feedback. As I understanding based on your results above, you are set the target CPU utilization is `50%`, but seems no one of recommendations will reach up `50%`.  Would you please try to add stress to make CPU utilization higher than 50%, and check if HPA controller will not scaling up pods within the time specifications where set in `stabilizationWindowSeconds`?

**We are expected scenario like shown below**
1. Set `stabilizationWindowSeconds: 300` for scaling up Pods and set the target CPU utilization is `90` in HPA.
2. Based on step 1 settings, we expected HPA controller will not scaling up the Pods within 5 mins, even monitored current CPU utilization is above the target. For example `95`
3. 5 mins later, HPA controller will gather all recommendations for 5 mins. The recommendations should be a list type. Like [10,20,50,95,10,5...]
4. HPA controller will pick up the largest recommendation value from the list. For example 95
5. Let the largest recommendation 95 compare with the target value 90.
6. If recommendation value greater than target value. Will scaling up Pods, otherwise nothing to do.

**What we see now**
Sometimes, the current CPU utilization is higher than target value suddenly, and then goes down lower soon.  We see pods keep scaling up/down in short time, even if we set the stabilizationWindowSeconds is 300 seconds. It will not prevent flapping at least 5 mins.

**Comment by CaoDonghui123** [comment]
@hui-maker this is my log
```
NAME            REFERENCE            TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
haptest-nginx   Deployment/hpatest   50%/50%   2         6         2          5m11s
haptest-nginx   Deployment/hpatest   800%/50%   2         6         2          5m58s
haptest-nginx   Deployment/hpatest   750%/50%   2         6         2          8m1s
haptest-nginx   Deployment/hpatest   800%/50%   2         6         2          9m2s
haptest-nginx   Deployment/hpatest   800%/50%   2         6         2          10m
haptest-nginx   Deployment/hpatest   750%/50%   2         6         2          11m
haptest-nginx   Deployment/hpatest   750%/50%   2         6         3          11m
haptest-nginx   Deployment/hpatest   800%/50%   2         6         3          11m
haptest-nginx   Deployment/hpatest   800%/50%   2         6         3          12m
haptest-nginx   Deployment/hpatest   800%/50%   2         6         4          12m
......# stop 
haptest-nginx   Deployment/hpatest   0%/50%    2         6         6          113m
haptest-nginx   Deployment/hpatest   16%/50%   2         6         6          113m
haptest-nginx   Deployment/hpatest   0%/50%    2         6         6          114m
haptest-nginx   Deployment/hpatest   16%/50%   2         6         6          116m
haptest-nginx   Deployment/hpatest   0%/50%    2         6         6          117m
haptest-nginx   Deployment/hpatest   0%/50%    2         6         6          117m
haptest-nginx   Deployment/hpatest   20%/50%   2         6         5          118m
haptest-nginx   Deployment/hpatest   20%/50%   2         6         5          118m
```
Maybe some PR fixed it, but I couldn't find it

**Comment by hui-maker** [comment]
@CaoDonghui123 : Thanks for the response. If some PR fixed it, what we should upgrade? Is HPA apiVersion or kubernetes version?

We now using following versions

**API version:**
```
apiVersion: autoscaling/v2beta2
```
**kubernetes version**
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+263ee0d", GitCommit:"263ee0d276ef68a1958d000be103d7c69f3e5494", GitTreeState:"clean", BuildDate:"2021-03-21T08:03:52Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by hui-maker** [comment]
The below will show our HPA actions. I monitoring the HPA for 4 mins, you can see the replicas will keep scaling  between 2-3 during 4 mins running, even if I already set `stabilizationWindowSeconds: 3000`
```
NAME            REFERENCE       TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
test-hpa   Deployment/test-app  35%/90%   2         3         2          52s
test-hpa   Deployment/test-app  35%/90%   2         3         3          62s
test-hpa   Deployment/test-app  35%/90%   2         3         3          72s
test-hpa   Deployment/test-app  0%/90%    2         3         3          83s
test-hpa   Deployment/test-app  0%/90%    2         3         3          93s
test-hpa   Deployment/test-app  0%/90%    2         3         3          104s
test-hpa   Deployment/test-app  53%/90%   2         3         3          114s
test-hpa   Deployment/test-app  85%/90%   2         3         3          2m4s
test-hpa   Deployment/test-app  85%/90%   2         3         3          2m15s
test-hpa   Deployment/test-app  0%/90%    2         3         2          2m25s
test-hpa   Deployment/test-app  0%/90%    2         3         3          2m35s
test-hpa   Deployment/test-app  0%/90%    2         3         3          2m46s
test-hpa   Deployment/test-app  0%/90%    2         3         3          2m56s
test-hpa   Deployment/test-app  93%/90%   2         3         3          3m6s
test-hpa   Deployment/test-app  93%/90%   2         3         2          3m17s
test-hpa   Deployment/test-app  93%/90%   2         3         2          3m27s
test-hpa   Deployment/test-app  0%/90%    2         3         2          3m38s
test-hpa   Deployment/test-app  50%/90%   2         3         3          3m48s
test-hpa   Deployment/test-app  50%/90%   2         3         3          3m58s
```

The full HPA configuration like:
```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: test-hpa
  namespace: test
  labels:
    app.kubernetes.io/version: '2102.21'
    release: test
spec:
  scaleTargetRef:
    kind: Deployment
    name: test-app
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60          
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60               
```
