### ISSUE TITLE
kubectl logs --follow exits too soon/returns empty/doesn't follow the stream

### ISSUE THREAD

**Issue by madarez** [kubernetes/kubernetes#101538]
#### What happened:
We used `--follow` switch of `kubectl logs` and it exited with 0 and returned nothing. However, if we rerun the command, we get the following logs correctly.

#### What you expected to happen:
I expected that it would be streamed all the way through the logs.

#### How to reproduce it (as minimally and precisely as possible):
Container:
```
FROM python:3.7.9
COPY . /app
WORKDIR /app
```

```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    project: my_project
  name: job_name
spec:
  template:
    spec:
      containers:
      - command:
        - python
        - main.py
        image: my_image
        name: my_container
      restartPolicy: Never
```

And have the `main.py` just returning a string.

```
kubectl --namespace=default apply -f job_name.yaml && \
kubectl --namespace=default wait --for=condition=complete job.batch/job_name --timeout=30 && \
kubectl --namespace=default logs -l=job-name=job_name
```

#### Anything else we need to know?:
I'm not sure if this is the same issue as the one reported [here](https://github.com/kubernetes/kubernetes/issues/11046), and I'd be happy to get back to you if I know where I need to check to check this.
This problem is reported on a MacOS. However, this process works as expected on a laptop that runs RHEL 8. So, I'm providing the MacOS's specs in the next section:

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.502", GitCommit:"a2a88ab32201dca596d0cdb116bbba3f765ebd36", GitTreeState:"clean", BuildDate:"2021-03-08T22:06:24Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GCP
- OS (e.g: `cat /etc/os-release`): 
![MacOS](https://user-images.githubusercontent.com/31979020/116321567-46ca8380-a788-11eb-8aa9-c16ba94f5d15.png)
- Kernel (e.g. `uname -a`):
```
Darwin user-50YM 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
```
