### ISSUE TITLE
kube-api crash on admission-control-config-file argument set

### ISSUE THREAD

**Issue by j-zimnowoda** [kubernetes/kubernetes#101521]
#### What happened:
Added `- --admission-control-config-file=/etc/kubernetes/admission.yaml` argument to `/etc/kubernetes/manifests/kube-apiserver.yaml`

The Kube-api crashes claiming that configuration file does not exist.
But the file exists:
```
-rw-r--r-- 1 root root 159 Apr 27 10:59 /etc/kubernetes/admission.yaml
```

The following error is reported by kube-api:
```
{"log":"Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.\n","stream":"stderr","time":"2021-04-27T11:00:37.834025241Z"}
{"log":"I0427 11:00:37.834028       1 server.go:632] external host was not specified, using 172.31.27.124\n","stream":"stderr","time":"2021-04-27T11:00:37.834133201Z"}
{"log":"I0427 11:00:37.834412       1 server.go:182] Version: v1.20.1\n","stream":"stderr","time":"2021-04-27T11:00:37.834479981Z"}
{"log":"I0427 11:00:38.322644       1 shared_informer.go:240] Waiting for caches to sync for node_authorizer\n","stream":"stderr","time":"2021-04-27T11:00:38.32276858Z"}
{"log":"Error: failed to initialize admission: failed to read plugin config: unable to read admission control configuration from \"/etc/kubernetes/admission.yaml\" [open /etc/kubernetes/admission.yaml: no such file or directory]\n","stream":"stderr","time":"2021-04-27T11:00:38.323057666Z"}
```

#### What you expected to happen:
Kube-api is able to read the file and start without crashing.

#### How to reproduce it (as minimally and precisely as possible):

```
sudo apt-get install -y kubeadm=1.20.1-00 kubelet=1.20.1-00 kubectl=1.20.1-00
sudo kubeadm init --kubernetes-version 1.20.1 --pod-network-cidr 192.168.0.0/16
```
create file with the  /etc/kubernetes/admission.yaml following content
```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins: []
```

update `/etc/kubernetes/manifests/kube-apiserver.yaml` with new argument.
```
- --admission-control-config-file=/etc/kubernetes/admission.yaml
```
#### Anything else we need to know?:
sudo cat /etc/kubernetes/manifests/kube-apiserver.yaml

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 172.31.27.124:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=172.31.27.124
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --admission-control-config-file=/etc/kubernetes/admission.yaml
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    image: k8s.gcr.io/kube-apiserver:v1.20.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 172.31.27.124
        path: /livez
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-apiserver
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: 172.31.27.124
        path: /readyz
        port: 6443
        scheme: HTTPS
      periodSeconds: 1
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 250m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 172.31.27.124
        path: /livez
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/ca-certificates
      name: etc-ca-certificates
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /usr/local/share/ca-certificates
      name: usr-local-share-ca-certificates
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/ca-certificates
      type: DirectoryOrCreate
    name: etc-ca-certificates
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-local-share-ca-certificates
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
```
#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
``` 

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
