### ISSUE TITLE
networking.k8s.io/v1 fails with default path

### ISSUE THREAD

**Issue by caleb15** [kubernetes/kubernetes#101594]
#### What happened:
When I tried to use the default path I got `Ingress.extensions "nginx" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "": must be an absolute path`.

#### What you expected to happen:
No error. According to https://docs.openshift.com/container-platform/4.6/rest_api/network_apis/ingress-networking-k8s-io-v1.html the path is not needed. "When unspecified, all paths from incoming requests are matched."

#### How to reproduce it (as minimally and precisely as possible):
Create a ingress like so:
```yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.arn_cert }}
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: "200,404"
spec:
  rules:
    - host: "*.foo.com"
      http:
        paths:
          - backend:
              service:
                name: foo
                port:
                  name: http
            pathType: "Exact"
```

#### Environment:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-10T12:53:33Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: brew
- Network plugin and version (if this is a network-related bug): N/A
- Others:
