### ISSUE TITLE
Unable to create ClusterIP services after reached amount of defined LoadBalancers in ResourceQuota

### ISSUE THREAD

**Issue by waltlps** [kubernetes/kubernetes#101686]
#### What happened: 

An attempt to create a ClusterIP service after it was reached the "hard" quota of LoadBalancers in a specific namespace returns this:

`Error from server (Forbidden): error when creating 'dev_deployment.yaml': services '' is forbidden: exceeded quota: object-counts, requested: services.loadbalancers=0, used: services.loadbalancers=1, limited: services.loadbalancers=0;`

#### What you expected to happen:

It is expected being able to create any number of clusterIP services no matter it was reached the defined amount of LoadBalancers has been reached.

Ref.: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

#### How to reproduce it (as minimally and precisely as possible):

While merged to a kubernetes cluster that runs on 1.17.16, please do this:
1) Create a namespace. For example: euskadi
`kubectl create ns euskadi`
2) Create a ResourceQuota object for that namespace. Manifest follows:
```
kind: ResourceQuota
apiVersion: v1
metadata:
  name: object-counts
  namespace: euskadi
spec:
  hard:
    services.loadbalancers: '2'
status:
  hard:
    services.loadbalancers: '0'
  used:
    services.loadbalancers: '0'
```
3) Please create 2 services of type LoadBalancer. Any of your choice.
Ref.: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

Once created, you should see something like this:

```
kubectl describe quota object-counts --namespace=euskadi
Name:                   object-counts
Namespace:              euskadi
Resource                Used  Hard
--------                ----  ----
services.loadbalancers  2     2
```

4) Deploy a ClusterIP service. Example manifest follows:

```
---
apiVersion: v1
kind: Service
metadata:
 name: xyz-clusterip-svc
 namespace: euskadi
spec:
 type: ClusterIP
 ports:
 - name: http-query
 port: 80
 protocol: TCP
 targetPort: 80
```
and run:

`kubectl create -f xyz-ClusterIP-svc.yaml`

The issue ought show-up now. It is, the ClusterIP service won't be created and instead will be returned the error notified at the beginning of this report.

#### Anything else we need to know?:

The issue occurs in a specific namespace. It was verified that it cannot be reproduced in another namespace of the same kubernetes cluster.

#### Environment:
- **Kubernetes version** (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T15:59:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**: Microsoft Azure
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux aks-nodepool1-51404490-vmss000000 4.15.0-1113-azure #126~16.04.1-Ubuntu SMP Tue Apr 13 16:55:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: NA
- Network plugin and version (if this is a network-related bug): NA
- Others: NA
