### ISSUE TITLE
Proxy protocol annotation is not working for AWS NLB

### ISSUE THREAD

**Issue by rkubik-hostersi** [kubernetes/kubernetes#101608]
#### What happened:
I'm trying to setup AWS NLB for nginx-ingress-controller via following annotations set:
```
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
However, the proxy protocol setting is not being applied to the target groups.
I've verified using CloudWatch Events, that the API call to the AWS during LB creation does not specify any attributes regarding target group proxy protocol setting as below:
```
    "eventName": "CreateTargetGroup",
    "awsRegion": "xxx",
    "sourceIPAddress": "eks.amazonaws.com",
    "userAgent": "eks.amazonaws.com",
    "requestParameters": {
      "unhealthyThresholdCount": 3,
      "healthyThresholdCount": 3,
      "protocol": "TCP",
      "targetType": "instance",
      "healthCheckPort": "traffic-port",
      "vpcId": "vpc-xxx",
      "port": 30832,
      "healthCheckProtocol": "TCP",
      "healthCheckIntervalSeconds": 30,
      "name": "k8s-tools-ingressi-xxx"
    },
```

I've tried to change the configuration via `kubectl edit svc`, but again - empty request was submitted to AWS:
```
    "eventSource": "elasticloadbalancing.amazonaws.com",
    "eventName": "ModifyTargetGroup",
    "awsRegion": "xxx,
    "sourceIPAddress": "eks.amazonaws.com",
    "userAgent": "eks.amazonaws.com",
    "requestParameters": {
      "healthCheckPort": "30617",
      "targetGroupArn": "arn:aws:elasticloadbalancing:xxx:xxx:targetgroup/k8s-tools-ingressi-xxx/xxx"
    },
```

#### What you expected to happen:
Annotation should enable the proxy protocol on target groups.

#### Anything else we need to know?:
AWS EKS, k8s 1.19
