### ISSUE TITLE
ContainerLogMaxFiles setting in kubelet.conf not work on cri-o

### ISSUE THREAD

**Issue by yckaolalala** [kubernetes/kubernetes#101656]
#### What happened:
I'm try to find my pod restart log, my pod restart over 10 times and kubectl log only save last two log file.
And I try to set containerLogMaxFiles in kubelet-config.yaml, but not work
This is my kubelet-config.yaml
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
nodeStatusUpdateFrequency: "10s"
failSwapOn: True
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: True
  x509:
    clientCAFile: /etc/kubernetes/ssl/ca.crt
authorization:
  mode: Webhook
staticPodPath: /etc/kubernetes/manifests
cgroupDriver: systemd
containerLogMaxFiles: 30
containerLogMaxSize: 100Mi
maxPods: 110
address: 192.168.56.182
readOnlyPort: 0
healthzPort: 10248
healthzBindAddress: 127.0.0.1
kubeletCgroups: /systemd/system.slice
clusterDomain: cluster.local
protectKernelDefaults: true
rotateCertificates: true
clusterDNS:
- 10.233.0.10
kubeReserved:
  cpu: 200m
  memory: 512Mi
resolvConf: "/etc/resolv.conf"
eventRecordQPS: 5
```
However every pod log in `/var/log/pods/` are saved max on 2 file
ls show:
```
0.log  1.log
```
or
```
3.log  4.log
```
or
```
8.log  9.log
```
#### What you expected to happen:
Should be rotation on containerLogMaxFiles
#### How to reproduce it (as minimally and precisely as possible):
Install with kubespray release-2.15 and using cri-o as containerd
#### Anything else we need to know?:
Did it not work no cri-o, or I need to set crio.conf
#### Environment:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

```
- cri-o version
```
crio version 1.19.1
Version:       1.19.1
GitCommit:     4e159cc8db813fb38e7429ba39ad2cf73b174446
GitTreeState:  clean
BuildDate:     2021-02-05T08:08:41Z
GoVersion:     go1.15.5
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```
- Kernel (e.g. `uname -a`): 
```
Linux k8s-1 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
kubespray release v2.15
```
- Network plugin and version (if this is a network-related bug):
- Others:
