### ISSUE TITLE
Error converting from YAML to JSON: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by ArchieHunter** [kubernetes/kubernetes#101761]
When I try to execute kubectl apply -f mongo-secret.yaml, I get this error "Error converting from YAML to JSON: mapping values are not allowed in this context".Can anyone help?

apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=

**Comment by BenTheElder** [comment]
It's hard to tell since your snippet is not code formatted but as GitHub displays it now it's missing indentation, which is significant in yaml.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
```

You can see examples at https://kubernetes.io/docs/concepts/configuration/secret/

/kind support
