### ISSUE TITLE
Add feature to configure a set of webhooks to intercept other webhooks

### ISSUE THREAD

**Issue by soorena776** [kubernetes/kubernetes#101794]
#### What would you like to be added:
Platform providers should be able to configure a select set of webhooks to intercept other webhoooks as well.

#### Why is this needed:
Currently webhooks [do not intercept other webhook types](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/generic/webhook.go#L222). This is rightly designed to avoid cycles in the admission flow, and also prevent losing control of a webhook in case of a bad configuration (e.g. a webhook rejects all webhook UPDATEs and DELETEs).

However, it is sometimes necessary to intercept webhooks to enforce policy. For instance, consider a platform validation webhook which only allows a certain set of root users to create pods in kube-system. Now, if a user creates a mutating webhook X which intercepts all pods, it could mutate a root users's pod request and use its privilege to create an arbitrary pod in the restricted kube-system namespace. 

In this case, a platform webhook which intercepts other webhooks would intercept X, and decides to either modify or reject it, so that the enforced policies won't be tampered with.

**Comment by liggitt** [comment]
If these would be configured via the API, I'd be concerned about scenarios that put a cluster in an unrecoverable state (a webhook intercepting webhooks fails and can't be fixed).

**Comment by soorena776** [comment]
> If these would be configured via the API, I'd be concerned about scenarios that put a cluster in an unrecoverable state (a webhook intercepting webhooks fails and can't be fixed).

One way to address that would be to add a `webhookInterceptingWebhooks`field which 1) specifies the intercepting webhooks, and 2) specifies what users are _maintainers_. (the same applies for `MutatingAdmissionWebhook`)
A request sent by a _maintainer_ won't be intercepted by these webhooks, so they could always modify and maintain these webhooks.

```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    webhookInterceptingWebhooks:
      identifiers:
        - configName: foo
           name: bar.x.y
      maintainers:
        users:
          - alice
          - bob
        groups:
          - admins
          - core
   ...
```
