### ISSUE TITLE
Unable to update the deployment containers ports name on redeployment

### ISSUE THREAD

**Issue by yashwanthkalva** [kubernetes/kubernetes#101784]
#### What happened:

managementPort is provided by default while applying the k8s manifest.

"mng-mytest" is the name alias for containerPort in deployment manifest.
        ports:
        - containerPort: 9095
          name: mng-mytest

Recently we changed the value of default management port, however for existing deployments that are running
when redeployed the changes of new default mgmt port while getting applied fails with this issue,

**The Deployment "mytestservice-deployment" is invalid: spec.template.spec.containers[0].ports[2].name: Duplicate value: "mng-mytest"**

"mng-mytest" is the name alias for containerPort in deployment manifest.
        ports:
        - containerPort: 9090
          name: mng-mytest

#### What you expected to happen:

The new port value should get applied.

#### How to reproduce it (as minimally and precisely as possible):
First, add a port name and value to the containerPort section of the deployment manifest
then deploy.
Second, change the value of the containerPort but keep the name same then redeploy on top of above existing running deployment.

#### Anything else we need to know?:
NA
#### Environment:
- Kubernetes version (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4"
- Server Version: version.Info{Major:"1", Minor:"18+",
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
NA

**Comment by RolandMa1986** [comment]
Hi @yashwanthkalva, would you mind provider a little bit more information? I can't reproduce the issue with the above steps.
I have created a simple deployment as below:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portest
  name: portest
spec:
  selector:
    matchLabels:
      app: portest
  template:
    metadata:
      labels:
        app: portest
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        - containerPort: 8085
          name: mgmt
          protocol: TCP
```
1. Use `kubectl apply -f portest.yaml` to create the deployment.
2. changed the mgmt port in the yaml file.
3. Use `kubectl apply -f portest.yaml` to update the deployment.
Please let me known if there's something different than your steps. Also if you can recreate the issue as same as the steps above, Please print the kubectl logs with `kubectl apply -f portest.yaml -v=8` and find the patch request and request body.

**Comment by yashwanthkalva** [comment]
Hi Team,

Any update or inputs ?

From,
Yashwanth

**Comment by cndoit18** [comment]
I think this is caused by Helm. You can try to create issue to Helm community.

**Comment by yashwanthkalva** [comment]
Hi @cndoit18 
Though I gave example of helm chart as input, we think its k8s issue. 
This issue happens during kubectl apply, we can see that rendered manifests post template rendering has only 2 ports with updated values. The issue happens during apply step.

```
Manifests [Post template rendering] :

           ports:
           - containerPort: 8085
             name: http-mytest
           - containerPort: 8091
             name: mng-mytest

```
From,
Yashwanth

**Comment by cndoit18** [comment]
> Hi @cndoit18
> Though I gave example of helm chart as input, we think its k8s issue.
> This issue happens during kubectl apply, we can see that rendered manifests post template rendering has only 2 ports with updated values. The issue happens during apply step.
> 
> kubectl --kubeconfig=config apply --filename=manifests.yaml --record
> 
> ```
> Manifests [Post template rendering] :
> 
>            ports:
>            - containerPort: 8085
>              name: http-mytest
>            - containerPort: 8091
>              name: mng-mytest
> ```
> 
> **The Deployment "mytestservice-deployment" is invalid: spec.template.spec.containers[0].ports[2].name: Duplicate value: "mng-mytest"**
> 
> We are facing these issues on changing port value inputs and redeployment of existing services that are running on the k8s cluster.
> 
> Please let me know if you still think it is issue with Helm with any supporting insights. It will be helpful.
> 
> From,
> Yashwanth

I tried it and didn't find this error. What is your kubectl version?

**Comment by AbdulBasitAlvi** [comment]
Hi @yashwanthkalva, 
I also tried to recreate the issue using the following steps

1. Created a nginx deployment and service using the following template
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 8076
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8076
  selector:
    app: nginx
```

2. Created it using the command `kubectl apply -f nginx.yml`

Output: 
```
deployment.apps/nginx created
service/nginx created
```

3. Edit the deployment and apply the changes using the command: `kubectl apply -f nginx.yml`

Output: 
```
deployment.apps/nginx configured
service/nginx configured
```

To me it also looks like a Helm issue rather than a Kubernetes bug
