### ISSUE TITLE
Pods can mount root (/) hostPaths into root (/) containers

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#101749]
#### What happened:
A pod spec and current validation allows for a pod to be admitted that mounts the host root filesystem as the root filesystem within the container. While this is probably not recommended, the resulting running container can exhibit errors. Validation rules should prevent a pod from doing this.

#### What you expected to happen:
Pod creation validation should prevent a pod from doing this due to unknown side-effects. 

#### How to reproduce it (as minimally and precisely as possible):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
  - name: test-container
    image: fedora
    command:
    - /bin/sh
    - -c
    - |
      #!/bin/sh
      sleep infinity
    volumeMounts:
    - name: host-slash
      mountPath: /
      readOnly: true
  volumes:
  - name: host-slash
    hostPath:
      path: /
```

#### Anything else we need to know?:
/sig node
/sig api-machinery

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21 and prior
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
