### ISSUE TITLE
kube-apiserver memory consumption during CRD creation

### ISSUE THREAD

**Issue by alexarefev** [kubernetes/kubernetes#101755]
#### What happened:
The CustomResourceDefinitions creation causes kube-apiserver high memory consumption. CRD has multiple versions.
Several creations during a short period of time may cause kube-apiserver restarting.
#### What you expected to happen:
kube-apiserver shouldn't consume an unreasonably huge amount of memory during processing objects such as CRD
#### How to reproduce it (as minimally and precisely as possible):
Apply yaml and watch kube-apiserver memory consumption:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  name: applications.deployment.nrm.netcracker.com
spec:
  group: deployment.nrm.netcracker.com
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  versions:
  - name: hub
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              milestones:
                properties:
                  activationTimestamp:
                    format: date-time
                    type: string
                type: object
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              notServed:
                type: string
            type: object
        type: object
    served: false
    storage: false
  - name: v1alpha10
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              milestones:
                properties:
                  activationTimestamp:
                    format: date-time
                    type: string
                type: object
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        appService:
                          type: string
                        database:
                          type: string
                        endpoint:
                          type: string
                        networkService:
                          type: string
                        queue:
                          type: string
                        storage:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha3
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        appService:
                          type: string
                        database:
                          type: string
                        endpoint:
                          type: string
                        networkService:
                          type: string
                        queue:
                          type: string
                        storage:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha4
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        appService:
                          type: string
                        database:
                          type: string
                        endpoint:
                          type: string
                        networkService:
                          type: string
                        queue:
                          type: string
                        storage:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha5
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        appService:
                          type: string
                        database:
                          type: string
                        endpoint:
                          type: string
                        networkService:
                          type: string
                        queue:
                          type: string
                        storage:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha6
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        appService:
                          type: string
                        database:
                          type: string
                        endpoint:
                          type: string
                        networkService:
                          type: string
                        queue:
                          type: string
                        storage:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha7
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha8
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
  - name: v1alpha9
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              activeVersion:
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    forResource:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                      type: object
                    lastProbeTime:
                      format: date-time
                      type: string
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: false
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```
#### Anything else we need to know?:
/sig api-machinery

#### Environment:
- Kubernetes version: 1.20.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.6.1810
- Kernel (e.g. `uname -a`): 3.10.0-957.27.2.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
