### ISSUE TITLE
Add a provision to add multiple authorization webhooks

### ISSUE THREAD

**Issue by vivekbagade** [kubernetes/kubernetes#101762]
#### What would you like to be added:
A mechanism that helps specify more than one webhooks at different places in the kubeapiserver authorization chain.

#### Why is this needed:
The authorization layer in the kubeapiserver currently supports adding one webhook via the “Webhook” mode. There are instances where we need multiple webhooks applied at different places of the authorization chain evaluation. One such use case is being discussed in https://groups.google.com/g/kubernetes-sig-api-machinery/c/MBa19WTETMQ by [lavalamp](https://github.com/lavalamp).

**Comment by vivekbagade** [comment]
@kubernetes/sig-auth-feature-requests

**Comment by vivekbagade** [comment]
One way to go about this could be if the kubeapiserver could take in a path to a config file via a parameter and use it to configure its authorization modes (higher precedence means indicates earlier ordering in the authz chain).

```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AuthorizationConfiguration
modes:
- name: Node
  precedence: 100
- name: RBAC
  precedence: 90
- name: DenyWebhook
  precedence: 200
  webhook: true
  kubeConfigFile: <path-to-config>
- name: AllowWebhook
  precedence: 1
  webhook: true
  kubeConfigFile: <path-to-config>

```

**Comment by liggitt** [comment]
If we do this, I agree something structured is required instead of flags.

I'd recommend using the natural ordering of the file to determine the order, and letting the type of each entry map to the current modes, something like this:

```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AuthorizationConfiguration
authorizers:
- type: Webhook
  webhook:
    kubeConfigFile: <path-to-deny-webhook-config>
    authorizedTTL: 5m
    unauthorizedTTL: 30s
    subjectAccessReviewVersion: v1
    onError: Deny
- type: Node
- type: RBAC
- type: Webhook
  webhook:
    kubeConfigFile: <path-to-allow-webhook-config>
    authorizedTTL: 5m
    unauthorizedTTL: 30s
    onError: NoOpinion
    subjectAccessReviewVersion: v1
    onError: Deny
```

as shown above, this would also be a good place to indicate what should happen when there's an error calling a webhook (currently it is treated as "NoOpinion" and evaluation passes to the next authorizer)

**Comment by vivekbagade** [comment]
Good point regarding the "on error" conditions. It is something that could be explicitly specified in the config file. Regarding which authorizers can be present multiple times, yes, the expected behavior would be to only allow `type: Webhook` to exist multiple times in the ordering.

**Comment by enj** [comment]
Since this would be a new config, I would recommend not including `subjectAccessReviewVersion` (go upgrade your webhook to `v1`) and dropping `kubeConfigFile` in favor of more structured API.  `onError: Deny` should be the default for this IMO.  I would also like to see some form of `resource` / `user` based pre-filtering to prevent invoking webhooks for requests they do not care about.

I would also like to see a `deny` + `no opinion` only version of the webhook (to complement things like OPA for read requests) as a Kube REST API, but I suspect that is more contentious 😄.  The allow case is well covered by RBAC (minus maybe some missing label support).

**Comment by liggitt** [comment]
> I would recommend not including subjectAccessReviewVersion (go upgrade your webhook to v1)

I'd want the version to be explicit.

> `onError: Deny` should be the default for this IMO

I wouldn't want a default for this. Deny and NoOpinion are both reasonable, the person routing to the webhook should decide which they want.

> I would also like to see some form of resource / user based pre-filtering to prevent invoking webhooks for requests they do not care about (this makes is much safer to run them as onError: Deny).

I like this idea as well.

**Comment by enj** [comment]
> I'd want the version to be explicit.

Are you worried that we would send `v1` data to a webhook that only supports `v1beta1` and fail to detect the mismatch on the response?  I would really like to get away from supporting the beta API.  Moving to a new config seems like a good time.

> I wouldn't want a default for this. Deny and NoOpinion are both reasonable, the person routing to the webhook should decide which they want.

+1 to no default and requiring the value to be specified.

**Comment by liggitt** [comment]
> Are you worried that we would send v1 data to a webhook that only supports v1beta1 and fail to detect the mismatch on the response?

Being explicit about inputs/outputs is good. I would bet money that there are people with authorization webhooks that don't know a v1 exists based on the flags.

> I would really like to get away from supporting the beta API. Moving to a new config seems like a good time.

Capabilities of the authorizer backends are orthogonal to this API server capability. I wouldn't couple them.

**Comment by soorena776** [comment]
One additional improvement would be to add an optional filter. The reason for this is that the additional webhook is usually only concerned about a subset of api paths.

with path addition, the config will look like this:
```
apiVersion: apiserver.config.k8s.io/v1
kind: AuthorizationConfiguration
authorizers:
- type: Webhook
  webhook:
    kubeConfigFile: <path-to-deny-webhook-config>
    authorizedTTL: 5m
    unauthorizedTTL: 30s
    subjectAccessReviewVersion: v1
    onError: Deny
  paths:
  - api/v1/namespaces/kube-system/pods 
- type: Node
- type: RBAC
- type: Webhook
  webhook:
    kubeConfigFile: <path-to-allow-webhook-config>
    authorizedTTL: 5m
    unauthorizedTTL: 30s
    onError: NoOpinion
    subjectAccessReviewVersion: v1
    onError: Deny
```

**Comment by liggitt** [comment]
> One additional improvement could be to add an optional paths filter.

I think that's a similar idea to the "I would also like to see some form of resource / user based pre-filtering to prevent invoking webhooks for requests they do not care about" bit @enj mentioned

**Comment by vivekbagade** [comment]
Some sort of resource / user based pre-filtering makes sense and could address some scalability concerns of use cases that need a "first in line" webhook. I'd like to start with a GVK and namespace selector based filter (like in dynamic admission control) to begin with and iterate on it later.

```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: AuthorizationConfiguration
authorizers:
- type: Webhook
  webhook:
    kubeConfigFile: <path-to-deny-webhook-config>
    authorizedTTL: 5m
    unauthorizedTTL: 30s
    subjectAccessReviewVersion: v1
    onError: Deny
    rules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      resources:   ["pods"]
      operations: ["CREATE"]
    namespaceSelector:
      matchExpressions:
      ...
- type: Node
- type: RBAC
```
