### ISSUE TITLE
Mounting service account tokens of other Kubernetes clusters

### ISSUE THREAD

**Issue by FabianKramm** [kubernetes/kubernetes#101775]
Hello!

I'm the author of [vcluster](https://github.com/loft-sh/vcluster) and my feature request / question is related regarding the future plans of service account token secrets. As service account token projection has become the default now in v1.21.0 and now pull requests such as #101730 emerge, it seems to me that there might be a deprecation coming soon for secret based service account tokens. It would be great if you could clarify if the option for secret based service account authentication will stay in Kubernetes (even if default off) or if there could be a feature that allows an user to use service account tokens in a pod from a different Kubernetes cluster.

Let me explain to you why this is important for us: virtual kubernetes clusters (vcluster and the multi-tenancy kubernetes sig one) work by syncing certain core resources from a control plane that is not able to actually execute them on its own to a cluster that is able to do that. This "sync" involves rewriting parts of the resource to retain the integrity of the resource during runtime. 

In vcluster, the "virtual" control plane and the "host" control plane are 2 completely different Kubernetes servers with their own separate set of certificates. Pods that are scheduled within the virtual cluster should not be able to query the "host" control plane and instead send their requests to the "virtual" control plane directly (we basically change the default kubernetes service ip from the host one to the virtual one within the pod). That's why we have to exchange the service account token and ca.cert of the running pod in the host cluster with the one from the virtual cluster. 

Currently that was pretty easy, as it just required mounting a different secret that contained the virtual cluster service account token & ca.cert. With service account token projection this is still possible as long as the virtual cluster does support service account token secrets, as we can rewrite projection -> secret. However, with this approach we already lose the advantages of the token volume and if sa token secrets gets removed eventually we would need to implement our own service account token signing for vcluster. 

So this issue is mostly a heads up that such use cases exist (and probably get more popular as well) and we would like to know whats the recommended approach to handle these in future.

**Comment by zshihang** [comment]
it is not clear to me why bound tokens don't work in your case.

**Comment by FabianKramm** [comment]
@zshihang thanks for your quick response! They don't work because the bound tokens are signed by a different API server with a different set of certificates. If you use the token you get during runtime to query the virtual cluster API server, you get an 'Signed by an unknown authority' error. Even if the root certificates would be the same for host and virtual cluster (which is a requirement that would limit certain other things such as creating virtual clusters for users that do not have access to the host cluster certificates), the token would still be signed with a service account name and namespace that potentially does not exist in the virtual cluster. Thats why we need to override the service account token of the pod with the one generated by a different Kubernetes cluster at runtime and currently the only way thats possible is with secrets.

**Comment by FabianKramm** [comment]
A more simple abstraction to think of it would be: how can I mount a token of another Kubernetes cluster that runs within my current cluster

**Comment by zshihang** [comment]
IIUC, you need to overwrite sa token from host cluster with one from virtual cluster. my question is why the token from virtual cluster cannot be bound token but secret-based token?

**Comment by FabianKramm** [comment]
@zshihang the problem is the pod does not run in the virtual cluster and instead in the host cluster, so when the pod has:
```yaml
volumes:
- name: kube-api-access-<random-suffix>
  projected:
    defaultMode: 420 # 0644
    sources:
      - serviceAccountToken:
          expirationSeconds: 3600
          path: token
      - configMap:
          items:
            - key: ca.crt
              path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
```

This would inject the sa token from the host cluster and the pod would not be able to talk to the virtual cluster API server. To overwrite the host sa token we rewrite this to:
```yaml
volumes:
- name: kube-api-access-<random-suffix>
  projected:
    defaultMode: 420 # 0644
    sources:
      - secret:
          name: secret-with-virtual-cluster-sa-token
          items:
          - key: token
             path: token
      - configMap:
          items:
            - key: ca.crt
              path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
```

Which currently works, but we lose the advantages of the token rotation and the virtual cluster behaves slightly different in that regards to what a real cluster is doing. Our fear is that if the sa token secrets feature gets removed all together, we would need to implement our own service account token signing service, so we would like to know what plans are there and if there might be some option to rotate tokens not only directly in volumes but maybe in secrets as well.
