### ISSUE TITLE
Secret mounted at variable subPath persists across pod redeployment

### ISSUE THREAD

**Issue by pmanno** [kubernetes/kubernetes#101743]
#### What happened:
Within a given deployment, a secret that gets created and mounted at a variable subPath persists across pod replacement.

#### What you expected to happen:
Expect all secret volumeMounts to be destroyed when the pod is destroyed and have only a single secret volumeMount exist at any given time.

#### How to reproduce it (as minimally and precisely as possible):
1) Create a secret
2) Create a deployment to a container that mounts the secret at some variable path.  For example:
```
    kind: Secret
    metadata:
      name: appsettings-frontend
      namespace: "{{ namespace }}"
    data:
      "app-settings.json": "{{ lookup('template', 'fe/appsettings.json.j2') | tojson | b64encode }}"

***
    containers:
      - name: billingfe
        image: "9999999999999.dkr.ecr.us-east-2.amazonaws.com/project:app-{{ build_number }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
    volumeMounts:
      - mountPath: "/usr/share/nginx/html/assets/config/app-settings.{{ build_number }}.json"
        name: appconfig
        subPath: "app-settings.json"
    volumes:
      - secret:
          secretName: appsettings-frontend
          defaultMode: 0444
        name: appconfig
```
3) Perform redeployments with a new container, incrementing build number, and see the new container have multiple secrets mounted.

#### Anything else we need to know?:
The above is a deployment managed with ansible.  When a new build executes, a new container is created then the deployment is created with the new build's container and the secret mounted at the new app-settings.{{ build_number }}.json location.  When I shell into the container I can see several "/usr/share/nginx/html/assets/config/app-settings.{{ build_number }}.json" files each with a different build number persisting in the container.  Only when I destroy the deployment do the stray secrets dismount.
#### Environment:
- Kubernetes version (use `kubectl version`): 
        clientVersion:
          buildDate: "2021-02-18T16:12:00Z"
          compiler: gc
          gitCommit: e87da0bd6e03ec3fea7933c4b5263d151aafd07c
          gitTreeState: clean
          gitVersion: v1.20.4
          goVersion: go1.15.8
          major: "1"
          minor: "20"
          platform: linux/amd64
        serverVersion:
          buildDate: "2020-12-23T22:10:21Z"
          compiler: gc
          gitCommit: 49a6c0bf091506e7bafcdb1b142351b69363355a
          gitTreeState: clean
          gitVersion: v1.19.6-eks-49a6c0
          goVersion: go1.15.5
          major: "1"
          minor: 19+
          platform: linux/amd64

- Cloud provider or hardware configuration: Amazon EKS
- OS (e.g: `cat /etc/os-release`): 
      NAME="Amazon Linux"
      VERSION="2"
      ID="amzn"
      ID_LIKE="centos rhel fedora"
      VERSION_ID="2"
      PRETTY_NAME="Amazon Linux 2"
      ANSI_COLOR="0;33"
      CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
      HOME_URL="https://amazonlinux.com/"

- Kernel (e.g. `uname -a`): Linux ip-10-5-5-237 4.14.219-164.354.amzn2.x86_64 #1 SMP Mon Feb 22 21:18:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
