### ISSUE TITLE
the node.status.allocatable about custom device resource  is not changed

### ISSUE THREAD

**Issue by mrpre** [kubernetes/kubernetes#101963]
#### What happened:
I develop a device-plugin to report my custom device info to kubernetes. It's all ok and the device info is shown in Node: 
```
status:
  allocatable:
    cpu: "104"
    test.com/mymem: "100"
  capacity:
    cpu: "104"
    test.com/mymem: "100"
```
After I apply a pod with resource `test.com/mymem: "10"` the `Allocate` in device-plugin is called.  but the `allocatable` about `test.com/mymem` is not be reduced to "90". 

#### What you expected to happen:
kubelet manage the custom device resource automatically.

#### Anything else we need to know?:
Is it the responsibility for developer to manage the custom resource ? If so the developer should watch the pod lifecycle and update node.status.allocatable manually.

I also write the scheduler by `scheduler framework` but didn't find the hook(Filter/score/...) to maintain the `allocatable`

#### Environment:
- Kubernetes version (use `kubectl version`):1.18.8
- Kernel (e.g. `uname -a`):4.19
