### ISSUE TITLE
Garbage collect VolumeAttachments of migrated in-tree volumes

### ISSUE THREAD

**Issue by timebertt** [kubernetes/kubernetes#102097]
#### What happened:

_Context:_ When a cluster has dangling `VolumeAttachment`s caused by restarts of kube-controller-manager (like described in https://github.com/kubernetes/kubernetes/issues/77324), the attach/detach controller tries to clean them up on startup (ref https://github.com/kubernetes/kubernetes/pull/96617).
For this, it iterates over all `VolumeAttachment`s and finds the responsible volume plugin for retrieving the unique volume name.

_Problem:_ However, if the volume was provisioned by an in-tree plugin, then later migrated to CSI and now the `CSIMigration*Complete ` / `InTreePlugin*Unregister` feature gate is set, the volume is skipped during `processVolumeAttachments`, so the `VolumeAttachment` will stay in the system and the volume will not be detached from the undesired node and potentially block a new attach operation to a different node.

_Analysis:_ The `CSIMigration*Complete ` / `InTreePlugin*Unregister` feature gate causes the respective in-tree volume plugins not to be registered: https://github.com/kubernetes/kubernetes/blob/bda557b4bc3f5ec655d32a9ec23345ed9c77147b/cmd/kube-controller-manager/app/plugins_providers.go#L53-L55

The `PersistentVolume` spec only contains the in-tree fields (e.g `awsElasticBlockStore` or `gcePersistentDisk`), but not the `csi` fields:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/migrated-to: pd.csi.storage.gke.io
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/pd-csi-storage-gke-io
  name: pvc-some-uid
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: some-pvc
    namespace: some-namespace
  gcePersistentDisk:
    fsType: ext4
    pdName: some-pd-name
status:
  phase: Bound
```

This causes the `FindAttachablePluginBySpec` call in `processVolumeAttachments` to find no responsible volume plugin for the `VolumeAttachment`, which will skip the cleanup: https://github.com/kubernetes/kubernetes/blob/be583070d23435577775a276af69c74bc640b964/pkg/controller/volume/attachdetach/attach_detach_controller.go#L719-L733

That's why we see a lot of logs like this on startup of kube-controller-manager and dangling `VolumeAttachment`s on our clusters:
```text
{"log":"Skipping processing the volume \"pvc-some-uid\" on nodeName: \"some-node\", no attacher interface found. err=no volume plugin matched","pid":"1","severity":"WARN","source":"attach_detach_controller.go:738"}
```

#### What you expected to happen:

The attach/detach controller should cleanup dangling `VolumeAttachment`s for migrated in-tree plugins with unregistered in-tree plugins as well.

#### How to reproduce it (as minimally and precisely as possible):
ref https://github.com/kubernetes/kubernetes/issues/94912, https://github.com/kubernetes/kubernetes/pull/101423#issuecomment-828678256

#### Anything else we need to know?:

https://github.com/kubernetes/kubernetes/pull/101737 addresses a similar issue. Though, the fix doesn't come into effect, if the respective `CSIMigration*Complete ` / `InTreePlugin*Unregister` feature gate is enabled.

#### Environment:
- Kubernetes version (use `kubectl version`): `1.18.16` / `1.20.6`
- Cloud provider or hardware configuration: AWS, GCP
