### ISSUE TITLE
Failed to try resolving symlinks when i do kubectl logs

### ISSUE THREAD

**Issue by carlosjpr-collab** [kubernetes/kubernetes#102170]
I am tring to get log from a cronjob pod using this command 
` kubectl logs pod_name
` 
 But i am seeing this error:
` 
 failed to try resolving symlinks in path "/var/log/pods/default_kubernetes-1621505400-jwt8r_09be41c0-af2f-4e74-b2a6-fdb44525be14/kubernetes-api/0.log": lstat /var/log/pods/default_kubernetes-api-1621505400-jwt8r_09be41c0-af2f-4e74-b2a6-fdb44525be14/kubernetes-api/0.log: no such file or director
 `
 and this my configuration 
 ```

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubernetes-api
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
          containers:
          - name: kubernetes-api-monitor
            image: test/latest
            env:
            imagePullPolicy: IfNotPresent
            command: ['python3']
            args: ['/test.py']
          restartPolicy: OnFailure
 
```
