### ISSUE TITLE
 [sig-storage][csi-translation] Duplicate zone information for in-tree PV

### ISSUE THREAD

**Issue by Elbehery** [kubernetes/kubernetes#102248]
#### What happened:
AWS EBS CSI driver returns `duplicate` topology segments
```

          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1b
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1b

```

#### What you expected to happen:
It should merge the `identical` topology segments
#### How to reproduce it (as minimally and precisely as possible):
Enabling `csi-migration` , and then describe the `PV` 
#### Anything else we need to know?:
I have found in the docs [this](https://github.com/kubernetes/kubernetes/blob/fed3a4520d99a2d99fd4ed0f7edf1ac79e7253e7/staging/src/k8s.io/csi-translation-lib/plugins/in_tree_volume.go#L84-L86) which indicates that the duplication is by intention 

Also I found this [issue](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/729) and pull [request](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/773)

**Comment by jsafrane** [comment]
It's caused by the migration from CSI to in-tree PV. AWS EBS CSI driver provides PV with:

```
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1b
          - key: topology.ebs.csi.aws.com/zone
            operator: In
            values:
            - us-east-1b
```

CSI translation changes `topology.ebs.csi.aws.com/zone` -> `topology.kubernetes.io/zone` and we end up with two same items in the array. It makes sense to squash these duplicates.

**Comment by jsafrane** [comment]
cc @Jiawei0227 @msau42, what do you think?

**Comment by Jiawei0227** [comment]
Why is aws csi driver provides PV with
```
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1b
```

Seems to me this is not needed.
