### ISSUE TITLE
Deployments/auth.yaml: No such file or directory

### ISSUE THREAD

**Issue by adilshehzad786** [kubernetes/kubernetes#102391]
#### What happened:
Auth Yaml file could not be detected in the latest Kubernetes Version
#### What you expected to happen:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        track: stable
    spec:
      containers:
        - name: auth
          image: "kelseyhightower/auth:1.0.0"
          ports:
            - name: http
              containerPort: 80
            - name: health
              containerPort: 81
...

```
#### How to reproduce it (as minimally and precisely as possible):
1.`gsutil -m cp -r gs://spls/gsp053/orchestrate-with-kubernetes .
cd orchestrate-with-kubernetes/kubernetes`

2.  `gcloud container clusters create bootcamp --num-nodes 5 --scopes "https://www.googleapis.com/auth/projecthosting,storage-rw"`

3.  `kubectl explain deployment`

4.  `kubectl explain deployment --recursive`

5.  `kubectl explain deployment.metadata.name`

#### Environment:
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1400", GitCommit:"ec68c7064ea987ad0c7fb63930df96bdefeb93c4", GitTreeState:"clean", BuildDate:"2021-04-07T09:20:04Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

![image](https://user-images.githubusercontent.com/53600644/119945753-4d2e6400-bfaf-11eb-8334-0962ac6337b6.png)
