### ISSUE TITLE
Inconsistent timezone shown for the same object 

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#102316]
#### What happened:
When you query an object, say `Node` object the timestamp will show in local timezone, for example
`kubectl describe node ip-10-0-49-125.us-east-2.compute.internal`
```
CreationTimestamp:  Sun, 16 May 2021 23:26:04 -0400
Taints:             node-role.kubernetes.io/master:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Mon, 17 May 2021 06:11:57 -0400   Sun, 16 May 2021 23:26:04 -0400   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 17 May 2021 06:11:57 -0400   Sun, 16 May 2021 23:26:04 -0400   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Mon, 17 May 2021 06:11:57 -0400   Sun, 16 May 2021 23:26:04 -0400   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Mon, 17 May 2021 06:11:57 -0400   Sun, 16 May 2021 23:29:54 -0400   KubeletReady                 kubelet is posting ready status
```
But when you query the same object using `kubectl get node ip-10-0-53-20.us-east-2.compute.internal -o yaml` he same timestamp item will show in UTC,
```
creationTimestamp: "2021-05-17T03:37:49Z"
  conditions:
  - lastHeartbeatTime: "2021-05-18T03:38:18Z"
    lastTransitionTime: "2021-05-17T03:37:49Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2021-05-18T03:38:18Z"
    lastTransitionTime: "2021-05-17T03:37:49Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2021-05-18T03:38:18Z"
    lastTransitionTime: "2021-05-17T03:37:49Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2021-05-18T03:38:18Z"
    lastTransitionTime: "2021-05-17T03:39:00Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
```

#### What you expected to happen:
Shouldn't the timezone shown should be consistent across different queries?

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
