### ISSUE TITLE
Pods stuck as failed with "Pod Predicate NodeAffinity failed"

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubernetes#102387]
#### What happened:
Ref: This is already reported in issue [#72502](https://github.com/kubernetes/kubernetes/issues/72502)

I have one deployment with node affinity to master with replica cnt = 1.
I did not follow up in-depth to get a repro. But now and then, I see a deployment that has a pod stuck as below:

`sonic-k8s-agent-8684d6989d-bhzbf   0/1     NodeAffinity   0          2d1h
`

BTW, the corresponding deployment had been updated and a new pod is running. In other words, the above one is also stale.

`sonic-k8s-agent-6bdf456844-dwnxj   1/1     Running        5          10h`

The deployment manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonic-k8s-agent
  labels:
    app: k8s-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-agent
  template:
    metadata:
      labels:
        app: k8s-agent
    spec:
      hostname: sonic
      hostNetwork: true
      containers:
      - name: sonic-k8s-agent
        image: sonicanalytics.azurecr.io/sonic-dockers/any/docker-sonic_k8s_agent:20210428.0258
        name: sonic-k8s-agent
        tty: true
        env:
        - name: KUBECONFIG
          value: /etc/kubernetes/admin.conf
        securityContext:
          privileged: true
        volumeMounts:
          ...
        volumes:
          ...
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: "Exists"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

```

copy/paste from the referred old issue:

_kqsantacruz commented on Mar 27:
FWIW, I'm also experiencing this issue using preemtible nodes in GKE, in my case running 1.18.16-gke.302, which I believe should contain the cherry-picked fix. Experience is the same, replacement pod starts eventually, but previous pod remains stuck in NodeAffinity state, with a kubectl describe pod showing "Pod Predicate NodeAffinity failed" as a Message._

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: VM
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`): `Linux CO4AEAP00010B96 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
