### ISSUE TITLE
Create HPA Behavior E2E Test

### ISSUE THREAD

**Issue by josephburnett** [kubernetes/kubernetes#102369]
#### What would you like to be added:

We need an E2E test for HPA behavior.

#### Why is this needed:

HPA v2beta2 is graduating to stable!  

- KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-autoscaling/2702-graduate-hpa-api-to-GA
- Tracking issue: https://github.com/kubernetes/enhancements/issues/2702
- Working doc: https://docs.google.com/document/d/1QGT9Waxc500ICGX_TGIoxfOWKmWbXYC6TWxfdUC2Njg/edit#
- Slack channel: #sig-autoscaling-api

#### What to do:

1. Read [End-to-End Testing in Kubernetes](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md).
2. Tell @josephburnett on #sig-autoscaling-api "Hey, I want to do this." (just so two people don't start the same work)
3. Write a new E2E test that tests `spec.behavior`.

#### Details:

There are currently two kinds of HPA tests in the Kubernetes E2E suite.  One tests [CPU autoscaling](https://github.com/kubernetes/kubernetes/blob/c495744436fc94ebbef2fcbeb97699ca96fe02dd/test/e2e/autoscaling/horizontal_pod_autoscaling.go#L31) and the other tests [custom metrics autoscaling](https://github.com/kubernetes/kubernetes/blob/c495744436fc94ebbef2fcbeb97699ca96fe02dd/test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go#L48).

The [Behavior](https://pkg.go.dev/k8s.io/api/autoscaling/v2beta2#HorizontalPodAutoscalerSpec) feature is independent of the kind of metrics HPA is using.  After HPA calculates scale for all metrics, it select the maximum and then applies user configured limits which are `MinReplicas`, `MaxReplicas` and `Behavior`.  Behavior specifies a scale up and down limit in rate (relative and absolute) as well as a delay.

Defaults are:
```yaml
# Scale up 4 pods or 2x, whichever is larger.
# Delay scale down by 5 minutes.
spec:
  behavior:
    scaleUp:
      selectPolicy: "Max"
      policies:
      - type: "Pods"
        value: 4
        periodSeconds: 15
      - type: "Percent"
        value: 200
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
```

New behavior tests could be part of the CPU or the custom metrics suites, it doesn't really matter.  Whichever is easier to implement and has the least flakes.

Cases we should test:
1. Faster scale down works.  Set `behavior.scaleDown.stabilizationWindowSeconds: 30`, verify scale up, then verify scale down happens within 1 minute.
2. Scale up delay works.  Set `behavior.scaleUp.stabilizationWindowSeconds: 300`, continuously send high usage and verify scale up happens only after 5 minutes.
3. Disabling autoscaling works.  Set `behavior.scaleUp.selectPolicy: "Disabled"` and `behavior.scaleDown.selectPolicy: "Disabled"`.  This will the replacement for the special 0 replicas case when we deprecate it, we should make sure it reliably works.

Send a pull request (one squashed commit please) and notify #sig-autoscaling-api so we can take a look too. It will probably need API review.

Feel free to reach out for help on #sig-autoscaling-api if you have any questions!
