### ISSUE TITLE
Scheduler: Simplify Plugin Configuration in ComponentConfig

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#102303]
Currently configuring the scheduler plugins requires explicitly configuring the extension points themselves. For example, consider a custom scheduler configuration that requires enabling `PodTopologySpread`, admins will need to explicitly add it to every extension point as follows:

```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
profiles:
  - plugins:
      preFilter:
        enabled:
        - name: PodTopologySpread
      filter:
        enabled:
        - name: PodTopologySpread
      preScore:
        enabled:
        - name: PodTopologySpread
      score:
        enabled:
        - name: PodTopologySpread
```

Configuring the exact extensions points where a plugin should be enabled offer maximum flexibility to the admin, but I think this is really not worth it for the following reasons:

1) It is way too repetitive and admins could potentially misconfigure a plugin by mistakenly forgetting to enable a specific extension point
2) It unnecessarily exposes the details of the plugin, and so we are violating separation of concerns. Admins shouldn't really care about the extension points, they care about high-level features (e.g., enable/disable PodTopologySpread).
3) If we decide to re-factor a plugin to add more extension points, this becomes a backward incompatible change since adding or removing an extension point may break existing configurations (see this example https://github.com/kubernetes/kubernetes/pull/102235#issuecomment-847835395).

I suggest we change component config such that plugins are enabled/disabled as a whole (e.g., `PodTopologySpread`), and then the plugin registers itself in the relevant extension points.

The configuration above becomes:
```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
profiles:
  - plugins:
        enabled:
        - name: PodTopologySpread
        - scoringWeight: 1
```

Looking at the [list of plugins](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/framework/plugins), it seems to me that they are already grouped properly:

- **DefaultBinder** `{Bind}`
- **DefaultPreemption** `{PostFilter}`
- **PrioritySort** `{QueueSort}`
- **NodePorts** `{PreFilter, Filter}`
- **NodeLabel** `{Filter}`
- **NodeName** `{Filter}`
- **NodeResourcesFit** `{PreFilter, Filter, Score}`
- **NodeResourcesBalancedAllocation** `{Score}`
- **NodeAffinity** `{PreFilter, Filter, PreScore, Score}`
- **InterPodAffinity** `{PreFilter, Filter, PreScore, Score}`
- **PodTopologySpread** `{PreFilter, Filter, PreScore, Score}`
- **TaintToleration** `{Filter, PreScore, Score}`
- **VolumeBinding** `{PreFilter, Filter, Reserve, PreBind, Score}`
- **NodeVolumeLimits** `{Filter}`
- **EBSLimits** `{Filter}`
- **AzureDiskLimits** `{Filter}`
- **GCEPDLimits** `{Filter}`
- **VolumeRestrictions** `{Filter}`
- **VolumeZone** `{Filter}`
- **ImageLocality** `{Score}`
- **NodePreferAvoidPods** `{Score}`

/sig scheduling

**Comment by Huang-Wei** [comment]
I think we need to get more user feedback to evaluate whether it's reasonable to enable/disable a plugin as a whole. Probably sending an email to sig-scheduling mailing list.

And before we adopt the pattern, let's examine existing plugins to verify if current groupings semantically make sense.

**Comment by ahg-g** [comment]
> I think we need to get more user feedback to evaluate whether it's reasonable to enable/disable a plugin as a whole. Probably sending an email to sig-scheduling mailing list.

Sure, this issue is to have this discussion, I will send an email to the list to bring more attention to the issue.

> And before we adopt the pattern, let's examine existing plugins to verify if current groupings semantically make sense.

Even if it doesn't, I don't think this is enough to stop us from pursuing this. We should change the plugins to adhere to the pattern, not the other way around. 

Do you have counter arguments to the listed drawbacks? especially number 2 and 3?

**Comment by Huang-Wei** [comment]
> Do you have counter arguments to the listed drawbacks? especially number 2 and 3?

Those points make sense to me, esp. in the perspective of simplifying configuration.

**Comment by ahg-g** [comment]
> And before we adopt the pattern, let's examine existing plugins to verify if current groupings semantically make sense.

I updated the description to address this point.

**Comment by denkensk** [comment]
@ahg-g  @Huang-Wei 
A little bit of concern, I think we can discuss to make `Simplify Plugin Configuration` more suitable for the actual scene.

1. how to set the weight of score of different extension points？
2. how to disable the other plugins in the same extension points like this?
```yaml
    queueSort:      
      enabled:        
      - name: Coscheduling     
      disabled:
      - name: "*"
``` 
or
```yaml
    postFilter:      
      enabled:        
      - name: Capacityscheduling     
      disabled:
      - name: "*"
```

**Comment by ahg-g** [comment]
> how to set the weight of score in different extension points？

Weight is only eligible for Score extension point.

> how to disable the other plugins in the same extension points like this?

What if we don't support the `*` expression? The alternative is for admins to explicitly list the plugins that they want to disable.

**Comment by denkensk** [comment]
> how to set the weight of score in different extension points？
> Weight is only eligible for Score extension point.

Sorry, I mean " how to set the weight of score in different plugins"?

**Comment by ahg-g** [comment]
something like this?

```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
profiles:
  - plugins:
        enabled:
        - name: PodTopologySpread
        - weight: 1
```

**Comment by denkensk** [comment]
> something like this?
Thanks, It's fine to me.

**Comment by mateuszlitwin** [comment]
I like the idea of simplifying the configuration. 

One problem though is how you configure order in which plugins are executed. 

I think it matters for plugin extension points such as PostFilter() which execute plugins until one of the returns Success. AFAIK it matters if you want the `coscheduling` plugin to work with `defaultpreemption` plugin.

**Comment by suigh** [comment]
@ahg-g @Huang-Wei
For the current configuration, can we still keep it even the new configuration is convenient for most cases? User can enable/disable one specific extension point by current configuration, needn't change the codes, this can help during development or for debug purpose.

**Comment by damemi** [comment]
I think for most use cases something exactly like what @ahg-g suggested in https://github.com/kubernetes/kubernetes/issues/102303#issuecomment-848431986 is perfect. But I agree with @suigh that keeping the current approach available for advanced use cases is a good idea, though users will have to pick one or the other. If we add this simplified config, it should be a new field

**Comment by atantawi** [comment]
How about keeping the ability to individually configure each extension point as it is today, but add an extension point with the name "all" to apply a configuration to all extension points relevant to the specific scheduler plugin? The use of "all" for a plugin takes precedence over any other extension point configuration of the plugin.
```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
profiles:
  - plugins:
      all:
        enabled:
        - name: PodTopologySpread
        - weight: 1
```
