### ISSUE TITLE
HPA desired replicas not respecting minReplicas when set to 1

### ISSUE THREAD

**Issue by dmrogers7** [kubernetes/kubernetes#102405]
#### What happened:

When deploying a HorizontalPodAutoscaler (HPA) with `minReplicas` set to `1`, the `desired` replicas is set to `0`

#### What you expected to happen:

I expect that the `desired` replicas should fall with the range of `minReplicas` and `maxReplicas` and, in this case, should be calculated to be `1`

#### How to reproduce it (as minimally and precisely as possible):

Deploy this manifest:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
        imagePullPolicy: IfNotPresent
        name: busybox
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: busybox
  namespace: default
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: busybox
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
```

The resulting HPA never sets `desired` replica count to the minimum replicas of `1`

```
$ kubectl describe hpa busybox
Name:                                                  busybox
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Fri, 28 May 2021 09:43:03 -0400
Reference:                                             Deployment/busybox
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 80%
Min replicas:                                          1
Max replicas:                                          4
Deployment pods:                                       1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpu
Events:
  Type     Reason                        Age   From                       Message
  ----     ------                        ----  ----                       -------
  Warning  FailedGetResourceMetric       13s   horizontal-pod-autoscaler  missing request for cpu
  Warning  FailedComputeMetricsReplicas  13s   horizontal-pod-autoscaler  failed to compute desired number of replicas based on listed metrics for Deployment/default/busybox: invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: missing request for cpu
```
  
#### Anything else we need to know?:

I realize that in my example, the HPA is unable to read the resource metric and that may be a contributing factor in the calculation of the `desired` replica count.  However, when `minReplicas` is set higher than `1`, then the `desired` replica count is calculated to be vale of `minReplicas`.  For example, deploying the same manifest as before with the only change is setting `minReplicas` to `2`.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
        imagePullPolicy: IfNotPresent
        name: busybox
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: busybox
  namespace: default
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: busybox
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
 ```

The resulting HPA has a `desired` replica count set to the minimum replicas of `2`

```
$ k describe hpa busybox
Name:                                                  busybox
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Fri, 28 May 2021 09:48:25 -0400
Reference:                                             Deployment/busybox
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 80%
Min replicas:                                          2
Max replicas:                                          4
Deployment pods:                                       2 current / 2 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpu
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Normal   SuccessfulRescale             2m10s              horizontal-pod-autoscaler  New size: 2; reason: Current number of replicas below Spec.MinReplicas
  Warning  FailedGetResourceMetric       5s (x8 over 113s)  horizontal-pod-autoscaler  missing request for cpu
  Warning  FailedComputeMetricsReplicas  5s (x8 over 113s)  horizontal-pod-autoscaler  failed to compute desired number of replicas based on listed metrics for Deployment/default/busybox: invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: missing request for cpu
```

The behavior should be consistent no matter the value of `minReplicas`.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
   Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
   Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1400", GitCommit:"ec68c7064ea987ad0c7fb63930df96bdefeb93c4", GitTreeState:"clean", BuildDate:"2021-04-07T09:20:04Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Google Kubernetes Engine

**Comment by manavchawla98** [comment]
Hi! I am a new contributor and would like to help solve this issue. I understand what's happening vs what's expected but was hoping someone could help with reproducing this issue on my local. I can then take a look at the code that needs to be modified and any tests that go along with it.

**Comment by apoorvajagtap** [comment]
Hello, @dmrogers7 I have been just looking through the issue and a bit curious to understand what might lead to such a scenario. Can you please confirm the versions, for which you are observing this behavior? 

IIUC, in case minreplica is not set, the default value is chosen as '1' as per [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L631-L636).

**Comment by dmrogers7** [comment]
@apoorvajagtap 

These are the versions I'm running
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.10-gke.1600", GitCommit:"7b8e568a7fb4c9d199c2ba29a5f7d76f6b4341c2", GitTreeState:"clean", BuildDate:"2021-05-07T09:18:53Z", GoVersion:"go1.15.10b5", Compiler:"gc", Platform:"linux/amd64"}
```

The issue isn't with `minReplicas` getting set to `1`, it's that the `desired` never gets set to `1` as it should per this [condition](https://github.com/kubernetes/kubernetes/blob/92726bf0f3e2f2c83ca9d0b750cac53a7d74d0c0/pkg/controller/podautoscaler/horizontal.go#L648-L650)

```go
	} else if currentReplicas < minReplicas {
		rescaleReason = "Current number of replicas below Spec.MinReplicas"
		desiredReplicas = minReplicas
```

However, I do see these other conditions happening

### Auto scaling disabled

If I set the `replicas` to `0` on the Deployment

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  replicas: 0
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
        imagePullPolicy: IfNotPresent
        name: busybox
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: busybox
  namespace: default
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: busybox
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
```

Then I see it go thru this [condition](https://github.com/kubernetes/kubernetes/blob/92726bf0f3e2f2c83ca9d0b750cac53a7d74d0c0/pkg/controller/podautoscaler/horizontal.go#L640-L644)
``` go
	if scale.Spec.Replicas == 0 && minReplicas != 0 {
		// Autoscaling is disabled for this resource
		desiredReplicas = 0
		rescale = false
		setCondition(hpa, autoscalingv2.ScalingActive, v1.ConditionFalse, "ScalingDisabled", "scaling is disabled since the replica count of the target is zero")
	}
```
```
$ kubectl describe hpa busybox
Name:                                                  busybox
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Tue, 29 Jun 2021 16:47:31 -0400
Reference:                                             Deployment/busybox
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 80%
Min replicas:                                          1
Max replicas:                                          4
Deployment pods:                                       0 current / 0 desired
Conditions:
  Type           Status  Reason             Message
  ----           ------  ------             -------
  AbleToScale    True    SucceededGetScale  the HPA controller was able to get the target's current scale
  ScalingActive  False   ScalingDisabled    scaling is disabled since the replica count of the target is zero
Events:          <none>
```

### Current replicas greater than maxReplicas

If I configure my deployment with a replica count higher than the `maxReplicas` of the HPA

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
        imagePullPolicy: IfNotPresent
        name: busybox
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: busybox
  namespace: default
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: busybox
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
```

Then I do see it going through this [condition](https://github.com/kubernetes/kubernetes/blob/92726bf0f3e2f2c83ca9d0b750cac53a7d74d0c0/pkg/controller/podautoscaler/horizontal.go#L645-L647)

```go
the replica count of the target is zero")
	} else if currentReplicas > hpa.Spec.MaxReplicas {
		rescaleReason = "Current number of replicas above Spec.MaxReplicas"
		desiredReplicas = hpa.Spec.MaxReplicas
```

```
$ kubectl describe hpa busybox
Name:                                                  busybox
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Tue, 29 Jun 2021 16:29:04 -0400
Reference:                                             Deployment/busybox
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 80%
Min replicas:                                          1
Max replicas:                                          2
Deployment pods:                                       2 current / 2 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpu
Events:
  Type     Reason                        Age                   From                       Message
  ----     ------                        ----                  ----                       -------
  Normal   SuccessfulRescale             4m                    horizontal-pod-autoscaler  New size: 2; reason: Current number of replicas above Spec.MaxReplicas
  Warning  FailedGetResourceMetric       51s (x12 over 3m44s)  horizontal-pod-autoscaler  missing request for cpu
  Warning  FailedComputeMetricsReplicas  51s (x12 over 3m44s)  horizontal-pod-autoscaler  failed to compute desired number of replicas based on listed metrics for Deployment/default/busybox: invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: missing request for cpu
```

Even though the HPA does scale the Deployment correctly, the reason I'm complaining about the the HPA reporting it incorrectly is that we use Spinnaker, which never considers the HPA deployed successfully because of this [code](https://github.com/spinnaker/clouddriver/blob/e2d7bfde5a3a77c1a415fe316fa25da8320a45b3/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesHorizontalPodAutoscalerHandler.java#L80-L88)

```java
    int desiredReplicas = defaultToZero(status.getDesiredReplicas());
    int existing = defaultToZero(status.getCurrentReplicas());
    if (desiredReplicas > existing) {
      return Status.defaultStatus()
          .unstable(
              String.format(
                  "Waiting for HPA to complete a scale up, current: %d desired: %d",
                  existing, desiredReplicas));
    }
```

**Comment by dmrogers7** [comment]
What's happening is that the Deployment get deployed with a single instance running, so `currentReplicas` is `1` and `minRepllicas` on the HPA is also `1`, so it never goes into the `if currentReplicas < minReplicas` condition and falls thru to the else condition
```go
	if scale.Spec.Replicas == 0 && minReplicas != 0 {
		// Autoscaling is disabled for this resource
		desiredReplicas = 0
		rescale = false
		setCondition(hpa, autoscalingv2.ScalingActive, v1.ConditionFalse, "ScalingDisabled", "scaling is disabled since the replica count of the target is zero")
	} else if currentReplicas > hpa.Spec.MaxReplicas {
		rescaleReason = "Current number of replicas above Spec.MaxReplicas"
		desiredReplicas = hpa.Spec.MaxReplicas
	} else if currentReplicas < minReplicas {
		rescaleReason = "Current number of replicas below Spec.MinReplicas"
		desiredReplicas = minReplicas
	} else {
		var metricTimestamp time.Time
		metricDesiredReplicas, metricName, metricStatuses, metricTimestamp, err = a.computeReplicasForMetrics(hpa, scale, hpa.Spec.Metrics)
		if err != nil {
			a.setCurrentReplicasInStatus(hpa, currentReplicas)
			if err := a.updateStatusIfNeeded(hpaStatusOriginal, hpa); err != nil {
				utilruntime.HandleError(err)
			}
			a.eventRecorder.Event(hpa, v1.EventTypeWarning, "FailedComputeMetricsReplicas", err.Error())
			return fmt.Errorf("failed to compute desired number of replicas based on listed metrics for %s: %v", reference, err)
		}
		...
	}
```

And since it can't compute the metric, it's returning the error.  I now see why it 'works' when `minReplicas` is set to `2` - the HPA will scale up the Deployment to the `minReplicas` first, then it will start looking at the metrics to determine how to scale from there.  I was so focused on the value of `desired` that i didn't really notice that it too ran into the same cannot-compute-metric error.

```
$ k describe hpa busybox
Name:                                                  busybox
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Fri, 28 May 2021 09:48:25 -0400
Reference:                                             Deployment/busybox
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 80%
Min replicas:                                          2
Max replicas:                                          4
Deployment pods:                                       2 current / 2 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: missing request for cpu
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Normal   SuccessfulRescale             2m10s              horizontal-pod-autoscaler  New size: 2; reason: Current number of replicas below Spec.MinReplicas
  Warning  FailedGetResourceMetric       5s (x8 over 113s)  horizontal-pod-autoscaler  missing request for cpu
  Warning  FailedComputeMetricsReplicas  5s (x8 over 113s)  horizontal-pod-autoscaler  failed to compute desired number of replicas based on listed metrics for Deployment/default/busybox: invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: missing request for cpu
```

So the key to this problem is to fix the metrics error, which I did by adding resource limits to my Deployment containers

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
        imagePullPolicy: IfNotPresent
        name: busybox
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: busybox
  namespace: default
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: busybox
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
```

With this in place, the HPA can compute a desired replica count based on the metric and sets the `desired` value appropriately

```
Name:                                                  busybox
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Wed, 30 Jun 2021 12:31:05 -0400
Reference:                                             Deployment/busybox
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  0% (0) / 80%
Min replicas:                                          1
Max replicas:                                          2
Deployment pods:                                       1 current / 1 desired
Conditions:
  Type            Status  Reason               Message
  ----            ------  ------               -------
  AbleToScale     True    ScaleDownStabilized  recent recommendations were higher than current one, applying the highest recent recommendation
  ScalingActive   True    ValidMetricFound     the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange   the desired count is within the acceptable range
Events:
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Warning  FailedGetResourceMetric       32s (x3 over 64s)  horizontal-pod-autoscaler  did not receive metrics for any ready pods
  Warning  FailedComputeMetricsReplicas  32s (x3 over 64s)  horizontal-pod-autoscaler  failed to compute desired number of replicas based on listed metrics for Deployment/default/busybox: invalid metrics (1 invalid out of 1), first error is: failed to get cpu utilization: did not receive metrics for any ready pods
  ```

In all cases when the Deployment's `replicas` starts out within the range of the HPA's `minReplicas`/`maxReplicas` range, the HPA will look to the metrics to determine the `desired` replicas, and if it can't do that it will set it to `0`

I don't think this is really an issue - but if you wanted the case when current replicas is already in the min/max range as it does when it starts outside the range, then this [code](https://github.com/kubernetes/kubernetes/blob/1534e0c7ec0c9d88ffb13ecc41975b33ead709ab/pkg/controller/podautoscaler/horizontal.go#L654-L661) could be changed to

```go
		if err != nil {
			if currentReplicas >= hpa.Spec.MinReplicas && currentReplicas <= hpa.Spec.MinReplicas {
				desiredReplicas = currentReplicas
			}
			a.setStatus(hpa, currentReplicas, desiredReplicas, hpa.Status.CurrentMetrics, false)
			if err := a.updateStatusIfNeeded(hpaStatusOriginal, hpa); err != nil {
				utilruntime.HandleError(err)
			}
			a.eventRecorder.Event(hpa, v1.EventTypeWarning, "FailedComputeMetricsReplicas", err.Error())
			return fmt.Errorf("failed to compute desired number of replicas based on listed metrics for %s: %v", reference, err)
		}
```
