### ISSUE TITLE
Conntrack table not flushed for UDP hostPort on pod restart (DaemonSet)

### ISSUE THREAD

**Issue by xytis** [kubernetes/kubernetes#102559]
#### What happened:
DaemonSet with port bound to hostPort is set up to accept UDP traffic. UDP traffic is generated from other pods, delivered to HOST_IP. (Real world example: Datadog agents with statsd metrics)

DaemonSet is rolled out. IP's of DaemonSet pods change. UDP traffic no longer reach DaemonSet pods. (Real world case: metrics not delivered)

#### What you expected to happen:

UDP traffic should reach new DaemonSet pods.

#### How to reproduce it (as minimally and precisely as possible):

DaemonSet
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: udp-port-listener
spec:
  selector:
    matchLabels:
      app: udp-port-listener
  template:
    metadata:
      labels:
        app: udp-port-listener
    spec:
      containers:
        - image: mendhak/udp-listener
          name: listener
          ports:
            - containerPort: 5005
              hostPort: 5005
              name: listener
              protocol: UDP
```

UDP producer
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-sender
spec:
  replicas: 8
  selector:
    matchLabels:
      app: udp-sender
  template:
    metadata:
      labels:
        app: udp-sender
    spec:
      containers:
        - name: udp-sender
          image: busybox
          command:
            - sh
            - -c
            - "while true; do echo -n $(date) | nc -n -u -w1 -p 65300 $HOST_IP 5005; sleep 0.1s; done;"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
```

1. Deploy DaemonSet
2. Deploy Deployment
3. Confirm UDP traffic is flowing from DaemonSet logs:
  ```
  Listening on UDP port 5005
  Thu Jun 3 08:55:02 UTC 2021
  Thu Jun 3 08:55:02 UTC 2021
  ...
  ```
4. Delete one DaemonSet pod (ensure pod IP changes)
5. Confirm UDP traffic is not flowing to restarted pod.

#### Anything else we need to know?:

Issue has exact same root cause as https://github.com/kubernetes/kubernetes/issues/96174
Fix should be the same, just in different code area.

Manual fix involves logging to affected nodes and performing conntrack cleansing:
```
conntrack -D -p udp --dport 5005 --dst-nat <initial pod IP>
```

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
```
AWS EKS
```

- OS (e.g: `cat /etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

- Kernel (e.g. `uname -a`):
```
Linux ip-10-0-2-210.ec2.internal 5.4.117-58.216.amzn2.x86_64 #1 SMP Tue May 11 20:50:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- Network plugin and version (if this is a network-related bug):
EKS default network, networking based on iptables
