### ISSUE TITLE
HPA scale up policies are ignored and default algorithm is used

### ISSUE THREAD

**Issue by amirschw** [kubernetes/kubernetes#102633]
#### What happened:
I created an HPA with a custom spec.behavior field, and the [default algorithm](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details) was used instead of the scale up behavior I defined.

My scale up behavior - add max{100 pods, 100% of the currently running replicas}:
```YAML
  behavior:
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      - periodSeconds: 15
        type: Pods
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 0
```

Actual behavior - default algorithm:

1. ceil[1 * ( 184 / 55 )] = 4
2. ceil[4 * ( 149 / 55 )] = 11
3. ceil[11 * ( 132 / 55 )] != 15 - unexplained...
3. ceil[15 * ( 105 / 55 )] = 29
4. ceil[29 * ( 89 / 55 )] = 47
5. ceil[47 * ( 62 / 55 )] = 53
6. ceil[53 * ( 64 / 55 )] = 62

```bash
~ $ kubectl get hpa php-apache -w
NAME         REFERENCE               TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
php-apache   Deployment/php-apache   184%/55%        1         1000      1          21m
php-apache   Deployment/php-apache   184%/55%        1         1000      1          21m
php-apache   Deployment/php-apache   184%/55%        1         1000      4          21m
php-apache   Deployment/php-apache   202%/55%        1         1000      4          22m
php-apache   Deployment/php-apache   149%/55%        1         1000      4          23m
php-apache   Deployment/php-apache   149%/55%        1         1000      11         23m
php-apache   Deployment/php-apache   132%/55%        1         1000      11         24m
php-apache   Deployment/php-apache   132%/55%        1         1000      15         24m
php-apache   Deployment/php-apache   105%/55%        1         1000      15         25m
php-apache   Deployment/php-apache   105%/55%        1         1000      29         25m
php-apache   Deployment/php-apache   89%/55%         1         1000      29         26m
php-apache   Deployment/php-apache   89%/55%         1         1000      47         26m
php-apache   Deployment/php-apache   62%/55%         1         1000      47         27m
php-apache   Deployment/php-apache   62%/55%         1         1000      53         27m
php-apache   Deployment/php-apache   7%/55%          1         1000      53         28m
php-apache   Deployment/php-apache   83%/55%         1         1000      53         29m
php-apache   Deployment/php-apache   64%/55%         1         1000      53         30m
php-apache   Deployment/php-apache   64%/55%         1         1000      53         31m
php-apache   Deployment/php-apache   64%/55%         1         1000      62         31m
php-apache   Deployment/php-apache   58%/55%         1         1000      62         31m
```

#### What you expected to happen:
The controller should scale up based on the given scale up behavior.

#### How to reproduce it (as minimally and precisely as possible):
1. Create a Deployment, Service and HPA using the following manifest (based on the [HPA walkthrough](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/)): `kubectl apply -f hpa-repro.yaml`
```YAML
# hpa-repro.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  replicas: 1
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  ports:
  - port: 80
  selector:
    run: php-apache
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      - periodSeconds: 15
        type: Pods
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 1000
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 55
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
```
2. Increase load: `for i in {1..10}; do kubectl run load-generator-${i} --image=busybox --restart=Never --
 /bin/sh -c "while sleep 0.01; do wget -q -O- http://php-apache; done"; done`
3. Observe the HPA behavior: `kubectl get hpa php-apache -w`
4. Clean up: `kubectl delete -f hpa-repro.yaml; for i in {1..10}; do kubectl delete po load-generator-${i}; done`
#### Environment:
- Kubernetes version (use `kubectl version`): reproduced in v1.19.8 and v1.19.9
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T23:36:21Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure (AKS Engine)
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1048-azure
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig autoscaling
