### ISSUE TITLE
Memory Reservations on Windows Pod

### ISSUE THREAD

**Issue by zhiweiv** [kubernetes/kubernetes#102686]
In https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#memory-reservations,
> As you deploy workloads, use resource limits (must set only limits or _**limits must equal requests**_) on containers.

It says limits must equal requests for memory, does it make sense? We are using following setting and it works.

```
resources:
  requests:
    memory: 1Gi
  limits:
    memory: 4Gi
```

/sig windows
