### ISSUE TITLE
Dualstack : Validation issues when creating services

### ISSUE THREAD

**Issue by VivekThrivikraman-est** [kubernetes/kubernetes#102654]
#### What happened:
Tried creating services with the below configurations(invalid configuration) in a DualStack cluster, the service creation didn't give any error:

1. Mutating an existing service with ipFamilyPolicy: RequireDualStack   ipFamilies: IPv4,IPv6 to ipFamilyPolicy: SingleStack   ipFamilies: IPv4,IPv6(or IPv4,IPv4)

2. Create a new service with  ipFamilyPolicy: RequireDualStack ,  ipFamilies: IPv4

#### What you expected to happen:
kubectl apply command is supposed to fail with appropriate error messages.

#### How to reproduce it (as minimally and precisely as possible):
Issue 1)
               a) Create a new service with following config:   ipFamilyPolicy: RequireDualStack and ipFamilies: ["IPv4","IPv6"]
               b) Edit the service created above and try to apply following config: ipFamilyPolicy: SingleStack and ipFamilies: ["IPv6"] , This would fail with error as expected.
               c) Edit the service again and try to apply following config: :  ipFamilyPolicy: SingleStack, ipFamilies: ["IPv4","IPv6"] (or even "IPv4","IPv4" as ipFamilies value).
                   Kubectl apply command does not give any error. 
                   Most of the time with just steps a) and c) it is reproducible, but always reproducible with a),b) and c).
                  Terminal logs attached : 
[singlestack_2families.txt](https://github.com/kubernetes/kubernetes/files/6606976/singlestack_2families.txt)

Issue 2)
              a) Create a new Service with following config: ipFamilyPolicy: RequireDualStack , ipFamilies: ["IPv4"] .
                 The service is created and there are no errors.
                 Terminal logs:
[requiredualstack_1family.txt](https://github.com/kubernetes/kubernetes/files/6607183/requiredualstack_1family.txt)

                 
               

#### Environment:
- Kubernetes version (use `kubectl version`): "v1.21.1"
- Cloud provider or hardware configuration: local
- OS (e.g: `cat /etc/os-release`): NAME="Ubuntu" VERSION="20.04.2 LTS (Focal Fossa)"
- Kernel (e.g. `uname -a`): Linux ccd-focal-clus2-1 5.4.0-66-generic 
- Install tools:
- Network plugin and version (if this is a network-related bug): calico
- Others:

**Comment by VivekThrivikraman-est** [comment]
@aojea

**Comment by aojea** [comment]
I run the described cases in `v1.22.0-alpha.1.28+6baad0a1d45435` and one validated correctly
```
cat > test-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: testbanana-ci-service
spec:
  type: ClusterIP
  selector:
    app: banana
  ipFamilyPolicy: SingleStack
  ipFamilies: ["IPv4","IPv6"]
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5678
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
[aojea@juanan ~]$ kubectl apply -f test-svc.yaml 
The Service "testbanana-ci-service" is invalid: spec.ipFamilyPolicy: Invalid value: "SingleStack": must be RequireDualStack or PreferDualStack when multiple 'ipFamilies' are specified
```

for the second case I think that is the expected behaviour
```
cat test-svc2.yaml 
apiVersion: v1
kind: Service
metadata:
  name: testbanana-ci-service
spec:
  type: ClusterIP
  selector:
    app: banana
  ipFamilyPolicy: RequireDualStack
  ipFamilies: ["IPv4"]
```

the apiserver completes the ipFamilies field after creation:
```
kubectl get svc service/testbanana-ci-service -o yaml                                                                                                                                           
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"testbanana-ci-service","namespace":"default"},"spec":{"ipFamilies":["IPv4"],"ipFamilyPolicy":"RequireDualStack","ports":[{"port":5678}],"selector":{"app":"banana"},"type":"ClusterIP"}}
  creationTimestamp: "2021-06-07T09:42:08Z"
...
...
spec:
  clusterIP: 10.96.127.52
  clusterIPs:
  - 10.96.127.52
  - fd00:10:96::319a
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
```

@khenidak can you please double check?
