### ISSUE TITLE
owner reference configured in pod template would not be added to the pod created by replica set

### ISSUE THREAD

**Issue by CodeNoobKc2** [kubernetes/kubernetes#102720]
#### What happened:
The pod created by replicaset does not include the ownerreference information configured in pod template. In my scenerio, the pod template is automatically generated by my operator.

#### What you expected to happen:
I expect the pod created by relicaset controller would include the ownerreference information configured in pod template.

#### How to reproduce it (as minimally and precisely as possible):
Given the following yaml
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    hello: the-wrold
  namespace: kube-operator
  ownerReferences:
  - apiVersion: <my-crd-group>/v1
    blockOwnerDeletion: true
    controller: true
    kind: <my-crd>
    name: nginx
    uid: <uid>
spec:
  replicas: 1
  selector:
    matchLabels:
      hello: the-wrold
  template:
    metadata:
      labels:
        hello: the-wrold
      ownerReferences:
      - apiVersion: <my-crd-group>/v1
        blockOwnerDeletion: true
        controller: true
        kind: <my-crd>
        name: nginx
        uid: <uid>
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
```
First use kubectl apply -f <file.yaml> -n <namspace> to apply the above yaml.
Then use kubectl get -n <namspace> rs nginx-rs -o yaml, one should discovered that only the following value are stored in ownerReferences field:
```
 ownerReferences:
  - apiVersion: <my-crd-group>/v1
    blockOwnerDeletion: true
    controller: true
    kind: <my-crd>
    name: nginx
    uid: <uid>
```

#### Anything else we need to know?:
I wonder whether  not including the owner references configured in the template is the intended behaviour or a bug.

#### Environment:
- Kubernetes version (use `kubectl version`):
1.17.6
