### ISSUE TITLE
Volume type of ephemeral is not recognized

### ISSUE THREAD

**Issue by JDSQ** [kubernetes/kubernetes#102706]
#### What happened:
I then tried to add a pod that uses an ephemeral volume:
```
kind: Pod
apiVersion: v1
metadata:
  name: my-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/scratch"
        name: scratch-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: scratch-volume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: my-frontend-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "efs-sc"
            resources:
              requests:
                storage: 1Gi
```

This resulted in the following response:
```
The Pod "my-app" is invalid: 
* spec.volumes[0]: Required value: must specify a volume type
* spec.containers[0].volumeMounts[0].name: Not found: "scratch-volume"

```

This example is taken directly from the Kubernetes documentation: https://v1-19.docs.kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes

#### What you expected to happen:
The pod to be launched with an ephemeral volume

#### How to reproduce it (as minimally and precisely as possible):
1. Add storage class
2. Try to add the pod

#### Anything else we need to know?:
This is my storage class yaml:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
mountOptions:
  - tls
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxxxxxxx
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/scratch"
```

#### Environment:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Running on 
- OS (e.g: `cat /etc/os-release`): 
- Others:
I enabled the feature gate for GenericEphemeralVolume

> root     27418 27400  2 May05 ?        21:40:22 kubelet --cluster-dns=10.43.0.10 --cni-conf-dir=/etc/cni/net.d --fail-swap-on=false --address=0.0.0.0 --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --cloud-provider= --cgroups-per-qos=True --event-qps=0 --network-plugin=cni --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --v=2 --cluster-domain=cluster.local --hostname-override=ip-172-31-14-247 --cni-bin-dir=/opt/cni/bin --max-pods=110 --pod-infra-container-image=rancher/mirrored-pause:3.2 --root-dir=/var/lib/kubelet --authentication-token-webhook=true --volume-plugin-dir=/var/lib/kubelet/volumeplugins --authorization-mode=Webhook --streaming-connection-idle-timeout=30m --anonymous-auth=false --resolv-conf=/etc/resolv.conf --make-iptables-util-chains=true **--feature-gates=GenericEphemeralVolume=true** --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml --read-only-port=0 --cgroup-driver=cgroupfs --resolv-conf=/run/systemd/resolve/resolv.conf

/sig storage
