### ISSUE TITLE
Pod with spec.priority configured cannot be created if priority admission controller enabled

### ISSUE THREAD

**Issue by tanjing2020** [kubernetes/kubernetes#102724]
#### What happened:
If the priority admission controller is enabled, pod configures spec.priority, and does not configure spec.priorityClassName, it cannot created.
```
pod.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: hello
    image: k8s.gcr.io/e2e-test-images/agnhost:2.31
    command: ['sh', '-c', 'sleep 3600']
  restartPolicy: OnFailure
  priority: 0

```
```
root@node4:/usr1/k8s/src/k8s.io/yaml# kubectl apply -f pod.yaml
Error from server (Forbidden): error when creating "pod.yaml": pods "hello" is forbidden: the integer value of priority (1) must not be provided in pod spec; priority admission controller computed 0 from the given PriorityClass name
```
#### What you expected to happen:
In case of  enable priority admission controller, we can choose  spec.priority or spec.priorityClassName flexibly to configure the pod priority.

#### How to reproduce it (as minimally and precisely as possible):
① Use hack/local-up-cluster.sh to create a local cluster，and priority admission controller is enabled.
② Create a pod with a priority value，use spec.priority. 

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
