### ISSUE TITLE
Windows Pods with a Projected Volume is stuck at ContainerCreating

### ISSUE THREAD

**Issue by aravindhp** [kubernetes/kubernetes#102849]
#### What happened:

When a Windows Pod is created with a Projected Volume is stuck at ContainerCreating

#### What you expected to happen:

The Pod should go to Running.

#### How to reproduce it (as minimally and precisely as possible):

Create a Windows Pod with a Projected Volume.

#### Anything else we need to know?:

The KEP, [proposal for file permission handling in projected service account volume](https://github.com/kubernetes/kubernetes/commit/3db7275b549559696c42c0b5f51c9a2397e9571d#diff-f4218ebfe0ced84087844da9d87b126752414e347e727c0455687d69e8e3d912) and its [implementation](https://github.com/kubernetes/kubernetes/commit/3db7275b549559696c42c0b5f51c9a2397e9571d) did not take Windows in to account. An [os.Chown()](https://github.com/kubernetes/kubernetes/commit/3db7275b549559696c42c0b5f51c9a2397e9571d#diff-f4218ebfe0ced84087844da9d87b126752414e347e727c0455687d69e8e3d912R403) was introduced which is not supported on Windows.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.1
- Cloud provider or hardware configuration: AWS / Azure 
- OS: Windows Server 2019 1809
- Kernel:

**Comment by aravindhp** [comment]
/retitle Windows Pod with RunAsUserName and a Projected Volume does not honor file permissions in the volume

**Comment by aravindhp** [comment]
Please follow sig-windows slack [thread](https://kubernetes.slack.com/archives/C0SJ4AFB7/p1623439088166000) for current state.

**Comment by aravindhp** [comment]
Currently investigating what is the current state of owner ship across users in different pods and containers. Created a simple ping container image with two users:
```Dockerfile
FROM mcr.microsoft.com/windows/servercore:ltsc2019
RUN net user TestUser1 /add
RUN net user TestUser2 /add
CMD ["ping", "-t", "localhost"]
```
Created the following pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: win-ping
spec:
  tolerations:
  - key: "os"
    value: "Windows"
    Effect: "NoSchedule"
  containers:
  - name: ping1
    image: quay.io/aravindh/win-ping
    imagePullPolicy: Always
    securityContext:
      windowsOptions:
        runAsUserName: TestUser1
    volumeMounts:
    - name: for-ping1
      mountPath: /projected-volume
    - name: c-volume
      mountPath: /from-host
  - name: ping2
    image: quay.io/aravindh/win-ping
    imagePullPolicy: Always
    securityContext:
      windowsOptions:
        runAsUserName: TestUser2
    volumeMounts:
    - name: for-ping2
      mountPath: /projected-volume
    - name: c-volume
      mountPath: /from-host
  nodeSelector:
    kubernetes.io/os: windows
  volumes:
  - name: for-ping1
    projected:
      sources:
      - secret:
          name: user
  - name: for-ping2
    projected:
      sources:
      - secret:
          name: pass
  - name: c-volume
    hostPath:
      path: /
```
I then execed into container ping1:
```bash
 kubectl exec win-ping -it powershell.exe -c ping1
```
and ran the following:
```powershell
PS C:\> whoami
win-ping\testuser1
PS C:\> cat C:\from-host\var\lib\kubelet\pods\d10783ef-919d-46bf-ab38-2b951f063632\volumes\kubernetes.io~projected\for-ping2\password.txt 
1f2d1e2e67df 
```
So `testuser1` is able to read a file projected for `testuser2`

**Comment by aravindhp** [comment]
I repeated the experiment with two pods running on the same host:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: win-ping1
spec:
  tolerations:
  - key: "os"
    value: "Windows"
    Effect: "NoSchedule"
  containers:
  - name: ping1
    image: quay.io/aravindh/win-ping
    imagePullPolicy: Always
    securityContext:
      windowsOptions:
        runAsUserName: TestUser1
    volumeMounts:
    - name: for-ping1
      mountPath: /projected-volume
    - name: c-volume
      mountPath: /from-host
  nodeSelector:
    kubernetes.io/os: windows
  volumes:
  - name: for-ping1
    projected:
      sources:
      - secret:
          name: user
  - name: c-volume
    hostPath:
      path: /
---
apiVersion: v1
kind: Pod
metadata:
  name: win-ping2
spec:
  tolerations:
  - key: "os"
    value: "Windows"
    Effect: "NoSchedule"
  containers:
  - name: ping2
    image: quay.io/aravindh/win-ping
    imagePullPolicy: Always
    securityContext:
      windowsOptions:
        runAsUserName: TestUser2
    volumeMounts:
    - name: for-ping2
      mountPath: /projected-volume
    - name: c-volume
      mountPath: /from-host
  nodeSelector:
    kubernetes.io/os: windows
  volumes:
  - name: for-ping2
    projected:
      sources:
      - secret:
          name: pass
  - name: c-volume
    hostPath:
      path: /
```
I then execed into win-ping1 pod:
```bash
 kubectl exec win-ping1 -it powershell.exe
```
and ran the following:
```pwsh
PS C:\> whoami
win-ping1\testuser1
PS C:\> cat C:\from-host\var\lib\kubelet\pods\b701defa-6138-4375-a6ec-f0c155973348\volumes\kubernetes.io~projected\for-ping2\password.txt 
1f2d1e2e67df
```
Again, `testuser1` is able to read a file projected for `testuser2`

**Comment by voigt** [comment]
Hey there (@immuzz, @jsturtevant, @aravindhp), Bug-Triage here 👋 ,
Given the fact that the code freeze for 1.22 already started I'd suggest moving this issue to 1.23. wdyt?

**Comment by marosset** [comment]
@voigt - We'll move it to 1.23 thanks!

**Comment by claudiubelu** [comment]
Indeed. I've tried this as well. It seems that those secrets have a read permission set by default for ``Everyone``, which will basically mean that anyone could read that, which shouldn't be the case in this scenario. But only the Read permission is set for ``Everyone``, so you can't write in it:

```
PS C:\tmp> wget https://github.com/kubernetes-sigs/windows-testing/raw/master/images/busybox/busybox.exe -UseBasicParsing -OutFile C:\tmp\busybox.exe
PS C:\tmp> .\busybox.exe stat C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping1\data_1
  File: C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping1\data_1
  Size: 0               Blocks: 0          IO Block: 4096   symbolic link
Device: 0h/0d   Inode: 0           Links: 1
Access: (0664/lrw-rw-r--)  Uid: ( 1000/TestUser1)   Gid: ( 1000/TestUser1)
Access: 2021-07-13 13:36:48.000000000
Modify: 2021-07-13 13:36:48.000000000
Change: 2021-07-13 13:36:48.000000000

PS C:\tmp> get-acl C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping1\data_1 | fl *


PSPath                  : Microsoft.PowerShell.Core\FileSystem::C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d
                          13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping1\data_1
PSParentPath            : Microsoft.PowerShell.Core\FileSystem::C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d
                          13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping1
PSChildName             : data_1
PSDrive                 : C
PSProvider              : Microsoft.PowerShell.Core\FileSystem
CentralAccessPolicyId   :
CentralAccessPolicyName :
Path                    : Microsoft.PowerShell.Core\FileSystem::C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d
                          13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping1\data_1
Owner                   : BUILTIN\Administrators
Group                   : NT AUTHORITY\SYSTEM
Access                  : {System.Security.AccessControl.FileSystemAccessRule,
                          System.Security.AccessControl.FileSystemAccessRule,
                          System.Security.AccessControl.FileSystemAccessRule}
Sddl                    : O:BAG:SYD:(A;ID;FA;;;BA)(A;ID;FA;;;SY)(A;ID;0x1200a9;;;BU)
AccessToString          : BUILTIN\Administrators Allow  FullControl
                          NT AUTHORITY\SYSTEM Allow  FullControl
                          BUILTIN\Users Allow  ReadAndExecute, Synchronize
AuditToString           :
AccessRightType         : System.Security.AccessControl.FileSystemRights
AccessRuleType          : System.Security.AccessControl.FileSystemAccessRule
AuditRuleType           : System.Security.AccessControl.FileSystemAuditRule
AreAccessRulesProtected : False
AreAuditRulesProtected  : False
AreAccessRulesCanonical : True
AreAuditRulesCanonical  : True

PS C:\tmp> .\busybox.exe stat C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping2\data_1
  File: C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping2\data_1
  Size: 0               Blocks: 0          IO Block: 4096   symbolic link
Device: 0h/0d   Inode: 0           Links: 1
Access: (0664/lrw-rw-r--)  Uid: ( 1000/TestUser1)   Gid: ( 1000/TestUser1)
Access: 2021-07-13 13:36:48.000000000
Modify: 2021-07-13 13:36:48.000000000
Change: 2021-07-13 13:36:48.000000000

PS C:\tmp> get-acl C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping2\data_1 | fl *


PSPath                  : Microsoft.PowerShell.Core\FileSystem::C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d
                          13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping2\data_1
PSParentPath            : Microsoft.PowerShell.Core\FileSystem::C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d
                          13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping2
PSChildName             : data_1
PSDrive                 : C
PSProvider              : Microsoft.PowerShell.Core\FileSystem
CentralAccessPolicyId   :
Path                    : Microsoft.PowerShell.Core\FileSystem::C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d
                          13-9731-4d00d30100c9\volumes\kubernetes.io~projected\for-ping2\data_1
Owner                   : BUILTIN\Administrators
Group                   : NT AUTHORITY\SYSTEM
Access                  : {System.Security.AccessControl.FileSystemAccessRule,
                          System.Security.AccessControl.FileSystemAccessRule,
                          System.Security.AccessControl.FileSystemAccessRule}
Sddl                    : O:BAG:SYD:(A;ID;FA;;;BA)(A;ID;FA;;;SY)(A;ID;0x1200a9;;;BU)
AccessToString          : BUILTIN\Administrators Allow  FullControl
                          NT AUTHORITY\SYSTEM Allow  FullControl
                          BUILTIN\Users Allow  ReadAndExecute, Synchronize
AuditToString           :
AccessRightType         : System.Security.AccessControl.FileSystemRights
AccessRuleType          : System.Security.AccessControl.FileSystemAccessRule
AuditRuleType           : System.Security.AccessControl.FileSystemAuditRule
AreAccessRulesProtected : False
AreAuditRulesProtected  : False
AreAccessRulesCanonical : True
AreAuditRulesCanonical  : True


PS C:\tmp> cat C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volumes\kubernetes.io~project
ed\for-ping2\data_1
hello there!
PS C:\tmp> echo "a different hello" > C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volume
s\kubernetes.io~projected\for-ping2\data_1
out-file : Access to the path 'C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volumes\kube
rnetes.io~projected\for-ping2\data_1' is denied.
At line:1 char:1
+ echo "a different hello" > C:\from-host\var\lib\kubelet\pods\1ed0e73d ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], UnauthorizedAccessException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

PS C:\tmp> echo "a different hello" > C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volume
s\kubernetes.io~projected\for-ping1\data_1
out-file : Access to the path 'C:\from-host\var\lib\kubelet\pods\1ed0e73d-e9d6-4d13-9731-4d00d30100c9\volumes\kube
rnetes.io~projected\for-ping1\data_1' is denied.
At line:1 char:1
+ echo "a different hello" > C:\from-host\var\lib\kubelet\pods\1ed0e73d ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], UnauthorizedAccessException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

```

I think the first step would be chown the volumes first, and afterwards remove the Read permission for ``Everyone`` (otherwise, we wouldn't be able to read the secret at all if we're running as an Administrator).

**Comment by liggitt** [comment]
cc @msau42 @zshihang fyi

**Comment by yukirii** [comment]
I am facing the issue with similar error messages. I have an AKS cluster which has Windows node pool. The initial K8s version is 1.20.7. I deployed the sample application and Pod was started successfully. Then I upgraded the cluster K8s version to 1.21.1.
`az aks upgrade --resource-group wincluster_group --name wincluster --kubernetes-version 1.21.1`

```
% k get nodes
NAME                                STATUS   ROLES   AGE   VERSION
aks-agentpool-18013334-vmss000000   Ready    agent   74m   v1.20.7
akswinnp000000                      Ready    agent   45m   v1.20.7
% k get pods -o wide
NAME                      READY   STATUS    RESTARTS   AGE   IP             NODE             NOMINATED NODE   READINESS GATES
sample-5b49874c85-t4fks   1/1     Running   0          31m   10.240.0.141   akswinnp000000   <none>           <none>
```

After upgraded K8s version, the Pod is stuck at `ContainerCreating` and `FailedMount` events occurred.

```
% k get nodes
NAME                                STATUS   ROLES   AGE   VERSION
aks-agentpool-18013334-vmss000000   Ready    agent   38m   v1.21.1
akswinnp000000                      Ready    agent   33m   v1.21.1
% k get pods -o wide
NAME                      READY   STATUS              RESTARTS   AGE   IP       NODE             NOMINATED NODE   READINESS GATES
sample-5b49874c85-2m9km   0/1     ContainerCreating   0          33m   <none>   akswinnp000000   <none>           <none>
```

Pod events:
```
Warning  FailedMount       11m (x10 over 32m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[kube-api-access-jjnld], unattached volumes=[kube-api-access-jjnld]: timed out waiting for the condition
Warning  FailedMount       3m36s (x16 over 32m)  kubelet            (combined from similar events): MountVolume.SetUp failed for volume "kube-api-access-jjnld" : chown c:\var\lib\kubelet\pods\69616e2b-11a3-4927-a521-e28e67061831\volumes\kubernetes.io~projected\kube-api-access-jjnld\..2021_09_17_05_07_10.049812282\token: not supported by windows
```

YAML I used (copied from [this document](https://docs.microsoft.com/en-us/azure/aks/windows-container-cli#run-the-application)):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  template:
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: sample
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: sample
```

I added a new nodepool and moved the Pod. The issue still occurred at the new node.

```
% kubectl get nodes
NAME                                STATUS                     ROLES   AGE    VERSION
aks-agentpool-18013334-vmss000000   Ready                      agent   12d    v1.21.1
aksnpwin2000000                     Ready                      agent   2d8h   v1.21.1
akswinnp000000                      Ready,SchedulingDisabled   agent   12d    v1.21.1

% kubectl get pods -o wide
NAME                      READY   STATUS              RESTARTS   AGE   IP       NODE              NOMINATED NODE   READINESS GATES
sample-5b49874c85-kgnkb   0/1     ContainerCreating   0          28s   <none>   aksnpwin2000000   <none>           <none>

% kubectl describe pod sample-5b49874c85-kgnkb
Name:           sample-5b49874c85-kgnkb
Namespace:      default
Priority:       0
Node:           aksnpwin2000000/10.240.0.146
Start Time:     Wed, 29 Sep 2021 22:19:00 +0900
Labels:         app=sample
                pod-template-hash=5b49874c85
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/sample-5b49874c85
Containers:
  sample:
    Container ID:
    Image:          mcr.microsoft.com/dotnet/framework/samples:aspnetapp
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  800M
    Requests:
      cpu:        100m
      memory:     300M
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-z5jm5 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-z5jm5:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=windows
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age   From               Message
  ----     ------       ----  ----               -------
  Normal   Scheduled    38s   default-scheduler  Successfully assigned default/sample-5b49874c85-kgnkb to aksnpwin2000000
  Warning  FailedMount  39s   kubelet            MountVolume.SetUp failed for volume "kube-api-access-z5jm5" : chown c:\var\lib\kubelet\pods\68af1fc1-10c1-420d-bbf7-b182686f8126\volumes\kubernetes.io~projected\kube-api-access-z5jm5\..2021_09_29_13_19_00.252578569\token: not supported by windows
  Warning  FailedMount  38s   kubelet            MountVolume.SetUp failed for volume "kube-api-access-z5jm5" : chown c:\var\lib\kubelet\pods\68af1fc1-10c1-420d-bbf7-b182686f8126\volumes\kubernetes.io~projected\kube-api-access-z5jm5\..2021_09_29_13_19_01.101299924\token: not supported by windows
  Warning  FailedMount  37s   kubelet            MountVolume.SetUp failed for volume "kube-api-access-z5jm5" : chown c:\var\lib\kubelet\pods\68af1fc1-10c1-420d-bbf7-b182686f8126\volumes\kubernetes.io~projected\kube-api-access-z5jm5\..2021_09_29_13_19_02.191861795\token: not supported by windows
  Warning  FailedMount  35s   kubelet            MountVolume.SetUp failed for volume "kube-api-access-z5jm5" : chown c:\var\lib\kubelet\pods\68af1fc1-10c1-420d-bbf7-b182686f8126\volumes\kubernetes.io~projected\kube-api-access-z5jm5\..2021_09_29_13_19_04.928033062\token: not supported by windows
  Warning  FailedMount  31s   kubelet            MountVolume.SetUp failed for volume "kube-api-access-z5jm5" : chown c:\var\lib\kubelet\pods\68af1fc1-10c1-420d-bbf7-b182686f8126\volumes\kubernetes.io~projected\kube-api-access-z5jm5\..2021_09_29_13_19_08.553316429\token: not supported by windows
  Warning  FailedMount  23s   kubelet            MountVolume.SetUp failed for volume "kube-api-access-z5jm5" : chown c:\var\lib\kubelet\pods\68af1fc1-10c1-420d-bbf7-b182686f8126\volumes\kubernetes.io~projected\kube-api-access-z5jm5\..2021_09_29_13_19_16.550898504\token: not supported by windows
  Warning  FailedMount  7s    kubelet            MountVolume.SetUp failed for volume "kube-api-access-z5jm5" : chown c:\var\lib\kubelet\pods\68af1fc1-10c1-420d-bbf7-b182686f8126\volumes\kubernetes.io~projected\kube-api-access-z5jm5\..2021_09_29_13_19_32.073144839\token: not supported by windows
```

kubelet log:

```
E0929 12:55:30.388796    3780 atomic_writer.go:404] pod default/sample-5b49874c85-crpft volume kube-api-access-425pc: unable to change file c:\var\lib\kubelet\pods\8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5\volumes\kubernetes.io~projected\kube-api-access-425pc\..2021_09_29_12_55_30.646331698\token with owner 0: chown c:\var\lib\kubelet\pods\8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5\volumes\kubernetes.io~projected\kube-api-access-425pc\..2021_09_29_12_55_30.646331698\token: not supported by windows
E0929 12:55:30.388796    3780 atomic_writer.go:175] pod default/sample-5b49874c85-crpft volume kube-api-access-425pc: error writing payload to ts data directory c:\var\lib\kubelet\pods\8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5\volumes\kubernetes.io~projected\kube-api-access-425pc\..2021_09_29_12_55_30.646331698: chown c:\var\lib\kubelet\pods\8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5\volumes\kubernetes.io~projected\kube-api-access-425pc\..2021_09_29_12_55_30.646331698\token: not supported by windows
E0929 12:55:30.388796    3780 projected.go:236] Error writing payload to dir: chown c:\var\lib\kubelet\pods\8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5\volumes\kubernetes.io~projected\kube-api-access-425pc\..2021_09_29_12_55_30.646331698\token: not supported by windows
W0929 12:55:30.389462    3780 empty_dir.go:520] Warning: Failed to clear quota on c:\var\lib\kubelet\pods\8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5\volumes\kubernetes.io~projected\kube-api-access-425pc: not implemented
E0929 12:55:30.390571    3780 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/projected/8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5-kube-api-access-425pc podName:8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5 nodeName:}" failed. No retries permitted until 2021-09-29 12:57:32.3900363 +0000 GMT m=+461.046606301 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"kube-api-access-425pc\" (UniqueName: \"kubernetes.io/projected/8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5-kube-api-access-425pc\") pod \"sample-5b49874c85-crpft\" (UID: \"8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5\") : chown c:\\var\\lib\\kubelet\\pods\\8cbb6441-8f70-4dbe-a1fe-3c7bf7e4b4c5\\volumes\\kubernetes.io~projected\\kube-api-access-425pc\\..2021_09_29_12_55_30.646331698\\token: not supported by windows"
```

#### Environment:

- Kubernetes version (use `kubectl version`): v1.21.1
- Cloud provider or hardware configuration: Azure Kubernetes Service (AKS)
- OS: Windows Server 2019 Datacenter 10.0.17763.2183
