### ISSUE TITLE
400 bad request on Azure cloud provider loadbalancer service TCP health probe (requestpath null)

### ISSUE THREAD

**Issue by mweibel** [kubernetes/kubernetes#102803]
#### What happened:
Creating a service `type: Loadbalancer` with `externalTrafficPolicy: Local` fails to be created when trying to use a TCP health probe. 
Example service:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: TCP
  labels:
    app: lbtest
  name: lbtest
spec:
  externalTrafficPolicy: Local
  ports:
    - name: smb
      port: 445
      protocol: TCP
      targetPort: 445
  selector:
    app: lbtest
  sessionAffinity: None
  type: LoadBalancer
```

Failed as follows:
```
$ kubectl describe svc lbtest
Name:                     lbtest
Namespace:                default
Labels:                   app=lbtest
Annotations:              service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: TCP
                          service.beta.kubernetes.io/azure-load-balancer-internal: true
Selector:                 app=lbtest
Type:                     LoadBalancer
IP Families:              <none>
IP:                       10.43.54.185
IPs:                      10.43.54.185
Port:                     smb  445/TCP
TargetPort:               445/TCP
NodePort:                 smb  30790/TCP
Endpoints:                10.42.7.13:445
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     31438
Events:
  Type     Reason                  Age              From                Message
  ----     ------                  ----             ----                -------
  Normal   EnsuringLoadBalancer    2s (x2 over 7s)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  1s (x2 over 7s)  service-controller  Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "ProbeRequestPathIsNotNull",
    "message": "Request path for probe /subscriptions/<uuid>/resourceGroups/<rgname>/providers/Microsoft.Network/loadBalancers/kubernetes-internal/probes/<probeuuid>-TCP-445 must be null when its protocol is Tcp.",
    "details": []
  }
}
```

#### What you expected to happen:
Health probe works correctly and is registered properly as TCP health probe.

#### How to reproduce it (as minimally and precisely as possible):
Take the mentioned service yaml and apply it, together with a corresponding pod / deployment exposing port 445. E.g. like this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lbtest
  name: lbtest
spec:
  selector:
    matchLabels:
      app: lbtest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lbtest
    spec:
      containers:
        - args:
            - -g
            - log level = 2
            - -g
            - server multi channel support = yes
            - -g
            - aio read size = 1
            - -g
            - aio write size = 1
            - -u
            - $(USERNAME);$(PASSWORD)
            - -s
            - data;/data/;yes;no;no;all;none
            - -r
            - -p
          env:
            - name: VETO
              value: "no"
            - name: USERNAME
              value: test
            - name: PASSWORD
              value: test
          image: dperson/samba:latest
          imagePullPolicy: IfNotPresent
          name: samba
          ports:
            - containerPort: 445
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 445
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lbtest
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lbtest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: azure-ssd
```

#### Anything else we need to know?:
The respective code seems to take the wrong path to me (it's +/- the same code on the in-tree as on the out of tree cloud provider):
https://github.com/kubernetes/legacy-cloud-providers/blob/release-1.20/azure/azure_loadbalancer.go#L1644
https://github.com/kubernetes/legacy-cloud-providers/blob/release-1.20/azure/azure_loadbalancer.go#L1590
https://github.com/kubernetes/cloud-provider/blob/release-1.20/service/helpers/helper.go#L87

My reading of the code and passed values are like this:
- `parseHealthProbeProtocolAndPath(service)` returns `("tcp", "")`
- `servicehelpers.NeedsHealthCheck(service)` returns `true`
-- because `servicehelpers.RequestsOnlyLocalTraffic(service)` returns `true`
- `servicehelpers.GetServiceHealthCheckPathPort(service)` returns `("/healthz", 445)`
therefore:

```go
	probeProtocol, requestPath := "tcp", ""
	podPresencePath, podPresencePort := "/healthz", 445
	if probeProtocol == "" {
		probeProtocol = string(network.ProbeProtocolHTTP)
	}
	// ########## This is wrong here, now it sets requestPath to "/healthz"
	if requestPath == "" {
		requestPath = podPresencePath
	}

	expectedProbes = append(expectedProbes, network.Probe{
		Name: &lbRuleName,
		ProbePropertiesFormat: &network.ProbePropertiesFormat{
			RequestPath:       to.StringPtr(requestPath),
			Protocol:          network.ProbeProtocol(probeProtocol),
			Port:              to.Int32Ptr(podPresencePort),
			IntervalInSeconds: to.Int32Ptr(5),
			NumberOfProbes:    to.Int32Ptr(2),
		},
	})
```

So the requestPath is not `null/nil` at this point and the azure API server returns a 400 bad request.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.6
- Cloud provider or hardware configuration: azure
- OS (e.g: `cat /etc/os-release`): linux
- Network plugin and version (if this is a network-related bug): vxlan & flannel
