### ISSUE TITLE
Support setting owner references declaratively 

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/kubernetes#102810]
#### What would you like to be added:

It'd be nice to setup owner references declaratively when creating a suite of resources using `kubectl apply -f` 

#### Why is this needed:

Users tend to try to clean up a Knative installation by deleting the 'namespace' in contrast using `kubectl delete -f`. Deleting the namespace leaves a bunch of cluster scoped resources around.

If we could setup owner references properly we could enable this user flow. But we obviously don't know the owner uids and can't do this declaratively at this moment.

**Comment by dprotaso** [comment]
Maybe this is also a API concern?
/sig api-machinery

**Comment by dprotaso** [comment]
Ideally it would be nice if this fix wasn't only for `kubectl` but something that the API could handle. That would open up the ability for other tools to mimic the same behaviour

**Comment by kwiesmueller** [comment]
Just to clarify what you're asking for.
Do you want to set ownerRefs to all resources managed in a single apply command?
What would be the owner you add? The namespace, some other resource? How would you like to specify the owner?

I'm not sure if this is an apply only feature or if the cli should record all the resources it touched and allow you to patch them all with an ownerRef afterwards.

**Comment by dprotaso** [comment]
I think I'd prefer to be explicit and declare owner references in the resources explicitly - and the API server just populate the UIDs


```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: some-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
  ownerReferences:
  - apiVersion: v1
    kind: Namespace
    name: some-namespace
    blockOwnerDeletion: true
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
```
