### ISSUE TITLE
Resource Quota Per PriorityClass is not working on ephemeral-storage

### ISSUE THREAD

**Issue by henrysecond1** [kubernetes/kubernetes#102996]
#### What happened:

According to the [document](https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-per-priorityclass), it is expected that resource quota for `ephemeral-storage` can be configured per PriorityClass.

However, below error occurs when I deployed `ResourceQuota` on `ephemeral-storage` with `PriorityClass` scopeSelector.

```sh
The ResourceQuota "example-quota" is invalid: spec.scopeSelector.matchExpressions: Invalid value: core.ScopeSelector{MatchExpressions:[]core.ScopedResourceSelectorRequirement{core.ScopedResourceSelectorRequirement{ScopeName:"PriorityClass", Operator:"In", Values:[]string{"normal"}}}}: unsupported scope applied to resource
```

#### What you expected to happen:

`ResourceQuota` on `ephemeral-storage` should be deployed with `PriorityClass` scopeSelector.

#### How to reproduce it (as minimally and precisely as possible):

Deploy below `ResourceQuota`.

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: example-user
spec:
  hard:
    ephemeral-storage: 200Gi
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["normal"]
```

#### Environment:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: on-premise deployment
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.8.2003 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1160.15.2.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
