### ISSUE TITLE
Cadvisor metrics missing multiple labels in kubernetes 1.16.8

### ISSUE THREAD

**Issue by brokencode64** [kubernetes/kubernetes#102938]
#### Summary:
After (partial) upgrade to kubernetes 1.16.8 Cadvisor metrics are missing proper lables and are not useful. Specifically `container_cpu_usage_seconds_total` is missing multiple labels including `pod`. Curling the metrics from localhost confirms the metrics are being exported with proper labels.

#### What you expected to happen:
Cadvisor metrics should be collected with proper labels. Metric `container_cpu_usage_seconds_total` should exist in prometheus with labels including `pod`.

Example output we should see:
```
container_cpu_usage_seconds_total{container="service",cpu="total",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod10c33f05_b1db_4349_91d4_3381d6b04a52.slice/docker-08d7e4fe8247fa2330204432bcd6ea4a5e9ea42a4cfe2fdede33345128949e5a.scope",image="registry.example.com/service@sha256:48f0fa71faa023761cad5be41be39623b1d181369bd075acee2d2ae36d42ec43",name="k8s_service_service-78f94d9d47-hz7nv_service-namespace_10c33f05-b1db-4349-91d4-3381d6b04a52_0",namespace="service-namespace",pod="service-78f94d9d47-hz7nv"} 12852.91696676 1623842126403
```

### What happened
Metrics exist, but without proper labels for Kubernetes nodes running 1.16.8 but do have proper labels for nodes running 1.15.11.

Example output:
```
container_cpu_usage_seconds_total{cpu="total", id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod10c33f05_b1db_4349_91d4_3381d6b04a52.slice/docker-08d7e4fe8247fa2330204432bcd6ea4a5e9ea42a4cfe2fdede33345128949e5a.scope", image="registry.example.com-service@sha256:48f0fa71faa023761cad5be41be39623b1d181369bd075acee2d2ae36d42ec43", instance="172.x.x.x", job="kube-cadvisor", kubernetes_io_arch="amd64", kubernetes_io_hostname="broken-node-name", kubernetes_io_os="linux", name="k8s_service-service-78f94d9d47-hz7nv_servicenamespace_10c33f05-b1db-4349-91d4-3381d6b04a52_0", namespace="service-namespace"} 12852.91696676 1623842126403
```
****

#### How to reproduce it (as minimally and precisely as possible):
1. Create on-prem kubernetes cluster with kubespray (k8 version 1.16.8)
2. Launch prometheus with cadvisor job listed in prometheus.yml
3. Search for metric `container_cpu_usage_seconds_total`in Prometheus
4. Verify labels are missing from metric

#### Environment:
**Notes**
At this point I'm suspecting there is something going wrong between cadvisor/prometheus. We have around 250 nodes, and soon all nodes will be running 1.16.8, but currently about half are on 1.15.11.

Kubernetes 1.16.8 | 1.15.11
Prometheus 2.26.0

### Configurations

**Kubelet Flags**
```
 --logtostderr=true --v=2 --node-ip=172.x.x.x --hostname-override=node-name --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --config=/etc/kubernetes/kubelet-config.yaml --kubeconfig=/etc/kubernetes/kubelet.conf --pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.1 --runtime-cgroups=/systemd/system.slice --cpu-manager-policy=static --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --volume-plugin-dir=/usr/libexec/kubernetes/kubelet-plugins/volume/exec
```

**Prometheus configuration file**:

cadvisor bit:
```
  # cAdvisor
        - source_labels: [__name__]
          regex: container_tasks_state
          action: drop
        - source_labels: [__name__, interface]
          regex: container_network.+;(?:tun.+|dummy.+|kube-.+|docker.+)
          action: drop
        - source_labels: [__name__, scope]
          regex: container_memory_.+;hierarchy
          action: drop
        - source_labels: [__name__]
          regex: container_spec_memory_(limit_bytes|swap_limit_bytes)
          action: drop
        - source_labels: [__name__]
          regex: container_network_(tcp|udp)_usage_total
          action: drop
        - source_labels: [__name__]
          regex: container_cpu_(user_seconds_total|system_seconds_total|load_average_10s|cfs_.+)
          action: drop
        - source_labels: [__name__]
          regex: container_fs_(inodes_.+|limit_bytes|reads_merged_total|read_seconds_total|writes_merged_total|write_seconds_total|io_.+|sector_.+|usage_bytes|writes_total|reads_total)
          action: drop
        - source_labels: [__name__]
          regex: container_memory_(mapped_file)
          action: drop
        - regex: 'beta_kubernetes_io_arch'
          action: labeldrop
        - regex: 'beta_kubernetes_io_os'
          action: labeldrop
        - regex: 'beta_kubernetes_io_instance_type'
          action: labeldrop
        - regex: 'failure_domain_beta_kubernetes_io_region'
          action: labeldrop
        - regex: 'failure_domain_beta_kubernetes_io_zone'
          action: labeldrop
        - source_labels: [container_name]
          target_label: container
        - source_labels: [pod_name]
          target_label: pod
```

```
  prometheus.yml: |-
    global:
      external_labels:
        env: 'production'
    rule_files:
      - /etc/config/rules
      - /etc/config/alerts
      - /etc/alerts/*.yml

    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - prometheus-prometheus-alertmanager

    scrape_configs:
      - job_name: etcd
        sample_limit: 50000
        scheme: https
        tls_config:
          ca_file: /etc/ssl/etcd/etcd.ca
          cert_file: /etc/ssl/etcd/etcd.crt
          key_file: /etc/ssl/etcd/etcd.key
          insecure_skip_verify: true
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
        - source_labels: [__meta_kubernetes_node_labelpresent_node_role_kubernetes_io_master]
          action: keep
          regex: true
        - source_labels: [__address__]
          action: replace
          regex: (.+):(?:\d+)
          replacement: ${1}:2379
          target_label: __address__
        - source_labels: [__meta_kubernetes_node_label_prometheus_io_scrape]
          regex: 'false'
          action: drop

      - job_name: prometheus
        sample_limit: 50000
        static_configs:
          - targets:
            - localhost:9090

      - job_name: 'kube-apiservers'
        sample_limit: 50000
        kubernetes_sd_configs:
          - role: endpoints

        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

      - job_name: 'kube-kubelet'
        sample_limit: 50000
        scheme: https
        kubernetes_sd_configs:
          - role: node

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__address__]
            action: replace
            regex: (.+):(?:\d+)
            replacement: ${1}:10250
            target_label: __address__
          - source_labels: [__address__]
            regex: (.+):(?:\d+)
            target_label: instance
            replacement: ${1}
          - source_labels: [__meta_kubernetes_node_label_prometheus_io_scrape]
            regex: 'false'
            action: drop

        metric_relabel_configs:
          - source_labels: [__name__]
            regex: kubelet_docker_operations_errors
            action: keep

      - job_name: 'kube-cadvisor'
        sample_limit: 5000000
        scheme: https
        scrape_interval: 15s
        honor_timestamps: false

        metrics_path: /metrics/cadvisor

        kubernetes_sd_configs:
          - role: node

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__address__]
            action: replace
            regex: (.+):(?:\d+)
            replacement: ${1}:10250
            target_label: __address__
          - source_labels: [__address__]
            regex: (.+):(?:\d+)
            target_label: instance
            replacement: ${1}
          - source_labels: [__meta_kubernetes_node_label_prometheus_io_scrape]
            regex: 'false'
            action: drop

        metric_relabel_configs:
          # cAdvisor
        - source_labels: [__name__]
          regex: container_tasks_state
          action: drop
        - source_labels: [__name__, interface]
          regex: container_network.+;(?:tun.+|dummy.+|kube-.+|docker.+)
          action: drop
        - source_labels: [__name__, scope]
          regex: container_memory_.+;hierarchy
          action: drop
        - source_labels: [__name__]
          regex: container_spec_memory_(limit_bytes|swap_limit_bytes)
          action: drop
        - source_labels: [__name__]
          regex: container_network_(tcp|udp)_usage_total
          action: drop
        - source_labels: [__name__]
          regex: container_cpu_(user_seconds_total|system_seconds_total|load_average_10s|cfs_.+)
          action: drop
        - source_labels: [__name__]
          regex: container_fs_(inodes_.+|limit_bytes|reads_merged_total|read_seconds_total|writes_merged_total|write_seconds_total|io_.+|sector_.+|usage_bytes|writes_total|reads_total)
          action: drop
        - source_labels: [__name__]
          regex: container_memory_(mapped_file)
          action: drop
        - regex: 'beta_kubernetes_io_arch'
          action: labeldrop
        - regex: 'beta_kubernetes_io_os'
          action: labeldrop
        - regex: 'beta_kubernetes_io_instance_type'
          action: labeldrop
        - regex: 'failure_domain_beta_kubernetes_io_region'
          action: labeldrop
        - regex: 'failure_domain_beta_kubernetes_io_zone'
          action: labeldrop
        - source_labels: [container_name]
          target_label: container
        - source_labels: [pod_name]
          target_label: pod

      - job_name: 'kube-prober'
        sample_limit: 50000
        scheme: https

        metrics_path: /metrics/probes

        kubernetes_sd_configs:
          - role: node

        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__address__]
            action: replace
            regex: (.+):(?:\d+)
            replacement: ${1}:10250
            target_label: __address__
          - source_labels: [__address__]
            regex: (.+):(?:\d+)
            target_label: instance
            replacement: ${1}
          - source_labels: [__meta_kubernetes_node_label_prometheus_io_scrape]
            regex: 'false'
            action: drop

      - job_name: 'kube-node-exporter'
        sample_limit: 1000000
        scheme: http

        kubernetes_sd_configs:
          - role: node

        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__address__]
            action: replace
            regex: (.+):(?:\d+)
            replacement: ${1}:9100
            target_label: __address__
          - source_labels: [__address__]
            regex: (.+):(?:\d+)
            target_label: instance
            replacement: ${1}
          - source_labels: [__meta_kubernetes_node_label_prometheus_io_scrape]
            regex: 'false'
            action: drop
          - source_labels: [__address__]
            regex: 172.23.125.14[4-6] #DR nodes
            action: drop

        metric_relabel_configs:
        - source_labels: [__name__]
          regex: node_filesystem_device_errors_total
          action: drop
        - source_labels: [mountpoint]
          regex: /rootfs/(.+)
          target_label: mountpoint
          replacement: /$1

      - job_name: 'kube-state'
        sample_limit: 250000
        static_configs:
        - targets:
          - kube-state-metrics

        metric_relabel_configs:
        - source_labels: [__name__]
          regex: 'kube_pod_status_(ready|scheduled)'
          action: drop
        - source_labels: [__name__]
          regex: 'kube_pod_container_status_(waiting_reason|terminated|waiting|running|ready)'
          action: drop
        - source_labels: [__name__]
          regex: 'kube_pod_(owner|labels)'
          action: drop
        - regex: 'pod_ip'
          action: labeldrop

      - job_name: 'pghoard'
        sample_limit: 50000
        scrape_interval: 15s
        honor_timestamps: false

        kubernetes_sd_configs:
          - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_name]
          action: keep
          regex: pghoard.+
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([\w\.]+)(?:\:\d+)?;(\d+)
          replacement: ${1}:${2}
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

      - job_name: 'kube-dns'
        sample_limit: 50000
        scrape_interval: 1m

        kubernetes_sd_configs:
        - role: endpoints

        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          action: keep
          regex: coredns
        - source_labels: [__meta_kubernetes_endpoint_ready]
          action: keep
          regex: true
        - source_labels: [__address__]
          action: replace
          regex: ([\w\.]+)(?:\:\d+)?
          replacement: ${1}:9153
          target_label: __address__
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace

      - job_name: 'kube-pods'
        sample_limit: 2000000
        scrape_interval: 15s

        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_name]
          action: drop
          regex: kube-router.+
        - source_labels: [__meta_kubernetes_pod_name]
          action: drop
          regex: pghoard.+
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([\w\.]+)(?:\:\d+)?;(\d+)
          replacement: ${1}:${2}
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - regex: 'pod_template_hash'
          action: labeldrop

      - job_name: 'kube-pods-slow'
        scrape_timeout: 300s
        scrape_interval: 10m

        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_slow]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_name]
          action: drop
          regex: kube-router.+
        - source_labels: [__meta_kubernetes_pod_name]
          action: drop
          regex: pghoard.+
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([\w\.]+)(?:\:\d+)?;(\d+)
          replacement: ${1}:${2}
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

        metric_relabel_configs:

          # General
        - source_labels: [__name__]
          regex: '(\w+)_(\d+xx)_(\w+)'
          replacement: '${2}'
          target_label: code
        - source_labels: [__name__]
          regex: '(\w+(?:MutableServletContextHandler|HttpClient)\w*)_(head|trace|put|post|other|options|move|head|get|delete|connect)_(\w+)'
          replacement: '${2}'
          target_label: method
        - source_labels: [__name__]
          regex: '(\w+(?:MutableServletContextHandler|HttpClient)\w*)_(head|trace|put|post|other|options|move|head|get|delete|connect|\d+xx)_(\w+)'
          replacement: '${1}_${3}'
          target_label: __name__

          # HTTP Client
        - source_labels: [__name__]
          regex: '(org_apache_http_(?:client|conn)_HttpClient[^_]*)_(\w+)_(responses_total|requests\w*|(?:[^_]+)_connections)'
          replacement: '${2}'
          target_label: target
        - source_labels: [__name__]
          regex: '(org_apache_http_(?:client|conn)_HttpClient[^_]*)_(\w+)_(responses_total|requests\w*|(?:[^_]+)_connections)'
          replacement: '${1}_${3}'
          target_label: __name__

```
