### ISSUE TITLE
minReadySeconds does not work according to documentation

### ISSUE THREAD

**Issue by adelca** [kubernetes/kubernetes#103121]
#### What happened:
Using minReadySeconds in deployment yaml, this field is ignored when reporting pod readiness.
Even requests are sent to the pod before minReadySeconds.
Documentation claims this minReadySeconds "_specifies the minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available._"
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds

Example is using minReadySeconds: 120 Pod is READY in 15 seconds, it is also receiving and serving requests via service.
Deployment shows AVAILABLE as 0, but pod is already online and receiving requests.

```
Elapsed time:[15] seconds...
Wed 23 Jun 2021 17:59:45 IST
GET DEPLOYMENT
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
backend   1/1     1            0           15s
GET PODS
NAME                       READY   STATUS    RESTARTS   AGE
backend-685445b9db-98lxv   1/1     Running   0          15s
```
Pod still not online at:
```
docker@minReadySeconds:~$ date;curl --max-time 5 http://10.104.35.150
Wed Jun 23 17:59:47 IST 2021
curl: (7) Failed to connect to 10.104.35.150 port 80: Connection refused
```

Pod online and serving requests after ~27 seconds (probably pod was online earlier but my script queries every 10 secs), minReadySeconds: 120 is ignored:
```
docker@minReadySeconds:~$ date;curl --max-time 5 http://10.104.35.150
Wed Jun 23 17:59:57 IST 2021
{"message":"Hello"}
```

Deployment eventually shows AVAILABLE as 1:
```
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
backend   1/1     1            1           2m18s
```

#### What you expected to happen:
Pod does not show as "ready" and no requests are sent to the pod until at least minReadySeconds.

#### How to reproduce it (as minimally and precisely as possible):
Use minReadySeconds in a deployment yaml, create a LoadBalancer service, apply it with kubectl (kubectl apply -f blah.yaml), get pods with kubectl (kubectl get pods), send requests to it via SVC IP with curl (curl http://x.x.x.x)

Deployment example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  revisionHistoryLimit: 5
  minReadySeconds: 120
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: "gcr.io/google-samples/hello-go-gke:1.0"
          ports:
            - name: http
              containerPort: 80
```
Service example:
```
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
```

#### Environment:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
