### ISSUE TITLE
YAML separator with comment causes the next resource to be silently ignored

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#103185]
#### What happened:

Attempting to create three namespaces (foo, bar, baz).

Notice the first YAML document separator has the comment `# something` after it on the same line.

```
kubectl apply -f - << EOF
apiVersion: v1
kind: Namespace
metadata:
  name: foo
--- # something
apiVersion: v1
kind: Namespace
metadata:
  name: bar
---            
apiVersion: v1
kind: Namespace
metadata:
  name: baz
EOF
```

Output:
```
namespace/foo created
namespace/baz created
```

Exit code is 0 and only `foo` and `baz` were created.

#### What you expected to happen:

It should either create all three namespaces or else it should fail with an error telling me my YAML is invalid.

#### How to reproduce it (as minimally and precisely as possible):
See Above.

#### Anything else we need to know?:

Same thing happens if I put random characters after the separator.  For example:
```
--- sjhklgjdlkjgkjg
```
No error message is printed, exit code is 0, and the next resource is just silently ignored

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04.2 LTS`
- Kernel (e.g. `uname -a`): `Linux cinlogic-xps13 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
