### ISSUE TITLE
kubectl logs error if multiple pods selected with different containerName

### ISSUE THREAD

**Issue by kebe7jun** [kubernetes/kubernetes#103283]
/kind bug

#### What happened:

```console
[root@dce-10-31-11-1 ~]# kubectl logs -l dce.daocloud.io/app=dsm-demo
error: container s0 is not valid for pod s1-7886d4cf8b-2c9th
```

#### What you expected to happen:

The logs of pods with label `dce.daocloud.io/app=dsm-demo` will be output expected without errors.

#### How to reproduce it (as minimally and precisely as possible):

create the following resources:
```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: s0
    dce.daocloud.io/app: dsm-demo
  name: s0
  namespace: default
spec:
  selector:
    matchLabels:
      app: s0
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-logs-container: s0
      labels:
        app: s0
        dce.daocloud.io/app: dsm-demo
        version: v1
      name: s0
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: s0
        command:
        - sh
        args:
        - -c
        - sed -i 's/worker_processes  auto;/worker_processes  1;/g' /etc/nginx/nginx.conf;  nginx -g 'daemon off;'
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 30m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: tmp
        command:
        - sh
        args:
        - -c
        - sed -i 's/worker_processes  auto;/worker_processes  1;/g' /etc/nginx/nginx.conf; sed -i 's/80;/81;/g' /etc/nginx/conf.d/default.conf; nginx -g 'daemon off;'
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 30m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: s1
    dce.daocloud.io/app: dsm-demo
  name: s1
  namespace: default
spec:
  selector:
    matchLabels:
      app: s1
  template:
    metadata:
      creationTimestamp: null
      annotations:
        kubectl.kubernetes.io/default-logs-container: s0
      labels:
        app: s1
        dce.daocloud.io/app: dsm-demo
        version: v1
      name: s1
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        args:
        - -c
        - sed -i 's/worker_processes  auto;/worker_processes  1;/g' /etc/nginx/nginx.conf;  nginx -g 'daemon off;'
        name: s1
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 30m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: tmp
        command:
        - sh
        args:
        - -c
        - sed -i 's/worker_processes  auto;/worker_processes  1;/g' /etc/nginx/nginx.conf; sed -i 's/80;/81;/g' /etc/nginx/conf.d/default.conf; nginx -g 'daemon off;'
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 30m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always

```
kubectl logs -l dce.daocloud.io/app=dsm-demo

#### Environment:
- Kubernetes version (use `kubectl version`):
latest master.
