### ISSUE TITLE
Inttermitent extra delays when using minReadySeconds in Deployment

### ISSUE THREAD

**Issue by adelca** [kubernetes/kubernetes#103258]
#### What happened:
Using minReadySeconds:550 in Deployment, rollingUpdate strategy (maxSurge:0, maxUnavailable:2) and replicas:6. 
When querying Deployment (kubectl get deployment), the field AVAILABLE does not update according to the value used in minReadySeconds and maxUnavailable. It will take longer and it will cause delays in pods rollout. This happens intermittently, I have been able to reproduce more consistently with a value of minReadySeconds:550 but I have also reproduced with 360 and 180 secs.

I would expect deployment to show all pods AVAILABLE somewhere around 550*(6/2)=1650 secs but, instead, it took 3240 secs for all pods to show AVAILABLE when querying deployment.
Also, the whole rollout is delayed too, the last 2 pods to be deployed happens after 2160 secs when it should have been after 1100 secs.

Deployment state claims only 5 pods are available even after last 2 pods have been running for 17 mins, we can see that all pods should be marked as available by now.
```
Sun 27 Jun 2021 13:00:23 UTC
GET DEPLOYMENT
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
test-minreadysecs   6/6     6            5           3h29m
GET PODS
NAME                                 READY   STATUS    RESTARTS   AGE
test-minreadysecs-547979f75c-2pjgd   1/1     Running   0          17m
test-minreadysecs-547979f75c-689m8   1/1     Running   0          17m
test-minreadysecs-547979f75c-cgt7g   1/1     Running   0          36m
test-minreadysecs-547979f75c-cpfr5   1/1     Running   0          36m
test-minreadysecs-547979f75c-rrb46   1/1     Running   0          54m
test-minreadysecs-547979f75c-wvj6q   1/1     Running   0          54m
XXXXXXXXXXXXXXXXX
NAME                                 TYPE    STATUS   LAST-TRANSACTION-TIME   START-TIME
test-minreadysecs-547979f75c-2pjgd   Ready   True     2021-06-27T12:42:43Z    2021-06-27T12:42:42Z
test-minreadysecs-547979f75c-689m8   Ready   True     2021-06-27T12:42:44Z    2021-06-27T12:42:42Z
test-minreadysecs-547979f75c-cgt7g   Ready   True     2021-06-27T12:24:23Z    2021-06-27T12:24:21Z
test-minreadysecs-547979f75c-cpfr5   Ready   True     2021-06-27T12:24:23Z    2021-06-27T12:24:21Z
test-minreadysecs-547979f75c-rrb46   Ready   True     2021-06-27T12:06:02Z    2021-06-27T12:06:00Z
test-minreadysecs-547979f75c-wvj6q   Ready   True     2021-06-27T12:06:02Z    2021-06-27T12:06:00Z
XXXXXXXXXXXXXXXXX
```

Eventually all pods are marked as available:
```
Sun 27 Jun 2021 13:01:05 UTC
GET DEPLOYMENT
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
test-minreadysecs   6/6     6            6           3h30m
GET PODS
NAME                                 READY   STATUS    RESTARTS   AGE
test-minreadysecs-547979f75c-2pjgd   1/1     Running   0          18m
test-minreadysecs-547979f75c-689m8   1/1     Running   0          18m
test-minreadysecs-547979f75c-cgt7g   1/1     Running   0          36m
test-minreadysecs-547979f75c-cpfr5   1/1     Running   0          36m
test-minreadysecs-547979f75c-rrb46   1/1     Running   0          55m
test-minreadysecs-547979f75c-wvj6q   1/1     Running   0          55m
XXXXXXXXXXXXXXXXX
NAME                                 TYPE    STATUS   LAST-TRANSACTION-TIME   START-TIME
test-minreadysecs-547979f75c-2pjgd   Ready   True     2021-06-27T12:42:43Z    2021-06-27T12:42:42Z
test-minreadysecs-547979f75c-689m8   Ready   True     2021-06-27T12:42:44Z    2021-06-27T12:42:42Z
test-minreadysecs-547979f75c-cgt7g   Ready   True     2021-06-27T12:24:23Z    2021-06-27T12:24:21Z
test-minreadysecs-547979f75c-cpfr5   Ready   True     2021-06-27T12:24:23Z    2021-06-27T12:24:21Z
test-minreadysecs-547979f75c-rrb46   Ready   True     2021-06-27T12:06:02Z    2021-06-27T12:06:00Z
test-minreadysecs-547979f75c-wvj6q   Ready   True     2021-06-27T12:06:02Z    2021-06-27T12:06:00Z
XXXXXXXXXXXXXXXXX

```

#### What you expected to happen:
Deployment respects minReadySeconds value of each pod and updates AVAILABLE field accordingly, I also expect no unnecessary delays when using more than 1 replica and rollingUpdate strategy.

#### How to reproduce it (as minimally and precisely as possible):
I use this deployment.yaml, apply it first, then change sleep value and apply deployment again, ie: from 19700 to 10000
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-minreadysecs
  labels:
    app: test-minreadysecs
spec:
  revisionHistoryLimit: 5
  replicas: 6
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 2
  minReadySeconds: 550
  selector:
    matchLabels:
      app: test-minreadysecs
  template:
    metadata:
      labels:
        app: test-minreadysecs
    spec:
      containers:
        - name: test-minreadysecs
          #image: "busybox:1.32"
          image: k8s.gcr.io/busybox
          command:
            - sleep
            - "19700"
          imagePullPolicy: IfNotPresent

```

#### Environment:
Using minikube version: v1.19.0
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
