### ISSUE TITLE
Kubernetes never cancels PreStop http hook

### ISSUE THREAD

**Issue by Zsolt-LazarZsolt** [kubernetes/kubernetes#103300]
#### What happened:
Consider the following setup.

Have a main container with a liveness probe and a http prestop hook.
Have a side container running a webserver that is listening on said prestop hook, stalling connections indefinitely.

If the following happens:
- main container start failing the liveness probe (in the example port 8002 is not actually open)
- kubernetes decides to kill the main container, triggers the prestop hook. (sidecontainer listens on the called port 8080)
- side container receives the http request towards the prestop hook, accepting the connection, and stalling it.
- after the terminationGracePeriodSeconds ends kubernetes forcefully kills the main containter

The problem is:
the connection to the prestop hook never disconnects, the connection is kept alive indefinitely.

#### What you expected to happen:
I would expect the connection to the prestop http endpoint to be cancelled upon forceful kill.

#### How to reproduce it (as minimally and precisely as possible):
Using the following go code to the server.
[slowserver.code.go.txt](https://github.com/kubernetes/kubernetes/files/6734868/slowserver.code.go.txt)
Using the following dockerfile:
[Dockerfile.txt](https://github.com/kubernetes/kubernetes/files/6734873/Dockerfile.txt)
and then using the created container in the following manifest.
[slowserver.txt](https://github.com/kubernetes/kubernetes/files/6734882/slowserver.txt)

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wzshiming** [comment]
In the 1.21 test, the PreStop hook can be triggered normally, I guess the process in the container exited early.

``` log
start
livenessProbe
livenessProbe
livenessProbe
preStop
```

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
    - name: c
      image: alpine
      args:
        - |
          echo start > /log.txt
          tail -f /log.txt
      command:
        - sh
        - -c
      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - |
              echo livenessProbe >> /log.txt
              exit 1
        initialDelaySeconds: 1
        periodSeconds: 1
        failureThreshold: 3
      lifecycle:
        preStop:
          exec:
            command:
              - sh
              - -c
              - echo preStop >> /log.txt
```
