### ISSUE TITLE
csi-translation-lib: Azure disk type is not properly translated

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#103433]
/kind bug
/sig storage
/area provider/azure

#### What happened:

Creation of a PVC that that uses a StorageClass with the in-tree provisioner `kubernetes.io/azure-disk` and parameter `kind: managed` fails.

#### What you expected to happen:
The above to work.

#### How to reproduce it (as minimally and precisely as possible):

1. Create an Azure cluster with CSI enabled

2. Create StorageClass with the in-tree provisioner `kubernetes.io/azure-disk`

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-test
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_LRS
  kind: managed
```

3. Create PVC and Deployment

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim
spec:
  storageClassName: sc-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: app
        image: centos
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: claim
```

5. Make sure that external-provisioner fails with:

```
E0702 10:16:07.216628       1 volume_store.go:144] error saving volume pv-shoot--foo--bar-01956d9d-bdbf-4602-b1b6-6c1b20a86349: PersistentVolume "pv-shoot--foo--bar-01956d9d-bdbf-4602-b1b6-6c1b20a86349" is invalid: [spec.azureDisk.kind: Unsupported value: "managed": supported values: "Dedicated", "Managed", "Shared", spec.azureDisk.diskURI: Unsupported value: "/subscriptions/<omitted>/resourceGroups/shoot--foo--bar/providers/Microsoft.Compute/disks/pv-shoot--foo--bar-01956d9d-bdbf-4602-b1b6-6c1b20a86349": supported values: "https://{account-name}.blob.core.windows.net/{container-name}/{disk-name}.vhd"]
```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.21.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
