### ISSUE TITLE
Allow both TCP and UDP ports in the same service of type `LoadBalancer`

### ISSUE THREAD

**Issue by su225** [kubernetes/kubernetes#103464]
#### What would you like to be added:
Currently, it is not possible to support both TCP and UDP services with the same service when it is of type `LoadBalancer`. For instance the following spec fails
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-https
  namespace: test
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: https-tcp
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: https-quic
    port: 443
    targetPort: 8443
    protocol: UDP
```
with the following error message (in v1.21)
> The Service "nginx-https" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"https-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:443, TargetPort:intstr.IntOrString{Type:0, IntVal:8443, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-quic", Protocol:"UDP", AppProtocol:(*string)(nil), Port:443, TargetPort:intstr.IntOrString{Type:0, IntVal:8443, StrVal:""}, NodePort:0}}: may not contain more than 1 protocol when type is 'LoadBalancer'

#### Why is this needed:
This is needed to support **both HTTP/2 over TLS+TCP and HTTP/3 over QUIC on the same port (here, 443)** so that clients can use either of them without having to know the port for both of them or not having different IP for TCP+TLS and QUIC. It also allows clients to switch if they support (think Google Chrome). I checked that it is possible at pod level to specify the same port, but with different protocols
