### ISSUE TITLE
CSINode does not support setting volume limits for different storageclass

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubernetes/kubernetes#103477]
#### What happened:
kubectl get csinode <nodeX> -o yaml:
```
spec:
  drivers:
  - allocatable:
      count: 10
    name: csi-qingcloud
    nodeID: i-3icpvocs
    topologyKeys:
    - topology.csi-qingcloud/instance-type
    - topology.csi-qingcloud/zone
```

This means the nodeX can attach up to 10 volumes(allocatable.count) provisioned by CSI driver `csi-qingcloud`, no matter what storageclass the volumes used.

A CSI driver could provision different volumes (by different storageclass), which may have different attach limit for a node. This could often happens on clouds. The cloud providers may provide one CSI driver to provision/attach all kinds of volumes the node supports, to ease development and maintenance effort.
 
For example, a node can attach 10 volumes of storageclass A (e.g. data storage is on the same hardware server with the computing instance(node)), but can attach 50 volumes of storageclass B(e.g. external data storage outside the hardware server). 

the workaround is installing many CSI drivers with only different driver names, then each driver will have its own limit. But that's a little dummy and wasting resources.

#### What you expected to happen:
I hope the spec.drivers.allocatable.count could support different storageclass(or label/signatures etc). 

#### How to reproduce it (as minimally and precisely as possible):
na

#### Environment:
- Kubernetes version (use `kubectl version`): 1.17 and above
- Cloud provider or hardware configuration: e.g. [qingcloud](www.qingcloud.com)
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by xing-yang** [comment]
This works as designed, so it is not a bug.  This is more like a feature request.  If `allocatable` is different dependent on the StorageClass, do you rely on some opaque parameters in the StorageClass to determine what value of `allocatable` is supported?

**Comment by stoneshi-yunify** [comment]
Yes, this is a feature request I guess.

The `allocatable` might be dependent on types of volumes, not StorageClass. Because user can easily create many storageclasses for one type of volume, right? These storageclasses show share one `allocatable` value.

The storageclass can put this type info into the parameters field. e.g.

```
root@i-zzyrsop1:~# kubectl get sc csi-standard -o yaml
parameters:
  fsType: ext4
  type: "100"  <----
provisioner: csi-qingcloud
```

And the pv will contains this type info in csi.volumeAttributes. e.g.
```
root@i-zzyrsop1:~# kubectl get pv pvc-769883cf-0dac-46c6-9f5e-b58ef92f5a3e -o yaml
spec:
  csi:
    driver: csi-qingcloud
    fsType: ext4
    volumeAttributes:
      fsType: ext4
      type: "100" <-----
    volumeHandle: vol-67g5flx1
```

The CSINode might be like:
```
spec:
  drivers:
  - allocatable:
      - count: 10
         volumeTypes:   <----- many types can share a count
         - "100"
         - "200"
         - "300"
      - count: 50
         volumeTypes:   <------
         - "400"
      - count: 50
         volumeTypes:   <------
         - "500"
    name: csi-qingcloud
    nodeID: i-3icpvocs
    topologyKeys:
    - topology.csi-qingcloud/instance-type
    - topology.csi-qingcloud/zone
 ```

When kubernetes does the predicts during scheduling, it can count volume's total number of each type (by looking at pv's csi.volumeattribute.type), and calculate the remaining spots with CSINode info.

Above is just my thought on top of my head. Obviously we can not force user to use an exact `type` field in the storageclass or csi.volumeattributes, user may want to define this key flexibly, like the ` topologyKeys`.
