### ISSUE TITLE
 Forbidden: disallowed by cluster policy

### ISSUE THREAD

**Issue by XzBuleSky** [kubernetes/kubernetes#103444]
#### What happened:
  When I try to create a daemonset resource, I prompt the following information:
```
The DaemonSet "node-exporter" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
```
DaemonSet yaml :
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: kube-system
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      name: node-exporter
  template:
    metadata:
      labels:
        name: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
        securityContext:
          privileged: true
```

I have added the `--allow-privileged=true` parameter to the apiserver service, but I still report an error

What else causes the error?
#### Environment:
- Kubernetes version (use `kubectl version`):
```
GitVersion:"v1.20.8"
```
- Kernel (e.g. `uname -a`):
```
Linux  5.10.23-5.al8.x86_64
```
