### ISSUE TITLE
Ubuntu 20.04: unable to bootstrap cluster fully (arm64)

### ISSUE THREAD

**Issue by samip5** [kubernetes/kubernetes#103466]
#### What happened:

Initialization of cluster on arm64 failed due to coredns not found error.

#### What you expected to happen:

Cluster would have initialized without issue, and gave me a joining token.

#### How to reproduce it (as minimally and precisely as possible):
- Grab a Raspberry Pi 4
- Install Ubuntu Server 20.04 arm64
- Install Kubernetes normally
- Try to deploy dual-stack cluster configuration via config file

#### Anything else we need to know?:

Minimal config that was used:
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.21.2
apiServer:
  extraArgs:
    service-cluster-ip-range: "10.250.0.0/16,2001:67c:1104:1000::50:0/108"
controllerManager:
  extraArgs:
    cluster-cidr: "10.244.0.0/16,fddf:f7bc:9670::/48"
    service-cluster-ip-range: "10.250.0.0/16,2001:67c:1104:1000::50:0/108"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
```

The cluster does initialize to some kind of half-state, but coredns doesn't start due to missing cni config. The kubeadm doesn't give me a join token which could be used to join other nodes to it.

#### Environment:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/arm64"}`

- Cloud provider or hardware configuration: arm64 hardware, Raspberry Pi 4
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):  `Linux KubeMaster 5.4.0-1028-raspi #31-Ubuntu SMP PREEMPT Wed Jan 20 11:30:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
- Install tools: I don't understand what this asks.
- Network plugin and version (if this is a network-related bug): It's not per se.
- Others:

Full kubeadm log (verbose level 7, `--v=7`):
[kubeadm_log.txt](https://github.com/kubernetes/kubernetes/files/6760565/kubeadm_log.txt)
