### ISSUE TITLE
Labels of pv are missing in version 1.18.18

### ISSUE THREAD

**Issue by AlwaySummit** [kubernetes/kubernetes#103403]
#### What happened:
With version 1.18.18, I'm facing an issue about pv label missing which causes a failure of some services running. For example:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: pd.csi.storage.gke.io
  creationTimestamp: "2021-07-01T07:33:42Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/pd-csi-storage-gke-io
```
As you can see, label `failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone` are missing.
#### What you expected to happen:
In previous version 1.17.16, labels are correctly set in pv. For example:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    velero.io/alibabacloud-restore-plugin: "1"
  creationTimestamp: "2021-06-07T07:04:23Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: europe-west1
    failure-domain.beta.kubernetes.io/zone: europe-west1-b
  name: pvc-165b7c53-1263-4469-a36f-84994da94a3b
  resourceVersion: "29425366"
  selfLink: /api/v1/persistentvolumes/pvc-165b7c53-1263-4469-a36f-84994da94a3b
  uid: c5fae559-1ba0-43c1-b864-4d44b76ae1b2
```

#### How to reproduce it (as minimally and precisely as possible):
1. Create a storage class with gke provider. For example:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcp-test
parameters:
  type: pd-balanced
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
2. Create a pvc. For example:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-test
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: gcp-test
```
3. Create a pod to consume it. For example:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-storageclass-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.gke.io/zone
            operator: In
            values:
            - europe-west1-c
  containers:
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sh"
    - "-c"
    args:
    - "sleep 3600"
    volumeMounts:
    - name: nfs-pvc
      mountPath: /mnt
  restartPolicy: Never
  volumes:
  - name: nfs-pvc
    persistentVolumeClaim:
      claimName: gcp-test
```
#### Anything else we need to know?:
As far as I know, in-tree volume plugin is deprecated in version 1.18. I'm not sure if it's related to this issue.
#### Environment:
- Kubernetes version (use `kubectl version`): [root@localhost k8s]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GCP and AWS have the same issue.
- OS (e.g: `cat /etc/os-release`): suse-chost: 15.2.20210405
