### ISSUE TITLE
scheduler: failed with unreadable error message with v1beta2 configuration 

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#103478]
#### What happened:
Have a legacy scheduler config, upgrade to v1beta2 since we are at v1beta2 now, 

```
  plugins:
	...
    score:
      disabled:
        - name: InterPodAffinity
      enabled:
        - name: InterPodAffinity
          weight: 2
	...
  pluginConfig:  
  - args:
        apiVersion: kubescheduler.config.k8s.io/v1beta2
        resources:
        - name: hugepages
          weight: 1
      name: NodeResourcesLeastAllocated
```

scheduler failed to start with some unreadable raw data, 
```
profiles[0].pluginConfig[0].args: Invalid value: runtime.Unknown{TypeMeta:runtime.TypeMeta{APIVersion:"", Kind:""}, Raw:[]uint8{0x7b, 0x22, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x22, 0x6b, 0x75, 0x62, 0x65, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x32, 0x22, 0x2c, 0x22, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x3a, 0x5b, 0x7b, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x68, 0x75, 0x67, 0x65, 0x70, 0x61, 0x67, 0x65, 0x73, 0x2d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x31, 0x22, 0x2c, 0x22, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x3a, 0x31, 0x7d, 0x5d, 0x7d}, ContentEncoding:"", ContentType:"application/json"}: has to match plugin args
Process 1130 has exited with status 1
```

#### What you expected to happen:
accurate and readable error message.

#### How to reproduce it (as minimally and precisely as possible):
config scheduler config like what has been said above.

#### Environment:
- Kubernetes version (use `kubectl version`): latest.
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): all
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig scheduling
/assign
