### ISSUE TITLE
subpath should not be directory when secret update 

### ISSUE THREAD

**Issue by yylt** [kubernetes/kubernetes#103531]
#### What happened:
the mountpoint of subpath is always directory even if update secret and add `k1` key

```bash
(before update secret)
# ls /var/lib/kubelet/pods/351ab454-aac1-4b55-bb96-36866f7f7465/volumes/kubernetes.io~secret/sub
drwxrwxrwt 4 root 120 Jul  7 11:14 .
drwxr-xr-x 4 root  44 Jul  7 11:14 ..
drwxr-xr-x 2 root  60 Jul  7 11:14 ..2021_07_07_03_14_04.560943344
lrwxrwxrwx 1 root  31 Jul  7 11:14 ..data -> ..2021_07_07_03_14_04.560943344
lrwxrwxrwx 1 root   9 Jul  7 11:14 k0 -> ..data/k0
drwxrwxrwt 2 root  40 Jul  7 11:14 k1

(after update secret)
# ls /var/lib/kubelet/pods/351ab454-aac1-4b55-bb96-36866f7f7465/volumes/kubernetes.io~secret/sub
total 0
drwxrwxrwt 4 root 100 Jul  7 11:15 .
drwxr-xr-x 4 root  44 Jul  7 11:14 ..
drwxr-xr-x 2 root  60 Jul  7 11:15 ..2021_07_07_03_15_03.374985634
lrwxrwxrwx 1 root  31 Jul  7 11:15 ..data -> ..2021_07_07_03_15_03.374985634
drwxrwxrwt 2 root  40 Jul  7 11:14 k1

```

#### What you expected to happen:
the mountpoint of subpath is softlink file when update secret 

#### How to reproduce it (as minimally and precisely as possible):

1. create resources in below
2. after pod running
3. update secret `kubectl patch secret -n test keys -p '{"data":{"k1":"aGVsbG8="}}'`

- resources:
```yaml
apiVersion: v1
data:
  k0: aGVsbG8=
kind: Secret
metadata:
  name: keys
  namespace: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-subpath
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tests
  template:
    metadata:
      labels:
        app: tests
    spec:
      containers:
      - image: busybox:latest
        command:
        - test
        - -d
        - /var/lib/test
        imagePullPolicy: IfNotPresent
        name: test
        volumeMounts:
        - mountPath: /var/lib/test
          name: sub
          subPath: k1
      volumes:
      - name: sub
        secret:
          defaultMode: 420
          secretName: keys
```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.16.6
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

```
# cat /etc/os-release 
NAME="Cloud Linux"
VERSION="7.6 (Core)"
ID="core"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.6"
```

- Kernel (e.g. `uname -a`):

```
# uname -a
Linux node-4.domain.tld 4.18.0-147.5.1.el8_1.5es.14.x86_64 #1 SMP Fri Jan 29 17:32:05 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
