### ISSUE TITLE
Should update endpoints when delete service selector 

### ISSUE THREAD

**Issue by zxh326** [kubernetes/kubernetes#103576]
#### What happened:

When I delete a service's selector, its endpoints are still the same.

#### What you expected to happen:

when svc selector is none, endpoint subset should be empty

#### How to reproduce it (as minimally and precisely as possible):
1. create service like this
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: reviews
status:
  loadBalancer: {}
```
2. get endpoints
```sh
❯ k get endpoints test-service
NAME           ENDPOINTS                            AGE
test-service   172.20.143.204:3000                 4m28s
```
3. remove service selector
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: test-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
status:
  loadBalancer: {}
```

4. get same endpoints
```sh
❯ k get endpoints test-service
NAME           ENDPOINTS                            AGE
test-service   172.20.143.204:3000                 4m28s
```

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by gccio** [comment]
if the services has no selector, the controller manager will not manage the services' endpoints. you need to manage it manually.

**Comment by thockin** [comment]
It seems like a legit bug, to me.  To track that, we'd need an annotation noting that the endpoints is, in fact, managed (vs manual).

**Comment by robscott** [comment]
This actually came up in the design of the EndpointSlice controller. I think there are 2 possible interpretations of a user removing a selector on a Service:

1. The user wants to start over with a completely new set of endpoints managed by themselves.
2. The user wants to start managing endpoints, starting with the existing set curated by the controller.

The Endpoints (and now EndpointSlice) controllers chose the second interpretation. In the case of the EndpointSlice controller decision, we saw this as the option that was both least disruptive and most consistent with the behavior of the existing Endpoints controller. I don't actually know what the reasoning was for the original Endpoints controller decision here though. Given that this behavior has existed for so long, it seems likely that there are at least some users and workflows that rely on this behavior so I'd be quite hesitant to change it.

Tim also raises a good point. With the Endpoints controller, we have no way to determine if an Endpoints resource is actually owned by the controller. Given the eventually consistent nature of controllers, there's a decent chance that the Endpoints controller would run after the user had modified the Endpoints resource and end up unexpectedly deleting the Endpoints the user had just set.

With EndpointSlices, we do have a concept of ownership with the [managed-by label](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/discovery/v1/well_known_labels.go#L27). We could take advantage of that and delete EndpointSlices were managed by the EndpointSlice controller for a Service, but again we could potentially break the workflow described in 2 if the user was trying to modify existing EndpointSlices (and hopefully change the managed-by label in the process). This would also be inconsistent with the behavior of the Endpoints controller.

I would be open to a fix that introduced the concept of a managed-by label to Endpoints and then updated both controllers to clean up resources they managed for Services with a nil selector. With that said, adding a managed-by label to Endpoints is a non-trivial change, and the upgrade story would be quite complicated (you'd have to update all Endpoints in a cluster when upgrading to the next k8s version). So although I think there's room for improvement here, I'm not sure it's worth the significant effort that would take.

Alternatively we could choose to limit this change to EndpointSlices. That would be much simpler, but it would introduce inconsistencies between the APIs and controllers that we've been trying to avoid.

**Comment by thockin** [comment]
After discussing, I think the right fix is to update documentation.

**Comment by zxh326** [comment]
In my case, i changed svc type `ClusterIP` to `ExternalName`, but endpoints still exist and has full subsets. it's useless, and no one cares that he even exists, it becomes garbage.

I don't understand why this design, svc created, create endpoints, svc deleted, delete endpoints, but svc updated, some case, will not update endpoints. 

our document tell me, how to design a controller

> a particular control loop (controller) uses one kind of resource as its desired state, and has a different kind of resource that it manages to make that desired state happen.

Obviously not in line with the current case.

**Comment by robscott** [comment]
> I think the right fix is to update documentation

Agreed, I can work on that.

> I don't understand why this design, svc created, create endpoints, svc deleted, delete endpoints, but svc updated, some case, will not update endpoints.

In this case, we interpret a nil selector as the user opting in to manage the Endpoints/EndpointSlices themselves. The real issue is the transition between the two states. Do we leave you with the Endpoints/EndpointSlices that already exist or clean them up and let you start with a clean slate. The existing behavior has been to leave the user with the Endpoints/EndpointSlices. To ensure we can retain backwards compatibility, the best option we have is just to document the behavior.

> i changed svc type ClusterIP to ExternalName, but endpoints still exist and has full subsets

That does seem like an instance where we should clean up Endpoints and/or EndpointSlices. Does this happen because you've also removed the selector on the Service? If so, then I think everything I've said above would still apply.

**Comment by thockin** [comment]
Hmm, I could see removing Endpoints if the result of the update doesn't use
them (basically only ExternalName).   In this case  there's no reason they
should exist - they mean nothing.  We can do that synchronously from
apiserver (I know, but we already do this on Delete).  EndpointSlice would
want to do this from the controller, if it doesn't already?

**Comment by Nitive** [comment]
I faced the same simular issue when making reverse operation — adding selector to Service

1. I created Service without `selector`
1. I created Endpoints resource for this service which was pointed to external service (VM)
1. Then I wanted to migrate traffic from external service to pods in my namespace. So I added `selector` to Service
1. Endpoints resource got updated — external service subset was removed and pods' subsets was added
1. But EndpointSlice resource for external service wasn't removed so traffic was flowing to both pods and external service

<details>
<summary>Minimal reproducible example</summary>

You can reproduce the issue by applying these manifests

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  name: test
subsets:
- addresses:
  - ip: 1.1.1.1
  ports:
  - name: http
    port: 80
    protocol: TCP
```

Then these

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1
```

Expected: 1 endpointslice
Actual: 2 endpointslices

```sh
$ kubectl get po,svc,ep,endpointslices
NAME        READY   STATUS    RESTARTS   AGE
pod/nginx   1/1     Running   0          102s

NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/test   ClusterIP   10.222.243.26   <none>        80/TCP    5m7s

NAME             ENDPOINTS         AGE
endpoints/test   10.111.2.219:80   5m7s

NAME                                        ADDRESSTYPE   PORTS   ENDPOINTS      AGE
endpointslice.discovery.k8s.io/test-5rvvf   IPv4          80      1.1.1.1        5m7s
endpointslice.discovery.k8s.io/test-h4gjl   IPv4          80      10.111.2.219   103s
```
</details>
