### ISSUE TITLE
Affinity probably present even after deleting it

### ISSUE THREAD

**Issue by ondrejdolezal93** [kubernetes/kubernetes#103584]
#### What happened: 

Deployment with affinity is blocking new deployment that does not contain affinity

#### What you expected to happen:  

I expect new deployment that does not contain affinity to be deployed without any problem

#### How to reproduce it (as minimally and precisely as possible):

Here is my first deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pts
  namespace: namespace
  labels:
    app: pts
spec:
  selector:
    matchLabels:
      app: pts
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 5
  minReadySeconds: 10
  template:
    metadata:
      name: pts
      namespace: namespace
      labels:
        app: pts
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      enableServiceLinks: false
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
              matchLabels:
                app: {{ .Chart.Name }}
             topologyKey: kubernetes.io/hostname    
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: topology.kubernetes.io/zone
      #     whenUnsatisfiable: ScheduleAnyway
      #     labelSelector:
      #       matchLabels:
      #         app: pts
      #   - maxSkew: 1
      #     topologyKey: kubernetes.io/hostname
      #     whenUnsatisfiable: ScheduleAnyway
      #     labelSelector:
      #       matchLabels:
      #         app: pts
      containers:
        - name: pts
          image: debian:buster-slim
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              echo '1'
              trap 'sleep 60; kill -9 0' TERM
              sleep infinity &
              wait
              echo '2'
```

After deploying previous deployment, pod is running just fine. 

Now I change deployment to following (remove affinity and add Pod Topology Spread):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pts
  namespace: namespace
  labels:
    app: pts
spec:
  selector:
    matchLabels:
      app: pts
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 5
  minReadySeconds: 10
  template:
    metadata:
      name: pts
      namespace: namespace
      labels:
        app: pts
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      enableServiceLinks: false
      # affinity:
      #    podAntiAffinity:
      #      requiredDuringSchedulingIgnoredDuringExecution:
      #      - labelSelector:
      #         matchLabels:
      #           app: {{ .Chart.Name }}
      #        topologyKey: kubernetes.io/hostname    
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: pts
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: pts
      containers:
        - name: pts
          image: debian:buster-slim
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              echo '1'
              trap 'sleep 60; kill -9 0' TERM
              sleep infinity &
              wait
              echo '2'
```

After rolling the update, I still have one old pod in "Running" state and one new pod which gets stuck in "Pending" state.
Describing new pod gives me following: **Warning  FailedScheduling  17s (x4 over 3m4s)  default-scheduler  0/1 nodes are available: 1 Too many pods.**

It looks like somehow affinity is still present in the deployment.

I tried deleting deployment by `kubectl delete deployment pts` after first deployment and then deploying with new configuration - everything worked just fine.

To me it looks like affinity is somehow preserved in the deployment even though I delete it from the deployment file - so now I have to delete deployment manually, which is not expected behavior.

Also, please - is there any command to find out if there is any affinity present in specific deployment?

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): Debian 10
- Kernel (e.g. `uname -a`):  SMP Debian 4.19.181-1 (2021-03-19)

**Comment by kerthcet** [comment]
I'll try to have a look. Reproduce first. 🥸

**Comment by kerthcet** [comment]
As `Warning FailedScheduling 17s (x4 over 3m4s) default-scheduler 0/1 nodes are available: 1 Too many pods.` tells, you have only one node in your cluster, I think it's a normal behavior, not a bug, as anti-affinity guarantees the distribution of the pods across different nodes in you cluster. If you add another one node to your cluster, I think rolling update will success.

**Comment by kerthcet** [comment]
@ondrejdolezal93

**Comment by ondrejdolezal93** [comment]
> As `Warning FailedScheduling 17s (x4 over 3m4s) default-scheduler 0/1 nodes are available: 1 Too many pods.` tells, you have only one node in your cluster, I think it's a normal behavior, not a bug, as anti-affinity guarantees the distribution of the pods across different nodes in you cluster. If you add another one node to your cluster, I think rolling update will success.

Thanks for your investigation!

I would like to point out one thing: 
This problem happens when I upgrade the deployment, when I delete old one and deploy new one, the problem is not there at all.

I would excpect that affinity will "vanish" when upgrading to new deployment that is not using it, as Kubernetes config files are of a declarative manner.

**Comment by kerthcet** [comment]
I tried to combing these logic acrossing these features, but I found I'm on the wrong way. For all the features, IMO, they all created to achieve high availability and efficient resource usage. So single node cluster should not be in consider. Or if you have any scenarios? 🥲

**Comment by ondrejdolezal93** [comment]
Could you then try to replicate my steps on single-node environment such as minikube?
I ran into this problem in our testing environment

**Comment by kerthcet** [comment]
yeah, I can reproduce it with `kind`, for it acts as expected. You can add another node to solve it.

**Comment by cbandy** [comment]
The update strategy is trying to surge and the running pod has an anti-affinity on the `app` label.

I suspect using the [Recreate](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment) strategy would solve it:

```yaml
  strategy:
    type: Recreate
```

I suspect using [RollingUpdate](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment) without surge would also solve it:

```yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
```
