### ISSUE TITLE
kube-scheduler add restful api for get a pod current node fit list and score.

### ISSUE THREAD

**Issue by llhhbc** [kubernetes/kubernetes#103528]
#### What would you like to be added:
kube-scheduler add a restful api, like `/api/v1/pod/scheduler?name=podName&namespace=namespace`, and it will get result like this:

```yaml
canScheduler: true
details:
  fitNodes: 
   - node1:
       scores: 10000 
   - node2:
       scores: 1000
errors: # will list can't fit list if  canScheduler=false
  - node1:
      scores: -1000
      description: "memory insufficient"
  - node2:
      scores: -1000
      description: "cpu insufficient, memory insufficient"
```

#### Why is this needed:
1. In order to clarify the insufficient resources of each node
2. The csi program wants to obtain all the optional node information of the current pod, and comprehensively store the situation, select an optimal scheduling node
