### ISSUE TITLE
allow kubeconfig to have non-embeeded token

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#10365]
Currently it is possible in a kubeconfig file to do:

``` yaml
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/certs/kubecfg.crt
    client-key: /etc/kubernetes/certs/kubecfg.key
```

But it is not possible to do:

``` yaml
users:
- name: proxy
  user:
    token: /etc/kubernetes/token/proxy.token
```

This means that certificates and kubeconfig files can be decoupled and distributed separately, but kubeconfig files and tokens MUST be managed together.

Not sure if it's possible to distinguish, so maybe a "token_file" option?
