### ISSUE TITLE
Feature request: Custom http method on ingress http path

### ISSUE THREAD

**Issue by brunoarueira** [kubernetes/kubernetes#103613]
I think the title is self explanatory, but I'll give an example of a simple config below:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
spec:
  rules:
    - http:
        paths:
          - path: /v1/foo
            method: "POST" # This can be GET, HEAD, POST, PUT, PATCH, DELETE, CONNECT, OPTIONS, and TRACE
            pathType: Prefix
            backend:
              service:
                name: foo
                port:
                  number: 3000
          - path: /v1/foo
            method: "GET" # This can be GET, HEAD, POST, PUT, PATCH, DELETE, CONNECT, OPTIONS, and TRACE
            pathType: Prefix
            backend:
              service:
                name: bar
                port:
                  number: 3000
```

With this new option, the ingress will route a specific path with a specific HTTP method to the defined backend service. Another take on the same subject will allow or disallow certain paths to not route to the backend (e.g PUT /v1/foo)

Some people already request this on the nginx ingress implementation here https://github.com/kubernetes/ingress-nginx/issues/187, but since some of the commenters explain the ingress spec not support it yet, I'm not be able to found another similar request and I'd opened it.
