### ISSUE TITLE
Mongodb StatefulSet error with Azure File Share

### ISSUE THREAD

**Issue by sbalajisivaram** [kubernetes/kubernetes#103773]
#### What happened: 
Mongodb StatefulSet error with Azure File Share

#### What you expected to happen:
I'm trying to run MongoDB on AKS with Statefulset. I Created an Azure File Share and mounted the fileshare as persistent volume the pvc created out of the volume is being used for the statefulset. However i cant seem to run mongodb when having Azure Files i'm yet to try Azure Disk but just checking to see if this is something supported. I have been making changes to the statefulset to see if it works as a result i'm getting different errors as well.. 

```
{"t":{"$date":"2021-07-19T14:16:16.643+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2021-07-19T14:16:16.644+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2021-07-19T14:16:16.645+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2021-07-19T14:16:16.645+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2021-07-19T14:16:16.645+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"mongo-0"}}
{"t":{"$date":"2021-07-19T14:16:16.645+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.7","gitVersion":"abb6b9c2bf675e9e2aeaecba05f0f8359d99e203","openSSLVersion":"OpenSSL 1.1.1d  10 Sep 2019","modules":[],"allocator":"tcmalloc","environment":{"distmod":"debian10","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2021-07-19T14:16:16.645+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"PRETTY_NAME=\"Debian GNU/Linux 10 (buster)\"","version":"Kernel 5.4.0-1047-azure"}}}
{"t":{"$date":"2021-07-19T14:16:16.645+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"},"replication":{"replSet":"rs0"}}}}
{"t":{"$date":"2021-07-19T14:16:16.685+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
{"t":{"$date":"2021-07-19T14:16:16.716+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=2965M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
{"t":{"$date":"2021-07-19T14:16:17.633+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1626704177:633349][1:0x7f8568bb8140], file:WiredTiger.wt, connection: __posix_open_file, 805: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
{"t":{"$date":"2021-07-19T14:16:17.757+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":1,"message":"[1626704177:757288][1:0x7f8568bb8140], file:WiredTiger.wt, connection: __posix_open_file, 805: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted"}}
{"t":{"$date":"2021-07-19T14:16:17.763+00:00"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
{"t":{"$date":"2021-07-19T14:16:17.763+00:00"},"s":"F",  "c":"STORAGE",  "id":28595,   "ctx":"initandlisten","msg":"Terminating.","attr":{"reason":"1: Operation not permitted"}}
{"t":{"$date":"2021-07-19T14:16:17.763+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":954}}
{"t":{"$date":"2021-07-19T14:16:17.763+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}
```

#### How to reproduce it (as minimally and precisely as possible):

* Create a Azure File Share: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume
* Create a secret for the stroage account
* Create a PV out of the storage account

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-volume
  namespace: mongod-ns
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    secretNamespace: mongod
    shareName: cloudpricing
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-pvc
  namespace: mongod-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: azurefile-volume
  resources:
    requests:
      storage: 25Gi

---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: mongo
    namespace: mongod-ns
  spec:
    selector:
      matchLabels:
        role: mongo
        environment: test
    serviceName: "mongo"
    replicas: 2
    template:
      metadata:
        labels:
          role: mongo
          environment: test
      spec:
        containers:
        - name: mongo
          image: bitnami/mongodb:latest
          ports:
          - containerPort: 27017
          command:
          - mongod
          - "--bind_ip_all"
          - "--replSet"
          - rs0
          resources: {}
          volumeMounts:
          - name: mongo-volume-fileshare
            mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongo,environment=test"
        volumes:
          - name: mongo-volume-fileshare
            persistentVolumeClaim:
              claimName: azurefile-pvc
 ```
#### Pod Status
```
NAME        READY   STATUS             RESTARTS   AGE   IP          NODE                              NOMINATED NODE   READINESS GATES
mongo-0     1/2     CrashLoopBackOff   7          13m   10.1.0.79   aks-default-29158593-vmss000002   <none>           <none>
mongo-1     1/2     CrashLoopBackOff   7          13m   10.1.0.46   aks-default-29158593-vmss000001   <none>           <none>
```

#### Anything else we need to know?:

As per  https://github.com/kubernetes/kubernetes/issues/58308, just found that bitnmai mongo works with azure file but it appears not as i'm still getting the same error.

Not sure if i'm missing anything in the above configurations.

#### Environment:
- Kubernetes version (use `kubectl version`): 
Client Version: v1.18.0
Server Version: v1.18.17
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Ubuntu-1804
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): Azure CNI
- Others:
