### ISSUE TITLE
k8s API server prunes metadata field in PodTemplateSpec

### ISSUE THREAD

**Issue by kscharm** [kubernetes/kubernetes#103739]
#### What happened:
The kubernetes API server prunes the `ObjectMeta` field of `PodTemplateSpec` when used in a Custom Resource Definition. It does not prune the `PodSpec` field.  

#### What you expected to happen:
The metadata field should be acknowledged as a known field by the k8s API server and persist in the CR object instead of being pruned.

#### How to reproduce it:
Create a new `CustomResourceDefinition` and include a `PodTemplateSpec` under the CR's `Spec` field. Here is a snippet of our CRD:
```yaml

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.5.0
  name: redisclusters.db.ibm.com
spec:
  group: db.ibm.com
  names:
    kind: RedisCluster
    listKind: RedisClusterList
    plural: redisclusters
    shortNames:
    - rdc
    singular: rediscluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: RedisCluster represents a Redis Cluster
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec represents the desired RedisCluster specification
            properties:
              podTemplate:
                description: PodTemplate contains the pod specification that should run the redis-server process
                properties:
                  metadata:
                    description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata'
                    type: object
                  spec:
                    description: 'Specification of the desired behavior of the pod. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
                    properties:
                    ...
```
We use `kubebuilder` and `controller-gen` to generate our CRD:
```golang
package v1alpha1

import (
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	kapiv1 "k8s.io/api/core/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// RedisCluster represents a Redis Cluster
// +kubebuilder:object:root=true
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
// +kubebuilder:resource:scope=Namespaced,shortName=rdc
type RedisCluster struct {
	metav1.TypeMeta `json:",inline"`
	// Standard object's metadata.
	// More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec represents the desired RedisCluster specification
	Spec RedisClusterSpec `json:"spec,omitempty"`

	// Status represents the current RedisCluster status
	Status RedisClusterStatus `json:"status,omitempty"`
}

// RedisClusterList implements list of RedisCluster.
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type RedisClusterList struct {
	metav1.TypeMeta `json:",inline"`
	// Standard list metadata
	// More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata
	metav1.ListMeta `json:"metadata,omitempty"`

	// Items is the list of RedisCluster
	Items []RedisCluster `json:"items"`
}

// RedisClusterSpec contains RedisCluster specification
type RedisClusterSpec struct {
	// PodTemplate contains the pod specification that should run the redis-server process
	PodTemplate *kapiv1.PodTemplateSpec `json:"podTemplate,omitempty"`
}
...
```
We install the CRD with our k8s redis-operator chart and then create the CR in the redis-cluster helm chart:
```yaml
apiVersion: db.ibm.com/v1alpha1
kind: RedisCluster
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  labels: {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  podTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "redis-cluster.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "icm-redis-cluster.serviceAccountName" . }}
     ...
```
 We have validated that the labels are properly generated by helm templating. Here is the output from `helm template charts/redis-cluster --debug`:
```yaml
# Source: redis-cluster/templates/rediscluster.yaml
apiVersion: db.ibm.com/v1alpha1
kind: RedisCluster
metadata:
  name: RELEASE-NAME-redis-cluster
  labels:
    helm.sh/chart: redis-cluster-0.0.0
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  podTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: redis-cluster
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-icm-redis-cluster
     ...
```
As you can see, we've added some labels under the `spec.metadata.labels` field. However, when we deploy the CR, everything in the `spec.podTemplate.metadata` field is pruned (at the bottom of this snippet):
```
~ k get redisclusters.db.ibm.com redis-cluster-icm-redis-cluster -o yaml
apiVersion: db.ibm.com/v1alpha1
kind: RedisCluster
metadata:
  annotations:
    meta.helm.sh/release-name: redis-cluster
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-07-15T15:41:23Z"
  generation: 31
  labels:
    app.kubernetes.io/instance: redis-cluster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/version: 0.0.0
    helm.sh/chart: redis-cluster-0.0.0
  managedFields:
  - apiVersion: db.ibm.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        .: {}
        f:podTemplate:
          .: {}
          f:metadata: {}
          f:spec:
            .: {}
    manager: Go-http-client
    operation: Update
    time: "2021-07-15T15:41:23Z"
  - apiVersion: db.ibm.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:podTemplate:
          f:spec:
            f:volumes: {}
      f:status:
        .: {}
        f:cluster:
          .: {}
    manager: operator
    operation: Update
    time: "2021-07-15T15:43:45Z"
  name: redis-cluster-icm-redis-cluster
  namespace: default
  resourceVersion: "1528"
  uid: 7029b91a-84b9-4236-a4b5-8ecb4342ed28
spec:
  podTemplate:
    metadata: {}
    spec:
      containers:
      ...
```
#### Environment:
- Kubernetes version (use `kubectl version`): 1.19, 1.20
- Cloud provider or hardware configuration: kind 0.11.0 (local) and IKS 1.19.11 (cloud)
- OS (e.g: `cat /etc/os-release`):  macOS Big Sur 11.4 (local)
- Install tools: helm v3.5.2, controller-gen v0.5.0
- k8s package versions:
```
k8s.io/api v0.20.2
k8s.io/apimachinery v0.20.2
k8s.io/client-go v0.20.2
sigs.k8s.io/controller-runtime v0.8.3
```
