### ISSUE TITLE
Pod Anti-Affinity not working

### ISSUE THREAD

**Issue by lukos** [kubernetes/kubernetes#103848]
#### What happened:
I have setup a pod anti-affinity to spread my pods among available nodes to provide maximum HA with 3 pods. I use the following node/pod affinity:

```yaml
      affinity: 
        nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms: 
            - matchExpressions: 
              - key: kubernetes.io/os 
                operator: In 
                values: 
                - "linux" 
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector: 
              matchExpressions: 
              - key: Octopus.Deployment.Id 
                operator: In 
                values: 
                - "Deployments-28802" 
            topologyKey: kubernetes.io/hostname 
```

Note that the deployments-28802 is a tag that is unique to the deployment/namespace pair, in other words, ignore any previous deployments, just make sure that the pods in this deployment stay away from each other.

The deployment put all 3 replicas on a single node!

#### What you expected to happen:
With 3 pods and 4 available identical nodes, I expected these to either be spread across 3 separate nodes or if I had made a mistake, that I would get pods that could not be scheduled.

#### How to reproduce it (as minimally and precisely as possible):
This file is the way that Octopus deploy generates it and a few names have been changed to protect the innocent!

```yaml
kind: Deployment 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      Octopus.Kubernetes.DeploymentName: 'files-deployments-28802' 
  template: 
    metadata: 
      labels: 
        Octopus.Kubernetes.SelectionStrategyVersion: "SelectionStrategyVersion2" 
        Octopus.Project.Id: "projects-701" 
        Octopus.Action.Id: "d569354b-1d26-448a-9f79-dc2438245830" 
        Octopus.Deployment.Id: "deployments-28802" 
        Octopus.RunbookRun.Id: "" 
        Octopus.Step.Id: "f7a8f322-ca2a-4617-9363-9b147dcd1493" 
        Octopus.Environment.Id: "environments-102" 
        Octopus.Deployment.Tenant.Id: "untenanted" 
        Octopus.Kubernetes.DeploymentName: "files-deployments-28802" 
    spec: 
      containers: 
      - name: redirect-files 
        image: registry.azurecr.io/microservices.files:1.0.38 
        ports: 
        - name: http 
          containerPort: 80 
          protocol: TCP 
        envFrom: [] 
        livenessProbe: 
          httpGet: 
            path: /api/version 
            port: 80 
            scheme: HTTP 
          successThreshold: 1 
        startupProbe: 
          httpGet: 
            path: /healthcheck 
            port: 80 
            scheme: HTTP 
          initialDelaySeconds: 5 
          timeoutSeconds: 5 
        securityContext: {} 
      imagePullSecrets: 
      - name: octopus-feedcred-feeds-azure-container-registry 
      affinity: 
        nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms: 
            - matchExpressions: 
              - key: kubernetes.io/os 
                operator: In 
                values: 
                - "linux" 
        podAntiAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector: 
              matchExpressions: 
              - key: Octopus.Deployment.Id 
                operator: In 
                values: 
                - "Deployments-28802" 
            topologyKey: kubernetes.io/hostname 
      dnsConfig: {} 
apiVersion: apps/v1 
metadata: 
  name: 'files-deployments-28802' 
  labels: 
    Octopus.Kubernetes.SelectionStrategyVersion: "SelectionStrategyVersion2" 
    Octopus.Project.Id: "projects-701" 
    Octopus.Action.Id: "d569354b-1d26-448a-9f79-dc2438245830" 
    Octopus.Deployment.Id: "deployments-28802" 
    Octopus.RunbookRun.Id: "" 
    Octopus.Step.Id: "f7a8f322-ca2a-4617-9363-9b147dcd1493" 
    Octopus.Environment.Id: "environments-102" 
    Octopus.Deployment.Tenant.Id: "untenanted" 
    Octopus.Kubernetes.DeploymentName: "files-deployments-28802" 
```
#### Anything else we need to know?:
When I used "preferred" instead of "required", it also did not work. I changed it to require to try and force an error.

This uses a blue/green deployment so it creates all new pods and then switches over the service in 1 go. My only thought is whether anti-affinity can work if all the pods are scheduled at the same time and aren't running so the scheduler won't see the conflict until they are all running.

#### Environment:
- Kubernetes version (use `kubectl version`): Client 1.21 Server 1.20
- Cloud provider or hardware configuration: 4 Linux VMs@ 4 cpu + 8GB with a Rancher GUI
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04 nodes, Windows 10 Octopus Server and Desktop
- Kernel (e.g. `uname -a`): 5.4.0-77-generic
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by kerthcet** [comment]
```
matchExpressions: 
              - key: Octopus.Deployment.Id 
                operator: In 
                values: 
                - "Deployments-28802" 
``` should be 
```
matchExpressions: 
              - key: Octopus.Deployment.Id 
                operator: In 
                values: 
                - "deployments-28802" 
```
it's case-sensitive. 🤧
