### ISSUE TITLE
Confusing/incomplete readiness probe warning when doing external redirections

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#103877]
#### What happened:

Used a HTTP probe with external redirect:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: GUNICORN_CMD_ARGS
          value: "--capture-output --error-logfile - --access-logfile - --access-logformat '%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}'"
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /redirect-to?url=http://httpbin.org/get
            port: 80
            scheme: HTTP
          initialDelaySeconds: 4
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
```

Got warning:
```
  Warning  ProbeWarning  75s (x21 over 95s)  kubelet            Readiness probe warning:
```

Kubelet logs show:
```
Probe terminated redirects for http://10.244.0.20:80/redirect-to?url=http://httpbin.org/get, Response: {302 FOUND 302  ...
```

#### What you expected to happen:

Warning messages either show additional context or don't show `: ""`. I would probably have expected `Readiness probe warning: terminated redirects` or just `Readiness probe warning`

Not a big deal, just a bit confusing message

#### How to reproduce it (as minimally and precisely as possible):
Apply yaml above
#### Environment:
- Kubernetes version (use `kubectl version`): v1.22.0-beta.1
- Cloud provider or hardware configuration: kind
- OS (e.g: `cat /etc/os-release`): linux
- Kernel (e.g. `uname -a`): 5.10.40
- Install tools: kind

/sig node
