### ISSUE TITLE
StorageClass complexity for static Volumes (Ceph or Longhorn)

### ISSUE THREAD

**Issue by rsoika** [kubernetes/kubernetes#103819]
#### What would you like to be added:

I have a question/feature request about the usage of static volumes.

I am running a self managed kubernetes cluster (v1.21.2). For persistence I am running [Longhorn](https://longhorn.io/) inside my cluster and also a separate [ceph cluster ](https://ceph.io) running outside of my cluster and connecting via the Ceph [ceph-csi plugin](https://github.com/ceph/ceph-csi). Everything works fine.

To define a static volume I currently do the following

1) First I create in my ceph cluster or in lonhorn an image with a specific name and size. This is fine.

2) In the next step I have to create in my kubernetes Deployment a PersistenceVolume and PVC. 

For both - Ceph and Longhorn - the PersistenceVolume seems to be unnecessary complex. For example in ceph it has to look like this:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-dbdata
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: ceph-system
    volumeAttributes:
      "clusterID": "1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      "pool": "kubernetes"
      "staticVolume": "true"
      "imageFeatures": "layering"
    volumeHandle: "my-dbdata"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```

I wonder why I (as an cluster admin) can't simply define a storage class with the csi cluster data
```

  csi:
    driver: rbd.csi.ceph.com
    fsType: ext4
    nodeStageSecretRef:
      name: csi-rbd-secret
      namespace: ceph-system
    volumeAttributes:
      "clusterID": "1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      "pool": "kubernetes"
      "staticVolume": "true"
      "imageFeatures": "layering"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```

...and than reduce my PersitenceVolume to a more simple config:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-dbdata
spec:
  storageClassName: ceph-durable
  volumeHandle: "my-dbdata"
```

Also in Longhorn a static persistence volume looks currently like this containing lot of csi details:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-dbdata
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: dbdata
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: my-db
  storageClassName: longhorn-durable
```

In longhorn you can define a storage class, but even here I need to provice CSI data like the driver name for each PersistenceVolume.

I asked the question first in the [ceph-csi community](https://github.com/ceph/ceph-csi/issues/2299) and the answer was that this is a restriction from Kubernetes and not form Ceph.

#### Why is this needed:

To sum it up: It would be easier for projects in my Kubernetes Cluster if a PersitenceVolume could be defined like this:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-dbdata
spec:
  storageClassName: ceph-durable
  volumeHandle: "my-dbdata"
```
The project should not know the details about the CSI drivers and storage cluster IDs or capacity. For a static volume I should be sufficient to define the storageClassName and the volumeHandle to define the storage image uniquely.

What did you think about this?
