### ISSUE TITLE
`kubectl exec` was failed when use socks5 proxy

### ISSUE THREAD

**Issue by Patrick0308** [kubernetes/kubernetes#104005]
#### What happened:
```
❯ k exec --tty sleep-64d7d56698-bct4r -n sample -c sleep -- sh
error: error sending request: Post "https://9881A2BCF1B7A06ABFBDAA4EC92FFAC3.sk1.ap-east-1.eks.amazonaws.com/api/v1/namespaces/sample/pods/sleep-64d7d56698-bct4r/exec?command=sh&container=sleep&stderr=true&stdout=true": EOF
```

#### What you expected to happen:
Not fail.

#### How to reproduce it (as minimally and precisely as possible):
To create a socks5 proxy though ssh tunnel or another way.
And add config in ~/.kube/config, for example;
```
clusters:
- cluster:
   certificate-authority-data: *****
   proxy-url: socks5://127.0.0.1:9999
   server: ****
```
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
