### ISSUE TITLE
Kubelet reporting 137 exit code for a container whose exit code 0 was previously known

### ISSUE THREAD

**Issue by ptnapoleon** [kubernetes/kubernetes#104107]
#### What happened:
I have pods with a `RestartPolicy: Never` that perform a task, wait for a sigterm, clean up and then exit. These pods have only one container inside them. I have observed on kubernetes > 1.20.0, that after issuing a graceful delete, sometimes these pods will be stuck in `Terminating`. Upon describing the pod, I can see the following state:

```
    State:          Waiting
      Reason:       ContainerCreating
    Last State:     Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was deleted.  The container used to be Running
      Exit Code:    137
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
```

I have confirmed from the `containerd` logs (the container runtime I am using) and with `strace`, that the pods are receiving a single `sigterm` and then exiting, with an exitCode of 0. I have been patching log statements into kubelet and I am now confident I understanding _what_ is happening, though I do not know why. All of the following statements relate specifically to commit `4aa451e8458a7cbf78ed464e9e47e87d424541ce`, which I believe is the sha for kubernetes `1.21.1`.

In https://github.com/kubernetes/kubernetes/blob/4aa451e8458a7cbf78ed464e9e47e87d424541ce/pkg/kubelet/kubelet.go#L1960-L1982, upon receiving a `pleg.ContainerDied` event for the pod sandbox, which for `containerd` is a container, https://github.com/kubernetes/kubernetes/blob/4aa451e8458a7cbf78ed464e9e47e87d424541ce/pkg/kubelet/kubelet.go#L1980 is called. This leads to us calling https://github.com/kubernetes/kubernetes/blob/4aa451e8458a7cbf78ed464e9e47e87d424541ce/pkg/kubelet/kubelet.go#L2268-L2269, and the returned `podStatus` is passed to https://github.com/kubernetes/kubernetes/blob/4aa451e8458a7cbf78ed464e9e47e87d424541ce/pkg/kubelet/kubelet.go#L2273. This takes us to https://github.com/kubernetes/kubernetes/blob/4aa451e8458a7cbf78ed464e9e47e87d424541ce/pkg/kubelet/kubelet_pods.go#L1519-L1522 where we immediately call `convertStatusToAPIStatus` with the `podStatus` arg. This function calls https://github.com/kubernetes/kubernetes/blob/4aa451e8458a7cbf78ed464e9e47e87d424541ce/pkg/kubelet/kubelet_pods.go#L1621-L1627, and we end up setting the ExitCode to 137 https://github.com/kubernetes/kubernetes/blob/4aa451e8458a7cbf78ed464e9e47e87d424541ce/pkg/kubelet/kubelet_pods.go#L1810-L1817.  Why does that happen? Well, it turns out that `podStatus.ContainerStatuses` is an empty slice at this point in time. 

Knowing that we got that `podStatus` from `kl.PodCache.Get`, I trace backwards and find that the slice of `ContainerStatuses` is empty because the last time this cache was updated, at `pleg/generic.go#updatecache`, we call `container/runtime.go#GetPodStatus` which is implemented in `kuberuntime_manager.go#GetPodStatus`, which calls `kuberuntime_container.go#getPodContainerStatuses`, which calls `cri/remote_riuntime.go#ListContainers`, which is getting an empty list of containers back from `containerd`, thus is ends up putting an empty list of container statuses in the cache. Just to confirm, I can see that the `ListContainers` request kubelet is sending seems correct, and has the correct pod UID in the filter.

#### What you expected to happen:

I've compared the above situation to a pod that cleans up correctly. Ultimately, I can only find one difference. For a "good" pod, inside `syncLoopIteration` in `kubelet.go`, we see a `pleg.ContainerDied` for the container, then a `pleg.ContainerDied` for the pod sandbox, then a `pleg.ContainerRemoved` for the container.

For a "bad" pod, the order is changed. We see the `pleg.ContainerDied` for the container, then a `pleg.ContainerRemoved` for the container, then the `pleg.ContainerDied` for the pod sandbox. In no case do I ever see a `pleg.ContainerRemoved` for the pod sandbox.

I would expect, given that the only container is exiting with 0, and `containerd` does know that at some point, that it would be reflected correctly in kubelet. 

#### How to reproduce it (as minimally and precisely as possible):

I am very sorry, but I have not been able to write a test that reproduces this. If that's a blocker, I can try to write a pod similar enough to [my pod spec](https://github.com/DataDog/chaos-controller/blob/8c64ef47a9e14cc79af287d85b380b0d791666eb/controllers/disruption_controller.go#L679-L831) to reproduce. I am happy to share any logs, run any patches, assist in any way, etc. If anyone has guidance on what _could_ be wrong, I can look into that on my own as well.

I have tested many times and am completely unable to reproduce this on the kubernetes 1.19 line. I am able to reproduce it very consistently on all tested kubernetes 1.20 and above, but have only debugged in 1.21.1 and only care about a fix there. 

We have found that the more pods on a single node, and the more pods being deleted at once, increase the odds of reproduction. Beyond that, I have no reproduction steps beyond creating many pods with a `RestartPolicy: Never` and then deleting them after they're Ready/Running.

#### Anything else we need to know?:

I have noticed that all of this occurs while the pod is gracefully terminating. Inside `kubelet.go#syncPod`, there is a check if a pod is currently pending termination. Locally, I have found that the map being checked never has anything in it, and we always return `false` when checking if the pod is pending termination, even when it is. I do not know if this is related to the behavior, but it was notable during debugging.

I can provide kubelet or containerd logs at any verbosity requested. I am comfortable patching kubelet with more logging if there's something specific I can test for you.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.1
- Cloud provider or hardware configuration: MBP 13" 2020
- OS (e.g: `cat /etc/os-release`): Underlying host OS is OS X 11.15
- Kernel (e.g. `uname -a`): Linux minikube 4.19.157 # 1 SMP Mon Jan 18 19:46:48 UTC 2021 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: Running minikube 1.22.0 with containerd 1.4.3

**Comment by ehashman** [comment]
/unassign
I won't be able to get to this one in the short-term

@endocrimes you may wanna take a look at this, there's something happening with the PLEG and container statuses (check out pkg/kubelet/kubelet_pods.go and you'll see where the exit code of 137 is filled in)

**Comment by smarterclayton** [comment]
I think this might be the cache reversion issue (i was convinced to remove the code that freshened the container cache after termination, which means that it's possible that the container is purged before the final status is reported and thus the last exit code is lost).  In theory the "pod` is created and then deleted quickly" e2e should catch this, but it's measuring the opposite (no pod that exited 1 is EVER reported as non-zero, which is a horrific problem).  This test is more "we report an acceptably low % of pods as exiting as non-zero that are actually zero", but that % will never be zero because of other issues (pressure, eviction, GC, etc, Kube is not offering at-most-once semantics, but at-least-once).

**Comment by smarterclayton** [comment]
Knowing what causes the `ContainerRemoved` (GC, pressure, etc) will help us pin down whether this is "the window for reporting this got larger" (due to the safety changes that fixed other bugs) or "there's additional pressure" or  "GC of containers wasn't working before, now it is" or even "we're too aggressively GCing containers of terminating pods when other containers could be instead"

**Comment by ptnapoleon** [comment]
I'll do my best to figure that out. Where is the best place to look for the reason behind a ContainerRemoved event, containerd or kubelet?

**Comment by timstoop** [comment]
I'm not sure how relevant this is, but it might help reproduce the error: We see this issue almost exclusively with Pods running MongoDB. I have no explanation or further indication about what might cause it. These are Pods with either a MongoDB container by itself, or sometimes sidecars with backup tooling (as created by the Percona Server for MongoDB operator). That sidecar experiences an OOMKilled event. At that point, the main container receives a SIGTERM, and the issue as described in the initial messages occurs. This is on Kubernetes 1.21.0.

Happy to provide additional information if I can.

**Comment by timoreimann** [comment]
I think we are hitting pretty much the same issue on a 1.21.3 cluster.

For us it's etcd running as a pod and (not sure if relevant or not) leveraging a CSI-managed PVC. The pod stays stuck indefinitely in the `Terminating` state unless we force-delete it. The pod termination happens as part of a regular namespace deletion with (AFAICT) no pressure, eviction, or similar involved.

We run periodic end-to-end / smoke tests throughout the day, and while the majority of them manages to terminate just fine, we are still able to observe the issue almost on a daily basis. Happy to provide more context and/or data in support of any investigations.

**Comment by javiku** [comment]
We have also seen this kind of errors once in a while, and only in Pods using persistent storage (CSI-managed PVCs).

**Comment by timoreimann** [comment]
@smarterclayton and others: what kind of information can we provide (and how?) to help further analyze this issue?

**Comment by navidnadali** [comment]
We are hitting this pretty often as well now since upgrading to v1.22.7-gke.1500 - It's actually causing us major issues in production documented in #109414 - We can put in resource to provide any further information/diagnostics if it can help resolve this please just let us know

**Comment by dims** [comment]
@navidnadali please contact your GKE support folks please! They take first crack at it and will approach the community as/when needed.

**Comment by dims** [comment]
Thanks @navidnadali

**Comment by timoreimann** [comment]
This is still an issue for us -- by now we have created a controller to detect the situation and address it when it occurs, but that's not a great long-term solution.

Still happy to provide further information / data that may help identify the root cause.

/remove-lifecycle stale

**Comment by navidnadali** [comment]
Hi @timoreimann 

Just to confirm does #110255 not solve your issue (more info on bug report at #109414)

Many thanks

**Comment by timstoop** [comment]
We regularly run into this as well, would love to help to get it solved. We notice it's usually a statefulset with a PV attached, but that's about the only common aspect we can see.

**Comment by timoreimann** [comment]
@navidnadali apologies, I missed your comment.

Do you happen to know which Kubernetes versions that PR is targeting? We yet have some 1.21 and 1.22 clusters in our fleet, and at least 1.21 seems to be affected.

**Comment by telmich** [comment]
This issue is still relevant on kubernetes v1.31.3. We observed that this happens for pods running on a specific node, even though the kubelet versions are all the same on all nodes.

**Comment by nathanperkins** [comment]
Here's my example to reproduce the issue:

`job.yaml`:

```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: incorrect-exit-code-
  labels:
    job: incorrect-exit-code
spec:
  parallelism: 25
  completions: 25
  backoffLimit: 25
  template:
    metadata:
      labels:
        job: incorrect-exit-code
    spec:
      containers:
        - name: incorrect-exit-code
          image: ubuntu
          command:
            - bash
          args:
            - -c
            - |
              #!/bin/bash
              set -euo pipefail

              function cleanup() {
                echo "Caught signal, exiting with code 6..."
                exit 6
              }
              trap cleanup TERM EXIT
              echo "Signal handling is set up"

              filesize_mb=10

              echo "Writing ${filesize_mb} megabytes of random data..."
              head -c "$((filesize_mb * 1024 * 1024))" /dev/random > random.txt

              echo "Wait 120s for eviction..."
              sleep 120 &
              wait $!

              echo "We should never get here because the pod should be evicted. Exiting with code 2..."
              exit 2
          resources:
            limits:
              ephemeral-storage: 5Mi
      restartPolicy: Never
```

Run:

```
kubectl create -f job.yaml
```

Cleanup:

```
kubectl delete jobs.batch -l job=incorrect-exit-code
```

Example pod results:

```
$ kubectl get pods
NAME                              READY   STATUS                   RESTARTS   AGE
incorrect-exit-code-4tnx8-28xn2   0/1     Error                    0          66s
incorrect-exit-code-4tnx8-75855   0/1     Error                    0          67s
incorrect-exit-code-4tnx8-8r4ft   0/1     ContainerStatusUnknown   1          66s
incorrect-exit-code-4tnx8-9bsxd   0/1     Error                    0          63s
incorrect-exit-code-4tnx8-9gn4d   0/1     Error                    0          65s
incorrect-exit-code-4tnx8-bdszn   0/1     Error                    0          63s
incorrect-exit-code-4tnx8-brrm2   0/1     Error                    0          66s
incorrect-exit-code-4tnx8-bxlkn   0/1     Error                    0          65s
incorrect-exit-code-4tnx8-dwrrq   0/1     ContainerStatusUnknown   1          63s
incorrect-exit-code-4tnx8-hwfg8   0/1     Error                    0          63s
incorrect-exit-code-4tnx8-jblsv   0/1     ContainerStatusUnknown   1          64s
incorrect-exit-code-4tnx8-kdm4t   0/1     Error                    0          64s
incorrect-exit-code-4tnx8-kg4lh   0/1     Error                    0          67s
incorrect-exit-code-4tnx8-l6mjm   0/1     Error                    0          65s
incorrect-exit-code-4tnx8-lh7lq   0/1     ContainerStatusUnknown   1          65s
incorrect-exit-code-4tnx8-m4b24   0/1     Error                    0          63s
incorrect-exit-code-4tnx8-mh7dq   0/1     ContainerStatusUnknown   1          66s
incorrect-exit-code-4tnx8-mvbxw   0/1     Error                    0          67s
incorrect-exit-code-4tnx8-n7vvc   0/1     Error                    0          65s
incorrect-exit-code-4tnx8-nffss   0/1     Error                    0          67s
incorrect-exit-code-4tnx8-q4wzk   0/1     Error                    0          67s
incorrect-exit-code-4tnx8-qlprj   0/1     Error                    0          64s
incorrect-exit-code-4tnx8-rpw9d   0/1     ContainerStatusUnknown   1          64s
incorrect-exit-code-4tnx8-rrqqn   0/1     ContainerStatusUnknown   1          65s
incorrect-exit-code-4tnx8-xh6d4   0/1     Error                    0          64s
```

Example pod status:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-04-10T01:00:13Z"
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-04-10T01:00:02Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-04-10T01:00:13Z"
    reason: PodFailed
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-04-10T01:00:13Z"
    reason: PodFailed
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-04-10T01:00:02Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: ubuntu
    imageID: ""
    lastState:
      terminated:
        exitCode: 137
        finishedAt: null
        message: The container could not be located when the pod was deleted.  The
          container used to be Running
        reason: ContainerStatusUnknown
        startedAt: null
    name: incorrect-exit-code
    ready: false
    restartCount: 1
    started: false
    state:
      terminated:
        exitCode: 137
        finishedAt: null
        message: The container could not be located when the pod was terminated
        reason: ContainerStatusUnknown
        startedAt: null
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-wq9jr
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.16.0.24
  hostIPs:
  - ip: 172.16.0.24
  message: 'Pod ephemeral local storage usage exceeds the total limit of containers
    5Mi. '
  phase: Failed
  podIP: 10.10.0.181
  podIPs:
  - ip: 10.10.0.181
  qosClass: BestEffort
  reason: Evicted
  startTime: "2025-04-10T01:00:02Z"
```
