### ISSUE TITLE
api server's ValidateCustomResource failed for map with additionalProperties of string type

### ISSUE THREAD

**Issue by yongxiu** [kubernetes/kubernetes#104137]
#### What happened:

Trying to use k8s.io/apiextensions-apiserver/pkg/apiserver/validation to validate a YAML file with OpenAPI.

The YAML file contains a map:
```
labels:
    a: b
```

And the openAPIV3Schema generated by kubebuilder contains below logic:
```
                      labels:
                        additionalProperties:
                          type: string
                        description: 'xxx.'
                        type: object
```

When I use this openAPIV3Schema to verify my YAML file, it will have errors:
```
unexpected validation error for map[field:map[a:b]]: [field: Invalid value: "a": field.a in body is a forbidden property]
```

#### What you expected to happen:

It should not throw error

#### How to reproduce it (as minimally and precisely as possible):

I wrote a unit test: https://github.com/kubernetes/apiextensions-apiserver/pull/52/files, this test is failing.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: None.
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yongxiu** [comment]
Any updates on this issue?

**Comment by Jefftree** [comment]
Thanks for following up. AFAIK this is the intended behavior, you would need to specify specific fields and their types to pass the validation or set `x-kubernetes-preserve-unknown-fields` to true.

According to the [documentation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/):

A structural schema is an OpenAPI v3.0 validation schema which:

> specifies a non-empty type (via type in OpenAPI) for the root, for **each specified field of an object node** (via properties or  additionalProperties in OpenAPI) and for each item in an array node (via items in OpenAPI), with the exception of:
> - a node with x-kubernetes-int-or-string: true
> - a node with x-kubernetes-preserve-unknown-fields: true

**Comment by yongxiu** [comment]
I added XPreserveUnknownFields as you mentioned: https://github.com/yongxiu/apiextensions-apiserver/blob/b3c97b674f0286ab34d4044c27d83f59e0f60bdf/pkg/apiserver/validation/validation_test.go#L150
But it's still failing with same error, anything else I'm missing?

**Comment by yongxiu** [comment]
Any updates on this? Is this by design?

**Comment by yongxiu** [comment]
Gentle ping!

**Comment by Shabirmean** [comment]
Following!

**Comment by liggitt** [comment]
I'm not able to reproduce... creating a CRD like this validates CRs properly:

CRD:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: maps.example.com
spec:
  group: example.com
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          labels:
            description: Some description
            type: object
            additionalProperties:
              type: string
  names:
    singular: map
    plural: maps
    kind: Map
    listKind: MapList
```

CR:
```yaml
apiVersion: example.com/v1
kind: Map
metadata:
  name: test
labels:
  a: b
  c: d
```

```sh
kubectl apply -f cr.yaml -o yaml
```

> ```yaml
> apiVersion: example.com/v1
> kind: Map
> labels:
>   a: b
>   c: d
> ```
