### ISSUE TITLE
Describe CRD gives confusing results for condition

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#104138]
All of the elements of a `conditions` list in `kubectl describe` are flattened together. For example (from Gateway CRD http://gateway-api.org/):

describe output:
```
Status:
  Conditions:
    Last Transition Time:  2021-08-04T21:48:19Z
    Message:               something
    Reason:                AddressNotAssigned
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-08-04T21:48:19Z
    Message:               something
    Reason:  ResourcesAvailable
    Status:  True
    Type:    Scheduled
```

This is confusing since it looks like a single condition that somehow repeats "Status" and other fields multiple times

Compare to -oyaml output, which has the `-` to delimit the list:
-oyaml output:
```
status:
  conditions:
  - lastTransitionTime: "2021-08-04T21:48:19Z"
    message: something
    reason: AddressNotAssigned
    status: "False"
    type: Ready
  - lastTransitionTime: "2021-08-04T21:48:19Z"
    message: something
    reason: ResourcesAvailable
    status: "True"
    type: Scheduled
```

/sig api-machinery
