### ISSUE TITLE
Deprecated documentation page

### ISSUE THREAD

**Issue by nibbl** [kubernetes/kubernetes#104230]
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/

yaml on this page will initialize a cluster not correctly
during startup we will see requests to deprecated 10248 port

kubeadm init --config kubeadm-config.yaml:
`[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.`

**Comment by SataQiu** [comment]
@nibbl 
I guess this is because the docker in your environment is using `cgroupfs` driver instead of `systemd`.
You can check it with `docker info | grep Cgroup`:
```sh
# docker info | grep Cgroup
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
```

You can also check why `kubelet` failed to start by `journalctl -xeu kubelet`.

**Comment by neolit123** [comment]
> yaml on this page will initialize a cluster not correctly
during startup we will see requests to deprecated 10248 port

the kubelet healthz port 10248 is not deprecated.

> https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/

i don't see anything wrong with the page.

make sure you configure both the CR and the kubelet with matching drivers.
also see this about the 1.22 release notes:
https://github.com/kubernetes/kubeadm/issues/2541#issuecomment-895176372

/close
/kind support

**Comment by yuswift** [comment]
same problem. 
```
docker info | grep Cgroup
 Cgroup Driver: systemd
 Cgroup Version: 1
WARNING: No swap limit support
```

```
cat /var/lib/kubelet/config.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupDriver: systemd
clusterDNS:
```
Aug 12 15:38:41 i-xlusu1t2 kubelet[25452]: E0812 15:38:41.930828   25452 server.go:294] "Failed to run kubelet" err="failed to run Kubelet: misconfiguration: kubelet cgroup driver: \"cgroupfs\" is different from docker cgroup driver: \"systemd\""
```

```
