### ISSUE TITLE
Pod Anti-Affinity scheduling fails when scheduling multiple pods concurrently

### ISSUE THREAD

**Issue by Static-Flow** [kubernetes/kubernetes#104213]
#### What happened: I have a batch of jobs to run in parallel and I want the job pods to each run on their own node. Should be simple enough with pod level anti-affinity but when I create the jobs with `kubectl apply -f ./jobs` multiple pods are assigned to the same pod. 

**Example job yaml:**
 ```
 apiVersion: batch/v1
kind: Job
metadata:
  name: testjob-$SHARD
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        run: testjob
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: run
                operator: In
                values:
                - testjob
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: testjob
        imagePullPolicy: Always
        image: image
        resources:
          requests:
            memory: "3072Mi"
          limits:
            memory: "4Gi"
        command: ["./foo"]
        securityContext:
          privileged: true
      restartPolicy: OnFailure
```

My guess is that because they are all started at the same time, POD A is assigned to Node 1, but since POD A is in "Container Creating" state and not "Running" that the scheduler thinks it can assign POD B to Node 1 as well. Is this intended? Does it work correctly if I use 1 job yaml that creates all the parallel pods?

#### What you expected to happen: 
I expect that when one pod is assigned to a node with a anti-affinity label that no other pod with that label will be assigned to the node regardless of the first pods state.

#### How to reproduce it (as minimally and precisely as possible):
Place multiple copies of the above yaml in a folder and use `kubectl apply` on the folder to create them all at once. Multiple pods should be assigned to the same node.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: Linode
