### ISSUE TITLE
INTERNAL_ERROR when patching a Service

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/kubernetes#104329]
#### What happened:

Patching a Kubernetes service failed with `INTERNAL_ERROR`
```
error: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"helloworld\",\"namespace\":\"default\"},\"spec\":{\"externalName\":\"envoy.contour-internal.svc.cluster.local\",\"ports\":[{\"name\":\"http2\",\"port\":80,\"protocol\":\"TCP\"}],\"sessionAffinity\":\"None\",\"type\":\"ExternalName\"}}\n"}},"spec":{"clusterIP":null,"externalName":"envoy.contour-internal.svc.cluster.local","type":"ExternalName"}}
to:
Resource: "/v1, Resource=services", GroupVersionKind: "/v1, Kind=Service"
Name: "helloworld", Namespace: "default"
for: "STDIN": Patch "https://127.0.0.1:51792/api/v1/namespaces/default/services/helloworld?fieldManager=kubectl-client-side-apply": stream error: stream ID 5; INTERNAL_ERROR
```

#### How to reproduce it (as minimally and precisely as possible):

I `kubectl apply -f` the following yaml documents

Create an external name service 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  externalName: envoy.contour-internal.svc.cluster.local
  ports:
  - name: http2
    port: 80
    protocol: TCP
  sessionAffinity: None
  type: ExternalName
```

Change to to an ClusterIP Service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  clusterIP: None  
  ports:
    - name: http2
      protocol: TCP
      port: 80
```

Try to change it back to an external name service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  externalName: envoy.contour-internal.svc.cluster.local
  ports:
  - name: http2
    port: 80
    protocol: TCP
  sessionAffinity: None
  type: ExternalName
```

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

```
$ kind version
kind v0.11.1 go1.16.4 darwin/amd64

$ docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
