### ISSUE TITLE
Container marked OOMKilled when a non init process gets killed

### ISSUE THREAD

**Issue by s4mur4i** [kubernetes/kubernetes#104454]
#### What happened:
Init container exited with OOMKilled reason, but init container was marked succesful, and main app container was allowed to be started

#### What you expected to happen:
If non init process gets killed the container should not be marked OOMKilled
or
If OOMKilled is terminate reason main app contaienr should not be started.

According to https://github.com/kubernetes/kubernetes/issues/50632#issuecomment-322849618
Container should only be marked OOMKilled if init process is killed.

#### How to reproduce it (as minimally and precisely as possible):
1. Build the container
2. Deploy the Deploy.yaml

When checking init container status:
```
    State:          Terminated
      Reason:       OOMKilled
      Exit Code:    0
      Started:      Thu, 19 Aug 2021 16:22:29 +0300
      Finished:     Thu, 19 Aug 2021 16:22:30 +0300
```
But main app container is running. 

#### Environment:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

Dockerfile:
```
FROM ubuntu:trusty
RUN apt-get update && apt-get install -y stress
ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
CMD ["/entrypoint.sh"]
```
Entrypoint.sh:
```
#!/bin/bash
while true
do
   /usr/bin/stress --verbose --vm 2 --vm-bytes 128M --timeout 10s
   if [[ ! -z "${INIT_CONTAINER}" ]]
   then
     exit 0
   fi
   sleep 86400
done
```
Deploy.yaml:
```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  labels:
    app: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      initContainers:
      - name: stress-init
        image: stress:latest
        imagePullPolicy: Always
        env:
        - name: INIT_CONTAINER
          value: "yes"
        resources:
          limits:
            memory: 64Mi
      containers:
        - name: stress
          image: stress:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 32Mi
```
