### ISSUE TITLE
CRD: Top level x-kubernetes-preserve-unknown-fields breaks kubectl explain

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/kubernetes#104419]
#### What happened:

`kubectl explain` breaks when used on a CRD with a top level `x-kubernetes-preserve-unknown-fields: true`.

#### What you expected to happen:

A coworker encountered this and I'm not sure what the expected behavior is. I think I'd expect either a validation error if this is is invalid or `kubectl explain` to still output descriptions and fields.

#### How to reproduce it (as minimally and precisely as possible):

<details>
<summary>Without top level `x-kubernetes-preserve-unknown-fields`:</summary>

```
cat <<EOF > crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.kuberneddies.dev
spec:
  group: kuberneddies.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          # x-kubernetes-preserve-unknown-fields: true
          type: object
          description: I am the top level description
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example
    shortNames:
    - ex
EOF

kubectl apply -f crd.yaml

kubectl explain example
```

```
KIND:     Example
VERSION:  kuberneddies.dev/v1

DESCRIPTION:
     I am the top level description

FIELDS:
   apiVersion   <string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
...
```
</details>

<details>
<summary>With top level `x-kubernetes-preserve-unknown-fields`:</summary>

```
cat <<EOF > crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.kuberneddies.dev
spec:
  group: kuberneddies.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
          description: I am the top level description
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example
    shortNames:
    - ex
EOF

kubectl apply -f crd.yaml

kubectl explain example
```

```
KIND:     Example
VERSION:  kuberneddies.dev/v1

DESCRIPTION:
     <empty>
```
</details>

#### Anything else we need to know?:

I'm not too familiar with this extension and this could indeed be the expected behavior.

#### Environment:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

/sig cli
/sig api-machinery
/area custom-resources
/area kubectl

cc @Shreya027
