### ISSUE TITLE
Kubectl always shows a diff for HPA

### ISSUE THREAD

**Issue by graywolf-at-work** [kubernetes/kubernetes#104417]
#### What happened:

After applying something, there is always a diff:

```
diff -u -N /tmp/LIVE-473397915/autoscaling.v2beta2.HorizontalPodAutoscaler.auth.auth /tmp/MERGED-122008894/autoscaling.v2beta2.HorizontalPodAutoscaler.auth.auth
--- /tmp/LIVE-473397915/autoscaling.v2beta2.HorizontalPodAutoscaler.auth.auth   2021-08-17 18:20:24.879138222 +0200
+++ /tmp/MERGED-122008894/autoscaling.v2beta2.HorizontalPodAutoscaler.auth.auth 2021-08-17 18:20:24.919138503 +0200
@@ -88,6 +88,13 @@
         averageValue: 500m
         type: AverageValue
     type: Pods
+  - pods:
+      metric:
+        name: pod:cpu_utilisation:ratio1m
+      target:
+        averageValue: 500m
+        type: AverageValue
+    type: Pods
   minReplicas: 2
   scaleTargetRef:
     apiVersion: apps/v1
```

It tries to add the exact same metric again, but after apply there is still just one so maybe a bug in the diffing logic?

#### What you expected to happen:

Since it was just applied, I would expect no changes to be shown. Seems to be same as 94420 which was closed by really helpful fejta bot without any resolution.

#### How to reproduce it (as minimally and precisely as possible):

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: auth
  namespace: auth
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 1
  maxReplicas: 32
  metrics:
  - pods:
      metric:
        name: pod:cpu_utilisation:ratio1m
      target:
        averageValue: 0.5
        type: AverageValue
    type: Pods
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth
```

#### Anything else we need to know?:

No.

#### Environment:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by graywolf-at-work** [comment]
/tmp/MERGED- file actually has

```
metrics:
- pods:
    metric:
      name: pod:cpu_utilisation:ratio1m
    target:
      averageValue: 500m
      type: AverageValue
  type: Pods
- pods:
    metric:
      name: pod:cpu_utilisation:ratio1m
    target:
      averageValue: 500m
      type: AverageValue
  type: Pods
```

So it looks like a bug during the merging.
