### ISSUE TITLE
I use China's azure file, and I expect the mount to be chinacloudapi.cn instead of windows.net

### ISSUE THREAD

**Issue by jiaozh8** [kubernetes/kubernetes#104501]
I deployed the Kubenetes cluster in azure vm, the version is 1.17.9, now based on the StatefulSet deployment service, need to use azure file, I first create a secret, then create a storageclass and pv, pvc is defined in the helm template

create secret
```
apiVersion: v1  
kind: Secret  
metadata:  
  name: static-persistence-secret  
type: Opaque  
data:  
  azurestorageaccountname: "YXpjb3B5dGVzdAo="
  azurestorageaccountkey: "xxxxxxxx"
```
create StorageClass
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefilestorage
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: azcopytest
reclaimPolicy: Retain
allowVolumeExpansion: true
```

create pv
```
apiVersion: v1  
kind: PersistentVolume  
metadata:  
  name: static-persistent-volume-nacos-0  
  labels:  
    storage: azurefile  
spec:  
  capacity:  
    storage: 5Gi  
  accessModes:  
    - ReadWriteMany  
  storageClassName: azurefilestorage  
  azureFile:  
    secretName: static-persistence-secret  
    shareName: testmongo  
    readOnly: false

  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - actimeo=30
```

My problem is that the viewing pod fails to start. The reason is that the azure endpoint is not chinacloud.cn, but windows.net. I manually modified it to chinacloud.cn and it can be successfully mounted on the linux server. 
The log is as follows:

> Mounting command: systemd-run
> Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/9e5d59a5-627e-40f9-acc8-e25819dfc6c0/volumes/kubernetes.io~azure-file/static-persistent-volume-nacos-0 --scope -- mount -t cifs -o username=azcopytest,password=xxxxx,file_mode=0777,dir_mode=0777,vers=3.0 //azcopytest.file.core.windows.net/testmongo /var/lib/kubelet/pods/9e5d59a5-627e-40f9-acc8-e25819dfc6c0/volumes/kubernetes.io~azure-file/static-persistent-volume-nacos-0
> Output: Running scope as unit run-r3d2d2e1f4b0b4949a00399c3148440ea.scope.
> mount error(13): Permission denied
> Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
>   Warning  FailedMount  11s  kubelet, iotrmcninfvmsa002  MountVolume.SetUp failed for volume "static-persistent-volume-nacos-0" : mount failed: exit status 32

I check the kubelet log, there is one entry: 
kubelet[6316]: W0822 02:47:18.459908 6316 azure_file.go:393] No Azure cloud provider found. Using the Azure public cloud endpoint: core.windows.net

I have tried adding --cloud-provider=azure --cloud-config=/etc/kubernetes/azure.json to kube-apiserver, kube-scheduler, kubelet, and found that kube-scheduler cannot be started without this parameter

Can you help me see how to solve it. 
Thank you very much
