### ISSUE TITLE
🐛 Quota Admission CheckRequest returns error vs pkg/api/errors

### ISSUE THREAD

**Issue by christopherhein** [kubernetes/kubernetes#104505]
#### What happened:

When using PriorityClasses and Resource quotas if there is insufficient quota in a specific priorityclass it will return `fmt.Errorf` instead of using `pkg/api/errors` this means when it's passed down to the response handler it has to construct the `metav1.Status` object. This also then emits a log line like:

```
E0822 22:44:35.449305  466021 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"insufficient quota to match these scopes: [{PriorityClass In [system-cluster-critical system-node-critical a b c d]}]"}
```

#### What you expected to happen:

The admission controller shouldn't return an unstructured error using `fmt.Errorf` instead it should return a `metav1.Status` so that the response package can pass it through.

#### How to reproduce it (as minimally and precisely as possible):

1. Create cluster with `AdmissionConfiguration`:

```yaml
apiVersion: apiserver.k8s.io/v1alpha1
kind: AdmissionConfiguration
plugins:
  - name: "ResourceQuota"
    configuration:
      apiVersion: apiserver.config.k8s.io/v1
      kind: ResourceQuotaConfiguration
      limitedResources:
      - resource: pods
        matchScopes:
        - scopeName: PriorityClass 
          operator: In
          values: ["system-cluster-critical", "system-node-critical", "high-stateful", "a", "b", "c"]
```
2. Create `ResourceQuota` for pods with limited quota
3. Try to exceed the quota with a too many pods
4. Check kube-apiserver logs for something like:

```
E0822 22:44:35.449305  466021 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"insufficient quota to match these scopes: [{PriorityClass In [system-cluster-critical system-node-critical a b c d]}]"}
```

#### Environment:
- Kubernetes version (use `kubectl version`):

```
→ k version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
