### ISSUE TITLE
Consider PodDisruptionBudgets to allow zonal disruptions

### ISSUE THREAD

**Issue by alanprot** [kubernetes/kubernetes#104583]
Some applications can tolerate multiple disruptions if the pods being disrupted are in the same Availability Zone. For instance, one of our applications have replicated data across AZ using a StatefulSet (+ topologySpreadConstraints) to make sure the data is available during an eventual AZ outage. Because of that, we can tolerate multiples pods being disrupted IF they are in the same AZ.

Is it possible to configure the PDB in a way that it continue to allow disruptions only if the pods being disrupted belongs to the same AZ?

I was thinking that we can extent the PDB to add a something like `disruptionBudgetKey` where we can set a node/pod label:

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ingester-pdb
spec:
  selector:
    matchLabels:
      name: ingester
disruptionBudgetKey: "topology.kubernetes.io/zone"
podDisruptionBudget:
   maxUnavailable: 1
```

Thanks :D
