### ISSUE TITLE
Unable to use private repository images as initContainer with imagePullSecrets

### ISSUE THREAD

**Issue by sniranjan** [kubernetes/kubernetes#104527]
I am trying to use a private docker image(from Artifactory) as `initContainer` with correct `imagePullSecrets`, but I keep getting `ErrImagePull `

On the Artifactory side, we see `anonymous pull attempts`

```
2021-08-23T13:12:29.512Z [d0152282e43f6480] [DENIED DOWNLOAD] private-repoo-local:docker/19.03/manifest.json  for client : NA / 12.2.3.3.
```
#### What happened:

ErrImagePull - Kubernetes secret not being used

#### What you expected to happen:

The image should be pulled with the provided secret

#### How to reproduce it (as minimally and precisely as possible):

```
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  imagePullSecrets:
    - name: <private-repo-secret>
  initContainers:
    - name: docker-demo
      image: <private-repo>/docker:latest
      command: ["docker", "-v"]
  containers:
    - name: pause
      image: gcr.io/google_containers/pause

```

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:13:35Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration: AWS EKS
