### ISSUE TITLE
Init Container in CrashLoop while regular containers are running

### ISSUE THREAD

**Issue by konstantin-tkachuk** [kubernetes/kubernetes#104629]
#### What happened:
I have a deployment where each pod has 1 initContainer and 3 regular containers. These pods usually work as expected, however I have observed several times now that occasionally they manage to fall into a state where the 3 regular containers are working and serving traffic, _while the initContainer is stuck in a CrashLoop_. 

#### What you expected to happen:
I expect an initContainer to be run and completed before the regular containers even start. A state where an initContainer gets executed again _after_ it already completed once should never happen. 
The initContainer in question sets up some iptables rules, so the fact that on subsequent restarts it fails with a "Chain already exists" message is understandable. It should not restart in the first place.

#### How to reproduce it (as minimally and precisely as possible):
Sadly, I am unable to intentionally reproduce this behaviour. I have observed it twice over the last couple of weeks. Forcing a pod to restart by killing a container using kubectl exec was not enough to reproduce. I am open to ideas.

#### Environment:
- Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes was setup using Rancher v2.5.5 on AWS EC2 instances.

#### Anything else we need to know?:
Kubectl view of the pods:
```
-> kubectl -n navigation-service-master get pods
NAME                                         READY   STATUS                  RESTARTS   AGE
navigation-service-master-578dcbb845-5tr4x   3/3     Running                 4          31d
navigation-service-master-578dcbb845-hg7tv   0/3     Init:CrashLoopBackOff   1754       31d
navigation-service-master-578dcbb845-tckhp   0/3     Init:CrashLoopBackOff   2036       31d
```
The kube_pod_container_status_restarts_total and kube_deployment_status_replicas_available metrics _do not show these restarts_! According to them the pods are just fine - and well, in some sense they are, because they _are_ correctly serving traffic.

The status of the pod. You see 3 regular containers running and the initContainer in a CrashLoop.
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-08-18T07:10:05Z"
    message: 'containers with incomplete status: [proxy-init]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-08-19T11:52:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-08-19T11:52:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-07-23T14:10:14Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b09901b4515b9badcea39717a0af745ae4feadb905f2c4d3f90997e7fc5ffc83
    image: envoyproxy/envoy:v1.16.0
    imageID: docker-pullable://envoyproxy/envoy@sha256:9e72bbba48041223ccf79ba81754b1bd84a67c6a1db8a9dbff77ea6fc1cb04ea
    lastState: {}
    name: envoy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-07-23T14:10:18Z"
  - containerID: docker://7f0a8b3638223fd34fcc126bc8b9b459687ed3d5416f2a527f183283c3a9a4df
    image: docker.artifactory.e-spirit.de/e-spirit/navigation/navigation-service:1.4.2
    imageID: docker-pullable://docker.artifactory.e-spirit.de/e-spirit/navigation/navigation-service@sha256:0151005e4003fe0a2ce05d48aa47c06b557a3747baa08ecac1c0bec71cde3136
    lastState: {}
    name: navigation-service
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-07-23T14:10:18Z"
  - containerID: docker://4552ed117079d576f09a0085175d5209c7e4eed42cd86f3d844217d5e48bb9c7
    image: openpolicyagent/opa:latest-envoy
    imageID: docker-pullable://openpolicyagent/opa@sha256:b6d13a52dc2abed2915a49d831e25c4649f4106b8c854e81b8fb69d00ef351fe
    lastState: {}
    name: opa
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-07-23T14:10:18Z"
  hostIP: 172.23.37.108
  initContainerStatuses:
  - containerID: docker://d6bec57675a8ba6339bc199dda54cefdc814297b3d2a15df88661b26c9b1417c
    image: openpolicyagent/proxy_init:v5
    imageID: docker-pullable://openpolicyagent/proxy_init@sha256:8f988a690516728b08956f2838a7a08202547e44d2c962009301d738c7a4abae
    lastState:
      terminated:
        containerID: docker://d6bec57675a8ba6339bc199dda54cefdc814297b3d2a15df88661b26c9b1417c
        exitCode: 1
        finishedAt: "2021-08-24T12:53:25Z"
        reason: Error
        startedAt: "2021-08-24T12:53:25Z"
    name: proxy-init
    ready: false
    restartCount: 1759
    state:
      waiting:
        message: back-off 5m0s restarting failed container=proxy-init pod=navigation-service-master-578dcbb845-hg7tv_navigation-service-master(29dcfc04-6295-4f51-8c19-40ee5a1b0e81)
        reason: CrashLoopBackOff
  phase: Running
  podIP: 10.42.8.193
  podIPs:
  - ip: 10.42.8.193
  qosClass: Burstable
  startTime: "2021-07-23T14:10:14Z"
```
