### ISSUE TITLE
Service deleting get stuck

### ISSUE THREAD

**Issue by eliecer2323** [kubernetes/kubernetes#104618]
#### What happened:
I'm trying to delete a service with the `kubect delete service claims` but it never finish (I have had let it run by 12 hours) so I have to press `ctrl+c` but the service doesn't get eliminated

#### What you expected to happen:
Write `kubect delete service claims` and get he service eliminated so I can write `kubectl get services`
 and don't see it them

#### How to reproduce it (as minimally and precisely as possible):
I am using the AWS Load Balancer Controller to expose the deployment by a Network Load Balancer in AWS, so basically I ran the next config file to generate the deployment and its service, after making all my tests I was going to delete them so I tipped `kubectl delete deployment claims` and `kubectl delete service claims`, the first one finish successfully but the second one get stuck and never finishes.

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: claims
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claims
  template:
    metadata:
      labels:
        app: claims
    spec:
      containers:
        - name: claims
          image: $AWS_REGISTRY_IMAGE:$CI_COMMIT_SHA
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: claims
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: NodePort
  ports:
    - name: claims
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: claims
```

#### Anything else we need to know?:
I had to delete the Load Balancer manually in the AWS Console for stopping cost billing but the service is still present and stuck in kubernetes

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): MacOS Big Sur version 11.5.2
- Kernel (e.g. `uname -a`): Darwin Kernel Version 20.6.0
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: Kubectl version 1.22.1, eksctl version 0.62.0
