### ISSUE TITLE
Incorrect initContainers order when using server-side apply

### ISSUE THREAD

**Issue by cbandy** [kubernetes/kubernetes#104641]
#### What happened:

The order of `initContainers` is significant, but when using `kubectl apply --server-side` to change this field, the intended order is not preserved.

#### What you expected to happen:

I expected the order of `initContainers` to match my submitted intent.

#### How to reproduce it (as minimally and precisely as possible):

Files:

```yaml
==> 00.yaml <==                                                            
apiVersion: v1
kind: Service
metadata:                                                                  
  name: init-container-order
spec:                
  clusterIP: None                                                          
---                                                                        
apiVersion: apps/v1                                                        
kind: StatefulSet
metadata:                                                                  
  name: init-container-order
spec:
  serviceName: init-container-order
  selector:
    matchLabels: { name: init-container-order }
  template:
    metadata:
      labels: { name: init-container-order }
    spec:
      initContainers:
      - { image: busybox, name: original }
      containers:
      - { image: busybox, name: main }

==> 01.yaml <==
apiVersion: v1
kind: Service
metadata:
  name: init-container-order
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: init-container-order
spec:
  serviceName: init-container-order
  selector:
    matchLabels: { name: init-container-order }
  template:
    metadata:
      labels: { name: init-container-order }
    spec:
      initContainers:
      - { image: busybox, name: first }
      - { image: busybox, name: original }
      - { image: busybox, name: last }
      containers:
      - { image: busybox, name: main }
```

```diff
● diff -u 00.yaml 01.yaml 
--- 00.yaml     2021-08-27 20:39:10.000000000 -0500
+++ 01.yaml     2021-08-27 20:39:08.000000000 -0500
@@ -18,6 +18,8 @@
       labels: { name: init-container-order }
     spec:
       initContainers:
+      - { image: busybox, name: first }
       - { image: busybox, name: original }
+      - { image: busybox, name: last }
       containers:
       - { image: busybox, name: main }
```

---

Create the StatefulSet and see it has one init container:

```
● kubectl apply --server-side -f 00.yaml 
service/init-container-order serverside-applied
statefulset.apps/init-container-order serverside-applied

● kubectl get sts/init-container-order -o jsonpath='{.spec.template.spec.initContainers[*].name}{"\n"}'
original
```

Add two more init containers, one before and one after the original. See that they are **both added to the end**:

```
● kubectl apply --server-side -f 01.yaml 
service/init-container-order serverside-applied
statefulset.apps/init-container-order serverside-applied

● kubectl get sts/init-container-order -o jsonpath='{.spec.template.spec.initContainers[*].name}{"\n"}'
original first last
```

#### Anything else we need to know?:

`kubectl replace` puts them in the intended order:

```
● kubectl replace -f 01.yaml 
service/init-container-order replaced
statefulset.apps/init-container-order replaced

● kubectl get sts/init-container-order -o jsonpath='{.spec.template.spec.initContainers[*].name}{"\n"}'
first original last
```

#### Environment:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Install tools: `k3d`, `brew install kubernetes-cli`

/sig api-machinery
