### ISSUE TITLE
kube-apiserver pod livenessProbe: why is kube-apiserver pod still `running` status when etcd healthz check failed 

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#104786]
#### What happened:
The livenessProbe method used is `exec`.
```yaml
readinessProbe:
  exec:
    command: ["curl", "-L", "-g", "--connect-timeout", "10", "--cacert", "/etc/kubernetes/certs/etcd/ca.crt", "--cert", "/etc/kubernetes/certs/etcd/etcd-client.crt", "--key", "/etc/kubernetes/certs/etcd/etcd-client.key", "https://192.168.33.100:3443/livez"]
  failureThreshold: 8
  initialDelaySeconds: 15
  timeoutSeconds: 15
```
When etcd is  down, apiserver detects that etcd health check failed, but apiserver pod  still running status.

 `httpGet` is ok. but `--anonymous-auth` must be set `true`, I don't want to set `--anonymous-auth`  to true when I use `HTTPS`.
```yaml
livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 192.168.33.100
        path: /livez
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
```

apiserver log:
```
I0906 10:29:37.198682       1 healthz.go:243] healthz check failed: etcd
```

apiserver status:
```
NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
kube-system   kube-apiserver-192.168.33.100            1/1     Running   0          13m
```

#### What you expected to happen:

kube-apiserver pod status should is `crashloopbackoff`.
or
I set `--anonymous-auth`  to `false`, `/health`、`/livez` do not require permission verification

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
