### ISSUE TITLE
kube-apiserver: Liveness probe failed: HTTP probe failed with statuscode: 401

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#104731]
#### What happened:
My `kube-apiserver.yaml` probe is configured as follows(I exclude `etcd` health check):
```yaml
...
 livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 192.168.33.100
        path: /livez?exclude=etcd
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
...
```

but liveness probe  is failed.

single quotation `'/livez?exclude=etcd'` is also failed.

#### What you expected to happen:
 liveness probe  is successful. 

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
