### ISSUE TITLE
kubemark cluster can't work normally

### ISSUE THREAD

**Issue by lixiaoyuner** [kubernetes/kubernetes#104746]
#### What happened:
I set up a kubemark cluster manually. It seems normal.
```
root@vm1:~# kubectl get node
NAME                STATUS   ROLES                  AGE   VERSION
hollow-node-6ghqx   Ready    <none>                 21h   v1.23.0-alpha.0.510+fe099b2abdb023-dirty
hollow-node-9kjkh   Ready    <none>                 21h   v1.23.0-alpha.0.510+fe099b2abdb023-dirty
hollow-node-r9nr5   Ready    <none>                 21h   v1.23.0-alpha.0.510+fe099b2abdb023-dirty
hollow-node-tz4xx   Ready    <none>                 21h   v1.23.0-alpha.0.510+fe099b2abdb023-dirty
hollow-node-xzzk4   Ready    <none>                 21h   v1.23.0-alpha.0.510+fe099b2abdb023-dirty
vm1                 Ready    control-plane,master   22h   v1.21.1
```
I made a camp deployment. So there is a pod called camp-d8945f8cc-v44cn. It works normally.
```
root@vm1:~# kubectl get po -A -o wide
NAMESPACE     NAME                          READY   STATUS    RESTARTS   AGE   IP                NODE                NOMINATED NODE   READINESS GATES
default       camp-d8945f8cc-v44cn          1/1     Running   0          21h   192.168.192.168   hollow-node-r9nr5   <none>           <none>
kube-system   etcd-vm1                      1/1     Running   0          22h   192.168.122.10    vm1                 <none>           <none>
kube-system   kube-apiserver-vm1            1/1     Running   0          22h   192.168.122.10    vm1                 <none>           <none>
kube-system   kube-controller-manager-vm1   1/1     Running   0          22h   192.168.122.10    vm1                 <none>           <none>
kube-system   kube-scheduler-vm1            1/1     Running   0          22h   192.168.122.10    vm1                 <none>           <none>
```
But when I try to look log and dive into the pod. Errors happened. Like this.
```
root@vm1:~# kubectl logs camp-d8945f8cc-v44cn
Error from server: Get "https://10.244.11.10:10250/containerLogs/default/camp-d8945f8cc-v44cn/kubernetes-bootcamp": http: server gave HTTP response to HTTPS client

root@vm1:~# kubectl exec -it camp-d8945f8cc-v44cn -- bash
Error from server: error dialing backend: tls: first record does not look like a TLS handshake
```
#### What you expected to happen:
I can get camp pod's log and can dive into the pod.

#### Anything else we need to know?:
The kubemark hollow-node config.
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: hollow-node
  namespace: kubemark
  labels:
    name: hollow-node
spec:
  replicas: 5
  selector:
    name: hollow-node
  template:
    metadata:
      labels:
        name: hollow-node
    spec:
      initContainers:
      - name: init-inotify-limit
        image: busybox:1.32
        command: ['sysctl', '-w', 'fs.inotify.max_user_instances=1000']
        securityContext:
          privileged: true
      volumes:
      - name: kubeconfig-volume
        secret:
          secretName: kubeconfig
      - name: logs-volume
        hostPath:
          path: /var/log
      - name: containerd
        hostPath:
          path: /run/containerd
      - name: no-serviceaccount-access-to-real-master
        emptyDir: {}
      containers:
      - name: hollow-kubelet
        image: lixiaoyuner/kubemark:latest
        ports:
        - containerPort: 4194
        - containerPort: 10250
        - containerPort: 10255
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: [
          "/kubemark",
          "--morph=kubelet",
          "--name=$(NODE_NAME)",
          "--kubeconfig=/kubeconfig/kubelet.kubeconfig",
          "--log-file=/var/log/kubelet-$(NODE_NAME).log",
          "--logtostderr=false",
        ]
        volumeMounts:
        - name: kubeconfig-volume
          mountPath: /kubeconfig
          readOnly: true
        - name: logs-volume
          mountPath: /var/log
        - name: containerd
          mountPath: /run/containerd
        resources:
          requests:
            cpu: 20m
            memory: 50m
        securityContext:
          privileged: true
      # Keep the pod running on unreachable node for 15 minutes.
      # This time should be sufficient for a VM reboot and should
      # avoid recreating a new hollow node.
      # See https://github.com/kubernetes/kubernetes/issues/67120 for context.
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 900
```
