### ISSUE TITLE
failed to create patch: failed to create two-way merge patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior"

### ISSUE THREAD

**Issue by zt185019** [kubernetes/kubernetes#104935]
#### What happened:
Helm upgrade fails with the following error:
`UPGRADE FAILED Error: failed to create patch: failed to create two-way merge patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior"`
#### What you expected to happen:
Expected to have the upgrade uninterrupted, hpa configuration updated with the modified field to a different value. (periodSeconds)
#### How to reproduce it (as minimally and precisely as possible):
1. create yaml for hpa
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
2. regular setup at first
min max replicas, cpu and memory targets for scaling.
3. install
4. add behavior spec
5. upgrade
6. update any field under behavior spec (in my case I updated periodSeconds from 120 to 100)
7. upgrade - fails
#### Anything else we need to know?:
Applying the upgrade with the same hpa yaml (unmodified) doesnt make the upgrade fail
Workaround is to delete autoscaling through GCP UI and then perform the upgrade.
#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f
5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-13T15:45:10Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:
"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-gke.2101", GitCommit:"05fc1fdacb292655c77a
2058a32ecc6a82cd71b0", GitTreeState:"clean", BuildDate:"2021-08-18T23:13:48Z", GoVersion:"go1.15.13b5", Compiler:"g
c", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
GCP Kubernetes
- Install tools:
Helm
```
Client: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"cle
an"}
Server: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"cle
an"}
```

**Comment by njegosrailic** [comment]
I can confirm the same problem. 

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.9-gke.1001", GitCommit:"1fe18c314ed577f6047d2712a9d1c8e498e22381", GitTreeState:"clean", BuildDate:"2021-08-23T23:06:28Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
```

```
 ➜ helm version
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
```

Example:
```
    maxReplicas: 6
    behavior:
      scaleDown:
        policies:
-       - periodSeconds: 300
+       - periodSeconds: 120
          type: Percent
          value: 10
-       - periodSeconds: 300
+       - periodSeconds: 120
          type: Pods
          value: 1
        selectPolicy: Max
        stabilizationWindowSeconds: 900
```

```
STDERR:
  Error: UPGRADE FAILED: failed to create patch: failed to create two-way merge patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior"

COMBINED OUTPUT:
  UPGRADE FAILED
  Error: failed to create patch: failed to create two-way merge patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior"
  Error: UPGRADE FAILED: failed to create patch: failed to create two-way merge patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior"
```

It is very interesting that in my case the error happens randomly and sometimes Helm just applies a patch without any problem.

**Comment by Sorionce** [comment]
Hello, I have a similar problem:
`Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: failed to create patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior": failed to create patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior"`
But in my case, I didn't even change behavior field. Even redeploying same yaml cause error. 

`kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1802", GitCommit:"d464a255a4acb8dca1e0914586f4f5085681fb51", GitTreeState:"clean", BuildDate:"2021-10-21T21:43:23Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
`

HPA:
`
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.cpu.targetAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: {{ .Values.hpa.memory.targetAverageValue }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 900
          periodSeconds: 300
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
        - type: Pods
          value: 1
          periodSeconds: 600
`

**Comment by ilyesAj** [comment]
we're having the issue on 1.20.
```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-17T13:00:29Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
![image](https://user-images.githubusercontent.com/34598860/184175780-10696647-e807-4808-95a9-8c93438e036a.png)

**Comment by zt185019** [comment]
shut up robot :) :)
/reopen

**Comment by dankolt** [comment]
The same problem

**Comment by ilyesAj** [comment]
@zt185019 @njegosrailic did you find any workarround for the issue or any root cause for it ?

**Comment by dankolt** [comment]
> The same problem

In my case problem resolved by upgrading helm from 2.17 to 3.9.

**Comment by olehm-ma** [comment]
In my case, the issue was related to the helmcart configuration and the way how json is converted to yaml. In the helm chart I had, something like that

hpa.yaml

```
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetValue }}
  {{- with .Values.hpaBehavior }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
```

values.yaml

```
hpaBehavior:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 3
        periodSeconds: 10
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 500
        periodSeconds: 5
      selectPolicy: Max 
```

In the result hpa manifest looked like

```
    scaleDown:
      policies:
      - periodSeconds: 10 <----------
        type: Percent
        value: 10
      - periodSeconds: 10 <----------
        type: Pods
        value: 15
      selectPolicy: Min
      stabilizationWindowSeconds: 120
    scaleUp:
      policies:
      - periodSeconds: 5 <----------
        type: Percent
        value: 500
      selectPolicy: Max
      stabilizationWindowSeconds: 0
```

The nastiest thing, is that initial install succeeded, however further upgrades failed with `failed to create patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior": failed to create patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior"` error

**Comment by ilyesAj** [comment]
> In my case, the issue was related to the helmcart configuration and the way how json is converted to yaml. In the helm chart I had, something like that
> 
> hpa.yaml
> 
> ```
>     resource:
>       name: cpu
>       target:
>         type: Utilization
>         averageUtilization: {{ .Values.hpa.targetValue }}
>   {{- with .Values.hpaBehavior }}
>     {{- toYaml . | nindent 2 }}
>   {{- end }}
> ```
> 
> values.yaml
> 
> ```
> hpaBehavior:
>   behavior:
>     scaleDown:
>       stabilizationWindowSeconds: 120
>       policies:
>       - type: Pods
>         value: 3
>         periodSeconds: 10
>       selectPolicy: Min
>     scaleUp:
>       stabilizationWindowSeconds: 0
>       policies:
>       - type: Percent
>         value: 500
>         periodSeconds: 5
>       selectPolicy: Max 
> ```
> 
> In the result hpa manifest looked like
> 
> ```
>     scaleDown:
>       policies:
>       - periodSeconds: 10 <----------
>         type: Percent
>         value: 10
>       - periodSeconds: 10 <----------
>         type: Pods
>         value: 15
>       selectPolicy: Min
>       stabilizationWindowSeconds: 120
>     scaleUp:
>       policies:
>       - periodSeconds: 5 <----------
>         type: Percent
>         value: 500
>       selectPolicy: Max
>       stabilizationWindowSeconds: 0
> ```
> 
> The nastiest thing, is that initial install succeeded, however further upgrades failed with `failed to create patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior": failed to create patch: unable to find api field in struct HorizontalPodAutoscalerSpec for the json field "behavior"` error

I'm having the exact same symptoms, how did you manage to fix it ?

**Comment by olehm-ma** [comment]
@ilyesAj  you can try to omit using`toYaml` function for hpaBehavior. 

E.g., 
values.yaml
```
hpaBehavior: |
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 10
        periodSeconds: 10
```

hpa.yaml
```
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetValue }}
        {{ .Values.hpaBehavior | nindent 2}}
```


Or add hpa behavior to the hpa template:
``` 
{{- with .Values.hpaBehavior }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ .scaleDown.percent_value }}
        periodSeconds: {{ .scaleDown.percent_periodSeconds }}
...........

```
