### ISSUE TITLE
kubectl multiple-clusters config error

### ISSUE THREAD

**Issue by wangshiyang** [kubernetes/kubernetes#104999]
What happened: 
When I use `kubectl config` to set up my cluster, I get the error message: `unknown flag: --client-certificate-data`.

How to reproduce it (as minimally and precisely as possible):
like this commad:  
`kubectl config --kubeconfig=mycluster-config2 set-credentials clusteruser2 --client-certificate-data=BASE64DATA --client-key-data=BASE64DATA`
Anything else we need to know?:
I use the official document to operate this.
link: [https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/](url)

 Environment:
- Kubernetes version (use `kubectl version`): 
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):  `Centos7.2`
- Kernel (e.g. `uname -a`): `Linux gfresh-master1 5.13.13-1.el7.elrepo.x86_64 #1 SMP Wed Aug 25 18:38:37 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: ` kubeadm`
- Network plugin and version (if this is a network-related bug): `cilium`

**Comment by pacoxu** [comment]
/sig cli
You may misunderstand the [docs](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/).

The key with the suffix `-data` can be used in kubeconfig file. It is not supported as `kubectl config set-cluster ` flags.
> Sometimes you may want to use Base64-encoded data embedded here instead of separate certificate files; in that case you need to add the suffix -data to the keys, for example, certificate-authority-data, client-certificate-data, client-key-data.

**Comment by wangshiyang** [comment]
> /sig cli
> You may misunderstand the [docs](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/).
> 
> The key with the suffix `-data` can be used in kubeconfig file. It is not supported as `kubectl config set-cluster ` flags.
> 
> > Sometimes you may want to use Base64-encoded data embedded here instead of separate certificate files; in that case you need to add the suffix -data to the keys, for example, certificate-authority-data, client-certificate-data, client-key-data.

Then what should i do？

**Comment by pacoxu** [comment]
I am not sure if there is other approaches. 

You may just save the base64 to file and use the command `kubectl config set-cluster`.

Or edit the kubeconfig like.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.6.177.40:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

/cc @eddiezane
Can this be a feature request? 😄
