### ISSUE TITLE
Job controller not respect backoffLimit in case of node failure

### ISSUE THREAD

**Issue by dsaydon90** [kubernetes/kubernetes#104961]
In my case, I want to run 1 `Job` that runs 1 `Pod`. This `Pod` during his lifecycle **must not** be **recreated** and **not** be **rebooted** because my app can't start from where it stops. In another words, if the `Pod` failed for any reason such as **application** issue or **infrastructure** issue (like node failure), the `Pod` should not be recreated and the `Job` should be marked as **Failed**.

#### What happened:
I have k8s `Job` resource with the following configuration
```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  backoffLimit: 0
  parallelism: 1
  template:
    metadata:
      labels:
        app: myapp
      restartPolicy: Never
      containers:
      - image: myrepo/myapp:mytag
        imagePullPolicy: Always
        name: myapp
        ports:
        - containerPort: 8080
          name: myport
          protocol: TCP
```

#### What you expected to happen:

Currently, if the `Pod` failed  due to **application** issue, the job will be failed as expected.
But,
if the `Pod` failed  due to **infrastructure** issue (like node failure), the job controller will recreate the pod in another node although I'm using `backoffLimit: 0` with `restartPolicy: Never`.

#### How to reproduce it (as minimally and precisely as possible):
1. create k8s cluster with 2 nodes
2. create job like the above example
3. kill the node that currently host the Job's pod

#### Anything else we need to know?:

From  [Docs](https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy)
> There are situations where you want to fail a Job after some amount of retries due to a logical error in configuration etc. To do so, set .spec.backoffLimit to specify the number of retries before considering a Job as failed.

If this behavior is by design for the `Job` controller and this won't be reconsidered as a bug, so it will be great to convert this issue to a feature request.

#### Environment:
- Kubernetes version (use `kubectl version`): `v1.20.7`
- Cloud provider or hardware configuration: `aws`

/sig apps
