### ISSUE TITLE
requiredDuringSchedulingIgnoredDuringExecution evicts pod when node label changes

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubernetes#104984]
#### What happened:
Applied a damonset with affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution with a node label as required
The pods were created on the node as expected.
**After the pods reached running phase** and I even paused few minutes, I **removed the label from the node.**
**The pod was instantly terminated**

#### What you expected to happen:
Pod continues to run, as the label requirement was while scheduling and not during  runtime
If I manually delete the pod, then kubernetes will not re-create as the required labels are not there. 

#### How to reproduce it (as minimally and precisely as possible):
Apply the sample ds below with updated image path.
Have a worker node with label "test_enabled=true"
Wait till pod is deployed and reaches running phase
Now remove the "test_enabled" label from the node
Watch pod terminates
Very simple repro

Sample ds:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sonic-test-container
  labels:
    app: k8s-test-container
spec:
  selector:
    matchLabels:
      app: k8s-test-container
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: k8s-test-container
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "test_enabled"
                operator: "In"
                values:
                - "true"
              - key: "kubernetes.io/hostname"
                operator: NotIn
                values:
                - str-s6000-acs-8
      hostname: sonic
      hostNetwork: true
      containers:
      - name: sonic-test-container
        image: sonicanalytics.azurecr.io/sonic-dockers/any/docker-sonic_test_container:20210908.0129
        tty: true
        env:
        securityContext:
          privileged: true
        volumeMounts:
        - name: sonic-scripts
          mountPath: /usr/share/sonic/scripts
          readOnly: true
        imagePullPolicy: IfNotPresent
      volumes:
      - name: sonic-scripts
        hostPath:
          path: /usr/share/sonic/scripts
```
#### Environment:
- Kubernetes version (use `kubectl version`): client: 1.21.1 server: 1.21.4
- Cloud provider or hardware configuration: VM
- OS (e.g: `cat /etc/os-release`):
```
- NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
- Kernel (e.g. `uname -a`): Linux CO4AEAP000110FB 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
