### ISSUE TITLE
OnDelete for Daemonset: terminates running pod w/o waiting for pod to exit

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubernetes#105017]
#### What happened:
Kubernetes version: client: 1.21.1 server 1.21.4

I deploy a ds (_pasted below_) with updateStrategy as "OnDelete". 
I apply this ds and it started pods in two nodes as expected, say node-a & node-b
Later I added an anti-affinity as hostname notIn [ node-b ]
Applied the updated ds

This **immediately terminated the pod** running **on node-b** 

ds:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sonic-test-container
  labels:
    app: k8s-test-container
spec:
  selector:
    matchLabels:
      app: k8s-test-container
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: k8s-test-container
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "test_enabled"
                operator: "In"
                values:
                - "true"
              - key: "kubernetes.io/hostname"
                operator: NotIn
                values:
                - node-b
      hostname: sonic
      hostNetwork: true
      containers:
      - name: sonic-test-container
        image: sonicanalytics.azurecr.io/sonic-dockers/any/docker-sonic_test_container:20210908.0129
        tty: true
        env:
        securityContext:
          privileged: true
        volumeMounts:
        - name: sonic-scripts
          mountPath: /usr/share/sonic/scripts
          readOnly: true
        imagePullPolicy: IfNotPresent
      volumes:
      - name: sonic-scripts
        hostPath:
          path: /usr/share/sonic/scripts

```
#### What you expected to happen:
Pod on excluded node (node-b) **continue to run**.
Later whenever I delete the pod on the excluded node, then k8s would not re-deploy it, as anti-affinity is set for that excluded node.

#### How to reproduce it (as minimally and precisely as possible):
Very easy repro:
Update the image link in sample ds (_pasted above_) to an available image
Remove the anti-affinity setting (_kubernetes.io/hostname notIn ..._) 
Have one / more worker nodes with test_enabled=true as label
Apply deamonset
Wait for pods on all nodes with "test_enabled=true"
Now add the anti-affinity back with one of the node names, where pod is running to the ds
Apply updated ds file

**Note:** The pod on excluded-node terminating instantly.

#### Environment:
Kubernetes version (use kubectl version): client: 1.21.1 server: 1.21.4
Cloud provider or hardware configuration: VM
OS (e.g: cat /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
- kernel (e.g. uname -a):  `Linux CO4AEAP000110FB 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
