### ISSUE TITLE
 Failed to extract certificate from certificatesigningrequest

### ISSUE THREAD

**Issue by hardy4yooz** [kubernetes/kubernetes#105000]
#### What happened:
Follow the documentation [create-private-key](https://v1-21.docs.kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#create-private-key), certificate not generated as expected.

![image](https://user-images.githubusercontent.com/4044094/133239465-9172ec39-5fdf-4ebe-aac8-3388a00116e1.png)
Nothing returned.
![image](https://user-images.githubusercontent.com/4044094/133239537-aeed2cc0-6087-4b73-95c5-5cb76f04d56c.png)

#### What you expected to happen:
`kubectl get csr myuser -o jsonpath='{.status.certificate}'| base64 -d > myuser.crt`
The certificate can be found in `myuser.crt`
#### Environment:
- Kubernetes version (use `kubectl version`): v1.21.2-eks-0389ca3
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
/sig auth

I cannot reproduce it in my CentOS 8 with steps in https://v1-21.docs.kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#create-private-key.

Would you check the  csr/myuser details ?
`kubectl get csr myuser  -o yaml`

Is the status of csr/myuser missing?

**Comment by hardy4yooz** [comment]
![image](https://user-images.githubusercontent.com/4044094/133247588-153da977-6034-458d-b1d7-c724a61a2cfb.png)

**Comment by hardy4yooz** [comment]
status details are as follows,

```
status:
  conditions:
  - lastTransitionTime: "2021-09-14T10:02:18Z"
    lastUpdateTime: "2021-09-14T10:02:17Z"
    message: This CSR was approved by kubectl certificate approve.
    reason: KubectlApprove
    status: "True"
    type: Approved
```
It seens ok with old apiVerson `apiVersion: certificates.k8s.io/v1beta1`
