### ISSUE TITLE
HPA autoscaling/v2beta2 not honoring behavior

### ISSUE THREAD

**Issue by kishoreakshat** [kubernetes/kubernetes#105099]
#### What happened:

While using autoscaling/v2beta2 api, if we specify an HPA spec as follows:

```

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 20
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
```
Initially, I had kept the CPU request for my application pod to '1m'. Due to this, CPUUtilization shot up to 100% which triggered a scale up for my deployment 'podinfo'.

The scaling behavior observed was as follows:

```
Events:
  Type    Reason             Age    From                       Message
  ----    ------             ----   ----                       -------
  Normal  SuccessfulRescale  4m58s  horizontal-pod-autoscaler  New size: 3; reason: cpu resource utilization (percentage of request) above target
  Normal  SuccessfulRescale  3m57s  horizontal-pod-autoscaler  New size: 5; reason: cpu resource utilization (percentage of request) above target
  Normal  SuccessfulRescale  3m12s  horizontal-pod-autoscaler  New size: 6; reason: cpu resource utilization (percentage of request) above target
  Normal  SuccessfulRescale  2m57s  horizontal-pod-autoscaler  New size: 8; reason: cpu resource utilization (percentage of request) above target
  Normal  SuccessfulRescale  2m12s  horizontal-pod-autoscaler  New size: 10; reason: cpu resource utilization (percentage of request) above target
```

I then modified my deployment to have 200m CPU requests which reduced the CPUUtilization of this deployment to 0%. The scale down looked like this:

  ```
Normal   SuccessfulRescale             2m11s                   horizontal-pod-autoscaler  New size: 8; reason: All metrics below target
  Normal   SuccessfulRescale             101s                      horizontal-pod-autoscaler  New size: 6; reason: All metrics below target
  Normal   SuccessfulRescale             71s                        horizontal-pod-autoscaler  New size: 4; reason: All metrics below target
  Normal   SuccessfulRescale             41s                        horizontal-pod-autoscaler  New size: 3; reason: All metrics below target
  Normal   SuccessfulRescale             10s                        horizontal-pod-autoscaler  New size: 2; reason: All metrics below target

```
#### What you expected to happen:

According to [1], this should mean if there is a scale up event, either 4 new pods or 100% of existing pods should have come up, but as can be seen from the hpa description I pasted above, you can see this was not followed as-is.

Similarly, the scale down behavior was not honored as well.

#### How to reproduce it (as minimally and precisely as possible):

Explained in the expectation section above

#### Environment:
- Kubernetes version (use `kubectl version`): v1.21
- Cloud provider or hardware configuration: Amazon EKS
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

Can you please clarify if this behavior is expected to be honored as mentioned in [1] with apiversion autoscaling/v2beta2?

[1] https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior

Additionally, kubectl get hpa -o yaml yields this result:

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
```

or in some cases, this:

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
```

This is despite the fact that the yaml manifest used to create the HPA object had 'apiVersion: autoscaling/v2beta2' defined within it. Is this is expected behavior?
