### ISSUE TITLE
kubeadm upgrade can't work with customize pause image

### ISSUE THREAD

**Issue by TomatoAres** [kubernetes/kubernetes#105007]
#### What happened:

When I upgrade my k8s cluster `1.20.4->1.21.4` with customized configuration to ensure pause image doesn't upgrade,

```yaml
apiVersion: kubeadm.k8s.io/v1beta2
...
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  kubeletExtraArgs:
    ...
    pod-infra-container-image: registry.tke.com/library/pause:3.2

```

but upgrade step is failed in preflight:

`[preflight] Some fatal errors occurred: [ERROR ImagePull]: failed to pull image registry.tke.com/library/pause:3.4.1:`

I found this error occurs in this link`preflight->CheckClusterHealth->CheckClusterHealth->createJob` ，

And the job work with a  [constant--hard code version](https://github.com/kubernetes/kubernetes/blob/3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae/cmd/kubeadm/app/phases/upgrade/health.go#L140) pause image. 

And I 

#### What you expected to happen:

I expected the pause image version could be customized by configuration 

I don't want to pull a new version pause image which is not necessary.

#### How to reproduce it (as minimally and precisely as possible):

kubeadm upgrade apply kubernetes version `1.20.4->1.21.4`without `3.4.1` pause image 

#### Environment:
- Kubernetes version (use `kubectl version`): `1.20.4->1.21.4`
- OS (e.g: `cat /etc/os-release`): `centos 7.9`
- Kernel (e.g. `uname -a`): `Linux global 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm-1.21.4
