### ISSUE TITLE
npd yaml failed in centos for journal path:  /run/log/journal not /var/log/journal

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#105258]
https://github.com/helm/charts/issues/21817#issuecomment-611510731
### Root cause issue
On CentOS log path is /run/log/journal but by default use /var/log/journal
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/node-problem-detector/npd.yaml#L69-L88

/sig cloud-provider
/kind bug

### Fix
add in daemonSet

```
      volumes:
      - hostPath:
          path: /run/log/journal
          type: ""
        name: journal
```
and
```
       volumeMounts:
        - mountPath: /run/log/journal
          name: journal
```

/cc @Random-Liu @wangzhen127
