### ISSUE TITLE
UDP datagram loss after service reconfiguration

### ISSUE THREAD

**Issue by m-ildefons** [kubernetes/kubernetes#105279]
#### What happened:
Dear K8s Maintainers,

I have a problem with an application on my cluster with respect to UDP traffic.
This problem appeared with the update from v1.22.0 to v1.22.1 and persisted
after upgrade to v1.22.2.

If I create a `nodePort` service for UDP and later on reconfigure the service to be a
dual protocol UDP/TCP service on a particular port, any new pod serving that
service will have connectivity issues on UDP. To demonstrate this, I have made a
small example application.

#### What you expected to happen:

I expected all newly created pods to be able to both send and receive UDP traffic as usual.

#### How to reproduce it (as minimally and precisely as possible):
I am assuming, your K8s nodes have ips 10.10.1.13 and 10.10.1.14 and you can
use port 31337 and 41447.

1) Create a the service and the deployment using manifests `deployment.yaml` for the
deployment and `service01.yaml` for the service initially.
```
kubectl apply -f service01.yaml
kubectl apply -f deployment.yaml
```

2) Confirm that the UDP connectivity works ok by starting the peer with `uping.py` on the
node with IP 10.10.1.13.
```
python3 uping.py 41447 10.10.1.14 31337
```
You should see that both the deployment as well as the peer log both `ping` and
`pong` messages, e.g.:
```
kubectl logs -f -l app=udp-debug --all-containers

[...]
received b'ping' from ('10.10.1.14', 19689)
received b'pong' from ('10.10.1.13', 41447)
received b'ping' from ('10.10.1.14', 19689)
received b'pong' from ('10.10.1.13', 41447)
received b'ping' from ('10.10.1.14', 19689)
received b'pong' from ('10.10.1.13', 41447)
received b'ping' from ('10.10.1.14', 19689)
received b'pong' from ('10.10.1.13', 41447)
[...]
```

3) Reconfigure the service with manifest `service02.yaml`
```
kubectl apply -f service02.yaml
```
This should not (yet) break things.

4) Force a pod restart and wait for the old pod to terminate.
```
kubectl delete pod udp-debug-xxxxxxx-xxx
```

Now you should see that both the pod and the peer are no longer logging `ping`s
and `pong`s. The pod is still receiving `pong`s and the peer is receiving
`ping`s but the pings from the peer to the pod seem to get lost, e.g.:
```
[...]
received b'pong' from ('10.10.1.13', 41447)
received b'pong' from ('10.10.1.13', 41447)
received b'pong' from ('10.10.1.13', 41447)
received b'pong' from ('10.10.1.13', 41447)
[...]
```

As far as I could figure out, this problem appears only when reconfiguring the
service with `kubectl apply` and not when reconfiguring the service with
`kubectl recreate`.

---

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `Selfhosted`
- OS (e.g: `cat /etc/os-release`): `CentOS 7.2009`
- Kernel (e.g. `uname -a`): `Linux server01 5.4.149-1.el7.elrepo.x86_64 #1 SMP Sat Sep 25 10:02:34 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `kubeadm`
- Network plugin and version (if this is a network-related bug): `Calico version: v3.20.0`
- Others:
```
NAME       STATUS   ROLES                  AGE      VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
server01   Ready    control-plane,master   2y47d    v1.22.1   10.10.1.13    <none>        CentOS Linux 7 (Core)   5.4.142-1.el7.elrepo.x86_64   containerd://1.4.9
server04   Ready    control-plane,master   2y53d    v1.22.1   10.10.1.14    <none>        CentOS Linux 7 (Core)   5.4.142-1.el7.elrepo.x86_64   containerd://1.4.9
```
---
uping.py:
```python
#!/usr/bin/env python3

import socket
import sys
import threading
import time


ADDR = ''
PORT = 41447
DEST = '127.0.0.1'
DEST_PORT = 31337

def init():
    global SOCK
    SOCK = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    SOCK.bind((ADDR, PORT))
    SOCK.settimeout(3)


def do_pong():
    global SOCK

    while True:
        try:
            msg, adr = SOCK.recvfrom(2048)
            print("received {} from {}".format(msg, adr))
            if msg == b'ping':
                SOCK.sendto(b'pong', adr)
            else:
                time.sleep(1)
        except socket.timeout as t:
            print("no answere received {}".format(t))
        except KeyboardInterrupt:
            break


def do_ping():
    global DEST
    global DEST_PORT
    global SOCK

    while True:
        try:
            SOCK.sendto(b'ping', (DEST, DEST_PORT))
            time.sleep(1)
        except KeyboardInterrupt:
            break


if __name__ == "__main__":
    PORT = int(sys.argv[1])
    DEST = sys.argv[2]
    DEST_PORT = int(sys.argv[3])
    init()
    ping_t = threading.Thread(target=do_ping)
    pong_t = threading.Thread(target=do_pong)

    ping_t.start()
    pong_t.start()

    ping_t.join()
    pong_t.join()
```
deployment.yaml:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udp-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-debug
  template:
    metadata:
      labels:
        app: udp-debug
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - udp-debug
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: debug
          image: python:3.9.7-slim-buster
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: LISTENPORT
              value: "31337"
            - name: PEER
              value: "10.10.1.13"
            - name: PEERPORT
              value: "41447"
          ports:
            - containerPort: 31337
          command:
            - /bin/bash
            - -exc
            - |
              cat <<EOF > /uping.py
              #!/usr/bin/env python3

              import socket
              import sys
              import threading
              import time


              ADDR = ''
              PORT = 41447
              DEST = '127.0.0.1'
              DEST_PORT = 31337

              def init():
                  global SOCK
                  SOCK = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                  SOCK.bind((ADDR, PORT))
                  SOCK.settimeout(3)


              def do_pong():
                  global SOCK

                  while True:
                      try:
                          msg, adr = SOCK.recvfrom(2048)
                          print("received {} from {}".format(msg, adr))
                          if msg == b'ping':
                              SOCK.sendto(b'pong', adr)
                          else:
                              time.sleep(1)
                      except socket.timeout as t:
                          print("no answere received {}".format(t))
                      except KeyboardInterrupt:
                          break


              def do_ping():
                  global DEST
                  global DEST_PORT
                  global SOCK

                  while True:
                      try:
                          SOCK.sendto(b'ping', (DEST, DEST_PORT))
                          time.sleep(1)
                      except KeyboardInterrupt:
                          break


              if __name__ == "__main__":
                  PORT = int(sys.argv[1])
                  DEST = sys.argv[2]
                  DEST_PORT = int(sys.argv[3])
                  init()
                  ping_t = threading.Thread(target=do_ping)
                  pong_t = threading.Thread(target=do_pong)

                  ping_t.start()
                  pong_t.start()
                  
                  ping_t.join()
                  pong_t.join()
              EOF

              chmod +x /uping.py
              /uping.py "$LISTENPORT" "$PEER" "$PEERPORT"
```
service01.yaml:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: udp-debug
spec:
  type: NodePort
  selector:
    app: udp-debug
  ports:
    - name: udp-debug
      protocol: UDP
      port: 31337
      nodePort: 31337
```
service02.yaml:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: udp-debug
spec:
  type: NodePort
  selector:
    app: udp-debug
  ports:
    - name: tcp-debug
      protocol: TCP
      port: 31337
      nodePort: 31337
    - name: udp-debug
      protocol: UDP
      port: 31337
      nodePort: 31337
```
