### ISSUE TITLE
Recreating CRD with changed scope leads to error "could not find the requested resource"

### ISSUE THREAD

**Issue by mseiwald** [kubernetes/kubernetes#105394]
#### What happened:

Changing the scope field of a CRD ist not possible since it's immutable. But even after deleting and re-creating the CRD with changed scope it doesn't let me create resources of the CRD's kind.

#### What you expected to happen:

Re-creating CRD with changed scope should just work.

#### How to reproduce it (as minimally and precisely as possible):

Here is a full example that in the end leads to the error `Error from server (NotFound): error when creating "STDIN": the server could not find the requested resource (post examples.test.com)` when trying to create a resource after re-creating the CRD.

```
kubectl apply -f - << EOF
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.test.com
spec:
  group: test.com
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                test:
                  type: string
  names:
    plural: examples
    singular: example
    kind: Example
EOF

kubectl apply -f - << EOF
apiVersion: test.com/v1
kind: Example
metadata:
  name: test
spec:
  test: test
EOF

kubectl delete crd examples.test.com

kubectl apply -f - << EOF
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.test.com
spec:
  group: test.com
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                test:
                  type: string
  names:
    plural: examples
    singular: example
    kind: Example
EOF

kubectl apply -f - << EOF
apiVersion: test.com/v1
kind: Example
metadata:
  name: test
spec:
  test: test
EOF
```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.21.4
- Cloud provider or hardware configuration: vSphere 7.0
- OS (e.g: `cat /etc/os-release`): Centos 7
- Kernel (e.g. `uname -a`): 3.10.0-1160.42.2.el7.x86_64
