### ISSUE TITLE
fsGroupChangePolicy: "OnRootMismatch" does not skip permission changes for ceph-csi rbd volume because of missing setgid bit on root directory

### ISSUE THREAD

**Issue by abckey** [kubernetes/kubernetes#105435]
#### What happened:
In my POD, I have following settings:

```
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  volumes:
  - name: normal-ceph
    persistentVolumeClaim:
      claimName: kai-ceph-normal-pvc
      readOnly: false
```
The POD has a PVC from a ceph-csi rbd PV attached, which has several millons of files and directories, that slows down the POD startup because of recursive permission changes for the volume. I expect `OnRootMismatch` could skip the recursive permission change since root directory of the volume already has right group owner and permissions, but it does not work, always I got log:

```
10.183.248.10: I1003 13:46:04.655155    7924 volume_linux.go:183] performing recursive ownership change on /var/lib/kubelet/pods/260ed8d0-1c2b-486f-ab27-cd592d989c98/volumes/kubernetes.io~csi/pvc-36321f60-68da-44cb-bdb8-d06cf9d5f449/mount because of mismatching mode
```

Looking at code, I suppose it failed at: 
https://github.com/kubernetes/kubernetes/blob/8a62859e515889f07e3e3be6a1080413f17cf2c3/pkg/volume/volume_linux.go#L182

Because the root diretory upon attachement, has no setgid bit set:

```
root@worker:/# ls -l /var/lib/kubelet/pods/ac1c638a-2eeb-4ff3-8367-f859b6293a79/volumes/kubernetes.io~csi/pvc-36321f60-68da-44cb-bdb8-d06cf9d5f449/
total 8
drwxrwxrwx 24 root 1000 4096 Oct  3 15:45 mount
```

I wonder in this case, who should set setgid bit ?

#### What you expected to happen:
`OnRootMismatch` should skip the recursive permission change if root directory of the volume has already right group owner and permissions.

#### How to reproduce it (as minimally and precisely as possible):
example manifests for my test pod, pvc, and storageclass

```storageclass.yaml```
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-csi
provisioner: rbd.csi.ceph.com
parameters:
   clusterID: xxyyzzaasdsd
   pool: devtest
   imageFeatures: layering
   csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
   csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi
   csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
   csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi
   csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
   csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi
   csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
   - discard
```

```pvc.yaml```
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kai-ceph-normal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-csi
```

```testpod.yaml```
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  terminationGracePeriodSeconds: 1
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
  containers:
  - name: web-server
    image: nginx
    volumeMounts:
    - name: normal-ceph
      mountPath: /normalceph
  volumes:
  - name: normal-ceph
    persistentVolumeClaim:
      claimName: kai-ceph-normal-pvc
      readOnly: false
```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.6
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): Talos (v0.10.3)
- Kernel (e.g. `uname -a`): 5.10.29-talos
- ceph-csi-rbd version: v3.3.1
