### ISSUE TITLE
Unable to start systemd based containers

### ISSUE THREAD

**Issue by psaini79** [kubernetes/kubernetes#105463]
#### We are trying to create a systemd based POD and it is throwing the following error:
```
 Warning  Failed     64s                  kubelet            Error: container create failed: time="2021-10-04T17:43:07Z" level=error msg="container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting \"/sys/fs/cgroup/systemd\" to rootfs at \"/sys/fs/cgroup/systemd\" caused: mkdir /var/lib/containers/storage/overlay/a758e3eb68c6dddcd02bfd4b1b3886b924f654c6926c55639f3d95b835e7e348/merged/sys/fs/cgroup/systemd: no such file or directory"
```

##### Create the bracnode.yaml using following contents:
```
kind: Pod
apiVersion: v1
metadata:
  name: bracnode1
  labels:
    name: bracnode1
spec:
  hostname: bracnode1
  volumes:
    - name: cgroup1
      hostPath:
       path: /sys/fs/cgroup
    - name: myshm
      emptyDir:
       medium: Memory
    - name: myrun
      emptyDir:
       medium: Memory
  containers:
    - name: bracnode1
      image: oraclelinux:8
      imagePullPolicy: Always
      securityContext:
       privileged: false
      command: [/usr/sbin/init]
      volumeMounts:
      - mountPath: "/sys/fs/cgroup"
        name: cgroup1
        readOnly: true
      - mountPath: "/dev/shm"
        name: myshm
      - mountPath: "/run"
        name: myrun
```

##### Apply the file
```
kubectl apply -f bracnode1.yaml
```

#### Pod creation will fail and you will see the following error
```
kubectl describe pod/bracnode1
```
#### Environment:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+2.el8", GitCommit:"b3b8bb36c6380a10f18aa1cdcb8d68399a8157f2", GitTreeState:"clean", BuildDate:"2021-07-21T04:09:24Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
- Cloud provider or hardware configuration: Oracle OCI cloud IaaS machines and installed 1.20 Kubernetes on OCI IaaS machines.
- OS (e.g: `cat /etc/os-release`):
```
cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.4"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:4:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.4
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.4
```
- Kernel (e.g. `uname -a`):
```
uname -a
Linux olcne-master-1-ol8 5.4.17-2102.203.6.el8uek.x86_64 #2 SMP Wed Jul 21 17:45:32 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
