### ISSUE TITLE
HPA behaviour is inconsistent at different averageUtilization metrics

### ISSUE THREAD

**Issue by argais** [kubernetes/kubernetes#105579]
### What happened?

I have a workload that I need to scale on CPU utilization, pretty standard, but I need it to scale all the way to 24 pods, then once the CPU avg lowers to slowly scale down to 1 by removing 25% of the pods every 5m.

I have the following manifest.

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app
  namespace: myns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  minReplicas: 1
  maxReplicas: 24

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 24
        periodSeconds: 15
      selectPolicy: Max
```

So I launch my deployment and the cpu utilization hits 100% quickly, the condition is met, but the HPA launches 1 extra pod, then around 45s later another 2, then 4, then 8 until it gets to 24.

Scale down, once all data is consumed and cpu avg goes rock bottom, works as described in the scaledown behaviour.

Now the thing is... if I set the cpu averageUtilization to 1, it scales all the way to 24 right away, like I wanted, but never when the averageUtilization is set to 50.

### What did you expect to happen?

The described scaleUp behaviour in the manifest to be followed by the HPA

### How can we reproduce it (as minimally and precisely as possible)?

Launch the HPA from the manifest I provided, HPA scales the deployment by doubling the pod count.
Change the manifest to have averageUtilization of 1% and try again, HPA will now honor the behaviour in the manifest.

### Kubernetes version

<details>

```console
➜ k version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
