### ISSUE TITLE
The number of pods goes down with ScaleDown: SelectPolicy: Disabled of HPA. 

### ISSUE THREAD

**Issue by sunhan-code** [kubernetes/kubernetes#105655]
### What happened?

Hi Kubernetes, 

I'm managing my service pods using HPA, and as the Title implies I have set SelectPolicy of ScaleDown to "Disabled" not to lose any pods. 

So basically it's just growing up to .spec.maxReplicas as specific resource metrics I set grow. 

However, I realized that HPA recalculates the desired when there was API Server not responding or pod rescheduling by events like OOM. The problem is when this happened HPA set the desired to a smaller one than it had before.  As a result, I end up losing some pods. 

Here is the HPA configurations.

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: myservice-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: myservice
  minReplicas: 1
  maxReplicas: 20
  behavior:
    scaleDown:
      selectPolicy: Disabled
    scaleUp:
      stabilizationWindowSeconds: 3600
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
```

### What did you expect to happen?

The number of pods never goes down. 

### How can we reproduce it (as minimally and precisely as possible)?

I'm not sure how it can be reproduced. But when  the target pods crashes, pod recreations caused by nod rescheduling, and API Server acting up seem to affect HPA. The following image is an example I experienced. 

![2021-09-27_21-13-44](https://user-images.githubusercontent.com/9150735/137166883-fbd0df44-9583-48f8-a65e-9f08810739c1.png)

### Kubernetes version

<details>

```console
> kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
