### ISSUE TITLE
Wrong “exp” date in projected serviceaccount token

### ISSUE THREAD

**Issue by ncsibra** [kubernetes/kubernetes#105654]
### What happened?

I'm using AWS EKS 1.21 with service account discovery enabled (it's enabled by default by EKS, I can't change it).
The `.well-known/openid-configuration` endpoint returns:

```
{
  "issuer": "https://oidc.eks.eu-west-1.amazonaws.com/id/***",
  "jwks_uri": "https://ip-***.eu-west-1.compute.internal:443/openid/v1/jwks",
  "response_types_supported": [
    "id_token"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ]
}
```

Created a ServiceAccount for one of my deployments and the pod gets this as projected volume.
```
  volumes:
  - name: kube-api-access-b4xt9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```
The projected token mounted into the pod contains this:
```
{
  "aud": [
    "https://kubernetes.default.svc"
  ],
  "exp": 1664448004,
  "iat": 1632912004,
  "iss": "https://oidc.eks.eu-west-1.amazonaws.com/id/***",
  "kubernetes.io": {
    "namespace": "sbx",
    "pod": {
      "name": "dliver-site-config-service-77494b8fdd-45pxw",
      "uid": "0dd440a6-1213-4faa-a69e-398b83d2dd6b"
    },
    "serviceaccount": {
      "name": "dliver-site-config-service",
      "uid": "c26ad760-9067-4d90-a327-b3d6e32bce42"
    },
    "warnafter": 1632915611
  },
  "nbf": 1632912004,
  "sub": "system:serviceaccount:sbx:dliver-site-config-service"
}
```

Kubernetes renew the projected token every hour, so everything looks fine.
Except the projected token "exp" field:
`"iat": 1632912004` which is `Wednesday, September 29, 2021 10:40:04 AM`
`"exp": 1664448004` which is `Thursday, September 29, 2022 10:40:04 AM`

So the problem is, that the projected token expiry time is 1 year, instead of around 1 hour.

If I set `automountServiceAccountToken: false` and configuring the volume manually to the same as above, the token `exp` will be the same, 1 year.
But when I change `expirationSeconds` to another value, e.g.: 3606, 3608, 3600, 3700, etc, then the token `exp` will be correct, based on the `expirationSeconds`, so it will be around 1 hour later than `iat`.

Looks likes something magical happens, when the value is the default `3607`, but I can't find any related information or issue.
Any idea why is this happening?

### What did you expect to happen?

A correct `exp` value in the projected token, based on the `expirationSeconds`.

### How can we reproduce it (as minimally and precisely as possible)?

Create an EKS cluster with 1.21 version, it should have an OIDC provider by default.
Create a ServiceAccount and use it for a pod, without manually mounting the token, that should be enough.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
EKS 1.21, Platform version: eks.2
</details>

### OS version

<details>

AMI:  amazon-eks-node-1.21-v20211004 (ID: ami-0c073420a05707690)

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
$ uname -a
Linux ip-10-152-17-3.eu-west-1.compute.internal 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
Pulumi
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerRuntimeVersion: containerd://1.4.6
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
