### ISSUE TITLE
dfadfsdf

### ISSUE THREAD

**Issue by abnormall** [kubernetes/kubernetes#105708]
**What happened**:
In one cluster, sender service is deployed. In another cluster, receiver service is deployed. The receiver  service is exposed by LoadBalancer.  The external ip:port is 52.191.20.176:50002.  When surfing the 52.191.20.176:50002 on the website, the receiver service will return "hello world".

In the  pod of sender service,  curling 52.191.20.176:50002 will return connection time out.

**What you expected to happen**:

In the  pod of sender service,  curling 52.191.20.176:50002 should return "hello world".

**How to reproduce it (as minimally and precisely as possible)**:

sender.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
  labels: 
    app: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "sender"
        dapr.io/app-port: "4001"
    spec:
      containers:
        - name: sender
          image: simpllly/bjli-docker-hub:20210906
          ports:
            - name: http
              containerPort: 4001

---
kind: Service
apiVersion: v1
metadata:
  name: sender
  labels:
    app: sender
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 100
    protocol: TCP
    targetPort: 4001
  sessionAffinity: None
  selector:
    app: sender
```

receiver.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  labels: 
    app: receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "receiver"
        dapr.io/app-port: "4001"
    spec:
      containers:
        - name: receiver
          image: simpllly/bjli-docker-hub:20210906
          ports:
            - name: http
              containerPort: 4001

---
kind: Service
apiVersion: v1
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 100
    protocol: TCP
    targetPort: 4001
  sessionAffinity: None
  selector:
    app: receiver






```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): AKS v1.2
- Size of cluster (how many worker nodes are in the cluster?)  
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:
