### ISSUE TITLE
Enhancement request for allowing hostnames in endpoints. Currently only IPs are supported

### ISSUE THREAD

**Issue by Eugenevml** [kubernetes/kubernetes#105733]
### What happened?

I'm working on a task requiring to implement a solution that would allow for horizontal pod autoscaling of a certain service to scale pods based on kafka metric "kafka_consumer_group_ConsumerLagMetrics_Value"

HPA would look something similar to this within that service: 

```
consumer-hpa.yaml
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: consumer-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-consumer-application
  minReplicas: 1
  maxReplicas: 10
  metrics:
   - type: Pods
      pods:
        metricName: "kafka_consumer_group_ConsumerLagMetrics_Value"
        targetAverageValue: 5
```
Kafka in this case is a MSK cluster in AWS. Service is running in k8s cluster also in AWS. And I'm using Prometheus operator that is running in k8s in the same cluster as my service to pick up metrics coming from MSK. MSK has Prometheus metrics enabled and port 11001 opened in the security groups for that msk cluster. Additional prometheus service monitor is deployed and discovered by prometheus operator: 

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: service-monitor
    app.kubernetes.io/part-of: prometheus
  name: prometheus-msk-metrics
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    interval: 15s
    port: web
    honorLabels: true
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - msk
  selector:
    matchLabels:
      app: msk-app
```
      
  Here's msk service deployed in k8s in a separate msk namespace: 
  
```
`apiVersion: v1
kind: Service
metadata:
  labels:
    app: msk-app
  name: msk-service
  namespace: msk
spec:
  externalName: b-3.env-dev-us-east-2-msk.12345.c4.kafka.us-east-1.amazonaws.com
  ports:
  - name: web
    port: 11001
  selector:
    app: msk-app
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}`
```
  
Note: external name modified out of security reasons. But the one I'm using in my implementation is totally valid. 

When creating this service in k8s it is not getting discovered by the Prometheus operator. The endpoint doesn't contain the IP of the external service (MSK). 

Therefore, endpoint created along with this service needs to be updated with the IP of the MSK instance like so:

```
`apiVersion: v1
kind: Endpoints
metadata:
  name: msk-service
  labels:
    app: msk-app
subsets:
- addresses:
  - ip: 10.2.3.45
  ports:
  - name: web
    protocol: TCP
    port: 11001`
```
    
Note: IP is just an example   
 
This setup works. However, for this whole thing to work properly and stably for any foreseeable time this solution is not ideal. The IP of the MSK instance may change and kafka metric based HPA will stop working because metrics would no longer be available in prometheus due to IP change. 

It would be awesome if Endpoints could take hostname of the external service to avoid any issues with changes of the IP:
```
 `
 ***
subsets:
- addresses:
  - **hostname**: external_service
  ***`
```
  
  I could think of a few more business cases where this would be perfectly justifiable and useful to have, like for instance allowing to work with RDS instances without having to worry about changing IPs all the time and then debugging broken k8s services due to IP change, creating PRs to update hardcoded IPs etc. This could potentially make lives much easier. 

### What did you expect to happen?

Would be awesome if endpoints allowed support of hostnames as an alternative to IPs.

### How can we reproduce it (as minimally and precisely as possible)?

Please see description for guidelines on how to recreate similar setup. 

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
