### ISSUE TITLE
Fail to reach another cluster by external ip:port

### ISSUE THREAD

**Issue by abnormall** [kubernetes/kubernetes#105709]
### What happened?

In one cluster, sender service is deployed. In another cluster, receiver service is deployed. The receiver service is exposed by LoadBalancer. The external ip:port is 52.191.20.176:50002. When surfing the 52.191.20.176:50002 on the website, the receiver service will return "hello world".

In the pod of sender service, curling 52.191.20.176:50002 will return connection time out.

### What did you expect to happen?

In the pod of sender service, curling 52.191.20.176:50002 should return "hello world".

### How can we reproduce it (as minimally and precisely as possible)?

sender.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
  labels: 
    app: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "sender"
        dapr.io/app-port: "4001"
    spec:
      containers:
        - name: sender
          image: simpllly/bjli-docker-hub:20210906
          ports:
            - name: http
              containerPort: 4001

---
kind: Service
apiVersion: v1
metadata:
  name: sender
  labels:
    app: sender
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 100
    protocol: TCP
    targetPort: 4001
  sessionAffinity: None
  selector:
    app: sender
```

receiver.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  labels: 
    app: receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "receiver"
        dapr.io/app-port: "4001"
    spec:
      containers:
        - name: receiver
          image: simpllly/bjli-docker-hub:20210906
          ports:
            - name: http
              containerPort: 4001

---
kind: Service
apiVersion: v1
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 100
    protocol: TCP
    targetPort: 4001
  sessionAffinity: None
  selector:
    app: receiver






```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
V 1.2
</details>

### Cloud provider

<details>
AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
