### ISSUE TITLE
Switching from numeric port to named port in service causes unexpected behavior in requests

### ISSUE THREAD

**Issue by Ethan-99** [kubernetes/kubernetes#105799]
### What happened?

Altering the kubernetes service targetPort from a numbered port to a named port that is referenced in the deployment causes the following error. Essentially, it is saying that my arbitrary container port (8054) is an HTTP port and it cannot service HTTPS traffic on it. It does not throw this error when using a numeric targetPort.

When using numeric targetPort in service (curl(60) expected):
```
$ curl https://<app name>.<namespace>:443/service-readiness
curl: (60) SSL certificate problem: self signed certificate
```

When using named ports:
```
$ curl https://<app name>.<namespace>:443/service-readiness
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

I also want to note that I made the same change for other apps as well (on different ports), but this is the only app that experienced this issue. It leads me to believe that there may be some different way kubernetes treats 8000 ports.

Original (which works without error):
```
# deployment.yaml
...
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /service-liveness
    port: 8054
    scheme: HTTPS

# service.yaml
...
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8054
```

New config (does not allow https traffic to 8054)
```
# deployment.yaml
...
# added ports section
ports:
- name: https
  containerPort: 8054
  protocol: TCP
...
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /service-liveness
    port: https                     # changed
    scheme: HTTPS

# service.yaml
...
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: https            # changed
```

### What did you expect to happen?

Nothing should have been changed when changing to a named port.

```
$ curl https://<app name>.<namespace>:443/service-readiness
curl: (60) SSL certificate problem: self signed certificate
```

### How can we reproduce it (as minimally and precisely as possible)?

See first section above.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
