### ISSUE TITLE
Extended SA token expiration

### ISSUE THREAD

**Issue by jyotimahapatra** [kubernetes/kubernetes#105801]
### What happened?

Kubernetes has promoted Bound Service Account Tokens to beta starting in 1.21.
Bound Service Account Tokens have a backward compatibility feature to allow extended expiration of tokens. However the extended expiration gets applied anytime the extended expiration is enabled and expiration seconds is `3607` https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/serviceaccount/storage/token.go#L132-L134 . 

This causes projected volume tokens to also be impacted. If a projected token was created with explicit 3607s expiry, they will have 1 year expiry irrespective of the audience.

### What did you expect to happen?

Bound service account token expiry should apply only when the audience is kube-apiserver

Projected volume tokens should not have 1 yr expiry when expiration seconds is `3607`s

### How can we reproduce it (as minimally and precisely as possible)?

Create a nginx pod with 3607s. 
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx3
  name: nginx3
spec:
  serviceAccountName: test3
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 3607
          audience: vault
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token

  dnsPolicy: ClusterFirst
  restartPolicy: Always
```

Inpect the `exp` field on the projected token on the pod 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

Verified this behavior on 1.19.15, 1.20.11 and 1.21.2

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
