### ISSUE TITLE
Incorrect status of kubernetes deployment after updating deployment few times

### ISSUE THREAD

**Issue by pagarwal-tibco** [kubernetes/kubernetes#105842]
### What happened?

When we try to update deployment resource many times where it fails intermittently, status would show incorrect information. Please check steps below for more information.

### What did you expect to happen?

In case of failure, deployment status should show correct information. Please check steps below for more information.

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: echo
  name: echo
  namespace: default
spec:
  progressDeadlineSeconds: 180
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: mendhak/http-https-echo
          imagePullPolicy: IfNotPresent
          name: echo
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      terminationGracePeriodSeconds: 10
```

**Steps:**
1. Deploy above kubernetes deployment resource
2. Change the image name to 'mendhak/http-https-echo1' and update the deployment. This should result in status of deployment as 'ProgressDeadlineExceeded'
3. Now again correct the image name as 'mendhak/http-https-echo' and update the deployment. Now deployment status will indicate success
4. Now again change the image name as 'mendhak/http-https-echo1' and update the deployment. Now deployment status will still incorrectly indicate success.
5. If issue could not be reproduced then repeat steps 2-4

At step #4, deployment status will be incorrect as follows,
`message: ReplicaSet "echo-547fb74949" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing`

Here reason should have been 'ProgressDeadlineExceeded' and message should contain correct replica-set name. "echo-547fb74949" replica-set has old revision than the one indicated by 'deployment.kubernetes.io/revision' deployment annotation.

### Kubernetes version

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-27T23:27:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

EKS and KinD
