### ISSUE TITLE
kubectl debug node cannot access root of non-root user process

### ISSUE THREAD

**Issue by lizzzcai** [kubernetes/kubernetes#105846]
### What happened?

For a container running as a NonRoot user, debug pod created by `kubectl debug node` cannot access the root of the process. User case [here](https://github.com/kubernetes/enhancements/issues/277#issuecomment-949320689)

### What did you expect to happen?

Privileged debug pod on the node should be able to access almost all the information of the pod running on that node.

### How can we reproduce it (as minimally and precisely as possible)?

below is the example pod.
```
# demo.yaml

apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  automountServiceAccountToken: false
  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: root-container
    image: nginx
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    args: ["sleep", "1d"]

  - name: user-container
    image: debian
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    args: ["sleep", "1d"]

```

below are the steps. above pod running on the node called `demo`. Get `Permission denied` when trying to access the root of the target process.

```
kubectl apply demo.yaml

kubectl debug node/demo -it --image=quay.io/libpod/ubuntu

root@demo:/# chroot host

# id
uid=0(root) gid=0(root) groups=0(root)

# docker ps | grep two-containers
184d03e4d858   debian                  "sleep 1d"               3 minutes ago        Up 3 minutes                  k8s_user-container_two-containers_default_28ff656c-5d8e-4b2b-b89b-b1977846a85a_0
e8045dfcfc4f   nginx                   "/docker-entrypoint.…"   4 minutes ago        Up 4 minutes                  k8s_root-container_two-containers_default_28ff656c-5d8e-4b2b-b89b-b1977846a85a_0
380153d0bada   k8s.gcr.io/pause:3.6    "/pause"                 4 minutes ago        Up 4 minutes                  k8s_POD_two-containers_default_28ff656c-5d8e-4b2b-b89b-b1977846a85a_0

## for user container

# docker top 184d03e4d858
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
1337                12513               12492               0                   10:21               ?                   00:00:00            sleep 1d

# cd /proc/12513/root
/bin/sh: 5: cd: can't cd to /proc/12513/root
# chroot /proc/12513/root
chroot: cannot change root directory to '/proc/12513/root': Permission denied
```

### Anything else we need to know?

If I add on below securityContext to the debug node, then I can access the root of the target process.

```
    securityContext:
      privileged: true
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.3", GitCommit:"90051602459ca81bcdfd91ff3d12ca5bde50a7a7", GitTreeState:"clean", BuildDate:"2021-09-28T12:27:26Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
minikube
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Darwin C02F51RLMD6R 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
minikube, kubernetes version: v1.23.0-aplha.3
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:31 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
