### ISSUE TITLE
Allowing mutating webhook to change pod spec for mirror pods is confusing. Consider making it clearer

### ISSUE THREAD

**Issue by b10s** [kubernetes/kubernetes#105844]
### What happened?

Limits applied by LimitRanger to a static Pod are not in effect.

### What did you expect to happen?

Either do apply limits or to not show them in yaml/API and document such behavior (if not yet :smiley:)
First is preferable per my opinion.

### How can we reproduce it (as minimally and precisely as possible)?

1. Make sure you have a LimitRanger with enforced limits.
2. Create a static Pod without limits:
```
apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: test
spec:
  containers:
  - image: nginx:latest
    name: test
    resources:
      request:
        cpu: 0.1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  ```
  3. Ensure limits are in Pod's yaml by getting it from API via kubectl:
  ```
      resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 256Mi
```

4. Ensure limits are not propagated to docker/cgroups:
```
# docker inspect b8648733a385 -f "{{.HostConfig.Memory}}"
0
```
and
```
# cat /sys/fs/cgroup/memory//kubepods/besteffort/podc5b07aadd2def35b173d5247ac61e619/b8648733a38542484091ed7ee5f123bf9b51d34f5595fa74ca4c8248000c6f92/memory.limit_in_bytes 
9223372036854771712
```

### Anything else we need to know?

If it's a bug and we want to fix it, I would like to try to work on in with support of someone from upstream : )

### Kubernetes version

<details>

```console
$ kubectl version
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.12", GitCommit:"2cb4598553d0a2ca5f3eb7980c99cd8236cc5011", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:44Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
on premise
</details>
