### ISSUE TITLE
ExternalName Services should not autogenerate endpoints based on selectors

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#105986]
Ref: https://github.com/kubernetes/kubernetes/issues/105733#issuecomment-946863322

> The IP of the endpoint is autogenerated by matching the pods used by the label selector, however,  I don't know if we should autogenerate endpoints for services with type `ExternalName` cc: @thockin @robscott 

To reproduce it, just apply the following manifest https://gist.github.com/aojea/a7744cd5d664e1516bf5d6b05f1787c8
to create a pod and a Service Type Externalname with a selector matching hte pod
```yaml
apiVersion: v1
kind: Service
metadata:
  name: mydomainfortest
  namespace: default
spec:
  externalName: www.google.com
  type: ExternalName
  selector:
    app: myapp
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    app: myapp
spec:
  containers:
    - name: web
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
```

```bash
$kubectl apply -f https://gist.githubusercontent.com/aojea/a7744cd5d664e1516bf5d6b05f1787c8/raw/d9a1c99f78b2ab39987231ab590ea2adca580452/external_name_selector.yaml
service/mydomainfortest created
pod/testpod created

$ kubectl get pods
NAME      READY   STATUS    RESTARTS   AGE
testpod   1/1     Running   0          26s

$ kubectl get service
NAME              TYPE           CLUSTER-IP   EXTERNAL-IP      PORT(S)   AGE
kubernetes        ClusterIP      10.96.0.1    <none>           443/TCP   99s
mydomainfortest   ExternalName   <none>       www.google.com   <none>    30s

$ kubectl get endpoints
NAME              ENDPOINTS         AGE
kubernetes        172.18.0.2:6443   104s
mydomainfortest   <none>            35s  <----------------

$ kubectl get endpointslices
NAME                    ADDRESSTYPE   PORTS     ENDPOINTS    AGE
kubernetes              IPv4          6443      172.18.0.2   4m56s
mydomainfortest-gzfnp   IPv6          <unset>   <unset>      3m47s
mydomainfortest-llds5   IPv4          <unset>   10.244.0.5   3m47s

```

**Comment by khenidak** [comment]
We shouldn't. External name is just a DNS entry. Thanks for this.

**Comment by khenidak** [comment]
@robscott (yo @thockin )

i don't think this should be a code change in endpoint slice/nor endpoint controller. We should delete them endpoints /slices in service stack its efficient, simpler and probably way less code this way.

**Comment by aojea** [comment]
> i don't think this should be a code change in endpoint slice/nor endpoint controller. We should delete them endpoints /slices in service stack its efficient, simpler and probably way less code this way.

should not be caught in validation?

**Comment by thockin** [comment]
We identified (some of) these mutual-use problems a while ago.  The problem is that changing the API to reject such inputs would be a breaking change.  Now, we can argue "it doesn't work anyway" but I'll bet 100 bucks that somewhere out there is a cluster that has Services in this state.  We could, maybe, go through a process of warning and then disallowing it on NEW Services, but we have to allow it on existing services.  That's a lot of work, but I could see exploring it.  Note that we can't simply wipe those fields on input, or else clients can go into an apply-loop.

We should fix the controllers to ignore ExternalName more completely, so we don't end up with endpoints when we don't want them - that's totally reasonable and I don't think that is a breaking change.

As to whether to do it in Service REST or in controllers... we have some such linkages today.  It makes the code slightly uglier and more convoluted (and tests).  I'd love to explore moving it all to the controllers, but that requires us to clearly define the intersection of the fields.

**Comment by khenidak** [comment]
I have been looking at the throwing warning using api-machinery. I think it is a good idea.

There are two cases here:
1. Service that had selector and thus endpoints that service then changes type to `ExternalName` (we need to delete those endpoints). I don't think controller can handle that logic consistently. Not sure at least.
2. Service that is already an `ExternalName`. If users set endpoints to them then the controller should just ignore them.

**Comment by aojea** [comment]
> * Service that had selector and thus endpoints that service then changes type to `ExternalName` (we need to delete those endpoints). I don't think controller can handle that logic consistently. Not sure at least.

only in endpointslice controller, endpoints controller doesn't handle updates
it should be something similar to https://github.com/kubernetes/kubernetes/pull/105997

> * Service that is already an `ExternalName`. If users set endpoints to them then the controller should just ignore them.

this is the simplest one 

https://github.com/kubernetes/kubernetes/blob/c9baa14d708415225ed030e520970b3e1b6e4349/pkg/controller/endpoint/endpoints_controller.go#L407-L411

**Comment by panslava** [comment]
More findings

1. ExternalName without selector will not generate endpoints
2. ExternalName with selector will generate <none> endpoint
```
NAME                      ENDPOINTS         AGE
echoserver-externalname   <none>            3s
```
3. ExternalName with selector and ports will generate proper endpoint
```
NAME                      ENDPOINTS         AGE
echoserver-externalname   10.24.1.7:80      69s
```

### After switching ExternalName with selector to ClusterIP, it will not respond to traffic

Reproduction:

1. Create deployment

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
        k8s-app: glbc
    spec:
      containers:
      - image: nginx:1.22
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 80
          hostPort: 80
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 3
```

2. Create ExternalName Service with selector

```
apiVersion: v1
kind: Service
metadata:
  name: echoserver-externalname
  namespace: default
spec:
  selector:
    app: echoserver
  type: ExternalName
  externalName: www.google.com
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
```

3. Change Service type to ClusterIP

after that, doing curl to ClusterIP (from cluster node) will return
`curl: (7) Failed to connect to 10.28.13.144 port 80 after 0 ms: Connection refused`

### iptables probably wrong

I compared node's iptables after creating ClusterIP service from scratch, and after doing ExternalName -> ClusterIP and found the only one different line:

```
-A KUBE-SERVICES -d 10.28.13.144/32 -p tcp -m comment --comment "default/echoserver-externalname has no endpoints" -m tcp --dport 80 -j REJECT --reject-with icmp-port-unreachable
```

Which probably is the source of dropped traffic.

Also, I verified, there is endpoints on the service, and you can also get them from kubectl get endpoints
```
$ kubectl describe service echoserver-externalname 
Name:              echoserver-externalname
Namespace:         default
Selector:          app=echoserver
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.28.13.144
IPs:               10.28.13.144
External Name:     www.google.com
Port:              <unset>  80/TCP
TargetPort:        80/TCP
Endpoints:         10.24.1.7:80
Session Affinity:  None
```

**Comment by panslava** [comment]
After switching ExternalName -> ClusterIP I see only those logs in kube-proxy

```

I1214 14:45:50.731550       1 service.go:324] "Service updated ports" service="default/echoserver-externalname" portCount=1
I1214 14:45:50.731685       1 service.go:440] "Adding new service port" portName="default/echoserver-externalname" servicePort="10.28.9.45:80/TCP"
I1214 14:45:50.731725       1 proxier.go:850] "Syncing iptables rules"
I1214 14:45:50.776750       1 proxier.go:1487] "Reloading service iptables data" numServices=6 numEndpoints=7 numFilterChains=5 numFilterRules=4 numNATChains=17 numNATRules=39
I1214 14:45:50.781575       1 proxier.go:817] "SyncProxyRules complete" elapsed="49.919239ms
```

**Comment by panslava** [comment]
So this is probably where we set this reject rule https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1082

**Comment by aojea** [comment]
Found the bug, the endpointslice for a ExternalName Service is created as a HeadlessService

```
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2022-12-14T17:32:29Z"
  creationTimestamp: "2022-12-14T17:32:29Z"
  generateName: externalname-
  generation: 1
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: externalname
    service.kubernetes.io/headless: ""
  name: externalname-qjpmq
```

when the Service is mutated to the ClusterIP type, the endpointslice is not updated and stills have the headless annotation
```
    uid: 531bf465-8548-4fea-980e-6eeb99e4d6d4
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2022-12-14T17:32:29Z"
  creationTimestamp: "2022-12-14T17:32:29Z"
  generateName: externalname-
  generation: 1
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: externalname
    service.kubernetes.io/headless: ""
``` 

so kube-proxy ignores it, and installs the reject rule thinking that the Service doesn´t have any endpoint associated
/cc @robscott
