### ISSUE TITLE
volumeClaimTemplates.spec.resources.requests.storage: 10Mi. PVC was not created as expected

### ISSUE THREAD

**Issue by ormissia** [kubernetes/kubernetes#105956]
### What happened?

When I test [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components) ,
I set requests storage 10Mi in volumeClaimTemplates

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Mi  # I set pvc templates storage 10Mi
        storageClassName: test-pv
```

But 100Mi is assigned by default

```
$ kubectl get pvc -n kube-test 
NAME        STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
www-web-0   Bound     test-pv   100Mi      RWX            test-pv        12m
www-web-1   Pending                                       test-pv        12m

$ kubectl describe pvc www-web-0 -n kube-test 
Name:          www-web-0
Namespace:     kube-test
StorageClass:  test-pv
Status:        Bound
Volume:        test-pv
Labels:        app=nginx
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Mi               # 100Mi is assigned by default
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       web-0
Events:        <none>
```

### What did you expect to happen?

I expect PVC to apply for 10Mi according to the `resources.requests.storage` of volumeClaimTemplates.

### How can we reproduce it (as minimally and precisely as possible)?

1. Have an available NFS and create path for PV
2. Create a PV
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: test-pv
  nfs:
    path: /data/nfs/kubernetes/test
    server: node1
```
3. Create a StatefulSet
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Mi
        storageClassName: test-pv
```
4. And then describe automatically created PVC
<details>
kubectl get pvcs -n kube-test

kubectl describe pvc www-web-1

</details>

### Anything else we need to know?

nil

### Kubernetes version

<details>

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}

</details>

### Cloud provider

nil

### OS version

<details>

# On Linux:
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.4"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:4:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.4
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.4

$ uname -a
Linux node1 5.4.17-2102.205.7.3.el8uek.aarch64 #2 SMP Fri Sep 17 16:33:18 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux

</details>

### Install tools

nil

### Container runtime (CRI) and and version (if applicable)

<details>

$ docker -v
Docker version 20.10.9, build c2ea9bc

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

nil
