### ISSUE TITLE
Deleting SA breaks project SA token

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#106049]
### What happened?

1. Create a pod with a project SA token:
```yaml
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
```
2. Send a TokenReview:

```
function review-token() {
    kubectl create --raw /apis/authentication.k8s.io/v1/tokenreviews -f - <<EOF
{"apiVersion":"authentication.k8s.io/v1","kind":"TokenReview","spec":{"audiences":["istio-ca"],"token":"${1:?token}"}}
EOF
}
$ review-token $(kubectl exec -c istio-proxy echo-cb96f8d94-7zdx7  -- cat ./run/secrets/tokens/istio-token) | jq
```

Result is a success.

3. Delete the SA for the pod
4. Wait for the token to refresh, run `review-token` again:

`[invalid bearer token, ServiceAccount UID (795fd62d-5f1f-44c8-89f0-3fae5e2af501) does not match claim (deb3ec38-9d9f-4868-abbb-948436f6d38c)]`

Note: `795fd62d-5f1f-44c8-89f0-3fae5e2af501` is the new UID, not the old one.

5. Restart pod and rerun. It now works.

### What did you expect to happen?

TokenReview is successful without pod restart.

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Kubernetes version

<details>

```console
$ kubectl version
1.22
```

</details>

### Cloud provider

<details>
I reproduced it on kind, another user mentioned it occurred on AWS.
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
