### ISSUE TITLE
x-kubernetes-embedded-resource fields not being validated as documented

### ISSUE THREAD

**Issue by rsalmond** [kubernetes/kubernetes#106057]
### What happened?

Created the following CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repros.superorbital.io
spec:
  group: superorbital.io
  scope: Namespaced
  names:
    kind: Repro
    plural: repros
    singular: repro
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              fooTemplate:
                type: object
                x-kubernetes-preserve-unknown-fields: true
                x-kubernetes-embedded-resource: true
                properties: {}
```

Then created the following instance:

```yaml
apiVersion: "superorbital.io/v1"
kind: Repro
metadata:
  name: reprotest
spec:
  fooTemplate:
    apiVersion: eleventyone
    kind: Doodad
    metadata: {}
    spec:
      foo: bar
```

### What did you expect to happen?

Given [this explanation in the docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/): "With x-kubernetes-embedded-resource: true, the apiVersion, kind and metadata are implicitly specified and validated." I expected that:

The `apiVersion` and `kind` in my CR would be rejected because it is not registered in the API.

The `metadata` field would be rejected because it is missing a `name` field.

Instead it appears that the object is only checked for the presence rather than the content of the fields mentioned in the documentation.

### How can we reproduce it (as minimally and precisely as possible)?

Apply the above manifests and observe that the `Repro` object is created without errors.

### Anything else we need to know?

Assuming this is a documentation issue, it would also be helpful to call out that when a valid native API object is embedded, such as the one below, the `spec` will not be validated either.

```
            properties:
              fooTemplate:
                type: object
                x-kubernetes-preserve-unknown-fields: true
                x-kubernetes-embedded-resource: true
                properties:
                  apiVersion:
                    type: string
                    pattern: v1
                  kind:
                    type: string
                    pattern: Pod
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-gke.1300", GitCommit:"9352724e36d9c7c35609d30b2696b0de61d23aa0", GitTreeState:"clean", BuildDate:"2021-10-06T09:26:56Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
