### ISSUE TITLE
Kubernetes client cert based authentication results in request using system:anonymous user

### ISSUE THREAD

**Issue by venugopalthati** [kubernetes/kubernetes#106117]
### What happened?

I have followed these instructions to create normal user in Kubernetes and generated client certificate https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#normal-user

When I try to send a request to the API server using curl by providing the certificate and key, response comes back as "message": "forbidden: User "system:anonymous" cannot get path "/apis"

kubectl get pods is also not working.

```
kubectl get pods -n xyz
error: the server doesn't have a resource type "pods"
```

### What did you expect to happen?

Expected authentication to work and list pods as per the kubectl command.

### How can we reproduce it (as minimally and precisely as possible)?

Follow the steps listed in this link to generate client certificate. https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#normal-user

Create ClusterRole and RoleBinding

```

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only-role
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  - /api/*
  - /apis/*
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-binding
  namespace: xyz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-only
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: userone

```

Then use certificate and key in the kubeconfig or curl command, results in 403.

```
curl -k -v -L --cert ./userone.crt --key ./userone.key -k --request GET https://<host>:443/apis\?timeout\=32s

<Removed some text>

 HTTP/1.1 403 Forbidden
< Server: nginx/1.12.2
< Date: Tue, 02 Nov 2021 21:53:03 GMT
< Content-Type: application/json
< Content-Length: 237
< Connection: keep-alive
< Cache-Control: no-cache, private
< X-Content-Type-Options: nosniff
< 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/apis\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
```

### Anything else we need to know?

Also tried impersonating this user where I had elevated access, this new user is able access pods as configured in the clusterrole and rolebinding. I think this atleast proves that authorization is working.

```
kubectl auth can-i -n xyz get pods --as=userone
yes

```

### Kubernetes version

<details>

```console
$ kubectl version
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:52:26Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On-Prem Kubernetes Cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
