### ISSUE TITLE
Volume mount not respecting fsGroup value on non-existant parent directory

### ISSUE THREAD

**Issue by TechnoChimp** [kubernetes/kubernetes#106194]
### What happened?

When deploying a container with a volume mount and fsGroup defined, the mount operation will disregard the fsGroup value for any newly created directory in the mount path.

fsGroup: 1234

Container has:
/my/path

Mount path:
/my/path/here/mount

the 'mount' folder correctly has group set to 1234, but the 'here' folder has group set to root.

### What did you expect to happen?

I expected the newly created 'here' folder to be set to the same permission as the fsGroup, or inherit the group from the existing parent folder.

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mounttest
spec:
  selector:
    matchLabels:
      app: mounttest
  template:
    metadata:
      labels:
        app: mounttest
    spec:
      containers:
      - name: mounttest
        image: node:latest
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /home/node/nonexistantpath/mount
          name: volume
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
      - emptyDir: {}
        name: volume
```

Check the folder permissions

```
node@mounttest-6cc4ff6468-zwkvr:/$ cd /home/node/
node@mounttest-6cc4ff6468-zwkvr:~$ ls -al
total 12
drwxr-xr-x 1 node node   55 Nov  5 21:31 .
drwxr-xr-x 1 root root   18 Oct 13 05:42 ..
-rw-r--r-- 1 node node  220 Aug  4 20:25 .bash_logout
-rw-r--r-- 1 node node 3526 Aug  4 20:25 .bashrc
-rw------- 1 node node    0 Nov  5 21:31 .node_repl_history
-rw-r--r-- 1 node node  807 Aug  4 20:25 .profile
drwxr-xr-x 3 root root   19 Nov  5 21:31 nonexistantpath
node@mounttest-6cc4ff6468-zwkvr:~$ cd nonexistantpath/
node@mounttest-6cc4ff6468-zwkvr:~/nonexistantpath$ ls -al
total 0
drwxr-xr-x 3 root root 19 Nov  5 21:31 .
drwxr-xr-x 1 node node 55 Nov  5 21:31 ..
drwxrwsrwx 2 root node  6 Nov  5 21:31 mount
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS ~ EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
