### ISSUE TITLE
static cpu pin should not related with Guaranteed pod, should support individual container enable cpu pin

### ISSUE THREAD

**Issue by smileusd** [kubernetes/kubernetes#106149]
### What would you like to be added?

When pod have two container and one's request equals limits but another is not, kubelet also can enable static cpu for that container limit=request. But now only pod is Guaranteed can be enable static pod.

### Why is this needed?

Users have  more choices when some containers in pod want high performance but others not. Some containers need use cpu pin but others unnecessary for example, side car container injected into pod doesn't need use static cpu.

**Comment by SergeyKanzhelev** [comment]
Can you please describe better what is the current vs. expected behavior. Ideally with the yaml files. I'm not quite clear on what is the feature request from the description.

**Comment by smileusd** [comment]
@SergeyKanzhelev  When use this pod yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        memory: "128Mi"
        cpu: "1"
      limits:
        memory: "128Mi"
        cpu: "1"
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        memory: "128Mi"
        cpu: "400m"
      limits:
        memory: "256Mi"
        cpu: "1"
```
Actually users want to enable static cpu on app container but not enable on log-aggregator container. But from now code kubelet will skip all the containers in this pod because it is not a Guareanteed pod:
```
func (p *staticPolicy) Allocate(s state.State, pod *v1.Pod, container *v1.Container) error {
	if numCPUs := p.guaranteedCPUs(pod, container); numCPUs != 0 {
```
```
func (p *staticPolicy) guaranteedCPUs(pod *v1.Pod, container *v1.Container) int {
	if v1qos.GetPodQOS(pod) != v1.PodQOSGuaranteed {
		return 0
	}
	cpuQuantity := container.Resources.Requests[v1.ResourceCPU]
	if cpuQuantity.Value()*1000 != cpuQuantity.MilliValue() {
		return 0
	}
	// Safe downcast to do for all systems with < 2.1 billion CPUs.
	// Per the language spec, `int` is guaranteed to be at least 32 bits wide.
	// https://golang.org/ref/spec#Numeric_types
	return int(cpuQuantity.Value())
}
```
