### ISSUE TITLE
Inconsistent behaviour across k8 versions while mounting character devices as file

### ISSUE THREAD

**Issue by utk231** [kubernetes/kubernetes#106205]
### What happened?

Issue - For v<1.19 k8 doesn't throw error if `type:File` being used for mounting character devices but as per its working it should.

How native k8 checks it is given in link [1](https://github.com/kubernetes/kubernetes/blob/dba9975e3e3ba25e0712a209e67862603c172777/pkg/volume/util/hostutil/hostutil.go#L27) & [2](https://github.com/kubernetes/kubernetes/blob/dba9975e3e3ba25e0712a209e67862603c172777/pkg/volume/hostpath/host_path.go#L369). Based on above code, as an expected behavior if user specifies `type:File` for mounting these character devices, it should throw error from [here](https://github.com/kubernetes/kubernetes/blob/dba9975e3e3ba25e0712a209e67862603c172777/pkg/volume/hostpath/host_path.go#L452) on checking, just like it throws on k8 versions >= 1.19. 

For versions <1.19, it bypasses and allows `type:File` for mounting character devices. This breaks the application flow when cluster is upgraded from 1.18 to 1.19 as the pods go into `ContainerCreating` State.

### What did you expect to happen?

Consistent behaviour across all kubernetes versions i.e. It should throw error on <1.19 k8 versions as well. 

### How can we reproduce it (as minimally and precisely as possible)?

Apply the following manifest on:

```
kubectl apply -f - <<EOF                                         
apiVersion: v1
kind: Pod
metadata:
  name: test-host-mount
spec:
  containers:
  - image: registry.access.redhat.com/ubi8/ubi
    name: test-container
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - mountPath: /host
      name: host-slash
  volumes:
   - name: host-slash
     hostPath:
       path: /dev/urandom
       type: File
EOF
```

1. On 1.18 or lower version clusters (No error thrown)
2. On 1.19 and higher clusters (Breaks the flow and starts throwing error `MountVolume.SetUp failed for volume "host-slash" : hostPath type check failed: /dev/urandom is not a file` )

### Anything else we need to know?

Here’s the [fix](https://github.com/kubernetes/kubernetes/commit/084fe6de9395f043700573dc3b8f490e9d02ee78) that has only been included since 1.19. Can this be added for k8 versions <1.19 as well ?

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
```

</details>

### Cloud provider

<details>
AWS 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
