### ISSUE TITLE
kubectl apply --prune does not delete resources matching label selector in "unvisited" namespaces 

### ISSUE THREAD

**Issue by jonbuckley33** [kubernetes/kubernetes#106284]
### What happened?

While experimenting with `kubectl apply --prune --selector`, I noticed that it skipped deleting resources in some circumstances. After further experimentation, I learned that `kubectl apply --prune --selector foo=bar -f resources.yaml` won't delete resources in a namespace if that namespace doesn't appear in resources.yaml, even if the resources have the specified label.

### What did you expect to happen?

I expect `kubectl apply --prune --selector foo=bar -f resources.yaml` to delete orphaned resources in all namespaces, regardless of whether some namespaces appear in resources.yaml.

### How can we reproduce it (as minimally and precisely as possible)?

Create test namespace:

```console
$ kubectl create namespace test
```

And given resources.yaml is initially:

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    foo: bar
  name: a
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    foo: bar
  name: b
  namespace: test
```

Apply resources.yaml: `kubectl apply -f resources.yaml`

Now remove ConfigMap `b` from resources.yaml and apply with `--prune`:

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    foo: bar
  name: a
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#  labels:
#    foo: bar
#  name: b
#  namespace: test
```

```console
$ kubectl apply -f resources.yaml --prune --selector foo=bar
```

We expect b to be pruned, but it is untouched.

Next, we add another ConfigMap, c, to the test namespace:

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    foo: bar
  name: a
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#  labels:
#    foo: bar
#  name: b
#  namespace: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    foo: bar
  name: c
  namespace: test
```

and we run `kubectl apply -f resources.yaml --prune --selector foo=bar` again. This time, ConfigMap b is pruned.

### Anything else we need to know?

As noted in https://github.com/kubernetes/kubernetes/issues/66430#issuecomment-801636255, this is probably because the implementation of prune "visits" namespaces and adds them to a list of namespaces to prune resources from. I'm not sure whether this behavior is intended -- I didn't see this limitation in the docs (e.g., https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands). If it is intended, I suggest including it in the documentation for better discoverability. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4-gke.200", GitCommit:"57bfc1baa0238d4e7b280f818bbe5730d91e0463", GitTreeState:"clean", BuildDate:"2021-08-16T09:32:17Z", GoVersion:"go1.16.6b7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4-gke.200", GitCommit:"57bfc1baa0238d4e7b280f818bbe5730d91e0463", GitTreeState:"clean", BuildDate:"2021-08-16T09:30:11Z", GoVersion:"go1.16.6b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

GKE

</details>
