### ISSUE TITLE
kubectl auth reconcile does not handle the default api group properly

### ISSUE THREAD

**Issue by chulkilee** [kubernetes/kubernetes#106221]
### What happened?

When using the default `apiGroup` value (which is `rbac.authorization.k8s.io` for `kind: User`, kubectl auth reconcile` prints out it's removing and adding the subject although they're effectively same.

### What did you expect to happen?

The diff should not be generated when no change is needed.

### How can we reproduce it (as minimally and precisely as possible)?

```
kubectl auth reconcile --remove-extra-subjects --remove-extra-permissions -f test.yaml
```

`test.yaml`:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbac-test-role
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["pods/exec"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-test-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-test-role
subjects:
- kind: User
  name: foo@example.com
```

Output:

```
role.rbac.authorization.k8s.io/rbac-test-role reconciled
rolebinding.rbac.authorization.k8s.io/rbac-test-role-binding reconciled
	reconciliation required update
	missing subjects added:
		{Kind:User APIGroup: Name:foo@example.com Namespace:}
	extra subjects removed:
		{Kind:User APIGroup:rbac.authorization.k8s.io Name:foo@example.com Namespace:}
```

When I add `  apiGroup: rbac.authorization.k8s.io` to the subject, 

first run:
```
role.rbac.authorization.k8s.io/rbac-test-role reconciled
rolebinding.rbac.authorization.k8s.io/rbac-test-role-binding reconciled
	reconciliation required update
	missing subjects added:
		{Kind:User APIGroup: Name:foo@example.com Namespace:}
	extra subjects removed:
		{Kind:User APIGroup:rbac.authorization.k8s.io Name:foo@example.com Namespace:}
```

second run:
```
role.rbac.authorization.k8s.io/rbac-test-role reconciled
rolebinding.rbac.authorization.k8s.io/rbac-test-role-binding reconciled
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.1600", GitCommit:"ef8e9f64449d73f9824ff5838cea80e21ec6c127", GitTreeState:"clean", BuildDate:"2021-09-06T09:24:20Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
macOS 11.6.1 (20G224) (intel)
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
