### ISSUE TITLE
Full Pod Disruption Budget support for Daemonsets

### ISSUE THREAD

**Issue by Crazybus** [kubernetes/kubernetes#106309]
### What would you like to be added?

Pod Disruption Budgets to have full support for Daemonsets. Currently only [minAvailable with integer values](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors) is supported.

### Why is this needed?

Daemonsets are used for cluster level networking functions like Ingress and Kubernetes system components like kube-proxy. Pod Disruption Budget support allows proper signaling that it is not safe to restart all pods in the Daemonset simultaneously. With the current available implementation there are situations where tools like the [Vertical Pod Autoscaler](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) will evict all pods at the same time in an undesirable way.

### Background

Similar to as seen by [Nginxinc](https://github.com/nginxinc/kubernetes-ingress/blob/master/deployments/daemon-set/nginx-ingress.yaml) we currently run our Nginx Ingress as a Daemonset. This is done for two reasons:

1. To work around an issue in GKE where it is not possible for nodes to reach an ingress running within the cluster unless the ingress pod is on their node (we run a Docker registry in GKE).
2. It allows us to naturally scale our ingress workload with the amount of nodes in the cluster. Without the workaround needed from 1 we would use a deployment with Horizontal Pod Autoscaler.

As a result of this we now use the [Vertical Pod Autoscaler](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) to scale this Daemonset in our cluster based on usage metrics. The Vertical Pod Autoscaler uses the evict API to update pods which respects configured Pod Disruption Budgets.

Without a PDB configured the VPA will replace all pods at the same time resulting in a short period of downtime. If you attempt to configure a PDB of `maxUnavailable: 1` VPA is unable to evict pods because the calculated status is incorrect:

(All examples below are on a 3 node cluster)

expected disruptionsAllowed: 1
```yaml
spec:
  maxUnavailable: 1
status:
  currentHealthy: 3
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 3
```

expected disruptionsAllowed: 1
```yaml
spec:
  maxUnavailable: 50%
status:
  currentHealthy: 3
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 3
```

expected disruptionsAllowed: 1
```yaml
spec:
  minAvailable: 50%
status:
  currentHealthy: 3
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 3
```

The only way to create a PDB with any allowed disruptions is to set `minAvailable < expectedPods`

```yaml
spec:
  minAvailable: 2
status:
  currentHealthy: 3
  desiredHealthy: 2
  disruptionsAllowed: 1
  expectedPods: 3
```

However the issue with not having a percent is that a node with 50 clusters will now allow 48 to become unavailable at the same time. Setting this number manually for a large amount of autoscaling (node autoscaling) clusters isn't a great option and would require something dynamically responding to changes in node numbers.
