### ISSUE TITLE
How to restart PODs in batches

### ISSUE THREAD

**Issue by jainpratik163** [kubernetes/kubernetes#106424]
Hi,

we have around 200+ MS and we are created customresourcebinding and once we apply this binding it will restart all the pod together .
Now we don't want this happen, we want to restart the pod in batches.
is this possible?

Thanks

**Comment by sftim** [comment]
What's a customresourcebinding?

**Comment by jainpratik163** [comment]
we are adding labels in all our MS and once we add such it will restart all MS and we want to avoid this.


```
spec:
  msSelector:
    provide: app
  volumes:
    - downwardAPI:
        items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              fieldPath: metadata.annotations
            path: annotations
      name: podinfo
  labels:
    color: "blue"
  annotations:
    active-color: blue
  businessContainerSpec:
    volumeMounts:
    - mountPath: /etc/podinfo
      name: podinfo
```
