### ISSUE TITLE
After upgrading from 1.19 to 1.21.3 deployments now require massive resource limit increases.

### ISSUE THREAD

**Issue by jurschel** [kubernetes/kubernetes#106537]
### What happened?

- Cluster was upgraded from 1.19 to 1.20 and finally to 1.21.3
- During this deployments were restarted  
- Noticed several were not starting and investigated
- Some deployments with startup probes were failing and thus could not start
- Some deployments with liveness and readiness probes were failing and thus could not start
- Logged into an example of one of these deployments and received no response from issued commands
- Determined that now the deployment was consuming over the resource limits
- Raised the resource limits on a deployment that was running prior to this upgrade at 100m and 128Mi to 1000m and 2Gi
- Even with raised limits the startup probe failed 3 times before succeeding 
- Now this deployment has enough resources to pass the probe checks and actually start

### What did you expect to happen?

That all deployments would start normally without any resource limit changes required.

### How can we reproduce it (as minimally and precisely as possible)?

Use this helm chart and install "TheHive" 
https://github.com/jaredjennings/helm-thehive
The only changes in this values.yaml file are the hostnames, tls and storage provider.
I would start with a 1.19 cluster and deploy a service with a startup, liveness and readiness probe similar to these below and then upgrade that cluster from 1.19 with docker runtime to 1.20 with docker runtime and then 1.21.3 with containerd runtime.  When you get to 1.21.3 the deployment should no longer start because it's likely going to fail the startup probe or one of the liveness or readiness probes.  Then increase the resource limits until it starts.

```
startupProbe:
  failureThreshold: 5
  httpGet:
    path: /api/v1/status
	port: http
	scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds

readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
	port: http
	scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeSeconds: 1
  
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /api/v1/status
	port: http
	scheme: HTTP
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
```

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

1.21.3-pmk.35 (platform9 build)
```

</details>

### Cloud provider

<details>
On prem bare metal build using platform9 as the k8s provider
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux platform907 4.15.0-162-generic #170-Ubuntu SMP Mon Oct 18 11:38:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd containerd.io 1.4.6 d71fcd7d8303cbf684402823e425e9dd2e99285d
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
