### ISSUE TITLE
low priority pods stuck in pending without any scheduling events

### ISSUE THREAD

**Issue by lianghao208** [kubernetes/kubernetes#106546]
### What happened?

My cluster already has high priority pending pods(lack of resources). Now I try to create a low priority pods, but it seems those pods won't be handled by the kube-scheduler(no scheduling event at all). And then I modify the low priority pods to high priority, it can be scheduled successfully. Is it normal? 

### What did you expect to happen?

Low priority pods can also be handled by scheduler event there are high priority pods still pending in cluster.

### How can we reproduce it (as minimally and precisely as possible)?

create some high priority pods with huge resource request( make sure they stuck in pending), then create some low priority pods with no  resource request( make sure they can be scheduled on reasonable nodes). The scheduler won't schedule the low priority pods (no events).

### Kubernetes version

<details>

```console
$ kubectl version
v1.18.4
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
The lower priority pods should be scheduled successfully as you described, maybe you can attach your yaml template?

**Comment by lianghao208** [comment]
@kerthcet 

This is the lower priorityClassName `medium` pod that stucks in pending
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-1
  namespace: default
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 5
    image: nginx:latest
    imagePullPolicy: Always
    name: smoke-test
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 250m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeSelector:
    kubernetes.io/hostname: 11.13.4.88
  priorityClassName: medium
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 2
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

After I modified the priorityClassName to `high`, the pod can be scheduled successfully.

This is my priorityClass:

```shell
$ kubectl get pc
NAME                      VALUE        GLOBAL-DEFAULT   AGE
high                      0            true             110d
low                       -1000        false            110d
medium                    -500         false            110d
```
