### ISSUE TITLE
Deployment Conditions - Progressing & Available not updated appropriately

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/kubernetes#106697]
### What happened?

There are numerous cases where the deployment doesn't update it's `Progressing` condition to have a status of `False` with the reason `ProgressDeadlineExceeded`.

Similarly `Available` remains `True` when I would expect it to become `False`

/sig apps

### What did you expect to happen?

After any spec change and after `spec.progressDeadlineSeconds` has elapsed the condition type `Progressing` has it's status set to `False` with the reason `ProgressDeadlineExceeded`.

Similarly, `Available` condition should be updated appropriately

### Repro 1 - A deployment with an invalid image scaling from 0 to 1

Apply the following deployment 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default  
spec:
  replicas: 0
  progressDeadlineSeconds: 20
  selector:
    matchLabels:
      app: nginx  
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: bad-image       
        name: nginx
        ports:
         - containerPort: 80
```

Then scale the deployment to have one replica

```sh
$ kubectl scale deploy nginx --replicas 1
```

The  deployments status remains `Progressing=True` forever
```yaml
status:
  conditions:
  - lastTransitionTime: "2021-11-26T20:52:12Z"
    lastUpdateTime: "2021-11-26T20:52:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-11-26T20:52:12Z"
    lastUpdateTime: "2021-11-26T20:52:12Z"
    message: ReplicaSet "nginx-b457db654" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
```

Oddly the deployment also shows `Available=True` which is incorrect

### Repro 2 - A resource quota is hit

Apply the following resource quota (assume no other pods in your namespace)
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods
spec:
  hard:
    pods: "3"
```

Apply this valid deployment with three replicas
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  progressDeadlineSeconds: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx:1.7.9
        ports:
        - containerPort: 80
```

Scale the deployment to four replicas
```sh
$ kubectl scale deploy nginx --replicas 4
```

See that the status shows `Progressing=True` forever
```
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-11-26T21:02:39Z"
    lastUpdateTime: "2021-11-26T21:02:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-11-26T21:03:25Z"
    lastUpdateTime: "2021-11-26T21:03:25Z"
    message: ReplicaSet "nginx-6678586ffc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-11-26T21:03:34Z"
    lastUpdateTime: "2021-11-26T21:03:34Z"
    message: 'pods "nginx-6678586ffc-xlw7v" is forbidden: exceeded quota: pods, requested:
      pods=1, used: pods=3, limited: pods=3'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

Oddly the deployment also shows `Available=True` which is incorrect

### Anything else we need to know?

It seems like `ProgressDeadlineExceeded` is only set when we first create the deployment.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-23T01:39:14Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
```
% kind version
kind v0.11.1 go1.16.4 darwin/amd64
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
