### ISSUE TITLE
"kubectl set" fails to output yaml sections that don't match.

### ISSUE THREAD

**Issue by Spongman** [kubernetes/kubernetes#106617]
### What happened?

`foo.yaml`:

```yaml
kind: pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-pod
    image: foo:latest
---
kind: service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    pod: my-pod
  ports:
  - port: 1234
    targetPort: 1234
```

this works:
```
$ kubectl apply -f foo.yaml
```

as does this:

```
$ cat foo.yaml | kubectl apply -f -
```

but this doesn't:

```
$ kubectl set image my-pod=bar:latest -o yaml | kubectl apply -f -
```

because it doesn't pass through the second section. instead it dumps
```
error: service/my-service the object is not a pod or does not have a pod template: *v1.Service
```

### What did you expect to happen?

i'd expect it to just pipe the section regardless of whether or not the resource type matched, like`sed`.

### How can we reproduce it (as minimally and precisely as possible)?

(see above)

### Kubernetes version

<details>
```console
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compi
ler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compi
ler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute

$ uname -a
Linux host 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
>wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                   OSArchitecture  Version     
19043        Microsoft Windows 10 Pro  64-bit          10.0.19043  
```

</details>
