### ISSUE TITLE
Unable to upgrade cluster more than 2 times using kubeadm.

### ISSUE THREAD

**Issue by ak2766** [kubernetes/kubernetes#106767]
### What happened?

I deployed a cluster of 10 nodes - 3 control-plane nodes and 7 worker nodes - and an external 3 node ETCD cluster on the 3 control-plane nodes.  The initial deployment was for v1.20.13.  I created a BASH script after going through Kubernetes the hard way.

I then proceeded to upgrade the cluster using another BASH script to v1.21.7.  That did not go so well.  Well, the upgrade completed successfully but the static pod manifests were still pointing to the old version - i.e. `kubectl version` would tell me that client was at v1.21.7 but server was still at v1.20.13.  I then went into the `/etc/kubernetes/manifests` directory, moved the manifests out, modified the `image:` key to point to the new version, then moved them back to their proper location and afterwards both client and server were reporting the same version.  Good.  I edited my script to add this to avoid having to do it again and life was good until I went to upgrade to v1.22.4.

My first attempt to upgrade to `v1.22.4` went as below:

<details>
<summary>ATTEMPT 1: kubeadm upgrade plan</summary>

```# kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.21.7
[upgrade/versions] kubeadm version: v1.22.4
[upgrade/versions] Target version: v1.22.4
[upgrade/versions] Latest version in the v1.21 series: v1.21.7

[upgrade/versions] FATAL: configmaps "kubelet-config-1.21" not found
To see the stack trace of this error execute with --v=5 or higher
```
</details>

I then tried something interesting:
```
# kubectl -n kube-system get cm kubelet-config-1.20 -oyaml | sed 's/1.20/1.21/' | kubectl apply -f -
configmap/kubelet-config-1.21 created
```

Obviously I do not know the implications of my actions - I'm trying stuff to see what sticks...

I then tried the upgrade plan again:
<details>
<summary>ATTEMPT 2: kubeadm upgrade plan</summary>

```
# kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.21.7
[upgrade/versions] kubeadm version: v1.22.4
[upgrade/versions] Target version: v1.22.4
[upgrade/versions] Latest version in the v1.21 series: v1.21.7

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT        TARGET
kubelet     10 x v1.21.7   v1.22.4

Upgrade to the latest stable version:

COMPONENT                 CURRENT   TARGET
kube-apiserver            v1.21.7   v1.22.4
kube-controller-manager   v1.21.7   v1.22.4
kube-scheduler            v1.21.7   v1.22.4
kube-proxy                v1.21.7   v1.22.4
CoreDNS                   1.7.0     v1.8.4

You can now apply the upgrade by executing the following command:

        kubeadm upgrade apply v1.22.4

_____________________________________________________________________


The table below shows the current state of component configs as understood by this version of kubeadm.
Configs that have a "yes" mark in the "MANUAL UPGRADE REQUIRED" column require manual config upgrade or
resetting to kubeadm defaults before a successful upgrade can be performed. The version to manually
upgrade to is denoted in the "PREFERRED VERSION" column.

API GROUP                 CURRENT VERSION   PREFERRED VERSION   MANUAL UPGRADE REQUIRED
kubeproxy.config.k8s.io   v1alpha1          v1alpha1            no
kubelet.config.k8s.io     v1beta1           v1beta1             no
_____________________________________________________________________
```
</details>

### What did you expect to happen?

I expected `kubeadm upgrade apply` to work reliably from an initial deployment of Kubernetes `v1.20.13` then to `v1.21.7` and finally to `v1.22.4` without requiring manual intervention as seen above.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a Kubernetes cluster at `v1.20.13` using `kubeadm`, then attempt to upgrade to version `v1.22.4` using `kubeadm`.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:41:19Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux node1 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
N/A
```

</details>

### Install tools

N/A

### Container runtime (CRI) and and version (if applicable)

containerd://1.4.12

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by pacoxu** [comment]
/area kubeadm
I will try to reproduce it tomorrow.
After 1.23 with #105741, UnversionedKubeletConfigMap will help us using `kubelet-config` instead of `kubelet-config-1.xx`.
> kubeadm: add the kubeadm specific, Alpha (disabled by default) feature gate UnversionedKubeletConfigMap. When this feature is enabled kubeadm will start using a new naming format for the ConfigMap where it stores the KubeletConfiguration structure. The old format included the Kubernetes version - "kube-system/kubelet-config-1.22", while the new format does not - "kube-system/kubelet-config". A similar formatting change is done for the related RBAC rules. The old format is now DEPRECATED and will be removed after the feature graduates to GA. When writing the ConfigMap kubeadm (init, upgrade apply) will respect the value of UnversionedKubeletConfigMap, while when reading it (join, reset, upgrade), it would attempt to use new format first and fallback to the legacy format if needed.

**Comment by neolit123** [comment]
I don't see how this can happen without external interference e.g deleting
the CM or passing --config.

When upgrade from 1.20 to 1.21 is done. The 1.21 CM is created, If not an
error is thrown during upgrade. This means that the 1.22 upgrade will
always find the CM.

We actually have e2e tests that ensure that the CM is cteated post upgrade.

/priority awaiting-more-evidence

**Comment by pacoxu** [comment]
```
# started with 1.18 
[root@dce-10-7-177-9 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"2cc6e0a70a", GitTreeState:"clean", BuildDate:"2020-03-26T06:42:04Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

[root@dce-10-7-177-9 ~]# kubectl get node
NAME             STATUS   ROLES    AGE   VERSION
dce-10-7-177-9   Ready    master   39m   v1.18.20-lts.0

[root@dce-10-7-177-9 ~]# kubectl get cm -A
NAMESPACE     NAME                                 DATA   AGE
kube-public   cluster-info                         2      37m
kube-system   coredns                              1      37m
kube-system   extension-apiserver-authentication   6      37m
kube-system   kube-proxy                           2      37m
kube-system   kubeadm-config                       2      37m
kube-system   kubelet-config-1.18                  1      37m


# upgrade to 1.19
kubeadm  upgrade apply v1.19.16

[root@dce-10-7-177-9 ~]# kubectl get node

NAME             STATUS   ROLES    AGE   VERSION
dce-10-7-177-9   Ready    master   56m   v1.19.16
[root@dce-10-7-177-9 ~]#
[root@dce-10-7-177-9 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"2cc6e0a70a", GitTreeState:"clean", BuildDate:"2020-03-26T06:42:04Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:20:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

[root@dce-10-7-177-9 ~]# kubectl get cm -n kube-system
NAME                                 DATA   AGE
coredns                              1      57m
extension-apiserver-authentication   6      57m
kube-proxy                           2      57m
kubeadm-config                       2      57m
kubelet-config-1.18                  1      57m
kubelet-config-1.19                  1      8m54s

# upgrade to 1.20
kubeadm  upgrade apply v1.20.13

[root@dce-10-7-177-9 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-17T13:00:29Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

[root@dce-10-7-177-9 ~]# kubectl get node
NAME             STATUS   ROLES                  AGE   VERSION
dce-10-7-177-9   Ready    control-plane,master   83m   v1.20.13

[root@dce-10-7-177-9 ~]# kubectl get cm -n kube-system
NAME                                 DATA   AGE
coredns                              1      83m
extension-apiserver-authentication   6      83m
kube-proxy                           2      83m
kube-root-ca.crt                     1      2m28s
kubeadm-config                       2      83m
kubelet-config-1.18                  1      83m
kubelet-config-1.19                  1      35m
kubelet-config-1.20                  1      2m44s


# upgrade to 1.21
kubeadm  upgrade apply v1.21.7

[root@dce-10-7-177-9 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
[root@dce-10-7-177-9 ~]# kubectl get node
NAME             STATUS   ROLES                  AGE    VERSION
dce-10-7-177-9   Ready    control-plane,master   112m   v1.21.7

[root@dce-10-7-177-9 ~]# kubectl get cm -n kube-system
NAME                                 DATA   AGE
coredns                              1      111m
extension-apiserver-authentication   6      111m
kube-proxy                           2      111m
kube-root-ca.crt                     1      30m
kubeadm-config                       2      111m
kubelet-config-1.18                  1      111m
kubelet-config-1.19                  1      63m
kubelet-config-1.20                  1      31m
kubelet-config-1.21                  1      18m
```

Not reproducible.

**Comment by neolit123** [comment]
Thanks @pacoxu for checking.
@ak2766 i will close this with the arguments above, but if have more evidence please provide it.

/closr

**Comment by ak2766** [comment]
@pacoxu - how many control plane nodes do you have?  I have done this multiple times and I always end up in the same situation.  I'm deploying my 10 node cluster using `kubeadm-config.yaml` file as follows:

`kubeadm init --config ${HOME}/etc/kubeadm-config.yaml --upload-certs | tee ${HOME}/init.log`

<details>
<summary>kubeadm-config.yaml</summary>

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.10.10.141
  bindPort: 6443
nodeRegistration:
  name: node1
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  criSocket: /var/run/containerd/containerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: cluster.local
etcd:
  external:
      endpoints:
      - https://10.10.10.141:2379
      - https://10.10.10.142:2379
      - https://10.10.10.143:2379
      caFile: /etc/ssl/etcd/ssl/ca.pem
      certFile: /etc/ssl/etcd/ssl/etcd.pem
      keyFile: /etc/ssl/etcd/ssl/etcd-key.pem
dns:
  type: CoreDNS
  imageRepository: docker.io/coredns
  imageTag: 1.7.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/16
  podSubnet: 10.233.0.0/16
controlPlaneEndpoint: k8slb.DOMAIN.com:6443
certificatesDir: /etc/kubernetes/ssl
imageRepository: k8s.gcr.io
useHyperKubeImage: False
apiServer:
  extraArgs:
    anonymous-auth: "True"
    authorization-mode: Node,RBAC
    bind-address: 0.0.0.0
    insecure-port: "0"
    apiserver-count: "3"
    endpoint-reconciler-type: lease
    service-node-port-range: 30000-32767
    kubelet-preferred-address-types: "InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP"
    profiling: "False"
    request-timeout: "1m0s"
    enable-aggregator-routing: "False"
    storage-backend: etcd3
    allow-privileged: "true"
    event-ttl: 1h0m0s
  extraVolumes:
  - name: usr-share-ca-certificates
    hostPath: /usr/share/ca-certificates
    mountPath: /usr/share/ca-certificates
    readOnly: true
  certSANs:
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster.local
  - 10.233.0.1
  - localhost
  - 127.0.0.1
  - node1
  - node2
  - node3
  - k8slb.DOMAIN.com
  - 10.10.10.30
  - 10.10.10.141
  - 10.10.10.142
  - 10.10.10.143
  - k8s-controller1
  - k8s-controller2
  - k8s-controller3
  timeoutForControlPlane: 5m0s
controllerManager:
  extraArgs:
    node-monitor-grace-period: 40s
    node-monitor-period: 5s
    pod-eviction-timeout: 5m0s
    node-cidr-mask-size: "24"
    profiling: "False"
    terminated-pod-gc-threshold: "12500"
    bind-address: 0.0.0.0
    configure-cloud-routes: "false"
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
clientConnection:
  acceptContentTypes: 
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: 
  qps: 5
clusterCIDR: 10.233.0.0/16
configSyncPeriod: 15m0s
conntrack:
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
enableProfiling: False
healthzBindAddress: 0.0.0.0:10256
hostnameOverride: node1
iptables:
  masqueradeAll: False
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  excludeCIDRs: []
  minSyncPeriod: 0s
  scheduler: rr
  syncPeriod: 30s
  strictARP: False
  tcpTimeout: 0s
  tcpFinTimeout: 0s
  udpTimeout: 0s
metricsBindAddress: 127.0.0.1:10249
mode: ipvs
nodePortAddresses: []
oomScoreAdj: -999
portRange: 
udpIdleTimeout: 250ms
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
- 10.96.0.10

```
</details>

Do you see anything in there that could be contributing to my dilemma?

I plagiarized the file from my `kubespray` deployed cluster and removed in it what seemed `kubespray` specific.  Maybe I removed too much or maybe I haven't removed enough.

During upgrade, I'm simply running this command after updating `kubeadm` to the version I want to upgrade to without reference to the config file:
`kubeadm upgrade apply -y v${applyver}`

Eager to resolve this one.
