### ISSUE TITLE
A StatefulSet does not respect fsGroup when creating a volume from a volumeClaimTemplate

### ISSUE THREAD

**Issue by victor-sudakov** [kubernetes/kubernetes#106806]
### What happened?

I create a StatefulSet with a spec.template.spec.securityContext.fsGroup=65534. The complete manifest can be found below. After the creation of a Pod, however, the volume mountpoint remains with "root:root 755" permissions.

### What did you expect to happen?

I expect the volume mountpoint to have "775 root:nobody" permissions.

### How can we reproduce it (as minimally and precisely as possible)?

Please apply the manifest below, shell into the prometheus-0 Pod and check the permissions on the /mygooddisk mountpoint. They will not belong to fsGroup.

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  serviceName: prometheus-headless
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: Always
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - image: prom/prometheus
          name: prometheus
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.config.file=/etc/prometheus/web.yml
            - --storage.tsdb.path=/mygooddisk
            - --web.console.libraries=/usr/share/prometheus
          volumeMounts:
            - mountPath: /etc/prometheus
              name: config
            - mountPath: /mygooddisk
              name: gooddisk
      volumes:
        - name: config
          configMap:
            name: prometheus-config
  volumeClaimTemplates:
    - metadata:
        name: gooddisk
      spec:  
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5G
```

### Anything else we need to know?

I'm ready to provide any additional info.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"2021-10-28T06:55:39Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
minikube version: v1.24.0
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

$ uname -a
Linux myws 5.14.18-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:24:59 UTC 2021 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by victor-sudakov** [comment]
After some experimenting I have a reason to believe that this permissions problem is minikube-specific.

Here is a simpler manifest to reproduce (permissions on /d01 remain root:root):

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ubuntu
  name: ubuntu
spec:
  replicas: 1
  serviceName: ubuntu-headless
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - image: ubuntu:jammy-20211122
          name: ubuntu
          command: ["/bin/sleep", "365d"]
          volumeMounts:
            - mountPath: /d01
              name: bigdisk
  volumeClaimTemplates:
    - metadata:
        name: bigdisk
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5G

```
