### ISSUE TITLE
kube-scheduler fail to start after upgrading to v1.23.0

### ISSUE THREAD

**Issue by leonanu** [kubernetes/kubernetes#106866]
### What happened?

kube-scheduler fail to start after upgrading from v1.22.4 to v1.23.0.

The kube-scheduler.service log shows:
`run.go:120] "command failed" err="[healthzBindAddress: Invalid value: \"0.0.0.0:10251\": must beempty or with an explicit 0 port, metricsBindAddress: Invalid value: \"0.0.0.0:10251\": must be empty or with an explicit 0 port]"`

My kube-scheduler.yaml is:
```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
clientConnection:
  burst: 200
  kubeconfig: "/etc/kubernetes/kube-scheduler.kubeconfig"
  qps: 100
enableContentionProfiling: false
enableProfiling: true
healthzBindAddress: 0.0.0.0:10251
leaderElection:
  leaderElect: true
metricsBindAddress: 0.0.0.0:10251
```

**But downgrade back to v1.22.4 it works well.**

### What did you expect to happen?

kube-scheduler service starts.

### How can we reproduce it (as minimally and precisely as possible)?

Start kube-scheduler v1.23.0 with kube-scheduler.yaml <kubescheduler.config.k8s.io/v1beta2> contains:
```
healthzBindAddress: 0.0.0.0:10251
etricsBindAddress: 0.0.0.0:10251
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None. Bare metal cluster.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux k8s 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:39 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
cni-plugins 1.0.1
CNI: calico 3.21.1
</details>
