### ISSUE TITLE
kubeletConfig - containerLogMaxSize not working 

### ISSUE THREAD

**Issue by lazarkrstic** [kubernetes/kubernetes#106855]
### What happened?

I created EKS using `eksctl` tool and than added a new node group. I am using `kubeletExtraConfig` for setting log maximum size of **500MB**, but it's not working. I still get only tail of container log. The size of returned log is 2.39MB.
Here is kubelet config
````JSON
{
    "kubeletconfig": {
        "enableServer": true,
        "syncFrequency": "1m0s",
        "fileCheckFrequency": "20s",
        "httpCheckFrequency": "20s",
        "address": "0.0.0.0",
        "port": 10250,
        "tlsCipherSuites": [
            "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
            "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
            "TLS_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_RSA_WITH_AES_128_GCM_SHA256"
        ],
        "serverTLSBootstrap": true,
        "authentication": {
            "x509": {
                "clientCAFile": "/etc/kubernetes/pki/ca.crt"
            },
            "webhook": {
                "enabled": true,
                "cacheTTL": "2m0s"
            },
            "anonymous": {
                "enabled": false
            }
        },
        "authorization": {
            "mode": "Webhook",
            "webhook": {
                "cacheAuthorizedTTL": "5m0s",
                "cacheUnauthorizedTTL": "30s"
            }
        },
        "registryPullQPS": 5,
        "registryBurst": 10,
        "eventRecordQPS": 5,
        "eventBurst": 10,
        "enableDebuggingHandlers": true,
        "healthzPort": 10248,
        "healthzBindAddress": "127.0.0.1",
        "oomScoreAdj": -999,
        "clusterDomain": "cluster.local",
        "clusterDNS": [
            "10.100.0.10"
        ],
        "streamingConnectionIdleTimeout": "4h0m0s",
        "nodeStatusUpdateFrequency": "10s",
        "nodeStatusReportFrequency": "5m0s",
        "nodeLeaseDurationSeconds": 40,
        "imageMinimumGCAge": "2m0s",
        "imageGCHighThresholdPercent": 85,
        "imageGCLowThresholdPercent": 80,
        "volumeStatsAggPeriod": "1m0s",
        "cgroupRoot": "/",
        "cgroupsPerQOS": true,
        "cgroupDriver": "cgroupfs",
        "cpuManagerPolicy": "none",
        "cpuManagerReconcilePeriod": "10s",
        "memoryManagerPolicy": "None",
        "topologyManagerPolicy": "none",
        "topologyManagerScope": "container",
        "runtimeRequestTimeout": "2m0s",
        "hairpinMode": "hairpin-veth",
        "maxPods": 35,
        "podPidsLimit": -1,
        "resolvConf": "/etc/resolv.conf",
        "cpuCFSQuota": true,
        "cpuCFSQuotaPeriod": "100ms",
        "nodeStatusMaxImages": 50,
        "maxOpenFiles": 1000000,
        "contentType": "application/vnd.kubernetes.protobuf",
        "kubeAPIQPS": 5,
        "kubeAPIBurst": 10,
        "serializeImagePulls": false,
        "evictionHard": {
            "memory.available": "100Mi",
            "nodefs.available": "10%",
            "nodefs.inodesFree": "5%"
        },
        "evictionPressureTransitionPeriod": "5m0s",
        "enableControllerAttachDetach": true,
        "protectKernelDefaults": true,
        "makeIPTablesUtilChains": true,
        "iptablesMasqueradeBit": 14,
        "iptablesDropBit": 15,
        "featureGates": {
            "RotateKubeletServerCertificate": true
        },
        "failSwapOn": true,
        "containerLogMaxSize": "500Mi",
        "containerLogMaxFiles": 5,
        "configMapAndSecretChangeDetectionStrategy": "Watch",
        "kubeReserved": {
            "cpu": "70m",
            "ephemeral-storage": "1Gi",
            "memory": "640Mi"
        },
        "enforceNodeAllocatable": [
            "pods"
        ],
        "volumePluginDir": "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/",
        "logging": {
            "format": "text"
        },
        "enableSystemLogHandler": true,
        "shutdownGracePeriod": "0s",
        "shutdownGracePeriodCriticalPods": "0s",
        "enableProfilingHandler": true,
        "enableDebugFlagsHandler": true
    }
}
```` 

### What did you expect to happen?

I expected to get full container log, not just log tail.

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce this problem create EKS with `eksctl` and add node group. 
````YAML
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <cluster-name>
  region: eu-central-1

nodeGroups:
  - name: worker-spot-large-log
    labels: { instance-type: spot }
    instanceType: t3.large
    minSize: 2
    maxSize: 30
    desiredCapacity: 2
    availabilityZones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
    kubeletExtraConfig:
        containerLogMaxSize: "500Mi"
        containerLogMaxFiles: 5
````
And then apply job (be avare of sheduling job to target node grop). I created demo docker image for genereating random data to stdout based on commnad `head -c $1 </dev/urandom`. Image is available at Docker Hub repo.
````YAML
apiVersion: batch/v1
kind: Job
metadata:
  name: log-large-data
spec:
  template:
    spec:
      containers:
      - name: log-large-data
        image: krstic94/generate-log
        args: ["10M"]
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1024m"
          limits:
            memory: "2Gi"
            cpu: "2048m"
      restartPolicy: Never
  backoffLimit: 4
````

### Anything else we need to know?

I was in contact with `eksctl` team, they comfirmed that configuration is ok, but k8s has an unexpected behaviour. Read more at [link](https://github.com/weaveworks/eksctl/issues/4518).

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Amazon EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
eksctl
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
` ps aux | grep container-runtime` to check if your kubelet is running with `--container-runtime=remote`.

```
     --container-log-max-size string                            <Warning: Beta feature> Set the maximum size (e.g. 10Mi) of container log file before it is rotated. This flag can only be used with --container-runtime=remote. (default "10Mi") (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)
      --container-runtime string                                 The container runtime to use. Possible values: 'docker', 'remote'. (default "docker")
```
If you are using docker by default, the containerLogMaxSize setting will be ignored.

**Comment by pacoxu** [comment]
I have two env which are installed by kubeadm. One is with contained and another on is with docker.

The node with contained below
```
[root@daocloud kube-apiserver]# ps aux | grep container-runtime
root       41903  2.8  0.7 2313988 128280 ?      Ssl  12月02 245:21 /usr/bin/kubelet -v 2 --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/var/run/containerd/containerd.sock --pod-infra-container-image=k8s-gcr.m.daocloud.io/pause:3.5 --logging-format=json
root     2422538  0.0  0.0  15252  2448 pts/0    S+   14:41   0:00 grep --color=auto container-runtime
[root@daocloud kube-apiserver]# cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint=/var/run/containerd/containerd.sock --pod-infra-container-image=k8s-gcr.m.daocloud.io/pause:3.5"
[root@daocloud kube-apiserver]#
8.0M -rw-r----- 1 root root 5.0M 12月  8 14:44 0.log
880K -rw-r--r-- 1 root root 879K 12月  8 14:41 0.log.20211208-143811.gz
716K -rw-r--r-- 1 root root 714K 12月  8 14:43 0.log.20211208-144101.gz
 11M -rw-r----- 1 root root  11M 12月  8 14:43 0.log.20211208-144331
```
**The log file is about 10MB(default value) each. And it will be compressed later.** 

The docker node below
```
[root@dce-10-7-177-9 ~]# ps aux | grep container-runtime
root      47443  0.0  0.0 112728   980 pts/0    S+   01:41   0:00 grep --color=auto container-runtime
[root@dce-10-7-177-9 ~]# cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS="--cgroup-driver=cgroupfs --network-plugin=cni --pod-infra-container-image=k8s-gcr.m.daocloud.io/pause:3.2"
```

**Comment by ehashman** [comment]
Can we please confirm if this is reproducible outside of EKS? If you are using a hosted provider, please file a support ticket with them first before coming upstream.

/triage needs-information

**Comment by lazarkrstic** [comment]
**SOLVED**
@pacoxu I changed `containerRuntime` to `containerd`  and now it's OK. I menaged to pull complete log from container. Here is `eksctl` configuration:
````YAML
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <cluster-name>
  region: eu-central-1

nodeGroups:
  - name: worker-spot-containerd-large-log
    labels: { instance-type: spot }
    instanceType: t3.large
    minSize: 2
    maxSize: 30
    desiredCapacity: 2
    amiFamily: AmazonLinux2
    containerRuntime: containerd
    availabilityZones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
    kubeletExtraConfig:
        containerLogMaxSize: "500Mi"
        containerLogMaxFiles: 5
````
