### ISSUE TITLE
kube-proxy from kubeadm default config using InCluster client

### ISSUE THREAD

**Issue by cuisongliu** [kubernetes/kubernetes#106993]
https://github.com/kubernetes/kubernetes/blob/ba200841fddcf8fb5edb413546ce9574f2a14d82/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L30

in kubeadm default kube-proxy config,using configmap config kubeconfig client connection kubernetes. why? we way not using InCluster mode connection to kubernetes apiserver . kubelet is write service env to pod .

**Comment by pacoxu** [comment]
I cannot understand the question. Would you add more details about what is expected? and what is the problem of current behavior? 

/kind support
BTW, the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
(stack overflow etc...)

**Comment by cuisongliu** [comment]
```
KubeProxyDaemonSet19 = `
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
    spec:
      priorityClassName: system-node-critical
      containers:
      - name: kube-proxy
        image: {{ .Image }}
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/kube-proxy
        - --hostname-override=$(NODE_NAME)
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
          readOnly: false
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      hostNetwork: true
      serviceAccountName: kube-proxy
      volumes:
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: lib-modules
        hostPath:
          path: /lib/modules
      tolerations:
      - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
`
```
I means remove kubeconfig config,using InCluster client . I don't know this way means is ??
