### ISSUE TITLE
Feature request: Support for "host-gateway" in "hostAliases"

### ISSUE THREAD

**Issue by devedse** [kubernetes/kubernetes#107079]
### What happened?

Output of `helm version`: `v3.6.3`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Local Docker Desktop for Windows with WSL

### Introduction

Our solution currently consists of quite a significant number of containers. Some of these containers expose API endpoints and we expose these externally.

The different container endpoints call each other through this external connection rather then the internal network traffic to be able to work/test with certificates. (We've mapped dev.coolproject.com to the developers machine's external IP: 192.168.2.123)

For example if container 1 needs some data from container 2 it would do:
https://dev.coolproject.com/container2api/blah

Since hostname resolving falls back to the Windows host running kubernetes it will actually redirect to 192.168.2.123 which is then redirected to the right container (container2).

The problem here is though that every time the developer machine's ip address changes we need to manually update the hosts file.

### Feature request

In docker it's possible to add hostAliases, apparently it's also possible now to add `host-gateway` to refer to the external ip address of the host running docker (See: https://github.com/docker/for-linux/issues/264#issuecomment-965465879)

Currently this doesn't seem to be possible in Helm though. I tried adding it to the Helm charts:
![image](https://user-images.githubusercontent.com/2350015/146372493-6b219c57-4ec4-4159-8412-4897cda2cc22.png)

But running this failed with the following error:

```
Error: UPGRADE FAILED: cannot patch "container2-api" with kind Deployment: Deployment.apps "container2-api" is invalid: spec.template.spec.hostAliases.ip: Invalid value: "host-gateway": must be valid IP address
```

Initially I thought this was a Helm problem but according to the response I got from the people there it's an error coming directly from Kubernetes. This is why I migrated this issue to the Kubernetes GitHub 😄 

### What did you expect to happen?

I expect `host-gateway` to redirect to the host external ip

### How can we reproduce it (as minimally and precisely as possible)?

See 'what happened'

### Anything else we need to know?

Nope, see 'what happened'

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Local Docker Desktop Environment
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Docker Desktop 4.2.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by pacoxu** [comment]
https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api 
Currently, we support exposing pod info to containers by env. `status.hostIP` is supported.

BTW, https://coredns.io/plugins/hosts/ Coredns also support customized hosts list.

**Comment by pacoxu** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: nginx:1.14.2
        env:
        - name: HOST_IP
          valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash","-c","echo $HOST_IP xxx.com >> /etc/hosts"]
#      hostAliases:  
#      - ip: "192.168.10.10" 
#        hostnames:
#        - "xxx.com"
```
I did an example like above.
```
[root@daocloud ~]# nerdctl exec -it  --namespace  k8s.io 43e831376f1e sh
# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.32.230.209	test-585fb7f9d4-szgq2
10.6.177.40 xxx.com
# exit
```
`10.6.177.40 xxx.com` is added to the `/etc/hosts`.
