### ISSUE TITLE
dry-run returns unwanted metadata fields

### ISSUE THREAD

**Issue by joejulian** [kubernetes/kubernetes#107086]
### What happened?

Running kubectl create with dry-run returns unwanted uid metadata field, as well as a generated name when using generateName.

This is inconsistent with the expectations as defined in [KEP 576](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/576-dry-run/README.md#generated-values) which states

```
The UID and the generated name would have a different value in a dry-run and non-dry-run creation. These values will be left empty when performing a dry-run.
```

### What did you expect to happen?

I expected uid, and a generated name to be empty when using the dry-run create option.

### How can we reproduce it (as minimally and precisely as possible)?

```
cat <<EOF > /tmp/d.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: foo-
spec:
  selector:
    matchLabels:
      test: foo
  template:
    metadata:
      labels:
        test: foo
    spec:
      containers:
        - command:
            - sleep
            - inf
          image: busybox:latest
          name: sleeper
EOF

kubectl create -f /tmp/d.yaml --dry-run=server -o yaml
```

Expected metadata:
```
metadata:
  creationTimestamp: "2021-12-16T21:24:32Z"
  generateName: foo-
  generation: 1
  namespace: default
```

Actual metadata:
```
metadata:
  creationTimestamp: "2021-12-16T21:24:32Z"
  generateName: foo-
  generation: 1
  name: foo-f8jql
  namespace: default
  uid: 3d26f113-01a0-491a-a4e4-4b77f8be5ce1
```

### Kubernetes version

<details>
I've tested this from 1.19.0 through 1.23.0
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
