### ISSUE TITLE
In multi-container pod, container statuses do not update after prestop hook starts on any container

### ISSUE THREAD

**Issue by declanlong** [kubernetes/kubernetes#107183]
### What happened?

In a multi container pod, when one of the containers defines a prestop hook. No container statuses update when prestop hook starts. 

I aim to create a simple golang client which would run as prestop hook, the client checks the status of other containers in pod via api server allowing containers to shutdown in order in a multi container pod.  

**Note:** To simplify this I have replicated behaviour in kind

Using the following pod 
```
apiVersion: v1
kind: Pod
metadata:
  name: testprestop
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 600
  containers:
  - name: webserver
    image: memcached
  - name: sidecartest
    image: gss-client:local-dev
    lifecycle:
      preStop:
        exec:
          command: ["/usr/local/bin/graceful-shutdown-service"]
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
```

### What did you expect to happen?

In the above pod spec I expect
- `webserver`: Terminates on receiving sigterm 
- `sidecartest`: Prestop hook starts and  golang client can retrieve termination status of webserver.
- even though `webserver` container does terminate, status is not updated.

### How can we reproduce it (as minimally and precisely as possible)?

This can be reproduced using sleep in prestop hook. 

- Create the following pod
```
apiVersion: v1
kind: Pod
metadata:
  name: testprestop
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 600
  containers:
  - name: webserver
    image: memcached
  - name: sidecartest
    image: nginx
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 400"]
```
- Delete pod  `kubectl delete po testprestop`
- Notice webserver container received termination signal
```
$kubectl logs testprestop -f webserver
Signal handled: Terminated.
```
- container is not present on node but status has not updated
```console
$crictl ps | grep web

$kubectl get po
NAME          READY   STATUS        RESTARTS   AGE
testprestop   2/2     Terminating   0          3m35s
```

### Kubernetes version

<details>

```console
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A - kind
</details>

### OS version

<details>

```console
sw_vers
ProductName:	macOS
ProductVersion:	11.6.2
BuildVersion:	20G314
```

</details>

### Install tools

<details>
kind
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.5.2
RuntimeApiVersion:  v1alpha2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
