### ISSUE TITLE
podAntiAffinity not working as expected 

### ISSUE THREAD

**Issue by mrad-bilel** [kubernetes/kubernetes#107161]
### What happened?

podAntiAffinity not working as expected 

### What did you expect to happen?

my applications will not be deployd on the same node 

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  generateName: zammad-prod-
  labels:
    app.kubernetes.io/instance: zammad-prod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zammad
    app.kubernetes.io/version: 3.6.0
    statefulset.kubernetes.io/pod-name: zammad-prod-0
```

here is my podAntiAffinity  configuration

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1    
  template:
    metadata:
      labels:
        app: test
    spec:
      affinity:
        podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: statefulset.kubernetes.io/pod-name
                operator: In
                values:
                - zammad-prod-0
            topologyKey: kubernetes.io/hostname
```

Here my 2 apps are deployed on the same node

```
 k get po -o wide
NAME                        READY   STATUS    RESTARTS   AGE   IP              NODE                                         NOMINATED NODE   READINESS GATES

test-67db7ccb58-sjjc5   1/1     Running   0          14h   10.24.182.122   ip-10-24-160-34.eu-west-3.compute.internal   <none>           <none>
```
```
 k get po -o wide
NAME                                     READY   STATUS    RESTARTS   AGE   IP              NODE                                          NOMINATED NODE   READINESS GATES
zammad-prod-0                            4/4     Running   0          40d   10.24.160.178   ip-10-24-160-34.eu-west-3.compute.internal    <none>           <none>
```

### Kubernetes version

```console
$ kubectl version  
# v1.18.20
```

### Cloud provider

```
AWS EKS
```

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
