### ISSUE TITLE
Graceful Node Shutdown does nothing on reboot

### ISSUE THREAD

**Issue by danisafta** [kubernetes/kubernetes#107158]
### What happened?

After I have configured Graceful Shutdown in the k8s cluster, I was expecting to see in the pods SIGTERM when a node reboots and preStop hook to run.

### What did you expect to happen?

Expected the pod to log that it received a SIGTERM when node-1 rebooted.

### How can we reproduce it (as minimally and precisely as possible)?

1. Configure the following parameters for kubelet on both nodes on 2-node k8s cluster:
```
shutdownGracePeriod: 30s
shutdownGracePeriodCriticalPods: 10s
```
2. Checked on both nodes that systemd-inhibitors are configured:

```
# systemd-inhibit --list
     Who: kubelet (UID 0/root, PID 94920/kubelet)
    What: shutdown
     Why: Kubelet needs time to handle node shutdown
    Mode: delay

1 inhibitors listed.
```
3. Apply the deployment file(displayed at the bottom of the section) on the cluster with a nodeSelector that will choose node-1 as the node for the signal handler to run:
```
NAME                                 READY   STATUS    RESTARTS   AGE   IP               NODE           NOMINATED NODE   READINESS GATES
signal-deployment-5f48bbb874-l5gq7   1/1     Running   0          75m   <ip>           node-1           <none>           <none>

```
4. Go to node-1 and execute # systemctl reboot 
5. When running ```# kubectl logs -f signal-deployment-5f48bbb874-l5gq7``` it should log that a  SIGTERM  was received

This is the deployment file I used to test if the pods are receiving SIGTERM:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal-deployment
  labels:
    app: signal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal
  template:
    metadata:
      labels:
        app: signal
    spec:
      containers:
      - name: signal
        image: saftone1/signal
        lifecycle:
          preStop:
            exec:
              command: ['/bin/sh', 'echo EXECUTED']
      nodeSelector:
        signal-target: enabled
```

### Anything else we need to know?

-

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"archive", BuildDate:"2021-12-09T02:27:23Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

-

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
NAME="CentOS Linux"
VERSION="7 (Core)"

$ uname -a
# paste output here
Linux hostname 5.10.74-200.1805.tis.el7.x86_64 #1 SMP PREEMPT Wed Dec 8 21:04:25 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
</details>


### Install tools

not relevant

### Container runtime (CRI) and and version (if applicable)

<details>
containerd v1.4.6
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

not relevant
