### ISSUE TITLE
kube-proxy: CLI arguments is ignored even the options are not specified in the config file

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#107156]
### What happened?

Start `kube-proxy` service with a config file without specifying the argument in the config file, instead, pass the value via the CLI args, the value is just ignored, for example,

I have a config file ```config.conf``` as this,

```

apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
bindAddressHardFail: false
clientConnection:
  acceptContentTypes: ""
  burst: 0
  contentType: ""
  kubeconfig: /etc/kubernetes/admin.conf
  qps: 0
clusterCIDR: 10.244.0.0/16
configSyncPeriod: 0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 0s
  syncPeriod: 0s
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 0s
  tcpFinTimeout: 0s
  tcpTimeout: 0s
  udpTimeout: 0s
kind: KubeProxyConfiguration
metricsBindAddress: ""
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
showHiddenMetricsForVersion: ""
udpIdleTimeout: 0s
winkernel:
  enableDSR: false
  networkName: ""
  sourceVip: ""
```

NOTE: I have not specified the `mode` in the config file, but give a value for the `mode` via the CLI, 

```go run ./proxy.go --config=./config.conf --proxy-mode=userspace```

the proxy mode is still set as `iptables` after the service is started.

### What did you expect to happen?

The reason for this is that CLI args is parsed before the loading of the config file, if the config file haven't specified the `mode` or leave it as empty, then it will be use the default value `iptables` instead.

https://github.com/kubernetes/kubernetes/blob/4cd6db046fd26bc7155d0ff59ad07babb934187d/cmd/kube-proxy/app/server_others.go#L552-L563

Two choices from my side, 

- Add a note somewhere, maybe where the option is defined, just say that the CLI args will be ignored when the config file is provided regardless the option is specified in the config file or not (this should be noted for lots of options).
- Merge the value passed from CLI with the config file if the option has an empty value, but we need to consider the backward compatibility.

### How can we reproduce it (as minimally and precisely as possible)?

```go run ./proxy.go -- --config=./config.conf --proxy-mode=userspace```

and check which mode is effective.

### Kubernetes version

```console
$ kubectl version

master branch
```

### Cloud provider

vanilla deployment with code in the upstream.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
