### ISSUE TITLE
The error message of portname valid syntax is wrong

### ISSUE THREAD

**Issue by Ranler** [kubernetes/kubernetes#107212]
### What happened?

https://github.com/kubernetes/kubernetes/blob/65ac7f09ec36736f1282adf876f54b665a35d750/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L318-L346

The `portNameOneLetterRegexp` only support at least one letter，but the error message is  at least one letter or number.
It will be error if portname only numbers, ex: '1-2' or '1' or '123'.

### What did you expect to happen?

Fix the error message or regex syntax

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: test
    workload-type: deployments
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
      workload-type: deployments
  template:
    metadata:
      labels:
        app: test
        workload-type: deployments
    spec:
      containers:
        - name: container123
          image: nginx
          ports:
            - name: 1-2   # < here
              protocol: TCP
              containerPort: 80
```

### Kubernetes version

at least 1.19+

### Cloud provider

None

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
