### ISSUE TITLE
Unable to route traffic to nginx webserver via nginx ingress

### ISSUE THREAD

**Issue by MuhammadMunir12** [kubernetes/kubernetes#107287]
### What happened?

I am trying to run the nginx ingress controller and nginx web server with custom configurations. For this I have created configmaps, deployment, exposed it as service of type node port, created a relevant route and ingress rule as well for both (ingress and web server). I can curl the static content for ingress and web server on their respective **worker node's ip:port**. 
I want to redirect the traffic coming to ingress over port 443 that'll forward the traffic towards backend webserver running in another worker node.

External traffic (outside cluster) <--------------> ingress (running on worker 1)<------------> Web server (running on worker 2)

The Yaml files i've created are given below: 
### Config map for ingress 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx-ingress
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  auto;
    worker_rlimit_nofile 10240;
    worker_cpu_affinity 1;
    error_log  /dev/null; #/var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  10240;
    }


    http {
            #include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /dev/null; #/var/log/nginx/access.log  main;
        #ssl on;
        sendfile        on;
     #   tcp_nopush     on;
        #keepalive_timeout  65;
        keepalive_timeout  300s;
        keepalive_requests 1000000;
        #gzip  on;

        include /etc/nginx/conf.d/default.conf;


        # kill cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'private no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;

    }

  default.conf: |-
    # file mounted externally
    upstream backend {
        server nginx-ws; # service name

    }
    server {
       listen       80;
       server_name  localhost;

       listen 443 ssl default_server;
       listen [::]:443 ssl default_server;

       ssl_certificate /etc/letsencrypt/server.crt;
       ssl_certificate_key /etc/letsencrypt/server.key;
       ssl_trusted_certificate /etc/letsencrypt/rootCA.pem;

       #root /usr/share/nginx/html;
       #index index.html index.htm;
       # till here
       location / {
           proxy_pass http://backend;
               #root   /usr/share/nginx/html;
               #index  index.html index.htm;
         }

         #error_page  404              /404.html;

         #error_page   500 502 503 504  /50x.html;
         #location = /50x.html {
         # root   /usr/share/nginx/html;
         #}

      }
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Welcome to nginx!</h1>
    <p>If you see this page, the nginx web server is successfully installed and
    working. Further configuration is required.</p>

    <p>For online documentation and support please refer to
    <a href="http://nginx.org/">nginx.org</a>.<br/>
    Commercial support is available at
    <a href="http://nginx.com/">nginx.com</a>.</p>

    <p><em> Thank you for using nginx. Response from ingress/proxy.</em></p>
    </body>
    </html>

``` 
### Deployment for ingress
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-ingress
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        compute1: worker1
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: default.conf
              path: default.conf
            - key: index.html
              path: index.html
      - name: ca-pem
        configMap:
          name: ca-pem
      - name: ca-crt
        configMap:
          name: ca-crt
      - name: ca-key
        configMap:
          name: ca-key
      containers:
      - name: nginx-alpine-perl
        image: docker.io/library/nginx@sha256:51212c2cc0070084b2061106d5711df55e8aedfc6091c6f96fabeff3e083f355
        ports:
        - containerPort: 80
        - containerPort: 443
        securityContext:
          allowPrivilegeEscalation: false
          #runAsUser: 0
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx
            #subPath: nginx.conf
            readOnly: true
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: nginx-conf
            mountPath: /usr/share/nginx/html
            #subPath: nginx.conf
            readOnly: true
          - name: nginx-conf
            mountPath: /etc/nginx/
            #subPath: nginx.conf
            readOnly: true
          - name: ca-pem
            mountPath: /etc/letsencrypt/rootCA.pem
            subPath: rootCA.pem
            readOnly: false
          - name: ca-crt
            mountPath: /etc/letsencrypt/server.crt
            subPath: server.crt
            readOnly: false
          - name: ca-key
            mountPath: /etc/letsencrypt/server.key
            subPath: server.key
            readOnly: true

```

### Service for ingress
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
 type: NodePort 
 ports:
 - port: 80
   name: http
   #protocol: TCP
   targetPort: 80
   nodePort: 30008
 - port: 443
   name: https
   #protocol: TCP
   targetPort: 443
   nodePort: 30009
 selector:
   app: nginx

```
### Route for ingress 
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  name: nginx-ingress
  namespace: nginx-ingress
  selfLink: /apis/route.openshift.io/v1/namespaces/nginx-ingress/routes/nginx-ingress
spec:
  host: nginx-ingress.example.com
  to:
    kind: Service
    name: nginx
    weight: 100
  wildcardPolicy: None

```

### Ingress rule for ingress 
```
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx # use only with k8s version >= 1.18.0
  tls:
  - hosts:
      - nginx-ingress.example.com
    secretName: testsecret-tls
  rules:
  - host: nginx-ingress.example.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          serviceName: nginx
          servicePort: 80

```

The configs for web server are almost identical and it's exposed as service as well. 
### configmap for webserver 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-ws
  namespace: nginx-ingress
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  auto;
    worker_rlimit_nofile 10240;
    error_log  /dev/null; #/var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  10240;
    }


    http {
            #include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /dev/null; #/var/log/nginx/access.log  main;
        #ssl on;
        sendfile        on;
     #   tcp_nopush     on;
        #keepalive_timeout  65;
        keepalive_timeout  300s;
        keepalive_requests 1000000;
        #gzip  on;

        include /etc/nginx/conf.d/default.conf;


        # kill cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'private no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;

    }

  default.conf: |-
    # file mounted externally
    server {
       listen       80;
       server_name  localhost;
       #location / {
       #    root   /usr/share/nginx/bin;
       #  }

         #root /usr/share/nginx/html;
         #index index.html index.htm;
       # till here
       location / {
           root   /usr/share/nginx/html;
           index  index.html index.htm;
         }

       error_page  404              /404.html;

       error_page   500 502 503 504  /50x.html;
       location = /50x.html {
           root   /usr/share/nginx/html;
       }

      }
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Welcome to nginx!</h1>
    <p>If you see this page, the nginx web server is successfully installed and
    working. Further configuration is required.</p>

    <p>For online documentation and support please refer to
    <a href="http://nginx.org/">nginx.org</a>.<br/>
    Commercial support is available at
    <a href="http://nginx.com/">nginx.com</a>.</p>

    <p><em>Hello. Thank you for using nginx. Response from webserver.</em></p>
    </body>
    </html>

```

### Deployment for web server 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-ws
  namespace: nginx-ingress
spec:
  selector:
    matchLabels:
      app: nginx-ws
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-ws
    spec:
      nodeSelector:
        compute2: worker2
      securityContext: {}
      volumes:
      - name: nginx-conf-ws
        configMap:
          name: nginx-conf-ws
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: default.conf
              path: default.conf
            - key: index.html
              path: index.html      
      containers:
      - name: nginx-alpine-perl
        image: docker.io/library/nginx@sha256:51212c2cc0070084b2061106d5711df55e8aedfc6091c6f96fabeff3e083f355
        ports:
        - containerPort: 80
        - containerPort: 443
        securityContext:
          allowPrivilegeEscalation: false
          #runAsUser: 0
        volumeMounts:
          - name: nginx-conf-ws
            mountPath: /etc/nginx
            #subPath: nginx.conf
            readOnly: true
          - name: nginx-conf-ws
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: nginx-conf-ws
            mountPath: /usr/share/nginx/html
            #subPath: nginx.conf
            readOnly: true
          - name: nginx-conf-ws
            mountPath: /etc/nginx/
            #subPath: nginx.conf
            readOnly: true
         
```

The webserver is exposed as node port with name **nginx-ws**. 

### What did you expect to happen?

When I curl or access the ingress on node port it should display the static content for web server.
Am I missing some thing in configurations??

### How can we reproduce it (as minimally and precisely as possible)?

The details are mentioned above. 

### Anything else we need to know?

Besides running this in openshift as well. But facing same issue. 

### Kubernetes version

<details>

```console
$ kubectl version
v1.19.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Redhat core os 4.6 
$ uname -a
4.18.0-193.68.1.el8_2.x86_64

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Podman

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
