### ISSUE TITLE
Kubelet not reporting metrics for generic ephemeral volumes

### ISSUE THREAD

**Issue by fhke** [kubernetes/kubernetes#107218]
### What happened?

We created a pod with a generic ephemeral volume:

```yaml
- ephemeral:                     
    volumeClaimTemplate:         
      metadata:                  
        creationTimestamp: null  
      spec:                      
        accessModes:             
        - ReadWriteOnce          
        resources:               
          requests:              
            storage: 20Gi        
        storageClassName: slow   
        volumeMode: Filesystem   
  name: tmp-aggregator
```

Volume level metrics like `kubelet_volume_stats_capacity_bytes` are not being reported for this volume:

```console
$ curl -s localhost:10255/metrics | grep -c 'kubelet_volume_stats_capacity_bytes.*tmp-aggregator'
0
```

### What did you expect to happen?

I expected volume level metrics to be exposed for this volume in the same way as other persistent volumes from the same CSI provisioner.

### How can we reproduce it (as minimally and precisely as possible)?

* Create a pod using a generic ephemeral volume for storage
* Check the kubelet volume-level metrics 

### Kubernetes version

```console
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud provider

N/A

### OS version

```console
$ uname -a
Linux 5.14.9-200.fc34.x86_64 #1 SMP Thu Sep 30 11:55:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Install tools

N/A

### Container runtime (CRI) and and version (if applicable)

```console
$ containerd --version
containerd github.com/containerd/containerd 1.5.5
```

### Related plugins (CNI, CSI, ...) and versions (if applicable)

CSI: NetApp Trident v21.07.2

**Comment by pacoxu** [comment]
I checked my env and cannot reproduce the problem. 
Can you give an example to reproduce it step by step(So I can dig into it)? 

The logic of this metric is in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/metrics/collectors/volume_stats.go#L91-L126.

**Comment by fhke** [comment]
Hi @pacoxu,

Steps to reproduce:

1. Create a pod with a generic ephemeral volume:

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: generic-ephemeral-test
spec:
  containers:
    - name: busybox
      image: busybox:latest
      volumeMounts:
      - mountPath: "/scratch"
        name: scratch-volume
      command:
      - sh
      - -c
      - |
        while sleep 1; do
          date >> /scratch/out.log
        done
  volumes:
    - name: scratch-volume
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "slow"
            resources:
              requests:
                storage: 1Gi
```
2. Create a pod using a normal persistent volume:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-test-1
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: pv-test-1
spec:
  containers:
    - name: busybox
      image: busybox:latest
      volumeMounts:
      - mountPath: "/scratch"
        name: scratch-volume
      command:
      - sh
      - -c
      - |
        while sleep 1; do
          date >> /scratch/out.log
        done
  volumes:
    - name: scratch-volume
      persistentVolumeClaim:
        claimName: pv-test-1
```

3. SSH onto the respective node(s) the pods are scheduled on and check the `kubelet_volume_*` metrics from the kubelet metrics endpoint:

*persistent volume*
```sh
$ curl -s localhost:10255/metrics | grep '^kubelet_volume_.*pv-test-1'
kubelet_volume_stats_available_bytes{namespace="fhk-test",persistentvolumeclaim="pv-test-1"} 1.00388864e+09
kubelet_volume_stats_capacity_bytes{namespace="fhk-test",persistentvolumeclaim="pv-test-1"} 1.02330368e+09
kubelet_volume_stats_inodes{namespace="fhk-test",persistentvolumeclaim="pv-test-1"} 65536
kubelet_volume_stats_inodes_free{namespace="fhk-test",persistentvolumeclaim="pv-test-1"} 65524
kubelet_volume_stats_inodes_used{namespace="fhk-test",persistentvolumeclaim="pv-test-1"} 12
kubelet_volume_stats_used_bytes{namespace="fhk-test",persistentvolumeclaim="pv-test-1"} 2.637824e+06
```

*generic ephemeral volume*
```sh
$ curl -s localhost:10255/metrics  | grep -c '^kubelet_volume_.*pvc-'
0
```
