### ISSUE TITLE
pod pending in case of scheduler leader election

### ISSUE THREAD

**Issue by xrmzju** [kubernetes/kubernetes#107262]
### What happened?

1. create a statefulset with 3 replicas with `podManagementPolicy: Parallel`, each pod claimed a localpv(dynamic provisioning), pod spread by host with maxSkew=1
2.  2 pods got scheduled, 1 remains pending, and 2 of 3 local pvs got scheduled to the same node 

### What did you expect to happen?

all pods scheduled successfully

### How can we reproduce it (as minimally and precisely as possible)?

1. create a statefulset with 3 replicas with `podManagementPolicy: Parallel`, each pod claimed a localpv(dynamic provisioning), pod spread by host with maxSkew=1
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-app
spec:
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sample-app
    spec:
      containers:
      - name: app
        image: registry.com/sample-app
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /data
          name: data
          readOnly: true
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: sample-app
        maxSkew: 1
        topologyKey: kubernetes/hostname
        whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sample-app
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100G
      storageClassName: local-pv
      volumeMode: Filesystem
```
2.  `pod0, pod1, pod2` created parallell by controller, scheduler start to schedule pods in uncertain order,  assume scheduler watch `pod0` create event first, after `pod-0` get scheduled to `node0`, scheduler start to schedule `pod-1`, after `data-pvc-1` patched with selected-node annotation to node-1,  and `pod-1` was still in pending state(in binding cycle but bind pod api not send yet), scheduler got leader lost somehow. The new leader may probably start schedule `pod-2` first,  `pod-2` was scheduled to `node-1`（ the spreadTopologyConstraint can not prevent `pod-2` choose `node-1`  because `pod-1` still in  pending state ）, `pod-1` remains in pending state cause the volumebinding plugin restrict `pod-1` goes to `node-1` but spreadTopologyConstraint otherwise.

### Kubernetes version

v1.18
