### ISSUE TITLE
How much data can be stored in a CR？ where does this limit come from, and for what purpose？

### ISSUE THREAD

**Issue by kadisi** [kubernetes/kubernetes#107233]
I defined a very simple CRD object： such as:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: summaries.test.io
spec:
  group: lite.test.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            data:
              type: string

  scope: Namespaced
  names:
    plural: summaries
    singular: summary
    kind: Summary
    shortNames:
    - sum
```

CR is as follows：

```
apiVersion: "test.io/v1alpha1"
kind: Summary
metadata:
  name: cluster
  namespace: infedge
data:
```

After testing, it is found that a CR stores a maximum of 3145728 (3M) of data。 

Excuse me, where are the restrictions here? 

For what purpose should size be limited?

Can we raise the limit？
