### ISSUE TITLE
Job didn't delete pods when I changed the activeDeadlineSeconds

### ISSUE THREAD

**Issue by Lantern-r** [kubernetes/kubernetes#107387]
### What happened?

Job didn't delete pods when I changed the activeDeadlineSeconds

```
➜  job  cat nc-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: nc-job
spec:
  activeDeadlineSeconds: 30
  ttlSecondsAfterFinished: 0
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nc-demo
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo 1|nc -l -p 9998"]
        ports:
        - containerPort: 9998
          protocol: TCP
      restartPolicy: Never
```

if I changed the activeDeadlineSeconds, job will not stop

```
➜  job kubectl describe job nc-job
Name:                     nc-job
Namespace:                default
Selector:                 controller-uid=cb97911b-e8c3-4f3e-bff7-c4b8955ce470
Labels:                   controller-uid=cb97911b-e8c3-4f3e-bff7-c4b8955ce470
                          job-name=nc-job
Annotations:              batch.kubernetes.io/job-tracking:
Parallelism:              1
Completions:              1
Completion Mode:          NonIndexed
Start Time:               Thu, 06 Jan 2022 13:49:11 +0000
Active Deadline Seconds:  31s
Pods Statuses:            1 Active / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  controller-uid=cb97911b-e8c3-4f3e-bff7-c4b8955ce470
           job-name=nc-job
  Containers:
   nc-demo:
    Image:      busybox
    Port:       9998/TCP
    Host Port:  0/TCP
    Command:
      /bin/sh
    Args:
      -c
      echo 1|nc -l -p 9998
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From            Message
  ----    ------            ----  ----            -------
  Normal  SuccessfulCreate  13m   job-controller  Created pod: nc-job-r8nrh
```

### What did you expect to happen?

Prolong the time of the job by changing the activeDeadlineSeconds

### How can we reproduce it (as minimally and precisely as possible)?

 chang the activeDeadlineSeconds before job stops

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
➜  job uname -a
Linux lantern 4.15.0-166-generic #174-Ubuntu SMP Wed Dec 8 19:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
