### ISSUE TITLE
Admission registration performs webhook rules expansion modifying object on apply

### ISSUE THREAD

**Issue by mbrancato** [kubernetes/kubernetes#107318]
### What happened?

When applying a `MutatingWebhookConfiguration`, the `.webhooks[].rules[]` array is being expanded by the `.webhooks[].rules[].apiVersions[]` values. This is causing configuration drift as the object that is in the manifest is different than the object stored by Kubernetes.

This results in the object always being modified and tools like Flux always think the object has changed:

```
% kubectl apply -f example.yaml
mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.domainmapping.serving.knative.dev configured
% kubectl apply -f example.yaml
mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.domainmapping.serving.knative.dev configured
```

So applying a config like this:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration

webhooks:
  - admissionReviewVersions: [ "v1", "v1beta1" ]
    clientConfig:
      service:
        name: domainmapping-webhook
        namespace: knative-serving
    failurePolicy: Fail
    sideEffects: None
    name: webhook.domainmapping.serving.knative.dev
    timeoutSeconds: 10
    rules:
      - apiGroups:
          - serving.knative.dev
        apiVersions:
          - v1alpha1
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        scope: "*"
        resources:
          - domainmappings
```

Then reading the object back, results in this:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
webhooks:
  - rules:
      - apiGroups:
          - serving.knative.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - domainmappings
          - domainmappings/status
        scope: '*'
      - apiGroups:
          - serving.knative.dev
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - domainmappings
          - domainmappings/status
        scope: '*'
```

### What did you expect to happen?

The object may be modified, fields added, but defined fields should either stay the same structure or fail validation at apply.

### How can we reproduce it (as minimally and precisely as possible)?

Apply an object like this:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration

webhooks:
  - admissionReviewVersions: [ "v1", "v1beta1" ]
    clientConfig:
      service:
        name: domainmapping-webhook
        namespace: knative-serving
    failurePolicy: Fail
    sideEffects: None
    name: webhook.domainmapping.serving.knative.dev
    timeoutSeconds: 10
    rules:
      - apiGroups:
          - serving.knative.dev
        apiVersions:
          - v1alpha1
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        scope: "*"
        resources:
          - domainmappings
```

Full example: https://github.com/knative/serving/blob/92b5a121d19ca0d9f4aa0c73da3b20e30a5e8a62/config/core/webhooks/domainmapping-defaulting.yaml

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.14-gke.1900", GitCommit:"abc4e63ae76afef74b341d2dba1892471781604f", GitTreeState:"clean", BuildDate:"2021-09-07T09:21:04Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mbrancato** [comment]
After some testing, this is also expanding by the `.webhooks[].rules[].apiGroups[]` and when `.webhooks[].rules[].apiVersions[]` is the wildcard `"*"` - it is expanding the wildcard into the actual versions and not storing the wildcard in the object config.

So if there are 4 values in `apiGroups` and 2 values in `apiVersions`, the single rule will turn into 8 rules.
Additionally,  the wildcard is used, it will be used and then expanded as well.

**Comment by liggitt** [comment]
I can't reproduce this. After applying the webhook in the description, I see this output when fetching it:

```
...
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: domainmapping-webhook
      namespace: knative-serving
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: webhook.domainmapping.serving.knative.dev
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - serving.knative.dev
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - domainmappings
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
```
