### ISSUE TITLE
sessionAffinity TTL expiration not working for Winuserspace

### ISSUE THREAD

**Issue by knabben** [kubernetes/kubernetes#107398]
### What happened?

On `Kube-proxy 1.22` on `winuserspace` with a `NodePort` service I have 2 pods behind the service with `sessionAffinity: clientIP ` and `timeoutSeconds` set. 

When doing a request from a source to the NodePort multiple times, the sessionAffinity works as expected. And one of the pod receives all the load.

The issues resides on after 10 seconds (the TTL set in the spec) the cached sessionAffinity DO NOT expires and the round-robin for the next pod fails, keeping the affinity after the expiration TTL.

Service example:

```
spec:
  ports:
  - name: http
    nodePort: 31279
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10
  type: NodePort
```

### What did you expect to happen?

After the TTL to the load be balanced across the existent pods.

### How can we reproduce it (as minimally and precisely as possible)?

Set two pods behind the service, agnhost is listening on port 80.

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    session-affinity: true
  name: pod-[1|2]
  namespace: default
spec:
  containers:
  - command:
    - /agnhost
    - serve-hostname
    - --tcp
    - --http=false
    - --port
    - "80"
    image: k8s.gcr.io/e2e-test-images/agnhost:2.31
    imagePullPolicy: IfNotPresent
    name: cont-80-tcp
    ports:
    - containerPort: 80
      name: serve-80-tcp
      protocol: TCP
```

From outside the cluster request the node port (mid panel with `date` print), in this case `10.90.1.1` on `31279`

```
> while true; do curl http://10.90.1.1:31279 2> /dev/null; sleep 1; date; done
```

![image](https://user-images.githubusercontent.com/1223213/148475053-eef041f3-b469-4884-ba37-e73b5123aa8e.png)

In the image the first panel have `pod-1` logs -f and the last panel `pod-2`, as noted even after 10 seconds the balancing does not happen and the clientIP affinity IS NOT expired.

UPDATE: This is still true (and the expected behavior) if we `s/sleep 1/sleep 10` and try again only after the TTL expiration.

### Kubernetes version

<details>

```console
$ kubectl version
"v1.22.3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
...
 Microsoft Windows Server 2019 Standard
...
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
