### ISSUE TITLE
Kubernetes ingress not able to reference a secret that is in another different namespace

### ISSUE THREAD

**Issue by Mangaal** [kubernetes/kubernetes#107495]
### What happened?

I was trying to used a secret which I have created in another namespace but I got error when I try to curl the host

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: sample-ingress
  namespace: test-ns  
spec:
  tls:
  - hosts:
      - example.mangaal.com
    secretName: ca-crt-secret
  rules:
  - host: example.mangaal.com
    http:
      paths:
      - path: /hello
        backend:
          serviceName: golang-api-service-web
          servicePort: 8080

```
here is the Error I got when i try to curl was "ssl_error_syscall"

### What did you expect to happen?

I think  ingress should be able to reference a secret that is in another different namespace

### How can we reproduce it (as minimally and precisely as possible)?

Either in annotation or in tls spec of an ingress we should be able to declare from which nameSpace we want to use the secret from.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
kubectl version --short
 client version :1.20.0
 control plane version :1.20.0

</details>

### Cloud provider

<details>
bare metal machines
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
