### ISSUE TITLE
remove use of github.com/imdario/mergo (currently use is incompatible with latest mergo version, latest mergo version introduces bugs)

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#107499]
### What happened?

client-go behavior changes depending on version of github.com/imdario/mergo used. Kubernetes pins to `v0.3.5`. Many other projects in the ecosystem, including Kubernetes projects like sigs.k8s.io/controller-runtime, use newer versions like `0.3.12`.

If a consumer of client-go is not careful, they will very likely automatically use `mergo`. This will subtly give different behavior than client-go declares. Users of client-go must therefor use a `replace` for mergo (if they care about this issue), which also implies all downstream consumers must do the same and `go install` will not work.

### What did you expect to happen?

client-go behavior is the same regardless of mergo version.

### How can we reproduce it (as minimally and precisely as possible)?

```go
package kube

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"k8s.io/client-go/tools/clientcmd"
)

func TestMergo(t *testing.T) {
	config1, err := mkKubeConfig("1.1.1.1", "3.3.3.3")
	if err != nil {
		t.Fatalf("Failed to create a sample kubernetes config file. Err: %v", err)
	}
	defer os.RemoveAll(filepath.Dir(config1))
	config2, err := mkKubeConfig("2.2.2.2", "4.4.4.4")
	if err != nil {
		t.Fatalf("Failed to create a sample kubernetes config file. Err: %v", err)
	}
	defer os.RemoveAll(filepath.Dir(config2))

	if err := os.Setenv("KUBECONFIG", config1+":"+config2); err != nil {
		t.Fatalf("Failed to set KUBECONFIG environment variable")
	}

	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
	loadingRules.DefaultClientConfig = &clientcmd.DefaultClientConfig
	configOverrides := &clientcmd.ConfigOverrides{
		ClusterDefaults: clientcmd.ClusterDefaults,
	}

	//resp, err := BuildClientConfig("", "")
	resp, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides).ClientConfig()
	if err != nil {
		t.Fatal(err)
	}
	wantHost := "https://1.1.1.1:8001"
	if resp != nil && resp.Host != wantHost {
		t.Fatalf("Incorrect host. Got: %s, Want: %s", resp.Host, wantHost)
	}
}

func mkKubeConfig(cluster1Host string, cluster2Host string) (string, error) {
	tempDir, err := os.MkdirTemp("/tmp/", ".kube")
	if err != nil {
		return "", err
	}
	filePath := filepath.Join(tempDir, "config")

	template := `apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://%s:8001
  name: cluster.local
- cluster:
    insecure-skip-tls-verify: true
    server: https://%s:8001
  name: cluster2.local
contexts:
- context:
    cluster: cluster.local
    namespace: default
    user: admin
  name: cluster.local-context
- context:
    cluster: cluster2.local
    namespace: default
    user: admin
  name: cluster2.local-context
current-context: cluster.local-context
preferences: {}
users:
- name: admin
  user:
    token: sdsddsd`

	sampleConfig := fmt.Sprintf(template, cluster1Host, cluster2Host)
	err = os.WriteFile(filePath, []byte(sampleConfig), 0o644)
	if err != nil {
		return "", err
	}
	return filePath, nil
}
```

Run with v0.3.5:
```
=== RUN   TestMergo
--- PASS: TestMergo (0.00s)
PASS
```

Run with v0.3.12:
```
=== RUN   TestMergo
    repro_test.go:41: Incorrect host. Got: https://2.2.2.2:8001, Want: https://1.1.1.1:8001
--- FAIL: TestMergo (0.00s)

FAIL
```

If its easier you can also remove the `replace` in http://github.com/istio/istio and run `go test ./pkg/kube -run TestBuildClientConfig` which will give the same result. The above test is just a simplified version of this test.

### Kubernetes version

<details>
v0.23.1, but this has been an issue for almost 2 years
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by howardjohn** [comment]
I believe https://github.com/kubernetes/kubernetes/blob/a8cb4e22bf982a39ae6f8a522bd2b74fdce04620/staging/src/k8s.io/client-go/tools/clientcmd/loader.go#L228 is the line that is broken btw, but not 100% sure

**Comment by dims** [comment]
cc @liggitt

**Comment by liggitt** [comment]
this seems primarily like a bug in mergo that reversed behavior in a patch release... has that been reported to that component as a bug?

if someone wanted to tackle updating client-go and making sure our use didn't regress, I wouldn't object

**Comment by jlsong01** [comment]
I would like to take a try

/assign

**Comment by jlsong01** [comment]
Now client-go pins to mergo v0.3.5, seem v0.3.5 has some bug, while the bug has been fixed since v0.3.8.

To my understanding, the expected `wantHost` should be https://2.2.2.2:8001  instead of 1.1.1.1, as in client-go mergo.WithOverride is specified.

so, we should upgrade the k8s dependency from v0.3.5 to the latest 0.3.12, and add some comments to client-go to clarify it.
@liggitt @dims Please correct my if my understanding is wrong.

```
package kube

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"k8s.io/client-go/tools/clientcmd"
)

func TestMergo(t *testing.T) {
	config1, err := mkKubeConfig("1.1.1.1", "3.3.3.3")
	if err != nil {
		t.Fatalf("Failed to create a sample kubernetes config file. Err: %v", err)
	}
	defer os.RemoveAll(filepath.Dir(config1))
	config2, err := mkKubeConfig("2.2.2.2", "4.4.4.4")
	if err != nil {
		t.Fatalf("Failed to create a sample kubernetes config file. Err: %v", err)
	}
	defer os.RemoveAll(filepath.Dir(config2))

	if err := os.Setenv("KUBECONFIG", config1+":"+config2); err != nil {
		t.Fatalf("Failed to set KUBECONFIG environment variable")
	}

	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
	loadingRules.DefaultClientConfig = &clientcmd.DefaultClientConfig
	configOverrides := &clientcmd.ConfigOverrides{
		ClusterDefaults: clientcmd.ClusterDefaults,
	}

	//resp, err := BuildClientConfig("", "")
	resp, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides).ClientConfig()
	if err != nil {
		t.Fatal(err)
	}
	wantHost := "https://1.1.1.1:8001"
	if resp != nil && resp.Host != wantHost {
		t.Fatalf("Incorrect host. Got: %s, Want: %s", resp.Host, wantHost)
	}
}

func mkKubeConfig(cluster1Host string, cluster2Host string) (string, error) {
	tempDir, err := os.MkdirTemp("/tmp/", ".kube")
	if err != nil {
		return "", err
	}
	filePath := filepath.Join(tempDir, "config")

	template := `apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://%s:8001
  name: cluster.local
- cluster:
    insecure-skip-tls-verify: true
    server: https://%s:8001
  name: cluster2.local
contexts:
- context:
    cluster: cluster.local
    namespace: default
    user: admin
  name: cluster.local-context
- context:
    cluster: cluster2.local
    namespace: default
    user: admin
  name: cluster2.local-context
current-context: cluster.local-context
preferences: {}
users:
- name: admin
  user:
    token: sdsddsd`

	sampleConfig := fmt.Sprintf(template, cluster1Host, cluster2Host)
	err = os.WriteFile(filePath, []byte(sampleConfig), 0o644)
	if err != nil {
		return "", err
	}
	return filePath, nil
}
```

**Comment by liggitt** [comment]
it's been a long time since I've looked at this, but whatever we upgrade to, the existing kubernetes unit tests exercising the merging need to keep passing

**Comment by liggitt** [comment]
I think the best resolution of this issue, given the number of times this dependency has reversed behavior on minor bumps (and the fact that the current version seems to introduce new bugs), would be to eliminate use of the dependency and write our own merge of our narrow use

**Comment by Neo2308** [comment]
Since mergo has been frozen, should we consider testing at 1.0.0 and see if it works? If it works, we may not have to do the extra effort of writing our own merge.

Ref:
v1 announcement: https://github.com/darccio/mergo/releases/tag/v0.3.16
v1 is frozen: https://github.com/darccio/mergo#status

**Comment by prologic** [comment]
A WIP branch to upgrade to Mergo v1.0 [here](https://github.com/kubernetes/kubernetes/compare/master...prologic:kubernetes:client-go_upgrade_merge?expand=1) -- still working through to understand this issue though... Haven't run tests yet...

**Comment by prologic** [comment]
We probably need a better unit test really, at least there's an "example" that fails:

```
$ go test -v -run '^Example_mergingSomeWithConflict' ./tools/clientcmd/...
?   	k8s.io/client-go/tools/clientcmd/api/latest	[no test files]
=== RUN   Example_mergingSomeWithConflict
--- FAIL: Example_mergingSomeWithConflict (0.00s)
got:
apiVersion: v1
clusters:
- cluster:
    disable-compression: true
    insecure-skip-tls-verify: true
    server: http://a-different-cow.org:8080
  name: cow-cluster
- cluster:
    disable-compression: true
    insecure-skip-tls-verify: true
    server: http://donkey.org:8080
  name: donkey-cluster
contexts:
- context:
    cluster: cow-cluster
    namespace: hammer-ns
    user: red-user
  name: federal-context
current-context: federal-context
kind: Config
preferences: {}
users:
- name: red-user
  user:
    token: a-different-red-token
- name: yellow-user
  user:
    token: yellow-token
want:
apiVersion: v1
clusters:
- cluster:
    server: http://cow.org:8080
  name: cow-cluster
- cluster:
    disable-compression: true
    insecure-skip-tls-verify: true
    server: http://donkey.org:8080
  name: donkey-cluster
contexts:
- context:
    cluster: cow-cluster
    namespace: hammer-ns
    user: red-user
  name: federal-context
current-context: federal-context
kind: Config
preferences: {}
users:
- name: red-user
  user:
    token: red-token
- name: yellow-user
  user:
    token: yellow-token
FAIL
FAIL	k8s.io/client-go/tools/clientcmd	0.326s
testing: warning: no tests to run
PASS
ok  	k8s.io/client-go/tools/clientcmd/api	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	k8s.io/client-go/tools/clientcmd/api/v1	(cached) [no tests to run]
FAIL
```

**Comment by prologic** [comment]
Noting the comment [here](https://github.com/kubernetes/kubernetes/pull/107837#issuecomment-1079744069) that favours rewriting our use of mergo to avoid the dependency entirely.

**Comment by prologic** [comment]
> Since mergo has been frozen, should we consider testing at 1.0.0 and see if it works? If it works, we may not have to do the extra effort of writing our own merge.
> 
> Ref: v1 announcement: https://github.com/darccio/mergo/releases/tag/v0.3.16 v1 is frozen: https://github.com/darccio/mergo#status

I've just tested the v1.0.0 release of Mergo with some additional unit tests added that were described in OP. The additional test fails as well as the existing example:

```
=== RUN   TestMergoCompatibility
    loader_test.go:159: Incorrect host. Got: https://2.2.2.2:8001, Want: https://1.1.1.1:8001
--- FAIL: TestMergoCompatibility (0.00s)
...
=== RUN   Example_mergingSomeWithConflict
--- FAIL: Example_mergingSomeWithConflict (0.00s)
got:
apiVersion: v1
clusters:
- cluster:
    disable-compression: true
    insecure-skip-tls-verify: true
    server: http://a-different-cow.org:8080
  name: cow-cluster
- cluster:
    disable-compression: true
    insecure-skip-tls-verify: true
    server: http://donkey.org:8080
  name: donkey-cluster
contexts:
- context:
    cluster: cow-cluster
    namespace: hammer-ns
    user: red-user
  name: federal-context
current-context: federal-context
kind: Config
preferences: {}
users:
- name: red-user
  user:
    token: a-different-red-token
- name: yellow-user
  user:
    token: yellow-token
want:
apiVersion: v1
clusters:
- cluster:
    server: http://cow.org:8080
  name: cow-cluster
- cluster:
    disable-compression: true
    insecure-skip-tls-verify: true
    server: http://donkey.org:8080
  name: donkey-cluster
contexts:
- context:
    cluster: cow-cluster
    namespace: hammer-ns
    user: red-user
  name: federal-context
current-context: federal-context
kind: Config
preferences: {}
users:
- name: red-user
  user:
    token: red-token
- name: yellow-user
  user:
    token: yellow-token
=== RUN   Example_mergingEverythingNoConflicts
--- PASS: Example_mergingEverythingNoConflicts (0.01s)
FAIL
FAIL	k8s.io/client-go/tools/clientcmd	2.064s
```

Mergo v1.0.0 is busted too :/
