### ISSUE TITLE
Field Selectors Need Docs on `status.successful` Selector for Jobs

### ISSUE THREAD

**Issue by dastrobu** [kubernetes/kubernetes#107536]
[Docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#supported-fields) on field selectors mentions:

> Supported field selectors vary by Kubernetes resource type.

According to https://stackoverflow.com/a/63128911/1458343 one can select jobs with 

```
kubectl get job --field-selector status.successful=1
```
which actually works. However, I did not find any docs on either the [Field Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/) or the [Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/job/) page.

Also, given that jobs have a `succeeded` and not a `successful` property 
```
status:
  completionTime: "2021-01-13T16:08:12Z"
  conditions:
  - ...
  startTime: "2021-01-13T16:04:37Z"
  succeeded: 1
```
it is very unintuitive that this field sector actually works.
