### ISSUE TITLE
Loss hostAliases records when edit existing deployment

### ISSUE THREAD

**Issue by dinhanhhuy** [kubernetes/kubernetes#107668]
### What happened?

Create deployment from a manifest file having different "hostAliases" with an upgrade from an existing one.

### What did you expect to happen?

The hostAliases in both case should be have 3 records, not loss when upgrade

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a deployment with the following manifest
```yaml
# Source: nginx/charts/common/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: harbor-registry
      containers:
        - name: nginx
          image: "harbor.xxx.vn/core/nginx"
          imagePullPolicy: Always
      hostAliases:
        - hostnames:
          - t.t.t.t
          ip: 10.30.49.2
        - hostnames:
          - x.x.x.x
          - y.y.y.y
          - z.z.z.z
          ip: 10.30.94.60
```
2. Verify hostAliases
```sh
$ kubectl get deploy nginx -o=jsonpath='{.spec.template.spec.hostAliases}' | jq                                                                                                            
[                                                                                                                                                                                                                                             
  {                                                                                                                                                                                                                                           
    "hostnames": [                                                                                                                                                                                                                            
      "t.t.t.t"                                                                                                                                                                                                                               
    ],                                                                                                                                                                                                                                        
    "ip": "10.30.49.2"                                                                                                                                                                                                                        
  },                                                                                                                                                                                                                                          
  {                                                                                                                                                                                                                                           
    "hostnames": [  # <---- it have 3 domain here                                                                                                                                                                                                                           
      "x.x.x.x",                                                                                                                                                                                                                              
      "y.y.y.y",                                                                                                                                                                                                                              
      "z.z.z.z"                                                                                                                                                                                                                               
    ],                                                                                                                                                                                                                                        
    "ip": "10.30.94.60"                                                                                                                                                                                                                       
  }                                                                                                                                                                                                                                           
] 
```
3. Upgrade deploy "kubectl apply -f deploy.2.yaml" with flowing manifest
```yaml
# Source: nginx/charts/common/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: harbor-registry
      containers:
        - name: nginx
          image: "harbor.xxx/core/nginx"
          imagePullPolicy: Always
      hostAliases:
        - hostnames:
          - t.t.t.t
          ip: 10.30.49.2
        - hostnames:
          - x.x.x.x
          ip: 10.30.94.60
        - hostnames:
          - y.y.y.y
          ip: 10.30.94.60
        - hostnames:
          - z.z.z.z
          ip: 10.30.94.60
```
4. Verify hostAliases
```sh
$ kubectl get deploy nginx -o=jsonpath='{.spec.template.spec.hostAliases}' | jq
[                                                                                                                                                                                                                                             
  {                                                                                                                                                                                                                                           
    "hostnames": [                                                                                                                                                                                                                            
      "t.t.t.t"                                                                                                                                                                                                                               
    ],                                                                                                                                                                                                                                        
    "ip": "10.30.49.2"                                                                                                                                                                                                                        
  },                                                                                                                                                                                                                                          
  {                                                                                                                                                                                                                                           
    "hostnames": [  # <----- lossing records                                                                                                                                                                                                                            
      "x.x.x.x"                                                                                                                                                                                                                               
    ],                                                                                                                                                                                                                                        
    "ip": "10.30.94.60"                                                                                                                                                                                                                       
  }                                                                                                                                                                                                                                           
] 
```
5. delete and create a new deployment from deploy.2.yaml
```sh
$ kubectl delete deploy nginx
$ kubectl create -f deploy.2.yaml
$ kubectl get deploy nginx -o=jsonpath='{.spec.template.spec.hostAliases}' | jq
[
  {
    "hostnames": [
      "t.t.t.t"
    ],
    "ip": "10.30.49.2"
  },
  {
    "hostnames": [
      "x.x.x.x"
    ],
    "ip": "10.30.94.60"
  },
  {
    "hostnames": [
      "y.y.y.y"
    ],
    "ip": "10.30.94.60"
  },
  {
    "hostnames": [
      "z.z.z.z"
    ],
    "ip": "10.30.94.60"
  }
]
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>


### Cloud provider

<details>
Bare metal, RKE
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
