### ISSUE TITLE
Over-Mounting an ssh-key using subpath makes the key unusable for the ssh-client

### ISSUE THREAD

**Issue by EugenMayer** [kubernetes/kubernetes#107818]
### What happened?

Mounting a ssh-key via a secret and subpath where an existing key was present, renders the key unusable of the ssh-clieent

### What did you expect to happen?

Overmount with subpath should work or not work transparently. In this case it seems to work, but not in all cases.

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod (and the secret) with the following mounts and volumes (i used debian:buster).
The secret should have the key `id_ed25519` with the ssh private key.

Create a docker image with a ssh-key generated during build time, put the ssh key to `/root/.ssh/id_ed25519` - this is the key we will overmount using the secret, so the actual value of the key does not matter

```yaml
        volumeMounts:
            - mountPath: "/root/ssh-keys"
              name: ssh-key
            - mountPath: "/root/.ssh/id_ed25519"
              subPath: "id_ed25519"
              name: ssh-key
```

```yaml
      volumes:
        - name: ssh-key
          secret:
            secretName: {{.Values.sshSecretName}}
            # 256 stands for chmod 0400
            defaultMode: 256
```

and
```yaml
      securityContext:
        runAsUser: 0
```

Now connect to the server of your choice using

```shell
ssh  -vvv -i /root/ssh-keys/id_ed25519 user@server
```

Should work.

But connecting using the key under the subpath won't

```shell
ssh -vvv -i /root/.ssh/id_ed25519 user@server
```

### Anything else we need to know?

The key has

-  the right permissions (0400)
- /root/.ssh has the right permissions (0700)
- i can read/show the key using `cat /root/.ssh/id_ed25519` - it is not the key from the docker-image but rather the mounted one (value wise)
- using `StrictModes no` on the sshd server will not help either (and is not what i want anyway)
### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5+k3s1", GitCommit:"405bf79da97831749733ad99842da638c8ee4802", GitTreeState:"clean", BuildDate:"2021-12-18T00:43:30Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
%     
```
</details>

### Cloud provider

<details>

</details>

### OS version

<details>
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=foca
```

```console
Linux prod-rke-server-1 5.4.0-90-generic
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

- calico (latest)
- longhorn (latest)
- local-path (latest)
