### ISSUE TITLE
Server-side apply dry-run incorrectly does not report any changes when removing a field from an object

### ISSUE THREAD

**Issue by chrisayoub** [kubernetes/kubernetes#107828]
### What happened?

When running a server-side apply with the following query parameters, the result indicates that there is no change when in fact a field is being deleted from the target object.
```
?dryRun=All&fieldManager=kubectl&force=true
``` 
(parameters taken from `kubectl diff ... -v6` as reproduced below)

### What did you expect to happen?

I would expect that the `kubectl diff` output when run server-side matches that when run client-side e.g. that it reports a field is being deleted.

### How can we reproduce it (as minimally and precisely as possible)?

Create deployment (or any mutable object, really)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: test-deploy
        my-label: my-value
    spec:
      containers:
      - name: test
        image: IMAGE
```

Update deployment file to remove a field. In this case, remove `my-label: my-value`

Attempt `kubectl diff -f deploy.yaml`. Client-side works (the default method with no additional flags):
```
@@ -115,7 +114,6 @@
       creationTimestamp: null
       labels:
         app: test-deploy
-        my-label: my-value
```

Attempt `kubectl diff -f deploy.yaml --server-side --force-conflicts=true` and it reports no such diff.

### Kubernetes version

<details>

We use a custom internal build of Kubernetes, but we are currently running this patch version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"archive", BuildDate:"2022-01-20T00:37:18Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EC2
</details>

### OS version

<details>

5.4.141-hs5.el6.x86_64 (internal kernel)

</details>

**Comment by ardaguclu** [comment]
I investigated the issue you filed and could have reproduced. 

I think server-side apply just skips if the resources are applied with client-side or managed fields' owners are different than it's?.

As you mentioned this does not work;

```
$ kubectl apply -f test_pod.yaml
$ kubectl diff -f test_changed_pod.yaml --server-side
```
But I tried this and it worked;

```
$ kubectl apply -f test_pod.yaml --server-side
$ kubectl diff -f test_changed_pod.yaml --server-side
```
I'm not sure this is a bug or intentional design decision, thereby I'm removing my assignment to someone verify it. If this is a bug(I don't think so, because this looks the backbone decision of server side but I might be wrong), I can gladly fix that problem.

/unassign

**Comment by ardaguclu** [comment]
I'd like to also note;

```
cluster/kubectl.sh apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: test-deploy
        my-label: my-value
    spec:
      containers:
      - name: test
        image: IMAGE
EOF
```

After applying above resource. This also does not remove `my-label: my-value`;

```
cluster/kubectl.sh apply --server-side -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - name: test
        image: IMAGE
EOF
```
