### ISSUE TITLE
Setting a defaultRequest on a LimitRange sets an implicit Limit

### ISSUE THREAD

**Issue by max-sixty** [kubernetes/kubernetes#107922]
### What happened?

Using a `LimitRange`, I'm hoping to have a default request, but _not_ a default limit.

Setting this:

```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-and-mem-defaults
spec:
  limits:
    - defaultRequest:
        memory: 512Mi
        cpu: 100m
      type: Container
```

Seems to set these in a container:

```yaml
    Limits:
      cpu:                100m
      memory:             512Mi
    Requests:
      cpu:                100m
      memory:             512Mi
```

### What did you expect to happen?

I would have expected this output:

```diff
-    Limits:
-      cpu:                100m
-      memory:             512Mi
     Requests:
       cpu:                100m
       memory:             512Mi
```

### How can we reproduce it (as minimally and precisely as possible)?

As above

### Anything else we need to know?

Possibly this is WAI, and I'm using the wrong resource to get default requests? Though the behavior also seems confusing.

### Kubernetes version

<details>

```console
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"
clean", BuildDate:"2022-01-19T17:27:51Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTr
eeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
MacOS 12.0.1
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
