### ISSUE TITLE
0/1 nodes are available: 1 node(s) had volume node affinity conflict

### ISSUE THREAD

**Issue by ahrtr** [kubernetes/kubernetes#108096]
I am pretty sure that the PV's node affinity is consistent with the node, but I still got the error message `1 node(s) had volume node affinity conflict`.

### K8s version: 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"8b932107b754fcea31c933314335ee6b550d3fc7", GitTreeState:"clean", BuildDate:"2022-01-21T20:34:02Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Cluster & Node info
The K8s cluster is created on AWS, but not in EKS.

Only one worker node in the cluster.
```

$ kubectl describe nodes
Name:               ip-10-0-8-8.ec2.internal
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=t3.medium
                    beta.kubernetes.io/os=linux
                    bosh.id=baa3bf67-b91f-46cc-9d6e-a3f5c92b9c74
                    bosh.zone=us-east-1a
                    failure-domain.beta.kubernetes.io/region=us-east-1
                    failure-domain.beta.kubernetes.io/zone=us-east-1a
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=ip-10-0-8-8.ec2.internal
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=t3.medium
                    pks-system/cluster.name=default_ca_cluster_62c075ac-5d72-42d7-a68d-4275767d9d34
                    pks-system/cluster.uuid=service-instance_731522c1-c22d-4f2c-bfa9-2fc3a9efe290
                    spec.ip=10.0.8.8
                    topology.kubernetes.io/region=us-east-1
                    topology.kubernetes.io/zone=us-east-1a
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 14 Feb 2022 05:51:59 +0000
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  ip-10-0-8-8.ec2.internal
  AcquireTime:     <unset>
  RenewTime:       Mon, 14 Feb 2022 09:14:32 +0000
......
```

### Steps to reproduce the issue
1. Disable CSI Migration feature for both kube-controller-manager and kubelet. Restarted both of them afterwards.
Added the following flag to kube-controller-manager,
`- "--feature-gates=CSIMigration=false,CSIMigrationAWS=false"`

Added the following flags to kubelet,
```
   featureGates:
     CSIMigration: false
     CSIMigrationAWS: false
```

2. Create storageClass below,

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-intree-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
```

3. Create PVC below,

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-intree-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-intree-sc
  resources:
    requests:
      storage: 2Gi
```

4. Create POD below,

```
apiVersion: v1
kind: Pod
metadata:
  name: app-for-intree
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-intree-claim
```

5. The PV is created successfully, but the POD is always in Pending status, and I see the error message "had volume node affinity conflict" when executing "`kubectl describe pod app-for-intree`".

```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  21m                 default-scheduler  0/1 nodes are available: 1 node(s) had volume node affinity conflict.
  Warning  FailedScheduling  85s (x19 over 20m)  default-scheduler  0/1 nodes are available: 1 node(s) had volume node affinity conflict.
```

### analysis
I set kube-controller-manager's log level to 5, but I still do NOT see the error message at [binder.go#L811](https://github.com/kubernetes/kubernetes/blob/c0add891584a4185ab9a2c2152135a2221462b9f/pkg/scheduler/framework/plugins/volumebinding/binder.go#L811).
