### ISSUE TITLE
Cronjob fails to be scheduled - reports JobAlreadyActive even though there are no jobs active

### ISSUE THREAD

**Issue by simonjpartridge** [kubernetes/kubernetes#108023]
### What happened?

A cronjob that is expired fails to be scheduled after the first run. The cronjob reports that it has an active job. Even though the referenced job has completed successfully.

We never see the event `SawCompletedJob` in the cronjob even when the child job completes.

We have been running this job for over a year with no problem and this problem seems to have started occuring after upgrade to kubernetes 1.21 with no change to the job.

```
kubectl get cronjobs -n transparency poll-daily-ballot-handout-v2
NAME                           SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
poll-daily-ballot-handout-v2   0 */2 * * *   False     1        17h             22h
```

```
k get jobs -n transparency
NAME                                             COMPLETIONS   DURATION   AGE
poll-daily-ballot-handout-v2-27405480            1/1           35m        21h
poll-daily-ballot-handout-v2-27405600            1/1           21m        19h
poll-daily-ballot-handout-v2-27405720            1/1           23m        17h
```

```
Name:                          poll-daily-ballot-handout-v2
Namespace:                     transparency
Labels:                        app=poll
                               skaffold.dev/run-id=a0745fb2-ebcb-4534-9776-85e8ebe19918
Annotations:                   <none>
Schedule:                      0 */2 * * *
Concurrency Policy:            Forbid
Suspend:                       False
Successful Job History Limit:  10
Failed Job History Limit:      10
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:  app=poll
           skaffold.dev/run-id=a0745fb2-ebcb-4534-9776-85e8ebe19918
  Containers:
   service:
    Image:      ## omitted
    Port:       <none>
    Host Port:  <none>
    Args:
      ## omitted
    Limits:
      cpu:     200m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  64Mi
    Environment:
       ## omitted
    Mounts:                   <none>
  Volumes:                    <none>
Last Schedule Time:           Tue, 08 Feb 2022 18:00:00 +0000
Active Jobs:                  poll-daily-ballot-handout-v2-27405720
Events:
  Type    Reason            Age                 From                Message
  ----    ------            ----                ----                -------
  Normal  JobAlreadyActive  43m (x13 over 15h)  cronjob-controller  Not starting job because prior execution is running and concurrency policy is Forbid
```

if we describe the job that is reported as being active:

```
k describe jobs -n transparency poll-daily-ballot-handout-v2-27405720 
Name:           poll-daily-ballot-handout-v2-27405720
Namespace:      transparency
Selector:       controller-uid=8df35af2-326c-41e8-a8f1-ca2d10219208
Labels:         app=poll
                skaffold.dev/run-id=30b70c83-7b87-41a9-91ab-1469b228e9fa
Annotations:    <none>
Controlled By:  CronJob/poll-daily-ballot-handout-v2
Parallelism:    1
Completions:    1
Start Time:     Tue, 08 Feb 2022 18:00:00 +0000
Completed At:   Tue, 08 Feb 2022 18:23:37 +0000
Duration:       23m
Pods Statuses:  0 Running / 1 Succeeded / 0 Failed
Pod Template:
  Labels:  app=poll
           controller-uid=8df35af2-326c-41e8-a8f1-ca2d10219208
           job-name=poll-daily-ballot-handout-v2-27405720
           skaffold.dev/run-id=30b70c83-7b87-41a9-91ab-1469b228e9fa
  Containers:
   service:
    Image:      ## omitted
    Port:       <none>
    Host Port:  <none>
    Args:
      ## omitted
    Limits:
      cpu:     200m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  64Mi
    Environment:
      ## omitted
    Mounts:                   <none>
  Volumes:                    <none>
Events:                       <none>
```

we can see that the pod status is reported as succeeded and completions is 1. However the cronjob still seems to be tracking it.

Definition of the cronjob is as follows

```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: poll
  name: poll-daily-ballot-handout-v2
  namespace: transparency
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 10
  schedule: 0 */2 * * *
  jobTemplate:
    metadata:
      labels:
        app: poll
    spec:
      template:
        metadata:
          labels:
            app: poll
        spec:
          containers:
            - args:
                ## omitted
              env:
                ## omitted
              image: #ommitted
              name: service
              resources:
                limits:
                  cpu: 200m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
```

### What did you expect to happen?

Cronjob to report active = 0 when the job finished executing and a new job to be created when the cronjob is next schedule to be run.

### How can we reproduce it (as minimally and precisely as possible)?

Not too sure what to suggest here, I'm don't think that cronjobs are expected to behave like this, and I'm unable to reproduce this with a basic cronjob. 

### Anything else we need to know?

Skaffold is deploying to the cluster multiple times throughout the day. I wonder if this could be the cause, would skaffold set the active field? 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
google cloud
</details>

### OS version

N/A

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>
N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>
