### ISSUE TITLE
dispatcher.go:129] Failed calling webhook, failing open webhook.openpolicyagent.org: failed calling webhook "webhook.openpolicyagent.org": converting (v1beta1.AdmissionReview) to (v1.AdmissionReview): unknown conversion

### ISSUE THREAD

**Issue by bjethwan** [kubernetes/kubernetes#108155]
### What happened?

OPA Helm Chart not working but problem with Kubernetes

tried with KIND k8s version 1.21.1 and v 1.22.5

OPA installed using ArgoCD
```
  repoURL: 'https://open-policy-agent.github.io/kube-mgmt/charts'
  targetRevision: 4.0.0
  helm:
    parameters:
      - name: admissionController.enabled
        value: 'true'
      - name: mgmt.configmapPolicies.enabled
        value: 'true'
      - name: mgmt.data.enabled
        value: 'true'
      - name: mgmt.enabled
        value: 'true'
  chart: opa
```

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: LS0....===
    service:
      name: opa
      namespace: opa
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: webhook.openpolicyagent.org
  namespaceSelector:
    matchExpressions:
    - key: openpolicyagent.org/webhook
      operator: NotIn
      values:
      - ignore
  objectSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - '*'
    resources:
    - '*'
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
```

### What did you expect to happen?

I expected the validatingwebhookconfiguration to work.
But kube-apiserver kept logging 

dispatcher.go:129] Failed calling webhook, failing open webhook.openpolicyagent.org: failed calling webhook "webhook.openpolicyagent.org": converting (v1beta1.AdmissionReview) to (v1.AdmissionReview): unknown conversion

### How can we reproduce it (as minimally and precisely as possible)?

Install OPA using Helm Chart

### Kubernetes version

tried with KIND k8s version 1.21.1 and v 1.22.5

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
