### ISSUE TITLE
retainKeys patch strategy not working as expected

### ISSUE THREAD

**Issue by rafaeljesus** [kubernetes/kubernetes#108249]
### What happened?

I needed to rename the volume name of a running a stateful set, so I ran the following command:

```bash
kubectl patch sts example-shard0 \
--type merge \
--patch "$(cat patch-sts-retain-keys-example.yaml)"
```

The applied patch file definition correctly renamed the volume, however, it ended up adding an empty string to the other volume that shouldn't be changed.

The `PodSpec` says:
```json
{
  "volumes":{
    "description":"List of volumes that can be mounted by containers belonging to the pod. More info: https://kubernetes.io/docs/concepts/storage/volumes",
    "items":{
      "$ref":"#/definitions/io.k8s.api.core.v1.Volume"
    },
    "type":"array",
    "x-kubernetes-patch-merge-key":"name",
    "x-kubernetes-patch-strategy":"merge,retainKeys"
  }
}
```

Am I making the right use of `$retainKeys` here?

<details>
<summary>example-shard0.yaml</summary>

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-example-shard0
  labels:
    app: sts-example
spec:
  selector:
    matchLabels:
      app: sts-example
  serviceName: "sts-example"
  replicas: 1
  template:
    metadata:
      labels:
        app: sts-example
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: logs
          mountPath: /root/logs
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
        - name: logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: sts-example-config
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: resizable-balanced
      resources:
        requests:
          storage: 512Mi
```
</details>

<details><summary>patch-sts-retain-keys-example.yaml</summary>

```yaml
spec:
  template:
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: sts-example-pool-config
        - $retainKeys:
          - logs
```
</details>

<details><summary>unexpected-output.yaml</summary>

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  ...
spec:
  template:
    ...
    metadata:
    spec:
      containers:
      ...
      volumes:
      - configMap:
          defaultMode: 420
          name: sts-example-pool-config
        name: config-volume
      - emptyDir: {}
        name: ""
   ...
```
</details>

### What did you expect to happen?

I'd expect the `kubectl patch --type merge ..` command to have changed the volume name as per the patch file, without changing the volume names declared in the `$retainKeys` array

### How can we reproduce it (as minimally and precisely as possible)?

create the stateful set
```bash
kubectl apply -f example-shard0.yaml
```

patch the stateful set
```bash
kubectl patch sts example-shard0 \
--type merge \
--patch "$(cat patch-sts-retain-keys-example.yaml)"
```

check if the stateful set volumes have the desired state
```yaml
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    metadata:
    spec:
      containers:
      volumes:
      - configMap:
          defaultMode: 420
          name: sts-example-pool-config
        name: config-volume
      - emptyDir: {}
        name: logs
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-dispatcher", GitCommit:"2a8027f41d28b788b001389f3091c245cd0a9a60", GitTreeState:"clean", BuildDate:"2022-01-21T20:31:13Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
