### ISSUE TITLE
cgroupv2 and  kubelet seem not playing well together on non systemd OS

### ISSUE THREAD

**Issue by liyimeng** [kubernetes/kubernetes#108364]
### What happened?

I deploy a k3s on a pure cgroupv2 system that is not using systemd. kubelet seem get no access to cgroup as expected. More background see https://github.com/k3s-io/k3s/issues/5133

### What did you expect to happen?

kubelet should support cgroupv2 without systemd.  There are still systems preper non running systemd

### How can we reproduce it (as minimally and precisely as possible)?

- Deploy k3s on a cgroupv2 only OS which not using systemd, e.g. alpine Linux
- run kubectl top node, k8s report no metric available 

### Anything else we need to know?

We have some troubleshooting here https://github.com/k3s-io/k3s/issues/5133

### Kubernetes version

<details>

```console
$ kubectl version

kubectl version 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3+k3s-683396c9", GitCommit:"683396c991d7d18da732fd786519b48004714119", GitTreeState:"clean", BuildDate:"2022-02-07T13:56:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3+k3s-683396c9", GitCommit:"683396c991d7d18da732fd786519b48004714119", GitTreeState:"clean", BuildDate:"2022-02-07T13:56:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
bare metal/VM
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
k3s
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd 
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ehashman** [comment]
/remove-wg iot-edge
/cc @mrunalp 

It's not clear to me if this is a supported use case. cgroupv2 support is only in beta.

/triage needs-information

**Comment by liyimeng** [comment]
@ehashman let ceanup the bug. be-prepared to move forward GA :D

**Comment by rphillips** [comment]
Got a report from @stevekuznetsov that this may be broken in `kind` as well.

/assign @giuseppe

**Comment by giuseppe** [comment]
could you try running directly cAdvisor and see if it collects any stat?

**Comment by liyimeng** [comment]
how can I run cadvisor in k8s,  I do this:

```
apiVersion: v1
kind: Pod
metadata:
  name: cadvisor
spec:
  nodeName: myserver
  containers:
  - name: cadvisor
    image:  cadvisor/cadvisor:v0.36.0
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /rootfs
      readOnly: true
      name: root
    - mountPath: /var/run
      readOnly: true
      name: varrun
    - mountPath: /sys
      readOnly: true
      name: sys
    - mountPath: /dev/disk
      readOnly: true
      name: disk
    - mountPath: /dev/kmsg
      name: kmsg

  volumes:
  - name: root
    hostPath:
      path: /
      type: Directory
  - name: varrun
    hostPath:
      path: /var/run
      type: Directory
  - name: sys
    hostPath:
      path: /sys
      type: Directory
  - name: disk
    hostPath:
      path: /dev/disk
      type: Directory
  - name: kmsg
    hostPath:
      path: /dev/kmsg

```

 I failed to start
```

F0308 12:28:36.905536       1 cadvisor.go:160] Failed to create a Container Manager: mountpoint for  not found
failed to create fsnotify watcher: too many open files
```

My cluster use Containerd, not docker runtime.
