### ISSUE TITLE
NFS subPath mount fails 

### ISSUE THREAD

**Issue by adyanth** [kubernetes/kubernetes#108374]
### What happened?

Attempting to mount a subpath of an existing NFS share fails with the error:
Error: failed to prepare subPath for volumeMount "data" of container "pod"

### What did you expect to happen?

I expect the mount to work

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      volumes:
        - name: test
          nfs:
            server: nas.adyanth.lan
            path: /export/Folder
      containers:
        - name: test
          image: alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: test
              mountPath: /test
              subPath: completed
```

```bash
$ k describe pod -l app=test | tail -1
Warning  Failed     6s (x3 over 27s)  kubelet            Error: failed to prepare subPath for volumeMount "test" of container "test"
```

### Anything else we need to know?

Removing the subPath works fine. The subPath folder already exists.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On prem k3s cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="VMware Photon OS"
VERSION="4.0"
ID=photon
VERSION_ID=4.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
$ uname -a
Linux kratos-master 5.10.93-6.ph4-esx #1-photon SMP Thu Feb 17 02:54:43 UTC 2022 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd
Client:
  Version:  v1.5.9-k3s1
  Revision: 
  Go version: go1.16.10

Server:
  Version:  v1.5.9-k3s1
  Revision: 
  UUID: afc2c474-1b8e-413d-80b5-ec10f515f8d8
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
