### ISSUE TITLE
HPA calculated periodStartRelicas maybe unexpected when scaling direction changed frequently during periodSecond

### ISSUE THREAD

**Issue by lxtywypc** [kubernetes/kubernetes#108354]
### What happened?

We created an hpa as following:  
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
  namespace: test
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 300
        type: Pods
        value: 2
      selectPolicy: Max
      stabilizationWindowSeconds: 0
    scaleUp:
      policies:
      - periodSeconds: 300
        type: Percent
        value: 300
      selectPolicy: Min
      stabilizationWindowSeconds: 0
  maxReplicas: 20
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-hpa
```
Then started a deployment with 4 replicas and made the CPU utilization about 10%, which proposed to double the replicas, and it did work:  
```
$kubectl get pod -n test
NAME                      READY   STATUS    RESTARTS   AGE
my-hpa-7677ddbfdf-4c6qb   1/1     Running   0          61s
my-hpa-7677ddbfdf-7pjq6   1/1     Running   0          61s
my-hpa-7677ddbfdf-9m5d8   1/1     Running   0          61s
my-hpa-7677ddbfdf-l4mvg   1/1     Running   0          61s

NAME                      READY   STATUS              RESTARTS   AGE
my-hpa-7677ddbfdf-4c6qb   1/1     Running             0          62s
my-hpa-7677ddbfdf-7pjq6   1/1     Running             0          62s
my-hpa-7677ddbfdf-9m5d8   1/1     Running             0          62s
my-hpa-7677ddbfdf-htrgw   0/1     ContainerCreating   0          1s
my-hpa-7677ddbfdf-jmkf2   0/1     ContainerCreating   0          1s
my-hpa-7677ddbfdf-l4mvg   1/1     Running             0          62s
my-hpa-7677ddbfdf-qwz5z   0/1     ContainerCreating   0          1s
my-hpa-7677ddbfdf-w5xxl   0/1     ContainerCreating   0          1s
```
Then we changed the CPU utilization to about 1%, which would trigger scaling down and would kill 2 pods only for scaleDown behavior:  
```
$kubectl get pod -n test
NAME                      READY   STATUS    RESTARTS   AGE
my-hpa-7677ddbfdf-4c6qb   1/1     Running   0          2m1s
my-hpa-7677ddbfdf-7pjq6   1/1     Running   0          2m1s
my-hpa-7677ddbfdf-9m5d8   1/1     Running   0          2m1s
my-hpa-7677ddbfdf-htrgw   1/1     Running   0          60s
my-hpa-7677ddbfdf-jmkf2   1/1     Running   0          60s
my-hpa-7677ddbfdf-l4mvg   1/1     Running   0          2m1s
my-hpa-7677ddbfdf-qwz5z   1/1     Running   0          60s
my-hpa-7677ddbfdf-w5xxl   1/1     Running   0          60s

NAME                      READY   STATUS        RESTARTS   AGE
my-hpa-7677ddbfdf-4c6qb   1/1     Running       0          2m2s
my-hpa-7677ddbfdf-7pjq6   1/1     Running       0          2m2s
my-hpa-7677ddbfdf-9m5d8   1/1     Running       0          2m2s
my-hpa-7677ddbfdf-htrgw   1/1     Running       0          61s
my-hpa-7677ddbfdf-jmkf2   1/1     Running       0          61s
my-hpa-7677ddbfdf-l4mvg   1/1     Running       0          2m2s
my-hpa-7677ddbfdf-qwz5z   1/1     Terminating   0          61s
my-hpa-7677ddbfdf-w5xxl   1/1     Terminating   0          61s
```
Then changed the CPU utilization to about 20%, which would trigger scaling up:  
```
$kubectl get pod -n test
NAME                      READY   STATUS    RESTARTS   AGE
my-hpa-7677ddbfdf-4c6qb   1/1     Running   0          2m45s
my-hpa-7677ddbfdf-7pjq6   1/1     Running   0          2m45s
my-hpa-7677ddbfdf-9m5d8   1/1     Running   0          2m45s
my-hpa-7677ddbfdf-htrgw   1/1     Running   0          104s
my-hpa-7677ddbfdf-jmkf2   1/1     Running   0          104s
my-hpa-7677ddbfdf-l4mvg   1/1     Running   0          2m45s

NAME                      READY   STATUS              RESTARTS   AGE
my-hpa-7677ddbfdf-2smm2   0/1     ContainerCreating   0          1s
my-hpa-7677ddbfdf-4c6qb   1/1     Running             0          2m47s
my-hpa-7677ddbfdf-7pjq6   1/1     Running             0          2m47s
my-hpa-7677ddbfdf-9m5d8   1/1     Running             0          2m47s
my-hpa-7677ddbfdf-htrgw   1/1     Running             0          106s
my-hpa-7677ddbfdf-jmkf2   1/1     Running             0          106s
my-hpa-7677ddbfdf-l4mvg   1/1     Running             0          2m47s
my-hpa-7677ddbfdf-mtjcc   0/1     ContainerCreating   0          1s
```
It did scale up, and for our expectation, it should be scaled to 6\*20/5=24 but would be limited by scaleUp behavior as 4\*(1+300%)=16, but in fact, it was just scaled up to 8

### What did you expect to happen?

It would be scaled up to 16 in last scaling actions

### How can we reproduce it (as minimally and precisely as possible)?

Start an hpa with a scaleUp behavior which has little long period and a little great Percent value, then start a deployment with a container whose CPU utilization could be controlled easily. Change the CPU utilization to make it scale up within limit, scale down a little, and scale up again without limit. 

### Anything else we need to know?

I think it is caused by https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L800, this function seems that it just considered about scaleUp event history when calculate scaleUp limit (so does calculate scaleDown limit). I think it is a bit unreasonable.  
Does this action match the design? Or it does be a bug? 

### Kubernetes version

<details>

```console
$ kubectl version
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
