### ISSUE TITLE
Pod of DaemonSet manage that be scheduled to a node which reach max pod limit(maybe other reasons) can not display node IP

### ISSUE THREAD

**Issue by jiaozhenkai** [kubernetes/kubernetes#108584]
### What would you like to be added?

A daemonset pod is scheduled to the node of cluster failed, should display node ip instead of `<none>`.

### Why is this needed?

A daemonset pod be scheduled to every node in cluster, if failed, `kubectl get po -o wide -n <ns>` may be not display node IP. if  we have a cluster that contains thousands of nodes, we won't distinguish which nodes that haven't ds pod.

For example, nginx-ds-mqq4f pod's node ip is <none>:
```
NAME                                READY   STATUS    RESTARTS   AGE     IP             NODE               NOMINATED NODE   READINESS GATES
nginx-deployment-6f94668c68-2lc8p   1/1     Running   0          8m55s   10.244.2.252   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-67259   1/1     Running   0          5m21s   10.244.2.254   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-8ckdh   1/1     Running   0          9m47s   10.244.2.248   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-b4v28   1/1     Running   0          147d    10.244.2.218   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-bb9m8   1/1     Running   0          9m47s   10.244.2.250   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-brqkd   1/1     Running   0          147d    10.244.2.222   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-cjbph   1/1     Running   0          147d    10.244.2.220   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-ck2fg   1/1     Running   0          56d     10.244.2.235   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-cnncn   1/1     Running   0          56d     10.244.2.234   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-cw95f   1/1     Running   0          56d     10.244.2.236   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-f9h77   1/1     Running   0          56d     10.244.2.237   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-hzrb8   1/1     Running   0          2m59s   10.244.2.196   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-j8qgf   1/1     Running   0          56d     10.244.2.231   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-lmmz8   1/1     Running   0          4h53m   10.244.2.239   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-ncxvw   1/1     Running   0          9m47s   10.244.2.251   vm-46-150-centos   <none>           <none>
nginx-deployment-6f94668c68-qg7gs   1/1     Running   0          56d     10.244.2.233   vm-46-150-centos   <none>           <none>
nginx-ds-mqq4f                      0/1     Pending   0          2m22s   <none>         <none>             <none>           <none>
``` 

I understand a ds pod be scheduled to a node in cluster, it will be bind to the node. So it schedule failed but also display a node ip.  (Maybe i understand is wrong. >-<)

Thanks.

**Comment by pacoxu** [comment]
You can check the pod yaml.
```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - your-node-name
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-09T03:08:12Z"
    message: '0/1 nodes are available: 1 Too many pods.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

DaemonsetController will create a pod for each node with nodeAffinity.
But the kube-scheduler failed to schedule it to the node due to `Too many pods` error.  So I think this is expected.

`kubectl get pod -o wide` shows nodeName of pod.spec.nodeName. It will not check the nodeAffinity.

**Comment by jiaozhenkai** [comment]
> 

Hi, Thanks to reply, this is my ds pod yaml in my test cluster:

```yaml
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - vm-46-150-centos
 ...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-08T09:24:38Z"
    message: '0/1 nodes are available: 1 Too many pods.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Guaranteed
```
And I also check our cluster of product that ds pod be scheduled to failed, every pod have node name in nodeAffinity. So I think `kubetl get po -o wide` show node name is a good idea.

And a ds pod have a nodeAffinity, so whatever I delete it, it will be scheduled to same node.

I try to pull request add this feature.
