### ISSUE TITLE
grpc feature gates - Liveness probe errored: missing probe handler

### ISSUE THREAD

**Issue by koolwithk** [kubernetes/kubernetes#108615]
### What happened?

Enabled [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) `GRPCContainerProbe=true` on my self managed kubernetes v1.23.4

- /etc/kubernetes/manifests/kube-apiserver.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 192.168.0.183:6443
  labels:
    component: kube-apiserver
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.0.183
    # masked output
    - --feature-gates=KubeletPodResources=true,GRPCContainerProbe=true,KubeletPodResourcesGetAllocatable=true
    # masked output
    image: k8s.gcr.io/kube-apiserver:v1.23.4

```
I followed the grpc liveness example mentioned on [docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).
`kubectl apply -f https://k8s.io/examples/pods/probe/grpc-liveness.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: etcd-with-grpc
spec:
  containers:
  - name: etcd
    image: k8s.gcr.io/etcd:3.5.1-0
    command: [ "/usr/local/bin/etcd", "--data-dir",  "/var/lib/etcd", "--listen-client-urls", "http://0.0.0.0:2379", "--advertise-client-urls", "http://127.0.0.1:2379", "--log-level", "debug"]
    ports:
    - containerPort: 2379
    livenessProbe:
      grpc:
        port: 2379
      initialDelaySeconds: 10
```

But When I run `kubectl describe pod etcd-with-grpc` I see Liveness probe errored. 

```sh
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  12m                  default-scheduler  Successfully assigned default/etcd-with-grpc to lp-knode-2.home
  Normal   Pulled     12m                  kubelet            Container image "k8s.gcr.io/etcd:3.5.1-0" already present on machine
  Normal   Created    12m                  kubelet            Created container etcd
  Normal   Started    12m                  kubelet            Started container etcd
  Warning  Unhealthy  114s (x60 over 11m)  kubelet            Liveness probe errored: missing probe handler for etcd-with-grpc_default(349c4a05-4424-4814-9dd5-b8f26a28de17):etcd

```

### What did you expect to happen?

grpc Liveness probe to be in healthy state.

### How can we reproduce it (as minimally and precisely as possible)?

- Enable feature gates **GRPCContainerProbe**
- `kubectl apply -f https://k8s.io/examples/pods/probe/grpc-liveness.yaml`
- `kubectl describe pod etcd-with-grpc`

### Anything else we need to know?

If check with **grpc_health_probe-linux-amd64** I see the status as SERVING.

```
[root@lp-k8control-1 ~]# k get pod -o wide | grep grpc
etcd-with-grpc                        1/1     Running   0          24m   10.47.0.3   lp-knode-2.home   <none>           <none>
[root@lp-k8control-1 ~]# 
[root@lp-k8control-1 ~]# ./grpc_health_probe-linux-amd64 -addr=10.47.0.3:2379
status: SERVING
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
Self managed k8
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.5:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
$ uname -a
Linux lp-k8control-1.home 4.18.0-348.el8.0.2.x86_64 #1 SMP Sun Nov 14 00:51:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
docker://20.10.12
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
{
    "cniVersion": "0.3.0",
    "name": "weave",
    "plugins": [
        {
            "name": "weave",
            "type": "weave-net",
            "hairpinMode": true
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        }
    ]
}
</details>
