### ISSUE TITLE
Mount points not propagated as expected when using subpath.

### ISSUE THREAD

**Issue by yuyue9284** [kubernetes/kubernetes#108681]
### What happened?

We performed mount in shared emptyDir volume subpath in one container, and read the data through the same mounted subpath in another container. And the container failed to read the data under the mount point occasionally. 

After some investigation, I thought this may be caused by the bind options used during the kubelet preparation the subpath. It use `bind` instead  of `rbind`, and if the mount procedure happens before the subpath bind operation, the sub mounts inside the emptyDir won't be picked up by the new subpath.

### What did you expect to happen?

The mount points should be consistent in each container.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  initContainers:
  - image: ubuntu
    command:
    - bash
    args:
    - "-c"
    - "set -x; touch /data/test_data.txt; mkdir /volume-subpath/mount-point/; mount --bind /data/ /volume-subpath/mount-point/; ls /volume-subpath/mount-point/"
    imagePullPolicy: IfNotPresent
    name: init
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /volume-subpath/
      name: volume
      subPath: sub-path-on-volume/
      mountPropagation: Bidirectional
    - mountPath: /data/
      name: mock-data-entry
  containers:
  - image: ubuntu
    command:
    - bash
    args:
    - "-c"
    - "set -x; ls /volume-subpath/; ls /volume-subpath/mount-point/"
    imagePullPolicy: IfNotPresent
    name: main-container
    volumeMounts:
    - mountPath: /volume-subpath/
      name: volume
      subPath: sub-path-on-volume/
      mountPropagation: HostToContainer
  restartPolicy: Always
  volumes:
  - name: volume
    emptyDir: {}
  - name: mock-data-entry
    emptyDir: {}
```

Apply this yaml, and the mount created in the init container won't be accessible by the main-container.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"118c47a50b26423bb47369437d0b7592bf5e67ba", GitTreeState:"clean", BuildDate:"2022-02-07T20:48:54Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
