### ISSUE TITLE
inconsistent behavior between client- and server-side apply

### ISSUE THREAD

**Issue by rittneje** [kubernetes/kubernetes#108708]
### What happened?

I reordered the list of environment variables in a Deployment spec.

With regular `kubectl apply`, this causes the Deployment to change.

With `kubectl apply --server-side`, this does not cause the Deployment to change.

### What did you expect to happen?

I expect client- and server-side apply to work the same.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ubuntu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: ubuntu
  labels:
    app: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: "ubuntu:focal"
          imagePullPolicy: IfNotPresent
          command: ['cat']
          tty: true
          env:
          - name: FOO
            value: foo
          - name: BAR
            value: bar
          resources:
            limits:
              memory: 100Mi
              cpu: 500m
            requests:
              cpu: 100m
              memory: 100Mi
...
```

Use `kubectl apply` to deploy it. Then flip the order of the two env vars and run `kubectl apply` again. Delete the deployment and repeat this exercise with `kubectl apply --server-side`.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rittneje** [comment]
There are more discrepancies between the two. Client-side apply allows the same env var to appear multiple times. Server-side does not. For example:
```yaml
          env:
          - name: FOO
            value: abc
          - name: BAR
            value: $(FOO)
          - name: FOO
            value: def
```

Also, there is a clear bug in server-side apply, because it never respects reordering. First server-side apply this:
```yaml
          env:
          - name: FOO
            value: abc
          - name: BAR
            value: def
```
And then server-side apply this:
```yaml
          env:
          - name: BAR
            value: def
          - name: FOO
            value: $(BAR)
```

Then run `env` inside the container. The value of `FOO` will be reported as `$(BAR)` instead of `def`. And if you look at the Deployment spec, it has it in the wrong order:
```yaml
          env:
            - name: FOO
              value: $(BAR)
            - name: BAR
              value: def
```

So I think there are two distinct bugs with server-side apply (at least in 1.20).
1. It does not account for list items being re-ordered.
2. It does not allow for duplicate entries, but this was never enforced by client-side apply and does not appear to be a documented change.
