### ISSUE TITLE
Waiting containers are marked as Terminated on pod failure

### ISSUE THREAD

**Issue by gautierdelorme** [kubernetes/kubernetes#108733]
**What happened**:

A pod failed due to an initContainer failure and the main container was marked as `Terminated`:

```yaml
initContainerStatuses:
  - state:
      terminated:
        exitCode: 103
        reason: Error
        startedAt: '2022-03-16T07:00:00Z'
        finishedAt: '2022-03-16T07:00:00Z'
        # ...
    lastState: {}
    ready: false
    restartCount: 0
    # ...
containerStatuses:
  - state:
      terminated:
        exitCode: 137
        reason: ContainerStatusUnknown
        message: The container could not be located when the pod was terminated
        startedAt: null
        finishedAt: null
    lastState: {}
    ready: false
    restartCount: 0
    started: false
    # ...
```

**What you expected to happen**:

The main container should stay in `Waiting` since it hasn't started (as described [in the docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-state-terminated): "_A container in the Terminated state began execution and then either ran to completion or failed for some reason_").

```yaml
initContainerStatuses:
  - state:
      terminated:
        exitCode: 103
        reason: Error
        startedAt: '2022-03-15T07:00:00Z'
        finishedAt: '2022-03-15T07:00:00Z'
        # ...
    lastState: {}
    ready: false
    restartCount: 0
    # ...
containerStatuses:
  - state:
      waiting:
        reason: PodInitializing
    lastState: {}
    ready: false
    restartCount: 0
    started: false
    # ...
```

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod with an initContainer that will fail. After the pod fails, inspect the main container status and you should see it in `Terminated` state instead of the `Waiting` expected state.

**Anything else we need to know?**:

I believe it might be a regression from https://github.com/kubernetes/kubernetes/pull/105462 that was [backported in v1.22.3](https://github.com/kubernetes/kubernetes/pull/105496) since we removed the `|| status.ContainerStatuses[i].State.Waiting != nil` check that was making sure only previously-running containers could end up as `Terminated`.

I noticed there was a test added in [kubernetes/kubernetes/pkg/kubelet/status/status_manager_test.go#L639](https://github.com/kubernetes/kubernetes/blob/7152825c0695d62fe06b47cc3e1699095290d73f/pkg/kubelet/status/status_manager_test.go#L639) as part of this PR so I'm not sure if this change was intentional (and undocumented) or just overlooked.

This is problematic since many systems expect `Terminated` containers to have started as documented in the docs. A workaround might be to rely `containerStatuses[i].state.terminated.startedAt` in addition to `containerStatuses[i].state.terminated` but I'm curious to know if this was an intentional change and the documentation should be updated or if it's a regression that should be fixed.

**Environment**:
- Kubernetes version: First saw in `v1.22` and was able to reproduce it in `master`.

/kind bug
/sig node
