### ISSUE TITLE
kubectl should apply OpenAPI schema defaults before OpenAPI schema validation

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/kubernetes#108768]
### What would you like to be added?

Today kubectl runs OpenAPI schema validation on e.g. `kubectl apply` without applying OpenAPI schema defaults before. (although validation can be disabled with --validate=false).

It would be great if kubectl could apply defaults before validation like the apiserver.

### Why is this needed?

Example:

Let's assume we have the following required port field in a CRD:
```yaml
      port:
        description: The port on which the API server is serving.
        format: int32
        default: 6443
        type: integer
```

In this case a user shouldn't have to set the port field because the APIserver first sets the default (6443) before validating if the required field exists.

With `kubectl apply` users get an error that the required field is not set.

A workaround is to use `kubectl apply --validate=false` instead.

Because we don't want to confuse our users, in ClusterAPI we made fields like this optional to avoid forcing users to set required fields on the client-side when they are not actually required because they have a default value.
