### ISSUE TITLE
[windows] - Update e2e tests that perform reboots to leverage node.BootId

### ISSUE THREAD

**Issue by marosset** [kubernetes/kubernetes#108886]
### What would you like to be added?

https://github.com/kubernetes/kubernetes/pull/108704 adds `BootId` support for Windows nodes.

We have some e2e tests in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/reboot_node.go to perform a reboot but do not have a great way to determine when the reboot finished.
We should update those tests to look for a change in the BootId property for the node.

### Why is this needed?

This will increase the reliability of some of the Windows e2e tests and possible save some time.

**Comment by markyjackson-taulia** [comment]
@jsturtevant Is it ok to remove the milestone?

**Comment by jayunit100** [comment]
The boot ID looks like this

```
 nodeInfo:
    architecture: amd64
    bootID: a73baaf1-cf07-420b-b57f-6ea4e8c9d8dc
    containerRuntimeVersion: containerd://1.6.4
    kernelVersion: 4.15.0-197-generic
    kubeProxyVersion: v1.24.0
    kubeletVersion: v1.24.0
    machineID: 8c81e63035e64e72abb34e8cddb7ea6c
    operatingSystem: linux
```
