### ISSUE TITLE
Getting  unknown field "HostNetwork" in io.k8s.api.core.v1.PodSpec

### ISSUE THREAD

**Issue by jzfb2** [kubernetes/kubernetes#108861]
### What happened?

Despite being documented, I'm getting  'unknown field "HostNetwork" in io.k8s.api.core.v1.PodSpec' when setting HostNetwork to true.

Output: 
error: error validating "STDIN": error validating data: ValidationError(Job.spec.template.spec): unknown field "HostNetwork" in io.k8s.api.core.v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false

### What did you expect to happen?

The manifest is accepted.

### How can we reproduce it (as minimally and precisely as possible)?

deployment:
<details>

```

apiVersion: batch/v1
kind: Job
metadata:
  name:  ...
spec:
  parallelism: 1
  template:
    spec:
      serviceAccountName: ...
      HostNetwork: true
      volumes:
...
      containers:
      - name:  ...
        image:  ...
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 0       
        env:
...
        securityContext:
...
        volumeMounts:
...
        command: 
        - sh
        - -c
        - |
          python3 /app/server.py; 
      restartPolicy: Never
  backoffLimit: 0

```

</details>

### Kubernetes version

<details>
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
Internal (not external cloud provider)
</details>

### OS version
</code>
<details>

Linux CentOS 7

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
