### ISSUE TITLE
kubectl command does not work after nodeport 8080 is applied in a cluster without taint

### ISSUE THREAD

**Issue by Fluxay-666** [kubernetes/kubernetes#108840]
Sorry, it's my first time to submit a question, I'm not very good at using it, the following is my question

I executed kubectl get pod but not normal return
```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

and I found that after executing kubectl config view

```
apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null
```
This is the return, but the pod of the cluster is still running normally, I use kubectl get pod --kubeconfig=kubelet.kubeconfig It is possible to return normally

And the message log also has this output
```
Mar 21 16:16:10 k8s-master1 kube-controller-manager: E0321 16:16:10.848600   30618 leaderelection.go:320] error retrieving resource lock kube-system/kube-controller-manager: Get http://127.0.0.1:8080/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Mar 21 16:16:12 k8s-master1 kube-scheduler: E0321 16:16:12.692066   29827 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.PodDisruptionBudget: Get http://127.0.0.1:8080/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8080: i/o timeout
```

I restarted the service but it has left it unreachable
Hope to get response and answer, thank you

**Comment by ardaguclu** [comment]
There are 2 possible ways; 
* Your api server which is running in `localhost:8080` is not healthy or even not running
* You api server is healthy but running in different hostname. If that is the case, you are using the correct kubeconfig file. 
According to your comments, I imagine that your api server is healthy but you are using incorrect kubeconfig file. 

Thus, I'd suggest to check your kubeconfig.

/kind support

**Comment by neolit123** [comment]
/sig cli network

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
^ might be the better place to ask.

**Comment by Fluxay-666** [comment]
> 有两种可能的方式；
> 
> * 您正在运行的 api 服务器`localhost:8080`不健康甚至没有运行
> * 您的 api 服务器是健康的，但在不同的主机名中运行。如果是这种情况，则说明您没有使用正确的 kubeconfig 文件。
>   根据您的评论，我想您的 api 服务器是健康的，但您使用的 kubeconfig 文件不正确。
> 
> /善良的支持

Hello,thanks for your response, I have caused this after applying a svc as follows, I was using the same kubeconfig before

```
apiVersion: v1
kind: Service
metadata:
  name: etcd-registry
  labels:
    name: etcd-registry
spec:
  type: NodePort
  ports:
  - port: 2379
    nodePort: 12379
    targetPort: 2379
    name: "2379"
  - port: 2380
    nodePort: 12380
    targetPort: 2380
    name: "2380"
  - port: 4001
    nodePort: 14001
    targetPort: 4001
    name: "4001"
  - name: etcdkeeper
    nodePort: 18080
    port: 8080
    targetPort: 8080
  selector:
    name: etcd-registry
```

This is the svc of my application, I don't know what the reason is, after that the kubectl command is no longer available and can be used normally
