### ISSUE TITLE
volumeClaimTemplates in statefulset not work well in windows containerd runtime

### ISSUE THREAD

**Issue by xiaoping8385** [kubernetes/kubernetes#108868]
### What happened?

we deployed stateful yaml in windows containerd env, the yaml is like 
```

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: http-https-echo-svc
  name: http-https-echo-svc
spec:
  ports:
    - port: 80
  selector:
    app: http_https_echo
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-web-0
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-web-1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-web-2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "statefulset-web"
  replicas: 3
  selector:
    matchLabels:
      app: http_https_echo
  template:
    metadata:
      labels:
        app: http_https_echo
    spec:
      containers:
      - name: statefulset-web
        image: mcr.microsoft.com/windows/servercore:1809
        command:
        - powershell.exe
        - -command
        - "<#code used from https://gist.github.com/wagnerandrade/5424431#> ; $$listener = New-Object System.Net.HttpListener ; $$listener.Prefixes.Add('http://*:80/') ; $$listener.Start() ; $$callerCounts = @{} ; Write-Host('Listening at http://*:80/') ; while ($$listener.IsListening) { ;$$context = $$listener.GetContext() ;$$requestUrl = $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;$$count = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$ip=(Get-NetAdapter | Get-NetIpAddress); $$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f $$ip[1].IPAddress,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer = [System.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close() ;$$responseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ; "
        lifecycle:
          postStart:
            exec:
              command: ["curl", "http://10.216.168.198/swalunj/pkswindows-test-resources/nc64.exe", "--output", "nc.exe"]
        volumeMounts:
        - name: www
          mountPath: "c:\\var\\run"
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
      - key: "windows"
        operator: "Equal"
        value: "2019"
        effect: "NoSchedule"
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

but but we found an error like :

```

Events:
  Type     Reason                  Age                   From               Message
---          -----                     ----                  -------          --------------
  Warning  FailedScheduling        57m                   default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               57m                   default-scheduler  Successfully assigned default/web-0 to f8cf1bfa-667e-434b-9a38-7b24587ce2d9
  Normal   Pulling                 56m                   kubelet            Pulling image "mcr.microsoft.com/windows/servercore:1809"
  Normal   Pulled                  51m                   kubelet            Successfully pulled image "mcr.microsoft.com/windows/servercore:1809" in 4m51.0014225s
  Normal   Created                 49m (x5 over 51m)     kubelet            Created container statefulset-web
  Normal   Pulled                  49m (x4 over 51m)     kubelet            Container image "mcr.microsoft.com/windows/servercore:1809" already present on machine
  Warning  Failed                  49m (x5 over 51m)     kubelet            Error: failed to create containerd task: failed to create shim: hcs::CreateComputeSystem statefulset-web: The parameter is incorrect.: unknown
  Warning  BackOff                 106s (x227 over 51m)  kubelet            Back-off restarting failed container
```

Check the containerd log, we found
```

arentSpanID=a7c01c1a451df017 path="C:\\var\\vcap\\data\\containerd-root\\io.containerd.snapshotter.v1.windows\\snapshots\\11" spanID=b8e94e6e8328d775 startTime="2022-03-22 09:22:11.8882204 +0000 GMT m=+349.137228201" traceID=b16866770a2665846a99bdf8947bdbf2
time="2022-03-22T09:22:11.550924000Z" level=error msg=Span bundle="C:\\var\\vcap\\data\\containerd-state\\io.containerd.runtime.v2.task\\k8s.io\\69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e" checkpoint= duration=357.3853ms endTime="2022-03-22 09:22:11.9083093 +0000 GMT m=+349.157319801" error=
"hcs::CreateComputeSystem 69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e: The parameter is incorrect." name=Create parentSpanID=dc0150d241f4e348 parentcheckpoint= pod-id=a580ee482dd19fa632b8dfbce02cdd6e30f7bbe1420a50bffcc19ea93dc66b26 spanID=a7c01c1a451df017 startTime="2022-03-22 09:22:11.550924
 +0000 GMT m=+348.799934501" stderr="\\\\.\\pipe\\ctr-69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e-stderr" stdin= stdout="\\\\.\\pipe\\ct
r-69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e-stdout" terminal=false tid=69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e traceID=b16866770a2665846a99bdf8947bdbf2
time="2022-03-22T09:22:11.550924000Z" level=info msg=Span duration=359.6243ms endTime="2022-03-22 09:22:11.9105483 +0000 GMT m=+349.159558801" name=containerd.task.v2.Task.Create parentSpanID=0000000000000000 spanID=dc0150d241f4e348 startTime="2022-03-22 09:22:11.550924 +0000 GMT m=+348.799934501" traceID=b168667
70a2665846a99bdf8947bdbf2
time="2022-03-22T09:22:11.910551200Z" level=error msg=Span duration=0s eid= endTime="2022-03-22 09:22:11.9105512 +0000 GMT m=+349.159558801" error="rpc error: code = NotFound desc = task with id: '69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e' not found: not found" name=Delete parentSpanID=83a8
1bb68651e344 pod-id=a580ee482dd19fa632b8dfbce02cdd6e30f7bbe1420a50bffcc19ea93dc66b26 spanID=4e67e8fd897aef13 startTime="2022-03-22 09:22:11.9105512 +0000 GMT m=+349.159558801" tid=69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e traceID=6c6305a334a3164d9a91057f0debcb0d
time="2022-03-22T09:22:11.910551200Z" level=info msg=Span duration=0s endTime="2022-03-22 09:22:11.9105512 +0000 GMT m=+349.159558801" name=containerd.task.v
2.Task.Delete parentSpanID=0000000000000000 spanID=83a81bb68651e344 startTime="2022-03-22 09:22:11.9105512 +0000 GMT m=+349.159558801" traceID=6c6305a334a3164d9a91057f0debcb0d
time="2022-03-22T09:22:11.910551200Z" level=info msg=Span duration=0s endTime="2022-03-22 09:22:11.9105512 +0000 GMT m=+349.159558801" name=Shutdown parentSpanID=1926b5458da3fbe2 pod-id=a580ee482dd19fa632b8dfbce02cdd6e30f7bbe1420a50bffcc19ea93dc66b26 spanID=e4e4818d90cc07b2 startTime="2022-03-22 09:22:11.9105512 
+0000 GMT m=+349.159558801" tid=69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e traceID=0f0a56a841259dd70251d42f0b2d9ad1
time="2022-03-22T09:22:11.910551200Z" level=info msg=Span duration="510.4Âµs" endTime="2022-03-22 09:22:11.9110616 +0000 GMT m=+349.160069201" name=container
d.task.v2.Task.Shutdown parentSpanID=0000000000000000 spanID=1926b5458da3fbe2 startTime="2022-03-22 09:22:11.9105512 +0000 GMT m=+349.159558801" traceID=0f0a56a841259dd70251d42f0b2d9ad1
time="2022-03-22T09:22:11.911093200Z" level=info msg="shim disconnected" id=69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e
time="2022-03-22T09:22:11.911093200Z" level=warning msg="cleaning up after shim disconnected" id=69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694
575e namespace=k8s.iotime="2022-03-22T09:22:11.911093200Z" level=info msg="cleaning up dead shim"
time="2022-03-22T09:22:11.980843600Z" level=warning msg="cleanup warnings time=\"2022-03-22T09:22:11Z\" level=error msg=Span duration=5.6088ms endTime=\"2022-03-22 09:22:11.9302335 +0000 GMT m=+0.010864401\" error=\"A virtual machine or container with the specified identifier does not exist.\" name=HcsOpenCompute
System parentSpanID=0d0410e8f553b762 spanID=deb24235cb4daf11 startTime=\"2022-03-22 09:22:11.9246247 +0000 GMT m=+0.005255601\" traceID=85b7e53ad1d7e8561d8452763686b658\ntime=\"2022-03-22T09:22:11Z\" level=info msg=Span duration=31.232ms endTime=\"2022-03-22 09:22:11.9558567 +0000 GMT m=+0.036487601\" name=delete
 parentSpanID=0000000000000000 spanID=0d0410e8f553b762 startTime=\"2022-03-22 09:22:11.9246247 +0000 GMT m=+0.005255601\" traceID=85b7e53ad1d7e8561d8452763686b658\n"
time="2022-03-22T09:22:16.541687700Z" level=error msg="Failed to pipe stdout of container \"69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e\"" error="file has already been closed"
time="2022-03-22T09:22:16.541687700Z" level=error msg="Failed to pipe stderr of container \"69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e\
"" error="file has already been closed"time="2022-03-22T09:22:16.543682700Z" level=error msg="StartContainer for \"69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e\" failed" error=
"failed to create containerd task: failed to create shim: hcs::CreateComputeSystem 69afdf219035297aeda9d74480419e25b50aa2e7518efbb81aa698e26694575e: The para
meter is incorrect.: unknown"time="2022-03-22T09:22:16.940658300Z" level=info msg="RemoveContainer for \"589110775a91c5617cee0229fbbcc0714655573cac486f47163110422b97d96d\""
time="2022-03-22T09:22:16.946732000Z" level=info msg="RemoveContainer for \"589110775a91c5617cee0229fbbcc0714655573cac486f47163110422b97d96d\" returns succes
sfully"
```

### What did you expect to happen?

it should work the statefulset should be deployed successfully. 

### How can we reproduce it (as minimally and precisely as possible)?

deploy the above statefulset.yml to windows containerd enviroment

### Kubernetes version

<details>

```console
$ kubectl version
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2+vmware.1", GitCommit:"8b932107b754fcea31c933314335ee6b550d3fc7", GitTreeState:"clean", BuildDate:"2022-01-21T20:34:02Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
PS C:\> wmic os get Caption
Caption
Microsoft Windows Server 2019 Datacenter Evaluation

PS C:\> wmic os get Version
Version     
10.0.17763

PS C:\> wmic os get BuildNumber
BuildNumber  
17763

PS C:\> wmic os get OSArchitecture
OSArchitecture  
64-bit
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd-v1.5.7
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>
