### ISSUE TITLE
AzureDisk in-tree tests don't work with CSI migration & single-zone Azure regions

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#108980]
### What happened?

This test fails on Kubernetes cluster in "westus" region (without any number) and with CSI migration enabled:

`[sig-storage] In-tree Volumes [Driver: azure-disk] [Testpattern: Dynamic PV (delayed binding)] topology should provision a volume and schedule a pod with AllowedTopologies`

Error:
`
failed to provision volume with StorageClass "e2e-topology-84vk7sp": error generating accessibility requirements: topology map[topology.disk.csi.azure.com/zone:] from selected node "ci-op-9j1nby77-e54d5-9zlwv-worker-westus-ljw4g" is not in requisite: [map[topology.disk.csi.azure.com/zone:0]]
`

StorageClass generated by the test:

```yaml
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - "0"
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: e2e-topology-84vk7sp
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

PVC created by the test:
<details>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
    volume.kubernetes.io/selected-node: ci-op-9j1nby77-e54d5-9zlwv-worker-westus-ljw4g
    volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
  creationTimestamp: "2022-03-24T12:36:08Z"
  finalizers:
  - kubernetes.io/pvc-protection
  generateName: pvc-
  name: pvc-ph9tb
  namespace: e2e-topology-84
  resourceVersion: "135683"
  uid: 7596de95-b733-46d3-93f2-f1309a244d20
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: e2e-topology-84vk7sp
  volumeMode: Filesystem
```

</details>

Labels of the selected node:
```yaml
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: Standard_D4s_v3
    beta.kubernetes.io/os: linux
    failure-domain.beta.kubernetes.io/region: westus
    failure-domain.beta.kubernetes.io/zone: "0"
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: ci-op-9j1nby77-e54d5-9zlwv-worker-westus-ljw4g
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
    node.kubernetes.io/instance-type: Standard_D4s_v3
    node.openshift.io/os_id: rhcos
    topology.disk.csi.azure.com/zone: ""
    topology.hostpath.csi/node: ci-op-9j1nby77-e54d5-9zlwv-worker-westus-ljw4g
    topology.kubernetes.io/region: westus
    topology.kubernetes.io/zone: "0"
```

The external-provisioner does not even call the CSI driver and reports this event:

```
failed to provision volume with StorageClass "e2e-topology-84vk7sp": error generating accessibility requirements: topology map[topology.disk.csi.azure.com/zone:] from selected node "ci-op-9j1nby77-e54d5-9zlwv-worker-westus-ljw4g" is not in requisite: [map[topology.disk.csi.azure.com/zone:0]]
```

### What did you expect to happen?

The volume should get provisioned.

### How can we reproduce it (as minimally and precisely as possible)?

See above, "westus" region with no availability zones seems to be the key.

### Anything else we need to know?

It looks like the translation from in-tree StorageClass to CSI one translates topology requirements to `topology.disk.csi.azure.com/zone: "0"`, but the CSI one expects `topology.disk.csi.azure.com/zone: ""`

### Kubernetes version

<details>

```console
v1.23.3-2024+54654d2ba49457-dirty
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
OpenShift 4.10
</details>

**Comment by jsafrane** [comment]
/priority important-soon
cc @andyzhangx

**Comment by andyzhangx** [comment]
@jsafrane per https://kubernetes-sigs.github.io/cloud-provider-azure/topics/availability-zones/#node-labels, `topology.disk.csi.azure.com/zone: "0"` is not a zone, it's actually a fault-domain num. valid zone format is `topology.disk.csi.azure.com/zone: "westus-0"`, could you change the storage class with `topology.disk.csi.azure.com/zone: "westus-0"` setting, and try again? Thanks.

**Comment by andyzhangx** [comment]
o, if "westus" region does not support zone, then I think you should test `allowedTopologies` setting in another zone, make sure you have created a zoned node first.

**Comment by jsafrane** [comment]
I have as SC that works without CSI migration, with CSI migration it does not work. That's a regression. It should not matter if the SC is somehow odd. The labels are selected by test code, some other production code might use these labels too.

**Comment by jsafrane** [comment]
Out of curiosity, how reliable are zone numbers in Azure? I can see `centralus-1` .. `cetralus-3` in a region with zones. If `"0"` is used **only** in regions without a zone, then the translation can translate `"0"` to `""`, which the CSI driver expects.

**Comment by andyzhangx** [comment]
@jsafrane I would say that's a wrong usage for zone. following config would create a pv that could only be scheduled to a non-zone node with fault domain `0`, if there is no node supports zone, then `allowedTopologies` should not be set.

```
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - "0"
```

**Comment by andyzhangx** [comment]
@jsafrane if we translation "0" to "", then the pv created by that sc could be scheduled to any non zone node with any fault domain. That's a corner case that cluster is not in zone, and user still wants to set `allowedTopologies` in sc

**Comment by jsafrane** [comment]
I am not sure I understand. If I provision a CSI volume in the westus cluster, its PV gets `zone: ""` anyway:

```
nodeAffinity:
    required:
      nodeSelectorTerms
      - matchExpressions:
        - key: topology.disk.csi.azure.com/zone
          operator: In
          values:
          - ""
```

I have the cluster only with nodes in "westus" region, so all of them are without any zone. What would the CSI driver do if there were nodes in "westus" and say "ukwest", which does not have zones either? I can't test that setup easily, but I think the driver would report `topology.disk.csi.azure.com/zone: ""` for both of them anyway, hence translating `"0"` to `""` does not make things worse, I think.
