### ISSUE TITLE
Creation of PV then PVC not equivalent to PVC request on Minikube host standard storage class

### ISSUE THREAD

**Issue by ivandir** [kubernetes/kubernetes#108926]
### What happened?

Executing kubectl apply on the following yields different results. 
```

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkinsvolume 
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /tmp/hostpath-provisioner/default/jenkinsnew
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem

```
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinsnew
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: jenkinsvolume

```
The above PVC can be attached to a jenkins pod but cannot create directories and files due to permissions issues.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkinsnew
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
```

When it creates the PV automatically from PVC and attaching this same named PVC to jenkins pod it allows for creation of directories without permission issues.

### What did you expect to happen?

PV+PVC creation to be equivalent to PVC creation since all it's doing is allocating a PV which I'm already referencing via volumeName.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a new minikube environment.
2. Create PV and PVC or just PVC via kubectl apply -f <filenames>
3. Using helm chart located here https://charts.bitnami.com/bitnami
4. Set this values for the chart
persistence:
  existingClaim: jenkinsnew

You will see the following issue:
jenkins 14:47:52.40 
jenkins 14:47:52.40 Welcome to the Bitnami jenkins container
jenkins 14:47:52.40 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-jenkins
jenkins 14:47:52.40 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-jenkins/issues
jenkins 14:47:52.40 
jenkins 14:47:52.41 INFO  ==> Configuring libnss_wrapper
jenkins 14:47:52.42 INFO  ==> ** Starting Jenkins setup **
mkdir: cannot create directory '/bitnami/jenkins/home': Permission denied

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Minikube
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Darwin C02D64XJMD6P 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
minikube start --memory=4096 --driver=hyperkit --cpus=4 --disk-size=20g
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
