### ISSUE TITLE
resource request > limit in statefulset PodTemplateSpec

### ISSUE THREAD

**Issue by heartlock** [kubernetes/kubernetes#108904]
### What happened?

```
~# kubectl create -f sts.yaml
statefulset.apps/test-sts created
```
sts.yaml as below:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    appgroup: ""
    version: v1
  name: test-sts
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-sts
      version: v1
  serviceName: test-sts-headless
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      creationTimestamp: null
      labels:
        app: test-sts
        version: v1
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: container-0
        resources:
          limits:
            cpu: 250m
            memory: 511Mi
          requests:
            cpu: 250m
            memory: 512Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
```
create statefulset succeed, but request mem > limit mem in PodTemplateSpec

### What did you expect to happen?

fail to create statefulset because request mem > limit mem in PodTemplateSpec

### How can we reproduce it (as minimally and precisely as possible)?

kubectl create -f sts.yaml
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    appgroup: ""
    version: v1
  name: test-sts
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-sts
      version: v1
  serviceName: test-sts-headless
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      creationTimestamp: null
      labels:
        app: test-sts
        version: v1
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: container-0
        resources:
          limits:
            cpu: 250m
            memory: 511Mi
          requests:
            cpu: 250m
            memory: 512Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-alpha.0.27+0153febd9f0098", GitCommit:"0153febd9f0098d4b8d0d484927710eaf899ef40", GitTreeState:"clean", BuildDate:"2021-12-07T01:49:48Z", GoVersion:"go1.17.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-08T00:29:07Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
