### ISSUE TITLE
Use template metadata.name when creating pods from Job/CronJob

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#108977]
### What happened?

When create job && cronJob with template metadata name specified, the metadata name of job-name or pod-name will not take effect.

Demo:
cronJob.yaml
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-name
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      name: job-name
    spec:
      template:
        metadata:
          name: pod-name
        spec:
          containers:
          - image: busybox
          ...
```
job.yaml
```
apiVersion: batch/v1
kind: Job
metadata:
  name: job-name
spec:
  template:
    metadata:
      name: pod-name
    spec:
      containers:
      - image: busybox
      ...
```

The job-name created by demo-cronjob is just like `cronjob-name-xxx`, and the pod-name is just like `cronjob-name-xxx-xxx`;
The job-name created by demo-job is just like `job-name`, and the pod-name is just like `job-name-xxx`;

The issue is: the metadata name not take effect accordingly.

### What did you expect to happen?

To honor the template metadata name, and take it into effect. 

### How can we reproduce it (as minimally and precisely as possible)?

Apply the Demo yaml above, then check the result resources.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
