### ISSUE TITLE
secret with space after --from-literal=password='password'  creates different base64 password.

### ISSUE THREAD

**Issue by samirpatry** [kubernetes/kubernetes#108933]
### What happened?

created secret with regular command but due space after password it generates different base64 string.
e.g

`kubectl create secret generic flux-gitrepo-creds --from-literal=username=samir.patry --from-literal=password='MTQyMzM1MTE0MzE5Ouep7a7j/vXo6CyhD9obRiTB5fj5'  -n flux-system --dry-run=client -o yaml`

`apiVersion: v1
data:
  password: **TVRReU16TTFNVEUwTXpFNU91ZXA3YTdqL3ZYbzZDeWhEOW9iUmlUQjVmajU=**
  username: c2FtaXIucGF0cnk=
kind: Secret
metadata:
  creationTimestamp: null
  name: flux-gitrepo-creds
  namespace: flux-system`

`kubectl create secret generic flux-gitrepo-creds --from-literal=username=samir.patry --from-literal=password='MTQyMzM1MTE0MzE5Ouep7a7j/vXo6CyhD9obRiTB5fj5'  -n flux-system --dry-run=client -o yaml`

apiVersion: v1
data:
  password: **TVRReU16TTFNVEUwTXpFNU91ZXA3YTdqL3ZYbzZDeWhEOW9iUmlUQjVmajWg**
  username: c2FtaXIucGF0cnk=
kind: Secret
metadata:
  creationTimestamp: null
  name: flux-gitrepo-creds
  namespace: flux-system

NAME                 STATUS   ROLES                  AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION                CONTAINER-RUNTIME
kind-control-plane   Ready    control-plane,master   14h   v1.21.1   172.20.0.2    <none>        Ubuntu 21.04   3.10.0-1160.59.1.el7.x86_64   containerd://1.5.2

### What did you expect to happen?

it should ignore the space after password with single quote 
echo -n 'MTQyMzM1MTE0MzE5Ouep7a7j/vXo6CyhD9obRiTB5fj5' | openssl base64
**TVRReU16TTFNVEUwTXpFNU91ZXA3YTdqL3ZYbzZDeWhEOW9iUmlUQjVmajU=**

### How can we reproduce it (as minimally and precisely as possible)?

kubectl create secret generic flux-gitrepo-creds --from-literal=username=samir.patry --from-literal=password='MTQyMzM1MTE0MzE5Ouep7a7j/vXo6CyhD9obRiTB5fj5'  -n flux-system --dry-run=client -o yaml

kubectl create secret generic flux-gitrepo-creds --from-literal=username=samir.patry --from-literal=password='MTQyMzM1MTE0MzE5Ouep7a7j/vXo6CyhD9obRiTB5fj5'  -n flux-system --dry-run=client -o yaml

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux internalkind78 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kind-cluster
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.5.2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by samirpatry** [comment]
this need to be part of k8s secrets no ?

**Comment by liggitt** [comment]
I can't reproduce this... both commands result in the same output:

```
kubectl create secret generic flux-gitrepo-creds --from-literal=username=samir.patry --from-literal=password='MTQyMzM1MTE0MzE5Ouep7a7j/vXo6CyhD9obRiTB5fj5' -n flux-system --dry-run=client -o yaml

apiVersion: v1
data:
  password: TVRReU16TTFNVEUwTXpFNU91ZXA3YTdqL3ZYbzZDeWhEOW9iUmlUQjVmajU=
  username: c2FtaXIucGF0cnk=
kind: Secret
metadata:
  creationTimestamp: null
  name: flux-gitrepo-creds
  namespace: flux-system

kubectl create secret generic flux-gitrepo-creds --from-literal=username=samir.patry --from-literal=password='MTQyMzM1MTE0MzE5Ouep7a7j/vXo6CyhD9obRiTB5fj5'  -n flux-system --dry-run=client -o yaml

apiVersion: v1
data:
  password: TVRReU16TTFNVEUwTXpFNU91ZXA3YTdqL3ZYbzZDeWhEOW9iUmlUQjVmajU=
  username: c2FtaXIucGF0cnk=
kind: Secret
metadata:
  creationTimestamp: null
  name: flux-gitrepo-creds
  namespace: flux-system
```
