### ISSUE TITLE
When define nodeName field in deployment yaml, cannot bind local persistent volume through nodeAffinity

### ISSUE THREAD

**Issue by HirazawaUi** [kubernetes/kubernetes#109063]
### What happened?

I use local volume as persistent volume and local StorageClass, the volumeBindingMode field of StorageClass is WaitForFirstConsumer. I want define nodeName field in deployment yaml for scheduling pods to nodes and I defined the filed of nodeAffinity in pv yaml, But the pod is in the ContainerCreating state, and kubectl describe displays the error "error processing PVC mysql/mysql-pvc: PVC is not bound". when I define the nodeAffinity field in the deeployment yaml, everything works fine.

  I saw that in the kube-scheduler code, when the define nodeName field in deployment yaml, the process of scheduling is skipped directly, but the relationship between bind pod and persistent volume is implemented in schedule code.

  Please ask if the kube-scheduler code needs to be modified, or if I have to use nodeAffinity filed in the deployment yaml

### What did you expect to happen?

Pods can be created normally, and bind persistent volumes

### How can we reproduce it (as minimally and precisely as possible)?

 use local volume as persistent volume and local StorageClass,  the volumeBindingMode field of StorageClass is WaitForFirstConsumer. then define nodeName field in deployment yaml and define the filed of nodeAffinity in pv yaml

### Anything else we need to know?

deployment yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
     app: mysql-deploy
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-pod
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      nodeName: n1.devops.dev.local
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:5.6
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: "/var/lib/mysql"
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
```
pv.yml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: "/opt/mysql/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key:  kubernetes.io/arch
          operator: In
          values:
          - amd64
```
pvc.yml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mysql
  labels:
    app: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-storage
```
storageclass.yaml
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:50:34Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

None

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux m1.devopsman.dev.local 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
```
Container runtime: Docker
version: 20.10.7
```
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
