### ISSUE TITLE
[sig-node] Node Performance Testing [Serial] [Slow] Run node performance testing with pre-defined workloads TensorFlow workload

### ISSUE THREAD

**Issue by ruiwen-zhao** [kubernetes/kubernetes#109295]
### Which jobs are failing?

[sig-node-containerd#node-kubelet-containerd-performance-test](https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-performance-test)

### Which tests are failing?

E2eNode Suite.[sig-node] Node Performance Testing [Serial] [Slow] Run node performance testing with pre-defined workloads TensorFlow workload

### Since when has it been failing?

From the testgrid, it has been 1/2 flaky since the start of history (03/20/2022) and has been failing constantly (0/2) since 04/01/2022

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-performance-test

### Reason for failure (if possible)

```
E2eNode Suite: [sig-node] Node Performance Testing [Serial] [Slow] Run node performance testing with pre-defined workloads TensorFlow workload expand_less | 37s
-- | --
{ Failure test/e2e_node/node_perf_test.go:172 wait for pod "tensorflow-wide-deep-pod" to succeed Expected success, but got an error:     <*errors.errorString \| 0xc000722840>: {         s: "pod \"tensorflow-wide-deep-pod\" failed with reason: \"\", message: \"\"",     }     pod "tensorflow-wide-deep-pod" failed with reason: "", message: "" test/e2e/framework/pods.go:240}
```

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
The failing test seems to be expecting GPU on machine and the image seems to be broken.

I tried the image manually:

```
apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-wide-deep-ctn
spec:
  containers:
  - name: tensorflow-wide-deep-ctn
    image: k8s.gcr.io/e2e-test-images/node-perf/tf-wide-deep:1.1
    command: ["/bin/sh"]
    args: ["-c", "python ./data_download.py && time -p python ./wide_deep.py --model_type=wide_deep --train_epochs=300 --epochs_between_evals=300 --batch_size=32561"]
```

Logs:

```
kubectl logs tensorflow-wide-deep-ctn
2022-04-19 21:24:17.714218: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 21:24:17.714292: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "./data_download.py", line 71, in <module>
    tf.app.run(argv=[sys.argv[0]] + unparsed)
AttributeError: module 'tensorflow' has no attribute 'app'
```
