### ISSUE TITLE
openapi for custom resources references second set of meta types (ObjectMeta_v2, etc)

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#109275]
Noticed while reproducing https://github.com/kubernetes/kubernetes/issues/109215#issuecomment-1087037419 with client-side validation:

> `error: error validating "/Users/liggitt/tmp/default-spiffeid.yaml.txt": error validating data: ValidationError(SpiffeID.metadata): unknown field "unknown" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta_v2; if you choose to ignore these errors, turn validation off with --validate=false`

The `ObjectMeta_v2` bit was weird...

Steps to reproduce:

1. Verify published openapi only contains expected metadata definitions:

```
kubectl get --raw /openapi/v2 | jq -r '.definitions | keys | .[]' | sort | grep io.k8s.apimachinery.pkg.apis.meta.v1
```

2. Create a CRD, e.g. simple-crd.yaml:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          foo:
            type: string
  names:
    singular: foo
    plural: foos
    kind: Foo
    listKind: FooList
```

```
kubectl apply -f simple-crd.yaml
```

3. Look at published openapi:

```
kubectl get --raw /openapi/v2 | jq -r '.definitions | keys | .[]' | sort | grep io.k8s.apimachinery.pkg.apis.meta.v1 | grep _

io.k8s.apimachinery.pkg.apis.meta.v1.DeleteOptions_v2
io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta_v2
io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference_v2
io.k8s.apimachinery.pkg.apis.meta.v1.StatusDetails_v2
io.k8s.apimachinery.pkg.apis.meta.v1.Status_v2
```

4. See where the _v2 definition is referenced:

```
kubectl get --raw /openapi/v2 | jq . | grep ObjectMeta_v2

          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta_v2"
    "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta_v2": {
```

```
kubectl get --raw /openapi/v2 | jq . | grep definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta_v2 -B 17
  "definitions": {
    "com.example.v1.Foo": {
      "type": "object",
      "properties": {
        "apiVersion": {
          "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
          "type": "string"
        },
        "foo": {
          "type": "string"
        },
        "kind": {
          "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
          "type": "string"
        },
        "metadata": {
          "description": "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta_v2"
```

For some reason, the same server publishing openapi for built-in types and custom resource definitions thinks the openapi definition differs.

Reproduced against at least the following branches:
* master
* release-1.23
* release-1.22
* release-1.21

In addition to fixing this to make `kube-apiserver` coherently refer to ObjectMeta definitions from built-in and custom types, we need a test for this scenario to ensure it doesn't creep back in.
