### ISSUE TITLE
Unable to create pod in minikube 

### ISSUE THREAD

**Issue by mehmood8** [kubernetes/kubernetes#109327]
below is my yml file 

```
kind: Pod
apiVersion: v1
metadata:
  name: testpod4
spec:
  containers:
    - name: c00
      image: httpd
      ports:
       - containerPort: 80  
```
 kubectl apply -f pod1.yml

error:error validating "ppod.yml" error validation :kind not set; if you choose to ignore these error, turn validation off with --validate=false
