### ISSUE TITLE
kubectl describe pod is missing env var values populated by downward API (spec.nodeName, status.podIP)

### ISSUE THREAD

**Issue by rsalmond** [kubernetes/kubernetes#109482]
### What happened?

Deployed this manifest and described a resulting pod.

nginx.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
```

```console
k describe po nginx-675894fc8b-fcjk8
Name:         nginx-675894fc8b-fcjk8
Namespace:    default
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Wed, 13 Apr 2022 17:25:28 -0400
Labels:       app=nginx
              pod-template-hash=675894fc8b
Annotations:  <none>
Status:       Running
IP:           172.17.0.4
IPs:
  IP:           172.17.0.4
Controlled By:  ReplicaSet/nginx-675894fc8b
Containers:
  nginx:
    Container ID:   docker://9c163032aeaf8b0631e96f555f06d4ec981a4c0b01bf02fae818fe9b5e8e0236
    Image:          nginx:latest
    Image ID:       docker-pullable://nginx@sha256:2275af0f20d71b293916f1958f8497f987b8d8fd8113df54635f2a5915002bf1
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 13 Apr 2022 17:25:36 -0400
    Ready:          True
    Restart Count:  0
    Environment:
      MY_NODE_NAME:       (v1:spec.nodeName) 👈
      MY_POD_NAME:       nginx-675894fc8b-fcjk8 (v1:metadata.name)
      MY_POD_NAMESPACE:  default (v1:metadata.namespace)
      MY_POD_IP:          (v1:status.podIP) 👈
```

hat tip @zahin-mohammad for pointing this out

### What did you expect to happen?

kubectl describe pod would show all env var values populated by the downward API.

### How can we reproduce it (as minimally and precisely as possible)?

minikube start
kubectl apply -f nginx.yaml
kubectl describe pod $(kubectl get pods --template '{{range .items}}{{.metadata.name}}{{end}}' --selector=app=nginx)

### Anything else we need to know?

The environment variables are correctly populated inside the running pod.

```console

$ minikube ssh
docker@minikube:~$ docker inspect $(docker ps --filter ancestor=nginx --format '{{ .ID }}') | grep MY_
                "MY_NODE_NAME=minikube",
                "MY_POD_NAME=nginx-675894fc8b-fcjk8",
                "MY_POD_NAMESPACE=default",
                "MY_POD_IP=172.17.0.4",
```

### Kubernetes version

<details>

```console
minikube version
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7

kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
homebrew
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
