### ISSUE TITLE
Still not able to create pod using minikube 

### ISSUE THREAD

**Issue by mehmood8** [kubernetes/kubernetes#109428]
pod1.yml

```
kind: Pod
apiVersion: v1
metadata:
  name: testpod4
spec:
  containers:
    - name: c00
      image: httpd
      ports:
       - containerPort: 80  
```

kubectl -f apply pod1.yml

error:error validating "pod1.yml" error validation :kind not set; if you choose to ignore these error, turn validation off with --validate=false

![kube vers](https://user-images.githubusercontent.com/20983588/162911190-4e9234d5-d0dd-4132-91fa-ebf1c7c77d98.PNG)
![mini staus](https://user-images.githubusercontent.com/20983588/162911198-0de310a3-2cb4-48e1-8004-0e7508a3cef9.PNG)

**Comment by neolit123** [comment]
could be malformed YAML in some way?

please try this example Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

from here:
https://kubernetes.io/docs/concepts/workloads/pods/#using-pods

/sig cli api-machinery
for triage, in case there is a strange bug lurking here.
