### ISSUE TITLE
pod with CreateContainerConfigError not restarted after stateful set update

### ISSUE THREAD

**Issue by robert-gdv** [kubernetes/kubernetes#109597]
### What happened?

1. I  applied a StatefulSet config which references in spec.template.spec.containers[0].env[i].valueFrom.secretKeyRef.name a secret, that doesn't exist. A corresponding pod is started but runs into CreateContainerConfigError.
2. I fixed the StatefulSet config by removing the corresponding spec.template.spec.containers[0].env[i] element and applied the new config.

Unexpected: The reduced env is not updated in the pod yaml. The pod remains stuck in CreateContainerConfigError state.

### What did you expect to happen?

I expect the pod to be restarted when its stateful set is modified.

### How can we reproduce it (as minimally and precisely as possible)?

1. Fix stateful set by adding a reference to your favorite image (any image should do) and create the set.
Do NOT create the secret `mysql-credentials`.
```yaml
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: USERNAME
          imagePullPolicy: Always
          image: 'yourFavoriteImage'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  serviceName: mysql
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
```

2. Observe the Pod mysql-0 with CreateContainerConfigError,
3. Update the StatefulSet by removing the reference to the missing secret (do NOT delete and create):
```yaml
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql
          imagePullPolicy: Always
          image: 'yourFavoriteImage'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  serviceName: mysql
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"w
indows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16+35fca9a", GitCommit:"aa3d30d3ccfe7b5e2c2bac7f7377725893c9a928", GitTreeState:"clean", BuildDate:"2022-01-20T03:11:31Z", GoVersion:"go1.15.14", Compiler:"gc", P
latform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```
</details>

### Cloud provider

<details>
Self-Hosted OpenShift environment
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
Ungültiger GET-Ausdruck.
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
