### ISSUE TITLE
scheduler_perf: "json: unsupported value: NaN" panic

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#109543]
### What happened?

Scheduler_perf sometimes causes "json: unsupported value: NaN" panic [here](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/util.go#L166).

### What did you expect to happen?

Not panic.

### How can we reproduce it (as minimally and precisely as possible)?

in my PC, when running scheduler_perf with the below config, there is a high probability of the panic.

```yaml
- name: PreemptionPVs
  workloadTemplate:
  - opcode: createNodes
    countParam: $initNodes
  - opcode: createPods
    countParam: $initPods
    podTemplatePath: config/pod-low-priority.yaml
  - opcode: createPods
    countParam: $measurePods
    podTemplatePath: config/pod-high-priority.yaml
    persistentVolumeTemplatePath: config/pv-aws.yaml
    persistentVolumeClaimTemplatePath: config/pvc.yaml
    collectMetrics: true
  workloads:
  - name: 500Nodes
    params:
      initNodes: 500
      initPods: 1000
      measurePods: 500
```

### Kubernetes version

latest master

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
