### ISSUE TITLE
`imagePullPolicy` issue.

### ISSUE THREAD

**Issue by siaimes** [kubernetes/kubernetes#109673]
### What happened?

```
kubectl apply -f pod-0.yaml
```

where `pod-0.yaml` is as follows:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-0
spec:
  selector:
    matchLabels:
      run: pod-0
  replicas: 1
  template:
    metadata:
      labels:
        run: pod-0
    spec:
      containers:
      - name: pod-0
        image: siaimes/pytorch1.10.0:v1.0.1
        imagePullPolicy: Always
      nodeName: csip-095
      restartPolicy: Always
```

When the pod is pulling the image.

```
kubectl apply -f pod-1.yaml
```

where `pod-1.yaml` is as follows:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-1
spec:
  selector:
    matchLabels:
      run: pod-1
  replicas: 1
  template:
    metadata:
      labels:
        run: pod-1
    spec:
      containers:
      - name: pod-1
        image: nginx:1.15
        imagePullPolicy: Always
      nodeName: csip-095
      restartPolicy: Always
```

which image `nginx:1.15` is locally available.

However, `pod-1` will not be able to start before `pod-0`.

### What did you expect to happen?

`pod-1` starts immediately, regardless of the state of `pod-0`.

### How can we reproduce it (as minimally and precisely as possible)?

Just follow the `what happened` section.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
$ uname -a
Linux csip-dev-box-test 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
