### ISSUE TITLE
Server Side Apply: metav1 `LabelSelector` members `MatchLabels` and `MatchExpressions` are not atomic

### ISSUE THREAD

**Issue by jan--f** [kubernetes/kubernetes#109668]
### What happened?

This issue is very similar to #97970 but limited to the `LabelSelector` type. A smallish reproducer can be found [in this gist](https://gist.github.com/jan--f/870b5f7a231245bba0ac870ae6206af7).

Same as in #97970, if a user and an operator both modify a `LabelSelector` such that they both either set map items of the `MatchLabels` field of modify entries of the `MatchExpressions` list we can end up with multiple owners.

In the example in the gist I have a `Prometheus` resource that has a `ServiceMonitorSelector` field of type `metav1.LabelSelector`. This field is populated with two labels and applied with SSA:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
  serviceMonitorSelector:
    matchLabels:
      resource: test
      system: foobar
```

Now a user can update that resource to add a label and change one:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
  serviceMonitorSelector:
    matchLabels:
      resource: test
      system: modified
      add: another
```

The operator detects this and reconciles the selector through SSA. The `system` label is reverted as expected but the `add` label remains:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
...
  serviceMonitorSelector:
    matchLabels:
      resource: test
      system: foobar
      add: another
```

### What did you expect to happen?

Given that entries in both `MatchLabels` and `MatchExpressions` are joined with AND I'd expect either field can only ever have one manager. Otherwise anyone who can access a resource with a `LabelSelector` field can modify it so that it changes the behavior of the selector to something an original manager (like an operator) can only address through read/modify/write instead of declaring managed fields.

### How can we reproduce it (as minimally and precisely as possible)?

See https://gist.github.com/jan--f/870b5f7a231245bba0ac870ae6206af7. If this is not minimal enough, I'm happy to try and improve it.

### Anything else we need to know?

This probably should have been part of #97989 and makes the same argument.

I'd be happy to propose a PR.

### Kubernetes version

<details>
tested with `v1.23`.
</details>

### Cloud provider

<details>
doesn't matter
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
