### ISSUE TITLE
`cobra.Command.RunE `  does not print errors if errors occur

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#109670]
### What happened?

`cobra.Command.RunE `  does not print errors in the file or console if errors occur.
e.g.:
https://github.com/kubernetes/kubernetes/blob/a83cc51a19d1b5f2b2d3fb75574b04f587ec0054/cmd/kube-scheduler/app/server.go#L85-L87

If `runCommand` return err, No error printing in console. 
Why not use `klog` to print errors?

pod.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
  annotations:
    openPalette.io/cpuSetType: plat
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - /usr/local/bin/kube-scheduler
    - --v=0
    - --log-file=/paasdata/op-log/k8s/kube-scheduler.klog
    - --tls-cert-file=/etc/kubernetes/certs/server.crt
    - --tls-private-key-file=/etc/kubernetes/certs/server.key
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.kubeconfig
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.kubeconfig
    - --tls-min-version=VersionTLS12
    - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - --logtostderr=false
    - --alsologtostderr=false
    - --stderrthreshold=4
    - --config=/etc/kubernetes/scheduler-config.yaml
    
...
```
if `/etc/kubernetes/scheduler-config.yaml`  file is configured incorrectly, e.g.: `healthzBindAddress`  only empty address or port 0 is allowed
```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.kubeconfig
enableProfiling: false
healthzBindAddress: "127.0.0.1:10251"
metricsBindAddress: ""
leaderElection:
  leaderElect: false
  leaseDuration: 30s
  renewDeadline: 20s
  resourceLock: leases
  retryPeriod: 5s
```

### What did you expect to happen?

If `runCommand` return err, errors printing in console or file(use `klog`)

### How can we reproduce it (as minimally and precisely as possible)?

`runCommand` return errors

### Kubernetes version

<details>

```console
$ kubectl version
1.23.6
```

</details>
