### ISSUE TITLE
Named target port is not working

### ISSUE THREAD

**Issue by hanlins** [kubernetes/kubernetes#109627]
### What happened?

Created a service using named `targetPort` (namely `http`), but it didn't work. Checked the endpoint for the service, the endpoint is empty but the endpointslice is not:
```
$ kubectl -n test get ep,endpointslice,deploy
NAME            ENDPOINTS   AGE
endpoints/svc   <none>      20s

NAME                                       ADDRESSTYPE   PORTS     ENDPOINTS                 AGE
endpointslice.discovery.k8s.io/svc-hqt89   IPv4          <unset>   10.244.0.73,10.244.0.72   20s

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/deploy   2/2     2            2           20s
```

### What did you expect to happen?

After I change the `targetPort` from `http` to a numeric value (namely `80`), it worked:
```
$ kubectl -n test get ep,endpointslice,deploy
NAME            ENDPOINTS                       AGE
endpoints/svc   10.244.0.74:80,10.244.0.75:80   5s

NAME                                       ADDRESSTYPE   PORTS   ENDPOINTS                 AGE
endpointslice.discovery.k8s.io/svc-tzx2r   IPv4          80      10.244.0.74,10.244.0.75   5s

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/deploy   2/2     2            2           5s
```
I expect this should be working for both `http` and `80` (since it used to work).

### How can we reproduce it (as minimally and precisely as possible)?

Here's a spec I used to reproduce the issue on latest `kind` (`1.23`):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: something
  template:
    metadata:
      labels:
        app: something
    spec:
      containers:
      - image: us.gcr.io/google-containers/nginx
        imagePullPolicy: IfNotPresent
        name: something
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: something
  type: ClusterIP
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:32:53Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
kind 1.23
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by hanlins** [comment]
This seemed to be a user error. User need to specifically specify the port's name in deployment spec, and reference that name (instead of common protocol name) in the service. Using following spec, the service is exposed correctly:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: something
  template:
    metadata:
      labels:
        app: something
    spec:
      containers:
      - image: us.gcr.io/google-containers/nginx
        imagePullPolicy: IfNotPresent
        name: something
        ports:
        - containerPort: 80
          protocol: TCP
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: something
  type: ClusterIP
```
Here's the workload:
```
$ kubectl -n test get deploy,ep,endpointslice
NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/deploy   2/2     2            2           23s

NAME            ENDPOINTS                       AGE
endpoints/svc   10.244.0.76:80,10.244.0.77:80   23s

NAME                                       ADDRESSTYPE   PORTS   ENDPOINTS                 AGE
endpointslice.discovery.k8s.io/svc-h4lxj   IPv4          80      10.244.0.76,10.244.0.77   23s
```
