### ISSUE TITLE
[RFE] scheduling profiles restricted by a list of namespaces

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#109693]
Currently, when a scheduling profile is configured, the `schedulerName` field [1] is used to map the profile to a pod. In cases where the same profile is shared between control plane pods [2] and user workload pods, this may become cumbersome when there's a demand on having different scheduling configuration for the workload pods. The obvious solution is to create another scheduling profile and have the workload pods set the `.spec.schedulerName` field. However, given the workload pods usually account for the majority of all the pods in a cluster, one needs e.g. a mutation admission webhook to update the `.spec.schedulerName` field before a pod is created (given workloads can originate from various external sources which assume the default scheduler is used). The challenge transforms rather into having the control plane pods set the `spec.schedulerName`. However, in already existing clusters changing the `.spec.schedulerName` field of all control plane pods may result in at least temporary disruptions during the transition from one scheduling profile to another. Also, the same change needs to be applied in all operators and/or deployers of the control plane pods which is not trivial since not every cluster deployment requires to have a dedicated profile for the control plane components. For the reasons mentioned above I'd like to propose a new field in the scheduling profile (e.g. `matchingNamespaces`) which will limit scope of a profile to only namespaces which are listed in the new field. E.g.

```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: default-scheduler
    # default scheduling profile for the control plane components
    matchingNamespace:
    - kube-system
    plugins: ...
  - schedulerName: default-scheduler
    # default scheduling profile for any other namespaces but the kube-system
    plugins: ...
  - schedulerName: no-scoring-scheduler
    plugins:
      preScore:
        disabled:
        - name: '*'
      score:
        disabled:
        - name: '*'
```

where if there are multiple profiles with the same `schedulerName` field, all their `matchingNamespace` have to be mutually exclusive with one exception of a profile without the `matchingNamespace` field which will be used as the last in case every other profile does not match the listed namespaces. If `matchingNamespace` field is used there always has to be a profile with the same name which does not set the field.

[1] https://kubernetes.io/docs/reference/scheduling/config/#multiple-profiles
[2] https://kubernetes.io/docs/concepts/overview/components/#control-plane-components
