### ISSUE TITLE
Kubernetes scheduler may preempt lower priority pods during deployment rollout

### ISSUE THREAD

**Issue by rtheis** [kubernetes/kubernetes#109714]
### What happened?

Kubernetes scheduler may preempt lower priority pods during deployment rollout. I suspect https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#higher-priority-pods-are-preempted-before-lower-priority-pods partially explains why.  

### What did you expect to happen?

Pods belonging to the **same** deployment should not preempt each other in a manner that breaks a highly available app rollout involving priority class changes.

### How can we reproduce it (as minimally and precisely as possible)?

Apply the following deployment on a 3 node cluster.  We are using 3 nodes here to simulate a multi zone cluster that spreads pods across zones.

```
---
apiVersion: scheduling.k8s.io/v1
description: high
kind: PriorityClass
metadata:
  name: high
value: 900000000
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
description: medium
kind: PriorityClass
metadata:
  name: medium
value: 500000000
globalDefault: false
---
apiVersion: scheduling.k8s.io/v1
description: low
kind: PriorityClass
metadata:
  name: low
value: 100000000
globalDefault: false
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: alpine
  name: alpine
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: alpine
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alpine
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["alpine"]
            topologyKey: kubernetes.io/hostname
      containers:
      - image: alpine:latest
        imagePullPolicy: IfNotPresent
        name: alpine
        command: ["sh", "-c", "sleep 100000"]
```

Patch the deployment to set a priority class.  This will cause all pods to either be `Pending` or `Terminating` at the same time.
```
kubectl patch deployment alpine -p '{"spec": {"template": {"spec": {"priorityClassName": "low"}}}}'
```

Patch the deployment to increase priority.  This will cause all pods to either be `Pending` or `Terminating` at the same time.
```
kubectl patch deployment alpine -p '{"spec": {"template": {"spec": {"priorityClassName": "medium"}}}}'
```

Patch the deployment to increase priority.  This will cause all pods to either be `Pending` or `Terminating` at the same time.
```
kubectl patch deployment alpine -p '{"spec": {"template": {"spec": {"priorityClassName": "high"}}}}'
```

Patch the deployment to lower priority.  This will yield the expected rollout.
```
kubectl patch deployment alpine -p '{"spec": {"template": {"spec": {"priorityClassName": "low"}}}}'
```

### Anything else we need to know?

This issue is similar to https://github.com/kubernetes/kubernetes/issues/108266 in that the deployment configuration impacts whether or not this problem occurs.

### Kubernetes version

Failure occurs on Kubernetes versions 1.20, 1.21, 1.22, 1.23 and 1.24.

### Cloud provider

N/A

### OS version

N/A

### Install tools

IBM Cloud Kubernetes Service

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A
