### ISSUE TITLE
kube-addon-manager seems to ignore ADDON_CHECK_INTERVAL_SEC var

### ISSUE THREAD

**Issue by blame19** [kubernetes/kubernetes#109862]
### What happened?

I'm deploying addon manager v9.1.6:
```
...
  - command:
        - /bin/bash
        - -c
        - exec /opt/kube-addons-main.sh
        env:
        - name: ADDON_CHECK_INTERVAL_SEC
          value: "180"
        - name: ADDON_PATH
          value: /var/kubernetes/addons/
        image: mcr.microsoft.com/oss/kubernetes/kube-addon-manager:v9.1.6
        imagePullPolicy: IfNotPresent
```

### What did you expect to happen?

I expected the addon-manager to run the check every 180 seconds.

Instead, according to the logs:

> k logs addons-manager-6486765fb-ctdqn -c kube-addon-manager 
INFO: == Kubernetes addon templatizer started at 2022-05-06T14:24:08+00:00 with ADDON_CHECK_INTERVAL_SEC=60 ==

The number of times the addon reconcile fails seems to confirm that it runs every minute:

>  k logs addons-manager-6486765fb-ctdqn -c kube-addon-manager | grep reconcile
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:24:17+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:25:13+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:26:18+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:27:17+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:28:20+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:29:17+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:30:17+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:31:17+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:32:18+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:33:17+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:34:18+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:35:17+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:36:17+00:00 ==
INFO: == Kubernetes addon reconcile completed at 2022-05-06T14:37:18+00:00 ==

Is there something I'm missing here?

### How can we reproduce it (as minimally and precisely as possible)?

Deploy the addon-manager with ADDON_CHECK_INTERVAL_SEC as an env var with a value =\= 60.
Check from the logs.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"e3b38d155d5377d1eaecbd73f3f62e8c35cee244", GitTreeState:"clean", BuildDate:"2022-03-30T18:27:24Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
