### ISSUE TITLE
Job status have been updated after it's marked as DeadlineExceeded

### ISSUE THREAD

**Issue by lsytj0413** [kubernetes/kubernetes#109902]
### What happened?

- Create a Job
- Wait job to exceeded it's deadline
- First, it marked as DeadlineExceeded: True and Failed: 1
- Second, it marked as DeadlineExceeded: True and Failed: 0

job:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-failed
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 100
      backoffLimit: 6
      completions: 1
      parallelism: 1
      template:
          labels:
            app: job-failed
        spec:
          containers:
          - image: xxx
            imagePullPolicy: IfNotPresent
            name: s
            resources:
              limits:
                cpu: "1"
                memory: 8Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 5
  suspend: true
```

the job's first update event from audit-log：
```
{
        "kind": "Event",
        "apiVersion": "[audit.k8s.io/v1](http://audit.k8s.io/v1)",
        "level": "RequestResponse",
        "auditID": "339948e7-8ee7-43b3-8700-d29a0f0b2c77",
        "stage": "ResponseComplete",
        "requestURI": "/apis/batch/v1/namespaces/default/jobs/job-failed-1652085120/status",
        "verb": "update",
        "userAgent": "kube-controller-manager/v1.20.12 (linux/amd64) kubernetes/4bf2e32/system:serviceaccount:kube-system:job-controller",
        "objectRef": {
                "resource": "jobs",
                "namespace": "default",
                "name": "job-failed-1652085120",
                "uid": "236fda56-5a50-4c01-a190-724e9c94ea3b",
                "apiGroup": "batch",
                "apiVersion": "v1",
                "resourceVersion": "14089826",
                "subresource": "status"
        },
        "responseStatus": {
                "metadata": {},
                "code": 200
        },
        "requestObject": {
                "kind": "Job",
                "apiVersion": "batch/v1",
                "metadata": {
                        "name": "job-failed-1652085120",
                        "namespace": "default",
                        "resourceVersion": "14089826",
                },
                "status": {
                        "conditions": [{
                                "type": "Failed",
                                "status": "True",
                                "lastProbeTime": "2022-05-09T08:33:07Z",
                                "lastTransitionTime": "2022-05-09T08:33:07Z",
                                "reason": "DeadlineExceeded",
                                "message": "Job was active longer than specified deadline"
                        }],
                        "startTime": "2022-05-09T08:32:07Z",
                        "failed": 1
                }
        },
        "responseObject": {
                "kind": "Job",
                "apiVersion": "batch/v1",
                "metadata": {
                        "name": "job-failed-1652085120",
                        "namespace": "default",
                        "resourceVersion": "14089996",
                },
                "status": {
                        "conditions": [{
                                "type": "Failed",
                                "status": "True",
                                "lastProbeTime": "2022-05-09T08:33:07Z",
                                "lastTransitionTime": "2022-05-09T08:33:07Z",
                                "reason": "DeadlineExceeded",
                                "message": "Job was active longer than specified deadline"
                        }],
                        "startTime": "2022-05-09T08:32:07Z",
                        "failed": 1
                }
        },
        "requestReceivedTimestamp": "2022-05-09T08:33:07.219049Z",
        "stageTimestamp": "2022-05-09T08:33:07.224789Z"
}
```

the job's second update event from audit-log：
```
{
        "kind": "Event",
        "apiVersion": "[audit.k8s.io/v1](http://audit.k8s.io/v1)",
        "level": "RequestResponse",
        "auditID": "398a8e74-778d-4bcf-b9e9-16c550402801",
        "stage": "ResponseComplete",
        "requestURI": "/apis/batch/v1/namespaces/default/jobs/job-failed-1652085120/status",
        "verb": "update",
        "user": {
                "username": "system:serviceaccount:kube-system:job-controller",
                "uid": "a62ba950-0220-4599-9ece-042ecdde4962",
                "groups": ["system:serviceaccounts", "system:serviceaccounts:kube-system", "system:authenticated"]
        },
        "sourceIPs": ["[10.0.16.189](http://10.0.16.189/)"],
        "userAgent": "kube-controller-manager/v1.20.12 (linux/amd64) kubernetes/4bf2e32/system:serviceaccount:kube-system:job-controller",
        "objectRef": {
                "resource": "jobs",
                "namespace": "default",
                "name": "job-failed-1652085120",
                "uid": "236fda56-5a50-4c01-a190-724e9c94ea3b",
                "apiGroup": "batch",
                "apiVersion": "v1",
                "resourceVersion": "14089996",
                "subresource": "status"
        },
        "responseStatus": {
                "metadata": {},
                "code": 200
        },
        "requestObject": {
                "kind": "Job",
                "apiVersion": "batch/v1",
                "metadata": {
                        "name": "job-failed-1652085120",
                        "namespace": "default",
                        "resourceVersion": "14089996",
                },
                "status": {
                        "conditions": [{
                                "type": "Failed",
                                "status": "True",
                                "lastProbeTime": "2022-05-09T08:33:07Z",
                                "lastTransitionTime": "2022-05-09T08:33:07Z",
                                "reason": "DeadlineExceeded",
                                "message": "Job was active longer than specified deadline"
                        }],
                        "startTime": "2022-05-09T08:32:07Z"
                }
        },
        "responseObject": {
                "kind": "Job",
                "apiVersion": "batch/v1",
                "metadata": {
                        "name": "job-failed-1652085120",
                        "namespace": "default",
                        "resourceVersion": "14089999",
                },
                "status": {
                        "conditions": [{
                                "type": "Failed",
                                "status": "True",
                                "lastProbeTime": "2022-05-09T08:33:07Z",
                                "lastTransitionTime": "2022-05-09T08:33:07Z",
                                "reason": "DeadlineExceeded",
                                "message": "Job was active longer than specified deadline"
                        }],
                        "startTime": "2022-05-09T08:32:07Z"
                }
        },
        "requestReceivedTimestamp": "2022-05-09T08:33:07.230416Z",
        "stageTimestamp": "2022-05-09T08:33:07.234652Z"
}
```

### What did you expect to happen?

- job been marked as DeadlineExceeded: True and Failed: 1

### How can we reproduce it (as minimally and precisely as possible)?

- When job controller delete pod, force delete it
- We use virtual-kubelet framework, it will delete pod as soon as possible

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.12", GitCommit:"4bf2e32bb2b9fdeea19ff7cdc1fb51fb295ec407", GitTreeState:"clean", BuildDate:"2021-10-27T17:07:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
