### ISSUE TITLE
ValidatingWebhookConfiguration stales it's deployment when created together

### ISSUE THREAD

**Issue by TzlilSwimmer123** [kubernetes/kubernetes#109964]
### What happened?

I have a yaml that contains 3 k8s configurations:
1. Deployment
2. Service
3. ValidatingWebhookConfiguration

If I try to apply them together I get a replica failure `failed calling admission webhook: connection refused`

I noticed that the combination of `resources:   ["*/*"]` alongside `operations:  ["CREATE", "UPDATE"]` and `failurePolicy: Fail` (default value)` makes the problem.

Working combinations:
- `resources:   ["*"]` alongside `operations:  ["CREATE"]` and `failurePolicy: Fail`
- `resources:   ["*/*"]` alongside `operations:  ["CREATE", "UPDATE"]` and `failurePolicy: Ignore` 
- `resources:   ["*/*"]` alongside `operations:  ["UPDATE"]` and `failurePolicy: Ignore` 

The problem is that we need to be able to intercept `resources:   ["*/*"] alongside operations:  ["CREATE", "UPDATE"]` while not ignoring unexpected errors in webhook `failurePolicy: Ignore`.

### What did you expect to happen?

I expect that ValidatingWebhookConfiguration creation along side the Deployment and Service will not affect the deployment creation while using the webhook capabilities of intercepting certain resources and operations!

### How can we reproduce it (as minimally and precisely as possible)?

Here are the configurations: (we use a local docker image, reproduces also on EKS with ECR image)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: default
  labels:
    app: webhook-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: server
        image: webhook-server
        imagePullPolicy: Never
        env:
          - name: FAIL
            value: "true"
        ports:
        - containerPort: 8443
          name: webhook-api
        volumeMounts:
        - name: webhook-tls-certs
          mountPath: /run/secrets/tls
          readOnly: true
      volumes:
      - name: webhook-tls-certs
        secret:
          secretName: webhook-server-tls
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: default
spec:
  selector:
    app: webhook-server
  ports:
    - port: 443
      targetPort: webhook-api
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    namespaceSelector:
      matchExpressions:
        - key: validate
          operator: NotIn
          values: [ "skip" ]
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["*"]
    clientConfig:
      service:
        namespace: "default"
        name: "webhook-server"
        path: "/validate"
      caBundle: ${CA_PEM_B64}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
#    failurePolicy: Ignore
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/arm64"}
```

### Cloud provider

<details>
EKS, also reproduced on local minikube (off course, not a cloud)
</details>

### OS version

<details>

```
macOS Monterey
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Docker 0.19.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
