### ISSUE TITLE
new invalid bearer token, square/go-jose: error in cryptographic primitive

### ISSUE THREAD

**Issue by 5279314** [kubernetes/kubernetes#110035]
### What happened?

I doubt whether the API configuration is wrong, because the created serviceaccount does not seem to be mounted in the pod container
```
[root@testwithsa /run/secrets/kubernetes.io/serviceaccount]$ curl --cacert ./ca.crt -H "Authorization: Bearer $(cat ./token)" https://10.1.1.100:6443/namespace/$(cat ./namespace)/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
apiserver log
```
E0505 15:59:49.432822    7867 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
```

### What did you expect to happen?

All pods can operate normally. Please help analyze whether there are errors

### How can we reproduce it (as minimally and precisely as possible)?

try to apply the yaml file I supply blow.
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: Pod
metadata:
  name: testwithsa
  namespace: default
spec:
  containers:
  - name: amdinbox
    image: ikubernetes/admin-toolbox:v1.0
    imagePullPolicy: Always
  serviceAccountName: test
```
kube-apserver args
```
[root@k8s-master1 ~]# cat /opt/kubernetes/cfg/kube-apiserver.conf 
KUBE_APISERVER_OPTS="--logtostderr=false \
--v=2 \
--log-dir=/opt/kubernetes/logs \
--etcd-servers=https://10.1.1.100:2379,https://10.1.1.130:2379,https://10.1.1.120:2379 \
--bind-address=10.1.1.100 \
--secure-port=6443 \
--advertise-address=10.1.1.100 \
--allow-privileged=true \
--service-cluster-ip-range=192.168.0.0/16 \
--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,NodeRestriction \
--authorization-mode=RBAC,Node \
--enable-bootstrap-token-auth=true \
--token-auth-file=/opt/kubernetes/cfg/token.csv \
--service-node-port-range=30000-32767 \
--kubelet-client-certificate=/opt/kubernetes/ssl/server.pem \
--kubelet-client-key=/opt/kubernetes/ssl/server-key.pem \
--client-ca-file=/opt/kubernetes/ssl/ca.pem \
--service-account-key-file=/opt/kubernetes/ssl/ca-key.pem \
--etcd-cafile=/opt/kubernetes/ssl/etcd/ca.pem \
--etcd-certfile=/opt/kubernetes/ssl/etcd/server.pem \
--etcd-keyfile=/opt/kubernetes/ssl/etcd/server-key.pem \
--service-account-issuer=api \
--service-account-signing-key-file=/opt/kubernetes/ssl/server-key.pem \
--tls-cert-file=/opt/kubernetes/ssl/server.pem  \
--tls-private-key-file=/opt/kubernetes/ssl/server-key.pem \
--proxy-client-cert-file=/opt/kubernetes/ssl/server.pem \
--proxy-client-key-file=/opt/kubernetes/ssl/server-key.pem \
--requestheader-allowed-names=kubernetes \
--requestheader-client-ca-file=/opt/kubernetes/ssl/ca.pem \
--requestheader-extra-headers-prefix=X-Remote-Extra- \
--requestheader-group-headers=X-Remote-Group \
--requestheader-username-headers=X-Remote-User \
--enable-aggregator-routing=true \
--audit-log-maxage=30 \
--audit-log-maxbackup=3 \
--audit-log-maxsize=100 \
--audit-log-path=/opt/kubernetes/logs/k8s-audit.log"
```
kube-controller-manager args
```
[root@k8s-master1 ~]# cat /opt/kubernetes/cfg/kube-controller-manager.conf 
KUBE_CONTROLLER_MANAGER_OPTS="--logtostderr=false \
--v=2 \
--log-dir=/opt/kubernetes/logs \
--leader-elect=true \
--kubeconfig=/opt/kubernetes/cfg/kube-controller-manager.kubeconfig \
--cluster-cidr=172.7.0.0/16 \
--service-cluster-ip-range=192.168.0.0/16 \
--cluster-signing-cert-file=/opt/kubernetes/ssl/ca.pem \
--cluster-signing-key-file=/opt/kubernetes/ssl/ca-key.pem  \
--root-ca-file=/opt/kubernetes/ssl/ca.pem \
--service-account-private-key-file=/opt/kubernetes/ssl/ca-key.pem \
--cluster-signing-duration=87600h0m0s"
```
kube-scheduler.conf args
```
KUBE_SCHEDULER_OPTS="--logtostderr=false \
--v=2 \
--log-dir=/opt/kubernetes/logs \
--leader-elect \
--kubeconfig=/opt/kubernetes/cfg/kube-scheduler.kubeconfig \
--bind-address=127.0.0.1"
```

### Anything else we need to know?

The serviceaccount attached to the pod container is different from that created. Is it correct？？
kubectl get pod testwithsa -o yaml
```
   volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: **kube-api-access-42vxd**
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-node1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: test
  serviceAccountName: test
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-42vxd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```
serviceaccount 
```
[root@k8s-master1 .kube]# kubectl describe serviceaccount 
Name:                test
Namespace:           default
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   test-token-hrjdb
Tokens:              test-token-hrjdb
Events:              <none>
```
test-token-hrjdb 
```
[root@k8s-master1 .kube]# kubectl describe secrets test-token-hrjdb 
Name:         test-token-hrjdb
Namespace:    default
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: test
              kubernetes.io/service-account.uid: f116f539-9a99-4c14-b9dd-239de4ca4fb4

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1310 bytes
namespace:  7 bytes
token:      eyJhbGciOiJSUzI1NiIsImtpZCI6IlNTX2YyUDliMGcxZmRxYkNQRzJYY1ZveGFJNjdQRHE2ZEQ0WTA1MGxha2sifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRlc3QtdG9rZW4taHJqZGIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidGVzdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImYxMTZmNTM5LTlhOTktNGMxNC1iOWRkLTIzOWRlNGNhNGZiNCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnRlc3QifQ.i_VjzIH15llVx1EyEWfMruaSeqYo8OapqHlDh0i6ylN2HvDQrsXFN7EW5SS4HtwtmIr457ZTHW7ViSH9lhAraUkKAFN8-Sg7mkr_SH3FUB6uQqA3PhMwb6psW10rT5aMuKWpN4ruqhkttPEKtlvVsAygzN8mhAUXgaC_sST0ZH_n8HBIPFpjorhCBR4kg4K6HTrrCJ1bvD077y_7Dod4JMCS-lMljdrQspYWy6FzEakceC-SKWbuhnrjiboQ7wHzI8EtSDEkYtJRr4WCpbnUPtL8Icqs2-buH3EMMLYtTqCppvS2N34DuYq8o_OuLcLzW2N9cSzsV84BEQMPIbixiA
```
pod token
```
[root@testwithsa /]# cat run/secrets/kubernetes.io/serviceaccount/token 
eyJhbGciOiJSUzI1NiIsImtpZCI6IlVWRVNhLUdrTVdneEdWbUtLYTZzSkVWa21nMGM1aDZscVBpQ1hVRHpkZDgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNjgzOTY3MDA4LCJpYXQiOjE2NTI0MzEwMDgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0IiwicG9kIjp7Im5hbWUiOiJ0ZXN0d2l0aHNhIiwidWlkIjoiMWY0OGU1ZmQtOWJhNi00NWMxLWE2NGUtNTY2NGY5ZGZjNmMyIn0sInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJ0ZXN0IiwidWlkIjoiZjExNmY1MzktOWE5OS00YzE0LWI5ZGQtMjM5ZGU0Y2E0ZmI0In0sIndhcm5hZnRlciI6MTY1MjQzNDYxNX0sIm5iZiI6MTY1MjQzMTAwOCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6dGVzdCJ9.R4NDO8IFldJF9slua8fX66at_TFSGeZnEW2zuZhh0Kwp5MMIE0PwRibx-q2i_sJCyqLC5gk7M3CS7Aa9lY1I1t_0nt0tOIGAfIUv_b7AzTUx-FcHsgpv9932QPdA1Lgx8tGwSjt9HTGLICOUKnbkd2Cgg5dEkylYva3EbGDe29FrwCzNFVvISaLLa9Lnxr-4Gb2kr8SjuOelOsndMwbq5ZahVQAAOGb8xXF_ume5vtQHXsLbmv5Mtd-7iMLAsn2hrEuQB1xVa1Frz0_sq3DBdkopfTenbezqhLeVVgNoLziC8vyNgwuApS0Tun2lNSGLxYAZs0HvpX1u0hxSDBUznA
```
kube-api log
```
E0505 15:54:18.319100    7867 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
E0505 15:55:27.574617    7867 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
I0505 15:56:24.576807    7867 controller.go:611] quota admission added evaluator for: rolebindings.rbac.authorization.k8s.io
E0505 15:56:30.742378    7867 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
E0505 15:59:49.432822    7867 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
W0505 16:02:35.263506    7867 watcher.go:229] watch chan error: etcdserver: mvcc: required revision has been compacted
W0505 16:10:01.585297    7867 watcher.go:229] watch chan error: etcdserver: mvcc: required revision has been compacted
W0505 16:20:20.157816    7867 watcher.go:229] watch chan error: etcdserver: mvcc: required revision has been compacted
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
# paste output here
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
CentOS Linux release 7.9.2009 (Core)
# paste output here
$ uname -a
Linux k8s-master1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
