### ISSUE TITLE
AWS EBS Attaches but Pod Remains at Pending

### ISSUE THREAD

**Issue by delianides** [kubernetes/kubernetes#11011]
Running the default cluster setup on AWS and using CoreOS. Creating a mongo pod with no volume is successful. But creating a pod with an attached EBS volume is not. The volume does successfully attach to the correct node but the pod remains at the pending state. 

```
Name:                           mongo
Namespace:                      default
Image(s):                       mongo:latest
Node:                           ip-172-20-0-194.ec2.internal/172.20.0.194
Labels:                         name=mongo,role=mongo
Status:                         Pending
Reason:
Message:
IP:
Replication Controllers:        <none>
Containers:
  mongo:
    Image:      mongo:latest
    Limits:
      cpu:              100m
    State:              Waiting
      Reason:           Image: mongo:latest is not ready on the node
    Ready:              False
    Restart Count:      0
Conditions:
  Type          Status
  Ready         False
Events:
  FirstSeen                             LastSeen                        Count   From                                    SubobjectPath   Reason          Message
  Thu, 09 Jul 2015 15:05:08 -0400       Thu, 09 Jul 2015 15:05:08 -0400 1       {scheduler }                                            scheduled       Successfully assigned mongo to ip-172-20-0-194.ec2.internal
  Thu, 09 Jul 2015 15:05:14 -0400       Thu, 09 Jul 2015 15:13:28 -0400 51      {kubelet ip-172-20-0-194.ec2.internal}                  failedMount     Unable to mount volumes for pod "mongo_default": fork/exec /usr/share/google/safe_format_and_mount: no such file or directory
  Thu, 09 Jul 2015 15:05:14 -0400       Thu, 09 Jul 2015 15:13:28 -0400 51      {kubelet ip-172-20-0-194.ec2.internal}                  failedSync      Error syncing pod, skipping: fork/exec /usr/share/google/safe_format_and_mount: no such file or directory
```

The template file: 

```
kind: Pod
apiVersion: v1
metadata:
  name: mongo
  labels:
    name: mongo
    role: mongo
spec:
  containers:
  - name: mongo
    image: mongo:latest
    ports:
    - name: mongo
      containerPort: 27017
      protocol: TCP
    resources: {}
    volumeMounts:
    - mountPath: /data/db
      name: mongo-disk
  volumes:
  - name: mongo-disk
    awsElasticBlockStore:
      volumeID: vol-xxxxxxx # PR#10181
      fsType: ext4
```

Followed new `VolumeID` name per #10181. There are no helpful error messages on the kubelet or controller-manager. I moved up to use larger ec2 instances rather than the default t2.micro and didn't have any change.
