### ISSUE TITLE
audit policy wrong logic does not record events.

### ISSUE THREAD

**Issue by dioguerra** [kubernetes/kubernetes#110116]
### What happened?

Configuration on the k8s audit-policy.yaml is failing to currectly record the events.
I'm trying to create a audit-policy.yaml fail to save some of the events and i noticed some issues.

1. I cannot dismiss all the logs that watch, get or list an object:
```yaml
- level: None
  resources:
  - verbs: ["watch", "get", "list"]
```
Will produce no effects and the logs will be printed in the log file.

2. I'm trying to drop all "watch", "get", "list" events from resources "leases" but instead all the events are dropped (including update)
```yaml
- level: None
  resources:
  - group: coordination.k8s.io
    resources:
    - "leases"
    verbs: ["watch", "get", "list"]
```

### What did you expect to happen?

1. I expect all the audit logs related to events that "list", "watch" or "get" to be removed from the audit logs

2. I expect to see all "resource leases" events that do not "list", "watch" or "get"

### How can we reproduce it (as minimally and precisely as possible)?

Here i drop my full audit-policy.yaml file
```yaml
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
# do not log requests to the following
- level: None
  nonResourceURLs:
  - "/healthz*"
  - "/logs"
  - "/metrics"
  - "/swagger*"
  - "/version"

# limit level to Metadata so token is not included in the spec/status
- level: Metadata
  omitStages:
  - RequestReceived
  resources:
  - group: authentication.k8s.io
    resources:
    - tokenreviews

# extended audit of auth delegation
- level: RequestResponse
  omitStages:
  - RequestReceived
  resources:
  - group: authorization.k8s.io
    resources:
    - subjectaccessreviews

# log changes to pods at RequestResponse level
- level: RequestResponse
  omitStages:
  - RequestReceived
  resources:
  - group: "" # core API group; add third-party API services and your API services if needed
    resources: ["pods", "deployments", "statefulsets", "daemonsets"]
    verbs: ["create", "patch", "update", "delete"]

- level: None
  resources:
  - group: coordination.k8s.io
    resources:
    - "leases"
    verbs: ["watch", "get", "list"]

# log everything else at Metadata level
- level: Metadata
  omitStages:
  - RequestReceived

```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Openstack
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="35.20220227.2.1 (CoreOS)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora CoreOS 35.20220227.2.1"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='35.20220227.2.1'
DEFAULT_HOSTNAME=localhost

$ uname -a
Linux dtomasgu-kubernetes-1-22-3-4-f4cj7pqiomtv-master-0 5.16.13-200.fc35.x86_64 #1 SMP PREEMPT Tue Mar 8 22:50:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.4.13
RuntimeApiVersion:  v1alpha2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tallclair** [comment]
`verbs` is a field on the policy rule, not the resources. Unfortunately our yaml parser just silently drops unknown fields, so your rule

```
- level: None
  resources:
  - group: coordination.k8s.io
    resources:
    - "leases"
    verbs: ["watch", "get", "list"]
```

is just seen as
```
- level: None
  resources:
  - group: coordination.k8s.io
    resources:
    - "leases"
```

Which will match all verbs.

---

In the case of 
```
- level: None
  resources:
  - verbs: ["watch", "get", "list"]
```

This is getting interpreted as
```
- level: None
  resources:
  - {}
```

Or equivalently:
```
- level: None
  resources:
  - group: ""
```

Which is the core API group. So, this should be dropping all events for the core types, but not events in other named api groups.

---

I filed https://github.com/kubernetes/kubernetes/issues/113266 to handle unknown fields better.
