### ISSUE TITLE
Service account not working in none default namespace

### ISSUE THREAD

**Issue by vincent5753** [kubernetes/kubernetes#110217]
### What happened?

I had tested on version 1.23.5 and 1.23.6, when I had ClusterRoleBing to ServiceAccount in Default namespace, everything went fine.
But if I want to put my service into another namespace, the service inside the pod will get "resolve failed" message like this
```
curl: (6) Could not resolve host: kubernetes
```

### What did you expect to happen?

Works just like running in default namespace.

### How can we reproduce it (as minimally and precisely as possible)?

Works fine when running in default namespace.

crb.yaml 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vp-default
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  #name: cluster-admin-vp
  name: default
  namespace: vp
```
po.yaml 
```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: vp
  labels:
    app: test-bench
spec:
  serviceAccountName: default
  serviceAccount: default
  automountServiceAccountToken: true
  containers:
  - image: vincent5753/ubuntu20.04
    imagePullPolicy: Always
    name: test-bench
    args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 99999; done']
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
on-premises
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux vp-VirtualBox 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd.io_1.5.10-1_amd64
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Flannel CNI
</details>
