### ISSUE TITLE
statefulset pod with zero terminationGracePeriodSeconds miss termination when shutdown node

### ISSUE THREAD

**Issue by hicaistar** [kubernetes/kubernetes#110401]
### What happened?

1. create statefulset with one pod, and set the terminationGracePeriodSeconds to 0, pod is running on node-1
2. shutdown node-1, after 5 min, new pod will be created and scheduled on node-2
3. shutdown node-2, we get the message of kube-controller-manager "Trying to add already existing work for &{NamespacedName:default/test-0}. Skipping."
4. then the pod will running on node-2 forever, meanwhile the node-2 is NotReady

### What did you expect to happen?

pod of statefulset should be deleted by TaintManager correctly

### How can we reproduce it (as minimally and precisely as possible)?

1. create statefulset with one pod, and set the terminationGracePeriodSeconds to 0, pod is running on node-1
2. shutdown node-1, after 5 min, new pod will be created and scheduled on node-2
3. shutdown node-2, it will happen

### Anything else we need to know?

````yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test
  serviceName: headless-svc-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: test
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
  updateStrategy:
    type: RollingUpdate
```

### Kubernetes version

<details>

```console
$ kubectl version
Kubernetes v1.20.15
```

</details>


### Cloud provider

<details>

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
