### ISSUE TITLE
job objects are not getting clean-up when Job is created using kubectl create job

### ISSUE THREAD

**Issue by zmalik** [kubernetes/kubernetes#110430]
### What happened?

A cronjob with correct values in `spec.failedJobsHistoryLimit` and `spec.successfulJobsHistoryLimit` is cleaning up the jobs objects once those are completed or failed, if those are scheduled objects. 

When the job is created using 
```
kubectl create job --from=cronjob/cronjob-name test-run-1
```
those manual runs aren't cleaned up. Even if those are owned by the cronjob.

When looking into the ownerReferences of the job, we have the next ownerReferences for the scheduled job:
```
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: cronjob-name
    uid: 5617f463-f5ed-4171-bf3a-02c6ae1fe1eb
```
for manually triggered job we have:
```
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    kind: CronJob
    name: cronjob-name
    uid: 5617f463-f5ed-4171-bf3a-02c6ae1fe1eb
```

this matches with kubectl job creation code: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/create/create_job.go#L275 

and in cronjob controller we filter by the condition
```
if controllerRef := metav1.GetControllerOf(job); controllerRef != nil
```
which do return nil, if the `controller` field in ownerReference isn't true, filtering out all the manually created job even if those are owned by the cronjob.
 https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cronjob/cronjob_controllerv2.go#L262 
 
Once these jobs aren't passed to `cleanupFinishedJobs` they will stay forever till manual intervention. 
 

### What did you expect to happen?

all job objects owned by a cronjob to be cleaned up. Respecting `spec.failedJobsHistoryLimit` and `spec.successfulJobsHistoryLimit` 

### How can we reproduce it (as minimally and precisely as possible)?

create multiple jobs manually using 
```
kubectl create job --from=cronjob/cronjob-name test-run-1
```

and observe once they finish those are never cleaned up.

### Kubernetes version

<details>
tested in 1.21.x and 1.22.x
</details>

### Cloud provider

<details>
tested on both GKE and AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
