### ISSUE TITLE
hostPort  failed in pod

### ISSUE THREAD

**Issue by ma-meng** [kubernetes/kubernetes#110445]
### What happened?

1.When I set hostport and hostnetwork at the same time, the hostport fails. 

2.---vim test-hostport.yaml
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-hostport
  name: test-hostport
spec:
  hostNetwork: true
  containers:
  - image: nginx
    name: test-hostport
    resources: {}
    ports:
    - hostPort: 9999
      containerPort: 9999
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```

3.kubecrl apply -f test-hostport.yaml

4.test
1)
[root@master ~]# curl localhost:9999
curl: (7) Failed connect to localhost:9999; Connection refused

2)
[root@master ~]# curl localhost:80
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

### What did you expect to happen?

1) Because the default port of the image container itself is 80, when I set the hostport and containerport to 999, accessing 9999 is unsuccessful
[root@master ~]# curl localhost:9999
curl: (7) Failed connect to localhost:9999; Connection refused

2)Because  I set the hostport and containerport to 999, accessing 80 is unsuccessful
[root@master ~]# curl localhost:80
curl: (7) Failed connect to localhost:80; Connection refused

### How can we reproduce it (as minimally and precisely as possible)?

vim test-hostport.yaml

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-hostport
  name: test-hostport
spec:
  hostNetwork: true
  containers:
  - image: nginx
    name: test-hostport
    resources: {}
    ports:
    - hostPort: 9999
      containerPort: 9999
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```

```
kubectl apply -f  test-hostport.yaml
```

```
curl localhost:9999
curl localhost:80
```

### Kubernetes version

<details>

```console
kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:57:37Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/kind support

You should config in `/etc/nginx/` to make nginx serving at port 9999. 
Pod's hostPort is only a declaration about that.

This is not a kubernetes bug.
/remove-kind bug

**Comment by ma-meng** [comment]
I have set hostPort: 9999. when I 'curl localhost:80' , why is it successful

**Comment by pacoxu** [comment]
> I have set hostPort: 9999. when I 'curl localhost:80' , why it is successful

The reason is that you use `hostNetwork:true` which means the pod is sharing the node's network.
```
hostNetwork: true
```

- hostPort is a declaration that this pod will use it. However, the pod may not use it.
- hostPort is not a limitation. A pod can use a port without this declaration.

**Comment by muyangren2** [comment]
The containerPort you set must be the same as the container port

**Comment by pacoxu** [comment]
Here is a simple demo to show what happened.

- Demo1:  test-hostnetwork-with-hostport. This pod is using hostNetwork.(in this case the hostPort must be same to containerPort as it is hostNetworking.)
- Demo2: test-hostport-only: you can set different ports. You can access both `<PodIP>:<contianerPort>` and `<PodLocatedNodeIP>:hostPort`.

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-hostnetwork-with-hostport
  name: test-hostnetwork-with-hostport
spec:
  hostNetwork: true
  containers:
  - image: nginx
    name: test-hostnetwork-with-hostport
    resources: {}
    ports:
    - hostPort: 80
      containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-hostport-only
  name: test-hostport-only
spec:
  containers:
  - image: nginx
    name: test-hostport-only
    resources: {}
    ports:
    - hostPort: 9999
      containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```
After creation, you can wait and curl on the pod/node IP. I have only one node in this cluster. The node IP is `10.6.177.40`.
`192.168.230.254` is the pod IP of test-hostport-only. And test-hostport-only  pod is scheduled to the node `10.6.177.40`. 
```
[root@paco ~]# kubectl create -f test-ho.yaml
pod/test-hostnetwork-with-hostport created
pod/test-hostport-only created
[root@paco ~]#
[root@paco ~]# kubectl get pod -o wide
NAME                             READY   STATUS              RESTARTS       AGE   IP                NODE       NOMINATED NODE   READINESS GATES
test-hostnetwork-with-hostport   1/1     Running             0              4s    10.6.177.40       daocloud   <none>           <none>
test-hostport-only               1/1     Running            0              13s   192.168.230.254   daocloud   <none>           <none>

```
[root@paco ~]# curl 10.6.177.40
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
[root@paco ~]# curl 192.168.230.254
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
[root@paco ~]#
[root@paco ~]# curl 10.6.177.40:9999
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

If you want to access 9999 on hostport, you can use my second pod yaml. 
Or you should just build a new image with nginx configured to listen on 9999. https://stackoverflow.com/questions/47364019/how-to-change-the-port-of-nginx-when-using-with-docker/57747905#57747905 is a demo.(I have already put it there, I don't know why you do not try that).
