### ISSUE TITLE
Add File templating for Kubernetes Object

### ISSUE THREAD

**Issue by ErnestFistozz** [kubernetes/kubernetes#110528]
### What would you like to be added?

# Current Setup
The current setup when creating a `ReplicaSet`, `Deployment` , `CronJob` or any k8s object requires the template to be described in the same file. For example
```yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: <rs-name>
  labels:
    <key>: <value>
spec:
  template:  #this is the template I am referring to
    metadata:
     name:
     labels:
       <key>: <value>
   spec:
     containers:
     - image: <image-name>
       name: <container-name>
```

#Potential Configuration
This is obviously does serve the purpose, however, for a complex pod template, this becomes tedious and is no longer readable. would be great to have functionality of calling a template file much like how `azure devops pipeline`  or  `terraform modules` works. consider the two files `pod.yml` and `replica-set.yml`  in the same directory

```yaml
# pod definition file -> to be used by replicas-set as a template
apiVersion: v1
kind: Pod
metadata:
  name: <pod-name>
  labels:
    <key>: <value>
spec:
  containers:
  - name: <container-name>
    image: <image-name>
```
Then this  file can be referenced in the replicaset as follows:

```yaml
# replica-set file calling the `pod.yml` file
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: <rs-name>
  labels:
    <key>: <value>
spec:
  template: 
    from-file: ./pod.yml  # this references the pod definition file file above (NB: the from file is merely just an example)
  replicas: <no-of-replicas>
  selector:
    matchLabels:
      <key>: <value>
```
NB: this replicaset calls the `pod.yml` file in the same file but this should work even with templates stored in a VCS.
This is much readable and much friendlier to work with. 

### Why is this needed?

Template would give rise to easily manageable k8s object definition files and the following among others:

- [ ] Reusability
- [ ] Readability
- [ ] Modularised k8s objects

**Comment by pacoxu** [comment]
There is already [PodTemplate](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#podtemplate-v1-core) definition. 
```
apiVersion: v1
kind: PodTemplate
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
template:
  spec:
    containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
```
Then we can reference it in the Deploy/RS/StatefulSet/Job.
```
  template: 
     from-template: nginx
```

However, I think this should only happen on the client-side, we cannot add such reference in the object.
/sig cli api-machinery
