### ISSUE TITLE
Secret import invalid environment variables into the Linux OS

### ISSUE THREAD

**Issue by DesireWithin** [kubernetes/kubernetes#110620]
### What happened?

We have a `secret(Opaque)` which created by rancher，
the key name is a invaild environment: like `"keyfield1_keyfield2-keyfield3"`

and then a deployment refer this secret by `deployment.spec.template.spec.containers.envFrom.secretRef`
as we konw Linux environment can not contain `"-"`

When I run `sh` in the pod, `set` command can't  output this invaild environment, but `env` command can.
```sh
$> set | grep keyfield1_keyfield2-keyfield3
$> env | grep keyfield1_keyfield2-keyfield3
keyfield1_keyfield2-keyfield3=value
$> echo ${keyfield1_keyfield2-keyfield3}
keyfield3
```

### What did you expect to happen?

According document:
https://kubernetes.io/docs/concepts/configuration/secret/#restriction-env-from-invalid
I wish no invaild environment import and there are `Warning events`  

### How can we reproduce it (as minimally and precisely as possible)?

Create  and apply a test secret and a busybox pod:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: testsecret
type: Opaque
data:
  1badKey: "MWJhZEtleS12YWx1ZQo="
  good_key: "Z29vZF9rZXktdmFsdWUK"
  bad-key2: "YmFkLWtleTItdmFsdWUK"
```

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: busybox:latest
      envFrom:
        - secretRef:
            name: testsecret
      command:
        - sleep
        - 1h
```
Excute shell in the busybox:
``` sh
$> set | grep bad-key2
$> env | grep good
good_key=good_key-value
$> env | grep bad
bad-key2=bad-key2-value
$> echo ${bad-key2}
key2
```
Run `kubectl get events`
```
...
33m         Warning   InvalidEnvironmentVariableNames   pod/test-pod   Keys [1badKey] from the EnvFrom secret default/testsecret were skipped since they are considered invalid environment variable names.
...
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T12:01:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

virtual server base on KVM

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux xiaowen-k8s-master 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
