### ISSUE TITLE
Modifying podAntiAffinity has no effect

### ISSUE THREAD

**Issue by DieterDP-ng** [kubernetes/kubernetes#110718]
### What happened?

- I create a statefulset with a `requiredDuringSchedulingIgnoredDuringExecution` podAntiAffinity and deploy it on a cluster where not enough nodes are available, resulting in some pods being stuck in a `Pending` state.
- I then update the statefulset to use `preferredDuringSchedulingIgnoredDuringExecution` instead.
- The pods are still stuck in a `Pending` state. Deleting the pod has no effect. Deleting the statefulset and re-applying fixes the issue.

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sfs-name
  labels:
    app.kubernetes.io/component: my-component
spec:
  serviceName: service-name
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: my-component
  template:
    metadata:
      labels:
        app.kubernetes.io/component: my-component
    spec:
      containers:
      - name: container-name
        image: busybox:1.28
        command: ["/bin/sh", "-ec", "sleep 1000"]
      affinity:
        podAntiAffinity:

          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: my-component
          
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - podAffinityTerm:
#              labelSelector:
#                matchLabels:
#                  app.kubernetes.io/component: my-component
#              topologyKey: kubernetes.io/hostname
#            weight: 100
```

### What did you expect to happen?

I expected the pods to be deployed as soon as I updated the statefulset to use `preferredDuringSchedulingIgnoredDuringExecution` podAntiAffinity.

### How can we reproduce it (as minimally and precisely as possible)?

- Use a 1 node cluster (eg: minikube)
- Copy above yaml into `test.yaml`
- `kubectl apply -f test.yaml`
- Observe 1 pod is `Pending` through `kubectl get pods`
- Change podAntiAffinity in `test.yaml` by commenting out top block and uncommenting bottom block
- `kubectl apply -f test.yaml`
- Observe 1 pod is still pending (deleting this pod has no effect)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7

Observed similar behavior on AWS EKS 1.22
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux dieter-Precision-7550 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
