### ISSUE TITLE
unmount volume with patch

### ISSUE THREAD

**Issue by STYNET** [kubernetes/kubernetes#110817]
Hello,

I have pached a deployment for mount a new volume. 
This my patch :
```
spec:
  template:
    spec:
      containers:
      - name: test3
        volumeMounts:
        - name: mount3
          mountPath: /var/www/rep3
      volumes:
      - name: mount3
        persistentVolumeClaim:
          claimName: pvc3
```

It work and now i have 3 volumes (2 old and 1 new).
This my deployment's describe :
```
...
Pod Template:
  ...
  Containers:
  ...
    Mounts:
      /var/www/rep1
      /var/www/rep2
      /var/www/rep3
...
  Volumes:
    pvc1:
      ...
    pvc2:
      ...
    pvc3:
      ...
```

For example, I need to unmounted rep2 (and remove pvc2) with a patch.
How do make this ?

Thank for your help.
