### ISSUE TITLE
Problem with mount emptyDir volume

### ISSUE THREAD

**Issue by es1o** [kubernetes/kubernetes#110832]
### What happened?

I have a deployment with emptyDir volume:
```
         volumeMounts:                                                                                                                                                                                                                                                                   
         - mountPath: /tmp                                                                                                                                                                                                                                                               
           name: tmp
...
       volumes:                                                                                                                                                                                                                                                                          
       - emptyDir: {}                                                                                                                                                                                                                                                                    
         name: tmp
```

When I start my deployment pod started, when I scale my deployment up, eg. to 10 replicas all replicas started.
When I scale down to 1 and want start again to 10 new deployments fails with error:

```
Warning  Failed     3s    kubelet            Error: cannot find volume "tmp" to mount into container "my-container"
```

I use 1.20.15 from AWS EKS.

### What did you expect to happen?

I'd like to be able scale deployment up and down.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create deployment with emptyDir
2. Scale up
3. Scale down
4. Scale up

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:41:58Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-a64ea69", GitCommit:"03450cdabfc4162d4e447e6d8c5037efe6d29742", GitTreeState:"clean", BuildDate:"2022-05-12T18:44:04Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>


### Cloud provider

<details>
AWS EKS 1.20
</details>


### OS version

Not releated


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
