### ISSUE TITLE
Enhance RBAC model to separate pod creation and port-forwarding

### ISSUE THREAD

**Issue by manuschillerdev** [kubernetes/kubernetes#110999]
For local development, it is a great workflow to have some services run remotely in the cloud and port-forward them to your local machine, so that as a developer I don't need to waste my resources on running all services locally.

From a cluster admin perspective, it makes sense to prohibit manual pod creation when using GitOps (e.g. ArgoCD) to avoid the deployed resources and the GitOps repo getting out of sync.

Port-Forwarding a service via `kubectl port-forward  svc/my-service 5432:5432` technically does create resources within the current namespace. Since they are being terminated automatically as soon as the port-forwarding ends it should not be seen as a problem with gitops (I assume - please correct me if I'm wrong!)

Would it be possible to express that in the rbac model like:
* users must not create resources manually
* users may create resources implicitly by using `kubectl port-foward` on their machine.

Would that be an option to consider?

**Comment by sftim** [comment]
Kubernetes already supports auth mechanisms that let you create port forwards but not create Pods. AIUI, that includes RBAC.

AIUI:
/kind support

**Comment by AndrewUnderwoodAtFanatics** [comment]
I haven't been able to identify what the existing mechanism might be for allowing port-forwarding but not pod creation.  If someone had details to share around how this can be achieved, that would be helpful.

**Comment by AndrewUnderwoodAtFanatics** [comment]
I think this article was the source of my confusion.

From the article:

```
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: my-namespace
  name: allow-port-forward
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward"]
  verbs: ["get", "list", "create"]
```

Having read it before I saw that the `role` was providing `create` for both `pods` and `pods/portforward` and with the explanation in the article, I took that at face value to mean that create was required for both resources.

I just cobbled together a quick test without pod create and it appears to be working:

```
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: my-namespace
  name: allow-port-forward
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
```

Now reading the comments on the article, I see that someone has suggested an even tighter scope:

```
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: my-namespace
  name: allow-port-forward
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
```

I will try this out tomorrow.

**Comment by AndrewUnderwoodAtFanatics** [comment]
Confirmed!  It appears the minimum viable permission set to allow port-forwarding to a pod and services is 

```
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: my-namespace
  name: allow-port-forward
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
```

Thanks all!
