### ISSUE TITLE
Resource Quota should enforce limits/request on ephemeral storage

### ISSUE THREAD

**Issue by Kartik494** [kubernetes/kubernetes#110956]
### What happened?

If user didn't set CPU/Memory limits in their pod but they have been limited by ResourceQuota, user gets the following error.

`Warning FailedCreate 2s (x4 over 20s) replicaset-controller (combined from similar events): Error creating: pods "ephpod-668668fc76-4rm6p" is forbidden: failed quota: ephtest: must specify limits.cpu`

On the other hand, user didn't set ephemeral-storage limit in their pod but it has been limited by ResourceQuota, the pod creation succeeds normally.
It means that user can avoid the limitation of ephemeral-storage defined by ResourceQuota.

```
apiVersion: v1
kind: Pod
metadata:
  name: ephpod
  namespace: quotatest
spec:
  containers:
  - name: con1
    image: nginx
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
  - name: con2
    image: nginx
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
  - name: con3
    image: nginx
    command: ["/bin/bash", "-c", "tail -f /dev/null"]
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
  terminationGracePeriodSeconds: 0
```
resourceQuota yaml file:

```
apiVersion: v1
kind: ResourceQuota
metadata:
    name: ephtest
    namespace: quotatest
spec:
    hard:
      cpu: "300m" 
      memory: 300Mi
      requests.ephemeral-storage: "300Mi" 

```

After deploying the pod the usage of CPU and memory got increased by the pod creation. But the usage of ephemeral-storage is the same.

```
# kubectl describe resourcequota ephtest -n quotatest
Name:              ephtest
Namespace:         quotatest
Resource           Used   Hard
--------           ----   ----
cpu                300m   300m
ephemeral-storage  0      300Mi
memory             300Mi  300Mi
```
The pod can write more than the limitation of ephemeral-storage defined by ResourceQuota.

```
kubectl exec ephpod -n quotatest -c con1 -- /bin/bash
Defaulted container "con1" out of: con1, con2, con3
sh-4.4$ dd if=/dev/zero of=/tmp/data bs=1M count=400
400+0 records in
400+0 records out
419430400 bytes (419 MB, 400 MiB) copied, 3.9856 s, 105 MB/s
sh-4.4$ du /tmp/data
409600  /tmp/data
sh-4.4$ exit
exit
```
There is no change in usage of ephemeral-storage in ResourceQuota.

```
kubectl describe resourcequota ephtest -n quotatest
Name:              ephtest
Namespace:         quotatest
Resource           Used   Hard
--------           ----   ----
cpu                300m   300m
ephemeral-storage  0      300Mi
memory             300Mi  300Mi
```

The [k8s source code](https://github.com/kubernetes/kubernetes/blob/master/pkg/quota/v1/evaluator/core/pods.go#L85) says that it was a mistake that user must make an explicit request/limit when ResourceQuota has CPU/Memory setting.
So it says that the current behaviour about ephemeral-storage is correct.
But In the current implementation, non-admin user can avoid the limitation of ephemeral-storage defined by ResourceQuota.
So how can admin handle it?

### What did you expect to happen?

1. Don't need to force user to set CPU or Memory limit even if admin defined ResourceQuota :
As we have covered this case with QoS classes i.e if we set CPU or memory limit to our pods, our pods are regarded as  guaranteed or Burstable class. It means that pods which have CPU or memory limit won't be evicted in prior to pods which have no CPU and Memory limit. So we didn't need to force user to set CPU or Memory limit to their pods even if admin defined ResourceQuota.

2. Need to force user to set ephemeral-storage limit if admin defined ResourceQuota :
we decides QoS class just by CPU and Memory limit. So QoS class would be the same if we set or don't set ephemeral-storage limit in our pod. It means that we cannot expect which pod will be evicted first.
    
### How can we reproduce it (as minimally and precisely as possible)?

Please find the sample yaml above for  pod and resourcequota 

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Kartik494** [comment]
cc @YuikoTakada

**Comment by Kartik494** [comment]
cc @jingxu97 @jsafrane

**Comment by jingxu97** [comment]
Hi @Kartik494 I think option 2 looks better to me to have consistent behavior with CPU and memory. WDYT?

**Comment by Kartik494** [comment]
cc @msau42

**Comment by Kartik494** [comment]
@jingxu97 yes option 2 looks ok to me too i.e Need to force user to set ephemeral-storage limit if admin defined ResourceQuota , i will be raising a  PR for this.
Thanks!!


> Hi @Kartik494 I think option 2 looks better to me to have consistent behavior with CPU and memory. WDYT?

**Comment by jingxu97** [comment]
@Kartik494 now I noticed about "The [k8s source code](https://github.com/kubernetes/kubernetes/blob/master/pkg/quota/v1/evaluator/core/pods.go#L85) says that it was a mistake that user must make an explicit request/limit when ResourceQuota has CPU/Memory setting."

I am not sure the reason behind it. Let's us sync up with sig-node people next week before committing this effort.

**Comment by Kartik494** [comment]
sure @jingxu97 please let me know on this.
Thanks!!

**Comment by wenwu449** [comment]
[This comment](https://github.com/kubernetes/kubernetes/blob/51ea7b21699ffc8857a7da9f2b1b4f293bf70a69/pkg/quota/v1/evaluator/core/pods.go#L121) mentioned the "coupled validation with resource counting" was introduced before QoS was introduced.

**Comment by YuikoTakada** [comment]
@wenwu449 Thank you for your comments. Is [this](https://github.com/kubernetes/kubernetes/blob/51ea7b21699ffc8857a7da9f2b1b4f293bf70a69/pkg/quota/v1/evaluator/core/pods.go#L121) written in any document? Or just in source code?

**Comment by Kartik494** [comment]
> [This comment](https://github.com/kubernetes/kubernetes/blob/51ea7b21699ffc8857a7da9f2b1b4f293bf70a69/pkg/quota/v1/evaluator/core/pods.go#L121) mentioned the "coupled validation with resource counting" was introduced before QoS was introduced.

Hi @wenwu449  thank you for your inputs as in  [comment](https://github.com/kubernetes/kubernetes/blob/51ea7b21699ffc8857a7da9f2b1b4f293bf70a69/pkg/quota/v1/evaluator/core/pods.go#L121)  it is mentioned that we need to explicitly request  in pod spec when enforcing `resource quota` on  `CPU` and `Memory` but when i enforce `resourcequota` on ephemeral-storage it would  not be enforced because we didn't set those request in pod spec. For `resourcequota` to  enforced on ephemeral-storage we should add in pod spec .

**Comment by jingxu97** [comment]
We discussed this issue in sig-node meeting this week. The reason we no longer enforce limit/request setting for pod if resource quota is present in the namespace is it will cause "best effort" pod fail to schedule in this case. For pods that have no limit/request setting is categorized as "best effort".  The main purpose of resource quota is to guarantee resource reservation for the pods having the resource settings. If the use case is to make sure all pods have a limit setting in namespace, limitRange can be used. 

/cc @derekwaynecarr @dchen1107

**Comment by YuikoTakada** [comment]
@jingxu97 thank you for having discussed and your comments.
Our use case(or perhaps concern) is security perspective:
For example, when I am a user and I want to require more storage, I would just not set ephemeral-storage's limit in my pod.
If I am an attacker, I will create multiple Pods which just infinity write garbage data to ephemeral-storage. Pods which were launched by other users and which require ephemeral-storage would be no longer able to work by that.
It's a problem for admin user in PaaS environment.

in order to  prevent this issue, does LimitRange match with our use case?

**Comment by pacoxu** [comment]
```
apiVersion: v1
kind: LimitRange
metadata:
  name: demo
  namespace: default
spec:
  limits:
  - default:
      ephemeral-storage: 2Gi
    defaultRequest:
      ephemeral-storage: 2Gi
    type: Container
```
Here is a demo to use. Then new pod created in the namespace will be applied with the default limit/request resources.
