### ISSUE TITLE
kubectl apply: prune should ignore no-namespaced resource if -n is not empty

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#110905]
seems I have  the same problem. save this to a file named `a.yaml`
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    environment: sandbox
    provider: kustomize
  labels:
    app: nginx
  name: nginx
  namespace: sandbox
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  type: NodePort
```

And run `kubectl apply --prune --dry-run=client --all -n sandbox -f a.yaml`, the results
```
service/nginx created (dry run)
namespace/cattle-system pruned (dry run)
```

I have no idea why it want to prune the `namespace/cattle-system`.

_Originally posted by @wd in https://github.com/kubernetes/kubernetes/issues/66430#issuecomment-708922169_
