### ISSUE TITLE
GKE FailedAttachVolume ControllerPublish not permitted on node "XYZ" due to backoff condition

### ISSUE THREAD

**Issue by igoooor** [kubernetes/kubernetes#110987]
### What happened?

I created a simple StatefulSet with volumeClaimTemplates (see "How to reproduce section"). However the pod stays in "Init" status and never succeed:
I can see the PVC and the PV, however on Google Cloud Console, I can see that the Disk with the same name as the PV is not used by any VM.
If I delete and recreate my resources over and over, sometimes it will succeed, but most of the time it will fail.

Here is the describe of my pod:
```
Name:           my-nginx-0
Namespace:      OMITTED
Priority:       0
Node:           gke-OMITTED-pool-6acbd600-ui3w/10.2.0.5
Start Time:     Wed, 06 Jul 2022 23:08:44 +0200
Labels:         controller-revision-hash=my-nginx-67c77bd754
                run=my-nginx
                statefulset.kubernetes.io/pod-name=my-nginx-0
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/my-nginx
Containers:
  nginx:
    Container ID:   
    Image:          nginx:1.14.2
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /cache from my-nginx (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jrr9s (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  my-nginx:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  my-nginx-my-nginx-0
    ReadOnly:   false
  kube-api-access-jrr9s:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason              Age                From                     Message
  ----     ------              ----               ----                     -------
  Normal   NotTriggerScaleUp   55s                cluster-autoscaler       pod didn't trigger scale-up: 1 pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling    52s (x3 over 57s)  default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
  Normal   Scheduled           48s                default-scheduler        Successfully assigned OMITTED/my-nginx-0 to gke-OMITTED-pool-6acbd600-ui3w
  Warning  FailedAttachVolume  12s (x7 over 47s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-fb926085-fc06-4912-bafe-e30dbe458e12" : rpc error: code = Unavailable desc = ControllerPublish not permitted on node "projects/OMITTED/zones/europe-west6-b/instances/gke-OMITTED-pool-6acbd600-ui3w" due to backoff condition

```

### What did you expect to happen?

Pod to be in ready state and volume to be attached

### How can we reproduce it (as minimally and precisely as possible)?

```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-nginx
spec:
  serviceName: my-nginx
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /cache
          name: my-nginx
      volumes:
      - name: my-nginx
        persistentVolumeClaim:
          claimName: my-nginx
  volumeClaimTemplates:
    - metadata:
        name: my-nginx
      spec:
        #storageClassName: premium-rwo
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 31Gi
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx

EOF
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1-gke.1400", GitCommit:"206efe6f8106824435f9e408af6f49e61b30ae54", GitTreeState:"clean", BuildDate:"2022-06-13T19:52:07Z", GoVersion:"go1.18.2b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Google Cloud Platform GKE
</details>

### OS version

<details>

Container-optimised OS with containerd (cos_containerd)

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
