### ISSUE TITLE
Static pod/Mirror pod resource information not being reflected in the pod status

### ISSUE THREAD

**Issue by swatisehgal** [kubernetes/kubernetes#110944]
**What happened?**
Resource information (request and limit) provided in the static pod spec cannot be seen in the corresponding mirror pod status. Because of this, irrespective of the resource request and limit provided in the static pod specification, the pod is created with `BestEffort` QoS class.

**What did you expect to happen?**
Expected to see the resource information in the mirror pod and the correct QoS (e.g. `Guaranteed` in case request==limit).

**How can we reproduce it (as minimally and precisely as possible)?**
1. Ensure that kubelet is configured with `staticPodPath: /etc/kubernetes/manifests/` field or a `--manifest-url=<URL>` as documented [here](https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/).
2.  Create a static pod on a node (in this example it was created on kind-worker node):
  ```
$ cat <<EOF >/etc/kubernetes/manifests/static-web.yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      resources:
      limits:
        cpu: 2
        memory: 20Mi
      requests:
        cpu: 2
        memory: 20Mi
      ports:
        - name: web
          containerPort: 80
  ```

4. List pods on the node
```
kubectl get pods -o wide
NAME                              READY   STATUS    RESTARTS   AGE     IP           NODE                 NOMINATED NODE   READINESS GATES
static-web-kind-worker            1/1     Running   0          41m     10.244.1.5   kind-worker          <none>           <none>

```
7. kubectl describe pods static-web-kind-worker
```
$ kubectl describe pods static-web-kind-worker

Name:         static-web-kind-worker
Namespace:    default
Priority:     0
Node:         kind-worker/172.18.0.3
Start Time:   Tue, 21 Jun 2022 02:13:03 +0100
Labels:       role=myrole
Annotations:  kubernetes.io/config.hash: db0fe0b685b41ea9725ee5dea6492248
              kubernetes.io/config.mirror: db0fe0b685b41ea9725ee5dea6492248
              kubernetes.io/config.seen: 2022-06-21T01:13:03.963502308Z
              kubernetes.io/config.source: file
Status:       Running
IP:           10.244.1.5
IPs:
  IP:           10.244.1.5
Controlled By:  Node/kind-worker
Containers:
  web:
    Container ID:   containerd://9e48916ca51022cd9f89c63e0982af3d43506bf8bb3d203c7301d0f35d89f444
    Image:          nginx
    Image ID:       docker.io/library/nginx@sha256:2bcabc23b45489fb0885d69a06ba1d648aeda973fae7bb981bafbb884165e514
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 21 Jun 2022 02:13:15 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:            <none>
QoS Class:          BestEffort
Node-Selectors:     <none>
Tolerations:        :NoExecute op=Exists
Events:
  Type    Reason   Age   From     Message
  ----    ------   ----  ----     -------
  Normal  Pulling  48m   kubelet  Pulling image "nginx"
  Normal  Pulled   48m   kubelet  Successfully pulled image "nginx" in 10.027281406s
  Normal  Created  48m   kubelet  Created container web
  Normal  Started  48m   kubelet  Started container web

```
**Kubernetes version**
```
$ kubectl version
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
 
```

**Comment by harshanarayana** [comment]
@swatisehgal 

```yaml
apiVersion: v1
kind: Pod
metadata:
name: static-web
labels:
  role: myrole
spec:
containers:
  - name: web
    image: nginx
    resources:
    limits:
      cpu: 2
      memory: 20Mi
    requests:
      cpu: 2
      memory: 20Mi
    ports:
      - name: web
        containerPort: 80
```
Unless this is an issue formatting the content while opening the issue here, there is an indentation issue in the yaml.

I was able to reproduce this with broken indents but not with proper yaml rendered. With proper yaml, things work just fine for me. 

```yaml
Name:         static-web-110944-worker
Namespace:    default
Priority:     0
Node:         110944-worker/172.18.0.4
Start Time:   Mon, 04 Jul 2022 20:13:31 +0530
Labels:       role=myrole
Annotations:  kubernetes.io/config.hash: 44e85cf536c94cae2b1c1e3a5bd4d3d0
              kubernetes.io/config.mirror: 44e85cf536c94cae2b1c1e3a5bd4d3d0
              kubernetes.io/config.seen: 2022-07-04T14:46:09.888503957Z
              kubernetes.io/config.source: file
Status:       Running
IP:           10.244.1.4
IPs:
  IP:           10.244.1.4
Controlled By:  Node/110944-worker
Containers:
  web:
    Container ID:   containerd://a48a811ce1e241cb09632b295d3cb4ca176c9866ae4f9997324f4974975a3de3
    Image:          nginx
    Image ID:       docker.io/library/nginx@sha256:10f14ffa93f8dedf1057897b745e5ac72ac5655c299dade0aa434c71557697ea
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 04 Jul 2022 20:16:28 +0530
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:            <none>
QoS Class:          BestEffort
Node-Selectors:     <none>
Tolerations:        :NoExecute op=Exists
Events:
  Type    Reason   Age   From     Message
  ----    ------   ----  ----     -------
  Normal  Pulling  25s   kubelet  Pulling image "nginx"
  Normal  Pulled   22s   kubelet  Successfully pulled image "nginx" in 2.822034721s
  Normal  Created  22s   kubelet  Created container web
  Normal  Started  22s   kubelet  Started container web
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
  - name: web
    image: nginx
    resources:
    limits:
      cpu: "2"
      memory: 20Mi
    requests:
      cpu: "2"
      memory: 20Mi
    ports:
      - name: web
        containerPort: 80
```

**Comment by harshanarayana** [comment]
```bash
Name:           static-web-110944-worker
Namespace:      default
Priority:       0
Node:           110944-worker/172.18.0.4
Start Time:     Mon, 04 Jul 2022 20:13:31 +0530
Labels:         role=myrole
Annotations:    kubernetes.io/config.hash: a2110af716c454ac5db693569ac5f7d9
                kubernetes.io/config.mirror: a2110af716c454ac5db693569ac5f7d9
                kubernetes.io/config.seen: 2022-07-04T14:50:41.897269174Z
                kubernetes.io/config.source: file
Status:         Pending
IP:
IPs:            <none>
Controlled By:  Node/110944-worker
Containers:
  web:
    Container ID:
    Image:          nginx
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  20Mi
    Requests:
      cpu:        2
      memory:     20Mi
    Environment:  <none>
    Mounts:       <none>
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:            <none>
QoS Class:          Guaranteed
Node-Selectors:     <none>
Tolerations:        :NoExecute op=Exists
Events:
  Type    Reason   Age    From     Message
  ----    ------   ----   ----     -------
  Normal  Pulling  6m12s  kubelet  Pulling image "nginx"
  Normal  Pulled   6m10s  kubelet  Successfully pulled image "nginx" in 2.844169004s
  Normal  Created  6m10s  kubelet  Created container web
  Normal  Started  6m10s  kubelet  Started container web
  Normal  Killing  4m48s  kubelet  Stopping container web
  Normal  Pulling  3s     kubelet  Pulling image "nginx"
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
  - name: web
    image: nginx
    resources:
      limits:
        cpu: "2"
        memory: 20Mi
      requests:
        cpu: "2"
        memory: 20Mi
    ports:
      - name: web
        containerPort: 80
```
