### ISSUE TITLE
nodeAffinity preferred is selected over podaffinity required

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/kubernetes#111094]
### What happened?

It seems that k8s will select a rule of preferred over a required one if the preferred rule has a weight:
```yaml
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - our-custom-nodepool
            weight: 1
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                statefulset.kubernetes.io/pod-name: must-be-together-pod
            topologyKey: kubernetes.io/hostname
```

### What did you expect to happen?

that the required rule will take precedence over the preferred one

### How can we reproduce it (as minimally and precisely as possible)?

add for a deployment this affinities:
- `nodeAffinity` with `preferredDuringSchedulingIgnoredDuringExecution` and weight 1
- `podAffinity` with `requiredDuringSchedulingIgnoredDuringExecution` and no wight

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:10:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.202", GitCommit:"88deae00580af268497b9656f216cb092b630563", GitTreeState:"clean", BuildDate:"2022-06-03T03:27:52Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Google GKE
</details>

### OS version

<details>
Container-Optimized OS with containerd (cos_containerd)
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
