### ISSUE TITLE
Add ability to opt-out of pruning and perform server side validation 

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/kubernetes#111074]
It was surprising to see that when a schema is full defined pruning is the default behaviour. I tried to read through the KEPs to determine why unknown fields wouldn't cause the API server to return an error and didn't really find an answer.

For example the [validation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation) example has:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                  pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                image:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```

If I mistype `replicas` for `replica` there doesn't seem to be a way to have server side validation return an error saying 'replica' is an unknown field.

ie.
```
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * *"
  image: my-awesome-cron-image
  replica: 15
```

kubectl supports client side validation - but unfortunately a lot of tools don't shell out to kubectl but instead make API calls directly.
