### ISSUE TITLE
re-attach fails after exiting from ephemeral container

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes/kubernetes#111147]
### What happened?

- Started a minikube cluster(minikube version: v1.25.2, commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7)
- Applied below deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
- Ran debug command for one of pods;
```bash
$ ./_output/bin/kubectl debug nginx-deployment-9456bbbf9-cm9f6 -it --image=busybox
(saw terminal successfully)
```
- exited from ephemeral container by typing `exit` and it printed `Session ended, resume using 'kubectl attach nginx-deployment-9456bbbf9-cm9f6 -c debugger-lnz6b -i -t' command when the pod is running` as mentioned in [here](https://github.com/kubernetes/kubernetes/blob/43c2ae479f056f9e420062e11f3251b7095c3108/staging/src/k8s.io/kubectl/pkg/cmd/debug/debug.go#L367)
- Assured that ephemeral container is in pod and it's `ready: false`

Lastly;
```bash
$ ./_output/bin/kubectl attach nginx-deployment-9456bbbf9-cm9f6 -c debugger-lnz6b -i -t 
If you don't see a command prompt, try pressing enter.
error: unable to upgrade connection: container debugger-lnz6b not found in pod nginx-deployment-9456bbbf9-cm9f6_default
```

After investigating the problem https://github.com/kubernetes/kubernetes/blob/f25ca15e1c47ebd8036c1fb5c06fe8fe6714807a/pkg/kubelet/kubelet_pods.go#L1908 looks not returning ephemeral containers and thereby, re-attach does not work. 

### What did you expect to happen?

It should re-attach to ephemeral container or we should remove `session ended, you can reconnect with attach` command message.

### How can we reproduce it (as minimally and precisely as possible)?

As described above.

### Kubernetes version

Minikube 1.25
Kubectl master branch

### Cloud provider

None

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
