### ISSUE TITLE
Creating service account does not auto generate corresponding secret 

### ISSUE THREAD

**Issue by alifiroozi80** [kubernetes/kubernetes#111167]
Hello everyone, 
 i've read [this issuer](https://github.com/kubernetes/kubernetes/issues/19980) and [this answer](https://github.com/kubernetes/kubernetes/issues/19980#issuecomment-173961597) from @[kelseyhightower](https://github.com/kelseyhightower) and checked my `kube-controller-manager.yaml`:

```shell
$ sudo vim /etc/kubernetes/manifests/kube-controller-manager.yaml
```
```yaml
[...]
spec:
  containers:
  - command:
    - kube-controller-manager
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-name=kubernetes
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --use-service-account-credentials=true
    image: k8s.gcr.io/kube-controller-manager:v1.24.1
[...]
```

As you can see,  `--use-service-account-credentials` is set to `true` and the `--service-account-private-key-file=/etc/kubernetes/pki/sa.key` is pointing to a private key...

But still the serviceaccount doesn't creates Tokens!

How can i fix this issue?

PS: Kubernetes versoin: `v1.24.1`

_Originally posted by @alifiroozi80 in https://github.com/kubernetes/kubernetes/issues/19980#issuecomment-1182950590_
