### ISSUE TITLE
commonLabels vs PodLabels - error in casting and then   podSelector/matchLabels

### ISSUE THREAD

**Issue by ch0mik** [kubernetes/kubernetes#111112]
/sig Network

### What happened?

the automatic casting of value from commonLabels for Pods Labels makes misleading matchLabels into others K8s Kinds like NetworkPolicy.

the workaround is only change into NetworkPolicy definition to : 
```
spec:
  podSelector: {}
```

PS. 
when i tried change it into Kustomize file to int value - got the error : 
```
error: json: cannot unmarshal number into Go struct field Kustomization.commonLabels of type string
```

PPS. 
selector for Service works ok, with the same selector with quotes like in NetworkPolicy ... 
```
  spec:
    clusterIP: 100.126.200.216
    clusterIPs:
    - 100.126.200.216
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: myapp
      application-component: "00000"
      environment: dev
      tier: frontend
```
3 replicas of pods for deploy
```console
kubectl -n mynamespace get endpoints 
```
```
NAME           ENDPOINTS                                                AGE
myapp 100.72.207.2:8443,100.72.207.5:8443,100.72.207.7:8443    97s
```

```



### What did you expect to happen?

fix it ;) that Labels into Pods are the same on all Kinds of Kubernetes. 


### How can we reproduce it (as minimally and precisely as possible)?

When in Kustomize file i put the 

```
commonLabels:
  environment : dev
  application-component: "00000"
```

the Pods have Labels as int

```console
kubectl describe pod nameofpod
```

```
Labels:      
              app=myapp
              app.kubernetes.io/component=webapp
              app.kubernetes.io/name=myapp
              application-component=00000
              environment=dev
              pod-template-hash=65bfb7966d
              tier=frontend
```

and then my NetworkPolicy, that have commonLabel from Kustomize file not matching this label but is int not string ...

```console
kubectl get networkpolicy mypolicy 
```

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
(...)
  labels:
    application-component: "00000"
    environment: dev
  name: allow-application-ingress
  namespace: mynamespace
  resourceVersion: "134481831"
  uid: 5e4feaeb-0954-46b6-a2c7-6b71e611f1d9
spec:
  ingress:
  - ports:
    - port: 8443
      protocol: TCP
  podSelector:
    matchLabels:
      application-component: "00000"
      environment: dev
      tier: frontend
  policyTypes:
  - Ingress
```

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11", GitCommit:"5824e3251d294d324320db85bf63a53eb0767af2", GitTreeState:"clean", BuildDate:"2022-06-16T05:33:55Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

N/A

**Comment by aojea** [comment]
@ch0mik is this not a kustomize problem?

**Comment by thockin** [comment]
I'm sorry, I don't understand the bug.  Can you show a more complete example if what you started with, what you did, and what happened?

**Comment by ch0mik** [comment]
yes, it dosnt problem with kustomize but problem z podSelector matching on NetworkPolicy
Kustomize only generate additional selectors to objects as NetworksPolicy / Service 

```
  podSelector:
    matchLabels:
      application-component: "00000" - added by Kustomize
      environment: dev - added by Kustomize
      tier: frontend
```

but the added labels for PodSelector forks fine with Service, but not working with NetworkPolicy.
The Network Policy probably has error on casts/matching value like application-component: "00000" 

regards
Pawel
