### ISSUE TITLE
Setcap doesn't work on master but works on v1.24.3

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#111196]
### What happened?

A test with a non-root container fails on master;
```
vm-002 ~ # kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.0-alpha.2.333+5b92e46b2238b4
Kustomize Version: v4.5.4
Server Version: v1.25.0-alpha.2.333+5b92e46b2238b4
vm-002 ~ # kubectl exec -it alpine-test-kc2c5 -- sh
~ $ id
uid=1000(1000) gid=3000
~ $ getcap /sbin/ip
/sbin/ip cap_net_admin=eip
~ $ /sbin/ip addr add 10.10.10.10/32 dev lo
RTNETLINK answers: Operation not permitted
```
The `/sbin/ip` has cap_net_admin=eip and this works on earlier version. We have a requirement on non-root containers but we must use the `ip` command in multi-network setups.

### What did you expect to happen?

I expect the same behaivor as in earlier versions:
```
vm-002 ~ # kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.24.3
vm-002 ~ # kubectl exec -it alpine-test-hk4fp -- sh
~ $ id
uid=1000(1000) gid=3000
~ $ getcap /sbin/ip
/sbin/ip cap_net_admin=eip
~ $ /sbin/ip addr add 10.10.10.10/32 dev lo
~ $ ip addr show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet 10.10.10.10/32 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
```
It works fine on `v1.24.3`.

### How can we reproduce it (as minimally and precisely as possible)?

Use this manifest and execute commands as described above:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alpine-test
spec:
  selector:
    matchLabels:
      app: alpine-test
  template:
    metadata:
      labels:
        app: alpine-test
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
      containers:
      - name: alpine-test
        imagePullPolicy: IfNotPresent
        image: registry.nordix.org/cloud-native/xcluster/alpine-test:latest
        command: ["tail", "-f", "/dev/null"]
        securityContext:
          #allowPrivilegeEscalation: false
          capabilities:
            add: ["NET_ADMIN"]
```

### Anything else we need to know?

I suspect some feature that had become beta. I have tried to set;
```
SeccompDefault=false
```
but that did not help.

### Kubernetes version

```
Linux 5.18.1 #8 SMP PREEMPT_DYNAMIC Sat Jun 18 12:53:37 CEST 2022
```

### Cloud provider

None

### OS version

Own busybox Linux

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

```
crio version 1.24.1
```
