### ISSUE TITLE
Errror during launch of Postgres as statefulset

### ISSUE THREAD

**Issue by RavitejaBadugu** [kubernetes/kubernetes#111270]
I am running the below code in minikube cluster in aws ec2 instance. I installed csi driver and give necessary permissions by following [the csi driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md).
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      type: DB
  serviceName: write-db-service
  replicas: 1
  template:
    metadata:
      labels:
        type: DB
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: job-creds
        volumeMounts:
        - name: my-vol
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: my-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: aws-storage
      resources:
        requests:
          storage: 3Gi
```
I am getting error during mounting

```
Events:
  Type     Reason                  Age                 From                     Message
  ----     ------                  ----                ----                     -------
  Normal   Scheduled               115s                default-scheduler        Successfully assigned default/postgres-0 to minikube
  Normal   SuccessfulAttachVolume  111s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-3db94a61-d6ea-4eab-84ab-c3cda450aea9"
  Warning  FailedMount             41s (x8 over 105s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-3db94a61-d6ea-4eab-84ab-c3cda450aea9" : rpc error: code = Internal desc = Failed to find device path /dev/xvdba. no device path for device "/dev/xvdba" volume "vol-0e50e939b9ad9bc71" found!
```
I even tried changing pgdata path and mount path as
```
env:
- name: PGDATA
  value: /var/lib/postgresql/data/pgdata
volumeMounts:
- name: my-vol
  mountPath: /var/lib/postgresql/data
```
But still, I'm getting the same error
