### ISSUE TITLE
Effective pod limits are not correctly computed

### ISSUE THREAD

**Issue by mladedav** [kubernetes/kubernetes#111393]
### What happened?

When there is an init container with limits specified and other containers (both init and standard) do not specify any limits, the limit of the first init container is used as the effective limit for the pod.

[The documentation](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#resources) states that it should be 0, unless I misunderstood something.

### What did you expect to happen?

I expected to see no limit if either the sum of all app containers has no limit (i.e. any of them does not have a limit) or if the effective init limit is none.

### How can we reproduce it (as minimally and precisely as possible)?

Apply this pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
  - name: init1
    image: nginx:1.14.2
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
  - name: init2
    image: nginx:1.14.2
    resources:
      limits:
        cpu: 0
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
      limits:
        cpu: 0
        memory: 0
```

Check the pod's limits with `kubectl node describe` (I am not sure if there is better way to go about this).

### Anything else we need to know?

The behavior is the same regardless of either setting the limit to 0 or omitting it.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
KinD.
Originally uncoverd on AKS running 1.22.
</details>

### OS version

<details>

```console
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                    OSArchitecture  Version
19044        Microsoft Windows 10 Home  64-bit          10.0.19044
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
