### ISSUE TITLE
Liveness & Readiness probe execution difference between version <=v1.19 vs version >= v1.20

### ISSUE THREAD

**Issue by advaaitt** [kubernetes/kubernetes#111410]
### What happened?

In version <= v1.19 the liveness probe starts first and readiness starts with a delay after liveness, whereas the probes start at the same time in version >= v1.20
I have Exec Type Liveness and Readiness probes configured as follows. 
```
    livenessProbe:
      exec:
        command:
        - sh
        - -c 
        - 'sleep 8 && echo "liveness"'
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    readinessProbe:
      exec:
        command:
        - sh
        - -c 
        - 'sleep 8 && echo "readiness"'
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
```

### What did you expect to happen?

With this configuration, I am expecting to see the 2 probe processes inside the container for each probe to start at the same time.
I could not find any documentation of this change

### How can we reproduce it (as minimally and precisely as possible)?

Create a Pod using following Manifest:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
  name: probes
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    livenessProbe:
      exec:
        command:
        - sh
        - -c 
        - 'sleep 8 && echo "liveness"'
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    readinessProbe:
      exec:
        command:
        - sh
        - -c 
        - 'sleep 8 && echo "readiness"'
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
```

Run following command and monitor probe processes.
```
kubectl exec -it busybox -- watch ps -ef 
```

### Anything else we need to know?

I have a script for these probes which invoke JVM and the behavior after v1.20 introduced higher CPU utilization. I was able to reduce this utilization by making these probes happen one after the other (as it happened in <=v1.19) by changing the probe configuration as follows:
```
    livenessProbe:
      exec:
        command:
        - sh
        - -c 
        - 'sleep 8 && echo "liveness"'
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 13
      successThreshold: 1
      timeoutSeconds: 10
    readinessProbe:
      exec:
        command:
        - sh
        - -c 
        - 'sleep 8 && echo "readiness"'
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 19
      successThreshold: 1
      timeoutSeconds: 10
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
