### ISSUE TITLE
multi KMS encryption provider support  

### ISSUE THREAD

**Issue by romdalf** [kubernetes/kubernetes#111405]
### What would you like to be added?

Add Secret/ConfigMap API annotations for KMS provider defined within EncryptionConfiguration

Considering the below `EncryptionConfiguration` including two KMS provider plugin references:
```YAML
---
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - kms:
          name : myFirstKmsPlugin
          endpoint: unix:///tmp/myFirstKmsPlugin.sock
          cachesize: 100
      - kms:
          name : mySecondKmsPlugin
          endpoint: unix:///tmp/mySecondKmsPlugin.sock
          cachesize: 100
      - identity: {}

```

Creating a secret using `myFirstKmsPlugin` as KMS provider plugin could be done with an annotation like:  
```YAML 
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret01
  annotations:
    kmsProviders: "myFirstKmsPlugin"
type: Opaque
data:
  USER_NAME: YWRtaW4=
  PASSWORD: MWYyZDFlMmU2N2Rm
```

and for a second secret with the second KMS provider plugin: 
```YAML 
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret02
  annotations:
    kmsProviders: "mySecondKmsPlugin"
type: Opaque
data:
  USER_NAME: YWRtaW4=
  PASSWORD: MWYyZDFlMmU2N2Rm
```

Although considering the high level API construct, the annotation could be more of the like or similar to:

```YAML
metadata:
  annotations:
    kubernetes.io/kmsprovider.class: "myFirstKmsPlugin"
```

Also, from object standpoint, changing the annotation from (based on the above example) provider to another:

```YAML
--- before
...
metadata:
  name: mysecret01
  annotations:
    kmsProviders: "myFirstKmsPlugin"
...

--- after
metadata:
  name: mysecret01
  annotations:
    kmsProviders: "mySecondKmsPlugin"
```

would trigger a replace logic like `kubectl get secrets mysecret01 -o json | kubectl replace -f -` any other relevant mutation to achieve the migration from one provider to another.

### Why is this needed?

Extend the value-add of the KMS provider plugin for multi KMS, multi tenancy, multi cloud, multi staging scenarios. 

The current EncryptionConfiguration supports multiple entries in a fallback mechanism with limited options for selecting a specific entry for a secret or configmap resource:

1. if the first entry in `provider` is a KMS, then `aescbc` and `identity`, the logic from an API server perspective is a suboptimal roundrobin till success for reads (with decryption) or FIFO for write
1. if migration from a KMS provider to another, a [tricky play](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#switching-from-a-local-encryption-provider-to-the-kms-provider) around the EncryptionConfiguration order has to be achieved with a disruptive restart of API server
1. if multi KMS would be involved for multi-tenancy and/or in multi-staging environment, there is no or limited capability to target a specific KMS from an API call perspective 
1.  no multi KMS providers would be used to support a failback from cloud services

Within the [version 2-alpha of the KMS provider plugin Trousseau](https://github.com/ondat/trousseau/tree/v2-alpha), we have implemented multi KMS provider support (3), migration helper (2), multi KMS encryption (4) but we believe this should be a logic handled at the Kubernetes API server level to avoid clash of request and data leading to potential disruption and corruption.
