### ISSUE TITLE
Unable to create cluster with smaller subnet than 24

### ISSUE THREAD

**Issue by sreejithrangarajan** [kubernetes/kubernetes#111425]
### What happened?

While trying to deploy a small K8s cluster using Kubespray the part of initializing the first master is failing with below error.

sudo /usr/local/bin/kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml --ignore-preflight-errors=all --skip-phases=addon/coredns --upload-certs --v=6
[sudo] password for ignite:
I0725 23:13:42.501687  780633 initconfiguration.go:255] loading configuration from "/etc/kubernetes/kubeadm-config.yaml"
I0725 23:13:42.506465  780633 kubelet.go:214] the value of KubeletConfiguration.cgroupDriver is empty; setting it to "systemd"
**podSubnet: Invalid value: "10.0.0.0/25": the size of pod subnet with mask 25 is smaller than the size of node subnet with mask 24**

**kubeadm-config.yaml**

```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.28.253
  bindPort: 6443
certificateKey: ffc9ed2862bb7fabacfde205e8adf286aabe2cef11482a75758f21ea4cb83caa
nodeRegistration:
  name: node1
  taints: []
  criSocket: unix:////var/run/containerd/containerd.sock
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: cluster.local
etcd:
  external:
      endpoints:
      - https://192.168.28.253:2379
      caFile: /etc/ssl/etcd/ssl/ca.pem
      certFile: /etc/ssl/etcd/ssl/node-node1.pem
      keyFile: /etc/ssl/etcd/ssl/node-node1-key.pem
dns:
  imageRepository: registry.k8s.io/coredns
  imageTag: v1.8.6
networking:
  dnsDomain: cluster.local
  serviceSubnet: "10.0.0.128/25"
  podSubnet: "10.0.0.0/25"
kubernetesVersion: v1.24.0
controlPlaneEndpoint: 192.168.28.253:6443
certificatesDir: /etc/kubernetes/ssl
imageRepository: registry.k8s.io
apiServer:
  extraArgs:
    default-not-ready-toleration-seconds: "300"
    default-unreachable-toleration-seconds: "300"
    anonymous-auth: "True"
    authorization-mode: Node,RBAC
    bind-address: 0.0.0.0
    apiserver-count: "1"
    endpoint-reconciler-type: lease
    service-node-port-range: 2000-36767
    service-cluster-ip-range: "10.0.0.128/25"
    kubelet-preferred-address-types: "InternalDNS,InternalIP,Hostname,ExternalDNS,ExternalIP"
    profiling: "False"
    request-timeout: "1m0s"
    enable-aggregator-routing: "False"
    service-account-lookup: "True"
    storage-backend: etcd3
    allow-privileged: "true"
    feature-gates: "SCTPSupport=True"
    event-ttl: 1h0m0s
  extraVolumes:
  - name: usr-share-ca-certificates
    hostPath: /usr/share/ca-certificates
    mountPath: /usr/share/ca-certificates
    readOnly: true
  certSANs:
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - kubernetes.default.svc.cluster.local
  - 10.0.0.129
  - localhost
  - 127.0.0.1
  - node1
  - lb-apiserver.kubernetes.local
  - 192.168.28.253
  - ignite-KVM
  timeoutForControlPlane: 5m0s
controllerManager:
  extraArgs:
    node-monitor-grace-period: 40s
    node-monitor-period: 5s
    cluster-cidr: "10.0.0.0/25"
    service-cluster-ip-range: "10.0.0.128/25"
    node-cidr-mask-size: "27"
    profiling: "False"
    terminated-pod-gc-threshold: "12500"
    bind-address: 0.0.0.0
    leader-elect-lease-duration: 15s
    leader-elect-renew-deadline: 10s
    feature-gates: "SCTPSupport=True"
    configure-cloud-routes: "false"
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
    config: /etc/kubernetes/kubescheduler-config.yaml
    feature-gates: "SCTPSupport=True"
  extraVolumes:
  - name: kubescheduler-config
    hostPath: /etc/kubernetes/kubescheduler-config.yaml
    mountPath: /etc/kubernetes/kubescheduler-config.yaml
    readOnly: true
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
clientConnection:
  acceptContentTypes:
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig:
  qps: 5
clusterCIDR: "10.0.0.0/25"
configSyncPeriod: 15m0s
conntrack:
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
enableProfiling: False
healthzBindAddress: 0.0.0.0:10256
hostnameOverride: node1
iptables:
  masqueradeAll: False
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  excludeCIDRs: []
  minSyncPeriod: 0s
  scheduler: rr
  syncPeriod: 30s
  strictARP: False
  tcpTimeout: 0s
  tcpFinTimeout: 0s
  udpTimeout: 0s
metricsBindAddress: 0.0.0.0:10249
mode: ipvs
nodePortAddresses: []
oomScoreAdj: -999
portRange:
udpIdleTimeout: 250ms
featureGates:
  SCTPSupport: True
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
- 10.0.0.138
featureGates:
  SCTPSupport: True
```
 

### What did you expect to happen?

The cluster should have been deployed with the above subnets

### How can we reproduce it (as minimally and precisely as possible)?

Attached the kubeadm-config.yaml used for creation.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4

```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux ignite-KVM 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
Kubespray latest
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/remove-kind bug
/kind support
/remove-sig network
/cc @neolit123 @pacoxu 

The configuration has `node-cidr-mask-size: "27"`
```
controllerManager:
  extraArgs:
    node-monitor-grace-period: 40s
    node-monitor-period: 5s
    cluster-cidr: "10.0.0.0/25"
    service-cluster-ip-range: "10.0.0.128/25"
    node-cidr-mask-size: "27"
    profiling: "False"
    terminated-pod-gc-threshold: "12500"
    bind-address: 0.0.0.0
    leader-elect-lease-duration: 15s
    leader-elect-renew-deadline: 10s
    feature-gates: "SCTPSupport=True"
    configure-cloud-routes: "false"
```

but it seems that the flag `node-cidr-mask-size` was deprecated when dual-stack GA on kubeadm

https://github.com/kubernetes/kubernetes/pull/104770

so you have to use in this case `node-cidr-mask-size-ipv4: "27"`
