### ISSUE TITLE
remove provider list ordering dependency within EncryptionConfiguration

### ISSUE THREAD

**Issue by romdalf** [kubernetes/kubernetes#111532]
### What would you like to be added?

The current behavior of the EncryptionConfiguration for the provider list is order based requiring a restart of the API server to acknowledge the a newly defined order. 

As an example, moving from this definition:
```yaml
---
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - identity: {}
      - kms:
          name : myKmsPlugin
          endpoint: unix:///tmp/myKmsPlugin.sock
          cachesize: 100
```
to the following one will require the API server to be restart:
```yaml
---
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - kms:
          name : myKmsPlugin
          endpoint: unix:///tmp/myKmsPlugin.sock
          cachesize: 100
      - identity: {}
```

With proposal #111405 will provide the necessary construct to enable the above. 

### Why is this needed?

The current behavior is source of disruption from a service perspective, requires an user with elevate privileges, and does not allow to leverage the KMS provider plugin capabilities within a the context of managed kubernetes offering (no access to the control plane nodes). 

This change will improve:
- day 2 operations; move the EncryptionConfiguration to a regular CRUD API object 
- resilience and service continuity by avoiding the restart of the API server
- broaden the usage of the KMS provider plugin to managed kubernetes offerings
