### ISSUE TITLE
Egress network policy blocks readiness probe

### ISSUE THREAD

**Issue by ErikEngerd** [kubernetes/kubernetes#111581]
### What happened?

I have deployed the nginx ingress controller using helm. 

```> helm list
NAME    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                   APP VERSION
nginx   nginx           53              2022-07-03 20:30:34.187933627 +0200 CEST        deployed        nginx-ingress-0.13.2    2.2.2      
```

When securing my cluster using network policies, I noticed that the nginx ingress controller was failing its readiness probe. This was also failing with only a single network policy present for egress. This network policy is: 

```
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-allow-nothing
  namespace: nginx
spec:
  podSelector: {}
  policyTypes:
    - Egress
```

The output of the kubectl describe of the affected pod is 
```  
Warning  Unhealthy  5m28s (x22 over 5m47s)  kubelet            Readiness probe failed: Get "http://10.200.208.50:8081/nginx-ready": dial tcp 10.200.208.50:8081: connect: connection refused


```

### What did you expect to happen?

Upon deleting an nginx pod it should come back and pass its readiness probe. The reason is that it is connecting to its own IP. Even when adding explicit egress rules for TCP port 8081, it still fails. 

In general network policies should not affect readiness probes. 

### How can we reproduce it (as minimally and precisely as possible)?

```
helm repo add nginx-stable https://helm.nginx.com/stable
helm install -n nginx --create-namespace nginx nginx-stable/nginx-ingress -f values.yaml
```

Wait until nginx is successfully running and all pods are running. 

Now create the network policy: 
```
kubectl apply -f networkpolicy.yaml # the policy shown above
```

And delete one of the nginx pod. 
The pod now fails because of a a readiness probe. 

### Anything else we need to know?

The network policy is the only network policy that I used for this test. It does not allow communication to any other pods in the system. However, my default network policies did cover egress and ingress rules to the pods that it needs to reach. The example is just a minimal working example. 

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
kubeadm install on centos 7
</details>

### OS version

Server OS version:

<details>

```console
# On Linux:
$ cat /etc/os-release
# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

$ uname -a
Linux panther 4.18.0-301.1.el8.x86_64 #1 SMP Tue Apr 13 16:24:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
helm was used in the example
</details>

### Container runtime (CRI) and version (if applicable)

<details>
# docker -v
Docker version 20.10.6, build 370c289
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI: calico

> kubectl exec -it -n kube-system calicoctl -- calicoctl version
Client Version:    v3.23.1
Git commit:        967e24543
Cluster Version:   v3.23.1
Cluster Type:      typha,kdd,k8s,operator,bgp,kubeadm

</details>

**Comment by ErikEngerd** [comment]
A simple deployment with an httpd container and readiness check works together with a NetworkPolicy that disables all egress: 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4
          ports: 
            - containerPort: 80
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-allow-nothing
spec:
  podSelector: {}
  policyTypes:
    - Egress

```

It also works when replacing the deployment by a daemonset which is what I was using for nginx.
