### ISSUE TITLE
Kubelet removes pause container to free up disk space

### ISSUE THREAD

**Issue by akunszt** [kubernetes/kubernetes#111796]
### What happened?

The Kubelet garbage collector mechanism started on one of our nodes and it choose to remove the `pause` container even if it was in use by pods already running on the node.

```
Aug 11 04:29:45 ip-x-x-x-x.ec2.internal kubelet[2188]: I0811 04:29:45.635975   10660 image_gc_manager.go:310] "Disk usage on image filesystem is over the high threshold, trying to free bytes down to the low threshold" usage=87 highThreshold=85 amountToFree=8078762803 lowThreshold=80
Aug 11 04:29:45 ip-x-x-x-x.ec2.internal kubelet[2188]: I0811 04:29:45.638055   10660 image_gc_manager.go:387] "Removing image to free bytes" imageID="sha256:ed210e3e4a5bae1237f1bb44d72a05a2f1e5c6bfe7a7e73da179e2534269c459" size=298685
Aug 11 04:29:45 ip-x-x-x-x.ec2.internal containerd[2070]: time="2022-08-11T04:29:45.638293084Z" level=info msg="RemoveImage \"sha256:ed210e3e4a5bae1237f1bb44d72a05a2f1e5c6bfe7a7e73da179e2534269c459\""
Aug 11 04:29:45 ip-x-x-x-x.ec2.internal containerd[2070]: time="2022-08-11T04:29:45.681130419Z" level=info msg="ImageDelete event &ImageDelete{Name:hiya.local/ext/pause:3.5,XXX_unrecognized:[],}"                                                                                                                                                                                 
Aug 11 04:29:45 ip-x-x-x-x.ec2.internal containerd[2070]: time="2022-08-11T04:29:45.718117915Z" level=info msg="ImageDelete event &ImageDelete{Name:sha256:ed210e3e4a5bae1237f1bb44d72a05a2f1e5c6bfe7a7e73da179e2534269c459,XXX_unrecognized:[],}"
```

We use a solution to preload some infrastructural containers and because of that those images couldn't be able to fetch by kubelet during runtime. This rendered that whole node is unusable and caused some issues in our production services as pods stuck in ContainerCreating phase is not handled by pod controllers.

We see this behaviour only on 1.24 but we didn't run 1.23 and 1.22 for a longer period of time so I'm not 100% sure that those were unaffected.

### What did you expect to happen?

Kubelet is not removing containers in use.

### How can we reproduce it (as minimally and precisely as possible)?

This is just a theory but it should work.

* Set the sandbox image in the containerd configuration to a container which cannot be downloaded automatically.
```
[plugins."io.containerd.grpc.v1.cri"]
sandbox_image = "foo.bar/ext/pause:3.5"
```
* Fetch the pause image manually and tag it to match the sandbox_image.
* Start containerd and kubelet.
* Start a few pods on the node.
* Fill up the disk until the kubelet initiates the image gc procedure.
* Check the logs and the `crictl images` to verify that the pause image is deleted.
* Try to start any pod on the node but I assume you aware that without the pause image it won't work.

### Anything else we need to know?

The kubelet command line options are:
```
/usr/local/bin/kubelet --cert-dir=/etc/kubernetes/tls --cloud-provider=external --config=/etc/kubernetes/kubelet.yaml --container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --hostname-override=ip-x-x-x-x.ec2.internal --kubeconfig=/etc/kubernetes/kubeconfig.yaml --node-ip=x.x.x.x --node-labels=foo.bar/node-role=worker,foo.bar/node-group=general,foo.bar/node-kind=on-demand
```
The kubelet configuration:
```yaml
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  x509:
    clientCAFile: /etc/ssl/certs/foobar-kubernetes-ca.pem
  webhook:
    enabled: true
    cacheTTL: 2m0s
authorization:
  mode: AlwaysAllow
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: systemd
cgroupRoot: "/"
cgroupsPerQOS: true
clusterDomain: cluster.local
clusterDNS:
  - 10.2.0.10
enforceNodeAllocatable:
  - pods
evictionHard:
  memory.available: 250Mi
  nodefs.available: 10%
evictionPressureTransitionPeriod: 5m0s
hairpinMode: hairpin-veth
kubeReserved:
  cpu: 500m
  ephemeral-storage: 1Gi
  memory: 1Gi
kubeReservedCgroup: "/system.slice"
maxPods: 110
readOnlyPort: 0
registerNode: true
registryPullQPS: 20
registryBurst: 30
serializeImagePulls: false
staticPodPath: "/etc/kubernetes/manifests"
systemReserved:
  cpu: 500m
  ephemeral-storage: 1Gi
  memory: 1Gi
systemReservedCgroup: "/system.slice"
tlsCertFile: "/etc/kubernetes/tls/server-bundle.pem"
tlsPrivateKeyFile: "/etc/kubernetes/tls/server-key.pem"
tlsCipherSuites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_RSA_WITH_AES_256_GCM_SHA384
  - TLS_RSA_WITH_AES_128_GCM_SHA256
```

### Kubernetes version

<details>

```console
$ kubectl version --output yaml
clientVersion:
  buildDate: "2022-07-13T14:30:46Z"
  compiler: gc
  gitCommit: aef86a93758dc3cb2c658dd9657ab4ad4afc21cb
  gitTreeState: clean
  gitVersion: v1.24.3
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-07-13T14:23:26Z"
  compiler: gc
  gitCommit: aef86a93758dc3cb2c658dd9657ab4ad4afc21cb
  gitTreeState: clean
  gitVersion: v1.24.3
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
```

</details>

### Cloud provider

<details>
We are running in AWS but not EKS. We are using EC2 instances directly.
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3033.2.3
VERSION_ID=3033.2.3
BUILD_ID=2022-03-02-2032
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3033.2.3 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
$ uname -a
Linux ip-x-x-x-x.ec2.internal 5.10.102-flatcar #1 SMP Wed Mar 2 19:40:13 -00 2022 x86_64 AMD EPYC 7R13 Processor AuthenticAMD GNU/Linux
```
</details>

### Install tools

<details>
None, we use our own solution to deploy a Kubernetes cluster.
</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
$ containerd --version
containerd github.com/containerd/containerd 1.5.9 3bf67dd479b3beba5d4d82590593df2d9d63534f
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Not relevant (I think).
</details>
