### ISSUE TITLE
k8s apiserver write big custom object timeout, apiserver high cpu

### ISSUE THREAD

**Issue by silenceper** [kubernetes/kubernetes#111819]
### What happened?

A timeout occurred when writing a large object

schema.yaml content size 180k
```
✦ ➜ kubectl apply -f schema.yaml
Error from server (Timeout): error when creating "schema.yaml": Timeout: request did not complete within requested timeout - context deadline exceeded
```

k8s apiserver log:
```
{"level":"warn","ts":"2022-08-12T12:54:22.608Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0166e5dc0/#initially=[https://[::1]:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
E0812 12:54:22.608199       1 finisher.go:175] FinishRequest: post-timeout activity - time-elapsed: 52.630776167s, panicked: false, err: context deadline exceeded, panic-reason: <nil>
```

But it is normal when I test writing directly with etcdctl
```
cat schema.yaml | ./etcdctl --endpoints=https://[::1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/apiserver-etcd-client.crt --key=/etc/kubernetes/pki/apiserver-etcd-client.key put /test
```

### What did you expect to happen?

normal

### How can we reproduce it (as minimally and precisely as possible)?

Write large objects normally

### Kubernetes version

<details>

```console
✦ ➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:26:51Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

</details>


### Cloud provider

<details>

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Linux xxxxx 5.4.119-1-tlinux4-0009.3 #1 SMP Thu Apr 28 09:35:59 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
you can have more information if you add the `-v 9`flag

```
kubectl apply -v 9 -f schema.yaml
````

ipv6 here doesn´t seem to be relevant, does it?

**Comment by silenceper** [comment]
```
I0813 22:55:23.941525  755057 round_trippers.go:466] curl -v -XPOST  -H "Content-Type: application/json" -H "User-Agent: kubectl/v1.23.9 (linux/amd64) kubernetes/c1de2d7" -H "Accept: application/json" 'https://test.local:6443/apis/gateway.test.com/v1beta1/namespaces/default/gatewayinstances?fieldManager=kubectl-client-side-apply'




dssI0813 22:55:57.943377  755057 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 34001 ms Duration 34001 ms
I0813 22:55:57.943412  755057 round_trippers.go:577] Response Headers:
I0813 22:55:57.943421  755057 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: b6218b72-c493-4460-bbaf-d740149be793
I0813 22:55:57.943436  755057 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: edec1453-8b2f-42b3-a9fa-b83522233f1c
I0813 22:55:57.943448  755057 round_trippers.go:580]     Content-Length: 211
I0813 22:55:57.943466  755057 round_trippers.go:580]     Date: Sat, 13 Aug 2022 14:55:57 GMT
I0813 22:55:57.943478  755057 round_trippers.go:580]     Audit-Id: ea97d5b2-67ab-4b34-8f2a-4319276c1508
I0813 22:55:57.943486  755057 round_trippers.go:580]     Cache-Control: no-cache, private
I0813 22:55:57.943494  755057 round_trippers.go:580]     Content-Type: application/json
I0813 22:55:57.943535  755057 request.go:1181] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Timeout: request did not complete within requested timeout - context deadline exceeded","reason":"Timeout","details":{},"code":504}
I0813 22:55:57.943699  755057 helpers.go:219] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"schema.yaml\": Timeout: request did not complete within requested timeout - context deadline exceeded",
  "reason": "Timeout",
  "details": {},
  "code": 504
}]
F0813 22:55:57.943732  755057 helpers.go:118] Error from server (Timeout): error when creating "schema.yaml": Timeout: request did not complete within requested timeout - context deadline exceeded
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x3080040, 0x3, 0x0, 0xc000d3cbd0, 0x2, {0x25f3007, 0x10}, 0xc00006d800, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0xc000e2a140, 0x96, 0x0, {0x0, 0x0}, 0xc00130e4c8, {0xc00131c110, 0x1, 0x1})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:735 +0x1ae
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1518
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal({0xc000e2a140, 0x96}, 0xc0013143c0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:96 +0xc5
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr({0x1feb940, 0xc0013143c0}, 0x1e79828)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:191 +0x7d7
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:118
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/apply.NewCmdApply.func1(0xc000532780, {0xc0005fe4b0, 0x0, 0x3})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/apply/apply.go:190 +0xb1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000532780, {0xc0005fe480, 0x3, 0x3})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0006fca00)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.run(0xc0006fca00)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/cli/run.go:146 +0x325
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.RunNoErrOutput(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/cli/run.go:84
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:30 +0x1e

goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1181 +0x6a
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xfb

goroutine 20 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x1febc40, 0xc00054ec90}, 0x1, 0xc000114360)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x13b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x12a05f200, 0x0, 0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x28
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:179 +0x85

goroutine 29 [IO wait]:
internal/poll.runtime_pollWait(0x7f86a1323858, 0x72)
        /usr/local/go/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc000238500, 0xc000ce8000, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000238500, {0xc000ce8000, 0x4587, 0x4587})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000238500, {0xc000ce8000, 0xc000ce8066, 0xed})
        /usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00000e050, {0xc000ce8000, 0x64ecb9, 0xc0001137f0})
        /usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000f974d0, {0xc000ce8000, 0x0, 0x409e2d})
        /usr/local/go/src/crypto/tls/conn.go:778 +0x3d
bytes.(*Buffer).ReadFrom(0xc000378278, {0x1fe9a80, 0xc000f974d0})
        /usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000378000, {0x1fed460, 0xc00000e050}, 0x4526)
        /usr/local/go/src/crypto/tls/conn.go:800 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000378000, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:607 +0x112
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:575
crypto/tls.(*Conn).Read(0xc000378000, {0xc000228000, 0x1000, 0x8daa20})
        /usr/local/go/src/crypto/tls/conn.go:1278 +0x16f
bufio.(*Reader).Read(0xc00008bce0, {0xc000242820, 0x9, 0x8e89e2})
        /usr/local/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x1fe9880, 0xc00008bce0}, {0xc000242820, 0x9, 0x9}, 0x9)
        /usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader({0xc000242820, 0x9, 0xc001296720}, {0x1fe9880, 0xc00008bce0})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0002427e0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:498 +0x95
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000113f98)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:2101 +0x130
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc0000ac600)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1997 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:725 +0xac5
```

**Comment by silenceper** [comment]
I found this issue which seems to be the same as this issue https://github.com/kubernetes/kubernetes/issues/102749

**Comment by aojea** [comment]
> dssI0813 22:55:57.943377  755057 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 34001 ms Duration 34001 ms

it seems so, 34 seconds and timeout of the request

**Comment by liggitt** [comment]
can you verify it doesn't reproduce on master?

**Comment by fedebongio** [comment]
ccing the same people from https://github.com/kubernetes/kubernetes/issues/109099 since seems to be the same issue / fix (for visibility): @apelisse @jpbetz @cici37 @alexzielenski 
/triage accepted

**Comment by apelisse** [comment]
Hopefully it's the same yeah, especially since you're applying a schema. If you can't reproduce, the schema might be interesting to share. Thanks.

**Comment by aojea** [comment]
we should have a test to cover regressions, if we have the schema the test seems straightforward

**Comment by aojea** [comment]
@silenceper can you share the reproducer?

**Comment by silenceper** [comment]
CRD like this:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testinstances.gateway.test.com
spec:
  conversion:
    strategy: None
  group: gateway.test.com
  names:
    kind: TestInstance
    listKind: TestInstanceList
    plural: testinstances
    singular: testinstance
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: TestInstance is the Schema for the testinstances API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TestInstanceSpec defines the desired state of TestInstance
            properties:
              reportInterval:
                type: string
            type: object
          status:
            description: TestInstanceStatus defines the observed state of TestInstance
            properties:
              controlPlane:
                properties:
                  curConfigVersion:
                    type: string
                  discoveryPlugins:
                    items:
                      properties:
                        discoveryType:
                          type: string
                        message:
                          type: string
                        name:
                          type: string
                        readyUntil:
                          format: date-time
                          type: string
                        services:
                          items:
                            type: string
                          type: array
                        status:
                          type: string
                      type: object
                    type: array
                  effectiveConfigVersion:
                    type: string
                  message:
                    type: string
                  status:
                    type: integer
                type: object
              dataPlane:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                properties:
                  apisixVersion:
                    type: string
                  configCenter:
                    type: string
                  message:
                    type: string
                  pluginSchema:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                  status:
                    type: integer
                  type:
                    type: string
                type: object
              lastUpdateTime:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
```

when remove field`x-kubernetes-preserve-unknown-fields: true`, is normal
