### ISSUE TITLE
kubernetes.io/service-account-token doesn't update Service Account Secret

### ISSUE THREAD

**Issue by JJotah** [kubernetes/kubernetes#111871]
### What happened?

Now in the > 1.24 kubernetes version the creation of the service account is not creating automatically the secret. 
If you want to create new secret yo need to add something like this
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: NAMEOFSECRET
  annotations:
    kubernetes.io/service-account.name: NAMEOFSA
type: kubernetes.io/service-account-token
```
But when you want to retrieve service account secrets is not showing
```bash
NAME      SECRETS   AGE
default   0         13d
```
I want to contribute with this project (because I have more than 3 years working with k8s) 
I will check the controllers and maybe add new secret token in kubectl cmd to give the option to create the token from command line.

### What did you expect to happen?

I want to get secret and show the token assigned in the secret at namespace level

### How can we reproduce it (as minimally and precisely as possible)?

```bash
kubectl create sa devops
```
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: NAMEOFSECRET
  annotations:
    kubernetes.io/service-account.name: NAMEOFSA
type: kubernetes.io/service-account-token
```
```bash
kubectl apply -f devops.yaml
``````yaml
apiVersion: v1
kind: Secret
metadata:
  name: NAMEOFSECRET
  annotations:
    kubernetes.io/service-account.name: NAMEOFSA
type: kubernetes.io/service-account-token
```

```bash
kubectl get secret devops
```

### Anything else we need to know?

No

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", 
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", }

```

</details>

### Cloud provider

<details>
Hetzner
</details>

### OS version

<details>

Ubuntu 22

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
