### ISSUE TITLE
A PSP is wrongly respecting "extensions/podsecuritypolicies/use" for admission

### ISSUE THREAD

**Issue by eugenenuke** [kubernetes/kubernetes#111913]
### What happened?

A pod is getting admitted from a user which has no policy/podsecuritypolicies/use permission, here is the defined rule in the user's role/rolebinding (see that the apiGroups is `extensions`, not `policy`):

```
- apiGroups:
  - ""
  resources:
  - 'pods'
  verbs:
  - 'create'
- apiGroups:
  - extensions
  resources:
  - 'podsecuritypolicies'
  verbs:
  - 'use'
```

### What did you expect to happen?

The pod isn't admitted by the apiserver

### How can we reproduce it (as minimally and precisely as possible)?

Create a PSP:

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: example
spec:
  privileged: false  # Don't allow privileged pods!
  # The rest fills in some required fields.
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
```

Create a role/clusterrole with the only rule:
```
- apiGroups:
  - ""
  resources:
  - 'pods'
  verbs:
  - 'create'
- apiGroups:
  - extensions
  resources:
  - 'podsecuritypolicies'
  verbs:
  - 'use'
```

Bind this role to your user that has no other roles.
Create a pod: `k run pod --image nginx`

### Anything else we need to know?

I suspect that apiserver still has some checks for the deprecated "extensions/podsecuritypolicies/use", after it was moved to `policy` group: https://github.com/kubernetes/kubernetes/pull/61608

### Kubernetes version

Tested on 1.21, 1.22, 1.23

### Cloud provider

GCP/GKE

### OS version

COS / Shouldn't be important

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

Containerd / Shouldn't be important

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
