### ISSUE TITLE
Add recording of Events in audit log for security reasons

### ISSUE THREAD

**Issue by hi120ki** [kubernetes/kubernetes#112117]
Events collect traces of attacks that are not recorded in default audit logs, such as creating cronjobs for attack persistence.

Attackers may delete events to erase the traces of attacks and make it harder to trace, as featured in the [Threat matrix for Kubernetes](https://www.microsoft.com/security/blog/2021/03/23/secure-containerized-environments-with-updated-threat-matrix-for-kubernetes/).

However, the current audit log does not record the events due to the performance impact.

For security reasons, "delete" events and possibly "update" and "patch" should be logged.

The current audit log's policy is created [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L1199-L1203), and I suggest modify code like this

```yaml
  - level: Request
    verbs: ["delete","update","patch"]
    resources:
      - group: "" # core
        resources: ["events"]
    omitStages:
      - "RequestReceived"
```

I'm waiting for your comments on adding logging of events to the audit log and my proposed changes.

(I would appreciate it if I could create a Pull Request.)

Thank you.
