### ISSUE TITLE
kube-proxy IPVS - Uncertain behavior on NodePort Entries

### ISSUE THREAD

**Issue by harshanarayana** [kubernetes/kubernetes#112185]
### What happened?

I have a `v1.24.1` based Single Node cluster running (Control Plane taking the workload as well). And the `kube-proxy` is running in IPVS mode. 

I am noticing a very odd behavior in terms of the entries under the `ipvsadm` that I am not able to point to a failure point. This behavior is causing the Node Port to be not reachable from outside. 

```bash
root@tardis-control-121-0-10-61:~# stern -n kube-system kube-proxy | egrep -A2 "Adding new service.*-kong-frontend.*:443.*"
+ kube-system kube-proxy-mzfhn › kube-proxy
kube-system kube-proxy-mzfhn kube-proxy I0901 04:59:52.225484       7 service.go:437] "Adding new service port" portName="tardis-ingress/tardis-kong-frontend:https" servicePort="10.26.188.146:443/TCP"
kube-system kube-proxy-mzfhn kube-proxy I0901 04:59:52.225864       7 proxier.go:1042] "Syncing ipvs proxier rules"
kube-system kube-proxy-mzfhn kube-proxy I0901 04:59:52.225887       7 iptables.go:358] running iptables-save [-t filter]
--
kube-system kube-proxy-mzfhn kube-proxy I0901 04:59:54.719024       7 proxier.go:1926] "Adding new service" serviceName="tardis-ingress/tardis-kong-frontend:https" virtualServer="10.26.188.146:443/TCP"
kube-system kube-proxy-mzfhn kube-proxy I0901 04:59:54.719066       7 proxier.go:1950] "Bind address" address="10.26.188.146"
kube-system kube-proxy-mzfhn kube-proxy I0901 04:59:54.719598       7 proxier.go:1926] "Adding new service" serviceName="tardis-ingress/tardis-kong-frontend:https" virtualServer="172.20.55.61:443/TCP"
kube-system kube-proxy-mzfhn kube-proxy I0901 04:59:54.719742       7 proxier.go:1926] "Adding new service" serviceName="tardis-ingress/tardis-kong-frontend:https" virtualServer="121.0.10.61:443/TCP"
kube-system kube-proxy-mzfhn kube-proxy I0901 04:59:54.720249       7 proxier.go:1926] "Adding new service" serviceName="tardis-ingress/tardis-kong-frontend:https" virtualServer="10.78.177.0:443/TCP"
kube-system kube-proxy-mzfhn kube-proxy I0901 04:59:54.720386       7 proxier.go:1926] "Adding new service" serviceName="tardis-ingress/tardis-kong-frontend:https" virtualServer="169.254.20.10:443/TCP"
```

The above snipper is from the `kube-proxy`. As you can see, the `:443` port is opened as a `NodePort` entry. According to the `kube-proxy` logs, the Virtual Service is being added to 4 entities in total. 

1. 172.20.55.61 -> Routable IP
2. 121.0.10.61 -> Node IP
3. 10.78.177.0 -> Calico `tunl0`
4. 169.254.20.10 -> Local DNS dummy interface (we create a dummy interface and attach a fixed IP to that and use that for local DNS Resolution)

However, when I check the `ipvsadm` output, I notice the following

```bash
root@tardis-control-121-0-10-61:~# ipvsadm -Ln -t 172.20.55.61:443
Memory allocation problem

root@tardis-control-121-0-10-61:~# ipvsadm -Ln -t 121.0.10.61:443
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  121.0.10.61:443 lc
  -> 10.78.177.133:8443           Masq    1      2          26

root@tardis-control-121-0-10-61:~# ipvsadm -Ln -t 10.78.177.0:443
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.78.177.0:443 lc
  -> 10.78.177.133:8443           Masq    1      0          0

root@tardis-control-121-0-10-61:~# ipvsadm -Ln -t 169.254.20.10:443
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  169.254.20.10:443 lc
  -> 10.78.177.133:8443           Masq    1      0          0
```

As you can see from the above, the entry for node port related service is missing for the routable IP `172.20.55.61`

Which causes all `https://172.20.55.61:443` to be connection refused. 

The Interface for which that IP is assigned to is NIC Bond enabled as following

```bash
root@tardis-control-121-0-10-61:~# ip l show bond-1
4: bond-1: <BROADCAST,MULTICAST,control,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:50:56:93:7b:cb brd ff:ff:ff:ff:ff:ff

root@tardis-control-121-0-10-61:~# ip a show bond-1
4: bond-1: <BROADCAST,MULTICAST,control,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:50:56:93:7b:cb brd ff:ff:ff:ff:ff:ff
    inet 172.20.55.61/24 brd 172.20.55.255 scope global bond-1
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe93:7bcb/64 scope link
       valid_lft forever preferred_lft forever

root@tardis-control-121-0-10-61:~# ip a show ens160
2: ens160: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq control bond-1 state UP group default qlen 1000
    link/ether 00:50:56:93:7b:cb brd ff:ff:ff:ff:ff:ff

root@tardis-control-121-0-10-61:~# ip l show ens160
2: ens160: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq control bond-1 state UP mode DEFAULT group default qlen 1000
    link/ether 00:50:56:93:7b:cb brd ff:ff:ff:ff:ff:ff 
```

The `kube-proxy` Configuration looks as following

```yaml
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
bindAddressHardFail: false
clientConnection:
  acceptContentTypes: application/json
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
  qps: 5
clusterCIDR: 10.78.0.0/16
configSyncPeriod: 15m0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
detectLocal:
  bridgeInterface: ""
  interfaceNamePrefix: ""
detectLocalMode: ""
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 0s
  syncPeriod: 0s
ipvs:
  excludeCIDRs: []
  minSyncPeriod: 1s
  scheduler: lc
  strictARP: false
  syncPeriod: 3s
  tcpFinTimeout: 2m0s
  tcpTimeout: 2h0m0s
  udpTimeout: 5m0s
kind: KubeProxyConfiguration
metricsBindAddress: 127.0.0.1:10249
mode: ipvs
nodePortAddresses: []
oomScoreAdj: -999
portRange: ""
showHiddenMetricsForVersion: ""
udpIdleTimeout: 0s
winkernel:
  enableDSR: false
  forwardHealthCheckVip: false
  networkName: ""
  rootHnsEndpointName: ""
  sourceVip: ""
```

### What did you expect to happen?

Virtual Service to be created on all applicable Interfaces detected on the system

### How can we reproduce it (as minimally and precisely as possible)?

I have two cluster in that state and haven't been able to find a way to reproduce this at will.  Both cluster match the configuration in a similar manner. 

### Anything else we need to know?

I have tries the following workaround trying to recover the cluster with no success. 

1. Delete the `kube-proxy` and let is re-sync the rules to see if it will create it back
2. `ipvsadm -D -t <svc:port>` and remove all the Virtual Services for the `:443` and restart `kube-proxy` to recreate the entire chain

In both the above cases the system gets back into the same mode. 

However, I have another cluster matching the configuration in an exact same manner and I am not seeing any issue with this behavior on that cluster. 

> THIS IS RUNNING A CUSTOMIZED VERSION OF K8S BASED ON v1.24.1 (Changes have been made into API Server to add a few additional Admission Controllers and a few changes on kubelet and kubeadm)

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.1-cisco", GitCommit:"91ebbb9c1d35c8e3f4c4e933f00aea2033af86c5", GitTreeState:"clean", BuildDate:"2022-07-26T17:30:05Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.1-cisco", GitCommit:"91ebbb9c1d35c8e3f4c4e933f00aea2033af86c5", GitTreeState:"clean", BuildDate:"2022-07-26T17:35:55Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


$ uname -a
Linux tardis-control-121-0-10-61 5.4.0-122-generic #138~18.04.1 SMP Sun Jul 3 05:55:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
Containerd

```console
$ containerd --version
containerd containerd.io 1.6.6 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

```console
$ calicoctl version
Client Version:    v3.21.2.cisco
Git commit:        58767c5b8
Cluster Version:   v3.21.2.cisco
Cluster Type:      k8s,bgp,kubeadm,kdd
```
</details>
