### ISSUE TITLE
`--container-log-max-files` and `--container-log-max-size` do not work as expected on Windows

### ISSUE THREAD

**Issue by AbelHu** [kubernetes/kubernetes#112114]
### What happened?

When setting "--container-log-max-files=5" and "--container-log-max-size=9Mi", we only can find two log files for the test container and the file size of one log file exceeds the max size.
```
C:\var\log\pods\default_win-logs-vtlfq_b8fec92f-bedd-42ad-8d3f-ee0718e71581\win-logs


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        8/30/2022   3:14 AM       59131151 5.log
-a----        8/30/2022   2:58 AM        9537899 5.log.20220830-025805
```

Test Windows Pod spec:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: win-logs
  labels:
    app: win-logs
spec:
  selector:
    matchLabels:
      app: win-logs
  template:
    metadata:
      labels:
        app: win-logs
    spec:
      containers:
      - name: win-logs
        image: mcr.microsoft.com/windows/servercore:1809
        args:
        - powershell.exe
        - -Command
        - "for ($i = 0; ; $i+=1) { Write-Host \"$i - $(date) : Generate much logs...\" }"
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: windows

```

### What did you expect to happen?

1. The count of log files does not exceed `--container-log-max-files`
2. The file size of all log files does not exceed `--container-log-max-size`

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an AKS cluster with k8s 1.23.8
2. Add a Windows agent pool with one node
3. Update `C:\k\kubeclusterconfig.json` to add "--container-log-max-files=5" and "--container-log-max-size=9Mi" under `Kubernetes.Kubelet.ConfigArgs` in the Windows node
4. Deploy the test Windows pod and wait for several minutes
5. Check the log files in the folder `C:\var\log\pods\default_win-logs-XXX\win-logs` in the Windows node

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a35ccc8395e8a5eaa83b7b8c981677893b651cba", GitTreeState:"clean", BuildDate:"2022-07-28T20:52:46Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here

```
aksnpwin000000                   Ready    agent   21h   v1.23.8   x.x.x.x   <none>        Windows Server 2019 Datacenter   10.0.17763.3287    containerd://1.6.6+azure
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.6+azure
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
