### ISSUE TITLE
Static CPU Manager can fail with UnexpectedAdmissionError with init-containers requesting integer CPUs

### ISSUE THREAD

**Issue by bpineau** [kubernetes/kubernetes#112228]
### What happened?

The static CPU manager can reserves full CPU cores for (Guaranteed, integer CPU) pods' init containers.

It supports re-using those reserved CPU cores for main containers, but doesn't enforce (or even favour) their re-use, which can lead to CPU core(s) being left reserved to an init-container while the main container uses a different CPU set.

The example deployment provided below can lead to a topology like this:
```
$ jq . /var/lib/kubelet/cpu_manager_state
{
  "policyName": "static",
  "defaultCpuSet": "0",
  "entries": {
    "3ba83abb-7ceb-45dc-96ec-556fe1640954": {
      "init": "4",              # reserved yet not reused (not in "1,5"), ie. leaked CPU
      "main": "1,5"
    },
    "f2ee3f83-3839-4d19-aa2d-f1b0775b18ca": {
      "init": "2",
      "main": "2,6"
    },
    "f8436276-f7e3-4b90-8824-ccef1313df16": {
      "init": "3",
      "main": "3,7"
    }
  },
  "checksum": 3949393128
}
```

Then Kubelet and the Kubernetes Scheduler will disagree on the remaining resources for that node.

Pods might get scheduled to that node then rejected with an `UnexpectedAdmissionError` (`Pod Allocate failed due to not enough cpus available to satisfy request, which is unexpected`).

### What did you expect to happen?

Static CPU Manager only reserving at most `max(sum_containers_requests, max(among init containers requests))` (as expected by the scheduler), allowing future scheduled pods to start.

### How can we reproduce it (as minimally and precisely as possible)?

Update the deployment's `nodeSelector` below to target a node with `cpuManagerPolicy: static`; then look at `/var/lib/kubelet/cpu_manager_state` and look for leaked "init" CPU cores (or schedule more pods on that node, and see them rejected with `UnexpectedAdmissionError`).

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tdeploy
  name: tdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tdeploy

  template:
    metadata:
      labels:
        app: tdeploy

    spec:
      nodeSelector:
        kubernetes.io/hostname: TEST-NODE-NAME-GOES-HERE

      initContainers:
      - name: init
        image: kubernetes/pause:go

        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi

      containers:
      - name: main
        image: kubernetes/pause:go

        resources:
          limits:
            cpu: 2
            memory: 1Gi
          requests:
            cpu: 2
            memory: 1Gi
```

### Kubernetes version

<details>

```console
$ kubectl version  # also tested with a 1.25 kubelet
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-dd.1", GitCommit:"d9705166e190927de148edae148bf46471c7f8d5", GitTreeState:"clean", BuildDate:"2022-03-07T11:53:47Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Any (irrelevant)
</details>

### OS version

<details>
Any (Linux)
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Tested and reproduced with Containerd 1.5.4 and 1.6.8.
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by fromanirh** [comment]
this is https://github.com/kubernetes/kubernetes/issues/94220 from another angle, but the root cause is pretty much the same. I think we should *not* close this issue because of the linked PR. The workaround for this issue is in https://github.com/kubernetes/kubernetes/issues/94220#issuecomment-1050004800

**Comment by qiutongs** [comment]
We saw a customer met the exact same issue. I suggested the workaround for them.

**Comment by qiutongs** [comment]
The workaround didn't work for my customer. They have some setting like below in Pod spec: 2 init containers 1 app containr.

```
Init Containers:
  init1:
    Limits:
      cpu:                            11
    Requests:
      cpu:                            11
  init2:
    Limits:
      cpu:                            11
    Requests:
      cpu:                            11
Containers:
  app:
    Limits:
      cpu:                            11
    Requests:
      cpu:                            11
```

This results in a weird cpu manager state:

```
{
   "policyName":"static",
   "defaultCpuSet":"0",
   "entries":{
      "5ea6856d-a833-4c93-97b4-66165521af39":{
         "app":"1,36-40,84-88",
         "init1":"1,36-40,84-88",
         "init2":"1-6,49-53"
      },
      "83a51fe7-151e-4989-b728-f7cbe23ed591":{
         "app":"12-17,60-64",
         "init1":"12-14,30,46-47,60-62,94-95",
         "init2":"12-14,30,46-47,60-62,94-95"
      },
      "a879d991-c4e6-4ff2-91d8-d456b27c6d5b":{
         "app":"7-11,54-59",
         "init1":"41-45,54,89-93",
         "node-health-init2":"7-11,54-59"
      }
   },
}
```

**Comment by fromanirh** [comment]
1.21 is too old and no longer supported. I'm inclined to propose a fix, considering it reportedly reproduces also on 1.25 (https://github.com/kubernetes/kubernetes/issues/112228#issue-1361226861)

**Comment by qiutongs** [comment]
Yeah, we don't need the fix to be backported to 1.21. We need some working workaround for the case https://github.com/kubernetes/kubernetes/issues/112228#issuecomment-1352405569.

**Comment by fromanirh** [comment]
> The workaround didn't work for my customer. They have some setting like below in Pod spec: 2 init containers 1 app containr.
> 
> ```
> Init Containers:
>   init1:
>     Limits:
>       cpu:                            11
>     Requests:
>       cpu:                            11
>   init2:
>     Limits:
>       cpu:                            11
>     Requests:
>       cpu:                            11
> Containers:
>   app:
>     Limits:
>       cpu:                            11
>     Requests:
>       cpu:                            11
> ```
> 
> This results in a weird cpu manager state:
> 
> ```
> {
>    "policyName":"static",
>    "defaultCpuSet":"0",
>    "entries":{
>       "5ea6856d-a833-4c93-97b4-66165521af39":{
>          "app":"1,36-40,84-88",
>          "init1":"1,36-40,84-88",
>          "init2":"1-6,49-53"
>       },
>       "83a51fe7-151e-4989-b728-f7cbe23ed591":{
>          "app":"12-17,60-64",
>          "init1":"12-14,30,46-47,60-62,94-95",
>          "init2":"12-14,30,46-47,60-62,94-95"
>       },
>       "a879d991-c4e6-4ff2-91d8-d456b27c6d5b":{
>          "app":"7-11,54-59",
>          "init1":"41-45,54,89-93",
>          "init2":"7-11,54-59"
>       }
>    },
> }
> ```

Hi, could you please provide a pod spec (and possibly the related node topology) which makes this issue likely to happen?
I'm looking for good reproducers, ideally more than one, to have good test coverage before to send any code changes.
I'll work myself on reproducers meantime.

**Comment by qiutongs** [comment]
Hi, I couldn't reproduce it in my local environment actually. With below pod spec, the reserved CPUs are always the same for init and app containers. My reproduction was on a new node without any user pods.

The problem happed in https://github.com/kubernetes/kubernetes/issues/112228#issuecomment-1352405569 were on an exiting nodes where there are already some users pods which leaked CPUs. I speculate there is something related to that.

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  initContainers:
  - name: init1
    image: kubernetes/pause:go
    resources:
      limits:
        cpu: 2
        memory: 1Gi
      requests:
        cpu: 2
        memory: 1Gi
  - name: init2
    image: kubernetes/pause:go
    resources:
      limits:
        cpu: 2
        memory: 1Gi
      requests:
        cpu: 2
        memory: 1Gi
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 2
        memory: 1Gi
      limits:
        cpu: 2
        memory: 1Gi
```

**Comment by qiutongs** [comment]
I also found another workaround which is setting the cpu request/limit of init container to **non-integer**. This can make cpu manager "skip" the init containers.

Examples are:

```
resources:
      limits:
        cpu: 100m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 1Gi
```

```
resources:
      limits:
        cpu: 1.1
        memory: 1Gi
      requests:
        cpu: 1.1
        memory: 1Gi
```

**Comment by 0Bumblebee** [comment]
The initContainer does not need to be tied to the core and can avoid leaks.
```
initContainers:
  - name: init
    image: nginx
    resources:
      requests:
        cpu: "0.1"
        memory: "10Mi"
      limits:
        cpu: "0.1"
        memory: "10Mi"
  containers:
  - name: main
    image: nginx
    resources:
      requests:
        cpu: "1"
        memory: "10Mi"
      limits:
        cpu: "1"
        memory: "10Mi"
```

@bpineau

**Comment by SergeyKanzhelev** [comment]
/assign @esotsal 

there might have been improvements in this area. @esotsal will triage after trying to repro again

**Comment by pravk03** [comment]
I wasn't able to reproduce this on 1.33. The init containers CPU assignments were being reused. 

```
root@133-worker:/# kubelet --version
Kubernetes v1.33.0
```

Pod Spec: 
```
apiVersion: v1
kind: Pod
metadata:
  name: guaranteedpod
spec:
  nodeName: 133-worker
  initContainers:
  - name: init1
    image: busybox:latest
    command: ['sh', '-c', 'echo Init1 running for 10s...; for i in $(seq 1 10); do echo "Init1: $i/10"; sleep 1; done; echo Init1 completed.']
    resources:
      limits:
        cpu: "11"
        memory: "256Mi"
      requests:
        cpu: "11"
        memory: "256Mi"
  - name: init2
    image: busybox:latest
    command: ['sh', '-c', 'echo Init2 running for 10s...; for i in $(seq 1 10); do echo "Init2: $i/10"; sleep 1; done; echo Init2 completed.']
    resources:
      limits:
        cpu: "11"
        memory: "256Mi"
      requests:
        cpu: "11"
        memory: "256Mi"
  containers:
  - name: app
    image: busybox:latest
    command: ['sh', '-c', 'echo App container running indefinitely...; trap "echo App stopping; exit 0" SIGINT SIGTERM; while true; do echo "App alive at $(date)"; sleep 30; done']
    resources:
      limits:
        cpu: "11"
        memory: "512Mi"
      requests:
        cpu: "11"
        memory: "512Mi"
```

Relevant Kubelet logs:
```
May 05 18:42:25 133-worker kubelet[2200]: I0505 18:42:25.669881    2200 state_mem.go:80] "Updated desired CPUSet" podUID="9858a960-9044-4842-9a66-46d6649912a4" containerName="init1" cpuSet="1-5,30-35"
May 05 18:42:36 133-worker kubelet[2200]: I0505 18:42:36.282012    2200 state_mem.go:80] "Updated desired CPUSet" podUID="9858a960-9044-4842-9a66-46d6649912a4" containerName="init2" cpuSet="1-5,30-35"
May 05 18:42:36 133-worker kubelet[2200]: I0505 18:42:36.282048    2200 policy_static.go:257] "RemoveContainer" podUID="9858a960-9044-4842-9a66-46d6649912a4" containerName="init1"
May 05 18:42:47 133-worker kubelet[2200]: I0505 18:42:47.304496    2200 state_mem.go:80] "Updated desired CPUSet" podUID="9858a960-9044-4842-9a66-46d6649912a4" containerName="app" cpuSet="1-5,30-35"
May 05 18:42:47 133-worker kubelet[2200]: I0505 18:42:47.304524    2200 policy_static.go:257] "RemoveContainer" podUID="9858a960-9044-4842-9a66-46d6649912a4" containerName="init2"
```

CPU State:
```
root@133-worker:/# cat /var/lib/kubelet/cpu_manager_state | jq .
{
  "policyName": "static",
  "defaultCpuSet": "0,6-29,36-59",
  "entries": {
    "9858a960-9044-4842-9a66-46d6649912a4": {
      "app": "1-5,30-35",
      "init1": "1-5,30-35",
      "init2": "1-5,30-35"
    }
  },
  "checksum": 2947708340
}
```

**Comment by pravk03** [comment]
I was able to reliable reproduce this by adding `reservedSystemCPUs: "0"` in kubelet config . 

pod spec:

```
apiVersion: v1
kind: Pod
metadata:
  name: guaranteedpod
spec:
  nodeName: 133-worker2
  initContainers:
  - name: init1
    image: busybox:latest
    command: ['sh', '-c', 'echo Init1 running for 10s...; for i in $(seq 1 10); do echo "Init1: $i/10"; sleep 1; done; echo Init1 completed.']
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
      requests:
        cpu: "1"
        memory: "256Mi"
  containers:
  - name: app
    image: busybox:latest
    command: ['sh', '-c', 'echo App container running indefinitely...; trap "echo App stopping; exit 0" SIGINT SIGTERM; while true; do echo "App alive at $(date)"; sleep 30; done']
    resources:
      limits:
        cpu: "2"
        memory: "512Mi"
      requests:
        cpu: "2"
        memory: "512Mi"
``` 

* CPU assigned to init1 container (30) is not assigned to app container and also not a part of defaultCpuSet. 

```
cat /var/lib/kubelet/cpu_manager_state | jq .
{
  "policyName": "static",
  "defaultCpuSet": "0,2-29,32-59",
  "entries": {
    "fdc9199f-64d6-4300-8ed1-e6b11f02c824": {
      "app": "1,31",
      "init1": "30"
    }
  },
  "checksum": 67685122
}
```

* Topology of the node 

```
root@133-worker2:/# lscpu | grep NUMA
NUMA node(s):                         2
NUMA node0 CPU(s):                    0-14,30-44
NUMA node1 CPU(s):                    15-29,45-59
```

My hypothesis of what could be happening:

1. CPU 0 is reserved by kubelet. 
2. The init container init1 requests 1 cpu and gets cpu sibling of CPU 30 (which is a sibling cpu of CPU 0)
3. When app container requests 2 CPU's, it likely prefers 2 SMT cores of a single CPU (1, 31) instead of CPU 30. 
4. CPU 30 is removed from reserved but not added to default pool.

There might be a bug in [allocateCores()](https://github.com/kubernetes/kubernetes/blob/4c0233b95c29cbae515fd3b92db1897062c4dd1a/pkg/kubelet/cm/cpumanager/policy_static.go#L426) function. The `reusableCPUs` needs to added back to `defaultCPUSet` if its not used by the actual allocation.
