### ISSUE TITLE
Total amount of ephemeral-storage in namespace is not limited/tracked properly

### ISSUE THREAD

**Issue by YuikoTakada** [kubernetes/kubernetes#112310]
### What happened?

In ResourceQuota's doc( https://kubernetes.io/docs/concepts/policy/resource-quotas/ )m written as:

- A resource quota, defined by a ResourceQuota object, provides constraints that limit aggregate resource consumption per namespace. It can limit the quantity of objects that can be created in a namespace by type, as well as the total amount of compute resources that may be consumed by resources in that namespace.
- Users create resources (pods, services, etc.) in the namespace, and the quota system tracks usage to ensure it does not exceed hard resource limits defined in a ResourceQuota.

But actually, total amount of ephemeral-storage in namespace is not limited/tracked properly.
Because, we can create pods which don't have limit.ephemeral-storage.
When I don't set limits.cpu/memory in pod and limits.cpu/memory is set in ResourceQuota, I get the following error.
```
Warning FailedCreate 2s (x4 over 20s) replicaset-controller (combined from similar events): Error creating: pods "test-668668fc76-4rm6p" is forbidden: failed quota: pj-quota: must specify limits.cpu
```
But when I don't set limits.ephemeral-storage in pod and limits.ephemeral-storage is set in ResourceQuota, this error doesn't occur.
And so, I cannot limit/track total amount of ephemeral-storage in namespace properly.

The reason of this behavior is written in https://github.com/kubernetes/kubernetes/blob/51ea7b21699ffc8857a7da9f2b1b4f293bf70a69/pkg/quota/v1/evaluator/core/pods.go#L121
```
	// BACKWARD COMPATIBILITY REQUIREMENT: if we quota cpu or memory, then each container
	// must make an explicit request for the resource.  this was a mistake.  it coupled
	// validation with resource counting, but we did this before QoS was even defined.
	// let's not make that mistake again with other resources now that QoS is defined.
```
Actually, we can limit usage of ephemeral-storage by using LimitRange, but I am confused by the different between documents and behavior.

My question:
* We cannot know total amount of ephemeral-storage. Is this correct behavior? Is there no use case for "limit/track the total amount of ephemeral-storage that may be consumed by resources in that namespace"?
* Document is incorrect? Should we remove the sentence "ResourceQuota can limit the total amount of compute resources that may be consumed by resources in that namespace"? 

### What did you expect to happen?

Fix document properly
or 
Make deprecated ResourceQuota feature if there is no use case

### How can we reproduce it (as minimally and precisely as possible)?

When I don't set limits.cpu/memory in pod like below:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: redis
          image: redis:latest
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secret-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: test-secret
```
and limits.cpu/memory is set in ResourceQuota like below, 
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
spec:
  hard:
   limits.cpu: "1.5"
   limits.memory: 2Gi
   requests.cpu: "0.6"
   requests.memory: 800Mi
   pods: "2"
```
I get the following error.
```
Events:
  Type     Reason        Age                 From                   Message
  ----     ------        ----                ----                   -------
  Warning  FailedCreate  4m6s                replicaset-controller  Error creating: pods "test-deployment-7ff6449445-cwp2s" is forbidden: failed quota: resource-quota: must specify limits.cpu for: redis; limits.memory for: redis; requests.cpu for: redis; requests.memory for: redis
```
But when I don't set limits.ephemeral-storage in pod and limits.ephemeral-storage is set in ResourceQuota, this error doesn't occur.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-beta.0.113+7380fc735aca59-dirty", GitCommit:"7380fc735aca591325ae1fabf8dab194b40367de", GitTreeState:"dirty", BuildDate:"2022-04-28T04:20:32Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.24) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
