### ISSUE TITLE
kubeadm incorrectly fails on /80 IPv6 network

### ISSUE THREAD

**Issue by telmich** [kubernetes/kubernetes#112367]
### What happened?

Trying to bootstrap a cluster using the following configuration file fails:

```
# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.25.0
networking:
  dnsDomain: k8s.ge.nau.so
  podSubnet: 2a0a:e5c0:13:aaaa::/80
  serviceSubnet: 2a0a:e5c0:13:bbbb::/108
controlPlaneEndpoint: "k8s-api.ge.nau.so:6443"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: cgroupfs
```

### What did you expect to happen?

kubeadm to use the /80 network

### How can we reproduce it (as minimally and precisely as possible)?

Use:

```
kubeadm init --config kubeadm.yaml --upload-certs
```

### Anything else we need to know?

From an operator point of view kubeadm should allow any sized pod or service subnet.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"archive", BuildDate:"2022-09-08T12:47:18Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

Any

### Install tools

Any

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by n4j** [comment]
@telmich Can you please provide logs from the kubeadm?Ffrom start to up until the point it fails to boostrap?

**Comment by neolit123** [comment]
/sig network
@aojea /80 is too big if I recall and we don't have the bitmap-like allocator yet?
@telmich are you getting podnet  validation warnings in kubeadm or other component logs?

**Comment by neolit123** [comment]
/kind support
this is a support ticket.. what we can do is improve docs / cli output.

**Comment by aojea** [comment]
> @aojea /80 is too big if I recall and we don't have the bitmap-like allocator yet?

that restriction of >112 is for Service

for pods the limitation is between `podSubnet` mask size and `node-mask-cidr-size-ipv6`, that by default is 64. The node-mask-size-cidr subdivides the podSubnet to assign subnets to the nodes, so the limit is podSubnet

If you want to use podSubnet /80 you need to set --node-mask-cidr-size-ipv6 to something greater than 80, i.e. 96


See https://github.com/kubernetes/kubernetes/issues/111425#issuecomment-1195076050 and https://github.com/kubernetes/kubernetes/pull/95723

**Comment by telmich** [comment]
The log from trying to use kubeadm when trying to use a /80:

```
blind:/home/nico/vcs/k8s-config/bootstrap/server120-server121# kubeadm  init --config kubeadm-t
est.yaml 
podSubnet: Invalid value: "2a0a:e5c0:32:10::/80": the size of pod subnet with mask 80 is smaller than the size of node subnet with mask 64
To see the stack trace of this error execute with --v=5 or higher
blind:/home/nico/vcs/k8s-config/bootstrap/server120-server121# cat kubeadm-test.yaml 
# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.25.0
networking:
  dnsDomain: server121.k8s.ooo
  podSubnet: 2a0a:e5c0:32:10::/80
  serviceSubnet: 2a0a:e5c0:32:11::/108
apiServer:
  extraArgs:
    service-node-port-range: 53-55000
controlPlaneEndpoint: "server121-api.k8s.ooo:6443"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: cgroupfs
blind:/home/nico/vcs/k8s-config/bootstrap/server120-server121# 
```

Note that even if this was related to the node subnets, the error message would be at least misleading.
