### ISSUE TITLE
Deployment fails to spawn new replicas after getting updated if one of nodes is `NotReady` (Multi-node setup)

### ISSUE THREAD

**Issue by mariusz-okulanis-dd** [kubernetes/kubernetes#112452]
### What happened?

In a multi-node setup, when one of nodes fails (has `NotReady` status) deployment (with 1 replica) will recreate pod on healthy node. If after that admin will try to modify this deployment (e.g. using `kubectl set env`) the healthy pod will get terminated and no new pod will be spawned. This happens only to deployments having `.spec.strategy.type==Recreate`.

### What did you expect to happen?

After updating deployment new pod should get spawned to fulfill `replicas` requirement.

### How can we reproduce it (as minimally and precisely as possible)?

Setup: multi-node (e.g. 3 nodes), ([also tested with minikube](https://github.com/kubernetes/kubernetes/issues/112452#issuecomment-1248129749))
Sample deployment - key aspect of the issue is having `.spec.strategy.type==Recreate`:
```
# test_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

1. Create deployment (using above snippet): `kubectl apply -f test_deployment.yaml`.
2. Wait until created pod reaches `Running` status.
3. Disable node where pod was spawned (e.g. `poweroff` command).
4. Wait until new pod gets spawned at another node and reaches `Running` status. Old pod should be stuck with `Terminating` status.
5. Perform a deployment update: `kubectl set env deployment/nginx-deployment TEST_VAR=1` (variable name and value does not matter).
6. As a result pod created at step 4 gets terminated and no new pod is created (thus failing to have `replicas == 1`).

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EC2
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:37:17 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico==3.19.4
</details>
