### ISSUE TITLE
Unable to access application using "service" name of kubernetes when using "hostNetwork"

### ISSUE THREAD

**Issue by Rajpratik71** [kubernetes/kubernetes#112481]
### What happened?

Unable to access application using "service" name of kubernetes when using "hostNetwork" in Pod Spec.

### What did you expect to happen?

I should able to access the application using "service" name of kubernetes

### How can we reproduce it (as minimally and precisely as possible)?

Deploy the application using below spec

<details>
`
apiVersion: v1
kind: Pod
metadata:
  name: influxdb
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: influxdb
      image: influxdb
      ports:
        - containerPort: 8086
          hostPort: 8086
---
kind: Service
apiVersion: v1
metadata:
  name: influxdb
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    name: influxdb
`
</details>

Or Use the spec from https://gist.github.com/Rajpratik71/d624f1ad0fa367098203830704ddbad1

then,

check the service name
`
kubectl get svc
`
and check the pod ip
`
kubectl get po -o wide
`
then , try to access the application using service name and Pod IP respectively from same pod or other pod.

with Pod IP application will be accessible but with service name it is saying connection refused

## With Pod IP

`
➜  ~ kubectl exec -it influxdb -- bash
root@kind-control-plane:/# 
root@kind-control-plane:/# curl -v 172.20.0.2:8086/ping
`

## With Service Name
`
➜  ~ kubectl exec -it influxdb -- bash
root@kind-control-plane:/# 
root@kind-control-plane:/# curl -v influxdb:8086/ping
curl: (7) Failed to connect to influxdb port 8086: Connection refused
root@kind-control-plane:/# 
`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-09-01T23:30:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux workplace-Latitude-5420 5.14.0-1051-oem #58-Ubuntu SMP Fri Aug 26 05:50:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

kind cli

</details>

### Container runtime (CRI) and version (if applicable)

<details>

containerd://1.6.7

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

kindnet

Even faced the same with Calico

</details>

**Comment by aojea** [comment]
/sig network

we don't have good coverage, so someone should be able to repro to confirm it

**Comment by Rajpratik71** [comment]
> /sig network
> 
> we don't have good coverage, so someone should be able to repro with an e2e to confirm it ... we do run KIND on ci

@aojea  Same issue is obeserved in cluster created using "kubeadm".

**Comment by aojea** [comment]
> @aojea Same issue is obeserved in cluster created using "kubeadm".

yeah, I tried to mean to reproduce the problem and explain the exact problem:
-  what is the `resolv.conf` inside the hostNetwork pod? it should the the cluster Service for dns
-  you can access the podIP, can you access the ClusterIP of the Service?
- ...

**Comment by aojea** [comment]
@Rajpratik71 I can't reproduce it, Services seems to resolve well to me on hotsNetwork pods with `ClusterFirstWithHostNet`, what happens if you do

```
curl -kv https://kubernetes.default
```

inside the pod?

**Comment by Rajpratik71** [comment]
> @Rajpratik71 I can't reproduce it, Services seems to resolve well to me on hotsNetwork pods with `ClusterFirstWithHostNet`, what happens if you do
> 
> ```
> curl -kv https://kubernetes.default
> ```
> 
> inside the pod?


Hi @aojea , I am talking about accessing deployed service using service name as shown below

![image](https://user-images.githubusercontent.com/12658912/190644376-2fb61a1a-b7fa-42df-8c9a-0cb54405db35.png)

**Comment by Rajpratik71** [comment]
> > @aojea Same issue is obeserved in cluster created using "kubeadm".
> 
> yeah, I tried to mean to reproduce the problem and explain the exact problem:
> 
> * what is the `resolv.conf` inside the hostNetwork pod? it should be ClusterIP of the cluster Service for dns
> * you can access the podIP, can you access the ClusterIP of the Service?
> * ...

Also, checked these, scenarios below

![image](https://user-images.githubusercontent.com/12658912/190645783-0fb89e7b-da79-4da2-a976-569eeb43cdb6.png)

**Comment by aojea** [comment]
:smile:  commented on the linked gist

this manifest is wrong , the selector of the service doesn't match the pod, thus there is no endpoints to forward the traffic.

```
kubectl get endpoints -A
NAMESPACE     NAME         ENDPOINTS                                               AGE
default       influxdb     <none>                                                  147m
```

You have to add a label to the Pod to match the service selector

https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service

```yaml
apiVersion: v1                           
kind: Pod                                
metadata:  
  name: influxdb                         
  labels:                                
    name: influxdb  <--------------------- has to match the selector                     
spec:                                    
  hostNetwork: true                      
  dnsPolicy: ClusterFirstWithHostNet
  containers:                            
    - name: influxdb
      image: influxdb
      ports:                             
        - containerPort: 8086
          hostPort: 8086
---                                      
kind: Service                            
apiVersion: v1                           
metadata:                                
  name: influxdb                         
spec:                                    
  type: ClusterIP                        
  ports:                                 
    - port: 8086                         
      targetPort: 8086
  selector:                              
    name: influxdb                   
```

/close

Thanks
