### ISSUE TITLE
NetworkPolicy block access nginx-ingress-controller

### ISSUE THREAD

**Issue by quoc9x** [kubernetes/kubernetes#112467]
### What happened?

Hi there,
I want to use networkpolicy to only allow pods in the same namespace to call each other and block all other namespaces. But this will also block nginx-ingress-controller and I can't access domain. I get error `504 Gateway Time-out`. Then, I created another networkpolicy to allow pods from ns ingress-nginx but still getting the same error.

### What did you expect to happen?

Is there any way to do this?
Thanks for support!

### How can we reproduce it (as minimally and precisely as possible)?

This is networkpolicy config
```
# DENY all traffic from other namespaces
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: payment-gateway
  name: payment-gateway-network-policy
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
---
# Allow pods from ingress-nginx
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: payment-gateway
  name: payment-gateway-network-policy-allow-ingress-nginx
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: ingress-nginx
---
# Allow pods from ingress-nginx
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: payment-gateway
  name: payment-gateway-network-policy-allow-ingress-http
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: default-http-backend
```

### Anything else we need to know?

This is network-policy.yaml:

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rikatz** [comment]
when you create a Network Policy, it will turn into "deny by default and allow only what is specified in some network policy".

Besides the fact that I "think" what you specified should be working, maybe what you can do is:


```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: payment-gateway
  name: payment-gateway-network-policy-allow-ingress-nginx
spec:
  podSelector: {}
  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: ingress-namespace-name # <- This should allow traffic from ingress namespace
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: payment-gateway # <- This should allow traffic from this own namespace.
```
Let me know if this works
