### ISSUE TITLE
kubectl convert doesnt pick right API version for conversion

### ISSUE THREAD

**Issue by garomonegro** [kubernetes/kubernetes#112682]
### What happened?

When running `kubectl convert` without the flag `--output-version` on an ingress manifest with `apiVersion` `networking.k8s.io/v1` it picks `extensions/v1beta1` instead of staying on `networking.k8s.io/v1` since that is the latest API version

#### kubectl convert output

```
❯ kubectl convert -f ingress-v1beta1.yaml --validate strict
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: aws-alb
  creationTimestamp: null
  name: example
spec:
  rules:
  - http:
      paths:
      - backend:
          servicePort: 0
        path: /testpath
status:
  loadBalancer: {}
```

#### Content of ingress manifest used

```
❯ cat ingress-v1beta1.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: aws-alb
  name: example
spec:
  backend:
    serviceName: default-backend
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```

### What did you expect to happen?

kubectl convert command to pick `networking.k8s.io/v1` instead of `extensions/v1beta1`

### How can we reproduce it (as minimally and precisely as possible)?

Copy the content below into a file named `ingress.yaml` on the PWD:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: aws-alb
  name: example
spec:
  backend:
    serviceName: default-backend
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```

Run the comment:
```
kubectl convert -f ingress.yaml --validate strict
```

### Kubernetes version

<details>

```console
❯ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
