### ISSUE TITLE
EmptyDir not being cleaned up after pod terminated with open file handles

### ISSUE THREAD

**Issue by abby-gourlay** [kubernetes/kubernetes#112630]
### What happened?

When pods are being terminated on our nodes they're getting stuck in the terminating state and review of the kubelet logs shows that it's unable to delete the emptyDir we have defined for this pod, as there is another process using the folder

```
   39707 Sep 21 10:04  Error       kubelet                         0 E0921 10:04:47.581699    1752 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/empty-dir/e6461804-3188-4189-952b-9be22ef072f8-artifact-dir
                                                                     podName:e6461804-3188-4189-952b-9be22ef072f8 nodeName:}" failed. No retries permitted until 2022-09-21 10:06:49.5816991 +0000 GMT m=+77903.602635501
                                                                     (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"artifact-dir\" (UniqueName:
                                                                     \"kubernetes.io/empty-dir/e6461804-3188-4189-952b-9be22ef072f8-artifact-dir\") pod \"e6461804-3188-4189-952b-9be22ef072f8\" (UID:
                                                                     \"e6461804-3188-4189-952b-9be22ef072f8\") : remove
                                                                     c:\\var\\lib\\kubelet\\pods\\e6461804-3188-4189-952b-9be22ef072f8\\volumes\\kubernetes.io~empty-dir\\artifact-dir\\CBE_DL: The process cannot access the file because
                                                                     it is being used by another process."
```
Reviewing the open file handles on the system it appears to only be kubelet that has one as all the containers within this pod have stopped running
```
PS C:\Windows\System32\config\systemprofile> handle64 e6461804-3188-4189-952b-9be22ef072f8
Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

kubelet.exe        pid: 1304   type: File           A4C: C:\var\lib\kubelet\pods\e6461804-3188-4189-952b-9be22ef072f8\volumes\kubernetes.io~empty-dir\artifact-dir\CBE_DL
```

Manually closing the file handle kubelet had open with the sysinternals tool `handle` then allowed kubelet to finish terminating the pod

```
handle -c A4C -p 1304

Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

  A4C: File  (R--)   C:\var\lib\kubelet\pods\e6461804-3188-4189-952b-9be22ef072f8\volumes\kubernetes.io~empty-dir\artifact-dir\CBE_DL
Close handle A4C in kubelet.exe (PID 1304)? (y/n) y

Handle closed.
```

### What did you expect to happen?

Kubelet removed the directory and completed terminating the pod

### How can we reproduce it (as minimally and precisely as possible)?

I'm not exactly sure why it's getting stuck here. We have a python script download files in our init container into the folder, and then mount it in the main container. The only thing that I did wonder was because we're mounting the volume at the base in the init container, but then using subPaths for the main container which the init container has setup within the volume. 

Our pod spec as minamally as I figured was required would be like
```
apiVersion: v1
kind: Pod
spec:
  containers:
    - image: exampleImageName:latest
      name: exampleImage
      volumeMounts:
        - mountPath: /Downloads
          name: artifact-dir
          subPath: CBE_DL
        - mountPath: /ISAPI/Documents
          name: artifact-dir
          subPath: ISAPIDocuments
  initContainers:
    - image: initContainerImage:latest
      name: download-artifacts
      volumeMounts:
        - mountPath: /DOWNLOADS
          name: artifact-dir
  nodeSelector:
    kubernetes.io/os: windows
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-18ef993", GitCommit:"ac73613dfd25370c18cbbbc6bfc65449397b35c7", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS 1.21
</details>

### OS version

<details>

```console

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                                   OSArchitecture  Version
17763        Microsoft Windows Server 2019 Datacenter  64-bit          10.0.17763
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
docker version
Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.16.12m2
  Git commit:       9b96ce992b
  Built:            12/21/2021 21:33:06
  OS/Arch:          windows/amd64
  Experimental:     false
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/remove-sig storage
/remove-sig node

I'd let sig windows to look at it first and triage

**Comment by marosset** [comment]
@dcantah @kevpar - Have either of you seen this before?

**Comment by kevpar** [comment]
> @dcantah @kevpar - Have either of you seen this before?

I haven't seen anything like this before. It sounds like kubelet is keeping a handle around that prevents it from deleting the directory, but I don't know why kubelet would have a handle open to the directory in the first place.

**Comment by marosset** [comment]
I saw someone run into a similar issue and can reproduce the issue with the following yaml deployments

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: animals
data:
  dog: |
    bark
    woof woof
  cat: |
    meow
    meow
```
and

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: volmount
spec:
  containers:
    - image: mcr.microsoft.com/windows/nanoserver:ltsc2022
      command:
        - "ping"
        - "-t"
        - "127.0.0.1"
      name: ctr
      volumeMounts:
        - mountPath: C:/volmount
          name: emptydir
        - mountPath: C:/volmount/dog.txt
          name: cm1
          subPath: dog.txt
        - mountPath: C:/volmount/cat.txt
          name: cm2
          subPath: cat.txt
  volumes:
    - name: emptydir
      emptyDir: {}
    - name: cm1
      configMap:
        name: animals
        items:
          - key: dog
            path: dog.txt
    - name: cm2
      configMap:
        name: animals
        items:
          - key: cat
            path: cat.txt
  nodeSelector:
    "kubernetes.io/os": windows
  os:
    name: windows
```

When you try and delete the pod it gets stuck in a terminating state and I see the following error messages in the kubelet log

```log
E1013 20:59:14.650323    5076 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/configmap/523abd72-2938-41e8-b775-33461ef86c35-cm1 podName:523abd72-2938-41e8-b775-33461ef86c35 nodeName:}" failed. No retries permitted until 2023-10-13 21:01:16.6503236 +0000 UTC m=+1578.644445501 (durationBeforeRetry 2m2s). Error: UnmountVolume.TearDown failed for volume "cm1" (UniqueName: "kubernetes.io/configmap/523abd72-2938-41e8-b775-33461ef86c35-cm1") pod "523abd72-2938-41e8-b775-33461ef86c35" (UID: "523abd72-2938-41e8-b775-33461ef86c35") : remove c:\var\lib\kubelet\pods\523abd72-2938-41e8-b775-33461ef86c35\volumes\kubernetes.io~configmap\cm1\..2023_10_13_20_45_56.849177365\dog.txt: The process cannot access the file because it is being used by another process.
```

**Comment by tzifudzi** [comment]
I can confirm this issue is still occurring. 

It can be minimally reproduced by creating a pod/deployment with at least 2 volume mounts with both being from either a configmap or secret. Using Sysinternals Process Explorer I was able to confirm that kubelet is the process that is maintaining the lock. For some yet to be known reason kubelet successfully deletes the directory for one of the volumes but fails to cleanup all all the volumes. 

Might be able to help out with investigating the root cause and potentially providing a fix.

Repro'd using the YAML shared by Mark with the following platform details
- Kubernetes Control plane version: 1.28
- Kubelet: 1.28.3
- Cloud provider: EKS
- OS: Microsoft Windows Server 2022 Datacenter 10.0.20348 (with latest updates as of today)

**Comment by acwwat** [comment]
Thanks @tzifudzi. Being able to mount multiple volumes is a common and essential use case, so this issue is pretty critical. I am seeing this exact problem and it's causing more downstream headaches. It seems that if we force terminate these stuck pods, the VPC CNI plugin/PAMD would lose track of IP usages, which causes it to hand out the same IP to new pods thereby causing failures. It would be great if someone could investigate this file lock issue soon. Thanks.

**Comment by marosset** [comment]
The issue is not caused by having multiple volume months for a Pod.
The issue is caused because other volume mounts are being mounted inside the emptyDir volume.

According to https://kubernetes.io/docs/concepts/storage/volumes/ this is not allowed

> Volumes cannot mount within other volumes (but see [Using subPath](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) for a related mechanism). Also, a volume cannot contain a hard link to anything in a different volume

I think if we don't nest other volume mounts inside the emptyDir volume we won't see this issue.

**Comment by kylelee24** [comment]
I am able to see the same behaviour without using emptyDir. There are many permutations to reproduce this, but I have simplified it to:

* Windows container image `mcr.microsoft.com/windows/servercore:ltsc2022`
* A single secret (or config map)
* Two volume mounts with different mount paths and subpaths referencing the single secret

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminated-pod-test-base-case
  labels:
    app: terminated-pod-test-base-case
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminated-pod-test-base-case
  template:
    metadata:
      labels:
        app: terminated-pod-test-base-case
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: terminated-pod-test-base-case
          image: mcr.microsoft.com/windows/servercore:ltsc2022
          command:
            - powershell.exe
            - -command
            - while(1){sleep 2; ping -t localhost;}
          volumeMounts:
            - name: config
              mountPath: /config/config1
              subPath: config1
              readOnly: true
            - name: config
              mountPath: /config/config2
              subPath: config2
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: config
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: config
  namespace: default
data:
  config1: aGVsbG8gd29ybGQ=
  config2: aGVsbG8gd29ybGQy
```

Reproduction steps:

1. Apply above config.
2. Delete pod.
3. New pod comes up but old pod gets stuck terminating.

**Comment by marosset** [comment]
Ahhh, thanks for the clarification!

**Comment by marciogmorales** [comment]
Hello,
Two questions:

1-  Did you try not to use ReadOnly flag? Secrets mounts are already ReadOnly by default. This "enforce by flag" may be holding the temporary file created in the OS, because the "file" is attached as read-only, and may be prevented from being deleted during pod termination.

2- Why are you using SubPath when mounting a Secret or ConfigMap? This isn't a best practice because volume mount using SubPath will not receive Secret/ConfigMaps updates, so the "dynamic" of using Secret/ConfigMaps for running pods will be lost.

A possible root cause is that you are mounting the same volume twice as a Secret/ConfigMap. During pod termination, Secret/ConfigMap files inside the pods suffer a parallel exclusion from the disk. However, as you mount it twice, the process will lock the file, and Windows throws: "The process cannot access the file because another process is using it."

If possible, try to:
 - Remove Readonly Flag and SubPath and give it a try
 - Try to use a single volume per secret and give it a try.

In case the tests above work, we will need to adjust how Kubelet handles files exclusion on Windows.

**Comment by kylelee24** [comment]
Hi @marciogmorales,

To answer your questions, 

1. Yes, I have tried without the `readOnly` flag. I still see the pods get stuck terminating. 
2. I am using `subPath` to mount the Secret/ConfigMap because we want to override a specific file on the container rather than just mounting the folder. We are not worried about having the data update dynamically at this time. The removal of `subPath` does seem to allow pods to be terminated.

I have tried to:
* Remove Readonly Flag and SubPath and give it a try
  * **The removal of `subPath` actually does work.** 
  * The problem is what I described in 2. where we need to override a specific file, rather than mounting a directory and I believe using `subPath` is the only supported way.
  * I am now considering workarounds such as using the entrypoint to copy the files to the appropriate places before running the application. Any other suggestions would be appreciated.
* Try to use a single volume per secret and give it a try
  * This does not work.

If there is a way to not use `subPath` but still mount individual files from a Secret/ConfigMap, that will solve my problem. 

# Testing

## Remove Readonly Flag and SubPath and give it a try

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminated-pod-test-base-case-no-readonly-or-subpath
  labels:
    app: terminated-pod-test-base-case-no-readonly-or-subpath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminated-pod-test-base-case-no-readonly-or-subpath
  template:
    metadata:
      labels:
        app: terminated-pod-test-base-case-no-readonly-or-subpath
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: terminated-pod-test-base-case-no-readonly-or-subpath
          image: mcr.microsoft.com/windows/servercore:ltsc2022
          command:
            - powershell.exe
            - -command
            - while(1){sleep 2; ping -t localhost;}
          volumeMounts:
            - name: config
              mountPath: /config/config1
            - name: config
              mountPath: /config/config2
      volumes:
        - name: config
          secret:
            secretName: config
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: config
  namespace: default
data:
  config1: aGVsbG8gd29ybGQ=
  config2: aGVsbG8gd29ybGQy
```

```
# Create deployment with no subPath or readOnly options
➜  workspace k apply -f terminated-pod-test-base-case-no-readonly-or-subpath.yaml
deployment.apps/terminated-pod-test-base-case-no-readonly-or-subpath created
secret/config unchanged

# List pods
➜  workspace k get po
NAME                                                              READY   STATUS    RESTARTS   AGE
terminated-pod-test-base-case-no-readonly-or-subpath-6b6d5qzmlw   1/1     Running   0          6s

# Delete deployment
➜  workspace k delete deployment terminated-pod-test-base-case-no-readonly-or-subpath
deployment.apps "terminated-pod-test-base-case-no-readonly-or-subpath" deleted

# Show pods as terminating 
➜  workspace k get po
NAME                                                              READY   STATUS        RESTARTS   AGE
terminated-pod-test-base-case-no-readonly-or-subpath-6b6d5qzmlw   1/1     Terminating   0          18s

# Show pods cleaned up
➜  workspace k get po
NAME                                     READY   STATUS    RESTARTS   AGE
➜  workspace
```

## Try to use a single volume per secret and give it a try

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminated-pod-test-base-case-multiple-volumes
  labels:
    app: terminated-pod-test-base-case-multiple-volumes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminated-pod-test-base-case-multiple-volumes
  template:
    metadata:
      labels:
        app: terminated-pod-test-base-case-multiple-volumes
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: terminated-pod-test-base-case-multiple-volumes
          image: mcr.microsoft.com/windows/servercore:ltsc2022
          command:
            - powershell.exe
            - -command
            - while(1){sleep 2; ping -t localhost;}
          volumeMounts:
            - name: config1
              mountPath: /config/config1
              subPath: config1
              readOnly: true
            - name: config2
              mountPath: /config/config2
              subPath: config2
              readOnly: true
      volumes:
        - name: config1
          secret:
            secretName: config1
        - name: config2
          secret:
            secretName: config2
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: config1
  namespace: default
data:
  config1: aGVsbG8gd29ybGQ=
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: config2
  namespace: default
data:
  config2: aGVsbG8gd29ybGQy
```

```
# Create deployment using multiple volumes (still using subPath and readOnly)
➜  workspace k apply -f terminated-pod-test-base-case-multiple-volumes.yaml
deployment.apps/terminated-pod-test-base-case-multiple-volumes created
secret/config1 unchanged
secret/config2 unchanged

# List pods
➜  workspace k get po
NAME                                                             READY   STATUS    RESTARTS   AGE
terminated-pod-test-base-case-multiple-volumes-d9895f459-44qm6   1/1     Running   0          14s

# Delete deployment
➜  workspace k delete deployment terminated-pod-test-base-case-multiple-volumes
deployment.apps "terminated-pod-test-base-case-multiple-volumes" deleted

# Show pods stuck terminating
➜  workspace k get po
NAME                                                             READY   STATUS        RESTARTS   AGE
terminated-pod-test-base-case-multiple-volumes-d9895f459-44qm6   0/1     Terminating   0          2m6s

```

**Comment by marciogmorales** [comment]
So I think we can work around this slightly differently because the idea of SubPath is to avoid having multiple volumes but still have different mount points from the volume.

If you need to replace a file during bootstrap, you could use lifecycle hooks (PostStart). This hook is executed immediately after a container is created.

Something like:

```
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
        lifecycle:
          PostStart:
            exec:
              command:
              - powershell.exe
              - -command
              - "COMMAND COPY YOUR FILE FROM SOURCE TO THE CONTAINER"
```

**Comment by kylelee24** [comment]
Thanks. I have tested the lifecycle hook feature which does work as expected however there are warnings in the documentation suggesting that this does not guarantee execution before the entrypoint is executed. 

> PostStart
> 
> This hook is executed immediately after a container is created. However, there is no guarantee that the hook will execute before the container ENTRYPOINT. No parameters are passed to the handler.

Reference: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks

While this has worked for me 100% of the time, the documentation does state this may not be risky. I know this is a bit of a hack, but would just combining the commands to copy your files with the entrypoint be safer? Or is this a feature we can rely on? 

# Testing

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminated-pod-test-base-case-fix-with-lifecycle-workaround
  labels:
    app: terminated-pod-test-base-case-fix-with-lifecycle-workaround
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminated-pod-test-base-case-fix-with-lifecycle-workaround
  template:
    metadata:
      labels:
        app: terminated-pod-test-base-case-fix-with-lifecycle-workaround
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: terminated-pod-test-base-case-fix-with-lifecycle-workaround
          image: mcr.microsoft.com/windows/servercore:ltsc2022
          command:
            - powershell.exe
            - -command
            - while(1){sleep 2; ping -t localhost;}
          volumeMounts:
            - name: config
              mountPath: /config
          lifecycle:
            postStart:
              exec:
                command:
                - powershell.exe
                - -command
                - New-Item -ItemType Directory -Path C:\web1; New-Item -ItemType Directory -Path C:\web2; Copy-Item "C:\config\config1" -Destination "C:\web1\config1"; Copy-Item "C:\config\config2" -Destination "C:\web2\config2"
      volumes:
        - name: config
          secret:
            secretName: config
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: config
  namespace: default
data:
  config1: aGVsbG8gd29ybGQ=
  config2: aGVsbG8gd29ybGQy
```

```
# Create deployment with no subPath or readOnly options
➜  workspace  k apply -f /Users/kyle/Softchoice/workspace/ctt-sci-ff17246/eks/examples/ignore_terminated-pod-troubleshooting-github/terminated-pod-test-base-case-fix-with-lifecycle-workaround.yaml
deployment.apps/terminated-pod-test-base-case-fix-with-lifecycle-workaround created
secret/config unchanged

# List containers
➜  workspace k get po
NAME                                                              READY   STATUS    RESTARTS   AGE
terminated-pod-test-base-case-fix-with-lifecycle-workaroun478cp   1/1     Running   0          18s

# Exec into container and list the volume mounted directory (c:\config)
➜  workspace k exec -it terminated-pod-test-base-case-fix-with-lifecycle-workaroun478cp -- powershell.exe -command dir c:\config

    Directory: C:\config


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2023   9:25 PM                ..2023_12_12_21_25_02.3598229827
d----l        12/12/2023   9:25 PM                ..data
-a---l        12/12/2023   9:25 PM              0 config1
-a---l        12/12/2023   9:25 PM              0 config2


# Exec into the container and list the web folders created by the lifecycle hook
➜  workspace k exec -it terminated-pod-test-base-case-fix-with-lifecycle-workaroun478cp -- powershell.exe -command dir 'c:\web*'

    Directory: C:\


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2023   9:25 PM                web1
d-----        12/12/2023   9:25 PM                web2


# Exec into the container and list the web1 folder contents
➜  workspace k exec -it terminated-pod-test-base-case-fix-with-lifecycle-workaroun478cp -- powershell.exe -command dir 'c:\web1\'


    Directory: C:\web1


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        12/12/2023   9:25 PM             11 config1

# Exec into the container 
➜  workspace k exec -it terminated-pod-test-base-case-fix-with-lifecycle-workaroun478cp -- powershell.exe -command get-content 'c:\web1\config1'
hello world

➜  workspace k exec -it terminated-pod-test-base-case-fix-with-lifecycle-workaroun478cp -- powershell.exe -command get-content 'c:\web2\config2'
hello world2

# Delete deployment
➜  workspace k delete deployment terminated-pod-test-base-case-fix-with-lifecycle-workaround
deployment.apps "terminated-pod-test-base-case-fix-with-lifecycle-workaround" deleted

# Ensure pods are removed
➜  workspace k get po
NAME                                     READY   STATUS    RESTARTS   AGE
```

**Comment by marciogmorales** [comment]
Yes, it is a feature you can rely on and it is widely used. What the document states is that there is no coordination between the entrypoint service startup and the preStart hook. 

If that worked for you, I would suggest to keep with this configuration instead of using Secret or ConfigMap to override an existing file.

**Comment by tzifudzi** [comment]
Hello everyone,

I wanted to provide an update on the ongoing investigation into this issue. After several hours of in-depth analysis, I am convinced there is a bug causing the file handle lock to be maintained without being released which in turn causes the pod to be stuck in terminating status.

I have developed several hypotheses regarding the root cause and plan to troubleshoot these in a further deep dive. In the event that am unable to figure it out, I will add add an update with all my findings and will unassign to allow for fresh perspectives from someone else.

**Comment by acwwat** [comment]
@tzifudzi Just doing a pulse check to see if there are any updates with this issue. Please advise - appreciate your help :)

**Comment by tzifudzi** [comment]
Hi @acwwat No updates unfortunately. This issue is still open and needs to be resolved.

Still need to make time to do another deep dive to figure out which part of the code is leading towards the lock being maintained. If someone else has capacity to take a look, I am happy to unassign myself. Else I will aim to take a look in the next few weeks or sooner.

**Comment by chemi0213** [comment]
I have similar issue about the issues of pod stuck at terminating. the error message is:
```
Operation for {volumeName:kubernetes.io/configmap/8fda17e6-e7fb-44bd-b5c0-0416e8858081-test-config podName:8fda17e6-e7fb-44bd-b5c0-0416e8858081 nodeName:} failed.
No retries permitted until 2024-05-19 06:41:22.9031532 +0000 UTC m=+731.352486701 (durationBeforeRetry 500ms). 
Error: UnmountVolume.TearDown failed for volume test-config (UniqueName: kubernetes.io/configmap/8fda17e6-e7fb-44bd-b5c0-0416e8858081-test-config) pod 8fda17e6-e7fb-44bd-b5c0-0416e8858081 (UID: 8fda17e6-e7fb-44bd-b5c0-0416e8858081) : remove c:\var\lib\kubelet\pods\8fda17e6-e7fb-44bd-b5c0-0416e8858081\volumes\kubernetes.io~configmap\test-config\..2024_05_19_06_39_29.445006245\test_config: The process cannot access the file because it is being used by another process.
```

I'm running AWS EKS v1.27 with below yaml. there is only one container in the pod, mount a config map and a PVC which is connect to AWS FSx for Windows by using [kubernetes-csi/csi-driver-smb](https://github.com/kubernetes-csi/csi-driver-smb)

<details>
<summary>Please click to show the whole yaml file</summary>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-termination
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-termination
  template:
    metadata:
      labels:
        app: test-termination
    spec:
      containers:
      - image: mcr.microsoft.com/windows/server:ltsc2022
        command:
        - ping.exe
        - -t
        - 127.0.0.1
        imagePullPolicy: IfNotPresent
        name: main-container
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: 40G
            memory: 8Gi
          requests:
            cpu: "1"
            ephemeral-storage: 10G
            memory: 4Gi
        volumeMounts:
        - mountPath: C:\test\test_config
          name: test-config
          subPath: test_config
        - mountPath: C:\fsx
          name: fsx-storage
          subPath: fsx
      nodeSelector:
        kubernetes.io/os: windows
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: win-nodegroup
      volumes:
      - configMap:
          items:
          - key: test_config
            path: test_config
          name: test-termination-cm
        name: test-config
      - name: fsx-storage
        persistentVolumeClaim:
          claimName: test-termination-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-termination-pv
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fsx
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: //xx.xx.xxx.xxx/share#test-termination##
    volumeAttributes:
      source: //xx.xx.xxx.xxx/share
    nodeStageSecretRef:
      name: smbcreds
      namespace: default
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-termination-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: test-termination-pv
  storageClassName: fsx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-termination-cm
data:
  test_config: test
</details>

A weird thing is if change the sequence of the Volumes: and volumeMounts:

Case1: `configmap before the PVC`. the deleting pod will stuck at terminating
```
...
        volumeMounts:
        - mountPath: C:\test\test_config
          name: test-config
          subPath: test_config
        - mountPath: C:\fsx
          name: fsx-storage
          subPath: fsx
...
      volumes:
      - configMap:
          items:
          - key: test_config
            path: test_config
          name: test-termination-cm
        name: test-config
      - name: fsx-storage
        persistentVolumeClaim:
          claimName: test-termination-pvc
...
```

Case2: `configmap after the PVC`. the pod will be delete normally
```
...
        volumeMounts:
        - mountPath: C:\fsx
          name: fsx-storage
          subPath: fsx
        - mountPath: C:\test\test_config
          name: test-config
          subPath: test_config
...
      volumes:
      - name: fsx-storage
        persistentVolumeClaim:
          claimName: test-termination-pvc
      - configMap:
          items:
          - key: test_config
            path: test_config
          name: test-termination-cm
        name: test-config
...
```
The case 1 & 2 logs can be found at https://gist.github.com/chemi0213/b24aa4e9ff9416406b8af3cd4467a3fb
So currently I put the PVC before ConfigMap to workaround it. Hope it can be fixed soon since the sequence in a yaml file will impact something is very unreasonable

P.S. Opened an AWS support case Case ID 171612527800869 and support said: We have confirmed that the issue is an upstream kubernetes issue, and thus we do not have control over the fix and cannot give an ETA from our side on this.
