### ISSUE TITLE
Setting Windows HostProcess causes agnhost to crash

### ISSUE THREAD

**Issue by alexander-ding** [kubernetes/kubernetes#112651]
### What happened?

I was able to create a deployment running `k8s.gcr.io/e2e-test-images/agnhost:2.33` on a Windows node successfully, but for some reason, setting the security context of the pod to be a Windows host process causes the image to crash, complaining that it fails to find the executable. 
![image](https://user-images.githubusercontent.com/22578848/191597658-cef99d24-183a-4e55-81ac-e0dafd5114af.png)

### What did you expect to happen?

Both specs should create pods that run without issues. 

### How can we reproduce it (as minimally and precisely as possible)?

Here's the deployment I'm creating. Just comment out 
```yaml
securityContext:
  windowsOptions:
    hostProcess: true
    runAsUserName: "NT AUTHORITY\\Networkservice"
hostNetwork: true
```
to have it run successfully as a regular process. 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-agnhost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agnhost
  template:
    metadata:
      labels:
        app: agnhost
    spec:
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\Networkservice"
      hostNetwork: true
      containers:
      - name: agnhost
        image: k8s.gcr.io/e2e-test-images/agnhost:2.33
        args:
        - serve-hostname
      nodeSelector:
        kubernetes.io/os: windows
```

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:40:59Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.0-alpha.0.690+8ac009f66d2aca-dirty", GitCommit:"8ac009f66d2aca70489b9299b7bf73dc19423268", GitTreeState:"dirty", BuildDate:"2022-09-20T20:11:54Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Google Cloud (Compute Engine)
</details>

### OS version

<details>

My workspace:
```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux rodete"
NAME="Debian GNU/Linux"
VERSION_ID="rodete"
VERSION="12 (rodete)"
VERSION_CODENAME=rodete
ID=debian
$ uname -a
Linux some.host.ip 5.18.16-1rodete1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1rodete1 (2022-08-24) x86_64 GNU/Linux
```

The node that the pod is running on:
```console
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                                   OSArchitecture  Version
17763        Microsoft Windows Server 2019 Datacenter  64-bit          10.0.17763
```

</details>

### Install tools

<details>
kube-up.sh
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
I have PDCSI installed, but I'm not sure if that's related.
</details>
