### ISSUE TITLE
kubectl convert validate seems to not work properly

### ISSUE THREAD

**Issue by garomonegro** [kubernetes/kubernetes#112681]
### What happened?

When running `kubectl convert` with the flag `--validate strict` on an ingress manifest with `networking.k8s.io/v1` `apiVersion` but fields from the `networking.k8s.io/v1beta1` `apiVersion` the commands succeeds. I was expecting it to failed. Instead it just drops the `serviceName` and `servicePort` fields and returns an ingress manifest with empty `backend`

### kubectl convert validate output: no failures, empty backend
```
kubectl convert --show-managed-fields false --output-version networking.k8s.io/v1 -f ingress-v1beta1.yaml --validate strict
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: aws-alb
  creationTimestamp: null
  name: example
spec:
  rules:
  - http:
      paths:
      - backend: {}
        path: /testpath
        pathType: null
status:
  loadBalancer: {}
```

### Content of ingress manifest used
```
❯ cat ingress-v1beta1.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: aws-alb
  name: example
spec:
  backend:
    serviceName: default-backend
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```

### What did you expect to happen?

I expected the command to failed because the manifest used did not meet the schema for the specified API version

### How can we reproduce it (as minimally and precisely as possible)?

Copy the content below into a file named `ingress.yaml` on the PWD:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: aws-alb
  name: example
spec:
  backend:
    serviceName: default-backend
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```

Run the comment:
```
kubectl convert --show-managed-fields false --output-version networking.k8s.io/v1 -f ingress.yaml --validate strict
```

### Kubernetes version

<details>

```console
❯ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
