### ISSUE TITLE
statefulSet controller will not sync all pods' template 

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#112767]
### What happened?

When I updated statefulSet image, not all pods' images will be synced with.

### What did you expect to happen?

All pods will be synced with the statefulSet pod template.

### How can we reproduce it (as minimally and precisely as possible)?

1. create a statefulSet like below
 ```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  updateStrategy:
    rollingUpdate:
      partition: 3
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:1.14.1
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
        - name: www
          emptyDir: {}
```
2.  Edit the yaml file and apply again, changed the `replicas` and `image`:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  updateStrategy:
    rollingUpdate:
      partition: 3
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
        - name: www
          emptyDir: {}
```
3. run `kubectl get pods -l app=nginx -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' | sort`, output as below:
```

web-0:	nginx:1.14.1,
web-1:	nginx:1.14.1,
web-2:	nginx:1.14.1,
web-3:	nginx:1.14.2,
web-4:	nginx:1.14.2,
web-5:	nginx:1.14.2,
web-6:	nginx:1.14.2,
web-7:	nginx:1.14.2,
web-8:	nginx:1.14.2,
web-9:	nginx:1.14.2,
```

### Kubernetes version

<details>
kind create cluster with image `kindest/node:v1.25.2`

Also exists in v.124
</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
