### ISSUE TITLE
matchLabelKeys in topologySpreadConstraints doesn't not print anything in kubectl describe

### ISSUE THREAD

**Issue by liboz** [kubernetes/kubernetes#112730]
### What happened?

I used `kubectl describe` on a pod with `topologySpreadConstraints`'s matchLabelKeys applied. I have the featuregate `MatchLabelKeysInPodTopologySpread` applied

### What did you expect to happen?

I expect some printed output that indicates that the config has been applied. I expect the code needs to be updated here https://github.com/kubernetes/kubernetes/blob/23a4920d83559ba803629512c8a02630e5fdc0a6/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L895

### How can we reproduce it (as minimally and precisely as possible)?

Use `kubectl describe` on a pod with `topologySpreadConstraints`'s matchLabelKeys applied

### Kubernetes version

1.25

### Cloud provider

k3s baremetal

**Comment by kerthcet** [comment]
matchLabelKeys only used in topology spreading, it's an in-memory operation, will not display in `kubectl describe`.

**Comment by vrnmthr** [comment]
@kerthcet is it expected that matchLabelKeys will not show in a `kubectl get -oyaml` operation as well? I specified this in my deployment, but when I run a get on my pod I see the following YAML:

```
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app: myapp
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
```

There is no matchLabelKeys even there. If I add matchLabelKeys via edit, it does not show up either.
Output of `kubectl version`:
```
vamathur@CPC-vamat-OOM4G:~/src/marian-dev$ k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.27.9
```
