### ISSUE TITLE
NodeSelector doesn't work with all the labels of nodes

### ISSUE THREAD

**Issue by ksankeerth** [kubernetes/kubernetes#112759]
### What happened?

I'm trying to deploy a `DaemonSet` only on Master Node. The master node has a few labels already and I added a few new labels as well. When I use those labels in `DaemonSet` Spec, the k8s not scheduling DS deployment in any nodes.

I have installed K8s using `Kubeadm` on Ubuntu 20 LTS.

**Labels available on each nodes**

```yaml

NAME       STATUS   ROLES                  AGE   VERSION   LABELS
kcp        Ready    control-plane,master   24h   v1.24.3   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=kcp,kubernetes.io/os=linux,kubernetes.io/test=test,node-role.kubernetes.io/control-plane=true,node-role.kubernetes.io/master=true,node.kubernetes.io/exclude-from-external-load-balancers=,test1=1

````

The master node contains the below labels.

- beta.kubernetes.io/arch=amd64
- beta.kubernetes.io/os=linux
- kubernetes.io/arch=amd64
- kubernetes.io/hostname=kcp
- kubernetes.io/os=linux
- kubernetes.io/test=test
- node-role.kubernetes.io/control-plane=true
- node-role.kubernetes.io/master=true
- node.kubernetes.io/exclude-from-external-load-balancers=
- test1=1

The below is my DaemonSet YAML

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wgcni-cluster-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      nodeSelector:
        kubernetes.io/test: "test"
      containers:
      - name: fluentd-elasticsearch
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
```

No DaemonSet for `wgcni-cluster-manager` scheduled on any nodes.

```yaml
sankeerthan@Sankeerthans-MacBook-Pro ~ % kubectl get ds -n kube-system
NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR             AGE
cilium                  2         2         2       2            2           kubernetes.io/os=linux    24h
kube-proxy              2         2         2       2            2           kubernetes.io/os=linux    24h
wgcni-cluster-manager   0         0         0       0            0           kubernetes.io/test=test   22h
sankeerthan@Sankeerthans-MacBook-Pro ~ %
```

If I use `kubernetes.io/os=linux` for `NodeSelector`, then I can see `wgcni-cluster-manager` deployed on all the nodes.

I changed the `NameSpace` to `default` and with different `lables`. The observations was the same.

### What did you expect to happen?

`NodeSelector` to work for all the labels, not just for `kubernetes.io/os=linux`

### How can we reproduce it (as minimally and precisely as possible)?

1. Add labels to node/master node 

```yaml
 kubectl label node <node_name> <label>=test
```
2. Create a DaemonSet like the below (Give the created label in `NodeSelector`)
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wgcni-cluster-manager
  namespace: default
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      nodeSelector:
        kubernetes.io/test: "test"
      containers:
      - name: fluentd-elasticsearch
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
```

### Anything else we need to know?

In my setup, If I use the label `kubernetes.io/os=linux`, then it create DaemonSet on all the nodes.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On-Prem/Dev Setup configured using `Kubeadm`
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux kcp 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
`kubectl` cli was use to create DaemonSet
</details>

### Container runtime (CRI) and version (if applicable)

<details>
RuntimeName:  containerd
RuntimeVersion:  v1.6.8
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
 Cilium
</details>
