### ISSUE TITLE
Can no longer create pods:  FailedCreate : context deadline exceeded

### ISSUE THREAD

**Issue by jseparovic** [kubernetes/kubernetes#112765]
### What happened?

I was testing out some Network Policies to understand how they work and after creating (and then removing) a Network Policy to limit ports on 80/443 (which I'm pretty sure I messed up, hence the delete), I realized the cluster will no longer create new pods.

I see the following over and over again in kube-apiserver logs (note I have multiple statefulsets trying to scale up pods and failing):
`
{"log":"W0928 06:57:27.611324       1 dispatcher.go:170] Failed calling webhook, failing open webhook.stork.libopenstorage.org: failed calling webhook \"webhook.stork.libopenstorage.org\": Post \"https://stork-service.kube-system.svc:443/mutate?timeout=10s\": context deadline exceeded\n","stream":"stderr","time":"2022-09-28T06:57:27.611357477Z"}
`

This is what I see for every new Pod attempt across the cluster.
kubectl describe:
`
Warning  FailedCreate  13s   replicaset-controller  Error creating: Timeout: request did not complete within requested timeout context deadline exceeded
`

### What did you expect to happen?

Pods should be getting created as normal

### How can we reproduce it (as minimally and precisely as possible)?

This was the network policy I had applied and removed. I was basically trying to limit external access to 80 and 443 to cloudflare IPs only. I failed miserably, so I just deleted the policy. I'm not sure if this had anything to do with the issue though. Probably a coincidence

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-network-policy
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 173.245.48.0/20
        - ipBlock:
            cidr: 103.21.244.0/22
        - ipBlock:
            cidr: 103.22.200.0/22
        - ipBlock:
            cidr: 103.31.4.0/22
        - ipBlock:
            cidr: 141.101.64.0/18
        - ipBlock:
            cidr: 108.162.192.0/18
        - ipBlock:
            cidr: 190.93.240.0/20
        - ipBlock:
            cidr: 188.114.96.0/20
        - ipBlock:
            cidr: 197.234.240.0/22
        - ipBlock:
            cidr: 198.41.128.0/17
        - ipBlock:
            cidr: 162.158.0.0/15
        - ipBlock:
            cidr: 104.16.0.0/13
        - ipBlock:
            cidr: 104.24.0.0/14
        - ipBlock:
            cidr: 172.64.0.0/13
        - ipBlock:
            cidr: 131.0.72.0/22
      ports:
      - port: 443
      - port: 80
```

### Anything else we need to know?

I managed to get 2 clusters in this state at the same time somehow

Also, deleting pods works no problem:
```
NAME                                 READY   STATUS        RESTARTS   AGE
pod/centos-util-1664063774           1/1     Terminating   6	      3d7h
```

Just can't create it again...

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Baremetal
```
kubelet --version
Kubernetes v1.21.9
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
NAME="AlmaLinux"
VERSION="8.6 (Sky Tiger)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.6 (Sky Tiger)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.6"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"

$ uname -a
# paste output here
Linux master1 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Tue Aug 2 13:42:59 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
