### ISSUE TITLE
kubectl/logs: kubectl logs MethodNotAllowed

### ISSUE THREAD

**Issue by seaurching** [kubernetes/kubernetes#112801]
#### While I show container's log by using kubectl logs, give me an error like this:
![image](https://user-images.githubusercontent.com/7349963/193247902-1be6abcf-3944-4cdb-a185-661f041db08a.png)

```
[root@k8s-master-1 ~]# kubectl logs nginx-85b98978db-4gd2n 
Error from server (MethodNotAllowed): the server does not allow this method on the requested resource ( pods/log nginx-85b98978db-4gd2n
```
The cluster's version 1.23.10 init by configuration,the content is
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 900h0m0s
  usages:
  - signing
  - authentication
  description: "bootstrap token"
localAPIEndpoint:
  advertiseAddress: "10.1.2.50"
  bindPort: 6443
nodeRegistration:
  imagePullPolicy: "IfNotPresent"
  name: "k8s-master-1"
  taints: null
  kubeletExtraArgs:
    v: "4"
  ignorePreflightErrors:
    - IsPrivilegedUser
    - Swap

---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs:
    authorization-mode: "Node,RBAC"
  extraVolumes:
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
#dns:
#  imageRepository:
#  imageTag:
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: "registry.cn-hangzhou.aliyuncs.com/google_containers"
kubernetesVersion: "v1.23.1"
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.101.0.0/24
  podSubnet: "10.102.0.0/24"
scheduler:
  extraArgs:
    bind-address: "0.0.0.0"
#featureGates:
controlPlaneEndpoint: "10.1.3.52:6443"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: "systemd"
enableServer: true
syncFrequency: "20s"
fileCheckFrequency: "20s"
httpCheckFrequency: "15s"
address: "0.0.0.0"
port: 10250
shutdownGracePeriod: "5s"
readOnlyPort: 0
registryPullQPS: 5
failSwapOn: false
containerLogMaxFiles: 10
containerLogMaxSize: "500Mi"
enableDebuggingHandlers: false
nodeStatusReportFrequency: "30s"
nodeStatusUpdateFrequency: "10s"
streamingConnectionIdleTimeout: "8h"
imageMinimumGCAge: "5m"
volumeStatsAggPeriod: "2m"
imageGCHighThresholdPercent: 80
imageGCLowThresholdPercent: 60
runtimeRequestTimeout: "30s"
nodeStatusMaxImages: 100
serializeImagePulls: true
evictionHard:
  "memory.available": "2048Mi"
  "nodefs.available": "40%"
  "imagefs.available": "15%"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: "0.0.0.0"
healthzBindAddress: "0.0.0.0:10256"
metricsBindAddress: "0.0.0.0:10249"
bindAddressHardFail: false
enableProfiling: true
configSyncPeriod: "10s"
mode: "ipvs"
ipvs:
  syncPeriod: 10s
  tcpTimeout: 10s
  tcpFinTimeout: 5s
#iptables:
#  masqueradeBit: 31
#  masqueradeAll: true
#  syncPeriod: "3m"
#  minSyncPeriod: "1m"
udpIdleTimeout: "2s"
conntrack:
  tcpEstablishedTimeout: "5s"
  tcpCloseWaitTimeout: "5s"

```

### What did you expect to happen?

Show the containers's log 

### How can we reproduce it (as minimally and precisely as possible)?

kubeadm init --config configfile.

### Kubernetes version

<details>

```console
[root@k8s-master-1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:32:54Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
SelfManaged
</details>

### OS version

<details>

```console
[root@k8s-master-1 ~]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@k8s-master-1 ~]# uname -a
Linux k8s-master-1 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
[root@k8s-master-1 ~]# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 21
  Running: 15
  Paused: 0
  Stopped: 6
 Images: 13
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.76.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.521GiB
 Name: k8s-master-1
 ID: EXOZ:2GQU:6EGC:JXKP:F7MB:TUZ3:KPXJ:PN4V:SHIJ:WLQD:JPGE:3SCC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://b9pmyelo.mirror.aliyuncs.com/
 Live Restore Enabled: false

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
docker.io/calico/kube-controllers:v3.24.1
</details>
@brosner @gnufied
