### ISSUE TITLE
When a Hostprocess container using new containerd (1.7 alpha) with the working directory set it doesn't map to right location

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#112885]
### What happened?

If I have a container with the following:

```
FROM mcr.microsoft.com/oss/kubernetes/windows-host-process-containers-base-image:v0.1.0

ENV PATH="C:\Windows\system32;C:\Windows;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;"
WORKDIR /debug

ADD ./wcnspectserv.exe /debug
```

and a yaml spec like:

```
      containers:
      - name: windowswcnspectserver
        image: ghcr.io/microsoft/wcnspect:latest
        command:
        - powershell.exe
        - -command
        - ./wcnspectserv.exe # can add `-p {num}` here to change server's port
 ```

This doesn't work since the container end up with the working directory of `c:\debug` and the binary is in c:\hpc\debug`. This behavoir works in containerd 1.6

 

### What did you expect to happen?

Backwards compat for HPC.

### How can we reproduce it (as minimally and precisely as possible)?

Install containerd nightly: https://github.com/kubernetes-sigs/sig-windows-tools/releases/tag/windows-containerd-nightly

Deploy https://github.com/microsoft/wcnspect/blob/main/manifest/wcnspectserv-daemon.yml

### Anything else we need to know?

/sig windows

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

1.24+

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>
containerd 1.7+ (alpha)

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
