### ISSUE TITLE
init Container does not restart on restarting mainContainer 

### ISSUE THREAD

**Issue by abu-siddique** [kubernetes/kubernetes#112815]
### What happened?

I am using init container to get rid of "read only file system error "  where i am copying configMap volume to an empty dir, after main container reads the empty dir i am deleting that empty dir

But when main container restarts it does not find the files in empty dir and hence my application is not started.

### What did you expect to happen?

when main container restarts it should restart first init container then main container 

### How can we reproduce it (as minimally and precisely as possible)?

init container should re trigger before starting main container 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by crikke** [comment]
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior
See this in documentation: 

>Each init container must exit successfully before the next container starts. If a container fails to start due to the runtime or exits with failure, it is retried according to the Pod restartPolicy. However, if the Pod restartPolicy is set to Always, the init containers use restartPolicy OnFailure.

So in order to restart initcontainer, you should set pod restartpolicy to OnFailure

**Comment by abu-siddique** [comment]
@crikke  https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior
here i guess  it is saying that if init container fails to start then kubelet will restart the init container  based on the restartPolicy of pod.(this is fine) 


However I had killed main container(after starts) intentionally by sending SIGTERM, SIGABRT, SIGBUS etc etc signals, but  kubelet is restarting the main container only.  It should re trigger the init container first

**Comment by crikke** [comment]
I was able to reproduce error with following:
```
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'cat /mnt/test/foo.txt && rm /mnt/test/foo.txt']
    volumeMounts:
    - name: testvol
      mountPath: /mnt/test
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'echo "TEST" > /mnt/test/foo.txt']
    volumeMounts:
    - name: "testvol"
      mountPath: "/mnt/test"
  volumes:
  - name: "testvol"
    emptyDir: {}
```
Doing kubectl log myapp-pod first time returns TEST, next time it returns `cat: can't open '/mnt/test/foo.txt': No such file or directory`
