### ISSUE TITLE
Kubectl rollout undo can cause unexpected config merges

### ISSUE THREAD

**Issue by Gikkman** [kubernetes/kubernetes#112911]
### What happened?

When applying a manifest after using `kubectl rollout undo`, some fields I've removed from my manifest is still present. 

The easiest way I've found to cause this is to create a base deployment, apply an update (that removes some fields), rollback the update, then apply the same (or very similar) update again. The first time you apply the update, the fields are removed as expected, but after the rollback, they are not.

### What did you expect to happen?

I'd expect the two usages of `kubectl apply` to behave similarly, either both keeps the environment variable around, or neither does. As it is right now, I don't think most would expect `kubectl rollout undo` to affect what they might be able to remove in the future. 

### How can we reproduce it (as minimally and precisely as possible)?

I've put together a scenario that showcases the issue:

First, we create a deployment (I'm using tags of nginx to indicate versions of my app). This one has an environment variable `new-feature-enabled` set to `no`, because we're currently working on this new feature so it is locked behind a feature toggle.

```
cat <<EOF | kubectl apply -f - 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: hello-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - env:
        - name: new-feature-enabled
          value: "no"
        image: nginx:1.22.0
        name: app
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
EOF
```

Then, we finish our new feature, builds a new image with a new tag, removes the `new-feature-enabled` env variable that blocks the feature, and applies:
```
cat <<EOF | kubectl apply -f - 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: hello-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.23.0
        name: app
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
EOF
```

When deployed, we see the environment variable dissapears and the new image version is used. But something wasn't quite alright with this new version so we decide to rollback:

```
kubectl rollout undo deployment/hello-app
```

This'll put us back on version `1.22.0` again, and the environment variable is back, as expected. So we fix the issue we had and builds a new image with a new tag. Updates the previous manifest we applied (the one without the env variable) and applies it again. 
```
cat <<EOF | kubectl apply -f - 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: hello-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.23.1
        name: app
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

EOF
```

However, when this rolls out, the environment variable `new-feature-enabled` is still present and set to `no`.

### Anything else we need to know?

When I was digging around during #112826 I came across this behavior. I am pretty sure this happens because  `kubectl rollout undo` creates a field manager (`manager: kubectl, operation: Update`) for all fields it handled when applying the previous manifest. Since the manager's signature is different (due to the operation field), the user isn't in control of the manager anymore. This causes fields the user intends to remove with future uses of `kubectl apply` to stick around.

So I think this is a similar series of events as #112826 . There's also another old issue #77058 that I am pretty sure tries to describe the same underlying chain of events.

## CSA vs SSA
This example is written using `client-side-apply`. But if you switch to using `server-side-apply` for all cases, you'll need to use `--force-conflicts` on the last apply. This will still however create the unintended environment variable, but at least the user gets a warning something might be off.

### Kubernetes version

<details>

```console
$ kubectl version
kubectl version                    
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/arm64"}

```

</details>

### Cloud provider

<details>
minikube version: v1.27.0
commit: 4243041b7a72319b9be7842a7d34b6767bbdac2b
</details>

### OS version

<details>

```console
Mac OS 12.4 (M1)
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

/sig api-machinery
/sig cli
