### ISSUE TITLE
State of a pod with multiple containers is not accurate in case of failure

### ISSUE THREAD

**Issue by ViBiOh** [kubernetes/kubernetes#113013]
### What happened?

I have a job that creates a pod with two containers.

One always succeed and another may fail sometimes. Here's a reduced `describe` output

```
Name:                 my-job
Status:               Failed
Containers:
  migrate:
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 12 Oct 2022 11:51:37 +0200
      Finished:     Wed, 12 Oct 2022 11:51:39 +0200
  cloud-sql-proxy:
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 12 Oct 2022 11:51:38 +0200
      Finished:     Wed, 12 Oct 2022 11:51:39 +0200
```

When getting pods with `kubectl get pods`, I got the following output.

```
> kubectl get pods
NAME                           READY   STATUS      RESTARTS   AGE
my-job                         0/2     Completed   0          7s
```

### What did you expect to happen?

In case of one container is in error, I want to see the `Error` status instead of `Completed`.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "my-job"
spec:
  backoffLimit: 0

  template:
    spec:
      shareProcessNamespace: true
      restartPolicy: Never

      containers:
        - name: proxy
          image: alpine

          command:
            - /bin/sh
          args:
            - "-c"
            - "sleep 2; exit 2"

        - name: migrate
          image: alpine

          command:
            - /bin/sh
          args:
            - "-c"
            - "sleep 2"
```

### Kubernetes version

<details>

```console
> kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.2+k3s1
```

</details>

### Cloud provider

<details>
none, k3s v1.25.2+k3s1
</details>

### OS version

<details>

```console
> uname -a
Darwin macbook 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
