### ISSUE TITLE
default value of nested object 

### ISSUE THREAD

**Issue by YCShen1010** [kubernetes/kubernetes#113110]
### What we found?

We found that the parent object will be pruned if we do not define this parent object when applying CR, even though the child object of it has a default value in CRD.
Here is an example of a csvInjector in NamespaceScope CR：

1. We set a default value for `.spec.CSVInjector.enable` to `true` in NSS CRD

   ```golang
   type CSVInjector struct {
	    // +kubebuilder:default:=true   <--marker in Golang code-->
	    Enable bool `json:"enable"`
    }
    ```
    ```yaml
    csvInjector:
      description: When CSVInjector is enabled, operator will inject the
      watch namespace list into operator csv.
      properties:
        enable:
          default: true   # <--default value in NSS CRD-->
          type: boolean
        required:
          - enable
        type: object
     ```

2. Create a NSS CR without `CSVInjector` field on new NSS CRD / no with with `CSVInjector` but `CSVInjector` is null
     ```yaml
     kind: NamespaceScope
     apiVersion: operator.ibm.com/v1
     metadata:
     name: namespacescope
     namespace: cs-2
     spec: {}
     ------------------------------
     kind: NamespaceScope
     apiVersion: operator.ibm.com/v1
     metadata:
     name: namespacescope
     namespace: cs-2
     spec:
         csvInjector: null
     ```
3. We get nothing created in CR eventually
     ```yaml
     kind: NamespaceScope
     apiVersion: operator.ibm.com/v1
     metadata:
     name: namespacescope
     namespace: cs-2
     spec: 
     ```

### What would you like to be added?

We hope that even if the required object is not defined in CR, it still can show up eventually because the default value of enable is true under its properties in CRD.
