### ISSUE TITLE
ValidatingWebhook not intercepting requests sent to /scale subresource

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#113187]
### What happened?

While configuring ValidatingWebhook to match incoming requests to the `/scale` subresource, the following configuration was used:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
webhooks:
- name: my-webhook.example.com
  rules:
  - operations: ["CREATE","UPDATE","DELETE","CONNECT"]
    apiGroups: ["autoscaling"]
    apiVersions: ["v1"]
    resources: ["deployments/scale"]
    scope: "*"
...
```

Corresponding `APIResource`:
```json
{                                             
  "name": "deployments/scale",                
  "singularName": "",                         
  "namespaced": true,                         
  "group": "autoscaling",                     
  "version": "v1",                            
  "kind": "Scale",                            
  "verbs": [                                  
    "get",                                    
    "patch",                                  
    "update"                                  
  ]                                           
}
```

Requests sent to the `/scale` subresource were not intercepted by the webhook, however when changing webhook to:
```yaml
...
  rules:
  - operations: ["CREATE","UPDATE","DELETE","CONNECT"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments/scale"]
    scope: "*"
...
```
resulted in it working correctly. 

### What did you expect to happen?

I expected it to match on:
```yaml
...
    apiGroups: ["autoscaling"]
    apiVersions: ["v1"]
    resources: ["deployments/scale"]
...
```
and not on:
```yaml
...
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments/scale"]
...
```
because the corresponding `APIResource` has `"group": "autoscaling"` and `"version": "v1"` 

### How can we reproduce it (as minimally and precisely as possible)?

Just create a validating webhook with the above-used configuration and try it with any admission webhook server.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:49:27Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

Running locally on a kind cluster

```console
$ kind version                                   
kind v0.14.0 go1.18.1 linux/amd64
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.3"
VERSION_ID="2022.3"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
$ uname -a
Linux kali 5.16.0-kali7-amd64 #1 SMP PREEMPT Debian 5.16.18-1kali1 (2022-04-01) x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
