### ISSUE TITLE
Cannot run patchesStrategicMerge on CRDs schema under Versions array

### ISSUE THREAD

**Issue by gaelgatelement** [kubernetes/kubernetes#113223]
### What happened?

When trying to use `patchesStrategicMerge` on CRD schema under `spec/versions` array, it fails and replace the whole array because it is missing a `mergeKey` and `patchStrategy` on `Versions`.

`patchesStrategicMerge` used to work with `spec.version` and `spec.validation` fields but those are now deprecated.

### What did you expect to happen?

`patchesStrategicMerge` should be usable with new `versions` array.

### How can we reproduce it (as minimally and precisely as possible)?

`base.yaml` : 
```yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foo.bug.local
spec:
  group: bug.local
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Foo is the Schema for the foos API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Foo
            type: object
            properties:
              bar:
                description: This should be present in the result
                type: object
              k8s:
                description: This field will be replaced by kustomize
```

`kustomization.yaml` : 
```yaml
resources:
- ./base.yaml

patchesStrategicMerge:
- |-
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: foo.bug.local
  spec:
    versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
                k8s:
                  description: This should be present in the result
                  type: string

```

`bar` is missing from result : `kustomize build bug/`
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foo.bug.local
spec:
  group: bug.local
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            k8s:
              description: This should be present in the result
              type: string

```

### Anything else we need to know?

This might be a breaking change, if people relies on `patchesStrategicMerge` to replace their CRDs versions content instead of adding/merging.

### Kubernetes version

All versions supporting `apiextensions.k8s.io/v1`.

### Cloud provider

--
