### ISSUE TITLE
Admission webhooks don't match changes on subresources like Scale

### ISSUE THREAD

**Issue by colega** [kubernetes/kubernetes#113594]
### What happened?

I have a statefulset with a label `colega.eu/webhook`:

`workload.yaml`:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workload
  labels:
    colega.eu/webhook: 'true'
spec:
  replicas: 1
  serviceName: workload
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      containers:
      - name: nothing
        image: alpine
        command: ["/bin/watch"]
        args: ["-t", "-n", "2", "date"]
```

And I've created a webhook for changes in `statefulsets` and `statefulsets/scale` that have that the `colega.eu/webhook=true` label:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook
webhooks:
- name: webhook.colega.eu
  clientConfig:
    service:
      name: something-that-does-not-exist
      namespace: default
      path: /webhook
      port: 443
  objectSelector:
    matchLabels:
      colega.eu/webhook: 'true'
  rules:
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    operations: ["UPDATE"]
    resources: ["statefulsets"]
    scope: Namespaced
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    operations: ["*"]
    resources: ["statefulsets/scale"]
    scope: '*'
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
```

When I try to update my statefulset, the webhook is called (and it fails as the webhook service doesn't exist):
```
$ kubectl patch statefulsets.apps workload --patch='{"spec": {"replicas": 2}}'
Error from server (InternalError): Internal error occurred: failed calling webhook "webhook.colega.eu": Post "https://something-that-does-not-exist.default.svc:443/webhook?timeout=10s": service "something-that-does-not-exist" not found
```

However, when I update it using `kubectl scale` subcommand it does not call the webhook:
```
$ kubectl scale statefulset workload --replicas 2                             
statefulset.apps/workload scaled
```

However, the statefulset's `spec.replicas` field is updated.

### What did you expect to happen?

I expected the `kubectl scale` command to also fail, as I'd expect the `statefulset/scale` subresource to have the same labels as the parent resource (because the subresource doesn't have labels). 

### How can we reproduce it (as minimally and precisely as possible)?

<details>

<summary>Click me to expand</summary>

```
$ cat workload.yaml 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workload
  labels:
    colega.eu/webhook: 'true'
spec:
  replicas: 1
  serviceName: workload
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      containers:
      - name: nothing
        image: alpine
        command: ["/bin/watch"]
        args: ["-t", "-n", "2", "date"]

$ cat webhook.yaml 
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook
webhooks:
- name: webhook.colega.eu
  clientConfig:
    service:
      name: something-that-does-not-exist
      namespace: default
      path: /webhook
      port: 443
  objectSelector:
    matchLabels:
      colega.eu/webhook: 'true'
  rules:
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    operations: ["UPDATE"]
    resources: ["statefulsets"]
    scope: Namespaced
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    operations: ["*"]
    resources: ["statefulsets/scale"]
    scope: '*'
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail

$ kubectl apply -f workload.yaml 
statefulset.apps/workload created

$ kubectl apply -f webhook.yaml 
validatingwebhookconfiguration.admissionregistration.k8s.io/webhook created

$ kubectl patch statefulsets.apps workload --patch='{"spec": {"replicas": 2}}'
Error from server (InternalError): Internal error occurred: failed calling webhook "webhook.colega.eu": Post "https://something-that-does-not-exist.default.svc:443/webhook?timeout=10s": service "something-that-does-not-exist" not found

$ kubectl scale statefulset workload --replicas 2
statefulset.apps/workload scaled
```
</details>

### Anything else we need to know?

I know that [the documentation states](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector) that:

> Use the object selector only if the webhook is opt-in, because end users may skip the admission webhook by setting the labels.

However, I'm not trying to prevent users from skipping the webhook here, I'm trying to catch changes to legitimately opted-in statefulsets replicas.

I can't see any way of creating a webhook without removing the label matchers on it (which would be highly undesired as there are a lot of objects that I don't want to validate in our clusters) and manually (from the webhook) accessing the deployment through the API when the validating request arrives to check whether it contains or not the labels.

### Kubernetes version

<details>

```console
$ kubectl version  
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

None, I'm testing locally.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal

$ uname -a
Linux beast 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

**Comment by jpbetz** [comment]
Use `apiGroups: ["autoscaling"]` for the scale subresource? Also note is has both a v1 and v2 API (but matchType=Equivalent, which is the default, should be enough to match)

**Comment by colega** [comment]
I just tried with this rule:
```
  - apiGroups: ["autoscaling"]
    apiVersions: ["v1"]
    operations: ["*"]
    resources: ["*"]
    scope: '*'
```

And even with no `objectSelectors`, the webhook isn't being called when `kubectl scale` operation is applied. (I even tried with `*` as apiVersions, with no luck).

I can see that `autoscaling/v1/Scale` does have the ObjectMeta in it, and it would be great to see it being checked in the scale operation.

**Comment by jpbetz** [comment]
`resources: ["*/scale"]` ?  I'll need to try this out locally as well..

**Comment by colega** [comment]
Thank you for the quick response, but that didn't work neither.

**Comment by jpbetz** [comment]
Tried this locally and I understand what is going on.

Apologies for my earlier suggestions. There were going in the wrong direction.

Changes to the autoscaling subresources are matched based on the apiGroup and apiVersion of the resource.  For example:

```
       - apiGroups:   ["apps"]                                                                                                                                                                                                                                          
         apiVersions: ["*"]                                                                                                                                                                                                                                             
         operations:  ["CREATE", "UPDATE"]                                                                                                                                                                                                                              
         resources:   ["*/scale"]   
```

Matches the subresource of a deployment, which can be validated  by using:

```
kubectl scale deploy/nginx-deployment --replicas=2
```

The problem with the original example in this issue is that the request to change scale was made to the statefulset resource directly, and not to the scale subresource of the statefulset.

A webhook that intends to intercept all changes to scale would need to match both the root resource and the scale subresource in a case like this, and handle both, since the scale fields exist in both resources.

**Comment by colega** [comment]
Hey, @jpbetz can you please share your entire webhook definition? There's something I'm still missing, I tried with:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook
webhooks:
- name: webhook.colega.eu
  clientConfig:
    service:
      name: something-that-does-not-exist
      namespace: default
      path: /webhook
      port: 443
  objectSelector:
    matchLabels:
      colega.eu/webhook: 'true'
  rules:
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    operations: ["UPDATE"]
    resources: ["statefulsets"]
    scope: Namespaced
  - apiGroups: ["apps"]
    apiVersions: ["*"]
    operations: ["CREATE", "UPDATE"]
    resources: ["*/scale"]
    scope: Namespaced
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
```

And then
```
$ kubectl scale statefulset workload --replicas 3
statefulset.apps/workload scaled
```

Which succeeds (but it shouldn't, as it should call the non-existent webhook).

> The problem with the original example in this issue is that the request to change scale was made to the statefulset resource directly, and not to the scale subresource of the statefulset.

I didn't understand this. I always tried with `kubectl scale statefulset ...`, doesn't that modify the scale subresource?

In order to ensure we're on the same page, just to be clear: the _problem_ for me is that the request _succeeds_, as it shouln't because the webhook endpoint doesn't exist.
