### ISSUE TITLE
kubelet: volumeManager.WaitForUnmount does not wait for emptydir to be unmounted sucessfuly

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#113563]
### What happened?

Kubelet has an internal `syncTerminatedPod` which is called after pods are terminated. The function is responsible for some final pod cleanup and is responsible to ensure that volumes mounted to the pod are unmounted.  The function calls `volumeManager.WaitForUnmount`:

https://github.com/kubernetes/kubernetes/blob/7d9c0e0a78e519cac0f892a8be2f063bedc94bad/pkg/kubelet/kubelet.go#L1881-L1885

As part of testing a different bug, I came across an issue with emptydir handling of unmounting -- it looks like that `volumeManager.WaitForUnmount` will return true if even if the empty dir was not unmounted successfully. 

Chatted with @msau42, it seems this is because, during `WaitForUnmount`, it is checking for mounted state:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/cache/actual_state_of_world.go#L965

However, if there is an error during unmounting the volume is marked as  "uncertain", which results in `WaitForUnmount` succeeding despite an error during unmounting. 

### What did you expect to happen?

I expected that `volumeManager.WaitForUnmount` will block (or return error) if the emptydir was had an error unmounting.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a kind cluster (I used v1.25.2 node image)

```
kind_config="$(cat << EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
nodes:
# the control plane node
- role: control-plane
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "4"
EOF
)"

kind create cluster --config <(printf '%s\n' "${kind_config}") --image kindest/node:v1.25.2@sha256:9be91e9e9cdf116809841fc77ebdb8845443c4c72fe5218f3ae9eb57fdb4bace
```

Create the following pod:

```
# test-pd.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "999999"
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
```

```
$ kubectl apply -f test-emptydir.yaml
```

Get the pod uid
```
$ kubectl get pod test-pd -o json | jq .metadata.uid
"5a8ef092-2173-4175-9557-947b73f9a8f9"
```

Enter the kind-worker (node) and do a `chattr +i` on the emtpydir. This will make the emptydir volume immutable and prevent it from being unmounted (and deleted).

```
$ docker exec -it kind-worker /bin/bash
root@kind-worker:/# cd /var/lib/kubelet/pods/5a8ef092-2173-4175-9557-947b73f9a8f9/volumes/kubernetes.io~empty-dir
root@kind-worker:/var/lib/kubelet/pods/5a8ef092-2173-4175-9557-947b73f9a8f9/volumes/kubernetes.io~empty-dir#
root@kind-worker:/var/lib/kubelet/pods/5a8ef092-2173-4175-9557-947b73f9a8f9/volumes/kubernetes.io~empty-dir# chattr +i cache-volume/
root@kind-worker:/var/lib/kubelet/pods/5a8ef092-2173-4175-9557-947b73f9a8f9/volumes/kubernetes.io~empty-dir# lsattr
----i---------e------- ./cache-volume
```

Now delete, the pod:
```
kubectl delete pod  test-pd --grace-period=5
```

Here's the logs:

Kubelet logs - https://gist.github.com/4f9b1fa0edda8d260c90a1f18c9dc6e5
Kubelet logs for test-pd pod: https://gist.github.com/d63b8713b71bef1e712ca138fcb5d602

### Kubernetes version

1.25.2

### Cloud provider

n/a

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
