### ISSUE TITLE
Containers with readinessProbe become not ready when kubelet restart

### ISSUE THREAD

**Issue by luozhiwenn** [kubernetes/kubernetes#113646]
### What happened?

Containers with readinessProbe become not ready for a period of time when kubelet restart, then it'll be ready again soon.

### What did you expect to happen?

The container status should remain ready when the kubelet restarts.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Pod with readinessProbe

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-test-1
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: docker.io/library/busyboxbase:latest
    imagePullPolicy: IfNotPresent
    name: busybox
    readinessProbe:
      exec:
        command:
        - sleep
        - "1"
```

2. Restart the kubelet process on the node where the pod resides
3. The container status changes from Ready to NotReady and then back to Ready for a short period of time.
```
[root@master ~]# kubectl get pod -w
busybox-test-1   1/1     Running   0              3m48s
busybox-test-1   0/1     Running   0              4m
busybox-test-1   1/1     Running   0              4m1s
```

### Kubernetes version

<details>

```console
$ kubectl version
v1.25.3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
