### ISSUE TITLE
HPA based on External metrics fails on label validation

### ISSUE THREAD

**Issue by vbshnsk** [kubernetes/kubernetes#113673]
### What happened?

We deploy an application with an autoscaler, that needs to be based on number of unacked messages in the queue. This is `hpa.yaml` file. `<topic-name>` and `<subscription>` both refer to placeholder values:

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: deployment
  namespace: deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment-type
    name: deployment
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - external:
      metric:
        name: pubsub.googleapis.com|subscription|num_undelivered_messages
        selector:
          matchLabels:
            resource.labels.subscription_id: <topic-name>+<subscription>
      target:
        type: AverageValue
        averageValue: 30
    type: External
```

The autoscaler, later on, complains:

```
Conditions:
  Type            Status  Reason                   Message
  ----            ------  ------                   -------
  AbleToScale     True    ReadyForNewScale         recommended size matches current size
  ScalingActive   False   FailedGetExternalMetric  the HPA was unable to compute the replica count: invalid label value: "<topic-name>+<subscription>": at key: "resource.labels.subscription_id": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
  ScalingLimited  False   DesiredWithinRange       the desired count is within the acceptable range
Events:
  Type     Reason                   Age                   From                       Message
  ----     ------                   ----                  ----                       -------
  Warning  FailedGetExternalMetric  12s (x4652 over 21h)  horizontal-pod-autoscaler  invalid label value: "<topic-name>+<subscription>": at key: "resource.labels.subscription_id": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

The format `<topic-name>+<subscription>` seems to be unacceptable because of the `+` sign, even though is a valid name for a Google Pub/Sub subscription

### What did you expect to happen?

Autoscaler needs to accept an External Metric label value with relaxed validation because those can be different for the metric providers. In this case, Google Pub/Sub allows you to name your subscription with a `+` character, but validation fails while deploying, rendering scaling based on it impossible. We use this naming conventionally across our organization, so it does not seem plausible to change the naming.

### How can we reproduce it (as minimally and precisely as possible)?

Use the `+` character for the string inside the `matchLabels` label value.

### Kubernetes version

<details>

1.21.14-gke.4300

</details>

### Cloud provider

<details>
GCP (GKE)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
