### ISSUE TITLE
Proposal: Add status.data in `Job/CronJob` to pass job output

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#113641]
### What would you like to be added?

Currently, the status section in `Job/CronJob` workload contains fields `succeeded/active/failed`, etc.
But usually we need the job to pass the output data, to let us do more logic rely on the result data.

So propose to add `status.data` in `Job/CronJob` to pass the job output, the data field type could be a string, then it can support more complex json string.

Demo:
```
apiVersion: batch/v1
kind: Job
...
status:
  completionTime: "2022-11-04T15:38:37Z"
  startTime: "2022-11-04T15:37:14Z"
  succeeded: 1
  data: '{"repo":"my-repo","imageTag":"v1.4.4-24.g5e8cc5be"}' // output data
```

### Why is this needed?

Usually, we run a job A, then run a controller or a script which need the job output data to do more logic.
But currently the `Job/CronJob` status does not support data output, so propose to add `status.data` to achieve it.
