### ISSUE TITLE
StatefulSet ignores OnDelete update strategy

### ISSUE THREAD

**Issue by alekseevx** [kubernetes/kubernetes#113880]
### What happened?

According to the official documentation https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies, when using the OnDelete strategy, the update of the pods should be done when the user deletes the pod. However, I found a case where StatefulSet tries to update volumes of an existing pod.

It is also worth noting that if StatefulSet gets an error when trying to update volumes in an existing pod (e.g. because the Volume field cannot be changed in an existing pod), StatefulSet will interrupt service to other pods.

### What did you expect to happen?

When using the OnDelete strategy, the StatefulSet will update the pod only when the pod is deleted.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an instance of StatefulSet without PVC and wait until all pods are created
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-sts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-pod
  serviceName: ""
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
        - name: test-container
          image: busybox
          command:
            - sleep
            - "3600"
          imagePullPolicy: IfNotPresent
  updateStrategy:
    type: OnDelete
```
2. Delete the created StatefulSet, but leave its pods
```shell
kubectl delete sts/test-sts --cascade=orphan
```

3. Create a new StatefulSet with PVC, for example
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-sts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-pod
  serviceName: ""
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
        - name: test-container
          image: busybox
          command:
            - sleep
            - "3600"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /mnt
              name: data
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 200Mi
        storageClassName: standard
        volumeMode: Filesystem
```
4. Get information about the StatefulSet
```shell
kubectl describe sts/test-sts
```
and see that StatefulSet tried to update an existing sub, but got an error:
```
Name:               test-sts
Namespace:          default
CreationTimestamp:  Mon, 14 Nov 2022 10:17:57 +0300
Selector:           app=test-pod
Labels:             <none>
Annotations:        <none>
Replicas:           3 desired | 3 total
Update Strategy:    OnDelete
Pods Status:        3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=test-pod
  Containers:
   test-container:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Command:
      sleep
      3600
    Environment:  <none>
    Mounts:
      /mnt from data (rw)
  Volumes:  <none>
Volume Claims:
  Name:          data
  StorageClass:  standard
  Labels:        <none>
  Annotations:   <none>
  Capacity:      200Mi
  Access Modes:  [ReadWriteOnce]
Events:
  Type     Reason            Age                   From                    Message
  ----     ------            ----                  ----                    -------
  Normal   SuccessfulCreate  13m                   statefulset-controller  create Claim data-test-sts-0 Pod test-sts-0 in StatefulSet test-sts success
  Warning  FailedUpdate      2m45s (x18 over 13m)  statefulset-controller  update Pod test-sts-0 in StatefulSet test-sts failed error: Pod "test-sts-0" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds`, `spec.tolerations` (only additions to existing tolerations) or `spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
  core.PodSpec{
    Volumes: []core.Volume{
+     {
+       Name: "data",
+       VolumeSource: core.VolumeSource{
+         PersistentVolumeClaim: &core.PersistentVolumeClaimVolumeSource{ClaimName: "data-test-sts-0"},
+       },
+     },
      {Name: "kube-api-access-sb9gt", VolumeSource: {Projected: &{Sources: {{ServiceAccountToken: &{ExpirationSeconds: 3607, Path: "token"}}, {ConfigMap: &{LocalObjectReference: {Name: "kube-root-ca.crt"}, Items: {{Key: "ca.crt", Path: "ca.crt"}}}}, {DownwardAPI: &{Items: {{Path: "namespace", FieldRef: &{APIVersion: "v1", FieldPath: "metadata.namespace"}}}}}}, DefaultMode: &420}}},
    },
    InitContainers: nil,
    Containers:     {{Name: "test-container", Image: "busybox", Command: {"sleep", "3600"}, VolumeMounts: {{Name: "kube-api-access-sb9gt", ReadOnly: true, MountPath: "/var/run/secrets/kubernetes.io/serviceaccount"}}, ...}},
    ... // 28 identical fields
  }
```

### Anything else we need to know?

Presumably the problem in the call `(spc *StatefulPodControl) UpdateStatefulPod`
```golang
		replica := replicas[i].DeepCopy()
		if err := ssc.podControl.UpdateStatefulPod(updateSet, replica); err != nil {
			return &status, err
		}
```

in the method `func (ssc *defaultStatefulSetControl) updateStatefulSet`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
