### ISSUE TITLE
Prometheus fails to proxy /metrics or /metrics/cadvisor in v1.24.8

### ISSUE THREAD

**Issue by jilleJr** [kubernetes/kubernetes#114073]
### What happened?

Updated to Kubernetes v1.24.8, and Prometheus was no longer able to collect metrics from one of the control-plane nodes.

Our Prometheus config asking `kubernetes.default.svc:443` with URL path `/api/v1/nodes/${1}/proxy/metrics`, where `${1}` is replaced by each of the node names.

It is able to read metrics via this proxying from all of the nodes, except for the node its talking to. I found out that this is because of this code which does a lookup of the DNS name and checks [IsGlobalUnicast()](https://pkg.go.dev/net#IP.IsGlobalUnicast) and then rejects it: https://github.com/kubernetes/kubernetes/blob/v1.24.8/pkg/proxy/util/utils.go#L130-L159

On our nodes, the node name resolves to `127.0.1.1`, which fails the if-statement and then returns "BadRequest".

### What did you expect to happen?

That reading metrics work, both regular /metrics, but also /metrics/cadvisor

### How can we reproduce it (as minimally and precisely as possible)?

For example, let's say we have 3 nodes: a.example.com, b.example.com, and c.example.com:

```console
$ kubectl get nodes
NAME            STATUS   ROLES    AGE    VERSION
a.example.com   Ready    <none>   110d   v1.24.8
b.example.com   Ready    <none>   110d   v1.24.8
c.example.com   Ready    <none>   110d   v1.24.8
```

Reading the metrics across nodes works fine:

```console
$ kubectl get --raw /api/v1/nodes/b.example.com/proxy/metrics --server https://a.example.com:6443 | wc
   1263    4424  125572

$ kubectl get --raw /api/v1/nodes/c.example.com/proxy/metrics --server https://a.example.com:6443 | wc
   1265    4428  125782
```

But trying to proxy from node A to node A fails:

```console
$ kubectl get --raw /api/v1/nodes/a.example.com/proxy/metrics --server https://a.example.com:6443 | wc
Error from server (BadRequest): address not allowed
      0       0       0
```

### Anything else we need to know?

Related CVE fix mentioned in release notes: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#cve-2022-3294-node-address-isnt-always-verified-when-proxying

Related PR: https://github.com/kubernetes/kubernetes/pull/113681

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

Self hosted. We run k8s nodes on a mix of VMs and on bare metal.

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux vm017.(redacted) 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

N/A

</details>

### Container runtime (CRI) and version (if applicable)

<details>

containerd: 1.6.10
crictl: 1.24.2
runc: 1.1.4
etcd: 3.5.4

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

coredns: 1.9.3
CSI: openebs: 3.3.0
CNI: calico: v3.23.3

</details>

**Comment by aimuz** [comment]
/sig node

Can you try it like this?

```
kubectl get --raw /api/v1/nodes/a.example.com/proxy/metrics --server https://$master-ip:6443 | wc
```

**Comment by jilleJr** [comment]
@aimuz Sure! Same results:

```console
$ kubectl get --raw /api/v1/nodes/a.example.com/proxy/metrics --server https://10.1.2.3:6443 | wc
Error from server (BadRequest): address not allowed
      0       0       0

$ kubectl get --raw /api/v1/nodes/10.1.2.3/proxy/metrics --server https://a.example.com:6443 | wc
Error from server (NotFound): nodes "10.1.2.3" not found
      0       0       0
```

**Comment by aimuz** [comment]
Does your api certificate contain this address?

**Comment by jilleJr** [comment]
@aimuz Yes. Both the IP's and the hostnames

```console
$ echo | openssl s_client -connect a.example.com:6443 | openssl x509 -noout -text
...snip...
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster, DNS:kubernetes.svc.cluster.local, DNS:vm019, DNS:a.example.com, DNS:kubeapi.our-internal-cluster-name.example.com, IP Address:10.1.2.3, IP Address:10.1.2.201, IP Address:127.0.0.1, IP Address:10.32.0.1
...snip...
```

**Comment by aimuz** [comment]
Can I execute the following command?

```
kubectl get node -o wide
```

Execute on host A B C separately
```
nslookup a.example.com
```

Execute on host A B C separately
```
kubectl get --raw /api/v1/nodes/a.example.com/proxy/metrics | wc
```

**Comment by aojea** [comment]
https://github.com/kubernetes/kubernetes/issues/113757

**Comment by aojea** [comment]
> the node name resolves to 127.0.1.1, 

then it is working as expected, meanwhile the hostname doesn't resolve to a global ip it will fail

**Comment by jilleJr** [comment]
@aimuz Here you go:

```console
$ kubectl get nodes -o wide
NAME               STATUS   ROLES    AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
a.example.com      Ready    <none>   111d   v1.24.8   10.1.2.3      <none>        Ubuntu 20.04.4 LTS   5.4.0-122-generic   containerd://1.6.10
b.example.com      Ready    <none>   111d   v1.24.8   10.1.2.4      <none>        Ubuntu 20.04.4 LTS   5.4.0-122-generic   containerd://1.6.10
c.example.com      Ready    <none>   111d   v1.24.8   10.1.2.5      <none>        Ubuntu 20.04.4 LTS   5.4.0-122-generic   containerd://1.6.10

root@a:~$ nslookup a.example.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	a.example.com
Address: 127.0.1.1

root@b:~$ nslookup a.example.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	a.example.com
Address: 10.1.2.3

root@c:~$ nslookup a.example.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	a.example.com
Address: 10.1.2.3
```

> @aojea 
> > the node name resolves to 127.0.1.1,
> 
> then it is working as expected, meanwhile the hostname doesn't resolve to a global ip it will fail

But do you have any ideas on getting around this?

We're using the following Prometheus config, which relies on proxying to obtain metrics from the different nodes:

```yaml
scrape_configs:
  - job_name: kubernetes-nodes
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics

  - job_name: kubernetes-cadvisor
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
```

I did not create the above scrape config, so I don't know the origin of it, but I am finding something similar at https://www.cloudforecast.io/blog/cadvisor-and-kubernetes-monitoring-guide/

However I also found this blog post where they use port 10250 instead, and are able to access /metrics and /metrics/cadvisor: https://www.digitalocean.com/community/questions/cadvisor-on-prometheus-with-kubernetes

Testing it and it works!

```console
$ kubectl get --raw /metrics --server https://a.example.com:10250 | wc
   1263    4424  125876

$ kubectl get --raw /metrics/cadvisor --server https://a.example.com:10250 | wc
    962    3324  181578
```

**Comment by jilleJr** [comment]
Yep confirmed, changing the /metrics/cadvisor scraper to this worked:

```yaml
    - job_name: kubernetes-cadvisor
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - source_labels: [__address__]
        target_label: __address__
        regex: ([^:]+)(?::\d+)?
        replacement: $1:10250
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /metrics/cadvisor
```

I also had to add `nodes/metrics` permission to Prometheus' ClusterRole, as it got 401 error otherwise:

```diff
 kind: ClusterRole
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: prometheus
 rules:
   - apiGroups:
     - ""
     resources:
     - nodes
     - nodes/proxy
+    - nodes/metrics
     - services
     - endpoints
     - pods
     verbs:
     - "get"
     - "list"
     - "watch"
```

Sorry for the trouble, and thanks for the help in debugging this!

Kind regards,
