### ISSUE TITLE
Terminating Pods will get their empty dir volumes unmounted when kubelet restarts

### ISSUE THREAD

**Issue by FullyScaled** [kubernetes/kubernetes#114047]
### What happened?

Workloads which do not shutdown instantly on SIGTERM but start a graceful shutdown behavior to delay the shutdown of the container for some additional time will be in the Pod-Phase "Terminating" after the SIGTERM was received.

If the kubelet on a node that hosts such a "Terminating" pod is restarted (e.g. during k8s version patching) mounted emptydir volumes will be unmounted and not added to the pod again. As a consequence there will no directory be mounted under the configured mount path.

### What did you expect to happen?

Terminating Pods (which can be basically fully operational workloads) should not end up with removed emptydir volumes and missing mounted directories when the kubelet restarts. Mounted emptydir volumes should behave just like pvcs.

### How can we reproduce it (as minimally and precisely as possible)?

Example Pod with both (empty dir + pvc):

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copy-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ed-pod
spec:
  containers:
    - name: worker
      image: eu.gcr.io/gardener-project/gardener/ops-toolbelt:latest
      command:
        - bash 
        - -c
        - while true; do echo $(date); sleep 5d; done
      volumeMounts:
      - mountPath: /var/tmp/data
        name: worker-data
      - mountPath: "/copy"
        name: copy-vol
  terminationGracePeriodSeconds: 3600
  volumes:
  - emptyDir: {}
    name: worker-data
  - name: copy-vol
    persistentVolumeClaim:
      claimName: copy-pvc
```

- Deploy sample pod
- Send SIGTERM to pod, pod should be in "Terminating" now
- Restart Kubelet
- Check directory /var/tmp/data (try creating a new file there)

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/blob/d6260cf1df957cf7155e1dae5818e949e9b169bd/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L170-L184

The check whether to add volumes to the desired state is still on [whether termination has been requested](https://github.com/kubernetes/kubernetes/blob/e4f776f23098ecf942cafa898777195adbc800f1/pkg/kubelet/pod_workers.go#L393) (status: terminating) (not whether termination has been successful).

### Kubernetes version

<details>

```console
$ kubectl version
1.23.x
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
