### ISSUE TITLE
Only Metadata level audit logging is required for Kubernetes

### ISSUE THREAD

**Issue by kavita1205** [kubernetes/kubernetes#114069]
### What happened?

Hi Team,

I am trying to get k8 audit logs only for level "Metadata" but I am logs for level "Request" and "RequestResponse". I tried multiple combinations to achieve the same but no luck. Also, followed K8 audit documentation but seems it's not helpful. Although they have mentioned to pull only metadata level logs but in my case it is pulling other level logs too

I am using below configurations 

```
apiVersion: audit.k8s.io/v1
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"
  - "RequestResponse"
  - "Request"
  - "ResponseStarted"
  - "ResponseComplete"
rules:
  # The following requests were manually identified as high-volume and low-risk,
  # so drop them.
  - level: None
    resources:
      - group: ""
        resources:
          - endpoints
          - services
          - services/status
          - pods
    users:
      - "system:kube-proxy"
      - "system:nodes"
      - "system:kube-scheduler"
      - "system:apiserver"
      - "system:kube-controller-manager"
      - "system:authenticated"
      - "system:anonymous"
      - "system:serviceaccounts"
      - "system:serviceaccounts:controller-xperi-k8s"
      - "system:serviceaccount:controller-xperi-k8s:controller"
    verbs:
      - watch
      - get
      - list
      - update

  # Don't log authenticated requests to certain non-resource URL paths.
  - level: None
    userGroups: 
      - "system:kube-proxy"
      - "system:nodes"
      - "system:kube-scheduler"
      - "system:apiserver"
      - "system:kube-controller-manager"
      - "system:authenticated"
      - "system:anonymous"
      - "system:serviceaccounts"
      - "system:serviceaccounts:controller-xperi-k8s"
      - "system:serviceaccount:controller-xperi-k8s:controller"
    nonResourceURLs:
    - "/api*" # Wildcard matching.
    - "/version"
    
  # Secrets, ConfigMap, so only log at the Metadata level.
  - level: Metadata
    omitStages:
      - RequestReceived
    resources:
      - group: ""
        resources:
          - secrets
          - configmaps

  # Default level for all other requests.
  - level: Metadata
    omitStages:
      - RequestReceived

```

### What did you expect to happen?

Don't want to get logs of level "Request" and "RequestResponse"

### How can we reproduce it (as minimally and precisely as possible)?

you can use my policy configuation.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.24.6

</details>

### Cloud provider

<details>
On-prem
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
