### ISSUE TITLE
Topology Aware Infrastructure Disruptions for Statefulsets

### ISSUE THREAD

**Issue by null-sleep** [kubernetes/kubernetes#114010]
### What would you like to be added?

Add the following features to the StatefulSet API for Kubernetes to make the management of stateful apps easier:
1. The ability to rollout pods by zone for a Statefulset.
2. Allow PDBs to have budget of disruptions per zone for a Statefulset.

### Why is this needed?

A key focus of most stateful applications is data availability and consistency. In service of this, many stateful applications replicate data and often have these replicas spread across multiple zones. Due to this zonal replication, these apps can often tolerate the disruptions of several pods if limited to the same zone.

We propose Kubernetes should provide native features to allow users to take advantage of the zonal replication for stateful apps when performing any kind of planned disruption ex. rollouts or node upgrades.

The two features we thing can have a high impact on easing the management of such applications are:
1. The ability to rollout pods by zone for a Statefulset.
2. Allow PDBs to have budget of disruptions per zone for a Statefulset.

**The aim for both these features is to speed up deployment times without having an impact on availability.**

There are several popular apps: Kafka, Zookeeper, Redis, Elastisearch, TiKV, Cortex to name a few which would benefit from the addition of these features to Kubernetes (one would expect most distributed apps should). These apps often support zonal replicas by using some kind of topology or rack aware setting in their configuration.

Ideally these are native features in Kubernetes that can be developed to be robust, generic and be of use to several stateful apps.

**More context for the proposal is captured in this public [doc here](https://docs.google.com/document/d/1mnV1D_2qz3iYjnMzEUuLFjW9Oi4Kw0Qtz_B1Nup8FlU/edit#heading=h.u7jfy9wqpd2b)**
**Similar requests have been made in the past:** https://github.com/kubernetes/kubernetes/issues/104583

#### Current attempts at solving the problem
The current way most teams support such features is by writing custom operators. These operator are either designed to be generic which is how we solve this at Shopify and thanks to @marianafranco it seems AWS seems to do the same. Or these features get baked into existing operators written to manage apps.

Another pattern we have seen, sometimes in conjunction with a custom operator is to have multiple Statefulset definitions for a single logical app, with each Statefulset definition restricting pods to a single zone.

### A simple case study of speeding up rollouts for Kafka using a custom operator at Shopify

Kafka is distributed event store, deployed as a Statefulset on Kubernetes. Users can read/write oredered events from a topics which are further made up of partitions. Kafka performs replication at this partition level.

Kafka like many other apps is rack/topology aware and spreads the partition replicas across the available zones. We usually have 3 replicas for each partition spread across 3 zones.

And so, if 3 or more pods are down at random we run the risk of data loss and unavailable partitions. So for deploys we were limited to the default behaviour provided for `RollingRestart` of updating one pod at a time. This strategy worked for small clusters with less than 10 pods, but for our larger cluster with over 200 pods, deploys could easily take 20+ hours.

We realized we could significantly speed up the deploy process by updating multiple pods at the same time as long as they were part of the same zone. We could tolerate a single replica being unavailable for planned disruptions like rollouts and still keep the minimum quorum of 2.

To support this "zonal rollout" of a StatefulApp we built a custom controller, designed to be generic. The deploys for our largest clusters now take ~20 min on average, down from 20 hours.

Besides the operational win of being able to deploy rapidly and safely within working hours for Kafka, there are other motivating factors specific to Kafka which motivate faster rollouts. Ex. Kafka consumer groups which read from a topic in parallel (a topic is made of multiple partitions, which can be read from in parallel to maximize throughput) are sensitive to to changes in partitions status. These changes often cause the entire group to stop reading, rebalance and resume work. During a Kafka rollout, a smaller time window of disruption is preferred to minimize time wasted by these consumer groups rebalancing due to pod restarts.

The [AWS use case for Cortex](https://aws.amazon.com/blogs/opensource/speed-up-highly-available-deployments-on-kubernetes/) is another case study to consider and reads quite similarly to this one.

#### What does the operator look like?

The zonal deploy operator is written using the [Kubebuilder SDK](https://book.kubebuilder.io/). At a high level:
- The operator watches a single Statefulset for a change in revision and triggers a rollout on a new revision.
- The StatefulSets is deployed using the `OnDelete` strategy.
- Pods are always updates in the same order. This helps with rollbacks or fix it forward updates so the most recently updated pods can be updated first.
- All pods in a zone are updated at the same time. I would imagine further control of how many pods in that zone should be restarted at a time (ex. 30% of pods) would be a useful configuration to have.
- We rely on the `readinessProbe` for the updated pod to signal that is running and successfully updated. For Kafka this check returns true once that pod is "caught up" with replication of data.
- If pods are unhealthy after restarting a zone, the operator does not make any further progress.
- The operator can be paused to stop an in progress deploy, similar to how [`Deployments` can be paused in Kubernetes](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pausing-and-resuming-a-deployment).

[From the same AWS use case](https://aws.amazon.com/blogs/opensource/speed-up-highly-available-deployments-on-kubernetes/), they seem to have implemented and open sourced their own operator which is very similar.

It is worth noting that for Kafka's use case, restarting all pods in a zone works. For many apps it woud be useful to have an option like `MaxUnavailable` to control how many pods should be restarted within a zone. Most would expect this to mean if `MaxUnavailable` for that zone is 5, then 5 pods can be restarted in parallel but the AWS controller went with an exponential approach to updating pods until the configured `MaxUnavailable` value for the zone is reached.

### What would such improvements look like for zonal rollouts?

To add support for the ability to rollout pods by zone for a Statefulset, I think these are the key semantics:
- Zones and the pods within them are always updated in the same order (ex. alphabetical).
- All pods in a zone have to be updated before moving to the next zone.
- Make good use of the `readinessProbe`. This gives the pod/application the flexibility to signal the health of that pod or the application as a whole and provides the application control over the conditions to continue with the rollout. Or run any custom commands, etc... if needed.
- If pods are unhealthy after restarting them in a zone, the controller stalls.
- Ability to pause rollouts like with [deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pausing-and-resuming-a-deployment).

What could the API changes possibly look like:

1. Add a new `updateStrategy: ZonalUpdate` with the ability to define what label to use for zone information.

```
apiVersion: apps/v1
kind: StatefulSet
spec:
  paused: false
  replicas: 100
  serviceName: kafka
  podManagementPolicy: Parallel
  updateStrategy:
    type: ZonalUpdate
    zonalUpdate:
      maxUnavailable: 5
      topologyKey: topology.kubernetes.io/zone
  template:
```

2. Similar to the first option. Be more explicit with `maxUnavailablePerZone` and allow configuration on how zones may be picked `alphabetical`

```
apiVersion: apps/v1
kind: StatefulSet
spec:
  paused: false
  replicas: 100
  serviceName: kafka
  podManagementPolicy: Parallel
  updateStrategy:
    type: ZonalUpdate
    zonalUpdate:
      maxUnavailablePerZone: 25%
      zoneOrder: alphabetical
      topologyKey: topology.kubernetes.io/zone
  template:
```

3. Expand the existing `RollingUpdate` configuration to support a label selector which can be the zone.

```
apiVersion: apps/v1
kind: StatefulSet
spec:
  paused: false
  replicas: 100
  serviceName: kafka
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      partitionType: Ordinal | Label Selector
      partition: topology.kubernetes.io/zone
  template:
```
