### ISSUE TITLE
Annnotation updates on LoadBalancer service are not propagated to corresponding AWS LoadBalancer listener

### ISSUE THREAD

**Issue by yogeek** [kubernetes/kubernetes#114111]
### What happened?

I have 1 "type=loadbalancer" service with the following annotations
```
serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Name=k8s-istio-nlb-internal,Project=Test,Application=K8S"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${CERT_ARN}"
          service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "${SSL_NEGO_POLICY}"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "${SSL_PORT}"
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "${BACKEND_PROTO}"
```

I want to set the ALPN policy, so I add the following annotation : 
```
          service.beta.kubernetes.io/aws-load-balancer-alpn-policy: "HTTP2Preferred"
```

But no change is propagated to the AWS LoadBalancer listener

(same goes with a tag modification)

### What did you expect to happen?

Updating service annotation should update the AWS LoadBalancer

### How can we reproduce it (as minimally and precisely as possible)?

Add  or update an annotation on a K8S LoadBalancer Service and check in AWS that the change is not applied.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15", GitCommit:"1d79bc3bcccfba7466c44cc2055d6e7442e140ea", GitTreeState:"clean", BuildDate:"2022-09-21T12:18:10Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15", GitCommit:"1d79bc3bcccfba7466c44cc2055d6e7442e140ea", GitTreeState:"clean", BuildDate:"2022-09-21T12:12:26Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### Install tools

<details>
kubeadm on AWS EC2
</details>
