### ISSUE TITLE
kubelet managed /etc/hosts content is not synced when changes are made in initContainers

### ISSUE THREAD

**Issue by levimm** [kubernetes/kubernetes#114206]
### What happened?

I have the requirement to dynamically add some content in `/etc/hosts` for the pod (because it's not fixed ip so I couldn't put it in spec.hostAliases).

I try to edit the `/etc/hosts` in one of the initContainers, but the change is not shown in other non-init containers. Checking this `makeHostMount` [function](https://github.com/kubernetes/kubernetes/blob/b39bf148cd654599a52e867485c02c4f9d28b312/pkg/kubelet/kubelet_pods.go#L314-L326) and looks like it didn't handle such case so the content is always refreshed when other container is up.

As I understand, the whole pod share the same host path mount, so I expect this to work. Not sure if it's by design or it's a bug.

### What did you expect to happen?

The changes to `/etc/hosts` in init container will be persisted in other non-init containers.

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
spec:
  initContainers:
  - name: myinit
    image: ubuntu:16.04
    imagePullPolicy: IfNotPresent
    command:
    - /bin/bash
    - -c
    - echo "127.0.0.1 localhost" > /etc/hosts; cat /etc/hosts
  containers:
  - name: ubuntu1
    image: ubuntu:16.04
    imagePullPolicy: IfNotPresent
    command:
    - /bin/bash
    - -c
    - cat /etc/hosts; sleep 1000000
  restartPolicy: Always
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - my.fqdn.com
```

expect the log of container `ubuntu1` to be  `127.0.0.1 localhost`, however, the log is 
```
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.244.6.27	ubuntu

# Entries added by HostAliases.
127.0.0.1	my.fqdn.com
```

### Kubernetes version

v1.24.6
<details>

```console
$ kubectl version
# paste output here
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"6c23b67c202a4cfa7c76c3e1b370bd5f0e654f30", GitTreeState:"clean", BuildDate:"2022-11-09T17:13:23Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
