### ISSUE TITLE
Incorrect computation of desired pods for HPAv2beta2

### ISSUE THREAD

**Issue by trick392** [kubernetes/kubernetes#114241]
### What happened?

We currently have the following HPA object created:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2022-11-30T20:07:37Z"
  labels:
    app: istio-ingressgateway
    operator.istio.io/version: 1.15-dev
  name: istio-ingressgateway-us-west-2a
  namespace: abc
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-ingressgateway-us-west-2a
status:
  conditions:
  - lastTransitionTime: "2022-11-30T20:08:32Z"
    message: recommended size matches current size
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2022-11-30T20:09:22Z"
    message: the HPA was able to successfully calculate a replica count from memory
      resource utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2022-11-30T20:10:10Z"
    message: the desired replica count is more than the maximum replica count
    reason: TooManyReplicas
    status: "True"
    type: ScalingLimited
  currentMetrics:
  - resource:
      current:
        averageUtilization: 24
        averageValue: 638698723555m
      name: memory
    type: Resource
  - resource:
      current:
        averageUtilization: 1
        averageValue: 22m
      name: cpu
    type: Resource
  currentReplicas: 5
  desiredReplicas: 5
  lastScaleTime: "2022-11-30T20:10:55Z"
```

Which we believe is computing the desiredReplicas incorrectly.

### What did you expect to happen?

Using the k8s formula for number of pods:
desiredReplicas = ceil[currentReplicas * ( currentMetricValue / desiredMetricValue )]

which is ceil[5 * 1/75] for the cpu and ceil[5 * 24/75]  resulting in 2 pods as the desired output. 

I have validate the metric server is up and the metrics displayed in the hpa object is correct.

### How can we reproduce it (as minimally and precisely as possible)?

Provided the relevant yaml file for the hpa object for a given deployment above. 

### Anything else we need to know?

Do let me know if any other steps are required for debugging this further.

### Kubernetes version

<details>

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
