### ISSUE TITLE
Kubernetes Jobs API rapid-fire scheduling doesnt honor exponential backoff characteristics

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#114391]
### What happened?

# Problem

The job controller appears to "rapidly reschedule" several pods at the same time (without backing off) which ultimately appears almost like a batch or gang scheduling workflow.  

... This is the opposite of what the job docs say, bc they clearly state :
```
 The back-off limit is set by default to 6. Failed Pods associated with the Job are recreated by the Job controller with an exponential back-off delay (10s, 20s, 40s ...) capped at six minutes.
```
So, rather then, 

- 10, 20, 40, 80 wait times between trying things we are seeing
- 0, 3, 3, 3, 3 second wait times before pods are being retried

This is in the 1.25 release, but not sure if it also happens earlier.  You can see this in the latest kind version. 

### What did you expect to happen?

Jobs wouldnt schedule the same pod at rapid fire intervals

### How can we reproduce it (as minimally and precisely as possible)?

# Details 

Thanks to Ryan for this reproducer: 
```
apiVersion: batch/v1

kind: Job

metadata:

  name: backoff-exp

spec:

  backoffLimit: 100

  template:

    spec:

      containers:

        - name: die

          image: ubuntu

          command: [ "/bin/false" ]

          imagePullPolicy: IfNotPresent

      restartPolicy: Never

```

Now once this is running, you can graph the values like so: 

```
kubectl get pods -o wide | awk '

BEGIN {

    a["d"] = 24*(\

    a["h"] = 60*(\

    a["m"] = 60*(\

    a["s"] = 1)));

  }

  {

    print fx($5); # kubernetes time elapsed in seconds

  }

  function fx(ktym,    f,u,n,t,i) {

    n = split(ktym, f, /[dhms]/, u)

    t = 0

    for (i=1; i<n; i++) {

      t += f[i] * a[u[i]]

    }

    return t

  }

'|sort
```

And youl see a table like this, where the integers below are the AGE OF PODS in SECONDS.  We can see that the pod ages are 3 seconds apart as opposed to (10, 20, 40, 80 ...) or some other exponentiallly increasing number of seconds, apart..... 
```
69
72
75
78
81
84
87
90
94
96
99
102
105
108
111
119
```

### Kubernetes version

.25

### Cloud provider

all

### OS version

all

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
