### ISSUE TITLE
HPA behaviour 

### ISSUE THREAD

**Issue by hadjiski** [kubernetes/kubernetes#114383]
### What would you like to be added?

The horizontal pod auto-scaling is currently limited in defining a behavior for the whole HPA.
What about being able to define a behavior per metric?
For example:
Having two metrics based on which the HPA scales up/down pods
- resource metric: CPU utilization
- pod metric: some_custom_metric

Use case:
Pods should be scaled up/down almost immediately if `some_custom_metric` gets above a certain value, on the other side if something goes wrong with the metric and it does not get populated properly we want to still have the fallback of the CPU utilization, but not kicking in immediately, rather after some stabilization period.
So in general, I would like to have below behaviour configurable per HPA metric:
```
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 1
            periodSeconds: 300
      scaleUp:
        stabilizationWindowSeconds: 5
        policies:
          - type: Pods
            value: 1
            periodSeconds: 5
```

so that `stabilizationWindowSeconds` and `periodSeconds` can be defined per HPA metric

### Why is this needed?

One can want immediate scale up based on a custom metric, but more relaxed scale up based on another metric
