### ISSUE TITLE
`kubectl expose` fails for apps with same-port, different-protocol

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#114402]
Given this deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiport
spec:
  replicas: 0
  selector:
    matchLabels:
      app: multiport
  template:
    metadata:
      labels:
        app: multiport
    spec:
      containers:
      - image: k8s.gcr.io/serve_hostname:v1.4
        name: c1
        ports:
        - containerPort: 93
          protocol: TCP
        - containerPort: 93
          protocol: UDP
```

```
$ k expose deploy multiport
The Service "multiport" is invalid: spec.ports[1]: Duplicate value: core.ServicePort{Name:"", Protocol:"UDP", AppProtocol:(*string)(nil), Port:93, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}
```

Looking at staging/src/k8s.io/kubectl/pkg/cmd/expose/expose.go, it builds a `protocolsMap` which reduces those 2 ports to one protocol.  It should probably just return a list of {proto, port} or even {proto, port, name} which it extracts from the target.
