### ISSUE TITLE
same directory is bind-mounted 32767 times

### ISSUE THREAD

**Issue by iameli** [kubernetes/kubernetes#114583]
I have no idea who to report this bug to, so I'm going to duplicate the report a few places.
local-path-provisioner: https://github.com/rancher/local-path-provisioner/issues/287
core-dump-handler: https://github.com/IBM/core-dump-handler/issues/119

### What happened?

I'm running [core-dump-handler](https://github.com/IBM/core-dump-handler) on a few nodes. When core-dump-handler comes under load — we had a service elsewhere that was malfunctioning and segfaulting many times per second — its directory gets bind-mounted over and over and over and over. I do not know by whom.
```
mount | grep core
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
/dev/md1 on /home/data/core-dump-handler/cores type ext4 (rw,relatime,stripe=256)
[...]

# mount | grep core | wc -l
32767
```

Nodes affected by this issue behave really strangely. `mount` and `df` are really really slow, some debugging shows that `stat` calls for this directory is very slow. On my Ubuntu installation it blocks SSH connections for multiple minutes before I can connect because of rendering the MOTD.

### What did you expect to happen?

It should really be bind-mounted one time.

### How can we reproduce it (as minimally and precisely as possible)?

I don't know yet, still investigating. I can try and reproduce in an isolated environment but it's intermittent.

### Anything else we need to know?

[Here's core-dump-handler's DaemonSet configuration file and the PVCs that back it](https://gist.github.com/iameli/805591ec961adddfd6e3f6b0a931fa3b). The pertinent volumes section:
```yaml
      volumes:
      - name: host-volume
        persistentVolumeClaim:
          claimName: host-storage-pvc
      - name: core-volume
        persistentVolumeClaim:
          claimName: core-storage-pvc
[...]
        volumeMounts:
        - mountPath: /home/data/core-dump-handler
          mountPropagation: Bidirectional
          name: host-volume
        - mountPath: /home/data/core-dump-handler/cores
          mountPropagation: Bidirectional
          name: core-volume
```

Possibly a problem with bind-mounting one directory inside another...?

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3+k3s1", GitCommit:"f2585c1671b31b4b34bddbb3bf4e7d69662b0821", GitTreeState:"clean", BuildDate:"2022-10-25T19:59:38Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None, bare metal
</details>

### OS version

<details>

```console
# On Linux:
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
# paste output here
# uname -a
Linux dp7744 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# paste output here
```

</details>

### Install tools

<details>
k3s
</details>

### Container runtime (CRI) and version (if applicable)

<details>
# k3s crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.6.8-k3s1
RuntimeApiVersion:  v1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Only what comes with k3s.
</details>
