### ISSUE TITLE
Job Completed Even Though Containers Have Errors

### ISSUE THREAD

**Issue by ntm97** [kubernetes/kubernetes#114641]
### What happened?

I have job with `1/1` completions, however the underlying container exited with an error.

Job status:
```yaml
  status:
    completionTime: "2022-12-21T12:45:02Z"
    conditions:
    - lastProbeTime: "2022-12-21T12:45:02Z"
      lastTransitionTime: "2022-12-21T12:45:02Z"
      status: "True"
      type: Complete
    startTime: "2022-12-21T12:38:31Z"
    succeeded: 1
    uncountedTerminatedPods: {}
 ```
 
 Pod status:
 ```yaml
 status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-12-21T12:38:30Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-12-21T12:43:28Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-12-21T12:43:28Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-12-21T12:38:31Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - [...]
    lastState: {}
    ready: false
    restartCount: 5
    started: false
    state:
      terminated:
        exitCode: 1
        finishedAt: "2022-12-21T12:45:16Z"
        reason: Error
        startedAt: "2022-12-21T12:44:55Z"
  hostIP: 192.168.101.101
  phase: Succeeded
  qosClass: BestEffort
  startTime: "2022-12-21T12:38:30Z"
```

### What did you expect to happen?

As the job has `backoffLimit` of `20` and a `restartPolicy` of `OnFailure`, I would have expected the container to be restarted after the error, however, the job is just declared as completed and stops trying.

<details>

Job spec:
```yaml
  spec:
    backoffLimit: 20
    completionMode: NonIndexed
    completions: 1
    parallelism: 1
    suspend: false
    template:
      spec:
        containers:
        - [...]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: OnFailure
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
```

</details>

### How can we reproduce it (as minimally and precisely as possible)?

Not sure how to reproduce this reliably.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+k3s1", GitCommit:"61a2aab25eeb97c26fa3f2b177e4355a7654c991", GitTreeState:"clean", BuildDate:"2021-11-04T00:24:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

Self-hosted on KVM virtual machines (`libvirtd 7.0.0-3`)

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
```

</details>

### Install tools

<details>

```console
# k3s -v
k3s version v1.22.3+k3s1 (61a2aab2)
go version go1.16.8
```

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
# docker --version
Docker version 20.10.18, build b40c2f6
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

```console
# calicoctl version
Client Version:    v3.17.6
Git commit:        a26c5fc6
Cluster Version:   v3.21.0
Cluster Type:      k8s,bgp,kdd
```

</details>
