### ISSUE TITLE
Deployment create too many Pods

### ISSUE THREAD

**Issue by zhuxiaolong-g** [kubernetes/kubernetes#114637]
### What happened?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom 
  labels:
    app: oom 
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: oom 
  template:
    metadata:
      labels:
        app: oom 
    spec:
      nodeName: hzen
      containers:
      - command:
          - sleep
          - "3600000"
        image: busybox 
        imagePullPolicy: IfNotPresent
        name: oomc 
        resources:
          limits:
            cpu: "0.2"
            memory: 10G
          requests:
            cpu: "0.2"
            memory: 10G
```
1. Define the deployment with **nodeName**
2. Apply the yaml
3. kubectl get pod, got to many pods with outOfMemory Status.
```
[root@dev oom]$ k get pod -A
NAMESPACE     NAME                                       READY   STATUS        RESTARTS      AGE
default       oom-bcb75fdfb-258zk                        0/1     OutOfmemory   0             84s
default       oom-bcb75fdfb-2cd4z                        0/1     OutOfmemory   0             71s
default       oom-bcb75fdfb-2dntb                        0/1     OutOfmemory   0             88s
default       oom-bcb75fdfb-2fbw8                        0/1     OutOfmemory   0             113s
default       oom-bcb75fdfb-2gtsb                        0/1     OutOfmemory   0             2m21s
default       oom-bcb75fdfb-2xf8h                        0/1     OutOfmemory   0             82s
default       oom-bcb75fdfb-44jwn                        0/1     OutOfmemory   0             11s
default       oom-bcb75fdfb-44sp5                        0/1     OutOfmemory   0             68s
default       oom-bcb75fdfb-44t5l                        0/1     OutOfmemory   0             97s
default       oom-bcb75fdfb-458h5                        0/1     OutOfmemory   0             2m15s
default       oom-bcb75fdfb-45g9l                        0/1     OutOfmemory   0             57s
default       oom-bcb75fdfb-49mmz                        0/1     OutOfmemory   0             2m15s
default       oom-bcb75fdfb-4fm4s                        0/1     OutOfmemory   0             23s
default       oom-bcb75fdfb-4hl2p                        0/1     OutOfmemory   0             106s
default       oom-bcb75fdfb-4kwh5                        0/1     OutOfmemory   0             2m7s
default       oom-bcb75fdfb-4l6b9                        0/1     OutOfmemory   0             106s
default       oom-bcb75fdfb-4nv6n                        0/1     OutOfmemory   0             100s
default       oom-bcb75fdfb-4qdc9                        0/1     OutOfmemory   0             89s
default       oom-bcb75fdfb-4qqcp                        0/1     OutOfmemory   0             54s
default       oom-bcb75fdfb-52pqc                        0/1     OutOfmemory   0             81s
default       oom-bcb75fdfb-52vsl                        0/1     OutOfmemory   0             2m1s
```

### What did you expect to happen?

Pods num as defined in config

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Kubernetes version

<details>

```console

[root@dev workspace]$ k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
[root@dev workspace]$

```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
