### ISSUE TITLE
PodTopologyConstraints - DoNotSchedule not working as expected

### ISSUE THREAD

**Issue by chmodrs** [kubernetes/kubernetes#114788]
### What happened?

Hi,

I tried to use PodTopologySpreadConstraint to organize our deployment engine, and to spread replicas across zones. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx
      tolerations:
      - effect: NoSchedule
        key: platform
        operator: Equal
        value: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodes
                operator: In
                values:
                - platform
```

I expected that, if I have just one node labeled "platform", the scheduler needs to run just one replica of Nginx, and others need to be in a "pending" state because "DoNotSchedule" constraint is not satisfied.

But the deployment running the 4 replicas in the same node/zone, even that "DoNotSchedule" defined.

```
➜ kubectl get pods -o wide | grep nginx-deployment
nginx-deployment-6cbbb547c-6qvrg   1/1     Running            0               15m     192.168.33.28    ip-192-168-42-2.sa-east-1.compute.internal     <none>           <none>
nginx-deployment-6cbbb547c-cgbcf   1/1     Running            0               15m     192.168.37.251   ip-192-168-42-2.sa-east-1.compute.internal     <none>           <none>
nginx-deployment-6cbbb547c-dlqvd   1/1     Running            0               15m     192.168.47.173   ip-192-168-42-2.sa-east-1.compute.internal     <none>           <none>
nginx-deployment-6cbbb547c-hkgzc   1/1     Running            0               15m     192.168.39.27    ip-192-168-42-2.sa-east-1.compute.internal     <none>           <none>
```

and i just have one node labeled "platform"

```
➜ kubectl get nodes -l app=platform
NAME                                         STATUS   ROLES    AGE     VERSION
ip-192-168-42-2.sa-east-1.compute.internal   Ready    <none>   4h45m   v1.22.15-eks-fb459a0
```

Does anyone have any idea what I made wrong?

### What did you expect to happen?

I expect that PodTopologySpreadConstraint with "DoNotSchedule" value, not scheduling pods in the same zone/node if I have just one node.

### How can we reproduce it (as minimally and precisely as possible)?

Apply the following manifest with one node labeled "platform" and following kubelet_extra_args: `-node-labels=app=platform,nodes=platform --register-with-taints=platform=true:NoSchedule`, or remove affinity and toleration from manifest and run in cluster with single node.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx
      tolerations:
      - effect: NoSchedule
        key: platform
        operator: Equal
        value: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodes
                operator: In
                values:
                - platform
```

### Kubernetes version

<details>

```console
➜ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by songminglong** [comment]
PodTopologyConstraints add new feature gate 'NodeInclusionPolicyInPodTopologySpread' to control the relationship between PodTopologyConstraints and nodeAffinity/nodeSelector in 1.25/alpha version. The default value of nodeAffinityPolicy is honor, means that only nodes matching nodeAffinity/nodeSelector are included in the calculations

**Comment by chmodrs** [comment]
@songminglong perfect, I understand that PodTopologySpreadConstraint doesn't work very well with nodeAffinity/nodeSelector definition, right?

But in case that we don't use this flags? Like bellow:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 8 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx
      #tolerations:
      #- effect: NoSchedule
      #  key: platform
      #  operator: Equal
      #  value: "true"
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: nodes
      #          operator: In
      #          values:
      #          - platform
```
In this case, I just have 3 zones in sa-east-1, I think that the scheduler just can run one pod per zone and others need to be in a "pending state", don't they?

But still running multiple pods in the same zone :(

```
nginx-deployment-56f498fc9b-4w7hn   1/1     Running     0                 44s     192.168.33.145   ip-192-168-43-89.sa-east-1.compute.internal    <none>           <none>
nginx-deployment-56f498fc9b-9wqgz   1/1     Running     0                 11s     192.168.43.127   ip-192-168-43-89.sa-east-1.compute.internal    <none>           <none>
nginx-deployment-56f498fc9b-dq966   1/1     Running     0                 44s     192.168.61.95    ip-192-168-63-116.sa-east-1.compute.internal   <none>           <none>
nginx-deployment-56f498fc9b-fflc6   1/1     Running     0                 11s     192.168.70.36    ip-192-168-70-157.sa-east-1.compute.internal   <none>           <none>
nginx-deployment-56f498fc9b-jgzg8   1/1     Running     0                 11s     192.168.63.240   ip-192-168-63-116.sa-east-1.compute.internal   <none>           <none>
nginx-deployment-56f498fc9b-m5g6r   1/1     Running     0                 44s     192.168.78.10    ip-192-168-70-157.sa-east-1.compute.internal   <none>           <none>
nginx-deployment-56f498fc9b-p6z2z   1/1     Running     0                 44s     192.168.45.204   ip-192-168-43-89.sa-east-1.compute.internal    <none>           <none>
nginx-deployment-56f498fc9b-zxmr4   1/1     Running     0                 11s     192.168.53.57    ip-192-168-63-116.sa-east-1.compute.internal   <none>           <none>
```

**Comment by kerthcet** [comment]
> I expected that, if I have just one node labeled "platform", the scheduler needs to run just one replica of Nginx, and others need to be in a "pending" state because "DoNotSchedule" constraint is not satisfied.

zone is divided by `topologyKey: topology.kubernetes.io/zone`, not `platform`.

**Comment by kerthcet** [comment]
Here're some examples: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#topology-spread-constraint-examples

**Comment by sftim** [comment]
Do we think this is a bug, or an opportunity to provide extra documentation?

**Comment by kerthcet** [comment]
Yes, I think we should add the examples of new features like `NodeInclusionPolicyInPodTopologySpread ` to https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#topology-spread-constraint-examples, and we also plan to post a new blog about them.

**Comment by kerthcet** [comment]
From the output:
```
nginx-deployment-56f498fc9b-4w7hn   1/1     Running     0                 44s     192.168.33.145   ip-192-168-43-89.sa-east-1.compute.internal    <none>           <none>
nginx-deployment-56f498fc9b-9wqgz   1/1     Running     0                 11s     192.168.43.127   ip-192-168-43-89.sa-east-1.compute.internal    <none>           <none>
nginx-deployment-56f498fc9b-dq966   1/1     Running     0                 44s     192.168.61.95    ip-192-168-63-116.sa-east-1.compute.internal   <none>           <none>
nginx-deployment-56f498fc9b-fflc6   1/1     Running     0                 11s     192.168.70.36    ip-192-168-70-157.sa-east-1.compute.internal   <none>           <none>
nginx-deployment-56f498fc9b-jgzg8   1/1     Running     0                 11s     192.168.63.240   ip-192-168-63-116.sa-east-1.compute.internal   <none>           <none>
nginx-deployment-56f498fc9b-m5g6r   1/1     Running     0                 44s     192.168.78.10    ip-192-168-70-157.sa-east-1.compute.internal   <none>           <none>
nginx-deployment-56f498fc9b-p6z2z   1/1     Running     0                 44s     192.168.45.204   ip-192-168-43-89.sa-east-1.compute.internal    <none>           <none>
nginx-deployment-56f498fc9b-zxmr4   1/1     Running     0                 11s     192.168.53.57    ip-192-168-63-116.sa-east-1.compute.internal   <none>           <none>
```

I guess you have three zones:
 - ip-192-168-63-116.sa-east-1.compute.internal  -- three pods matched
 - ip-192-168-43-89.sa-east-1.compute.internal   -- three pods matched
 - ip-192-168-43-157.sa-east-1.compute.internal  -- two pods matched

The maxMatchedPodsNumber - minMatchedPodsNumber = 3 - 2 = 1 <= maxSkew, so it's still satisfied and working as expected. @chmodrs Can you confirm this and I guess you misunderstood the usage.

**Comment by chmodrs** [comment]
Hi @kerthcet 

So maybe I made a confusion about PodTopologySpreadConstraint utilization, right?

I think that configuring maxSkew = 1 corresponds to that I will have 1 pod in each zone, using `topologyKey: topology.kubernetes.io/zone` (its what I wanted), but I need to use node toleration + affinity to place my pods in correct nodegroup (platform) too.

An example of a scenario that I want to configure, with PodTopologySpreadConstraint is:

- 3 zones (a, b, c)
- All deployments with 4 replicas

Guarantee that I have at least 1 pod in each zone, no matter what happens, and the last pod (fourth) in any zone.

I can't configure this scenario with PodTopologySpreadConstraints?

Thankss!!

**Comment by kerthcet** [comment]
So I guess all the nodes in platform nodegroup scoped by the three zones. Then what you pasted above can work as your expected:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx
      tolerations:
      - effect: NoSchedule
        key: platform
        operator: Equal
        value: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodes
                operator: In
                values:
                - platform
```

The nodeAffinity will filter out all the nodes with label `nodes:platform`, then `topologySpreadConstraints` will divide the zones via `topology.kubernetes.io/zone`, and make sure not violating the maxSkew.

**Comment by chmodrs** [comment]
Hi @kerthcet , sorry for my lateness.

I tried to apply the following deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx
```

I have a EKS cluster in sa-east-1 region with 3 availability zones.

```
➜ kubectl get pods | grep nginx-deployment
nginx-deployment-56f498fc9b-d4hfr   1/1     Running            0                  9m56s
nginx-deployment-56f498fc9b-d6hzd   1/1     Running            0                  9m56s
nginx-deployment-56f498fc9b-nkgs5   1/1     Running            0                  9m56s
nginx-deployment-56f498fc9b-q968x   1/1     Running            0                  9m53s
nginx-deployment-56f498fc9b-vdwmq   1/1     Running            0                  9m54s
```

With just 3 zones and maxSkew=1, we need to get two pods in "Pending" state, right? Because "DotNotSchedule" is defined.

In my case, even i use "DoNotSchedule" or "ScheduleAnyway" the result is the same.

**Comment by geniusjoe** [comment]
@kerthcet 
I use EKS with kubernetes 1.20.x and it seems that I encountered the same problem. I am a newbee in kubernetes and I don't know if my opration is correct. Steps below:

1. Create a cluster with two EKS nodes: node1, node2
2. Add a label to node1: `testLabel: testValue`
3. Create a StatefulSet with 3 replicas, and I set `topologySpreadConstraints` and `nodeAffinity` properties like:
```
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: testLabel
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: my-app
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: testLabel
              operator: In
              values:
                - testValue
                - testValue1
```
This time every created pods will be scheduled to node1, and it work fine.
5. Add a label in node2: `testLabel: testValue1`
6. Expand this StatefulSet to 4 replicas, I think this new pod will still hang in pending status because `maxSkew` violate in node1(3pods) and node2(0pod). But now the pod is successfully scheduled to node2 and becomes to running status.

Are there any questions or advice? Please feel free to let me know.
