### ISSUE TITLE
Event timestamps don't support sub-second precision

### ISSUE THREAD

**Issue by mruzicka** [kubernetes/kubernetes#114765]
### What happened?

We started exporting Kubernetes events into a monitoring system and noticed that some events seem to be out of order (e.g. container started event before container created event). Upon further investigation we concluded that the root cause is the insufficient precision of the event timestamps - the timestamps only support seconds precision - so the order of events which happen in the same second is lost.
This behavior turns out to be by design: 
* [staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time_proto.go#L45-L48](https://github.com/kubernetes/kubernetes/blob/ca858e0c961db6ef8b22ecc3e257a02757261ea1/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time_proto.go#L45-L48)
* [staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time_proto.go#L70-L73](/kubernetes/kubernetes/blob/ca858e0c961db6ef8b22ecc3e257a02757261ea1/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time_proto.go#L70-L73)

It was introduced in commit 5b8a483a9623998625fe970e78307b0c5e064d51.
Given the commit is 5 years old, has it perhaps become obsolete, could it be reverted so that the nanosecond precision is preserved?

### What did you expect to happen?

Order of events which happened in the same second is preserved. The relevant timestamps support sub-second precision.

### How can we reproduce it (as minimally and precisely as possible)?

Query the Kubernetes Events API using client supporting ProtoBuf content type (such [resmoio/kubernetes-event-exporter](/resmoio/kubernetes-event-exporter), which uses k8s client internally).

### Kubernetes version

```yaml
clientVersion:
  buildDate: "2022-11-11T00:00:00Z"
  compiler: gc
  gitCommit: fdc77503e954d1ee641c0e350481f7528e8d068b
  gitTreeState: archive
  gitVersion: v1.24.8
  goVersion: go1.18.8
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-12-08T10:08:09Z"
  compiler: gc
  gitCommit: 804d6167111f6858541cef440ccc53887fbbc96a
  gitTreeState: clean
  gitVersion: v1.25.5
  goVersion: go1.19.4
  major: "1"
  minor: "25"
  platform: linux/amd64
```

### Cloud provider

N/A

### OS version

N/A

### Install tools

`kubeadm`
