### ISSUE TITLE
Feature Request: Add semaphore feature to CronJob API

### ISSUE THREAD

**Issue by MPParsley** [kubernetes/kubernetes#115086]
### What would you like to be added?

Please extend the CronJob API with a Semaphore feature.

```
  semaphore:
    name: cron-semaphore
    maxConcurrency: 1
```

It allows to control concurrency of CronJobs being executed. It can be used to limit the number of concurrent different CronJobs running at the same time.

### Why is this needed?

A semaphore is different from the _concurrencyPolicy_ as it allows limiting the amount of **different** CronJobs.

**Comment by MPParsley** [comment]
This API extension was actually proposed after a discussion with ChatGPT.

Q: I have two tasks that need to run on a regular schedule but they can't overlap:

> If you have two tasks that need to run on a regular schedule but cannot overlap, you can use two separate CronJobs, each with its own schedule, and set the concurrencyPolicy field to Forbid for each of them. This will prevent a new instance of the CronJob from starting if another instance is still running.
>
> Here's an example of how you can create two Kubernetes CronJobs with the names ldes-consumer-tentoonstellingen and ldes-consumer-dmg that cannot overlap:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ldes-consumer-tentoonstellingen-job
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ldes-consumer-tentoonstellingen
            image: ldes-consumer-tentoonstellingen-image
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ldes-consumer-dmg-job
spec:
  schedule: "30 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ldes-consumer-dmg
            image: ldes-consumer-dmg-image
          restartPolicy: OnFailure
```

Q: concurrencyPolicy: Forbid will prevent an instance of the same cronjob, for instance ldes-consumer-tentoonstellingen-job , to overlap but are you sure that it will also prevent to overlap with the other cronjob (ldes-consumer-dmg-job)?

> You are correct, concurrencyPolicy: Forbid will prevent an instance of the same CronJob from running at the same time, but it will not prevent two different CronJobs from running at the same time.

> If you need to ensure that two different CronJobs do not run at the same time, you can use a different approach:

> Use a custom controller for the CronJobs, for example, you can write a script that checks the status of the other CronJob before starting a new run.
>
> Use a lock mechanism like distributed locks such as Zookeeper or etcd to ensure that only one instance of the CronJobs is running at a time.
>
> Use Kubernetes' Job API instead of CronJob API, Jobs ensure that only a certain number of pods are running at a time, you can use one Job for each of your cronjob and set the parallelism field to 1, this way only one pod will run at a time.
>
> Use a Kubernetes Semaphore resource to manage the concurrency between your two cronjobs, this way you can coordinate the execution of your cronjobs and prevent them from running at the same time.
>
> It's important to note that the solution you choose will depend on the specific requirements of your application and the resources available on your cluster.

Q: Can you update the last example to ensure the two different CronJobs do not run at the same time?

> Sure, here is an example of how you can create two Kubernetes CronJobs ldes-consumer-tentoonstellingen and ldes-consumer-dmg that will not run at the same time by using a Kubernetes Semaphore resource:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ldes-consumer-tentoonstellingen-job
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ldes-consumer-tentoonstellingen
            image: ldes-consumer-tentoonstellingen-image
          restartPolicy: OnFailure
          readinessProbe:
            exec:
              command:
              - "sh"
              - "-c"
              - "curl -s http://localhost:8080/health | grep -q 'OK'"
          livenessProbe:
            exec:
              command:
              - "sh"
              - "-c"
              - "curl -s http://localhost:8080/health | grep -q 'OK'"
  semaphore:
    name: cron-semaphore
    maxConcurrency: 1
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ldes-consumer-dmg-job
spec:
  schedule: "30 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ldes-consumer-dmg
            image: ldes-consumer-dmg-image
          restartPolicy: OnFailure
          readinessProbe:
            exec:
              command:
              - "sh"
              - "-c"
              - "curl -s http://localhost:8080/health | grep -q 'OK'"
          livenessProbe:
            exec:
              command:
              - "sh"
              - "-c"
              - "curl -s http://localhost:8080/health | grep -q 'OK'"
  semaphore:
    name: cron-semaphore
    maxConcurrency: 1
```

**Comment by Shuimo03** [comment]
Please assign me

**Comment by sftim** [comment]
If you have two separate CronJobs and want to make sure that only one Job from either CronJob is considered active, use a [Lease](url), and update your code (or possibly a sidecar container) to work with that Lease.

If we want to prevent a CronJob from creating a Job when some other thing has made a particular kind of Job, _I_ would [file an enhancement request to] define a selector for matching the other Jobs.

Something like this:

```yaml
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: first
spec:
  schedule: "/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job-type: first-or-second
        spec:
          containers:
          - name: something
            image: busybox:stable
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh","-c","sleep 60 && echo Hello, world"]
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: second
spec:
  schedule: "/5 * * * *"
  concurrencyPolicy: ForbidWithCollisionSelector # this is new
  collisionSelector:                             # this is new
      job-type: first-or-second                  # this is new
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job-type: first-or-second
        spec:
          containers:
          - name: somethingelse
            image: busybox:stable
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh","-c","sleep 600 && echo Hello again, world"]
```

_However_, if we can implement this purely by extending Kubernetes, that's even better. Core API changes should be something we avoid if we can.
