### ISSUE TITLE
Cannot create ingress with ingressClass annotation and IngressClassName both set

### ISSUE THREAD

**Issue by matthewbyrne** [kubernetes/kubernetes#115018]
### What happened?

An ingress resource with both `kubernetes.io/ingress.class` annotation and `spec.ingressClassName` set cannot be **created**. Ingress resources can be updated to include both the annotation and the `ingressClassName` without issue.

Kubernetes response:

> The Ingress "example-ingress" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set

### What did you expect to happen?

The ingress should be deployed with both annotation and `spec.ingressClassName` set, as it is supported by updating an existing ingress.

### How can we reproduce it (as minimally and precisely as possible)?

Apply this resource:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: test.foo.bar
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dummy-service
              port:
                number: 1234

```

### Anything else we need to know?

The code causing this issue is here:

https://github.com/kubernetes/kubernetes/blob/f166a525737e700d12da56833388af72585d4239/pkg/apis/networking/validation/validation.go#L279

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:36:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/arm64"}
# Kustomize Version: v4.5.7
# Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
</details>

### OS version

<details>

Linux, Mac, mulitple OSs with the same issue. It's caused by code as linked above

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
