### ISSUE TITLE
Attempting to mount a badly defined secret at a subPath results in an empty folder instead of some error condition

### ISSUE THREAD

**Issue by alexdyas** [kubernetes/kubernetes#115131]
### What happened?

Attempting to mount a secret as a file at a subPath, if the secret's data key does not match the deployment's `subPath` definition
I get an empty directory. If the secret was correctly defined, I would see my secret file mounted. This behavior  is confusing, especially as there is no error or warning anywhere, at least not that I've seen.

### What did you expect to happen?

If anything I would expect nothing to be created in the filesystem. Falling back to an empty directory makes no sense to me. And ideally some error or warning reported somewhere.

### How can we reproduce it (as minimally and precisely as possible)?

Secret and deployment definitions to reproduce. Note - secret data key does _not_ match the `subPath` defined in the deployment.
```
# secret.yaml
---
apiVersion: v1
data:
  NOTsomefile.txt: TWFyeSBoYWQgYSBsaXR0bGUgbGFtYgo=
kind: Secret
metadata:
  annotations:
  name: somesecret
  namespace: default
```
```
# deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: default
spec:
  replicas: 1
  selector:
      matchLabels:
          app: alpine
  template:
    metadata:
        labels:
            app: alpine
    spec:
      containers:
          - image: alpine:3.17.1
            command: ["sh", "-c", "tail -f /dev/null"]
            name: alpine
            volumeMounts:
                - mountPath: /var/tmp/somefile.txt
                  name: somefile-txt-v
                  subPath: somefile.txt
      volumes:
        - name: somefile-txt-v
          secret:
            secretName: somesecret
```

### Kubernetes version

```console
~% kubectl.v1.23.4 version --short
Client Version: v1.23.4
Server Version: v1.23.4
```

### Cloud provider

Oracle OCI OKE

### OS version

```console
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"                                                                         
VERSION="8.6 (Ootpa)"                                                                                   
ID="rhel"                                                                                               
ID_LIKE="fedora"                                                                                        
VERSION_ID="8.6"                                                                                        
PLATFORM_ID="platform:el8"                                                                              
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"                                                      
ANSI_COLOR="0;31"                                                                                       
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"                                                     
HOME_URL="https://www.redhat.com/"                                                                      
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"                 
BUG_REPORT_URL="https://bugzilla.redhat.com/"                                                           
                                                                                                        
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"                                                    
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6                                                                     
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"                                                       
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"                                                                    

$ uname -a
Linux hqchdevnes2 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Sat Aug 27 02:44:20 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux 
```

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
