### ISSUE TITLE
concurrencyPolicy: Replace don`t work

### ISSUE THREAD

**Issue by SergeyLadutko** [kubernetes/kubernetes#115335]
### What happened?

concurrencyPolicy: Replace don`t work

### What did you expect to happen?

I expected that when starting new jobs, the old ones would be deleted

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: batch/v1 
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - sleep 100
          restartPolicy: OnFailure
```
apply this file

`kubectl apply -f cron-job.yaml`

and run:

```
kubectl create job --from=cronjob/hello test-1
kubectl create job --from=cronjob/hello test-2
kubectl create job --from=cronjob/hello test-3
```

### Kubernetes version

<details>
I checked on two clusters with different versions

```
$ kubectl version
#Client Version: v1.23.7
Server Version: v1.23.7

```
and

```
$ kubectl version
Client Version: v1.23.7
Server Version: v1.23.7
```

</details>

### Cloud provider

<details>
    dedicated server in [hetzner](https://www.hetzner.com/)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
