### ISSUE TITLE
imageRepository config not working

### ISSUE THREAD

**Issue by ggg17226** [kubernetes/kubernetes#115356]
### What happened?

i had defined "imageRepository" in init config file, it works for kube-apiserver/kube-controller-manager/kube-proxy/kube-scheduler/etcd/coredns images, but not work for "pause" image.
when i use 
> kubeadm config images pull --config xxx.yaml
  
to pull image, it shows this:  
```
[config/images] Pulled xxx/kube-apiserver:v1.25.6
[config/images] Pulled xxx/kube-controller-manager:v1.25.6
[config/images] Pulled xxx/kube-scheduler:v1.25.6
[config/images] Pulled xxx/kube-proxy:v1.25.6
[config/images] Pulled xxx/pause:3.8
[config/images] Pulled xxx/etcd:3.5.6-0
[config/images] Pulled xxx/coredns:v1.9.3
```

but when i init the cluster, i get this error:

```
E0127 16:55:37.040714   20458 kuberuntime_manager.go:772] "CreatePodSandbox for pod failed" err="rpc error: code = DeadlineExceeded desc = creating pod sandbox with name \"k8s_kube-apiserver-k8s-test-master-1.k8s.xxx.xxx_kube-system_08343cf2935f5738071b1e941c04dcc5_0\": initializing source docker://registry.k8s.io/pause:3.6: Get \"https://asia-east1-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.6\": dial tcp 64.233.189.82:443: i/o timeout" pod="kube-system/kube-apiserver-k8s-test-master-1.k8s.xxx.xxx"
```

so it pull image from imageRepository which i defined but running use the default one.

### What did you expect to happen?

both pull and running use the imageRepository which i defined on config file

### How can we reproduce it (as minimally and precisely as possible)?

just init a new cluster with imageRepository defined.

### Anything else we need to know?

here is my init config file

```yaml
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: x.x.x.x
  bindPort: 6443
nodeRegistration:
  criSocket: "unix:///var/run/crio/crio.sock"
  imagePullPolicy: IfNotPresent
  name: k8s-test-master-1.xxx.xxx.xxx
  taints:
  - effect: NoSchedule
    key: kubeadmNode
    value: "master"
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
controlPlaneEndpoint: "xxx.xxx.xxx:6443"
certificatesDir: /etc/kubernetes/pki
clusterName: k8s-test
controllerManager: {}
etcd:
  local:
    dataDir: /data/k8s/etcd
imageRepository: image.repo.xxx
kind: ClusterConfiguration
kubernetesVersion: 1.25.6
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.128.0.0/16
  podSubnet: 172.129.0.0/16
scheduler: {}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
  scheduler: "nq"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
```

### Kubernetes version

<details>

```yaml
clientVersion:
  buildDate: "2023-01-18T19:22:09Z"
  compiler: gc
  gitCommit: ff2c119726cc1f8926fb0585c74b25921e866a28
  gitTreeState: clean
  gitVersion: v1.25.6
  goVersion: go1.19.5
  major: "1"
  minor: "25"
  platform: linux/amd64
kustomizeVersion: v4.5.7
```

</details>

### Cloud provider

<details>
self server
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux vm-k8s-master-1 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```
cri-o-runc/unknown,now 1.0.1~2 amd64 [installed]
cri-o/unknown,now 1.26.1~0 amd64 [installed]
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
