### ISSUE TITLE
Secrets does not creating

### ISSUE THREAD

**Issue by titans2016** [kubernetes/kubernetes#115483]
### What happened?

I am writing to report an issue with the latest version of Kubernetes in Azure, version v1.24.6. Before this version, when creating a Kubernetes cluster, the service account and secrets were automatically created and everything worked smoothly. However, with version v1.24.6, I have encountered an error when attempting to connect the cluster to Azure DevOps. Also during execution command in version v1.23.8 "kubectl create serviceaccount some_name", security token generating automatically. But not in v1.24.6. I found only 2 secrets in new cluster v1.24.6 comparing with v1.23.8 where was more than 30 secrets. I am checking all namespaces with command "kubectl get secrets --all-namespaces"

Upon investigation, I learned that a developer made the decision to delete the feature of automatically creating the service account and secrets, which has now affected all Azure DevOps organizations. I have tried to manually create the token secret  command, but I have not seen any changes in the secrets.

```
apiVersion: v1
kind: Secret
metadata:
  name: oke-kubeconfig-sa-token
  namespace: dev-cluster
  annotations:
    kubernetes.io/service-account.name: devops-kubernetes-sa
type: kubernetes.io/service-account-token
```
Kubernetes just ignore this applying.
I am unsure if this is a bug or if there has been a deliberate change in the functionality. 
I would greatly appreciate it if you could investigate this issue and provide further information or guidance.

### What did you expect to happen?

I expected that after manually creating the secret, it would appear in the list of secrets when executing the "kubectl get secrets --all-namespaces" command. However, the secret is not appearing, and I am unable to connect my Kubernetes cluster to Azure DevOps as a result.

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce the issue, you can follow these steps:

Create a Kubernetes cluster with version v1.24.6. I am not sure if the issue only in azure kubernetes. But as I see, microsoft reported that this is a common problem.
Attempt to create a token secret .
Observe that the secret does not appear in the list of secrets when executing the "kubectl get secrets --all-namespaces" command.

### Anything else we need to know?

Related discussion:
[https://techcommunity.microsoft.com/t5/azure-devops/could-not-find-any-secrets-associated-with-the-service-account/m-p/3588722](url)
[https://learn.microsoft.com/en-us/answers/questions/1051970/aks-with-kubernetes-service-connection-returns-cou](url)

### Kubernetes version

<details>

```console
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"c86d003ea699ec4bcffee10ad563a26b63561c0e", GitTreeState:"clean", BuildDate:"2022-12-17T10:31:53Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
BuildNumber  Caption                          OSArchitecture  Version
19044        Microsoft Windows 10 Enterprise  64-bit          10.0.19044
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
Autogeneration of token secrets ceased to be necessary for injecting credentials into pods in 1.21, when ephemeral tokens started getting used.

In 1.24, auto-generation of token secrets was disabled by default, both to save cluster resources and to reduce exposure of permanent unused credentials visible to anyone with read access to secrets. If needed, cluster operators can re-enable token autogeneration in 1.24 and 1.25 by disabling the LegacyServiceAccountTokenNoAutoGeneration 
feature-gate (more info in https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token). In 1.27, the auto-generation functionality is removed.

Use of token secrets outside of pods is still supported, and requires creating a secret to hold the desired token, as described at https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount

> I expected that after manually creating the secret, it would appear in the list of secrets when executing the "kubectl get secrets --all-namespaces" command.

You likely need to create the service account first. If you create a secret that indicates it is a token secret for a serviceaccount, and the service account does not exist, Kubernetes will remove the secret.

You can create the service account first like this:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-kubernetes-sa
  namespace: dev-cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: oke-kubeconfig-sa-token
  namespace: dev-cluster
  annotations:
    kubernetes.io/service-account.name: devops-kubernetes-sa
type: kubernetes.io/service-account-token
```

Applying that example produces this result, with the secret holding the token as requested:
```
kubectl apply -f secret.yaml 
serviceaccount/devops-kubernetes-sa created
secret/oke-kubeconfig-sa-token created

$ kubectl get secrets -A
NAMESPACE     NAME                      TYPE                                  DATA   AGE
dev-cluster   oke-kubeconfig-sa-token   kubernetes.io/service-account-token   3      4s
```

**Comment by czybjtu** [comment]
```bash
# k get sa -ndev-cluster
NAME                   SECRETS   AGE
default                0         82s
devops-kubernetes-sa   0         80s

# k describe sa -ndev-cluster devops-kubernetes-sa
Name:                devops-kubernetes-sa
Namespace:           dev-cluster
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              oke-kubeconfig-sa-token
Events:              <none>
```
Hi @liggitt , should the value of `SECRETS` be 1 when get sa?

**Comment by liggitt** [comment]
No, that description is for the `secrets` field inside the service account, which is not populated by default by any core kubernetes components now, and doesn't actually drive any behavior unless the service account opts into limiting mountable secrets by setting a `kubernetes.io/enforce-mountable-secrets=true` annotation

I opened https://github.com/kubernetes/kubernetes/pull/117160 to drop the misleading/unused fields from the human-readable get and describe output

**Comment by gowthamakanthan** [comment]
Hi @liggitt  We followed your inputs and created the SA secrets manually. However, we are still facing issues with tokens `Mountpoints` .  Am I missing something? 

```
  ~ k_dev_new version --short
Client Version: v1.21.5
Server Version: v1.25.6-eks-48e63af
WARNING: version difference between client (1.21) and server (1.25) exceeds the supported minor version skew of +/-1
➜  ~
```

Service account yaml
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.cloud.accountID }}:role/{{ .Values.cloud.iamRoleName}}
  name: "{{ .Values.serviceAccountName }}"
  namespace: "{{ .Release.Namespace }}"
  automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.serviceAccountName }}-token"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes.io/service-account.name: "{{ .Values.serviceAccountName }}"
    kubernetes.io/enforce-mountable-secrets: "true"
type: kubernetes.io/service-account-token
```
Secret:
```
 ~ k_dev_new get secrets -n amazon-custom-metrics
NAME                                                  TYPE                                  DATA   AGE
k8s-cloudwatch-adapter-token                          kubernetes.io/service-account-token   3      6m51s
sh.helm.release.v1.cloudwatch-custom-metrics-new.v1   helm.sh/release.v1                    1      6m51s
➜  ~
```
Secret describe:
```
~ k_dev_new describe secret k8s-cloudwatch-adapter-token -n amazon-custom-metrics
Name:         k8s-cloudwatch-adapter-token
Namespace:    amazon-custom-metrics
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  kubernetes.io/enforce-mountable-secrets: true
              kubernetes.io/service-account.name: k8s-cloudwatch-adapter
              kubernetes.io/service-account.uid: a86fe6fd-057d-4cc0-a39a-8cf79bb7998b
              meta.helm.sh/release-name: cloudwatch-custom-metrics-new
              meta.helm.sh/release-namespace: amazon-custom-metrics

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1099 bytes
namespace:  21 bytes
token:      <token>
➜  ~
```
Service account describe o/p
```
➜  ~ k_dev_new describe sa k8s-cloudwatch-adapter  -n amazon-custom-metrics
Name:                k8s-cloudwatch-adapter
Namespace:           amazon-custom-metrics
Labels:              app.kubernetes.io/managed-by=Helm
Annotations:         eks.amazonaws.com/role-arn: arn:aws:iam::681496624581:role/eks_cloudwatch_metrics_aws_core-eks-new
                     meta.helm.sh/release-name: cloudwatch-custom-metrics-new
                     meta.helm.sh/release-namespace: amazon-custom-metrics
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              k8s-cloudwatch-adapter-token
Events:              <none>
```
Pod logs
```
~ k_dev_new logs -f k8s-cloudwatch-adapter-fb66fd97f-56vcm  -n amazon-custom-metrics
F0411 09:33:49.242418       1 adapter.go:35] unable to construct client config: unable to construct lister client config to initialize provider: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

**Comment by gowthamakanthan** [comment]
Thanks for your comments @liggitt . Have removed `automountServiceAccountToken: false ` from the SA  and the `kubernetes.io/enforce-mountable-secrets` annotation on the secrets and redeployed the service.  Still having the same error. Any thoughts ?

```
F0411 14:27:37.266811       1 adapter.go:35] unable to construct client config: unable to construct lister client config to initialize provider: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

**Comment by liggitt** [comment]
What does the yaml for the running pod look like?

**Comment by gowthamakanthan** [comment]
Deployment, service, pod, sa Yaml has uploaded in the following gist
https://gist.github.com/gowthamakanthan/081d029fcd19725d994270984979e252

**Comment by liggitt** [comment]
https://gist.github.com/gowthamakanthan/081d029fcd19725d994270984979e252#file-gistfile1-txt-L38 is the issue

Your deployment is indicating it does not want a token mounted into the pods. That's why the process inside your pod is failing to see a mounted token.

**Comment by gowthamakanthan** [comment]
Thanks for finding that. have added `automountServiceAccountToken: true` for the `deployments, which moved to the `panic` error.

https://gist.github.com/gowthamakanthan/c7d32dd87f69756d8e2a5865fc45be83

```
 k_dev_new logs -f k8s-cloudwatch-adapter-7d5fbccdd-pddpg -n amazon-custom-metrics
I0411 15:40:19.555612       1 controller.go:35] Setting up external metric event handlers
I0411 15:40:19.560141       1 controller.go:57] initializing controller
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/awslabs/k8s-cloudwatch-adapter/pkg/aws.GetLocalRegion(0x0, 0x0)
	/go/src/github.com/awslabs/k8s-cloudwatch-adapter/pkg/aws/util.go:29 +0x27e
github.com/awslabs/k8s-cloudwatch-adapter/pkg/aws.NewCloudWatchManager(...)
	/go/src/github.com/awslabs/k8s-cloudwatch-adapter/pkg/aws/client.go:22
main.(*CloudWatchAdapter).makeCloudWatchManager(...)
	/go/src/github.com/awslabs/k8s-cloudwatch-adapter/cmd/adapter/adapter.go:28
main.main()
	/go/src/github.com/awslabs/k8s-cloudwatch-adapter/cmd/adapter/adapter.go:88 +0x256
```

**Comment by liggitt** [comment]
that looks like a bug in that controller that tries to index a zero-length body even when an error occurs: https://github.com/amazon-archives/k8s-cloudwatch-adapter/blob/master/pkg/aws/util.go#L23-L29

**Comment by rahulp223** [comment]
I have the same issue, reproducible on 2 clusters, one running v1.25.15 and the other running 1.26.10, both in Azure AKS.
I confirmed the service account exists but no secret is created.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-k8s-devops
  namespace: my-namespace
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: k8s-devops-secret
  namespace: my-namespace
  annotations:
    kubernetes.io/service-account.name: “sa-k8s-devops”
```

`$> kubectl  apply -f sa.yaml`
serviceaccount/sa-k8s-devops created
secret/k8s-devops-secret created

```
kubectl -n my-namespace get sa
NAME               SECRETS   AGE
default              0               104d
sa-k8s-devops  0               26s
```

Service account is created ....but 

```
$ kubectl -n my-namespace get secrets
NAME        TYPE                DATA   AGE
dbpass      Opaque              1      55d
dbuser      Opaque              1      55d
```

No secret created.

**Comment by liggitt** [comment]
your annotation might be malformed... instead of

```yaml
kubernetes.io/service-account.name: “sa-k8s-devops”
```
try
```yaml
kubernetes.io/service-account.name: "sa-k8s-devops"
```

(note the curly quotes instead of the straight quotes

**Comment by rahulp223** [comment]
> your annotation might be malformed... instead of
> 
> (note the curly quotes instead of the straight quotes)

That's how it got encoded in Github page, in the yaml I have, it is plain double quotes, I write the yaml in notepad first, so I'm sure this isn't the case of wrong type of quotes.

**Comment by bootcd** [comment]
I have the same issue, but i added namespace in secret metadata, and it`s resolve my problem.

Documentation says:

```
apiVersion: v1
kind: Secret
metadata:
  name: sa1-token
  annotations:
    kubernetes.io/service-account.name: sa1
type: kubernetes.io/service-account-token
```
But no new secrets listed with kubectl get secrets -A

But if add a namespace to metadata (this is my example):

```
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: gitlab
  annotations:
    kubernetes.io/service-account.name: "gitlab"
  namespace: kube-system

```
it`s listed good:

```
NAMESPACE       NAME                      TYPE                                  DATA   AGE
ingress-nginx   ingress-nginx-admission   Opaque                                3      4d22h
kube-system     bootstrap-token-4rjy48    bootstrap.kubernetes.io/token         6      13h
kube-system     gitlab                    kubernetes.io/service-account-token   3      3s
```
