### ISSUE TITLE
Inform users about unsupported PDB options

### ISSUE THREAD

**Issue by atiratree** [kubernetes/kubernetes#115435]
### What happened?

When using PDBs with `MaxUnavailable` or `MinAvailable` (percentage), it is not supported to reference pods via a PDB selector, that do not have a supported controller owner reference:
- Deployment, ReplicationController, ReplicaSet, and StatefulSet controllers
- or a resource implementing `/scale` subresource

This is also documented https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors 

Nevertheless, there are still people who create PDBs a pods without controllers  that ignore this. For example PDBs that set `MaxUnavailable: 0`, want to block eviction, and node drain (it works for them but the PDB status is invalid).

Unfortunately there is no feedback for the user to receive when this happens. The KCM logs is the only place that informs the user when unmanaged pods are found.

https://github.com/kubernetes/kubernetes/blob/f58f70bd5730658505042cd9baa80f72d3b6e31e/pkg/controller/disruption/disruption.go#L709

Which I think is insufficient.  

### What did you expect to happen?

There should be some way to inform users about this. Since it cannot be know on admission we probably have to do it when reconciling the PDB and unmanaged pods are found. Options:

1. create an event when this is detected - probably needs to be throttled in some way
2. manage a condition in a PDB status that would be set and admins could monitor these to detect misbehaving PDBs   

### How can we reproduce it (as minimally and precisely as possible)?

create a PDB

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-test
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
```

create unmanaged pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name:  nginx
      image: k8s.gcr.io/nginx-slim:0.8
```

observe incorrect status because this configuration is unsupported

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  generation: 1
  name: nginx-test
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
status:
  conditions:
  - lastTransitionTime: "2023-01-31T14:57:35Z"
    message: ""
    observedGeneration: 1
    reason: InsufficientPods
    status: "False"
    type: DisruptionAllowed
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0
  observedGeneration: 1
```

### Kubernetes version

<details>

NA

</details>

### Cloud provider

<details>
NA 
</details>

### OS version

<details>
NA
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
