### ISSUE TITLE
Allow type LoadBalancer for Headless service for specialized proxiers

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#115429]
## Feature requested

Allow type LoadBalancer for Headless service for specialized proxiers. A service of type LoadBalancer with clusterIP None is rejected with:

```
# kubectl create -f /etc/kubernetes/svc-headless-lb/svc.yaml 
The Service "alpine" is invalid: spec.clusterIPs[0]: Invalid value: "None": may not be set to 'None' for LoadBalancer services
```
Even if the [service.kubernetes.io/service-proxy-name](https://kubernetes.io/docs/reference/labels-annotations-taints/#servicekubernetesioservice-proxy-name) label is used.

<details><summary>manifest</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: alpine
  labels:
    service.kubernetes.io/service-proxy-name: kpng-example
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: alpine
  type: LoadBalancer
  clusterIP: None
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 5001
    name: nc
```

</details>

This is just a check, not that anything fails if the combination is allowed.

I want that check removed for specialized proxiers.

## Why?

A specialized proxier using the [service.kubernetes.io/service-proxy-name](https://kubernetes.io/docs/reference/labels-annotations-taints/#servicekubernetesioservice-proxy-name) label may handle external traffic, while it can't handle internal traffic to the `ClusterIP`. For such a service the combination `type:LoadBalancer` and `clusterIP:None` makes perfect sense. Otherwise one must document something like:

> Even though the clusterIP is defined with valid endpoints, **you can't use it** since the specialized proxier don't care about clusterIP.

Access to the service via DNS addresses which (provided for Headless services) is proably something the service _can_ handle, which make this feature _valuable_ and not just a cosmetic thing.

An example has been [discussed](https://github.com/kubernetes/enhancements/pull/2611#issuecomment-819125885) in the "All-IP service" context, and [considered breaking](https://github.com/kubernetes/enhancements/pull/2611#issuecomment-822063553). If the restriction is removed for specialized proxiers only, this will not be a problem.

/kind feature
/sig network
