### ISSUE TITLE
Kubernetes pod's request for 8 x 1Gi hugepages consumes all 16 x 1Gi hugepages on worker node

### ISSUE THREAD

**Issue by msbrod** [kubernetes/kubernetes#115581]
Kubernetes 1.24
Ubuntu 20.04
Kernel 5.8.0-53-generic 

NOTE:  Regarding formatting of this question, could not figure out why certain lines were crossed out and why I could not remove the bullet associated with the emptyDir.
_maintainer edit: have marked the relevant bits as preformatted_

Problem:  Worker node running Kubernetes 1.24 on ubuntu 20.04 kernel 5.8.0-53-generic is configured with 16 x 1Gi hugepages (8 per Numa node).  Before the kubernetes pod is deployed on this worker node, none of the hugepages are consumed.

```
ubuntu@worker-1:~$ cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/free_hugepages
8
ubuntu@worker-1:~$ cat /sys/devices/system/node/node1/hugepages/hugepages-1048576kB/free_hugepages
8

ubuntu@worker-1:~$ hugeadm --pool-list
libhugetlbfs: ERROR: Line too long when parsing mounts
      Size  Minimum  Current  Maximum  Default
   2097152        0        0        0        *
1073741824       16       16       16

ubuntu@worker-1:~$ hugeadm --page-sizes-all
libhugetlbfs: ERROR: Line too long when parsing mounts
2097152
1073741824

ubuntu@worker-1:~$ hugeadm --list-all-mounts
libhugetlbfs: ERROR: Line too long when parsing mounts
Mount Point          Options
/dev/hugepages       rw,relatime,pagesize=2M
```

After the Kubernetes pod is deployed on the worker node, even though it requests 8 x 1Gi, it receives 16 x 1Gi hugepages (8 from each Numa node).

```
ubuntu@worker-1:~$ cat /sys/devices/system/node/node0/hugepages/hugepages-1048576kB/free_hugepages
0
ubuntu@worker-1:~$ cat /sys/devices/system/node/node1/hugepages/hugepages-1048576kB/free_hugepages
0

ubuntu@worker-1:~$ hugeadm --list-all-mounts
libhugetlbfs: ERROR: Line too long when parsing mounts
Mount Point                                                                                             Options
/dev/hugepages                                                                                          rw,relatime,pagesize=2M
/var/lib/kubelet/pods/f9c5220e-be80-471d-8627-080054478b55/volumes/kubernetes.io~empty-dir/hugepage-1gi rw,relatime,pagesize=1024M
```
View of hugepage mount from worker node:
```
ubuntu@worker-1:~$ sudo ls /var/lib/kubelet/pods/f9c5220e-be80-471d-8627-080054478b55/volumes/kubernetes.io~empty-dir/hugepage-1gi
rtemap_0  rtemap_10  rtemap_12  rtemap_14  rtemap_2  rtemap_4  rtemap_6  rtemap_8
rtemap_1  rtemap_11  rtemap_13  rtemap_15  rtemap_3  rtemap_5  rtemap_7  rtemap_9
```
View of hugepage mount from within the pod:
```
[myself@mypod-0 /]$ ls /hugepages
rtemap_0  rtemap_10  rtemap_12  rtemap_14  rtemap_2  rtemap_4  rtemap_6  rtemap_8
rtemap_1  rtemap_11  rtemap_13  rtemap_15  rtemap_3  rtemap_5  rtemap_7  rtemap_9
```
Pod Hugepage Configuration requesting for 8 x 1Gi hugepages
```yaml
    resources:
      limits:
        cpu: "10"
        hugepages-1Gi: 8Gi
        memory: 52Gi
      requests:
        cpu: "10"
        hugepages-1Gi: 8Gi
        memory: 52Gi
      ...config left out...
    - mountPath: /hugepages
      name: hugepage-1gi
      ...config left out...
  - emptyDir:
      medium: HugePages
    name: hugepage-1gi
      ...config left out...
```
