### ISSUE TITLE
"pods/exec", "pods/attach", portforward not included in resources: ["*"] for dynamic admission webhooks configuration

### ISSUE THREAD

**Issue by RichardoC** [kubernetes/kubernetes#115523]
### What happened?

I'm the maintainer of [kube-audit-rest](https://github.com/RichardoC/kube-audit-rest) which relies on the fact that all creation/mutation API calls go through the [dynamic admission process](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) including exec and port forward commands, which show up using the special "CONNECT" verb on pods/exec, pods/attach and pods/portforward.

While testing I discovered that using the following rules doesn't cause these calls to be sent to my admission webhook regardless of whether it's a validating or mutating one. This is surprising as I'd expect all wildcards, or listing the exact operation I want to lead to my webhook being invoked.
```yaml
rules: # To be reduced as needed
      # Doesn't work 
      - operations: [ "*" ]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
        scope: "*"
      # Doesn't work
      - apiGroups: ["*"]
        apiVersions: ["*"]
        operations: ["CONNECT"]
        resources: ["*"]
```

### What did you expect to happen?

The following admission review to be sent to my webhook from all wildcard rules after the following command was run

```console
$ kubectl -n kube-system exec -it traefik-56b8c5fb5c-t4n8l whoami
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
whoami: unknown uid 65532
command terminated with exit code 1
```

```json
{"kind":"AdmissionReview","apiVersion":"admission.k8s.io/v1","request":{"uid":"0ef95324-2e35-4a8a-a9c9-0d843247242f","kind":{"group":"","version":"v1","kind":"PodExecOptions"},"resource":{"group":"","version":"v1","resource":"pods"},"subResource":"exec","requestKind":{"group":"","version":"v1","kind":"PodExecOptions"},"requestResource":{"group":"","version":"v1","resource":"pods"},"requestSubResource":"exec","name":"traefik-56b8c5fb5c-t4n8l","namespace":"kube-system","operation":"CONNECT","userInfo":{"username":"system:admin","groups":["system:masters","system:authenticated"]},"object":{"kind":"PodExecOptions","apiVersion":"v1","stdin":true,"stdout":true,"tty":true,"container":"traefik","command":["whoami"]},"oldObject":null,"dryRun":false,"options":null}}
```

### How can we reproduce it (as minimally and precisely as possible)?

Run the following WebhookConfiguration, with either kind ValidatingWebhookConfiguration or MutatingWebhookConfiguration

Pointing to anything that can log out the request (can provide kube-audit-rest steps if required)

run some kubectl exec, or kubectl attach with the "Doesn't work" rules below and see that the requests are not sent to your webhook

```yaml
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration # Can also be a MutatingWebhookConfiguration if required
metadata:
  name: kube-audit-rest
  labels:
    app: kube-audit-rest
webhooks:
  - name: kube-audit-rest.kube-audit-rest.svc.cluster.local
    failurePolicy: Ignore # Don't block requests if auditing fails
    timeoutSeconds: 1 # To prevent excessively slowing everything
    sideEffects: None
    clientConfig:
      service:
        name: kube-audit-rest
        namespace: kube-audit-rest
        path: "/log-request"
      caBundle: "$CABUNDLEB64" # To be replaced
    rules: 
      # Doesn't work 
      # - operations: [ "*" ]
      #   apiGroups: ["*"]
      #   apiVersions: ["*"]
      #   resources: ["*"]
      #   scope: "*"
      # Works
      # - apiGroups: ["*"]
      #   apiVersions: ["*"]
      #   operations: ["*"]
      #   resources: ["pods/exec", "pods/attach", "pods/portforward"]      
      # Works
      # - apiGroups: ["*"]
      #   apiVersions: ["*"]
      #   operations: ["CONNECT"]
      #   resources: ["pods/exec", "pods/attach", "pods/portforward"]
      # Doesn't work
      # - apiGroups: ["*"]
      #   apiVersions: ["*"]
      #   operations: ["CONNECT"]
      #   resources: ["*"]
    admissionReviewVersions: ["v1"]
    ```

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0+k3s2", GitCommit:"f0ec6a4c127b2c671b271974a2f21783f0e3c525", GitTreeState:"clean", BuildDate:"2023-01-11T21:36:41Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Rancher Desktop 1.7.0
</details>

### OS version

<details>

```console
$ rdctl shell cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.3
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
BUILD_ID="v0.2.25.rd2"
VARIANT_ID="rd"
$ rdctl shell uname -a
Linux lima-rancher-desktop 5.15.78-0-virt #1-Alpine SMP Fri, 11 Nov 2022 10:19:45 +0000 x86_64 Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
