### ISSUE TITLE
Pod Failure Policy Edge Case: Job Retries When Pod Finishes Successfully

### ISSUE THREAD

**Issue by jensentanlo** [kubernetes/kubernetes#115688]
### What happened?

I've noticed an edge case when trying out the PodFailurePolicy example from Story 3 of the KEP. When a pod is marked as a DisruptionTarget but then completes successful, it retries anyways. I wasn't able to add some sort of Ignore rule to exclude the 0 case

### What did you expect to happen?

I'm not sure what the expected behavior should be, but I expected that the job should succeed.

### How can we reproduce it (as minimally and precisely as possible)?

Here's a job that reproduces the issue 99% of the time

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      activeDeadlineSeconds: 60
      containers:
        - name: busybox
          image: busybox
          command: ["sleep", "1m"]
      restartPolicy: Never
  backoffLimit: 3
  podFailurePolicy:
    rules:
      - action: Count
        onPodConditions:
          - type: DisruptionTarget
      - action: FailJob
        onExitCodes:
          operator: NotIn
          values: [0]
```

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1-gke.200", GitCommit:"e7a3bc760915b7368460d2ed0bd2c2568645ab70", GitTreeState:"clean", BuildDate:"2023-01-20T09:28:11Z", GoVersion:"go1.19.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
In your yaml, it seems that this is a single pod Job. Since you say the pod is succeeding, is the job marked as succeeded even after creating a replacement pod? This can help us understand whether there is an additional problem.

**Comment by jensentanlo** [comment]
> In your yaml, it seems that this is a single pod Job. Since you say the pod is succeeding, is the job marked as succeeded even after creating a replacement pod? This can help us understand whether there is an additional problem.

Looks like it fails with a backoff limit error.

```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"test-job","namespace":"default"},"spec":{"backoffLimit":3,"podFailurePolicy":{"rules":[{"action":"Count","onPodConditions":[{"type":"DisruptionTarget"}]},{"action":"FailJob","onExitCodes":{"operator":"NotIn","values":[0]}}]},"template":{"spec":{"activeDeadlineSeconds":60,"containers":[{"command":["sleep","1m"],"image":"busybox","name":"busybox"}],"restartPolicy":"Never"}}}}
  creationTimestamp: "2023-02-10T16:52:04Z"
  generation: 1
  labels:
    controller-uid: 74b33f35-dd4c-4504-9c11-13ae7f99356e
    job-name: test-job
  name: test-job
  namespace: default
  resourceVersion: "25103390"
  uid: 74b33f35-dd4c-4504-9c11-13ae7f99356e
spec:
  backoffLimit: 3
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  podFailurePolicy:
    rules:
    - action: Count
      onExitCodes: null
      onPodConditions:
      - status: "True"
        type: DisruptionTarget
    - action: FailJob
      onExitCodes:
        containerName: null
        operator: NotIn
        values:
        - 0
      onPodConditions: null
  selector:
    matchLabels:
      controller-uid: 74b33f35-dd4c-4504-9c11-13ae7f99356e
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 74b33f35-dd4c-4504-9c11-13ae7f99356e
        job-name: test-job
    spec:
      activeDeadlineSeconds: 60
      containers:
      - command:
        - sleep
        - 1m
        image: busybox
        imagePullPolicy: Always
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastProbeTime: "2023-02-10T16:57:21Z"
    lastTransitionTime: "2023-02-10T16:57:21Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 4
  ready: 0
  startTime: "2023-02-10T16:52:04Z"
  uncountedTerminatedPods: {}
```

**Comment by alculquicondor** [comment]
And how are the pods terminating? Are you reproducing by deleting the Pod?

A local run of `busybox sleep 1m`, followed by ctrl-C gives me a 130 exit code.

**Comment by jensentanlo** [comment]
> And how are the pods terminating? Are you reproducing by deleting the Pod?
> 
> A local run of `busybox sleep 1m`, followed by ctrl-C gives me a 130 exit code.

The pod is deleted because "activeDeadlineSeconds: 60" is the same as the sleep duration, so you can reproduce this by just applying the yaml and letting it run to completion

**Comment by alculquicondor** [comment]
Ah ok, so this seems to be WAI from the job controller perspective. Not sure why a pod would be marked as Failed if it exits with exit code 0.
@bobbypage, can you provide some context?

/sig node

**Comment by alculquicondor** [comment]
Highlighting the important bits:

```yaml
  containerStatuses:
  - containerID: containerd://9529ee05bd276a70d534a3688639596b0a96e06b8b3f111da9008a99bdb8b0ea
    image: docker.io/library/busybox:latest
    name: busybox
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        exitCode: 0
        finishedAt: "2023-02-10T18:52:46Z"
        reason: Completed
  message: Pod was active on the node longer than the specified deadline
  phase: Failed
```

**Comment by Cool-Coder174** [comment]
Have you tried re-writing your code? You can try modifying the rules field of the podFailurePolicy as follows:
,,,
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      activeDeadlineSeconds: 60
      containers:
        - name: busybox
          image: busybox
          command: ["sleep", "1m"]
      restartPolicy: Never
  backoffLimit: 3
  podFailurePolicy:
    rules:
      - action: Count
        onPodConditions:
          - type: DisruptionTarget
      - action: FailJob
        onExitCodes:
          operator: In
          values: [1, 2, 3, ..., 255]
,,,

The modification specifies that the job should only fail if the exit code is one of the values in the range [1, 2, 3, ..., 255]. This should exclude the exit code 0 and resolve the issue with retrying the pod when it completes successfully.

**Comment by jensentanlo** [comment]
@Cool-Coder174 I think that our podFailurePolicies are basically the same. The rules are applied sequentially so first it checks for DisruptionTarget, then it checks for the exit code.

In the yaml I provided, I use NotIn [0].

**Comment by bobbypage** [comment]
> Ah ok, so this seems to be WAI from the job controller perspective. Not sure why a pod would be marked as Failed if it exits with exit code 0. @bobbypage, can you provide some context?
> 
> /sig node

I think in this case the pod is being marked as Failed because it exceeded the `activeDeadlineSeconds`. The reproduction script has a busybox sleep of 1 minute and the activeDeadlineSeconds is also 60 seconds. So it seems like there is a race here between the containers terminating and the active deadline seconds.

**Comment by mimowo** [comment]
> @Cool-Coder174 I think that our podFailurePolicies are basically the same. The rules are applied sequentially so first it checks for DisruptionTarget, then it checks for the exit code.
> 
> In the yaml I provided, I use NotIn [0].

Yes, the rule with `In` 1..255 is the same as the `NotIn` for 0. However, you can do the following workaround to cover `0` with `FailJob` action.

```yaml
  podFailurePolicy:
    rules:
      - action: Count
        onPodConditions:
          - type: DisruptionTarget
      - action: FailJob   # this rules covers all exit codes != 0
        onExitCodes:
          operator: NotIn
          values: [0]
      - action: FailJob   # this rules covers all exit codes != 1, but effectively when exit code = 0
        onExitCodes:
          operator: NotIn
          values: [1]
``` 

Also note, that the behavior that an individual pod is in `Failed` phase, when the container exit code equals 0 can be reproduced at the pod level, with the following example: 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pob
spec:
  activeDeadlineSeconds: 60
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "1m"]
  restartPolicy: Never
```

**Comment by mimowo** [comment]
So I think what might be missing here is a cleaner API to express that:
```yaml
      - action: FailJob   # this rules covers all exit codes != 0
        onExitCodes:
          operator: NotIn
          values: [0]
      - action: FailJob   # this rules covers all exit codes != 1, but effectively when exit code = 0
        onExitCodes:
          operator: NotIn
          values: [1]
```
For that we could relax the validation for the `In` operator to allow for `0`.

**Comment by alculquicondor** [comment]
Before we do that in the Job validation, I want to have a clear understanding whether this is expected behavior in kubelet.

**Comment by mimowo** [comment]
I was consulting this with @bobbypage and it seems the fact that the pod is failed and the container has 0 exit codes is WAI by Kubelet. There are also other eviction scenarios in which this can happen. So I think we should open a PR to relax the validation.

**Comment by alculquicondor** [comment]
+1

The only thing to note is that relaxing validation requires 2 releases:

- In release N, we allow Job updates to have a policy with exit code zero, if they already had it.
- In release N+1, we allow Job creations with exit code zero.

This is similar to adding a new Enum value https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#new-enum-value-in-existing-field

/help

**Comment by kidddddddddddddddddddddd** [comment]
I'd like to work on this one as this issue is labels `help wanted`, and @mimowo closed #115841 .
/assign

**Comment by kidddddddddddddddddddddd** [comment]
> One extra decision to make is how to handle `NotIn`. Currently `NotIn: [1,2,3]` would not match `0`, but it would match `4`. I think it makes sense to keep the logic for `NotIn` and just extend it for `In`. WDYT?

I think the reason why this issue happened is because we allowed users to use `0` in `NotIn`, but we don't really deal with it.https://github.com/kubernetes/kubernetes/blob/c9ff2866682432075da1a961bc5c3f681b34c8ea/pkg/controller/job/pod_failure_policy.go#L100
So the key movement is to remove this line, but not the logic for `NotIn`, am I right?
I saw #115688 before, and I think you have done the most of the work, it's just we have to add a feature gate to control the relaxing.

**Comment by mimowo** [comment]
> So the key movement is to remove this line, but not the logic for `NotIn`, am I right?

I **think** so. Hence, one possible solution is to remove this line, and handle `0` inside the `isOnExitCodesOperatorMatching` function under the `NotIn` case.

**Comment by kidddddddddddddddddddddd** [comment]
I got confused by writing the related code:

1. Currently, I just removed the check for `exitcode!=0`:

https://github.com/kubernetes/kubernetes/blob/c9ff2866682432075da1a961bc5c3f681b34c8ea/pkg/controller/job/pod_failure_policy.go#L100

so if the config is like `operator: NotIn values: [1]`, and container exits with code `0`, I think previouly we will return a nil in `matchOnExitCodes`, but currently we'll return the corresponding container, is this acceptable?

2. If the config is like `operator: NotIn values: [0]`, and container exits with code 0. I think previouly we got a nil in `getMatchingContainerFromList` because we only check rules when exit codes aren't 0. After this change, we try to match containers, but we'll still get a nil, because the code doesn't match the rule. 
So it seems that we always get a nil for `matchOnExitCodes` before and after this code change. And how does this behavior help with this issue?

I'd be glad if someone can answer my questions :)

**Comment by mimowo** [comment]
> 3\. And how does this behavior help with this issue?

This should solve the issue for the `In` operator. However, as you point out removal of the line changes logic for the `NotIn` operator, in a non-obvious way, as a side effect. 

I think it makes sense to keep the current behavior for the `NotIn` operator to be backward-compatible, in that case, one solution is to exclude containers with 0 exit code here: https://github.com/kubernetes/kubernetes/blob/c9ff2866682432075da1a961bc5c3f681b34c8ea/pkg/controller/job/pod_failure_policy.go#L120 inject `if exitCode == 0 { return false }`.

**Comment by alculquicondor** [comment]
> One extra decision to make is how to handle `NotIn`. Currently `NotIn: [1,2,3]` would not match `0`, but it would match `4`. I think it makes sense to keep the logic for `NotIn` and just extend it for `In`. WDYT?

I think we should maintain consistency and make it match `0`. Since the feature is beta we are allowed to change the behavior, given the proper release note.

**Comment by mimowo** [comment]
> I think we should maintain consistency and make it match `0`. Since the feature is beta we are allowed to change the behavior, given the proper release note and documentation updates.

+1 This makes sense.

> I didn't find where to update documentation.

A couple of places will need adjustments:
1. The API field description: 
  - https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/types.go#L145-L146
  - https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/types.go#L155-L157
  
2. KEP:
 - https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3329-retriable-and-non-retriable-failures#jobspec-api
 - https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3329-retriable-and-non-retriable-failures#story-3
 here I think we could extend the example with (along with a comment):
 ```yaml
     - action: FailJob
      onExitCodes:
        operator: In
        values: [0]
```

3. user-facing documentation (but it does not seem to be affected by the change):
- https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-failure-policy
- https://kubernetes.io/docs/tasks/job/pod-failure-policy/
