### ISSUE TITLE
Manually created Endpoints for a headless Service are deleted when kube-controller-manager Pod restarted

### ISSUE THREAD

**Issue by DmytroLinkin** [kubernetes/kubernetes#115801]
### What happened?

Initially issue was observed using downstream version of ovn-kubernetes deployment. ovn-kubernetes central components include ovn database pod (ovnkube-db) along with a headless service and endpoints created by this pod. Database pod contains two databases - northbound and southbound, hence endpoints are created for each database as a *separate endpoints object*.
When all central components are deployed, images pull process may significantly consume a CPU, which cause kube-controller-manager to restart because readiness probe temporarily loses connection to tcp socket. If ovnkube-db pod had managed to create endpoints before kube-controll-manager initialization - they are being deleted.

### What did you expect to happen?

Endpoints to not being deleted.

### How can we reproduce it (as minimally and precisely as possible)?

Create headless service and endpoints, using following yaml:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  ports:
  - name: port-a
    port: 4455
    protocol: TCP
    targetPort: 4455
  - name: port-b
    port: 4456
    protocol: TCP
    targetPort: 4456
  sessionAffinity: None
  clusterIP: None
  type: ClusterIP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service-a
  namespace: default
subsets:
  - addresses:
    - ip: 10.237.121.204
    ports:
    - name: port-a
      port: 4455
      protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service-b
  namespace: default
subsets:
  - addresses:
    - ip: 10.237.121.204
    ports:
    - name: port-b
      port: 4456
      protocol: TCP
```

Run `kubectl get ep` and see endpoints in the output.
Then trigger kube-controller-manager to restart. It can be one of:
- stop kube-controll-manager container
- set iptables rule `INPUT -p tcp --dport 10257 -j REJECT` and then remove it after pod restarted
- pull few big images

When kube-controller-manager pod will be `Ready`, observe endpoints will be deleted after some time.

### Anything else we need to know?

Downstream version of ovn-kubernetes have database endpoints defined as a separate endpoints objects for the purpose of updating a single endpoint without affecting the other. If endpoint object have same `metadata.name` as a service (like upstream ovn-kubernetes version with a single endpoints object), it is not deleted.
If EndpointSlices are used instead of Endpoints they are also not deleted.

### Kubernetes version

<details>

First met at

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T15:54:23Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

Recently reproduced at

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"

$ uname -a
Linux cloud-dev-78-204 5.14.0-162.6.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 18 02:06:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
`kubeadm init` with `--skip-phases=addon/kube-proxy` in case of OVNK8s
</details>

### Container runtime (CRI) and version (if applicable)

<details>

containerd containerd.io 1.6.16 31aa4358a36870b21a992d3ad2bef29e1d693bec
crictl version v1.26.0

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

ovn-kubernetes downstream version is not available publicly, sorry.

</details>
