### ISSUE TITLE
control pod name on headless without selector

### ISSUE THREAD

**Issue by christiancadieux** [kubernetes/kubernetes#115941]
### What would you like to be added?

headless services without selectors can be used to access external resources. Example:
```
apiVersion: v1
kind: Service
metadata:
  name: yb-masters
spec:
  clusterIP: None
  ports:
  - name: tcp-rpc-port
    port: 7100
    protocol: TCP
    targetPort: 7100
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: yb-masters2
  labels:
    kubernetes.io/service-name: yb-masters
addressType: IPv4
ports:
  - name: tcp-rpc-port
    protocol: TCP
    port: 7100
endpoints:
  - addresses:
      - 10.60.7.13
    conditions:
      ready: true
```

this will generate a headless service `yb-masters.namespace...` 
but since these is no pod attached (there is no selector and the endpointslice was manually created), the 
dns names look like this: 
```
10-60-7-13.yb-masters2.rdei-yb-zone3.svc.cluster.local    << uses the addresses IP as pod name in the headless dns.
```
would be nice if there was a way, maybe with annotations, to control the podname being used. 
For example:
```
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
   annotation: 
        kubernetes.io/headless.podname : "yb-master-0"
...
```
so that the address 10.60.7.13:7100 can be accessed with this dns entry:
```
yb-master-0.yb-masters2.rdei-yb-zone3.svc.cluster.local 
```
I realize that headless bind to multiple pods, so maybe allow a comma-separated list in the annotation. 

### Why is this needed?

this would allow to very easily create meshes for headless services where some services of a statefulset like yugabyte can
run locally in cluster1 and some services can be mapped to external services running in a different cluster.
