### ISSUE TITLE
Required value: must be only one value when `operator` is 'In' or 'NotIn' for node field selector

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#115980]
### What happened?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchFields:
              - key: metadata.name
                operator: In
                values:
                - 192.168.229.153
                - 192.168.229.156
      containers:
      - image: nginx
        name: nginx

```

[root@localhost resourceBinding]# kubectl apply -f nginx-deploy-affinity-matchFields.yaml -n karmada --kubeconfig ~/kube-karmada 
The Deployment "nginx" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchFields[0].values: Required value: must be only one value when `operator` is 'In' or 'NotIn' for node field selector

### What did you expect to happen?

In NotIn is multi value

### How can we reproduce it (as minimally and precisely as possible)?

apply the yaml

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
[root@localhost resourceBinding]# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>

</details>
vmware

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blame/b8ef5be44f4d54b29751d0a7cc6d536be546c356/pkg/apis/core/validation/validation.go#L3942

I cannot find any explanation about it and you may use `matchExpressions`.

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node-2
                - node-4
                - paco-centos-9
                
```
