### ISSUE TITLE
Pods of successful jobs show as OOMKilled

### ISSUE THREAD

**Issue by jgoeres** [kubernetes/kubernetes#116042]
### What happened?

We are recently observing a number of job pods that had been running on a node with memory pressure that are shown as OOMKilled. Looking closer, the jobs are, however, successful/succeeded in almost all cases, e.g.

```
$ kubectl get pods | grep OOMK
job1-2k5bx   0/1     OOMKilled          0                143m
job2-fsdst   0/4     OOMKilled          0                143m
job3-st585   0/1     OOMKilled          0                143m
job4-2k7fb   0/1     OOMKilled          0                143m

$ kubectl get jobs 
NAME COMPLETIONS   DURATION   AGE
job1   1/1           4m21s      143m
job2   1/1           10m        143m
job3   1/1           10m        143m
job4   1/1           2m21s      143m
```
Describing the pods and jobs confirms that, e.g.

```$ kubectl describe pod job1-2k5bx
Name:         job-2k5bx
Namespace:    somenamespace
[...]
Status:       Succeeded
[...]
Containers:
  job:
  [...]
    State:          Terminated
      Reason:       OOMKilled
      Exit Code:    0
      Started:      Fri, 24 Feb 2023 11:33:19 +0000
      Finished:     Fri, 24 Feb 2023 11:37:34 +0000
    Ready:          False
    Restart Count:  0
[...]
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
[...]
Events:             <none>
```
Observe Status: "Succeeded"

```
$ kubectl describe job -n job1
Name:             job1
Namespace:        somenamespace
[...]
Completions:      1
Completion Mode:  NonIndexed
[...]
Pods Statuses:    0 Active (0 Ready) / 1 Succeeded / 0 Failed
Events:                              <none>
```

Observe the pod statuses: "1 Succeeded"

### What did you expect to happen?

A completed job pod should be and stay in status Completed, even if some OOM-killing happened on that node.

### How can we reproduce it (as minimally and precisely as possible)?

Fill a node to the brim with regular pods and some jobs. Let some pods exceed their memory requests, that should give you OOMKilled pods, including some of the completed jobs.

### Kubernetes version

v1.24.8-eks-ffeb93d

### Cloud provider

AWS EKS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chenyw1990** [comment]
@jgoeres can you upload kubelet's on the node which job1-2k5bx  、job2-fsdst 、job3-st585、job4-2k7fb runs on

**Comment by saschagrunert** [comment]
I'm not able to reproduce this with Kubernetes 931e07de169. Also not with v1.26.2.

I used the job:

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
      - name: ctr
        image: alpine:3
        command: ["sh", "-c", "sleep 3 && dd if=/dev/zero of=/dev/null bs=20M"]
        resources:
          requests:
            memory: "15Mi"
          limits:
            memory: "15Mi"
      restartPolicy: Never
  backoffLimit: 1
```

And always got:

```
NAME            COMPLETIONS   DURATION   AGE
job.batch/job   0/1           17s        17s

NAME            READY   STATUS      RESTARTS   AGE
pod/job-4tzrj   0/1     OOMKilled   0          10s
pod/job-bh95t   0/1     OOMKilled   0          17s
```
