### ISSUE TITLE
ttlSecondsAfterFinished Ignored for jobs

### ISSUE THREAD

**Issue by yonahd** [kubernetes/kubernetes#116008]
### What happened?

When running a Job in Kubernetes 1.23 the job gets terminated immediately and not respecting ttlSecondsAfterFinished.

### What did you expect to happen?

Expected the job to stay alive for the timeframe defined in ttlSecondsAfterFinished

### How can we reproduce it (as minimally and precisely as possible)?

Create a job using 

```
apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
```

### Kubernetes version

<details>

```console
$ kubectl version
# Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T15:54:23Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
