### ISSUE TITLE
Allowing overwritable DNS options for ClusterFirst and ClusterFirstWithHostNet  policy in the kubelet configuration

### ISSUE THREAD

**Issue by eminaktas** [kubernetes/kubernetes#116117]
### What would you like to be added?

In the `KubeletConfiguration` [here](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration), I want to have more options for DNS to override the Cluster Level DNS configuration for `ClusterFirst` and `ClusterFirstWithHostNet` policies. I am not including the other policies since they are bound the the `resolv.conf` file since we don't want to override the values provided in the K8s manifests.

| Field               | Description |
| ------------- | -----------  |
| dnsOptions  [DNSConfigOption](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#poddnsconfigoption-v1-core)  | [Options](https://man7.org/linux/man-pages/man5/resolv.conf.5.html#:~:text=The%20resolver%20configuration%20file%20contains,various%20types%20of%20resolver%20information.) allows certain internal resolver variables to be modified.  Default: nil   |

Example usage in a `kubelet-config.yaml`: 

```yaml
dnsOptions:
  ndots: 2
  timeout: 1
  attempts: 1
```

This option can be evaluated at `GetPodDNS` function [here](https://github.com/kubernetes/kubernetes/blob/aad305051934350e8f51d57a852a0ba390f97757/pkg/kubelet/network/dns/dns.go#L401-L421). 

Or, we can make it more configurable by using the same `dnsConfig` in the Pod manifests.

| Field               | Description |
| ------------- | -----------  |
| dnsConfig  [DNSConfig](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#poddnsconfig-v1-core)  | TODO.  Default: nil   |

```yaml
dnsConfig:
  nameservers:
    - 192.0.2.1 # this is an example
  searches:
    - ns1.svc.cluster-domain.example
    - my.dns.search.suffix
  options:
    - name: ndots
      value: "2"
    - name: edns0
```

### Why is this needed?

Today's Kubernetes does not allow us to override the DNS options in Kubelet's configs. In order to override the DNS configuration for the Pods, as a workaround, we must add the DNS configuration in the manifest files

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-example
spec:
  containers:
    - name: test
      image: nginx
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 192.0.2.1 # this is an example
    searches:
      - ns1.svc.cluster-domain.example
      - my.dns.search.suffix
    options:
      - name: ndots
        value: "2"
      - name: edns0
```

or use a mutation webhook to change DNS options for every deployment. However, we can eliminate this by making this externally configurable.

/cc @Dentrax

**Comment by aojea** [comment]
Can you expand more on the description and the use cases, I'm a bit confused on which part you want to override , the kubelet dns config or the pod spec config?

**Comment by eminaktas** [comment]
> Can you expand more on the description and the use cases, I'm a bit confused on which part you want to override , the kubelet dns config or the pod spec config?

@aojea thanks for your interest. I am sorry about it. I just updated the description and the use cases.

I simply want to be able to override the default DNS configuration on the cluster level.

**Comment by aojea** [comment]
> I simply want to be able to override the default DNS configuration on the cluster level.

yeah, I think there are a similar ones, but this issue is really well explained.

The proposal is for `KubeletConfiguration` that is owned by sig-node, it seems the config is v1 now https://kubernetes.io/docs/reference/config-api/kubelet-config.v1/ and that implies change should be backward compatible

/sig-node

**Comment by eminaktas** [comment]
> > I simply want to be able to override the default DNS configuration on the cluster level.
> 
> yeah, I think there are a similar ones, but this issue is really well explained.
> 
> The proposal is for `KubeletConfiguration` that is owned by sig-node, it seems the config is v1 now https://kubernetes.io/docs/reference/config-api/kubelet-config.v1/ and that implies change should be backward compatible
> 
> /sig-node

Thanks 🙏 

/sig node

**Comment by thockin** [comment]
I don't think the answer is to stick it into KubeletConfig, which is not easily (or at all) accessible in some environments.

If we wanted to do this, we're sort of talking about an API resource, a la `GatewayClass` or `StorageClass`.  I'm not endorsing this idea yet, just saying that it's the logical conclusion.

**Comment by eminaktas** [comment]
We'd like to work on this task. Introducing an API resource could more logical solution and I liked the idea more. Kubernetes users could have more control over DNS configuration.

If you agree on letting us take on this task, I'd like to first work on the idea. At least, you can agree on the work first. Then, I can submit a KEP about _DNSClass_ to discuss.

Thanks, @thockin 

cc @Dentrax

**Comment by aojea** [comment]
> If you agree on letting us take on this task, I'd like to first work on the idea. At least, you can agree on the work first. Then, I can submit a KEP about _DNSClass_ to discuss.

/assign @eminaktas 

Important thing you should detail in the KEP from the top of my head:
- conflict resolution between flags, config file and new API mode: who takes precedence?
- upgrades/downgrades: I start using the new API from an existing cluster, I don't feel comfortable and I roll back the change to keep using the config file
- reconciliation of configurations, can I change the current config, what happens with running pods?
- network partition scenarios kubelet goes offline

**Comment by thockin** [comment]
I'm not against anyone spending time thinking about it, but I want to be clear that the priority of this is probably lower than most of the other in-flight KEPs, so it's possible it won't get the largest share of attention (IOW - slower feedback)

**Comment by eminaktas** [comment]
Hi, I understand your situation, and I believe we can gradually make progress on this matter. I have created a draft for the idea, which you can read and provide comments on. I would appreciate your endorsement of the idea so that we can proceed further with this subject.

https://hackmd.io/@g49GPvqbTXKXQGWM4uzg1g/rJ7s2uU72

Additionally, I have been considering the updates to DNSClass and whether they should necessitate a pod restart. However, I was wondering if it is possible to achieve these updates without requiring a restart. I believe that requiring rescheduling would be a safer approach, as administrators or users can reschedule the pods in a controlled manner. I am eager to hear your thoughts and ideas on this matter, especially regarding the feasibility of implementing these updates without the need for rescheduling.

**Comment by eminaktas** [comment]
Hello again, This issue has been sitting here quite while in a silent mode. I decided to create a project where we can have this feature with an operator. Here is the repository link: https://github.com/eminaktas/kubedns-shepherd

In this project, I basically created a cluster wide DNSClass CRD to define DNS configuration with various settings. You can find all samples [here](https://github.com/eminaktas/kubedns-shepherd/tree/main/config/samples).

For example; 
```yaml
apiVersion: config.kubedns-shepherd.io/v1alpha1
kind: DNSClass
metadata:
  labels:
    app.kubernetes.io/name: dnsclass
    app.kubernetes.io/instance: dnsclass-sample
    app.kubernetes.io/part-of: kubedns-shepherd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubedns-shepherd
  name: dnsclass-sample
spec:
  allowedNamespaces:
    - default
  disabledNamespaces:
    - kube-system
  dnsConfig:
    nameservers:
      - 10.96.0.10
    searches:
      - svc.cluster.local
    options:
      - name: ndots
        value: "2"
      - name: edns0 
```

#### How it works

We utilize webhooks in the project. Whenever a pod comes in cluster, it will mutate the pod with user defined dns configuration. I also added a few features that I thought users could utilize in their envs. For example, whenever DNSClass is created or updated, it will restart the pods that matches with DNSClass.

**Comment by thockin** [comment]
This sounds like a great thing to exist as an optional operator!  What sort of feedback are you looking for, specifically?

**Comment by aojea** [comment]
> For example, whenever DNSClass is created or updated, it will restart the pods that matches with DNSClass.

disrupting users workloads without notice is going to have a negative impact on users

**Comment by eminaktas** [comment]
> > For example, whenever DNSClass is created or updated, it will restart the pods that matches with DNSClass.
> 
> disrupting users workloads without notice is going to have a negative impact on users

I have added an option to disable it. I should've mentioned it in the example earlier. It distributes pods by default but it can be disabled. Based on your comment, Should I disable it by default? 

```yaml
apiVersion: config.kubedns-shepherd.io/v1alpha1
kind: DNSClass
metadata:
  labels:
    app.kubernetes.io/name: dnsclass
    app.kubernetes.io/instance: dnsclass-sample
    app.kubernetes.io/part-of: kubedns-shepherd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubedns-shepherd
  name: dnsclass-all-namespaces-sample
spec:
  # If set, this flag disables dynamic DNS configuration for pods. This feature is not disabled by default,
  # any changes to DNSClass configuration or the addition of a new DNSClass will trigger a restart of
  # all pods affected by these changes to apply the new DNS configuration.
  disablePodRestart: false
  disabledNamespaces:
  - kube-system
  allowedDNSPolicies:
  - None
  - ClusterFirst
  - ClusterFirstWithHostNet
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 10.96.0.10
    searches:
      - svc.cluster.local
    options:
      - name: ndots
        value: "2"
      - name: edns0 
```
