### ISSUE TITLE
One versioned resource, two versioned CRDs, two informers events.

### ISSUE THREAD

**Issue by ivanmatmati** [kubernetes/kubernetes#116136]
### What happened?

We created CRD with now two versions: v1alpha1 and v1alpha2. Their relative configuration is as follows:
```yaml
 ...
  versions:
    - name: v1alpha1
      served: true
      storage: false
      deprecated: true
      ...
   - name: v1alpha2
      served: true
      storage: true
```
We use the generated informers to get events from these two versions. But when creating a resource with :
```yaml
apiVersion: core.haproxy.org/v1alpha2
kind: Backend
metadata:
  name: example-backend-alpha1
  namespace: default
```
We get two events for this very single resource. One for v1alpha1 and an other for v1alpha2. NB: we don't use conversion strategy.

### What did you expect to happen?

As I created a resource with a specific version I expected a single event for this resource in the correct versioned informer.

### How can we reproduce it (as minimally and precisely as possible)?

Create a yaml for a versioned CRD with two versions and set their version fields according the values in the presentation of the issue. Generate the code for your custom resource then configure and use the related informers for both versions. Create a resource for a single version, check you get two events from informers.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-06-22T04:47:11Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Tested on-premise.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
$ uname -a
Linux midgard 5.15.94-1-MANJARO #1 SMP PREEMPT Tue Feb 14 19:45:58 UTC 2023 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
