### ISSUE TITLE
Kubelet e2e tests are failing on public ubuntu-2204-jammy GCE images 

### ISSUE THREAD

**Issue by upodroid** [kubernetes/kubernetes#116112]
### What happened?

I'm working with @dims and @tzneal on enabling e2e tests on AWS. We want to run many e2e tests on there as we have alot of AWS credits to consume. As part of that journey, we need to start building on public GCE ubuntu images instead of COS and the custom Google Ubuntu Images that we build from.

My working theory is that there is minimal differences between the ubuntu2204 images on AWS/GCP if they are built from a public cloud-init file that doesn't rely on instance-metadata features of either cloud.

cloud-init file + configure.sh is available at https://github.com/containerd/containerd/pull/8170
Current image matrix used for testing:
https://github.com/kubernetes/test-infra/blob/master/jobs/e2e_node/containerd/containerd-main/image-config.yaml

```
images:
  ubuntu:
    image_family: pipeline-1-24
    project: ubuntu-os-gke-cloud
    metadata: "user-data</go/src/github.com/containerd/containerd/test/e2e_node/init.yaml,containerd-configure-sh</go/src/github.com/containerd/containerd/cluster/gce/configure.sh,containerd-env</workspace/test-infra/jobs/e2e_node/containerd/containerd-main/env"
  cos-stable:
    image_family: cos-stable
    project: cos-cloud
    metadata: "user-data</go/src/github.com/containerd/containerd/test/e2e_node/init.yaml,containerd-configure-sh</go/src/github.com/containerd/containerd/cluster/gce/configure.sh,containerd-extra-init-sh</go/src/github.com/containerd/containerd/test/e2e_node/gci-init.sh,containerd-env</workspace/test-infra/jobs/e2e_node/containerd/containerd-main/env,gci-update-strategy=update_disabled"
```

Proposed Image Config: https://github.com/kubernetes/test-infra/pull/28856

This image config can't be enabled yet as the tests are failing right now.

### What did you expect to happen?

Build Args:

```
REDACTED@knative-e2e:~/tz-kubernetes$ cat ~/k8s-test-infra/jobs/e2e_node/containerd/containerd-main/image-config.yaml
images:
  ubuntu:
    image_family: ubuntu-2204-lts
    project: ubuntu-os-cloud
    metadata: "user-data</home/REDACTED/k8s-test-infra/jobs/e2e_node/containerd/containerd-main/ubuntu-init.yaml"
    
 
REDACTED@knative-e2e:~/tz-kubernetes$ make test-e2e-node REMOTE=true REMOTE_MODE=gce IMAGE_CONFIG_FILE=~/k8s-test-infra/jobs/e2e_node/containerd/containerd-main/image-config.yaml
```

Result

```
Summarizing 5 Failures:
  [FAIL] [sig-node] Summary API [NodeConformance] when querying /stats/summary [It] should report resource usage through the stats api
  test/e2e_node/summary_test.go:332
  [FAIL] [sig-node] Pods [It] should delete a collection of pods [Conformance]
  test/e2e/common/node/pods.go:877
  [FAIL] [sig-node] Security Context When creating a pod with HostUsers [It] must create the user namespace if set to false [LinuxOnly] [Feature:UserNamespacesStatelessPodsSupport]
  test/e2e/common/node/security_context.go:106
  [FAIL] [sig-node] Pods [It] should run through the lifecycle of Pods and PodStatus [Conformance]
  test/e2e/common/node/pods.go:959
  [FAIL] [sig-node] Pods [It] should patch a pod status [Conformance]
  test/e2e/common/node/pods.go:1108

Ran 261 of 390 Specs in 887.151 seconds
FAIL! -- 256 Passed | 5 Failed | 0 Pending | 129 Skipped


Ginkgo ran 1 suite in 14m48.016348681s

Test Suite Failed
You're using deprecated Ginkgo functionality:
=============================================
  --untilItFails is deprecated, use --until-it-fails instead
  Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-command-line-flags

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=2.7.0


Failure Finished Test Suite on Host test-ubuntu-2204-jammy-v20230214
command [ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR -i /home/maha4472/.ssh/google_compute_engine maha4472@35.204.131.40 -- sudo sh -c 'cd /tmp/node-e2e-20230227T222612 && timeout -k 30s 2700.000000s ./ginkgo -timeout=24h -nodes=8  -skip="\[Flaky\]|\[Slow\]|\[Serial\]"  -untilItFails=false  ./e2e_node.test -- --system-spec-name= --system-spec-file= --extra-envs= --runtime-config= --v 4 --node-name=test-ubuntu-2204-jammy-v20230214 --report-dir=/tmp/node-e2e-20230227T222612/results --report-prefix=ubuntu --image-description="ubuntu-2204-jammy-v20230214" --kubelet-flags=--kernel-memcg-notification=true --kubelet-flags=--feature-gates=DisableKubeletCloudCredentialProviders=true,KubeletCredentialProviders=true --kubelet-flags=--image-credential-provider-config=/tmp/node-e2e-20230227T222612/credential-provider.yaml --kubelet-flags=--image-credential-provider-bin-dir=/tmp/node-e2e-20230227T222612 --kubelet-flags="--cluster-domain=cluster.local" --dns-domain="cluster.local" --container-runtime-endpoint=unix:///run/containerd/containerd.sock '] failed with error: exit status 1
```

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Kubernetes version

n/a

### Cloud provider

n/a

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
