### ISSUE TITLE
Ability to create pods allows access to secrets in the same namespace

### ISSUE THREAD

**Issue by fox-md** [kubernetes/kubernetes#116188]
### What happened?

I created a cluster role
```
kubectl describe clusterrole pods-full-access
Name:         pods-full-access
Labels:       <none>
Annotations:  <none>
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
  pods/exec  []                 []              [*]
  pods       []                 []              [*]
```
Assigned this cluster role to a user.
```
alex@kmaster:~$ kubectl auth can-i list secrets
no
alex@kmaster:~$ kubectl auth can-i get secrets
no
alex@kmaster:~$ kubectl auth can-i watch secrets
no
```
Then I created below pod under this user, knowing about existence of "web" secret
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alex
  name: alex
spec:
  containers:
  - image: nginx
    name: alex
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: web
```
Once pod started, I was able to read secrets mounted inside of the pod.
```
alex@kmaster:~$ kubectl exec -it alex -- ls /etc/foo
url  user
alex@kmaster:~$ kubectl exec -it alex -- cat /etc/foo/url
http://localhost
alex@kmaster:~$ kubectl exec -it alex -- cat /etc/foo/user
webuser
```
So I`ve been thinking, can this be considered as a bug. Technically user has no rights to read data from secrets. However it is possible, once you know secret name and you can mount it into a pod.

### What did you expect to happen?

---

### How can we reproduce it (as minimally and precisely as possible)?

1. Create role with pods permissions only
2. Create a new user
3. Assign role to this user
4. Run a pod with existing secret
5. Check that you can see data mounted inside of the pod

### Kubernetes version

Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

bare-metal

### OS version

Linux kmaster 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
