### ISSUE TITLE
Service publishNotReadyAddresses and EndpointSlices Conditions

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#116285]
The EndpointSlice API says

https://github.com/kubernetes/kubernetes/blob/fafa45d13c21dcf99801631413fc58e9cf91226c/pkg/apis/discovery/types.go#L111-L116

and it works as expected in normal circumstances

```
apiVersion: v1
kind: Pod
metadata:
  name: terminating
  labels:
    app: MyApp
spec:
  terminationGracePeriodSeconds: 300
  containers:
  - name: agnhost
    image: k8s.gcr.io/e2e-test-images/agnhost:2.39
    args:
      - netexec
      - --http-port=80
      - --delay-shutdown=300
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: terminating-service
spec:
  type: ClusterIP
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

I delete the pod and the endpoints conditions are the expected
```
    ready: true
    serving: true
    terminating: true
```

However, if during this time I set `service.spec.publishNotReadyAddresses: true` 

```
    ready: true
    serving: true
    terminating: true
```

we run into an incoherence with the API doc, but it seems that we already documented this edge case in the code

https://github.com/kubernetes/kubernetes/blob/fafa45d13c21dcf99801631413fc58e9cf91226c/pkg/controller/endpointslice/utils.go#L44-L60

I think that at this point is just to amend this information to the API, no? 

```diff
diff --git a/pkg/apis/discovery/types.go b/pkg/apis/discovery/types.go
index efc2d331ec9..1a19ad5ecaa 100644
--- a/pkg/apis/discovery/types.go
+++ b/pkg/apis/discovery/types.go
@@ -112,7 +112,8 @@ type EndpointConditions struct {
        // according to whatever system is managing the endpoint. A nil value
        // indicates an unknown state. In most cases consumers should interpret this
        // unknown state as ready. For compatibility reasons, ready should never be
-       // "true" for terminating endpoints.
+       // "true" for terminating endpoints, except when the Service associated has
+       // enabled the field PublishNotReadyAddresses.
        Ready *bool
 
```

/kind bug
/kind documentation
