### ISSUE TITLE
K8s volume/pv cannot be mounted in pod

### ISSUE THREAD

**Issue by luoxue03** [kubernetes/kubernetes#116278]
### What happened?

The k8s volume/pv cannot be mounted into the pod. I used the created static pv to mount to nginxpod, and mounted different pvs respectively. But only confPV is successfully mounted to the pod. I tried to mount only html, and found that it cannot be mounted using hostpath. Tried different permissions ROX RWX etc but could not succeed. They agree that in the namespace, the node node exists in the directory

### What did you expect to happen?

I want to use three PVs to mount all three different directories in nginxpod, but only confPV is successful. The remaining PVs are displayed as being successfully mounted but do not display paths in Mounts.

![6b11450aa0b8b85e26a9bb8f4bf16bf](https://user-images.githubusercontent.com/55294713/222965854-05a2eae8-428d-42e2-a036-713a50b05300.png)
![6de50181080fd02981e1a7183a822ad](https://user-images.githubusercontent.com/55294713/222965856-b1eeb7e0-c1ee-4672-b266-2f3b1d0926e6.png)
![8634c63e064a6f586587adbba4a80d1](https://user-images.githubusercontent.com/55294713/222965858-8958f9d3-8f2a-4866-bd0d-402bd0130f
![48506a9a86e6fa0753262a75719dd48](https://user-images.githubusercontent.com/55294713/222965881-eb8d1f5c-ed3c-44ee-8d4f-995e810aee41.png)

![584145ce51be15c0207dc6112895ef6](https://user-images.githubusercontent.com/55294713/222965877-e1db0aba-ed8d-4383-b751-c812da68
![c9a6a98b
![3fbdd6a9fd
![bc1fd86ffbb8ce1cfbb832ea4efccb5](https://user-images.githubusercontent.com/55294713/222965909-48f4c582-8d7e-4e20-9fa4-09f04e641673.png)
b8c37d08
![a1ab98b8b87f7fce1e30638e9bba037](https://user-images.githubusercontent.com/55294713/222965903-9f099ee5-2330-4838-8b31-dea7bca8784c.png)
7146cd10dabc7](https://user-images.githubusercontent.com/55294713/222965900-a6ae7a95-56a6-4bd1-984a-7b830635b85b.png)
3412afcddcb5c47d807053b](https://user-images.githubusercontent.com/55294713/222965888-8eb6312c-208d-4161-96d3-ca97d
![6d10b40eec5126b94823403f211c477](https://user-images.githubusercontent.com/55294713/222965898-771c9056-d4a8-433c-a053-57f6f6d8002c.png)

![bb200576b4954f16d1a3d57e431d56b](https://user-images.githubusercontent.com/55294713/222965896-a9a7b4ed-c5c3-4382-bc0d-6aa761eddd65.png)
78
![d52c593cea38846595eccf77fa15410](https://user-images.githubusercontent.com/55294713/222965893-ede97254-d743-43de-9af0-3a59a6569577.png)

![866d62ab7a11e28086e2a33031dbdef](https://user-images.githubusercontent.com/55294713/222965892-c9ee71a9-4640-49d9-87e7-8d7ba32674f3.png)
c35df.png)
52da.png)
![e09fd5da176e12fdb9e698ee2cd1a03](https://user-images.githubusercontent.com/55294713/222965891-12016180-ef40-46c3-9b57-b8ed0ab94ae5.png)

0d.png)
![e0e047f
![5935b744d12a36c3df349c9b169aa82](https://user-images.githubusercontent.com/55294713/222965874-573711de-e69b-49cd-986d-7b8ab50fce3f.png)

![891dc0d9660ee2cf7e24c9fb0671548](https://user-images.githubusercontent.com/55294713/222965870-5af5fcae-71cb-44c4-beeb-ecdff5c00179.png)

![5d5fb2721ec62dcec1eb941f32de99b](https://user-images.githubusercontent.com/55294713/222965866-2d318f44-4e41-4a45-b13c-e13e8413e8ab.png)
09a998e67b92084bc6092f18](https://user-images.githubusercontent.com/55294713/222965863-8a38c954-80d4-40bd-b9e4-041a9adee94b.png)

### How can we reproduce it (as minimally and precisely as possible)?

i dot know

### Anything else we need to know?

Sorry, I thought the picture had already been loaded. This code was modified by me after constant testing. Changed from Deployment to Statefulset, and annotated the PVC in Volumes, and changed it to HostPath but it does not take effect
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-log
  namespace: default
  labels:
    pv-name: nginx-log
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: "/a"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-conf
  namespace: default
  labels:
    pv-name: nginx-conf
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: "/mnt/nginx/nginx/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-html
  namespace: default
  labels:
    pv-name: nginx-html
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: "/b"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-log
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: nginx-log
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-conf
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: nginx-conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-html
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: nginx-html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: nginx
    port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: nginx-sc
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-log
          mountPath: /mnt
          # - name: nginx-html
          # mountPath: /mnt
          # - name: nginx-conf
          #  mountPath: /mnt
      volumes:
              #  - name: nginx-log
              #    persistentVolumeClaim:
              #      claimName: nginx-pvc-log
              #  - name: nginx-conf
              #    persistentVolumeClaim:
              #      claimName: nginx-pvc-conf
      - name: nginx-log
        hostPath:
          path: /c
        #persistentVolumeClaim:
        # claimName: nginx-pvc-html

```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>
no
</details>
no

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>
containerd
ctr containerd.io 1.6.4

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jsafrane** [comment]
From https://user-images.githubusercontent.com/55294713/222965881-eb8d1f5c-ed3c-44ee-8d4f-995e810aee41.png, it looks like invalid yaml.

There should be a dash `-` before each `name:` to mark separate array items:

```
        volumeMounts:
        - name: nginx-log
          mountPath: /mnt
        - name: nginx-html
          mountPath: /mnt
        - name: nginx-conf
          mountPath: /mnt

```
