### ISSUE TITLE
HPA looks at CronJob containers for metrics

### ISSUE THREAD

**Issue by williejay2017** [kubernetes/kubernetes#116339]
### What happened?

First post here, hello :) 👋 .

I enabled HPA on one of our API's. When I checked lens to insure it was running properly I came across this error.

`failed to get cpu utilization: missing request for cpu`

After doing some digging I realized that I needed to specify resources on _all_ containers that run with my deployment. After doing this I still encountered this error. After spending the entire day digging around and making changes to our charts etc, I eventually got it to work. Our chart runs a cron job container that updates our DB (runs liquid base changes) before the deployment object is created. Once that job is completed it still hangs around. For some strange reason HPA was looking at that cron job for resources and once I deleted the completed job HPA started working correctly.

### What did you expect to happen?

I expected HPA to target the deployment object as specified in the scaleTargetRef of the resource object.

### HPA resource yml

```
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "spring-api.fullAppName" . }}
  labels:
    {{- include "spring-api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "spring-api.fullAppName" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
```

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a chart with Deployment Object (with or without sidecars) / HPA and a cronjob that runs before deployment. 

### Anything else we need to know?

Just looking for clarity as why HPA would look at CronJob objects when its specified to look at Deployment objects for metric based scaling? Thanks!

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"d0b89678ea884ca501cba708c56d2ea41debbf2c", GitTreeState:"clean", BuildDate:"2022-01-31T09:05:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AKS
</details>

### OS version

<details>

```console
N/A - cloud deployed
```

</details>

### Install tools

<details>
Helm
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
Can you provide a YAML manifest for a Pod belonging to the Deployment and another for a Pod belonging to the CronJob? Maybe there is an issue with the selectors that these are using.

**Comment by williejay2017** [comment]
> Can you provide a YAML manifest for a Pod belonging to the Deployment and another for a Pod belonging to the CronJob? Maybe there is an issue with the selectors that these are using.


Database cronjob yml thats causing the conflict - minus ref config map (no relevance here)
```
{{- $dbChangeLogDir := "/dbscripts" -}}
{{- $dbMount := "db-upgrade-scripts" -}}
{{- $dbServerName := (split "." (required "Missing database.host" .Values.database.host)) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "spring-api.fullAppName" . }}-db-update
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spring-api.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
spec:
  template:
    metadata:
      name: {{ include "spring-api.fullAppName" . }}-db-update
      labels:
        {{- include "spring-api.selectorLabels" . | nindent 8 }}
        {{- if .Values.podIdentity.enabled }}
        aadpodidbinding: {{ required "podIdentity.bindingName is required" .Values.podIdentity.bindingName }}
        {{- end }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: db-update
          image: {{ printf "%s/%s:%s" .Values.image.repository .Values.database.upgrade.image.name .Values.database.upgrade.image.tag }}
          imagePullPolicy: {{ .Values.database.upgrade.image.pullPolicy }}
          volumeMounts:
            - name: {{ $dbMount }}
              mountPath: {{ $dbChangeLogDir }}
          env:
            - name: DB_ADDR
              value: {{ required "database.host is required" .Values.database.host }}
            - name: DB_PORT
              value: {{ required "database.port is required" .Values.database.port | quote }}
            - name: DB_DATABASE
              value: {{ required "database.name is required" .Values.database.name }}
            - name: DB_USER
              value: {{ printf "%s@%s" .Values.podIdentity.name $dbServerName._0 }}
            - name: DB_MIGRATIONS_CHANGELOG_DIR
              value: {{ $dbChangeLogDir }}
            - name: DB_MIGRATIONS_CHANGELOG_FILE
              value: {{ required " database.upgrade.changeLogFile is required" .Values.database.upgrade.changeLogFile }}
            - name: DB_DRIVER
              value: {{ required "database.driver is required" .Values.database.dbDriver }}
            - name: USE_AZ
              value: "true"
            - name: DB_TAG
              value: {{ printf "%s:%s" (include "spring-api.fullAppName" .) (.Values.application.pr | default .Values.application.version) }}
            - name: DB_ROLLBACK
              value: {{ .Values.database.upgrade.rollback | quote }}
            - name: ENV_CONTEXT
              value: {{ required "application.deployEnv is required" .Values.application.deployEnv }}
      restartPolicy: Never
      volumes:
        - name: {{ $dbMount }}
          configMap:
            name: {{ include "spring-api.fullAppName" . }}-database-upgrade
{{- end }}
```

Deployment yml in same chart

```

{{- $appTls := .Values.ingress.base.tls.enabled -}}
{{- $fullName := include "spring-api.fullAppName" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-api.fullAppName" . }}
  labels:
    {{- include "spring-api.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 2
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spring-api.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      annotations:
        {{- (include "spring-api.prometheus.annotations" . ) | nindent 8 }}
        {{- (include "spring-api.deployment.istioAnnotations" . ) | nindent 8 }}
      labels:
        {{- include "spring-api.selectorLabels" . | nindent 8 }}
        {{- if .Values.podIdentity.enabled }}
        aadpodidbinding: {{ required "podIdentity.bindingName is required" .Values.podIdentity.bindingName }}
        {{- end }}
    spec:
      dnsPolicy: ClusterFirst # default but including for clarity
      restartPolicy: Always # default but including for clarity
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      nodeSelector:
       {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
      {{ toYaml .Values.tolerations | nindent 8 }}
      initContainers:
        {{- include "spring-api.extraInitContainers" . | indent 8 }}
        {{- if .Values.podTls.enabled }}
        - name: pem-to-keystore
          image: {{ printf "%s/alpine:tls" .Values.image.repository }}
          imagePullPolicy: Always
          env:
            {{- if not .Values.podTls.certsPassedThroughSecrets.enabled }}
            {{ $tlsCertFile := printf "%s/certs/%s" (include "spring-api.tls.path" . ) (include "spring-api.tls.cert" .)  -}}
            - name: TLS_CERT_FILE
              value: {{ $tlsCertFile }}
            {{- end }}
            - name: ALIAS
              value: {{ include "spring-api.tls.cert" . }}
            - name: KEYSTORE_FILE
              value: {{ include "spring-api.tls.keystore" . }}
              {{- if .Values.podTls.certsPassedThroughSecrets.enabled }}
            - name: CERTS_BASE_PATH
              value: {{ required ".podTls.certsPassedThroughSecrets.certsBasePath" .Values.podTls.certsPassedThroughSecrets.certsBasePath }}
            - name: CERTS_OP_PATH
              value: {{ required ".podTls.certsPassedThroughSecrets.certsOutputPath" .Values.podTls.certsPassedThroughSecrets.certsOutputPath }}
              {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "spring-api.fullAppName" . }}-tls-secret
          command: ['/bin/bash']
          resources:
          {{- toYaml .Values.podTls.resources | nindent 12 }}
          {{- if .Values.podTls.certsPassedThroughSecrets.enabled }}
          args: [ '-c',  '{{ include "spring-api.configurationPath" . }}/scripts/convert-multiple-certs.sh' ]
          {{- else }}
          args: [ '-c',  '{{ include "spring-api.configurationPath" . }}/scripts/convert-certs.sh' ]
          {{- end }}
          securityContext:
            {{- toYaml .Values.podTls.securityContext | nindent 12 }}
          volumeMounts:
            {{- if not .Values.podTls.certsPassedThroughSecrets.enabled }}
            - name: tls-certs
              mountPath: {{ include "spring-api.tls.path" . }}/certs
            {{- end }}
            - name: tls-keystores
              mountPath: {{ include "spring-api.tls.path" . }}/keystores
            - name: scripts
              mountPath: {{ include "spring-api.configurationPath" . }}/scripts
          {{- if .Values.podTls.extraVolumeMounts }}
          {{ toYaml .Values.podTls.extraVolumeMounts | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.database.useIdentity }}
        - name: pod-token-generation
          image: mcr.microsoft.com/azure-cli
          imagePullPolicy: IfNotPresent
          env:
            - name: AZURE_DB_CONFIG_PATH
              value: {{ include "spring-api.database.configurationPath" . }}
          command:  ['bash']
          args: ['-c', '{{ include "spring-api.configurationPath" . }}/scripts/generate-token.sh']
          volumeMounts:
            - name: generated-token
              mountPath: {{ include "spring-api.database.configurationPath" . }}
            - name: scripts
              mountPath: {{ include "spring-api.configurationPath" . }}/scripts
        {{- end }}
      containers:
        {{- include "spring-api.additionalContainers" . | indent 8 }}
        - name: {{ $fullName }}
          image: "{{ .Values.image.repository | trimSuffix "/" }}/{{ required "image.name is required" .Values.image.name }}:{{- .Values.image.tag | default .Values.application.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: "tcp-{{ include "deployment.port" . }}"
              containerPort: {{ include "deployment.port" . }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.pod.securityContext | nindent 12 }}
          env:
            - name: CLUSTER
              value: {{ include "spring-api.cluster" . }}
            - name: APP_NAME
              value: {{ .Values.application.name }}
            - name: DEPLOY_ENV
              value: {{ include "spring-api.env" . }}
            - name: LOG_LEVEL
              value: {{ .Values.application.logLevel }}
            {{- if not .Values.config.serverCreation }}
            - name: CONFIG_HOST
              value: {{ include "spring-api.config.host" . }}
            - name: CONFIG_PROJECT_NAME
              value: {{ .Values.application.name }}
            - name: CONFIG_HOST_PROTOCOL
              value: "https"
            - name: CONFIG_BRANCH
              value: {{ .Values.config.label }}
            - name: CONFIG_PROFILE
              value:  {{ default .Values.application.deployEnv .Values.config.profiles }}
            {{- end }}
            {{- if .Values.aws.enabled }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access
                  key: AWS_ACCESS_KEY
            {{- end }}
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end}}
            - name: JAVA_OPTS
              value: {{ include "spring-api.javaOpts" . | quote }}
            {{- if .Values.podTls.enabled }}
            - name: SERVER_SSL_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "spring-api.fullAppName" . }}-tls-secret
                  key: KEYSTORE_PASSWORD
            {{- end }}
            {{- if and (not .Values.database.useIdentity) .Values.database.enabled }}
            {{- if .Values.database.hikariConnection }}
            - name: SPRING_DATASOURCE_HIKARI_PASSWORD
            {{- else }}
            - name: SPRING_DATASOURCE_PASSWORD
            {{- end }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "spring-api.fullAppName" . }}-db-password
                  key: password
            {{- end }}
            {{- if .Values.signalfx.enabled }}
            {{- include "spring-api.signalfx.envs" . | nindent 12 }}
            {{- end }}
            {{- if .Values.otel.enabled }}
            {{- include "spring-api.otel.envs" . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- range .Values.pvc }}
            - name: {{ $fullName }}-{{ .name }}-pvc
              mountPath: {{ .mountPath }}
            {{- end }}
            {{- if .Values.secretProviderClass.enabled }}
            {{- if and (not .Values.podTls.certsPassedThroughSecrets.enabled) (or (or .Values.podTls.enabled $appTls) (and (not .Values.database.useIdentity) .Values.database.enabled)) }}
            - name: tls-certs
              mountPath: {{ include "spring-api.tls.path" . }}/certs
            {{- end }}
            {{- end }}
            {{- if .Values.database.useIdentity }}
            - name: generated-token
              mountPath: {{ include "spring-api.database.configurationPath" . }}
            {{- end }}
            {{- if .Values.podTls.enabled }}
            - name: tls-keystores
              mountPath: {{ include "spring-api.tls.path" . }}/keystores
            {{- end }}
            {{- if .Values.volumes }}
            {{- toYaml .Values.volumes | nindent 12 }}
            {{- end }}
            {{- if .Values.deployment.extraVolumeMounts }}
            {{- toYaml .Values.deployment.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
            {{- include "spring-api.istio.customProbe" (merge (dict "definedProbe" .Values.probes.liveness.httpGet) . ) | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
            {{- include "spring-api.istio.customProbe" (merge (dict "definedProbe" .Values.probes.readiness.httpGet) . ) | nindent 12 }}
        {{- end }}
      volumes:
        {{- if (or .Values.podTls.enabled .Values.database.useIdentity) }}
        - name: scripts
          configMap:
            name: {{ include "spring-api.fullAppName" . }}-scripts
            defaultMode: 0555
        {{- end }}
        {{- if .Values.podTls.enabled }}
        - name: tls-keystores
          emptyDir:
            sizeLimit: 100Mi
        {{- end }}
        {{- if .Values.database.useIdentity }}
        - name: generated-token
          emptyDir: {}
        {{- end }}
        {{- if .Values.secretProviderClass.enabled }}
        {{- if and (not .Values.podTls.certsPassedThroughSecrets.enabled) (or (or .Values.podTls.enabled $appTls) (and (not .Values.database.useIdentity) .Values.database.enabled)) }}
        - name: tls-certs
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "spring-api.fullAppName" . }}
        {{- end }}
        {{- end }}
        {{- if .Values.deployment.extraVolumes }}
        {{- toYaml .Values.deployment.extraVolumes | nindent 8 }}
        {{- end }}
        {{- range .Values.pvc }}
        - name: {{ $fullName }}-{{ .name }}-pvc
          persistentVolumeClaim:
            claimName:  {{ $fullName }}-{{ .name }}-pvc
      {{- end }}

{{- if .Values.aws.enabled }}
---
{{- include "spring-api-secret-generation"  (merge (dict "secretName" "aws-secret" "secretKey" "AWS_SECRET_KEY" "secret" .Values.aws.secretKey ) . )}}
---
{{- include "spring-api-secret-generation"  (merge (dict "secretName" "aws-access" "secretKey" "AWS_ACCESS_KEY" "secret" .Values.aws.accessKey ) . )}}
{{- end}}
```
