### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Add new CI job that runs in-place pod resize e2e tests in parallel

### ISSUE THREAD

**Issue by vinaykul** [kubernetes/kubernetes#116431]
### What would you like to be added?

Add a new CI job (atleast for cgroup v2) and fix up in-place pod resize tests to run in parallel while ensuring that we don't see any flaky behavior in a limited resource CI VM environment (typically 2000m cpu)

This can be done by changing --ginkgo-parallel = M and --minStartupPods = <numVM> with gcp-nodes = 2 (or more)

```yaml
- name: ci-cos-cgroupv2-inplace-pod-resize-containerd-main-e2e-gce-serial
  interval: 24h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-e2e-containerd: "true"
  spec:
    containers:
    - args:
      - --repo=github.com/containerd/containerd=main
      - --timeout=180
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=KUBE_FEATURE_GATES=InPlacePodVerticalScaling=true
      - --env=ENABLE_POD_SECURITY_POLICY=true
      - --env=KUBE_MASTER_EXTRA_METADATA=user-data=/workspace/github.com/containerd/containerd/test/e2e/master.yaml,containerd-configure-sh=/workspace/github.com/containerd/containerd/cluster/gce/configure.sh,containerd-extra-init-sh=/workspace/github.com/containerd/containerd/test/e2e_node/gci-init.sh,containerd-env=/workspace/test-infra/jobs/e2e_node/containerd/containerd-main/cgroupv2/env-cgroupv2
      - --env=KUBE_NODE_EXTRA_METADATA=user-data=/workspace/github.com/containerd/containerd/test/e2e/node.yaml,containerd-configure-sh=/workspace/github.com/containerd/containerd/cluster/gce/configure.sh,containerd-extra-init-sh=/workspace/github.com/containerd/containerd/test/e2e_node/gci-init.sh,containerd-env=/workspace/test-infra/jobs/e2e_node/containerd/containerd-main/cgroupv2/env-cgroupv2
      - --env=KUBELET_TEST_ARGS=--runtime-cgroups=/system.slice/containerd.service --cgroup-driver=systemd
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-nodes=1
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel=1
      - --image-family=cos-stable
      - --image-project=cos-cloud
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:InPlacePodVerticalScaling\] --minStartupPods=1
      - --timeout=150m
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230222-b5208facd4-master
  annotations:
    testgrid-dashboards: sig-node-containerd
    testgrid-tab-name: cos-cgroupv2-inplace-pod-resize-containerd-e2e-serial
    description: Runs cluster e2e pod resize tests in serial with FOCUS=[Feature:InPlacePodVerticalScaling] with cgroup v2
```

### Why is this needed?

Running E2E tests in parallel provides more realistic in-place resize usage environment that is encountered in production use.
