### ISSUE TITLE
Service account not showing the secret count attached to it

### ISSUE THREAD

**Issue by harsh4870** [kubernetes/kubernetes#116451]
### What happened?

**SA** not showing the **secret** **count** attached to it, when we list the `kubectl get sa`

**Step to reproduce** 

`kubectl create sa test-sa`

Create a secret attach to SA

```
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: token-secret
  annotations:
    kubernetes.io/service-account.name: "test-sa"
```
<img width="596" alt="Screenshot 2023-03-10 at 10 47 18 AM" src="https://user-images.githubusercontent.com/15871000/224229927-3a79b020-1bd0-4ef0-8eb5-875c567b0086.png">

### What did you expect to happen?

i think SA should be showing the attached secret count. Is this expected behavior? 

i am aware there are changes from **SA** & **secret** creation from **1.24** version in K8s but ideally it should be showing the count **SA** having a count of secret. 

Correct me if missing anything. 

### Kubernetes version

<details>

```console
$ kubectl version
# 1.25
```

**Comment by LuBingtan** [comment]
Also curious about this issue, was it done on purpose or is it a bug?

**Comment by harsh4870** [comment]
Same curious to know is this know and done for purpose or bug, if bug would love to work on it.

**Comment by xyz-li** [comment]
I think this work as design, not a bug.
https://github.com/kubernetes/kubernetes/blob/c09d01192aa51f9db0457ddb1ae1972326e37e8d/staging/src/k8s.io/api/core/v1/types.go#L4957-L4965

**Comment by harsh4870** [comment]
If we do something like this, it's showing the count as struct having the field **Secrets**

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
secrets:
  - name: token-secret
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: token-secret
  annotations:
    kubernetes.io/service-account.name: "test-sa"
```
