### ISSUE TITLE
Enable allowedUnsafeSysctls on v1.26 but can't use net.core.wmem_max in pod

### ISSUE THREAD

**Issue by hungzinza** [kubernetes/kubernetes#116460]
### What happened?

My cluster is v1.26. I enabled option allowedUnsafeSysctls in kubelet config
my pod use `net.core.somaxconn` is success, but failed with `net.core.wmem_max` 

This is config in kubelet
```
...
kind: KubeletConfiguration
...
allowedUnsafeSysctls:
- net.core.wmem_max
- net.core.somaxconn
...
```
This is pod
```
apiVersion: v1
kind: Pod
metadata:
  name: sysctl-example
spec:
  containers:
  - name: busybox
    image: ubuntu
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: Always
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: k8s1-stg
  nodeName: k8s1-stg
  securityContext:
    sysctls:
      - name: net.core.somaxconn
        value: "1024"
      - name: net.core.wmem_max
        value: "212994"
```

### What did you expect to happen?

I expect my pod can running

### How can we reproduce it (as minimally and precisely as possible)?

Step 1: Enable `allowedUnsafeSysctls` on kubelet config and restart kubelet service
Step 2: Running a pod as my above example

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by VuKhuongDuy** [comment]
/sig/sysctl

**Comment by SergeyKanzhelev** [comment]
@HirazawaUi can you please clarify how this Pod has failed. Is it failed to be scheduled, admitted by kubelet, or failed during execution?

/triage needs-information

**Comment by hungzinza** [comment]
@SergeyKanzhelev 
This is error 
![Screenshot from 2023-03-23 13-31-30](https://user-images.githubusercontent.com/96384818/227122190-af2058c5-573c-46f3-a7c1-70deb22a30de.png)

This is my code 
```
apiVersion: v1
kind: Pod
metadata:
  name: sysctl-example
  namespace: test-sysctl
spec:
  # hostNetwork: true
  containers:
  - name: busybox
    image: ubuntu
    # command: [ "/bin/bash", "-c", "echo 65530 > /tmp/vm/max_map_count; sysctl vm.max_map_count" ]
    imagePullPolicy: Always
    # volumeMounts:
    # - mountPath: /tmp/
    #   name: test-core
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: k8s1-stg
  nodeName: k8s1-stg
  securityContext:
    sysctls:
      - name: net.core.somaxconn
        value: "1024"
      - name: net.core.wmem_max
        value: "212994"
```

And I use this config inside file /etc/kubernetes/kubelet-config.yml

```
allowedUnsafeSysctls:
- net.core*
```
