### ISSUE TITLE
Add Custom fields to Service Account Token

### ISSUE THREAD

**Issue by dcarrion87** [kubernetes/kubernetes#116638]
### What happened?

Ability to add custom fields into service account token. Adding here as I believe they've not been looked at:

https://discuss.kubernetes.io/t/add-custom-claims-into-bound-service-account-jwt-token/21733
https://discuss.kubernetes.io/t/adding-custom-fields-into-a-service-account-token/23322/2

I believe this might be a feature request.

### What did you expect to happen?

Ability to add custom fields at this point:

```
  volumes:
  - name: test
    projected:
      sources:
      - serviceAccountToken:
          path: test
          audience: test
          additional: ???
```

Example use case passing session tags as per [AWS docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#:~:text=%3C/Attribute%3E-,Passing%20session%20tags%20using%20AssumeRoleWithWebIdentity,-Use%20OpenID%20Connect)

```
    "https://aws.amazon.com/tags": {
        "principal_tags": {
            "Project": ["Automation"],
            "CostCenter": ["987654"],
            "Department": ["Engineering"]
        },
        "transitive_tag_keys": [
            "Project",
            "CostCenter"
        ]
    }
```
