### ISSUE TITLE
readinessProbe for initContainer can not be set . but kubectl explain says its possible

### ISSUE THREAD

**Issue by ArjunDandagi** [kubernetes/kubernetes#116760]
### What happened?

while the docs does tell about not setting these values 
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#differences-from-regular-containers
`kubectl explain pod.spec.initContainers` shows all the fields you can set in `initContainers` section of the pod. 

so i tried it anyways:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: awscli
  name: awscli
spec:
  restartPolicy: OnFailure
  serviceAccountName: mlflow-test
  initContainers:
  - name: awscli-init
    image: amazon/aws-cli
    args:
    - sts
    - get-caller-identity
    readinessProbe:
      exec:
        command:
        - aws
        - sts
        - get-caller-identity
  containers:
  - name: awscli
    image: amazon/aws-cli
    args:
    - s3 
    - ls
    readinessProbe:
      exec:
        command:
        - aws
        - sts
        - get-caller-identity

```
1. dry-run=server didn't throw any error 
2. while creating i got the error 
```
Error: INSTALLATION FAILED: Pod "awscli" is invalid: [spec.initContainers[0].readinessProbe: Invalid value: core.Probe{Handler:core.Handler{Exec:(*core.ExecAction)(0xc055dd2c00), HTTPGet:(*core.HTTPGetAction)(nil), TCPSocket:(*core.TCPSocketAction)(nil)}, InitialDelaySeconds:0, TimeoutSeconds:1, PeriodSeconds:10, SuccessThreshold:1, FailureThreshold:3, TerminationGracePeriodSeconds:(*int64)(nil)}: must not be set for init containers]
```

### What did you expect to happen?

kubectl explain pod.spec.initContainers MUST not show invalidFields

### How can we reproduce it (as minimally and precisely as possible)?

run the command 
`kubectl explain pod.spec.initContainers` and see that it shows `livenessProbe` , `readinessProbe` , `startupProbe` or `lifecycle` 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:11Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-eks-ffeb93d", GitCommit:"52e500d139bdef42fbc4540c357f0565c7867a81", GitTreeState:"clean", BuildDate:"2022-11-29T18:41:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.22) exceeds the supported minor version skew of +/-1

--- 
ITS unrelated to unmatching binary i believe

```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

$ uname -a
Darwin myhost 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yuzhiquan** [comment]
I think missed this meesage:
`Also, init containers do not support lifecycle, livenessProbe, readinessProbe, or startupProbe because they must run to completion before the Pod can be ready.`

**Comment by ArjunDandagi** [comment]
@yuzhiquan Yes that's what I have mentioned the issue while the docs on website does inform about this .. the --dry-run client should or server both should support this 

And also kubectl explain shouldn't show those fields for initContainer(s) as they are invalid

**Comment by yuzhiquan** [comment]
I see, if you have intersting, pr is welcomed.
/sig cli
/triage accepted

**Comment by varshaprasad96** [comment]
@yuzhiquan @ArjunDandagi I can work on this fix and submit a PR if that's fine.

**Comment by ArjunDandagi** [comment]
@varshaprasad96  , can i pair with you on this please. want to learn how its done

**Comment by varshaprasad96** [comment]
@ArjunDandagi Yes, sure!

**Comment by varshaprasad96** [comment]
While looking at this, @ArjunDandagi and I found that the `Pod` spec contains a field named `InitConatiners` (https://github.com/kubernetes/api/blob/699cbbc336e23257e05cd1e5c97343e64ec4ccb3/core/v1/types.go#L3143) which is of the type `[]Container`. The container in turn has liveness and redness probes defined. 

Is defining a new type without these fields the right approach for this? Or could we modify this through OpenAPISchema markers which we are missing to understand. Could anyone please provide more explanation on this? 

@yuzhiquan Could you please help in this?

**Comment by gjkim42** [comment]
> Is defining a new type without these fields the right approach for this? Or could we modify this through OpenAPISchema markers which we are missing to understand. Could anyone please provide more explanation on this?

https://github.com/kubernetes/kubernetes/issues/115362

There was a discussion about desharing InitContainer from Container and I think we decided not to do that for the client-go compatibility.

https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/753-sidecar-containers#proposal

FYI, in line with the sidecar containers KEP, we are trying to enable all types of probes in init containers in next release (not all init containers but sidecar containers)

**Comment by Affan-7** [comment]
When I tried this with --dry-run=server, It gave me the error `The Pod "awscli" is invalid: spec.initContainers[0].readinessProbe: Forbidden: may not be set for init containers`

**Comment by brianpursley** [comment]
I don't think this is a sig/cli issue.

`kubectl explain` is just using what is provided in the OpenAPI spec.  

This part seems relevant:
https://github.com/kubernetes/kubernetes/blob/8718b3336609b8962a7dac464d8a39a0c2ddb65c/api/openapi-spec/v3/api__v1_openapi.json#L5459-L5476

The `io.k8s.api.core.v1.Container` type is reused in various places, but as the comment says in the explain description, some of the fields must not be set.

So the validation passes according to the spec, but the creation will fail due to these other limitations that are enforced separately from the spec.

/remove-sig cli
/remove-triage accepted
/sig api

**Comment by gjkim42** [comment]
We cannot remove probe and lifecycle fields from the init container description as it should be available for the init container with container's restartPolicy of Always.

See https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/753-sidecar-containers/README.md for the detail.

**Comment by SergeyKanzhelev** [comment]
/remove-triage accepted

this issue seems that was accepted by sig cli, but not api-machinery.

**Comment by seans3** [comment]
/triage accepted
/assign @aaron-prindle   Thanks Aaron :)

Needs a restart policy for the init container

**Comment by aaron-prindle** [comment]
From the sidecar container documentation [here](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#pod-sidecar-containers) I believe it might be possible to use `readinessProbe` with `initContainer` if you also set `initContainers[x].restartPolicy`.  Example from the docs linked above:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: alpine:latest
          command: ['sh', '-c', 'while true; do echo "logging" >> /opt/logs.txt; sleep 1; done']
          volumeMounts:
            - name: data
              mountPath: /opt
      initContainers:
        - name: logshipper
          image: alpine:latest
          restartPolicy: Always
          command: ['sh', '-c', 'tail -F /opt/logs.txt']
          volumeMounts:
            - name: data
              mountPath: /opt
      volumes:
        - name: data
          emptyDir: {}
```

In your current repro example it seems that `initContainers[x].restartPolicy` is not set, only the top level `restartPolicy`
