### ISSUE TITLE
PodAntiAffinity prevents scheduling the only pod with the label in AntiAffinity

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/kubernetes#116827]
### What happened?

I created a deployment that looked as follows:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      labels:
        app: test
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - test
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - test
            topologyKey: kubernetes.io/hostname
      containers:
      - image: nginx
        name: nginx
```

It successfully created a pod in my one node kind cluster:

```
$ k get pod
NAME                    READY   STATUS    RESTARTS   AGE
test-84dc5648f7-hbprp   1/1     Running   0          22s
```

I then realized that I want `podAntiAffinity` just within an image version, so I added a new label for that, making the deployment look like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
    metadata:
      labels:
        app: test
        app-version: v0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app-version
                  operator: In
                  values:
                  - v0
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app-version
                operator: In
                values:
                - v0
            topologyKey: kubernetes.io/hostname
      containers:
      - image: nginx
        name: nginx
```

I applied it and found that the new pod can not be scheduled:

```
$ k get pod
NAME                    READY   STATUS    RESTARTS   AGE
test-6cf566dbb7-8jfxq   0/1     Pending   0          3s
test-84dc5648f7-hbprp   1/1     Running   0          117s
```

Looking at the event, it seems to be because of the affinity:

```
$ k describe pod test-6cf566dbb7-8jfxq|rg Warn
  Warning  FailedScheduling  46s   default-scheduler  0/1 nodes are available: 1 node(s) didn't satisfy existing pods anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```

This doesn't make sense to me, as the only pod in the cluster that has the label used by the `podAntiAffinity` is the one that is now in pending:

```
$ k get pod -l app-version -A
NAMESPACE   NAME                    READY   STATUS    RESTARTS   AGE
default     test-6cf566dbb7-8jfxq   0/1     Pending   0          89s
```

### What did you expect to happen?

The new pod that uses the new label for `podAntiAffinity` to be scheduled onto the existing node, as the existing pod doesn't have the relevant label.

### How can we reproduce it (as minimally and precisely as possible)?

See the `What happened` section

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.25.3

</details>

### Cloud provider

<details>
None/irrelevant, reproducible in kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kind and kubectl
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
