### ISSUE TITLE
A K8s POD using mmap(2) can cause oom-kills on the K8s node

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#116895]
### What happened?

With a manifest that sets a memory limit for the container it is possible to allocate any size of "rss-file" memory and still run (not get evicted).

This have caused kernel oom-kills on the node. Fortunately, the process itself got oom-killed, but the kernel can pick any process on the node with a high oom score.

### What did you expect to happen?

The over-use of memory should be detected by K8s and the POD should be evicted.

### How can we reproduce it (as minimally and precisely as possible)?

Compile the example in https://docs.kernel.org/networking/packet_mmap.html and start it in a container as "packet_mmap eth0". Deploy with something like;

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rssfile
spec:
  selector:
    matchLabels:
      app: rssfile
  replicas: 4
  template:
    metadata:
      labels:
        app: rssfile
    spec:
      containers:
      - name: rssfile
        image: registry.nordix.org/cloud-native/rssfile:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "50Mi"
        securityContext:
          privileged: true
#          capabilities:
#            add: ["NET_ADMIN", "NET_RAW"
```
Please note the memory limit. Check the _real_ memory usage with "grep Rss /proc/<pid>/status". It shows;
```
# grep Rss /proc/851/status 
RssAnon:               0 kB
RssFile:          263552 kB
RssShmem:              0 kB
```
The RssFile memory is real memory and exceeds the limit by 5x.

If replicas are increased the kernel-oom killer will eventually kick in.

### Anything else we need to know?

It seems "privileged: true" is required. At least I have not found any capabilities that allows mmap(2).

The ~256M rss-file memory is not visible with `kubectl top`:
```
# kubectl top pods
NAME                       CPU(cores)   MEMORY(bytes)   
rssfile-77cc7d6dc5-2pq4w   0m           0Mi             
rssfile-77cc7d6dc5-7n6fg   1m           1Mi             
rssfile-77cc7d6dc5-cq2xf   0m           1Mi             
rssfile-77cc7d6dc5-x7pqb   1m           1Mi             
```

### Kubernetes version

v1.26.3

### Cloud provider

None

### OS version

Linux 6.2.7

### Install tools

None

### Container runtime (CRI) and version (if applicable)

crio version 1.25.1
