### ISSUE TITLE
Overlapping Deployment matchLabels causes HPA to not scale correctly

### ISSUE THREAD

**Issue by BojanZelic-DD** [kubernetes/kubernetes#116898]
### What happened?

When I create 2 deployments with overlapping label selectors; HPA does not scale up to the expected pod count; 

I'm targeting 30% CPU usage, but when pods have > 30% CPU scale up does not happen

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
...
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  metrics:
  - resource:
       name: cpu  
       target:
         averageUtilization: 30 
         type: Utilization
status: 
  currentMetrics:
    - resource:
      current:
        averageUtilization: 50
        averageValue: 2191m
      name: cpu
    type: Resource
  currentReplicas: 3
  desiredReplicas: 3
```
Deployment A
```
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: my-app
      service: my-service
```
Deployment B with same labels but crashing pods
```
metadata:
  name: my-app-canary
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: my-app
      service: my-service
```

Pod status when querying by labels:
```
kubectl get pods --selector=app=my-app,service=my-service
NAME                                                           READY   STATUS                       RESTARTS   AGE
my-app-67c49df89-2l4s8             2/2     Running                      0          33m
my-app-67c49df89-4w7sl             2/2     Running                      0          33m
my-app-67c49df89-vdw4m             2/2     Running                      0          33m
my-app-canary-54c87ffbd8-tnht9     1/2     CreateContainerConfigError   0          5h4m
my-app-canary-54c87ffbd8-t66t9     1/2     CreateContainerConfigError   0          5h4m
```

### What did you expect to happen?

I expect HPA to target pods belonging to the replicaset of the deployment and not just the labels it's matching against, since it miscalculates the replica count to scale to;

Following the [HPA algorithm](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details): 
`desiredReplicas = ceil[currentReplicas * ( currentMetricValue / desiredMetricValue )]` 
I would expect the deployment to scale to 5 replicas:
`desiredReplicas = ceil(3 * (50/30)) == 5`

but instead it stays at 3 and even reports 3 currentReplicas & desiredReplicas in the status

### How can we reproduce it (as minimally and precisely as possible)?

* create 2 deployments with same matchLabels
* create an `autoscaling/v2/HorizontalPodAutoscaler` targeting the first deployment; 
* observe that scaling isn't targeting only the first deployment, but any pods that use the same labels;

### Kubernetes version

<details>

```console
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:21Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
