### ISSUE TITLE
cri support logScheme=file 

### ISSUE THREAD

**Issue by ningmingxiao** [kubernetes/kubernetes#116900]
### What would you like to be added?

cri default  log-uri is fifo, I create a pr for containerd which support file mode can save some memory
ref : https://github.com/containerd/containerd/pull/8239

### Why is this needed?

I want kubernetes can  support logScheme=file 

### Here is my test
50 pods, 100 containers
pod.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sx-heap
  labels:
    app: test
spec:
  replicas: 50
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      hostNetwork: true
      containers:
      - name: busybox-1
        image: docker.io/library/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-ec','top']
        livenessProbe:
          exec:
            command: ['/bin/sh', '-ec', 'echo 1 > /dev/null']
      - name: busybox-2
        image: docker.io/library/busybox:latest
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-ec', 'top']
        livenessProbe:
          exec:
            command: ['/bin/sh', '-ec', 'echo 1 > /dev/null']
```
 default 
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
[root@localhost home]# ps -auxf |grep containerd |grep -v shim
root     1525670  0.0  0.0 221916  1096 pts/0    S+   14:28   0:00  |           \_ grep --color=auto containerd
root     1427218 12.8  2.2 5762452 176812 ?      Sl   14:22   0:46  \_ containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd

```
use  log-uri=file by setting container_log_scheme="file"
```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
[root@localhost home]# ps -auxf |grep containerd|grep -v shim
root       74212  0.0  0.0 221916  1080 pts/0    S+   11:50   0:00  |           \_ grep --color=auto containerd
root        9890  2.1  1.5 2507028 119504 ?      Sl   11:22   0:37  \_ containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
```
will save about  32% memory of containerd
（176812-119504）/176812 = 32%  ,
cpu% from 12.8 to 2.1
