### ISSUE TITLE
Allow custom tolerance levels for horizontal pod autoscalers

### ISSUE THREAD

**Issue by GautamSinghania** [kubernetes/kubernetes#116984]
### What would you like to be added?

We have a configuration for HPA called `horizontal-pod-autoscaler-tolerance` in [Kube Controller Manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/), defaulted to `0.1`.

An individual HPA should be allowed to set a custom value for this, overriding the default value. Sample yaml:
```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-hpa
  namespace: holmes-seldon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-deployment
  minReplicas: 20
  maxReplicas: 450
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  behavior:
    scaleDown:
        tolerance: 0.05  # Custom tolerance value for scaledown
    scaleUp:
        tolerance: 0.02 # Custom tolerance value for scaleUp
```

### Why is this needed?

K8 Clusters in organizations are often used by multiple applications with different needs. Allowing individual HPA to set their own tolerance limits (and possibly other HPA related config) can help in handling different usecases smoothly.

**Comment by pbetkier** [comment]
An alternative we were thinking of is removing tolerance altogether. I'm curious is tolerance at all beneficial for you?

**Comment by GautamSinghania** [comment]
Removing tolerance might be useful to us (honestly, we will have to test that). But, I imagine having tolerance would be good as general.

**Comment by du2016** [comment]
i also need this Feature. Some services are very sensitive to delay. Using this Feature can reduce the number of scaling
，for example we need a feature to let cpu more than 60% to scale up,and low than 40%to scale down,40%-60% not scale down and up

**Comment by chenshiwei-io** [comment]
> i also need this Feature. Some services are very sensitive to delay. Using this Feature can reduce the number of scaling ，for example we need a feature to let cpu more than 60% to scale up,and low than 40%to scale down,40%-60% not scale down and up

+1

**Comment by GautamSinghania** [comment]
For anyone following this thread from before, I have updated the requirement to have separate custom tolerance levels for scale up and scale down. I believe this will be a minimal and impactful change.

**Comment by pbetkier** [comment]
@GautamSinghania could you explain the rationale behind having a different tolerance for scaling up and scaling down? Is your use case for differing tolerance levels solvable by tuning [behavior controls](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior)?

**Comment by GautamSinghania** [comment]
@pbetkier I feel that different tolerances are a general ask and should be doable. In my instance, it derives from the fact that pods take a long time to come up. Hence, I want to have a higher tolerance for scale down and lower tolerance for scale up. This helps me control the average values and scale up/down tolerances separately.

Tuning behavior controls will be a round-about way to do this, but can be done.

I feel that if the ask is too great or convoluted from the back-end, we could reduce it to a simple custom tolerance control. However, if different tolerances are doable, it would be a great offering.

**Comment by BojanZelic** [comment]
In our usecase we use external scalers and the granularity for control is not there without being able to set this tolerance value on a case-by-case basis;

simple example, a cron-based scaler:
`100` replicas between `1-2PM`
`108` replicas between `2-3PM`

The external metric returns either `100` or `108` depending on the time of day; But the scaleUp never happens because of the 10% tolerance default setting.

Here's an example:

currentReplicas = 100

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
...
  metrics:
  - external:
      metric:
        name: my-cron
        selector:
          matchLabels:
            cron-scale: true
      target:
        averageValue: "1"
        type: AverageValue
```

During first cron schedule, pods scale up to 100, ratio is 1/1 because 100 = 100
desiredReplicas = 100

```
status:
  currentMetrics:
  - external:
      current:
        averageValue: "1"
        value: "0"
      metric:
        name: my-cron
        selector:
          matchLabels:
            cron-scale: true
```


then during the second cron schedule:
desiredReplicas still = 100 because 1067m/1 = 1.067 and is less then the 10% tolerance, so scaleUp is never triggered
```
status:
  currentMetrics:
  - external:
      current:
        averageValue: "1067m"
        value: "0"
      metric:
        name: my-cron
        selector:
          matchLabels:
            cron-scale: true
```
