### ISSUE TITLE
Pv in local storage. I am getting error of file not exist.

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/kubernetes#116923]
### What happened?

I am trying persistent volume demo where i use local -storage and had made folder with store name in linux machine.
But the path is not getting mount. the pods remain always in Containercreating mode. I thaught it is searching for the folder in VM as well but there also its showing same error. PV and PVC get created successfully but when i use to create pod of it . It is not  getting in running or ready state.

I am attaching PVdemo.yaml file.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: `pv-demo-final`
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /store
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubenode01

```

Attaching pvcdemo.yaml file

`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo-final
spec:
  volumeName: pv-demo-final
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

`

Attaching Poddemo.yaml file

`apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc-demo-final
  labels:
    name: pod-with-pvc-demo-final
spec:
  containers:
  - name: pod-with-pvc-demo
    image:  niranjandarshan/bihartour:latest
    ports:
      - containerPort: 8080
        name: podport
    volumeMounts:
      - name: persistent-storage
        mountPath: /store
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: pvc-demo-final

`

Help me where i am lacking and what could be the error. 
when i run kubectl describe pods pod-with-pvc-demo-final it shows Warning /store files not exists. 

### What did you expect to happen?

![Screenshot from 2023-03-25 15-50-47](https://user-images.githubusercontent.com/124760321/227711381-c2e386a6-7293-4e41-8673-5fb302bf6bb2.png)
 
Expecting pod-with-pvc-demo-final to be in ready state.

### How can we reproduce it (as minimally and precisely as possible)?

checking with the error. 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
