### ISSUE TITLE
Improve observability for Pods that specify a `schedulerName` the cluster doesn't have

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#116982]
### What happened?

Use case: apply a deployment with `schedulerName` specified:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      schedulerName: test  # test not exist
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

When the specified `schedulerName` not exist in the cluster, the pod stuck in pending, with no event or log info to debug.

### What did you expect to happen?

To add event or log info when `schedulerName` not exist, to figure out the pod pending reason quickly.

### How can we reproduce it (as minimally and precisely as possible)?

See above.

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

**Comment by sftim** [comment]
I think Kubernetes is working as designed, so I propose to reframe this:

/retitle Improve observability for Pods that specify a `schedulerName` the cluster doesn't have
/kind feature
/remove-kind bug

**Comment by astraw99** [comment]
> I think Kubernetes is working as designed, so I propose to reframe this:
> 
> /retitle Improve observability for Pods that specify a `schedulerName` the cluster doesn't have /kind feature /remove-kind bug

Sure, now it is more proper.

**Comment by garethsb** [comment]
Encountered this with a pod having `schedulerName: topo-aware-scheduler` on cluster where that scheduler is not deployed. No helpful status or events on the pod or anywhere as far as I can tell...

**Comment by dshebib** [comment]
/unassign
/sig api-machinery

As far as I can tell, there is no way for schedulers to know that a pod matches no other schedulers. We could emit some kind of event or status when pods haven't been scheduled, but this would probably best be handled by implementing an [admission policy](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/) to verify that the scheduler name exists prior to admitting the pod. Somebody more familiar with admission logic could determine if it makes sense to include this as a default check or if there is another way to notify users that the scheduler name does not match.

**Comment by sftim** [comment]
:thought_balloon: Maybe we can declare that schedulers should hold a Lease in kube-system with a label matching their `schedulerName`.

If you submit a Pod (or something with a Pod template) and the `schedulerName` doesn't match a known Lease, we can emit a warning (admission time) and maybe an Event (post admission?)

BTW this is buildable out-of-tree, but then we need to invest effort into making it a recommended add-on.

**Comment by pacoxu** [comment]
> As far as I can tell, there is no way for schedulers to know that a pod matches no other schedulers. We could emit some kind of event or status when pods haven't been scheduled, but this would probably best be handled by implementing an [admission policy](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/) to verify that the scheduler name exists prior to admitting the pod. Somebody more familiar with admission logic could determine if it makes sense to include this as a default check or if there is another way to notify users that the scheduler name does not match.

Following this, kyverno can provide a simple solution like below. You can use 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-names
  namespace: kyverno
data:
  allowed: '["default-scheduler","my-scheduler"]'
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-scheduler-name
spec:
  emitWarning: true
  background: true
  rules:
  - name: known-scheduler-name
    match:
      any:
      - resources:
          kinds: ["Pod"]
          operations: ["CREATE", "UPDATE"]
    context:
    - name: schedulers
      configMap:
        name: scheduler-names
        namespace: kyverno
    validate:
      failureAction: Audit   # use Enforce if you want to block it
      message: "Unknown schedulerName {{ request.object.spec.schedulerName }}."
      deny:
        conditions:
          any:
          - key: "{{ request.object.spec.schedulerName || 'default-scheduler' }}"
            operator: AnyNotIn
            value: '{{ schedulers.data.allowed | parse_json(@) }}'
```

https://github.com/kubernetes/kubernetes/pull/117407 which adds an event, was declined by sig scheduling maintainers.
https://github.com/kubernetes/kubernetes/pull/139750 is trying to add a debug log.
