### ISSUE TITLE
topologySpreadConstraints with DoNotSchedule and bad AZ leads to 7/9 pending in that AZ

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#116978]
### What happened?

- make 1 of the AZs have insufficient capacity
- create deployment with 9 replicase and AZ spread with DoNotSchedule and maxSkew 1
- 7/9 pods end up as pending in the bad AZ

```
NAME                             READY   STATUS    RESTARTS   AGE   ZONE
donotschedule-69fb6f5469-4kffs   1/1     Running   0          7s    us-west-2b
donotschedule-69fb6f5469-bfn46   0/1     Pending   0          7s
donotschedule-69fb6f5469-dvfbn   0/1     Pending   0          7s
donotschedule-69fb6f5469-frprz   0/1     Pending   0          7s
donotschedule-69fb6f5469-qsb75   0/1     Pending   0          7s
donotschedule-69fb6f5469-r8sfc   1/1     Running   0          7s    us-west-2c
donotschedule-69fb6f5469-spdlv   0/1     Pending   0          7s
donotschedule-69fb6f5469-wmhhq   0/1     Pending   0          7s
donotschedule-69fb6f5469-zbrs7   0/1     Pending   0          7s
```

### What did you expect to happen?

3/9 being pending in the bad AZ

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
---
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: donotschedule
        namespace: kube-public
        labels:
          role: donotschedule
      spec:
        replicas: 9
        selector:
          matchLabels:
            role: donotschedule
        template:
          metadata:
            labels:
              role: donotschedule
          spec:
            topologySpreadConstraints:
            - labelSelector:
                matchLabels:
                  role: donotschedule
              maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
            containers:
            - name: default
              image: busybox
              resources:
                requests:
                  cpu: 0.1
                  memory: 100Mi
                limits:
                  cpu: 0.2
                  memory: 200Mi
              args: ["/bin/sleep", "999"]
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
AWS
</details>

**Comment by sanposhiho** [comment]
> make 1 of the AZs have insufficient capacity

@grosser you meant to say that one AZ has less CPU or memory than each Pod requests?
Also, could you share the result of `kubectl describe pods <unscheduled Pod>`?

**Comment by grosser** [comment]
No, 1 az has no nodes without enough free cpu capacity while the others have some.
The nodes in all azs have enough memory/cpu to fit the pod if they were empty/

```
Node:                 <none>
Status:               Pending
...
Topology Spread Constraints:  topology.kubernetes.io/zone:DoNotSchedule when max skew 1 is exceeded for selector pod-template-hash=69fb6f5469,role=donotschedule
...
  Warning  FailedScheduling  46s   default-scheduler  0/17 nodes are available: 1 Insufficient cpu, 1 node(s) had untolerated taint {node.kubernetes.io/unschedulable: }, 10 node(s) had untolerated taint {ownedby: compute}, 11 node(s) didn't match pod topology spread constraints, 3 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: true}, 6 node(s) were unschedulable. preemption: not eligible due to preemptionPolicy=Never.
```

**Comment by sanposhiho** [comment]
Ah, ok, I misunderstood the situation. Thanks for sharing the detail.
Then, the answer is that everything is working expectedly from the scheduler's PoV.

The scheduler basically schedules pending Pods one by one. It doesn't take any other pending Pods into consideration during scheduling.

So, in your scenario, 
1. the scheduler scheduled the first two Pods to different zone's Nodes.
2. the scheduler wanted to schedule the next one to the third zone, but Pods couldn't go due to insufficient resources.
3. All other Pods got unschedulable in the same reason.
4. As a result, 2 went to Nodes, and other couldn't go anywhere.

**Comment by grosser** [comment]
Yeah, that sounds about right.
So a possible fix would be to make the scheduler look at pending pods too.

Current behavior is bad when 1 az is in trouble and then suddenly the whole app is down, only semi-fix I found so far was to cordon the whole AZ and then use "nodeTaintsPolicy: Honor", but that means manual effort and another restart for all pods.

**Comment by sanposhiho** [comment]
I wouldn't say the current behavior is wrong.
Because if it goes as your expectation (`3/9 being pending in the bad AZ`), it obviously violates the `minSkew`.

**Comment by sanposhiho** [comment]
> Current behavior is bad when 1 az is in trouble and then suddenly the whole app is down

But, this is true. If one az has trouble, that affects the scheduling on other zones as well.
So, probably, what we want to have is https://github.com/kubernetes/kubernetes/issues/105977.

**Comment by grosser** [comment]
Yeah that sounds good!

**Comment by csatl** [comment]
> Because if it goes as your expectation (3/9 being pending in the bad AZ), it obviously violates the maxSkew.

I think the behaviour may be correct in the sense that it is what is documented but I think it would be much more useful to consider Pending pods in the calculation. This is because I think the expectation when someone is setting maxSkew to 1 with replicas 9 is that if one of three AZ is down is that they would still have 6 pods running not that they would be limited to only 2 pods.

**Comment by sanposhiho** [comment]
> if one of three AZ is down is that they would still have 6 pods running not that they would be limited to only 2 pods.

Actually, "one of three AZ is down" is a bit different from what I was assuming for this issue, which defined the situation like "1 of the AZs have insufficient capacity".

In your case, if all nodes within one AZ facing issue have taints properly, you can just use `nodeTaintsPolicy: Honor` and then your deployment should ignore all nodes in the dead AZ at the spreading calculation, and schedule all your pods into two pods evenly.

**Comment by csatl** [comment]
I think my point was more that I think it still makes sense to schedule pods to an AZ even "maxSkew" might be exceeded provided that after all the Pending pods are scheduled the skew is less than maxSkew. It seems relatively easy to compute just check <pods in AZ + 1> < <max Skew>  + <total pods> / <domains>. I agree that would be a change but I don't understand how anyone could depend on the previous behaviour.

In our case I think it makes sense to use three StatefulSets because that also solves some edge cases around scaling as because of a PVC we can't "move" pods between AZs.

**Comment by sanposhiho** [comment]
First, as you mentioned, we cannot break this existing behavior in the first place. We'd need an API so that people can opt-in the behavior only if they want, and otherwise keep the current behavior. 

Second, from a technical perspective, the scheduler doesn't know which pods belong to the same group. It just schedules pods one by one and don't consider other pending pods.

Let's say pod-a has this constraint:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    app: awesome-app
spec:
...
          topologySpreadConstraints:
            - labelSelector:
                matchLabels:
                  app: awesome-app
              maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule
```

Then, if we want to compute like your formula, how would it get `<total pods>`? It's impossible to fetch by `app: awesome-app` label because maybe not all pods with the label have the constraint. 

And, third, from the behavior perspective, why do we still want to keep 2 pods pending (in your scenario)? I know the current behavior is worse because it only allows only 2 pods to be scheduled, while keeping 7 pods pending. 
But, I believe the ideal behavior, in general, is to spread pods evenly for reliability. For example, people just want to keep pods spread across all available AZs so that the service can be reliable even when one AZ is dead. And then, when one AZ is actually dead, they probably wouldn't want to keep pods in one AZ pending, but they would expect them to be scheduled on other AZs instead of a dead AZ so that the service gets a full replicas coming back soon even after one AZ's issue.
That's why I'm saying let's wait for https://github.com/kubernetes/kubernetes/issues/105977. It's simpler and more aligned with that expectation; people define their pods can be fallback to other AZs in such cases. In your scenario, if one AZ is dead, all pods would go to two alive AZs evenly, not keeping two pods pending.

Also, sidenote though, Pod Topology Spread is already one of the slowest in-tree plugins. So, for that reason as well, we don't want to put additional calculations basically in it.
