### ISSUE TITLE
`kubectl -oyaml -w` should return fully deliminated objects 

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#117075]
### What happened?

Watching an object returns outputs like:

Single object:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: obj1
  namespace: default
```

Multiple objects:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: obj2
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obj2
  namespace: default
```

### What did you expect to happen?

Watching an object returns output like:

```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: obj1
  namespace: default
---
```

Multiple objects:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: obj2
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obj2
  namespace: default
---
```

This is helpful as a tool parsing the output has no way to know if the last object is incomplete in the current format - it could have just not been fully read yet.

### How can we reproduce it (as minimally and precisely as possible)?

Just `kubectl -w -oyaml` anything

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ardaguclu** [comment]
Seems like duplicate of https://github.com/kubernetes/kubectl/issues/1265

**Comment by liggitt** [comment]
I'm not sure that would be valid… isn't the --- separator the header of the next object?

**Comment by howardjohn** [comment]
@liggitt I think you are right

The yaml spec does have `...` to indicate this and actually gives a streaming example:

```yaml
# A communication channel based on a YAML stream.
---
sent at: 2002-06-06 11:46:25.10 Z
payload: Whatever
# Receiver can process this as soon as the following is sent:
...
# Even if the next message is sent long after:
---
sent at: 2002-06-06 12:05:53.47 Z
payload: Whatever
...
```

(example 4.9 on https://yaml.org/spec/1.0/)

So seems like that may be an alternative - but a bigger diff from what is done today. I am not sure the libraries even support emitting this format today, and not sure how many can process this form either

**Comment by liggitt** [comment]
Once we know there's no more output, the stream ends and any reader would get an EOF. I don't think a "…" is necessary in this case

**Comment by ardaguclu** [comment]
You are right, it seems working as expected. And this issue is NOT duplicate of https://github.com/kubernetes/kubectl/issues/1265

**Comment by howardjohn** [comment]
This is the concern I am seeing:

```yaml
sent at: 2002-06-06 11:46:25.10 Z
payload: Whatever

# When I have read this far in the stream, how do I know the payload is incomplete and has some more data later in the same object, or I am waiting for a new object?

---
sent at: 2002-06-06 12:05:53.47 Z
payload: Whatever

#  EOF occurs here, not a problem
```

So if you are processing the stream of yaml objects, you will always be 1 object behind
