### ISSUE TITLE
Not possible to access rootfs from an ephemeral container when user namespace is enabled

### ISSUE THREAD

**Issue by asierHuawei** [kubernetes/kubernetes#117159]
### What happened?

A pod is created with user namespace

``` yaml
apiVersion: v1
kind Pod
metadata:
    name: alpine
    namespace: default
sepc:
    hostUsers: false
    containers:
    - image: alpine:latest
      command:
        - /bin/sh
        - "c"
      args:
        - sleep infinity;
      imagePullPolicy: IfNotPresent
      name: alpine
    restartPolicy: always
```

Then, create a debug ephemeral container

``` bash
# kubectl debug -it alpine --image=busybox:latest --target=alpine
```

When I try to access the file system from the alpine container, I get an error.

```bash
# ls -lsh /proc/1/root
ls: /proc/1/root: cannot read link: Permission denied
```

/proc/1/root is just a symlink that points to nowhere

### What did you expect to happen?

Be able to acces the files from the original alpine container throught /proc/1/root

### How can we reproduce it (as minimally and precisely as possible)?

File alpine.yaml

``` yaml
apiVersion: v1
kind Pod
metadata:
    name: alpine
    namespace: default
sepc:
    hostUsers: false
    containers:
    - image: alpine:latest
      command:
        - /bin/sh
        - "c"
      args:
        - sleep infinity;
      imagePullPolicy: IfNotPresent
      name: alpine
    restartPolicy: always
```

``` bash
# kubectl apply -f alpine.yaml
```

``` bash
# kubectl debug -it alpine --image=busybox:latest --target=alpine
```

### Kubernetes version

v1.26.1

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

Any runtime that supports user namespaces. I have tested it with containerd master branch.

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by iyear** [comment]
I can't reproduce the bug.

And your yaml has some errors, after fixing the result is as follows:

```yaml
# 117159.yaml
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  hostUsers: false
  containers:
    - image: alpine:latest
      command:
        - /bin/sh
        - "-c"
      args:
        - "sleep infinity"
      imagePullPolicy: IfNotPresent
      name: alpine
  restartPolicy: Always
```

Steps:
```
$ kind create cluster --image kindest/node:v1.26.3@sha256:61b92f38dff6ccc29969e7aa154d34e38b89443af1a2c14e6cfbd2df6419
c66f
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.26.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂

$ k version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-30T06:34:50Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

$ k apply -f 117159.yaml
pod/alpine created

$ k get pods
NAME     READY   STATUS    RESTARTS   AGE
alpine   1/1     Running   0          4s

$ k debug -it alpine --image=busybox:latest --target=alpine
/ # ls -lsh /proc/1/root
      0 lrwxrwxrwx    1 root     root           0 Apr 11 07:38 /proc/1/root -> /
```
