### ISSUE TITLE
When periodSeconds is shorter than processing time, startupProbe is executed twice.

### ISSUE THREAD

**Issue by R-HNF** [kubernetes/kubernetes#117153]
### What happened?

I use startupProbe in the following Deployment. In the startupProbe, it waits for the application to start with `initialDelaySeconds: 50` and then start the warm-up process with `timeoutSeconds: 95`. The warm-up process takes about 40 seconds, and the interval in probe is set to `periodSeconds: 10`.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
        - name: api
          image: <IMAGE> # Actually, it is an application image.
         resources:
            limits:
              cpu: "500m"
              memory: "800Mi"
          readinessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 20"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      startupProbe:
        exec:
          command:
            - sh
            - -c
            - |
              echo "$(date) startupProbe start" >> /tmp/startupProbe-check
              if [ ! $(curl -s -w "%{http_code}\n" "http://localhost:8080/health-check" -o /dev/null) -eq 200 ]; then
                echo "$(date) startupProbe failed" >> /tmp/startupProbe-check
                exit 1
              fi
              echo "$(date) startupProbe warmup-start" >> /tmp/startupProbe-check
              curl "http://localhost:8080/<API_PATH>"
              sleep 40 # Actually, it is a warmup process.
          echo "$(date) startupProbe warmup-end" >> /tmp/startupProbe-check
        initialDelaySeconds: 0
        periodSeconds: 100
        timeoutSeconds: 100
        successThreshold: 1
        failureThreshold: 1
```

When I run this Deployment, it waits for the application to start for `initialDelaySeconds` as expected. Immediately after that, the first probe begins and succeeds. The `successThreshold` is set to `1`, and since the first probe succeeded, I thought that `startupProbe` ended there, but immediately after the first probe succeeded, the second probe started.

Is this because the `periodSeconds` is too short for the processing time of `exec`, so the second probe is waiting, and it is executed regardless of the success or failure of the first one?

### What did you expect to happen?

Even if the `periodSeconds` is too short for the processing time of `exec` and the second probe has been waiting, I want to make sure that the second probe does not run with the result of the last one.

### How can we reproduce it (as minimally and precisely as possible)?

You can use the following yaml, and check the log `/tmp/startupProbe-check` in the container to see that the second probe is running immediately after the first probe.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-probe-research
spec:
  selector:
    matchLabels:
      run: startup-probe-research
  template:
    metadata:
      labels:
        run: startup-probe-research
    spec:
      containers:
        - name: startup-probe-research
          image: nginx # Actually, it is an application image.
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  echo "$(date) startupProbe start" >> /tmp/startupProbe-check
                  if [ ! $(curl -s -w "%{http_code}\n" "http://localhost:80/" -o /dev/null) -eq 200 ]; then
                    echo "$(date) startupProbe failed" >> /tmp/startupProbe-check
                    exit 1
                  fi
                  echo "$(date) startupProbe warmup-start" >> /tmp/startupProbe-check
                  curl "http://localhost:80/"
                  sleep 40 # Actually, it is a warmup process.
                  echo "$(date) startupProbe warmup-end" >> /tmp/startupProbe-check
            initialDelaySeconds: 50
            periodSeconds: 10
            timeoutSeconds: 95
            successThreshold: 1
            failureThreshold: 10
```

### Anything else we need to know?

If you increase the `periodSeconds` to `100` seconds, the second probe will not be executed as expected.
However, if `initialDelaySeconds` is shorter than `periodSeconds`, `initialDelaySeconds` becomes meaningless and the application will wait `100` seconds for the first probe. This means that even if the application is started, there will be time wasted waiting for the first probe to be executed.

### Kubernetes version

<details>
 
It happens in both AWS and Docker Deskop.
 
AWS
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.16", GitCommit:"b28e1f370a4a4c428ddbeababcaf0198f048fcac", GitTreeState:"clean", BuildDate:"2022-11-09T13:37:37Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.17-eks-48e63af", GitCommit:"47b89ea2caa1f7958bc6539d6865820c86b4bf60", GitTreeState:"clean", BuildDate:"2023-01-24T09:34:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
 
Docker Desktop
```console
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.16", GitCommit:"b28e1f370a4a4c428ddbeababcaf0198f048fcac", GitTreeState:"clean", BuildDate:"2022-11-09T13:37:37Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.25) exceeds the supported minor version skew of +/-1
```
 
</details>

### Cloud provider

<details>
* AWS
* Docker Desktop
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
