### ISSUE TITLE
can't upgrade ds pods when a new node join and leave(become unavailable)

### ISSUE THREAD

**Issue by ShuhanYan** [kubernetes/kubernetes#117204]
### What happened?

Hi, I'm a K8s cluster maintainer, and I have a scenario in which some nodes will join and leave my cluster frequently and the node may not be deleted immediately.  After I trigger the upgrade deployment of our system daemonset in rolling upgrade mode, and then a node joins our cluster, it will run the new version of the ds pod. And then the node leave and the ds pod on it becomes unavailable, the deployment will be stuck due to this node.

### What did you expect to happen?

1. I found a for loop in [here](https://github.com/kubernetes/kubernetes/blob/ad18954259eae3db51bac2274ed4ca7304b923c4/pkg/controller/daemon/update.go#LL73C31-L73C48), and the nodes which shouldn't run daemon pod don't be removed from nodeToDaemonPods, and I found that they are removed from [desiredNumberScheduled](https://github.com/kubernetes/kubernetes/blob/ad18954259eae3db51bac2274ed4ca7304b923c4/pkg/controller/daemon/update.go#LL532C1-L543C3). Will it be better to remove those nodes from "nodeToDaemonPods"? thus we don't need to check the status of the pods on them.
2. Or could we check whether the node shouldn't run daemon pod before counting it into [numUnavailable](https://github.com/kubernetes/kubernetes/blob/ad18954259eae3db51bac2274ed4ca7304b923c4/pkg/controller/daemon/update.go#LL70C7-L70C22)? 

### How can we reproduce it (as minimally and precisely as possible)?

1. trigger the daemonset upgrade deployment
2. a node joins our cluster, it will run the new version of the ds pod
3. the node leave and the ds pod on it becomes unavailable
4. deployment will be stuck due to this node

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-19T18:39:03Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
bare mental
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mochizuki875** [comment]
@ShuhanYan 
Hi, I will try to fix this.

/assign @mochizuki875

**Comment by mochizuki875** [comment]
@ShuhanYan 

A brief and concrete reproduction of this problem is as follows, right?

Now, we have 3 Nodes(except ControlPlane Node). 
```
$ kubectl get no
NAME                  STATUS   ROLES           AGE   VERSION
k8s-cluster2-cp01     Ready    control-plane   13d   v1.27.1
k8s-cluster2-node01   Ready    <none>          13d   v1.27.1
k8s-cluster2-node02   Ready    <none>          13d   v1.27.1
k8s-cluster2-node03   Ready    <none>          13d   v1.27.1
```

Create `Daemonset`.

<details>

`nginx-daemonset.yaml`
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  selector:
    matchLabels:
      app: nginx-ds
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.4
        # image: nginx:1.24.0
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 60"]
```

Notably, the following `updateStrategy` are set implicity by default.

```yaml
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
```

</details>

```
$ kubectl apply -f nginx-daemonset.yaml
daemonset.apps/nginx-ds created

$ kubectl get po -l app=nginx-ds -owide
NAME             READY   STATUS    RESTARTS   AGE   IP             NODE                  NOMINATED NODE   READINESS GATES
nginx-ds-8x2mt   1/1     Running   0          23s   10.0.194.21    k8s-cluster2-node01   <none>           <none>
nginx-ds-kz6p4   1/1     Running   0          23s   10.0.30.108    k8s-cluster2-node02   <none>           <none>
nginx-ds-qdnkz   1/1     Running   0          23s   10.0.159.146   k8s-cluster2-node03   <none>           <none>
```

Update the `Daemonset`.

<details>

`nginx-daemonset.yaml`
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  selector:
    matchLabels:
      app: nginx-ds
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
      - name: nginx
        # image: nginx:1.23.4
        image: nginx:1.24.0
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 60"]
```

</details>

```
$ kubectl apply -f nginx-daemonset.yaml
```


When specific `Pod` starts to be `Terminating`, stop `kubelet` on the `Node`.
In this case, when `nginx-ds-8x2mt` on `k8s-cluster2-node01` starts to be `Terminating`, stop `kubelet` on `k8s-cluster2-node01`.


```
$ kubectl get po -l app=nginx-ds -owide -w
NAME             READY   STATUS        RESTARTS   AGE   IP             NODE                  NOMINATED NODE   READINESS GATES
nginx-ds-8x2mt   1/1     Running       0          50s   10.0.194.21    k8s-cluster2-node01   <none>           <none>
nginx-ds-kz6p4   1/1     Terminating   0          50s   10.0.30.108    k8s-cluster2-node02   <none>           <none>
nginx-ds-qdnkz   1/1     Running       0          50s   10.0.159.146   k8s-cluster2-node03   <none>           <none>
nginx-ds-kz6p4   1/1     Terminating   0          74s   10.0.30.108    k8s-cluster2-node02   <none>           <none>
nginx-ds-kz6p4   0/1     Terminating   0          74s   <none>         k8s-cluster2-node02   <none>           <none>
nginx-ds-kz6p4   0/1     Terminating   0          75s   10.0.30.108    k8s-cluster2-node02   <none>           <none>
nginx-ds-kz6p4   0/1     Terminating   0          75s   10.0.30.108    k8s-cluster2-node02   <none>           <none>
nginx-ds-kz6p4   0/1     Terminating   0          75s   10.0.30.108    k8s-cluster2-node02   <none>           <none>
nginx-ds-6gz57   0/1     Pending       0          0s    <none>         <none>                <none>           <none>
nginx-ds-6gz57   0/1     Pending       0          0s    <none>         k8s-cluster2-node02   <none>           <none>
nginx-ds-6gz57   0/1     ContainerCreating   0          0s    <none>         k8s-cluster2-node02   <none>           <none>
nginx-ds-6gz57   0/1     ContainerCreating   0          0s    <none>         k8s-cluster2-node02   <none>           <none>
nginx-ds-6gz57   1/1     Running             0          16s   10.0.30.109    k8s-cluster2-node02   <none>           <none>
nginx-ds-8x2mt   1/1     Terminating         0          91s   10.0.194.21    k8s-cluster2-node01   <none>           <none>
```

```
root@k8s-cluster2-node01:~# systemctl stop kubelet
```

Eventually, `Pod`(`nginx-ds-8x2mt`) `Terminating` and subsequent update process will be stuck.
