### ISSUE TITLE
Implement "depends_on" for kind deployment

### ISSUE THREAD

**Issue by Stenstromen** [kubernetes/kubernetes#117359]
Hi!

I would like something similar to docker-compose's "depends_on" feature.

For example in deployment dependent on mysql:
```
    depends_on:
      - mysql
```

Currently, I am doing the following workaround. 
Using initContainers, I check the connection to the MariaDB service with Alpine and NetCat
```
      initContainers:
      - command:
        - sh
        - -c
        - for i in $(seq 1 300); do nc -zvw1 mariadb-service 3306 && exit 0 || sleep
          3; done; exit 1
        image: alpine:3.17
        name: init-wait
```
