### ISSUE TITLE
Grace Termination Period timer doesn't start before preStop

### ISSUE THREAD

**Issue by cyrus-mc** [kubernetes/kubernetes#117373]
### What happened?

Implementing graceful shutdown by leveraging `preStop` hooks. According to all the documentation I can find the `terminatinoGracePeriodSeconds` includes the time that the `preStop` is running, meaning the timer starts before `preStop` executes.

In my setup I have a simple `preStop` that sleeps for 15 seconds. In my app code I then sleep for 90 seconds in the SIGTERM handler. Given that the default terminationGracePeriod is 30 seconds I would expect that the POD is killed 15 seconds after the SIGTERM handler reports it received the signal. However the POD receives the SIGTERM (prints out that it did) and then lives for a while 30 seconds after that point. 

### What did you expect to happen?

As it states here:

* https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
* https://www.datree.io/resources/kubernetes-guide-graceful-shutdown-with-lifecycle-prestop-hook#anchor5
* https://livebook.manning.com/concept/kubernetes/terminationgraceperiodsecond

```
The Pod's termination grace period countdown begins before the PreStop hook is executed, so regardless of the outcome of the handler, the container will eventually terminate within the Pod's termination grace period.
```

### How can we reproduce it (as minimally and precisely as possible)?

I have the following simple NodeJS app:

```
import * as Koa from 'koa';
import * as Router from 'koa-router';

const app = new Koa();
const router = new Router();

function delay(time) {
  return new Promise(resolve => setTimeout(resolve, time));
}

router.get("/", ctx => {
  ctx.body = 'Hello World';
});

app.use(router.routes);
app.use(router.allowedMethods());

export const server = app.listen(3000, () => {
  console.log(`Server listening on port 3000`);
});

process.on('SIGTERM', () => {
  server.close(async() => {
    console.log('Received SIGTERM, closing server');
    await delay(90000);
  });
});
```

As you can see in the SIGTERM handler it prints out the signal was received and then simply sleeps for 90 seconds.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  namespace: default
  labels:
    app: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-jfrog
      containers:
      - name: node
        image: test:latest
        lifecycle:
          preStop:
            exec:
              command:
                - sleep
                - "15"
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 256Mi
```

My deployment of above code adds a preStop that simply sleeps for 15 seconds. 

When I delete this POD, the application receives the SIGTERM after 15 seconds (as expected). It then lives for a whole 30 more seconds before being forcefully terminated. Give that the `terminationGracePeriodSeconds` is set to 30 seconds if I am interpreting the documentation above correctly the POD should have been forcefully terminated at 15 seconds after receiving SIGTERM.

```
    lifecycle:
      preStop:
        exec:
          command:
          - sleep
          - "15"
    name: node
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30

```

### Kubernetes version

<details>

```console
› kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.16-eks-48e63af", GitCommit:"e6332a8a3feb9e0fe3db851878f88cb73d49dd7a", GitTreeState:"clean", BuildDate:"2023-01-24T19:18:15Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

Running in AWS EKS version 1.23.

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

Container Runtime Version:  containerd://1.6.15+bottlerocket
