### ISSUE TITLE
Strategic Merge does not handle directives for empty slices. 

### ISSUE THREAD

**Issue by KevinJoiner** [kubernetes/kubernetes#117470]
### What happened?

When performing a strategic merge for a slice of maps with `patchStrategy=merge`, directives in the patch slice are ignored if the original list is empty. Instead, the merged slice still contains the directives. This causes the patched object to fail subsequent validation since it has directives in a slice.

This behavior can be seen if one attempts to patch `ValidatingWebhookConfiguration.admissionregistration.k8s.io` specifically changes to the optional field [Webhooks](https://github.com/kubernetes/api/blob/master/admissionregistration/v1beta1/types.go#L93-L97).

If the original object has the following value
``` json
{
    "apiVersion": "admissionregistration.k8s.io/v1",
    "kind": "ValidatingWebhookConfiguration",
    "metadata": {
        "creationTimestamp": "2023-04-19T13:41:39Z",
        "generation": 2,
        "name": "base-validation",
        "resourceVersion": "200160",
        "uid": "70d47b26-ddba-430a-82d2-3fe7f8b4b840"
    }
}
```
And we attempt to do a strategic patch with the following information 
``` json
{
    "$setElementOrder/webhooks": [
        {
            "name": "new.foo.com"
        }
    ],
    "webhooks": [
        {
            "admissionReviewVersions": [
                "v1"
            ],
            "clientConfig": {
                "url": "https://foo.com"
            },
            "name": "new.foo.com",
            "sideEffects": "None"
        },
        {
            "$patch": "delete",
            "name": "foo.bar.com"
        }
    ]
}
```
The resulting object will look like the following JSON and fail validation.
``` json
{
    "apiVersion": "admissionregistration.k8s.io/v1",
    "kind": "ValidatingWebhookConfiguration",
    "metadata": {
        "creationTimestamp": "2023-04-19T13:41:39Z",
        "generation": 2,
        "name": "base-validation",
        "resourceVersion": "200160",
        "uid": "70d47b26-ddba-430a-82d2-3fe7f8b4b840"
    },
    "webhooks": [
        {
            "admissionReviewVersions": [
                "v1"
            ],
            "clientConfig": {
                "url": "https://foo.com"
            },
            "name": "new.foo.com",
            "sideEffects": "None"
        },
        {
            "$patch": "delete",
            "name": "foo.bar.com"
        }
    ]
}
```
Errors:
```
The ValidatingWebhookConfiguration "base-validation" is invalid: 
* webhooks[1].sideEffects: Required value: must specify one of None, NoneOnDryRun
* webhooks[1].clientConfig: Required value: exactly one of url or service is required
* webhooks[1].admissionReviewVersions: Required value: must specify one of v1, v1beta1
```

### What did you expect to happen?

Strategic merge always handles any directives in the patch.

## Repo steps with kubectl
1. Apply the following webhook configuration `kubectl apply`
    ``` yaml
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: base-validation
    webhooks:
      - name: foo.bar.com
        admissionReviewVersions:
          - "v1"
        clientConfig:
          url: https://foo.com
        sideEffects: None
    ```
2. Edit the newly created webhook and remove the Webhooks list. `kubectl edit validatingwebhookconfiguration base-validation`

3. Attempt to apply the following webhook configuration with `kubectl apply`
      ``` yaml
      apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      metadata:
        name: base-validation
      webhooks:
        - name: new.foo.com
          admissionReviewVersions:
            - "v1"
          clientConfig:
            url: https://foo.com
          sideEffects: None
    ```

Notice that the request fails with the following errors
```
The ValidatingWebhookConfiguration "base-validation" is invalid: 
* webhooks[1].sideEffects: Required value: must specify one of None, NoneOnDryRun
* webhooks[1].clientConfig: Required value: exactly one of url or service is required
* webhooks[1].admissionReviewVersions: Required value: must specify one of v1, v1beta1
```

### Anything else we need to know?

The logic causing this behavior for the example can be seen here in [apimachinery](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/strategicpatch/patch.go#L1179-L1194)
In this code, we see that if the original value was not found, we blindly assign the `patchFieldValue`

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:46:35Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}

------------

Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.4+k3s1

</details>

### Cloud provider

<details>
N/A local K3s cluster
</details>

### OS version

<details>

```console
# On Mac:
Darwin M1

Running Cluster via docker

# container OS:
a438642cd255: # cat /etc/os-release 
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp4"
DOCUMENTATION_URL="https://documentation.suse.com/"

a438642cd255: # uname
Linux


</details>


### Install tools

<details>
docker 
rancher-desktop
</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
