### ISSUE TITLE
Mismatched URLs for service-account-issuer-discovery and Open API Spec's swagger.json

### ISSUE THREAD

**Issue by michaeljmarshall** [kubernetes/kubernetes#117455]
### What happened?

When I use the official Kubernetes Java Client (version 18.0.0) from within a pod using `Config.defaultClient()` to build an `ApiClient` and then access `getServiceAccountIssuerOpenIDConfiguration` in the `WellKnownApi` I get the following error:

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:serviceaccount:test:user\" cannot get path \"/.well-known/openid-configuration/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

The same happens with the `OpenidApi#getServiceAccountIssuerOpenIDKeyset`.

However, the problem does not happen when I call the `/.well-known/openid-configuration` endpoint using the pod's service account and curl.

The problem is that the generated Open API spec indicates that the client should call `/.well-known/openid-configuration/` instead of `/.well-known/openid-configuration` (and similarly `/openid/v1/jwks/` instead of `/openid/v1/jwks`). While the API Server seems to resolve these endpoints just fine, the `ClusterRole` defined in the code does not have the trailing slashes and therefore rejects the requests with a 403:

https://github.com/kubernetes/kubernetes/blob/6a75e7c40cab5a0d96d815c3aa976dc98b4b0972/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L521-L530

### What did you expect to happen?

I expected to be able to access these APIs from within a pod that has a mounted service account because this [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery) suggests all that is required is a service account and because all clusters get this `ClusterRoleBinding` and this `ClusterRole` by default:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:service-account-issuer-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:service-account-issuer-discovery
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:service-account-issuer-discovery
rules:
- nonResourceURLs:
  - /.well-known/openid-configuration
  - /openid/v1/jwks
  verbs:
  - get
```

### How can we reproduce it (as minimally and precisely as possible)?

Here is the Java snippet to reproduce it:

```Java
        ApiClient k8sApiClient = Config.fromCluster();
        WellKnownApi wellKnownApi = new WellKnownApi(k8sApiClient);
        try {
            wellKnownApi.getServiceAccountIssuerOpenIDConfiguration();
        } catch (ApiException e) {
            LOG.error("Message: " + e.getMessage() + " Response body: " + e.getResponseBody());
        }
```

When run from within a pod that has a service account mounted into it, the above code will fail.

You can also reproduce the error without the Java Client by running `curl --cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)"  https://kubernetes.default.svc/.well-known/openid-configuration/` from within a pod.

I can resolve the issue by updating the `system:service-account-issuer-discovery` cluster role to have the endpoints with the trailing `/`.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:service-account-issuer-discovery
rules:
- nonResourceURLs:
  - /.well-known/openid-configuration/
  - /.well-known/openid-configuration
  - /openid/v1/jwks/
  - /openid/v1/jwks
  verbs:
  - get
```

### Anything else we need to know?

I am happy to provide a fix, if I can get the right pointers. The detail I'm unclear on is how to fix this in a backwards compatible way.

Also, this PR seems to have introduced the potentially problematic `swagger.json` entry: https://github.com/kubernetes/kubernetes/pull/93258.

### Kubernetes version

<details>

Here is one of the remote clusters I reproduced the issues with.

```console
$ kubectl version
 kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:29:16Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

I reproduced this bug in multiple cloud providers as well as in minikube. It does not appear to be cloud provider specific. 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
