### ISSUE TITLE
Pods in terminal state are still counted as "used" count/pods quota

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#117663]
### What happened?

According to https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota:

| Resource Name | Description                                                                                                                                                     |
|---------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| pods          | The total number of Pods in a non-terminal state that can exist in the namespace. A pod is in a terminal state if .status.phase in (Failed, Succeeded) is true. |

Terminated pods are still counted as "used" count/pods quota. See the following section for repro steps.

### What did you expect to happen?

Terminal Pods shouldn't be counted as "used" count/pods quota.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a quota:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
spec:
  hard:
    count/pods: "8"
    limits.cpu: "4"
    limits.memory: 2000Gi
    requests.cpu: "4"
    requests.memory: 400Gi
```
- Create a Job with replicas=1
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: alpine
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        command:
         - "sh"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never
```
- Check quota after the Job is completed
```console
⇒  k get job                                                                                                               (⎈|kind-kind:N/A)
NAME        COMPLETIONS   DURATION   AGE
countdown   1/1           7s         11s

⇒  k get quota                                                                                                             (⎈|kind-kind:N/A)
NAME    AGE   REQUEST                                                        LIMIT
quota   48s   count/pods: 1/8, requests.cpu: 0/4, requests.memory: 0/400Gi   limits.cpu: 0/4, limits.memory: 0/2000Gi
```
- Regular resources are not counted in quota, but count/pods is still counted

### Anything else we need to know?

This bug will cause Job's completion pods still consume count/pods quota. count/pods quota can only be reset when the pods are physically deleted. 

### Kubernetes version

master, and possibly all k8s versions.

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
