### ISSUE TITLE
`ResourceQuota` with "PriortyClass" as its scope is not calculated properly

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#117676]
### What happened?

If a Pod is subjected to a `ResourceQuota` with "PriortyClass" as its scope, the quota's calculation is incorrect. See repo steps for more details.

### What did you expect to happen?

`ResourceQuota` with "PriortyClass" as its scope can be calculated at all times.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a PriorityClass named "p1"
```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: p1
value: 100
```
- Create a quota with `PriorityClass` as its scope. ⚠️ Note: w/o specifying `PriorityClass`, this issue won't happen
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-p4
spec:
  hard:
    count/pods: "8"
    limits.cpu: "4"
    limits.memory: 2000Gi
    requests.cpu: "4"
    requests.memory: 400Gi
  scopes:
  - PriorityClass <=== Notice this line
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - p1
```
- Create a Job and wait for its completion.
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  template:
    metadata:
      name: countdown
    spec:
      priorityClassName: p1
      containers:
      - name: counter
        image: alpine
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        command:
         - "sh"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never
```
```
⇒  k get job
NAME        COMPLETIONS   DURATION   AGE
countdown   1/1           7s         8s
```
- Check quota's usage calculation
```
NAME       AGE    REQUEST                                                        LIMIT
quota-p1   2m8s   count/pods: 0/8, requests.cpu: 0/4, requests.memory: 0/400Gi   limits.cpu: 0/4, limits.memory: 0/2000Gi
```
Here `count/pods` is incorrect - it should be `1/8`.
- Worse calculation may happen if I create a regular pod and then delete the Job:
```
⇒  cat pod1.yaml                                                                                               (⎈|kind-kind:N/A)
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  priorityClassName: p1
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.7
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
⇒  k apply -f pod1.yaml
pod/pod-1 created
⇒  k get quota
NAME       AGE     REQUEST                                                          LIMIT
quota-p1   3m50s   count/pods: 1/8, requests.cpu: 1/4, requests.memory: 2Gi/400Gi   limits.cpu: 1/4, limits.memory: 2Gi/2000Gi
# count/pods is still incorrect - there are two pods at this moment

# Now I delete Job
⇒  k delete job countdown
job.batch "countdown" deleted
⇒  k get pod
NAME    READY   STATUS    RESTARTS   AGE
pod-1   1/1     Running   0          92s
⇒  k get quota
NAME       AGE     REQUEST                                                        LIMIT
quota-p1   4m54s   count/pods: 0/8, requests.cpu: 0/4, requests.memory: 0/400Gi   limits.cpu: 0/4, limits.memory: 0/2000Gi
```
- The eventual result is totally incorrect.

### Kubernetes version

master, and possibly all versions.

### Cloud provider

kind

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
