### ISSUE TITLE
time type field in configuration is zero when kubeadm create cluster

### ISSUE THREAD

**Issue by chwetion** [kubernetes/kubernetes#117772]
### What happened?

use custom kubeadm configuration file to create cluster, but got a lot of zero value in configuration file.

kubeadm configuration file as follow:

```yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.27.1
apiServer:
  extraArgs:
    authorization-mode: "Node,RBAC"
    endpoint-reconciler-type: lease
  certSANs:
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - localhost
  - 127.0.0.1
  - 10.211.55.3
controlPlaneEndpoint: 10.211.55.3:6443

networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: systemd
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
failSwapOn: false
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 70
maxPods: 110
podPidsLimit: 65535
rotateCertificates: true
staticPodPath: /etc/kubernetes/manifests
```

kubelet configuration file genereated by kubeadm as follow:

```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: systemd
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
containerRuntimeEndpoint: ""
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
failSwapOn: false
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 70
imageMinimumGCAge: 0s
kind: KubeletConfiguration
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: 0
maxPods: 110
memorySwap: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
podPidsLimit: 65535
rotateCertificates: true
runtimeRequestTimeout: 0s
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
```

### What did you expect to happen?

i don't know if these fields with a value of 0 will cause kubelet to run abnormally, or convert default value.

these filed undeclared in kubeadm configuration file should not written to configuration files. just use default value.

### How can we reproduce it (as minimally and precisely as possible)?

```console
cat > kubeadm-conf.yaml <<EOF 
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.27.1
apiServer:
  extraArgs:
    authorization-mode: "Node,RBAC"
    endpoint-reconciler-type: lease
  certSANs:
  - kubernetes
  - kubernetes.default
  - kubernetes.default.svc
  - localhost
  - 127.0.0.1
  - 10.211.55.3
controlPlaneEndpoint: 10.211.55.3:6443

networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: systemd
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
failSwapOn: false
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 70
maxPods: 110
podPidsLimit: 65535
rotateCertificates: true
staticPodPath: /etc/kubernetes/manifests
EOF

kubeadm init --config ./kubeadm-conf.yaml
```

### Kubernetes version

```console
[root@localhost ~]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[root@localhost ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:20:04Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud provider

localhost

### OS version

```console
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Install tools

kubeadm
