### ISSUE TITLE
Pods being scheduled to a cordon'ed node due to the presence of nodeName field

### ISSUE THREAD

**Issue by matheusjunior** [kubernetes/kubernetes#117843]
Playing around with kind, I noticed the following somewhat unexpected behavior:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      nodeName: kind-worker
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - "3600"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
```

Using this deployment on a 3-node kind cluster, all two pods get scheduled onto kind-worker node. Now suppose I drain that node by running `kubectl drain --ignore-daemonsets kind-worker`. The node gets cordon'ed (no more pods can be assigned to it) and then all pods are evicted. All pods are rescheduled to the same node due to the presence of `nodeName` field, but that node has just been marked as unschedulable.

It is clear there is a conflict here, and `nodeName` feature takes precedence, so I assume this behavior is expected. Thus, the section [Use kubectl drain to remove a node from service](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#use-kubectl-drain-to-remove-a-node-from-service) could be updated to reflect it is not safe to turn off the node since there are pods running on it. Quoting the doc:
> It is then safe to bring down the node by powering down its physical machine or, if running on a cloud platform, deleting its virtual machine.
