### ISSUE TITLE
Job not running on scheduled time - Kubernetes CronJob

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubernetes#117856]
### What happened?

```
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
  name: productsetl
  namespace: default
spec:
  schedule: "10 15 * * 1"
  successfulJobsHistoryLimit: 3
  suspend: false
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          dnsPolicy: Default
          hostNetwork: true
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          imagePullSecrets:
            - name: aws-ecr-registry
          containers:
            - name: productsetl
              image: <AWS Account#>.dkr.ecr.<Region>.amazonaws.com/productsetl:latest
              imagePullPolicy: IfNotPresent
              resources: {}
              securityContext:
                capabilities: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              env:
                - name: DOTNET_ENVIRONMENT
                  value: "Production"
              volumeMounts:
                - name: aws-credentials
                  mountPath: /app/appsettings.aws.json
                  subPath: appsettings.aws.json
                  readOnly: true
                - name: appsettings-production
                  mountPath: /app/appsettings.Production.json
                  subPath: appsettings.Production.json
                  readOnly: true
          volumes:
            - name: aws-credentials
              secret:
                secretName: aws-credentials
                items:
                  - key: appsettings.aws.json
                    path: appsettings.aws.json
            - name: appsettings-production
              configMap:
                name: appsettings-production
```
```
Name:                          productsetl
Namespace:                     default
Labels:                        <none>
Annotations:                   <none>
Schedule:                      23 15 * * 1
Concurrency Policy:            Allow
Suspend:                       False
Successful Job History Limit:  3
Failed Job History Limit:      1
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:  <none>
  Containers:
   productsetl:
    Image:      <AWS Account#>.dkr.ecr.<region>.amazonaws.com/productsetl:latest
    Port:       <none>
    Host Port:  <none>
    Environment:
      DOTNET_ENVIRONMENT:  Production
    Mounts:
      /app/appsettings.Production.json from appsettings-production (ro,path="appsettings.Production.json")
      /app/appsettings.Staging.json from appsettings-staging (ro,path="appsettings.Staging.json")
      /app/appsettings.aws.json from aws-credentials (ro,path="appsettings.aws.json")
  Volumes:
   aws-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  aws-credentials
    Optional:    false
   appsettings-staging:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      appsettings-staging
    Optional:  false
   appsettings-production:
    Type:            ConfigMap (a volume populated by a ConfigMap)
    Name:            appsettings-production
    Optional:        false
Last Schedule Time:  <unset>
Active Jobs:         <none>
Events:              <none>
```
The cronjob is not scheduled. No pod is run.

### What did you expect to happen?

Cronjob runs as scheduled.

### How can we reproduce it (as minimally and precisely as possible)?

manifest provided.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-25T19:00:00Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.2-eks-a59e1f0", GitCommit:"8b68f4b95d7121d039ceebd30870e48acc7772e4", GitTreeState:"clean", BuildDate:"2023-03-09T19:59:45Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar

$ uname -a
Linux khteh-p15v-3i 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
