### ISSUE TITLE
Resource limits are at the pod level, not at the container level

### ISSUE THREAD

**Issue by kong62** [kubernetes/kubernetes#118004]
### What would you like to be added?

Because setting resource limits at the container level is tedious, and it's hard to know how much you should set。

### Why is this needed?

```
containers:
- name: contianersA
  resources: {}
- name: contianersB
  resources: {}
- name: contianersC
  resources: {}
...
initContainers:
- name: contianersa
  resources: {}
- name: contianersb
  resources: {}
- name: contianersb
  resources: {}
...
```

change to:
```
kind: Pod
spec:
  resources: {}
  containers:
  - name: contianersA
  - name: contianersB
  - name: contianersC
  ...
  initContainers:
  - name: contianersa
  - name: contianersb
  - name: contianersb
 ```
