### ISSUE TITLE
The field spec.jobTemplate.spec.completions is not effect in CronJob

### ISSUE THREAD

**Issue by yynespoon** [kubernetes/kubernetes#118026]
### What happened?

I wanna run a job  per 1 minue for 3 times, the yaml like this

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: print
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completionMode: Indexed
      completions: 3
      template:
        spec: 
          restartPolicy: Never
          containers:
            - name: busybox
              image: busybox
              command: ["/bin/sh", "-c", "echo 'hello world'"]
```

but after 3 times, the job create pod continuely to execution

### What did you expect to happen?

the job will stop after 3 times

### How can we reproduce it (as minimally and precisely as possible)?

kubectl apply -f 

### Kubernetes version

<details>

```
version v1.24.0

print-28070106-0-wk6lx   0/1     Completed           0              2m39s
print-28070106-1-ljjhl   0/1     Completed           0              2m19s
print-28070106-2-hpqjb   0/1     Completed           0              118s
print-28070107-0-kmxr6   0/1     Completed           0              99s
print-28070107-1-jjhwb   0/1     Completed           0              95s
print-28070107-2-pk5f7   0/1     Completed           0              90s
print-28070108-0-4txnw   0/1     Completed           0              39s
print-28070108-1-dvcln   0/1     Completed           0              20s
print-28070108-2-2l49l   0/1     ContainerCreating   0              1s

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```
Mac OS Monterey 12.0.1
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
