### ISSUE TITLE
Updating the nodeAffinity of gated pods having nil affinity is not allowed

### ISSUE THREAD

**Issue by aleskandro** [kubernetes/kubernetes#118052]
### What happened?

When a gated pod is created with nil affinity and a user/controller tries to update its nodeAffinity, the validation fails.

### What did you expect to happen?

The pod gets updated with the new affinity as per rules in [KEP-3838](https://github.com/kubernetes/enhancements/commit/ac65b5853a9a5b8fb77a8c3069c07780057a4c9e)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a pod as in the following using `kubectl create`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  generateName: example-no-affinity-
spec:
  schedulingGate:
    - name: "example-gate" # just to ignore any other component that should add a scheduling gate
  containers:
    - name: example-container
      image: 'quay.io/openshifttest/hello-openshift:1.2.0'
```
2. Try to update the pod as with:
```shell
 kubectl patch pod example-no-affinity-hz4lz -p '{"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"expr","operator":"In","values":["value"]}]}]}}}}}'

```

### Kubernetes version

<details>

```console
Kubernetes Version: v1.27.1
```

</details>

### Cloud provider

<details>
Tested on kind and OpenShift
</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
