### ISSUE TITLE
First protocol in port list is used by feature MixedProtocolLBService

### ISSUE THREAD

**Issue by uportalis** [kubernetes/kubernetes#118107]
### What happened?

Using Kubernetes 1.24.11 (GKE).

If I create this service, UDP is not routed to the pod:
```
apiVersion: v1
 kind: Service
 metadata:
   name: lb-mytool
   annotations:
     networking.gke.io/load-balancer-type: "Internal"
 spec:
   type: LoadBalancer
   selector:
     name: mytool
   ports:
     - name: tcp
       port: 8080
       targetPort: 8080
       protocol: TCP
     - name: udp
       port: 4108
       targetPort: 4108
       protocol: UDP
```

If I switch the list entries, UDP is routed (and I'm not sure TCP is routed):
```
apiVersion: v1
 kind: Service
 metadata:
   name: lb-mytool
   annotations:
     networking.gke.io/load-balancer-type: "Internal"
 spec:
   type: LoadBalancer
   selector:
     name: mytool
   ports:
     - name: udp
       port: 4108
       targetPort: 4108
       protocol: UDP
     - name: tcp
       port: 8080
       targetPort: 8080
       protocol: TCP
```

It looks like the protocol of the first port in the list is considered.

### What did you expect to happen?

Packets on both UDP and TCP ports should be routed to the pod.

### How can we reproduce it (as minimally and precisely as possible)?

See above examples.

### Kubernetes version

Kubernetes 1.24.11

### Cloud provider

Google Cloud (GKE)

### Container runtime (CRI) and version (if applicable)

containerd
