### ISSUE TITLE
`kubectl apply --server-side --dry-run=server` can duplicate field in an atomic list

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#118293]
Apparently, the bug happens in 1.26.3 but not in 1.27.1 so maybe it's been fixed somewhere.

Here are the steps to reproduce:
```
cat > testhpa.yaml <<EOF
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-hpa
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - external:
      metric:
        name: foo
      target:
        averageValue: "10"
        type: AverageValue
    type: External
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-depl
EOF

kubectl apply --server-side=true -f testhpa.yaml
kubectl apply --dry-run=server --server-side=true -o yaml -f testhpa.yaml
```

Note that the metrics list is atomic, so the list should be entirely replaced every-time, not merged/appended.
https://github.com/kubernetes/kubernetes/blob/v1.27.2/staging/src/k8s.io/api/autoscaling/v2/types.go#L67-L77

/wg api-expression
/triage accepted
/priority important-soon
