### ISSUE TITLE
cronjob error - Missing annotations

### ISSUE THREAD

**Issue by rshiva777** [kubernetes/kubernetes#118215]
### What happened?

I am trying to apply a cronjob on kubernetes cluster, but the apply is getting failed with an error

### What did you expect to happen?

cronjob should be applied successfully onto the cluster

### How can we reproduce it (as minimally and precisely as possible)?

Try to apply the below cronjob yaml on the cluster

```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: elasticsearch-curator
    chart: elasticsearch-curator-5.8.5-gks.1
    heritage: Helm
    release: elasticsearch-curator
  name: elasticsearch-curator
  namespace: efk-system-logging
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch-curator
        release: elasticsearch-curator
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: elasticsearch-curator
            release: elasticsearch-curator
        spec:
          containers:
          - args:
            - --config
            - /etc/es-curator/config.yml
            - /etc/es-curator/action_file.yml
            command:
            - /usr/local/bin/curator
            image: curator:5.8.5
            imagePullPolicy: IfNotPresent
            name: elasticsearch-curator
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/es-curator
              name: config-volume
            - mountPath: /etc/certs
              name: es-certs
              readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsUser: 16
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: elasticsearch-curator-config
            name: config-volume
          - name: es-certs
            secret:
              defaultMode: 420
              secretName: elasticsearch-master-certs
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
```

When i try to apply, getting the below error

`Error from server (InternalError): error when creating "curator.yaml": Internal error occurred: add operation does not apply: doc is missing path: "/spec/jobtemplate/spec/template/metadata/annotations": missing value`

As it is showing the annotation is missing, i tried to add the annotations on the cronjob.yaml file

```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: elasticsearch-curator
    chart: elasticsearch-curator-5.8.5-gks.1
    heritage: Helm
    release: elasticsearch-curator
  name: elasticsearch-curator
  namespace: efk-system-logging
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch-curator
        release: elasticsearch-curator
      annotations:
        testanno: test
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: elasticsearch-curator
            release: elasticsearch-curator
          **annotations:
            testanno: test**
        spec:
          containers:
          - args:
            - --config
            - /etc/es-curator/config.yml
            - /etc/es-curator/action_file.yml
            command:
            - /usr/local/bin/curator
            image: curator:5.8.5
            imagePullPolicy: IfNotPresent
            name: elasticsearch-curator
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/es-curator
              name: config-volume
            - mountPath: /etc/certs
              name: es-certs
              readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsUser: 16
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: elasticsearch-curator-config
            name: config-volume
          - name: es-certs
            secret:
              defaultMode: 420
              secretName: elasticsearch-master-certs
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
```

Even then no luck, getting the same error

`Error from server (InternalError): error when creating "cronjob.yaml": Internal error occurred: add operation does not apply: doc is missing path: "/spec/jobtemplate/spec/template/metadata/annotations": missing value`

### Anything else we need to know?

NA

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here

root@test:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+vmware.2", GitCommit:"d625665700d901401d7504761cf473dd8adfc7b3", GitTreeState:"clean", BuildDate:"2022-07-18T23:09:26Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+vmware.2", GitCommit:"d625665700d901401d7504761cf473dd8adfc7b3", GitTreeState:"clean", BuildDate:"2022-07-18T23:04:08Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}


```

</details>

### Cloud provider

<details>
VMware Tanzu
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
NAME="VMware Photon OS"
VERSION="3.0"
ID=photon
VERSION_ID=3.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"


$ uname -a
# paste output here
4.19.247-7.ph3


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kannon92** [comment]
triage/needs-information

**Comment by rshiva777** [comment]
@kannon92 Thanks for the quick response

I am able to apply the cronjob on one cluster without the annotations.

But on a different cluster with same kubernetes / kubectl / os version, i am getting the error i mentioned above 

I tried to compare both the cluster but i dont see any difference, not sure where it is getting blocked up. Hence as a work around i tried to add the annotations as shown in the error, even after applying annotations i am getting the same error

`Error from server (InternalError): error when creating "cronjob.yaml": Internal error occurred: add operation does not apply: doc is missing path: "/spec/jobtemplate/spec/template/metadata/annotations": missing value`

**Comment by kannon92** [comment]
So are you saying that you apply that cronjob and then add annotations separately?

**Comment by rshiva777** [comment]
@kannon92 ,

Please find the below steps that i followed

1. Try to deploy the cronjob without annotations

```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: elasticsearch-curator
    chart: elasticsearch-curator-5.8.5-gks.1
    heritage: Helm
    release: elasticsearch-curator
  name: elasticsearch-curator
  namespace: efk-system-logging
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch-curator
        release: elasticsearch-curator
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: elasticsearch-curator
            release: elasticsearch-curator
        spec:
          containers:
          - args:
            - --config
            - /etc/es-curator/config.yml
            - /etc/es-curator/action_file.yml
            command:
            - /usr/local/bin/curator
            image: curator:5.8.5
            imagePullPolicy: IfNotPresent
            name: elasticsearch-curator
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/es-curator
              name: config-volume
            - mountPath: /etc/certs
              name: es-certs
              readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsUser: 16
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: elasticsearch-curator-config
            name: config-volume
          - name: es-certs
            secret:
              defaultMode: 420
              secretName: elasticsearch-master-certs
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
```

When i try to apply, getting the below error

`Error from server (InternalError): error when creating "curator.yaml": Internal error occurred: add operation does not apply: doc is missing path: "/spec/jobtemplate/spec/template/metadata/annotations": missing value`


2. As it is showing the annotation missing error i tried to add annotations to the cronjob.yaml file

```
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: elasticsearch-curator
    chart: elasticsearch-curator-5.8.5-gks.1
    heritage: Helm
    release: elasticsearch-curator
  name: elasticsearch-curator
  namespace: efk-system-logging
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch-curator
        release: elasticsearch-curator
      annotations:
        testanno: test
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: elasticsearch-curator
            release: elasticsearch-curator
          **annotations:
            testanno: test**
        spec:
          containers:
          - args:
            - --config
            - /etc/es-curator/config.yml
            - /etc/es-curator/action_file.yml
            command:
            - /usr/local/bin/curator
            image: curator:5.8.5
            imagePullPolicy: IfNotPresent
            name: elasticsearch-curator
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/es-curator
              name: config-volume
            - mountPath: /etc/certs
              name: es-certs
              readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext:
            runAsUser: 16
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: elasticsearch-curator-config
            name: config-volume
          - name: es-certs
            secret:
              defaultMode: 420
              secretName: elasticsearch-master-certs
  schedule: '*/5 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
```
Even after adding annotations to the cronjob.yaml When i try to apply, getting the same below error

`Error from server (InternalError): error when creating "curator.yaml": Internal error occurred: add operation does not apply: doc is missing path: "/spec/jobtemplate/spec/template/metadata/annotations": missing value`
