### ISSUE TITLE
Support a list of AppProtocols

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes/kubernetes#118407]
The Kubernetes Service API allow us to specify an Application Protocol for each Service port. This is used as a hint for implementations to offer richer behavior for protocols that they understand.

According to the [docs](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol) one of the valid values can be `Implementation-defined prefixed names such as mycompany.com/my-custom-protocol`.

There are cases where different implementations installed in the same cluster and different behaviors may be needed for the same ports.

Starting a discussion to gather thoughts, ideas and use-cases about the need for multiple appProtocols support for the same port.

**Comment by dprotaso** [comment]
Knative OSS and Cloud Run support the same portable API. It has a restrictions to listen only on one port since we need to capture request metrics for scaling and we also enforce request concurrency for each instance.

We had a TensorFlow Service user which wanted to bring that workload to Knative in order to get elastic autoscaling and scale to zero etc. but they wanted to service both GRPC and HTTP. This could be accomplished via multiplexing on a single port but there's no mechanic to signal to ingress providers that protocol a K8s Service supports.

Note there are alternative solutions to model serving built on top of Knative - https://kserve.github.io/ so I don't view this as a random request.

Also an alternative mechanic (to which I have no preference) would be to relax the validation of a list of container ports to support unique combinations of (port, protocol, appProtocol) - similar to how mixed protocol LBs was supported. https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1435-mixed-protocol-lb#proposal

**Comment by arkodg** [comment]
Outlining some use cases
* Websockets over HTTP2 - https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#websocket-over-http-2-or-http-3-hops
* gRPC and HTTP/1.1 on the same port - this is something I think etcd supports https://etcd.io/docs/v3.5/dev-guide/api_grpc_gateway/

**Comment by howardjohn** [comment]
A use case not mentioned IMO is not even the app supporting different protocols exactly, but above vendor specific tweaks to the protocol. For example, gRPC is HTTP2 (more or less).

I may have 2 things reading service, one that does special grpc things, and one that doesn't even know what 'grpc' is.

I may want to declare `appProtocol: grpc,http2` to allow both of those to behave properly

**Comment by LiorLieberman** [comment]
@howardjohn Thats more or less the use case mentioned in the description, no? 

> There are cases where different implementations installed in the same cluster and different behaviors may be needed for the same ports.

**Comment by Ingvord** [comment]
I could think of `tango://` which is a Tango-Controls protocol (open source framework for building system controls and data acquisition systems of any scale), simply CORBA under the hood though

**Comment by dprotaso** [comment]
FWIW it may be simpler to relax some verification and allow multiple entries with distinct appProtocol instead of switching to a list

eg.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      appProtocol: kubernetes.io/ws
      port: 80
      targetPort: 9376
    - protocol: TCP
      appProtocol: kubernetes.io/h2c
      port: 80
      targetPort: 9376
```

**Comment by dprotaso** [comment]
Though the above _wouldn't_ address different protocols with different transports (eg. grpc/h2c vs grpc/http2)

**Comment by thockin** [comment]
Too many things iterate the set of ports and expect the tuple of (port+protocol) t0 be unique.  We can't break that any worse than it is already.

**Comment by uablrek** [comment]
/kind feature

Any progress on this?

**Comment by kahirokunn** [comment]
Bump up 👀

**Comment by mrueg** [comment]
Came across this, while investigating Application-Layer Protocol Negotiation (ALPN) support.

Maybe it would be better to have a more extensible structure like this

```
kind: Service
apiVersion: v1
metadata:
  name: service-example
spec:
  ports:
    - name: https
      port: 443
      applicationHint:
          - protocol: https
            alpn: h3
          - protocol: kubernetes.io/ws 
```

and deprecate the appProtocol field?
