### ISSUE TITLE
Testing: ./consume-cpu/consume-cpu binary in resource-consumer tool didn't consume the specified millicores

### ISSUE THREAD

**Issue by alyssa1303** [kubernetes/kubernetes#118415]
### What happened?

I tried to use resource-consumer tool to generate enough workload on my nodes to crash them (either generating a NodeNotReady or SystemOOM event). However, when I used ./consume-cpu/consume-cpu binary in an Deployment with resoure-consumer image and told it to consume a specific amount of millicores, it never consumed that amount of cpu but always lower than that. 

### What did you expect to happen?

The ./consume-cpu/consume-cpu should consume the exact amount that I specified for the argument --millicores=<cpu usage>

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster with 3 nodes, each has 2 vCPU and 7GiB of memory, so total capacity for all nodes is 6 vCPU and 21 GiB of memory. Run the below deployment in the cluster: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-consumer
  namespace: default
spec:
  replicas: 12
  selector:
    matchLabels:
      app: resource-consumer
  template:
    metadata:
      labels:
        app: resource-consumer
    spec:
      containers:
      - name: resource-consumer
        image: registry.k8s.io/e2e-test-images/resource-consumer:1.13
        command:
          - ./consume-cpu/consume-cpu
        args:
          - --duration-sec=3600
          - --millicores=500
        resources:
          requests:
            cpu: 10m
```
This should be able to consume all 6 vCPU of the nodes. Wait for 30 seconds or so then run `k top pods -kube-system` to check the resource usage. Also, run `k describe nodes` to check for events to see if nodes were crashed or not. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"08d3594304660f86cfbd17bbb862041b4b75fe6c", GitTreeState:"clean", BuildDate:"2023-02-08T17:22:59Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure Kubernetes Services
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
