### ISSUE TITLE
Failed to mount the hostPath /proc/net/

### ISSUE THREAD

**Issue by maxin93** [kubernetes/kubernetes#118465]
### What happened?

I want to deploy a pod in my cluster to monitor NIC information on nodes. I mount `/proc/net/` of the host directory to my pod in hostPath mode.
However, when I enter the container, I find that the owner of the mount point is incorrect, and the content in the corresponding directory is not the content of `/proc/net/dev` on the host, but the content of `/app/proc/net/dev` in the container.
What's even more amazing is that when I remove the "/" at the end of the host directory (`/proc/net`) and go back to the container, the directory and content are correct.
I don't know if this is a problem of k8s or runc.

Can anyone helps? Thanks a lot.

### What did you expect to happen?

The content of `/app/proc/net/dev` in the container is the same as the content of `/proc/net/dev` on the host.

### How can we reproduce it (as minimally and precisely as possible)?

1.Start up a local k8s cluster with Kubernetes v1.25.3 by hack/local-up-cluster.sh;

2.Apply a Pod with busybox with hotsPath `/proc/net/` to `/app/proc/net/` of container;
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox
    image: registry.k8s.io/e2e-test-images/busybox:1.29-2
    command: ["/bin/sh","-c","sleep 3600;"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /app/proc/net
      name: net
  volumes:
  - hostPath:
      path: /proc/net/
      type: ""
    name: net
  securityContext:
    runAsGroup: 2000
    runAsUser: 3001
```
3.Run the Kubectl exec command to access the busybox container and check whether the content of `/app/proc/net/dev` is the same as that of `/proc/net/dev` on the host;
![image](https://github.com/opencontainers/runc/assets/46313756/50abdc2f-ccec-4e18-a20d-91f455b80323)

4.When I change the hotsPath from `/proc/net/` to `/proc/net`, it works as what I want.
![image](https://github.com/opencontainers/runc/assets/46313756/8a317c4b-f5b3-4b1f-9971-23b52f1e908d)

### Kubernetes version

v1.25.3

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
