### ISSUE TITLE
Repeated server side apply creates additional revisions

### ISSUE THREAD

**Issue by shawkins** [kubernetes/kubernetes#118519]
### What happened?

A configmap using string data:

```
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "example"
stringData:
  foo: "bar"
type: "Opaque"
```

Each time it is applied: "kubectl apply -f secret.yml --server-side"

Will create a new resourceVersion and an updated managedFields time, but otherwise no changes.

I observed similar behavior with Ingress resources as well.

### What did you expect to happen?

When there are no real modifications, no new revision should be created.

### How can we reproduce it (as minimally and precisely as possible)?

Run

```
kubectl apply --server-side -f - <<EOF
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "example"
stringData:
  foo: "bar"
type: "Opaque"
EOF
```

twice and confirm the resourceVersion changes

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"09f825e2ac8ddedf8bbc6bc82ffc5520560788a0", GitTreeState:"clean", BuildDate:"2022-04-29T17:13:31Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A - just minikube
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/sig api-machinery 

It seems to be same as https://github.com/kubernetes/kubernetes/issues/96841#issuecomment-747837808.

> After reading the comments from https://github.com/kubernetes/kubernetes/issues/89938#issuecomment-656206971 , it seems to be not expected to update secrets using `kubectl apply` since the feature discussions. 
> 
> As I tried, apply with same data fields will not change the resource version. apply with same StringData would change the resource version as the conversion from v1 secret to core secret only happened in server side later.
> 
> > apelisse commented on 9 Jul • 
> > From #22059 (comment), a good prediction from Brian ;-):
> > 
> > I definitely would not want to do this anywhere else, since it would break kubectl apply and probably other things. However, users shouldn't use kubectl apply on secrets, so that reason isn't relevant in this case.
> > 
> > I still have no idea how to fix that.
> 
> 
> **Suggested Workaround/Solution**
> Do not use kubectl apply to edit secrets, use kubectl edit or kubectl replace.
> 
> Suggestions from https://github.com/kubernetes/kubernetes/issues/89938#issue-596195483

**Comment by jiahuif** [comment]
/assign @pacoxu 
Thank you.
/triage accepted

**Comment by sftim** [comment]
As well as an implementation fix, we might want to document this behavior on k/website _main_, and then remove that detail for the v1.28 docs branch.

**Comment by shawkins** [comment]
In addition to see the same behavior with Ingress, a related issue can be seen with the repeated application of the StatefulSet from https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components when the minReadySeconds feature gate is not enabled - on subsequent applications you'll get an error about a spec modification, even though from a user perspective no changes have been made.

**Comment by shawkins** [comment]
The same issue, additional revisions, with Ingress was caused by the cr having spec rule with path specified as an empty string.  This is likely something that fabric8's default serialization should account for.

**Comment by shawkins** [comment]
Another one like the StatefulSet issue - a service with a port number may be modifed by a json patch to include a port name. Subsequently attempting a server side apply with just the port number will fail with a 422 "cannot set both port name & port number".

**Comment by shawkins** [comment]
Just to have it captured, the similar issue with Ingress is:

Create an ingress with server side apply:
```
kubectl apply --server-side -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  defaultBackend:
    service:
      name: "example-service"
      port:
        number: 8080
  rules:
  - host: "example.com"
    http:
      paths:
      - backend:
          service:
            name: "example-service"
            port:
              number: 8080
        path: ""
        pathType: "ImplementationSpecific"
EOF
```
Then run the server side apply again and confirm that the revision changed but nothing in the spec, nor metadata beyond a timestamp in the managed fields.  It seems to be specifying the path as an empty string that is problematic as it's removed in the stored resource.
