### ISSUE TITLE
DaemonSet does not recreate failed pods when they have deletionTimestamp

### ISSUE THREAD

**Issue by mimowo** [kubernetes/kubernetes#118587]
/sig apps

When a terminal pod (Failed or Succeeded) has a deletionTimestamp it is ignored by DaemonSet and not recreated, because of this check: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L822-L824.

It was observed when working on what was isolated to Kubelet issue, that Kubelet would not force-delete pods in some scenarios: https://github.com/kubernetes/kubernetes/issues/118472. 

The below reproduction steps use the 1.27.2 version with affected kubelet by the bug:

1. create kind cluster using 1.27.2 with config in `kind-config.yaml`

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
```

```sh
kind create cluster --config kind-config.yaml --image kindest/node:v1.27.2
```

2. create daemonset with the following spec:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: issue-daemonset
 namespace: default
spec:
 selector:
   matchLabels:
     name: issue-label
 template:
   metadata:
     labels:
       name: issue-label
   spec:
     os:
       name: "windows"
     containers:
     - name: ubuntu
       image:  gcr.io/google-containers/ubuntu:14.04
       command: ["/bin/sleep"]
       args: ["infinity"]
```
```sh
kubectl create -f ds.yaml
```
Observe the pod is created but marked Failed as non-admissible:
```sh 
kubectl get pods -oyaml
``` 
```sh
  status:
    message: 'Pod was rejected: Failed to admit pod as the OS field doesn''t match
      node OS'
    phase: Failed
    reason: PodOSNotSupported
    startTime: "2023-06-09T09:04:54Z"
```
3. Stop kubelet on the worker node

```sh
docker exec kind-worker systemctl stop kubelet
```
After a while observe that a replacement pod to be created by DS
```sh
kubectl get pods
```
```sh
NAME                    READY   STATUS    RESTARTS   AGE
issue-daemonset-tvrfr   0/1     Pending   0          10s
```
Observe that a replacement pod is created, but remains Pending (as the kubelet is down)

4. Delete the pending pod
```sh
kubectl delete pods/issue-daemonset-tvrfr
```
Observe that the delete hangs as Kubelet is stopped, and the pod is pending.

5. Start Kubelet again 
```sh
docker exec kind-worker systemctl start kubelet
```

Observe, that the pod now transitions to the `Failed` phase, but the delete hangs.

**Issue**: DaemonSet does not recreate a failed pod, because it has the `deletionTimestamp`. 

Note: the behavior is tricky to reproduce on a healthy system, because then the pod is typically force-deleted by Kubelet soon after transitioning to `Failed` phase.

However, it was also suggested as a potential DS issue (see [comment](https://github.com/kubernetes/kubernetes/issues/118472#issuecomment-1579025614)), so opening the ticket to track the discussion.
