### ISSUE TITLE
blank window when updating ClusterRole with AggregationRule

### ISSUE THREAD

**Issue by armstrongli** [kubernetes/kubernetes#118648]
### What happened?

the rules of ClusterRole is reset as null when applying ClusterRule with AggregationRule. it results in permission blank window and bring unexpected Unauthorized errrors.

ClusterRole with aggregation rule:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      aggregate-to-admin: "true"
```

ClusterRole to aggregate:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    aggregate-to-admin: "true"
  name: admin-etcd
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  verbs:
  - '*'
```

when applying the cluster role `admin` for a 2nd time, the rules part is reset as `null`. requests get 403 before kube-controller-manager aggregates rules into the rules of admin ClusterRole

### What did you expect to happen?

the existing rules are not impacted when there are no updates on the aggregation rule.

### How can we reproduce it (as minimally and precisely as possible)?

1. apply the following clusterroles
2. watch the admin clusterrole with `kubectl get clusterrole admin -o yaml -w`
3. apply the follow clusterroles for a 2nd time
4. the rules of admin is reset to `null` for a while and updated again with aggregated rules.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      aggregate-to-admin: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    aggregate-to-admin: "true"
  name: admin-etcd
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  verbs:
  - '*'
```

### Kubernetes version

all versions <=1.28

### Cloud provider

none

### OS version

mac 13.4 (22F66)

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
