### ISSUE TITLE
How to know that the cpu management policy is in effect?

### ISSUE THREAD

**Issue by Zruto** [kubernetes/kubernetes#118657]
I modified the cpu management policy according to the official document [Control CPU Management Policies on the Node](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/), but after experiments, I found that the execution time of the task has not been shortened but slightly longer. How do I know that the configuration I modified has taken effect?

I added the following configuration to /var/lib/kubelet/config.yml of each working node,the master node is not modified because it is not scheduled,
```
systemReserved:
  cpu: "4"
  memory: "500m"
kubeReserved:
  cpu: "4"
  memory: "500m"
cpuManagerPolicy: "static"
cpuManagerPolicyOptions:
  full-pcpus-only: "true"
```
deleted cpu_manager_state,restarted the kubelet and started executing tasks, and found that the content of the cpu_manager_state of one of the nodes is
```
{"policyName":"static","defaultCpuSet":"0-7,16-55","entries":{"b0e4cb0d-47b0-4ed3-b707-4baf7eb0875a":{"nf-97cb00a04fbdc660b8193d6093288930":"8-15,56-63"}},"checksum":2824956018}
```
Does this mean that the configuration I modified has taken effect? If it works, why does it take longer to run? Is it related to my k8s version, my k8s version is v1.23.

**Comment by ffromani** [comment]
> I modified the cpu management policy according to the official document [Control CPU Management Policies on the Node](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/), but after experiments, I found that the execution time of the task has not been shortened but slightly longer. How do I know that the configuration I modified has taken effect?

Hi, in kubernetes >= 1.23 you can use the kubelet-local [podresources API endpoint and check if your containers got exclusive resources assigned](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#monitoring-device-plugin-resources).

In kubernetes >= 1.26 you can also observe the prometheus metric `cpu_manager_pinning_requests_total`

In any case, checking the `cpu_manager_state` is discouraged and should be avoided, even if you just read the data.

> I added the following configuration to /var/lib/kubelet/config.yml of each working node,the master node is not modified because it is not scheduled,
> 
> ```
> systemReserved:
>   cpu: "4"
>   memory: "500m"
> kubeReserved:
>   cpu: "4"
>   memory: "500m"
> cpuManagerPolicy: "static"
> cpuManagerPolicyOptions:
>   full-pcpus-only: "true"
> ```

you may want to use the `reserved-cpus` option and/or corresponding kubelet value.



> 
> deleted cpu_manager_state,restarted the kubelet and started executing tasks, and found that the content of the cpu_manager_state of one of the nodes is
> 
> ```
> {"policyName":"static","defaultCpuSet":"0-7,16-55","entries":{"b0e4cb0d-47b0-4ed3-b707-4baf7eb0875a":{"nf-97cb00a04fbdc660b8193d6093288930":"8-15,56-63"}},"checksum":2824956018}
> ```
> 
> Does this mean that the configuration I modified has taken effect?

This seems to suggest the workload got 16 exclusive CPU assigned

> If it works, why does it take longer to run?

There's not enough data to answer here: this depends on the machine config (HW and SW) and on the workload.
We can only say with reasonnable confidence that the CPU pinning _seems_ to have been performed correctly.

**Comment by ffromani** [comment]
/close

@Zruto please feel free to reopen if you're not happy with the answer or if there is more to investigate

**Comment by Zruto** [comment]
I have a question. When I tested static and none, I used the following program and found that the running time of the static strategy was longer than that of none. Is it because my test cases are not CPU-intensive? 4m55s runs on nodes with static strategy, and 3m52s runs on nodes with none strategy.
```
apiVersion: batch/v1
kind: Job
metadata:
  name: my-task-job
spec:
  parallelism: 50
  completions: 50
  template:
    metadata:
      name: my-task-pod
    spec:
      nodeName: dc02-pff-500-aa44-1a35-b076-109c
      containers:
      - name: my-task-container
        image: python:3.9-slim
        command: ["python", "-c"]
        args: ["import time\n\ndef fibonacci(n):\n    return n if n <= 1 else fibonacci(n-1) + fibonacci(n-2)\n\nstart_time = time.time()\nresult = fibonacci(43)\nend_time = time.time()\nprint('Result: ', result)\nprint('Time taken: ', end_time - start_time, ' seconds')\n"]
        resources:
          limits:
            cpu: "1"
            memory: "100Mi"
      restartPolicy: Never
  backoffLimit: 0
  ```
  
![image](https://github.com/kubernetes/kubernetes/assets/46238825/a1baafea-4bd7-4ed7-9791-23b627c5cbb2)

![image](https://github.com/kubernetes/kubernetes/assets/46238825/01a7db69-c753-4e18-a725-4dc858be986a)
