### ISSUE TITLE
warning or decline pod creation with RestartContainer resizePolicy  if the restartPolicy is Never

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#118674]
### What happened?

> Note: If the Pod's restartPolicy is Never, container's resize restart policy must be set to NotRequired for all Containers in the Pod.

https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/

This is already mentioned in the doc, but no warning or decline is shown when it happens.

### What did you expect to happen?

warning or decline 

/sig node

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-5
  namespace: qos-example
spec:
  restartPolicy: Never
  containers:
  - name: qos-demo-ctr-5
    image: docker.m.daocloud.io/library/nginx:1.14.2
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: RestartContainer
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
```

### Anything else we need to know?

xref https://github.com/kubernetes/enhancements/issues/1287

### Kubernetes version

1.27

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
