### ISSUE TITLE
podAffinity on statefulset is not scheduling pod to appropriate node with dependency pod label

### ISSUE THREAD

**Issue by michaelsaxbury** [kubernetes/kubernetes#118627]
### What happened?

I have 2 nodes and I want mssql and rabbitmq running on the same node.
I have tolleration in both mssql and rabbitmq statefulsets that match the same taint on both nodes, so mssql can go to either node, it spins up first.
I configured a podAffinity in my rabbitmq statefulset so it will schedule the pod on the same node as mssql:
```
     affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - mssql
              namespaces:
                - cluedin
              topologyKey: kubernetes.io/hostname
```
The label from the rabbitmq podAffinity above, is on my sql pod:
```
  labels:
    app.kubernetes.io/instance: cluedin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mssql
```

### What did you expect to happen?

rabbitmq statefulset should schedule the rabbitmq pod on the same node as mssql, but it is not.

rabbitmq fails to schedule with the following error:
**0/7 nodes are available: 1 node(s) didn't match pod affinity rules, 1 node(s) had untolerated taint {CriticalAddonsOnly: true}, 1 node(s) had untolerated taint {kubernetes.cluedin.com/pool: data-neo}, 1 node(s) had untolerated taint {kubernetes.cluedin.com/pool: processing}, 1 node(s) had volume node affinity conflict, 2 node(s) didn't match Pod's node affinity/selector. preemption: 0/7 nodes are available: 1 No preemption victims found for incoming pod, 6 Preemption is not helpful for scheduling.**

### How can we reproduce it (as minimally and precisely as possible)?

do the above

### Kubernetes version

1.25.6

### Cloud provider

AKS

### OS version

linux

### Install tools

helm

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
