### ISSUE TITLE
Replicaset and Pods not deleted after Deployment has been deleted 

### ISSUE THREAD

**Issue by eyujy** [kubernetes/kubernetes#118753]
**Cluster information:**
Kubernetes version: 1.27.2
Cloud being used: baremetal
Installation method: kubeadm
Host OS: Ubuntu 20.04.4 LTS
CNI and version: calico v3.26.0
CRI and version: containerd v1.6.2

**Dummy NGINX Deployment**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: stacksimplify/kube-nginxapp1:1.0.0
        ports:
        - containerPort: 80
```
      
**Output after deploying**

```
NAME                                              READY   STATUS    RESTARTS   AGE
pod/nginx-deployment-7d94b5f487-7q2hd             1/1     Running   0          8s

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx-deployment             1/1     1            1           8s

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-deployment-7d94b5f487             1         1         1       8s
```

**After i run kubectl delete deploy nginx-deployment**

```
NAME                                              READY   STATUS    RESTARTS   AGE
pod/nginx-deployment-7d94b5f487-7q2hd             1/1     Running   0          5m22s

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-deployment-7d94b5f487             1         1         1       5m23s
```

Even if i run `kubectl delete deploy nginx-deployment --cascade=background`, the replicasets and pods does not get deleted.

How should I proceed with this?

Thank you!

**Comment by killshotrevival** [comment]
Did you changed any labels in pod, manually after creating them with deployment?? That might have cause the breaking of deployment <-> pod monitoring link???

**Comment by eyujy** [comment]
> Did you changed any labels in pod, manually after creating them with deployment?? That might have cause the breaking of deployment <-> pod monitoring link???

Hi @killshotrevival,

I did not change any labels manually after creating them with deployment. 

I did a test where i created a new deployment and deleted it after. The pods and rs were not deleted.

**Comment by killshotrevival** [comment]
ohh, noted noted. @eyujy are you able to replicate this behaviour again, like can u please try the same thing with different name, and check if the same behaviour occurs. 🤔

**Comment by eyujy** [comment]
Yes, this behaviour can be replicated from my end @killshotrevival 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  labels:
    app: nginx2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

After deleting

```
NAME                                   READY   STATUS    RESTARTS   AGE
pod/nginx-deployment-cbdccf466-lkmxw   1/1     Running   0          4h49m
pod/nginx-deployment-cbdccf466-vnxnd   1/1     Running   0          4h49m
pod/nginx-deployment-cbdccf466-x9fxh   1/1     Running   0          4h49m
pod/nginx2-6f558c4d44-58xfs            1/1     Running   0          67s
pod/nginx2-6f558c4d44-dk9h6            1/1     Running   0          67s
pod/nginx2-6f558c4d44-rtkdh            1/1     Running   0          67s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-deployment-cbdccf466   3         3         3       4h49m
replicaset.apps/nginx2-6f558c4d44            3         3         3       67s
```
