### ISSUE TITLE
kubectl patch command throws an error without providing any indication when using 'imagePullSecret: - {}'

### ISSUE THREAD

**Issue by arvindh123** [kubernetes/kubernetes#118715]
### What happened?

I'm using HELM to install chart 

During the HELM upgrade I got the following error 

```
failed to create patch: map: map[] does not contain declared merge key: name
```
In order to find root cause problem , I got the YAML file from helm,  with command  ```helm upgrade --dry-run `

Copied part of Deployment to new file `t1.yaml`

Then tried to apply patch to that file where I encountered the same error . I applied the following command:

```bash
$ kubectl patch deployment mainflux-ui -n mf --patch-file ./t1.yaml
```
```error
Error from server: map: map[] does not contain declared merge key: name
```

The contents of `t1.yaml` are as follows:

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainflux-ui
spec:
  selector:
    matchLabels:
      app: mainflux
      component: ui
  template:
    metadata:
      labels:
        app: mainflux
        component: ui
    spec:
      containers:
        - env:
            - name: MF_UI_PORT
              value: "3000"
            - name: MF_UI_MQTT_WS_URL
              value: "ws://localhost/mqtt"
            - name: MF_PROXY_AUTH
              value: "false"
            - name: MF_UI_APP_PREFIX
              value: "ui"
            - name : MF_PROXY_LOGOUT_URL
              value: "/logout"
          image: "mainflux/ui:latest"
          imagePullPolicy: IfNotPresent
          name: ui
          ports:
            - containerPort: 3000
              protocol: TCP
          stdin: true
          tty: true
      imagePullSecrets:
            - {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
```

## When I removed the `imagePullSecrets` section as shown below, the patch command executed successfully:

```
    spec:
      containers:
        - env:
            - name: MF_UI_PORT
              value: "3000"
            - name: MF_UI_MQTT_WS_URL
              value: "ws://localhost/mqtt"
            - name: MF_PROXY_AUTH
              value: "false"
            - name: MF_UI_APP_PREFIX
              value: "ui"
            - name : MF_PROXY_LOGOUT_URL
              value: "/logout"
          image: "mainflux/ui:latest"
          imagePullPolicy: IfNotPresent
          name: ui
          ports:
            - containerPort: 3000
              protocol: TCP
          stdin: true
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
 ```
Output  after removingimagePullSecrets

```
deployment.apps/mainflux-ui patched (no change)
```

### What did you expect to happen?

Expectation is to accept the patch and provide a message stating "no changes" if there are no modifications.
 or
alternatively, The minimum expectation is to display the correct error message indicating the location of the error.

## When I removed the `imagePullSecrets` section as shown below, the patch command executed successfully:

```
    spec:
      containers:
        - env:
            - name: MF_UI_PORT
              value: "3000"
            - name: MF_UI_MQTT_WS_URL
              value: "ws://localhost/mqtt"
            - name: MF_PROXY_AUTH
              value: "false"
            - name: MF_UI_APP_PREFIX
              value: "ui"
            - name : MF_PROXY_LOGOUT_URL
              value: "/logout"
          image: "mainflux/ui:latest"
          imagePullPolicy: IfNotPresent
          name: ui
          ports:
            - containerPort: 3000
              protocol: TCP
          stdin: true
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
 ```
Output  after removingimagePullSecrets

```
deployment.apps/mainflux-ui patched (no change)
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
This issue looks like it is being fixed 
FYI. https://github.com/kubernetes/kubernetes/pull/110147
/sig api-machinery

**Comment by seans3** [comment]
/assign @arvindh123 

Can you verify that this has been addressed ?

**Comment by arvindh123** [comment]
I have create `test.yaml` with following content: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainflux-ui
spec:
  selector:
    matchLabels:
      app: mainflux
      component: ui
  template:
    metadata:
      labels:
        app: mainflux
        component: ui
    spec:
      containers:
        - env:
            - name: MF_UI_PORT
              value: "3000"
            - name: MF_UI_MQTT_WS_URL
              value: "ws://localhost/mqtt"
            - name: MF_PROXY_AUTH
              value: "false"
            - name: MF_UI_APP_PREFIX
              value: "ui"
            - name : MF_PROXY_LOGOUT_URL
              value: "/logout"
          image: "mainflux/ui:latest"
          imagePullPolicy: IfNotPresent
          name: ui
          ports:
            - containerPort: 3000
              protocol: TCP
          stdin: true
          tty: true
      imagePullSecrets:
            - {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
```

**Then ran the command** 
```bash 
kubectl apply -f test.yaml -n test
```
**Received  Output with warning:** 
```log
Warning: spec.template.spec.imagePullSecrets[0].name: invalid empty name ""
deployment.apps/mainflux-ui created
````

**Then again ran the same command** 
```bash 
kubectl apply -f test.yaml -n test
```
**Received  Output with  error:**
```log
warning: error calculating patch from openapi v3 spec: map: map[] does not contain declared merge key: name
warning: error calculating patch from openapi spec: map: map[] does not contain declared merge key: name
error: error when applying patch:

to:
Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"
Name: "mainflux-ui", Namespace: "test"
for: "test.yaml": error when patching "test.yaml": creating patch with:
original:
{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"mainflux-ui","namespace":"test"},"spec":{"selector":{"matchLabels":{"app":"mainflux","component":"ui"}},"template":{"metadata":{"labels":{"app":"mainflux","component":"ui"}},"spec":{"containers":[{"env":[{"name":"MF_UI_PORT","value":"3000"},{"name":"MF_UI_MQTT_WS_URL","value":"ws://localhost/mqtt"},{"name":"MF_PROXY_AUTH","value":"false"},{"name":"MF_UI_APP_PREFIX","value":"ui"},{"name":"MF_PROXY_LOGOUT_URL","value":"/logout"}],"image":"mainflux/ui:latest","imagePullPolicy":"IfNotPresent","name":"ui","ports":[{"containerPort":3000,"protocol":"TCP"}],"stdin":true,"tty":true}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{}],"restartPolicy":"Always"}}}}

modified:
{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"name\":\"mainflux-ui\",\"namespace\":\"test\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"mainflux\",\"component\":\"ui\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"mainflux\",\"component\":\"ui\"}},\"spec\":{\"containers\":[{\"env\":[{\"name\":\"MF_UI_PORT\",\"value\":\"3000\"},{\"name\":\"MF_UI_MQTT_WS_URL\",\"value\":\"ws://localhost/mqtt\"},{\"name\":\"MF_PROXY_AUTH\",\"value\":\"false\"},{\"name\":\"MF_UI_APP_PREFIX\",\"value\":\"ui\"},{\"name\":\"MF_PROXY_LOGOUT_URL\",\"value\":\"/logout\"}],\"image\":\"mainflux/ui:latest\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"ui\",\"ports\":[{\"containerPort\":3000,\"protocol\":\"TCP\"}],\"stdin\":true,\"tty\":true}],\"dnsPolicy\":\"ClusterFirst\",\"imagePullSecrets\":[{}],\"restartPolicy\":\"Always\"}}}}\n"},"name":"mainflux-ui","namespace":"test"},"spec":{"selector":{"matchLabels":{"app":"mainflux","component":"ui"}},"template":{"metadata":{"labels":{"app":"mainflux","component":"ui"}},"spec":{"containers":[{"env":[{"name":"MF_UI_PORT","value":"3000"},{"name":"MF_UI_MQTT_WS_URL","value":"ws://localhost/mqtt"},{"name":"MF_PROXY_AUTH","value":"false"},{"name":"MF_UI_APP_PREFIX","value":"ui"},{"name":"MF_PROXY_LOGOUT_URL","value":"/logout"}],"image":"mainflux/ui:latest","imagePullPolicy":"IfNotPresent","name":"ui","ports":[{"containerPort":3000,"protocol":"TCP"}],"stdin":true,"tty":true}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{}],"restartPolicy":"Always"}}}}

current:
{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"name\":\"mainflux-ui\",\"namespace\":\"test\"},\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"mainflux\",\"component\":\"ui\"}},\"template\":{\"metadata\":{\"labels\":{\"app\":\"mainflux\",\"component\":\"ui\"}},\"spec\":{\"containers\":[{\"env\":[{\"name\":\"MF_UI_PORT\",\"value\":\"3000\"},{\"name\":\"MF_UI_MQTT_WS_URL\",\"value\":\"ws://localhost/mqtt\"},{\"name\":\"MF_PROXY_AUTH\",\"value\":\"false\"},{\"name\":\"MF_UI_APP_PREFIX\",\"value\":\"ui\"},{\"name\":\"MF_PROXY_LOGOUT_URL\",\"value\":\"/logout\"}],\"image\":\"mainflux/ui:latest\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"ui\",\"ports\":[{\"containerPort\":3000,\"protocol\":\"TCP\"}],\"stdin\":true,\"tty\":true}],\"dnsPolicy\":\"ClusterFirst\",\"imagePullSecrets\":[{}],\"restartPolicy\":\"Always\"}}}}\n"},"creationTimestamp":"2024-08-06T00:29:26Z","generation":1,"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:labels":{".":{},"f:app":{},"f:component":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"ui\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"MF_PROXY_AUTH\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MF_PROXY_LOGOUT_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MF_UI_APP_PREFIX\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MF_UI_MQTT_WS_URL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MF_UI_PORT\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":3000,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:resources":{},"f:stdin":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:tty":{}}},"f:dnsPolicy":{},"f:imagePullSecrets":{".":{},"k:{\"name\":\"\"}":{}},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2024-08-06T00:29:26Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","subresource":"status","time":"2024-08-06T00:29:31Z"}],"name":"mainflux-ui","namespace":"test","resourceVersion":"7831473","uid":"0ab523a4-ae04-4698-bf06-72589ccd890b"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"mainflux","component":"ui"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"mainflux","component":"ui"}},"spec":{"containers":[{"env":[{"name":"MF_UI_PORT","value":"3000"},{"name":"MF_UI_MQTT_WS_URL","value":"ws://localhost/mqtt"},{"name":"MF_PROXY_AUTH","value":"false"},{"name":"MF_UI_APP_PREFIX","value":"ui"},{"name":"MF_PROXY_LOGOUT_URL","value":"/logout"}],"image":"mainflux/ui:latest","imagePullPolicy":"IfNotPresent","name":"ui","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-08-06T00:29:31Z","lastUpdateTime":"2024-08-06T00:29:31Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2024-08-06T00:29:26Z","lastUpdateTime":"2024-08-06T00:29:31Z","message":"ReplicaSet \"mainflux-ui-c847fd99f\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}

for:: map: map[] does not contain declared merge key: name
```
