### ISSUE TITLE
errImageNeverPull error when try to run the pod using the image of the local machines docker

### ISSUE THREAD

**Issue by Amit-limbasiya** [kubernetes/kubernetes#118795]
### What happened?

Pointing out the existing issue looks like mine [here](https://github.com/oracle/docker-images/issues/1154)
I was trying to host my application in the kubernetes and my issue is similar to above issue. However he resolved that issue by uploading the image in the docker hub repo. I don't want to do that and I want to use docker image of my local machine.

When I try to fetch the image from the docker images of the local machine by `imagePullPolicy: Never` and provide the image name from the docker-desktop then i got the error as **ErrImageNeverPull** .

I am using minikube as the node and minikube is running inside the docker.

### How can we reproduce it (as minimally and precisely as possible)?
My source code looks like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jmeterclidemo
  name: jmeterclidemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeterclidemo
  template:
    metadata:
      labels:
        app: jmeterclidemo
    spec:
      containers:
        - image: jmeterclidemo
          name: jmeterclidemo
          imagePullPolicy: Never 
          ports:
            - containerPort: 80
            - containerPort: 443
```
when i do `kubectl apply -f <filename>` and `kubectl get po` it is showing container is not running and facing error ErrImageNeverPull.

I got the logs by `kubectl logs <podname>` it is showing the error like: 
Error from server (BadRequest): container "jmeterclidemo" in pod "jmeterclidemo-7cb9c5d84-j8btq" is waiting to start: ErrImageNeverPull.

### Anything else we need to know?

However I have fetched the image of mssql from my local docker registery the same way.
It's source code looks like(ignoring volumes and env vars and pointing to image):
```
piVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata: 
      name: mssql-deployment
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql-container
        image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
        imagePullPolicy: Never
        ports:
        - containerPort: 1433
```
It is running properly.
The same way when I do for the api it is not running.

### What did you expect to happen?

It should take the image from local registery like other images in the application.

### Kubernetes version

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.26.3

### Cloud provider

No cloud provider used, rather minikube was used.

### OS version

BuildNumber    Caption                                  OSArchitecture  Version
22000               Microsoft Windows 11 Pro     64-bit                10.0.22000
