### ISSUE TITLE
readiness probe is not scheduled as configured periodSeconds

### ISSUE THREAD

**Issue by vkatabat** [kubernetes/kubernetes#118815]
### What happened?

**Below pod yaml file was deployed. From probe logs we see probe is getting scheduled more than once in 30 sec duration of perodSeconds configured for readinessProbe. At times it gets scheduled twice within 5 seconds though 30 sec is configured as periodSeconds**
<code>
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: ready1
spec:
  containers:
  - name: readiness
    image: busybox
    command: ["top"]
    readinessProbe:
      exec:
        command:
        - /tmp/probe.sh
      initialDelaySeconds: 3
      failureThreshold: 1
      successThreshold: 1
      periodSeconds: 30
</code>
      **/tmp/probe.sh was added as executable after doing exec to pod to simulate the issue.**

 

/ # cat /tmp/probe.sh
#!/bin/sh
echo "Probe at `date`" >> /tmp/probe.log
exit 1
/ # tail -f /tmp/probe.log
Probe at Fri Jun 16 07:16:16 UTC 2023
Probe at Fri Jun 16 07:16:35 UTC 2023
Probe at Fri Jun 16 07:17:05 UTC 2023
Probe at Fri Jun 16 07:17:19 UTC 2023
Probe at Fri Jun 16 07:17:35 UTC 2023

### What did you expect to happen?

Expect readinessProbe to be scheduled acurately as periodSeconds. 

### How can we reproduce it (as minimally and precisely as possible)?

Above yaml file can be created in k8s 1.27 with probe content to log output of `date` command.

### Anything else we need to know?

When probe was successful scheduling was accurate. 

### Kubernetes version

<details>

```console
$ kubectl version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"c978334577baba04da0671abbcd788e510503453", GitTreeState:"clean", BuildDate:"2023-06-18T06:28:15Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"c978334577baba04da0671abbcd788e510503453", GitTreeState:"clean", BuildDate:"2023-06-18T06:17:43Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
sudo dmidecode | grep -i -e manufacturer -e product -e vendor
        Vendor: SeaBIOS
        Manufacturer: OpenStack Foundation
        Product Name: OpenStack Nova
        Manufacturer: QEMU
        Manufacturer: QEMU
        Manufacturer: QEMU
        Manufacturer: QEMU

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
 cat /etc/os-release
NAME="SLES"
VERSION="15-SP4"
VERSION_ID="15.4"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP4"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp4"
DOCUMENTATION_URL="https://documentation.suse.com/"

$ uname -a
Linux master-2-test10 5.14.21-150400.24.63-default #1 SMP PREEMPT_DYNAMIC Tue May 2 15:49:04 UTC 2023 (fd0cc4f) x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
/usr/local/bin/containerd --version
containerd github.com/containerd/containerd v1.7.0 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SataQiu** [comment]
FYI: 
https://github.com/kubernetes/kubernetes/blob/ba6d2674ca6b7b4992189bba1516062004f05ed3/pkg/kubelet/prober/prober_manager.go#L283-L288

**Comment by mochizuki875** [comment]
@vkatabat 
Hi,
I try to reproduce it, but it dosen't.
I used this manifest, is it reproduced in your environment using it?
If you see anything odd, please point it out:)

`probe-pod.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: ready1
spec:
  containers:
    - name: readiness
      image: busybox
      command: ["top"]
      readinessProbe:
        exec:
          command:
          - /mnt/probe.sh
        initialDelaySeconds: 3
        failureThreshold: 1
        successThreshold: 1
        periodSeconds: 30
      volumeMounts:
      - name: probe-sh
        mountPath: "/mnt"
        readOnly: false
  volumes:
  - name: probe-sh
    configMap:
      name: probe-sh
      defaultMode: 0777

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: probe-sh
data:
  probe.sh: |
    #!/bin/sh
    echo Probe at $(date) > /tmp/prove.txt
    exit 1
```

Apply this manifest.
```console
$ kubectl apply -f probe-pod.yaml
pod/ready1 created
configmap/probe-sh created
```

After that, probe has failed.
```console
$ kubectl describe po ready1
Name:             ready1
Namespace:        default
...
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  77s                default-scheduler  Successfully assigned default/ready1 to kind-worker
  Normal   Pulling    76s                kubelet            Pulling image "busybox"
  Normal   Pulled     75s                kubelet            Successfully pulled image "busybox" in 1.401711187s (1.401724144s including waiting)
  Normal   Created    75s                kubelet            Created container readiness
  Normal   Started    75s                kubelet            Started container readiness
  Warning  Unhealthy  16s (x3 over 72s)  kubelet            Readiness probe failed:
```

Check the file and only one record has been added.
```console
$ kubectl exec -it ready1 -- /bin/sh
/ # tail /tmp/prove.txt 
Probe at Mon Jun 26 08:40:01 UTC 2023
```

My environment is k8s v1.27.3.
```console
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.3
```

Thanks.
