### ISSUE TITLE
Inconsistency in' securityContext.privileged and allowPrivilegeEscalation behaviors

### ISSUE THREAD

**Issue by arthurghz** [kubernetes/kubernetes#118822]
### What happened?

**What happened:**

When using the following Kubernetes settings:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: privilege_escalation_test
  namespace: default
spec:
  containers:
  - name: centos
    image: arthsouza/privilege_escalation_test
    command: ['sh', '-c', 'sleep 999']
    securityContext:
       privileged: false
       allowPrivilegeEscalation: false
  - name: centos2
    image: arthsouza/privilege_escalation_test
    command: ['sh', '-c', 'sleep 999']
    securityContext:
       privileged: false
```

without specifying `allowPrivilegeEscalation`, it should default to `FALSE` preventing the container from running privileged. However, that is not what happens.

**How to reproduce it (as minimally and precisely as possible):**
### How to reproduce it (as minimally and precisely as possible):

First, use this image > **_`arthsouza/privilege_escalation_test_`**  or create your image based on docker file below . 

```Dockerfile
FROM alpine

ARG USER=user
ENV HOME /home/$USER

# install sudo as root
RUN apk add --update sudo

# add new user
RUN adduser -D $USER \
        && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
        && chmod 0440 /etc/sudoers.d/$USER

USER $USER
```

Then, apply the following Pod configuration in your Kubernetes cluster:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: privilege_escalation_test
  namespace: default
spec:
  containers:
  - name: centos
    image: arthsouza/privilege_escalation_test
    command: ['sh', '-c', 'sleep 999']
    securityContext:
       privileged: false
       allowPrivilegeEscalation: false
  - name: centos2
    image: arthsouza/privilege_escalation_test
    command: ['sh', '-c', 'sleep 999']
    securityContext:
       privileged: false
```

Next, check if the Pod is running:

```bash
kubectl get pods
```

Once the Pod `privilege_escalation_test` is running, enter the `centos` container by using the `kubectl exec` command:

```bash
kubectl exec -it privilege_escalation_test -c centos2 -- /bin/sh
```

Inside the container, try running a `sudo` command, like:

```bash
sudo apk update
```

### Anything else we need to know?

This should not be happening according to this code: https://github.com/kubernetes/kubernetes/blob/9325a57125e8502941d1b0c7379c4bb80a678d5c/pkg/securitycontext/util.go#L181

This issue is critical because it impacts the security context of the Kubernetes environment.

**Anything else we need to know:**

The settings `privileged: false` and `allowPrivilegeEscalation: true` are not behaving as expected according to the Kubernetes documentation and the linked code reference. It seems there may be a bug or a gap in the implementation. This issue is critical because it impacts the security context of the Kubernetes environment.

### What did you expect to happen?

**What you expected to happen:**

If `privileged: false` is set and `allowPrivilegeEscalation` is not provided, it should default to `false`, disallowing privilege escalation within the container.

### How can we reproduce it (as minimally and precisely as possible)?

Here is a Dockerfile to create a container in which the user can use SUDO commands:

```Dockerfile
FROM alpine

ARG USER=user
ENV HOME /home/$USER

# install sudo as root
RUN apk add --update sudo

# add new user
RUN adduser -D $USER \
        && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
        && chmod 0440 /etc/sudoers.d/$USER

USER $USER
```

Also, I created a table for the various behaviors:

| `privileged` value | `allowPrivilegeEscalation` value | Can escalate privileges |
| --- | --- | --- |
| True | Default or True | Yes |
| True | False | Error: Cannot set `allowPrivilegeEscalation` to false and `privileged` to true |
| False | False | No |
| False | Default (null) | Yes |

This should not be happening according to this code: https://github.com/kubernetes/kubernetes/blob/9325a57125e8502941d1b0c7379c4bb80a678d5c/pkg/securitycontext/util.go#L181

### Anything else we need to know?

The settings privileged: false and allowPrivilegeEscalation: true are not behaving as expected according to the Kubernetes documentation and the linked code reference. It seems there may be a bug or a gap in the implementation. This issue is critical because it impacts the security context of the Kubernetes environment.

### Kubernetes version

<details>

```console
Client Version: v1.27.2
Kustomize Version: v5.0.1

```

</details>

### Cloud provider

<details>
Cloud Provider: AWS

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
