### ISSUE TITLE
Kubectl apply svc cannot add UDP protocol ports

### ISSUE THREAD

**Issue by aimuz** [kubernetes/kubernetes#118920]
### What happened?

```yaml
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```

Add a port for tcp

svc.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/name: coredns
  name: coredns
  namespace: kube-system
  resourceVersion: "95020809"
  uid: 3d01d1a1-753a-4729-b0f1-b5271a9aee18
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```

```bash
kubectl apply -f svc.yaml
```

```bash
kubectl get svc coredns.yaml -n kube-system
```

There is no change after apply

```yaml
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```

Did not add successfully
```
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
```

When I `kubectl delete -f svc.yaml`, and then use `kubectl apply -f svc.yaml` again, it works

/sig api-machinery
/sig cli

### What did you expect to happen?

Apply will take effect after

svc.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    createdby: kubespray
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  creationTimestamp: "2023-01-03T10:14:13Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/name: coredns
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP

```

### How can we reproduce it (as minimally and precisely as possible)?

svc-0.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    createdby: kubespray
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  creationTimestamp: "2023-01-03T10:14:13Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/name: coredns
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP

```

```bash
kubectl apply -f svc-0.yaml
```

After execution, please make sure the result returned by `get svc` is the same as the result of `svc-0.yaml`

svc-1.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    createdby: kubespray
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  creationTimestamp: "2023-01-03T10:14:13Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/name: coredns
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```

```bash
kubectl apply -f svc-1.yaml
```

Then run `kubectl apply -f svc-1.yaml` again

Please confirm that the results are consistent

Another problem may arise at this point, and the following will be output

```bash
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Here's another bug

You can execute apply multiple times

Until the result is consistent with svc-1.yaml

Finally, run 

```bash
kubectl apply -f svc-0.yaml
```

ports cannot be modified

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.1-tke.1", GitCommit:"4180a3e93ec5dc8ae57778fc177019c946847c62", GitTreeState:"clean", BuildDate:"2023-03-30T03:04:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

```[tasklist]
### Tasks
```
