### ISSUE TITLE
Kubectl editing service will cause the port information to be lost

### ISSUE THREAD

**Issue by aimuz** [kubernetes/kubernetes#118918]
### What happened?

Using kubectl edit svc will cause unexpected changes to the port name

Before

```yaml
➜  ~ kubectl -n kube-system get svc coredns  -o yaml
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```

```bash
Kubectl edit svc coredns -n kube-system
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp-1 # Change dns-tcp to dns-tcp-1
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```

save After

```bash
kubectl -n kube-system get svc coredns -o yaml
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns-tcp-1
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```

The ports information has changed in a strange way

### What did you expect to happen?

Expected results

```yaml
apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
spec:
  clusterIP: 10.233.0.3
  clusterIPs:
  - 10.233.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp-1 # Change dns-tcp to dns-tcp-1
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
```

### How can we reproduce it (as minimally and precisely as possible)?

```bash
kubectl -n kube-system get svc coredns -o yaml
```

```bash
kubectl -n kube-system edit svc coredns
```

```bash
kubectl -n kube-system get svc coredns -o yaml
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
