### ISSUE TITLE
kubectl cannot correctly apply nodeport service

### ISSUE THREAD

**Issue by Richard-Joe** [kubernetes/kubernetes#119126]
### What happened?

old service：
```yaml
apiVersion: v1
kind: Service
metadata:
  name: loadbalance-echo-4
spec:
  type: NodePort
  selector:
    run: echo-4
  ports:
    - name: tcp-1234
      protocol: TCP
      port: 1234
      targetPort: 5001
```
kubectl apply -f svc.yaml
```
root@dev:/workspace/test# kubectl get svc -A
NAMESPACE     NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
default       loadbalance-echo-4   NodePort    10.96.212.12   <none>        1234:31919/TCP
```
then, change the service, add udp port
```yaml
apiVersion: v1
kind: Service
metadata:
  name: loadbalance-echo-4
spec:
  type: NodePort
  selector:
    run: echo-4
  ports:
    - name: tcp-1234
      protocol: TCP
      port: 1234
      targetPort: 5001
    - name: udp-1234
      protocol: UDP
      port: 1234
      targetPort: 5001
```
applied, but it didn't work
```
root@dev:/workspace/test# kubectl apply -f svc.yaml 
service/loadbalance-echo-4 configured
root@dev:/workspace/test# kubectl get svc -A
NAMESPACE     NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
default       loadbalance-echo-4   NodePort    10.96.212.12   <none>        1234:31919/TCP
```
then, use server-side, it works
```
root@dev:/workspace/test# kubectl apply -f svc.yaml --server-side=true
service/loadbalance-echo-4 serverside-applied
root@dev:/workspace/test# kubectl get svc -A
NAMESPACE     NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                         AGE
default       loadbalance-echo-4   NodePort    10.96.212.12   <none>        1234:31919/TCP,1234:30894/UDP   24h
```
So, when the kubectl apply command uses the patcher, is some configuration lost?

### What did you expect to happen?

client-side works fine

### How can we reproduce it (as minimally and precisely as possible)?

see my example

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"archive", BuildDate:"2023-07-06T04:11:30Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"archive", BuildDate:"2023-07-06T02:25:17Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux dev 6.0.7 #3 SMP PREEMPT_DYNAMIC Fri Jan 13 10:45:54 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

```[tasklist]
### Tasks
```
