### ISSUE TITLE
No ICMP is received when connecting to a node without local PODs when externalTrafficPolicy:Local is used

### ISSUE THREAD

**Issue by Sunnatillo** [kubernetes/kubernetes#119131]
### What happened?

Due to following upstream changes (K8s commit): https://github.com/kubernetes/kubernetes/pull/97081, when there is no local endpoint then kube-proxy will route the traffic to other endpoints in the cluster.

This change is added to support use-case/issue: https://github.com/kubernetes/kubernetes/issues/92857, where a POD within the cluster should be able to access the service by External LB IP. But this is causing an issue:

When a node ~~(which is not hosting any local endpoint)~~ (whose local endpoint is restarted and currently not up) receives traffic that is sent from an external IP to service LB IPreceives traffic that is sent from an external IP to service LB IP, the traffic is not SNATed as the service `ExternalTrafficPolicy` is 'local' but the traffic is forwarded to other node, resulting it to be dropped by other node. Thus connection remains `UNREPLIED` in conntrack.

This is breaking following use-case:

When we upgrade the deployment/daemonset, as the local end-points are going down and coming up again with new changes, for some time during this operation kube-proxy updates ipvs to forward traffic to other endpoints.

During this time any midstream redirected traffic causes conntrack entry to be as ESTABLISHED - UNREPLIED, and for any new connection it causes conntrack to register it as SYN-SENT - UNREPLIED
 
This causes significant traffic drop (blackholing) until this entry gets flushed out from conntrack.

### What did you expect to happen?

No traffic loss.

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy kubernetes cluster, with at least two worker nodes
2. Set `kube-proxy` mode to `ipvs`
3. Create a following daemonset:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: debugger-ds
  name: debugger-ds
spec:
  selector:
    matchLabels:
      app: debugger-ds
  template:
    metadata:
      labels:
        app: debugger-ds
    spec:
      containers:
      - image: ealen/echo-server:0.7.0
        name: http-https-echo
      initContainers:
      - name: init-nginx
        image: nginx:latest
        command: ['sleep', '120']

```
3. Create a LoadBalancer Service

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: debugger-ds
  name: dubugger-svc
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: debug-port
    port: 80
    targetPort: 80
  selector:
    app: debugger-ds
  type: LoadBalancer
```
4.  Set a static route from external server to one of the workers(worker-2).
5. Run hping3 command from external server to establish tcp connection to a worker-2. It is important to specify the source port here. 

`sudo hping3 -i u10000 -s <FIXED_SRC_PORT> --keep -p <SVC_PORT> -S <SVC_EXT_IP>
`
 6. Delete debugger-ds pod from worker-2. 

We can see tcp   UNREPLIED conntrack entries on worker-2. 
`
6 119 SYN_SENT src=192.168.39.1 dst=192.168.0.12 sport=40100 dport=80 [UNREPLIED] src=10.244.2.7 dst=192.168.39.1 sport=80 dport=40100 mark=0 use=1`

 

### Kubernetes version

`Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}`

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>
Delete debugger-ds pod from worker-2.

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
