### ISSUE TITLE
Pod gets VolumeConditionAbnormal event while volume is still being mounted

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/kubernetes#119293]
### What happened?

While testing the CSIVolumeHealth feature in Kubelet, we noticed that the VolumeConditionAbnormal event was recorded with message "Volume my-csi-volume: The volume isn't mounted" even though the volume was mounted successfully.

```
# kubectl describe pod my-csi-app-2
Name:             my-csi-app-2
Namespace:        default
Priority:         0
Service Account:  default
Node:             k8s-node-496-1686873019/10.92.186.76
Start Time:       Fri, 23 Jun 2023 11:43:09 +0000
Labels:           <none>
Annotations:      <none>
Status:           Running
IP:               10.244.5.28
IPs:
  IP:  10.244.5.28
Containers:
  my-frontend:
    Container ID:  containerd://14f864070f4ffeb1a9ebb5b2e7b1b75a00139f608fed41166a9fff960d608821
    Image:         harbor-repo.vmware.com/csi/busybox:1.35
    Image ID:      harbor-repo.vmware.com/csi/busybox@sha256:2f694e8d1755ba0be89165efc9a153349fd604d8afa24e5fa3006650eb124fbf
    Port:          <none>
    Host Port:     <none>
    Command:
      sleep
      1000000
    State:          Running
      Started:      Fri, 23 Jun 2023 11:43:18 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from my-csi-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-grcc6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  my-csi-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  csi-pvc-2
    ReadOnly:   false
  kube-api-access-grcc6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                   Age   From                     Message
  ----     ------                   ----  ----                     -------
  Normal   Scheduled                2m3s  default-scheduler        Successfully assigned default/my-csi-app-2 to k8s-node-496-1686873019
  Normal   SuccessfulAttachVolume   2m3s  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-67414d8f-33ad-4ade-a61f-bedbaf1745fc"
  Normal   Pulled                   114s  kubelet                  Container image "harbor-repo.vmware.com/csi/busybox:1.35" already present on machine
  Normal   Created                  114s  kubelet                  Created container my-frontend
  Normal   Started                  114s  kubelet                  Started container my-frontend
  Warning  VolumeConditionAbnormal  67s   kubelet                  Volume my-csi-volume: The volume isn't mounted
```
It appears that this warning event happened while Kubelet is still working on mounting the volume. So the event was recorded too early.  Instead, we should record this warning event only if the volume is no longer mounted after it has been mounted successfully previously.

https://github.com/kubernetes/kubernetes/blob/v1.28.0-alpha.4/pkg/kubelet/server/stats/volume_stat_calculator.go#L172

### What did you expect to happen?

We don't expect the VolumeConditionAbnormal event to happen before the volume is mounted successfully.  Kubelet will continue to monitor the volume stats including the volume health condition after the volume is mounted and should only record the event if the volume is no longer mounted after the volume has been mounted successfully earlier.

### How can we reproduce it (as minimally and precisely as possible)?

- Enable CSIVolumeHealth alpha feature gate in Kubelet.
- Using examples [here](https://github.com/kubernetes-csi/csi-driver-host-path/tree/master/examples), create a StorageClass for the CSI hostpath driver, create a PVC, and create a Pod using the PVC.
```
~/csi-driver-host-path/examples# cat csi-pvc.yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc # defined in csi-storageclass.yaml

~/csi-driver-host-path/examples# cat csi-app.yaml
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app-3
spec:
  containers:
    - name: my-frontend
      image: harbor-repo.vmware.com/csi/busybox:1.35
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: csi-pvc-3 # defined in csi-pvc.yaml
```
- Watch that the Pod is in running state, but there is a warning event like this: `Warning  VolumeConditionAbnormal  67s   kubelet                  Volume my-csi-volume: The volume isn't mounted`

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:10:18Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:04:24Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
vSphere, however, CSI hostpath driver is used.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
