### ISSUE TITLE
Conntrack cleaning happens before network programming endpoints

### ISSUE THREAD

**Issue by aroradaman** [kubernetes/kubernetes#119249]
### What happened?

Currently kube-proxy efficiently cleans all stale conntrack entries preventing traffic black holing for deleted endpoints, but there can be some corner cases when conntrack cleaning happens before programming the network leaving a small window in which if any packet arrives will back-hole the traffic.

The corner case:
Taking a simple case of load-balancer service backed by a deployment with single replica, on deleting the pod(gracefully), I observed two **OnEndpointSliceUpdate** invocations:
1.  First one with EndpointConditions.Ready as false
2. EndpointSlice was cleared for the pod 

The conntrack flow for this case:
1. After processing the first **OnEndpointSliceUpdate** invocation **EndpointsMap** will still have entries for the pod as endpoint still exists, though not in ready state so proxier won't program deletion of endpoint from the data path. But the endpoint IP will be picked for conntrack cleaning as new endpoint != old endpoint because of the not ready condition.
https://github.com/kubernetes/kubernetes/blob/95e915c4288eda15da1724989f3f7dec9f3512d6/pkg/proxy/endpoints.go#L423-L436
https://github.com/kubernetes/kubernetes/blob/95e915c4288eda15da1724989f3f7dec9f3512d6/pkg/proxy/endpoints.go#L120-L126

2.  After processing the second **OnEndpointSliceUpdate** invocation **EndpointsMap** won't have entries for the endpoint and the proxier will program deletion of the endpoint in the data path. EndpointIP won't be picked up for conntrack cleaning as the following logic will skip it
https://github.com/kubernetes/kubernetes/blob/95e915c4288eda15da1724989f3f7dec9f3512d6/pkg/proxy/endpoints.go#L417-L421

This behaviour leads to conntrack cleaning one cycle ahead of network programming.  
This might be a regression of https://github.com/kubernetes/kubernetes/pull/106163

### What did you expect to happen?

Conntrack cleanup should happen after programming the network.

### How can we reproduce it (as minimally and precisely as possible)?

This behaviour can be observed in kube-proxy logs (verbosity=4).
[link to log snippet showing the behaviour](https://github.com/kubernetes/kubernetes/pull/119010#issuecomment-1622325495)

I used the following objects for experimenting:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-worker2
      containers:
      - name: test
        image: registry.k8s.io/e2e-test-images/agnhost:2.45
        command:
          - /agnhost
        args:
          - netexec
          - --udp-port=80
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
    - protocol: UDP
      name: udp
      nodePort: 31111
      port: 80
      targetPort: 80
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
I was using latest kind node-image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
