### ISSUE TITLE
Statefulset with podManagementPolicy=Parallel ignores minReadySeconds on statefulset rollout update

### ISSUE THREAD

**Issue by rkojedzinszky** [kubernetes/kubernetes#119234]
### What happened?

Deployed a statefulset with `podManagementPolicy: Parallel` and with `minReadySeconds: 15`, have waited for all the pods being ready. Then, issued a rollout restart on the sts.

### What did you expect to happen?

Expected that the rollout update happens the same way as with `podManagementPolicy: OrderedReady`, that is the last pod is terminated, then restarted, waited to be ready, and then waiting for the extra `minReadySeconds` to pass before moving the next pod. Instead, once the pod became ready, the rollout process instantly moved to the next pod, ignoring the `minReadySeconds` setting.

### How can we reproduce it (as minimally and precisely as possible)?

Apply the following sts:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  minReadySeconds: 10
  podManagementPolicy: Parallel
  replicas: 5
  selector:
    matchLabels:
      application: web
  serviceName: web
  template:
    metadata:
      labels:
        application: web
    spec:
      containers:
      - image: nginx
        name: web
  updateStrategy:
    type: RollingUpdate
```

Wait until all pods become ready. Then, issue a rollout restart:

```
$ kubectl rollout restart sts web
```

Then, observe that as soon a pod enters ready state, the upgrade process moves to the next pod, ignoring `minReadySeconds` value.

If the sts is created with default `podManagementPolicy`, the update procedure works as expected.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux k-desktop 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kind
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xuexu6666** [comment]
I can reproduce with the following config at k8s version 1.25.6. If using `podManagementPolicy: Parallel` and `minReadySeconds: 20`, statefulset controller would ignore `minReadySeconds: 20` and directly update the next pod. From the documentation of [minReadySeconds](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#minimum-ready-seconds), it is expected to work for both `podManagementPolicy = OrderedReady` or `Parallel` during updating. From the testing, only `podManagementPolicy = OrderedReady` works as expected.


```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  minReadySeconds: 20
  podManagementPolicy: Parallel
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```
