### ISSUE TITLE
Repeated server side apply to a statefulset updates the revisionVersion, even without template modifications.

### ISSUE THREAD

**Issue by bachmanity1** [kubernetes/kubernetes#119304]
### What happened?

I am utilizing server-side apply to generate a statefulset using the provided template. Afterwards, without modifying the template, I perform server-side apply once more with the expectation that it will not alter the statefulset in any manner. However, I have observed that server-side apply does update the resourceVersion, and each subsequent apply operation also updates the resourceVersion.

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-ssa
  labels:
    app: test-ssa
spec:
  serviceName: "test-ssa"
  selector:
    matchLabels:
      app: test-ssa
  replicas: 1
  template:
    metadata:
      labels:
        app: test-ssa
    spec:
      containers:
        - name: test-ssa
          image: alpine:3.17.4
          command: ["sh", "-c", "while true; do echo 'sleep 10'; sleep 10; done"]
          volumeMounts:
          - name: pvc
            mountPath: /etc
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 100m
              ephemeral-storage: 1Gi
              memory: 128Mi
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: rbd-ssd
```

I've also observed that if I modify `volumeClaimTemplates` section by adding some extra fields(shown below) generated by the k8s then server side apply does NOT update resourceVersion. 
```
...
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null # added
        name: pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: rbd-ssd
        volumeMode: Filesystem # added
      status: # added
          phase: Pending # added
```

Can anyone please explain this behavior? I haven't observed similar behavior while testing with other resource types, statefulset seems to be somewhat special. 

### What did you expect to happen?

I expected that performing repeated server-side apply without any template modifications would not update the resourceVersion.

### How can we reproduce it (as minimally and precisely as possible)?

`test-ssa.yaml`

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-ssa
  labels:
    app: test-ssa
spec:
  serviceName: "test-ssa"
  selector:
    matchLabels:
      app: test-ssa
  replicas: 1
  template:
    metadata:
      labels:
        app: test-ssa
    spec:
      containers:
        - name: test-ssa
          image: reg.navercorp.com/base/alpine:3.17
          command: ["sh", "-c", "while true; do echo 'sleep 10'; sleep 10; done"]
          volumeMounts:
          - name: pvc
            mountPath: /etc
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 100m
              ephemeral-storage: 1Gi
              memory: 128Mi
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: rbd-ssd
```
You can see that every time you run the command shown below resourceVersion of the `test-ssa` statefulset is updated.
`k apply -f test-ssa.yaml --server-side=true --field-manager=test --force-conflicts=true`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:46:11Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:42:57Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
on-prem cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Darwin local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103 arm64

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
