### ISSUE TITLE
failing kubelet / kubeadm skew tests

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#119325]
### Which jobs are failing?

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kubelet-1-26-on-latest
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kubelet-1-27-on-latest

also
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest-on-1-27

### Which tests are failing?

skewed / older kubelet is failing to parse a --config file generated by kubeadm at k/k master (1.28-pre).
kubeadm imports the public v1beta1 kubeletconfiguration, applies some kubeadm related defaults and then marshals the config to a file. since some of the kubelet fields are not pointers they end up as part of the marshaled output as per golang's PoD type defaults - e.g. bools are "false", ints are 0, etc.

```
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.0-alpha.4.212+e3bc35bc1bc7b3", GitCommit:"e3bc35bc1bc7b399b564f2c4efc75eb9959e70f7", GitTreeState:"clean", BuildDate:"2023-07-14T06:08:00Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubelet --version
Kubernetes v1.27.3-50+3ca3e0ad4841ce
```

```
# modified minimal kubelet config to reproduce
#
cat /var/lib/kubelet/config.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: false
authorization:
  mode: AlwaysAllow
logging:
  flushFrequency: 0s # problem field
```

```
kubelet --config /var/lib/kubelet/config.yaml
E0714 11:21:44.209001    3335 run.go:74] "command failed" err="failed to load kubelet config file, error: failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to decode: json: cannot unmarshal string into Go struct field LoggingConfiguration.logging.flushFrequency of type time.Duration, path: /var/lib/kubelet/config.yaml"
```

on a quick look it seems this old version of kubelet does not tolerate the "0s".
before https://github.com/kubernetes/kubernetes/pull/117800/commits/c550c17f7f0910ca32fcf97762170bea4f616cc6#diff-0eee074a0055cfbd121ea036feb1e593d7e37980cc291732368c0b94a8ded444L42-L45

```
logging:
  flushFrequency: 0
```

after:
 ```
logging:
  flushFrequency: 0s
```

which renders the change in the kubelet v1beta1 not backwards compatible for existing v1beta1 configs prepared by users.
we either need to allow the 0s to pass for older kubelets and/or backport some changes.

### Since when has it been failing?

since https://github.com/kubernetes/kubernetes/pull/117800 merged

cc @liggitt @pohly @danwinship 
/assign @cyclinder 

### Relevant SIG(s)

/sig
