### ISSUE TITLE
the time interval between the createion of two StatefulSet pods is not equal to `spec.minReadySeconds`

### ISSUE THREAD

**Issue by nayihz** [kubernetes/kubernetes#119352]
### What happened?

When I try to create a statefulset with more than 2 replias(example as follows), the time interval between the creation of Pods is twice the value configured in `minReadySeconds`.

```bash
# k get po
NAME    READY   STATUS    RESTARTS   AGE
sts-0   1/1     Running   0          24s
sts-1   1/1     Running   0          4s
```
As we can see from the result, the time interval between the createion of these two pods is (24s-4s) = 20s, but in fact `spec.minReadySeconds` is 10 but not 20.
IIUR, the time interval between the createion of these two pods is equal to `spec.minReadySeconds`
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts
spec:
  serviceName: "nginx"
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
```

### What did you expect to happen?

the time interval between the createion of these two pods is equal to `spec.minReadySeconds`

### How can we reproduce it (as minimally and precisely as possible)?

yaml as above

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

Kubernetes v1.26.3

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
