### ISSUE TITLE
HTTP Health Check stats are not reported correctly

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#11948]
A new Pod with HTTP Health Check probe is created as:

```
apiVersion: v1
kind: Pod
metadata:
  name: wildfly-pod
  labels: 
    name: wildfly
spec: 
  containers: 
    - image: jboss/wildfly
      name: wildfly-pod
      livenessProbe:
        # an http probe
        httpGet:
          path: /index.html
          port: 8080
        httpGet:
          path: /movieplex7
          port: 8080
        # length of time to wait for a pod to initialize
        # after pod startup, before applying health checking
        initialDelaySeconds: 30
        timeoutSeconds: 1
      ports: 
        - containerPort: 8080
```

This one works correctly. If the path of second probe is changed to `/movieplex` then status of created Pod is shown as:

```
kubernetes-1.0.1> ./cluster/kubectl.sh get -w po
NAME      READY     STATUS    RESTARTS   AGE
NAME          READY     STATUS    RESTARTS   AGE
wildfly-pod   0/1       Pending   0          0s
wildfly-pod   0/1       Pending   0         0s
wildfly-pod   0/1       Pending   0         0s
wildfly-pod   0/1       Running   0         2s
wildfly-pod   1/1       Running   0         10s
wildfly-pod   0/1       Running   1         51s
wildfly-pod   1/1       Running   1         52s
wildfly-pod   0/1       Running   2         1m
wildfly-pod   1/1       Running   2         1m
wildfly-pod   0/1       Running   3         2m
wildfly-pod   1/1       Running   3         2m
wildfly-pod   0/1       Running   3         3m
wildfly-pod   1/1       Running   3         3m
wildfly-pod   0/1       Running   4         4m
wildfly-pod   1/1       Running   4         4m
wildfly-pod   1/1       Running   3         4m
wildfly-pod   0/1       Running   4         5m
wildfly-pod   1/1       Running   4         5m
wildfly-pod   1/1       Running   2         5m
wildfly-pod   0/1       Running   3         5m
wildfly-pod   1/1       Running   3         5m
wildfly-pod   0/1       Running   3         6m
wildfly-pod   1/1       Running   3         6m
wildfly-pod   0/1       Running   4         7m
wildfly-pod   1/1       Running   4         7m
wildfly-pod   1/1       Running   3         7m
wildfly-pod   0/1       Running   4         7m
wildfly-pod   1/1       Running   4         7m
wildfly-pod   0/1       Running   3         8m
wildfly-pod   1/1       Running   3         8m
wildfly-pod   0/1       Running   4         9m
wildfly-pod   1/1       Running   4         9m
wildfly-pod   1/1       Running   3         9m
wildfly-pod   0/1       Running   4         9m
wildfly-pod   1/1       Running   4         9m
wildfly-pod   0/1       Running   3         10m
wildfly-pod   1/1       Running   3         10m
wildfly-pod   0/1       Running   4         11m
wildfly-pod   1/1       Running   4         11m
wildfly-pod   1/1       Running   2         11m
wildfly-pod   0/1       Running   3         11m
wildfly-pod   1/1       Running   3         11m
wildfly-pod   0/1       Running   3         12m
wildfly-pod   1/1       Running   3         12m
wildfly-pod   0/1       Running   3         13m
wildfly-pod   1/1       Running   3         13m
wildfly-pod   0/1       Running   4         14m
wildfly-pod   1/1       Running   4         14m
wildfly-pod   1/1       Running   3         14m
wildfly-pod   0/1       Running   4         15m
wildfly-pod   1/1       Running   4         15m
wildfly-pod   1/1       Running   2         15m
wildfly-pod   0/1       Running   3         16m
wildfly-pod   1/1       Running   3         16m
wildfly-pod   0/1       Running   3         16m
wildfly-pod   1/1       Running   3         16m
wildfly-pod   0/1       Running   3         17m
wildfly-pod   1/1       Running   3         17m
wildfly-pod   0/1       Running   4         18m
wildfly-pod   1/1       Running   4         18m
wildfly-pod   1/1       Running   3         18m
wildfly-pod   0/1       Running   4         19m
wildfly-pod   1/1       Running   4         19m
wildfly-pod   1/1       Running   2         19m
```

The stats on restarts are not reported correctly because the container should have started multiple times because the probe is failing. The number of restarts should increase by 1 every time it is restarted.
