### ISSUE TITLE
e2e tests for kubectl proxy cannot get cluster url

### ISSUE THREAD

**Issue by whzghb** [kubernetes/kubernetes#119419]
### What happened?

When I was running an e2e test:
`kubetest2 noop -v 2 --test=ginkgo --run-id=e2etest -- --focus-regex='should support exec through kubectl proxy'`

I got the error below:
`  [FAILED] --host variable must be set to the full URI to the api server on e2e run.
  In [It] at: test/e2e/kubectl/kubectl.go:512 @ 07/19/23 10:38:34.036
`

the test code is:
```
if TestContext.Host == "" && c.Clusters != nil {
	currentContext, ok := c.Clusters[c.CurrentContext]
	if ok {
		TestContext.Host = currentContext.Server
	}
}
```
but my kubeconfig is:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  
         ...
    server: https://172.21.42.202:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
```

the curren-context name is "kubernetes-admin@kubernetes", the cluser name is "kubernetes", the test code didn`t use the context.cluster name but context name as the key to get the cluster,  which causes the assignment to fail

### What did you expect to happen?

use the context.cluster.name, not the context name

### How can we reproduce it (as minimally and precisely as possible)?

I use the kubetest2 to run the test: 
`kubetest2 noop -v 2 --test=ginkgo --run-id=e2etest -- --focus-regex='should support exec through kubectl proxy'`

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
