### ISSUE TITLE
PVC dataSource is immutable

### ISSUE THREAD

**Issue by uhthomas** [kubernetes/kubernetes#119451]
### What happened?

Given a PVC created with [CSI Volume Cloning](https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/):

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  dataSource:
    apiGroup: null
    kind: PersistentVolumeClaim
    name: grafana-hdd
  dataSourceRef:
    apiGroup: null
    kind: PersistentVolumeClaim
    name: grafana-hdd
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-nvme-ec-delete-block
  volumeMode: Filesystem
  volumeName: pvc-0fcb6ae8-99e0-4062-b027-5606ae963c2e
```

It's not possible to remove the `dataSource` and `dataSourceRef` fields, which is aggravating as the documentation claims the new PVC should be considered completely independent:

> Upon availability of the new PVC, the cloned PVC is consumed the same as other PVC. It's also expected at this point that the newly created PVC is an independent object. It can be consumed, cloned, snapshotted, or deleted independently and without consideration for it's original dataSource PVC. This also implies that the source is not linked in any way to the newly created clone, it may also be modified or deleted without affecting the newly created clone.

https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/#usage

As such, if the reference PVC were to be deleted, there would be no meaning to the `dataSource` and `dataSourceRef` fields at all. This goes against "gitops" management.

### What did you expect to happen?

The fields `dataSource` and `dataSourceRef` should not be immutable.

### How can we reproduce it (as minimally and precisely as possible)?

Create a PVC, and then create another PVC with [CSI Volume Cloning](https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/), then attempt to delete the fields `dataSource` and `dataSourceRef`.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"archive", BuildDate:"2023-06-15T08:14:06Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

N/A

### OS version

N/A

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
