### ISSUE TITLE
[Question] Proxy to replace publicIPs based service access?

### ISSUE THREAD

**Issue by esecules** [kubernetes/kubernetes#11950]
As of now Im using public IPs to access my services from outside the kubernetes cluster and I'm looking for a better way than doing:  ```curl http://kubenode1:<some port# I have to find>```. Ideally the solution would only require me to know the service name and the name I gave the port like "dashboard" or "api".

**Comment by kelseyhightower** [comment]
@esecules I've been using NodePort when setting up a kubernetes service. For example I can hit port 36000 on any node running the kube-proxy and hit the hello service.

```
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - name: http
    nodePort: 36000
    port: 80
    protocol: TCP
```
