### ISSUE TITLE
service.beta.kubernetes.io/load-balancer-source-ranges not usable with ExternalName

### ISSUE THREAD

**Issue by excalq** [kubernetes/kubernetes#119548]
### What happened?

[Per AWS Load Balancer Controller's docs](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/service/annotations/#lb-source-ranges), the annotation `service.beta.kubernetes.io/load-balancer-source-ranges` will provision Security Groups for a Load Balancer when configured with a service. Other AWS LB annotations work as expected with an `ExternalName` service, however this annotation fails [validation (code pointer)](https://github.com/kubernetes/kubernetes/blob/b53830590fc2eff8a219d7bc225091878263ebe6/pkg/apis/core/validation/validation.go#L5252-L5271), with an error as follows:

`Service "the-externalname-service" is invalid: metadata.annotations[service.beta.kubernetes.io/load-balancer-source-ranges]: Forbidden: may only be used when `type` is 'LoadBalancer'`

### What did you expect to happen?

The annotation is passed to the aws-load-balancer-controller as are other LB annotations.

### How can we reproduce it (as minimally and precisely as possible)?

An example, ran on AWS EKS, which deploys a Network Load Balancer, without the problematic final annotation.

```
apiVersion: v1
kind: Service
metadata:
  name: opensearch-ingress-proxy
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: HTTPS
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-success-codes: 200-403
    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
    service.beta.kubernetes.io/aws-load-balancer-name: eks-opensearch-ingress-proxy
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/load-balancer-source-ranges: 8.8.8.0/24
spec:
  type: ExternalName
  sessionAffinity: None
  externalName: opensearch-internal-api.our.domain

```

### Kubernetes version

<details>

```console
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.27.3-eks-a5565ad
```

</details>

### Cloud provider

<details>
AWS
</details>
