### ISSUE TITLE
Can't restrict access from K8s nodes with loadBalancerSourceRanges for proxy-mode=ipvs

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#119656]
### What happened?

When using loadBalancerSourceRanges to allow access only from CIDRs outside the cluster segment, access from the K8s nodes (or pods with hostNetwork:true) should be rejected, but for proxy-mode=ipvs it works.

/sig network
/area kube-proxy
/area ipvs

### What did you expect to happen?

Access from K8s nodes should be rejected in the same way as for proxy-mode=iptables

### How can we reproduce it (as minimally and precisely as possible)?

Define a service with loadBalancerSourceRanges that allows access from a cidr outside the cluster, e.g.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: alpine
spec:
  loadBalancerSourceRanges:
#  - "192.168.1.0/24"
  - "192.168.2.0/24"
#  - "fd00::c0a8:100/120"
  - "fd00::c0a8:200/120"
  ipFamilyPolicy: RequireDualStack
  selector:
    app: alpine
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 5001
    name: nc
```
The K8s nodes have addresses on 192.168.1.0/24 and fd00::c0a8:100/120.

Make sure a loadBalancerIP is assigned (in this example 10.0.0.0/32) and try to access it from a K8s node:
```
# With proxy.mode=ipvs
> nc 10.0.0.0:5001
alpine-f6c8bd7db-zljnl    # (works)
# With proxy.mode=iptables
# nc 10.0.0.0:5001
# (hangs...)
```

### Anything else we need to know?

Same for both ipv4 and ipv6.

This is related to https://github.com/kubernetes/kubernetes/issues/119524 since a fix requires that the `nodeID` passed to the `kube-proxy` is correct. Please see https://github.com/kubernetes/kubernetes/issues/119524#issuecomment-1655389139

### Kubernetes version

v1.27.4 and master

### Cloud provider

None

### OS version

Linux 6.4.4

### Install tools

None

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A
