### ISSUE TITLE
CronJob gets stuck when jobs quota is reached

### ISSUE THREAD

**Issue by ASverdlov** [kubernetes/kubernetes#119775]
### What happened?

We (in Booking.com) run CronJobs in Kubernetes clusters with ResourceQuota's defined. When quota for # of jobs is reached we observed that CronJobs:
1. stop scheduling new jobs (because quota is reached),
2. don't clean the old jobs (despite # of jobs > history allows and the fact that it would unblock the CronJob new Jobs). 

The only way to progress is to remove enough Jobs to make room for a new Job in namespace quota. When we do that manually, the CronJob kicks in.

The workaround we found around the internet is to specify `ttlSecondsAfterFinished` for the job template. But it's not ideal as it's not a history-based limit, but a time-based limit, and often you want to have the last N jobs to be around for debugging.

### What did you expect to happen?

When jobs quota is reached and # of cronjob jobs exceeds specified the history limit, these jobs are deleted giving room for new jobs to run.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: job-quota
  namespace: default
spec:
  hard:
    count/jobs.batch: "1"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cronjob
spec:
  successfulJobsHistoryLimit: 0
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-world
              image: bash
              command: ["bash", "-c", "sleep 80"]
          restartPolicy: OnFailure
```

1. Wait for a first Job to be created (which will fill up the jobs quota) at X minute.
2. A job for X + 1 will fail to be created (because quota won't allow, and X job is still running).
3. All future attempts to create a new job by the controller will fail (check `kubectl get events --sort-by='.lastTimestamp' | tail`, you'll see re-occuring `Error creating job: jobs.batch "hello-world-cronjob-28187648" is forbidden: exceeded quota: job-quota, requested: count/jobs.batch=1, used: count/jobs.batch=1, limited: count/jobs.batch=1`).
4. The first job will never be cleaned (although it will be eligible, since history is 0).

### Anything else we need to know?

Looks like the problem was introduced in the `cronjob_controllerv2.go` implementation: if `jm.syncCronJob` returned an error, we return from the function and never invoke `jm.cleanupFinishedJobs`.:
https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/pkg/controller/cronjob/cronjob_controllerv2.go#L199-L213

In the old `cronjob_controller.go` implementation this was not the case:
https://github.com/kubernetes/kubernetes/blob/0f77da5bd4809927e15d1658fb4aa8f13ad890a5/pkg/controller/cronjob/cronjob_controller.go#L137-L138

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.27) and server (1.21) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
Baremetal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
