### ISSUE TITLE
CEL Estimated cost incorrect for lowerAscii

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#119749]
### What happened?

Creating a CRD with a case-insensitive uniqueness check and appropriate maxLength/maxItems limits should be allowed:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uniquetests.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                headers:
                  type: array
                  maxItems: 1
                  x-kubernetes-validations:
                    - rule: "self.all(item1, self.exists_one(item2, item1.name.lowerAscii() == item2.name.lowerAscii()))"
                  items:
                    type: object
                    properties:
                      name:
                        maxLength: 1
                        type: string
  scope: Namespaced
  names:
    plural: uniquetests
    singular: uniquetest
    kind: UniqueTest
```

But I got:

```
kubectl apply -f unique.yaml
The CustomResourceDefinition "uniquetests.stable.example.com" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[headers].x-kubernetes-validations[0].rule: Forbidden: estimated rule cost exceeds budget by factor of more than 100x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared)
* spec.validation.openAPIV3Schema.properties[spec].properties[headers].x-kubernetes-validations[0].rule: Forbidden: contributed to estimated rule cost total exceeding cost limit for entire OpenAPIv3 schema
* spec.validation.openAPIV3Schema: Forbidden: x-kubernetes-validations estimated rule cost total for entire OpenAPIv3 schema exceeds budget by factor of more than 100x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared)
```

### What did you expect to happen?

I expected the estimated cost to be very low with maxItems=1 and maxLength=1.

### How can we reproduce it (as minimally and precisely as possible)?

This also exceeds the estimated cost limit, suggesting the problem is unrelated to the array:

```yaml
 x-kubernetes-validations:                                                                                        
  - rule: "self[0].name.lowerAscii() == self[0].name.lowerAscii()"
```

But this is valid (estimated cost is under the limit):

```yaml
x-kubernetes-validations:                                                                                        
  - rule: "self.all(item1, self.exists_one(item2, item1.name == item2.name))"
```

Which suggests that the estimated cost system is not handling `lowerAscii` correctly.  The estimated cost of `lowerAscii` should be a function of the input string length (which in this case has a max length of 1), and, for purposes of subsequent cost calculations, the resulting value of `lowerAscii` should be known by the estimated cost system to be the same length as the input string.

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/staging/src/k8s.io/apiserver/pkg/cel/library/cost.go#L119 is where the estimated cost of lowerAscii is handled. Just glancing at the code I don't see an obvious problem.

### Kubernetes version

<details>
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"29+", GitVersion:"v1.29.0-alpha.0.17+97c7dbcd227ec2", GitCommit:"97c7dbcd227ec253bb277a91575706fe30f519dc", GitTreeState:"clean", BuildDate:"2023-07-29T02:24:33Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
hack/local-up-cluster.sh
</details>
