### ISSUE TITLE
Add different roles for resources in same apigroups in kubernetes

### ISSUE THREAD

**Issue by smartaquarius10** [kubernetes/kubernetes#119740]
I need to define different roles for pods/log and namespaces.. Tried this but second resources section overwriting the first(pods) one and its verbs as well.  Any suggestions please

```
- apiGroups: [""] 
  resources:
    - pods   
  verbs:
    - create
    - delete
    - get
    - list
  resources:
    - pods/log
    - namespaces
  verbs:
    - get
    - list
```
Kind Regards,
Tanul

**Comment by carlory** [comment]
FYI:

```yaml
- apiGroups: [""] 
  resources:
    - pods   
  verbs:
    - create
    - delete
    - get
    - list
- apiGroups: [""] 
  resources:
    - pods/log
    - namespaces
  verbs:
    - get
    - list
```
