### ISSUE TITLE
Resource allocation during startup

### ISSUE THREAD

**Issue by saireddyb** [kubernetes/kubernetes#119893]
Is there a option to set different cpu resource allocation to a container only during till the application is in ready state.
Eg:
```
resources: 
  limits:
    cpu: 500m
    memory: 750Mi
  requests:
    cpu: 250m
    memory: 750Mi
```
This is the resource allocation we can currentrly give to a container which is great of course.
But I have a unique situation where my conatiner only during the initial startup if given (cpu cores) can consume up to 4 cores (4000m) which helps to start the application in under 5 seconds.
Neither with the above existing resource requests and limits the conainer will take 4 min.

Can we pass resources like 
```
resources: 
  startup:
    cpu: 4000m
    memory: 750Mi
  limits:
    cpu: 500m
    memory: 750Mi
  requests:
    cpu: 250m
    memory: 750Mi
```
    
 This startup resource to consume only during the startup till the container becomes to ready state.
 Ofcourse I can directly give 4000m to limits but I want the bussiness logic in the container to run in only under limited resource but only during startup I want to change as it helps to start the container in under 5 seconds.
 
 I know we can edit the resources live but I believe that is not ideal.
