### ISSUE TITLE
HostAliases for static pods do not take effect when the node network is not yet connected

### ISSUE THREAD

**Issue by Levi080513** [kubernetes/kubernetes#119852]
### What happened?

When the node network is not yet connected, start kubelet and create static pod like this 
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: cp_enable
      value: "true"
    - name: vip_interface
      value: ens4
    - name: address
      value: 10.255.9.11
    - name: port
      value: "6443"
    - name: vip_arp
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    image: 10.255.128.144/sks/kube-vip/kube-vip:v0.5.12
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
    - mountPath: /etc/localtime
      name: localtime
      readOnly: true
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /etc/localtime
      type: ""
    name: localtime
status: {}
```
The created container ` /etc/hosts` file does not contain the configuration of hostAliases.
```
::1         ipv6-localhost ipv6-loopback
127.0.0.1   localhost
127.0.0.1   hw-sks-test--1-24-16-controlplane-f4zt8
```

### What did you expect to happen?

The created container ` /etc/hosts` file should contain the configuration of hostAliases.

### How can we reproduce it (as minimally and precisely as possible)?

1. Stop kubelet service.
2. Create static pod with configuration of hostAliases.
3. disconnet network, like `nmcli device disconnect ens4`.
4. Start kubelet service.
5. The created container ` /etc/hosts` file does not contain the configuration of hostAliases.

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:34:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:27:46Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
$ uname -a
4.18.0-425.3.1.el8.x86_64

```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd containerd.io 1.6.4 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
