### ISSUE TITLE
NodeResourcesFit support multi strategy

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes/kubernetes#119849]
### What would you like to be added?

There are different kinds of nodes in our clusters.
We want to use a binpack strategy for gpu nodes and use a spread strategy for cpu nodes.

Support to set different binpack or spread strategy for different nodes.

### Why is this needed?

If we set the a binpack strategy for nvidia.com/gpu in our cluster, nodeResourceFit will score 0 for all nodes and all pods without gpu requests. As a result, these pods maybe scheduled on one node.

You can see the resource consumption:
> k inspect resource 
Resource                          Requested          Limit               Allocatable  Free
 cpu                              37150m (79.4%)     55500m (118.6%)     46800m       9650m
 ├─ nodeA   15150m (97.1%)     27300m (175.0%)     15600m       450m
 ├─ nodeB   7 (44.9%)          11100m (71.2%)      15600m       8600m
 └─ nodeC  15 (96.2%)         17100m (109.6%)     15600m       600m

**Comment by denkensk** [comment]
I think this fits the practical needs, we also have different node pools in the same cluster in our production environment and would like to have different strategies for NodeResourceFit as well

**Comment by tzneal** [comment]
I think a near-term workaround would be to run multiple schedulers configured differently (e.g. your normal scheduler and a "gpu" scheduler) and use taints/tolerations to segregate your pods.

**Comment by KunWuLuan** [comment]
> I think a near-term workaround would be to run multiple schedulers configured differently (e.g. your normal scheduler and a "gpu" scheduler) and use taints/tolerations to segregate your pods.

@tzneal  Thanks, I think you are right, deploy a scheduler with 2 profiles is a good way to meet the requirement for now. But it still need some changes for existing workload.

**Comment by kerthcet** [comment]
Do you mean if pod requires gpu, then we'll process with binpack scheduling(by configured)?

**Comment by KunWuLuan** [comment]
> Do you mean if pod requires gpu, then we'll process with binpack scheduling(by configured)?

@kerthcet I mean maybe we should support apply different resource allocate policy for different nodes (maybe distinguish them using label selectors)

**Comment by AxeZhan** [comment]
If we're going to score the nodes with different strategies, how can we rank them after scoring🤔️. I think their scores will have different meanings under different strategies.

**Comment by kerthcet** [comment]
I think this is a reasonable demand, like GPU is expensive we hope they're binpack however CPU can apply with spread strategy to avoid heat node. WDYT? @kubernetes/sig-scheduling-misc

**Comment by AxeZhan** [comment]
We actually suffered from this a few months ago.
We have a cluster where training workloads and serving workloads running together.  And like this issue, we set binpack strategy for nvidia.com/gpu in our cluster, which results in our serving workloads all scheduled to the same node.
We ended up set `topologyspreadconstraints` for serving workloads to spread them in cluster.
Multi strategy can indeed help. But I was thinking that make it a pod configuration(like node affinity), instead of making a node configuration.

**Comment by KunWuLuan** [comment]
> But I was thinking that make it a pod configuration(like node affinity), instead of making a node configuration.

Do you mean a pod can say it want to go to a low usage node or a high usage node? I think this is a good idea.

**Comment by AxeZhan** [comment]
> Do you mean a pod can say it want to go to a low usage node or a high usage node? I think this is a good idea. 

Yes.

**Comment by alculquicondor** [comment]
Does anyone have a proposal for how the math could look like? We need to answer this https://github.com/kubernetes/kubernetes/issues/119849#issuecomment-1680164017

And also how to normalize scores.

> If we set the a binpack strategy for nvidia.com/gpu in our cluster, nodeResourceFit will score 0 for all nodes and all pods without gpu requests. As a result, these pods maybe scheduled on one node.

You could still set binpacking for multiple resources and apply weights. If a node doesn't have the resource, it will just use the remaining ones.

**Comment by AxeZhan** [comment]
> Does anyone have a proposal for how the math could look like? We need to answer this https://github.com/kubernetes/kubernetes/issues/119849#issuecomment-1680164017

If we do this as  https://github.com/kubernetes/kubernetes/issues/119849#issuecomment-1953634478 . There should be no math problems.

> But I was thinking that make it a pod configuration(like node affinity), instead of making a node configuration.

The pod will probably look like this(only a draft):
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  nodeResourceFitStrategy:
    Type: MostAllocated
    Resources:
      - gpu
```
It will have the same effect as we reconfigure nodeResourceFit's strategy each time scheduler receives a pod, and use the new strategy to score this pod.
We can also leave most of the logics of `noderesources` plugin unchanged, only that we'll have multiple scorers in `Fit` struct, and use different scorer in `Score`.
When a pod doesn't have `nodeResourceFitStrategy` field set, we can keep the original way(using strategy set in scheduler config), so it's also compatible.
This will bring some api changes though.

/remove-lifecycle stale

**Comment by kerthcet** [comment]
From my poor point, how resource being consumed should be a global configuration, if partial pods want binpack, the other parts want spread, then actually no strategy will take effect. It's a hedge result. 

If each resource has independent scoring strategy, then what's the problem here? We can still accumulate the score, if GPU is more important, we can increase its weight, it's a relatively better choice not the absolute one.

**Comment by KunWuLuan** [comment]
I realized that I hadn't considered it thoroughly enough before. Maybe a global configuration may be better. 
Maybe the configuration can be like this:
```
strategies:
- requestResources:
  - cpu
  - gpu
  scoringStrategy:
    resources:
    - name: gpu
      weight: 3
    - name: cpu
      weight: 1
    requestedToCapacityRatio:
      shape:
      - utilization: 0
        score: 0
      - utilization: 100
        score: 10
    type: RequestedToCapacityRatio
- requestResources:
  - *
  ...
```
For example for a pod only request cpu, we may only consider the utilization of cpus instead of cpu and gpu because MostAllocated strategy for gpu can influence the score.

**Comment by AxeZhan** [comment]
> From my poor point, how resource being consumed should be a global configuration, if partial pods want binpack, the other parts want spread, then actually no strategy will take effect. It's a hedge result.

@kerthcet Can you show an example? It looks correct to me 🤦.

**Comment by alculquicondor** [comment]
> For example for a pod only request cpu, we may only consider the utilization of cpus instead of cpu and gpu because MostAllocated strategy for gpu can influence the score.

You want Pods that only request CPU to run in non-GPU nodes, correct?

If so, you should be achieving that by setting a taint in the GPU Nodes.

The scoring math already ignores GPUs if the node doesn't provide it https://github.com/kubernetes/kubernetes/blob/11785bb815d58eb553be3a1fa305464c35d860cc/pkg/scheduler/framework/plugins/noderesources/most_allocated.go#L34-L36

So, what is missing?

**Comment by AxeZhan** [comment]
> You want Pods that only request CPU to run in non-GPU nodes, correct?

I think the purpose here is not only let cpu pods running on non-gpu nodes, but also spread them(do a least allocated strategy)

Currently, if we set binpack and taint nodes. Cpu pods can still be scheduled to one same node as they follow binpack strategy for cpu.

**Comment by KunWuLuan** [comment]
> I think the purpose here is not only let cpu pods running on non-gpu nodes, but also spread them(do a least allocated strategy)

Yes. Someone will run spark applications on gpu node to full utilize the gpu node.

**Comment by alculquicondor** [comment]
I see. Can you elaborate on this? https://github.com/kubernetes/kubernetes/issues/119849#issuecomment-1955855020 I don't think I understood how this solves the problem.

**Comment by KunWuLuan** [comment]
I have two ideas to set different policies for different resources:

1. Set  policies for different individual resources, and ignore resources not requested by the Pod when scoring nodes. Configurations can be like this:
```
strategies:
- name: cpu
  weight: 1
  scoringStrategy:
    requestedToCapacityRatio:
      shape:
      - utilization: 100
        score: 0
      - utilization: 0
        score: 10
    type: RequestedToCapacityRatio
- name: gpu
  weight: 2
  scoringStrategy:
    requestedToCapacityRatio:
      shape:
      - utilization: 0
        score: 0
      - utilization: 100
        score: 10
    type: RequestedToCapacityRatio
```
For example, for the pod (requests: 4 cpu), node-a (allocatable: 16 cpu, 2 gpu, allocated: 4 cpu, 1 gpu),  node-b (allocatable: 16 cpu, 2 gpu, allocated: 0 cpu, 0 gpu) , strategy (cpu weight=1, gpu weight=2, least allocated for cpu, most allocated for gpu), we want to place the pod to node-b. We will score node-a and node-b like this: `((1-8/16) * 1) * maxNodeScore=0.5 * maxNodeScore` and `((1-4/16) * 1) * maxNodeScore=0.75 * maxNodeScore`. So that score for node-b will be larger than node-a.
Becides, if we do not ignore the gpu utilization. Socres for node-a and node-b would be like this: 
`((1-8/16) * 1 + (1/2) * 2) * maxNodeScore=1.5 * maxNodeScore` and `((1-4/16) * 1+ 0 * 2) * maxNodeScore=0.75 * maxNodeScore`
If we have same most allocated strategy for cpu and gpu, we will get a larger score for node-a.
And for a gpu pod (requests: 4 cpu, 1 gpu), we will get `2.5 * maxNodeScore` for node-a and `1.75 * maxNodeScore` for node-b. So the gpu pod will still be placed on node-a.

3. Set  policies for different resources set like [  #119849](https://github.com/kubernetes/kubernetes/issues/119849#issuecomment-1955855020) for a more powerful control. We can set like this:
```
strategies:
- requestResources:
  - cpu
  - gpu
  scoringStrategy:
    resources:
    - name: gpu
      weight: 1
    requestedToCapacityRatio:
      shape:
      - utilization: 0
        score: 0
      - utilization: 100
        score: 10
    type: RequestedToCapacityRatio
- requestResources:
  - cpu
  scoringStrategy:
    resources:
    - name: cpu
      weight: 1
    requestedToCapacityRatio:
      shape:
      - utilization: 100
        score: 0
      - utilization: 0
        score: 10
    type: RequestedToCapacityRatio
- requestResources:
  - *
  ...
```
This means if a pod request cpu and gpu, we will just consider gpu with mostAllocated strategy when scoring node and only consider cpu with leastAllocated strategy when scoring node. So that we will ignore the gpu utilization for a gpu-node . Still for the example above, for the cpu pod, we will score node-a and node-b as `((1-8/16) * 1) * maxNodeScore=0.5 * maxNodeScore` and `((1-4/16) * 1) * maxNodeScore=0.75 * maxNodeScore`. For gpu pod, we will score node-a and node-b as `((1) * 1) * maxNodeScore=1 * maxNodeScore` and `((0.5) * 1) * maxNodeScore=0.5 * maxNodeScore`.
