### ISSUE TITLE
Scheduling of the number of pods for kubernetes workload

### ISSUE THREAD

**Issue by dashanji** [kubernetes/kubernetes#119903]
### What would you like to be added?

Suppose we have a workflow including two deployments (one is producer, and one is consumer). The producer deployment has 2 replicas and the consumer deployment has 3 replicas. After the producer deployment is created on the kubernetes cluster, we can get one producer pod deployed on node1, and another pod deployed on node2. After computing, the best scheduling order for producer deployment is `1 replica for node1 and 2 replicas for node2`. It looks like the current [pod-affinity and anti-affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity) is not enough for such case, so I wonder that add some number fields for pod-affinity/anti-affinity will make sense?

### Why is this needed?

This will help the data-intensive workload to achieve fine-grained scheduling to reduce data copying costs.

**Comment by yp969803** [comment]
@claim  I want to work on this issue please assign me

**Comment by yp969803** [comment]
Can anyone guide me how to start working on this issue

**Comment by utkarsh-singh1** [comment]
@yp969803, Anybody is welcome to work on this issue.

You can use `/assign` tag to assign this issue to yourself

**Comment by AxeZhan** [comment]
This issue has not been accepted yet. I think we should wait for sig-scheduling‘s discussion first.

**Comment by yp969803** [comment]
Ok let's wait for it

**Comment by kerthcet** [comment]
Thanks for bring this to the community @dashanji but I can't fully understand what you mean, can you embrace more? Like 

> After computing, the best scheduling order for producer deployment is 1 replica for node1 and 2 replicas for node2

But as you said above, we have 2 replicas for producer, but we have 3 here ... Do you mean the **second replica** here? And how this helps to reduce data copying costs.

One more thing, considering we usually deploy the HPA together with deployment, which will dynamically tune the replicas of deployment, specify the pod number might be problematic ...

**Comment by dashanji** [comment]
@kerthcet, sorry for the poor expression previously. Assume we have a kubernetes cluster with 3 worker nodes and the following consumer yaml is as follows.
```yaml
apiVersion: apps/v1
kind: Job
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 2
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
         image: consumer
```
Assume the job will create one pod on Node1 and another pod on Node2. After the job completed, we can get the data produced on Node1 is around 80%, and the data on Node2 is around 20%. Then we want to create three consumer workers to consume these data.To reduce the , we want to deploy two workers on the .E.g, we create the consumer yaml as follows.
```yaml

```

**Comment by dashanji** [comment]
@kerthcet, sorry for the poor expression previously, I will show a demo next. 

Assume we have a kubernetes cluster with 3 worker nodes and the following consumer yaml is as follows.
```yaml
apiVersion: apps/v1
kind: Job
metadata:
  name: producer
spec:
  selector:
    matchLabels:
      app: producer
  parallelism: 2
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
         image: producer
```
Assume the job will create one pod on Node1 and another pod on Node2. After the job is completed, we can get the data produced on Node1 is around 80%, and the data on Node2 is around 20%. Then we want to create three consumer workers to consume these data average. If three consumer workers are deployed on Node1, then we need to migrate the data on Node2 to the Node1 and the cost is 20%. If three consumer workers are deployed on Node2, the cost is 80%. As a result, the best scheduling order is two workers on Node1 and one worker on Node2.

Based on the current kubernetes affinity/anti-affinity design, it looks like we can't achieve the above target. If there is something I missed, please feel free to correct me. 

Assuming we have a number field, then we can label Node1 with `kubernetes.io/name:node1` and Node2 with `kubernetes.io/name:node2` and apply the following consumer yaml.
```yaml
apiVersion: apps/v1
kind: Job
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  parallelism: 3
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
         image: consumer
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/name
              operator: In
              values:
              - node1
            # indicate the target number of pods that match the expressions
            num: 2
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/name
              operator: In
              values:
              - node2
            # indicate the target number of pods that match the expressions
            num: 1
```

**Comment by kerthcet** [comment]
Based on my understanding, you want the result `the best scheduling order is two workers on Node1 and one worker on Node2` b/c:
- No need to migrate the data across nodes
- Allocate more pods on the nodes with more data for faster data ingesting.

What you present in the yaml is not right because we only accept one `requiredDuringSchedulingIgnoredDuringExecution` for nodeAffinity. So basically what you need is:
- You want the spread scheduling, seems like topology spread
- You have a prefer node where node affinity seems can help

Then maybe we can bind podTopologySpread and nodeAffinity together, you can refer to https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/ for details. Pay attention to the `minDomains`, I guess 2 in your scenario and also the `maxSkew`.

But we can't specify the pod number explicitly. Does this helpful?

**Comment by dashanji** [comment]
@kerthcet Thanks a lot, the doc https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/ makes sense to me.

Based on the doc, we can bind the nodeAffinity and podTopologySpread together as follows.
```yaml
apiVersion: apps/v1
kind: Job
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  parallelism: 3
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
         image: consumer
      affinity:
        topologySpreadConstraints:
          - maxSkew: 2
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app: consumer
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - node1
                  - node2
```

Actually, it can't be specific, as the result could be `two workers on Node1 and one worker on Node2` or `one worker on Node1 and two workers on Node2`. Also, the way is a little tricky and it can't handle such an order of `three workers on Node1, two workers on Node2, one worker on Node3`.

IMHO, maybe we need to extend the current design, I wonder if such a feature would benefit the community.
