### ISSUE TITLE
Cannot connect to service of it's own from inside pod or from other pods on Kubernetes 

### ISSUE THREAD

**Issue by Vivekdjango** [kubernetes/kubernetes#119920]
### What happened?

I am deploying a web service on Kubernetes with there major components

- Web-UI
- API
- Database

Exposed each service using Kubernetes service at the desired port number but except API rest two services are accessible.

API deployment file

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mind-api
  namespace: mind-app
spec:
  selector:
    matchLabels:
      app: mind-api
  replicas: 1
  template:
    metadata:
      labels:
        app: mind-api
    spec:
      containers:
      - name: mind-api
        image: multiscale/mind-airflow:1.1.3
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4000
        env:
        - name: DB_HOST
          value: #####
        - name: DB_NAME
          value: #####
        - name: DB_USER
          value: #####
        - name: DB_PORT
          value: "27017"
        - name: SOURCE_MOUNTED_DRIVE
          value: "/mind-data"
        - name: MIND_HOME
          value: "/mind-data"
        volumeMounts:
            - name: azure-mind-vol
              mountPath: /mind-data
      volumes:
        - name: azure-mind-vol
          persistentVolumeClaim:
            claimName: mind-pvc
      imagePullSecrets:
        - name: regcred

```

API Service 

```
apiVersion: v1
kind: Service
metadata:
  name: web-api-service
  namespace: mind-app
  labels:
    app: mind-api
spec:
  selector:
    app: mind-api
  ports:
    - protocol: "TCP"
      port: 8086
      targetPort: 4000
  type: LoadBalancer

```
```
root@mindairflow:~/mind-api# kubectl get svc
NAME              TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)           AGE
mongo             LoadBalancer   10.0.176.106   ######   27017:31062/TCP   15d
web-api-service   LoadBalancer   10.0.171.39    #####    8086:30571/TCP    41h
web-ui-service    LoadBalancer   10.0.142.99    ######    8084:30909/TCP    16d
```

From API pod
```
/api # curl -i web-api-service:8086
curl: (7) Failed to connect to web-api-service port 8086 after 5 ms: Couldn't connect to server
/api # curl -i 10.0.171.39:8086
curl: (7) Failed to connect to 10.0.171.39 port 8086 after 0 ms: Couldn't connect to server
/api #
/api # curl -i localhost:4000
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, PATCH, DELETE
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers,X-Access-Token,XKey,Authorization
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: text/html; charset=utf-8
Content-Length: 17
ETag: W/"11-uHyBxMeNlIJAQfw7PJuBJSmOJ9E"
Date: Sun, 13 Aug 2023 06:40:15 GMT
Connection: keep-alive
Keep-Alive: timeout=5

Server is running/api #

``


### What did you expect to happen?

API service should be accessible from pod as well as from outside or different pods

### How can we reproduce it (as minimally and precisely as possible)?

Just try deploying the shared file

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
1.27.4
```

</details>

### Cloud provider

<details>
AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
