### ISSUE TITLE
Service- TopologyAwareHintsDisabled

### ISSUE THREAD

**Issue by wt-1611** [kubernetes/kubernetes#119990]
### What happened?

I don't quite understand why this problem has arisen
```bash
$ kubectl describe  svc topic-service
Name:                     topic-service
Namespace:                default
Labels:                   <none>
Annotations:              service.kubernetes.io/topology-aware-hints: auto
Selector:                 mytopic=topic-pod
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.96.240.77
IPs:                      10.96.240.77
Port:                     <unset>  10000/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  30000/TCP
Endpoints:                10.244.0.16:80,10.244.1.22:80,10.244.1.23:80 + 3 more...
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                      Age                     From                       Message
  ----     ------                      ----                    ----                       -------
  Warning  TopologyAwareHintsDisabled  3m32s (x15 over 3m46s)  endpoint-slice-controller  Insufficient Node information: allocatable CPU or zone not specified on one or more nodes, addressType: IPv4
```

### What did you expect to happen?

This is my yaml
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: topic-service
  namespace: default
  annotations:
    service.kubernetes.io/topology-aware-hints: auto

spec:
  type: NodePort
  selector:
    mytopic: topic-pod
  ports:
    - port: 10000
      targetPort: 80
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topic-pod
spec:
  replicas: 6
  selector:
    matchLabels:
      mytopic: topic-pod
  template:
    metadata:
      labels:
        mytopic: topic-pod
    spec:
      containers:
      - name: container-topic
        image: nginx

```
I also label each node
```bash
kubectl get nodes --show-labels | grep zone
node0   Ready    control-plane   8d    v1.26.7   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=node0,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=,topology.kubernetes.io/zone=a
node1   Ready    control-plane   8d    v1.26.7   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=node1,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=,topology.kubernetes.io/zone=a
node2   Ready    control-plane   8d    v1.26.7   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=node2,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=,topology.kubernetes.io/zone=a
node3   Ready    <none>          8d    v1.26.7   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=node3,kubernetes.io/os=linux,topology.kubernetes.io/zone=b
node4   Ready    <none>          8d    v1.26.7   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=node4,kubernetes.io/os=linux,topology.kubernetes.io/zone=b

```

### How can we reproduce it (as minimally and precisely as possible)?

kube-proxy log
```bash
I0817 02:05:14.737427       1 topology.go:171] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0817 02:05:14.738075       1 topology.go:171] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0817 02:05:14.738189       1 topology.go:171] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0817 02:05:14.738310       1 topology.go:171] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0817 02:05:14.738447       1 topology.go:171] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0817 02:05:14.738645       1 topology.go:171] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
I0817 02:05:14.738740       1 topology.go:171] "Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint"
```

### Kubernetes version

v1.26.7

### Cloud provider

Self-built environment

### OS version

Rocky Linux release 8.7 (Green Obsidian)

### Container runtime (CRI) and version (if applicable)

containerd 1.6.22
