### ISSUE TITLE
NoSchedule related tolerations are not working with kustomize

### ISSUE THREAD

**Issue by vinibali** [kubernetes/kubernetes#120098]
### What happened?

We have a project built with Kustomize.
The small components are using kutomization templates, in which we are setting most of the properties.
The pods seem to have the correct key values pair for the tolerations, however some of the pods are still deployed to the master node(s).
According to the template and the pod's output, multiple K8s clusters are getting the parameter. We experience the same using real and kind clusters.
The node labels and the pod outputs are correct, but I also tried to add the key in a different form.
What could go wrong here?
I can see exactly the same format in other pods from different projects and those are working fine.
Snippet from the pod's output.
```
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/master
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/control-plane
    operator: Exists
```

### What did you expect to happen?

The pods seem to have the correct key values pair for the tolerations, however some of the pods are still deployed to the master node(s).

### How can we reproduce it (as minimally and precisely as possible)?

You can use kusomize build with that template:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${REMOTE_IMAGE}
  newName: ${FINAL_REGISTRY}/${FINAL_REPOSITORY_BOOTSTRAP}/${FINAL_IMAGE_NAME_BOOTSTRAP}
  newTag: ${FINAL_IMAGE_TAG_BOOTSTRAP}
patches:
- target:
    kind: Deployment
    labelSelector: "cluster.x-k8s.io/provider=manager"
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/1
      valueFrom: --metrics-bind-addr=localhost:8080
      value: --metrics-bind-addr=0.0.0.0:8080
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: manager
    namespace: system
  spec:
    replicas: 2
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8080"
          prometheus.io/scheme: http
          prometheus.io/scrape: "true"
        labels:
          app.kubernetes.io/name: manager
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: cluster.x-k8s.io/provider
                  operator: In
                  values:
                  - bootstrap-kubeadm
                - key: control-plane
                  operator: In
                  values:
                  - controller-manager
              topologyKey: kubernetes.io/hostname
        containers:
        - name: manager
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: healthz
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /readyz
              port: healthz
              scheme: HTTP
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 7m
              memory: 100Mi
            limits:
              cpu: 10m
              memory: 120Mi
        - args:
          - 'manager'
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_UID
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.uid
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: ${FINAL_REGISTRY}/${FINAL_REPOSITORY_TIMESTAMP_TRANSFORMER}/${FINAL_IMAGE_NAME_TIMESTAMP_TRANSFORMER}:${FINAL_IMAGE_TAG_TIMESTAMP_TRANSFORMER}
          imagePullPolicy: ${ADDED_IMAGES_PULL_POLICY}
          name: timestamp-transformer
          volumeMounts:
          - mountPath: /var/log/pods
            name: kubernetes-containers
        imagePullSecrets:
        - name: ${IMAGE_PULL_SECRET}
        tolerations:
        - key: node.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/test
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        volumes:
        - hostPath:
            path: /var/log/pods
            type: ""
          name: kubernetes-containers
resources:
- bootstrap-components.yaml
```

### Anything else we need to know?

https://github.com/kubernetes-sigs/kustomize/issues/5235

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.3
WARNING: version difference between client (1.28) and server (1.26) exceeds the supported minor version skew of +/-1
WARNING: version difference between client (1.28) and server (1.26) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
* Private K8s solution
* kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Kustomize version: v4.5.4
Kustomize version: v5.1.0
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
