### ISSUE TITLE
Evicting Pod due to emptyDir violation returns as Completed

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#120182]
### What happened?

If a Pod is evicted because it violates EmptyDir storage limits, your pod will be evicted but it will be marked as completed.  

### What did you expect to happen?

I would expect the pod to say `terminating` or `Failed` rather than completed.  For a Job, the controller will take this Pod to be succeeded even though it was evicted.  

### How can we reproduce it (as minimally and precisely as possible)?

Run the K8 job below.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: emptydir-job
spec:
  backoffLimit: 1  # Number of retries before considering the Job as failed
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: emptydir-container
          image: nginx
          volumeMounts:
            - name: emptydir-volume
              mountPath: /data
      volumes:
      - name: emptydir-volume
        emptyDir:
         sizeLimit: 500Mi
```

I exec into this pod and run `fallocate -l 1 Gb /data/dummy.txt`

If you wait a few seconds, the pod will be evicted.

### Anything else we need to know?

It doesn't seem to matter if this is a naked pod or not.  For a job, this is especially bad as it would be considered a successful run.  

### Kubernetes version

Current main.

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
Fedora 38

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRIO 
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kannon92** [comment]
This issue may be related: https://github.com/kubernetes/kubernetes/issues/118310

**Comment by kannon92** [comment]
@mimowo and @alculquicondor I found it curious that we don't have a `Disruption` condition for this case.  

I notice that there was a condition for `Disruption` on eviction but evictions due to `localVolumes` are missing here.  

https://github.com/kubernetes/kubernetes/blob/0e86fa5115cb79a04bdb949d135e35a31ce806f2/pkg/kubelet/eviction/eviction_manager.go#L466

Looks like these three cases would trigger eviction but don't have a disruption added.

**Comment by mrunalp** [comment]
cc: @bobbypage

**Comment by bobbypage** [comment]
I believe we should be setting a disruption target condition for ephemeral storage eviction, it should go through here - https://github.com/kubernetes/kubernetes/blob/0e86fa5115cb79a04bdb949d135e35a31ce806f2/pkg/kubelet/eviction/eviction_manager.go#L390-L396

**Comment by bobbypage** [comment]
Hmm, this might be a missed case. I see we add the DisruptionTarget condition here - https://github.com/kubernetes/kubernetes/blob/0e86fa5115cb79a04bdb949d135e35a31ce806f2/pkg/kubelet/eviction/eviction_manager.go#L389-L397.

But for emptyDir eviction, it will call `evictPod` here - https://github.com/kubernetes/kubernetes/blob/0e86fa5115cb79a04bdb949d135e35a31ce806f2/pkg/kubelet/eviction/eviction_manager.go#L504-L509 without setting the condition.

cc @mimowo

**Comment by mimowo** [comment]
@bobbypage @kannon92 Regarding the DisruptionTarget condition this is WAI. The condition is added when the pod is disrupted due to external factors - the eviction manager needs to reclaim memory / disk space. The pod itself does not exceed the limits. 

In the second case from the [comment](https://github.com/kubernetes/kubernetes/issues/120182#issuecomment-1693956635) it is the pod itself that exceeds the limits. In that case we considered adding the `ResourceExceeded` condition, but it was tricky to make it fully correct as we intended to reuse the same condition for OOM killing and memory limits. In particular, it is not clear if OOM killed container exceeded its limits, or it was oom killed due to memory pressure. Thus, we left adding the `ResourceExceeded` condition as a potential follow up.

FYI @alculquicondor

**Comment by mimowo** [comment]
Regarding the `Completed` status - what is the exit code for the container in this case? If the exit code is `0` then indeed it might be related to https://github.com/kubernetes/kubernetes/issues/118310, but in this case the exit code was inconsistent with the pod status in the first place (failed pod with container with exit code 0). This might be indeed breaking, so we are going to keep track of the issue.

Btw. I didn't reproduce this locally on 1.27.3 with the following commands:
1. `kubectl create -f test.yaml`
2. `kubectl exec pod/emptydir-job-jbrwg -- fallocate -l 1GiB /data/dummy.txt`

Then I get:
```sh
kubectl get pods -oyaml
```
```yaml
    containerStatuses:
    - image: nginx
      name: emptydir-container
      ...
      state:
        terminated:
          exitCode: 137
          message: The container could not be located when the pod was terminated
          reason: ContainerStatusUnknown
          ...
    message: 'Usage of EmptyDir volume "emptydir-volume" exceeds the limit "500Mi". '
    phase: Failed
    reason: Evicted
```
Can you test it on a released version?
