### ISSUE TITLE
Numerous incorrect pods caused by specifying node names

### ISSUE THREAD

**Issue by wujunwei** [kubernetes/kubernetes#120160]
### What happened?

When I specifying node names in deployment like below.
```yaml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: node1
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:1.14.3
        ports:
        - containerPort: 80
```
 Something terrible has happened！
SO MANY PODS WAS CREATED!!! until I change the replicas to zero , 131 pods were created and remained, and their status was `failed`
```
  phase: Failed
  message: 'Pod was rejected: Predicate NodePorts failed'
  reason: NodePorts
  startTime: '2023-08-24T14:48:37Z'
```
It seems that pod 's pod was used (previous pod) in target node.

I think we can change the logic of the RS controller to solve this problem, such as not filtering failed pods or determining the specific reason for the failure before deciding when to create a new pod.

I would be happy to provide a PR if our discussion came to an outcome : )

### What did you expect to happen?

failed immediately (no not create so many pods ) or give a hint or warning shows the state that can not be continue handing

### How can we reproduce it (as minimally and precisely as possible)?

1. create deployment with nodeName and hostNetwork,set .spec.replicas greater than one.
   ```
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
      labels:
        app: nginx
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          nodeName: adam-pro
          hostNetwork: true
          containers:
          - name: nginx
            image: nginx:1.14.3
            ports:
            - containerPort: 80

   ```
2. Waiting for a surge in the number of pods.
    ```
    kubectl get pod --watch
    ```

### Anything else we need to know?

I have try it in many versions of k8s (1.24,1.25, 1.28), all  meet same situation.

When I look into the code,I found `ReplicaSetController` will ignore pod whose status is Failed and create new one.

https://github.sheincorp.cn/kubernetes/kubernetes/blob/1d52fb2806e0af468b8b0185f9ba3721d1d2fb3b/pkg/controller/controller_utils.go#L949-959

```go
func IsPodActive(p *v1.Pod) bool {
	return v1.PodSucceeded != p.Status.Phase &&
		v1.PodFailed != p.Status.Phase &&
		p.DeletionTimestamp == nil
}
```
And scheduler's plugin `NodePorts` will be used in kubelet(pkg/kubelet/lifecycle/predicate.go)and `kubelet ` will  set pod's status to fail, as a result `ReplicaSetController` will create pods on and on !
```go
	if !nodeports.Fits(pod, nodeInfo) {
		admissionResults = append(admissionResults, AdmissionResult{Name: nodeports.Name, Reason: nodeports.ErrReason})
		if !includeAllFailures {
			return admissionResults
		}
	}
```
https://github.sheincorp.cn/kubernetes/kubernetes/blob/master/pkg/scheduler/eventhandlers.go#L583-L614

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
```

</details>

### Cloud provider

<details>
cluster by kubeadm
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# PRETTY_NAME="Ubuntu 22.04.3 LTS"
# NAME="Ubuntu"
# VERSION_ID="22.04"
# VERSION="22.04.3 LTS (Jammy Jellyfish)"
# VERSION_CODENAME=jammy
# ID=ubuntu
# ID_LIKE=debian
# HOME_URL="https://www.ubuntu.com/"
# SUPPORT_URL="https://help.ubuntu.com/"
# BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
# PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
# UBUNTU_CODENAME=jammy

$ uname -a
# Linux  6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>

```
containerd --version

containerd github.com/containerd/containerd v1.6.23 b69f1ad231b6d87eeb30504398075a92d615e83e
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
containerd cni 
</details>
