### ISSUE TITLE
Old version pods are created when deploying a new version with more replicas - Reopen old issue?

### ISSUE THREAD

**Issue by nagygergo** [kubernetes/kubernetes#120157]
### What happened?

 Same issue as #105395, can't reopen it.

We've observed this issue and it was causing issues when we wanted to change the version of the software deployed while also scaling out the deployment. We have some data store configuration and database schema update scripts implemented as init containers. In our case needed to do a non backward compatible configuration upgrade, so the old version of the service was not able to work with the new config, and the new version of the service was not able to work with the new config.

The following happened:

1. Updated deployment to have 2 replicas instead of 1. (default maxUnavailable and maxSurge configs)
2. New ReplicaSet created with 1 podv2. Old ReplicaSet scaled up to 2 podv1-s.
3. podv2 updated data store config.
4. new podv1 updated data store config.
5. Eventually podv2 failed liveness probe, because couldn't contact data store correctly.
6. RollingUpdate never finished.

### What did you expect to happen?

Old replicaset is not scaled out, but stays on it's previous size. The current behaviour is trying to saturate the new replicacount, even if with old pods, while doing rolling upgrade.
As the old replicaset is connected to the old intent of the deployment, there is no guarantee that it can support scaling out to the size described in the new deployment.

### How can we reproduce it (as minimally and precisely as possible)?
Taken from #105395
#1. Provision a simple nginx deployment with 2 replicas using the below manifest.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    release: testdeploy
    app: nginx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 30%
  selector:
    matchLabels:
      release: testdeploy
      app: nginx
  template:
    metadata:
      labels:
        release: testdeploy
        app: nginx
      annotations:
    spec:
      imagePullSecrets:
      tolerations:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  release: testdeploy
                  app: nginx
      containers:
        - name: web
          image: "nginx:1.20"
```
The deployment works as expected.
```
 kubectl -n test-elasticsearch get pods
NAME                     READY   STATUS    RESTARTS   AGE
nginx-844bf5fdb8-vn72z   1/1     Running   0          15s
nginx-844bf5fdb8-w45ww   1/1     Running   0          15s
```
#2. Update the deployment by just changing the image version and also increase the replicas to 3 as shown below
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    release: testdeploy
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 30%
  selector:
    matchLabels:
      release: testdeploy
      app: nginx
  template:
    metadata:
      labels:
        release: testdeploy
        app: nginx
      annotations:
    spec:
      imagePullSecrets:
      tolerations:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  release: testdeploy
                  app: nginx
      containers:
        - name: web
          image: "nginx:1.21"
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-14T09:49:08Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
K8s on bare metal, internally built
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
