### ISSUE TITLE
podAntiAffinity in a daemonset is not accepted , k8s versions > 1.27.0 

### ISSUE THREAD

**Issue by abhinov-netapp** [kubernetes/kubernetes#120189]
### What happened?

During one of our tests with daemonsets, we find new pods being scheduled despite having a podAntiAffinity rule set into the daemonset.

Here's our test case;
1. We installed older version of our app.
2. We apply a finalizer to a pod( rlinux-xs84n in this case).
3. We upgrade(rolling update) to latest version of the app.(no change in Kubernetes version).
4. At this point, rlinux-xs84n pod gets stuck in 'Terminating'.
5. As a new daemonset spins up, it succeeds in scheduling new pods on the same node( xxx.194 in this case).

Actual output:
`
NAME         READY   STATUS      RESTARTS   AGE     IP         NODE      NOMINATED NODE   READINESS GATES
rlinux-8p5qt             2/2     Running       0          3h47m   xxx.194   vm7002   <none>           <none>
rlinux-b6z99             2/2     Running       0          3h47m   xxx.105   vm8001   <none>           <none>
rlinux-hjpj7             2/2     Running       0          3h47m   xxx.42    vm7001   <none>           <none>
rlinux-xs84n             0/2     Terminating   0          3h52m   xxx.194   vm7002   <none>           <none>`

**This behaviour is observed in K8S; 1.27.0 - 1.28 versions
This behaviour is not observed is K8S; 1.23, 1.24, 1.25 and 1.26 versions**

### What did you expect to happen?

Expected output(A pod scheduled by the new DS should have been 'Pending' on the same node 'vm7002'):
`
NAME         READY   STATUS      RESTARTS   AGE     IP         NODE      NOMINATED NODE   READINESS GATES
rlinux-8p5qt             2/2     Pending       0          3h47m   xxx.194   vm7002   <none>           <none>
rlinux-b6z99             2/2     Running       0          3h47m   xxx.105   vm8001   <none>           <none>
rlinux-hjpj7             2/2     Running       0          3h47m   xxx.42    vm7001   <none>           <none>
rlinux-xs84n             0/2     Terminating   0          3h52m   xxx.194   vm7002   <none>           <none>`

Please share a workaround to make the pod scheduling (like above) and let us know if there were any similar field issues were noticed earlier.

### How can we reproduce it (as minimally and precisely as possible)?

Steps could be similar to that of our test.

### Anything else we need to know?

The daemonset has a podAntiAffinity like below:
```
"spec": {
                        ...
                            "podAntiAffinity": {
                                "requiredDuringSchedulingIgnoredDuringExecution": [
                                    {
                                        "labelSelector": {
                                            "matchExpressions": [
                                                {
                                                    "key": "app",
                                                    "operator": "In",
                                                    "values": [
                                                        "node.rlinux.app.io"
                                                    ]
                                                }
                                            ]
                                        },
                                        "topologyKey": "kubernetes.io/hostname"
                                    }
                                ]
                            }
                        }
```

Also daemonset has a rollingUpdate strategy:

```
"updateStrategy": {
                    "rollingUpdate": {
                        "maxSurge": 0,
                        "maxUnavailable": 1
                    },
                    "type": "RollingUpdate"
                }
```

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"xyz", GitTreeState:"clean", BuildDate:"2023-04-11T17:10:18Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"xtz", GitTreeState:"clean", BuildDate:"2023-08-24T00:42:11Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.19
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
kube-flannel
</details>

**Comment by aojea** [comment]
/sig scheduling
/sig apps

I

**Comment by kerthcet** [comment]
Let me take an experiment, kube-scheduler should take terminating pods into consideration.

**Comment by kerthcet** [comment]
Thanks @tksm for the detailed investing and Aldo pointed out the key point. So after https://github.com/kubernetes/kubernetes/commit/3d68f362c372ea2af5165198c0c60f19ebc60a3f, Pod will be marked as succeed finally, then scheduler will ignore the pod, that's the phenomenon currently. But we should fix the https://github.com/kubernetes/kubernetes/issues/120207 to prevent confusion.

However, since pod is protected by the finalizer, should we mark the pod succeeded directly rather than waiting for the finalizer being removed? But I have no *real sense* yet ..

**Comment by alculquicondor** [comment]
From the slack thread, the Pod status of the Terminating pod is the following:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-28T10:07:59Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-28T10:10:32Z"
    message: 'containers with unready status: [xyz driver-registrar]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-28T10:10:32Z"
    message: 'containers with unready status: [xyz driver-registrar]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-28T10:07:59Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://cecc646a749583aeb3efe51b1e2c4abe00be969c48865e22df2aeb549e131c52
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0
    imageID: registry.k8s.io/sig-storage/csi-node-driver-registrar@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183
    lastState: {}
    name: driver-registrar
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://cecc646a749583aeb3efe51b1e2c4abe00be969c48865e22df2aeb549e131c52
        exitCode: 0
        finishedAt: "2023-08-28T10:10:04Z"
        reason: Completed
        startedAt: "2023-08-28T10:08:00Z"
  - containerID: containerd://efc36728996678ee808dada741c1514489ed77316838b6fde8366c79da5e461b
    image: xyz
    imageID: xyz
    lastState: {}
    name: t-main
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://efc36728996678ee808dada741c1514489ed77316838b6fde8366c79da5e461b
        exitCode: 0
        finishedAt: "2023-08-28T10:10:30Z"
        reason: Completed
        startedAt: "2023-08-28T10:08:00Z"
  hostIP: 10.193.161.74
  phase: Running
  podIP: 10.193.161.74
  podIPs:
  - ip: 10.193.161.74
  qosClass: BestEffort
  startTime: "2023-08-28T10:07:59Z"
```

So two questions:
- Why is this Pod not marked as Failed, if it has a deletionTimestamp and the containers are terminated?
- Why would the Daemonset create a replacement Pod, if it's still running and `maxSurge == 0`?
