### ISSUE TITLE
Desired behavior of a startup failed restartable init container in a pod with `restartPolicy` set to `Never`

### ISSUE THREAD

**Issue by gjkim42** [kubernetes/kubernetes#120234]
When we use v1.28.0 with `SidecarContainers` feature,
(restartable init container = init container with container `restartPolicy` of `Always`)

a restartable init container, in a pod with `restartPolicy` set to `Never`, restarts when its `startupProbe` fails.

This is inconsistent with the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/753-sidecar-containers#proposal),

> During the sidecar startup stage the restart behavior will be similar to init containers. If Pod restartPolicy is Never, sidecar container failed during startup will NOT be restarted and the whole Pod will fail. If Pod restartPolicy is Always or OnFailure, it will be restarted.

What should happen if a restartable init container in a pod with `restartPolicy` set to `Never` fails the `startupProbe`?

```yaml
apiVersion: batch/v1    
kind: Job    
metadata:    
  name: test-restartable-init    
  namespace: default    
spec:    
  template:    
    spec:    
      initContainers:    
      - command:    
        - sleep    
        - infinity    
        image: ubuntu    
        imagePullPolicy: Always    
        name: restartable-init    
        restartPolicy: Always    
        startupProbe:    
          exec:    
            command:    
              - "/bin/false"    
      containers:    
      - command:    
        - sleep    
        - 60s    
        image: ubuntu                                                                                                                                                                                       
        imagePullPolicy: Always                                                                                                                                                                             
        name: regular                                                                                                                                                                                          
      restartPolicy: Never
```

We may need a way for a job to recreate a pod (not restarting a container) if its restartable init container fails the startup.

Right now, I have three ways in mind.

1. Original KEP: Let a restartable init container not restart if it fails the startup and the pod's `restartPolicy` is `Never`.
1. Current implementation: We don't need this use case.
1. Introduce another `ContainerRestartPolicy` called `AlwaysAfterStartUp`.

cc @SergeyKanzhelev @tzneal @matthyx
