### ISSUE TITLE
ValidatingAdmissionPolicy: variable expression type not recognized as return type in expression that evaluates the variable

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#120239]
### What would you like to be added?

Variables field is added to ValidatingAdmissionPolicy in 1.28. Currently the usage of variables would expect a operator associated. 
e.g. (thanks to Mariam Fahmy for raising the issue)
```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "chech-deployment-labels"
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments"]
  variables:
    - name: environment
      expression: "has(object.metadata.labels) && 'env' in object.metadata.labels && object.metadata.labels['env'] == 'prod'"
  validations:
    - expression: "variables.environment"
      message: "Deployment labels must be env=prod"
```
Above will fail with error: 
```
The ValidatingAdmissionPolicy "chech-deployment-labels" is invalid: spec.validations[0].expression: Invalid value: "variables.environment": must evaluate to bool
```
Meanwhile the `- expression: "variables.environment == true"` will pass.

The reason is when variables be evaluated to non dyn type(like bool or string), it will require special handling(like casting) since we use dyn type everywhere. 

### Why is this needed?

It might confuse user.
