### ISSUE TITLE
 cpuset.cpu changed for Guaranteed pod when use cpumanager static policy

### ISSUE THREAD

**Issue by zhoushuke** [kubernetes/kubernetes#120230]
### Which jobs are failing?

when I change kubelet cpumanager from none to static and do some testing for guaranteed pod ,I found some interesting things.

### Which tests are failing?

I deploy a simple pod with requests and limits all is 2cpu, after that.

kubelet cpu_manager_state like:
```bash
{"policyName":"static","defaultCpuSet":"0-9,11-77,79-85,87-151","entries":{"c5eb47f4-a9a7-4682-ac98-4f2d187e3994":{"busybox":"10,86"}}, "checksum":3322146737}
```

look so good, and cpu is binding to 10 and 86,
I found the cgroup file cpuset.cpus(/sys/fs/cgroup/cpuset/kubepods.slice/kubepods-podxxx.slice/docker-yyy.scope/cpuset.cpus
), when pod created, the file content is also 10, 86, but this context changed to 2-75,78-151 after for a while(one seconds, maybe..), and  exec into the container and cat /proc/1/task/1/status,found Cpus_allowed_list:	2-75,78-151(after I did multiple test and found it also change from 10,86 to  2-75,78-151) 
it seems there is a reconcile  to change this .
I did many test and get the same result. after I search kubelet code about cpumanager and no ideal why this happend.

2-75,78-151 is os cpu affinity.

### Since when has it been failing?

changed cpumanager from node to static

### Anything else we need to know?

kubernetes: v1.22.13
docker: 20.10.18
kubeletconfig:
topologyManagerPolicy: best-effort
topologyManagerScope: pod
cpuManagerPolicy: static

### Relevant SIG(s)

/sig

**Comment by gjkim42** [comment]
@zhoushuke 
Could you test this with the latest version? I think 1.22 is not supported by the community now.

**Comment by zhoushuke** [comment]
> @zhoushuke 
> 
> Could you test this with the latest version? I think 1.22 is not supported by the community now.

sorry, maybe least version works well, but because it's private production environment,so hardly to upgrade,so any thoughts to trace this issue,tks?

**Comment by ffromani** [comment]
Hi! how do you kubelet configuration and pod spec looks like? Specifically, does this happen for Guaranteed QoS pods?

**Comment by zhoushuke** [comment]
@ffromani 
this is kubeletconfig content:
```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 30s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 10s
    cacheUnauthorizedTTL: 10s
cgroupDriver: systemd
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
cpuManagerPolicy: static
cpuManagerReconcilePeriod: 10s
evictionHard:
  imagefs.available: 10%
  memory.available: 8Gi
  nodefs.available: 5%
evictionPressureTransitionPeriod: 3m0s
failSwapOn: false
fileCheckFrequency: 20s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 20s
imageMinimumGCAge: 2m0s
kind: KubeletConfiguration
kubeReserved:
  cpu: 2000m
  memory: 8Gi
logging: {}
maxPods: 250
memorySwap: {}
nodeStatusReportFrequency: 1m0s
nodeStatusUpdateFrequency: 10s
rotateCertificates: true
runtimeRequestTimeout: 2m0s
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
systemReserved:
  cpu: 10000m
  memory: 32Gi
topologyManagerPolicy: best-effort
topologyManagerScope: pod
volumeStatsAggPeriod: 1m0s
```
and some cmdline arguments passed to  kubelet
--fail-swap-on=false --reserved-cpus=0-9,76,77
 
the pod spec like:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-2g-xx
  namespace: test 
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      nodeName: kc32-g6
      containers:
      - image: harbor.pl/bj/ubuntu:latest
        imagePullPolicy: IfNotPresent
        name: busybox
        command:
        - sh
        - -c
        - |
          sleep infinity
        resources:
          requests:
            cpu: "2"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "1Gi"
      restartPolicy: Never

```
it's a Guaranteed QoS shown in pod status after deployed it.

does this happen for Guaranteed QoS pods?
as static policy works for guaranteed pod, so other qos pod works fine, use CFS.
