### ISSUE TITLE
Node Graceful Shutdown is taking too long

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#120271]
### What happened?

Pods usually have a 30s grace period when they do not define a terminationGracePeriodSeconds for termination. When NodeGraceful Shutdown is enabled the grace period gets set to the ShutdownGracePeriodSeconds, which is configured by the Kubelet. Let's say the Kubelet is configured with a ShutdownGracePeriodSeconds of 65 minutes. This means that pods without a termination grace period can terminate with a grace period of 65 minutes.

The Kubelet configuration includes:

```
...
shutdownGracePeriod: 65m
shutdownGracePeriodCriticalPods: 35m
```

alternatively, this alternate configuration does not work either:
```
...
shutdownGracePeriodByPodPriority:
  - priority: 0
    shutdownGracePeriodSeconds: 300
  - priority: 10000
    shutdownGracePeriodSeconds: 600
  - priority: 2000000000
    shutdownGracePeriodSeconds: 1200
  - priority: 2000001000
    shutdownGracePeriodSeconds: 1200
```

The Kubernetes E2E tests timeout when this configuration is applied as the default, since many E2E tests and pods do not set a terminationGracePeriodSeconds field.

The fix is to set the [graceful termination](https://github.com/kubernetes/kubernetes/blob/dd6bc2548e008e5d49a62dff73af1aa18712a1cb/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L368C1-L368C1) to 30 seconds by default, and allow the shutdown code to override the [grace period](https://github.com/kubernetes/kubernetes/blob/dd6bc2548e008e5d49a62dff73af1aa18712a1cb/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L372) if the pod sets one.

### What did you expect to happen?

I expect pods without a terminationGracePeriodSeconds to be terminated after 30 seconds with a large `shutdownGracePeriod` set within Kubelet.

### How can we reproduce it (as minimally and precisely as possible)?

Configure Kubelet with this config:

```
...
shutdownGracePeriod: 65m
shutdownGracePeriodCriticalPods: 35m
```

Create a pod without a terminationGracePeriodSeconds and observe the 65m grace period used.

### Kubernetes version

1.24,1.25,1.26,1.27,1.28

### Cloud provider

<details>
All
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
