### ISSUE TITLE
Job Failed StartTime is 1970?

### ISSUE THREAD

**Issue by agardnerIT** [kubernetes/kubernetes#120331]
### What happened?

I wrote a deliberately failing Job. It should cause a `StartError`.

The problem is that the container start time is reported as '1970-01-01T00:00:00Z' whereas the `finishedAt` time is correct.

```
{
  'terminated': {
    'exitCode': 128,
    'reason': 'StartError',
    'message': 'failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "sleepx": executable file not found in $PATH: unknown',
    'startedAt': '1970-01-01T00:00:00Z',
    'finishedAt': '2023-09-01T01:58:59Z',
    'containerID': 'containerd://b9833afeb22eac8639dd1a8890279525b14d25faefd0b690fe1b32e79aee8f9f'
  }
}
```

### What did you expect to happen?

The correct `startedAt` time is given. Since k8s clearly knows when "now" is, is it really logical to have a start time almost 50 years ago?

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: batch/v1
kind: Job
metadata:
  name: job1e
  namespace: default
  annotations:
    tracepusher/collector: "http://localhost:4318"
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - image: alpine:latest
        command: 
          - "sleeps"
        args:
          - "1"
        imagePullPolicy: IfNotPresent
        name: first
```

Then `kubectl get pods -l job-name=job1e`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by AxeZhan** [comment]
Well I guess it's because we don't treat a `StartError` job as started, so it will not have a `StartedAt` field(1970-01-01T00:00:00Z is a null date). But I'm not a job expert.
/wg batch

**Comment by kannon92** [comment]
Looking at this again, I don't think this would be an issue with Job Controller.  The field you are referring to is present in the podspec.  

I was unable to reproduce this on current main (1.29).  Can you see if you can reproduce this on a newer version?  

I tried running your job spec but it complained about restartPolicy not being specified.  Once I made that modification, it was failing but both PodSpec and Job have the correct startTime.

**Comment by Ithrael** [comment]
> Looking at this again, I don't think this would be an issue with Job Controller. The field you are referring to is present in the podspec.
> 
> I was unable to reproduce this on current main (1.29). Can you see if you can reproduce this on a newer version?
> 
> I tried running your job spec but it complained about restartPolicy not being specified. Once I made that modification, it was failing but both PodSpec and Job have the correct startTime.

kubectl version
<img width="575" alt="image" src="https://github.com/kubernetes/kubernetes/assets/38208715/e05f3e0f-7e8d-4868-89d8-4654d5a02826">

The latest version still has this issue. Here is the yml I used for testing.
```
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['xxx', '-c', 'echo "Hello"']
      restartPolicy: Never
```

**Comment by lowang-bh** [comment]
I also reproduced it.
```
    state:
      terminated:
        containerID: containerd://94516d5164f81c7eac1967db790e79c8fd9d0ea3e9ab49eeab837a417ea24621
        exitCode: 128
        finishedAt: "2023-09-02T06:26:05Z"
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          exec: "xxx": executable file not found in $PATH: unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z"
```
```
version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2"
```

**Comment by kannon92** [comment]
Ah. Thank you.  I don't see this behavior with CRIO actually.

Just to clarify, in  this state, what is the StartTime for Job Controller?  And what is the startedAt in the podspec?

**Comment by lowang-bh** [comment]
job
```yaml
status:
  failed: 3
  ready: 0
  startTime: "2023-09-02T13:41:01Z"
  uncountedTerminatedPods: {}
```
pod
```yaml
  phase: Failed
  podIP: 10.244.1.18
  podIPs:
  - ip: 10.244.1.18
  qosClass: BestEffort
  startTime: "2023-09-02T13:41:01Z"
```
container
```yaml
    state:
      terminated:
        containerID: containerd://7ed07452ecdef26f2ce45a2f4a5b0e32c35cf5bee94b11b6c368945dd0771895
        exitCode: 128
        finishedAt: "2023-09-02T13:41:05Z"
        message: 'failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          exec: "xxx": executable file not found in $PATH: unknown'
        reason: StartError
        startedAt: "1970-01-01T00:00:00Z
```

**Comment by kannon92** [comment]
Thank you! So can you reproduce with other controllers? Or just a pod?

seems to me that this would not be related to job controller at all.

/sig node

**Comment by Ithrael** [comment]
> Thank you! So can you reproduce with other controllers? Or just a pod?
> 
> seems to me that this would not be related to job controller at all.
> 
> /sig node

Yes, this is a pod issue and is not related to the job. When a pod is in a 'startError' state, this happens. It seems that in this state, the 'startedAt' of the pod is not assigned. I am looking into this issue.
<img width="591" alt="image" src="https://github.com/kubernetes/kubernetes/assets/38208715/9fadd404-8e5e-4516-a25c-98c897eee8ac">
```
apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - command:
    - xxx
    - -c
    - echo "Hello"
    image: busybox
    name: hello
  restartPolicy: Never
```
you can reproduce the issue with this  pod yml
