### ISSUE TITLE
service nodeport cannot be released promptly.

### ISSUE THREAD

**Issue by lojies** [kubernetes/kubernetes#120536]
### What happened?

Why PatchService method is used for deleting finalizers in cloud-controller-manager,
[https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L922 ](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L922 )
```golang
// removeFinalizer patches the service to remove finalizer.
func (c *Controller) removeFinalizer(service *v1.Service) error {
	if !servicehelper.HasLBFinalizer(service) {
		return nil
	}
	// Make a copy so we don't mutate the shared informer cache.
	updated := service.DeepCopy()
	updated.ObjectMeta.Finalizers = removeString(updated.ObjectMeta.Finalizers, servicehelper.LoadBalancerCleanupFinalizer)

	klog.V(2).Infof("Removing finalizer from service %s/%s", updated.Namespace, updated.Name)
	_, err := servicehelper.PatchService(c.kubeClient.CoreV1(), service, updated)
	return err
}
``` 
This method updates with service/status,
```golang
// PatchService patches the given service's Status or ObjectMeta based on the original and
// updated ones. Change to spec will be ignored.
func PatchService(c corev1.CoreV1Interface, oldSvc, newSvc *v1.Service) (*v1.Service, error) {
	// Reset spec to make sure only patch for Status or ObjectMeta.
	newSvc.Spec = oldSvc.Spec

	patchBytes, err := getPatchBytes(oldSvc, newSvc)
	if err != nil {
		return nil, err
	}

	return c.Services(oldSvc.Namespace).Patch(context.TODO(), oldSvc.Name, types.StrategicMergePatchType, patchBytes, metav1.PatchOptions{}, "status")

}
```
[https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/service/helpers/helper.go#L132](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/service/helpers/helper.go#L132)
It seems to go unnoticed by the API server, resulting in the API server being unaware when the finalizer field on the service is deleted, leading to a delay in the release of service-related NodePorts.

### What did you expect to happen?

service nodeport be released promptly when service is deleted.

### How can we reproduce it (as minimally and precisely as possible)?
create a loadblancer service with nodeport seted,then delete it and recreate.
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    testid: svc-not-tolerate-unready-5d178209-1284-4cd3-9790-ba6118c5e1ba
  name: svc-not-tolerate-unready
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30999
  selector:
    testid: svc-not-tolerate-unready-5d178209-1284-4cd3-9790-ba6118c5e1ba
  sessionAffinity: None
  type: LoadBalancer
```
```shell
[root@test-1:~]$ kubectl apply -f svc-nodeport.yaml 
The Service "svc-not-tolerate-unready" is invalid: spec.ports[0].nodePort: Invalid value: 30999: provided port is already allocated

```
cloud-controller-manager add  a finalizer on service. delete this service and then cloud-controller remove finalizer. but nodeport is not released when service deleted.
ref #87217

i change like this, it seems like releasing nodeport when service is deleted
:
[https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L922 ](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L922 )
```golang
// PatchService patches the given service's Status or ObjectMeta based on the original and
// updated ones. Change to spec will be ignored.
func PatchService(c corev1.CoreV1Interface, oldSvc, newSvc *v1.Service) (*v1.Service, error) {
	// Reset spec to make sure only patch for Status or ObjectMeta.
	newSvc.Spec = oldSvc.Spec

	patchBytes, err := getPatchBytes(oldSvc, newSvc)
	if err != nil {
		return nil, err
	}
	if oldSvc.DeletionTimestamp != nil {
		return c.Services(oldSvc.Namespace).Patch(context.TODO(), oldSvc.Name, types.StrategicMergePatchType, patchBytes, metav1.PatchOptions{})
	}
	return c.Services(oldSvc.Namespace).Patch(context.TODO(), oldSvc.Name, types.StrategicMergePatchType, patchBytes, metav1.PatchOptions{}, "status")

}
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
