### ISSUE TITLE
Liveness/Readiness Certificate verification failed

### ISSUE THREAD

**Issue by 0xff-dev** [kubernetes/kubernetes#120519]
### What happened?

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes
According to the documentation, when liveness or readiness is configured as HTTPS, certificate verification will be automatically skipped.

I configured a self-signed certificate for the pod, but at this point liveness and readiness return a certificate error.

```shell
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  13m                   default-scheduler  Successfully assigned default/chartmuseum-tls-auth-7b8ff98956-lhn7m to kubebb-core-control-plane
  Normal   Started    12m (x2 over 13m)     kubelet            Started container chartmuseum
  Normal   Pulled     12m (x3 over 13m)     kubelet            Container image "ghcr.io/helm/chartmuseum:v0.16.0" already present on machine
  Normal   Created    12m (x3 over 13m)     kubelet            Created container chartmuseum
  Warning  Unhealthy  12m (x9 over 12m)     kubelet            Readiness probe failed: Get "https://10.244.0.66:8899/abc/health": remote error: tls: bad certificate
  Warning  Unhealthy  12m (x6 over 12m)     kubelet            Liveness probe failed: Get "https://10.244.0.66:8899/abc/health": remote error: tls: bad certificate
  Normal   Killing    12m (x2 over 12m)     kubelet            Container chartmuseum failed liveness probe, will be restarted
  Warning  BackOff    2m51s (x47 over 12m)  kubelet            Back-off restarting failed container
root@macbookpro:~/core-showcase# kubectl get po -owide
NAME                                    READY   STATUS             RESTARTS       AGE   IP            NODE                        NOMINATED NODE   READINESS GATES
chartmuseum-tls-auth-7b8ff98956-lhn7m   0/1     CrashLoopBackOff   9 (101s ago)   13m   10.244.0.66   kubebb-core-control-plane   <none>           <none>

```

### What did you expect to happen?

Can skip verification and start the pod normally.

### How can we reproduce it (as minimally and precisely as possible)?

1. create tls secret

```yaml
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqekNDQW5lZ0F3SUJBZ0lVZFE5T0RlWVJCNVo0SW4vYnV3THJrOFR6V3dNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1Z6RUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtKS01Rc3dDUVlEVlFRSERBSmlhakVNTUFvRwpBMVVFQ2d3RGJtbHNNUXd3Q2dZRFZRUUxEQU51YVd3eEVqQVFCZ05WQkFNTUNXeHZZMkZzYUc5emREQWVGdzB5Ck16QTVNRFF3TnpBME5EVmFGdzB6TXpBNU1ERXdOekEwTkRWYU1GY3hDekFKQmdOVkJBWVRBa05PTVFzd0NRWUQKVlFRSURBSkNTakVMTUFrR0ExVUVCd3dDWW1veEREQUtCZ05WQkFvTUEyNXBiREVNTUFvR0ExVUVDd3dEYm1scwpNUkl3RUFZRFZRUUREQWxzYjJOaGJHaHZjM1F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNxVmdPSk0wQVVqVU55UDJhVWI3bDh2b2xDRndRMHo3Z2xWYjFFUHJYMUpRbG44RXZ6TysxOGFLSHMKeDNaTEJLUDBLdFdjb2xla2M5SlRrSHFWc1l2amdCU2dPdE03MlErd3ZYV0N4TjRCcTdRdHNmd256QzJHZERucwpidFRlOUFQeGdjYXlxeFVpOVVNUFpLMUdKOEpjRndRTzNiK21qcVVOMXlSOVhRUEtGYWhQRDk0U2cwcklNTVllCnFmZ0RtSXM4SUt4UGJOcmRzSlV2ZkpXMFp5ZDM2bG1MYkRoSTBsQlpYS1lOWHdmWWhnNVI0Z1dwMGRLOFNhSkwKayt0YnM0WjQybzlRenlKaGlmb3BKb1A5TkEwc3hpaFh6dC8vZWVEVVdQSWZMaDVHZ3ZsRFRwSkNqUlhDQmxtQgpWaTZUc0ZZSmhuTUNxSGNHNjV5a0VqZ3F5bUxEQWdNQkFBR2pVekJSTUIwR0ExVWREZ1FXQkJTa3NMWURMZXFPClo5ZXdQcEx2SGh4UkJMS0hlakFmQmdOVkhTTUVHREFXZ0JTa3NMWURMZXFPWjlld1BwTHZIaHhSQkxLSGVqQVAKQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNjTC94d21GRkJ3V0VEK3FRQQpmeTZ6SlFkMG1FZFVCMS9mNlpRVERUMEM1ckZ3MmdsWnJ1YjRGNUFWRGcyZXFhN3VPUVZvRkRQOVcrM2huajZsCjZMVEdITDhTNk0xUVJFa1MwOVBRYXJSa242b2ZaeXBDaVFkdDh4dTZINEpLTzc3V2c2Vyt1VkFKTE1ldzFVM1gKVENLM29ZdE03UUJTR2FIbklTZ0xsWFBFR0dpNFBhNHF0alFJVm90dExhTkt0eGVHeFY5ekdkVUR5K2ZkeEpGNgphMUpjd2xlNis0bldSTERvbzBvVnpROW5McktTdDQwQlBKL1d3UXIwSzh1U0MvMTNhdDF3Tk90SXloZVFnbTFoCklvRU5zRGJnY1cxOW4rcExDNmgzOGtKS0JiYkdxVU1ndDJNZHAzNFZCTVlHTGpJeUNWZ0FsVnBERjgzbXdGUDgKYVYrSwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURzekNDQXB1Z0F3SUJBZ0lVWHpESDFjbmFMTFgwQXVxQ2Vpa0U5cXI1eGhFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1Z6RUxNQWtHQTFVRUJoTUNRMDR4Q3pBSkJnTlZCQWdNQWtKS01Rc3dDUVlEVlFRSERBSmlhakVNTUFvRwpBMVVFQ2d3RGJtbHNNUXd3Q2dZRFZRUUxEQU51YVd3eEVqQVFCZ05WQkFNTUNXeHZZMkZzYUc5emREQWVGdzB5Ck16QTVNRFF3TnpFNE5UWmFGdzB5TkRBNU1ETXdOekU0TlRaYU1FUXhDekFKQmdOVkJBWVRBa05PTVFzd0NRWUQKVlFRSURBSmlhakVNTUFvR0ExVUVCd3dEYm1sc01Rd3dDZ1lEVlFRS0RBTnVhV3d4RERBS0JnTlZCQXNNQTI1cApiRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMcldFM0VuVkVwNi9zUXJyempSCjBucTB2aEtSdHJhN2o3N0dldU56YldlMURzMTF4YmNrZlFIUWNzZ3B4RmlSbXd5UXdNWDNYdndNdHdsYmtFYkEKTkEwbnNiTnZ5S0IzWWY5S2JvL3hGK2VQZ2d5VlVVcDNQTk5LN0gxSFBNNWNMeCsvSURyQzlqdHhvY05jZXcyZwp0NVFPblcxN3V2SzJDZG9ySnNnZUFYV3kvdURVUks5d2R2L1hvM3NpcmwzdlduRzJ2TWlYVERjWUFTaC95eVJJClAyR1YyL3QxMGFkcHRtN2dzWUtudlUra1dsc2NWK0pzZExRWDNSYlhYeHhXbVBFUEYyREZJZDRqcTJLc01xY0QKWmh6NGdiVkhQM0x5WS9kUSsvb0FrLzJjSUF4NVNCNnRtU1JYQ1lXK3JlYSt5QnpGMjZzaUxSUGlZWnptNTJVSAo5YUVDQXdFQUFhT0JpVENCaGpCRUJnTlZIUkVFUFRBN2dnbHNiMk5oYkdodmMzU0NMbU5vWVhKMGJYVnpaWFZ0CkxYUnNjeTFoZFhSb0xtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d0hRWURWUjBPQkJZRUZBeVYKNmJJYzgrYkhJMktKMy9KNC9VTHIyK3dMTUI4R0ExVWRJd1FZTUJhQUZLU3d0Z010Nm81bjE3QStrdThlSEZFRQpzb2Q2TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBK25XbTBGdUM3Y2ZaR0hKWldnaDRkam5RWVRTRUFHYWlzClozZWJOZ1FheWRORmd4cEp2aTZTQjZwaHpFbUxOQWNLbndWK3VmaWpBVmdEemVsejVJY2E3V3FKYzl1d0xhR0UKZWVNWHZ3K2hMd0RLVTlwVEowdUIwRUgxdUxadnc2US90Z21zUXJ4ZjQyaXk5MDBJcVgxNU1QWS80ODB4K3h4eApDTEV4VUZLK1ppT2V4bHo4MURBR3NGTzg1ODdReS8zMGxzS1NXczBEdS82NXdnbjkvR3lLV1ZCS09CbUJmaDlYCkpPME9qWlIzM1R6YW5IRTJ3Tk16TEQxdXlLTDFtVjB1RGlNTnl4ekxWQUpQbzBMU1IrYUR3a2pLMmVpa3dHMzUKOVZFYittK0h3eHBXODJSdXhQQ3YrUDhqRzJTU3R6aDBHaEYxdkhXUTdpZjRHQVJFQnpXTAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzYxaE54SjFSS2V2N0UKSzY4NDBkSjZ0TDRTa2JhMnU0Kyt4bnJqYzIxbnRRN05kY1czSkgwQjBITElLY1JZa1pzTWtNREY5MTc4RExjSgpXNUJHd0RRTko3R3piOGlnZDJIL1NtNlA4UmZuajRJTWxWRktkenpUU3V4OVJ6ek9YQzhmdnlBNnd2WTdjYUhEClhIc05vTGVVRHAxdGU3cnl0Z25hS3liSUhnRjFzdjdnMUVTdmNIYi8xNk43SXE1ZDcxcHh0cnpJbDB3M0dBRW8KZjhza1NEOWhsZHY3ZGRHbmFiWnU0TEdDcDcxUHBGcGJIRmZpYkhTMEY5MFcxMThjVnBqeER4ZGd4U0hlSTZ0aQpyREtuQTJZYytJRzFSejl5OG1QM1VQdjZBSlA5bkNBTWVVZ2VyWmtrVndtRnZxM212c2djeGR1cklpMFQ0bUdjCjV1ZGxCL1doQWdNQkFBRUNnZ0VBTHNWa2ZKRVI0c3REZDZ4UDR2TnpzMUFIdlBKSlFSbFc5TFVQRWwxVTUvOUYKUTEzV0x2Q3Rjb1RTRnhXTmwzWnIwQXQwbHBwRVp1aHY4YUhBVGxYVE1lL2I1a1YzZmVRazNobXQ3ODYwNHp6agptMjdOdU14OHA1QTcvMmlUNmp6ZGR4OExYR3B0NVplZW5SOUxscS9EQlFkYmxZckIwL3lLSHRscWpmSWsvMmR2CnRxOHRHVnlZWXozdDRwOHRKeWYzZ3ZoQm4rM1UvYitraW9pL1FuRVRBL1BGNXhwRjlhNUhwN2JJM0VtZVh6UmoKSm1aSGwyc1ZZR21EWXBOTE1BNEdGNjBaa1dtaU96V0JIMHU4MVVpNUVWRUpnOUcxc2ljbnZYOXphWU05aWh2dwo1WmdQODFDSWs2RTBZU3lxQkFNak1vdENwN29ZSlp1MEQ1MnZWK1BtdVFLQmdRRHdVeGh0cVJJQ1ZGdXFjTWM1CmhBSThUNEd4cytLYkl2bzNzRjREL0dsV1lqL29oYmJSbkZEa0ZOUko1TFZLWFBYVWNONGx3LzVzdnZ3RzlpNXUKZXZrc2F4RFpFbDRybndGN1BBWmh3cFlub0V4eWdwaTg0VlZLcjl2VlJYdVFObzM1QnJXV3BmcUUxZ1VZRkxocQplaHZJSklkd282emZLbHRyZTQ2a243eGFld0tCZ1FESEJkYitqcURXMm1LVlFuUHRWeTJWVFg4WFA4Z092Wmo5CjlXR1NEVjZ2UHhUaWFCcjhMSnhYekRObjZZNktwejFyWURmc1Q2SnF4U2pDZnczRzZrK0F1RUF5cUZzN3MrTWMKZ2pMbjRIQmovNTZnZlUvMUF0TEhRUXFYc2ROVXBkdWtYSW9ISGNCb0tOZXpiTk9JR2xLdXZYRE02ZHg2OHp3NQpKUWdDaFJTemt3S0JnRTdVWXVudGtGdTFRaEFwU0NBa25mc2NkVVZONVNIUUdsVlVBN0s1QS9CeTc5V2NycmdZCjF5dkpiVTBEdVRlNFFHYTcweEorTktHRkQvUlVvaXhaS0F5YTNmN21HSCtrZTM3cDFJb1NvdUJDbzNEWVI3T0YKRWs0YVd6aWN2d2d4N09YbmZuNzQyTERqNXUzY05oV3ZFaGZYYTVuV0JtbDVZbDFpUFFyZzNvNnJBb0dCQUwxRgppbjh3T1RuYkdtSUVmcWM2ZnprOEtCOStJczRSOVl1ZmJ4a3M2ZDBUeXRLK1d0dHp1WU90eVQyTFdtbjJQbXo5ClpuR3dFakFrTEcwNzAyaFdzU0VqR0xxVWJaOUxwak1ZaHowSnJ4a0tvbHJTa2RYYXg0V0RENFhRTWNDUXMxK08KT2g0bVp6TW5sR3NvbGNzYjdZSU0yMWVsR0c4OUh3cmhjc3Fpc1Z0TkFvR0FmelY2Z1FVWEJiVGdIM05FcGVyNQpSZUZucGVncjdBRVdGbzdiREtDT0dPOTZKTUFaRTJVWERqNHY4S0JDcER0UmRtNkZmc01OcUorS2h3UGFtNjJ5CkZVL3RWVEFWcW85akJyYVNhWFBjamJRZjN4SnR2MmZzWi9tMVkzQWVNUU9ISW0rNUFNTVNtVEJjL3ozcyt2ekUKOTY0VXJIT0ptRXhOZGtGQks2NWZxYTg9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: charttls
  namespace: default
type: Opaque
```

2. create chartmuseum deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chartmuseum-tls-auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chartmuseum-tls-auth
  template:
    metadata:
      labels:
        app: chartmuseum-tls-auth
    spec:
      volumes:
      - name: dir
        emptyDir: {}
      - name: tls
        secret:
          secretName: charttls
      containers:
      - name: chartmuseum
        image: ghcr.io/helm/chartmuseum:v0.16.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /abc/health
            port: 8899
            scheme: HTTPS
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /abc/health
            port: 8899
            scheme: HTTPS
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
        - name: dir
          mountPath: /storage
        - name: tls
          mountPath: /tls
        command:
        - /chartmuseum
        args:
        - --port
        - "8899"
        - --depth
        - "1"
        - --storage
        - "local"
        - --storage-local-rootdir
        - "./storage"
        - --tls-ca-cert
        - "/tls/ca.crt"
        - --tls-cert
        - "/tls/server.crt"
        - --tls-key
        - "/tls/server.key"
          #- --basic-auth-user
          #- "admin"
          #- --basic-auth-pass
          #- "password"
```

3. watch pod

### Anything else we need to know?

I have checked the code of `kubelet`'s prober, and the http part indeed sets the transport's `InsecureSkipVerify` to true.

https://github.com/kubernetes/kubernetes/blob/f8ca582a06a8379968ddb7960adefeea3c467e36/pkg/probe/http/http.go#L40

My cluster is built through kind, version 1.24

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short. Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-09-01T23:46:50Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.10"
NAME="Ubuntu"
VERSION_ID="22.10"
VERSION="22.10 (Kinetic Kudu)"
VERSION_CODENAME=kinetic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=kinetic
LOGO=ubuntu-logo

$ uname -a
# paste output here
Linux macbookpro 5.19.0-46-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun 16 13:30:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kind
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
