### ISSUE TITLE
`NetworkPolicy`: connection-oriented semantics are undocumented

### ISSUE THREAD

**Issue by sanmai-NL** [kubernetes/kubernetes#120525]
### What would you like to be added?

It is undocumented (on e.g., https://kubernetes.io/docs/concepts/services-networking/network-policies/ or https://network-policy-api.sigs.k8s.io/reference/spec/#policy.networking.k8s.io%2fv1alpha1) that `NetworkPolicy` rules result in a `conntrack` rule, i.e., that `NetworkPolicy`s are connection-oriented rather than packet oriented, for TCP.

For example, the egress key in the last `NetworkPolicy` is redundant:

```yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: defaultdeny
spec:
  podSelector: {}
  policyTypes:
    - Egress
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: http
spec:
  egress: # This entire key is redundant.
    - ports:
        - protocol: TCP
          port: '1024-65535'
  ingress:
    - ports:
        - port: '80'
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: webservice
  policyTypes:
    - Ingress
    - Egress
```

The docs are misleading, for example:

https://kubernetes.io/docs/concepts/services-networking/network-policies/ 

> A pod is isolated for egress if there is any NetworkPolicy that both selects the pod and has "Egress" in its policyTypes; we say that such a policy applies to the pod for egress. When a pod is isolated for egress, **the only allowed connections from the pod are those allowed by the egress list of some NetworkPolicy that applies to the pod for egress**. The effects of those egress lists combine additively.

In truth this refers to **the only new, unestablished connections ...**.

Indeed, given https://github.com/kubernetes/kubernetes/issues/109672 and https://github.com/kubernetes/kubernetes/issues/120214 it seems this design choice for TCP is not protocol-independent and an undeliberate architectural design.

### Why is this needed?

Securing networks is important. The current documentation is misleading as to what rules are required in a default-deny scenario with TCP.
