### ISSUE TITLE
Add negative index regression test for json-patch

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#120563]
https://github.com/kubernetes/kubernetes/pull/120327 reverted json-patch back to 4.12.0 to fix a regression in negative index json-patch behavior

A test that exercises the bug fixed in https://github.com/kubernetes/kubernetes/pull/105896 is needed to ensure we don't accidentally bump again and lose the fix

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/120326#issuecomment-1701891191_
           
cc @Jefftree @soltysh

**Comment by MeenuyD** [comment]
Hello @liggitt I would like to work on this issue can i work on this issue

**Comment by liggitt** [comment]
sounds good, a unit test that tries to apply a patch like the one indicated in https://github.com/kubernetes/kubernetes/issues/105895#issue-1035786694 would probably be sufficient

**Comment by MeenuyD** [comment]
I am confused about whether should I change the version of json-patch.

**Comment by liggitt** [comment]
No, we already reverted json-patch to fix the regression. This issue is to add a new unit test exercising a negative index `replace` json-patch as described in https://github.com/kubernetes/kubernetes/issues/105895#issue-1035786694 to make sure we don't reintroduce the regression

**Comment by MeenuyD** [comment]
Ok thanks for guiding

**Comment by carlory** [comment]
/assign MeenuyD

I assign this issue to you in order to avoid someone to do duplicated work.

**Comment by MeenuyD** [comment]
Hello @liggitt should we have to add a replacement operation for the negative index because issue #105895 says this is resolved by changing the version from 4.11.0 to 4.12.0 Can you please explain more

**Comment by liggitt** [comment]
that bumped the dependency, fixing the issue, but we never added a test to exercise the fix. Then, when json-patch accidentally got bumped to a version that regressed the fix, no test caught it

**Comment by aryabhatta-dey** [comment]
Hey! There has been no activity on this for some time. I will like to take a stab at this if nobody's working on it @liggitt @carlory

**Comment by aryabhatta-dey** [comment]
Hey! I will like to take a stab at this since it looks like nobody is actively working on it.
/assign

**Comment by Vandit1604** [comment]
I don't see anyone actively working on this issue. I would like to give it a try.
/assign 

@liggitt I searched the test file for the `JsonPatch` and stumbled on this testing function in [helpers_test.go](https://github.com/kubernetes/kubernetes/blob/6aac45ff1e99068e834ba3b93b673530cf62c007/staging/src/k8s.io/kubectl/pkg/cmd/util/helpers_test.go#L249-L309). 
I want to ask if adding a testcase with negative index in the above function would count as a solution. If yes, I can submit a Pull Request.

Something like this 
```go
{
	obj:       &corev1.Pod{},
	fragment:  `[ {"op": "replace", "path": "/spec/volumes/-1/foo", "value": "bar"} ]`,
	expectErr: true,
},
```

**Comment by liggitt** [comment]
@Vandit1604 I'm not 100% sure without digging, but if adding that negative index test case passes on master and fails on v1.28.0, that seems like what we're looking for

**Comment by Vandit1604** [comment]
I saw interesting behaviour in branch `release-1.28` [helpers_test.go's TestJSONPatch function](https://github.com/kubernetes/kubernetes/blob/release-1.28/staging/src/k8s.io/kubectl/pkg/cmd/util/helpers_test.go#L249). When I added this testcase
```go
{
			obj: &corev1.Pod{
				ObjectMeta: metav1.ObjectMeta{
					Name:       "foo",
					Finalizers: []string{"foo", "bar", "test"},
				},
			},
			fragment: `[ {"op": "replace", "path": "/metadata/finalizers/-1", "value": "foo"} ]`,
			expected: &corev1.Pod{
				TypeMeta: metav1.TypeMeta{
					Kind:       "Pod",
					APIVersion: "v1",
				},
				ObjectMeta: metav1.ObjectMeta{
					Name:       "foo",
					Finalizers: []string{"foo", "bar", "foo"},
				},
				Spec: corev1.PodSpec{},
			},
			expectErr: true,
}
```
I expected it to fail on negative index replace operation but it didn't and gave 
```bash
root@vandit-box:/home/vandit/go/src/k8s.io/kubernetes/staging/src/k8s.io/kubectl/pkg/cmd/util# go test
--- FAIL: TestJSONPatch (0.00s)
    helpers_test.go:329: testcase[3], unexpected non-error
FAIL
exit status 1
FAIL	k8s.io/kubectl/pkg/cmd/util	0.014s
```

I also ran a `make all` it also didn't fail on `release-1.28`
```bash
--- FAIL: TestJSONPatch (0.00s)
    helpers_test.go:329: testcase[3], unexpected non-error
FAIL
FAIL	k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util
```

I ran tests on master after adding 
```go
{
			obj: &corev1.Pod{
				ObjectMeta: metav1.ObjectMeta{
					Name:       "foo",
					Finalizers: []string{"foo", "bar", "test"},
				},
			},
			fragment: `[ {"op": "replace", "path": "/metadata/finalizers/-1", "value": "foo"} ]`,
			expected: &corev1.Pod{
				TypeMeta: metav1.TypeMeta{
					Kind:       "Pod",
					APIVersion: "v1",
				},
				ObjectMeta: metav1.ObjectMeta{
					Name:       "foo",
					Finalizers: []string{"foo", "bar", "foo"},
				},
				Spec: corev1.PodSpec{},
			},
			// expectErr: true,
}
```
And every test passed. 

Was this the desired output ? Since I am assuming the unexpected error to be false alarm or It should be like this?

**Comment by liggitt** [comment]
The negative index should *not* error, right?

**Comment by Vandit1604** [comment]
Thanks for pointing that out. I ran the tests again both on `master` and `release-1.28`. All the testcases passed on both branches.

I saw that we are only using the JsonPatch() function only in 2 more files i.e 
```go
staging/src/k8s.io/kubectl/pkg/cmd/util/helpers.go            func JSONPatch(codec runtime.Codec, dst runtime.Object, fragment string) (runtime.Object, error) {
staging/src/k8s.io/kubectl/pkg/cmd/util/helpers_test.go       out, err := JSONPatch(codec, test.obj, test.fragment)
staging/src/k8s.io/kubectl/pkg/cmd/util/override_options.go   return JSONPatch(codec, obj, o.Options.Overrides)
```
I think I'll need to look at other places as it seems we're not using the JSONPatch() function for patching the resources anywhere.

**Comment by Vandit1604** [comment]
TLDR: The `kubectl patch` replace operation was working fine with negative index on **release-1.28**

I created a nginx-deployment and added 3 more `ports` in `spec.container.ports` with

```bash
kubectl patch deployment nginx-deployment --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/ports/-", "value": {"containerPort": 10253,"name": "metrics2"}}]'
```

<details open>
<summary>Ran the above command 2 more times with different values.</summary>
 <br>
 
 ```yaml
            "spec": {
                "containers": [
                    {
                        "image": "nginx:1.14.2",
                        "imagePullPolicy": "IfNotPresent",
                        "name": "nginx",
                        "ports": [
                            {
                                "containerPort": 80,
                                "protocol": "TCP"
                            },
                            {
                                "containerPort": 10254, # we will change this value i.e -3 index
                                "name": "metrics",
                                "protocol": "TCP"
                            },
                            {
                                "containerPort": 10254,
                                "name": "metrics1",
                                "protocol": "TCP"
                            },
                            {
                                "containerPort": 10253,
                                "name": "metrics2",
                                "protocol": "TCP"
                            }
                        ],
                        "resources": {},
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File"
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "restartPolicy": "Always",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "terminationGracePeriodSeconds": 30
            }
        }
    },
```

 </details>
 
<details open>
<summary> Then the kubectl replace patch worked perfectly fine. Here's the output</summary>
<br>

 ```yaml
 root@vandit-box:/home/vandit/go/src/k8s.io/kubernetes# k get deployment nginx-deployment -o json
{
 ...
   "spec": {
                "containers": [
                    {
                        "image": "nginx:1.14.2",
                        "imagePullPolicy": "IfNotPresent",
                        "name": "nginx",
                        "ports": [
                            {
                                "containerPort": 80,
                                "protocol": "TCP"
                            },
                            {
                                "containerPort": 10251,
                                "name": "metrics",
                                "protocol": "TCP"
                            },
                            {
                                "containerPort": 10254,
                                "name": "metrics1",
                                "protocol": "TCP"
                            },
                            {
                                "containerPort": 10253,
                                "name": "metrics2",
                                "protocol": "TCP"
                            }
                        ],
                        "resources": {},
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File"
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "restartPolicy": "Always",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "terminationGracePeriodSeconds": 30
            }
        }
    },
...
}
 ```


</details>
 
 ```bash
 root@vandit-box:/home/vandit/go/src/k8s.io/kubernetes# kubectl patch deployment nginx-deployment --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/ports/-3", "value": {"containerPort": 10251,"name": "metrics"}}]'
deployment.apps/nginx-deployment patched
```

Kubectl Version. I was testing using KinD
```bash
root@vandit-box:/home/vandit/go/src/k8s.io/kubernetes# kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-5+5d19345cef50b0-dirty
```
