### ISSUE TITLE
scheduler: handle in-flight Pods with less memory

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#120622]
All cluster events during scheduling are piled up in [inFlightEvents](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue.go#L187).
In the current design, we need them to evaluate which queue to push failed Pods to. 
But, given it needs to record all cluster events that happen during pod's scheduling, it increases the scheduler's memory consumption -- especially in a busy cluster.

Also, in the first place, maybe we have a memory leak around the inFlightEvents, see:
- https://github.com/kubernetes/kubernetes/issues/122661
- https://github.com/kubernetes/kubernetes/issues/122725

This issue is the general issue to try to reduce the impact as much as possible.

/kind feature
/sig scheduling
/cc @alculquicondor 
/assign
```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes/kubernetes/pull/120586
- [ ] https://github.com/kubernetes/kubernetes/pull/122628
- [ ] https://github.com/kubernetes/kubernetes/pull/127016
- [ ] https://github.com/kubernetes/kubernetes/pull/126962
- [ ] https://github.com/kubernetes/kubernetes/pull/127052
- [ ] https://github.com/kubernetes/kubernetes/pull/127220
- [ ] Add a scheduler_perf test case with the `inflight_events` metric to keep the memory consumption reasonably low
```

**Comment by sanposhiho** [comment]
Here is another idea:
- For InFlight Pods, we execute QueueingHint of all plugins when any events happen. And, the scheduling queue remembers which plugin returned Queue.
- When InFlight Pods come back, the scheduling queue checks remembered plugin results based on failed plugins the Pod got, and decides which queue it requeue the Pod to

It’d solve this problem since we no longer need to cache the events.
But, we need to make sure if it could work in a large scale.
(e.g., could it slow down the speed to handle events from EventHandler? then what if there are too many events to handle? etc)
Talking with @alculquicondor, heavy load test should be implemented in E2E with all components (kubelet etc) so that we can do so.

slack thread: https://kubernetes.slack.com/archives/C09TP78DV/p1697738803285919

**Comment by sanposhiho** [comment]
/retitle scheduler: handle in-flight Pods with less memory 

(We might be able to eliminate "record events". So, just retitle it to be a bit more vague - what we want to do is handle in-flight Pods with less memory impact.)

**Comment by alculquicondor** [comment]
cc @tosi3k @aleksandra-malinowska

**Comment by alculquicondor** [comment]
Our latest run with 1.28.2 shows better memory usage.
The only difference is this PR https://github.com/kubernetes/kubernetes/pull/120413
Maybe there was a memory leak after all.

**Comment by alculquicondor** [comment]
While reviewing #119177, I realize that we might be keeping way too many events in memory.

The NodeResourcesFit and PodTopologySpread plugins register for Pod updates. In a busy cluster, Pod updates would happen very often, as Pod statuses are continuously updated. However, we don't care about most Pod updates.
- NodeResourcesFit would only care about updates to `Pod.Status.ContainerStatuses[i].AllocatedResources`.
- PodTopologySpread would only care about updates to labels.

I think we might need to distinguish between those to reduce memory usage, since we can't run the hints for inflight pods.

**Comment by sanposhiho** [comment]
Splitting Pod events like Node events, LGTM. Maybe like:
- `PodContainerStatusUpdate`
- `PodLabelUpdate`

**Comment by sanposhiho** [comment]
I'm concerned... https://github.com/kubernetes/kubernetes/issues/122306 means that plugins with NodeAdd must register a general NodeUpdate event until preCheck is removed. It increases the number of events that the scheduling queue has to record for in-flight Pods. 
So, now many things including this issue depend on the removal of preCheck. When we can enable QHint by default might equal when preCheck is removed.

**Comment by alculquicondor** [comment]
> When we can enable QHint by default might equal when preCheck is removed.

Yes, I wouldn't enable it by default otherwise.

**Comment by sanposhiho** [comment]
/assign @AxeZhan 

Talked in DM a while ago and they'll take this one:
> Measure the memory consumption via some tests to confirm no significant memory degradation

@AxeZhan sorry it's been a while since we talked about it. If you changed your mind and don't have enough time/curiosity for this, feel free to just `/unassign`.

**Comment by AxeZhan** [comment]
I tried several test cases in `scheduler_perf`, for example, this:
```
- name: SchedulingWithMixedChurn
  featureGates:
    SchedulerQueueingHints: true
  workloadTemplate:
  - opcode: createNodes
    countParam: $initNodes
    nodeTemplatePath: config/node-default.yaml
    labelNodePrepareStrategy:
      labelKey: "topology.kubernetes.io/zone"
      labelValues: ["moon-1", "moon-2", "moon-3"]
  - opcode: createPods
    countParam: $initPods
    podTemplatePath: config/pod-default.yaml
  - opcode: churn
    mode: create
    number: 5000
    templatePaths:
    - config/pod-with-topology-spreading.yaml
    intervalMilliseconds: 1
  - opcode: createPods
    countParam: $measurePods
    podTemplatePath: config/pod-default.yaml
    collectMetrics: true
  workloads:
  - name: 1000Nodes
    labels: [integration-test, fast]
    params:
      initNodes: 1000
      initPods: 1000
      measurePods: 1000
  - name: 5000Nodes
    labels: [performance, fast]
    params:
      initNodes: 5000
      initPods: 1000
      measurePods: 2000
```

and run with 
```
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TIMEOUT="-timeout=3600s" ETCD_LOGLEVEL=warn KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-run=^$$ -benchtime=1ns -bench=BenchmarkPerfScheduling -memprofile ~/mem-profile-hint.out"
```

I didn't find a significant difference in memory usage between the two cases(with feature enabled/disabled).
Memory usage with feature enabled: 8792.40MB total
Memory usage with feature disabled: 8834.72MB total
(It looks weird since memory usage goes down after enabling the feature)

Any thoughts on how to reproduce the memory usage increase?
