### ISSUE TITLE
Kubelet log query errors "input contains unsupported characters"

### ISSUE THREAD

**Issue by rothgar** [kubernetes/kubernetes#120618]
### What happened?

I enabled the [kubelet log query feature](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#log-query) on EKS 1.27.4 using Ubuntu 20.04.6.

When I try to query the kubelet logs or log files from the system I get the error "input contains unsupported characters"

```
kubectl get --raw "/api/v1/nodes/i-0ede67f2d75dfe308.us-west-2.compute.internal/proxy/logs/?query=snap.kubelet-eks.daemon.service"
Error from server (NotAcceptable): query: Invalid value: "snap.kubelet-eks.daemon.service": input contains unsupported characters

kubectl get --raw "/api/v1/nodes/i-0ede67f2d75dfe308.us-west-2.compute.internal/proxy/logs/?query=cloud-init.log"
Error from server (NotAcceptable): query: Invalid value: "cloud-init.log": input contains unsupported characters
```
The systemd kubelet service runs as a snap called `snap.kubelet-eks.daemon.service` and I _think_ that might be the source of this problem (running the kubelet in a snap), but I'm not sure if it's intended to work. The fact that I couldn't see /var/log file query was surprising and the error message is misleading which is why I'm opening an issue here.

I followed the same configuration steps on Amazon Linux 2 and it works as expected.

### What did you expect to happen?

Log query should work on Ubuntu or provide a clearer error message.

### How can we reproduce it (as minimally and precisely as possible)?

This should be reproducible on any Kubernetes cluster running Ubuntu with Kubelet in a snap, but this is what I did.

Install [eksdemo](https://github.com/awslabs/eksdemo) to make cluster creation and karpenter setup easier)
```
eksdemo create cluster log-testing --os Ubuntu2004 --prefix-assignment
```
Install Karpenter as a node autoscaler. This will automatically create a provisioner and AWSNodeTemplate objects.
```
eksdemo install autoscaling karpenter -c ubuntu -A Ubuntu
```
Modify the AWSNodeTemplate with userdata that can customize Ubuntu with log query enabled
```
cat << EOF | kubectl apply -f -
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiFamily: Ubuntu
  securityGroupSelector:
    aws:eks:cluster-name: ubuntu
  subnetSelector:
    Name: eksctl-ubuntu-cluster/SubnetPrivate*
  userData: |
    #!/bin/bash
    set -e

    # This probably isn't the best way to do this but it worked
    sed -i 's/args="$KUBELET_EXTRA_ARGS"/args="--feature-gates=NodeLogQuery=true $KUBELET_EXTRA_ARGS"/g' /etc/eks/bootstrap.sh
    sed -i '/# writes kubeReserved and evictionHard/a echo "$(jq .enableSystemLogHandler=true $KUBELET_CONFIG)" > $KUBELET_CONFIG' /etc/eks/bootstrap.sh
    sed -i '/# writes kubeReserved and evictionHard/a echo "$(jq .enableSystemLogQuery=true $KUBELET_CONFIG)" > $KUBELET_CONFIG' /etc/eks/bootstrap.sh
EOF
```
Deploy a workload that uses hostname spread to get more nodes.
```
cat << EOF | kubectl apply -f -
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: myapp
spec:
  minAvailable: "80%"
  selector:
    matchLabels:
      app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
        name: myapp
        resources:
          requests:
            cpu: "1"
            memory: 256M
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: host-zone-spread
        maxSkew: 2
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            app: host-zone-spread
        maxSkew: 5
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
EOF
```
When the new Ubuntu node is created you can log into the node with session manager. I like to use [ssm-helpers](https://github.com/disneystreaming/ssm-helpers)
```
brew install disneystreaming/tap/ssm-helpers
ssm session
# select the new node
```
You can verify that the kubelet is running and logging is enabled
```
sudo systemctl status -l snap.kubelet-eks.daemon.service
```
Now you can try to query logs
```
kubectl get --raw "/api/v1/nodes/$NODE/proxy/logs/?query=snap.kubelet-eks.daemon.service"
```

### Anything else we need to know?

This works with AL2. You can test with a different AWSNodeTemplate that uses AL2 instead
```
cat << EOF | kubectl apply -f -
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  amiFamily: AL2
  securityGroupSelector:
    aws:eks:cluster-name: ubuntu
  subnetSelector:
    Name: eksctl-ubuntu-cluster/SubnetPrivate*
  userData: |
    #!/bin/bash
    set -e

    cat << EOF > /etc/systemd/system/kubelet.service.d/90-kubelet-extra-args.conf
    [Service]
    Environment="KUBELET_EXTRA_ARGS=--feature-gates=NodeLogQuery=true $KUBELET_EXTRA_ARGS"
    EOF
    systemctl daemon-reload

    echo "$(jq '.enableSystemLogHandler=true' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
    echo "$(jq '.enableSystemLogQuery=true' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
EOF
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4-eks-2d98532
```

</details>

### Cloud provider

<details>
EKS (but should happen on any provider)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
