### ISSUE TITLE
Nodelabeler support in the ResourceQuota as of now is missing. It doesn't segregate resources of node types.

### ISSUE THREAD

**Issue by vishakumarc95** [kubernetes/kubernetes#120794]
### What would you like to be added?

As of now , If I have "AMD" & "ARM"  architectures based machines , there is no way for me to apply quota of CPU/memory on only ARM based machines

### Why is this needed?

This is needed because one can have very few arm machines in the K8s & hence any generic resource quota might not help control the consumption of any particular nodeType.

**Comment by vishakumarc95** [comment]
If I have 10 namespaces & only 2 arm nodes in the K8s ,I wouldn't want all arm nodes resources to get consumed by only few projects. We need a way to control resource consumption of different node types by a namespace.

While defining resource quota of a namespace , we got to able to provide limits on CPU/Memory for different kinds of node based on architecture ( AMD/ARM)

**Comment by pacoxu** [comment]
Currently, resource quota are just based on resources or resource size. Only service cut into several types: `services.loadbalancers` and `services.nodeports`.

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    services: "10"
    services.loadbalancers: "2"
    pod: 10
    pod.arm64: 4
    pod.amd64: 6
```
We may follow the service style like above. However, this is harder to do as images can be multi-arch and this may affect scheduler to schedule the pod to arm64 or amd64. Just some of my thoughts on this. It may mess up things IMO.
