### ISSUE TITLE
External service UDP fails while TCP works due to definition processing asymmetry

### ISSUE THREAD

**Issue by realbazso** [kubernetes/kubernetes#120863]
### What happened?

I have a single node k3s installation. I'd like to use it as an entry point even if some services are installed on separate VMs, not on K8s. External services work nicely when the service is available via TCP, but not when it's UDP as the system thinks UDP service doesn't have Endpoint definition and creates deny rules for iptables. The YAML is symmetric to the TCP one.

Working TCP:
````
apiVersion: v1
kind: Service
metadata:
  name: bugreport-works
  namespace: mate
spec:
  type: LoadBalancer
  ports:
  - port: 4321
    name: works-tcp
    protocol: TCP
    targetPort: 4321
---
kind: Endpoints
apiVersion: v1
metadata:
  name: bugreport-works
  namespace: mate
subsets:
  - addresses:
      - ip: 192.168.122.108
    ports:
      - port: 4321
        name: works-tcp
````

Not working UDP:
````
apiVersion: v1
kind: Service
metadata:
  name: bugreport-fails
  namespace: mate
spec:
  type: LoadBalancer
  ports:
  - port: 4321
    name: fails-udp
    protocol: UDP
    targetPort: 4321
---
kind: Endpoints
apiVersion: v1
metadata:
  name: bugreport-fails
  namespace: mate
subsets:
  - addresses:
      - ip: 192.168.122.108
    ports:
      - port: 4321
        name: fails-udp
````

For UDP I see these generated rejection rules (for TCP, there is no any similar):
```
-A KUBE-EXTERNAL-SERVICES -d 192.168.31.133/32 -p udp -m comment --comment "mate/bugreport-fails:fails-udp has no endpoints" -m udp --dport 4321 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-EXTERNAL-SERVICES -p udp -m comment --comment "mate/bugreport-fails:fails-udp has no endpoints" -m addrtype --dst-type LOCAL -m udp --dport 31974 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.43.215.148/32 -p udp -m comment --comment "mate/bugreport-fails:fails-udp has no endpoints" -m udp --dport 4321 -j REJECT --reject-with icmp-port-unreachable
```

### What did you expect to happen?

TCP and UDP definitions should work identically

### How can we reproduce it (as minimally and precisely as possible)?

Modify the definitions above according to your environment. Get an external host (VM, node, etc), netcat is the easiest to test it.
On caller client (first for TCP, second for UDP)
```
root@hu1l2022978:~# nc 192.168.31.133 4321
a
b
^C
root@hu1l2022978:~# nc-u 192.168.31.133 4321
a
root@hu1l2022978:~#
```
On backend host (first for TCP, second for UDP)
```
root@matelin:~# nc -ul 4321
^C
root@matelin:~# nc -l 4321
a
b
root@matelin:~# nc -ul 4321
```

In case of applying the UDP definition, on K8S node you immediately see the rejection rules (see above)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5+k3s1", GitCommit:"8d074ecb5a8765a09eeef6f8be7987055210bc40", GitTreeState:"clean", BuildDate:"2023-09-05T18:24:36Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5+k3s1", GitCommit:"8d074ecb5a8765a09eeef6f8be7987055210bc40", GitTreeState:"clean", BuildDate:"2023-09-05T18:24:36Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux blackpearl 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Standard K3S installation
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
>  but not when it's UDP as the system thinks UDP service doesn't have Endpoint definition and creates deny rules for iptables.

and the system thinks right ;), just do `kubectl get endpoints -o yaml` to see what the system ¨thinks"

You are missing the protocol field for the endpoint

```yaml
kind: Endpoints
apiVersion: v1
metadata:
  name: bugreport-fails
  namespace: mate
subsets:
  - addresses:
      - ip: 192.168.122.108
    ports:
      - port: 4321
        name: fails-udp
        protocol: UDP <-------------------
```
