### ISSUE TITLE
Fixes in cel-go breaks backward compatible of CRD validation rules between 1.27 and 1.28 release

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#120821]
### What happened?

We were using cel-go v0.12.7 in Kubernetes 1.27 release and cel-go v0.16.0 in Kubernetes 1.28 release. There are many changes from cel-go side between those two releases and some may break backward compatible of CRD validation rules.

An example would be the estimated cost for CRD validation rules(Thanks to @inteon who brought this to our attention with the following example).
In the example CRD validation rules below:
```
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resources.example.com
spec:
  group: example.com
  names:
    kind: Resource
    listKind: ResourceList
    plural: resources
    singular: resource
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            items:
              properties:
                a:
                  type: string
                b:
                  type: string
                c:
                  type: string
                d:
                  type: string
                e:
                  type: string
                f:
                  type: string
              type: object
              x-kubernetes-validations:
              - message: must have exactly one field set
                rule: '(has(self.a) ? 1 : 0) + (has(self.b) ? 1 : 0) + (has(self.c)
                  ? 1 : 0) + (has(self.d) ? 1 : 0) + (has(self.e) ? 1 : 0)
                  + (has(self.f) ? 1 : 0) == 1'
            type: array
        type: object
    served: true
    storage: true
    ...
```
It will pass perfect in Kubernetes 1.27 version but fail in Kubernetes 1.28 with error:
`Forbidden: estimated rule cost exceeds budget by factor of 1.6x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared) `

This is due to the estimator fix happened in cel-go([cel fix 1](https://github.com/google/cel-go/pull/651), [cel fix 2](https://github.com/google/cel-go/pull/798))

### What did you expect to happen?

The changes should not cause backward incompatible of CRD validation rules. OR a stability test suite should be in place to prevent the changes causing backward compatible issue before GA.

### How can we reproduce it (as minimally and precisely as possible)?

Apply the above CRD in Kubernetes 1.27 and 1.28, 1.27 cluster should pass and 1.28 cluster should fail.

### Anything else we need to know?

Since the fix in cel-go side makes sense to me and the feature is in Beta now, I am not quite sure how strict we should be on backward compatible.  cc @liggitt 

As a followup, a stability test suite for estimate cost is worth adding before GA to make sure any future changes be caught before the feature promoted to GA.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
