### ISSUE TITLE
SideCar startupProbe on 1.28

### ISSUE THREAD

**Issue by bechampion** [kubernetes/kubernetes#120848]
### What happened?

There seems to be a bit of a time sync or race condition between the intiContainer doing its thing and the startup probe , take this example:
```
  containers:
    - name: myapp
      image: alpine:latest
      command: ['sh', '-c', 'tail -F /opt/logs.txt']
      volumeMounts:
        - name: data
          mountPath: /opt
  initContainers:
    - name: logshipper
      image: alpine:latest
      restartPolicy: Always
      command: ['sh', '-c', 'sleep 3 ; echo "containerId: $(cat /proc/1/uid_map  | awk "{ print $3 }") logging $(date +%s)" >> /opt/logs.txt']
      startupProbe:
        exec:
          command: ["true"]
        periodSeconds: 1
        initialDelaySeconds: 0
      volumeMounts:
        - name: data
          mountPath: /opt
```
This example passes the startupProbe and the container `myapp` starts ok , but if i remove the `sleep` or if i reduce it to anything shorter than `3` seconds ,  the `myapp` container never start.

### What did you expect to happen?

`myapp` should of start as a result of `startupProbe` passing ,  but it seems to take too long to exec

### How can we reproduce it (as minimally and precisely as possible)?

example provided above but ,  enabling sidecar feature gate and with this example:
```#kind create cluster --image kindest/node:v1.28.0 --config cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "SidecarContainers": true
```
pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  volumes:
  - name: data
    emptyDir:
      sizeLimit: 500Mi
  containers:
    - name: myapp
      image: alpine:latest
      command: ['sh', '-c', 'tail -F /opt/logs.txt']
      volumeMounts:
        - name: data
          mountPath: /opt
  initContainers:
    - name: logshipper
      image: alpine:latest
      restartPolicy: Always
      command: ['sh', '-c', 'sleep 5 ; echo "containerId: $(cat /proc/1/uid_map  | awk "{ print $3 }") logging $(date +%s)" >> /opt/logs.txt']
      startupProbe:
        exec:
          command: ["true"]
        periodSeconds: 1
        initialDelaySeconds: 0
      volumeMounts:
        - name: data
          mountPath: /opt
    - name: logshipper1
      image: alpine:latest
      restartPolicy: Always
      command: ['sh', '-c', 'sleep 5 ; echo "containerId: $(cat /proc/1/uid_map  | awk "{ print $3 }") logging $(date +%s)" >> /opt/logs.txt']
      startupProbe:
        exec:
          command: ["true"]
        periodSeconds: 1
        initialDelaySeconds: 0
      volumeMounts:
        - name: data
          mountPath: /opt
```

### Anything else we need to know?

Version is 1.28

### Kubernetes version

<details>

```console
❯ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0

```

</details>

### Cloud provider

<details>
Local / Kind
</details>

### OS version

<details>

```console
❯ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
