### ISSUE TITLE
Changing service from headless to cluster IP does not fail

### ISSUE THREAD

**Issue by fraenkel** [kubernetes/kubernetes#120937]
### What happened?

Used `kubectl apply` to switch an existing headless service to a cluster IP service.
The `apply` succeeds but the service remains unchanged.

The response body shows `spec.clusterIP` is "", but it is not.

### What did you expect to happen?

The update to fail.

### How can we reproduce it (as minimally and precisely as possible)?

```
kubectl apply -f headless.yaml
kubectl apply -f clusterip.yaml
```
<details><summary>headless.yaml</summary>

```
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: test
  type: ClusterIP
```
</details>
<details><summary>clusterip.yaml</summary>

```
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  clusterIP: ""
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: test
  type: ClusterIP
```
</details>

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Kind
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
