### ISSUE TITLE
E2E Service Test assumes node name matches node's hostname

### ISSUE THREAD

**Issue by rifelpet** [kubernetes/kubernetes#121018]
### Which jobs are failing?

https://testgrid.k8s.io/kops-misc#e2e-kops-do-calico-dns-none

### Which tests are failing?

Kubernetes e2e suite.[It] [sig-network] Services should respect internalTrafficPolicy=Local Pod and Node, to Pod (hostNetwork: true)

### Since when has it been failing?

For as long as we have retention history on the e2e job

### Testgrid link

https://testgrid.k8s.io/kops-misc#e2e-kops-do-calico-dns-none

### Reason for failure (if possible)

This test creates an "echo hostname" server pod with hostNetwork. It then verifies that the pod's hostname matches the name of the node it runs on:

https://github.com/kubernetes/kubernetes/blob/3bfa9482fca675803c456ecbe4252b6525c9d021/test/e2e/network/service.go#L2665-L2670

These names match in the most common cluster configurations in GCP and AWS, but isn't a documented requirement. In other cluster configurations this test will fail due to this invalid assumption even though the behavior the test intends to verify is working as expected.

### Anything else we need to know?

Looking at a cluster-info dump of the cluster being tested, [the nodes](https://storage.googleapis.com/kubernetes-jenkins/logs/e2e-kops-do-calico-dns-none/1709688569984978944/artifacts/cluster-info/nodes.yaml) have a Hostname address that is the fully qualified name reported on the host and in the test's unexpected response.

I think it would be more appropriate for this test to compare against a node's unqualified Hostname address if one exists, otherwise falling back to the node name. Similar nodes on [AWS](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/15996/pull-kops-e2e-k8s-aws-calico/1710078083949662208/artifacts/cluster-info/nodes.yaml) and [GCP](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kops/15996/pull-kops-e2e-k8s-gce-cilium/1710078084008382464/artifacts/cluster-info/nodes.yaml) have Hostname addresses that (when unqualified) match their node names, so this test would continue to pass on these clusters.

Note that this test failure is on a Kops e2e job and relates to https://github.com/kubernetes/kubernetes/issues/120989

### Relevant SIG(s)

/sig testing
/sig network

**Comment by aojea** [comment]
Interesting, IIRC we had similar issues before, but just curious how does the node name is an IP address `    name: 10.106.0.3`

that is the reason why the test fails, because the node name is an IP address
```
{ failed [FAILED] Expected
    <string>: nodes-nyc3
to equal
    <string>: 10
In [It] at: test/e2e/network/util.go:181 @ 10/06/23 06:25:27.719
}
```

**Comment by hakman** [comment]
@aojea https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/getting-started.md#kubernetes-nodes-can-be-reached-via-ip-address-only

**Comment by aojea** [comment]
puff, open to ideas on how to deambiguate it on the tests

**Comment by rifelpet** [comment]
In this test I think its reasonable to compare against a Hostname address on the node, falling back to the node name if a Hostname address doesn't exist.

From the cluster-info dump of nodes above:
```yaml
- metadata:
    labels:
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: 10.106.0.6
      kubernetes.io/os: linux
      node-role.kubernetes.io/node: ""
      node.kubernetes.io/instance-type: c2-16vcpu-32gb
      region: lon1
      topology.hostpath.csi/node: 10.106.0.6
      topology.kubernetes.io/region: lon1
    name: 10.106.0.6
  spec:
    podCIDR: 100.96.3.0/24
    podCIDRs:
    - 100.96.3.0/24
    providerID: digitalocean://378038500
  status:
    addresses:
    - address: nodes-lon1.e2e-e2e-kops-do-calico-dns-none.k8s.local
      type: Hostname
    - address: 10.106.0.6
      type: InternalIP
    - address: 68.183.44.153
      type: ExternalIP
```
