### ISSUE TITLE
uneven Pods spreading across domains

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#121211]
## What 

Implement an uneven Pod spreading constraints between domains. Like domainA:domainB = x:y.

This requires us to introduce a new field to `topologySpreadConstraints` (name it `domains` for now). 
When `domains` field is non-empty, `maxSkew` should be nil. (vise-versa)

```yaml
- topologySpreadConstraints:
    # ...
    domains:
      - topologyLabel: "domainA"
        weight: 7
      - topologyLabel: "domainB"
        weight: 3
```

### Usecase1: spread Pods between zones

```yaml
- topologySpreadConstraints:
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
       matchLabels:
         app: foo
    topologyKey: "zone"
    domains:
      - topologyLabel: "zonea"
        weight: 7
      - topologyLabel: "zoneb"
        weight: 3
```

We have a DB in zoneA, so we want to schedule the Pods mostly to zoneA for better latency.
But, want to schedule smaller part of them to zone-b in case of zone failure.

### Usecases2: spread Pods for on-demand/spot

```yaml
- topologySpreadConstraints:
    labelSelector:
       matchLabels:
         app: foo
    topologyKey: "node-availability"
    domains:
      - topologyLabel: "on-demand"
        weight: 7
      - topologyLabel: "spot"
        weight: 3
```

So, we want to keep a large part of Pods running in on-demand Nodes because the spot instance might be deleted suddenly.
But, we're greedy, we want to keep some Pods in the spot Nodes for sure for the cost saving.

### Usecase3: gradual infrastructure migration

```yaml
- topologySpreadConstraints:
    labelSelector:
       matchLabels:
         app: foo
    topologyKey: "nodepool"
    domains:
      - topologyLabel: "old-nodepool"
        weight: 9 # will be reduced gradually
      - topologyLabel: "new-nodepool"
        weight: 1 # will be increased gradually
```

When we migrate workloads from one domain to another, we want to do it gradually.

## Why
 
Our company has one huge cluster to accommodate tons of Pods.

Currently, in order to achieve such uneven spreading, we need to choose either:
- create multiple deployments (+ HPA etc), one per domain. And somehow keep them to a specific ratio via some custom autoscaling solution.
  - It's hard to prepare multiple deployments in the first place when doing that for many services.(the usecase 2 / 3)
- use one deployment, but create the mutating webhook to add the required nodeaffinity to each Pod based on the current number of Pods in each domain. Also, descheduling should be done somehow.
- EDIT: Or follow [a similar way of Karpenter](https://github.com/kubernetes/kubernetes/issues/121211#issuecomment-1761840082). 

All are not simple solutions, which require engineering effort a lot and could cause serious problems in case of bugs.

Also, again we're greedy, we want to have a fallback mechanism like https://github.com/kubernetes/enhancements/issues/3990 when it comes to usecase 2. So, there could be a stockout problem in spot instance↓, and have to fallback to on-demand if necessary. That is something very hard to achieve with a custom solution, but can be _hopefully_ done with this proposal + the enhancement mentioned earlier.

> Spot VMs have no availability guarantees. Design your systems under the assumption that GKE might reclaim any or all your Spot VMs at any time, with no guarantee of when new instances become available.
https://cloud.google.com/kubernetes-engine/docs/concepts/spot-vms

/kind feature
/sig scheduling
/assign @sanposhiho

**Comment by sanposhiho** [comment]
@kubernetes/sig-scheduling-leads Any inputs on this?

**Comment by tzneal** [comment]
With Karpenter, the solution we've come up with is to use "virtual domains" (https://karpenter.sh/docs/concepts/scheduling/#on-demandspot-ratio-split).  


It has its own issues, but works for some users.

**Comment by sanposhiho** [comment]
@tzneal 
Thanks, that's an interesting approach. We'll consider following the similar until this feature comes.

**Comment by toVersus** [comment]
> Usecase1: spread Pods between zones

As a reason for Usecase 1, there may be instances where the cloud provider's inventory runs out in specific zones, preventing the provisioning of an sufficient number of nodes. For instance, suppose you attempted to manually scale nodes in advance to handle expected spikes in load, such as during Black Friday or New Year's Day. However, instances in specific zones may run out, preventing the even distribution of nodes across zones. It would be helpful if Pods could be scheduled unevenly based on the capacity of each zone, using `weight`.

**Comment by alculquicondor** [comment]
I'm not sure this should be built in the scheduler. For one, it's hard to make it work with autoscaling, just like it's hard to do regular spreading.
Maybe it's worth pursuing a subproject under sig-apps that has the ability to manage the size of multiple otherwise similar deployments?

**Comment by Huang-Wei** [comment]
@sanposhiho do you envision the new directive to be _hard_ requirements for all 3 usecases? (i read them as _soft_ ones)

**Comment by sanposhiho** [comment]
> For one, it's hard to make it work with autoscaling, just like it's hard to do regular spreading.

@alculquicondor could you elaborate? 
I don't see any autoscaling specific difficulty in this proposal. CA just imports the scheduling framework + plugins and simulates the scheduling with it, right? Or does CA do something special for topology spread?


> do you envision the new directive to be hard requirements for all 3 usecases? (i read them as soft ones)

I consider them to be hard ones.
So all of them want to make sure to put a certain % of pods to some domain, and trigger CA if necessary.

**Comment by pbetkier** [comment]
> Maybe it's worth pursuing a subproject under sig-apps that has the ability to manage the size of multiple otherwise similar deployments?

Have a look at https://github.com/kubernetes/autoscaler/blob/master/balancer/proposals/balancer.md, it’s about the exactly that. The KEP is almost implemented: code is there, what’s missing AFAIR is the component and user docs.

**Comment by kerthcet** [comment]
As we know, scheduler place pods one by one, so how it knows where to place the pod in the first place, say we have a deployment with 5 replicas, how to know where to locate the first pod since the weight is not met.

**Comment by kerthcet** [comment]
> > Maybe it's worth pursuing a subproject under sig-apps that has the ability to manage the size of multiple otherwise similar deployments?
> 
> Have a look at https://github.com/kubernetes/autoscaler/blob/master/balancer/proposals/balancer.md, it’s about the exactly that. The KEP is almost implemented: code is there, what’s missing AFAIR is the component and user docs.

Thanks @pbetkier for this input, so does this kep means Balancer will try to keep the balance via autoscaling?

**Comment by alculquicondor** [comment]
> I don't see any autoscaling specific difficulty in this proposal. 

The difficulty is around keeping the desired balance when nodes don't exist. Similar to what you are trying to solve in https://github.com/kubernetes/enhancements/issues/3990

It looks like the balancer proposal is an alternate solution to the same problem. @pbetkier who are the main developers on it? Maybe we can join efforts.

**Comment by pbetkier** [comment]
> Thanks @pbetkier for this input, so does this kep means Balancer will try to keep the balance via autoscaling?

It will change the replica size of deployments to meet configured balance conditions (e.g. 50-50 pod split between 2 similar deployments). You could call it autoscaling I guess, but it’s not related to HPA or VPA at all.

You can integrate it with HPA though, where HPA controls the total number of pods in N deployments and balancer controls how they are then split across specific deployments.

**Comment by pbetkier** [comment]
> It looks like the balancer proposal is an alternate solution to the same problem. @pbetkier who are the main developers on it? Maybe we can join efforts.

No developers working on it at the moment AFAIR. @mwielgus was the author of KEP and implementation, I was the reviewer.

If we decide it’s indeed needed and solves a significant problem then I guess I could take on the task to drive balancer to the end - make it usable by the public.

**Comment by sanposhiho** [comment]
> The difficulty is around keeping the desired balance when nodes don't exist. Similar to what you are trying to solve in kubernetes/enhancements#3990

I see. Yes, we'd want to use this feature with the fallback in any scenarios above.

@pbetkier Thanks, that project **does** look interesting. 🙂
Do you have any impression of pros/cons between the balancer and this proposal?

IIUC, in order to do spreading with the balancer, the developers need to prepare deployment per domain, right?
In the above usecase 2 and 3, we want to apply those spreading strategies to tons of deployments.
It'd be tough to duplicate deployments in duch a large scale. Also, HPA controller throughput is another concern - we'd have to create HPA for each deployment.
That's the first impression I have for the balancer.

**Comment by pbetkier** [comment]
You would need deployment per domain. It adds to the config overhead for sure. Perhaps you can mitigate with common helm templates or sth? Probably depends on the use case.

HPA is one per balancer, not per domain (deployment). The way it works is balancer is a scale resource itself. HPA scales the balancer only and it’s the balancer that distributes this scale across deployments (domains) under its control. So nothing changes for the number of HPAs.

**Comment by kerthcet** [comment]
> It will change the replica size of deployments to meet configured balance conditions

It's somehow overlapped with descheduler functionally, but bypassing the scheduler.

**Comment by sanposhiho** [comment]
Oh, wow the balancer has a scale subresource. 

@pbetkier Do you have any remaining task list for the balancer? 

@alculquicondor @Huang-Wei 
We need to dig into it more though, I don't have any critical concerns for our usecases for now. 
So, the question seems to be whether this uneven spreading feature would be popular or not -- whether it's worth implementing in the upstream scheduler or we can put effort into the Balancer and just prompt using the Balancer to every this kind of feature requests.

**Comment by toVersus** [comment]
I tried out Balancer. As one of the users who want to distribute Pods unevenly for a domain based on weight, I found Balancer to be promising. Thanks to the "create Deployment per domain" model, Balancer can scale in/out the replicas of Deployments while taking the domain into account. Furthermore, it offers flexibility to support combinations of multiple domains while having a fallback mode.

```yaml
apiVersion: balancer.x-k8s.io/v1alpha1
kind: Balancer
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  policy:
    policyName: proportional
    proportions:
      targetProportions:
        nginx: 20
        nginx-spot: 60
        nginx-spot-even-spread: 20
    fallback:
      startupTimeoutSeconds: 180
  targets:
  # On-Demand with evenly distributed Pods within the Zones
  - name: nginx
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: nginx
    minReplicas: 2
    maxReplicas: 4
  # Spot with evenly distributed Pods within the Zones
  - name: nginx-spot-even-spread
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: nginx-spot-even-spread
    minReplicas: 2
    maxReplicas: 20
  # Spot without Pod Topology Spread Constranints
  - name: nginx-spot
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: nginx-spot
    maxReplicas: 20
```

@pbetkier @mwielgus
The only thing that concerned me was the requirements to specify Balancer's `spec.replicas`. Since the HPA controller overwrites Balancer's `spec.replicas`, specifying it is mandatory, which means you have to update your manifests and apply changes each time the HPA controller changes the number of replicas for Balancer. This concern is not directly related to this thread, so I raised the feature requests in Autoscaler repository. (See https://github.com/kubernetes/autoscaler/issues/6207)
