### ISSUE TITLE
Custom Labels for PVC metrics

### ISSUE THREAD

**Issue by Sridhar-Konduri** [kubernetes/kubernetes#121251]
Is it possible to get any custom labels on the PVC?

https://github.com/kubernetes/kubernetes/blob/7d309e0104fedb57280b261e5677d919cb2a0e2d/pkg/kubelet/metrics/collectors/volume_stats.go#L97

If I have the following PVC template
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myPVC
  labels:
    app: my-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: local
  storageClassName: hostpath
```
We only get _namespace_ and _persistentvolumeclaim_ as labels
Example metric:
kubelet_volume_stats_used_bytes{namespace="myNamespace",persistentvolumeclaim="myPVC"} xxxxxx

Is it possible to get app or any other labels? It would be easy for aggregation if application has multiple pvc for each pod replica
