### ISSUE TITLE
The "kubernetes" endpoint is continuously updated when its subsets[0].addresses has been manually moved to subsets[0].notReadyAddresses

### ISSUE THREAD

**Issue by paveew** [kubernetes/kubernetes#121231]
### What happened?

Update "kubernetes" endpoint by moving `subsets[0].addresses` to `subsets[0].notReadyAddresses` and the kube-apiserver keep logging
```
...
Resetting endpoints for master service "kubernetes" to [x.x.x.x]
...
"HTTP" verb="GET" URI="/api/v1/namespaces/default/endpoints/kubernetes"
"HTTP" verb="PUT" URI="/api/v1/namespaces/default/endpoints/kubernetes"
...
// The same log is continuously printed.
```

### What did you expect to happen?

The `ReconcileEndpoints` shows that following steps will be performed under the condition mentioned earlier:

1. Currently the "kubernetes" endpoint struct is (We manually updated it):
```
  subsets:
  - notReadyAddresses:
    - ip: x.x.x.x
```
2. Since currently "kube-apiserver" is healthy in fact (we just manually update the endpoint), the "kubernetes" endpoint struct will first be constructed as: 
```
  subsets:
  - addresses:
    - ip: x.x.x.x
```
3. And then `RepackSubsets` is called so the "kubernetes" endpoint struct will be updated to
```
  // the struct has no changes compared to the current "kubernetes" endpoint struct
  subsets:
  - notReadyAddresses:
    - ip: x.x.x.x
```
4. However, the update request will still be sent and nothing will be updated

In such condition, I think either the "kubernetes" endpoint should be updated by moving `subsets[0].notReadyAddresses` back to `subsets[0].addresses`, or not sending an update request

### How can we reproduce it (as minimally and precisely as possible)?

Update 'kubernetes' endpoint  by moving `subsets[0].Addresses` to `subsets[0].notReadyAddresses`
```
  // before
  subsets:
  - addresses:
    - ip: x.x.x.x
```
```
  // after
  subsets:
  - notReadyAddresses:
    - ip: x.x.x.x
```

### Anything else we need to know?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
Major:"1", Minor:"27+"
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
N/A
```

</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>
