### ISSUE TITLE
kube-proxy bug in ipvs mode

### ISSUE THREAD

**Issue by ivanovpavel1983** [kubernetes/kubernetes#121272]
### What happened?

After kube-proxy switching in ipvs mode the routing can't go on control plane cluster nodes.
Kube-proxy config:
```
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    bindAddressHardFail: false
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: ""
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 5
    configSyncPeriod: 15m0s
    clusterCIDR: 10.244.0.0/16
    conntrack:
      maxPerCore: 32768
      min: 1024000
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    detectLocal:
      bridgeInterface: ""
      interfaceNamePrefix: ""
    detectLocalMode: ""
    enableProfiling: false
    healthzBindAddress: ""
    hostnameOverride: ""
    iptables:
      localhostNodePorts: null
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    ipvs:
      excludeCIDRs: []
      minSyncPeriod: 0s
      scheduler: rr
      strictARP: false
      syncPeriod: 30s
      tcpFinTimeout: 0s
      tcpTimeout: 0s
      udpTimeout: 0s
    kind: KubeProxyConfiguration
    logging:
      flushFrequency: 0
      options:
        json:
          infoBufferSize: "0"
      verbosity: 0
    metricsBindAddress: ""
    mode: "ipvs"
    nodePortAddresses: []
    oomScoreAdj: -999
    portRange: ""
    showHiddenMetricsForVersion: ""
    winkernel:
      enableDSR: false
      forwardHealthCheckVip: false
      networkName: ""
      rootHnsEndpointName: ""
      sourceVip: ""
  kubeconfig.conf: |-
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://kube-api.test.rost:6443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap 
```

Kube-proxy log after starting in ipvs mode:
![Clipboard - October 16, 2023 8_56 PM](https://github.com/kubernetes/kubernetes/assets/5180093/bc18ec18-e125-4d9d-a9ea-cb62aaa90499)

ipvsadm shows that the routing rules are correct:
![Clipboard - October 16, 2023 8_57 PM](https://github.com/kubernetes/kubernetes/assets/5180093/97538d40-7e2a-4016-8069-02b98d0ee799)

The starting error of calico install-cni container (the kubernetes service is unavailable)

![Clipboard - October 16, 2023 8_59 PM](https://github.com/kubernetes/kubernetes/assets/5180093/833e6376-662a-42a0-a714-0d25f7b17069)

In ip routes we can see wrong routing records for control plane nodes:
![Clipboard - October 16, 2023 8_58 PM](https://github.com/kubernetes/kubernetes/assets/5180093/320c3120-9ee7-4152-baa0-e234d1d4cbcc)

We can see that control plane nodes are unavailable from our server:

![Clipboard - October 16, 2023 9_04 PM](https://github.com/kubernetes/kubernetes/assets/5180093/23ce4da8-b872-4c20-b9bb-2d5b4761acb5)

After wrong routing rules deleting the resourses will be available.
But after server restarting Kube-proxy create wrong routes again.

### What did you expect to happen?

ipvs works automatically

### How can we reproduce it (as minimally and precisely as possible)?

Take 2 servers with centos 9 stream operation system with different network segments, configure kube-api balancer, install kubernetes with kubeadm operator, afterwards switch kube-proxy operation mode to ipvs and we can see that nothing works.

### Anything else we need to know?

In cluster there are 2 network segments (as can been seen from description 10.1.32.0/24, 10.1.36.0/24).

### Kubernetes version

1.28.2

### Cloud provider

bar metal cluster

### OS version

centos stream 9

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

containerd 1.6.24

### Related plugins (CNI, CSI, ...) and versions (if applicable)

calico 3.26.3
