### ISSUE TITLE
after kubernetes upgrade, all mongodb databases are gone

### ISSUE THREAD

**Issue by Hokutosei** [kubernetes/kubernetes#12136]
Greetings,

continuation from this problem https://github.com/GoogleCloudPlatform/kubernetes/issues/12134
thanks brendan, after the update, nodes were restarted and all containers started without problems, but there is one thing I am really afraid of my `mongodb` instances.

I'm using this yaml file, just cut the container list.
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb-shard1-controller
spec:
  replicas: 2
  selector:
    name: mongodb-shard1-controller
    version: v0
  template:
    metadata:
      labels:
        name: mongodb-shard1-controller
        version: v0
    spec:
      containers:
      - name: mongodb-node1
        image: gcr.io/app/mongodb3.0.4
        ports:
        - containerPort: 27017
          hostPort: 27031
        env:
          - name: REPL_SET
            value: kube_shard1
        volumeMounts:
          - mountPath: /data/db
            name: db-path
      volumes:
        - name: db-path
          source:
            emptyDir: {}
```

it may not be the best, but I am using it in production. after the nodes restarted, all replica sets of mongodb instances, could not connect on to each other, and other than that, databases are gone. and I could not get it back up w/databases. i don't know where is `/data/db` gone?

I'm using `GCP`, what is the best practice for database storages?
