### ISSUE TITLE
Requests to a service with no local endpoints are dropped rather than ICMP rejected

### ISSUE THREAD

**Issue by chenlin2001** [kubernetes/kubernetes#121371]
### What happened?

When setting internalTrafficPolicy: Local and see what happens when there are no available pods on the specific node:I exec into a pod on a specific node and ran the curl command:
curl micronaut-k8-sample:8080/stickiness/5 and got:
curl: (28) Failed to connect to micronaut-k8-sample port 8080 after 129261 ms: Couldn’t connect to server
(This api succeeds when running on a node that there are available pods of for service micronaut-k8-sample)
It's timing out according to the client timeout, and not getting an immediate rejection 

### What did you expect to happen?

An ICMP rejection that service is not available

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a service with internalTrafficPolicy:  Local. 
2. Have 2 nodes, and deployment with node affinity so no pods are available on one of the nodes.
3.  Exec into a pod on the node that doesn't have the pod and curl to that service 

### Kubernetes version

1.2.6

### Cloud provider

EKS

**Comment by thockin** [comment]
pkg/proxy/iptables/proxier.go:

```
1029         if !hasEndpoints {
1030             // The service has no endpoints at all; hasInternalEndpoints and
1031             // hasExternalEndpoints will also be false, and we will not
1032             // generate any chains in the "nat" table for the service; only
1033             // rules in the "filter" table rejecting incoming packets for
1034             // the service's IPs.
1035             internalTrafficFilterTarget = "REJECT"
1036             internalTrafficFilterComment = fmt.Sprintf(`"%s has no endpoints"`, svcPortNameString)
1037             externalTrafficFilterTarget = "REJECT"
1038             externalTrafficFilterComment = internalTrafficFilterComment
1039         } else {
1040             if !hasInternalEndpoints {
1041                 // The internalTrafficPolicy is "Local" but there are no local
1042                 // endpoints. Traffic to the clusterIP will be dropped, but
1043                 // external traffic may still be accepted.
1044                 internalTrafficFilterTarget = "DROP"
1045                 internalTrafficFilterComment = fmt.Sprintf(`"%s has no local endpoints"`, svcPortNameString)
1046                 serviceNoLocalEndpointsTotalInternal++
1047             }                                                                                                                                                                                        
1048             if !hasExternalEndpoints {
1049                 // The externalTrafficPolicy is "Local" but there are no
1050                 // local endpoints. Traffic to "external" IPs from outside
1051                 // the cluster will be dropped, but traffic from inside
1052                 // the cluster may still be accepted.
1053                 externalTrafficFilterTarget = "DROP"
1054                 externalTrafficFilterComment = fmt.Sprintf(`"%s has no local endpoints"`, svcPortNameString)
1055                 serviceNoLocalEndpointsTotalExternal++
1056             }
1057         }
```

If there are no endpoints at all, we do an ICMP reject, but if there are no policy-satisfying endpoints we drop. 

@danwinship do you recall why?

**Comment by danwinship** [comment]
The decision to make it work that way predates me, but my understanding is:

There is necessarily a race condition between when kube-proxy stops accepting connections for the service, and when the Load Balancer re-queries the HealthCheckNodePort and _notices_ that kube-proxy has stopped accepting connections for the service. During that time, it's possible that a client will try to connect to the service, and the LB will route it to a node that is no longer accepting connections for it. If we REJECT the packet, and the LB passes that REJECT back to the client, then the client fails with "can't connect". Whereas if we just DROP the packet then the client's TCP stack (or userspace UDP code) will eventually retry, and hopefully the next time the LB will have updated its endpoint set, and send the connection to a valid node, and it just looks to the client like the service was slow to respond or there was a momentary glitch in the internet.

(Previous discussion [here](https://github.com/kubernetes/kubernetes/pull/106497#discussion_r835673633), in the context of syncing the iTP and eTP behavior. @aojea suggested that clients should just retry on error, but there's a difference between this case (where you'd want to retry immediately) and the cases where we currently actually do REJECT (where you'd want to retry *eventually*, because there is legitimately something wrong with the service right now and if you try again it's just going to fail again).)

But of course, this all predates ProxyTerminatingEndpoints, and at this point, as long as the LB re-checks HealthCheckNodePorts more frequently than your pod termination grace period, then there's actually no race condition...

**Comment by uablrek** [comment]
/cc @aroradaman 

For proxy-mode=ipvs it might not be so simple to return an ICMP reject.

The use of "drop" is also documented at several places and how HealthCheck shall be used to direct traffic to nodes with local pods, e.g. [here](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport).

@chenlin2001 Is there a real use-case where this is a problem? Or is it just when doing tests?

IMO this is a documented and intended behavior, and not a bug. To alter it would be a feature request and should be well motivated.

**Comment by chenlin2001** [comment]
Hi, yes, this is a real use case. I want to implement "local first" approach - try through the InternalTransferPolicy to pods on same node, but if that doesn't succeed go to another node (will then go through external load balancer, to make sure it will pick an endpoint). This is possible if I get an immediate rejection, but if it's just dropped and I have to wait for client timeout this is much more problematic, and not sure I can do it.
In addition I would suggest adding to https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/ documentation about dropping also in addition to the existing documentation about NodePort. My use case is service with ClusterIp and internalTransferPolicy, as those are not the same use cases

**Comment by thockin** [comment]
> I want to implement "local first" approach - try through the InternalTransferPolicy to pods on same node, but if that doesn't succeed go to another node

@robscott one more vote for "PreferLocal"

@uablrek Is IPVS similar to the above (REJECT when no endpoints at all) or does it DROP there, too?

Even though I think this use-case is better handled with a PreferLocal, I do kind of lean towards REJECT as a better answer, when possible and safe.

**Comment by uablrek** [comment]
> Is IPVS similar to the above (REJECT when no endpoints at all) or does it DROP there, too?

Um, it turns out that "PreferLocal" is already implemented in proxy-mode=ipvs.

To test I create a deployment with affinity for some nodes, and access them from a node where no server PODs are started:
```
vm-002 ~ # kubectl get pods -o wide
NAME                       READY   STATUS    RESTARTS   AGE     IP         NODE     NOMINATED NODE   READINESS GATES
tserver-86ccfcf6f5-cnktc   1/1     Running   0          5m59s   11.0.4.3   vm-004   <none>           <none>
tserver-86ccfcf6f5-fsw8r   1/1     Running   0          5m59s   11.0.3.2   vm-003   <none>           <none>
tserver-86ccfcf6f5-h2prg   1/1     Running   0          5m59s   11.0.4.2   vm-004   <none>           <none>
tserver-86ccfcf6f5-pc2dq   1/1     Running   0          5m59s   11.0.3.3   vm-003   <none>           <none>
```
With proxy-mode=iptables:
```
vm-002 ~ # mconnect -address tserver.default.svc.xcluster:5001 -nconn 40
Failed connects; 40
Failed reads; 0
vm-003 ~ # mconnect -address tserver.default.svc.xcluster:5001 -nconn 40
Failed connects; 0
Failed reads; 0
tserver-86ccfcf6f5-pc2dq 27
tserver-86ccfcf6f5-fsw8r 13
```
With proxy-mode=ipvs:
```
vm-002 ~ # mconnect -address tserver.default.svc.xcluster:5001 -nconn 40
Failed connects; 0
Failed reads; 0
tserver-86ccfcf6f5-rvq8q 10
tserver-86ccfcf6f5-cztbt 10
tserver-86ccfcf6f5-qbsf8 10
tserver-86ccfcf6f5-szr52 10
vm-003 ~ # mconnect -address tserver.default.svc.xcluster:5001 -nconn 40
Failed connects; 0
Failed reads; 0
tserver-86ccfcf6f5-rvq8q 20
tserver-86ccfcf6f5-szr52 20
```
The example above is from the main netns on the nodes, but the result is the same when doing it from within a POD on the nodes.

**Comment by thockin** [comment]
Well that's....not right. :)

Is that intentional somewhere?

**Comment by uablrek** [comment]
> Well that's....not right. :)

Ok, but why drop? The src (pod-address) is preserved in any case and `externalTrafficPolicy: Local` works as "PreferLocal". I was not involved implementing internalTrafficPolicy for proxy-mode=ipvs, but my guess is that the same code as for `externalTrafficPolicy: Local` was re-used.

**Comment by uablrek** [comment]
> try through the InternalTransferPolicy to pods on same node, but if that doesn't succeed go to another node (will then go through external load balancer, to make sure it will pick an endpoint)

@chenlin2001 How will this work exactly? A try from a POD to the clusterIP doesn't work (drop or rejected), then what? Will it fall-back to a loadBalancerIP for the same service? If so, please use loadBalancerIP with `externalTrafficPolicy:Local` always. It will do exactly what you want automatically, and without performance penalty (no round-trip to an external LB)

**Comment by chenlin2001** [comment]
My setup is built to work on both Kubernetes on prem and on eks. I have a Traefik load balancer with following rule:
```
{{- if .Values.ingressroute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "micronaut-k8-sample.fullname" . }}
  labels:
{{ include "micronaut-k8-sample.labels" . | indent 4 }}
{{- with .Values.ingressroute.annotations }}
annotations:
  {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingressroute.host }}`)
      kind: Rule
      services:
        - name: {{ include "micronaut-k8-sample.fullname" . }}
          port: {{ int .Values.ingressroute.port }}
          kind: Service
{{- end }}
```
And the service is configured:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "micronaut-k8-sample.fullname" . }}
  labels:
    {{- include "micronaut-k8-sample.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: api
    - port: {{ .Values.management.port }}
      targetPort: {{ .Values.management.port }}
      protocol: TCP
      name: management
  internalTrafficPolicy: Local
  selector:
    {{- include "micronaut-k8-sample.selectorLabels" . | nindent 4 }}
```
So my service itself is ClusterIp, and not LoadBalancer/NodePort so I can't use the externalTrafficPolicy:Local option
