### ISSUE TITLE
Setting restart policy in init container and main container makes the pod manifest invalid

### ISSUE THREAD

**Issue by sathyanarays** [kubernetes/kubernetes#121498]
### What happened?

With "SidecarContainers" feature flag enabled, I tried setting `restartPolicy` for one of the init containers and the main container. The restart policy of the init container is set to "Always" and the restart policy of main container is set to "Never". The YAML manifest is considered invalid by the api-server with the  following error in the console.

```
The Pod "sidecar-test" is invalid: spec.containers[0].restartPolicy: Forbidden: may not be set for non-init containers
```

### What did you expect to happen?

Expected the pod to get deployed successfully and terminate all containers if the main container exited.

### How can we reproduce it (as minimally and precisely as possible)?

Enable "SidecarContainers" feature gate and do a kubectl apply of the following manifest:

```
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-test
  labels:
    role: myrole
spec:
  initContainers:
  - name: sidecar
    image: ubuntu:latest
    command: ["sleep"]
    args: ["3600"]
    restartPolicy: "Always"
  - name: init-container
    image: ubuntu:latest
    command: ["sleep"]
    args: ["5"]
  containers:
    - name: main
      image: ubuntu:latest
      command: ["sleep"]
      args: ["60"]
      restartPolicy: Never
```

### Kubernetes version

<details>

```console
Server version: v1.28.0
```

</details>

### Cloud provider

<details>
KIND
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
