### ISSUE TITLE
kubectl shows Pod status Completed if one of the containers exited with an Error

### ISSUE THREAD

**Issue by teoincontatto** [kubernetes/kubernetes#121563]
**What happened**:

Running a Job with two or more containers creates a Pod. If one of the container fails such Pod status in kubectl is shown as Completed if the name of such container is the last name of the container names ordered alphabetically.

**What you expected to happen**:

If the container who's name is the last name of the container names ordered alphabetically fails the Pod status in kubectl should be shown as Error.

**How to reproduce it (as minimally and precisely as possible)**:

```
cat << EOF | kubectl create -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  backoffLimit: 0
  completionMode: NonIndexed
  parallelism: 1
  suspend: false
  template:
    spec:
      restartPolicy: Never
      containers:
      - command:
        - /bin/sh
        - -exc
        - "true"
        name: a
        image: busybox
      - command:
        - /bin/sh
        - -exc
        - "false"
        name: z
        image: busybox
EOF
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):

```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.22.17
```

- Cloud provider or hardware configuration:

```
kind v0.15.0 go1.19 linux/amd64
```

- OS (e.g: `cat /etc/os-release`):

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by kannon92** [comment]
Is this behavior the same if you use just a naked pod?

**Comment by teoincontatto** [comment]
@kannon92 Tested right away and yes, same behavior.

**Comment by kannon92** [comment]
/remove-sig apps
/sig node

maybe @bobbypage or @smarterclayton have some thoughts on this one.

**Comment by kannon92** [comment]
Wait, can you confirm you see this in 1.28? 1.22 is out of support.

**Comment by teoincontatto** [comment]
Yes, confirmed with:

```
$ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
```

**Comment by ndixita** [comment]
@teoincontatto could you please confirm if you are able to see the same issue using kubelet readonly /pods?

**Comment by teoincontatto** [comment]
@ndixita I've tried with command `kubelet readonly /pods` but it throws an `unknown command readonly` did you meant something else?

```
# kubelet readonly /pods
E1102 08:16:35.635304   14314 run.go:74] "command failed" err="unknown command readonly"
# kubelet --version
Kubernetes v1.28.0
```

**Comment by Goend** [comment]
```
[root@qa-vpc-cni-node-3-s57fhiyhso4f ~]# kubectl get job
NAME   COMPLETIONS   DURATION   AGE
test   0/1           65s        65s
[root@qa-vpc-cni-node-3-s57fhiyhso4f ~]# kubectl describe job test
Name:             test
Namespace:        default
Selector:         batch.kubernetes.io/controller-uid=8c391b14-81d9-448e-8460-052b0ef5eb71
Labels:           batch.kubernetes.io/controller-uid=8c391b14-81d9-448e-8460-052b0ef5eb71
                  batch.kubernetes.io/job-name=test
                  controller-uid=8c391b14-81d9-448e-8460-052b0ef5eb71
                  job-name=test
Annotations:      batch.kubernetes.io/job-tracking: 
Parallelism:      1
Completions:      <unset>
Completion Mode:  NonIndexed
Start Time:       Thu, 02 Nov 2023 21:22:02 +0800
Pods Statuses:    0 Active (0 Ready) / 0 Succeeded / 1 Failed
Pod Template:
  Labels:  batch.kubernetes.io/controller-uid=8c391b14-81d9-448e-8460-052b0ef5eb71
           batch.kubernetes.io/job-name=test
           controller-uid=8c391b14-81d9-448e-8460-052b0ef5eb71
           job-name=test
  Containers:
   a:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -exc
      true
    Environment:  <none>
    Mounts:       <none>
   z:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -exc
      false
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason                Age   From            Message
  ----     ------                ----  ----            -------
  Normal   SuccessfulCreate      80s   job-controller  Created pod: test-2hgpg
  Warning  BackoffLimitExceeded  73s   job-controller  Job has reached the specified backoff limit

```
kube version
```
[root@qa-vpc-cni-node-3-s57fhiyhso4f ~]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.6-es", GitCommit:"aa2c39c6a6c61456ba2bfe7dc466ed2e4249a3a6", GitTreeState:"clean", BuildDate:"2023-09-15T09:23:11Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.6-es", GitCommit:"aa2c39c6a6c61456ba2bfe7dc466ed2e4249a3a6", GitTreeState:"clean", BuildDate:"2023-09-15T09:22:46Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by teoincontatto** [comment]
The problem is with the Pod status on kubectl:

```
$ kubectl get pod
NAME         READY   STATUS      RESTARTS   AGE
test-srvsp   0/2     Completed   0          8h
```

If I swap the containers name it will show the correct status:

```
$ kubectl get pod
NAME         READY   STATUS   RESTARTS   AGE
test-4rb7k   0/2     Error    0          4s
```
```

**Comment by teoincontatto** [comment]
And just for completeness of the results above. The first pod (where the issue occur) has the following output for the status of the containers:

```
$ kubectl get pod -o json | jq -c '[.items[].status.containerStatuses[].state.terminated.reason]'
["Completed","Error"]
```

And for the second Pod (with the correct output):

```
$ kubectl get pod -o json | jq -c '[.items[].status.containerStatuses[].state.terminated.reason]'
["Error","Completed"]
```

I am trying to figure out in which part of the code this table is generated by my Go understanding is quite poor so it will take time

**Comment by RandellP** [comment]
@kannon92 I am confused by what happened with this ticket.  It got closed... but after that you added it to SIG Node Bugs and moved it to Done.  We just upgraded to 1.30 (from something much older) and I am seeing this issue.  Is there somewhere that I am missing that explains why it was moved to Done?

**Comment by kannon92** [comment]
There was a board migration. This ticket was closed due to inactivity.

/reopen

**Comment by SergeyKanzhelev** [comment]
@RandellP this ticket is still marked as "needs-information" If you believe that this can be repro on supported k8s version and has steps to repro with enough details posted in the ticket, please comment here with the summary. It will help routing and triaging the bug

**Comment by RandellP** [comment]
@SergeyKanzhelev Is what @teoincontatto posted above missing anything?  He was on 1.28 which is at least supported for a little while longer. 
In my case it is cronjobs using linkerd sidecars.  If the cronjob container is alphabetically after linkerd-proxy and exits non-zero, then we see the issue.  If it is alphabetically before we don't.  So matches perfectly with his write up.

**Comment by SergeyKanzhelev** [comment]
/remove-triage needs-information
/remove-lifecycle rotten

seems more and more like a CLI issue.

**Comment by cybercoder** [comment]
Also my stand-alone nginx pod

```
image-repo                          0/1     Completed   0          98d    <none>
```
log shows:

```
2024/09/19 16:08:32 [notice] 1#1: signal 29 (SIGIO) received
2024/09/19 16:08:32 [notice] 1#1: signal 17 (SIGCHLD) received from 75
2024/09/19 16:08:32 [notice] 1#1: worker process 46 exited with code 0
2024/09/19 16:08:32 [notice] 1#1: worker process 42 exited with code 0
2024/09/19 16:08:32 [notice] 1#1: worker process 56 exited with code 0
2024/09/19 16:08:32 [notice] 1#1: worker process 63 exited with code 0
2024/09/19 16:08:32 [notice] 1#1: worker process 67 exited with code 0
2024/09/19 16:08:32 [notice] 1#1: worker process 73 exited with code 0
2024/09/19 16:08:32 [notice] 1#1: signal 29 (SIGIO) received
2024/09/19 16:08:32 [notice] 1#1: signal 17 (SIGCHLD) received from 42
2024/09/19 16:08:32 [notice] 1#1: signal 17 (SIGCHLD) received from 55
2024/09/19 16:08:32 [notice] 1#1: worker process 55 exited with code 0
2024/09/19 16:08:32 [notice] 1#1: signal 29 (SIGIO) received
2024/09/19 16:08:32 [notice] 1#1: signal 17 (SIGCHLD) received from 70
2024/09/19 16:08:32 [notice] 1#1: worker process 70 exited with code 0
2024/09/19 16:08:32 [notice] 1#1: exit
```
And it hasn't restarted!

**Comment by dshebib** [comment]
Testing this in e2e_node, the pod condition is set as failed. so likely a CLI issue

passing test: https://github.com/kubernetes/kubernetes/compare/master...dshebib:kubernetes:zTMP_PodStatusCompletedWhenContainerErrorTest

**Comment by SergeyKanzhelev** [comment]
@cybercoder if you interested to explore more - can you post the whole json pod status and the kubectl results?

The error may be somewhere in `pkg/printers/internalversion/printers.go`

**Comment by AnishShah** [comment]
sig-node triage:

This seems to be an issue with sig-cli and not sig-node issue.

/remove-sig node

**Comment by cybercoder** [comment]
> @cybercoder if you interested to explore more - can you post the whole json pod status and the kubectl results?
> 
> The error may be somewhere in `pkg/printers/internalversion/printers.go`

```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-09-24T23:47:58Z"
    message: Pod was terminated in response to imminent node shutdown.
    reason: TerminationByKubelet
    status: "True"
    type: DisruptionTarget
  - lastProbeTime: null
    lastTransitionTime: "2024-09-24T19:16:36Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-09-24T23:47:58Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-09-24T23:47:58Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-09-24T19:16:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://b2d815702bb45daeed52503d4047b4b013c5f8f39ba28844e346f42ff5f3ecdd
    image: registry.ik8s.ir/nginx:latest
    imageID: registry.ik8s.ir/nginx@sha256:04ba374043ccd2fc5c593885c0eacddebabd5ca375f9323666f28dfd5a9710e3
    lastState: {}
    name: repo
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://b2d815702bb45daeed52503d4047b4b013c5f8f39ba28844e346f42ff5f3ecdd
        exitCode: 0
        finishedAt: "2024-09-24T23:47:57Z"
        reason: Completed
        startedAt: "2024-09-24T19:17:36Z"
  hostIP: 172.16.20.202
  phase: Succeeded
  qosClass: BestEffort
  startTime: "2024-09-24T19:16:36Z"
```
