### ISSUE TITLE
Correct Keyword name for DisruptionsAllowed in PDB.

### ISSUE THREAD

**Issue by nikhilmaheshwari24** [kubernetes/kubernetes#121585]
When describing a PodDisruptionBudget (PDB) in text, JSON, or YAML format, the keyword used to represent the "Number of pod disruptions that are currently allowed" should ideally be `disruptionsAllowed`. This naming convention is more consistent with the typical JSON/YAML key naming practices. It not only adheres to the convention but also clearly conveys its meaning. Using `disruptionsAllowed` makes it instantly clear that it defines the allowed number of disruptions.

Furthermore, consistent naming practices in JSON and YAML are essential for clarity and maintainability. When key names align with their meaning, it becomes easier for humans and automated systems to understand and work with the data. This consistency helps reduce potential confusion and errors in managing resources like PodDisruptionBudgets in a Kubernetes cluster.

For example, a PodDisruptionBudget configuration in YAML format might look like this:

```yaml

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: my-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: my-app
  disruptionsAllowed: 1
 ```
By using `disruptionsAllowed` as the keyword, it is clear that this PDB allows only one disruption while keeping a minimum of two pods available. This naming convention helps maintain readability and understanding in the Kubernetes configuration.
