### ISSUE TITLE
Stuned deleting of a pod whose parents are job.

### ISSUE THREAD

**Issue by metanovii** [kubernetes/kubernetes#121605]
### What happened?

```
❯ k -n qa-lk-3900 get pod
NAME                               READY   STATUS        RESTARTS   AGE
cron-job-dashmail-28306992-9dcql   0/1     Terminating   0          2d18h
```
```
❯ k -n qa-lk-3900 get job
No resources found in qa-lk-3900 namespace.
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    vault.hashicorp.com/agent-init-first: "true"
    vault.hashicorp.com/agent-inject: "true"
    ...
  finalizers:
  - batch.kubernetes.io/job-tracking
  generateName: cron-job-dashmail-28306992-
  labels:
    batch.kubernetes.io/job-name: cron-job-dashmail-28306992
    cronjob: leadgid-my-leadgid
    job-name: cron-job-dashmail-28306992
  name: cron-job-dashmail-28306992-9dcql
  namespace: qa-lk-3900
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: cron-job-dashmail-28306992
spec:
  containers:
  ....

```

I also can't delete the finalizer :
```sh
❯ k -n qa-lk-3900 patch pod cron-job-dashmail-28306992-9dcql -p '{"metadata":{"finalizers":null}}'
The Pod "cron-job-dashmail-28306992-9dcql" is invalid: spec.initContainers: Forbidden: pod updates may not add or remove containers
```

### What did you expect to happen?

This problem appeared after the release batch.kubernetes.io/job-tracking

### How can we reproduce it (as minimally and precisely as possible)?

Just delete the namespace.

### Kubernetes version

<details>

```sh
❯ k version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.6
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```sh
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Linux hcloud-cluster-01-md-0-bb457 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
