### ISSUE TITLE
Job readiness gates

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#121681]
### What would you like to be added?

An alternative to `Job.spec.suspend` that allows multiple controllers to cooperate towards starting a Job.

This is analogous to scheduling gates https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/

### Why is this needed?

This would enable queueing of steps of a workflow.

For example, the job could have:
```
readinessGates:
  - kueue.k8s.io/suspend
  - snakemake.io/step
```

The job is only allowed to run (create pods) if all gates are removed.
In the case above, `snakemake.io/step` would be removed by snakemake when all the dependencies for this job are completed.

At this point, kueue would allow this job to compete for resources in the queue. When there is enough quota to run this job, Kueue would remove the `kueue.k8s.io/suspend`.

**Comment by alculquicondor** [comment]
I'll bring this to wg-batch after Kubecon

**Comment by andrewsykim** [comment]
Love the idea :) 

/cc

**Comment by sftim** [comment]
:thought_balloon: Building on this idea: CronJob could create its Jobs slightly ahead of schedule, and remove the readiness gate as the right moment arrives.

**Comment by alculquicondor** [comment]
Interesting... why would that be desirable?

**Comment by sftim** [comment]
`at` example
```yaml
---
# This Job doesn't start until the scheduled time,
# but it doesn't repeat.
apiVersion: batch/v1
kind: Job
metadata:
  name: not-yet
  annotations:
    k8s.example/not-before: '2023-11-03T00:05:00+0000'
spec:
  # readiness gates also imply suspend: true
  parallelism: 1
  completions: 42
  template:
    spec:
      containers:
      - name: example
        image: example-thing:v1
      restartPolicy: Never
  readinessGates:
  - job.k8s.example/run-job-at
```

---

Custom cron-like scheduling example
```yaml
---
# This is a gang scheduled job that requests 420 TiB of RAM, once an hour
# The control plane creates the 42 Jobs 90 seconds early, and then creates 42 unbound
# Pods moments later. The Pods for the CronJob have a DIFFERENT, related scheduling
# gate set. This triggers autoscaling to buy some expensive, chunky compute just in time.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: not-yet
  annotations:
    k8s.example/gang: "true"
    cron.k8s.example/early-creation: "90s"
spec:
  schedule: "42 * * * *"
  jobTemplate:
    # readiness gate for the Job also implies suspend: true
    parallelism: 42
    completions: 42
    template:
      spec:
         readinessGates:
         - job-autoscaling.k8s.example/autoscaling: "true"
        containers:
        - name: example
          resources:
            requests:
             memory: "10203Gi"
             cpu: "2"
            limits:
              memory: "16384Gi"
              cpu: "2"
          image: a-different-thing:v1
        restartPolicy: Never
    readinessGates:
    - job-autoscaling.k8s.example/autoscaling: "true"
```

**Comment by dejanzele** [comment]
Sounds like something from which a lot of batch schedulers could benefit!

**Comment by alculquicondor** [comment]
Let's bring the topic to wg-batch on Dec 7th

**Comment by everpeace** [comment]
I love the idea too.

> The job is only allowed to run (create pods) if all gates are removed.

Does this proposal assume to re-add the readiness gate unlike pod's one??

>  An alternative to Job.spec.suspend that allows multiple controllers to cooperate towards starting a Job.


If this is the main purpose of this proposal, feature consistency would be nice to have.

**Comment by kerthcet** [comment]
Can this be more grand as https://github.com/kubernetes/kubernetes/issues/107294 describes?

**Comment by tenzen-y** [comment]
> > The job is only allowed to run (create pods) if all gates are removed.
> 
> Does this proposal assume to re-add the readiness gates unlike pod's one??

@everpeace Yes, correct. This feature is Job level, not Pod level. So these gates are separate from pod's one.

**Comment by tenzen-y** [comment]
> Can this be more grand as #107294 describes?

@kerthcet Do you mean the idea like "JobReadinessGate sub-resource"?

**Comment by everpeace** [comment]
> This feature is Job level, not Pod level. So these gates are separate from pod's one.

Thanks for the quick reply. Let me confirm your answer🙇. As you might know, Pod's readiness gate does NOT allow to add readiness gate item once the gate became empty.

Does this job's readiness gate proposal allow the third party controllers to add readiness gate even after readiness got empty once?? I didn't catch the intention of your "This feature is Job level, not Pod level" sentence 🙇

**Comment by kerthcet** [comment]
> @kerthcet Do you mean the idea like "JobReadinessGate sub-resource"?

Something like that independent of the specification.

**Comment by alculquicondor** [comment]
> Does this job's readiness gate proposal allow the third party controllers to add readiness gate even after readiness got empty once??

I haven't decided. For the purposes of queueing (preemption, more specifically), it's more useful if the gates can be added back. Since it's similar to the existing `suspend` field, it can be easily justified.

Re: subresource

I don't think I would have the bandwidth to work through it. But I would be happy to support anyone who is willing to pursue it. Let's talk in the wg-batch.

**Comment by tenzen-y** [comment]
> @tenzen-y Thanks for the quick reply. Let me confirm your answer🙇. As you might know, Pod's readiness gate does NOT allow third party controllers to add readiness gate items once the gate became empty.
> 
> Does this job's readiness gate proposal allow the third party controllers to add readiness gate even after readiness got empty once??
> 

@everpeace This is a good point. We haven’t decided yet if we will make the JobReadinessGate mutable after jobs start.
TBH, I'm wondering if we should allow JobReadinessGate to be mutable since we can use `suspend` to stop job situations.

However, we're open if we make it mutable or immutable. Let us know if you have some use cases.

**Comment by tenzen-y** [comment]
Ah, Aldo had already responded.

**Comment by everpeace** [comment]
> Since it's similar to the existing suspend field, it can be easily justified.

Yeah, the feature consistency would be nice in Job. I actually prefer this because it can make queues flexible(preemption, back-filling, etc.). 

But, if it goes with the same name ("readiness gate"), the semantic difference from pod's readiness gate should be emphasized or clearly noted in documents.

**Comment by tenzen-y** [comment]
> But, if it goes with the same name ("readiness gate"), I think the semantic difference from pod's readiness gate should be emphasized or clearly noted in documents.

That makes sense.

**Comment by everpeace** [comment]
> TBH, I'm wondering if we should allow JobReadinessGate to be mutable since we can use suspend to stop job situations.

hmm, but, the main motivation of introducing JobReadinessGate is "to allow multiple controllers to cooperate towards suspending/resuming a Job.", right?? If so, personally, "it can use `suspend` to stop the job after gate was opened(became empty)" would not be consistent a bit.

**Comment by liggitt** [comment]
are readiness gates considered to be ordered? are controllers expected to recognize specific other gate names, or generically cooperate with unspecified other gates?

**Comment by sftim** [comment]
> are readiness gates considered to be ordered?

I propose that they aren't that we document that they aren't: controllers should be written to make jobs ready whenever that's feasible.

I can also see challenges there. Would a controller that removes a readiness gate (“Yes, lots of cheap renewable energy, let's compute!”) be able to put it back when the situation changes (“it's dark now; grid running on coal”)

**Comment by sftim** [comment]
> This "delay pod creation by honoring podTemplate's schedulingGates" pattern can be generic to any custom FooJob controller.

Could go further: create Pods for the Job as soon as
1. the Pod template's `schedulingGates` field does not contain any gate not listed in [some array]
2. the Job is also not suspended using the existing, GA mechanism

Example:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-billion-digits
spec:
  # this check is an AND requirement with the existing "suspend" field
  suspendWhileSchedulingGatesDefined:
    - example.com/foo # not yet set; might turn up before the job unsuspends
                      # if something else doesn't set that gate, this is a no-op
    - wait-for-cheap-compute # cluster-private 
  template:
    spec:
        schedulingGates:
         - name: example.com/bar # Once the job unsuspends, Pods get created with this scheduling gate set;
                                 # something else has to remove that scheduling gate on the one Pod that
                                 # this Job owns
         - name: wait-for-cheap-compute
      containers:
      - name: pi
        image: calculate-pi::3.141592654
        command: ["calculate",  "--digits", "1000000000"]
      restartPolicy: Never
```
