### ISSUE TITLE
pod was rescheduled to node which being shutdown

### ISSUE THREAD

**Issue by yylt** [kubernetes/kubernetes#121843]
### What happened?

the pod yaml is below. it created by ReplicaSet controller. 

```
...
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: redis-67d469c688
    uid: 4ba681de-ed59-4860-883b-cb90927904fb
...
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300

```

when node-5 shutdown, the pod had been scheduler on node-5, it's obvious that the node-5 is unable to run the container because the node status is false or unknown.

```
$ kubectl get po -n redis -w -owide
 redis-67d469c688-829rs         0/1     Terminating   0             4m59s    <none>        node-5   <none>           <none>
 redis-67d469c688-zv9k7         0/1     Pending       0             0s    <none>        <none>   <none>           <none>
 redis-67d469c688-zv9k7         0/1     Pending       0             0s    <none>        node-5   <none>           <none>

$kubectl get no node-5 -o yaml
...
  - lastHeartbeatTime: "2023-11-11T00:35:13Z"
    lastTransitionTime: "2023-11-11T00:35:13Z"
    message: node is shutting down
    reason: KubeletNotReady
    status: "False"
    type: Ready
...

```

As seen above, the pod is scheduled to the node that Ready type is `False` again.

### What did you expect to happen?

after node shutdown, pods should not be scheduled to node which Ready type is `False` 

### How can we reproduce it (as minimally and precisely as possible)?

1 login node
2 shutdown -h

### Anything else we need to know?

maybe should add new filter plugin on kube-scheduler, the plugin work on `node.conditions[Ready]`. filter node when node condition is below

```
    reason: KubeletNotReady
    status: "False"
    type: Ready
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.7", GitCommit:"c1968c4ab8caf96ac11e5d4c51e48c3695651e29", GitTreeState:"clean", BuildDate:"2023-11-01T13:16:25Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.7", GitCommit:"c1968c4ab8caf96ac11e5d4c51e48c3695651e29", GitTreeState:"clean", BuildDate:"2023-11-01T13:16:03Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:

$ uname -a
Linux master-1-ld5iqlu6vxf6.novalocal 4.19.90-25.27.v2101.ky10.x86_64 #1 SMP Fri May 26 15:05:05 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nayihz** [comment]
Pod could be scheduled because you have added toleration for `node.kubernetes.io/unreachable` taint.

**Comment by AxeZhan** [comment]
Taint "node.kubernetes.io/unschedulable" should be added during terminating.

**Comment by yylt** [comment]
i know that. It had been described on https://kubernetes.io/docs/reference/scheduling/config/. 

why not to add new plugin for this situation?

**Comment by AxeZhan** [comment]
Plugin `NodeUnschedulable` already done the same thing. Which checks `node.spec.unschedulable`.  
My opinion is: scheduler should only be aware of this field for simplicity. 
If anything goest wrong and a node is not `Unschedulable` now, but the taint is not added correctly, it should be kubelet to take care of.

**Comment by yylt** [comment]
could we add new `NodeCondition`  plugin to https://github.com/kubernetes-sigs/scheduler-plugins ?

**Comment by utam0k** [comment]
> could we add new `NodeCondition` plugin to https://github.com/kubernetes-sigs/scheduler-plugins ?

As @AxeZhan mentioned, it should take care of the kubelet, not the scheduler, because the kubelet is responsible for the node.
Why not first look at how Kubelet determines the state of a node?

**Comment by yylt** [comment]
> > could we add new `NodeCondition` plugin to https://github.com/kubernetes-sigs/scheduler-plugins ?
> 
> As @AxeZhan mentioned, it should take care of the kubelet, not the scheduler, because the kubelet is responsible for the node. Why not first look at how Kubelet determines the state of a node?

actually, [the issue](https://github.com/kubernetes/kubernetes/issues/109998) had descript what happen when node shutdown. 

Now question is why schedule pod to node which being shutdown?

**Comment by utam0k** [comment]
> Now question is why schedule pod to node which being shutdown?

I guess the nodes you mentioned didn't unschedulable `node.spec.unschedulable` by kubelet.

**Comment by yylt** [comment]
umm..  
The pod which created by `Deployment` or `StatefulSet` controller would add tolerations, like this

```
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

IMO, even if node have taints `node.kubernetes.io/unreachable`, but the pod could also schedulerd on this node.
