### ISSUE TITLE
Apply for node will failed in  IP dual stack enviroment, with setting --server-side=true

### ISSUE THREAD

**Issue by jiangyouP** [kubernetes/kubernetes#121896]
### What happened?

I use helm to apply my node patch, which is going to add some labels to node.But I get error like this: `Error from server: failed to create manager for existing fields: failed to convert new object (/master1; /v1, Kind=Node) to smd typed: .status.addresses: duplicate entries for key [type="InternalIP"]`

### What did you expect to happen?

apply success without error

### How can we reproduce it (as minimally and precisely as possible)?

1.Prepare a node with IP dual stack. Do `kubectl get node -oyaml master1` and you can see it like：
```
status:
  addresses:
  - address: 192.168.75.222
    type: InternalIP
  - address: 3fff:75:4000:0:192:168:75:222
    type: InternalIP
  - address: master1
    type: Hostname
``` 
2. Do  ` kubectl apply -f node.yaml --server-side=true`. The node.yaml can like this:
```
kind: Node
apiVersion: v1
metadata:
  name: master1
  labels:
    test: ''
``` 

### Kubernetes version

<details>

```console
$ kubectl version
v1.25.3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="EulerOS"
VERSION="2.0 (SP11x86_64)"
ID="euleros"
VERSION_ID="2.0"
PRETTY_NAME="EulerOS 2.0 (SP11x86_64)"
ANSI_COLOR="0;31"

$ uname -a

Linux master1 5.10.0-60.18.0.50.h1002.eulerosv2r11.x86_64 #1 SMP Thu Sep 7 13:46:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
