### ISSUE TITLE
svc can't find a pod started via manifest file

### ISSUE THREAD

**Issue by farcaller** [kubernetes/kubernetes#12194]
Given a kubelet running with `--config=/etc/kubernetes/manifests` and a pod defined in a manifest:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: prometheus
spec:
  ...
```

the pod is reasonably identical to pods started by apiserver from the `kubectl` perspective. However, it's not possible to bind a service to it:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - port: 443
  selector:
    name: prometheus-da
```

can't find anything:

```
% kubectl describe svc/prometheus
Name:			prometheus
Namespace:		default
Labels:			<none>
Selector:		name=prometheus-da
Type:			ClusterIP
IP:			10.100.217.233
Port:			<unnamed>	443/TCP
Endpoints:		<none>
Session Affinity:	None
No events.
```

This is confusing, given kubectl talks to apiserver and gets the metadata-based pods I'd expect no difference with how you can interact with them, specifically given there's really no easy way from user to figure out if the pod is defined from metadata or apiserver.
