### ISSUE TITLE
Kubernetes: failed creating expose service 'clabernetes/cicd-lab-core1' error: Service "cicd-lab-core1" is invalid: spec.ports: Invalid value

### ISSUE THREAD

**Issue by bharmarsameer** [kubernetes/kubernetes#121991]
Hello,

I have a yml file as below 

```
---
apiVersion: topology.clabernetes/v1alpha1
kind: Containerlab
metadata:
  name: cicd-lab
  namespace: clabernetes
spec:
  
  config: |-
    name: cicd-lab
    topology:
      nodes:
        
          core1:
            kind: ceos
            image: ceos:4.30.3M
          core2:
            kind: ceos
            image: ceos:4.30.3M
      links:
        
          - endpoints: ['core1:eth1', 'core2:eth1']

``` 
When I try to do kubectl apply -f it throws below error

CRITICAL |     topology-containerlab | failed creating expose service 'clabernetes/cicd-lab-core1' error: Service "cicd-lab-core1" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"port-161-udp", Protocol:"UDP", AppProtocol:(*string)(nil), Port:161, TargetPort:intstr.IntOrString{Type:0, IntVal:60000, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-21-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:21, TargetPort:intstr.IntOrString{Type:0, IntVal:60000, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-22-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:22, TargetPort:intstr.IntOrString{Type:0, IntVal:60001, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-23-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:23, TargetPort:intstr.IntOrString{Type:0, IntVal:60002, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-80-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:80, TargetPort:intstr.IntOrString{Type:0, IntVal:60003, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-443-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:443, TargetPort:intstr.IntOrString{Type:0, IntVal:60004, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-830-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:830, TargetPort:intstr.IntOrString{Type:0, IntVal:60005, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-5000-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:5000, TargetPort:intstr.IntOrString{Type:0, IntVal:60006, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-5900-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:5900, TargetPort:intstr.IntOrString{Type:0, IntVal:60007, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-6030-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:6030, TargetPort:intstr.IntOrString{Type:0, IntVal:60008, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-9339-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:9339, TargetPort:intstr.IntOrString{Type:0, IntVal:60009, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-9340-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:9340, TargetPort:intstr.IntOrString{Type:0, IntVal:60010, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-9559-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:9559, TargetPort:intstr.IntOrString{Type:0, IntVal:60011, StrVal:""}, NodePort:0}, core.ServicePort{Name:"port-57400-tcp", Protocol:"TCP", AppProtocol:(*string)(nil), Port:57400, TargetPort:intstr.IntOrString{Type:0, IntVal:60012, StrVal:""}, NodePort:0}}: may not contain more than 1 protocol when type is 'LoadBalancer'

Any help is greatly appreciated. I am fairly new to kubernetes

/sig kubernetes
