### ISSUE TITLE
Kubernetes job completed event propagation take around ~20min for 5k jobs

### ISSUE THREAD

**Issue by rstreics** [kubernetes/kubernetes#121990]
### What happened?

I'm running self-hosted powerfull  cluster(5 control-plane nodes). What we have noticed that job completion increases proportionally with amount of parallel jobs running in cluster. 
Increasing `concurrent-cron-job-syncs`,`kube-api-qps`, `event-qps` have some effects, but not in a way that it would make it scalable.

Stats: 
| Job Count  | Job Finished Event Latency |
| ------------- | ------------- |
| 10  | ~2s  |
| 1000  | ~1min  |
| 5000  | ~20min  |

[csv_1000jobs](https://gist.github.com/rstreics/122002689c8b3f7c1b951f1a87f1e99e), [csv_5000_jobs](https://gist.github.com/rstreics/451c616227f6072d425e6538c18f66fa)

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: '[unique job id goes here]'
  namespace: default
spec:
  template:
    metadata:
      name: '[unique job id goes here]'
      namespace: default
    spec:
      containers:
      - name: test
        image: alpine:3
        command: ['sleep', '2']
      restartPolicy: Never
```

### What did you expect to happen?

Job completed event latency shouldn't be increasing linearly with amount of parallel jobs

### How can we reproduce it (as minimally and precisely as possible)?

Run 1-5k jobs with just sleep 2s, measure `received_success_event` - `container_finished` 

### Kubernetes version

<details>

```console
❯ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```

</details>

### Cloud provider

self-hosted, kubespray

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux node1 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
