### ISSUE TITLE
cannot Specify  the path where PV data are stored?

### ISSUE THREAD

**Issue by lauradavidd** [kubernetes/kubernetes#122098]
I started to learn Kubernetes by creating  stack. For my MySQL database I have created a persistent volume and persistent volume claim but now I came across a problem where I can't find the place where my PV files are stored.
I was hoping that my everything from Pod's  would be backed up at the host's  directory but that doesn't seem to happen for me.

 Help me to find the data to get stored at PV and  the location of PV stored.

**Comment by niranjandarshann** [comment]
@lauradavidd  can you please provide the pv.yaml and pvc.yaml file that you are using for pv and pvc? as you are  asking for PV so please provide the yaml file. for which we can better help you out.

**Comment by lauradavidd** [comment]
@niranjandarshann  sure.

**Comment by lauradavidd** [comment]
MY PV.yaml file
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydata_pv
  labels:
    app: mysql
spec:
  storageClassName: datamanual
  capacity:
    storage: 4Gi
  volumeMode: Files
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/datastack/pvstorage"
```

MY PVC.yaml file 
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydata_pvc
  labels:
    app: mysql
spec:
  storageClassName: datamanual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi`
