### ISSUE TITLE
One service manages multiple deployment instances. Service uses nodePort type. Upstream traffic is distributed unevenly through different deployment through nodePort.

### ISSUE THREAD

**Issue by Ljohn001** [kubernetes/kubernetes#122015]
### What happened?

Due to business requirements, a single Service is needed to manage multiple deployments for a simple grayscale scheme. When I associated a deployment tag change to an existing Service, I found that the traffic was skewed. Traffic access path: nginx --> Service nodePort --> deployment1
                                              |--> deployment2

### What did you expect to happen?

It was found that when grayscale a new deployment pod, severe traffic skew occurred.

### How can we reproduce it (as minimally and precisely as possible)?

Recurrence scheme
first run with deployment-1, the traffic is load balanced, but when deployment-2 is enabled, the traffic will tilt.
Simulation request
```
for i in `seq 1 10000`;do sleep 1 ; curl -s  http://10.4.83.27:8081/ ;done | tee /tmp/1.log

First time
cat /tmp/12.log | grep http-deployment-1 | wc -l
94
cat /tmp/12.log | grep http-deployment-2 | wc -l
6

Try again
cat /tmp/13.log | grep http-deployment-2 | wc -l
378
cat /tmp/13.log | grep http-deployment-1 | wc -l
622

```
Upstream load balancing configuration
```
    upstream backend {
        server 10.4.87.33:33632;
        server 10.4.87.34:33632;
        server 10.4.87.35:33632;
        keepalive 300;
    }

    server {
        listen 8081;
        server_name ljohn.com;

        location / {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
```

deployment-1
```
# Deployment 2
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: http-deployment-1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      deployment: one
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        deployment: one
    spec:
      containers:
        - image: nginx:1.20.1
          imagePullPolicy: IfNotPresent
          name: http
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: html-files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: html-files
          configMap:
            name: html-files-config-one
---
# ConfigMap for NGINX configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
---
# ConfigMap for HTML file
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-files-config-one
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Deployment Name</title>
    </head>
    <body>
      <h1>Deployment Name: http-deployment-1</h1>
    </body>
    </html>
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
```

deployment-2
```
# Deployment 2
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: http-deployment-2
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      deployment: two
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        deployment: two
    spec:
      containers:
        - image: nginx:1.20.1
          imagePullPolicy: IfNotPresent
          name: http
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: html-files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: html-files
          configMap:
            name: html-files-config-two
---
# ConfigMap for NGINX configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }
---
# ConfigMap for HTML file
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-files-config-two
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Deployment Name</title>
    </head>
    <body>
      <h1>Deployment Name: http-deployment-2</h1>
    </body>
    </html>
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T12:15:37Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T12:07:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux HZPL004087021 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeasz 2.2.4 ，Binary installation
</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI: docker 19.03.14 
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275
 Built:             Tue Dec  1 19:14:24 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275
  Built:            Tue Dec  1 19:21:08 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc93+dev
  GitCommit:        6538f9f20ac52569d1ffa26123774b57c7bf75ae-dirty
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI : calico v3.15.3
</details>

**Comment by aojea** [comment]
Why don't you use an Ingress?

**Comment by Ljohn001** [comment]
> Why don't you use an Ingress?

For some historical reasons, the ingress version of this cluster is older than 0.32 and cannot better support returning to the original IP, so this service uses the nodePort method

**Comment by aroradaman** [comment]
> first run with deployment-1, the traffic is load balanced, but when deployment-2 is enabled, the traffic will tilt.

[keepalive](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive) maintains connection cache, reuses same TCP sockets .. so it is possible when deployment-2 is rolled out nginx is still using old/open TCP connections (deployment-1) causing a skew in traffic. 

 

> for i in `seq 1 10000`;do sleep 1 ; curl -s  http://10.4.83.27:8081/ ;done

Also noticed you are running this sequentially, load-balancing won't be of much use here as nignx will try its best to use any existing/open TCP connection as part of optimisation. 

Can you run this in parallel and check if skewness still presists ?

**Comment by Ljohn001** [comment]
> > first run with deployment-1, the traffic is load balanced, but when deployment-2 is enabled, the traffic will tilt.
> 
> [keepalive](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive) maintains connection cache, reuses same TCP sockets .. so it is possible when deployment-2 is rolled out nginx is still using old/open TCP connections (deployment-1) causing a skew in traffic.
> 
> > for i in `seq 1 10000`;do sleep 1 ; curl -s  http://10.4.83.27:8081/ ;done
> 
> Also noticed you are running this sequentially, load-balancing won't be of much use here as nignx will try its best to use any existing/open TCP connection as part of optimisation.
> 
> Can you run this in parallel and check if skewness still presists ?

First of all, thank you for your enthusiastic reply. 
Long connections may cause traffic skew, but this problem seems to be extreme. Using an actual business instance to reproduce, almost all the traffic will be sent to the new grayscale instance, causing the new instance to The request volume is too high to respond.

In addition, I tried concurrent access, and the problem still exists. Testing process:
```
time seq 1 2000 | parallel -j5 curl -s "http://10.4.83.27:8081/" >> /tmp/2000.txt

cat /tmp/2000.txt | grep 'http-deployment-1' | wc -l
1590
cat /tmp/2000.txt | grep 'http-deployment-2' | wc -l
410
```
> The reproduction plan is a bit crude. This problem is an actual production gateway instance. The normal Qps is 300/s. After grayscale, there is a serious traffic skew.

**Comment by uablrek** [comment]
K8s v1.17.16 is not supported (it's super-old!), and _a lot_ has changed, for instance endpoints->endpointslices, which is likely relevant in this case.

I will try to re-create this on v1.28.4, but with a different but similar setup:
1. Create a deployment and a service with nodePort
2. Verify distribution from external clients
3. Add another deployment with the same selector, and same "replicas"
4. Check if the new deployment gets a too-large share of new connections

All connections are closed between the tests, and client (src) addresses will be different

**Comment by uablrek** [comment]
Result: distribution is even. No skew occurred.

Tests using [mconnect](https://github.com/Nordix/mconnect).

One deployment:
```
# mconnect -address 192.168.1.2:32130 -nconn 100
Failed connects; 0
Failed reads; 0
deployment1-79647cfbbb-nvphf 25
deployment1-79647cfbbb-7qfvn 25
deployment1-79647cfbbb-h2sm4 25
deployment1-79647cfbbb-5h8vl 25
```
Two deployments:
```
# mconnect -address 192.168.1.2:32130 -nconn 100
Failed connects; 0
Failed reads; 0
deployment1-79647cfbbb-nvphf 13
deployment2-84c8644cf7-qs7pl 12
deployment1-79647cfbbb-7qfvn 12
deployment2-84c8644cf7-k2jr4 12
deployment1-79647cfbbb-h2sm4 13
deployment2-84c8644cf7-4p728 12
deployment1-79647cfbbb-5h8vl 13
deployment2-84c8644cf7-pjqhq 13
```
Re-create:
```
kubectl create -f deployment1.yaml
kubectl create -f svc-deployment.yaml
# Check distribution
kubectl create -f deployment2.yaml
# (wait a bit, then...)
# Check distribution again
```


<details><summary>Manifests</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deployment1
      service: deployment
  template:
    metadata:
      labels:
        app: deployment1
        service: deployment
    spec:
      containers:
      - name: tserver
        image: docker.io/uablrek/tserver:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVERS
          value: "mconnect"
        ports:
        - name: mconnect
          containerPort: 5001
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deployment2
      service: deployment
  template:
    metadata:
      labels:
        app: deployment2
        service: deployment
    spec:
      containers:
      - name: tserver
        image: docker.io/uablrek/tserver:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVERS
          value: "mconnect"
        ports:
        - name: mconnect
          containerPort: 5001
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: deployment
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    service: deployment
  type: NodePort
  ports:
  - port: 5001
    name: mconnect
```

</details>
