### ISSUE TITLE
v1.27.0   ServiceAccount still have no permission in a pod after rolebinding

### ISSUE THREAD

**Issue by chaseSpace** [kubernetes/kubernetes#122010]
### What happened?

```
$ kubectl describe role pod-reader      
Name:         pod-reader
Labels:       <none>
Annotations:  <none>
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
  pods       []                 []              [get watch list]

# Focusing on [sa1]
$ kubectl describe rolebinding read-pods  
Name:         read-pods
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  Role
  Name:  pod-reader
Subjects:
  Kind            Name   Namespace
  ----            ----   ---------
  User            user2  
  User            user3  
  ServiceAccount  sa1   

$ cat pod_associate_serviceaccount.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-sa-longtime
  labels:
    app: nginx
spec:
  serviceAccountName: sa1
  containers:
    - name: nginx-container
      image: nginx

# Enter container to test with curl, got 403
$ kubectl exec -it nginx-sa-longtime -- bash   
root@nginx-sa-longtime:/# TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
root@nginx-sa-longtime:/# CACERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
root@nginx-sa-longtime:/# curl --cacert $CACERT --header "Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local/api/v1/namespaces/defaut/pods
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "pods is forbidden: User \"system:serviceaccount:default:sa1\" cannot list resource \"pods\" in API group \"\" in the namespace \"defaut\"",
  "reason": "Forbidden",
  "details": {
    "kind": "pods"
  },
  "code": 403
}
```

### What did you expect to happen?

I should able to get pods' list, not 403.

### How can we reproduce it (as minimally and precisely as possible)?

```
kubectl create serviceaccount sa1
```
secret-serviceaccount.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
  namespace: default
  annotations:
    kubernetes.io/service-account.name: sa1 
type: kubernetes.io/service-account-token
```
rbac_role.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: [ "" ] 
    resources: [ "pods" ] 
    verbs: [ "get", "watch", "list" ]
```
rbac_rolebinding.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default 
subjects: 
  - kind: User
    name: user2 
  - kind: User
    name: user3
  - kind: ServiceAccount
    name: sa1
    apiGroup: ""
roleRef:
  kind: Role       
  name: pod-reader  
  apiGroup: rbac.authorization.k8s.io
```
pod_associate_serviceaccount.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-sa-longtime
  labels:
    app: nginx
spec:
  serviceAccountName: sa1
  containers:
    - name: nginx-container
      image: nginx
```

### Kubernetes version

v1.27.0

### Cloud provider

no
