### ISSUE TITLE
Pod ready condition is updated to True after readiness gates condition is False

### ISSUE THREAD

**Issue by soulseen** [kubernetes/kubernetes#122002]
### What happened?

I have a Deployment with 3 replicas. It have deafined custom readinessGates condition. But sometimes after readinessGates condition gets changed to False, pod ready condition still set to True.
pod Status:
```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-11-22T11:31:51Z"
    status: "False"
    type: custom-readiness-gate
  - lastProbeTime: null
    lastTransitionTime: "2023-11-22T11:31:49Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-11-22T11:31:59Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-11-22T11:31:59Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-11-22T11:31:49Z"
    status: "True"
    type: PodScheduled
```
describe pod:
```yaml
Conditions:
  Type                             Status
  custom-readiness-gate            False
  Initialized                      True
  Ready                            True
  ContainersReady                  True
  PodScheduled                     True
```

### What did you expect to happen?

pod condition type==ready status should be updated to True with all conditions True. If the custom readiness-gates condition is False, the Ready condition can no be True.

### How can we reproduce it (as minimally and precisely as possible)?

create a Deployment with 3 replicas, and update it, sometime will reproduce

### Anything else we need to know?

we should notice that the custom readinessGates condition is set at `2023-11-22T11:31:51Z`, but the Ready condition is set at `2023-11-22T11:31:59Z`, but it still changes to True although custom readinessGates condition is False

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:16Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:48Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
private cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
