### ISSUE TITLE
Describe wrong memory usage.

### ISSUE THREAD

**Issue by lenneker-encora** [kubernetes/kubernetes#122113]
### What happened?

When running the command `kubectl describe node <name of the node>`, the value reported in the memory requested usage is accounting the memory of init containers of some pods, and not the value of the main containers, thus reporting wrong values in the memory request usage.

### What did you expect to happen?

The value of `kubectl describe node <name of the node> `show the value of memory request of main pod containers, not the init container.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy kafka 
Run the command kubectl describe node 

### Anything else we need to know?

Mainly happen when deploying kafka, the wrong value is with kafka and zookeeper when using confluent-init-container:2.6.0 init container

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"17b7accf8fd25125ce015cf4bea7d3cd3f336317", GitTreeState:"clean", BuildDate:"2023-08-28T17:24:07Z", GoVersion:"go1.19.10 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.12+26bab08", GitCommit:"cd33b979be9160c25e490d60aecc9c17920f959f", GitTreeState:"clean", BuildDate:"2023-08-25T22:21:36Z", GoVersion:"go1.19.10 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo

$ uname -a
Linux sbx-app1-5cplr-master-0 4.18.0-372.71.1.el8_6.x86_64 #1 SMP Fri Aug 25 08:34:17 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
cri-o://1.25.4-4.rhaos4.12.gitb9319a2.el8
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Ithrael** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      initContainers:
      - name: my-init-container
        image: busybox:latest
        command: ['sh', '-c', 'echo The app is starting! > /work-dir/start']
        volumeMounts:
        - name: workdir
          mountPath: /work-dir
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
      containers:
      - name: my-app
        image: busybox:latest
        command: ['sh', '-c', 'sleep 600']
        volumeMounts:
        - name: workdir
          mountPath: /work-dir
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: workdir
        emptyDir: {}
```
<img width="682" alt="image" src="https://github.com/kubernetes/kubernetes/assets/38208715/52b79ac4-02ce-4b78-9c6f-04d7d35312b4">

<img width="1430" alt="image" src="https://github.com/kubernetes/kubernetes/assets/38208715/87a19a7b-4eda-417f-a2b7-9f1dbe35348a">
 I can't reproduce using the above kubectl Kubernetes server version, the memory I see is normal. What's your kubectl version
