### ISSUE TITLE
 HostPath type volumes do not support subPath 

### ISSUE THREAD

**Issue by DokiDoki1103** [kubernetes/kubernetes#122156]
### What happened?

 I want to mount the/data/logstash/data directory of the real machine to the data directory of the container, but it cannot be mounted. What is the reason for this 
 
  I manually created several garbage files in the container, and these files were actually persisted, but they were not found in the volumes in my corresponding hostPath 
  
  Now it's:

1: The path in the pod is not bound to the actual machine

2: The data path of pod has been persisted, but it has not been persisted to volumes under the real machine hostPath

### What did you expect to happen?

 I expect the directory of the host to be mapped to the container 

### How can we reproduce it (as minimally and precisely as possible)?

 Create a subdirectory in the data directory of the host and mount it using subpath 

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: itihey-system
  name: logstash
spec:
  serviceName: "logstash"
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:8.9.0
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
            - name: logstash-volume
              mountPath: /data
              subPath: data
      volumes:
        - name: logstash-volume
          hostPath:
            path: /data/logstash
            type: Directory


```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:32:54Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:25:26Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.26) exceeds the supported minor version skew of +/-1
```
v1.26.9
</details>

### Cloud provider

<details>
 Tianyi Cloud 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by DokiDoki1103** [comment]
> /sig storage

 What does it mean

**Comment by Ithrael** [comment]
I pull your image.  
`docker run -it logstash:8.9.0 bash`
Found that there is no /data directory.

<img width="453" alt="image" src="https://github.com/kubernetes/kubernetes/assets/38208715/d69464e8-5b33-4afc-819b-9583f78ca159">
You can change the type to DirectoryOrCreate, which means it will create the directory if it does not exist. This should solve your problem.
```
      volumes:
        - name: logstash-volume
          hostPath:
            path: /data/logstash
            type: DirectoryOrCreate
```



> > /sig storage
> 
> What does it mean

This represents categorizing your issue into storage-related problems
