### ISSUE TITLE
Ability to transform volume files from secret

### ISSUE THREAD

**Issue by jcchavezs** [kubernetes/kubernetes#122103]
Secret's API allows you yo mount a file from a secret. For example:

```yaml
    spec:
        volumeMounts:
          - name: postgres-credentials
            mountPath: /etc/db
            readOnly: true
...

      volumes:
      - name: postgres-credentials
        secret:
          secretName: postgres-credentials
          optional: true
```

However different applications require different configurations means. For example, imagine a user provides all the configuration through a file stored as a secret:

```yaml
# config.yaml
username: abc
password: xyz
```

but the deployment requires the following config file:
```
[my-db]
username=abc
password=xyz
```

We could use a init container to turn the yaml into the postgres service file but what if we use vault or we rotate credentials through other methods and then I need to run the transformation during pod lifecycle and not only on bootstrap?

Given that mounting a secret as a volume would have sync if the secret changes and update the file accordingly I propose a function mechanism to turn a file input into a file output like:

**Local file**

```yaml
    spec:
        volumeMounts:
          - name: postgres-credentials
            mountPath: /etc/db
            mappers:
              - outputPath: .pgservice.conf
                 wasm:
                   url: file:///opt/filters/yamlToDSN.wasm
            readOnly: true
```

**Remote URL**

```yaml
    spec:
        volumeMounts:
          - name: postgres-credentials
            mountPath: /etc/db
            mappers:
              - outputPath: .pgservice.conf
                 wasm:
                   url: https://private-bucket/filters/yamlToDSN.wasm
            readOnly: true
```

**Inline bash**

```yaml
    spec:
        volumeMounts:
          - name: postgres-credentials
            mountPath: /etc/db
            mappers:
            - outputPath: .pgservice.conf
               bash: |
                  #!/bin/bash
                  input=$(cat "./config.yaml")
                  echo "${input//:/=}"
            readOnly: true
```

## Prior Art:

https://github.com/jcchavezs/wasmbox
