### ISSUE TITLE
service-account-token falsely reported as created when there is not service-account

### ISSUE THREAD

**Issue by wiktorkisielewski** [kubernetes/kubernetes#122169]
### What happened?

While creating the secret with `type: kubernetes.io/service-account-token` it is reported as created:

```
$ kubectl  apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  annotations:
    kubernetes.io/service-account.name: my-sa
type: kubernetes.io/service-account-token
EOF

> secret/my-secret created
```

but it is actually not created until there is a corresponding service-account existing:

```
$ kubectl get sa my-sa
Error from server (NotFound): serviceaccounts "my-sa" not found

$ kubectl get secrets --all-namespaces
No resources found
```

> On the recreation (`kubectl apply`) of the secret it is once again reported as `created`

### What did you expect to happen?

The secret should not be reported as created, or there should be a warning that it won't be visible until the `service-account` exists/

On the recreation (running `kubectl apply` again ) of the secret it is once again reported as `created` instead of expected `unchanged`/`updated`

### How can we reproduce it (as minimally and precisely as possible)?

execute:

```
kubectl  apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  annotations:
    kubernetes.io/service-account.name: not-existing-service-account
type: kubernetes.io/service-account-token
EOF
```

and after:
```
secret/my-secret created
```
check if it is visible/exists with `kubectl get secrets`

### Kubernetes version

```console
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.10-eks-4f4795
```

### Cloud provider

AWS
