### ISSUE TITLE
NetworkPolicy block access from alb causing 504 gateway timeout

### ISSUE THREAD

**Issue by kkarczewski** [kubernetes/kubernetes#122151]
### What happened?

I want to use networkpolicy to restrict traffic between pods. In my case I have argocd deployed to AWS EKS cluster with alb on top of aws load balancer contoller. Argocd is in argocd namespace. AWS Load Balancer controller in kube-system namespace. Setup works nicely without network policies. When Network Policy is deployed to argocd namespace it blocks also traffic from alb and I can't access domain. I get error 504 Gateway Time-out. Added entries in network policies for traffic both ways from and to argocd and kube-system namespace. 

### What did you expect to happen?

I'd expect adding entry for alb controller namespace will allow traffic from alb.

### How can we reproduce it (as minimally and precisely as possible)?

EKS deployed from aws blueprints. 
Argocd and aws-load-balancer-cotroller deployed from latest helm charts.
Network policy as below:
```
            apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: argocd-allow-ingress-egress
              namespace: argocd
            spec:
              podSelector: {}
              policyTypes:
              - Ingress
              - Egress
              ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: argocd
              - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
              egress:
              - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: argocd
              - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
```

### Anything else we need to know?

Network policies via aws vpc cni addon.
aws-load-balancer-controller with hostNetwork set to false.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3-eks-4f4795d
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

```
vpc-cni    = {
    addon_version = "v1.15.4-eksbuild.1"
    configuration_values = {
      "enableNetworkPolicy" : "true",
      "nodeAgent" : {
        "enableCloudWatchLogs" : "true"
      }
    }
  }
```

aws-load-balancer-controller version: 1.6.2

**Comment by astoycos** [comment]
@kkarczewski  So this issue is most likely specific to the aws vpc cni addon since that's the process actually implementing the dataplane rules.  However, if the ALB pods are hostnetworked that could be the issue.  Regardless reaching out to the aws VPC cni addon development community it most likely the best course of action  

Additionally you can simplify your policy like so:

```yaml
            apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: argocd-allow-ingress-egress
              namespace: argocd
            spec:
              podSelector: {}
              policyTypes:
              - Ingress
              - Egress
              ingress:
              - from:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: argocd
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
              egress:
              - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: argocd
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
```
Although that shouldn't effect the functionality
