### ISSUE TITLE
Pod Container.Command doesn't respect ulimit set in `etc/bash/bash.rc`

### ISSUE THREAD

**Issue by Souheil-Yazji** [kubernetes/kubernetes#122280]
### What happened?

There's a good chance I'm misunderstanding how the command runs against the container, but from what I understand, this is doing `exec -- bin/bash -c <command>` and so I'd expect the ulimit to apply there as well but it doesn't. 

With the following dockerfile:

<details>
<summary> Dockerfile </summary>

```
FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN echo "ulimit -S -s 65536" >> etc/bash.bashrc && \

SHELL ["/bin/bash", "-c"]
```

</details>

Using the following manifest:

<details>
<summary>testpod.yaml</summary>

```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: test/latest
    name: test
    command: ["/bin/bash", "-c", "ulimit -s"]
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 250Mi
```

</details>

The pod logs show `8192` which is the default value and not the one set in the dockerfile.

### What did you expect to happen?

According to my [research](https://askubuntu.com/questions/815066/whats-the-difference-between-bashrc-and-etc-bash-bashrc), `RUN echo "ulimit -S -s 65536" >> etc/bash.bashrc && \`  should allow all bash instances to have their ulimit set regardless of which user starts the instance. 

### How can we reproduce it (as minimally and precisely as possible)?

Build the dockerfile and deploy the pod on a cluster.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.26.10
Kustomize Version: v4.5.7
Server Version: v1.26.6
```

</details>

### Cloud provider

<details>
AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux test 5.15.0-1051-azure #59-Ubuntu SMP Wed Oct 11 18:49:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>
