### ISSUE TITLE
topologySpreadConstraints not working as expected if the topologyKey is not set in the nodes

### ISSUE THREAD

**Issue by mtenrero** [kubernetes/kubernetes#122278]
### What happened?

When setting topologySpreadContraints with ScheduleAyway whenUnsatisfiable param set the scheduling is not working as it expected if multiple constraints are set at the same time
Instead of splitting workload among all available workers , all workloads goes to the same node or they are note evenly distributed.

No other affinities nor nodeSelector are set

### What did you expect to happen?

All the replicas should be evenly distributed among all available workers

### How can we reproduce it (as minimally and precisely as possible)?

Create any deployment with the following topologySpreadConstraints:

```yaml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: foo
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: foo
```

Check created pods are not evenly distributed

### Anything else we need to know?

**It seems if we remove the zone constraint, the scheduler works fine again**

Important note: it only fails if the nodes doesn't have the label which is configured in the constraint present

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:21:34Z", GoVersion:"go1.20.8", Compiler:"gc", Platfor
m:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:14:09Z", GoVersion:"go1.20.8", Compiler:"gc", Platfor
m:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Bare Metal 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:21:34Z", GoVersion:"go1.20.8", Compiler:"gc", Platfor
m:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:14:09Z", GoVersion:"go1.20.8", Compiler:"gc", Platfor
m:"linux/amd64"}

$ uname -a

Linux k8s-master01 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chengjoey** [comment]
if you not set `topology.kubernetes.io/zone` in nodes, maybe you should make `nodeAffinityPolicy: Ignore`, i am no sure
```
- maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: foo
         nodeAffinityPolicy: Ignore
```
