### ISSUE TITLE
Ephemeral storage limits do not account for data written to /dev/termination-log, pods are not evicted

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/kubernetes#122224]
### What happened?

A pod with an ephemeral storage limit is never evicted due to excessive data written to `/dev/termination-log`.

### What did you expect to happen?

Data written to `/dev/termination-log` should count against a pod's ephemeral storage limit and result in eviction once too much data is written.

### How can we reproduce it (as minimally and precisely as possible)?

The following pod demonstrates the problem:

```
---                                                                                                                                                     
apiVersion: v1                                                                                                                                          
kind: Pod                                                                                                                                               
metadata:                                                                                                                                               
  name: dev-termination-log-test                                                                                                                        
spec:                                                                                                                                                   
  containers:                                                                                                                                           
  - image: k8s.gcr.io/busybox:latest                                                                                                                    
    name: test                                                                                                                                          
    command: ["/bin/sh"]                                                                                                                                
    # create 200MiB of data and write it to /dev/termination-log, then sleep forever                                                                    
    args:                                                                                                                                               
    - -c                                                                                                                                                
    - |-                                                                                                                                                
      yes $(printf 'Hello world!!!!\n%.0s' `seq 1 $((1024/16))`) | dd bs=1024 count=$((200*1024)) | tee /dev/termination-log                            
      while sleep 3600; do                                                                                                                              
        true                                                                                                                                            
      done                                                                                                                                              
    resources:                                                                                                                                          
      limits:                                                                                                                                           
        ephemeral-storage: "100Mi"                                                                                                                      
  securityContext:                                                                                                                                      
    runAsUser: 0                                                                                                                                        
```

### Anything else we need to know?

This issue was originally reported as part of the Kubernetes HackerOne bug bounty program. The current security posture of the Kubernetes Security Response Committee is to treat issues like this as security hardening bugs, and not as a CVE. Thanks to Chijin Zhou (chijin on HackerOne) for reporting this issue.

### Kubernetes version

<details>

```console
Server Version: version.Info{Major:"1", Minor:"29+", GitVersion:"v1.29.0-alpha.0.372+714e77595c8b19-dirty", GitCommit:"714e77595c8b19b693925bda2a96ab80c307d38f", GitTreeState:"dirty", BuildDate:"2023-12-07T17:32:58Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Tested on a local-up cluster

</details>

### OS version

<details>

Tested on Fedora 37

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
