### ISSUE TITLE
ExternalIP is always in Pending state

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/kubernetes#122212]
I am trying to run the Service on minikube 
Whose yaml file is.

```
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  ports:
    - port: 8000
  selector:
    app: demo-service
    tier: app
  type: LoadBalancer
```

The Service get created well , The pods and deployment are running well but when i run command 
`kubectl get svc`  Here i found that the external IP is in `<pending> ` state from long time.
Thats the reason why 
`minikube service demo-service` is not rendering to the correct page.

Note I had configured the minikube VM before starting the minikube for work.

**What do You want**
 External Ip should have allocated the ip value   

How to resolve the issue . There is no any error while describing the service django.

**What may be the Probable reason the External IP is in pending state and what we should do to resolve this issue.?**
