### ISSUE TITLE
CEL in Admission(ValidatingAdmissionPolicy): explicitly excluding resources from validatingadmissionpolicy interception

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#122205]
### What would you like to be added?
Currently, the vap only prevent itself and the binding from being intercepted: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/validatingadmissionpolicy/admission.go#L189-L197
We would love to revisit this before going to GA to make sure if we wanna explicitly prevent any other resources as well.

Thanks for the suggestion from @liggitt : "propose excluding tokenreviews / subjectaccessreviews from validatingadmissionpolicy interception"

### Why is this needed?

It's too easy to brick delegated authn / authz in a cluster if user-configurable policy can break subjectaccessreview / tokenreview specifically.

**Comment by cici37** [comment]
This is discussed in today's sig apimachinery CEL meeting: https://docs.google.com/document/d/1Z7p5183OsJ1enJA4-WTk98g7agwSILqKUYxwVHZHilE/edit?tab=t.0#bookmark=id.3n5wj74otles
I'll bring this to both sig apimachinery and sig auth meeting.

**Comment by cici37** [comment]
Notes from sig-auth meeting:
```
- Admission should not be able to break read requests (i.e. token review)
- Probably should not handle virtual resources since they are not persisted
- Add integration test that makes sure that virtual resources cannot be intercepted
```

**Comment by cici37** [comment]
Thanks! Although that will give webhook more power than in-process validation which sounds a little weird but I guess it could be addressed in a separate KEP since webhook is GAed for long time -_-

**Comment by enj** [comment]
@kubernetes/sig-auth-leads I did not realize it at the time of the SIG Auth meeting, but we plan on using `ValidatingAdmissionPolicy` to intercept the virtual token request resource (`serviceaccounts/token`) in https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/1364 for limiting the secret sync controller to a specific audience:

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "secret-sync-controller-validate-token-policy"
spec:
  failurePolicy: Fail
  matchConditions:
    - name: 'userIsController'
      expression: "request.userInfo.username == 'system:serviceaccount:foo-bs:bar-sa'"
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE"]
      resources:   ["serviceaccounts/token"]
  variables:
  - name: hasCorrectAudience
    expression: "object.spec.audiences.size() == 1 && object.spec.audiences.exists(w, w == 'expected-audience'))"
  validations:
  - expression: "variables.hasCorrectAudience == true"
```

A blanket restriction on not allow virtual resources to be intercepted would break that.
