### ISSUE TITLE
Already API-evicted Pods do not get evicted by the kubelet eviction manager (memory pressure, ephemeral storage pressure)

### ISSUE THREAD

**Issue by FullyScaled** [kubernetes/kubernetes#122297]
### What happened?

When pods have a long _terminationGracePeriod_ and get evicted by downscaling or some other reason (via API) the eviction is initiated which respects that long _terminationGracePeriod_. This works fine.

If the pods need to be evicted due to memory pressure on the node after the already initiated API eviction there is no more eviction done with the specified _evictionMaxPodGracePeriod_ of the kubelet. This means that the second eviction due to e.g. memory pressure cannot be successful at all when you have large _terminationGracePeriod_ on your pod and there was a prior unrelated API eviction.

![image](https://github.com/kubernetes/kubernetes/assets/28532557/9d83248f-7dfe-49b0-88b0-7b7e9f73faf6)

### What did you expect to happen?

The eviction manager triggered eviction due to memory pressure should still be issued with the specified _evictionMaxPodGracePeriod_ even if there was a prior API based eviction with a large terminationGracePeriod.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a workload pod that does ignore sig-terms
- Specify a large _terminationGracePeriod_ for that pod, do not set any memory limits for the pod
- Specify a small _evictionMaxPodGracePeriod_ for the kubelet on the node
- API evict the Pod
- Make sure the kubelet wants to evict the pod (e.g. by allocating memory inside pod until the node is under memory pressure)

### Anything else we need to know?

The bug was not present in k8s 1.25.x

### Kubernetes version

<details>

1.26.7

</details>

### Cloud provider

<details>
Azure

</details>

### OS version

<details>

GardenLinux 934.10.0

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd/1.6.20
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig node
for triage

**Comment by kannon92** [comment]
Do you have a `pod.yaml` that can reproduce this?

**Comment by FullyScaled** [comment]
Yes, I was able to reproduce this with this minimal example. I had 16GB Nodes (RAM) inside the cluster. If your nodes are smaller or larger you have to adjust the memory allocation in order to trigger the memory pressure eviction.


- Kubelet settings:
```
kubelet:
            evictionMaxPodGracePeriod: 20
            evictionSoft:
              memoryAvailable: 25%
            evictionSoftGracePeriod:
              memoryAvailable: 1m0s
```

```
apiVersion: v1
kind: Pod
metadata:
  name: eviction-pod
spec:
  containers:
    - name: worker
      image: eu.gcr.io/gardener-project/gardener/ops-toolbelt:latest
      command:
        - bash 
        - -c
        - while true; do echo $(date); sleep 5d; done
      resources:
        requests:
          memory: "2Gi"
          cpu: "0.5"
  terminationGracePeriodSeconds: 3600
```



### Steps to reproduce
1. Create pod
2. API-Evict pod (e.g. via `kubectl delete eviction-pod -n default`)
3. `kubectl exec -it eviction-pod -n default -- bash`
4. `cat <(head -c 10000m /dev/zero) <(sleep 10000) | tail`

Result: Pod will not get killed by the kubelet eviction manager. If you do the exact same without API evicting the pod in the second step, the kubelet eviction will work.
