### ISSUE TITLE
can't remove NodePorts from LoadBalancer type Service with AllocateLoadBalancerNodePorts=false 

### ISSUE THREAD

**Issue by armstrongli** [kubernetes/kubernetes#122381]
### What happened?

A LB type service has `AllocateLoadBalancerNodePorts=false`. the nodePorts can't be deleted by removing the nodePort, neither set the NodePort to be 0.

### What did you expect to happen?

after removing the NodePort, the value should be gone from Service spec definition.

### How can we reproduce it (as minimally and precisely as possible)?

```
:kind-capi-2:default:~# k get svc rest-1 -o yaml | yq .spec
allocateLoadBalancerNodePorts: false
clusterIP: 10.109.145.199
clusterIPs:
  - 10.109.145.199
externalTrafficPolicy: Cluster
internalTrafficPolicy: Cluster
ipFamilies:
  - IPv4
ipFamilyPolicy: SingleStack
ports:
  - name: http
    nodePort: 32428
    port: 8080
    protocol: TCP
    targetPort: 8080
selector:
  app: rest
sessionAffinity: None
type: LoadBalancer
:kind-capi-2:default:~# k patch svc rest-1 -p '{"spec":{"$setElementOrder/ports":[{"port":8080}],"ports":[{"nodePort":null,"port":8080}]}}'
service/rest-1 patched (no change)
:kind-capi-2:default:~# k get svc rest-1 -o yaml | yq .spec
allocateLoadBalancerNodePorts: false
clusterIP: 10.109.145.199
clusterIPs:
  - 10.109.145.199
externalTrafficPolicy: Cluster
internalTrafficPolicy: Cluster
ipFamilies:
  - IPv4
ipFamilyPolicy: SingleStack
ports:
  - name: http
    nodePort: 32428
    port: 8080
    protocol: TCP
    targetPort: 8080
selector:
  app: rest
sessionAffinity: None
type: LoadBalancer
...
:kind-capi-2:default:~# k patch svc rest-1 -p '{"spec":{"$setElementOrder/ports":[{"port":8080}],"ports":[{"nodePort":0,"port":8080}]}}'
service/rest-1 patched (no change)
```

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.0", GitCommit:"855e7c48de7388eb330da0f8d9d2394ee818fb8d", GitTreeState:"clean", BuildDate:"2023-08-15T21:24:51Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
