### ISSUE TITLE
[BUG] Windows node reports less CPU usage than its pods when kubernetes version >= 1.27

### ISSUE THREAD

**Issue by junjiezhang1997** [kubernetes/kubernetes#122382]
### What happened?

In AKS clusters (k8s version >= 1.27), `kubectl top node` is showing less cpu load for windows nodes than expected.

### What did you expect to happen?

It should show the summary of cpu load in all windows pods.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an AKS cluster with k8s version 1.27.3
2. Create a windows nodepool with 1 Windows2022/2019 node
3. Create simple cpu-consuming deployment.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-cpu-load
  name: win-cpu-load
spec:
  replicas: 3
  selector:
    matchLabels:
      app: win-cpu-load
  template:
    metadata:
      labels:
        app: win-cpu-load
      name: win-cpu-load
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.azure.com/agentpool
                      operator: In
                      values:
                        - win19
      containers:
      - name: windowswebserver
        image: mcr.microsoft.com/windows/servercore:ltsc2019
        command:
        - powershell.exe
        - -command
        - "while ($true) { $result = 1; foreach ($number in 1..100000000) {$result = $result * $number}; Write-Host $result; Start-Sleep -Seconds 7; }"
```
4. Wait until metrics are collected (~1 minute)
5. Execute command `kubectl top pod` and `kubectl top node`
<img width="558" alt="image" src="https://github.com/kubernetes/kubernetes/assets/109257558/0a7f332f-ceae-4dc3-8f54-7c6b8c6df25b">
<img width="568" alt="image" src="https://github.com/kubernetes/kubernetes/assets/109257558/53a99213-72f8-464c-994e-5848623e9bd9">

7. Pods have in total more cpu usage than node (It seems that the CPU metric is a factor 10 off).

### Anything else we need to know?

1. This issue was reported in https://github.com/Azure/AKS/issues/4028 and I reproduce it successfully in 1.27.3, 1.27.7 and 1.28.0.
It doesn't occur when k8s version is 1.26.10.
2. This issue occurs both in Windows2019 and Windows2022 node.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

</details>

### Cloud provider

<details>
AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
# paste output here
Linux DESKTOP-6RR60DH 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
