### ISSUE TITLE
Align-by-socket doesn't work in the CPU Manager

### ISSUE THREAD

**Issue by changzhi1990** [kubernetes/kubernetes#122473]
### What happened?

Hi, all. The option `align-by-socket` doesn't work in my env. Here are the steps:
1. Change the kubelet config (/var/lib/kubelet/config.yaml) and add the following configs:
```
cpuManagerPolicy: static
systemReserved:
  cpu: 500m
  memory: 256M
kubeReserved:
  cpu: 500m
```
2. Add the `align-by-socket` option in the `/var/lib/kubelet/kubeadm-flags.env`:
```
KUBELET_KUBEADM_ARGS="--feature-gates=CPUManagerPolicyAlphaOptions=true --container-runtime-endpoint=unix:///run/containerd/containerd.sock --pod-infra-container-image=registry.k8s.io/pause:3.9 --cpu-manager-policy-options=align-by-socket=true"
```
3. Restart the kubelet and create pods.

### What did you expect to happen?

The cpuset of these pods should align by socket.

### How can we reproduce it (as minimally and precisely as possible)?

Create a nginx yaml and scale it to 6:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 20
            memory: 1Gi
          requests:
            cpu: 20
            memory: 1Gi
```
Scale it and get the result:
```
sdp@b49691d6a544:~$ kubectl scale deployment/nginx-deployment --replicas=6
deployment.apps/nginx-deployment scaled
sdp@b49691d6a544:~$ for a in `kubectl get pods|awk -F ' ' '{print $1}'`; do kubectl exec $a -- cat /proc/1/status |grep Cpus_allowed_list; done
Error from server (NotFound): pods "NAME" not found
Cpus_allowed_list:      1-10,113-122
Cpus_allowed_list:      11-20,123-132
Cpus_allowed_list:      31-40,143-152
Cpus_allowed_list:      21-30,133-142
Cpus_allowed_list:      41-50,153-162
Cpus_allowed_list:      51-60,163-172
```

In my env, there are 2 sockets and 4 NUMA nodes. The Socket0 contains NUMA0 and NUMA1, the Socket1 contains NUMA2 and NUMA3:
```
sdp@b49691d6a544:~$ lscpu|grep NUMA |grep -v "node(s)"
NUMA node0 CPU(s):                  0-27,112-139
NUMA node1 CPU(s):                  28-55,140-167
NUMA node2 CPU(s):                  56-83,168-195
NUMA node3 CPU(s):                  84-111,196-223
```

Based on my understanding of the `align-by-socket` (https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/). The cpuset of each pod shouldn't across the socket. In my example, the cpuset of last Nginx pod is **Cpus_allowed_list:      51-60,163-172**. This shouldn't happen.

### Kubernetes version

<details>

```console
$ kubectl version
sdp@b49691d6a544:~/zhi/PerfSpect/similarity-analyzer$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

</details>

### Cloud provider

<details>
Intel
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

$ uname -a
5.15.0-91-generic

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
