### ISSUE TITLE
DaemonSet UpdatedNumberScheduled Status Not Right with RollingUpdate

### ISSUE THREAD

**Issue by shihaohems** [kubernetes/kubernetes#122527]
### What happened?

DaemonSet with "RollingUpdate" update strategy does not count scheduled updated Pods in "UpdatedNumberScheduled" status until old Pod on the same Node is terminated.

### What did you expect to happen?

With rolling update, "UpdatedNumberScheduled" should count updated Pods once it is scheduled, instead of being blocked by old Pod on the same Node.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a DaemonSet with a container that sleeps some time on SIGTERM.
- Update the DaemonSet spec to trigger the rolling update.
- Check "UpdatedNumberScheduled" status of this DaemonSet.

### Anything else we need to know?

The root cause should be [status update](https://github.com/kubernetes/kubernetes/blob/63eb5028ba613003f044f0391912be356e0f1b97/pkg/controller/daemon/daemon_controller.go#L1152C3-L1152C3) only checks the oldest pod on each Node, which should not be the case with rolling update?

### Kubernetes version

1.28.2

### Cloud provider

Docker Desktop

**Comment by Ithrael** [comment]
I think this seems to be normal logic.

This is the process I reproduced, I used minikube k8s server 1.27.4 with 3 nodes.

daemonset.yaml
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "trap 'sleep 30' TERM; while true; do sleep 1; done"]
```
`kubectl rollout restart ds my-daemonset `


The observed situation is: 
Pods on the node are first deleted and then created. 
When the pod is in the 'terminating' state, 'UpdatedNumberScheduled' does not change. It only increases when the pod is in the 'creating' state.

Look the doc，https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/
<img width="698" alt="image" src="https://github.com/kubernetes/kubernetes/assets/38208715/d49b2fa3-98a8-4701-8c87-4a334a6a3374">

I believe this description is consistent with the actual logic being carried out

**Comment by shihaohems** [comment]
Hi @Ithrael, thanks for the reply.
I missed "RollingUpdate as the updateStrategy" in the reproduce steps, sorry for that (editted it in).

Try the following and see the issue.
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "trap 'sleep 30' TERM; while true; do sleep 1; done"]
  updateStrategy:
    type: RollingUpdate                                                                                                                                                                                                 
    rollingUpdate:                                                                                                                                                                                               
      maxSurge: 1                                                                                                                                                                                        
      maxUnavailable: 0                                                                                                                                                                                   
```
