### ISSUE TITLE
Deployment is not tracking changes

### ISSUE THREAD

**Issue by heflain-mendes** [kubernetes/kubernetes#122531]
### What happened?

When executing a command that causes changes to the deployment, a new state is not created, what happens is that the previous state is envelope.

I'm reporting it as a bug, because in tutorials I've been following this is not the default behavior.

### What did you expect to happen?

I expected the second output of the history command to look like this:
```console
REVISION  CHANGE-CAUSE
1         <none>
2         <none>
```

### My Deployment code 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
```
### Running apply command:
`kubectl apply -f .\deployment.yaml`

###  History command output:
```console
REVISION  CHANGE-CAUSE
1         <none>
```

### Editando quantidade de replicas para 5
The change in the number of replicas was made with the set, edit commands and by changing the file and executing the apply command
###  History command output:
```console
REVISION  CHANGE-CAUSE
1         <none>
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                   OSArchitecture  Version
22631        Microsoft Windows 11 Pro  64 bits         10.0.22631
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
