### ISSUE TITLE
`--proxy-mode=nftables` fails if non-canonical (but standardized) IPv6 addresses are used

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#122611]
### What happened?

When a non-canonical IPv6 address, e.g. `fd00::10.0.0.34`, is used as a loadBalancerIP, communication fails.

/sig network
/area kube-proxy

### What did you expect to happen?

Addresses like `fd00::10.0.0.34` should work, as they do for proxy-mode ipvs and iptables

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a dual-stack service with type loadBalancer
2. Assign a non-canonical ipv6 loadBalancerIP
3. Try to access the service with the non-canonical ipv6 address

I will add a manifest for test, and more instructions later.

### Anything else we need to know?

What "canonical" really is can be debated. The [rfc5952](https://datatracker.ietf.org/doc/html/rfc5952) seems to accept "embedded ipv4", as long as the prefix follows the rules. So, as I understand it, `fd00::10.0.0.34` *is* a canonical IPv6 address.

@danwinship If you don't mind I would like to take a shot at this myself to get acquainted with the code

### Kubernetes version

v1.29.0

### Cloud provider

None

### OS version

Linux

### Install tools

None

### Container runtime (CRI) and version (if applicable)

N/A (cri-o)

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A (but tested with calico and flannel)

**Comment by uablrek** [comment]
Use the manifest below, and the [assign-lb-ip](https://github.com/Nordix/assign-lb-ip) tool:
```
kubectl create namespace alpine-nc
kubectl create -n alpine-nc -f alpine-nc.yaml
assign-lb-ip -n alpine-nc -svc alpine-nc -ip 203.0.113.1,2001:db8::203.0.113.1
echo | nc 203.0.113.1 7007
echo | nc 2001:db8::203.0.113.1 7007
```
The loadBalancerIPs are taken from the documentation ranges, specified in [rfc5737](https://datatracker.ietf.org/doc/html/rfc5737) and [rfc3849](https://datatracker.ietf.org/doc/html/rfc3849).

<details><summary>alpine-nc.yaml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-nc
spec:
  selector:
    matchLabels:
      app: alpine-nc
  replicas: 4
  template:
    metadata:
      labels:
        app: alpine-nc
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["nc", "-lk", "-p", "7007", "-e", "hostname"]
        ports:
        - name: nc
          containerPort: 7007
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-nc
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: alpine-nc
  type: LoadBalancer
  ports:
  - port: 7007
    name: nc
```

</details>
