### ISSUE TITLE
too many `ContainerStatusUnknown` pod 

### ISSUE THREAD

**Issue by yylt** [kubernetes/kubernetes#122779]
### What happened?

```
openstack            grafana-69b4cc7666-2tp5p                            0/1     Init:ContainerStatusUnknown   0          59d
openstack            grafana-69b4cc7666-2w25h                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-2x7r6                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-46895                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-4hs54                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-4vt9k                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-5b9l8                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-5ccd6                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-5nf7v                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-66hvm                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-6bcsq                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-799w9                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-7bn64                            0/1     Init:ContainerStatusUnknown   0          60d
openstack            grafana-69b4cc7666-7sbmv                            0/1     Init:ContainerStatusUnknown   0          60d
...
```

Upon reviewing the log, it appears that this issue arises when the `node.kubernetes.io/memory-pressure` condition transitions from True to False. Even if the current pressure is significant, but it will not immediately changing back to memory-pressure=True. As the documentation https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#node-condition-oscillation, the default transition period is 5 minutes(eviction-pressure-transition-period default). It seems that this is leading to the accumulation of Pods in the ContainerStatusUnknown state 

In practical terms,  it appears that while `node.kubernetes.io/memory-pressure` condition transition from True to False should wait for a certain period, such as 5 minutes, but `node.kubernetes.io/memory-pressure` condition transition from False to True should not involve a waiting period and should occur immediately. this is will resolved the generation of many invalid Pods.

### What did you expect to happen?

some pod are in `ContainerStatusUnknown` state, but not a large numbers.

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stressng-memory
spec:
  replicas: 8
  selector:
    matchLabels:
      app: stress-ng
  template:
    metadata:
      labels:
        app: stress-ng
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-1
      containers:
      - name: stress
        image: alexeiled/stress-ng:0.11.19-ubuntu
        command:
          - /bin/bash
          - -c
          - |
            stress-ng --vm 1 --vm-bytes 1G --timeout 120s &
            wait
            echo "start to sleep"
            sleep 1d
        resources:
          requests:
            memory: "128Mi"
            cpu: "20m"
```

make sure the node `node-8` has memory-pressre, and than wait 10 seconds create again.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

</details>

### Cloud provider

<details>

none 

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
