### ISSUE TITLE
Accessing NodePort on K8S host has latency when reaching Pods across different hosts

### ISSUE THREAD

**Issue by wuyanfeiwork** [kubernetes/kubernetes#122835]
### What happened?

I have deployed a Kubernetes cluster on Debian 12.4 operating system. I am using a test image, exposing a port to obtain the container's name. I use this method to determine which Pod the request is assigned to.

As shown in the screenshot below, accessing the Pod on the local machine works fine. However, if the request is assigned to a Pod on another host, there is a 1-second delay before receiving a response. Upon inspecting the packets using tcpdump, I observed that the first request resulted in a connection reset, and I am not quite sure about the cause of this issue.

![image](https://github.com/kubernetes/kubernetes/assets/104751498/d2fb1b0e-d2ea-4627-b691-9d6bfbc1398f)

![image](https://github.com/kubernetes/kubernetes/assets/104751498/84aa407e-4387-47fe-94f1-384950f0909a)

### What did you expect to happen?

Deployed Kubernetes environment is functioning properly on CentOS 7.9 operating system.

![image](https://github.com/kubernetes/kubernetes/assets/104751498/7f9ed3e6-c0be-4458-b6fd-b6c05afa6842)

### How can we reproduce it (as minimally and precisely as possible)?

I can reproduce it on Debian 12, Debian 11, and Ubuntu 22.04.

Here is my YAML file.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: centos:7.9.2009
        command:
        - sh
        - -c
        - |
          echo $(hostname) > hostname.txt
          python -m SimpleHTTPServer
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 64Mi
            cpu: 0.01
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Etc/GMT-8

---

apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  selector:
    app: test
  ports:
  - name: external-test
    port: 8000
    targetPort: 8000
    nodePort: 8000
  type: NodePort

```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

```
</details>

### Cloud provider

<details>
Aliyun
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux debian-1 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd -v
containerd containerd.io 1.6.27 a1496014c916f9e62104b33d1bb5bd03b0858e59

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
mirrored-flannelcni-flannel:v0.20.1
</details>
