### ISSUE TITLE
missing events for some of pod containers

### ISSUE THREAD

**Issue by rangoo94** [kubernetes/kubernetes#122904]
### What happened?

After running the Pod with 9+ containers (1 regular container + minimum of 8 init containers) there are Events available only for 8 containers, anything above is not registered in the Pod's events.

### What did you expect to happen?

I would expect to have `Pulled`/`Created`/`Started` events for all the containers of the Pod.

### How can we reproduce it (as minimally and precisely as possible)?

Create a job with 9 init containers and 1 further container:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  suspend: false
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - image: busybox:1.36.1
        name: example-1
      - image: busybox:1.36.1
        name: example-2
      - image: busybox:1.36.1
        name: example-3
      - image: busybox:1.36.1
        name: example-4
      - image: busybox:1.36.1
        name: example-5
      - image: busybox:1.36.1
        name: example-6
      - image: busybox:1.36.1
        name: example-7
      - image: busybox:1.36.1
        name: example-8
      - image: busybox:1.36.1
        name: example-9
      containers:
      - image: busybox:1.36.1
        name: example-10
```

and later:

```console
$ kubectl get events | grep pod/example
```

It won't display events for `example-9` and `example-10` containers:
* on K3S and Minikube the last event is `Pulled` from `example-9`
* on GKE the last event is `Started` from `example-8`
<details>
  <summary>Example events log</summary>

```console
$ kubectl get events | grep pod/example
55s         Normal    Scheduled            pod/example-k4jfw                                    Successfully assigned testkube/example-k4jfw to homelab
55s         Normal    Pulled               pod/example-k4jfw                                    Container image "busybox:1.36.1" already present on machine
55s         Normal    Created              pod/example-k4jfw                                    Created container example-1
55s         Normal    Started              pod/example-k4jfw                                    Started container example-1
54s         Normal    Pulled               pod/example-k4jfw                                    Container image "busybox:1.36.1" already present on machine
54s         Normal    Created              pod/example-k4jfw                                    Created container example-2
54s         Normal    Started              pod/example-k4jfw                                    Started container example-2
53s         Normal    Pulled               pod/example-k4jfw                                    Container image "busybox:1.36.1" already present on machine
53s         Normal    Created              pod/example-k4jfw                                    Created container example-3
53s         Normal    Started              pod/example-k4jfw                                    Started container example-3
52s         Normal    Pulled               pod/example-k4jfw                                    Container image "busybox:1.36.1" already present on machine
52s         Normal    Created              pod/example-k4jfw                                    Created container example-4
52s         Normal    Started              pod/example-k4jfw                                    Started container example-4
51s         Normal    Pulled               pod/example-k4jfw                                    Container image "busybox:1.36.1" already present on machine
51s         Normal    Created              pod/example-k4jfw                                    Created container example-5
51s         Normal    Started              pod/example-k4jfw                                    Started container example-5
50s         Normal    Pulled               pod/example-k4jfw                                    Container image "busybox:1.36.1" already present on machine
50s         Normal    Created              pod/example-k4jfw                                    Created container example-6
50s         Normal    Started              pod/example-k4jfw                                    Started container example-6
49s         Normal    Pulled               pod/example-k4jfw                                    Container image "busybox:1.36.1" already present on machine
49s         Normal    Created              pod/example-k4jfw                                    Created container example-7
49s         Normal    Started              pod/example-k4jfw                                    Started container example-7
48s         Normal    Pulled               pod/example-k4jfw                                    Container image "busybox:1.36.1" already present on machine
48s         Normal    Created              pod/example-k4jfw                                    Created container example-8
48s         Normal    Started              pod/example-k4jfw                                    Started container example-8
47s         Normal    Pulled               pod/example-k4jfw                                    Container image "busybox:1.36.1" already present on machine
```
</details>

### Kubernetes version

<details>

```console
# K3S
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5+k3s1

# GKE
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.10-gke.2700
```
</details>

### Cloud provider

<details>
Tested on GKE, K3S and Minikube
</details>

### OS version

<details>

```console
# K3S
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=lunar
LOGO=ubuntu-logo
$ uname -a
Linux homelab 6.2.0-20-generic #20-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
