### ISSUE TITLE
sidecar container readniess result to be used in Pod ready state also for pod.spec.restartPolicy = Never or OnFailure

### ISSUE THREAD

**Issue by CindyLizi** [kubernetes/kubernetes#122902]
### What happened?

I created a pod with sidecar container with following manifest:
```
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    app: webapp
spec:
  tolerations:
  - key: "key1"
    operator: "Exists"
    effect: "NoSchedule"
  initContainers:
    - name: init-service
      image:  busybox
      command:
        - sleep
        - 5s
    - name: sidecar
      image:  busybox
      command:
        - sleep
        - 30s
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
      readinessProbe:
        exec:
          command:
          - cat
        initialDelaySeconds: 5
        periodSeconds: 5
      imagePullPolicy: IfNotPresent
      restartPolicy: Always
  containers:
  - name: main-application
    image: nginx
    volumeMounts:
      - name: shared-logs
        mountPath: /var/log/nginx
    resources:
      requests:
        memory: "100Mi"
        cpu: "0.5"
  volumes:
    - name: shared-logs
      emptyDir: {}
  restartPolicy: Never

```

watch the pod readiness. 
```
#before the sidecar container be restarted , the readiness is 2/2
watch kubectl  get pod
Every 2.0s: kubectl get pod                                                     

NAME                    READY   STATUS    RESTARTS   AGE
simple-webapp           2/2     Running   0          36s

#after the sidecar container be restarted, the pod readiness is 1/2, sidecar readiness result is not be used to the pod. 
NAME                    READY   STATUS    RESTARTS   AGE
simple-webapp           1/2     Running   2          2m15s

```
in [Sidecar containers and Pod lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#sidecar-containers-and-pod-lifecycle), it's mentioned "If a readinessProbe is specified for this init container, its result will be used to determine the ready state of the Pod."

it's true only for pod.spec.restartPolicy = Always, sidecar container readniess result will be used in Pod ready state, neither "Never" or "OnFailure".

I tested with v1.29.0

### What did you expect to happen?

I expect "If a readinessProbe is specified for this init container, its result will be used to determine the ready state of the Pod." also applicable to  pod.spec.restartPolicy = "Never" or "OnFailure".

### How can we reproduce it (as minimally and precisely as possible)?

Set pod.spec.restartPolicy = "Never" or "OnFailure".

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux node-10-210-171-200 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
 containerd --version
containerd github.com/containerd/containerd v1.7.11 64b8a811b07ba6288238eefc14d898ee0b5b99ba

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
