### ISSUE TITLE
configure topologySpreadConstraints in order to ignore zones which have no health nodes?

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/kubernetes#123019]
**How can we configure topologySpreadConstraints in order to ignore zones which have no health nodes?**

**Details**
We prepared nodes (kubernetes.io/hostname) and zones (topology.kubernetes.io/zone) as follows.
```
Zone: E01
node1
node2
node3

Zone: E02
node4

Zone: E03
node5
```
Then we deployed the following deployment.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
  labels:
    app: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: dummy
        image: nginx
        command: ["/bin/sh", "-c", "sleep infinity"]
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: test
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - test
              topologyKey: kubernetes.io/hostname
```
4 Pods were spreaded as follows.

```
# Zone: E01
node1   Pod
node2
node3   Pod

# Zone: E02
node4   Pod

# Zone: E03
node5   Pod

$ kubectl get pod -o wide
NAME                     READY   STATUS    RESTARTS   AGE   IP             NODE    READINESS GATES
dummy-XXXXXXXXXX-dmhvr   1/1     Running   0          8s    10.130.2.20    node1   <none>
dummy-XXXXXXXXXX-m22hq   1/1     Running   0          8s    10.128.5.158   node4   <none>
dummy-XXXXXXXXXX-nrk8z   1/1     Running   0          8s    10.129.2.103   node3   <none>
dummy-XXXXXXXXXX-xkbkb   1/1     Running   0          8s    10.131.0.56    node5   <none>

```
Then I powered off node4.
We had expected that the pod running on node4 would be moved to node5 of Zone: E03, since we set topologySpreadConstraints with "maxSkew: 1", "topologyKey: topology.kubernetes.io/zone" and "whenUnsatisfiable: DoNotSchedule".
But in actual result, the new pod got stacked with pending state.
```
$ kubectl get pod -o wide
NAME                     READY   STATUS        RESTARTS   AGE     IP             NODE    READINESS GATES
dummy-XXXXXXXXXX-dmhvr   1/1     Running       0          8m50s   10.130.2.20    node1   <none>
dummy-XXXXXXXXXX-m22hq   1/1     Terminating   0          8m50s   10.128.5.158   node4   <none>
dummy-XXXXXXXXXX-nrk8z   1/1     Running       0          8m50s   10.129.2.103   node3   <none>
dummy-XXXXXXXXXX-xgs68   0/1     Pending       0          83s     <none>         <none>  <none>
dummy-XXXXXXXXXX-xkbkb   1/1     Running       0          8m50s   10.131.0.56    node5   <none>
```
The pending Pod started to be scheduled on node5 after we unlabeled Zone: E02 from node4.

```
$ kubectl label node example-cluster-node topology.kubernetes.io/zone-
node/example-cluster-node unlabeled

$ kubectl get pod -o wide
NAME                     READY   STATUS        RESTARTS   AGE   IP             NODE    READINESS GATES
dummy-XXXXXXXXXX-dmhvr   1/1     Running       0          31m   10.130.2.20    node1   <none>
dummy-XXXXXXXXXX-m22hq   1/1     Terminating   0          31m   10.128.5.158   node4   <none>
dummy-XXXXXXXXXX-nrk8z   1/1     Running       0          31m   10.129.2.103   node3   <none>
dummy-XXXXXXXXXX-xgs68   1/1     Running       0          24m   10.131.0.63    node5   <none>
dummy-XXXXXXXXXX-xkbkb   1/1     Running       0          31m   10.131.0.56    node5   <none>
```
It seems that topologySpreadConstraints respects even zones that have no health nodes.

**What did you expect to happen?**
My expectation was that topologySpreadConstraints ignores E02 and schedule a new pod on node5.

Maybe should we use nodeTaintsPolicy?

Can we do it by setting nodeTaintsPolicy?
