### ISSUE TITLE
Customizing the manifest for the allocate device plugin

### ISSUE THREAD

**Issue by R-285** [kubernetes/kubernetes#123059]
Hi. It is necessary to process the manifest of the created pod or deployment and send the results to the device plugin during the call to the allocate method.

For example
Input:
```
spec:
   containers:
   - name: test-pod
     ............
     resources:
       requests:
         devices: 1
         deviceb: 3
       limits:
         devices: 1
         deviceb: 3
```
After that gonna perform calculations, for example in a scheduler plugin, the result would be like “a1b3someinfo”, and then send that string to the Allocate of a custom device plugin (for example, place it in the DevicesIDs field in the ContainerAllocateRequest structure, which is the content of the AllocateRequest structure received by the Allocate method)
In which component is it possible to accept and process an incoming yaml file? How can the result be delivered to the device plugin node?
