### ISSUE TITLE
Daemonset RollingUpdate does not correctly count old non-ready pods towards MaxUnavailable budget

### ISSUE THREAD

**Issue by marshallbrekka** [kubernetes/kubernetes#123232]
### What happened?

Starting with a cluster of three nodes, with a healthy deamonset pod running on each, with `updateStrategy.rollingUpdate.maxUnavailable=1`.
```
kubectl get pods
NAME                   READY   STATUS    RESTARTS   AGE
demo-daemonset-7fmn7   1/1     Running   0          17s
demo-daemonset-f49kg   1/1     Running   0          17s
demo-daemonset-mflls   1/1     Running   0          17s          
```

When performing three updates to the daemonset, each with some reason that prevents the new pods from becoming ready, I  ended up with zero ready pods.
```
kubectl get pods                                                                                                                                               
NAME                   READY   STATUS    RESTARTS   AGE
demo-daemonset-5sbf5   0/1     Running   0          9s
demo-daemonset-bswfc   0/1     Running   0          9s
demo-daemonset-jgdv7   0/1     Running   0          9s
```

### What did you expect to happen?

I would expect that when I apply an update, and the new pods fail to become ready, when I apply a second update the "new" failing pods are replaced before considering any of the oldest healthy pods.
This is similar behavior to how Deployments work.

### How can we reproduce it (as minimally and precisely as possible)?

On a three node (or any count really) cluster, create this daemonset, which is just an nginx pod with a startup probe hitting port 80.
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-daemonset
  namespace: 
  labels:
    app: demo-daemonset
spec:
  selector:
    matchLabels:
      app: demo-daemonset
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demo-daemonset
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 5
          periodSeconds: 3
```
```
kubectl get pods
NAME                   READY   STATUS    RESTARTS   AGE
demo-daemonset-7fmn7   1/1     Running   0          17s
demo-daemonset-f49kg   1/1     Running   0          17s
demo-daemonset-mflls   1/1     Running   0          17s          
```

Update the startup probe port to something other than port 80, which should cause the pod to never become ready, and apply again.
```yaml
        startupProbe:
          httpGet:
            path: /
            port: 8081
```
You can see the new unhealthy pod, and the generation of each pod
```
kubectl get pods
NAME                   READY   STATUS             RESTARTS      AGE
demo-daemonset-f49kg   1/1     Running            0             5m41s
demo-daemonset-mflls   1/1     Running            0             5m41s
demo-daemonset-zmqnj   0/1     CrashLoopBackOff   6 (46s ago)   4m59s

kubectl get pods -o 'custom-columns=NAME:.metadata.name,generation:.metadata.labels.pod-template-generation,ready:status.conditions[?(@.type=="Ready")].status'
NAME                   generation   ready
demo-daemonset-f49kg   1            True
demo-daemonset-mflls   1            True
demo-daemonset-zmqnj   2            False
```

Repeat this process for as many nodes/pods as you have (2 more in this example), changing anything that would cause the pods to be recreated (in this case I just cycled the startup probe port a few times).
```yaml
        startupProbe:
          httpGet:
            path: /
            port: 8082
```
```
kubectl get pods                                                                                                                                               
NAME                   READY   STATUS    RESTARTS   AGE
demo-daemonset-4rpgq   0/1     Running   0          3s
demo-daemonset-7wfxm   0/1     Running   0          3s
demo-daemonset-f49kg   1/1     Running   0          6m27s

kubectl get pods -o 'custom-columns=NAME:.metadata.name,generation:.metadata.labels.pod-template-generation,ready:status.conditions[?(@.type=="Ready")].status'
NAME                   generation   ready
demo-daemonset-4rpgq   3            False
demo-daemonset-7wfxm   3            False
demo-daemonset-f49kg   1            True
```

After the 2nd update, you can see that it has replaced both the 2nd generation pod (the one that was failing), and one of the first generation pods. Im now down to 1 out of 3, when I had specified `maxUnavailable=1`.

One more apply / update, and all generation 1 pods are gone, and all pods are unhealthy.
```
kubectl get pods                                                                                                                                               
NAME                   READY   STATUS    RESTARTS   AGE
demo-daemonset-5sbf5   0/1     Running   0          9s
demo-daemonset-bswfc   0/1     Running   0          9s
demo-daemonset-jgdv7   0/1     Running   0          9s

kubectl get pods -o 'custom-columns=NAME:.metadata.name,generation:.metadata.labels.pod-template-generation,ready:status.conditions[?(@.type=="Ready")].status'
NAME                   generation   ready
demo-daemonset-5sbf5   4            False
demo-daemonset-bswfc   4            False
demo-daemonset-jgdv7   4            False
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-gke.1425000
```

</details>

### Cloud provider

<details>
Reproduced this on bare metal, and GKE/GCP
</details>
