### ISSUE TITLE
[APF] Separate Events requests from non-Events

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#123280]
### What would you like to be added?

Adding separate `prioritylevel`s for Events to avoid resource competitions to non-event requests.

I currently think two ways of separation:

Option 1:

Create a new FS and PLC for events. The new FS will catch all events regardless of requestors. PLC will have a minimum `nominalConcurrencyShares`

| Name | Nominal Shares | Lendable | Borrowing Limit | Min Shares |
| ---- | -------------: | -------: | -----------------------: | --: |
| event |  5 |   100% | none | 0 |

Rules
```
  rules:
  - nonResourceRules:
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - events
      verbs:
      - '*'
    subjects:
    - group:
        name: '*'
      kind: Group
    - user:
        name: '*'
      kind: User
```

Option 2:

Create a mirror of existing FSs and PLCs for event counterparts

| Name | Nominal Shares | Lendable | Borrowing Limit | Min Shares |
| ---- | -------------: | -------: | -----------------------: | --: |
| node-high-events       |  5 |  100% | none | 0 |
| system-events          |  2 |  100% | none | 0 |
| workload-high-events   |  2 |  100% | none | 0 |
| workload-low-events    | 5 |  100% | none | 0 |
| global-default-events  |  2 |  100% | none | 0 |

The numbers of "Nominal Shares" need more thoughts to be more reasonable but they should be minimum with the hope to use borrowed concurrent shares. I am inclined to Option 1 for its simplicity. 

### Why is this needed?

In my tests that add a few hundreds of nodes to the cluster, I noticed if the machine that hosts `apiserver` & `etcd` is too small, `apiserver` can be easily stressed out and starts responding 429s and 504s (also, nodes became NotReady due to missing lease renews). However, in fact, the majority of the resources were consumed to serve event requests. If I removed events entirely, the cluster was able to survive the whole test more healthily. 

AIUI, event requests are less critical but voluminous so they likely compete currency shares with non-event requests when apiserver is under stress. It's more ideal to process Events when apiserver has free capacity.

To give a sense of competition, I observed POST requests of 3k non-event and 9.3k event from kubelet (also a few thousands from scheduler and controller-manager etc) in a test adding 200 nodes to a k8s cluster. Worth mentioning POST requests have to hit the ETCD so they are pretty expensive in terms of the duration occupying the concurrency shares as well as the machine resources.

Most importantly, event requests are resilient to temporary failures. For example, events are stored in client side up to [1000](https://github.com/kubernetes/client-go/blob/v0.29.1/tools/record/event.go#L43) before dropping. So it seems relatively safe to reject or throttle event requests.

**Comment by MikeSpreitzer** [comment]
I think this interacts with #120787, which is also reporting problems with the existing default configuration.

**Comment by MikeSpreitzer** [comment]
@linxiulei: can you try the priority level configurations suggested in https://github.com/kubernetes/kubernetes/issues/121982#issuecomment-1933534198 together with adding the following FlowSchema, which will send the kubelet Event requests to the "workload-high" priority level?

```yaml
apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  name: node-events
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 300
  priorityLevelConfiguration:
    name: workload-high
  rules:
  - resourceRules:
    - apiGroups: [ "", "events.k8s.io" ]
      namespaces: [ "*" ]
      resources: [ events ]
      verbs: [ "*" ]
    subjects:
    - group:
        name: system:nodes
      kind: Group
```

**Comment by linxiulei** [comment]
@MikeSpreitzer thanks for your suggestion. I tested this new FS in combination of https://github.com/kubernetes/kubernetes/issues/121982#issuecomment-1933534198 but it didn't work well for my test cases. I think it was mainly due to two problems with this new FS

1. the large amount of event requests impacts/starves other requests in workload-high, which are critical to complete cluster upscale (scheduling pods, initializing nodes etc)
2. the large amount of event requests are also queued in the APF waiting queue of `workload-high`, and IIUC, the borrowing takes the amount queued request into consideration to calculate how many shares should be borrowed into this thirsty PL, which results in small borrowable shares for other PLs, which has similar negative impact as 1

At this point, I feel APF configurations for events are quite tricky. To achieve what I want, the following configurations are more ideal (having a separate PL for events and shares and queues are small)

```
apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: PriorityLevelConfiguration
metadata:
  name: catch-all-events
spec:
  limited:
    nominalConcurrencyShares: 5 # it should be minimum to avoid competing with other PLs
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 10 # queue* should be also reasonably low to avoid competing borrowings with other PLs
        queues: 8
      type: Queue
  type: Limited
---
apiVersion: flowcontrol.apiserver.k8s.io/v1beta3
kind: FlowSchema
metadata:
  name: catch-all-events
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 499
  priorityLevelConfiguration:
    name: catch-all-events
  rules:
  - nonResourceRules:
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - events
      verbs:
      - '*'
    subjects:
    - group:
        name: '*'
      kind: Group
    - user:
        name: '*'
      kind: User
```
