### ISSUE TITLE
HPA External metrics with `metricType: AverageValue` don't correctly count the number of pods

### ISSUE THREAD

**Issue by RRethy** [kubernetes/kubernetes#123296]
### What happened?

When using an HPA with an external metric with `metricType: AverageValue`, it calculated the ratio of desired-to-actual by looking at the scale sub-resource's `.status.replicas`.
This caused an issue during a rolling deploy with `Deployment.spec.strategy.rollingUpdate.maxSurge: 50%` and `Deployment.spec.strategy.rollingUpdate.maxUnavailable: 0%` since the scale sub-resources `.status.replicas` will be inflated by up to 1.5x, which incorrectly tells the HPA to scale the workload down.

### What did you expect to happen?

I would expect the number of pods used when calculating the ratio of desired-to-actual to match the algorithm described in https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details.
Generally, I would expect only Ready pods to be counted, similar to the behaviour for Pod metrics.

### How can we reproduce it (as minimally and precisely as possible)?

I'm unable to get it to reproduce consistently, but the main issue is the code itself which I'll link the code flow below. I'll give a brief overview on how I reproduced it, but it's flaky and you can honestly skip this and understand the issue better by looking at the code I outline in `Anything else we need to know?`.

<details>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: foobar
  labels:
    app: ubuntu
spec:
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - test -f /tmp/ready.txt
            initialDelaySeconds: 65
          command:
            - /bin/bash
            - -c
            - --
          args:
            - while true; do sleep 30; touch /tmp/ready.txt; done
          image: ubuntu:jammy
          imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 50%
```

Then you need an HPA with a static metric and short scaleDown.stabilizationWindowSeconds, you can achieve this using Keda. To be clear, this is not specific to Keda, it's just a way to get a metric that always returns a value of `25`. This ScaledObject will create an external metric for the fallback with a `metricType: AverageValue`.

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: myscaledobject
  namespace: foobar
spec:
  scaleTargetRef:
    kind: Deployment
    name: mydeployment
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 10
              periodSeconds: 15
  fallback:
    failureThreshold: 1
    replicas: 25
  pollingInterval: 15
  minReplicaCount: 10
  maxReplicaCount: 50
  triggers:
  - type: prometheus
    name: invalid_trigger
    metricType: AverageValue
    metadata:
      serverAddress: http://fake.svc.cluster.local:9090
      threshold: "1"
      activationThreshold: "0"
      query: >
        max(mymetric1{}[2m])
```

After doing many deployments, eventually you'll see it scale down. You can also do a `kubectl get hpa -w` to see the target ratio be something like `0.673m/1.0` during a deploy. 

</details>

### Anything else we need to know?

Here is the code flow for the HPA:

1. [computeReplicasForMetric](https://github.com/kubernetes/kubernetes/blob/015e76aa24ebfebfd64062e1161059ac62ddabc9/pkg/controller/podautoscaler/horizontal.go#L424) is called
2. Which takes [this branch](https://github.com/kubernetes/kubernetes/blob/015e76aa24ebfebfd64062e1161059ac62ddabc9/pkg/controller/podautoscaler/horizontal.go#L488-L489)
3. [computeStatusForExternalMetric](https://github.com/kubernetes/kubernetes/blob/015e76aa24ebfebfd64062e1161059ac62ddabc9/pkg/controller/podautoscaler/horizontal.go#L685) is called
4. Which takes [this branch](https://github.com/kubernetes/kubernetes/blob/015e76aa24ebfebfd64062e1161059ac62ddabc9/pkg/controller/podautoscaler/horizontal.go#L686-L687)
5. [GetExternalPerPodMetricReplicas](https://github.com/kubernetes/kubernetes/blob/015e76aa24ebfebfd64062e1161059ac62ddabc9/pkg/controller/podautoscaler/replica_calculator.go#L354) is called
6. Which calculates a replica count [here](https://github.com/kubernetes/kubernetes/blob/015e76aa24ebfebfd64062e1161059ac62ddabc9/pkg/controller/podautoscaler/replica_calculator.go#L368-L375)
7. [Which uses the raw statusReplicas](https://github.com/kubernetes/kubernetes/blob/015e76aa24ebfebfd64062e1161059ac62ddabc9/pkg/controller/podautoscaler/replica_calculator.go#L368) value when calculating the desired-to-actual ratio
8. statusReplicas can be traced back to [scale.Status.replicas](https://github.com/kubernetes/kubernetes/blob/015e76aa24ebfebfd64062e1161059ac62ddabc9/pkg/controller/podautoscaler/horizontal.go#L307) which gets the status replicas on the scale sub-resource of the deployment. This includes unready pods.

However, the [Kubernetes documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details) says the algorithm for `metricType: AverageValue` should list the pods in the scale target, then filter out unready pods and terminating pods (I'm simplifying for brevity), and use that value as the available replicas when calculating the ratio.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9-gke.1507000", GitCommit:"72c9a88fa43c09937d03b1bbc2141631d040c1aa", GitTreeState:"clean", BuildDate:"2023-10-09T09:32:44Z", GoVersion:"go1.20.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux web-7c9fc4c85b-xcl4g 5.15.107+ #1 SMP Thu Jun 29 09:19:06 UTC 2023 x86_64 GNU/Linux
```

</details>
