### ISSUE TITLE
Treat liveness probe-based restarts as a voluntary disruptions gated by PodDisruptionBudgets

### ISSUE THREAD

**Issue by MarcPow** [kubernetes/kubernetes#123204]
### What would you like to be added?

Prevent liveness probes from driving all pods in a cluster down (by treating a container restart as a gated, voluntary disruption)

### Why is this needed?

Overly sensitive liveness probes have the potential to cause outage.  Categorizing restarts as voluntary disruptions that must be budget checked provides natural gating to protect Service availability.

**Comment by MarcPow** [comment]
This appears related to #66230.  The objections therein seem to be related to implementation complexity, but it's not clear to me why we can't simply treat a container restart as a pseudo-eviction and get the behavior that we want.  No one can argue that an interior pod restart is semantically, if not physically, not equivalent to a pod eviction followed by a rescheduling on the same node.

Perhaps we could solve this in sig-node by adding a liveness-failure-mode that actually promotes to evicting the pod itself (rather than restarting the container).  If that opt-in failure mode were added, we'd get PDB checks for free.

**Comment by thockin** [comment]
@tallclair

**Comment by sftim** [comment]
Restarting a container is **not** an eviction, not even a pseudo one. If we were failing Pods outright (which Kubernetes AIUI right now doesn't do as a direct outcome from a probe failure), then a disruption budget might be appropriate.

Bear in mind that container restarts on probe failure are available to static Pods; this is super useful for keeping the control plane available in the event of a partial outage. It can even help with a situation where all the API server Pods fail, but in a way that they can recover from individually.

> Perhaps we could solve this in sig-node by adding a liveness-failure-mode that actually promotes to evicting the pod itself (rather than restarting the container). If that opt-in failure mode were added, we'd get PDB checks for free.

Yes, that feels like the way to go.

---

If we still want to support conditional container restarts, I would add a new opt-in API. The kubelet would try to create or interact with a subresource on Pod. For Pods that opted in, the kubelet would respond to container probe failure by trying incrementing the container restart request counter. And then if that change to status was admitted, the kubelet increments the container restart counter.

```yaml
spec:
  ...
  containers:
  - name: example
    image: registry.k8s.io/pause:1-healthcheckable
    args:
    - --forever
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      probeFailureAction: container-restart-request # new field, new value
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    restartRequestCount: 18                         # exposed via a subresource?
status:
   ...
  containerStatuses:
  - name: example
    ready: true
    containerID: 8d6a0af603edb6c668967d64a2a6
    ...
    restartCount: 23                                # how many actual restarts
```

**Comment by MarcPow** [comment]
>> Perhaps we could solve this in sig-node by adding a liveness-failure-mode that actually promotes to evicting the pod itself (rather than restarting the container). If that opt-in failure mode were added, we'd get PDB checks for free.
> Yes, that feels like the way to go.

Modifying your example, perhaps we can simplify:

```yaml
containers:
  - name: example
    image: registry.k8s.io/pause:1-healthcheckable
    args:
    - --forever
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      probeFailureAction: evict-containing-pod
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
```
