### ISSUE TITLE
HPA autoscaling triggered on rolling updates

### ISSUE THREAD

**Issue by hleal18** [kubernetes/kubernetes#123325]
### What happened?

We have a setup that consists of a deployment and HPA manifest. The HPA is configured with a CPU threshold relying on custom metrics API. We’re using `prometheus-adapter` as a custom metrics solution.

We’ve observed that any action that triggers a rolling update, the update process adds one extra instance. So an initial deployment of 1 replica after the rolling update is finished is going to end up with 2 replicas (sometimes 3) until the HPA scales the replicas back down after the stabilization window.

There’s no CPU outburst during this time and CPU metrics are nowhere near the configured threshold.

The event **`New size: 2; reason: pods metric container_cpu_usage_seconds_total above target`** is reported but that’s misleading given that the metric value it’s not close to the threshold. Also, this scale up decision is usually made when metrics for the new pod are still not available but the ones for the old pod can still be fetched.

### What did you expect to happen?

I expected that no scaling up action would be triggered unless the metric indeed goes above the threshold. Instead, one extra instance is provisioned during the rolling update which it’s not aligned with the way HPA with custom metrics is intended to work. 

This also leads to situations where unnecessary compute is used during rolling updates.

### How can we reproduce it (as minimally and precisely as possible)?

The following deployment and HPA manifests are used to reproduce it. 

Deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-autoscaling-debugging
  namespace: default
spec:
  selector:
    matchLabels:
      app: hpa-autoscaling-debugging
  template:
    metadata:
      labels:
        app: hpa-autoscaling-debugging
    spec:
      containers:
        - name: main-service
          image: hleal18/ubuntu-stress-ng:latest
          command: ['stress-ng']
          args: ['-c', '1', '-l', '5']
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - "-c"
              - echo
              - hello
            initialDelaySeconds: 45
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "1"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

HPA
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-autoscaling-debugging
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: hpa-autoscaling-debugging
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Pods
      pods:
        metric:
          name: container_cpu_usage_seconds_total
        target:
          type: AverageValue
          averageValue: 450m
```

Prometheus and prometheus-adapter have to be installed in the cluster as well. This is the configuration used when installed through the helm charts:

Prometheus-adapter
```
prometheus:
  url: <http://prometheus-server.prometheus.svc.cluster.local>
  port: 80
rules:
  default: false
  custom:
  - seriesQuery: '{namespace!="",__name__="container_cpu_usage_seconds_total"}'
    resources:
      template: <<.Resource>>
    name:
      matches: ""
      as: ""
    metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container!=""}[1m])) by (<<.GroupBy>>)
```

Prometheus
```
alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
```

It can be reproduced by deploying a workload and HPA with a threshold supported by the prometheus-adapter component. In this case `container_cpu_usage_seconds`. Then a rolling update action has to be triggered, usually a restart action does the job. This should be enough to check how an extra pod is provisioned during the rolling update process and the HPA metrics are not even close to the threshold.

### Anything else we need to know?

- It’s hard to reproduce on a deployment without a `readinessProbe`. However, adding it with `initialDelaySeconds: 45` showed that this can be reproduced quite consistently. During a rolling update, after 10-20 seconds of the first pod getting created, the second one is provisioned as a consequence of a scaling up event from the HPA.
- Without the readiness probe, it’s a matter of the HPA sync period timing the query to the custom metrics API when the new pod has all containers running and just before the old pod enters into `Terminating` state.
- Normally in a configuration with `minReplicas: 1` and `maxReplicas: 5` , and not high CPU usage, after the rolling update is done, the new `replicaSet` is going to end up with 2 replicas. Nonetheless, we’ve also seen occasions where it goes up to 3 replicas as well.

### Kubernetes version

We’ve tested this on GKE with 1.27 and 1.28 releases.

### Cloud provider

We've been using GKE clusters.
