### ISSUE TITLE
force-delete pod execute prestop hook

### ISSUE THREAD

**Issue by liangjingtao11** [kubernetes/kubernetes#123408]
### What happened?

as the pr https://github.com/kubernetes/kubernetes/pull/49449 said：Do not try to run preStopHook when the gracePeriod is 0 。 When we execute a force delete pod, it will not execute a pre-stop hook。But this pr https://github.com/kubernetes/kubernetes/pull/115835 Disrupted this behavior。It will execute a pre-stop hook when force delete。

### What did you expect to happen?

https://github.com/kubernetes/kubernetes/pull/49449
https://github.com/kubernetes/kubernetes/pull/115835

The behavior of the above two PR is conflicting. I don't know which approach meets expectations

### How can we reproduce it (as minimally and precisely as possible)?

1 use this yaml apply pod：
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: hub.easystack.io/captain/nginx:1.21
        volumeMounts:
        - name: root-volume
          mountPath: /root/
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo 'hello world' > /root/tempfile && sleep 5"]
      volumes:
      - name: root-volume
        hostPath:
          path: /root/
```

2  force delete one pod：
kubectl delete po nginx-daemonset-pml7f --force

You can see the result of the pre-stop execution

### Kubernetes version

<details>

```console
$ kubectl version
server Version: v1.28.2
# paste output here
```

</details>

### Cloud provider

<details>
..
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Linux node-1.domain.tld 4.18.0-372.19.1.es8_8.x86_64 #1 SMP Tue Jan 2 14:54:00 CST 2024 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
