### ISSUE TITLE
Scheduler: Avoid scheduling pods to nodes where the allocatable resource is insufficient for the pod limit resource

### ISSUE THREAD

**Issue by NoicFank** [kubernetes/kubernetes#123553]
### What would you like to be added?

Should we consider pod `limit resource` during scheduling to prevent pod scheduled to node where the allocatable resource is insufficient for the pod limit resource? 

There are two impl ways:
1. soft solution: Maintain current behavior but prefer nodes with sufficient allocatable resource for the pod limit resource.
2. hard solution: Reject node with insufficient allocatable resource for the pod limit resource.

Is in-tree plugin better than out-of-tree plugin to implement?

# Current Behavior Example
e.g. 
pod 
```
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: xxx
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      resources:
        limits:
          memory: '100Gi'
          cpu: 100
        requests:
          memory: '1Gi'
          cpu: 1
  dnsPolicy: Default
  volumes:
    - name: workdir
      emptyDir: {}

```

node
<img width="835" alt="image" src="https://github.com/kubernetes/kubernetes/assets/18323315/c2f17a75-ed71-4a6b-bb3e-d24e3fd9dcd1">

currently, pod will be scheduled to this node successfully. We expect it can't be scheduled to this node for hard solution, or this node is not the first choice for soft solution.

/sig scheduling
/triage accepted
/assign @Huang-Wei 

### Why is this needed?

the limit resource on pod will be meaningless, if the value of pod limit resource larger than node allocatable resource. Since the real limit resource of this pod will be the allocatable resource on this node. 

For example, nodeA with allocatable cpu 4c, podA with request cpu 2c, limit cpu 6c, and podA located on nodeA. Then the real limit cpu of this pod will be 4c, instead of 6c.
