### ISSUE TITLE
Completed Job leaves orphaned pod

### ISSUE THREAD

**Issue by v-novytskyi** [kubernetes/kubernetes#123704]
### What happened?

We have a job template:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: REPLACE_ME
spec:
  backoffLimit: 6
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: test
    spec:
      serviceAccountName: job-sa
      containers:
      - name: document-test
        resources:
          limits:
            memory: 2000Mi
            cpu: 2000m
          requests:
            memory: 500Mi
            cpu: 500m
        image: REPLACE_ME
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: secrets-volume
            mountPath: /app/secrets
      restartPolicy: Never
      volumes:
        - name: secrets-volume
          secret:
            secretName: ****-secrets
```

After launching a random number of jobs (10-600), all jobs are deleted after completion, whether the status is succeeded or failed. However, this does not remove all associated pods and leaves a random number of orphaned pods.

The problem arose suddenly, there were no changes to the teamplate. There are also no changes in the args for the container.

### What did you expect to happen?

As before, I expected that all associated pods would be deleted after deleting the jobs.

### How can we reproduce it (as minimally and precisely as possible)?

If there needed i can share my full job part.

### Kubernetes version

<details>

```console
$ kubectl version
serverVersion:
  buildDate: "2024-01-02T20:34:38Z"
  compiler: gc
  gitCommit: 3f8ed3d5017d988600f597734a4851930eda35a6
  gitTreeState: clean
  gitVersion: v1.27.9-eks-5e0fdde
  goVersion: go1.20.12
  major: "1"
  minor: 27+
  platform: linux/amd64
```

</details>

### Cloud provider

<details>
aws
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
$ uname -a
Linux 5.10.209-198.858.amzn2.x86_64 #1 SMP Tue Feb 13 18:46:41 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kannon92** [comment]
Do you see any webhooks interfering with this? Anything in the logs?

**Comment by kannon92** [comment]
Are the pods terminating by chance?

**Comment by v-novytskyi** [comment]
@kannon92 
> Do you see any webhooks interfering with this? Anything in the logs?

No, there nothing in webhooks, nothing anomaly in logs
```
status:
  phase: Succeeded
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      reason: PodCompleted
  containerStatuses:
    - name: loader
      state:
        terminated:
          exitCode: 0
          reason: Completed
      lastState: {}
      ready: false
```


> Are the pods terminating by chance?

Jobs all complete without problems, pods complete their work randomly. I didn't find any logic. This could be a random under. Out of 100 launched, today, for example, 8 were not deleted.
