### ISSUE TITLE
patching a service with the same value ipFamilyPolicy: "RequireDualStack" causes an error

### ISSUE THREAD

**Issue by tibeer** [kubernetes/kubernetes#123761]
### What happened?

1. Used the [ingress-nginx](https://github.com/kubernetes/ingress-nginx) helm chart to deploy a dual stack ingress.
2. Ran helm upgrade --install with the exact same values again to gain idempotancy
3. Got an error that describes, that ipFamilyPolicy cannot be patched, even though the same value "RequireDualStack" was used.
4. Created a [bug](https://github.com/kubernetes/ingress-nginx/issues/11068) on ingress-nginx because I initially thought this was an issue with the helm-chart
5. The folks over there were kind enough to route me here with a more comprehensive point to look at: https://github.com/kubernetes/kubernetes/blob/dc3f5ec6ccb9855dfa99f4c1078625df5fdfab6a/pkg/registry/core/service/storage/alloc.go#L184

### What did you expect to happen?

A patch with the same value in the service will not result in an error.

### How can we reproduce it (as minimally and precisely as possible)?

```sh
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update

# 1st installation on a fresh cluster, no issues
helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace --reuse-values --set resources=null --set controller.service.ipFamilyPolicy=RequireDualStack --wait

# 2nd try, same cluster, this time the error happens
helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace --reuse-values --set resources=null --set controller.service.ipFamilyPolicy=RequireDualStack --wait
```

### Anything else we need to know?

Independent of cloudprovider or used loadbalancers, this issue comes directly from kubernetes itself.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.2
Server Version: v1.28.2
```

</details>

### Cloud provider

<details>
Doesn't matter
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux beta 5.15.0-1052-oracle #58-Ubuntu SMP Tue Feb 13 19:44:34 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
runc
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
probably not of interest, but
- calico
- longhorn
- metallb
</details>

**Comment by pacoxu** [comment]
/sig network
for triage

**Comment by aojea** [comment]
@tibeer do you think is possible to get more details on the specific requests? 

I can see you already reproduced it with kubectl https://github.com/kubernetes/ingress-nginx/issues/11068#issuecomment-1978582191

Using `-v 7` gives us the exact http queries that is going to be easier to understand the problem
```
kubectl -v7 get pods
I0307 15:28:37.522962 4119311 loader.go:395] Config loaded from file:  /usr/local/google/home/aojea/.kube/config
I0307 15:28:37.523999 4119311 round_trippers.go:463] GET https://[::1]:41079/api?timeout=32s
I0307 15:28:37.524016 4119311 round_trippers.go:469] Request Headers:
I0307 15:28:37.524025 4119311 round_trippers.go:473]     Accept: application/json;g=apidiscovery.k8s.io;v=v2beta1;as=APIGroupDiscoveryList,application/json
I0307 15:28:37.524032 4119311 round_trippers.go:473]     User-Agent: kubectl/v1.29.1 (linux/amd64) kubernetes/bc401b9
I0307 15:28:37.529714 4119311 round_trippers.go:574] Response Status: 200 OK in 5 milliseconds
I0307 15:28:37.531752 4119311 round_trippers.go:463] GET https://[::1]:41079/apis?timeout=32s
I0307 15:28:37.531770 4119311 round_trippers.go:469] Request Headers:

```

If you can just

**Comment by tibeer** [comment]
Okay, tried to reproduce it and now it worked. But I figured out why: In helm when I run with `--dry-run=server` I can see the templates that are applies, and the service looks like this when patched:

```yaml
# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: ingress-nginx-4.10.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: "1.10.0"
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  ipFamilyPolicy: RequireDualStack
  ipFamilies: 
    - IPv4
  ports:
  (...)
```

I am pretty sure the problem is not the ipFamilyPolicy, but rather the ipFamiles that are onlyl set now to "IPv4". Kuberentes detects this only on a patch as there is now a "difference" but not on first time installs, could that be right?
Now the question is: Who is having the false behaviour here? Kubernetes or helm / the ingress-nginx helm chart?

**Comment by tibeer** [comment]
Confirmed that. There is an extra setting on the helm chart for `ipFamilies` that needs to be set, too. A little cumbersome that the kubernetes API requires both ipFamilies to be set if the ipFamilyPolicy is set to RequireDualStack, but not a big deal. Thanks for your help!

**Comment by aojea** [comment]
> A little cumbersome that the kubernetes API requires both ipFamilies to be set if the ipFamilyPolicy is set to RequireDualStack, but not a big deal. Thanks for your help!

```
  type: LoadBalancer
  ipFamilyPolicy: RequireDualStack
  ipFamilies: 
    - IPv4
  ```
the problem is that you are saying "require dual stack but only use IPv4", if you leave ipFamilies empty it has to work and infer the field from the other
