### ISSUE TITLE
pod topologySpreadConstraints nodeAffinityPolicy: Ignore not work？

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#123746]
### What happened?

crd
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx
```

```
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: myapp
spec:
  containers:
  - name: web-server
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: In
            values:
            - web
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app: myapp
    nodeAffinityPolicy: Ignore
```

```
root@29-b:~# kubectl get pod -n k8s  -owide -w
NAME                                READY   STATUS    RESTARTS   AGE   IP           NODE        NOMINATED NODE   READINESS GATES
myapp-deployment-7546cdb555-d55cf   1/1     Running   0          57m   10.0.1.118   worker-03   <none>           <none>
myapp-deployment-7546cdb555-dt4vs   1/1     Running   0          57m   10.0.0.129   worker-01   <none>           <none>
myapp-deployment-7546cdb555-j9v5z   1/1     Running   0          57m   10.0.1.61    worker-03   <none>           <none>
myapp-deployment-7546cdb555-kc9zf   1/1     Running   0          57m   10.0.3.79    master-01   <none>           <none>
myapp-deployment-7546cdb555-tzbnj   1/1     Running   0          57m   10.0.2.182   worker-02   <none>           <none>
myapp-deployment-7546cdb555-zjmsw   1/1     Running   0          57m   10.0.0.94    worker-01   <none>           <none>
web-server                          0/1     Pending   0          12m   <none>       <none>      <none>           <none>
```

2m16s       Warning   FailedScheduling    pod/web-server                           0/4 nodes are available: 4 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.

nodeTaintsPolicy has the same problem

### What did you expect to happen?

ignore nodeaffinity

### How can we reproduce it (as minimally and precisely as possible)?

apply my crd,node without that label

### Kubernetes version

<details>

```console
^Croot@29-b:~ kubectl versionon
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
```

</details>

### Cloud provider

<details>
vmware
</details>

### OS version

<details>

```console
root@29-b:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
