### ISSUE TITLE
Discussion Feature: Ability to use downward API in node/pod Affinity/antiAffinity

### ISSUE THREAD

**Issue by p53** [kubernetes/kubernetes#123987]
Problem:

we have platform where batch jobs of various size will be submitted by users. Thus we need to dynamically request/select instances for pods based on resources for each pod=step in batch jobs. We are provisioning instances with karpenter, so we have several NodeClasses/PRovisioners (which contain available types of instances, which are initializied based on pod resource requirements), our problem is that those pods often will be placed on instances which have more resources than it was requested, because pods e.g. from previous steps asked for big machine, they are finished, but big machine is still there (and thus we are paing for it) and k8s schedules them there because they are free, because it takes some time before it is garbage collected. What we would like to have is referencing resources from pod spec in node affinity rules so that  we can e.g write:
```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - nodeSelectorTerms:
        matchExpressions:
        - key: karpenter.aws.io/instance-cpu
          operator: In
          values:
          - valueFrom:
              fieldRef:
                fieldPath: spec.resource.requests.cpu
```

There can be probably also other applications of this: https://stackoverflow.com/questions/48223562/how-to-create-statefulset-with-nodeaffinity
