### ISSUE TITLE
Provide Support  to HPA to autoscale the target resource by label as well 

### ISSUE THREAD

**Issue by shashikumar09** [kubernetes/kubernetes#123923]
### What would you like to be added?

Currently in HPA,  we define target resource  in below format. 

```
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-deployment

```
it basically scales the resource matching above apiVersion, kind and name. 

Along with above feature, if we add label. it will scale up all the resources matching that label for given kind and apiVersion

Example:
```
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    label:
      app.kubernetes.io/name:  my-app
```

### Why is this needed?

We had a requirement to scale up the multiple resources to the same number of replicas during high CPU usage. 

But if we use HPA for each deployment, the replica count is not matching with other resources. 

Let say, we have 3 deployments
1. Deployment-1
2. Deployment-2
3. Deployment-3

During peak usage,  if we have requirement scale all 3 deployments by same number of replicas, we can have common label to scale all 3 deployment,.
