### ISSUE TITLE
Both Endpoints and EndpointSlices not working with Service abstraction for external IPs

### ISSUE THREAD

**Issue by PMacho** [kubernetes/kubernetes#123954]
### What happened?

As recommend in https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors I did try to abstract access to an externally hosted mariaDB. However, both the recommend approach and the legacy approach with Endpoints did not work as expected. There is a slight difference however, in the EndpointSlice case the service description showed `Endpoints: <none>` while in the endpoints case it was empty, i.e. `Endpoints: `.

### What did you expect to happen?

The external database should be reachable through the service abstraction.

### How can we reproduce it (as minimally and precisely as possible)?

It is a clean K3s with --disable traefik, nginx ingress as well as cert-manager installed via helm, plus GitLab Agent for Kubernetes also using Helm.

The Service:

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
```

I've tried both, EndpointSlice:

``` yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mariadb-1
  labels:
    kubernetes.io/service-name: mariadb
addressType: IPv4
ports:
  - name: mysql
    port: 3306
    protocol: TCP
endpoints:
  - addresses:
    - 10.0.0.5
```

, and Endpoints:

``` yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: mariadb
subsets:
  - addresses:
      - ip: 10.0.0.5
    ports:
      - name: mysql
        port: 3306
```

Both were successfully deployed in the same namespace as the service and linked to the service.

## case: EndpointSlices

```
kubectl get endpointslice -l kubernetes.io/service-name=mariadb

NAME        ADDRESSTYPE   PORTS   ENDPOINTS   AGE
mariadb-1   IPv4          3306    10.0.0.5    3m29s
```
```
kubectl describe service mariadb

Name:              mariadb
Namespace:         keldysh-projects-workshop
Labels:            app.kubernetes.io/managed-by=Helm
Annotations:       meta.helm.sh/release-name: service
                   meta.helm.sh/release-namespace: keldysh-projects-workshop
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.43.126.23
IPs:               10.43.126.23
Port:              <unset>  3306/TCP
TargetPort:        3306/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

## case: Endpoints

```
kubectl describe endpoints mariadb

Name:         mariadb
Namespace:    keldysh-projects-workshop
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: service
              meta.helm.sh/release-namespace: keldysh-projects-workshop
Subsets:
  Addresses:          10.0.0.5
  NotReadyAddresses:  <none>
  Ports:
    Name   Port  Protocol
    ----   ----  --------
    mysql  3306  TCP

Events:  <none>
```
```
kubectl describe service mariadb

Name:              mariadb
Namespace:         keldysh-projects-workshop
Labels:            app.kubernetes.io/managed-by=Helm
Annotations:       meta.helm.sh/release-name: service
                   meta.helm.sh/release-namespace: keldysh-projects-workshop
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.43.126.23
IPs:               10.43.126.23
Port:              <unset>  3306/TCP
TargetPort:        3306/TCP
Endpoints:         
Session Affinity:  None
Events:            <none>
```

### Anything else we need to know?

DNS is working in principle:

```
kubectl exec -i -t dnsutils -- nslookup mariadb

Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   mariadb.keldysh-projects-workshop.svc.cluster.local
Address: 10.43.19.67
```

I already submitted a bug report in the K3s repository. They however claim to not change the core kubernetes functionality:
https://github.com/k3s-io/k3s/issues/9725
https://github.com/k3s-io/k3s/discussions/9726

### Kubernetes version

K3s Version:
k3s version v1.28.7+k3s1 (https://github.com/k3s-io/k3s/commit/051b14b248655896fdfd7ba6c93db6182cde7431)
go version go1.21.7

### Cloud provider

Self hosted K3s on Hetzner Cloud Servers

### OS version

Linux kubernetes-test-server 5.15.0-91-generic https://github.com/k3s-io/k3s/issues/101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
Can you explain exactly what you expect to happen? is not very clear from your description,

do you expect that a pod that tries to connect to the Service ClusterIP `10.43.0.10` ends connected to the IP `10.0.0.5` ?

Have you verified all connectivity works without services too?

**Comment by PMacho** [comment]
@aojea 


The documentation of "Services without Selectors" https://kubernetes.io/docs/concepts/services-networking/service/#service-no-selector-access explicitly states 
> Accessing a Service without a selector works the same as if it had a selector. In the [example](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors) for a Service without a selector, traffic is routed to one of the two endpoints defined in the EndpointSlice manifest: a TCP connection to 10.1.2.3 or 10.4.5.6, on port 9376.

Where the "example" defines:

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
```

and 
``` yaml
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-service-1 # by convention, use the name of the Service
                     # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: my-service
addressType: IPv4
ports:
  - name: '' # empty because port 9376 is not assigned as a well-known
             # port (by IANA)
    appProtocol: http
    protocol: TCP
    port: 9376
endpoints:
  - addresses:
      - "10.4.5.6"
  - addresses:
      - "10.1.2.3"
```

Therefore, in my configuration I expect `r2dbc:mariadb://mariadb` to be routed to `10.0.0.5`, instead of complaining `Connection refused: mariadb.debug-endpoints.svc.cluster.local/10.43.202.125:3306`.

For the record, defining the service to be headless, i.e. `spec.clusterIP: "None"`, does route to `10.0.0.5`. However, https://kubernetes.io/docs/concepts/services-networking/service/#headless-services states: 
> Sometimes you don't need load-balancing and a single Service IP.
Considering that the Database may very well be a cluster, this does not necessarily apply.


The requested output of `iptables save`, with the above configuration deployed to namespace `debug-endpoints`:
[iptables-save.txt](https://github.com/kubernetes/kubernetes/files/14624940/iptables-save.txt)
