### ISSUE TITLE
Server-side apply has trouble with empty map

### ISSUE THREAD

**Issue by annasong20** [kubernetes/kubernetes#124050]
### What happened?

Every time I server-side apply a `Deployment` with `spec.template.metadata.annotations: {}`, the `resourceVersion` updates. Nothing about my manifest changes between applies; if I map `annotations` to the empty map, `kubectl apply --server-side` the same manifest updates the `resourceVersion`. With client-side apply, the `resourceVersion` stays the same as long as my manifest remains constant, even if `annotations: {}`.

I read in #70281 that Kubernetes should treat absent keys, empty values (in this case, an empty map), and `null` values the same. I observe that leaving the `annotations` key out and `annotations: null` behave as expected, not modifying the `Deployment` and leaving `resourceVersion` the same, but empty map `{}` behaves as described above.

If we cannot change this behavior, I'd at least like to understand the rationale behind it.

### What did you expect to happen?

I expected my `Deployment` object to stay the same between identical server-side applies, where the manifest file content was exactly the same, regardless of the value of `spec.template.metadata.annotations`. A different `resourceVersion` every apply indicates that the object was event type `MODIFIED`. I expect no events to fire on applying the same manifest.

### How can we reproduce it (as minimally and precisely as possible)?

1. Say `deployment.yaml` contains https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment. In actuality, any `Deployment` is fine.
2. Add `spec.template.metadata.annotatations: {}`.
3. `kubectl apply --server-side deployment.yaml`
4. `kubectl get deployment nginx-deployment -o yaml`

Every successive repeat of steps 3-4 should show different `metadata.resourceVersion` values.

Example of `Deployment` with `spec.template.metadata.annotatations: {}`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations: {}
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

### Anything else we need to know?

This is especially a problem when I server-side apply with code in my operator. My operator is built on https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern and watches changes to the child objects it deploys. If I create a `Deployment` with `spec.template.metadata.annotations: {}`, the operator constantly reconciles because every server-side apply of the manifest registers as a type `MODIFIED` event on the object, which triggers the watching operator to reconcile.

### Kubernetes version

```console
$ kubectl version --short
Client Version: v1.27.11
Kustomize Version: v5.0.1
Server Version: v1.27.8-gke.1067004
```

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
ID=debian
$ uname -a
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
