### ISSUE TITLE
Kubernetes Skips Init Containers Beyond First During Some Pod Restarts

### ISSUE THREAD

**Issue by mike-capyh** [kubernetes/kubernetes#124002]
### What happened?

Init containers beyond the first are ignored during certain pod restarts.  In particular, when the pod sandbox suddenly temporarily disappears (possibly due to a node restart) the automatic restart sequence of the pod seems to skip init containers after the first.

### What did you expect to happen?

From the [Kubernetes docs](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior):

"If the Pod [restarts](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#pod-restart-reasons), or is restarted, all init containers must execute again."

### How can we reproduce it (as minimally and precisely as possible)?

Below `repro.yaml` is a trimmed-down deployment:
two init containers and a primary container, all running bash.
Primary just sleeps, init containers each echo and exit.

Apply the yaml, let it get running, and then, eg, forcibly kill its pod sandbox (variety of methods, depending on CRI, host environment, etc..):

A specific repro that assumes a linux host, containerd:

```bash
kubectl create namespace delme
kubectl apply -f repro.yaml
kubectl get pods -n delme  # confirm the deployment started normally

# simulate a node/sandbox-level disruption by killing pod's slice (probably a better way to do this..?)
# run next command on **node host**:
sudo systemctl stop --force \
 "$(ps -o cgroup --pid "$(pgrep --full 'pgrepid:PkIOeQU4J6zI')" |
 sed -ne '2s/.*\(kubepods-besteffort-pod.*\.slice\).*/\1/p')"

kubectl describe pods -n delme
```

The restart count of the second init container is 0, while main container and first init container are 1.  Can repeat the stop, and the restart count of the first init container will increment, staying in sync with the main container and the overall pod restart counter, but the second init container stays at 0.  Start/finish time stamps in describe, and results of `kubectl logs`, are also consistent with the second init container not being re-run.

And here's `repro.yaml`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi-init-container-bug-repro
  name: multi-init-container-bug-repro
  namespace: delme
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: multi-init-container-bug-repro
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: multi-init-container-bug-repro
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - /bin/bash
        - -c
        - sleep infinity && echo 'pgrepid:PkIOeQU4J6zI'
        image: debian:stable
        imagePullPolicy: IfNotPresent
        name: main
      initContainers:
      - command:
        - /bin/bash
        - -c
        - "echo 'init-container: First!'"
        image: debian:stable
        imagePullPolicy: IfNotPresent
        name: init-first
      - command:
        - /bin/bash
        - -c
        - "echo 'init-container: Second!'"
        image: debian:stable
        imagePullPolicy: IfNotPresent
        name: init-second
      restartPolicy: Always
```

## Practical Impact:

Deployments that use multiple init containers (which includes some popular ones, eg gitlab via helm) can get stuck during their auto restart after a transient node outage (requiring manual intervention to get unstuck).  In production, this is hopefully a rare (but potentially unpleasant) event.  It is fairly common and annoying in certain kinds of development/test configurations if eg intentional host node restarts are common.

## Workarounds:

Deleting the pod through `kubectl delete pod`, or `kubectl rollout restart`ing its eg deployment, causes init containers to be re-run when the pod is restarted (or more precisely, when the fresh replacement pod is started).

## Additional Notes

- [This issue](https://github.com/kubernetes/kubernetes/pull/47599) might be related.
- In the repro below, if instead of killing the whole pod sandbox, just the main container is killed, then `kubectl get pods` again reports a restart, but `describe` now shows *both* init containers are skipped.  This might be intended behavior? It is less-obviously-bad than arbitrarily skipping just some init containers, as happens in the main repro path.. but if the restart count in the output of `kubectl get pods` is to be interpreted as the "number of pod restarts", it seems like this path also contradicts the cited docs.

### Kubernetes version

Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.1

### Cloud provider

n/a (repros on bare-metal `kubeadm`)

### OS version

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

containerd github.com/containerd/containerd v1.7.5 fe457eb99ac0e27b3ce638175ef8e68a7d2bc373

**Comment by rockswe** [comment]
Hi Mike.

I modified the init container commands to use the workaround script and added a shared emptyDir volume for the completion markers. This configuration adds an emptyDir volume named init-completion-markers, which is mounted into both init containers and the main container at /tmp/init-markers. Each init container now checks for the presence of its specific marker file before executing its main command. If the marker is not present, it executes the command and creates the marker. This makes sure that on pod restart, if the init container was previously completed successfully, it will not re-execute its payload, effectively working around the issue.

Try this revised version of "repro.yaml":

`apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multi-init-container-bug-repro
  name: multi-init-container-bug-repro
  namespace: delme
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: multi-init-container-bug-repro
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: multi-init-container-bug-repro
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - /bin/bash
        - -c
        - sleep infinity && echo 'pgrepid:PkIOeQU4J6zI'
        image: debian:stable
        imagePullPolicy: IfNotPresent
        name: main
        volumeMounts:
        - name: init-completion-markers
          mountPath: /tmp/init-markers
      initContainers:
      - command:
        - /bin/bash
        - -c
        - >
          if [ ! -f /tmp/init-markers/init-first ]; then
            echo 'init-container: First!';
            touch /tmp/init-markers/init-first;
          fi
        image: debian:stable
        imagePullPolicy: IfNotPresent
        name: init-first
        volumeMounts:
        - name: init-completion-markers
          mountPath: /tmp/init-markers
      - command:
        - /bin/bash
        - -c
        - >
          if [ ! -f /tmp/init-markers/init-second ]; then
            echo 'init-container: Second!';
            touch /tmp/init-markers/init-second;
          fi
        image: debian:stable
        imagePullPolicy: IfNotPresent
        name: init-second
        volumeMounts:
        - name: init-completion-markers
          mountPath: /tmp/init-markers
      restartPolicy: Always
      volumes:
      - name: init-completion-markers
        emptyDir: {}
`

**Comment by mike-capyh** [comment]
Hi rockswe,

Thank you for taking the time to look into this, it is much appreciated!

I ran the repro procedure using the modified `repro.yaml`. Unfortunately, the second init container still gets skipped (restart count 0).

It appears that the proposed workaround is intended to prevent ill effects of init containers *running inconveniently often* (eg if have non-idempotent init).

However, the problem I ran into is that the init containers *don't run often enough* (K8s docs imply that all init containers *must* be re-run on Pod restart).

**Comment by chengjoey** [comment]
> ```shell
> # simulate a node/sandbox-level disruption by killing pod's slice (probably a better way to do this..?)
> # run next command on **node host**:
> sudo systemctl stop --force \
>  "$(ps -o cgroup --pid "$(pgrep --full 'pgrepid:PkIOeQU4J6zI')" |
>  sed -ne '2s/.*\(kubepods-besteffort-pod.*\.slice\).*/\1/p')"
> ```

`crictl pods` to get pod id and then `crictl stopp ${pod id}`

hi @mike-capyh , I would like to say that this is just a restart count error in the status, but in fact the second init container also restarts. You can increase the date command to display the time to verify.

```
- command:
        - /bin/bash
        - -c
        - "echo 'init-container: Second!' && date"
        image: debian:stable
        imagePullPolicy: IfNotPresent
        name: init-second
```
