### ISSUE TITLE
The repository 'https://pkgs.k8s.io kubernetes-xenial InRelease' is not signed

### ISSUE THREAD

**Issue by xqi-nr** [kubernetes/kubernetes#124089]
### What happened?

I am trying to update the old apt repo to the new apt repo (pkgs.k8s.io) in my Ansible workflow

```
- name: Download k8s apt repo key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.25/deb/Release.key
    dest: /tmp

- name: Add a key from a file
  ansible.builtin.apt_key:
    file: /tmp/Release.key
    state: present

...

- name: Download k8s source list file
  shell:
    cmd: echo "deb [signed-by=/tmp/Release.key] https://pkgs.k8s.io/core:/stable:/v1.25/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

...

- name: Add the Kubernetes repo
  apt_repository:
    repo: "deb https://pkgs.k8s.io/ kubernetes-xenial main"
    update_cache: True
    state: present
    mode: 0644
    filename: kubernetes
```

I got the following error (I redact my IP)

```
fatal: [default]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:Failed to fetch https://pkgs.k8s.io/dists/kubernetes-xenial/InRelease  403  Forbidden [IP: XXX.XXX.XXX.XXX 443], E:The repository 'https://pkgs.k8s.io/ kubernetes-xenial InRelease' is not signed."}
```

### What did you expect to happen?

The `update apt cache` passes.

### How can we reproduce it (as minimally and precisely as possible)?

Follow the Ansible actions I mention above in the description.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
