### ISSUE TITLE
DRA: structured parameters: management containers

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#124041]
### What would you like to be added?

Management containers are contains that get access to some hardware while it is in use by some workload.

In terms of the "named resources" structured model that means that the resource instance is not considered "allocated" when a claim for such a management container uses it.

/cc @johnbelamaric @klueska 
/sig node
/triage accepted
/priority important-longterm

We would like to support this in Kubernetes 1.31, but can proceed without it.

### Why is this needed?

Mostly monitoring.

**Comment by pohly** [comment]
Allowing management access to in-use resources is (potentially) a privileged operation. I can see two ways to achieve this:

We add a "management" boolean flag to a resource class. That flag applies to all claims using it. We then use the [pending quota PR](https://github.com/kubernetes/kubernetes/issues/114916) to limit access to this class to specific namespaces. When quota is exceeded (i.e. access is disabled), creating claims is prevented.

We add a "management" boolean flag to ResourceClaimParameters. Then a single class can be used for normal claims and management. To limit usage of that flag, we need a quota mechanism that considers resource claim parameters. This implies that this needs to be implemented as part of allocation during scheduling.

**Comment by klueska** [comment]
We support this currently (with opaque paramters) in the https://github.com/NVIDIA/k8s-dra-driver using a namespace annotation. Only namespaces that have this annotation are allowed to request resources in this way (using a dedicated field in our standard GpuClaimParamters object). This only works, however, because our custom controller is able to enforce this (which is not possible in the new structured parameters way of doing things).

For structured parameters, I don't necessarily have a preference on which of the two approaches you mention are followed, so long as the cluster admin is still able to pick-and-choose which namespaces are allowed to request resources in this way.

**Comment by pohly** [comment]
This is implemented in https://github.com/kubernetes/kubernetes/pull/125488 with access control of the feature via validating admission policy. From Slack:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: resourceclaim-policy.dra.example.com
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["resource.k8s.io"]
      apiVersions: ["v1alpha3"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["resourceclaims"]
  validations:
    - expression: '! object.spec.requests.exists(e, has(e.device) && has(e.device.adminAccess) && e.device.adminAccess)'
      reason: Forbidden
      message: 'admin access to devices not enabled'
      messageExpression: '"admin access to devices not enabled in namespace " + object.metadata.namespace'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: resourceclaim-binding.dra.example.com
spec:
  policyName:  resourceclaim-policy.dra.example.com
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: admin-access
        operator: DoesNotExist
```
