### ISSUE TITLE
exec probe should kill timeout process

### ISSUE THREAD

**Issue by zxh326** [kubernetes/kubernetes#124226]
### What happened?

The process of exec probe may enter the `S` state due to some reasons. If it still does not end after the timeout period, the process will not exit, and more and more processes will accumulate, resulting in consuming a large amount of resources.

### What did you expect to happen?

kill timeout process

### How can we reproduce it (as minimally and precisely as possible)?

Make a probe that doesn't quit like this

```yaml
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - sleep 10000
          # It's just a simulation of processes that don't exit, the reality can be a bit more complicated
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
```

### Anything else we need to know?

Notice this warning in the [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes)

But why don't we kill this process by kubelet after timeout? What is the reason for keeping it?

> Caution: Incorrect implementation of readiness probes may result in an ever growing number of processes in the container, and resource starvation if this is left unchecked.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.3
Server Version: v1.28.0
```

</details>

### Cloud provider

<details>
Host
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux k8s-01 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>
kubelet

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
