### ISSUE TITLE
Mounted volume size in pod is smaller than size declared in PVC.

### ISSUE THREAD

**Issue by PrasanaaV** [kubernetes/kubernetes#124230]
### What happened?

Hello,

Mounted volume size in pod is smaller than size declared in PVC.
I don't know if this is the usual behavior or it is a bug.

Thanks for your help

### What did you expect to happen?

I expect when I exec it the container and I hit the command df -h to see 20Gi for the path /mypath/ but I only see 4Gi.

### How can we reproduce it (as minimally and precisely as possible)?

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ex1
  namespace: ns1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-s3fs-standard-perf-regional
  volumeMode: Filesystem
```
---
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: ns01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumeMode:
      - name: vol
        PersistentVolumeClaim:
          claimName: ex1
      containers:
      #
      #
        volumeMounts:
          - mountPath: /mypath/
            name: vol
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version : 1.11
Server Version : 1.26
</details>

### Cloud provider

<details>
IBM Cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
Ubuntu 20
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
