### ISSUE TITLE
Deployment does not apply multiplexed ports correctly to my Pods

### ISSUE THREAD

**Issue by sym-stiller** [kubernetes/kubernetes#124233]
### What happened?

I'm running a DNS server (dnsmasq) Deployment, which is exposed to the internet via a Traefik Reverse Proxy. The DNS protocol requires me to multiplex different protocols on the same port, as DNS queries can come in with either TCP or UDP protocol.

On both the dnsmasq and the Traefik deployments, I've run into the issue that the K8s API "swallows" one of the muliplexed ports, effectively rendering the DNS server useless (as either TCP or UDP traffic can't reach the Pod). 

To make it short: 
When I apply this port configuration to a container:
```
ports:
  - containerPort: 1053
    name: udp
    protocol: UDP
  - containerPort: 1053
    name: tcp
    protocol: TCP
```

only one of both ports is actually applied (and it seems to be random which of those ports is applied).

**The issue is not reproducible 100% of the time! In my short study, it occured about every 5th time I tried. The exact conditions that must be met to reproduce this issue are unknown to me.**

My current workaround is to manually add the missing port by editing the Deployment with kubectl/ArgoCD after it was initially applied. This has consistently resolved the issue, but is not a viable long-term solution for me.

### What did you expect to happen?

I expected that both protocols are usable on the same port after the first `kubectl apply`.

### How can we reproduce it (as minimally and precisely as possible)?

Keep in mind that this issue is occuring randomly, and you might need to try a few times until you are able to reproduce it.
You can reproduce the issue by `kubectl apply`ing this Deployment manifest:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplexed-port
  namespace: multiplexed-port
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiplexed-port
  template:
    metadata:
      labels:
        app: multiplexed-port
    spec:
      containers:
        - name: multiplexed-port
          image: busybox:latest
          command: ["sh", "-c", "echo 'Hello, World!' && sleep infinity"]
          ports:
            - containerPort: 1053
              name: udp
              protocol: UDP
            - containerPort: 1053
              name: tcp
              protocol: TCP
```
After the manifest was applied to the cluster, run `kubectl describe` to see that only one of both ports was applied.

I did not test the issue with a naked Pod or other pod controllers like `DaemonSet` or `StatefulSet`.

### Anything else we need to know?

I'm using ArgoCD (currently v2.9.6) to manage my Deployments. When one of the multiplexed ports is not correctly applied, ArgoCD does *not* show an OutOfSync status for my Deployment, indicating that the K8s API does not work correctly here.
The `kubectl.kubernetes.io/last-applied-configuration` annotation also shows both ports have been applied, while only one is displayed when I run `kubectl describe`.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.9
WARNING: version difference between client (1.29) and server (1.27) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
We're using an AKS cluster with AzureLinux.
</details>

### OS version

<details>

I'm using MacOS Sonoma (14.4).
The cluster is always running on the latest version of AzureLinux.

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
