### ISSUE TITLE
kubeadm uses and configures kube-log-runner

### ISSUE THREAD

**Issue by system51** [kubernetes/kubernetes#124359]
### What happened?

klog command line flags [are deprecated](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components) starting with Kubernetes v1.23 and removed in Kubernetes v1.26，I hope to use kube-log-runner to configure log output to a specified file，I deploy using kubeadm

### What did you expect to happen?

I deploy using kubeadm，I hope to use kube-log-runner to configure log output to a specified file。How should I edit the kube-apiserver.yaml file

/apps/k8s/bin/kube-log-runner -log-file=/apps/k8s/log/kube-apiserver.log --also-stdout=false /apps/k8s/bin/kube-apiserver $KUBE_APISERVER_OPTS

### How can we reproduce it (as minimally and precisely as possible)?

Deploy kubernetes using kubeadm

### Kubernetes version

```
kubeadm version: &version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.2", GitCommit:"4b8e819355d791d96b7e9d9efe4cbafae2311c88", GitTreeState:"clean", BuildDate:"2024-02-14T10:39:04Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud provider

<details>
nothing
</details>

### OS version

```
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
```

```
[root@k8s-master-01 manifests]# uname -rn
k8s-master-01 6.7.6-1.el8.elrepo.x86_64
```

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by system51** [comment]
I have found the solution, but I have a question why kube-log-runner cannot be integrated into kubernetes component services, such as kube-apiserver, kube-controller-manager, etc.

```
spec:
  containers:
  - command:
    - /apps/kube-log-runner
    - --log-file=/apps/k8s/log/kube-apiserver.log
    - --also-stdout=false
    - kube-apiserver
    - --advertise-address=10.168.137.26
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
……
```


```
    volumeMounts:
    - mountPath: /apps/kube-log-runner
      name: kube-log-runner
    - mountPath: /apps/k8s/log
      name: k8s-logs
```



```
  volumes:
  - hostPath:
      path: /root/kube-log-runner
      type: File
    name: kube-log-runner
  - hostPath:
      path: /var/log/kubernetes/kube-apiserver
      type: DirectoryOrCreate
    name: k8s-logs
```

**Comment by mengjiao-liu** [comment]
> but I have a question why not integrate kube-log-runner into the kubernetes base image

In fact, the k8s base image already integrates the kube-log-runner binary. 

> The Kubernetes [registry.k8s.io/build-image/go-runner](https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/us/build-image/go-runner) image wraps the gcr.io/distroless/static image and provides kube-log-runner under its traditional name as /go-runner. It gets maintained in https://github.com/kubernetes/release/tree/master/images/build/go-runner.

see details for https://github.com/kubernetes/component-base/tree/master/logs/kube-log-runner#container-base-image

Maybe @pohly @dims know more context?


@system51 You can use the go-runner command directly without having to mount it:

Here is the manifest:
```
spec:
  containers:
  - command:
    - /go-runner
    - --log-file=/var/log/kube-apiserver.log
    - --also-stdout=false
    - --redirect-stderr=true
    - kube-apiserver
    - --advertise-address=10.6.9.1
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
```
```
    - mountPath: /var/log/kube-apiserver.log
      name: logfile
      readOnly: false
```
```
  volumes:
  - hostPath:
      path: /var/log/kube-apiserver.log
      type: FileOrCreate
    name: logfile
```
