### ISSUE TITLE
Repeated Pod creation and eviction during DaemonSet rolling update(surge > 1) when Node is under pressure

### ISSUE THREAD

**Issue by sujoshua** [kubernetes/kubernetes#124388]
### What happened?

When the update strategy for a DaemonSet in Kubernetes is set to RollingUpdate and `maxSurge` is greater than 1, I've noticed an issue where, if a Node's status is under pressure, the system repeatedly creates and then evicts Pods. This behavior creates a lot of unnecessary churn and could potentially cause problems with system resources. 

### What did you expect to happen?

like the behavior when option `maxSurge` is 0

### How can we reproduce it (as minimally and precisely as possible)?

produce a diskpressure, and then deploy this
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
  updateStrategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
```

### Anything else we need to know?

Actually, I've found the problem.

When `maxSurge == 1`, these [codes](https://github.com/kubernetes/kubernetes/blob/c4bce63d9886e5f1fc00f8c3b5a13ea0d2bdf772/pkg/controller/daemon/daemon_controller.go#L799-L820) work perfectly. Because we run into [this](https://github.com/kubernetes/kubernetes/blob/c4bce63d9886e5f1fc00f8c3b5a13ea0d2bdf772/pkg/controller/daemon/daemon_controller.go#L832-L844) and then directly return.

But when `maxSurge > 1`, it passes that, and run into [this](https://github.com/kubernetes/kubernetes/blob/c4bce63d9886e5f1fc00f8c3b5a13ea0d2bdf772/pkg/controller/daemon/daemon_controller.go#L846-L853). Badly, it causes node be added to `nodesNeedingDaemonPods`.

Maybe if we are `inBackoff`, we should break directly ?

### Kubernetes version

main

### Cloud provider

no

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
