### ISSUE TITLE
PersistentVolumeLabel admission blocks PVs on Azure + vSphere

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#124504]
### What happened?

In 1.30, the PersistentVolumeLabel admission plugin blocks creation of in-tree AzureDisk and vSphere PVs:

```
persistentvolumes "pvc-2d9b3999-f60d-4797-923f-210f1f75025d" is forbidden:
error querying AzureDisk volume pvc-2d9b3999-f60d-4797-923f-210f1f75025d:
unable to build Azure cloud provider for AzureDisk
```

The reason is that the cloud provider was removed (https://github.com/kubernetes/kubernetes/pull/122857), but the admission plugin still calls GetCloudProvider there, which fails: https://github.com/kubernetes/kubernetes/blob/646fbe6d0a3fa1a100d90a429f039324de9c8138/plugin/pkg/admission/storage/persistentvolume/label/admission.go#L285

### What did you expect to happen?

The PV should be admitted + created.

### How can we reproduce it (as minimally and precisely as possible)?

Enable PersistentVolumeLabel admission plugin. For example, when running local-up-cluster.sh:
```
ALLOW_PRIVILEGED=true ENABLE_ADMISSION_PLUGINS="NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,Priority,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,PersistentVolumeLabel" bash -x hack/local-up-cluster.sh
```

Create AzureDisk PV on _any_ 1.30 cluster, you don't need Azure cloud:

```
kubectl create -f <<EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvol
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  azureDisk:
    diskName: test2.vhd
    diskURI: https://someacount.blob.core.windows.net/vhds/test2.vhd
EOF
```

### Anything else we need to know?

/sig storage
/priority important-soon

### Kubernetes version

<details>

Today's master
```console
$ kubectl version
Server Version: v1.31.0-alpha.0.24+9791f0d1f39f3f
```

</details>

### Cloud provider

<details>
Azure
</details>

### Install tools

<details>
local-up-cluster.sh
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
