### ISSUE TITLE
Support `env` variables in values from `envFrom`

### ISSUE THREAD

**Issue by lesaux** [kubernetes/kubernetes#124756]
### What would you like to be added?

Currently if I define environment variables on container in the following way:
```
env:
  - name: SOME_VAR
     value: SOME_VALUE
  - name: SOME_OTHER_VAR
     value: SOME_OTHER_VALUE-$(SOME_VALUE)
envFrom:
  - secretRef:
      name: some-secret
```
When one of the values in the secret being set to $(SOME_VAR), that value doesn't get replaced.

SOME_OTHER_VAR gets replaced properly, but the envFrom, wether its a configmap or secret doesn't get replaced.

### Why is this needed?

It would be quite nice to simplify very long manifests by removing most `env:` stanzas in favor of `envFrom:`
