### ISSUE TITLE
Bug: securityContext appArmorProfile unconfined not working with containerd

### ISSUE THREAD

**Issue by jbmolle** [kubernetes/kubernetes#125069]
### What happened?

If I define the podSecurityContext with appArmorProfile unconfined, containerd does not take it into account and use the default cri-containerd.apparmor.d profile.
I don't have the problem if I use the deprecated annotations.

### What did you expect to happen?

The securityContext should give the same result as the annotations. According to #123811 containerd uses both methods.

### How can we reproduce it (as minimally and precisely as possible)?

This deployment works with annotations:
```
apiVersion: apps/v1                                                                                                                                          
kind: Deployment                                                                                                                                             
metadata:                                                                                                                                                    
  name: test                                                                                                                                                 
  namespace: test                                                                                                                                            
spec:                                                                                                                                                        
  selector:                                                                                                                                                  
    matchLabels:                                                                                                                                             
      mytest: test
  template:
    metadata:
      labels:
        mytest: test
      annotations:
        container.apparmor.security.beta.kubernetes.io/mount-cgroup: unconfined
    spec:
      initContainers:
      - name: mount-cgroup
        image: quay.io/cilium/cilium:v1.15.4
        env:
        - name: CGROUP_ROOT
          value: /run/cilium/cgroupv2
        - name: BIN_PATH
          value: /opt/cni/bin
        securityContext:
          appArmorProfile:
            type: Unconfined
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_CHROOT
            - SYS_PTRACE
            drop:
            - ALL
          seLinuxOptions:
            level: s0
            type: spc_t
        command:
        - sh
        - -ec
        - ls -la /hostproc/1/ns/cgroup
        volumeMounts:
        - name: hostproc
          mountPath: /hostproc
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        - "300"
        securityContext:
          appArmorProfile:
            type: Unconfined
      volumes:
      - name: hostproc
        hostPath:
          path: /proc
          type: Directory
```
But this one doesn't.
```
apiVersion: apps/v1                                                                                                                                          
kind: Deployment                                                                                                                                             
metadata:                                                                                                                                                    
  name: test                                                                                                                                                 
  namespace: test                                                                                                                                            
spec:                                                                                                                                                        
  selector:                                                                                                                                                  
    matchLabels:                                                                                                                                             
      mytest: test
  template:
    metadata:
      labels:
        mytest: test
    spec:
      initContainers:
      - name: mount-cgroup
        image: quay.io/cilium/cilium:v1.15.4
        env:
        - name: CGROUP_ROOT
          value: /run/cilium/cgroupv2
        - name: BIN_PATH
          value: /opt/cni/bin
        securityContext:
          appArmorProfile:
            type: Unconfined
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_CHROOT
            - SYS_PTRACE
            drop:
            - ALL
          seLinuxOptions:
            level: s0
            type: spc_t
        command:
        - sh
        - -ec
        - ls -la /hostproc/1/ns/cgroup
        volumeMounts:
        - name: hostproc
          mountPath: /hostproc
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        - "300"
        securityContext:
          appArmorProfile:
            type: Unconfined
      volumes:
      - name: hostproc
        hostPath:
          path: /proc
          type: Directory
```
dmesg on the node where the container is launched gives:
`type=1400 audit(1716404572.354:231): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=1852196 comm="ls" requested_mask="read" denied_mask="read" peer="unconfined"`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1
```

</details>

### Cloud provider

<details>
Bare Metal K8s on Ubuntu 22.04 servers
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
# Linux k8s-master-01 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.7.17
RuntimeApiVersion:  v1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
cilium-cli: v0.16.7 compiled with go1.22.2 on linux/amd64
cilium image (default): v1.15.4
cilium image (stable): v1.15.5
cilium image (running): 1.15.4
</details>

**Comment by neolit123** [comment]
/sig node
https://github.com/search?q=repo%3Akubernetes%2Fenhancements%20appArmorProfile&type=code

**Comment by haircommander** [comment]
/cc @tallclair 
/triage needs-information 

I think this is an issue with containerd, your version may not be new enough to take the new field into account. We may need a containerd dev to take a look

**Comment by jbmolle** [comment]
I'm using conatinerd 1.7.17 which is the last stable release from 2 weeks ago. So it would mean that the feature is still experimental in containerd?

**Comment by haircommander** [comment]
yeah I would guess so. @mikebrow do you know?

**Comment by tallclair** [comment]
hmm, the 2 deployments you shared should yield identical pods after the API synchronizes the annotation & field. Can you confirm that the resulting pods from each have both the field & annotations set (to unconfined)?

Also, are your nodes running v1.30?

**Comment by tallclair** [comment]
> /cc @tallclair /triage needs-information
> 
> I think this is an issue with containerd, your version may not be new enough to take the new field into account. We may need a containerd dev to take a look

Kubelet sets both the new and old version of the apparmor profile in the CRI, so it shouldn't matter
https://github.com/kubernetes/kubernetes/blob/6911225c3f747e1cd9d109c305436d08b668f086/pkg/kubelet/kuberuntime/security_context.go#L44-L45

**Comment by jbmolle** [comment]
Yes my nodes are running v1.30.1.
I've checked the 2 containers on the node with crictl inspect and the result is not exactly the same.
I've attached the 2 files.
[inspection.not-working.json](https://github.com/user-attachments/files/15747448/inspection.not-working.json)
[inspection.working.json](https://github.com/user-attachments/files/15747449/inspection.working.json)

Line 254 in the working container (the one defined with annotations), we have the json fields info.config.linux.security_context.apparmor and info.config.linux.security_context.apparmor_profile. Those fields are not present in the container with appArmorProfile k8s flag.

Line 307 in the not working container we have the field info.runtimeSpec.process.apparmorProfile: cri-containerd.apparmor.d which is not present in the working container

I've actually noticed the problem when I've updated Cilium from v1.15.4 to v1.15.5 because they added the appArmorProfile type Unconfined flag and they removed the annotations. In v1.15.5 my cilium pods were not starting anymore.

**Comment by jbmolle** [comment]
Also in the file kubernetes/pkg/kubelet/kuberuntime/security_context.go you mentioned I'm not sure that synthesized ever has an AppArmor or AppArmorProfile variable.
We have the following:
```
effectiveSc := securitycontext.DetermineEffectiveSecurityContext(pod, container)
synthesized := convertToRuntimeSecurityContext(effectiveSc)
```

`convertToRuntimeSecurityContext` does not mention AppArmor at all.
`DetermineEffectiveSecurityContext` is defined in kubernetes/pkg/security_context/util.go line 40. And there because our pod securitycontext field is not nil then effectiveSc won't be nil. We will add to it SELinuxOptions, WindowsOptions, Capabilities, Privileged, RunAsUser, RunAsGroup, RunAsNonRoot, ReadOnlyRootFilesystem, AllowPrivilegeEscalation and ProcMount but no AppArmorProfile.

I'm not a Go developer so I may have missed something in the code but it seems to me that the AppArmorProfile field is not added to effectiveSc and therefore to synthesized.

**Comment by jbmolle** [comment]
I'm running the 2 following  pods:
Pod A
```
apiVersion: v1                                                                                                                                          
kind: Pod                                                                                                                                             
metadata:
  namespace: test
  name: test
  annotations:
    container.apparmor.security.beta.kubernetes.io/busybox: unconfined
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "300"
```
and Pod B
```
apiVersion: v1                                                                                                                                          
kind: Pod                                                                                                                                             
metadata:
  namespace: test
  name: test
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "300"
    securityContext:
      appArmorProfile:
        type: Unconfined
```
And then I'm running `kubectl apply -f yaml_file_for_pod.yaml -oyaml --dry-run=server`
For Pod A which is working, I get the securityContext:
```
apiVersion: v1                                                                                                                                                                                
kind: Pod                                                                                                                                                                                     
metadata:                                                                                                                                                                                     
  annotations:                                                                                                                                                                                
    container.apparmor.security.beta.kubernetes.io/busybox: unconfined                                                                                                                        
    kubectl.kubernetes.io/last-applied-configuration: |                                                                                                                                       
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"container.apparmor.security.beta.kubernetes.io/busybox":"unconfined"},"name":"test","namespace":"test"},"spec":{"containers"
:[{"command":["sleep","300"],"image":"busybox","name":"busybox"}]}}                                                                                                                           
  creationTimestamp: "2024-06-10T10:59:43Z"                                                                                                                                                   
  name: test                                                                                                                                                                                  
  namespace: test                                                                                                                                                                             
  uid: 592deaea-11c3-459a-84e1-a0c3bb578708                                                                                                                                                   
spec:                                                                                                                                                                                         
  containers:                                                                                                                                                                                 
  - command:                                                                                                                                                                                  
    - sleep                                                                                                                                                                                   
    - "300"                                                                                                                                                                                   
    image: busybox                                                                                                                                                                            
    imagePullPolicy: Always                                                                                                                                                                   
    name: busybox                                                                                                                                                                             
    resources: {}                                                                                                                                                                             
    securityContext:                                                                                                                                                                          
      appArmorProfile:                                                                                                                                                                        
        type: Unconfined                                                                                                                                                                      
    terminationMessagePath: /dev/termination-log                                                                                                                                              
    terminationMessagePolicy: File                                                                                                                                                            
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vcl4z
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-vcl4z
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  phase: Pending
  qosClass: BestEffort
```
And for Pod B
```
apiVersion: v1                                                                                                                                                                                
kind: Pod                                                                                                                                                                                     
metadata:                                                                                                                                                                                     
  annotations:                                                                                                                                                                                
    kubectl.kubernetes.io/last-applied-configuration: |                                                                                                                                       
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"test","namespace":"test"},"spec":{"containers":[{"command":["sleep","300"],"image":"busybox","name":"busybox","secu
rityContext":{"appArmorProfile":{"type":"Unconfined"}}}]}}                                                                                                                                    
  creationTimestamp: "2024-06-10T11:00:58Z"                                                                                                                                                   
  name: test                                                                                                                                                                                  
  namespace: test                                                                                                                                                                             
  uid: 7e95490b-de34-4242-bc0e-c8c4c272a187                                                                                                                                                   
spec:                                                                                                                                                                                         
  containers:                                                                                                                                                                                 
  - command:                                                                                                                                                                                  
    - sleep                                                                                                                                                                                   
    - "300"                                                                                                                                                                                   
    image: busybox                                                                                                                                                                            
    imagePullPolicy: Always                                                                                                                                                                   
    name: busybox                                                                                                                                                                             
    resources: {}                                                                                                                                                                             
    securityContext: {}                                                                                                                                                                       
    terminationMessagePath: /dev/termination-log                                                                                                                                              
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vghxr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-vghxr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  phase: Pending
  qosClass: BestEffort
```
So the problem must come from func getProfile line 56 in kubernetes/pkg/security/apparmor/helpers.go
I've run the tests from helpers_test.go and they work.
I've also tried to enable explicitly the feature gates AppArmor and AppArmorFields but I've still the same error (which is normal because they are enabled per default anyway).
