### ISSUE TITLE
Container dependencies & volumes-from support within Pod

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#12526]
I'd like to propose one use case and two issues, which I think are a little different from https://github.com/GoogleCloudPlatform/kubernetes/issues/831. 
#### use case: a java dev workflow

```
java code ---> git repo ---> app docker image (a war, nothing more)---> registry

Web server docker image (a standard tomcat image) ---> registry
```

Deploy:

A pod.yaml with two containers,:

```
apiVersion: v1beta3
kind: Pod
metadata:
  name: app
spec:
  containers:
  - image: tomcat:latest
    name: tomcat
    volumeMounts:
    - mountPath: /home
      name: test-volume
  - image: app:latest
    name: war
    command: ["sh", "-c", "cp /app/myapp.war /work"]
    volumeMounts:
    - mountPath: /work
      name: test-volume
  volumes:
  - name: test-volume
  restartPolicy: OnFailure # have to, but I really want to set Always for `tomcat` and onFailture for `war`
```

It works OK, tomcat can load war from /work dir, but the **only concern** is that we need to make tomcat container starts after app finish `cp`.                    

So, this is about two issues:
#### **container dependency**

There're many other cases users want to guarantee container A starts before B in a Pod. See #1996.

_Why not git volume?_ Nobody stores everything in a git repo, and the file may also be generated by B.
_Why not other type of distributed fs volume?_ We don't want to maintain NFS server or other kinds, because we don't want to maintain folders and directories with unique names in case of conflicts.

Two dependency types:
**Soft**: just create & start the containers defined in Pod one by one, the order is just the same as it is in listed pod.yaml
**Hard**: B will wait until A 's state become `OK` ( It's a signal defined by user, like RUNNING, better work with container handler)

Definitely, we can also integrate them into one rule: start by order, and start the next when meeting a handler defined rule.

We should implement Soft order at least (`map` in golang is not order promised I believe), for the use case above, it's enough.
#### **volumes-from**

Yes, this feature will make things much easier, we don't need use `empty_dir` anymore. A and B should always be in the same Pod, and that's also volumes-from want to see.

We also need to make sure the order of containers, which can be exactly the same as  **container dependency** part says.

We can use `Empty_dir` to imitate volumes-from, see https://github.com/kubernetes/kubernetes/issues/12526#issuecomment-130540796
#### In one word

Instead of container type volume, I think the native `volumes-from` of docker is much better. It will solve a tricky problem for all:

"Should I package my war in the image or use it as a volume?"

That's where Pod can play better!

**Comment by resouer** [comment]
[Update] On the other hand, we can set a copyData flag for container, so when mounted with a empty_dir, it will Copy whatever is in the container at the mntToPath to the volume (and neglect the potential  conflicts).

The we don't need dependency and volumes-from any more.

**Comment by thockin** [comment]
The volumes-from idea was what I meant when I originally filed #831.  It's
a little complicated because ordering dependencies may not be something we
want to solve generically.  There are a number of ways this can be used,
and I think that is the main reason we haven't done it yet - scoping the
various solutions, analyzing trade-offs, and a deciding what we are and
are-not supporting.

I think it's a fun project, but nobody has taken it on just yet.  I'm happy
to advise if someone wants to own development.

@saad-ali

**Comment by bgrant0607** [comment]
We definitely would like to avoid supporting generic dependencies. The semantics would be very tricky, such as in the cases of retry-able failures of the producer container, restart after failure of consuming containers, updates that add containers or dependencies, etc. OTOH, support for some kind of "setup" containers can have straightforward behavior defined.

**Comment by resouer** [comment]
@thockin So what about the `copyTo` idea mentioned here https://github.com/kubernetes/kubernetes/issues/12526#issuecomment-130540796.

We can try to keep the content in volume, and then we don't need volume-from.

**Comment by thockin** [comment]
Can you be more precise on the specification of how you think it would act?
 who is responsible for copying data?  The whole volume image or just
VOLUME dirs?  How does it know where to copy the data?

I am reluctant to do half-measures but if the spec can be clearly defined,
maybe.

**Comment by dalanlan** [comment]
I have good reasons to believe it could cause something like race condition w/o polling. 
OTOH I cannot see why flag `copyData` matters if we take polling into consideration.

**Comment by resouer** [comment]
@thockin That's because I think we can use `Empty_dir` to imitate `volumes-from` within a Pod, instead of redefine a new volume type.

The reason we can not achieve this currently, is that when mounted a `Empty_dir`, the original files in the mount point inside container A will be hided.

But, if we can add a `copyData` flag to container A, and use kubelet copy all the original files in A's mount point to the `Empty_dir` path before bind mounting.

Then, when container B in the same Pod mounted the `Empty_dir`, he will see the files from container A. Just like  B `volumes-from` A.

The only tricky is dependency as I mentioned. kubelet should create containers with `copyData` flag first. 

I think this can cover most use cases in #831.

**Comment by dalanlan** [comment]
>The reason we can not achieve this currently, is that when mounted a Empty_dir, the original files in the mount point inside container A will be hided.

I'm sorry but are you sure? I'll bet #12588 is able to use emptyDir to get this work.

**Comment by resouer** [comment]
@dalanlan Nope.

Check the `pod.yaml` I posted at the very beginning:  you always need to explicitly `cp file` to dir, and you can also find #12588 also did that. 

That's why I want `volumes-from` style:
```
docker run -v /file --name A
docker run --volumes-from A --name =B
```
See, no `cp` at all, but B can consume `/file` now.

And in Pod, I expect:
```
apiVersion: v1beta3
kind: Pod
metadata:
  name: app
spec:
  containers:
  - image: tomcat:latest
    name: tomcat
    volumeMounts:
    - mountPath: /home
      name: test-volume
  - image: app:latest
    name: war
    volumeMounts:
    - mountPath: /myapp.war
      copyData: true
      name: test-volume
  volumes:
  - name: test-volume
```

Again, no `cp`, but tomcat can consume `/myapp.war` in `/home`.


Why no `cp` is important?
1. you cannot do `cp` in Dockerfile, because volume dir is not ready when building the image
2. you cannot run `cp` in pod.yaml, as k8s does not support one-off task, so you need monkey patch to make the pod alive, see what I did in the first example.

Other work around like init scripts, handler may also work,  but `volumes-from` style file sharing is straightforward , which I propose to be implemented with Empty_dir + copyData easily. cc @thockin

**Comment by thockin** [comment]
@mikedanese Why do you think #14094 closes this?

**Comment by mikedanese** [comment]
PR description says "Close: #12526" so when I merged, github closes the issue automatically. I merged it because it was e2e-not-required, and lgtm'd. I only skimmed the content.

**Comment by resouer** [comment]
@thockin Most of the problems I described in this issue can be fixed by #14094. So I have no problem to close this.

**Comment by resouer** [comment]
@thockin I've been thinking & digging this for a while, so here's some thoughts.

For example, in a Pod, we have `A --volumes-from B`.

The main obstacle here is that we need to implement this without introducing volumes of Docker. Thus, we have to make sure:
1. B starts before A (it already works now when defining B before A in pod yaml && B don't consume long time to start)
2. Preserve the contents in B's mount point.

Generally, I use life-cycle handler to achieve `2`, see: https://gist.github.com/resouer/378bcdaef1d9601ed6aa

But, do you think it is reasonable to keep `1` not changed and implement `2` by introducing a new volume type.

**Comment by resouer** [comment]
In this case, I can see the main tricky point is how to update containers when they have dependency. This is kind of conflict with current implement of kubelet actually. 

OTOH, this dilemma may be solved by some special tricks (hook, sidecar, any type ) , just thinking ...

**Comment by bgrant0607** [comment]
cc @erinboyd

**Comment by yybear** [comment]
hi  @ resouer, if the war file is very big like 6GB, cp will spend too much time, so can use soft link or other method avoids to cp?
docker volumes-from seems better.

**Comment by resouer** [comment]
I think soft link should work

**Comment by resouer** [comment]
@yybear I think soft link should work

**Comment by yybear** [comment]
@resouer i tried get en error--- failed to call event handler: Error executing in Docker Container: -1.

u r chinese?

**Comment by harryge00** [comment]
What about add "timeafter" in poststart? Users can manually set the order of containers in a pod.

**Comment by linsun** [comment]
@yybear have you ever gotten soft link working?  I tried it today, it failed too.

**Comment by yybear** [comment]
@linsun  yeah, soft link is not working

**Comment by surajssd** [comment]
@resouer now this problem can be solved using `init-containers`? Also with `init-containers` we don't need an extra container always running which only copies data around, and the sequence is also maintained as you asked!

And example pod def might look like:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: init
  labels:
    app: init
  annotations:
    pod.alpha.kubernetes.io/init-containers: '[
        {
            "name": "download",
            "image": "axeclbr/git",
            "command": [
                "git",
                "clone",
                "https://github.com/mdn/beginner-html-site-scripted",
                "/var/lib/data"
            ],
            "volumeMounts": [
                {
                    "mountPath": "/var/lib/data",
                    "name": "git"
                }
            ]
        }
    ]'
spec:
  containers:
  - name: run
    image: docker.io/centos/httpd
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /var/www/html
      name: git
  volumes:
  - emptyDir: {}
    name: git
```
