### ISSUE TITLE
readinessProbe not failing if command is not installed

### ISSUE THREAD

**Issue by AlbertoSoutullo** [kubernetes/kubernetes#125339]
### What happened?

I have the following readinessProbe in my .yaml file:
```
readinessProbe:
  exec:
    command:
      - /bin/sh
      - -c
      - >
        curl -s http://127.0.0.1:8008/metrics |
        awk '!/^#/ && /^libp2p_gossipsub_healthy_peers_topics /{
          print "Found gossipsub:", $0;
          if ($2 == 1.0) {
            exit 0;  # success, healthy state
          } else {
            exit 1;  # failure, unhealthy state
          }
        }'
  successThreshold: 5
  initialDelaySeconds: 5
  periodSeconds: 1
  failureThreshold: 2
  timeoutSeconds: 5
```

The pod only has one container, and this container doesn't have `curl` installed. Still, the readinessProbe is making the pod as Ready.

I then manually entered in the container, and installed `curl` by hand. 1 second after that, the POD was marked as not ready.

If I don't manually install `curl`, and I run the same command, I got an error, as curl is not installed.

### What did you expect to happen?

The POD should not be marked as ready.

### How can we reproduce it (as minimally and precisely as possible)?

I edited my yaml to be reproducible and reach to the same issue.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodes
  namespace: zerotesting
spec:
  replicas: 1
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: zerotenkay
  template:
    metadata:
      labels:
        app: zerotenkay
    spec:
      containers:
        - name: test
          image: alpine:3.18
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - >
                  curl -s http://127.0.0.1:8008/metrics |
                  awk 'asd'
            successThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 2
            timeoutSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "600Mi"
              cpu: "400m"
          command:
            - sh
            - -c
            - sleep 99999
```

If I run this, I still can see that the pod is marked as Ready, even curl is not installed.

### Kubernetes version

<details>

```console
$ kubectl version
 v1.28.9+k3s1
```

</details>

### Cloud provider

<details>
Own deployment
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
