### ISSUE TITLE
After the kubelet restarted, the ready state of the pod should not change.

### ISSUE THREAD

**Issue by chenk008** [kubernetes/kubernetes#125397]
### What happened?

A pod with startuoProbe/readinessProbe has been ready, it will be used as backends for Services. After the kubelet restarted, this pod will be marked `not ready`.  An additional startuoProbe needs to be executed.

### What did you expect to happen?

After the kubelet restarted, the ready state of the pod should not change. The ready status should only be false if a probe fails.

### How can we reproduce it (as minimally and precisely as possible)?

1. create a pod with startupProbe 
Pod demo yaml:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: startup
  name: startup-exec
spec:
  containers:
  - name: startup
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy;  sleep infinity
    startupProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - sleep 10; cat /tmp/healthy
      initialDelaySeconds: 6
      timeoutSeconds: 15
      periodSeconds: 60
```

2. wait this pod to be ready
```
    - lastProbeTime: null
      lastTransitionTime: "2024-06-08T07:53:27Z"
      status: "True"
      type: ContainersReady
```
3. restart the kubelet 
```
kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf, 11-kind.conf
     Active: active (running) since Sat 2024-06-08 08:17:09 UTC; 1min 16s ago
```
4. this pod will be not ready. 
```
Jun 08 08:17:55 kind-control-plane kubelet[4644]: I0608 08:17:55.463964    4644 kubelet.go:2527] "SyncLoop (probe)" probe="startup" 
status="unhealthy" pod="default/startup-exec"


    - lastProbeTime: null
      lastTransitionTime: "2024-06-08T08:17:55Z"
      message: 'containers with unready status: [liveness]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
```

5.After an additional startuoProbe, it will be ready again.
```
        - lastProbeTime: null
      lastTransitionTime: "2024-06-08T08:19:05Z"
      status: "True"
      type: ContainersReady
```

### Anything else we need to know?

It also affects readiness probe

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.0", GitCommit:"7c48c2bd72b9bf5c44d21d7338cc7bea77d0ad2a", GitTreeState:"clean", BuildDate:"2024-05-13T22:00:36Z", GoVersion:"go1.22.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
