### ISSUE TITLE
KEP-4639 OCI VolumeSource PoC

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#125463]
This issue is tracking a proof of concept (PoC) implementation for the OCI VolumeSource KEP: https://github.com/kubernetes/enhancements/issues/4639

- **Kubernetes**: https://github.com/kubernetes/kubernetes/compare/master...saschagrunert:oci-volumesource-poc
  - **cri-api**: https://github.com/kubernetes/cri-api/compare/master...saschagrunert:oci-volumesource-poc
  - **cri-client**: https://github.com/kubernetes/cri-client/compare/master...saschagrunert:oci-volumesource-poc
- **CRI-O**: https://github.com/cri-o/cri-o/compare/main...saschagrunert:oci-volumesource-poc
- **cri-tools**: https://github.com/kubernetes-sigs/cri-tools/compare/master...saschagrunert:oci-volumesource-poc

cc @sallyom 

#### CRI only
Prepare an OCI artifact within a local registry.

```bash
# Prepare the structure
mkdir -p dir
echo 1 > dir/file
echo 2 > file
tar cfvz layer.tar dir file

# Create a config for matching the platform
jq --null-input '.architecture = "amd64" | .os = "linux"' > config.json

# Run a local registry
podman run --rm -d -p 5000:5000 --name registry registry:2

# Push the artifact
oras push --config config.json:application/vnd.oci.image.config.v1+json \
    localhost:5000/image:v1 \
    layer.tar:application/vnd.oci.image.layer.v1.tar+gzip
```

Verify the artifact:
```bash
oras manifest fetch localhost:5000/image:v1 | jq .
```

```json
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.manifest.v1+json",
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:4a2128b14c6c3699084cd60f24f80ae2c822f9bd799b24659f9691cbbfccae6b",
    "size": 47
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "digest": "sha256:5763499f5a85effa1a83e886f2cc0f72c7bc8f057bef2e8df95b1b330e3f25d6",
      "size": 181,
      "annotations": {
        "org.opencontainers.image.title": "layer.tar"
      }
    }
  ],
  "annotations": {
    "org.opencontainers.image.created": "2024-06-14T08:32:43Z"
  }
}
```

- Start CRI-O built from: https://github.com/saschagrunert/cri-o/tree/oci-volumesource-poc
- Use `crictl` built from: https://github.com/saschagrunert/cri-tools/tree/oci-volumesource-poc

```console
> sudo ./build/bin/linux/amd64/crictl pull --mount localhost:5000/image:v1

Image is up to date for localhost:5000/image@sha256:0cd52d8d65ebc72cfa8b5f74629a4e0ee1def0d2c33eff0ee90bc193732aae65
Image mounted to: /var/lib/containers/storage/overlay/c58a1595bb4829d7f08bb2521c6d5e379009e0476613f0007131476f157a7385/merged

> sudo tree /var/lib/containers/storage/overlay/c58a1595bb4829d7f08bb2521c6d5e379009e0476613f0007131476f157a7385/merged
/var/lib/containers/storage/overlay/c58a1595bb4829d7f08bb2521c6d5e379009e0476613f0007131476f157a7385/merged
├── dir
│   └── file
└── file

2 directories, 2 files

> sudo cat /var/lib/containers/storage/overlay/c58a1595bb4829d7f08bb2521c6d5e379009e0476613f0007131476f157a7385/merged/dir/file
1

> sudo cat /var/lib/containers/storage/overlay/c58a1595bb4829d7f08bb2521c6d5e379009e0476613f0007131476f157a7385/merged/file
2
```

#### Kubernetes

Use the Kubernetes sources mentioned above by enabling the feature gate `OCIVolume`. When using [`hack/local-up-cluster.sh`](https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh), then:

```bash
export FEATURE_GATES=OCIVolume=true
```

If the cluster is up and running, create an example Pod referencing the pre-pushed artifact [quay.io/saschagrunert/artifact:v1](https://quay.io/repository/saschagrunert/artifact/tag/v1):

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: test
      image: busybox:1.28
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: oci-volume
          mountPath: /volume
  volumes:
    - name: oci-volume
      oci:
        reference: quay.io/saschagrunert/artifact:v1
        # pullPolicy: IfNotPresent
```

```bash
kubectl apply -f pod.yaml
```

```console
> k exec -it pod -- sh -c 'set -x && ls -l /volume && cat /volume/dir/file && cat /volume/file'
+ ls -l /volume
total 8
drwxr-xr-x    2 1000     users         4096 Jun 18 09:02 dir
-rw-r--r--    1 1000     users            2 Jun 18 09:02 file
+ cat /volume/dir/file
1
+ cat /volume/file
2
```

**Comment by asviel** [comment]
Hi everyone. Are there plans to support subPath or (better) projected volumes for OCI VolumeSource? I have multiple (10+) models and would like to be able to mount them in one place:
```
apiVersion: v1
kind: Pod
metadata:
  name: image-volume
spec:
  containers:
    - name: shell
      command: ["sleep", "infinity"]
      image: debian
      volumeMounts:
        - name: models
          mountPath: /models
  volumes:
    - name: models
      projected:
        sources:
          - image:
              reference: quay.io/crio/artifact-1:v1
              pullPolicy: IfNotPresent
          - image:
              reference: quay.io/crio/artifact-2:v1
              pullPolicy: IfNotPresent
```
