### ISSUE TITLE
kubelet unbalanced affinity pod in different numa node

### ISSUE THREAD

**Issue by ryanlyy** [kubernetes/kubernetes#125453]
### What happened?

in current kubelet below algorithm, the pods/containers shall be affinity to different numa node unbalanced. 

for example: if there is 6 pods with integer cpu container configured, most of pods will be scheduled into numa0 if numa0 has enough available cpus (4 pods in numa0 and 2 pod in numa1). 

then if turboboost is enabled with OS control or static max performance, the cpu frequency will be different in callload running. for example cpus in numa0 maybe 2500 but cpus in numa1 maybe 2900 since workload is different in two numa nodes. 

in this environment, even the incoming traffic to those pods which are scheduled in numa0 and numa1 is same (round robin), the cpu usage in those pods are different. that will cause issue which traffic load can not be increased to expected values since 4 pods in numa0 is already with high cpu usage (call maybe starting drop)  but 2 pods in numa1 with low cpu usage.

       // Algorithm: topology-aware best-fit
        // 1. Acquire whole NUMA nodes and sockets, if available and the container
        //    requires at least a NUMA node or socket's-worth of CPUs. If NUMA
        //    Nodes map to 1 or more sockets, pull from NUMA nodes first.
        //    Otherwise pull from sockets first.
        acc.numaOrSocketsFirst.takeFullFirstLevel()
        if acc.isSatisfied() {
                return acc.result, nil
        }
        acc.numaOrSocketsFirst.takeFullSecondLevel()
        if acc.isSatisfied() {
                return acc.result, nil
        }

        // 2. Acquire whole cores, if available and the container requires at least
        //    a core's-worth of CPUs.
        acc.takeFullCores()
        if acc.isSatisfied() {
                return acc.result, nil
        }

        // 3. Acquire single threads, preferring to fill partially-allocated cores
        //    on the same sockets as the whole cores we have already taken in this
        //    allocation.
        acc.takeRemainingCPUs()
        if acc.isSatisfied() {
                return acc.result, nil
        }

### What did you expect to happen?

affinity pod/container balanced to different numa instead of filling numa0 first and then numa1

### How can we reproduce it (as minimally and precisely as possible)?

any env with cpuManagePolicy as static and turboboost enabled with call load

### Kubernetes version

test version is 1.27

### Cloud provider

any cloud provider

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ryanlyy** [comment]
sig/k8s-infra

**Comment by ffromani** [comment]
would the cpumanager policy option `distribute-cpus-across-numa` help here? https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy-options

**Comment by ryanlyy** [comment]
@ffromani thanks a lot. my understanding is distribute-cpus-accors-numa is used to affinity cpu to different numa for one pod/container. for example: if one pod/container needs 16 cpus, w/o distribute-cpus-accross-numa, 16cpus will firstly  be affinity in numa0 and numa1, then it maybe 14cpus in numa0 if there is enough cpus in numa0 and 2 cpus in numa1. w/ distribute-cpus-accorss-numa, 8 cpus are affinity in numa0 although there is enough cpus availabe in numa0 but another 8 cpus are affinity into numa1. then cpus in pod/conainer are distributed in numa0 and numa1.

but this issue described in this ticket is; if there are 8 pods. those 8 pods will be affinity into numa0 firstly if there is enough cpu available in nuam1. then then numa1, that will result in different cpu load in different numa nodes and then different cpu frequency when turboboost enabled.

**Comment by ffromani** [comment]
> but this issue described in this ticket is; if there are 8 pods. those 8 pods will be affinity into numa0 firstly if there is enough cpu available in nuam1. then then numa1, that will result in different cpu load in different numa nodes and then different cpu frequency when turboboost enabled.

right, so the ask is about distributing the pods (containers) across NUMA nodes more evenly it seems. This is indeed not yet covered by options or combinations thereof.

**Comment by ryanlyy** [comment]
> right, so the ask is about distributing the pods (containers) across NUMA nodes more evenly it seems. This is indeed not yet covered by options or combinations thereof.
yes @ffromani . frankly cpuManagePolicyOption/distribute-cpus-accors-numa is conflict with topoloygManagerPolicy/single-numa-node. but single-numa-node can provide more high performance. 

w/o evenly distribute pod/container into different numa, cpu frequency will be different when turboboost enabled and then result in different cpu usage although incoming traffic is same. 
I think evenly distribute pod/container into different numa can overall increase performance.

So will you create a feature to support it?

Thanks a lot

**Comment by ffromani** [comment]
> So will you create a feature to support it?

Unfortunately I don't have capacity atm. But I agree this is a gap (triage accepted)
Addressing this gap will require an enancement proposal, design etc. etc. It's 1.32 material in the best case IMO.

**Comment by ryanlyy** [comment]
> > So will you create a feature to support it?
> 
> Unfortunately I don't have capacity atm. But I agree this is a gap (triage accepted) Addressing this gap will require an enancement proposal, design etc. etc. It's 1.32 material in the best case IMO.

Thanks a lot @ffromani. we agreed it is gap and triage accepted then there will be followup by someone since you have no capacity atm. correct?

**Comment by ffromani** [comment]
> Thanks a lot @ffromani. we agreed it is gap and triage accepted then there will be followup by someone since you have no capacity atm. correct?

Not automatically. Someone has to volunteer pick this work up. If you wish to push forward, by all means do it!

**Comment by pravk03** [comment]
Should this be introduced as an additional static CPU policy option (and disabled by default) ?. The CPU allocation fragmentation could make it harder for future pods to find enough free CPUs on a single node ?

**Comment by pravk03** [comment]
I'd be interested in exploring this. While I'm still getting familiar with this codebase, I've spent some time looking into how we might approach NUMA interleaving. My initial thought is along these lines:

- Introduce a new topology manager policy named `prefer-numa-interleaving` (or a similar, more descriptive name).
- Add a field like `AffineNUMANodeAvailableCPUMask` to the `TopologyHint` struct
https://github.com/kubernetes/kubernetes/blob/195803cde570ad1025a78e36cdbef76bddbc4c33/pkg/kubelet/cm/topologymanager/topology_manager.go#L104 
- When generating topology hints in the CPU manager (specifically within the static CPU policy) we would populate this new field number of cpu's available for reservation on the candidate node/nodes.
https://github.com/kubernetes/kubernetes/blob/195803cde570ad1025a78e36cdbef76bddbc4c33/pkg/kubelet/cm/cpumanager/policy_static.go#L699
- During the hint selection process in the topology manager, we consider the number of CPU's in `AffineNUMANodeAvailableCPUMask` in order to stagger pod/container on different nodes when `prefer-numa-interleaving` is enabled.
https://github.com/kubernetes/kubernetes/blob/195803cde570ad1025a78e36cdbef76bddbc4c33/pkg/kubelet/cm/topologymanager/policy.go#L151

There might be some details I haven't fully grasped yet, but if this general direction seems reasonable, I'd be happy to prepare a pull request to figure out the details and iterate based on feedback.

cc:@ffromani, @swatisehgal

**Comment by ffromani** [comment]
I'm reviewing again the issue and I'm no longer convinced about what's wrong if we use `distribute-cpus-across-numa` cpumanager policy PLUS the `single-numa-node` topology manager policy.  was that approach tried?

**Comment by pravk03** [comment]
> I'm reviewing again the issue and I'm no longer convinced about what's wrong if we use distribute-cpus-across-numa cpumanager policy PLUS the single-numa-node topology manager policy. was that approach tried?

From what I understand, `distribute-cpus-across-numa` option is intended to distribute the CPUs allocated to a single pod/container across multiple NUMA nodes. However the ask here is to have an option to distribute containers/pods themselves more evenly across the available NUMA nodes.

I tried the suggestion made above and here is my observation: 

1.  I set up a kind cluster with a worker node configured with 2 NUMA domains. Each NUMA node has 30 CPUs.

    ```
    docker exec 132-worker lscpu | grep NUMA
    NUMA node(s):                    2
    NUMA node0 CPU(s):               0-14,30-44
    NUMA node1 CPU(s):               15-29,45-59
    ```

2.  I modified the kubelet configuration on the worker node to enable the `single-numa-node` topology manager policy and the `static` CPU manager policy, along with the `distribute-cpus-across-numa` option.

    ```yaml
    topologyManagerPolicy: single-numa-node
    topologyManagerScope: container
    cpuManagerPolicy: static
    reservedSystemCPUs: "0"
    memoryManagerPolicy: Static
    systemReserved:
      memory: "500Mi"
    kubeReserved:
      memory: "500Mi"
    reservedMemory:
      - numaNode: 0
        limits:
          memory: "1000Mi"
    featureGates:
      CPUManagerPolicyOptions: true
      CPUManagerPolicyAlphaOptions: true
    cpuManagerPolicyOptions:
      distribute-cpus-across-numa: "true"
      full-pcpus-only: "true"
    ```

3.  I created two identical Guaranteed QoS pods, each requesting 10 CPUs, and scheduled them to the configured worker node.

    ```yaml
    # Pod 1 Definition
    apiVersion: v1
    kind: Pod
    metadata:
      name: guaranteed-pod-10cpu
    spec:
      nodeName: 132-worker
      containers:
      - name: my-guaranteed-container
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            memory: "512Mi"
            cpu: "10"
          limits:
            memory: "512Mi"
            cpu: "10"

    ---
    # Pod 2 Definition
    apiVersion: v1
    kind: Pod
    metadata:
      name: guaranteed-pod-10cpu-2
    spec:
      nodeName: 132-worker
      containers:
      - name: my-guaranteed-container-2
        image: registry.k8s.io/pause:3.9
        resources:
          requests:
            memory: "512Mi"
            cpu: "10"
          limits:
            memory: "512Mi"
            cpu: "10"
    ```

4.   I examined the `cpu_manager_state` file and observed that the containers from both pods were assigned CPUs from NUMA Node 0.

    ```
    root@132-worker:/# cat /var/lib/kubelet/cpu_manager_state
    {"policyName":"static","defaultCpuSet":"0,11-30,41-59","entries":{"11b213d2-ad10-41ff-83da-226b3428c16f":{"my-guaranteed-container":"1-5,31-35"},"d92effe0-fce0-4551-8ba6-ad5738cb9a75":{"my-guaranteed-container-2":"6-10,36-40"}},"checksum":1271419287}
    ```

    Extracting the CPU allocations from above, both containers are assigned CPUs solely within Node 0 (NUMA node0 CPU range: `0-14,30-44`):

    ```
    my-guaranteed-container   : "1-5,31-35"  (Node 0)
    my-guaranteed-container-2 : "6-10,36-40" (Node 0)
    ```

Sidenote: 
Interestingly, all CPUs for *each* container were allocated from NUMA Node 0, despite `distribute-cpus-across-numa` being enabled. My expectation was that enabling this option would result in each container having its 10 CPUs split across both NUMA nodes (5 CPUs on Node 0 and 5 CPUs on Node 1). I also tried changing the `topologyManagerPolicy` to `restricted`, but the observed behavior remained the same.

I read through the code and I noticed that the CPU Manager policy options (like `distribute-cpus-across-numa`) seem to be considered only during the *Allocation* phase but not during the *Hint generation* phase. If the topology hint generated before admitting the pod indicates affinity to only one NUMA node (Node 0 in this case), the CPU manager, during the subsequent allocation phase would not distribute CPUs across nodes even with the option enabled. Is this the intended behavior ?. If it's not expected, would it be worth creating a separate issue to follow up on this?
