### ISSUE TITLE
kubectl port-forward failing for named ports in native sidecar

### ISSUE THREAD

**Issue by rouke-broersma** [kubernetes/kubernetes#125412]
### What happened?

```
kubectl port-forward svc/adguard-metrics metrics (named port on service)
error: Pod 'adguard-primary-7cc5d498f4-67zs4' does not have a named port 'metrics'

kubectl port-forward adguard-primary-7cc5d498f4-67zs4 metrics (named port on native sidecar)
error: Pod 'adguard-primary-7cc5d498f4-67zs4' does not have a named port 'metrics'
```

### What did you expect to happen?

Since native sidecards support named ports, named ports on native sidecar should be supported in kubectl port-forward.

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod/deployment with a named port. Example:

<details>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app.kubernetes.io/name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      initContainers:
        - name: nginx
          image: nginx
          restartPolicy: Always
          ports:
            - name: metrics
              protocol: TCP
              containerPort: 80
          livenessProbe:
            httpGet:
              port: metrics
              path: /metrics
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: metrics
              path: /metrics
            failureThreshold: 5
            periodSeconds: 10
      containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'echo Hello Kubernetes! && sleep infinity']
```

</details>

Port forward with named port does not work:
```
kubectl port-forward app-<pod-id> 8080:metrics
error: Pod 'app-7c74c5d9db-bzmqb' does not have a named port 'metrics'
```

Port forward with port number works:
`kubectl port-forward app-<pod-id> 8080:80`
```
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080
```

Same deal when port-forwarding through deployment or service:

```
kubectl port-forward deploy/app 8080:metrics
error: Pod 'app-645b84f678-tjh8j' does not have a named port 'metrics'
```

```
kubectl port-forward svc/app 8080:metrics
error: Pod 'app-645b84f678-tjh8j' does not have a named port 'metrics'
```

### Anything else we need to know?

@aojea ping as requested

### Kubernetes version

<details>

```console
kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

</details>

### Cloud provider

<details>
Talos Linux in VMs on ProxMox
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Talos"
ID=talos
VERSION_ID=v1.7.1
PRETTY_NAME="Talos (v1.7.1)"
HOME_URL="https://www.talos.dev/"
BUG_REPORT_URL="https://github.com/siderolabs/talos/issues"
VENDOR_NAME="Sidero Labs"
VENDOR_URL="https://www.siderolabs.com/"
$ uname -a
Linux version 6.6.29-talos (@buildkitsandbox) (gcc (GCC) 13.2.0, GNU ld (GNU Binutils) 2.42) #1 SMP Tue Apr 30 14:19:14 UTC 2024
```

</details>

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI: Cilium v1.15.5
</details>
