### ISSUE TITLE
PodSecurityStandards being enforced provide different log information for Deployments and for pods to the user

### ISSUE THREAD

**Issue by cck1860** [kubernetes/kubernetes#125507]
### What happened?

I set up a namespace as described in the documentation example: 

```
apiVersion: v1
kind: Namespace
metadata:
  name: my-baseline-namespace
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.30

    # We are setting these to our _desired_ `enforce` level.
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.30
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.30
```

When trying to make a request to deploy the following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

I am only getting the warnings restricted specification violation:
```
 kubectl apply -f nginx.yml -n  my-baseline-namespace
Warning: would violate PodSecurity "restricted:v1.30": host namespaces (hostNetwork=true), allowPrivilegeEscalation != false (container "nginx" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "nginx" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "nginx" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "nginx" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

The deployment resource is generated and the pods are not spinned up due to the violation of the baseline standard (because of the hostNetwork:true setting).

I expected to get here also a message that the deployment is not possible due to this violation. -  When I am deploying just a pod with the same configuration:
kubectl apply -f nginx-pod.yml -n  my-baseline-namespace
Error from server (Forbidden): error when creating "nginx-pod.yml": pods "nginx" is forbidden: violates PodSecurity "baseline:v1.30": host namespaces (hostNetwork=true)

I wonder, if deployments should behave in the same way as the pods being configured like shown below:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  hostNetwork: true
  containers:
  - command:
    - sleep
    - 1h
    image: nginx
    name: nginx
```

### What did you expect to happen?

I expected to get the same message for deployment resources like I am getting it for pods for the kubectl output. 

Also when running kubectl describe deployment nginx, there is no further hint regarding to PodSecurityStandards why the pods are not started:
 kubectl describe deployment nginx-deployment  -n  my-baseline-namespace
Name:                   nginx-deployment
Namespace:              my-baseline-namespace
CreationTimestamp:      Fri, 14 Jun 2024 11:31:35 +0200
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=nginx
Replicas:               2 desired | 0 updated | 0 total | 0 available | 2 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=nginx
  Containers:
   nginx:
    Image:         nginx:1.14.2
    Port:          80/TCP
    Host Port:     0/TCP
    Environment:   <none>
    Mounts:        <none>
  Volumes:         <none>
  Node-Selectors:  <none>
  Tolerations:     <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Available        False   MinimumReplicasUnavailable
  ReplicaFailure   True    FailedCreate
  Progressing      False   ProgressDeadlineExceeded
OldReplicaSets:    <none>
NewReplicaSet:     nginx-deployment-7cc7dc59f6 (0/2 replicas created)
Events:            <none>

### How can we reproduce it (as minimally and precisely as possible)?

The yaml files are posted above, I deployed this on a Minikube Kubernetes 1.30.2

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2

```

</details>

### Cloud provider

Not applicable
<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
 cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
# paste output here
  uname -a
Linux svmseadevel 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
 minikube start --kubernetes-version=v1.30.2 --container-runtime=containerd
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd containerd.io 1.6.28 ae07eda36dd25f8a1b98dfbf587313b99c0190bb
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
n.a
</details>

/wg Policy
