### ISSUE TITLE
Better field-ordering when rendering YAML/JSON

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#125525]
Today it looks like fields are all rendered in alphabetical order which makes for terrible reading.  We have a strong convention of list-map fields -- when we render each item, it would be much nicer to put the key(s) first.

Example, compare:

```
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-06-09T22:52:34Z"
      status: "False"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2024-06-09T22:52:32Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-06-09T22:52:32Z"
      reason: PodFailed
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-06-09T22:52:32Z"
      reason: PodFailed
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-06-09T22:52:32Z"
      status: "True"
      type: PodScheduled
```

with

```
    conditions:
    - type: PodReadyToStartContainers
      lastProbeTime: null
      lastTransitionTime: "2024-06-09T22:52:34Z"
      status: "False"
    - type: Initialized
      lastProbeTime: null
      lastTransitionTime: "2024-06-09T22:52:32Z"
      status: "True"
    - type: Ready
      lastProbeTime: null
      lastTransitionTime: "2024-06-09T22:52:32Z"
      reason: PodFailed
      status: "False"
    - type: ContainersReady
      lastProbeTime: null
      lastTransitionTime: "2024-06-09T22:52:32Z"
      reason: PodFailed
      status: "False"
    - type: PodScheduled
      lastProbeTime: null
      lastTransitionTime: "2024-06-09T22:52:32Z"
      status: "True"
```

It would super if we could annotate fields with enough information to get
better ordering.  Perhaps a simple integer, such that lower numbers render
first, and any two fields with the same number arte sorted alphabetically.
