### ISSUE TITLE
Suppress all logs and only see errors. Verbosity=0 does not help

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes/kubernetes#125505]
### What happened?

Setting verbosity to 0 does not disable all logs. 

### What did you expect to happen?

Setting verbosity to the lowest level should only show fatal error messages or there should be some other setting that the user can set to suppress all logs and see only error logs.

### How can we reproduce it (as minimally and precisely as possible)?

Create kind cluster with verbosity of k8s components set to 0.
example config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "0"
    extraArgs:
      kube-apiserver:
        v: "0"
      kube-controller-manager:
        v: "0"
      kube-scheduler:
        v: "0"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "0"
```
Get logs from any of k8s components and you will see info logs.

### Anything else we need to know?

this is needed for optimizing the CPU usage in resource intensive environments.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:38:14Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>
Kind cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
