### ISSUE TITLE
Node Labeling node.kubernetes.io/out-of-service Taint Label Delay

### ISSUE THREAD

**Issue by Black-max12138** [kubernetes/kubernetes#125608]
### What happened?

After the node is powered off, the node.kubernetes.io/out-of-service label is not added in time. Therefore, the pod created by the statefulset is not deleted in time.
 ```
 taints:
  - effect: NoSchedule
    key: node.kubernetes.io/out-of-service
    value: nodeshutdown
  - effect: NoExecute
    key: node.kubernetes.io/out-of-service
    value: nodeshutdown
  - effect: NoSchedule
    key: node.kubernetes.io/unreachable
    timeAdded: "2024-06-20T08:56:43Z"
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    timeAdded: "2024-06-20T08:56:55Z"
```
A node is powered off. At least one pod created by statefulset exists on the node. The pod tolerance is set to 30s. After the node is powered off, the node status changes to notready. The pod is in the terminating state 30s later but is deleted after a long time. The reason is that the node.kubernetes.io/out-of-service taint label is updated late.
So I want to know when the node.kubernetes.io/out-of-service taint tag was added.

### What did you expect to happen?

The pod should be deleted in a timely manner.

### How can we reproduce it (as minimally and precisely as possible)?

Powering Off a Node

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.28
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
