### ISSUE TITLE
NetPol block self pod trafic using an svc and not direct call

### ISSUE THREAD

**Issue by mmohamed** [kubernetes/kubernetes#125611]
### What happened?

Hello,

In case of a pod exposed by an internal service (ClusterIP) and a presence of a network-policy allowing ingress traffic from some namespaces and th pod namespace it self (my-namespace) like :

```yaml
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: my-namespace
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nginx
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: prometheus
  podSelector: {}
  policyTypes:
  - Ingress
```

When the pod call it self using the service IP or service name (DNS), got timeout when the NetPol is presente.

### What did you expect to happen?

From the pod, i can : 

1. Pod can call it self by his IP
2. Pod can call it self by the service IP
3. Pod can call it self by the service FQDN (DNS)

### How can we reproduce it (as minimally and precisely as possible)?

Deploy pod with svc and netpol with ingress filtering. Run from inside the pod, a curl call to the service like :  
`wget http://hello-world.my-namespace.svc.cluster.local`

### Kubernetes version

<details>

```console
$ kubectl version
# v1.25.7
```

</details>

### Cloud provider

<details>
On promise
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNS : Antre v1.9.0
</details>
