### ISSUE TITLE
Kubernetes Job failed status after a graceful termination

### ISSUE THREAD

**Issue by saaguero** [kubernetes/kubernetes#125695]
### What happened?

Let's take the following Kubernetes Cronjob

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleep-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0 # Avoid two executions
      template:
        spec:
          containers:
          - name: sleep
            image: busybox
            command: ["sh", "-c", "sleep 120"] # 2 minutes
          restartPolicy: Never
          terminationGracePeriodSeconds: 300 # 5 minutes
```

It runs a job every 5 minutes, and the pod sleeps for 2 minutes.

If during the sleep I execute the kubectl delete pod <POD_NAME> for a graceful termination, it will work, it will wait for the specified terminationGracePeriodSeconds and in this case, it will allow the pod to finish its job successfully.

But, the Kubernetes Job will be marked as 1 Failed with the reason BackoffLimitExceeded.

I have tried the Job configuration [activeDeadlineSeconds](https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup) and I'm still getting the error.

Could this be a bug or am I missing some configuration?

### What did you expect to happen?

The job is mark as completed.

### How can we reproduce it (as minimally and precisely as possible)?

Using the following, run it, and delete the pod before it finish its operation and then check for associated job status.

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleep-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0 # Avoid two executions
      template:
        spec:
          containers:
          - name: sleep
            image: busybox
            command: ["sh", "-c", "sleep 120"] # 2 minutes
          restartPolicy: Never
          terminationGracePeriodSeconds: 300 # 5 minutes
```

### Kubernetes version

<details>

```console
Client Version: v1.29.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5-gke.1091000
```

</details>

### Cloud provider

<details>
GCP with GKE v1.29.5-gke.1091000
</details>

**Comment by Ritikaa96** [comment]
Hi @saaguero , 
**BackoffLimitExceeded** as explained [here](https://github.com/kubernetes/kubernetes/blob/66126bbdc6c28dea6a3994d801974a9bbf892453/staging/src/k8s.io/api/batch/v1/types.go#L641
) is job failure reason where pods within a job have failed a number of times higher than backOffLimit times

Maybe check the output of kubectl get cronjobs.batch and see the value of backOffLimit set.

**Comment by Ritikaa96** [comment]
Here is the output to  `kubectl get cronjobs.batch -oyaml` in my system
```bash
apiVersion: v1
items:
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{},"name":"sleep-cronjob","namespace":"default"},"spec":{"jobTemplate":{"spec":{"backoffLimit":0,"template":{"spec":{"containers":[{"command":["sh","-c","sleep 120"],"image":"busybox","name":"sleep"}],"restartPolicy":"Never","terminationGracePeriodSeconds":300}}}},"schedule":"*/5 * * * *"}}
    creationTimestamp: "2024-06-26T14:27:16Z"
    generation: 1
    name: sleep-cronjob
    namespace: default
    resourceVersion: "102158"
    uid: 0e92b3cf-DDDD-4d22-VVVV-d6f6efd46ce8
  spec:
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        backoffLimit: 0
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers:
            - command:
              - sh
              - -c
              - sleep 120
              image: busybox
              imagePullPolicy: Always
              name: sleep
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 300
    schedule: '*/5 * * * *'
    successfulJobsHistoryLimit: 3
    suspend: false
  status: {}
kind: List
metadata:
  resourceVersion: ""
```
In your example , the backoffLimit is found was 0. Perhaps, that is the reason you are getting this reason.

**Comment by saaguero** [comment]
@Ritikaa96 hi, thanks for the details, and that's exactly what's happening which looks odd, that is:

- There is a Cronjob that needs to ensure only 1 Job is running at any given time, this why there is a `backoffLimit=0`.
- The Cronjob has the `pod.terminationGracePeriodSeconds = 300` to ensure it will get enough time (5 min) when there is a termination request.

This is working, in the sense that when the POD is running and you send a `kubectl delete [pod]` it will keep running until it finishes (in this example it just waits until 2 minutes.)

Therefore, I think the job should be marked as completed and not with the error `BackoffLimitExceeded`.

**Comment by Ritikaa96** [comment]
In my case i see 
```output
Events:
  Type    Reason            Age   From                Message
  ----    ------            ----  ----                -------
  Normal  SuccessfulCreate  27s   cronjob-controller  Created job sleep-cronjob-28656885
  Normal  SawCompletedJob   18s   cronjob-controller  Saw completed job: sleep-cronjob-28656885, status: Failed

```
when i delete the pod while it is sleeping the reason comes as SawCompletedJob.

**Comment by Ritikaa96** [comment]
Just to check , what you are doing is:

**Comment by saaguero** [comment]
> Just to check , what you are doing is:
> 
> * deploy the cronjob
> * when the pod starts , before its completion delete it
> * it will wait till graceperiod then get deleted and we will see status: Failed in the events
> * In your case the reason is backOffLimitExceeded

Exactly, and I would've expected the Cronjob (or the Job) waits for the `terminationGracePeriodSeconds` before calling it as failed.

**Comment by Ritikaa96** [comment]
I tried the same to replicate the issue but the reason was completely different. hm.. 
in the code , the SawCompletedJobs  reason occur [here](https://github.com/kubernetes/kubernetes/blob/66126bbdc6c28dea6a3994d801974a9bbf892453/pkg/controller/cronjob/cronjob_controllerv2.go#L450)
can you share the message  in the event section here as I'm unable to replicate the issue.

**Comment by Ritikaa96** [comment]
I am running cluster with the same k8s version however i tried in linux system. its uncertain if that might change the output , but i tried replicating it in different ways and the output is same.

**Comment by saaguero** [comment]
I run this again and I tail the events logs with `kubectl get events --watch`, the order of the event logs are the following:

```
Normal    Pulled                       pod/sleep-cronjob-28658220-mj58d                                  Successfully pulled image "busybox" in 861ms (861ms including waiting)
Normal    Created                      pod/sleep-cronjob-28658220-mj58d                                  Created container sleep
Normal    Started                      pod/sleep-cronjob-28658220-mj58d                                  Started container sleep
Normal    Killing                      pod/sleep-cronjob-28658220-mj58d                                  Stopping container sleep
Warning   BackoffLimitExceeded         job/sleep-cronjob-28658220                                        Job has reached the specified backoff limit
Normal    SuccessfulDelete             cronjob/sleep-cronjob                                             Deleted job sleep-cronjob-28658215
Normal    SawCompletedJob              cronjob/sleep-cronjob                                             Saw completed job: sleep-cronjob-28658220, status: Failed

... POD is still in Terminating status (waiting for the 'sleep' to finish)

POD ends successfully
```

As you can see, once I executed the `kubectl delete pod` it will almost at the same time emit the `BackoffLimitExceeded`, `SuccessfulDelete`, `SawCompletedJob`.

That means that the Job is not honoring the `terminationGracePeriodSeconds` from the POD specification. I'm wondering if there isn't any Job config that can honor that value?

**Comment by Ritikaa96** [comment]
It's quite interesting that in my system the reason: BackOffLimitExceeded is not seen with same manifest and test.
Here is what i got:
```bash
10m         Normal    SawCompletedJob           cronjob/sleep-cronjob              Saw completed job: sleep-cronjob-28658380, status: Complete
10m         Normal    SuccessfulCreate          cronjob/sleep-cronjob              Created job sleep-cronjob-28658385
8m30s       Normal    SuccessfulDelete          cronjob/sleep-cronjob              Deleted job sleep-cronjob-28658250
8m30s       Normal    SawCompletedJob           cronjob/sleep-cronjob              Saw completed job: sleep-cronjob-28658385, status: Complete
5m37s       Normal    SuccessfulCreate          cronjob/sleep-cronjob              Created job sleep-cronjob-28658390
3m30s       Normal    SawCompletedJob           cronjob/sleep-cronjob              Saw completed job: sleep-cronjob-28658390, status: Complete
37s         Normal    SuccessfulCreate          cronjob/sleep-cronjob              Created job sleep-cronjob-28658395
17s         Normal    SawCompletedJob           cronjob/sleep-cronjob              Saw completed job: sleep-cronjob-28658395, status: Failed


```

**Comment by saaguero** [comment]
I've tested this locally using [kind](https://kind.sigs.k8s.io/) with the following Kubernetes versions and I can still reproduce the issue.

- v1.30.0: kindest/node:v1.30.0
- v1.29.4: kindest/node:v1.29.4
- v1.25.16: kindest/node:v1.25.16

All of them had the same sequence of events when you delete the pod before it finishes:

```
0s          Normal   Created                   pod/sleep-cronjob-28685730-vbc85   Created container sleep
0s          Normal   Started                   pod/sleep-cronjob-28685730-vbc85   Started container sleep
0s          Normal   Killing                   pod/sleep-cronjob-28685730-vbc85   Stopping container sleep
0s          Warning   BackoffLimitExceeded      job/sleep-cronjob-28685730         Job has reached the specified backoff limit
0s          Normal    SawCompletedJob           cronjob/sleep-cronjob              Saw completed job: sleep-cronjob-28685730, status: Failed
```

**Comment by carvido1** [comment]
If you kill de pod before the sleep ends, the sleep process will exit with a exit code != 0.

```bash
➜  ~ sleep 1
➜  ~ echo $?
0
➜  ~ sleep 10
^C
➜  ~ echo $?
130
```

The exit code when you SIGINT the sleep is `130`, at least in system.

If you add a trap for the SIGINT or the termination signal, you might get a success run.

```bash
trap 'exit 0' SIGINT SIGQUIT SIGTERM;
```

Apparently this issue #85884 talks about preStop hooks in cronjobs, which similar thing could happen with the `terminationGracePeriodSeconds` attribute.

**Comment by saaguero** [comment]
Hi @carvido1 thanks for looking up. To clear things up, here is a better example ensuring that we have a graceful termination using Python. I'm getting the exact same issue though, that is, the Job is marked as Failed if you run a `kubectl delete pod`.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: script-configmap
data:
  test.py: |
    import signal
    import time
    import sys

    class GracefulKiller:
        kill_now = False
        def __init__(self):
            signal.signal(signal.SIGINT, self.exit_gracefully)
            signal.signal(signal.SIGTERM, self.exit_gracefully)

        def exit_gracefully(self, *args):
            print(f'Kill signal detected.')
            self.kill_now = True

    if __name__ == '__main__':
        killer = GracefulKiller()
        while True and not killer.kill_now:
          print("Sleeping 30 seconds")
          time.sleep(30)
        print(f'Gracefully terminated')
        sys.exit(0)
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleep-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0 # Avoid two executions
      template:
        spec:
          containers:
          - name: python-script
            image: python:3.8-slim
            command: ["python", "/scripts/test.py"]
            env:
            - name: PYTHONUNBUFFERED
              value: "1"
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
          restartPolicy: Never
          terminationGracePeriodSeconds: 300 # 5 minutes
          volumes:
          - name: script-volume
            configMap:
              name: script-configmap
```
