### ISSUE TITLE
ValidatingAdmissionPolicy could not find ConfigMap

### ISSUE THREAD

**Issue by Rookeur** [kubernetes/kubernetes#125737]
### What happened?

The ValidationAdmissionPolicyBinding cannot find the ConfigMap used as param

### What did you expect to happen?

The ValidationAdmissionPolicyBinding should find the ConfigMap

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
---
# policy.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: test-policy
spec:
  failurePolicy: Fail
  matchConstraints:
    matchPolicy: Equivalent
    resourceRules:
      - apiGroups:
          - ''
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - services
        scope: '*'
  paramKind:
    apiVersion: v1
    kind: ConfigMap
  validations:
    - expression: "object.spec.ports.exists_one(p, p.nodePort == int(params.data.minPort))"
      message: Invalid nodePort number selected
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "test-binding"
spec:
  matchResources:
    matchPolicy: Equivalent
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: test
  paramRef:
    name: "param-test"
    namespace: "test-config"
    parameterNotFoundAction: Deny
  policyName: test-policy
  validationActions:
    - Deny
---
apiVersion: v1
data:
  minPort: '31000'
kind: ConfigMap
metadata:
  name: "param-test"
  namespace: "test-config"
```
```yaml
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: test
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: ssh
      nodePort: 31000
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    app: nginx-test
  sessionAffinity: None
  type: NodePort
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1+rke2r1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
