### ISSUE TITLE
Why doesn't Kubernetes support all namespace deployments?

### ISSUE THREAD

**Issue by changhyuni** [kubernetes/kubernetes#125724]
### What happened?

Why doesn't Kubernetes support all namespace deployments?

### What did you expect to happen?

I want to deploy objects to all namespaces with a single manifest
I'm sorry if this was already asked, I couldn't find anything related.

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: *
spec:
....
...
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
       .....
       ..
       
apiVersion: v1
kind: Secret
metadata:
  name: docker-token
  namespace: *
data:
  .dockerconfigjson: UYaskdmqwasd
```

### Anything else we need to know?

I want to know the related issue URL or discussion information

### Kubernetes version

all

### Cloud provider

all
