### ISSUE TITLE
DRA: better reporting of problems in CEL expressions

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#125826]
### What would you like to be added?

This is fairly open-ended. We need to identify things that make sense first. Some options:

- Detect attribute or capacity domains and/or identifiers which don't match the validation constraints for those. Could be done by analyzing the AST of the CEL expression.
- Report problems with a claim, claim template or class in the status (new API!) or via events (no new API needed). ValidatingAdmissionPolicy could server as an example for how to do that.
- Write a tool which evaluates a CEL expression against a local or remove device definition and provides a detailed report.

### Why is this needed?

Help users write correct CEL.

**Comment by liggitt** [comment]
make sure whatever increased validation is done will do something sensible if already-persisted expressions that would not pass the validation is encountered

**Comment by nojnhuh** [comment]
@pohly I can try the attribute name validation part of this. Can the set of valid attribute names be determined from within [`CompileCELExpression`](https://github.com/kubernetes/kubernetes/blob/3d2ee2fbb729857e5f71868107882f9e3c2aa43e/staging/src/k8s.io/dynamic-resource-allocation/cel/compile.go#L125-L128) currently, or is part of the work here to figure out how to make that available?

**Comment by pohly** [comment]
`CompileCELExpression` can probably collect attribute names by walking over the AST, but I don't know how. So yes, definitely needs some exploration.

**Comment by cici37** [comment]
Thanks for the issue!

- `Detect attribute or capacity domains and/or identifiers which don't match the validation constraints for those. Could be done by analyzing the AST of the CEL expression.`
Didn't quite get this one. Is this related with type checking we wanna enforced for the attributes/domains or is it related with some further constraints we wanna apply for validation or something else?

- `Report problems with a claim, claim template or class in the status (new API!) or via events (no new API needed). ValidatingAdmissionPolicy could server as an example for how to do that.`
 This makes sense. Having status for reporting such problem sounds reasonable to me. 

- `Write a tool which evaluates a CEL expression against a local or remove device definition and provides a detailed report. This can include more details about cost limits than what is provided by validation.`
 I plan to have some tooling provided for shift-left testing which hopefully would help.

**Comment by johnbelamaric** [comment]
I broadened the scope of this a bit, @pohly. Let's use it as a place to collect ideas, at least. In addition to the troubleshooting help, one things we discussed is allowing definition of variables to make the expressions more readable. Looking at the [CELDeviceSelector](https://pkg.go.dev/k8s.io/kubernetes/pkg/apis/resource#CELDeviceSelector), I think we could add `Variables` to pre-define some snippets and re-use them in the expression:

```yaml
...
  selectors:
    - cel:
      variables:
      - x: "some complex expression"
      - y: "some other complex expression"
      expression: "x == y"
```

**Comment by johnbelamaric** [comment]
cc @cslink

**Comment by cici37** [comment]
Variables is working great in VAP and MAP as a way to avoid repeating variables used in expression. Happy to see it could be used in DRA as well. :)

**Comment by pohly** [comment]
> > Detect attribute or capacity domains and/or identifiers which don't match the validation constraints for those. Could be done by analyzing the AST of the CEL expression.
>
> Didn't quite get this one. Is this related with type checking we wanna enforced for the attributes/domains or is it related with some further constraints we wanna apply for validation or something else?

Specific example: `devices.attributes["%^#$@$"].some_very_very_very_very_very_long_name` can never work for two reasons:
- `%^#$@$` is not a valid DNS subdomain
- `some_very_very_very_very_very_long_name` is too long for the C identifier part of an attribute name

Validation of the CEL expression does not detect that this expression is broken. Instead, it will fail each time it gets evaluated.

Another example: `"%^#$@$" in devices.attributes` is always false, which is probably a user mistake.

We can't catch everything, but some checks would be better than none.

> Variables is working great in VAP and MAP as a way to avoid repeating variables used in expression.

Agreed, added to description.

**Comment by cici37** [comment]
Hi @pohly thanks for the further info! Is this regarding with failing the expression early instead of behaving incorrect? Cause the behavior seems right to me(fail the request if "%^#$@$" does not match. Is there a the DNS subdomain check while creating the resources(if that is the name of other resources, it might exist while API validation) or is it guaranteed that the attributes value should be a DNS subdomain? Would a subdomain check func be sufficient instead of traversing AST(from my poor memory I don't think AST is exported)?

**Comment by pohly** [comment]
> Is there a the DNS subdomain check while creating the resources(if that is the name of other resources, it might exist while API validation) or is it guaranteed that the attributes value should be a DNS subdomain?

Yes, validation ensures that:
https://github.com/kubernetes/kubernetes/blob/ee22760391bae28954a69dff499d1cead9a9fcf0/pkg/apis/resource/types.go#L238-L254

> Would a subdomain check func be sufficient instead of traversing AST(from my poor memory I don't think AST is exported)?

But who does that check? The code which looks it up at runtime? That then leads to runtime errors, which is roughly what we have now. I don't think that's worth it.

**Comment by TristonianJones** [comment]
Hi all! I'm just catching up on this thread, but you may find the CEL policy parser / compiler useful here since it tackles this same use case: https://github.com/google/cel-go/blob/master/policy/README.md

**Comment by cslink** [comment]
I can take a look at status reporting for CEL issues.

**Comment by cslink** [comment]
@TristonianJones my plan was to look at this item specifically:

> * Report problems with a claim, claim template or class in the status (new API!) or via events (no new API needed). ValidatingAdmissionPolicy could server as an example for how to do that.

It looks like the options are either to add something to [ResourceClaimStatus](https://pkg.go.dev/k8s.io/kubernetes/pkg/apis/resource#ResourceClaimStatus) to report CEL errors or to use the event API to surface this info. The goal in either case would be to surface these errors in a place that's easier to find for the user.

If I have time, I can also take a look at the other concrete proposal from the original request, specifically: 

> * Extend the CEL selector to support variables:
>   ```
>    selectors:
>       - cel:
>         variables:
>         - x: "some complex expression"
>         - y: "some other complex expression"
>         expression: "x == y"
>   ```

**Comment by cslink** [comment]
To get a better idea of the current behavior, I put together a repro of this issue on a kind cluster using a 1.33 image built from head a couple weeks ago.
Kind setup:
`kind create cluster --image kindest/node:latest --config config.yaml`
config.yaml:
```
kind: Cluster

apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "DynamicResourceAllocation": true
runtimeConfig:
  "api/beta": "true" 

nodes:
- role: control-plane
- role: worker
```

As my setup on this cluster, I had this `ResourceSlice`:
```
apiVersion: resource.k8s.io/v1beta1
kind: ResourceSlice
metadata:
  name: gpu-node-0
spec:
  driver: gpu.nvidia.com
  nodeName: kind-worker
  pool:
    name: "pool"
    generation: 1
    resourceSliceCount: 1
  devices:
  - name: gpu-0
    basic:
      attributes:
        uuid:
          string: GPU-18db0e85-99e9-c746-8531-ffeb86328b39
        index:
          int: 0
        model:
          string: "NVIDIA GH200 96GB HBM3"
        driverVersion:
          version: 550.94.0
      capacity:
        memory: 
          value: 96Gi
```

These variants of `DeviceClass`: 

Good CEL selector
```
apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: gpu.nvidia.com
spec:
  selectors:
  - cel:
      expression: "true"
```

Bad CEL selector
```
apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: gpu.nvidia.com
spec:
  selectors:
  - cel:
      expression: "device.driver == 'gpu.nvidia.com' && device.attributes['bar'].type == 'gpu'"
```

These variants of `ResourceClaimTemplate`:

Good CEL selector
```
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: all-gpus
spec:
  spec:
    devices:
      requests:
      - name: gpu
        deviceClassName: gpu.nvidia.com
        allocationMode: All
        selectors:
        - cel:
            expression: 'true' 
```

Bad CEL selector
```
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: all-gpus
spec:
  spec:
    devices:
      requests:
      - name: gpu
        deviceClassName: gpu.nvidia.com
        allocationMode: All
        selectors:
        - cel:
            expression: 'device.attributes["example.com"].foo' 
```

This `Deployment`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccc-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccc-gpu
  template:
    metadata:
      labels:
        app: ccc-gpu
    spec:
      containers:
      - name: ctr
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; trap 'exit 0' TERM; sleep 9999 & wait"]
        resources:
          claims:
          - name: gpu
      resourceClaims:
      - name: gpu
        resourceClaimTemplateName: all-gpus
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
```

I observed what happened when I applied the deployment in `kubectl get events`

For the bad selector in `ResourceClaimTemplate`:

9m10s       Warning   FailedScheduling                pod/ccc-gpu-78b76d674f-8c9mp   running "DynamicResources" filter plugin: claim default/ccc-gpu-78b76d674f-8c9mp-gpu-b9n4s: selector #0: CEL runtime error: no such key: foo

For the bad selector in `DeviceClass`:

44m         Warning   FailedScheduling                pod/ccc-gpu-78b76d674f-8c9mp   running "DynamicResources" filter plugin: class gpu.nvidia.com: selector #0: CEL runtime error: no such key: type

These events come from failed scheduling of the corresponding `Pod` to the `Deployment`, which can be confirmed as follows:
```
$ kubectl describe pod ccc-gpu-78b76d674f-8c9mp
Name:             ccc-gpu-78b76d674f-8c9mp
Namespace:        default
[redacted for brevity]
Events:
  Type     Reason                         Age                      From               Message
  ----     ------                         ----                     ----               -------
  Warning  FailedScheduling               36m (x20 over 39m)       default-scheduler  running "DynamicResources" filter plugin: class gpu.nvidia.com: selector #0: CEL runtime error: no such key: type
  Warning  FailedScheduling               106s (x1184 over 3h27m)  default-scheduler  running "DynamicResources" filter plugin: claim default/ccc-gpu-78b76d674f-8c9mp-gpu-b9n4s: selector #0: CEL runtime error: no such key: foo
```

Also of note: If you provide a CEL selector that doesn't compile such as the one below, the API server will reject it.
```
$ kubectl create -f - << EOF

apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: gpu.nvidia.com
spec:
  selectors:
  - cel:
      expression: "undefined"
EOF
The DeviceClass "gpu.nvidia.com" is invalid: spec.selectors[0].cel.expression: Invalid value: "undefined": compilation failed: ERROR: <input>:1:1: undeclared reference to 'undefined' (in container '')
 | undefined
 | ^
$ kubectl get deviceclasses
No resources found
```
