### ISSUE TITLE
emptyDir Volume sometimes not populated (race condition?)

### ISSUE THREAD

**Issue by bkeroackdsc** [kubernetes/kubernetes#12588]
I have a pod which consists of two containers, an application "build" container with application code and a "runner" container which executes the application.

In order for the two to share the data, the build container copies over the application code to an ``emptyDir`` volume on startup, which is also mounted in the runner container. The runner container polls for the existence of a magic file in the volume and, when found, executes the application.

Roughly 50% of the time, even after the build container successfully copies over the data, the runner container can't see it. Using a shell via ``docker exec`` I can verify that the data is copied to the correct location from the perspective of the build container, however i can also see that it is an empty directory from the perspective of the runner container.

The pod template is equivalent to this:

```yaml
    spec:
      containers:
        - name: app-runner
          image: foobar/app-runner:latest
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: app-build-volume
              mountPath: /opt/k8s-build
        - name: app-build
          image: foobar/app-build:latest
          volumeMounts:
            - name: app-build-volume
              mountPath: /opt/k8s-build
      volumes:
        - name: app-build-volume
          emptyDir: {}
```

The build container does this on startup:

```bash
rm -rfv /opt/k8s-build/* || exit 1
cp -v -R /opt/build/* /opt/k8s-build/ || exit 1
```

This is what the volume looks like from the runner:

```bash
$ ls /opt/k8s-build/foobar/
application-name
$ ls /opt/k8s-build/foobar/application-name/
$
```

I usually have to delete and restart the controller once or twice before the volume succeeds. This is k8s 1.0.1 on CoreOS in AWS.

Any ideas how I can troubleshoot further?
