### ISSUE TITLE
Using server-side-apply for an Ingress failed when updating IngressBackend from port number to port name

### ISSUE THREAD

**Issue by ahus1** [kubernetes/kubernetes#125869]
### What happened?

I created an Ingress resource with a port number manually, and then tried to use an Operator with server-side apply to update the resource from a port number to a port name. This failed with the error message "cannot set both port name & port number".

### What did you expect to happen?

I expected the port number to be cleared as the operator would take over the ownership of the ServiceBackendPort. 

### How can we reproduce it (as minimally and precisely as possible)?

To simulate the behavior in the operator in a most simple example I use `kubectl`:

ingress-v1.yaml:

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: myingress
spec:
  defaultBackend:
    service:
      name: myservice
      port:
        number: 8443
```

ingress-v2.yaml:

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: myingress
spec:
  defaultBackend:
    service:
      name: myservice
      port:
        name: http
```

```
kubectl apply -f  ingress-v1.yaml --server-side --field-manager=app-1 --validate=false
kubectl apply -f  ingress-v2.yaml --server-side --field-manager=app-2 --validate=false  --force-conflicts 
```

This will print: 

> The Ingress "myingress" is invalid: spec.defaultBackend: Invalid value: "": cannot set both port name & port number

### Anything else we need to know?

It seems to me that the merge type for the struct ServiceBackendPort should to be set to "atomic" [according to this doc](https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy), so that the Operator updating the port  should take over the whole struct, and two applications shouldn't update single fields in it.

https://github.com/kubernetes/kubernetes/blob/0cc57258c3f8545c8250f0e7a1307fd01b0d283d/staging/src/k8s.io/api/networking/v1/types.go#L523-L544

### Kubernetes version

```
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9+416ecaf
```

### Cloud provider

Red Hat OpenShift on AWS

### OS version

OS version of the client:

NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"

Linux fedora.fritz.box 6.9.6-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 21 15:48:21 UTC 2024 x86_64 GNU/Linux

### Install tools

-

### Container runtime (CRI) and version (if applicable)

-

### Related plugins (CNI, CSI, ...) and versions (if applicable)

-
