### ISSUE TITLE
Termination signals not sent to Native Sidecars when multiple Native Sidecars

### ISSUE THREAD

**Issue by Stono** [kubernetes/kubernetes#125880]
### What happened?

In a situation where during the init phase of a `Pod`, a native sidecar never becomes ready (because its `startupProbe` is failing), then the `Pod` is terminated, if there are multiple startup containers, a termination signal is never received by the init container and the Pod is stuck (until `terminationGracePeriodSeconds` is hit).

### What did you expect to happen?

All running initContainer to receive the termination signal correctly.  

### How can we reproduce it (as minimally and precisely as possible)?

Create a `Dockerfile` with this bash script as an entrypoint:

```
#!/bin/bash
set -e 
trap 'echo "saw an exit signal"; sleep 5; exit' EXIT

while true; do
  echo "hello"
  sleep 1
done
```

Create a deployment with two init containers (one normal one sidecar).  Add an probe which means the startupProbe never passes

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karl-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app2: karl-test
  template:
    metadata:
      labels:
        app2: karl-test 
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 600
      initContainers:
      - name: init-1
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "echo 'init container 1'"]
      - name: init-2
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        restartPolicy: Always 
        startupProbe:                                                                                                                                                                                                          
          failureThreshold: 600 
          httpGet:
            path: /whatever
            port: 1234
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 3
      containers:
      - name: karl-test
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
```

Create the deployment, and it'll be stuck in Init, as you'd expect:

```
karl-test-deployment-c979948d8-xghf4   0/2     Init:1/2   0          5s
```

`kubectl delete` the pod and you'll see the exit signal has been sent to `init-2`:
```
hello
hello
hello
saw an exit signal
```

Delete the deployment / clean everything up.  Now, add a third `initContainer`:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karl-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app2: karl-test
  template:
    metadata:
      labels:
        app2: karl-test 
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 600
      initContainers:
      - name: init-1
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "echo 'init container 1'"]
      - name: init-2
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        restartPolicy: Always 
        startupProbe:                                                                                                                                                                                                          
          failureThreshold: 600 
          httpGet:
            path: /whatever
            port: 1234
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 3
      - name: init-3
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        restartPolicy: Always 
        startupProbe:                                                                                                                                                                                                          
          failureThreshold: 600 
          httpGet:
            path: /whatever
            port: 1234
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 3
      containers:
      - name: karl-test
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
```

As before, the `init` process will be stuck on `init-2` because of the bad probe:
```
karl-test-deployment-5c547f8f86-s8nqh   0/3     Init:1/3   0          1s
```

However when you delete the pod this time, no exit signal is sent to `init-2`, the pod is now stuck until `terminationGracePeriodSeconds` is reached.

### Anything else we need to know?

_No response_

### Kubernetes version

```
Client Version: v1.28.5
Server Version: v1.29.4-gke.1043002
```

### Cloud provider

GKE v1.29.4-gke.1043002

### OS version

Core OS on GCP

### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
