### ISSUE TITLE
NodePort service with endpoints has "has no local endpoints" in iptables

### ISSUE THREAD

**Issue by pingiun** [kubernetes/kubernetes#125810]
### What happened?

I set up a NodePort service pointing to an envoy gateway. Initially this works, and the port is connected to the envoy gateway correctly. However when something changes about the gateway (does not matter what), the service does not connect anymore. In iptables-save, I found the following rule which blocks traffic:
```
-A KUBE-EXTERNAL-SERVICES -p tcp -m comment --comment "envoy-gateway-system/envoy-default-eg-e41e7b31:http-80 has no local endpoints" -m addrtype --dst-type LOCAL -m tcp --dport 30100 -j DROP
```

Even though this rule also still exists:
```
-A KUBE-NODEPORTS -p tcp -m comment --comment "envoy-gateway-system/envoy-default-eg-e41e7b31:http-80" -m tcp --dport 30100 -j KUBE-EXT-GGWL76EB3A5WOB4Q
-A KUBE-EXT-GGWL76EB3A5WOB4Q -s 10.1.0.0/16 -m comment --comment "pod traffic for envoy-gateway-system/envoy-default-eg-e41e7b31:http-80 external destinations" -j KUBE-SVC-GGWL76EB3A5WOB4Q
-A KUBE-EXT-GGWL76EB3A5WOB4Q -m comment --comment "masquerade LOCAL traffic for envoy-gateway-system/envoy-default-eg-e41e7b31:http-80 external destinations" -m addrtype --src-type LOCAL -j KUBE-MARK-MASQ
-A KUBE-EXT-GGWL76EB3A5WOB4Q -m comment --comment "route LOCAL traffic for envoy-gateway-system/envoy-default-eg-e41e7b31:http-80 external destinations" -m addrtype --src-type LOCAL -j KUBE-SVC-GGWL76EB3A5WOB4Q
-A KUBE-SVC-GGWL76EB3A5WOB4Q ! -s 10.1.0.0/16 -d 10.0.0.251/32 -p tcp -m comment --comment "envoy-gateway-system/envoy-default-eg-e41e7b31:http-80 cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SVC-GGWL76EB3A5WOB4Q -m comment --comment "envoy-gateway-system/envoy-default-eg-e41e7b31:http-80 -> 10.1.1.19:10080" -j KUBE-SEP-TW3CXZOYNBZZ6B2U
```

### What did you expect to happen?

When the envoy gateway changes, the nodeport should still work.

### How can we reproduce it (as minimally and precisely as possible)?

The nodeport service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: envoy-default-eg-e41e7b31
  namespace: envoy-gateway-system
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 10080
      nodePort: 30100
    - name: https-443
      protocol: TCP
      port: 443
      targetPort: 10443
      nodePort: 30101
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: eg
    gateway.envoyproxy.io/owning-gateway-namespace: default
  type: NodePort
```

The gateway:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  listeners:
  - name: http
    protocol: HTTP
    port: 80
  - name: https
    protocol: HTTPS
    hostname: "bot.yele.dev"
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: eg-https
```

### Anything else we need to know?

```
; kubectl -n envoy-gateway-system get endpointslices
NAME                              ADDRESSTYPE   PORTS                           ENDPOINTS   AGE
envoy-default-eg-e41e7b31-cx6mm   IPv4          10443,10080                     10.1.1.19   66m
envoy-gateway-mxd5w               IPv4          19001,18000,18002 + 1 more...   10.1.2.80   4h4m
; kubectl -n envoy-gateway-system get endpoints envoy-default-eg-e41e7b31
NAME                        ENDPOINTS                         AGE
envoy-default-eg-e41e7b31   10.1.1.19:10443,10.1.1.19:10080   57m
```

When I replace the service, it starts working again.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.4", GitCommit:"bae2c62678db2b5053817bc97181fcc2e8388103", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.21.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.28) exceeds the supported minor version skew of +/-1```

</details>


### Cloud provider

<details>
None
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="23.11.20240213.01885a0"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 23.11 (Tapir)"
SUPPORT_END="2024-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="23.11 (Tapir)"
VERSION_CODENAME=tapir
VERSION_ID="23.11"
$ uname -a
Linux vmbox-1 6.1.77 #1-NixOS SMP PREEMPT_DYNAMIC Mon Feb  5 20:13:03 UTC 2024 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
