### ISSUE TITLE
Horizontal Pod Autoscaler - Ranges

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [kubernetes/kubernetes#125987]
**Which component are you using?**:

Horizontal Pod Autoscaler

**Is your feature request designed to solve a problem? If so describe the problem this feature should solve.**:

My feature is meant to allow an easier control of your deployment total capacity

**Describe the solution you'd like.**:

Let's say that im scaling out/in based on CPU. I would like to be able to express that my IF my deployment usage of cpu is:
- inferior to 30%, a scale in operation should take place
- superior to 75%, a scale out operation should take place

any value in between, and the deployment stays put.

I imagine that the yml should look like:

```yml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: sample-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      range: #NOT target, but RANGE!
        type: Utilization
        minUtilization: 30
        maxUtilization: 75
```

**Describe any alternative solutions you've considered.**:

Couldn't come up with alternative solutions

**Additional context.**:

I would be willing to help coding this feature
