### ISSUE TITLE
Remove gitRepo volume type

### ISSUE THREAD

**Issue by vinayakankugoyal** [kubernetes/kubernetes#125983]
### What would you like to be added?

I'd like to remove gitRepo volume types. It's been deprecated for 6 years now and if a giant foot gun. 

In a recent blog a researcher has exploited it to get remote code execution(RCE). 

https://irsl.medium.com/sneaky-write-hook-git-clone-to-root-on-k8s-node-e38236205d54

### Why is this needed?

To prevent folks from using a deprecated and dangerous volume type.

**Comment by SaranBalaji90** [comment]
+1. FYI we discussed about removing the gitRepo volume provisioner in the past (for context - https://docs.google.com/document/d/1-8KEG8AjAgKznS9NFm3qWqkGyCHmvU6HVl0sk5hwoAE/edit#heading=h.9ealp5t409p1). As a first step to restrict the use, we could also evaluate adding support in PSA to disallow creation of gitRepo volume for Baseline/Restricted namespaces [1].

[1] - https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline

**Comment by raesene** [comment]
I'd definitely agree that this should be removed, or at the very least moved to not be enabled by default. PSS baseline would be good to.

Having a situation where anyone with create pod automatically gets code execution on the underlying node as root is .... not the best.

**Comment by niranjandarshann** [comment]
We should remove the gitRepo volume provisioner or at least disable it by default. Adding a restriction in the Pod Security Standards baseline would be good too. Letting anyone who can create a pod run code as root on the node is very risky.

**Comment by destijl** [comment]
+1 for removal, and putting a forbid into PSS baseline (like hostpath is today) while that happens.

**Comment by tabbysable** [comment]
+1 for removing gitRepo if possible

Huge +1 to forbidding gitRepo in baseline

**Comment by saad-ali** [comment]
Copying my comment from https://github.com/kubernetes/kubernetes/issues/126041:

> It looks like completely removing the API/code would have been considered a backwards incompatible change which k8s avoids, and so only a deprecation notice was created and the code was left as is see #63445 (comment)
> 
> We have been able to get rid of other in-tree plugins by keeping the API and implementing "CSI migration" which enables the implementation to be removed and redirect to new CSI drivers. In this case there is no "CSI" migration -- instead the recommendation is to use emptyDir + initContainers.
> 
> To remove risk from the unmaintained code -- I suggest that we keep the API, but remove the implementation. (We did exactly this with Flocker, for example, see #111618)

**Comment by BenTheElder** [comment]
cc @thockin

somewhat git-sync adjacent.

**Comment by liggitt** [comment]
I'm in favor of a controlled way to remove this, but there *has* to be a way to burn down use safely. Starting with an opt-in gate that disables the plugin, then planning and communicating how to flip that to opt-out safely is a much more controlled way to allow this to roll out.

**Comment by BenTheElder** [comment]
> Starting with an opt-in gate that disables the plugin, then planning and communicating how to flip that to opt-out safely is a much more controlled way to allow this to roll out.

This, we should outline:
- A concrete "this feature gate will be removed in release 1.X"
- This is what you can use instead (e.g. git-sync)

And communicate it widely ahead of time, not just in release notes. With a way to opt-back in to support for N releases. 
We don't want people to stop upgrading Kubernetes because we abruptly dropped functionality.

At the minimum we should be creating a kubernetes.io blogpost and planning to work with contributor comms on that and posting to social media etc. cc @kubernetes/contributor-comms

**Comment by vinayakankugoyal** [comment]
How about we block it in PSS baseline for now and work on a plan to remove it with opt-in in 1.32?

**Comment by liggitt** [comment]
I don't think it makes sense to block in baseline... that profile forbids _inherently_ host-level and escalating things. I don't think gitRepo volumes fall in that bucket.

**Comment by thockin** [comment]
It looks like there are ways to disable hooks (e.g. config `core.hooksPath=/dev/null`, but I have not manually tested that) which would have LESS, but not NO impact.  We could add that as an optional field in gitRepo and then security-conscious folks could demand it be set, while still allowing repos to be cloned?

**Comment by BenTheElder** [comment]
Regarding removal, see also the discussion in https://github.com/kubernetes/kubernetes/pull/126084#issuecomment-2231579005


> I don't think it makes sense to block in baseline... that profile forbids inherently host-level and escalating things. I don't think gitRepo volumes fall in that bucket.

Isn't it effectively at this point? Unless we're able to prevent these hooks ...


> It looks like there are ways to disable hooks (e.g. config core.hooksPath=/dev/null, but I have not manually tested that) which would have LESS, but not NO impact. We could add that as an optional field in gitRepo and then security-conscious folks could demand it be set, while still allowing repos to be cloned?

Don't we have precedent with breaking behavioral changes for volumes to mitigate serious vulns?

https://github.com/kubernetes/kubernetes/issues/60814

> **Fix impact:**
> Secret, configMap, downwardAPI and projected volumes will be mounted as read-only volumes. Applications that attempt to write to these volumes will receive read-only filesystem errors. Previously, applications were allowed to make changes to these volumes, but those changes were reverted at an arbitrary interval by the system. Applications should be re-configured to write derived files to another location.

**Comment by BenTheElder** [comment]
Ah, we do have https://github.com/kubernetes/kubernetes/pull/124531

**Comment by ritazh** [comment]
Should the removal be part of 1.33?

**Comment by vinayakankugoyal** [comment]
Yes please! To liggitt@ point we should atleast consider adding an opt-in that allows users to turn this off. In addition we can update documentation and provide alternatives to gitRepo.

**Comment by thockin** [comment]
I posted somewhere a VAP config that people can/should use to deny gitRepo (will post it again below).

> Should the removal be part of 1.33? [on behalf of SRC]

Do we think this is SO critical that we violate our own breaking-changes rule?

Easy: Add a new optional field in `gitRepo` to disable hooks.  Alpha-gated in 33, GA, default-off in 34.
  Pro: not a breaking change
  Con: opt-in

Medium: Add a new optional field in `gitRepo` to disable hooks.  Alpha-gated in 33, GA default-on in 34.
  Pro: secure by default
  Con: breaking change for users of hooks
  Rebuttal: It's hard to imagine a correct use of hooks

Hard: Nullify out `gitRepo` functionality entirely.  (it's been deprecated since 1.11)
  Pro: secure by default
  Con: breaking change for all `gitRepo` users


deny-gitrepo-vap.yaml:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "deny-git-repo-volumes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE"]
      resources:   ["pods"]
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["podtemplates", "replicationcontrollers"]
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["daemonsets", "deployments", "replicasets", "statefulsets"]
    - apiGroups:   ["batch"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["jobs", "cronjobs"]
  validations:
    - expression: |
        (object.kind == "Pod" &&
            object.spec.?volumes.orValue([]).all(v, !has(v.gitRepo))) ||
        (object.kind == "PodTemplate" &&
            object.template.spec.?volumes.orValue([]).all(v, !has(v.gitRepo))) ||
        (["DaemonSet","Deployment","ReplicaSet",'StatefulSet','Job'].filter(kind, object.kind == kind) != [] &&
            object.spec.template.spec.?volumes.orValue([]).all(v, !has(v.gitRepo))) ||
        (object.kind == "CronJob" &&
            object.spec.jobTemplate.spec.template.spec.?volumes.orValue([]).all(v, !has(v.gitRepo)))
      message: "gitRepo volumes are forbidden"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "deny-git-repo-volumes"
spec:
  policyName: "deny-git-repo-volumes"
  validationActions: [Deny]
  # empty matchResources means match all
```

**Comment by BenTheElder** [comment]
Regarding dropping fields entirely: see https://kubernetes.io/docs/reference/using-api/deprecation-policy/

**Comment by thockin** [comment]
Note: I am not proposing to remove fields.  At most we would make them mean nothing.

> a way for a cluster admin to neuter gitRepo volume support

Does the VAP I provided above satisfy that?  I think it does, as long as "opt in to security" is acceptable.  And if that is acceptable, I don't know if we need a change to the `gitRepo` API/impl to block hooks (it's opt-in either way).

If we want secure-by-default, that's a breaking change however we do it.  We can do varying levels of hoop-jumping to re-allow usage.
- trivially restored: Add a field to `gitRepo` requiring end-users to opt-in to hooks.
  - Pro: easy for an impacted user to fix themselves
  - Con: easy for an attacker to circumvent
- possible to restore by admin: Add a kubelet config which tells it not to run hooks for `gitRepo`
  - Pro: hard for attacker to circumvent
  - Con: requires changes on each node, enablement is whole node
- very hard to restore by admin: Add an API server config which tells it not to run hooks
  - Pro: whole cluster
  - Con: probably better to have the VAP above
- impossible to restore: Disable git hooks in `gitRepo`, no way to re-enable
  - Pro: no API surface, no circumvention
  - Con: no way to restore
- a step too far: turn `gitRepo` into an actual no-op
  - Pro: no way around it
  - Con: no way around it 

The question is: Do we think this is dire enough to break people?

I think the hole is pretty nasty, personally, and may be worth it.  I have a hard time coming up with a legitimate use of git hooks thsat run in root context, `gitRepo` has been depreceated for years, and there is a workable alternative in `git-sync`.  

I am pretty sure there are users of `gitRepo` volumes, so breaking them entirely seems a step too far, but breaking the specific hooks functionality might be OK (even without an option to restore it).  Obviously it would be a gate, so we'd have a way back.  We might want to consider accelerating the announcment-and-wait cycle.

**Comment by vinayakankugoyal** [comment]
Could we write a ValidatingAdmissionWebhook similar to DenyServiceExternalIP that prevents this?

**Comment by thockin** [comment]
@vinayakankugoyal What is "this" in "denies this"?

The VAP I wrote above denies all use of gitRepo, but it's opt-in.  Cluster admin has to take the action of installing it.

In looking at it, I think I forgot to properly handle "replicationcontrollers" which just goes to show how easy it is to get wrong :)

**Comment by vinayakankugoyal** [comment]
Sorry that I wasn't clear earlier. "this" meant a way to block the use of gitRepo in the cluster.

**Comment by vinayakankugoyal** [comment]
I am not a huge fan of using VAP for this. If we deem gitRepo to be dangerous then we should provide a way to outright disable it using an APIServer flag because that option is more auditable. Its much easier to check if the AdmissionPlugin "DenyGitRepo" is enabled than to check if a VAP exists that blocks gitRepo volumes.

**Comment by thockin** [comment]
I don't have a strong feeling, but:

* Do we want dozens of bespoke admission plugins?  This is what VAP is for.
* If we do that, cluster providers need to re-expose it through their infra APIs - more work
* If we do that, there's no way to ask the cluster "is gitRepo blocked" except to try creating a pod
* VAP can be enabled or disabled more granularly

**Comment by liggitt** [comment]
This is announced as targeting future removal in the 1.32 release notes - https://github.com/kubernetes/website/pull/48666/files#r1871864868

Until we've actually decided that, we should not announce removal

**Comment by liggitt** [comment]
cc @xing-yang @saad-ali @msau42 @jsafrane

**Comment by saad-ali** [comment]
> This is announced as targeting future removal in the 1.32 release notes - https://github.com/kubernetes/website/pull/48666/files#r1871864868
> 
> Until we've actually decided that, we should not announce removal

We (SIG Storage) should have coordinated that better with the folks in this thread before it went in (sorry about that).

We discussed this in SIG Storage. Our thought process is:

1. There is no one actively maintaining git-repo.
2. There are security concerns with the plugin
3. Our [public docs](https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo) have a warning about deprecation(`The gitRepo volume type is deprecated...`) and there is a warning on the resource.
5. There is a viable alternative emptyDir+initContainer
6. Disabling hooks feels like playing "whack a mole" with security issues that emerge. 
7. We have "removed" other in-tree plugins successfully in the past.
8. There is a non-trivial cost to continuing to fix the gitRepo code.

So from a SIG Storage POV -- we would prefer to remove the gitRepo plugin altogether. Note that "remove" here means removing the business logic not the API (which is still a breaking change, of course). 

The idea is to get the removal notice in the release notes ASAP, so that we can actually remove it in some future release.

If API reviewers disagree with that (or want more time to discuss this) we will undo the [removal notice](https://github.com/kubernetes/website/pull/48666/files#r1871864868). 

Please let us know.

**Comment by thockin** [comment]
https://github.com/kubernetes/website/pull/48666/files#r1871943622

"""
we've discussed this at SIG Storage meetings and agreed to remove this
"""

This is relatively unprecedented and I don't think this is a decision to be made lightly or unilaterally.  It sets precedent for the project.  Unfortunately, I have a thing I must be at during this week's sig-arch meeting.  I will try to come for some of it.

I personally DO NOT think we should announce the removal without broader agreement and boundaries - what makes this OK and the next one not?

**Comment by thockin** [comment]
I put it on sig-arch agenda

**Comment by dims** [comment]
for the CSI volume plugins, we were sooooo conservative, we still have portworx that is to be removed in 1.33... we can't rush here!

So +1 to what @thockin and @liggitt said.

**Comment by saad-ali** [comment]
Based on your input, we'll go ahead and rollback the removal notice.

**Comment by thockin** [comment]
Quick notes from sig-arch discussion:

Preference for a way to disable it while allowing cluster providers (Openshift, GKE, etc) to offer a way to enable it if they need to, based on their own data.  I read that as a built-in admission controller (or maybe a pre-installed VAP?) that prevents either using `gitRepo` or perhaps just prevents using hooks.  This would be a break for people who use gitRepo (or just those who use hooks).  Providers can look at their respective fleets for how many users of `gitRepo` exist.  They cannot easily analyze how many of those `gitRepo` users rely on hooks.

Preference for on-by-default, since this is a significant potential exposure.

IMO, if we are doing a breaking change, we need to scope it as small as possible.  I do not love this feature, but there are lots of features in k8s I don't like, and we're not considering ripping those out.  :)

Here's my revised proposal(s):

* Add a field to `gitRepo` called `enableInsecureHooks bool` or something like that.  Default to false.
* Either:
  a) Add a built-in admission control that rejects workloads that set `gitRepo.enableInsecureHooks: true` with either:
    1) On by default + relnote about disabling it if needed
    2) Relnote that cluster providers are STRONGLY ENCOURAGED to enable it
  b) Publish a VAP that rejects workloads that set `gitRepo.enableInsecureHooks: true` with a relnote that cluster providers are STRONGLY ENCOURAGED to preinstall it.

Having a field in the API allows `gitRepo` users who do not need hooks to keep working, while allowing those who need to hooks to self-identify, and locked-down providers (e.g. do not allow SSH to nodes) can prevent hooks entirely. 

VAP has the advantage of being an "initial setting" that providers impose, but cluster admins can change (either partially or entirely) *without* needing providers to expose it through their own API.  I don't think we have any real precedent for this specific pattern, but we know many providers run their own webhooks or other admission controls.  It has the disadvantage of requiring providers to take action to be secure.

Built-in admission control has the advantage and disadvantage of being on by default, and requires providers to expose an knob through their own APIs to change the behavior, and such a change is for the whole cluster (unless we also offer per-node control).

I lean towards VAP, myself.  It seems like a useful pattern to have "recommended but optional" policies that can be installed by providers and changed by admins.

Thoughts?

**Comment by thockin** [comment]
@saad-ali @msau42 since this sort of rolls up to sig-storage, is there anyone who can help with impl?  It should not be very  much work, but having someone who could do it would help me a ton.

Someone who wants to build up to org membership, perhaps?  Or someone who wants to build their contributions up more?  I imagine this is a small KEP, especially if we add a field.

**Comment by vinayakankugoyal** [comment]
@thockin I'd be more than happy to help with impl and driving the KEP.

**Comment by thockin** [comment]
Awesome.  Can we talk either next week or after the holidays?  If we are going to come up with a KEP, we need to move fast.  Talking to some folks today, even more options were presented:

1) Builtin-admission as described above
2) Pre-installed VAP as described above
3) NEW IDEA: disable `gitRepo.allowInsecureHooks` in the baseline PSP.  Pro: simple!
4) NEW IDEA: go through the act of CSI migration. Pro: removes gitRepo from kubelet entirely.  Con: longer process.

**Comment by vinayakankugoyal** [comment]
@thockin

I started a doc to capture some of the ideas discussed here and in sg-arch. Eventually we can use it  for the KEP.

https://docs.google.com/document/d/1sUx65kAm1EMXpAhPycMApoNDTKAQR2vGP7yz88jKDSE/edit?usp=sharing

**Comment by saad-ali** [comment]
Thanks Tim for the follow up on this and @vinayakankugoyal for volunteering to move this forward. 
We'll work with Vinayak to move the KEP forward.

**Comment by raesene** [comment]
Just a quick question on the current status of security exposure via `gitrepo` volumes. My understanding was that after the fixes put in place for [CVE-2024-10220](https://github.com/kubernetes/kubernetes/issues/128885) there wasn't currently a risk of users with rights to create pods being able to execute commands on the node as root.

Reading the discussions on this, is there still a way for someone creating a pod to use this to get command execution via git hooks? I was guessing there might be as we're discussing the idea of having a feature to allow cluster-admins to disable git hooks. But I wasn't sure if that's a current exposure or just something we're worried about being possible in the future if another vulnerability is discovered.

**Comment by thockin** [comment]
I think this is the "real" resolution to that CVE.  Running git as kubelet is a large an unnecessary vector for attacks.  There are alternatives which are superior in pretty much every way.  Rather than play whack-a-mole forever, the KEP proposes to rip the bandaid off.

**Comment by raesene** [comment]
@thockin oh yeah I agree in terms of removing the plugin altogether, that's definitely (IMO) the right way to go. The bit I was a bit confused about was the `enableInsecureHooks` flag option. That made me think that in the current setup it's still possible for someone creating a pod to get the Kubelet to run a hook script (after the patch for the CVE-2024-10220).

I'm not that experienced with git hooks, so wasn't sure if that was a possibility or I was missing something :)

**Comment by thockin** [comment]
I don't think there was a patch, this is the reaction to the CVE (plus the VAP that was published).  Did I miss a patch?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/124531 and backports addressed the specific issue of directory depth nesting to address that CVE. They did not prevent use of repos with hooks.

**Comment by thockin** [comment]
Ahh, right.  Thank you

**Comment by raesene** [comment]
@liggitt Just checking, my understanding of git hooks was that they're not copied from source repositories during a git clone operation, they're purely local, with the only work-around being a git config setting `hooksPath` that specifies them at a different location so that they can be stored and transmitted as part of a clone operation. 

So I wasn't too clear if there's a case at the moment where the Kubelet could execute a hook script when setting up a gitRepo volume?

**Comment by liggitt** [comment]
> [@liggitt](https://github.com/liggitt) Just checking, my understanding of git hooks was that they're not copied from source repositories during a git clone operation, they're purely local, with the only work-around being a git config setting `hooksPath` that specifies them at a different location so that they can be stored and transmitted as part of a clone operation.
> 
> So I wasn't too clear if there's a case at the moment where the Kubelet could execute a hook script when setting up a gitRepo volume?

I don't really know the details of git / hook / kubelet behavior, and what the directory level gap was that the previous fix closed, sorry.

**Comment by raesene** [comment]
Hi All, I noticed that there's a new CVE relating to gitrepo volumes out now (https://github.com/kubernetes/kubernetes/issues/130786), and in the description it mentions that there will be no patch as gitrepo volumes are deprecated.

We seem to be in a slightly unusual situation where the feature is not patched as it's deprecated but can't be immediately removed as it may still be in use. 

It feels like really it should either be so unused as to be removed immediately, or so in-use that it should be patched?

**Comment by thockin** [comment]
Rather than backporting, which is risky and still would be on-by-default (compat!), the KEP offers this ValidatingAdmissionPolicy for existing clusters:

```
apiVersion: admissionregistration.k8s.io/v1
vinayakankugoyal marked this conversation as resolved.
kind: ValidatingAdmissionPolicy
metadata:
  name: "no-gitrepo-volumes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["pods", "podtemplates", "replicationcontrollers"]
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments", "replicasets", "statefulsets", "daemonsets"]
    - apiGroups:   ["batch"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["jobs", "cronjobs"]
  validations:
    - expression: |-
        object.kind != 'Pod' ||
        !object.spec.?volumes.orValue([]).exists(v, has(v.gitRepo))
      message: "gitRepo volumes are not allowed."
    - expression: |-
        object.kind != 'PodTemplate' ||
        !object.template.spec.?volumes.orValue([]).exists(v, has(v.gitRepo))
      message: "gitRepo volumes are not allowed."
    - expression: |-
        !['Deployment','ReplicaSet','DaemonSet','StatefulSet','Job', 'ReplicationController'].exists(kind, object.kind == kind) ||
        !object.spec.template.spec.?volumes.orValue([]).exists(v, has(v.gitRepo))
      message: "gitRepo volumes are not allowed."
    - expression: |-
        object.kind != 'CronJob' ||
        !object.spec.jobTemplate.spec.template.spec.?volumes.orValue([]).exists(v, has(v.gitRepo))
      message: "gitRepo volumes are not allowed."
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "no-gitrepo-volumes"
spec:
  policyName: "no-gitrepo-volumes"
  validationActions:
  - Deny
```

This lets cluster admins take action at their own pace.
