### ISSUE TITLE
scheduler postFilter plugin will not be executed

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#125951]
### What happened?

```
package plugin

import (
    "context"
    "fmt"
    "k8s.io/kubernetes/pkg/scheduler/framework"
     "k8s.io/apimachinery/pkg/runtime"
    v1 "k8s.io/api/core/v1"
)

const Name = "MyPostFilterPlugin"

type MyPostFilterPlugin struct{}

func (pl *MyPostFilterPlugin) Name() string {
    return Name
}

func (pl *MyPostFilterPlugin) PostFilter(ctx context.Context, state *framework.CycleState, pod *v1.Pod,  nodeToStatusMap framework.NodeToStatusMap) (*framework.PostFilterResult, *framework.Status) {
    fmt.Println("PostFilter function called")  // 新增日志
    filteredNodes := make([]string, 0, len(nodeToStatusMap))
    for nodeName := range nodeToStatusMap {
        filteredNodes = append(filteredNodes, nodeName)
    }
    
    // Log the details of the filtered nodes
    fmt.Printf("PostFilter: Pod %s/%s, filtered nodes: %d\n", pod.Namespace, pod.Name, len(filteredNodes))


    if len(filteredNodes) > 0 {
        return &framework.PostFilterResult{}, framework.NewStatus(framework.Success, "Retrying scheduling")
    }
    // If no nodes are available, return Unschedulable status
    return nil, framework.NewStatus(framework.Unschedulable, "No suitable nodes found")
}

func New(_ runtime.Object, _ framework.Handle) (framework.Plugin, error) {
    return &MyPostFilterPlugin{}, nil
}

var _ framework.PostFilterPlugin = &MyPostFilterPlugin{}
```

```
package main

import (
    "k8s.io/kubernetes/cmd/kube-scheduler/app"
    mypostfilter "myPostFilterPlugin/plugin"

    "k8s.io/component-base/logs"
)

func main() {
    command := app.NewSchedulerCommand(
        app.WithPlugin(mypostfilter.Name, mypostfilter.New),
    )
    logs.InitLogs()
    defer logs.FlushLogs()

    if err := command.Execute(); err != nil {
        panic(err)
    }
}
```

```
---
# Source: scheduler-plugins/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-scheduler
  namespace: kube-system
---
# Source: scheduler-plugins/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: default-scheduler
        plugins:
          postFilter:
            enabled:
            - name: MyPostFilterPlugin
---
# Source: scheduler-plugins/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-scheduler
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create"]
- apiGroups: ["coordination.k8s.io"]
  resourceNames: ["kube-scheduler"]
  resources: ["leases"]
  verbs: ["get", "update"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["create"]
- apiGroups: [""]
  resourceNames: ["kube-scheduler"]
  resources: ["endpoints"]
  verbs: ["get", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get", "list", "watch", "update", patch]
- apiGroups: [""]
  resources: ["bindings", "pods/binding"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch", "update"]
- apiGroups: [""]
  resources: ["replicationcontrollers", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps", "extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes", "storageclasses" , "csidrivers" , "csistoragecapacities"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["topology.node.k8s.io"]
  resources: ["noderesourcetopologies"]
  verbs: ["get", "list", "watch"]
---
# Source: scheduler-plugins/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-scheduler
subjects:
- kind: ServiceAccount
  name: default-scheduler
  namespace: kube-system
---
# Source: scheduler-plugins/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sched-plugins::extension-apiserver-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: default-scheduler
  namespace: kube-system
---
# Source: scheduler-plugins/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
  name: default-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
    spec:
      serviceAccountName: default-scheduler
      containers:
      - command:
        - /bin/my-scheduler
        - --config=/etc/kubernetes/scheduler-config.yaml
        - --v=2
        image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/my-scheduler:v5
        imagePullPolicy: Always  
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: scheduler-plugins-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts:
        - name: scheduler-config
          mountPath: /etc/kubernetes
          readOnly: true
      hostNetwork: false
      hostPID: false
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
```

logs:
I0708 08:58:32.444142       1 leaderelection.go:255] successfully acquired lease kube-system/kube-scheduler

I0708 08:59:15.417973       1 schedule_one.go:252] "Successfully bound pod to node" pod="default/test-pod" node="k8s-worker03" evaluatedNodes=6 feasibleNodes=3

### What did you expect to happen?

execute postfilter logic

### How can we reproduce it (as minimally and precisely as possible)?

appy the yaml

### Kubernetes version

<details>

[root@k8s-master03 ~]# kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0
</details>

### Cloud provider

<details>
wmware workstation
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
