### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Infeasible resize is actuated by restarting container

### ISSUE THREAD

**Issue by hshiina** [kubernetes/kubernetes#126033]
### What happened?

If a container is restarted along with an exit while its resizing is stuck in `Infeasible` or `Deferred`, the unacceptable resizing is actuated:
1. Request an infeasible resize (exceeds node allocatable cpu):
    ```
   $ kubectl patch pod resize-pod --patch '{"spec":{"containers":[{"name":"resize-container", "resources":{"requests":{"cpu":"100"}, "limits":{"cpu":"100"}}}]}}'
   pod/resize-pod patched

    ```
2. Kill the container manually (`restartPolicy` is `Always`):
   ```
   $ kubectl exec resize-pod -- kill 1
   ```
3. Then, it looks still stuck in `Infeasible` or `Deferred` on the API pod status. However, the cgroup of the container is configured as requested:
   ```
   $ kubectl get pod resize-pod -o jsonpath='{.status.resize}'
   Infeasible
   ```
   ```
   $ kubectl exec resize-pod -- cat /sys/fs/cgroup/cpu.max
   10000000 100000
   # 10000000 = newLimit(100) * 1000mCPU * period(100000) / 1000mCPU
   ```
   ```
   $ kubectl exec resize-pod -- cat /sys/fs/cgroup/cpu.weight
   3906
   # 3906 = ((newRequest(100) * 1000mCPU * SharesPerCPU(1024) / 1000mCPU) - 2 ) * 9999 / 262142
   ```

However, it does not seem that this issue affects actual resource consumption. Because the pod cgroup is not updated in this case, the container resource will keep limited. In addition, since `AllocatedResources` in the container is not updated, this infeasible resizing will not affect the pod resource calculation of the scheduler.

### What did you expect to happen?

This killed container is restarted with the old spec.

### How can we reproduce it (as minimally and precisely as possible)?

1. Enable `InPlacePodVerticalScaling`.
2. Create a pod whose restartPolicy is `Always`:
    <details>

   ```
   apiVersion: v1
   kind: Pod
   metadata:
     creationTimestamp: null
     labels:
       run: resize-pod
     name: resize-pod
   spec:
     containers:
     - image: busybox
       name: resize-container
       command:
         - sh
         - -c
         - trap "exit 0" SIGTERM; while true; do sleep 1; done
       resources:
         requests:
           cpu: 200m
           memory: 200Mi
         limits:
           cpu: 200m
           memory: 200Mi
       resizePolicy:
       - resourceName: cpu
         restartPolicy: NotRequired
       - resourceName: memory
         restartPolicy: NotRequired
     restartPolicy: Always
   ```

    </details>
3. Request an infeasible resize:
   ```
   kubectl patch pod resize-pod --patch '{"spec":{"containers":[{"name":"resize-container", "resources":{"requests":{"cpu":"100"}, "limits":{"cpu":"100"}}}]}}'
   ```
4. Kill the container:
   ```
   kubectl exec resize-pod -- kill 1
   ```

   

### Anything else we need to know?

By executing `kubectl get --watch`, we can see the resized status in a moment:
```
$ kubectl get pod resize-pod -o jsonpath='spec: {.spec.containers[0].resources}{"\nallocatedResources: "}{.status.containerStatuses[0].allocatedResources}{"\nstatus: "}{.status.containerStatuses[0].resources}{"\nresize: "}{.status.resize}{"\n"}' -w
spec: {"limits":{"cpu":"100","memory":"200Mi"},"requests":{"cpu":"100","memory":"200Mi"}}
allocatedResources: {"cpu":"200m","memory":"200Mi"}
status: {"limits":{"cpu":"100","memory":"200Mi"},"requests":{"cpu":"100","memory":"200Mi"}}  # <- See this line
resize: 
spec: {"limits":{"cpu":"100","memory":"200Mi"},"requests":{"cpu":"100","memory":"200Mi"}}
allocatedResources: {"cpu":"200m","memory":"200Mi"}
status: {"limits":{"cpu":"200m","memory":"200Mi"},"requests":{"cpu":"200m","memory":"200Mi"}}
resize: Infeasible
```

The resized pod status is set here:
https://github.com/kubernetes/kubernetes/blob/37f733a657ef71d66177d00f9b7d47ec507dedd3/pkg/kubelet/kubelet.go#L1802
However, the pod status is overwritten with an old pod status immediately here:
https://github.com/kubernetes/kubernetes/blob/37f733a657ef71d66177d00f9b7d47ec507dedd3/pkg/kubelet/kubelet.go#L2820

This issue is mentioned in another issue: https://github.com/kubernetes/kubernetes/issues/125205#issuecomment-2143532151

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.6
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```
</details>

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
