### ISSUE TITLE
Can only access pod nodePort accessible only from the node where the pod is running

### ISSUE THREAD

**Issue by BeehiveSystems** [kubernetes/kubernetes#126065]
### What happened?

I built a brand new Kubernetes cluster on Rocky 9 with one control-plane and two workers. I deployed a sample Nginx deployment and service which serves a simple index.html page on port 30081 using a nodePort in the service file. I can curl the node that is running the pod and see the index.html, but not the other two. The issue moves around when draining nodes to move the pod around. Firewalld is disabled on all 3 nodes.

### What did you expect to happen?

I expected to be able to curl mynode1:30081 or mynode2:30081 and get an answer, not just mynode3:30081 where the pod is located.

### How can we reproduce it (as minimally and precisely as possible)?

Build a new Kubernetes cluster on Rocky 9, deploy Flannel CNI, deploy the following service and deployment.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-demo
          items:
          - key: index.html
            path: index.html
```

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
  type: NodePort
  externalTrafficPolicy: Cluster
```

### Anything else we need to know?

/etc/sysctl.d/k8s.conf
```
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2
```

</details>

### Cloud provider

<details>
On-prem vSphere.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
$ uname -a
Linux kube1-dev.home.REDACTED.io 5.14.0-427.22.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 19 17:35:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
Deployed with my own Salt state. 
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Flannel 0.25.4.
</details>
