### ISSUE TITLE
JobTemplate validation bug: OnExitCodes should be an optional field for PodFailurePolicyRule

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes/kubernetes#126040]
### What happened?

[OnExitCodes field should be optional](https://github.com/kubernetes/kubernetes/blob/60862c98a4c0bcbc351b076714108d364883b5f7/staging/src/k8s.io/api/batch/v1/types.go#L238) for a PodFailurePolicyRule. 

However, when trying to create a JobSet programmatically with a JobTemplate that defines a PodFailurePolicy rule for failing a job immediately if the failed pod had condition DisruptionTarget, I get a validation error indicating that `OnExitCodes` cannot be null. I've tried using both `k8s.io/api v0.29.4` and `k8s.io/api v0.30.2` (with matching versions for k8s.io/apimachinery package as well).

Error:
```
$ k apply -f examples/simple/failure-policy.yaml 
The JobSet "failurepolicy" is invalid: 
* spec.replicatedJobs[0].template.spec.podFailurePolicy.rules[0].onExitCodes: Invalid value: "null": spec.replicatedJobs[0].template.spec.podFailurePolicy.rules[0].onExitCodes in body must be of type object: "null"
* <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
```

JobSet spec:

```yaml
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: failurepolicy
spec:
  replicatedJobs:
  - name: leader
    replicas: 1
    template:
      spec:
        # Set backoff limit to 0 so job will immediately fail if any pod fails.
        backoffLimit: 0
        completions: 2
        parallelism: 2
        template:
          spec:
            restartPolicy: Never
            containers:
            - name: leader
              image: bash:latest
              command:
              - bash
              - -xc
              - |
                for i in $(seq 1 1000)
                do
                  echo "$i"
                  sleep 1
                done
        podFailurePolicy:
          rules:
          - action: FailJob
            onPodConditions:
            - type: DisruptionTarget
```

### What did you expect to happen?

JobTemplate passes validation.

### Repro steps using k8s.io/api v0.29.4

1. Install JobSet:

```VERSION=v0.5.2
kubectl apply --server-side -f https://github.com/kubernetes-sigs/jobset/releases/download/$VERSION/manifests.yaml
```

2. Try applying example JobSet in the description of this issue.

```kubectl apply -f jobset-from-github-issue.yaml```

### Repro steps using k8s.io/api v0.30.2

1. Clone JobSet: `git clone https://github.com/kubernetes-sigs/jobset`
2. Upgrade k8s.io/api and k8s.io/apimachinery

```
go get -u k8s.io/api
go get -u k8s.io/apimachinery
go mod tidy
```

3. Try applying example JobSet in the description of this issue.

```kubectl apply -f jobset-from-github-issue.yaml```

### Kubernetes version

1.30 (tests on a kind cluster using kindest/node:v1.30.0)

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
