### ISSUE TITLE
CEL validation can cause APIServer to crashloop

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#126133]
### What happened?

We observed a scenario that can cause APIServer to crash due to a CEL validation issue for CRD.
There's an edge case that when a CRD schema is updated after a CR instance is created, CRD finalizer can cause APIServer to crash when the CRD is being deleted.
Updating the CRD schema after some CRs are created can be problematic, but it should fail gracefully instead of crash.

<details>
<summary>
Sample stack trace
</summary>

```
http: panic serving 10.44.11.12:52946: runtime error: invalid memory address or nil pointer dereference

goroutine 100444784 [running]:

net/http.(*conn).serve.func1()

    net/http/server.go:1868 +0xb9

panic({0x42d7a80?, 0x7a07d50?})

    runtime/panic.go:920 +0x270

k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0xc07f113608, 0x1, 0xfffffffe?})

    k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:56 +0xcd

panic({0x42d7a80?, 0x7a07d50?})

    runtime/panic.go:914 +0x21f

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithAudit.func6.1.1()

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/audit.go:84 +0x25

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithAudit.func6.1()

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/audit.go:93 +0x23f

panic({0x42d7a80?, 0x7a07d50?})

    runtime/panic.go:914 +0x21f

k8s.io/apiserver/pkg/cel.(*DeclType).IsObject(...)

    k8s.io/apiserver@v0.0.0/pkg/cel/types.go:223

k8s.io/apiserver/pkg/cel.(*DeclType).MaybeAssignTypeName(0x0, {0xc05c767bf0?, 0x0?})

    k8s.io/apiserver@v0.0.0/pkg/cel/types.go:117 +0x2d

k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.prepareEnvSet(0x418768?, 0xc07f113de0?)

    k8s.io/apiextensions-apiserver@v0.0.0/pkg/apiserver/schema/cel/compilation.go:150 +0x45

k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.Compile(0xc00f930420, 0x0, 0x23701c7?, 0xc07f114058?, {0x5494948, 0x4ef9790})

    k8s.io/apiextensions-apiserver@v0.0.0/pkg/apiserver/schema/cel/compilation.go:130 +0x11a

k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.validator(0xc00f930420, 0x0, 0x0, 0xc07f114290?)

    k8s.io/apiextensions-apiserver@v0.0.0/pkg/apiserver/schema/cel/validation.go:94 +0xc9

k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.validator(0xc04c9bbc30, 0x0, 0xc096d67080, 0x8?)

    k8s.io/apiextensions-apiserver@v0.0.0/pkg/apiserver/schema/cel/validation.go:98 +0x11b

k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.validator(0xc04c9bbad0, 0x0, 0xc096d67100, 0x4?)

    k8s.io/apiextensions-apiserver@v0.0.0/pkg/apiserver/schema/cel/validation.go:120 +0x358

k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.validator(0xc00f930210, 0x1, 0xc096d67280, 0xc03ea2c340?)

    k8s.io/apiextensions-apiserver@v0.0.0/pkg/apiserver/schema/cel/validation.go:120 +0x358

k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.NewValidator(0xc00f930210, 0x83?, 0x23?)

    k8s.io/apiextensions-apiserver@v0.0.0/pkg/apiserver/schema/cel/validation.go:86 +0x85

k8s.io/apiextensions-apiserver/pkg/registry/customresource.NewStrategy({_, _}, _, {{_, _}, {_, _}, {_, _}}, {0x548eb18, ...}, ...)

    k8s.io/apiextensions-apiserver@v0.0.0/pkg/registry/customresource/strategy.go:69 +0xb6

k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).getOrCreateServingInfoFor(0xc00146d810, {0xc04b5b8c90?, 0x1a?}, {0xc08114f360, 0x1a})

    k8s.io/apiextensions-apiserver@v0.0.0/pkg/apiserver/customresource_handler.go:802 +0x18da

k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).ServeHTTP(0xc00146d810, {0x549cd90, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiextensions-apiserver@v0.0.0/pkg/apiserver/customresource_handler.go:295 +0x905

k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc006a54380, {0x549cd90, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiserver@v0.0.0/pkg/server/mux/pathrecorder.go:249 +0x41d

k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc0b54960c4?, {0x549cd90?, 0xc053b3c4b0?}, 0xc0158c6b00?)

    k8s.io/apiserver@v0.0.0/pkg/server/mux/pathrecorder.go:235 +0x66

k8s.io/apiserver/pkg/server.director.ServeHTTP({{0x4c9aa69?, 0x555a555569155555?}, 0xc00138d320?, 0xc00016b8f0?}, {0x549cd90, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiserver@v0.0.0/pkg/server/handler.go:154 +0x6f1

k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc012ce2c40, {0x549cd90, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiserver@v0.0.0/pkg/server/mux/pathrecorder.go:255 +0x56a

k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc0b54960c4?, {0x549cd90?, 0xc053b3c4b0?}, 0x4fc39e?)

    k8s.io/apiserver@v0.0.0/pkg/server/mux/pathrecorder.go:235 +0x66

k8s.io/apiserver/pkg/server.director.ServeHTTP({{0x4c76d39?, 0xc011a13d40?}, 0xc0015838c0?, 0xc000317340?}, {0x549cd90, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiserver@v0.0.0/pkg/server/handler.go:154 +0x6f1

k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc0745bd0b0?, {0x549cd90?, 0xc053b3c4b0?}, 0x23?)

    k8s.io/kube-aggregator@v0.0.0/pkg/apiserver/handler_proxy.go:112 +0x152

k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc04b5b6640, {0x549cd90, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiserver@v0.0.0/pkg/server/mux/pathrecorder.go:249 +0x41d

k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc0b54960c4?, {0x549cd90?, 0xc053b3c4b0?}, 0x1?)

    k8s.io/apiserver@v0.0.0/pkg/server/mux/pathrecorder.go:235 +0x66

k8s.io/apiserver/pkg/server.director.ServeHTTP({{0x4c7a111?, 0x40e74c?}, 0xc00357dd40?, 0xc0041438f0?}, {0x549cd90, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiserver@v0.0.0/pkg/server/handler.go:154 +0x6f1

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.TrackCompleted.trackCompleted.func21({0x549cd90?, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filterlatency/filterlatency.go:110 +0x177

net/http.HandlerFunc.ServeHTTP(0x54ad4d0?, {0x549cd90?, 0xc053b3c4b0?}, 0x4?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/endpoints/filters.withAuthorization.func1({0x549cd90, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/authorization.go:78 +0x639

net/http.HandlerFunc.ServeHTTP(0x8a62a0?, {0x549cd90?, 0xc053b3c4b0?}, 0x3?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x549cd90, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filterlatency/filterlatency.go:84 +0x192

net/http.HandlerFunc.ServeHTTP(0x490a1c0?, {0x549cd90?, 0xc053b3c4b0?}, 0x5467f10?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.TrackCompleted.trackCompleted.func22({0x549cd90?, 0xc053b3c4b0}, 0xc07aaa0600)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filterlatency/filterlatency.go:110 +0x177

net/http.HandlerFunc.ServeHTTP(0x54ad4d0?, {0x549cd90?, 0xc053b3c4b0?}, 0x5467f10?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server/filters.(*priorityAndFairnessHandler).Handle(0xc003fdec30, {0x549cd90?, 0xc053b3c4b0}, 0xc07aaa0400)

    k8s.io/apiserver@v0.0.0/pkg/server/filters/priority-and-fairness.go:271 +0x9ff

net/http.HandlerFunc.ServeHTTP(0x8a62a0?, {0x549cd90?, 0xc053b3c4b0?}, 0x3?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x549cd90, 0xc053b3c4b0}, 0xc07aaa0400)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filterlatency/filterlatency.go:84 +0x192

net/http.HandlerFunc.ServeHTTP(0x490a1c0?, {0x549cd90?, 0xc053b3c4b0?}, 0x5467f10?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.TrackCompleted.trackCompleted.func23({0x549cd90?, 0xc053b3c4b0}, 0xc07aaa0400)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filterlatency/filterlatency.go:110 +0x177

net/http.HandlerFunc.ServeHTTP(0xc0158c80a8?, {0x549cd90?, 0xc053b3c4b0?}, 0xc0901c0020?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithImpersonation.func4({0x549cd90, 0xc053b3c4b0}, 0xc082fc4700)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/impersonation.go:182 +0x1902

net/http.HandlerFunc.ServeHTTP(0x8a62a0?, {0x549cd90?, 0xc053b3c4b0?}, 0x0?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x549cd90, 0xc053b3c4b0}, 0xc082fc4700)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filterlatency/filterlatency.go:84 +0x192

net/http.HandlerFunc.ServeHTTP(0x490a1c0?, {0x549cd90?, 0xc053b3c4b0?}, 0x5467f10?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.TrackCompleted.trackCompleted.func24({0x549cd90?, 0xc053b3c4b0}, 0xc082fc4700)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filterlatency/filterlatency.go:110 +0x177

net/http.HandlerFunc.ServeHTTP(0xc000d13c80?, {0x549cd90?, 0xc053b3c4b0?}, 0x54ad4d0?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithAudit.func6({0x54a9600, 0xc0672f27e0}, 0x547c9e0?)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/audit.go:115 +0x395

net/http.HandlerFunc.ServeHTTP(0x8a62a0?, {0x54a9600?, 0xc0672f27e0?}, 0x0?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x54a9600, 0xc0672f27e0}, 0xc082fc4700)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filterlatency/filterlatency.go:84 +0x192

net/http.HandlerFunc.ServeHTTP(0x490a1c0?, {0x54a9600?, 0xc0672f27e0?}, 0x5467f10?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.TrackCompleted.trackCompleted.func26({0x54a9600?, 0xc0672f27e0}, 0xc082fc4700)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filterlatency/filterlatency.go:110 +0x177

net/http.HandlerFunc.ServeHTTP(0x54ad4d0?, {0x54a9600?, 0xc0672f27e0?}, 0x545fde0?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/endpoints/filters.withAuthentication.func1({0x54a9600, 0xc0672f27e0}, 0xc082fc4700)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/authentication.go:120 +0x7e5

net/http.HandlerFunc.ServeHTTP(0x54ad4d0?, {0x54a9600?, 0xc0672f27e0?}, 0x5467f10?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x54a9600, 0xc0672f27e0}, 0xc07c2ffe00)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filterlatency/filterlatency.go:94 +0x37a

net/http.HandlerFunc.ServeHTTP(0xc07c2ffe00?, {0x54a9600?, 0xc0672f27e0?}, 0xc00be6a100?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc003ffa450, {0x54a9600, 0xc0672f27e0}, 0xc0b54960c0?)

    k8s.io/apiserver@v0.0.0/pkg/server/filters/timeout.go:87 +0x346

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithRequestDeadline.withRequestDeadline.func27({0x54a9600, 0xc0672f27e0}, 0xc07c2ffe00)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/request_deadline.go:65 +0x3f3

net/http.HandlerFunc.ServeHTTP(0x54ad4d0?, {0x54a9600?, 0xc0672f27e0?}, 0x47eef40?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithWaitGroup.withWaitGroup.func28({0x54a9600, 0xc0672f27e0}, 0xc0158c8d98?)

    k8s.io/apiserver@v0.0.0/pkg/server/filters/waitgroup.go:65 +0x1cc

net/http.HandlerFunc.ServeHTTP(0xc000081ed0?, {0x54a9600?, 0xc0672f27e0?}, 0x842718?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server/filters.(*goaway).ServeHTTP(0xc003ffd920, {0x54a9600, 0xc0672f27e0}, 0xc07c2ffe00)

    k8s.io/apiserver@v0.0.0/pkg/server/filters/goaway.go:72 +0x142

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithWarningRecorder.func13({0x54a9600?, 0xc0672f27e0}, 0xc053b3c090?)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/warning.go:35 +0xc6

net/http.HandlerFunc.ServeHTTP(0x4a10120?, {0x54a9600?, 0xc0672f27e0?}, 0x4c81012?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithCacheControl.func14({0x54a9600, 0xc0672f27e0}, 0x0?)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/cachecontrol.go:31 +0xa7

net/http.HandlerFunc.ServeHTTP(0xc0833e5e50?, {0x54a9600?, 0xc0672f27e0?}, 0xc0158c8f20?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithHTTPLogging.WithLogging.withLogging.func34({0x54a9600, 0xc0672f27e0}, 0x1?)

    k8s.io/apiserver@v0.0.0/pkg/server/httplog/httplog.go:111 +0x95

net/http.HandlerFunc.ServeHTTP(0xc0af0b1950?, {0x54a9600?, 0xc0672f27e0?}, 0xc03ea2c340?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/endpoints/filters.WithTracing.func1({0x54a9600?, 0xc0672f27e0?}, 0xc07c2ffd00?)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/traces.go:42 +0x222

net/http.HandlerFunc.ServeHTTP(0x54ad4d0?, {0x54a9600?, 0xc0672f27e0?}, 0x5467f10?)

    net/http/server.go:2136 +0x29

go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP(0xc004dd6160, {0x5498f60?, 0xc04331cc40}, 0xc07c2ffb00, {0x5478720, 0xc003ffa4e0})

    go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.44.0/handler.go:217 +0x1202

go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1({0x5498f60?, 0xc04331cc40?}, 0x5?)

    go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.44.0/handler.go:81 +0x35

net/http.HandlerFunc.ServeHTTP(0x54ad4d0?, {0x5498f60?, 0xc04331cc40?}, 0xc07c2ffb00?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithLatencyTrackers.func16({0x5498f60?, 0xc04331cc40}, 0xc07c2ffb00?)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/webhook_duration.go:47 +0x172

net/http.HandlerFunc.ServeHTTP(0xc07c2ffa00?, {0x5498f60?, 0xc04331cc40?}, 0x7f22b516b5b8?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithRequestInfo.func17({0x5498f60, 0xc04331cc40}, 0xc07c2ffa00?)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/requestinfo.go:39 +0x118

net/http.HandlerFunc.ServeHTTP(0xc07c2ff900?, {0x5498f60?, 0xc04331cc40?}, 0x80eb343ab745?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithRequestReceivedTimestamp.withRequestReceivedTimestampWithClock.func31({0x5498f60, 0xc04331cc40}, 0x4106d3?)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/request_received_time.go:38 +0xaf

net/http.HandlerFunc.ServeHTTP(0x150?, {0x5498f60?, 0xc04331cc40?}, 0x7f226329e938?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithMuxAndDiscoveryComplete.func18({0x5498f60?, 0xc04331cc40?}, 0xc07c2ff900?)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/mux_discovery_complete.go:52 +0xd5

net/http.HandlerFunc.ServeHTTP(0xc000096400?, {0x5498f60?, 0xc04331cc40?}, 0xc0158c9a18?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithPanicRecovery.withPanicRecovery.func32({0x5498f60?, 0xc04331cc40?}, 0xc053b3c090?)

    k8s.io/apiserver@v0.0.0/pkg/server/filters/wrap.go:74 +0xa6

net/http.HandlerFunc.ServeHTTP(0x54ad4d0?, {0x5498f60?, 0xc04331cc40?}, 0xc06de83470?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithAuditInit.withAuditInit.func33({0x5498f60, 0xc04331cc40}, 0xc0158c9b18?)

    k8s.io/apiserver@v0.0.0/pkg/endpoints/filters/audit_init.go:63 +0x12c

net/http.HandlerFunc.ServeHTTP(0xc0158c9b68?, {0x5498f60?, 0xc04331cc40?}, 0x0?)

    net/http/server.go:2136 +0x29

k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0x7a85a00?, {0x5498f60?, 0xc04331cc40?}, 0xc0158c9b50?)

    k8s.io/apiserver@v0.0.0/pkg/server/handler.go:189 +0x25

net/http.serverHandler.ServeHTTP({0xc0836e76b0?}, {0x5498f60?, 0xc04331cc40?}, 0x6?)

    net/http/server.go:2938 +0x8e

net/http.(*conn).serve(0xc0a9d997a0, {0x54ad4d0, 0xc00ccbda70})

    net/http/server.go:2009 +0x5f4

created by net/http.(*Server).Serve in goroutine 2661

    net/http/server.go:3086 +0x5cb
```

</details>

### What did you expect to happen?

APIServer not to crash

### How can we reproduce it (as minimally and precisely as possible)?

Step 1:
```
$ kubectl create -f crd.yaml
```

<details>
<summary>
Content of crd.yaml
</summary>

```yaml
# crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shirts.stable.example.com
spec:
  group: stable.example.com
  names:
    plural: shirts
    singular: shirt
    kind: Shirt
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                backend:
                  items:
                    properties:
                      replicas:
                        type: integer
                    required:
                      - replicas
                    type: object
                    x-kubernetes-validations:
                      - message: Replicas can be set in beetwen 0 to 10.
                        rule: 0 <= self.replicas && self.replicas <= 10
                  type: array
              type: object
          type: object
      served: true
      storage: true
```
</details>

Step 2:
```
$ kubectl create -f cr.yaml
```

<details>
<summary>
Content of cr.yaml
</summary>

```yaml
# cr.yaml
apiVersion: stable.example.com/v1
kind: Shirt
metadata:
  name: test-cr
spec :
  backend:
    - replicas: 8
```

</details>

Step 3:

```
$ kubectl replace -f crd2.yaml
```

<details>
<summary>
Content of crd2.yaml
</summary>

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shirts.stable.example.com
spec:
  group: stable.example.com
  names:
    plural: shirts
    singular: shirt
    kind: Shirt
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                backend:
                  description: Backend service tracking parameters
                  items:
                    properties:
                      replicas:
                        type: integer
                    required:
                      - replicas
                    type: object
                    x-kubernetes-validations:
                      - message: Replicas can be set in beetwen 0 to 10.
                        rule: 0 <= self.replicas && self.replicas <= 10
                  type: object  # <========= changed
              type: object
          type: object
      served: true
      storage: true
```

</details>

Step 4:
```
$ kubectl delete -f crd.yaml
```

### Kubernetes version

<details>

At least 1.29 and 1.30. 

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
