### ISSUE TITLE
Projected secrets mounted with a subPath disappear after the secret is updated.

### ISSUE THREAD

**Issue by hdermois** [kubernetes/kubernetes#126112]
### What happened?

I want to prevent kubernetes from automatically updating my mounted secrets. I project my secrets in a volume and mount them with a subpath to unlink them. In the configuration I see the files I expect and they are unlinked. After I update the secret I mounted the files disappear from the pod.

### What did you expect to happen?

I expect nothing to happen. I have unlinked the secrets and after a update of the secret I expect my pod to be unaffected.

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: Pod
metadata:
  name: mypod-no-update
spec:
  containers:
  - name: mycontainer
    image: busybox
    command: ['sh', '-c', 'sleep 3000']
    volumeMounts:
    - name: mysecrets
      mountPath: /etc/secret-volume
      subPath: cert
      # Optional: You can specify read-only here
      readOnly: true
  volumes:
  - name: mysecrets
    projected:
      sources:
      - secret:
          name: mysecret
          items:
            - key: username
              path: cert/mysecret.txt
          # Optional: You can specify defaultMode here, which is reflected in 
          # the file permissions for the files created from the secret
---
apiVersion: v1
data:
  password: bXlwYXNzd29yZA==
  username: bXl1c2Vy
kind: Secret
metadata:
  name: mysecret
type: Opaque
```

Apply these resources check if the file is present in the pod. Edit the secret and see that file disappears.

### Anything else we need to know?

The functionality does work when you created a volume mount per file.

### Kubernetes version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4 and     v1.27.13+e709aa5

### Cloud provider

Locally and also tested on Openshift 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
</details

### Install tools

<details>
microk8s and openshift
</details>


### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.28
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

no

**Comment by chengjoey** [comment]
I can also reproduce this in kind:
```
kubectl get pod -o wide
NAME              READY   STATUS    RESTARTS   AGE   IP            NODE                 NOMINATED NODE   READINESS GATES
mypod-no-update   1/1     Running   0          28m   10.244.2.10   my-cluster-worker2   <none>           <none>
```
docker exec -it my-cluster-worker2 bash:
```
root@my-cluster-worker2:/# crictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID              POD
b1822bd8565bb       3fba0c87fcc8b       38 minutes ago      Running             mycontainer         0                   5dca62210a964       mypod-no-update
```
mount | grep b1822bd8565bb
```
overlay on /run/containerd/io.containerd.runtime.v2.task/k8s.io/b1822bd8565bbf3cb7b26911707f9b1018249fef66d5df5f9b19e07ecffc4a1a/rootfs type overlay (rw,relatime,lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/111/fs,upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/112/fs,workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/112/work)
```
ls secret path is empty:
```
root@my-cluster-worker2:/# ls /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/112/fs/etc/secret-volume/
root@my-cluster-worker2:/#
```

**Comment by Jerry-yz** [comment]
[official document](https://kubernetes.io/docs/concepts/storage/volumes/#secret)

**Comment by Jerry-yz** [comment]
A container using a Secret as a [subPath](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) volume mount will not receive Secret updates.

**Comment by chengjoey** [comment]
> A container using a Secret as a [subPath](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) volume mount will not receive Secret updates.

will not receive Secret updates, but will it also cause the loss of original files in pod?

**Comment by chengjoey** [comment]
updates:
The same can be reproduced in 1.26. Is this scenario expected?
i modify pkg/volume/projected/projected.goL186-191, skip running pod, there will be no file loss, but this is definitely not the right way
```
func (s *projectedVolumeMounter) SetUp(mounterArgs volume.MounterArgs) error {
	if s.pod.Status.Phase == v1.PodRunning {
		return nil
	}
	return s.SetUpAt(s.GetPath(), mounterArgs)
}
```

**Comment by Jerry-yz** [comment]
> > A container using a Secret as a [subPath](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) volume mount will not receive Secret updates.
> 
> will not receive Secret updates, but will it also cause the loss of original files in pod? and looks like it receive the secret update
> 
> ```
> root@my-cluster-worker2:/# cat /var/lib/kubelet/pods/e980d27e-40d8-4645-8a02-56e98a851d81/volumes/kubernetes.io~projected/mysecrets/cert/mysecret.txt
> mypassword
> ```
> 
> content about mysecret.txt from `myuser` to `mypassword` after i update secret and set `username` to `mypassword`

volumes and sub-volumes are different, can you show you resource yaml file content

**Comment by chengjoey** [comment]
> volumes and sub-volumes are different, can you show you resource yaml file content

yaml provided by the Author, just modified secret.data.username after the pod is running.:
```
apiVersion: v1
data:
  password: bXlwYXNzd29yZA==
  # after pod is running, change username to `bXlwYXNzd29yZA==`(mypassword)
  username: bXl1c2Vy
kind: Secret
metadata:
  name: mysecret
type: Opaque
```

**Comment by hdermois** [comment]
Hi Jerry,

What information do you need? @chengjoey Has been able to reproduce the behavior. I have the same question as Chenjoey, Is this the expected behavior? I expect the volume mount of the pod not to be updated. But I do not know if the complete removal of a volume mount can be seen as and update.

With kind regards,
Harm

**Comment by chengjoey** [comment]
after update secret, kubelet print this log:
```
Jul 17 06:37:08 minikube kubelet[294068]: I0717 06:37:08.420308  294068 reconciler_common.go:209] "Starting operationExecutor.MountVolume for volume \"mysecrets\" (UniqueName: \"kubernetes.io/projected/da0bebab-c33f-4ad7-87da-798ec1ce83b6-mysecrets\") pod \"mypod-no-update\" (UID: \"da0bebab-c33f-4ad7-87da-798ec1ce83b6\") Volume is already mounted to pod, but remount was requested." pod="default/mypod-no-update"
```
remountingLogStr is `Volume is already mounted to pod, but remount was requested`, maybe the volume should not be `remount required`

**Comment by chengjoey** [comment]
`AtomicWriter` should not remove OldTsDir if it's link `subpath`

**Comment by chengjoey** [comment]
@dims  could you please take a look when you have time

**Comment by chengjoey** [comment]
hi @hdermois , you can change it to the following way, so that subpath will not be disappeared:
```
apiVersion: v1
kind: Pod
metadata:
  name: mypod-no-update
spec:
  containers:
  - name: mycontainer
    image: busybox
    command: ['sh', '-c', 'sleep 3000']
    volumeMounts:
    - name: mysecrets
      # use filename
      mountPath: /etc/secret-volume/mysecret.txt
      subPath: mysecret.txt
      readOnly: true
  volumes:
  - name: mysecrets
    projected:
      sources:
      - secret:
          name: mysecret
          items:
            - key: username
               # use filename
               path: mysecret.txt
```
