### ISSUE TITLE
Get 502 [Request Entity Too Large] while add service

### ISSUE THREAD

**Issue by wb14123** [kubernetes/kubernetes#12624]
I get this error while add a service:

```
kubectl create -f mongo-svc.yaml
The Service "mongo-service" is invalid:spec.clusterIP: invalid value '': 502:  (unhandled http status [Request Entity Too Large] with body []) [0]
```

Here is the content of `mongo-svc.yaml`:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: adhoc-backend
spec:
  selector:
    name: mongo
    app: adhoc-backend
  ports:
    - port: 5000
      targetPort: 5000
```

And the kube-apiserver log is as this:

```
E0813 10:50:17.267182   13659 repair.go:67] unable to persist the updated service IP allocations: 502:  (unhandled http status [Request Entity Too Large] with body []) [0]
```

Then when I restart kube-apiserver, I always get this error and the master is not able to start:

```
F0813 11:07:12.447484    1408 controller.go:80] Unable to perform initial IP allocation check: unable to persist the updated service IP allocations: 502:  (unhandled http status [Request Entity Too Large] with body []) [0]
```

After I stop etcd and cleanup the dir `/infra0.etcd`, kube-apiserver could start again but still cannot add the service.

The versions are:

```
sudo /opt/bin/kube-apiserver --version
Kubernetes v1.0.1

curl -L http://127.0.0.1:4001/version
etcd 2.0.12
```
