### ISSUE TITLE
how to config nvidia driverName in dynamicResourceAllocation

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#126267]
### What happened?

```
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClass
metadata:
  name: nvidia-gpu
parametersRef:
  apiGroup: resource.k8s.io
  kind: ResourceClassParameters
  name: nvidia-gpu-class-param
  namespace: default
driverName: nvidia.com/gpu
suitableNodes:
  nodeSelectorTerms:
  - matchExpressions:
    - key: accelerator
      operator: In
      values:
      - nvidia-gpu
---
apiVersion: resource.x-k8s.io/v1alpha2
kind: ResourceClassParameters
metadata:
  name: nvidia-gpu-class-param
spec:
  vendorParameters:
  - driverName: nvidia.com/gpu
    parameters:
      resource: nvidia.com/gpu     
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaim
metadata:
  name: gpu-claim
spec:
  resourceClassName: nvidia-gpu
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: gpu-claim-template
spec:
  spec:
    allocationMode:
    resourceClassName: nvidia-gpu
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  schedulerName: my-scheduler
  containers:
  - name: gpu-container
    image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/cuda:11.7.1-base-ubi8
    resources:
      claims:
        - name: gpu-claim
    command: ["nvidia-smi"]
  resourceClaims:
    - name: gpu-claim
      source:
        #resourceClaimName: gpu-claim
        resourceClaimTemplateName: gpu-claim-template

```

Error from server (Invalid): error when creating "dynamic-res-nvidia.yaml": ResourceClass.resource.k8s.io "nvidia-gpu" is invalid: driverName: Invalid value: "nvidia.com/gpu": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

### What did you expect to happen?

apply ok

### How can we reproduce it (as minimally and precisely as possible)?

apply the yaml

### Kubernetes version

<details>

root@k8s-master01:~/k8s-core-teaching/scheduler# kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
</details>

### Cloud provider

<details>
pve 8
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 13567436138** [comment]
![image](https://github.com/user-attachments/assets/29eb7565-464f-45a8-ba2f-6a0679576d2b)
can not scheduler
with driverName nvidia.com

**Comment by 13567436138** [comment]
```
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClass
metadata:
  name: nvidia-gpu
parametersRef:
  apiGroup: resource.k8s.io
  kind: ResourceClassParameters
  name: nvidia-gpu-class-param
  namespace: default
driverName: nvidia.com
suitableNodes:
  nodeSelectorTerms:
  - matchExpressions:
    - key: accelerator
      operator: In
      values:
      - nvidia-gpu
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClassParameters
metadata:
  name: nvidia-gpu-class-param
vendorParameters:
- driverName: nvidia.com
  parameters:
    resource: nvidia.com/gpu     
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaim
metadata:
  name: gpu-claim
spec:
  resourceClassName: nvidia-gpu
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimTemplate
metadata:
  name: gpu-claim-template
spec:
  spec:
    allocationMode: WaitForFirstConsumer
    resourceClassName: nvidia-gpu
    parametersRef:
      apiGroup: resource.k8s.io
      kind: ResourceClaimParameters
      name: gpu-claim-template-params
---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaimParameters
metadata:
  name: gpu-claim-template-params
driverRequests:
- driverName: nvidia.com
  requests:
  - vendorParameters:
      nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  schedulerName: my-scheduler
  containers:
  - name: gpu-container
    image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/cuda:11.7.1-base-ubi8
    resources:
      claims:
        - name: gpu-claim
    command: ["nvidia-smi"]
  resourceClaims:
    - name: gpu-claim
      source:
        #resourceClaimName: gpu-claim
        resourceClaimTemplateName: gpu-claim-template

```

change to this got 
The ResourceClaimParameters "gpu-claim-template-params" is invalid: driverRequests[0].requests[0]: Required value: exactly one structured model field must be set

**Comment by googs1025** [comment]
/retitle how to config nvidia driverName in dynamicResourceAllocation

**Comment by Octopusjust** [comment]
> driverName

1. `driverName: nvidia.com/gpu` needs to comply with [RFC 1123](https://datatracker.ietf.org/doc/html/rfc1123) 
2. In the Kubernetes resource definition, you need to ensure that only one structured model field is set under the requests field. Like: 
```
driverRequests:
- driverName: nvidia.com
  requests:
    nvidia.com/gpu: "1"
```
more details : 
https://kubernetes.io/zh-cn/docs/concepts/scheduling-eviction/dynamic-resource-allocation/
https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4381-dra-structured-parameters

3. After completing the above steps, you can try again. The pod scheduling failure may be related to this.
