### ISSUE TITLE
IPVS backend active connections aren't distributed evenly

### ISSUE THREAD

**Issue by jslouisyou** [kubernetes/kubernetes#126378]
### What happened?

Hello Kubernetes Team,
I'm newbie about networks or `kube-proxy`, so I'd appreciate it if anyone could help me!

Recently I faced unbalanced network Tx traffic in all master nodes and I found that there were unbalance between the number of IPVS connection between `Services` exposed in k8s cluster and `kube-apiserver`.

This happened when any of `kube-apiserver` stopped or restarted, and `kube-proxy` seemed to re-established IPVS connections to alive `kube-apiserver` and this caused unbalance IPVS connections, in this case `MASTER2` was restarted, such as:
```
$ ipvsadm -ln | grep 10.233.0.1 -A 3
TCP  10.233.0.1:443 rr
  -> MASTER1:6443           Masq    1      13         0
  -> MASTER2:6443           Masq    1      2          0
  -> MASTER3:6443           Masq    1      12          0
```
as you can see, there is unbalance connection between all master nodes and this remains the save even after a long time.

Here's example of above situation in one of my cluster:
1. The number of IPVS backend connections still remains balanced with all `kube-apiserver` until then 00:30.
2. `kube-apiserver` restarted at 00:30, after then IPVS connections were changed and imbalance situation happened. This wasn't changed even if almost 16 hours elapsed.

![image](https://github.com/user-attachments/assets/3f0e2468-790f-4225-bf4a-ec2ed1031aed)

I'm wondering that:
* Why does this imbalance continue to persist?
* Is there a way to resolve this situation, such as modify `kube-proxy` configuration?

### What did you expect to happen?

When `kube-apiserver` stops:
1. `kube-proxy` will re-establish IPVS connections between `Service` and `kube-apiserver`.
4. `kube-proxy` will establish IPVS connection with alive `kube-apiserver`.

I expected that after `kube-apiserver` restarts and elapse several minutes and hours:
5. The number of IPVS connection in local node will be distributed evenly.

But IPVS connections are remaining same which I means that the number of IPVS connection is remaining also and there isn't significant changes after elapsed hours.

### How can we reproduce it (as minimally and precisely as possible)?

WIth deploying several `Services` (ensuring there are IPVS connections between `kube-apiserver` and node), kill or restart one of `kube-apiserver`.

### Anything else we need to know?

I'm using `IPVS` mode for `kube-proxy`. Here's the full configuration I'm using for `kube-proxy`:
```
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    bindAddressHardFail: false
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 5
    clusterCIDR: 10.0.0.0/12
    configSyncPeriod: 15m0s
    conntrack:
      maxPerCore: 32768
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    detectLocalMode: ""
    enableProfiling: false
    healthzBindAddress: 0.0.0.0:10256
    hostnameOverride: master01
    iptables:
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    ipvs:
      excludeCIDRs: []
      minSyncPeriod: 0s
      scheduler: rr
      strictARP: true
      syncPeriod: 30s
      tcpFinTimeout: 0s
      tcpTimeout: 0s
      udpTimeout: 0s
    kind: KubeProxyConfiguration
    metricsBindAddress: 0.0.0.0:10249
    mode: ipvs
    nodePortAddresses: []
    oomScoreAdj: -999
    portRange: ""
    showHiddenMetricsForVersion: ""
    udpIdleTimeout: 250ms
    winkernel:
      enableDSR: false
      networkName: ""
      sourceVip: ""
  kubeconfig.conf: |-
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://127.0.0.1:6443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```

### Kubernetes version

K8S v1.21.6
K8S v1.28.3

### Cloud provider

On-premise K8S cluster provisioned via `kubespray`

### OS version

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux n3-mgmt-master01 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

```
$ crictl --version
crictl version v1.21.0
```

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
