### ISSUE TITLE
ephemeral-storage used over requested

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#126376]
### What happened?

ephemeral-storage-pod.yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-storage-pod
spec:
  containers:
  - name: my-container
    image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/busybox:1.33.1
    image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/busybox:1.33.1
    command:
    - sleep
    - inf
    resources:
      requests:
        ephemeral-storage: "1Gi"
      limits:
        ephemeral-storage: "2Gi"
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}

```

```
/ # dd if=/dev/zero of=/cache/file bs=1M count=2049
2049+0 records in
2049+0 records out
2148532224 bytes (2.0GB) copied, 1.525452 seconds, 1.3GB/s
/ # dd if=/dev/zero of=/cache/file2 bs=1M count=100
100+0 records in
100+0 records out
104857600 bytes (100.0MB) copied, 0.037725 seconds, 2.6GB/s
/ # du -sh /cache/
2.1G    /cache/
/ # 
```

### What did you expect to happen?

limit 2Gi

### How can we reproduce it (as minimally and precisely as possible)?

apply the yaml and dd

### Kubernetes version

<details>

root@k8s-master01:~/k8s-core-teaching/scheduler# kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

</details>

### Cloud provider

<details>
pve 8
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
