### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Resizing pod gets stuck if limit is not configured

### ISSUE THREAD

**Issue by hshiina** [kubernetes/kubernetes#126388]
### What happened?

Resizing CPU requests gets stuck in `InProgress` if the CPU limit is not configured:
```
$ kubectl patch pod resize-pod --patch '{"spec":{"containers":[{"name":"resize-container", "resources":{"requests":{"cpu":"300m"}}}]}}'
pod/resize-pod patched
$ sleep 300
$ kubectl get pod resize-pod -o jsonpath='spec: {.spec.containers[0].resources}{"\nallocatedResources: "}{.status.containerStatuses[0].allocatedResources}{"\nstatus: "}{.status.containerStatuses[0].resources}{"\nresize: "}{.status.resize}{"\n"}'
spec: {"requests":{"cpu":"300m","memory":"200Mi"}}
allocatedResources: {"cpu":"300m","memory":"200Mi"}
status: {"requests":{"cpu":"200m","memory":"200Mi"}}
resize: InProgress
```

The internal behavior in kubelet varies depending on other resource limits configuration.
- If the limit for another resource is also not configured, no action is computed at `computePodResizeAction()`:
  ```
  Jul 26 13:43:09 kind-control-plane kubelet[708]: I0726 13:43:09.494698     708 kuberuntime_manager.go:1051] "computePodActions got for pod" podActions="KillPod: false, CreateSandbox: false, UpdatePodResources: false, Attempt: 0, InitContainersToStart: [], ContainersToStart: [], EphemeralContainersToStart: [],ContainersToUpdate: map[], ContainersToKill: map[]" pod="default/resize-pod"
  ```
  This looks caused because `container.Resources.Limits == nil`:
  https://github.com/kubernetes/kubernetes/blob/3a8a60eba29940e26ac8db52329a91ba87305114/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L555-L557
- If the limit for another resource is configured, `doPodResizeAction()` gets failed:
  ```
  Jul 26 14:04:23 kind-control-plane kubelet[708]: E0726 14:04:23.063108     708 kuberuntime_manager.go:750] "podResources.CPUQuota or podResources.CPUShares is nil" pod="resize-pod"
  ```
  This message is logged here:
  https://github.com/kubernetes/kubernetes/blob/3a8a60eba29940e26ac8db52329a91ba87305114/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L754-L757
  This is caused because CPUQuota is not set if the CPU limit is not configured:
  https://github.com/kubernetes/kubernetes/blob/3a8a60eba29940e26ac8db52329a91ba87305114/pkg/kubelet/cm/helpers_linux.go#L179-L182

There is a similar problem in resizing memory limits. See the comment below: https://github.com/kubernetes/kubernetes/issues/126388#issuecomment-2276385213

### What did you expect to happen?

This resizing should not get stuck in `InProgress` though I’m not sure whether this should be actuated or rejected yet.

### How can we reproduce it (as minimally and precisely as possible)?

1. Enable `InPlacePodVerticalScaling`.
2. Create a pod where CPU request is configured and CPU limit is not configured:
    <Details>

   pod with no resource limits:
   ```
   apiVersion: v1
   kind: Pod
   metadata:
     creationTimestamp: null
     labels:
       run: resize-pod
     name: resize-pod
   spec:
     containers:
     - image: busybox
       name: resize-container
       command:
         - sh
         - -c
         - trap "exit 0" SIGTERM; while true; do sleep 1; done
       resources:
         requests:
           cpu: 200m
           memory: 200Mi
       resizePolicy:
       - resourceName: cpu
         restartPolicy: NotRequired
       - resourceName: memory
         restartPolicy: NotRequired
     restartPolicy: Always
   ```

   pod with memory limit:
   ```
   apiVersion: v1
   kind: Pod
   metadata:
     creationTimestamp: null
     labels:
       run: resize-pod
     name: resize-pod
   spec:
     containers:
     - image: busybox
       name: resize-container
       command:
         - sh
         - -c
         - trap "exit 0" SIGTERM; while true; do sleep 1; done
       resources:
         requests:
           cpu: 200m
           memory: 200Mi
         limits:
           memory: 200Mi
       resizePolicy:
       - resourceName: cpu
         restartPolicy: NotRequired
       - resourceName: memory
         restartPolicy: NotRequired
     restartPolicy: Always
   ```

   </Details>
3. Patch the pod to update its CPU request:
   ```
   $ kubectl patch pod resize-pod --patch '{"spec":{"containers":[{"name":"resize-container", "resources":{"requests":{"cpu":"300m"}}}]}}'
   ```
4. Wait for more than two minutes in order to confirm this issue is not the [known issue](https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/#known-issues).
5. See the pod resize status:
   ```
   $ kubectl get pod resize-pod -o jsonpath='spec: {.spec.containers[0].resources}{"\nallocatedResources: "}{.status.containerStatuses[0].allocatedResources}{"\nstatus: "}{.status.containerStatuses[0].resources}{"\nresize: "}{.status.resize}{"\n"}'
   spec: {"requests":{"cpu":"300m","memory":"200Mi"}}
   allocatedResources: {"cpu":"300m","memory":"200Mi"}
   status: {"requests":{"cpu":"200m","memory":"200Mi"}}
   resize: InProgress
   ```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

</details>

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by hshiina** [comment]
Memory requests can be resized even if memory limits are not configured because memory requests are resized without requesting anything to the runtime. However, a similar error is caused  in the following case:
1. Multiple containers are configured in a pod.
2. Memory limits are configured in some containers while memory limits are not configured in the other containers.
3. Memory limits of one of containers that have memory limits are requested to be resized.

pod example:
<Details>

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: resize-pod
  name: resize-pod
spec:
  containers:
  - image: busybox
    name: resize-container1
    command:
      - sh
      - -c
      - trap "exit 0" SIGTERM; while true; do sleep 1; done
    resources:
      requests:
        memory: 200Mi
      limits:
        memory: 200Mi
  - image: busybox
    name: resize-container2
    command:
      - sh
      - -c
      - trap "exit 0" SIGTERM; while true; do sleep 1; done
    resources:
      requests:
        memory: 100Mi
  restartPolicy: Always

```
</Details>

```
kubectl patch pod resize-pod  --patch '{"spec":{"containers":[{"name":"resize-container1", "resources":{"requests":{"memory":"250Mi"}, "limits":{"memory": "300Mi"}}}]}}
```

After this patch, this message is logged in `kubelet.log`:
```
Aug 08 18:04:00 kind-control-plane kubelet[714]: E0808 18:04:00.219134     714 kuberuntime_manager.go:722] "podResources.Memory is nil" pod="resize-pod"
```
