### ISSUE TITLE
dra did not create ResourceSlice api，so I create one，but get nono

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#126346]
### What happened?

```
root@k8s-master01:~/k8s-core-teaching/scheduler# kubectl apply -f resource-slice.yaml 
resourceslice.resource.k8s.io/k8s-worker01 created
root@k8s-master01:~/k8s-core-teaching/scheduler# kubectl get resourceslice -A
No resources found
```

```
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceSlice
metadata:
  name: k8s-worker01
driverName: gpu.resource.nvidia.com
nodeName: k8s-worker01
namedResources:
  instances:
  - name: nvidia-gpu
    attributes:
    - name: gpu.memory
      quantity: 4Gi
    - name: num.cores
      int: 1
    - name: vendor
      string: nvidia
    - name: cuda.version
      string: "12.4"
    - name: driver.version
      string: "550.90.07"
    - name: gpu.name
      string: NVIDIA GeForce GTX 1650
```

### What did you expect to happen?

get success

### How can we reproduce it (as minimally and precisely as possible)?

apply the yaml

### Kubernetes version

<details>

root@k8s-master01:~/k8s-core-teaching/scheduler# kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

</details>

### Cloud provider

<details>
pve 8
</details>

### OS version

<details>
ubuntu 2404

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
