### ISSUE TITLE
the code said when NodeCacheCapable  is true NodeNames  has value，NodeCacheCapable is false Nodes has value。but NodeNames  alwalys has value，Nodes  always is nil

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#126425]
### What happened?

type ExtenderArgs struct {
	// Pod being scheduled
	Pod *v1.Pod
	// List of candidate nodes where the pod can be scheduled; to be populated
	// only if Extender.NodeCacheCapable == false
	Nodes *v1.NodeList
	// List of candidate node names where the pod can be scheduled; to be
	// populated only if Extender.NodeCacheCapable == true
	NodeNames *[]string
}

![image](https://github.com/user-attachments/assets/abf70d5c-5bf0-4e2a-b0a5-688d21fd59be)
```
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  resourceLock: leases
  resourceName: kube-scheduler
  resourceNamespace: kube-system
  retryPeriod: 2s
extenders:
- urlPrefix: "http://127.0.0.1:80/scheduler"
  filterVerb: filter
  preemptVerb: preemption
  prioritizeVerb: priorities
  weight: 2
  bindVerb: bind
  enableHTTPS: false
  httpTimeout: 10s
  nodeCacheCapable: false
  ignorable: false
```

### What did you expect to happen?

parameter value error

### How can we reproduce it (as minimally and precisely as possible)?

try the code

### Kubernetes version

<details>

1.30.0

</details>

### Cloud provider

<details>
vmware
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
