### ISSUE TITLE
Scheduling Inconsistency Caused by kube-scheduler Restart

### ISSUE THREAD

**Issue by kangzhiqin** [kubernetes/kubernetes#126499]
### What would you like to be added?

I have a deployment that needs to pull up two replicas and configure pod strong anti-affinity as follows:
```
      - ephemeral:
          volumeClaimTemplate:
            metadata:
              creationTimestamp: null
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 200Mi
              storageClassName: localcsi
              volumeMode: Filesystem

```

```
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - xxx
            topologyKey: kubernetes.io/hostname
```

### Why is this needed?

kube-scheduler schedules the temporary volume of replica 1 to node 1 but does not schedule the pod of replica 1. At this time, kube-scheduler restarts. After the restart, kube-scheduler starts to schedule the temporary volume and pod of replica 2 and schedules replica 2 to node 1. As a result, copy 1 cannot be scheduled due to anti-affinity.
After kube-scheduler is restarted, it cannot load the temporary volume information scheduled before the restart.
Does the community have any suggestions on this issue?
