### ISSUE TITLE
KubeSchedulerConfiguration acceptContentTypes contentType configured to  application/yaml application/protobuf will make pod unschedulable

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#126412]
### What happened?

scheduler-config.yaml

```
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
  acceptContentTypes: application/yaml
  contentType: application/yaml
  qps: 20
  burst: 10
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  resourceLock: leases
  resourceName: kube-scheduler
  resourceNamespace: kube-system
  retryPeriod: 2s
```

scheduler-config.yaml

```
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
  acceptContentTypes: application/protobuf
  contentType: application/protobuf
  qps: 20
  burst: 10
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  resourceLock: leases
  resourceName: kube-scheduler
  resourceNamespace: kube-system
  retryPeriod: 2s
```

### What did you expect to happen?

scheduler the pod

### How can we reproduce it (as minimally and precisely as possible)?

change scheduler config 
apply the pod

### Kubernetes version

<details>

Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

</details>

### Cloud provider

<details>
pve8
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
