### ISSUE TITLE
E0728 07:40:02.660770       1 run.go:74] "command failed" err="leaderElection.resourceLock: Invalid value: \"configmaps\": resourceLock value must be \"leases\""

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#126413]
### What happened?

E0728 07:40:02.660770       1 run.go:74] "command failed" err="leaderElection.resourceLock: Invalid value: \"configmaps\": resourceLock value must be \"leases\""

```
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  resourceLock: configmaps
  resourceName: kube-configmap
  resourceNamespace: kube-system
  retryPeriod: 2s
```

### What did you expect to happen?

can use configmap

### How can we reproduce it (as minimally and precisely as possible)?

change scheduler config

### Kubernetes version

<details>
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
</details>

### Cloud provider

<details>
pve 8
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pranav-pandey0804** [comment]
The error message indicates that the `resourceLock` value should be `leases` instead of `configmaps`.

**Comment by pranav-pandey0804** [comment]
try with this

```
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  resourceLock: leases
  resourceName: kube-configmap
  resourceNamespace: kube-system
  retryPeriod: 2s
```
