### ISSUE TITLE
Secret Creation for Service Account Does Not Populate secrets Field

### ISSUE THREAD

**Issue by UgOrange** [kubernetes/kubernetes#126515]
### What happened?

I used the following command in Kubernetes to create a secret with the token of the prometheus-agent service account:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: prometheus-agent
  name: get-prometheus-sa-token
  namespace: kube-system
type: kubernetes.io/service-account-token
EOF
```

However, when I check the prometheus-agent service account using the command kubectl get sa prometheus-agent -n kube-system, I found that the secrets field is still 0.

### What did you expect to happen?

I expected the secrets field of the prometheus-agent service account to be populated with the created secret.

### How can we reproduce it (as minimally and precisely as possible)?

Create a Kubernetes cluster (any version >= 1.24).
Use the provided kubectl apply -f - command to create the secret.
Check the secrets field of the prometheus-agent service account using kubectl get sa prometheus-agent -n kube-system.

### Anything else we need to know?

I am willing to fix this potential bug (need confirmation if this is indeed a bug). The proposed solution involves updating the ServiceAccount (SA) information when renewing the tokens for secrets. However, I would like to confirm this approach beforehand.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.15-vke.32
```

</details>

### Cloud provider

<details>
Volcano Engine
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
