### ISSUE TITLE
Prometheus allows "/" in label values but kubernetes does not

### ISSUE THREAD

**Issue by drawnwren** [kubernetes/kubernetes#126555]
### What happened?

```yaml
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: my_name
  namespace: my_namespace
spec:
...
  metrics:
  - type: Pods
    pods:
      metric:
        name: vllm_average_first_token_time
        selector: 
          matchLabels:
            model_name: '/a/file/path'
      target:
        type: Value
        averageValue: "4.0"
```

This hpa is invalid and gives:
```text
  Warning  FailedGetPodsMetric  2m35s (x13 over 5m36s)  horizontal-pod-autoscaler  values[0][model_name]: Invalid value: "/a/file/path/": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

### What did you expect to happen?

It would be nice if `labelSelectors` allowed the same values as prometheus.

### How can we reproduce it (as minimally and precisely as possible)?

.

### Anything else we need to know?

.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6-eks-db838b0
```

</details>

### Cloud provider

<details>
aws
</details>

### OS version

.
