### ISSUE TITLE
The event handlers of job controller are slow

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#126510]
### What happened?

The event handlers in job controller are much slower than other controllers. It can cause the ring buffer in the processorListener to grow unbounded when the job churn is high enough.
The processing logic in the job controller events handler appears to be more complicated than other controllers. e.g. in [updateJob](https://github.com/kubernetes/kubernetes/blob/dbc2b0a5c7acc349ea71a14e49913661eaf708d2/pkg/controller/job/job_controller.go#L464-L504), it invokes function `cleanupPodFinalizers` that lists the pods matching some selectors and the enqueue them to another queue. Similarly in [deleteJob](https://github.com/kubernetes/kubernetes/blob/dbc2b0a5c7acc349ea71a14e49913661eaf708d2/pkg/controller/job/job_controller.go#L508-L524).

I added some instrumenting code to understand the latency of each event handler.
For job controller P99:
job add event handler: 0.080 ms
job update event handler: 3.075 ms
job delete event handler: 3.076 ms
pod add event handler: 0.136 ms
pod update event handler: 0.709 ms
pod delete event handler: 0.405 ms

For ttl-after-completion controller P99:
job add event handler: 0.0065 ms
job update event handler: 0.024 ms

The above 2 controllers processes same amount of job objects.

### What did you expect to happen?

Complicated logic should not be in the job controller event handler. They should be in the reconciler instead.
So that the event handler can be faster and pendingNotification can be drained faster.

### How can we reproduce it (as minimally and precisely as possible)?

I use a few thousands of cronjobs with TTL after completion.
I will add more details.

### Kubernetes version

1.30
<details>

Current HEAD of master
</details>

### Cloud provider

EKS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L485-L487

is most probably the offender - without looking deeper into the code, this should most probably go to the worker function

/cc @mimowo @alculquicondor

**Comment by mengqiy** [comment]
cc: @soltysh

**Comment by mimowo** [comment]
@mengqiy thanks for reporting the issue. 

To help the triage the issue I traced down the introduction of `cleanupPodFinalizers` code:
- for the `deleteJob` it was introduced in 1.24: https://github.com/kubernetes/kubernetes/pull/108752
- for the `updateJob` it was introduced in 1.29: https://github.com/kubernetes/kubernetes/pull/119944

The `updateJob` seems to be expensive only when finished Jobs are updated.

**Comment by mengqiy** [comment]
Given we only run one single goroutine for `run()` which is responsible for invoking the event handler https://github.com/kubernetes/kubernetes/blob/dbc2b0a5c7acc349ea71a14e49913661eaf708d2/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L802
this can easily be the bottleneck in a controller whenever the event handler is slow.
The event handler that used by the informer is expected to be very thin and fast. It seems `cleanupPodFinalizers` has some expansive logic and slow down updateJob and deleteJob. 
IMO we should move `cleanupPodFinalizers` to the reconciler.

**Comment by hakuna-matatah** [comment]
I was wondering @mengqiy  given you already have the metrics instrumentation code in place, can we quickly remove `cleanupPodFinalizers` from `event handler` and crunch the numbers ?? Leaving the correctness of job controller aside for testing purposes ?? (as discussed offline )

**Comment by mimowo** [comment]
I think this should work - I don't see anything that would block achieving correctness, let me know if some complications surface exposed by tests.

**Comment by atiratree** [comment]
@mengqiy how can we reproduce this? What jobs did you use?

>  It can cause the ring buffer in the processorListener to grow unbounded when the job churn is high enough.

Have you observed this or do you have any data on the limitations?

**Comment by aojea** [comment]
repro and also a pprof may be useful

**Comment by mengqiy** [comment]
Will find some time to add the detailed steps to repro this week.

**Comment by mengqiy** [comment]
A simple way to reproduce this is creating about 10k copy of the following cronjobs. In case 10k doesn't reproduce it for your setup, adding 1 or 2k more should be able to do it.
Each cronjob creates a job every minute.
```
apiVersion: batch/v1
kind: CronJob
metadata:
  generateName: simple-
  namespace: kube-stress
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30
      template:
        spec:
          automountServiceAccountToken: false
          containers:
            - name: simple
              image: busybox
              command: ["sleep", "10"]
              resources:
                requests:
                  cpu: 5m
                  memory: 10Mi
                limits:
                  cpu: 5m
                  memory: 10Mi
          restartPolicy: OnFailure
```

Control plane configuration:
kube-controller-manager:
- qps: 500
- concurrent-job-syncs: 50

kube-scheduler:
- qps: 400

These configuration is large enough to ensure QPS doesn't become a bottleneck.

I added [this commit](https://github.com/mengqiy/kubernetes/commit/8114fc925f16deaf88ee2e21ee18bc030babfbec) to show some metrics about event processing latency and pending notification count. It is a bit hacky.
