### ISSUE TITLE
Static Pods never get evicted when under Node Pressure

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#126542]
### What happened?

Static Pods are considered critical by [this code] (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L597) and hence never get evicted.

### What did you expect to happen?

The [doc](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#pod-selection-for-kubelet-eviction) says 

> If you are running a [static pod](https://kubernetes.io/docs/concepts/workloads/pods/#static-pods) and want to avoid having it evicted under resource pressure, set the priority field for that Pod directly. Static pods do not support the priorityClassName field.

At least, we should fix the inconsistency between code and doc.

### How can we reproduce it (as minimally and precisely as possible)?

1. Run a kubelet with fs eviction and static pods
```
apiVersion: kubelet.config.k8s.io/v1beta1
staticPodPath: /home/k8s/manifests
evictionHard:
  imagefs.available: "2Gi"
```

2. Create a static pod spamming disk
```
apiVersion: v1
kind: Pod
metadata:
  name: disk
spec:
  priority: 0
  - name: disk
    image: docker.io/busybox
    command: ["/bin/sh",  "-c", "/bin/dd if=/dev/zero of=/bigfile bs=1G count=102 && sleep 10000"]
```

3. check kubelet logs
> "Eviction manager: cannot evict a critical pod" pod="default/disk"

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
