### ISSUE TITLE
kubectl v1.29.7 is built with go1.22.5 but expected goVersion go1.21.*

### ISSUE THREAD

**Issue by caixiangibm** [kubernetes/kubernetes#126573]
**What happened**:
kubectl v1.29.7 is built with go1.22.5 but expected goVersion go1.21.*
**What you expected to happen**:
kubectl in v1.29 line is expected with goVersion go1.21.*

**How to reproduce it (as minimally and precisely as possible)**:
Download kubectl from https://dl.k8s.io/release/v1.29.7/bin/linux/amd64/kubectl, and check version details
It's saying "goVersion: go1.22.5", but the expected is goVersion go1.21.* as set in https://github.com/kubernetes/kubectl/blob/kubernetes-1.29.7/go.mod#L5
```
# ./kubectl version --client -o yaml
clientVersion:
  buildDate: "2024-07-17T00:06:19Z"
  compiler: gc
  gitCommit: 4e4a18878ce330fefda1dc46acca88ba355e9ce7
  gitTreeState: clean
  gitVersion: v1.29.7
  goVersion: go1.22.5
  major: "1"
  minor: "29"
  platform: linux/amd64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
```

**Anything else we need to know?**:
Also checked kubectl v1.29.6 with "kubectl version --client -o yaml" command, which is with goVersion: go1.21.11
So it maybe build issue that goVersion bump in kubectl v1.29.7

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):v1.29.7
- Cloud provider or hardware configuration: linux
- OS (e.g: `cat /etc/os-release`): CentOS Stream 9 / amd64
