### ISSUE TITLE
Can't interact with service's ip 

### ISSUE THREAD

**Issue by zmsp** [kubernetes/kubernetes#12661]
Hello, we are running a postgres pod and we are able to connect to it using the minion's ip however we want to couple it with a service. We are running this locally using libvirt VM. Our service validates but doesn't seem to be running correctly. We can't interact with the service ip. Our goal is to use the service's ip to connect to postgresql using psql client. 

Here are our codes
Service
```
apiVersion: v1
kind: Service
metadata: 
  name: postgresql
  labels:
    component: postgresql
spec: 
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 0
  selector: 
    name: postgres-pod
apiVersion: v1
kind: Service
metadata: 
  name: postgresql
  labels:
    component: postgresql
spec: 
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 0
  selector: 
    name: postgres-pod
    context: postgres-pod-k9
```

pod
```
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    context: postgres-pod-k9
spec:
  containers:
  - image: postgres:latest
    name: postgres
    volumeMounts:
      - name: nfs
        mountPath: /var/lib/postgresql/data
    ports:
      - containerPort: 5432
        hostPort: 5432
        name: pg-port
  volumes:
    - name: nfs
      nfs:
       server: 10.20.20.190
       path: /postgres
```

Thank you.
