### ISSUE TITLE
Pod status phase misses Pending transition after node reboot

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#126650]
### What happened?

When a kubernetes node is rebooted, all the containers running on the node are terminated and then created & started over again. When the pod has a list of init containers runing, and if the init container takes a little bit time (longer than PLEG period), the pod is supposed to have `status.phase: Pending`, but instead, during the whole operation, `status.phase` is always `Running`.

This new behavior (always has `status.phase: Running`) started when "restartable init container" was [introduced][1]. After node reboots, all the regular init containers are started one by one, so `pendingInitialization` is supposed by larger than 0 (unless the init container is completed pretty fast that PLEG doesn't catch any running init container), and should report `Pending` phase. But the behavior has changed to check further whether there are any other regular containers that have started. In the case of node reboot, all the other regular containers are already terminated, and then considered as "yes, they have started", and then no longer reported as `Pending`.

I think this behavior change is unexpected, as that violates the [definition][2] of "Running":

> // PodRunning means the pod has been bound to a node and all of the containers have been started.
	// At least one container is still running or is in the process of being restarted.

None of the containers have been started, and they are not in the process of being started or restarted as init containers are still running.

[1]: https://github.com/kubernetes/kubernetes/blob/099a88370d017dacf16e67306ebcdec8394fae83/pkg/kubelet/kubelet_pods.go#L1675-L1685
[2]: https://github.com/kubernetes/kubernetes/blob/099a88370d017dacf16e67306ebcdec8394fae83/pkg/apis/core/types.go#L2871

### What did you expect to happen?

I expect that pods with init containers should transition into "Pending" when kubelet observed that its regular init container is still running and none of its main containers are started.

### How can we reproduce it (as minimally and precisely as possible)?

1. Launch a cluster with minikube:

```console
$ minikube start --nodes=2 --kubernetes-version=v1.30.3
```

2. Create the following pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sleep
spec:
  restartPolicy: Always
  containers:
  - name: sleep
    image: busybox
    command:
    - sleep
    - infinity
  initContainers:
  - name: snap
    image: busybox
    command:
    - sleep
    - "10"
```

3. Log in the node and simulate "reboot"

```console
$ minikube ssh --node <node-which-runs-the-pod-above>
...
# systemctl stop kubelet
# docker stop $(docker ps -aq)
# systemctl start kubelet
```

4. Observe the pod status via:

```console
$ k get pods -w -o jsonpath='{$.status.phase}{"\n"}'
```

On 1.30.3, the output from 4 is `Running` constantly, while in previous kubernetes version (for e,g, v1.23.17), it will show "Pending" while the init container is still Running.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.3", GitCommit:"6fc0a69044f1ac4c13841ec4391224a2df241460", GitTreeState:"clean", BuildDate:"2024-07-16T23:48:12Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.30) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
None (minikube)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by zhifei92** [comment]
I think this is indeed a bug, and it should at least not affect the original logic for regular init containers. I will submit a PR to fix this problem.

/assign

**Comment by gjkim42** [comment]
I'll take a look.

**Comment by gjkim42** [comment]
looks similar to https://github.com/kubernetes/kubernetes/issues/120247
but different issue.

**Comment by kannon92** [comment]
@gjkim42 can you help triage this? Feel free to add the labels.

**Comment by AnishShah** [comment]
sig-node CI Meeting:

/triage accepted
/priority critical-urgent

**Comment by gjkim42** [comment]
I confirmed that the bug can be reproduced using the given scenario.

```yaml
...
  containerStatuses:                               
  - containerID: containerd://92701f3cfe6491648b6d50bfa13d947ef17e3925bb9a5995085e6b29d9e429a9
    image: docker.io/library/ubuntu:latest         
    imageID: docker.io/library/ubuntu@sha256:8a37d68f4f73ebf3d4efafbcf66379bf3728902a8038616808f04e34a9ab63ee
    lastState: {}                                  
    name: regular                                                                                     
    ready: false                                                                                      
    restartCount: 1                                                                                                                                                                                         
    started: false                                 
    state:                                                                                                                                                                                                  
      terminated:                                                                                     
        containerID: containerd://92701f3cfe6491648b6d50bfa13d947ef17e3925bb9a5995085e6b29d9e429a9
        exitCode: 255                              
        finishedAt: "2024-09-05T13:11:38Z"                                                            
        reason: Unknown                            
        startedAt: "2024-09-05T13:08:44Z"
  hostIP: 172.18.0.3                               
  hostIPs:                                         
  - ip: 172.18.0.3                                 
  initContainerStatuses:                           
  - containerID: containerd://61f8bc55eaa04eca408bb1b082fbcacf4523237722f96ab88c3dacb4427d466c
    image: docker.io/library/ubuntu:latest      
    imageID: docker.io/library/ubuntu@sha256:8a37d68f4f73ebf3d4efafbcf66379bf3728902a8038616808f04e34a9ab63ee
    lastState: {}                                  
    name: init                                                                                        
    ready: false                                   
    restartCount: 2                                                                                   
    started: true                                  
    state:                                                                                                                                                                                                  
      running:                                     
        startedAt: "2024-09-05T13:11:44Z"
```

To make a workaround,
we can exclude regular containers in a `terminated` state with an `Unknown` reason from being considered as having started.
Not sure it is a good idea though...
