### ISSUE TITLE
tokenfile path is hardcoded in the config.go

### ISSUE THREAD

**Issue by meeee123** [kubernetes/kubernetes#126635]
### What happened?

To enable automatic rotation of service account tokens, we need to mount the tokens in the different path and not the default path **/var/run/secrets/kubernetes.io/serviceaccount/token**

We tried with projected volumes and mounted the token under /token with the expiration like below
- name: token
          projected:
            sources:
            - serviceAccountToken:
                audience: api
                path: token
                expirationSeconds: 31536000

     **In Container:**          
    volumeMounts:
          - name: token
            mountPath: token
            readOnly: true
                
Since the path is hardcoded to the default, pod is still expecting the default tokens and mounted tokens under/token is not used at all
![image](https://github.com/user-attachments/assets/ff6892fe-f511-4bc4-8c20-081799cfa16a)

### What did you expect to happen?

Expected to use the mounted token under /token and not the default token

### How can we reproduce it (as minimally and precisely as possible)?

Mount the service account token to different path, pod should come up with the path provided
 automountServiceAccountToken: false ---> to disbale the default path. We tried mounting on a different path and pods are not coming up as they are still expecting the default token.

Error is pod:
panic: /var/run/secrets/kubernetes.io/serviceaccount/token not found

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aramase** [comment]
@meeee123 Could you provide more details on what you're trying to accomplish here?

**Comment by meeee123** [comment]
@aramase we are trying to include the expiry of token. Mounting the serviceAccount token in a different path and not in the default path. 
We tried with mountpath and subpath, it is still expecting default token to be present even though we mounted the token in a different path

**Comment by xuzhenglun** [comment]
Can you please provide some detail to describe why you need two different tokens in one pod, to avoid our discussion from falling into the XY problem?

If you are seeking a way to do migration, there is already one mechanism to help user to do so ([see `--service-account-extend-token-expiration` of kube-apiserver](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)), and I don't believe that two token files are really necessary.

**Comment by meeee123** [comment]
@xuzhenglun we tried to mount the token under /var/run/secrets/kubernetes.io/serviceaccount with the expiration of lets say 10 days

name: token
projected:
sources:
- serviceAccountToken:
audience: api
path: /var/run/secrets/kubernetes.io/serviceaccount
expirationSeconds: 864000

Observed that /var/run/secrets/kubernetes.io/serviceaccount  path has only the token and not the ca.crt
Usually under this path /var/run/secrets/kubernetes.io/serviceaccount - ca.crt and token will be generated.

We tried disabling automountServiceAccountToken: false so that this default path tokens won't be generated and used projected volume to mount the token in a different path.

automountServiceAccountToken: false
name: token
projected:
sources:
- serviceAccountToken:
audience: api
path: token
expirationSeconds: 864000

In this scenario, we observed that default path is still expected by the pod as the path provided in the config.go

**Comment by xuzhenglun** [comment]
In my understanding, you want to expand the default `expirationSeconds` from one hour to ten days? To accomplish this, you created a Pod with a projected Volume manually setting `expirationSeconds=864000`. After Pod being created, you found that the `ca.crt` and `namespace` file did not show up.   Am I understand correctly?

I assume that the reason `ca.crt` and `namespace` is missing is because you misconfigured the Pod's YAML. As following example can see, `ca.crt` and `namespace` are also a entry of projected source. Maybe you need to check the Pod YAML that do something wrong there.
```
  - name: kube-api-access-mz42r
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

under the hoold, volume `kube-api-access-<random>` are injected by admission controller automatic

**Comment by meeee123** [comment]
We need only the token to get expired every 10 days or user configurable expiry. is it possible to mount the token alone in the different path without the token in the default path?
  
  Below is the pod's yaml, we do have ca.crt and token in the default path
  - name: token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: api
          expirationSeconds: 864000
          path: token
  - name: kube-api-access-flbmj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt

**Comment by xuzhenglun** [comment]
It looks like that volume `token` and `kube-api-access-flbmj` both mount to `/var/run/secrets/kubernetes.io/serviceaccount`, so the pervious  one shadowed the later one. 

As the pervious repaly said, you may specific a volume with same volume name pattern to override the default setting. I don't believe that mounting the token to another path could reach your goal, because as you can see the path is hardcoded in `client-go` by designed.

**Comment by xuzhenglun** [comment]
1. you can disable token injection by setting `pod.spec.automountServiceAccountToken=false` or `sa.automountServiceAccountToken=false`. see more: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting

2. if the auto injection mechanism is working, you may specific a volume with same volume name pattern to override it. see more:
https://github.com/kubernetes/kubernetes/blob/128d6cc14624c55e227761cab4897c471b691b4e/plugin/pkg/admission/serviceaccount/admission.go#L418-L428

**Comment by meeee123** [comment]
Tried the first point, pod.spec.automountServiceAccountToken=false 
Observed no tokens are generated in the default path and mounted the token in /token path

Can you please provide more details on the second point if the auto injection mechanism is working, you may specific a volume with same volume name pattern to override it
Thanks

**Comment by xuzhenglun** [comment]
# the first approach
1.  disable default token volume injection by setting `pod.spec.automountServiceAccountToken=false`
2. create a pod with a projected token file
```
apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - image: foo-image
    name: foo
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: custom-token-volume
      readOnly: true
  hostNetwork: true
  volumes:
  - name: custom-token-volume
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 864000
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

# the second approach
1. create a pod with projected token file whose name in specific prefix

```
apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - image: foo-image
    name: foo
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-foo
      readOnly: true
  hostNetwork: true
  volumes:
  - name: kube-api-access-foo
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 864000
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

**Comment by meeee123** [comment]
Tried the below scenario, only token is present and tls failed errors in pod as ca.crt is not present
automountServiceAccountToken: false
volumeMounts:
- mountPath: /var/run/secrets/kubernetes.io/serviceaccount
   name: custom-token
   readOnly: true
volumes:
- name: custom-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: api
              expirationSeconds: 864000
              path: token

only token is present:
 cd /var/run/secrets/kubernetes.io/serviceaccount/
 
 Pod logs:
 tls: failed to verify certificate: x509: certificate signed by unknown authority
token

**Comment by xuzhenglun** [comment]
which kubernetes version you are using, I tested in 1.20 and 1.30 are both worked. do you modify anything in YAML? just copy and paste below in terminal.

```
echo 'apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - image: docker.io/library/ubuntu:latest
    command: ["sleep", "101201020102"]
    name: foo
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-foo
      readOnly: true
  hostNetwork: true
  volumes:
  - name: kube-api-access-foo
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 864000
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace' | kubectl apply -f -
```

**Comment by xuzhenglun** [comment]
The path is hardcoded in client-go, so there is no easy way to do that. 

I don’t understand why you have to do that, since you already be able to change to token expire date. Or pervious approach did not solve your issue? Maybe I didn’t understand your issue correctly, maybe you need to share more detail to help me to understand you.

**Comment by meeee123** [comment]
@xuzhenglun we tried both the approaches suggested. 
With both the approaches, both the pods are getting into standby state and observed the pods logs that unauthorized.
Failed to list *v1.Pod: Unauthorized

With the default tokens generated under /var/run/secrets/kubernetes.io/serviceaccount, our pods are in active-standby which is the expected behavior.

Thanks

**Comment by xuzhenglun** [comment]
It because `spec.serviceAccountName` is not set in my example, so the user which the token represents is not the one you are using before.

**Comment by meeee123** [comment]
Can you please provide an example with spec.serviceAccountName with the same token?

**Comment by xuzhenglun** [comment]
Just set the `spec.serviceAccountName` to what you are using before. For more imformation, please checkout mannal of ServiceAccount here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-multiple-service-accounts

**Comment by meeee123** [comment]
Hi,
spec.serviceAccountName was set and observed the same behavior. Both the pods are getting into standby state with the below error
open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

**Comment by meeee123** [comment]
Hi @xuzhenglun ,

Any update? Can you please suggest the solution?

**Comment by xuzhenglun** [comment]
I'm not sure what you modified else, I assume that you remove the volume related fields in my example: https://github.com/kubernetes/kubernetes/issues/126635#issuecomment-2288551272

Just like previously mentioned, the `Unauthorized issue` is because you need to set `spec.serviceAccountName` to a name of your actual service account. the full example would be like:
```
echo 'apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  serviceAccountName: <set-here>
  containers:
  - image: docker.io/library/ubuntu:latest
    command: ["sleep", "101201020102"]
    name: foo
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-foo
      readOnly: true
  hostNetwork: true
  volumes:
  - name: kube-api-access-foo
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 864000
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace' | kubectl apply -f -
```
You can find more detail about RBAC in https://kubernetes.io/docs/reference/access-authn-authz/rbac/
