### ISSUE TITLE
Pod Anti Affinity is not working as expected

### ISSUE THREAD

**Issue by prafull01** [kubernetes/kubernetes#126632]
### What happened?

I have setup the pod Anti Affinity to be applied on set of nodes which has specific labels.
```
affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: custom-app
            operator: In
            values:
            - aj
        topologyKey: kubernetes.io/hostname
```

I have two nodes cluster and there are already 2 pods deployed which have the above anti-affinity but doesn't have label `custom-app: aj` on them.

Pod1:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: trilio
    pod-template-hash: fd956d7c7
  name: pod1
  namespace: default
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: custom-app
            operator: In
            values:
            - aj
        topologyKey: kubernetes.io/hostname
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 36000000
    image: busybox
    imagePullPolicy: Always
    name: dm
```

pod 2:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: trilio
    pod-template-hash: 8674564dcb
  name: pod2
  namespace: default
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: custom-app
            operator: In
            values:
            - aj
        topologyKey: kubernetes.io/hostname
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 36000000
    image: busybox
    imagePullPolicy: Always
    name: dm
```

Now when I create the 3rd pod with label `custom-app: aj` on the cluster it should be deployed on any of the nodes as there are no pods present on the nodes which have `custom-app: aj` label. However the next node which have the label `custom-app: aj` goes into pending state.

Pod3:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    custom-app: aj
    pod-template-hash: 855cb8df4f
  name: pod3
  namespace: default
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: custom-app
            operator: In
            values:
            - aj
        topologyKey: kubernetes.io/hostname
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep 36000000
    image: busybox
    imagePullPolicy: Always
    name: dm
```

This pod gets stuck in pending state saying:
```
prafulll@EMPID18004 k8s-triliovault % kubectl get pods
NAME                    READY   STATUS    RESTARTS   AGE
pod1                         1/1       Running              0          53m
pod2                         1/1       Running              0          52m
pod3                         0/1       Pending              0          20m


Events:
  Type     Reason             Age                  From                Message
  ----     ------             ----                 ----                -------
  Normal   NotTriggerScaleUp  14s (x122 over 20m)  cluster-autoscaler  pod didn't trigger scale-up:
  Warning  FailedScheduling   0s (x6 over 20m)     default-scheduler   0/2 nodes are available: 2 node(s) didn't satisfy existing pods anti-affinity rules. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod..
```

### What did you expect to happen?

As per the anti affinity logic stated, the third pod should be scheduled as there are no other pod with `custom-app: aj` label exists on the nodes.

```
// This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching
// the labelSelector in the specified namespaces, where co-located is defined as running on a node
// whose value of the label with key topologyKey matches that of any node on which any of the
// selected pods is running.
```

### How can we reproduce it (as minimally and precisely as possible)?

Steps to reproduce:
1. Create two nodes cluster
2. Create the following two pod `pod1` and `pod2` without the label `custom-app: aj`. Verify that they are scheduled to different nodes.
3. Create the Pod3 with the label `custom-app: aj` and see it is still in pending state even when there are no pods with `custom-app: aj` label present on the nodes.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.11-gke.1019001
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
