### ISSUE TITLE
rolling-update (1.0.3): v2 rc cannot have same name as v1 rc

### ISSUE THREAD

**Issue by mcbain** [kubernetes/kubernetes#12680]
I want to keep the name of the rc. This currently only work when using a --image replacement:
```bash
kubectl rolling-update demo --image=nginx:1.9.3
```

This does not work.
```bash
kubectl rolling-update demo -f rc-v2.yaml
// cannot have the same name as the existing ReplicationController demo
```

Versionize the rc-name e.g. demo-v2 does not really make sense to me, since it must be specified as 'from' in the rolling-update command. Say, although the current version is v5, no one knows whether to use v4 or - due an error before - v3 or even both?!

Any ideas?

rc-v1.yaml
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: demo
  name: demo
spec:
  replicas: 1
  selector:
    name: demo
    version: v1
  template:
    metadata:
      labels:
        name: demo
        version: v1
    spec:
      containers:
        -
          image: nginx:1.9.1
          name: demo
          ports:
            - containerPort: 80
```

rc-v2.yaml
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: demo
  name: demo
spec:
  replicas: 3
  selector:
    name: demo
    version: v2
  template:
    metadata:
      labels:
        name: demo
        version: v2
    spec:
      containers:
        -
          image: nginx:1.9.3
          name: demo
          ports:
            - containerPort: 80
```
