### ISSUE TITLE
ReplicaSet do not update latest failure condition into status

### ISSUE THREAD

**Issue by hope792** [kubernetes/kubernetes#127081]
### What happened?

If I have 2 admissions to check before a POD can be create, the 2 admissions checks run one after one (not in parallel), with 2 different error messages.
I'll use the below admission check for POD creation as an example to reproduce the bug:
```
if currentTime.Minute() < 40 {
		admissionResponse.Allowed = false
		admissionResponse.Result = &metav1.Status{
			Reason:  metav1.StatusReasonForbidden,
			Message: "Pod creation is not allowed during the first 40 minutes of the hour.",
		}
	} else {
		admissionResponse.Allowed = false
		admissionResponse.Result = &metav1.Status{
			Reason:  metav1.StatusReasonForbidden,
			Message: "Pod creation is not allowed during the second 20 minutes of the hour.",
		}
	}
```
Which means, in the first 40 minutes of every hour, the error message will be "Pod creation is not allowed during the first 40 minutes of the hour.", while in the left 20 minutes of every hour, the error message will be "Pod creation is not allowed during the second 20 minutes of the hour".

If I create a deployment now, in the left 20 minutes (xx:40 - xx:59), the ReplicaSet will be:
Describe result:
```
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                 From                   Message
  ----     ------        ----                ----                   -------
  Warning  FailedCreate  40m (x19 over 95m)  replicaset-controller  Error creating: admission webhook "pod-blocker-service.pod-blocker.com" denied the request: Pod creation is not allowed during the first 40 minutes of the hour.
  Warning  FailedCreate  7m2s (x4 over 84m)  replicaset-controller  Error creating: admission webhook "pod-blocker-service.pod-blocker.com" denied the request: Pod creation is not allowed during the second 20 minutes of the hour.
```
Status:
```
status:
  conditions:
  - lastTransitionTime: "2024-09-03T02:31:25Z"
    message: 'admission webhook "pod-blocker-service.pod-blocker.com" denied the request:
      Pod creation is not allowed during the first 40 minutes of the hour.'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 1
  replicas: 0
```
Apparently, the second error message "Pod creation is not allowed during the second 20 minutes of the hour." is not updated into the status condition.

### What did you expect to happen?

The status shows the up to date error condition:
```
status:
  conditions:
  - lastTransitionTime: "2024-09-03T02:31:25Z"
    message: 'admission webhook "pod-blocker-service.pod-blocker.com" denied the request:
      Pod creation is not allowed during the second 20 minutes of the hour.'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 1
  replicas: 0
```

### How can we reproduce it (as minimally and precisely as possible)?

Just create 2 admissions to block POD creation one by one, with different error message.
After a period of time, let the first admission pass, and the second admission continue to block.

Which should show the error message from the second admission in the ReplicaSet status condition.

### Anything else we need to know?

It appears this block of code introduced the above behavior: https://github.com/kubernetes/kubernetes/blob/e5bafe2bed13fe72e88a3597930bdfbab5267e9d/pkg/controller/replicaset/replica_set_utils.go#L110

It only set condition when failed condition is `nil`; if the failed condition is still there, it just won't set the up to date condition.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-22T05:28:27Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/arm64"}
```

But from the code, it seems still in the latest version

</details>

### Cloud provider

<details>
Reproduced on KinD
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig apps

> $ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-22T05:28:27Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/arm64"}


please verify if this happens with a supported version:
https://kubernetes.io/releases/

your version is out of support

**Comment by hope792** [comment]
> /sig apps
> 
> > $ kubectl version
> > WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
> > Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
> > Kustomize Version: v4.5.4
> > Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-22T05:28:27Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/arm64"}
> 
> please verify if this happens with a supported version: https://kubernetes.io/releases/
> 
> your version is out of support

@neolit123 , I tested in the latest server version 1.31.0, the bug still exists:

```
$kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.0", GitCommit:"9edcffcde5595e8a5b1a35f88c421764e575afce", GitTreeState:"clean", BuildDate:"2024-08-13T22:46:38Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.24) and server (1.31) exceeds the supported minor version skew of +/-1

```

**Comment by chengjoey** [comment]
/assign

I can reproduce it

**Comment by chengjoey** [comment]
Add the information I reproduced:

I used an addmission webhook to reproduce the problem. The logic of the judgment is roughly as follows:
```
func (n timeValidator) Validate(pod *corev1.Pod) (validation, error) {
	createStr := pod.Labels["createAt"]
	if createStr == "" {
		return validation{
			Valid: true,
		}, nil
	}
	createAt, err := time.Parse("2006-01-02-15-04-05", createStr)
	if err != nil {
		return validation{
			Valid: true,
		}, nil
	}
	subTime := time.Now().UTC().Add(8 * time.Hour).Sub(createAt)
	if subTime.Minutes() < 5 {
		return validation{
			Valid:  false,
			Reason: "pod is too young less than 5 minutes",
		}, nil
	}
	if subTime.Minutes() < 40 && subTime.Minutes() > 5 {
		return validation{
			Valid:  false,
			Reason: "pod is too young less than 40 minutes",
		}, nil
	}

	return validation{Valid: true, Reason: "valid time"}, nil
}
```
It gets the `createAt` from the pod label and compares it with the current time, returning different validations

Then I created a deployment, specifying the `createAt` label
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        createAt: "2024-09-04-14-54-00"
```

then get rs `kubectl get rs apps-6c5fd57fd4 -n apps -o yaml`:
```
        imagePullPolicy: Always
        name: lifespan-offensive
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-09-04T06:57:34Z"
    message: 'admission webhook "simple-kubernetes-webhook.acme.com" denied the request:
      pod is too young less than 5 minutes'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 1
  replicas: 0
```

the message always `pod is too young less than 5 minutes`

admission webhook logs:
```
time="2024-09-04T06:58:15Z" level=debug msg="{\"message\":\"pod is too young less than 5 minutes\",\"code\":403}}}" uri="/validate-pods?timeout=2s"
time="2024-09-04T06:58:56Z" level=debug msg="received mutation request" uri="/mutate-pods?timeout=2s"
time="2024-09-04T06:58:56Z" level=info msg="no lifespan label found, applying default lifespan toleration" min_lifespan=0 mutation=min_lifespan pod_name=apps-6c5fd57fd4-
time="2024-09-04T06:58:56Z" level=debug msg="pod env injected {KUBE true nil}" mutation=inject_env pod_name=apps-6c5fd57fd4-
time="2024-09-04T06:58:56Z" level=debug msg="sending response" uri="/mutate-pods?timeout=2s"
time="2024-09-04T06:58:56Z" level=debug msg="{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1\",\"response\":{\"uid\":\"be1ef3cc-fc5c-40cf-b5e2-135a368c7902\",\"allowed\":true,\"patch\":\"W3sib3AiOiJhZGQiLCJwYXRoIjoiL3NwZWMvY29udGFpbmVycy8wL2VudiIsInZhbHVlIjpbeyJuYW1lIjoiS1VCRSIsInZhbHVlIjoidHJ1ZSJ9XX0seyJvcCI6ImFkZCIsInBhdGgiOiIvc3BlYy90b2xlcmF0aW9ucy8tIiwidmFsdWUiOnsiZWZmZWN0IjoiTm9TY2hlZHVsZSIsImtleSI6ImFjbWUuY29tL2xpZmVzcGFuLXJlbWFpbmluZyIsIm9wZXJhdG9yIjoiRXhpc3RzIn19XQ==\",\"patchType\":\"JSONPatch\"}}" uri="/mutate-pods?timeout=2s"
time="2024-09-04T06:58:56Z" level=debug msg="received validation request" uri="/validate-pods?timeout=2s"
time="2024-09-04T06:58:56Z" level=info msg="delete me" pod_name=apps-6c5fd57fd4-g2vrv
time="2024-09-04T06:58:56Z" level=debug msg="sending response" uri="/validate-pods?timeout=2s"
time="2024-09-04T06:58:56Z" level=debug msg="{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1\",\"response\":{\"uid\":\"a862f019-e9c0-4f55-ade7-edd45486320f\",\"allowed\":false,\"status\":{\"metadata\":{},\"message\":\"pod is too young less than 5 minutes\",\"code\":403}}}" uri="/validate-pods?timeout=2s"
time="2024-09-04T07:00:18Z" level=debug msg="received mutation request" uri="/mutate-pods?timeout=2s"
time="2024-09-04T07:00:18Z" level=info msg="no lifespan label found, applying default lifespan toleration" min_lifespan=0 mutation=min_lifespan pod_name=apps-6c5fd57fd4-
time="2024-09-04T07:00:18Z" level=debug msg="pod env injected {KUBE true nil}" mutation=inject_env pod_name=apps-6c5fd57fd4-
time="2024-09-04T07:00:18Z" level=debug msg="sending response" uri="/mutate-pods?timeout=2s"
time="2024-09-04T07:00:18Z" level=debug msg="{\"kind\":\"AdmissionReview\",\"apiVersion\":\"admission.k8s.io/v1\",\"response\":{\"uid\":\"5e7b1107-03b4-4b88-8e8b-7f3b98241799\",\"allowed\":true,\"patch\":\"W3sib3AiOiJhZGQiLCJwYXRoIjoiL3NwZWMvY29udGFpbmVycy8wL2VudiIsInZhbHVlIjpbeyJuYW1lIjoiS1VCRSIsInZhbHVlIjoidHJ1ZSJ9XX0seyJvcCI6ImFkZCIsInBhdGgiOiIvc3BlYy90b2xlcmF0aW9ucy8tIiwidmFsdWUiOnsiZWZmZWN0IjoiTm9TY2hlZHVsZSIsImtleSI6ImFjbWUuY29tL2xpZmVzcGFuLXJlbWFpbmluZyIsIm9wZXJhdG9yIjoiRXhpc3RzIn19XQ==\",\"patchType\":\"JSONPatch\"}}" uri="/mutate-pods?timeout=2s"
time="2024-09-04T07:00:18Z" level=debug msg="received validation request" uri="/validate-pods?timeout=2s"
time="2024-09-04T07:00:18Z" level=info msg="delete me" pod_name=apps-6c5fd57fd4-npqtc
time="2024-09-04T07:00:18Z" level=debug msg="sending response" uri="/validate-pods?timeout=2s"
time="2024-09-04T07:00:18Z" level=debug msg="{\"message\":\"pod is too young less than 40 minutes\",\"code\":403}}}" uri="/validate-pods?timeout=2s"
```
return message already changed to `pod is too young less than 40 minutes`

replicaset controller logs:
```
E0904 06:57:55.100273       1 replica_set.go:557] sync "apps/apps-6c5fd57fd4" failed with admission webhook "simple-kubernetes-webhook.acme.com" denied the request: pod is too young less than 5 minutes
I0904 06:58:15.594968       1 replica_set.go:676] "Finished syncing" logger="replicaset-controller" kind="ReplicaSet" key="apps/apps-6c5fd57fd4" duration="13.435883ms"
E0904 06:58:15.595052       1 replica_set.go:557] sync "apps/apps-6c5fd57fd4" failed with admission webhook "simple-kubernetes-webhook.acme.com" denied the request: pod is too young less than 5 minutes
I0904 06:58:56.577231       1 replica_set.go:676] "Finished syncing" logger="replicaset-controller" kind="ReplicaSet" key="apps/apps-6c5fd57fd4" duration="20.88323ms"
E0904 06:58:56.577346       1 replica_set.go:557] sync "apps/apps-6c5fd57fd4" failed with admission webhook "simple-kubernetes-webhook.acme.com" denied the request: pod is too young less than 5 minutes
I0904 07:00:18.515753       1 replica_set.go:676] "Finished syncing" logger="replicaset-controller" kind="ReplicaSet" key="apps/apps-6c5fd57fd4" duration="17.43277ms"
E0904 07:00:18.515816       1 replica_set.go:557] sync "apps/apps-6c5fd57fd4" failed with admission webhook "simple-kubernetes-webhook.acme.com" denied the request: pod is too young less than 40 minutes
I0904 07:03:02.412787       1 replica_set.go:676] "Finished syncing" logger="replicaset-controller" kind="ReplicaSet" key="apps/apps-6c5fd57fd4" duration="54.863571ms"
E0904 07:03:02.413179       1 replica_set.go:557] sync "apps/apps-6c5fd57fd4" failed with admission webhook "simple-kubernetes-webhook.acme.com" denied the request: pod is too young less than 40 minutes
I0904 07:08:30.132437       1 replica_set.go:676] "Finished syncing" logger="replicaset-controller" kind="ReplicaSet" key="apps/apps-6c5fd57fd4" duration="37.377777ms"
E0904 07:08:30.132757       1 replica_set.go:557] sync "apps/apps-6c5fd57fd4" failed with admission webhook "simple-kubernetes-webhook.acme.com" denied the request: pod is too young less than 40 minutes
```

But the app rs condition message always shows `pod is too young less than 5 minutes`
```
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-09-04T06:57:34Z"
    message: 'admission webhook "simple-kubernetes-webhook.acme.com" denied the request:
      pod is too young less than 5 minutes'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 1
  replicas: 0
```
