### ISSUE TITLE
Network Ports Grouping

### ISSUE THREAD

**Issue by francislance** [kubernetes/kubernetes#127013]
### What would you like to be added?

Is it possible to have a group of ports that is reusable by many policies. Something like:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPorts
metadata:
  name: internet-ports
spec:
  ports:
    - protocol: TCP
      port: 80  # HTTP
    - protocol: TCP
      port: 443  # HTTPS
    - protocol: TCP
      port: 53  # DNS TCP
    - protocol: UDP
      port: 53  # DNS UDP
```
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: outgoing-internet-policy
  namespace: mynamespace
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0  # Allows to all external IP addresses (the internet)
      ports:
        refNetworkPorts: internet-ports
```

### Why is this needed?

To keep it DRY. Reusable objects similar to Cisco object-groups.
