### ISSUE TITLE
Cannot mount the same PVC multiple times on one Pod

### ISSUE THREAD

**Issue by songjiaxun** [kubernetes/kubernetes#127004]
### What happened?

When I mount the same PVC multiple times on one Pod, the Pod is stuck in `containerCreating` state.

Same issue described here: https://stackoverflow.com/questions/65931457/why-cant-i-mount-the-same-pvc-twice-with-different-subpaths-to-single-pod

### What did you expect to happen?

The mount of volumes should succeed, and the Pod should be created successfully.

Or, if Kubernetes treats this as a mis-configuration, a clear error message should be returned.

### How can we reproduce it (as minimally and precisely as possible)?

I am testing on a GKE cluster. The same PVC is used by one Pod twice.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi  
  storageClassName: standard  
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx  
    volumeMounts:
    - name: my-pvc
      mountPath: /data/path1
    - name: my-pvc-2
      mountPath: /data/path2
  volumes:
  - name: my-pvc
    persistentVolumeClaim:
      claimName: my-claim  
  - name: my-pvc-2
    persistentVolumeClaim:
      claimName: my-claim  
```

### Anything else we need to know?

We have another similar issue documented: https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/48

According to the kubelet code: https://github.com/kubernetes/kubernetes/blob/8f15859afc9cfaeb05d4915ffa204d84da512094/pkg/kubelet/volumemanager/cache/desired_state_of_world.go#L296-L298

> For non-attachable and non-device-mountable volumes, generate a unique name based on the pod namespace and name and the name of the volume within the pod.

Since the user has two same PVCs specified on the Pod spec, the tow PVCs must bound to the same PV, meaning the `volumeHandle` is the same for the two volumes. Therefore, different volumes will be treated as the same volume. After kubelet mounts one of the volumes, the other volume will be treated as already mounted. As a result, the Pod will be stuck in volume mount stage.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6-gke.1326000
```

Note that this issue is not limited to any specific k8s verisons.

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by thisisharrsh** [comment]
Hi @songjiaxun, thanks for reporting the issue, I have also reproduced the issue on my cluster and facing a similar error.

**Comment by thisisharrsh** [comment]
Have you tried using the `subPath` feature in `volumeMounts` instead of mounting the same PVC multiple times?

**Comment by chengjoey** [comment]
https://github.com/kubernetes/kubernetes/blob/ed373709d839b9410a2e410558f5e6bf2ba0e7b0/pkg/kubelet/volumemanager/volume_manager.go#L536-L542

https://github.com/kubernetes/kubernetes/blob/ed373709d839b9410a2e410558f5e6bf2ba0e7b0/pkg/volume/util/operationexecutor/operation_executor.go#L696-L718

Because `my-pvc` and `my-pvc-2` use the same pvc, uniqueVolumeName is the same, resulting in `OuterVolumeSpecName` being overwritten by `my-pvc-2`

`vm.actualStateOfWorld.GetMountedVolumesForPod` should return `my-pvc` and `my-pvc-2`


logs:
```
Aug 31 12:33:14 minikube kubelet[920248]: I0831 12:33:14.140813  920248 volume_manager.go:546] "expectedVolumes" expectedVolumes=["my-pvc","my-pvc-2","kube-api-access-gr24m"]
Aug 31 12:33:14 minikube kubelet[920248]: I0831 12:33:14.440318  920248 volume_manager.go:545] "mountedVolumes" mountedVolumes={"kube-api-access-gr24m":{},"my-pvc-2":{}}
Aug 31 12:33:14 minikube kubelet[920248]: I0831 12:33:14.440387  920248 volume_manager.go:546] "expectedVolumes" expectedVolumes=["my-pvc","my-pvc-2","kube-api-access-gr24m"]
Aug 31 12:33:14 minikube kubelet[920248]: I0831 12:33:14.740446  920248 volume_manager.go:545] "mountedVolumes" mountedVolumes={"kube-api-access-gr24m":{},"my-pvc-2":{}}
Aug 31 12:33:14 minikube kubelet[920248]: I0831 12:33:14.740496  920248 volume_manager.go:546] "expectedVolumes" expectedVolumes=["my-pvc","my-pvc-2","kube-api-access-gr24m"]
Aug 31 12:33:15 minikube kubelet[920248]: I0831 12:33:15.040952  920248 volume_manager.go:545] "mountedVolumes" mountedVolumes={"kube-api-access-gr24m":{},"my-pvc-2":{}}
```

**Comment by chengjoey** [comment]
add events:
```
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason  Age                   From     Message
  ----     ------  ----                  ----     -------
  Warning  Failed  117s (x2 over 4m12s)  kubelet  Failed to make pod data directories: unmounted volumes=[my-pvc], unattached volumes=[], failed to process volumes=[my-pvc]: context deadline exceeded
```

**Comment by xing-yang** [comment]
There's a potential fix submitted for this issue: https://github.com/kubernetes/kubernetes/pull/122140

**Comment by msau42** [comment]
This works if you reference the same volume in the `volumeMounts`:

```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx  
    volumeMounts:
    - name: my-pvc
      mountPath: /data/path1
    - name: my-pvc
      mountPath: /data/path2
  volumes:
  - name: my-pvc
    persistentVolumeClaim:
      claimName: my-claim  
```

**Comment by msau42** [comment]
The use case where you may want 2 pvs to reference the same volumeHandle is where you may have different mount options, so you actually do want two different mounts.

**Comment by john8329** [comment]
Additionally the `subPath` can be specified. This works:
```yaml
          volumeMounts:
            - mountPath: /srv/app/files
              name: backend-files
              subPath: files
            - mountPath: /srv/app/logs
              name: backend-logs
              subPath: logs
            - mountPath: /srv/app/configs
              name: backend-files
              subPath: configs
      volumes:
        - name: backend-files
          persistentVolumeClaim:
            claimName: app-backend-files-pvc
        - name: backend-logs
          persistentVolumeClaim:
            claimName: app-backend-logs-pvc
```

**Comment by fajfer** [comment]
Thanks guys, got confused but last few bits helped me get some TrueCharts to work
```yaml
        - name: "persistence.foo.targetSelector.bar.mountPath"
          value: "/some/path"
        - name: "persistence.foo.existingClaim"
          value: my-claim
```

**Comment by romilbhardwaj** [comment]
Running into the same issue on Kubernetes v1.32. Here's a minimal repro:

```
apiVersion: v1
kind: Pod
metadata:
  name: repro-broken
spec:
  restartPolicy: Never
  containers:
  - name: main
    image: busybox:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: vol-a
      mountPath: /mnt/a
    - name: vol-b
      mountPath: /mnt/b
  volumes:
  - name: vol-a
    persistentVolumeClaim:
      claimName: repro-pvc
  - name: vol-b
    persistentVolumeClaim:
      claimName: repro-pvc    # same PVC as vol-a → deadlock
```

Looks like it's fixed in https://github.com/kubernetes/kubernetes/pull/122140, available in k8s v1.35+.
