### ISSUE TITLE
mismatchLabelKeys matchLabelKeys not effective

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#127263]
### What happened?

```
cat <<EOF | kubectl apply -n k8s -f -
apiVersion: v1
kind: Pod
metadata:
  name: app-mysql
  labels:
    app: mysql
    app2: mysql2
    test: test
spec:
  nodeName: k8s-worker02
  containers:
  - name: mysqldb
    image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/examples-bookinfo-mysqldb:1.17.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123456"
    args: ["--default-authentication-plugin","mysql_native_password"]
    volumeMounts:
    - name: var-lib-mysql
      mountPath: /var/lib/mysql
  volumes:
  - name: var-lib-mysql
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: rating
  labels:
    app: rating
spec:
  containers:
  - name: ratings
    image: registry.cn-hangzhou.aliyuncs.com/hxpdocker/examples-bookinfo-ratings-v2:1.17.0
    imagePullPolicy: IfNotPresent
    env:
     - name: DB_TYPE
       value: "mysql"
     - name: MYSQL_DB_HOST
       value: localhost
     - name: MYSQL_DB_PORT
       value: "3306"
     - name: MYSQL_DB_USER
       value: root
     - name: MYSQL_DB_PASSWORD
       value: "123456"
    ports:
    - containerPort: 9080
    securityContext:
      runAsUser: 1000
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 10
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: analytics
            matchExpressions:
              - key: department
                operator: In
                values:
                - sales
              - key: department
                operator: NotIn
                values:
                - finance
          topologyKey: "kubernetes.io/hostname"
          namespaceSelector:
            matchLabels:
              project: myproject 
      - weight: 90
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: mysql
          topologyKey: "kubernetes.io/hostname"
          mismatchLabelKeys:
          - test
          matchLabelKeys:
          - app3
          namespaces:
          - k8s
EOF
```

root@k8s-master01:~# kubectl get pod -owide -n k8s
NAME        READY   STATUS    RESTARTS   AGE   IP            NODE           NOMINATED NODE   READINESS GATES
app-mysql   1/1     Running   0          10s   10.244.0.88   k8s-worker02   <none>           <none>
rating      1/1     Running   0          10s   10.244.0.87   k8s-worker02   <none>           <none>

![image](https://github.com/user-attachments/assets/b13a5955-e033-4778-96a4-2e357e589641)

![image](https://github.com/user-attachments/assets/98a2842f-ad89-4ad0-b122-b7bf65e6203b)
![image](https://github.com/user-attachments/assets/f0ee43d9-ac52-40b1-86df-6ef5bf6da53f)

### What did you expect to happen?

scheduler to difference node

### How can we reproduce it (as minimally and precisely as possible)?

apply the config,modify nodeName

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
1.31.0

### Cloud provider

<details>

</details>
wmware workstation

### OS version

<details>
ubuntu 2404
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
