### ISSUE TITLE
[InPlacePodVerticalScaling]Got RunContainerError when patch pod image and resources

### ISSUE THREAD

**Issue by ABNER-1** [kubernetes/kubernetes#127356]
### What happened?

In cluster which enable InPlacePodVerticalScaling, if update image and resources(scale up), the pod will be CrashLoopBackOff with reason "StartError" and message `failed to create containerd task: failed to create shim task: OCI
          runtime create failed: runc create failed: unable to start container process:
          error during container init: error setting cgroup config for procHooks process:
          failed to write "300000": write /sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-xxx.slice/cri-containerd-xxx.scope/cpu.cfs_quota_us:
          invalid argument: unknown`

### What did you expect to happen?

The pod can successfully updated with new image and new resources.

### How can we reproduce it (as minimally and precisely as possible)?

pod yaml: pod-simple.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: clone-test-pod
  namespace: default
spec:
  containers:
  - env:
    - name: test
      value: foo
    image: registry.k8s.io/e2e-test-images/nginx:1.14-4
    imagePullPolicy: IfNotPresent
    name: nginx
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: NotRequired
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
```

Create pod
```bash
kubectl apply -f pod-simple.yaml
```

Wait pod ready

Update image and resources

```bash
kubectl patch pod clone-test-pod --type='json' -p='[{"op": "replace", "path": "/spec/containers/0/image", "value":"registry.k8s.io/e2e-test-images/nginx:1.15-4"}, {"op": "replace", "path": "/spec/containers/0/resources/requests/cpu", "value": "200m"},{"op": "replace", "path": "/spec/containers/0/resources/requests/memory", "value": "200Mi"},{"op": "replace", "path": "/spec/containers/0/resources/limits/cpu", "value": "3"},{"op": "replace", "path": "/spec/containers/0/resources/limits/memory", "value": "3Gi"}]'
```

### Anything else we need to know?

Enable InPlacePodVerticalScaling

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here

Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1
```

</details>

### Cloud provider

<details>
I test in kind in github action and ack.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
