### ISSUE TITLE
nodeAffinityPolicy not effective

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#127342]
### What happened?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx
```

````
cat <<EOF | kubectl apply -n k8s -f -
apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: myapp
spec:
  containers:
  - name: web-server
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: In
            values:
            - web
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app: myapp
    nodeAffinityPolicy: Ignore
EOF
```

```
root@k8s-master01:~# kubectl get pod -n k8s -owide
NAME                                READY   STATUS              RESTARTS   AGE     IP              NODE           NOMINATED NODE   READINESS GATES
myapp-deployment-79bf885b89-8js64   1/1     Running             0          12m     10.244.79.145   k8s-worker01   <none>           <none>
myapp-deployment-79bf885b89-cs2w9   1/1     Running             0          12m     10.244.79.129   k8s-worker01   <none>           <none>
myapp-deployment-79bf885b89-g8lf7   1/1     Running             0          12m     10.244.0.89     k8s-worker02   <none>           <none>
myapp-deployment-79bf885b89-hcblx   1/1     Running             0          12m     10.244.0.90     k8s-worker02   <none>           <none>
myapp-deployment-79bf885b89-lfgbx   1/1     Running             0          12m     10.244.79.142   k8s-worker01   <none>           <none>
myapp-deployment-79bf885b89-zk6bj   0/1     ContainerCreating   0          12m     <none>          k8s-master01   <none>           <none>
web-server                          0/1     Pending             0          4m57s   <none>          <none>         <none>           <none>
```

pod should schedule to k8s-master01,but not
master01 do not have node-type label but     nodeAffinityPolicy: Ignore

### What did you expect to happen?

schedule to k8s-master01

### How can we reproduce it (as minimally and precisely as possible)?

do the experiment as me

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
1.31.0

</details>


### Cloud provider

<details>
vmware workstation
</details>


### OS version

<details>
unbunt 2404

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
