### ISSUE TITLE
removing a pod affinity doesn't take effect until pods are rolled

### ISSUE THREAD

**Issue by rsalmond** [kubernetes/kubernetes#127330]
### What happened?

after creating a deployment with a pod affinity, and then updating it (thus recreating all the pods) to have no affinity, the recreated pods remain under the influence of the removed affinity until they are recreated a second time.

### What did you expect to happen?

I would expect the pods to immediately obey the default topology spread constraint and be distributed across hosts and zones upon removal of the pod affinity.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx:latest
```

```console
$ k apply -f with-affinity.yaml
deployment.apps/nginx created

$ k get po -owide
NAME                     READY   STATUS    RESTARTS   AGE   IP            NODE                                 NOMINATED NODE   READINESS GATES
nginx-6866547996-245rz   1/1     Running   0          10s   10.116.0.40   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-6866547996-b4wck   1/1     Running   0          10s   10.116.0.38   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-6866547996-ch9vd   1/1     Running   0          10s   10.116.0.41   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-6866547996-j74gm   1/1     Running   0          10s   10.116.0.37   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-6866547996-kpmpg   1/1     Running   0          10s   10.116.0.42   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-6866547996-sz68c   1/1     Running   0          10s   10.116.0.39   gke-lab-default-pool-f642a75e-w308   <none>           <none>
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
```

```console
$ k apply -f without-affinity.yaml
deployment.apps/nginx configured

$ k get po -owide
NAME                     READY   STATUS    RESTARTS   AGE   IP            NODE                                 NOMINATED NODE   READINESS GATES
nginx-7584b6f84c-4j74c   1/1     Running   0          8s    10.116.0.45   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-7584b6f84c-d66cz   1/1     Running   0          5s    10.116.0.48   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-7584b6f84c-f8fch   1/1     Running   0          8s    10.116.0.43   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-7584b6f84c-tqtdf   1/1     Running   0          7s    10.116.0.46   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-7584b6f84c-vk6br   1/1     Running   0          8s    10.116.0.44   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-7584b6f84c-wg675   1/1     Running   0          6s    10.116.0.47   gke-lab-default-pool-f642a75e-w308   <none>           <none>

$ k rollout restart deploy/nginx
deployment.apps/nginx restarted

$ k get po -owide
NAME                     READY   STATUS    RESTARTS   AGE   IP            NODE                                 NOMINATED NODE   READINESS GATES
nginx-59f5fd959d-4mgzk   1/1     Running   0          7s    10.116.2.8    gke-lab-default-pool-c44628b2-1b70   <none>           <none>
nginx-59f5fd959d-525l9   1/1     Running   0          7s    10.116.0.49   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-59f5fd959d-92b28   1/1     Running   0          4s    10.116.0.50   gke-lab-default-pool-f642a75e-w308   <none>           <none>
nginx-59f5fd959d-ng8h4   1/1     Running   0          5s    10.116.1.17   gke-lab-default-pool-0ef416fe-thsr   <none>           <none>
nginx-59f5fd959d-pr9fn   1/1     Running   0          7s    10.116.1.16   gke-lab-default-pool-0ef416fe-thsr   <none>           <none>
nginx-59f5fd959d-vzv4d   1/1     Running   0          5s    10.116.2.9    gke-lab-default-pool-c44628b2-1b70   <none>           <none>
```

### Kubernetes version

<details>

```console
$ k version
Client Version: v1.29.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4-gke.1213000
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux 0 5.15.0-1066-gcp #74~20.04.1-Ubuntu SMP Fri Jul 26 09:28:41 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
