### ISSUE TITLE
kubelet fails to start pods after upgrade to 1.31.X

### ISSUE THREAD

**Issue by JumpMaster** [kubernetes/kubernetes#127316]
### What happened?

After the first controller upgrade from 1.30.4 to 1.31.0 and later 1.31.1. The kubelet service fails to start the majority of pods running on the controller.

### What did you expect to happen?

All pods should start as before the upgrade.

```
$ kubectl get pod -o wide --all-namespaces -w | grep controller2
calico-system     calico-node-p4fzm                                          0/1     CreateContainerConfigError   0              153m    192.168.16.112   kubecontroller2   <none>           <none>
calico-system     calico-typha-685957f77b-k2xf8                              0/1     CreateContainerConfigError   4 (122m ago)   40d     192.168.16.112   kubecontroller2   <none>           <none>
calico-system     csi-node-driver-b6jkc                                      0/2     CreateContainerConfigError   8 (122m ago)   40d     10.245.98.170    kubecontroller2   <none>           <none>
default           netdata-child-pctf4                                        0/2     CreateContainerConfigError   2 (122m ago)   11d     192.168.16.112   kubecontroller2   <none>           <none>
kube-system       etcd-kubecontroller2                                       1/1     Running                      1 (122m ago)   122m    192.168.16.112   kubecontroller2   <none>           <none>
kube-system       kube-apiserver-kubecontroller2                             1/1     Running                      1 (122m ago)   122m    192.168.16.112   kubecontroller2   <none>           <none>
kube-system       kube-controller-manager-kubecontroller2                    1/1     Running                      1 (122m ago)   122m    192.168.16.112   kubecontroller2   <none>           <none>
kube-system       kube-proxy-q2drw                                           0/1     CreateContainerConfigError   0              17h     192.168.16.112   kubecontroller2   <none>           <none>
kube-system       kube-scheduler-kubecontroller2                             1/1     Running                      1 (122m ago)   122m    192.168.16.112   kubecontroller2   <none>           <none>
kube-system       kube-vip-kubecontroller2                                   1/1     Running                      1 (122m ago)   122m    192.168.16.112   kubecontroller2   <none>           <none>
monitoring        kube-prometheus-stack-prometheus-node-exporter-gnwsj       0/1     CreateContainerConfigError   1 (122m ago)   5d1h    192.168.16.112   kubecontroller2   <none>           <none>
```

### How can we reproduce it (as minimally and precisely as possible)?

Basic Debian 12 VM used as a controller node. First controller upgraded from 1.30.4 to 1.31.0 and later to 1.31.1.

### Anything else we need to know?

Reinstalling kubelet 1.30.4 allows pods to start correctly.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4
```

</details>

### Cloud provider

<details>
Self hosted / metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux kubecontroller2 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd containerd.io 1.7.22 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico v3.28.1
</details>

**Comment by kannon92** [comment]
/triage needs-information

Can you share the pods that you are running? It looks like kubelet doesn’t like the envvar setup in your pods.

**Comment by kannon92** [comment]
https://github.com/kubernetes/kubernetes/issues/110977

TBH this sounds like it may be an issue with your setup. I can't reproduce this with kind or other clusters so I think you may need to troubleshoot it on your end.

**Comment by dims** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support

**Comment by JumpMaster** [comment]
> #110977
> 
> TBH this sounds like it may be an issue with your setup. I can't reproduce this with kind or other clusters so I think you may need to troubleshoot it on your end.

I'm sorry to hear that. It's a very basic setup without any customisation.

Is this error from the Kubelet relevant?

```
Sep 12 09:13:01 kubecontroller2 kubelet[6803]: E0912 09:13:01.625188    6803 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: \"spec.clusterIP\" is not a known field selector: only \"metadata.name\", \"metadata.namespace\"" logger="UnhandledError"
```

**Comment by JumpMaster** [comment]
Anyway to track this down further? I see no service using this selector

```
kubectl get svc --all-namespaces -o yaml | grep spec.clusterIP
```

**Comment by kannon92** [comment]
I am not sure. I don't know what kubecontroller2 is.

**Comment by kannon92** [comment]
Sorry @JumpMaster. We are not trying to be unhelpful here but I think you have an issue where whatever you have on your end is breaking for 1.31. This does not look to be a k8s issue at the moment. 

I know very little about calico and what your setup looks like. Maybe there is a patch of your pods via the calico controllers that is causing problems.

**Comment by JumpMaster** [comment]
Thanks @kannon92 

kubecontroller2 is one of the 3 kubernetes control-plane nodes. The only one that has been updated to 1.31.1.

```
$ kubectl get node
NAME              STATUS   ROLES           AGE    VERSION
kubecontroller1   Ready    control-plane   471d   v1.30.4
kubecontroller2   Ready    control-plane   470d   v1.31.1
kubecontroller3   Ready    control-plane   470d   v1.30.4
sonic             Ready    worker          471d   v1.30.4
tails             Ready    worker          471d   v1.30.4
knuckles          Ready    worker          470d   v1.30.4
```

After setting the log level to 8 I can see the kubelet is trying to run the following incorrect get request with the field selector spec.clusterIP but I cannot see why it would do such a thing.

```
Sep 12 15:57:55 kubecontroller2 kubelet[2477]: I0912 15:57:55.728232    2477 round_trippers.go:463] GET https://kubernetes.cluster.local:6443/api/v1/services?fieldSelector=spec.clusterIP%21%3DNone&limit=500&resourceVersion=0
```

**Comment by thockin** [comment]
It looks like an issue trying to use a field-selector: https://github.com/kubernetes/kubernetes/pull/123905/files

**Comment by thockin** [comment]
OK, in my own test env, I can say that it DOES work:

```
$ k get svc --field-selector='spec.clusterIP!=""'
NAME          TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
hostnames     ClusterIP   10.0.102.14   <none>        80/TCP,81/TCP   167d
kubernetes    ClusterIP   10.0.0.1      <none>        443/TCP         167d
```

It looks like this was cited: https://github.com/kubernetes/kubernetes/pull/123905#issuecomment-2260639787

The fix is supposed to be kubeadm feature-gate "ControlPlaneKubeletLocalMode" (https://github.com/kubernetes/kubernetes/pull/125582)

@JumpMaster does that apply to you?

This is unfortunate - we probaly should have done it in two releases.

**Comment by JumpMaster** [comment]
> get svc --field-selector='spec.clusterIP!=""'

That appears to be it. This isn't working for me on 1.30.4

```
$ kubectl get svc --field-selector='spec.clusterIP!=""'
Error from server (BadRequest): Unable to find "/v1, Resource=services" that match label selector "", field selector "spec.clusterIP!=\"\"": "spec.clusterIP" is not a known field selector: only "metadata.name", "metadata.namespace"
```

**Comment by JumpMaster** [comment]
Adding a host entry to allow the upgraded node to connect to itself solves the issue, and the field-selector works as intended when targeting the upgraded now.

**Comment by chrischdi** [comment]
In cluster-api we update the kubeadm-config ConfigMap in the cluster to enable/configure the feature gate before joining the new control-plane node.

**Comment by JumpMaster** [comment]
To resolve the issue I have edited the kubeadm-config configmap within kube-system to add the ControlPaleKuberletLocalMode flag as below

```
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      extraArgs:
      - name: authorization-mode
        value: Node,RBAC
    apiVersion: kubeadm.k8s.io/v1beta4
    caCertificateValidityPeriod: 87600h0m0s
    certificateValidityPeriod: 8760h0m0s
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: kubernetes.cluster.local:6443
    controllerManager: {}
    dns: {}
    encryptionAlgorithm: RSA-2048
    etcd:
      local:
        dataDir: /var/lib/etcd
++    featureGates:
++      ControlPlaneKubeletLocalMode: true
    imageRepository: registry.k8s.io
```

After adding the flag and upgrading a control node the /etc/kubernetes/kubelet.conf file is updated so the server field connects to the host itself rather then the cluster vip address.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
      CLUSTER-CERTIFICATE-REMOVED
--    server: https://kubernetes.cluster.local:6443
++    server: https://10.0.0.12:6443
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
    user: default-auth
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: default-auth
  user:
    client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
    client-key: /var/lib/kubelet/pki/kubelet-client-current.pem
```

So if a controller has already been upgraded and is now failing, changing the server address within kubelet.conf will return the node to service and adding the flag will make it permanent for future upgrades.

I don't know what the official or recommended fix will be but this is working well for me.
