### ISSUE TITLE
terminationMessagePolicy: "File" not effective

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#127531]
### What happened?

```
cat <<EOF | kubectl apply  -f -
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: container
    image: registry.cn-hangzhou.aliyuncs.com/hxpdocker2/term:1.0
    terminationMessagePath: "/tmp/my-termination-message"
    terminationMessagePolicy: "File"
    volumeMounts:
    - mountPath: /tmp/
      name: volume
    imagePullPolicy: Always
  nodeSelector:
    kubernetes.io/os: linux
  os:
    name: linux
  volumes:
  - name: volume
    hostPath:
      path: /tmp/
      type: Directory
EOF
```

root@k8s-master01:~/finalizer-operator-master# kubectl logs pod -f
2024/09/22 04:00:08 应用程序启动
2024/09/22 04:00:08 应用程序正在运行...
2024/09/22 04:01:07 收到信号: terminated, 正在关闭应用程序...
2024/09/22 04:01:09 清理工作完成，应用程序已关闭

root@k8s-master01:~/trident-operator# kubectl exec -it pod -- tail -f /tmp/my-termination-message

command terminated with exit code 137

```
package main

import (
    "log"
    "os"
    "os/signal"
    "syscall"
    "time"
)

func main() {
    // 设置日志
    logFile, err := os.OpenFile("app.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
    
    if err != nil {
        log.Fatalf("error opening log file: %v", err)
    }
    defer logFile.Close()

    log.SetOutput(os.Stdout)
    log.Println("应用程序启动")

    // 创建一个 channel 用于接收系统信号
    sigs := make(chan os.Signal, 1)
    // 监听 SIGTERM 和 SIGINT 信号
    signal.Notify(sigs, syscall.SIGTERM, syscall.SIGINT)

    go func() {
        // 等待接收信号
        sig := <-sigs
        log.Printf("收到信号: %s, 正在关闭应用程序...", sig)
        // 模拟清理工作
        time.Sleep(2 * time.Second)
        log.Println("清理工作完成，应用程序已关闭")
        time.Sleep(20 * time.Second)
        os.Exit(0)
    }()

    // 模拟应用程序的主循环
    for {
        log.Println("应用程序正在运行...")
        time.Sleep(1000 * time.Second)
    }
}

```

### What did you expect to happen?

/tmp/my-termination-message has message

### How can we reproduce it (as minimally and precisely as possible)?

apply the yaml

### Kubernetes version

<details>
1.31.0
</details>

### Cloud provider

<details>
wmware workstation
</details>

### OS version

<details>

ubuntu2404

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by niranjandarshann** [comment]
@13567436138 it depends on the working of kubernetes. According to me we can do it by changing the go code here you will find the code snippet  to be added .
```
// Write termination message to /tmp/my-termination-message
        terminationFile, err := os.OpenFile("/tmp/my-termination-message", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
        if err != nil {
            log.Fatalf("error opening termination message file: %v", err)
        }
        defer terminationFile.Close()

        terminationFile.WriteString("Application terminated gracefully.\n")
        os.Exit(0)
    }() 
```

**Comment by niranjandarshann** [comment]
Instead of it you can also change it instead of `app.log` 

```
// Set up log
    logFile, err := os.OpenFile("/tmp/my-termination-message", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
    if err != nil {
        log.Fatalf("error opening log file: %v", err)
    }
```

**Comment by niranjandarshann** [comment]
If you want to put the app.log file also and also to put termination message. Find the go code here. 
```

package main

import (
    "log"
    "os"
    "os/signal"
    "syscall"
    "time"
)

func main() {
    // Set up regular log file for application logs
    logFile, err := os.OpenFile("app.log", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
    if err != nil {
        log.Fatalf("error opening log file: %v", err)
    }
    defer logFile.Close()

    log.SetOutput(logFile)
    log.Println("应用程序启动")

    // Create a channel to receive system signals
    sigs := make(chan os.Signal, 1)
    // Listen for SIGTERM and SIGINT signals
    signal.Notify(sigs, syscall.SIGTERM, syscall.SIGINT)

    go func() {
        // Wait for termination signal
        sig := <-sigs
        log.Printf("收到信号: %s, 正在关闭应用程序...", sig)

        // Simulate cleanup work
        time.Sleep(2 * time.Second)
        log.Println("清理工作完成，应用程序已关闭")

        // Write termination message to /tmp/my-termination-message
        terminationFile, err := os.OpenFile("/tmp/my-termination-message", os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
        if err != nil {
            log.Fatalf("error opening termination message file: %v", err)
        }
        defer terminationFile.Close()

        terminationFile.WriteString("Application terminated gracefully.\n")
        os.Exit(0)
    }()

    // Simulate the main loop of the application
    for {
        log.Println("应用程序正在运行...")
        time.Sleep(1000 * time.Second)
    }
}

```

Its my point of view check for it and let me know if it fine for you ?

**Comment by 13567436138** [comment]
but the file is configed in yaml,how can i fix it in the code,if i change the yaml config of terminationMessagePath ,do i need to change the code

**Comment by niranjandarshann** [comment]
This is because the termination message does not contain the expected content.
We should do in such a way that before shutdown of the container termination message should be written to the file.

**Comment by niranjandarshann** [comment]
Try changing the yaml file 
With labels: in spec 
as lifecycle  and prestop,exec, command. I think it will work

**Comment by niranjandarshann** [comment]
```
lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "echo 'Apps terminating' > /tmp/my-termination-message"]
```

Try this in your yaml hope it will work.
