### ISSUE TITLE
Completed Jobs Not Fully Removed After EKS v1.29 Update

### ISSUE THREAD

**Issue by gciria** [kubernetes/kubernetes#127618]
### What happened?

I am experiencing an issue with completed Jobs in my Kubernetes cluster. Despite configuring my CronJobs to retain only 3 completed Jobs, I am seeing many more completed Jobs in `k9s` than in `kubectl`.

This issue started occurring after updating the EKS cluster to v1.29. In another cluster running EKS v1.28, this issue does not occur.

Here we can see the difference in jobs between `k9s` and `kubectl`:

![image](https://github.com/user-attachments/assets/b4dfbb65-f5e7-4090-950c-d49d87df8f99)

Removing the job `api-monitor-services-api-28787625-ssnn9`, we can see the kubelet removing it from the node:

![image](https://github.com/user-attachments/assets/ef478bcc-85b9-46cd-9f54-99d5af47c14c)

### What did you expect to happen?

I expected `k9s` to show the same number of completed Jobs as `kubectl`, which is 3. Additionally, I expected that the completed Jobs would be completely removed from the node, retaining only the 3 defined by the `successfulJobsHistoryLimit`.

### How can we reproduce it (as minimally and precisely as possible)?

All CronJobs created in my EKS v1.29 cluster are experiencing the same issue. Here is an example:

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-test
  namespace: cronjob-test
  labels:
    app: cronjob-test
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
            app: cronjob-test
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: xxxx
              imagePullPolicy: IfNotPresent
```
After 4 or more executions, check the Jobs:
```yaml
kubectl get jobs -n cronjob-test
```
In k9s
```
k9s -n cronjob-test
```
Using k9s, remove the first completed Job and leave the last three. In the kubelet logs, you will see the Job being deleted.

### Anything else we need to know?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.9
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8-eks-a737599
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console

# EKS v1.29

# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
$ uname -a
5.10.224-212.876.amzn2.x86_64 #1 SMP Thu Aug 22 16:55:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
