### ISSUE TITLE
plugin returned version client.authentication.k8s.io/__internal

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#127694]
### What happened?

root@k8s-master01:~# kubectl get pod
123456
Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1, plugin returned version client.authentication.k8s.io/__internal

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSFZOS3NCaDNwTVF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNU1ERXlNelF4TWpaYUZ3MHpOREE0TXpBeU16UTJNalphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUROU29BVG1zaTJ3YXpJUk1TT1UyNzNjYVpCdm82Z0FnS0g5T1hYYXhzODdIV2ZUaWcrRHVNYlM1NUIKN05aOEZUWjBNVkUvZmVUNVpzZG1pZTN5SDlFK3dmQXRMclBRMWJsRkJFdDV4bDNvWjYxamdQdzZseEFrMWxjOAo3QlZEVGFPUFNMMktZbXZKL0Yya2phMTdtOEFvMnp3azJJMkJqbzRjdVYzdGl1dzA5czQwMmEvd3lSWWRHYzBoCjFUamxRZHk3TW9NZk9mNFBwdmdyeVVuSHZWQ0RLVXBNaG1URVFZcXk0NnhYdjFIbVdaWm9ZWjQwUDZ0UmJJajgKYndiUXhSeWFDdnBoRkdZakt4cjIzc2JETWRKS2ljZ0lqU2pMTU1CZklNWWQvcGdhTzRnWTU5Zm95dEdncVUwVApDUnZydmFVbjRkeXFqRE5sVUlDOUJURmI1eXREQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTcWk0eVZMZk84Sy8rMU9PRHMzR3hLREU3cUpUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRREtRQlFQNEpCSgoySGZZWlN3dGtvb1J3SGRLNXFrUk1MMlRtMDIxRU91TVhyTVR0RWc5Wmwrb0lpNXc3T2tKNGdFSVlNQUo4eXZhCnNnV2tCQ2lEVEM5Z3FaWk9RL1BrYm04VU1jRTNrSWJFcmt1REw1N2IzU1pid3p2NmtKNC9rd0cwOUZoUU8wb0kKWXFxQ1RiMVpKbzRNQW0ydXZUeFhIY2lxdWhpUHM3cEc4dTBNOTFydGk2REJDME5hNGlrUUZob002NmUrWEJIYgpqZ0duanpDU05uN1UzQzhIbWtUdEJsclphOWE5RFBXMi8wdWRXYy81WU5WV2kwN1dWU1NvVkFweXZGaURWODk5Cmp0cDI5emx4S2J1R09EWFhmVFJGdXRvSnIzWGRlMUI1VUoza0M2MmtWY1FJaCs4cnZFN3l3QlhmdTRXdE04ZXgKV3E0cG4rRktCVDBnCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.229.180:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: krb5-user
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: krb5-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: kinit
      interactiveMode: Always
      args:
        - root/admin@EXAMPLE.COM

```

### What did you expect to happen?

login success

### How can we reproduce it (as minimally and precisely as possible)?

install kerberos server and client,config .kube/config

### Kubernetes version

<details>
1.31.0

</details>

### Cloud provider

<details>
vmware workstation
</details>

### OS version

<details>

ubuntu2404
```

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 13567436138** [comment]
![image](https://github.com/user-attachments/assets/fa3e5ef7-6fd7-4af3-94a2-8c7730a4f118)
the registry version is internal

**Comment by 13567436138** [comment]
![image](https://github.com/user-attachments/assets/7a1219a1-4eaa-49e0-86f6-f2cd03fd8b26)
error is here

**Comment by liggitt** [comment]
That indicates the exec plugin is not returning a response in the correct version. Check the output of the plugin and ensure it is returning data with the correct apiVersion and kind

**Comment by 13567436138** [comment]
but I think my config is wright

**Comment by 13567436138** [comment]
\reopen

**Comment by liggitt** [comment]
What is the serialized response of the exec plugin? Are you able to write that out and capture it in a file to verify the apiVersion and kind it is returning?

**Comment by 13567436138** [comment]
```
#!/usr/bin/env python3

import subprocess
import json
import sys
import time

def main():
    # 获取 kinit 命令行参数
    if len(sys.argv) < 2:
        print("Usage: kinit_exec.py <principal>")
        sys.exit(1)

    principal = sys.argv[1]

    # 提示用户输入密码
    password = input("请输入密码: ")

    # 执行 kinit 命令
    try:
        process = subprocess.Popen(
            ['kinit', principal],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )

        # 将密码写入 kinit 的标准输入
        stdout, stderr = process.communicate(input=password + '\n')

        if process.returncode != 0:
            print(f"Failed to run kinit: {stderr}", file=sys.stderr)
            sys.exit(1)

        # 获取当前时间和过期时间
        expiration_time = time.time() + 3600  # 假设凭证有效期为1小时
        expiration_timestamp = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime(expiration_time))

        # 输出符合 Kubernetes exec 规范的 JSON
        output = {
            "kind": "ExecCredential",
            "apiVersion": "client.authentication.k8s.io/v1",
            "status": {
                "token": "YOUR_JWT_TOKEN",  # 这里需要获取实际的 token
                "expirationTimestamp": expiration_timestamp
            }
        }

        print(json.dumps(output))

    except Exception as e:
        print(f"An error occurred: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
```
even I return the right version,the same error

**Comment by 13567436138** [comment]
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSFZOS3NCaDNwTVF3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBNU1ERXlNelF4TWpaYUZ3MHpOREE0TXpBeU16UTJNalphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUROU29BVG1zaTJ3YXpJUk1TT1UyNzNjYVpCdm82Z0FnS0g5T1hYYXhzODdIV2ZUaWcrRHVNYlM1NUIKN05aOEZUWjBNVkUvZmVUNVpzZG1pZTN5SDlFK3dmQXRMclBRMWJsRkJFdDV4bDNvWjYxamdQdzZseEFrMWxjOAo3QlZEVGFPUFNMMktZbXZKL0Yya2phMTdtOEFvMnp3azJJMkJqbzRjdVYzdGl1dzA5czQwMmEvd3lSWWRHYzBoCjFUamxRZHk3TW9NZk9mNFBwdmdyeVVuSHZWQ0RLVXBNaG1URVFZcXk0NnhYdjFIbVdaWm9ZWjQwUDZ0UmJJajgKYndiUXhSeWFDdnBoRkdZakt4cjIzc2JETWRKS2ljZ0lqU2pMTU1CZklNWWQvcGdhTzRnWTU5Zm95dEdncVUwVApDUnZydmFVbjRkeXFqRE5sVUlDOUJURmI1eXREQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTcWk0eVZMZk84Sy8rMU9PRHMzR3hLREU3cUpUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRREtRQlFQNEpCSgoySGZZWlN3dGtvb1J3SGRLNXFrUk1MMlRtMDIxRU91TVhyTVR0RWc5Wmwrb0lpNXc3T2tKNGdFSVlNQUo4eXZhCnNnV2tCQ2lEVEM5Z3FaWk9RL1BrYm04VU1jRTNrSWJFcmt1REw1N2IzU1pid3p2NmtKNC9rd0cwOUZoUU8wb0kKWXFxQ1RiMVpKbzRNQW0ydXZUeFhIY2lxdWhpUHM3cEc4dTBNOTFydGk2REJDME5hNGlrUUZob002NmUrWEJIYgpqZ0duanpDU05uN1UzQzhIbWtUdEJsclphOWE5RFBXMi8wdWRXYy81WU5WV2kwN1dWU1NvVkFweXZGaURWODk5Cmp0cDI5emx4S2J1R09EWFhmVFJGdXRvSnIzWGRlMUI1VUoza0M2MmtWY1FJaCs4cnZFN3l3QlhmdTRXdE04ZXgKV3E0cG4rRktCVDBnCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://192.168.229.180:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: krb5-user
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: krb5-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      command: ./kinit_exec.py
      interactiveMode: Always
      args:
        - root/admin@EXAMPLE.COM
```
