### ISSUE TITLE
Ephemeral storage exhausted by users not mounting the emptyDir

### ISSUE THREAD

**Issue by dimm0** [kubernetes/kubernetes#127642]
### What happened?

A user requested/limited ephemeral storage, but forgot to mount the emptyDir volume. The application was writing data to the snapshot of the image in containerd, which went to mounted /var/lib/containerd folder and not /var/lib/kubelet. Kubelet is watching the size of /var/lib/kubelet and was not evicting the pod, which resulted in /var/lib/containerd overfilled and node not responsive.

### What did you expect to happen?

Not sure, but current ephemeral storage mechanism is not intuitive to users. The data goes in 2 different folders and there's no control over the containerd snapshots size from kubernetes side.

### How can we reproduce it (as minimally and precisely as possible)?

Limit ephemeral storage, not create the emptyDir volume, write some data to /tmp and see /var/lib/containerd getting overfilled.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.28.11
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux k8s-epyc-01.sdsc.optiputer.net 5.4.0-195-generic #215-Ubuntu SMP Fri Aug 2 18:28:05 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd/now 1.7.2-0ubuntu1~20.04.1 amd64 [installed,upgradable to: 1.7.12-0ubuntu2~20.04.1]
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by thisisharrsh** [comment]
I've have also observed an issue where a pod with limited ephemeral storage was deployed without an `emptyDir` volume.

**Comment by jsafrane** [comment]
/sig node
Container writable layer is managed by the container runtime. I am not sure how quota works there

**Comment by haircommander** [comment]
I think this is something that setting a nodefs eviction signal could help with. Do you have eviction enabled @dimm0? I'm not sure we can add validation on the pod spec that the ephemeral volume is actually used by the container (without a feature, at least), so this may be working as intended. Eviction could help in this case, but ultimately having a properly setup pod spec is the best option

/triage needs-information

**Comment by dimm0** [comment]
Once the job fills up the container runtime storage, a bunch of system pods (correct ones) and other users jobs (also correct ones) get evicted and the node becomes completely broken. Then they try starting again and fail. The cluster becomes a complete mess if such user has submitted a bunch of broken jobs. From the user's perspective it's totally fine - they requested X GB of ephemeral storage and wrote less than X GB.

Currently there's no way to only evict the broken pod or to distinguish between runtime storage and kubelet storage. Even to monitor such case via prometheus metrics (only the node exporter stuff, which doesn't point at particular pod)

**Comment by AnishShah** [comment]
unable to reproduce this with the following pod. I noticed that the `disk-eater` pod is evicted once its disk usage reaches 5GiB.

```
apiVersion: v1
kind: Pod
metadata:
  name: disk-eater
spec:
  containers:
  - name: disk-eater
    image: busybox
    command: ["sh", "-c", "dd if=/dev/zero of=/file bs=1G count=1024;"]
    resources:
      limits:
        ephemeral-storage: 5Gi
      requests:
        ephemeral-storage: 5Gi
```

We also have a few e2e tests that evicts pod when the data is written to writable layers. can you give a repro script?

**Comment by dimm0** [comment]
Yes, will try to repro. Thanks!

**Comment by AnishShah** [comment]
maybe I misunderstood but you might be writing data to a hostPath volume instead of a writable container layer. In that case,  it is WAI.

**Comment by dimm0** [comment]
No, writing to containerd writeable layer. The issue might be when containerd mounted storage is smaller than kubelet mounted storage. But I need to check that

**Comment by SergeyKanzhelev** [comment]
@dimm0 would you be able to provide some step by step repro that would help us triage?

**Comment by dimm0** [comment]
Here's the disk layout of the node. Please note that /var/lib/kubelet is larger than /var/lib/containerd.

```
root@k8s-chase-ci-02:/home/nautilus# lsblk
NAME       MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sda          8:0    0 447.1G  0 disk
├─sda1       8:1    0     1M  0 part
└─sda2       8:2    0 447.1G  0 part
  └─md0      9:0    0   447G  0 raid1 /
sdb          8:16   0 447.1G  0 disk
├─sdb1       8:17   0     1M  0 part
└─sdb2       8:18   0 447.1G  0 part
  └─md0      9:0    0   447G  0 raid1 /
sdc          8:32   0 447.1G  0 disk
├─k8s-containers
│          253:0    0   300G  0 lvm   /var/lib/containerd
└─k8s-kubelet
           253:1    0 594.3G  0 lvm   /var/lib/kubelet/pods/18fc1ce0-2169-4458-8d0e-db5bd2d376f6/volume-subpaths/conf/sflow/1
                                      /var/lib/kubelet/pods/b609292e-384a-4299-979c-1775eaca251b/volume-subpaths/etc-cvmfs-default-d/automount-reconciler/4
                                      /var/lib/kubelet/pods/b609292e-384a-4299-979c-1775eaca251b/volume-subpaths/etc-cvmfs-default-conf/automount-reconciler/2
                                      /var/lib/kubelet/pods/b609292e-384a-4299-979c-1775eaca251b/volume-subpaths/etc-cvmfs-default-d/automount/7
                                      /var/lib/kubelet/pods/b609292e-384a-4299-979c-1775eaca251b/volume-subpaths/etc-cvmfs-default-conf/automount/5
                                      /var/lib/kubelet/plugins/cvmfs.csi.cern.ch
                                      /var/lib/kubelet/pods/b609292e-384a-4299-979c-1775eaca251b/volume-subpaths/etc-cvmfs-default-conf/nodeplugin/9
                                      /var/lib/kubelet/pods/8e383386-1569-4d5a-bd19-2208b6937482/volume-subpaths/pscheduler-agent/testpoint/0
                                      /var/lib/kubelet/pods/5eaf8a1c-8e2e-4733-a6f4-777daf001711/volume-subpaths/pscheduler-agent/testpoint-h/1
                                      /var/lib/kubelet
sdd          8:48   0 447.1G  0 disk
└─k8s-kubelet
           253:1    0 594.3G  0 lvm   /var/lib/kubelet/pods/18fc1ce0-2169-4458-8d0e-db5bd2d376f6/volume-subpaths/conf/sflow/1
                                      /var/lib/kubelet/pods/b609292e-384a-4299-979c-1775eaca251b/volume-subpaths/etc-cvmfs-default-d/automount-reconciler/4
                                      /var/lib/kubelet/pods/b609292e-384a-4299-979c-1775eaca251b/volume-subpaths/etc-cvmfs-default-conf/automount-reconciler/2
                                      /var/lib/kubelet/pods/b609292e-384a-4299-979c-1775eaca251b/volume-subpaths/etc-cvmfs-default-d/automount/7
                                      /var/lib/kubelet/pods/b609292e-384a-4299-979c-1775eaca251b/volume-subpaths/etc-cvmfs-default-conf/automount/5
                                      /var/lib/kubelet/plugins/cvmfs.csi.cern.ch
                                      /var/lib/kubelet/pods/b609292e-384a-4299-979c-1775eaca251b/volume-subpaths/etc-cvmfs-default-conf/nodeplugin/9
                                      /var/lib/kubelet/pods/8e383386-1569-4d5a-bd19-2208b6937482/volume-subpaths/pscheduler-agent/testpoint/0
                                      /var/lib/kubelet/pods/5eaf8a1c-8e2e-4733-a6f4-777daf001711/volume-subpaths/pscheduler-agent/testpoint-h/1
                                      /var/lib/kubelet
```

I create this pod (not using any emptyDir since I'm too lazy to read the docs):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-pod
  namespace: dimm
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - "k8s-chase-ci-02.calit2.optiputer.net"
  tolerations:
    - effect: NoSchedule
      key: nautilus.io/testing
      operator: Exists
  containers:
    - name: vol-container
      #image: praqma/network-multitool
      image: ubuntu
      resources:
        requests:
          cpu: 1
          memory: 1Gi
          ephemeral-storage: 400Gi
        limits:
          cpu: 5
          memory: 5Gi
          ephemeral-storage: 400Gi
      command: ["sleep", "infinity"]
```

<img width="713" alt="Screenshot 2024-10-09 at 3 19 51 PM" src="https://github.com/user-attachments/assets/55d5b92b-2271-46b9-a74a-b1644eeeb2ac">

All pods are good:

<img width="1253" alt="Screenshot 2024-10-09 at 3 20 21 PM" src="https://github.com/user-attachments/assets/c8388274-eb42-47db-933a-e8d15bc9076a">

Now I fill the root filesystem with my precious data:

`root@ephemeral-pod:/# for i in `seq 1 100`; do dd if=/dev/zero of=/tmp/file$i bs=1G count=10; done`

I see /var/lib/containerd usage growing:

<img width="616" alt="Screenshot 2024-10-09 at 3 27 58 PM" src="https://github.com/user-attachments/assets/12b7af79-242e-4f94-8625-05fcb92e5cfd">

Once I fill /var/lib/containerd (which is totally fine since I asked for 400G which I have in /var/lib/kubelet), other system pods get evicted even if they're small and use a couple kilobytes:

<img width="1255" alt="Screenshot 2024-10-09 at 3 30 06 PM" src="https://github.com/user-attachments/assets/6b6d8b75-238e-42ee-a1e5-f2ce4f6c8dbb">

And stay evicted until I delete the file (which is not the case for user jobs that keep trying to fill the disk)
