### ISSUE TITLE
Inconsistent DNS resolution for pod's IP when using headless and headful services

### ISSUE THREAD

**Issue by alexblue46** [kubernetes/kubernetes#127716]
### What happened?

I have a statefulset with multiple pods that make up a hashicorp raft. The raft needs stable ip addresses (see https://github.com/hashicorp/raft/issues/236) so I have defined a headful ClusterIP service for each pod. I have also defined a headless service for my statefulset.

The problem is that when I do a reverse DNS lookup of one of the pod's ip addresses (from a different pod) sometimes I get `<ip>.<headful service for that pod>.<namespace>.svc.cluster.local` and sometimes I get `<pod name>.<headless service name>.<namespace>.svc.cluster.local`. 

This is a problem because I have a mysql pod which needs to be able to consistently resolve the pod's ip to `<pod name>.<headless service name>.<namespace>.svc.cluster.local` in order for user authentication to succeed.

### What did you expect to happen?

I expect the pod's ip to consistently resolve to `<pod name>.<headless service name>.<namespace>.svc.cluster.local`.

### How can we reproduce it (as minimally and precisely as possible)?

Apply the following statefulset and services:
```
apiVersion: v1
kind: Service
metadata:
  name: headless-svc
  namespace: test
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: dummy
---
apiVersion: v1
kind: Service
metadata:
  name: headful-svc-0
  namespace: test
spec:
  ports:
    - name: dummy
      port: 1111
      targetPort: 1111
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: dummy
    statefulset.kubernetes.io/pod-name: dummy-0
---
apiVersion: v1
kind: Service
metadata:
  name: headful-svc-1
  namespace: test
spec:
  ports:
    - name: dummy
      port: 1111
      targetPort: 1111
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: dummy
    statefulset.kubernetes.io/pod-name: dummy-1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dummy
  namespace: test
  labels:
    app: dummy
spec:
  replicas: 2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: dummy
  serviceName: headless-svc
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: ["sleep", "infinity"]
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 1Mi
---
kind: CiliumNetworkPolicy
apiVersion: "cilium.io/v2"
metadata:
  name: network-policy
  namespace: test
spec:
  endpointSelector:
    matchLabels:
      app: dummy
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
```
Observe inconsistent DNS resolution for pod 0's ip on pod 1:
```
$ k exec -it dummy-1 -- /bin/sh
~ $ getent hosts 100.64.185.189
100.64.185.189    100-64-185-189.headful-svc-0.alex-test.svc.cluster.local  100-64-185-189.headful-svc-0.alex-test.svc.cluster.local
~ $ getent hosts 100.64.185.189
100.64.185.189    dummy-0.headless-svc.alex-test.svc.cluster.local  dummy-0.headless-svc.alex-test.svc.cluster.local
```

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"29+", GitVersion:"v1.29.7-eks-a18cd3a", GitCommit:"713ff29cb54edbe951b4ed70324fb3e7f8c8191b", GitTreeState:"clean", BuildDate:"2024-08-21T06:36:43Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.27) and server (1.29) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.20.3
PRETTY_NAME="Alpine Linux v3.20"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
$ uname -a
Linux dummy-1 5.15.165-110.161.amzn2.x86_64 #1 SMP Fri Aug 23 18:41:15 UTC 2024 x86_64 Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
didn't get much into detail but I will check first this is not the same as https://github.com/kubernetes/kubernetes/issues/124207

@adrianmoisey you looked into the other bug so you may have this fresher than me

**Comment by adrianmoisey** [comment]
I don't think it's the same issue, since this one uses different types of services.

I'm happy to look into this one a little more though, since it's close to the other issue 

/assign

**Comment by aojea** [comment]
@alexblue46 who is the DNS provider? CoreDNS? is there any other thing on that cluster or EKS that fiddles with dns records?

**Comment by alexblue46** [comment]
@aojea CoreDNS is the provider. I don't believe anything else on the cluster messes with DNS records but I will double check with my team on Monday.

**Comment by adrianmoisey** [comment]
> didn't get much into detail but I will check first this is not the same as #124207

So the problem seems to be multiple PTR records are returned, one for each Service.
```
# dig +short -x 10.244.0.6
10-244-0-6.headful-svc-0.test.svc.cluster.local.
dummy-0.headless-svc.test.svc.cluster.local.
```

According to the [spec](https://github.com/kubernetes/dns/blob/master/docs/specification.md) there should only be PTR records returned for the headless Service.

There is a slack conversation linked from https://github.com/coredns/coredns/pull/6898
That PR happened to be merged today, which I believe will fix the issue.

**Comment by adrianmoisey** [comment]
Closing this out as the issue will be fixed in the next CoreDNS release, which contains https://github.com/coredns/coredns/pull/6898

/close

**Comment by alexblue46** [comment]
Confirmed that https://github.com/coredns/coredns/pull/6898 fixes this issue.

**Comment by Michael-Sinz** [comment]
Note that coredns now breaks our load balancer since now there is no IP address for the individual pods - the `<ip>.<service name>.<namespace>.svc.cluster.local.` no longer exists and that was core to our use case.

What is the replacement mechanism?

**Comment by adrianmoisey** [comment]
> Note that coredns now breaks our load balancer since now there is no IP address for the individual pods - the `<ip>.<service name>.<namespace>.svc.cluster.local.` no longer exists and that was core to our use case.

Could you elaborate on this? Are you referring to an A record or a PTR record? Can you demonstrate a case that used to work and now doesn't?

Using this as a test case:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dummy
  labels:
    app: dummy
spec:
  replicas: 2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: dummy
  serviceName: headless-svc
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: ["sleep", "infinity"]
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: dummy
```

If I query the service, I get the Pod IPs back:
```
# dig +short headless-svc.default.svc.cluster.local
10.244.0.7
10.244.0.6
```

If I query the PTR record for a Pod, I get the Pod name back:
```
# dig +short -x 10.244.0.6
dummy-1.headless-svc.default.svc.cluster.local.
```

This is all using a kind cluster, with CoreDNS v1.11.3.

If I upgrade to v1.11.4, I get the same:
```
# dig +short headless-svc.default.svc.cluster.local
10.244.0.6
10.244.0.7
```

and...

```
# dig +short -x 10.244.0.6
dummy-1.headless-svc.default.svc.cluster.local.
```
