### ISSUE TITLE
Deployment with multiple port mappings with same port number but different protocol fails to update properly

### ISSUE THREAD

**Issue by ccjette-logmein** [kubernetes/kubernetes#127813]
### What happened?

When updating a Deployment and adding two port mappings with the same port number, but with a different protocol, only one of the mappings is created. `kubectl diff` does not detect a difference between the manifest and what's deployed. However, when applying the manifest with both port mappings from scratch, they are correctly defined. 

### Example 

`deployment_without_ports.yaml`
<details>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ed-example-chart
  namespace: "playground"
  labels:
    helm.sh/chart: example-chart-0.5.1
    app.kubernetes.io/name: example-chart
    app.kubernetes.io/instance: ed
    app.kubernetes.io/version: "0.2.3"
    app.kubernetes.io/managed-by: Helm
spec:
  #<...>
    spec:
      containers:
        - name: http-echo
          image: #<...>
          imagePullPolicy: IfNotPresent
          args:
            - -text="hello I'm httpEcho"
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
    #<...>
``` 
</details>

`deployment_with_ports.yaml`
<details>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ed-example-chart
  namespace: "playground"
  labels:
    helm.sh/chart: example-chart-0.5.1
    app.kubernetes.io/name: example-chart
    app.kubernetes.io/instance: ed
    app.kubernetes.io/version: "0.2.3"
    app.kubernetes.io/managed-by: Helm
spec:
  #<...>
    spec:
      containers:
        - name: http-echo
          image: #<...>
          imagePullPolicy: IfNotPresent
          args:
            - -text="hello I'm httpEcho"
          ports:
       	- containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 80
              name: http
              protocol: TCP
    #<...>
``` 
</details>

`kubectl apply -f deployment_with_ports.yaml` will give the expected result if the ressource doesn't already exist. 
However 
`kubectl apply -f deployment_without_ports.yaml` followed by `kubectl apply -f deployment_with_ports.yaml` will give the following result. 

<details>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ed-example-chart
  namespace: "playground"
  labels:
    helm.sh/chart: example-chart-0.5.1
    app.kubernetes.io/name: example-chart
    app.kubernetes.io/instance: ed
    app.kubernetes.io/version: "0.2.3"
    app.kubernetes.io/managed-by: Helm
spec:
  #<...>
    spec:
      containers:
        - name: http-echo
          image: #<...>
          imagePullPolicy: IfNotPresent
          args:
            - -text="hello I'm httpEcho"
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
			# Missing port mapping here
            - containerPort: 80
              name: http
              protocol: TCP
    #<...>
``` 
</details>

### What did you expect to happen?

I would expect the update to the manifest to be configured with both container port mappings, like it is when creating the initial deployment. 

### How can we reproduce it (as minimally and precisely as possible)?

- First, create a Deployment manifest with the following container port mappings 
```yaml
ports:
  - containerPort: 80
    name: http
    protocol: TCP
```
- Then create another one, identical with the following container port mappings 
```yaml
ports:
  - containerPort: 53
    name: dns-tcp
    protocol: TCP
  - containerPort: 53
    name: dns-udp
    protocol: UDP
  - containerPort: 80
    name: http
    protocol: TCP
```
- Apply first manifest, then second
- `kubectl get deploy <deploy-name> -o yaml`
- The result will be missing one of the `53` port mappings
- Delete the `Deployment`
- Apply second manifest
- It will contain all expected port mappings

### Kubernetes version

Tested with two Kubernetes versions
<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.12", GitCommit:"696a9fdd2a58340e61e0d815c5769d266fca0802", GitTreeState:"clean", BuildDate:"2022-04-13T19:01:10Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>
<details>

```console
$ kubectl version
Client Version: v1.29.9
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1
```

</details>

### Cloud provider

<details>
For 1.21, cluster is onprem
For 1.29, cluster is on Oracle Kubernetes Engine
</details>

### OS version

<details>

```console
$ sw_vers
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93
$ uname -a
Darwin ccoupaljette-MBP 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
