### ISSUE TITLE
"pods is forbidden: User \"system:anonymous\" cannot list resource \"pods\" in API group \"\" in the namespace \"kube-system\""

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#127884]
### What happened?

```
root@k8s-master01:~/.kube# curl -k https://192.168.229.180:6443/api/v1/namespaces/kube-system/pods
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "pods is forbidden: User \"system:anonymous\" cannot list resource \"pods\" in API group \"\" in the namespace \"kube-system\"",
  "reason": "Forbidden",
  "details": {
    "kind": "pods"
  },
  "code": 403
}root@k8s-master01:~/.kube# 
```

authentication-anonymous-config.yaml
```
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
anonymous:
  enabled: true
  conditions:
  - path: /api/v1/namespaces/kube-system/pods
```

```
    - --authentication-config=/etc/kubernetes/authentication-anonymous-config.yaml
    - --feature-gates=AnonymousAuthConfigurableEndpoints=true

    
    - mountPath: /etc/kubernetes/authentication-anonymous-config.yaml
      name: authentication-config
      readOnly: true
  
  - hostPath:
      path: /etc/kubernetes/authentication-anonymous-config.yaml
      type: File
    name: authentication-config
```

### What did you expect to happen?

can visit https://192.168.229.180:6443/api/v1/namespaces/kube-system/pods

### How can we reproduce it (as minimally and precisely as possible)?

config the configuration above

### Kubernetes version

<details>
1.31.0
</details>

### Cloud provider

<details>
vmware workstation
</details>

### OS version

<details>

ubuntu2404

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
That policy only enables the anonymous authenticator for that endpoint. You still need to configure authorization to actually allow that API request (likely using RBAC or something similar)

**Comment by 13567436138** [comment]
I donot understand,why need this

**Comment by liggitt** [comment]
this bit configures authentication, which tells the system which paths the anonymous user can even be identified for:

```
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
anonymous:
  enabled: true
  conditions:
  - path: /api/v1/namespaces/kube-system/pods
```

That does *not* configure authorization, which is needed to tell the system what operations the anonymous user can do.

In this case, you need something to tell the system that listing pods in all namespaces is allowed for the anonymous user. (note: that would be a surprisingly powerful permission to actually grant an anonymous user, but I'm assuming you're just giving this as an example).

See the following links for more documentation about these two phases:
* https://kubernetes.io/docs/reference/access-authn-authz/authentication/#anonymous-requests
* https://kubernetes.io/docs/reference/access-authn-authz/authorization/
