### ISSUE TITLE
`system:monitoring` lacks access to kubelet /metrics endpoint

### ISSUE THREAD

**Issue by richabanker** [kubernetes/kubernetes#127990]
### What happened?

Discussion began in https://github.com/kubernetes/enhancements/pull/4830#discussion_r1794149005 where it was identified that [`system:monitoring` cluster role](https://github.com/kubernetes/kubernetes/blob/release-1.31/staging/src/k8s.io/apiserver/pkg/authentication/user/user.go#L73) does not allow access to kubelet's /metrics and /metrics endpoint

### What did you expect to happen?

Would have expected the test described [here](https://github.com/kubernetes/enhancements/pull/4830#discussion_r1794426008) to pass

### How can we reproduce it (as minimally and precisely as possible)?

Summarized [here](https://github.com/kubernetes/enhancements/pull/4830#discussion_r1794426008)

### Kubernetes version

<details>

```console
$ kubectl version
# v1.31.0
```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by richabanker** [comment]
As a resolution, and especially since [Fine grained Kubelet API Auth](https://github.com/vinayakankugoyal/enhancements/blob/aa3d634d8243fa925fc67ff2e2be99a6a6957599/keps/sig-node/2862-fine-grained-kubelet-authz/README.md) is underway, could we make changes to the `system:monitoring` cluster role to be expanded to the following

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:monitoring 
rules:
# existing rules
- apiGroups: [""]
  resources: ["nodes/metrics", "/nodes/metrics/slis"]
  verbs: ["get"] 
```

This is also whats proposed as a way to add auth for kubelet's /statusz endpoint in https://github.com/kubernetes/enhancements/pull/4830

cc @tallclair for his thoughts.

**Comment by pacoxu** [comment]
@vinayakankugoyal I tried the steps in https://github.com/kubernetes/enhancements/pull/4830#discussion_r1794426008.
```
[root@paco ~]# kubectl create serviceaccount hello --namespace default
serviceaccount/hello created
[root@paco ~]# kubectl create clusterrolebinding --clusterrole=system:monitoring --serviceaccount default:hello helloissystemmonitor
clusterrolebinding.rbac.authorization.k8s.io/helloissystemmonitor created
[root@paco ~]# kubectl get --raw /api/v1/nodes/$(kubectl get nodes --no-headers | awk '{print $1}')/proxy/metrics --token $(kubectl create token hello)
# HELP aggregator_discovery_aggregation_count_total [ALPHA] Counter of number of times discovery was aggregated
```
Did I miss something?

https://github.com/kubernetes/kubernetes/blob/05b076b7413eec87fa647d179344e4b592a46b3f/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L220-L232

cc @SergeyKanzhelev @tallclair

**Comment by vinayakankugoyal** [comment]
Can you post the results of `kubectl get clusterrole system:monitoring -o yaml`

**Comment by vinayakankugoyal** [comment]
Also is your kubelet configured with `AllowAll`?

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/05b076b7413eec87fa647d179344e4b592a46b3f/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L220-L232

```
[root@paco ~]# kubectl get clusterrole system:monitoring -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2024-09-25T09:53:08Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:monitoring
  resourceVersion: "73"
  uid: ce4cb911-1c6c-4382-bd6a-7bb709a972a9
rules:
- nonResourceURLs:
  - /healthz
  - /healthz/*
  - /livez
  - /livez/*
  - /metrics
  - /metrics/slis
  - /readyz
  - /readyz/*
  verbs:
  - get
  ```
  
config.yaml of kubelet
```
[root@paco ~]# cat /var/lib/kubelet/config.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s

```
