### ISSUE TITLE
Scheduling Problems Caused by Definition of Persistent Volumes and Ephemeral Volumes

### ISSUE THREAD

**Issue by kangzhiqin** [kubernetes/kubernetes#128041]
### What would you like to be added?

k8s version is 1.28.1.
In the same sts， a 10 GB persistent volume and a 10 MB ephemeral volume are defined.

ephemeral volume：
```
  - ephemeral:
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Mi
          storageClassName: localcsi
          volumeMode: Filesystem
    name: share
```

persistent volume ：
```
  volumes:
  - name: search-pod-pvc
    persistentVolumeClaim:
      claimName: search-pod-pvc-pod-0
```

In normal cases, the two volumes can be created and scheduled.
```
ns         pod-0-share                                                        Bound    pvc-2cb4b639-9d8a-4f44-af7a-16692ff4e7dd   10Mi       RWO            localcsi       6h42m
ns         search-pod-pvc-pod-0                                      Bound    pvc-32195605-0fa6-4ee2-b1fb-a90a8a7a6b1e   10Gi       RWO            localcsi       6h42m

```

However, in some small resource scenarios, if the ephemeral volume is scheduled before the persistent volume, the persistent volume may fail to be scheduled due to insufficient resource.
```
ns         pod-0-share                                                        Bound     pvc-39836b73-3f85-4660-a890-2eaa75cee4c0   10Mi       RWO            localcsi       3d1h
ns         search-pod-pvc-pod-0                                      Pending                                                                        localcsi       3d1h

```

### Why is this needed?

Is there any optimization solution for this scheduling problem in the community?
