### ISSUE TITLE
Unable to simulate the unschedulable state through plugin

### ISSUE THREAD

**Issue by BhautikChudasama** [kubernetes/kubernetes#128002]
### What happened?

I want to simulate the the Unschedulable state (intentationally) using plugin but unable to do

```golang
func (pl *CustomePlugin) Bind(ctx context.Context, state *framework.CycleState, pod *v1.Pod, nodeName string) *framework.Status {
	log.Printf("Simulating failure in binding for pod %s to node %s", pod.Name, nodeName)
	return framework.NewStatus(framework.Unschedulable, "Pod will remain in Pending state, no node bound")
}
```

Here is my Config
```
    plugins:
      bind:
        enabled:
          - name: CustomPlugin
        disabled:
          - name: "*"
      score:
        # Additional enabled plugins
        enabled:
          - name: CustomPlugin
        disabled:
          - name: "*"
```

When i am describing pod log, It schedule on another node here is the log

<img width="1062" alt="Screenshot 2024-10-11 at 7 32 38 PM" src="https://github.com/user-attachments/assets/f1e9f579-20d7-4fa0-a599-e43e64a34459">

What I am doing wrong?

### What did you expect to happen?

It should not schedule to any node.

### How can we reproduce it (as minimally and precisely as possible)?

Here is my `main.go`

```golang
package main

import (
	"context"
	"fmt"
	"log"

	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/kubernetes/cmd/kube-scheduler/app"
	"k8s.io/kubernetes/pkg/scheduler/framework"
)

const (
	PluginName = "CustomScheduler"
)

type CustomScheduler struct {
	handle framework.Handle
}

var _ framework.ScorePlugin = &CustomScheduler{}

func (pl *CustomScheduler) Name() string {
	return PluginName
}

func (pl *CustomScheduler) Score(ctx context.Context, state *framework.CycleState, pod *v1.Pod, nodeName string) (int64, *framework.Status) {
	if nodeName == "w1" || nodeName == "w2" {
		return 100, nil
	}

	return 0, nil
}

func (pl *CustomScheduler) ScoreExtensions() framework.ScoreExtensions {
	return pl
}

func (pl *CustomScheduler) Bind(ctx context.Context, state *framework.CycleState, pod *v1.Pod, nodeName string) *framework.Status {
	// Log the attempt to bind the pod and simulate failure
	log.Printf("Simulating failure in binding for pod %s to node %s", pod.Name, nodeName)

	// Return an error to keep the pod in Pending state
	return framework.NewStatus(framework.Unschedulable, "Pod will remain in Pending state, no node bound")
}

func (pl *CustomScheduler) NormalizeScore(ctx context.Context, state *framework.CycleState, pod *v1.Pod, scores framework.NodeScoreList) *framework.Status {
	fmt.Println(scores)
	return nil
}

func New(_ context.Context, _ runtime.Object, h framework.Handle) (framework.Plugin, error) {
	return &CustomScheduler{handle: h}, nil
}

func main() {
	cmd := app.NewSchedulerCommand(
		app.WithPlugin(PluginName, New),
	)

	err := cmd.Execute()
	if err != nil {
		log.Fatal(err)
	}
}
```

config.yaml
```
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/Users/bhautik/.kube/config"
profiles:
  - schedulerName: default-scheduler
    percentageOfNodesToScore: 100
    plugins:
      bind:
        enabled:
          - name: CustomScheduler
            weight: 5
        disabled:
          - name: "*"
      score:
        # Additional enabled plugins
        enabled:
          - name: CustomScheduler
        disabled:
          - name: "*"
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.30.2+k3s1
```

</details>

### Cloud provider

<details>
I am using k3s.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
