### ISSUE TITLE
[Bug] Missing constraint and validation for label selector's values

### ISSUE THREAD

**Issue by scheduler-tester** [kubernetes/kubernetes#128156]
### What happened?

Hello,
There are some [constraints](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) that label selector's `values` need to conform:
>* must be 63 characters or less (can be empty),
>* unless empty, must begin and end with an alphanumeric character ([a-z0-9A-Z]),
>* could contain dashes (-), underscores (_), dots (.), and alphanumerics between.

Every label selctor's `values` will be checked [here](https://github.com/kubernetes/kubernetes/blob/e5ba5cd2b0d3bddd4a0393b98fde14960f31a33c/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L166C1-L175C2), and when values is not conforming these constraints, an error will be returned.

`nodeAfffinty.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms.matchExpressions.values` also needs to conform these constraints (because `matchExpressions` will be parsed as a label selector), but cccording to the [concept documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#operators) and the [API documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#nodeselectorrequirement-v1-core), 
Kubernetes only requires `V1NodeSelectorRequirement.values` to be strings. 
>`values` (string array): An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.

So when creating a pod with invalid `V1NodeSelectorRequirement.values`, no warning or error message appears and the pod is created successfully.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-test-pod
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: int-cmkzofgjsu
            operator: NotIn
            values:
            - '-1' # <- invalid value
  containers:
  - image: nginx
    name: test-container
# pod/node-affinity-test-pod created <- no warning or error here
```
By contrast, when you set an invalid value in matchFields, it will be rejected.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-test-pod
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: NotIn
            values:
            - '-1'
  containers:
  - image: nginx
    name: test-container
# The Pod "node-affinity-test-pod" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchFields[0].values[0]: Invalid value: "-1": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
---
And after creating the first pod successfully, it couldn’t be scheduled even though one node satisfied its `nodeAffinity`. By adding some log codes, we found that when the scheduler tries to parse a `nodeSelectorTerm`, it receives a non-empty `parseErr`(because the value is not conforming label value constraints as stated above), causing it to consider the entire `nodeSelectorTerm` unmatched. [code](https://github.com/kubernetes/kubernetes/blob/d88b4e3b6e34a85f58778b7ef96e64edffff6823/staging/src/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go#L191C2-L193C3) here.

This behavior may cause the scheduler to make unexpected decisions without the user's awareness. More critically, an invalid value will prevent the entire nodeSelectorTerm from matching.

```yaml
nodeSelectorTerms:
 - matchExpressions:
    - matchExpressions1{key, operator, values} -> has an invalid value, but user is not aware of it
    - matchExpressions2{key, operator, values}
    - ...
   matchFields:
    - matchFields1{key, operator, values}
    - matchFields2{key, operator, values}
    - ...
# matchExpressions1 cannot be parsed, so the whole nodeSelectorTerm is considered as not matched in nodeAffinity
```

### What did you expect to happen?

* Implicit constraints on the [label selector](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/labels/selector.go)'s `values` field should be specified in the API documentation and also validated before creating the pod. (We think not only `nodeAfffinty.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms` will be parsed as label selector, other fields in V1Pod also need to be checked for the same reason.)
* Those implicit constraints should also be added to the concept documentation. (will create an issue in kuberentes/website later)

### How can we reproduce it (as minimally and precisely as possible)?

Use the yaml file above.

### Anything else we need to know?

/sig bugs scheduling

### Kubernetes version

Tested on 1.30.2

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
