### ISSUE TITLE
oidc config and AuthenticationConfiguration can not config both，but AuthenticationConfiguration does not have signing-algs config，lead to problem？

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#128207]
### What happened?

    - --oidc-signing-algs=RS512

```
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
jwt:
- issuer:
    # url 在所有认证组件中必须是唯一的。
    # url 不得与 --service-account-issuer 中配置的颁发者冲突。
    url: https://cas.example.org/cas/oidc
    # discoveryURL（如果指定）将覆盖用于获取发现信息的 URL，而不是使用 “{url}/.well-known/openid-configuration”。
    # 系统会使用所给的配置值，因此如果需要，“/.well-known/openid-configuration” 必须包含在 discoveryURL 中。
    #
    # 取回的发现信息中的 “issuer” 字段必须与 AuthenticationConfiguration 中的
    # “issuer.url” 字段匹配，并被用于验证所呈现的 JWT 中的 “iss” 声明。
    # 这适用于众所周知的端点和 jwks 端点托管在与颁发者不同的位置（例如集群本地）的场景。
    # discoveryURL 必须与 url 不同（如果指定），并且在所有认证组件中必须是唯一的。
    discoveryURL: https://cas.example.org/cas/oidc/.well-known/openid-configuration
    # PEM 编码的 CA 证书用于在获取发现信息时验证连接。
    # 如果未设置，将使用系统验证程序。
    # 与 --oidc-ca-file 标志引用的文件内容的值相同。
    certificateAuthority: |
      -----BEGIN CERTIFICATE-----
      MIIDxTCCAq2gAwIBAgIEHSYe8TANBgkqhkiG9w0BAQsFADBHMQswCQYDVQQGEwJV
      UzEMMAoGA1UECxMDT3JnMRAwDgYDVQQLEwdFeGFtcGxlMRgwFgYDVQQDEw9jYXMu
      ZXhhbXBsZS5vcmcwHhcNMjQxMDE0MDQ1MTA5WhcNMjUwMTEyMDQ1MTA5WjBHMQsw
      CQYDVQQGEwJVUzEMMAoGA1UECxMDT3JnMRAwDgYDVQQLEwdFeGFtcGxlMRgwFgYD
      VQQDEw9jYXMuZXhhbXBsZS5vcmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCu5cxJB7oy812FiREeMAuwRY6zOL+Z0fzzL2+yNB62drf8++xSDWRRIzdW
      d6ao4/8OoZoGf6MwmJimeqzJfgIwAFPWKIXQiWTr1pIt3RmGbMWyMieA6pTu03oa
      dYgDxliPaKyqK3lauQ3hIxOBX5igS+ZFwP00t/KYZLaUYq90E0CfkaaMxDRHpyFa
      L/NTlx7fDe4iJv5e43XqU6mmHxHtdSYkHCXRKb2eqZzipOL4/T9KqyICEOK26mnB
      LDMuGUOhuqTw2/eEcAzpFotu12sYjywe9sbTJZEjVyXpCyIf06A2mh1RzqYZrcdX
      KKu6P2t+Fl5wVwHmr07nUffVjfJdAgMBAAGjgbgwgbUwHQYDVR0OBBYEFAi6kyO7
      eASBkHz1X4mlqvU3ERm7MIGTBgNVHREEgYswgYiCD2Nhcy5leGFtcGxlLm9yZ4IU
      Y2FzYWRtaW4uZXhhbXBsZS5vcmeCFWNhcy1zZXJ2ZXItYm9vdC1hZG1pboIjY2Fz
      LXNlcnZlci0wLmNhcy1zZXJ2ZXIuZGVmYXVsdC5zdmOCI2Nhcy1zZXJ2ZXItMS5j
      YXMtc2VydmVyLmRlZmF1bHQuc3ZjMA0GCSqGSIb3DQEBCwUAA4IBAQA9SR55kjOK
      abIbEFthdg2djwydlBysVyu+C1YQ5ratdryVgnbG9zjsLphGzYXSwdsOjw8VdZiu
      Fk4bEm/6+sFtksMfLza6OJj/Mq0JPTiDQAnvokBgJBllJJmerAbeKwMmpiuYFZPS
      j1A7456JrHnl9T/QREuqYAWt7oyXHKrorLjuPjoe1bqgE/lgIIvDtTuPMrZ3rO/T
      WC4HbBvpm61w1osZzqjitV+qzZkZ50z2oLdkISPaXxWVS5feNga8imijQ4zBMC25
      Ni0pI/FSU7Lx/sP2bSjuC/8H/FBUpeSlzh37/ZRd6H6eR5zw75LykDF85+5L2oNd
      LrfEiw8rsu+s
      -----END CERTIFICATE-----
    # audiences 是 JWT 必须发布给的一组可接受的受众。
    # 至少其中一项必须与所提供的 JWT 中的 “aud” 声明相匹配。
    audiences:
    - kubernetes # 与 --oidc-client-id 一致。
    # 当指定多个受众时，需要将此字段设置为 “MatchAny”。
    #audienceMatchPolicy: MatchAny
  # 用于验证令牌声明以对用户进行身份认证的规则。
  #claimValidationRules:
    # 与 --oidc-required-claim key=value 一致
  #- expression: 'claims.exp - claims.nbf <= 86400'
  #  message: total token lifetime must not exceed 24 hours
  claimMappings:
    # username 表示用户名属性的选项。
    # 这是唯一必需的属性。
    username:
      # 与 --oidc-username-claim 相同，与 username.expression 互斥。
      claim: "preferred_username"
      # 与 --oidc-username-prefix 相同，与 username.expression 互斥。
      # 如果设置了username.claim，则需要username.prefix。
      # 如果不需要前缀，可显式将其设置为 ""。
      prefix: "oidc-"
      # 与 username.claim 和 username.prefix 互斥。
      # expression 是计算结果为字符串的 CEL 表达式。
      #
      # 1.  如果 username.expression 使用 “claims.email”，则必须在 username.expression
      #     或 extra[*].valueExpression 或 ClaimValidationRules[*].expression 中使用 “claims.email_verified”。
      #     与 username.claim 设置为 “email” 时自动应用的验证相匹配的示例声明验证规则表达式是
      #     “claims.?email_verified.orValue(true)”。
      # 2.  如果根据 username.expression 断言的用户名是空字符串，则身份认证请求将失败。
      #expression: '"oidc:"+claims.preferred_username'
    # groups 代表 groups 属性的一个选项。
    groups:
      # 与 --oidc-groups-claim 相同，与 groups.express 互斥。
      #claim: "user_groups"
      # 与 --oidc-groups-prefix 相同。与 groups.express 互斥。
      # 如果设置了 groups.claim，则需要 groups.prefix。
      # 如果不需要前缀，则显式将其设置为 ""。
      #prefix: "oidc-"  #Invalid value: \"oidc-\": prefix can't be set when expression is set"
      # 与 groups.claim 和 groups.prefix 互斥。
      # expression 是一个计算结果为字符串或字符串列表的 CEL 表达式。
      expression: 'claims.group_name.split(",").map(g, "oidc-" + g)'
    # uid 表示 uid 属性的一个选项。
    uid:
      # 与 uid.expression 互斥。
      claim: 'preferred_username'
      # 与 uid.claim 互斥
      # expression 是计算结果为字符串的 CEL 表达式。
      #expression: 'claims.preferred_username'
  # 应用于最终用户对象的验证规则。
  userValidationRules:
    # expression 是一个计算结果为布尔值的 CEL 表达式。
    # 所有表达式的计算结果必须为 true，用户才有效。
  - expression: "!user.username.startsWith('system:')"
    # Message 自定义验证失败时在 API 服务器日志中看到的错误消息。
    message: 'username cannot used reserved system: prefix'
  - expression: "user.groups.all(group, !group.startsWith('system:'))"
    message: 'groups cannot used reserved system: prefix'
```

```
E1020 08:34:22.274226       1 authentication.go:73] "Unable to authenticate the request" err="[invalid bearer token, oidc: verify token: failed to verify signature: failed to verify id token signature]"
```

### What did you expect to happen?

command execute right

### How can we reproduce it (as minimally and precisely as possible)?

config AuthenticationConfiguration  with oidc provider with signing-algs is RS512

### Kubernetes version

<details>

1.31.0

</details>

### Cloud provider

<details>
wmware workstation
</details>

### OS version

<details>

ubuntu 2404

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
