### ISSUE TITLE
AppArmor type validation fails in `Deployments` when mixing old annotations with `securityContext.appArmorProfile`.

### ISSUE THREAD

**Issue by tsaarni** [kubernetes/kubernetes#128306]
### What happened?

Validation may fail when`Deployment` mixes deprecated `container.apparmor.security.beta.kubernetes.io/` annotations with the new `securityContext.appArmorProfile`.

```
The Deployment "xyz" is invalid: spec.template.spec.containers[0].securityContext.appArmorProfile.type: Forbidden: apparmor type in annotation and field must match
```

### What did you expect to happen?

The validation was expected to pass.

### How can we reproduce it (as minimally and precisely as possible)?

The following minimal example defines a pod-level default AppArmor profile within the pod-level `securityContext`, while using a deprecated annotation to override the profile at the container-level:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-fails-validation
spec:
  selector:
    matchLabels:
      app: deployment-fails-validation
  template:
    metadata:
      labels:
        app: deployment-fails-validation
      annotations:
        # Container-level override using deprecated annotation.
        container.apparmor.security.beta.kubernetes.io/fails-validation: 'runtime/default'
    spec:
      securityContext:
        appArmorProfile:
          # Pod-level default profile.
          type: Unconfined
      containers:
      - name: fails-validation
        image: alpine:latest
        command: ["/bin/sh"]
        args:
        - "-c"
        - "sleep 99999999"
```

When this configuration is applied, the following error occurs:

```
$ kubectl apply -f deployment-fails-validation.yaml
The Deployment "deployment-fails-validation" is invalid: spec.template.spec.containers[0].securityContext.appArmorProfile.type: Forbidden: apparmor type in annotation and field must match
```

The error message suggests that `spec.containers[0].securityContext.appArmorProfile` at the container-level doesn't match the annotation, even though container-level profile is not defined.

### Anything else we need to know?

I believe the reason for the failure is as follows:

In the [validation code](https://github.com/kubernetes/kubernetes/blob/352056f09df3101d53af74aee30b79e2aba742da/pkg/apis/core/validation/validation.go#L4820-L4858), the pod-level profile `spec.securityContext.appArmorProfile` is retrieved [here](https://github.com/kubernetes/kubernetes/blob/352056f09df3101d53af74aee30b79e2aba742da/pkg/apis/core/validation/validation.go#L4822). During the iteration over each container, this profile is used as the [default value](https://github.com/kubernetes/kubernetes/blob/352056f09df3101d53af74aee30b79e2aba742da/pkg/apis/core/validation/validation.go#L4825). If a container doesn't explicitly set its own AppArmor profile in `spec.containers[i].securityContext.appArmorProfile`, the pod-level profile remains the default. In the provided manifest, this results in the need for all container-level annotations to match the pod-level security context for validation to pass, making it impossible to override the pod-level profile using deprecated annotations.

I believe it would be sufficient to ensure that container-level annotations align with the container-level security context, while ignoring the pod-level security context.

This issue seems to only affect `Deployments`, as e.g. `StatefulSets` do not call this validation function.

The validation logic was introduced in #123435.

I understand this is an uncommon scenario, mixing old and new methods within a single pod, but I wanted to document the issue and the likely cause.

### Kubernetes version

<details>

```console
 kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.0
```
</details>

### Cloud provider

<details>

</details>
