### ISSUE TITLE
Configuring Nodes to Authenticate to a Private Repository

### ISSUE THREAD

**Issue by preillyme** [kubernetes/kubernetes#12835]
```
# docker --version
Docker version 1.6.2-cs5, build 6f88399
```

```
# docker pull dtr.k8s.co/kismatic/oracle-java7:latest
latest: Pulling from dtr.k8s.co/kismatic/oracle-java7

6d370c930acc: Downloading [==========>                                        ] 14.27 MB/68.32 MB
9a63f1e91c4c: Download complete
74364530838d: Download complete
dce38fb57986: Download complete
3c5086cea6ef: Download complete
600f1ea88e8c: Download complete
280e22001ea6: Download complete
9ca2f7e6931b: Downloading [=================================>                 ] 13.79 MB/20.69 MB
f3dae0c260f1: Download complete
1ce61cd2dcad: Downloading [==>                                                ] 15.87 MB/317.4 MB
```

But with:

```
# cat /tmp/private-image-test-1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: private-image-test-1
spec:
  containers:
    - name: uses-private-image
      image: dtr.k8s.co/kismatic/oracle-java7
      command: [ "echo", "SUCCESS" ]
  imagePullPolicy: Always

We see the following

# kubectl describe pods/private-image-test-1 | grep "Failed"
  Mon, 17 Aug 2015 18:29:42 +0000       Mon, 17 Aug 2015 18:30:42 +0000 7       {kubelet 172.31.26.97}  spec.containers{uses-private-image}   failed          Failed to pull image "dtr.k8s.co/kismatic/oracle-java7": image pull failed for dtr.k8s.co/kismatic/oracle-java7, this may be because there are no credentials on this request.  details: (Error: image kismatic/oracle-java7:latest not found)
 ```

Also worth mentioning that:

  ```
# cat /root/.dockercfg
{
        "dtr.k8s.co": {
                "auth": "cGF0***************IB5+",
                "email": "patrick@kismatic.com"
        }
```
exists and works as root directly.

and

```
# ps aux | grep 'kubelet'
root      1077  1.0  0.5 350656 43432 ?        Ssl  Aug13  55:10 /opt/bin/kubelet --address=172.31.17.60 --port=10250 --hostname_override=172.31.17.60 --api_servers=172.31.17.60:8080 --logtostderr=false --log_dir=/var/log/kubernetes
```

**Comment by bgrant0607** [comment]
@preillyme Have you tried imagePullSecrets?
http://kubernetes.io/v1.0/docs/user-guide/production-pods.html#authenticating-with-a-private-image-registry

**Comment by lachie83** [comment]
@bgrant0607 - Yes. I can confirm using imagePullSecrets yields the same error message.

**Comment by preillyme** [comment]
@bgrant0607 — putting the .dockercfg file into a secret resource did the trick it's now working.
```
Tue, 18 Aug 2015 07:39:24 +0000       Tue, 18 Aug 2015 07:39:24 +0000 1       {kubelet 172.31.26.97}  spec.containers{uses-private-image}     started         Started with docker id afd01879bfb4
```
Thanks! This documentation http://kubernetes.io/v1.0/docs/user-guide/images.html#using-a-private-registry should probably be updated as well.

**Comment by preillyme** [comment]
@lachie83 it's working for me with the following:
```
# cat /tmp/image-pull-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
data:
  .dockercfg: ewo**********=
type: kubernetes.io/dockercfg
```

and 

```
kubectl create -f /tmp/image-pull-secret.yaml
```

```
# cat /tmp/private-image-test-1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: private-image-test-1
spec:
  containers:
    - name: uses-private-image
      image: dtr.k8s.co/kismatic/oracle-java7
      command: [ "echo", "SUCCESS" ]
  imagePullPolicy: Always
  imagePullSecrets:
    - name: myregistrykey
```
