### ISSUE TITLE
When containers use memory backed tmpfs and hit a OOM limit they will keep OOM on restarts.

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#128339]
### What happened?

While aiming to promote SizeMemoryBackedVolumes to stable, tim brought up a point about what would happen if a pod that hit a OOM due to tmpfs memory limits would keep OOM as the pages are still kept around.

He is correct. If a pod hits a OOM limit with tmpfs it will keep OOM and never purge that memory

### What did you expect to happen?

I would expect the tmpfs to be empty on a restart of the container.

### How can we reproduce it (as minimally and precisely as possible)?

I used kind 1.30.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: test-pd
spec:
  restartPolicy: OnFailure
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: busybox
    command:
      - /bin/sh
      - -c
      - |
         sleep infinity
    name: test-pd
    resources:
      limits:
        memory: 2Gi
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 4Gi
```

kubectl exec -it example -- sh
cd /dev/shm/
dd if=/dev/zero of=filename bs=1024 count=2GB
command terminated with exit code 137

In this case, the pod is unable to start again and it gets stuck with:

```
7s          Warning   Failed                    pod/example               Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: container init was OOM-killed (memory limit too low?): unknown
```

### Anything else we need to know?

This is probably a long outstanding issue so its unclear if this will be fixed as a bug.

### Kubernetes version

<details>

```console
$ kubectl version
1.30
```

</details>

### Cloud provider

<details>
na
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
