### ISSUE TITLE
DRA: Is it possible to add a new resource: ClusterResourceClaim?

### ISSUE THREAD

**Issue by cyclinder** [kubernetes/kubernetes#128440]
### What would you like to be added?

We plan to develop a DRA plugin for networking (possibly related to CNI drivers). For ease of use, we may create a ResourceClaim in advance and declare some additional configurations in the opaqueConfig. If there is a cluster-scope ResourceClaim, then pods in different namespaces can use the same ResourceClaim. Currently, ResourceClaim is namespace-scope, meaning each namespace must create at least one ResourceClaim.

### Why is this needed?

add a new resource: ClusterResourceClaim

**Comment by pohly** [comment]
This looks like a reasonable discussion topic for the working group. I'm keeping it in the "new" state in our board for that.

One topic to consider, which may also affect other types in Kubernetes and thus might be something for SIG Architecture: who in the cluster gets access to such a cluster-scoped claim?

**Comment by cyclinder** [comment]
> who in the cluster gets access to such a cluster-scoped claim?

I want to say the cluster admin, the cluster admin is the response to creating a serval cluster-scoped ResourceClaim(maybe same time with `DeviceClass`), and a resourceclaim represents a set of CNI configurations that the end-user has permission to use, but not to create or delete.

**Comment by pohly** [comment]
Presumably pods will have new fields to reference a ClusterResourceClaim or ClusterResourceClaimTemplate. These new fields then need to be restricted to more privileged users ("cluster admin"). This is similar to allowing resp. not allowing "adminAccess: true".

Unfortunately, Kubernetes has no good way of expressing such a policy. It can be done with a VAP, but that then raises the question of how a "builtin VAP" gets deployed and updated.

**Comment by cyclinder** [comment]
@aojea Could you show your ResourceSlice look like? 

> There is a global networking config https://github.com/aojea/kubernetes-network-driver/blob/main/examples/deviceclass.yaml

In this example,  the deviceClass `dummy-interfaces` is represents the configuration of the dummy CNI, If we have a serval CNIs(macvlan,ipvlan,sriov...) in a cluster, we also need a few deviceClass, For each CNI, there may be one or more Device Classes (the same CNI may also have different configurations, e.g., ipam), right?

> why DeviceClass is not enough? is Admin focused an and referenced by the claims,

I want to easing the works of the cluster admin, For a real production, the cluster admin creates at least one resourceClaim for each namespace, even if they're exactly the same. and when a new namespace is created. the cluster admin also need sync the resourceClaim to the new namespace, with a large production cluster, the number of namespaces can also be very large, which is a lot of work.

Yes we can develop a operator, when a new namespace added, the operator help us to sync the resourceClaim resources to the new namespace. It's a little overcomplicated.

like Multus Net-Atta-Def(NAD) CRD, the cluster admin creates some amount of NAD, the scope is cluster level, Users can use it with `namespace + name`. maybe we don't need the ClusterResourceClaim, By extending the Pod API, we can specify namespace when referencing ResourceClaim/ResourceClaimTemplate in `Pod.spec.ResourceClaims`. default to "", means that same as the namespace of the pod.

```
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr1
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
  resourceClaims:
  - name: dummy1
     resourceClaimName: dummy-interface-static-ip
     namespace: kube-system <=======
```

**Comment by sftim** [comment]
- I think this needs a KEP
- We could define a new system namespace for cluster level, cluster-critical dynamic resource offerings, and allow cross-namespace claiming with ReferenceGrants. Then we put the cluster-level dynamic resources in some namespace, _potentially_ this new system namespace but it wouldn't have to be.

**Comment by cyclinder** [comment]
- Once we have determined the direction to move forward, I am interested in drafting a KEP for this.
- New system namespace for dra, maybe `dra-system`? Just saying. we put the cluster-scoped dynamic resources in `dra-system`, we can reference it in `pod.Spec.ResourceClaims` like the following:

```
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr1
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
  resourceClaims:
  - name: dummy1
    resourceClaimName: dummy-interface-static-ip
    systemResourceClaimName/clusterResourceClaimName: dummy-interface-static-ip
```

`resourceClaimName` and `systemResourceClaimName/clusterResourceClaimName` cannot be configured simultaneously, only one can be configured.
