### ISSUE TITLE
Anonymous volumes not counted against pod ephemeral-storage limits

### ISSUE THREAD

**Issue by tyrken** [kubernetes/kubernetes#128500]
### What happened?

Hi, not sure if this is the correct place to report, but we're seeing an issue between K8s and containerd with tracking disk usage against ephmeral-storage limits.

We have K8s (AWS EKS) v1.26.15 with containerd 1.7.22 running on Amazon Linux 2 with cgroups v1.  If you apply the below K8s manifest you should get a pod that uses around 1 GiB of disk in either an anonymous volume (coming from the VOLUME instruction in the Dockerfile that created the image), or by switching to alternate value of `DEST_DIR` the container root file system or a named volume.

For the container root filesystem, I see the usage briefly appear in `crictl stats` before the pod is evicted due to exceeding its `ephemeral-storage` limit.  For the named volume, `crictl stats` stays at zero but the pod is similarly killed.  However for the anonymous volume case `crictl stats` stays similarly on zero but the pod remains running, as presumably K8s is not counting the usage towards the total.

While I can see both volumes in `crictl inspect` under status/mounts I'm not sure if containerd/cri or the kubelet is meant to be reporting the disk usage of volumes.  `kubectl get --raw /api/v1/nodes/$MY_NODE/proxy/stats` only shows the named volume, not anonymous ones.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-es-limit
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
  terminationGracePeriodSeconds: 1
  containers:
    - name: test
      image: postgres
      env:
        - name: DEST_DIR
          value: /var/lib/postgresql/data # Anon volume
          # value: /var/lib/misc # Container root fs
          # value: /data # Named volume
        - name: BIG_FILE
          value: /usr/lib/postgresql/17/bin/postgres # 9.6 MiB
      command:
        - bash
        - -c
        - "for RUN in {1..100}; do cp $BIG_FILE $DEST_DIR/dummy.$RUN ; done ; du -sh $DEST_DIR ; sleep 5000"
      resources:
        limits:
          cpu: 100m
          ephemeral-storage: 200Mi # Script uses almost 1 GiB
          memory: 128Mi
        requests:
          cpu: 100m
          ephemeral-storage: 200Mi
          memory: 128Mi
      volumeMounts:
        - name: named-storage
          mountPath: /data
  volumes:
    - name: named-storage
      emptyDir: {}
```

### What did you expect to happen?

For the pod described by the above YAML to get Evicted as using over storage limits

### How can we reproduce it (as minimally and precisely as possible)?

See included pod YAML

### Kubernetes version

<details>
v1.26.15
</details>

### Cloud provider

<details>
AWS - EKS v1.26
</details>

### OS version

<details>

```console
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"

Linux HOSTNAME 5.10.226-214.880.amzn2.x86_64 #1 SMP Tue Oct 8 16:18:15 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

<details>
containerd 1.7.22
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

**Comment by dims** [comment]
> correct place to report ..

this is AL2/EKS. Please open a support ticket with AWS.

/close

**Comment by vasim38** [comment]
The kubelet will only track the root filesystem for ephemeral storage. OS layouts that mount a separate disk to /var/lib/kubelet or /var/lib/containers will not report ephemeral storage correctly.

[+] https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

**Comment by tyrken** [comment]
@vasim38 I agree that upon reading the fine print, someone has carefully excluded anonymous volumes (declared in image/Dockerfile not K8s manifest).  But this sounds like a specification workaround not a sensible decision.  Unless there is some real reason it "cannot be done" then what SIG would this be further discussed in?

**Comment by benmoss** [comment]
I am seeing this on a kind cluster as well, it's not a EKS specific issue. Is this the same as https://github.com/kubernetes/kubernetes/issues/120149 ?

**Comment by benmoss** [comment]
Repro:

Create a docker image that has a `VOLUME` 
```
FROM ubuntu
RUN mkdir /myvol
RUN echo "hello world" > /myvol/greeting
VOLUME /myvol
CMD ["sleep", "infinity"]
```

Create a pod with that container and an ephemeral storage limit:
```
apiVersion: v1
kind: Pod
metadata:
  name: repro
spec:
  containers:
  - image: repro
    name: repro
    resources: 
      limits:
        ephemeral-storage: 100Mi
```

Write 1Gi to the `/myvol` directory, but the pod won't be killed
```
kubectl exec -ti repro -- dd if=/dev/zero of=/myvol/wow  bs=1M  count=1000
```

```
$ crictl stats

CONTAINER           NAME                CPU %               MEM                 DISK                INODES
06b1d9599787e       repro               0.00                62.43MB             24.58kB             6
176e216c5fc6c       kube-proxy          0.00                19.52MB             69.63kB             25
9f287e4e80537       kindnet-cni         0.00                13.72MB             69.63kB             25
d27fd23c03f1b       wait                0.00                213kB               45.06kB             14
```

```
$ crictl inspect 06b | jq '.info.runtimeSpec.mounts[] | select(.destination == "/myvol").source' | xargs ls -alh
total 2.0G
drwxr-xr-x 2 root root 4.0K Nov  8 15:13 .
drwxr-xr-x 3 root root 4.0K Nov  8 15:13 ..
-rw-r--r-- 1 root root   12 Nov  8 14:27 greeting
-rw-r--r-- 1 root root 2.0G Nov  8 15:13 wow
