### ISSUE TITLE
Eviction manager should evict terminated pods before running pods

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/kubernetes#128790]
### What happened?

Consider two pods are running on the node:
1.  pod with a large image size but in terminated state.
2.  running pod which is utilizing disk space just above the eviction limit.

kubelet's eviction manager will evict the running pod first instead of evicting the terminated pod and cleaning up the image.

### What did you expect to happen?

kubelet should evict terminated pods and clean up images first beforing deciding to evict the running pod.

### How can we reproduce it (as minimally and precisely as possible)?

1. create a pod with large image size and let it run to completion (you can write some data to writable layers if there's no large image).
2. create a pod with different image but it should utilize disk space until eviction limit.
3. watch kubelet evict the running pod first.

### Anything else we need to know?

I think we should modify our node reclaim funcs to prioritize terminated pods first - https://github.com/kubernetes/kubernetes/blob/c9092f69fc0c099062dd23cd6ee226bcd52ec790/pkg/kubelet/eviction/helpers.go#L1222

### Kubernetes version

<details>

```console
$ kubectl version
1.31
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by hshiina** [comment]
`DeleteAllUnusedContainers()` looks to already delete terminated pods.

I tried running the following pods on my laptop with kind where `eviction-hard` is `nodefs.available<(availableBytes)-1GB`:

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: termpod
  name: termpod
spec:
  containers:
  - command:
    - sh
    - -c
    - dd if=/dev/random of=largefile bs=1048576 count=500 2>/dev/null
    image: busybox
    name: termcontainer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: activepod
  name: activepod
spec:
  containers:
  - command:
    - sh
    - -c
    - for i in `seq 800`; do dd if=/dev/random of=file${i} bs=1048576 count=1 2>/dev/null; sleep .1; done;
    image: busybox
    name: activecontainer
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
```

These pods are expected to work as following:
1. `termpod` gets terminated after consuming 500MB.
2. When `activepod` consumes 500MB, `termpod` is evicted, which means the container and sandbox are deleted in the runtime.
3. `activepod` gets completed without being evicted.

As far as I tried a few times, there were both cases where `activepod` gets succeeded and evicted.

I suspect the disk usage might be updated asynchronously after the terminated pod is deleted so that the summary might has an older value:
https://github.com/kubernetes/kubernetes/blob/f3cbd79db7f0c86a2d3602fdff6b174543d2cf1c/pkg/kubelet/eviction/eviction_manager.go#L477

**Comment by AnishShah** [comment]
@hshiina , `DeleteAllUnusedContainers` does not delete terminated pods by default. It deletes terminated pods only if you use the deprecated flag [`minimum-container-ttl-duration`](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L313C44-L313C74).

Can you check if you're using that?

**Comment by hshiina** [comment]
> [@hshiina](https://github.com/hshiina) , `DeleteAllUnusedContainers` does not delete terminated pods by default. It deletes terminated pods only if you use the deprecated flag [`minimum-container-ttl-duration`](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L313C44-L313C74).
> 
> Can you check if you're using that?

I didn't use `minimum-container-ttl-duration`.

My understanding is:
1. Without `minimum-container-ttl-duration`, all containers that are not running are regarded as evictable no matter when they are created because `minAge` is `0`:
   https://github.com/kubernetes/kubernetes/blob/2d0a4f75560154454682b193b42813159b20f284/pkg/kubelet/kuberuntime/kuberuntime_gc.go#L197-L207
2. Then, containers in terminated pods are deleted because `evictNonDeletedPods` is `true`:
  https://github.com/kubernetes/kubernetes/blob/2d0a4f75560154454682b193b42813159b20f284/pkg/kubelet/kuberuntime/kuberuntime_gc.go#L237-L238

**Comment by KevinTMtz** [comment]
I verified the behavior mentioned by @hshiina, and effectively the `DeleteAllUnusedContainers` and `DeleteUnusedImages` are already cleaning up the containers belonging to terminated pods.

I tried multiple times, and found that the behavior was consistent when the corresponding image to be deleted was older than the default `minAge` required for an image to be eligible for cleanup. I used the following pods:

#### Terminated pod
This pod should be marked as `Completed` before executing the Running pod, and its image is big enough (4.67GB) to remove disk pressure when the image is cleaned up.
```
apiVersion: v1
kind: Pod
metadata:
  name: android
spec:
  restartPolicy: Never
  containers:
  - name: android
    image: cimg/android:2024.11.1-ndk
    command: ["sh", "-c", "sleep 0"]
    volumeMounts:
    - name: tmp-volume
      mountPath: /tmp
  volumes:
  - name: tmp-volume
    emptyDir: {}
```

#### Runnning pod
This pod writes 10GB of storage, and is expected to continue running even when it causes disk pressure on the node, as the cleaning of the terminated pod frees up enough resources to remove the disk pressure.
```
apiVersion: v1
kind: Pod
metadata:
  name: over-limit
spec:
  containers:
  - name: over-limit
    image: busybox
    command: ["sh", "-c", "dd if=/dev/zero of=/tmp/largefile bs=1M count=10000 && sleep infinity"]
    volumeMounts:
    - name: tmp-volume
      mountPath: /tmp
  volumes:
  - name: tmp-volume
    emptyDir: {}
```
