### ISSUE TITLE
Failure cluster [c199077e...]: Pod InPlace Resize Container pod-resize-resource-quota-test

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#128840]
##### Error text:
```
[FAILED] exceeded quota: resize-resource-quota, requested: memory=350Mi, used: memory=700Mi, limited: memory=800Mi
Expected an error to have occurred.  Got:
    <nil>: nil
In [It] at: k8s.io/kubernetes/test/e2e/node/pod_resize.go:172 @ 11/13/24 12:32:16.302

```

Another failure:

```
container[c1] status resources mismatch: Expected
    <v1.ResourceRequirements>: 
        limits:
          cpu: 300m
          memory: 300Mi
        requests:
          cpu: 300m
          memory: 300Mi
to equal
    <v1.ResourceRequirements>: 
        limits:
          cpu: 400m
          memory: 400Mi
        requests:
          cpu: 400m
          memory: 400Mi
```

#### Recent failures:
[11/18/2024, 3:48:51 AM ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce/1858341567471816704)
[11/17/2024, 5:34:50 PM ci-kubernetes-e2e-gci-gce-ip-alias](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce-ip-alias/1858187048112885760)
[11/17/2024, 11:42:35 AM ci-containerd-e2e-ubuntu-gce](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-containerd-e2e-ubuntu-gce/1858098195528159232)
[11/17/2024, 5:48:18 AM ci-kubernetes-e2e-kind-alpha-beta-features](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kind-alpha-beta-features/1858008341704347648)
[11/16/2024, 12:34:32 PM ci-containerd-e2e-ubuntu-gce](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-containerd-e2e-ubuntu-gce/1857748878409863168)

/kind failing-test
/kind flake
/sig node
