### ISSUE TITLE
In terminating pod, status of containers is not updated

### ISSUE THREAD

**Issue by olyazavr** [kubernetes/kubernetes#128820]
### What happened?

When a pod with several containers is terminating, until all of those containers successfully terminate, the number of ready containers is not updated. For example, if you have a pod with two containers and one of them immediately exits and one of them has a prestop hook that sleeps for several minutes, the pod will show up as 2/2 containers ready even though one container immediately exits.

See kubelet logs here: https://gist.github.com/olyazavr/7f77673a47ce441b3a8670d509de8b16

### What did you expect to happen?

I expect that the pod status should reflect the number of containers that is actually ready, even if the pod is terminating.

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod with two containers, one of which has a prestop hook that sleeps:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  terminationGracePeriodSeconds: 200
  containers:
  - name: test
    command: ["bash", "-c", "sleep infinity"]
  - name: test2
    command: ["bash", "-c", "sleep infinity"]
    lifecycle:
      preStop:
        exec:
          command: ["bash", "-c", "sleep 180"]

```

Delete the pod, and notice that it will stay at 2/2 ready until both containers die even when the runtime acknowledges that one container has been successfully shut down early on

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.10
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.10
```

</details>

### Cloud provider

<details>
aws
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="9.3 (Shamrock Pampas Cat)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.3 (Shamrock Pampas Cat)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
$ uname -a
Linux ip-172-18-59-83 6.1.109-hs83.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Sep 24 17:33:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
crio and containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chengjoey** [comment]
I tried to reproduce this problem. In my attempt, 2/2 is consistent with the number displayed in container runtime.

get pods:
```
NAME       READY   STATUS        RESTARTS   AGE
test-pod   2/2     Terminating   0          18s
```

containers:
```
79061545   busybox                     "sh -c 'sleep infini…"   42 seconds ago   Up 42 seconds             k8s_test2_test-pod_default_4c14661b-2f5a-43d5-8d3f-5ad01b_0
9280ccda3   busybox                     "sh -c 'sleep infini…"   45 seconds ago   Up 44 seconds             k8s_test_test-pod_default_4c14661b-2f5a-43d5-8d3f-5a01b_0
```

**Comment by olyazavr** [comment]
Both crio and containerd report the containers that exited early as exited, so it should be reflected in the container statuses in the pod:


With crio, this is the container without the prestop hook:
```
crictl inspect 45782987e025b5b802bac3a4310abd39e4663798e17609742850089ee5644473 | head
{
  "status": {
    "id": "45782987e025b5b802bac3a4310abd39e4663798e17609742850089ee5644473",
    "metadata": {
      "attempt": 0,
      "name": "test"
    },
    "state": "CONTAINER_EXITED",
    "createdAt": "2024-11-17T16:13:37.451448Z",
    "startedAt": "2024-11-17T16:13:37.815007698Z",
 ```

the container with prestop hook:
```
crictl inspect fca3701940c0035a1993eb67ba50ece67db02c88de17d153d32bf1af7b4c05dd | head
{
  "status": {
    "id": "fca3701940c0035a1993eb67ba50ece67db02c88de17d153d32bf1af7b4c05dd",
    "metadata": {
      "attempt": 0,
      "name": "test2"
    },
    "state": "CONTAINER_RUNNING",
    "createdAt": "2024-11-17T16:13:38.781815Z",
    "startedAt": "2024-11-17T16:13:39.154641227Z",
```

and yet, when getting the pod status:
```
 containerStatuses:
  - containerID: cri-o://45782987e025b5b802bac3a4310abd39e4663798e17609742850089ee5644473
    image: docker.hubteam.com/dockerbaseimages/almalinux-9-base:1336
    imageID: docker.hubteam.com/dockerbaseimages/almalinux-9-base@sha256:26ce41bb5f30e7a4e192769b3f5e05762ee6d0847c5b73c5ad042dffadcc355f
    lastState: {}
    name: test
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-11-17T16:13:37Z"
  - containerID: cri-o://fca3701940c0035a1993eb67ba50ece67db02c88de17d153d32bf1af7b4c05dd
    image: docker.hubteam.com/dockerbaseimages/almalinux-9-base:1336
    imageID: docker.hubteam.com/dockerbaseimages/almalinux-9-base@sha256:26ce41bb5f30e7a4e192769b3f5e05762ee6d0847c5b73c5ad042dffadcc355f
    lastState: {}
    name: test2
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-11-17T16:13:39Z"
```


Same thing with containerd:
```
crictl inspect 54e437a1f3deac659c465d3d3623a983308ae9d1422bccccf1d449e572fff260 | head
{
  "status": {
    "id": "54e437a1f3deac659c465d3d3623a983308ae9d1422bccccf1d449e572fff260",
    "metadata": {
      "attempt": 0,
      "name": "test"
    },
    "state": "CONTAINER_EXITED",
    "createdAt": "2024-11-17T16:17:58.464318874Z",
    "startedAt": "2024-11-17T16:17:59.67610185Z",
 ```

and the container with the prestop hook:
```
crictl inspect 16aae606df9ef9b7b8fda53215e0490fcbaf8425373e8c9e83db15d25b1e0dc2 | head
{
  "status": {
    "id": "16aae606df9ef9b7b8fda53215e0490fcbaf8425373e8c9e83db15d25b1e0dc2",
    "metadata": {
      "attempt": 0,
      "name": "test2"
    },
    "state": "CONTAINER_RUNNING",
    "createdAt": "2024-11-17T16:17:59.683259546Z",
    "startedAt": "2024-11-17T16:18:00.930015649Z",
  ```

and yet, pod status:
```
 containerStatuses:
  - containerID: containerd://54e437a1f3deac659c465d3d3623a983308ae9d1422bccccf1d449e572fff260
    image: docker.hubteam.com/dockerbaseimages/almalinux-9-base:1336
    imageID: docker.hubteam.com/dockerbaseimages/almalinux-9-base@sha256:d3d204786f89bbc3a0328d6afec54d2eca41ccd118972c38c6c78c7a66a2920f
    lastState: {}
    name: test
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-11-17T16:17:59Z"
  - containerID: containerd://16aae606df9ef9b7b8fda53215e0490fcbaf8425373e8c9e83db15d25b1e0dc2
    image: docker.hubteam.com/dockerbaseimages/almalinux-9-base:1336
    imageID: docker.hubteam.com/dockerbaseimages/almalinux-9-base@sha256:d3d204786f89bbc3a0328d6afec54d2eca41ccd118972c38c6c78c7a66a2920f
    lastState: {}
    name: test2
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-11-17T16:18:00Z"
 ```

**Comment by hshiina** [comment]
This looks caused because a pod worker that updates the pod API status gets blocked until all containers are stopped:
https://github.com/kubernetes/kubernetes/blob/cf480a3a1a9cb22f3439c0a7922822d9f67f31b5/pkg/kubelet/kubelet.go#L2084

Only container readiness can be updated if a readiness probe is configured to a container because a probe failure is handled by another thread.

**Comment by HirazawaUi** [comment]
This issue occurs because when calling `killPodWithSyncResult`, we must wait for all containers in the pod to terminate before returning and reporting the pod's status to the API Server.

If the pod defines multiple containers, each with a different preStop hook, we must wait for all the preStop hooks to complete before returning and reporting the status of all containers in the pod.

https://github.com/kubernetes/kubernetes/blob/a499facee693a1a83daadb82d88f7b51d324ffc5/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1531-L1551

I think this request is reasonable. The kubelet should report the container's status more quickly to keep it consistent with the status provided by the CRI.

/cc @SergeyKanzhelev @smarterclayton

**Comment by AnishShah** [comment]
/assign @SergeyKanzhelev 

sig-node CI meeting:

/triage accepted
/priority backlog

**Comment by pandeykushagra51** [comment]
@olyazavr  I was able to reproduce this issue using the corrected pod deployment file below:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  terminationGracePeriodSeconds: 200
  containers:
  - name: test1
    command: ["sh", "-c", "trap 'exit 0' TERM; while true; do sleep 1; done"]
  - name: test2
    command: ["sh", "-c", "trap 'exit 0' TERM; while true; do sleep 1; done"]
    lifecycle:
      preStop:
        exec:
          command: ["sh", "-c", "sleep 180"]

```
Issue with the original YAML:

- The command ["bash", "-c", "sleep infinity"] ignores SIGTERM signals
- Both containers only terminate when receiving SIGKILL after the full terminationGracePeriod expires
- This means both containers are always killed forcefully, making it impossible to observe the ready count bug during different termination timings

The corrected version:

- Adds proper signal handling with trap 'exit 0' TERM
- Allows test1 to exit gracefully immediately upon receiving SIGTERM
- test2 runs the 180-second preStop hook before exiting gracefully

This creates the scenario where containers terminate at different times, making the ready count bug visible

After examining the kubelet code, I found the actual root cause: The SyncTerminatingPod() function sets the initial pod status when termination begins, then calls killPod() which blocks the entire thread until ALL containers are terminated. During this blocking operation, there are no intermediate status updates sent to the API server. The pod status is only updated again after all containers have completely stopped, which is why the ready count remains frozen at 2/2 throughout the termination process instead of updating incrementally as individual containers exit.
