### ISSUE TITLE
kube-proxy nftables test are flaky

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#128829]
### Which jobs are flaking?

https://testgrid.k8s.io/sig-network-kind#sig-network-kind,%20nftables,%20master
https://testgrid.k8s.io/sig-network-kind#sig-network-kind,%20nftables,%20IPv6,%20master

### Which tests are flaking?

Seems to impact test randomly

### Since when has it been flaking?

15-11-2024

### Reason for failure (if possible)

Checking at https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-kubernetes-kind-network-nftables/1858001043166597120/artifacts/kind-worker/pods/kube-system_kube-proxy-tbpmz_fdcd393e-47df-4afe-a88e-27eaa918f570/kube-proxy/0.log

it seems there is some contention on the system

```
2024-11-17T04:51:06.117022547Z stderr F E1117 04:51:06.116486       1 proxier.go:1210] "Unable to delete stale chains; will retry later" err=<
2024-11-17T04:51:06.117050539Z stderr F 	/dev/stdin:2:28-104: Error: Could not process rule: Device or resource busy
2024-11-17T04:51:06.117056524Z stderr F 	delete chain ip kube-proxy endpoint-LR2XJHKW-services-4884/service-proxy-toggled/tcp/__10.244.1.180/9376
2024-11-17T04:51:06.117062922Z stderr F 	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-17T04:51:06.117070369Z stderr F 	/dev/stdin:51:28-109: Error: Could not process rule: Device or resource busy
2024-11-17T04:51:06.117075351Z stderr F 	delete chain ip kube-proxy endpoint-23XNSDHO-nettest-2983/session-affinity-service/udp/udp__10.244.1.119/8081
2024-11-17T04:51:06.117079767Z stderr F 	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-17T04:51:06.117084441Z stderr F 	/dev/stdin:57:28-108: Error: Could not process rule: Device or resource busy
2024-11-17T04:51:06.117088698Z stderr F 	delete chain ip kube-proxy endpoint-CLRXJGC4-services-8162/affinity-clusterip-timeout/tcp/__10.244.1.97/9376
2024-11-17T04:51:06.117092772Z stderr F 	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-17T04:51:06.117096629Z stderr F 	/dev/stdin:58:28-104: Error: Could not process rule: Device or resource busy
2024-11-17T04:51:06.117100766Z stderr F 	delete chain ip kube-proxy endpoint-O34ANCIM-services-4884/service-proxy-toggled/tcp/__10.244.1.181/9376
2024-11-17T04:51:06.117122875Z stderr F 
```

it seems to be present in multiple jobs https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-kubernetes-kind-network-nftables/1857638650775343104/artifacts/kind-worker/pods/kube-system_kube-proxy-mcfxw_41e1cb46-c2e5-440c-8174-246253f0def2/kube-proxy/0.log , most probably on some of them reconciling solves the problem
```
2024-11-16T04:31:53.06971039Z stderr F I1116 04:31:53.068065       1 proxier.go:1174] "Syncing nftables rules" ipFamily="IPv4"
2024-11-16T04:31:53.069715193Z stderr F I1116 04:31:53.068092       1 proxier.go:1204] "Deleting stale nftables chains" ipFamily="IPv4" numChains=4
2024-11-16T04:31:53.126729378Z stderr F E1116 04:31:53.125738       1 proxier.go:1210] "Unable to delete stale chains; will retry later" err=<
2024-11-16T04:31:53.12702478Z stderr F 	/dev/stdin:2:28-100: Error: Could not process rule: Device or resource busy
2024-11-16T04:31:53.12703517Z stderr F 	delete chain ip kube-proxy endpoint-YHMEV5IX-services-5210/externalip-test/tcp/http__10.244.1.6/9376
2024-11-16T04:31:53.127040928Z stderr F 	                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-16T04:31:53.127046499Z stderr F  > ipFamily="IPv4"
```

### Relevant SIG(s)

/sig network

**Comment by danwinship** [comment]
"Device or resource busy" is `EBUSY`, which in the context of "`nft delete chain`" means "you're trying to delete a chain that is still referenced from elsewhere".

It looks like this is probably a failure in the partial-sync code; it's not removing a service chain that it should be removing, so it's not possible to remove the corresponding endpoint chains.

**Comment by aojea** [comment]
is it harmless? a red herring?

**Comment by danwinship** [comment]
cc @npinaeva

**Comment by aojea** [comment]
/priority important-soon

Checking this occurrence https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-kind-network-nftables/1858725882303090688


The pod is not able to connect to the Service
```
1119 04:40:04.726397 71449 builder.go:146] stderr: "+ curl -q -s --connect-timeout 5 172.18.0.2:31520/hostname\n"
I1119 04:40:04.726459 71449 builder.go:147] stdout: "webserver-pod"
I1119 04:40:04.726616 71449 service.go:2126] Unexpected error: pod on node1 still serves traffic: 
    <context.deadlineExceededError>: 
    context deadline exceeded
    
        {}
[FAILED] pod on node1 still serves traffic: context deadline exceeded
```

The client runs in kind-worker2
```
I1119 04:40:04.963881 71449 resource.go:175] pause-pod-1    kind-worker2  Running         [{PodReadyToStartContainers True 0001-01-01 00:00:00 +0000 UTC 2024-11-19 04:39:04 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-11-19 04:39:02 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2024-11-19 04:39:04 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2024-11-19 04:39:04 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-11-19 04:39:02 +0000 UTC  }]
```

The rule for the service can not be added because the sync is failing constantly
```
2024-11-19T04:39:32.738428609Z stderr F I1119 04:39:32.734032       1 proxier.go:1174] "Syncing nftables rules" ipFamily="IPv4"
2024-11-19T04:39:32.906117415Z stderr F I1119 04:39:32.902204       1 proxier.go:1794] "Reloading service nftables data" ipFamily="IPv4" numServices=82 numEndpoints=88
2024-11-19T04:39:33.035933438Z stderr F E1119 04:39:33.034689       1 proxier.go:1805] "nftables sync failed" err=<
2024-11-19T04:39:33.035955957Z stderr F 	/dev/stdin:419:1-122: Error: Could not process rule: File exists
2024-11-19T04:39:33.035961651Z stderr F 	add element ip kube-proxy no-endpoint-nodeports { tcp . 30301 comment "services-7322/svc-proxy-terminating:http" : drop }
2024-11-19T04:39:33.035966413Z stderr F 	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-19T04:39:33.036117951Z stderr F  > ipFamily="IPv4"
```

This should be a blocker for GA, there are 52  `nftables sync failed` errors on https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-kubernetes-kind-network-nftables/1858725882303090688/artifacts/kind-worker2/pods/kube-system_kube-proxy-nddrb_99e30ca6-ba3d-419a-873d-1b942b553f5e/kube-proxy/0.log that are impacting Services

**Comment by npinaeva** [comment]
@aojea @danwinship it looks like kernel version update is the reason for these failures
on `11-15` kernel version was updated from `5.15.0-1061-gke` to `5.15.0-1067-gke` and that is the first time (IFAICS) when we found this problem. We have already seen that kube-proxy does correct transactions and gets unexpected errors.
Is there a way to reach out to the team that builds those `gke` kernels and check what changes were introduced around netfilter?

**Comment by aojea** [comment]
@SergeyKanzhelev @yujuhong can you help me to connect the kernel version to the COS image version?

https://cloud.google.com/container-optimized-os/docs/release-notes

I think that COS 105 LTS are the ones based on kernel 5.15 , @BenTheElder @ameukam @mauriciopoppe is there any plan to update the node pools we use on CI to a more modern version of the kernel?

**Comment by ameukam** [comment]
@aojea We use Ubuntu (22.04) for the nodepools : 
https://github.com/kubernetes/k8s.io/blob/6f350eef158a5f0268adee8395c9827b5553a55b/infra/gcp/terraform/k8s-infra-prow-build/main.tf#L100

and they are auto-upgraded based on the GKE Version (currently `v1.30.5-gke.1443001`) .
Maybe ask internally (or `bobbypage`) which GKE version has the kernel version you are looking for ? 
AFAIK:
GKE 1.31: ubuntu 22.04 (Kernel 5.17.x)
GKE 1.32: Ubunut 24.04 (Kernel 6.8.x)

**Comment by danwinship** [comment]
5.15 should be new enough... it just seems like maybe this particular build has a bad backport or something...

**Comment by mauriciopoppe** [comment]
https://github.com/kubernetes/k8s.io/blob/6f350eef158a5f0268adee8395c9827b5553a55b/infra/gcp/terraform/k8s-infra-prow-build/main.tf#L100 seems to be the prow builder VM but not a GCE nodepool VM. However because this is a kind cluster I believe that the k8s cluster would be built on top of the prow builder VM.

From https://github.com/kubernetes/kubernetes/issues/128829#issue-2666254702 I believe the next question is for the GCE nodepool VMs but I'll try to answer it:

> I think that COS 105 LTS are the ones based on kernel 5.15, @SergeyKanzhelev @yujuhong can you help me to connect the kernel version to the COS image version?

The last time I remember there was an update of the COS version for data plane nodes created on top of GCE VMs it was through https://github.com/kubernetes/test-infra/pull/31016. It's been a while since then so I'm not sure if there were more changes, if testing on COS the kernel mapping is as follows:

- COS 109 - 6.1
- COS 113 - 6.1
- COS 117 - 6.6

You can find additional details in https://cloud.google.com/container-optimized-os/docs/release-notes.

For the prow builder VM and kind, https://github.com/kubernetes/k8s.io/blob/6f350eef158a5f0268adee8395c9827b5553a55b/infra/gcp/terraform/k8s-infra-prow-build/main.tf#L100 points to a GKE nodepool running Ubuntu 22.04 which uses kernel 5.15 as mentioned in https://github.com/kubernetes/kubernetes/issues/128829#issuecomment-2497466269.

I can give more details about the Ubuntu 22.04 version, where can I see the prow builder VM creation logs or the terraform logs? I'd like to know the GKE version it was used to create the nodepool, the reason is that the GKE version would change over time because of `release_channel    = "REGULAR"`.

**Comment by npinaeva** [comment]
here are the job artifacts https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/pr-logs/pull/128886/pull-kubernetes-e2e-kind-nftables/1859623692095459328/ hopefully there is some useful info

**Comment by BenTheElder** [comment]
> @BenTheElder @ameukam @mauriciopoppe is there any plan to update the node pools we use on CI to a more modern version of the kernel?

We use managed clusters where possible (because we don't have a lot of time to operate Kubernetes vs develop it), and that includes the OS image in the GKE case, so that cadence is automated and tied to the GKE release channel.

We have currently opted for Ubuntu, because it had IPv6 kernel modules (available, but not loaded) when COS did not, years ago, and we've been using it ever since setting up the first IPv6 (kind) jobs. It's possible we could switch to COS but ...

If we need to test on specific Kernel versions, we should implement that directly (disposable VMs etc where we explicitly control this in the CI config).

The kind jobs running within the CI pods currently run primarily on the main GKE CI cluster but could be on EKS if we need to shift costs or maybe someday, with more funding ,another provider. I'm not sure what kernels we have on EKS currently but it should be something that works with a stable Kubernetes release.

**Comment by mauriciopoppe** [comment]
1.30.5-gke.1443001 -> ubuntu-gke-2204-1-30-v20240929 with the following release notes:

```
gsutil cat gs://ubuntu-os-gke-cloud/ubuntu-gke-2204-1-30-v20240929.release-notes-summary.json
{
    "build_info_serial": "20240929",
    "release_version": "22.04.5 LTS (Jammy Jellyfish)",
    "release_version_id": "22.04",
    "release_version_codename": "jammy",
    "linux_gke_version": "5.15.0-1067-gke",
    "gke_nvidia_driver_version": "535.161.07",
    "gke_nvidia_driver_gpu_versions": {},
    "gke_variant": "1.30",
    "gke_image_track": "stable",
    "gke_image_cgroups_variant": "2",
    "runc_version": "1.1.7-0ubuntu1~22.04.2",
    "containerd_version": "1.7.22-0ubuntu0~22.04.1~gke1",
    "docker_version": "20.10.12-0ubuntu3",
    "architecture": "amd64"
}
```

With the current setup where the GKE version comes from the regular channel we could possible bump to Ubuntu 24.04 (which uses kernel 6.8) in GKE 1.32 however this is still up in the air, we are aware of at least one blocker issue that if not addressed would make us stay with Ubuntu 22.04 in GKE 1.32. Anyways, in the happy path where we adopt it in GKE 1.32 I think that a good estimate for it to be available in Regular is the last week of January 2025.

https://github.com/kubernetes/kubernetes/issues/128829#issuecomment-2497466269 has a good insight on a possible kernel diff that might have introduced flakiness, @npinaeva we can ask Canonical about kernel diffs between these two versions `5.15.0-1061-gke` to `5.15.0-1067-gke` that might have introduced a problem visible in this test.

**Comment by npinaeva** [comment]
Filed a bug https://bugs.launchpad.net/ubuntu/+bug/2089699, let's see how it goes

**Comment by aojea** [comment]
> https://github.com/kubernetes/kubernetes/issues/128829#issuecomment-2497466269 has a good insight on a possible kernel diff that might have introduced flakiness, @npinaeva we can ask Canonical about kernel diffs between these two versions 5.15.0-1061-gke to 5.15.0-1067-gke that might have introduced a problem visible in this te

@mauriciopoppe appreciate if you can get some eyes on this from Canonical, in case you have any contact

**Comment by mauriciopoppe** [comment]
Yes, I'll meet them tomorrow and I'll talk about them about [bugs.launchpad.net/ubuntu/+bug/2089699](https://bugs.launchpad.net/ubuntu/+bug/2089699), thanks for filing it.

**Comment by mauriciopoppe** [comment]
Canonical is aware of [bugs.launchpad.net/ubuntu/+bug/2089699](https://bugs.launchpad.net/ubuntu/+bug/2089699) and were looking for info to reproduce this. Having a similar environment would be hard given that they don't have access to GKE but I mentioned that they just need a GCE VM using the image that they provide to GKE, that's for the VM setup only but for the test it might be difficult to set it up in the same way as https://git.k8s.io/test-infra/config/jobs/kubernetes/sig-network/sig-network-kind.yaml.

Is there a way to provide a shell script that can run the test? E.g. turn the Pod spec into something that can be run through a script or through a regular Pod? e.g.

```
  pod_spec:
    containers:
    - command:
      - wrapper.sh
      - bash
      - -c
      - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz -
        -C "${PATH%%:*}/" && e2e-k8s.sh
      env:
      - name: GINKGO_TOLERATE_FLAKES
        value: "n"
      - name: KUBE_PROXY_MODE
        value: nftables
      - name: PARALLEL
        value: "true"
      - name: FOCUS
        value: \[sig-network\]|\[Conformance\]
      - name: SKIP
        value: Alpha|Beta|LoadBalancer|Disruptive|Flaky|IPv6DualStack|Networking-IPv6|Internet.connection
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      - name: E2E_GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      - name: GOOGLE_APPLICATION_CREDENTIALS_DEPRECATED
        value: Migrate to workload identity, contact sig-testing
      - name: DOCKER_IN_DOCKER_ENABLED
        value: "true"
      - name: GOPROXY
        value: https://proxy.golang.org
      - name: AWS_ROLE_SESSION_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      image: gcr.io/k8s-staging-test-infra/krte:v20241128-8df65c072f-master
      name: ""
      resources:
        limits:
          cpu: "4"
          memory: 9Gi
        requests:
          cpu: "4"
          memory: 9Gi
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /etc/service-account
        name: service
        readOnly: true
      - mountPath: /docker-graph
        name: docker-graph
      - mountPath: /var/lib/docker
        name: docker-root
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: service
      secret:
        secretName: service-account
    - emptyDir: {}
      name: docker-graph
    - emptyDir: {}
      name: docker-root
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules
    - hostPath:
        path: /sys/fs/cgroup
        type: Directory
      name: cgroup
```
