### ISSUE TITLE
Sidecar Containers for Services are not accessible

### ISSUE THREAD

**Issue by mbrancato** [kubernetes/kubernetes#128825]
### What happened?

I'm using a helm chart to deploy an application, and I typically insert an specific proxy I need as a legacy sidecar (after init). However, this helm chart specifically does now allow specifying additional containers (again, legacy sidecar pattern), but it does allow specifying init containers using the newer [Sidecar Containers](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) feature.

The sidecar config might look like this with the new sidecar pattern:
```yaml
      initContainers:
        - name: myproxy
          image: myproxy
          restartPolicy: Always
          ports:
            - containerPort: 8080
              name: proxy-port
              protocol: TCP
```

After deploying this:
- The `v1/Service` has endpoints that point to the target pods
- Manually, I can connect to `<pod IP>:8080`
- Attempting to connect to the service results in a connection refused.

### What did you expect to happen?

The connection to the sidecar should work.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a pod with a named port in a container under `initContainers` with `restartPolicy: Always`
- Create a `v1/Service` that has a `selector` that targets the pod
- Attempt to lookup the SRV record

### Kubernetes version

<details>

```console
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.5-gke.1443001
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by toVersus** [comment]
The issue did not reproduce in my local kind cluster running Kubernetes 1.30.4 and 1.30.6.
At first, I thought it might be a bug fixed in https://github.com/kubernetes/kubernetes/pull/127976, but that doesn’t seem to be the case. Are you specifying the port name (`spec.ports[0].name` in the following example) defined in the Service? If not specified, the SRV record will not be created. Could you share the complete reproduction steps?

```console
❯ kind create cluster --image kindest/node:v1.30.4@sha256:976ea815844d5fa93be213437e3ff5754cd599b040946b5cca43ca45c2047114
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.30.4) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a nice day! 👋

❯ kubectl get nodes
NAME                 STATUS   ROLES           AGE   VERSION
kind-control-plane   Ready    control-plane   65s   v1.30.4

❯ cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  initContainers:
  - name: el-sidecar1
    image: registry.k8s.io/e2e-test-images/agnhost:2.52
    args: ["netexec", "--http-port=8090", "--udp-port=-1"]
    restartPolicy: Always
    ports:
    - containerPort: 8090
      name: http-sidecar
      protocol: TCP
  containers:
  - name: el1
    image: registry.k8s.io/e2e-test-images/agnhost:2.52
    args: ["netexec", "--http-port=8080", "--udp-port=-1"]
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  ports:
  - name: http-sidecar
    protocol: TCP
    port: 8090
    targetPort: http-sidecar
  selector:
    app: http-server
  type: ClusterIP
EOF
pod/http-server created
service/http-server created

❯ kubectl exec -it http-server -c el1 -- dig SRV _http-sidecar._tcp.http-server.default.svc.cluster.local

; <<>> DiG 9.16.48 <<>> SRV _http-sidecar._tcp.http-server.default.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 7488
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: f4bc48863118d01d (echoed)
;; QUESTION SECTION:
;_http-sidecar._tcp.http-server.default.svc.cluster.local. IN SRV

;; ANSWER SECTION:
_http-sidecar._tcp.http-server.default.svc.cluster.local. 27 IN	SRV 0 100 8090 http-server.default.svc.cluster.local.

;; ADDITIONAL SECTION:
http-server.default.svc.cluster.local. 27 IN A	10.96.98.56

;; Query time: 1 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Sat Nov 16 13:00:21 UTC 2024
;; MSG SIZE  rcvd: 263
```

**Comment by mbrancato** [comment]
I just want to clarify this means the `v1/Service` doesn't work as the ultimate result. I traced the cause back to a lack of SRV records for the port in question.

**Comment by mbrancato** [comment]
Thanks @toVersus - I've taken your example and updated it. I've also updated the issue to be a bit more broad - since it probably is not a problem with SRV records.

Below is a an example with two services:
- `http-server` - points to the initContainer port
- `http-server-direct` - points to the main container port

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  initContainers:
  - name: el-sidecar1
    image: registry.k8s.io/e2e-test-images/agnhost:2.52
    args: ["netexec", "--http-port=8090", "--udp-port=-1"]
    restartPolicy: Always
    ports:
    - containerPort: 8090
      name: http-sidecar
      protocol: TCP
  containers:
  - name: el1
    image: registry.k8s.io/e2e-test-images/agnhost:2.52
    args: ["netexec", "--http-port=8080", "--udp-port=-1"]
    ports:
    - containerPort: 8080
      name: http-direct
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-sidecar
  selector:
    app: http-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-direct
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-direct
  selector:
    app: http-server
  type: ClusterIP
```

Here the `http-server-direct` service is accessible (this is from a pod in the cluster):
```
# curl -v http-server-direct.default.svc.cluster.local
*   Trying 10.43.119.252:80...
* Connected to http-server-direct.default.svc.cluster.local (10.43.119.252) port 80 (#0)
> GET / HTTP/1.1
> Host: http-server-direct.default.svc.cluster.local
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 18 Nov 2024 00:51:35 GMT
< Content-Length: 61
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host http-server-direct.default.svc.cluster.local left intact
NOW: 2024-11-18 00:51:35.820105082 +0000 UTC m=+492.084894194
```

However, the `http-server` service is NOT accessible:
```
# curl -v http-server.default.svc.cluster.local
*   Trying 10.43.62.224:80...
* connect to 10.43.62.224 port 80 failed: Connection refused
* Failed to connect to http-server.default.svc.cluster.local port 80 after 1 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to http-server.default.svc.cluster.local port 80 after 1 ms: Couldn't connect to server
```

I'm testing with k3s here, but I originally experienced this on a GKE cluster:
```
% kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.5+k3s1
```
