### ISSUE TITLE
pod requesting zero devices with zero available fails admission for 'Allocate failed due to no healthy devices present'

### ISSUE THREAD

**Issue by yylt** [kubernetes/kubernetes#128854]
### What happened?

pod create failed

```
status:
  message: 'Pod was rejected: Allocate failed due to no healthy devices present; cannot allocate unhealthy devices      nvidia.com/gpu, which is unexpected'
  phase: Failed
  reason: UnexpectedAdmissionError
  startTime: "2024-11-19T03:04:55z"
```

pod yaml is 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jktest
spec:
  selector:
    matchLabels:
      workload.es.io: jktest
  template:
    metadata:
      labels:
        workload: jktest
    spec:
      containers:
      - image: centos:latest
        imagePullPolicy: IfNotPresent
        name: test
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
            nvidia.com/gpu: "0"
          requests:
            cpu: 250m
            memory: 512Mi
            nvidia.com/gpu: "0"
```

the node info is

```
...
allocatable: 
  memory: 252717800Ki       
  nvidia.com/gpu: "0"
  pods: "255"
capacity: 
  memory: 263278312Ki 
  nvidia.com/gpu: "0" 
  pods: "255"
```

This failure are very similar to https://github.com/kubernetes/kubernetes/issues/109191 , but the prompts are different.

### What did you expect to happen?

When the number of `external resource` requests in a pod is `0`, the creation is successful.

### How can we reproduce it (as minimally and precisely as possible)?

1 create pod a which use hot pluggable device in resource.request, and the resource is 1
2 remove device
3 create pod b which use hot pluggable device in resource.request, and the ressource is 0

### Anything else we need to know?

I am confident that this issue was introduced by the [pull](https://github.com/kubernetes/kubernetes/pull/114640).

Unable to control the application even when resources are not used, but set to 0, for more information see [issue](https://github.com/kubernetes/kubernetes/issues/109191).

### Kubernetes version

```console
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
