### ISSUE TITLE
[InPlacePodVerticalScaling]stuck in InProgress when patch resources in a special pod

### ISSUE THREAD

**Issue by ABNER-1** [kubernetes/kubernetes#128977]
### What happened?

In clusters with InPlacePodVerticalScaling enabled, if a pod without resource limits undergoes a resource patch change, its status will perpetually remain 'InProgress'. The kubelet log contains an error message: 'E1125 17:05:47.633962 12114 kuberuntime_manager.go:750] "podResources.CPUQuota or podResources.CPUShares is nil" pod="clone3-h6r9k"'.

### What did you expect to happen?

I hope this case can be closed-loop, and it can be achieved in any of the following ways:

1. Rejected by the api-server.
2. The proposal is rejected by Kubelet and displayed in `.status.resize`.
3. Able to be properly resized.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml pod.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    owner: clone
  name: clone-test
spec:
  containers:
  - env:
    - name: test
      value: foo
    image: registry.cn-hangzhou.aliyuncs.com/abner1/nginx:alpine
    imagePullPolicy: IfNotPresent
    name: nginx
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: NotRequired
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
  dnsPolicy: ClusterFirst
  terminationGracePeriodSeconds: 30
```
1. create pod
```bash
kubectl apply -f pod.yaml
```
2. wait pod ready
3. patch pod

```bash
kubectl patch po clone-test --type='json' -p='[{"op": "replace", "path": "/spec/containers/0/resources/requests/cpu", "value": "200m"}]'
```

4. You will encounter an error log like `podResources.CPUQuota or podResources.CPUShares is nil` in the Kubelet logs, and as a result, the pod will remain stuck in the 'InProgress' state.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
