### ISSUE TITLE
Add support for environment variable resolution in `httpGet` probe paths

### ISSUE THREAD

**Issue by bachmanity1** [kubernetes/kubernetes#128900]
Currently, Kubernetes does not support resolving environment variables in `httpGet` probe paths, which limits configuration flexibility.

Expected behavior:
- Allow environment variable interpolation like `path: "$(CONTEXT_PATH)/health/"`
- ~~Support standard shell-like variable substitution syntax~~

Sample configuration:
```yaml
       readinessProbe:
          httpGet:
            path: "$(CONTEXT_PATH)/actuator/health/readiness"
            port: 8080
            scheme: HTTP

```
