### ISSUE TITLE
Add configuration property to delete cronjobs if it succeeds after retry

### ISSUE THREAD

**Issue by renepupil** [kubernetes/kubernetes#128969]
### What would you like to be added?

Add a boolean cronjob property `deleteFailedJobsOnSuccess` that, when set to `true`, will effectively delete the failed jobs history of that cronjob when it succeeds based on retries dependent on `backoffLimit`.

So e.g. `backoffLimit: 2` and the 1. run fails, but the 2. succeeds, the 1. failed job should be kept in history.

### Why is this needed?

Sometimes cronjob fail because of temporary issues e.g. database not reachable for short amount of time, then the cronjob succeeds when it automatically runs again, but the failed job is still in the job history.

Setting `failedJobsHistoryLimit: 0` is not a solution as jobs are also not kept when the cronjob fails all the time.

Setting `ttlSecondsAfterFinished` (if possible for cronjobs) is also not a solution as the time is highly dependent on the schedule and has to be calculated to keep a failed job for some time until the next schedule, also the kept failed job might still me unnecessary as the cronjob could have been successful after a direct retry.

**Comment by Ruchi1499** [comment]
This enhancement would help clean up transient failures while retaining meaningful job history. A key consideration is whether all failed attempts should be deleted upon success or just the most recent one?

**Comment by Ruchi1499** [comment]
Some additional notable points for implementation:
**Failure Tracking:** The CronJob controller would need to maintain a state reference of previous job attempts to determine when to delete failed jobs.
**Edge Cases:** What should happen if a CronJob has multiple failed attempts before a success? Should all failures be deleted, or only the most recent one?
**Event Logging:** If failures are removed, should there still be a log entry indicating a failure occurred, even if it no longer exists in history?

**Comment by renepupil** [comment]
> What should happen if a CronJob has multiple failed attempts before a success?

I would simply let all jobs be deleted, there is no point keeping them after an issue is resolved.

> Should all failures be deleted, or only the most recent one?

All, at least the is the feature I request.

> If failures are removed, should there still be a log entry indicating a failure occurred, even if it no longer exists in history?

AFAIK "events" are not bound to existing resources, e.g. you still have pod logs after the pod has been deleted (e.g. from a successful cronjob)

**Comment by renepupil** [comment]
I created this kubernetes cronjob to delete failed jobs of cronjobs that had a successful successor job:

```yaml
# Workaround for feature request: https://github.com/kubernetes/kubernetes/issues/128969
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl-delete-jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delete-jobs
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-delete-jobs-role-to-internal-service-account
subjects:
  - kind: ServiceAccount
    name: internal-kubectl-delete-jobs
roleRef:
  kind: Role
  name: delete-jobs
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-failed-jobs-from-successful-cronjobs
spec:
  # Run every day at 07:00:
  schedule: "0 7 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 86400
      template:
        spec:
          serviceAccountName: internal-kubectl-delete-jobs
          containers:
            - name: bitname-kubectl
              image: bitnami/kubectl:${KUBECTL_VERSION}
              command:
                - bin/bash
                - -c
                - |
                  set -e -E -o pipefail -u # Add error handling.
                  
                  cronjobs="$(kubectl get cronjobs --no-headers -o custom-columns=":metadata.name")"
                  job_rows="$(kubectl get jobs --no-headers -o custom-columns=":metadata.name,:metadata.ownerReferences[0].kind,:metadata.ownerReferences[0].name,:status.failed")"
                  
                  for cronjob in ${cronjobs}; do
                    last_schedule_time="$(kubectl get cronjob "${cronjob}" -o jsonpath='{.status.lastScheduleTime}')"
                    last_successful_time="$(kubectl get cronjob "${cronjob}" -o jsonpath='{.status.lastSuccessfulTime}')"
                  
                    last_schedule_timestamp="$(date -d "${last_schedule_time}" +%s)"
                    last_successful_timestamp="$(date -d "${last_successful_time}" +%s)"
                  
                    # Delete failed jobs from cronjob if last scheduled run was succcesful:
                    if [ -n "${last_schedule_time}" ] && [ -n "${last_successful_time}" ] && [ "${last_schedule_timestamp}" -lt "${last_successful_timestamp}" ]; then
                      while IFS=' ' read -r jobname jobkind jobowner failed; do
                        # '.status.failed' represents the number of failed runs, see https://kubernetes.io/docs/concepts/workloads/controllers/job/#backoff-limit-per-index
                        number_of_failed_runs_or_none="$(echo "${failed}" | tr -d ',')" # remove comma
                  
                        # Can not separate into multiple lines because kubernetes is not able to deal with '\'.
                        if [ "${jobkind}" == 'CronJob' ] && [ "${jobowner}" == "${cronjob}" ] && [[ "$number_of_failed_runs_or_none" =~ ^-?[0-9]+$ ]] && (( number_of_failed_runs_or_none > 0 )); then
                          kubectl delete job "${jobname}"
                        fi
                      done <<< "${job_rows}"
                    fi
                  done
          restartPolicy: OnFailure 
```
