### ISSUE TITLE
Improper Permissions on ConfigMap and Secret Mounts

### ISSUE THREAD

**Issue by yakirk** [kubernetes/kubernetes#129043]
### What would you like to be added?

Hey, I am opening this issue publicly as it was approved by a member of the Kubernetes staff on HackerOne (#2867563) to be discussed with the larger community. Since addressing it would break existing users, it may require a Kubernetes Enhancement Proposal (KEP). The staff member also agreed that it is a poor default.

# Description
Kubernetes mounts ConfigMaps and Secrets to containers with default permissions -rw-r--r-- (644) also the permission on the ConfigMaps and Secrets directories mounted to the container is set to -rwxrwxrwx (777),
This configuration allows any user in the container, not just the root user, to read these files, exposing sensitive data and violating the principle of least privilege.
In multi-user containers, any non-root user can access these ConfigMaps and Secrets, further increasing the risk of unauthorized data exposure.
To prevent this, users can use the defaultMode parameter to set stricter permissions, such as 600/750, ensuring only the root user has access.
The current default behavior conflicts with the principle of least privilege, making manual adjustment necessary to protect sensitive data.

# Steps To Reproduce:
1. Create a Kubernetes ConfigMap or Secret.
2. Mount the ConfigMap or Secret into a container.
```
apiVersion: v1
kind: Pod
metadata:
  name: secret-mounted-pod
spec:
  containers:
    - name: my-app
      image: nginx:latest
      securityContext:
        runAsUser: 1000
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secret"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
```
3. Run the container with multiple users, including a non-root user (e.g., user ID 1000).
4. Observe that the default permissions are -rw-r--r-- and that any non-root user can read the mounted data.

### Why is this needed?

To mitigate this risk, we need to ensure that the directory and the mounted files of Configmaps/Secrets have permissions set to 750. This setting allows only the root user and the group owner to read and execute, while preventing access by other users.
his approach limits read access to the root/owner only, thereby following the principle of least privilege and reducing unauthorized exposure of sensitive data.
