### ISSUE TITLE
kubelet: PodRejectionStatus Kubelet should reject pod when the node didn't have enough resource test error

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#129056]
### What happened?

https://github.com/kubernetes/kubernetes/pull/128403 merged to move PodRejectionStatus into e2e/node from e2e/common/node. In certain cases this test fails because the test is comparing the entire status object. The test needs to be changed to validate the fields we care about.

```
Expected
    <v1.PodStatus>: 
        conditions:
        - lastProbeTime: null
          lastTransitionTime: "2024-11-29T14:10:06Z"
          status: "False"
          type: PodReadyToStartContainers
        - lastProbeTime: null
          lastTransitionTime: "2024-11-29T14:10:06Z"
          status: "True"
          type: Initialized
        - lastProbeTime: null
          lastTransitionTime: "2024-11-29T14:10:06Z"
          reason: PodFailed
          status: "False"
          type: Ready
        - lastProbeTime: null
          lastTransitionTime: "2024-11-29T14:10:06Z"
          reason: PodFailed
          status: "False"
          type: ContainersReady
        - lastProbeTime: null
          lastTransitionTime: "2024-11-29T14:10:06Z"
          status: "True"
          type: PodScheduled
        containerStatuses:
        - image: registry.k8s.io/pause:3.10
          imageID: ""
          lastState: {}
          name: pod-out-of-cpu
          ready: false
          restartCount: 0
          started: false
          state:
            waiting:
              reason: ContainerCreating
          volumeMounts:
          - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            name: kube-api-access-4dd6q
            readOnly: true
            recursiveReadOnly: Disabled
        hostIP: 10.0.128.3
        hostIPs:
        - ip: 10.0.128.3
        message: 'Pod was rejected: Node didn''t have enough resource: cpu, requested: 1000000000000000,
          used: 491, capacity: 3500'
        phase: Failed
        qosClass: Burstable
        reason: OutOfcpu
        startTime: "2024-11-29T14:10:06Z"
to equal
    <v1.PodStatus>: 
        message: 'Pod was rejected: Node didn''t have enough resource: cpu, requested: 1000000000000000,
          used: 491, capacity: 3500'
        phase: Failed
        qosClass: Burstable
        reason: OutOfcpu
        startTime: "2024-11-29T14:10:06Z"
```

### What did you expect to happen?

Expect the test case to run successfully.

### How can we reproduce it (as minimally and precisely as possible)?

See reproduced output.

### Kubernetes version

<details>
1.31+
</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
Linux
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
