### ISSUE TITLE
Namespace deletion does not trigger container lifecycle hooks

### ISSUE THREAD

**Issue by schen7179** [kubernetes/kubernetes#129097]
### What happened?

I want to ensure that certain commands are run on graceful deletion of a pod, so I have set up a container lifecycle prestop hook to do so. Deleting the pod does trigger the prestop hook as expected; however, when deleting the namespace that the pod is in, I would expect this to also be a graceful shutdown event, which should trigger the prestop hook, but this does not happen. In addition, helm uninstalling our helm chart with the relevant statefulset has the same issue. See the test example below where we have setup RBAC for kubectl access within the container:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: <>
  namespace: <>
  labels:
    component: <>
    app: <>
spec:
  ...
  template:
    metadata:
      labels:
    spec:
      containers:
        - name: testContainer
          image: <>
          lifecycle:
           preStop:
             exec:
               command:
                  - /bin/bash
                  - -c
                  - "kubectl label cm test-configmap -n test-prestop-hook testlabel=8 --overwrite"
             
```

### What did you expect to happen?

Prestop hook should be triggered by namespace deletion. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Bring up a pod with a container that has a prestop hook configured
2. Exec into the pod and label the ConfigMap to see that it works (no RBAC or image issues)
3. Delete the namespace that the pod is in (expected to trigger the prestop hook)
4. Wait 30 seconds and see that the prestop hook did not run, configmap label did not change to `testlabel: "8"`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.10-eks-7f9249a
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

NA

</details>

### Install tools

<details>
Using helm to install the helm chart with statefulset:

$ helm version
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by AmarNathChary** [comment]
> when deleting the namespace that the pod is in, I would expect this to also be a graceful shutdown event which should trigger the prestop hook,

When a namespace is deleted, K8s uses a namespace finalizer to clean up all resources. also K8s might clean up resources like Pods, bypassing some of the usual deletion procedures, including triggering the preStop hook.

**Comment by AmarNathChary** [comment]
>  but this does not happen. In addition, helm uninstalling our helm chart with the relevant statefulset has the same issue.

Similarly, when Helm uninstalls are used, resources like `Statefulsets` and `Pods` are deleted as part of the Helm release cleanup.

**Comment by AmarNathChary** [comment]
Try to add a _**finalizer**_ to the `Pods` or `StatefulSet` to delay their deletion. check your `StatefulSet` or `Pod` has a sufficiently large `terminationGracePeriodSeconds` to allow the prestop hook to execute.

**Comment by liggitt** [comment]
Namespace deletion does not bypass pod finalizers, it issues normal pod deletions, then waits for the pods to terminate and be deleted by the kubelet normally

**Comment by liggitt** [comment]
> also K8s might clean up resources like Pods, bypassing some of the usual deletion procedures, including triggering the preStop hook.

That is not accurate, namespace deletion triggers normal deletion of pods.

**Comment by liggitt** [comment]
What is more likely is that namespace deletion also deletes all objects in the namespace, including the service account and rbac role bindings, which can result in service account credentials for the pod being invalidated or forbidden if they attempt to be used to make API requests

**Comment by mochizuki875** [comment]
Hi, I've tried to reproduce it.
The preStop hook seems to have been triggered correctly.

1. Create test namespace.

```bash
$ kubectl create ns test
```

2. Prepare the pod manifest including preStop.

`test-pod.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test
  labels:
    app: test-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "echo 'Pod is terminating' > /host-tmp/output"]
    volumeMounts:
    - mountPath: /host-tmp
      name: host-tmp
  volumes:
  - name: host-tmp
    hostPath:
      path: /tmp
```

3. Create the test-pod.

```bash
$ kubectl apply -f test-pod.yaml 

$ kubectl get pod -n test
NAME       READY   STATUS    RESTARTS   AGE
test-pod   1/1     Running   0          14s
```

4. Delete test namespace.
```bash
$ kubectl delete ns test
namespace "test" deleted
```

5. Check `/tmp` of Node where pod's preStop command will output a file.

```bash
# cat /tmp/output
Pod is terminating
```
