### ISSUE TITLE
Setting revisionHistoryLimit field in statefulset.spec to negative value causes a panic in controller manager

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes/kubernetes#129018]
### What happened?

Applying this yaml causes a panic in controller manager

<details>
<summary>example statefulset</summary>

```yaml
$ cat test_statefulset.yaml 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-statefulset
  namespace: default
spec:
  revisionHistoryLimit: -1
  serviceName: "example-service"
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-container
        image: nginx:1.21
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: example-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

```
</details>

Please see the value in `revisionHistoryLimit`

### What did you expect to happen?

No panic occurs and API server simply rejects to apply this invalid yaml.

### How can we reproduce it (as minimally and precisely as possible)?

Apply the resource give above.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

</details>

### Cloud provider

<details>
Cloud agnostic
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
