### ISSUE TITLE
add `matchLabelKeys: ["pod-template-hash"]` in the default `ScheduleAnyway` topology spread

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#129198]
We recently added `matchLabelKeys` feature at [pod topology spread](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/).

Pod topology spread has the [Cluster-level default constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#cluster-level-default-constraints);

```yaml
defaultConstraints:
  - maxSkew: 3
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: ScheduleAnyway
  - maxSkew: 5
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: ScheduleAnyway
```

I was wondering, when it comes to the pods owned by a replicaset controller, would it make sense to consider `matchLabelKeys: ["pod-template-hash"]` there? (I guess such change in the default behavior is allowed, am I right?)

/cc @kubernetes/sig-scheduling-misc @macsko @dom4ha 
/sig scheduling
/kind feature
