### ISSUE TITLE
RBAC `cluster/rolebinding` created without subjects and `SA` namespace check

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#129265]
### What happened?

When creating RBAC `rolebinding` and `clusterrolebinding` with subjects `ServiceAccount`, there is no subjects empty check and namespace empty check.

### What did you expect to happen?

Shoud check both subjects empty and namespace empty.

### How can we reproduce it (as minimally and precisely as possible)?

rolebinding-test.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-test
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-test
#subjects: # subjects is required
#- kind: ServiceAccount
#  name: sa-test
#  namespace: default # namespace is required
```

clusterrolebinding-test.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role-test
#subjects: # subjects is required
#- kind: ServiceAccount
#  name: sa-test
#  namespace: default # namespace is required
```

`kubectl apply -f xxx.yaml` will reproduce this issue.

### Anything else we need to know?
Issue tested in 1.31.

### Kubernetes version
1.31
