### ISSUE TITLE
RBAC `cluster/rolebinding` created without `roleRef` and `SA` existence check

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#129268]
### What happened?

When creating RBAC `rolebinding` and `clusterrolebinding` with subjects `ServiceAccount`, there is no `roleRef` (`Role/ClusterRole`) and `SA` existence check.

### What did you expect to happen?

Shoud check both `roleRef` (`Role/ClusterRole`) and `SA` existence.

### How can we reproduce it (as minimally and precisely as possible)?

rolebinding-test.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-test
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-not-exist # should check Role existence
subjects:
- kind: ServiceAccount
  name: sa-not-exist # should check SA existence
  namespace: default
```

clusterrolebinding-test.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role-not-exist # should check ClusterRole existence
subjects:
- kind: ServiceAccount
  name: sa-not-exist # should check SA existence
  namespace: default
```

`kubectl apply -f xxx.yaml` will reproduce this issue.

### Anything else we need to know?

Issue tested in 1.31.

### Kubernetes version

1.31

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
