### ISSUE TITLE
Make kube-proxy ipset parameters 'hashSize' and 'maxElem' customizable

### ISSUE THREAD

**Issue by weak-fox** [kubernetes/kubernetes#129389]
### What would you like to be added?

Allow users to configure ipset parameters 'hashSize' and 'maxElem' in kube-proxy configuration. These parameters should be customizable via the kube-proxy config file or command line flags.

### Why is this needed?

In our use case, we have multiple LAN devices that need to interact with services in the cluster via RTP media streams. Each service can have thousands of ports, and we assign an external IP for each LAN to access these services. This results in the required ipset size reaching "ports num" * "external IP num," which can exceed the default limit of 65536.When the ipset size reaches its limit, any new services added will not take effect.

By making these parameters configurable, users can adjust the size based on their specific needs, providing greater flexibility and adaptability. Additionally, when modifying `maxElem`, users should also consider adjusting `hashSize` to achieve optimal performance, allowing them to balance memory usage according to their current scenario.

This feature will enhance kube-proxy's scalability and performance in diverse environments.

There are also many users like us who need to expose a large number of ports：
https://github.com/kubernetes/kubernetes/issues/23864
https://github.com/kubernetes/kubernetes/issues/23864#issuecomment-373937794

**Comment by weak-fox** [comment]
@kubernetes/sig-network-feature-requests

**Comment by aroradaman** [comment]
The request seems reasonable
/triage accepted

**Comment by uablrek** [comment]
> 65536.When the ipset size reaches its limit, any new services added will not take effect.

What does "new services" mean here? Does overstepping the limit for one service prevent new ones?

I tried to recreate the problem with a *very big* service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: big-svc
spec:
  selector:
    app: tserver
  ports:
  - port: 5000
    name: p5000
  - port: 5001
    name: p5001
# ... 10000 ports goes here
  externalIPs:
  - 10.0.0.0
  - 10.0.0.1
# ... a number of ip's goes here
```
If I add 6 externalIPs it works (sort of), but if I make that 7, this shows up in the kube-proxy logs:

```
 > ipSetEntry="10.0.0.6,tcp:6656" ipSet="KUBE-EXTERNAL-IP"
E1228 09:05:11.483159     427 ipset.go:180] "Failed to add ip set entry to ip set" err=<
        error adding entry 10.0.0.0,tcp:10966, error: exit status 1 (ipset v6.38: Hash is full, cannot add more elements
```
