### ISSUE TITLE
bug(dra): when deleting resourceclaimtemplate, pod can't running again

### ISSUE THREAD

**Issue by googs1025** [kubernetes/kubernetes#129362]
### What happened?

```yaml
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart# kubectl apply -f gpu-test2-dep.yaml
namespace/gpu-test2 created
resourceclaimtemplate.resource.k8s.io/single-gpu created
deployment.apps/gpu-deployment created
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart# kubectl get all -ngpu-test2
NAME                                  READY   STATUS    RESTARTS   AGE
pod/gpu-deployment-6965899554-zmq5j   2/2     Running   0          16s

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/gpu-deployment   1/1     1            1           16s

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/gpu-deployment-6965899554   1         1         1       16s
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart# kubectl get resourceclaimtemplates -ngpu-test2
NAME         AGE
single-gpu   47s
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart#
```
1. delete resourceclaimtemplates
2. delete pod
```yaml
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart# kubectl get resourceclaimtemplates -ngpu-test2
NAME         AGE
single-gpu   2m33s
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart# kubectl delete resourceclaimtemplates single-gpu -ngpu-test2
resourceclaimtemplate.resource.k8s.io "single-gpu" deleted
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart# kubectl get pods -ngpu-test2
NAME                              READY   STATUS    RESTARTS   AGE
gpu-deployment-6965899554-zmq5j   2/2     Running   0          2m50s
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart# kubectl delete pods gpu-deployment-6965899554-zmq5j -ngpu-test2
pod "gpu-deployment-6965899554-zmq5j" deleted
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart# kubectl get pods -ngpu-test2
NAME                              READY   STATUS    RESTARTS   AGE
gpu-deployment-6965899554-wl2dj   0/2     Pending   0          3s
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart#
```
pod is always Pending
```yaml
root@VM-0-6-ubuntu:/home/ubuntu/k8s-dra-driver/demo/specs/quickstart# kubectl describe pods gpu-deployment-6965899554-wl2dj -ngpu-test2
Name:             gpu-deployment-6965899554-wl2dj
Namespace:        gpu-test2
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app=gpu-app
                  pod-template-hash=6965899554
Annotations:      <none>
Status:           Pending
IP:
IPs:              <none>
Controlled By:    ReplicaSet/gpu-deployment-6965899554
Containers:
  ctr0:
    Image:      ubuntu:22.04
    Port:       <none>
    Host Port:  <none>
    Command:
      bash
      -c
    Args:
      nvidia-smi -L; trap 'exit 0' TERM; sleep 9999 & wait
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-m26j7 (ro)
  ctr1:
    Image:      ubuntu:22.04
    Port:       <none>
    Host Port:  <none>
    Command:
      bash
      -c
    Args:
      nvidia-smi -L; trap 'exit 0' TERM; sleep 9999 & wait
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-m26j7 (ro)
Volumes:
  kube-api-access-m26j7:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              nvidia.com/gpu.present=true
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                             nvidia.com/gpu:NoSchedule op=Exists
Events:
  Type     Reason                       Age                 From            Message
  ----     ------                       ----                ----            -------
  Warning  FailedResourceClaimCreation  11s (x13 over 31s)  resource_claim  PodResourceClaim shared-gpu: resource claim template "single-gpu": resourceclaimtemplate.resource.k8s.io "single-gpu" not found
```

### What did you expect to happen?

When resourceclaimtemplate is deleted, the pod can still run successfully after restart. Or resourceclaimtemplate cannot be deleted when it is in use.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-test2

---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  namespace: gpu-test2
  name: single-gpu
spec:
  spec:
    devices:
      requests:
      - name: gpu
        deviceClassName: gpu.nvidia.com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gpu-test2
  name: gpu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-app
  template:
    metadata:
      labels:
        app: gpu-app
    spec:
      containers:
      - name: ctr0
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; trap 'exit 0' TERM; sleep 9999 & wait"]
        resources:
          claims:
          - name: shared-gpu
      - name: ctr1
        image: ubuntu:22.04
        command: ["bash", "-c"]
        args: ["nvidia-smi -L; trap 'exit 0' TERM; sleep 9999 & wait"]
        resources:
          claims:
          - name: shared-gpu
      resourceClaims:
      - name: shared-gpu
        resourceClaimTemplateName: single-gpu
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        nvidia.com/gpu.present: "true"
      restartPolicy: Always
```
use this sample yaml, and delete pod.

### Anything else we need to know?

I'm not sure if this is by design. But according to common sense, there is a possibility that resourceclaimtemplate was accidentally deleted. If the training task is restarted, the above problem may occur. 🤔 

### Kubernetes version

```console
root@VM-0-6-ubuntu:/home/ubuntu# kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.32.0
```

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
