### ISSUE TITLE
`kubectl describe pod` probe host is empty

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#129320]
### What happened?

Using `kubectl describe po xxx` to show pod probe info, when the probe host is empty, there is no default value showed in the output, like below, so this PR add the default value.
```
    State:          Running
      Started:      Thu, 19 Dec 2024 15:25:42 +0800
    Ready:          False
    Restart Count:  0
    ...
    Liveness:       http-get http://:8080/healthz delay=0s timeout=5s period=10s #success=1 #failure=3
```

### What did you expect to happen?

When the host not set, add the default value `localhost`.
```
    Liveness:       http-get http://:8080/healthz delay=0s timeout=5s period=10s #success=1 #failure=3
    ======== to below
    Liveness:       http-get http://localhost:8080/healthz delay=0s timeout=5s period=10s #success=1 #failure=3
```

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          timeoutSeconds: 5

```
`kubectl apply -f xxx.yaml && kubectl describe po xxx` will reproduce this issue.

### Anything else we need to know?

Issue tested in 1.31.

### Kubernetes version

1.31
