### ISSUE TITLE
DRA: Using All allocation mode will schedule to nodes with zero devices

### ISSUE THREAD

**Issue by johnbelamaric** [kubernetes/kubernetes#129310]
### What happened?

I created a resource claim template to get "All" GPUs on a node:

```yaml
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: all-gpus
spec:
  spec:
    devices:
      requests:
      - name: gpu
        deviceClassName: gpu.nvidia.com
        allocationMode: All
```

I then created a deployment that had a Pod that used that claim. The Pod was scheduled to a node. However, my DRA driver on that node was not running, so there were no resource slices for that node.

### What did you expect to happen?

I expected the pod to not schedule, since there were no available devices meeting the request. "All" should mean "at least one".

### How can we reproduce it (as minimally and precisely as possible)?

Create the resource claim template as shown and a deployment, with no DRA driver running. The pod will still schedule.

### Anything else we need to know?

/wg device-management

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.32.0-gke.1358000
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux rodete"
NAME="Debian GNU/Linux rodete"
VERSION_CODENAME=rodete
ID=debian
HOME_URL="https://go/glinux"
SUPPORT_URL="https://go/techstop"
BUG_REPORT_URL="https://go/techstop"
$ uname -a
Linux jbelamaric.c.googlers.com 6.10.11-1rodete2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.11-1rodete2 (2024-10-16) x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
