### ISSUE TITLE
Why do we need to remove the status field when creating a CR resource

### ISSUE THREAD

**Issue by Chaunceyctx** [kubernetes/kubernetes#129451]
### What happened?

1. create crd
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.4
  name: testcrds.foo.test.com
spec:
  group: foo.test.com
  names:
    kind: TestCRD
    listKind: TestCRDList
    plural: testcrds
    singular: testcrd
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TestCRD is the Schema for the testcrds API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: TestCRDSpec defines the desired state of TestCRD.
            properties:
              powerSpec:
                default: "off"
                description: Foo is an example field of TestCRD. Edit testcrd_types.go
                  to remove/update
                type: string
            type: object
          status:
            description: TestCRDStatus defines the observed state of TestCRD.
            properties:
              powerStatus:
                default: "off"
                description: |-
                  INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
                  Important: Run "make" to regenerate code after modifying this file
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```
2. create cr
```yaml
apiVersion: foo.test.com/v1alpha1
kind: TestCRD
metadata:
  name: test
  namespace: default
spec: {}
status: {}
```
3.  get specific cr
```shell
[root@test ~]# kubectl get testcrds.foo.test.com  -oyaml
apiVersion: v1
items:
- apiVersion: foo.test.com/v1alpha1
  kind: TestCRD
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"foo.test.com/v1alpha1","kind":"TestCRD","metadata":{"annotations":{},"name":"test","namespace":"default"},"spec":{},"status":{}}
    creationTimestamp: "2025-01-02T09:16:07Z"
    generation: 1
    name: test
    namespace: default
    resourceVersion: "25480250"
    uid: e7dd695d-cd27-4c0a-8859-4e1d45ec718a
  spec:
    powerSpec: "off"
kind: List
metadata:
  resourceVersion: ""
```
status field content lost

same issue:
https://discuss.kubernetes.io/t/how-to-set-default-status-of-crd-customresourcedefinition/18133

/sig apimachinery

### What did you expect to happen?

set default value for `status` field in cr

### How can we reproduce it (as minimally and precisely as possible)?

just like https://discuss.kubernetes.io/t/how-to-set-default-status-of-crd-customresourcedefinition/18133:
1. create crd
2. create cr
3. `status` field content lost in cr

### Kubernetes version

all k8s versions

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
