### ISSUE TITLE
env variables are not expanded in pod lifecycle hooks

### ISSUE THREAD

**Issue by tdihp** [kubernetes/kubernetes#129502]
### What happened?

Hi,

variable expansion ( the `$(var_name)` expansion) seem to work to specific places, it is a surprise for me when I use exec trace to find that it didn't work in `spec.containers[].lifecycle.preStop.exec.command` of pod.

### What did you expect to happen?

Either explicit documentation on where variable expansion happens, or explicit mention that the lifecycle hooks doesn't honor it.

Preferably it can render the template, though.

/sig node

### How can we reproduce it (as minimally and precisely as possible)?

Simplly have a env "foo"="bar" in container, then have a lifecycle hook with exec configured that includes `$(foo)`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.2
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by AnishShah** [comment]
can you provide steps to reproduce this? I tried this and it works:

```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx:latest
    env:
    - name: foo
      value: bar
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - 'if [ -z "$foo" ]; then exit 1; fi'
```
