### ISSUE TITLE
Support spec.MaxUnavailable=0  to use PDB with Jobs and prevent disruptions during node upgrades

### ISSUE THREAD

**Issue by snavarron** [kubernetes/kubernetes#129625]
### What would you like to be added?

Add support to the `spec.MaxUnavailable` setting when set to 0 (zero) for PDBs used in combination with jobs. 

### **Context**
Currently, the [documentation](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors) states that `spec.MaxUnavailable` should not be used for resources that do not support the scale subresource, and when deployed,  the PDB shows this warning:  

> Warning  CalculateExpectedPodCountFailed  75s  controllermanager  Failed to calculate the number of expected pods: jobs.batch does not implement the scale subresource

However, by setting `spec.MaxUnavailable=0` in the PDB and use it in combination with a selector label to point the PDB to the Scaled Jobs, our testing has confirmed that it effectively prevents disruptions of Keda Scaled Jobs during node upgrades. 

**The reasoning is that when `spec.MaxUnavailable` is set to 0, there is not need to know the number of Pods running at a given moment.** 

Behavior observed during testing:

1. Node is cordoned 
2. Kubernetes attempts to evict pods running a job, and eviction is prevented by the PDB.
3. Kubernetes keeps attempting to evict the pods.
4. Jobs finish execution.
5. Kubernetes evicts the pods.
6. The upgrade can proceed.

**Example PDB Used** 
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agent-scaledjob-pdb
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: agent-scaledjobs
```
 The selector label is also included in the ScaledJob
```
..
spec:
  jobTargetRef:
    activeDeadlineSeconds: 1500
    template:
      metadata:
        name: agent-scaledjob
        labels:
          app: agent-scaledjobs
..
```

### Why is this needed?

To avoid disruptions of jobs during node image or Kubernetes upgrades
