### ISSUE TITLE
kubectl proxy hangs in minion pod

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/kubernetes#12976]
I'm trying to set up kube-ui in a minion pod, and using an external LB to direct traffic to it. Obviously it needs to access the API server, so I've added a `kubectl` container to the pod so it can run as a proxy. Here's the definition in the RC file:

```yaml
- name: kubectl
  image: gcr.io/google_containers/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty
  args: [proxy, -p, "8001", -s, "http://10.1.0.1"]
```

There's also a generic WordPress container that gets set up too. When the pod is fully active, I `docker exec` into the WordPress container and execute:

```bash
curl localhost:8001/api/
```

which I _assume_ should be hitting the `kubectl proxy` container in the same pod, which in turn directs traffic to the master API server. But it just hangs, and then eventually returns this error in the `kubectl` container:

> 2015/08/20 12:29:28 http: proxy error: dial tcp 10.1.0.1:80: i/o timeout

What do I need to do to allow the `kubectl` container in the minion pod to speak to the API server on master?
