### ISSUE TITLE
Unable to run cronjobs on kubernetes

### ISSUE THREAD

**Issue by oba11** [kubernetes/kubernetes#12970]
I'm having an issue whereby cronjob in kubernetes doesnt seem to work.

Below is the test dockerfile used

```
FROM debian:jessie

RUN apt-get update
RUN apt-get -y install --no-install-recommends cron

RUN echo 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' | crontab

RUN echo '0-59/2 * * * 0-4 export ENV=dev RECIPIENT=email@example.com; echo "$(date) ${ENV} ${RECIPIENT}" >> /var/log/cron.log' | crontab

CMD ["cron", "-f", "-L", "15"]
```

Using native docker to run the above dockerfile, I could see the output in the logfile but not in kubernetes. Checked the events but didn't notice anything unusual.

Below is the replicationcontroller yaml file used

```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cron-test
  name: cron-test
spec:
  replicas: 1
  selector:
    name: cron-test
  template:
    metadata:
      labels:
        name: cron-test
    spec:
      containers:
        - name: cron-test
          image: example/cron-test:latest
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
          imagePullPolicy: Always
```

Thanks.
