### ISSUE TITLE
ValidatingAdmissionPolicy still applied to Terminating Namespaces

### ISSUE THREAD

**Issue by felipe88alves** [kubernetes/kubernetes#129883]
### What happened?

I'm implementing policies using ValidatingAdmissionPolicy and ValidatingAdmissionPolicyBindings using a custom CR as paramKind.

The binding is configured with `.spec.paramRef.parameterNotFoundAction: Deny`

Some of those policies are associated to external resources that may take a bit longer to terminate.

When a namespace is deleted, the custom CR resource is immediately removed, and the policy's target resource is left hanging.

Attempting to remove the resource's finalizer returns a ValidatingAdmissionPolicy error:
```
The persistentvolumeclaims "xxx-pvc" is invalid: : ValidatingAdmissionPolicy 'xxx-vap' with binding 'xxx-vapbind' denied request: failed to configure binding: no params found for policy binding with `Deny` parameterNotFoundAction
```

### What did you expect to happen?

The resources in the namespace to be deleted along with the namespace

Perhaps the policy should stop acting on the namespace if it is in Terminating state.

### How can we reproduce it (as minimally and precisely as possible)?

Create Kind cluster with extraMount
```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: <some-path>/foo
        containerPath: /foo
```

Create test namespace
```
> kubectl create ns test
```

Deploy ValidatingAdmissionPolicy, ValidatingAdmissionPolicyBinding and ConfigMap parameter reference
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: policy
spec:
  paramKind:
    apiVersion: v1
    kind: ConfigMap
  matchConstraints:
    resourceRules:
      - apiVersions:
          - v1
        apiGroups:
          - ""
        resources:
          - persistentvolumeclaims
        operations:
          - CREATE
          - UPDATE
  validations:
    - expression: params != null && has(params.data) && has(params.data.storageClasses) && variables.storageClassName == params.data.storageClasses
      messageExpression: '"Namespace " + string(namespaceObject.metadata.name) + " does not have permissions to storageClassName " + variables.storageClassName'
  failurePolicy: Fail
  variables:
    - name: storageClassName
      expression: '"storageClassName" in object.spec ? object.spec.storageClassName : "empty"'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: binding
spec:
  policyName: policy
  paramRef:
    name: ref
    parameterNotFoundAction: Deny
  validationActions:
    - Deny
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ref
data:
  storageClasses: "standard"
```

Create the PVC
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-www
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /foo/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-www
spec:
  volumeName: pv-www
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: pvc-www
      containers:
      - name: nginx
        image: nginx:1.14.2
        volumeMounts:
        - name: www
          mountPath: /var/www
```

Delete the namespace:
```
> kubectl delete ns test
```

The namespace will hang due to the PVC, attempting to remove the PVC finalizer will reveal the ValidatingAdmissionPolicy error:
```
> kubectl patch pvc pvc-www -p '{"metadata":{"finalizers":[]}}' --type=merge
The persistentvolumeclaims "pvc-www" is invalid: : ValidatingAdmissionPolicy 'policy' with binding 'binding' denied request: failed to configure binding: no params found for policy binding with `Deny` parameterNotFoundAction
```

The PVC is removed (or finalizer can be removed) after configuring the binding with `.spec.paramRef.parameterNotFoundAction: Allow` or removing the ValidatingAdmissionPolicy.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.32.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
