### ISSUE TITLE
`AuthenticationConfig` kind cannot be found

### ISSUE THREAD

**Issue by emilianomaccaferri** [kubernetes/kubernetes#129958]
### What happened?

Hello there,
I was trying to implement OIDC authentication using the authentication configuration following the [official documentation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#using-authentication-configuration).
I have a very simple configuration:
```yaml
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration

jwt:
- issuer:
    url: https://my.keycloak.endpoint.com
    # discoveryURL: 
    audiences:
    - kubernetes
    audienceMatchPolicy: MatchAny
  #claimValidationRules:
  claimMappings:
    username:
      claim: "sub"
```

If I try to submit this resource via `kubectl apply` I get the following error:
```
error: resource mapping not found for name: "" namespace: "" from "oidc.yaml": no matches for kind "AuthenticationConfiguration" in version "apiserver.config.k8s.io/v1beta1"
ensure CRDs are installed first
```
I also tried to feed the configuration via the command line parameter in the `/etc/kubernetes/manifests/kube-apiserver.yaml`:
```yaml
apiVersion: v1
kind: Pod
# more stuff...
spec:
  containers:
  - command:
    - kube-apiserver
    - --feature-gates=StructuredAuthenticationConfiguration=true # i also forced the feature gate
    # other default parameters...
    - --authentication-config=/path/to/config.yaml
# more stuff ...
```
but I always get the same error (the file is loaded correctly).

I also tried changing the `apiVersion` field to `apiserver.k8s.io/v1beta1`, but still no luck.

### What did you expect to happen?

I expected a successful `AuthenticationConfig` resource creation.

### How can we reproduce it (as minimally and precisely as possible)?

Using the following configuration:
```yaml
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration

jwt:
- issuer:
    url: https://my.keycloak.endpoint.com
    # discoveryURL: 
    audiences:
    - kubernetes
    audienceMatchPolicy: MatchAny
  #claimValidationRules:
  claimMappings:
    username:
      claim: "sub"
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.3
Kustomize Version: v5.4.2
Server Version: v1.32.0
```

</details>

### Cloud provider

<details>
Self hosted
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux K8S-cp1 6.1.0-29-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.123-1 (2025-01-02) x86_64 GNU/Linux
```

</details>

### Install tools

<details>
`kubeadm`
</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRIO 1.32.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
