### ISSUE TITLE
Enforce a pod to deploy on certain node machine

### ISSUE THREAD

**Issue by mattma** [kubernetes/kubernetes#12990]
I run a MongoDB database in `k8s` and need a persistent data solution. I followed with [persistent volumes guide](https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/persistent-volumes) to setup `rc` config. It works brilliant. 

Here is a taste of my `rc`

```
apiVersion: v1
kind: ReplicationController
metadata:
  ...
spec:
  replicas: 1
  selector:
  template:
    metadata:
      labels:
    spec:
      containers:
      - name: mongo
        image: mongodb
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-claim
```

I quickly run into the issue which describe in the guide. 

> IMPORTANT! For `HostPath` to work, you will need to run a single node cluster. Kubernetes does not support local storage on the host at this time. There is no guarantee your pod ends up on the correct node where the HostPath resides.

I tried to delete my pod, and a new pod is created. It could land in any `node` in the cluster. E.G: my `mongodb` presistent data storage is on `Node 1`, but the new pod may land in `node 3`, anything other than `Node 1`? It could not read the data off the `Node 1` in that case.

Is there a solution to enforce the `rc` backed `pod` will always land in `node 1`? for instance, in the `coreos fleet` senario, I could define a rule in Unit file like `[X-Fleet] MachineOf` to enforce certain `service` will only land in certain machine. Something similar in `k8s`? 

Or there is an alternative using `nfs` storage, or `nodes` in the cluster to access a common drive? any solutions on the way for this purpose?
