### ISSUE TITLE
Configmap envFrom no longer warns when invalid keys are skipped

### ISSUE THREAD

**Issue by daviddob** [kubernetes/kubernetes#130099]
### What happened?

As called out in the documentation section for Configmap envFrom restrictions (https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#restrictions) 

If you use envFrom to define environment variables from ConfigMaps, keys that are considered invalid will be skipped. The pod will be allowed to start, but the invalid names will be recorded in the event log (InvalidVariableNames). The log message lists each skipped key. For example:

```
kubectl get events
```
The output is similar to this:
```
LASTSEEN FIRSTSEEN COUNT NAME          KIND  SUBOBJECT  TYPE      REASON                            SOURCE                MESSAGE
0s       0s        1     dapi-test-pod Pod              Warning   InvalidEnvironmentVariableNames   {kubelet, 127.0.0.1}  
```

Using the configmap defined below, and mounting it via envfrom in the pod

```yaml
apiVersion: v1
data:
  app.invalid: "this should not be mounted, but should warn with InvalidEnvironmentVariableNames"
  app_valid: "this should show up as an env var"
kind: ConfigMap
metadata:
  creationTimestamp: "2025-02-11T19:35:58Z"
  name: config-file-env
  namespace: test
```

```yaml
envFrom:
    - configMapRef:
        name: config-file-env
```

The key `app.invalid` was not mounted in the container environment and **there was no event or warning generated in `kubectl get events`. This essentially means all `invalid` env vars are silently dropped without means of notification**

The key `app_valid` exists in the container environment as expected

### What did you expect to happen?

I expected:

The key `app.invalid` to not be mounted in the container environment and an event with reason InvalidEnvironmentVariableNames to show up in the events.

The key `app_valid` to exist in the container environment

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a configmap as above containing both a valid and invalid key
2. Mount it to a pod using envFrom in your deployment
3. Exec into the pod to validate with `env` to see the invalid env name is dropped
4. Check the events with `kubectl get events` and see that no warning was generated.

### Anything else we need to know?

It appears like this functionality was removed as part of https://github.com/kubernetes/kubernetes/pull/123385, which enables almost all printable characters in env vars, but seems to be a regression in that if the env vars are still silently dropped/invalid or the alpha feature is not enabled, there is no event/notification.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.5
```

</details>

### Cloud provider

<details>
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
