### ISSUE TITLE
Validate duplicate keys between matchLabelKeys and labelSelector in PodTemplateSpec

### ISSUE THREAD

**Issue by mochizuki875** [kubernetes/kubernetes#130063]
### Summary
When an attempt is made to create an object(e.g. `Deployment`) containing a `PodTemplateSpec` with a specific key that exists in both `PodAffinity`'s `matchLabelKeys` and `labelSelector`, the validation should fail.

### Details
If a specific key exists in both PodAffinity's `matchLabelKeys` and `labelSelector` in a Pod, validation will fail.

`sample-affinity.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sample-affinity
  labels:
    app: sample-affinity
    foo: bar
spec:
  containers:
  - image: nginx
    name: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - xxxxxxxxxxx
        topologyKey: kubernetes.io/hostname
        matchLabelKeys:
        - app
```

```console
$ k apply -f sample-affinity.yaml
The Pod "sample-affinity" is invalid: spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0][0]: Invalid value: "app": exists in both matchLabelKeys and labelSelector
```

On the other hand, if a specific key exists in both PodAffinity's `matchLabelKeys` and `labelSelector` in a `PodTemplateSpec`(e.g. `Deployment`), validation will pass.

`sample-deployment-affinity.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-deployment-affinity
  name: sample-deployment-affinity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-deployment-affinity
  template:
    metadata:
      labels:
        app: sample-deployment-affinity
    spec:
      containers:
      - image: nginx:1.23
        name: nginx
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - xxxxxxxxxxx
            topologyKey: topology.kubernetes.io/zone
            matchLabelKeys:
            - app
```

```console
$ k apply -f sample-deployment-affinity.yaml
deployment.apps/sample-deployment-affinity created
```

In this case, `Deployment` and `ReplicaSet` are created, but the `Pod`s are not created for the same reason as in the first `Pod` case.
```console
$ k get all
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   20d

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sample-deployment-affinity   0/3     0            0           14s

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/sample-deployment-affinity-6f64f565b9   3         0         0       14s

$ k describe replicaset sample-deployment-affinity-6f64f565b9
Name:           sample-deployment-affinity-6f64f565b9
...
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age               From                   Message
  ----     ------        ----              ----                   -------
  Warning  FailedCreate  28s               replicaset-controller  Error creating: Pod "sample-deployment-affinity-6f64f565b9-mgppk" is invalid: spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0][0]: Invalid value: "app": exists in both matchLabelKeys and labelSelector
  Warning  FailedCreate  28s               replicaset-controller  Error creating: Pod "sample-deployment-affinity-6f64f565b9-vhkgd" is invalid: spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0][0]: Invalid value: "app": exists in both matchLabelKeys and labelSelector
  Warning  FailedCreate  28s               replicaset-controller  Error creating: Pod "sample-deployment-affinity-6f64f565b9-5s6vj" is invalid: spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0][0]: Invalid value: "app": exists in both matchLabelKeys and labelSelector
  ...
```

I think that if an object containing such a `PodTemplateSpec` is attempted to be created, the validation should fail.

/sig scheduling
/kind feature
/cc @sanposhiho
