### ISSUE TITLE
Pods on the same Node cannot access each other

### ISSUE THREAD

**Issue by whc9527** [kubernetes/kubernetes#130234]
### What happened?

Both mysql and busybox Pods are deployed on node 172.21.8.183. The svc address of mysql pod is apollo-db. mysql pod can access mysql services through apollo-db. However, the busybox pod cannot access apollo-db. The domain name apollo-db can be resolved normally in busybox pod.

Is there a friend who can help me look at it? It is urgent to solve this problem at work. Thank you very much！！

![Image](https://github.com/user-attachments/assets/0b928839-f045-4a5a-abd7-3d46d53f31ea)

svc information：

![Image](https://github.com/user-attachments/assets/fba06e70-401d-4ce3-94c6-16a2dc9bf87e)

Log in to 172.21.8.183 and see some information:

![Image](https://github.com/user-attachments/assets/6dfab93c-54a6-4f14-ac54-ca233f4392b6)

![Image](https://github.com/user-attachments/assets/b0698822-71b5-4932-8bf1-d2c24164d2ad)

![Image](https://github.com/user-attachments/assets/a12648f8-ed3b-40ab-8049-8e1de2eb5caf)

![Image](https://github.com/user-attachments/assets/f3e0f112-4f10-4b8c-8153-28882b40bb55)

![Image](https://github.com/user-attachments/assets/b99096b8-abb4-4c4c-a510-584a2146c40c)

At first I thought it was the Hairpin Mode, but I found that hairpin_mode is set to 1 in all my VNets

![Image](https://github.com/user-attachments/assets/198da1f3-15fb-4991-8070-b0da1d9acb3e)

### What did you expect to happen?

Pods on the same Node can access each other

### How can we reproduce it (as minimally and precisely as possible)?

A Node starts a Mysql Pod, a busybox Pod, and telnet the svc address of mysql on the busybox Pod

### Kubernetes version

1.31.1

### Cloud provider
<details>
The node node is on Alibaba Cloud, and the master node is on aws. They are connected by a special line
</details>

### OS version
<details>

```
# On Linux:
$ cat /etc/os-release 
NAME="Alibaba Cloud Linux (Aliyun Linux)"
VERSION="2.1903 LTS (Hunting Beagle)"
ID="alinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.1903"
PRETTY_NAME="Alibaba Cloud Linux (Aliyun Linux) 2.1903 LTS (Hunting Beagle)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"
# paste output here
$ uname -a
# paste output here
Linux iZ0xi930e22iqpyhwaa27xZ 4.19.91-24.1.al7.x86_64 #1 SMP Wed Jul 21 17:40:23 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)
<details>

```
root@iZ0xi930e22iqpyhwaa27xZ:~ #containerd --version
containerd github.com/containerd/containerd v1.7.23 57f17b0a6295a39009d861b89e3b3b87b005ca27
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
kube-flannel.yml

```
---
kind: Namespace
apiVersion: v1
metadata:
  name: kube-flannel
  labels:
    k8s-app: flannel
    pod-security.kubernetes.io/enforce: privileged
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: flannel
  name: flannel
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: flannel
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-flannel
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: flannel
  name: flannel
  namespace: kube-flannel
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-flannel
  labels:
    tier: node
    k8s-app: flannel
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "192.168.0.0/17",
      "EnableNFTables": false,
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-flannel
  labels:
    tier: node
    app: flannel
    k8s-app: flannel
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: flannel
      initContainers:
      - name: install-cni-plugin
        image: docker.io/flannel/flannel-cni-plugin:v1.5.1-flannel2
        command:
        - cp
        args:
        - -f
        - /flannel
        - /opt/cni/bin/flannel
        volumeMounts:
        - name: cni-plugin
          mountPath: /opt/cni/bin
      - name: install-cni
        image: docker.io/flannel/flannel:v0.25.7
        command:
        - cp
        args:
        - -f
        - /etc/kube-flannel/cni-conf.json
        - /etc/cni/net.d/10-flannel.conflist
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      containers:
      - name: kube-flannel
        image: docker.io/flannel/flannel:v0.25.7
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENT_QUEUE_DEPTH
          value: "5000"
        volumeMounts:
        - name: run
          mountPath: /run/flannel
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
        - name: xtables-lock
          mountPath: /run/xtables.lock
      volumes:
      - name: run
        hostPath:
          path: /run/flannel
      - name: cni-plugin
        hostPath:
          path: /opt/cni/bin
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: flannel-cfg
        configMap:
          name: kube-flannel-cfg
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
```
</details>
