### ISSUE TITLE
Ephemeral Storage with emptyDir – Data Still Written to Disk not ephemeral storage

### ISSUE THREAD

**Issue by isaac-rnd** [kubernetes/kubernetes#130385]
I’ve observed that even when specifying ephemeral storage resource requests/limits and using an emptyDir volume in our Pod, data ends up being written to disk rather than ephemeral space.
ref :- https://kubernetes.io/docs/concepts/storage/volumes/#emptydir 

![Image](https://github.com/user-attachments/assets/585361d9-f6f3-4500-892c-7bf782dd2f38)
 
In my case, the Pod’s configuration uses an emptyDir (without specifying the medium), and when checking the mount point (e.g. via `mount | grep /rocksdb-state`), it shows the volume is backed by /dev/root (an ext4 disk).

![Image](https://github.com/user-attachments/assets/909fab01-ab43-4309-bcfa-c51d329c31d9)
 

Steps to Reproduce:-
1) Create a Pod with a configuration for examplesimilar :
```
  containers:
  - name: test-container
    image: ubuntu
    volumeMounts:
    - name: rocksdb-storage
      mountPath: /rocksdb-state
    resources:
      requests:
        ephemeral-storage: "30Gi"
      limits:
        ephemeral-storage: "40Gi"
  volumes:
  - name: rocksdb-storage
    emptyDir: {}
```
2) Deploy the Pod and exec into it.
3) Verify that data is being written to /rocksdb-state and inspect the mount using:
mount | grep "/rocksdb-state"

Expected Behavior:
as i understood from the documentation that emptyDir volumes by default use the node’s disk unless explicitly configured to use memory. However, since we’re specifying **ephemeral-storage requests/limits**, 
I expected or at least hoped that it might write into the ephemeral storage.

Actual Behavior:
so without setting medium: "Memory", the emptyDir volume is disk-backed even though it’s intended for ephemeral storage. 
this leads to some confusion regarding how ephemeral-storage requests and the emptyDir volume interact.

Any insight, suggestions, or corrections on this behavior would be appreciated. Thanks in advance for your help!

**Comment by niranjandarshann** [comment]
@isaac-rnd What i think is Ephemeral-storage limits apply to the container’s writable layer and logs, but not to emptyDir volumes.

**Comment by niranjandarshann** [comment]
If you want ephemeral storage in memory, you must explicitly set medium: "Memory" in your volume configuration.
 like this 
```
 volumes:
  - name: rocksdb-storage
    emptyDir:
      medium: "Memory"


```

then check the result. I think it may work.
