### ISSUE TITLE
Support basic arithmetic operations for environment variable value

### ISSUE THREAD

**Issue by quaff** [kubernetes/kubernetes#130435]
### What would you like to be added?

K8s already support to derive environment variable from existing one by [`$()`](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/), currently it supports string substitution only, it's not enough if derived environment variable need some arithmetic operations.

For example:
```yaml
env:
  - name: POD_INDEX
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
  - name: WORKER_ID
    value: "$(POD_INDEX+100)" # similar to $((POD_INDEX+100)) in shell
```

I expect `WORKER_ID` is `103` if the pod index is `3`, currently there is no way to archive.

### Why is this needed?

We could define environment variables more flexible.

**Comment by BenTheElder** [comment]
Why not do this in a shell script in your image?

I don't think we should attempt to partially implement sh.

**Comment by quaff** [comment]
> Why not do this in a shell script in your image?
> 
> I don't think we should attempt to partially implement sh.

The image is not under my control, I tried `lifecycle.postStart` it doesn't work.
```yaml
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "export WORKER_GROUP=$((POD_INDEX%3))"]
```
Is there any other workaround?
