### ISSUE TITLE
Service account token refresh failure in pods with pvcs in terminating state

### ISSUE THREAD

**Issue by parkjeongryul** [kubernetes/kubernetes#130442]
### What happened?

When a PersistentVolumeClaim (PVC) enters the Terminating state due to a deletion request, any pod mounting this PVC experiences a failure in ServiceAccount token refresh operations. This prevents the pod from receiving updated tokens once the current token expires.

### What did you expect to happen?

Token should be refreshed because pod is running.

### How can we reproduce it (as minimally and precisely as possible)?

1. Set up latest kubernetes cluster (i used [kind](https://kind.sigs.k8s.io/docs/user/quick-start/))
```
$ k get nodes
NAME                 STATUS   ROLES           AGE     VERSION
kind-control-plane   Ready    control-plane   5h29m   v1.32.2
```

2. Create pod mounting pvc with SA token
```
# token-test.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-token-sa
  namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: token-client
spec:
  serviceAccountName: simple-token-sa
  containers:
  - name: client
    image: curlimages/curl:latest
    command:
      - sleep
      - infinite
    volumeMounts:
    - name: token-volume
      mountPath: /var/run/secrets/tokens
    - name: data-volume
      mountPath: /data
  volumes:
  - name: token-volume
    projected:
      sources:
      - serviceAccountToken:
          path: custom-token
          expirationSeconds: 600
          audience: my-custom-audience
  - name: data-volume
    persistentVolumeClaim:
      claimName: client-data-pvc
```
```
$ k apply -f  token-test.yaml
```

3. Request pvc deletion and the pvc enters terminating state because a pod is still mounting it.
```
$ k delete pvc client-data-pvc 
persistentvolumeclaim "client-data-pvc" deleted
```

4. Check if the token refreshes correctly before reaching its expiration time.
```
# monitor-token.sh
#!/bin/bash

# Colors for output formatting
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}Token Renewal Monitoring Script${NC}"
echo -e "${CYAN}------------------------------${NC}"
echo -e "Checking for token updates every 30 seconds...\n"

# Initialize variables to track changes
previous_exp=""
first_run=true

while true; do
  # Get the current timestamp for logging
  current_time=$(date "+%Y-%m-%d %H:%M:%S")
  
  # Execute the command to get the token payload
  token_payload=$(kubectl exec -it token-client -- sh -c 'TOKEN=$(cat /var/run/secrets/tokens/custom-token); echo $TOKEN | cut -d. -f2 | base64 -d' 2>/dev/null)
  
  # Check if command was successful
  if [ $? -ne 0 ]; then
    echo -e "${YELLOW}[${current_time}] Error: Could not retrieve token. Check if the pod is running.${NC}"
    sleep 30
    continue
  fi
  
  # Extract expiration time
  exp_value=$(echo $token_payload | grep -o '"exp":[0-9]*' | cut -d':' -f2)
  
  # Format expiration time as human-readable
  exp_human=$(date -d "@$exp_value" "+%Y-%m-%d %H:%M:%S")
  
  # Calculate time until expiration
  now_seconds=$(date +%s)
  seconds_remaining=$((exp_value - now_seconds))
  minutes_remaining=$((seconds_remaining / 60))
  seconds_remainder=$((seconds_remaining % 60))
  
  # If first run, just display the token info
  if $first_run; then
    echo -e "${CYAN}[${current_time}] Initial token detected${NC}"
    echo -e "Token audience: $(echo $token_payload | grep -o '"aud":\[[^]]*\]' | sed 's/"aud":\["\(.*\)"\]/\1/')"
    echo -e "Service account: $(echo $token_payload | grep -o '"sub":"[^"]*"' | sed 's/"sub":"\(.*\)"/\1/')"
    echo -e "Expires at: ${exp_human} (in ${minutes_remaining}m ${seconds_remainder}s)"
    echo -e "JWT ID: $(echo $token_payload | grep -o '"jti":"[^"]*"' | sed 's/"jti":"\(.*\)"/\1/')"
    echo -e "${CYAN}------------------------------${NC}\n"
    previous_exp=$exp_value
    first_run=false
  else
    # Check if token has been renewed (expiration time changed)
    if [ "$previous_exp" != "$exp_value" ]; then
      echo -e "${GREEN}[${current_time}] Token renewed!${NC}"
      echo -e "New expiration: ${exp_human} (in ${minutes_remaining}m ${seconds_remainder}s)"
      echo -e "New JWT ID: $(echo $token_payload | grep -o '"jti":"[^"]*"' | sed 's/"jti":"\(.*\)"/\1/')"
      echo -e "${CYAN}------------------------------${NC}\n"
      previous_exp=$exp_value
    else
      echo -e "[${current_time}] Token unchanged. Expires in ${minutes_remaining}m ${seconds_remainder}s"
    fi
  fi
  
  # Wait for 30 seconds before checking again
  sleep 30
done
```

```
$ ./monitor-token.sh
Token Renewal Monitoring Script
------------------------------
Checking for token updates every 30 seconds...

[2025-02-26 19:12:46] Initial token detected
Token audience: my-custom-audience
Service account: system:serviceaccount:default:simple-token-sa
Expires at: 2025-02-26 19:15:13 (in 2m 27s)
JWT ID: cd509fb4-f1ab-4275-91c9-1f6a72e1860a
------------------------------

[2025-02-26 19:13:16] Token unchanged. Expires in 1m 57s
[2025-02-26 19:13:46] Token unchanged. Expires in 1m 27s
[2025-02-26 19:14:16] Token unchanged. Expires in 0m 57s
[2025-02-26 19:14:46] Token unchanged. Expires in 0m 27s
[2025-02-26 19:15:16] Token unchanged. Expires in 0m -4s
[2025-02-26 19:15:47] Token unchanged. Expires in 0m -34s
[2025-02-26 19:16:17] Token unchanged. Expires in -1m -4s
[2025-02-26 19:16:47] Token unchanged. Expires in -1m -34s
[2025-02-26 19:17:17] Token unchanged. Expires in -2m -4s
[2025-02-26 19:17:47] Token unchanged. Expires in -2m -34s
[2025-02-26 19:18:17] Token unchanged. Expires in -3m -4s
[2025-02-26 19:18:47] Token unchanged. Expires in -3m -35s
[2025-02-26 19:19:18] Token unchanged. Expires in -4m -5s
```

### Anything else we need to know?

The bug presents a critical failure scenario for environments running service meshes such as Linkerd and Istio.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

```
$ k version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.2
```

### Cloud provider

<details>

</details>

kind

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux k8stest 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

kind

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
