### ISSUE TITLE
add more info when pod PreStop and PostStart Hook failed

### ISSUE THREAD

**Issue by googs1025** [kubernetes/kubernetes#130438]
### What would you like to be added?

- add more info when pod PreStop and PostStart Hook failed

### Why is this needed?

When I use the postStart or preStop Hook, I find that the event does not have more errors, which makes troubleshooting relatively difficult. Of course, we can view the log in kubelet, but only sre has permission, and users may not have this permission. I hope to provide err information in the event.

```yaml
➜  ~ kubectl describe pods test-pod-prestarthook-error
Name:             test-pod-prestarthook-error
Namespace:        default
Priority:         0
Service Account:  default
Node:             minikube/192.168.49.2
Start Time:       Wed, 26 Feb 2025 13:36:21 +0800
Labels:           <none>
Annotations:      <none>
Status:           Running
IP:               10.244.16.55
IPs:
  IP:  10.244.16.55
Containers:
  test-container:
    Container ID:   docker://af7db28b9dcff8da4a582221c151ab7e6447e0177d45d693407e3b557ee3062f
    Image:          nginx
    Image ID:       docker-pullable://nginx@sha256:9d6b58feebd2dbd3c56ab5853333d627cc6e281011cfd6050fa4bcf2072c9496
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PostStartHookError
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 26 Feb 2025 13:37:30 +0800
      Finished:     Wed, 26 Feb 2025 13:37:30 +0800
    Ready:          False
    Restart Count:  3
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ttzcx (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       False
  ContainersReady             False
  PodScheduled                True
Volumes:
  kube-api-access-ttzcx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason               Age                From               Message
  ----     ------               ----               ----               -------
  Normal   Scheduled            77s                default-scheduler  Successfully assigned default/test-pod-prestarthook-error to minikube
  Normal   Pulled               68s                kubelet            Successfully pulled image "nginx" in 7.924s (7.924s including waiting). Image size: 197285467 bytes.
  Normal   Pulled               62s                kubelet            Successfully pulled image "nginx" in 4.838s (4.838s including waiting). Image size: 197285467 bytes.
  Normal   Pulled               45s                kubelet            Successfully pulled image "nginx" in 4.473s (4.473s including waiting). Image size: 197285467 bytes.
  Normal   Pulling              16s (x4 over 76s)  kubelet            Pulling image "nginx"
  Normal   Created              8s (x4 over 68s)   kubelet            Created container: test-container
  Normal   Started              8s (x4 over 68s)   kubelet            Started container test-container
  Warning  FailedPostStartHook  8s (x4 over 68s)   kubelet            PostStartHook failed
  Normal   Killing              8s (x4 over 68s)   kubelet            FailedPostStartHook
  Warning  FailedPreStopHook    8s (x4 over 68s)   kubelet            PreStopHook failed
  Normal   Pulled               8s                 kubelet            Successfully pulled image "nginx" in 7.504s (7.504s including waiting). Image size: 197285467 bytes.
  Warning  BackOff              7s (x5 over 62s)   kubelet            Back-off restarting failed container test-container in pod test-pod-prestarthook-error_default(d4269640-1e2e-45af-bf61-be28d8b4fb17)

```

```yaml
➜  ~ kubectl get event
LAST SEEN   TYPE      REASON                OBJECT                               MESSAGE
79m         Normal    Pulling               pod/my-pod                           Pulling image "nginx"
79m         Warning   Failed                pod/my-pod                           Error: configmap "my-config-map" not found
89m         Normal    Pulled                pod/my-pod                           (combined from similar events): Successfully pulled image "nginx" in 6.352s (6.352s including waiting). Image size: 197285467 bytes.
3m25s       Normal    BackOff               pod/my-pod                           Back-off pulling image "nginx"
17s         Normal    Pulled                pod/test-pod-prestarthook-error      Successfully pulled image "nginx" in 7.924s (7.924s including waiting). Image size: 197285467 bytes.
16s         Normal    Pulling               pod/test-pod-prestarthook-error      Pulling image "nginx"
11s         Normal    Pulled                pod/test-pod-prestarthook-error      Successfully pulled image "nginx" in 4.838s (4.838s including waiting). Image size: 197285467 bytes.
11s         Warning   FailedPreStopHook     pod/test-pod-prestarthook-error      PreStopHook failed
11s         Normal    Killing               pod/test-pod-prestarthook-error      FailedPostStartHook
11s         Warning   FailedPostStartHook   pod/test-pod-prestarthook-error      PostStartHook failed
11s         Normal    Started               pod/test-pod-prestarthook-error      Started container test-container
11s         Normal    Created               pod/test-pod-prestarthook-error      Created container: test-container
10s         Warning   BackOff               pod/test-pod-prestarthook-error      Back-off restarting failed container test-container in pod test-pod-prestarthook-error_default(d4269640-1e2e-45af-bf61-be28d8b4fb17)

```

some code: 

https://github.com/kubernetes/kubernetes/blob/39c640fe9051b60bacbacf47f64cb697fb807861/pkg/kubelet/kuberuntime/kuberuntime_container.go#L308-L324

https://github.com/kubernetes/kubernetes/blob/39c640fe9051b60bacbacf47f64cb697fb807861/pkg/kubelet/kuberuntime/kuberuntime_container.go#L688-L698
