### ISSUE TITLE
Duplicate keys in MatchLabelKeys of PodSpec should be explicitly validated

### ISSUE THREAD

**Issue by mochizuki875** [kubernetes/kubernetes#130554]
#### Summary
If `MatchLabelKeys` of `PodSpec` contains duplicate keys, the validation should fail with an explicit error.

#### Details
If `MatchLabelKeys` of `PodSpec` contains duplicate keys, validation will fail as follows.

`sample-affinity.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sample-affinity
  labels:
    app: sample-affinity
spec:
  containers:
  - image: nginx
    name: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector: {}
        topologyKey: kubernetes.io/hostname
        matchLabelKeys:
        - app
        - app
```
 
```console
$ kubectl apply -f sample-affinity.yaml
The Pod "sample-affinity" is invalid: spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].matchLabelKeys[1]: Invalid value: "app": exists in both matchLabelKeys and labelSelector
```

It is caused by duplication between `matchLabelKeys[1]` and the key added to the `labelSelector` corresponding to `matchLabelKeys[0]`, so strictly speaking, key duplication in `matchLabelKeys` is not validated.
I think it should be explicitly validated.

#### Special notes:
#130534, which adds `matchLabelKeys` validation for `PodTemplateSpec`, is in progress.
In the case of `PodTemplateSpec`, the duplication of keys in `matchLabelKeys` is explicitly validated because the key-values corresponding to `matchLabelKeys` will not be added to the `labelSelector`.

https://github.com/kubernetes/kubernetes/blob/0ab306a08655c72fe26c01090a154264648fd2ba/pkg/apis/core/validation/validation.go#L8032-L8040

/kind feature 
/sig scheduling
