### ISSUE TITLE
Support different verbs for different resourceNames of same resource type.

### ISSUE THREAD

**Issue by GunaKKIBM** [kubernetes/kubernetes#130586]
### What would you like to be added?

Requirement:

I have an application deployed as a pod in kubernetes which needs to be able to create, update, get, etc on only one configmap, but should be able get, list, watch all the other configmaps in the same namespace. 

As of today, when I define two roles 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cm-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cm-writer
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["existing-configmap"]
  verbs: ["create", "delete", "get", "watch", "list"]
```

And create two rolebindings against a serviceaccount and deploy my application, 
the application only picks up one role, and I see the following error in pod logs. I have the added the go code as well for reference

```
package main

import (
	"context"
	"fmt"
	"log"

	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func main() {
	// Load Kubernetes config
	config, err := rest.InClusterConfig()
	if err != nil {
		log.Fatalf("Error creating in-cluster config: %v", err)
	}

	// Create Kubernetes clientset
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		log.Fatalf("Error creating Kubernetes client: %v", err)
	}

	namespace := "default"

	// Get an existing ConfigMap
	existingConfigMapName := "existing-configmap"
	cm, err := clientset.CoreV1().ConfigMaps(namespace).Get(context.TODO(), existingConfigMapName, metav1.GetOptions{})
	if err != nil {
		log.Fatalf("Failed to get ConfigMap: %v", err)
	}

	log.Printf("Retrieved ConfigMap: %s\n", cm.Data)

	// Update the ConfigMap
	cm.Data = map[string]string{
		"newKey1": "newValue1",
		"newKey2": "newValue2",
		"newKey3": "newValue3",
	}

	// update
	_, err = clientset.CoreV1().ConfigMaps(namespace).Update(context.TODO(), cm, metav1.UpdateOptions{})
	if err != nil {
		log.Fatalf("Failed to update ConfigMap: %v", err)
	}

	fmt.Println("ConfigMap updated successfully!")

	existingConfigMapName2 := "existing-configmap2"
        cm, err = clientset.CoreV1().ConfigMaps(namespace).Get(context.TODO(), existingConfigMapName2, metav1.GetOptions{})
        if err != nil {
                log.Fatalf("Failed to get ConfigMap: %v", err)
        }

        log.Printf("Retrieved ConfigMap: %s\n", cm.Data)
}
```

Pod logs
```
2025/03/05 11:52:01 Retrieved ConfigMap: <some-content>
2025/03/05 11:52:01 Failed to update ConfigMap: configmaps "existing-configmap" is forbidden: User "system:serviceaccount:default:default" cannot update resource "configmaps" in API group "" in the namespace "default"
```

### Why is this needed?

Ideally, RBAC should have the capability where, permissions/verbs can be different for different resourceNames even if the resourceType is same.
