### ISSUE TITLE
Secret referenced with envFrom in a Deployment not reloaded after rollout restart

### ISSUE THREAD

**Issue by sybernatus** [kubernetes/kubernetes#130769]
### What happened?

I'm using a Deployment to run an httpd instance in my cluster.
I'm using a secret with `envFrom` to make environment variables available in my container.

If I update my secret and then run a rollout restart on my deployment, I see the pod and its RC is well replaced but the environment variable within the pod didn't change. It still contains the old value.

### What did you expect to happen?

I expect at least that the rollout restart of the pod load the new secret value.

### How can we reproduce it (as minimally and precisely as possible)?

- Deploy a secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  MY_VAR: test
```

- Deploy the deployment referencing that secret:
```yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: busybox
          command: [ "/bin/sh", "-c", "env; sleep 3600" ]
          envFrom:
            - secretRef:
                name: my-secret
```
- Update the secret value
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  MY_VAR: test2
```
- Rollout restart the `my-app` deployment
```shell
kubectl exec -it <pod_name> -- env
# OUTPUT
MY_VAR=test
```

### Anything else we need to know?

I didn't find any official documentation or any issues talking about this behaviour. 

### Kubernetes version

<details>

```console
$ kubectl version
v1.29.10+67d3387
```

</details>

### Cloud provider

<details>
$ oenshift on prem version
v4.16.30
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.10 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://issues.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.10
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
$ uname -a
Linux <hidden> 4.18.0-553.34.1.el8_10.x86_64 #1 SMP Mon Dec 16 04:25:43 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
