### ISSUE TITLE
Pod Disruption Budget Treats Terminating Pods as Unmanaged During Rolling Restarts

### ISSUE THREAD

**Issue by atilsensalduz** [kubernetes/kubernetes#130723]
I have been experiencing a recurring issue with PDBs during every rolling restart or deployment. The issue manifests as a momentary event where a terminating pod from the old ReplicaSet is treated as unmanaged, causing the following warning event:

`Warning  CalculateExpectedPodCountFailed  49s (x3 over 49s)  controllermanager  Failed to calculate the number of expected pods: found no controllers for pod "service-6958844f49-rw9cr"
`

Just before the pod is deleted, the PDB incorrectly classifies it as an unmanaged pod, leading to the above warning.
Despite this being a transient issue (lasting only momentarily before the pod is removed), I have observed it consistently across multiple microservices.

Expected Behaviour: The terminating pod should still be recognized as managed by the ReplicaSet and not cause a miscalculation in expected pod counts.

Environment Details:
Kubernetes Version: 1.30 EKS

PDB Configuration:
```
  apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: test-pdb
      argocd.argoproj.io/instance: test
      helm.sh/chart: generic-1.0.0
    name: test
    namespace: test
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        app.kubernetes.io/name: test
```

**Comment by AmarNathChary** [comment]
Does this impact workload availability, or is it just a warning event?

**Comment by atilsensalduz** [comment]
It's just a warning event, but it triggers unnecessary notifications on the ArgoCD side because the PDB status is marked as false and ArgoCD treats as an unhealthy resource just for a sec.

**Comment by atilsensalduz** [comment]
I'm observing this behavior when the deployment has 2 pods, but I don't see it when the deployment has 3 pods.

**Comment by mwatkins-ld** [comment]
Just encountered this issue also. Replica count 2 during rollout and minAvailable 50% on k8s v1.33

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
  spec:
    minAvailable: 50%
...
```

**Comment by julien-aubert** [comment]
We're running into the exact same problem.

Here is our config:

- Kubernetes 1.32.4 (GKE)
- Deployments:
```
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
```
- PDBs:
```
maxUnavailable: 1
```

We are using those configs to not decrease the number of pod during a deployment, but we want to not block Kubernetes upgrade or maintenance.

We know that we can use `minAvailable: 1` instead, but in some cases, some of our deployments have only one replicas (during night end weekend) so we want to cover all cases with the same config.

Each time a deployment is restarted, two events are raised saying:
```
Note:        Failed to calculate the number of expected pods: found no controllers for pod "my-pod-XXX-vgjnm"                                                                                                                                            
Reason:      CalculateExpectedPodCountFailed
```

Our main problem is that ArgoCD raises an alert saying that our application is "Degraded".
But I don't think the problem is on ArgoCD side.

The problem here is that during a short period of time some pods have no controller.
