### ISSUE TITLE
[Bug] Pod not scheduled although there is a node matching all hard pod affinity terms

### ISSUE THREAD

**Issue by anbrsap** [kubernetes/kubernetes#130784]
### What happened?

A pod (`pod-x`) is supposed to be scheduled on a node (only) when:

- another pod with `label-1: x` **and**
- yet another pod with `label-2: x`

are already running on that node.

This should be possible by using _multiple_ pod affinity terms in `spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution` like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-x
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              label-1: "x"
          topologyKey: kubernetes.io/hostname
        - labelSelector:
            matchLabels:
              label-2: "x"
          topologyKey: kubernetes.io/hostname
  containers:
    - name: c1
      image: registry.k8s.io/pause:3.8
```

For testing purposes the two prerequisite pods may be created like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    label-1: "x"
spec:
  containers:
    - name: c1
      image: registry.k8s.io/pause:3.8
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    label-2: "x"
spec:
  containers:
    - name: c1
      image: registry.k8s.io/pause:3.8
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              label-1: "x"
          topologyKey: kubernetes.io/hostname
```

What actually happens is that **`pod-x` is not scheduled at all**:

```
NAME    STATUS    NODE
pod-a   Running   ip-10-250-74-235.ec2.internal
pod-b   Running   ip-10-250-74-235.ec2.internal
pod-x   Pending   <none>
```

Status of `pod-x`:

```yaml
status:                                                                                                                                                                                     
  conditions:                                                                                                                                                                               
  - lastProbeTime: null                                                                                                                                                                     
    lastTransitionTime: "2025-03-13T09:49:54Z"                                                                                                                                              
    message: '0/1 nodes are available: 1 node(s) didn''t match pod affinity rules.                                                                                                          
      preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.'                                                                                                     
    reason: Unschedulable                                                                                                                                                                   
    status: "False"                                                                                                                                                                         
    type: PodScheduled                                                                                                                                                                      
  phase: Pending                                                                                                                                                                            
  qosClass: BestEffort                                                                                                                                                                      
```

### What did you expect to happen?

The [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodAffinity) says:

> requiredDuringSchedulingIgnoredDuringExecution ([]PodAffinityTerm)
> ...
> When there are multiple elements, the lists of nodes corresponding to each podAffinityTerm are intersected, i.e. all terms must be satisfied.

This means, each affinity term should be resolved to a list of matching nodes independently of other affinity terms, and the results are intersected to yield the nodes where the pod to be scheduled is feasible. This corresponds to the [algorithm](https://github.com/kubernetes/design-proposals-archive/blob/main/scheduling/podaffinity.md#algorithm) (step 1a) described in the pod affinity design proposal.

In my example the pod affinity terms would resolve to two lists:

- `["ip-10-250-74-235.ec2.internal"]`
- `["ip-10-250-74-235.ec2.internal"]`

The intersection of those yields:

- `["ip-10-250-74-235.ec2.internal"]`

**Expected Result**: `pod-x` is feasible on node `ip-10-250-74-235.ec2.internal` and gets scheduled there.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create the pods:

    ```bash
    kubectl create -f - <<EOF
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-a
      labels:
        label-1: "x"
    spec:
      containers:
        - name: c1
          image: registry.k8s.io/pause:3.8
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-b
      labels:
        label-2: "x"
    spec:
      containers:
        - name: c1
          image: registry.k8s.io/pause:3.8
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  label-1: "x"
              topologyKey: kubernetes.io/hostname
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-x
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  label-1: "x"
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchLabels:
                  label-2: "x"
              topologyKey: kubernetes.io/hostname
      containers:
        - name: c1
          image: registry.k8s.io/pause:3.8
    EOF
    ```

2. Check the pods' status:

    ```bash
    kubectl get pods
    ```
    
    Output:

    ```
    NAME    READY   STATUS    RESTARTS   AGE
    pod-a   1/1     Running   0          86s
    pod-b   1/1     Running   0          85s
    pod-x   0/1     Pending   0          85s
    ```

3. Inspect the reason for `pod-x` not being scheduled:

    ```bash
    kubectl get pod pod-x -o yaml
    ```

    ```yaml
    ...
    status:
      conditions:
      - lastProbeTime: null
        lastTransitionTime: "2025-03-13T14:48:28Z"
        message: '0/1 nodes are available: 1 node(s) didn''t match pod affinity rules.
          preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.'
        reason: Unschedulable
        status: "False"
        type: PodScheduled
      phase: Pending
      qosClass: BestEffort
    ```

### Anything else we need to know?

As soon as a _single_ pod, e.g. `pod-a`, matches both pod affinity terms, `pod-x` _gets_ scheduled. This proves that the pod affinity terms as such are understood correctly. However, considering only nodes that match _all_ affinity terms evaluated with a _single_ pod is not compliant to the API spec and design proposal.

### Kubernetes version

Tested with:

* v1.31.5
* v1.29.1

### Cloud provider

not relevant

### OS version

not relevant

### Install tools

not relevant

### Container runtime (CRI) and version (if applicable)

not relevant

### Related plugins (CNI, CSI, ...) and versions (if applicable)

not relevant

**Comment by joe-msys** [comment]
I'd like to work on this issue.

**Comment by timown** [comment]
spent a few hours on this, thought I was going crazy
yep it doesn't work.

**Comment by timown** [comment]
interesting @togettoyou, so that means there is currently no functionality in k8s to assign `pod-x` on a node with `pod-a` and `pod-b`, right?

**Comment by anbrsap** [comment]
> the rules under `requiredDuringSchedulingIgnoredDuringExecution` in `podAffinity` must be satisfied by the same Pod — not by multiple Pods individually fulfilling each condition.
> …
> this is expected behavior, not a bug.

@togettoyou Please prove your statement by citation of the respective passages in the specification (design proposal, API docs).

As I already pointed out in _What did you expect to happen?_, my understanding of the specification is:

> … each affinity term should be resolved to a list of matching nodes independently of other affinity terms, and the results are intersected to yield the nodes where the pod to be scheduled is feasible

If a _single_ pod must match multiple labels, this must be expressed in a _single_ affinity term like this:

```yaml
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              label-1: "x"
              label-2: "x"
          topologyKey: kubernetes.io/hostname
```
