### ISSUE TITLE
Linking docker containers through yaml file

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#13085]
Hi,

I have been trying to get the mysql and wordpress containers up in the kubernetes cluster. I have my mysql container and want to link it with the wordpress container.

Normally this is how it's done throught CLI:
docker run --name some-wordpress --link some-mysql:mysql -p 80:80 -d wordpress

But how do you do it in the yaml file?

This is the wordpress.yaml file:
```
apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    name: wordpress
spec:
  containers:
    - image: wordpress
      name: wordpress
      env:
        - name: WORDPRESS_DB_PASSWORD
                    value: password
      ports:
        - containerPort: 80
          name: wordpress
      volumeMounts:
        - name: wordpress-persistent-storage
                    mountPath: /var/www/html
```
