### ISSUE TITLE
Validating Admission Policy with configmap parameter not working

### ISSUE THREAD

**Issue by Zerotay** [kubernetes/kubernetes#130887]
### What happened?

I'm testing VAP in my local cluster(currently using Virtualbox with Vagrant).  
I tried to use `paramKind` in VAP and `paramRef` in VAPB, as document said that configMap or any resources can be used in those fields, I used configmap.  
Creating VAP was good, but when I tried to check the policy works well, server returned error with this message.  
```
ValidatingAdmissionPolicy 'deny-hostpath-policy' with binding 'default-deny-hostpath' denied request: failed to configure binding: no params found for policy binding with `Deny` parameterNotFoundAction
```

### What did you expect to happen?

I hoped the server returns deny because of the validations rules. 

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: "test"
  namespace: "default"
data:
  subjects: "sam"
  secret_role_prefix: "secret"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "deny-secret-policy"
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: v1
    kind: ConfigMap
  matchConstraints:
    resourceRules:
    - apiGroups:   ["rbac.authorization.k8s.io"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["roles", "rolebindings"]
  validations:
    - expression: "params != null"
      message: "params missing but required to bind to this policy"
      messageExpression: "string(params.data.subjects)"
    - expression: "false"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "default-deny-secret"
spec:
  paramRef:
    name: "test"
    namespace: "default"
    parameterNotFoundAction: Deny
  policyName: "deny-secret-policy"
  validationActions: [Deny]
  matchResources:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: default
```  
  
ConfigMap, ValidatingAdmissionPolicy, ValidatingAdmissionPolicyBinding manifests used for test.    
```
# use user sam
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sam-secret
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sam-secret
  namespace: default
subjects:
- kind: User
  name: sam
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sam-secret
  apiGroup: rbac.authorization.k8s.io
```  

Role, RoleBinding manifests for checking validating policy.  

![Image](https://github.com/user-attachments/assets/f8508e99-8d2b-4b6f-b9bf-2190633fbf29)

### Anything else we need to know?

What I tried:  
- Made the ConfigMap first, and after it created, then made VAP, VAPB --> not worked.  
- Changed matchConditions. i.e) not about rbac, such as pods

Extra FeatureGates:
- CSIVolumeHealth=true
- RecursiveReadOnlyMounts=true

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here  
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.2
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here  
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
...
$ uname -a
# paste output here
Linux master1 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm version: &version.Info{Major:"1", Minor:"32", GitVersion:"v1.32.2", GitCommit:"67a30c0adcf52bd3f56ff0893ce19966be12991f", GitTreeState:"clean", BuildDate:"2025-02-12T21:24:52Z", GoVersion:"go1.23.6", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd github.com/containerd/containerd/v2 v2.0.3 
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
For installing CNI : https://raw.githubusercontent.com/projectcalico/calico/v3.29.2/manifests/calico.yaml
</details>
