### ISSUE TITLE
[Question] How do I force Kubernetes to re-pull an image?

### ISSUE THREAD

**Issue by rajsaur** [kubernetes/kubernetes#130845]
I have the following replication controller in Kubernetes on GKE:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    app: myapp
    deployment: initial
  template:
    metadata:
      labels:
        app: myapp
        deployment: initial
    spec:
      containers:
      - name: myapp
        image: myregistry.com/myapp:5c3dda6b
      imagePullPolicy: Never
      imagePullSecrets:
        - name: myregistry.com-registry-key

```Now, if I say

`kubectl rolling-update myapp --image=<image path>
`
the rolling update is performed, but no re-pull. Why?

**Comment by rajsaur** [comment]
@niranjandarshann  My bad but I tried by giving imagepullpolicy as Always also but its not working.

**Comment by niranjandarshann** [comment]
What error you are facing? 

> [@niranjandarshann](https://github.com/niranjandarshann) My bad but I tried by giving imagepullpolicy as Always also but its not working.

**Comment by rajsaur** [comment]
port Allocation not defined

**Comment by niranjandarshann** [comment]
> port Allocation not defined

Try to add 
```
ports:
- containerPort:80
```

**Comment by niranjandarshann** [comment]
Please find the updated yaml file and then check if you are facing any issue
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    app: myapp
    deployment: initial
  template:
    metadata:
      labels:
        app: myapp
        deployment: initial
    spec:
      containers:
      - name: myapp
        image: myregistry.com/myapp:5c3dda6b
        ports:
        - containerPort: 80
      imagePullPolicy: Always
      imagePullSecrets:
        - name: myregistry.com-registry-key
```

**Comment by rajsaur** [comment]
Facing issue with re pull image

**Comment by niranjandarshann** [comment]
> Facing issue with re pull image

there should not  be any error message With .
So, this spec snippet works:
```
spec:
  containers:
  - name: myapp
    image: myregistry.com/myapp:5c3dda6b
    ports:
    - containerPort: 80
    imagePullPolicy: Always
  imagePullSecrets:
    - name: myregistry.com-registry-key
```
