### ISSUE TITLE
Support HTTP/3 for Container Probes

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubernetes#130851]
I am running a python quart application using hypercorn  ASGI server. I am using flask-healthz for probes. Can I use UDP and HTTPS (port:443) for these probes? I hit the following errors with the pods:
```
  Warning  Unhealthy  1s (x2 over 6s)  kubelet            Liveness probe failed: Get "https://10.1.207.219:443/healthz/live": dial tcp 10.1.207.219:443: connect: connection refused
  Warning  Unhealthy  1s (x2 over 6s)  kubelet            Readiness probe failed: Get "https://10.1.207.219:443/healthz/ready": dial tcp 10.1.207.219:443: connect: connection refused
```
Log of the application:
```
[pythonrestapi-0 pythonrestapi] 2025-03-17 03:38:17 INFO     Running on http://0.0.0.0:80 (CTRL + C to quit) 
[pythonrestapi-0 pythonrestapi] 2025-03-17 03:38:18 INFO     Running on https://0.0.0.0:443 (QUIC) (CTRL + C to quit) 
```

**Comment by aojea** [comment]
> Can I use UDP and HTTPS (port:443) for these probes? I hit the following errors with the pods:

do you mean is an http3 server?

**Comment by khteh** [comment]
Yes Http/3.

**Comment by khteh** [comment]
Does the probe spec accept `protocol`?

**Comment by khteh** [comment]
Inside the pod:
```
root@pythonrestapi-0:/app# curl --insecure https://localhost/healthz/live
curl: (7) Failed to connect to localhost port 443 after 398 ms: Couldn't connect to server
```

**Comment by aojea** [comment]
http/3 is not supported as today for http probes, this should be a feature request.
You have to use the exec probe and a tool like curl for that, until this feature is implemented

/retitle "Support HTTP/3 for Container Probes"
/kind feature

**Comment by khteh** [comment]
Not even using TCP protocol for the same port?

**Comment by khteh** [comment]
> You have to use the exec probe and a tool like curl for that, until this feature is implemented

How? The following still fails:
```
    Liveness:   exec [curl -s --insecure https://localhost/healthz/live] delay=10s timeout=10s period=5s #success=1 #failure=3
    Readiness:  exec [curl -s --insecure https://localhost/healthz/ready] delay=10s timeout=10s period=5s #success=1 #failure=3
```

**Comment by khteh** [comment]
Inside the pod:
```
root@pythonrestapi-0:/app# curl --insecure https://localhost/healthz/live
curl: (7) Failed to connect to localhost port 443 after 0 ms: Couldn't connect to server
root@pythonrestapi-0:/app# curl --insecure https://localhost/healthz/ready
curl: (7) Failed to connect to localhost port 443 after 0 ms: Couldn't connect to server
```

**Comment by khteh** [comment]
It works with the application run locally in BASH shell:
```
$ curl --insecure https://localhost:4433/healthz/ready
{"status": 200, "title": "OK"}khteh@khteh-p17-2i:/usr/src/Python/PythonRestAPI 2080 $ 
$ curl --insecure https://localhost:4433/healthz/live
{"status": 200, "title": "OK"}
```

**Comment by aojea** [comment]
> Not even using TCP protocol for the same port?

If your server is http3 and only uses UDP how can TCP work?

> How? The following still fails:

I said curl , but at the end you need something that executes http3 requests, from the docs https://curl.se/docs/http3.html it seems you need a binary with http3 compiled and set the `--http3` flag

**Comment by khteh** [comment]
> If your server is http3 and only uses UDP how can TCP work?

The question is "only uses UDP" <- I am not sure about this.


> I said curl , but at the end you need something that executes http3 requests, from the docs https://curl.se/docs/http3.html it seems you need a binary with http3 compiled and set the --http3 flag

Too much trouble. Why does it work when I run the app locally and curl it?

**Comment by aojea** [comment]
I'm trying to help, I really don't know how your application is working, but simple thing is to expose the endpoint in an http or http server, and not use http3 only

**Comment by khteh** [comment]
> I also notice that you use different tcp ports, your local example uses 4433

You can't use port lower than 1024 on bare-metal OS unless using elevated privilege which is not desired in this case.

**Comment by khteh** [comment]
No. The pod in the k8s is using 443.

**Comment by adrianmoisey** [comment]
> It works with the application run locally in BASH shell:
> 
> ```
> $ curl --insecure https://localhost:4433/healthz/ready
> {"status": 200, "title": "OK"}
> $ curl --insecure https://localhost:4433/healthz/live
> {"status": 200, "title": "OK"}
> ```

But then how does this work?

**Comment by khteh** [comment]
Diff env diff setup/config

**Comment by adrianmoisey** [comment]
This works for me:
```
apiVersion: v1
kind: Pod
metadata:
  name: curl-test
spec:
  containers:
  - name: curl-container
    image: python:3.11-slim
    command: ["sh", "-c", "apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/* && python3 -m http.server 8080"]
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - "curl -f http://localhost:8080/"
      initialDelaySeconds: 5
      periodSeconds: 10
```

**Comment by khteh** [comment]
https://github.com/pgjones/hypercorn/issues/290

**Comment by khteh** [comment]
Is it possible to use a separate docker image for probes? https://github.com/justdan6/docker-quart-http3

**Comment by khteh** [comment]
> http/3 is not supported as today for http probes, this should be a feature request. You have to use the exec probe and a tool like curl for that, until this feature is implemented
> 
> /retitle "Support HTTP/3 for Container Probes" /kind feature

Isn't this still something that needs to work on?

**Comment by aojea** [comment]
> > http/3 is not supported as today for http probes, this should be a feature request. You have to use the exec probe and a tool like curl for that, until this feature is implemented
> > /retitle "Support HTTP/3 for Container Probes" /kind feature
> 
> Isn't this still something that needs to work on?

yeah, but this is issue now is confusing with, "Support HTTP/3 for Container Probes" is a real feature request, but what happens in your environment is not clear if is caused by that, and there are now more than 20 comments that will make this a magnet for random problem :)

**Comment by khteh** [comment]
After fixing the app, the probes work now with UDP. I am not sure if http/3 is relevant here.
```
            - containerPort: 443
              name: https-udp
              protocol: UDP
            - containerPort: 443
              name: https-tcp
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/ready
              port: https-udp
              scheme: HTTPS
              httpHeaders:
                - name: Host
                  value: myhost.com
```
