### ISSUE TITLE
Applying ValidatingAdmissionPolicyBinding with paramRef fails with `spec.paramRef.parameterNotFoundAction: Required value`

### ISSUE THREAD

**Issue by poehlerflorian** [kubernetes/kubernetes#130822]
### What happened?

When trying to apply the Binding for a Validating Admission Policy referencing from a Custom Resource I get the following error (See manifests below):
`The ValidatingAdmissionPolicyBinding "test-policy-binding" is invalid: spec.paramRef.parameterNotFoundAction: Required value`

Applying the same binding without `paramRef` works as expected.

Manifests were created based on https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/ and stripped down in the example manifests below to allow for minimal reproducibility.

### What did you expect to happen?

VAP-Binding should have been applied successfully.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create k8s cluster
2. Apply Manifests
    1. CRD
        <details>

        ```yaml
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: testparams.test.param
        spec:
          group: test.param
          versions:
            - name: v1
              served: true
              storage: true
              schema:
                openAPIV3Schema:
                  type: object
                  properties:
                    test:
                      type: string
          scope: Cluster
          names:
            plural: testparams
            singular: testparam
            kind: TestParam
        ```

        </details>
    2. Policy
        <details>

        ```yaml
        apiVersion: admissionregistration.k8s.io/v1
        kind: ValidatingAdmissionPolicy
        metadata:
          name: test-policy
        spec:
          failurePolicy: Fail
          matchConstraints:
            resourceRules:
            - apiGroups:
              - ""
              apiVersions:
              - v1
              operations:
              - CREATE
              - UPDATE
              resources:
              - pods
          paramKind:
            apiVersion: test.param/v1
            kind: TestParam
          validations:
          - expression: 'params.test == "test-value"'
            message: Success
        ```

        </details>
    3. Config
        <details>

        ```yaml
        apiVersion: test.param/v1
        kind: TestParam
        metadata:
          name: test-config
        test: test-value
        ```

        </details>
    4. Binding
        <details>

        ```yaml
        apiVersion: admissionregistration.k8s.io/v1
        kind: ValidatingAdmissionPolicyBinding
        metadata:
          name: test-policy-binding
        spec:
          policyName: test-policy
          paramRef:
            name: test-config
          validationActions:
          - Warn
        ```

        </details>
3. Applying the binding fails with `The ValidatingAdmissionPolicyBinding "test-policy-binding" is invalid: spec.paramRef.parameterNotFoundAction: Required value`

### Kubernetes version

<details>

```console
# k3d/k3s
$ kubectl version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.31.5+k3s1
# minikube
$ kubectl version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.0
```
Tested with k3d/k3s and minikube Cluster

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="9.5 (Teal Serval)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.5 (Teal Serval)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.5"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.5"
SUPPORT_END=2032-06-01
$ uname -a
Linux redacted.hostname 5.14.0-503.26.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Mar 3 05:56:39 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

- k3d/k3s
- minikube
</details>

### Container runtime (CRI) and version (if applicable)

<details>

k3d/k3s: `containerd://1.7.23-k3s2`
minikube: `containerd://1.7.24`
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
