### ISSUE TITLE
Int-or-String fields are presented as Object in kubectl explain

### ISSUE THREAD

**Issue by cbandy** [kubernetes/kubernetes#130946]
### What happened?

I created a CRD that has a map of int-or-string fields. When I `kubectl explain` that field, its type is presented as `<map[string]Object>`.

### What did you expect to happen?

I'm not certain what I expect it to present, but acceptable values are not shaped like JSON objects.

### How can we reproduce it (as minimally and precisely as possible)?

This CRD has a single field in its spec. Create or Apply this CRD, then run `kubectl explain` on it.

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: maps.example.com
spec:
  group: example.com
  names:
    kind: Map
    listKind: MapList
    plural: maps
    singular: map
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              options:
                type: object
                x-kubernetes-map-type: atomic
                maxProperties: 20
                additionalProperties:
                  anyOf:
                  - type: integer
                  - type: string
                  x-kubernetes-int-or-string: true
```

```console
$ kubectl explain Maps.spec
GROUP:      example.com
KIND:       Map
VERSION:    v1

FIELD: spec <Object>


DESCRIPTION:
    <empty>
FIELDS:
  options	<map[string]Object> 👈
    <no description>
```

```console
$ kubectl explain Maps.spec.options
GROUP:      example.com
KIND:       Map
VERSION:    v1

FIELD: options <map[string]Object> 👈


DESCRIPTION:
    <empty>
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.32.1+k3s1
```

</details>

### Cloud provider

n/a

### OS version

`kubectl` on macOS

### Install tools

<details>
Rancher Desktop
</details>

**Comment by cbandy** [comment]
I think I see the raw schema an HTTP response during `kubectl -v10 explain`, so maybe this happens on the client side?

```
\"spec\":{\"type\":\"object\",\"properties\":{\"options\":{\"type\":\"object\",\"maxProperties\":20,\"additionalProperties\":{\
"anyOf\":[{\"type\":\"integer\"},{\"type\":\"string\"}],\"x-kubernetes-int-or-string\":true},\"x-kubernetes-map-type\":\"atomic\"}}
```

/sig cli

**Comment by thisisharrsh** [comment]
The `options` field is defined as a map. It uses `anyOf` with integer and string types, along with `x-kubernetes-int-or-string: true`.

**Comment by thisisharrsh** [comment]
Kubernetes' OpenAPI schema processing treats `anyOf` as a generic object, leading to `<map[string]Object]>` in kubectl explain.

**Comment by thisisharrsh** [comment]
The possible workaround to this issue could be removing `anyOf` and use `x-kubernetes-int-or-string` directly.

**Comment by thisisharrsh** [comment]
That avoids `anyOf`, which may be causing `kubectl` explain to default to `<map[string]Object]>`.

**Comment by mpuckett159** [comment]
/remove-sig cli
This seems like a decision for API Machinery.

**Comment by cbandy** [comment]
> The possible workaround to this issue could be removing `anyOf` and use `x-kubernetes-int-or-string` directly.
>
> That avoids `anyOf`, which may be causing `kubectl` explain to default to `<map[string]Object]>`.

When I do that, the API server still appears to return `anyOf`, and `explain` still shows `<map[string]Object>`:

```yaml
              options:
                type: object
                x-kubernetes-map-type: atomic
                maxProperties: 20
                additionalProperties:
                  x-kubernetes-int-or-string: true
```

`kubectl -v10 explain Maps.spec`

```
spec\":{\"type\":\"object\",\"properties\":{\"options\":{\"type\":\"object\",\"maxProperties\":20,\"additionalProperties\":{\"anyOf\":[{\"type\":\"integer\"},{\"type\":\"string\"}],\"x-kubernetes-int-or-string\":true},\"x-kubernetes-map-type\":\"atomic\"}}
```

/remove-lifecycle stale
