### ISSUE TITLE
Prevent Pod Rescheduling When Other Replica is Healthy

### ISSUE THREAD

**Issue by ganchandrasekaran** [kubernetes/kubernetes#130936]
#### Problem Statement
Currently, when a node fails, Kubernetes reschedules pods onto other nodes even if another healthy replica exists on a different node. This behavior can lead to unnecessary resource usage, overloading of remaining nodes, and increased costs in environments where resource optimization is critical.

#### Proposed Solution
Introduce a new field in the Deployment or Pod spec, such as `preventRescheduleIfHealthy: true` or `maxUnavailable: 1`. When this field is set, the Kubernetes scheduler would check if another healthy replica of the same application is running on a different node. If a healthy replica exists, the scheduler would skip rescheduling the failed pod until the healthy replica becomes unhealthy or the node is restored.

#### Alternatives Considered
I explored using Pod Anti-Affinity to ensure replicas are not co-located on the same node, but this does not prevent rescheduling when a node fails. I also considered writing a custom controller to enforce this behavior, but this approach is complex, error-prone, and not scalable. A native Kubernetes feature would provide a more robust and maintainable solution.

#### Example Implementation 1
Here’s an example of how the new field could be added to a Deployment spec: The `preventRescheduleIfHealthy`  specifies to prevent reschedule if any other pod is already healthy.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      preventRescheduleIfHealthy: true
      containers:
      - name: my-container
        image: my-image
```

#### Example Implementation 2
Here’s an example of how the new field could be added to a Deployment spec: The `maxUnavailable` specifies that at most one replica can be unavailable at any time.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      disruptionBudget:
        maxUnavailable: 1
      containers:
      - name: my-container
        image: my-image
```

#### Use Case
In my deployment, I have a stateful application that runs two replicas for high availability. When a node fails, Kubernetes reschedules the failed pod onto another node, even though the second replica is already healthy and running on a different node. This results in unnecessary resource consumption and potential performance degradation. I want to ensure that the second replica is not rescheduled unless the first replica is unhealthy, to optimize resource usage and reduce costs.

#### Impact
This feature would help users optimize resource usage, reduce unnecessary pod rescheduling, and lower costs in environments where resource efficiency is critical. It would also simplify the management of stateful applications and improve the overall stability of deployments.

#### References
- [Pod Topology Spread Constraints Documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/)
