### ISSUE TITLE
Custom Resource Definition format is not validated

### ISSUE THREAD

**Issue by Skaronator** [kubernetes/kubernetes#131082]
### What happened?

I noticed that the kube-api server doesn't validate the `format` field despite the documentation mentioning that only the following field types are valid: 

- int32
- int64
- float
- double
- byte
- date
- date-time
- password

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#format

Trying to apply a CRD with field `format: giubseufbuilsebfiu` results in a successfull apply.

### What did you expect to happen?

I would expect that the kube api server returns an error that the `format: giubseufbuilsebfiu` is not an valid format.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: debugformats.example.com
spec:
  group: example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              format:
                format: giubseufbuilsebfiu
                type: string
  scope: Namespaced
  names:
    plural: debugformats
    singular: debugformat
    kind: DebugFormat
    shortNames:
    - df
```

Apply this file will result in: `customresourcedefinition.apiextensions.k8s.io/debugformats.example.com configured`

### Anything else we need to know?

I encountered a validation error with [kubeconform](https://github.com/yannh/kubeconform) when processing a duration field within the Grafana Operator's GrafanaDatasource Custom Resource Definition (CRD). The problem stems from the field's format: duration specification in the operator's manifests: https://github.com/grafana/grafana-operator/blob/8a35e3b02a161c8c8196eb15c0245a0932a2357f/bundle/manifests/grafana.integreatly.org_grafanadatasources.yaml#L159

This highlights a potential weakness: if the Kubernetes API server strictly enforced expected field types, this issue would not arise.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.2-eks-bc803b4
```

</details>

### Cloud provider

<details>
AWS EKS 1.32
</details>
