### ISSUE TITLE
Same RWO PVC ends up on different nodes

### ISSUE THREAD

**Issue by nicsalv** [kubernetes/kubernetes#131152]
### What happened?

I applied the following configuration that has two pods using the same RWO PVC.

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: data
      resources:
        limits:
          cpu: "1"
          memory: "200Mi"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: claim1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: data
      resources:
        limits:
          cpu: "1"
          memory: "200Mi"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: claim1

```

According to #103305 and #26567, pods could be scheduled on different nodes, and actually were. But, contrary to these issues, both pods were able to attach to the volume (s?) and run just fine.

It really seems that the PVC "used" both nodes because data written by both pods were present on each corresponding node, and this happened **without any notice**.

Is this expected behavior?

### What did you expect to happen?

Volume attachment should fail for at least one of the two pods.

### How can we reproduce it (as minimally and precisely as possible)?

By applying the provided configuration.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.4+rke2r1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux ubuntu-nic 6.8.0-57-generic #59~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Mar 19 17:07:41 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
