### ISSUE TITLE
Allow users to modify the nodeAffinity field inside a persistentVolume.

### ISSUE THREAD

**Issue by mowangdk** [kubernetes/kubernetes#131108]
### What would you like to be added?

I hope to make nodeAffinity field in persistentvolume editable

### Why is this needed?

We（AlibabaCloud）has recently introduced [Regional EBS](https://www.alibabacloud.com/help/en/ecs/user-guide/regional-essd-disks?spm=a2c63.p38356.0.i1). a new type of EBS that enables pod(app) to utilize it across all zones within a specific region, thereby achieving higher availablity. 

![Image](https://github.com/user-attachments/assets/a42d92b1-2393-42c6-9b05-ff39f4a54792)

Meanwhile, users can modify their existing EBS to a regional EBS by openapi to use the EBS in the other zone. However, after changing the EBS type, we cannot modify the current PV's nodeAffinity to enable the new feature, as it remains limited to its original zone.

current state
```
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - cn-hangzhou-i
```

desired state
```
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "topology.kubernetes.io/region"
          operator: In
          values:
          - cn-hangzhou
```

therefore, we want to make nodeAffinity editable to transition PVs from their current state to the desired state. 

We also note that [Hyperdisk Balanced High Availability](https://cloud.google.com/compute/docs/disks/hyperdisks) in GCP has a similar definition, suggesting similar requirements. 

![Image](https://github.com/user-attachments/assets/0e5a1c4f-b573-4195-9b12-988256fc4b12)
