### ISSUE TITLE
containerd eviction tests have become flaky

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/kubernetes#131142]
### Which jobs are flaking?

After containerd 2.x bump, the containerd eviction tests have become flaky. These tests were never flaky before 2.x bump. It might be worth looking into this as this bump already caused one test to fail (#130663)

### Which tests are flaking?

`PriorityPidEvictionOrdering`: https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=PriorityPidEvictionOrdering

`MemoryAllocatableEviction`:  https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=MemoryAllocatableEviction

### Since when has it been flaking?

Since containerd 2.x bump

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-eviction

### Relevant SIG(s)

/sig node

/cc @SergeyKanzhelev @mikebrow

**Comment by mikebrow** [comment]
```
state:
              waiting:
                message: Container image "registry.k8s.io/e2e-test-images/busybox:1.36.1-1"
                  is not present with pull policy of Never
                reason: ErrImageNeverPull

```

any recent changes to never pull setup? maybe https://github.com/kubernetes/kubernetes/pull/128152
