### ISSUE TITLE
Kubelet failed to start on reboot with memory manager's `Static` policy

### ISSUE THREAD

**Issue by Vigilans** [kubernetes/kubernetes#131253]
### What happened?

Memory manager's `Static` policy will cause kubelet fail to start on reboot, when total memory of each numa node changes after each reboot, while they still sum up to a fixed number, just as https://github.com/kubernetes/kubernetes/issues/109996 describes.
 
Though Kubernetes v1.32 [improves memory manager reliability and consistency](https://kubernetes.io/blog/2024/12/13/memory-manager-goes-ga/#improving-memory-manager-reliability-and-consistency) with https://github.com/kubernetes/kubernetes/pull/127074 by @Tal-or, the issue is still not fixed because it still checks whether numa node's total memory is unchanged:

https://github.com/kubernetes/kubernetes/blob/d64f34eb2cf57ca017368bd94dc577952c2647d9/pkg/kubelet/cm/memorymanager/policy_static.go#L710-L714

Thus following error happened in kubelet on reboot:
<details>
```
Apr 11 09:15:09 master0 kubelet[13019]: E0411 09:15:09.451647   13019 policy_static.go:718] "Memory states for the NUMA node and resource are different" node=2 resource="memory" field="TotalMemSize" TotalMemSize1=135233794048 TotalMemSize2=135277490176 memoryState1={"total":135233794048,"systemReserved":4429185024,"allocatable":130804609024,"reserved":0,"free":130804609024} memoryState2={"total":135277490176,"systemReserved":4429185024,"allocatable":130848305152,"reserved":0,"free":130848305152}
Apr 11 09:15:09 master0 kubelet[13019]: E0411 09:15:09.451671   13019 policy_static.go:90] "Invalid state, please drain node and remove policy state file" err="[memorymanager] the expected machine state is different from the real one"
Apr 11 09:15:09 master0 kubelet[13019]: E0411 09:15:09.451680   13019 memory_manager.go:202] "Policy start error" err="[memorymanager] the expected machine state is different from the real one"
Apr 11 09:15:09 master0 kubelet[13019]: E0411 09:15:09.451690   13019 kubelet.go:1643] "Failed to start ContainerManager" err="start memory manager error: [memorymanager] the expected machine state is different from the real one"
Apr 11 09:15:09 master0 systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
```
</details>

1. Memory state json before reboot:
<details>
```json
{
  "policyName": "Static",
  "machineState": {
    "0": {
      "numberOfAssignments": 0,
      "memoryMap": {
        "hugepages-1Gi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "hugepages-2Mi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "memory": {
          "total": 134607716352,
          "systemReserved": 4429185024,
          "allocatable": 130178531328,
          "reserved": 0,
          "free": 130178531328
        }
      },
      "cells": [
        0
      ]
    },
    "1": {
      "numberOfAssignments": 0,
      "memoryMap": {
        "hugepages-1Gi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "hugepages-2Mi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "memory": {
          "total": 135277490176,
          "systemReserved": 4429185024,
          "allocatable": 130848305152,
          "reserved": 0,
          "free": 130848305152
        }
      },
      "cells": [
        1
      ]
    },
    "2": {
      "numberOfAssignments": 0,
      "memoryMap": {
        "hugepages-1Gi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "hugepages-2Mi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "memory": {
          "total": 135233794048,
          "systemReserved": 4429185024,
          "allocatable": 130804609024,
          "reserved": 0,
          "free": 130804609024
        }
      },
      "cells": [
        2
      ]
    },
    "3": {
      "numberOfAssignments": 0,
      "memoryMap": {
        "hugepages-1Gi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "hugepages-2Mi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "memory": {
          "total": 134193364992,
          "systemReserved": 4429185024,
          "allocatable": 129764179968,
          "reserved": 0,
          "free": 129764179968
        }
      },
      "cells": [
        3
      ]
    }
  },
  "checksum": 1040760267
}
```
</details>

2. Memory state json after reboot:
<details>
```json
{
  "policyName": "Static",
  "machineState": {
    "0": {
      "numberOfAssignments": 0,
      "memoryMap": {
        "hugepages-1Gi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "hugepages-2Mi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "memory": {
          "total": 134607716352,
          "systemReserved": 4429185024,
          "allocatable": 130178531328,
          "reserved": 0,
          "free": 130178531328
        }
      },
      "cells": [
        0
      ]
    },
    "1": {
      "numberOfAssignments": 0,
      "memoryMap": {
        "hugepages-1Gi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "hugepages-2Mi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "memory": {
          "total": 135277490176,
          "systemReserved": 4429185024,
          "allocatable": 130848305152,
          "reserved": 0,
          "free": 130848305152
        }
      },
      "cells": [
        1
      ]
    },
    "2": {
      "numberOfAssignments": 0,
      "memoryMap": {
        "hugepages-1Gi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "hugepages-2Mi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "memory": {
          "total": 135277490176,
          "systemReserved": 4429185024,
          "allocatable": 130848305152,
          "reserved": 0,
          "free": 130848305152
        }
      },
      "cells": [
        2
      ]
    },
    "3": {
      "numberOfAssignments": 0,
      "memoryMap": {
        "hugepages-1Gi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "hugepages-2Mi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "memory": {
          "total": 134149668864,
          "systemReserved": 4429185024,
          "allocatable": 129720483840,
          "reserved": 0,
          "free": 129720483840
        }
      },
      "cells": [
        3
      ]
    }
  },
  "checksum": 3935320266
}
```
</details>

We can see total memory of node 0, 1 is unchanged, but node 2, 3 changed while they sum up to a same count.

### What did you expect to happen?

Improve the implementation of `areMemoryStatesEqual`, to allow for numa node total memory change as long as the total summed up memory is consistent (and the current memory state can serve allocated pods?).

### How can we reproduce it (as minimally and precisely as possible)?

1. Prepare a multi numa-node machine where memory of each numa node varies on reboot.
2. Start kubernetes cluster with kubelet memory manager policy to be `Static`.
3. Reboot to see the failure of kubelet.

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/issues/109996#issuecomment-1145929818 says issue described there would be classified as a feature request instead of bug. But I think this is a bug given that Kubernetes v1.32 is [improving memory manager reliability and consistency](https://kubernetes.io/blog/2024/12/13/memory-manager-goes-ga/#improving-memory-manager-reliability-and-consistency):

> The kubelet does not guarantee pod ordering when admitting pods after a restart or reboot.
>
> In certain edge cases, this behavior could cause the memory manager to reject some pods, and in more extreme cases, it may cause kubelet to fail upon restart.
> 
> Previously, the beta implementation lacked certain checks and logic to prevent these issues.
> 
> To stabilize the memory manager for general availability (GA) readiness, small but critical refinements have been made to the algorithm, improving its robustness and handling of edge cases.

And this issue is exactly the edge case that `cause kubelet to fail upon restart`, which should be handed to improve its robustness.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.3
```

</details>

### Cloud provider

Self-host

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux gpu164-master0 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

`kubeadm`, configuration as follows:
<details>
```
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta3

nodeRegistration:
  name: master0
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  taints: [] # Set taints to empty list to avoid control-plane node from being tainted
  kubeletExtraArgs:
    resolv-conf: /run/systemd/resolve/resolv.conf
    system-reserved: cpu=100m,memory=100Mi
    kube-reserved: cpu=607.5m,memory=16696Mi
    cpu-manager-policy: static
    memory-manager-policy: Static
    reserved-memory: 0:memory=4224Mi;1:memory=4224Mi;2:memory=4224Mi;3:memory=4224Mi

localAPIEndpoint:
  advertiseAddress: 10.194.3.15
  bindPort: 6443

bootstrapTokens:
  - token: xvq0og.vyaim43ag7mw45r9

---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3

kubernetesVersion: 1.32.3
clusterName: kubernetes
controlPlaneEndpoint: 10.194.3.14

imageRepository: registry.k8s.io
certificatesDir: /etc/kubernetes/pki
networking:
  podSubnet: 10.240.0.0/12
  serviceSubnet: 10.96.0.0/12
  dnsDomain: cluster.local
apiServer:
  extraArgs:
    service-node-port-range: 10000-65530
    event-ttl: 24h0m0s
  extraVolumes: []
  certSANs: []
  timeoutForControlPlane: 4m0s
controllerManager:
  extraArgs:
    node-cidr-mask-size: "20"
  extraVolumes: []
scheduler:
  extraArgs: {}
  extraVolumes: []
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs: {}
    serverCertSANs: []
    peerCertSANs: []

---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1

cgroupDriver: systemd

clusterDomain: cluster.local
clusterDNS: [10.96.0.10]

featureGates:
  CPUManager: true
  MemoryManager: true
```
</details>
