### ISSUE TITLE
Defined nodePort same for UDP/TCP -- service update does not sync ports.

### ISSUE THREAD

**Issue by bdowling** [kubernetes/kubernetes#131228]
### What happened?

If you change a service manifest to have the same NodePort: and "Update/Apply" to an existing service it will only change 1 of the nodePorts that is on the same port, seems to be the first `ports:` in the list.

If you delete and recreate the service, the duplicate TCP/UDP service accepts the same nodePort.

Server Version: v1.32.1

Ref #91590 

```
[manifests] % kubectl  apply -f k8s-external-coredns-service.yaml
service/k8s-external-coredns configured
[manifests] % kubectl  get svc k8s-external-coredns
NAME                   TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)                                    AGE
k8s-external-coredns   NodePort   10.4.215.193   <none>        53:30054/UDP,53:30054/TCP,9153:30828/TCP   14m
[manifests] % kubectl  apply -f k8s-external-coredns-service.yaml
service/k8s-external-coredns configured
[manifests] % kubectl  get svc k8s-external-coredns
NAME                   TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)                                    AGE
k8s-external-coredns   NodePort   10.4.215.193   <none>        53:30154/UDP,53:30054/TCP,9153:30828/TCP   15m
```

FYI, Additionally while testing the order issue, I noted that if you change the order of the ports: attribute, it also does not accept an update due to the duplicates:
```
% kubectl  apply -f k8s-external-coredns-service.yaml
The Service "k8s-external-coredns" is invalid:
* spec.ports[1].name: Duplicate value: "dns"
* spec.ports[1]: Duplicate value: core.ServicePort{Name:"", Protocol:"UDP", AppProtocol:(*string)(nil), Port:53, TargetPort:intstr.IntOrString{Type:0, IntVal:0, StrVal:""}, NodePort:0}
```

### What did you expect to happen?

The apply/update should take the same as a new creation.

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-dns-k8s-external
    kubernetes.io/name: CoreDNS
  name: k8s-external-coredns
  namespace: kube-system
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
    nodePort: 30054
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
    nodePort: 30054
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: k8s-external-coredns
  sessionAffinity: None

```

### Anything else we need to know?

Non-Critcal, the workaround is just to delete/recreate.  Just reporting for completness.

### Kubernetes version

<details>

```console
Client Version: v1.32.3
Server Version: v1.32.1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI is FLannel
</details>
