### ISSUE TITLE
allowPrivilegeEscalation:false insufficient for privilege escalation prevention

### ISSUE THREAD

**Issue by hkoushik** [kubernetes/kubernetes#131336]
The issue relates to how allowPrivilegeEscalation: false doesn't prevent all forms of privilege escalation through dangerous capabilities. 

When a container's security context sets allowPrivilegeEscalation: false, the current validation only blocks CAP_SYS_ADMIN capability. However, other dangerous capabilities that can also lead to privilege escalation are still allowed.

Technical Details:
1. Current Validation:
   - Blocks: CAP_SYS_ADMIN when allowPrivilegeEscalation: false
   - Allows: CAP_NET_ADMIN, CAP_SYS_MODULE, CAP_SYS_PTRACE, etc.

2. Example:
```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: busybox
    image: busybox
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add: ["CAP_NET_ADMIN", "CAP_SYS_MODULE"]  # This is allowed but can lead to privilege escalation
```

3. Dangerous Capabilities Still Allowed:
   - CAP_NET_ADMIN: Network stack manipulation, potential for network namespace escape
   - CAP_SYS_MODULE: Loading kernel modules
   - CAP_SYS_PTRACE: Process debugging and memory access
   - CAP_DAC_READ_SEARCH: Bypass file permission checks
   - CAP_SYS_RAWIO: Direct I/O access
   - CAP_AUDIT_CONTROL: Audit system manipulation

Impact:
- False sense of security when using allowPrivilegeEscalation: false
- Privilege escalation still possible through allowed capabilities

Proposed Fix:
Extend the validation to block all dangerous capabilities when allowPrivilegeEscalation is set to false.

I’d love to hear your thoughts! Have you run into situations where `allowPrivilegeEscalation: false` didn’t cut it? 
Thanks
