### ISSUE TITLE
NodeResizePending status not removed after successful NodeExpandVolume

### ISSUE THREAD

**Issue by hajiler** [kubernetes/kubernetes#131402]
### What happened?

When resizing a Persistent Disk CSI driver-backed volume, although the node expansion succeeds and the CSI driver completes NodeExpandVolume, the PVC's AllocatedResourceStatus NodeResizePending condition persists.

```
 spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    storageClassName: standard-rwo
    volumeMode: Filesystem
    volumeName: pvc-22d448b9-d98a-46d5-9910-fd2cb0029a7d
  status:
    accessModes:
    - ReadWriteOnce
    allocatedResourceStatuses:
      storage: NodeResizePending
    allocatedResources:
      storage: 15Gi
    capacity:
      storage: 15Gi
    phase: Bound
```

Upon pod restart, the NodeExpandVolume operation successfully resizes the file system.
```
/csi.v1.Node/NodeExpandVolume returned with response: capacity_bytes:16106127360
"NodeExpandVolume succeeded on volume Key{"pvc-8fb88ce1-0feb-47c7-9993-e6bf9d0d64e7", zone: "x"} to size 16106127360"
```
Despite this, node logs show that NodeExpandVolume is failing due to an unidentified error.
```
nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/pd.csi.storage.gke.io^projects/x/zones/x/disks/pvc-8fb88ce1-0feb-47c7-9993-e6bf9d0d64e7 podName: nodeName:}" failed. No retries permitted until 2025-04-18 20:17:09.901667408 +0000 UTC m=+10542.012736234 (durationBeforeRetry 16s). Error: NodeExpandVolume.NodeExpandVolume failed to resize volume for volume "pvc-8fb88ce1-0feb-47c7-9993-e6bf9d0d64e7" (UniqueName: "kubernetes.io/csi/pd.csi.storage.gke.io^projects/x/zones/x/disks/pvc-8fb88ce1-0feb-47c7-9993-e6bf9d0d64e7") pod "pod" (UID: "18e508ae-a670-4486-b993-e6355d0abcff") : volume resizing failed for unknown reason
```
The Kubelet appears to unexpectedly enter a placeholder code path. This issue can be traced to the following lines in the Kubernetes source code: https://github.com/kubernetes/kubernetes/blob/680ea07dbb2c6050d13b93660fa4d27d2d28d6eb/pkg/volume/util/operationexecutor/operation_generator.go#L1921-L1924. 

### What did you expect to happen?

After completion of NodeExpandVolume, we expect that NodeResizePending status is removed.
```
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    storageClassName: standard-rwo
    volumeMode: Filesystem
    volumeName: pvc-8fb88ce1-0feb-47c7-9993-e6bf9d0d64e7
  status:
    accessModes:
    - ReadWriteOnce
    allocatedResources:
      storage: 15Gi
    capacity:
      storage: 15Gi
    phase: Bound
```

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy a GKE cluster with master version `1.32.2-gke.1182003` and one node running version `1.31.6-gke.1020000`.
2. Create a pod that utilizes a `standard-rwo` PersistentVolumeClaim (PVC) with an initial size of 5Gi.
3. After the pod is operational, expand the PVC's storage capacity to 15Gi.
4. Restart the pod.
5. Examine the status of the PVC.

### Anything else we need to know?

The "NodeResizePending" status resolves successfully when the node and cluster versions match at v1.31.6-gke.1020000. This issue seems to arise only when the cluster and node versions are different.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.2-gke.1182003
```
Node version: v1.31.6-gke.1020000
Resizer version: v1.13.1-gke.0
</details>

### Cloud provider

<details>
Google Cloud Platform
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux rodete"
NAME="Debian GNU/Linux rodete"
VERSION_CODENAME=rodete
ID=debian
HOME_URL="https://go/glinux"
SUPPORT_URL="https://go/techstop"
BUG_REPORT_URL="https://go/techstop"
$ uname -a
Linux elijahrb-mt.c.googlers.com 6.12.17-1rodete2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.17-1rodete2 (2025-03-12) x86_64 GNU/Linux


### Install tools

<details>
Google Kubernetes Engine
</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
External resizer: v1.13.1-gke.0
</details>
