### ISSUE TITLE
Pod scheduling failed due to pod anti-affinity.

### ISSUE THREAD

**Issue by Black-max12138** [kubernetes/kubernetes#131467]
### What happened?

The pod is bound to the PVC on the master1 node.However, the current pod is in the pending state.
The log is as follows:
```shell
I0425 08:09:37.487898      25 schedule_one.go:1107] "Unable to schedule pod; no fit; waiting" pod="default/managekvs-1" err="0/14 nodes are available: 1 node(s) didn't match pod anti-affinity rules, 11 node(s) didn't match Pod's node affinity/selector, 2 node(s) had volume node affinity conflict. preemption: 0/14 nodes are available: 1 No preemption victims found for incoming pod, 13 Preemption is not helpful for scheduling."
```
However, when I query the labels of all pods on the node, there is no conflicting label.
```shell
[root@master1 ~]# kubectl get pods --all-namespaces -o wide --field-selector spec.nodeName=master1 --show-labels | grep 'app=managekvs'
[root@master1 ~]# 
```
The pod anti-affinity configuration is as follows:
```yaml
podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - managekvs
    topologyKey: kubernetes.io/hostname
```

### What did you expect to happen?

The pod should be scheduled successfully.

### How can we reproduce it (as minimally and precisely as possible)?

I don't know how it happened.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.31
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
