### ISSUE TITLE
spec.jobTemplate.spec.podFailurePolicy.rules[0].onPodConditions[0].status: Required value: valid values: ["False" "True" "Unknown"]

### ISSUE THREAD

**Issue by devopsmash** [kubernetes/kubernetes#131512]
### What happened?

When I try to apply (patching) an existing `CronJob` with the following `podFailurePolicy`:
```
      podFailurePolicy:
        rules:
        - action: Ignore
          onPodConditions:
          - type: DisruptionTarget
```

I'm getting the following Error:
```
error when patching "/dev/shm/2794561279": CronJob.batch "mycronjob" is invalid: spec.jobTemplate.spec.podFailurePolicy.rules[0].onPodConditions[0].status: Required value: valid values: ["False" "True" "Unknown"]
```

Following the docs ([link1](https://kubernetes.io/blog/2024/08/19/kubernetes-1-31-pod-failure-policy-for-jobs-goes-ga/), [link2](https://kubernetes.io/blog/2024/08/19/kubernetes-1-31-pod-failure-policy-for-jobs-goes-ga/)), it seems to be optional.

same in code(?)

https://github.com/kubernetes/api/blob/c5439348b1cf0e96c7446a1bef9475553530f12f/batch/v1/types.go#L214

### What did you expect to happen?

should be applied without any errors

### How can we reproduce it (as minimally and precisely as possible)?

create a sample cronjob with these configurations: 

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob
  labels:
    app: release-name
    app.kubernetes.io/name: "release-name"
    app.kubernetes.io/instance: "release-name"
    app.kubernetes.io/part-of: mycronjob
spec:
  schedule: "*/10 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 172800 
      backoffLimit: 2
      parallelism: 1
      activeDeadlineSeconds: 1800
      podFailurePolicy:
        rules:
        - action: Ignore
          onPodConditions:
          - type: DisruptionTarget
...
```

### Anything else we need to know?

workaround: adding the field `status: 'True'` fix it

```
    podFailurePolicy:
      rules:
      - action: Ignore
        onPodConditions:
        - type: DisruptionTarget
          status: 'True'
```

### Kubernetes version

<details>

```console
$ kubectl version
v1.31.7-eks-bcf3d70
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
