### ISSUE TITLE
VolumeDevices mappings ignored whhen  /dev is volumeMounted

### ISSUE THREAD

**Issue by eaceaser** [kubernetes/kubernetes#131638]
### What happened?

When the host system's `/dev` is mounted into a container, `volumeDevices` do not appear to get created. 

Even if `/dev` is mounted into a container, it is necessary to be able to map a volume (e.g. a PVC with `volumeMode: Block`) to a known name, because the actual path of the block device in `/dev` may vary.

### What did you expect to happen?

I expect `volumeDevices` to be mapped no matter what other volumes are mounted into the container.

### How can we reproduce it (as minimally and precisely as possible)?

Create a Block PVC:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-gp3
  volumeMode: Block
```

Then create a pod that tries to mount it and /dev:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: debian:bookworm
          name: test
          command:
            - sleep
            - infinity
          volumeMounts:
            - mountPath: /dev
              name: dev
          volumeDevices:
            - devicePath: /disks/test
              name: test
      volumes:
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: test
          persistentVolumeClaim:
            claimName: test

```

And observe that `/disks/test` is not created. If you remove the `/dev` volumeMount, `/disks/test` is created as expected.

### Anything else we need to know?

Seems somewhat similar to https://github.com/kubernetes/kubernetes/issues/85624 but the container being privileged doesn't matter in this case.

### Kubernetes version

<details>

```console
❯ kubectl version
Client Version: v1.32.4
Kustomize Version: v5.5.0
Server Version: v1.32.3-eks-bcf3d70
```

</details>

### Cloud provider

<details>
AWS, using EKS
</details>

### OS version

<details>

```console
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.7.20250414"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/amazon-linux-2023/"
DOCUMENTATION_URL="https://docs.aws.amazon.com/linux/"
SUPPORT_URL="https://aws.amazon.com/premiumsupport/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
VENDOR_NAME="AWS"
VENDOR_URL="https://aws.amazon.com/"
SUPPORT_END="2029-06-30"

Linux 6.1.132-147.221.amzn2023.aarch64 #1 SMP Tue Apr  8 13:14:35 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
> ctr version
Client:
  Version:  1.7.27
  Revision: 05044ec0a9a75232cad458027ca83437aae3f4da
  Go version: go1.23.7

Server:
  Version:  1.7.27
  Revision: 05044ec0a9a75232cad458027ca83437aae3f4da
  UUID: fa952131-14a2-401d-b8f2-4cd0126110ac
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
https://github.com/kubernetes-sigs/aws-ebs-csi-driver - v1.42.0
</details>
