### ISSUE TITLE
cannot delete pod with finalizer and invalid imagePullSecrets

### ISSUE THREAD

**Issue by gblues** [kubernetes/kubernetes#131657]
### What happened?

A `batch/v1:Job` was created that generated a pod with an invalid `.spec.imagePullSecrets` block:

```
metadata:
  finalizers:
  - "batch.kubernetes.io/job-tracking"
spec:
  imagePullSecrets:
    - {}
```

This pod is now stuck in a `ContainerStatusUnknown` state and cannot be deleted.

Conventional wisdom is to delete the finalizer, right? Weeeeeell that busted imagePullSecrets causes that to fail:

```
kubectl patch -n NAMESPACE pod POD_NAME --type='json' -p='[{"op":"remove","path":"/metadata/finalizers/0"}]'
The Pod "POD_NAME" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
  core.PodSpec{
        ... // 11 identical fields
        NodeName:         "NODE_NAME",
        SecurityContext:  &{HostPID: true},
-       ImagePullSecrets: []core.LocalObjectReference{{}},
+       ImagePullSecrets: []core.LocalObjectReference{},
        Hostname:         "",
        Subdomain:        "",
        ... // 18 identical fields
  }
```

I've tried to add an explicit patch that would result in `ImagePullSecrets` not getting modified, but it gets optimized down to `[]core.LocalObjectReference{}` no matter what I do.

I've also tried rolling the node the pod was scheduled for, which did nothing.

The pod was created under EKS 1.31, I have just updated the cluster to 1.32 

### What did you expect to happen?

I expected the finalizer patch to succeed

### How can we reproduce it (as minimally and precisely as possible)?

I'm not looking to create _more_ zombie pods, so I'm not sure this will work.

Note that the `.spec.containers[0].image` being a nonexistent image may be relevant, it's part of why it got into the `ContainerStatusUnknown` state in the first place.

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bad-job-no-donut
  namespace: default
spec:
  template:
    metadata:
      finalizers:
      - "batch.kubernetes.io/job-tracking"
    spec:
      containers:
      - image: nonexistent/image
        name: broken-container
      restartPolicy: Never
      imagePullSecrets:
      - {}
```

### Anything else we need to know?

This is an AWS EKS cluster

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.3-eks-4096722
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
I have no idea what OS the EKS backplane is running on. Probably amazon linux 2. the workers are running amazon linux 2 
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
