### ISSUE TITLE
Set container ready condition to false once liveness probe failed

### ISSUE THREAD

**Issue by caitong93** [kubernetes/kubernetes#131690]
# Problem 

There is a case:
t0: container liveness probe failed, readiness probe still succeed for some reason, kubelet starts to do pre-stop
t1: pre-stop done, kubelet starts to stop container
between t0 and t1, readiness probe didn't failed,  pod is still ready, traffic is forwarded to  the abnormal container.

# Suggestion

Set container ready condition to false once liveness probe failed.

**Comment by ComingCL** [comment]
Liveness probes do not wait for readiness probes to succeed. If you want to wait before executing a liveness probe, you can either define initialDelaySeconds or use a [startup probe](https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/#startup-probe).

The k8s document describes.
https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/

**Comment by caitong93** [comment]
@HirazawaUi 
Thanks for reviewing this issue. I’ve proposed a fix:
In [syncLoopIteration](https://github.com/kubernetes/kubernetes/blob/d4f73b797aa0aad8883dd18dda7325f637fc03b1/pkg/kubelet/kubelet.go#L2575), when handling `case update := <-kl.livenessManager.Updates()` and detecting proberesults.Failure, we could explicitly call SetContainerReadiness to mark the container as not ready. At the same time,  readiness probe should be stopped to prevent it set container readiness back to true.
I’m happy to submit a PR for this if the approach sounds good.

**Comment by caitong93** [comment]
@ComingCL 

Thanks for comment. I think there might be a slight misunderstanding here. My issue isn't about making liveness probes wait for readiness probes, but rather about the container readiness state behavior when liveness probes fail.
In this case, pod is already running and all containers ready, then liveness probe fail.

**Comment by HirazawaUi** [comment]
@caitong93 Could you provide a reproducible example in the description of the current issue? Also, please specify the k8s version you are using (ensuring it is within the supported version range). If you could verify whether this is a regression issue, that would be greatly appreciated, as it is important for us to triage this issue.

/triage needs-information

**Comment by aojea** [comment]
> container readiness state behavior when liveness probes fail.

why? both probes have specific semantics, why liveness probe should become readiness probe too? those are different concepts

**Comment by caitong93** [comment]
> both probes have specific semantics, why liveness probe should become readiness probe too? those are different concepts

@aojea 
Thanks for replying.
I'm not trying to make liveness probe become  readiness probe. My point is that since container is going to be killed after liveness probe failed, kubelet can set container status to false immediately before pre-stop, so that controllers like ingress controller can remove traffic to this container early.
Here is an example:

**manifest**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestop-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestop-example
  template:
    metadata:
      labels:
        app: prestop-example
    spec:
      containers:
      - image: nginx:1.25
        lifecycle:
          preStop:
            exec:
              command:
              - /usr/bin/sleep
              - "20"
        livenessProbe:
          failureThreshold: 3
          exec:
            #  This setting is not actually correct in production, it just simulates the failure scenario.
            command:
            - /usr/bin/test
            - -f
            - /var/run/nginx.pid
          initialDelaySeconds: 15
          periodSeconds: 1
        name: nginx
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
```

k8s version:

```bash
➜  ~ kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.32.2
```

**reproduction steps**

watch events and pod:

```
kubectl get events -w | ts '[%Y-%m-%d %H:%M:%S]'
kubectl get pods -o wide -w | ts '[%Y-%m-%d %H:%M:%S]'
```

trigger health check failure:

```
➜  ~ kubectl exec -it deploy/prestop-example -- bash
root@prestop-example-755dc7446-t6kph:/# rm -f /var/run/nginx.pid
```

observe result:


events

```
[2025-05-19 17:11:52] 0s          Warning   Unhealthy           pod/prestop-example-65f548f69c-pfqb7    Liveness probe failed:
[2025-05-19 17:11:53] 0s          Warning   Unhealthy           pod/prestop-example-65f548f69c-pfqb7    Liveness probe failed:
[2025-05-19 17:11:54] 0s          Warning   Unhealthy           pod/prestop-example-65f548f69c-pfqb7    Liveness probe failed:
[2025-05-19 17:11:54] 0s          Normal    Killing             pod/prestop-example-65f548f69c-pfqb7    Container nginx failed liveness probe, will be restarted
```

pods

```
[2025-05-19 17:11:28] prestop-example-65f548f69c-pfqb7   1/1     Running   0                 14m   10.244.0.10   kind-control-plane   <none>           <none>
[2025-05-19 17:12:15] prestop-example-65f548f69c-pfqb7   0/1     Running   1(1s ago)    15m   10.244.0.10   kind-control-plane   <none>           <none>
```

We can see that liveness probe failed at 17:11:54, and container was ready util 17:12:15. 
We can update readiness probe to cover this case, but it still takes some time.
