### ISSUE TITLE
Kubelet registerWithTaints does not taint the node

### ISSUE THREAD

**Issue by ttc0419** [kubernetes/kubernetes#131666]
### What happened?

Given the following config:
```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt

cgroupDriver: systemd
containerRuntimeEndpoint: unix:///run/containerd/containerd.sock
rotateCertificates: true
serverTLSBootstrap: true

registerWithTaints:
- key: node.kubernetes.io/unschedulable
  effect: NoSchedule
```
Kubelet does not add node.kubernetes.io/unschedulable taint to the node when TLS bootstrapping

### What did you expect to happen?

Node should be tainted with node.kubernetes.io/unschedulable

### How can we reproduce it (as minimally and precisely as possible)?

Follow the TLS Bootstrap process with the kubelet config above.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.33.0
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
