### ISSUE TITLE
topologySpreadConstraints are not correctly applied on StatefulSets

### ISSUE THREAD

**Issue by danibaeyens** [kubernetes/kubernetes#131761]
### What happened?

I'm using AWS EKS 1.31. I was doing some tests with `topologySpreadConstraints` and I've noticed that the API Server behaves differently on `Deployments` and `StatefulSets` objects.

Using this `test.yaml` YAML file:
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-without-enough-replicas-2
spec:
  selector:
    matchLabels:
      app: test
  replicas: 3
  template:
    metadata:
      labels:
        app: test
    spec:
      topologySpreadConstraints:
        - topologyKey: topology.kubernetes.io/zone
          # commented on purpose to trigger a failure
          # whenUnsatisfiable: DoNotSchedule
          maxSkew: 1
          labelSelector:
            matchLabels:
              app: test
      containers:
      - name: echo-server-container
        image: alpine
        command: ["sleep", "3600"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-without-enough-replicas-2
spec:
  selector:
    matchLabels:
      app: test
  replicas: 3
  template:
    metadata:
      labels:
        app: test
    spec:
      topologySpreadConstraints:
        - topologyKey: topology.kubernetes.io/zone
          # commented on purpose to trigger a failure
          # whenUnsatisfiable: DoNotSchedule
          maxSkew: 1
          labelSelector:
            matchLabels:
              app: test
      containers:
      - name: echo-server-container
        image: alpine
        command: ["sleep", "3600"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
```

When applied, I get a different response from both:
```bash
$ kubectl apply -f test.yaml
statefulset.apps/statefulset-without-enough-replicas-2 created
The Deployment "deployment-without-enough-replicas-2" is invalid: spec.template.spec.topologySpreadConstraints[0].whenUnsatisfiable: Unsupported value: "": supported values: "DoNotSchedule", "ScheduleAnyway"
```

After this, the `Deployment` has been rejected, as the fields are missing (correct), but the `StatefulSet` is accepted and unable to schedule pods, because `whenUnsatisfiable` field is missing:
```
Events:
  Type     Reason           Age                  From                    Message
  ----     ------           ----                 ----                    -------
  Warning  FailedCreate     41s (x15 over 2m3s)  statefulset-controller  create Pod statefulset-without-enough-replicas-2-0 in StatefulSet statefulset-without-enough-replicas-2 failed error: Pod "statefulset-without-enough-replicas-2-0" is invalid: spec.topologySpreadConstraints[0].whenUnsatisfiable: Unsupported value: "": supported values: "DoNotSchedule", "ScheduleAnyway"
```

### What did you expect to happen?

I expect the validation should behave similarly in both resources, rejecting the resource which lacks of required fields.

### How can we reproduce it (as minimally and precisely as possible)?

Apply this YAML file:
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-without-enough-replicas-2
spec:
  selector:
    matchLabels:
      app: test
  replicas: 3
  template:
    metadata:
      labels:
        app: test
    spec:
      topologySpreadConstraints:
        - topologyKey: topology.kubernetes.io/zone
          # commented on purpose to trigger a failure
          # whenUnsatisfiable: DoNotSchedule
          maxSkew: 1
          labelSelector:
            matchLabels:
              app: test
      containers:
      - name: echo-server-container
        image: alpine
        command: ["sleep", "3600"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-without-enough-replicas-2
spec:
  selector:
    matchLabels:
      app: test
  replicas: 3
  template:
    metadata:
      labels:
        app: test
    spec:
      topologySpreadConstraints:
        - topologyKey: topology.kubernetes.io/zone
          # commented on purpose to trigger a failure
          # whenUnsatisfiable: DoNotSchedule
          maxSkew: 1
          labelSelector:
            matchLabels:
              app: test
      containers:
      - name: echo-server-container
        image: alpine
        command: ["sleep", "3600"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.7
Kustomize Version: v5.5.0
Server Version: v1.31.7-eks-4096722
```

</details>

### Cloud provider

<details>
AWS EKS
</details>
