### ISSUE TITLE
Add option for mTLS for conversion webhook

### ISSUE THREAD

**Issue by shubham14bajpai** [kubernetes/kubernetes#131810]
### What would you like to be added?

Add a way for kube-apiserver to present client certificate while requesting to a ConversionWebhook. Maybe we add a new entry for ConversionWebhook as well like:

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "<path-to-kubeconfig-file>"
- name: MutatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: WebhookAdmissionConfiguration
    kubeConfigFile: "<path-to-kubeconfig-file>"
- name: ConversionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1
    kind: ConversionWebhookConfiguration
    kubeConfigFile: "<path-to-kubeconfig-file>"
```
And use it while creating a client for ConversionWebhooks.
As the client for all the ConversionWebhooks will be same i.e. kube-apiserver, so it makes sense to keep it in kube-apiserver configuration.

### Why is this needed?

After we implement mTLS between the kube-apiserver and webhooks using the steps mentioned in: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers 

When ConversionWebhook is added to the same server manager as AdmissionWebhooks using `AddToManager`, then conversion webhooks keeps failing for error
```
2025/05/15 18:33:43 http: TLS handshake error from 192.168.128.0:42658: tls: client didn't provide a certificate

```
Suppose we have `conversionReviewVersions: ["v1", "v1beta1"]`. Here the requests for v1 CRDs goes through without any errors as the conversion is not triggered. But when the v1beta1 CRD is applied the ConversionWebhook returns tls errors.

Also going through the code we can confirm that this discrepancy is the cause of errors here:
For AdmissionWebhooks: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/generic/webhook.go#L74 , here the client is created with kubeconfig for client auth.

For ConversionWebhooks: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/conversion/webhook_converter.go#L77 , here the client is created without any client auth.

kube-apiserver as a client should behave in similar way when connecting to the webhook server hosting all 3 enpoints.

Workarounds that were thought of:
1. Use `tls.RequestClientCert` but it defeats the security purpose of introducing authentication in the first place.
2. Run conversion webhooks in a separate server inside the controller instead of re-using the admission webhooks server. This should work in theory but it would be good to consolidate all webhooks in a single server.
