### ISSUE TITLE
Managed fields are not updated when patching or updating the `/scale` subresource for custom resources

### ISSUE THREAD

**Issue by MohammadAlavi1986** [kubernetes/kubernetes#131892]
### What happened?

When updating or patching the `/scale` subresource of a custom resource, the managed field for `specReplicasPath` is not updated as expected. 

### What did you expect to happen?

When updating or patching the `/scale` subresource, the managed field for `specReplicasPath` should be updated to reflect the subresource operation and the field manager used, as is done for built-in resources.

### How can we reproduce it (as minimally and precisely as possible)?

1. **Create a CRD with a scale subresource:**
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mypods.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                replicas:
                  type: integer
            status:
              type: object
              properties:
                scale:
                  type: integer
      subresources:
        status: {}
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
  scope: Namespaced
  names:
    plural: mypods
    singular: mypod
    kind: MyPod
    shortNames:
      - mpo
```
2. **Create a custom resource:**
```sh
kubectl apply --server-side --field-manager m1 -f - <<'EOF'
apiVersion: example.com/v1
kind: MyPod
metadata:
  name: test
spec:
  name: mypod
EOF
```

3. **Update or patch replicas using the `/scale` subresource:**  

   a. Update the `/scale` subresource:
   ```sh
   kubectl scale mypods.example.com test --replicas 2
   # Or via direct API call:
   curl -XPUT -H 'content-type: application/json' \
     'http://localhost:8001/apis/example.com/v1/namespaces/default/mypods/test/scale?fieldManager=m2' \
     -d '{"apiVersion": "autoscaling/v1", "kind": "Scale", "metadata": {"name": "test"}, "spec": {"replicas": 2}}'
   ```
   b. Patch the `/scale` subresource:
   ```sh
   kubectl patch mypods.example.com test --subresource scale --type merge --field-manager m2 -p '{"spec": {"replicas": 2}}'
   # Or via direct API call:
   curl -XPATCH -H 'content-type: application/merge-patch+json' \
     'http://localhost:8001/apis/example.com/v1/namespaces/default/mypods/test/scale?fieldManager=m2' \
     -d '{"spec": {"replicas": 2}}'
   ```

4. **Observe that `spec.replicas` is not in the managed fields:**
    ```sh
    kubectl get mypods.example.com test --show-managed-fields -o yaml
    ```
   Output:
    ```yaml
    apiVersion: example.com/v1
    kind: MyPod
    metadata:
      creationTimestamp: "2025-05-22T00:46:21Z"
      generation: 2
      managedFields:
      - apiVersion: example.com/v1
        fieldsType: FieldsV1
        fieldsV1:
          f:spec:
            f:name: {}
        manager: m1
        operation: Apply
        time: "2025-05-22T00:46:21Z"
      name: test
      namespace: default
      resourceVersion: "49104"
      uid: 87e87c4d-8557-4aaf-a9e4-15794ea8ad5d
    spec:
      name: mypod
      replicas: 2
    ```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.4
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
