### ISSUE TITLE
Kubelet manifest doesn't allow multiple host ports to map to the same internal port

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#13203]
Where the following command

```
docker run -d=true -p 80:8153 -p 443:8154 -p 8154:8154 gocd/gocd-server:15.2.0 /sbin/my_init
```

Results in the following bindings:

```
"PortBindings": {
    "8153/tcp": [
        {
            "HostIp": "",
            "HostPort": "80"
        }
    ],
    "8154/tcp": [
        {
            "HostIp": "",
            "HostPort": "443"
        },
        {
            "HostIp": "",
            "HostPort": "8154"
        }
    ]
}
```
 
Trying to do the same in the kubelet manifest:

```
 ports:
    - name: http
      containerPort: 8153
      hostPort: 80
      protocol: TCP
    - name: https-internal
      containerPort: 8154
      hostPort: 443
      protocol: TCP
    - name: https
      containerPort: 8154
      hostPort: 8154
      protocol: TCP
```

Results in the last port mapping overriding the second one:

```
"PortBindings": {
    "8153/tcp": [
        {
            "HostIp": "",
            "HostPort": "80"
        }
    ],
    "8154/tcp": [
        {
            "HostIp": "",
            "HostPort": "8154"
        }
    ]
}         
```
