### ISSUE TITLE
Service Conflict When Using ClusterIP Port 31000 and NodePort Services Using Same Port

### ISSUE THREAD

**Issue by nagarjundevops89** [kubernetes/kubernetes#132068]
### What happened?

We’re experiencing an intermittent issue when running a Kubernetes service configured with ClusterIP and specifying port 31000. Occasionally, the service becomes inaccessible or fails to function properly.
Upon investigation, we’ve observed this typically happens when another user in the cluster creates a NodePort service that also uses port 31000. It seems there's a conflict at the node level, even though our service is of type ClusterIP.

### What did you expect to happen?

* Kubernetes version: v1.27.16
* Service type: ClusterIP with port 31000
* Observed behavior: Our service randomly fails or becomes inaccessible when others create NodePort services using the same port.
* Expected behavior: ClusterIP services should not conflict with NodePort services even if using the same port, unless explicitly configured to share.

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-nodeport
  name: nginx-nodeport
spec:
  ports:
  - port: 31000
    targetPort: 31000
    protocol: TCP
    nodePort: 31000
  selector:
    app: nginx-nodeport
  type: NodePort 
```

### Anything else we need to know?

Kube-proxy version: kube-proxy:v1.27.16

```
apiVersion: v1
data:
  config: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: /var/lib/kube-proxy/kubeconfig
      qps: 5
    clusterCIDR: 100.96.0.0/11
    configSyncPeriod: 15m0s
    conntrack:
      maxPerCore: 131072
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    enableProfiling: false
    healthzBindAddress: 0.0.0.0:10256
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: "" # rr is the default which is used if nothing is specified. See https://linux.die.net/man/8/ipvsadm
      syncPeriod: 30s
    kind: KubeProxyConfiguration
    metricsBindAddress: 0.0.0.0:10249
    mode: ipvs
    nodePortAddresses: null
    oomScoreAdj: -1000
    portRange: ""
    udpIdleTimeout: 250ms
```

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.16", GitCommit:"cbb86e0d7f4a049666fac0551e8b02ef3d6c3d9a", GitTreeState:"clean", BuildDate:"2024-07-17T01:53:56Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.16", GitCommit:"cbb86e0d7f4a049666fac0551e8b02ef3d6c3d9a", GitTreeState:"clean", BuildDate:"2024-07-17T01:44:26Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2026-06-30"

$ uname -a
Linux ip-10-XX-YY-4.eu-west-1.compute.internal 5.10.236-227.928.amzn2.aarch64 #1 SMP Sat Apr 19 16:55:31 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
