### ISSUE TITLE
Unexpected Pod creation delay after recreating Jobs with same names

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#132042]
### What happened?

Pod creations are delayed for up to 10 minutes after creating a Job, which is previously deleted as well as its pods in foreground deletion.

I noticed this case while using [jobset](https://github.com/kubernetes-sigs/jobset), which when notices a pod failure, it deletes all Jobs and Pods (controlled by jobset spec) then creates new Jobs with same names. After creation of new jobs, I found some Jobs had no Pods. I observed the following logs:

```
"enqueueing job" logger="job-controller" key="default/base-100-workers-0" delay="0"
"enqueueing job" logger="job-controller" key="default/base-100-workers-0" delay="9m35.78848664s"
```

### What did you expect to happen?

Since jobs are newly created, there should no delays in creating their pods.

### How can we reproduce it (as minimally and precisely as possible)?

1. setup a k8s cluster with a few nodes
2. install jobset
3. apply below jobset

```
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool
  name: base-100
  namespace: default
spec:
  failurePolicy:
    maxRestarts: 2000
    restartStrategy: Recreate
  network:
    enableDNSHostnames: true
    publishNotReadyAddresses: true
  replicatedJobs:
  - name: workers
    replicas: 4
    template:
      metadata: {}
      spec:
        backoffLimit: 0
        completionMode: Indexed
        completions: 30
        parallelism: 30
        template:
          metadata: {}
          spec:
            containers:
            - name: pi
              image: busybox
              command: ["sh",  "-c", "sleep 10 && exit 10"]
              resources: {}
            restartPolicy: Never
            terminationGracePeriodSeconds: 0
```

You should see the delays in pod creation or similar logs from job controller.

### Anything else we need to know?

Those setup creates a JobSet and since the Pods fails after running for a few seconds, the JobSet controller deletes all 4 Jobs and Pods, then create 4 new Jobs with the same names. For example, base-100-workers-[0|1|2|3] and keys used in the [queue](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L592) and [podBackoffStore](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L912) are identical if job names are the same.

The bug is likely caused by the race condition:

* t0: job0 (v0) is created
* t1: pods of job0 are created and running
* t2: pods fail and job controller records a backoff record with key default/job0 due the to non-zero number of failed Pods
* t3: job0 and pods are deleted by Jobset controller, deletion events are not yet processed by job controller
* t4: job0 (v1) is created
* t5: job0 creation event is processed by job controller and syncJob() [gets the backoffRecord](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L912) with key default/job0, which is old record from previous job
* t6: job controller gets non-zero remainingTime in [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L1709) so it enqueues the job0 task again to delay the pod creation

It appears to me that we need to use a better key in backoffRecordStore to fix this bug or strictly guarantee the sequence of processing Job/Pod events, which will delete the old records from backoffRecordStore.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
