### ISSUE TITLE
API can be streamlined: assume same key for some `EnvVarSource`

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#132195]
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2376

All `EnvVarSource` must specify `name` in the parent, but the `ConfigMapKeyRef` and `SecretKeyRef` fields both require a `key` to spe specified.  https://github.com/kubernetes/enhancements/pull/5384 introduces another case.

It seems like we could assume the env var's name if the key is not specified.  One less line of YAML in many cases.

It would require a feature gate which means a (small) KEP.

**Comment by kei01234kei** [comment]
> It seems like we could assume the env var's name if the key is not specified.

Is this assumption always valid?
Looking at the documentation specified [here](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-a-container-environment-variable-with-data-from-a-single-secret), environment variable names are typically in UPPERCASE, but the keys in secretRef are in lowercase.

Given that the convention is to define environment variables in uppercase while secretRef keys are typically in lowercase, we might not be able to assume the env var's name from the key of the SecretKeyRef due to this case mismatch.

**Comment by kei01234kei** [comment]
If the env var's source is a .env file, we can assume that the key of the fileKeyRef is the env var's name. However, I think this assumption cannot be applied to ConfigMapKeyRef and SecretKeyRef.

**Comment by thockin** [comment]
I'm not saying they HAVE TO be the same, but if someone leaves off the key, maybe we can infer?  It's completely opt-in.

Truthfully I don't know how valuable this is for anything but .env files.

**Comment by Priyankasaggu11929** [comment]
Hello @thockin,

@jasonbraganza and I want to work on writing the required small KEP for this issue.

We'll be using the next 2 weeks to go through the linked pointers (thanks for providing them), to get a foundational understanding of what's needed to implement the ask. 

And then come back and assign the issue to us + ask all our doubts and questions.

PS: we're new. But we just finished going through the [KEP 4369](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4369-allow-special-characters-environment-variable) implementation (alpha -> GA) and we'll be using the foundational learning we gathered from there to proceed with this issue.

**Comment by ekam-walia** [comment]
Hi there, I really want to contribute to Kubernetes but i don't know anything about it, can you please help me go into the right direction and so that I start contributing in Kubernetes.
Thanks,
Regards

**Comment by jasonbraganza** [comment]
Hello 👋🏿  
Here is our (@Priyankasaggu11929 and mine) understanding of what is needed in the issue.

We need the ability to skip the `env[i].valueFrom.*KeyRef.key` field such that it falls back to the value of the parent name (i.e. defaults to `env[i].name` for the key/value lookup).

Note: This is for scenarios where the user ***is*** specifying the env parent name (`env[i].name`) to be same as the key (`env[i].valueFrom.*KeyRef.key`) present in the `*EnvFromSource`

Below are portions of various spec files.
So, as an example, what we are looking to do in the first code snippet, is to have the ability to skip writing `key: SECRET_USERNAME`  (save a line of yaml as the issue suggests) and just use value of the top level name: field (i.e. `SECRET_USERNAME`) as the default value for `key` in `secretKeyRef`


```yaml
env:
  - name: SECRET_USERNAME
    valueFrom:
       secretKeyRef:
          name: backend-user
          key: SECRET_USERNAME
```
---
```yaml
env:
  - name: SPECIAL_LEVEL_KEY
    valueFrom:
      configMapKeyRef:
        # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
        name: special-config
        # Specify the key associated with the value
        key: SPECIAL_LEVEL_KEY
```
---
```yaml
env:
  - name: MY_JWT
    fileKeyRef:
      path: /env
      key: MY_JWT
```



Our understanding is, we’ll perform such defaulting behaviour for the `env[i].valueFrom.*KeyRef.key` in function [`makeEnvironmentVariables()`](https://github.com/kubernetes/kubernetes/blob/7f4f1c29a97de6712d341bf3d724fb122c828772/pkg/kubelet/kubelet_pods.go#L710C6-L711)

Something in this logic:
https://github.com/kubernetes/kubernetes/blob/7f4f1c29a97de6712d341bf3d724fb122c828772/pkg/kubelet/kubelet_pods.go#L844-L900 

Also adjust the corresponding validation logic here:
https://github.com/kubernetes/kubernetes/blob/9e204ba03c2c95fd20dd18fcc6c40c3b16576592/pkg/apis/core/validation/validation.go#L2866-L2900 

@thockin, could you please review the above, and confirm if what we have stated/understood is the correct requirement for the KEP? 
We’ll workout a POC and start writing accordingly the KEP. Thank you!
