### ISSUE TITLE
Job status.conditions behavior change 1.31 -> 1.32

### ISSUE THREAD

**Issue by jb-metzger** [kubernetes/kubernetes#132144]
### What happened?

In version 1.32.0 apply job with `spec.completions=0` and `spec.suspend=true`:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: suspended-zero-completions 
  namespace: default
spec:
  completions: 0
  suspend: true
  template:
    spec:
      containers: 
      - name: noop
        image: busybox
        command: ["true"] 
      restartPolicy: Never
```
Job ends up with conditions:
```
  status:
    conditions:
    - lastProbeTime: "2025-06-06T09:44:17Z"
      lastTransitionTime: "2025-06-06T09:44:17Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: SuccessCriteriaMet
``` 
and STATUS=Running
```
NAME                         STATUS    COMPLETIONS   DURATION   AGE
suspended-zero-completions   Running   0/0                      2s
```

### What did you expect to happen?

To have the same behavior as with version 1.31.9 when applying same job. 
That is expecting following conditions:
```
status:
    completionTime: "2025-06-06T09:40:50Z"
    conditions:
    - lastProbeTime: "2025-06-06T09:40:50Z"
      lastTransitionTime: "2025-06-06T09:40:50Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: SuccessCriteriaMet
    - lastProbeTime: "2025-06-06T09:40:50Z"
      lastTransitionTime: "2025-06-06T09:40:50Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: Complete
```
and STATUS=Complete
```
NAME                         STATUS     COMPLETIONS   DURATION   AGE
suspended-zero-completions   Complete   0/0                      11m
```

### How can we reproduce it (as minimally and precisely as possible)?

Apply job provided above to version 1.31 and version 1.32 and observe difference.

### Anything else we need to know?

If this is an intended change have release notes mention the change in behavior.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.32.0+k3s1
```

</details>

### Cloud provider

<details>
Irrelevant, core component.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kannon92** [comment]
cc @tenzen-y @mimowo 

I think this may be because of SuccessPolicy feature.

**Comment by mimowo** [comment]
Seeing (2s) here:
```
NAME                         STATUS    COMPLETIONS   DURATION   AGE
suspended-zero-completions   Running   0/0                      2s
```
I assume the job is still "Running", because some pods are still terminating.

Since 1.31 Kubernetes adds conditions which indicate the fate of the Job (SuccessCriteriaMet or FailureTarget), but awaits with adding the terminal conditions (Complete, Failed) until all Pods are fully terminated.

This was stated in the release note for [1.31](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.31.md):
```
Delay setting terminal Job conditions until all pods are terminal.

Additionally, the FailureTarget condition is also added to the Job object in the first Job
status update as soon as the failure conditions are met (backoffLimit is exceeded, maxFailedIndexes, 
or activeDeadlineSeconds is exceeded).

Similarly, the SuccessCriteriaMet condition is added in the first update as soon as the expected number
of pod completions is reached.

Also, introduce the following validation rules for Job status when JobManagedBy is enabled:
1. the count of ready pods is less or equal than active
2. when transitioning to terminal phase for Job, the number of terminating pods is 0
3. terminal Job conditions (Failed and Complete) should be preceded by adding the corresponding interim conditions: FailureTarget and SuccessCriteriaMet
```
If you can confirm the Job eventually obtains the terminal condition, then this is WAI.

**Comment by tenzen-y** [comment]
@kannon92 Thank you for pointing me.
As @mimowo mentioned above, I believe that this is expected behavior.
As we discussed in https://github.com/kubernetes/kubernetes/issues/123775, we had problems with capacities and quota management. The in-flight conditions (SuccessCriteriaMet / FailureTarget) allows them to report the fact that terminating Pods are still grabbing computing resources. After computing resources are completely freed (Pods finished), the Job can retrieve the completion conditions (`Complete` / `Failed`)

**Comment by ali-a-a** [comment]
I tested the same job and the behavior between v1.31 and v1.32 is different when `spec.completions` is 0 and `spec.suspend` is true.

This is the output for v1.31:

```bash
NAME                         STATUS     COMPLETIONS   DURATION   AGE
suspended-zero-completions   Complete   0/0           0s         3m31s
```

There are no pods created as expected, and the job status is updated to `Complete` right away.

For v1.32, it stays in a running state with no pods created.

```bash
NAME                         STATUS    COMPLETIONS   DURATION   AGE
suspended-zero-completions   Running   0/0                      10m
```

I looked at the controller logs, and for v1.32, we have this error:

```
E0610 00:44:48.650216       1 job_controller.go:631] "Unhandled Error" err="syncing job: tracking status: removing uncounted pods from status: Job.batch \"suspended-zero-completions\" is invalid: status.startTime: Required value: startTime is required for finished job" logger="UnhandledError"
```

Which means that the job is completed (as the completion count is zero out of zero), but the start time is not set (as the job is suspended). It seems that because of this error, the status of the job cannot be updated to `Complete`.

My question is why do we allow the creation of jobs with `completions=0`? In the documentation we clearly indicate that this value is a non-zero positive.

**Comment by tenzen-y** [comment]
@ali-a-a Thank you for the great insight.

> In the documentation we clearly indicate that this value is a non-zero positive.

Could you point the place where they mention the specifications? As I checked the documentation and API comments, I could not find the non-zero specifications to Job, while Parallel Job has non-zero completions specifications: https://kubernetes.io/docs/concepts/workloads/controllers/job/#parallel-jobs

**Comment by mimowo** [comment]
> I tested the same job and the behavior between v1.31 and v1.32 is different when spec.completions is 0 and spec.suspend is true.

@ali-a-a thank you for testing. I completely missed this was for completions=0 and suspend=0. This makes sense now.

> My question is why do we allow the creation of jobs with completions=0?

That's a good question. A job with `completions=0` would not run any Pods in any case. @jb-metzger do you have any use-case for this setup?

**Comment by mimowo** [comment]
The options I see:
1. strengthen Job validation to prevent setting `completions=0`
2. relax Job validation to do not reject setting "Complete" condition when there is no `status.startTime` when completions=0 and suspend=true
3.  update Job controller to ensure it sets startTime whenever it wants to set the Complete condition, probably around [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L1509) 

I would be leaning to (3.) because. Strengthening validation (1.) is always hard, you never know what use cases people have. For example one that comes to my mind is just to trigger JobTemplate validation and defaulting without creating Pods (so that later the JobTemplate can be safely used with completions > 0). (2.) seems more work than (3.) .

cc @atiratree @soltysh wdyt?

EDIT: there is also option (4.) keep as is, because this a corner case without too bad consequences. However, the very fact that the Job controller produces updates inconsistent with validation makes me think we should fix it with (3.).

**Comment by tenzen-y** [comment]
> The options I see:
> 
> 1. strengthen Job validation to prevent setting `completions=0`
> 2. relax Job validation to do not reject setting "Complete" condition when there is no `status.startTime` when completions=0 and suspend=true
> 3. update Job controller to ensure it sets startTime whenever it wants to set the Complete condition, probably around [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L1509)
> 
> I would be leaning to (3.) because. Strengthening validation (1.) is always hard, you never know what use cases people have. For example one that comes to my mind is just to trigger JobTemplate validation and defaulting without creating Pods (so that later the JobTemplate can be safely used with completions > 0). (2.) seems more work than (3.) .
> 
> cc [@atiratree](https://github.com/atiratree) [@soltysh](https://github.com/soltysh) wdyt?
> 
> EDIT: there is also option (4.) keep as is, because this a corner case without too bad consequences. However, the very fact that the Job controller produces updates inconsistent with validation makes me think we should fix it with (3.).

I agree with (1) is a bit hard. TBH, I'm with (2) since it seems that it does not occur additional corner case. But, I agree with (2) might be a bit ad hoc patch.

IIUC, (3) will add the complete time to startTime, right? In that case, it looks weird the from user's PoV.

**Comment by mimowo** [comment]
> IIUC, (3) will add the complete time to startTime, right?

I didn't mean "add", but set both along, just to make sure "startTime" is set whenever we set "completionTime", updating code [here](https://github.com/kubernetes/kubernetes/blob/da502386e53c1be6d476af8352337d82deb470aa/pkg/controller/job/job_controller.go#L1509-L1511):
```golang
if finishedCond.Type == batch.JobComplete {
	job.Status.CompletionTime = &finishedCond.LastTransitionTime
	job.Status.StartTime = ptr.Deref(job.Status.StartTime , *job.Status.CompletionTime) // extra line
}
```

**Comment by tenzen-y** [comment]
> > IIUC, (3) will add the complete time to startTime, right?
> 
> I didn't mean "add", but set both along, just to make sure "startTime" is set whenever we set "completionTime", updating code [here](https://github.com/kubernetes/kubernetes/blob/da502386e53c1be6d476af8352337d82deb470aa/pkg/controller/job/job_controller.go#L1509-L1511):
> 
> if finishedCond.Type == batch.JobComplete {
> 	job.Status.CompletionTime = &finishedCond.LastTransitionTime
> 	job.Status.StartTime = ptr.Deref(job.Status.StartTime , *job.Status.CompletionTime) // extra line
> }

Yes, that's what I meant. In that case, `startTime` could have `completionTime`. Isn't it weird since it's not "start" time?

**Comment by mimowo** [comment]
Well, it is a bit, but so is setting  "CompletionTime" without "StartTime", imo. 

Looking at the validation rules (2.) will be more difficult, and thus risky fix, than to implement (3.).

**Comment by dejanzele** [comment]
I have some spare cycles to assist.

After discussing with @mimowo, I could submit an integration test which reproduces it, and take it from there depending on the approach which will be agreed.

**Comment by ali-a-a** [comment]
> As I checked the documentation and API comments, I could not find the non-zero specifications to Job, while Parallel Job has non-zero completions specifications

Yeah I think what I saw before was only for Parallel jobs. Still, I think it could have been added to the doc.

> The options I see:
> 
> 1. strengthen Job validation to prevent setting `completions=0`
> 2. relax Job validation to do not reject setting "Complete" condition when there is no `status.startTime` when completions=0 and suspend=true
> 3. update Job controller to ensure it sets startTime whenever it wants to set the Complete condition, probably around [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L1509)
> 
> I would be leaning to (3.) because. Strengthening validation (1.) is always hard, you never know what use cases people have. For example one that comes to my mind is just to trigger JobTemplate validation and defaulting without creating Pods (so that later the JobTemplate can be safely used with completions > 0). (2.) seems more work than (3.) .

(3.) makes sense but it is a bit strange to set the startTime and completeTime together :?

Another option that makes more sense to me is to set the startTime when we do it normally:

https://github.com/kubernetes/kubernetes/blob/1a200abf92ac69abc468c48fb727f76ab9568d6a/pkg/controller/job/job_controller.go#L913-L916

It can be something like this:

```go
if job.Status.StartTime == nil {
	if !jobSuspended(&job) || (job.Spec.Completions != nil && *job.Spec.Completions == 0) {
		now := metav1.NewTime(jm.clock.Now())
		job.Status.StartTime = &now
	}
}
```

Meaning that the startTime of the job should be set if the job is not suspended or it is already completed.

**Comment by jb-metzger** [comment]
@mimowo my setup uses fluxcd with [`dependsOn` and `wait`](https://fluxcd.io/flux/components/kustomize/kustomizations/#wait) for a Kustomization object. This means the Kustomization waits till all resources managed by it are in ready state to signal the Kustomization is ready. The setup broke when the cluster was upgraded from 1.31 to 1.32. The job was "stuck" in the Running state and so flux wasn't proceeding further to the next Kustomization.

Since I didn't see any mention of this breaking change I submitted the issue since kubernetes has a strict policy on deprecations as far as I know. Maybe others have the same problem.

In any case I'm changing my setup a bit so it doesn't rely on the job's status.

**Comment by mimowo** [comment]
I have opened the fix PR https://github.com/kubernetes/kubernetes/pull/132614. PTAL

**Comment by tenzen-y** [comment]
It looks like Michal is working on this issue.

/assign @mimowo

**Comment by mimowo** [comment]
@jb-metzger would you be able to test / confirm the [PR](https://github.com/kubernetes/kubernetes/pull/132614) fixes the issue e2e? It could help us to support backporting, see [comment](https://github.com/kubernetes/kubernetes/pull/132614#issuecomment-3025038826).

**Comment by mimowo** [comment]
I've opened the cherry-picks:
- [1.33](https://github.com/kubernetes/kubernetes/pull/132728)
- [1.32](https://github.com/kubernetes/kubernetes/pull/132727)

**Comment by mimowo** [comment]
I have tested the fix myself on a kind cluster using the Job spec from the issue description, the status is as expected:

```yaml
  status:
    completionTime: "2025-07-04T15:38:17Z"
    conditions:
    - lastProbeTime: "2025-07-04T15:38:17Z"
      lastTransitionTime: "2025-07-04T15:38:17Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: SuccessCriteriaMet
    - lastProbeTime: "2025-07-04T15:38:17Z"
      lastTransitionTime: "2025-07-04T15:38:17Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: Complete
    ready: 0
    terminating: 0
    uncountedTerminatedPods: {}
```
I also tested the analogous Job by "Indexed" and it passed too.
