### ISSUE TITLE
StatefulSet volumeClaimTemplates not validated when creating

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#132211]
### What happened?

When creating StatefulSet by yaml (volumeClaimTemplates has no accessModes), got error:
```
Warning  FailedCreate  4s (x12 over 15s)  statefulset-controller  create Pod nginx-sts-0 in StatefulSet nginx-sts failed error: failed to create PVC data-nginx-sts-0: PersistentVolumeClaim "data-nginx-sts-0" is invalid: spec.accessModes: Required value: at least 1 access mode is required
``` 

### What did you expect to happen?

Add StatefulSet volumeClaimTemplates validation when creating.

### How can we reproduce it (as minimally and precisely as possible)?

Apply this yaml, will reproduce.
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
#        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
```

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.32.1
```

</details>
