### ISSUE TITLE
ValidatingAdmissionPolicy does not get all groups membership information

### ISSUE THREAD

**Issue by rubroboletus** [kubernetes/kubernetes#132202]
### What happened?

I wrote a ValidatingAdmissionPolicy policy for controlling access to specific configmap resource with exceptions for several groups (cluster-admin, ...). But policy is failing and blocking resources. Policy itself:
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: disallow-mmb-ing-cm-modify
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: mbid.cz/v1
    kind: PolicyConfiguration
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["*"]
      resources: ["configmaps"]
      resourceNames: ["mmb-ing-map"]
      operations: ["CREATE","UPDATE"]
  matchConditions:
    - name: exclude-namespace-from-list
      expression: '!(params.spec.?excludes.orValue([]).exists_one(excl, excl.RuleName=="disallow-mmb-ing-cm-modify" && excl.?Namespaces.orValue([]).exists(prefix, object.metadata.namespace.startsWith(prefix))))'
    - name: exclude-groups-from-list
      expression: '!(params.spec.?excludes.orValue([]).exists_one(excl, excl.RuleName=="disallow-mmb-ing-cm-modify" && excl.?Groups.orValue([]).exists(grupa, grupa in request.userInfo.groups)))'
    - name: exclude-userss-from-list
      expression: '!(params.spec.?excludes.orValue([]).exists_one(excl, excl.RuleName=="disallow-mmb-ing-cm-modify" && excl.?Userss.orValue([]).exists(user, user==request.userInfo.username)))'
  validations:
    - expression: "false"
      message: "Changing mmb ingress settings is not allowed."
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: disallow-mmb-ing-cm-modify
spec:
  policyName: disallow-mmb-ing-cm-modify
  validationActions: [Deny,Audit]
  paramRef:
    name: default
    parameterNotFoundAction: Allow
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: mmb_policies_exclude_all
        operator: NotIn
        values:
        - excluded
```
section from customresource PolicyConfiguration:
```
  - RuleName: disallow-mmb-ing-cm-modify
    Groups:
    - "system:masters"
    - cluster-admin
    - system:controller:namespace-controller
    Users:
    - "system:serviceaccount:cicd-jenkins:jenkins-admin"
    - "system:serviceaccount:kube-system:namespace-controller"
```
message from audit log, where you can see, that not all groups of serviceaccount used to create this configmap was reported to apiserver:
```
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "Metadata",
  "auditID": "3527bc2c-7366-4149-850e-75decfb410d0",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/pricemaps-dev-97/configmaps?fieldManager=kubectl-client-side-apply&fieldValidation=Strict",
  "verb": "create",
  "user": {
    "username": "system:serviceaccount:pricemaps-dev-97:mmb-pricemaps-ca-c6bw4zd2bp0f2jwzq93m",
    "uid": "188ba9ec-0037-4d6c-89ef-447c723039fe",
    "groups": [
      "system:serviceaccounts",
      "system:serviceaccounts:pricemaps-dev-97",
      "system:authenticated"
    ],
    "extra": {
      "authentication.kubernetes.io/credential-id": [
        "JTI=76cd9824-6771-4cf7-9a10-fb5e9b1bc7ee"
      ]
    }
  },
  "sourceIPs": [
    "10.66.9.62"
  ],
  "userAgent": "kubectl/v1.33.1 (linux/amd64) kubernetes/8adc0f0",
  "objectRef": {
    "resource": "configmaps",
    "namespace": "pricemaps-dev-97",
    "name": "mmb-ing-map",
    "apiVersion": "v1"
  },
  "responseStatus": {
    "metadata": {},
    "status": "Failure",
    "message": "configmaps \"mmb-ing-map\" is forbidden: ValidatingAdmissionPolicy disallow-mmb-ing-cm-modify with binding disallow-mmb-ing-cm-modify denied request: Changing mmb ingress settings is not allowed.",
    "reason": "Invalid",
    "details": {
      "name": "mmb-ing-map",
      "kind": "configmaps",
      "causes": [
        {
          "message": "ValidatingAdmissionPolicy disallow-mmb-ing-cm-modify with binding disallow-mmb-ing-cm-modify denied request: Changing mmb ingress settings is not allowed."
        }
      ]
    },
    "code": 422
  },
  "requestReceivedTimestamp": "2025-06-10T06:58:12.324618Z",
  "stageTimestamp": "2025-06-10T06:58:12.326449Z",
  "annotations": {
    "authorization.k8s.io/decision": "allow",
    "authorization.k8s.io/reason": "RBAC: allowed by RoleBinding \"mmb-pricemaps-ca-c6bw4zd2bp0f2jwzq93m/pricemaps-dev-97\" of ClusterRole \"cluster-admin\" to ServiceAccount \"mmb-pricemaps-ca-c6bw4zd2bp0f2jwzq93m/pricemaps-dev-97\"",
    "validation.policy.admission.k8s.io/validation_failure": "[{\"message\":\"Changing mmb ingress settings is not allowed.\",\"policy\":\"disallow-mmb-ing-cm-modify\",\"binding\":\"disallow-mmb-ing-cm-modify\",\"expressionIndex\":0,\"validationActions\":[\"Deny\",\"Audit\"]}]"
  }
}
```

but in annotations is visible, that the serviceaccount has roleBinding to clusterRole named "cluster-admin". It is bound using this RoleBinding:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mmb-pricemaps-ca-c6bw4zd2bp0f2jwzq93m
  namespace: pricemaps-dev-97
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: mmb-pricemaps-ca-c6bw4zd2bp0f2jwzq93m
  namespace: pricemaps-dev-97
```

### What did you expect to happen?

Expected is, that this policy will see, that SA is in cluster-admin group and will skip this policy based on the matchConditions section, condition
'!(params.spec.?excludes.orValue([]).exists_one(excl, excl.RuleName=="disallow-mmb-ing-cm-modify" && excl.?Groups.orValue([]).exists(grupa, grupa in request.userInfo.groups)))'

### How can we reproduce it (as minimally and precisely as possible)?

using manifests pasted in first part

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.33.1-eks-7308294
```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

not important for this case

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
