### ISSUE TITLE
IPAddressWrongReference when creating an existing service

### ISSUE THREAD

**Issue by liubog2008** [kubernetes/kubernetes#132321]
### What happened?

POST an existing service. A new ip address will be created and then cleaned up.

```
2m39s   Warning   IPAddressWrongReference   ipaddress/10.96.77.125    IPAddress: 10.96.77.125 for Service default/kubernetes has a wrong reference; cleaning up
```

### What did you expect to happen?

No new ip address being created.

### How can we reproduce it (as minimally and precisely as possible)?

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
EOF
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.33.1
```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
