### ISSUE TITLE
Kubectl returns error when creating CRs if CRD scope has changed

### ISSUE THREAD

**Issue by northbymidwest** [kubernetes/kubernetes#132437]
### What happened?

1. I created a namespace-scoped CRD.
2. I created a CR based on this CRD.
3. I deleted the CRD
4. I created an nearly identical CRD differing only in that it was cluster-scoped
5. I tried creating a CR based on the new CRD and got the following error:
```
Error from server (NotFound): error when creating "manifest-ns.yml": the server could not find the requested resource (post testdefs.test.test)
```

### What did you expect to happen?

I expected the CR to be created

### How can we reproduce it (as minimally and precisely as possible)?

```console
kubectl create -f crd-ns.yaml
kubectl create -f cr-ns.yaml
kubectl delete crd testdefs.test.test
kubectl create -f crd-clus.yaml
kubectl create -f cr-clus.yaml
```
The last `kubectl` invocation will return 
```
Error from server (NotFound): error when creating "cr-clus.yaml": the server could not find the requested resource (post testdefs.test.test)
```

### Resource Defs
NS-CRD:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testdefs.test.test
spec:
  group: test.test
  names:
    kind: TestDef
    listKind: TestDefList
    plural: testdefs
    singular: testdef
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              number:
                type: integer
    served: true
    storage: true
    subresources:
      status: {}
```
NS-CR
```
apiVersion: test.test/v1alpha1
kind: TestDef
metadata:
  name: test-ns
  namespace: crd-test
spec:
  number: 1
```
Culs-CRD
```

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testdefs.test.test
spec:
  group: test.test
  names:
    kind: TestDef
    listKind: TestDefList
    plural: testdefs
    singular: testdef
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              number:
                type: integer
    served: true
    storage: true
    subresources:
      status: {}
```
Clus-CR
```
apiVersion: test.test/v1alpha1
kind: TestDef
metadata:
  name: test-clus
spec:
  number: 1
```

### Anything else we need to know?

If you attempt to create a resource in a nonexistent api-group after creating the second CRD e.g.
```
apiVersion: test-bad.test/v1alpha1
kind: TestDef
metadata:
  name: test-clus
spec:
  number: 1
```
 The subsequent creation of the actual CR will succeed.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.31.5+k3s1
```

</details>

### Cloud provider

Originally identified on AWS EKS but I reproduced it locally on k3d

### OS version

<details>

```console
Darwin J9TVKJTF3H 24.5.0 Darwin Kernel Version 24.5.0: Tue Apr 22 19:54:29 PDT 2025; root:xnu-11417.121.6~2/RELEASE_ARM64_T6030 arm64 arm Darwin
```

</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
Docker version 28.1.1, build 4eba377
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>
