### ISSUE TITLE
Cannot specify xfs for local-storage

### ISSUE THREAD

**Issue by sergey-safarov** [kubernetes/kubernetes#132597]
### What happened?

I have configured storage class with `fsType: xfs`
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: xfs
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  fsType: xfs
```
Specified PersistentVolume
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
spec:
  capacity:
    storage: 300Mi
  accessModes:
  - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: xfs
  local:
    path: /dev/volgroup/my-lv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example.com
```
And specified PersistentVolumeClaim
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-db
spec:
  storageClassName: xfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 200Mi
  volumeName: pv-db
```

I have also created an LVM block device `/dev/volgroup/my-lv` and formatted it with `xfs` filesystem.
When starting pod I see

>   Warning  FailedMount  6s  kubelet  MountVolume.MountDevice failed for volume "pv-db" : local: failed to mount device /dev/volgroup/my-lv at /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/pv-db (fstype: ext4), error mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/pv-db --scope -- mount -t ext4 -o defaults /dev/volgroup/my-lv /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/pv-db
Output: Running as unit: run-p11617-i11917.scope; invocation ID: 75fcf1fa8e3c44f6b61e1b6bb4e9d8c9
mount: /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/pv-db: wrong fs type, bad option, bad superblock on /dev/mapper/volgroup-my--lv, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.

It looks like `local-storage` does not support `fsType` param. Could it be added like for other storage types.

### What did you expect to happen?

I fant mount block device with xfs filesystem as volume into pod.

### How can we reproduce it (as minimally and precisely as possible)?

yaml files provided above

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.2
Kustomize Version: v5.6.0
Server Version: v1.33.2
```

</details>

### Cloud provider

<details>
bare metal server
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 13 (trixie)"
NAME="Debian GNU/Linux"
VERSION_ID="13"
VERSION="13 (trixie)"
VERSION_CODENAME=trixie
DEBIAN_VERSION_FULL=13.0
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux srv0.anycast-lb.net 6.12.33+deb13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.33-1 (2025-06-19) x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
cri-0 v1.33
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
cilium
</details>

**Comment by sushmitha37** [comment]
Hi @sergey-safarov ,
The issue is that local PVs don’t use fsType from the StorageClass. Instead, you need to set fsType directly in your PersistentVolume spec. Your PV should look like this:

local:
  path: /dev/volgroup/my-lv
  fsType: xfs
This ensures the kubelet mounts your XFS-formatted disk correctly. Let me know if you need help updating your YAML.

**Comment by sergey-safarov** [comment]
Thanks @sushmitha37 for clarification. It is forks for me.
Full snipet looks like
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOncePod
  capacity:
    storage: 300Mi
  local:
    path: /dev/volgroup/my-lv
    fsType: xfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example.com
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-db
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 200Mi
  volumeName: pv-db
---
```
