### ISSUE TITLE
[PodLevelResources] Update Downward API defaulting logic for `resource.limits`

### ISSUE THREAD

**Issue by toVersus** [kubernetes/kubernetes#132603]
Using the Downward API's [resourceFieldRef](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/#downwardapi-resourcefieldref), you can inject values specified in `resources.limits`, such as CPU, memory, or ephemeral storage into environment variables.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: downward-api-resource-limits
spec:
  containers:
  - name: sleep
    image: busybox
    command: ["sh", "-c", "echo CPU_LIMIT=$CPU_LIMIT; echo MEMORY_LIMIT=$MEMORY_LIMIT; sleep infinity"]
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
    env:
    - name: CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          resource: limits.cpu
    - name: MEMORY_LIMIT
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
```

Currently, when container-level resource limits were not specified and the Downward API was used to set environment variables referencing them, the node's allocatable resources were used in the defaulting logic.
With the introduction of the Pod Level Resources feature, this behavior should be updated as outlined in the comment.
https://github.com/kubernetes/kubernetes/blob/b2f27c0649fc0f3d2a4a6dd29135ecc81781f7e4/pkg/kubelet/kubelet_resources.go#L33-L34
