### ISSUE TITLE
Expose status.lastScheduleTime and status.lastSuccessfulTime to Downward API

### ISSUE THREAD

**Issue by Clashsoft** [kubernetes/kubernetes#132630]
### What would you like to be added?

The CronJob status lastScheduleTime and lastSuccessfulTime timestamps would be a useful addition to the Downward API, i.e. being allowed as env > valueFrom > fieldRef > fieldPath and related options.

Example:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  schedule: {{ .schedule }}
  timeZone: {{ $.Values.cronJobs.timeZone }}
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      parallelism: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: example
              image: ...
              env:
                - name: LAST_SCHEDULE_TIME
                  valueFrom:
                    fieldRef:
                      fieldPath: status.lastScheduleTime
```

### Why is this needed?

Cronjobs can use the timestamp for various purposes. For example, a job that scans a database every night can filter by some timestamp > LAST_SCHEDULE_TIME to get only rows that were changed since the last run.

Right now, this is possible by hardcoding (or having an environment variable for) the schedule interval into the app and calculating the schedule time. But this does not take potential startup delays for both the current and previous job.
Alternatively, the job can store its previous schedule or completion time in some form of database (e.g. key value store). But this requires a database to exist and the maintenance overhead that entails.
