### ISSUE TITLE
Pod life-cycle postStart handler behavior question

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#13389]
During my work around to fix #12526, it comes to me that postStart life-cycle handler does not work as I expect. Here's the case:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: resouer/myapp:v6
    lifecycle:
      postStart:
        exec:
          command:
            - "cp"
            - "/app/myapp.war /work"
    volumeMounts:
    - mountPath: /work
      name: test-volume
  - name: web
    image: nginx
    volumeMounts:
    - mountPath: /work
      name: test-volume
  volumes:
  - name: test-volume
```

I mean to start two containers in a Pod, and then copy a file from 'nginx' container to Empty_dir volume.

But this handler will lead the container to Terminated status:

```
Containers:
  nginx:
    Image:                      resouer/myapp:v5
    State:                      Waiting
      Reason:                   CrashLoopBackOff
    Last Termination State:     Terminated
      Exit Code:                137
      Started:                  Mon, 31 Aug 2015 22:17:27 +0800
      Finished:                 Mon, 31 Aug 2015 22:17:58 +0800
    Ready:                      False
    Restart Count:              1
    Variables:
  web:
    Image:              nginx
    State:              Running
      Started:          Mon, 31 Aug 2015 22:11:48 +0800
    Ready:              True
    Restart Count:      0
    Variables:
```

It seems postStart command is a exec that will replace the original CMD (`nc -l -p 60001` in this case) , and Pod will then think the container is killed (137).

But as we defined the handler as a postStart, there seems no intention that we want to terminate the original process. So, is it designed to be like this, or I misuse the postStart here, or a bug?

**Comment by lavalamp** [comment]
Did your post start script return an error value? If not, this is a bug.

**Comment by resouer** [comment]
@lavalamp If I do not use postStart, and then `docker exec  "cp /app/myapp.war /work"`, everything is ok.

I also think it is not caused by when doing `cp`, the volume is not ready yet, otherwise that will be a bug too.

**Comment by lavalamp** [comment]
Yes, if the volume is not ready, that would be a separate bug.

**Comment by resouer** [comment]
@lavalamp I'll dig it through and feedback it here

**Comment by resouer** [comment]
@lavalamp I think both two issues exists actually:

1. First, postStart will replace my default CMD of my image:
If I changed it to:
```
command:
  - 'touch tmp.log'
```
The container state will still be `Terminated`, but it's code is: `Exited (0)`.  That means, even if there's nothing wrong with my `command`, the container become a one-off-task somehow.

2. If I do:
```
command:
  - 'ls /work'
```
The container stops with `Exited (1)`. It seems, the `/work` is not ready when running postSart.

I can not do more deep study as the container's behavior became wired and so hard to track. But it seems there's something buggy ...

**Comment by lavalamp** [comment]
@dchen1107 Can you find an owner for this? It sounds like something wrong is happening.

**Comment by resouer** [comment]
@lavalamp Thanks for your time, after dig this with the latest release for a period,  I realized the main reason may be that I should write command like this:
```
lifecycle:
      postStart:
        exec:
          command:
          - "cp"
          - "/app/myapp.war"
          - "/work
```
Instead of:
```
command:
            - "cp"
            - "/app/myapp.war /work"
```
The later will lead the container state to exit(137), and now, everything works
So, issue closed, until I can re-pro this.
