### ISSUE TITLE
HashContainer is sensitive to order of repeated elements

### ISSUE THREAD

**Issue by kamalmarhubi** [kubernetes/kubernetes#13572]
```
$ ./kubelet --version
Kubernetes v1.0.3
```

The implementation of HashContainer is sensitive to the order of elements in repeated fields. As a result, the kubelet will recreate a container if, eg, only the order of `ports` changes.

Eg, swapping the order of the `ports` in this config causes the container to be recreated:

```
apiVersion: v1
kind: Pod
metadata:
  name: pause
spec:
  containers:
  - name: pause
    image: gcr.io/google_containers/pause:0.8.0
    ports:
      - containerPort: 1234
      - containerPort: 5678
```

Is this desired behaviour? Are there repeated elements where the order is relevant?

Investigating this arose from discussion on the deployment proposal: https://github.com/kubernetes/kubernetes/pull/12236#discussion_r38608888
