### ISSUE TITLE
kubelet should verify updates to the pods from non-apiserver sources

### ISSUE THREAD

**Issue by kamalmarhubi** [kubernetes/kubernetes#13573]
```
$ ./kubelet --version
Kubernetes v1.0.3
```

The implementation of HashContainer is sensitive to the `name` of a volume in the `volumeMounts` section, and not the actual volume. This means that a change to a volume will not result in containers being restarted.

Eg, changing the `hostDir` path from `/tmp/dir` to `/tmp/another-dir` will not result in the kubelet recreating the container for the spec below.

```
apiVersion: v1
kind: Pod
metadata:
  name: pause
spec:
  containers:
  - name: pause
    image: gcr.io/google_containers/pause:0.8.0
    volumeMounts:
    - mountPath: /mount-point
      name: vol
  volumes:
  - name: vol
    hostDir: /tmp/dir
```

Investigating this arose from discussion on the deployment proposal: https://github.com/kubernetes/kubernetes/pull/12236#discussion_r38608888
