### ISSUE TITLE
Add an inline volume type that stores small amounts of RO data with the manifest

### ISSUE THREAD

**Issue by kamalmarhubi** [kubernetes/kubernetes#13610]
For cases where a small amount of static data is desired. This could include
1. configuration for containers whose process is configured by files
2. small-medium amounts of static data, such as an archive of www data for a static site server
3. inputs to a process that has a small input to work ratio

Example use cases:
- allow developers to specify data along side the pod it's used with, instead of needing to put it "somewhere else" (EBS / PD / RBD)
- allow Kubernetes-native process coordinators to pass input data to worker pods

For developers, this would be facilitated by a kubectl plugin (https://github.com/kubernetes/kubernetes/issues/13606) in a similar way to what is proposed for easing secret creation (https://github.com/kubernetes/kubernetes/issues/4822). The plugin would handle archive creation and encoding for inclusion in the manifest.

The size of this data would be limited, as it would be living in etcd. I don't know what a reasonable limit is as I'm not familiar enough with etcd. I would assume a couple hundred KB at the most?

**Comment by thockin** [comment]
Can you sketch the API in a bit more detail.  I don't have any
philosophical objections to this.

**Comment by erictune** [comment]
Yes, I want this.  It would be like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypythonprogram
spec:
  containers:
   - name: c
      image: python
      command: ["python",  "/immediate/hello_server.py"]
    volumeMounts:
    - name: immediate
      mountPath: /immediate
volumes:
  - name: immediate
    immediateFiles:
      - name: hello.py
      - contents: |
#!/usr/bin/python
from BaseHTTPServer import BaseHTTPRequestHandler,HTTPServer
class myHandler(BaseHTTPRequestHandler):	
	def do_GET(self):
		self.send_response(200)
		self.send_header('Content-type','text/html')
		self.end_headers()
		self.wfile.write("Hello World !")
		return
	server = HTTPServer(('', 8080), myHandler)	
	server.serve_forever()

```

**Comment by bgrant0607-nocc** [comment]
Do we really need this if we have ConfigData #1553?

**Comment by bgrant0607-nocc** [comment]
To clarify: Imagine something like Secret, but for non-secret data.

**Comment by kamalmarhubi** [comment]
@thockin sorry I've been traveling and only got to look at this now. Something like @erictune's example is what I had in mind, though with the ability to specify it as base64 encoded compressed data or something else like that.

@bgrant0607-nocc I think that would work for my imagined use cases. The ConfigData could be specified in the same file for easy reference. Similarity with Secret would be good for sharing client side stuff I remember reading about for creating the secrets from files &c.

**Comment by erictune** [comment]
I guess with ConfigData, it would look something like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypythonprogram
spec:
  containers:
   - name: c
      image: python
      command: ["python",  "/immediate/hello_server.py"]
    volumeMounts:
    - name: immediate
      mountPath: /immediate
volumes:
  - name: file
    configData:
      configDataName: mypythonfile
----
apiVersion: v1
kind: ConfigData
metadata:
  name: mypythonfile
spec:
    files:
      - name: hello.py
      - contents: |
#!/usr/bin/python
from BaseHTTPServer import BaseHTTPRequestHandler,HTTPServer
class myHandler(BaseHTTPRequestHandler):    
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type','text/html')
        self.end_headers()
        self.wfile.write("Hello World !")
        return
    server = HTTPServer(('', 8080), myHandler)  
    server.serve_forever()
```

A little wordier, but works too.

**Comment by kamalmarhubi** [comment]
I did think of one reason to still want an inline volume: it would tie the lifetime of the volume to the pod. Imagine a Kubernetes aware application that creates child pods to do work. It may want to pass them different configuration, such as the shard of data to work on. Creating a ConfigData as well as the pod would require more cleanup, and could result in garbage ConfigData in case of errors.

I'm totally willing to accept YAGNI on this though! My use case is quite hypothetical at this point!

**Comment by erictune** [comment]
ConfigData is some other object that has to be named, created, deleted.  It need to have its own permissions.   This does not have that overhead.  Which is nice.

Also, immediate data is immutable, and in some cases, you want to express that the configuration should
not change after runtime.

**Comment by bgrant0607** [comment]
On lifetime: we plan to support cascading deletion, so lifetime shouldn't be an issue. Just use ConfigMap.

**Comment by jberkus** [comment]
this would be excellent, and a nice alternative to templates.

One request: allow for input from a file on the host as well as inline contents.

**Comment by thockin** [comment]
You can effectively do this with a ConfigMap and it's even better -
ConfigMap is fully update-friendly, so the files can "change" without the
Pod restarting, if you want.

**Comment by derekmahar** [comment]
@bgrant0607 @kamalmarhubi @erictune @thockin

Given that ConfigMaps cannot (yet) contain binary data (see #32432), I think the idea of a pre-populated, read-only volume type is still relevant.  For example, in order to deploy a binary file to a pod using a volume, I am torn between using a gitRepos or a ConfigMap volume.  Each has benefits and drawbacks:

### gitRepos

**Advantages**

- Can store common file types including text, binary, or directory.

**Disadvantages**

- Requires a remote Git repository which further requires an HTTP or HTTPS proxy and in the case of HTTPS, TLS certificates.
- Pull model that requires explicit volume update or a pod restart. 

### ConfigMap

**Advantages**

- Push model that automatically updates mounted volumes.

**Disadvantages**

- Cannot store binary files unless files are stored using base64 encoding.
- Cannot store directories.

Ideally, I'd like a volume type that combines the advantages of both gitRepos and ConfigMap, but without their disadvantages.  This volume type would effectively enable me to push a populated file tree into one or more pods.  I think this may have been an intention of #831, but I think that issue implies a Docker image, not just a simple file system image.

**Comment by thockin** [comment]
On Mon, Sep 19, 2016 at 11:50 AM, Derek Mahar <notifications@github.com> wrote:
>
> @bgrant0607 @kamalmarhubi @erictune @thockin
>
> Given that ConfigMaps cannot (yet) contain binary data (see #32432), I think the idea of a pre-populated, read-only volume type is still relevant. For example, in order to deploy a binary file to a pod using a volume, I am torn between using a gitRepos or a ConfigMap volume. Each has benefits and drawbacks:
>
> gitRepos
>
> Advantages
>
> Can store common file types including text, binary, or directory.
>
> Disadvantages
>
> Requires a remote Git repository which further requires an HTTP or HTTPS proxy and in the case of HTTPS, TLS certificates.
> Pull model that requires explicit volume update or a pod restart.

git-sync as a sidecar is a better answer than gitRepo volumes, and self-updates

> ConfigMap
>
> Advantages
>
> Push model that automatically updates mounted volumes.
>
> Disadvantages
>
> Cannot store binary files unless files are stored using base64 encoding.
> Cannot store directories.

ConfigMap can be expanded into directories, as long as you have a key per-file.

Binary data is true, but if Secret adds plain-text support, ConfigMap
could add Binary...  maybe.  @pmorie @smarterclayton

Secret can do Binary data...

> Ideally, I'd like a volume type that combines the advantages of both gitRepos and ConfigMap, but without their disadvantages. This volume type would effectively enable me to push a populated file tree into one or more pods. I think this may have been an intention of #831, but I think that issue implies a Docker image, not just a simple file system image.

inline-volumes would have to be explicitly allowed to update - we do
not allow updates to most pod fields...

**Comment by derekmahar** [comment]
@thockin 

> git-sync as a sidecar is a better answer than gitRepo volumes, and self-updates

I read about git-sync on slide 16 of Brendan Burns' [Composite Containers for Modular Architectures](http://www.slideshare.net/Docker/slideshare-burns) and @philips referred to it in a recent reply to [_How to perform automatic data copy/reset with Kubernetes ?_](https://groups.google.com/d/topic/kubernetes-users/ob437DP0tpY/discussion), but even that I find more complicated than simply providing a volume that already contains some files.

> ConfigMap can be expanded into directories, as long as you have a key per-file.

I'm glad you corrected me on this point, because I wasn't sure.  It's still not clear to me exactly how to consume the directories in a ConfigMap volume, though.

> Secret adds plain-text support, ConfigMap could add Binary... maybe. Secret can do Binary data...

I didn't know that Secret could store binary, but not plain text.  I may use this as a workaround to store my binary files.  It's a little awkward to partition text and binary files between ConfigMap and Secret, but I prefer this option to creating a side car or using an init container.  These are useful patterns, but in this case, I'm looking for something as easy to use as a ConfigMap.

> inline-volumes would have to be explicitly allowed to update - we do not allow updates to most pod fields..

Before you replied, I was going to comment that #24044 more closely resembles what I have in mind than inline-volumes.  @bgrant0607 closed #24044 as a duplicate of #831, so I guess a container volume type is even closer to what I want, but without the Docker image, if that is what #831 implies.

Would a pre-populated volume type be difficult to implement?  I'm having some difficulty understanding why #831 or similar isn't a higher priority.  In fact, I'm quite surprised that it hasn't already been implemented.  I think it's a really good idea and very easy to understand and would likely be just as easy to use.

**Comment by smarterclayton** [comment]
I think we need to fix the ConfigMap thing but it has a work around.

Do we have to allow inline volumes to be updated?  I think the value of an inline volume is more if they can't be updated (otherwise, use a config map).  Treating an inline volume like a piece of static, materialized config co-located with the template that stamps them out (RS / PS / D) that can be safely changed in a rollout is (to me) the primary value they have for anything more complex than an env var and less complex than a full config-driven workflow.

#831 is very interesting especially with very small images, but has enough headwinds in how Docker handles those types of containers and the other changes in CRI that it's fairly risky today.

**Comment by thockin** [comment]
Secret can store both, but it base64 encodes everything.  Eventually that
will be fixed.  But that is a hack.

ConfigMaps can be explicitly mapped key-to-file in the `volumes` block, and
that can be paths like "foo/bar/bat.txt"

#831 is specifically about pulling container images, so "but without the
Docker image" is something else :)  Where do you envision the data coming
from?

@smarterclayton:  "Do we have to allow inline volumes to be updated" -
up-thread this was proposed as a requirement.  Without that requirement it
is vastly easier.

**Comment by derekmahar** [comment]
@thockin 

> #831 is specifically about pulling container images, so "but without the Docker image" is something else :) Where do you envision the data coming from?

I imagined it would work similar to how `kubectl` creates a ConfigMap where a directory on the `kubectl` host populates the object or volume type that would back the volume.  A volume would associate this directory with a volume name which a container could then map into its file system.  I think this is similar to what you described for a ConfigMap directory.

**Comment by smarterclayton** [comment]
I think I would argue that updates belongs to configmaps and secrets (because you have to deal with them), immutable things belong to pods (because they are easier to reason about).  The initial issue talks about immutable pod data (where config + pod definition = total config).

Discussing the complexity of achieving safe config map reuse in deployments convinced me that mutable config maps are more dangerous than they should be - I think we should look for affordances that reduce the complexity of mutable config maps and also make simple pods easier to write.  I generally agree that inline volumes are rife for abuse - but if they are immutable, they do focus the attention.

An argument along this line is that env variables can be very large - promoting someone using an env var to parameterize a file by using a bash entrypoint isn't *wrong*, but it is *complex*, and is the user workaround the spirit rather than intent.  It is a totally valid workaround once we fix the downward API to allow more fields to do:

```
env:
- name: CONFIG
   value: |- 
     massive chunk of config
volumes:
  downwardAPI:
    valueFrom:
    - fieldPath: spec.containers[1].env[@name=CONFIG].value
```

I'm just not sure we should encourage it.
