### ISSUE TITLE
Not able to mount the NFS Storage Block 

### ISSUE THREAD

**Issue by tusharsappal** [kubernetes/kubernetes#13781]
Hi ,
I am trying to mount the NFS Storage block that my IT Team has provided . I am trying the sample nginix image by using the following YAML File 

``` 
#
# This pod imports nfs-server.default.kube.local:/ into /usr/share/nginx/html
#

apiVersion: v1beta3
kind: Pod
metadata:
  name: nfs-web-tushar
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
          # name must match the volume name below
          - name: localstorage
            mountPath: "/usr/share/nginx/html"
  volumes:
    - name: localstorage
      hostPath:
        #This is the NFS Storage Block 
        server: indsharenfs.corp.adobe.com
        # This is the actual Path for the storage block
        path: "/ifs/data/testtushar"
```

When the Kubernetes master allocates the Node to this docker image to run , and the docker image is up and running  . I am not able to see the mounted NFS Block .

Where as when I first mount that NFS Block on the physical host  and use that in spinning up the docker , I am able to see the Storage block 

Our IT team provides in the documentation that the following parameters are needed to be passed when we mount the NFS Block .

``` 
mount -o intr,tcp,nfsvers=3 <NFS Sever URI>:/<Directory> /<Local Directory On to which we want ot mount the Storage Block>
```

First question :- Is the reason for failure is that I am not passing these parameters ,if yes How in the Kubernetes Pod Definition file we are allowed to pass options , as I did not saw any guidelines and docs around this
