### ISSUE TITLE
AWS EBS Credential NoCredential Provider error.

### ISSUE THREAD

**Issue by sumsuddin** [kubernetes/kubernetes#13858]
We are trying to Configure kubernetes RC in AWS instance with AWS Elastic Block Store(EBS). here is the key part of our controller yaml file -

```
          volumeMounts:
            - mountPath: "/opt/phabricator/repo"
              name: ebsvol
      volumes:
        -
          name: ebsvol
          awsElasticBlockStore:
            volumeID: aws://us-west-2a/vol-*****
            fsType: ext4


```

our rc can start pod and works fine with out mounting it to a AWS EBS but with volume mounting in an AWS EBS it gives us -

```
Fri, 11 Sep 2015 11:29:14 +0000 Fri, 11 Sep 2015 11:29:34 +0000 3   {kubelet 172.31.24.103}         failedMount Unable to mount volumes for pod "phabricator-controller-zvg7z_default": error listing AWS instances: NoCredentialProviders: no valid providers in chain
  Fri, 11 Sep 2015 11:29:14 +0000   Fri, 11 Sep 2015 11:29:34 +0000 3   {kubelet 172.31.24.103}         failedSync  Error syncing pod, skipping: error listing AWS instances: NoCredentialProviders: no valid providers in chain
```

We have an credential file with appropiate credential in .aws directory. But its not working.
Do we missing something? Is it a configuration issue?

Kubectl version: 1.0.4 and 1.0.5 (Tried with both)
