### ISSUE TITLE
Scaling a rc with an attached gcePersistentDisk creates loop

### ISSUE THREAD

**Issue by csaintc** [kubernetes/kubernetes#13869]
As title, if you attempt to scale an rc similar to this one:
```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb
  namespace: default
spec:
  replicas: 1
  selector:
    db: rethinkdb-admin
    role: replicas
  template:
    metadata:
      labels:
        db: rethinkdb-admin
        role: replicas
    spec:
      containers:
      - image: [REDACTED]/kubectl-proxy
        imagePullPolicy: 'Always'
        name: kubeproxy
        ports:
        - containerPort: 8001
          name: kubeport
      - image: [REDACTED]/rethinkdb
        imagePullPolicy: 'Always'
        name: rethinkdb
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        volumeMounts:
          - name: volume-name
            mountPath: [REDACTED]
      volumes:
        - name: volume-name
          gcePersistentDisk:
            pdName: [REDACTED] 
            fsType: ext4
```

 with the command:
```
kubectl scale rc rcName --replicas=2
```

The cli will wait indefinitely while the kublet attempts to post a new pod over and over again.
