### ISSUE TITLE
pods with nfs volume,the nfs mount point and the pod volume are synchronized,but the pod volume and container volume are not synchronized

### ISSUE THREAD

**Issue by ydhydhjanson** [kubernetes/kubernetes#14153]
### docker info:

```
[root@localhost /]# docker version
 Version:      1.8.1.el7
 API version:  1.20
 Package Version: 
 Go version:   go1.5beta2
 Git commit:   4ae60f0-dirty
 Built:        Tue Aug 25 20:12:11 UTC 2015
 OS/Arch:      linux/amd64
```

```
[root@localhost /]# docker info
Containers: 13
Images: 67
Storage Driver: devicemapper
 Pool Name: docker-8:3-70034212-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.183 GB
 Data Space Total: 107.4 GB
 Data Space Available: 30.41 GB
 Metadata Space Used: 4.01 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 1.784 GiB
Name: localhost.localdomain
ID: WS5Y:RGIP:7ALW:CD3J:G57D:WPRY:ASB3:PGHF:6S46:M7CS:UEZ6:LM2N
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```
### kubernetes info:

```
[root@localhost /]# kubectl version
Client Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-891-gc5bffaaf316651", GitCommit:"c5bffaaf3166513da6259c44a5d1ba8e86bea5ce", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0+", GitVersion:"v1.0.0-891-gc5bffaaf316651", GitCommit:"c5bffaaf3166513da6259c44a5d1ba8e86bea5ce", GitTreeState:"clean"}
```
### OS version:

```
[root@localhost /]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core) 
```
### PersistentVolume:

```
kind: PersistentVolume

apiVersion: v1

metadata:

  name: pv1

  labels:

    type: local

spec:

  capacity:

    storage: 3Gi

  accessModes:

    - ReadWriteOnce

  nfs:

    path:"/var/lib/webapps/"

    server: 10.10.10.5

```
### PersistentVolumeClaim:

```
kind: PersistentVolumeClaim

apiVersion: v1

metadata:

  name: webapps-pvc

spec:

  accessModes:

    - ReadWriteOnce

  resources:

    requests:

      storage: 1Gi
```
### ReplicationController:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: leavewordrc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: leaveword
    spec:
      containers:
      - name: leaveword
        image: getlot/tomcat:8u23
        ports:
        - containerPort: 8080
          volumeMounts:
          - name: webdir
            mountPath: /var/lib/tomcat8/webapps
      volumes:
        - name: webdir
          persistentVolumeClaim:
            claimName: nfs-claim
```
### nfs mount point:

```
[root@localhost /]# showmount -e 10.10.10.5
Export list for 10.10.10.5:
/var/lib/webapps *
```
### /var/lib/webapps ls:

```
[root@localhost /]# ls /var/lib/webapps/
test.html
```
### pod volume path:

```
/var/lib/kubelet/pods/7ce29f78-5b58-11e5-b96c-000c29accf26/volumes/kubernetes.io~nfs/nfs-pv
```
### pod volume path content:

```
[root@localhost /]# ls /var/lib/kubelet/pods/7ce29f78-5b58-11e5-b96c-000c29accf26/volumes/kubernetes.io~nfs/nfs-pv
 test.html
```
### container volume path content:

```
[root@leavewordrc-ouxhh webapps]# ls /var/lib/tomcat8/webapps
 ROOT docs examples host-manager manager
```
### container volume path content:

```
[root@leavewordrc-ouxhh webapps]# ls /var/lib/tomcat8/webapps
 test.html
```
### docker error log:

```
[root@localhost docker]# journalctl --since=11:15 | grep kubelet
 9月 15 11:18:52 localhost.localdomain docker[3848]: time="2015-09-15T11:18:52.609186369+08:00" level=info msg="GET /containers/var-lib-kubelet-pods-7ce29f78%5Cx2d5b58%5Cx2d11e5%5Cx2db96c%5Cx2d000c29accf26-volumes-kubernetes.io%5Cx7enfs-nfs%5Cx2dpv.mount/json"
 9月 15 11:18:52 localhost.localdomain docker[3848]: time="2015-09-15T11:18:52.609586127+08:00" level=error msg="Handler for GET /containers/{name:.*}/json returned error: no such id: var-lib-kubelet-pods-7ce29f78\x2d5b58\x2d11e5\x2db96c\x2d000c29accf26-volumes-kubernetes.io\x7enfs-nfs\x2dpv.mount"
 9月 15 11:18:52 localhost.localdomain docker[3848]: time="2015-09-15T11:18:52.609628353+08:00" level=error msg="HTTP Error" err="no such id: var-lib-kubelet-pods-7ce29f78\x2d5b58\x2d11e5\x2db96c\x2d000c29accf26-volumes-kubernetes.io\x7enfs-nfs\x2dpv.mount" statusCode=404
 9月 15 11:19:01 localhost.localdomain kubelet[3980]: I0915 11:19:01.745450 3980 kubelet.go:1338] volume "7ce29f78-5b58-11e5-b96c-000c29accf26/nfs-pv", still has a container running "7ce29f78-5b58-11e5-b96c-000c29accf26", skipping teardown
 9月 15 11:19:11 localhost.localdomain kubelet[3980]: I0915 11:19:11.789151 3980 kubelet.go:1338] volume "7ce29f78-5b58-11e5-b96c-000c29accf26/nfs-pv", still has a container running "7ce29f78-5b58-11e5-b96c-000c29accf26", skipping teardown
```
### config.json of container :

```
[root@localhost 1f13988b5868c3a7a45b857b076d23818ad0dc66b370781f951af23cc91f27a9]# cat config.json | python -mjson.tool
 {
 "AppArmorProfile": "",
 "Args": [
 "-c",
 "$TOMCAT_DIR/bin/startup.sh && tail -f $TOMCAT_DIR/logs/catalina.out"
 ],
 "Config": {
 "AttachStderr": false,
 "AttachStdin": false,
 "AttachStdout": false,
 "Cmd": [
 "/bin/sh",
 "-c",
 "$TOMCAT_DIR/bin/startup.sh && tail -f $TOMCAT_DIR/logs/catalina.out"
 ],
 "Domainname": "",
 "Entrypoint": null,
 "Env": [
 "KUBERNETES_SERVICE_HOST=10.254.0.1",
 "KUBERNETES_SERVICE_PORT=443",
 "KUBERNETES_PORT=tcp://10.254.0.1:443",
 "KUBERNETES_PORT_443_TCP=tcp://10.254.0.1:443",
 "KUBERNETES_PORT_443_TCP_PROTO=tcp",
 "KUBERNETES_PORT_443_TCP_PORT=443",
 "KUBERNETES_PORT_443_TCP_ADDR=10.254.0.1",
 "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
 "JAVA_PACKAGE=jdk-8u20-linux-x64.rpm",
 "TOMCAT_PACKAGE=apache-tomcat-8.0.23",
 "TOMCAT_DIR=tomcat8"
 ],
 "ExposedPorts": {
 "8080/tcp": {}
 },
 "Hostname": "leavewordrc-ouxhh",
 "Image": "getlot/tomcat:8u23",
 "Labels": {
 "io.kubernetes.pod.name": "default/leavewordrc-ouxhh"
 },
 "MacAddress": "",
 "NetworkDisabled": false,
 "OnBuild": null,
 "OpenStdin": false,
 "PublishService": "",
 "StdinOnce": false,
 "Tty": false,
 "User": "",
 "VolumeDriver": "",
 "Volumes": null,
 "WorkingDir": "/var/lib"
 },
 "Created": "2015-09-15T03:18:52.828763266Z",
 "Driver": "devicemapper",
 "ExecDriver": "native-0.2",
 "HasBeenStartedBefore": false,
 "HostnamePath": "/var/lib/docker/containers/c5480899095418bfbec3d0dad20e479e8531f39e4708e0cfaa9124382a075c67/hostname",
 "HostsPath": "/var/lib/docker/containers/c5480899095418bfbec3d0dad20e479e8531f39e4708e0cfaa9124382a075c67/hosts",
 "ID": "1f13988b5868c3a7a45b857b076d23818ad0dc66b370781f951af23cc91f27a9",
 "Image": "62820cd0ea0082a50c4f3a5a061b7b76774279dcc4e683976f4fcc8cc1c9b166",
 "LogPath": "/var/lib/docker/containers/1f13988b5868c3a7a45b857b076d23818ad0dc66b370781f951af23cc91f27a9/1f13988b5868c3a7a45b857b076d23818ad0dc66b370781f951af23cc91f27a9-json.log",
 "MountLabel": "system_u:object_r:svirt_sandbox_file_t:s0:c345,c551",
 "MountPoints": {
 "/dev/termination-log": {
 "Destination": "/dev/termination-log",
 "Driver": "",
 "Name": "",
 "RW": true,
 "Relabel": "",
 "Source": "/var/lib/kubelet/pods/7ce29f78-5b58-11e5-b96c-000c29accf26/containers/leaveword/1f13988b5868c3a7a45b857b076d23818ad0dc66b370781f951af23cc91f27a9"
 }
 },
 "Name": "/k8s_leaveword.d36ff1aa_leavewordrc-ouxhh_default_7ce29f78-5b58-11e5-b96c-000c29accf26_4a4b40b7",
 "NetworkSettings": {
 "Bridge": "",
 "EndpointID": "",
 "Gateway": "",
 "GlobalIPv6Address": "",
 "GlobalIPv6PrefixLen": 0,
 "HairpinMode": false,
 "IPAddress": "",
 "IPPrefixLen": 0,
 "IPv6Gateway": "",
 "LinkLocalIPv6Address": "",
 "LinkLocalIPv6PrefixLen": 0,
 "MacAddress": "",
 "NetworkID": "",
 "PortMapping": null,
 "Ports": null,
 "SandboxKey": "",
 "SecondaryIPAddresses": null,
 "SecondaryIPv6Addresses": null
 },
 "Path": "/bin/sh",
 "ProcessLabel": "system_u:system_r:svirt_lxc_net_t:s0:c345,c551",
 "ResolvConfPath": "/var/lib/docker/containers/c5480899095418bfbec3d0dad20e479e8531f39e4708e0cfaa9124382a075c67/resolv.conf",
 "RestartCount": 0,
 "State": {
 "Dead": false,
 "Error": "",
 "ExitCode": 0,
 "FinishedAt": "0001-01-01T00:00:00Z",
 "OOMKilled": false,
 "Paused": false,
 "Pid": 30565,
 "Restarting": false,
 "Running": true,
 "StartedAt": "2015-09-15T03:18:53.743593893Z"
 },
 "UpdateDns": false,
 "Volumes": {
 "/dev/termination-log": "/var/lib/kubelet/pods/7ce29f78-5b58-11e5-b96c-000c29accf26/containers/leaveword/1f13988b5868c3a7a45b857b076d23818ad0dc66b370781f951af23cc91f27a9"
 },
 "VolumesRW": {
 "/dev/termination-log": true
 }
 }
```

why the volumes info is :
 "Volumes": {
 "/dev/termination-log": "/var/lib/kubelet/pods/7ce29f78-5b58-11e5-b96c-000c29accf26/containers/leaveword/1f13988b5868c3a7a45b857b076d23818ad0dc66b370781f951af23cc91f27a9"
