### ISSUE TITLE
Better documentation for deploying cluster add on fluentd-elasticsearch wanted

### ISSUE THREAD

**Issue by theresiasnow** [kubernetes/kubernetes#14170]
Trying to set it up with pod definitions in /etc/kubernetes/manifests/ (bare metal ubuntu cluster). Note I'm using my own docker image (modifed the provided one). Restarting kubelet and then trying:

```
docker run --log-driver=fluentd --log-opt fluentd-address=10.131.8.21:24224 ubuntu echo "Hello Fluentd!"
dial tcp 10.131.8.21:24224: connection refused
```

Can't figure out what ip to use.. Localhost? Where do I find the port?

```
apiVersion: v1
kind: Pod
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
spec:
  containers:
    - name: fluentd-elasticsearch
      image: registry.buildtools.bisnode.net/bisnode/server-fluentd-es
      resources:
        limits:
         cpu: 100m
      env:
        - name: "FLUENTD_ARGS"
          value: "-qq"
      volumeMounts:
          - name: containers
            mountPath: "/var/lib/docker/containers"
          - name: varlog
            mountPath: "/var/log"
  volumes:
    - name: containers
      source:
        hostDir:
        path: "/var/lib/docker/containers"
    - name: varlog
      source:
        hostDir:
        path: "/var/log"
```

**Comment by thockin** [comment]
If you want docker to find it, you probably should set fluentd to use host networking or at least a host port.

**Comment by sigmundlundgren** [comment]
Trying with nodeport and hostport

**Comment by sigmundlundgren** [comment]
Got it working! Didn't set --log-driver to fluentd yet

```
apiVersion: v1
kind: Pod
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
spec:
  containers:
    - name: fluentd-elasticsearch
      image: registry.buildtools.bisnode.net/bisnode/server-fluentd-es
      resources:
        limits:
         cpu: 100m
      env:
        - name: "FLUENTD_ARGS"
          value: "-qq"
      ports:
          - containerPort: 24224
            hostPort: 24224         
      volumeMounts:
          - name: containers
            mountPath: "/var/lib/docker/containers"
          - name: varlog
            mountPath: /var/log
  volumes:
    - name: containers
      hostPath:
        path: "/var/lib/docker/containers"
    - name: varlog
      hostPath:
        path: /var/log
````

**Comment by biswars** [comment]
Useful. But how to schedule the fluentd-elasticsearch pod on **all the nodes** of the cluster ? On GCE, it runs on all nodes after the cluster set up is successful.
What would be the RC specification (yaml file) to achieve the same if the cluster set up is manual i.e, bare metal ubuntu/centos machines.

**Comment by ddgenome** [comment]
@biswars use a DaemonSet rather than a ReplicationController.

**Comment by agustincastanio** [comment]
@biswars I hope this helps:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: gcr.io/google_containers/fluentd-elasticsearch:1.15
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```
