### ISSUE TITLE
Nominal Jobs

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#14188]
Allow a Job to optionally be a  _Nominal_ Jobs by setting `.spec.nominal = true`.

If `nominal` is true, when each Pod is created, manager decides which "completion index" that pod is going to work on.  Manager ensures that there is one completion for each index from 0 to `completions - 1`.  We make it possible to expose that index via the downward API.  Pods can specialize themselves based on their index.  For example, by indexing into bash-array env var. 

Examples of podTemplates in _Nominal Jobs_:
```
spec:
  containers:
    - name: foo
      env:
        - name: N
          valueFrom:
            fieldRef:
              fieldPath: metadata.completionIndex
      cmd: [ "/bin/sh", "-c", "myprogram --work_unit=$N" ]
```
or
```
spec:
  containers:
    - name: foo
      env:
        - name: N
          valueFrom:
            fieldRef:
              fieldPath: metadata.completionIndex
      cmd: [ "/bin/sh", "-c",
             "files_to_process=(foo bar); myprogram --work_unit=$files_to_process[$N]" ]
```
