### ISSUE TITLE
Fail to update a pod that consumes its pod info via the downward API volume

### ISSUE THREAD

**Issue by qwang1** [kubernetes/kubernetes#14263]
After creating a pod with the following config, I tried to change its data (e.g. modify the value of annotation or delete the label). 
1) Use "kubectl edit pod $podname", it can't be edited and always get the error "unable to find api field in struct VolumeSource for the json field "items""
2) Use "kubectl label pod/$podname rack-" and "kubectl describe pod $podname" to verify, the rack label is removed, but the content of /etc/labels in container doesn't change.
Seems "kubectl logs $podname" couldn't give me info.
```
# cat dapi-volume.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-downwardapi-volume-example-nginx
  namespace: default
  labels:
    region: r1
    zone: z11
    rack: a111
  annotations:
    build: one
    builder: qe-one
spec:
  containers:
    - name: client-container
      image: nginx
       command: ["sh", "-c", "while true; do if [[ -e /etc/labels ]]; then cat  /etc/labels; fi; if [[ -e /etc/annotations ]]; then cat  /etc/annotations; fi; sleep 5; done"]
      volumeMounts:
        - name: podinfo
          mountPath: /etc
          readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
          - path: "name"
            fieldRef:
              fieldPath: metadata.name
          - path: "namespace"
            fieldRef:
              fieldPath: metadata.namespace
```
