### ISSUE TITLE
Experimental: Job: Incorrect parallelism/completions

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#14301]
In master branch at 843134885e7e0b360eb5441e85b1410a8b1a7a0c (was head today).

Created a job with unspecified `.spec.parallelism` and `.spec.completions`.  Kubectl described it.
Saw
```
Parallelism:	8740693024
Completions:	8740693032
```
which are a bit higher than I wanted.

**Comment by erictune** [comment]
Example job number 1:
```
apiVersion: v1
kind: Job
metadata:
  name: test-job
spec:
  parallelism: 2
  completions: 5
  selector:
    job: test
  template:
    metadata:
      labels:
        job: test
    spec:
      restartPolicy: OnFailure
      containers:
      - name: basic-pod
        image: "centos:centos7"
        command: ['bash', '-c', 'echo ok']
```

Example job 2:
```
apiVersion: v1
kind: Job
metadata:
  name: pi
spec:
  selector:
    app: pi
  template:
    metadata:
      name: pi
      labels:
        app: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
```
