### ISSUE TITLE
Experimental: DaemonSet: selector should default from template labels

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#14312]
I tried to create this DaemonSet:
```yaml
apiVersion: v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
spec:
  template:
    metadata:
      name: prometheus-node-exporter
    spec:
      containers:
      - name: c
        image: prom/prometheus
        ports:
        - containerPort: 9090
          hostPort: 9090
          name: serverport
```
and got this error:
`The DaemonSet "prometheus-node-exporter" is invalid. spec.selector: required value`

This should have been defaulted from the node label.
