### ISSUE TITLE
Proposal: Affinity Priority for pods of different RC/services

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubernetes/kubernetes#14484]
When deploying a multi-layer application, a typical model is to spread the pods of same layer while placing pods of different layers together.
Currently the scheduler can spread pods from the same RC and/or Service, but cannot affiliate a pod to another.

This proposal is to support the affinity priority between pods of different RC/services.

As a first step, we use label selector to implement. When scheduling, the scheduler compares affinitySelector with all pods’ labels on each node. Nodes with pods(that have particular label values) running on will get high score.

The initial version will be in a followup PR, thanks to have a look and let me know.

**Here is a example of usage**  
The definition of Redis:  
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-rc
  labels:
    name: redis-rc
spec:
  replicas: 2
  selector:
    service: redis
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
      - name: redis-container
        image: redis
```

The definition of application that accesses Redis:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs
  labels:
    name: nodejs
spec:
  replicas: 2
  selector:
    name: nodejs
  template:
    metadata:
      labels:
        name: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: nodejs
      affinitySelector:
        service: redis
```
