### ISSUE TITLE
Container failing to start isn't governed by pod's restart policy

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#14491]
If you create a pod with a restart policy of never, and you have a container that fails to start (e.g. you set its command to a nonexistent file), the Kubelet currently tries to restart it infinitely because the container never started successfully, and therefore never received an exit code. You end up with something like this from Docker:

```
Cannot start container ebd101cfcd0b1aab572a184ece01a17ce081658114977bd6490cd6c78aff06e3: [8] System error: exec: "start": executable file not found in $PATH
```

Is it worth modifying the code to consider a container that failed to start as actually failed, so the pod's restart policy can govern it?

Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=1262753

@kubernetes/rh-cluster-infra @kubernetes/goog-node @smarterclayton @dchen1107

**Comment by vishh** [comment]
+1. Also, I'm not sure why we would even apply a restart policy, since the
container never started.

**Comment by derekwaynecarr** [comment]
One issue that comes up with marking it failed is if its governed by a
Replication Controller, a consequence of marking it Failed is a
proliferation of Pods being rapidly created and then failed.  I know pod
garbage collection would help that, but it would be good if we can update
the dependent controller to recognize in common cases to back-off if pods
keep failing because of failure to start scenarios.

**Comment by dchen1107** [comment]
I thought Kubelet already surfaces both creation and start failure from docker. Let me find the old issue I filed.

**Comment by dchen1107** [comment]
Here is the issue https://github.com/kubernetes/kubernetes/issues/6321 and the initial fix is PR: #6711 

This is a bug we should fix anyway.

**Comment by dchen1107** [comment]
@ncdc what is the output of kubectl describe pods? Are container at waiting state with proper error message from docker?

**Comment by bgrant0607-nocc** [comment]
With respect to replication controller, see also #2529. It should back off.

**Comment by yujuhong** [comment]
> I thought Kubelet already surfaces both creation and start failure from docker. Let me find the old issue I filed.

kubelet does surface the error (see the status below). The problem is that it doesn't categorize the container as dead/terminated, which affects the restart policy.

```
status:
  conditions:
  - lastProbeTime: 2015-09-24T21:45:40Z
    lastTransitionTime: null
    message: 'containers with unready status: [transient]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  containerStatuses:
  - containerID: docker://350fccd11f252594cf58ca16a136361e0c8dca5d95b246e150560ee9bf033855
    image: gcr.io/google_containers/busybox
    imageID: docker://4986bf8c15363d1c5d15512d5266f8777bfba4974ac56e3270e7760f6f0a8125
    lastState: {}
    name: transient
    ready: false
    restartCount: 0
    state:
      waiting:
        message: |
          API error (404): Cannot start container 350fccd11f252594cf58ca16a136361e0c8dca5d95b246e150560ee9bf033855: [8] System error: exec: "fooooooo": executable file not found in $PATH
        reason: RunContainerError
  hostIP: 10.240.0.4
  phase: Pending
  podIP: 10.245.2.254
  startTime: 2015-09-24T21:45:30Z
```
A container would be considered "terminated" in kubelet if its state is not Running and the [FinishedAt time is not zero](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L349). In the case where a container failed to start, the FinishedAt time is zero (see example below), and the container state would be [Waiting](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L383). This may cause kubelet to not even back off restarting at all (didn't check thoroughly), let alone complying to the restart policy.
```
{
    "Id": "0a7ae601729220e717322833bff16d6b5fb42b8df50e2909626ac6082a7a5ade",
    "Created": "2015-09-24T21:47:11.012105087Z",
    "Path": "fooooooo",
    "Args": [
        "run"
    ],
    "State": {
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": -1,
        "Error": "[8] System error: exec: \"fooooooo\": executable file not found in $PATH",
        "StartedAt": "0001-01-01T00:00:00Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
   ...
```
We should make sure kubelet categorize these containers properly.

**Comment by dchen1107** [comment]
Ok, I reproduced the issue easily. Here are the current situation:

When container cannot start by docker due to various reasons, Kubelet marked the container as Waiting state with proper reason (**RunContainerError**) and detail message for docker, so Pod will stuck at Pending state. I copied & pasted a PodStatus example below:

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    status: "False"
    type: Ready
  containerStatuses:
  - containerID: docker://d5c3e5c93e153bee0f1b3d1b0a945d33c1084835da78159c9b75c2080f132f88
    image: openshift/hello-openshift
    imageID: docker://5d856bfbafd3e943c16aaa4ef6a5f0fb2ba71591d8c3cd6a15f37f848b0bc574
    lastState: {}
    name: hello-openshift
    ready: false
    restartCount: 0
    state:
      waiting:
        message: |
          API error (404): Cannot start container d5c3e5c93e153bee0f1b3d1b0a945d33c1084835da78159c9b75c2080f132f88: [8] System error: exec: "start": executable file not found in $PATH
        reason: RunContainerError
  hostIP: 10.240.0.5
  phase: Pending
  podIP: 10.244.1.25
  startTime: 2015-09-24T21:39:18Z
```

When above situation occurs, Kubelet will **retry** in next syncLoop, which is the original issue reported here. Please note that I call this retry, instead of restart, which arguably align with our current [pod-state](https://github.com/kubernetes/kubernetes/edit/master/docs/user-guide/pod-states.md), and do nothing. So that upstream layer can pick up such issue, for example, job controller in this case, and delete such bad pods.

Or

Kubelet can introspect ContainerStatus's reason:

* With restartPolicy never, Kubelet marks such Container as terminated with above proper reason. 
* With restartPolicy onFailure, Kubelet marks such Container as terminated with above proper reason, and pod stays Running. Retry / Restart will be backoff by the same backoff policy on the node. 
* With restartPolicy Always, Kubelet marks such Container as terminated with above proper reason, and pod stays Running. etry / Restart will be backoff by the same backoff policy on the node. For replication controlled pods, since we didn't mark Pod as Failed, there is no issue mentioned at https://github.com/kubernetes/kubernetes/issues/14491#issuecomment-143005454
