### ISSUE TITLE
Can kubernetes use basic auth to authenticate kubelet?

### ISSUE THREAD

**Issue by qq690388648** [kubernetes/kubernetes#14701]
The api doc shows:Kubernetes uses client certificates, tokens, or http basic auth to authenticate users for API calls.
So I tried to use basic auth to authenticate kubelet by set the --kubeconfig as config.yaml which generted by kubectl under ~/.kube/:
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://master:8080
  name: ubuntu
contexts:
- context:
    cluster: ""
    user: ""
  name: development
- context:
    cluster: ubuntu
    user: ubuntu
  name: ubuntu
current-context: ubuntu
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    password: wpJjc2rKyCoiP7tb
    username: admin
```
But it did not work, so I thought whether the kubelet can use basic auth?

**Comment by qq690388648** [comment]
I also tried to set the --api_servers to <code>https://admin:admin_passwd@192.168.102.20:6443</code>, but the kubelet's logs shown:<code>Get https://admin:admin_passwd@master:6443/api/v1/services: x509: certificate is valid for kubernetes.default.svc, kubernetes.default, kubernetes, not master</code>.

**Comment by fgrzadkowski** [comment]
@kubernetes/goog-node

**Comment by vishh** [comment]
AFAIK, basic auth is not supported in the kubelet. @roberthbailey is the expert here. We recommend going through the apiproxy to reach the nodes. This helps narrow down the security context in the cluster for now.

**Comment by roberthbailey** [comment]
It sounds like @qq690388648 is trying to get the kubelet to use basic auth to talk to the apiserver (not for a client to use basic auth to the kubelet). That should work if you have basic auth configured in your apiserver. 

What flags did you pass to the apiserver on startup? In particular, you have to pass the `--basic-auth-file` argument to the apiserver (see https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L196) pointing to a CSV file with the credentials to enable basic auth in the apiserver.

**Comment by qq690388648** [comment]
Yes, you understood my poor English totally! @roberthbailey 
Now I has already config the basic auth on apiserver successfully with <code>--basic-auth-file</code>,  and I can access the api with commands like below:
``` shell
curl --basic -u admin:admin_passwd https://192.168.3.146:6443/api/v1/pods -k
```
But I do not know how to config the kubelet to access the apiserver with basic auth.

**Comment by roberthbailey** [comment]
Your kubeconfig file looks good - make sure you are correctly pointing to it with the `--kubeconfig` argument to the kubelet (documented at https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L245). Note that even though you have the server specified in your kubeconfig file, you need to pass the `--api-servers` flag as well (set it to `http://master:8080` to match your kubeconfig file).

**Comment by qq690388648** [comment]
Oh? I nearly exclude the <code>--kubeconfig</code> if you did not raise it because I think it is used for configuring the kubelet server. I will try it after our great national day and show the result here. Thanks again! @roberthbailey

**Comment by roberthbailey** [comment]
The `--kubeconfig` argument is how to plumb authentication information into an apiserver client: it's used by the kubelet, kubectl, kube-proxy, etc. It doesn't have any relation to configuring the kubelet's http server.

**Comment by liggitt** [comment]
the example kubeconfig in the description would send the user credentials if the server url was https. the basic auth and bearer token transports don't send credentials over http

**Comment by liggitt** [comment]
to summarize, start the kubelet with `--kubeconfig=kubelet.kubeconfig --api-servers=https://master:6443`

kubelet.kubeconfig:
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://master:6443
  name: ubuntu
contexts:
- context:
    cluster: ubuntu
    user: ubuntu
  name: ubuntu
current-context: ubuntu
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    password: ...
    username: admin
```
