### ISSUE TITLE
yaml and json parsers silently drop duplicate keys

### ISSUE THREAD

**Issue by ravwojdyla** [kubernetes/kubernetes#14791]
```
spec:
  selector:
    app: foobar-service
    track: prod
    track: post-prod-staging
```

I can't seem to find how to define _IN_ semantic for svc's selector, I tried to above and it resulted in only the last one being used:

```
> kubectl describe svc svc-prod-svc
Name:                   svc-prod-svc
Namespace:              default
Labels:                 <none>
Selector:               app=foobar-service,track=post-prod-staging
```

kubectl should probably notify of duplication and fail, or are least print warning.
