### ISSUE TITLE
MESOS: Possible to define Service port on Node

### ISSUE THREAD

**Issue by brandon-adams** [kubernetes/kubernetes#14911]
Sorry if the title is vague. I'm running Kubernetes v1 on Mesos (0.24), and I'm having some trouble getting service ports mapped correctly. Whenever I create a service to serve as an endpoint for a pod, it always chooses the first available node port on it's scheduled node. I have my range defined to start at port 1000, so it just chooses sequentially from there. Shouldn't it be using the value I provide? Or is this a limitation in the Mesos platform?

**Comment by bprashanth** [comment]
I'm confused by the explanantion, this should work if 30284 is available on every node in your cluster:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: foo
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30284
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: foo
```
