### ISSUE TITLE
Available EBS volume remains in 'detached' state

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#15073]
Environment: CoreOS 815.0.0, k8s 1.1.0 (7d6c8b6)

It happens to me quite often that a volume marked as "available" on AWS remains in a "detached" state according to the kubelet:

```
kubelet[1535]: W1005 13:39:28.982470    1535 aws.go:1034] Timeout waiting for volume state: actual=detached, desired=attached
kubelet[1535]: E1005 13:39:28.984595    1535 aws.go:921] releaseMountDevice on non-allocated device
kubelet[1535]: E1005 13:39:28.984620    1535 kubelet.go:1282] Unable to mount volumes for pod "artifactory_internal": Timeout waiting for volume state; skipping pod
kubelet[1535]: E1005 13:39:29.045364    1535 pod_workers.go:112] Error syncing pod 5aa8c285-6b66-11e5-903c-0a09c88130bd, skipping: Timeout waiting for volume state
kubelet[1535]: W1005 13:39:29.048711    1535 aws.go:888] Got assignment call for already-assigned volume: f@vol-f016833f
kubelet[1535]: I1005 13:39:29.088711    1535 aws.go:1030] Waiting for volume state: actual=detached, desired=attached
kubelet[1535]: I1005 13:39:30.128916    1535 aws.go:1030] Waiting for volume state: actual=detached, desired=attached
kubelet[1535]: I1005 13:39:31.195361    1535 aws.go:1030] Waiting for volume state: actual=detached, desired=attached
kubelet[1535]: I1005 13:39:32.232307    1535 aws.go:1030] Waiting for volume state: actual=detached, desired=attached

... same message repeats indefinitely ...
```

```
$ aws ec2 describe-volumes --volume-id vol-f016833f --query 'Volumes[*].{State:State,Attachments:Attachments}' 
[
    {
        "Attachments": [],
        "State": "available"
    }
]
```

Deleting the pod and recreating it eventually succeeds.

**Comment by justinsb** [comment]
I have some fixes in progress that should fix this

**Comment by jsafrane** [comment]
I can reliably reproduce similar issue, I am not sure it's the same:
* create a AWS EBS, let's say it has ID `vol-a37f5d43`
* Create a pod that uses this EBS:

  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: aws-web
  spec:
    containers:
      - name: web
        image: nginx
        volumeMounts:
          - name: html-volume
            mountPath: "/mnt/html"
    volumes:
      - name: html-volume
        awsElasticBlockStore:
          volumeID: vol-a37f5d43
          fsType: ext4
  ```
* Create the pod. It succeeds eventually:

   ```console
   $ kubectl create -f pod.yaml
   pod "aws-web" created
   $ kubectl get pods
   NAME      READY     STATUS 
   aws-web   1/1       Running
   ```
* Delete the pod

  ```console
  $ kubectl delete pod aws-web
   pod "aws-web" deleted
  ```

* Create the pod again. It will be `pending` forever

   ```console
   $ kubectl create -f pod.yaml
   pod "aws-web" created
   $ kubectl get pods
   NAME      READY     STATUS 
   aws-web   0/1       Pending
   ```

IMO, it's caused by `AWSCloud.DetachDisk` not removing the detached volume from internal map of attached volumes `awsInstance.deviceMappings`. Subsequent `AWSCloud.AttachDisk` will find it there and it won't even try to attach it again. Patch is available in referenced PR.
