### ISSUE TITLE
kubectl run waits forever to attach to pod that won't start

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#15201]
`kubectl run ... --image=busybox --attach -i -- bash ...` will wait forever because bash isn't in the image, which means the container never leaves pending.  We probably need to transition the pod to failed state in this particular scenario (start will fail with an error, and until the image changes we can't start the image).

```
  containerStatuses:
  - containerID: docker://9c0a7cf4c9900d74317965ca32aea4a767937eaa79705d9a9d8dd28ddeb0b979
    image: busybox
    imageID: docker://d7057cb020844f245031d27b76cb18af05db1cc3a96a29fa7777af75f5ac91a3
    lastState: {}
    name: run-test
    ready: false
    restartCount: 0
    state:
      waiting:
        message: |
          API error (404): Cannot start container 9c0a7cf4c9900d74317965ca32aea4a767937eaa79705d9a9d8dd28ddeb0b979: [8] System error: exec: "bash": executable file not found in $PATH
        reason: RunContainerError
  hostIP: 127.0.0.1
  phase: Pending
```
