### ISSUE TITLE
Delete docs/user-guide/simple-yaml.md

### ISSUE THREAD

**Issue by mudrion** [kubernetes/kubernetes#15355]
Following documentation for setting up the cluster and managing ports and replication controller i found some inconsistency.

Ex configuration:
```
cat ng_rep_2.yml
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-yaml
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx-yaml
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-yaml
        image: nginx
        ports:
        - containerPort: 80
```

If I run the rc hostPort 80 is not exposed and  can't access the nginx server on port 80
missing 0.0.0.0:80->80/tcp

```
docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
77e3bbbb756d        nginx                                  "nginx -g 'daemon off"   51 seconds ago      Up 51 seconds                           k8s_nginx-yaml.9ba7ed0f_nginx-yaml-rctie_default_1c87dff6-6e54-11e5-852d-06a75f8e54e3_67e9a258
35529fe8b793        gcr.io/google_containers/pause:0.8.0   "/pause"                 51 seconds ago      Up 51 seconds                           k8s_POD.ef28e851_nginx-yaml-rctie_default_1c87dff6-6e54-11e5-852d-06a75f8e54e3_1d05931f
```

Adding hostPort: 80 to the yaml file fix the issue exposing the port
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-yaml
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx-yaml
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-yaml
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 80
```
```
docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                NAMES
00fc7903442b        nginx                                  "nginx -g 'daemon off"   21 seconds ago      Up 20 seconds                            k8s_nginx-yaml.4497ed47_nginx-yaml-bpvyo_default_3c52a84b-6e55-11e5-852d-06a75f8e54e3_c31d1566
548ac39ddca1        gcr.io/google_containers/pause:0.8.0   "/pause"                 21 seconds ago      Up 20 seconds       0.0.0.0:80->80/tcp   k8s_POD.98d1e889_nginx-yaml-bpvyo_default_3c52a84b-6e55-11e5-852d-06a75f8e54e3_8d8814da
```

Note: maybe is worth correcting documentation and examples to add hostPort: to yaml files
