### ISSUE TITLE
Support renaming clone in gitRepo volumes

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#15421]
From [stackoverflow thread](http://stackoverflow.com/questions/33044198/naming-gitrepo-mount-path-in-kubernetes), a user would like to set the destination name of the cloned repository in a gitRepo volume.

`git clone` supports supplying a destination name for a cloned repository, e.g. `git clone https://github.com/kubernetes/kubernetes.git k8s`, so I think it is reasonable for us to support the same.

**Comment by markturansky** [comment]
Isn't that exactly what volumeMount provides?  The user specifies exactly what directory is mounted into the container.

The gitrepo plugin uses emptyDir internally, which seems appropriate.  It'll get cleaned up after the pod is gone.

**Comment by markturansky** [comment]
nm, i read through the stack issue and I'm looking at the PR.

**Comment by markturansky** [comment]
After reviewing the linked PR and re-reading what was on stack, I don't think this is what the stack user asked for. He wants his volumeMount to be the root of his repo.  He didn't want his container to have to know the repo name (or any other).

If that's the requirement, it changes the PR.

**Comment by timstclair** [comment]
I believe the requirement was that the container should not depend on the exact source of the repo. If the directory name is arbitrary but fixed in the container (as I believe was the case), then this should address the issue.

If the exact location is predetermined and the volume cannot be mounted one directory up (e.g. to get `/mnt/volumes/k8s` mount the gitRepo at `/mnt/volumes` and rename the repo to `k8s`), then this will not address it. Perhaps this is the more common / general use case though?

**Comment by markturansky** [comment]
Knowing the name of the repo versus any other name is still requiring the container to know 1 name.  Your suggestion on stack to `mv` the contents would accomplish whatever his app needs.  Still needs to know 1 name to move. Having volumeMount as the repo root means the container has to know 0 names.  

The code requires 1 subdir, though, and I am trying understand why.  

Still, even if volumeMount as repo root is what gitVolume *should* do, it's a breaking API change :( I imagine a boolean to toggle a mode would be sufficient.

**Comment by resouer** [comment]
@markturansky If I understand right, this is what the stack user ask for:
```
apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /usr/share/docroot
      name: docroot-volume
  volumes:
  - name: docroot-volume
    gitRepo:
      repository: "git@somewhere:me/my-git-repository.git"
      directory: '.'
```

I think you are suggesting to hard code optional directory to '.' and use a flag to enable this. I'm not against it, the UX in this case will be changed to:
```
apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /usr/share/docroot
      name: docroot-volume
  volumes:
  - name: docroot-volume
    gitRepo:
      repository: "git@somewhere:me/my-git-repository.git"
      cloneToPath: true # equals to `git clone xxx .`
```

@timstclair I think we reach agreement here?
