### ISSUE TITLE
"imagePullPolicy: Always" does not re-pull an image

### ISSUE THREAD

**Issue by bronger** [kubernetes/kubernetes#15609]
Consider the following Dockerfile:

```
FROM debian:jessie
RUN echo 1 > /counter
CMD ["bash", "-c", "for ((i = 0; ; i++)); do cat /counter; sleep 1; done"]
```

And the following rc.yaml:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: ipp-test
spec:
  replicas: 2
  selector:
    app: ipp-test
    deployment: initial
  template:
    metadata:
      labels:
        app: ipp-test
        deployment: initial
    spec:
      containers:
      - name: ipp-test
        image: us.gcr.io/project-108021/ipp_test
      imagePullPolicy: Always
```

Now I say

```
docker build -t us.gcr.io/project-108021/ipp_test .
gcloud docker --server=us.gcr.io push us.gcr.io/project-108021/ipp_test
kubectl create -f rc.yaml
```

After changing "echo 1" to "echo 2" in the Dockerfile and re-building and re-pushing it to the same image name/tag, I call

```
kubectl rolling-update ipp-test --image=us.gcr.io/project-108021/ipp_test
```
and watch the logs with
```
kubectl logs ipp-test-<yourPodHashHere>
```

... and get a lot of "1"s.  Thus, the image was not pulled although imagePullPolicy was set to "Always".  I see no difference between "Always" and "IfNotPresent" then, so I suspect something in kubectl is not working.
