### ISSUE TITLE
NFS Volume not mapped (v1.1.0-beta)

### ISSUE THREAD

**Issue by four43** [kubernetes/kubernetes#15668]
Following setup guide: https://github.com/kubernetes/kubernetes/tree/release-1.1/examples/nfs

Built kubernetes with tagged v1.1.0-beta (latest tagged revision at the time, however I tried with master too)

We are using a salted host, AWS EC2. (Side note: the provisioning works really well, that part runs very smoothly)

Created NFS Server Pod via: https://github.com/kubernetes/kubernetes/blob/release-1.1/examples/nfs/nfs-server-pod.yaml
Created NFS Service via: https://github.com/kubernetes/kubernetes/blob/release-1.1/examples/nfs/nfs-server-service.yaml

Both of those succeeded, nfs service exposed via port: 

```
$ kubectl get service
NAME         CLUSTER_IP     EXTERNAL_IP   PORT(S)    SELECTOR          AGE
kubernetes   10.0.0.1       <none>        443/TCP    <none>            3h
nfs-server   10.0.155.224   <none>        2049/TCP   role=nfs-server   30m
```

Running provided web server:

```
#
# This pod imports nfs-server.default.kube.local:/ into /usr/share/nginx/html
#

apiVersion: v1
kind: Pod
metadata:
  name: nfs-web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/usr/share/nginx/html"
  volumes:
    - name: nfs
      nfs:
        # FIXME: use the right hostname (We did, yay)
        server: 10.0.155.224
        path: "/"
```

```
$ kubectl create -f nfs-web-pod.yaml 
pod "nfs-web" created

$ kubectl describe pod nfs-web
Name:				nfs-web
Namespace:			default
Image(s):			nginx
Node:				[our node ip]/[our node ip]
Start Time:			Wed, 14 Oct 2015 17:24:11 -0500
Labels:				<none>
Status:				Pending
Reason:				
Message:			
IP:				
Replication Controllers:	<none>
Containers:
  web:
    Container ID:	
    Image:		nginx
    Image ID:		
    QoS Tier:
      cpu:	Burstable
    Requests:
      cpu:		100m
    State:		Waiting
      Reason:		ImageNotReady
    Ready:		False
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  nfs:
    Type:	NFS (an NFS mount that lasts the lifetime of a pod)
    Server:	10.0.155.224
    Path:	/
    ReadOnly:	false
  default-token-kdzk8:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	default-token-kdzk8
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath	Reason		Message
  ─────────	────────	─────	────					─────────────	──────		───────
  23s		23s		1	{scheduler }						Scheduled	Successfully assigned nfs-web to [our ip].ec2.internal
  23s		3s		3	{kubelet [our ip].ec2.internal}			FailedMount	Unable to mount volumes for pod "nfs-web_default": exit status 32
  23s		3s		3	{kubelet [our ip].ec2.internal}			FailedSync	Error syncing pod, skipping: exit status 32
```

```
$ kubectl get pods
NAME         READY     STATUS          RESTARTS   AGE
nfs-server   1/1       Running         0          37m
nfs-web      0/1       ImageNotReady   0          4m
```

Any help on what an exit status 32 is? The guide seems to not work.
