### ISSUE TITLE
Kubernetes components seem to downgrade themselves automatically

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#15819]
I attempt to update kube-ui like so.

First, I update the rc file: 

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-ui-v3
  namespace: kube-system
  labels:
    k8s-app: kube-ui
    version: v3
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-ui
    version: v3
  template:
    metadata:
      labels:
        k8s-app: kube-ui
        version: v3
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube-ui
        image: gcr.io/google_containers/kube-ui:v3
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 8080
```

Then I do a rolling upgrade like so:

```
kubectl rolling-update kube-ui-v1 -f kube-ui-rc.yaml --namespace="kube-system"
Created kube-ui-v3
Scaling up kube-ui-v3 from 0 to 1, scaling down kube-ui-v1 from 1 to 0 (keep 1 pods available, don't exceed 2 pods)
Scaling kube-ui-v3 up to 1
```

Everything's fine but eventually the system deletes the new replication controller and re-instates the old version.

How can I update system components like this?
