### ISSUE TITLE
Very high latency connecting to container via virtual IP

### ISSUE THREAD

**Issue by willmore** [kubernetes/kubernetes#15823]
**Quick Description**
Connecting to a "benign" k8s-hosted http application via virtual IP is incurring a consistent ~40sec response overhead.

From within the container:
```console
root@admin-iwcpo:/admin# time curl 127.0.0.1:3005
<html><body>You are being <a href="http://127.0.0.1:3005/session/new">redirected</a>.</body></html>
real    0m0.051s
user    0m0.004s
sys    0m0.000s
```

From the node host, connecting to exposed port:
```console
ubuntu@ip-10-0-3-25:~$ time curl 127.0.0.1:31894
<html><body>You are being <a href="http://127.0.0.1:31894/session/new">redirected</a>.</body></html>
real    0m40.061s
user    0m0.016s
sys    0m0.000s
```

Note the **40sec** difference - this never seems to change. I was able to reproduce on multiple nodes.

I've run the pod/service in a Vagrant testbed without issue. It was only when deploying to AWS with the turn-key setup that I hit the latency.
I initially focused on kube-proxy, but increasing log-levels didn't reveal anything terribly suspicious (at least to my kube-newbie eyes). The one exception being that kube-dns 

I then connected to the virtual IP, bypassing kube-proxy (I believe - I'm a bit confused as what the status is wrt kube-proxy and iptables) and the problem persisted.

I'd appreciate any guidance as to where to focus. Thanks in advance.

**Details**

Running off `1.1` branch from `910f81` (couple of days old). 

Setup is "turn-key AWS", with minor modifications in `aws/util.sh` to deploy to a specific subnet within a pre-existing VPC. This is why the node ip is in the `10.0.3` subnet rather than the default `172.20.0`.

Node OS is `Linux ip-10-0-3-26 3.19.0-20-generic #20-Ubuntu`.

The application being accessed is a Rails app. 
Pod and service defined:
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: ***********
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  selector:
    app: admin
  type: NodePort
  ports:
  - port: 3005  
```

Here is what I think are the relevant iptables entries from the host:
```console
ubuntu@ip-10-0-3-25:~$ sudo iptables-save | grep admin
-A KUBE-NODEPORT-CONTAINER -p tcp -m comment --comment "default/admin:" -m tcp --dport 31894 -j REDIRECT --to-ports 52766
-A KUBE-NODEPORT-HOST -p tcp -m comment --comment "default/admin:" -m tcp --dport 31894 -j DNAT --to-destination 10.0.3.25:52766
-A KUBE-PORTALS-CONTAINER -d 10.1.208.118/32 -p tcp -m comment --comment "default/admin:" -m tcp --dport 80 -j REDIRECT --to-ports 52766
-A KUBE-PORTALS-HOST -d 10.1.208.118/32 -p tcp -m comment --comment "default/admin:" -m tcp --dport 80 -j DNAT --to-destination 10.0.3.25:52766
```
