### ISSUE TITLE
Refactoring downward API ObjectFieldSelector

### ISSUE THREAD

**Issue by tmrts** [kubernetes/kubernetes#15844]
At the moment ``ObjectFieldSelector`` can only be used to access a handful of metadata fields belonging to a pod. Extracting a generic ``ResourceSelector`` would make downward API very flexible. For example, in #6477 we would be able to specify a mounted object field roughly as follows:
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: ExampleReplicationController
spec:
  replicas: 2
  selector:
    app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: gcr.io/google_containers/busybox
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-data-volume
      volumes:
      - name: config-data-volume
        downwardAPI:
          items:
            - path: "config.yaml"
              resourceRef:
                from: pod-config-volume
                fieldPath: component_config
```

This is just one example but it applies to Secrets as well and also opens up possibilities for more.
There might be some concerns about allowing every API object to be accessible, but I believe that's inline with the purpose of the downward API
