### ISSUE TITLE
counter-pod.yaml renders incorrectly in various browsers

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/kubernetes#15912]
The counter-pod.yaml code block renders incorrectly on kubernetes.io see how 'kind' is indented:
http://kubernetes.io/v1.0/docs/getting-started-guides/logging.html

But renders correctly on the GitHub page:
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/logging.md

This repro's on Linux Chrome|Firefox and Chrome on an Android device.

Once the indentation starts it appears to continue through 2 code blocks:

* 'kind' is incorrectly indented in the page source and the rendered HTML.
* The error persists through the next code tag "pods/counter" incorrectly indented
* Is fixed by the third code tag

![image](https://cloud.githubusercontent.com/assets/1022400/10594639/ec7d3b9c-7683-11e5-9f34-74be8836c8dd.png)

It's a minor point but, copying the yaml from the rendered page on kubernetes.io results in invalid YAML:
```
apiVersion: v1
 kind: Pod
 metadata:
   name: counter
   namespace: default
 spec:
   containers:
   - name: count
     image: ubuntu:14.04
     args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 1; done']
```
Instead of:
```
apiVersion: v1
kind: Pod
metadata:
  name: counter
  namespace: default
spec:
  containers:
  - name: count
    image: ubuntu:14.04
    args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 1; done']
```

There is a further YAML code block on the page (fluentd-gcp.yaml) and this renders correctly.
