### ISSUE TITLE
Openstack Cinder

### ISSUE THREAD

**Issue by sramakr** [kubernetes/kubernetes#15966]
Hey,

Testing Cinder Volumes , and , it seems to see it as empty_dir volume.I believe have issues with my configuration file or some syntax error. Appreciate any help.

Are there any dependancy with openstack version ? 

/opt/bin/kubelet --version=true
Kubernetes v1.2.0-alpha.2

Manifest file

```
apiVersion: v1
kind: Pod
metadata:
  name: os-web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html-volumesdf
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: html-volumesdf
      cinder:
        # Enter the volume ID below
        volumeID: 1797be14-4575-4e98-a99b-b8da8c01a764
        fsType: ext4
```

Log Snippet from Kubelet.
Oct 20 19:25:58 kube-slave-181af6c2-0e19-4028-a9de-832e86c7dd89.novalocal kubelet[15514]: I1020 19:25:58.182171   15514 volumes.go:192] Making a volume.Cleaner for volume kubernetes.io~empty-dir/html-volumesdf of pod 57f3b2f9-7760-11e5-a19e-fa163e3240c9
Oct 20 19:25:58 kube-slave-181af6c2-0e19-4028-a9de-832e86c7dd89.novalocal kubelet[15514]: I1020 19:25:58.182195   15514 volumes.go:228] Used volume plugin "kubernetes.io/empty-dir" for 57f3b2f9-7760-11e5-a19e-fa163e3240c9/kubernetes.io~empty-dir
Oct 20 19:25:58 kube-slave-181af6c2-0e19-4028-a9de-832e86c7dd89.novalocal kubelet[15514]: I1020 19:25:58.182209   15514 volumes.go:192] Making a volume.Cleaner for volume kubernetes.io~secret/default-token-4o88a of pod 57f3b2f9-7760-11e5-a19e-fa163e3240c9
Oct 20 19:25:58 kube-slave-181af6c2-0e19-4028-a9de-832e86c7dd89.novalocal kubelet[15514]: I1020 19:25:58.182222   15514 volumes.go:228] Used volume plugin "kubernetes.io/secret" for 57f3b2f9-7760-11e5-a19e-fa163e3240c9/kubernetes.io~secret
