### ISSUE TITLE
failedSync Could not attach GCE PD

### ISSUE THREAD

**Issue by Hokutosei** [kubernetes/kubernetes#16002]
Greetings,

Hope everybody is ok, But please fix this
```
failedSync	Error syncing pod, skipping: Could not attach GCE PD "shard1-node1-master". Timeout waiting for mount paths to be created.
```

got lots of database pods, and keep getting this....

this is my RC file

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb-shard1-master
spec:
  replicas: 1
  selector:
    name: mongodb-shard1-master
    version: v0
  template:
    metadata:
      labels:
        name: mongodb-shard1-master
        version: v0
    spec:
      containers:
      - name: mongodb-shard1-master
        image: gcr.io/chat-app-proto01/mongodb3.0.4
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
          hostPort: 27031
        env:
          - name: REPL_SET
            value: kube_shard1
        volumeMounts:
        - mountPath: /data/db
          name: db-path1
      volumes:
        - name: db-path1
          gcePersistentDisk:
            pdName: shard1-node1-master
            fsType: ext4
            readOnly: false
```

problem seems to be, when a Host died and `NotReady` state, the mounted disk could not be detache
