### ISSUE TITLE
[coreos] - kubelet don't start kube-proxy manifest

### ISSUE THREAD

**Issue by genti-t** [kubernetes/kubernetes#16029]
I'm trying to figure out why kube-proxy.yaml is not started by kubelet.
My current kubelet.service:
```
[Service]
EnvironmentFile=/etc/kubernetes.env
ExecStart=/usr/bin/kubelet $KUBE_KUBELET_OPTS
Restart=on-failure
RestartSec=5
```
/etc/kubernetes.env:
```
KUBE_KUBELET_OPTS="--api_servers=http://127.0.0.1:8080 \
  --tls-cert-file={{ KUBE_TLS_CERT_FILE }} \
  --tls-private-key-file={{ KUBE_TLS_PRIVATE_KEY_FILE }} \
  --register-node=true \
  --cluster_dns={{ DNS_SERVICE_IP }} \
  --config=/etc/kubernetes/manifests \
  --cluster_domain=kubestack.local"
```
/etc/kubernetes/manifests/kube-proxy.yaml
```
piVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube:v1.0.6
    command:
    - /hyperkube
    - proxy
    - --master=http://127.0.0.1:8080
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
```

No error log, nothing
Can someone help me with this?
