### ISSUE TITLE
Events describe pod as unhealthy on init when using readiness probe

### ISSUE THREAD

**Issue by eliaslevy** [kubernetes/kubernetes#16051]
If you configure a readiness probe, an event will be generated for the pod stating it is unhealthy and that the readiness probe failed, even before any readiness probe is executed (i.e. before initialDelaySeconds have expired). In addition, there is no event that records the transition of a pod from unhealthy to healthy.

For example, this is a ready pod whose last event says it is unhealthy, and that event was actually generated before the first readiness probe was executed:

```
Containers:
  server:
    Image:      192.168.99.100:5000/elevy/zookeeper:latest
    State:      Running
      Started:      Wed, 21 Oct 2015 12:56:48 -0700
    Ready:      True
    Restart Count:  0
Conditions:
  Type      Status
  Ready     True 
Events:
  FirstSeen             LastSeen            Count   From            SubobjectPath               Reason      Message
  Wed, 21 Oct 2015 12:56:47 -0700   Wed, 21 Oct 2015 12:56:47 -0700 1   {scheduler }                            scheduled   Successfully assigned zookeeper-1-u4qfe to 172.17.4.99
  Wed, 21 Oct 2015 12:56:48 -0700   Wed, 21 Oct 2015 12:56:48 -0700 1   {kubelet 172.17.4.99}   implicitly required container POD   pulled      Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  Wed, 21 Oct 2015 12:56:48 -0700   Wed, 21 Oct 2015 12:56:48 -0700 1   {kubelet 172.17.4.99}   implicitly required container POD   created     Created with docker id 38e8525f2827
  Wed, 21 Oct 2015 12:56:48 -0700   Wed, 21 Oct 2015 12:56:48 -0700 1   {kubelet 172.17.4.99}   implicitly required container POD   started     Started with docker id 38e8525f2827
  Wed, 21 Oct 2015 12:56:48 -0700   Wed, 21 Oct 2015 12:56:48 -0700 1   {kubelet 172.17.4.99}   spec.containers{server}         created     Created with docker id fd585c375cd2
  Wed, 21 Oct 2015 12:56:48 -0700   Wed, 21 Oct 2015 12:56:48 -0700 1   {kubelet 172.17.4.99}   spec.containers{server}         started     Started with docker id fd585c375cd2
  Wed, 21 Oct 2015 12:56:48 -0700   Wed, 21 Oct 2015 12:56:48 -0700 1   {kubelet 172.17.4.99}   spec.containers{server}         pulled      Successfully pulled image "192.168.99.100:5000/elevy/zookeeper:latest"
  Wed, 21 Oct 2015 12:56:57 -0700   Wed, 21 Oct 2015 12:57:17 -0700 3   {kubelet 172.17.4.99}   spec.containers{server}         unhealthy   Readiness probe failed: 
```

**Comment by lavalamp** [comment]
Can you post your Kubernetes version? Complete pod spec?

**Comment by dohnto** [comment]
I can encounter similar behaviour. Can you please explain me the behaviour?

Content of `rc.yml`
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx-rc
spec:
    replicas: 1
    selector:
        app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx
              ports:
                - containerPort: 80
              readinessProbe:
                initialDelaySeconds: 100
                timeoutSeconds: 1
                httpGet:
                    path: /
                    port: 80
```

```bash
$ LC_ALL=C date && kubectl create -f rc.yml 
Wed Feb  3 14:23:23 CET 2016
replicationcontroller "nginx-rc" created
```

```yaml
# LC_ALL=C date && kubectl describe po nginx-rc-rxij4
# Wed Feb  3 14:23:34 CET 2016
Name:				nginx-rc-rxij4
Namespace:			default
Image(s):			nginx
Node:				sk8s-w01.dev/10.0.164.155
Start Time:			Wed, 03 Feb 2016 14:23:22 +0100
Labels:				app=nginx
Status:				Running
Reason:				
Message:			
IP:				172.18.97.9
Replication Controllers:	nginx-rc (1/1 replicas created)
Containers:
  nginx:
    Container ID:	docker://8748046cdf97c00816f365de8056592bb4d37ed41c75662d06e6dcc0df44b22a
    Image:		nginx
    Image ID:		docker://9737f81306ee0f70b4e998af64d9b2c026b80c5866f01e922ca338d6d81760d7
    State:		Running
      Started:		Wed, 03 Feb 2016 14:23:24 +0100
    Ready:		False
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False 
No volumes.
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath				Reason		Message
  ─────────	────────	─────	────			─────────────				──────		───────
  12s		12s		1	{kubelet sk8s-w01.dev}	implicitly required container POD	pulled		Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  11s		11s		1	{scheduler }							scheduled	Successfully assigned nginx-rc-rxij4 to sk8s-w01.dev
  11s		11s		1	{kubelet sk8s-w01.dev}	implicitly required container POD	created		Created with docker id a041a1e02975
  11s		11s		1	{kubelet sk8s-w01.dev}	implicitly required container POD	started		Started with docker id a041a1e02975
  11s		11s		1	{kubelet sk8s-w01.dev}	spec.containers{nginx}			created		Created with docker id 8748046cdf97
  10s		10s		1	{kubelet sk8s-w01.dev}	spec.containers{nginx}			started		Started with docker id 8748046cdf97
  1s		1s		1	{kubelet sk8s-w01.dev}	spec.containers{nginx}			unhealthy	Readiness probe failed: 

```

My question is, why was the readiness probe run so early when I set `initialDelaySeconds: 100`. After some time (probably the 100 secs, the pod is marked as **ready**, but no event is generated).

```yaml
# LC_ALL=C date && kubectl describe po nginx-rc-rxij4
# Wed Feb  3 14:25:10 CET 2016
Name:				nginx-rc-rxij4
Namespace:			default
Image(s):			nginx
Node:				sk8s-w01.dev/10.0.164.155
Start Time:			Wed, 03 Feb 2016 14:23:22 +0100
Labels:				app=nginx
Status:				Running
Reason:				
Message:			
IP:				172.18.97.9
Replication Controllers:	nginx-rc (1/1 replicas created)
Containers:
  nginx:
    Container ID:	docker://8748046cdf97c00816f365de8056592bb4d37ed41c75662d06e6dcc0df44b22a
    Image:		nginx
    Image ID:		docker://9737f81306ee0f70b4e998af64d9b2c026b80c5866f01e922ca338d6d81760d7
    State:		Running
      Started:		Wed, 03 Feb 2016 14:23:24 +0100
    Ready:		True
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Ready 	True 
No volumes.
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath				Reason		Message
  ─────────	────────	─────	────			─────────────				──────		───────
  1m		1m		1	{kubelet sk8s-w01.dev}	implicitly required container POD	pulled		Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  1m		1m		1	{scheduler }							scheduled	Successfully assigned nginx-rc-rxij4 to sk8s-w01.dev
  1m		1m		1	{kubelet sk8s-w01.dev}	implicitly required container POD	created		Created with docker id a041a1e02975
  1m		1m		1	{kubelet sk8s-w01.dev}	implicitly required container POD	started		Started with docker id a041a1e02975
  1m		1m		1	{kubelet sk8s-w01.dev}	spec.containers{nginx}			created		Created with docker id 8748046cdf97
  1m		1m		1	{kubelet sk8s-w01.dev}	spec.containers{nginx}			started		Started with docker id 8748046cdf97
  1m		17s		9	{kubelet sk8s-w01.dev}	spec.containers{nginx}			unhealthy	Readiness probe failed: 
```
