### ISSUE TITLE
How do I get to know the config context (default (preference) namespace etc)

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#16085]
I found that kubectl namespace has been forbidden: and if I use `kubectl namespace`, there is a clue that  "See 'kubectl config set-context --help' for more details"
But `kubectl config set-context` couldn't view the default (preference) namespace.
Then I use  `kubectl config view`, but the result is:

```
{
    "kind": "Config",
    "apiVersion": "v1",
    "preferences": {},
    "clusters": [],
    "users": [],
    "contexts": [],
    "current-context": ""
}
```

I couldn't found any contexts there.
So I see, If we don't specify any context,  The current-context (default namespace etc) is hard coded in our code.
I think this is a bad user experience. We should enhance this.

And I specify a current-context, use  `kubectl config view` again, the result is:

```
apiVersion: v1
clusters: []
contexts:
- context:
    cluster: ""
    namespace: development
    user: ""
  name: development
current-context: development
kind: Config
preferences: {}
users: []
```

Yes, it works. But I think we should support `kubectl config view --current-context` to see the current-context directly.
