### ISSUE TITLE
Shouldn't Persistent Volume config file define key 'spec.type' ?

### ISSUE THREAD

**Issue by josefkarasek** [kubernetes/kubernetes#16155]
Why Persistent Volume configuration doesn't define a 'spec.type' key, which would contain the specific config values of the PV type. Including the actual type of the volume as a value of some key. Similarly to an example:

```
  apiVersion: v1
  kind: PersistentVolume
  spec:
    type:
      volumeType: nfs
      path: /tmp
      server: 172.17.0.2
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
```

Currently the PV configuration defines a key for [every possible type](https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.2/docs/user-guide/volumes.md#types-of-volumes), like this:

```
  apiVersion: v1
  kind: PersistentVolume
  spec:
    nfs:
      path: /tmp
      server: 172.17.0.2
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
```
