### ISSUE TITLE
Incorrect --to-destination iptables flag being set for services by kube-proxy when using Vagrant

### ISSUE THREAD

**Issue by activeshadow** [kubernetes/kubernetes#16224]
I'm using Vagrant to deploy a small, multi-node cluster on my local machine for development/testing. I've been banging my head against the wall trying to figure out why I can't get a couple of my containers running in different pods to talk to one another via services, and I finally realized that the iptables `--to-destination` flag for my KUBE-PORTALS-HOST rules on the service node is pointing to the default VirtualBox IP address (`10.0.2.15`). I assume, based on examples in the documentation [here](http://kubernetes.io/v1.0/docs/user-guide/debugging-services.html), that the iptables `--to-destination` option should instead be pointing to an IP address in my Flannel network.

Any ideas on how to fix this? I don't seem to have the same issue when testing in more traditional configurations, like GCE, AWS, or DigitalOcean, but I'd **really** like to be able to do development and testing on my local machine.

**Comment by activeshadow** [comment]
Here's some output I should have included in the original post. The service is named `foobar` and the port names are `a` and `b`. The service's cluster IP address is `10.3.99.48`.

```
core@node ~ $ sudo iptables-save | grep foobar
-A KUBE-PORTALS-CONTAINER -d 10.3.99.48/32 -p tcp -m comment --comment "default/foobar:a" -m tcp --dport 9990 -j REDIRECT --to-ports 39702
-A KUBE-PORTALS-CONTAINER -d 10.3.99.48/32 -p tcp -m comment --comment "default/foobar:b" -m tcp --dport 9991 -j REDIRECT --to-ports 45934
-A KUBE-PORTALS-HOST -d 10.3.99.48/32 -p tcp -m comment --comment "default/foobar:a" -m tcp --dport 9990 -j DNAT --to-destination 10.0.2.15:39702
-A KUBE-PORTALS-HOST -d 10.3.99.48/32 -p tcp -m comment --comment "default/foobar:b" -m tcp --dport 9991 -j DNAT --to-destination 10.0.2.15:45934
```

**Comment by thockin** [comment]
No, that's the correct config.  It is redirecting to the local kube-proxy, which is (supposedly) listening on the node.  You should see the same pattern in any install.

The open question for me is what is really failing?  What is your node's podCIDR and what is the IP space set aside for Services (`--service-cluster-ip-range` on kube-apiserver)?

**Comment by activeshadow** [comment]
Dang... I thought I had tracked down the issue. :-(

When I get the details of the node running my service, it doesn't show the `podCIDR` config as part of the spec for some reason...

```
apiVersion: v1
kind: Node
metadata:
  creationTimestamp: 2015-10-24T02:02:49Z
  labels:
    kubernetes.io/hostname: 192.168.0.102
  name: 192.168.0.102
  resourceVersion: "2454"
  selfLink: /api/v1/nodes/192.168.0.102
  uid: 541e32f5-79f3-11e5-a077-080027a06d5e
spec:
  externalID: 192.168.0.102
status:
  addresses:
  - address: 192.168.0.102
    type: LegacyHostIP
  capacity:
    cpu: "1"
    memory: 2053684Ki
    pods: "40"
  conditions:
  - lastHeartbeatTime: 2015-10-24T12:22:37Z
    lastTransitionTime: 2015-10-24T02:02:49Z
    reason: kubelet is posting ready status
    status: "True"
    type: Ready
  nodeInfo:
    bootID: 34ce14d6-3ed2-4063-9d63-18a9fd722721
    containerRuntimeVersion: docker://1.8.3
    kernelVersion: 4.2.2-coreos
    kubeProxyVersion: v1.0.6-release-1.0+388061f
    kubeletVersion: v1.0.6-release-1.0+388061f
    machineID: 93d90de48011408b8db1850e6377646c
    osImage: CoreOS 835.1.0
    systemUUID: 4DDCFE93-C706-4784-BA0F-61E993DA1A7F
```

However, here's the IP configuration details for that particular node. The `192.168.0.102/24` interface address is the Vagrant/VirtualBox private network I have setup for all the CoreOS/Kubernetes nodes to communicate over.

```
core@localhost ~ $ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:a0:6d:5e brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 84709sec preferred_lft 84709sec
    inet6 fe80::a00:27ff:fea0:6d5e/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:44:f0:09 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.102/24 brd 192.168.0.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe44:f009/64 scope link 
       valid_lft forever preferred_lft forever
4: flannel0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1472 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 10.244.34.0/16 scope global flannel0
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:9c:1d:d6:1c brd ff:ff:ff:ff:ff:ff
    inet 10.244.34.1/24 scope global docker0
       valid_lft forever preferred_lft forever
```

The IP space I have for services is `10.3.0.0/16`, per the `kube-apiserver` config.

```
containers:                                                                               
- name: kube-apiserver                                                                    
  image: gcr.io/google_containers/hyperkube:v1.0.6                                        
  command:                                                                                
  - /hyperkube                                                                            
  - apiserver                                                                             
  - --bind-address=0.0.0.0                                                                
  - --etcd-servers=http://127.0.0.1:2379                                                  
  - --allow-privileged=true                                                               
  - --service-cluster-ip-range=10.3.0.0/16                                                
  - --secure-port=443                                                                     
  - --advertise-address=192.168.0.10                                                      
  - --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
  - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem                                     
  - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem                          
  - --client-ca-file=/etc/kubernetes/ssl/ca.pem
  - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem                      
  ports:
  - containerPort: 443                                                                    
    hostPort: 443
    name: https
  - containerPort: 8080                                                                   
    hostPort: 8080 
    name: local
  volumeMounts:                                                                           
  - mountPath: /etc/kubernetes/ssl                                                        
    name: ssl-certs-kubernetes
    readOnly: true
  - mountPath: /etc/ssl/certs                                                             
    name: ssl-certs-host
    readOnly: true
volumes:
- hostPath:                                                                               
    path: /etc/kubernetes/ssl                                                             
  name: ssl-certs-kubernetes
- hostPath:
    path: /usr/share/ca-certificates                                                      
  name: ssl-certs-host
```

Thank you for helping! I'm curious what's going on here... I'm **99% sure** it's user error on my part, so I apologize in advance for (likely) wasting your time. :-/
