### ISSUE TITLE
Services load balance to all nodes, not just minion nodes

### ISSUE THREAD

**Issue by runningwild** [kubernetes/kubernetes#16278]
At least on GCE, a load balanced service will get a target pool that includes the master node, which causes a constant fraction of requests to fail because the master node doesn't forward anything.

Easy to reproduce:
```bash
$ kube-up.sh
$ kubectl create -f ./simple-service.yaml
```

-- simple-service.yaml --
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: simple
  name: simple
spec:
  ports:
    - port: 20000
      targetPort: 10000
      protocol: TCP
      name: grpc
    - port: 20001
      targetPort: 10001
      protocol: TCP
      name: http
  type: LoadBalancer
  selector:
    name: simple
```

```bash
$ gcloud compute forwarding-rules list --region us-central1
NAME                             REGION      IP_ADDRESS     IP_PROTOCOL TARGET
af52d62427bf611e5b08e42010af0000 us-central1 146.148.37.120 TCP         us-central1/targetPools/af52d62427bf611e5b08e42010af0000

$ gcloud compute target-pools describe --region us-central1 af52d62427bf611e5b08e42010af0000
creationTimestamp: '2015-10-26T08:34:17.616-07:00'
id: '8768978418393313284'
instances:
- https://www.googleapis.com/compute/v1/projects/montage-generator/zones/us-central1-a/instances/kubernetes-master
- https://www.googleapis.com/compute/v1/projects/montage-generator/zones/us-central1-a/instances/kubernetes-minion-268c
- https://www.googleapis.com/compute/v1/projects/montage-generator/zones/us-central1-a/instances/kubernetes-minion-tl5l
kind: compute#targetPool
name: af52d62427bf611e5b08e42010af0000
region: https://www.googleapis.com/compute/v1/projects/montage-generator/regions/us-central1
selfLink: https://www.googleapis.com/compute/v1/projects/montage-generator/regions/us-central1/targetPools/af52d62427bf611e5b08e42010af0000
```

kubernetes-master is in there (you might need to scroll to the right a bit to see it), but shouldn't be.  See https://groups.google.com/forum/#!topic/google-containers/yg539XUMQSA for more context.

I was able to fix this by culling the kubernetes-master when listing nodes in the service controller.  I can't help thinking that it should just be created with something like a minionNodeLister rather than a nodeLister, but this isn't the only place in k8s that checks for a master node by doing a string comparison.  Anyway, if this looks good I will submit it as a PR, but if not then someone who knows more than I do should do a real fix.

My fix: https://github.com/runningwild/kubernetes/commit/01a39ebcb6cca77e797ad80e5ae231299322fd1f
