### ISSUE TITLE
Question: Will k8s support docker volume scheme?

### ISSUE THREAD

**Issue by x1022as** [kubernetes/kubernetes#16405]
Newbie to k8s~

As I know Docker has volume plugin, and k8s gets its own too. Is it possible that k8s will support docker volume scheme to inherit its volume plugin?

What is k8s plan for volume (docker related volume plan, more specifically)? I tried to search issues and got nothing, maybe I had missed something? Any issues or discussion related to this will help.

Not sure whom to ping, maybe @thockin ?

In our scene, we are managing data with docker volume plugin(maintained by ourselves, not open-source yet). and we are trying to migrate to k8s,   That is what this issue intend to figure out, other solution is appreciated too.

**Comment by lavalamp** [comment]
P1 for answering the question, I think.

**Comment by x1022as** [comment]
As docker now support : 
    docker volume create vol --volume-driver=vd1 --opt=foo=bar
    docker run -v vol:/foo busybox sh

Maybe we can add a new volume plugin called docker-volome to k8s, This plugin will call docker volume create/rm with specific info like volume-driver and opts to operate volumes. maybe it works like this:
```
apiVersion: v1
kind: Pod 
metadata:
  name: docker-volume-example
spec:
  containers:
    - name: web 
      image: nginx
      ports:
        - name: web 
          containerPort: 80
      volumeMounts:
         - name: docker-volume-test
            mountPath: "/foo"
  volumes:
    - name: docker-volume-test
      docker-volume:
        volume-driver: docker-volume-driver1
        opt: foo=bar
```

just an immature thought, any suggestion and criticism are welcome :)
