### ISSUE TITLE
create snapshot directory error: mkdir /home/data/etcd/member: permission denied

### ISSUE THREAD

**Issue by JunejaTung** [kubernetes/kubernetes#16493]
when i try to launch kube-dns in 'kubernetes/cluster/addons/dns', then etcd pods have to restart because failed to mkdir */member
i have try etcd:2.0.9 and etcd:2.0.12, and already mkdir for member. the same error encounter:

## container logs
[root@wlan-cloudserver34 etcd]# docker ps -a | grep dns
38edaf47d1db        gcr.io/google_containers/etcd:2.0.12             "/usr/local/bin/etcd   5 seconds ago       Exited (1) 4 seconds ago                        k8s_etcd.270935d_kube-dns-v9-zngr8_kube-system_180a98f3-7e23-11e5-8c76-fa163e77e286_dcf9c42a        
49e771d7a4b7        gcr.io/google_containers/etcd:2.0.12             "/usr/local/bin/etcd   14 seconds ago      Exited (1) 14 seconds ago                       k8s_etcd.270935d_kube-dns-v9-zngr8_kube-system_180a98f3-7e23-11e5-8c76-fa163e77e286_54c1cbe5        
ee0f1622882a        gcr.io/google_containers/etcd:2.0.12             "/usr/local/bin/etcd   25 seconds ago      Exited (1) 24 seconds ago                       k8s_etcd.270935d_kube-dns-v9-zngr8_kube-system_180a98f3-7e23-11e5-8c76-fa163e77e286_6ed15a18        
8d1b47d6d220        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   33 seconds ago      Up 32 seconds                                   k8s_skydns.d8596ce5_kube-dns-v9-zngr8_kube-system_180a98f3-7e23-11e5-8c76-fa163e77e286_7507bc87     
ba0a7ee40a94        gcr.io/google_containers/kube2sky:1.11           "/kube2sky '-domain=   33 seconds ago      Up 32 seconds                                   k8s_kube2sky.82833f00_kube-dns-v9-zngr8_kube-system_180a98f3-7e23-11e5-8c76-fa163e77e286_5b75f66a   
4150da2f4ca0        gcr.io/google_containers/etcd:2.0.12             "/usr/local/bin/etcd   34 seconds ago      Exited (1) 33 seconds ago                       k8s_etcd.270935d_kube-dns-v9-zngr8_kube-system_180a98f3-7e23-11e5-8c76-fa163e77e286_4a6e9ca1        
6da72d6b20fc        gcr.io/google_containers/exechealthz:1.0         "/exechealthz '-cmd=   34 seconds ago      Up 34 seconds                                   k8s_healthz.fa8774e2_kube-dns-v9-zngr8_kube-system_180a98f3-7e23-11e5-8c76-fa163e77e286_97126b14    
7aa0f0e2f584        gcr.io/google_containers/pause:0.8.0             "/pause"               35 seconds ago      Up 34 seconds                                   k8s_POD.2688308a_kube-dns-v9-zngr8_kube-system_180a98f3-7e23-11e5-8c76-fa163e77e286_46047d2f        
[root@wlan-cloudserver34 etcd]# docker logs 38edaf47d1db
2015/10/29 09:54:54 etcd: listening for peers on http://localhost:2380
2015/10/29 09:54:54 etcd: listening for peers on http://localhost:7001
2015/10/29 09:54:54 etcd: listening for client requests on http://127.0.0.1:2379
2015/10/29 09:54:54 etcd: listening for client requests on http://127.0.0.1:4001
2015/10/29 09:54:54 etcdserver: datadir is valid for the 2.0.1 format
2015/10/29 09:54:54 etcdserver: name = default
2015/10/29 09:54:54 etcdserver: data dir = /home/data/etcd
2015/10/29 09:54:54 etcdserver: member dir = /home/data/etcd/member
2015/10/29 09:54:54 etcdserver: heartbeat = 100ms
2015/10/29 09:54:54 etcdserver: election = 1000ms
2015/10/29 09:54:54 etcdserver: snapshot count = 10000
2015/10/29 09:54:54 etcdserver: advertise client URLs = http://127.0.0.1:2379,http://127.0.0.1:4001
2015/10/29 09:54:54 etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2015/10/29 09:54:54 etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
2015/10/29 09:54:54 etcdserver create snapshot directory error: mkdir /home/data/etcd/member: permission denied
[root@wlan-cloudserver34 etcd]# 
[root@wlan-cloudserver34 etcd]# pwd
/home/data/etcd
[root@wlan-cloudserver34 etcd]# ll
total 4
drwxr-xr-x. 2 root root 4096 Oct 29 17:41 member
[root@wlan-cloudserver34 etcd]# docker logs 49e771d7a4b7
2015/10/29 09:54:44 etcd: listening for peers on http://localhost:2380
2015/10/29 09:54:44 etcd: listening for peers on http://localhost:7001
2015/10/29 09:54:44 etcd: listening for client requests on http://127.0.0.1:2379
2015/10/29 09:54:44 etcd: listening for client requests on http://127.0.0.1:4001
2015/10/29 09:54:44 etcdserver: datadir is valid for the 2.0.1 format
2015/10/29 09:54:44 etcdserver: name = default
2015/10/29 09:54:44 etcdserver: data dir = /home/data/etcd
2015/10/29 09:54:44 etcdserver: member dir = /home/data/etcd/member
2015/10/29 09:54:44 etcdserver: heartbeat = 100ms
2015/10/29 09:54:44 etcdserver: election = 1000ms
2015/10/29 09:54:44 etcdserver: snapshot count = 10000
2015/10/29 09:54:44 etcdserver: advertise client URLs = http://127.0.0.1:2379,http://127.0.0.1:4001
2015/10/29 09:54:44 etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2015/10/29 09:54:44 etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
2015/10/29 09:54:44 etcdserver create snapshot directory error: mkdir /home/data/etcd/member: permission denied
[root@wlan-cloudserver34 etcd]# 

## other info
[root@wlan-cloudserver31 dns]# ls
kube2sky  MAINTAINERS.md  README.md  skydns  skydns-rc.yaml  skydns-svc.yaml
[root@wlan-cloudserver31 dns]# kubectl create  -f  skydns-rc.yaml 
replicationcontrollers/kube-dns-v9
[root@wlan-cloudserver31 dns]# kubectl get service --all-namespaces 
NAMESPACE     NAME              LABELS                                                                           SELECTOR               IP(S)            PORT(S)
default       kubernetes        component=apiserver,provider=kubernetes                                          <none>                 10.254.0.1       443/TCP
default       maintain-master   name=maintain-master                                                             name=maintain-master   10.254.98.56     6379/TCP
default       portal-master     name=portal-master                                                               name=portal-master     10.254.173.124   6379/TCP
default       portal-slave      name=portal-slave                                                                name=portal-slave      10.254.217.179   6379/TCP
kube-system   kube-dns          k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS   k8s-app=kube-dns       10.254.47.183    53/UDP
                                                                                                                                                         53/TCP
[root@wlan-cloudserver31 dns]# kubectl get  pods --all-namespaces  -o wide
NAMESPACE     NAME                     READY     STATUS                                                                                                                                                                                                                                  RESTARTS   AGE       NODE
default       apphealth-master-jlwt1   0/1       image pull failed for h3crd-wlan1.chinacloudapp.cn:5000/microservice/apphealth:20151028175009, this may be because there are no credentials on this request.  details: (Error: image microservice/apphealth:20151028175009 not found)   0          1d        wlan-cloudserver34
default       portal-v3-oe13j          1/1       Running                                                                                                                                                                                                                                 0          46m       wlan-cloudserver32
kube-system   kube-dns-v9-zngr8        3/4       Running                                                                                                                                                                                                                                 1          18s       wlan-cloudserver34

## yaml file
```
[root@wlan-cloudserver31 dns]#more skydns-svc.yaml 
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  #clusterIP: wlan-cloudserver31
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
[root@wlan-cloudserver31 dns]#more  skydns-rc.yaml 
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v9
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v9
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v9
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v9
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.12
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        command:
        - /usr/local/bin/etcd
        - -data-dir
        - /home/data/etcd
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
        volumeMounts:
        - name: etcd-storage
          mountPath: /home/data/etcd
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.11
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        #command = "/kube2sky"
        - -domain= cluster.local
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-03-11-001
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/skydns"
        - -machines=http://127.0.0.1:4001
        - -addr=0.0.0.0:53
       #- -ns-rotate=false
        - -domain= cluster.local
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
```
