### ISSUE TITLE
Failed to create a kubernetes client: invalid --kube_master_url specified

### ISSUE THREAD

**Issue by JunejaTung** [kubernetes/kubernetes#16780]
## create kube-dns

the container `kube2sky` have to restart for underly confused errors.My kubernetes master ip is 172.27.8.210.

```
[root@wlan-cloudserver34 wlanuser]# docker logs 43d620f27ff8
I1104 03:00:21.546242       1 kube2sky.go:383] [Attempt: 1] Attempting access to etcd after 5 second sleep
I1104 03:00:26.549125       1 kube2sky.go:389] Etcd server found: http://127.0.0.1:4001
F1104 03:00:27.553317       1 kube2sky.go:517] Failed to create a kubernetes client: invalid --kube_master_url specified  http://172.27.8.210:8080
[root@wlan-cloudserver34 wlanuser]# 
```

how to resolve this troble? I can't find any config miss in skydns-rc.yaml.

```
[root@wlan-cloudserver31 dns]# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                     READY     STATUS    RESTARTS   AGE       NODE
default       redis-master-rze58       1/1       Running   2          1d        172.27.8.214
kube-system   heapster-zr8zh           1/1       Running   0          23h       172.27.8.214
kube-system   influxdb-grafana-h9rnx   2/2       Running   0          23h       172.27.8.214
kube-system   kube-dns-v9-d14vg        2/4       Running   1          17s       172.27.8.214
[root@wlan-cloudserver31 dns]# 
---------------------------------------------------------------------------------------------------------------
[root@wlan-cloudserver34 wlanuser]# docker ps -a
CONTAINER ID        IMAGE                                            COMMAND                CREATED             STATUS                        PORTS               NAMES
ae08a25fad52        gcr.io/google_containers/kube2sky:1.11           "/kube2sky '-domain=   4 seconds ago       Exited (255) 1 seconds ago                        k8s_kube2sky.45ef4ba8_kube-dns-v9-d14vg_kube-system_409a1920-82a0-11e5-a8b4-fa163e77e286_e297b6ca        
38e0ca1c170e        gcr.io/google_containers/kube2sky:1.11           "/kube2sky '-domain=   14 seconds ago      Exited (255) 11 seconds ago                       k8s_kube2sky.45ef4ba8_kube-dns-v9-d14vg_kube-system_409a1920-82a0-11e5-a8b4-fa163e77e286_87ee286d        
4edde49d6fc0        gcr.io/google_containers/etcd:2.0.9              "/usr/local/bin/etcd   21 seconds ago      Up 20 seconds                                     k8s_etcd.a0988a50_kube-dns-v9-d14vg_kube-system_409a1920-82a0-11e5-a8b4-fa163e77e286_9de364b7            
c9f2535dfd19        gcr.io/google_containers/exechealthz:1.0         "/exechealthz '-cmd=   21 seconds ago      Up 20 seconds                                     k8s_healthz.58777676_kube-dns-v9-d14vg_kube-system_409a1920-82a0-11e5-a8b4-fa163e77e286_1f0dca74         
bd7f92d92ee4        gcr.io/google_containers/skydns:2015-03-11-001   "/skydns -machines=h   22 seconds ago      Up 21 seconds                                     k8s_skydns.d8596ce5_kube-dns-v9-d14vg_kube-system_409a1920-82a0-11e5-a8b4-fa163e77e286_1728dca5          
43d620f27ff8        gcr.io/google_containers/kube2sky:1.11           "/kube2sky '-domain=   23 seconds ago      Exited (255) 15 seconds ago                       k8s_kube2sky.45ef4ba8_kube-dns-v9-d14vg_kube-system_409a1920-82a0-11e5-a8b4-fa163e77e286_a9b031be        
c6f16e55807e        gcr.io/google_containers/pause:0.8.0             "/pause"               23 seconds ago      Up 22 seconds                                     k8s_POD.2688308a_kube-dns-v9-d14vg_kube-system_409a1920-82a0-11e5-a8b4-fa163e77e286_9de4aa1a             
```
## skydns-rc.yaml

```
[root@wlan-cloudserver31 dns]# pwd
/home/gopath/src/k8s.io/kubernetes/cluster/addons/dns
[root@wlan-cloudserver31 dns]# more skydns-rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v9
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v9
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v9
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v9
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        command:
        - /usr/local/bin/etcd
       # - --privileged=true
       # - -data-dir
       # - /home/data/etcd
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
        volumeMounts:
        - mountPath: /home/data/etcd
          name: etcd-storage
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.11
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/kube2sky"
        - -domain= cluster.local
       # - -etcd-server= http://127.0.0.1:4001
        - -kube_master_url= http://172.27.8.210:8080
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-03-11-001
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/skydns"
        - -machines=http://127.0.0.1:4001
        - -addr=0.0.0.0:53
       # - -ns-rotate=false
        - -domain= cluster.local
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 5
      - name: healthz
        image: gcr.io/google_containers/exechealthz:1.0
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.kube-system.svc.cluster.local 127.0.0.1 >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.
[root@wlan-cloudserver31 dns]# 
```
