### ISSUE TITLE
Add fields to HTTPIngressRuleValue 

### ISSUE THREAD

**Issue by aledbf** [kubernetes/kubernetes#16891]
Currently the file [types.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L559) contains a comment `Consider adding fields for ingress-type specific global`

Is possible to define some of this fields?

_I wish it could be possible to add this ones:_
- sessionAffinity
- algorithm
- keepAlive

The it could be possible to define something like:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    http:
      sessionAffinity: true
      algorithm: leastconn
      keepAlive: 75000
      paths:
      - path: /foo
        backend:
          serviceName: s1
          servicePort: 80
      - path: /bar
        backend:
          serviceName: s2
          servicePort: 80
```

Thanks

**Comment by bprashanth** [comment]
I like this idea, but I don't know if this is something we should expose to users. On one hand it makes going from Ingress -> loadbalancer configuration really straightforward, on the other, we're stuck with the same problems we have today (complexity: what's the right value for keepAlive? what about server/client/connection timeouts?). 

Another way to address this problem is via admin defined QoS buckets (this class will support 100qps, and each request will be killed at 60m). The user just has to pick a best fit. This makes configuring an Ingress controller a little more complex, but all the user needs to think about is their backend.

Maybe this is overkill and we can get away with sensible defaulting?
Users probably care about "algorithm".

@thockin @smarterclayton @ramr wdyt?

**Comment by smarterclayton** [comment]
Two thoughts.  One, admin sets up the routing config, so is free to choose to support whatever default algorithm they want, but there are always specific apps that have specific needs.  Second, the list of algorithms in haproxy and F5 is pretty deep, and very powerful.  If we do something simple here, we're basically preventing admins from actually tuning individual apps to leverage the power of the underlying tech that is doing their routing.  I like having LCD, but I don't want it to block actually letting routes get somewhat powerful.

For instance, we've been asked to expose at least 3/4 of these for different people at different times in the last few months: https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4.2-balance.  I don't believe we should be adding one field per value here.  But I don't want to create an ingress that cannot expose this complexity if someone wants.

My suggestion would be that we define standard annotations, or annotations that work for specific backends, and let them be optional and implementation specific.  We *might* pick a few core values and put them in ingress, but we should always let those annotations override the specified values.  

Example annotations:

    # haproxy annotation that overrides session affinity algorithm and max keep alive queue
    kubernetes.io/ingress.haproxy.balance=first
    kubernetes.io/ingress.haproxy.max-keep-alive-queue=500

I think we really, really want to be careful about this.  We have to invert the problem so that the types of things you can use are what you need in your environment, not what we expose in the API.

**Comment by bprashanth** [comment]
I like the annotation override, but a lot of people have an aversion to stringly typed interfaces (@thockin I'm looking at you). Eitherway, I think we should target some basic use cases and make sure people can achieve them without annotations. 

Lb configuration is possible at at least 3 scopes:
* per backend
* loadbalancer global
* frontend

I'd like to somehow consolidate all these into a relatively tiny IngressConfig subobject (in theory, a subobject might not be necessary) and only allow a single scope for config options (per IngressBackend?). 

As to what we actually want this conceptual subobject to contain, I think at least:
* Duration - Just set this to whatever timout your backend server closes the connection at, and the controller takes care of the rest.
* Balancing - I think we somehow want to express stickyness but fallback to an algorithm through this one field. I think we can also use this field to express backend drain.

A potential problem with annotation override: how would you target a single IngressBackend (since the Ingress contains multiple hosts, and multiple backends per host)?

**Comment by smarterclayton** [comment]
It's been a while on this, but I feel like we should be really, really
careful before adding things here.  @pweil- had a number of requests from
end users he can detail, they did not stop at just duration and balancing
(and the users needed fixes in order to run real apps) so while the simple
object may suffice for now, it's not actually solving the problem for a
deployer (they are still unable to solve the underlying problem).  We need
an escape hatch in order to support the wonderful and terrible variety of
applications in this.

**Comment by bprashanth** [comment]
Yeah I 100% agree. We need a way to break the glass when we need to. There have been a few discussions on bugs/docs lately (it's a general problem, just more obvious for Ingress). I'll try to collect thoughts update sometime next week, or poke @thockin to write some prose.

**Comment by smarterclayton** [comment]
See https://github.com/openshift/origin/pull/5253 for Paul's proposal and
my feedback.


On Nov 20, 2015, at 6:45 PM, Prashanth B <notifications@github.com> wrote:

Yeah I 100% agree. We need a way to break the glass when we need to. There
have been a few discussions on bugs/docs lately (it's a general problem,
just more obvious for Ingress). I'll try to collect thoughts update
sometime next week, or poke @thockin <https://github.com/thockin> to write
some prose.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/16891#issuecomment-158560613>
.

**Comment by mgoodness** [comment]
I also have a use case (URI rewrites) that I think these fields would facilitate. For example:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    http:
      uri_rewrite: /baz
      paths:
      - path: /foo
        backend:
          serviceName: s1
          servicePort: 80
      - path: /bar
        backend:
          serviceName: s2
          servicePort: 80
```
Would generate this nginx controller config:
```
location /foo {
  proxy_pass http://s1:80;
}

location ~* /bar/ {
  rewrite /bar/(.*) /baz/$1 break;
  proxy_pass http://s2:80;
}
```

**Comment by mgoodness** [comment]
I also have a use case (URI rewrites) that I think these fields would facilitate. For example:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    http:
      uri_rewrite: /baz
      paths:
      - path: /foo
        backend:
          serviceName: s1
          servicePort: 80
      - path: /bar
        backend:
          serviceName: s2
          servicePort: 9080
```
Would (when fed into a template) generate this nginx controller config:
```
location /foo {
  proxy_pass http://s1:80;
}

location ~* /bar/ {
  rewrite /portals/(.*) /baz/$1 break;
  proxy_pass http://s2:9080;
}
```
