### ISSUE TITLE
Running service made pod CrashLoopBackOff - invalid ip

### ISSUE THREAD

**Issue by cdpb** [kubernetes/kubernetes#16906]
Hi there,

I'm running a 3 node coreos kubernetes cluster.

* Kubernetes v1.1.0-alpha.1.1613+ab02443985ed70
 * UPDATE: v1.2.0-alpha.3.185+ff796147f61ab9 didn't fix the problem
* CoreOS 845.0.0

I'm trying to run a docker registry pod:
```
kind: Pod
apiVersion: v1
metadata:
  name: registry
  labels: 
    name: registry
spec:
  containers:
    - name: registry-docker
      image: registry
      ports:
        - containerPort: 5000
      volumeMounts:
      - mountPath: "/tmp/registry"
        name: registry
  volumes:
    - name: registry
      persistentVolumeClaim:
       claimName: registry
```

* Created with flannel IP: 172.16.92.2 

After that I wan't to create a k8s service:

```
apiVersion: v1
kind: Service
metadata:
  labels:
  name: registry
spec:
  ports:
    - port: 5000
  selector:
    name: registry
```

* Created with k8s service IP: 10.10.240.151

* Everything works fine - but if the registry service get rescheduled or you want to create the service befor the host the pod gets in state `CrashLoopBackOff` 
 * Docker logs `Error: 'tcp://10.10.240.151:5000' is not a valid port number.`

In my opinion k8s services should manage a higher level of networking, why does the container even know what k8s service ip is assigned - he shouldn't care !?

UPDATE: Didn't work either with a rc controller between pod and service, seems to be a low level pod problem

Thanks for clarification

**Comment by cdpb** [comment]
Found the error, it's more a docker registry bug/feature.

If the service name is equal to the pod name ( registry ) it will fail because there is a environment variable that disturbed docker registry.

**Comment by imesh** [comment]
@cdpb Can you please explain the cause of this issue bit further? 
Thanks

**Comment by cdpb** [comment]
@imesh sure:

no working service file:

```
apiVersion: v1
kind: Service
metadata:
  labels:
  name: registry
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: registry
  selector:
    run: registry
```

working service file

```
apiVersion: v1
kind: Service
metadata:
  labels:
  name: registry-whatever
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: registry
  selector:
    run: registry
```

So it seems that the kubernetes service name set a environment variable or whatever that disturbed the pod from beeing started. 
So just rename your svc metadata name and everything is fine.
