### ISSUE TITLE
Add basic authentication support for livenessProbe

### ISSUE THREAD

**Issue by johanhaleby** [kubernetes/kubernetes#16910]
For example:

``` yaml
livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        username: user
        password: pass
      initialDelaySeconds: 15
      timeoutSeconds: 1
```
