### ISSUE TITLE
RollingUpdate fails when no pods are scheduled with percentage based limits

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#17000]
See https://github.com/openshift/origin/issues/5787

This is due to rollingUpdate requiring maxSurge or maxUnavailable as seen here:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/rolling_updater.go#L213

Despite my dc having this:

```yaml
strategy:
  resources: {}
  rollingParams:
    intervalSeconds: 1
    maxSurge: 25%
    maxUnavailable: 25%
    timeoutSeconds: 600
    updatePeriodSeconds: 1
  type: Rolling
```

I think the solution is to just set one of the two to 1 if 25% * pod count = 0. It's a bit difficult to code though, as you would have to track if it was a percentage based input and, if so, minimize it at 1 if the other is not in place. Or create a special case if the pod count is zero, return 1.

One option is to leave the error in place and not allow rollingupdates with percentage based limits when the pod count is zero. If you decide to not change the behavior, I'd recommend adding a more descriptive error message (mention scheduled pods = zero).
