### ISSUE TITLE
MESOS: issue with data transfer using Kubernetes service endpoint

### ISSUE THREAD

**Issue by slimshady986** [kubernetes/kubernetes#17015]
Hello,
I wanted to test the throughput of k8s service endpoint on my 3 nodes cluster. So I have settled up a kubernetes service:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: ndvi
  labels:
    type: ndvi
spec:
  containers:
  - name: ndviimage
    image: centos:7
    command: ["/bin/sh","-c"]
    args: ["yum install nc -y && sleep 3600"]
    ports:
    - containerPort: 7000
      restartPolicy: "Never"

apiVersion: v1
kind: Service
metadata:
  name: ndvi
  labels:
    name: ndvi
spec:
  selector:
    type: ndvi
  ports:
  - name: ndviport
    port: 7000
    targetPort: 7000
```

I go into the docker and I use a simple netcat process listening on the port 7000 (nc -l -p 7000)
on another of my slaves, I send some data:
dd if=/dev/urandom bs=1024 count=100 | pv | nc server_ip 7000

Everything works fine, when the amount of data is small. but when the amount is raised to 1Mbyte for example, the transfer blocks (the pv command progress stops)
I was wondering if the problem is on the kubernetes-proxy level because when the transfer is done directly to the docker images (using the local ip of the docker) all is fine even with more data.

I am using kubernetes over mesos.
Kubernetes v1.0.4.9+1222a4258c06e0

Do you have any idea ?
Thanks in advance
