### ISSUE TITLE
elasticsearch-logging-v1 dies and is gone after some minutes

### ISSUE THREAD

**Issue by roflmao** [kubernetes/kubernetes#17160]
Trying to start a elasticsearch-logging-v1 in my GKE 1.1.1 cluster.

Starting with: kubectl create -f es-controller.yaml
I see my 2 pods with  kubectl get pods --namespace kube-system and can log into the pods and see that elasticsearch runs.
After some minutes i get thrown out and my 2 pods are gone. I can not locate any logs regarding this. Where should i start to look?

es-controller.yaml:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-logging-v1
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 2
  selector:
    k8s-app: elasticsearch-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: gcr.io/google_containers/elasticsearch:1.7
        name: elasticsearch-logging         
        resources:
          limits:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
      volumes:
      - name: es-persistent-storage
        emptyDir: {}
```
