### ISSUE TITLE
kubernetes 1.1.1 System error starting container on debian SID

### ISSUE THREAD

**Issue by ltagliamonte** [kubernetes/kubernetes#17215]
I'm running a local kubernetes cluster using vagrant, today i recreated the cluster updating to the latest kubernetes version 1.1.1 and i'm getting the following error creating a simple rc:

```
Name:                           mysql-fp4t5
Namespace:                      dev
Image(s):                       mysql
Node:                           127.0.0.1/127.0.0.1
Start Time:                     Fri, 13 Nov 2015 14:20:33 +0100
Labels:                         app=demo,name=mysql,role=mysqldb
Status:                         Pending
Reason:
Message:
IP:                             172.17.0.2
Replication Controllers:        mysql (1/1 replicas created)
Containers:
  mysql:
    Container ID:       docker://2920575e57d043247f9c2fd5c1763d6ee2e96d82217717687c8c12f800652607
    Image:              mysql
    Image ID:           docker://c29b1276a98ab5da05ca3cd1a97690767cb7f15478e1fd2d2b35fcd7e47b6f4e
    State:              Waiting
      Reason:           RunContainerError
    Ready:              False
    Restart Count:      0
    Environment Variables:
      MYSQL_ROOT_PASSWORD:      password
      MYSQL_USER:               admin
      MYSQL_PASSWORD:           password
      MYSQL_DATABASE:           wordpress
Conditions:
  Type          Status
  Ready         False
No volumes.
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath                           Reason          Message
  ─────────     ────────        ─────   ────                    ─────────────                           ──────          ───────
  2m            2m              1       {scheduler }                                                    Scheduled       Successfully assigned mysql-fp4t5 to 127.0.0.1
  2m            2m              1       {kubelet 127.0.0.1}     implicitly required container POD       Pulled          Container image "gcr.io/google_containers/pause:0.8.0" alre
ady present on machine
  2m            2m              1       {kubelet 127.0.0.1}     implicitly required container POD       Created         Created with docker id ead67f18723d
  2m            2m              1       {kubelet 127.0.0.1}     implicitly required container POD       Started         Started with docker id ead67f18723d
  2m            2m              1       {kubelet 127.0.0.1}                                             FailedSync      Error syncing pod, skipping: open /proc/12935/cgroup: no su
ch file or directory
  2m            2m              1       {kubelet 127.0.0.1}     spec.containers{mysql}                  Pulling         Pulling image "mysql"
  16s           16s             1       {kubelet 127.0.0.1}     spec.containers{mysql}                  Pulled          Successfully pulled image "mysql"
  14s           14s             1       {kubelet 127.0.0.1}     spec.containers{mysql}                  Created         Created with docker id 2920575e57d0
  12s           12s             1       {kubelet 127.0.0.1}     spec.containers{mysql}                  Failed          Failed to start with docker id 2920575e57d0 with error: API
 error (500): Cannot start container 2920575e57d043247f9c2fd5c1763d6ee2e96d82217717687c8c12f800652607: [8] System error: not a directory
```

docker logs output:

```
Timestamp: 2015-11-13 14:23:30.251005569 +0100 CET
Code: System error

Message: not a directory

Frames:

---
0: setupRootfs
Package: github.com/opencontainers/runc/libcontainer
File: rootfs_linux.go@40

---
1: Init
Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
File: standard_init_linux.go@57

---
2: StartInitialization
Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
File: factory_linux.go@242

---
3: initializer
Package: github.com/docker/docker/daemon/execdriver/native
File: init.go@35

---
4: Init
Package: github.com/docker/docker/pkg/reexec
File: reexec.go@26

---
5: main
Package: main
File: docker.go@18

---
6: main
Package: runtime
File: proc.go@63

---
7: goexit
Package: runtime
File: asm_amd64.s@2232
```

i'm using vagrant 1.7.2, docker 1.9 and debian sid:

```
root@debian:~# uname -a
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64 GNU/Linux
root@debian:~# cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"
```

step to reproduce the issue:

```
vagrant init loicfrering/debian-unstable; vagrant up --provider virtualbox
vagrant ssh
sudo -i
apt-get update && apt-get install -y vim curl
curl -sSL https://get.docker.com/ | sh
KUBERNETES_VERSION="1.1.1"
ETH0=$(ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
if [ -z ${ETH0} ]; then
  ETH0=$(ifconfig eth0 | grep inet | grep -v inet6 | tr -s " " | cut -d " " -f3)
fi
docker run --name k8s-etcd --net=host -d gcr.io/google_containers/etcd:2.0.9 /usr/local/bin/etcd --addr=127.0.0.1:4001 --bind-addr=0.0.0.0:4001 --data-dir=/var/etcd/data --initial-cluster-token=skydns-etcd
docker run --name k8s-kubelet --net=host -d -v /var/run/docker.sock:/var/run/docker.sock  gcr.io/google_containers/hyperkube:v${KUBERNETES_VERSION} /hyperkube kubelet --cluster_dns=${ETH0} --cluster_domain=cluster.local --allow-privileged=true --api_servers=http://localhost:8080 --v=2 --address=0.0.0.0 --enable_server --hostname_override=127.0.0.1 --config=/etc/kubernetes/manifests
docker run --name k8s-proxy -d --net=host --privileged gcr.io/google_containers/hyperkube:v${KUBERNETES_VERSION} /hyperkube proxy --master=http://127.0.0.1:8080 --v=2
sleep 20s
docker run --name k8s-kube2sky -d --net=host gcr.io/google_containers/kube2sky:1.11 -domain=cluster.local -kube_master_url=http://127.0.0.1:8080 -etcd-server=http://127.0.0.1:4001
docker run --name k8s-skydns -d --net=host gcr.io/google_containers/skydns:2015-03-11-001 -machines=http://127.0.0.1:4001 -addr=0.0.0.0:53 -domain=cluster.local
```

when kubernetes is up create a a simple namespace with a mysql rc running the following script:

```
#!/bin/bash

KUBERNETES_VERSION="1.1.1"

namespaces=("dev")

if [ ! -f $(pwd)/kubectl ]; then
  wget https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl
  chmod +x kubectl
fi

cat <<- 'EOF' > "mysql-rc.yaml"
kind: ReplicationController
apiVersion: v1
metadata:
  name: mysql
  labels:
    name: mysql-rc
    app: demo
spec:
  replicas: 1
  selector:
    name: mysql
    role: mysqldb
    app: demo
  template:
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
              name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: wordpress
    metadata:
      labels:
        name: mysql
        role: mysqldb
        app: demo
EOF

for namespace in ${namespaces[@]}
do
cat <<- EOF > "namespace.yaml"
  kind: "Namespace"
  apiVersion: "v1"
  metadata: 
    name: ${namespace}
    labels: 
      name: ${namespace}
EOF
./kubectl create -f namespace.yaml

echo "Creating resource in ${namespace} namespace"
./kubectl create --namespace=${namespace} -f mysql-rc.yaml
done

exit 0
```

I have no problem using kubernetes 1.0.6. or running a mysql container manually:

```
root@debian:~# docker run -e MYSQL_ROOT_PASSWORD=password -e MYSQL_USER=admin -e MYSQL_PASSWORD=password -e MYSQL_DATABASE=wordpress mysql
Initializing database
2015-11-13T13:28:48.365485Z 0 [Warning] InnoDB: New log files created, LSN=45790
2015-11-13T13:28:48.496818Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2015-11-13T13:28:48.630085Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 78d68b18-8a0a-11e5-8a8b-0242ac110003.
2015-11-13T13:28:48.639924Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2015-11-13T13:28:48.643809Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2015-11-13T13:28:52.859950Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2015-11-13T13:28:52.861269Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2015-11-13T13:28:52.861725Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
```
