### ISSUE TITLE
When a service has multiple ports, Return "this service has multiple ports".

### ISSUE THREAD

**Issue by drocsid** [kubernetes/kubernetes#17338]
I defined a service with multiple ports and tried to get the endpoint through the proxy.

For example:

```json
curl http://localhost:8001/api/v1/proxy/namespaces/default/services/jenkins/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for \"jenkins\"",
  "code": 500
}
```

```yaml

cat jenkins-svc.yaml                                                                         
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    k8s-app: jenkins
spec:
  selector:
    k8s-app: jenkins
  type:
    NodePort
  ports:
  - name: jenkins1
    port: 8080
    nodePort: 30800
    protocol: TCP
  - name: jenkins2
    port: 50000
    nodePort: 30801
    protocol: TCP
```

A better message would be "this service has multiple ports" or similar.
