### ISSUE TITLE
ingress name-based requires path when service port 80

### ISSUE THREAD

**Issue by reesew** [kubernetes/kubernetes#17348]
ingress.yaml

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: long-running
spec:
  rules:
    - host: specs.example.com
      http:
        paths:
        - backend:
            serviceName: specs-service
            servicePort: 80
```

`kubectl describe ing long-running` returns `googleapi: Error 400: Invalid value for field 'resource.pathMatchers[0].pathRules[0].paths[0]': ''.  Must have between 1 and 1024 character(s), invalid`
changing the `servicePort` to something other than 80, and adding `path: /*` both solve this problem
