### ISSUE TITLE
Ingress without rules is still valid

### ISSUE THREAD

**Issue by johanhaleby** [kubernetes/kubernetes#17376]
The [documentation](http://kubernetes.io/v1.1/docs/user-guide/ingress.html#single-service-ingress) says that you should be able to create an ingress resource like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  backend:
    serviceName: testsvc
    servicePort: 80
```

But if you try to create this (`kubectl create -f some.yaml`) you'll get an error:

```bash
error validating "some.yaml": error validating data: field rules: is required; if you choose to ignore these errors, turn validation off with --validate=false
```
