### ISSUE TITLE
GCE L7 LoadBalancer Controller test should consider GCE 'BACKEND_SERVICES' quota

### ISSUE THREAD

**Issue by andyzheng0831** [kubernetes/kubernetes#17464]
Since this test case was added, we have seen failures in Jenkins trusty job many times. Every failure is due to the same reason as follows:

GCE :Quota: googleapi: Error 403: Quota 'BACKEND_SERVICES' exceeded.  Limit: 3.0

Therefore, the test code itself should take this in consider. Or Jenkins administrator should raise the limit to a big enough value.

**Comment by wonderfly** [comment]
This has also been flaky on the regular gce-slow job that runs test against containervm - 56% stability. I can increase the quota on the test project we use, but am not entirely sure what resource "BACKEND_SERVIECS" refers to. @ixdy  Any idea?

**Comment by andyzheng0831** [comment]
cc/ @bprashanth
cc/ @ixdy

**Comment by bprashanth** [comment]
> Since this test case was added, we have seen failures in Jenkins trusty job many times. Every failure is due to the same reason as follows:
GCE :Quota: googleapi: Error 403: Quota 'BACKEND_SERVICES' exceeded. Limit: 3.0
Therefore, the test code itself should take this in consider. Or Jenkins administrator should raise the limit to a big enough value.

Yes, bump up the quota? That's what I did for all the gce projects. Unfortunately 3 backend services is not high enough to test anything useful. See following for some documentation on quota:
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-loadbalancing/glbc#quota
https://github.com/kubernetes/contrib/tree/master/Ingress/controllers/gce#disclaimer

If you can't bump up the quota I can probably figure out a way to give you a slim version that only tests 1 backend.

> This has also been flaky on the regular gce-slow job that runs test against containervm - 56% stability. I can increase the quota on the test project we use,

Recent gce-slow flakes are https://github.com/kubernetes/kubernetes/pull/17409

Also see: https://github.com/kubernetes/kubernetes/issues/17119  in case you're trying to run multiple instances of the test in parallel in the same project, it won't currently handle the parallelism. So I recommend 1 test at a time in 1 project till that bug is fixed.

**Comment by bprashanth** [comment]
Backend services is gce backend services. For reference this is my quota request (higher than you probably need):
```
Number of Forwarding Rules: 35
Number of Target HTTP Proxies: 35
Number of Target HTTPS Proxies: 35
Number of URL Maps: 35
Number of Backend Services: 35
Number of Global External In-Use IP Addresses: 35
```

**Comment by wonderfly** [comment]
My project has 75 as "Backend Services" limit, however the doc you pointed out says that
>GLBC is not aware of your GCE quota.

How do I increase the quota per Ingress? The GCE quota documentation doesn't mention anything like that either.

```
quotas:
- limit: 25000.0
  metric: SNAPSHOTS
  usage: 0.0
- limit: 125.0
  metric: NETWORKS
  usage: 2.0
- limit: 2500.0
  metric: FIREWALLS
  usage: 6.0
- limit: 2500.0
  metric: IMAGES
  usage: 0.0
- limit: 700.0
  metric: STATIC_ADDRESSES
  usage: 0.0
- limit: 2500.0
  metric: ROUTES
  usage: 4.0
- limit: 375.0
  metric: FORWARDING_RULES
  usage: 0.0
- limit: 1250.0
  metric: TARGET_POOLS
  usage: 0.0
- limit: 1250.0
  metric: HEALTH_CHECKS
  usage: 0.0
- limit: 2300.0
  metric: IN_USE_ADDRESSES
  usage: 0.0
- limit: 1250.0
  metric: TARGET_INSTANCES
  usage: 0.0
- limit: 250.0
  metric: TARGET_HTTP_PROXIES
  usage: 0.0
- limit: 250.0
  metric: URL_MAPS
  usage: 0.0
- limit: 75.0
  metric: BACKEND_SERVICES
  usage: 0.0
- limit: 2500.0
  metric: INSTANCE_TEMPLATES
  usage: 0.0
- limit: 125.0
  metric: TARGET_VPN_GATEWAYS
  usage: 0.0
- limit: 250.0
  metric: VPN_TUNNELS
  usage: 0.0
- limit: 250.0
  metric: TARGET_HTTPS_PROXIES
  usage: 0.0
- limit: 250.0
  metric: SSL_CERTIFICATES
  usage: 0.0
```
