### ISSUE TITLE
Add port based routing to ingress resource

### ISSUE THREAD

**Issue by johanhaleby** [kubernetes/kubernetes#17571]
I'd like to use an ingress resource to create an HTTP Load Balancer in GKE but I'd like to do port based routing. Something like:

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:  
  - http:
      ports:
      - port: 80
        backend:
          serviceName: service
          servicePort: 80
      - port: 443
        backend:
          serviceName: service
          servicePort: 80
      - port: 81
        backend:
          serviceName: service
          servicePort: 81
      - port: 4433
        backend:
          serviceName: service
          servicePort: 81
```

The reason I want to use an ingress and not just a service of type LoadBalancer is that I want to be ready for Kubernetes 1.2 that will have https support for the http load balancer.
