### ISSUE TITLE
internal elbs in AWS

### ISSUE THREAD

**Issue by mahehss** [kubernetes/kubernetes#17620]
When I give service Type as LoadBalancer it creates an elb in my AWS environment. Can I somehow make it internal elb?

**Comment by jessesanford** [comment]
I also would like to launch internal elbs. I can see that there is reference to a boolean for this purpose here:
https://github.com/kubernetes/kubernetes/blob/f3af5d26a4930c9a0414eafd7e6dae10313de39a/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L45
Anyone have any idea how to set that flag from the user facing cli?

**Comment by pdbogen** [comment]
Digging around in the code, it looks like you just need to add an annotation named "kubernetes.io/role/internal-elb" with any non-blank value to your service.

The code @jessesanford links to is called by the AWS cloud provider's "ensureLoadBalancer" (https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/cloudprovider/providers/aws/aws.go#L2103), which in turn checks the annotation I mention to decide whether to pass true or false (https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/cloudprovider/providers/aws/aws.go#L2139).

**Comment by jessesanford** [comment]
Thanks @pdbogen I am using the coreos kube-aws command line utility to generate most of my configs. Where do I put the annotation you mention?

**Comment by pdbogen** [comment]
You'd annotate a *server* that has Type: LoadBalancer, in the metadata, a lá:
```
kind: Service
apiVersion: v1
metadata:
    name: someService
    annotations:
        - name: services.beta.kubernetes.io/aws-load-balancer-internal
          value: 0.0.0.0/0
```

...but YMMV, the code is not _super_ easy to read for this, and it's not documented yet, as you might guess from the "beta" smack in the middle of the annotation name. It'll probably also break when the feature leaves beta, though _maybe_ they'll check the old annotation too. There are also some other limitations around subnet selection (https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/cloudprovider/providers/aws/aws.go#L2044), which might make it unusable in the current state.

**Comment by acmcelwee** [comment]
Just for anyone who stumbles upon this trying to get internal elbs working on AWS, @pdbogen's suggestion needs a tiny substitition, and it works like a charm.

`s/services\.beta/service.beta/`

Obviously, the code referenced is correct, but I figured I'd save someone else the couple minutes I spent trying it the other way.

**Comment by sstarcher** [comment]
```
kind: Service
apiVersion: v1
metadata:
    name: someService
    annotations:
        services.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```
