### ISSUE TITLE
Ingress serviceSelector

### ISSUE THREAD

**Issue by guybrush** [kubernetes/kubernetes#17686]
currently a service for an ingress-backend can only be selected by service-name (see https://github.com/kubernetes/kubernetes/blob/ba383bc/pkg/apis/extensions/v1beta1/types.go#L588-L595)

would it be possible to support service-selection by using a label-selector (similar to service.spec.selector)?

currently i have to write long descriptive service-names like that:

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: projectX
spec:
  rules:
    - host: projectX.com
      http:
        paths:
          - path: /
            backend:
              serviceName: projectX-production-webFrontend
              servicePort: 80
```

i would like to do something like that:

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: projectX
spec:
  rules:
    - host: projectX.com
      http:
        paths:
          - path: /
            backend:
              serviceSelector: 
                project: X
                environment: production
                component: webFrontend
              servicePort: 80
```
