### ISSUE TITLE
GKE Manually-created external IP forwarding (I think) issue.

### ISSUE THREAD

**Issue by lgomez** [kubernetes/kubernetes#17901]
Hello again,

I'm struggling to figure this out. I've followed official and unofficial instructions to the best of my abilities but still can't make a service available externally. Here's what I've got:

###### A minimal cluster
```sh
# gcloud container clusters list

NAME     ZONE           MASTER_VERSION  MASTER_IP        MACHINE_TYPE  NUM_NODES  STATUS
testing  us-central1-c  1.1.2           130.211.167.255  f1-micro      3          RUNNING
```
###### A manually created static IP address
```sh
# gcloud compute addresses list

NAME   REGION      ADDRESS      STATUS
api-ip us-central1 8.32.416.296 IN_USE
```
###### The following forwarding rules (note the _api-server_ rule in particular)
```sh
# gcloud compute forwarding-rules list

NAME                             REGION      IP_ADDRESS     IP_PROTOCOL TARGET
a76e3e06895b311e5ab3142010af000f us-central1 104.197.62.222 TCP         us-central1/targetPools/a76e3e06895b311e5ab3142010af000f
api-server                       us-central1 8.32.416.296   TCP         us-central1/targetPools/api-target-pool
```
###### The target pools
```sh
# gcloud compute target-pools list

NAME                             REGION      SESSION_AFFINITY BACKUP HEALTH_CHECKS
a76e3e06895b311e5ab3142010af000f us-central1
api-target-pool                  us-central1                         api-health-check
```
###### Firewall rules 
```sh
# gcloud compute firewall-rules list

NAME                                    NETWORK SRC_RANGES         RULES                        SRC_TAGS TARGET_TAGS
api-allow-public                        default 0.0.0.0/0          tcp                                   gke-testing-421bc6b9-node
```
###### My svc/rc file
```yaml
# kubectl create -f api.yaml
# kubectl delete -f api.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app: api
spec:
  type: LoadBalancer
  externalIPs: [8.32.416.296]
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: api
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: api-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        release: canary # canary
        environment: prototyping # dev, qa
        tier: frontend # backend, cache
        # customer: customerA
        # track: daily #weekly
        app: api
    spec:
      # volumes:
      # - name: secret-volume
      #   secret:
      #     secretName: nginxsecret
      containers:
      - name: api
        image: tutum/hello-world
        ports:
        - containerPort: 80
        # volumeMounts:
        # - mountPath: /etc/nginx/ssl
        #   name: secret-volume
```
I understand these things can and do get generated automatically when I set `type: LoadBalancer` in there but there must be a way I can do all these manually so I can have more fine-grained control over things like naming throughout the different resources in my cluster.

Any ideas regarding what I may be doing wrong?

Thanks!

**Comment by lgomez** [comment]
Oh god... Stupid mistake. Just noticed it as I was re-reading my post. I was using the `tutum/hello-world` image which exposes 80 not 3000. So I changed:

```yaml
spec:
  type: LoadBalancer
  externalIPs: [8.32.416.296]
  ports:
  - port: 3000
    targetPort: 80
```
to...
```yaml
spec:
  type: LoadBalancer
  externalIPs: [8.32.416.296]
  ports:
  - port: 3000
    targetPort: 80
```
Thank you and sorry for the noise.
