### ISSUE TITLE
Need a https liveness probe

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#18226]
I saw a proposal to extend liveness probe to https, websocket, etc., but that didn't go anywhere. Can the liveness probe be extended to at least support https?

**Comment by liggitt** [comment]
The `httpGet` probe already supports a `scheme` field that can be `HTTP` (default) or `HTTPS`

See http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_httpgetaction

**Comment by jeremywadsack** [comment]
Updated link to documentation:

https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_httpgetaction

Example use:

```
        livenessProbe:
          httpGet:
            path: /live
            port: 443
            scheme: https
```
