### ISSUE TITLE
Can't setup DNS add-on with local Docker setup

### ISSUE THREAD

**Issue by ericandrewlewis** [kubernetes/kubernetes#18626]
I've successfully set up Kubernetes on Docker locally following the [Getting Started Guide](https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/docker.md). 

Now I'm trying to setup the DNS add-on, and having issues. This might be a dupe of #16836, but I don't want to add noise to that discussion if it isn't.

I've modified the `kubelet` boot-up command according to [the DNS add-on configuration](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns#how-do-i-configure-it), so that looks like

```bash
docker run \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/dev:/dev \
    --volume=/var/lib/docker/:/var/lib/docker:ro \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    -d \
    gcr.io/google_containers/hyperkube:v1.0.1 \
    /hyperkube kubelet --containerized --hostname-override="127.0.0.1" --address="0.0.0.0" --api-servers=http://localhost:8080 --config=/etc/kubernetes/manifests --cluster-dns=10.0.0.10 --cluster-domain=cluster.local
```

And I've booted up the DNS service and replication controller based on the examples in the docs ([rc](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-rc.yaml.in), [svc](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/skydns-svc.yaml.in)) modifying templating variables accordingly. 

Here's the rc:

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v9
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v9
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v9
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v9
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        command:
        - /usr/local/bin/etcd
        - -data-dir
        - /var/etcd/data
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
        volumeMounts:
        - name: etcd-storage
          mountPath: /var/etcd/data
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.11
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/kube2sky"
        - -domain=cluster.local
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-10-13-8c72f8c
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/skydns"
        - -machines=http://127.0.0.1:4001
        - -addr=0.0.0.0:53
        - -ns-rotate=false
        - -domain=cluster.local.
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 5
      - name: healthz
        image: gcr.io/google_containers/exechealthz:1.0
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.
```

and the service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.0.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```

I've turned off the liveness and readiness probe, because they are causing infinite pod restarts.

Attempting to do an nslookup inside of a container returns the wrong IP for the kubernetes.default service. Expected: 10.0.0.1, actual: 198.105.254.228.

```
docker@kubernetes:~$ kubectl exec busybox -- nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      kubernetes.default
Address 1: 198.105.254.228
Address 2: 198.105.244.228
docker@kubernetes:~$ kubectl exec busybox -- nslookup 
docker@kubernetes:~$ kubectl get services
NAME         LABELS                                    SELECTOR    IP(S)       PORT(S)
kubernetes   component=apiserver,provider=kubernetes   <none>      10.0.0.1    443/TCP
nginx        run=nginx                                 run=nginx   10.0.0.49   80/TCP
```

Looking into the logs, it looks like kube2sky can't talk to the Kubernetes API.

```
docker@kubernetes:~$ kubectl logs --namespace=kube-system kube-dns-v9-ooz2c kube2sky
I1212 21:56:51.986778       1 kube2sky.go:389] Etcd server found: http://127.0.0.1:4001
I1212 21:56:52.990598       1 kube2sky.go:455] Using http://localhost:8080 for kubernetes master
I1212 21:56:52.990611       1 kube2sky.go:456] Using kubernetes API 
E1212 21:56:52.991696       1 reflector.go:136] Failed to list *api.Service: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value
E1212 21:56:52.991794       1 reflector.go:136] Failed to list *api.Endpoints: couldn't get version/kind; json parse error: invalid character '<' looking for beginning of value
```

**Comment by dalanlan** [comment]
@ericandrewlewis
The following log shows that you might get a wrong configuration.
`I1212 21:56:52.990598       1 kube2sky.go:455] Using http://localhost:8080 for kubernetes master` 
Try to pass a proper flag `--kube_master_url=http://{kube-api-server}:8080` for kube2sky

**Comment by luxas** [comment]
This will probably be fixed when #17213 is merged.
Now, serviceAccounts doesn't work by default when using k8s-in-docker.

However you may bypass it in two ways:
 - option 1 
   - pass `--kube_master_url=http://{kube-api-server}:8080` to `kube2sky` (easy and good, however can fail in some scenarios when master ip has changed)
 - option 2 (warning: hackish)
   - pull hyperkube `v1.1.1`
   - download this file: https://github.com/luxas/kubernetes/blob/16987-default-serviceaccount-secret-hyperkube/cluster/images/hyperkube/master.json
   - replace ARCH to `amd64` and VERSION to `v1.1.1` in the master.json file
   - add this to your `kubelet` command: 
   - `--volume={absolute path of your master.json}:/etc/kubernetes/manifests/master.json`

Yes, the other option is too complicated at the moment. It enables serviceAccounts that are expected by the default configuration.
#17213 will fix this in future releases.

Hope it helps!

**Comment by ericandrewlewis** [comment]
Thanks for the help! How do I figure out what the IP of the master server is?

**Comment by luxas** [comment]
That's the problem! :smile:
Well, since you run it locally, just type `hostname -i`, `hostname -I` or `ip addr` to see which ip you have

**Comment by ericandrewlewis** [comment]
If i run `hostname -i` inside the VM running Kubernetes, I see `127.0.0.1`, i.e. `localhost`. I guess this is part of the problem — the machine provisioned in the guide doesn't have an IP addressable from inside of a container?

**Comment by luxas** [comment]
Try the other commands... (`hostname -I` often works when `i` doesn't)

**Comment by ericandrewlewis** [comment]
From running the commands, I see these results:

```
docker@kubernetes:~$ hostname -i
127.0.0.1
docker@kubernetes:~$ hostname -I
hostname: invalid option -- 'I'
BusyBox v1.23.1 (2015-02-22 15:53:49 UTC) multi-call binary.

Usage: hostname [OPTIONS] [HOSTNAME | -F FILE]

Get or set hostname or DNS domain name

	-s	Short
	-i	Addresses for the hostname
	-d	DNS domain name
	-f	Fully qualified domain name
	-F FILE	Use FILE's content as hostname

docker@kubernetes:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 1a:c5:1e:f3:20:fe brd ff:ff:ff:ff:ff:ff
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:d9:a7:11 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fed9:a711/64 scope link 
       valid_lft forever preferred_lft forever
4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:57:c1:e3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.100/24 brd 192.168.99.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe57:c1e3/64 scope link 
       valid_lft forever preferred_lft forever
6: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:7b:ec:44:dd brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:7bff:feec:44dd/64 scope link 
       valid_lft forever preferred_lft forever
36: vethf0a75fe@if35: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 76:3b:f7:6b:db:9d brd ff:ff:ff:ff:ff:ff
    inet6 fe80::743b:f7ff:fe6b:db9d/64 scope link 
       valid_lft forever preferred_lft forever
```

I'm not too familiar with the `ip addr` return, but I guess that the master machine has an IP of `10.0.2.15`, `192.168.99.100`, or `172.17.0.1`. 

A container should be able to reach the master machine (as kube2sky will need to), so I log into a container and curl each of them. All of them fail.

```
docker@kubernetes:~$ kubectl exec nginx-5otq9 -it bash
root@nginx-5otq9:/# curl 10.0.2.15
curl: (7) Failed to connect to 10.0.2.15 port 80: Connection refused
root@nginx-5otq9:/# curl 192.168.99.100
curl: (7) Failed to connect to 192.168.99.100 port 80: Connection refused
root@nginx-5otq9:/# curl 172.17.0.1
curl: (7) Failed to connect to 172.17.0.1 port 80: Connection refused
root@nginx-5otq9:/# curl 10.0.2.15:8080
curl: (7) Failed to connect to 10.0.2.15 port 8080: Connection refused
root@nginx-5otq9:/# curl 192.168.99.100:8080
curl: (7) Failed to connect to 192.168.99.100 port 8080: Connection refused
root@nginx-5otq9:/# curl 172.17.0.1:8080
curl: (7) Failed to connect to 172.17.0.1 port 8080: Connection refused
```

**Comment by luxas** [comment]
OK, test `kubectl cluster-info` instead when your cluster is up. That will do it.

**Comment by ericandrewlewis** [comment]
Running `kubectl cluster-info` gives me this response:

```
docker@kubernetes:~$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080
```

**Comment by luxas** [comment]
Oops, forgot that. Try `kubectl get no` and `kubectl describe no <your node>`

**Comment by luxas** [comment]
BTW, are you running `master` or `master-multi`? Also, try `netstat -nlp`

**Comment by ericandrewlewis** [comment]
`kubectl get no` results:

```
docker@kubernetes:~$ kubectl get no
NAME        LABELS                             STATUS
127.0.0.1   kubernetes.io/hostname=127.0.0.1   Ready
```

`kubectl describe no` results:
```
docker@kubernetes:~$ kubectl describe no 127.0.0.1
Name:			127.0.0.1
Labels:			kubernetes.io/hostname=127.0.0.1
CreationTimestamp:	Mon, 14 Dec 2015 18:29:32 +0000
Conditions:
  Type		Status	LastHeartbeatTime			LastTransitionTime			Reason					Message
  Ready 	True 	Mon, 14 Dec 2015 18:30:02 +0000 	Mon, 14 Dec 2015 18:29:32 +0000 	kubelet is posting ready status 	
Addresses:	127.0.0.1
Capacity:
 cpu:		0
 memory:	0
 pods:		40
Version:
 Kernel Version:		
 OS Image:			
 Container Runtime Version:	
 Kubelet Version:		
 Kube-Proxy Version:		
ExternalID:			127.0.0.1
Pods:				(1 in total)
  Namespace			Name
  default			k8s-master-127.0.0.1
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath	Reason			Message
  Mon, 14 Dec 2015 18:29:19 +0000	Mon, 14 Dec 2015 18:29:19 +0000	1	{kubelet 127.0.0.1}			starting		Starting kubelet.
  Mon, 14 Dec 2015 18:29:19 +0000	Mon, 14 Dec 2015 18:29:19 +0000	1	{kubelet 127.0.0.1}			kubeletSetupFailed	Failed to start CAdvisor cAdvisor is unsupported in this build
  Mon, 14 Dec 2015 18:29:19 +0000	Mon, 14 Dec 2015 18:29:19 +0000	1	{kubelet 127.0.0.1}			kubeletSetupFailed	Failed to start OOM watcher cAdvisor is unsupported in this build
  Mon, 14 Dec 2015 18:29:19 +0000	Mon, 14 Dec 2015 18:29:32 +0000	7	{kubelet 127.0.0.1}			NodeReady		Node 127.0.0.1 status is now: NodeReady
```

`netstat -nlp` results:

```
docker@kubernetes:~$ sudo netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      9730/hyperkube
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2017/sshd
tcp        0      0 127.0.0.1:7001          0.0.0.0:*               LISTEN      9623/etcd
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      9641/hyperkube
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      9671/hyperkube
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      9743/hyperkube
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      9716/hyperkube
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      9623/etcd
tcp        0      0 :::55023                :::*                    LISTEN      9671/hyperkube
tcp        0      0 :::10255                :::*                    LISTEN      9641/hyperkube
tcp        0      0 :::22                   :::*                    LISTEN      2017/sshd
tcp        0      0 :::4001                 :::*                    LISTEN      9623/etcd
tcp        0      0 :::2376                 :::*                    LISTEN      2299/docker
tcp        0      0 :::10250                :::*                    LISTEN      9641/hyperkube
tcp        0      0 :::6443                 :::*                    LISTEN      9730/hyperkube
udp        0      0 0.0.0.0:68              0.0.0.0:*                           2049/udhcpc
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
unix  2      [ ACC ]     STREAM     LISTENING      19434 2299/docker         /var/lib/docker/network/files/19679e45e81f4b6025a7b65b8f5626929b6d81a8b0ab551951db22a1b560906e.sock
unix  2      [ ACC ]     STREAM     LISTENING      17796 2021/acpid          /var/run/acpid.socket
unix  2      [ ACC ]     STREAM     LISTENING      19367 2299/docker         /var/run/docker.sock
unix  2      [ ACC ]     SEQPACKET  LISTENING      14286 191/udevd           /run/udev/control
```

> BTW, are you running master or master-multi?

I'm running master on a single machine, following the [Running Kubernetes locally via Docker guide](https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/docker.md). I might try the [Docker multi-node guide](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode.md) to see if that makes any more sense of this.

Thanks a lot for your help with this :smile: I hope whatever we figure out here

**Comment by luxas** [comment]
Yes, there's the problem!
> `tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      9730/hyperkube`
When you are using `docker`, `apiserver` just listens to `localhost` and therefore `curl 192.168.99.100:8080` didn't work.

Before you switch to `docker-multinode` just make this change and test again `--config=/etc/kubernetes/manifests-multi`

**Comment by luxas** [comment]
However, this is going to be a lot simplier in the future :)

**Comment by ericandrewlewis** [comment]
I finally got this working. Thanks a ton to both @dalanlan and @luxas :smile: 

I ended up finding the IP of the master via `docker-machine ls`, here it's `192.168.99.100`

```bash
$ docker-machine ls
NAME         ACTIVE   DRIVER       STATE     URL                         SWARM   ERRORS
default      -        virtualbox   Stopped                                       
kubernetes   -        virtualbox   Running   tcp://192.168.99.100:2376           
```

I injected this into the `kube2sky` start-up command [as @dalanlan suggested](https://github.com/kubernetes/kubernetes/issues/18626#issuecomment-164229840) and also switched to the multinode config bootstrap [as @luxas suggested](https://github.com/kubernetes/kubernetes/issues/18626#issuecomment-164521814).

Closing this out.

**Comment by ericandrewlewis** [comment]
For my own reference (and perhaps others), to get this working correctly, follow 
the [getting started guide instructions](https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/getting-started-guides/docker.md)
with these caveats.

Run the master kubelet like so

```bash
docker run \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/dev:/dev \
    --volume=/var/lib/docker/:/var/lib/docker:ro \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    -d \
    gcr.io/google_containers/hyperkube:v1.0.1 \
    /hyperkube kubelet --containerized --hostname-override="127.0.0.1" --address="0.0.0.0" --api-servers=http://localhost:8080 --config=/etc/kubernetes/manifests-multi --cluster-dns=10.0.0.10 --cluster-domain=cluster.local
```

Create the Kubernetes DNS replication controller. Replace `{{IP address of the master}}`
with the address of your master machine.

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v9
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v9
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v9
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v9
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        command:
        - /usr/local/bin/etcd
        - -data-dir
        - /var/etcd/data
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
        volumeMounts:
        - name: etcd-storage
          mountPath: /var/etcd/data
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.11
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/kube2sky"
        - -domain=cluster.local
        - -kube_master_url=http://{{IP address of the master}}:8080
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-10-13-8c72f8c
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/skydns"
        - -machines=http://127.0.0.1:4001
        - -addr=0.0.0.0:53
        - -ns-rotate=false
        - -domain=cluster.local.
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      - name: healthz
        image: gcr.io/google_containers/exechealthz:1.0
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.
```

and its corresponding service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.0.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```
