### ISSUE TITLE
DaemonSet doesn't create any pods: v1.1.3

### ISSUE THREAD

**Issue by sheriffmohamed** [kubernetes/kubernetes#18656]
Hi,

I've been trying to run the example for DaemonSets with no luck:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
spec:
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        daemon: prom-node-exp
    spec:
      containers:
      - name: c
        image: prom/prometheus
        ports:
        - containerPort: 9090
          hostPort: 9090
          name: serverport
```

## The Problem
The DaemonSet gets created successfully, but no pods are getting created on any of the nodes. But when I go to describe the DaemonSet, I get the following:

```
Name:		prometheus-node-exporter
Image(s):	prom/prometheus
Selector:	daemon=prom-node-exp
Node-Selector:	<none>
Labels:		daemon=prom-node-exp
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Misscheduled: 0
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
No events.
```

The odd thing is that it's showing the Desired Number of Nodes set to zero. I have even tried to use the selector directive with a specific node and still no luck same outcome as above.

## Env Spec
Here are the specs of the environment:

* AWS
* Used kube-up
* All nodes are m3.xlarge
* Kubernetes server and client are both v1.1.3
* Updated the ```/etc/kubernetes/manifest/kube-apiserver.manifest``` to enable DaemonSets by adding ```--runtime-config=extensions/v1beta1/daemonsets=true``` to the command
* Then did a ```service salt-master restart```
* Nothing is running on the cluster other than kube-system obviously

Thank you for the help in advanced!
