### ISSUE TITLE
kubectl logs not working on k8sm

### ISSUE THREAD

**Issue by huang195** [kubernetes/kubernetes#18681]
I just did a pull from the HEAD and using mesos 0.25. To reproduce, I use a very simple guestbook yaml:

```
apiVersion: v1
kind: Pod
metadata:
  name: guestbook
spec:
  containers:
  - name: redis
    image: redis
  - name: guestbook
    image: google/guestbook-python-redis
    ports:
    - name: www
      containerPort: 80
```

Creating the pod with `kubect create -f guestbook.yaml`. After the pod is showing as RUNNING, run `kubectl logs -c redis guestbook` will result in the following error message:

```
Error from server: the server could not find the requested resource ( Pod guestbook)
```

This only seems to impact k8sm setup, and k8s-standalone works as expected.

cc @jdef @sttts
