### ISSUE TITLE
Horizontal pod autoscaling tests are broken

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#18845]
These tests are failing:

    Horizontal pod autoscaling (scale resource: CPU) [Skipped] [Autoscaling] ReplicationController Should scale from 1 pod to 3 pods and from 3 to 5

    Horizontal pod autoscaling (scale resource: CPU) [Skipped] [Autoscaling] ReplicationController Should scale from 5 pods to 3 pods and from 3 to 1

They failed first in:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-autoscaling/2089/

will fail in the current run too (probably they were broken by some change...)

This is blocking merge-queue

@k8s-oncall @kubernetes/goog-testing 
@piosz @mwielgus @jszczepkowski @fgrzadkowski

**Comment by wojtek-t** [comment]
@ArtfulCoder - since you're current oncall - can you please take a look?

**Comment by ArtfulCoder** [comment]
investigating.

**Comment by ArtfulCoder** [comment]
Am seeing the followin error in the log: Node is out of sufficient disk.

Could this be another quota issue ?


*08:10:56* Latency metrics for node
e2e-autoscaling-minion-so3z*08:10:56* Dec 17 08:10:56.281: INFO:
{Operation: Method:pod_start_latency_microseconds Quantile:0.9
Latency:10m32.051945s}*08:10:56* Dec 17 08:10:56.281: INFO:
{Operation: Method:pod_start_latency_microseconds Quantile:0.99
Latency:10m32.051945s}*08:10:56* Dec 17 08:10:56.281: INFO:
{Operation: Method:pod_start_latency_microseconds Quantile:0.5
Latency:10m32.051945s}*08:10:56* Dec 17 08:10:56.281: INFO: Waiting up
to 1m0s for all nodes to be ready*08:10:56* Dec 17 08:10:56.458: INFO:
Node e2e-autoscaling-minion-1dun condition 1/2: type: OutOfDisk,
status: False, reason: "KubeletHasSufficientDisk", message: "kubelet
has sufficient disk space available", last transition time: 2015-12-17
07:39:03 -0800 PST*08:10:56* Dec 17 08:10:56.458: INFO: Node
e2e-autoscaling-minion-1dun condition 2/2: type: Ready, status: True,
reason: "KubeletReady", message: "kubelet is posting ready status",
last transition time: 2015-12-17 07:40:13 -0800 PST*08:10:56* Dec 17
08:10:56.458: INFO: Successfully found condition Ready of node
e2e-autoscaling-minion-1dun to be true*08:10:56* Dec 17 08:10:56.458:
INFO: Node e2e-autoscaling-minion-3132 condition 1/2: type: OutOfDisk,
status: False, reason: "KubeletHasSufficientDisk", message: "kubelet
has sufficient disk space available", last transition time: 2015-12-17
07:38:58 -0800 PST*08:10:56* Dec 17 08:10:56.458: INFO: Node
e2e-autoscaling-minion-3132 condition 2/2: type: Ready, status: True,
reason: "KubeletReady", message: "kubelet is posting ready status",
last transition time: 2015-12-17 07:40:08 -0800 PST*08:10:56* Dec 17
08:10:56.458: INFO: Successfully found condition Ready of node
e2e-autoscaling-minion-3132 to be true*08:10:56* Dec 17 08:10:56.458:
INFO: Node e2e-autoscaling-minion-so3z condition 1/2: type: OutOfDisk,
status: False, reason: "KubeletHasSufficientDisk", message: "kubelet
has sufficient disk space available", last transition time: 2015-12-17
07:39:03 -0800 PST*08:10:56* Dec 17 08:10:56.458: INFO: Node
e2e-autoscaling-minion-so3z condition 2/2: type: Ready, status: True,
reason: "KubeletReady", message: "kubelet is posting ready status",
last transition time: 2015-12-17 07:40:24 -0800 PST*08:10:56* Dec 17
08:10:56.458: INFO: Successfully found condition Ready of node
e2e-autoscaling-minion-so3z to be true*08:10:56* *STEP*: Destroying
namespace "e2e-tests-horizontal-pod-autoscaling-7gyzv" for this suite.

**Comment by ArtfulCoder** [comment]
I could reproduce this in a manual test run as well on my own e2e cluster.

**Comment by ArtfulCoder** [comment]
I see the following error that seems relevant:

Dec 17 12:42:11.923: INFO: event for rc: {horizontal-pod-autoscaler } FailedGetMetrics: failed to get CPU consumption and request: failed to unmarshall heapster response: invalid character 'h' in literal true (expecting 'r')
Dec 17 12:42:11.923: INFO: event for rc: {horizontal-pod-autoscaler } FailedComputeReplicas: failed to get cpu utilization: failed to get CPU consumption and request: failed to unmarshall heapster response: invalid character 'h' in literal true (expecting 'r')
Dec 17 12:42:11.923: INFO: event for rc: {horizontal-pod-autoscaler } FailedRescale: New size: 1; error: Internal error occurred: no kind {extensions  replicationcontrollers} has been defined; known resources: map[{ v1 serviceaccountlists}:{ v1 serviceaccountlist} { v1 componentstatuses}:{ v1 componentstatus} { v1 services}:{ v1 service} { v1 endpoints}:{ v1 endpoints} { v1 resourcequotalists}:{ v1 resourcequotalist} { v1 podtemplates}:{ v1 podtemplate} { v1 serializedreferences}:{ v1 serializedreference} { v1 nodelists}:{ v1 nodelist} { v1 nodes}:{ v1 node} { v1 exportoptionses}:{ v1 exportoptions} { v1 podtemplatelists}:{ v1 podtemplatelist} { v1 bindings}:{ v1 binding} { v1 replicationcontrollers}:{ v1 replicationcontroller} { v1 secretlists}:{ v1 secretlist} { v1 namespacelists}:{ v1 namespacelist} { v1 persistentvolumelists}:{ v1 persistentvolumelist} { v1 lists}:{ v1 list} { v1 secrets}:{ v1 secret} { v1 replicationcontrollerlists}:{ v1 replicationcontrollerlist} { v1 persistentvolumeclaimlists}:{ v1 persistentvolumeclaimlist} { v1 eventlists}:{ v1 eventlist} { v1 resourcequotas}:{ v1 resourcequota} { v1 persistentvolumes}:{ v1 persistentvolume} { v1 limitranges}:{ v1 limitrange} { v1 pods}:{ v1 pod} { v1 componentstatuslists}:{ v1 componentstatuslist} { v1 servicelists}:{ v1 servicelist} { v1 serviceaccounts}:{ v1 serviceaccount} { v1 rangeallocations}:{ v1 rangeallocation} { v1 events}:{ v1 event} { v1 namespaces}:{ v1 namespace} { v1 endpointslists}:{ v1 endpointslist} { v1 podlists}:{ v1 podlist} { v1 persistentvolumeclaims}:{ v1 persistentvolumeclaim} { v1 podstatusresults}:{ v1 podstatusresult} { v1 limitrangelists}:{ v1 limitrangelist}]

**Comment by ArtfulCoder** [comment]
The outofdisk errors seem to occur even on successful runs. (so it should not be causing the failure)

**Comment by wojtek-t** [comment]
It seems like a cleear regression - it was constantly passing and now it's constantly failing. It seems that it must have been caused by one of the PRs merged around that time...

**Comment by ArtfulCoder** [comment]
The other issue in this failure seems to be that the HPA cant figure out cpu resource

30s         0s         2         rc                            HorizontalPodAutoscaler                         Warning   FailedGetMetrics        {horizontal-pod-autoscaler }               failed to get CPU consumption and request: metrics obtained for 0/1 of pods
30s         0s         2         rc                            HorizontalPodAutoscaler                         Warning   FailedComputeReplicas   {horizontal-pod-autoscaler }               failed to get cpu utilization: failed to get CPU consumption

**Comment by ArtfulCoder** [comment]
@vishh has there been a recent change in heapster whereby HPA cant get cpu consumption ?

**Comment by ArtfulCoder** [comment]
@deads2k I think you made changes in this area recently. It seems that HPA's ScaleRef.Kind might not be set correctly. you can bring up a cluster with the latest changes and try to create a rc and hpa and see if it scales. it won't

HPA.yaml
````
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rc
spec:
  cpuUtilization:
    targetPercentage: 20
  maxReplicas: 5
  minReplicas: 1
  scaleRef:
    kind: replicationController
    name: rc
    subresource: scale
```
RC.yaml
```
apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    name: rc
  name: rc
spec:
  replicas: 1
  selector:
    name: rc
  template:
    metadata:
      labels:
        name: rc
    spec:
      containers:
      - image: gcr.io/google_containers/resource_consumer:beta2
        imagePullPolicy: IfNotPresent
        name: rc
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: "104857600"
          requests:
            cpu: 500m
            memory: "104857600"
        terminationMessagePath: /dev/termination-log
      dnsPolicy: Default
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30


```
