### ISSUE TITLE
field keyring   must be set  when I create PV in kubernetes v.1.1??

### ISSUE THREAD

**Issue by jaywayjayway** [kubernetes/kubernetes#18885]
v.1.1,when I create PV(Ceph  backend) , it told me that   field keyring is required.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume1
  namespace: 4bdd206a12004dcfa95085f60387daa8
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  rbd:
    monitors:
    - 10.10.0.1:6789
    pool: rbd
    image: volume-1
    user: admin
    secretRef:
      name: ceph-test-keyring   
    fsType: ext4
```
before v1.1,it worked well with  ` secretRef`. 

## Now , field `keyring ` must be set ???
