### ISSUE TITLE
kubernetes 1.1  create pod with mounting rbd image  error 

### ISSUE THREAD

**Issue by jaywayjayway** [kubernetes/kubernetes#18949]
as titile showed,my ceph cluster  worked healthly ,

```
    cluster 655807bb-c157-46e6-8f10-2454da8d710f
     health HEALTH_WARN mon.10-51-161-109 low disk space
     monmap e1: 3 mons at {10-51-161-109=10.51.161.109:6789/0,10-51-161-110=10.51.161.110:6789/0,10-51-161-111=10.51.161.111:6789/0}, election epoch 56, quorum 0,1,2 10-51-161-109,10-51-161-110,10-51-161-111
     osdmap e57: 3 osds: 3 up, 3 in
      pgmap v2539: 200 pgs, 4 pools, 344 MB data, 128 objects
            1101 MB used, 103 GB / 104 GB avail
                 200 active+clean
```

as belove , it's my pod  with needed image named foo ,

```
rbd image 'foo':
    size 10000 MB in 2500 objects
    order 22 (4096 kB objects)
    block_name_prefix: rbd_data.18932ae8944a
    format: 2
    features: layering

```

```
apiVersion: "v1"
kind: "Pod"
metadata: 
  name: "rbd2"
spec: 
  containers: 
    - 
      name: "rbd-rw"
      image: "nginx"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts: 
        - 
          mountPath: "/mnt/rbd"
          name: "rbdpd"
  volumes: 
    - 
      name: "rbdpd"
      rbd: 
        monitors: 
          - "10.51.161.109:6789"
          - "10.51.161.110:6789"
          - "10.51.161.111:6789"
        pool: "rbd"
        image: "foo"
        user: "admin"
        secretRef: 
          name: "ceph-client-admin-keyring"
        fsType: "ext4"
        keyring: "/etc/ceph/ceph.client.admin.keyring"
        readOnly: false  
```

when I create pod with `kubelet create -f pod.yaml`, it show me:

```
Events:
  FirstSeen LastSeen    Count   From            SubobjectPath   Reason      Message
  ─────────   ────────    ───── ────            ───────────── ──────      ───────
  1h        1m      486 {kubelet 10.51.161.111}         FailedMount Unable to mount volumes for pod "rbd2_default": rbd: image foo is locked by other nodes
  1h        1m      486 {kubelet 10.51.161.111}         FailedSync  Error syncing pod, skipping: rbd: image foo is locked by other nodes
  1h        3s      11  {kubelet 10.51.161.111}         FailedMount Unable to mount volumes for pod "rbd2_default": exit status 1
  1h        3s      11  {kubelet 10.51.161.111}         FailedSync  Error syncing pod, skipping: exit status 1
```

then ,I go to the node with pod, search the log 

```
Dec 21 13:22:04 docker kubelet: E1221 13:22:04.105584   13909 pod_workers.go:112] Error syncing pod 200bcc0d-a797-11e5-98a5-fa163e29fbd9, skipping: exit status 1
Dec 21 13:22:13 docker kernel: libceph: client8060 fsid 655807bb-c157-46e6-8f10-2454da8d710f
Dec 21 13:22:13 docker kernel: libceph: auth method 'x' error -1
Dec 21 13:22:13 docker kernel: libceph: client9042 fsid 655807bb-c157-46e6-8f10-2454da8d710f
Dec 21 13:22:13 docker kernel: libceph: auth method 'x' error -1
Dec 21 13:22:13 docker kernel: libceph: client8032 fsid 655807bb-c157-46e6-8f10-2454da8d710f
Dec 21 13:22:13 docker kernel: libceph: auth method 'x' error -1
Dec 21 13:22:13 docker kubelet: E1221 13:22:13.992751   13909 disk_manager.go:55] failed to attach disk
Dec 21 13:22:13 docker kubelet: E1221 13:22:13.992792   13909 rbd.go:203] rbd: failed to setup
Dec 21 13:22:13 docker kubelet: E1221 13:22:13.992862   13909 kubelet.go:1360] Unable to mount volumes for pod "rbd2_default": exit status 1; skipping pod
Dec 21 13:22:14 docker kubelet: E1221 13:22:14.011721   13909 pod_workers.go:112] Error syncing pod 200bcc0d-a797-11e5-98a5-fa163e29fbd9, skipping: exit status 1
```
## But wen I change  `readOnly: false` to `readyOnly: true`,And `map` foo image to host. it can be successful .But only read .

```
[root@10-51-161-111 ~]# docker exec -ti 78ab17af10a4 /bin/bash 

====================

root@rbd2:/# df -Th 
Filesystem                                                                                          Type   Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:1-101252703-78ab17af10a4b380752a2fdaed78fa914d9863296ca2a8d068fdd3b4951818c8 ext4   9.8G  182M  9.1G   2% /
tmpfs                                                                                               tmpfs  1.9G     0  1.9G   0% /dev
shm                                                                                                 tmpfs   64M     0   64M   0% /dev/shm
tmpfs                                                                                               tmpfs  1.9G     0  1.9G   0% /sys/fs/cgroup
tmpfs                                                                                               tmpfs  1.9G     0  1.9G   0% /run/secrets
/dev/rbd0                                                                                           ext4   9.5G   37M  9.0G   1% /mnt/rbd
/dev/mapper/centos-root                                                                             xfs     31G   14G   18G  43% /etc/hosts
tmpfs                                                                                               tmpfs  1.9G  8.0K  1.9G   1% /run/secret


=================

root@rbd2:/# touch  /mnt/rbd/test.txt 
touch: cannot touch '/mnt/rbd/test.txt': Read-only file system
root@rbd2:/# 

```
