### ISSUE TITLE
HTTPS Ingress controller for SNI based routing

### ISSUE THREAD

**Issue by paultag** [kubernetes/kubernetes#19333]
Happy to send a patch for this -- I've already written an SNI Client Hello packet parser -- 

https://github.com/paultag/sniff/blob/master/parser/parser.go

That code needs to be audited a bit, and fuzzed, but it's hello-world-ing. Anyone willing to break this?

However, this will fail if the request has no SNI extension, so default routes are unclear to me.

The HTTPS Ingress point could do TLS termination, but that'll be mildly annoying for containers that terminate TLS (perhaps Golang apps that to TLS Peer Authentication?), otherwise we could use virtual hosting on HTTP Host.

**Comment by bprashanth** [comment]
The resource itself should support basic HTTPS but that doesn't have anything to do with how one might implement https for one of the backends. Are you volunteering to patch a specific ingress controller so it supports SNI and/or https, or something else? We recently got an nginx controller that supports ssl (https://github.com/kubernetes/contrib/tree/master/Ingress/controllers/nginx-third-party), can you suggest improvements?

**Comment by paultag** [comment]
nginx does TLS termination, so you couldn't, say, do TSL client certs. SNI
would let you route that before TLS handshake.

That also requires nginx to have all the TLS certs, which is unfortunate.

Unless I misunderstood what you're saying?

**Comment by bprashanth** [comment]
Yes, I think we're talking past each other a little :)

So it sounds like you're interested in writing an Ingress controller like the ones in [contrib/Ingress](https://github.com/kubernetes/contrib/tree/master/Ingress) that handles (just?)SNI via your go libarary. For example when a user creates an Ingress like:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: svc1
          servicePort: 80
  - host: bar.baz.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: svc2
          servicePort: 80
```

Your Ingress controller will start listening on 443 for those 2 hostnames and perform ssl routing to the appropriate service backend (kind of like haproxy does). In the example svc1 and svc2 will terminate ssl. Correct?

**Comment by paultag** [comment]
@bprashanth Yeah, exactly, sorry, still pretty new to k8s, trying to get up to speed here, but that's exactly right, I'd love to be able to do that based on SNI to allow `svc` to do TLS termination :)

Thoughts, feels? Worthwhile?

**Comment by bprashanth** [comment]
Yes that sounds useful. We should be clear on how we handle the non-SNI subset of Ingress so users aren't confused. You can either:
* Ignore user created Ingresses that request specific url regexes, because your controller doesn't have that level of visibility. 
* Offload anything but a pure hostname Ingress to something like nginx (eg: so you'd run 2 containers in a pod, the nginx controller will serve on 80 and yours on 443)
* Actually teach your controller to proxy url regexes etc in go

Feel free to open a WIP pr in contrib/Ingress and tag me for help as needed. A basic controller example: https://github.com/kubernetes/contrib/blob/master/Ingress/controllers/README.md (you can also use this as the nginx sidecar listening on :80 if you choose option 2 above)

**Comment by bprashanth** [comment]
Just checking in, @paultag need help?

**Comment by jesstm** [comment]
Wanted to chime in to say this is extremely interesting to me. What would be even more incredible is if there was a dead-simple way to configure routing based on a regex of the SNI info.

What we want is to be able to say is: if the server name in SNI is: `$CUSTOMER_ID.domain.com` then automatically route the request to `customer-$CUSTOMER_ID.default.cluster.local:443`

Ideally the user would be able to specify the SNI regex in the ingress YAML definition.

@bprashanth @paultag curious to hear what you think about this idea.

**Comment by paultag** [comment]
So I've been the worst about working on this -- the URL route bits caused
me to realize this wasn't just drop-in sni hackery.

Regex sounds interesting - is there such an ingress controller for http
now? We could mirror names!

**Comment by bprashanth** [comment]
Now that 1.2 is almost out the door we should focus on nailing this. There are several ingress controllers that you can draw inspiration from: 
https://github.com/kubernetes/contrib/tree/master/ingress
https://github.com/kubernetes/contrib/tree/master/service-loadbalancer

And a few out there in the wild.

The easiest way to express SNI would be as mentioned above (https://github.com/kubernetes/kubernetes/issues/19333#issuecomment-170278350), with an addional annotation to indicate SNI, eg:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.beta.kubernetes.io/sni: "true"
  name: test
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: svc1
          servicePort: 80
  - host: bar.baz.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: svc2
          servicePort: 80
```

When discussion on TCP + Ingress converge, this might become: 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    tcp:
      backend:
        serviceName: svc1
        servicePort: 80
  - host: bar.baz.com
    tcp:
      backend:
        serviceName: svc2
        servicePort: 80
```

But I don't think the latter needs to gate implementation.
@emmanuel @aledbf fyi

**Comment by aledbf** [comment]
> The easiest way to express SNI...

Two or more certificates implies that only SNI capable clients can access the server (at least in haproxy and nginx)

> When discussion on TCP + Ingress converge, this might become:

Which port is going to be used to expose each tcp service?

**Comment by bprashanth** [comment]
If you want to actually terminate the tls connection at the lb using SNI, your Ingress will need a list of matching certs too. But haproxy supports SSL routing which you can express without a TLS section (right?). 

> Which port is going to be used to expose each tcp service?

I think that's a non-SNI tcp question. We should discuss that on the tcp bug (which I'm yet to file).  For SNI it's safe to assume :443 right?

**Comment by aledbf** [comment]
@paultag > but that's exactly right, I'd love to be able to do that based on SNI to allow svc to do TLS termination :)

I asked exactly the same thing here https://github.com/openresty/lua-nginx-module/issues/612

I tried that but basically you need to write a proxy that routes the traffic inspecting the server name. Doing that you end with a man-in-the-middle "attack" (from the perspective of the security)

**Comment by aledbf** [comment]
> For SNI it's safe to assume :443 right?

ok, so all the Ingress TCP services share the same port? (that might sound weird, one port for many services)

**Comment by bprashanth** [comment]
> I tried that but basically you need to write a proxy that routes the traffic inspecting the server name. Doing that you end with a man-in-the-middle "attack" (from the perspective of the security)

I think such a proxy would be really useful (whether written as a simple go proxy or using haproxy). I also think for an MITM attack we'd need to decrypt and re-encrypt, the SNI router should just act as a tcp proxy muxed on SNI hostname.

> ok, so all the Ingress TCP services share the same port? (that might sound weird, one port for many services)

Currently, :443 is assumed unless you put more information into the annotations. This makes the non-SNI tcp use case a little hard.

We discussed exposing ports as a first class field (https://github.com/kubernetes/kubernetes/issues/19497#issuecomment-174112834) but decided against it right now to reduce the parametrization complexity. We can still promote it out of annotation once we've fleshed out tcp ingress.

**Comment by Lukasa** [comment]
> Doing that you end with a man-in-the-middle "attack" (from the perspective of the security)

No you don't.

The SNI extension is provided in the ClientHello TLS record, which is not encrypted in any way. The client sends this before it sends any data, and so the SNI proxy does not need to have any knowledge of the server's private keys or any ability to insert itself into the encryption handshake.

(I should note that session resumption might make this tricky, but you can get around that by simply not supporting it.)

**Comment by bprashanth** [comment]
> I think that's a non-SNI tcp question. We should discuss that on the tcp bug (which I'm yet to file).

Filed: https://github.com/kubernetes/kubernetes/issues/23291

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc

**Comment by cmluciano** [comment]
@paultag Is this something that you are still interested in working on?

**Comment by aledbf** [comment]
@cmluciano we are using `paultag/sniff` as entry point for the tls connection in [nginx ingress controller](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/pkg/cmd/controller/tcp.go)

**Comment by paultag** [comment]
I'm interested, but my bandwidth is likely not enough to not become a blocker, so I'm 100% fine giving up the mutex, helping merge / fix / change any code I've written or provide emotional support to those who need it

:confetti_ball:

**Comment by cmluciano** [comment]
@aledbf Do you think this issue can be closed or migrated?

**Comment by aledbf** [comment]
@cmluciano I think this can be closed. We use the library to enable ssl passthrough.
That being said this is only present in the nginx ingress controller.

**Comment by paultag** [comment]
The intent here would be for a ingress controller to not have to run nginx at all - for instance, if I have a webserver that gets a letsencrypt cert every boot, or if I want to do tls mutual authentication in a server process

**Comment by cmluciano** [comment]
@paultag Are you ok with my closing this since there isn't a clear owner? It seems that there is definitely some interest in the use-case, but I'm not sure if anyone is volunteering to implement it :(

**Comment by paultag** [comment]
I think closing this was a mistake - it's a needed feature, and the incomplete implementation will likely result in other people opening similar issues.

**Comment by cmluciano** [comment]
@freehan @nicksardo @aledbf Is this a feature that we should target for 1.8?

**Comment by aledbf** [comment]
@cmluciano which feature?

**Comment by cmluciano** [comment]
Adding https://github.com/kubernetes/kubernetes/issues/19333#issuecomment-199396785 as an ingress controller. 

This is a useful feature, but I'b not sure if we have any owners.

**Comment by paultag** [comment]
Why do we need an owner for each bug? Keeping this open will reduce duplicates, and make sure everyone knows the state of the defect

**Comment by MichaelSp** [comment]
We where able to implement this using standard [nginx-ingress](https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress)
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
spec:
  rules:
    - host: app.on.my.host.com
      http:
        paths:
          - backend:
              serviceName: app-service
              servicePort: 8443
```
