### ISSUE TITLE
It should be possible to consume specific annotations/labels in env vars

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#19367]
During the initial downward API implementation for environment vars, we decided to punt on exposing specific annotations/labels in environment variables because it would require container restart if those values changed, and we wanted to be able to change annotations/labels without restarting containers.  During an F2F meeting today, we decided to just implement this with the caveat that env vars are not updated, period.
This issue is to do that implementation.

Proposed syntax:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SOME_ANNOTATION
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations[k8s.io/some-annotation]
        - name: SOME_LABEL
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels[some-label]
  restartPolicy: Never
```

@erictune @thockin @bgrant0607 @smarterclayton

**Comment by thockin** [comment]
SGTM

**Comment by bgrant0607** [comment]
@pmorie Is that what we decided? 

My view is that since the downward API would be explicit, we could restart only those containers that injected annotations that were modified, and users should know what they signed up for. If they don't want restarts, don't use env vars or don't modify the annotations.

We can't do this with service links because we don't know what containers use what service links.

**Comment by thockin** [comment]
I understood the agreement to be that we would start with no-restart and
consider moving to optional restart-on-change.  In a parallel conversation,
ISTR @smarterclayton agreeing that we could allow an opt-in for Secret
volumes to self-update, and maybe an opt-out for down-api volumes.

It won't be 100% consistent (secret is no-update by default, the rest
probably are auto-updated), but it will be possible to control.

**Comment by erictune** [comment]
If we are going to do no-restart at first, then I think we need to reject
annotation and label updates on pods that use downward API.

Otherwise, if we allow metadata updates, and don't restart, then we we
switch to restarting, that is a breaking change.

**Comment by thockin** [comment]
maybe it's time to add an argument like `allowRestart` for updates so a
user can say whether they want to allow a restart or fail the txn.

**Comment by erictune** [comment]
I think `allowRestart` is going to be very complex to implement well.  Some reasons:

- ability to change a value without a restart will change over time, and with kubelet versions.  
- If the master has to track the capabilities of its kubelets, that will be complex to get right.
- if the kubelet has to ask the kubelet whether it can do an update, that adds complexity too.
- If the kubelet-to-master protocol is changed to make updates conditional, or to allow the master to ask the kubelet if it can accept a change without restart, then the master-kubelet protocol changes from declarative to imperative.  I suspect that will have complex side effects.

**Comment by erictune** [comment]
To clarify, I think a general "allowRestart" bit on requests, or on the whole Pod, would be quite hard to get right over the space of all things users will want to update.

However, I think it might make sense to put an "allowRestart" bit on DownwardAPI volumes, and maybe even on EnvVars.  That would make it super explicit about under what conditions you are allowing the pod to be updated, and would be backward compatible.


For example on this pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: ANNOT_A
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations[annotation-a]
        - name: ANNOT_B
          allowRestartOnChange: true
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations[k8s.io/annotation-b]
```
the apiserver validation would reject a change to update `.metadata.annotations[a]` but would allow a change that updated `.metadata.annotations[b]`.

**Comment by erictune** [comment]
It could get verbose though for people with a lot of env vars who want all of them updatable.

**Comment by thockin** [comment]
rather that blocking updates, I would naively expect the semantic to be:

If the valueFrom block sets `restartOnChange` then the pod would restart
when the referenced field is changed.  Otherwise the field would change but
the pod would not update (as today).

Volumes are more complex because you really have (live-update | restart |
ignore) policies.  Maybe we can make this policy (and env) be pod-global?

**Comment by ncdc** [comment]
+1 to not blocking. I agree w/Tim's suggestion - if we want to allow automatic restarts on change, the user can opt in to that behavior explicitly.

**Comment by pmorie** [comment]
Spent a fair amount of time thinking about the question of whether to restart pods due to env changes recently, and I feel like that is going to be a losing game.  I think users of environment variables are usually well-aware of the non-existent update semantics, and I suspect that if we try to make pods restart because something that goes into an env var changed, that we'll be playing a losing game.  So, what about these semantics:

1.  We will never restart pods due to a piece of data consumed via some API mechanism changes, ever.
2.  We will make the documentation for such APIs reflect that pods will never ever be restarted due to changes in those values
3.  We will advise folks who want updates to these values as they happen to use the volume plugins and inotify.

**Comment by ncdc** [comment]
:+1: After thinking about this more, I assume that most application developers are aware that executables must be restarted when env vars change (and they need to perform the restart themselves), and they can either decide to reread config files periodically or via inotify if they want to react to changes in files.

**Comment by thockin** [comment]
SGTM.  Still need to decide if we allow opt-{in,out} for live updates of
volume-projected secrets,configs,dapi

**Comment by bgrant0607** [comment]
People who don't want changes propagated to pods shouldn't update their ConfigMaps or Secrets. No knobs.

**Comment by dhawal55** [comment]
Any update on this?

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by ryanmcnamara** [comment]
Any update?

**Comment by techdragon** [comment]
I just found this while looking for this feature. It seems strange that I can pluck a value from the hierarchy like `spec.nodeName` but not `spec.template.metadata.labels.environment`. I definitely concur that either a mechanism to specify or a decision on restart behaviour is necessary. But it seems weird this very useful feature request has sat without update for nearly 2 years. Using labels and annotations as environment variables is a mechanism to enable DRY and avoid making mistakes when building larger deployment units.

I have an example deployment where the general structure of the service's YAML Kubernetes configuration file is roughly:
- configMap
- environment one deployment
  - environment one pod
    - pod container one
    - pod container two 
    - initContainer one
- environment two deployment
  - environment two pod
    - pod container one
    - pod container two 
    - initContainer one
- environment three deployment
  - environment three pod
    - pod container one
    - pod container two 
    - initContainer one

The config map is shared across all three environments and used in both pod container two and the initcontainer one. Meanwhile I have to manually inject an environment variable containing the environment name into every container either with explicit `env` entries, or other means. But when adding and removing environments this is prone to mistakes, so being able to 'lock it in' as something like 
```yaml
env:
  - name: ENVIRONMENT
    valueFrom:
      fieldRef:
        fieldPath: spec.template.metadata.labels.environment
```
Would remove multiple hand edited locations from most of our service's Kubernetes YAML configuration/deployment files.
