### ISSUE TITLE
Add basic TLS support to Ingress

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#19497]
Proposal:
```go
$ git diff | tr '+' ' '

diff --git a/pkg/api/types.go b/pkg/api/types.go
index 744a498..de9ed32 100644
--- a/pkg/api/types.go
    b/pkg/api/types.go
@@ -2090,6  2090,14 @@ 
const (
 
 	// DockerConfigJsonKey is the key of the required data for SecretTypeDockerConfigJson secrets
 	DockerConfigJsonKey = ".dockerconfigjson"
 
 	// SecretTypeTLS contains information about SSL termination used with the Ingress resource.
 	//
 	// Required fields:
 	// - Secret.Data["key"] - TLS private key in pem format.
 	//   Secret.Data["cert"] - TLS certificate in pem format.
 	// TODO: Consider supporting different formats, destination CA bundle etc.
 	SecretTypeTLS SecretType = "TLS"
 )
 
diff --git a/pkg/apis/extensions/types.go b/pkg/apis/extensions/types.go
index f478059..a1e8cc6 100644
--- a/pkg/apis/extensions/types.go
    b/pkg/apis/extensions/types.go
@@ -523,6  523,13 @@ 
type IngressSpec struct {
 	// is optional to allow the loadbalancer controller or defaulting logic to
 	// specify a global default.
 	Backend *IngressBackend `json:"backend,omitempty"`
 
 	// TLS configuration.
 	TLS []IngressTLS `json:"tls,omitempty"`
 
 	// A list of host rules used to configure the Ingress. If unspecified, or
 	// no rule matches, all traffic is sent to the default backend.
 	Rules []IngressRule `json:"rules,omitempty"`

@@ -535,6  542,21 @@ 
 // IngressTLS describes the transport layer security associated with an Ingress.
 type IngressTLS struct {
 	// If specified, this host is used to multiplex listeners on the same port
 	// via a hostname specified through the SNI TLS extension. The value of this
 	// field must match the name/s used in the tlsSecret.
 	Host string `json:"host,omitempty"`
 	// SSL traffic received on this Port must be terminated with the given TLSSecret.
 	// In the future we might support different forms of SSL termination.
 	Port int32 `json:"port,omitempty"`
 	// The secret used to terminate SSL traffic on the given port. This field is left
 	// optional to allow SSL routing based on SNI hostname alone. If the SNI host
	// in the this section conflicts with the "Host" header field used by an IngressRule,
	// the SNI host is used for termination and value of the Host header is used
	// for routing.
 	TLSSecretRef *api.LocalObjectReference `json:"tlsSecret,omitempty"`
 	// TODO: Consider specifying different modes of termination, ssl protocols etc.
 }
```

This gives us:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echomap
spec:
  tls:
  - host: foo.bar.com
    port: 443
    tlsSecret:
      name: fooSecret
  - host: bar.baz.com
    port: 443
    tlsSecret:
      name: barSecret
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: echoheadersx
          servicePort: 80
  - host: bar.baz.com
    http:
      paths:
      - path: /bar
        backend:
          serviceName: echoheadersy
          servicePort: 80
      - path: /foo
        backend:
          serviceName: echoheadersx
          servicePort: 80
```

@kubernetes/goog-cluster @thockin @smarterclayton

**Comment by smarterclayton** [comment]
@pweil- @ramr we should discuss termination policy and insecure termination policy. This structure assumes termination, which I don't think we want to require.

**Comment by bprashanth** [comment]
Termination is the most common, though I don't think this locks us out of re-encrypt and passthrough. Re-encrypt would probably require a destination CA bundle (in the secret). For passthrough, would you expect it to drop down to L4 (+SNI, optionally)? Currently the Ingress only attempts L7.

What do you mean by insecure termination policy (ssl negotiation stuff like protocols, ciphers etc or something to do with self signed certs)?

**Comment by pweil-** [comment]
> Re-encrypt would probably require a destination CA bundle (in the secret)

correct, a destination cert should be required in this case.

> For passthrough, would you expect it to drop down to L4 (+SNI, optionally)

Yes.  For HAProxy in particular all of the incoming connections can be done on a tcp front end and configuration can be checked to see if a) SNI is present and b) if present, is there a passthrough route configured.  This is done before any type of termination flow in the OpenShift router.

> insecure termination policy

We use this to help setup secure and insecure modes at the same time.  It allows the user to say "here is a TLS route and also accept/redirect/deny the insecure version of it as well".

**Comment by bprashanth** [comment]
>Yes. For HAProxy in particular all of the incoming connections can be done on a tcp front end and configuration can be checked to see if a) SNI is present and b) if present, is there a passthrough route configured. This is done before any type of termination flow in the OpenShift router.

Ah, so this comes back to the old: Ingress is currently L7, when are we going to teach it about L4? discussion. Here's what an L4 Ingress might look like:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echomap
spec:
  tls:
  - host: foo.bar.com
    port: 443
  Backend:
    ServiceName: echoheadersx
    ServicePort: 80
```

To get SNI based SSL routing you'd have to create multiple like this. Does that work? 

I'm also not against a simple `TLSMode: passthrough, terminate` field that defaults to the latter, but the passthrough option will not make sense if we decide to keep the Igress pure L7 (and for loadbalancers like nginx that don't understand SNI at L4).

>We use this to help setup secure and insecure modes at the same time. It allows the user to say "here is a TLS route and also accept/redirect/deny the insecure version of it as well".

By insecure mode I'm assuming you mean HTTP on :80. This sounds useful since we don't have a way to express re-directs yet, but HTTP->HTTPS is the most common. 

@aledbf fyi

**Comment by bprashanth** [comment]
I think we should table the L4 discussion for now, I want to tackle that next, after basic TLS. @kubernetes/rh-networking can you sketch out a list of features you need from Ingress before adoption? 


@pweil- thoughts on generic redirects as a replacement for `insecure: accept, deny, redirect`? eg:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echomap
spec:
  listeners:
  - port: 443
    hosts: 
      - www.foobar.com
      - foobar.com
    tlsSecret:
      name: fooSecret
  - port: 80
  redirects:
  - url: http://foobar.com
    redirect: https://www.foobar.com
  rules:
  - host: www.foobar.com
    http:
      paths: 
      - path: /foo
        backend:
          serviceName: echoheadersx
          servicePort: 80
```
I guess my question is are redirects a frequent enough feature that we should add it to the 60% Ingress or do we banish it to annotations and just handle the most common type of redirect via an `insecure` field (though redirecting foobar.com to www.foobar.com for seo is pretty common too).

**Comment by pweil-** [comment]
> I guess my question is are redirects a frequent enough feature that we should add it to the 60% Ingress or do we banish it to annotations and just handle the most common type of redirect via an insecure field (though redirecting foobar.com to www.foobar.com for seo is pretty common too)

Starting the insecure options as an annotation is a safe bet.  We can always upgrade it to a field later.

**Comment by ramr** [comment]
@bprashanth I think having an explicit `redirect` is good (though it might be worth seeing if we can fold it into `rules` - really just a rule for all practical purposes). The `deny` can be implicit - meaning if you didn't specify it, its denied. The `allow` bit would be just a listener on port `80` that you had in the above example. 
One other use case, I can see is to have an ingress point/path that routes part of the URI namespace on the `insecure` connection to something akin to a CDN service - so there'd be different backends for the assets (js, images, css etc) and the actual content. But that can be achieved by adding two different ingress points.

**Comment by bprashanth** [comment]
Alright so it sounds like people are mostly on board with the original proposal, replacing the `tls` section with a `listeners` section which defaults to 80 if unspecified. Essentially this will give us TLS termination with multiple certs/ports per Ingress, while leaving room for growth around:
* Explicit listener.termination modes (re-encrypt, passthrough, terminate)
* Generic redirects (superset of insecure)
* L4+SNI

If there are additional use cases please bring them up so we can work out a plausible proof of concept in yaml with the current proposal.

**Comment by thockin** [comment]
Can you post updated YAML and Go illustrating?  I don't want to add
comments to a stale design :)

**Comment by bprashanth** [comment]
So listeners are just a way to specify that something is listening for a connection on a port. A listener can have TLS configuration associated with it, but it doesn't contain any routing information (eg redirects, urlmaps, services etc). 

```go
diff --git a/pkg/api/types.go b/pkg/api/types.go
index 588b8ed..7c6b905 100644
--- a/pkg/api/types.go
    b/pkg/api/types.go
@@ -2111,6  2111,14 @@ const (
 
 	// DockerConfigJsonKey is the key of the required data for SecretTypeDockerConfigJson secrets
 	DockerConfigJsonKey = ".dockerconfigjson"
 
 	// SecretTypeTLS contains information about SSL termination used with the Ingress resource.
 	//
 	// Required fields:
 	// - Secret.Data["key"] - TLS private key.
 	//   Secret.Data["cert"] - TLS certificate.
 	// TODO: Consider supporting different formats, specifying CA/destinationCA.
 	SecretTypeTLS SecretType = "TLSTermination"
 )
 
 // SecretList is a list of Secret.
diff --git a/pkg/apis/extensions/types.go b/pkg/apis/extensions/types.go
index 54bd36f..6b83f5c 100644
--- a/pkg/apis/extensions/types.go
    b/pkg/apis/extensions/types.go
@@ -525,12  525,39 @@ type IngressSpec struct {
 	// is optional to allow the loadbalancer controller or defaulting logic to
 	// specify a global default.
 	Backend *IngressBackend `json:"backend,omitempty"`
 
 	// Listeners accept connections on a port and apply the specified security
 	// configuration.
 	Listeners []IngressListener `json:"listeners,omitempty"`
 
 	// A list of host rules used to configure the Ingress. If unspecified, or
 	// no rule matches, all traffic is sent to the default backend.
 	Rules []IngressRule `json:"rules,omitempty"`
 	// TODO: Add the ability to specify load-balancer IP through claims
 }
 
 // IngressListener describes the properties of a loadbalancer frontend, or
 // listener, such as TLS configuration and which ports to accept incoming
 // connections.
 type IngressListener struct {
 	// If specified, this host is used to multiplex listeners on the same port
 	// via a hostname specified through the SNI TLS extension. The value of this
 	// field must match the name/s used in the tlsSecret.
 	Hosts []string `json:"hosts,omitempty"`
 	// Ports on which to accept incoming connections. SSL traffic received on
 	// this Port must be terminated with the given TLSSecret. If no secret is
 	// specified all traffic on the given ports are treated insecurely, as HTTP.
 	// In the future, TLSRule might support different forms of SSL termination.
 	Ports []int32 `json:"ports,omitempty"`
 	// The secret used to terminate SSL traffic on the given port. Field is left
 	// optional to allow SSL routing based on SNI hostname alone. If the SNI host
 	// in a listener conflicts with the "Host" header field used by an IngressRule,
 	// the SNI host is used for termination and value of the Host header is used
 	// for routing.
 	TLSSecretRef *api.LocalObjectReference `json:"tlsSecret,omitempty"`
 	// TODO: Consider specifying different modes of termination, protocols etc.
 }
```

I'm really just targetting 3 broad cases:
* insecure 80
* secure 443, redirect 80
* secure 443, reject 80

Where 443 and 80 could be a list of any ports with the same/different certs and sni hostnames.


```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: redirect-80-443
spec:
  listeners:
  - port:
    # Implementation defines which port returns a 301
    - 80
    - 443
    host:
    - foo.bar.com
    - '*.google.com'
    tlsSecret:
      name: fooSecret
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: foosvc
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reject-80-encrypt-443
spec:
  listeners:
  - port:
    - 443
    host:
    - foo.bar.com
    - '*.google.com'
    tlsSecret:
      name: fooSecret
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: foosvc
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: insecure-80
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: foosvc
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sni-http
spec:
  listeners:
  - port:
    - 443
    host:
    - foo.bar.com
    tlsSecret:
      name: fooSecret
  - port:
    - 443
    host:
    - '*.google.com'
    tlsSecret:
      name: googleSecret
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: foosvc
          servicePort: 80
  - host: api.google.com
    http:
      paths:
      - path: /app1
        backend:
          serviceName: app1svc
          servicePort: 80
```

Note the following: 
* you *do not * know which port a connection was received on. This means if someone wants to use Ingress for port redirection (listener 80->svc:80, listner 8080 -> svc:8080), they'd have to create multiple resources each with a single backend. 
* tls termination is assumed, but I plan to add a `type=re-encrypt,terminate,passthrough` field and a new type of secret for re-encrypt.

**Comment by thockin** [comment]
Mostly SGTM, a few Qs

On Sat, Jan 16, 2016 at 4:25 PM, Prashanth B <notifications@github.com> wrote:
>
> So listeners are just a way to specify that something is listening for a connection on a port. A listener can have TLS configuration associated with it, but it doesn't contain any routing information (eg redirects, urlmaps, services etc).
>
> diff --git a/pkg/api/types.go b/pkg/api/types.go
> index 588b8ed..7c6b905 100644
> --- a/pkg/api/types.go
>     b/pkg/api/types.go
> @@ -2111,6  2111,14 @@ const (
>
>     // DockerConfigJsonKey is the key of the required data for SecretTypeDockerConfigJson secrets
>     DockerConfigJsonKey = ".dockerconfigjson"
>
>     // SecretTypeTLS contains information about SSL termination used with the Ingress resource.
>     //
>     // Required fields:
>     // - Secret.Data["key"] - TLS private key.
>     //   Secret.Data["cert"] - TLS certificate.
>     // TODO: Consider supporting different formats, specifying CA/destinationCA.
>     SecretTypeTLS SecretType = "TLSTermination"
>  )
>
>  // SecretList is a list of Secret.
> diff --git a/pkg/apis/extensions/types.go b/pkg/apis/extensions/types.go
> index 54bd36f..6b83f5c 100644
> --- a/pkg/apis/extensions/types.go
>     b/pkg/apis/extensions/types.go
> @@ -525,12  525,39 @@ type IngressSpec struct {
>     // is optional to allow the loadbalancer controller or defaulting logic to
>     // specify a global default.
>     Backend *IngressBackend `json:"backend,omitempty"`
>
>     // Listeners accept connections on a port and apply the specified security
>     // configuration.
>     Listeners []IngressListener `json:"listeners,omitempty"`
>
>     // A list of host rules used to configure the Ingress. If unspecified, or
>     // no rule matches, all traffic is sent to the default backend.
>     Rules []IngressRule `json:"rules,omitempty"`
>     // TODO: Add the ability to specify load-balancer IP through claims
>  }
>
>  // IngressListener describes the properties of a loadbalancer frontend, or
>  // listener, such as TLS configuration and which ports to accept incoming
>  // connections.
>  type IngressListener struct {
>     // If specified, this host is used to multiplex listeners on the same port
>     // via a hostname specified through the SNI TLS extension. The value of this
>     // field must match the name/s used in the tlsSecret.
>     Hosts []string `json:"hosts,omitempty"`
>     // Ports on which to accept incoming connections. SSL traffic received on
>     // this Port must be terminated with the given TLSSecret. If no secret is
>     // specified all traffic on the given ports are treated insecurely, as HTTP.
>     // In the future, TLSRule might support different forms of SSL termination.
>     Ports []int32 `json:"ports,omitempty"`
>     // The secret used to terminate SSL traffic on the given port. Field is left
>     // optional to allow SSL routing based on SNI hostname alone. If the SNI host
>     // in a listener conflicts with the "Host" header field used by an IngressRule,
>     // the SNI host is used for termination and value of the Host header is used
>     // for routing.
>     TLSSecretRef *api.LocalObjectReference `json:"tlsSecret,omitempty"`

Why a Ref and not a Name ?

>     // TODO: Consider specifying different modes of termination, protocols etc.
>  }
>
> I'm really just targetting 3 broad cases:
>
> insecure 80
> secure 443, redirect 80
> secure 443, reject 80
>
> Where 443 and 80 could be a list of any ports with the same/different certs and sni hostnames.
>
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: redirect-80-443
> spec:
>   listeners:
>   - port:
>     # Implementation defines which port returns a 301
>     - 80
>     - 443
>     host:
>     - foo.bar.com
>     - '*.google.com'
>     tlsSecret:
>       name: fooSecret

Doesn't this say that port 80 is using TLS?  I would have expected to see:

```
listeners:
- ports:
  - 80 # unencrypted
- ports:
  - 443 # TLS
  hosts:
  - foo.bar.com
  - '*.google.com'
  tlsSecret:
    name: fooSecret
```

>   rules:
>   - host: foo.bar.com
>     http:
>       paths:
>       - path: /foo
>         backend:
>           serviceName: foosvc
>           servicePort: 80
> ---
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: reject-80-encrypt-443
> spec:
>   listeners:
>   - port:
>     - 443
>     host:
>     - foo.bar.com
>     - '*.google.com'
>     tlsSecret:
>       name: fooSecret
>   rules:
>   - host: foo.bar.com
>     http:
>       paths:
>       - path: /foo
>         backend:
>           serviceName: foosvc
>           servicePort: 80
> ---
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   name: insecure-80

So no listeners implies insecure 80?  Where is that documented?

**Comment by bprashanth** [comment]
> Why a Ref and not a Name ?

Name is good enough. I guess we decided the same thing for Backend ->ServiceName too.

 >Doesn't this say that port 80 is using TLS?  I would have expected to see:

```
listeners:
- ports:
  - 80 # unencrypted
- ports:
  - 443 # TLS
  hosts:
  - foo.bar.com
  - '*.google.com'
  tlsSecret:
    name: fooSecret
```

That's right. That will serve insecurely on :80. Specifying a bunch of ports in the same listener, like so:
```
listeners:
- ports:
  - 80 
  - 443
  hosts:
  - foo.bar.com
  - '*.google.com'
  tlsSecret:
    name: fooSecret
```
Leaves it to the backend. It could either redirect all ports to the first one, actually write out a redirect rule of the form "http://foo.com -> https://www.foo.com", or just serve https on all. 

> So no listeners implies insecure 80?  Where is that documented?

As a user I'd expect the Ingress I have today to continue doing what it does, no? Obviously a better choice would be default ssl termination with some cluster cert.

**Comment by smarterclayton** [comment]
Although we use local object reference everywhere else...

**Comment by thockin** [comment]
On Mon, Jan 18, 2016 at 8:43 PM, Prashanth B <notifications@github.com> wrote:
>
> Why a Ref and not a Name ?
>
> Name is good enough. I guess we decided the same thing for Backend ->ServiceName too.
>
> Doesn't this say that port 80 is using TLS? I would have expected to see:
>
> listeners:
> - ports:
>   - 80 # unencrypted
> - ports:
>   - 443 # TLS
>   hosts:
>   - foo.bar.com
>   - '*.google.com'
>   tlsSecret:
>     name: fooSecret
>
> That's right. That will serve insecurely on :80. Specifying a bunch of ports in the same listener, like so:
>
> listeners:
> - ports:
>   - 80
>   - 443
>   hosts:
>   - foo.bar.com
>   - '*.google.com'
>   tlsSecret:
>     name: fooSecret
>
> Leaves it to the backend. It could either redirect all ports to the first one, actually write out a redirect rule of the form "http://foo.com -> https://www.foo.com", or just serve https on all.

I don't mind that, but it's not at all obvious.

> So no listeners implies insecure 80? Where is that documented?
>
> As a user I'd expect the Ingress I have today to continue doing what it does, no? Obviously a better choice would be default ssl termination with some cluster cert.

Why not require 1 listener?  Or At least document that no listeners
gets defaulted to a single non-tls listener on :80

**Comment by thockin** [comment]
We have no consistency on this.  Object reference makes sense if the type
or apiversion matter.  If it is known to be a Service, serviceName is
simpler.

If we had consistency, I would not object, but we don't.  v2 should.

**Comment by smarterclayton** [comment]
A concern I have with the current spec is that defining the listening ports conveys no useful information.  The implementation of the router is what makes the decision on what ports to expose - saying 80 and 443 here mean nothing to the implementation (it doesn't provide useful info to the implementation).  Saying that you desire TLS termination is a very explicit intent.  Saying that you desire to have insecure requests redirected to a specific port is an intent.  As they are now, people will just cargo cult copy them.

**Comment by bprashanth** [comment]
> The implementation of the router is what makes the decision on what ports to expose - saying 80 and 443 here mean nothing to the implementation (it doesn't provide useful info to the implementation). 

Hmm, are you saying the users shouldn't be allowed to ask for a different port? you might be running postgres with tls and require a different port no?

**Comment by bprashanth** [comment]
I think the safest way to proceed would be to ditch ports for now. How about?
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echomap
spec:
  tls:
  # list? 
  - hosts: 
    - foo.bar.com
    - foo.baz.com
    secretName: fooSecret
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: echoheadersx
          servicePort: 80
  - host: foo.baz.com
```
Serving insecurely/bocking/redirecting :80 and frontend port are conveyed via annotation. This gives the loadbalancer controller freedom to apply its default policy in the absense of the annotation and/or a tls section.
