### ISSUE TITLE
kubectl config set-credentials paths do not write correct paths to ~/.kube/config

### ISSUE THREAD

**Issue by bloo** [kubernetes/kubernetes#19561]
I cannot get the write path to write using `kubectl config set-credentials`  v1.1.2 or v1.1.4. I suspect this affects other versions and other arguments.

# 1

`kubectl config set-credentials admin --client-certificate=.kube/ssl/admin.pem --client-key=.kube/ssl/admin.pem`

results in:
```
- name: admin
  user:
    client-certificate: ssl/admin.pem
    client-key: ssl/admin.pem
```

# 2

`kubectl config set-credentials admin --client-certificate=~/.kube/ssl/admin.pem --client-key=~/.kube/ssl/admin.pem`

results in

```
- name: admin
  user:
    client-certificate: /Users/bloo/~/.kube/ssl/admin.pem
    client-key: /Users/bloo/~/.kube/ssl/admin.pem
```

# 3

```
echo $HOME
/Users/bloo
```

and 

`kubectl config set-credentials admin --client-certificate=${HOME}/.kube/ssl/admin.pem --client-key=${HOME}/.kube/ssl/admin.pem`

results in

```
- name: admin
  user:
    client-certificate: ssl/admin.pem
    client-key: ssl/admin.pem
```

# 4

```
echo $HOME
/Users/bloo
```

and 

`kubectl config set-credentials admin --client-certificate=$HOME/.kube/ssl/admin.pem --client-key=$HOME/.kube/ssl/admin.pem`

```
- name: admin
  user:
    client-certificate: ssl/admin.pem
    client-key: ssl/admin.pem
```

# 5

`kubectl config set-credentials admin --client-certificate='.kube/ssl/admin.pem' --client-key='.kube/ssl/admin.pem'`

results in 

```
- name: admin
  user:
    client-certificate: ssl/admin.pem
    client-key: ssl/admin.pem
```
