### ISSUE TITLE
nfs example doesn't work in coreos based cluster

### ISSUE THREAD

**Issue by adieu** [kubernetes/kubernetes#19593]
I was trying to setup the nfs example in my coreos based cluster and I found `nfs-busybox` and `nfs-web` pods would fail to start due to errors mounting volumes from `nfs-server`.

After some debugging, I found the error message `exportfs: /exports does not support NFS export` in `docker logs NFS_SERVER_CONTAINER_ID` and confirmed the nfs server didn't provide `/exports` as a share as it should be.

After reading [this post](https://bbs.archlinux.org/viewtopic.php?id=192585), I understood the problem. Coreos is using overlayfs for its docker containers and folders in overlayfs can't be exported as nfs shares.

So I edited `examples/nfs/nfs-server-rc.yaml` to mount a folder from host to `/exports`:

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs
        ports:
          - name: nfs
            containerPort: 2049
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /exports
          name: storage
      volumes:
      - name: storage
        hostPath:
          path: /srv
```

Then the problem went away and I could successfully finish the example.

I think it's not a bug in k8s nor coreos. The reason I reported the issue to the k8s repo is because there might be some other people failed to setup the nfs example in a coreos cluster following the guide in `examples/nfs/README.md` and it would be nice to have a notice in the document to save them some time.

I would love to contribute a PR adding the notice if someone think it's necessary.

Thanks for building this great software.
