### ISSUE TITLE
Secrets broken on Docker 1.9.1 on non-containerized kubelet

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#19622]
I am running Docker 1.9.1 on Kubernetes 1.1.3 on SL6 with a 3.10.0-229.14.1.el7.x86_64 kernel with a NON-containerized kubelet. Secrets mounting works fine on the same host when I am running on Docker 1.7.1.

```
kind: Secret
apiVersion: v1
metadata:
  name:
    mysecret
data:
  abc: ZGVm # "def"
```
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: nginx
      image: docker-registry-vip.dev.box.net/jenkins/nginx
      volumeMounts:
        - mountPath: "/secret"
          name: "secret"
          readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: mysecret
```
```
$ kubectl create -f secret.yaml
secret "mysecret" created
$ kubectl create -f pod.yaml
pod "mypod" created
```

All those setup steps are same on Docker 1.7.1 and Docker 1.9.1. This is what happens on Docker 1.7.1 (working):

```
$ # docker exec into the pod's container
$ sudo docker exec -t -i 683 /bin/bash
root@mypod:/# ls -al /secret/
total 8
drwxrwxrwt  2 root root   60 Jan 13 23:18 .
drwxr-xr-x 22 root root 4096 Jan 13 23:26 ..
-r--r--r--  1 root root    3 Jan 13 23:18 abc
root@mypod:/# ls -al /var/run/secrets/kubernetes.io/serviceaccount/
drwxrwxrwt 2 root root   80 Jan 13 23:18 .
drwxr-xr-x 3 root root 4096 Jan 13 23:26 ..
-r--r--r-- 1 root root 7845 Jan 13 23:18 ca.crt
-r--r--r-- 1 root root  846 Jan 13 23:18 token
root@mypod:/#
```

This is what happens when I upgrade the machine to Docker 1.9.1 (not working):

```
$ # docker exec into the pod's container
$ sudo docker exec -t -i 2fc /bin/bash
root@mypod:/# ls -al /secret/
root@mypod:/# ls -al /var/run/secrets/kubernetes.io/serviceaccount/
root@mypod:/#
```

With Docker 1.9.1, the files DO exist on the host:

```
$ sudo ls -al /var/lib/kubelet/pods/ea4ad4dd-ba4b-11e5-bc0f-005056894f70/volumes/kubernetes.io~secret/secret
total 8
drwxrwxrwt 2 root root   60 Jan 13 15:18 .
drwxr-xr-x 4 root root 4096 Jan 13 15:18 ..
-r--r--r-- 1 root root    3 Jan 13 15:18 abc
$ sudo ls -al /var/lib/kubelet/pods/ea4ad4dd-ba4b-11e5-bc0f-005056894f70/volumes/kubernetes.io~secret/default-token-7pgja
total 16
drwxrwxrwt 2 root root   80 Jan 13 15:18 .
drwxr-xr-x 4 root root 4096 Jan 13 15:18 ..
-r--r--r-- 1 root root 7845 Jan 13 15:18 ca.crt
-r--r--r-- 1 root root  846 Jan 13 15:18 token
```

So it seems that for both the kubernetes service account secret and user-specified secrets, the files get pulled down to the host but are not viewable from the container.
