### ISSUE TITLE
Jobs don't work well with running unit tests

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#19701]
When running unit tests as a Job, I'd like to also run a MySQL, rabbitmq, memcache and Elasticsearch container in the same pod. As these are long running services the Job will never finish. There's also currently no general way to stop a container gracefully from another container in the same Pod. This makes it very hard to run unit tests in the cluster.

I propose to make it easily possible to stop other containers in the Pod, or allow a main container to be specified that when it exits will bring the other containers in the Pod down automatically.

**Comment by mikedanese** [comment]
cc @soltysh @erictune

**Comment by AdoHe** [comment]
@hanikesn IIRC after the unit tests finished, the job corresponding pod should get deleted.

**Comment by hanikesn** [comment]
Here's a workaround using shell scripts to check for a shutdown flag:

```
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: yourname
spec:
  template:
    spec:
      containers:
      - name: tests
        image: yourimg
        command: ["sh", "-c", "execute tests; touch /shutdown/shutdown"]
        volumeMounts:
          - mountPath: /shutdown/
            name: shutdown
      - name: mysql
        image: mysql:5.6
        command: ["sh", '-c', '(until [ -f /shutdown/shutdown ] ; do sleep 1; done; mysqladmin shutdown) & exec /entrypoint.sh mysqld']
        env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "yes"
        volumeMounts:
          - mountPath: /shutdown/
            name: shutdown
      volumes:
        - name: shutdown
          emptyDir:
             medium: Memory
      restartPolicy: Never
```
