### ISSUE TITLE
[Services] Error when creating service in 1.2 with "ClusterIP: None" in spec.

### ISSUE THREAD

**Issue by v1k0d3n** [kubernetes/kubernetes#19744]
```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"bf56e235826baded1772fb340266b8419c3e8f30", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"bf56e235826baded1772fb340266b8419c3e8f30", GitTreeState:"clean"}
```

Here's the service declaration file, as documented on the NGINX website:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ClusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
```

This causes an error:
```
error validating "nginx-service.yaml": error validating data: found invalid field ClusterIP for v1.ServiceSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

I tried looking for 1.2 docs for changes to services declarations, but I couldn't find anything related to 1.2 or warnings in the release notes. Hopefully, I'm not missing something glaring? This works in another deployment with 1.0.6.
