### ISSUE TITLE
Deployment object not creating RCs

### ISSUE THREAD

**Issue by thebeardisred** [kubernetes/kubernetes#19757]
I'm not really sure what info to provide, so let me know. I followed [this guide](http://kubernetes.io/v1.1/docs/user-guide/deployments.html) exactly. I'm running a single node kubernetes cluster. Here's the apiserver config
```
    command:
    - /hyperkube
    - apiserver
    - --insecure-bind-address=0.0.0.0
    - --cluster-name=infra
    - --service-cluster-ip-range=10.31.0.0/17
    - --etcd-servers=http://localhost:4001
    - --token-auth-file=/dev/null
    - --advertise-address=0.0.0.0
    - --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota
    - --cluster-name=infra
    - --runtime-config=extensions/v1beta1/deployments=true
```
I have the latest release (1.1.4). I'm using the spec file given, but I will reproduce it here:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
I created it with the following command:
```bash
$> kubectl create -f test.dp.yaml  --validate=false
```
The `--validate=false` is because of [this bug](https://github.com/kubernetes/kubernetes/issues/19515). And here's what I see:
```bash
$> kubectl get deployments
NAME               UPDATEDREPLICAS   AGE
nginx-deployment   0/3               27m
```
digging deeper:
```bash
$> kubectl describe deployment nginx-deployment
Name:                           nginx-deployment
Namespace:                      default
CreationTimestamp:              Sat, 16 Jan 2016 00:38:42 -0800
Labels:                         app=nginx
Selector:                       app=nginx
Replicas:                       0 updated / 3 total
StrategyType:                   RollingUpdate
RollingUpdateStrategy:          1 max unavailable, 1 max surge, 0 min ready seconds
OldReplicationControllers:      <none>
NewReplicationController:       <none>
No events.
```
Why are there `No events`? Shouldn't I see something failing? I don't see anything enlightening in the kubelet or the apilogs. I have no idea what I'm missing here...
