### ISSUE TITLE
All-in-one managed data volume

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#19762]
This issue is to aggregate opinions and indications of interest in a single volume that handles all types of 'managed' data, such as:
1.  Secrets
2.  ConfigMaps
3.  Downward API
4.  Service Links

One possible API for such a volume might look like:

``` yaml
name: my-mega-dir
items:
  - configMapName: my-config-map
    files:
      - key: config
        file: myapp.conf
  - secretName: my-secret
    files:
      - key: password
        file: path/passwd.txt
  - downwardAPI: 
      apiVersion: v1
      fieldPath: metadata.name
    file: myapp.name.txt
```

Forking issue from discussion that started here: https://github.com/kubernetes/kubernetes/pull/18586#discussion_r49519513
