### ISSUE TITLE
kubectl update/replace not working for resources quotas 

### ISSUE THREAD

**Issue by balooo** [kubernetes/kubernetes#19822]
We create a resource quota using:

`kubectl --namespace=tools update -f quota.yaml`

quota.yml
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
spec:
  hard:
    cpu: "2"
    memory: 3Gi
    resourcequotas: "1"
```

Then doing : 

`kubectl --namespace=tools update -f quota.yaml`  or `kubectl --namespace=tools replace -f quota.yaml`

results in 

```
Error from server: error when replacing "quota.yaml": resourcequotas "quota" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
```

If the initial resource was created with:

quota.yml
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  resourceVersion: "0"
spec:
  hard:
    cpu: "2"
    memory: 3Gi
    resourcequotas: "1"
```

Then any subsequent updates/replaces work as expected.  (i.e. including `resourceVersion: "0"` in the metadata).  The only other workaround we have is to include a `--force` so that the quota is deleted then recreated.
