### ISSUE TITLE
udp port forwarding failing

### ISSUE THREAD

**Issue by hyperbolic2346** [kubernetes/kubernetes#19937]
I'm not sure what is going on here, but I have a fairly simple example of my issue. It appears that udp packets aren't being properly routed or the service is getting confused about the origin of such packets. I am running kubernetes on a coreos bare-metal cluster. I have my firewall forwarding port 67438 tcp and udp to the master machine for now(10.0.1.19). I have the following setup for a mumble server:
The replication controller:
```
    apiVersion: v1
    kind: ReplicationController
    metadata:
      name: mumble-v0
      labels:
        app: mumble
        version: v0
    spec:
      replicas: 1
      selector:
        app: mumble
        version: v0
      template:
        metadata:
          labels:
            app: mumble
            version: v0
        spec:
          containers:
          - name: mumble
            image: coppit/mumble-server
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 0.5
                memory: 500Mi
            ports:
            - containerPort: 64738
              name: mumble
            - containerPort: 64738
              name: mudp
              protocol: UDP
```
And the service:
```
    apiVersion: v1
    kind: Service
    metadata:
      name: mumble
      labels:
        app: mumble
        kubernetes.io/name: "mumble"
    spec:
      selector:
        app: mumble
      ports:
      - name: mumble
        port: 64738
      - name: mumble-udp
        port: 64738
        protocol: UDP
      externalIPs: ["10.0.1.19"]
```
If I exec inside the container I am able to verify an echo of the udp ports as expected, but the mumble server fails to function properly. Any user connected can only see themselves talking and can not hear anyone else. My understanding is that all voice is handled via udp. If I run the container with docker `docker run --name mumble --rm -p 64739:64738 -p 64739:64738/udp coppit/mumble-server` everything works fine. Note that I'm using a different port so as to not impact the kubernetes mumble server.

I've also had trouble with other services that use udp, but this one is the most concise. I'm hoping it is just some configuration issue that I have, but I'm not able to figure out what could be the issue.
