### ISSUE TITLE
apiserver proxy: no endpoints available error if Service.spec.ports[*].name is specified

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#20070]
Hello everyone!
I noticed this strange behaviour today when I was trying to connect to my service via the `apiserver proxy`:
```yaml
spec:
  ports:
  - port: 80
    name: foo
    targetPort: 3000
```
```console
$ curl -sSL localhost:8080/api/v1/proxy/namespaces/default/services/foobar
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"gogs\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

But when I deleted the `Service.spec.ports[*].name` field, it worked as it should:
```yaml
spec:
  ports:
  - port: 80
    targetPort: 3000
```
```console
$ curl -sSL localhost:8080/api/v1/proxy/namespaces/default/services/foobar
OK
```

Is this a known bug? Or is it made this way "by design"?
This also makes services with two or more ports inaccessible via apiserver proxy
@ArtfulCoder @thockin
