### ISSUE TITLE
NodePort allocation conflates TCP and UDP

### ISSUE THREAD

**Issue by matthiasr** [kubernetes/kubernetes#20092]
Consider a service like

```yaml
apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    …
  clusterIP: …
  type: NodePort
  ports:
  - name: dns
    port: 53
    nodePort: 30053
    protocol: UDP
  - name: dns-tcp
    port: 53
    nodePort: 30053
    protocol: TCP
```

The API refuses to accept this service, stating

> Service "dns" is invalid: spec.ports[1].nodePort: invalid value '30053', Details: provided port is already allocated

It works fine without `nodePort`. It works when using _different_ ports. The iptables rules installed (in `--proxy-mode=iptables` mode) are TCP/UDP specific.

I'm not sure if this is deliberate but not well documented, or a bug? I don't see a reason not to allow a UDP and TCP node port to have the same number.
