### ISSUE TITLE
Job being constanly recreated despite RestartPolicy: Never

### ISSUE THREAD

**Issue by tobad357** [kubernetes/kubernetes#20255]
I have a job with the spec as shown below.
During testing we are forcing a non zero exit code and would expect the job to not be recreated.
However the Job controller keeps on creating new pods again and again while I would expect after reading the docs that it would run it once and if it fails it fails.
Are our assumptions incorrect and if they are is there someway we can run an image on the K8S cluster and get the return value back without it being scheduled to run again on failure?

```
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: app-deploy
spec:
  selector:
    matchLabels:
      app: app-deploy
  template:
    metadata:
      name: app-deploy
      labels:
        app: app-deploy
    spec:
      containers:
      - name: db-upgrade
        image: XXXX/XXX
      restartPolicy: Never
```
