### ISSUE TITLE
Overlapping jobs are easy to create and hard to debug.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#20350]
A user had created a job with a matches-all selector while playing with jobs.  Then the user made a second job (details unimportant).  The second job would start a pod.  The job controller would notice a pod was created. It would try to match the created pod with a job.  It would match both.  It matched the first because that selector matched everything.  It matched the second because that created it.  In case of multiple matches, the job controller sorted the jobs by creation time and picked the oldest one.
But the oldest/first job saw the pod as not needed because it had parallelism 0 and/or was completed.  So it deleted the pod immediately.  This happened so fast that it looked like no pods were ever created.

This took me many hours to debug, in part because there were so many spurious error message and other red herrings.  

This needs to be easier to debug, or prevented entirely.

I don't think the details matter, but for reference the first job looked like this:
```
apiVersion: extensions/v1beta1
kind: Job
metadata:
  generateName: test-job-
spec:
  completions: 1
  parallelism: 0
  selector: {}
  template:
    spec:
      containers:
      - command:
        - ls
        image: busybox
        name: c
        resources: {}
        terminationMessagePath: /dev/termination-log
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
```
