### ISSUE TITLE
Headless service targetPort not resolving containerPort name

### ISSUE THREAD

**Issue by ewolinetz** [kubernetes/kubernetes#20488]
It seems that my headless service definition does not correctly resolve the containerPort name.
I receive this error when I `oc process <template> | oc create -f -`
```
Error from server: Service "logging-es-cluster" is invalid: spec.ports[0].port: invalid value '9300', Details: must be equal to targetPort when clusterIP = None
```

My service is defined as:
```
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "logging-es-cluster"
    spec:
      portalIP: "None"
      ports:
      -
        port: 9300
        targetPort: cluster
      selector:
        provider: "openshift"
        component: "es"
```

And my container is defined with:
```
              ports:
              -
                containerPort: 9200
                name: "restapi"
              -
                containerPort: 9300
                name: "cluster"
```

This was run using kubernetes v1.2.0-alpha.4-851-g4a65fa1
