### ISSUE TITLE
Investigate kube-proxy performance needs

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#20567]
There's been awful amounts of flake in various nodeport services tests that seem to indicate a kubeproxy bottleneck. There are a couple of prs in flight that might help, but this bug is to make sure we don't let the e2e tests (which currently retry for way longer than necessary) to continue doing so.

Related https://github.com/kubernetes/kubernetes/issues/20470, https://github.com/kubernetes/kubernetes/issues/20402, https://github.com/kubernetes/kubernetes/pull/20471

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/20402, https://github.com/kubernetes/kubernetes/pull/20471

**Comment by AdoHe** [comment]
@bprashanth Ok, I will do more investigate about kube-proxy performance.

**Comment by jeremyeder** [comment]
One of my team members was working on this last week.  @ofthecurerh can you please provide an update?

**Comment by bprashanth** [comment]
@jeremyeder an update would be good. I haven't had the time to loop back to this, but we did put a couple of fixes in. Most important thing i care about is how much lag do we observe for something like flipping a service to Type=NodePort, till all nodes see and apply this update to iptables.

**Comment by jeremyeder** [comment]
@bprashanth I am so sorry -- we had to table the proxy testing because we got a higher priority interrupt.  It's still on the list but not in the current sprint anymore.

**Comment by thockin** [comment]
@bprashanth It sounds like the most pressing problems are fixed.  I'd still like to leave this open to investigate what the right value for CPU is.  Will retitle.

**Comment by thockin** [comment]
It would be nice to get memory and CPU profiles of kube-proxy, and make sure we understand the top items, and see if we can reduce our footprint any.

**Comment by thockin** [comment]
This would be a cool intern or community project.

**Comment by jeremyeder** [comment]
@ofthecurerh

**Comment by ofthecure** [comment]
@bprashanth I've had a few issues with the userspace mode, but the iptables mode has been pretty consistent. Are there particular tests that were showing flake?

The only thing I've found interesting about the iptables mode is that it seems to be less fair with distributing network traffic.

**Comment by bprashanth** [comment]
@ofthecure this was fixed, we just need to profile the resource usage now, for a lot of services and endpoints. 

> The only thing I've found interesting about the iptables mode is that it seems to be less fair with distributing network traffic.

Yeah we use statistical mode in iptables and I've observed something similar too. I think we're sometimes not setting the probabilities right. Needs some digging.

**Comment by AI-PaaS** [comment]
Does the issue be resolved? I have hit it. I have a four node cluster and kube proxy use iptables. In the cluster i deployed the zookeeper cluster and kafa cluster only. when i use java zk client connection to the zk, the connection established is very slow, same as kafka.

**Comment by thockin** [comment]
kube-proxy is not involved in connection setup.  If it is slow, it is
something else.

**Comment by cmluciano** [comment]
@kubernetes/sig-network-misc Do we think this is still relevant?

**Comment by cmluciano** [comment]
/assign

assigning to me for now since bprashanth does not work on the project anymore

**Comment by dohnto** [comment]
Hello, encounter problem with iptables performance.

First, let me describe our setup:
 * 10 bare metal node cluster, 16 procs, 94 GB RAM, load is below 2
 * 380 pods
 * 492 services (we use **several services on single deployment**)
 * 3710 iptables lines

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-11T07:11:31Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-11T07:11:31Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

```
 * We use flanneld as a network plugin (0.7.0-0)
 * We run debian jessie

The problem is following:

We can see issues with slow iptables flushing when often deleting and re-creating pods. Docker reuses the same ip addresses repeatedly, just after the container finishes, so it is possible that **container-a** has a certain IP address, it finishes and new **container-b** receives the same address, before the iptables rules are updated on all nodes, it is possible that **container-b** receives traffic meant to be send to **container-a**, which can cause very much confusion and event data corruption.

It should be noted, that I have no **hard** evidence that the root cause of this is iptables, but if we lower the number of services/pods/iptables rules, we don't see the issues anymore.

---
Minimal artificial model use-case how to reproduce in our environment is following:

We build a dummy app using this Dockerimage
```Dockerfile
FROM fedora
RUN dnf install -y python2-flask
ADD app.py /
ENV FLASK_APP=/app.py
CMD flask run --host=0.0.0.0
```

```python
from flask import Flask
import os
import socket
app = Flask(__name__)

@app.route('/')
def hello_world():
    ip = socket.gethostbyname(socket.gethostname())
    namespace = os.getenv("NAMESPACE")
    return 'I run in namespace=%s, my ip is=%s\n' % (namespace, ip)
```

I have named this image as `dohnto/iptables-fail:0.0.1` (and pushed to docker registry)

We use following kubernetes manifests to deploy it to cluster
```yaml
# test-a.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: dohnto/iptables-fail:0.0.1
        ports:
        - containerPort: 5000
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      nodeSelector:
        kubernetes.io/hostname: node3.dev
---
kind: Service
apiVersion: v1
metadata:
  name: test
spec:
  type: NodePort
  selector:
    app: test
  ports:
    - port: 5000
      nodePort: 11122
```

```yaml
# test-b.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: dohnto/iptables-fail:0.0.1
        ports:
        - containerPort: 5000
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      nodeSelector:
        kubernetes.io/hostname: node3.dev
---
kind: Service
apiVersion: v1
metadata:
  name: test
spec:
  type: NodePort
  selector:
    app: test
  ports:
    - port: 5000
      nodePort: 11123
```

Note that the deployments are identical except the Service's nodePort number. After I run this init script:
```bash
# init.sh
kubectl create ns test-a
kubectl -n test-a apply -f test-a.yaml
kubectl create ns test-b
kubectl -n test-b apply -f test-b.yaml

while true; do
    kubectl -n test-a delete pod -l app=test --grace-period=5
    sleep 10
    kubectl -n test-b delete pod -l app=test --grace-period=5
    sleep 10
done
```
Finally, I run this script to periodically scrape the **test-b** endpoint
```bash
#!/bin/bash
# test.sh
  
trap "exit" SIGINT SIGTERM
port=$1

previous_out=

while :; do
    for node_i in {1..10}; do # iterate through all nodes
       node=node${node_i}.dev
       out=$(timeout 1s curl -s http://$node:$1)
       if [ "$out" != "$previous_out" ]; then
            date
            echo $node
            echo $out
        fi
        previous_out="$out"
    done
done
```

When I run 
```
./test.sh 11123 # test-b node port
...
Mon 14 Aug 10:39:35 CEST 2017
node1.dev
I run in namespace=test-a, my ip is=172.24.51.22
Mon 14 Aug 10:39:36 CEST 2017
node6.dev
I run in namespace=test-b, my ip is=172.24.51.28
Mon 14 Aug 10:39:36 CEST 2017
node7.dev
I run in namespace=test-a, my ip is=172.24.51.22
Mon 14 Aug 10:39:36 CEST 2017
node4.dev
I run in namespace=test-b, my ip is=172.24.51.28
Mon 14 Aug 10:39:37 CEST 2017
...
```
Here we expect only to see `namespace=test-b`, but due to slow iptables flushing, on some nodes we hit also container from `namespace=test-a`.
