### ISSUE TITLE
Fluentd pod on master has broken resolv.conf

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#20670]
Causing fluentd to fail to export logs from the master, because it can't resolve logging.googleapis.com (or anything else, for that matter). It only seems to affect the fluentd pod, not the other kube-* pods.

In an affected fluentd pod on the master at HEAD:
```
/etc/hosts:
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
fe00::1 ip6-allnodes
fe00::2 ip6-allrouters
172.17.0.3      fluentd-cloud-logging-gke-249458424157-f624d740e956aedbf6f2

/etc/resolv.conf:
nameserver 10.247.240.10
search kube-system.svc.cluster.local svc.cluster.local cluster.local c.projectid.internal. google.internal.
options ndots:5

/etc/resolvconf/interface-order:
# interface-order(5)
lo.inet*
lo.dnsmasq
lo.pdnsd
lo.!(pdns|pdns-recursor)
lo
tun*
tap*
hso*
em+([0-9])?(_+([0-9]))*
p+([0-9])p+([0-9])?(_+([0-9]))*
eth*
ath*
wlan*
ppp*
*
```

In an unaffected kube-apiserver pod on the same master VM:
```
/etc/hosts:
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
10.240.0.15 gke-249458424157-f624d740e956aedbf6f2.c.gke-test-us-central1-f-0.internal gke-249458424157-f624d740e956aedbf6f2  # Added by Google

/etc/resolve.conf:
domain c.projectid.internal.
search c.projectid.internal. 365122390874.google.internal. google.internal.
nameserver 169.254.169.254
nameserver 10.240.0.1

/etc/resolveconf/interface-order: doesn't exist
```

In a functioning fluentd pod on the master at 1.1.7
```
/etc/resolv.conf
nameserver 10.159.240.10
nameserver 169.254.169.254
nameserver 10.240.0.1
search kube-system.svc.cluster.local svc.cluster.local cluster.local c.projectid.internal. google.internal.
options ndots:5
```

@ArtfulCoder @thockin @kubernetes/goog-cluster

**Comment by thockin** [comment]
This looks like the difference between DNS policy "default" and "cluster first"

**Comment by thockin** [comment]
Can you kubectl get -o yaml the pod?

**Comment by a-robinson** [comment]
It's started by a manifest file on the node, not via the API, and this is the yaml from the API:
```
apiVersion: v1
kind: Pod
metadata:
  name: fluentd-cloud-logging
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  containers:
  - name: fluentd-cloud-logging
    image: gcr.io/google_containers/fluentd-gcp:1.15
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    env:
    - name: FLUENTD_ARGS
      value: -q
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
  terminationGracePeriodSeconds: 30
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
```
