### ISSUE TITLE
NFS PV is getting mounted then immediately unmounted, causing Kubernetes to fail to bring up pods

### ISSUE THREAD

**Issue by AmandaCameron** [kubernetes/kubernetes#20734]
Kubelet seems to be having trouble mounting a NFS PV. The mount will briefly appear in the mount output, then immediatly (within 2s) disappear. This is causing some major headaches for me.

The only clue I can find is this:
I0205 19:00:24.904536   27673 nfs.go:157] NFS mount set up: /var/lib/kubelet/pods/8c73c65c-cc39-11e5-810b-5600001de9f9/volumes/kubernetes.io~nfs/maine-coon-keys false stat /var/lib/kubelet/pods/8c73c65c-cc39-11e5-810b-5600001de9f9/volumes/kubernetes.io~nfs/maine-coon-keys: no such file or directory

if I spam stat <path given> it'll stat, then disappear again, presumably when it gets unmounted.

I was told in the slack to cc @saad-ali so here it is.

**Comment by AmandaCameron** [comment]
Upon scanning through with a different grep, it appears it's mounted, then immediatly called an orphan and unmounted.

**Comment by thockin** [comment]
@rootfs also

**Comment by metral** [comment]
I too am hitting this hiccup on v1.1.7.

I filed a similar issue on v1.1.3 a few months back https://github.com/kubernetes/kubernetes/issues/18749

**Comment by rootfs** [comment]
@AmandaCameron what are your pod and pv/pvc like? i want to run it locally to reproduce this issue.

**Comment by rootfs** [comment]
This looks similar to #18749

**Comment by metral** [comment]
Agreed, like https://github.com/kubernetes/kubernetes/issues/18749, its orphaning + unmounting the disk on its own.

my PV:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mystore
    server: <IP_ADDR>
```

my PVC:

```
apiVersion: v1
metadata:
  name: my-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

My NFS server is nfsv4 running on an Ubuntu 14.04 distro with /etc/exports looking like such, where 192.168.1.100 is a K8s Node:

```
/mystore 192.168.1.100(rw,sync,no_root_squash,no_all_squash,no_subtree_check)
```

Mounting the NFS volume manually from other machines works fine and has no issues, but when NFS is used with PV+PVC I hit this orphaning issue all the time.

The pod hits this issue while instantiating per `kubectl describe`:
```
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Reason          Message
  ─────────     ────────        ─────   ────                    ─────────────   ──────          ───────
  5m            5m              1       {scheduler }                            Scheduled       Successfully assigned my-rc to 192.168.1.100
  5m            4s              33      {kubelet 192.168.1.100}                 FailedMount     Unable to mount volumes for pod "my-rc": exit status 32
  5m            4s              33      {kubelet 192.168.1.100}                 FailedSync      Error syncing pod, skipping: exit status 32
```

**Comment by rootfs** [comment]
@kubernetes/goog-node

**Comment by rootfs** [comment]
@metral I tested v1.1.7 code locally using your pv/pvc and my own pod, found no problem so far.

is it possible to post your pod?

**Comment by AmandaCameron** [comment]
my PVC/PV are the same as above, the Pod is just the normal

```yaml
...
volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-pvc
```
