### ISSUE TITLE
pods don't run in replication controller

### ISSUE THREAD

**Issue by bitchecker** [kubernetes/kubernetes#20964]
Hi, i've a simple kubernetes cluster with a master and two minions. In this scenario, if i run a simple pod of a nginx or a mysql it works properly but, if i change type of KIND into yaml file and i try to run a replicated service, pods will start but i can't access to the service.

this is my yaml file for nginx simple pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    name: nginx
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: nginx
      name: nginx
      ports: 
        - containerPort: 80
          name: nginx
```

it works properly and i can access to it after i run associated service.

this is my yaml file for nginx with 2 replicas:
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

obviously, i run also related service yaml.
