### ISSUE TITLE
PV auto-provisioning on GCE doesn't work

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#21041]
```
E0211 01:00:31.253641       6 persistentvolume_provisioner_controller.go:144] Error encoutered reconciling claim pv-provisioning-demo: PersistentVolumeClaim[pv-provisioning-demo] failed provisioning: persistentvolumes "pv-gce-" is forbidden: error querying GCE PD volume dummy: GCE persistent disk not found: "dummy"
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: demos
  name: pv-provisioning-demo
  labels:
    demo: pv-provisioning
  annotations:
    volume.alpha.kubernetes.io/storage-class: anything
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
```

This needs a fix and an e2e ASAP.
