### ISSUE TITLE
[proxy] Listening on a specific IP for nodePort

### ISSUE THREAD

**Issue by guilhem** [kubernetes/kubernetes#21070]
For now, we are listening on any interface for nodePorts.
It can be a problem for machines with a public and private address, where we only want to provide a service in private network.

What can be done is to user `--bind-address` and listening only on this IP.

I already have a commit with this feature: https://github.com/guilhem/kubernetes/tree/listennode
It lack support in `userspace` part and tests but is working fine for `iptables`.

**Comment by AdoHe** [comment]
@guilhem interesting and I will look into this.

**Comment by guilhem** [comment]
Thx @AdoHe , code is quite simple, especially after latest commit with `args` reformatting :)

I only add a restriction with `-d` for `127.0.0.1,{IP}`. (iptables create 2 rules for each ip)

**Comment by bgrant0607** [comment]
cc @kubernetes/goog-cluster

**Comment by thockin** [comment]
The implementation is simple.  It's the representation I am concerned about.  How do we expose this in the API in a way that doesn't require users to do something like name 'eth1'.  

Is this a case of wanting localhost only or of actually having multiple NICs, some public and some private?

An idea that has been bouncing around in my head, but I am not sure I like it:  Let nodes describe the set of interfaces they have and apply labels to those interfaces.  Then let operations like this specify an interface selector.  For example:

```
Node:
  networkInterfaces:
  - name: eth0
    addresses:
    - 10.240.93.76
    labels:
        kubernetes.io/exposure: internal
  - name: eth1
    addresses:
    - 1.18.19.78
    labels:
        kubernetes.io/exposure: public
```

```
Service:
  type: NodePort
  interfaceSelector:
    kubernetes.io/exposure: internal
```

That's a fairly complicated change, but I feel like it might pay off over time to have that info.  That said, nodes would have to populate it...

@kubernetes/sig-node @kubernetes/goog-node
