### ISSUE TITLE
skydns service resolution

### ISSUE THREAD

**Issue by bitchecker** [kubernetes/kubernetes#21271]
on my kubernetes cluster i've deployed skydns addon.

this is skydns yaml file:
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v8
  labels:
    k8s-app: kube-dns
    version: v8
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 3
  selector:
    k8s-app: kube-dns
    version: v8
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v8
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        command:
        - /usr/local/bin/etcd
        - -data-dir
        - /var/etcd/data
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
        volumeMounts:
        - name: etcd-storage
          mountPath: /var/etcd/data
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.11
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/kube2sky"
        - -domain=kube.local
        - -kube_master_url=http://MASTER_NODE_IP:8080
      - name: skydns
        image: skynetservices/skydns:latest
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/skydns"
        - -machines=http://localhost:4001
        - -addr=0.0.0.0:53
        - -domain=kube.local
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
      - name: healthz
        image: gcr.io/google_containers/exechealthz:1.0
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.default.svc.kube.local localhost >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.
```

and this is related service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.254.0.2
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```

i've deplyed a simple busybox pod, and this is his yaml file:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
```

if i run:
```bash
# kubectl exec busybox -- nslookup kube.local
```

i get:

```bash
Server:    10.254.0.2
Address 1: 10.254.0.2

Name:      kube.local
Address 1: 10.254.0.1
Address 2: 10.254.0.2
```

if i run a simple pod with a casual image i would get to resolve it from dns, i tried:

```bash
# kubectl exec busybox -- nslookup mysql.kube.local
Server:    10.254.0.2
Address 1: 10.254.0.2

nslookup: can't resolve 'mysql.kube.local'
error: Error executing remote command: Error executing command in container: Error executing in Docker Container: 1
```

i've tried also:

```bash
# kubectl exec busybox -- nslookup mysql.default.svc.cluster.local                                                                                                     
Server:    10.254.0.2
Address 1: 10.254.0.2

nslookup: can't resolve 'mysql.default.svc.cluster.local'
error: Error executing remote command: Error executing command in container: Error executing in Docker Container: 1
```

if i run the same command on busybox, i get:

```bash
# kubectl exec busybox -- nslookup kube.local                                                                                                                  [0/1922]
Server:    10.254.0.2
Address 1: 10.254.0.2

Name:      kube.local
Address 1: 10.254.0.1
Address 2: 10.254.0.2
Address 3: 10.254.131.103
```

so, busybox found mysql pod with ip 10.254.131.103 but it's reported as dns server how can i solve mysql pod with a direct name record?
