### ISSUE TITLE
Fluentd image to log to ES service on AWS

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#21285]
There is a plugin that seems able to do this, linked from Fluent::Plugin::Elasticsearch:

https://github.com/atomita/fluent-plugin-aws-elasticsearch-service

cc: @a-robinson @jimmidyson

**Comment by justinsb** [comment]
There's also a proxy I wrote that can be dropped in instead of the k8s ES service: https://github.com/kopeio/aws-es-proxy

**Comment by therc** [comment]
What are pros (beside simplicity) and cons of the proxy? I'll give it a shot in the morning.

**Comment by justinsb** [comment]
I'd say the biggest advantage is that it means the whole ES ecosystem works with the AWS ES service, rather than having to patch each reader/writer to speak AWS auth.  The biggest cons are that it isn't really heavily tested and is another piece vs having the clients speak direct to ES.

**Comment by therc** [comment]
The proxy works perhaps a bit too well. 80% of my log files, with minimal services on, are from kube-dns' healthz container.

**Comment by a-robinson** [comment]
Heh, that's not the proxy's fault :)

I've noticed that as well -- the DNS healthz output dominates the logs from any cluster without much running on it. cc @bprashanth to see whether there's a reasonable way to make it quieter

**Comment by bprashanth** [comment]
We can just add a -q flag and have the health prober shutup under normal conditions: https://github.com/kubernetes/contrib/blob/master/exec-healthz/exechealthz.go#L42. @therc if you have the time please send a pr? if not I'll get to it in due time.

**Comment by therc** [comment]
I was being ironic, sorry. The healthz logs were actually quite helpful in debugging earlier issues, but perhaps they don't belong into ES.

I think I'll have to tweak the loggers' configuration to toss our the healthz checks. As to what I was actually doing: I just created a DaemonSet with the standard fluentd-elasticsearch:1.14 image with its built-in configuration, then brought up the proxy as service kube-system:elasticsearch-logging (because fluentd was setup for that hostname).

**Comment by therc** [comment]
I'll see if I can get to implement the flag in the next couple of days during downtime. For now, it's a good load test!

**Comment by therc** [comment]
The proxy seems to work well. I'm going to be running tests to look for dropped entries, but it's been able to handle 20G/day before replication without issues.

So, what's the next step?

We could either recommend the proxy+fluentd-elasticsearch setup or have yet another image as I originally suggested. I have a couple of issues open regarding the existing image. One is for reliability (#22366, silently dropping logs when the ES endpoint returns 403) and one is a feature request (#22222, sending the cluster name along). Another ideal feature for production readiness would be a second output to dump logs to S3, for long-term storage. I'm not sure if this should be supported through additional flags (environment variables) passed to the image (or to the proxy!) or if we should allow the administrator to provide drop-in configurations.

**Comment by drora** [comment]
Guys, this is awesome.. is there any usage documentation or reference?

**Comment by cheungpat** [comment]
For those who are interested, I have a docker image with fluentd and the [aws elasticsearch plugin] installed. It can send log to AWS Elasticsearch without requiring a proxy for authenticating to AWS Elasticsearch:

https://github.com/cheungpat/fluentd-es-aws
https://hub.docker.com/r/cheungpat/fluentd-elasticsearch-aws

You can compare it to the fluentd-es image which I modified to build my own image:

https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image

To use the fluentd-es-aws image, you need to set extra environment variables. Here is the daemonset manifest I used to run my fluentd:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: fluentd-logging
    kubernetes.io/cluster-service: "true"
  name: fluentd-elasticsearch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      kubernetes.io/cluster-service: "true"
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: fluentd-logging
        kubernetes.io/cluster-service: "true"
      name: fluentd-elasticsearch
      namespace: kube-system
    spec:
      containers:
      - env:
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_ELASTICSEARCH_URL
          value: https://name.us-west-2.es.amazonaws.com
        - name: AWS_ACCESS_KEY_ID
          value: <access key>
        - name: AWS_SECRET_ACCESS_KEY
          value: <secret access key>
        image: cheungpat/fluentd-elasticsearch-aws:1.22
        imagePullPolicy: IfNotPresent
        name: fluentd-elasticsearch
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
      restartPolicy: Always
      tolerations:
      - effect: NoSchedule
        key: node.alpha.kubernetes.io/role
        operator: Equal
        value: master
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
```
