### ISSUE TITLE
health checks example

### ISSUE THREAD

**Issue by joshuacox** [kubernetes/kubernetes#21315]
From a default kubernetes setup on GCE using kube-up.sh.  Using the pod with healthcheck from the walkthrough:

https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/walkthrough/pod-with-http-healthcheck.yaml

```
kubectl create -f pod-with-http-healthcheck.yaml                                        
pod "pod-with-healthcheck" created

kubectl get pods
NAME                   READY     STATUS    RESTARTS   AGE
pod-with-healthcheck   0/1       Pending   0          9s

kubectl describe pod/pod-with-healthcheck   
<<TRUNCATING>>
44818900b384
  40s           40s             1       {kubelet kubernetes-minion-zkwc}        spec.containers{nginx}                  Killing         Killing with docker id b64f4ec76991
  40s           40s             1       {kubelet kubernetes-minion-zkwc}        spec.containers{nginx}                  Created         Created with docker id 44818900b384
  40s           10s             2       {kubelet kubernetes-minion-zkwc}        spec.containers{nginx}                  Unhealthy       Liveness probe failed: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.9.11</center>
</body>
</html>
```

I notice running the 'nginx' without the healthchecks that _status/healthz is not a functioning URI, so I changed the path to: 

```
diff fix.yaml pod-with-http-healthcheck.yaml 
13c13
<         path: /
---
>         path: /_status/healthz
```

and now the liveness probe succeeds, but if I add in a readiness check it reports unhealthy:

```
 1m            1m              3       {kubelet kubernetes-minion-zkwc}        spec.containers{nginx}                  Unhealthy       Readiness probe failed:
```

I feel like, as this is the default example, I may be doing something wrong on my end.  I ran into all of this first while setting up [Kubernetes on Arm](https://github.com/luxas/kubernetes-on-arm) where I expect a few issues.  But I'm failing on the bog standard kubernetes on GCE setup as well.  Here's my example pod with readiness probe:

```
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-healthcheck
spec:
  containers:
  - name: nginx
    image: nginx
    # defines the health checking
    livenessProbe:
      # an http probe
      httpGet:
        path: /
        port: 80
      # length of time to wait for a pod to initialize
      # after pod startup, before applying health checking
      initialDelaySeconds: 30
      timeoutSeconds: 1
    readinessProbe:
      # an http probe
      httpGet:
        path: /
        port: 80
      # length of time to wait for a pod to initialize
      # after pod startup, before applying health checking
      initialDelaySeconds: 30
      timeoutSeconds: 1
    ports:
    - containerPort: 80
```

If I'm doing something wrong I'd greatly appreciate any help on what I need to do otherwise.
