### ISSUE TITLE
Graceful termination doesn't play well with services

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#21418]
Use case:

I have a download server sitting behind a service with long lived tcp connections. I want to let connections complete before shutting down. I set termination grace period to 5 minutes. My pod is deleted gracefully.

Expected behavior:

Kube-proxy does not send any new connections to my pod. but allows open connections to remain intact. Downloads finish after 40 seconds. My pod shuts down.

Current behavior:

Endpoints controller immediately removes my pod from the service's endpoints. Kube-proxy deletes the load balancing iptables rule for my pod. The connection is dropped in the time that it takes the deletion to propagate ( ~ 10 seconds).

cc @smarterclayton @thockin @ArtfulCoder

**Comment by smarterclayton** [comment]
Would definitely not expect the drop to happen until the pod is removed -
the ip should still be in unready endpoints, so it's possible that the kube
proxy should only drop rules that aren't in ready or unready endpoints

**Comment by smarterclayton** [comment]
Actually, this may even be a bug that terminating pod ips should move the
unready endpoints

**Comment by mikedanese** [comment]
I'm going to confirm that the current behavior I described is actually causing what I'm observing right now, closing for now

**Comment by ArtfulCoder** [comment]
I created nc server on ubuntu pod
` cat linux-4.5-rc4.tar.xz  | nc -l -p 8080`
where the xz file is a big file.

I created a service that hits 8080 on that ubuntu pod

I then did
`curl --limit-rate 1k http://10.0.201.246:8080 > foo` on another node.
where the ip specified is the service ip.


I then deleted the service that mapped to the ubuntu pod.
The curl download still continued without any problem.

```
abshah@abhidesk:~/go/src/k8s.io/kubernetes$ cat ubuntusvc.yaml 
apiVersion: v1
kind: Service
metadata:
  name: ubuntusvc
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: ubuntu
```

```
abshah@abhidesk:~/go/src/k8s.io/kubernetes$ cat ubuntusvc.yaml 
apiVersion: v1
kind: Service
metadata:
  name: ubuntusvc
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: ubuntu
abshah@abhidesk:~/go/src/k8s.io/kubernetes$ 
abshah@abhidesk:~/go/src/k8s.io/kubernetes$ cat ubuntupod.yaml 
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ubuntu
  annotations:
    net.beta.kubernetes.io/podHostname: abhiu
    net.beta.kubernetes.io/podSubdomain: svcu
  name: podu
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command:
      - sh
      - -c
      - sleep 3600
  restartPolicy: Never
```
