### ISSUE TITLE
How to start a container in pod?

### ISSUE THREAD

**Issue by Toplife** [kubernetes/kubernetes#21660]
Hi all,
Now I want start a container by k8s pod,below is my docker run command
:
` docker run -it -d --name=aaa--net=host -v /opt/headedness/phantomjs:/data/phantomjs/bin/phantomjs -v /opt/ctcrawler/log:/data/log xxx/app/xxx -endpoint http://xxx/c2/ -selenium http://localhost:4444/wd/hub`
How to change this command to .yaml file?
below is my .yaml file,but not working:

```
apiVersion: v1
kind: Pod
metadata:
  name: A
spec:
  containers:
    - name: A
      image: xxx/app/A:latest
      net: "host"
      id:
       - XXX
      volumes:
       - /opt/headedness/phantomjs:/data/phantomjs/bin/phantomjs
       - /opt/ctcrawler/log:/data/log
      endpoint:
       - http://xxxxxxx/c2/
      selenium:
       - http://localhost:4444/wd/hub
      imagePullPolicy: Always
  imagePullSecrets:
    - name: myregistrykey
```
Please help...
