### ISSUE TITLE
why do daemonsets often say they were misscheduled?

### ISSUE THREAD

**Issue by jchauncey** [kubernetes/kubernetes#21714]
I've noticed that when looking at the description of a daemonset it will say that it was misscheduled onto 2 nodes. It also normally has the wrong Pod Status. 

```
╰─± k describe ds deis-logger-fluentd
Name:       deis-logger-fluentd
Image(s):   quay.io/deis/fluentd:v2-beta
Selector:   heritage=deis
Node-Selector:  <none>
Labels:     heritage=deis
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Misscheduled: 2
Pods Status:    1 Running / 0 Waiting / 1 Succeeded / 0 Failed
Events:
  FirstSeen LastSeen    Count   From        SubobjectPath   Reason          Message
  ─────────   ────────    ───── ────        ───────────── ──────          ───────
  26m       26m     1   {daemon-set }           SuccessfulCreate    Created pod: deis-logger-fluentd-3u2al
  26m       26m     1   {daemon-set }           SuccessfulCreate    Created pod: deis-logger-fluentd-xvm8c
```

**Comment by mikedanese** [comment]
stale

**Comment by Adhira-Deogade** [comment]
Any updates on this?

**Comment by Pluies** [comment]
FWIW I've noticed this as well on our cluster, and spoiler alerts, it had to do with taints & tolerations!

Full write-up: https://blog.florentdelannoy.com/blog/2020/kube-daemonset-misscheduled/

**Comment by WillerWasTaken** [comment]
Also saw that issue on our end, having
```
  tolerations:
  - effect: NoSchedule
    key: ToBeDeletedByClusterAutoscaler
    operator: Exists
```
toleration was not enough though. We still had a couple of MisScheduled events. Looking at the [daemon_controller code](https://github.com/kubernetes/kubernetes/blob/429f71d9583af6f2add7496fd8e41ae0f180a832/pkg/controller/daemon/daemon_controller.go#L1266), it would seem like to determine whether a pod is misscheduled or not, it filters out the taints against the tolerations for those with the effect `NoSchedule` and `NoExecute`.

While investigating it ended up that the node gets the following taints on scale-in event:
```
  taints:
  - effect: PreferNoSchedule
    key: DeletionCandidateOfClusterAutoscaler
    value: "1666791614"
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    timeAdded: "2022-10-26T13:42:56Z"
  - effect: NoSchedule
    key: node.kubernetes.io/unreachable
    timeAdded: "2022-10-26T13:43:30Z"
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    timeAdded: "2022-10-26T13:43:35Z"
```

Vs the tolerations we had on our daemon set:
```
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/disk-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/pid-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists
```

It appears that the pod is missing
```
    - effect: NoSchedule
      key: node.kubernetes.io/unreachable
      operator: Exists
```

Adding both
```
      - effect: NoSchedule
        key: node.kubernetes.io/unreachable
        operator: Exists
      - effect: NoSchedule
        key: ToBeDeletedByClusterAutoscaler
        operator: Exists
```
to our daemonset seems to fix it for us
