### ISSUE TITLE
kubelet unable to talk to kube-apiserver in 1.2alpha8

### ISSUE THREAD

**Issue by macb** [kubernetes/kubernetes#21901]
When updating 2 different secure mode clusters (one at 1.2alpha7 and one at 1.1.3) both clusters had all the nodes go into `NotReady` after the `kube-apiserver` updated and restarted.

`kubelet` log's at the time look something like:

```
kubelet: W0224 13:32:24.279554   32061 manager.go:402] Failed to update status for pod "_()": the server does not allow access to the requested resource (put pods loadbalancer-kif76)
kubelet: E0224 13:32:24.554102   32061 kubelet.go:2650] Error updating node status, will retry: error getting node "kubelet01": the server does not allow access to the requested resource (get nodes kubelet01)
```

Nothing stood out in the `kube-apiserver` logs. After downgrading the `kube-apiserver` back to `1.1.3` the `1.2alpha8` kubelet was able to update everything and the node returned to `Ready` state.

**Comment by vishh** [comment]
cc @roberthbailey

**Comment by macb** [comment]
When rolling back to 1.2alpha7 the errors persisted. I ended up having to go back to a stable release for everything to become healthy again.

**Comment by roberthbailey** [comment]
/cc @ihmccreery 

Where are you running your clusters (GCP/AWS/bare metal)? And what mechanism are you using to upgrade them?

**Comment by macb** [comment]
Droplets (vms) on DigitalOcean managed by Chef. In all the cases the binaries were replaced on disk and the corresponding upstart service restarted in no particular order (most likely all relatively close to the same time).

**Comment by roberthbailey** [comment]
Did you change the version of docker that you are using?

**Comment by roberthbailey** [comment]
And what kind of auth are you using between the kubelets and the apiserver? Client cert / bearer token / basic auth?

**Comment by macb** [comment]
No, docker did not change with this upgrade. We are on docker version `1.8.2`.

Client certs with this kubeconfig:

```
---
apiVersion: v1
kind: Config
users:
- name: kubelet
  user:
    client-certificate: "/path/to/kubelet.crt"
    client-key: "/path/to/kubelet.key"
clusters:
- cluster:
    certificate-authority: "/path/to/kubelet.ca.crt"
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubelet
  name: service-account-context
current-context: service-account-context
```
