### ISSUE TITLE
apiVersion required in specs

### ISSUE THREAD

**Issue by elouanKeryell-Even** [kubernetes/kubernetes#21988]
field `apiVersion` is marked as 'not required' in the docs, although it seems to me it actually is required. For example, creating this small service:

```
kind: Service
metadata:
  name: example
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    name: example
    kind: Pod
```

fails with:

```
# kubectl create -f example.yml
error validating "example.yml": error validating data: Object 'apiVersion' is missing in '{"kind":"Service","metadata":{"name":"example"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":"http"}],"selector":{"kind":"Pod","name":"example"}}}'; if you choose to ignore these errors, turn validation off with --validate=false
```

**My setup:**

kubectl version 1.1
CentOS 7
Docker version 1.9.1
