### ISSUE TITLE
Not able to run DaemonSet Pods

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/kubernetes#22173]
Hi,

Since today we are running Kube 1.1.8 and I am testing DaemonSets now. I can create a simple daemonset with "kubectl create -f nginx-ds.yaml --valudate=false" (it seems I have to set validate to false):

```

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    name: nginx
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

Then "kubectl get daemonsets" gives me:

```

NAME      CONTAINER(S)   IMAGE(S)   SELECTOR     NODE-SELECTOR
nginx     nginx          nginx      name=nginx   <none>
```
But "kubectl get pods" gives me an empty list. 

Also, I had to add the following option to the kube-apiserver command: 
`
--runtime-config=extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/jobs=true,extensions/v1beta1/ingress=true`
