### ISSUE TITLE
Deployments: Cannot unmarshal objects

### ISSUE THREAD

**Issue by tspecht** [kubernetes/kubernetes#22273]
Hey guys,

I just wanted to try out the new Deployments feature and therefore tried to use one of the example deployment specs I found in this repo and the user guides:

https://github.com/kubernetes/kubernetes/blob/533bc598dd451feabeff85eb1345bb9cf5265300/docs/user-guide/deployment.yaml

When I run that locally against my cluster which is running v1.2.0-alpha.8 I get the following error:

```
kubectl create -f kubernetes/deployment.yaml --v=5

I0301 15:02:48.470600   12155 decoder.go:144] decoding stream as YAML

F0301 15:02:48.522049   12155 helpers.go:96] unable to load "kubernetes/deployment.yaml": json: cannot unmarshal object into Go value of type string
```

Any idea what could cause this and how I could possible resolve this? I know this feature is still in beta but I'm super excited for it and really would love to try it out!

**Comment by AdoHe** [comment]
Seems like a bug, I will take a look.

**Comment by tspecht** [comment]
Okay cool, thanks, thought I was going completely stupid ... Looking forward to what you'll find! :)

**Comment by AdoHe** [comment]
@tspecht can you provide your detailed kubernetes version? `kubectl version` can get this.
I test this feature with this yaml:
```
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```
(copy from the link above)
And it is ok, I can create the deployment:
```
deployment "nginx-deployment" created
```
Of course, my version is:
```
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.8", GitCommit:"5918967a86489460846af94a5c393d971337be29", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.8", GitCommit:"5918967a86489460846af94a5c393d971337be29", GitTreeState:"clean"}
```
And you can get more detailed log through setting log level higher like `--v=9`. Hope this can help you.
