### ISSUE TITLE
Daemonset keeps getting killed if hostNetwork: true

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#22309]
I just built from HEAD.

The DS works fine with pod networking. As soon as I run it with hostNetwork: true, though, the container gets created, then a second or two later, kubelet says "Killing unwanted pod X".

**Comment by mikedanese** [comment]
Does this happen on all nodes?

**Comment by therc** [comment]
Yes, on all of them, where by "all" I mean both in my crash cell. One of them is the master with an unschedulable=true kubelet, the other one is a regular node. This is running on CoreOS on AWS, with Docker 1.10.

**Comment by therc** [comment]
This is how to reproduce. Something to do with ports defined *and* hostNetwork. You can guess which ones crash loop and which don't:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ds-crash
spec:
  template:
    metadata:
      labels:
        app: ds-crash
      name: ds-crash
    spec:
      hostNetwork: true
      containers:
      - image: busybox
        imagePullPolicy: Always
        command:
          - sleep
          - "3600"
        name: busybox
        ports:
          - containerPort: 9000
            name: foo
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ds-non-crash
spec:
  template:
    metadata:
      labels:
        app: ds-non-crash
      name: ds-non-crash
    spec:
      containers:
      - image: busybox
        imagePullPolicy: Always
        command:
          - sleep
          - "3600"
        name: busybox
        ports:
          - containerPort: 9001
            name: foo
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ds-non-crash-too
spec:
  template:
    metadata:
      labels:
        app: ds-non-crash-too
      name: ds-non-crash-too
    spec:
      hostNetwork: true
      containers:
      - image: busybox
        imagePullPolicy: Always
        command:
          - sleep
          - "3600"
        name: busybox
```

I guess port definitions don't make any sense when using the host network? I was just trying to convert an existing setup away from pod networking.
