### ISSUE TITLE
What's the difference between type: NodePort & type: LoadBalance

### ISSUE THREAD

**Issue by mysterytree** [kubernetes/kubernetes#22346]
```
apiVersion: v1
kind: Service
metadata:
  name: nginx 
  labels:
    name: nginx
spec:
  ports:
    # the port that this service should serve on
  - port: 80 
    targetPort: 80
    nodePort: 30000 
  selector:
    name: nginx
  type: NodePort 
```
```
apiVersion: v1
kind: Service
metadata:
  name: nginx 
  labels:
    name: nginx
spec:
  ports:
    # the port that this service should serve on
  - port: 80 
    targetPort: 80
    nodePort: 30000 
  selector:
    name: nginx
  type: LoadBalancer 
```
Two methods all support loadbalance .
