### ISSUE TITLE
invalid volume specification on reschedule

### ISSUE THREAD

**Issue by wallnerryan** [kubernetes/kubernetes#22436]
Kubernetes 1.2.0 and 1.1.1
Docker 1.10.2
Flocker 1.10.2

The spec below works fine on creation, but when I kill a node and the scheduler reschedules the POD the below error occurs

```
 14s   14s     1       {kubelet host3}       spec.containers{flocker-ghost}  Created Created with docker id 248205ed7016                                                  │··········································
  4s    4s      1       {kubelet host4}       spec.containers{flocker-ghost}  Failed  Failed to start with docker id f1a4a8c3a264 with error: API error (500): Invalid volu│··········································
me specification: ':/usr/share/nginx/html'
```

spec with volumes
```
        volumeMounts:                                                                                                                                                                                
          # name must match the volume name below                                                                                                                                                    
          - name: nginxdata                                                                                                                                                                          
            mountPath: "/usr/share/nginx/html"                                                                                                                                                       
      volumes:                                                                                                                                                                                       
        - name: nginxdata                                                                                                                                                                            
          flocker:                                                                                                                                                                                  
            datasetName: testvol-poc
```

**Comment by thockin** [comment]
This suggests to me that the flocker driver is not producing a path on the node that can be mounted.  If it returns "", we would pass ":/usr/share/nginx/html" to docker and get something like that error.

@lukemarsden @agonzalezro who can we bother when it comes to potential bugs in the flocker driver?

**Comment by wallnerryan** [comment]
@thockin (desclaimer, i work at clusterhq) I can bother the right people but I want to make sure of a few things first. Odd thing is I've run this exact use-case before with it working no problem with kubernetes 1.1.1. It might be an issue with docker version being used?

**Comment by wallnerryan** [comment]
@thockin 
My theory was correct, reverting to docker 1.9.1 this works fine

**Comment by wallnerryan** [comment]
so I tested it with docker 1.9.1 and the ":/usr/share/nginx/html" error went away but received 
```
 Failed  Failed to start with docker id 526789635ce7 with error: API error (500): Cannot start│·········································· container 526789635ce70939d768a49541761a1e6c8d468506e37a22f8ab5f5535d0d41d: Unable to setup mount point, neither source nor volume defined
```

when the scheduler rescheduled the node

**Comment by wallnerryan** [comment]
for example: this blog ( https://clusterhq.com/2015/12/22/ha-demo-kubernetes-flocker/ ) demos kubernetes 1.1.1 doing the same exact usecase without issue. So trying to find what the difference is.

**Comment by thockin** [comment]
Yeah, all those errors are coming from Docker.  We can/should probably
sanity check volumes more in Kubelet before passing to Docker - as you are
tracking this bug, maybe you could help on that? :D

**Comment by wallnerryan** [comment]
@thockin happy to help. Just for clarification, your suggesting that the kubelet may need some changes/optimizations for sanity checking volumes before passing to docker api?

**Comment by thockin** [comment]
yeah.  For example, if a volume driver's GetPath() ever returns "", Kubelet
should fail the pod and blame the driver, rather than pass that through to
docker.

**Comment by wallnerryan** [comment]
Right, okay, I will dig into this and hopefully have some more info. Thanks.

**Comment by mattbates** [comment]
@thockin I'm looking after the Flocker driver - will dig into this. Thanks @wallnerryan for the report.

**Comment by wallnerryan** [comment]
@mattbates I just verified this same use case running and working on a different set up. heres the breakdown.

```
root@ip-172-20-0-195:/home/ubuntu# kubelet --version=true
Kubernetes v1.1.7

root@ip-172-20-0-195:/home/ubuntu# docker version
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   79edcc5
 Built:        Sat Feb 13 00:12:47 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   79edcc5
 Built:        Sat Feb 13 00:12:47 2016
 OS/Arch:      linux/amd64
 Experimental: true

root@ip-172-20-0-195:/home/ubuntu# flocker-diagnostics --version
1.10.2

root@ip-172-20-0-195:/home/ubuntu# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

root@ip-172-20-0-195:/home/ubuntu# uname -a
Linux ip-172-20-0-195 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

The setup with the error above

OS: `CentOS 7`
Tried: `Kubernetes/Kubelet 1.2.0 and 1.1.1`
Tried: `Docker 1.8.7, Docker 1.10.2,  Docker 1.9.1` (docker 1.8.7 1.9.1 has the `API Error` while 1.10.2 had the `Invalid volume specification`
Flocker: `Flocker 1.10.2`

**Comment by PradeepSingh1988** [comment]
@wallnerryan , i am getting same problem on below versions:
`kubernetes : 1.1.4
 docker: 1.10.3
 flocker: 1.10.2
os: ubuntu 14.04 trusty LTS`
 i am using `https://get.docker.com/|sh` to install docker, how did you install  the `1.11.0-dev` version of the docker?
Is this problem related to the docker version or flocker plugin?

**Comment by wallnerryan** [comment]
@PradeepSingh1988, the issues with `invalid volume specification` i have not seen since i opened this. The `unable to set mountpoint` and `cant find volume` issues have been fixed using kubernetes greater than v1.2.0-beta.0. Heres the explanation below.

I was using kubernetes v1.1 and v1.2.0.6-alpha1 (v1.2.0alpha6 on github), these versions of kubernetes use flocker-go at revision 3f33ece70f6571f0ec45bfae2f243ab11fab6c52 according to `Godeps`

Here is the partial Godeps.json for these versions
```
{
 "ImportPath": "k8s.io/kubernetes",
 "GoVersion": "go1.5.1",
 "Packages": [
"./..."
 ],
 "Deps": [
...
{
"ImportPath": "github.com/ClusterHQ/flocker-go",
"Rev": "3f33ece70f6571f0ec45bfae2f243ab11fab6c52"
},
...
```

Flocker-go at the above revision `3f33ece70f6571f0ec45bfae2f243ab11fab6c52` doesnt include https://github.com/ClusterHQ/flocker-go/commit/c7e1cecd4fa003416d39d74ff365f22a6dc24a67 because its the revision directly before it :) And that commit fixes finding deleted datasets / mountpoint issues AFAICT.

So, using a version of Kubernetes below https://github.com/kubernetes/kubernetes/releases/tag/v1.2.0-beta.0 will likely see mountpoint issues with flocker during migrations etc.

The `invalid volume specification: ':/usr/share/nginx/html'` issues i have not seen again, so if this is what your seeing, I would be interested finding more out.

R

**Comment by PradeepSingh1988** [comment]
I am seeing `invalid volume specification: ':/var/jenkins_home'` ,.
I have 3 node cluster with 2 minions and one master.
i created volume using flockerctl on openstack cinder and attached to minion1.
i created jenkins pod and k8 scheduled it to minion1, and flocker volume is attached and every thing is fine.

now i executed below command so that k8 does not schedule the pod on minion1 in future.
`kubectl patch nodes minion1 -p '{"spec": {"unschedulable": true}}'`

now i killed the pod, k8 scheduled it on minion2 but it could not start it due to 
 `invalid volume specification: ':/var/jenkins_home'`

am i doing something wrong?
i will test it again by stopping the minion1 like real failure scenario and let you know the result.

**Comment by wallnerryan** [comment]
Hmm, no, this seems to be the original problem I ran into. @mattbates since this surfaced again, we should look into if its a kubelet/k8s thing or a flocker thing. Looks more like a kubelet/k8s issue to me.

**Comment by thockin** [comment]
I'm going to make a new issue to cover the systemic error reporting, but it sounds like a driver is still returning ""

**Comment by mattbates** [comment]
Yes, this absolutely needs more investigation. Thanks @thockin. we'll pick this up and look to find the root cause over the next week.

**Comment by PradeepSingh1988** [comment]
JFI: flocker is able to attache the volume to the node2 when node1 goes off.
If you guys need any logs please let me know.

**Comment by PradeepSingh1988** [comment]
@wallnerryan,
Hey, i updated my setup to `kubernetes : 1.2.0 docker: 1.10.3 flocker: 1.10.2 os: ubuntu 14.04 trusty LTS`
Basically i updated my k8 only.
I am using openstack as flocker backend.

Below scenarios are working fine:

1. I can create the POD and volume from openstack is mounting correctly in container.

2. When i power off one of my node, POD moves to another node, and volume is mounted successfully.

3. I deleted the POD using `kubectl delete pod <podname>`, and k8 created my POD again, since i have replication controller with replica 1. Volume is mounted successfully inside the container.

Below scenario is failing:

1. I killed the container using `docker kill <containerid>` and k8 is not able to create my POD.
Below error is coming:

`49s           26s             2       {kubelet 10.0.24.5}     spec.containers{dockerjenkins}  Warning         Failed                  Failed to create docker container with error: API error (500): Invalid bind mount spec ":/var/jenkins_home": volumeinvalid: Invalid volume specification: ':/var/jenkins_home'`

`  49s   26s     2       {kubelet 10.0.24.5}             Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "dockerjenkins" with RunContainerError: "runContainer: API error (500): Invalid bind mount spec \":/var/jenkins_home\": volumeinvalid: Invalid volume specification: ':/var/jenkins_home'\n"`

**Comment by wallnerryan** [comment]
@PradeepSingh1988 Thanks! @mattbates and I are looking into this one, it seems this surfaces in two ways which could be seperate errors, but seem related based on initial investigations.

* When kubernetes shows error message of `Invalid bind mount spec ":/some/mount"`
* When kubernetes shows error message of  `Unable to setup mount point, neither source nor volume defined`

In both cases, it looks like the wrong path is being handed to Docker as these errors seem like Docker messages as @thockin suggested. Thanks for reporting.

**Comment by PradeepSingh1988** [comment]
@wallnerryan , yes indeed this error is coming from docker, it seems errors are originating from below points, but not sure.

https://github.com/docker/docker/blob/master/runconfig/config.go#L56
https://github.com/docker/docker/blob/bump_v1.10.3/volume/volume_unix.go#L42

**Comment by sindrepm** [comment]
Regarding the error:

`Unable to setup mount point, neither source nor volume defined`

At least in my case, the reason for this was that my Docker image had a VOLUME definition in the Dockerfile with the same path as the `mountPath` given in the POD manifest.

For example, the official [MySQL image](https://hub.docker.com/_/mysql/) includes the following in the [Dockerfile](https://github.com/docker-library/mysql/blob/5b1a6a2b50efceac44579df0936facfee654a805/5.6/Dockerfile#L40):

`VOLUME /var/lib/mysql`

If I try to specify a Flocker volume at the same mountPath in the POD manifest, I get the error.

I am not sure if this is specific to the Flocker volume driver or if other type of volumes can be affected as well.

**Comment by sindrepm** [comment]
After further research I am not so sure the VOLUME declaration in the Dockerfile is causing the problem after all. I tried to build my own MySQL (Percona Galera) image from debian:jessie (not inheriting the official mysql image) to make sure it did not include the volume instruction. Yet, I get the same error when trying to mount a Flocker volume at `/var/lib/mysql`. If I change the mount point in the POD manifest to something like `/var/lib/mysql2` it works fine.

Here is a [link](http://hastebin.com/uyiyevojec.vbs) to my Dockerfile.

Is the Flocker volume failing because the Dockerfile tries to access the same path? (/var/lib/mysql)

**Comment by sindrepm** [comment]
I have also ran into this issue lately and as far as I can tell, the problem happens when the container (POD) fails to start for some reason. When the container is restarted, the Flocker mount is lost and k8s is reverting to `Driver = "local"` with `Source = ""`.

I have created a minimalistic POD to reproduce it.

Manifest:

```
apiVersion: v1
kind: Pod
metadata:
  name: epicfail
spec:
  containers:
    - name: epicfail
      image: hello-world:latest
      command:
        - "fail"
      volumeMounts:
        - name: my-vol
          mountPath: "/my-vol"
  volumes:
    - name: my-vol
      flocker:
        datasetName: flocker-vol
```

Note, above I am just passing a command "fail" to the container, which I know will fail (no pun intended..) in order to reproduce the issue.

`kubectl describe po epicfail` shows that the container fails and tries to restart it:

```
Created container with docker id f4a8c5ad40aa
Failed to start container with docker id f4a8c5ad40aa with error: API error (500): Cannot start container f4a8c5ad40aa624412ece6c0d6db400679b4838279fddd3a58ed45a97252ba50: [8] System error: exec: "fail": executable file not found in $PATH

Created container with docker id 5772630ddb71
Failed to start container with docker id 5772630ddb71 with error: API error (500): Cannot start container 5772630ddb7146113477232c0e642f297e160f1b5dad2a6df31a0f7eca84a003: Unable to setup mount point, neither source nor volume defined
```
Complete log: [epicfail-describe.txt](https://github.com/kubernetes/kubernetes/files/210081/epicfail-describe.txt)

Running `docker inspect` on the two container uuids reveals the issue:

`docker inspect f4a8c5ad40aa`

```
"Mounts": [
    ...
    {
        "Source": "/flocker/01271ba6-fb8f-4328-854e-b9fb6f34acab",
        "Destination": "/my-vol",
        "Mode": "",
        "RW": true
    },
    ...
]
```

`docker inspect 5772630ddb71`

```
"Mounts": [
    ...
    {
        "Source": "",
        "Destination": "/my-vol",
        "Driver": "local",
        "Mode": "",
        "RW": true
    },
    ...
]
```

Complete inspect output:

[inspect-f4a8c5ad40aa.txt](https://github.com/kubernetes/kubernetes/files/210097/inspect-f4a8c5ad40aa.txt)
[inspect-5772630ddb71.txt](https://github.com/kubernetes/kubernetes/files/210098/inspect-5772630ddb71.txt)

Hopefully this will help nail down where the bug is.
