### ISSUE TITLE
Two more problems with Deployments

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#22512]
We discovered these problems when I prepared for the demo.
The deployment config file I used:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-demo
  namespace: demos
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        demo: deployment
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sh
        - -c
        - while true; do echo "$(hostname) v1" > /data/index.html; sleep 60; done
        volumeMounts:
        - name: content
          mountPath: /data
      - name: nginx
        image: nginx
        volumeMounts:
          - name: content
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
      - name: content
```

The first problem occurs when I rolling update it with the following command:

```
cat deployment.yaml | sed 's/ v1/ v2/g' | kubectl --namespace=demos apply -f- --validate=false
```

**The problem is when the v1 rs scrolls down from 1 to 0, it gets scrolled up to 4 and then to 0.**

Then I use this command to roll back:

```
kubectl --namespace=demos rollout undo deployment deployment-demo
```

**The problem is the v1 rs get scrolled from 0 to 3 at once, and the v2 rs get scrolled from 3 to 0 at once.** @janetkuo and I had `watched` the events to confirm this was not caused by my bash scripts.

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.8.877+2cf3c7809eac09-dirty", GitCommit:"2cf3c7809eac093f4ccbabbfac4640abde41d6b1", GitTreeState:"dirty"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.8.916+2a4479fa601fb5-dirty", GitCommit:"2a4479fa601fb5ccc50676fa1f8c9e1f159ca558", GitTreeState:"dirty"}
```
