### ISSUE TITLE
Deleting a pending pod wedges it

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#22677]
Create this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: default
spec:
  nodeName: foo
  terminationGracePeriodSeconds: 30
  containers:
  - image: alpine:edge
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
```
Then delete it without --grace-period, it'll get stuck in Terminating for a lot longer than 30s (probably forever?).
