### ISSUE TITLE
Can't use service IP from inside the pod that backs the service

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#22717]
To reproduce, create a pod running a simple HTTP server and create a service for it:

web-test.yaml
```
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: web-test
  name: web-test
  namespace: default
spec:
  replicas: 1
  selector:
    app: web-test
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
      - image: python:2.7
        name: web-test
        terminationMessagePath: /dev/termination-log
        args:
        - python
        - -m
        - SimpleHTTPServer
        ports:
        - containerPort: 8000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: web-test
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: web-test
  sessionAffinity: None
  type: ClusterIP
```
```
kubectl create -f web-test.yaml
```

I was able to curl it from another pod:
```
$ kubectl exec -it another-pod -- curl -v web-test:8000
* Rebuilt URL to: web-test:8000/
* Hostname was NOT found in DNS cache
*   Trying 10.3.0.45...
* Connected to web-test (10.3.0.45) port 8000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: web-test:8000
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: SimpleHTTP/0.6 Python/2.7.11
< Date: Tue, 08 Mar 2016 22:43:06 GMT
< Content-type: text/html; charset=UTF-8
< Content-Length: 810
<
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html>
<title>Directory listing for /</title>
<body>
<h2>Directory listing for /</h2>
<hr>
<ul>
<li><a href=".dockerenv">.dockerenv</a>
<li><a href=".dockerinit">.dockerinit</a>
<li><a href="bin/">bin/</a>
<li><a href="boot/">boot/</a>
<li><a href="dev/">dev/</a>
<li><a href="etc/">etc/</a>
<li><a href="home/">home/</a>
<li><a href="lib/">lib/</a>
<li><a href="lib64/">lib64/</a>
<li><a href="media/">media/</a>
<li><a href="mnt/">mnt/</a>
<li><a href="opt/">opt/</a>
<li><a href="proc/">proc/</a>
<li><a href="root/">root/</a>
<li><a href="run/">run/</a>
<li><a href="sbin/">sbin/</a>
<li><a href="srv/">srv/</a>
<li><a href="sys/">sys/</a>
<li><a href="tmp/">tmp/</a>
<li><a href="usr/">usr/</a>
<li><a href="var/">var/</a>
</ul>
<hr>
</body>
</html>
* Closing connection 0
```

But curling from the web-test pod itself fails:
```
$ kubectl exec -it web-test-ts14s -- curl -v web-test:8000
* Rebuilt URL to: web-test:8000/
* Hostname was NOT found in DNS cache
*   Trying 10.3.0.45...
```

We are using v1.2.0-alpha.8 for the master components and kubelet is on v1.2.0-alpha.6.

EDIT: correcting the versions we are using.
