### ISSUE TITLE
AWS: Dynamic volumes should have EC2 tags

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#22792]
We should tag EBS volumes created by k8s with our tags, just like we (should) tag everything else we create/own.

**Comment by paralin** [comment]
Is there any documentation yet on automatic EBS volume creation?

**Comment by justinsb** [comment]
@paralin from a user perspective, they are not AWS specific.  That said, I don't know that we have clear user-facing docs.  Here's an example though, from my (very) WIP Ubernetes-Lite docs:

https://raw.githubusercontent.com/justinsb/kubernetes/docs_ubernetes_lite/docs/getting-started-guides/ubernetes-lite.md

...

```
kubectl create -f - <<EOF
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "claim1",
    "annotations": {
        "volume.alpha.kubernetes.io/storage-class": "foo"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "5Gi"
      }
    }
  }
}
EOF
```

The PV is also tagged with the zone & region is is in (us-central1-a):

```
> kubectl get pv
NAME           LABELS                                                                                                        CAPACITY   ACCESSMODES   STATUS      CLAIM     REASON    AGE
my-data-disk   failure-domain.alpha.kubernetes.io/region=us-central1,failure-domain.alpha.kubernetes.io/zone=us-central1-a   5Gi        RWO           Available                       5s
```

Create a pod that uses the PVC:

```
kubectl create -f - <<EOF
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: claim1
EOF
```
