### ISSUE TITLE
kubectl get ingress should print consistently formatted columns

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#22837]
We should show a nicely formatted map, with tls and ports. This 50% works. Today we have:
```
NAME      RULE          BACKEND   ADDRESS          AGE
echomap   -                       130.211.10.121   5h
          foo.bar.com   
          /foo          echoheadersx:80
          bar.baz.com   
          /bar          echoheadersy:80
          /foo          echoheadersx:80

```
Which works well enough, but printing a single Ingress involves hand managing tabs and newlines till the entire Ingress is printed, i.e: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L1029

So when we start mixing different Ingress types, we get jarring output:
```
NAME                   RULE          BACKEND      ADDRESS   AGE
another-no-rules-map   -             haproxy:80             39s
                                     
                                     echoheadersy:80
echomap                -                       130.211.10.121   5h
                       foo.bar.com   
                       /foo          echoheadersx:80
                       bar.baz.com   
                       /bar          echoheadersy:80
                       /foo          echoheadersx:80

```

This is because the columns are formatted per the top ingress and don't match the bottom one. The tabbed writer used by kubectl to align columns gets confused on the whole.

**Comment by AdoHe** [comment]
@bprashanth you can assign this to me, will fix this next-candidate.

**Comment by bprashanth** [comment]
@AdoHe thanks!

**Comment by bprashanth** [comment]
Sounds like we should keep it to a single line (https://github.com/kubernetes/kubernetes/pull/22772/files#r55788741) and move everything else to describe. Well, that makes this bug easier.

**Comment by AdoHe** [comment]
@bprashanth yeah, we will move this to a single line, this is the principle.

**Comment by roberthbailey** [comment]
@AdoHe was this finished for 1.3?

**Comment by AdoHe** [comment]
@roberthbailey the code is already finished on my local branch. I will open a PR.

**Comment by AdoHe** [comment]
@bgrant0607 @bprashanth what do you think if print ingress like this:
```
[tony@localhost kubernetes]$ cluster/kubectl.sh get ingress --output=wide
NAME      RULE      BACKEND   ADDRESS   AGE       RULES
test      -                             3s        foo.bar.com/foo->s1:80,foo.bar.com/bar->s2:80,zoo.bar.com/foo->s1:80,zoo.bar.com/bar->s2:80
```
Also the original resource is:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: s1
          servicePort: 80
      - path: /bar
        backend:
          serviceName: s2
          servicePort: 80
  - host: zoo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: s1
          servicePort: 80
      - path: /bar
        backend:
          serviceName: s2
          servicePort: 80
```
