### ISSUE TITLE
Provide a Docker Image Volume

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#22894]
There are applications which need to have a shared directory between two containers in a pod. For example legacy PHP applications that share the application folder between Nginx and PHP-FPM. 

For various reasons Kubernetes doesn't have a builtin way to share existing directories between containers. That means currently on Pod start one of the containers has to copy the application files into a shared `emptyDir` and writing a readiness probe to wait for this copying to finish. This is a tedious process and introduces a lot of complexity.

This process could be simplified by a Docker volume not unlike the `gitRepo`, which mounts or copies a directory from an existing Docker image into the Pod for all the containers to share.

**Comment by ncdc** [comment]
This sounds like it might be covered by #831 and/or #15899 

cc @kubernetes/rh-storage @kubernetes/sig-storage

**Comment by rootfs** [comment]
@hanikesn I think your use case can be solved by using [Kubernetes volumes](http://kubernetes.io/docs/user-guide/volumes/). Kubernetes volume supports multiple storage assets, NFS, iSCSI, Ceph, Glusterfs, just to name a few. The storage is bind mounted to the containers and they can share and persist data.

**Comment by hanikesn** [comment]
@rootfs I don't want to share data between different pods or persist it, so I think the existing Volume providers are not a good fit.

**Comment by rootfs** [comment]
@hanikesn  Would the following simplifed pods work for your use case?

As long as `/path/to/your/shared/directory` are the same in two pods and the your volume type are the same, you should be able to share either your binary or your data between pods.

php pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: php
spec: 
  containers: 
    - image: php
      volumeMounts:
        - name: shared_directory
          mountPath: /path/to/your/shared/directory
  volumes:
    - name: shared_directory
      # your volume spec goes here
```
ngix Pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: ngix
spec: 
  containers: 
    - image: ngix
      volumeMounts:
        - name: shared_directory
          mountPath: /path/to/your/shared/directory
  volumes:
    - name: shared_directory
      # your volume spec goes here
```
