### ISSUE TITLE
Some Replication Controllers fail with lifecycle hooks 

### ISSUE THREAD

**Issue by rwillard** [kubernetes/kubernetes#22947]
Starting with a working cluster, wanted to add lifecycle hooks for slack integration. Half of the RC work correctly, and I can see the messages in slack. The other half fail to build properly in kubernetes at all now. When I comment out the lifecycle section for the ones that fail, the build works fine. I'm really at a loss, and there isn't any good error reporting come from kubernetes about this issue. Only reason I knew that this was what was breaking it is because it was working without it. Here's one of the offending rc that doesn't work.
```yaml
kind: 'ReplicationController'
apiVersion: 'v1'
metadata:
   name: 'registry-app'
   labels:
      name: 'registry'
      role: 'app'
spec:
   replicas: 3
   selector:
      name: 'registry'
      role: 'app'
   template:
      metadata:
         name: 'registry-app'
         labels:
            name: 'registry'
            role: 'app'
      spec:
         containers:
         -
            name: 'registry'
            image: 'xxx'
            imagePullPolicy: 'Always'
            lifecycle:
               postStart:
                  exec: 
                     command: 
                     - 'curl'
                     - '-X'
                     - 'POST'
                     - '-H'
                     - 'Content-type: application/json'
                     - '--data'
                     - '{ "text": "Registry *STARTED*", "username": "Registry", "icon_emoji": ":megaman:"}'
                     - 'https://hooks.slack.com/services/xxx'
               preStop:
                  exec:
                     command: 
                     - 'curl'
                     - '-X'
                     - 'POST'
                     - '-H'
                     - 'Content-type: application/json'
                     - '--data'
                     - '{ "text": "Registry *STOPPED*", "username": "Registry", "icon_emoji": ":megaman:"}'
                     - 'https://hooks.slack.com/services/xxx'
            env:
            -
               name: 'REGISTRY_HTTP_SECRET'
               value: 'xxx'
            ports:
            -
               name: 'reg-http'
               containerPort: 5000
         imagePullSecrets:
         -
            name: 'dockersecret'
```

**Comment by JoelBCarter** [comment]
Was this ever resolved? Could you post a YAML showing the fix if it was just escaping/syntax issues? I'm trying to do _exactly_ the same thing.

**Comment by rwillard** [comment]
I never resolved it, but it became a non-issue anyway. With HPA pods are going up and down frequently, so it would have just become spam.

**Comment by JoelBCarter** [comment]
I can see Slack being too busy.  If you're ever wanting to do this, I worked around it by:

- creating a secret from files that contained the curl commands
- mounting the secret as a volume
- executing the secret file in the lifecycle hook

Something like this would do it for you

```Shell
kubectl create secret generic slack-integrations --from-file=post-start-slack-webhook.sh --from-file=pre-stop-slack-webhook.sh
```

And then in your YAML file

```YAML
apiVersion: 'extensions/v1beta1'
kind: 'Deployment'
metadata:
  name: 'registry-app'
spec:
  replicas: 3
  selector:
    matchLabels:
      name: 'registry'
      role: 'app'
  template:
    metadata:
      labels:
        name: 'registry'
        role: 'app'
    spec:
      containers:
      - name: 'registry'
        image: 'xxx'
        volumeMounts:
        - name: 'slack-integrations'
          mountPath: '/etc/slack'
          readOnly: true
        lifecycle:
          postStart:
            exec:
              command:
                - '/bin/bash'
                - '/etc/slack/post-start-slack-webhook.sh'
          preStop:
            exec:
              command:
                - '/bin/bash'
                - '/etc/slack/pre-stop-slack-webhook.sh'
      volumes:
      - name: 'slack-integrations'
        secret:
          secretName: 'slack-integrations'
```
