### ISSUE TITLE
DaemonSet doesn't run in all nodes

### ISSUE THREAD

**Issue by Calpicow** [kubernetes/kubernetes#23013]
Using v1.2.0-beta.1. Deployed a DaemonSet with no node selector, but it's not running in all of them.

The two that are running are the ones with SchedulingDisabled.

```
$ kubectl get nodes
NAME            STATUS                     AGE
100.64.32.234   Ready                      8d
100.64.32.71    Ready,SchedulingDisabled   5m
100.64.33.77    Ready,SchedulingDisabled   19m
100.64.33.82    Ready                      2d
```

```
$ kubectl describe daemonset kube-proxy
Name:       kube-proxy
Image(s):   calpicow/hyperkube:v1.2.0-beta.1-custom
Selector:   name in (kube-proxy)
Node-Selector:  <none>
Labels:     name=kube-proxy
Desired Number of Nodes Scheduled: 2
Current Number of Nodes Scheduled: 2
Number of Nodes Misscheduled: 0
Pods Status:    2 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

**Comment by mikedanese** [comment]
can I see:
```
kubectl get no,ds,po -o json
```

Do the nodes have enough resource? Are their host port conflicts?

**Comment by Calpicow** [comment]
Output at https://gist.github.com/Calpicow/c25057f849061deb5f2e. `cmd` and `env` parameters removed to avoid potential security issues.

**Comment by vsimon** [comment]
Also seeing this issue.

**Comment by lacion** [comment]
i am experiencing the same issue with 10 nodes.

running latest releases kubernetes 1.2.0

`kubectl get nodes
NAME                     STATUS    AGE
node1    Ready     2d
node10  Ready     2d
node2    Ready     2d
node3    Ready     2d
node4    Ready     2d
node5    Ready     2d
node6    Ready     2d
node7    Ready     2d
node8    Ready     2d
node9    Ready     2d`

`Name:		fluentd
Image(s):	dronedeploy/fluentd:v0.1.0
Selector:	app=fluentd
Node-Selector:	<none>
Labels:		name=fluentd
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Misscheduled: 0
Pods Status:	3 Running / 0 Waiting / 0 Succeeded / 0 Failed`

this is the only daemon set i have running

**Comment by mikedanese** [comment]
Do the nodes have capacity, are you using host ports?

**Comment by lacion** [comment]
2 of the nodes *DO NOT* have capacities, all the other do. i am not using host ports

will it be possible to reserve resource for daemonsets?
will they get created in the nodes with no capacity when there is?

**Comment by lacion** [comment]
kube version across the cluster is 1.2 as well as my local kubectl version

i started using --kube-reserved=cpu=1000m,memory=1G and launched a DS for fluentd
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      dnsPolicy: "ClusterFirst"
      restartPolicy: "Always"
      containers:
      - name: fluentd
        image: dronedeploy/fluentd:v0.1.0
        imagePullPolicy: "Always"
        env:
        - name: KUBE_API
          value: http://kube-master
        - name: ES_HOST
          value: http://elasticsearch
        - name: ES_PORT
          value: "9200"
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: "elasticsearch-found-logs"
              key: user
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "elasticsearch-found-logs"
              key: password
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: "aws-s3"
              key: key
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: "aws-s3"
              key: secret
        - name: S3_BUCKET
          value: drone-kube-logs
        - name: S3_REGION
          value: us-east-1
        - name: S3_TIMESLICE
          value: 10m
        volumeMounts:
          - mountPath: /var/log
            name: varlog
          - mountPath: /var/lib/docker/containers
            name: containers
      volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: containers
```

i  then launched 3 pods  into each node that were consuming about 80% ram and about 70% cpu, the DS staying there and all the logs were in ES.

today i added second DS for sensu, only the fluentd DS pods, heapster and dashboard pods were running when i added this second DS

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sensu-client
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: sensu-client
    spec:
      dnsPolicy: "ClusterFirst"
      restartPolicy: "Always"
      hostNetwork: true
      containers:
      - name: sensu-client
        image: dronedeploy/sensu-client:v0.1.0
        imagePullPolicy: "Always"
        securityContext:
          privileged: true
        env:
        - name: CERT_SECRET
          value: "true"
        - name: CLIENT_SUBSCRIPTIONS
          value: kubenode
        - name: RABBITMQ_PORT
          value: "5671"
        - name: RABBITMQ_HOST
          value: xx.xx.xx.xx
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: "sensu-credentials"
              key: user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "sensu-credentials"
              key: password
        - name: RABBITMQ_VHOST
          value: sensu
        - name: SENSU_SSL_KEY
          valueFrom:
            secretKeyRef:
              name: "sensu-ssl"
              key: key
        - name: SENSU_SSL_CERT
          valueFrom:
            secretKeyRef:
              name: "sensu-ssl"
              key: cert
```

the result was all the pods being created and everything seemed to work, them i proceeded to create again 3 pods  into each node that were consuming about 80% ram and about 70% cpu the result of this was that all the DS pods were killed for both DS

```
kubectl describe ds sensu-client --namespace=kube-system
Name:		sensu-client
Image(s):	dronedeploy/sensu-client:latest
Selector:	app=sensu-client
Node-Selector:	<none>
Labels:		app=sensu-client
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Misscheduled: 0
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Events:
  FirstSeen	LastSeen	Count	From		SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----		-------------	--------	------			-------
  37m		37m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-gk52x
  37m		37m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-gk52x
  37m		37m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-gk52x
  36m		36m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-hd5ms
  36m		36m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-hd5ms
  35m		35m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-hd5ms
  34m		34m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-n0ue6
  34m		34m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-n0ue6
  34m		34m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-n0ue6
  32m		32m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-8255q
  32m		32m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-8255q
  32m		32m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-8255q
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-2x4my
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-2x4my
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-2x4my
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-nienw
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-2y90n
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-2y90n
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-nienw
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-nienw
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-2y90n
  29m		29m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-4jfl1
  29m		29m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-4jfl1
  29m		29m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-4jfl1
  29m		29m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-34lvc
  29m		29m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-34lvc
  29m		29m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: sensu-client-34lvc
```

```
kubectl describe ds fluentd --namespace=kube-system
Name:		fluentd
Image(s):	dronedeploy/fluentd:latest
Selector:	app=fluentd
Node-Selector:	<none>
Labels:		app=fluentd
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Misscheduled: 0
Pods Status:	0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Events:
  FirstSeen	LastSeen	Count	From		SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----		-------------	--------	------			-------
  38m		38m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-3qg9z
  38m		38m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-3qg9z
  38m		38m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-3qg9z
  36m		36m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-08fnk
  36m		36m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-08fnk
  36m		36m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-08fnk
  35m		35m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-cv096
  35m		35m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-cv096
  35m		35m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-cv096
  33m		33m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-6ysry
  33m		33m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-6ysry
  33m		33m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-6ysry
  32m		32m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-01gb5
  32m		32m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-01gb5
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-01gb5
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-eii4s
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-eii4s
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-eii4s
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-y27g1
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-y27g1
  31m		31m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-y27g1
  30m		30m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-j21r9
  30m		30m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-j21r9
  30m		30m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-j21r9
  30m		30m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-avpi7
  30m		30m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-avpi7
  29m		29m		1	{daemon-set }			Normal		SuccessfulDelete	Deleted pod: fluentd-avpi7
```
