### ISSUE TITLE
[Proposal] add support for labels in rolling-update

### ISSUE THREAD

**Issue by mrezaei00** [kubernetes/kubernetes#23055]
**Background:**
In an effort to introduce personalities and roles for Replication Controllers, there exists N number of RCs that run the same image but labeled to show their role. E.g.
- RC 1:
  ```
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: my-application
          group: some-group-1
          role: my-app-role-1
  ```

- RC 2:
  ```
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: my-application
          group: some-group-1
          role: my-app-role-2
  ```
... and so on, all the way to...

- RC N:
  ```
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: my-application
          group: some-group-2
          role: my-app-role-n
  ```

**Proposal:**
Introduce a new way to update all of these RCs with one rolling-update transaction (specific example for rolling updates using a new image):
```
kubectl rolling-update -l name=my-application --image=https://link/to/image/for/my/application:4.0.4
```
...and for more specific grouping, this would be:
```
kubectl rolling-update -l name="my-application,some-group-1" --image=https://link/to/image/for/my/application:4.0.4
```
...and in a multi-container world, it would be:
```
kubectl rolling-update -l name="my-application,some-group-1" --container=container-1 --image=https://link/to/image/for/my/application:4.0.4
```
