### ISSUE TITLE
Proposal: Mount each secret as a file, not as a directory 

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#23237]
On the following example, the user is setting up the mount path as `/etc/foo` which will create the directory `/etc/foo`.

I was hopping if it would be possible instead the `/host_directory/foo` to be the mount point of `/etc/foo`, it would be created the mounting point `/host_directory/foo/mysecret` and that one would be mounted in `/etc/foo/mysecret`.

This would allow a user to be able to mount specific secrets files, for example, `/home/user/.ssh/id_rsa` without deleting the content of `/home/user/.ssh` inside the container.

```json
{
 "apiVersion": "v1",
 "kind": "Pod",
  "metadata": {
    "name": "mypod",
    "namespace": "myns"
  },
  "spec": {
    "containers": [{
      "name": "mypod",
      "image": "redis",
      "volumeMounts": [{
        "name": "foo",
        "mountPath": "/etc/foo",
        "readOnly": true
      }]
    }],
    "volumes": [{
      "name": "foo",
      "secret": {
        "secretName": "mysecret"
      }
    }]
  }
}
```

**Comment by thockin** [comment]
Dup of #19764

It's a great idea, it's just technically hard.

**Comment by jkodroff** [comment]
FYI, per [this thread](https://github.com/kubernetes/kubernetes/issues/19764#issuecomment-269879587), the workaround is to mount the secret to a dir elsewhere and copy the file or use a symlink in a `postStart` hook.

Example:
```yaml
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp /etc/secret-gitconfig/gitconfig /home/atlantis/.gitconfig && chown atlantis /home/atlantis/.gitconfig"]
```
