### ISSUE TITLE
Rolling-updates timing out since v1.2.0

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#23276]
Rolling-update tasks which worked since v1.0 are now getting stuck mid-way since v1.2

I'm rolling a multi-container pod from `sidekiq-rollout` to `sidekiq`. The target number of replicas is 4. The first 2 pods are rolled correctly, but the job hangs and times out (5min) after the first 2 iterations:

```
NAME              DESIRED   CURRENT   AGE
sidekiq           2         2         56s
sidekiq-rollout   2         3         57s
```

```
NAME            READY     STATUS    RESTARTS   AGE       APP                COMPONENT   DEPLOYMENT
sidekiq-3mni0   3/3       Running   0          25m       fl-backend-rails   sidekiq     82        <- new
sidekiq-8glbk   3/3       Running   0          37m       fl-backend-rails   sidekiq     81
sidekiq-fe1r3   3/3       Running   0          37m       fl-backend-rails   sidekiq     81
sidekiq-r7c06   3/3       Running   0          25m       fl-backend-rails   sidekiq     82        <- new
```

Controller manager logs:

```
Mar 21 12:31:42 node01 kube-controller-manager[8697]: I0321 12:31:42.687964    8697 replication_controller.go:510] Replication Controller has been deleted bodyweight-api/sidekiq
Mar 21 12:31:46 node01 kube-controller-manager[8697]: I0321 12:31:46.191549    8697 replication_controller.go:434] Too few "bodyweight-api"/"sidekiq" replicas, need 1, creating 1
Mar 21 12:31:46 node01 kube-controller-manager[8697]: I0321 12:31:46.215334    8697 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"bodyweight-api", Name:"sidekiq", UID:"de5b3478-ef60-11e5-b33a-0a59d1e77755", APIVersion:"v1", ResourceVersion:"114094222", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: sidekiq-r7c06
Mar 21 12:32:01 node01 kube-controller-manager[8697]: I0321 12:32:01.725368    8697 replication_controller.go:451] Too many "bodyweight-api"/"sidekiq-rollout" replicas, need 3, deleting 1
Mar 21 12:32:01 node01 kube-controller-manager[8697]: I0321 12:32:01.772642    8697 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"bodyweight-api", Name:"sidekiq-rollout", UID:"ddfa58e1-ef60-11e5-b33a-0a59d1e77755", APIVersion:"v1", ResourceVersion:"114094394", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: sidekiq-2wjbr
Mar 21 12:32:07 node01 kube-controller-manager[8697]: I0321 12:32:07.757771    8697 replication_controller.go:434] Too few "bodyweight-api"/"sidekiq" replicas, need 2, creating 1
Mar 21 12:32:07 node01 kube-controller-manager[8697]: I0321 12:32:07.809994    8697 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"bodyweight-api", Name:"sidekiq", UID:"de5b3478-ef60-11e5-b33a-0a59d1e77755", APIVersion:"v1", ResourceVersion:"114094461", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: sidekiq-3mni0
Mar 21 12:37:16 node01 kube-controller-manager[8697]: I0321 12:37:16.324724    8697 replication_controller.go:451] Too many "bodyweight-api"/"sidekiq-rollout" replicas, need 2, deleting 1
Mar 21 12:37:16 node01 kube-controller-manager[8697]: E0321 12:37:16.327923    8697 controller_utils.go:300] Clobbering existing delete keys: map[bodyweight-api/sidekiq-2wjbr:{}]
Mar 21 12:37:16 node01 kube-controller-manager[8697]: I0321 12:37:16.350471    8697 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"bodyweight-api", Name:"sidekiq-rollout", UID:"ddfa58e1-ef60-11e5-b33a-0a59d1e77755", APIVersion:"v1", ResourceVersion:"114094650", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: sidekiq-bfob2
```

Note the time it took to scale down `sidekiq-rollout` on the second iteration, although all the pods marked _new_ transitioned to a `Running` state in less than 10sec.
## 

**edit**

My RC selector matches 3 labels. After the timeout the 2 RCs look like:

```
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: sidekiq-rollout
  spec:
    replicas: 2
    selector:
      app: fl-backend-rails
      component: sidekiq
      deployment: "81"

- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: sidekiq
  spec:
    replicas: 2
    selector:
      app: fl-backend-rails
      component: sidekiq
      deployment: "82"
```

**Comment by nikhiljindal** [comment]
@antoineco Can you please share the exact command you are running that leads to timeout?

cc @janetkuo

**Comment by antoineco** [comment]
I first get the current RC definition in YAML format, replace the image and `deployment` label, and finally pass it to:

`kubectl --rolling-update --update-period=0s api-rollout -f -`

**Comment by janetkuo** [comment]
@antoineco Were you able to reproduce this consistently (i.e. this always fail)?

**Comment by antoineco** [comment]
Yes, 100%. It eventually goes through if I increase the timeout but I still have to wait a couple of minutes between each container.

I switched this deployment task to the `deployment` API with the Rolling-update strategy and it's extremely fast.

**Comment by janetkuo** [comment]
@antoineco Yes, we'd recommend using [`Deployment`](http://kubernetes.io/docs/user-guide/deployments/) since it's faster, declarative and has more features, such as you can rollback to a previous reversion even when the rollout/rolling-update is done. 

When you're using `kubectl rolling-update`, is it possible that there are overlapping resources fighting with `kubectl rolling-update`, such as replicasets, deployments, or replication controllers with the same label selector?

**Comment by antoineco** [comment]
@janetkuo labels are not conflicting. I have 2 other rcs in that namespace and each of them has a different `component` label (see my first comment).

Nothing has changed in that deployment procedure since Kubernetes v1.0, and v1.2 is the first version that seems to struggle.

I can post my rc definition here, just in case you can't reproduce with a generic 3-container pod.

**Comment by janetkuo** [comment]
Yes, posting the RC definition would help, since I cannot reproduce it on my end. Thanks!

**Comment by antoineco** [comment]
The following definition times out as described above. It resembles our real definition, minus a log forwarding container which I replaced by something generic like postgres.

```yaml
kind: ReplicationController
apiVersion: v1
metadata:
  name: issue23276
spec:
  replicas: 5
  template:
    metadata:
      labels:
        issue: "23276"
        deployment: "0"
    spec:
      containers:
      - name: rails
        image: nginx
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        - name: RAILS_ENV
          value: staging
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
        volumeMounts:
        - name: rails-secrets
          mountPath: /run/secrets/rails
          readOnly: true
        - name: rails-logs
          mountPath: /app/log
          readOnly: false
        - name: nginx-logs
          mountPath: /var/log/nginx
          readOnly: false
      - name: logrotate
        image: alpine
        imagePullPolicy: IfNotPresent
        command: ["crond","-f"]
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
        volumeMounts:
        - name: rails-logs
          mountPath: /var/log/containers/rails
          readOnly: false
        - name: nginx-logs
          mountPath: /var/log/containers/nginx
          readOnly: false
        - name: logrotate-d
          mountPath: /etc/logrotate.d
          readOnly: true
      volumes:
      - name: rails-secrets
        secret:
          secretName: rails
      - name: rails-logs
        emptyDir: {}
      - name: nginx-logs
        emptyDir: {}
      - name: logrotate-d
        secret:
          secretName: logrotate-d
```

Secrets:

```yaml
apiVersion: v1
data:
  database.yml: c3RhZ2luZzoKICBhZGFwdGVyOiBwb3N0Z3Jlc3FsCiAgZGF0YWJhc2U6IG15ZGIKICBlbmNvZGluZzogdW5pY29kZQogIGhvc3Q6IGxvY2FsaG9zdAogIHVzZXJuYW1lOiBzb21ldXNlcgogIHBhc3N3b3JkOiBzb21lcHcKICBwb29sOiA1CiAgdGltZW91dDogNTAwMAo=
  secrets.yml: c3RhZ2luZzoKICBzZWNyZXRfa2V5X2Jhc2U6IDFlM2EyNzE1NDMwZDAxYzJkNTk4YjE0MjhjZjEwNjIwMzJlMjgxY2Y3YzY2MmQzMWUyZmMzMTI0YjU5OTFlZjA3MTY2ZTAyZDE4M2M2ZGExMWQxMTcxZDE1MjRlOGM2NjEwNzRlMjU5MDVkYzQxNWY0MmM2NWUzMjg1ZWIxNzQ0Cg==
kind: Secret
metadata:
  name: rails
type: Opaque
---
apiVersion: v1
data:
  nginx: L3Zhci9sb2cvY29udGFpbmVycy9uZ2lueC8qLmxvZyB7CglzaXplIDEwTQoJbWlzc2luZ29rCglyb3RhdGUgMQoJbm9kYXRlZXh0Cglub2NvbXByZXNzCglub3RpZmVtcHR5Cglwb3N0cm90YXRlCgkJdG91Y2ggL3Zhci9sb2cvY29udGFpbmVycy9uZ2lueC9yb3RhdGUKCWVuZHNjcmlwdAp9Cg==
  rails: L3Zhci9sb2cvY29udGFpbmVycy9yYWlscy8qLmxvZyB7CglzaXplIDEwTQoJbWlzc2luZ29rCglyb3RhdGUgMQoJbm9kYXRlZXh0Cglub2NvbXByZXNzCglub3RpZmVtcHR5Cgljb3B5dHJ1bmNhdGUKfQo=
kind: Secret
metadata:
  name: logrotate-d
type: Opaque
```

Create the rc and secrets:

```
$ kubectl get rc,secret
NAME                  DESIRED                               CURRENT   AGE
issue23276            5                                     5         20s
NAME                  TYPE                                  DATA      AGE
default-token-lzsd4   kubernetes.io/service-account-token   3         164d
logrotate-d           Opaque                                2         20s
rails                 Opaque                                2         20s
```

Now delete the rc without killing the pods:
```
kubectl delete rc issue23276 --cascade=false
```

In the definition, rename the rc to anything else, and recreate it:

```
$ kubectl get rc,secret
NAME              DESIRED   CURRENT   AGE
issue23276-roll   5         5         11s
```

In the definition, rename the rc back to the original name "issue23276" and bump the "deployment" number in the label, then perform a rolling-update:

```
$ kubectl rolling-update issue23276-roll -f /tmp/rc.yml --update-period=0s
Created issue23276
Scaling up issue23276 from 0 to 5, scaling down issue23276-roll from 5 to 0 (keep 5 pods available, don't exceed 6 pods)
Scaling issue23276 up to 1
Scaling issue23276-roll down to 4
Scaling issue23276 up to 2
Scaling issue23276-roll down to 3
[then nothing]
```

It remains stuck in this state:

```
$ kubectl get pods -L deployment
NAME               READY     STATUS    RESTARTS   AGE       DEPLOYMENT
issue23276-0tojm   3/3       Running   0          2m        2
issue23276-2686n   3/3       Running   0          6m        1
issue23276-30h99   3/3       Running   0          2m        2
issue23276-609i5   3/3       Running   0          6m        1
issue23276-7p9xs   3/3       Running   0          6m        1
issue23276-yuu1p   3/3       Running   0          6m        1
```
