### ISSUE TITLE
Not able to start pod through yaml

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#23271]
Hi all,

I have been trying to run mysql pod using a yaml file. Here is my yaml file:

```
apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
    name: db
spec:
  containers:
    name: mysql
    image: "mysql"
    env:
      - name: MYSQL_USER
        value: test
      - name: MYSQL_PASSWORD
        value: test
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DB
        value: BucketList
    ports:
      - containerPort: 3306
```

And here is the error I am getting:
```
[root@localhost ~]# kubectl create -f mysqlpod.yaml 
error validating "mysqlpod.yaml": error validating data: expected type array, for field spec.containers, got map; if you choose to ignore these errors, turn validation off with --validate=false
```

I am not sure if there is a problem with my yaml or some other issue. Please help. TIA.

**Comment by AdoHe** [comment]
@Pensu the root cause is here: `error validating data: expected type array, for field spec.containers, got map`. Try this:
```
apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
    name: db
spec:
  containers:
  - name: mysql
    image: "mysql"
    env:
      - name: MYSQL_USER
        value: test
      - name: MYSQL_PASSWORD
        value: test
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DB
        value: BucketList
    ports:
    - containerPort: 3306
```
