### ISSUE TITLE
Ingress and TCP 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#23291]
This is more of an open question, should we teach the Ingress about TCP?

If we fold TCP into Ingress:
- Everything in the Ingress is about entry into the cluster 
- Everything in the Service is intra cluster (ips, algorithms, affinity etc) 
- Type=NodePort will continue to be an escape hatch for Services

This would enable us to leverage the Ingress for things like SSL routing (https://github.com/kubernetes/kubernetes/issues/19333), and leverage Service.Type=Loadbalancer for internal lb (whatever form that takes). 

**How to express type=loadbalancer?**

Create an Ingress like:

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: no-rules-map
spec:
  backend:
    serviceName: backendSvc
    servicePort: 80
```

kubectl expose would do this (discussion on https://github.com/kubernetes/kubernetes/issues/17429 needs to converge). 

**How to express SNI?**

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rules-map
spec:
  # SSL routing
  rules:
  - host: www.foo.com
    tcp:
      backend:
        serviceName: svc1
        servicePort: 80
  - host: foo.bar.com
    tcp:
      backend:
        serviceName: svc2
        servicePort: 80
```

If the above spec is defined _with_ a TLS section, the Ingress controller will terminate the connection using SNI to figure out which certs to serve. Discussion on: https://github.com/kubernetes/kubernetes/issues/19333

**Do we need to express TCP frontend ports?**

The challenge here is defining a frontend port that we don't really need for HTTP (:80 and :443 are implicit). One way is:

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rules-map
spec:
  rules:
  - host: www.foo.com
    tcp:
      port: 3321
      backend:
        serviceName: svc1
        servicePort: 80
```

Another option is to disallow `port`, the Ingress controller just picks one and writes it to Status (on GCE a port is not needed). All that matters is that TCP traffic reaches the backend. For legacy apps that _need_ a port, they create multiple ingresses with a `ingress.port` annotation that the Ingress controller tries to honor.

@kubernetes/goog-cluster @kubernetes/rh-networking @smarterclayton @aledbf @thockin @therc
