### ISSUE TITLE
autoscaling/v1 groupversion does not work well with validation/edit/export

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/kubernetes#23378]
As noted here: https://github.com/openshift/origin/issues/8213

Attempting to create the following HPA:

``` yml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-autoscaler 
spec:
  scaleRef:
    kind: DeploymentConfig 
    name: frontend 
    apiVersion: v1
  minReplicas: 1 
  maxReplicas: 10  
```

We get the following error:

``` sh
$ kubectl create -f hpa.yaml
kubectl create --validate=false -f hpa.yaml
The HorizontalPodAutoscaler "test-autoscaler" is invalid.

* spec.scaleRef.kind: Required value
* spec.scaleRef.name: Required value
```

This doesn't make sense as the values that seem to be missing in fact are in the YAML -- the issue is that `scaleRef` is the name of the reference in the `extensions/v1beta1` groupversion, whereas `scaleTargetRef` is the name in `autoscaling/v1`.

Attempting `kubectl edit` and making any change to the HPA will result in:

```
$ kubectl edit hpa test-autoscaler
error: apiVersion should not be changed
```

even if no changes to `apiVersion` field were made

Furthermore, when exporting using `kubectl get -o yaml`, the groupversion emitted is `extensions/v1beta1` even if the HPA was originally created as `autoscaling/v1` - this may be the desired behavior but it is suprising nonetheless.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1588+e44c8e6661c931", GitCommit:"e44c8e6661c931f7fd434911b0d3bca140e1df3a", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0-36-g4a3f9c5", GitCommit:"4c91857", GitTreeState:"not a git tree"}
```

/cc @liggitt @DirectXMan12
