### ISSUE TITLE
Environment variables from Secret include new line character

### ISSUE THREAD

**Issue by motomux** [kubernetes/kubernetes#23404]
secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: MWYyZDFlMmU2N2RmCg==
  username: YWRtaW4K
```

secret-env-pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: mycontainer
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
  restartPolicy: Never
```

Run pod and export environment variables.
```
kubectl create -f secret.yaml
kubectl create -f secret-env-pod.yaml
kubectl exec -it secret-env-pod bash
root@secret-env-pod:/data# export
```

Environment variables.
```
declare -x GOSU_VERSION="1.7"
declare -x HOME="/root"
declare -x HOSTNAME="secret-env-pod"
declare -x KUBERNETES_PORT="tcp://10.55.240.1:443"
declare -x KUBERNETES_PORT_443_TCP="tcp://10.55.240.1:443"
declare -x KUBERNETES_PORT_443_TCP_ADDR="10.55.240.1"
declare -x KUBERNETES_PORT_443_TCP_PORT="443"
declare -x KUBERNETES_PORT_443_TCP_PROTO="tcp"
declare -x KUBERNETES_SERVICE_HOST="10.55.240.1"
declare -x KUBERNETES_SERVICE_PORT="443"
declare -x KUBERNETES_SERVICE_PORT_HTTPS="443"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PWD="/data"
declare -x REDIS_DOWNLOAD_SHA1="e56b4b7e033ae8dbf311f9191cf6fdf3ae974d1c"
declare -x REDIS_DOWNLOAD_URL="http://download.redis.io/releases/redis-3.0.7.tar.gz"
declare -x REDIS_VERSION="3.0.7"
declare -x SECRET_PASSWORD="1f2d1e2e67df
"
declare -x SECRET_USERNAME="admin
"
declare -x SHLVL="1"
```
