### ISSUE TITLE
DNS is not working for external domains like google.com

### ISSUE THREAD

**Issue by arminbalalaie** [kubernetes/kubernetes#23474]
I have installed Kubernetes on Bare-metal/Ubuntu. I am on `6b649d7f9f2b09ca8b0dd8c0d3e14dcb255432d1` commit in git. I used `cd kubernetes/cluster; KUBERNETES_PROVIDER=ubuntu ./kube-up.sh` followed by `cd kubernetes/cluster/ubuntu; ./deployAddons.sh` to start the cluster. Everything went fine and the cluster got up.

My `/ubuntu/config-default.sh` is as follows:

``` bash
    # Define all your cluster nodes, MASTER node comes first"
    # And separated with blank space like <user_1@ip_1> <user_2@ip_2> <user_3@ip_3> 
    export nodes=${nodes:-"root@192.168.48.170 root@192.168.48.180"}

    # Define all your nodes role: a(master) or i(minion) or ai(both master and minion), must be the order same 
    role=${role:-"ai i"}
    # If it practically impossible to set an array as an environment variable
    # from a script, so assume variable is a string then convert it to an array
    export roles=($role)

    # Define minion numbers
    export NUM_NODES=${NUM_NODES:-2}
    # define the IP range used for service cluster IPs.
    # according to rfc 1918 ref: https://tools.ietf.org/html/rfc1918 choose a private ip range here.
    export SERVICE_CLUSTER_IP_RANGE=${SERVICE_CLUSTER_IP_RANGE:-192.168.3.0/24}  # formerly PORTAL_NET
    # define the IP range used for flannel overlay network, should not conflict with above SERVICE_CLUSTER_IP_RANGE
    export FLANNEL_NET=${FLANNEL_NET:-172.16.0.0/16}

    # Optionally add other contents to the Flannel configuration JSON
    # object normally stored in etcd as /coreos.com/network/config.  Use
    # JSON syntax suitable for insertion into a JSON object constructor
    # after other field name:value pairs.  For example:
    # FLANNEL_OTHER_NET_CONFIG=', "SubnetMin": "172.16.10.0", "SubnetMax": "172.16.90.0"'

    export FLANNEL_OTHER_NET_CONFIG
    FLANNEL_OTHER_NET_CONFIG=''

    # Admission Controllers to invoke prior to persisting objects in cluster
    export ADMISSION_CONTROL=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,SecurityContextDeny

    # Path to the config file or directory of files of kubelet
    export KUBELET_CONFIG=${KUBELET_CONFIG:-""}

    # A port range to reserve for services with NodePort visibility
    SERVICE_NODE_PORT_RANGE=${SERVICE_NODE_PORT_RANGE:-"30000-32767"}

    # Optional: Enable node logging.
    ENABLE_NODE_LOGGING=false
    LOGGING_DESTINATION=${LOGGING_DESTINATION:-elasticsearch}

    # Optional: When set to true, Elasticsearch and Kibana will be setup as part of the cluster bring up.
    ENABLE_CLUSTER_LOGGING=false
    ELASTICSEARCH_LOGGING_REPLICAS=${ELASTICSEARCH_LOGGING_REPLICAS:-1}

    # Optional: When set to true, heapster, Influxdb and Grafana will be setup as part of the cluster bring up.
    ENABLE_CLUSTER_MONITORING="${KUBE_ENABLE_CLUSTER_MONITORING:-true}"

    # Extra options to set on the Docker command line.  This is useful for setting
    # --insecure-registry for local registries.
    DOCKER_OPTS=${DOCKER_OPTS:-""}

    # Extra options to set on the kube-proxy command line.  This is useful
    # for selecting the iptables proxy-mode, for example.
    KUBE_PROXY_EXTRA_OPTS=${KUBE_PROXY_EXTRA_OPTS:-""}

    # Optional: Install cluster DNS.
    ENABLE_CLUSTER_DNS="${KUBE_ENABLE_CLUSTER_DNS:-true}"
    # DNS_SERVER_IP must be a IP in SERVICE_CLUSTER_IP_RANGE
    DNS_SERVER_IP=${DNS_SERVER_IP:-"192.168.3.10"}
    DNS_DOMAIN=${DNS_DOMAIN:-"cluster.local"}
    DNS_REPLICAS=${DNS_REPLICAS:-1}

    # Optional: Install Kubernetes UI
    ENABLE_CLUSTER_UI="${KUBE_ENABLE_CLUSTER_UI:-true}"

    # Optional: Enable setting flags for kube-apiserver to turn on behavior in active-dev
    RUNTIME_CONFIG="--basic-auth-file=password.csv"

    # Optional: Add http or https proxy when download easy-rsa.
    # Add envitonment variable separated with blank space like "http_proxy=http://10.x.x.x:8080 https_proxy=https://10.x.x.x:8443"
    PROXY_SETTING=${PROXY_SETTING:-""}

    DEBUG=${DEBUG:-"false"}
```

Then, I created a pod using the following yml file:

``` yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

And a service using the following yml:

``` yaml
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx-service
    spec:
      ports:
      - port: 8000
        targetPort: 80
        protocol: TCP
      selector:
        app: nginx
      type: NodePort
```

Then, I got into the started container terminal using `docker exec -it [CONTAINER_ID] bash`. The problem is that I cannot ping external domains like google.com, but I can ping external IPs like 8.8.8.8. So the container has internet access.

The host's `/etc/resolve.conf` file is as follows:

``` App.config
    nameserver 8.8.8.8
    nameserver 127.0.1.1
```

The container's `/etc/resolve.conf` file is as follows:

```
    search default.svc.cluster.local svc.cluster.local cluster.local
    nameserver 192.168.3.10
    nameserver 8.8.8.8
    nameserver 127.0.1.1
    options ndots:5
```

I think it could be related to either SkyDNS nameservers  misconfigurarion or a custom configuration that I have to do but I am not aware of.

Any workarounds?

I have also asked this question in [stackoverflow](http://stackoverflow.com/questions/35742070/cannot-ping-clusterip-from-inside-the-pod-and-dns-is-not-working-for-external-do), but no one has answered yet.

**Comment by arminbalalaie** [comment]
I found a workaround. SkyDNS documentation in the commandline arguments section, and specifically, for "nameservers" argument implies that:

> nameservers: forward DNS requests to these (recursive) nameservers (array of IP:port combination), when not authoritative for a domain. This defaults to the servers listed in /etc/resolv.conf

But it does not! To solve the problem, the dns addon replication controller configuration file (cluster/addons/dns/skydns-rc.yaml.in) should be changed to contain nameservers configuration. I changed the skydns container part as follows and it worked like a charm.
```yaml
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-10-13-8c72f8c
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        args:
        # command = "/skydns"
        - -machines=http://127.0.0.1:4001
        - -addr=0.0.0.0:53
        - -nameservers=8.8.8.8:53
        - -ns-rotate=false
        - -domain={{ pillar['dns_domain'] }}.
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 5

```

**Comment by m1093782566** [comment]
Are you sure `nameservers` is a valid flag?

```
Usage of /kube-dns:
      --alsologtostderr[=false]: log to standard error as well as files
      --dns-port=53: port on which to serve DNS requests.
      --domain="cluster.local.": domain under which to create names
      --federations=: a comma separated list of the federation names and their corresponding domain names to which this cluster belongs. Example: "myfederation1=example.com,myfederation2=example2.com,myfederation3=example.com"
      --healthz-port=8081: port on which to serve a kube-dns HTTP readiness probe.
      --kube-master-url="": URL to reach kubernetes master. Env variables in this flag will be expanded.
      --kubecfg-file="": Location of kubecfg file for access to kubernetes master service; --kube-master-url overrides the URL part of this; if neither this nor --kube-master-url are provided, defaults to service account tokens
      --log-backtrace-at=:0: when logging hits line file:N, emit a stack trace
      --log-dir="": If non-empty, write log files in this directory
      --log-flush-frequency=5s: Maximum number of seconds between log flushes
      --logtostderr[=true]: log to standard error instead of files
      --stderrthreshold=2: logs at or above this threshold go to stderr
      --v=0: log level for V logs
      --version[=false]: Print version information and quit
      --vmodule=: comma-separated list of pattern=N settings for file-filtered logging
```

I can't find `--nameservers`

**Comment by arminbalalaie** [comment]
Actually this is an argument for skydns not kube-dns. I saw similar complaints at [stackoverflow](http://stackoverflow.com/questions/35742070/cannot-ping-clusterip-from-inside-the-pod-and-dns-is-not-working-for-external-do). It seems things have changed about kubernetes DNS system. I didn't find time to give it a look. I am sure @thockin have better ideas about this issue.

**Comment by m1093782566** [comment]
@thockin 

I think visiting external domain is a reasonable need for the containered application inside kubernetes cluster. I wonder why kube-dns doesn't support it?

**Comment by bbnnt** [comment]
I took me time to realize I could not reach anything externally — guess what, my db was hosted outside so I looked everywhere but there, as not being able to reach anything externally still can't make sense to me at this point

You closed your issue but providing a bit more could insights could help the next person getting into this!

**Comment by arminbalalaie** [comment]
AFAIK, kube-dns is a wrapper for sky-dns to do the internal services and pods name resolution. SkyDNS is a DNS server and uses etcd as its backend which makes it a good fit for kubernetes. SkyDNS itself supports DNS forwarding and in the previous versions of kubernetes DNS plugin my workaround above would solve the problem of not resolving external domains. I am not sure how the current version is working.

**Comment by bbnnt** [comment]
But I mean, out of the box you're able to resolve external domains, aren't you ? It stopped to work all of a sudden (one of the apps was using an external db, you can understand the trouble)... feels like I miss to understand something important right here

**Comment by arminbalalaie** [comment]
I don't understand what is confusing for you here. the problem is that kube-dns resolves internal services and pod names but it cannot resolve external domains like google.com. So, for some unknown reason the DNS forwarding feature is not working. I am not sure if it is still happening in the current version because I didn't find time to re-produce the problem with the current version. However, as some ppl reported here and in the stackoverflow question the above  workaround which was working for the previous version is not working anymore, I opened the issue. 

Also, notice that DNS resolution is working fine at the individual nodes that host the containers and specifically ones that host SkyDNS containers. However, inside the containers, the DNS has been configured by kubernetes to use kube-dns/SkyDNS and it doesnt resolve external domains.

**Comment by bbnnt** [comment]
Well sorry for reaching you out here; in the end, not related exactly to DNS itself. We've been starting out with small instances, the kube-proxy got evicted due to a lack of resources (or a wrong decision made by kubelet - still related to this lack of resources). Better hit this one now than later…

**Comment by thockin** [comment]
DNS forwarding is end-to-end tested, so it is not systematically broken.  KubeDNS forwards to whatevcer is in your host's /etc/resolv.conf - is that configured properly?

@bowei

**Comment by amarruedo** [comment]
Does this mean that now it is not possible to use either `-nameserver` nor `SKYDNS_NAMESERVERS`  (as stated [here](http://stackoverflow.com/questions/33260745/adding-nameservers-to-kubernetes/34085756#34085756))?

I'm trying to use SKYDNS_NAMESERVERS (so my settings will be independet of hosts '/etc/resolv.conf') with no luck. Here is the spec I'm using:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dns-v20
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v20
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v20
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: kubedns
        image: gcr.io/google_containers/kubedns-amd64:1.9
        resources:
          # TODO: Set memory limits when we've profiled the container for large
          # clusters, then set request = limit to keep this container in
          # guaranteed class. Currently, this container falls into the
          # "burstable" category so the kubelet doesn't backoff from restarting it.
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        livenessProbe:
          httpGet:
            path: /healthz-kubedns
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
            scheme: HTTP
          # we poll on pod startup for the Kubernetes master service and
          # only setup the /readiness HTTP server once that's available.
          initialDelaySeconds: 3
          timeoutSeconds: 5
        args:
        # command = "/kube-dns"
        - --domain=cluster.local.
        - --dns-port=10053
        env:
        - name: SKYDNS_NAMESERVERS
          value: "192.168.0.70:53,192.168.0.100:53"
        ports:
        - containerPort: 10053
          name: dns-local
          protocol: UDP
        - containerPort: 10053
          name: dns-tcp-local
          protocol: TCP
      - name: dnsmasq
        image: gcr.io/google_containers/kube-dnsmasq-amd64:1.4
        livenessProbe:
          httpGet:
            path: /healthz-dnsmasq
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - --cache-size=1000
        - --no-resolv
        - --server=127.0.0.1#10053
        - --log-facility=-
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      - name: healthz
        image: gcr.io/google_containers/exechealthz-amd64:1.2
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 10m
            # Note that this container shouldn't really need 50Mi of memory. The
            # limits are set higher than expected pending investigation on #29688.
            # The extra memory was stolen from the kubedns container to keep the
            # net memory requested by the pod constant.
            memory: 50Mi
        args:
        - --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
        - --url=/healthz-dnsmasq
        - --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
        - --url=/healthz-kubedns
        - --port=8080
        - --quiet
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: Default  # Don't use cluster DNS.
```

**Comment by thockin** [comment]
Correct.  That will not work any more.  Kubelet has a flag to set the
resolv.conf to something other than /etc, so you can configure it that way.

**Comment by amarruedo** [comment]
@thockin I see, ok, thanks for the answer. 

So now, if my understanding is correct, if you want to change DNS configuration, you must restart the kubelet service (CoreOS systemd service in my case) in order to propagate changes in the cluster, no matter if you choose to edit hosts `resolv.conf` or use Kubelets `--resolv-conf` flag, is this right?

The key thign here is that I'm trying to avoid restarting services at host level (kubelet, network...) and just make the change updating `kube-dns-v20` manifest. I came up with this workarround:

Create the following `ConfigMap`:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-resolvconf
  namespace: kube-system
data:
  resolv.conf: |
    nameserver 192.168.0.70
    nameserver 192.168.0.100
```

Then, change `kube-dns-v20` manifest on the `dnsmasq` container part:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dns-v20
  namespace: kube-system

...

- name: dnsmasq
        image: gcr.io/google_containers/kube-dnsmasq-amd64:1.4
        livenessProbe:
          httpGet:
            path: /healthz-dnsmasq
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - --cache-size=1000
        - --server=127.0.0.1#10053
        - --log-facility=-
        - --resolv-file=/etc/resolvconf/resolv.conf
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        volumeMounts:
        - mountPath: "/etc/resolvconf"
          name: "dnsmasq-resolvconf"
...

volumes:
   - name: dnsmasq-resolvconf
     configMap:
       name: dnsmasq-resolvconf
```

It works...., but after a while name resolution doesn't work anymore, now I'm trying to figure out why it stops working. Does this aproach make any sense or am I completely wrong trying to configure things this way?

**Comment by bowei** [comment]
You probably need to change the resolv.conf used by the kubedns executable, not dnsmasq. dnsmasq is meant to be purely a caching layer.

**Comment by m1093782566** [comment]
@thockin 

I have a small worry that if host deny kube-dns's permission of retrieving /etc/resolv.conf, how kube-dns work correctly?

**Comment by bowei** [comment]
@m1093782566 Can you explain the specific situation that causes kube-dns to not be able to read `/etc/resolv.conf`. The file is populated by kubelet on pod startup.

**Comment by lslatr** [comment]
I'm running a cluster built with kubeadm on ubuntu 16.10.  The resolv.conf file points to 127.0.0.1 and the machine has dnsmasq running.  This is the problem in my case.   kube-dns inside a container tries to connect to 127.0.0.1 to resolve external dns requests.

```
$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search home
```

```
$ ps -ef | grep dns | grep -v grep
nobody    3085  1853  0 Jan10 ?        00:00:00 /usr/sbin/dnsmasq --no-resolv --keep-in-foreground --no-hosts --bind-interfaces --pid-file=/var/run/NetworkManager/dnsmasq.pid --listen-address=127.0.1.1 --cache-size=0 --conf-file=/dev/null --proxy-dnssec --enable-dbus=org.freedesktop.NetworkManager.dnsmasq --conf-dir=/etc/NetworkManager/dnsmasq.d
root      4233     1  9 Jan10 ?        01:55:53 /usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true --pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true --network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin --cluster-dns=10.96.0.10 --cluster-domain=cluster.local
root     32429 32413  0 Jan10 ?        00:04:20 /kube-dns --domain=cluster.local --dns-port=10053 --config-map=kube-dns --v=2
root     32519 32503  0 Jan10 ?        00:01:08 /usr/sbin/dnsmasq --keep-in-foreground --cache-size=1000 --no-resolv --server=127.0.0.1#10053 --log-facility=-
root     32577 32560  0 Jan10 ?        00:01:45 /dnsmasq-metrics --v=2 --logtostderr
root     32670 32647  0 Jan10 ?        00:03:07 /exechealthz --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null --url=/healthz-dnsmasq --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null --url=/healthz-kubedns --port=8080 --quiet
```

Manually editing the resolv.conf file to point to 8.8.8.8 fixes the problem... at least temporarily.   I'm not an ubuntu guy so I'll have to dig around for a more permanent solution.

**Comment by bowei** [comment]
@lslatr -- it looks like the `resolv.conf` is inherited from the Ubuntu system. Ubuntu by default runs its own copy of dnsmasq locally to do name resolution, so the inherited configuration doesn't work (the kube cluster dnsmasq would need use the ubuntu instance of dnsmasq, which is not possible as it is bound on the `lo` device on a different network namespace.

Changing the resolv.conf to 8.8.8.8 (or the recursive resolver from your ISP) will fix this issue (as you did above)

**Comment by thockin** [comment]
Maybe kubelet should recognize 127.0.0.1 and rewrite it to `hostname -i` ?
Is that dnsmasq bound to all interfaces or only loopback?

**Comment by bowei** [comment]
dnsmasq is bound only on 127.0.0.1

**Comment by lslatr** [comment]
Looks like just loopback

```
$ netstat -an | grep '53 ' | egrep 'LIST|udp'
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
udp        0      0 0.0.0.0:5353            0.0.0.0:*                          
udp        0      0 127.0.1.1:53            0.0.0.0:*                          
udp        0      0 127.0.0.53:53           0.0.0.0:*                          
udp6       0      0 :::5353                 :::*                               
```

**Comment by thockin** [comment]
well, that makes it pretty useless for containers.  We should just filter
that out and scream if the result is the empty set ?

**Comment by bowei** [comment]
@thockin -- that makes sense -- 127.x.x.x should never be inherited

**Comment by lslatr** [comment]
Just incase someone else has to resolve the issue here's a list of options:
http://askubuntu.com/questions/130452/how-do-i-add-a-dns-server-via-resolv-conf

**Comment by ravishivt** [comment]
For me on a bare-metal Ubuntu 16.04 cluster with Flannel, I couldn't resolve external DNS because I couldn't reach the external DNS server.  I had to add an iptables masquerade rule to get routing to work properly as detailed in #40761.

**Comment by snowhigh** [comment]
Hi, I have the same issue resolving external domain name in pods. I have a workaround by adding extra external name server into kube-dnsmasq pod parameters.
ex.
```
      - name: dnsmasq
        image: gcr.io/google_containers/kube-dnsmasq-amd64:1.4
        livenessProbe:
          httpGet:
            path: /healthz-dnsmasq
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - --cache-size=1000
        - --no-resolv
        - --server=127.0.0.1#10053
+        - --server=8.8.8.8
+        - --all-servers
        - --log-facility=-
```
