### ISSUE TITLE
AWS Feature: CA integration

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#23482]
AWS has limited CA support, and there is also LetsEncrypt.

Services (or ingress points) should declare that they want a certificate, and we should be able to automatically provision (& renew) them.

It is unclear whether there is value in the Amazon service, given LetsEncrypt exists.

**Comment by therc** [comment]
We're using the new Certificate Manager and #23495 does the trick if you create a wildcard certificate in advance. Wildcards are probably a better match for now, since you can have only twenty certificates, each with up to ten fully qualified domains, plus there's an yearly limit, too, so I'm reluctant to have the controller manager burn through such a scarce resource, especially if there are bugs or misconfigurations. An improvement might be to have the controller look up certificates by host/domain name, instead of having to hardcode the ARN.

**Comment by bprashanth** [comment]
See https://github.com/kubernetes/kubernetes/issues/19899 for lets encrypt integration. Having at least one way to get/renew real certs cross-platform makes sense, that's not to say we can't support multiple platform-specific ways. 

I imagine that if a user creats something like:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  tls:
  - hosts:
    - foo.bar.com
    - foobar.bar.com
    secretName: empty
  backend:
    serviceName: echoserver-https
    servicePort: 80
```

A cluster wide cert controller (or a cert sidecar in the ingress controller) would notice this, get the certs and populate the secret field. Only then would the haproxy/nginx/cloudlb pick the Ingress up.
