### ISSUE TITLE
Kubelet sometimes creates a second container when it shouldn't

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#23636]
If you create a pod that will never be able to run successfully, such as this:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: bad
spec:
  containers:
  - name: bad
    image: busybox
    command:
    - /blarg
  restartPolicy: Never
```

sometimes you'll see 1 container that is created and then fails to start, and then the pod is marked as failed. Other times you'll see that the Kubelet creates 2 containers before marking the pod as failed. The following are kubelet log line numbers that show the sequence of events:

```
7577 - syncPod (1st time - for new pod)
7637 - PLEG starts relisting
7662 - 1st container created for pod
7663 - PLEG inspects container. Container isn't running yet
7666 - PLEG records "unknown" status
7672 - error running container
7690 - PLEG starts relisting again
7691 - syncPod (2nd time, status cache still has "unknown")
7714 - 2nd container created for pod
7731 - PLEG inspects containers and sees 2 dead containers now
7733 - PLEG updates status to dead
```

It looks like the pod worker is passing a slightly out of date pod status to syncPod.

@kubernetes/rh-cluster-infra @kubernetes/sig-node
