### ISSUE TITLE
Allow underscore in configMapKeyRef key's

### ISSUE THREAD

**Issue by johanhaleby** [kubernetes/kubernetes#23722]
Is there a reason why underscore (`_`) is prohibited from being used as keys in a configMapKeyRef?

Let's say I have a `deployment.yaml` file that contains an env section like this:

```yaml
env:
	- name: SOMETHING
	  valueFrom:
	    configMapKeyRef:
	      name: my-config
	      key: SOME_KEY
```

If I `kubectl create` this deployment file I'll end up with this error:

```bash
* spec.template.spec.containers[0].env[0].valueFrom.configMapKeyRef.key: Invalid value: "SOME_KEY": must have at most 253 characters and match regex \.?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
```

The reason why we had underscores in the configuration name is because of previous configuration limitations with Kubernetes as described [here](http://code.haleby.se/2015/11/20/simple-templating-engine-in-bash/). So if underscores are not allowed we would have to change all of our config files and many of our Jenkins build jobs.

**Comment by liggitt** [comment]
The envvar can have an underscore, just not the config map key

**Comment by johanhaleby** [comment]
Yes, but I'm talking about the config map key.

**Comment by liggitt** [comment]
Sure, but why would that require changing config files and Jenkins jobs?

**Comment by johanhaleby** [comment]
Well since there was no good way of exposing environment variables from a config file in the previous versions of Kubernetes we created our own [bash templater](https://github.com/johanhaleby/bash-templater) which essentially allowed us to create a concrete yaml description files based on templates. For example using the "bash templater" we could transform:

```yaml
kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: "my-pod"
  labels:
    name: "my-pod"
    version: "{{VERSION}}"
spec:
  replicas: 2
  selector:
    name: "my-pod"
    version: "{{VERSION}}"
  template:
    metadata:
      labels:
        name: "my-pod"
        version: "{{VERSION}}"
    spec:
      containers:
        - name: "my-pod"
          image: "gcr.io/my-project/my-pod:{{VERSION}}"
          env:
            - name: "TIMEOUT"
              value: {{TIMEOUT}}
            - name: "URL"
              value: "{{URL}}"
          ports:
            - containerPort: {{API_PORT}}
              name: "api"
              protocol: "TCP"
            - containerPort: {{ADMIN_PORT}}
              name: "admin"
              protocol: "TCP"
```

Into:

```yaml
kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: "my-pod"
  labels:
    name: "my-pod"
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    name: "my-pod"
    version: "1.0.0"
  template:
    metadata:
      labels:
        name: "my-pod"
        version: "1.0.0"
    spec:
      containers:
        - name: "my-pod"
          image: "gcr.io/my-project/my-pod:1.0.0"
          env:
            - name: "TIMEOUT"
              value: "2000"
            - name: "URL"
              value: "http://something.com"
          ports:
            - containerPort: 8080
              name: "api"
              protocol: "TCP"
            - containerPort: 8081
              name: "admin"
              protocol: "TCP"
```

Based on config files that looked like this:

```bash
VERSION=1.0.0
TIMEOUT=5000
URL="http://something.com"
API_PORT=8080
ADMIN_PORT=8081
```

This is why all of our keys in our config files have underscored in their names (which is not allowed in config maps). The bash templater doesn't support "." or "-" in the key name (since it'll actually convert the key - value pairs into environment variables). So in our case we would have to migrate all of our config files as well as changing to a another templater engine (which should be used by Jenkins) since we still cannot assign all values from config maps alone. For example the "VERSION" key which is exposed as a label still needs to be assigned from a template (since config maps only works in the pod specification afaik).

But regardless of all of this my question still remains, is there a reason why underscores are allowed in config map keys?

**Comment by johanhaleby** [comment]
Oh and another thing. I think support underscores would make it easier to migrate from docker and docker-compose since they both allow you to specify the environment variables from a file (--env-file). Migrating these files to work on kubernetes with config maps would require you to replace the underscores with (for example) dashes which in my view should not be necessary.

**Comment by errm** [comment]
When using secrets or config maps to configure environment variables it would make sense to allow keys to be the same as env vars.

Most POSIX tools (bash) allow `/[a-zA-Z_][a-zA-Z0-9_]*/` in the names of env vars, so I think we should allow `[a-zA-Z0-9]([-_a-zA-Z0-9]*[a-zA-Z0-9])?` in these keys.

I will open a PR in a day or two.

**Comment by thockin** [comment]
Truthfully, the only reason I can think of for being restrictive was that it is easier to loosen than to tighten, and we weren't sure what we needed.

I can't think of a reason not to allow upper case and underscores and dots, personally.  @pmorie?

**Comment by ram-argus** [comment]
Also consider ramification of introducing `--from-file`: 
`kubectl create configmap vpn-config --from-file=./config/ovpn_env.sh`
the command breaks because the file happens to have an underscore.

**Comment by thockin** [comment]
fixed in 1.4!

**Comment by zeniri** [comment]
**ConfigMap File:** 
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap_test
data:
  Values1: config_dir
  Values2: service
```
**Error:** The ConfigMap "configmap_test" is invalid: metadata.name: Invalid value: "configmap_test": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**name: configmap_test <-- Why is underscore not allowed?**
