### ISSUE TITLE
If kube-controller-manager restarts, changes to ELBs are reverted

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#23744]
I use LoadBalancer services in AWS to create ELBs. A typical service looks like this:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: internal-api
  name: internal-api
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    name: internal-api
  type: LoadBalancer
```

I have a script that will then slightly twiddle the ELB via the AWS API to change the listener from type `TCP` to type `HTTPS` and configure my SSL/TLS certificate.

If for any reason, the controller manager restarts, these changes are reverted. Preferably, the manager should only alter the ports in question and no other ELB parameters.
