### ISSUE TITLE
Using Persistent Volume Claims in combination with ConfigMap for same path

### ISSUE THREAD

**Issue by jason-riddle** [kubernetes/kubernetes#23748]
So I have an interesting situation. I have a use case where I want to use run a jenkins docker image which is backed with a persistent volume and uses a configmap for defining a proxy config. The pseudocode, which is just a snippet of an [application-dm-template](https://github.com/kubernetes/charts), looks roughly like this.

```yaml
volumes:
  - mount_path: /var/jenkins_home
    persistentVolumeClaim:
      claimName: jenkins-server-data
  - mount_path: /var/jenkins_home
    configMap:
      name: cicd-proxy-config
      items:
      - key: jenkins-proxy-xml
        path: proxy.xml
```

Now my issue is I want to save my Jenkins config to a persistent volume which is mounted as <code>/var/jenkins_home</code>, but I also want to mount a file, <code>proxy.xml</code> under that directory as well. I'm assuming that you can't have two mount_path's with the same path, but are being backed by different storage systems.

I would normally have the ConfigMap exposed as environment variables, but the application in this instance (Jenkins) does not look at environment variables for proxy credentials and they must be under the data directory (in this case <code>/var/jenkins_home</code>) in the <code>proxy.xml</code> file. Is it possible to accomplish this?

**Comment by maclof** [comment]
I would also like to see if this is possible to do as I have several use cases where this would be ideal.

**Comment by thockin** [comment]
It's not possible to have 2 mounts at the same path.  One would just override the other.  Specifically, the configMap mount is not just writing files into a directory, it actually bind-mounts a whole dir over the mount point.

It may be possible in Kubernetes v1.3 to mount JUST a single file from the configmap with the volumeMount.subPath` field, but I have not tried doing that OVER another volume.  In short:

```
volumes:
  - name: jenkins
    persistentVolumeClaim:
      claimName: jenkins-server-data
  - name: proxy-xml
    configMap:
      name: cicd-proxy-config
      items:
      - key: jenkins-proxy-xml
        path: proxy.xml
...
volumeMounts:
  - name: jenkins:
    mount_path: /var/jenkins_home
  - name: proxy-xml
    mount_path: /var/jenkins_home/proxy.xml
    subPath: proxy.xml
```

To reiterate, I have not tried this, but it sounds like it should work.

@pmorie

**Comment by thockin** [comment]
My curiosity got the better of me, and I tried it.  It works!  The only
caveat here is that, because of the way bind mount works, the auto-updating
feature of config-map volumes will not update the file.

**Comment by thockin** [comment]
I'm going to close this issue, but please let me know if you can't make it work.  My exact YAML is below.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-pd-plus-cfgmap
data:
  file-from-cfgmap: file data
```

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd-plus-cfgmap
spec:
  containers:
  - image: ubuntu
    name: bash
    stdin: true
    stdinOnce: true
    tty: true
    volumeMounts:
    - mountPath: /mnt
      name: pd
    - mountPath: /mnt/file-from-cfgmap
      name: cfgmap
      subPath: file-from-cfgmap
  volumes:
  - name: pd
    gcePersistentDisk:
      pdName: testdisk
  - name: cfgmap
    configMap:
      name: test-pd-plus-cfgmap
```
