### ISSUE TITLE
Installing multiple third party resources on same resource path prefix has issues

### ISSUE THREAD

**Issue by uruddarraju** [kubernetes/kubernetes#23831]
I am trying to install the following thirdparty resources:

```yaml
metadata:
  name: compute-node.tess.io
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A compute node object is used by the mastercontroller to track computes in cloud"
versions:
 - name: v1
```

And 

```yaml
metadata:
  name: node-pool.tess.io
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A node pool object to nodes is analogous to what a replicationcontroller is to pods"
versions:
 - name: v1
```

The first one gets successfully registered when I try to create it. But the second on never gets registered and kubectl does not throw an error out either. I digged a little deep into the kube-apiserver logs and I see the following error:

`Recovered from panic: "http: multiple registrations for /apis/tess.io/v1" (http: multiple registrations for /apis/tess.io/v1)`

When I digged deep into the thirdparty controller and master.go, here: https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L611, I see that we have not covered the case where there can be 2 API objects defined on the same resource path prefix, like `/apis/tess.io/v1/nodepools` and `/apis/tess.io/v1/computenodes`

Is there something I am missing, or is this a genuine issue you think ?
