### ISSUE TITLE
HostPort seemingly not working

### ISSUE THREAD

**Issue by microadam** [kubernetes/kubernetes#23920]
I am not sure if what I am doing is supposed to work. But I have created the following pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-host
spec:
  containers:
  - image: caseydavenport/nginx
    imagePullPolicy: IfNotPresent
    name: nginx-host
    ports:
    - containerPort: 80
      hostPort: 80
  restartPolicy: Always
```

This gives me a pod with the following:

```
        "hostIP": "178.x.x.x",
        "podIP": "10.x.x.x",
```

From the host (178.x.x.x), running: `curl http://10.x.x.x` gets me the response from nginx that I expect.
From the host (178.x.x.x), running `curl http://178.x.x.x` gets me `port 80: Connection refused`.

Should this work? Or have I missed something?

Versions:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.1", GitCommit:"50809107cd47a1f62da362bccefdd9e6f7076145", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.1", GitCommit:"50809107cd47a1f62da362bccefdd9e6f7076145", GitTreeState:"clean"}
```

Networking: Calico

Host OS: Ubuntu 16.04

Docker: 1.10.3

Thanks a lot

**Comment by zhouhaibing089** [comment]
what's the output when you run `ip route` on host?

**Comment by microadam** [comment]
@zhb I got an email notification with you asking for the output of `ip route`, but your message seems to have gone now? The output is this:

```
default via 178.79.148.1 dev eth0 onlink
10.233.64.0/26 via 192.168.10.3 dev tunl0  proto bird onlink
blackhole 10.233.64.64/26  proto bird
10.233.64.65 dev calief9a4578fa8  scope link
10.233.64.71 dev cali70f7dfd2fb5  scope link
10.233.64.81 dev cali4660569efc0  scope link
10.233.64.128/26 via 192.168.10.1 dev tunl0  proto bird onlink
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown
178.x.x.x/xx dev eth0  proto kernel  scope link  src 178.x.x.x
192.168.10.0/24 dev k8s0  proto kernel  scope link  src 192.168.10.2
192.168.128.0/17 dev eth0  proto kernel  scope link  src 192.168.202.48
```

**Comment by microadam** [comment]
Just to say, I can get this to work if I set `hostNetwork: true` on the pod, but that then exposes all of the ports in the pod to the host network, where as I only want one specific port (80) to be exposed

**Comment by microadam** [comment]
anyone able to confirm if I am just doing something wrong with this? or if it should work like I have described?

Thanks

**Comment by thockin** [comment]
It should work, and it does work on my local cluster.

**Comment by microadam** [comment]
@thockin Thanks for confirming. Could I ask what setup your test cluster is please? (networking type, cloud provider, host OS etc).

**Comment by thockin** [comment]
GCE, underlay networking, Debian

We pass HostPort thru to Docker, so maybe start with docker inspect?

**Comment by microadam** [comment]
@thockin sorry, I am not familiar with underlay networking (or GCE for that matter). It it a GCE specific thing? I can't see anything about underlaying networking in the k8s documentation.

With regards to docker inspect. The output of the networking section is as follows:
```
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": null
        }
```
 Would I be right in assuming that I should be seeing port 80 in the "Ports" property that is currently null?

Thanks for your assistance!

**Comment by thockin** [comment]
Sorry, docker would call it "bridge" mode.

You need to look at `docker inspect` on the "pause" container for your pod.

You can also run `netstat -nap` and look for your port (on the host)

**Comment by microadam** [comment]
@thockin Ah yes of course. I forget about the `pause` container. Looking at this there are a couple of interesting things. Not sure which is most relevant:

```
"HostConfig": {
  "Binds": null,
  "ContainerIDFile": "",
  "LogConfig": {
      "Type": "json-file",
      "Config": {}
  },
  "NetworkMode": "none",
  "PortBindings": null,
```

and 

```
"NetworkSettings": {
    "Bridge": "",
    "SandboxID": "995f5b5b80714e4ad98e5db6fb6069980d32c308c72fe875cd5598463e7e0ebd",
    "HairpinMode": false,
    "LinkLocalIPv6Address": "",
    "LinkLocalIPv6PrefixLen": 0,
    "Ports": {},
    "SandboxKey": "/var/run/docker/netns/995f5b5b8071",
    "SecondaryIPAddresses": null,
    "SecondaryIPv6Addresses": null,
    "EndpointID": "",
    "Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "IPAddress": "",
    "IPPrefixLen": 0,
    "IPv6Gateway": "",
    "MacAddress": "",
    "Networks": {
        "none": {
            "IPAMConfig": null,
            "Links": null,
            "Aliases": null,
            "NetworkID": "bcf6c68b0dd8461cc977d6168ad01a98e6499826085d58e3f8a16eb18fef32f6",
            "EndpointID": "792de55003f37bfd94f2dac62d05dff792b10fc5eef0fe771e78c58accf5d2b7",
            "Gateway": "",
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "MacAddress": ""
        }
    }
}
```

Guessing `Bridge` should not be an empty string?

Nothing about anything listening on port 80 when I run `netstat` either.

**Comment by caseydavenport** [comment]
@thockin @microadam - Correct me if I'm misunderstanding something, but I _think_ that `hostPort` just isn't going to work with CNI based integrations at the moment (I see you're using Calico).

`hostPort` currently relies on Docker to configure the port mapping, but in the CNI case Docker doesn't have the knowledge to do this, since pods are started with `net=none`.

I think this could be resolved by sending hostPort the way of NodePort, and writing the iptables rules from k8s instead of docker.  I don't think the `kube-proxy` watches pods at the moment, so probably not a trivial change.

**Comment by freehan** [comment]
@dcbw

**Comment by bboreham** [comment]
Referencing CNI discussion at http://github.com/containernetworking/cni/issues/46

**Comment by thockin** [comment]
FWIW it is possible to do in many CNI implementations, but I hesitate to
promise that it will work for all CNI implementations.  The question then
is which side of that fence it belongs on.

**Comment by bboreham** [comment]
New discussion about a solution in CNI at #31307

**Comment by danielschonfeld** [comment]
I can confirm this problem and solution renders all the Ingress examples useless.  Most of those nginx RC and DS examples contain the use of `hostPort` but no use of `hostNetwork`.  Took me a while to stumble on this issue and figure out how to make it work.

**Comment by chulkilee** [comment]
I confirm this problem when I set up a cluster on bare metal using kubeadm. Since I want to use nginx ingress controller on 80 and 443 but apiserver uses 443 in the cluster, `hostNetwork` cannot be an option in my case.

**Comment by spiddy** [comment]
same issue here, I stumbled on that when creating a cluster using kube-aws with `v1.4.0_coreos.1` (AWS environment). The problem is the Ingress controller (the nginx one) cannot be used since it uses `hostPort` as mentioned before.

**Comment by veryhumble** [comment]
I have the same issue. Running 14 on CentOS with Weave. Does anyone have a workaround? Without an ingress controller the cluster is pretty much unusable.

**Comment by axsuul** [comment]
Also need to rely on `hostPort` with https://github.com/kubernetes/contrib/tree/master/for-demos/proxy-to-service

Am using Weave for networking and I need to expose a service to port 80 on the host

**Comment by howlym** [comment]
I have the same issue with kube-registry-proxy on 1.4 bare metal.

**Comment by bacongobbler** [comment]
We've also seen this issue with Deis. We use a hostPort with a container called [registry-proxy](https://github.com/deis/registry-proxy) to bypass the Docker `--insecure-registry` requirement for internal networks. We've seen this occur only on CoreOS-specific installations such as with [kube-aws](https://github.com/coreos/coreos-kubernetes). Vagrant (Fedora), GKE (Debian), AWS (Ubuntu) and [Minikube](https://github.com/kubernetes/minikube) (custom ISO) all work without issue.

To reproduce:

 - install Workflow on a kube-aws cluster
 - observe registry-proxy isn't listening on the host's port 5555 with `netstat -a`

**Comment by carsonoid** [comment]
For those that care one possible workaround is to use NodePort mappings to make ingress controllers work when using cni. Not an ideal solution for anyone that uses hostPort a lot but if you only need it for ingress it can be acceptable. The big downside is that you have to map to ports in the allowed nodeport range or change the range to allow lower ports.

**Comment by shenshouer** [comment]
I have the same issue. Running 1.4.5 on ubuntu 16.04 with calico.hostPort of  ingress controller on node not work. 

version of k8s:

```
sope$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by nailgun** [comment]
@bacongobbler, looks like it's not just CoreOS.

Just followed [kubeadm tutorial](http://kubernetes.io/docs/getting-started-guides/kubeadm/) to install Kubernetes on single **Cent**OS 7 bare-metal host. Then I've deployed Deis Workflow by following [this guide](https://deis.com/docs/workflow/installing-workflow/). Now when I'm trying to [deploy example app](https://deis.com/docs/workflow/quickstart/deploy-an-app/) using Deis, I'm experiencing the same issue.

**Comment by bboreham** [comment]
As noted at https://github.com/kubernetes/kubernetes/issues/23920#issuecomment-217048099,  Kubernetes installs that use CNI, which includes all `kubeadm` installs, do not currently support `hostPort`.

**Comment by dgoujard** [comment]
@nailgun You need to use hostNetwork in your router pod i think, example with an nginx ingress controller : 
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress-lb
spec:
  template:
    metadata:
      labels:
        name: nginx-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
        name: nginx-ingress-lb
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
```

**Comment by Rastusik** [comment]
@dgoujard but when using hostNetwork, the pod isn't visible from the k8s/calico/cni network, or am I wrong? And also the opposite way, the pod with host network doesn't see the calico/cni networked pods, I suppose at least.

**Comment by caseydavenport** [comment]
@Rastusik hostNetworked pods should have access to non-host networked pods, and vice-versa.

**Comment by pesho** [comment]
@Rastusik the hostNetwork pod can reach other (CNI) pods directly by IP. But it can't resolve services by their name, because it does not use `kube-dns` as the resolver.

E.g. the Nginx ingress controller works with hostNetwork.

**Comment by shenshouer** [comment]
@dagnello if use `hostNetwork` in ingress controller, the pod cann`t access the kubernetes api server with `https://10.100.0.1:443` which in environment variables. I think the pod with host network cann`t access the service in kubernetes

**Comment by dcbw** [comment]
@dgoujard I'm pretty sure that HostNetwork pods can't use HostPort mappings.  That's the case with plain Docker (eg, try "docker run -it -p 8080:14000 --net=host nginx bin/bash" and watch nothing happen in iptables) and that's also the case with Kubernetes and CNI.

Since docker is no longer involved in the networking when CNI is used, the CNI plugins themselves currently need to implement the hostport functionality.

**Comment by nailgun** [comment]
Besides using `hostNetwork` I had to manually open ports on nodes using iptables. After that it started working.

**Comment by Rastusik** [comment]
just a question - is this issue being worked on or not? Is it not that important? I think it should be quite important, because we have to use NodePorts as workaround for all external traffic, which is not optimal.

**Comment by gaord** [comment]
The issue makes ingress controller have to run in hostNetwork container. Hope it can be fixed soon. 
[https://github.com/nginxinc/kubernetes-ingress](url)

**Comment by sheerun** [comment]
Here's my workaround for the time being, just replace the backend ip in second service:

```
apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: nginx-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: nginx-ingress-controller
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-controller
        name: nginx-ingress-controller
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: nginx
        name: nginx-ingress-controller
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service
  namespace: kube-system
  labels:
    name: nginx-ingress-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    name: nginx-ingress-controller
```

```
kind: ConfigMap
metadata:
  name: nginx-volume-config
  namespace: kube-system
data:
  nginx.conf: |-
    worker_processes 1;

    events {
      worker_connections 1024;
    }

    http {
      upstream kubernetes {
        server 10.106.50.107;
      }

      server {
        listen 80;

        location / {
          proxy_pass http://kubernetes;
          proxy_redirect off;
          proxy_set_header Host $host;
        }
      }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress-proxy
  namespace: kube-system
  labels:
    k8s-app: nginx-ingress-proxy
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-proxy
        name: nginx-ingress-proxy
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: nginx
        name: nginx-ingress-proxy
        imagePullPolicy: IfNotPresent
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx
          name: config
          readOnly: false
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
          protocol: TCP
      hostNetwork: true
      restartPolicy: Always
      securityContext: {}
      volumes:
      - name: config
        configMap:
          name: nginx-volume-config
          items:
          - key: nginx.conf
            path: nginx.conf
```

I'd be really happy if someone knows how to automatically configure 10.106.50.107

For some reasone kube-dns isn't working, so I can't use something like `traefik-ingress-service.kube-system.svc.cluster.local`

**Comment by thockin** [comment]
@freehan This feels like a dup of something related to CNI and host ports - can you de-dup as needed?

**Comment by bboreham** [comment]
This is the primary "HostPort doesn't work with CNI" issue, as far as I know.

**Comment by ekozan** [comment]
https://github.com/kubernetes/kubernetes/issues/31307

**Comment by bboreham** [comment]
#31307 is a proposed way forward, posted 4 months after this issue.
I'm relying on the comment at https://github.com/kubernetes/kubernetes/issues/23920#issuecomment-217048099 being the correct diagnosis of this issue.

**Comment by tobilarscheid** [comment]
Would it be an acceptable workaround to run kubernetes without calico? [This](https://coreos.com/kubernetes/docs/latest/deploy-master.html#set-up-calico-for-network-policy-optional) states that calico is optional, but it also says that calico enables the one-IP-per-Pod concept which seems to be very important to me.

**Comment by bboreham** [comment]
@tobilarscheid it would not really be a workaround, more like forgetting this issue exists.

The issue applies to any 3rd-party network; if anyone has any reason to use such a thing, and they also want to use hostPort, then we need to fix this.

"one-IP-per-Pod" is currently the way Kubernetes works.  All container networks that work with Kubernetes enable this concept.

**Comment by ekozan** [comment]
this one can be caused ?

**Comment by bboreham** [comment]
Some work underway as part of a fix: https://github.com/containernetworking/cni/pull/378

**Comment by tbchj** [comment]
@microadam  did you solve the problem,  I met the same problem as you
my k8s version is : 1.3.10     hostport didn't work

**Comment by tbchj** [comment]
all my fault. hostport can work . i make a mistake, sorry

**Comment by jeffchanjunwei** [comment]
hi @tbchj，how do u solve it. i also meet the same problem

**Comment by tbchj** [comment]
@jeffchanjunwei   mine is ok.  my fault. i did nothing. the command line  i wrote before,  miss one paramter , and the paramter just is a port number  which  the process running need.
so my fault

**Comment by xlgao-zju** [comment]
+1 for this issue.

**Comment by ekozan** [comment]
It's working now ^^ it's still open beacause an temporary solution has been made

**Comment by xlgao-zju** [comment]
@ekozan how did you fix this issue?

**Comment by ekozan** [comment]
upgrade to 1.6.0 ^^

**Comment by Bregor** [comment]
@ekozan you mean just upgrade to 1.6 fixes this issue automagically?
Maybe you installed newer CNI-binary with `hostPort` support?
I mean https://github.com/containernetworking/cni/commit/71c4a60741c87e17325ea6b03234a38fabd06986 for example.

**Comment by Bregor** [comment]
BTW, PR about port mapper is still not merged: https://github.com/containernetworking/plugins/pull/1

**Comment by ekozan** [comment]
if i have understand all thing https://github.com/kubernetes/kubernetes/pull/40948/files fix it temporary and definitive solution will be the cni plugin

**Comment by Bregor** [comment]
@ekozan thanks for the link and good luck with upgrade!

**Comment by xlgao-zju** [comment]
Setting `NET_PLUGIN=cni` to use cni network will cause the hostport not to work.
Setting `NET_PLUGIN=kubenet` to use kubenet, then the hostport works fine.

**Comment by jeffchanjunwei** [comment]
@xlgao-zju ，where do u set these NET_PLUGIN=cni  NET_PLUGIN=kubenet ?

**Comment by xlgao-zju** [comment]
@jeffchanjunwei I just use k8s on my laptop, os I just local up k8s. 
I add  NET_PLUGIN=cni NET_PLUGIN=kubenet in /hack/local_up.sh. And I use k8s 1.6. Hope I can help you. :）

**Comment by freehan** [comment]
FYI, upstream cni repo has a PR to add port-forwarding plugin in flight https://github.com/containernetworking/plugins/pull/1 

With this, one can set NET_PLUGIN=cni and include the port-forwarding plugin in the cni network config chain. Then it will be able to support hostport feature.

**Comment by bboreham** [comment]
FYI CNI PR is merged

**Comment by philips** [comment]
@bboreham does that mean this will be fixed in 1.7?

**Comment by caseydavenport** [comment]
@philips yep.  Kubernetes now has support for plugin chaining and the portmap capability, and an upstream port mapping plugin exists which can be chained to provide the port mapping.

@gunjan5 has tested this out with Calico and it works using k8s v1.7.0-alpha.4

**Comment by moserke** [comment]
I'm not sure I'm following this.  Some things say it's fixed, others say it's not.  If I am using k8s 1.6.4 with Calico CNI, should hostPort work?

**Comment by caseydavenport** [comment]
@moserke you'll need a v1.7.0 k8s for this to work, and then you'll need to update your CNI configuration and version. 

Here's an example: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/calico-policy-controller/calico-node-daemonset.yaml#L77

**Comment by moserke** [comment]
@caseydavenport I have tried to get this to work in v1.7.0-beta.1 but my calico nodes continue to throw the error

```
2017-06-13 15:47:19.655 [ERROR][35] felix.go 840: Unable to get Typha service from Kubernetes. error=services "calico-typha" not found
2017-06-13 15:47:19.655 [ERROR][35] felix.go 213: Typha discovery enabled but discovery failed. error=services "calico-typha" not found
```

And port mapping seems to still not be happening.  Perhaps I have my configuration wrong?

**Comment by moserke** [comment]
@caseydavenport I've been fighting this all day.  The best I can get to is if I use this config it works:

```
{
            "name": "calico",
            "type": "flannel",
            "delegate": {
              "type": "calico",
              "log_level": "info",
              "etcd_endpoints": "http://#{private_fqdn}:2379",
              "policy": {
                  "type": "k8s",
                  "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
                  "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
              },
              "kubernetes": {
                  "kubeconfig": "/etc/cni/net.d/__KUBECONFIG_FILENAME__"
              }
            }
        }
```

But if I use this config it does not:

```
    {
      "name": "calico",
      "cniVersion": "0.3.0",
      "plugins": [
        {
            "name": "calico",
            "type": "flannel",
            "delegate": {
              "type": "calico",
              "log_level": "info",
              "etcd_endpoints": "http://#{private_fqdn}:2379",
              "policy": {
                  "type": "k8s",
                  "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
                  "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
              },
              "kubernetes": {
                  "kubeconfig": "/etc/cni/net.d/__KUBECONFIG_FILENAME__"
              }
            }
        },
        {
          "name": "calico",
          "type": "portmap",
          "capabilities": {"portMappings": true},
          "noSnat": true
        }
      ]
    }
```

The above config just continues to through the error `network: no plugin name provided`

Any thoughts on what I might be doing wrong?  I feel like I am so close but just not quite there.

kubelet is 1.7.0-beta.1

**Comment by gunjan5** [comment]
@moserke what is the config file called? It has to end with `.conflist` extension (not `.conf`)

**Comment by moserke** [comment]
@gunjan5 oh geez!  Don't I feel like an idiot.  That was 100% my problem.  Well that's several hours of my life I won't get back.  Thanks a ton to you and @caseydavenport for the help to get me up and running!  Port mapping is now working for me.  Great!

**Comment by pichouk** [comment]
Maybe I miss something but it appear not working with Kubernetes `1.7.0` for me.

```
root@test-master0:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
Pushing this :
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
  namespace: infra
data:
  http2: 'True'
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress-controller
  namespace: infra
spec:
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
        name: nginx-ingress-controller
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.10
          name: nginx-ingress-controller
          imagePullPolicy: Always
          ports:
            - containerPort: 80
               hostPort: 80
               protocol: TCP
           - containerPort: 443
             hostPort: 443
             protocol: TCP
          args:
            - /nginx-ingress-controller
            - '--configmap=infra/nginx-ingress-controller'
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      nodeSelector:
        type: node
```

I try to curl my ingress controller, but didn't work :
```
root@test-node0:~# curl myNodeIp
curl: (7) Failed to connect to myNodeIp port 80: Connection refused
```

I checked and the container does not seems to listen on the node port.

**Comment by redbaron** [comment]
@pichouk do you have hostPort in your CNI plugin config?

**Comment by pichouk** [comment]
@redbaron I'm not sure of how to verify this.

I'm using Weave and I try to look on some documentation by myself but didn't find something relevant to help me.
My `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` looks like this :
```
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment=HOME=/root
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_EXTRA_ARGS
```

And `/etc/cni/net.d/10-weave.conf`   
```json
{
    "name": "weave",
    "type": "weave-net",
    "hairpinMode": true
}
```

**Comment by caseydavenport** [comment]
@pichouk you'll need to add the portmap plugin to your CNI config.

Theres [an example using Calico here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/calico-policy-controller/calico-node-daemonset.yaml#L86) - should be similar for Weave.

/assign

**Comment by caseydavenport** [comment]
Closing as fixed in v1.7.0

/close

**Comment by linhdsv** [comment]
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - image:  quay.io/prometheus/node-exporter:v0.14.0
        args:
        - "-collector.procfs=/host/proc"
        - "-collector.sysfs=/host/sys"
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
```
Is this issue resolved yet? I got same error with my `node-exporter` service.
