### ISSUE TITLE
Replacing ClusterIP service with NodePort service fails 

### ISSUE THREAD

**Issue by w0mbat** [kubernetes/kubernetes#24040]
It had a service with type `ClusterIP` and wanted to switch it to type `NodePort`and it failed with the following message:
```The Service "xyz" is invalid.
spec.clusterIP: Invalid value: "": field is immutable````

I deleted the existing service and created the new one which worked fine.

**Comment by bprashanth** [comment]
How did you change it? sounds like you tried to apply an update with clusterIP=="" whereas the Service in the apiserver already had a clusterIP. 

Fyi the easiest way to update a Service is simply to run kubectl edit svcName, and change the one field (in this case Type from ClusterIP to NodePort).

**Comment by w0mbat** [comment]
I just did a `kubectl apply ...`. Using ´kubectl edit` from a CI is not possible so I just wanted to apply the file.
At first it looked like this:
```
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: webapp
```
afterwards:
```
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: webapp
```
