### ISSUE TITLE
kubectl validation fails when creating a non-v1 object in a v1 list

### ISSUE THREAD

**Issue by ghodss** [kubernetes/kubernetes#24089]
In other words, you can't create/replace/delete/apply deployments with kubectl if they're in a list.

Works as expected:

```console
$ cat nginx-rc.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ReplicationController
    metadata:
      name: nginx
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            name: nginx
        spec:
          containers:
            - name: nginx
              image: nginx
$ kubectl create -f nginx-rc.yaml
replicationcontroller "nginx" created
```

Does not work as expected:

```
$ cat nginx-dpl.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: nginx
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            name: nginx
        spec:
          containers:
            - name: nginx
              image: nginx
$ kubectl create -f nginx-dpl.yaml
error validating "nginx-dpl.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false
$ kubectl create -f nginx-dpl.yaml --validate=false
deployment "nginx" created
```

This is a high priority issue for us, since it means we can't (easily) use apply (or any kubectl command) with lists of JSON objects since we've moved all our replication controllers over to deployment objects, which is hampering the UX of our config efforts.

**Comment by AdoHe** [comment]
we just consider the outside group version when we get the schema file for validation. In this example, we will use schema file of this path: `.kube/schema/<version>/api/v1/schema.json`

**Comment by zhouhaibing089** [comment]
Curious about whether it means a v1 `List` could only contains v1 objects.

And what's the difference between a `List` and writing multiple resources into a single file?

**Comment by ghodss** [comment]
@zhouhaibing089 I believe that is the implication, as demonstrated above.

@AdoHe Maybe we should make an exception if the outer type is a List, and recurse one level deeper and fetch schemas for all versions of the objects inside.

**Comment by AdoHe** [comment]
@kubernetes/kubectl need more comments on this:
```
Maybe we should make an exception if the outer type is a List, and recurse one level deeper and fetch schemas for all versions of the objects inside.
```

**Comment by ghodss** [comment]
cc @bgrant0607 @smarterclayton

**Comment by smarterclayton** [comment]
A v1 list can contain any object under the sun.  If validation is assuming a v1 object contains only v1 objects then it's broken.  The Items under a list should be considered `any` in swagger - if we have other objects in the future that can contain opaque objects we're going to need to ensure swagger validation properly identifies sub objects.  Special casing List isn't enough (since there's PodList, ServiceList, etc which are valid for piping from export -> create).

**Comment by bgrant0607** [comment]
cc @lavalamp

**Comment by ghodss** [comment]
Can @smarterclayton or @lavalamp give some guidance on how precisely to solve this in the code? It's a bit of a blocker for us for rolling out applyable config and would be really nice to get into a 1.2.x point release.

**Comment by ghodss** [comment]
It's a blocker because right now a kube list is the only way to enforce ordering of objects when kubectl apply is applied to a directory, and we need to apply namespace objects before the objects that are supposed to be inside of them.

**Comment by lavalamp** [comment]
Looking at this is in my queue, but my queue is long and growing :(

**Comment by lavalamp** [comment]
I tried to reproduce this in a test, but it passes. I will try actually running kubectl on this file next.

**Comment by lavalamp** [comment]
@ghodss what kubectl version are you using?

**Comment by ghodss** [comment]
@lavalamp 1.2.0

**Comment by lavalamp** [comment]
OK, now I understand the issue -- I thought it was more than just the validation problem :)

The problem is that when [create gets a validator](https://github.com/kubernetes/kubernetes/blob/v1.3.0-alpha.2/pkg/kubectl/cmd/create.go#L97) the version for the schema is set in stone at that time. What needs to change is that [the factory](https://github.com/kubernetes/kubernetes/blob/v1.3.0-alpha.2/pkg/kubectl/cmd/util/factory.go#L594) should return a wrapper that implements the validation.Schema which first figures out the version and then chooses the right schema for that version.

**Comment by lavalamp** [comment]
@nikhiljindal to see if he agrees with my suggested solution.

**Comment by nikhiljindal** [comment]
If i understand correctly, [clientSwaggerSchema](https://github.com/kubernetes/kubernetes/blob/v1.3.0-alpha.2/pkg/kubectl/cmd/util/factory.go#L758) that the factory is returning is generic (it is not tied to a particular api group version).
[clientSwaggerShema.ValidateBytes](https://github.com/kubernetes/kubernetes/blob/v1.3.0-alpha.2/pkg/kubectl/cmd/util/factory.go#L911) creates and returns a new [SwaggerSchema](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/schema.go#L64) that has swagger schema for only a particular group version.
SwaggerSchema knows how to [handle all Lists](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/schema.go#L159) (all objects with List suffix). 

We need to update SwaggerSchema to be able to create another SwaggerSchema for a different group version.

**Comment by nikhiljindal** [comment]
There is another way to specify multiple resources without using List: https://github.com/kubernetes/kubernetes/blob/master/hack/testdata/multi-resource-yaml.yaml (Just specify all the resources separated by `---`).

@ghodss Does that work for you?

**Comment by ghodss** [comment]
@nikhiljindal We're using jsonnet to produce valid JSON. It looks like we can theoretically apply a temporary hack where we transform a kube JSON list into JSON objects separated by "---", but that would ideally only be temporary since it complicates our build tooling.

**Comment by AdoHe** [comment]
I agree with what @nikhiljindal suggested, we need to update SwaggerSchema to be able to create another SwaggerSchema when handling list case.

**Comment by smarterclayton** [comment]
We need Lists to work - I think they're fundamental to stuff going forward
(like templates, which are a variant of lists)

**Comment by nikhiljindal** [comment]
cc @pwittrock who is also facing this issue

**Comment by pwittrock** [comment]
I am going to need to fix this for Templates.  Working on this now.

**Comment by errordeveloper** [comment]
I agree with @smarterclayton. We need this to work also. @pwittrock I can see you commits here, how is it coming along?

**Comment by rothgar** [comment]
Was this ever resolved? I see it was closed but still affects me in 1.3.4.

**Comment by AdoHe** [comment]
@rothgar could you give more details?

**Comment by rothgar** [comment]
When I try to install weavescope daemonset from the manifest they provide I run into this error. Their documentation points to this issue as the source of the error.

Here's their manifest. I've also tried splitting this out from a list and making it separate daemonset.yaml and replicationcontroller.yaml with the same error.

```
apiVersion: v1
kind: List
items:
  - metadata:
      labels:
        app: weavescope
        weavescope-component: weavescope-app
      name: weavescope-app
    apiVersion: v1
    kind: ReplicationController
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: weavescope
            weavescope-component: weavescope-app
        spec:
          containers:
            - name: weavescope-app
              image: 'weaveworks/scope:0.17.1'
              args:
                - '--no-probe'
              ports:
                - containerPort: 4040
  - metadata:
      labels:
        app: weavescope
        weavescope-component: weavescope-app
      name: weavescope-app
    apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: app
          port: 80
          targetPort: 4040
          protocol: TCP
      selector:
        app: weavescope
        weavescope-component: weavescope-app
  - metadata:
      labels:
        app: weavescope
        weavescope-component: weavescope-probe
      name: weavescope-probe
    apiVersion: extensions/v1beta1
    kind: DaemonSet
    spec:
      template:
        metadata:
          labels:
            app: weavescope
            weavescope-component: weavescope-probe
        spec:
          hostPID: true
          hostNetwork: true
          containers:
            - name: weavescope-probe
              image: 'weaveworks/scope:0.17.1'
              args:
                - '--no-app'
                - '--probe.docker.bridge=docker0'
                - '--probe.docker=true'
                - '--probe.kubernetes=true'
                - '$(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)'
              securityContext:
                privileged: true
              resources:
                limits:
                  cpu: 50m
              volumeMounts:
                - name: docker-sock
                  mountPath: /var/run/docker.sock
          volumes:
            - name: docker-sock
              hostPath:
                path: /var/run/docker.sock
```
