### ISSUE TITLE
How to execute command without leaving the pod 

### ISSUE THREAD

**Issue by SimoTabtaoui** [kubernetes/kubernetes#24096]
I execute a echo command in my yaml  file, and the pod stop after the echo. how can i run my image with the command ?
```
 command: ["/bin/sh","-c"]
          args: ["echo 'VALIDE_SOLUTION_PATH=/var/test0/Simo/Simo\' > /etc/default/solution"]

```

**Comment by thockin** [comment]
You told us to run "echo", so we ran echo.  If you want us to run something
else, you have to say something else.  What do you want it to run?

You might try "echo yourmessage > file && othercommand" or maybe bundle
that all into a /run.sh script?

**Comment by SimoTabtaoui** [comment]
thanks @thockin  
my problem is that the pod stop after the execution of the command, i want to execute the command and the image ( application ) continue working 
the command is just for doing some modification in the container. no to execute it only.

**Comment by ncdc** [comment]
If you need configuration to be injected either as environment variables or files, you can create a ConfigMap object and then inject its contents into the pod: http://kubernetes.io/docs/user-guide/configmap/

**Comment by thockin** [comment]
When you specify the "command" you are taking over the default thing to run
(in docker called ENTRYPOINT).  It's not a logic "and", it's a logical
"xor".  One or the other but not both.

So you can either run "echo foo > file; /usr/local/bin/foobar" or you can
put that in a script and run the script.

If you want to inject variables you can use the `Env` block, or do as Andy
suggests and use something like ConfigMap.

**Comment by SimoTabtaoui** [comment]
I didn't get how to use Configmap to solve my prob, so i resolve it with a multi mount, i replace the command echo with a volume wish contain the file :D. 

```
containers:
        - name: myfirst
          image: Server
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8081
            protocol: TCP
          args:
             - --apiserver-host=http://192.168.230.92:8888
          volumeMounts:
          - mountPath: "/opt//data"   # data files
            name: mypd
          - mountPath: "/etc/default"   #configuration files
            name: mypd2	 
        volumes:
        - name: mypd
          persistentVolumeClaim:
             claimName: myclaim-1
        - name: mypd2
          persistentVolumeClaim:
             claimName: myclaim-2
```
