### ISSUE TITLE
Cannot delete pods associated with a former deployment

### ISSUE THREAD

**Issue by marcolenzo** [kubernetes/kubernetes#24137]
I am in a state where I have PODs which are being automatically replaced even though there is no RC or Deployment associated with them.

I am using Kubernetes 1.2.0

```shell
[marcol@kube-master deployments]$ kubectl get rc
[marcol@kube-master deployments]$ kubectl get deployment
[marcol@kube-master deployments]$ kubectl get pods
NAME                                            READY     STATUS    RESTARTS   AGE
xyz-deployment-3326926642-5iyvw   0/1       Running   3          9m
xyz-deployment-3326926642-d30ja   0/1       Running   5          10m
xyz-deployment-347725808-91yg0    0/1       Running   4          10m
xyz-deployment-347725808-xxk24    0/1       Running   5          10m

[marcol@kube-master deployments]$ kubectl delete pod xyz-deployment-3326926642-5iyvw
[marcol@kube-master deployments]$ kubectl get pods
NAME                                            READY     STATUS              RESTARTS   AGE
xyz-deployment-3326926642-4vaq5   0/1       ContainerCreating   0          4s
xyz-deployment-3326926642-5iyvw   0/1       Terminating         5          12m
xyz-deployment-3326926642-d30ja   0/1       CrashLoopBackOff    6          14m
xyz-deployment-347725808-91yg0    0/1       Running             6          14m
xyz-deployment-347725808-xxk24    0/1       Running             7          14m
```

The sequence that caused the issue from me was:

1- Create deployment xyz-deployment
2- Replace deployment with an updated version of xyz-deployment
3- Delete deployment before its pods are considered ready

My deployment definition is the following:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: xyz-deployment}
spec:
  replicas: 2
  template:
    metadata:
      labels: {app: xyz, build: '12343242323'}
    spec:
      containers:
      - name: xyz
        image: 10.239.32.81:5000/xyz:0.2.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 20040
        - containerPort: 25701
        readinessProbe:
          httpGet:
            path: /manage/health
            port: 20040
          initialDelaySeconds: 60
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /manage/health
            port: 20040
          initialDelaySeconds: 60
          timeoutSeconds: 3
```
