### ISSUE TITLE
Deployments with overlapping selectors thrash pods

### ISSUE THREAD

**Issue by rileylark** [kubernetes/kubernetes#24152]
A developer accidentally made two deployments with labels that overlapped, such that one of the deployment's selectors matched the pods from both deployments.  In the repro below the labels are exactly the same, but this also happened one one set of labels is a subset of another.

Expected: An error?

Actual: **Cluster CPU went past 100% and everything else broke.** Crazy thrashing with kubernetes shutting down pods & restarting new ones so quickly that we could not even get logs. They never made it past the Pending state. 

We are running kubernetes 1.2 on GKE. Here's a minimal repro, just apply it (on a cluster you don't need!  D: )

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: d1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        duplicate-key: duplicate-value
    spec:
      containers:
        - image: busybox
          name: c1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: d2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        duplicate-key: duplicate-value
    spec:
      containers:
        - image: busybox
          name: c2
```
