### ISSUE TITLE
Is hostPath broken in 1.2.2?

### ISSUE THREAD

**Issue by iamthemuffinman** [kubernetes/kubernetes#24237]
I'm trying to have kubelet start an etcd pod (etcd.yaml pod definition here: http://hastebin.com/davifuwuzi.sm) and it keeps giving me this error: "only encoded map or array can be decoded into a struct." If I remove "hostPath" or the "volumes" map entirely then it works just fine. I'm using kubelet version 1.2.2.

**Comment by iamthemuffinman** [comment]
I should also note that I've also done this:

```yaml
volumes:
    - hostPath: /var/log
        path: /var/log
      name: varlog
    - hostPath: /var/etcd/data
        path: /var/etcd/data
      name: varetcddata
```

And I get this error: "mapping values are not allowed in this context" even though it's done that way [here](https://github.com/kubernetes/kubernetes/blob/release-1.2/cluster/saltbase/salt/kube-proxy/kube-proxy.manifest).
