### ISSUE TITLE
gcePersistentDisk not usable with MySQL on GKE

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/kubernetes#24255]
Hi,

I was testing this [example](https://cloud.google.com/container-engine/docs/tutorials/persistent-disk/) on GKE.

Turns out the Mysql pod is not running properly with gcePersitentDisk. Mysql starts but the environment variable are not dealt with properly and the root password is not used. The database runs but I cannot access it.

Here is the problematic pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: mysqlgce
  labels:
    name: mysqlgce
spec:
  containers:
  - image: mysql
    name: mysqlgce
    env:
    - name: MYSQL_ROOT_PASSWORD
      # Use secrets instead of env for passwords
      value: password
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    # name must match the volume name below
    - name: mysql-storage
      # mount path within the container
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-storage
    gcePersistentDisk:
      pdName: mysql-disk
      fsType: ext4
```

Mysql runs but I get access denied with the root password:

```
$ kubectl exec -ti mysqlgce -- /bin/bash
root@mysqlgce:/# mysql -u root -ppassword
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
root@mysqlgce:/#
```

My disk does exists and is mounted in the pod:

```
$ gcloud compute disks list
NAME                          ZONE           SIZE_GB TYPE        STATUS
...
mysql-disk                    europe-west1-c 50      pd-standard READY
```

Strangely the same Pod with an emptyDir volume works fine:

```
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - image: mysql
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      # Use secrets instead of env for passwords
      value: password
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    # name must match the volume name below
    - name: mysql-storage
      # mount path within the container
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-storage
    emptyDir: {}
```

I can access the DB:

```
$ kubectl exec -ti mysql -- /bin/bash
root@mysql:/# mysql -u root -ppassword
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.12 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

At the very least the example is wrong somewhere.

Any help is much appreciated.

**Comment by lavalamp** [comment]
@saad-ali do people still need to format GCE PDs? Is that the problem here?

**Comment by sijnc** [comment]
I'm using gcePD with PV and PVC and a Deployment on GKE and it works. I had an issue where I had to chown -R mysql:mysql ./mysql/ (/var/lib/mysql) because it was set to 501 staff, instead of mysql for some reason. Also I mount the gcePD in a regular Google cloud machine outside of Kubernetes and do the formatting manually before I attach to k8s.

**Comment by saad-ali** [comment]
> @saad-ali do people still need to format GCE PDs? Is that the problem here?

No, volumes are [automatically formatted](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gce_pd/gce_util.go#L93) if they are not already formated.

**Comment by saad-ali** [comment]
I wonder if  this is a permissions issue like @sijnc mentioned. Might be worth trying his suggestion.

Just for the sake of debugging could you `echo $MYSQL_ROOT_PASSWORD` to verify the environment variable is set correctly

**Comment by sijnc** [comment]
@saad-ali Glad to know about the FormatAndMount, will save some time... Would it be possible to also have Kubernetes run safely run resize2fs on a PD during FormatAndMount if the size has changed, or could that cause issues?

**Comment by sijnc** [comment]
@runseb If you want to discuss the issue your having hit me up on the kubernetes slack channel, same username.

**Comment by saad-ali** [comment]
> Would it be possible to also have Kubernetes safely run resize2fs on a PD during FormatAndMount if the size has changed

Supporting automatic resizing is something we've considered. The design needs to be thought through--what are the triggers, how does it interact with PV/PVC objects, what edge cases to watch out for, etc. Definitely something we should support, but lower on the priority list at the moment.

**Comment by runseb** [comment]
@sijnc if you check the URL of the example I mention, they don't use PV or PVC.

@saad-ali the MYSQL_ROOT_PASSWORD is properly set in the environment and the volume has the proper mysql/mysql permissions.

That's why I am filing the bug :) I am out of ideas...

**Comment by zhulinhong** [comment]
UP
Is there a schedule to add this feature ? We also pay attention to this.
THX. @saad-ali

**Comment by matchstick** [comment]
@saad-ali @erictune @bprashanth Any thoughts on this Issue? I know some of you are looking at stateful workloads.

**Comment by bprashanth** [comment]
suggest modifying your config to include: 
```yaml
name: mysqlgce
command:
- sh
- -c
- "while true; do sleep 1; done"
```

Then running `kubectl exec -it mysql-pod-name /bin/bash`, `env`, `/entrypoint.sh mysqld` ...you get the idea.
