### ISSUE TITLE
HTTP liveness probe always fails with "connection refused" even though URL works without it

### ISSUE THREAD

**Issue by dbbernstein** [kubernetes/kubernetes#24306]
```
Kubernetes version: 1.2.1
Cloud provider: GKE
Docker version: 1.9.1
OS: Debian (3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux)
```

I have a pretty simple and ordinary configuration: a service and replication controller each for a database and a tier of load-balanced external web servers. I can bring it up fine without any liveness or readiness checks, having tried both one and two replicas for the web tier. I tried adding liveness and readiness probes and they both repeatedly fail with "connection refused" with the web servers set to just one replica. When I remove both checks and re-create the web server replication controller, it works again. In fact, it works until the probe hits the failure threshhold, at which point the container goes into an endless restart loop and becomes unaccessible. For debugging, I removed the readiness probe (which was HTTPS for an application-specific URL) and just left the liveness probe in -- it still has the same refused connection problem. The URL being used is a straightforward HTTP GET of the web root: HTTP, port 80, path /.

Looking for similar problems, I found some discussion of this sort of thing occurring when the timeout was too short, so I've moved the timeout from 5 seconds to as high as 25 seconds with no change. I also saw some mention of problems with DNS, but I'm not (I think) using anything explicitly out of the ordinary there. On the theory that perhaps some (virtual) machine had used up all usable connections, I destroyed the whole setup and re-created the virtual machine and cluster; this also did not fix the problem.

From kubelet.log:

```
I0414 19:41:05.020018    3338 server.go:1096] GET /stats/summary/: (5.710163ms) 200 [[Go-http-client/1.1] 10.168.1.6:42415]
I0414 19:41:14.404857    3338 server.go:1096] GET /healthz: (26.803µs) 200 [[curl/7.26.0] 127.0.0.1:45860]
I0414 19:41:24.402257    3338 prober.go:104] Liveness probe for "omgf-rc-r0vo0_default(61ed247a-0278-11e6-aa13-42010af000e6):omgf-container" failed (failure): Get http://10.168.0.3:80/: dial tcp 10.168.0.3:80: connection refused
```

This repeats over and over until the failure threshold is reached, k8s concludes the node is no good, and restarts it, ad infinitum.

The definition of the liveness probe is:

```
livenessProbe:
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  initialDelaySeconds: 30
  # problems with "connection refused", "use of closed network connection"
  # "Increasing the probe timeout to 15 seconds solved this for me, thanks for the suggestion."
  # https://github.com/kubernetes/kubernetes/issues/19904
  timeoutSeconds: 25
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 10
```

The URL is accessible from the web browser on my PC via the external static IP address associated with the load balancer ingress, until, of course, k8s decides that the node is no good. The readiness probe (HTTPS to an application-specific URL) exhibits the same symptoms when added, but the liveness probe fails with or without the readiness probe. With neither probe defined, the system comes up happily, except that that's not desired behavior for me since in addition to not having the protection of the probes, the nodes are exposed before ready.

I've spent a couple days playing with this and looking for a similar problem or related instructions but haven't been able to find anything obvious in either bug reports or documentation. If I've missed it, I'll certainly appreciate the appropriate RTFM pointer. If I've missed reporting any salient information, please let me know what more is needed.
