### ISSUE TITLE
Termination message guide does not work 

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#24318]
I followed this guide http://kubernetes.io/docs/user-guide/production-pods/#termination-message, and test it against 1.2.2 release.

`.lastState.terminated.message` returns `<no value>`

I can see that `lastState` has no `message` filed:
```
- containerID: docker://fac24b3785dc4d37a0cd8ffd82160c28d7f12375a3d3c564d6dd47390ffb0041
    image: busybox:latest
    imageID: docker://bc744c4ab376115cc45c610d53f529dd2d4249ae6b35e5d6e7a96e58863545aa
    lastState:
      terminated:
        containerID: docker://fac24b3785dc4d37a0cd8ffd82160c28d7f12375a3d3c564d6dd47390ffb0041
        exitCode: 0
        finishedAt: 2016-04-15T06:51:02Z
        reason: Completed
        startedAt: 2016-04-15T06:50:02Z
    name: messager
    ready: false
    restartCount: 4
    state:
      waiting:
        message: Back-off 2m40s restarting failed container=messager pod=pod--message_default(077cd810-02d5-11e6-b8fe-080027532ca8)
        reason: CrashLoopBackOff
```

I can confirm that `/dev/termination-log` is created and mounted.

btw, I did not look into where `lastState` is set in kubelet, for now I consider this inconsistency as a issue.
