### ISSUE TITLE
Deleting and recreating a ThirdPartyResource fails

### ISSUE THREAD

**Issue by 0x777** [kubernetes/kubernetes#24591]
```bash
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2+coreos.0", GitCommit:"b7381e5f631654f3a9459c6fe24f75005e28233a", GitTreeState:"clean"}
```

`route-resource.yaml`

```yaml
metadata:
  name: route.hasura.io
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A specification to expose services"
versions:
- name: v1
```
1. Create the resource

  ```bash
  $ kubectl create -f route-resource.yaml
  thirdpartyresource "route.hasura.io" created
  $ curl http://127.0.0.1:8001/apis/hasura.io/
{
  "kind": "APIGroup",
  "apiVersion": "v1",
  "name": "hasura.io",
  "versions": [
    {
      "groupVersion": "hasura.io/v1",
      "version": "v1"
    }
  ],
  "preferredVersion": {
    "groupVersion": "",
    "version": ""
  },
  "serverAddressByClientCIDRs": null
 }
  ```
2. Delete the resource

  ```bash
  $ kubectl delete -f route-resource.yaml
thirdpartyresource "route.hasura.io" deleted
  ```
3. Create the same resource again

 ```bash
  $ kubectl create -f route-resource.yaml
  thirdpartyresource "route.hasura.io" created
  $ curl http://127.0.0.1:8001/apis/hasura.io/
  {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}
```

I was deleting the third party resource as the controller-manager wouldn't start (#24380).
