### ISSUE TITLE
how can get the hostIP in a pod

### ISSUE THREAD

**Issue by Aleishus** [kubernetes/kubernetes#24657]
I want to get the hostIP in a pod through the downward API，but failed this my error：
  
  “spec.template.spec.containers[0].env[2].valueFrom.fieldRef.fieldPath: invalid value 'status.hostIP', Details: error converting fieldPath”

**Comment by thockin** [comment]
It's not currently exposed, but we're gathering information about why
people want stuff like this, so we can find a good answer.  What are you
hoping to do with that?

**Comment by Aleishus** [comment]
Thank you @thockin . I use logstash as a daemonset pod for log collection . I want to get more node's information from this pod and put them into logstash,so that I can know where the logs comes from.

**Comment by Aleishus** [comment]
Thank you @thockin . I use logstash as a daemonset pod for log collection . I want to get more node's information from this pod and put them into logstash,so that I can know where the logs come from.

**Comment by therc** [comment]
The IP is not exposed, because it would e.g. prevent live migrations of pods one day, but perhaps daemonsets could be an exception, because of their very nature? 

We have a monitoring daemon on every node and wanted pods to report to the local agent. We solved that by having them contact a static IP, whose traffic gets rerouted to the local agent through an iptables rule.

**Comment by Aleishus** [comment]
I know thanks

**Comment by jeremyong** [comment]
Can we reopen this? I think pods that are known to be 1-1 with the host in high performance applications should be able to understand their own public IPs to publish if they want.

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/27880 merged this week, so
1.4 will allow the node name to be known.

**Comment by jeremyong** [comment]
Thanks for the response @thockin . Forgive my ignorance but even if I have the node name, how do I discover the public IP bound to the node? Is the instance metadata querying even available within the pod? Or are people in the issue you linked referring to a different API?

**Comment by thockin** [comment]
Sorry, you need the PUBLIC IP?  you have to go through some
provider-specific API, such as metadata to get that...

**Comment by jeremyong** [comment]
In the case when I am enabling host networking on the pod so that the underlying host's network stack is used, shouldn't the host IP be available? I just now found #6558 which describes some of the concerns (multiple network interfaces etc) but it seems like the decision was to just remove the feature altogether instead of moving forward and handling the edge cases.

What I'm opting to do instead is add an additional boostrapping step to each node to expose information like public ips in a file and mounting it as a volume but this really feels like an ugly workaround. I should mention (not that it matters necessarily) that I'm using GKE at the moment.

**Comment by thockin** [comment]
that issue was about the node's IP, but not necessarily a PUBLIC address.
If you use host networking you can just look at the interfaces and get the
IP?

**Comment by sirhopcount** [comment]
I might also have a use case for this. I want containers to be able to reach the etcd (proxy) on the node they are running on. That way services in the containers can register them selfs with the etcd cluster.

I could use host networking but that seems overkill to me for exposing a service on the node.

What I really want to be able to do is to set an env var with the public ip of the node the pod is running on.

**Comment by thockin** [comment]
With kube 1.4 you can get the node's name, which is usually resolvable.
Sufficient?

On Wed, Sep 7, 2016 at 12:21 PM, Adrian van Dongen <notifications@github.com

**Comment by sirhopcount** [comment]
Yes that would also fix my problem. 

Just out of curiosity, what the reasoning for not exposing the entire API to  a manifest? Don't really see the harm in exposing the same data as one is able to fetch via for example kubectl.

**Comment by Bregor** [comment]
`status.hostIP` is valuable for DaemoSets, for example.
In my case, I want to listen with Prometheus's node_exporter and weave scope only on the host.IP which is a private address of the node.

**Comment by kayrus** [comment]
As soon as I understand it is enough to add extra value in this list:
https://github.com/kubernetes/kubernetes/blob/313ef63993017597bd28f5efd23677820274cb58/pkg/api/validation/validation.go#L1320

**Comment by thockin** [comment]
node name is available as DownwardAPI as of 1.4

**Comment by Bregor** [comment]
@thockin but what is the reason not to add extra values to `validFieldPathExpressionsEnv`?

**Comment by thockin** [comment]
Just to make sure we curate that well.

**Comment by cemo** [comment]
@thockin I don't want to open a new issue but I have some similar requirements as others. Our fluentd agent is collecting data from docker logs file but I would like to feed by socket. docker files has docker id in filename but I need to access in k8s environment. Is there a way to get it?

**Comment by thockin** [comment]
At this point, I guess I am open to adding `status.hostIP`, if someone can
write the PR (should be easy, tests are a bit more complex)

**Comment by cemo** [comment]
@thockin I was referring `container-id`. I think that you did not reply to me. :)

**Comment by thockin** [comment]
container-id is significantly harder, since the ID isn't known until after
the container starts, but by then it is too late to make changes to things
like env vars.

**Comment by cemo** [comment]
I was looking this answer. Thank you so much.

**Comment by chen-anders** [comment]
> At this point, I guess I am open to adding `status.hostIP`

This would work for our use case (as local node names don't resolve in our local VM though they do in our AWS cluster). While it seems pretty trivial to add an additional value to pkg/api/validation/validation.go, I'm not exactly sure where the corresponding tests should be aside from an additional validator around here: https://github.com/kubernetes/kubernetes/blob/313ef63993017597bd28f5efd23677820274cb58/pkg/api/validation/validation_test.go#L2324

**Comment by andrewsykim** [comment]
Does hostIP refer to pod ip or node ip? If pod IP can we also consider supporting nodeIP via downward API? My use case is pushing metrics to a daemonset and having to know its IP to do so.

**Comment by thockin** [comment]
podIP is already supported.  This is about hostIP

**Comment by andrewsykim** [comment]
@chen-anders were you working on a PR for this? If not I don't mind giving it a shot :)

**Comment by chen-anders** [comment]
@andrewsykim - I haven't been able to get to this yet.

**Comment by andrewsykim** [comment]
@thockin opened https://github.com/kubernetes/kubernetes/pull/42717 for this. For the most part I took your advice and did a search for `status.podIP` and added `status.hostIP` where possible. 

p.s. super excited for your talk at cloud next :)

**Comment by ajit-sarnaik** [comment]
Any idea when host_ip will be supported please.

**Comment by yaronha** [comment]
@thockin following our discussion this week, any update on getting status.hostIP via downward API?
we need it to try and connect to local Daemon if it exists, had to use host volume w hacks to get it 

Yaron

**Comment by andrewsykim** [comment]
@ajit-sarnaik @yaronha support for status.hostIP was added in this PR https://github.com/kubernetes/kubernetes/pull/42717. It should be included in the 1.7 release.

**Comment by thockin** [comment]
@yaronha I told you I thought it was in :)

**Comment by rachlenko** [comment]
@thockin How I've waited for this moment. Thank you :)

**Comment by oliverisaac** [comment]
> We have a monitoring daemon on every node and wanted pods to report to the local agent. We solved that by having them contact a static IP, whose traffic gets rerouted to the local agent through an iptables rule.

I needed to solve the same problem and was able to do so using the below daemonset. This daemonset adds an iptables rule to every node which causes all traffic sent to the Magic IP `192.168.168.168` to be re-routed back onto the node. I then exposed the node-local agent (apm-server in my case) as a NodePort and my clients can talk to their sibling DaemonSet pod/agent (running on the same node) by connecting to `192.168.168.168:$NODEPORT`.

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: add-iptables-rule
  name: add-iptables-rule
spec:
  selector:
    matchLabels:
      app: add-iptables-rule
  template:
    metadata:
      labels:
        app: add-iptables-rule
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          export CHECKPOINT_PATH="/tmp/$( echo "$STARTUP_SCRIPT" | sha256sum | awk '{print $1}' ).checkpoint"
          echo "PATH: $CHECKPOINT_PATH" >&2
          /bin/bash /manage-startup-script.sh
        env:
        - name: STARTUP_SCRIPT
          value: |
            #!/bin/bash

            set -o errexit
            set -o pipefail
            set -o nounset

            echo Starting >&2
            # Route all hits to 192.168.168.168 to the node. this allows us to have a static IP for each node
            if ! iptables-save 2>&1 | grep -q 192.168.168.168; then
              iptables -t nat -A PREROUTING -d 192.168.168.168/32 -p tcp -j KUBE-HOSTPORTS
            fi
            echo done >&2
        image: gcr.io/google-containers/startup-script:v1
        imagePullPolicy: Always
        name: startup-script-v2
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      hostPID: true
      restartPolicy: Always
```
