### ISSUE TITLE
deployments does not support (honor) containers restartPolicy 

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes/kubernetes#24725]
Steps: Create deployment file and set restartPolicy to "Never"
Result: 
```
The Deployment "foo" is invalid.
spec.template.spec.restartPolicy: Unsupported value: "Never": supported values: Always
```

**Comment by AdoHe** [comment]
@kubernetes/kubectl we should document what restart policy deployment support.

**Comment by janetkuo** [comment]
@ichekrygin Deployments only support restartPolicy = `Always`; so do Replication Controllers, Replica Sets, and Daemon Sets. 

I'll document this.

**Comment by kachkaev** [comment]
Sorry for a late follow up, but what if I'd like to deliberately kill the pods instead of restarting? I've got a deployment with pods that are somewhat buggy. They do not restore themselves well after one of the containers fails and thus my deployment becomes unstable after some time. How can I maintain a Deployment (and consequently a ReplicaSet) that would kill and recreate failing Pods rather than restarting them?

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-apps-feature-requests

**Comment by kargakis** [comment]
@kachkaev https://github.com/kubernetes/kubernetes/issues/13488 is related to what you are asking.

**Comment by kachkaev** [comment]
Probably not quite. Rolling restart seems to be something triggered by a user, while what i’m asking is pod recreation on failure (rather than a restart).

**Comment by yuedai** [comment]
I have a similar requirement. @kachkaev

**Comment by mattmb** [comment]
Does anyone know *why* deployments only support restartPolicy == Always? It's not clear from the documentation and I can't spot the reason easily in the code.

I think there are legitimate use cases for "Never". For example, I have a pod running on a node and it has a liveness probe. That node then fails in someway that makes it remain up but perform slowly. The liveness probe fails and the kubelet will now try to recreate the container. But the problem is with the node so the new container doesn't become healthy. And my ReplicaSet doesn't see the pod as failed so it doesn't try to create a new pod elsewhere.

If I could set the restart policy to Never then I imagine in this scenario: liveness probe fails, container terminated, pod marked as failed, replica set creates a new pod (maybe or maybe not on the same node).

Or have I mis-understood something?

**Comment by kyessenov** [comment]
Another example that is difficult to handle: sidecars and sidecar proxies, in particular. If an application container does not properly clean up after itself (e.g. UDS sockets), then the pod stays alive since the sidecar is still running. The application keeps trying to restart, and keeps failing since it attempts to use some resources that have not been cleaned up.

**Comment by llech** [comment]
If deploymets support only restartPolicy: Always, why do that parameter exists at all?
It doesn't make much sense to have a 'parameter' that can have only one value...

What is the alternative for running one-time or periodic tasks, like data import or backups?

**Comment by rcsavage** [comment]
> If deploymets support only restartPolicy: Always, why do that parameter exists at all?
> It doesn't make much sense to have a 'parameter' that can have only one value...
> 
> What is the alternative for running one-time or periodic tasks, like data import or backups?

I totally agree, there's no need for the parameter if it's behaves like this.

**Comment by chrisghill** [comment]
I also have a use case like @kachkaev where I would prefer to have a pod die and be rescheduled as a new pod than be restarted.  This feature would be useful.

**Comment by kaneg** [comment]
I was also confused by the failed message which said 'Unsupported value: "Never": supported values: "Always"'.
There is no any document saying that the flag can't be supported by Deployment.

**Comment by 2PacIsAlive** [comment]
This has me so confused. I am creating a deployment that automatically creates a replicaset - I am not creating the replicaset directly. How do I get that replicaset to have `restartPolicy` `Never`?

**Comment by symonsoft** [comment]
I'm experiencing the same problem. Uh three years since ticked opened. I think the worst decision in my life is the decision to use fkn Kubernetes at all. The worst product ever.

**Comment by SummerShoohaw** [comment]
I'm experiencing the same problem +1, we have some sidecars running in our pod which will keep running forever, and the we want the pod to fail and restart if the primary container failed.

**Comment by janpaul123** [comment]
Sounds like this should get addressed by https://github.com/kubernetes/enhancements/pull/912. My workaround for now has been to set up a ServiceAccount that can delete pods, and then run `kubectl delete pods $HOSTNAME` from within my container.

**Comment by wuestkamp** [comment]
I would also like to completely start a new pod instead restarting. @janpaul123 your workaround sounds ugly as hell, but thanks for suggestion ;)

**Comment by AKCen** [comment]
I wonder this thing was raised 3 years back and why is documentation here https://v1-12.docs.kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy says 

```
A PodSpec has a restartPolicy field with possible values Always, OnFailure, and Never. 
```

while I get 

```
... is invalid: spec.template.spec.restartPolicy: Unsupported value: "Never": supported values: "Always"
```

kubectl version

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by 0marq** [comment]
> Only a .spec.template.spec.restartPolicy equal to Always is allowed, which is the default if not specified.

The doc says only Always is supported for Deployments

You might want to consider switching to a Job 

> Only a RestartPolicy equal to Never or OnFailure is allowed.

See 
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-template

**Comment by felix0080** [comment]
why closed,this issue is important

**Comment by wuestkamp** [comment]
I also think it would be great to reopen this.

**Comment by z-oo** [comment]
Please reopen because this is critical and particularly bad when combined with unstable volumne mount bug like this: https://github.com/kubernetes/kubernetes/issues/67643 or a dead fuse daemon.

If any volumne mount is broken for a pod, we have no choice but restarting the whole pod. We have put liveness probe and in code health check to commit suicide after write failure or any mountpoint abnormality. But if restartPolicy is always, the pod simply enters crashloop without restarting itself.

We used to be able to set "Never" on deployments and it works as expected. However recently we found that this has been enforced and our existing mechanism stops working.

Another possible solution is to add a time limit of crashloopbackoff and kill the pod after limit. We can write a script to do so but it would be better if it can be built into the official controller or kubelet.

**Comment by yurilaaziz** [comment]
hope this comes true. I would like to avoid seeing failed deployment with 200x pod restarts,
Okay to keep restartPolicy to Always as default.
but forcing Never will help.

**Comment by tommyjcarpenter** [comment]
why is this issue closed? how do I get k8s to not restart a pod? what is the point of a parameter if it can only take one value?

**Comment by Nitesh-vaidyanath** [comment]
+1 Our application is designed in such a way if container crash it will fail to start again.  We need option "spec.template.spec.restartPolicy" : "Never".

**Comment by sinchanroy** [comment]
+1, our pods gets restarted 200x in case of errors and eating up much of resources. I would voteup for this issue

**Comment by junneyang** [comment]
+1 Our application is designed in such a way if container crash it will start again, if not we want to just ignore the health check error,  We need option "spec.template.spec.restartPolicy" : "OnFailure".

**Comment by bronger** [comment]
My backup pod contained a bug and restarted over and over again, wearing out the backup disk. This is not good! And any remedy is more complicated than being able to set restartPolicy=Never.

**Comment by fara-nak** [comment]
Please open this, we need the pod not to restart, what's the point of "Never" if we can't use it?

**Comment by bronger** [comment]
Well, to be fair, the parameter exists because it is inherited from pod spec. A deployment spec contains a pod spec with some constrains, one of them being that restartPolicy can only be Never.

I *think* the reasoning behind this is that deployments are not jobs.  Like a container must be able to cope with the fact that it can be shut down at any time, a deployment must be able to cope with the fact that it is kept alive by restarts.

**Comment by huide9** [comment]
+1 need it can be configured as onFailure or Never.  Always is not fit for the real case here.

**Comment by amboowang** [comment]
+1 need it can be configured as onFailure or Never. Always is not fit for the real case here.

**Comment by NovaHe** [comment]
+1 need it can be configured as onFailure or Never. Always is not fit for the real case here.

**Comment by persunde** [comment]
Please add onFailure and Never.
+1 need it can be configured as onFailure or Never. Always is not fit for the real case here.

**Comment by bronger** [comment]
Please don’t spam.

**Comment by viniciusd** [comment]
> Only a RestartPolicy equal to Never or OnFailure is allowed.



> > Only a .spec.template.spec.restartPolicy equal to Always is allowed, which is the default if not specified.
> 
> The doc says only Always is supported for Deployments
> 
> You might want to consider switching to a Job
> 
> > Only a RestartPolicy equal to Never or OnFailure is allowed.
> 
> See
> https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template
> https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-template

Jobs are immutable, I need a run-to-completion that can be shot again and again whenever I want.

**Comment by rainerfrey** [comment]
Comments in this issue mix to separate aspects:
* run-to-completion or fail-and-exit use cases (these are addressed by Jobs)
* use cases that want to keep the application running, but require the restart of the entire pod instead of just the container
The second case doesn't seem to be addressed in any way yet. Another example for that is: a main container, that needs the action of an init container to be run on every start.

**Comment by viniciusd** [comment]
>     * run-to-completion or fail-and-exit use cases (these are addressed by Jobs)
> 
The issue with jobs for me is the fact one can't run a job with the same name. Even if I use a plugin that adds random gibberish to the job name, they are going to be pilling up in the cluster. Lots of pollution after some time.

**Comment by wuestkamp** [comment]
We did need the use case: `want to keep the application running, but require the restart of the entire pod instead of just the container`.

For this we let our main container, after its done, contact the K8s api to delete its own Pod (without gracePeriod) which causes a new Pod to be created.

Example here, but stripped down so not sure if working just like that:



```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      id: agent
  template:
    metadata:
      labels:
        id: agent
    spec:
      serviceAccountName: agent
      containers:
      - name: sidecar
        image: sidecar
        command: ["./sidecar"]
      - name: agent
        image: agent
        command:
        - /bin/sh
        - -c
        - >
          ./agent; # processes one message then exits
          curl -m 10 -k -X DELETE --data '{"gracePeriodSeconds":0,"propagationPolicy":"Background"}' -H "Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)" -H 'Accept: application/json' -H'Content-Type: application/json' https://kubernetes.default/api/v1/namespaces/$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)/pods/$(hostname);
          sleep 10 # awaiting death while sleeping

```
