### ISSUE TITLE
kube2sky Waiting for service: default/kubernetes timeout

### ISSUE THREAD

**Issue by Aleishus** [kubernetes/kubernetes#24842]
### I use skydns, the kube2sky can't get the response form the apiserver.

  `
 I0427 10:40:42.758130    7114 kube2sky.go:445] Etcd server found: http://192.168.46.40:4001
I0427 10:40:43.759542    7114 kube2sky.go:512] Using http://192.168.56.191:8080 for kubernetes master
I0427 10:40:43.759570    7114 kube2sky.go:513] Using kubernetes API v1
I0427 10:40:43.759732    7114 kube2sky.go:581] Waiting for service: default/kubernetes
F0427 10:40:53.816543    7114 kube2sky.go:377] Failed to mutate etcd for 10s using mutator: 0x409170
`

### but the the apiserver has already received the kube2sky's request 
`
6564 handlers.go:152] GET /api/v1/namespaces/default/services/kubernetes: (2.254833ms) 200 [[kube2sky/v1.2.3 (linux/amd64) kubernetes/$Format] 192.168.56.191:35209] 
`

### what's wrong ? Someone help me please.

**Comment by thockin** [comment]
Can you please provide more information?  What cloud?  What version of
kubernetes?  What instructions did you follow for setup and for DNS?  What
flags are you using on kube2sky?

**Comment by Aleishus** [comment]
* k8s  cluster version: 1.2.2
* env: centos 7 bare metal
* I follow the [skydns.rc] (https://github.com/kubernetes/kubernetes/blob/release-1.2/cluster/addons/dns/skydns-rc.yaml.in) and just rename the image name in my private registry

  ```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v11
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 2
  selector:
    k8s-app: kube-dns
    version: v11
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v11
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube2sky
        image: 192.168.46.21:5000/zhouxi/kube2sky
        resources:
          limits:
            cpu: 350m
            # Kube2sky watches all pods.
            memory: 300Mi
          requests:
            cpu: 300m
            memory: 300Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
            scheme: HTTP
          # we poll on pod startup for the Kubernetes master service and
          # only setup the /readiness HTTP server once that's available.
          initialDelaySeconds: 30
          timeoutSeconds: 5
        args:
        # command = "/kube2sky"
        - --domain=tmd
        - --kube-master-url=http://192.168.46.40:8080
        - --etcd-server=http://192.168.46.40:4001
        - --etcd-mutation-timeout=20
      - name: skydns
        image: 192.168.46.21:5000/zhouxi/skydns
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 200Mi
        args:
        # command = "/skydns"
        - -machines=http://192.168.46.40:2379
        - -addr=0.0.0.0:53
        - -ns-rotate=false
        - -nameservers=192.168.45.10:53
        - -domain=tmd
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      - name: healthz
        image: 192.168.46.21:5000/zhouxi/exechealthz:1.0
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.default.svc.snet 127.0.0.1 >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.


  ```
            
            
            
                
* etcd: 2.2.1 outside the cluster
* flags: ./kube2sky  --domain=tmd --kube-master-url=http://192.168.56.191:8080 --etcd-servers=http://192.168.46.40:4001  

##### container  skydns and exechealthz works well ,then I run kube2sky in my host machine but has the same errors
```
[root@localhost kube2sky]# ./kube2sky  --domain=tmd --kube-master-url=http://192.168.56.191:8080 --etcd-servers=http://192.168.46.40:4001
I0427 10:40:42.758130    7114 kube2sky.go:445] Etcd server found: http://192.168.46.40:4001
I0427 10:40:43.759542    7114 kube2sky.go:512] Using http://192.168.56.191:8080 for kubernetes master
I0427 10:40:43.759570    7114 kube2sky.go:513] Using kubernetes API v1
I0427 10:40:43.759732    7114 kube2sky.go:581] Waiting for service: default/kubernetes
F0427 10:40:53.816543    7114 kube2sky.go:377] Failed to mutate etcd for 10s using mutator: 0x409170 
```
@thockin
