### ISSUE TITLE
Multi-port services w/ different backends for each port

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#24875]
Assume I have Deployment A that exposes port 4444, and Deployment B that exposes port 5555. I'd like to create Service S, backed by A & B, that exposes both 4444 & 5555.

**Comment by thockin** [comment]
Why?

This is not possible today, and it's pretty complex to describe, and some modes of proxies won't handle it well.

**Comment by cjcullen** [comment]
Came up on SO: http://stackoverflow.com/questions/36885886/wire-multiple-deployments-to-one-service-in-kubernetes

It would allow multiple pods (with different dev velocities) to back a single complex service with a single IP. I can't think of a real concrete case, but consider a service w/ both HTTP & HTTPS ports. I might have my HTTP endpoint doing a simple redirect, with my HTTPS endpoint doing real work, and I may want to deploy those at different times/rates.

Maybe this pattern isn't something we want to encourage.

**Comment by mshockwave** [comment]
Hi, do you mean that the redirecting jobs are still done by the user server program, not kubernetes?

**Comment by thockin** [comment]
This is something that L7 load balancers are better suited for.  While we
can probably do what you describe in our built-in balancer,I doubt if many
other implementations can do it.  It's much more expressive than most VIP
systems I have seen..

**Comment by cjcullen** [comment]
I'm fine with closing this if it isn't a good idea.

**Comment by thockin** [comment]
It's interesting, I just don't think it is practical.

**Comment by tansly** [comment]
Hello people, sorry for bumping up this old issue but I’ve just came across this and got a bit confused. A Stackoverflow user states that exactly the scenario described here works. https://stackoverflow.com/a/50221754

Is the user doing something wrong? Is it not supposed to work that way? Thanks!

**Comment by thockin** [comment]
Unless I am misunderstanding, that Service will select both deployments and will try to route both service ports to both backends.  IOW half the traffic will fail.

There *is* a way to achieve the desired result.  To do this you have to use named ports, rather than numbered (it seems the OP assumed that they behave the same, but they do not).

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      containers:
      - name: nginx
        image: patientplatypus/kubeplayfrontend
        ports:
        - name: frontend
          containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      containers:
      - name: nginx
        image: patientplatypus/kubeplaybackend
        ports:
        - name: backend
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: entrypt
spec:
  type: ClusterIP
  ports:
  - name: backend
    port: 8080
    targetPort: backend
  - name: frontend
    port: 8081
    targetPort: frontend
  selector:
    app: exampleapp

```
