### ISSUE TITLE
Creating HPA using docs/user-guide/replicasets/hpa-rs.yaml fails validation 

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#24973]
```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scaler
spec:
  scaleRef:
    kind: ReplicaSet
    name: frontend
    subresource: scale
  minReplicas: 3
  maxReplicas: 10
  cpuUtilization:
    targetPercentage: 50
```

from [1].

```
$ kubectl create -f hpa.yaml
error validating "hpa.yaml": error validating data: [field scaleTargetRef: is required, found invalid field scaleRef for v1.HorizontalPodAutoscalerSpec, found invalid field cpuUtilization for v1.HorizontalPodAutoscalerSpec]; if you choose to ignore these errors, turn validation off with --validate=false
```

Caused by [2]. Docs needs to be updated.

[1] http://kubernetes.io/docs/user-guide/replicasets/
[2] https://github.com/kubernetes/kubernetes/commit/90c647eff94b5af85d6bb19154b472f73b7784c6

**Comment by ingvagabund** [comment]
cc @piosz @kubernetes/autoscaling @gouyang

**Comment by ingvagabund** [comment]
Simple docs update. Updating the yaml file to:

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scaler
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: frontend
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
```

creates the ``HorizontalPodAutoscaler``.
