### ISSUE TITLE
DNS yaml.in templates assume salt, not sed friendly.

### ISSUE THREAD

**Issue by rboorgapally** [kubernetes/kubernetes#25020]
I get the following error when I try to deploy addons to my kubernetes cluster. 
```
Deploying DNS on Kubernetes
yaml: line 21: found character that cannot start any token
```

I am running a 5 node kubernetes cluster on Azure with Ubuntu 14.04.
The cluster itself is up and running.
I tried to debug this issue and the issue seems to be because of skydns-rc.yaml not being in the right format. When I look at deployAddons.sh, this yaml file is generated from a yaml.in file.
I did a diff of these two files and the following is the output:

```
diff ~/kubernetes/cluster/addons/dns/skydns-rc.yaml.in skydns-rc.yaml
11c11
<   replicas: {{ pillar['dns_replicas'] }}
---
>   replicas: 1
86c86
<         - --domain={{ pillar['dns_domain'] }}
---
>         - --domain=cluster.local
105c105
<         - -domain={{ pillar['dns_domain'] }}.
---
>         - -domain=cluster.local.
124c124
<         - -cmd=nslookup kubernetes.default.svc.{{ pillar['dns_domain'] }} 127.0.0.1 >/dev/null
---
>         - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null

```

**Comment by thockin** [comment]
And what is at line 21?

**Comment by rboorgapally** [comment]
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v11
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v11
    kubernetes.io/cluster-service: "true"
**spec:**
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v11
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v11
        kubernetes.io/cluster-service: "true"
    spec:
{% if grains['cloud'] is defined and grains['cloud'] in [ 'vsphere', 'photon-controller' ] %}
      hostNetwork: true
{% endif %}
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd-amd64:2.2.1
        resources:
          # TODO: Set memory limits when we've profiled the container for large
          # clusters, then set request = limit to keep this container in
          # guaranteed class. Currently, this container falls into the
          # "burstable" category so the kubelet doesn't backoff from restarting it.
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 50Mi
```
