### ISSUE TITLE
kubernetes - FailedSync	Error syncing pod, skipping: configmaps 

### ISSUE THREAD

**Issue by ajohnstone** [kubernetes/kubernetes#25096]
The following errors are occurring despite the volume being mounted.
 * Warning     FailedMount Unable to mount volumes for pod "nginx-ingress-controller-1626740531-88561_default(d125e230-1151-11e6-a2d1-0adbaa6061ff)": configmaps "nginx-template" not found
 * Warning     FailedSync  Error syncing pod, skipping: configmaps "nginx-template" not found

```
Events:
  FirstSeen	LastSeen	Count	From							SubobjectPath				Type		Reason		Message
  ---------	--------	-----	----							-------------				--------	------		-------
  32m		32m		1	{default-scheduler }										Normal		Scheduled	Successfully assigned nginx-ingress-controller-1626740531-88561 to ip-10-115-0-133.eu-west-1.compute.internal
  32m		32m		1	{kubelet ip-10-115-0-133.eu-west-1.compute.internal}						Warning		FailedMount	Unable to mount volumes for pod "nginx-ingress-controller-1626740531-88561_default(d125e230-1151-11e6-a2d1-0adbaa6061ff)": configmaps "nginx-template" not found
  32m		32m		1	{kubelet ip-10-115-0-133.eu-west-1.compute.internal}						Warning		FailedSync	Error syncing pod, skipping: configmaps "nginx-template" not found
  32m		32m		1	{kubelet ip-10-115-0-133.eu-west-1.compute.internal}	spec.containers{nginx-ingress-lb}	Normal		Pulling		pulling image "aledbf/nginx-third-party:0.16"
```

however the configmap exists.
```
$ kubectl get configmaps
NAME                  DATA      AGE
config-secure-proxy   1         1d
nginx-confd           1         26m
nginx-template        1         26m
```

full details: https://gist.github.com/ajohnstone/0b19202e68fef620ad006d9555f7f887

**Comment by ajohnstone** [comment]
incorrect
```
          volumeMounts:
            - mountPath: /etc/nginx/template
              name: nginx-template-volume
              readOnly: true
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-confd-volume
              readOnly: true

```

```
          volumeMounts:
            - mountPath: /etc/nginx/template
              name: nginx-template-volume
              readOnly: true
            - mountPath: /etc/nginx/conf.d
              name: nginx-confd-volume
              readOnly: true
```
