### ISSUE TITLE
Expected behavior for Deployment replicas with HPA during update

### ISSUE THREAD

**Issue by verdverm** [kubernetes/kubernetes#25238]
I am seeing unexpected behavior from a user standpoint when `kubectl apply -f mydeployment.yml`

The existing Deployment has an HPA associated with it and the current replica count is 3. When the deployment is accepted, the number of replicas jumps to 9, then scales down to 6, the value in the deployment. Eventually, the new pods info starts flowing in and the HPA does its thing and scales back to satisfaction.

The behavior I expected is that the rollout would use the current replicas from the HPA and the strategy parameters from the Deployment to keep replica count in line with the current target set by the HPA. 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "40%"
      maxSurge: "50%"
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: "someimage"
```

```
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mydeployment
  namespace: default
spec:
  scaleRef:
    kind: Deployment
    name: mydeployment
    subresource: scale
  minReplicas: 3
  maxReplicas: 12
  cpuUtilization:
    targetPercentage: 50
```

**Comment by DirectXMan12** [comment]
cc @kubernetes/autoscaling 

The scaling of a deployment is based on the `replicas` field.  When the HPA scales a deployment, it also updates the `replicas` field.  AFAICT from your description, what's going on is that the `apply` operation ends up updating the replicas field, and thus is temporarily scaling the deployment manually until the HPA's next sync loop iteration (when the HPA notices the extra replicas, and corrects the replica count).  You should be able to check this by checking (via `kubectl get`) if the replicas field on the deployment changes temporarily after the apply.

**Comment by kargakis** [comment]
@kubernetes/deployment

**Comment by verdverm** [comment]
This is more an issue when we have 20 replicas under load and roll a new Deployment and the replicas go from `20 -> 26 -> 6 -> ... -> 20`

**Comment by bgrant0607** [comment]
@verdverm 

There are multiple issues here.

Do not set the replicas field in Deployment if you're using `apply` and HPA. As mentioned by @DirectXMan12, `apply` will interfere with HPA and vice versa. If you don't set the field in the yaml, `apply` should ignore it.

Also, I'm not sure HPA can be expected to be stable right now with large maxUnavailable and maxSurge values. Maybe try maxUnavailable=0 and maxSurge=1.

Finally, Deployment doesn't do a good job of detecting scaling behavior right now, since it's fairly tricky to do robustly. What I'd like it to do is to distinguish scaling from other changes and then scale proportionally. #20754

**Comment by rosskukulinski** [comment]
I agree with @verdverm - this was unexpected behavior for me as well.  At a minimum, I think the Deployment docs should call this out.

I would like to be able to utilize the same deployment.yml file for both initial deploy and updates (all is done through CI/CD).  It seems like the 'proper' way is to not specify a replicas in the Deployment (defaults to 1?) and apply the HPA profile when launching a new service.

**Comment by verdverm** [comment]
@bgrant0607 @DirectXMan12 

Your suggested changes makes the observed behavior in line with what we were expecting.
Maybe an update to the docs to make this more explicit would be helpful.

Thanks for all your help!

**Comment by bgrant0607** [comment]
I wrote an explanation of apply behavior here:
https://github.com/kubernetes/kubernetes/issues/15894#issuecomment-222194015

**Comment by itajaja** [comment]
>  If you don't set the field in the yaml, apply should ignore it.

@bgrant0607 I am not noticing this. It seems when I `apply` the replica number is set to 0 if I don't specify the number in the file

**Comment by jszczepkowski** [comment]
Are we sure we want to deliver this for 1.6? Not much time left.

As I understand, the problem here lies in `kubectl apply` and no modification in HPA are needed. Please, correct me if I'm wrong.

**Comment by jszczepkowski** [comment]
CC @jszczepkowski

**Comment by kargakis** [comment]
The milestone was probably added for triaging. I don't think we can do anything for 1.6.

**Comment by ichekrygin** [comment]
Hi guys, remove `replicas` from deployment or setting it to `0` does not seem to work (v1.5.6). 
Use-case: 
1. create deployment with `replicas:3`
2. create hpa with `--min=5` 
---
a) applying deployment.yaml with `replicas:0` - removed *all* the pods
b) applying deployment.yaml with `replicas` removed - scaled down deployment to a single pod (default)

**Comment by kargakis** [comment]
@ichekrygin [if replicas is not specified, it will be defaulted to 1](https://github.com/kubernetes/kubernetes/blob/e0ba40b67c76b0734bedafbc547a24b5eedd441f/pkg/apis/extensions/v1beta1/defaults.go#L73)

**Comment by ichekrygin** [comment]
@kargakis - which is expected, however, it does not help with the HPA.`min` and Deployment.`replicas` conflict issue. I assume this is not a trivial issue to figure out what is the source of truth when applying changes to `deployment`. Perhaps, we could leverage Strategy section to preserve current scale settings:
```
  strategy:
    rollingUpdate:
    ...
       keepScale: true
    type: RollingUpdate
```

**Comment by ianrose14** [comment]
FYI `@hubt` on slack pointed out to me that an unspecified `replicas` field will only default to 1 on `create` - "if you do an `apply` though, it will do a patch and not change the existing number if replicas."  My experiments seem to confirm this.

**Comment by ichekrygin** [comment]
@ianrose14 - strange, this is my repro in `v1.6.2` and `v1.6.4`:
```
# kubernetes versions
⋊> ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

# demo deployment (nginx) with 3 pods
⋊> ~ kubectl create namespace demo
namespace "demo" created
⋊> ~ cat nginx.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
⋊> ~ grep replicas nginx.yaml
  replicas: 3

# create deployment
⋊> ~ kubectl create -f nginx.yaml --save-config
deployment "nginx" created
⋊> ~ kubectl -n demo get deploy nginx
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx     3         3         3            3           14s
⋊> ~ kubectl -n demo get pod
NAME                     READY     STATUS    RESTARTS   AGE
nginx-2371676037-84lkj   1/1       Running   0          19s
nginx-2371676037-p1jz5   1/1       Running   0          19s
nginx-2371676037-p51qp   1/1       Running   0          19s

# edit deployment: set `replicas` to empty value
⋊> ~ vim nginx.yaml
⋊> ~ grep replicas nginx.yaml
  replicas:
⋊> ~ kubectl apply -f nginx.yaml
deployment "nginx" configured
⋊> ~ kubectl -n demo get deploy nginx
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx     1         1         1            1           48s
⋊> ~ kubectl -n demo get pod
NAME                     READY     STATUS    RESTARTS   AGE
nginx-2371676037-p1jz5   1/1       Running   0          1m
```

**Comment by rochdev** [comment]
@ichekrygin Do you get the same result if you completely remove the `replicas` field from the deployment definition?

**Comment by pior** [comment]
Any update on this? (I was considering using HPA)

**Comment by ichekrygin** [comment]
@rochdev It **almost** works with `replicas` field removed. :) 
The key difference is to **create** initial deployment w/out replicas field.
(Tested on `v1.7.6`)
For example: 
1. create a deployment w/out `replicas` field -> result: 1 pod deployment (expected)
2. scale deployment to `--replicas=3` -> result: 3 pod deployment (expected)
3. modify `deployment.yaml` to cause rolling update (modify `env` or so) and `apply` new deployment, still w/out `replicas` field -> result: 3 pod deployment (expected)
---
Where it doesn't work if the initial create deployment did provide a `replicas` field, as in the example below:
1. create a deployment with `replicas: 1`-> result: 1 pod deployment (expected)
2. scale deployment to `--replicas=3` -> result: 3 pod deployment (expected)
3. modify `deployment.yaml` removing `replicas` field (and modify env, although not necessary) and apply modified deployment -> result: 1 pod deployment (expected 3!)

Not sure if this is entirely expected, but it seems if you want to maintain current replicas count when you update your deployments without providing `replicas` field, your initial deployment **must** also omit the `replicas` field, otherwise, replicas counts will reset to `1`

**Comment by bgrant0607** [comment]
@ichekrygin 

apply interprets your change as wanting to change back to the default value for the replicas field, since you previously explicitly configured the field. Your desired behavior is not unreasonable, but not what apply's current behavior is. We don't have good ways of transitioning fields in and out of apply's control at the moment. 

@pwittrock Do you have a label specifically for apply issues?

**Comment by bgrant0607** [comment]
Note that at least for maps and lists, we do generally want to remove them when they are removed from the user's configuration. A typical example is a label.

**Comment by jlwynkoop** [comment]
As a workaround, we tried using kubectl replace to replace the original deployment with a new deployment that does not specify a number of replicas.  This seems to allow the deployment to scale as expected with the HPA.  If you modify your CI/CD system to use "kubectl replace" vs "kubectl apply", you may be able to work around this issue.

**Comment by julianvmodesto** [comment]
> Note that at least for maps and lists, we do generally want to remove them when they are removed from the user's configuration. A typical example is a label.

@bgrant0607 should .spec.replicas be the exception?

I ran into the issue @ichekrygin described as well (`kubectl apply` with replicas + then `kubectl apply` without replicas => replicas set back to 1) , and it's not well documented nor intuitive. The expected behavior @ichekrygin described seems more intuitive, if there are no issues.

**Comment by julianvmodesto** [comment]
Also, it seems to be a bug that `kubectl apply —dry-run` will not expose the unexpected behavior. That is, dry running doesn’t show that the apply will scale the deployment down to 1.

**Comment by julianvmodesto** [comment]
Btw the workaround if the initial Deployment set `.spec.replicas` is to use `kubectl apply set-last-applied -f <replicaless Deployment>` before `kubectl apply -f <replicaless Deployment>` to correctly set the last-applied annotation used in the merge, as in this e2e test: https://github.com/kubernetes/kubernetes/pull/42545/files.

**Comment by bgrant0607** [comment]
@julianvmodesto Though I know it's a map in JSON terms, to the API, .spec.replicas is a struct field rather than a map.

**Comment by shiywang** [comment]
> Also, it seems to be a bug that kubectl apply —dry-run will not expose the unexpected behavior. That is, dry running doesn’t show that the apply will scale the deployment down to 1.

@julianvmodesto --dry-run just do a three-way calculate without interfere with server, replicate set to 1 happend in [defaulting](https://github.com/kubernetes/kubernetes/blob/e0ba40b67c76b0734bedafbc547a24b5eedd441f/pkg/apis/extensions/v1beta1/defaults.go#L73) here, I will file an issue to try if we can fix that.

**Comment by bgrant0607** [comment]
@shiywang Users definitely want dry-run to work with apply, but what they want is to show what the resulting resources would look like. 

Anyway, that's not the problem here.

**Comment by discordianfish** [comment]
> From my testing, this will scale down to the --min value for the HPA, but not back to the default of 1.

Is this still the case? This would be even a bigger issue without having a workaround.

**Comment by discordianfish** [comment]
@jlwynkoop I've just edit my annotations as suggested here and I can't reproduce your described behavior. For me everything works as expected and apply didn't change the number of relicas.

**Comment by ocervell** [comment]
Seeing the same. Deployment without 'replicas' field goes to 1 (default), and then to 3 when the HPA's --min aligns. What is the recommended work-around here ?

**Comment by d-grigorenko** [comment]
I believe the issue does not exist if you NEVER set replicas for deployment
We use CI/CD to set replicas equal to current replica just before applying a new deployment

**Comment by cwoolum** [comment]
I am using 1.9.6 and have the same issue. Removing the replicas section causes the replica set to scale down to 1 which looks pretty nasty on deploy load testing metrics 😆.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web-deployment
spec:
  selector:
    matchLabels:
      app: app-web
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: app-web
    spec:      
      containers:
      - name: app-web
        image: blah/myimage:latest 
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
          requests:
            memory: 250Mi   
            cpu: 250m     
        ports:
        - containerPort: 80
        imagePullPolicy: Always   
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Release"
        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
```

Here is my hpa config as well

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-web-deployment
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/app-web-deployment
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: app-web-deployment
  targetCPUUtilizationPercentage: 60
```

**Comment by bgrant0607** [comment]
cc @apelisse re. apply behavior

**Comment by apelisse** [comment]
Yeah, we intend to not re-default after creation (discussion to be finalized). My opinion (and it seems to be confirmed by this issue) is that people remove fields because they don't want to manage them, not because they want the default value (they should specify the default value if that's what they want). Obviously, elements of a map/list are different, and IMO, should be removed when the creator drops them.

**Comment by GEverding** [comment]
I'm running into the same issue on 1.9.7
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.0", GitCommit:"f4c74e18e57148052c59cc0467bb7e99dcc46399", GitTreeState:"clean", BuildDate:"2018-06-21T14:11:26Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Is there an accepted workaround to this issue?

**Comment by apelisse** [comment]
OK Here is the scenario:
- You have a deployment, and you've specified a number of replicas, let's say 5, and you've applied this deployment.
- Later, you've set-up an HPA that keeps changing the number of replicas to a much bigger number,
- You make a change to your deployment configuration (maybe updating the image, that's pretty common),
- When you apply that configuration, the number of replicas is reset to 5 (the value from the configuration), and that's bad.
- If you remove the number of replicas from your configuration before applying, it's every worse, since it resets to 1 ...

Here's the proposed workaround:
- Remove the "replicas: 5" line from your deployment configuration file,
- Remove the "replicas: 5" line from the file opened by running `kubectl apply edit-last-applied deployment/the-deployement`
- Run `kubectl apply -f deployment.yaml` as many times as you want, it shouldn't ever reset the number of replicas.

**Comment by jakebolam** [comment]
Can we add this behaviour to the HPA docs? I'm happy to put up a PR

**Comment by dudicoco** [comment]
I've tried the proposed workaround of removing the replicas field from the deployment spec.
However, when performing a rolling update, the number or replicas increases regardless of the load on the pods, the number of replicas goes down once the HPA scales them in.

Any ideas?

**Comment by dsiebel** [comment]
> I've tried the proposed workaround of removing the replicas field from the deployment spec.
> However, when performing a rolling update, the number or replicas increases regardless of the load on the pods, the number of replicas goes down once the HPA scales them in.
> 
> Any ideas?

Do you have any numbers on the CPU consumption during startup? It might be the pods are scaled up according to the HPA CPU threshold during a deployment. I've seen that one before.

Also: did you run `kubectl apply edit-last-applied deployment/your-deployment`? If not the "old" replica count will be merged with your manifest on each apply, which might also cause this behaviour.

**Comment by dudicoco** [comment]
@dsiebel, it doesn't seem like this is related to CPU consumption during startup.

Using the following manifest:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: example
  labels:
    app: example
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
```

After deploying the above, If you change the container spec such as the readinessProbe initialDelaySeconds or resources cpu and run kubectl apply, HPA will add a replica during the rolling update.

**Comment by dsiebel** [comment]
@dudicoco that sounds to me this is related to your `maxSurge: 1`. It allows the scheduler to place one more pod than the desired replicaCount during releases.

**Comment by dudicoco** [comment]
@dsiebel the problem is that the number of pods doesn't go back down after the rolling update.
Also, when changing maxSurge to 0 I still get the same behaviour - so the HPA is responsible for this scale up.

**Comment by apelisse** [comment]
Do you see the value of "replicas" in the deployment change? Do you have access to the apiserver logs showing the scale requests from the hpa? Do you have events from the HPA?

**Comment by dobesv** [comment]
I think it would solve this problem and a few others if you could specify in the yaml file that certain fields should be set only on creation.

In our case we want to be able to run apply to create the cluster and also to update it.  When updating, we want to leave `replicas` and container image alone during an update, but set them if the resource is being newly created.

**Comment by hermanbanken** [comment]
Specifying `replicas` while also using a HPA is a weird situation that can lead to this behavior when combined with `kubectl apply` patches.

If you dry-run the kubectl apply with `--server-dry-run` you can observe that it **sets** the replicas to 1:
```
GIST=https://gist.githubusercontent.com/hermanbanken/e2bfafc454a47737170e09463a684deb/raw/61713596879a5a9f98baf470f44ced8ca931ca18
kubectl apply -f "$GIST/repro1.yaml"
kubectl apply --server-dry-run -f "$GIST/repro2.yaml" -o yaml
# cleanup
kubectl delete deployment/demo
```

IMO, the docs should contain a warning about using both the `replicas` property and HPAs. We could make adjustments to have the master consider the current status value of replicas instead of using the default value 1, but that is probably a breaking change. What we wanted to build was a Validating Webhook that would check that replicas is not set to a value lower than allowed by the HPA scaling factor. Eg. scaling from 16 pods -> 1 pod is disallowed, but 8 -> 4 or 2 -> 1 pods is allowed.

**Comment by szuecs** [comment]
@bgrant0607 does it still hold true that it's not stable?
I am not sure, but I expect that this will work correctly and not be reset.

**Comment by apelisse** [comment]
@jpbetz has solved this bug in 1.19, I don't think the fix has been cherry-picked. It should work like this now:
1. If an HPA (or another actor) has changed the value of replicas and you remove it from your config before running server-side apply, the value will be kept as-is
2. If you're the only actor that has changed replicas, it'll get reset when you remove it and server-side apply

Would that match your expectations?

**Comment by szuecs** [comment]
@apelisse seems so, thanks for your answer! 
I think 1. should have caught us, but we are also in progress to update to 1.19 from 1.18.

**Comment by lrascao** [comment]
I was also seeing this happening in EKS 1.18, can confirm it no longer occurs after moving to 1.19

**Comment by Israphel** [comment]
I'm 1.19 and I still see the issue. I tried @hermanbanken example and replicas want to go to 1, even though the HPA min is 3.

**Comment by mynampatinaveen** [comment]
@apelisse **If an HPA (or another actor) has changed the value of replicas and you remove it from your config before running server-side apply, the value will be kept as-is**
This is not working in 1.18 or 1.19.when the replicas field is removed from deployment , RollingUpdate will not keep the pod count to the current level but brings it down to 1 .

**Comment by apelisse** [comment]
@mynampatinaveen Can you give exact steps to reproduce? I'm not sure I fully understand the scenario you're describing.

**Comment by Israphel** [comment]
If initially you had replicas: 3, and some days after you create an HPA that has, let's say, min: 3 and max: 9, the following can happen:

If you deploy while your service is at 6 replicas, it will be forced to go down to 3.
If you remove the replicas line, it will be forced to go down to 1.

I tried both.

**Comment by apelisse** [comment]
OK yes, that makes sense. We won't be fixing that behavior specifically, especially for `kubectl apply` "client-side". The server-side apply version should fix it though.

**Comment by alegmal** [comment]
> OK yes, that makes sense. We won't be fixing that behavior specifically, especially for `kubectl apply` "client-side". The server-side apply version should fix it though.

This scenario is different from the one that is supposedly fixed because initial deployment had no replicas set?

**Comment by jtslear** [comment]
I'm seeing this on Kubernetes 1.20.8.

We may need to figure out how to separate the `spec.replicas` here when other things, such as an HPA, are involved.  Being that this field defaults to a value of `1`, we cannot simply remove it from our Deployment objects.  This forces users to create an extra step of grabbing the current replica count, and feeding it into their Deployment object.  This may be simple for persons manually managing Yaml files, but far more difficult for persons utilizing Helm.  Pushing the need to update this field inside of a Helm deployment is also highly awkward from my opinion.  And since every Helm chart may manage this differently, end users consuming that chart will most certainly struggle.

---

How can we pull this issue out of the backlog?  We've got enough proof in the history of this issue that there's a clear problem here that needs to be addressed.  We should start seeking answers to how to solve this.

**Comment by apelisse** [comment]
Can you explain precisely what behavior you're seeing and what you're trying to do?

We've basically fixed this bug with server-side apply in 1.22.

**Comment by jtslear** [comment]
@apelisse 

Ok, after further testing, I can confirm that this indeed working correctly, it just isn't immediately apparent, and I am still building an understanding, but feel free to tell me where I'm wrong, and guide me as needed.  For the purposes of the below demonstration, I'm going to utilize `client config` and `server config` to describe the Deployment object I create, and the Deployment object that Kubernetes has.  Keep in mind the below is strictly for demonstration purposes.

Initially I stood up my test instance and `client config` to have `replicas.spec` set to a value of `1`, and an HPA that set `minReplicas` to `10`.  This provides me with the `10` Pods.  In my first test, I initiate change to the only the container image (mimicking a deploy) we see the negative behavior of `9` Pods being terminated, in tandem with the creation of a new replicaset, and followed by both replicasets building back up to their original numbers during the deployment procedure.  Eventually this reconciles, mostly dependent on the time it takes for Pods to come back online.  In my testing using an nginx image, this is SUPER quick.  In reality on the workloads I am managing, this is very sluggish due to a wide array of factors.

<details><summary>test1.yaml</summary>

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.0
          resources:
            requests:
              cpu: 1m

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 10
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 100
```

</details>

In my second test, I would remove `replicas.spec` from the `client config`, which would essentially set this to a null value on the `server config`.  Kubernetes is going to see this change, and apply this with a default value of `1`, as stated in its documentation, to the `server config`.  This is why [I continued to remain confused, and hence my comment above.](https://github.com/kubernetes/kubernetes/issues/25238#issuecomment-916945565)  Because of this, we see the same behavior described in the first test.  9 Pods going into a Terminated state, followed by 2 replicasets building back up during the deployment cycle.

<details><summary>test2.yaml</summary>

```diff
spec:
- replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
-         image: nginx:1.14.0
+         image: nginx:1.14.1

```

</details>

When we look at a third test, say we change the image again to mimic a deploy, this is when things finally look okay.  Okay being, we surge up 3 new Pods, before terminating any Pods belonging to the now outdated replicaset.   I believe the reason why things finally behave properly here is because WE still have a `null` value for the `spec.replicas` in our `client config` Deployment object.  Due to this, when a new deploy happens, we take in whatever value comes in from the `server config` Deployment object.  An HPA doesn't modify the `client config` `spec.replicas` value anytime it scales.  Something else is happening there that I do not yet fully understand.  And I say this because if you output the Deployment object, `spec.replicas` is always our desired value per our HPA.  I could still use further clarification on this point just to ensure I'm fully understanding the inner workings of Kubernetes in this case.

<details><summary>test3.yaml</summary>

```diff
spec:
  template:
    spec:
      containers:
        - name: nginx
-         image: nginx:1.14.1
+         image: nginx:1.14.2

```

</details>

---

[So my comment above is unfounded.](https://github.com/kubernetes/kubernetes/issues/25238#issuecomment-916945565)  We do not need to go further and do more work inside of helm, we just need to remove `spec.replicas` anytime some form of autoscaling is enabled.  I see two problems here:

1. People need to be made aware of is that if you enable an HPA, and remove `spec.replicas` in the same step, you run into the very problem I had with my second test.
2. We should probably figure out a way to really drill into persons that when an HPA is enabled, do not set your deployment objects `spec.replicas` field.  Otherwise the deployment does not behave as desired.

**Comment by apelisse** [comment]
Thanks for the example @jtslear, I'm assuming you've been applying the changes with `kubectl apply`, without the `--server-side` flag?

**Comment by jtslear** [comment]
That's correct.  We use Helm for most our deployments; I'm not sure how Helm accomplishes the same task, but the behavior that we see is appears the same that I describe.

**Comment by WarheadsSE** [comment]
> We should probably figure out a way to really drill into persons that when an HPA is enabled, do not set your deployment objects spec.replicas field. Otherwise the deployment does not behave as desired.

A little more detail:

The Deployment object can/will be edited separately of the HPA. Because the HPA does not have an admission/mutating controller that ensures the the `.spec.replicas` count is overridden with the current value the HPA feels is correct, we see this behavior.

**Comment by dsalaza4** [comment]
Are there any workarounds for this? In my specific case, we do `kubectl apply` for our HPA and deployment configs MANY times a day and this is causing the cluster to provision/deprovision nodes all day.

**Comment by dobesv** [comment]
> Are there any workarounds for this?

You have to *remove* the `spec.replicas` from the deployment spec, then `kubectl apply` will stop resetting the replica count after the next deploy.

**Comment by Israphel** [comment]
> > Are there any workarounds for this?
> 
> You have to _remove_ the `spec.replicas` from the deployment spec, then `kubectl apply` will stop resetting the replica count after the next deploy.

what's the min kubernetes version for that?

**Comment by dsalaza4** [comment]
@dobesv I did some basic testing but it seems like not specifying `replicas` in my `yaml` file simply defaults them to `1` after an `apply`. :thinking:

**Comment by dobesv** [comment]
> what's the min kubernetes version for that?

I don't know.

> I did some basic testing but it seems like not specifying replicas in my yaml file simply defaults them to 1 after an apply

OK, I don't know why.

**Comment by jtslear** [comment]
I am attempting to address recommendations and the behaviors others have reported via a documentation update here: https://github.com/kubernetes/website/pull/29739

For those that have chimed in, I thank you very much for your time.  Please feel free to help me improve our documentation as you see fit to help others that have run into this same situation.

**Comment by pinowthebird** [comment]
> @dobesv I did some basic testing but it seems like not specifying `replicas` in my `yaml` file simply defaults them to `1` after an `apply`. 🤔
> 
> By the way:
> 
> ```
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
> ```

That's indeed what the docs are stating: 
> If you do not specify .spec.replicas, then it defaults to 1.

(source: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#replicas)

**Comment by dsalaza4** [comment]
I ended up implementing a [hpa_replicas function](https://gitlab.com/fluidattacks/product/-/blob/b34d4dccbcae59c96de238c74dd30d4f82d22a45/makes/applications/integrates/back/deploy/prod/entrypoint.sh#L3 and [replacing its returned value in the deployment YAML](https://gitlab.com/fluidattacks/product/-/blob/b34d4dccbcae59c96de238c74dd30d4f82d22a45/makes/applications/integrates/back/deploy/prod/entrypoint.sh#L48).

**Comment by philipsu522** [comment]
I'm trying to follow the recommendation instructed in https://github.com/kubernetes/website/pull/29739/files, specifically recommendation 1. Note that the **patch** verb exhibits the same behavior of scaling the replica count down to 1, although remove the spec.replica field from the manifest then applying doesn't.
Specifically, this command causes the scale-to-1 behavior:
```
 kubectl patch -n psu-test-hpa deployment/sample-app --type=json -p='[{"op": "remove", "path":"/spec/replicas"}]' 
```

**Comment by bgrant0607** [comment]
@apelisse Is there a way with SSA to specify an initial value of a field, such as spec.replicas, but not take ownership of it?

Discussion with @tamalsaha:
https://twitter.com/tsaha/status/1489720742300160004

**Comment by dudicoco** [comment]
@apelisse thank you for the documentation, it's very clear.

However, I don't think it is usable in most real word scenarios where we store our yamls in git and use helm/CI/controllers to apply new configs.

**Comment by apelisse** [comment]
> However, I don't think it is usable in most real word scenarios where we store our yamls in git and use helm/CI/controllers to apply new configs.

Because they rely on multiple steps? i.e. "commit this, apply that, commit that, apply this" kind of sequence?

**Comment by dudicoco** [comment]
> > However, I don't think it is usable in most real word scenarios where we store our yamls in git and use helm/CI/controllers to apply new configs.
> 
> Because they rely on multiple steps? i.e. "commit this, apply that, commit that, apply this" kind of sequence?

@apelisse because a special logic would need to be added to any tool/system which adds the flag only when adding an hpa to an existing deployment.

**Comment by apelisse** [comment]
What special logic needs to be built? I guess I must be missing that part.

**Comment by dudicoco** [comment]
The logic is:
1. check if deployment exists without an hpa
2. if 1 is true, add the flag `--field-manager=handover-to-hpa`

Please correct me if I misunderstood how this new feature works.

**Comment by rehevkor5** [comment]
> We wrote this piece of [documentation](https://kubernetes.io/docs/reference/using-api/server-side-apply/#transferring-ownership) to describe how one should do that. I'd love to hear feedback and if this doesn't work!

That is helpful if you're using `kubectl`, but it doesn't appear to matter if you use Helm, sadly.

**Comment by rbroggi** [comment]
I wanted to contribute with my 2-cents:

We have faced the issue of defining `spec.replicas` while having `hpa` enabled - in our case the situation was even more confusing as at a certain point when we had around 11 pods (defined by `hpa`) we started a deployment and instead of seing the number of our ready replicas drop to `3` (which was the `spec.replicas` defined in our `deployment.yaml`) we saw it going all the way down to 0. After investigating it we realized that the reason was that the remaining 3 pods belonging to the old replica set were so overwhelmed with the traffic - which was supposed to be handled by 11 instances - that the Kubernetes readiness probes started failing and therefore we had a big problem as we faced due to this very issue a downtime.

**Comment by victorboissiere** [comment]
We had the same problem, we ended up by implementing a mutating webhook with Kyverno to make sure the current `replicas`  value is not overriden.

Example:
```yaml

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: general-deployment-hpa-replicas
  annotations:
    policies.kyverno.io/title: HPA replicas spec
    policies.kyverno.io/category: Standard
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      Prevent spec.replicas to be overriden when HPA handles the deployment replicas
spec:
  background: false
  schemaValidation: false # Issue: https://github.com/kyverno/kyverno/issues/2748
  rules:
  - name: Deployment spec replicas
    match:
      resources:
        kinds:
          - Deployment
    preconditions:
      all:
      - key: "{{ request.object.metadata.labels.hpa || '' }}"
        operator: Equals
        value: "true"
      - key: "{{request.object.spec.replicas }}" # Allow to scale down to zero without changes
        operator: GreaterThan
        value: 0
      - key: "{{request.operation}}"
        operator: Equals
        value: UPDATE
    mutate:
      patchStrategicMerge:
        spec:
          replicas: '{{request.object.status.replicas}}'
```
