### ISSUE TITLE
PATCH API request on deployment results in panic

### ISSUE THREAD

**Issue by coco98** [kubernetes/kubernetes#25417]
A PATCH request to: `/apis/extensions/v1beta1/namespaces/default/deployments/adminer`
of `'Content-Type': 'application/json-patch+json'` with body:

```
[{   
        op: 'replace',
        path: 'spec/template/spec/containers/0/image',
        value: 'clue/adminer'
},  
{   
        op: 'replace',
        path: 'spec/template/spec/containers/0/env',
        value: []
}]
```

results in:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "an error on the server has prevented the request from succeeding",
  "reason": "InternalError",
  "details": {},
  "code": 500
}
```

and the kube-api-server logs show this:

```
E0510 18:59:10.790108       1 apiserver.go:207] recover from panic situation: - runtime error: invalid memory address or nil pointer dereference
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:183
    /usr/src/go/src/runtime/asm_amd64.s:401
    /usr/src/go/src/runtime/panic.go:387
    /usr/src/go/src/runtime/panic.go:42
    /usr/src/go/src/runtime/sigpanic_unix.go:26
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/evanphx/json-patch/patch.go:390
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/evanphx/json-patch/patch.go:481
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:1029
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:531
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:500
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:249
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95
    /usr/src/go/src/net/http/server.go:1265
    /usr/src/go/src/net/http/server.go:1541
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:414
    /usr/src/go/src/net/http/server.go:1265
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:47
    /usr/src/go/src/net/http/server.go:1265
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101
    /usr/src/go/src/net/http/server.go:1265
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101
    /usr/src/go/src/net/http/server.go:1265
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:182
    /usr/src/go/src/runtime/asm_amd64.s:2232
```

The original deployment was this:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: adminer
  name: adminer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - env:
        - name: FOO
          value: bar
        image: clue/adminer
        name: adminer
        ports:
        - containerPort: 80
```
