### ISSUE TITLE
Traffic splitting through Ingress

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#25485]
Something like:

``` yaml
rules:
- host: foo.bar.com
  path: /api
  backend:
  - serviceName: alpha1
    weight: 1, or 33%
  - serviceName: alpha2
    weight: 2, or 66%
```

There'er ways to achieve similar splitting with either a deployment or by managing Service labels so they span a mix of alpha1 and alpha2 endpoints, but this seems more intuitive.

On GCE I think we'd have to use iptables stats to  satisfy that, but we can't push it down into a Service because today a single Service only understands homogenous endpoints.

Nginx and haproxy understand wrr, so the 33% and 66% would have to apply to all the endpoints of the Service, and we'd just need to make sure the tie is broken evenly.

**Comment by marun** [comment]
cc: @rajatchopra

**Comment by bgrant0607** [comment]
Also provided by: https://www.amalgam8.io/

**Comment by errordeveloper** [comment]
It feels like there multiple ways to go about the implementation, and Istio supports this use-case, so I think we should start a more specific proposal of how Ingress API needs to be extended.

As the API stands right now, we don't de-duplicate paths, so the following object is legit:
```YAML
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: test1
          servicePort: 80
        path: /testpath
      - backend:
          serviceName: test2
          servicePort: 80
        path: /testpath
```
