### ISSUE TITLE
Environment variables named specific things not getting passed on from deployment to pods

### ISSUE THREAD

**Issue by drashkov** [kubernetes/kubernetes#25585]
Deployment is defined in a json file with several environment varibles. Deployment is deployed using "kubectl apply -f deployment.json". Pods get most of the environment variables defined, but not all.

Specifically, the variables defined in the deployment.json are named:
`
 {
                "name": "DB_HOSTS",
                "value": "10.0.0.1"
              },
              {
                "name": "SLACK_ENDPOINT",
                "value": "ERRORNOT"
              },
              {
                "name": "LACK_ENDPOINT",
                "value": "ERRORNOT"
              },
              {
                "name": "SLACK",
                "value": "ERRORNOT"
              },
              {
                "name": "CK_ENDPOINT",
                "value": "ERRORNOT"
              },
              {
                "name": "ACK_ENDPOINT",
                "value": "ERRORNOT"
              },
              {
                "name": "K_ENDPOINT",
                "value": "ERRORNOT"
              },
              {
                "name": "CASSANDRA_LOGGING_LEVEL",
                "value": "ERROR"
              },
              {
                "name": "ENABLE_GETIP",
                "value": "https://www.url.com"
              }
`

the environment variables that appear in a pod are:

`
ENABLE_GETIP

CASSANDRA_LOGGING_LEVEL

K_ENDPOINT

ACK_ENDPOINT

CK_ENDPOINT

DB_HOSTS
`

That is, ENV variables named "SLACK_ENDPOINT", "LACK_ENDPOINT" and "SLACK" never get passed on to the pods.

**Comment by drashkov** [comment]
It also won't accept "randomshit" as an environment varible. When I add that as an environment variable to an existing deployment and run "kubctl apply -f deployment.json" nothing happens.

This is on version v1.2.4 / 3eed1e3be6848b877ff80a93da3785d9034d0a4f

**Comment by thockin** [comment]
Ehh?  Can you post a full but minimized yaml that I can run to reproduce it?

**Comment by drashkov** [comment]
We use JSON files, here is the full one. "SLACK_ENDPOINT" does not appear as an environment variable in the pods. Doing "kubectl apply -f <thisfile>.json" does not create new pods, and does not pass these variables to the pods. If I change the number of replicas and add a new pod, that pod will be created, but won't have that varible.

`
{
    "apiVersion": "extensions/v1beta1",
    "kind": "Deployment",
    "metadata": {
        "name": "test-api-deployment"
    },
    "spec": {
        "replicas": 3,
        "template": {
            "metadata":{
                "labels": {
                    "app": "test-api"
                }
            },
            "spec": {
                "containers": [{
                    "image": "gcr.io/<repository>/test_api:1.3.5",
                    "name": "test-api",
                    "env": [
                        {
                            "name": "SLACK_ENDPOINT",
                            "value": "https://slack.com"
                        },
                        {
                            "name": "API_DB_HOSTS",
                            "value": "10.0.0.83"
                        },
                        {
                            "name": "CASSANDRA_LOGGING_LEVEL",
                            "value": "ERROR"
                        }]
                }]
            }
        }
    }
}
`

**Comment by pwittrock** [comment]
I am not able to reproduce on GKE at 1.2.4 when exec'ing into one of the Pods and printing the environment.

```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
```

```sh
$ kubectl exec test-api-deployment-2124663613-029ak -i -t sh
/ # env
...
SLACK_ENDPOINT=https://slack.com
...
```

This is the yaml I used - note the image is different:

```yaml
{

    "apiVersion": "extensions/v1beta1",

    "kind": "Deployment",

    "metadata": {

        "name": "test-api-deployment"

    },

    "spec": {

        "replicas": 3,

        "template": {

            "metadata":{

                "labels": {

                    "app": "test-api"

                }

            },

            "spec": {

                "containers": [{

                    "image": "gcr.io/google_containers/serve_hostname:v1.4",

                    "name": "test-api",

                    "env": [

                        {

                            "name": "SLACK_ENDPOINT",

                            "value": "https://slack.com"

                        },

                        {

                            "name": "API_DB_HOSTS",

                            "value": "10.0.0.83"

                        },

                        {

                            "name": "CASSANDRA_LOGGING_LEVEL",

                            "value": "ERROR"

                        }]

                }]

            }

        }

    }

}
```

What are the symptoms you are seeing?  Can you provide yaml using standard public image along with the specific symptoms you are seeing?

**Comment by gflarity** [comment]
@pwittrock did you create the deployment first with out the env, then add them via an apply?

**Comment by drashkov** [comment]
Thanks for looking into it @pwittrock, I managed to reproduce it with the yaml you posted. 

Here's what I did:
1. Saved the yaml you provided as 'og.yaml'
2. Deleted the "SLACK_ENDPOINT" env var from that file and save that as "mod.yaml" (no other changes)

3.
`$ kubectl apply -f og.yaml

deployment "test-api-deployment" created

$ kubectl exec test-api-deployment-2124663613-9tl0u env |grep SLACK

SLACK_ENDPOINT=https://slack.com`

This creates the deployment with all env vars as expected

4. `
$ kubectl apply -f mod.yaml
$ kubectl exec test-api-deployment-2413078913-547h0 env |grep SLACK
`
This re-creates a new set of pods and they don't have the SLACK_ENDPOINT var, as expected.

5. `kubectl apply -f og.yaml ; watch kubectl get pods`
This does not re-create the pods, so the env var is not passed along. kubectl does not return errors.

**Comment by pwittrock** [comment]
cc @janetkuo 
cc @AdoHe

**Comment by pwittrock** [comment]
@drashkov Thanks, I was able to reproduce the issue.

It looks like the config with the ENV does get stored in the last-applied-configurations annotation:

```json
kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"test-api-deployment","creationTimestamp":null},"spec":{"replicas":3,"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"test-api","app2":"test-api2"}},"spec":{"containers":[{"name":"test-api","image":"gcr.io/google_containers/serve_hostname:v1.4","env":[{"name":"SLACK_ENDPOINT","value":"https://slack.com"},{"name":"SLACK_ENDPOINT2","value":"https://slack.com"},{"name":"CASSANDRA_LOGGING_LEVEL","value":"ERROR"}],"resources":{}}]}},"strategy":{}},"status":{}}'
```

But does not get put into the pods:

```yaml
  containers:
  - env:
    - name: SLACK_ENDPOINT
      value: https://slack.com
    - name: CASSANDRA_LOGGING_LEVEL
      value: ERROR
    image: gcr.io/google_containers/serve_hostname:v1.4
    imagePullPolicy: IfNotPresent
    name: test-api
    resources:
      requests:
        cpu: 100m
```
