### ISSUE TITLE
PetSet not launching more than one pod

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#25618]
I am running PetSet with only one node.  Should PetSet create more than one Replica?  The single po is up and happy.  Again only have a single k8s node up

Here is the yaml for the pet:

```yaml
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 2
  template:
    metadata:
      # Why is this here??
      # annotations:
        # Flip this to false after each node is stable.
        # To check the stability of a node, see kubectl logs.
        # pod.alpha.kubernetes.io/initialized: "false"
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: 10.100.179.231:5000/cassandra
        imagePullPolicy: Always
        command:
          - /run.sh
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        # If you need it it is going away in C* 4.0
        #- containerPort: 9160
        #  name: thrift
        resources:
          limits:
            cpu: 1
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        # CJL figure this out
        #args:
        #- --on-start="/on-start.sh"
        #- --service=cassandra

        volumeMounts:
        # These volume mounts are persistent. They're like inline claims,
        # but not exactly because the names need to match exactly one of
        # the pet volumes.
        - name: data
          mountPath: /cassandra_data
      volumes:
        - name: data
          emptyDir: {}
  #volumeClaimTemplates:
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  #- metadata:
  #    name: data
  #    annotations:
  #      volume.alpha.kubernetes.io/storage-class: anything
  #  spec:
  #    accessModes: [ "ReadWriteOnce" ]
  #    resources:
  #      requests:
  #        storage: 10Gi
```

A bunch of console commands:

```console
bash-3.2$ kubectl get petset -o wide
NAME        DESIRED   CURRENT   AGE
cassandra   2         2         6m        cassandra   10.100.179.231:5000/cassandra   app=cassandra
```

```console
bash-3.2$ kubectl get pods -o wide
NAME          READY     STATUS    RESTARTS   AGE       NODE
cassandra-0   1/1       Running   0          6m        192.168.64.2
```

```console
bash-3.2$ kubectl describe petsets
Name:			cassandra
Namespace:		default
Image(s):		10.100.179.231:5000/cassandra
Selector:		app=cassandra
Labels:			app=cassandra
Replicas:		2 current / 2 desired
Annotations:		<none>
CreationTimestamp:	Sat, 14 May 2016 11:40:41 -0600
Pods Status:		1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Volumes:
  data:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
Events:
  FirstSeen	LastSeen	Count	From		SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----		-------------	--------	------			-------
  7m		7m		1	{petset }			Normal		SuccessfulCreate	pet: cassandra-0
```

```console
bash-3.2$ kubectl get node
NAME           STATUS    AGE
192.168.64.2   Ready     12h
```
