### ISSUE TITLE
How use DNS domain name[kubernetes service name] to visit pod in cluster?

### ISSUE THREAD

**Issue by DreamLog** [kubernetes/kubernetes#25799]
I have done all kubernetes DNSservice config,and test it running ok. but how could I reach the pod from serviceName(DNS domain name)?

```
[root@test-s59tr /]# nslookup bj001
Server:     10.254.0.2
Address:    10.254.0.2#53

Name:   bj001.default.svc.cluster.local
Address: 10.254.54.162
```
above this， dns works ok. but.....

```
[root@test-s59tr /]# curl bj001:18010/sso/login
^C
```
how ever, use IP works.

```
[root@test-s59tr /]# curl 172.17.12.3:18010/sso/login
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>TEST-LOGIN</title>
```

**Comment by DreamLog** [comment]
@ncdc

**Comment by lavalamp** [comment]
(personal note: you used a different IP address than the DNS lookup showed?)

Please re-post your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes).

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases.

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
   * [the user guide](http://kubernetes.io/v1.0/)
   * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by DreamLog** [comment]
@lavalamp Thanks a lot.I will do it.

**Comment by DreamLog** [comment]
I have resolved it by modifying the service YAML file. all you  used port should be seted in the {spec.ports}, like my issue, the 18010 port must be opened.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: bj001
  name: bj001
spec:
  sessionAffinity: ClientIP
#  externalIPs:
#    - 172.16.2.51
  ports:
    # the port that this service should serve on
    - port: 3306
      name: mysql
      targetPort: 3306
    - port: 18010
      name: bxnpf
      targetPort: 18010
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: bj001
```
