### ISSUE TITLE
Doesn't detect failed replication controller

### ISSUE THREAD

**Issue by livelace** [kubernetes/kubernetes#25790]
Configuration:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        lifecycle:
          postStart:
            exec:
              command: ["exit", "1"]
        ports:
        - containerPort: 80
```

[root@kube-controller1 ~]# kubectl get pods
NAME          READY     STATUS             RESTARTS   AGE
nginx-4xf35   0/1       CrashLoopBackOff   5

https://paste.fedoraproject.org/367808/63550656/

[root@kube-controller1 ~]# kubectl get rc
NAME      DESIRED   CURRENT   AGE
nginx     1         1         6m

https://paste.fedoraproject.org/367809/46355072/

https://github.com/openshift/jenkins-plugin/issues/33
https://github.com/openshift/origin/issues/8507
