### ISSUE TITLE
Inconsistent deployment annotation in rollout history

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes/kubernetes#25924]
Repro Steps:
```bash
kubectl create -f nginx-deployment.yaml 
deployment "nginx-deployment" created

kubectl get deployments
NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment   3         3         3            3           0s

kubectl rollout history deployment/nginx-deployment
deployments "nginx-deployment":
REVISION        CHANGE-CAUSE
1               <none>
```

Note: `CHANGE-CAUSE` has value `<none>`, since deployment file did not contain any annotations.

Modify nginx-deployment.yaml file adding annotation `foo-bar` like so:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    kubernetes.io/change-cause: foo-bar
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

Delete nginx-desployment and re-create one from scratch
```bash
kubectl delete deployment/nginx-deployment
deployment "nginx-deployment" deleted
```
Assert deployment is gone:
```bash
 kubectl get deployments
```

Create new nginx-deployment:
```bash
kubectl apply -f nginx-deployment.yaml 
deployment "nginx-deployment" created

kubectl rollout history deployment/nginx-deployment
deployments "nginx-deployment":
REVISION        CHANGE-CAUSE
1               kubectl apply -f nginx-deployment.yaml
```
Note: `CHANGE-CAUSE` reflect the actual command and not the value from the file

Apply the same change again:
```bash
kubectl apply -f nginx-deployment.yaml 
deployment "nginx-deployment" configured

kubectl rollout history deployment/nginx-deployment
deployments "nginx-deployment":
REVISION        CHANGE-CAUSE
1               foo-bar
```
Note: second time around annotation is correctly updated. Since there were no other changes to the deployment, no new pods/replicasets were created.

Repeat applying the same deployment file and observe alternating value in `CHANGE-CAUSE`
```bash
kubectl apply -f nginx-deployment.yaml 
deployment "nginx-deployment" configured

kubectl rollout history deployment/nginx-deployment
deployments "nginx-deployment":
REVISION        CHANGE-CAUSE
1               kubectl apply -f nginx-deployment.yaml

kubectl apply -f nginx-deployment.yaml 
deployment "nginx-deployment" configured

kubectl rollout history deployment/nginx-deployment
deployments "nginx-deployment":
REVISION        CHANGE-CAUSE
1               foo-bar
```
