### ISSUE TITLE
slow pv <--> pvc binding when claim created before pv

### ISSUE THREAD

**Issue by jeffvance** [kubernetes/kubernetes#25930]
This is based on the recently merged PR #24331: 
```
v1.3.0-alpha.4.129
```

The test involves a simple pv and pvc spec that match accessModes and capacity.

Case 1: create pv first then create pvc using _default_ claim sync period (10m):
```
Elapsed: 0:03.99
syncVolume() calls: 12
syncClaim() calls: 4
```
Case 2: create **pvc** first then create pv using _default_ claim sync period (10m):
```
Elapsed: 10:02.26     // <------------- 150 times slower!
syncVolume() calls: 14
syncClaim() calls: 5
```
Case 3: create pv first then create pvc using claim sync period *30s*:
```
Elapsed: 0:04.04
syncVolume() calls: 12
syncClaim() calls: 4
```
Case 4: create **pvc** first then create pv using claim sync period *30s*:
```
Elapsed: 0:30.91     // <-------------------- 7.5 times slower
syncVolume() calls: 14
syncClaim() calls: 5
```

Here are the pv and pvc yaml files:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /opt/nfs  #export dir
    server: 192.168.122.73
  persistentVolumeReclaimPolicy: Retain

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
