### ISSUE TITLE
pre-bound claim remains Pending 

### ISSUE THREAD

**Issue by jeffvance** [kubernetes/kubernetes#25935]
This is based on the recently merged PR #24331:
```
v1.3.0-alpha.4.129
```

I created 2 PVs (pv1,pv2) followed by 2 pvcs (claim1,claim2) where claim2 is pre-bound to pv2 via _volumeName_:
```
NAME      CAPACITY   ACCESSMODES   STATUS      CLAIM                REASON    AGE
nfs-pv1   1Gi        RWO           Available                                  1m
nfs-pv2   1Gi        RWO           Bound       default/nfs-claim1             1m

NAME         STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
nfs-claim1   Bound     nfs-pv2   0                        1m
nfs-claim2   Pending   nfs-pv2   0                        1m     <--------------- 
```
claim1 finds pv2 before claim2 finds pv2 (which it is pre-bound to). This is ok due to timing.
If I change the order and create pv2,pv1 followed by claim2,claim1 then I again see claim2 in the Pending phase:
```
NAME      CAPACITY   ACCESSMODES   STATUS    CLAIM                REASON    AGE
nfs-pv1   1Gi        RWO           Bound     default/nfs-claim1             3s
nfs-pv2   1Gi        RWO           Bound     default/nfs-claim2             4s

NAME         STATUS    VOLUME    CAPACITY   ACCESSMODES   AGE
nfs-claim1   Bound     nfs-pv1   0                        3s
nfs-claim2   Pending   nfs-pv2   0                        3s    <------------------- 
```
This time **all** pvs are Bound but claim2 remains Pending even though pv2 shows it as being bound to.
If repeat the above test (order: pv2,pv1,claim2,claim1) in a loop (deleting the pvs and claims each iteration) I see a Pending claim2 about 50% of the time. The other times all objects are Bound.

Here are the spec files for pv2 and claim2:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /opt/nfs  #export dir
    server: 192.168.122.73
  persistentVolumeReclaimPolicy: Retain

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim2
spec:
  volumeName: nfs-pv2                   # <----------------------- pre-bound
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
