### ISSUE TITLE
kubectl: edit + boolean leads to confusing error

### ISSUE THREAD

**Issue by philips** [kubernetes/kubernetes#26050]
I edit a pod with some metadata such as:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Pod
metadata:
  generateName: guestbook-
  labels:
    app: guestbook
```

Then I close the file and it pops back open with this message after I add `fun: true` label:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# The edited file had a syntax error: unable to decode "edited-file": [pos 453]: json: expect char '"' but got char 't'
#
apiVersion: v1
kind: Pod
metadata:
  generateName: guestbook-
  labels:
    app: guestbook
    fun: true
```

Putting the error in the comment header is OK but I was very confused when this happened to me and didn't notice the errors at all. A few potential fixes:

1. Print out the errors and then ask the user to "press enter" to fix, then launch the $EDITOR again
2. Put the error message above the line that generated the error
3. Automatically quote true/false values before converting to JSON in fields like labels.

Given the three options 1 is probably easiest and would fix the issue well enough for now.

cc @janetkuo as we discussed this might be a duplicate but I can't find the other one.

**Comment by kargakis** [comment]
cc: @kubernetes/kubectl

**Comment by thockin** [comment]
I agree.  In fact, I think it doesn't go far enough.

Sometimes I get this:

```
$ kubectl edit ns test
A copy of your changes has been stored to "/tmp/kubectl-edit-oh43e.yaml"
error: expected type string, for field metadata.finalizers[1], got bool
```

Sometimes it pops me back into an editor with comments:

```
# namespaces "test" was not valid:
# * metadata.finalizers: Invalid value: "foobar": name is neither a standard finalizer name nor is it fully qualified
```
...but it has actually deleted my changes!  If I made any other changes that were not errors, they are erased.  This is really bad.

Other times, as in the case of #32398, it accepts my changes, generates a do-nothing patch and exits.  If I don't read carefully, I might think it succeeded, but didn't do anything.

So there are a number of bugs here.  I think it should:

a) always go back to the editor
b) always retain what I hand-edited, even if that has to be in comments
c) put validation errors in comments next to the lines in question
d) treat YAML errors the same as validation errors (I know that is significant work)
e) detect do-nothing PATCHES and give a big error (even if you have to save the upstream state and diff the saved state against it - detect it!)
f) probably not use PATCH at all.

**Comment by nikinath** [comment]
Hi, I am new here and noticed that this was marked as a good issue for new contributors.

Regarding putting validation errors (eg, swagger-based schema validation) next to lines in question, I found that it was a little difficult to get line numbers out of the functions that are being used for the validation: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory.go#L489. Maybe I'm missing something here? Is there a better way to achieve this?

Any pointers to get started would be much appreciated, thanks.

**Comment by pwittrock** [comment]
@nikhita Sorry no one ever responded.  If you are still interested in this @apelisse may be able to help you

**Comment by nikhita** [comment]
@pwittrock thanks for the response. I am currently busy with my Google Summer of Code project (with kubernetes) so won't be able to work on it now. I'll come back to this later if it's still open.

Meanwhile, if anyone is interested in taking this, please feel free to do so.

**Comment by mccormd** [comment]
Should/would something like this prevent me from deleting an API object?

~~~
# kubectl delete deploy prometheus -n kube-system
The Deployment "prometheus" is invalid: metadata.finalizers[0]: Invalid value: "foregroundDeletion": name is neither a standard finalizer name nor is it fully qualified
~~~

**Comment by mrajashree** [comment]
Hi, I'm interested in contributing to kubernetes. Can I take this up if it's not already taken?

**Comment by fabianofranz** [comment]
@mrajashree Feel free to take it, thanks for the interest! [Ping us](https://github.com/kubernetes/community/tree/master/sig-cli) if you need any help.

**Comment by MorrisLaw** [comment]
Hey @mrajashree @fabianofranz Is this issue still being worked on? I'd like to contribute if it's available :octocat:

**Comment by mrajashree** [comment]
@MorrisLaw I didn't get time to work on this previously but now I'm able to. So I'd still like to work on this. :) I'll add you in the PR so you can review too

**Comment by MorrisLaw** [comment]
Ok @mrajashree sounds good. Thanks for the heads up!

**Comment by thockin** [comment]
Is anyone working on this?

**Comment by FilipNikolovski** [comment]
@thockin can I take a crack at this, if no one is working on it currently?

**Comment by mrajashree** [comment]
@thockin I feel like some parts of this issue have been fixed by the PRs referencing it. But some things are still left
These were the issues listed in your comment and the current status on them
a) always go back to the editor
Update: Still doesn't go back to editor, I get the following error. Has there been any change in what is required/expected wrt this? meaning do we still want it to go back to the editor or this is fine?
```
error: pods "newpod-6c86c676bd-x2rz2" could not be patched: unrecognized type: string
You can run `kubectl replace -f /var/folders/c1/r2dxlmh503q691xhb8zfr8t00000gp/T/kubectl-edit-0133o.yaml` to try this update again.
```

b) always retain what I hand-edited, even if that has to be in comments
Update: Whatever the user hand-edited during the edit is retained only if the correct lines were added after the line causing the error. So if I'm adding two labels: `blah: true` which is incorrect and `blah: "true"` which is correct, the correct label gets retained based on the order in which they're added
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    blah: "true"
    blah: true
```
Not retained

BUT
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    blah: true
    blah: "true"
```
Retained and no error thrown for `blah: true`

c) put validation errors in comments next to the lines in question
Update: Lines aren't retained so no validation error

d) treat YAML errors the same as validation errors (I know that is significant work)
Update: This error indicates validation I guess? `could not be patched: unrecognized type: string`

e) detect do-nothing PATCHES and give a big error (even if you have to save the upstream state and diff the saved state against it - detect it!)
f) probably not use PATCH at all
Update: Looks like e and f are fixed by this https://github.com/kubernetes/kubernetes/pull/35647

I'm looking into fixing what I noticed in `b`, i.e, the hand-edited changes aren't always retained. Please let me know if I've missed anything/any of my observations are wrong.
