### ISSUE TITLE
Unable to have an external ip on my ingress

### ISSUE THREAD

**Issue by herbalizer404** [kubernetes/kubernetes#26273]
Hi, 
When I try to expose a service directly on one of my nodes port, i can precise his ip like this when i create the service, Im on baremetal and all my nodes have a public ip.

```
apiVersion: v1
kind: Service
metadata:
  labels:
  name: nginx-service
spec:
  externalIPs:
   - 81.34.343.131
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
```

And it works, I can access the service to the external ip on port 80.

But When I try to use ingress, I deleted this service above and put this one without external ip:
```

apiVersion: v1
kind: Service
metadata:
  labels:
  name: nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
```
then i create the ingress:
```

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: tristan
    http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-service
          servicePort: 80
```
But it doesnt work, and i dont know how to give an ip adress to my ingress. thanks
