### ISSUE TITLE
Allow auto-population of environment variables from ConfigMap

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kubernetes#26299]
The current approach for populating environment variables from ConfigMaps ends up pretty verbose. With the following ConfigMap:

```
apiVersion: v1
data:
  space-ships: 1
  ship-type: battle-cruiser
  weapon: laser-cannon
kind: ConfigMap
metadata:
  name: space-config
```

I have to manually expose each variable separately:

```
apiVersion: v1
kind: Pod
metadata:
  name: space-simulator
spec:
  containers:
  - name: space-simulator
    image: foo/space-simulator
    env:
    - name: SPACE_SHIPS
      valueFrom:
        configMapKeyRef:
          name: space-config
          key: space-ships
    - name: SHIP_TYPE
      valueFrom:
        configMapKeyRef:
          name: space-config
          key: ship-type
    - name: WEAPON
      valueFrom:
        configMapKeyRef:
          name: space-configs
          key: weapon
```

This seems unnecessary and error-prone if all I want to express is that the pod should pull all the data from the ConfigMap and populate environment variables from them.

It would be nice if this could be done in more concise manner, perhaps by introducing an `envFrom` field. For example:

```
apiVersion: v1
kind: Pod
metadata:
  name: space-simulator
spec:
  containers:
  - name: space-simulator
    image: foo/space-simulator
  - envFrom:
      configMap: space-config
```

The idea being that `envFrom` could support other ways of auto-population, e.g. secrets.

**Comment by yissachar** [comment]
Note that my example implicitly assumes that there would be some type of auto-conversion from the lowercase and hyphenated ConfigMap keys to uppercased and underscored environment variables. This is not a requirement of the proposal, and it would probably simplify matters if no auto-conversion was done.

**Comment by bgrant0607** [comment]
@yissachar Thanks. This is a reasonable request. Others have also encountered the same issue.

cc @pmorie

**Comment by smarterclayton** [comment]
Makes sense to me, we've heard the same thing from multiple users.

**Comment by bgrant0607** [comment]
Related to #17097

**Comment by pmorie** [comment]
I'd like to get this into 1.5.

**Comment by andrewmclagan** [comment]
Would be so great to have this in `1.5` at present the current ENV configuration scenario leaves allot of room for error when having large env var container configurations.

**Comment by dims** [comment]
@pmorie @smarterclayton @bgrant0607 - Looks like @fraenkel has a PR ready (https://github.com/kubernetes/kubernetes/pull/36245) but that does not have the 1.5 milestone set. PTAL

**Comment by bgrant0607** [comment]
@dims IMO this shouldn't go into 1.5. The feature-complete date is long past. Removing from milestone.

**Comment by dims** [comment]
@bgrant0607 awesome. thanks!

**Comment by andrewmclagan** [comment]
@bgrant0607 What is the new ETA on this landing? `1.6` ?

**Comment by deitch** [comment]
Plans for secret support as well?

**Comment by fraenkel** [comment]
It's done for secrets as well.

**Comment by deitch** [comment]
Excellent! Targeted for 1.6 as well? I think that is late March?

What's the spec for it?

```yml
envFrom:
  secretRef:
    name: my-secret
```

Or something like that?

**Comment by fraenkel** [comment]
Exactly like that.

**Comment by deitch** [comment]
Curious if there are plans to do secrets to a single file as env vars, like configMap. (this may be the wrong venue, but since we are comparing feature sets on secrets vs configmaps...)

#### Env vars
* 1.5: Consume secrets as individual env vars and configmap as env vars
* 1.6: Per this issue, also can consume all entries in configmap as env vars with `envFrom` and consume all entries in secret as env vars with `envFrom`

So parity. Nice.

#### File
* config: map all entries in configMap as a single file `subPath`
* secrets: can map each entry in secrets as individual files, but not as a single file

So no parity. Any plans to match those? Or should I open separate issue?

**Comment by smarterclayton** [comment]
What sort of file are you expecting?  A JSON representation of the config
map?  An ENV file with one line per?  How would you use this file?

**Comment by deitch** [comment]
> An ENV file with one line per? 

Yep. Exactly as I use `subPath` to map an entire configMap into a single file. There are a lot of programs out there that consume `.env` (or similar) files. It is a common way to get secrets into an app.

BTW, what's the history behind the handler "smarter" Clayton? And which ruin are you standing in front of in your avatar?

**Comment by leandrocr** [comment]
I'm sorry but I'm new to k8s and I cannot seem to find in the documentation which apiVersion should I use and what is the proper way to set this up. I have a lot of env vars for one application and this feature would be extremely handy. Thanks.

**Comment by renaudguerin** [comment]
Hi, this is a great feature but there is very little in terms of documentation (I could only find a single sentence actually : "To set environment variables, include the env or envFrom field in the configuration file.")

So, is the syntax initially suggested by @yissachar the one that eventually got in ? 

Tangential request : it would be great if documentation included the k8s versions where such features were introduced. Ansible docs for example, do this really well. Where should I complain / contribute ?

**Comment by nergdron** [comment]
+1 on the docs request, it wasn't obvious from me what the syntax needed to look like to make this work, or even that the functionality was there, until a google search turned up this ticket. Should at least have a simple example.

**Comment by andrewmclagan** [comment]
Yeah generally with k8 I have found more usful information in github issues then the docs :-/ 

Saying that I guess is a side-effect of of such a fast paced project :-)

**Comment by OrDuan** [comment]
As other mentioned, there is not enough docs on this feature.
I was trying to create a container and use the `envFrom` but go no luck since I got this error:
```
error: error validating "kubernetes/deployment-django.yaml": error validating data: found invalid field envFrom for v1.Container; if you choose to ignore these errors, turn validation off with --validate=false
```

In my yaml file I wrote:
```
    spec:
      containers:
      - name: django
        image: keyboard/backend-app
        envFrom:
          secretRef:
            name: development-secrets
```
Did I missed something ?
