### ISSUE TITLE
Kubectl warn user that they are going to delete files

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#26317]
Is it expected behavior that when:

``` console
$ kubectl delete pvc pyclaim-dev
$ kubectl delete pv py-dev
```

Are executed that ALL files on the NFS share are deleted??

Here is the pvc and the pv:

``` yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: py-dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /Users/clove/Workspace
    server: 192.168.64.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyclaim-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
```

Everything under /Users/clove/Workspace was deleted ... by by work ...
