### ISSUE TITLE
kubectl error "json: cannot unmarshal object into Go value of type string"

### ISSUE THREAD

**Issue by fedenusy** [kubernetes/kubernetes#26327]
Given `deployment.yml`:

```
kind: "Deployment"
apiVersion: "extensions/v1beta1"
metadata:
  name: "web"
  labels:
    app: "web"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "web"
    spec:
      containers:
        - name: "nginx"
          image: "REDACTED"
          env:
            - name: "TARGET_HOST"
              value: "localhost"
            - name: "TARGET_PORT"
              value: "8080"
            - name: "ENABLE_SSL"
              value: "false"
          ports:
            - name: "nginx-http"
              containerPort: 80
            - name: "nginx-https"
              containerPort: 443
          resources:
            limits:
              memory: "500Mi"
              cpu: "1000m"
          volumeMounts:
            - name: "ssl-credentials"
              mountPath: "/etc/ssl-credentials"
              readOnly: true
        - name: "web"
          image: "REDACTED"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: "/healthy"
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
          resources:
            requests:
              memory: "1000Mi"
              cpu: "250m"
            limits:
              memory: "7500Mi"
              cpu: "2000m"
      volumes:
        - name: "ssl-credentials"
          secret:
            secretName: "ssl-credentials"
      imagePullSecrets:
        - name: "ecr"
  selector:
    matchLabels:
      app: "web"
```

`kubectl create -f deployment.yml` fails with message `unable to load "deployment.yml": json: cannot unmarshal object into Go value of type string`.

Unfortunately not a very helpful error message. Any idea what I'm doing wrong?
