### ISSUE TITLE
 PATCH  one container image, the other container in the same pod is gone. 

### ISSUE THREAD

**Issue by workhardcc** [kubernetes/kubernetes#26412]
kube version:1.22 and 1.24
OS distro: centos 7.2.1511
Steps to reproduce the problem:
1.create a deployment by config file:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    add: deployment-patch
  name: deployment-patch
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  template:
    metadata:
      labels:
        name: deployment-patch
    spec:
      containers:
      - name: mofang-web
        image: docker/mofang-web:stable
        ports:
        - containerPort: 8000
      - name: mofang-web-cc
        image: docker/mofang-web-cc-2:stable
        ports:
        - containerPort: 8001
```
2.Use PATCH api to update container's image
`curl --request PATCH --header "Content-Type:application/merge-patch+json" http://10.1.1.1:8080/apis/extensions/v1beta1/namespaces/default/deployments/deployment-patch --data '{"spec":{"template":{"spec":{"containers":[{"name":"mofang-web","image":"docker\/mofang-web-cc:stable"}]}}}}'`
3.container  mofang-web-cc is gone
