### ISSUE TITLE
rkt: Liveness probe failing to restart pod

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#26456]
With rkt as the container runtime, the e2e test `Pods should be restarted with a docker exec "cat /tmp/health" liveness probe [Conformance]` fails with `expected number of restarts: %!t(int=1), found restarts: %!t(int32=0)`

I dove into it a bit further and it looks like a real issue. With additional logging it appears that the probe does fail (exec happens and returns incorrectly as expected), but when `rkt.go` calls `livenessManager.Get(ID)` it never gets that the given ID exists.

The pod definition I've been using is:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: liveness-exec
  name: liveness-exec
spec:
  containers:
    - name: liveness
      image: busybox
      command: ["sh", "-c", "echo ok >/tmp/health; sleep 10; rm -rf /tmp/health; sleep 600"]
      livenessProbe:
        initialDelaySeconds: 15
        failureThreshold: 1
        exec:
          command: ["cat", "/tmp/health"]
```

It restarts very slowly with rkt (on the order of an hour I believe, see sleep 600), but restarts very frequently with docker.

cc @sjpotter
