### ISSUE TITLE
Unable to use EBS/GCE PV when AWS/GCE host is registered via another cloud provider

### ISSUE THREAD

**Issue by alena1108** [kubernetes/kubernetes#26791]
Kubernetes 1.2.4

In Rancher we support Kubernetes as an orchestration framework, while Rancher acts as an infrastructure platform for various cloud providers (DO, AWS, GCE, etc). Rancher is registered as a cloud provider in Kubernetes, and acts as a proxy for other cloud provider's hosts. It was done to enable extra functionality provided by Rancher (overlay network as an example) in addition to functionality given by providers themselves.

Starting 1.2.4, we were unable to use Kubernetes Persistent volumes feature; the commit below disabled it for us:

```
commit c04108e90ca28e341af2bd72bcef6e09e7400763
Author: saadali <saadali@google.com>
Date:   Fri Apr 1 16:40:36 2016 -0700

    Ensure volume GetCloudProvider code uses cloud config
```

In our case, the provider in the code below is returned as a Rancher provider, not AWS cloud provider, and the error is raised.

```
cloudProvider := plugin.host.GetCloudProvider()
       awsCloudProvider, ok := cloudProvider.(*aws.AWSCloud)
       if !ok || awsCloudProvider == nil {
               return nil, fmt.Errorf("Failed to get AWS Cloud Provider. plugin.host.GetCloudProvider returned %v instead", cloudProvider)
        }
```

I wonder what is the recommended approach to unblock Persistent Volumes use for a use case like ours?

**Comment by childsb** [comment]
@alena1108 which PV features are you trying to use that this broke?

**Comment by alena1108** [comment]
@childsb just the regular volume mount/attach; here is is the RC yml example:

```
apiVersion: v1
kind: Pod
metadata:
  name: aws-web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html-volume
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: html-volume
      awsElasticBlockStore:
        # Enter the volume ID below
        volumeID: vol-f28df840  // id of the AWS volume
        fsType: ext4
```

**Comment by matchstick** [comment]
First off the k8s team wants to apologize for the long delay in our response. You have done a great job at root causing this. @saad-ali PTAL

**Comment by saad-ali** [comment]
If there are cloud providers other than Amazon, that want to support Amazon EBS volumes, then we'll need to create an EBS interface like [cinder has](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/cinder/cinder.go#L44) and then `getCloudProvider` can support multiple cloud providers.

Feel free to send out a PR to do this.

CC @justinsb @kubernetes/sig-aws

**Comment by pwittrock** [comment]
@saad-ali  I am moving this out of the blocking issues we are tracking for the 1.4 release.  If there is still 1.4 work to be done here, move it back and provide daily updates to this issue.

**Comment by pwittrock** [comment]
@matchstick fyi

**Comment by saad-ali** [comment]
Removing milestone.

**Comment by Dmitry1987** [comment]
@alena1108  was this solved somehow?  I have Kubernetes environment on rancher 1.2.1  which doesn't create LoadBalancer for services, if I try to create something like:  
```
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  namespace: $NAMESPACE
spec:
  ports:
    - port: 30001
      targetPort: 3000
  selector:
    name: $POD_NAME
  type: LoadBalancer
```

this was working for normal kubernetes 1.3 (with no rancher), but now it doesn't :(  , i tried to find a way to change "--cloud-provider=rancher"  in kubelet or api-server directives, but it's impossible. they start as containers, and no way to modify the hardcoded  "--cloud-provider"
