### ISSUE TITLE
rkt: hostPath mounts to non-existent directories fail

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#26816]
A pod referencing a nonexistent host path, such as the one below, does not run under the rkt container runtime.. However, it runs just fine under docker (which, by default, creates nonexistent paths as empty directories when a mount references them).

The pod also does not show up in `kubectl get pods` in any state, though it can still be deleted.

The latter is definitely something that should be fixed; the former is an intentional behavioural difference between rkt and docker and might be up to debate.

1) Should the pod fail? Do we need consistent behavior with docker here? Do we think that blindly creating directories on the host masks typos and is surprising?
1b) Should rkt change to this behavior, or should we create the directory before referencing it in a bindmount? (e.g. an `ExecStartPre=mkdir -p <host directories>`)
2) Pods that fail like this should still be visible in `get pods`; I think this is jut that rkt failed during stage1 and there's some over-aggressive error handling in our code that masks this pod, but I haven't dived very deeply there yet.

Example failing pod

``` yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mount-dn
  name: mount-dne
spec:
  restartPolicy: Never
  volumes:
  - name: dne
    hostPath:
      path: /does/not/exist
  containers:
    - name: exit
      image: busybox
      command: ["sh", "-c", "ls /test; sleep 60"]
      volumeMounts:
      - mountPath: /test
        name: dne
```

cc @yifan-gu @tmrts
