### ISSUE TITLE
apply failed when use init containers

### ISSUE THREAD

**Issue by AdoHe** [kubernetes/kubernetes#26840]
FYI. I am playing with init containers, and just did a simple test:

First create two pods with `apply -f`:
```
[tony@localhost kubernetes]$ cat ~/Desktop/yaml/test_k8s/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    pod.alpha.kubernetes.io/init-containers: "[{\"name\":\"wait\",\"image\":\"ubuntu:16.04\",\"command\":[\"/bin/sh\",\"-c\",\"sleep 120\"]}]"
spec:
  containers:
  - name: nginx
    image: nginx:1.9.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  restartPolicy: Never
[tony@localhost kubernetes]$ kubectl apply -f ~/Desktop/yaml/test_k8s/pod.yaml
pod "nginx" created
[tony@localhost kubernetes]$ cat ~/Desktop/yaml/test_k8s/pod_new.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginxtwo
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.9.1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  restartPolicy: Never
[tony@localhost kubernetes]$ kubectl apply -f ~/Desktop/yaml/test_k8s/pod_new.yaml
pod "nginxtwo" created
```
Then wait for while before the two pods running, update yaml files and run `apply -f` again:
```
[tony@localhost kubernetes]$ cat ~/Desktop/yaml/test_k8s/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    pod.alpha.kubernetes.io/init-containers: "[{\"name\":\"wait\",\"image\":\"ubuntu:16.04\",\"command\":[\"/bin/sh\",\"-c\",\"sleep 120\"]}]"
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  restartPolicy: Never
[tony@localhost kubernetes]$ kubectl apply -f ~/Desktop/yaml/test_k8s/pod.yaml
proto: no encoder for TypeMeta unversioned.TypeMeta [GetProperties]
proto: tag has too few fields: "-"
proto: no coders for struct *reflect.rtype
proto: no encoder for sec int64 [GetProperties]
proto: no encoder for nsec int32 [GetProperties]
proto: no encoder for loc *time.Location [GetProperties]
proto: no encoder for Time time.Time [GetProperties]
proto: no encoder for i resource.int64Amount [GetProperties]
proto: no encoder for d resource.infDecAmount [GetProperties]
proto: no encoder for s string [GetProperties]
proto: no encoder for Format resource.Format [GetProperties]
proto: no encoder for InitContainers []v1.Container [GetProperties]
proto: no coders for intstr.Type
proto: no encoder for Type intstr.Type [GetProperties]
proto: no encoder for InitContainerStatuses []v1.ContainerStatus [GetProperties]
The Pod "nginx" is invalid.
spec: Forbidden: pod updates may not change fields other than `containers[*].image` or `spec.activeDeadlineSeconds`
[tony@localhost kubernetes]$ cat ~/Desktop/yaml/test_k8s/pod_new.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginxtwo
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  restartPolicy: Never
[tony@localhost kubernetes]$ kubectl apply -f ~/Desktop/yaml/test_k8s/pod_new.yaml
pod "nginxtwo" configured
```
Seems pod validation failed when update, and I noticed the `VolumeMounts` is not equal. @smarterclayton ptal.
