### ISSUE TITLE
Create PVC failed when using labelSelector

### ISSUE THREAD

**Issue by chao007** [kubernetes/kubernetes#26866]
Description of problem:
Create PVC failed when using labelSelector

Version-Release number of selected component (if applicable):
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.5.131+68097515d82121", GitCommit:"68097515d821217918a1c916759a8373e5e5eb86", GitTreeState:"clean", BuildDate:"2016-06-06T02:42:14Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

How reproducible:
Always

Steps to Reproduce:
1.Setup k8s env
2.Create a pvc according to pr https://github.com/kubernetes/kubernetes/pull/25413

``` yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-claim-west
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      ebs-volume-type: iops-ssd
      aws-availability-zone: us-west-1
```

3.
error validating "test.yaml": error validating data: unexpected type: unversioned.LabelSelector; if you choose to ignore these errors, turn validation off with --validate=false
