### ISSUE TITLE
quantities must match the regular expression ~ cpu resource limits are forced to have unit

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#26898]
Hi all

I am on

```shell
bash-3.2$ kubectl version
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.5", GitCommit:"914163247d9a16b46921e83f7dbedb572859b3e4", GitTreeState:"clean", BuildDate:"2016-06-02T20:44:18Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.5", GitCommit:"914163247d9a16b46921e83f7dbedb572859b3e4", GitTreeState:"clean", BuildDate:"2016-06-02T20:38:51Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

Yaml that worked on head, is no longer working.  

```yaml
apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 1
  template:
    metadata:
      annotations:
        # Flip this to false after each node is stable.
        # To check the stability of a node, see kubectl logs.
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: "gcr.io/google-samples/cassandra:v9"
        imagePullPolicy: Always
        command:
          - /run.sh
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        # If you need it it is going away in C* 4.0
        #- containerPort: 9160
        #  name: thrift
        resources:
          limits:
            cpu: 1
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        # CJL figure this out
        #args:
        #- --on-start="/on-start.sh"
        #- --service=cassandra

        volumeMounts:
        # These volume mounts are persistent. They're like inline claims,
        # but not exactly because the names need to match exactly one of
        # the pet volumes.
        - name: data
          mountPath: /cassandra_data
      volumes:
        - name: data
          emptyDir: {}
  #volumeClaimTemplates:
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  #- metadata:
  #    name: data
  #    annotations:
  #      volume.alpha.kubernetes.io/storage-class: anything
  #  spec:
  #    accessModes: [ "ReadWriteOnce" ]
  #    resources:
  #      requests:
  #        storage: 10Gi
```

Was working previously.  Now I get the error:

```shell
bash-3.2$ kubectl create -f cassandra-petset-local.yaml
unable to decode "cassandra-petset-local.yaml": quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

This error is cause by:

```yaml
        resources:
          limits:
            cpu: 1
   ```

It I change is to

```yaml
        resources:
          limits:
            cpu: 250m
   ```

It works.

Is this a new feature?  If so documentation and examples needs to be fixed ...
