### ISSUE TITLE
[k8s.io] hostPath should support subPath [Conformance] failed on rktnetes

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#26986]
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/host_path.go:121
Expected error:
    <*errors.errorString | 0xc820347400>: {
        s: "pod 'pod-host-path-test' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:{Time:2016-06-07 08:35:39 +0000 UTC} FinishedAt:{Time:2016-06-07 08:38:39 +0000 UTC} ContainerID:rkt://0bf1f80a-75df-42ff-92ef-703f979039b3:test-container-2}",
    }
    pod 'pod-host-path-test' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:{Time:2016-06-07 08:35:39 +0000 UTC} FinishedAt:{Time:2016-06-07 08:38:39 +0000 UTC} ContainerID:rkt://0bf1f80a-75df-42ff-92ef-703f979039b3:test-container-2}
not to have occurred
```

cc @kubernetes/sig-node @euank @tmrts

**Comment by dchen1107** [comment]
@euank I assigned p0 issues to you since yifan is out-of town? Please delegate the issue.

**Comment by euank** [comment]
This is important for rktnetes, but I'm not sure this is actually p0. Investigating...

In a failing pod, there are the following volumes:
```
 {
      "name": "test-volume",
      "kind": "host",
      "source": "/tmp/sub-path",
      "readOnly": false
    },
...
    {
      "name": "test-volume",
      "kind": "host",
      "source": "/tmp",
      "readOnly": false
    },
```

It seems likely there is a misunderstanding between a container's volumes and them being translated to pod volumes in rkt.

**Comment by yifan-gu** [comment]
I am back in the town @dchen1107

**Comment by euank** [comment]
Further investigation: We have the assumption that volume names within a pod are unique (or at least that multiple volumes with the same name are the same volume). This isn't the case when there's a subPath specified. The kubelet transforms it into a different host volume mount per container and doesn't mutate the name. We can potentially fix this by including container-specific information (even a random id) in the volume names for the rkt.

I'm not super happy with the above solution though..

**Comment by euank** [comment]
In practice, a subPath will rarely exist I believe. That means that without some sort of resolution to #26816, this feature will typically break regardless. Even if we do decide in the referenced issue we don't want the creation of arbitrary unknown paths, we might want that here.

Based on some offline discussion with @yifan-gu, it might be best to recognize this as an unsupported feature in rktnetes 1.0 and not block on this working, in no small part because of the complexities of the above referenced issue.
We at least understand the issue now.

For my own future reference, a pod showing this:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: subpath
  name: subpath
spec:
  restartPolicy: Never
  containers:
    - name: subpath
      volumeMounts:
      - mountPath: /host-tmp-foo
        subPath: foo
        name: foo
      - mountPath: /host-tmp-bar
        subPath: bar
        name: foo
      image: busybox
      command: ["sh", "-c", "touch /host-tmp-foo/foo; touch /host-tmp-bar/bar; ls /host-tmp-bar /host-tmp-foo"]
  volumes:
  - name: foo
    hostPath:
      path: /tmp
# subPath usage above expects to create subdirectories /tmp/foo and /tmp/bar, or for them to already exist. Example use-case, mounting a EBS/GCE disk and splitting it into directories for difference containers
```
