### ISSUE TITLE
PetSet Error PersistentVolumeClaim is not bound

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#27067]
I am using 

```shell
$ ../../gce/kubernetes/cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.5", GitCommit:"914163247d9a16b46921e83f7dbedb572859b3e4", GitTreeState:"clean", BuildDate:"2016-06-02T20:44:18Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.5", GitCommit:"914163247d9a16b46921e83f7dbedb572859b3e4", GitTreeState:"clean", BuildDate:"2016-06-02T20:38:51Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

I am running creating a petset of Cassandra nodes and it is WORKING, but I am getting an error on the describe of the first pod:

```shell
$ ../../gce/kubernetes/cluster/kubectl.sh describe po cassandra-0
Name:		cassandra-0
Namespace:	default
Node:		kubernetes-minion-group-zf0y/10.128.1.238
Start Time:	Wed, 08 Jun 2016 18:45:34 +0000
Labels:		app=cassandra
Status:		Running
IP:		10.245.240.3

<removed for brevity>

---------	--------	-----	----					-------------			--------	------			-------
  8m		8m		4	{default-scheduler }							Warning		FailedScheduling	[PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0", PersistentVolumeClaim is not bound: "cassandra-data-cassandra-0"

```

The error message is repeated hundreds of times.  As I mentioned everything the PetSet starts just fine :)

Here is the yaml for the PetSet: https://github.com/chrislovecnm/gpmr/blob/1dd02269845d49a4387d2ad02ad65a719f1d4a2b/pet-race-devops/k8s/cassandra/cassandra-petset-storage.yaml

cc: @bprashanth @smarterclayton @bgrant0607

**Comment by chrislovecnm** [comment]
Just incase I delete that branch.  Here is the yaml

```yaml
apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 10
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: "gcr.io/aronchick-apollobit/cassandra:v1.0"
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        env:
          - name: MAX_HEAP_SIZE
            value: 2048M
          - name: HEAP_NEWSIZE
            value: 200M
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CASSANDRA_OPEN_JMX
            value: "true"
        # - name: CASSANDRA_GC_STDOUT
        #  value: "true"

        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "nodetool status"
          initialDelaySeconds: 60 
          timeoutSeconds: 5
        # These volume mounts are persistent. They're like inline claims,
        # but not exactly because the names need to match exactly one of
        # the pet volumes.
        volumeMounts:
        - name: cassandra-data
          mountPath: /cassandra_data

  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: ssd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
```
