### ISSUE TITLE
Preserve source ip of service.clusterIP traffic

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#27110]
This appears to be a regression. Create an nginx pod and service such as:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: echoheaders
  labels:
    app: echoheaders
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: echoheaders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.3
        ports:
        - containerPort: 8080
```
And a test pod like:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /tmp/foo
      name: test
  volumes:
  - name: test
    emptyDir: {}
  restartPolicy: Always
```

Try and get them to land on different nodes. 
```console
19:52:02-beeps~/logs]$ k get svc
NAME          CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
echoheaders   10.0.204.199   <none>        80/TCP    3h
kubernetes    10.0.0.1       <none>        443/TCP   4h

$ k exec -it busybox /bin/sh
[ root@busybox:/ ]$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue 
    link/ether 0a:58:0a:b4:01:08 brd ff:ff:ff:ff:ff:ff
    inet 10.180.1.8/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20db:d6ff:febd:ed7b/64 scope link 
       valid_lft forever preferred_lft forever
```
curl the service vip
```console
[ root@busybox:/ ]$ wget -qO- 10.0.204.199
CLIENT VALUES:
client_address=10.240.0.5
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://10.0.204.199:8080/

SERVER VALUES:
server_version=nginx: 1.9.11 - lua: 10001

HEADERS RECEIVED:
connection=close
host=10.0.204.199
user-agent=Wget
BODY:
-no body in request-
```

And in another window:
```console
19:52:42-beeps~/logs]$ k logs echoheaders-k5fs5 --follow
10.240.0.5 - - [09/Jun/2016:02:53:21 +0000] "GET / HTTP/1.1" 200 386 "-" "Wget"
```

I expected a source ip of `10.180.1.8`. We should just be DNATing to the pod ip.
I see rules like:
```
:CNI-252089a662c3409f212af1da - [0:0]
-A POSTROUTING -s 10.180.1.0/24 -m comment --comment "name: \"kubenet\" id: \"dc71fad93e755458b75b6cc3379b4f0052941ce4612a06d7c421ec5c1e522168\"" -j CNI-252089a662c3409f212af1da
-A CNI-252089a662c3409f212af1da -d 10.180.1.0/24 -m comment --comment "name: \"kubenet\" id: \"dc71fad93e755458b75b6cc3379b4f0052941ce4612a06d7c421ec5c1e522168\"" -j ACCEPT
-A CNI-252089a662c3409f212af1da ! -d 224.0.0.0/4 -m comment --comment "name: \"kubenet\" id: \"dc71fad93e755458b75b6cc3379b4f0052941ce4612a06d7c421ec5c1e522168\"" -j MASQUERADE
```

@kubernetes/sig-network @dcbw
