### ISSUE TITLE
PetSet: pod scheduling failures or unbound PVCs results in an infinite loop of PVC creation

### ISSUE THREAD

**Issue by paralin** [kubernetes/kubernetes#27174]
I tried setting a PVC without a storage-class on a PetSet so that I could manually create the volumes:

```
apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 80
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra....
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          limits:
            cpu: "3"
            memory: 4Gi
          requests:
           cpu: "3"
           memory: 4Gi
        securityContext:
          privileged: true
        env:
          - name: MAX_HEAP_SIZE
            value: 2048M
          - name: HEAP_NEWSIZE
            value: 800M
          - name: CASSANDRA_NUM_TOKENS
            value: "16"
          - name: CASSANDRA_CLUSTER_NAME
            value: Primary
          - name: CASSANDRA_SERVICE_NUM_SEEDS
            value: "2"
          - name: CASSANDRA_MIGRATION_WAIT
            value: "8"
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CASSANDRA_OPEN_JMX
            value: "true"
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 30
          timeoutSeconds: 5
        volumeMounts:
        - name: cassandra-data
          mountPath: /cassandra_data
      volumes:
        - name: cassandra-data
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
```

This resulted in over 80 pvcs being created as the lower numbered ones could not be bound, so I assume it just made more without deleting the failed ones.

The expected behavior is that the petset just waits for the PVC to bind before continuing.
