### ISSUE TITLE
SELinux label on the mounted volume

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#27282]
There is a field named `SELinuxOptions` in `PodSecurityContext`, however this is only used for the running process in containers.

For example, the following spec:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu3
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu:14.04
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    volumeMounts:
    - name: log-dir
      mountPath: /var/log/ubuntu3
  volumes:
  - name: log-dir
    hostPath:
      path: /var/log/ubuntu3
  restartPolicy: Always
  securityContext:
    seLinuxOptions:
      user: system_u
      role: object_r
      type: svirt_sandbox_file_t
      level: s0:c100,c200
```

What I am hoping is that the files under `/var/log/ubuntu3` would have type `svirt_sandbox_file_t`, however it was set on the process, not the volumes.

``` console
# ps auxZ | grep sleep
system_u:object_r:svirt_sandbox_file_t:s0:c100,c200 root 8633 0.1  0.0 4348 636 ? Ss 10:12   0:00 sleep 3600
```

My question is: Is there a way to set selinux labels for the volumes(something like `-v ${hostpath}:${containerpath}:z` in docker)?
