### ISSUE TITLE
Kubectl attach command doesn't work for InitContainters

### ISSUE THREAD

**Issue by gitfred** [kubernetes/kubernetes#27540]
Related issue https://github.com/kubernetes/kubernetes/issues/25818

**Comment by dims** [comment]
@gitfred is there a simple example that you used to recreate the problem?

**Comment by gitfred** [comment]
@dims yep. Just create for eg. RC with Initcontainer with

**Comment by gitfred** [comment]
@dims I used exactly the example below:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: sflask-w-init
spec:
  selector:
    name: web
    version: v0.1
  template:
    metadata:
      labels:
        name: web
        version: v0.1
      annotations:
        pod.alpha.kubernetes.io/init-containers: "[{\"name\":\"wait\",\"image\":\"ubuntu:16.04\",\"command\":[\"/bin/sh\",\"-c\",\"while true; date; do sleep 1; done\"]}]"
    spec:
      containers:
      - name: whatever
        image: training/webapp
        ports:
        - containerPort: 5000
```
So Pod sflask-w-init gets into penting state "Init:0/1" forever. Then you can try to run
`cluster/kubectl.sh attach sflask-w-init-<smth-random> -c wait` and you can see that is not working while invoking corresponding command with docker works - it displays current date every second.
