### ISSUE TITLE
`kubectl get cs`: incorrect hard coded master component locations

### ISSUE THREAD

**Issue by DutchakVitaliy** [kubernetes/kubernetes#27607]
I am trying to run controller-manager and scheduler on custom private ip.
But kubectl get cs trying to check health on 127.0.0.1 not on ip where they bind.

Kubernetes version: 1.2.4

**kube-controller-manager.yaml**

```
apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: 'quay.io/coreos/hyperkube:v1.2.4_coreos.0'
    command:
        - /hyperkube
        - controller-manager
        - --address=10.0.0.10
        - --master=http://127.0.0.1:8080
        - --leader-elect=true
        - --service-account-private-key-file=/etc/kubernetes/ssl/server-key.pem
        - --root-ca-file=/etc/kubernetes/ssl/ca.pem
        - --pod-eviction-timeout=30s
    livenessProbe:
      httpGet:
        host: 10.0.0.10
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true

    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
```

**kube-scheduler.yaml**

```
apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: quay.io/coreos/hyperkube:v1.2.4_coreos.0
    command:
    - /hyperkube
    - scheduler
    - --master=http://127.0.0.1:8080
    - --leader-elect=true
    - --address=10.0.0.10
    livenessProbe:
      httpGet:
        host: 10.0.0.10
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1
```

**kubectl get cs**

```
NAME                 STATUS      MESSAGE                                                                                                   ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connection refused                          
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connection refused                          
```

I think problem is here:
**pkg/master/master.go**

```
...
func (m *Master) getServersToValidate(c *Config) map[string]apiserver.Server {
    serversToValidate := map[string]apiserver.Server{
        "controller-manager": {Addr: "127.0.0.1", Port: ports.ControllerManagerPort, Path: "/healthz"},
        "scheduler":          {Addr: "127.0.0.1", Port: ports.SchedulerPort, Path: "/healthz"},
    }
...
```
