### ISSUE TITLE
pod prestop

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#27618]
Pods are useful to co-schedule multiple containers together.

We would like to use it to co-schedule things like a user code running container with a container doing nslcd for ldap support of the user code.

I want to put a preStop hook on the user container to start the drain and wait until the user's code cleanly exits (its time limited but could be hours). But the ldap container quits early. There should be a way to request that all the containers in a pod's preStop hooks are finished before TERM's are sent to any container.

Reproducer:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-shutoff
spec:
  volumes:
    - name: "data"
  containers:
    - name: test1
      image: centos:centos7
      command:
      - /bin/bash
      - -c
      - "trap exit TERM; while true; do cat /srv/date; sleep 1; done"
      volumeMounts:
      - mountPath: /srv
        name: "data"
      lifecycle:
        preStop:
          exec:
            command:
            - /bin/sh
            - -c
            - sleep 15
    - name: test2
      image: centos:centos7
      command:
      - /bin/bash
      - -c
      - "trap exit TERM; while true; do date > /srv/date; sleep 1; done"
      volumeMounts:
      - mountPath: /srv
        name: "data"
```

If you create the pod, start watching test1's logs, and delete the pod, the date printed should continue to increment until ~15 seconds after deletion starts. On my system, it stops incrementing.
