### ISSUE TITLE
having problems with secrets in AWS 

### ISSUE THREAD

**Issue by developerinlondon** [kubernetes/kubernetes#27694]
I am trying to load containers form ECR into my kubernetes stack. But it seems to work fine with docker but not if I use the kubernetes imagePullSecrets.

here is the output from the pods:
```
root@kubemaster1:~# kubectl describe pods --namespace coup
Name:		coup-app-1zxz3
Namespace:	coup
Node:		ip-172-16-20-64.eu-central-1.compute.internal/172.16.20.64
Start Time:	Sun, 19 Jun 2016 20:06:50 +0000
Labels:		name=coup-app
Status:		Pending
IP:		
Controllers:	ReplicationController/coup-app
Containers:
  coup-app:
    Container ID:	
    Image:		124243881633.dkr.ecr.eu-west-1.amazonaws.com/coup/app
    Image ID:		
    Port:		80/TCP
    Command:
      bash
      -c
      rake db:create db:migrate && rm -f tmp/pids/server.pid && bin/rails server -p 3000 -b 0.0.0.0 -d && /usr/sbin/nginx -c /etc/nginx/nginx.conf
    QoS Tier:
      memory:		BestEffort
      cpu:		BestEffort
    State:		Waiting
      Reason:		ImagePullBackOff
    Ready:		False
    Restart Count:	0
    Environment Variables:
      DATABASE_URL:	postgis://coupapp:password@app.db.coup.dev.bcginternal.com:5432
      REDIS_URL:	redis.coup.dev.bcginternal.com:6379
      RAILS_ENV:	staging
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  default-token-wcra2:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-wcra2
Events:
  FirstSeen	LastSeen	Count	From							SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----							-------------			--------	------		-------
  13m		13m		1	{default-scheduler }									Normal		Scheduled	Successfully assigned coup-app-1zxz3 to ip-172-16-20-64.eu-central-1.compute.internal
  13m		2m		7	{kubelet ip-172-16-20-64.eu-central-1.compute.internal}	spec.containers{coup-app}	Normal		Pulling		pulling image "124243881633.dkr.ecr.eu-west-1.amazonaws.com/coup/app"
  13m		2m		7	{kubelet ip-172-16-20-64.eu-central-1.compute.internal}	spec.containers{coup-app}	Warning		Failed		Failed to pull image "124243881633.dkr.ecr.eu-west-1.amazonaws.com/coup/app": image pull failed for 124243881633.dkr.ecr.eu-west-1.amazonaws.com/coup/app, this may be because there are no credentials on this request.  details: (unauthorized: authentication required)
  13m		2m		7	{kubelet ip-172-16-20-64.eu-central-1.compute.internal}					Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "coup-app" with ErrImagePull: "image pull failed for 124243881633.dkr.ecr.eu-west-1.amazonaws.com/coup/app, this may be because there are no credentials on this request.  details: (unauthorized: authentication required)"

  13m	3s	58	{kubelet ip-172-16-20-64.eu-central-1.compute.internal}	spec.containers{coup-app}	Normal	BackOff		Back-off pulling image "124243881633.dkr.ecr.eu-west-1.amazonaws.com/coup/app"
  13m	3s	58	{kubelet ip-172-16-20-64.eu-central-1.compute.internal}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "coup-app" with ImagePullBackOff: "Back-off pulling image \"124243881633.dkr.ecr.eu-west-1.amazonaws.com/coup/app\""

```

this is the pod definition:
```
root@kubemaster1:~# cat /etc/kubernetes/pods/coup/app.yml 
apiVersion: v1
kind: ReplicationController
metadata:
  name: coup-app
  namespace: coup
spec:
  replicas: 3
  selector:
    name: coup-app
  template:
    metadata:
      labels:
        name: coup-app
    spec:
      containers:
      - name: coup-app
        image: 124243881633.dkr.ecr.eu-west-1.amazonaws.com/coup/app
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: postgis://coupapp:password@app.db.coup.dev.bcginternal.com:5432
        - name: REDIS_URL
          value: redis.coup.dev.bcginternal.com:6379
        - name: RAILS_ENV
          value: staging
        command:
        - bash
        - -c
        - 'rake db:create db:migrate && rm -f tmp/pids/server.pid && bin/rails server -p 3000 -b 0.0.0.0 -d && /usr/sbin/nginx -c /etc/nginx/nginx.conf'
      imagePullSecrets:
      - name: eu-west-1-ecr-registry

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: coup-app
    role: service
  name: coup-app
  namespace: coup
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: coup-app
  type: LoadBalancer

```

and this is the secrets file:

```
$ cat /etc/kubernetes/pods/coup/secret.yml 

apiVersion: v1
kind: Secret
metadata:
  name: eu-central-1-ecr-registry
  namespace: coup
data:
  .dockerconfigjson: <output from running base64 on ~/.docker/config.json that was produced by running aws ecr get-login --region=eu-west1 to start with>
type: kubernetes.io/dockerconfigjson
```

and this is the output from kubectl secrets:
```
root@kubemaster1:~# kubectl get secrets --namespace coup
NAME                        TYPE                                  DATA      AGE
default-token-wcra2         kubernetes.io/service-account-token   2         1h
eu-central-1-ecr-registry   kubernetes.io/dockerconfigjson        1         14m
root@kubemaster1:~# 
```

any ideas what i am doing wrong here or how i can resolve this? its been driving me nuts all day today.
