### ISSUE TITLE
After rolling update, old pod still lying around

### ISSUE THREAD

**Issue by luispabon** [kubernetes/kubernetes#27721]
Whenever I do a rolling update of a replication controller with an image, the originally deployed pod is kept alive on the cluster. For instance, if I deploy a new application, version 1 gets deployed. After a number of deployments, both original version 1 and version X are active.

Not only that, replication controllers seem messed up. If I describe the pods in question, they each are in a different replication controller (the original rc with the original pod, and a new one with the new pod). But if I go into the kubernetes kube-ui dashboard, the OLD rc is linked to the NEW pod.

Also, the describe command reckons the OLD rc and pod started AFTER the new one.

Old and new version are load balanced on the service, and clients are served 50% of the time from old code.

Quite a few things not right here. 

I'm roll-updating via `kubectl rolling-update rc-name --image=new/image:version`.

Kubernetes 1.2.4, deployed on AWS via supplied scripts. Images are built with docker 1.10 and stored at amazon's ECR.

Yaml config (service, horizontal autoscaling and rc):

``` yml
## PHP Service and replication controllers
apiVersion: v1
kind: Service
metadata:
  name: api-runtime
  labels:
    app: api-runtime
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: api-runtime-pod

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: api-runtime-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-runtime-pod
    spec:
      containers:
      - name: api-runtime-pod
        imagePullPolicy: Always
        image: xxxxx.amazonaws.com/xxxxxx:master-20
        ports:
          - containerPort: 9000
        env:
          - name:  APP_DEV_MODE
            value: '0'

---

# Pod horizontal autoscaling
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api-runtime-hpa
  namespace: default
spec:
  scaleRef:
    kind: ReplicationController
    name: api-runtime-rc
    subresource: scale
  minReplicas: 1
  maxReplicas: 4
  cpuUtilization:
    targetPercentage: 70

```

```
[development@localhost ~/B/b/kubernetes] (master) kubectl describe service api-runtime
Name:           api-runtime
Namespace:      default
Labels:         app=api-runtime
Selector:       app=api-runtime-pod
Type:           NodePort
IP:         10.0.54.148
Port:           <unset> 9000/TCP
NodePort:       <unset> 31131/TCP
Endpoints:      10.244.1.5:9000,10.244.2.7:9000
Session Affinity:   None
No events.
```

```
[development@localhost ~/B/b/kubernetes] (master) kubectl describe pod api-runtime-rc
Name:       api-runtime-rc-a11ad91f9295fecc40b2424c94fbc86e-j2knj
Namespace:  default
Node:       ip-172-20-0-177.eu-west-1.compute.internal/172.20.0.177
Start Time: Mon, 20 Jun 2016 14:55:28 +0100
Labels:     app=api-runtime-pod,deployment=a11ad91f9295fecc40b2424c94fbc86e
Status:     Running
IP:     10.244.2.7
Controllers:    ReplicationController/api-runtime-rc-a11ad91f9295fecc40b2424c94fbc86e
Containers:
  api-runtime-pod:
    Container ID:   docker://a3bba0dffce65b73ea5ef54e2df17420bc411c932bde216793c215667425d40a
    Image:      xxxxxx.amazonaws.com/xxxxxx:master-23
    Image ID:       docker://06617122419a7741728b0117bc327b6cc85990d68f1bcbb8671b71c6db396ca9
    Port:       9000/TCP
    QoS Tier:
      cpu:  Burstable
      memory:   BestEffort
    Requests:
      cpu:      100m
    State:      Running
      Started:      Mon, 20 Jun 2016 14:55:32 +0100
    Ready:      True
    Restart Count:  0
    Environment Variables:
      APP_DEV_MODE:     0

Conditions:
  Type      Status
  Ready     True 
Volumes:
  default-token-g84wh:
    Type:   Secret (a volume populated by a Secret)
    SecretName: default-token-g84wh
No events.

Name:       api-runtime-rc-hmuo7
Namespace:  default
Node:       ip-172-20-0-228.eu-west-1.compute.internal/172.20.0.228
Start Time: Mon, 20 Jun 2016 14:56:38 +0100
Labels:     app=api-runtime-pod,deployment=ee9a49bd7a578f054e7c31762f47cdf0
Status:     Running
IP:     10.244.1.5
Controllers:    ReplicationController/api-runtime-rc
Containers:
  api-runtime-pod:
    Container ID:   docker://1d586edc2dbd051e5010274145355f5c19191663daf7524d0b2dc6e4c6d3cb34
    Image:      xxxxx.amazonaws.com/xxxxx:master-20
    Image ID:       docker://7506e66c6df9a32d048a76b29287376f3619ea8e03b52d7f91beb9180f6e1bc2
    Port:       9000/TCP
    QoS Tier:
      cpu:  Burstable
      memory:   BestEffort
    Requests:
      cpu:      100m
    State:      Running
      Started:      Mon, 20 Jun 2016 14:56:39 +0100
    Ready:      True
    Restart Count:  0

Conditions:
  Type      Status
  Ready     True 
Volumes:
  default-token-g84wh:
    Type:   Secret (a volume populated by a Secret)
    SecretName: default-token-g84wh
No events.

```

```
[development@localhost ~/B/b/kubernetes] (master) kubernetes-dist/cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
```

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by pwittrock** [comment]
@AdoHe Are you able to reproduce this?

**Comment by kargakis** [comment]
@luispabon  are the old pods in Terminating phase? Can you post the output of `kubectl get pods` when you hit this?

**Comment by luispabon** [comment]
@kargakis they aren't, they show as running:

```
[development@localhost ~/B/b/kubernetes] (master) kubectl get pods
NAME                                                              READY     STATUS    RESTARTS   AGE
admin-frontend-rc-a5a6fac9ca1d292424e9be48b29d7ddo1wl             1/1       Running   0          3h
admin-runtime-rc-1fb70988738ec09decc45b7f1d97851rob6u             1/1       Running   0          3h
api-runtime-rc-7e475aa105964f8c516f7be7e03e97b3-zc2co             1/1       Running   0          3h
api-webserver-rc-8d435779a6f767e4d71786deb6607158e3tk             1/1       Running   0          3h
api-webserver-rc-z1ody                                            1/1       Running   0          6h
image-server-rc-67d98f5a662d2e5003bab154f7396fed-ef459            2/2       Running   0          3h
image-server-rc-tmbde                                             2/2       Running   0          3h
redis-rc-xe2su                                                    1/1       Running   0          4d
ssl-termination-rc-j8g9n                                          1/1       Running   4          4d
users-rc-p91dq                                                    1/1       Running   0          4d
```

In this case, api-webserver and image-server show this problem.

**Comment by luispabon** [comment]
```

**Comment by AdoHe** [comment]
Try to reproduce but not success, will check it again.

**Comment by ConradIrwin** [comment]
I think I'm also seeing this (if not, please move this to a new issue). Using kubectl/master/nodes all 1.3.5 on Google Container Engine:

I have a replication controller with gracefulTermination set to 30s, and configured to keep 4 instances up:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    kubectl.kubernetes.io/next-controller-id: backend-9737fb380f8dd8cb62f50988b66dae97
    kubectl.kubernetes.io/original-replicas: "2"
  creationTimestamp: 2016-08-31T03:03:52Z
  generation: 4
  labels:
    name: backend
  name: backend
  namespace: default
  resourceVersion: "8229060"
  selfLink: /api/v1/namespaces/default/replicationcontrollers/backend
  uid: 8befc817-6f27-11e6-aecc-42010af00038
spec:
  replicas: 1
  selector:
    deployment: bd1ac26c2804017445331454ab0e9b7f
    name: backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: bd1ac26c2804017445331454ab0e9b7f
        name: backend
    spec:
      containers:
      - command:
        - /main
        image: us.gcr.io/superhuman-inc/backend:1472604379
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080
          name: backend
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/production-env/
          name: production-env-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: production-env-volume
        secret:
          secretName: production-env
status:
  fullyLabeledReplicas: 3
  observedGeneration: 4
  replicas: 3
```

Now I run `kubectl rolling-update backend --image=X --image-pull-policy=Always --update-period=1s` lots of times!

The first time it succeeds (yay, the deploy worked), the second time, it fails:

```
kubectl rolling-update backend --image=us.gcr.io/superhuman-inc/backend:1472604379 --image-pull-policy=Always --update-period=1s
Found existing update in progress (backend-9737fb380f8dd8cb62f50988b66dae97), resuming.
Continuing update with existing controller backend-9737fb380f8dd8cb62f50988b66dae97.
Scaling up backend-9737fb380f8dd8cb62f50988b66dae97 from 2 to 4, scaling down backend from 2 to 0 (keep 4 pods available, don't exceed 5 pods)
Scaling backend-9737fb380f8dd8cb62f50988b66dae97 up to 3
Scaling backend down to 1
error: timed out waiting for the condition
```

Looking at the replication controller, it is correctly desiring only 1 node, but it currently has 3, and it is not making any effort to terminate them.

I keep running the command, until it succeeds. At which point it deletes my old replication controller and renames the new one. At this point it has too many nodes (this run through 5 when it expects 4)

```
kubectl rolling-update backend --image=us.gcr.io/superhuman-inc/backend:1472604379 --image-pull-policy=Always --update-period=1s
Found existing update in progress (backend-9737fb380f8dd8cb62f50988b66dae97), resuming.
Continuing update with existing controller backend-9737fb380f8dd8cb62f50988b66dae97.
Scaling up backend-9737fb380f8dd8cb62f50988b66dae97 from 4 to 4, scaling down backend from 0 to 0 (keep 4 pods available, don't exceed 5 pods)
Update succeeded. Deleting old controller: backend
Renaming backend-9737fb380f8dd8cb62f50988b66dae97 to backend
replicationcontroller "backend" rolling updated
```

```
kubectl describe rc backend
Name:		backend
Namespace:	default
Image(s):	us.gcr.io/superhuman-inc/backend:1472604379
Selector:	deployment=75efa8a6bae31c2c874b58936d020405,name=backend
Labels:		name=backend
Replicas:	4 current / 4 desired
Pods Status:	4 Running / 0 Waiting / 0 Succeeded / 0 Failed
Volumes:
  production-env-volume:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	production-env
No events.
```

```
kubectl get pods | grep backend
backend-9737fb380f8dd8cb62f50988b66dae97-bfj8b   1/1       Running   0          17m
backend-9737fb380f8dd8cb62f50988b66dae97-iiz58   1/1       Running   0          17m
backend-9737fb380f8dd8cb62f50988b66dae97-it1po   1/1       Running   0          2m
backend-9737fb380f8dd8cb62f50988b66dae97-k0t5k   1/1       Running   0          19m
backend-9737fb380f8dd8cb62f50988b66dae97-nqeex   1/1       Running   0          14m
```

```
kubectl describe pods backend | grep Controllers
Controllers:	ReplicationController/backend-9737fb380f8dd8cb62f50988b66dae97
Controllers:	ReplicationController/backend-9737fb380f8dd8cb62f50988b66dae97
Controllers:	ReplicationController/backend-9737fb380f8dd8cb62f50988b66dae97
Controllers:	ReplicationController/backend-9737fb380f8dd8cb62f50988b66dae97
Controllers:	ReplicationController/backend-9737fb380f8dd8cb62f50988b66dae97
```

So now I'm stuck in this state where I have 5 pods attached to the rc, but it only knows about 4 of them.

If I now run yet-another deploy (but with a new image this time) it will only cycle 4 of my nodes, leaving the last one uncycled.

```
kubectl describe pods backend | grep Image:
    Image:		us.gcr.io/superhuman-inc/backend:1472613819
    Image:		us.gcr.io/superhuman-inc/backend:1472613819
    Image:		us.gcr.io/superhuman-inc/backend:1472613819
    Image:		us.gcr.io/superhuman-inc/backend:1472613819
    Image:		us.gcr.io/superhuman-inc/backend:1472604379
```
