### ISSUE TITLE
consider a tmpfs storage class 

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#27732]
This should be easy to write and it makes iterating on petset development fast. Sometimes you just want some fast storage for each pet, simply `/tmp/ns_petname` should do. The petset will create the appropriate claims, we just need a provisioner that creates a pv (based on the storage class annotation) that takes the pvc name and shoves it under the hostPath, eg:

``` yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-provisioning-test
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/default_foo-0
```

I know this sounds similar to datagravity but it's mostly for dev work, nothing serious. 
@kubernetes/sig-storage
