### ISSUE TITLE
Verify that Job behaves properly across master/node upgrade

### ISSUE THREAD

**Issue by davidopp** [kubernetes/kubernetes#27968]
There are some notes on this in a separate doc, it's not worth pasting it in right now, @erictune understands what to investigate.

**Comment by erictune** [comment]
This is not new to 1.3 because job impl. did not change in 1.3.
The behavior is curious (more pods ran than expected), but pods need to be idempotent, so this is more of a curiosity than a release blocker.

**Comment by soltysh** [comment]
Is this related to #27997 or this is something different?

**Comment by erictune** [comment]
David asked for an example of a Job YAML that would run for a few minutes, and a some test criteria for a manual test that when the cluster was upgraded, and nodes and master replaced, that the job still finished.  I provided this one:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: long
spec:
  template:
    metadata:
      name: long
    spec:
      containers:
      - name: c
        image: busybox
        command: ["/bin/sh",  "-c", "sleep 1800"]
      restartPolicy: Never
  parallelism: 3
  completions: 3
```

@gmarek manually tested that the job kept running despite an upgrade during that `1800` second period.  It did, which was good.

We noted that the `kubectl describe jobs` doesn't show events for pods that are "lost" and need to be replaced, for reasons other than exiting with failure.  That could be a nice feature, but goes in a separate issue.  

Closing this one.
