### ISSUE TITLE
GCE L7 Ingress floods backend with health requests

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#28028]
When using the Ingress object on GKE it creates a GCE L7 load balancer with a health check testing the Ingress backend at an interval of 1 second. 

It does this through each cluster node though - to make sure a node is healthy - resulting in an amount of traffic towards the backend that scales with the number of nodes in cluster. 

Imagine a 1000 node cluster with a 1 pod application. It will receive a 1000 requests per second for just a health check. This is not an optimal situation.

The Ingress object is created with the following manifest

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:  
  name: service-name
spec:
  backend:
    serviceName: service-name
    servicePort: 80
  tls:
  - secretName: tls-secret
```
