### ISSUE TITLE
"requests: alpha.kubernetes.io/nvidia-gpu: 1", Error: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#28199]
Hey guys,

Here, I added "--experimental-nvidia-gpus=1" arguments into function of start_kubelet in /hack/local-up-cluster.sh, and the local cluster running, the cluster info like below:
```
            "status": {
                "capacity": {
                    "alpha.kubernetes.io/nvidia-gpu": "1",
                    "cpu": "2",
                    "memory": "3884184Ki",
                    "pods": "110"
                },
                "allocatable": {
                    "alpha.kubernetes.io/nvidia-gpu": "1",
                    "cpu": "2",
                    "memory": "3884184Ki",
                    "pods": "110"
                },
```
It seems running normal for supporting GPU devices, but when I create Pod, it return error:
```
mapping values are not allowed in this context
```
the Pod Yaml content as below:
```
apiVersion: v1
kind: Pod
metadata:
  name: jian-gpu
  namespace: default
spec:
  containers:
  - name: jian-gpu
    image: ubuntu_1404_x86_cuda:latest
    resources:
      requests: alpha.kubernetes.io/nvidia-gpu: 1
```
Have someone know the solution?
