### ISSUE TITLE
Zone dependant mount target for NFS (or referencing AZ based services in zone agnostic way)

### ISSUE THREAD

**Issue by goblain** [kubernetes/kubernetes#28226]
AWS announced general availability of the EFS today and I'm looking into possibility of using it with my k8s cluster. The tricky part here is that I run a multi-AZ setup hence it would be optimal if I could mount from NFS server (aka EFS mount target) in the same zone, so obviously

```
- name: somevol
  nfs:
    server: eu-west-1b.fs-xxxxxxxx.efs.eu-west-1.amazonaws.com
    path: "/"
```

will not do the trick... initially my idea was that it would be nice if I could reference node label in server name like `<failure-domain.beta.kubernetes.io/zone>.fs-xxxxxxxx.efs.eu-west-1.amazonaws.com`. 

After quick chat @justinsb suggested that maybe kubernetes own DNS could handle such cases.

Another approach could be based on k8s service with hardcoded endpoints, as long as endpoint can be labeled with AZ and kube-proxy can be forced into sort of "use AZ local endpoints first if available" mode
