### ISSUE TITLE
kubectl apply for service errors on spec.ports[0].name

### ISSUE THREAD

**Issue by geriBatai** [kubernetes/kubernetes#28225]
Kubectl fails modifying existing service resource when changing it's ports. To reproduce:

kubectl version 1.2.4
api version 1.2.2

original spec, for kubectl create:

```
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    name: myservice
spec:
  ports:
  - port: 80
    protocol: TCP
    name: tcp-80
    targetPort: 80
  selector:
    name: myservice
```

modified spec, for kubectl apply:
```
apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    name: myservice
spec:
  ports:
  - port: 81
    protocol: TCP
    name: tcp-81
    targetPort: 81
  selector:
    name: myservice
```

Running kubectl apply on the second definition generates the following error:

```
spec.ports[0].name: Required value
```

Debug info shows that it fails PATCH command, because generated diff omits "name". Excerpt from request body:

```
"spec":{"ports":[{"$patch":"delete","port":81},{"name":"tcp-port","port":80,"protocol":"TCP
","targetPort":80}]
```
