### ISSUE TITLE
Feature: LifnessProbe based on parsing log.

### ISSUE THREAD

**Issue by Trane9991** [kubernetes/kubernetes#28345]
Would be very nice to have feature of Lifness/Readness Probe based of pod logs.

For example: Mark pod as unhealthy if "Started" not appeared in the logs in the 30 sec period duting pod start.

```
          livenessProbe:
            logsReader:
              stdout: true
              stderr: true
              regexp: "Started"
              readFrom: "BOF"
              findOnce: true
            initialDelaySeconds: 100
            timeoutSeconds: 10
```

or checking some periodically log to ensure application is working

```
          livenessProbe:
            logsReader:
              stdout: true
              stderr: true
              regexp: "\d* bytes received"
              readFrom: "EOF"
              findOnce: false
            initialDelaySeconds: 100
            checkPeriod: 200
            timeoutSeconds: 10
```

Thank you.
