### ISSUE TITLE
Daemons started on master node are not reachable

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#28356]
In v1.2.5 Daemon Pods are started on master machine, which is Unschedulable (this may be a problem, or not - I'm not certain what the decision was). For some reason Pod that is started on master machine is not reachable from other machines (it's reachable from master though). After upgrade to v1.3.0-beta.3 problem persists.

Repro:
- start a cluster (certainly from 1.2 branch, but I think it'll work the same on 1.3)
- create a daemon set:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: daemon
  name: daemon
spec:
  template:
    metadata:
      labels:
        app: daemon
    spec:
      containers:
      - image: gcr.io/google_containers/serve_hostname:v1.4
        name: servehostname
        ports: 
        - containerPort: 9376
```
- `kubectl get pod -o wide`
- find out which pod runs on the master machine
- `kubectl describe <that pod>`, find Pod IP
- ssh to any node and try `curl <pod IP>:9376` - it should hang.
- profit!

(to verify you can try curling any other daemon pod, which should work)

cc @fgrzadkowski @davidopp @erictune
