### ISSUE TITLE
another-annotation-key: another-annotation-value with preferresDuringSchedulingIgnoredDuringExecution

### ISSUE THREAD

**Issue by dvohra** [kubernetes/kubernetes#28376]
Kubernetes version 1.2.5
Kubectl 1.2.5
Multi node cluster
Multi etcd cluster

If _nodeAffinity_ is set to _preferresDuringSchedulingIgnoredDuringExecution_ and the _another-annotation-key: another-annotation-value_ is also set, according to documentation "In addition, among nodes that meet that criteria, nodes with a label whose key is another-annotation-key and whose value is another-annotation-value should be preferred." But, the preferresDuringSchedulingIgnoredDuringExecution setting is used. 

For example, two nodes node1 and node2
node1 has label _kubernetes.io/image-name: nginx_ and node2 has label _kubernetes.io/image-name: hello-world_. The following pod.yaml is used.

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: with-labels
  annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
        "nodeAffinity": {
          "preferresDuringSchedulingIgnoredDuringExecution": {
            "nodeSelectorTerms": [
              {
                "matchExpressions": [
                  {
                    "key": "kubernetes.io/image-name",
                    "operator": "In",
                    "values": ["nginx", "hello-world"]
                  }
                ]
              }
            ]
          }
        }
      }
    kubernetes.io/image-name: hello-world
spec:
  containers:
- name: with-labels
    image: nginx
```

The kubectl create -f pod.yaml command should start a Pod on the node2 as it has the label kubernetes.io/image-name: hello-world which is specified in _another-annotation-key and whose value is another-annotation-value_, but the the Pod is scheduled on node1.

For the requiredDuringSchedulingIgnoredDuringExecution nodeAffinity the node with label _another-annotation-key and whose value is another-annotation-value_ is used. 

Seems like the label with _another-annotation-key and whose value is another-annotation-value_ is preferred if nodeAffinity is requiredDuringSchedulingIgnoredDuringExecution but not if nodeAffinity is   preferresDuringSchedulingIgnoredDuringExecution.

**Comment by ncdc** [comment]
It looks like maybe you have a typo? `preferresDuringSchedulingIgnoredDuringExecution` should be `preferredDuringSchedulingIgnoredDuringExecution` (preferre**d**, not preferre**s**). Or are you using `preferredDuringSchedulingIgnoredDuringExecution` and it's still not working?

**Comment by dvohra** [comment]
I had also used "preferred" but an error was generated and turned out nodeAffinity prefix is "preferres".
Refer
http://kubernetes.io/docs/user-guide/node-selection/

Should be "prefers" if it has to be as "preferres" is misspelled. 

And the setting preferresDuringSchedulingIgnoredDuringExecution does have a use case when none of the nodes have a label matching the nodeAffinity label. Another node with non-matching label is used with preferresDuringSchedulingIgnoredDuringExecution as tested. "preferresDuringSchedulingIgnoredDuringExecution" is fine; it is just that when used with "another-annotation-key and whose value is another-annotation-value" the "another-annotation-key and whose value is another-annotation-value" is not preferred as in the documentation. "In addition, among nodes that meet that criteria, nodes with a label whose key is another-annotation-key and whose value is another-annotation-value should be preferred."

**Comment by ncdc** [comment]
Looking at the code, I'm seeing that it should be "preferred". It's possible the documentation has a typo. What error were you getting?

I'm also confused by the documentation stating that the scheduler should take into account arbitrary annotations on a pod to give higher weights to nodes with labels that match said annotations. @kubernetes/sig-scheduling @ingvagabund is the documentation correct or incorrect?

**Comment by dvohra** [comment]
![preferred-errormessage](https://cloud.githubusercontent.com/assets/3654431/16536704/12af0134-3faa-11e6-99b3-d9eb9cd794df.jpg)

Error message output is enclosed.

**Comment by ncdc** [comment]
@dvohra I tested on Kube 1.3 (I realize you're testing on 1.2.5), and I had to change the pod definition to make it work. This is what worked for me:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: with-labels
  annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
        "nodeAffinity": {
          "preferredDuringSchedulingIgnoredDuringExecution": [
            {
              "weight": 75,
              "preference":
              {
                "matchExpressions": [
                  {
                    "key": "kubernetes.io/image-name",
                    "operator": "In",
                    "values": ["nginx", "hello-world"]
                  }
                ]
              }
            }
          ]
        }
      }
    kubernetes.io/image-name: hello-world
spec:
  containers:
  - name: with-labels
    image: nginx
```

I had to tweak the contents of `scheduler.alpha.kubernetes.io/affinity` to get it to pass validation.
