### ISSUE TITLE
bad error for deployment with no labels

### ISSUE THREAD

**Issue by rbtcollins** [kubernetes/kubernetes#28475]
This trivial deployment:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu-debug:latest
        command:
        - sleep
        - "3600"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
```

Which is missing the metadata.labels map, gives a misleading error:

```
The Deployment "ubuntu-deployment" is invalid.

* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: null: `selector` does not match template `labels`
```

The spec.selector is defined in the API docs as optional, not required.
