### ISSUE TITLE
configmap behaviour change since v1.2.0

### ISSUE THREAD

**Issue by asalkeld** [kubernetes/kubernetes#28502]
In v1.2.0 we could do the following:

```
apiVersion: v1
kind: ConfigMap
data:
  configs: "configs"
  network: "network"
  start-script: "import time; time.sleep(3600)"
metadata:
  name: openstack-default-files

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - args: [bash, -c,
           'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 1; done']
        image: ubuntu:latest
        name: ubuntu
        volumeMounts:
        - mountPath: /etc/whatever
          name: global-volume
        - mountPath: /opt/script/bin
          name: script-volume
      restartPolicy: Always
      volumes:
      - configMap:
          items:
          - key: configs
            path: globals.yaml
          - key: network
            path: network_topology.yaml
          name: openstack-default-files
        name: global-volume
      - configMap:
          items:
          - key: start-script
            path: start_script.py
          name: openstack-default-files
        name: script-volume
```
i.e. mulitple configmap volumes could reference one configmap.
(note that both volumes reference "openstack-default-files")

Since https://github.com/kubernetes/kubernetes/commit/9b6a505f8a28edacb5aae00b951e61806901a59a (or the one before - this commit does not build) we can not do this, but have to have a one to one mapping of configmap-volume to configmap.

The question is: Is this intentional or a regression?
@saad-ali ^
