### ISSUE TITLE
petset pods should not scheduled on the same node

### ISSUE THREAD

**Issue by tweakmy** [kubernetes/kubernetes#28532]
I followed the guide to http://kubernetes-v1-3.github.io/docs/getting-started-guides/ubuntu-calico/ to setup a 1 master 2 node on a local vm. 

Using http://kubernetes-v1-3.github.io/docs/user-guide/petset/ and glusterfs, I was able to create petset with 2 replica, however, after manually killing one pods, it still schedule 2 petset pods on the same node. Not sure this is intended due to alpha state.

Could you suggest a work around?

**Comment by chrislovecnm** [comment]
@bprashanth can you use node or pod affinity to handle this?  @tweakmy this is a scheduling issue not a petset issue persay

**Comment by bprashanth** [comment]
Yeah either pod anti affinity (https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/design/podaffinity.md), or simply set `hostPort` in the `podTemplate` (eg: https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/rc.yaml#L35).

**Comment by bprashanth** [comment]
Please send an example for glusterfs deployment if it works out (it would help others), closing this issue for now

**Comment by tweakmy** [comment]
Gluster deployment

endpoints

```
kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.100.173
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.100.159
    ports:
      - port: 1
```
service.yaml

```
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1
```



pv.yaml 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-default-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: testvol
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-default-volume2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: testvol2
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
```
