### ISSUE TITLE
Possible Bug: `kubectl get svc blah -o yaml --export` output invalid for import

### ISSUE THREAD

**Issue by osterman** [kubernetes/kubernetes#28548]
We use `kubectl get` together with `-o yaml --export` to take backups of resources in our cluster. The problem is when we `--export` services, they cannot be reimported unless we edit them to remove invalid data. 
## what
- Running `kubectl get svc blah -o yaml --export` outputs invalid `spec.clusterIP` (we see the value as `<unknown>`)
## expectation
- `spec.clusterIP` should be blank if it's not explicitly set (which is our case)
## reproducing
1. define a new `Service` resource without a `spec.ClusterIP` 
2. Run `kubectl get svc blah -o yaml --export | kubectl apply -f -`
## output yaml

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"edge-router","selfLink":"/api/v1/namespaces//services/edge-router","creationTimestamp":null,"labels":{"app":"edge-router","serial":"3","tier":"frontend"}},"spec":{"ports":[{"name":"http","protocol":"TCP","port":80,"targetPort":30630}],"selector":{"app":"edge-router","tier":"frontend"},"type":"NodePort","sessionAffinity":"None"},"status":{"loadBalancer":{}}}'
  creationTimestamp: null
  labels:
    app: edge-router
    serial: "3"
    tier: frontend
  name: edge-router
  selfLink: /api/v1/namespaces//services/edge-router
spec:
  clusterIP: <unknown>
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 30630
  selector:
    app: edge-router
    tier: frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
## error

```
proto: no encoder for TypeMeta unversioned.TypeMeta [GetProperties]
proto: tag has too few fields: "-"
proto: no coders for struct *reflect.rtype
proto: no encoder for sec int64 [GetProperties]
proto: no encoder for nsec int32 [GetProperties]
proto: no encoder for loc *time.Location [GetProperties]
proto: no encoder for Time time.Time [GetProperties]
proto: no coders for intstr.Type
proto: no encoder for Type intstr.Type [GetProperties]
The Service "edge-router" is invalid.

* spec.clusterIP: Invalid value: "\u003cunknown\u003e": field is immutable
* spec.clusterIP: Invalid value: "\u003cunknown\u003e": must be empty, 'None', or a valid IP address
```
