### ISSUE TITLE
Possible Bug: `kubectl get svc --export` omits `NodePort`

### ISSUE THREAD

**Issue by osterman** [kubernetes/kubernetes#28551]
We've defined a `Service` that needs to be port-bound to the host-machine on a specific port, which is then associated with our ELB. This `Service` fronts a `Deployment` that acts like our "mesh" router (which we call `edge-router`). When we `--export` a service, the `nodePort` we originally defined is dropped. Upon re-import, it will be assigned some random `nodePort`.
## what
- Using `--export` with `kubectl get svc` causes `nodePort` to be dropped, even if it was explicitly set
## expectation
- Using `--export` option should produce output that resembles original resource as submitted by using `kubectl apply`
- If the original resource was created with an explicit `nodePort`, the value should be preserved when using `--export`
## reproduction
1. create a new service called `foo` with an explicit `nodePort` defined
2. `apply` the `foo` service 
3. run `kubectl get svc foo -o yaml --export`
4. observe that the `nodePort` is missing

**Comment by osterman** [comment]
Interestingly enough, if you omit the service name (e.g. `foo`) and use `--export`, the `nodePort` is preserved and the `clusterIP` is set! See below.

Running `kubectl get svc edge-router -o yaml  --export`
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"edge-router","namespace":"sagan","selfLink":"/api/v1/namespaces/sagan/services/edge-router","uid":"a64dcfb5-43b7-11e6-b3a0-02420af41304","resourceVersion":"4935797","creationTimestamp":"2016-07-06T20:24:32Z","labels":{"app":"edge-router","serial":"3","tier":"frontend"}},"spec":{"ports":[{"name":"http","protocol":"TCP","port":80,"targetPort":30630,"nodePort":32310}],"selector":{"app":"edge-router","tier":"frontend"},"clusterIP":"10.100.142.57","type":"NodePort","sessionAffinity":"None"},"status":{"loadBalancer":{}}}'
  creationTimestamp: null
  labels:
    app: edge-router
    serial: "3"
    tier: frontend
  name: edge-router
  selfLink: /api/v1/namespaces//services/edge-router
spec:
  clusterIP: <unknown>
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 30630
  selector:
    app: edge-router
    tier: frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```


Running `kubectl get svc -o yaml --export`, filtering for `edge-router`
```
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"edge-router","namespace":"sagan","selfLink":"/api/v1/namespaces/sagan/services/edge-router","uid":"a64dcfb5-43b7-11e6-b3a0-02420af41304","resourceVersion":"4935797","creationTimestamp":"2016-07-06T20:24:32Z","labels":{"app":"edge-router","serial":"3","tier":"frontend"}},"spec":{"ports":[{"name":"http","protocol":"TCP","port":80,"targetPort":30630,"nodePort":32310}],"selector":{"app":"edge-router","tier":"frontend"},"clusterIP":"10.100.142.57","type":"NodePort","sessionAffinity":"None"},"status":{"loadBalancer":{}}}'
    creationTimestamp: 2016-07-06T20:24:32Z
    labels:
      app: edge-router
      serial: "3"
      tier: frontend
    name: edge-router
    namespace: sagan
    resourceVersion: "4936314"
    selfLink: /api/v1/namespaces/sagan/services/edge-router
    uid: a64dcfb5-43b7-11e6-b3a0-02420af41304
  spec:
    clusterIP: 10.100.142.57
    ports:
    - name: http
      nodePort: 32310
      port: 80
      protocol: TCP
      targetPort: 30630
    selector:
      app: edge-router
      tier: frontend
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
```

**Comment by osterman** [comment]
Behavior observed in k8s 1.2.4 & 1.3.0

**Comment by osterman** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/28548

**Comment by AdoHe** [comment]
@osterman Thanks for reporting. Actually when you use `kubectl get --export`, the exported resource is stripped off cluster-specific information. In you example, the nodePort and clusterIP of service are stripped off. However I do think there is a bug when using `--export` with resource list, we should forbid export when retrieving list, this options should only be used when get singular resource. @kubernetes/kubectl

**Comment by osterman** [comment]
@AdoHe Thanks - that helps explain what's going on. I'd prefer that `--export` work for lists as well. I also think "cluster-specific" should be qualified. Fields dynamically generated by the *cluster* should be stripped off with `--export`; however, fields that I specify should always be preserved by exports. I also think that the following fields should be stripped from exports because they were generated by the *cluster*. We do this currently with `sed -E /\b(creationTimestamp|resourceVersion|uid|selfLink):/d`.

**Comment by AdoHe** [comment]
@kubernetes/kubectl I think there are two things we need to with export: 1. "cluster-specific" should be qualified, or users will get confused. 2. how export should work with list resources.

**Comment by babin93** [comment]
Hi, 
I am having a similar issue.
I have some services similar to this one

**InitialService.yaml**
```
apiVersion: v1
kind: Service
metadata:
  name: someName
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 1234
  selector:
    app: someName
```
When I do 
`kubectl get services --export -o yaml > backup.yaml`
The generated file contains a ClusterIp and a Resource Version as many other informations.

In the annotations, the annotation `kubectl.kubernetes.io/last-applied-configuration` contains a copy of **InitialService.yaml**. 

If I do 
`kubectl apply -f  backup.yaml` 

it works fine.

When I do 
`kubectl apply -f **InitialService.yaml**`
I get the following error
```
* metadata.resourceVersion: Invalid value: "": must be specified for an update
* spec.clusterIP: Invalid value: "": field is immutable
```

Therefore, any time I want to migrate my services to a new cluster, I am unable to apply changes to those services afterward.
