### ISSUE TITLE
How to specify docker user-defined networks

### ISSUE THREAD

**Issue by dotNetDR** [kubernetes/kubernetes#28588]
I define docker network
```shell
docker network create -d bridge \
  --subnet="172.16.88.0/24" \
  --gateway=172.16.88.10 \
  --ipam-driver=myipam \
  -o "com.docker.network.bridge.name"="br9" \
  br9
```

and how to kubernetes specify it?
yaml
```yaml
spec:
  containers:
    -
      args:
        - ""
      command:
        - ""
      env:
        -
          name: ""
          value: ""
      image: ""
      imagePullPolicy: ""
      name: ""
      ports:
        -
          containerPort: 0
          name: ""
          protocol: ""
      resources:
        cpu: ""
        memory: ""
      # how to specify br9
```

environment:

    docker version 1.9.1
    kubernetes 1.2.2
