### ISSUE TITLE
when several pods in the same minion how to distinguish their log

### ISSUE THREAD

**Issue by workhardcc** [kubernetes/kubernetes#28681]
If there're only three minion, five replicas. There're must two pods running in a same minion.Deployment yaml like below:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    add: deployment-standard
  name: deployment-standard
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        name: deployment-standard
    spec:
      containers:
      - name: cc-web
        image: aaaaaa/bjdocker/web:stable
        volumeMounts:
          - name: log
            mountPath: /search
            readOnly: false
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 1
            memory: 4294967296
      - name: cc-web-cc
        image: aaaaaa/bjdocker/web-cc-2:stable
        volumeMounts:
          - name: log
            mountPath: /search
            readOnly: false
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: 1
            memory: 4294967296
      volumes:
        - name: log
          hostPath:
            path: /home/xxxxx
```

containerA and containerB has the same logname(access.log) and output in the same dir:/search. So they log output in the same file watch in host. Is there any way I can distinguish their log?
