### ISSUE TITLE
Do not allow pods to request millibytes 

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#28741]
This pod is validated and runs to completion:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: millibyte
spec:
  containers:
  - name: c
    image: busybox
    command: ["sh", "-c", "echo Allocating millibytes of memory."]
    resources:
      limits:
        cpu: 10m
        memory: 20000000001m
      requests:
        cpu: 10m
        memory: 20000000001m
  restartPolicy: Never
```

I think it should not pass validation. 

Allowing `m` for bytes doesn't have a real-world meaning.  It probably is a typo (meant `M` or swapped with cpu field). 

We should avoid accepting values with more precision that we can ever support.
