### ISSUE TITLE
broken example in NetworkPolicy proposal

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#28795]
Example 3 in https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/network-policy.md#examples is broken: it has an empty list of ingress rules, and consequently means nothing.

**Comment by MikeSpreitzer** [comment]
CC @caseydavenport I think we agreed that an empty list means nothing, right?  The pseudo-code in the same proposal, along with the comments on the data types, look clear on this subject.

**Comment by caseydavenport** [comment]
Yes, I think you're right.  That example looks wrong.

I think it's from an older version of the proposal that didn't get updated when the semantics were nailed down.

**Comment by caseydavenport** [comment]
I believe it should be:

```
kind: NetworkPolicy
apiVersion: extensions/v1beta1 
metadata:
  name: allow-all
spec:
  podSelector: 
  ingress:
  - {}
```
