### ISSUE TITLE
Firewall support

### ISSUE THREAD

**Issue by tristanz** [kubernetes/kubernetes#2880]
As Kubernetes moves to support more multi-tenant use cases and to increase security in general, it would be helpful if there was a way to firewall pods from other pods, ideally using something simple like labels.  

Is there a preferred approach to support this use case?  If this is implemented via dynamic iptables rules, I assume it would need to be part of the pod definition and kubelet rather than an external firewall service? Or perhaps there are lessons learned at Google regarding how to best isolate applications?

Somewhat related #2585.

**Comment by Symmetric** [comment]
I've implemented a prototype of pod firewalling, using the [Calico](https://github.com/Metaswitch/calico-docker) networking framework. It's on a branch in my repo [here](https://github.com/Metaswitch/calico-kubernetes/tree/calico-with-services).

I added annotation directly to the ports dictionary in the PodSpec; that's just for clarity. So with a spec like this:

```
apiVersion: v1beta1
desiredState:
  manifest:
    containers:
      - image: busybox
        name: demo-busybox
        command:
          - "/bin/sh"
          - "-c"
          - "while sleep 10; do date; done"
        ports: 
          - containerPort: 80
            name: http
            allowFrom: 
              app: db
    id: demo-busybox
    version: v1beta1
labels:
  app: sleep
  stage: prod
id: demo-busybox
kind: Pod
```

any pod with label `app: db` would be able to access port 80 on the demo-busybox pod. Traffic from pods with label `app: db` to other ports will be firewalled, as will all traffic from pods without that label.

Thoughts on the syntax? The allowFrom field could also be an annotation, but I think there's an advantage to making this a first-class citizen in the API, since it reduces duplication (with an annotation you'd have to specify the port in two places).

This could easily be extended to include `allowTo` as well, so that traffic is firewalled at both ends.

Note that this currently only works with headless services, since for normal services the kube-proxy prevents destination filtering (since all traffic at the destination pod has the src_ip of the proxy, and therefore we can't determine the original sender).
