### ISSUE TITLE
Service health check

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#28924]
This would help loadbalancers. The simplest way to do it (but in no way the only) is through a boolean on the port. 

``` yaml
  ports:
  - port: 8080
    targetPort: 8080
    healthCheck: true
    protocol: TCP
    name: healthz
```

Which means the frontend loadbalancer looks up the endpoints matching this service, and adopts their tcp/http readiness probe as a health check. 
- All endpoints behind the Service must have _the same_ tcp/http readiness probe on the given port
- "ready" endpoints that don't respond on healthCheck don't get Service traffic
- An exec probe on the healthCheck endpoint is a failure

If kube-proxy respected this we could layer Services (eg: a Service with all members for reads, and a service with just 1 member for writes). 

@kubernetes/sig-network
