### ISSUE TITLE
Timeout attaching/mounting volume

### ISSUE THREAD

**Issue by george-angel** [kubernetes/kubernetes#28962]
Deployment/Service manifest:

```

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/coreos/prometheus:0.19.2
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data
          mountPath: /prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prometheus
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-data-pvc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-data-pvc
  annotations:
    volume.alpha.kubernetes.io/storage-class: "ebs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

logs from events:

```
2m         31m         14        prometheus-210570969-bqkbd                   Pod                                     Warning   FailedMount               {kubelet ip-10-66-10-42.eu-west-1.compute.internal}       Unable to mount volumes for pod "prometheus-210570969-bqkbd_default(b03d4cc7-49d5-11e6-8d0f-02468703b623)": timeout expired waiting for volumes to attach/mount for pod "prometheus-210570969-bqkbd"/"default". list of unattached/unmounted volumes=[data]
2m         31m         14        prometheus-210570969-bqkbd                   Pod                                     Warning   FailedSync                {kubelet ip-10-66-10-42.eu-west-1.compute.internal}       Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "prometheus-210570969-bqkbd"/"default". list of unattached/unmounted volumes=[data]
```

In aws, the volume is attached,

On the box:

```
core@ip-10-66-10-42 ~ $ ls -ltr /dev/xvdb*
brw-rw---- 1 root disk 202, 13312 Jul 14 15:15 /dev/xvdba
brw-rw---- 1 root disk 202, 13568 Jul 14 15:15 /dev/xvdbb
```

In `/proc/mounts` only one is mounted:

```
core@ip-10-66-10-42 ~ $ cat /proc/mounts | grep xvdb
/dev/xvdbb /var/lib/rkt/pods/run/58129cda-9746-4723-816c-e4fbfee90d3c/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/eu-west-1a/vol-7c5014ff ext4 rw,seclabel,relatime,data=ordered 0 0
/dev/xvdbb /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/eu-west-1a/vol-7c5014ff ext4 rw,seclabel,relatime,data=ordered 0 0
/dev/xvdbb /var/lib/rkt/pods/run/58129cda-9746-4723-816c-e4fbfee90d3c/stage1/rootfs/opt/stage2/hyperkube/rootfs/var/lib/kubelet/pods/b038c2e6-49d5-11e6-8d0f-02468703b623/volumes/kubernetes.io~aws-ebs/pvc-562db436-49b4-11e6-8d0f-02468703b623 ext4 rw,seclabel,relatime,data=ordered 0 0
/dev/xvdbb /var/lib/kubelet/pods/b038c2e6-49d5-11e6-8d0f-02468703b623/volumes/kubernetes.io~aws-ebs/pvc-562db436-49b4-11e6-8d0f-02468703b623 ext4 rw,seclabel,relatime,data=ordered 0 0
```

Where can I debug this further?
