### ISSUE TITLE
kubectl apply: parsing unquoted number in selector value in yaml fails

### ISSUE THREAD

**Issue by Markbnj** [kubernetes/kubernetes#28974]
`kubectl apply -f` fails to parse this yaml file due to the unquoted number '1' in the spec.selector.instance and spec.template.metadata.labels.instance fields.

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: test-rc
spec:
  replicas: 1
  selector:
    instance: 1
  template:
    metadata:
      labels:
        instance: 1
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          imagePullPolicy: Always
```
```
$ kubectl apply -f test-rc.yaml
unable to decode "test-rc.yaml": [pos 125]: json: expect char '"' but got char '1'
```

If the number is quoted then parsing succeeds. Apologies if this is by design but the use doesn't seem prohibited in any way I can think of, and the error seems inconsistent with the way other fields in a yaml definition are treated.
