### ISSUE TITLE
SkyDNS | failure to forward request "read udp ${outside_DNS_IP}: i/o timeout"

### ISSUE THREAD

**Issue by bmikhael** [kubernetes/kubernetes#29041]
I'm trying to setup SkyDNS on a Kubernetes cluster running on bare-metal with Calico network.

I keep getting the following error from SkyDNS container:
```
2016-07-15T23:35:10.849076958Z [skydns] Jul 15 23:35:10.816 INFO      | falling back to default configuration, could not read from etcd:100: Key not found (/skydns/config) [31]

2016-07-15T23:35:10.849377687Z [skydns] Jul 15 23:35:10.816 INFO      | ready for queries on cluster.local. for tcp://127.0.0.1:53 [rcache 0]

2016-07-15T23:35:10.849419477Z [skydns] Jul 15 23:35:10.816 INFO      | ready for queries on cluster.local. for udp://127.0.0.1:53 [rcache 0]

2016-07-15T23:35:23.068061601Z [skydns] Jul 15 23:35:23.067 ERROR     | failure to forward request "read udp ${outside_DNS_IP}:53: i/o timeout"

2016-07-15T23:35:27.068482772Z [skydns] Jul 15 23:35:27.068 ERROR     | failure to forward request "read udp ${outside_DNS_IP}:53: i/o timeout"

2016-07-15T23:35:31.069153608Z [skydns] Jul 15 23:35:31.068 ERROR     | failure to forward request "read udp ${outside_DNS_IP}: i/o timeout"
```

Although the etcd instance is running fine and kube2sky successfully added entries for Kubernetes in the etcd database as follows:
```
# kubectl exec kube-dns-v11-m1kc9 -c etcd --namespace=kube-system -- etcdctl ls --recursive
/skydns
/skydns/local
/skydns/local/cluster
/skydns/local/cluster/svc
/skydns/local/cluster/svc/default
/skydns/local/cluster/svc/default/kubernetes
/skydns/local/cluster/svc/default/kubernetes/c88f1059
/skydns/local/cluster/svc/default/node-js
/skydns/local/cluster/svc/default/node-js/63aec4af
/skydns/local/cluster/svc/kube-system
/skydns/local/cluster/svc/kube-system/monitoring-grafana
/skydns/local/cluster/svc/kube-system/monitoring-grafana/28de9a7
/skydns/local/cluster/svc/kube-system/monitoring-influxdb
/skydns/local/cluster/svc/kube-system/monitoring-influxdb/4fa2ac2b
/skydns/local/cluster/svc/kube-system/default-http-backend
/skydns/local/cluster/svc/kube-system/default-http-backend/f0230b
/skydns/local/cluster/svc/kube-system/heapster
/skydns/local/cluster/svc/kube-system/heapster/7622b0dc
/skydns/local/cluster/svc/kube-system/kube-dns
/skydns/local/cluster/svc/kube-system/kube-dns/21172049
/skydns/local/cluster/svc/kube-system/kubernetes-dashboard
/skydns/local/cluster/svc/kube-system/kubernetes-dashboard/f90de212
/skydns/local/cluster/pod
/skydns/local/cluster/pod/kube-system
/skydns/local/cluster/pod/kube-system/192-168-0-70
/skydns/local/cluster/pod/kube-system/192-168-0-70/764720c3
/skydns/local/cluster/pod/kube-system/192-168-0-4
/skydns/local/cluster/pod/kube-system/192-168-0-4/308f4c50
/skydns/local/cluster/pod/kube-system/192-168-0-3
/skydns/local/cluster/pod/kube-system/192-168-0-3/1f9f18f3
/skydns/local/cluster/pod/kube-system/192-168-0-86
/skydns/local/cluster/pod/kube-system/192-168-0-86/70c57650
/skydns/local/cluster/pod/kube-system/${master}
/skydns/local/cluster/pod/kube-system/${master}/36f8af66
/skydns/local/cluster/pod/kube-system/${node1}
/skydns/local/cluster/pod/kube-system/${node1}/d6e3caf2
/skydns/local/cluster/pod/kube-system/${node2}
/skydns/local/cluster/pod/kube-system/${node2}/504f72db
/skydns/local/cluster/pod/kube-system/192-168-0-69
/skydns/local/cluster/pod/kube-system/192-168-0-69/583621d9
/skydns/local/cluster/pod/default
/skydns/local/cluster/pod/default/192-168-0-15
/skydns/local/cluster/pod/default/192-168-0-15/e2e1c858
/skydns/local/cluster/pod/default/192-168-0-22
/skydns/local/cluster/pod/default/192-168-0-22/eba731fa
/skydns/local/cluster/pod/default/192-168-0-80
/skydns/local/cluster/pod/default/192-168-0-80/c74cb70a
```

I'm using the following Kubernetes RPMs:
```
# rpm -qa | grep kube
kubernetes-master-1.2.0-0.12.gita4463d9.el7.x86_64
kubernetes-client-1.2.0-0.12.gita4463d9.el7.x86_64
kubernetes-node-1.2.0-0.12.gita4463d9.el7.x86_64
```

and that's the DNS replication controller YAML file:
```
# cat skydns-rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v11
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v11
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v11
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v11
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd-amd64:2.2.1
        command:
        - /usr/local/bin/etcd
        - -data-dir
        - /var/etcd/data
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
        volumeMounts:
        - name: etcd-storage
          mountPath: /var/etcd/data
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky-amd64:1.15
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
            scheme: HTTP
          # we poll on pod startup for the Kubernetes master service and
          # only setup the /readiness HTTP server once that's available.
          initialDelaySeconds: 30
          timeoutSeconds: 5
        args:
        # command = "/kube2sky"
        - --domain=cluster.local.
        - --etcd-server=http://127.0.0.1:4001
        - --kube-master-url=http://${MASTER_IP}:8080
      - name: skydns
        image: kubernetes/skydns:latest
        args:
        # command = "/skydns"
        - -machines=http://127.0.0.1:4001
        - -addr=127.0.0.1:53
        - -domain=cluster.local
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      - name: healthz
        image: gcr.io/google_containers/exechealthz:1.0
        args:
        - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.
```

and that's the service YAML file:
```
# cat skydns-svc.yaml 
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP:  10.0.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```

I've tried to create a busybox pod and here is the contents of the /etc/resolv.conf
```
# kubectl exec busybox -- cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.0.0.10
nameserver ${outside_DNS_IP}
options ndots:5
```

and here is the kubectl version:
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"a4463d9a1accc9c61ae90ce5d314e248f16b9f05", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
```

and here is how the kubelet process is running:
`/usr/bin/kubelet --logtostderr=true --v=0 --api-servers=http://${master_IP}:8080 --allow-privileged=True --register-node=true --register-schedulable=false --config=/etc/kubernetes/manifests --network-plugin=cni --network-plugin-dir=/etc/cni/net.d --cluster-dns=10.0.0.10 --cluster-domain=cluster.local`

any suggestions on what am I doing wrong?!
