### ISSUE TITLE
kubectl: `create secret` does not work without `https`

### ISSUE THREAD

**Issue by DenisIzmaylov** [kubernetes/kubernetes#29120]
Dear,
Thank you for this project. Really awesome. But I got the issue while trying to create and use a secret for private docker registry.

When I run it as:

```
kubectl create secret docker-registry private-registry1 --docker-server=private.qwe.com:5000 --docker-username=pruser --docker-password=qweqwe --docker-email=system@qwe.com
```

And create new pod:

```
kind: Pod
apiVersion: v1
metadata:
  name: qwe-release
  labels:
    app: qwe
    env: release
spec:
  containers:
    - name: frontend-static
      image: private.qwe.com:5000/qwe-static
      ports:
        - containerPort: 3000
  restartPolicy: Always
  imagePullSecrets:
    - name: private-registry1
```

It doesn't work and when I run `kubectl describe pods`:

```
  18m    5s    114    {kubelet 10.91.119.198}    spec.containers{frontend-static}            Pulling    Pulling image "private.qwe.com:5000/qwe-static"
  18m    4s    114    {kubelet 10.91.119.198}    spec.containers{frontend-static}        Failed    Failed to pull image "private.qwe.com:5000/qwe-static": API error (500): Get https://private.qwe.com:5000/v2/qwe-static/manifests/latest: no basic auth credentials
```

But when I add `https://` prefix to `docker-server`:

```
kubectl create secret docker-registry private-registry1 --docker-server=https://private.qwe.com:5000 --docker-username=pruser --docker-password=qweqwe --docker-email=system@qwe.com
```

So in this case everything is working.
