### ISSUE TITLE
Pod with hostNetwork=true lacks listening socket on one node

### ISSUE THREAD

**Issue by atombender** [kubernetes/kubernetes#29165]
This is odd. Here's my daemonset:

``` yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:0.12.0
        ports:
        - name: scrape
          containerPort: 9100
          hostPort: 9100
      hostNetwork: true
      hostPID: true
```

It runs fine. Says it's listening. on port 9100. On node A:

``` shell
$ sudo lsof -p 13165
COMMAND     PID USER   FD      TYPE   DEVICE SIZE/OFF     NODE NAME
node_expo 13165 root  cwd       DIR    252,4      148      131 /
node_expo 13165 root  rtd       DIR    252,4      148      131 /
node_expo 13165 root  txt       REG    252,4 14480776 33557023 /bin/node_exporter
node_expo 13165 root    0r     FIFO     0,10      0t0 18039984 pipe
node_expo 13165 root    1w     FIFO     0,10      0t0 18039985 pipe
node_expo 13165 root    2w     FIFO     0,10      0t0 18039986 pipe
node_expo 13165 root    3u     IPv6 18040039      0t0      TCP *:9100 (LISTEN)
node_expo 13165 root    4u  a_inode     0,11        0     8114 [eventpoll]
$ curl -I http://localhost:9100/
HTTP/1.1 200 OK
```

On node B:

``` shell
$ sudo lsof -p 14378
COMMAND     PID USER   FD      TYPE DEVICE SIZE/OFF     NODE NAME
node_expo 14378 root  cwd       DIR  252,4      148      131 /
node_expo 14378 root  rtd       DIR  252,4      148      131 /
node_expo 14378 root  txt       REG  252,4 14480776 33557023 /bin/node_exporter
node_expo 14378 root    0r     FIFO   0,10      0t0 10053053 pipe
node_expo 14378 root    1w     FIFO   0,10      0t0 10053054 pipe
node_expo 14378 root    2w     FIFO   0,10      0t0 10053055 pipe
node_expo 14378 root    3u     sock    0,8      0t0 10053071 protocol: TCPv6
node_expo 14378 root    4u  a_inode   0,11        0     8114 [eventpoll]
$ curl -I http://localhost:9100/
curl: (7) Failed to connect to localhost port 9100: Connection refused
```

`docker inspect` shows both containers being utterly identical. Both nodes are running the same version of Docker and Kubernetes.

How do I debug this?

---

**Environment**

``` shell
$ lsb_release -d
Description:    Ubuntu 16.04 LTS

$ uname -a
Linux ip-10-0-4-248 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ docker --version
Docker version 1.11.2, build b9f10c9

$ kubelet --version
Kubernetes v1.3.0
```
