### ISSUE TITLE
kubectl apply -f of a DaemonSet with an updated container image does not update the pods of the DaemonSet

### ISSUE THREAD

**Issue by jacobgmathew** [kubernetes/kubernetes#29199]
I have a DaemonSet configured as follows:

`daemonset.yaml`
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bugreport-daemonset
spec:
  template:
    metadata:
      labels:
        app: bugreport
    spec:
      containers:
      - name: bugreport-container
        image: gcr.io/bug-project/testcontainer:tag0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
```

When I run `kubectl apply -f daemonset.yaml` i can see the pods running on each node.

But if I change the image to `gcr.io/bug-project/testcontainer:tag1` and then run `kubectl apply -f daemonset.yaml` again, the pods are never updated with the new container image.
