### ISSUE TITLE
Deploying with recreate strategy fails to move a mounted PD to new pod on GKE

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#29202]
I'm running a single pod application with strategy Recreate, because it uses mounted PDs which can only be attached to a single pod at a time.

When I first deploy the application mounting the PDs works fine, but when deploying it again with command `cat ./kubernetes.yaml | envsubst | kubectl apply -f -` I get the following error:

```
Unable to mount volumes for pod "server-2215164912-msv75_namespace306b4538-4dbf-11e6-bae6-42010af001fc)": Could not attach GCE PD "pd". Timeout waiting for mount paths to be created.
```

The manifest for the deployment looks as follows:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        version: ${VERSION}
    spec:
      containers:
      - name: ${APP_NAME}
        image: travix/gocd-server:16.6.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: ${GCLOUD_RESOURCE_LIMIT_CPU}
            memory: ${GCLOUD_RESOURCE_LIMIT_MEMORY}
          requests:
            cpu: ${GCLOUD_RESOURCE_REQUESTS_CPU}
            memory: ${GCLOUD_RESOURCE_REQUESTS_MEMORY}
        volumeMounts:
        - mountPath: /var/lib/go-server/artifacts
          name: server-artifacts
        - mountPath: /var/lib/go-server/db/h2db
          name: server-db
        - mountPath: /etc/go
          name: server-config
        - mountPath: /var/go/.ssh
          name: ssh-keys
        ports:
        - name: http-8153
          containerPort: 8153
        - name: https-8154
          containerPort: 8154
        env:
        - name: "AGENT_KEY"
          value: "9ea6778d-86e2-4b11-96ef-90359b9c760d"
        - name: "SERVER_MEM"
          value: "1024m"
        - name: "SERVER_MAX_MEM"
          value: "3072m"
        livenessProbe:
          httpGet:
            path: /go/auth/login
            port: 8153
          initialDelaySeconds: 300
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /go/auth/login
            port: 8153
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: server-db
        gcePersistentDisk:
          pdName: ${NAMESPACE}-${APP_NAME}-db
          fsType: ext4
      - name: server-config
        gcePersistentDisk:
          pdName: ${NAMESPACE}-${APP_NAME}-config
          fsType: ext4
      - name: server-artifacts
        gcePersistentDisk:
          pdName: ${NAMESPACE}-${APP_NAME}-artifacts
          fsType: ext4
      - name: ssh-keys
        secret:
          secretName: ssh-keys
```

All of this runs on GKE with master version 1.3.0 and node version 1.2.5.

**Comment by JorritSalverda** [comment]
The same issue also occurs when upgrading the version of the nodes in a cluster.

**Comment by saad-ali** [comment]
My initial thought was a rolling deployment creates a second pod while the first pod is still running (by default), and since the GCE PD would already be attached to the first node, the 2nd pod would fail whenever it landed on a different machine.

But it looks like you are using the `Recreate` strategy which is supposed to kill all existing Pods before creating new ones.

When you run into this again could you grab the `/var/log/kubelet.log` log from your nodes and share them with me. Also do `kubectl describe deployment`, `kubectl describe rc`, and `kubectl describe pod` to get info about the pod(s) created during the deployment. I'd like to see what node the pods land on.

**Comment by kargakis** [comment]
Can you post the state of your replica sets? We recently merged a fix where the deployment process waits for the old replica set to be fully scaled down before proceeding with scaling up the new replica set: https://github.com/kubernetes/kubernetes/pull/27713 - not sure if that fix is included in 1.3

cc: @kubernetes/deployment

**Comment by JorritSalverda** [comment]
I'm now on version 1.3.2 for both the master and the nodes and the issue still happens.

The replica set seems to scale down before the new one scales up, but the old pod is still **Terminating** while the new one is already at **ContainerCreating**.

Describing the pods it seems the **SuccessfulCreate** of the new pod happens before the **SuccessfulDelete** of the old one, but the exact timestamps aren't visible in the describe output.

One thing that jumps out at me is that the old pod has a **FailedPreStopHook**. Not sure if that could be related. Previously I left out one container from my manifest, but I now added the full manifest at the end. It uses a lifecycle hook for one of the containers in the pod, although it's not the container with the pd volume mounts.

`kubectl describe deployment/server --namespace meta-gocd`

```
Name:                   server
Namespace:              meta-gocd
CreationTimestamp:      Mon, 18 Jul 2016 17:16:53 +0200
Labels:                 app=server,version=6648e26--24-1
Selector:               app=server
Replicas:               1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           Recreate
MinReadySeconds:        0
OldReplicaSets:         server-3472939187 (0/0 replicas created)
NewReplicaSet:          server-4287092916 (1/1 replicas created)
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type        Reason                      Message
  ---------     --------        -----   ----                            -------------   --------    ------                      -------
  5s            5s              1       {deployment-controller }                        Normal      ScalingReplicaSet   Scaled down replica set server-3472939187 to 0
  5s            5s              1       {deployment-controller }                        Normal      ScalingReplicaSet   Scaled up replica set server-4287092916 to 1
```

`kubectl get rs --namespace meta-gocd`

```
NAME                      DESIRED   CURRENT   AGE
agent-golang-3007899745   2         2         6d
agent-golang-3332102144   0         0         25d
server-3472939187         0         0         5m
server-4287092916         1         1         5s
```

`kubectl describe rs/server-3472939187 --namespace meta-gocd`

```
Name:           server-3472939187
Namespace:      meta-gocd
Image(s):       travix/gocd-server:16.6.0,travix/haproxy:1.6.2-r0
Selector:       app=server,pod-template-hash=3472939187
Labels:         app=server,pod-template-hash=3472939187,version=a3c315e--28-1
Replicas:       0 current / 0 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Volumes:
  server-db:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-db
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  server-config:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-config
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  server-artifacts:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-artifacts
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  ssh-keys:
    Type:       Secret (a volume populated by a Secret)
    SecretName: ssh-keys
  ssl-certificate:
    Type:       Secret (a volume populated by a Secret)
    SecretName: ssl-server-production-931c5175770f-20160629
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type        Reason                      Message
  ---------     --------        -----   ----                            -------------   --------    ------                      -------
  6m            6m              1       {replicaset-controller }                        Normal      SuccessfulCreate    Created pod: server-3472939187-qe6kw
  1m            1m              1       {replicaset-controller }                        Normal      SuccessfulDelete    Deleted pod: server-3472939187-qe6kw
```

`kubectl describe rs/server-4287092916 --namespace meta-gocd`

```
Name:           server-4287092916
Namespace:      meta-gocd
Image(s):       travix/gocd-server:16.6.0,travix/haproxy:1.6.2-r0
Selector:       app=server,pod-template-hash=4287092916
Labels:         app=server,pod-template-hash=4287092916,version=a3c315e--29-1
Replicas:       1 current / 1 desired
Pods Status:    0 Running / 1 Waiting / 0 Succeeded / 0 Failed
Volumes:
  server-db:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-db
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  server-config:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-config
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  server-artifacts:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-artifacts
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  ssh-keys:
    Type:       Secret (a volume populated by a Secret)
    SecretName: ssh-keys
  ssl-certificate:
    Type:       Secret (a volume populated by a Secret)
    SecretName: ssl-server-production-931c5175770f-20160629
Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type        Reason                      Message
  ---------     --------        -----   ----                            -------------   --------    ------                      -------
  1m            1m              1       {replicaset-controller }                        Normal      SuccessfulCreate    Created pod: server-4287092916-h9dj4
```

`kubectl get pods --namespace meta-gocd`

```
NAME                            READY     STATUS              RESTARTS   AGE
agent-golang-3007899745-qw6tv   1/1       Running             0          49m
agent-golang-3007899745-xjjlu   1/1       Running             0          47m
server-3472939187-qe6kw         2/2       Terminating         0          5m
server-4287092916-h9dj4         0/2       ContainerCreating   0          5s
```

`kubectl describe pod/server-3472939187-qe6kw --namespace meta-gocd`

```
Name:                           server-3472939187-qe6kw
Namespace:                      meta-gocd
Node:                           gke-tooling-default-pool-486a2631-kgqz/10.240.0.2
Start Time:                     Mon, 25 Jul 2016 09:45:38 +0200
Labels:                         app=server,pod-template-hash=3472939187,version=a3c315e--28-1
Status:                         Terminating (expires Mon, 25 Jul 2016 09:51:30 +0200)
Termination Grace Period:       30s
IP:                             10.220.2.3
Controllers:                    ReplicaSet/server-3472939187
Containers:
  server:
    Container ID:       docker://644dbbda3f23e1095b7f355fdf40ba774339de46e476ec16c51f8c2126f0406f
    Image:              travix/gocd-server:16.6.0
    Image ID:           docker://sha256:eb6015a2d66b3f465d18b1a42c90ff3137070a248b012d68450b9ee1a6380695
    Ports:              8153/TCP, 8154/TCP
    QoS Tier:
      cpu:      Burstable
      memory:   Burstable
    Limits:
      cpu:      2
      memory:   4Gi
    Requests:
      cpu:              100m
      memory:           1Gi
    State:              Running
      Started:          Mon, 25 Jul 2016 09:47:53 +0200
    Ready:              True
    Restart Count:      0
    Liveness:           http-get http://:8153/go/auth/login delay=300s timeout=1s period=10s #success=1 #failure=3
    Readiness:          http-get http://:8153/go/auth/login delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables:
      AGENT_KEY:                9ea6778d-86e2-4b11-96ef-90359b9c760d
      SERVER_MEM:               1024m
      SERVER_MAX_MEM:           3072m
      GO_SERVER_PORT:           8153
      GO_SERVER_SSL_PORT:       8154
  server-haproxy:
    Container ID:       docker://4d00d7855eb7ee3e89688709a8ebd32dd57ff681c3bf663556622446e2956b05
    Image:              travix/haproxy:1.6.2-r0
    Image ID:           docker://sha256:0c18c8c325413e19d853e2c318d3138833d50d9b947fffbf39e644bfca31023b
    Ports:              80/TCP, 443/TCP
    QoS Tier:
      cpu:      Burstable
      memory:   Burstable
    Limits:
      cpu:      100m
      memory:   100Mi
    Requests:
      cpu:              10m
      memory:           25Mi
    State:              Running
      Started:          Mon, 25 Jul 2016 09:47:54 +0200
    Ready:              True
    Restart Count:      0
    Liveness:           http-get http://:82/liveness delay=15s timeout=1s period=10s #success=1 #failure=3
    Readiness:          http-get http://:81/readiness delay=0s timeout=1s period=5s #success=1 #failure=2
    Environment Variables:
      OFFLOAD_TO_HOST:          localhost
      OFFLOAD_TO_PORT:          8153
      DIRECT_HOST_NAME:         server
      SSL_CERTIFICATE_NAME:     tls.pem
      HEALT_CHECK_PATH:         /go/auth/login
      HEALT_CHECK_VERB:         GET
      WHITELIST_CIDRS:
Conditions:
  Type          Status
  Initialized   True
  Ready         True
  PodScheduled  True
Volumes:
  server-db:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-db
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  server-config:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-config
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  server-artifacts:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-artifacts
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  ssh-keys:
    Type:       Secret (a volume populated by a Secret)
    SecretName: ssh-keys
  ssl-certificate:
    Type:       Secret (a volume populated by a Secret)
    SecretName: ssl-server-production-931c5175770f-20160629
  default-token-5qpz4:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-5qpz4
Events:
  FirstSeen     LastSeen        Count   From                                                    SubobjectPath                   Type            Reason                  Message
  ---------     --------        -----   ----                                                    -------------                   --------        ------                  -------
  5m            5m              1       {default-scheduler }                                                            Normal          Scheduled               Successfully assigned server-3472939187-qe6kw to gke-tooling-default-pool-486a2631-kgqz
  3m            3m              1       {kubelet gke-tooling-default-pool-486a2631-kgqz}                                Warning         FailedMount             Unable to mount volumes for pod "server-3472939187-qe6kw_meta-gocd(c75c25f2-523b-11e6-b085-42010af000a7)": timeout expired waiting for volumes to attach/mount for pod "server-3472939187-qe6kw"/"meta-gocd". list of unattached/unmounted volumes=[server-db server-config server-artifacts]
  3m            3m              1       {kubelet gke-tooling-default-pool-486a2631-kgqz}                                Warning         FailedSync              Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "server-3472939187-qe6kw"/"meta-gocd". list of unattached/unmounted volumes=[server-db server-config server-artifacts]
  3m            3m              1       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server}         Normal          Pulling                 pulling image "travix/gocd-server:16.6.0"
  3m            3m              1       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server}         Normal          Pulled                  Successfully pulled image "travix/gocd-server:16.6.0"
  3m            3m              1       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server}         Normal          Created                 Created container with docker id 644dbbda3f23
  3m            3m              1       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server-haproxy} Normal          Pulling                 pulling image "travix/haproxy:1.6.2-r0"
  3m            3m              1       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server}         Normal          Started                 Started container with docker id 644dbbda3f23
  3m            3m              1       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server-haproxy} Normal          Pulled                  Successfully pulled image "travix/haproxy:1.6.2-r0"
  3m            3m              1       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server-haproxy} Normal          Created                 Created container with docker id 4d00d7855eb7
  3m            3m              1       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server-haproxy} Normal          Started                 Started container with docker id 4d00d7855eb7
  3m            2m              4       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server}         Warning         Unhealthy               Readiness probe failed: Get http://10.220.2.3:8153/go/auth/login: dial tcp 10.220.2.3:8153: getsockopt: connection refused
  3m            2m              8       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server-haproxy} Warning         Unhealthy               Readiness probe failed: HTTP probe failed with statuscode: 503
  22s           22s             1       {kubelet gke-tooling-default-pool-486a2631-kgqz}        spec.containers{server-haproxy} Warning         FailedPreStopHook
```

`kubectl describe pod/server-4287092916-h9dj4 --namespace meta-gocd`

```
Name:           server-4287092916-h9dj4
Namespace:      meta-gocd
Node:           gke-tooling-default-pool-c08ebb35-3qb3/10.240.0.3
Start Time:     Mon, 25 Jul 2016 09:51:00 +0200
Labels:         app=server,pod-template-hash=4287092916,version=a3c315e--29-1
Status:         Pending
IP:
Controllers:    ReplicaSet/server-4287092916
Containers:
  server:
    Container ID:
    Image:              travix/gocd-server:16.6.0
    Image ID:
    Ports:              8153/TCP, 8154/TCP
    QoS Tier:
      memory:   Burstable
      cpu:      Burstable
    Limits:
      cpu:      2
      memory:   4Gi
    Requests:
      cpu:              100m
      memory:           1Gi
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Liveness:           http-get http://:8153/go/auth/login delay=300s timeout=1s period=10s #success=1 #failure=3
    Readiness:          http-get http://:8153/go/auth/login delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables:
      AGENT_KEY:                9ea6778d-86e2-4b11-96ef-90359b9c760d
      SERVER_MEM:               1024m
      SERVER_MAX_MEM:           3072m
      GO_SERVER_PORT:           8153
      GO_SERVER_SSL_PORT:       8154
  server-haproxy:
    Container ID:
    Image:              travix/haproxy:1.6.2-r0
    Image ID:
    Ports:              80/TCP, 443/TCP
    QoS Tier:
      memory:   Burstable
      cpu:      Burstable
    Limits:
      cpu:      100m
      memory:   100Mi
    Requests:
      memory:           25Mi
      cpu:              10m
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Liveness:           http-get http://:82/liveness delay=15s timeout=1s period=10s #success=1 #failure=3
    Readiness:          http-get http://:81/readiness delay=0s timeout=1s period=5s #success=1 #failure=2
    Environment Variables:
      OFFLOAD_TO_HOST:          localhost
      OFFLOAD_TO_PORT:          8153
      DIRECT_HOST_NAME:         server
      SSL_CERTIFICATE_NAME:     tls.pem
      HEALT_CHECK_PATH:         /go/auth/login
      HEALT_CHECK_VERB:         GET
      WHITELIST_CIDRS:
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  server-db:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-db
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  server-config:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-config
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  server-artifacts:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     meta-gocd-server-artifacts
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
  ssh-keys:
    Type:       Secret (a volume populated by a Secret)
    SecretName: ssh-keys
  ssl-certificate:
    Type:       Secret (a volume populated by a Secret)
    SecretName: ssl-server-production-931c5175770f-20160629
  default-token-5qpz4:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-5qpz4
Events:
  FirstSeen     LastSeen        Count   From                                                    SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                                                    -------------   --------        ------          -------
  2m            2m              1       {default-scheduler }                                            Normal          Scheduled       Successfully assigned server-4287092916-h9dj4 to gke-tooling-default-pool-c08ebb35-3qb3
  20s           20s             1       {kubelet gke-tooling-default-pool-c08ebb35-3qb3}                Warning         FailedMount     Unable to mount volumes for pod "server-4287092916-h9dj4_meta-gocd(874a916e-523c-11e6-b085-42010af000a7)": timeout expired waiting for volumes to attach/mount for pod "server-4287092916-h9dj4"/"meta-gocd". list of unattached/unmounted volumes=[server-db server-config server-artifacts]
  20s           20s             1       {kubelet gke-tooling-default-pool-c08ebb35-3qb3}                Warning         FailedSync      Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "server-4287092916-h9dj4"/"meta-gocd". list of unattached/unmounted volumes=[server-db server-config server-artifacts]
```

The full deployment manifest:

```
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
    scope: public
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP  
  - name: http-go
    port: ${GO_SERVER_PORT}
    targetPort: http-go
    protocol: TCP  
  - name: https-go
    port: ${GO_SERVER_SSL_PORT}
    targetPort: https-go
    protocol: TCP
  selector:
    app: ${APP_NAME}
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
type: Opaque
data:
  config: ${SSH_KEYS_CONFIG}
  id-rsa: ${SSH_KEYS_ID_RSA}
  id-rsa.pub: ${SSH_KEYS_ID_RSA_PUB}
---
apiVersion: v1
kind: Secret
metadata:
  name: gcloud-keys
  namespace: ${NAMESPACE}
  labels:
    app: ${APP_NAME}
type: Opaque
data:
  ${GCLOUD_FILE_NAME}: ${GCLOUD_FILE_CONTENT}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        version: ${VERSION}
    spec:
      containers:
      - name: ${APP_NAME}
        image: travix/gocd-server:16.6.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: ${GCLOUD_RESOURCE_LIMIT_CPU}
            memory: ${GCLOUD_RESOURCE_LIMIT_MEMORY}
          requests:
            cpu: ${GCLOUD_RESOURCE_REQUESTS_CPU}
            memory: ${GCLOUD_RESOURCE_REQUESTS_MEMORY}
        volumeMounts:
        - mountPath: /var/lib/go-server/artifacts
          name: server-artifacts
        - mountPath: /var/lib/go-server/db/h2db
          name: server-db
        - mountPath: /etc/go
          name: server-config
        - mountPath: /var/go/.ssh
          name: ssh-keys
        ports:
        - name: http-go
          containerPort: ${GO_SERVER_PORT}
        - name: https-go
          containerPort: ${GO_SERVER_SSL_PORT}
        env:
        - name: "AGENT_KEY"
          value: "9ea6778d-86e2-4b11-96ef-90359b9c760d"
        - name: "SERVER_MEM"
          value: "1024m"
        - name: "SERVER_MAX_MEM"
          value: "3072m"
        - name: "GO_SERVER_PORT"
          value: "${GO_SERVER_PORT}"
        - name: "GO_SERVER_SSL_PORT"
          value: "${GO_SERVER_SSL_PORT}"
        livenessProbe:
          httpGet:
            path: /go/auth/login
            port: ${GO_SERVER_PORT}
          initialDelaySeconds: 300
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /go/auth/login
            port: ${GO_SERVER_PORT}
          initialDelaySeconds: 5
          timeoutSeconds: 1
      - name: ${APP_NAME}-haproxy
        image: travix/haproxy:1.6.2-r0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: "OFFLOAD_TO_HOST"
          value: "localhost"
        - name: "OFFLOAD_TO_PORT"
          value: "${GO_SERVER_PORT}"
        - name: "DIRECT_HOST_NAME"
          value: "${APP_NAME}"
        - name: "SSL_CERTIFICATE_NAME"
          value: "tls.pem"
        - name: "HEALT_CHECK_PATH"
          value: "/go/auth/login"
        - name: "HEALT_CHECK_VERB"
          value: "GET"
        - name: "WHITELIST_CIDRS"
          value: "${WHITELIST_CIDRS}"
        volumeMounts:
        - name: ssl-certificate
          mountPath: /etc/ssl/private
        livenessProbe:
          httpGet:
            path: /liveness
            port: 82
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 81
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["kill -USR1 1"]
      volumes:
      - name: server-db
        gcePersistentDisk:
          pdName: ${NAMESPACE}-${APP_NAME}-db
          fsType: ext4
      - name: server-config
        gcePersistentDisk:
          pdName: ${NAMESPACE}-${APP_NAME}-config
          fsType: ext4
      - name: server-artifacts
        gcePersistentDisk:
          pdName: ${NAMESPACE}-${APP_NAME}-artifacts
          fsType: ext4
      - name: ssh-keys
        secret:
          secretName: ssh-keys
      - name: ssl-certificate
        secret:
          secretName: ${SSL_CERTIFICATE_NAME}
```          

I'm going to put the kubelet.log in a separate comment.
