### ISSUE TITLE
PetSet doesnt get deleted with kubectl delete all -lapp=nginx

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#29265]
```
kubectl delete all -lapp=nginx
service "nginx" deleted
pod "web-0" deleted
pod "web-1" deleted
persistentvolumeclaim "www-web-0" deleted
persistentvolumeclaim "www-web-1" deleted
```

Note that all resources got deleted above except petsets

Now again i delete petsets specifically and its gets deleted see below.

```
 kubectl delete petsets -lapp=nginx
petset "web" deleted
```

Not sure why delete all should behave differentely for just PetSets.

**Comment by krmayankk** [comment]
Here is the example i tried
```
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  # *.nginx.default.svc.cluster.local
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.7
        ports:
        - containerPort: 80
          name: web
        command:
        - nginx
        args:
        - -g
        - "daemon off;"
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

```
