### ISSUE TITLE
Federation: Manually test an Ingress object created in multiple GCE clusters, and write up the results

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#29341]
Desired outcome:

1. Single GCE L7 LB IP
2. Correct geotargeting
3. Correct overflow behavior

How do we expose service load to the L7 load balancer? (rather than VM load)

**Comment by mml** [comment]
> How do we expose service load to the L7 load balancer? (rather than VM load)

When creating a cross-region load balancer, you can specify a custom health check.  The health check acts as a health check on the **instance** (in GCP parlance, **node** in kubernetes), but since each `backend-service` can specify its own health check, the health check is in reality can check anything, including only your pod.  See https://cloud.google.com/compute/docs/load-balancing/http/cross-region-example and https://cloud.google.com/compute/docs/load-balancing/health-checks

We are presumably already doing this with ordinary services.  The only difference in this case is that the instance group containing the backends spans zones/regions.

**Comment by mml** [comment]
Hmm... it seems we are currently not exposing anything about health checking or any knobs around load balancing through Ingress right now.  It seems impoverished compared to the service implementation.  Worth noting that even non-federated Ingress might be far away from what we need.

From http://kubernetes.io/docs/user-guide/ingress/#loadbalancing
> An Ingress controller is bootstrapped with some loadbalancing policy settings that it applies to all Ingress, such as the loadbalancing algorithm, backend weight scheme etc. More advanced loadbalancing concepts (eg: persistent sessions, dynamic weights) are not yet exposed through the Ingress. You can still get these features through the service loadbalancer. With time, we plan to distill loadbalancing patterns that are applicable cross platform into the Ingress resource.

> It’s also worth noting that even though health checks are not exposed directly through the Ingress, there exist parallel concepts in Kubernetes such as readiness probes which allow you to achieve the same end result. Please review the controller specific docs to see how they handle health checks (nginx, GCE).

**Comment by mml** [comment]
OK.  One piece of background info is that an instance may be present in at most one *load-balanced* instance group.  If you try to violate this condition, it shows up when you try to add the second group to a backend-service.  If that doesn't make sense now, just wait.  I'll refer to this One Instance Group Rule later.

So you have a list of instances on which your pod is running.  A1..A2 in zone A and B1..B2 in zone B.

Those instances are added to per-zone unmanaged instance groups, ig-A and ig-B.  You must specify namedPorts here which describe the ports on which you are serving.

The port here is 31444.  Ignore the other ports.

```
% gcloud compute instance-groups describe k8s-ig--afd6f841b2a344a1 --zone us-central1-c
creationTimestamp: '2016-07-21T15:44:44.435-07:00'
description: ''
fingerprint: Z84kx-YiYQQ=
id: '6753934125070872243'
isManaged: 'No'
kind: compute#instanceGroup
name: k8s-ig--afd6f841b2a344a1
namedPorts:
- name: port31441
  port: 31441
- name: port31444
  port: 31444
- name: http
  port: 31444
- name: port32474
  port: 32474
network: https://www.googleapis.com/compute/v1/projects/mml-fed/global/networks/e2e
selfLink: https://www.googleapis.com/compute/v1/projects/mml-fed/zones/us-central1-c/instanceGroups/k8s-ig--afd6f841b2a344a1
size: 1
zone: https://www.googleapis.com/compute/v1/projects/mml-fed/zones/us-central1-c
```

Now we have to describe how to health check these.
```
% gcloud compute http-health-checks describe http-basic-check
checkIntervalSec: 1
creationTimestamp: '2016-07-25T14:08:29.638-07:00'
description: ''
healthyThreshold: 2
host: ''
id: '2114039126515499298'
kind: compute#httpHealthCheck
name: http-basic-check
port: 31444
requestPath: /
selfLink: https://www.googleapis.com/compute/v1/projects/mml-fed/global/httpHealthChecks/http-basic-check
timeoutSec: 1
unhealthyThreshold: 10
```

Note that we had to list the port to run the check on above.  And below, even though we specify multiple instance groups, we specify only one health check for the whole service.  I call these the One Health Check Rule and the One Port Number Corollary.

Now we can define this as a **load-balanced** backend.  AFAICT, the port field here is ignored, but it's worth noting that here we specify load balancing properties between the N groups, and these groups do not need to be in the same zone or even region.

```
% gcloud compute backend-services describe global-backend    
backends:
- balancingMode: UTILIZATION
  capacityScaler: 1.0
  description: ''
  group: https://www.googleapis.com/compute/v1/projects/mml-fed/zones/us-central1-c/instanceGroups/k8s-ig--afd6f841b2a344a1
  maxUtilization: 0.8
- balancingMode: UTILIZATION
  capacityScaler: 1.0
  description: ''
  group: https://www.googleapis.com/compute/v1/projects/mml-fed/zones/us-central1-b/instanceGroups/k8s-ig--232d86c114f09dab
  maxUtilization: 0.8
creationTimestamp: '2016-07-25T14:09:48.438-07:00'
description: ''
enableCDN: false
fingerprint: UCPD6JJhBtU=
healthChecks:
- https://www.googleapis.com/compute/v1/projects/mml-fed/global/httpHealthChecks/http-basic-check
id: '1137117126771556083'
kind: compute#backendService
name: global-backend
port: 80
portName: http
protocol: HTTP
selfLink: https://www.googleapis.com/compute/v1/projects/mml-fed/global/backendServices/global-backend
timeoutSec: 30
```

Next we create a proxy object.  We aren't doing any fancy URL-based mapping here, but we still need to create a trivial url-map to create the proxy.

```
% gcloud compute url-maps describe global-web-map 
creationTimestamp: '2016-07-25T14:33:19.895-07:00'
defaultService: https://www.googleapis.com/compute/v1/projects/mml-fed/global/backendServices/global-backend
description: ''
fingerprint: T_HyGzG6pKo=
id: '7813374047277497200'
kind: compute#urlMap
name: global-web-map
selfLink: https://www.googleapis.com/compute/v1/projects/mml-fed/global/urlMaps/global-web-map
% gcloud compute target-http-proxies describe global-http-lb-proxy
creationTimestamp: '2016-07-25T14:33:39.775-07:00'
id: '7662774545211407196'
kind: compute#targetHttpProxy
name: global-http-lb-proxy
selfLink: https://www.googleapis.com/compute/v1/projects/mml-fed/global/targetHttpProxies/global-http-lb-proxy
urlMap: https://www.googleapis.com/compute/v1/projects/mml-fed/global/urlMaps/global-web-map
```

Now we just allocate a global IP address and point it at our proxy with a global forwarding rule.

```
% gcloud compute addresses describe lb-global --global
address: 107.178.247.56
creationTimestamp: '2016-07-25T14:04:24.353-07:00'
description: ''
id: '2341173360953376823'
kind: compute#address
name: lb-global
selfLink: https://www.googleapis.com/compute/v1/projects/mml-fed/global/addresses/lb-global
status: IN_USE
users:
- https://www.googleapis.com/compute/v1/projects/mml-fed/global/forwardingRules/http-content-rule
% gcloud compute forwarding-rules describe http-content-rule --global 
IPAddress: 107.178.247.56
IPProtocol: TCP
creationTimestamp: '2016-07-25T14:34:39.421-07:00'
description: ''
id: '7518559439016377088'
kind: compute#forwardingRule
name: http-content-rule
portRange: 80-80
selfLink: https://www.googleapis.com/compute/v1/projects/mml-fed/global/forwardingRules/http-content-rule
target: https://www.googleapis.com/compute/v1/projects/mml-fed/global/targetHttpProxies/global-http-lb-proxy
```

Set all this up, wait for things to sync, and you have global load balancing.  Here we see my requests being served from both clusters.

```
% for zone in us-central1-{b,c}; do
cluster/kubectl.sh --context=federation-e2e-gce-${zone} get pods -oname -l foo=bar | while read pod; do
cluster/kubectl.sh --context=federation-e2e-gce-${zone} logs ${pod} | grep Chrome | perl -pe "s/^/${zone} /"
done
done | sort -t: -k2,4
[...]
us-central1-c 10.181.1.1 - - [25/Jul/2016:23:37:33 +0000] "GET /xyzzy HTTP/1.1" 200 928 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
us-central1-b 10.180.1.1 - - [25/Jul/2016:23:37:33 +0000] "GET /xyzzy HTTP/1.1" 200 929 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
```

Now... referring back to the One Instance Group Rule, if you're exposing multiple load balanced services, you can't put a node into multiple **load-balanced** instance groups.  As a result, any global system must also play nice with local systems.  To be more specific, it'll be an implementation, uh, challenge (nightmare?) to have a federated ingress controller trying to create IGs and a local ingress controller possibly fighting with it.

Also, referring back to the One Port Number Corollary, the underlying kubernetes services all need to specify the same NodePort for this to work.  They can't be dynamically allocated by each cluster.  This is another bit of global coordination if we want to handle collisions.  To make this demo work, I had to manually specify `nodePort: 31444` in each service.

```yaml
 apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-07-25T21:14:46Z
  labels:
    foo: bar
  name: echo
  namespace: default
  resourceVersion: "150393"
  selfLink: /api/v1/namespaces/default/services/echo
  uid: d0811363-52ac-11e6-aceb-42010af00002
spec:
  clusterIP: 10.0.0.237
  ports:
  - nodePort: 31444
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    foo: bar
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2016-07-21T22:52:22Z
  labels:
    foo: bar
  name: echo
  namespace: default
  resourceVersion: "140459"
  selfLink: /api/v1/namespaces/default/services/echo
  uid: c943a2fb-4f95-11e6-9989-42010af00004
spec:
  clusterIP: 10.0.140.209
  ports:
  - nodePort: 31444
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    foo: bar
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
