### ISSUE TITLE
Poor kubectl error message for bad Deployment

### ISSUE THREAD

**Issue by yissachar** [kubernetes/kubernetes#29403]
I went to edit my deployment to add some resource requests:

`kubectl edit deployment/mything`

I set my resources and saved the file:

```
resources:
  cpu: 100m
  memory: 600Mi
```

But got the unhelpful message:

> deployment "mything" skipped

The problem was that I had left out the `requests` object:

```
resources:
  requests:
    cpu: 100m
    memory: 600Mi
```

Once I fixed this it deployed successfully, but it would have been nice to get a more descriptive error message.
