### ISSUE TITLE
Fail to update service's named port with "kubectl apply"

### ISSUE THREAD

**Issue by alena1108** [kubernetes/kubernetes#29493]
Kubernetes v1.3
Kubelet v1.3

Steps to reproduce:

1) Create a service with the named port:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    k8s-app: nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: myport
  selector:
    k8s-app: nginx-service
```

2) Change "port" from 80 to some other value, call kubectl apply. It fails:

```
> kubectl apply -f n                                                                                                    
proto: no encoder for TypeMeta unversioned.TypeMeta [GetProperties]                                                     
proto: tag has too few fields: "-"                                                                                      
proto: no coders for struct *reflect.rtype                                                                              
proto: no encoder for sec int64 [GetProperties]                                                                         
proto: no encoder for nsec int32 [GetProperties]                                                                        
proto: no encoder for loc *time.Location [GetProperties]                                                                
proto: no encoder for Time time.Time [GetProperties]                                                                    
proto: no coders for intstr.Type                                                                                        
proto: no encoder for Type intstr.Type [GetProperties]                                                                  
The Service "nginx-service" is invalid.                                                                                 
spec.ports[1].name: Duplicate value: "myport"                                                                             
```

Workaround: rename  the port, and then apply works fine
