### ISSUE TITLE
ConfigMaps consuming pod facts

### ISSUE THREAD

**Issue by nebril** [kubernetes/kubernetes#29607]
## The problem

I would like to use pod facts (such as pod IP address) in ConfigMaps, so that each container configuration is populated with the correct value of a pod fact.

## Possible solution

The idea is to add templates to ConfigMap values, so each time a ConfigMap is applied to a pod - it can transform the value into something specific to a pod.

The example syntax would be `$(variable.name)`.

## Example case

We assume that there are two possible variables (templates) that can be used to consume pod facts: `pod.IP` and `pod.name`, which evaluate to `pod.Status.podIP` and `pod.Name`.

Let's consider following ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  service.ip: $(pod.IP)
  other.value: trololo
  service.name: $(pod.name)
```

Then we have a pod with a service that needs to put the IP of the pod in the config file `/etc/config/service.ip`.

Pod manifest can look like that:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-facts-consumer
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "cat", "/etc/config/service.ip" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  restartPolicy: Never
```

When we create above ConfigMap and run the pod, we expect the `test-container` output to be an IP address that was assigned to the Pod.

## Proof of concept

The proof of concept implementation is demoed here: https://asciinema.org/a/e90cs3ymgtatdexk6rmjuet92

The code for above demo will be linked to this issue via WiP Pull Request.

## Benefits

With this mechanism in place, we can have clean configuration of containers that need to be aware of their IPs. We can drop init containers creating additional volumes mounted in final containers - the state passed to container happens implicitly by templates defined by user, which should add to overall user experience in cases of writing configuration for such applications.

## Real world example

An example of such application can be Galera, which needs local IP addresses in `my.conf` file.

## Alternatives

The alternative way to achieve this which already works is using init containers to create volumes filled with data from downward API, which are then mounted in the container running the desired workload.

The downside of above approach requires you to compile pod facts into configuration files using additional scripts or template engines, which add to complexity of pod configuration.

In contrast, if this feature is implemented you can declare configuration files with multiple pod facts in them directly in ConfigMap, which moves the burden of injecting them into config files away from cluster user.

## Previous submissions
This document was previously submitted by me here:
https://github.com/kubernetes/features/issues/38
I was pointed out to me that it needs more discussion before submitting a feature.
