### ISSUE TITLE
Race in `Downward API volume should update annotations / labels on modification`

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#29633]
Ref https://github.com/kubernetes/kubernetes/issues/28462
Ref https://github.com/kubernetes/kubernetes/issues/28416

I believe these two flakes have the same root cause:

When there's a pod UPDATE event to kubelet, kubelet will invoke the `volume manager` to update the pod state to introduce the updated annotation:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/volume_manager.go#L298

The `volume manager`:
- 1, Tells the `desiredStateOfWorld populator` to reprocess the volume mount in the next loop.
- 2, Mark the volume in `actualStateOfWorld` to be remounted.
  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/volume_manager.go#L311-L312

However in the reconciler's reconciling loop, it does not always pick up the latest pod state with the latest annotation in the memory cache as the `populator` is running asynchronously.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L150

But when it reads the `actualStateOfWorld`, it does get notified that the volume needs to be remount, 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L223

So when remounting the volume, it ends up thinking that the annotation in the pod is not changed, and thus not modifying the content on the disk.

Although the annotation updates on the disk will happen eventually after another periodic pod SYNC event received by kubelet, but it will results in the timeout of the e2e tests.

cc @kubernetes/sig-storage

**Comment by yifan-gu** [comment]
This can be easily reproduced locally with such pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    builder: foo
  name: annotationannotationupdate
spec:
  containers:
  - command:
    - /mt
    - --break_on_expected_content=false
    - --retry_time=12000
    - --file_content_in_loop=/etc/annotations
    image: gcr.io/google_containers/mounttest:0.6
    image: busybox
    imagePullPolicy: IfNotPresent
    name: client-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /opt
      name: podinfo
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - downwardAPI:
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
        path: podname
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: podinfo
```

After creating the pod, try to `kubectl edit` the pod and change the annotation value. We can find the content in the volume under `/var/lib/kubelet/pods/$uid/volumes/kubernetes.io~downward-api/podinfo/annotations` is not always changed quickly enough.
