### ISSUE TITLE
RBAC - wildcard on nonResourceURLs

### ISSUE THREAD

**Issue by jcmoraisjr** [kubernetes/kubernetes#29675]
I am using RBAC authorization on Kubernetes 1.3.2 and trying to figure out a way to allow kubectl execute its queries. On some commands like `kubectl get` this is enought:

```
nonResourceURLs:
- /api
- /apis
```

But if I try to execute eg `kube run` it fails with:

```
I0727 10:52:34.272286   14651 round_trippers.go:318] GET https://10.200.81.86/apis/apps/v1alpha1 403 Forbidden in 72 milliseconds
```

I tried to use wildcard like `/api/*` but no luck. Currently my `ClusterRole/api` resource only work if I configure it like this:

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: api
rules:
- apiGroups: [""]
  resources: []
  verbs: []
  nonResourceURLs:
  - /api
  - /apis
  - /apis/apps/v1alpha1
  - /apis/autoscaling/v1
  - /apis/batch/v1
  - /apis/batch/v2alpha1
  - /apis/extensions/v1beta1
  - /apis/policy/v1alpha1
  - /apis/rbac.authorization.k8s.io/v1alpha1
```

Note that if I use only a single `'*'` it works:

```
nonResourceURLs:
- '*'
```

Is there a way to simplify the reading of `/apis/*`?
