### ISSUE TITLE
NodePort behavior changes 1.1->1.2

### ISSUE THREAD

**Issue by jboero** [kubernetes/kubernetes#29730]
Hi just a heads-up for anybody else having these issues after update.  I noticed that my CentOS 7 install of Kubernetes 1.1 had undocumented behavior with NodePort services.  While documentation says you specify "nodePort:<port>" to expose your service on your nodes, in my experience it used the value of "targetPort" instead.  Now in 1.2 I see the behavior is corrected to match documentation, but with a new caveat.  If I specify both targetPort and nodePort, services are inaccessible even with "type: NodePort" set.

So an example apache service on nodePort 20080 used to be (v1.1):

```
spec:
  selector:
    run: apache
  type: NodePort
  ports:
  - port: 80
#    nodePort: 20080
    targetPort: 20080
    protocol: TCP
```

must be rewritten in 1.2:

```
spec:
  selector:
    run: apache
  type: NodePort
  ports:
  - port: 80
    nodePort: 20080
#    targetPort: 20080
    protocol: TCP
```

In my experience in 1.1 I could have both nodePort and targetPort set with no problems but it took some testing to realize corrections were made.  Note that this is using kube_proxy --proxy-mode=iptables (not userspace).  Not sure if this is a bug as such but I was always confused by documentation not matching testing in 1.1.  Hope this helps anybody else having similar issues.

See: https://github.com/kubernetes/kubernetes/issues/20799
