### ISSUE TITLE
taints & tolerations with daemonsets

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#29738]
I'm trying to use taints and tolerations to run a daemonset only on my master nodes.  The daemonset is scheduling pods on all nodes though.  I don't know whether daemonsets bypass taints & tolerations, or whether I am doing something wrong.

I taint my master node:

```
kubectl taint  nodes ip-172-20-77-44.ec2.internal role=master:NoSchedule
```

My daemonset:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aws-controller
  labels:
    tier: cloud
    app: aws-controller
    version: v1
spec:
  template:
    metadata:
      labels:
        name: aws-controller
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "role", "value": "master", "effect": "NoSchedule" }]
    spec:
      containers:
        - resources:
            requests:
              cpu: 0.20
          securityContext:
            privileged: true
          image: kope/aws-controller
          name: aws-controller
          command:
          - /usr/bin/aws-controller
          - --healthz-port=10245
          - --zone-name=yahoo.com
          - --v=4
```

The pod is scheduled on all my nodes though.  One of their annotations (so we can see the final result):

```
        "annotations": {
            "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"DaemonSet\",\"namespace\":\"default\",\"name\":\"aws-controller\",\"uid\":\"47395313-54d4-11e6-9aa6-0681a2fd2e75\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"3520\"}}\n",
            "scheduler.alpha.kubernetes.io/tolerations": "[{\"key\": \"role\", \"value\": \"master\", \"effect\": \"NoSchedule\" }]\n"   
        }
```

And the annotations on the node:

```
    "annotations": {
      "scheduler.alpha.kubernetes.io/taints": "[{\"key\":\"role\",\"value\":\"master\",\"effect\":\"NoSchedule\"}]",
      "volumes.kubernetes.io/controller-managed-attach-detach": "true"
    }
```
