### ISSUE TITLE
ConfigMap links

### ISSUE THREAD

**Issue by zefciu** [kubernetes/kubernetes#29776]
This proposal is for an ability for configmaps to reference each other by loading data from other configmaps. This proposal is closely related to https://github.com/kubernetes/kubernetes/issues/29607 as it would use a lot of common logic addressing common problems
## Example

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
  namespace: default
data:
  foo: bar
  fizz: buzz

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm2
  namespace: default
data:
  foo: {{ (.ConfigMap "cm1").fizz }}
```

In the above example trying to read the key 'foo' in configmap 'cm2' would yield 'buzz'.
## Problems
1. How should this data be propagated?
2. How do we handle changes?
3. What about volumes?

I believe these problems are very similar to ones that we address in https://github.com/kubernetes/kubernetes/issues/29607 and would share some solutions. In both cases we need to handle changes of values that are external to the configmap. The possible solutions could be:
1. Eager rerendering the ConfigMap on every access. This is the simplest solution, but we need to examine if there are some use cases that would cause severe losses of performance. The consumers of config-maps would share a lot responsibility for efficient use of them, so the documentation should warn them.
2. Notifications. This would be much harder to implement. Every config map should listen to events that might mean that some of the value is changed.

Please comment!
