### ISSUE TITLE
Export matching named ports through endpoints

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#29874]
Ingress currently allows you to plug a service + port into the backends section. However if you have an ingress like:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-logging
  namespace: kube-system
spec:
  rules:
  - host: phive-logs.pmi.ag
    http:
      paths:
      - backend:
          serviceName: kibana-logging
          servicePort: 5601
        path: /
```

With a service like:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: kube-system
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana-logging
```

The ingress controller needs to get pods and figure out the matching targetPort, because the endpointPort object has a Name field that matches the Name on the ServicePort. 

Can we export an omitempty portName field in the EndpointPoint so all ingress controllers don't have to watch pods: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1897 ?

@kubernetes/sig-network
