### ISSUE TITLE
Pet sets stuck in Init state though the pods are running

### ISSUE THREAD

**Issue by oba11** [kubernetes/kubernetes#29972]
Hit an issue with the pet set states switching from **running state** to **init state**. Initially I thought the pods aren't running but later figured out that the containers are actually running but the container state is not consistent with the pod state in kubernetes api.
### Issue

```
Container State: Running
Pod State: Pending
```
### Kubernetes Cluster Version

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3", GitCommit:"c6411395e09da356c608896d3d9725acab821418", GitTreeState:"clean", BuildDate:"2016-07-22T20:29:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3", GitCommit:"c6411395e09da356c608896d3d9725acab821418", GitTreeState:"clean", BuildDate:"2016-07-22T20:22:25Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```
## Kubernetes Get Pod State

```
kubectl get po -l app=zk
NAME      READY     STATUS     RESTARTS   AGE
zoo-0     0/1       Init:0/2   0          13h
zoo-1     0/1       Init:0/2   0          13h
zoo-2     0/1       Init:0/2   0          13h
```
## Kubernetes Describe Pod State

```
kubectl describe po zoo-0
Name:       zoo-0
Namespace:  default
Node:       ip-1-2-3-4.region.compute.internal/10.1.2.3
Start Time: Tue, 02 Aug 2016 20:33:34 +0400
Labels:     app=zk
        name=zoo
Status:     Pending
IP:     10.24.1.2
Controllers:    PetSet/zoo
Init Containers:
  install:
    Container ID:   
    Image:      gcr.io/google_containers/zookeeper-install:0.1
    Image ID:       
    Port:       
    Args:
      --version=3.5.0-alpha
      --install-into=/opt
      --work-dir=/work-dir
    State:          Waiting
      Reason:           PodInitializing
    Ready:          False
    Restart Count:      0
    Environment Variables:  <none>
  bootstrap:
    Container ID:   
    Image:      java:openjdk-8-jre
    Image ID:       
    Port:       
    Command:
      /work-dir/peer-finder
    Args:
      -on-start="/work-dir/on-start.sh"
      -service=zk
    State:      Waiting
      Reason:       PodInitializing
    Ready:      False
    Restart Count:  0
    Environment Variables:
      POD_NAMESPACE:    default (v1:metadata.namespace)
Containers:
  zk:
    Container ID:   docker://4a2e193fa6c86559c9387a0ee473596be59cff2fb7dcd10ca9bb08c9918e6d13
    Image:      java:openjdk-8-jre
    Image ID:       docker://sha256:372859dd1c695759fe765be375346390ddd393f76fa84319630d1d64b85b9806
    Ports:      2888/TCP, 3888/TCP
    Command:
      /opt/zookeeper/bin/zkServer.sh
    Args:
      start-foreground
    State:          Running
      Started:          Tue, 02 Aug 2016 20:33:58 +0400
    Ready:          True
    Restart Count:      0
    Readiness:          exec [sh -c /opt/zookeeper/bin/zkCli.sh ls /] delay=15s timeout=5s period=10s #success=1 #failure=3
    Environment Variables:  <none>
Conditions:
  Type      Status
  Initialized   False 
  Ready     True 
  PodScheduled  True 
Volumes:
  datadir:
    Type:   PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-zoo-0
    ReadOnly:   false
  workdir:
    Type:   EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium: 
  opt:
    Type:   EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium: 
QoS Tier:   BestEffort
No events.
```
### Container State

```
core@ip-1-2-3-4 ~ $ docker ps | grep zoo-0
4a2e193fa6c8        java:openjdk-8-jre                         "/opt/zookeeper/bin/z"   13 hours ago        Up 13 hours                                                    k8s_zk.484fe5b9_zoo-0_default_db0ce747-58ce-11e6-8261-02548dfad2e5_4424c4ea
1b74ed7351fd        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 13 hours ago        Up 13 hours                                                    k8s_POD.85382e2a_zoo-0_default_db0ce747-58ce-11e6-8261-02548dfad2e5_18dc3c54

```
## Node State

```
System Info:
 Machine ID:            ID
 System UUID:           UUID
 Boot ID:           BOOT_ID
 Kernel Version:        4.6.3-coreos
 OS Image:          CoreOS 1068.8.0 (MoreOS)
 Operating System:      linux
 Architecture:          amd64
 Container Runtime Version: docker://1.10.3
 Kubelet Version:       v1.3.3
 Kube-Proxy Version:        v1.3.3

```

**Comment by dchen1107** [comment]
This sounds like a bug introduced by init containers. Thanks for such detail issue reports and will try to reproduce it. cc/ @smarterclayton @erictune

**Comment by dchen1107** [comment]
Just saw a flake test #29954, which might have the same cause as this issue.

**Comment by dchen1107** [comment]
I couldn't reproduce the issue at all. Also the flake reported at #29954 is never re-occur. I will leave this issue open for a while.

**Comment by mikebryant** [comment]
I believe we're hitting this issue too - running a zookeeper petset with init containers, the pod starts up, init containers run, main container runs.
Then a short time later the pod status goes back to Init 0/1, but the main container is still running

If I can reproduce it reliably what debug output would be helpful?

**Comment by dshulyak** [comment]
@mikebryant you are hitting this with 1.4 release? how many kubelet nodes?

**Comment by dchen1107** [comment]
@mikebryant If you can reproduce the issue, could you please provide the following information:

1) docker info
2) zookeeper petset podspec
3) kubectl describe pod <pod-id>
4) related kubelet logs

Thanks

**Comment by dims** [comment]
This needs to be triaged as a release-blocker or not for 1.5 @oba11 @dchen1107

**Comment by smarterclayton** [comment]
Not a blocker because we have had no recreations.

**Comment by DSTOLF** [comment]
Hi, I've hit a similar issue here, running Kubernetes on CoreOS, except it doesn't even create all the pods, just the first one.

If there's anything else you need, please let me know.

**CoreOS Version**
> `core@VINCORE701 ~ $ uname -a
Linux VINCORE701.dev1.stelo.local 4.7.1-coreos #1 SMP Wed Aug 31 10:16:05 CDT 2016 x86_64 Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz GenuineIntel GNU/Linux
`

**Kubernetes Cluster Version**

> Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.3+coreos.0", GitCommit:"7819c84f25e8c661321ee80d6b9fa5f4ff06676f", GitTreeState:"clean", BuildDate:"2016-10-17T21:19:17Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

kubectl get pods state
> `$ kubectl get pods
NAME      READY     STATUS     RESTARTS   AGE
zoo-0     0/1       Init:0/2   0          1m
`

**kubectl describe pod** 
> `kubectl describe pod zoo-0
Name:		zoo-0
Namespace:	default
Node:		10.150.9.27/10.150.9.27
Start Time:	Thu, 17 Nov 2016 11:09:55 -0200
Labels:		app=zk
Status:		Pending
IP:		169.254.50.6
Controllers:	PetSet/zoo
Init Containers:
  install:
    Container ID:	docker://eab8527b8262bb7da463beddd4b16d3f582a8856c8743f143977c84e9ed01333
    Image:		gcr.io/google_containers/zookeeper-install:0.1
    Image ID:		docker://sha256:99da5a092e764b2b1b5cbfaeec0a4b485eb2390efd85328ad9581cbde77c54c0
    Port:		
    Args:
      --version=3.5.0-alpha
      --install-into=/opt
      --work-dir=/work-dir
    State:			Terminated
      Reason:			Completed
      Exit Code:		0
      Started:			Thu, 17 Nov 2016 11:11:03 -0200
      Finished:			Thu, 17 Nov 2016 11:11:23 -0200
    Ready:			True
    Restart Count:		0
    Environment Variables:	<none>
  bootstrap:
    Container ID:	docker://c6dd9edb3321641f5d8b41edaa090f04727ec24f79df4c37826026387552bb54
    Image:		java:openjdk-8-jre
    Image ID:		docker://sha256:b13ebf1a499999325c5493d6412a687b164256360477df0a23afbd5574103981
    Port:		
    Command:
      /work-dir/peer-finder
    Args:
      -on-start="/work-dir/on-start.sh"
      -service=zk
    State:		Running
      Started:		Thu, 17 Nov 2016 11:11:24 -0200
    Ready:		False
    Restart Count:	0
    Environment Variables:
      POD_NAMESPACE:	default (v1:metadata.namespace)
Containers:
  zk:
    Container ID:	
    Image:		java:openjdk-8-jre
    Image ID:		
    Ports:		2888/TCP, 3888/TCP
    Command:
      /opt/zookeeper/bin/zkServer.sh
    Args:
      start-foreground
    State:			Waiting
      Reason:			PodInitializing
    Ready:			False
    Restart Count:		0
    Readiness:			exec [sh -c /opt/zookeeper/bin/zkCli.sh ls /] delay=15s timeout=5s period=10s #success=1 #failure=3
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	False 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  datadir:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	datadir-zoo-0
    ReadOnly:	false
  opt:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  workdir:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  default-token-03q30:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-03q30
QoS Tier:	BestEffort
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----			-------------			--------	------		-------
  2m		2m		1	{default-scheduler }					Normal		Scheduled	Successfully assigned zoo-0 to 10.150.9.27
  1m		1m		1	{kubelet 10.150.9.27}	spec.initContainers{install}	Normal		Pulling		pulling image "gcr.io/google_containers/zookeeper-install:0.1"
  1m		1m		1	{kubelet 10.150.9.27}	spec.initContainers{install}	Normal		Pulled		Successfully pulled image "gcr.io/google_containers/zookeeper-install:0.1"
  1m		1m		1	{kubelet 10.150.9.27}	spec.initContainers{install}	Normal		Created		Created container with docker id eab8527b8262; Security:[seccomp=unconfined]
  1m		1m		1	{kubelet 10.150.9.27}	spec.initContainers{install}	Normal		Started		Started container with docker id eab8527b8262
  1m		1m		1	{kubelet 10.150.9.27}	spec.initContainers{bootstrap}	Normal		Pulled		Container image "java:openjdk-8-jre" already present on machine
  1m		1m		1	{kubelet 10.150.9.27}	spec.initContainers{bootstrap}	Normal		Created		Created container with docker id c6dd9edb3321; Security:[seccomp=unconfined]
  1m		1m		1	{kubelet 10.150.9.27}	spec.initContainers{bootstrap}	Normal		Started		Started container with docker id c6dd9edb3321
`
**Container State**
> `docker ps| grep zoo
c6dd9edb3321        java:openjdk-8-jre                                           "/work-dir/peer-finde"   5 minutes ago       Up 5 minutes                            k8s_bootstrap.9351faf6_zoo-0_default_223f593f-acc7-11e6-9732-061a2edfc0e3_7a4bae2c
46e68b01fbb1        gcr.io/google_containers/pause-amd64:3.0                     "/pause"                 6 minutes ago       Up 6 minutes                            k8s_POD.d8dbe16c_zoo-0_default_223f593f-acc7-11e6-9732-061a2edfc0e3_4fd305b1
`

**kubectl describe service**
> `kubectl describe service zk
Name:			zk
Namespace:		default
Labels:			app=zk
Selector:		app=zk
Type:			ClusterIP
IP:			None
Port:			peer	2888/TCP
Endpoints:		<none>
Port:			leader-election	3888/TCP
Endpoints:		<none>
Session Affinity:	None
No events.
`

**kubectl describe petset**

> `kubectl describe petset zoo
Name:			zoo
Namespace:		default
Image(s):		java:openjdk-8-jre
Selector:		app=zk
Labels:			app=zk
Replicas:		3 current / 3 desired
Annotations:		<none>
CreationTimestamp:	Thu, 17 Nov 2016 11:09:55 -0200
Pods Status:		0 Running / 1 Waiting / 0 Succeeded / 0 Failed
Volumes:
  opt:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
  workdir:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
Events:
  FirstSeen	LastSeen	Count	From		SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----		-------------	--------	------			-------
  20m		20m		1	{petset }			Normal		SuccessfulCreate	pet: zoo-0
`

**kubectl get nodes**
> `kubectl get nodes
NAME          STATUS                     AGE
10.150.9.25   Ready                      2h
10.150.9.27   Ready                      2h
10.150.9.7    Ready,SchedulingDisabled   2h
`

**kubectl describe node**

> `kubectl describe node 10.150.9.27
Name:			10.150.9.27
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=10.150.9.27
Taints:			<none>
CreationTimestamp:	Thu, 17 Nov 2016 08:39:33 -0200
Phase:			
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  OutOfDisk 		False 	Thu, 17 Nov 2016 11:23:54 -0200 	Thu, 17 Nov 2016 08:39:33 -0200 	KubeletHasSufficientDisk 	kubelet has sufficient disk space available
  MemoryPressure 	False 	Thu, 17 Nov 2016 11:23:54 -0200 	Thu, 17 Nov 2016 08:39:33 -0200 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  DiskPressure 		False 	Thu, 17 Nov 2016 11:23:54 -0200 	Thu, 17 Nov 2016 08:39:33 -0200 	KubeletHasNoDiskPressure 	kubelet has no disk pressure
  Ready 		True 	Thu, 17 Nov 2016 11:23:54 -0200 	Thu, 17 Nov 2016 08:39:43 -0200 	KubeletReady 			kubelet is posting ready status
Addresses:		10.150.9.27,10.150.9.27
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					2
 memory:				4045600Ki
 pods:					110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:	0
 cpu:					2
 memory:				4045600Ki
 pods:					110
System Info:
 Machine ID:			48230110dd084e91b7b6885728b98295
 System UUID:			8BED96D0-C411-3CD8-4A68-82776571640C
 Boot ID:			6480c850-71ee-4c7b-981e-7c83895735c2
 Kernel Version:		4.7.1-coreos
 OS Image:			CoreOS 1068.10.0+2016-08-31-1023 (MoreOS)
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.12.1
 Kubelet Version:		v1.4.3+coreos.0
 Kube-Proxy Version:		v1.4.3+coreos.0
ExternalID:			10.150.9.27
Non-terminated Pods:		(4 in total)
  Namespace			Name						CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----						------------	----------	---------------	-------------
  default			zoo-0						0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-proxy-10.150.9.27				0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kube-scheduler-10.150.9.27			0 (0%)		0 (0%)		0 (0%)		0 (0%)
  kube-system			kubernetes-dashboard-v1.4.1-sz70j		100m (5%)	100m (5%)	50Mi (1%)	50Mi (1%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  100m (5%)	100m (5%)	50Mi (1%)	50Mi (1%)
`

**docker info**

> `docker info
Containers: 10
 Running: 8
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: selinux
Kernel Version: 4.7.1-coreos
Operating System: CoreOS 1068.10.0+2016-08-31-1023 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: VINCORE703.dev1.stelo.local
ID: P4NN:TZO7:ZPED:3DOU:Q4GE:RSIE:VPXV:BMO3:YKML:QB6A:544I:O6RD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://proxy2.dev1.local:3130
Https Proxy: http://proxy2.dev1.local:3130
No Proxy: *.stelo.local,10.150.9.*,localhost,127.0.0.1
Registry: https://index.docker.io/v1/
Insecure Registries:
 172.29.0.0/24
 127.0.0.0/8
`

**zookeeper.yaml**
> `cat zookeeper/zookeeper.yaml 
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: zk
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: peer
  - port: 3888
    name: leader-election
  # *.zk.default.svc.cluster.local
  clusterIP: None
  selector:
    app: zk
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: zoo
spec:
  serviceName: "zk"
  replicas: 3
  template:
    metadata:
      labels:
        app: zk
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
            {
                "name": "install",
                "image": "gcr.io/google_containers/zookeeper-install:0.1",
                "imagePullPolicy": "Always",
                "args": ["--version=3.5.0-alpha", "--install-into=/opt", "--work-dir=/work-dir"],
                "volumeMounts": [
                    {
                        "name": "opt",
                        "mountPath": "/opt/"
                    },
                    {
                        "name": "workdir",
                        "mountPath": "/work-dir"
                    }
                ]
            },
            {
                "name": "bootstrap",
                "image": "java:openjdk-8-jre",
                "command": ["/work-dir/peer-finder"],
                "args": ["-on-start=\"/work-dir/on-start.sh\"", "-service=zk"],
                "env": [
                  {
                      "name": "POD_NAMESPACE",
                      "valueFrom": {
                          "fieldRef": {
                              "apiVersion": "v1",
                              "fieldPath": "metadata.namespace"
                          }
                      }
                   }
                ],
                "volumeMounts": [
                    {
                        "name": "opt",
                        "mountPath": "/opt/"
                    },
                    {
                        "name": "workdir",
                        "mountPath": "/work-dir"
                    },
                    {
                        "name": "datadir",
                        "mountPath": "/tmp/zookeeper"
                    }
                ]
            }
        ]'
    spec:
      containers:
      - name: zk
        image: java:openjdk-8-jre
        ports:
        - containerPort: 2888
          name: peer
        - containerPort: 3888
          name: leader-election
        command:
        - /opt/zookeeper/bin/zkServer.sh
        args:
        - start-foreground
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "/opt/zookeeper/bin/zkCli.sh ls /"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /tmp/zookeeper
        - name: opt
          mountPath: /opt/
      volumes:
      - name: opt
        emptyDir: {}
      - name: workdir
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
`

** PV spec **

> `cat ceph/ceph-pv1.yaml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rbd1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    # FIXME: use the right IP
    monitors: [ "10.150.9.21:6789",
              "10.150.9.14:6789",
              "10.150.9.11:6789",
              "10.150.9.12:6789" ]
    image: "rbd1"
    secretRef: 
      name: "ceph-secret"
    fsType: "ext4"
`

** pv mount state inside container **
> `docker exec -it c6dd9edb3321 df -kh /tmp/zookeeper 
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd0        20G   44M   20G   1% /tmp/zookeeper

docker exec -it c6dd9edb3321 mount | grep zoo     
/dev/rbd0 on /tmp/zookeeper type ext4 (rw,relatime,seclabel,stripe=1024,data=ordered)
`

**Comment by DSTOLF** [comment]
Hi,

Nevermind, I got the zookeeper example working. It was a problem with a miss configuration on kube-controller.

**Comment by mzehrer** [comment]
I have this issue also with the new StatefulSets on 1.5.1

This is a pod

```
root@kub01:~# kubectl describe pod cockroachdb-0
Name:		cockroachdb-0
Namespace:	default
Node:		ossn02/10.10.4.82
Start Time:	Sun, 18 Dec 2016 20:42:52 +0100
Labels:		app=cockroachdb
Status:		Pending
IP:		10.39.0.8
Controllers:	StatefulSet/cockroachdb
Init Containers:
  bootstrap:
    Container ID:	
    Image:		cockroachdb/cockroach-k8s-init:0.1
    Image ID:		
    Port:		
    Args:
      -on-start=/on-start.sh
      -service=cockroachdb
    State:		Waiting
      Reason:		PodInitializing
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /cockroach/cockroach-data from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jd4sr (ro)
    Environment Variables:
      POD_NAMESPACE:	default (v1:metadata.namespace)
Containers:
  cockroachdb:
    Container ID:	docker://3168145e8b10930f602b36f701ad8e79d2e790a3a6171b1cf528282fb6247e2a
    Image:		cockroachdb/cockroach:beta-20161215
    Image ID:		docker-pullable://cockroachdb/cockroach@sha256:f430259175f25bc7a0b36a902be237b6267cd4fb53fe787062c016d390fe23be
    Ports:		26257/TCP, 8080/TCP
    Command:
      /bin/bash
      -ecx
      # The use of qualified `hostname -f` is crucial:
# Other nodes aren't able to look up the unqualified hostname.
CRARGS=("start" "--logtostderr" "--insecure" "--host" "$(hostname -f)" "--http-host" "0.0.0.0")
# We only want to initialize a new cluster (by omitting the join flag)
# if we're sure that we're the first node (i.e. index 0) and that
# there aren't any other nodes running as part of the cluster that
# this is supposed to be a part of (which indicates that a cluster
# already exists and we should make sure not to create a new one).
# It's fine to run without --join on a restart if there aren't any
# other nodes.
if [ ! "$(hostname)" == "cockroachdb-0" ] || \
   [ -e "/cockroach/cockroach-data/cluster_exists_marker" ]
then
  # We don't join cockroachdb in order to avoid a node attempting
  # to join itself, which currently doesn't work
  # (https://github.com/cockroachdb/cockroach/issues/9625).
  CRARGS+=("--join" "cockroachdb-public")
fi
exec /cockroach/cockroach ${CRARGS[*]}

    State:		Running
      Started:		Sun, 18 Dec 2016 20:45:13 +0100
    Ready:		True
    Restart Count:	2
    Liveness:		http-get http://:http/_admin/v1/health delay=30s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:http/_admin/v1/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Volume Mounts:
      /cockroach/cockroach-data from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jd4sr (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	False 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  datadir:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	datadir-cockroachdb-0
    ReadOnly:	false
  default-token-jd4sr:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-jd4sr
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  25m		25m		2	{kubelet ossn02}			Warning		FailedMount	MountVolume.SetUp failed for volume "kubernetes.io/secret/2a13c4eb-c55a-11e6-85cf-005056bd5829-default-token-jd4sr" (spec.Name: "default-token-jd4sr") pod "2a13c4eb-c55a-11e6-85cf-005056bd5829" (UID: "2a13c4eb-c55a-11e6-85cf-005056bd5829") with: Get https://10.10.4.50:6443/api/v1/namespaces/default/secrets/default-token-jd4sr: dial tcp 10.10.4.50:6443: getsockopt: connection refused
root@kub01:~# kubectl describe pod cockroachdb-1
Name:		cockroachdb-1
Namespace:	default
Node:		docker-node4/10.10.4.84
Start Time:	Sun, 18 Dec 2016 20:43:32 +0100
Labels:		app=cockroachdb
Status:		Pending
IP:		10.47.0.9
Controllers:	StatefulSet/cockroachdb
Init Containers:
  bootstrap:
    Container ID:	
    Image:		cockroachdb/cockroach-k8s-init:0.1
    Image ID:		
    Port:		
    Args:
      -on-start=/on-start.sh
      -service=cockroachdb
    State:		Waiting
      Reason:		PodInitializing
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /cockroach/cockroach-data from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jd4sr (ro)
    Environment Variables:
      POD_NAMESPACE:	default (v1:metadata.namespace)
Containers:
  cockroachdb:
    Container ID:	docker://545a0ce6a6d2a942501be478d5761d33d0a2224d58d831012a01479668ae4042
    Image:		cockroachdb/cockroach:beta-20161215
    Image ID:		docker-pullable://cockroachdb/cockroach@sha256:f430259175f25bc7a0b36a902be237b6267cd4fb53fe787062c016d390fe23be
    Ports:		26257/TCP, 8080/TCP
    Command:
      /bin/bash
      -ecx
      # The use of qualified `hostname -f` is crucial:
# Other nodes aren't able to look up the unqualified hostname.
CRARGS=("start" "--logtostderr" "--insecure" "--host" "$(hostname -f)" "--http-host" "0.0.0.0")
# We only want to initialize a new cluster (by omitting the join flag)
# if we're sure that we're the first node (i.e. index 0) and that
# there aren't any other nodes running as part of the cluster that
# this is supposed to be a part of (which indicates that a cluster
# already exists and we should make sure not to create a new one).
# It's fine to run without --join on a restart if there aren't any
# other nodes.
if [ ! "$(hostname)" == "cockroachdb-0" ] || \
   [ -e "/cockroach/cockroach-data/cluster_exists_marker" ]
then
  # We don't join cockroachdb in order to avoid a node attempting
  # to join itself, which currently doesn't work
  # (https://github.com/cockroachdb/cockroach/issues/9625).
  CRARGS+=("--join" "cockroachdb-public")
fi
exec /cockroach/cockroach ${CRARGS[*]}

    State:		Running
      Started:		Sun, 18 Dec 2016 20:45:13 +0100
    Ready:		True
    Restart Count:	1
    Liveness:		http-get http://:http/_admin/v1/health delay=30s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:http/_admin/v1/health delay=10s timeout=1s period=10s #success=1 #failure=3
    Volume Mounts:
      /cockroach/cockroach-data from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jd4sr (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	False 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  datadir:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	datadir-cockroachdb-1
    ReadOnly:	false
  default-token-jd4sr:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-jd4sr
QoS Class:	BestEffort
Tolerations:	<none>
No events.
```

and the StefulSet:

```
root@kub01:~# kubectl describe statefulset cockroachdb
Name:			cockroachdb
Namespace:		default
Image(s):		cockroachdb/cockroach:beta-20161215
Selector:		app=cockroachdb
Labels:			app=cockroachdb
Replicas:		3 current / 3 desired
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"kind":"StatefulSet","apiVersion":"apps/v1beta1","metadata":{"name":"cockroachdb","creationTimestamp":null},"spec":{"replicas":3,"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"cockroachdb"},"annotations":{"pod.alpha.kubernetes.io/init-containers":"[ { \"name\": \"bootstrap\", \"image\": \"cockroachdb/cockroach-k8s-init:0.1\", \"args\": [ \"-on-start=/on-start.sh\", \"-service=cockroachdb\" ], \"env\": [ { \"name\": \"POD_NAMESPACE\", \"valueFrom\": { \"fieldRef\": { \"apiVersion\": \"v1\", \"fieldPath\": \"metadata.namespace\" } } } ], \"volumeMounts\": [ { \"name\": \"datadir\", \"mountPath\": \"/cockroach/cockroach-data\" } ] } ]","pod.alpha.kubernetes.io/initialized":"true"}},"spec":{"volumes":[{"name":"datadir","persistentVolumeClaim":{"claimName":"datadir"}}],"containers":[{"name":"cockroachdb","image":"cockroachdb/cockroach:beta-20161215","command":["/bin/bash","-ecx","# The use of qualified `hostname -f` is crucial:\n# Other nodes aren't able to look up the unqualified hostname.\nCRARGS=(\"start\" \"--logtostderr\" \"--insecure\" \"--host\" \"$(hostname -f)\" \"--http-host\" \"0.0.0.0\")\n# We only want to initialize a new cluster (by omitting the join flag)\n# if we're sure that we're the first node (i.e. index 0) and that\n# there aren't any other nodes running as part of the cluster that\n# this is supposed to be a part of (which indicates that a cluster\n# already exists and we should make sure not to create a new one).\n# It's fine to run without --join on a restart if there aren't any\n# other nodes.\nif [ ! \"$(hostname)\" == \"cockroachdb-0\" ] || \\\n   [ -e \"/cockroach/cockroach-data/cluster_exists_marker\" ]\nthen\n  # We don't join cockroachdb in order to avoid a node attempting\n  # to join itself, which currently doesn't work\n  # (https://github.com/cockroachdb/cockroach/issues/9625).\n  CRARGS+=(\"--join\" \"cockroachdb-
public\")\nfi\nexec /cockroach/cockroach ${CRARGS[*]}\n"],"ports":[{"name":"grpc","containerPort":26257},{"name":"http","containerPort":8080}],"resources":{},"volumeMounts":[{"name":"datadir","mountPath":"/cockroach/cockroach-data"}],"livenessProbe":{"httpGet":{"path":"/_admin/v1/health","port":"http"},"initialDelaySeconds":30},"readinessProbe":{"httpGet":{"path":"/_admin/v1/health","port":"http"},"initialDelaySeconds":10},"imagePullPolicy":"IfNotPresent"}],"terminationGracePeriodSeconds":60}},"volumeClaimTemplates":[{"metadata":{"name":"datadir","creationTimestamp":null,"annotations":{"volume.beta.kubernetes.io/storage-class":"example-nfs"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"1Gi"}}},"status":{}}],"serviceName":"cockroachdb"},"status":{"replicas":0}}
CreationTimestamp:	Sun, 18 Dec 2016 18:24:39 +0100
Pods Status:		0 Running / 4 Waiting / 0 Succeeded / 0 Failed
Volumes:
  datadir:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	datadir
    ReadOnly:	false
No events.
```
