### ISSUE TITLE
loadBalancerSourceRanges does not work on GKE

### ISSUE THREAD

**Issue by ged15** [kubernetes/kubernetes#29997]
Hello!

I am running a cluster on GKE (k8s version 1.3.3) and have the following service definition:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: api
    tier: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: <a static IP>
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  ports:
  - name: https
    port: 443
  - name: http
    port: 80
  selector:
    app: api
    tier: frontend
```

When I apply this configuration, the source IP range in the created firewall rule is still `0.0.0.0/0`. Am I missing something? The `loadBalancerIP` seems to be applied correctly every time.
