### ISSUE TITLE
Cleanup orphaned pods (unmount pods directories)

### ISSUE THREAD

**Issue by suquant** [kubernetes/kubernetes#30067]
Hi all,

Sometimes we delete/kill pods who is uses NFS directories which also run in kubernetes cluster or somewhere else.

**Simple case**:
1. Run gluster server pod
2. Run app server which use gluster server volume as NFS mount point
3. Delete gluster pod
4. Delete app pod

gluster.yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: gluster1
  namespace: gitlab
  labels:
    component: glusterfs-storage
    host: st01
spec:
  nodeSelector:
    host: st01
  containers:
    - name: glusterfs-server
      image: suquant/glusterd:3.6.kube
      imagePullPolicy: Always
      command:
        - /kubernetes-glusterd
      args:
        - --namespace
        - gitlab
        - --labels
        - component=glusterfs-storage
      ports:
        - containerPort: 24007
        - containerPort: 24008
        - containerPort: 49152
        - containerPort: 38465
        - containerPort: 38466
        - containerPort: 38467
        - containerPort: 2049
        - containerPort: 111
        - containerPort: 111
          protocol: UDP
      volumeMounts:
        - name: brick
          mountPath: /mnt/brick
        - name: fuse
          mountPath: /dev/fuse
        - name: data
          mountPath: /var/lib/glusterd
      securityContext:
        capabilities:
          add:
            - SYS_ADMIN
            - MKNOD
  volumes:
    - name: brick
      hostPath:
        path: /mnt/gitlab
    - name: fuse
      hostPath:
        path: /dev/fuse
    - name: data
      hostPath:
        path: /opt/var/lib/gluster/gitlab
```

app.yaml

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: gitlab
    version: 8.10.3-ce.0
  name: gitlab
  namespace: gitlab
spec:
  nodeSelector:
    host: app02
  containers:
    - name: gitlab
      image: gitlab/gitlab-ce:8.10.3-ce.0
      ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
      volumeMounts:
        - name: data
          mountPath: /var/opt/gitlab
  volumes:
    - name: data
      nfs:
        server: glusterfs-storage
        path: /media

```

After delete/kill glusterfs pod before delete/kill app pod, which is gitlab app.
What is happen in this case:
1. After delete/kill glusterfs server nfs was unavailable
2. gitlab also used nfs from glusterfs-storage which is unavailable after
3. After delete  app pod, cleanup method in kubernetes working incorrectly because unmount unused pod directory stay in NFS I/O wait which is unavailable forever.

How this appears in logs:

```
...
Aug 04 10:34:03 app03 kubelet-wrapper[15357]: E0804 10:34:03.552870   15357 kubelet.go:2596] Failed cleaning pods: remove /var/lib/kubelet/pods/dc8634a9-56fd-11e6-b43a-305a3a75dc73/volumes/kubernetes.io~nfs/image-store: device or resource busy
...
```

**Solutions:**

We need detect network storage mount point which is NFS one of that and force unmount it with --force and --lazy options.

```
umount --force --lazy /var/lib/kubelet/pods/dc8634a9-56fd-11e6-b43a-305a3a75dc73/volumes/kubernetes.io~nfs/image-store
```

Also this kind of problem appears in secrets (http://kubernetes.io/docs/user-guide/secrets/) and configmaps (http://kubernetes.io/docs/user-guide/configmap/) mount points.

Thank you.
