### ISSUE TITLE
Pets in a PetSet not exposed via DNS

### ISSUE THREAD

**Issue by etotheipi** [kubernetes/kubernetes#30076]
I have created a PetSet, and tried giving it both the same and diffferent `serviceName` than the k8s Service I use to expose the pets to the outside world.  Neither case appears to provide DNS resolution for the pets to talk to each other.

Here's the first pet:
```
$ k exec -it zookeeper-0 bash
[root@zookeeper-0 zookeeper]# cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
10.246.100.3	zookeeper-0.zookeeper-cluster.default.svc.cluster.local	zookeeper-0
```

And after installing bind-utils in one of the other pets:
```
# nslookup zookeeper-0.zookeeper-cluster.default.svc.cluster.local
Server:		10.247.0.10
Address:	10.247.0.10#53

** server can't find zookeeper-0.zookeeper-cluster.default.svc.cluster.local:
```

The documentation on petsets suggest that each Pet should get a DNS-resolvable name, and so far I have not found that to be the case no matter what I do.

Here's my petset definition:
```
apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper-cluster
  replicas: 3
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: zookeeper
        type: node
        version: 3.4.8
    spec:
      volumes:
        - name: zookeeperdatadir
          emptyDir: {}
      containers:
        - name: zookeeper-node
          image: localregistry.io/zookeeper-petset
          imagePullPolicy: Always
          ports:
            - name: client
              containerPort: 2181
            - name: follower
              containerPort: 2888
            - name: leader
              containerPort: 3888
          volumeMounts:
            - name: zookeeperdatadir
              mountPath: /var/zookeeper/datadir
```

Am I doing something wrong or did I misunderstand the documentation?

**Comment by ianunruh** [comment]
I can confirm this issue on Kubernetes 1.3.5. I was expecting this functionality to be able to cluster RabbitMQ.

```
bash-4.3$ hostname
rabbitmq-1
bash-4.3$ hostname -f
rabbitmq-1.rabbitmq.default.svc.cluster.local
bash-4.3$ ping rabbitmq-0.rabbitmq
ping: bad address 'rabbitmq-0.rabbitmq'
bash-4.3$ ping rabbitmq-0.rabbitmq.default.svc.cluster.local
ping: bad address 'rabbitmq-0.rabbitmq.default.svc.cluster.local'
```

```
[~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by xavierholt** [comment]
Seeing the same problem in Kubernetes 1.3.4 on CoreOS.  Does anyone have any idea on the cause / potential workarounds?

```
/ # hostname -i
10.2.81.3
/ # hostname -f
consul-0.consul.suvfork.svc.cluster.local
/ # nslookup consul-0.consul.suvfork.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      consul-0.consul.suvfork.svc.cluster.local
Address 1: 10.2.81.3 consul-0.consul.suvfork.svc.cluster.local
/ # nslookup consul-1.consul.suvfork.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'consul-1.consul.suvfork.svc.cluster.local': Name does not resolve
/ # nslookup consul.suvfork.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      consul.suvfork.svc.cluster.local
Address 1: 10.3.0.203
```

**Comment by xavierholt** [comment]
Found a fix!  Short version:  Add `clusterIP: None` to your Service spec to make it "headless."
 - The SO post that gave me the starting point:  
   https://stackoverflow.com/questions/38901877/kubernetes-petset-dns-not-working
 - The docs it references:  
   http://kubernetes.io/docs/user-guide/petset/#network-identity
 - Details on headless services:  
   http://kubernetes.io/docs/user-guide/services/#headless-services

No idea why the service needs to be headless.  The current behavior sure seems like a bug (per the SO answer:  "you don't get an error - you just get random DNS names for you [sic] pets").

**Comment by etotheipi** [comment]
Yes, that worked for me.  Almost.

I made it a headless service as you suggested using `clusterIP: None`.  I believe what that means is that (in my case) you don't get a *head* `zookeeper-cluster` hostname anymore that points to all of them.  Instead, the service is only used to expose the individual pods behind it, and petset takes advantage of that when you declare the matching `serviceName` field.  I'm not sure either, why that is required.

So I got one step further, now by hardcoding each pet to find each other pet via `zookeeper-1.zookeeper-cluster:2181`, etc.  However, I'm not out of the woods yet.  Although `zookeeper-X.zookeeper-cluster` resolves properly to the correct pod IP, it seems that not all my ports are exposed properly, and I'm not sure if this is a problem with the petset, service, or pebkac.  

The logs for zookeeper trying to connect to another over 3888 indicates that the dest refused the connection.  A nearly identical configuration outside of k8s works fine.

```
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
  labels:
    app: zookeeper
    type: service
spec:
  clusterIP: None
  ports:
    - name: clientport
      port: 2181
      targetPort: 2181
    - name: followerport
      port: 2888
      targetPort: 2888
    - name: leaderport
      port: 3888
      targetPort: 3888
  selector:
    app: zookeeper
    type: node
---
apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
    type: petset
spec:
  serviceName: zookeeper-cluster
  replicas: 3
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: zookeeper
        type: node
        version: 3.4.8
    spec:
      containers:
        - name: zookeeper-node
          image: service.de.vm.ironnet.io:5001/areiner/zookeeper-petset
          imagePullPolicy: Always
          ports:
            - name: client
              containerPort: 2181
            - name: follower
              containerPort: 2888
            - name: leader
              containerPort: 3888
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
```

Is this the correct way to expose the three ports?  I do have `EXPOSE 2181 2888 3888` in the Dockerfile (is that even necessary?).
