### ISSUE TITLE
Feature; if kubernetes created the folders that didn't exist in the paths for nfs mounts

### ISSUE THREAD

**Issue by jonathan-kosgei** [kubernetes/kubernetes#30140]
With:
``` 
     volumes:
      - name: wordpress-nfs
        nfs:
          server: 172.1.2.6
          path: "/storage/jonathan/helloworld/wordpress"
      - name: mysql-nfs
        nfs:
          server: 172.1.2.6
          path: "/storage/jonathan/helloworld/mysql"
      - name: mysql-conf
        hostPath:
          path: "/home/jonathan/mysql.conf"
```

It would be great if I could swap `jonathan` with the name of another user say `dan` and have `/storage/dan/helloworld/wordpress` created or if `jonathan` has other wordpress sites he'd like to use the same nfs server eg. `/storage/jonathan/companyblog/wordpress` and `kubernetes` would create those paths on the nfs server.

I'm creating the folders manually on the nfs server atm.

**Comment by ravilr** [comment]
this should be somewhat possible by specifying a 'subPath' field in volumeMount of your containers, since v1.3.0 version:
https://github.com/kubernetes/kubernetes/blob/release-1.3/api/swagger-spec/v1.json#L18270

I couldn't find any example in the repo, except this comment from the author of this feature here: https://github.com/kubernetes/kubernetes/issues/20466#issuecomment-192526797

**Comment by jonathan-kosgei** [comment]
Interesting, from the link:

> Path within the volume from which the container's volume should be mounted. Defaults to \"\" (volume's root)

Doesn't this imply though that the path would have to exist within the volume? Which would mean I still have to `mkdir -p` all the paths to the storage folders on the nfs server?

**Comment by jonathan-kosgei** [comment]
Still a very cool feature, can't get over that :-)

**Comment by ravilr** [comment]
you still need to have the base export path on the nfs server pre-setup. kubernetes will create the subpaths specified in each pod.

from your example:
```
# jonathan helloworld pod
containers:
    - name: ".."
       volumeMounts:
       - mountPath: "/wordpress"
          name: wordpress-nfs
          subPath: "jonathan/helloworld"       # this can be "dan/companyblog" for dan's pod
volumes:
      - name: wordpress-nfs
        nfs:
          server: 172.1.2.6
          path: "/storage/wordpress"
      - name: mysql-nfs
        nfs:
          server: 172.1.2.6
          path: "/storage/mysql"
```
after the above pod is binded, you would see kubernetes mounted  172.1.2.6/storage/workdpress/jonathan/helloworld under /wordpress path inside the container.
