### ISSUE TITLE
Third Party Resources list has empty metadata

### ISSUE THREAD

**Issue by ash2k** [kubernetes/kubernetes#30192]
```yaml
---
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "Resource template definition"
metadata:
  name: resource-template.smith.ash2k.com
versions:
  - name: v1
```
Getting `/apis/smith.ash2k.com/v1/resourcetemplates` outputs
```json
{
  "kind": "ResourceTemplateList",
  "apiVersion": "smith.ash2k.com/v1",
  "metadata": {},
  "items": [  ]
}
```
I was expecting `selfLink` and `resourceVersion` to be there just like for e.g. `/apis/extensions/v1beta1/thirdpartyresources`:
```json
{
  "kind": "ThirdPartyResourceList",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "selfLink": "/apis/extensions/v1beta1/thirdpartyresources",
    "resourceVersion": "496"
  },
  "items": [
    "items here"
  ]
}
```
I'm interested in `resourceVersion` because otherwise implementing "watch" operation on the list is not possible.
This is with minikube 0.7.1 (Kubernetes 1.3.3)
