### ISSUE TITLE
large number in ThirdPartyResource encoded as float

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#30213]
When we submit the resource object containing large integer, its field is encoded as floating point with exponents, like 1.03e+9.  We want to encode the number in integer, not floating point, since with the latter we may lose precision, and Go cannot decode such field into int64.

For example, submitting the following third party resource object:

```
apiVersion: foo.example.com/v1alpha1
kind: Foo
metadata:
  name: f1
spec:
  num: 1000000009
```

and getting result from apiserver looks like this:

```
"size":1.000000009e+09
```

Small integer, like 100, is encoded as just 100 as we expected.

We use Kuberentes 1.4.0-alpha.2
