### ISSUE TITLE
Cannot use configmap in pod

### ISSUE THREAD

**Issue by msplayer** [kubernetes/kubernetes#30214]
Hi All, 
  When I create a pod with configmap, it always report error: 'field fieldRef: is required, found invalid field configMap for v1.EnvVarSource', I am using k8s v1.2.0 on CentOS7, below is my pod creating script.

`apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMap:
              configMapName: special-config
              key: special.how
  restartPolicy: Never`

I also use secretKeyRef to replace of configMap, but it does not work still.
Thanks for your reply.

**Comment by asalkeld** [comment]
See: http://kubernetes.io/docs/user-guide/configmap/ in the section "Use-Case: Consume ConfigMap in environment variables"

The following works for me:
```yaml
apiVersion: v1
kind: ConfigMap
data:
  special.how: "medium"
metadata:
  name: special-config

---

apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
  - name: test-container
    image: gcr.io/google_containers/busybox
    command: [ "/bin/sh", "-c", "env" ]
    env:
    - name: SPECIAL_LEVEL_KEY
      valueFrom:
        configMapKeyRef:
          name: special-config
          key: special.how
  restartPolicy: Never
```
