### ISSUE TITLE
Can't resolve domain name in container except kube-dns

### ISSUE THREAD

**Issue by Ladicle** [kubernetes/kubernetes#30210]
I have installed kubernetes(1.3.4) cluster on local server.  
kube-dns can resolve domain name, but other containers can not resolve domain names.

* kube-dns can resolve kubernetes.default.svc.cluster.local & google.com
```
$ kubectl --namespace=kube-system exec -ti kube-dns-v15-e0a9u -c kubedns -- nslookup kubernetes.default.svc.cluster.local 127.0.0.1
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      kubernetes.default.svc.cluster.local
Address 1: 10.232.0.1 kubernetes.default.svc.cluster.local
```
* Other containers can not resolve (have direct dns)
```
$ kubectl exec -ti hoge-798068633-uwtfu -- ping google.com
ping: unknown host

$ kubectl exec -ti hoge-798068633-uwtfu -- ping 216.58.220.238
PING 216.58.220.238 (216.58.220.238): 56 data bytes
64 bytes from 216.58.220.238: icmp_seq=0 ttl=48 time=7.945 ms
64 bytes from 216.58.220.238: icmp_seq=1 ttl=48 time=6.955 ms
64 bytes from 216.58.220.238: icmp_seq=2 ttl=48 time=7.003 ms
^C--- 216.58.220.238 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 6.955/7.301/7.945/0.456 ms
```

## Versions

* kernel
```
$ uname -a
Linux k8s-master-01-u16 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

* kubernetes
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:38:31Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

* flanneld
```
flanneld --version
0.5.5
```

* etcd
```
$ etcd --version
etcd Version: 3.0.4
Git SHA: d53923c
Go Version: go1.6.3
Go OS/Arch: linux/amd64
```

## Kube-dns manifests

* skydns-rc.yaml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v15
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v15
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v15
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v15
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kubedns
        image: gcr.io/google_containers/kubedns-amd64:1.5
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
            scheme: HTTP
          # we poll on pod startup for the Kubernetes master service and
          # only setup the /readiness HTTP server once that's available.
          initialDelaySeconds: 30
          timeoutSeconds: 5
        args:
        # command = "/kube-dns"
        - --domain=cluster.local.
        - --dns-port=10053
        ports:
        - containerPort: 10053
          name: dns-local
          protocol: UDP
        - containerPort: 10053
          name: dns-tcp-local
          protocol: TCP
      - name: dnsmasq
        image: gcr.io/google_containers/dnsmasq:1.1
        args:
        - --cache-size=1000
        - --no-resolv
        - --server=127.0.0.1#10053
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      - name: healthz
        image: gcr.io/google_containers/exechealthz-amd64:1.0
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        args:
        - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
        - -port=8080
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: Default  # Don't use cluster DNS.
```

* skydns-svc.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP:  10.254.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```
