### ISSUE TITLE
hostpath is getting created as root

### ISSUE THREAD

**Issue by bpatelcs** [kubernetes/kubernetes#30378]
I have following config for pod, I have docker file which runs as non root user, and the same user with gid and uid is the owner of /opt/volume on the host machine, when I try to deploy the pod with following config, it is creating the path 'default/srv/test' under '/opt/volume/' with root access and my application is not able to access it.

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test
    image:test
    volumeMounts:
      - mountPath: "/opt/volume"
        name: host-vol
  volumes:
    - name: host-vol
      hostPath:
        path: "/opt/volume/default/srv/test"
```
