### ISSUE TITLE
When running ScheduledJob with ConcurencyPolicy Replace the pods are left behind

### ISSUE THREAD

**Issue by soltysh** [kubernetes/kubernetes#30442]
I've created a ScheduledJobs as follows:
```yaml
apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: test
spec:
  schedule: "*/1 * * * ?"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: test
        spec:
          containers:
          - name: test
            image: gcr.io/google_containers/busybox:1.24
            command: ["sleep", "300"]
          restartPolicy: Never
```
This should replace an existing job with a new one upon next run, so it does the old job is being removed but not its pod. So after a while I have only one job (correct) and two pods (incorrect), one running the old job, the other the new one. I assume this is due to lack of server side deletion (#19054), since currently the job deletion logic is in [JobReaper](https://github.com/kubernetes/kubernetes/blob/7bd2db47f9f70a57fa5ae31a2aabc5cc3f168e94/pkg/kubectl/stop.go#L317). 

@janetkuo depending on timing either you or me need to fix this.
@erictune fyi
