### ISSUE TITLE
NodePort doesn't work properly for kube-up with Ubuntu Provider

### ISSUE THREAD

**Issue by tobegit3hub** [kubernetes/kubernetes#30572]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:38:31Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:  3 `AWS g2.8xlarge instances` cluster
- **OS** (e.g. from /etc/os-release):

``` NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
- **Kernel** (e.g. `uname -a`): `Linux ip-10-69-1-246 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**What happened**:

I have containerized the gRPC server in docker image. Then create the Deployment yaml with one replica and the associated service with NodePort. I found that the if I access the exactly server which runs the gRPC server container, I can get the data with gRPC client. 

![image](https://cloud.githubusercontent.com/assets/2715000/17644129/7bc0adb2-61b0-11e6-9433-ea313da353a8.png)

But if I access the same port from other kubernetes nodes, it raises error. I have testes other service, like nginx, could work no matter which node I choose to access.

![image](https://cloud.githubusercontent.com/assets/2715000/17644132/c511c19a-61b0-11e6-9ec0-05e3c505b315.png)

Not sure if it's related to AWS's networking or the configuration of gRPC service.

**What you expected to happen**:

I can access the any node with the same port and return the same data.

**Comment by luxas** [comment]
@justinsb

**Comment by justinsb** [comment]
So from node 246 you can reach node 245 but not node 247?

How did you install kubernetes?

**Comment by tobegit3hub** [comment]
Yes and any other other web services work.

We install kubernetes with the scripts from Ubuntu Provider and start with `./cluster/kube-up.sh`.

**Comment by justinsb** [comment]
Hmmm.... if you're using flannel, sounds like a flannel bug, or a bug with the ubuntu provider.  I don't maintain either, I'm afraid :-(

You might try verifying that the problem persists with kops or standard AWS kube-up - if it does it'll be much easier for me to diagnose the issue.

**Comment by tobegit3hub** [comment]
Thanks @justinsb . I will create the example grpc container and processes to reproduce this issue.

**Comment by tobegit3hub** [comment]
It's easy to reproduce in existing Kubernetes cluster or new Kubernetes cluster. Follow the the [doc](https://github.com/kubernetes/kubernetes/tree/master/cluster/ubuntu) to setup multiple nodes of Kubernetes in Ubuntu 14.04. The default network component is `Flannel` and you can start `SkyDNS` addon.

Now we create the `NodePort` service with the port `30300` for [grpc-helloworld](https://github.com/tobegit3hub/grpc-helloworld) server.

```
apiVersion: v1
kind: Service
metadata:
  name: grpc-helloworld
  labels:
    app: grpc-helloworld
spec:
  type: NodePort
  ports:
  - name: grpc-helloworld
    port: 50051
    targetPort: 50051
    nodePort: 30300
  selector:
    app: grpc-helloworld
```

Then create the `Deployment` of `grpc-helloworld` server.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-helloworld
    spec:
      containers:
      - name: grpc-helloworld
        image: tobegit3hub/grpc-helloworld
        ports:
        - containerPort: 50051
```

In order to test the gRPC service, we run the gRPC client locally and try to connect with the server with kubelet's IP and `NodePort`. In my test environment, there're only two kubelet so I test with these two IPs.

```
docker run -d --net=host grpc-helloworld /greeter_client.py 10.69.1.246:30300
docker run -d --net=host grpc-helloworld /greeter_client.py 10.69.1.245:30300
```

If the pod locates in `10.69.1.246`, the first container will get "Hello, you!" normally.

![screen shot 2016-08-16 at 16 13 19](https://cloud.githubusercontent.com/assets/2715000/17692455/6b6bffca-63cc-11e6-8bff-cb04aead8034.png)

And the second container will get the error.

![screen shot 2016-08-16 at 16 13 01](https://cloud.githubusercontent.com/assets/2715000/17692459/7178da64-63cc-11e6-95cf-8fa3b45cad7f.png)
