### ISSUE TITLE
How can I specify ReclaimPolicy for dynamically provisioning volumes

### ISSUE THREAD

**Issue by mqliang** [kubernetes/kubernetes#30606]
@jsafrane 

I use a PVC with a "volume.alpha.kubernetes.io/storage-class" annotation to let k8s dynamically provision a PV. However, kubernetes will set the "persistentVolumeReclaimPolicy" as "Delete", see https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/controller.go#L1210

However, I want to specify the reclaim policy as "Retain" so that I could retain the PV when I delete then PVC and manually reclaim it. 

Is there any plan to support this feature?

cc @ddysher

**Comment by mqliang** [comment]
How about add a "volume.alpha.kubernetes.io/storage-reclaimPolicy" annotation in PVC, and persistentvolume_controller will set the reclaim policy of the provisioning PV according to the "volume.alpha.kubernetes.io/storage-reclaimPolicy" annotation?

If this proposal looks good, I am glad to send a PR to address this

**Comment by jsafrane** [comment]
@mqliang, dynamic provisioning is going through massive overhaul in 1.4 and we will support configurable storage classes (or profiles or policies or whatever term will be used in the end).

Adding this feature there is quite easy, however we have more pressing issues right now. While this dynamic provisioning stabilizes, do you have more high-level use case for this? Is reclaim policy something that should be common to a group of PVCs (or even a site policy) or is it something that each PVC author decides individually for each PVC?

**Comment by ddysher** [comment]
In our case, volume consumer decides individually for each PVC.  However, I think the default works for us right now as we kinda bind the lifecycle of a PV and PVC together.  User won't notice the creation and deletion of PV, all he cares about is a PVC.  So if retain PV if needed, just dont delete PVC.

**Comment by jsafrane** [comment]
@speedplane: it *is* maintained as long as you don't delete the PVC. Reclaim policy is executed *only* if kuberenetes sees a PV that was bound to a PVC and the PVC does not exist.

**Comment by speedplane** [comment]
@jsafrane okay, got it. So just have to be careful with the PVCs, deleting one is like deleting all the data on the disk.

**Comment by whitecolor** [comment]
So is it possible to force particular policy on created PV via PVC configuration?

**Comment by JacobJakub** [comment]
:+1:

**Comment by giovannicandido** [comment]
This can be done, but it would be nice with the dynamically provisioning as requested.
Work around is to create the pv and bound to pvc manually:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  volumeMode: Filesystem
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  csi:
    driver: csi.hetzner.cloud
    fsType: ext4
    volumeHandle: "1642794"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes
  volumeName: pv-demo
---
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: csi-pvc
```
