### ISSUE TITLE
FeatureRequest : GitRepo Mount Additional Configuration

### ISSUE THREAD

**Issue by iceandroidph** [kubernetes/kubernetes#30660]
Some project cannot afford to have one repository per each small feature. 

So it would be very nice if on the Volume type parameters/argument to allow to specify folder/s or file type to include, so it won't have to mount the entire repo with unnecessary data.

i.e. 

```
volumes:
  -name: some-volume
    gitRepo:
      repository: "https://github.com/some_name/repo.git"
      regex: "some_filter_*.properties"
      directory: "configuration/templates"
```
