### ISSUE TITLE
feature request: dynamic labels for pods

### ISSUE THREAD

**Issue by kayrus** [kubernetes/kubernetes#30755]
According to petset implementation, pods could be generated with dynamic names, etc. Does it worth to create extra labels for these pods according to some specific data? I.e.:

* configmap
* fieldRefs
* etc...

I already have a clue how to implement that, but would like to get some critics from dev community.

**Comment by kayrus** [comment]
Just to clarify. My goal is to make petsets to look like [systemd template](https://fedoramagazine.org/systemd-template-unit-files/) unit files. I.e.

When you spawn `petset@red`, petset will create petset-red pod.

At the moment petset can spawn petsets only by indexes, i.e. petset-0, petset-1, petset-2. What If you would like to remove only `petset-1`? You can not do this, becasue scheduler will spawn it from the scratch.

And petset template inside should have possibility to use this instance name inside the template.

I.e. if you wish to create a pod with the name "petset-${instance}-v3", and use a label selector which will also use ${instance}, i.e.

```yaml
selector:
  matchLabels:
    component: petset-${instance}-v3
  matchExpressions:
    - {key: tier, operator: In, values: [cache-${instance}]}
    - {key: environment, operator: NotIn, values: [dev]}
```

I know that it could be done within templates (bash, go templates, jinja2, etc.) but it would be great if a regular app could request Kubernetes through API just to spawn a petset with specific instance name without generating templates.
