### ISSUE TITLE
Find a way to pass a secret to dynamic provisioner

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#30897]
Currently, StorageClass contains `map[string]string` with configuration for dynamic provisioning. These parameters are passed to volume plugin to provisioning a volume. Some provisioners (e.g. Gluster) need also username and password in order to access the remote storage appliance and provision something.

It's undesirable to have a password in clear text in StorageClass and we should find a way how to pass a reference to Secret there.

Couple of thought discussed on SIG-storage call:
- Add Secret referece to StorageClass API object and passing it through all the controllers to volume plugins seems like the most clean way.
- Secrets are namespaced, while StorageClass is not.
  - It is undesirable to take the secret from a namespace where the provisioned PVC comes from - it would show the password to all users in that namespace. 
  - Should there be a special namespace for these secrets?

@kubernetes/sig-storage

**Comment by rootfs** [comment]
As implemented in #30959 for RBD storage class, Ceph key is placed in a Secret. The Secret's name and namespace need to be set in the storage class's parameter, illustrated below:

```yaml
apiVersion: extensions/v1beta1
kind: StorageClass
metadata:
   name: slow
provisioner: kubernetes.io/rbd
parameters:
    monitors: 10.16.153.105:6789
    adminID: admin
    adminSecretName: ceph-secret-admin
    adminSecretNamespace: kube-system
    pool: kube
    userId: kube
    secretName: ceph-secret-user
```
