### ISSUE TITLE
Feature Request: Allow RBAC Roles to have permissions in other namespaces

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#30924]
I have 2 namespaces, `["myapp", "default"]`. I created a “myapp” deployment and a “myapp” service in the “myapp” namespace.  (I’m using RBAC and its awesome)

I have Jenkins workers running in the “default” namespace, and I’d like to assign a `ServiceAccount` to Jenkins that has permissions to modify deployments in the "myapp" namespace

Here’s my current `ServiceAccount`, `Role`, and `RoleBinding`.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  namespace: myapp
  name: jenkins-deployer
rules:
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["*"]
  nonResourceURLs: ["/version"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: deploy-myapp
  namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: default
roleRef:
  kind: Role
  namespace: myapp
  name: jenkins-deployer
  apiVersion: rbac.authorization.k8s.io/v1alpha1
```

When I try to use the secret on the "jenkins-deployer” ServiceAccount to just get deployments in the “myapp” namespace, I get `Forbidden`

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4+dd6b458", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"not a git tree", BuildDate:"2016-08-04T09:44:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS EC2
- **OS** (e.g. from /etc/os-release):
```
NAME=CoreOS
ID=coreos
VERSION=1068.9.0
VERSION_ID=1068.9.0
BUILD_ID=2016-08-05-0455
PRETTY_NAME="CoreOS 1068.9.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
- **Kernel** (e.g. `uname -a`): 
```
Linux ip-172-31-34-166.us-west-2.compute.internal 4.6.3-coreos #2 SMP Fri Aug 5 04:51:16 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
```

**How to reproduce it** (as minimally and precisely as possible):
run `kubectl create -f` on this file

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: myapp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      name: myapp
    spec:
      containers:
      - name: web
        image: "nginx:latest"
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  namespace: myapp
  name: jenkins-deployer
rules:
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["*"]
  nonResourceURLs: ["/version"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: deploy-myapp
  namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: default
roleRef:
  kind: Role
  namespace: myapp
  name: jenkins-deployer
  apiVersion: rbac.authorization.k8s.io/v1alpha1
```

**What happened**:
To test the above scenario, I ran
```bash
JENKINS_SECRET_NAME=$(kubectl get sa jenkins-deployer -o json  | jq -r .secrets[0].name)
JENKINS_TOKEN=$(kubectl get secret ${JENKINS_SECRET_NAME} -o json |jq -r .data.token |base64 -D)

curl -H "Authorization: Bearer $JENKINS_TOKEN" \
    https://kubernetes.io/apis/extensions/v1beta1/namespaces/myapp/deployments/myapp \
    -vvv
```
and the reply was
```
Forbidden: "/apis/extensions/v1beta1/namespaces/myapp/deployments/myapp"
```

**What you expected to happen**:
I expected that my role could access the resource in the other namespace

**Anything else do we need to know**:
I understand that I could use a `ClusterRole`, but that would give permissions across _all_ namespaces, and that is not what I want. The `default` role in the default namespace, has permission to get anything in any namespace, and I'd just like to dial that down.

**Comment by ericchiang** [comment]
> I understand that I could use a ClusterRole, but that would give permissions across all namespaces, and that is not what I want. The default role in the default namespace, has permission to get anything in any namespace, and I'd just like to dial that down.

ClusterRoles only describe a role which can be reused across namespaces. It doesn't grant any permissions without a binding.   If you use a cluster role and two (non-cluster) role bindings you accomplish your goal. I believe the following rule setup does exactly what you're describing:

```yaml
kind: Cluster
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: jenkins-deployer
rules:
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["*"]
  nonResourceURLs: ["/version"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: deploy-myapp
  namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: default
roleRef:
  kind: ClusterRole
  name: jenkins-deployer
  apiVersion: rbac.authorization.k8s.io/v1alpha1
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: deploy-myapp
  namespace: myapp
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: default
roleRef:
  kind: ClusterRole
  name: jenkins-deployer
  apiVersion: rbac.authorization.k8s.io/v1alpha1
```

**Comment by micahhausler** [comment]
That did it! I actually only needed the second RoleBinding. Thanks!

**Comment by dhawal55** [comment]
I can't get this to work.

Here's my ClusterRole:
```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: admin-access
rules:
- apiGroups:
  - '*'
  attributeRestrictions: null
  nonResourceURLs:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
```

And roleBinding:
```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: RoleBinding
metadata:
  name: admin-access
  namespace: kube-system
roleRef:
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  kind: ClusterRole
  name: admin-access
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
```

Error i get from my pod in kube-system namespace:
`Invalid Kubernetes API v1 endpoint https://25.0.0.1:443/api: 403 Forbidden`

## Kubernetes Version
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.2", GitCommit:"9bafa3400a77c14ee50782bb05f9efc5c91b3185", GitTreeState:"clean", BuildDate:"2016-07-17T18:30:39Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```
