### ISSUE TITLE
error: yaml: line 2: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by chen0031** [kubernetes/kubernetes#30961]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
## kubectl       yaml    mapping values are not allowed in this context

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
v1.2

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
  CentOS 7
- **Kernel** (e.g. `uname -a`):
  3.10
- **Install tools**:
  yum install 
- **Others**:

**What happened**:
When I execute kubectl create -f X.yaml or kubectl get nodes, I get "error: yaml: line 2: mapping values are not allowed in this context".  This is a serious problem. I cannot use kubernetes to manage my cluster.

**What you expected to happen**:
Who can help me to repair this problem.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by AdoHe** [comment]
@chen0031 would you mind pasting the full yam document here?

**Comment by errordeveloper** [comment]
> After I finished the installation according to the guide...

It'd also help if you could specify which guide are referring to.

**Comment by bluecmd** [comment]
When I gave kubectl a malformed YAML I received this error. I would argue the bug here is to make the error message more clear when using multiple YAMLs in the same file. The line number above refers to the start of the current section ('---' delimited YAMLs) which is quite confusing if you have many configs in the same file.

Example (purposely malformed Deployment):
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-config
data:
  conf: |
      foobar

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  template:
    metadata:
      name: test
        labels:
          app: test
```

Output:
```
$ kubectl create -f test.yaml 
configmap "test-config" created
yaml: line 9: mapping values are not allowed in this context
```

Note: The error is actually on line 19 in the total file. Line 9 is the offset from `---`.

**Comment by fabiand** [comment]
Seeing this one as well with
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-18T10:52:03Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by fabiand** [comment]
Okay - issue with my yaml was that the value of a key was invlaid.

**Comment by ehernandez-xk** [comment]
same error following this basic example of a pod

```yaml
apiVersion: v1
kind: Pod
metadata:
 name: rss-site
 labels:
   app: web
spec:
 containers:
  – name: front-end
    image: nginx
    ports:
      – containerPort: 80
  – name: rss-reader
    image: nickchase/rss-php-nginx:v1
    ports:
      – containerPort: 88
```

```
kubectl create -f pod.yaml 
error: error converting YAML to JSON: yaml: line 9: mapping values are not allowed in this context
```

**Comment by Martlark** [comment]
This error for me was caused by use of an em-dash instead of a dash from a downloaded yml sample.

**Comment by adohe** [comment]
@fabiand @Martlark generally the YAML configuration file should be valid, and kubectl will try to provide more clear error message.

**Comment by spiffxp** [comment]
/sig cli
/sig api-machinery
do we have enough info to provider smarter error messages in this context?

**Comment by aba182** [comment]
Those who find themselves with this I hit same error due to a rouge colon. Basically you busted your config and system can't tell what is actually wrong.

**Comment by dims** [comment]
we should see if we can throw better error messages since we forked ghodss/yaml into sigs.k8s.io/yaml ( cc @neolit123 )

**Comment by neolit123** [comment]
>Note: The error is actually on line 19 in the total file. Line 9 is the offset from ---.

this might be a bit tricky.

/assign
/remore-lifecycle rotten

**Comment by Codesleuth** [comment]
Useful to try it out with
```
helm install --debug --dry-run ./mychart
```
Then at least you can visually see the line and the issue (it prints the YAML).

See also: https://docs.helm.sh/chart_template_guide/#debugging-templates

**Comment by silentbang** [comment]
> This error for me was caused by use of an em-dash instead of a dash from a downloaded yml sample.

For me, it's because of an unset environment variable which caused empty string for docker image tag. When validating yml against an online tool, it complained about no value after the colon.

**Comment by smaslennikov** [comment]
I got this error for improper tabbing:

**Wrong**:
```
env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws
          key: AWS_ACCESS_KEY_ID
```

**Correct**:
```
env:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws
        key: AWS_ACCESS_KEY_ID
```

**Comment by ashishb** [comment]
Thanks @smaslennikov

**Comment by spuder** [comment]
For others running into this issue, `mapping values are not allowed in this context` likely means that the yaml isn't valid. 
The following appears to be valid yaml in every linter I've tried, but still fails in kubernetes (notice the 4 dashes instead of the typical 3)

```
----                <---- sneaky dash breaks kubernetes
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny
  namespace: default
spec:
  podSelector:
    matchLabels: {}
```


```
helm lint foo
==> Linting foo/
[ERROR] templates/networkpolicy.yaml: unable to parse YAML
	error converting YAML to JSON: yaml: line 1: mapping values are not allowed in this context
```
