### ISSUE TITLE
How to delete probe for a container

### ISSUE THREAD

**Issue by workhardcc** [kubernetes/kubernetes#30991]
Define a deployment like below(part of config yaml):

```
containers:
      - name: mofang-web
        image: hello/docker/mofang-web:stable
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 0.5
            memory: 4294967296
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
```

I can modify the livenessProbe's config by PATCH the  API:/apis/extensions/v1beta1/namespaces/{namespace}/deployments/{name}, but how can I remove it?
