### ISSUE TITLE
Condition restartPolicy on exit code

### ISSUE THREAD

**Issue by colhom** [kubernetes/kubernetes#31147]
It would be nice&trade; to be able to specify which container exit codes should elicit a retry attempt.

Perhaps something like this:

``` yaml
spec:
  containers: ....
  restartPolicy: OnExitCode
  recoverableExitCodes:
    - 2
    - 4 
```

This would mean a failed container will not be restarted **unless** it exited with code `2` or `4`. 

\cc @xiang90
