### ISSUE TITLE
Daemonsets silently fail if resources are insufficent

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#31369]
When working with a daemonset, there were sufficient CPU resources to run it on all the nodes, but not on the master.  But there was no indication that this was the case (AFAICT), other than the fact that the number of pods was one short.

Status was:

```
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberMisscheduled: 0
```

(but there were 3 nodes - the master & two nodes.  The master was marked as `Ready,SchedulingDisabled`, so maybe we are miscounting in that case?)

Thanks to @adiri for working with me on this!
