### ISSUE TITLE
Strange decoding error when creating secret with kubectl

### ISSUE THREAD

**Issue by Markbnj** [kubernetes/kubernetes#31548]
This seems like a strange sequence of events. I am attempting to create secrets in our cluster to contain database user passwords. The passwords are generated each time a secret is created. This worked great for 'root'.

```
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-root-secret
type: Opaque
data:
  password: [32 chars of stuff]
  username: root

secret "mysqldb-root-secret" created
```

These definitions are being specialized and then piped to 'kubectl create -f -', so I will just show the definition yaml and the result.

I then tried creating one for a user with a longer name, used in one of our services. Let's call him 'billy'.

```
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-billysservice-secret
type: Opaque
data:
  password: b64377d7043139fc99ddb8a693f9a709
  username: billy

unable to decode "STDIN": [pos 91]: json: error decoding base64 binary 'billy': illegal base64 data at input byte 4
```

So I thought perhaps if we call him 'bill'?

```
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-paymentservice-secret
type: Opaque
data:
  password: 6120fcf7640f052861fcac52087a0c72
  username: bill

secret "mysqldb-paymentservice-secret" created
```

It likes 'bill'. Would it also like 'bil'?

```
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-paymentservice-secret
type: Opaque
data:
  password: a1a6d51971227fe0a592c5da881954fe
  username: bil

unable to decode "STDIN": [pos 89]: json: error decoding base64 binary 'bil': illegal base64 data at input byte 0
```

Nope. In reality the name I want is even longer than "billy" and I don't want to change it. Am I doing something wrong here?

**Comment by Markbnj** [comment]
Closing this as I misunderstood the requirement to base64 encode data items when using the declarative method for creating a secret.

**Comment by alouane** [comment]
hi there
I'm having the same problem here, can you point me out how did you get the issue fixed
Thanks

**Comment by maxandron** [comment]
Same for me.. I get this: `error: unable to decode "STDIN": [pos 228]: json: expect char '"' but got char '8'`

**Comment by ingcsmoreno** [comment]
@alouane check section "Creating a Secret Manually" here: https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually

**Comment by nickyfoster** [comment]
I had the same issue.
I was using ansible to generate secret.

Adding `b64encode` fixed this problem for me.

```
kind: Secret
apiVersion: v1
metadata:
  name: "{{ app.name }}"
type: Opaque
data:
{% for k, v in app.secrets.items() %}
  {{ k }}: >-
    {{ v | b64encode }}
{% endfor %}
```

**Comment by danielmotaleite** [comment]
so basically, the secret with data need to be already base64 encoded

```

kind: Secret
apiVersion: v1
metadata:
  name: "{{ app.name }}"
type: Opaque
data:
  password: {{ app.password | b64enc }}
```

while stringData should NOT be base64 encoded

```
kind: Secret
apiVersion: v1
metadata:
  name: "{{ app.name }}"
type: Opaque
stringData:
  password: {{ app.password }}
```

If the data is not base64 encoded, it will return this error.
some examples in some webpages are either wrong (using data secret without base64) or people end  mixing data and stringData examples, ending in this issue


hope this helps random helm users! :D
