### ISSUE TITLE
Cannot access webapp inside kubernetes deployment

### ISSUE THREAD

**Issue by kanebryant** [kubernetes/kubernetes#31643]
This might be a config issue but I have trawled through the documentation and its not very clear.

When I add my docker container to kubernetes as a container you can edit it to expose a public to private port mapping and the app works great.

However when I deploy the same docker image as a kubernetes deployment using a yaml deployment file, everything deploys fine and starts up but I am unable to access the application? The only difference I can see is that when inside the pod there are no port mapping details. When deploying as a pod are we supposed to expose the pod as a service?? Below is my yaml deployment file am I missing anything? --validate didn't report anything

``` yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: currency-conversion-xe-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: currency-conversion-xe
    spec:
      containers:
      - name: currency-conversion-xe
        image: cdiregistry.test.austrac.gov.au:5000/library/currency-conversion-xe:0.4
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: goagent1.test.austrac.gov.au
```

Further to my issue I have now created a service to expose the pod with an external ip address however I still am unable to hit the tomcat docker container which shows as being started in the logs, I believe the underlying issue is the lack of port mappings between the kubernetes container / pod and the docker container. Plus its not configurable through Rancher like a container is. Any help would be greatly apprectiated.
