### ISSUE TITLE
storage class for glusterfs  should not use plaintext password

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#31871]
Current provisioner for GlusterFS needs a plaintext password in `StorageClass.Parameters`:

```yaml
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/glusterfs
parameters:
  endpoint: "glusterfs-cluster"
  resturl: "http://127.0.0.1:8081"
  restauthenabled: "true"
  restuser: "admin"
  restuserkey: "password"
```

There should be a secret to hold the password.

In addition, as agreed in #30897, the configuration parameters from StorageClass should be stored in provisioned  PVs as annotations, so the class can be modified/deleted without blocking deletion of dynamically provisioned volumes.

 Proposing P1: This is a new API in 1.4, it would be better to fix it before we release it.
