### ISSUE TITLE
Failed to create a kubernetes client: invalid configuration: no configuration has been provided

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#31910]
From PR #31894

Working on the addon kube-dns, but found the lastest kube-dns program failed to start with below error:
`F0901 17:39:14.914386       1 server.go:55] Failed to create a kubernetes client: invalid configuration: no configuration has been provided`

After a bit exploration, found this commit 06cbb29e9e9b10c371347d2457ff8708f4a9e9f5

kube-dns works after revert this patch.

@smarterclayton @thockin @girishkalele

**Comment by MrHohn** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
Thank you for noticing this. This is a hole in our testing, we don't test all our addons by building them at head.

Rolling back the PR may not be the best fix. @smarterclayton may have an idea.

**Comment by girishkalele** [comment]
We cannot build kube-dns from latest master because of this issue - it fails to pick up the service account from inside the pod.

**Comment by thockin** [comment]
After the 1.4 branch we should switch kube-dns to the versioned client.
Bug filed

**Comment by smarterclayton** [comment]
I don't think we should roll this back.  Why would kube-dns fail to start if it has in-cluster config which has both KUBERNETES_SERVICE_HOST and the alternative?  Is InClusterConfig broken too?

**Comment by smarterclayton** [comment]
InClusterConfig being broken would be a p0.  If it's not, then I'd recommend fixing this to not introduce the defaulting and use the correct load style to the flags.

**Comment by thockin** [comment]
Yeah, I missed this before - why do we care about localhost?

**Comment by smarterclayton** [comment]
Let me check whether this is how kube-dns is setting up the clientcmd loader, or whether in cluster config is broken.

**Comment by smarterclayton** [comment]
Yeah, in cluster config is broken (because we were relying on defaulting to bypass empty).  Instead we need to check against a known error type (IsEmptyConfig) and move down to in cluster setup.  And add tests so this can't regress in the future.

**Comment by smarterclayton** [comment]
@lavalamp do we build *any* image for e2e that has a kubectl in it?  That would be a sufficient e2e to guard.  I can add more unit tests but the e2e is probably a necessity.

**Comment by lavalamp** [comment]
I've been asking for us to build a consistent set of containers at head for
every e2e for over a year, but no one has done it.

**Comment by girishkalele** [comment]
Atleast for kube-dns, I filed an issue this week to build and run the kube-dns that exists in-tree.

#31739

**Comment by dims** [comment]
@lavalamp - Is there a issue i can find more details? ("build a consistent set of containers at head for every e2e")

**Comment by zag2art** [comment]
Is there any workaround for kube 1.4 to make kube-dns working?

**Comment by djsd123** [comment]
Hi @zag2art,
After a bit of trial and error, I found that the below worked.  All I've done essentially is bump the version of the container down as the current versions aren't considered misconfigured.  At least that's how I interpreted the above. 

```
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP:
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP


---


apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v20
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v20
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v20
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v20
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: kubedns
        image: gcr.io/google_containers/kubedns-amd64:1.7
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        livenessProbe:
          httpGet:
            path: /healthz-kubedns
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 5
        args:
        - --domain=cluster.local.
        - --dns-port=10053
        ports:
        - containerPort: 10053
          name: dns-local
          protocol: UDP
        - containerPort: 10053
          name: dns-tcp-local
          protocol: TCP
      - name: dnsmasq
        image: gcr.io/google_containers/kube-dnsmasq-amd64:1.3
        livenessProbe:
          httpGet:
            path: /healthz-dnsmasq
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - --cache-size=1000
        - --no-resolv
        - --server=127.0.0.1#10053
        - --log-facility=-
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      - name: healthz
        image: gcr.io/google_containers/exechealthz-amd64:1.2
        resources:
          limits:
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
        args:
        - --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null
        - --url=/healthz-dnsmasq
        - --cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1:10053 >/dev/null
        - --url=/healthz-kubedns
        - --port=8080
        - --quiet
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: Default
```
