### ISSUE TITLE
Init container not sharing volumes correctly

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#32094]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Kubernetes version** (use `kubectl version`):
latest master (commit: aee6d10b5770ff11f52ffc2750cde008b6a638ff)

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): default (GCI maybe?)
- **Kernel** (e.g. `uname -a`): default
- **Install tools**: kube-up.sh

**What happened**:
According to the [design](https://github.com/kubernetes/kubernetes/blob/385fb81407a561292460585afc556783dcd6eaf8/docs/proposals/container-init.md#design-points), containers (incl. init container) in the same pod should share volumes and init container would be run first to do initialization.

Now I have an init container that's supposed to initialize a dir "/var/lib/data/", and a normal container to use that. But when the normal container failed because of "/var/lib/data" wasn't initialized at all.

**How to reproduce it** (as minimally and precisely as possible):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-initc
  annotations:
    pod.alpha.kubernetes.io/init-containers: '[
      {
        "name": "initc",
        "image": "centos:centos7",
        "command": [
          "/bin/sh", "-c", "echo haha > haha.txt && cat haha.txt"
        ]
      }
    ]'
spec:
  restartPolicy: Never
  containers:
  - name: normc
    image: centos:centos7
    command:
    - /bin/sh
    - -c
    - "cat haha.txt; sleep 50"
```

**Comment by hongchaodeng** [comment]
cc @smarterclayton @xiang90

**Comment by euank** [comment]
I think this is working as intended; they share volumes, not mount namespaces.

A modified version of your example showing what I'm pretty sure is meant by "shared volumes":

```yaml
apiVersion: v1       
kind: Pod
metadata:
  name: test-initc
  annotations:
    pod.alpha.kubernetes.io/init-containers: '[
      {
        "name": "initc",
        "image": "busybox",
        "command": [
          "/bin/sh", "-c", "echo hello world > /data/hello_world && cat /data/hello_world"
        ],
        "volumeMounts":[{"name":"data","mountPath":"/data"}]
      }
    ]'
spec:
  restartPolicy: Never
  containers:
  - name: normc
    image: busybox
    command:
    - /bin/sh
    - -c
    - "cat /data/hello_world; sleep 50"
    volumeMounts:
    - name: data
      mountPath: /data

  volumes:
  - name: data
    emptyDir: {}
```

For that one, the same output appears in both container's logs.
