### ISSUE TITLE
Deep mount of ceph-fs volume returns "No such file or directory"

### ISSUE THREAD

**Issue by nvnobelen** [kubernetes/kubernetes#32167]
BUG REPORT

The following ceph-fs mount option works when used from the fstab:

10.240.0.13:6789:/somedeeppath/ /data/ ceph name=admin,secret=mySecret,noatime,_netdev 0 2

In kubernetes this however returns an error:

I0906 23:32:52.467789    3061 reconciler.go:254] MountVolume operation started for volume "kubernetes.io/cephfs/3a722450-748a-11e6-8758-42010af00005-event-data" (spec.Name: "event-data") to pod "3a722450-748a-11e6-8758-42010af00005" (UID: "3a722450-748a-11e6-8758-42010af00005"). 
E0906 23:32:52.500394    3061 mount_linux.go:110] Mount failed: exit status 2
Mounting arguments: 10.240.0.13:6789:/somedeeppath/:/ /var/lib/kubelet/pods/3a722450-748a-11e6-8758-42010af00005/volumes/kubernetes.io~cephfs/event-data ceph [name=admin,secretfile=/etc/ceph/admin.secret]
Output: mount error 2 = No such file or directory

**Kubernetes version**

Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:29:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- GCE

PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- **Kernel** 4.7.2
- **Install tools**: Ceph-fs-client tools 0.8 debian installed

**What happened**:
Mount fails due to incorrectly constructed path:

10.240.0.13:6789:/somedeeppath/**:/** /var/lib/kubelet/pods/3a722450-748a-11e6-8758-42010af00005/volumes/kubernetes.io~cephfs/event-data ceph [name=admin,secretfile=/etc/ceph/admin.secret]

Should read:

10.240.0.13:6789:/somedeeppath/ /var/lib/kubelet/pods/3a722450-748a-11e6-8758-42010af00005/volumes/kubernetes.io~cephfs/event-data ceph [name=admin,secretfile=/etc/ceph/admin.secret]

**What you expected to happen**:
The 10.240.0.13:6789:/somedeeppath/**:/** should not have the trailing **:/**, which results in an incorrect mount statement. The code for mounting ceph does not yet verify if the monitors entered actually contain the second **:**.

**How to reproduce it** (as minimally and precisely as possible):

Start a ceph cluster and run:

apiVersion: v1
kind: Pod
metadata:
  name: cephfs2
spec:
  containers:
  - name: cephfs-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - {yourCephNode}:6789:/somedeeppath/
      user: admin
      secretFile: "/etc/ceph/admin.secret"
      readOnly: false

Then look for the error line in the kubelet.log

**Anything else do we need to know**:

**Comment by asalkeld** [comment]
I believe you should be using the `path` attribute to specify the subdirectory not monitors.

something like this (not tested):
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cephfs2
spec:
  containers:
  - name: cephfs-rw
    image: kubernetes/pause
    volumeMounts:
      mountPath: "/mnt/cephfs"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - 10.0.0.23:6789
      path: "/somedeeppath"
      user: admin
      secretFile: "/etc/ceph/admin.secret"
      readOnly: false
```

See:  https://blog.lsd25.net/index.php/2016/02/19/cephfs-volume-support-for-kubernetes-part-2/
