### ISSUE TITLE
Cannot create StorageClass

### ISSUE THREAD

**Issue by adambom** [kubernetes/kubernetes#32225]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No, this is a bug report

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Searched for: "error validating data: couldn't find type: v1beta1.StorageClass"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0+2831379", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"not a git tree", BuildDate:"2016-07-05T15:40:13Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5+coreos.0", GitCommit:"d7a04b1c6044647f5919fadf3cecb9ee70c10fc5", GitTreeState:"clean", BuildDate:"2016-08-15T21:01:42Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Mac OSX 10.11.5
- **Kernel** (e.g. `uname -a`): Darwin Adams-MacBook-Pro.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
- **Install tools**:
- **Others**:

**What happened**: I want to create a StorageClass. I ran the following code:

```
kubectl create -f - <<EOF
kind: StorageClass
apiVersion: extensions/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  zone: us-east-1d
  iopsPerGB: "10"
EOF
```

And got the following error:
```
error validating "STDIN": error validating data: couldn't find type: v1beta1.StorageClass; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:
A StorageClass is created succesfully

**How to reproduce it** (as minimally and precisely as possible):
Run this:

```
kubectl create -f - <<EOF
kind: StorageClass
apiVersion: extensions/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  zone: us-east-1d
  iopsPerGB: "10"
EOF
```

**Anything else do we need to know**:

**Comment by johscheuer** [comment]
https://github.com/kubernetes/kubernetes/commit/6320dc6e73b8d2405618af4bc3acf8d51b7d0f63 moved `apiVersion: extensions/v1beta1` to `apiVersion: storage.k8s.io/v1beta1`

**Comment by adambom** [comment]
If this is a versioning issue, which version of Kubernetes will contain this feature? We should probably update the docs to make note of this as well.

**Comment by adambom** [comment]
This appears to mostly work under version 1.4.x-beta, but I'm experiencing a problem with creating a storageclass with `encrypted` set to true.

Example:

```
kubectl create -f - <<EOF
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: sc1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: sc1
  zone: us-west-2a
  encrypted: true
EOF
```

This fails with the error:
`Error from server: error when creating "STDIN": StorageClass in version "v1beta1" cannot be handled as a StorageClass: [pos 131]: json: expect char '"' but got char 't'`

It seems to me like it's trying to treat the boolean field as a string. When I supply `encrypted: "true"` instead, it succeeds, but persistent volumes created using this storage class are not encrypted (at least using AWS).

Updated version info:
```
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-beta.6", GitCommit:"a77bafdcb39e7a854f22ab73136ab7f0907293c0", GitTreeState:"clean", BuildDate:"2016-09-16T18:00:16Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-beta.6+coreos.0", GitCommit:"c2f7e403b8f5d7aba0f88b250db746ffc2708961", GitTreeState:"clean", BuildDate:"2016-09-16T22:03:16Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
