### ISSUE TITLE
Multi-hub selenium grid k8s service loose endpoints on node reboot

### ISSUE THREAD

**Issue by dev-e** [kubernetes/kubernetes#32289]
**Related to**: [https://github.com/kubernetes/kubernetes/blob/release-1.4/examples/selenium/README.md](url)

**Kubernetes version** (use `kubectl version`): v1.3.6+coreos.0

**Environment**:
- **Cloud provider or hardware configuration**: VMware
- **OS** (e.g. from /etc/os-release): CoreOS 1068.10.0
- **Kernel** (e.g. `uname -a`): 4.6.3-coreos x86_64 Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz GenuineIntel GNU/Linux
- **Tools**: SkyDNS

**What happened**:
Greetings! I have a 3-node k8s cluster with schedulable master and 2 worker nodes. On each node there is a Selenium hub that holds 4 Selenium Chrome nodes and 4 Selenium Firefox nodes. There are 3 services for each of Selenium hubs for connecting Selenium nodes and 1 headless service for all 3 Selenium hubs for loadbalancing selenium tests. There are some selenium tests that connect to arbitrary hub via headless server several time a minute. When any node is rebooted all 4 services loose their endpoints for a few minutes.

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-hub-node0 
  labels:
    app: selenium-hub-node0
    mode: prod
    version: v2.53.0
spec:
  replicas: 1
  selector:
    app: selenium-hub-node0
    mode: prod
  template:
    metadata:
      labels:
        app: selenium-hub-node0
        role: selenium-hub
        mode: prod
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub
        resources:
          limits:
            memory: 2000Mi
        ports:
          - containerPort: 4444 
        env:
          - name: GRID_UNREGISTER_IF_STILL_DOWN_AFTER
            value: "15000"
        livenessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 120
        readinessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
      nodeSelector:
        node: "0"
```

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-hub-node1
  labels:
    app: selenium-hub-node1
    mode: prod
    version: v2.53.0
spec:
  replicas: 1
  selector:
    app: selenium-hub-node1
    mode: prod
  template:
    metadata:
      labels:
        app: selenium-hub-node1
        role: selenium-hub
        mode: prod
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub 
        resources:
          limits:
            memory: 2000Mi
        ports:
          - containerPort: 4444 
        env:
          - name: GRID_UNREGISTER_IF_STILL_DOWN_AFTER
            value: "15000"
        livenessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 120
        readinessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
      nodeSelector:
        node: "1"
```

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-hub-node2
  labels:
    app: selenium-hub-node2
    mode: prod
    version: v2.53.0
spec:
  replicas: 1
  selector:
    app: selenium-hub-node2
    mode: prod
  template:
    metadata:
      labels:
        app: selenium-hub-node2
        role: selenium-hub
        mode: prod
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub
        resources:
          limits:
            memory: 2000Mi
        ports:
          - containerPort: 4444 
        env:
          - name: GRID_UNREGISTER_IF_STILL_DOWN_AFTER
            value: "15000"
        livenessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 120
        readinessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
      nodeSelector:
        node: "2"
```

``` yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app: selenium-hub-node0
  name: selenium-hub-node0
  namespace: default
spec:
  ports:
    - port: 4444
  selector:
    app: selenium-hub-node0
```

``` yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app: selenium-hub-node1
  name: selenium-hub-node1
  namespace: default
spec:
  ports:
    - port: 4444
  selector:
    app: selenium-hub-node1
```

``` yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app: selenium-hub-node2
  name: selenium-hub-node2
  namespace: default
spec:
  ports:
    - port: 4444
  selector:
    app: selenium-hub-node2
```

``` yaml
kind: Service
apiVersion: v1
metadata:
  labels:
    app: selenium-hub
  name: selenium-hub
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 4444
  selector:
    role: selenium-hub
    mode: prod
```

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-chrome-node0 
  labels:
    app: selenium-node-chrome-node0
    version: v2.53.0
spec:
  replicas: 4
  selector:
    app: selenium-node-chrome-node0
  template:
    metadata:
      labels:
        app: selenium-node-chrome-node0
    spec:
      containers:
      - name: selenium-node-chrome
        image: selenium/node-chrome-debug
        ports:
          - containerPort: 5900 
        env:
          - name: HUB_PORT_4444_TCP_ADDR 
            value: "selenium-hub-node0.default"
          - name: HUB_PORT_4444_TCP_PORT 
            value: "4444"
        resources:
          limits:
            memory: 1000Mi
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
          readOnly: false
      volumes:
      - hostPath:
          path: /dev/shm
        name: shm
```

And so on...
Before reboot:

``` bash
#kubectl describe service selenium-hub
Name:           selenium-hub
Namespace:      default
Labels:         app=selenium-hub
Selector:       mode=prod,role=selenium-hub
Type:           ClusterIP
IP:         None
Port:           <unset> 4444/TCP
Endpoints:      10.64.134.14:4444,10.64.204.20:4444,10.64.221.5:4444
Session Affinity:   None
No events.
```

``` bash
#kubectl describe service selenium-hub-node0
Name:           selenium-hub-node0
Namespace:      default
Labels:         app=selenium-hub-node0
Selector:       app=selenium-hub-node0
Type:           ClusterIP
IP:         10.64.0.191
Port:           <unset> 4444/TCP
Endpoints:      10.64.221.5:4444
Session Affinity:   None
No events.
```

After node1 reboot:

``` bash
#kubectl describe service selenium-hub
Name:           selenium-hub
Namespace:      default
Labels:         app=selenium-hub
Selector:       mode=prod,role=selenium-hub
Type:           ClusterIP
IP:         None
Port:           <unset> 4444/TCP
Endpoints:      
Session Affinity:   None
No events.
```

``` bash
#kubectl describe service selenium-hub-node0
Name:           selenium-hub-node0
Namespace:      default
Labels:         app=selenium-hub-node0
Selector:       app=selenium-hub-node0
Type:           ClusterIP
IP:         10.64.0.191
Port:           <unset> 4444/TCP
Endpoints:      
Session Affinity:   None
No events.
```

Selenium hub pods on node0 and node2 do not get down or are restarted in this case. Just respective services loose the endpoints.
**What you expected to happen**:
After node1 reboot only one endpoint (from `selenium-hub-node1`) should be removed from service `selenium-hub`. No endpoints should be removed from services `selenium-hub-node0` and `selenium-hub-node2`.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a few simple looped selenium tests on explained Selenium Grid configuration. Then reboot any node.
