### ISSUE TITLE
support for digital ocean volumes

### ISSUE THREAD

**Issue by gosuri** [kubernetes/kubernetes#32334]
I was wondering if there are any plans to support digital ocean volumes (similar to awsElasticBlockStore)? If not, are you open to pull requests for this feature?

**Comment by pouledodue** [comment]
any news on that? I need this

**Comment by wardviaene** [comment]
I was looking for this as well. Haven't found anything yet, so started writing a digitalocean cloud provider myself. It's stil WIP, but the driver itself can create/delete/attach volumes and list/filter droplets. The kubernetes volume code still needs to be written though. Code at https://github.com/wardviaene/kubernetes/tree/do-volume/pkg/cloudprovider/providers/digitalocean

**Comment by wardviaene** [comment]
Update: I finished writing a volume plugin for digitalocean. Attach/detach is working on my cluster. Looking for anyone willing to test this on their k8s digitalocean cluster. My branch is https://github.com/wardviaene/kubernetes/tree/do-volume

You can use the following spec in your pod yml:
```
    spec:
      containers:
      - name: k8s-demo
        image: yourimage
        volumeMounts:
        - mountPath: /myvol
          name: myvolume
        ports:
        - containerPort: 3000
      volumes:
      - name: myvolume
        digitaloceanVolume:
          volumeID: mykubvolume
          fsType: ext4
```

Where mykubvolume is the volume created in DigitalOcean in the same region.

Still waiting for an issue in the godo driver to be resolved, before I can submit a PR (https://github.com/digitalocean/godo/issues/102)
