### ISSUE TITLE
Service <> Endpoints mapping ports to external service not working

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#32412]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:29:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

On GKE, using Service, Endpoints and an external application:

Using the following Service and Endpoints:

``` yml

---
kind: Service
apiVersion: v1
metadata:
  name: vault
  namespace: development
spec:
  clusterIP: None
  ports:
  - targetPort: 32001
    port: 8200

---
kind: Endpoints
apiVersion: v1
metadata:
  name: vault
  namespace: development
subsets:
- addresses:
  - ip: 104.199.xx.yy
  ports:
  - port: 32001
```

This does not work:

``` shell
telnet vault 8200
Trying 104.199.xx.yy...
^C
```

But this does:

``` shell
telnet vault 32001
Trying 104.199.xx.yy...
Connected to vault.development.svc.cluster.local.
Escape character is '^]'.
```

I expected the service `port` to be mapped to `targetPort` before being sent to the external `Endpoint`. This does not happen.

According to the [documentation](http://kubernetes.io/docs/user-guide/services/#services-without-selectors) this should work.
