### ISSUE TITLE
Kubeletes NotReady because of lack of CNI plugin make cluster startup scripts fail.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#32478]
Noticeably often (#31513) startup of cluster in scalability suite (100) Nodes fail, because 2 Nodes don't have CNI plugins installed:

```
I0910 17:19:59.718154    3719 kubelet.go:2240] skipping pod synchronization - [could not locate kubenet required CNI plugins [bridge host-local loopback] at "/opt/cni/bin" or "/usr/libexec/kubernetes/kubelet-plugins/net/exec/"]
```

which in turn causes tests to fail.

cc @kubernetes/sig-cluster-lifecycle @kubernetes/goog-node @wojtek-t

**Comment by wojtek-t** [comment]
As @yujuhong noticed few days before, this is because startup script on a node finishes unsuccessfully - see https://github.com/kubernetes/kubernetes/issues/31215#issuecomment-244430989 for more details.

Node team already fixed it on their side, by setting Kubelet to non-ready state.

However, this bug is about fixing the source of those failures, which are basically incorrectly installing CNI plugins: see: https://github.com/kubernetes/kubernetes/issues/31215#issuecomment-244430989

**Comment by justinsb** [comment]
Root cause here is that Salt doesn't retry, right?  Is this just a configuration option for Salt?

**Comment by wojtek-t** [comment]
>
Root cause here is that Salt doesn't retry, right?

I didn't take a deeper look, but that's highly probable.

**Comment by gmarek** [comment]
That I don't know - do we have any Salt expert? @kubernetes/sig-cluster-lifecycle

**Comment by onorua** [comment]
AFAIK, Salt doesn't retry state by default, however it does have `onfail` [requisite definition](https://docs.saltstack.com/en/latest/ref/states/requisites.html#onfail): 
So, basically you can set another step to retry in case main state failed.

**Comment by wojtek-t** [comment]
If that's only a case of adding this ```onfail``` then it shouldn't be hard to do, and it may help with a bunch of our startup cluster issues... @mikedanese WDYT?

**Comment by gmarek** [comment]
IIUC we're moving to GCI Nodes soon, so I'm not sure it's worth fixing containervm now, but if it's super easy I'm all for it.

**Comment by mikedanese** [comment]
Does that require modifying every single salt statment? Can we just run https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/configure-vm.sh#L1028 in a retry loop if it's failing? I assume it's returning a non-zero exit code.

**Comment by mikedanese** [comment]
> IIUC we're moving to GCI Nodes soon, so I'm not sure it's worth fixing containervm now, but if it's super easy I'm all for it.

Agree, a quick and dirty fix is probably best here.

**Comment by davidopp** [comment]
@dchen1107 @yujuhong

**Comment by onorua** [comment]
@mikedanese theoretically you should be able to add one `onfail` state for every states you expect failure. Something like:
```
primary_state1:
  mount.mounted:
    - name: /mnt/share
    - device: 10.0.0.45:/share
    - fstype: nfs

primary_state2:
  mount.mounted:
    - name: /mnt/share
    - device: 10.0.0.46:/share
    - fstype: nfs

backup_state:
  mount.mounted:
    - name: /mnt/share
    - device: 192.168.40.34:/share
    - fstype: nfs
    - onfail:
      - mount: primary_state1
      - mount: primary_state2
```
In this case you can add one state for states file, with `onfail` with the list of all needed states with:
```
cmd.run:
  - name: salt-call state.highstate
  - onfail:
    - state1
    - state2
   ....
```
fast and dirty :)
