### ISSUE TITLE
Incorrect error message when labels & expressions are not matching for replica set

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#32534]
Using the following configuration for replica set:

```
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: wildfly-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wildfly-rs-pod
    matchExpressions:
      - {key: tier, operator: In, values: ["backend"]}
      - {key: environment, operator: NotIn, values: ["dev"]}
  template:
    metadata:
      labels:
        app: wildfly-rs-pod
    spec:
      containers:
      - name: wildfly
        image: jboss/wildfly
        ports:
        - containerPort: 8080
```

Creating the resource as:

```
kubectl.sh create -f wildfly-replicaset.yml 
```

This gives the error:

```
The ReplicaSet "wildfly-rs" is invalid.
spec.template.metadata.labels: Invalid value: {"app":"wildfly-rs-pod"}: `selector` does not match template `labels`
```

The resource does created successfully if `matchExpressions` fragment is removed.

The error message seems to indicate that `labels` are incorrect where as the `expressions` were not matching.
