### ISSUE TITLE
Scope restricts a quota doesn't track PVC requests.storage

### ISSUE THREAD

**Issue by qwang1** [kubernetes/kubernetes#32562]
**What keywords did you search in Kubernetes issues before filing this one?** :
scope, requests.storage

---

**FEATURE REQUEST**:
Could persistent volume claim storage become an element of Qos and is it necessary to support scope constraint in the future?

**Kubernetes version** (use `kubectl version`):
kubenetes v1.5.0-alpha.0.368+5512104d363813

**Environment**:
- **OS** (RHEL 7.2)
- **Kernel** (3.10.0-327.22.2.el7.x86_64)

**What happened**:
So far persistent volume claim storage requests are managed by quota, and quota can have an associated set of scopes like this:

A BestEffort scope restricts a quota to limit the following resources:
    pods

A Terminating, NotTerminating, and NotBestEffort scope restricts a quota to tracking the following resources:
    pods
    memory
    requests.memory
    limits.memory
    cpu
    requests.cpu
    limits.cpu

However, scope restricts a quota doesn't track PVC requests.storage. 

**What you expected to happen**:
Do we have a plan to support scope restricted quota tracks PVC requests.storage?

**How to reproduce it** (as minimally and precisely as possible):
Create a quota with any scopes and PVC requests.storage
```
# cat my-quota-1.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-quota-1
spec:
  hard:
    persistentvolumeclaims: "50"
    requests.storage: "2Gi"
  scopes:
  - NotTerminating

# ./kubectl create -f my-quota-1.yaml
The ResourceQuota "my-quota-1.yaml" is invalid: spec.scopes: Invalid value: ["NotTerminating"]: unsupported scope applied to resource
```
