### ISSUE TITLE
PersistentVolumeClaim are not working as expected

### ISSUE THREAD

**Issue by ltagliamonte** [kubernetes/kubernetes#32743]
I'm using a brand new cluster on google gke, that has kubernetes 1.3.6
I'm trying to build a cassandra cluster that uses google persistent disk.

I'm running each node of the cluster in a kubernetes deployment, once i start the second node of the cluster the scheduler start a creation/destroy loop that doesn't stabilise.

With 1 cassandra deployment+pv+pvc it works

To replicate the issue create a kubernetes cluster on gce with 2 nodes and create 2 persistent disks named cassandra-1 and cassandra-2 of 10Gi each, the run the following script:

```
#/bin/bash

WORKDIR=$(mktemp -d /tmp/XXXX)
NAMESPACE=test

cat <<- EOF > "${WORKDIR}/namespace.yaml"
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
EOF
kubectl create -f ${WORKDIR}/namespace.yaml

for i in 1 2
do
cat <<- EOF > "${WORKDIR}/pv-${i}.yaml"
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cassandra-pv-${i}
spec:
  capacity:
    storage: 10Gi # Dimension of the created volume
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: cassandra-${i} # GCE volume name
    fsType: ext4
EOF
kubectl create -f ${WORKDIR}/pv-${i}.yaml --namespace=${NAMESPACE}

cat <<- EOF > "${WORKDIR}/claim-${i}.yaml"
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cassandra-pvc-${i}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Dimension of the created volume
EOF
kubectl create -f ${WORKDIR}/claim-${i}.yaml --namespace=${NAMESPACE}


cat <<- EOF > "${WORKDIR}/cassandra-${i}.yaml"
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra-${i}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: cassandra
    spec:
      containers:
        - image: cassandra:2.1.13
          name: cassandra
          ports:
            - containerPort: 9042
              name: cql
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cassandra-pvc-${i}
EOF
kubectl create -f ${WORKDIR}/cassandra-${i}.yaml --namespace=${NAMESPACE}
done
```
following the get pods output:
```
NAME                           READY     STATUS        RESTARTS   AGE
cassandra-1-2841067423-01363   1/1       Terminating   0          2m
cassandra-1-2841067423-036yn   0/1       Terminating   0          45s
cassandra-1-2841067423-0gn1h   0/1       Terminating   0          1m
cassandra-1-2841067423-0lj69   0/1       Terminating   0          1m
cassandra-1-2841067423-0pv6b   0/1       Terminating   0          15s
cassandra-1-2841067423-1ufz0   0/1       Terminating   0          47s
cassandra-1-2841067423-38wv8   0/1       Terminating   0          2m
cassandra-1-2841067423-38zy9   0/1       Terminating   0          2m
cassandra-1-2841067423-43kwf   1/1       Terminating   0          1m
cassandra-1-2841067423-4bols   0/1       Terminating   0          27s
cassandra-1-2841067423-525wu   0/1       Terminating   0          38s
cassandra-1-2841067423-5lap5   0/1       Terminating   0          57s
cassandra-1-2841067423-5yehj   0/1       Terminating   0          25s
cassandra-1-2841067423-6ehg8   0/1       Terminating   0          1m
cassandra-1-2841067423-6iy1c   0/1       Terminating   0          59s
cassandra-1-2841067423-6q8fh   0/1       Terminating   0          1m
cassandra-1-2841067423-6v03r   0/1       Terminating   0          15s
cassandra-1-2841067423-737c5   0/1       Terminating   0          53s
cassandra-1-2841067423-76imp   0/1       Terminating   0          47s
cassandra-1-2841067423-7mdk5   0/1       Terminating   0          29s
cassandra-1-2841067423-7uv43   0/1       Terminating   0          1m
cassandra-1-2841067423-812kw   0/1       Terminating   0          26s
cassandra-1-2841067423-8rytc   0/1       Terminating   0          42s
cassandra-1-2841067423-9romw   0/1       Terminating   0          49s
cassandra-1-2841067423-9xtv4   0/1       Terminating   0          55s
cassandra-1-2841067423-a8eb6   0/1       Terminating   0          9s
cassandra-1-2841067423-abctd   0/1       Terminating   0          11s
cassandra-1-2841067423-afqom   1/1       Terminating   0          2m
cassandra-1-2841067423-afvbw   0/1       Terminating   0          1m
cassandra-1-2841067423-az5yv   0/1       Terminating   0          8s
cassandra-1-2841067423-b1n2k   0/1       Terminating   0          1m
cassandra-1-2841067423-bieln   0/1       Terminating   0          45s
cassandra-1-2841067423-bruql   0/1       Terminating   0          1m
cassandra-1-2841067423-bt19x   0/1       Terminating   0          1m
cassandra-1-2841067423-cdzhx   0/1       Terminating   0          12s
cassandra-1-2841067423-chafj   0/1       Terminating   0          5s
cassandra-1-2841067423-dkhhu   0/1       Terminating   0          1m
cassandra-1-2841067423-dsij9   0/1       Terminating   0          38s
cassandra-1-2841067423-dye9d   1/1       Terminating   0          2m
cassandra-1-2841067423-e8hiz   0/1       Terminating   0          16s
cassandra-1-2841067423-euu52   0/1       Terminating   0          20s
cassandra-1-2841067423-f150z   0/1       Terminating   0          17s
cassandra-1-2841067423-f2jh9   1/1       Terminating   0          2m
cassandra-1-2841067423-f56q4   1/1       Terminating   0          2m
cassandra-1-2841067423-f83f2   0/1       Terminating   0          6s
cassandra-1-2841067423-fe04v   0/1       Terminating   0          33s
cassandra-1-2841067423-fik6x   0/1       Terminating   0          41s
cassandra-1-2841067423-g18ay   0/1       Terminating   0          36s
cassandra-1-2841067423-g2aae   0/1       Terminating   0          58s
cassandra-1-2841067423-gokpb   0/1       Terminating   0          1m
cassandra-1-2841067423-gwnfv   0/1       Terminating   0          1m
cassandra-1-2841067423-hnuj6   0/1       Terminating   0          37s
cassandra-1-2841067423-i3adn   0/1       Terminating   0          49s
....
```
I'm attaching the kubectl logs of the minion nodes (archive.zip)

[Archive.zip](https://github.com/kubernetes/kubernetes/files/473660/Archive.zip)
