### ISSUE TITLE
Manual upgrade: No CA_CERT in metadata after upgrade on GCE

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#32812]
During a manual upgrade test, described in [this doc](https://docs.google.com/document/d/1yv9tm5qeCqbyw5SWysHaXxSLDRZ-RmK8QRBrkbnh6Tg/edit#), a kubelet failed to communicate via SSL to its master.  
This is currently blocking the 1.4 release.

There is not a repro for this yet.

The cluster was running 1.3, and was upgraded to 1.4 successfully, but upon downgrading to 1.3, the kubelets one one or more machines are not able to talk to the master.

Current kubelet version is `v1.4.0-beta.5`. (EDITED)

The error when talking to the master is (lots like this):
```
# journalctl -u kubelet | grep x509 | tail -1
Sep 15 19:04:35 kubernetes-minion-group-20m5 kubelet[1239]: E0915 19:04:35.106381    1239 reflector.go:203] pkg/kubelet/kubelet.go:406: Failed to list *api.Node: Get https://kubernetes-master/api/v1/nodes?fieldSelector=metadata.name%3Dkubernetes-minion-group-20m5&resourceVersion=0: x509: certificate signed by unknown authority
```

I think this means that the kubelet cannot verify the master's cert.  I can't find the master's cert.

Since there is not flag to kubelet to tell it where to find its config, I assume it is using the default location, which is `/var/lib/kubelet/kubeconfig`.

```
# cat /var/lib/kubelet/kubeconfig
apiVersion: v1
kind: Config
users:
- name: kubelet
  user:
    client-certificate-data: 
    client-key-data: 
clusters:
- name: local
  cluster:
    certificate-authority-data: 
contexts:
- context:
    cluster: local
    user: kubelet
  name: service-account-context
current-context: service-account-context
```
It seems wrong that clusters[0].cluster.certificate-authority-data is empty.  That should have the cert for the master, right?

I see this thing:
```
# cat /mnt/stateful_partition/home/kubernetes/kube-manifests/kubernetes/kubelet-config.yaml
apiVersion: v1
kind: Config
users:
- name: kubelet
  user:
    client-certificate-data: ${KUBELET_CERT}
    client-key-data: ${KUBELET_KEY}
clusters:
- name: local
  cluster:
    certificate-authority-data: ${CA_CERT}
contexts:
- context:
    cluster: local
    user: kubelet
  name: service-account-context
current-context: service-account-context
```
but I don't understand what process generates ` /var/lib/kubelet/kubeconfig`, and if, presumably, from that template, why it isn't setting the env var CA_CERT.
