### ISSUE TITLE
High churn from ReplicationController when Pod cannot schedule

### ISSUE THREAD

**Issue by timstclair** [kubernetes/kubernetes#32837]
If a Pod cannot be scheduled on any nodes (rejected by the kubelet), the ReplicationController will continuously recreate the pod trying to schedule it on every node. This causes very high churn & resource usage across the cluster.

For example, create a replication controller that creates a Pod with an AppArmor profile that is not loaded on any nodes (or if AppArmor is not enabled):

``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name:   pause
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pause
      annotations:
        container.apparmor.security.beta.kubernetes.io/pause: localhost/bad
    spec:
      containers:
        - name:    pause
          image: gcr.io/google_containers/pause
```

A (growing) number of reasons can cause a pod to be rejected, including resource shortage, security profiles not found, etc.

Potential solutions include:
- Exponential backoff for recreating rejected pods
- Exponential backoff for rescheduling rejected pods on the node that rejected them

@kubernetes/sig-cluster-lifecycle @kubernetes/sig-scheduling @dchen1107
