### ISSUE TITLE
Some ports in a PetSet exposed, others not

### ISSUE THREAD

**Issue by etotheipi** [kubernetes/kubernetes#32905]
Kubernetes version 1.3.6, vagrant cluster with three nodes (+master).

I have setup a PetSet and headless service for a Zookeeper ensemble.  DNS resolution works (i.e. `zookeeper-1.zookeeper-cluster`), and the pets appear to be able to talk to each other over the first port listed (2181).  However, get `Connection Refused` on the second and third port listed (2888, 3888).  I minimally modified the configuration file used in the docker image to run it locally and it works without issue.  As far as I can tell port 2888 and 3888 is not exposed despite the docker image `EXPOSE`ing all three, and the `Service` and `PetSet` definitions declaring them.

Here's the error:

```
2016-09-16 21:21:25,729 [myid:1] - INFO  [QuorumPeer[myid=1]/0:0:0:0:0:0:0:0:2181:QuorumPeer$QuorumServer@149] - Resolved hostname: zookeeper-1.zookeeper-cluster to address: zookeeper-1.zookeeper-cluster/10.246.7.2
2016-09-16 21:21:25,733 [myid:1] - WARN  [QuorumPeer[myid=1]/0:0:0:0:0:0:0:0:2181:QuorumCnxManager@400] - Cannot open channel to 3 at election address zookeeper-2.zookeeper-cluster/10.246.76.3:3888
java.net.ConnectException: Connection refused
```

I confirmed that `telnet` can open connection to 2181, but not 2888 or 3888.

Dockerfile contains `EXPOSE 2181 2888 3888`.

K8s PetSet YAML:

```
apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
    type: petset
spec:
  serviceName: zookeeper-cluster
  replicas: 3
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: zookeeper
        type: node
    spec:
      containers:
        - name: zookeeper-node
          image: co.private.registry.io/zookeeper-petset
          ports:
            - name: client
              containerPort: 2181
            - name: follower
              containerPort: 2888
            - name: leader
              containerPort: 3888
```

The Service YAML:

```
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
  labels:
    app: zookeeper
    type: service
spec:
  clusterIP: None
  ports:
    - name: clientport
      port: 2181
    - name: followerport
      port: 2888
    - name: leaderport
      port: 3888
  selector:
    app: zookeeper
    type: node
```

I would think I did something wrong if all three ports failed to work, but it's only some of them.
