### ISSUE TITLE
Glusterfs doesn't create subPath

### ISSUE THREAD

**Issue by jonathan-kosgei** [kubernetes/kubernetes#32996]
I have 3 containers in a pod with the following mount points
```
        volumeMounts:
        - name: gluster
          mountPath: /ns/app
          subPath: {{app_id}}/app
```
```
        volumeMounts:
        - name: gluster
          mountPath: /ns/app
          subPath: {{app_id}}/app
```
```
        volumeMounts:
        - name: gluster
          mountPath: /home/git/data
          subPath: {{app_id}}/git
        volumeMounts:
        - name: gluster
          mountPath: /app
          subPath: {{app_id}}/app
      volumes:
      - name: gluster
        persistentVolumeClaim:
          claimName: glusterfs-claim
```

And the following pv & pvc : 
```
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
 name: {{name}}
 labels:
  name: {{name}}
spec:
 capacity:
  storage: 100M
 accessModes:
 - "ReadWriteMany"
 persistentVolumeReclaimPolicy: "Recycle"
 glusterfs:
  endpoints: "glusterfs-cluster"
  path: "gluster_vol-1"
  readOnly: false
```

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
  selector:
    matchLabels:
      name: {{name}}
```

The `{{app_id}}/git` subpath does not get created . I've reproduced this a few times and the only way I've been able to get `<>/git` to be created is by not mounting the second `/app` mount. If it's relevant the pod is in it's own namespace.

Oddly the following works, created in default:
```
apiVersion: v1
kind: Pod
metadata:
  name: glusterfs
spec:
  containers:
  - name: glusterfs
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/glusterfs"
      name: glusterfsvol
      subPath: here/app
    volumeMounts:
    - mountPath: "/glusterfs002"
      name: glusterfsvol
      subPath: here/app1
  - name: glusterfs002
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/glusterfs"
      name: glusterfsvol
      subPath: here/app
    volumeMounts:
    - mountPath: "/glusterfs002"
      name: glusterfsvol
      subPath: here/app102
  - name: glusterfs003
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/glusterfs"
      name: glusterfsvol
      subPath: here/app
    volumeMounts:
    - mountPath: "/glusterfs002"
      name: glusterfsvol
      subPath: here/app102
  volumes:
  - name: glusterfsvol
    persistentVolumeClaim:
      claimName: glusterfs-claim
```
The above works with the same pv & pvc

**Comment by jonathan-kosgei** [comment]
palm .. this worked
```
        volumeMounts:
          - name: gogs-gluster
            mountPath: /home/git/data
            subPath: "{{app_id}}/git"
          - name: gluster
            mountPath: /ns/app
            subPath: "{{app_id}}/app"
```
Odd though, that the dummy yaml above worked.
