### ISSUE TITLE
kube-DNS request/limits messes with tail latency

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#33027]
Long tail observed in normal case: 

``` console
$ for i in `seq 1 1000`; do dig @10.0.0.10
kubernetes.svc.cluster.local A | grep Query | cut -f2 -d: ; done |
sort -n | uniq -c

      4  0 msec
    930  1 msec
     29  2 msec
     11  3 msec
      1  4 msec
      4  5 msec
      1  6 msec
      2  7 msec
      1  9 msec
      1  10 msec
      1  13 msec
      1  15 msec
      1  22 msec
      1  29 msec
      2  44 msec
      1  48 msec
      1  51 msec
      1  65 msec
      1  68 msec
      2  72 msec
      2  73 msec
      1  76 msec
      1  83 msec
```

I tried a bunch of things like using hostNetwork and doing a lookup from 127.0.0.1, didn't help.

Then tried:
- drained the node (deleted all pods, cordoned the node) 
- removed dnsmasq from kube-dns yaml
- removed static pod manifests for fluentd, kube-proxy from /etc/kubernetes
- modified podTemplate spec like of kube-dns rc to 

``` yaml
    spec:
      containers:
      - args:
        - --domain=cluster.local.
        - --dns-port=53
        image: gcr.io/google_containers/kubedns-amd64:1.7
        imagePullPolicy: IfNotPresent
        name: kubedns
        ports:
        - containerPort: 53
          hostPort: 53
          name: dns-local
          protocol: UDP
        resources:
          requests:
            cpu: 200m
            memory: 70Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      nodeName: e2e-test-beeps-minion-group-oka0
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

basically kube-dns now has 1 box.

Observed much better latencies, at least in the handful of lookups I did: 

```
root@dnsutils2:/# for i in `seq 1 1000`; do dig @10.0.0.10 kubernetes.svc.cluster.local A | grep Query | cut -f2 -d: ; done | sort -n | uniq -c
    537  0 msec
    456  1 msec
      4  2 msec
      2  3 msec
      1  9 msec
```

Theories:
1. dnsmasq is cpu constrainted (it has 10m)
2. kube-dns is setting GOMAXPROCS to what it _thinks_ is num cores
3. one of the other components I removed from the node was hammering cpu 

We should try doing https://github.com/kubernetes/kubernetes/issues/29597#issuecomment-235469479
