### ISSUE TITLE
Services with clusterIP: None can be created with type LoadBalancer

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#33036]
Create the following svc:

```
apiVersion: v1
kind: Service
metadata:
  name: headful
spec:
  clusterIP: None
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    run: hostnames
```

It should fail.
