### ISSUE TITLE
PersistentVolumeClaims using NFS leave its PersistentVolume in the "Released" state after the PVC has been deleted

### ISSUE THREAD

**Issue by metral** [kubernetes/kubernetes#33102]
After a PVC has been deleted, its underlying PersistentVolume should be in the "Available" state and not in the "Released" state. If in "Released", then the PV is not usable by any other PVC's until the PV is deleted and a new one is created.

This is a dup of https://github.com/kubernetes/kubernetes/issues/27164 and #20753. My last issue  on this (https://github.com/kubernetes/kubernetes/issues/27164) was closed as it was believed to have been resolved in v1.3, however, I am still hitting this issue on k8s v1.3.5 with NFS + PVC's.

Here is my system's info:
```
Kubernetes OS: CoreOS 1010.5.0
Kubernetes kernel: 4.5.0-coreos-r1

NFS OS: Ubuntu 16.04
NFS kernel: 4.4.0-34-generic
NFS version: v4
```

There aren't any obvious issues that I can tell from the logs on any of the components, other than seeing a lot of these types of informational logs scattered throughout the kubelet:

```
reconciler.go:254] MountVolume operation started for volume "kubernetes.io/configmap/c203c7e0-7eff-11e6-b0c0-bc764e103445-my-config" (spec.Name: "my-config") to pod "c203c7e0-7eff-11e6-b0c0-bc764e103445" (UID: "c203c7e0-7eff-11e6-b0c0-bc764e103445"). Volume is already mounted to pod, but remount was requested.
```

**Comment by childsb** [comment]
Will you provide your PV and PVC yaml?

**Comment by metral** [comment]
PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/foobar
    server: <IP_ADDR>
```

PVC:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
```
