### ISSUE TITLE
Idea: "merge" volumes

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#33179]
A common problem we hear today is that people want to consume a Secret or ConfigMap as a file or files in a existing directory, without hiding the other files therein.  The semantics of volumeMounts today do not allow this by default, though it can be achieved using subPath, one volumeMount per file.  A downside to this approach is that the Secret and ConfigMap file(s) are not auto-updated because bind mounts bind to the inode, not the dentry.

An idea to solve this, though it's a little tricky.  Consider the case of wanting to project one Secret file and one ConfigMap file into /etc.

1) Define Secret and ConfigMap volumes as normal
2) volumeMount them onto /vol/secret and /vol/cfgmap
2) Create a new flavor of volumeMount that merges them

```
volumeMounts:
  - name: my-secret
    mountPath: /vol/secret
  - name: my-cfgmap
    mountPath: /vol/cfgmap
  - name: my-etc
    mountPath: /etc
    merge:
      - /vol/secret
      - /vol/cfgmap
```

Kubelet would recognize that no volume named "my-etc" exists (but I think that field is required), nbut the "merge" key does exist.  It would make a temp directory and bind mount everything from the container's /etc into the temp dir, one-by-one (with a limit, maybe 1024).  Then it would iterate /vol/secret, and symlink from /etc for every file.  Repeat for cfgmap.  Finally, bind mount that onto /etc.

Net result is that /etc/exists as it did before, but it includes symlinks to volume-projected files.

The tricky part of this is that it has to have access to the container's mounted and prepared rootfs before the container starts, which I don't think is possible yet.  Filing this for future opportunities.

@kubernetes/sig-storage
