### ISSUE TITLE
Private registry and connection refused

### ISSUE THREAD

**Issue by oglu** [kubernetes/kubernetes#33220]
I am trying to use a private registry with kubernetes with images named (e.g.) `private.registry.com/redis:3.0.3` . Configuration (.docker/config.json) is there and 

`docker run -t -i private.registry.com/redis:3.0.3 ` executes perfectly

I am assuming that somehow it tries to contact the registry at port 80 which is disabled. 

A sample pod definition is 

```
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: registry.private.com/redis:3.0.3
      imagePullPolicy: Always
```
