### ISSUE TITLE
GCI Test Failing: (kubernetes-gci-gce-alpha-features-release-1.4) ([k8s.io] PetSet [Slow] [Feature:PetSet] [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet] should creating a working mysql cluster [Feature:PetSet])

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#33315]
GCI Test Failing: (kubernetes-gci-gce-alpha-features-release-1.4) ([k8s.io] PetSet [Slow] [Feature:PetSet] [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet] should creating a working mysql cluster [Feature:PetSet])

https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features-release-1.4

**Comment by foxish** [comment]
This one, https://github.com/kubernetes/kubernetes/issues/33317 and https://github.com/kubernetes/kubernetes/issues/33316 appear to be failing because of the same reasons.
The files being written by the init containers don't have the right permissions perhaps? This is what I observed so far.

```
root@zoo-0:/work-dir# ls -altr
total 2936
-rwxr-xr-x 1 root root    4172 Sep 23 00:22 on-start.sh
drwxrwxrwx 2 root root    4096 Sep 23 00:22 .
-rwxr-xr-x 1 root root 2987890 Sep 23 00:22 peer-finder
drwxr-xr-x 1 root root    4096 Sep 23 00:22 ..

root@zoo-0:/work-dir# chmod +x on-start.sh 
root@zoo-0:/work-dir# ./on-start.sh
bash: ./on-start.sh: Permission denied

```

**Comment by foxish** [comment]
cc @erictune

**Comment by erictune** [comment]
👍 nice debug

**Comment by bprashanth** [comment]
Random tip, came across this looking for another bug. GCI broken emptydir because kubelet's root-dir is noexec. Petset is just a victim:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    foo: bar
spec:
  terminationGracePeriodSeconds: 0
  hostNetwork: true
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sh
      - -ec
      - |
        echo date > /tmp/foo/date.sh
        chmod -c 777 /tmp/foo/date.sh
        while true; do /tmp/foo/date.sh || true; sleep 1; done
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /tmp/foo
      name: test
  volumes:
  - name: test
    emptyDir: {}
  restartPolicy: Always
```
