### ISSUE TITLE
Didn't handle invalid permission mode: '0008' properly

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#33475]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): secret permission mode

**Kubernetes version** (use `kubectl version`):
v1.5.0-alpha.0.1251+e05e8664d5dd7a

**Environment**:
- **OS** (e.g. from /etc/os-release): Red Hat Enterprise Linux Server 7.2
- **Kernel** (e.g. `uname -a`): 3.10.0-327.22.2.el7.x86_64

**What happened**:
Didn't handle invalid permission mode: '0008' properly. I think we don't need to change to 0010 with octonary number in here. We should add limitation for these invalid value, such as 8 and 9. For reference, linux os doesn't allow user set "chmod 008" always.

**How to reproduce it** (as minimally and precisely as possible):
**1. Create a secret: `kubectl create -f secret.yaml`**

```
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  data-1: dmFsdWUtMQ0K
  data-2: dmFsdWUtMg0KDQo=
```

**2. Create a pod with specifying secret permission mode(0008): `kubectl create -f secret-permission-pod.yaml`**

```
apiVersion: v1
kind: Pod
metadata:
  name: secret-permission-pod
spec:
  containers:
  - name: secret-permission-pod
    image: redis
    volumeMounts:
    - name: foo-volume
      mountPath: "/etc/foo"
  volumes:
  - name: foo-volume
    secret:
      secretName: test-secret
      defaultMode: 8
```

**Actual results**:
Created succeful and set 0010 for files in secret volume.

```
# kc create -f secret-permission-pod.yaml
pod "secret-permission-pod" created
# kc get pod
NAME                    READY     STATUS    RESTARTS   AGE
secret-permission-pod   1/1       Running   0          19s
# kc exec -it secret-permission-pod sh
# ls -l /etc/foo/..data/
total 8
------x---. 1 root root  9 Sep 26 05:13 data-1
------x---. 1 root root 11 Sep 26 05:13 data-2
```

**Expected results**: 
Pod should be created failed with properly warnning info.

**Comment by rata** [comment]
@chengzhang1016 sorry, don't follow why you way it should fail. If you specify `8` in decimal mode, it is 010 in octal. And that permission is used.

It should fail if you specify `08`, that is not valid in octal. Right?

But to specify numbers in octal, you need to use a "0" before.

Am I missing something? If not, do you suggest any improvement to the doc?

**Comment by chengzhang1016** [comment]
@rata Thanks for your response.
I'm confusing. In my testing, all values in `8`, `08`, `008` and `0008` will be change to 0010 (`------x---`) in octal, and all will be created successful.

Furthermore, the reason why I think it should fail is that the behaviour is different with `chmod` command in Linux. User maybe have confusion in here. As we know, the valid value is [0-7][0-7][0-7] in Linux, in another word, we cannot `chmod` to 008 or 099.  
For example, all `8`, `08`, `008` and `0008` are not permitted in `chmod` in Linux.
```
# chmod 8 test.file
chmod: invalid mode: '8'
Try 'chmod --help' for more information.
# chmod 08 test.file
chmod: invalid mode: '08'
Try 'chmod --help' for more information.
# chmod 008 test.file
chmod: invalid mode: '008'
Try 'chmod --help' for more information.
# chmod 0008 test.file
chmod: invalid mode: '0008'
Try 'chmod --help' for more information.
```

**Comment by rata** [comment]
@chengzhang1016 will try to reproduce tomorrow. But I think probably the parser parse it that way and there is no way to validate that if we use a valid yaml/json parser. 

Also, chmod says it accepts only OCTAL-MODE for numberic ways, it is not the case of yaml/json nor our. In fact, the example uses decimal mode.

@chengzhang1016 why do you think it's nice to fail with "8" if it is stated that we accept in decimal? Also, even if we don't fail in 08 (because the parser is smart to detect this as decimal or something) why is that a problem?

I mean, if you use a proper number in octal, it works. If you use decimal, it works. And (let's say, but this is not what is in the test case reported) it works with `08` too, it considers it a decimal and works. I don't see why it is necessarily wrong. Can you please elaborate? Do you have something in mind?

**Comment by chengzhang1016** [comment]
@rata OKay. I see and thanks for your explanation. Do you think if we need to add some description in docs?

**Comment by rata** [comment]
On Sun, Oct 09, 2016 at 07:13:01PM -0700, Cheng Zhang wrote:
> @rata OKay. I see and thanks for your explanation.

But do you see it as a problem? Can you please elaborate? I'd really like to
know why :)


> Do you think if we need to add some description in docs?

Not sure, what confused you and how do you think it can be better explained?
Also, feel free to send a PR. But if you don't want, also please explain me some
more and I'll try to clarify it! :)


Thanks again!
Rodrigo

**Comment by chengzhang1016** [comment]
I understand the implement and your explanation. 
1. Use a proper number in octal, will not change and it works.
2. Use a decimal or a invalid octal, will change to proper octal and it works. 
That is fine. But, user maybe have confusion for below two things, I think we should add some explanation for that.
1. What happen while user set a decimal or a invalid octal (will change to a proper octal)
2. Why use decimal record in pod yaml/json file(kubectl get pod $pod_name -o yaml) although user set a proper octal number. (I know the reason, but user maybe have confusion.)
Such as:
User set `0400` for defaultMode
```
apiVersion: v1
kind: Pod
metadata:
  name: secret-permission-pod
spec:
  containers:
  - name: secret-permission-pod
    image: redis
    volumeMounts:
    - name: foo-volume
      mountPath: "/etc/foo"
  volumes:
  - name: foo-volume
    secret:
      secretName: test-secret
      defaultMode: 0400
```
Use decimal record in pod yaml
`kubectl get pod secret-permission-pod -o yaml`
```
...
  volumes:
  - name: foo-volume
    secret:
      defaultMode: 256
      secretName: test-secret
...
```
