### ISSUE TITLE
Pod with resource quota not getting created

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#33621]
Using Kubernetes 1.3.3, started cluster as:

```
NUM_NODES=2 NODE_SIZE=m3.medium KUBERNETES_PROVIDER=aws kube-up.sh
```

Creating a pod using the following configuration file:

```
apiVersion: v1
kind: Pod
metadata:
  name: wildfly-pod
  labels: 
    name: wildfly
spec: 
  containers: 
    - image: jboss/wildfly
      name: wildfly-pod
      resources:
        requests:
          memory: 1G
          cpu: 1
        limits:
          memory: 2G
          cpu: 2
```

`kubectl` shows the pod as:

```
kubectl.sh get -w pods
NAME          READY     STATUS    RESTARTS   AGE
wildfly-pod   0/1       Pending   0          2s
```

Creating the pod using the following configuration works:

```
apiVersion: v1
kind: Pod
metadata:
  name: wildfly-pod
  labels: 
    name: wildfly
spec: 
  containers: 
    - image: jboss/wildfly
      name: wildfly-pod
```

Examples quoted at http://kubernetes.io/docs/admin/resourcequota/walkthrough/ refer to the files at `docs/admin/resourcequota/object-counts.yaml` but https://github.com/kubernetes/kubernetes/tree/master/docs/admin/resourcequota does not have these files.
