### ISSUE TITLE
Better YAML validation error message for kubectl apply -f to indicate why it is invalid

### ISSUE THREAD

**Issue by ye** [kubernetes/kubernetes#33679]
**FEATURE REQUEST**

Scratching my head on this error message today for quite a while now:

``` bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:15:30Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:08:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl apply -f /tmp/celery.yaml 
proto: no encoder for TypeMeta unversioned.TypeMeta [GetProperties]
proto: tag has too few fields: "-"
proto: no coders for struct *reflect.rtype
proto: no encoder for sec int64 [GetProperties]
proto: no encoder for nsec int32 [GetProperties]
proto: no encoder for loc *time.Location [GetProperties]
proto: no encoder for Time time.Time [GetProperties]
proto: no encoder for i resource.int64Amount [GetProperties]
proto: no encoder for d resource.infDecAmount [GetProperties]
proto: no encoder for s string [GetProperties]
proto: no encoder for Format resource.Format [GetProperties]
proto: no encoder for InitContainers []v1.Container [GetProperties]
proto: no coders for intstr.Type
proto: no encoder for Type intstr.Type [GetProperties]
The Job "celery-worker-inspector" is invalid.
spec.template: Invalid value: {"metadata":{"creationTimestamp":null,"labels":{"controller-uid":"13eac6e5-81cf-11e6-8f5a-42010af001cc","job-name":"celery-worker-inspector","name":"celery-worker-inspector"}},"spec":{"volumes":null,"containers":[{"name":"celery-worker-inspector","image":"quay.io/test-co/api:ye-test-1474910174","command":["/usr/local/bin/python","tasks/worker_inspector.py"],"env":[{"name":"DEFAULT_DB_URL","valueFrom":{"secretKeyRef":{"Name":"api","key":"default-db-url"}}}],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"OnFailure","terminationGracePeriodSeconds":30,"activeDeadlineSeconds":90,"dnsPolicy":"ClusterFirst","serviceAccountName":"","securityContext":{}}}: field is immutable
```

The YAML file look like this:

``` yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: celery-worker-inspector
spec:
  template:
    metadata:
      labels:
        name: celery-worker-inspector
    spec:
      restartPolicy: OnFailure
      activeDeadlineSeconds: 90
      containers:
        - name: celery-worker-inspector
          image: quay.io/test-co/api:ye-test-1474910174
          command: ["/usr/local/bin/python", "tasks/worker_inspector.py"]
          env:
            - name: DEFAULT_DB_URL
              valueFrom:
                secretKeyRef:
                  name: api
                  key: default-db-url
```

The error message is quite raw that I have no clue what and why the yaml file was invalid. 
A few days later, as it turned out, it was due to the existing job with the same name that 
made `kubectl apply` kept failing. 

What made it even harder to interpret was the fact that the error message looked like it was a YAML validation error but it really wasn't.

Is there a better way to indicate this type of errors that gives a short and sweet answer rather than cryptic raw outputs? (IMMO `git` a shining example of what user (not only developer) friendly errors.)
