### ISSUE TITLE
Ingress service scaling results into 502 Bad Gateway on boot of pods

### ISSUE THREAD

**Issue by nvnobelen** [kubernetes/kubernetes#33674]
BUG REPORT:

When scaling a (simple) nginx using the HPA the service will return a number of 502 responses while the new pods are being activated. The tests run shows this happens on high CPU load of the container (so near 100% container CPU on nginx when you start scaling). There are less (but not 0) 502 errors when the load on the already running containers is much lower then 100%

**System details:**
Kubernetes version: 1.3.5 (kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:29:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
)
Nginx: 1.10.1
Platform: GCE
Debian Jessie with kernel 4.7.4
Docker version 1.9.1, build a34a1d5

**Load scenario/ how to replicate:**
Run 2 pods to a max of 100% cpu using jmeter. Pods are limited at (just) 100m, 80Mi 
Then increase pods to 4 while watching the number of 502 errors in jmeter.

**Yaml:**
```
Autoscaler:
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tracking-nginx-autoscaler
  namespace: default
spec:
  scaleRef:
    kind: Deployment
    name: tracking
    subresource: scale
  minReplicas: {numberOfReplicas}
  maxReplicas: {numberOfReplicas}
  cpuUtilization:
    targetPercentage: 90

```
In which {numberOfReplicas} = 2 for the first part of the test, then the HPA is reloaded with a setting of 4. During initialisation of the 2 new pods the 502s occurs 

Service definition
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tracking-ingress
spec:
  backend:
    serviceName: tracking-nginx-service
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-nginx-service
  labels:
    name: tracking-nginx-service
spec:
  type: NodePort
  selector:
    app: tracking-nginx
  ports:
  - name: "http"
    port: 80
    targetPort: "tracking-http"
    protocol: "TCP"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tracking
spec:
  template:
    metadata:
      name: tracking-nginx
      labels:
        app: tracking-nginx
    spec:
      containers:
        - name: tracking-nginx
          resources:
            requests:
              memory: 4Mi
              cpu: 100m
            limits:
              cpu: 100m
              memory: 80Mi
          image: gcr.io/ourproject/nginx-tracking:1.10.1_18
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - "/usr/local/nginx/serverDown.sh"
          ports:
            - containerPort: 80
              name: "tracking-http"
            - containerPort: 443
              name: "tracking-https"
          volumeMounts:
            - mountPath: /var/log/nginx
              name: local-share
              readOnly: false
            - mountPath: /data
              name: log-data
              readOnly: false
        - name: logstash-tracking
          resources:
            requests:
              memory: 1100Mi
              cpu: 1000m
            limits:
              cpu: 1000m
              memory: 1100Mi
          image: gcr.io/ourproject/logstash-tracking:2.3_3
          command:
            - "logstash"
            - "--allow-env"
            - "-f"
            - "/usr/local/logstashetl/config"
          env:
            - name: WEBSRV_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          lifecycle:
            postStart:
              exec:
                command:
                  - "/usr/local/logstashetl/cmds/signalServerUp.sh"
            preStop:
              exec:
                command:
                  - "/usr/local/logstashetl/cmds/signalServerDown.sh"
          volumeMounts:
            - mountPath: /localshare
              name: local-share
              readOnly: false
            - mountPath: /eventdata
              name: event-data
              readOnly: false
      volumes:
        - name: local-share
          emptyDir: {}
        - name: log-data
          nfs:
            server: prd-str-gue-04
            path: "/data/nfs/etl/logstash/logs"
            readOnly: false
        - name: event-data
          nfs:
            server: prd-str-gue-04
            path: "/data/nfs/etl/logstash"
            readOnly: false

```
