### ISSUE TITLE
Feature: allow configuring files in volumes without configmaps

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#33707]
atm I need to use a configmap to add files to my fake volumes, for example:

```
apiVersion: v1
kind: ConfigMap
data:
  process.yaml: |
    init_config:

... and later ...

      volumes:
        - name: configfiles
          configMap:
            name: datadog
```

this is a bit awkward since the reader has to jump back and forth, but also adds a separate model that needs to be managed / makes the deployment not be atomic (revert without updating configmap -> boom) ... so ideally it be possible to do this configuration inline:

```
      volumes:
        - name: configfiles
          data:
            process.yaml: |
              init_config:
```
