### ISSUE TITLE
Create a simple pod but failed，why?

### ISSUE THREAD

**Issue by dearplain** [kubernetes/kubernetes#33710]
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: smebberson/alpine-nginx
        ports:
        - containerPort: 80
```

```
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  15s           15s             1       {default-scheduler }                    Normal          Scheduled               Successfully assigned nginx-82fwn to yf-host
  15s           15s             2       {kubelet yf-host}                       Warning         MissingClusterDNS       kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  15s           15s             1       {kubelet yf-host}                       Warning         FailedSync              Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "addNDotsOption: ResolvConfPath \"/alidata1/docker/containers/a43d0c968d3b8761e0c640b04ee04b79fe38604f8a4c9828ff9b246ae0ddc259/resolv.conf\" does not exist"

  15s   15s     1       {kubelet yf-host}       spec.containers{nginx}  Normal  Pulled          Container image "smebberson/alpine-nginx" already present on machine
  14s   14s     1       {kubelet yf-host}       spec.containers{nginx}  Normal  Created         Created container with docker id 117f0684dfce
  14s   14s     1       {kubelet yf-host}       spec.containers{nginx}  Warning Failed          Failed to start container with docker id 117f0684dfce with error: Error response from daemon: {"message":"oci runtime error: rootfs_linux.go:53: mounting \"/alidata1/docker/aufs/mnt/58950762c7c59c994eb119a70d75eed21109756caecec54172bcc4ceb18d96f6/etc/hosts\" to rootfs \"/alidata1/docker/aufs/mnt/58950762c7c59c994eb119a70d75eed21109756caecec54172bcc4ceb18d96f6\" caused \"not a directory\""}
  14s   14s     1       {kubelet yf-host}                               Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "nginx" with RunContainerError: "runContainer: Error response from daemon: {\"message\":\"oci runtime error: rootfs_linux.go:53: mounting \\\"/alidata1/docker/aufs/mnt/58950762c7c59c994eb119a70d75eed21109756caecec54172bcc4ceb18d96f6/etc/hosts\\\" to rootfs \\\"/alidata1/docker/aufs/mnt/58950762c7c59c994eb119a70d75eed21109756caecec54172bcc4ceb18d96f6\\\" caused \\\"not a directory\\\"\"}"
```

I'm using gcr.io/google_containers/hyperkube-amd64:v1.4.0-alpha.0

docker version
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```
