### ISSUE TITLE
Feature GKE, GCE Internal Load Balancing

### ISSUE THREAD

**Issue by owenhaynes** [kubernetes/kubernetes#33830]
Google cloud now supports Internal Load Balancing (beta).  

Would be nice to expose a service on to a internal load balancer. To prevent having to run another machine to run ha-proxy with some extra magic. 

We currently have to-do this to support our elastic search cluster and would like to move away from this.

From the looks of it AWS sort of has an option for this on there services.

**Comment by erikgrinaker** [comment]
This is already possible by creating a service with a static endpoint. For example, we use the following to create a `rabbitmq01` service which points to an internal Google Cloud load balancer with IP `10.132.0.15` in front of our RabbitMQ cluster:

```yaml
kind: Endpoints
apiVersion: v1
metadata:
  name: rabbitmq01
subsets:
- addresses:
  - ip: '10.132.0.15'
  ports:
  - port: 5672
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq01
spec:
  ports:
  - port: 5672
```
