### ISSUE TITLE
kubedns doesn't start because of label kubernetes.io/cluster-service: "true"

### ISSUE THREAD

**Issue by yolkov** [kubernetes/kubernetes#33894]
BUG REPORT:

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: 3 baremetal nodes
- **OS** (e.g. from /etc/os-release): debian jessie
- **Kernel** (e.g. `uname -a`): Linux avi-app68 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
- **Install tools**:  kubelet as systemd service, others from manifests pods
- **Others**: calico network

**What happened**:
`cat kubedns-deployments.yaml`

``` yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dns-v20
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v20
    #kubernetes.io/cluster-service: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: kube-dns
      version: v20
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v20
        #kubernetes.io/cluster-service: "true"
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      #nodeSelector:
      #  kube-role: master
      volumes:
        - name: ssl-certs-kubernetes
          hostPath:
            path: /etc/kubernetes/ssl
        - name: kubeconfig
          hostPath:
            path: /etc/kubernetes/kubeconfig.yaml
      containers:
        - name: kubedns
          image: gcr.io/google_containers/kubedns-amd64:1.8
          resources:
            # TODO: Set memory limits when we've profiled the container for large
            # clusters, then set request = limit to keep this container in
            # guaranteed class. Currently, this container falls into the
            # "burstable" category so the kubelet doesn't backoff from restarting it.
            limits:
              cpu: 100m
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
          livenessProbe:
            httpGet:
              path: /healthz-kubedns
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8081
              scheme: HTTP
            # we poll on pod startup for the Kubernetes master service and
            # only setup the /readiness HTTP server once that's available.
            initialDelaySeconds: 30
            timeoutSeconds: 5
          args:
          # command = "/kube-dns"
          - --domain=dev.k8s
          - --dns-port=10053
          - --kubecfg-file=/etc/kubernetes/kubeconfig.yaml
          - --v=2
          volumeMounts:
          - mountPath: /etc/kubernetes/ssl
            name: ssl-certs-kubernetes
            readOnly: true
          - mountPath: /etc/kubernetes/kubeconfig.yaml
            name: kubeconfig
            readOnly: true
          ports:
          - containerPort: 10053
            name: dns-local
            protocol: UDP
          - containerPort: 10053
            name: dns-tcp-local
            protocol: TCP
        - name: dnsmasq
          image: gcr.io/google_containers/kube-dnsmasq-amd64:1.4
          livenessProbe:
            httpGet:
              path: /healthz-dnsmasq
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          args:
          - --cache-size=1000
          - --no-resolv
          - --server=127.0.0.1#10053
          ports:
          - containerPort: 53
            name: dns
            protocol: UDP
          - containerPort: 53
            name: dns-tcp
            protocol: TCP
        - name: healthz
          image: gcr.io/google_containers/exechealthz-amd64:1.2
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 10m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
          args:
          - --cmd=nslookup kubernetes.default.svc.dev.k8s 127.0.0.1 >/dev/null
          - --url=/healthz-dnsmasq
          - --cmd=nslookup kubernetes.default.svc.dev.k8s 127.0.0.1:10053 >/dev/null
          - --url=/healthz-kubedns
          - -port=8080
          #- -quiet
          ports:
          - containerPort: 8080
            protocol: TCP
      dnsPolicy: Default
```

if I create this deployments:
`kubectl create -f kubedns-deployments.yaml`
it's ok
If I uncomment `#kubernetes.io/cluster-service: "true"`, then pods started and immediately terminated.

**What you expected to happen**:
I want start kubedns as addon
