### ISSUE TITLE
PetSet container config is not regenerated in case of Failure

### ISSUE THREAD

**Issue by holser** [kubernetes/kubernetes#33938]
**BUG REPORT**

**Kubernetes version** (use `kubectl version`):

`Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-beta.11.1+26dbde542d8a7d-dirty", GitCommit:"26dbde542d8a7df3b0eac1c4094762ae5b82c1f9", GitTreeState:"dirty", BuildDate:"2016-09-28T10:08:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-beta.11.1+26dbde542d8a7d-dirty", GitCommit:"26dbde542d8a7df3b0eac1c4094762ae5b82c1f9", GitTreeState:"dirty", BuildDate:"2016-09-28T10:08:15Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Cloud provider or hardware configuration**:

baremetal
- **OS** (e.g. from /etc/os-release):

16.04.1 LTS (Xenial Xerus)
- **Kernel** (e.g. `uname -a`):

Linux node1 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:

`kill -9` on mysql-0 introduced a split brain.

**What you expected to happen**:

expected a regenerated config with is used for connecting to cluster.

**How to reproduce it**
- Let's create service

`kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/test/e2e/testing-manifests/petset/mysql-galera/service.yaml`
- Let's create pv

```
cat << EOF | kubectl create -f -
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv0
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/mysql-0"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv1
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/mysql-1"

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv2
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/mysql-2"
EOF
```
- Let's create a petset (_delete annotation in volume_ if you are not running GCE)

`kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/test/e2e/testing-manifests/petset/mysql-galera/petset.yaml`
- Let's wait when all pods are running

`kubectl get pods`
NAME      READY     STATUS    RESTARTS   AGE       IP              NODE
mysql-0   1/1       Running   0          6m        10.233.83.70    node1
mysql-1   1/1       Running   0          5m        10.233.86.72    node3
mysql-2   1/1       Running   0          5m        10.233.73.199   node2
- Let's check the config of mysql-0 pod

`kubectl exec -t -i mysql-0 /bin/cat /etc/mysql/my-galera.cnf | grep wsrep_cluster_address`
wsrep_cluster_address=gcomm://
`kubectl exec -t -i mysql-1 /bin/cat /etc/mysql/my-galera.cnf | grep wsrep_cluster_address`
wsrep_cluster_address=gcomm://mysql-0.galera.default.svc.cluster.local,mysql-1.galera.default.svc.cluster.local
- Let's check how many nodes in cluster

`mysql -h10.233.83.70 -e 'show status like "wsrep_incoming_addresses"\G'`
**************************\* 1. row ***************************
Variable_name: wsrep_incoming_addresses
        Value: mysql-0.galera.default.svc.cluster.local:3306,mysql-1.galera.default.svc.cluster.local:3306,mysql-2.galera.default.svc.cluster.local:3306

All 3 nodes have the same info. 
- Let's 'kill -9' the process of mysql-0 (it's important to kill exactly mysql-0 as it's config is empty). Let's wait when it's up and running
- Let's compare  'wsrep_incoming_addresses' on this node and on any other node

`mysql -h10.233.83.70 -e 'show status like "wsrep_incoming_addresses"\G'`
**************************\* 1. row ***************************
Variable_name: wsrep_incoming_addresses
        Value: mysql-0.galera.default.svc.cluster.local:3306
`mysql -h10.233.86.72 -e 'show status like "wsrep_incoming_addresses"\G'`
**************************\* 1. row ***************************
Variable_name: wsrep_incoming_addresses
        Value: mysql-1.galera.default.svc.cluster.local:3306,mysql-2.galera.default.svc.cluster.local:3306

We've got a split brain as config for mysql-0 was not regenerated.

**Anything else do we need to know**:

Normally, config should be regenerated somehow. It should be done by rerunning init container or introduce a new type of 'refresh' containers. Otherwise stateful services will require much more complex orchestration.
