### ISSUE TITLE
kubectl 1.4 cannot edit 1.2 cluster deployment using DownwardAPI mount because defaultMode is invalid

### ISSUE THREAD

**Issue by hubt** [kubernetes/kubernetes#33968]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
kubectl defaultMode

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

Doing a `kubectl edit deployment <deployment>` fails with the error unless the `defaultMode` line is deleted :
```error: found invalid field defaultMode for v1.DownwardAPIVolumeSource
```

**Kubernetes version** (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.1", GitCommit:"50809107cd47a1f62da362bccefdd9e6f7076145", GitTreeState:"clean", BuildDate:"", GoVersion:"", Compiler:"", Platform:""}
```

**Environment**:
- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release): debian/jessie
- **Kernel** (e.g. `uname -a`): n/a
- **Install tools**: kube-up.sh
- **Others**:

**What happened**:
kubectl edit failed
```error: found invalid field defaultMode for v1.DownwardAPIVolumeSource```

**What you expected to happen**:
kubectl edit succeeded.

**How to reproduce it** (as minimally and precisely as possible):
use `kubectl edit deployment <deployment>` with kubectl version 1.4 talking to a kubernetes 1.2 cluster for a deployment that is using the Downward API eg.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            # name must match the volume name below
            - name: podinfo
              mountPath: /mnt
              readOnly: false
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
```

**Anything else do we need to know**:
