### ISSUE TITLE
Deleting a deployment does not delete replicaset

### ISSUE THREAD

**Issue by jonathan-kosgei** [kubernetes/kubernetes#34052]
The following is a standard deployment 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{name}}
  namespace: {{namespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{name}}
      name: {{name}}
    spec:
      containers:
      - name: redis
        image: jkosgei/redis
        env:
           - name: PASS
             value: {{ auth_password }}
        imagePullPolicy: Always
        ports: 
          - name: redis
            containerPort: "6379"
        volumeMounts:
        - name: gluster
          mountPath: /data
          subPath: {{app_id}}/app
      volumes:
      - name: gluster
        persistentVolumeClaim:
          claimName: "storage-{{name}}-{{namespace}}"
```

According to the docs at http://kubernetes.io/docs/user-guide/deployments/ , creating the above with create a replicaset with a redis pod under it. In this sense creating the above deployment will create a replicaset. However deleting the above with , via api will not delete the replicaset created. The pods will stay up and continue running.
