### ISSUE TITLE
Identify missing storage drivers & tooling in GCI

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#34127]
GCI base image is missing a few storage drivers and tooling. Given that GCI is currently only available on GCP, it doesn't have to include support for all storage backends in k8s. 
Known list of missing storage drivers and tooling include,
1. NFS (kernel support exists, missing tools)
2. Glusterfs 
3. ??

@kubernetes/sig-storage @saad-ali @Amey-D

**Comment by vishh** [comment]
@Amey-D & @saad-ali are already working on adding support for glusterfs and nfs. Help from the community to identify what other storage drivers are important with k8s on GCP will be helpful.

**Comment by vishh** [comment]
In addition to identifying plugins, we need to add simple node e2e tests for these storage backends.

**Comment by jsindy** [comment]
It would make sense to run through the list of supported volumes located here http://kubernetes.io/docs/user-guide/volumes/

**Comment by luxas** [comment]
Everything will be easier with containerized volumes I think.
That's proposed in #32550 and would remove the need for gluster and nfs binaries on host.

GCI, CoreOS and RancherOS are environments which may not have such tools on host and that's where containerized volume drivers would shine.

Maybe it's worth focusing on that for the general case instead of hacking it by adding those specific tools you need today. Tomorrow, users will ask about the next volume driver they want to use on GCI, and then you would have to update the base image again.

WDYT?

**Comment by jsafrane** [comment]
There are e2e tests for most of the volumes, however they're disabled because they need privileged containers (to run NFS and iSCSI servers) and necessary client tools were often missing.

From `kubernetes/cluster/saltbase/salt/e2e/init.sls`:

```
e2e:
  # Install various packages required by e2e tests to all hosts.
  pkg.installed:
    - refresh: true
    - pkgs:
      - targetcli
      - ceph
{% if grains['os_family'] == 'RedHat' %}
      - glusterfs-fuse
      - rbd-fuse
      - iscsi-initiator-utils
      - nfs-utils
{% else %}
      - glusterfs-client
      - open-iscsi
      - iscsitarget-dkms
      - nfs-common
{% endif %}
```

This installs both server components that need to be present on a node to run a test server (e.g. kernel modules for iSCSI - this can't be shipped in a container) and client tools.
