### ISSUE TITLE
Add a kubectl command to generate manifests

### ISSUE THREAD

**Issue by cgag** [kubernetes/kubernetes#34148]
Currently if I want to create a deployment, I either copy and paste from the docs and modify as needed.  It would be nice to be able to run something like `kubectl new deployment` and have
a template spit to stdout like:
 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: myapp
        image: myimage:mytag
        ports:
        - containerPort: 80
```

I actually wouldn't particularly mind if it just dumped out one of the examples from the current docs, filled with nginx.
