### ISSUE TITLE
AWS: Instances briefly deregistered from service ELB after replacement of single controller instance

### ISSUE THREAD

**Issue by jnewland** [kubernetes/kubernetes#34267]
**Is this a request for help?**: No.

**What keywords did you search in Kubernetes issues before filing this one?**: ELB, Elastic. https://github.com/kubernetes/kubernetes/issues/26362 and https://github.com/kubernetes/kubernetes/issues/11002 may be related, but are not identical.

---

**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report.

**Kubernetes version** (use `kubectl version`): 1.4.0

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Debian Jessie
- **Kernel** (e.g. `uname -a`): `Linux ip-172-20-63-176 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`
- **Install tools**: kubernetes/kops@5871b24b320b1c336c5d5096a456d1f94c82c2e7
- **Others**:  `kops create cluster $NAME --node-size m3.large --zones us-east-1a`

**What happened**:

On a single-controller 1.4.0 cluster launched with kops, requests to an existing service's ELB sometimes fail for a short duration after the termination of a controller instance and the creation of a replacement instance. In situations where requests are observed to fail, the newly-launched controller instance contains entries similar to the following in `/var/log/kube-controller-manager.log`:

```
I1006 18:28:35.971327       5 aws_loadbalancer.go:419] Instances removed from load-balancer a0bb431bd8bef11e692940a24a820d1a
I1006 18:30:15.130235       5 aws_loadbalancer.go:408] Instances added to load-balancer a0bb431bd8bef11e692940a24a820d1a
```

All requests failed to this service's ELB in the time between these two log events. CloudTrail records an `DeregisterInstancesFromLoadBalancer` request being made at the time of the first entry that removes all of the running minions from this ELB, and a corresponding `RegisterInstancesWithLoadBalancer` call that adds them back at the same time as the second entry.

**What you expected to happen**:

I expected the failure of a controller instance in a `kops` launched cluster to not negatively impact the ability to access a service through it's configured ELB, as a replacement instance is started with the same `etcd` state as existed on the previous controller instance.

**How to reproduce it** (as minimally and precisely as possible):

I'm able to reproduce this failure about 30% of the time by following this procedure:
- Create a kops cluster with the version and arguments provided above.
- Create the following resources:

``` yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: http-echo
spec:
  selector:
    matchLabels:
      app: http-echo
  replicas: 2
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo
        image: kennship/http-echo
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
  labels:
    app: http-echo
spec:
  type: LoadBalancer
  selector:
    app: http-echo
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
```
- Wait until an ELB is created: `kubectl get service http-echo -o jsonpath="{.status.loadBalancer.ingress[0].hostname}"`
- Confirm that a request to this ELB returns a successful result.
- Terminate the running controller instance.
- Send sustained traffic to the service's ELB.
- Observe that requests to this service fail after the newly-launched controller instance's controller-manager process deregisters minion instances from the service's ELB.
- Observe that requests to this service succeed a short while later as the controller manager re-registers the same instances.

**Anything else do we need to know**:

I'm able to re-run the simulation that triggers this situation and gather additional information anytime if there's anything in particular that would be useful.

/cc @justinsb, who spoke briefly with me about this in #sig-aws. Thanks again!
