### ISSUE TITLE
Server side defaulting of values prevents diff patches from working

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#34292]
Server side defaults are easily differentiated from other values set within the kubernetes system (e.g. DeploymentStatus).  `kubectl apply` records the applied config as an annotation on the objects that it creates so that it can perform a 3-way diff to merge local changes into the live config without erasing other items such as the status.

Steps to reproduce:

Use `kubectl apply -f` to create a deployment using this config:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80 
```

Update the config spec adding

```yaml
strategy:
    type: "Recreate"
```

Apply the new config.

Result:

```sh
The Deployment "nginx-deployment" is invalid.
spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

This is caused because the server defaults spec.strategy.rollingUpdate but this is invisible to the client and cannot be differentiated from other changes made by the server (e.g. status changes).

This can be seen for any field whose default is derived from another field such as Deployment labels and selectors (derived from the PodTemplate labels).

Solving this will require at least some changes on the server side.  One possible solution would be to:
1. Have the server record which derived fields that it adds / updates
1. Have the client then merge these changes into the last-applied-config used by diff patch so they are deleted
1. Have the server re-perform defaulting / normalization on the resulting object from the PATCH

Thoughts / Comments / Suggestions?
