### ISSUE TITLE
Cannot mount volume with different subPath

### ISSUE THREAD

**Issue by wernight** [kubernetes/kubernetes#34453]
**Kubernetes version** (use `kubectl version`): 1.4 (client and server)

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"201
6-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"201
6-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

```

**Environment**:
- **Cloud provider or hardware configuration**: GKE

**What happened**:
Doesn't show an error but only keeps **one** of the volumes mount when the same volume is mounted multiple times (with different `mountPath` and `subPath`).

**What you expected to happen**:
Should work (that's the main reason to have `subPath`) or at least fail with an error.

**How to reproduce it** (as minimally and precisely as possible):
YAML:

```
     volumeMounts:
        - name: che-vol
          mountPath: /home/user/che/workspaces
          subPath: workspaces
        - name: che-vol
          mountPath: /home/user/che/storage
          subPath: storage
```

**Anything else do we need to know**:
Trying here to mount a GKE disk, so cannot reference that volume twice.
