### ISSUE TITLE
Audit log not working

### ISSUE THREAD

**Issue by dhawal55** [kubernetes/kubernetes#34560]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**: `AWS`
- **OS** (e.g. from /etc/os-release): 
```
NAME=CoreOS
ID=coreos
VERSION=1185.1.0
VERSION_ID=1185.1.0
BUILD_ID=2016-10-05-0500
PRETTY_NAME="CoreOS 1185.1.0 (MoreOS)"
```
- **Kernel** (e.g. `uname -a`):
```
Linux ip-xx-xx-xx-xx.cloud.example.net 4.7.3-coreos #1 SMP Wed Oct 5 04:11:34 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
```

**What happened**:
I'm running a 2 node k8s cluster (1 master, 1 worker) with following kube-apiserver definition and expect audit logs to be generated but no logs are generated:
```
name: kube-apiserver
      image: "gcr.io/google_containers/hyperkube:v1.4.0"
      command:
        - /hyperkube
        - apiserver
        - "--bind-address=0.0.0.0"
        - "--authorization-mode=RBAC"
        - "--authorization-rbac-super-user=xyz.cloud.example.net"
        - "--audit-log-maxage=30"
        - "--audit-log-maxsize=100"
        - "--audit-log-path=/var/log/apiserver/audit.log"
        - "--runtime-config=rbac.authorization.k8s.io/v1alpha1"
        - "--secure-port=443"
        - "--insecure-bind-address=0.0.0.0"
        - "--insecure-port=8080"
        - "--apiserver-count=1"
        - "--allow-privileged=true"
        - "--tls-cert-file=/etc/kubernetes/ssl/apiserver.pem"
        - "--tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem"
        - "--client-ca-file=/etc/kubernetes/ssl/ca.pem"
        - "--service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem"
        - "--cloud-provider=aws"
```

**What you expected to happen**:
I expected audit logs to be generated for calls made to api-server via kubectl

**How to reproduce it** (as minimally and precisely as possible):
Start a new k8s cluster with 1 master and 1 worker and the above definition for api-server. After the cluster is up and running, make calls to view pods/services from kubectl. ssh to master node and verify if audit logs are created.

**Anything else do we need to know**:
