### ISSUE TITLE
Default seccomp profile cannot be configured without hardcoding it in Kubelet

### ISSUE THREAD

**Issue by metral** [kubernetes/kubernetes#34649]
As of v1.4.0 (and current master), the default seccomp profile is set to`unconfined`, as this is the intended behavior for a new k8s cluster.

However, it would be great if there was a config flag in the Kubelet that allowed the specification of an alternate default seccomp profile e.g. the `docker/default` profile. Currently, we have to alter the src and rebuild the bin to use `docker/default` so that we don't force user's to specify the profile in resource annotations every time.

Hardcoded setting: https://github.com/kubernetes/kubernetes/blob/v1.4.0/pkg/kubelet/dockertools/docker_manager.go#L115

**Comment by lblackstone** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/20870

**Comment by timstclair** [comment]
I believe this is fixed by https://github.com/kubernetes/kubernetes/pull/28300 (in v1.5), which lets the default seccomp profile be specified as part of the cluster-wide PodSecurityPolicy via an annotation: `seccomp.security.alpha.kubernetes.io/defaultProfileName`.

@pweil-

**Comment by lblackstone** [comment]
Confirmed that this is possible in v1.5.2 by following these steps:

1. Run `kube-apiserver` with `–runtime-config=extensions/v1beta1/podsecuritypolicy=true` and `–admission-control=PodSecurityPolicy` set.
1. Create a PSP like the following example `psp.yaml` and apply it with a `kubectl create -f psp.yaml`.

### psp.yaml
```yaml
kind: PodSecurityPolicy
apiVersion: "extensions/v1beta1"
metadata:
 name: seccomp-default
 annotations:
  seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
  seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
spec:
 seLinux:
  rule: RunAsAny
 supplementalGroups:
  rule: RunAsAny
 runAsUser:
  rule: RunAsAny
 fsGroup:
  rule: RunAsAny
 volumes:
  - "*"
```

Pods launched after this policy is created have `"SecurityOpt":[]` set in the docker API call.
