### ISSUE TITLE
Ingress doesn't add X-Forwarded-Host header

### ISSUE THREAD

**Issue by hekike** [kubernetes/kubernetes#34723]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

`x-forwarded-host`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT:

While ingress behaves as a proxy I believe it should add the `X-Forwarded-Host` header to the request. Like in the nginx example: https://github.com/kubernetes/contrib/tree/ed89c3de28b5455a7914e1461073a1c50180961a/ingress/controllers/nginx/examples/rewrite

**Kubernetes version** (use `kubectl version`):

`1.3.7`

**Environment**:
- Kubernetes on GC (Container Engine)

**What happened**:

- `X-Forwarded-Host` doesn't show up in request in pod.

**What you expected to happen**:

Ingress adds `X-Forwarded-Host` header.

**How to reproduce it** (as minimally and precisely as possible):

pod + service + ingress

ingress config:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  backend:
    serviceName: my-service
    servicePort: 80
  tls:
  - secretName: my-secret
```

**Anything else do we need to know**:
-
