### ISSUE TITLE
kubectl edit brokenness editing volumeMounts (list of struct)

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#34800]
Start with:

```        
       volumeMounts:
        - mountPath: /vol
          name: vol 
        - mountPath: /vol-456                                                                                                                                 
          name: vol 
          subPath: d456
```

Edit to:

```
        volumeMounts:
        - mountPath: /vol
          name: vol 
        - mountPath: /vol-d2
          name: vol
          subPath: d2     
```

Read back what happened:

```
        volumeMounts:
        - mountPath: /vol-d2
          name: vol 
          subPath: d2
        - mountPath: /vol-456
          name: vol 
          subPath: d456
```

It synthesized a COMPLETELY WRONG result.  At this point, I can not, in good conscience, advocate using kubectl edit.

Can I please have `kubectl edit --replace` that doesn't go through patch brokenness.  Or better, make that default for 1.5 and make `kubectl edit --patch`   be the broken (but eventually fixed) path.
