### ISSUE TITLE
PSP usability subresources

### ISSUE THREAD

**Issue by pweil-** [kubernetes/kubernetes#34963]
Creating follow up issue for https://github.com/kubernetes/kubernetes/pull/33080#issuecomment-249038736

Create subresources for PSP usability items:

"use" subresource on the PodSecurityPolicy object that returns 200 if you are authorized to use that PSP, and 403 if you are not.

"match" subresource on a PodSecurityPolicy object that takes a Pod and returns 200, plus a JSON message that says "match: true" or "match: false".

**Comment by zetaab** [comment]
any progress in this? currently podsecuritypolicy is kind of useless because all policies is returned always. It means that if we have some policies in kube-system components, all other namespaces are also allowed to use those.

**Comment by pweil-** [comment]
@zetaab https://github.com/kubernetes/kubernetes/pull/33080 allowed the ability to grant access to specific policies when RBAC is enabled so that you can [control which policies are matched](https://github.com/kubernetes/kubernetes/tree/master/examples/podsecuritypolicy/rbac).  This issue is only a follow up to add some usability enhancements.

**Comment by zetaab** [comment]
@pweil- hmm, ok. Well i have tried to follow those instructions but it does not work for me as excepted (i am using 1.5.1 and RBAC). What i am trying to achieve is that kube-system namespace can do whatever their pod wants, but in default namespace i want disable things like hostPath mount.

I can share my yaml files:

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: privileged-psp-user
rules: 
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
```

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: restricted-psp-user
rules: 
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - restricted
  verbs:
  - use
```

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
    name: privileged-psp-users
subjects:
- kind: User
  name: kubelet
- kind: ServiceAccount
  name: default
  namespace: kube-system
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: privileged-psp-user
```

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
    name: restricted-psp-users
subjects:
- kind: User
  name: myuser
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: restricted-psp-user
```

```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  privileged: true
  defaultAddCapabilities: null
  requiredDropCapabilities: null
  allowedCapabilities: null
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  -
    min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
```

```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: false
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - 'emptyDir'
  - 'secret'
  - 'downwardAPI'
  - 'configMap'
  - 'persistentVolumeClaim'
  - 'cinder'
```

when i create new deployment to default namespace using "myuser" -user, i can see following in log files. Other background info to this user is that it has role cluster-admin in namespace default.
```
{"log":"I1229 12:09:10.640748       1 admission.go:155] getting pod security policies for pod  (generate: demoapp-2647692745-)\n","stream":"stderr","time":"2016-12-29T12:09:10.64097391Z"}
{"log":"I1229 12:09:10.640824       1 admission.go:361] validating pod  (generate: demoapp-2647692745-) against providers privileged,restricted\n","stream":"stderr","time":"2016-12-29T12:09:10.641109155Z"}
{"log":"I1229 12:09:10.640892       1 admission.go:188] pod  (generate: demoapp-2647692745-) validated against provider privileged\n","stream":"stderr","time":"2016-12-29T12:09:10.64112267Z"}
```

the interesting thing here is why it is returning all policies to single pod? As i understand myuser should have only that restricted policy added? 

https://github.com/kubernetes/kubernetes/blob/v1.5.1/plugin/pkg/admission/security/podsecuritypolicy/admission.go#L304

maybe because of this?
// getMatchingPolicies returns policies from the store.  For now this returns **everything**
// in the future it can filter based on UserInfo and permissions.

or is this something that i am not using correctly? I can also make separate issue about this if this is not correct place to ask.
