### ISSUE TITLE
kubelet: http prober DNS resolver

### ISSUE THREAD

**Issue by kayrus** [kubernetes/kubernetes#35032]
When you use internal service name (when you have installed DNS add-on), kubelet doesn't use it for probing:

```
spec.containers{app-master}   Warning   Unhealthy   {kubelet 172.16.0.12}   Readiness probe failed: Get http://app-master/status: dial tcp: lookup app-master on 127.0.0.1:53: no such host
```

Even when you define `--cluster-dns=10.254.0.10` inside kubelet.

This problem actually lies in go implementation (see https://github.com/golang/go/issues/12503, which should be resolved soon). But I suggest a hack. When there is defined resolver, we have to resolve host first (i.e. `https://golang.org/pkg/net/#ResolveIPAddr`, hook around `url.Host = net.ResolveIPAddr("foo")` and then automatically populate `req.Host` and set it to `foo` https://github.com/kubernetes/kubernetes/blob/bcbdcd17f3430545e60a52e27661cc6ca14800e4/pkg/probe/http/http.go#L61). Does it make sense?

``` yaml
        readinessProbe:
          httpGet:
            host: app-master
            scheme: HTTP
            path: /status
          timeoutSeconds: 30
          successThreshold: 3
```
