### ISSUE TITLE
'Stat fs failed: no such file or directory' error in kubelet logs

### ISSUE THREAD

**Issue by daniilyar** [kubernetes/kubernetes#35062]
Running Kubernetes 1.4.1 at AWS (Ubuntu 14.04 LTS). Kubernetes cluster is spinned with 'contrib/ansible' playbook with the only change of `--cloud-provider aws` argument added to all cluster internal services (such as kubelet).

After spinning up and terminating several pods with config like below

```
apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: kafka1
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: kafka1
        image: daniilyar/kafka
        ports:
        - containerPort: 9092 
          name: clientconnct
          protocol: TCP
        volumeMounts:
        - mountPath: /kafka
          name: storage
      volumes:
      - name: storage
        awsElasticBlockStore:
          volumeID: vol-56676d83
          fsType: ext4
```

I see a following error in kubelet logs logged each 40-60 sec:

```
E1018 21:03:09.616581   22780 fs.go:332] Stat fs failed. Error: no such file or directory
```

Error contains a different line number than in https://github.com/kubernetes/kubernetes/issues/17725 , so I assume this one is probably not a duplicate.
