### ISSUE TITLE
kubectl apply fails when the type of env var in the manifest changes from value to configmap reference

### ISSUE THREAD

**Issue by kmala** [kubernetes/kubernetes#35134]
**Kubernetes version** (use `kubectl version`): 1.4.0

**Environment**:
- **Cloud provider or hardware configuration**: GKE

**What happened**: `kubectl apply` fails to change the way environment variable is specified from a normal value to a configmap reference.

**How to reproduce it** (as minimally and precisely as possible): Create a deployment object with an environment var in the container manifest just as a key, value pair. Now update the manifest to use a key from configmap as the valuefrom instead of simple value and do a `kubectl apply` which fails giving the error:

```
Deployment.extensions "deis-test" is invalid: spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when `value` is not empty
```

**Comment by ymqytw** [comment]
@kmala Can you paste the manifest here?

**Comment by kmala** [comment]
Created the deployment using
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-test
  labels:
    heritage: deis
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: deis-test
  template:
    metadata:
      labels:
        app: deis-test
    spec:
      containers:
        - name: deis-test
          image: deis/example-go:latest
          imagePullPolicy: Always
          env:
            - name: "SLUGBUILDER_IMAGE_NAME"
              value: "deis/slugbuilder:canary"
```
then did a kubectl apply using 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deis-test
  labels:
    heritage: deis
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: deis-test
  template:
    metadata:
      labels:
        app: deis-test
    spec:
      containers:
        - name: deis-test
          image: deis/example-go:latest
          imagePullPolicy: Always
          env:
            - name: "SLUGBUILDER_IMAGE_NAME"
              valueFrom:
                configMapKeyRef:
                  name: slugbuilder-config
                  key: image
```
