### ISSUE TITLE
Container Spec env vars: allow simple map instead of list of name/value pairs

### ISSUE THREAD

**Issue by hjacobs** [kubernetes/kubernetes#35151]
**Is this a request for help?**: no

**What keywords did you search in Kubernetes issues before filing this one?**: env, spec, environment

---

I would like to conveniently specify container environment variables via a simple map instead of having a list of "name"/"value" pairs.

I.e. rather than defining the following (real world examples have a much larger number of env vars):

``` yaml
env:
- name: FOO_URL
  value: https://example.org/foo
- name: BAR_URL
  value: https://example.org/bar
```

I would like to have a simple:

``` yaml
env_map:
 FOO_URL: https://example.org/foo
 BAR_URL: https://example.org/bar
```

I find the current "env" property rather inconvenient for human users to use directly (I know of the flexibility to lookup a single value from config map etc, but it should IMHO be convenient for the 90% use case).

See also my [original post on the kubernetes-users mailing list](https://groups.google.com/forum/#!topic/kubernetes-users/t-k7VMtDwgM).
