### ISSUE TITLE
Automatic service env-var names can collide with apps

### ISSUE THREAD

**Issue by Tapuzi** [kubernetes/kubernetes#35189]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4+coreos.0", GitCommit:"be9bf3e842a90537e48361aded2872e389e902e7", GitTreeState:"clean", BuildDate:"2016-08-02T00:54:53Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: CoreOS v0.8.1 on AWS
- **OS** (e.g. from /etc/os-release): 

> NAME=CoreOS
> ID=coreos
> VERSION=1068.10.0
> VERSION_ID=1068.10.0
> BUILD_ID=2016-08-23-0220
> PRETTY_NAME="CoreOS 1068.10.0 (MoreOS)"
> ANSI_COLOR="1;32"
> HOME_URL="https://coreos.com/"
> BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
- **Kernel**: Linux ip-10-0-0-136.eu-central-1.compute.internal 4.6.3-coreos #2 SMP Tue Aug 23 02:14:16 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz GenuineIntel GNU/Linux
- **Install tools**: kube-aws

**What happened**: A container failed running and produced a cryptic log.

**What you expected to happen**: The container to work.

**How to reproduce it** (as minimally and precisely as possible): Described in detail below
## Most important info:

Kubernetes v1.3.4
Certain pod crashes on creation without providing info because of a running service associated with it.
## I want to mention something

I think there is a bigger improvement potential here rather than fixing the bug: I actually stated filling a bug report on pod creation, because I didn't understand the whole issue and the error feedback from kubernetes is lacking.
I started looking at the `docker inspect` of containers before guessing it might be something else.
## How to reproduce (including all resources)

Run the following commands to reproduce and see the problematic log: (resources below)

```
kctl create -f service-rq-dashboard.yaml
kctl create -f pod-rq-dashboard.yaml
kctl logs rq-dashboard
```

I got this:

```
Usage: rq-dashboard [OPTIONS]

Error: Invalid value for "-p" / "--port": tcp://10.3.0.49:80 is not a valid integer
```
### Dockerfile for the image (no other files needed for the `docker build`)

```
FROM python:2.7.11-alpine
# Install
RUN pip install rq-dashboard
EXPOSE 9181
CMD ["rq-dashboard", "-H redis", "-P 6379"]
```
### pod-rq-dashboard.yaml

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rq-dashboard
  name: rq-dashboard
spec:
  containers:
  - name: rq-dashboard
    image: rq-dashboard
    command: ["/bin/sh", "-c", "rq-dashboard", "-H", "redis", "-P", "6379"]
    ports:
    - containerPort: 9181
```
### service-rq-dashboard.yaml

```
apiVersion: v1
kind: Service
metadata:
  name: rq-dashboard
spec:
  selector:
    app: rq-dashboard
  ports:
    - name: rq-dashboard
      protocol: TCP
      port: 80
      targetPort: 9181
```
## More info

To be concise: I ssh'd into my coreos to try and run a docker image that was failing. 
While doing that I got the following error log from the pod:

```
itay@ubuntu $ kctl logs --follow rq-dashboard-3456423072-xkc5w
Usage: rq-dashboard [OPTIONS]

Error: Invalid value for "-p" / "--port": tcp://10.3.0.105:80 is not a valid integer
```

The image is runnable from the same host with the same docker command and arguments. (tested via docker run, verified by comparing docker inspect with the kubectl run)
