### ISSUE TITLE
two petset with the same service

### ISSUE THREAD

**Issue by davidstack** [kubernetes/kubernetes#35269]
when i test petset, i want to deploy two petset whih one service. my file is
service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  **name: ambari-cluster**
  namespace: bigdata
  labels:
    app: ambari-cluster
spec:
  type: NodePort
  clusterIP: None
  ports:
- name: web
  port: 8080
  targetPort: 8080
  nodePort: 31175
- name: agent
  port: 8440
  targetPort: 8440
- name: https
  port: 8441
  targetPort: 8441
  selector:
    app: ambari-cluster
```
petset1.yaml
```yaml
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: ambari-master
  namespace: bigdata
spec:
  **serviceName: "ambari-cluster"**
  replicas: 1
  template:
    metadata:
      labels:
        app: ambari-master
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: ambari-master
        image: 10.110.17.138:5000/iop/ambari-server:v2.0
        imagePullPolicy: Always
        command:
           - /usr/local/bin/start.sh
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        - name: agent
          containerPort: 8440
          protocol: TCP
        - name: https
          containerPort: 8441
          protocol: TCP
        securityContext:
          privileged: true
```
petset2.yaml:
```yaml
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: ambari-agent
spec:
  **serviceName: "ambari-cluster"**
  replicas: 5
  template:
    metadata:
      labels:
        app: ambari-agent
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: ambari-agent
        image: 10.110.17.138:5000/iop/ambari-agent:v2.0
        imagePullPolicy: Always
        command:
           - /usr/local/bin/start.sh
        securityContext:
          privileged: true
```
after i create petset1 and petset2. i can only create one petset. is there any method that we can create two petset with the same service?
