### ISSUE TITLE
Feature proposal: generic cmd auth provider plugin for kubectl

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#35530]
kubectl currently supports 2 [auth provider plugins](https://github.com/kubernetes/kubernetes/tree/master/plugin/pkg/client/auth), gcp and oidc. I believe a wide range of other use cases could be handled by a plugin that runs a command to generate an access token.

Sample [AuthProviderConfig](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/clientcmd/api/types.go#L143) below with explanation:

```
name: cmd
config:
  command:
  - /path/to/binary/gettoken
  - --with
  - args
  format: json
  token-key: access_token
  expiry-key: token_expiry
```
- `command` is a command to execute that will generate an access token. First element is path to executable, remaining elements treated as args
- `format` is the format of the output, json/yaml by default, or raw (interpret output in its entirety as bearer token).
- `token-key` is the field name of the access token in json/yaml output, required if format is not raw.
- `expiry-key` is the field name of an rfc3339-formatted expiration timestamp in json/yaml output, optional.

This will allow kubectl to easily integrate with arbitrary auth systems. I'd like to add it for v1.5. @kubernetes/sig-auth, @kubernetes/kubectl, thoughts?

cc @cjcullen

**Comment by hjacobs** [comment]
@jlowdermilk we use token authentication and we are using a simple helper script/binary to generate the right `kubeconfig` for the user. So theoretically this feature proposal is interesting for us, BUT: I think it just makes `kubectl` more complex and other tools like the `docker` client have the same issue (we also generate a `.docker/config.json` with a token).

=> My opinion is that the `kubeconfig` file is a good enough interface for other tools.

**Comment by jlowdermilk** [comment]
@hjacobs, are your tokens long lived? For long lived tokens, generating kubeconfig is sufficient, but if you have access tokens with a 1hr expiry (oauth2 default), it's a pain to have to manually run a helper when kubectl could do it for you and handle caching the access token.

**Comment by deads2k** [comment]
@smarterclayton How do you feel about this versus the kubectl extension mechanism? I think that `kubectl login` plus  kubectl extensions would end up being a nicer integration long term.

If we go down this route instead, I think we'll want a way to pass through the current state of the merged kubeconfig file or maybe just the known information to the helper command.

**Comment by ericchiang** [comment]
@jlowdermilk would you just want to add an OAuth2 auth provider instead?

```
name: oauth2
config:
    accessToken: foobar
    refreshToken: barfoo
    clientID: clientfoo
    clientSecret: asecret
    tokenEndpoint: https://github.com/login/oauth/access_token
```
