### ISSUE TITLE
Failed to negotiate an api version v1

### ISSUE THREAD

**Issue by DjangoPeng** [kubernetes/kubernetes#35576]
Everytime when I run `kubectl version`, I get the error:

```
error: failed to negotiate an api version; server supports: map[], client supports: 
map[authentication.k8s.io/v1beta1:{} componentconfig/v1alpha1:{} extensions/v1beta1:{} 
rbac.authorization.k8s.io/v1alpha1:{} autoscaling/v1:{} batch/v2alpha1:{} v1:{} policy/v1alpha1:{} 
federation/v1beta1:{} authorization.k8s.io/v1beta1:{} batch/v1:{} apps/v1alpha1:{}]
```

Version Info:
- Ubuntu 14.04 64bit
- latest version of k8s master branch
- docker v1.12.1

I login shell with user `dl`, and localhost is `9.91.9.130`.
rbac.yaml

```

---
kind: "ClusterRole"
apiVersion: "rbac.authorization.k8s.io/v1alpha1"
metadata:
  name: "admin"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
    nonResourceURLs: ["*"]

---
kind: "ClusterRoleBinding"
apiVersion: "rbac.authorization.k8s.io/v1alpha1"
metadata:
  name: "admin"
subjects:
  - kind: "User"
    name: "pjt"
roleRef:
  kind: "ClusterRole"
  apiVersion: "rbac.authorization.k8s.io/v1alpha1"
  name: "admin"
```

.kube/config

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: http://9.91.9.130:8080
  name: ubuntu
contexts:
- context:
    cluster: ubuntu
    user: ubuntu
  name: ubuntu
current-context: ubuntu
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    password: 2fO8rxXAHZs3OE1H
    username: admin
```

**Comment by zreigz** [comment]
I was trying reproduce the issue. First I had to modify `rbac.yaml` file because of validation problems:
```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
    nonResourceURLs: []
---
kind: "ClusterRoleBinding"
apiVersion: "rbac.authorization.k8s.io/v1alpha1"
metadata:
  name: admin
subjects:
  - kind: "User"
    name: "pjt"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: admin
```
I was using the latest master branch and I didn't notice any problems
