### ISSUE TITLE
federation service set default function not working properly

### ISSUE THREAD

**Issue by mfanjie** [kubernetes/kubernetes#35667]
related issues:
#28615
#35247

Steps to reproduce:
1. start federation apiserver
2. create a simple service profile which can be proceeded by kube-apiserver

```
apiVersion: v1
kind: Service
metadata:
  name: es1
  namespace: default
  labels:
    component: elasticsearch
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
```
1. the following error is shown

```
Service \"es1\" is invalid: [spec.ports[0].targetPort: Invalid value: 0: must be between 1 and 65535, inclusive, spec.ports[1].targetPort: Invalid value: 0: must be between 1 and 65535, inclusive, spec.sessionAffinity: Required value]
```
1. by investigating on the source code, the root cause should be SetDefaults_ServiceSpec is not being invoked properly.
2. the register.go has registered this function by the path
   `NewSchemeBuilder->addDefaultingFuncs->SetDefaults_ServiceSpec`, more investigation is needed.

@quinton-hoole @nikhiljindal
