### ISSUE TITLE
Service sessionAffinity with ClientIP 180 sec instead of minutes when using iptables proxy mode.

### ISSUE THREAD

**Issue by vincentheet** [kubernetes/kubernetes#35677]
**Kubernetes version**: 1.4.4

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **Kernel**: Linux gke-pool 3.16.0-4-amd64 1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

**What happened**: Session affinity is lost frequently when using a service to connect from a pod to another pod using a service with sessionAffinity: ClientIP on Kubernetes 1.4.4 with the iptables proxy mode.

**What you expected to happen**: Adhere to sessionAffinity: ClientIP setting and do not open/route connections to other endpoints off the service for this ClientIP.

**How to reproduce it**: Make a service with sessionAffinity set to ClientIP.

``` yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: galera-saf-cli
  name: galera-saf-cli
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    type: galera
  sessionAffinity: ClientIP
```

**Anything else do we need to know**:
It seems like the stickyMaxAgeMinutes is refactored to stickyMaxAgeSeconds in this commit: https://github.com/kubernetes/kubernetes/commit/8e503f3814a007408ce91572bd57c4749b6884d7

Where previously stickyMaxAgeMinutes was indeed incorrect since the setting was seconds there was a multiply of 60 to convert the property from seconds to minutes `info.stickyMaxAgeMinutes*60` on this line: https://github.com/kubernetes/kubernetes/commit/731d5e519139da63b1d551d45708484bbde4a9b8#diff-d51765b83fe795b469e8a86276b12dc9L513

In my opinion the behaviour should be that the stickiness is retained for 180 minutes instead of 180 seconds. The affinity is also 180 minutes in the kube-proxy implementation: https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/pkg/proxy/userspace/proxier.go#L356
