### ISSUE TITLE
mounting nfs volumes in pods is broken

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#35718]
https://github.com/kubernetes/kubernetes/pull/35652 broke mounting nfs volumes in pods:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - image: fedora:24
    name: fedora
    imagePullPolicy: Always
    command:
    - /usr/bin/sleep
    - "3600"
    volumeMounts:
    - name: myvol
      mountPath: /mnt
  volumes:
  - name: myvol
    nfs:
      path: /srv/share
      server: localhost
  terminationGracePeriodSeconds: 5
```

`kubectl create -f nfspod.yaml`

Stuck in `ContainerCreating`

`kubectl describe pod demo`

```
Events:
  FirstSeen LastSeen    Count   From            SubObjectPath   Type        Reason      Message
  --------- --------    -----   ----            -------------   --------    ------      -------
  14s       14s     1   {default-scheduler }            Normal      Scheduled   Successfully assigned demo to 127.0.0.1
  14s       6s      5   {kubelet 127.0.0.1}         Warning     FailedMount MountVolume.SetUp failed for volume "kubernetes.io/nfs/3cc8bac7-9c77-11e6-ae11-fa163e815edd-myvol" (spec.Name: "myvol") pod "3cc8bac7-9c77-11e6-ae11-fa163e815edd" (UID: "3cc8bac7-9c77-11e6-ae11-fa163e815edd") with: mount failed: exit status 32
Mounting command: mount
Mounting arguments: /localhost:/srv/share /var/lib/kubelet/pods/3cc8bac7-9c77-11e6-ae11-fa163e815edd/volumes/kubernetes.io~nfs/myvol nfs []
Output: mount.nfs: Failed to resolve server /localhost: Name or service not known
```

Note the leading `/` on the nfs server name.

@vishh @derekwaynecarr
