### ISSUE TITLE
source ip preservation on aws

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#35758]
We now have https://github.com/kubernetes/kubernetes/issues/19754#issuecomment-256837411

you can create a service like: 

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: echoheaders-nodeport
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
  labels:
    app: echoheaders-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30416
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders
```

And that will do what you expect (i.e traffic hitting the wrong node:nodeport gets blackholed, traffic hitting the right node is kept local). @justinsb will this just work with type=lb on aws?

**Comment by hjacobs** [comment]
@bprashanth this does not work on AWS at the moment as you can see from my bug report https://github.com/kubernetes/kubernetes/issues/35187

**Comment by bprashanth** [comment]
As discussed on the other issue, OnlyLocal solves the double hop issue on AWS.
We probably need to get at a header to actually figure out source ip (http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html#proxy-protocol or http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html).

**Comment by bonovoxly** [comment]
It would be nice if Kubernetes could use an external load balancer.  As of now, it appears you must use NodePort with the annotation `service.beta.kubernetes.io/external-traffic: OnlyLocal`.

So +1 to this.

**Comment by Phanindra48** [comment]
Hi @bprashanth, is there a way to get source ip in k8s cluster (v1.6.x) running in aws. I have raised a similar question in this https://github.com/kubernetes/features/issues/27 but couldn't resolve from the suggestions that I got. Any help/suggestions would be greatly appreciated.

**Comment by scribnar** [comment]
nginx gets load balancer IP, not client IP.

We use kubernets with kops/kubectl on aws with version 1.8.6

kubectl is 1.9.x

Followed this link. https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

We have this issue of not getting the client IP even after using below settings in nginx
	set_real_ip_from 0.0.0.0/0;
        real_ip_header X-Forwarded-For;
We also have set below in service config for nginx
type: LoadBalancer  
  externalTrafficPolicy: Local

Still the IP printed is of loadbalancer, not client.

It appears that the issue was logged 1.5 years back and I find discussions about this issue everywhere. However, there seem to be no fix for it in aws. Can anyone please confirm if its fixed or not? 

Geo detection of user is extremely important for us and it appears to me that it would be required by many applications. I am surprised this issue is not address properly even after many reports. Thanks.

**Comment by Phanindra48** [comment]
Try adding this  `service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'` to annotations in nginx service config like shown [here](https://github.com/kubernetes/ingress-nginx/blob/master/deploy/provider/aws/service-l4.yaml#L10)

**Comment by scribnar** [comment]
Thanks @Phanindra48. nginx is now getting the client IP as I can see it in access log of nginx. However, SSL stopped working. The browser throws error that it can't establish ssl connection to server. 

Here is service definition. We use nginx and rails inside a pod. NO ingress configurations. nginx has upstream configuration. SSL was working before well. If I remove the those two lines added to enable proxy protocol, then it works great. It would be great if you can direct me. Thanks.

`apiVersion: v1
kind: Service
metadata:
  name: cp-rails-service
  labels:
    app: cp
    platform: rails
  annotations:
    # Enable PROXY protocol
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    # Increase the ELB idle timeout to avoid issues with WebSockets or Server-Sent Events.
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'  
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 30080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 30443
  type: LoadBalancer  
  #externalTrafficPolicy: Local
  selector:
    app: cp-rails-pod`

**Comment by Phanindra48** [comment]
We are on version 1.7.11 and here is how my config looks like.

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  labels:
    app: nginx-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: nginx-ingress
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
      - name: nginx-ingress
        image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.11
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=nginx-ingress/nginx
```

I'm really not sure if it has to do anything with newer version.
