### ISSUE TITLE
dnsPolicy=ClusterFirst does not work when hostNetwork=true

### ISSUE THREAD

**Issue by ligc** [kubernetes/kubernetes#35761]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 
https://github.com/kubernetes/kubernetes/issues/17406 is the only one I found that might be related, I think this is a feature request to implement the dnsPolicy support.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

Kubernetes version: 1.3.6

```
root@c910f04x19k07:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"cfc-0.1.0-dirty", GitCommit:"7577a50e5c71505e3458884f83590270bb693351", GitTreeState:"dirty", BuildDate:"2016-10-25T17:24:22Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
root@c910f04x19k07:~# 
```

**Environment**:
- **Cloud provider or hardware configuration**: hardware configuration
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Linux c910f04x19k07 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Run kubernetes in containers
- **Others**:

**What happened**:

For some service discovery issue with the software I am running, I have to run some PODs with hostNetwork=true, however, I still need to have the POD access the other PODs through Kubernetes service, but it turned out that the dnsPolicy=ClusterFirst does not help, the POD uses the /etc/resolv.conf from the docker host and could not resolve the Kubernete service hostnames.

**What you expected to happen**:

With  hostNetwork=true and dnsPolicy=ClusterFirst,  the POD should use the kube-dns to resolve the hostnames in Kubernetes cluster.

**How to reproduce it** (as minimally and precisely as possible):

1 create the yaml file

```
root@c910f04x19k07:~/yaml# cat nginx.yaml 
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 8800
    targetPort: 80
  selector:
    app: my-nginx

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirst
      containers:
      - name: my-nginx
        image: nginx:1.8.1
        ports:
        - containerPort: 31556
root@c910f04x19k07:~/yaml# 
```

2 create the deployment and service

```
root@c910f04x19k07:~/yaml# kubectl create -f nginx.yaml 
service "my-nginx" created
deployment "my-nginx" created
root@c910f04x19k07:~/yaml#
```

3 Make sure the service and POD are up and running

```
root@c910f04x19k07:~/yaml# kubectl get service | grep my-nginx
my-nginx         20.0.0.66    <pending>     8800/TCP          31s
root@c910f04x19k07:~/yaml#
```

4 kubectl exec into the POD and try to access the Kubernete service nodename:

```
root@c910f04x19k07:~/yaml# kubectl get pod | grep nginx
my-nginx-103987416-1r8z6        1/1       Running   0          40s
root@c910f04x19k07:~/yaml#
root@c910f04x19k07:~/yaml# kubectl exec -it my-nginx-103987416-1r8z6 -- /bin/bash
root@c910f04x19k09:/# cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.2.1.2
search pok.stglabs.ibm.com
root@c910f04x19k09:/# ping my-nginx
ping: unknown host
```

5 Update the /etc/resolv.conf with the Kubernetes DNS and ping the service name again

```
root@c910f04x19k09:/#echo "search default.svc.cluster.local svc.cluster.local cluster.local pok.stglabs.ibm.com
nameserver 20.0.0.10
options ndots:5" > /etc/resolv.conf
root@c910f04x19k09:/#ping my-nginx
PING my-nginx.default.svc.cluster.local (20.0.0.66): 56 data bytes
^C--- my-nginx.default.svc.cluster.local ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
root@c910f04x19k09:/#

```

**Anything else do we need to know**:
