### ISSUE TITLE
How to create scheduledjobs using the API?

### ISSUE THREAD

**Issue by PierrickI3** [kubernetes/kubernetes#35822]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): ScheduledJobs API
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`): 1.4.1-beta.0.18

**Environment**:
- **Cloud provider or hardware configuration**: minikube 0.12.0
- **OS** (e.g. from /etc/os-release): Mac OS Sierra

**What happened**:

I am trying to create a scheduled job using the API (via kubectl proxy):

`curl -X POST http://localhost:8001/apis/batch/v2alpha1/scheduledjobs -d @testscheduledjob.yaml -H 'Content-type:application/yaml'`

Contents of testscheduledjob.yaml:

```
apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: hello
spec:
  schedule: 0/1 * * * ?
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

I get this error:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server does not allow this method on the requested resource",
  "reason": "MethodNotAllowed",
  "details": {},
  "code": 405
}
```

Is there a way to create a scheduled job other than using `kubectl` at the moment? 

**Anything else do we need to know**:

Trying to create a scheduledjob from inside a container
