### ISSUE TITLE
StorageClass deviates from API conventions

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#35874]
Maybe it's not a big deal, but StorageClass objects don't conform to the usual anatomy of k8s API objects. The `provisioner` and `parameters` fields are at the top level instead of being under a `spec` field.

Instead of this:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
```

It should be like this:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
spec:
  provisioner: kubernetes.io/gce-pd
  parameters:
    type: pd-standard
```

Feel free to close this if you think I'm being too petty. I just like my APIs nice and consistent :)
