### ISSUE TITLE
RBAC kubectl create failed : "error validating data: field apiGroup: is required"

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#35890]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.214+e4b41dd2920eb9", GitCommit:"e4b41dd2920eb98402d745931964f11279a9ff2e", GitTreeState:"clean", BuildDate:"2016-10-31T03:12:19Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.214+e4b41dd2920eb9", GitCommit:"e4b41dd2920eb98402d745931964f11279a9ff2e", GitTreeState:"clean", BuildDate:"2016-10-31T03:12:19Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu15.10
- **Kernel** (e.g. `uname -a`): 4.2.0-42-generic

**What happened**:
when I run `kubectl create -f rbac_resource.yaml`, I get a error.
```
clusterrole "admin-resource-role" created
error: error validating "rbac_resource.yaml": error validating data: field apiGroup: is required; if you choose to ignore these errors, turn validation off with --validate=false
```

rbac_resource.yaml 
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin-resource-role
rules:
- apiGroups: ["*"]
  verbs: ["*"]
  resources: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin-resource-binding
subjects:
  - kind: User # May be "User", "Group" or "ServiceAccount"
    name: test
roleRef:
  kind: ClusterRole
  name: admin-resource-role
```

if i run `kubectl create -f rbac_resource.yaml  --validate=false`, it works fine. 

Any help is appreciated, thank you!

**Comment by liggitt** [comment]
the apiGroup in the role ref is defaulted server side, but client-side validation doesn't know about that.

**Comment by george-angel** [comment]
Has this been fixed? Unsure why closed.

**Comment by liggitt** [comment]
The issue is with client side validation of required server-defaulted fields. There's not an issue with this field in particular.

**Comment by george-angel** [comment]
Is there a github issue for that then I could follow? Thanks.

**Comment by defunctzombie** [comment]
> The issue is with client side validation of required server-defaulted fields. There's not an issue with this field in particular.

Ok, so what is the fix? Just to ignore validation? When kubectl is run on what looks like a valid file, it errors out so from the user's perspective it looks like a ux bug or documentation issue. Is there a separate repo for kubectl that has an issue to follow?

**Comment by liggitt** [comment]
> Ok, so what is the fix? Just to ignore validation?

Yes. Client-side validation of server-defaulted fields is unlikely to work well.

> Is there a separate repo for kubectl that has an issue to follow?

https://github.com/kubernetes/kubernetes/issues/39434

**Comment by sellers** [comment]
Can someone verify that a valid way to remove this misleading message would be to ensure that the roleRef section looked like:

Leaving something with a warning and using --ignore-validation is a poor practice for anyone to get into.  It teaches poor behavior for users.  

```
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
```

**Comment by InAnimaTe** [comment]
`roleRef` in that format doesn't work for me either....from the default `ClusterRoleBinding` portworx provides:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: node-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-get-put-list-role
subjects:
- kind: ServiceAccount
  name: px-account
  namespace: kube-system

```
