### ISSUE TITLE
kube-proxy not redirect to correct node.

### ISSUE THREAD

**Issue by antonionappi88** [kubernetes/kubernetes#35973]
Hello there,

I'm trying to run a Kubernetes cluster on 4 VMs (one master and 3 minion).
I'm trying to deploy an application that is composed by 1 master and 2 servers.
The servers should be able to comunicate with the master also if they are on different minion using the Service Ip associate to the master.

This is the definition of the service of the Master of the application

```
apiVersion: v1                      
kind: Service                       
metadata:                           
  name: "container-master"        
  namespace: default                
spec:                               
  clusterIP: 10.254.3.160           
  ports:                            
  - name: "p0"                      
    nodePort: 0                     
    port: 52100                     
    targetPort: 8001                
    protocol: "TCP"                 
  selector:                         
    name: "container-master-pod"  

```

The Replication controller associated is : 

```
apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "container-master-controller"
  namespace: default
spec:
  replicas: 1
  selector:
    name: "container-master-pod"
  template:
    metadata:
      annotations:
          pod.beta.kubernetes.io/hostname: "master"
      labels:
        name: "container-master-pod"
    spec:
      containers:
      - name: "master"
        image: "MY_LOCAL_REGISTRY/master:latest"
        ports:
        - containerPort: 8001
          name: "c0"
        env:
        - name: "MASTER_HOST"
          value: "10.254.3.160"
        - name: "MASTER_PORT"
          value: "52100"
        resources:
          limits:
            memory: "2Gi"
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: mysecretkey
      restartPolicy: Always
```

I can connect to the clusterIP only from the node that hosts the Master but not from other minions.
The kube-proxy on the minions is configured like this : 

KUBE_PROXY_ARGS=" --healthz-port=0 --master=http://master-kubernetes:8080 --oom-score-adj=-999 --proxy-port-range=0-0 --proxy-mode=userspace"

Every time that i try to connect to 10.254.3.160:52100 it returns me a "Connection closed by foreign host."

I tried also to change the --proxy-mode to iptables but i cannot connect anyway to the service ip.
The problem is here I think  

[root@]# iptables-save | grep master
-A KUBE-PORTALS-CONTAINER -d 10.254.3.160/32 -p tcp -m comment --comment "default/container-master:p0" -m tcp --dport 52100 -j REDIRECT --to-ports 42291
-A KUBE-PORTALS-HOST -d 10.254.3.160/32 -p tcp -m comment --comment "default/container-master:p0" -m tcp --dport 52100 -j DNAT --to-destination LOCAL_MINION:42291

instead of local_minion it should be redirect to the minion that hosts the Master of the application.
The cluster is running 

Kubernetes Client and Server version : v1.2.0
Docker Client and Server version : 1.10.3
Docker API version : 1.22
OS : centOS 7

Thank you in advance.

Cheers,
Antonio
