### ISSUE TITLE
Volume that overrides a Dockerfile VOLUME doesn't mount into container

### ISSUE THREAD

**Issue by kennu** [kubernetes/kubernetes#3599]
I'm trying to start a MongoDB container which overrides the default data volume /data/db (specified by the image's [Dockerfile  VOLUME directive)](https://github.com/docker-library/mongo/blob/master/2.6/Dockerfile).

Kubernetes fails to mount the overridden volume from the path configured for the pod. Docker inspect shows that the volume is actually mounted from /var/lib/docker/vfs/dir/xxx, i.e. the default path.

For comparison, mounting another data volume with a different path in the same container works just fine. Also, running a similar container manually with Docker CLI works fine and mounts /data/db properly. SELinux doesn't seem to affect this but I've tried with "setenforce 0" just in case. My environment is Fedora 21 Atomic which uses Docker 1.4.0.

These are the relevant portions from "docker inspect" when the container is running:

```
"HostConfig": {
    "Binds": [
        "/var/lib/data/mongodb/data/db:/data/db",
        "/var/lib/data/mongodb/data/db2:/data/db2"
    ],
    "VolumesFrom": null
},
"Volumes": {
    "/data/db": "/var/lib/docker/vfs/dir/d0064b45422af35e836b39256233e616fb7909803e621e6a4006914c5b769ead",
    "/data/db2": "/var/lib/data/mongodb/data/db2"
},
"VolumesRW": {
    "/data/db": true,
    "/data/db2": true
}
```

The pod configuration looks like this:

```
apiVersion: v1beta1
kind: Pod
id: mongodb
labels:
  name: mongodb
desiredState:
  manifest:
    version: v1beta1
    id: mongodb
    volumes:
      - name: mongodb-data
        source:
          hostDir:
            path: /var/lib/data/mongodb/data/db
      - name: mongodb-data2
        source:
          hostDir:
            path: /var/lib/data/mongodb/data/db2
    containers:
      - name: mongodb
        image: mongo:2.6.6
        command: ['mongod', '--smallfiles']
        volumeMounts:
          - name: mongodb-data
            mountPath: /data/db
          - name: mongodb-data2
            mountPath: /data/db2
```
