### ISSUE TITLE
"delete patch type with no merge key defined" when removing mountPath

### ISSUE THREAD

**Issue by msmans** [kubernetes/kubernetes#36024]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

* `delete patch type with no merge key defined`
* `cannot apply deleted mountpath kubernetes`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: `AWS`
- **OS** (e.g. from /etc/os-release): `Arch Linux`
- **Kernel** (e.g. `uname -a`): `Linux niagara 4.8.4-1-ARCH #1 SMP PREEMPT Sat Oct 22 18:26:57 CEST 2016 x86_64 GNU/Linux`
- **Install tools**: `?`
- **Others**: `?`

**What happened**: After removing one of the pod container's `volumeMounts` from a deployment spec file and attempted to apply it using `kubectl apply -f test-deploy.yaml`, I got the following error message:

```
"test-deploy.yaml": delete patch type with no merge key defined
```

**What you expected to happen**: changes to take effect successfully

**How to reproduce it** (as minimally and precisely as possible):

1. Create a deployment below:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rm-mount-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        uid: abcdefght
    spec:
      containers:
      - name: debian
        image: debian
        args:
        - sleep
        - "100000"
        volumeMounts:
        - mountPath: /empty
          name: empty
        - mountPath: /empty2
          name: empty2
      volumes:
      - name: empty
        emptyDir:
      - name: empty2
        emptyDir:
```

Once successfully up, remove the lines below and use `kubectl apply` to update it:

```
        - mountPath: /empty2
          name: empty2
```

**Anything else do we need to know**:
