### ISSUE TITLE
multi container issue in pod 

### ISSUE THREAD

**Issue by kashifali94** [kubernetes/kubernetes#36348]
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    app: web
spec:
  containers:
    - name: key-value-store
      image: nginx
    - name: testcont
      image: nginx
  securityContext:
     seLinuxOptions:
       level: "s0:c11,c22"
```
This is my yaml file which i have created for multi container in pod i know container share the pod ip but is there anyway to specify the port for each container in pods because when i deploy pod one of the container is deployed and other don't and docker daemon gives me error 
016/11/02 11:03:11 [emerg] 1#1: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/11/02 11:03:11 [emerg] 1#1: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/11/02 11:03:11 [emerg] 1#1: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/11/02 11:03:11 [emerg] 1#1: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/11/02 11:03:11 [emerg] 1#1: bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
2016/11/02 11:03:11 [emerg] 1#1: still could not bind()
nginx: [emerg] still could not bind()
so cacn anyone help i need to slove it as sson as possible
