### ISSUE TITLE
Shouldn't count the time in pause phase for perma-failed deployment

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#36427]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 
perma-failed deployment

**Kubernetes version** (use `kubectl version`):
v1.6.0-alpha.0.191+a132e5c5800108

**What happened**:
Shouldn't count the time in pause phase for perma-failed deployment.

**How to reproduce it** (as minimally and precisely as possible):
1. Create deployment by deployment-perme-failed-1.yaml and pause the deployment immediately.
```
$ kubectl create -f deployment-perme-failed-1.yaml; kubectl rollout pause deployment/hello-openshift
```
```
# cat deployment-perme-failed-1.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-openshift
spec:
  progressDeadlineSeconds: 30
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift:123
        ports:
        - containerPort: 80
```

2. After 30 seconds, check deployment status. 
```
$ kubectl describe deployment/hello-openshift
Conditions:
  Type        Status    Reason
  ----        ------    ------
  Available     False    MinimumReplicasUnavailable
  Progressing     Unknown    DeploymentPaused
```

```
$ kubectl get deployment/hello-openshift -o yaml
  status:
    conditions:
    - lastTransitionTime: 2016-11-08T08:20:41Z
      lastUpdateTime: 2016-11-08T08:20:41Z
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: 2016-11-08T08:20:41Z
      lastUpdateTime: 2016-11-08T08:20:41Z
      message: Deployment is paused
      reason: DeploymentPaused
      status: Unknown
      type: Progressing
    observedGeneration: 2
    replicas: 3
    unavailableReplicas: 3
    updatedReplicas: 3
```

3. Resuming the deployment
```
$ kubectl rollout resume deployment/hello-openshift
```

**Actual results**:
3. The type of `Progressing` change to `false` and `ProgressDeadlineExceeded` immediately after resume deployment.
In describtion of deployment:
```
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	False	MinimumReplicasUnavailable
  Progressing 	False	ProgressDeadlineExceeded
```

**Expected results**: 
3.1 Conditions should be as below after resume deployment. 
```
Conditions:
  Type        Status    Reason
  ----        ------    ------
  Available     False    MinimumReplicasUnavailable
  Progressing     True    ReplicaSetUpdated
```

3.2 After 30 seconds, the type of `Progressing` change to `false` and `ProgressDeadlineExceeded`.
```
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	False	MinimumReplicasUnavailable
  Progressing 	False	ProgressDeadlineExceeded
```

**Anything else do we need to know**:
We should concern how to count times for below three scenarios:
1. `progressDeadlineSeconds: 30`, deploy a deployment(with not exist pod image), pause deployment after 10 seconds, hold on 1mins in pause phase, what status after resume deployment?
2. `progressDeadlineSeconds: 30`, deploy a deployment(with not exist pod image), pause deployment after 10 seconds, hold on 5 seconds in pause phase, what status after resume deployment?
3. `progressDeadlineSeconds: 30`, deploy a deployment(with not exist pod image) and pause deployment immediately, hold on 1mins in pause phase, what status after resume deployment?
