### ISSUE TITLE
Volume stuck in attaching state when using multiple PersistentVolumeClaim

### ISSUE THREAD

**Issue by willis7** [kubernetes/kubernetes#36450]
I'm using Kube 1.4.5, and AWS storage.

When I try to attach multiple volumes using PVC's, one of the volumes consistently gets stuck in the attaching state whilst the other is successful.

Below are the definitions that I used.

_sonar-persistence.yml_
``` yaml

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: aws://eu-west-1a/vol-XXXXXXX
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extensions
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: aws://eu-west-1a/vol-XXXXXX
    fsType: ext4
```
_sonar-claim.yml_
``` yaml

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-extensions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
_sonar-deployment.yml_
``` yaml

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar
spec:
  replicas: 1
  template:
    metadata:
      name: sonar
      labels:
        name: sonar
    spec:
      containers:
        - image: sonarqube:lts
          args:
            - -Dsonar.web.context=/sonar
          name: sonar
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonar:5432/sonar
          ports:
            - containerPort: 9000
              name: sonar
          volumeMounts:
          - name: sonarqube-data
            mountPath: /opt/sonarqube/data
          - name: sonarqube-extensions
            mountPath: /opt/sonarqube/extensions
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data
        - name: sonarqube-extensions
          persistentVolumeClaim:
            claimName: sonarqube-extensions
```
The data volume always appears to be successful, and maybe coincidentally is first in the list. I have tried this multiple times but the result is always the same. 

The error message is as follows:
```
Unable to mount volumes for pod "sonar-3504269494-tnzwo_default(2cc5292c-a5d4-11e6-bd99-0a82a8a86ebf)": timeout expired waiting for volumes to attach/mount for pod "sonar-3504269494-tnzwo"/"default". list of unattached/unmounted volumes=[sonarqube-data sonarqube-extensions]
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "sonar-3504269494-tnzwo"/"default". list of unattached/unmounted volumes=[sonarqube-data sonarqube-extensions]
```

**Comment by eggie5** [comment]
I am experiencing this too on GKE 1.4.5

The pod mounts the PV initially then after some time, ostensibly after the pod is moved to a new node, the pod can't remount the PV as it's stuck on the last node.

**Comment by gnufied** [comment]
@willis7 what do you see when you do `kubectl describe pod sonar-3504269494-tnzwo_default` . Do you see any particular errors in the YAML?

I

**Comment by willis7** [comment]
@gnufied I dont still have this available as I took another approach, but there was no errors beyond what I shared above.

**Comment by gnufied** [comment]
@justinsb or @saad-ali I will take a stab at this.  Do assign this to me, if it is not a problem.

**Comment by whereisaaron** [comment]
We get this frequently with EBS PVC/PV voumes and see plenty of simialr reports. It usually starts when recreating a Pod ("Recreate" Strategy). The old Pod is torn down and the PV unmounted, then the PV is mounted on the new Pod (on same or different worker). It seems like quick unmount/mount can trigger the 'stuck attaching' issue, which AWS blames on reusing device names (or reusing them too quickly maybe):
https://aws.amazon.com/premiumsupport/knowledge-center/ebs-stuck-attaching/

A temporary fix is to tell AWS for force detach the drive, then wait, the new Pod will attach and recover with a few minutes. However next time you recreate that particular Pod you also most certainly get the same stuck. Once a instance+PV combo start doing this it seems to happen every time. The only long term fix I have found/seen is to reboot the worker node or to delete and recreate the PVC/PV.

It is a major hassle and we're looking to switch away from EBS to something more reliable for mounting, like EFS, NFS or GlusterFS.

I wondered about scaling the deployment to 0 instances first, waiting a while before redeploying. Not an attractive option though.

**Comment by saad-ali** [comment]
> @justinsb or @saad-ali I will take a stab at this. Do assign this to me, if it is not a problem.

Thanks @gnufied

> We get this frequently with EBS PVC/PV voumes and see plenty of similar reports. 

Sorry for the crappy experience! What version of kubernetes are you running?

I know @justinsb @jingxu97 have worked on a number of fixes to improve the AWS EBS experience. A big fix, https://github.com/kubernetes/kubernetes/pull/34859, went in to 1.4.6 and there are already fixes pending for 1.4.7: https://github.com/kubernetes/kubernetes/pull/36840

CC @kubernetes/sig-storage

**Comment by rootfs** [comment]
@willis7 
Can you provide `kubectl describe pvc` output and is it possible to share your controller log and kubelet log?

**Comment by saad-ali** [comment]
@willis7 and @eggie5 Could you also try 1.4.6+ if you get a chance and see if you get a repro there.

**Comment by eggie5** [comment]
@saad-ali upgraded to 1.4.6 today, i'll keep an eye on it...

**Comment by saad-ali** [comment]
@eggie5 Thanks!

**Comment by whereisaaron** [comment]
@saad-ali no need to apologize, even before k8s the 'stuck attaching' was a known EBS condition (hence the AWS FAQ). It was just that before k8s it came up less often because it was much less common to be unmounting and remounting EBS volumes between instances every few minutes when a k8s CD deployment happens :-) 

Thanks for the tip about the upcoming patches by @justinsb and @jingxu97. We create clusters using coreos kube-aws and latest release is 1.4.3 and master is 1.4.6 I think. Might test a 1.4.6 cluster if I can.

I see AWS EFS or similar as a more natural fit for smallish disk volumes for k8s anyway,
- no need to decide/estimate volume sizes ahead of time or resize later
- you can multiply mount, allowing more options for rolling deployments. 

Unfortunately EFS is taking its own sweet time to get to the southern hemisphere, like Java committee process slow :-P

**Comment by willis7** [comment]
Hey gang, @whereisaaron has summed up my scenario perfectly in his first post. I shall fire up another cluster, and see if this is resolved with the latest patches. Many thanks!

**Comment by gnufied** [comment]
I tried reproducing this with latest version and I think situation has defenitely improved. Here is my deployment file:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx2
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        run: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/opt1"
          name: pvol1
        - mountPath: "/opt2"
          name: pvol2
        - mountPath: "/opt3"
          name: pvol3
        - mountPath: "/opt4"
          name: pvol4
      volumes:
      - name: pvol1
        persistentVolumeClaim:
          claimName: "gnufied-vol1"
      - name: pvol2
        persistentVolumeClaim:
          claimName: "gnufied-vol2"
      - name: pvol3
        persistentVolumeClaim:
          claimName: "gnufied-vol3"
      - name: pvol4
        persistentVolumeClaim:
          claimName: "gnufied-vol4"
```

and I bumped nginx image verison so as to trigger new deployment. I couldn't reproduce it. So I think situation here has definitely improved in latest version.

If those - who are still seeing this problem can attach `kubelet.log` and `kube-controller-manager.log` that would be pretty helpful making this area robust.
