### ISSUE TITLE
Apply of configuration change on SVC does not remove previous selectors

### ISSUE THREAD

**Issue by nvnobelen** [kubernetes/kubernetes#36509]
BUG REPORT:

On apply of a svc configuration, the label **Selector** does not get updated correctly:

**Environment:**
Kubernetes: 1.3.6 (only tested in this version)

**Re-create by:**
Load first yaml:

```
kind: Service
apiVersion: v1
metadata:
  name: "redis-geo"
  namespace: ournamespace
spec:
  selector:
    app: "redis-geo"
  ports:
    - name: "redis-geo"
      protocol: "TCP"
      port: 6379
      targetPort: "redis-geo"
```

Results in:
```
Name:			redis-geo
Namespace:		ournamespace
Labels:			<none>
Selector:		app=redis-geo
Type:			ClusterIP
IP:			10.0.206.148
Port:			redis-geo	6379/TCP
Endpoints:		<none>
Session Affinity:	None
No events.
```

Then with kubectl apply -f run the following yaml:
```
kind: Service
apiVersion: v1
metadata:
  name: "redis-geo"
  namespace: ournamespace
spec:
  selector:
    role: "redis-geo"
  ports:
    - name: "redis-geo"
      protocol: "TCP"
      port: 6379
      targetPort: "redis-geo"
```

Results in:
```
Name:			redis-geo
Namespace:		adserving
Labels:			<none>
Selector:		app=redis-geo,role=redis-geo
Type:			ClusterIP
IP:			10.0.206.148
Port:			redis-geo	6379/TCP
Endpoints:		<none>
Session Affinity:	None
No events.
```

**While the expected result was:**
```
Name:			redis-geo
Namespace:		ournamespace
Labels:			<none>
Selector:		role=redis-geo
Type:			ClusterIP
IP:			10.0.141.183
Port:			redis-geo	6379/TCP
Endpoints:		10.144.16.10:6379
Session Affinity:	None
No events.
```

See **Selector:** for the differences:
The apply added a "role=redis-geo" to the selector instead of replacing the selector.

**Work around & severity:**
Unload the service and reload the service. This works OK when you do not have a GLB setup in your service but will be 100% destructive on external IP addresses and DNS configurations if you do have this in the service configuration, making this a potentially blocking issue on service changes in more advanced service configurations.
