### ISSUE TITLE
GCE ingress with routes always falls back to default-http-backend

### ISSUE THREAD

**Issue by Iulian7** [kubernetes/kubernetes#36572]
This is cross-posted on stackoverflow (http://stackoverflow.com/questions/40518095/gce-ingress-with-routes-always-falls-back-to-default-http-backend). However, I am also writing here because this may be a bug and if not may lead to better documentation or understanding of how ingress works. 

**Kubernetes version**: 1.4.5

**Environment**:
- **Cloud provider or hardware configuration**: Default GKE cluster managed by Google
- **OS** (e.g. from /etc/os-release): I am using macOS Sierra

I have a very simple service with `type: NodePort`. It only returns some text on `/info`. I am using the default GKE ingress controller (the L7 Google load balancer - https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce) with TLS. If I use the following ingress everything works as expected:

Working ingress
---------------

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: global-ingress
      namespace: global
      annotations:
        kubernetes.io/ingress.allow-http: "false"
    spec:
      tls:
      - secretName: tls-secret
      backend:
        serviceName: gate-front
        servicePort: 80

---

    curl -k https://130.211.39.140/info
    POD: gate-front-1871107570-ue07p
    IP: 10.0.2.26
    REQ: /info

---

    $ kubectl describe ing
    Name:			global-ingress
    Namespace:		global
    Address:		130.211.39.140
    Default backend:	gate-front:80 (10.0.2.25:8080,10.0.2.26:8080)
    TLS:
      tls-secret terminates
    Rules:
      Host	Path	Backends
      ----	----	--------
      *	* 	gate-front:80 (10.0.2.25:8080,10.0.2.26:8080)
    Annotations:
      backends:			{"k8s-be-31966--f3f0bf21d171a625":"HEALTHY"}
      https-forwarding-rule:	k8s-fws-global-global-ingress--f3f0bf21d171a625
      https-target-proxy:		k8s-tps-global-global-ingress--f3f0bf21d171a625
      url-map:			k8s-um-global-global-ingress--f3f0bf21d171a625

Broken ingress
--------------

However, if I introduce a rule and leave out the default backend, all requests return `default backend - 404`. 

    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: global-ingress
      namespace: global
      annotations:
        kubernetes.io/ingress.allow-http: "false"
    spec:
      tls:
      - secretName: tls-secret
      rules:
      - http:
          paths:
          - path: /gate
            backend:
              serviceName: gate-front
              servicePort: 80

---
    curl -k https://130.211.33.150/gate/info
    default backend - 404

---

    $ kubectl describe ing
    Name:			global-ingress
    Namespace:		global
    Address:		130.211.33.150
    Default backend:	default-http-backend:80 (10.0.2.3:8080)
    TLS:
      tls-secret terminates
    Rules:
      Host	Path	Backends
      ----	----	--------
      *
        	/gate 	gate-front:80 (<none>)
    Annotations:
      https-forwarding-rule:	k8s-fws-global-global2-ingress--f3f0bf21d171a625
      https-target-proxy:		k8s-tps-global-global2-ingress--f3f0bf21d171a625
      url-map:			k8s-um-global-global2-ingress--f3f0bf21d171a625
      backends:			{"k8s-be-31966--f3f0bf21d171a625":"HEALTHY","k8s-be-32552--f3f0bf21d171a625":"HEALTHY"}

If I add hosts and use `curl -k --resolve ...` I get the same behaviour. 

I went through the following documentation and examples:

- http://kubernetes.io/docs/user-guide/ingress/
- https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/README.md

Can anyone shed some light on this?

**Comment by huysamen** [comment]
I am experiencing the same issue.

**Comment by Gugic** [comment]
@Iulian7, @huysamen the thing is you need to use some kind of wildcard to attach desired path. Using "/gate" in path will work only for exact "/gate" endpoint and will not work for "/gate/info". So you should use "/gate/*". 

It's actually not clear from documentation, because almost all examples contains strict endpoints.

**Comment by ChrisTerBeke** [comment]
Still having this issue on 1.8.4-gke.1. This is my config:

``` yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "gce"
spec:
  backend:
    serviceName: helloworld
    servicePort: 80
  tls:
  - secretName: <redacted>
    hosts:
    - <redacted>
  rules:
  - host: <redacted>
    http:
      paths:
      - path: /helloworld
        backend:
          serviceName: helloworld
          servicePort: 80
      - path: /helloworld/*
        backend:
          serviceName: helloworld
          servicePort: 80
```

The default (root) url works, but any paths give me a 404.
