### ISSUE TITLE
Kubernetes Volumn HostPath on AWS EC2 is not working

### ISSUE THREAD

**Issue by anchitanc** [kubernetes/kubernetes#36641]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):HostPath  not working

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.4.5

**Environment**:
- **Cloud provider or hardware configuration**: Amazon EC2
- **OS** (e.g. from /etc/os-release): Linux
- **Kernel** (e.g. `uname -a`):Linux
- **Install tools**:
- **Others**:

**What happened**: Kubernetes Hostpath on AWS EC2 Volumn is not working

**What you expected to happen**:  i have some file in host vm which i would like to use in pods, but in pods is not sync those file.

**How to reproduce it** (as minimally and precisely as possible):

I am using Kubernetes in AWS EC2 i want to use EC2 instance directory (which has some properties file ) in pods, so i have below yml file.

```
[ec2-user@ip-XXX-XX-XX-XX symtmp]$ pwd
/symtmp
[ec2-user@ip-XXX-XX-XX-XX symtmp]$ ls
head.properties
[ec2-user@ip-XXX-XX-XX-XX symtmp]$
```

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: symserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: symserver
    spec:
      volumes:
      - name: symtmp
        hostPath:
          path: /symtmp
      containers:
      - name: symserver
        image:symserver:latest
        env:
        - name: JAVA_OPTS
          value: Ddatabase.url=amazonaws.com
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: symtmp
          mountPath: /symtmp
      securityContext:
        fsGroup: 1234
        supplementalGroups: [5678]
        seLinuxOptions:
          level: "s0:c123,c456"
```

But look like its no working i have logged in to pods to see if file is copied or not.

```
[ec2-user@ip-XXX-XX-XX-XX symtmp]$ kubectl exec -ti symserver -                                                                            - sh
# pwd
/symtmp
# ls
#
```

I am not sure why hostpath is no working directory is getting created in pod but i cant get the file in pods.

**Anything else do we need to know**:
