### ISSUE TITLE
Service port name still required on multiple ports

### ISSUE THREAD

**Issue by MeromTh** [kubernetes/kubernetes#36803]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**: `gke`
- **OS** (e.g. from /etc/os-release): `container-vm` `Debian GNU/Linux 7 (wheezy)`
- **Kernel** (e.g. `uname -a`): `Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux`

**What happened**:
I'm trying to use multi ports on service. Like this
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-namespace
spec:
  ports:
  - port: 49000
    targetPort: 8445
    nodePort: 30005
  - port: 49001
    targetPort: 9000
    nodePort: 30006
  type: NodePort
  selector:
    app: my-deploy
```
but, I got an errors
```bash
The Service "my-service" is invalid: 
* spec.ports[0].name: Required value
* spec.ports[1].name: Required value
```
In [document right here](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_serviceport)
"name" was not required
BUT, if I use only single port, it's working fine.

**What you expected to happen**:
Should work fine on multiple ports too.
