### ISSUE TITLE
StatefulSets with the same selector interfere with each other

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#36859]
**What happened**:
When two statefulsets are created with the same labels, only one manages to come up.
This is caused by the same issue as https://github.com/kubernetes/kubernetes/issues/36855#issuecomment-260828249.

**What you expected to happen**:
Two StatefulSets should be created, instead, one was created, and another was unable to come up.

```
~ kubectl get pods --watch
NAME      READY     STATUS    RESTARTS   AGE
ss2-0     1/1       Running   0          7s
ss2-1     1/1       Running   0          6s
ss2-2     1/1       Running   0          4s
NAME      READY     STATUS    RESTARTS   AGE
ss1-0     0/1       Pending   0          1s
ss1-0     0/1       Pending   0         1s
ss1-0     0/1       ContainerCreating   0         1s
ss1-0     1/1       Running   0         2s
ss1-0     1/1       Terminating   0         2s
ss1-0     1/1       Terminating   0         2s
ss1-0     0/1       Pending   0         0s
ss1-0     0/1       Pending   0         0s
ss1-0     0/1       ContainerCreating   0         1s
ss1-0     1/1       Running   0         2s
ss1-0     1/1       Terminating   0         2s
ss1-0     1/1       Terminating   0         2s
```

**How to reproduce it** (as minimally and precisely as possible):

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ss1
spec:
  serviceName: "ss1"
  replicas: 3
  template:
    metadata:
      labels:
        app: ss
    spec:
      containers:
      - name: alpine
        image: alpine
        command: 
        - /bin/sleep
        - "1000000"
```

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ss2
spec:
  serviceName: "ss2"
  replicas: 3
  template:
    metadata:
      labels:
        app: ss
    spec:
      containers:
      - name: alpine
        image: alpine
        command: 
        - /bin/sleep
        - "1000000"
```

**What we should be doing**:

- Do not filter on the label selector to find the pods associated with a PetSet.

cc @kubernetes/sig-apps
