### ISSUE TITLE
How to scope secrets to a set of pods

### ISSUE THREAD

**Issue by F21** [kubernetes/kubernetes#36856]
From my current understanding, once I create a secret using something like the following, it is available to all pods in the namespace if they mount it into an environment variable or volume:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: MWYyZDFlMmU2N2Rm
  username: YWRtaW4=
```

It would be nice if we could scope secrets to a deployment. In this case, the secrets can only be mounted into a volume or environment variables for the deployment. When the deployment is deleted, the secrets are also deleted. This way, another pod would not be able to get access to secrets owned by the deployment.

The current work around is to use an environment variable directly in the deployment configuration, but environment variables are very insecure because a user can easily see the secret in plain text if he/she retrieves the deployment as a yaml file from the api server.

**Comment by liggitt** [comment]
subdivision of secret access within a namespace is difficult to accomplish for someone who has the ability to create arbitrary pods. do you anticipate allowing users to create pods but not access secrets in a particular namespace?

**Comment by F21** [comment]
Not within a namespace, but within a deployment. I am thinking of something like this:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
secrets:
  - api_key:
    key: api_key_here
  - stripe_token:
    token: token_here
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
      - env:
           - name: API_KEY
             valueFrom:
               secretKeyRef:
                  name: api_key
                  key: key
        ports:
        - containerPort: 80
```
