### ISSUE TITLE
In upstream should set S_ISGID on the directory in volumes

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#36872]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): secret permission mode

**Kubernetes version** (use `kubectl version`):
version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.551+8fefda3bc3c134", GitCommit:"8fefda3bc3c134fbd29ec18c7b6b9bddb0add86d", GitTreeState:"clean", BuildDate:"2016-11-16T01:56:56Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **OS** (e.g. from /etc/os-release): Red Hat Enterprise Linux Server 7.2
- **Kernel** (e.g. `uname -a`): 3.10.0-327.22.2.el7.x86_64

**What happened**:
In upstream doesn't set S_ISGID on the directory in volumes. But, set S_ISGID on the directory in volumes in OCP.

**How to reproduce it** (as minimally and precisely as possible):
**1. Create a secret: `kubectl create -f secret.yaml`**

```
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  data-1: dmFsdWUtMQ0K
  data-2: dmFsdWUtMg0KDQo=
```

**2. Create a pod with default permission mode: `kubectl create -f secret-permission-pod.yaml`**

```
apiVersion: v1
kind: Pod
metadata:
  name: secret-permission-pod
spec:
  containers:
  - name: secret-permission-pod
    image: redis
    volumeMounts:
    - name: foo-volume
      mountPath: "/etc/foo"
  volumes:
  - name: foo-volume
    secret:
      secretName: test-secret
      defaultMode: 0400
```

**3. Check `/etc/foo` directory and files permission**

**Actual results**:
Doesn't set S_ISGID on the directory `/etc/foo`.

```
# ls -ld /etc/foo
drwxrwxrwt. 3 root root 120 Nov 16 02:23 /etc/foo                  <-- Doesn't set S_ISGID
# ls -l /etc/foo/..data/*
-r--------. 1 root root  9 Nov 16 02:23 /etc/foo/..data/data-1
-r--------. 1 root root 11 Nov 16 02:23 /etc/foo/..data/data-2
```

**Expected results**: 
Should set S_ISGID on the directory `/etc/foo`.

```
# ls -ld /etc/foo
drwxrwsrwt. 3 root root 120 Nov 16 02:23 /etc/foo                  <-- Set S_ISGID
# ls -l /etc/foo/..data/*
-r--------. 1 root root  9 Nov 16 02:23 /etc/foo/..data/data-1
-r--------. 1 root root 11 Nov 16 02:23 /etc/foo/..data/data-2
```

**Anything else do we need to know**:
You can refer to OCP bug: https://bugzilla.redhat.com/show_bug.cgi?id=1387306
Relate Kube PR: https://github.com/kubernetes/kubernetes/pull/36386
Relate Origin cherry-pick PR: https://github.com/openshift/origin/pull/11816

**Comment by qwang1** [comment]
Upstream(v1.6.0-alpha.0.551+8fefda3bc3c134) now has the same result with OCP 3.4.0.26.
@chengzhang1016 I think the authority difference was unaware of. 

In container as root:
# ls -ld /etc/foo
drwxrwxrwt. 3 root root 120 Nov 16 08:37 /etc/foo
Since it's root, unique root, unique group. It doesn't need Set S_ISGID.

As normal user:
$ ls -ld /etc/foo
drwxrwsrwt. 3 root 1000100000 120 Nov 16 10:01 /etc/foo
Need to set GID to distinguish/group and protect different users' operations.

Above are my understanding. Welcome for any comments.

**Comment by mdshuai** [comment]
@chengzhang1016 you need set fsGroup for pod :
```
apiVersion: v1
kind: Pod
metadata:
  name: secret-permission-pod
spec:
  containers:
  - name: secret-permission-pod
    image: redis
    volumeMounts:
    - name: foo-volume
      mountPath: "/etc/foo"
  volumes:
  - name: foo-volume
    secret:
      secretName: test-secret
      defaultMode: 0400
  securityContext:
    fsGroup: 1001
```
