### ISSUE TITLE
Service label selector issue to group pods

### ISSUE THREAD

**Issue by talk2vino** [kubernetes/kubernetes#36979]
**Kubernetes version** 

kubectl version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:

Kubernetes in AWS

The issue here is i am trying to have the service label selector like below

![selector](https://cloud.githubusercontent.com/assets/8231899/20380144/446d7dde-acc6-11e6-881a-6a62031bd8d3.png)

While doing this there is some issue while group the pods using the service selector.

Here is the steps i did,

Start the service layer and pod1

```
apiVersion: v1
kind: Service
metadata:
  name: userauthservice
  labels:
   app: userauthservice
   env: QA
   env: beta

spec:
  ports:
    - port: 8877
      name: userauthservice
  selector:
      app: userauthservice
      env: QA
      env: beta
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: userauthservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: userauthservice
        env: QA
    spec:
      containers:
        - image: x.x.x/userauthservice:1.1.4
          name: userauthservice

```

Pod started with the label env:QA

```
[root@localhost start]# kubectl get pods -l app=userauthservice,env=QA
NAME                    READY     STATUS    RESTARTS   AGE
userauthservice-440u0   1/1       Running   0          <invalid>
userauthservice-g1aiq   1/1       Running   0          <invalid>
```

While describe the service layer, it wont show the labels env: QA and neither the endpoints of "env=QA" pods.

```
kubectl describe service userauthservice
Name:                   userauthservice
Namespace:              default
Labels:                 app=userauthservice
                        env=beta
Selector:               app=userauthservice,env=beta
Type:                   ClusterIP
IP:                     10.0.108.6
Port:                   userauthservice 8877/TCP
Endpoints:              <none>
Session Affinity:       None

```

Now started the pod2 

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: userauthservice1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: userauthservice
        env: beta

    spec:
      containers:
        - image: x.x.x/userauthservice:1.1.4
          name: userauthservice

```

```
[root@localhost start]# kubectl get pods -l app=userauthservice,env=beta
NAME                     READY     STATUS    RESTARTS   AGE
userauthservice1-1od0d   1/1       Running   0          <invalid>
userauthservice1-mcys1   1/1       Running   0          <invalid>
```

Now the service describe command shows the endpoint of "env=beta" pods . It wont group the pods have the "env=QA"

```
[root@localhost start]# kubectl describe service userauthservice
Name:                   userauthservice
Namespace:              default
Labels:                 app=userauthservice
                        env=beta
Selector:               app=userauthservice,env=beta
Type:                   ClusterIP
IP:                     10.0.108.6
Port:                   userauthservice 8877/TCP
Endpoints:              10.244.0.17:8877,10.244.1.51:8877
Session Affinity:       None
```

Please apologize that i doing on the wrong way. 

I feel it should list all the 4 pods endpoints on the describe command.
