### ISSUE TITLE
Strategic patch forgets a edge case

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/kubernetes#37138]
Strategic patch doesn't work on an edge case:
```
original:
  mergingIntList:
  - 1

current:
  mergingIntList:
  - 1
  - 2

modified:
  {}
```
The expected state is:
```
  mergingIntList:
  - 2
```
But we get:
```
  {}
```
The cause is we send a patch looks like this which will delete the whole list.
```
  mergingIntList: null
```
The patch we should send is
```
  mergingIntList:
  - 1: null
  - 2: null
```
This case is not covered in #35647. We should add a test case in `strategicpatch`.

Similar issue has been found in list of maps.

cc @pwittrock
