### ISSUE TITLE
kubectl delete rc cloudn't  release rbd  volumn. 

### ISSUE THREAD

**Issue by sysit** [kubernetes/kubernetes#37268]
kubernetes version :  hyperkube:v1.4.6_coreos.0
OS: coreos stable  1185.3.0
ceph version:  10.2.3

I  want create elasticsearch service, and use rbd storage data.  the rc yaml:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-logging-v1
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: elasticsearch-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: gcr.io/google_containers/elasticsearch:v2.4.1
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
      volumes:
      - name: es-persistent-storage
        rbd:
          monitors:
          - 10.199.134.2:6789
          - 10.199.134.3:6789
          - 10.199.134.4:6789
          user: admin
          image: es-persistent-storage
          pool: kube
          secretRef:
            name: ceph-secret-admin
          fsType: xfs
          readOnly: false
```

I use `kubectl create -f  es-rc.yaml `create  it successful,   and  enter the pod can see the rbd volume mount sucessful.

but when I use `kubectl delete rc elasticsearch-logging-v1 ` , the rc and the pod is deleted ,but the rbd storage still mount on the k8s-node host. it didn't destory automated.

what wrong with me ?

**Comment by sysit** [comment]
If  diectly create pod , not rc,  it working properly on create and delete.

the yaml file :
```
apiVersion: v1
kind: Pod
metadata:
  name: ceph-rbd
spec:
  nodeSelector:
    kubernetes.io/hostname: 10.199.134.36
  containers:
  - name: cephrbd-rw
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 1; done
    volumeMounts:
    - mountPath: "/mnt/cephrbd"
      name: cephrbd
  volumes:
  - name: cephrbd
    rbd:
      monitors:
      - 10.199.134.2:6789
      - 10.199.134.3:6789
      - 10.199.134.4:6789
      user: kube
      image: img002
      pool: kube
      secretRef:
        name: ceph-secret-user
      fsType: xfs 
```
