### ISSUE TITLE
Allow item EnvVar be optional if user thinks it ok, and if referenced key in valueFrom (ConfigMap or Secrets) is missing

### ISSUE THREAD

**Issue by kad** [kubernetes/kubernetes#37448]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): EnvVar, optional, defaults, configmap

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0", GitCommit:"42fe4ab0270e44c750d77c682e2fcab394aeb392", GitTreeState:"clean", BuildDate:"2016-11-06T01:00:40Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: none
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
At the moment, all references described in EvnVars in Pod spec are mandatory.
In different cluster instances (private, public) it might require different content or even variable can be omitted, depending on ConfigMap content for this cluster.
If key is not present in ConfigMap, right now creation of the pod will fail.

**What you expected to happen**:
I'd like to extend syntax of   EnvVar/valueFrom to allow omitting variable if specified key not found in config map. or have some default value (e.g. "null" in yaml can be treated as "don't put this variable to container). Same in theory applicable to Secretes use cases.

Use case:
- cluster might have config map which describes proxy variables: http_proxy, https_proxy, no_proxy, etc.
- pod can reference it via
```yaml
env:
    - name: http_proxy
        valueFrom:
            configMapKeyRef:
                name: cluster-proxy-config
                key: http_proxy
            optional: true
    - name: https_proxy
        valueFrom:
            configMapKeyRef:
                name: cluster-proxy-config
                key: https_proxy
            optional: true
    - name: ftp_proxy
        valueFrom:
            configMapKeyRef:
                name: cluster-proxy-config
                key: ftp_proxy
            optional: true
    - name: no_proxy
        valueFrom:
            configMapKeyRef:
                name: cluster-proxy-config
                key: no_proxy
            optional: true
```

**How to reproduce it** (as minimally and precisely as possible):
```console
kubectl -f test-case.yaml
```

test-case.yaml:
```yaml
apiVersion: v1
data:
  proxy.http: http://example.com:8080
  proxy.https: http://example.com:8080
  proxy.no_proxy: .example.com,127.0.0.1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: envpod 
spec:
  containers:
    - name: envcontainer
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: http_proxy
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: proxy.http
        - name: https_proxy
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: proxy.http
        - name: ftp_proxy
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: proxy.ftp
        - name: no_proxy
          valueFrom:
            configMapKeyRef:
              name: proxy-config
              key: proxy.no_proxy
  restartPolicy: Never
```

Check that pod creation failed:
```console
kubectl describe pod envpod | grep Failed
```

**Anything else do we need to know**:
