### ISSUE TITLE
Readiness probe keeps running when the pod is ready

### ISSUE THREAD

**Issue by Nicofuma** [kubernetes/kubernetes#37450]
**Kubernetes version** (use `kubectl version`): v1.2.0-36

**Environment**:
- **Cloud provider or hardware configuration**: OpenShift Enterprise v3

**What happened**: 
I am using an OpenShift 3.2.0.44 platform (which is running Kubernetes master 1.2.0-36-g4a3f9c5).
On this platform I launched a POD with a single container, which has a readiness probe. My issue is that when the container is determined as being ready, I can see the process of the probe spawning regularly (according to the periodSeconds value)

Note: it seems that there is another issue with periodSeconds: I tried to set the following readiness probe and have a warning saying that my container didn't pass its readiness check. Considering the executed command, it looks like the first check will be spawned at least 3600 seconds after the creation of the container

```
              readinessProbe:
                exec:
                  command:
                    - "true"
                initialDelaySeconds: 30
                timeoutSeconds: 1
                periodSeconds: 3600
                successThreshold: 1
                failureThreshold: 1
```

**What you expected to happen**:
Once the pod is determined ready I am not expecting the readiness probe to keep being spawned (which eats up resources).

**How to reproduce it** (as minimally and precisely as possible):
Adds this readiness probe and looks at the /tmp/readiness file in the pod:
```
              readinessProbe:
                exec:
                  command:
                    - "bash"
                    - "-c"
                    - "echo test >> /tmp/readiness"
                initialDelaySeconds: 30
                timeoutSeconds: 1
                periodSeconds: 1
                successThreshold: 1
                failureThreshold: 1
```
You will see an entry appended to the file every second.

**Anything else do we need to know**:
I apologize if it has already been reported or fixed but I didn't see anything related in the changelog or in the issues.
