### ISSUE TITLE
HostPath PV recycler tries to download busybox image from gcr.io 

### ISSUE THREAD

**Issue by vbasem** [kubernetes/kubernetes#37461]
### **What happened**:
Being on a virtual machine with no internet, I have created few different PVs using hostpath with recycling policy set to recycle. When I delete these PVs, the recycle policy will try to download the busybox image from gcr.io and fail. I can override the template for one of the PVs using kube-controller-manager --pv-recycler-pod-template-filepath-hostpath,  but the rest of them will fail, as the volume needs to be defined in the template.

###  **What you expected to happen**:
being able to specify the image for the recycler or change the image pull policy to IfNotPresent, that way I can tag busybox from a private repo.

###  **How to reproduce it** (as minimally and precisely as possible):
1) Make sure you are unable to reach gcr.io
2) Define multiple PVs with hostpath and recycle as recycling policy. 
3) Delete the PVs.
4) PVs should now be in FAILED status 

###  **Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

###  **Environment**: VM
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.2.1511 (Core)
- **Kernel** (e.g. `uname -a`): 3.10.0-327.36.3.el7.x86_64
- **Install tools**: rpm

**Comment by xingzhou** [comment]
Let me take a look at it, if I can reproduce, will try to fix that.

**Comment by xingzhou** [comment]
@vbasem, I failed to reproduce the issue on my local environment, would you please share your recycler template file?

Here is my I did on my machine:
1. I was using ubuntu 16.04 and k8s code from master branch.
2. Started the k8s cluster without network connection on the machine and using .
3. Created a recycler pod template file by using "imagePullPolicy: Never" and the image is gcr.io/google_containers/busybox which is cached on the machine.
4. Created 6 hostPath pv and 6 PVC.
5. Delete all the PVC's to start the pv recycler.

I can see all the recycler started and destroyed successfully, after that, all the hostPath PVs are recycled and in available status.

**Comment by vbasem** [comment]
@xingzhou  thanks for looking into this.

Perhaps the issue has been my template, do you mind sharing the recylcer pod template . I can run my system with it and report back.

**Comment by xingzhou** [comment]
@vbasem, sure, here is what I'm using right now:
```
kind: Pod
apiVersion: v1
metadata:
  name: pv-recycler-1
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: pv-recycler
      image: gcr.io/google_containers/busybox
      imagePullPolicy: Never
      command: ["/bin/sh"]
      args: ["-c", "test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z \"$(ls -A /scrub)\" || exit 1"]
      volumeMounts:
      - mountPath: "/scrub"
        name: vol
  volumes:
    - name: vol
```
