### ISSUE TITLE
Ingress does not support several TLS certificates

### ISSUE THREAD

**Issue by ged15** [kubernetes/kubernetes#37518]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): `ingress` `tls`.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): 1.4

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: Currently Ingress resources can only have one TLS certificate configured:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  tls:
    - secretName: testsecret
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: s1
          servicePort: 80
  - host: bar.foo.com
    http:
      paths:
      - backend:
          serviceName: s2
          servicePort: 80
```

**What you expected to happen**: Would it make sense to have a TLS certificate per route rule. Something like this:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: foo.bar.com
    tls:
      - secretName: testsecret
    http:
      paths:
      - backend:
          serviceName: s1
          servicePort: 80
  - host: bar.foo.com
    tls:
      - secretName: testsecret
    http:
      paths:
      - backend:
          serviceName: s2
          servicePort: 80
```

I am not aware of the design decisions behind the current implementation so this might not make sense at all.
The reason I propose this is because I see Ingress'es as public IP addresses. You might want to have several public IPs pointing to your cluster but also only one IP and then have several hosts point to that IP.

Initially submitted at https://github.com/kubernetes/contrib/issues/2058, but per request of @aledbf, submitting here.

**Comment by bprashanth** [comment]
Cloudproviders don't really support muxing multiple certs onto a single lb, so your current options are: 
1. Create 2 ingresses with 2 certs (works everywhere)
2. Create 1 ingress with a wildcard or san (works everywhere)
3. Create 1 ingress with a list of certs with different hostnames, one per host (depends on backend implementation, cloud provider will simply pick the first cert and assume it's a san throwing a warning event)

In theory a backend can parse the hostnames out of the list of certs and use the right one with the right `Host` header.  

We don't put the cert in with the HTTP rules because encryption is handled at Layer 5. So:    

1. We'd need to repeat the same structs in a bunch of places for non-http protocols (dtls, just tcp + ssl etc)
2. Keeping the certs in a separate section also makes centralized validation and renewal easier, i.e I can write a letsencrypt controller that doesn't even care about the rules

Non-http ingress is being discussed here: https://github.com/kubernetes/kubernetes/issues/23291
More explicity ingress sharing is being discussed here: https://github.com/kubernetes/kubernetes/issues/30151

**Comment by admiralobvious** [comment]
@bprashanth There's an example on how to use multiple TLS certificates [here](https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx/examples/multi-tls) that @aledbf wrote. It actually lets you create the Ingress but it does not work as it uses the first certificate only.

When you describe the Ingress you actually see:
```
TLS:
  somedomain.io-cert terminates somedomain.io,www.somedomain.io
  api.somedomain.io-cert terminates api.somedomain.io
  otherdomain.com-cert terminates otherdomain.com,www.otherdomain.com
```
So it's almost there it seems.

**Comment by bprashanth** [comment]
What controller are you running? If you're runnign the nginx controller, it has nothing to do with gke or gce, it functions the same everywhere. If you're running the gce ingress controller, gce doesn't accept multiple certs. By default you get the gce controller on gce, if you want to deploy the nginx controller instead, you need to do: https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx#running-on-cloudproviders, eg https://github.com/kubernetes/contrib/blob/master/ingress/controllers/gce/BETA_LIMITATIONS.md#disabling-glbc

**Comment by bprashanth** [comment]
To clarify, we *don't* validate against a single cert, because it's 100% valid to use a list of certs and look them up in the backend. If you're interested in submitting a patch to the nginx backend, i'm sure @aledbf would be more than happy to guide you (assuming the nginx controller doesn't already handle this). 

You just need to read out the hostname from the provided certs and write the appropriate rules, eg
```go
const (
	keyFile  = "/tmp/nginx.key"
	certFile = "/tmp/nginx.crt"
	hostname = "nginxsvc"
)

func main() {
	cmd := fmt.Sprintf("openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout %v -out %v -subj \"/CN=%v/O=%v\"",
		keyFile, certFile, hostname)
	exec.Command("sh", "-c", cmd).Run()
	defer func() {
		exec.Command("rm", "-f", certFile, keyFile).Run()
	}()
	rawCert, _ := ioutil.ReadFile(certFile)
	cert, _ := pem.Decode(rawCert)
	x509Cert, _ := x509.ParseCertificate(cert.Bytes)
	if err := x509Cert.VerifyHostname(hostname); err != nil {
		log.Fatal(err)
	}
	log.Printf("successfully verified hostname %v in cert %v", x509Cert.Subject.CommonName, certFile)
}

```

The "write the appropriate rules" part won't work when using a cloudprovider lb (eg: GCLB, ELB) but you can still use something like nginx *on* a cloudprovider.

**Comment by ged15** [comment]
> Cloudproviders don't really support muxing multiple certs onto a single lb, so your current options are:
> 
> Create 2 ingresses with 2 certs (works everywhere)
> Create 1 ingress with a wildcard or san (works everywhere)
> Create 1 ingress with a list of certs with different hostnames, one per host (depends on backend implementation, cloud provider will simply pick the first cert and assume it's a san throwing a warning event)

@bprashanth I am lost now - which of these options are supported on GKE? :)

**Comment by bprashanth** [comment]
If you're running the nginx controller on GKE, you can do all of them
If you're using the normal GCE ingress controller on GKE, then options that say "(works everywhere)"

**Comment by cmluciano** [comment]
Is this still an issue?

**Comment by ged15** [comment]
Sorry for the lack of responsiveness. I've not worked with GKE and K8s Ingress integration with Google load balancer for a while so do not know whether this is still an issue. Will close.

**Comment by kzka90** [comment]
This is still a issue.

**Comment by noname85** [comment]
@ged15  This is still an issue. 
Please re-open this issue

**Comment by RaDiu5** [comment]
@ged15 can you reopen a ticket? This is still an issue

**Comment by pkdetlefsen** [comment]
Is this something that might get supported eventually? It would be a big plus to be able to put all your services, hosted on different domains using multiple certificates, behind a single Google Cloud Load Balancer using an Ingress.

Currently I can work around the issue by managing the additional certs manually, as it looks like the GCLB does support multiple certs and SNI. For now I will probably move towards using a SAN cert for most of the domains to avoid managing them manually, but that's not possible for all of them in my case unfortunately.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts: # First cert are managed automatically
    - my.domain.com
    - domain.com
    secretName: domain-tls
  - hosts: # Additional certs have to be added manually to the load balancer
    - other-domain.com
    secretName: other-domain-tls
  rules: ...
  backend: ...
```
