### ISSUE TITLE
RBAC Role not Working as expected

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#37565]
Kubernetes version: 1.4.0

Hello all, I nees some help setting up RBAC authorization mode in my cluster, I have the following role:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: aguia
  namespace: aguia
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
    nonResourceURLs: []
```

And this RoleBinding:

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: test.user@email.com
  namespace: aguia
subjects:
- kind: User
  name: test.user@email.com
roleRef:
  kind: Role
  namespace: aguia
  name: aguia
  apiVersion: rbac.authorization.k8s.io/v1alpha1
```

I expected user test.user@email.com to be able to do anything in namespace aguia, and currently, he can for example create secrets in that namespace but when he tries to modify a 
Deployment(create, edit or delete) then an unauthorized error appears:

```
The server does not allow access to the requested resource
```

Is that the expected behavior in that situation?
