### ISSUE TITLE
Annotation in Deployment is not propagated automatically to pods created

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#37666]
**What keywords did you search in Kubernetes issues before filing this one?** "annotations propagated to pods"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
If I pass annotations to deployment object meta it doesn't get propagated to pods but gets propagated to ReplicaSets. I need to pass it explicitly to a Pod Template to make it work . Is this fixed or am I doing something wrong . I am using 1.2.6

**Comment by krmayankk** [comment]
@kubernetes/sig-apps @janetkuo  since i earlier talked to you about it. Its not an urgent requirement for us, but it seems weird to have to copy the annotations explicitly and the Deployment doesnt automatically copy it to all its created pods, but only to replicasets and deployment objects

**Comment by kargakis** [comment]
There is not an easy way to propagate replica set annotations in pods and I am not sure we want to do it since they are not part of the pod template.

**Comment by mirague** [comment]
As part of "kube2iam" one needs to annotate pods to set the proper AWS IAM role. However, using deployments/replica sets we don't have direct access to the Pods being created dynamically.

How should this be managed?

**Comment by kargakis** [comment]
@mirague can't you set the annotations in the PodTemplate of your Deployment?

**Comment by mirague** [comment]
@kargakis How would one go about this? Couldn't find anything useful on the official docs on PodTemplates. 

Related: https://github.com/jtblin/kube2iam/issues/49

**Comment by kargakis** [comment]
Here's a Deployment that uses an annotation `mycustom`:`annotation` in the PodTemplate. This will be added in all Pods created by ReplicaSets owned by this Deployment.
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        mycustom: annotation
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
        ports:
- containerPort: 80
```
