### ISSUE TITLE
Allow PersistentVolumeClaim capacity increase on GCE or other platform that supports dynamic resizing

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#37705]
**FEATURE REQUEST**

When creating a pvc on container engine - with slow and fast storage classes set up - with following manifest automatic creation works perfectly.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-provisioning
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```

But when trying to increase the storage capacity and re-applying the manifest it returns the following error:

```
The PersistentVolumeClaim "test-pvc-provisioning" is invalid: spec: Forbidden: field is immutable after creation
```

Of course from the perspective of most persistent volumes that don't support dynamic resizing this makes sense, but on GCE where persistent disks can grow on the fly it would be very useful to be able to grow the size of the volume claim.

**Kubernetes version**

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:16:27Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**

Google Container Engine, GCI image
