### ISSUE TITLE
GCE PD still in use after Pod deleted during rolling Node upgrade

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#37984]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No,

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

* "already being used"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.2", GitCommit:"0776eab45fe28f02bbeac0f05ae1a203051a21eb", GitTreeState:"clean", BuildDate:"2016-11-24T22:35:03Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.1228+2212c421f6e10e", GitCommit:"2212c421f6e10e3bb7ff1e106f14dcd049990235", GitTreeState:"clean", BuildDate:"2016-12-02T17:27:41Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 7 (wheezy)
- **Kernel** (e.g. `uname -a`):
- **Install tools**: cluster/gce/upgrade.sh
- **Others**:

**What happened**:

A Pod with a PVC got deleted during a rolling Node upgrade. A controller recreated it on a different Node. The new Pod was unable to attach the PD because it was still marked as being in use by the previous Node:

```
Failed to attach volume "pvc-61045ddc-b8c7-11e6-bee7-42010a800002" on node "kubernetes-minion-group-yl0d" with: googleapi: Error 400: The disk resource 'kubernetes-dynamic-pvc-61045ddc-b8c7-11e6-bee7-42010a800002' is already being used by 'kubernetes-minion-group-c4x6'
```

The issue resolved itself after 7min. I was able to reproduce this based on https://github.com/kubernetes/kubernetes/issues/37585#issuecomment-264519943. Although it happened to a different pod this time, the delay was about the same (7-8min).

**What you expected to happen**:

The PD should mount to the new Node that the Pod has scheduled to, without such a long delay.

**How to reproduce it** (as minimally and precisely as possible):

1.  Start a v1.4.6 cluster on GCE.

1.  Create the following example PetSet and wait for all Pods to be Running.

    ```yaml
    # A headless service to create DNS records
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      ports:
      - port: 80
        name: web
      # *.nginx.default.svc.cluster.local
      clusterIP: None
      selector:
        app: nginx
    ---
    apiVersion: apps/v1alpha1
    kind: PetSet
    metadata:
      name: web
    spec:
      serviceName: "nginx"
      replicas: 5
      template:
        metadata:
          labels:
            app: nginx
          annotations:
            pod.alpha.kubernetes.io/initialized: "true"
        spec:
          containers:
          - name: nginx
            image: gcr.io/google_containers/nginx-slim:0.8
            ports:
            - containerPort: 80
              name: web
            volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      volumeClaimTemplates:
      - metadata:
          name: www
          annotations:
            volume.alpha.kubernetes.io/storage-class: anything
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
    ```

1.  Delete PetSet without cascading (keep the Pods).

    ```shell
    kubectl delete petset web --cascade=false
    ```

1.  Upgrade master to `v1.6.0-alpha.0.1228+2212c421f6e10e` with `cluster/gce/upgrade.sh`.

    ```shell
    git checkout release-1.5
    git pull upstream release-1.5
    cluster/gce/upgrade.sh -M v1.6.0-alpha.0.1228+2212c421f6e10e
    ```

1.  Create the following StatefulSet to adopt the Pods.

    ```yaml
    # A headless service to create DNS records
    apiVersion: v1
    kind: Service
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      ports:
      - port: 80
        name: web
      # *.nginx.default.svc.cluster.local
      clusterIP: None
      selector:
        app: nginx
    ---
    apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      name: web
    spec:
      serviceName: "nginx"
      replicas: 5
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: gcr.io/google_containers/nginx-slim:0.8
            ports:
            - containerPort: 80
              name: web
            volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      volumeClaimTemplates:
      - metadata:
          name: www
          annotations:
            volume.alpha.kubernetes.io/storage-class: anything
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
    ```

1.  Upgrade nodes to `v1.6.0-alpha.0.1228+2212c421f6e10e` with `cluster/gce/upgrade.sh`.

    ```shell
    cluster/gce/upgrade.sh -N v1.6.0-alpha.0.1228+2212c421f6e10e
    ```

1.  Check for Pods stuck in ContainerCreating. Look in the event log for `The disk resource ... is already being used by ...`

    ```
    NAME      READY     STATUS              RESTARTS   AGE
    web-0     1/1       Running             0          16m
    web-1     1/1       Running             0          15m
    web-2     0/1       ContainerCreating   0          4m
    web-3     1/1       Running             0          15m
    web-4     1/1       Running             0          15m
    ```

**Anything else do we need to know**:

* [kubectl describe pod on the stuck pod](https://gist.github.com/enisoc/5cc11b467e9e6b68ce09f1d6e23d8961)
* [kube-controller-manager.log](https://gist.github.com/enisoc/e0fe54d0dc22a9138adfe77f4c19ee63)
* [kubernetes-minion-group-c4x6 kubelet.log](https://gist.github.com/enisoc/970727bef695053dc5c583eb2d187642)
* [kubernetes-minion-group-yl0d kubelet.log](https://gist.github.com/enisoc/4dae9db18dbe6b563c88f13193debcd9)
