### ISSUE TITLE
Allow configuration of reclaim policy in StorageClass

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#38192]
Use case: as Kubernetes admin I want to define a StorageClass that provisions PVs with `PersistentVolumeReclaimPolicy = "Retain"` so users don't loose their data when they accidentally delete their PVCs.

**API changes:**

* Either "magic" annotation `kubernetes.io/reclaim-policy: Retain`
* Or a new StorageClass field `sc.PersistentVolumeReclaimPolicy: Retain`

**Requested actions:**

* Update the API.
* Update internal provisioning logic to respect this new annotation/field.
* Update docs.
* Announce that external provisioners need to respect this new annotation/field.

All these items are fairly easy if we agree on the design.

@kubernetes/sig-storage

**Comment by rootfs** [comment]
Along this line, I'd also want fsType (used by block volume plugins, such as ebs, pd, cinder, etc) to be configurable. It is default to ext4, and we have encountered format latency issues with ext4.

**Comment by gnufied** [comment]
There is already an issue open for allowing user to specify fsType - https://github.com/kubernetes/kubernetes/issues/37801

**Comment by eparis** [comment]
Do we ahve any interest in supporting the USER deciding if they want reclaim or delete? I think doing so would have DoS fears.

**Comment by thockin** [comment]
This doesn't seem unreasonable, but it does seem very niche.  Do you have real, rational user demand for this?

**Comment by jsafrane** [comment]
One guy asked for this on slack. I don't know how real or rational he was, he had good arguments (never trust users, some of them *will* delete PVCs)

**Comment by thockin** [comment]
Can we leave this open to accumulate feedback?

**Comment by wongma7** [comment]
Another person asked for this on slack. SC field sounds good to me! Don't think supporting users deciding the reclaim policy is needed. If an admin wants that, they could just create two near-identical Classes.

**Comment by Raffo** [comment]
+1, it would be good to have this. While we trust the users and don't allow the to do write operations with `kubectl`, in some cases we want to make sure data is never deleted.

**Comment by humblec** [comment]
+1. If we are placing this in 'SC', is it going to be a mandatory  or optional field ?  If optional, is it the plan to make 'delete' as default value ?

**Comment by jeffvance** [comment]
Wouldn't it be safer, if there is to be a default reclaimPolicy, to make it "Retain" so as not to inadvertantly delete customer data?

**Comment by akram** [comment]
@thockin Hi Tim, I guess a very valuable feedback relies on the fact that we also use storageClass for dynamic provisionning.
In the case of gluster, the reclaimPolicy is set to delete, and you can't change it, because the PV+PVC are automatically crated with this policy.
When delete the PV or PVC, both are remove, and the gluster volume delete as well.
This behaviour is very usefull in dev like environment, but in production, one would feel more confident in allowing it manually.

**Comment by thockin** [comment]
I am honored retain would be a very surprising (and different from beta,
hence warranting more beta?) default.

If we really need this field, I would argue it should default to Delete,
since the price.ary use case is provisioning.

**Comment by humblec** [comment]
@jsafrane looks like more users are requesting this functionality. It would be good if we can resume this thread.

**Comment by humblec** [comment]
```In the case of gluster, the reclaimPolicy is set to delete, and you can't change it, because the PV+PVC are automatically crated with this policy.
When deleting the PV or PVC, both are remove, and the gluster volume delete as well.```

@akram this is not specific to gluster. All the provisioners act the same way. Thats by design of storage class. This thread is a rethink of an enhancement.

**Comment by humblec** [comment]
Agreed totally with @thockin , If we are bringing this enhancement `delete` should be the default.

**Comment by xeor** [comment]
Making a user go through an extra step to delete her data sounds good. I imagine many newcomers being afraid of deleting the "wrong thing". This also sounds very plausible as a company policy for their internal install.

**Comment by chy168** [comment]
For my use case, I'd like to create StatefulSet to deploy db application. In this scenario, I would like the created PV default to Retain policy. If we could provide reclaim option to StorageClass, it would also benefit StatefulSetSpec.volumeClaimTemplates. After scale out SatefulSet, I won't patch the PV to persistentVolumeReclaimPolicy= Retain anymore.

**Comment by msvechla** [comment]
How can it be that this is not implemented yet. Seems to be a basic task to change the default reclaim policy for automatically provisioned volumes.

**Comment by krmayankk** [comment]
@thockin @jsafrane does Here is my take as we work on enabling all this for our internal customers. For dynamic provisioning, i see that the reclaim policy is not even exposed and always defaults to `delete`. Exposing through StoragePolicy makes sense, but it also means its the default for all dynamically provisioned volumes. What if i want to override it based on a per claim basis. It would be ideal to say in the PVC, what is the reclaim policy which overrides the default behavior of retain. This way, short term testing apps can invoke automatic GC/reclaim for their volumes. 

I think we can generalize to say there are some default params in StorageClass, which should be allowed to be overriden on a per claim basis as well, although its a bigger discussion because we dont want to expose storage impl details from PVC for sure.

**Comment by stevesloka** [comment]
I think we need a way to define the ReclaimPolicy as well. Do we all agree that this should be added? How can I help? Happy to work on a PR or something if we can agree on the implementation.

**Comment by gnufied** [comment]
There seems to be enough interest in this feature. @saad-ali @childsb lets schedule this for 1.8 milestone?

**Comment by galan** [comment]
@jsafrane Refering https://github.com/kubernetes/kubernetes/issues/38192#issuecomment-265390193 - Why should it not be correct to delete pvcs? The offical documentation is telling the users exactly this.

> Reclaiming
> When a user is done with their volume, they can delete the PVC objects from the API which allows reclamation of the resource. The reclaim policy for a PersistentVolume tells the cluster what to do with the volume after it has been released of its claim. Currently, volumes can either be Retained, Recycled or Deleted.

**Comment by jsafrane** [comment]
@galan It is correct to delete PVCs. But some users don't realize that they are going to loose data when they do it. Sometimes they delete and create random Kubernetes objects hoping it fixes something. They don't realize that PVCs are different to say Pods here. Reclaim policy "Retain" could help them a bit.

**Comment by dminkovsky** [comment]
Thank you for fixing this!

Does anyone know how to make the `StorageClass`es that comes provisioned with new clusters on GKE have `reclaimPolicy` not be `Delete` by default?

**Comment by chino** [comment]
Any reason that updating the storageClass reclaimPolicy is forbidden?

**Comment by gnufied** [comment]
It was recently fixed. In kube-3.9 you can edit update reclaimPolicy of a storageclass as expected.

**Comment by chino** [comment]
I just tried on 1.9.1 but it still rejected it.

**Comment by gertcuykens** [comment]
I am probably missing something here but why not adding the field to `volumeClaimTemplates` instead 
```
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        name: redis-cluster
    spec:
      accessModes: [ "ReadWriteOnce" ]
      persistentVolumeReclaimPolicy: Retain
      storageClassName: redis
      resources:
        requests:
          storage: 64Mi
```
for me `reclaimPolicy` vs `persistentVolumeReclaimPolicy` it is confusing and inconsistent when defining it at two place when you create a PersistentVolume manually 
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: redis
reclaimPolicy: Retain
provisioner: docker.io/local-storage

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis
  labels:
    app: redis
spec:
  capacity:
    storage: 64Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: redis
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-for-desktop
```
