### ISSUE TITLE
servicecontroller is not retrying on service status update

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#38349]
Found this while debugging an issue

kube-proxy depends on the status field of loadBalancer service to setup iptables rules. But servicecontroller sometimes failed to update status due to various reasons: 
The one I saw is due to update conflict.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L330
In this case, servicecontroller gives up immediately. 

But service status in cache has already been altered: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L361

Then the next round of service update, servicecontroller will skip
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L305

**Comment by bprashanth** [comment]
seems worthy of a 1.5.X fix, let me know if you're not doing this and I will. I'm going to try to get a repro first with some theories I have.

**Comment by bprashanth** [comment]
Basically it's too easy to trick the controller into thinking the Service doesn't change with create/delete cycles. This is why I wanted to beef up the restart testing around this controller in 1.5 but we didn't get a chance to finish it. 

save this as `/tmp/svc.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  name: echoheaders-lb
  labels:
    app: echoheaders-lb
spec:
  type: LoadBalancer
  #loadBalancerIP: "35.184.21.228"
  ports:
  - port: 80
    nodePort: 30415
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: echoheaders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.3
        ports:
        - containerPort: 8080
```

__1. Leak__

run this script
```shell
#! /bin/sh
REGION=us-central1

kubectl create -f /tmp/svc.yaml
UID_1=$(kubectl get svc echoheaders-lb -o jsonpath='a{$.ObjectMeta.uid}' | sed -e 's/-//g' | cut -c 1-32)
echo creating loadbalancer with uid $UID_1
sleep 5
kubectl delete -f /tmp/svc.yaml
kubectl create -f /tmp/svc.yaml
UID_2=$(kubectl get svc echoheaders-lb -o jsonpath='a{$.ObjectMeta.uid}' | sed -e 's/-//g' | cut -c 1-32)
echo creating loadbalancer with uid $UID_2

until kubectl get svc echoheaders-lb | awk '{ print $3 }' | tail -n +2 | grep -iv pending; do
    echo waiting for service to acquire IP
done

kubectl delete -f /tmp/svc.yaml

for uid in $UID_2 $UID_1; do
  until ! gcloud compute forwarding-rules describe $uid --region=$REGION 2>&1 > /dev/null; do
      echo waiting for cleanup of $uid
  done
done
```

What's happenening:
* first create happens
* the next delete and create come in while the gce cloudprovider is processing the first create
* the first create is associating a bunch of resources with the UID
* the new service has a different UID
* the service controller tries to create a second forwarding rule with the provided static ip, named after the second UID
* the final delete only purges the second UID 
* first UID loadbalancer resources are leaked

__2. Static-ip ends up in "pending"__

Now plug a static ip into the same svc.yaml as follows: 
```
$ gcloud compute addresses create test-ip --region=us-central1
NAME     REGION       ADDRESS        STATUS
test-ip  us-central1  35.184.21.228  RESERVED
```

And modify the yaml by removing the commented out `#loadBalancerIP` field. 
Run the same script.
This time the Servcie will never actually get an IP, it'll stay in <pending> forever.

What's happening: 
* same as first repro
* the first leaked forwarding-rule blocks the static-ip from actually getting used in the second forwarding-rule
* the Service never updates status

you end up the symptom described in other issues, ie:
```
NAME             CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
echoheaders-lb   10.0.19.213   <pending>     80:30415/TCP   5m
kubernetes       10.0.0.1      <none>        443/TCP        1d
```
