### ISSUE TITLE
 API Server Panic due to .... something something audit logs

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes/kubernetes#38716]
**Kubernetes version** (use `kubectl version`):
Unable to run kubectl version, but it's a 1.5.0 cluster.

**Environment**:
- AWS
- OS
NAME=CoreOS
ID=coreos
VERSION=1235.2.0
VERSION_ID=1235.2.0
BUILD_ID=2016-12-07-0039
PRETTY_NAME="CoreOS 1235.2.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
- **Kernel** (e.g. `uname -a`):
core@ip-172-24-240-20 /etc/kubernetes/manifests $ uname -a
Linux ip-172-24-240-20.cloud.nordstrom.net 4.8.6-coreos-r1 #1 SMP Wed Dec 7 00:29:42 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

**What happened**:
Api server crashes like so ...
```
I1213 18:15:04.798098       1 serve.go:93] Serving securely on 0.0.0.0:443
I1213 18:15:04.798272       1 serve.go:107] Serving insecurely on 127.0.0.1:8080
E1213 18:15:04.799460       1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
/usr/local/go/src/runtime/asm_amd64.s:479
/usr/local/go/src/runtime/panic.go:458
/usr/local/go/src/runtime/panic.go:62
/usr/local/go/src/runtime/sigpanic_unix.go:24
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/audit.go:119
/usr/local/go/src/net/http/server.go:1726
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:75
/usr/local/go/src/net/http/server.go:1726
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/requestinfo.go:45
/usr/local/go/src/net/http/server.go:1726
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107
/usr/local/go/src/net/http/server.go:1726
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:78
/usr/local/go/src/runtime/asm_amd64.s:2086
E1213 18:15:04.799738       1 panics.go:37] APIServer panic'd on GET /apis/extensions/v1beta1/thirdpartyresources: runtime error: invalid memory address or nil pointer dereference
goroutine 675 [running]:
runtime/debug.Stack(0x5ace780, 0xc4213d3500, 0x34d3646)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
k8s.io/kubernetes/pkg/genericapiserver/filters.WithPanicRecovery.func1.1(0x2e640e0, 0xc420018040)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:37 +0x74
k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0xc421563da0, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:52 +0xe5
panic(0x2e640e0, 0xc420018040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
k8s.io/kubernetes/pkg/apiserver/filters.WithAudit.func1(0x5ace780, 0xc4213d3500, 0xc420c390e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/audit.go:119 +0x49d
net/http.HandlerFunc.ServeHTTP(0xc420800000, 0x5ace780, 0xc4213d3500, 0xc420c390e0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/genericapiserver/filters.WithPanicRecovery.func1(0x5ace780, 0xc4213d3500, 0xc420c390e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:75 +0x24a
net/http.HandlerFunc.ServeHTTP(0xc420ba5f20, 0x7f668e329e10, 0xc420fb1c98, 0xc420c390e0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/apiserver/filters.WithRequestInfo.func1(0x7f668e329e10, 0xc420fb1c98, 0xc420c390e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/requestinfo.go:45 +0x212
net/http.HandlerFunc.ServeHTTP(0xc420ba5fb0, 0x7f668e329e10, 0xc420fb1c98, 0xc420c390e0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/api.WithRequestContext.func1(0x7f668e329e10, 0xc420fb1c98, 0xc420c390e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107 +0xef
net/http.HandlerFunc.ServeHTTP(0xc420bdcd40, 0x7f668e329e10, 0xc420fb1c98, 0xc420c390e0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP.func1(0xc420bdcd60, 0x5ad7c80, 0xc420fb1c98, 0xc420c390e0, 0xc421e08840)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:78 +0x8d
created by k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:80 +0x1db

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1637e9d]

goroutine 675 [running]:
panic(0x2e640e0, 0xc420018040)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0xc421563da0, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126
panic(0x2e640e0, 0xc420018040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
k8s.io/kubernetes/pkg/apiserver/filters.WithAudit.func1(0x5ace780, 0xc4213d3500, 0xc420c390e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/audit.go:119 +0x49d
net/http.HandlerFunc.ServeHTTP(0xc420800000, 0x5ace780, 0xc4213d3500, 0xc420c390e0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/genericapiserver/filters.WithPanicRecovery.func1(0x5ace780, 0xc4213d3500, 0xc420c390e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:75 +0x24a
net/http.HandlerFunc.ServeHTTP(0xc420ba5f20, 0x7f668e329e10, 0xc420fb1c98, 0xc420c390e0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/apiserver/filters.WithRequestInfo.func1(0x7f668e329e10, 0xc420fb1c98, 0xc420c390e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/requestinfo.go:45 +0x212
net/http.HandlerFunc.ServeHTTP(0xc420ba5fb0, 0x7f668e329e10, 0xc420fb1c98, 0xc420c390e0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/api.WithRequestContext.func1(0x7f668e329e10, 0xc420fb1c98, 0xc420c390e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107 +0xef
net/http.HandlerFunc.ServeHTTP(0xc420bdcd40, 0x7f668e329e10, 0xc420fb1c98, 0xc420c390e0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP.func1(0xc420bdcd60, 0x5ad7c80, 0xc420fb1c98, 0xc420c390e0, 0xc421e08840)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:78 +0x8d
created by k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:80 +0x1db
```

**What you expected to happen**:
The api server not to panic.

**How to reproduce it** (as minimally and precisely as possible):
My API-Server config:
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: "${hyperkube_image?:"hyperkube_image must be set"}"
    command:
    - /hyperkube
    - apiserver
    - --anonymous-auth=false
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
    - --allow-privileged=true
    - --apiserver-count=${control_plane_cluster_size?:"control_plane_cluster_size must be set"}
    - --audit-log-maxage=30
    - --audit-log-maxsize=100
    - --audit-log-path=/var/log/apiserver/audit.log
    - --authorization-mode=RBAC
    - --authorization-rbac-super-user=kube-apiserver.${private_fqdn?:"private_fqdn must be set"}
    - --bind-address=0.0.0.0
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --cloud-provider=aws
    - --etcd-cafile=/etc/ssl/etcd/ca.pem
    - --etcd-certfile=/etc/ssl/etcd/etcd_client.pem
    - --etcd-keyfile=/etc/ssl/etcd/etcd_client-key.pem
    - --etcd-servers=https://127.0.0.1:2379
    - --external-hostname=${private_fqdn?:"private_fqdn must be set"}
    - --runtime-config=rbac.authorization.k8s.io/v1alpha1,batch/v2alpha1,extensions/v1beta1/thirdpartyresources,policy/v1beta1
    - --secure-port=443
    - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --service-cluster-ip-range=${k8s_service_cluster_ip_range?:"k8s_service_cluster_ip_range must be set"}
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 443
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 1Gi
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/etcd
      name: ssl-certs-etcd
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: /var/log/apiserver
      name: apiserver-logs
      readOnly: false
  volumes:
  - hostPath:
      path: /etc/ssl/etcd
    name: ssl-certs-etcd
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  - hostPath:
      path: /var/log/apiserver
    name: apiserver-logs
```

**Anything else do we need to know**:
Disabling audit logs causes this to no blow up. I suspect calling the api on the secure port from the controller using credentials would also cause this not to explode.
