### ISSUE TITLE
StatefulSet Fails to Dynamically Create AWS EBS Volume

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes/kubernetes#38723]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.0", GitCommit:"58b7c16a52c03e4a849874602be42ee71afdcab1", GitTreeState:"clean", BuildDate:"2016-12-12T23:35:54Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/386"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.0+coreos.0", GitCommit:"0b9222468d0002ba678555ae903e91f346d92024", GitTreeState:"clean", BuildDate:"2016-12-13T02:16:08Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
AWS
- **OS** (e.g. from /etc/os-release):
```
core@ip-10-0-0-165 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1185.5.0
VERSION_ID=1185.5.0
BUILD_ID=2016-12-07-0937
PRETTY_NAME="CoreOS 1185.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
- **Kernel** (e.g. `uname -a`):
```
core@ip-10-0-0-165 ~ $ uname -a
Linux ip-10-0-0-165 4.7.3-coreos-r3 #1 SMP Wed Dec 7 09:29:55 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
```
- **Install tools**:
Terraform/Manual
- **Others**:

**What happened**:
```
$ kubectl describe pods
Name:		test-ebs-0
Namespace:	default
Node:		/
Labels:		app=test-ebs
Status:		Pending
IP:
Controllers:	StatefulSet/test-ebs
Containers:
 test-ebs:
   Image:	gcr.io/google_containers/test-webserver
   Port:
   Volume Mounts:
     /datadir from datadir (rw)
     /var/run/secrets/kubernetes.io/serviceaccount from default-token-9z6jv (ro)
   Environment Variables:	<none>
Conditions:
 Type		Status
 PodScheduled 	False
Volumes:
 datadir:
   Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
   ClaimName:	datadir-test-ebs-0
   ReadOnly:	false
 test-volume:
   Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
   ClaimName:	datadir
   ReadOnly:	false
 default-token-9z6jv:
   Type:	Secret (a volume populated by a Secret)
   SecretName:	default-token-9z6jv
QoS Class:	BestEffort
Tolerations:	<none>
Events:
 FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
 ---------	--------	-----	----			-------------	--------	------			-------
 29s		14s		6	{default-scheduler }			Warning		FailedScheduling	SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-test-ebs-0", which is unexpected

 $ kubectl describe pvc
Name:		datadir-test-ebs-0
Namespace:	default
StorageClass:	default
Status:		Pending
Volume:
Labels:		app=test-ebs
Capacity:
Access Modes:
Events:
 FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
 ---------	--------	-----	----				-------------	--------	------			-------
 36s		14s		3	{persistentvolume-controller }			Warning		ProvisioningFailed	no volume plugin matched
```

**What you expected to happen**:
EBS volume to be created dynamically

**How to reproduce it** (as minimally and precisely as possible):
Create StorageClass
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
```

Create StatefulSet
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: test-ebs
spec:
  serviceName: "test-ebs"
  replicas: 1
  template:
    metadata:
      labels:
        app: test-ebs
    spec:
      containers:
      - name: test-ebs
        image: gcr.io/google_containers/test-webserver
        volumeMounts:
        - name: datadir
          mountPath: /datadir
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: datadir
  volumeClaimTemplates:
  - metadata:
      name: datadir
      # annotations:
      #   volume.beta.kubernetes.io/storage-class: aws-ebs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

**Anything else do we need to know**:

IAM Policy
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["ec2:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": ["elasticloadbalancing:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": ["route53:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::kubernetes-*"
      ]
    }
  ]
}
```

IAM Role
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": { "Service": "ec2.amazonaws.com"},
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Started kubelet with `--cloud-provider=aws` flag
