### ISSUE TITLE
Fail to request secured kube-apiserver with certification files

### ISSUE THREAD

**Issue by tobegit3hub** [kubernetes/kubernetes#38749]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.1.34+700c1dc9fe78b6-dirty", GitCommit:"700c1dc9fe78b612dd59c2945777ea1fc715394e", GitTreeState:"dirty", BuildDate:"2016-07-15T01:01:47Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

**Environment**:
- **OS** CentOS 7
- **Kernel** 4.1.5-1.el7.centos.x86_64
- **Install tools**: yum

**What happened**:

We have followed the instructions to generate ssl certification files and setup the secured kube-apiserver. But the client kubectl fail to request with certification files. 

The log of `kubectl` looks like this.

![screen shot 2016-12-14 at 16 51 09](https://cloud.githubusercontent.com/assets/2715000/21175756/e6bb39ce-c21e-11e6-9954-06b31f9a641e.png)

And we have tried with `curl` and got these error.

![screen shot 2016-12-14 at 16 51 24](https://cloud.githubusercontent.com/assets/2715000/21175766/f4227a8c-c21e-11e6-8473-54d9e7627491.png)

The log of kube-apiserver looks like this.

![screen shot 2016-12-14 at 16 58 27](https://cloud.githubusercontent.com/assets/2715000/21175776/04f13e70-c21f-11e6-8a8e-9f2f7d708e25.png)

And here is our configuration of `~/.kube/config`.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/work/chendihao/kubernetes_ssl/ca.crt
    server: https://10.108.36.9:6443
  name: ubuntu
contexts:
- context:
    cluster: ubuntu
    auser: ubuntu
    user: ubuntu
  name: ubuntu
current-context: ubuntu
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    client-certificate: /home/work/chendihao/kubernetes_ssl/server.crt
    client-key: /home/work/chendihao/kubernetes_ssl/server.key
```
