### ISSUE TITLE
Documentation for built in docker registry produces a non-functional docker registry

### ISSUE THREAD

**Issue by lazzarello** [kubernetes/kubernetes#38849]
**Kubernetes version** (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): 
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- **Kernel** (e.g. `uname -a`): `Linux ip-10-53-83-178 4.4.23-k8s #1 SMP Fri Sep 30 13:51:02 UTC 2016 x86_64 GNU/Linux`
- **Install tools**: kops

**What happened**:

I installed the project's [built in docker registry](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry) for cluster image hosting. It deployed to each node. I could not access the registry from each node on http://localhost:5000 as documented.

```
$ kubectl describe service kube-registry --namespace=kube-system
Name:			kube-registry
Namespace:		kube-system
Labels:			k8s-app=kube-registry
			kubernetes.io/cluster-service=true
			kubernetes.io/name=KubeRegistry
Selector:		k8s-app=kube-registry
Type:			ClusterIP
IP:			100.71.167.69
Port:			registry	5000/TCP
Endpoints:		100.96.18.70:5000
Session Affinity:	None
No events.

$ kubectl describe rc --namespace=kube-system
Name:		kube-registry-v0
Namespace:	kube-system
Image(s):	registry:2
Selector:	k8s-app=kube-registry,version=v0
Labels:		k8s-app=kube-registry
		kubernetes.io/cluster-service=true
		version=v0
Replicas:	1 current / 1 desired
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Volumes:
  image-store:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	kube-registry-pvc
    ReadOnly:	false
No events.

$ kubectl describe pod kube-registry-proxy-ip-10-53-83-178.us-west-2.compute.internal --namespace=kube-system
Name:		kube-registry-proxy-ip-10-53-83-178.us-west-2.compute.internal
Namespace:	kube-system
Node:		ip-10-53-83-178.us-west-2.compute.internal/10.53.83.178
Start Time:	Thu, 15 Dec 2016 23:18:13 +0000
Labels:		<none>
Status:		Running
IP:		100.96.17.24
Controllers:	<none>
Containers:
  kube-registry-proxy:
    Container ID:	docker://b1844eb046d85a65a6545a1b906e8920133f168cd11a6a07a55058cccc6d1c25
    Image:		gcr.io/google_containers/kube-registry-proxy:0.3
    Image ID:		docker://sha256:b86ac3f11a0c35b480138b9c3a555c2d8abb5b40023df3dd257ce9d432ee6006
    Port:		80/TCP
    Limits:
      cpu:	100m
      memory:	50Mi
    Requests:
      cpu:		100m
      memory:		50Mi
    State:		Running
      Started:		Thu, 15 Dec 2016 23:59:27 +0000
    Ready:		True
    Restart Count:	0
    Environment Variables:
      REGISTRY_HOST:	kube-registry.kube-system.svc.cluster.local
      REGISTRY_PORT:	5000
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
No volumes.
QoS Tier:	Guaranteed
No events.
```

**What you expected to happen**:

To access the registry on each node at http://localhost:5000

**How to reproduce it** (as minimally and precisely as possible):

`curl http://localhost:5000` on each node

**Anything else do we need to know**:

I worked around this first by reading #38843 and second by changing the containerPort to 5000 after inspecting the network inside one of the proxy containers. There is no service listening on TCP port 80.

**Comment by nicerobot** [comment]
I've followed along but still can not access localhost:5000. I can only access it at the Endpoints, IP:5000, of the nodes themselves. I'm using the [coreos-vagrant multi-node cluster](https://coreos.com/kubernetes/docs/latest/kubernetes-on-vagrant.html) and am using a `volume: emptyDir` but otherwise it's that 👆 config. I'm unclear if this is something to do with CoreOS, maybe something to do with flannel?. But since I can't access it at localhost, i can't use the registry insecurely.

**Comment by ravishivt** [comment]
@nicerobot Same issue here.  I believe it's because of #23920, where the kube-registry-proxy daemonset requests hostPort 5000 but it doesn't actually bind on the host.  I'm using canal CNI.

I tried to switch from hostPort to hostNetwork but then I face another issue where the daemonset can not resolve the kube-registry hostname due to #17406.  So I then manually set REGISTRY_HOST to the service IP, but it still cannot access the service for some reason.  My host can access the service IP so I'm a bit lost on why kube-registry-proxy cannot, which is supposedly on the same network.

<details>
<summary>registry-ds.yaml</summary>

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-registry-proxy
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    version: v0.3
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        kubernetes.io/name: "kube-registry-proxy"
        kubernetes.io/cluster-service: "true"
        version: v0.3
    spec:
      hostNetwork: true
      containers:
      - name: kube-registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.3
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          # value: kube-registry.kube-system.svc.cluster.local
          value: 10.100.212.24
        - name: REGISTRY_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 5000
```
</details>

<details>
<summary>kubectl get pods --namespace=kube-system -l "k8s-app=kube-registry" -o wide</summary>

```
$ kubectl get pods --namespace=kube-system -l "k8s-app=kube-registry" -o wide
NAME                        READY     STATUS    RESTARTS   AGE       IP               NODE
kube-registry-proxy-b7z77   1/1       Running   0          15s       10.163.148.197   ravi-kube197
kube-registry-proxy-c3gms   1/1       Running   0          15s       10.163.148.196   ravi-kube196
kube-registry-proxy-psck4   1/1       Running   0          15s       10.163.148.198   ravi-kube198
kube-registry-v0-7wzq4      1/1       Running   0          47m       192.168.75.8     ravi-kube198
```
</details>

<details>
<summary>kubectl get service --namespace=kube-system -l "k8s-app=kube-registry"</summary>

```
$ kubectl get service --namespace=kube-system -l "k8s-app=kube-registry"
NAME            CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kube-registry   10.100.212.24   <none>        5000/TCP   36m
```
</details>


<details>
<summary>curl 10.100.212.24:5000/test</summary>

```
$ curl 10.100.212.24:5000/test
404 page not found
```
</details>


<details>
<summary>kubectl logs --namespace=kube-system kube-registry-proxy-b7z77 --tail=5</summary>

```
$ kubectl logs --namespace=kube-system kube-registry-proxy-b7z77 --tail=5
waiting for 10.100.212.24 to come online
waiting for 10.100.212.24 to come online
waiting for 10.100.212.24 to come online
waiting for 10.100.212.24 to come online
waiting for 10.100.212.24 to come online
```
</details>

<details>
<summary>curl localhost:5000</summary>

```
$ curl localhost:5000
curl: (7) Failed to connect to localhost port 5000: Connection refused
```
</details>
