### ISSUE TITLE
Ingress doesn't pick up healthcheck URL when using named port in readinessProbe

### ISSUE THREAD

**Issue by cblecker** [kubernetes/kubernetes#38850]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
readinessProbe
readinessProbe ingress

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+82450d0", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"not a git tree", BuildDate:"2016-12-14T04:09:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: gke
- **OS** (e.g. from /etc/os-release): 
```
BUILD_ID=8872.47.0
NAME="Container-VM Image"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=55
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Google Container-VM Image"
VERSION=55
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=gci
```
- **Kernel** (e.g. `uname -a`): `Linux gke-testcluster1-default-pool-28630e9c-5txn 4.4.21+ #1 SMP Thu Nov 10 21:43:53 PST 2016 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux`
- **Install tools**:
- **Others**:

**What happened**:
When using a named port in the readinessProbe, the Ingress doesn't pick up the custom URL for the healthcheck. Named ports appear to be supported, as described [here](http://kubernetes.io/docs/user-guide/liveness/).

**What you expected to happen**:
The Ingress create a GCE healthcheck using the custom URL, rather than defaulting to /.

**How to reproduce it** (as minimally and precisely as possible):
The below should work but does not. If you change line 22 to `port: 8080`, then it functions as expected.

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoheaders
spec:
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.4
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthcheck
            scheme: HTTP
            port: http

---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: echoheaders
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: nodeport-service
    servicePort: 8080
```

**Anything else do we need to know**:
