### ISSUE TITLE
BUG in kubernetes 1.3.5 use calico1.6 as network :service NodePort can not work when namespace isolation set

### ISSUE THREAD

**Issue by heartlock** [kubernetes/kubernetes#39065]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG

**Kubernetes version** (use `kubectl version`):v1.3.5

**Environment**:
- **Cloud provider or hardware configuration**:master:10.10.102.66  node1:10.10.102.67 mode2:10.10.102.68
- **OS** (e.g. from /etc/os-release):ubuntu14.04
- **Kernel** (e.g. `uname -a`):3.13.0-32-generic
- **Install tools**:
- **Others**:use calico1.6 & kube-proxy mode iptables

**What happened**:
install calico1.6 with kubernetes [http://docs.projectcalico.org/v1.6/getting-started/kubernetes/installation/](url)
I created namespace and service in this namespace use conf files as below:
```
kind: Namespace
metadata:
  name: net1-sub1
  labels:
    project: net1-sub1
  annotations:
    net.beta.kubernetes.io/network-policy: |
      {
        "ingress": {
          "isolation": "DefaultDeny"
        }
      }
```

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace: net1-sub1
  labels:
    ns: net1-sub1
spec:
  replicas: 2
  selector:
    rc: nginx
  template:
    metadata:
      labels:
        rc: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
```

```
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: net1-sub1
  labels:
    ns: net1-sub1
    svc: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    rc: nginx
```
from master(10.10.102.66) curl 10.10.102.67:30001 there is no response. In other words, if we set namespace isolation，service NodePort will not work. @caseydavenport

**Comment by resouer** [comment]
cc @thockin Would you mind to take a look to see if this is expected?

**Comment by caseydavenport** [comment]
@heartlock If I understand correctly, I think this is the expected behavior.

By setting DefaultDeny on the Namespace, you've said "don't allow any traffic to pods in this Namespace unless a NetworkPolicy says so", and that is the behavior you're seeing.

You'll need to create a NetworkPolicy in the net1-sub1 Namespace which allows the traffic in order to use NodePort services.

**Comment by heartlock** [comment]
@caseydavenport thanks for your reply! 

As you said

> You'll need to create a NetworkPolicy in the net1-sub1 Namespace which allows the traffic in order to use NodePort services.

so I need to create a NetworkPolicy to make backend pod to allow the traffic. Now we can add podIP  to whitelist by setting namespaceSelector and podSeletctor in NetworkPolicy spec. But these all traffic from inside the cluster. NodePort need to handle the traffic from outside the cluster. The key issue is that I can not find way to add external traffic to whitelist by setting  NetworkPolicy.

**Comment by thockin** [comment]
For some reason, I had it in my head that NetworkPolicy didn't apply to
NodePorts, but that seems silly.  You should be able to omit the 'from'
block of NetworkPolicy to allow traffic from anything.

**Comment by thockin** [comment]
Dup of #22469

**Comment by MikeSpreitzer** [comment]
Not exactly a _dup_ of #22469, because that issue is for tracking NetworkPolicy issues in general.

**Comment by MikeSpreitzer** [comment]
@heartlock You need a NetworkPolicy object that applies to the service pods you want to reach and does not restrict the remote peer (i.e., has no `from`).

**Comment by heartlock** [comment]
@MikeSpreitzer I create a NetworkPolicy as below : 
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
 name: test-network-policy
 namespace: net1-sub1
spec:
 podSelector:
  matchLabels:
 ingress:
```
But it not work. If ingress field is empty then this NetworkPolicy does not affect ingress isolation.
