### ISSUE TITLE
Proposal Quobyte tenants and Kubernetes namespaces

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubernetes#39101]
# Proposal Quobyte tenants and Kubernetes namespaces

We (@quolix and myself) developed an architecture/workflow to combine Quobyte tenants with Kubernetes namespaces (this is in the first place an proposal/draft and is open for discussions). 

Our Goals:

- Adding some simple "security" mechanisms
- Kubernetes Quobyte plugin decides which Quobyte tenant must be used
- A user shouldn't be able to modify the used Quobyte tenant
- A Quobyte Storage Class doesn't need to be configured with a tenant
- Easy to configure

## Our assumptions:

- Kubernetes namespace names are indiviual
- Kubernetes namespace == Quobyte tenant
- User access is restriced to namespaces otherwise the user can use all Quobyte Volumes / namespaces anyway
- If there is a Volume UUID specified, use the UUID instead of the Volume name (default case for dynamic provisioning)

### Dynamic Provisioning with Quobyte

1.) Admin creates an StorageClass with the following config

```yaml
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: slow
provisioner: kubernetes.io/quobyte
parameters:
    quobyteAPIServer: "http://138.68.74.142:7860"
    registry: "138.68.74.142:7861"
    adminSecretName: "quobyte-admin-secret"
    adminSecretNamespace: "kube-system"
    user: "root"
    group: "root"
    quobyteConfig: "BASE"

```
2.) User creates a PVC for a specific namespace

```json
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "claim1",
    "namespace": "test",
    "annotations": {
      "volume.beta.kubernetes.io/storage-class": "slow"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "3Gi"
      }
    }
  }
}

```

3.) Quobyte Plugin takes Kubernets namespace as Quobyte tenant
4.) Quobyte Plugin creates a Volume (auto generated name -> assume `testVolume`) in the tenant `test`
5.) User uses PVC in PodSpec (namespace must be the same otherwise it will fail)

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: server
  namespace: test
spec:
  replicas: 1
  selector:
    role: server
  template:
    metadata:
      labels:
        role: server
    spec:
      containers:
      - name: server
        image: nginx 
        volumeMounts:
          - mountPath: /var/lib/www/html
            name: quobytepvc
      volumes:
        - name: quobytepvc
          persistentVolumeClaim:
            claimName: claim1
```

6.) Quobyte Plugin takes Kubernets namespace as Quobyte tenant
7.) Quobyte Plugin resolves mountPath to `/var/lib/kubelet/plugins/kubernetes.io~quobyte/root#root#test@testVolume`

As a result we have a Quobyte Volume created in tenant `test`, an according PVC in namespace `test` and a Pod running in namespace `test` consuming the PVC.

### Volume Mount

1.) Quobyte Volume `testVolume` is created in Quobyte tenant `test`
2.) User has access to namespace `test`
3.) User creates PodSpec that uses the Volume above

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: server
  namespace: test
spec:
  replicas: 1
  selector:
    role: server
  template:
    metadata:
      labels:
        role: server
    spec:
      containers:
      - name: server
        image: nginx 
        volumeMounts:
          - mountPath: /var/lib/www/html
            name: quobytevolume
      volumes:
      - name: quobytevolume
        quobyte:
        registry: registry:7861
        volume: testVolume
        readOnly: false
        user: root
        group: root
```

4.) Quobyte Plugin takes Kubernets namespace as Quobyte tenant
5.) Quobyte Plugin resolves mountPath to `/var/lib/kubelet/plugins/kubernetes.io~quobyte/root#root#test@testVolume`

As a result we a Pod running in namespace `test` consuming a Quobyte Volume created for tenant `test`.

## Profit

- User can only use Volumes created in the namespace he has access to (simple/minimal ACL)
- Builtin Quobyte tenant and Kubernetes namespace mapping

We are open for discussions and improvements @kubernetes/sig-storage
