### ISSUE TITLE
Clarify container.name validation failures

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#39110]
create this deamonset
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: daemon-test
  labels:
    app: daemon-test
spec:
  selector:
    matchLabels:
      app: daemon-test
  template:
    metadata:
      labels:
        app: daemon-test
    spec:
      containers:
      - image: busybox
        command:
        - sleep
        - "36000"
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 20Mi
      restartPolicy: Always
```

with 
```console
$ kubectl create -f daemonset.yaml
error: error validating "/tmp/daemon.yaml": error validating data: field name: is required; if you choose to ignore these errors, turn validation off with --validate=false
```

Which is a confusing error. 
The code to change is: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L1717
It can mention that path of the parent object missing the name.
