### ISSUE TITLE
spec.initContainers[0].env[0].valueFrom.fieldRef.apiVersion: Required value

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#39189]
What?
The following pod yaml works on 1.4 cluster:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
      {
        "Name": "fun",
        "Image": "alpine",
        "Command": [
          "/bin/sh",
          "-c",
          "sleep 5"
        ],
        "Env": [
          {
            "Name": "MY_POD_IP",
            "ValueFrom": {
              "FieldRef": {
                "APIVersion": "",
                "FieldPath": "status.podIP"
              }
            }
          }
        ]
      }
    ]'
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```

However, creating it against 1.5.1 or master branch 84d0fbd gives the following error:
```
The Pod "nginx" is invalid: spec.initContainers[0].env[0].valueFrom.fieldRef.apiVersion: Required value
```

**Comment by philips** [comment]
cc @kubernetes/sig-api-machinery-misc

**Comment by smarterclayton** [comment]
Your annotations are wrong - you're using upper case field names instead of lower case field names - i.e. "Env" is not correct, but "env" is.

**Comment by smarterclayton** [comment]
If you serialized that from a go object, it means you are using the internal type (pkg/api) instead of the versioned type (pkg/api/v1), which was always subtly broken.  We removed the JSON fields to prevent accidents like this.

**Comment by philips** [comment]
@smarterclayton Since this used to work and no longer does can we add it to the [deprecations](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#deprecations)? I guess the entry would say:

    > The init-container (`pod.beta.kubernetes.io/init-containers`) annotations used to accept capitalized field names that could be accidently generated by the `k8s.io/kubernetes/pkg/api` package. This will now return an error like The Pod "nginx" is invalid: spec.initContainers[0].env[0].valueFrom.fieldRef.apiVersion: Required value

**Comment by smarterclayton** [comment]
Yeah - I'm curious as to how it worked before, because we invoked a
versioned decode from external (or should have) and either way only one
deserialization should have been possible (lower or upper, but not both).

On Dec 28, 2016, at 2:23 PM, Brandon Philips <notifications@github.com>
wrote:

cc @kubernetes/sig-api-machinery-misc
<https://github.com/orgs/kubernetes/teams/sig-api-machinery-misc>

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/39189#issuecomment-269526679>,
or mute the thread

**Comment by hongchaodeng** [comment]
@philips @calebamiles @smarterclayton 
Can we reopen this? Still doesn't work.

yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
      {
        "name": "fun",
        "image": "alpine",
        "command": [
          "/bin/sh",
          "-c",
          "echo $MY_POD_IP"
        ],
        "env": [
          {
            "name": "MY_POD_IP",
            "valueFrom": {
              "fieldRef": {
                "fieldPath": "status.podIP"
              }
            }
          }
        ]
      }
    ]'
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```

On 1.5:
```
The Pod "nginx" is invalid: spec.initContainers[0].env[0].valueFrom.fieldRef.apiVersion: Required value
```

Successful on 1.4
