### ISSUE TITLE
failed to authorize non-namespaced resource when use rolebinding

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#39194]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**: local cluster
- **OS** (e.g. from /etc/os-release):Fedora 24
- **Kernel** (e.g. `uname -a`):Linux nfs 4.7.7-200.fc24.x86_64 #1 SMP Sat Oct 8 00:21:59 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:hack/local-up-cluster.sh

**What happened**:
test.yaml
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: test
rules:
- apiGroups: ["*"]
  verbs: ["*"]
  resources: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin-resource-binding
subjects:
  - kind: Group # May be "User", "Group" or "ServiceAccount"
    name: test
roleRef:
  kind: Role
  name: test
```
can not get the permission to non-namespaced resource
```
# ./cluster/kubectl.sh --token=/test get no                  
Error from server (Forbidden): User "" cannot list nodes at the cluster scope.: "<nil>" (get nodes)
```
namespaced resource is fine
```
# ./cluster/kubectl.sh --token=/test get sa                  
NAME      SECRETS   AGE
default   1         1m
```

**How to reproduce it** (as minimally and precisely as possible):
The problem is that the namespace of non-namespaced resource is empty, so RulesFor() doesn't deal with rolebinding.
