### ISSUE TITLE
PVC w/ alpha storage-class annotation stuck in "cannot find volume plugin for alpha provisioning"

### ISSUE THREAD

**Issue by bluecmd** [kubernetes/kubernetes#39201]
**BUG**

Using Kubernetes 1.5.1 with Ceph RBD.

Storage Class:
```
[bluecmd-laptop]$ kubectl get storageclass --output=yaml
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1beta1
  kind: StorageClass
  metadata:
    annotations:
      storageclass.beta.kubernetes.io/is-default-class: "true"
    creationTimestamp: 2016-12-22T14:12:38Z
    name: generic
    namespace: ""
    resourceVersion: "2375670"
    selfLink: /apis/storage.k8s.io/v1beta1/storageclassesgeneric
    uid: b1ee8459-c850-11e6-b7c2-ac162d706004
  parameters:
    [ REDACTED ]
  provisioner: kubernetes.io/rbd
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
```

The following PVCs work just fine:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim-nothing
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```

Adding annotations to specify the storage class also works, but *only* if the annotation is using volume.beta.kubernetes.io:
```
annotations:
    volume.beta.kubernetes.io/storage-class: generic
```

**Problem: If using the following PVC, the PVC gets stuck.**

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-alpha-test
  annotations:
    volume.alpha.kubernetes.io/storage-class: generic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

```
[bluecmd-laptop]$ kubectl describe pvc test-claim-alpha-test
Name:		test-claim-alpha-test
Namespace:	default
StorageClass:	generic
Status:		Pending
Volume:		
Labels:		<none>
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  3s		3s		1	{persistentvolume-controller }			Warning		ProvisioningFailed	cannot find volume plugin for alpha provisioning
```

Compare with another claim using the beta annotation:
```
[bluecmd-laptop]$ kubectl describe pvc test-claim-beta
Name:		test-claim-beta
Namespace:	default
StorageClass:	generic
Status:		Bound
Volume:		pvc-3fe365fb-c918-11e6-8d1f-ac162d706004
Labels:		<none>
Capacity:	8Gi
Access Modes:	RWO
No events.
```

Hypothesis: Maybe RBD wasn't available in alpha and thus the alpha annotations only works for what was associated with the alpha to ensure compatibility (for good and for worse)?

**Comment by prat0318** [comment]
I am facing the same while installing MySQL with helm:
When trying `helm install stable/mysql`, pod always hangs in Pending state.
```
left-pig-mysql-2164587610-xddk9          0/1       Pending   0          14s
washed-marsupial-redis-626610541-qr8nh   0/1       Pending   0          1m
```
Looks like PersistentVolume is not able to be created by helm.

`kubectl describe pod mysql` gives:
```
Volumes:
  data:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	left-pig-mysql
    ReadOnly:	false
  default-token-rr96x:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-rr96x
QoS Class:	Burstable
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  28s		13s		6	{default-scheduler }			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "left-pig-mysql", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "left-pig-mysql", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "left-pig-mysql", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "left-pig-mysql", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "left-pig-mysql", which is unexpected.]
```

```
[root@kube01 ~]# kubectl describe pvc left-pig-mysql
Name:		left-pig-mysql
Namespace:	default
StorageClass:	default
Status:		Pending
Volume:
Labels:		app=left-pig-mysql
		chart=mysql-0.2.6
		heritage=Tiller
		release=left-pig
Capacity:
Access Modes:
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  17m		10s		72	{persistentvolume-controller }			Warning		ProvisioningFailed	cannot find volume plugin for alpha provisioning
```
