### ISSUE TITLE
possible to restrict access to hostpath volume mounts

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#39269]
**This is FEATURE REQUEST**

**Kubernetes version** (use `kubectl version`): 1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: openstack
- **OS** (e.g. from /etc/os-release): centos7

**What happened**: currently if user can create pod - he can also mount volumes using hostPath. However, that is pretty big security issue in shared(many projects with own namespaces) kubernetes cluster. User can for instance mount kubernetes node cloud-provider config inside his pod and get all information about credentials.

**What you expected to happen**: we should have possibility to restrict access to use hostpath in RBAC, or some other mechanism like hostPath is allowed only in kube-system namespace.

@liggitt any ideas to this?

**Comment by liggitt** [comment]
PodSecurityPolicy can be used to control which volume types are allowed to specific users or namespaces

**Comment by zetaab** [comment]
hmm, do you have idea what is wrong with following:

```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - 'emptyDir'
  - 'secret'
  - 'downwardAPI'
  - 'configMap'
  - 'persistentVolumeClaim'
  - 'cinder'
---
# restrictedPSP grants access to use
# the restricted PSP.
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: restricted-psp-user
rules: 
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - restricted
  verbs:
  - use
---
# restrictedPSP grants the restrictedPSP role to
# the groups restricted
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
    name: restricted-psp-users
subjects:
- kind: User
  name: "*"
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: restricted-psp-user
```

this should add role restricted-psp-user to all users? i am using this readme https://github.com/kubernetes/kubernetes/blob/master/examples/podsecuritypolicy/rbac/README.md 

However, when i deploy new nginx container and execute command kubectl get pod nginx -o yaml | grep psp i cannot see any psp added.
