### ISSUE TITLE
Confuse the rollout result after proportionally scale

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#39295]
Description of problem:
I noticed you have new PR (controller: scale proportionally before rolling out new templates): https://github.com/kubernetes/kubernetes/pull/32995
So I did below test, and want to discuss with you for step 3 and step7. In another word, I want to know how to rollout after scale proportionally. How to select which RS to do scaling down when new RS was created?

kubectl version: v1.6.0-alpha.0.2586+d4bf500e7340e6-dirty
docker version: 1.12.2-rc2

Steps to Reproduce:
1. Create a deployment with a RS: RS1=10
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-openshift
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift
        ports:
        - containerPort: 80
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
    type: RollingUpdate
```

2. Edit deployment ( change image to 'not-exist-1' )
Actual result:
RS1=8
RS2=5

3. Edit deployment: Scale + Update image ( change replicas to 30 and image to 'not-exist-2')
Actual result:
RS1=15
RS2=13
RS3=5

4. Pausing the deployment

5. Edit deployment: Scale + Update image ( change replicas to 50 and image to 'not-exist-3')
Actual result:
RS1=24
RS2=21
RS3=8

6. Resuming the deployment

7. Check replicas of RSs
Actual result:
Sometimes are:
RS1=24
RS2=16
RS3=8
RS4=5
Sometimes are:
RS1=19
RS2=21
RS3=8
RS4=5

Addition info: 
Follow your new PR 32995:
In Step 3: We actual did proportionally scale and then rolling out
3.1 proportionally scale
RS1=20
RS2=13
3.2 rolling out: RS1 scale down 5, RS3 scale up 5
RS1=15
RS2=13
RS3=5

Question: Why not is that RS2 scale down 5, RS3 scale up 5
RS1=20
RS2=8
RS3=5

In Step 7: Sometimes have different result
Result A: Caused by RS2 scale down 5, RS4 scale up 5
RS1=24
RS2=16
RS3=8
RS4=5

Result B: Caused by RS1 scale down 5, RS4 scale up 5
RS1=19
RS2=21
RS3=8
RS4=5

Question:Which one is correct? How to understanding the result?
