### ISSUE TITLE
Permissions 0755 instead of 0775 on gcePersistentDisk volumeMount with subPath

### ISSUE THREAD

**Issue by epall** [kubernetes/kubernetes#39474]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): gcePersistentDisk, fsGroup, permissions

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
whServer Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:43:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Google Cloud Platform
- **OS** (e.g. from /etc/os-release): OS X
- **Kernel** (e.g. `uname -a`): Darwin XXX 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
- **Install tools**: Google Cloud SDK
- **Others**:

**What happened**: The first time my pod comes up, the `volumeMount` lacks group write permission. The second time (after deleting the pod and letting the ReplicationController replace it), it is group-writable.

**What you expected to happen**: I expect the mount to be group-writable by the group specified in `securityContext.fsGroup` on the first instance of my pod.

Or maybe the group writability is the bug, and I should expect it to be 0755 every time.

What I definitely don't expect is the permissions changing between two instances of my pod template.

**How to reproduce it** (as minimally and precisely as possible):
```sh
gcloud compute disks create --size=10GB --zone=us-west1-b k8s-repro-pd
gcloud container clusters create k8s-repro --machine-type n1-standard-1 --num-nodes 1
gcloud container clusters get-credentials k8s-repro
kubectl create -f repro.yaml
echo -n "Waiting for pod to come up..."; while ! kubectl get -o template pods --template '{{(index .items 0).status.phase}}' | grep Running; do sleep 1; echo -n .; done
kubectl exec `kubectl get -o template pods --template '{{(index .items 0).metadata.name}}'` -- ls -ld /data
# expected result:
drwxrwsr-x 2 root games 4096 Jan  5 01:27 /data
# actual result:
drwxr-sr-x 2 root games 4096 Jan  5 01:27 /data

kubectl delete pod `kubectl get -o template pods --template '{{(index .items 0).metadata.name}}'`
echo -n "Waiting for pod to be replaced..."; while ! kubectl get -o template pods --template '{{(index .items 0).status.phase}}' | grep Running; do sleep 1; echo -n .; done
kubectl exec `kubectl get -o template pods --template '{{(index .items 0).metadata.name}}'` -- ls -ld /data
# output:
drwxrwsr-x 2 root games 4096 Jan  5 01:27 /data
```

repro.yaml
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: gce-pd-repro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        foo: bar
    spec: 
      containers:
      - name: foo
        image: ubuntu:latest
        command: [ "sleep", "600"]
        volumeMounts:
        - name: pd-volume
          mountPath: /data
          subPath: data
      volumes:
      - name: pd-volume
        gcePersistentDisk:
          pdName: k8s-repro-pd
          fsType: ext4
      securityContext:
        fsGroup: 60
```

**Anything else do we need to know**:

If I don't use `subPath`, then the mount is `0775` (group-writable) on the fist try.

My goal here is to expose a `subPath` of a GCE persistent disk to a process running as non-root in a container.
