### ISSUE TITLE
There's no way to stop a job from restarting forever on failure, documentation is wrong

### ISSUE THREAD

**Issue by btipling** [kubernetes/kubernetes#39578]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): jobs, activeDeadlineSeconds, restartPolicy

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GCE
- **OS** (e.g. from /etc/os-release): macos
- **Kernel** (e.g. `uname -a`): darwin
- **Install tools**: N/A
- **Others**: N/A

**What happened**:
Created a job, specified activeDeadlineSeconds as per documentation [which explicitly says](http://kubernetes.io/docs/user-guide/jobs/#job-termination-and-cleanup):

> However, if you prefer not to retry forever, you can set a deadline on the job. Do this by setting the spec.activeDeadlineSeconds field of the job to a number of seconds. **The job will have status with reason: DeadlineExceeded. No more pods will be created, and existing pods will be deleted**.

What happened instead:

![2017-01-07 at 9 12 pm](https://cloud.githubusercontent.com/assets/249641/21747527/f84b7868-d51d-11e6-871e-5e0478a080bf.png)

**What you expected to happen**:

Job to not restart when `DeadlineExceeded` exceeded as per documentation.

**How to reproduce it** (as minimally and precisely as possible):

Create a job that exits with greater than exit code 0.

**Anything else do we need to know**:

Related issues:

https://github.com/kubernetes/kubernetes/issues/24533
https://github.com/kubernetes/kubernetes/issues/30243

More...

**Comment by btipling** [comment]
My Yaml was:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: sphela-letsencrypt
spec:
  template:
    metadata:
      labels:
        run: sphela-letsencrypt
        app: sphela
    spec:
      activeDeadlineSeconds: 1
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: letsencrypt
        image: gcr.io/sphela-153202/sphela-letsencrypt:v6
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        command: [
          "/usr/local/bin/encrypt-script.sh"
        ]
      restartPolicy: Never
```
