### ISSUE TITLE
Invalid regexp for ingress host

### ISSUE THREAD

**Issue by sheerun** [kubernetes/kubernetes#39622]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "must match the regex"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.2-beta.0-dirty", GitCommit:"5f332aab13e58173f85fd204a2c77731f7a2573f", GitTreeState:"dirty", BuildDate:"2017-01-02T00:07:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:

Kubernetes shows wrong error message when creating ingress resource with invalid host. Accorting to id, a wildcard url is incorrect, but Kubernetes accepts following ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: deis
  name: deis
spec:
  rules:
  - host: "*.example.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: deis-router
          servicePort: 80
```

**What you expected to happen**:

An error message:

`The Ingress "deis" is invalid: spec.rules[0].host: Invalid value: "*.example.com": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')`

**Extra notes**:

I think it's fine to allow hosts with wildcard character, but please update the error message above with the true regexp.. e.g. `[a-z0-9\*]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*`
