### ISSUE TITLE
Better error message and documentation for RBAC config

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#39640]
Recently found examples on [kubernetes-incubator/cluster-proportional-autoscaler](https://github.com/kubernetes-incubator/cluster-proportional-autoscaler) not longer work on latest k8s cluster because of RBAC. While working on assigning this app an appropriate role I met a bit difficulty at the beginning.

Below ClusterRole was not working and led to below error message:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: cluster-proportional-autoscaler
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["replicationcontrollers"]
    verbs: ["get", "update"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create"]
```
```
E0109 21:25:43.067827       1 autoscaler_server.go:129] Update failure: the server does not allow access to the requested resource (get deployments.extensions nginx-autoscale-example)
```

Because this app uses things like `k.clientset.Extensions().Scales(...)...` to scale resources `Deployment`, `ReplicaSet` and `ReplicationController`, it turned out a working config should be like below:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: cluster-proportional-autoscaler
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["replicationcontrollers/scale"]
    verbs: ["get", "update"]
  - apiGroups: ["extensions"]
    resources: ["deployments/scale", "replicasets/scale"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create"]
```

Because the error message did not point the subresource out, it is not obvious for me to figure out this `/scale` suffix (found out by looking at the existing kube-system components in cluster). All I thought about before was may be I should add `extensions/v1beta1.Scale` to the rules, which did not work. Also, it is also not obvious what `subresource`s are available for a certain type of resource. The `Referring to Resources` section on [doc](http://kubernetes.io/docs/admin/authorization/) only mentions `pods/log` for `pods`. May be better document how to figure this out?

@kubernetes/sig-auth-misc
