### ISSUE TITLE
Feature Request: AWS EFS PVC and StatefullSet - PVCT support.

### ISSUE THREAD

**Issue by hsyed** [kubernetes/kubernetes#39753]
# Overview.

Some services are extremely well suited for use in EFS especially stateful sets (Elasticsearch, Kafka). Also addressing the messiness of all the helm charts creating 1gb PVC's which AWS users have to create EBS volumes for.

EFS NFS targets have previously required the AZ name in the target. This doesn't seem to be a requirement any longer. The target name is now of the following shape: `<EFS-ID>.efs.<REGION>.amazon.com`. 

This makes EFS useable as an NFS target realistically today as the target can float across failure domains. This also somewhat simplifies the work required for this feature. 

# How We Use EFS in our clusters. 

Our clusters currently use EFS in two ways. We have a `/data` directory and a `/meta` directory. The EFS drive is mounted at `/cluster` across the worker and control plane in the cluster. 

We have a mixture of EFS and EBS volumes in our clusters -- some of the EBS volumes should be run under EFS but we couldn't find a way to achieve it (these are standard NFS / docker issues). We manually create the directories following a naming scheme and use host paths for them in containers. This has the potential for race conditions with deployments -- So we currently follow conventions for making use of the drive (deployment size always 1, destroy deployment on update). We now use Statefull sets for the deterministic semantics. Sufficed to say we can't use this pattern for >1 replica StatefulSets.

# Proposal For Statefull Sets.

I propose support for automatic requisition of PVC's in EFS drives. A PVC in this case would just be a directory inside an EFS drive. The path exists of two parts, the base which is a cluster wide configuration and the per-volume part which is specified in the PVCT. 

## Deriving / Configuring Base Part:

This signifies the EFS drive the cluster should use and where the cluster specific partitioning should occur. This is to support multiple clusters per EFS drive as well as giving the administrator an opportunity to use the EFS drive for other purposes.

We could use a tag of the form "KubernetesCluster" : "<CLUSTER_NAME>:/<CLUSTER_NAME>/data". 

The value is a comma separated list. 

The first part in the value is the cluster id, the second part is a user specified location where partitioning can begin.

## Deriving the PVCT Part.

The suffix of the EFS storage path can be derived off the namespace name (or stateful set domain ? ), the container name and the stateful set ordinal. 

## Kubernetes Mechanics:

An AWS controller that manages discovering the EFS drives. It ensures the target path is present on the drive. This might just end up being a simple specialisation to the existing NFS controller. 

# Related issues: 

https://github.com/kubernetes/kubernetes/issues/28226

**Comment by hsyed** [comment]
I’ve discussed the feature with Justinb and I think there is a nice general solution to this problem. It involves a a new “meta” provisioner type to support sub-volumes.

# Sub-Volume Storage Class Provisioner:

This storage class partially delegates to existing provisioners and as such it is a meta provisioner. 

The configuration structure could look like this:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: standard
  namespace: qa
provisioner: kubernetes.io/sub-volume
parameters:
  type: kubernetes.io/nfs // I don’t know if an NFS provisioner currently exists.
  parameters:                    // parameters passed to the NFS provisioner.
    path: /pre-prod/qa             //  This is the root from which sub-volumes are created. 
                                               //  /pre-prod/qa are conventions used by the administrator in this example.
```

This provisioner can have a generic self-contained implementation for the most part. In the case of NFS the provisioner needs to be able to `mkdir-p` the root path, further specialisations for other existing provisioners are bound to crop up.

# Sub-Volume provisioning protocol for PV’s:

The provisioner expect a field “sub-volume.path:” in the PV. This should be general enough for use by a SS PVCT (dynamic) as well as for static provisioning. 

For dynamic provisioning a PVCT could just write a “sub-volume.path” regardless of provisioner type of the storage class — it would just be a hint. — e.g., <DOMAIN>/<SERVICE_NAME>/<ORDINAL>.
