### ISSUE TITLE
Feature request: support dns aliases for service 

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#39792]
**FEATURE REQUEST**

I'd like to be able to set custom hostnames in Kubernetes for a service besides the default my-service, my-service.my-ns and my-service.my-ns.svc.cluster.local so I can use the same dns name externally and internally, whereas the external dns record resolves to the public ip and the internal dns record resolves to the service cluster ip.

For our services of type LoadBalancer we create a LetsEncrypt certificate that runs in an HAProxy sidecar container for the application in that service. The hostname in the certificate matches the external hostname as set by us in a dns server external to Kubernetes.

Directly connecting to the service from another Kubernetes hosted application leads to a mismatch in hostname for the certificate. As any public certificate authority is not allowed to use internal host names in the certificates they generate this makes it hard to encrypt our internal Kubernetes traffic without using our own certificate signing service.

My proposal would be to allow something like the following

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-ns
spec:
  dnsAliases:
    - hostname: my-service.mydomain.com
    - hostname: my-service.mydomain.org
  selector:
    app: my-app
```

Where Kubernetes then automatically manages that **my-service.mydomain.com** and **my-service.mydomain.org** resolve to the clusterIP of my-service inside Kubernetes, independent from what they resolve to outside of the cluster. This wouldn't necessarily be tied to the type LoadBalancer, because we can use it to outfit our internal-only services with LetsEncrypt certificates as well.

Because of the requirement for the host to match the host in the certificate ticket https://github.com/kubernetes/kubernetes/issues/13748 wouldn't work for this specific scenario.

**Comment by JorritSalverda** [comment]
As a workaround is it possible to directly add dns records to kube-dns? Either by kubectl or directly via the Kubernetes api?

**Comment by r4j4h** [comment]
Speaking to your workaround:

> You can add a Service in kubernetes with clusterIP=None and an empty
selector, and then add an Endpoints object that has the IP you want. This
will make a kube-dns record for you. It's sort of a workaround, but it
should work for now.

[Source](https://github.com/kubernetes/kubernetes/issues/12337#issuecomment-218951154)

**Comment by liggitt** [comment]
> the same dns name externally and internally

not sure about that... isn't ingress intended to be used to surface services via external DNS names?

**Comment by JorritSalverda** [comment]
So far we hardly use ingress because of a number of reasons. 

- The health checks used by the L7 load balancer put a lot of load on our applications, scaling linearly with the number of nodes in a cluster. At least when we last looked at it.
- Ingress is L7 instead of L4; we currently do TLS termination in a sidecar container. So we don't really need L7, because it forces us to set the certificate in both the sidecar container and the ingress object to keep all traffic - including internal traffic - encrypted.
- L7 load balancer on GCE only does port 80 and 443 and regular TCP and UDP, so the network load balancer allows us more freedom.

Are you sure that the Ingress object sets a dns record in kube-dns that resolves directly to the service? That could possibly help us out.

**Comment by cmluciano** [comment]
Does externalName work for your use case https://kubernetes.io/docs/user-guide/services/#without-selectors

**Comment by JorritSalverda** [comment]
The externalName actually serves a different purpose. It's for a service to resolve to some external application. 

I need to be able to give any service in Kubernetes an alias though that sets up a dns record in kube-dns so I can use my-service.mydomain.com in any of the other applications running inside the cluster and have it resolve to the clusterIP of my-service.

**Comment by JorritSalverda** [comment]
I'm trying to figure out if I can write records to KubeDNS myself, but the only post I could find about it seems outdated: 

https://rsmitty.github.io/Manually-Checking-Out-KubeDNS/

I mentions there's an etcd container, but in my 1.5.3 cluster there isn't.

How would one go about writing records to KubeDNS?

**Comment by JorritSalverda** [comment]
This issue seems to deal with the same functionality I'm looking for: https://github.com/kubernetes/dns/issues/55

**Comment by dkiser** [comment]
This makes perfect sense for use cases where we need to terminate TLS internally between services who are also reached externally.  E.g. map `someawsomesite.com` to `someawsomesite.namepace.svc.cluster.local`.

**Comment by krish7919** [comment]
@dkiser That's exactly my use case. I am moving a multi-instance service external to k8s to k8s instance by instance, and I need cluster requests for x.y.z to be resolved to an internal instance rather than go out to the internet.

**Comment by thockin** [comment]
@krish7919 in v1.7 we will have hostAliases to map a hostname to an IP.  Maybe in v1.8 we could extend this automatically pull service IPs.  Will need someone to drive it.

**Comment by rickypai** [comment]
I agree that HostAlias should be able to pull IPs dynamically. Having dynamic IPs from services would be nice. That said, HostAlias only provides an override for a particular Pod. If there's a need to provide alternative DNS name for a service for all Pods, HostAlias might not be the right direction.

**Comment by rickypai** [comment]
there is one way to implement this without change in Kubernetes API:

1. write a DNS server that watches services, and if the service has a particular annotation, like `dns-alias`, then it would resolve the DNS address to the service IP

2. use private DNS zone feature in 1.6: http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html

**Comment by krish7919** [comment]
@thockin : Thanks!
I would love to contribute and would want some guidance. Can you tell me where can I get more info on this? Proposal, specs, timeline, etc.?

**Comment by costinm** [comment]
Also see https://github.com/kubernetes-incubator/external-dns

**Comment by djhaskin987** [comment]
@costinm if you read the thread you would see that this thread is not about externalNames at all.

**Comment by djhaskin987** [comment]
@costinm haha, perhaps I am the wrong one here.

@JorritSalverda @krish7919 While externalNames were built for external applications, [they were explicitly also built for migrating external applications inside kubernetes](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors):
> When looking up the host my-service.prod.svc.CLUSTER, the cluster DNS service will return a CNAME record with the value my.database.example.com. Accessing such a service works in the same way as others, with the only difference that the redirection happens at the DNS level and no proxying or forwarding occurs. Should you later decide to move your database into your cluster, you can start its pods, add appropriate selectors or endpoints and change the service type.

It looks like external name should be fine forwarding stuff on to internal DNS names.

**Comment by kaarolch** [comment]
@djhaskin987 I guess that @JorritSalverda  want to have some kind of split horizon on DNS (different IP for internal and external queries). 
We hit the same issue, in different case: 
- We have a frontend company loadbalancer that expose domain keycloak.example.com and ui.example.com.
- Keycloak server and some backend services are inside k8s cluster and by default frontend proxy forward all traffic from keycloak.example.com to the ingress controller and everything is fine but:
- We have backend application that use keycloak to sso users and is visible from world like ui.example.com 
- When user enter us.example.com it is correctly proxy to internal k8s backend app exposed via ingress. This apps redirect user to the keycloak (keycloak.example.com) server to get some token. Keycloak return token and redirect user back to the ui.example.com/.... Everything is fine until next point. 
- Internal apps (visible via ui.example.com) get user's token and try to validate it in keycloak.example.com. It query DNS about keycloak.example.com and get external reverse proxy address. Then our ui apps need to talk with the keycloak via external revers proxy so some part of traffic need to get out from cluster to hit other cluster application. 

In the correct solution the apps should ask about keycloak.example.com and get ingress or internal keycloak service ip not the external one. Of course you can setup some custom DNS with split horizon but it would be difficult to maintenance.

**Comment by johnbelamaric** [comment]
You can do this in CoreDNS, which will eventually replace kube-dns (hopefully in 1.11, though it is available as [alpha in 1.9](https://coredns.io/2018/01/29/deploying-kubernetes-with-coredns-using-kubeadm/) and will be beta in 1.10). It's not totally natural, though. That is, you can't just create an annotation or something in the K8s api server to make it happen. You have to configure it in another file - but that would be a config map so you still can control it via the k8s api.

See https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/

One of the goals with moving to CoreDNS is to enable a lot wider variety of use cases. As a general-purpose DNS server with a K8s integration, it offers a lot of features that would never be added to a point solution like kube-dns.

**Comment by w1ndy** [comment]
This feature would also be extremely useful in implementing domain-based proxies, e.g., routing  blocked google.com traffic to an internal container, where the ports are mapped to Google servers via a SOCKS5 proxy.

**Comment by liggitt** [comment]
> This feature would also be extremely useful in implementing domain-based proxies, e.g., routing blocked google.com traffic to an internal container

the idea that any service can specify something that overrides dns of external names for pods in other namespaces seems problematic. what determines whether this is permitted?

**Comment by w1ndy** [comment]
@liggitt Yeah it could be hard to determine. I have worked out a solution with the rewrite plugin of CoreDNS. For example, redirecting google.com traffic to a service named google under the proxy namespace can be set up as follows:

```
    .:53 {
        ....
        rewrite name google.com google.proxy.svc.cluster.local
    }
```

Save it to the config map of CoreDNS, and the service's cluster IP will be returned for google.com DNS queries.

**Comment by quater** [comment]
@w1ndy I would not consider this a solution although it could be considered a workaround in some scenarios.

**Our use case:**

The DNS rewrite feature in CoreDNS is great and we us this already but do not want to create a rewrite for each service separately. In our case we don't have multiple top level domains but we have multiple services within a Kubernetes namespace where the namespace corresponds to a sub-domain.

So with the suggested feature...
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-ns
spec:
  dnsAliases:
    - hostname: sunrise
  selector:
    app: my-app
```
We only would need to have one CoreDNS rewrite for all services that are deployed within the `my-ns` namespace.
```
rewrite stop {
  name regex (.*)\.my\.example\.org {1}.my-ns.svc.cluster.local
  answer name (.*).my-ns.svc.cluster.local {1}.my.example.org
}
```
When doing a name resolution against CoreDNS, `sunrise.my.example.org` would be resolved to the `my-service` service.

**Comment by vincentjorgensen** [comment]
I just came up with a usecase for using this. We namespace all our services, so being able to namespace our redis clusters (instead of having a custom entry per development environment) would be very useful.

**Comment by denis111** [comment]
+1 Besides of valid certificates issues this would be useful to avoid any external traffic between services for traffic speed and saving on external traffic. I think services should support some cluster-level dns aliases for that without need to edit any CoreDNS...

**Comment by zedtux** [comment]
I need this feature because my app serves 2 hosts (one is the client facing app, the second one is the admin facing app) so that they have 2 different URLs but pointing to the same service.

Locally I'm using a selenium image with the Docker link flag to alias my `app` container to the URLs:

```yaml
  selenium:
    links:
      - app:one-tst.domain.co
      - app:admin-one-tst.domain.co
    ...
```

This works fine and I'm now building a CI/CD within a Kubernetes cluster with zalenium and I need to re-create those aliases.

**Comment by johnbelamaric** [comment]
@zedtux you can have two different "service" entries that use the same selector - that gives you two names for the same set of endpoints. Is that sufficient? This request is more around having specific names rather than the names provided by the K8s DNS spec.

**Comment by zedtux** [comment]
Thank you @johnbelamaric, you seem to be right, I will try to deploy k8s service with an `externalName` as suggested to me from zalando/zalenium#822.

**Comment by guillaume-eb** [comment]
I have a use case for this as well.
We have an nginx pod with different configurations depending on the hostname other apps hit it with.
We can't use `HostAliases` on the other pods, since we don't know the IP address of the nginx pod in advance.
In Docker and docker-compose we would use `--link` with a custom hostname.

**Comment by thockin** [comment]
I do not think we want Kubernetes to become a general-purpose DNS server

**Comment by AndrewSav** [comment]
This is a requiest for supporting dns aliases for kubernetes service, it is not a request for kubernetes to become a general-purpose DNS server, that would be ridiculous. Note, that you cannot emulate that with an external general-purpose DNS server, because these, generally don't want to become kubernetes api consumers favouring staying general-purpose DNS servers. That is to say, whatever solution to this issue is to be it's going to be tightly integrated with kubernetes. Thus, kubernetes sounds like the right please to implement it.

**Comment by thockin** [comment]
This is what things like external-dns are for - syncing kubernetes
state into some other DNS system.

I don't think it's reasonable for kubernetes core to grow surface area
to cover this because it is a slippery slope -- we start with A
records, but very quickly we need AAAA and PTR, and there will be some
need for CNAME, and TXT.  NOt to mention the auth and security issues
- who is allowed to claim what names?

This *can* be done as an extension, so it almost certainly should be.
If we can show why it absolutely cannot be solved any other way, we
can consider it,

**Comment by johnbelamaric** [comment]
Why can't you create multiple services (i.e., names) backed by the same nginx pods?

**Comment by prashantbhate** [comment]
This is a useful feature while running integration tests in CI environment that does not have access to external public network.
Code contains references to Js files hosted on public cdn  (in <script> block) 
so when the tests run these js files fails to load,

We are currently using hostaliases , mapping them to localhost, and run a sidecar to serve these files

```
      - hostnames:
        - public.cdn.host.com
        ip: 127.0.0.1
```

It would be nice if these hosts to be resolved to an internal pod/service that can serve static content within current namespace.

**Comment by hsjalilian** [comment]
Hi,

Is there any way to map "a.domain.com" to "a-domainservice"?
i want connect microservice applications together  with domain name , but domain resolve service name in cluster.

Thanks,

**Comment by dariuszbz** [comment]
it would be veeeeery useful !!!! especially when migrating from old fashion app.

myservvice.public.domain.com CNAM internalkubernetesservice.namespace

so all calls from intern-k8s services goes over the internal network instead of the public endpoint.

**Comment by figroc** [comment]
Why can't service name contain dot?

**Comment by lstellway** [comment]
@figroc 
I was half-expecting the same ability to be available in Kubernetes _(equivalent to [Docker network aliases](https://docs.docker.com/compose/compose-file/compose-file-v3/#aliases))_. It would be GREAT to have this functionality built-in without needing to find a work-around. 

I was able to accomplish what I wanted via a [`hostAliases` configuration](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/) and a sidecar NGINX proxy to forward traffic to the internal service:

```yml
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: frontend-configmap
data:
    default.conf: |
        server {
            server_name example.com;
            listen 80 default_server reuseport backlog=4096;
            listen [::]:80 default_server reuseport backlog=4096;
            listen 443 default_server reuseport backlog=4096 ssl http2;
            listen [::]:443 default_server reuseport backlog=4096 ssl http2;

            # SSL configuration
            # https://ssl-config.mozilla.org/#server=nginx
            ssl_certificate /etc/ssl/example.com/tls.crt;
            ssl_certificate_key /etc/ssl/example.com/tls.key;
            ssl_trusted_certificate /etc/ssl/example.com/ca.crt;
            ssl_session_timeout 1d;
            ssl_session_cache shared:MozSSL:10m;
            ssl_session_tickets off;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
            ssl_prefer_server_ciphers off;

            # Proxy configuration
            location / {
                # Headers
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header Host $http_host;
                proxy_intercept_errors on;

                # Other
                proxy_redirect      off;
                proxy_http_version  1.1;
                proxy_read_timeout  60s;
                # This is pointing to my ingress controller (I am using NGINX ingress in the default namespace)
                proxy_pass https://ingress-nginx-controller.ingress-nginx/;
            }
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deployment
    labels:
        app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: frontend:0.0.2
                - name: frontend-nginx
                  image: nginx:1.21.6-alpine
                  ports:
                      - containerPort: 80
                      - containerPort: 443
                  volumeMounts:
                      - name: certificate-secret
                        mountPath: /etc/ssl/example.com
                        readOnly: true
                      - name: frontend-nginx-config
                        mountPath: /etc/nginx/conf.d
                        readOnly: true
            hostAliases:
                # Loop requests for `example.com` back to sidecar NGINX proxy
                - ip: 127.0.0.1
                  hostnames:
                      - example.com
            volumes:
                - name: frontend-nginx-config
                  configMap:
                      name: frontend-configmap
                      items:
                          - key: default.conf
                            path: default.conf
                - name: certificate-secret
                  secret:
                      secretName: certificate-secret
                      items:
                          - key: ca.crt
                            path: ca.crt
                          - key: tls.crt
                            path: tls.crt
                          - key: tls.key
                            path: tls.key
```

_Note:
The `certificate-secret` resource referenced here is generated by a [cert-manager](https://cert-manager.io/) certificate. I would love to hear feedback if anyone sees something here that can be better._
