### ISSUE TITLE
Environment variables created from Secrets are incorrect under printenv and set

### ISSUE THREAD

**Issue by lihan** [kubernetes/kubernetes#39795]
Duplicate of https://github.com/kubernetes/kubernetes/issues/23404

**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

Yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

secrets, environmental variables

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

1.5.1
**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release):gci
- **Kernel** (e.g. `uname -a`):Linux envar-demo 4.4.21+ #1 SMP Thu Oct 27 02:50:36 PDT 2016 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:

The same environmental variable returns different value under ``printenv`` and ``set``.

**What you expected to happen**:

They should return the same value.

**How to reproduce it** (as minimally and precisely as possible):

1. Create following secret and pod
2. Get interactive shell access to the running pod
3. Test with ``set | grep PLIVO`` and ``printenv | grep PLIVO``
4. It returns different value

```
apiVersion: v1
kind: Secret
metadata:
  name: django-credentials
data:
  PLIVO_TOKEN: "test_string"
```

```
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: PLIVO_TOKEN
      valueFrom:
        secretKeyRef:
          name: django-credentials
          key: PLIVO_TOKEN
```

```
The set command wraps the correct string by a "$'" "\n'", which changes the meaning of the variable.
root@envar-demo:/# set | grep PLIVO
PLIVO_TOKEN=$'CorrectString\n'
root@envar-demo:/# env | grep PLIVO
PLIVO_TOKEN=CorrectString
```

**Anything else do we need to know**:

* For the environment variables created using ConfigMap does not have this issue.
* In Python, ``os.environ['VARIABLE']`` will return another version of the incorrect value, format is `{CorrectValue}\n`.
