### ISSUE TITLE
Validation errors in the cli are cryptic

### ISSUE THREAD

**Issue by eric-tucker** [kubernetes/kubernetes#39811]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
ports required

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

I would like to be able to create a deployment without a port.  This is currently not possible.

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
Not relevant

**What happened**:
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graylog-collector
  namespace: my-namespace
  labels:
    name: graylog-collector
spec:
  replicas: 4
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: graylog-collector
  template:
    metadata:
      labels:
        name: graylog-collector
    spec:
      containers:
      - name: graylog-collector
        image: my-registry:5000/graylog_collector:42
        env:
        - name: GRAYLOG_HOST
          value: example.com
---
apiVersion: v1
kind: Service
metadata:
  name: graylog-collector
  namespace: my-namespace
  labels:
    name: graylog-collector
spec:
  selector:
    name: graylog-collector```
```
This will not work, instead throwing this error:

```
error validating "kubernetes.yaml": error validating data: field ports: is required; if you choose to ignore these errors, turn validation off with --validate=false
```

I'd rather not disable validation.

**What you expected to happen**:
I expect to be able to create a deployment without a port.  Not all things deployed to Kubernetes are meant to be connected to.  I am simply deploying a Graylog collector container.

Note: if this is simply a matter of having incorrect configuration then I will tell you the documentation on this is lacking and that's why I can't figure this out.
