### ISSUE TITLE
Cannot expose deployment on AWS environment

### ISSUE THREAD

**Issue by cazorla19** [kubernetes/kubernetes#39849]
**Is this a request for help?** I guess yes, but I didn't find any information to troubleshoot this issue either in docs or in Google Groups.

**What keywords did you search in Kubernetes issues before filing this one?** : kubectl aws cannot expose deployment, service pending ip

**Kubernetes version**: 1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: AWS (EC2 on Auto Scaling group + Elastic Load Balancer in front of)
- **OS** : Ubuntu 16.04 Xenial
- **Kernel**: 4.4.0-57-generic
- **Docker**: 1.12.5
- **Install tools**: I initialized my cluster through kubeadm as mentioned in [official guide](https://kubernetes.io/docs/getting-started-guides/kubeadm/). So, I installed cluster not through kops, cause I want to keep hardware state outside and keep custom OS configuration.

**What happened**:

Cluster state: 1 master + 2 nodes

```
NAME                               STATUS         AGE
cluster-manager.dev.example.net   Ready,master   1d
dev-1.example.net                 Ready          1d
dev-2.example.net                 Ready          1d
```

_**Goals:**_ 

1. expose deployment pods network access to special bind address (at first try 0.0.0.0) and port (here is 80). So, simpler, the docker-proxy should open 80 port on node for pod.
2. pin deployment pods to the same DNS name (didn't think much about its implementation cause I'm getting stuck on the first goal).

After initialization and double check network connections established (using Weave), I initialized my first deployment.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    tier: frontend
    environment: dev
    product: nginx
  name: proxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: reg.example.net/proxy:0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.05
            memory: 128M
      imagePullSecrets:
      - name: example-registry
```

It runs correct.

```
[cazorla19@localhost dev]$ kubectl get pods
NAME                     READY     STATUS    RESTARTS   AGE
proxy-3357623934-5v5rw   1/1       Running   0          1h
proxy-3357623934-rms19   1/1       Running   0          1h
```

But I cannot expose containers the way K8s doing. As mentioned in docs, I created the service for deployments. Cannot get external IP address and finally containers are closed with no way to reach even at local host. 80 port is not opened on deployment pods.

**What you expected to happen**: having deployment pods with 80 port exposed and shared DNS address assigned by kube-dns.

**How to reproduce it**:

I tried to expose deployment 2 ways. The first one:

```
[cazorla19@localhost dev]$ kubectl expose deployment proxy --port=80 --target-port=80
service "proxy" exposed
[cazorla19@localhost dev]$ kubectl get service proxy 
NAME      CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
proxy     10.111.15.130   <none>        80/TCP    1m
```

The second one:

```
[cazorla19@localhost dev]$ kubectl expose deployment proxy --port=80 --target-port=80 --type=LoadBalancer
service "proxy" exposed
[cazorla19@localhost dev]$ kubectl get service proxy 
NAME      CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
proxy     10.102.8.95   <pending>     80:30728/TCP   44s
```

I see the External IP is pending but cannot figure out why.

Checking containers if the 80 port open.

```
ubuntu@dev-1:~$ docker ps | grep 'reg.example.net/proxy'
72c0478c7567        reg.example.net/proxy:0.1                         "nginx -g 'daemon off"   11 hours ago        Up 11 hours                             k8s_proxy.9388b000_proxy-3357623934-vvm27_default_17d49c4a-d8e4-11e6-8fb8-02dfdae1a1e9_12209a11
```

I guess there is a initial configuration mismatch, because I didn't use any IAM roles, policies etc. doing a default installation. But unfortunately I don't even know how to debug this issue. So, if you guess where is the hitch might be, please, help.
