### ISSUE TITLE
init-containers: Deployment in version "v1beta1" cannot be handled as a Deployment

### ISSUE THREAD

**Issue by robertlemke** [kubernetes/kubernetes#39881]
**Is this a request for help?**:
_no_

**What keywords did you search in Kubernetes issues before filing this one?**:
_init-containers, init container, deployment_

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):

_**Client Version**: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.6", GitCommit:"e569a27d02001e343cb68086bc06d47804f62af6", GitTreeState:"clean", BuildDate:"2016-11-12T05:22:15Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}_
_**Server Version**: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}_

**Environment**:
- **Cloud provider or hardware configuration**:
GKE
- **OS** (e.g. from /etc/os-release):
Google Container VM (GCI), BUILD_ID=8938.0.0

**What happened**:
`kubectl create -f` reported the following error when I tried to create a `Deployment` using the `pod.beta.kubernetes.io/init-containers` beta feature:

```console
Deployment in version "v1beta1" cannot be handled as a Deployment: invalid character '"' after object key:value pair
```
**What you expected to happen**:
I expected the `Deployment` resource to be created.

**How to reproduce it** (as minimally and precisely as possible):
Create a file with the following Deployment definition and run `kubectl create -f` to create it:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 'nginx'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'nginx'

  template:
    metadata:
      labels:
        app: 'nginx'
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "install",
                "image": "busybox",
                "imagePullPolicy": "IfNotPresent"
                "command": ["wget", "-O", "/application/index.html", "http://kubernetes.io/index.html"],
                "volumeMounts": [
                    {
                      "name": "application",
                      "mountPath": "/application"
                    }
                ]
            }
        ]'
    spec:
      volumes:
        - name: 'application'
          emptyDir: {}

      containers:

      - name: webserver
        image: 'nginx'
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - name: 'application'
            mountPath: '/application'
```

**Anything else do we need to know**:
I checked if Deployment should actually support init containers and assumed that it should after stumbling over the following sentence [in the user guide](https://kubernetes.io/docs/user-guide/production-pods/#handling-initialization):

> Since init containers are a beta feature, they are specified by setting the pod.beta.kubernetes.io/init-containers annotation on a pod (or replica set, deployment, daemon set, pet set, or job).
