### ISSUE TITLE
Node affinity "preferredDuringSchedulingIgnoredDuringExecution" type error

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#39934]
Hi Guys,

I tried to use the Node Affinity feature, but got the below error when I using `preferredDuringSchedulingIgnoredDuringExecution` affinity type.
```
root@slave2:/home/zhangjian/testK8s# kubectl create -f nginx-deploy.yaml 
The Deployment "nginx-deploy" is invalid: spec.template.annotations: Invalid value: "scheduler.alpha.kubernetes.io/affinity": json: cannot unmarshal object into Go value of type []api.PreferredSchm
```
The below is my configure file. Something else I missed? BTW, the `requiredDuringSchedulingIgnoredDuringExecution` works well.
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
          app: nginx-deploy
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
          {
             "nodeAffinity": {
                "preferredDuringSchedulingIgnoredDuringExecution": {
                  "nodeSelectorTerms": [
                   {
                      "matchExpressions": [
                       {
                         "key": "gpu/nvidia",
                         "operator": "In",
                         "values": ["GeForceGT731"]
                       }
                     ]
                   }
                 ]
               }
             }
           }
    spec:
      containers:
      - name: nginx-deploy
        image: nginx:jian
        ports:
        - containerPort: 80
```
```
root@slave2:/home/zhangjian/testK8s# kubectl version
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.2-beta.0.56+e80ebba218aa9c-dirty", GitCommit:"e80ebba218aa9c70b110f0aeebe15e64006ceac5", GitTreeState:"dirty", BuildDate:"2017-01-12T05:17:16Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.2-beta.0.56+e80ebba218aa9c-dirty", GitCommit:"e80ebba218aa9c70b110f0aeebe15e64006ceac5", GitTreeState:"dirty", BuildDate:"2017-01-12T05:17:16Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by resouer** [comment]
`scheduler.alpha.kubernetes.io/affinity` belongs to Pod spec, you wrongly added it to Deployment spec.

**Comment by jianzhangbjz** [comment]
@resouer I have a bit confused, as the above shows, if I changed `preferredDuringSchedulingIgnoredDuringExecution` to `requiredDuringSchedulingIgnoredDuringExecution`, it works well! And, I  think it did belongs to Pod spec in my configure, or can you provide me an example?
As the below shows, I config it in a Pod, it still get the below error, but the `requiredDuringSchedulingIgnoredDuringExecution` works well.
```
root@slave2:/home/zhangjian/testK8s# kubectl create -f nginx-pod.yaml 
The Pod "nginx-pod" is invalid: metadata.annotations: Invalid value: "scheduler.alpha.kubernetes.io/affinity": json: cannot unmarshal object into Go value of type []api.PreferredSchedulingTerm
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
         "nodeAffinity": {
            "preferredDuringSchedulingIgnoredDuringExecution": {
              "nodeSelectorTerms": [
               {
                  "matchExpressions": [
                   {
                     "key": "gpu/nvidia",
                     "operator": "In",
                     "values": ["GeForceGT731"]
                   }
                 ]
               }
             ]
           }
         }
       }
spec:
  containers:
  - name: nginx-pod
    image: nginx:jian
    ports:
    - containerPort: 80
```

**Comment by resouer** [comment]
Sorry, I mis-read your yaml. re-opened it.

**Comment by resouer** [comment]
`json: cannot unmarshal object into Go value of type []api.PreferredSchm`

`PreferredSchm`? May be it's `PreferredSchedulingTerm` or something. Could you please pos complete error message here.

**Comment by jianzhangbjz** [comment]
@resouer The above is all of the error message, when I replace the `prefer` type to `required`, it works. I walk through the [Node affinity](https://kubernetes.io/docs/user-guide/node-selection/) and [nodeaffinity.md](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/nodeaffinity.md) docs, but didn't find any examples for `prefer` type.

**Comment by resouer** [comment]
As for your problem, I believe the root cause is: `preferredDuringSchedulingIgnoredDuringExecution` is a array. For example:
```
"preferredDuringSchedulingIgnoredDuringExecution": [
    {
        "nodeSelectorTerms": [
              {
                "matchExpressions": [
                  {
                    "key": "kubernetes.io/e2e-az-name",
                    "operator": "In",
                    "values": ["e2e-az1", "e2e-az2"]
                  }
                ]
              }
            ]
    }
]
```

I did not test, so you need to format and test it by yourself. 

More details: [nodeaffinity design doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/nodeaffinity.md#nodeaffinity)

**Comment by resouer** [comment]
And, you have to use annotation (ugly and easy to make mistake) because it's still alpha/beta feature, it will become api fields after released.

**Comment by jianzhangbjz** [comment]
@resouer Yes, you're right, it should be a array. And I have modified the `yaml` file(as the below), but still get the below error. Now I refer to a test example: [validation_test.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation_test.go#L3591), maybe somewhere is still mistake, could you help to point out?
```
root@slave2:/home/zhangjian/testK8s# kubectl create -f nginx-debug.yaml 
The Pod "nginx-pod" is invalid: metadata.annotations.scheduler.alpha.kubernetes.io/affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions: Required value: must have at least one node selector requirement
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
         "nodeAffinity": {
            "preferredDuringSchedulingIgnoredDuringExecution": [
               {
                 "weight" : 1,
                 "podAffinityTerm": [
                    {
                       "labelSelector" : {
                         "matchExpressions": [
                            {
                              "key": "gpu/nvidia",
                              "operator": "In",
                              "values": ["GeForceGT731", "GeForceGT730"]
                            }
                         ]
                       },
                       "namespaces": ["default"],
                       "topologyKey": "region"
                 }
               ]
             }
           ]
         }
       }
spec:
  containers:
  - name: nginx-pod
    image: nginx:jian
    ports:
    - containerPort: 80
```

**Comment by resouer** [comment]
Do not copy from `PodAffinity` it's different, please check the example I provided.

**Comment by jianzhangbjz** [comment]
@resouer Yeah, I also followed your example, but still get the error, I don't understand that why it always print `matchExpressions: Required value: must have at least one node selector requirement` error, obviously, I have added one. 
```
root@slave2:/home/zhangjian/testK8s# kubectl create -f nginx-pod.yaml 
The Pod "nginx-pod" is invalid: metadata.annotations.scheduler.alpha.kubernetes.io/affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions: Required value: must have at least one node selector requirement
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
         "nodeAffinity": {
            "preferredDuringSchedulingIgnoredDuringExecution": [
               {
                 "weight" : 1,
                 "nodeSelectorTerms": [
                    {
                       "matchExpressions": [
                          {
                            "key": "gpu/nvidia",
                            "operator": "In",
                            "values": ["GeForceGT731", "GeForceGT730"]
                          }
                       ]
                    }
                 ]
              }
           ]
         }
       }
spec:
  containers:
  - name: nginx-pod
    image: nginx:jian
    ports:
    - containerPort: 80
```

**Comment by resouer** [comment]
@jianzhangbjz You missed `preference` key, check my previous example, I've updated it to a full version.

**Comment by jianzhangbjz** [comment]
@resouer I followed your latest example, but still get the same error, the below is the latest configure. BTW,  
could you clarify why need to add `preference` key, I'm confused about the [NodeAffinity](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/nodeaffinity.md#nodeaffinity) 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
         "nodeAffinity": {
            "preferredDuringSchedulingIgnoredDuringExecution": [
               {
                 "weight" : 10,
                 "preference": {
                    "nodeSelectorTerms": [
                       {
                          "matchExpressions": [
                             {
                               "key": "gpu/nvidia",
                               "operator": "In",
                               "values": ["GeForceGT731", "GeForceGT730"]
                             }
                          ]
                       }
                     ]
                 }
              }
           ]
         }
       }
spec:
  containers:
  - name: nginx-pod
    image: nginx:jian
    ports:
    - containerPort: 80
```

**Comment by resouer** [comment]
Here's the example API object of affinity:
```
&api.Affinity{
					NodeAffinity: &api.NodeAffinity{
						RequiredDuringSchedulingIgnoredDuringExecution: &api.NodeSelector{
							NodeSelectorTerms: []api.NodeSelectorTerm{
								{
									MatchExpressions: []api.NodeSelectorRequirement{
										{
											Key:      "key2",
											Operator: api.NodeSelectorOpIn,
											Values:   []string{"value1", "value2"},
										},
									},
								},
							},
						},
						PreferredDuringSchedulingIgnoredDuringExecution: []api.PreferredSchedulingTerm{
							{
								Weight: 10,
								Preference: api.NodeSelectorTerm{
									MatchExpressions: []api.NodeSelectorRequirement{
										{
											Key:      "foo",
											Operator: api.NodeSelectorOpIn,
											Values:   []string{"bar"},
										},
									},
								},
							},
						},
					},
				},
```

**Comment by resouer** [comment]
I updated my previous example again, you can have a look.

**Comment by jianzhangbjz** [comment]
@resouer It works! Thanks a lot! :) The below is the correct `yaml` configure. I suggest that provide an example for the `preferred` type.  Otherwise, [ nodeaffinity design doc](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/nodeaffinity.md#nodeselector) will make users feel confuse. Users could not find the description of `preference` key in it, after all. :) 
```
root@slave2:/home/zhangjian/testK8s# kubectl get pods
NAME                 READY     STATUS    RESTARTS   AGE
nginx-pod            1/1       Running   0          6m
with-node-affinity   0/1       Pending   0          1d
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    scheduler.alpha.kubernetes.io/affinity: >
      {
         "nodeAffinity": {
            "preferredDuringSchedulingIgnoredDuringExecution": [
               {
                 "weight" : 10,
                 "preference": {
                   "matchExpressions": [
                      {
                        "key": "gpu/nvidia",
                        "operator": "In",
                        "values": ["GeForceGT731"]
                      }
                   ]
              }
            }
           ]
         }
       }
spec:
  containers:
  - name: nginx-pod
    image: nginx:jian
    ports:
    - containerPort: 80
```
