### ISSUE TITLE
RBAC roles for some components still missing

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#40021]
We do not have well-crafted RBAC roles for some components like heapster, node-problem-detector, etc which basically has led to them using either overly powerful roles (like cluster-admin) or less powerful roles which leads to RBAC DENY msgs in the apiserver logs. We need to create the right roles for each of these components.

Feel free to comment below any new role that you think might be required.

- [x] node problem detector - https://github.com/kubernetes/kubernetes/pull/40035
- [x] heapster - https://github.com/kubernetes/kubernetes/pull/40028
- [x] scheduler - https://github.com/kubernetes/kubernetes/pull/41285

cc @kubernetes/sig-auth-misc @deads2k

**Comment by shyamjvs** [comment]
cc @wojtek-t @gmarek @Random-Liu

**Comment by deads2k** [comment]
> or less powerful roles which leads to RBAC DENY msgs in the apiserver logs. We need to create the right roles for each of these components.

It seems like kubemark is already set up to produce the RBAC DENY messages we'd need to craft complete roles.  If you can assign them unique identities and then produce a log, it will be a lot easier to create these.

**Comment by Random-Liu** [comment]
Ref https://github.com/kubernetes/node-problem-detector/issues/76.

NPD needs permission to get/patch node status and generate node events.

Should we create a new role in https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go? Or use `system:node` which has overly powerful role? Or change any other existing role?

**Comment by shyamjvs** [comment]
> It seems like kubemark is already set up to produce the RBAC DENY messages we'd need to craft complete roles. If you can assign them unique identities and then produce a log, it will be a lot easier to create these.

@deads2k Yup. In the process of doing it. I'll post the RBAC DENY logs here once I do what you've said and filter the noise (for eg, logs due to initial delay in role propogation)

**Comment by shyamjvs** [comment]
> Should we create a new role in https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go? Or use system:node which has overly powerful role? Or change any other existing role?

@Random-Liu Unless there is a role already which logically is the same as that what npd needs, I think creating a new role makes sense. However, whether we want the role to be bootstrapped is something @deads2k has to decide.

**Comment by deads2k** [comment]
> @Random-Liu Unless there is a role already which logically is the same as that which npd needs, I think creating a new role makes sense. However, whether we want the role to be bootstrapped is something @deads2k has to decide.

Node problem detector can have its own bootstrap role.  It's for a repo under `k8s.io/`, so it seems pretty reasonable to have its own dedicated role.

**Comment by shyamjvs** [comment]
@deads2k Thanks a ton for PRs #40028 and #40035 . Once we have them both merged into the code, this issue can be closed.

**Comment by Random-Liu** [comment]
> Node problem detector can have its own bootstrap role. It's for a repo under k8s.io/, so it seems pretty reasonable to have its own dedicated role.

@deads2k Cool. And thanks a lot for sending the PR.

**Comment by shyamjvs** [comment]
@deads2k I still see some RBAC DENYs in the logs of kubemark apiserver (that pop up even after the roles/bindings are propagated):
```
19576-I0118 17:33:07.499172       6 rbac.go:49] RBAC DENY: user "system:serviceaccount:kube-system:pod-garbage-collector" groups [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] cannot "list" on "nodes./"
19577:I0118 17:33:07.499229       6 panics.go:75] GET /api/v1/nodes: (378.746µs) 403 [[kube-controller-manager/v1.6.0 (linux/amd64) kubernetes/e827393/system:serviceaccount:kube-system:pod-garbage-collector] [::1]:44838]
```

**Comment by shyamjvs** [comment]
@deads2k I looked into the above issue, and given that we have the following role:

```
- apiVersion: rbac.authorization.k8s.io/v1alpha1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:pod-garbage-collector
  rules:
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - pods
    verbs:
    - delete
    - list
    - watch
  - apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - nodes
    verbs:
    - list
```

and the following binding:

```
- apiVersion: rbac.authorization.k8s.io/v1alpha1
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:pod-garbage-collector
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:controller:pod-garbage-collector
  subjects:
  - kind: ServiceAccount
    name: pod-garbage-collector
    namespace: kube-system
```

it is strange that we still see these RBAC DENYs. Could it be because the real cluster on which I'm running kubemark cluster had been started long back (when probably abac was doing the rounds)? I would still hope to not see these msgs as the kubemark master itself is quite up to date with the rbac changes.
