### ISSUE TITLE
Create a default StorageClass for Photon

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#40072]
We'd like to deprecate alpha provisioning in 1.6. In order to make current deployments working after upgrade to 1.6 we need to deploy a default StorageClass as part of installation/upgrade on Photon so it will automatically provision volumes for PVCs marked with annotation `volume.alpha.kubernetes.io/storage-class` - the annotation will be ignored and default storage class must provision the volume instead.

On GCE and AWS, we use addon manager to install the default storage class, see https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/storage-class. Note that some extra code is probably needed to actually put the storage class into addons directory during installation, e.g. https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/container-linux/configure-helper.sh#L1129 for manual script-based installation on GCE or https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-addons/init.sls#L181 for salt-based installation.

Please make sure that:
* A default StorageClass is deployed during "default" installation.
  * It would be nice if admin could turn this off during installation (e.g.  as `export ENABLE_DEFAULT_STORAGE_CLASS=false` on GCE)
* If any additional manual steps are needed to deploy the default storage class make sure they're documented in appropriate installation guide.

**Comment by luomiao** [comment]
Since the installation of kubernetes cluster on Photon Controller is part of the cluster management code in [https://github.com/vmware/photon-controller](url), in order to have the default storage class started by addons manager, the following changes are required on the Photon Controller side:
1. Create a flavor with default parameters with “--kind persistent-disk” and “--name k8s-default-persis-disk-[SOME ID]”
2. Generate a yaml file under /etc/kubernetes/addons on master nodes:
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: default
annotations:
  storageclass.beta.kubernetes.io/is-default-class: "true"
labels:
  kubernetes.io/cluster-service: "true"
provisioner:
  kubernetes.io/photon
parameters:
  flavor: k8s-default-persis-disk-[SOME ID]
```

If I understand correctly, we may not need anything on K8s side for this issue.

@AlainRoy @ashoksekar07
