### ISSUE TITLE
vSphere Cloud provider: wrong vm path when using multiple working-dir

### ISSUE THREAD

**Issue by sswierczyna** [kubernetes/kubernetes#40084]
**BUG REPORT**

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+coreos.0", GitCommit:"3ed7d0f453a5517245d32a9c57c39b946e578821", GitTreeState:"clean", BuildDate:"2017-01-13T00:23:19Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
VMWare virtual machine
- **OS** (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.6.0
VERSION_ID=1235.6.0
BUILD_ID=2017-01-10-0545
PRETTY_NAME="Container Linux by CoreOS 1235.6.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
- **Kernel** (e.g. `uname -a`):
Linux master-01.c002.k8s.easypack24.net 4.7.3-coreos-r2 #1 SMP Sun Jan 8 00:32:25 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz GenuineIntel GNU/Linux
- **Install tools**:
Installation method:
https://coreos.com/kubernetes/docs/latest/kubernetes-on-baremetal.html

- **Others**:
3 nodes cluster with Vsphere Cloud Provider (master + 2 workers)

## master
components with vsphere coloud provider flag:  ```kube-apiserver, kube-controller-manager, kubelet-wrapper```
```
      [Global]
               user = k8s@vmware.local
               password = xxxxxx
               server = 192.168.99.114
               port = 443
               insecure-flag = 1
               datacenter = DC_first
               datastore = KRK_5300_T1_SAS_ILPC_1_VM_006
               working-dir = /DC_first/vm/PROD/CoreOS-C002/
      [Disk]
               scsicontrollertype = pvscsi
```
## node-a-01
**same** config as on master.
component with vsphere coloud provider flag: ```kubelet-wrapper```
```
      [Global]
               user = k8s@vmware.local
               password = xxxxxx
               server = 192.168.99.114
               port = 443
               insecure-flag = 1
               datacenter = DC_first
               datastore = KRK_5300_T1_SAS_ILPC_1_VM_006
               working-dir = /DC_first/vm/PROD/CoreOS-C002/
      [Disk]
               scsicontrollertype = pvscsi
```
## node-b-01
**different** config as than on ```master``` and ```node-a-01```.
component with vsphere coloud provider flag:  ```kubelet-wrapper```
```
      [Global]
               user = k8s@vmware.local
               password = xxxxxx
               server = 10.102.51.124
               port = 443
               insecure-flag = 1
               datacenter = DC_second
               datastore = DEB_5300_DT_ILPC_1_VM_007
               working-dir = /DC_second/vm/PROD/CoreOS_c002/
      [Disk]
               scsicontrollertype = pvscsi
```

**What happened**:
Error when try to create POD on node ```worker-b-01``` using attached volume from VMWare data storage.
```
apiVersion: v1
kind: Pod
metadata:
  name: test-vmdk-second
spec:
  nodeSelector:
    dc: second
  containers:
  - image: ubuntu
    name: test-container
    command: ["sleep","3600"]
    volumeMounts:
    - mountPath: /test-vmdk
      name: test-volume-deb
  volumes:
  - name: test-volume-deb
    # This VMDK volume already exists.
    vsphereVolume:
      volumePath: "[DEB_5300_DT_ILPC_1_VM_007] volumes/myDisk1"
      fsType: ext4
```
### kubectl describe pod test-vmdk-second
```
core@master-01 ~ $ kubectl  describe pod test-vmdk-second
Name:           test-vmdk-second
Namespace:      default
Node:           node-b-01.c002.k8s.easypack24.net/
Start Time:     Wed, 18 Jan 2017 13:54:07 +0100
Labels:         <none>
Status:         Failed
Reason:         MatchNodeSelector
Message:        Pod Predicate MatchNodeSelector failed
IP:             
Controllers:    <none>
Containers:
  test-container:
    Image:      ubuntu
    Port:       
    Command:
      sleep
      3600
    Volume Mounts:
      /test-vmdk from test-volume-deb (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-f3r71 (ro)
    Environment Variables:      <none>
Volumes:
  test-volume-deb:
    Type:       vSphereVolume (a Persistent Disk resource in vSphere)
    VolumePath: [DEB_5300_DT_ILPC_1_VM_007] volumes/myDisk1
    FSType:     ext4
  default-token-f3r71:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-f3r71
QoS Class:      BestEffort
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  20m           19m             8       {default-scheduler }                    Warning         FailedScheduling        pod (test-vmdk-second) failed to fit in any node
fit failure summary on nodes : MatchNodeSelector (3)
  18m   18m     1       {default-scheduler }                                    Normal  Scheduled               Successfully assigned test-vmdk-second to node-b-01.c002.k8s.easypack24.net
  16m   16m     1       {kubelet node-b-01.c002.k8s.easypack24.net}             Warning FailedMount             Unable to mount volumes for pod "test-vmdk-second_default(e993310f-dd7c-11e6-a40b-00505690f6d8)": timeout expired waiting for volumes to attach/mount for pod "default"/"test-vmdk-second". list of unattached/unmounted volumes=[test-volume-deb]
  16m   16m     1       {kubelet node-b-01.c002.k8s.easypack24.net}             Warning FailedSync              Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"test-vmdk-second". list of unattached/unmounted volumes=[test-volume-deb]
  15m   15m     1       {kubelet node-b-01.c002.k8s.easypack24.net}             Warning MatchNodeSelector       Predicate MatchNodeSelector failed
  18m   16s     10      {controller-manager }                                   Warning FailedMount             Failed to attach volume "test-volume-deb" on node "node-b-01.c002.k8s.easypack24.net" with: vm '/DC_first/vm/PROD/CoreOS-C002/node-b-01.c002.k8s.easypack24.net' not found
```
```controller-manager``` create wrong path to vm:
```/DC_first/vm/PROD/CoreOS-C002/node-b-01.c002.k8s.easypack24.net```

**currently using:** 
```working-dir = /DC_first/vm/PROD/CoreOS-C002/ ``` from ```master```

**expected:** 
```working-dir = /DC_second/vm/PROD/CoreOS_c002/``` from ```worker-b-01```

**What you expected to happen**:
1. Path to vm should looks like ```/DC_second/vm/PROD/CoreOS_c002/node-b-01.c002.k8s.easypack24.net```
2. POD should start with attached VMWare volume.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
Nodes are sucessfully added do cluster
```
core@master-01 ~ $ kubectl get nodes
NAME                                STATUS                     AGE
master-01.c002.k8s.easypack24.net   Ready,SchedulingDisabled   2d
node-a-01.c002.k8s.easypack24.net   Ready                      3d
node-b-01.c002.k8s.easypack24.net   Ready                      1h
```

I'am able to successfully create POD on ```worker-a-01``` using config:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-vmdk-first
spec:
  nodeSelector:
    dc: second
  containers:
  - image: ubuntu
    name: test-container
    command: ["sleep","3600"]
    volumeMounts:
    - mountPath: /test-vmdk
      name: test-volume
  volumes:
  - name: test-volume
    # This VMDK volume already exists.
    vsphereVolume:
      volumePath: "[KRK_5300_T1_SAS_ILPC_1_VM_006] volumes/myDisk1"
      fsType: ext4
```
