### ISSUE TITLE
Can't access a service through the internet using externalIPs, though I can access it inside the server.

### ISSUE THREAD

**Issue by brunomvsouza** [kubernetes/kubernetes#40268]
**Kubernetes version** (use `kubectl version`): 
- Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: hardware
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): Linux HOST_REDACTED 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**: 
**docker version**: 1.13.0
**kubeadm version**: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
Timeout while trying to access a service exposed using externalIPs via internet.

**What you expected to happen**:
Should be able to access it.

**How to reproduce it** (as minimally and precisely as possible):
- Install kubernetes via kubeadm as described in the [docs](kubernetes.io/docs/getting-started-guides/kubeadm/). Current versions can be found above.
- Doesn't really matter if you chose flannel or weave.
- Create any service and try to expose it via externalIPs.
- Access it. You should see a timeout.

**Anything else do we need to know**:
- It succeeds when I try to access from within the server using the service IP, the endpoint (pod) IP and the exposedIPs (server) IP.
- It fails when I try to access the service through the internet. `curl REDACTED_EXTERNAL_IP:8080`.
- Checked if it was a network issue unrelated with kubernetes using `python -m SimpleHTTPServer 8080`. `curl REDACTED_EXTERNAL_IP:8080` worked as expected.
- [`iptables-save` output](https://gist.github.com/brunomvsouza/1a1edcd5356401b7633e64d0dfb416a6).
- Service and deployment schemas used:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
spec:
  ports:
  - port: 8080
    targetPort: 80
  externalIPs:
  - REDACTED_EXTERNAL_IP
  selector:
    app: phpmyadmin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  labels:
    app: phpmyadmin
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      restartPolicy:  Always
      containers:
      - image: phpmyadmin/phpmyadmin:4.6.4-1
        imagePullPolicy: Always
        name: phpmyadmin
        env:
        - name: PMA_HOST
          value: percona-svc
        ports:
        - containerPort: 80
        volumeMounts:
        - name: tz
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: tz
        hostPath:
           path: /etc/localtime
```
