### ISSUE TITLE
Azure disk: no key found for storage account

### ISSUE THREAD

**Issue by otaviosoares** [kubernetes/kubernetes#40276]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 LTS
- **Kernel** (e.g. `uname -a`): 4.4.0-28-generic
- **Install tools**: Azure ACS Engine

**What happened**:
PVC keeps pending and returns "no key found for storage account"

**What you expected to happen**:
Storage class can retrieve the storage account key and successfully create the blob and pv.

**How to reproduce it** (as minimally and precisely as possible):
1 - Create a new storage account and create a blob container named vhds

2 - Create a storage class as below

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: brazilsouth
  storageAccount: artyoudbs
```

3 - Create the pvc
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kaui-db
  annotations:        
    volume.beta.kubernetes.io/storage-class: slow 
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
```

4 -  Check kube-controller-manager logs:

I0122 19:02:49.781348       1 azure_storage.go:208] **no key found for storage account artyoudbs**
I0122 19:02:49.781388       1 pv_controller.go:1305] failed to provision volume for claim "default/kaui-db" with StorageClass "slow": failed to find a matching storage account

**Anything else do we need to know**:
I can retrieve storage account keys using azure-cli:

`az storage account keys list`

I've already used storageclass and pvc in azure  with success before.
