### ISSUE TITLE
Certificate errors after context switches

### ISSUE THREAD

**Issue by sanderploegsma** [kubernetes/kubernetes#40512]
**Kubernetes version**: `kubectl` version is 1.5.2. Clusters differentiate between 1.4.7 and 1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: Google Cloud Platform
- **OS**: macOS Sierra 10.12.2
- **Kernel**: `Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64`
- **Install tools**: I just installed `kubectl` using `gcloud components install kubectl`
- **Others**:

**What happened**: We run a kubernetes cluster on multiple GCP projects and use 
```
gcloud container clusters get-credentials $CLUSTER --project=$PROJECT --zone=europe-west1-b
``` 
to switch between them. After upgrading to a new Macbook Pro (2016 model, 13" with touch bar) I  (and some of my coworkers with the same Macbook Pro model) keep getting the following error on any `kubectl` command after switching context:
```
Unable to connect to the server: Post https://accounts.google.com/o/oauth2/token: x509: certificate signed by unknown authority
```

This does not happen every time, but enough to be annoying. Usually this problem resolves itself after a system restart.

**What you expected to happen**: On my old hardware I could switch context all the time, never encountering this error. 

**How to reproduce it**: Difficult. It may work hours on end at times. Right now, I can't get any project to work. I also tried reinstalling `kubectl` to no avail, so I guess it's as easy as:
- Install `gcloud`
- Run `gcloud init`
- Install `kubectl`
- Switch context
- Run any `kubectl` command (such as `kubectl get pods`). Sometimes it works, sometimes it spits out the error above.

**Comment by jeffkpayne** [comment]
I am seeing the same behavior, also on macOS and GCP (almost identical specs to above).  I've been using `kubectl` all day, with other intermittent errors, but I *just* created a deployment a few minutes ago, then started seeing this error...

**Comment by jeffkpayne** [comment]
OK, so I'm fairly new to all this stuff, but I'm guessing there's a problem (either in `kubectl` or on the GCP side) that results in the `~/.kube/config` getting out of sync or otherwise corrupted.  Looking at that file, I noticed that the cert that was being rejected did, in fact, have an expiry date in the past.  Simply running `gcloud container clusters get-credentials <cluster-name>` *did not* resolve the issue.  So, of course, I manually modified the file, removing the existing records for the target cluster.  After that, running `gcloud container clusters get-credentials <cluster-name>` resolved the issue and I was able to use `kubectl` again without any auth-related error.

**Comment by sanderploegsma** [comment]
Right, my behaviour seems to be slightly different. I just caught another of these errors, and while @jeffkpayne mentions a wrong expiry date, my config file doesn't have any config at all for the cluster. For reference, here is the `~/.kube/config` file at the exact time the error occurs:
``` yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <obfuscated>
    server: <server ip>
  name: gke_meethue-live_europe-west1-b_hue-niverse
- cluster:
    certificate-authority-data: <obfuscated>
    server: <server ip>
  name: gke_cl-dev_europe-west1-b_hue-niverse
- cluster:
    certificate-authority-data: <obfuscated>
    server: <server ip>
  name: gke_cl-portal_europe-west1-b_hue-niverse
contexts:
- context:
    cluster: gke_meethue-live_europe-west1-b_hue-niverse
    user: gke_meethue-live_europe-west1-b_hue-niverse
  name: gke_meethue-live_europe-west1-b_hue-niverse
- context:
    cluster: gke_cl-dev_europe-west1-b_hue-niverse
    user: gke_cl-dev_europe-west1-b_hue-niverse
  name: gke_cl-dev_europe-west1-b_hue-niverse
- context:
    cluster: gke_cl-portal_europe-west1-b_hue-niverse
    user: gke_cl-portal_europe-west1-b_hue-niverse
  name: gke_cl-portal_europe-west1-b_hue-niverse
current-context: gke_meethue-live_europe-west1-b_hue-niverse
kind: Config
preferences: {}
users:
- name: gke_meethue-live_europe-west1-b_hue-niverse
  user:
    auth-provider:
      name: gcp
- name: gke_cl-dev_europe-west1-b_hue-niverse
  user:
    auth-provider:
      config:
        access-token: <valid access token>
        expiry: 2017-02-09 14:50:44.440458
      name: gcp
- name: gke_cl-portal_europe-west1-b_hue-niverse
  user:
    auth-provider:
      config:
        access-token: <valid access token>
        expiry: 2017-02-08 11:34:25.977650
      name: gcp
```
