### ISSUE TITLE
controller-manager fails to read ECDSA private key

### ISSUE THREAD

**Issue by pizzarabe** [kubernetes/kubernetes#40589]
**Kubernetes version**

Serverversion 1.5.2 (running Hyperkube v1.5.2_coreos.1 (https://quay.io/repository/coreos/hyperkube))

**Environment**:
- Bare-Metal
- Coreos 1235.6.0 (Kernel 4.7.3-coreos-r2)

**What happened**:
kube-controller-manager with ecdsa key fails to start 
`
F0127 09:59:04.041033       1 controllermanager.go:181] error running controllers: Error reading key for service account token controller: error reading private key file /etc/kubernetes/ssl/alien1.rz.tu-bs.de.key.pem: data does not contain a valid RSA or ECDSA private key`

The key is valid (and works with e.g. the api-server)

```
cat /etc/ssl/alien.key.pem

-----BEGIN EC PARAMETERS-----
Bgg[...]
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQ[...]
-----END EC PRIVATE KEY-----
```

Command used to create the key:

`openssl ecparam -out /etc/pki/alien_certs/private/$hostname -name prime256v1 -genkey`

```
cat /etc/kubernetes/manifests/kube-controller-manager.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: quay.io/coreos/hyperkube:v1.5.2_coreos.1
    command:
    - /hyperkube
    - controller-manager
    - --master=http://127.0.0.1:8080
    - --leader-elect=true
    - --service-account-private-key-file=/etc/kubernetes/ssl/alien.key.pem 
    - --root-ca-file=/etc/kubernetes/ssl/alien-chain.cert.pem
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/ssl/alien
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
```
