### ISSUE TITLE
Consider exposing node labels via downward api

### ISSUE THREAD

**Issue by simonswine** [kubernetes/kubernetes#40610]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): downward api node labels

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

I think the downward API should support exposing the node labels on which the pod it is running. While I understand that the Pod should not be coupled too much with the node it is scheduled to. But I think there are certain scenarios that require the pod  to have more information about it's host.

- ***failure-zones*** like rack names on premise or availability zones in cloud
- ***instance-types*** for adapting thread settings per instance type
- other labels like local ssd storage available 

This helps applications that are cloud-native to understand where they are located. While this could be achieved using API calls to the node object, I think it should be supported by the downward API. A node object would expose way more information that should not be available to any pod. In OpenShift's default configuration there is access to the Node objects prevented by default.

@mattbates @smarterclayton @bprashanth

**Comment by smarterclayton** [comment]
There *could* be security implications for some types of clusters (exposing information the admin doesn't want the pod to have, like the exact core architecture).  That said, for most deployments it doesn't seem completely unreasonable.  A per node setting might decide whether to expose it or to return an empty map.

**Comment by tpetracca** [comment]
This was previously explored in #25957

**Comment by dwilliams782** [comment]
Is this still being considered? I'm currently trying to find a sensible way to retrieve the zone a pod is scheduled in for rack awareness, as per the original use case.

**Comment by laurieodgers** [comment]
We're looking at doing this for a per-zone load balancer, and per-region load balancer on a single deployment. Our use case is that customers must be able to bind multiple times to multiple failure domains. This could be achieved with 3x deployments (one per zone) but it would be much nicer to only have to worry about a single deployment.

**Comment by discordianfish** [comment]
I think this should be brought up in a sig-node meeting, otherwise I doubt this will get attention and ultimately get closed off by @fejta-bot

**Comment by thockin** [comment]
I am in favor of something like this.  The real problem here is that most people seem to want this for topology information and that information is somewhat arbitrary.  Hostname/Zone/Region are codified, so they get the most attention, but there is some demand for other topology.  That leads me to assert that the common API is labels and not something special for topology info.

**Comment by bjhaid** [comment]
would folks be comfortable with kubelet having a configurable whitelist of node-labels that can be consumed by pods via the downward-api. I am constantly hitting snags that having this feature would have unblocked or prevented weird workarounds

**Comment by thockin** [comment]
Can we talk about concrete needs?  What snags are you hitting?

I have heard concrete need for topology info, which is stored as labels and is indistinguishable from other labels.  That (rightly) sets off alarms for security-conscious people.  Do we need to first-class topology?  I'm less confident in that.

The last thing we really want is another configuration knob that admins have to know about to be secure...

**Comment by erik-stephens** [comment]
Our use case is being able to inform elasticsearch pods about topology so that we can make sure shards get placed across failure domains (eg racks).  Currently, we have to contort ourselves through some awkward initContainers to get those details into elasticsearch configs.

**Comment by thockin** [comment]
ACK.  Another +1 for topology.  I am not sure the right answer.  Moving
topology to a distinct struct would make it easy to copy that info into
pods, but there's a lot of momentum around labels already, so we'd have to
do both for the indefinite future.

As far as I know, nobody is signed up to try to push that yet.

**Comment by bjhaid** [comment]
> Can we talk about concrete needs? What snags are you hitting?

Sorry for not providing an helpful case :) All my snags have all been topology related, app needs to know what region/az or datacenter it is deployed to.

> As far as I know, nobody is signed up to try to push that yet.

Where do I get to sign up for this :) I don't mind pushing it if I get guidance

**Comment by 2rs2ts** [comment]
My use case is for the EC2 instance ID (which is automatically added as a label by the cloud provider) to be added as an environment variable for a container. Since I lacked this feature I had to provide a workaround (granted my pod access to the AWS metadata FUSE we use at my company https://github.com/jszwedko/ec2-metadatafs) that I wasn't really keen on. Having pod labels available in the downward API just makes sense honestly, I don't know why we need to introduce brand new features for this :D

**Comment by thockin** [comment]
> Where do I get to sign up for this :) I don't mind pushing it if I get guidance

You sign up by saying "I'd like to tackle this". :)

As for guidance, the real problem is that I don't know what the right design is.  The way I would usually start such an effort is with a brainstorm doc - try to pin down the kernel of the requirements expressed here and then dream up 10 different ways we could solve it, no judgement on good/bad ideas.  Then write the most aggressive pros/cons you can for each.  Then we discuss.

e.g. 

1) we could add node labels as a downward API "fake" field path
1b) we could make new syntax for field paths that follow object ref pointers
2) we could literally copy node labels to pods
3) we could add a new node topology block and copy THAT into pods
4) we could add a link-local metadata API for use at run-time
5) we could add a new type of volume/envFrom source that is node-metadata
...

**Comment by bjhaid** [comment]
> You sign up by saying "I'd like to tackle this". :)

I'd like to tackle this :)

Thanks for all of this context, I'll start writing some doc and share as soon I have something

**Comment by intlabs** [comment]
Like @erik-stephens failure domain awareness would be a prime motivator for this: in our case Ceph.

**Comment by bjhaid** [comment]
For folks interested myself and @thockin had a brainstorm in this doc https://docs.google.com/document/d/1fH64mEfZH597luup-ZBfBNkiTVjfoFYGEa-G1G_TM6A/edit#, I wrote something that covered the last idea (which is Tim's preference): https://github.com/bjhaid/node-labels-to-files

**Comment by erik-stephens** [comment]
Thanks @bjhaid, this helps but for my use-case (elasticsearch), I will still need another initContainer in order to get those values into a form that elasticsearch will read (eg write updated config, inject environment variables).  Maybe I can use something like [envdir](https://cr.yp.to/daemontools/envdir.html).  Some soft goals I'm aiming for:

1. Minimal changes to vendor's image
1. Use default entrypoint & command
1. Minimal initContainers

Chiming in here in case others on this thread have ideas.  I was hoping there was a stock/std linux way to do what `envdir` does but I couldn't find.

**Comment by danielmotaleite** [comment]
we need this for 2 user cases:
- nodes zone info in pod labels, so service selector can deliver traffic inside the same zone instead of doing cross zone requests
- environment variable with node zone info, so cluster based apps can have the correct info. It can also be used to request the correct in-zone dns and add the correct labels to monitoring ( like /metrics) and logs 

While we can use a initcontainer to set this, it require giving pods `patch` permissions to affected pods and so opening a security hole to allow some hacker to change kubernetes setup


My proposal is to have a node "flag"/label/annotations that would enable label propagation and what labels are allowed to be propagated (say: `node-labels-propagation: false` (default) , `true` (all labels) , `'{"failure-domain.beta.kubernetes.io/zone","failure-domain.beta.kubernetes.io/region"}' `)

- This allow the admin to control the info node leak to pods.

Then in the pods, it would be required to request what info they want, with two annotation, one for labels and another for environment ( say: `pod-labels-from-nodes-labels: false, true , '{"...","..."}' ` for label copy and `pod-enviroment-from-nodes-labels: false, true, '{..}' ` for environment). If needed, another option for a volume with the info (`pod-volume-from-node-labels: ...`)

- This allow the pod admin to request only what is needed and ignore any other label that he doesn't need

**Comment by Bessonov** [comment]
I'm not sure, that `fejta-bot` is useful. Why every one subscriber must get this message, just because no body take care about issues and hope that they are automagically get closed by time?

/remove-lifecycle stale

**Comment by discordianfish** [comment]
@Bessonov tell that @fejta 
I've just stopped filling issues I don't have the resources to fix right away.

**Comment by hzxuzhonghu** [comment]
One similar use case from istio: to support locality load balancing, we need to watch all nodes of the cluster to acquire its topology labels such as`[topology.kubernetes.io/region, topology.kubernetes.io/zone]`. We just need these locality info, but we have to get all the nodes, which is a waste of lot of memory. It would be better if k8s provide a way to allow setting these topology info directly into pod.

**Comment by jpmcb** [comment]
+1 for this as well

We would like access to this information in order for a highly available data store service to know which `[topology.kubernetes.io/region, topology.kubernetes.io/zone]` the data store processes are running. Without this information, we could end up in a scenario where data is stored in only a single region or zone. Upon that region becoming unavailable, it's possible the data store service would be 0% available.

**Comment by tedyu** [comment]
```
node-labels-propagation: false (default) , true (all labels) ...
```
I think when node label is allowed to propagate, 'all labels' should be avoided since there may be information which admin doesn't want to reveal.
Listing specific labels to propagate would serve the use cases.

**Comment by Feder1co5oave** [comment]
It is a bit sad seeing this feature, with so many practical use cases listed above, left unanswered for so long.
As a fully owned, single tenant Kubernetes user, I take care of both nodes AND pods, and I've been needing this feature for a long time.
It it utterly pointless to set topology information on nodes if that information can not be propagated to pods to implement intelligent, topology-aware deployments. Besides, pod affinity/antiaffinity rules already rely on node labels, and that is not considered a security concern.

I have never considered hiding nodes' labels a security feature.

I am wondering if we can tackle the security concerns by adding a clause that the user creating (or the serviceaccount associated with) a pod that requests node's information via one of the methods proposed by @bjhaid in the linked google doc, needs to have the `get node` permission?

**Comment by s97712** [comment]
> ```
> node-labels-propagation: false (default) , true (all labels) ...
> ```
> 
> I think when node label is allowed to propagate, 'all labels' should be avoided since there may be information which admin doesn't want to reveal.
> Listing specific labels to propagate would serve the use cases.

I think a better solution is allow to set different value of configMap/secret  for different nodes

**Comment by anyasabo** [comment]
As another +1 for topology info. [Topology spread constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) let you easily spread pods across different regions/racks etc, but there's no (easy) way for the pod to know where it is actually scheduled, so the application can't make smart decisions based on topology. Even making only `topology.kubernetes.io` labels available would be an improvement.

**Comment by iMartyn** [comment]
Another solid use-case is in a cluster-per-environment setup where a node label can be added (e.g. in gke or eks you could add a label `cluster-environment: staging` to all nodes in a cluster) and then that can be provided to workloads via the downward api to behave appropriately according to business logic.
This obviously doesn't fit with a `topology` structure, so I might propose that it is maybe slightly too narrow in scope.  Something perhaps to consider would be a format for "exposable" labels.  Perhaps something along the lines of `user/.*` being exposable.
Already regretting this comment just because of the notifications I'll get from fejta forever as it languishes.

**Comment by bozaro** [comment]
I want to have node zone name in envronment variable to use some latency-critical services strongly in the same zone (for example: `mongos`).

`mongos` is a separate service from mongodb, through which all requests in a sharded configuration pass (app <-> mongos <-> mongodb). Since these are database queries, each hop has a significant impact on overall performance.

In bare hardware we deploy and use mongos in the same host (`localhost`) for reduce traffic and latency.

In Kubernetes envrinoment we try to:
 - Reproduce localhost topology by DaemonSet deploy. This does not work well due to very different resource consumption from node to node and service to service.
 - Deploy mongos to same pod. This leads to too large RAM and CPU overhead.
 - Deploy separate mongos Service to every zone. This solution looks very ugly, as the application has to execute a lot of code to get the zone from the node's metadata. Moreover, this code is different in each language. If it was possible to add a zone to an environment variable, it would be much easier.

**Comment by steffeneichler** [comment]
Hi,

we need to propagate the node labels
failure-domain.beta.kubernetes.io/region
failure-domain.beta.kubernetes.io/zone
topology.kubernetes.io/region
topology.kubernetes.io/zone
to our pods because we need the information to distribute elasticsearch shards correctly and more safely.

So it would be great if this possibility could be implemented.

**Comment by howardjohn** [comment]
Given EndpointSlice is removing `topology`, this becomes even more important, as the only source of region/zone is now the node.

**Comment by hzxuzhonghu** [comment]
> Given EndpointSlice is removing topology

Any links? @howardjohn

**Comment by howardjohn** [comment]
https://opensource.googleblog.com/2020/11/kubernetes-efficient-multi-zone.html, https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2030-endpointslice-subsetting, and https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/2086-service-internal-traffic-policy/README.md

After thinking about it a bit more I don't think it is directly related to this issue though (needing to know the topology of all endpoints vs your own node labels) but this would still help in many other cases

**Comment by Feder1co5oave** [comment]
@steffeneichler

This is what I had to do to implement rack-awareness for elasticsearch in kubernetes:

Add rack awareness in elasticsearch.yml:
```yaml
cluster.routing.allocation.awareness.attributes: rack
```

Label my nodes with their rack-information:
```bash
kubectl label node my-node topology.kubernetes.io/rack=L101B09
```

Extract node information via kubectl, and export them to elasticsearch via env variable:
```yaml
apiVersion: apps/v1
kind: StatefulSet
spec:
  serviceName: elasticsearch
  template:
    spec:
      serviceAccountName: elasticsearch

      initContainers:
      - name: get-rack
        image: kubectl
        command:
        - bash
        - -c
        - |
          set -ex
          RACK=$(kubectl get node $NODE_NAME -o jsonpath='{.metadata.labels.topology\.kubernetes\.io/rack}')
          echo "$RACK" > /tmp/es-rack
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: tmp
          mountPath: /tmp/

      containers:
      - name: elasticsearch
        image: elasticsearch
        command:
        - bash
        - -c
        - |
          set -ex
          env "node.attr.rack=$(</tmp/es-rack)" /usr/local/bin/docker-entrypoint.sh eswrapper
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: node.attr.node
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: tmp
          mountPath: /tmp/
      volumes:
      - name: tmp
        emptyDir: {}
```

Aaaaand of course you need RBAC to allow the serviceaccount to extract node information:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: elastic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearch-get-nodes
  namespace: elastic
rules:
- apiGroups: [""]
  resources: [nodes]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elasticsearch-get-nodes
  namespace: elastic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elasticsearch-get-nodes
subjects:
- kind: ServiceAccount
  name: elasticsearch
  namespace: elastic
```

Yes, it is this ugly. I actually could have done it all in the main container by creating an image with both elasticsearch and kubectl.

**Comment by steffeneichler** [comment]
Hi @Feder1co5oave,

I found this way too. But this is a very ugly way. The best way would be to propagate the node topoloy information to the pods like the nodename.

**Comment by natereid72** [comment]
is this ever going to be addressed? perhaps a label for nodes prefaced with an indicator for downwardapi. e.g. dapi-region, dapi-az, etc. This way all of the node labels aren't exposed, but ones the admin wants are.

**Comment by immanetize** [comment]
Wow, this has been going for a long time.  I would really like to have a clear picture of how my pods are balanced between availability zones.  I can't imagine I am the only one operating kubernetes clusters in multiple failover zones who would benefit from this perspective.  Can anyone explain to me at a high level how region/AZ labels on metrics can be used to compromise the cluster or it's workload?  I don't understand the objection here, there are clear benefits to the proposal.

**Comment by thockin** [comment]
The simple answer is that it will get implemented when someone steps up to design and implement it.  There are hundreds and hundreds of these issues - really decent ideas - and they all need someone to step up to drive it.

I know that's not what you wanted to hear, but this project has a finite number of (mostly volunteer!) contributors with finite hours per week.  If you have some time, why not write a KEP?  It's not hard, but it needs some follow-thru.

In the interim, you can always run `kubectl get ... | jq ...` in a container in your pod, and save the output to a file on an emptydir volume.

**Comment by immanetize** [comment]
Absolutely, I do understand how community contributions work. I've read through two issues here with somewhat unsubstantiated privacy concerns, my hope was to get those concerns overtly documented here to help such contributions move forward.

**Comment by s97712** [comment]
What about the solution https://github.com/kubernetes/kubernetes/issues/93999 ?

**Comment by steffeneichler** [comment]
@s97712: I'm not sure how #93999 could help here to fix the problem. One thing is the node label and #93999 is about nodeSecret or configmap.

**Comment by s97712** [comment]
> @s97712: I'm not sure how #93999 could help here to fix the problem. One thing is the node label and #93999 is about nodeSecret or configmap.

Although the names are different, they are all data in essence.

**Comment by steffeneichler** [comment]
> 
> 
> > @s97712: I'm not sure how #93999 could help here to fix the problem. One thing is the node label and #93999 is about nodeSecret or configmap.
> 
> Although the names are different, they are all data in essence.

Everything is data. A node label is an existing node property. The task here is to find a way to expose this existing information to pod in the same way as the node name. #93999 is a request for new kind of information.

**Comment by laplasz** [comment]
in my point of view these node labels should be available by default as env variable...

**Comment by steffeneichler** [comment]
> 
> 
> in my point of view these node labels should be available by default as env variable...

that would be great.

**Comment by antaloala** [comment]
What about implementing it as a new kind of volume (e.g. nodeProperties) that a pod spec could require?
kubelet would be in charge of representing the requested node properties (in the volumes entry definition included in the Pod spec) as files, "mounting" it in the pod's container's specified path; those requested node properties (i.e. labels) configured in kubelet as "restricted" would be exposed to the pod's container as an empty file.

I think this is a cleaner solution than using the downward API (as it was thought for exposing to a pod's container some pod's fields, but not fields from another API object).

**Comment by m00lecule** [comment]
HI, also seeking for this feature. It also might be useful for reducing latency. Imagine a situation when we host each kafka node and k8s worker node in separate AZ. Then with additional metadata pod should pick the closest destination to provide the better network performance. I believe its a bit complicated, but this feature would make it possible.

**Comment by intjonathan** [comment]
>Imagine a situation when we host each kafka node and k8s worker node in separate AZ. Then with additional metadata pod should pick the closest destination to get a better network performance.

We're in exactly this situation and it's not just performance, but cost. Cross-AZ Kafka traffic is serious money at scale. Right now we're relying on GET requests to the node metadata API, but that's going to get locked down for compliance. A pattern for exposing certain fields and not others would satisfy both needs nicely.

**Comment by wmgroot** [comment]
It reads to me that a PR that allowed cluster admins to selective choose which metadata is made available to the downward API would address the security concerns in https://github.com/kubernetes/kubernetes/pull/25957#issuecomment-228041766

**Comment by derekwaynecarr** [comment]
I think its reasonable to open a KEP for this proposal for a specific set of allowed node labels for usage in downward API.  Labels have been better normalized since this issue was originally opened and expanding labels for particular use cases could be useful.  Allowing all labels though may prove problematic for users that label nodes with security sensitive information that is not to be exposed to the workload.

**Comment by schaefec** [comment]
Having access to a selected 'allow-listed' set of node labels through the downward API would address my use-case as well as long as the following [(Well-Known)](https://kubernetes.io/docs/reference/labels-annotations-taints/) labels would be part of this set:

[topology.kubernetes.io/zone](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone)
[topology.kubernetes.io/region](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesioregion)

I understand and agree that exposing all node labels is definitely not wanted due to the concerns mentioned by @derekwaynecarr

Has a KEP been created for this already?

**Comment by vassilvk** [comment]
Injecting topology awareness into pods can be accomplished with the [KubeMod](https://github.com/kubemod/kubemod) operator.

Here's a KubeMod ModRule which intercepts the event of any pod being scheduled on a node, then copies the node's `topology.kubernetes.io/region` and `topology.kubernetes.io/zone` labels into the pod's labels before the pod's containers are created.

```yaml
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: inject-topology-labels
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: ".*"
  admissionOperations:
    - UPDATE

  match:
    # Match pods...
    - select: '$.kind'
      matchValue: 'Pod'
    # ...which have access to the node's manifest through the synthetic ref injected by KubeMod.
    - select: '$.syntheticRefs.node.metadata.labels'

  patch:
    # Grab the node's region and zone and put them in the pod's corresponding labels.
    - op: add
      path: /metadata/labels/topology.kubernetes.io~1region
      value: '"{{ index .Target.syntheticRefs.node.metadata.labels "topology.kubernetes.io/region"}}"'
    - op: add
      path: /metadata/labels/topology.kubernetes.io~1zone
      value: '"{{ index .Target.syntheticRefs.node.metadata.labels "topology.kubernetes.io/zone"}}"'
``` 

Having KubeMod and the above ModRule deployed to your cluster, transparently stamps out all pods with their node's topology labels whenever they get scheduled on a node. This makes topology information available to the pod's containers through Kubernetes Downward API.

For example, assuming that you have the above ModRule, the following Deployment will push the region and availability zone its pods are deployed to, into their containers' environment variables `TOPOLOGY_REGION` and `TOPOLOGY_ZONE`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    metadata:
      annotations:
        # Tell KubeMod to monitor this deployment's pods for scheduling events.
        ref.kubemod.io/inject-node-ref: "true"
    spec:
      containers:
      - name: my-container
        image: my-container-image:v1.2.3
        env:
          - name: TOPOLOGY_REGION
            valueFrom:
              fieldRef:
                # The following label will be populated by ModRule inject-topology-labels.
                fieldPath: metadata.labels['topology.kubernetes.io/region']
          - name: TOPOLOGY_ZONE
            valueFrom:
              fieldRef:
                # The following label will be populated by ModRule inject-topology-labels.
                fieldPath: metadata.labels['topology.kubernetes.io/zone']
```
