### ISSUE TITLE
Stop edit from updating last-applied-config annotation and let replace respect --save-config

### ISSUE THREAD

**Issue by ymqytw** [kubernetes/kubernetes#40626]
From discussion in https://github.com/kubernetes/community/pull/287#issuecomment-275445705

We should consider drop the functionality of updating `last-applied-config` annotation in `kubectl edit`.
Because `kubectl edit` does a 2-way diff and will save all the fields that exist in the live config to the annotation. An `apply` operation after `edit` may delete fields unintentionally.

E.g. create a deployment using `apply -f` 
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.10
...
```
Object before `edit`. Some fields are added by controller etc. (This can be mocked by `kubectl patch`)
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
  replicas: 1
  revisionHistoryLimit: 3 # this is a field added without touching the `last-applied-annotation` annotation
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.10
...
```
Then edit a field, e.g. `replicas`: 1 -> 5
After edit all field are saved in the annotation, then `kubectl apply` the original config.
`revisionHistoryLimit: 3` has been deleted.
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.10
...
```

This behavior is not what we want.

Another issue: `kubectl replace` doesn't respect `--save-config`. 

Old behavior:
`kubectl replace` saves the config in the annotation if `--save-config=true`. If `--save-config=false` and the annotation already exists, it still updates the annotation.

New Behavior:
`replace` respects the `--save-config` flag. If the user specify `--save-config=true`, `replace` will either creates or updates the annotation. If the user specify`--save-config=false`, it won't touch the annotation. If the flag is unspecified, `replace` will update the annotation iff it already exists.

cc: @pwittrock @liggitt @kubernetes/sig-cli-misc
