### ISSUE TITLE
Are there plans to make the ordinal index for a statefulset available dynamically within a config file?

### ISSUE THREAD

**Issue by deitch** [kubernetes/kubernetes#40651]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): statefulset ordinal config
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Kubernetes version** (use `kubectl version`): 1.5.2

With a StatefulSet, the hostname is set to `name-`_ordinal_. It is a common pattern with the types of services that go into StatefulSets to expect the unique ID of the service to be passed, e.g. as an env var. 

This causes all sorts of interesting contortions, like extending the official zookeeper image to try and guess the ordinal index of the set from the hostname and then set another var with the index.

It would be good if there were some templating format so that the property could be set directly in the config file. E.g. (simplified):

```yml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zk
spec:
  serviceName: zk-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zk
        imagePullPolicy: Always
        image: zookeeper
        resources:
        env:
        - name : ZOO_MY_ID
          value: ${{ordinal}}
        - name : ZOO_SERVERS
          value: server.0=zk-0:2888:3888 server.1=zk-1:2888:3888 server.2=zk-2:2888:3888
        - name : ZOO_TICK_TIME
          value: "2000"
        - name : ZOO_INIT_LIMIT
          value: "10"
        - name : ZOO_SYNC_LIMIT
          value: "5"
```

**Comment by kargakis** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by smarterclayton** [comment]
There is an issue to expose this downwards via the downward API from each pod.

**Comment by deitch** [comment]
> via the downward API

I can see that. I still think a go-template syntax is cleaner, but however we get it exposed is good. 

Is that issue open? Happy to close this one and follow that one if it is.

**Comment by smarterclayton** [comment]
Original issue: https://github.com/kubernetes/kubernetes/pull/30860

Proposal to expose annotations:
https://github.com/kubernetes/community/pull/147

Any dynamic values on pods must be exposed via the downward API (nothing
prevents you from using Helm to do it on creation, but the API and clients
need explicit fields to tell them what to do unambiguously).

**Comment by deitch** [comment]
So it would look something like?

```yml
        env:
        - name: ZOO_MY_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.pod.beta.kubernetes.io/statefulset-index
```

or something like that? 

I notice that the issue is set to close automatically due to inactivity on 24 Feb, and that it still talks about PetSets?

**Comment by foxish** [comment]
cc @kow3ns

**Comment by smarterclayton** [comment]
field paths must point to a valid part of the JSON struct - so it has to be
"metadata.annotations['spec.pod.beta.kubernetes.io/statefulset-index']" but
we need to finish the proposal out.

**Comment by deitch** [comment]
`"metadata.annotations['spec.pod.beta.kubernetes.io/statefulset-index']"`

How does that look in the config?

**Comment by smarterclayton** [comment]
fieldPath: <what i typed>

**Comment by deitch** [comment]
So:

```yml
        env:
        - name: ZOO_MY_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['spec.pod.beta.kubernetes.io/statefulset-index']
```

Got it, thanks. Man, that is one painful deep structure.

**Comment by deitch** [comment]
@smarterclayton I am closing this in favour of that merged PR https://github.com/kubernetes/community/pull/147

**Comment by aliakhtar** [comment]
Has this been merged yet? I'm getting an error when I try to do the following:

```
            - name: ZOOKEEPER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['spec.pod.beta.kubernetes.io/statefulset-index']
```

**Comment by aliakhtar** [comment]
Given how many popular tools (Kafka, Zookeeper) require a stable node ID, for which this ordinal field would be perfect, its really surprising that this obvious feature has not been implemented / integrated yet.

This should be merged asap.

**Comment by mandrean** [comment]
I'm doing this little init-hack for my ZK:
```
        command:
        - sh
        - c
        - export ZOOKEEPER_SERVER_ID =$(hostname | grep -o "[[:digit:]]*$") && \/etc/confluent/docker/run
```

**Comment by deitch** [comment]
So the exposure of a single annotation has been merged in, but there is no annotation for the index itself? i.e. the following does not exist as an annotation?

```
spec.pod.beta.kubernetes.io/statefulset-index
```

**Comment by mikesparr** [comment]
Here's a workaround that worked for me with a Kafka cluster using lifecycle hooks until this feature is available:
```
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "export KAFKA_BROKER_ID=${HOSTNAME##*-}"]
```

**Comment by oleg-kiselev** [comment]
If you have `"hostNetwork: true"` set in the spec, $HOSTNAME is the name of the node on which the pod is executing.

A more reliable work-around to get the pod's unique name and enumeration index is to expose `metadata.name` using downward API:
```
...
kind: StatefulSet
metadata:
     name: my-test-pod
spec:
     template:
         spec:
              containers:
                     ....
                     env:
                            - name MY_POD_NAME
                               valueFrom:
                                       fieldRef:
                                              fieldPath: metadata.name   
```
`${MY_NODE_NAME}` will be unique in the cluster and have the format like `my-test-pod-index`.  You can parse the index out of that.

**Comment by zhoulouzi** [comment]
@mikesparr  @oleg-kiselev   a great workaround

**Comment by ianseyer** [comment]
It'd be great to have this index available from _within_ the statefulset config; certain applications require, for example, special behaviors to be executed by the first member of a network, to "bootstrap" the network. I don't see an elegant solution to this, even  with the downwards API.

**Comment by cjbottaro** [comment]
Any idea how to use the `metadata.name` of a statefulset to get a key in a `configmap`?

**Comment by mfilotto** [comment]
Any update on this ?
Would be awesome to get the ordinal index without any script

**Comment by chhetripradeep** [comment]
Is there any workaround for achieving this ?

**Comment by okgolove** [comment]
+1

**Comment by aalubin** [comment]
+1

**Comment by harishanchu** [comment]
I just added a init container to write server id to /data/myid file like below(where /data directory is volume mounted to both init and main container):
```yml
      initContainers:
      - command:
        - /bin/bash
        - -c
        - |-
          set -ex;
          mkdir -p "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR";
          chown "$ZOO_USER:$ZOO_USER" "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR"
          if [[ ! -f "$ZOO_DATA_DIR/myid" ]]; then
            echo $HOSTNAME| rev | cut -d "-" -f1 | rev > "$ZOO_DATA_DIR/myid"
          fi
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: zookeeper:3.4.9
        imagePullPolicy: IfNotPresent
        name: zookeeper-init
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /data
          name: zookeeper-storage

```
With this zookeeper ensemble works fine.

**Comment by juandiegopalomino** [comment]
+1

**Comment by mikesparr** [comment]
+1 ;-)

**Comment by JuanManuelVizcainoAbad** [comment]
+1

**Comment by horan-geeker** [comment]
It works for me
statefuleset spec.template.spec.containers
```
lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "echo ${HOSTNAME##*-} > /data/myid"]
```

**Comment by joshshn** [comment]
+1

**Comment by mancini0** [comment]
+1

**Comment by chenmin1992** [comment]
> I just added a init container to write server id to /data/myid file like below(where /data directory is volume mounted to both init and main container):
> 
> ```yaml
>       initContainers:
>       - command:
>         - /bin/bash
>         - -c
>         - |-
>           set -ex;
>           mkdir -p "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR";
>           chown "$ZOO_USER:$ZOO_USER" "$ZOO_DATA_LOG_DIR" "$ZOO_DATA_DIR" "$ZOO_CONF_DIR"
>           if [[ ! -f "$ZOO_DATA_DIR/myid" ]]; then
>             echo $HOSTNAME| rev | cut -d "-" -f1 | rev > "$ZOO_DATA_DIR/myid"
>           fi
>         env:
>         - name: HOSTNAME
>           valueFrom:
>             fieldRef:
>               fieldPath: metadata.name
>         image: zookeeper:3.4.9
>         imagePullPolicy: IfNotPresent
>         name: zookeeper-init
>         securityContext:
>           runAsUser: 0
>         volumeMounts:
>         - mountPath: /data
>           name: zookeeper-storage
> ```
> 
> With this zookeeper ensemble works fine.

And how to use myid in args? it seems args can't execute bash script.

**Comment by debu99** [comment]
+1

**Comment by deitch** [comment]
It looks like the proposal was accepted, but was it actually implemented?

**Comment by Zetanova** [comment]
The ordinal index could be used in Set selector
Somehow there is no option to spread the replicas over a set.

It could be implented over an new "Ordinal" operator
The operator could then pick one item of the item based on the oridinal index.
```
key: rack, value: set[ oridnal % set.length ]
```

example to alternate a volumeClaimTemplates
```
volumeClaimTemplates:
  spec:
  selector:
    matchExpressions:
      - {key: rack, operator: Ordinal, values: [rackA, rackB, rackC, rackD]}
      - {key: san, operator: Ordinal, values: [sanA, sanB]}
```

**Comment by ktreese** [comment]
@oleg-kiselev 

I have a question on the statement

> ${MY_POD_NAME} will be unique in the cluster and have the format like my-test-pod-index. You can parse the index out of that.

Is there an example on how to parse the index from `metadata.name` inline?  Or is this solution more for setting an env var MY_POD_NAME to then parse via a script from an init container or otherwise?  Thanks for helping provide some clarification!!

**Comment by gaveezy** [comment]
Any workaround solution to this without using shell command? I'm using a distroless image so shell is N/A.

**Comment by SleepyBrett** [comment]
It's absurd that this hasn't been addressed, there was a feature request for this back when it was called `petset`.

**Comment by zemmet** [comment]
+1

**Comment by rivenhk** [comment]
+1

**Comment by Xtigyro** [comment]
+1

**Comment by mk811** [comment]
It looks there is no update yet, I've made a workaround by developing custom k8s admission controller - [sts-annotator](https://github.com/mk811/sts-annotator). This custom controller is adding annotations of pod index and pod replicas to Statefulset Pod. All the purpose is to allow PODs to get those values from Environment Variable. 

In my use case, I need to access to POD Index from Spring Boot `application.yaml`, which meant there was only one solution - Get the value from Environment Variable. if anyone likes my solution,  I will highly appreciate it.

**Comment by rivenhk** [comment]
> It looks there is no update yet, I've made a workaround by developing custom k8s admission controller - [sts-annotator](https://github.com/mk811/sts-annotator). This custom controller is adding annotations of pod index and pod replicas to Statefulset Pod. All the purpose is to allow PODs to get those values from Environment Variable.
> 
> In my use case, I need to access to POD Index from Spring Boot `application.yaml`, which meant there was only one solution - Get the value from Environment Variable. if anyone likes my solution, I will highly appreciate it.


another solution i used for spring boot application:
// in k8s statefulset yaml
command: ["sh"]
args: ["-c", "ENV_ORDINAL=${HOSTNAME##*-} java -jar uber.jar"]

**Comment by mk811** [comment]
> another solution i used for spring boot application:
> // in k8s statefulset yaml
> command: ["sh"]
> args: ["-c", "ENV_ORDINAL=${HOSTNAME##*-} java -jar uber.jar"]

Thank you for sharing. As I wanted to have POD Replicas in env var as well and also wanted a consistent solution for all applications, I developed the custom controller though, your solution is also great.

**Comment by ivanpang1996** [comment]
> This works for me
> statefuleset spec.template.spec.containers
> 
> ```
> lifecycle:
>     postStart:
>         exec:
>         command: 
>             - "/bin/bash"
>             - "-c"
>             - |
>             sed -i "s/${HOSTNAME}\.[^:]*:/0.0.0.0:/g" /conf/zoo.cfg
>             echo $((${HOSTNAME##*-}+1)) > /data/myid
> ```
> 
> and you also need to replace owner ip to 0.0.0.0 that in zoo.cfg file

myId is working.
but zoo.cfg sometimes works and sometimes not. 
I don't get it.

**Comment by mk811** [comment]
@ivanpang1996 
You should not use `postStart` here because `postStart` is async. 
k8s doesn't ensure `postStart` completed before your application starts running.
If you want to output the id to local as a file, I suggest you use `initContainers` as posted by @harishanchu .
https://github.com/kubernetes/kubernetes/issues/40651#issuecomment-421392345

**Comment by cocofish** [comment]
> The ordinal index could be used in Set selector
> Somehow there is no option to spread the replicas over a set.
> 
> It could be implented over an new "Ordinal" operator
> The operator could then pick one item of the item based on the oridinal index.
> 
> ```
> key: rack, value: set[ oridnal % set.length ]
> ```
> 
> example to alternate a volumeClaimTemplates
> 
> ```
> volumeClaimTemplates:
>   spec:
>   selector:
>     matchExpressions:
>       - {key: rack, operator: Ordinal, values: [rackA, rackB, rackC, rackD]}
>       - {key: san, operator: Ordinal, values: [sanA, sanB]}
> ```
Hiya Zetanova, I have the same requirement, want to append the statefulset ordinal index to pod name tail, as a label, aim to match PV which I labeled the same label. would you tell me how can I append the ordinal index into the _**volumeClaimTemplates.spec.selector.matchLabels**_? I appreciate you can review it, thanks so much in advance.

data-postgresql-0 PV yaml
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgresql-0
  labels:
      pv: data-postgresql-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  iscsi:
    iqn: iqn.2020-05.com.xsky:cluster-bc86fc6b.iscsi.4.1430471279add5f5
    lun: 31
    targetPortal: 192.224.161.146:3260
    portals: ['192.224.161.146:3260','192.224.161.147:3260','192.224.161.148:3260']
  persistentVolumeReclaimPolicy: Retain`

data-postgresql-1 PV yaml
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-postgresql-1
  labels:
      pv: data-postgresql-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  iscsi:
    iqn: iqn.2020-05.com.xsky:cluster-bc86fc6b.iscsi.4.1430471279add5f5
    lun: 31
    targetPortal: 192.224.161.146:3260
    portals: ['192.224.161.146:3260','192.224.161.147:3260','192.224.161.148:3260']
  persistentVolumeReclaimPolicy: Retain`

Statefulset yaml and values.yaml
![image](https://user-images.githubusercontent.com/3415902/106704959-f1b71f80-6627-11eb-9df9-fb3c83f1871d.png)

**Comment by Zetanova** [comment]
@cocofish   u dont need to matchLabel the volumeClaimTemplate
The name of the PVC is used to create or use an existent one.

The name pattern is `{volumeName}-{statefullSetNam}-{ordinal}`

If u need a custom defined claim with a special volume
you can create the volume and/or the claim before the statefullset
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-01
spec:
  storageClassName: csi-hyperv-sc
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  csi:
    driver: eu.zetanova.csi.hyperv
    volumeHandle: mssql-01
    fsType: ext4
    readOnly: false
    volumeAttributes:
      Id: 7F243007-D4E6-4F2A-9316-2B55D5F6513B
      Path: C:\ClusterStorage\hv05\Volumes\mssql-01.vhdx
      Storage: hv05                           
  capacity:
    storage: 10Gi
  claimRef:
    name: data-mssql-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mssql-0
spec:
  storageClassName: csi-hyperv-sc
  accessModes: [ "ReadWriteOnce" ]
  volumeName: mssql-01
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: mssql
#...
volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: csi-hyperv-sc
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

```

The problem is that currently is no oridinal placeholder / replacement in the yaml itself
or like for my idea something like an ordinal operator to spread over sets.

You are using an template generator (helm?), there u should have the ordinal variable 
It should generate the pvc with the correct names before the statefullset

**Comment by cvetomir-todorov** [comment]
I implemented an alternative method to @harishanchu 's approach via init containers. I create an entrypoint.sh in a configmap which:
* First `export`s the `ZOO_MY_ID` env var
* Secondly executes the image's `ENTRYPOINT`

This configmap is mounted as a volume and ran as the app container's `command`.

```k8s
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
data:
  entrypoint.sh: |-
    export ZOO_MY_ID=${HOSTNAME##*-}
    /docker-entrypoint.sh zkServer.sh start-foreground
```
```k8s
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.4.14
          volumeMounts:
            - mountPath: /bin/entrypoint.sh
              name: config
              readOnly: true
              subPath: entrypoint.sh
          command:
            - /bin/entrypoint.sh
      volumes:
        - name: config
          configMap:
            defaultMode: 0700
            name: zookeeper-config
```

##### PROS
* There are no dealings with `/data/myid` files and init containers
* The approach is generic since it is applicable to apps which rely exclusively on env vars, instead of files as is zookeeper

##### CONS
* Need to do `docker inspect` and copy the image's `ENTRYPOINT` (and potentially its `CMD` args)
* If updating the image, you need to check if its `ENTRYPOINT` has changed and update it accordingly
* The env var is set only in the app container process, so `exec`-ing into the container won't reveal it, which means app logging is needed

/cc @kikyomits @ivanpang1996

**Comment by piratf** [comment]
> Hi! What is the status here? I've tried to use the following conf, but it does not work:
> 
> ```yaml
> env:
> - name: STATEFULSET_INDEX
>   valueFrom:
>     fieldRef:
>       fieldPath: metadata.annotations['spec.pod.beta.kubernetes.io/statefulset-index']
> ```

This annotation still doesn't exist in v1.21.8.

**Comment by Zetanova** [comment]
@piratf I followed this topic only lax, but of my knowledge there was no improvement.
The statefulset will generate simply a well-known pod name.
This well-known name can be used to pre-create resources like pvc, databases, users ...
or ordinal index can be extracted at runtime from inside the container at runtime

**Comment by davidkatko** [comment]
> > @piratf or ordinal index can be extracted at runtime from inside the container at runtime
> 
> but anyone know if is there anyway/anyplans to get that ordinal at creation-time, instead at runtime?

have you been able to figure this out? I am trying to include the ordinal index as a label in the template for each pod, but it looks like that may not be possible..

**Comment by Zetanova** [comment]
@davidkatko It can be done in general by a admission webhook, that simply looks if its a pod created by sts and adds the ordinal label to it.
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook

I will do something like it for my project to distribute sts-pods over a set of storages (drives)
https://github.com/Zetanova/hyperv-csi-driver

**Comment by lucasvc** [comment]
> have you been able to figure this out? I am trying to include the ordinal index as a label in the template for each pod, but it looks like that may not be possible..

My usage was on a Spring Boot application, where I needed **only** the pod index. I solved creating an `initContainer` with a command that wrote the value into a file into a shared volume that Spring Boot included.

**Comment by Zetanova** [comment]
@lucasvc this is the runtime option, already mentioned above. The main problem is if you need the ordinal index at deploy time, like for an label or to use it inside the PVC template

**Comment by Ashtonian** [comment]
121 upvotes, 44 participants, 70 comments, 5 year old issue but triage bot closes it.

**Comment by dims** [comment]
@Ashtonian yep, that's what the bot is expected to do. Also see https://twitter.com/dims/status/1593348306054397952?s=20&t=pYAUvlNoO2enJmMYsmccIQ

**Comment by Ashtonian** [comment]
> @Ashtonian yep, that's what the bot is expected to do. Also see [twitter.com/dims/status/1593348306054397952?s=20&t=pYAUvlNoO2enJmMYsmccIQ](https://twitter.com/dims/status/1593348306054397952?s=20&t=pYAUvlNoO2enJmMYsmccIQ)

I understand its intention, but as a community member I can't help but view this as a huge detriment. From a community perspective it seems to enable large organizations to ignore community feedback and requests and undermines product quality. 

This issue for example is exposing more metadata, metadata that is a piece of the pod name composition which is available via an env variable already. Useful for things like kafka, nsq and any other service that needs some sense of id for clustering. Should be relatively minor enhancement to somebody familiar with the codebase, but the expectation is that a formal proposal is written before it even gets considered?

**Comment by dims** [comment]
@Ashtonian all of us are community members here.

**Comment by lucasvc** [comment]
@dims, Unfortunatelly, not all the community have the knowledge to how to solve the issue in the code. Even some we don't know where to start to propose such a change.

**Comment by dims** [comment]
@lucasvc there are a lot of resources to help someone get started ( https://github.com/kubernetes/community/tree/master/contributors/devel#table-of-contents ) we have way more things  than folks who can help do them :( the  bot makes it quite clear `lacks enough active contributors`

**Comment by odinsy** [comment]
Since 1.28 kubernetes version you can use `statefulset.kubernetes.io/pod-index` from pod label.
Here is KEP and so on https://github.com/kubernetes/enhancements/issues/4017

**Comment by deitch** [comment]
So this is finally complete?

**Comment by odinsy** [comment]
Maybe someone can test it, it should look like this
```
    - name: ZK_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
```
