### ISSUE TITLE
Slow network performance accessing Service with type=NodePort on some nodes

### ISSUE THREAD

**Issue by pizzarabe** [kubernetes/kubernetes#40653]
**Is this a request for help?** 
Yes, but I already asked the Slack and looked at https://github.com/kubernetes/kubernetes/wiki/Debugging-FAQ and https://kubernetes.io/docs/user-guide/debugging-services/, so this is (maybe?) a bug.

> If you get this far, something very strange is happening. Your Service is running, has Endpoints, and your Pods are actually serving. You have DNS working, iptables rules installed, and kube-proxy does not seem to be misbehaving. And yet your Service is not working. You should probably let us know, so we can help investigate!

**Environment**

I have a 4 Node K8s Cluster running self hosted on a VMware Cluster.

- **OS** : Container Linux by CoreOS 1235.6.0 (Ladybug) 

- **Kubernetes version**: Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+coreos.1",

- **Network**: flannel (v.0.6.2, also tested with v.0.7.0). Calico is used for network policy (but no network policy is active)

**What happened**:

I have a simple nginx service deployed, type=NodePort. 
Using "siege" I can confirm, that 3 out of 4 nodes are running very "fast"

```
siege -b -c 10 111.169.1.131:30000
Transactions:		       15017 hits
Availability:		      100.00 %
Elapsed time:		        1.63 secs
Data transferred:	        8.76 MB
Response time:		        0.00 secs
Transaction rate:	     9212.88 trans/sec
Throughput:		        5.38 MB/sec
Concurrency:		        9.53
Successful transactions:       15017
Failed transactions:	           0
Longest transaction:	        0.01
Shortest transaction:	        0.00
```

The 4th node is very "slow" (The first 2-10 requests are okay, the other requests are slow.).
Testing this from the 4th node the problem does not occur, only on every other system.

```
siege -b -c 10 111.169.1.134:30000
Transactions:		           6 hits
Availability:		       60.00 %
Elapsed time:		      131.52 secs
Data transferred:	        0.00 MB
Response time:		        0.00 secs
Transaction rate:	        0.05 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        0.00
Successful transactions:           6
Failed transactions:	           4
Longest transaction:	        0.00
Shortest transaction:	        0.00
```

According to the debugging docs, I tested:

**Does the Service exist?**
Yes
```
~/kubectl get svc nginx-testing
NAME            CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
nginx-testing   10.2.0.112   <nodes>       80:30000/TCP   22h

```

**Does the Service work by DNS?**

Yes (from pod):
```
$ getent hosts nginx-testing
10.2.0.112      nginx-testing.default.svc.cluster.local
```

Yes (from node):
```
$ nslookup nginx-testing.default.svc.cluster.local 10.2.0.2
Server:		10.2.0.2
Address:	10.2.0.2#53

Name:	nginx-testing.default.svc.cluster.local
Address: 10.2.0.112

$ nslookup kubernetes.default.svc.cluster.local 10.2.0.2
Server:		10.2.0.2
Address:	10.2.0.2#53

Non-authoritative answer:
Name:	kubernetes.default.svc.cluster.local
Address: 10.2.0.1
```

**Does the Service work by IP?**

Yes
```
$ siege -b -c 10 10.2.0.112

Transactions:		        5512 hits
Availability:		      100.00 %
Elapsed time:		        0.62 secs
Data transferred:	        3.22 MB
Response time:		        0.00 secs
Transaction rate:	     8890.32 trans/sec
Throughput:		        5.19 MB/sec
Concurrency:		        9.47
Successful transactions:        5512
Failed transactions:	           0
Longest transaction:	        0.01
Shortest transaction:	        0.00
```
**Is the Service correct?**
```
~/kubectl get service nginx-testing -o json
{
   "apiVersion": "v1",
   "kind": "Service",
   "metadata": {
       "annotations": {
           "kubectl.kubernetes.io/last-applied-configuration": "{\"kind\":\"Service\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"nginx-testing\",\"creationTimestamp\":null},\"spec\":{\"ports\":[{\"port\":80,\"targetPort\":0,\"nodePort\":30000}],\"selector\":{\"app\":\"nginx\",\"dev\":\"true\"},\"type\":\"NodePort\"},\"status\":{\"loadBalancer\":{}}}"
       },
       "creationTimestamp": "2017-01-27T20:18:01Z",
       "name": "nginx-testing",
       "namespace": "default",
       "resourceVersion": "58729",
       "selfLink": "/api/v1/namespaces/default/services/nginx-testing",
       "uid": "b3d96137-e4cd-11e6-b50d-005056b77f24"
   },
   "spec": {
       "clusterIP": "10.2.0.112",
       "ports": [
           {
               "nodePort": 30000,
               "port": 80,
               "protocol": "TCP",
               "targetPort": 80
           }
       ],
       "selector": {
           "app": "nginx",
           "dev": "true"
       },
       "sessionAffinity": "None",
       "type": "NodePort"
   },
   "status": {
       "loadBalancer": {}
   }
}

```
**Does the Service have any Endpoints?**

```
~/kubectl get pods -l app=nginx -l dev=true
NAME                                       READY     STATUS    RESTARTS   AGE
nginx-static-deployment-1769137648-1hnkp   1/1       Running   0          2h
nginx-static-deployment-1769137648-2n7fd   1/1       Running   0          2h
nginx-static-deployment-1769137648-99ndd   1/1       Running   0          2h
nginx-static-deployment-1769137648-9tx0n   1/1       Running   0          2h
nginx-static-deployment-1769137648-b4rfz   1/1       Running   0          2h
nginx-static-deployment-1769137648-fmpdb   1/1       Running   0          2h
nginx-static-deployment-1769137648-g1zbx   1/1       Running   0          2h
nginx-static-deployment-1769137648-n87sd   1/1       Running   0          2h
nginx-static-deployment-1769137648-pmw4z   1/1       Running   0          2h
nginx-static-deployment-1769137648-qsp0m   1/1       Running   0          2h

~/kubectl get endpoints nginx-testing      
NAME            ENDPOINTS                                              AGE
nginx-testing   10.1.48.10:80,10.1.48.11:80,10.1.48.8:80 + 7 more...   23h

```

**Are the Pods working?**
Yes, each pod is "fast", accessing the direct pod ip

**Is the kube-proxy running?**
```
docker ps 
[...]
1d6b6261b575        quay.io/coreos/hyperkube:v1.5.2_coreos.1   "/hyperkube proxy --m"   3 hours ago         Up 3 hours                                   k8s_kube-proxy.2961ca0f_kube-proxy-111.169.1.134_kube-system_3254b05f59426154c2be2057e409b2fd_47cb3bf8
kube-proxy-111.169.1.134                1/1       Running   5          8h
[...]

docker logs 1d6b6261b575
I0128 16:21:50.167832       1 server.go:215] Using iptables Proxier.
W0128 16:21:50.253450       1 server.go:468] Failed to retrieve node info: nodes "alien4" not found
W0128 16:21:50.254845       1 proxier.go:249] invalid nodeIP, initialize kube-proxy with 127.0.0.1 as nodeIP
W0128 16:21:50.254865       1 proxier.go:254] clusterCIDR not specified, unable to distinguish between internal and external traffic
I0128 16:21:50.254887       1 server.go:227] Tearing down userspace rules.
I0128 16:21:50.330334       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_max' to 196608
I0128 16:21:50.330911       1 conntrack.go:66] Setting conntrack hashsize to 49152
I0128 16:21:50.338052       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0128 16:21:50.338126       1 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600

```

**Is kube-proxy writing iptables rules?**

```
sudo iptables-save | grep nginx-testing
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx-testing:" -m tcp --dport 30000 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "default/nginx-testing:" -m tcp --dport 30000 -j KUBE-SVC-ZPXYYOVZD4M2SOHU
-A KUBE-SEP-2CHMA5NPKCPMZARL -s 10.1.6.9/32 -m comment --comment "default/nginx-testing:" -j KUBE-MARK-MASQ
-A KUBE-SEP-2CHMA5NPKCPMZARL -p tcp -m comment --comment "default/nginx-testing:" -m tcp -j DNAT --to-destination 10.1.6.9:80
-A KUBE-SEP-5HHRXC36TQYT3V7I -s 10.1.48.10/32 -m comment --comment "default/nginx-testing:" -j KUBE-MARK-MASQ
-A KUBE-SEP-5HHRXC36TQYT3V7I -p tcp -m comment --comment "default/nginx-testing:" -m tcp -j DNAT --to-destination 10.1.48.10:80
-A KUBE-SEP-766ZW5IWV7AXNVNR -s 10.1.48.9/32 -m comment --comment "default/nginx-testing:" -j KUBE-MARK-MASQ
-A KUBE-SEP-766ZW5IWV7AXNVNR -p tcp -m comment --comment "default/nginx-testing:" -m tcp -j DNAT --to-destination 10.1.48.9:80
-A KUBE-SEP-7V5CJWJTRYEHKAYC -s 10.1.65.6/32 -m comment --comment "default/nginx-testing:" -j KUBE-MARK-MASQ
-A KUBE-SEP-7V5CJWJTRYEHKAYC -p tcp -m comment --comment "default/nginx-testing:" -m tcp -j DNAT --to-destination 10.1.65.6:80
-A KUBE-SEP-7ZC4G5V3JOJRA5Z6 -s 10.1.48.8/32 -m comment --comment "default/nginx-testing:" -j KUBE-MARK-MASQ
-A KUBE-SEP-7ZC4G5V3JOJRA5Z6 -p tcp -m comment --comment "default/nginx-testing:" -m tcp -j DNAT --to-destination 10.1.48.8:80
-A KUBE-SEP-DJNYZU23GIKSBVTB -s 10.1.48.11/32 -m comment --comment "default/nginx-testing:" -j KUBE-MARK-MASQ
-A KUBE-SEP-DJNYZU23GIKSBVTB -p tcp -m comment --comment "default/nginx-testing:" -m tcp -j DNAT --to-destination 10.1.48.11:80
-A KUBE-SEP-HFYA3ZSN6FJNJFLJ -s 10.1.65.7/32 -m comment --comment "default/nginx-testing:" -j KUBE-MARK-MASQ
-A KUBE-SEP-HFYA3ZSN6FJNJFLJ -p tcp -m comment --comment "default/nginx-testing:" -m tcp -j DNAT --to-destination 10.1.65.7:80
-A KUBE-SEP-LCRN3NFZ4AYC4F43 -s 10.1.65.8/32 -m comment --comment "default/nginx-testing:" -j KUBE-MARK-MASQ
-A KUBE-SEP-LCRN3NFZ4AYC4F43 -p tcp -m comment --comment "default/nginx-testing:" -m tcp -j DNAT --to-destination 10.1.65.8:80
-A KUBE-SEP-MNRSVYFBLJ5VFYFZ -s 10.1.6.10/32 -m comment --comment "default/nginx-testing:" -j KUBE-MARK-MASQ
-A KUBE-SEP-MNRSVYFBLJ5VFYFZ -p tcp -m comment --comment "default/nginx-testing:" -m tcp -j DNAT --to-destination 10.1.6.10:80
-A KUBE-SEP-QYBRQASTLDHSGHGG -s 10.1.6.8/32 -m comment --comment "default/nginx-testing:" -j KUBE-MARK-MASQ
-A KUBE-SEP-QYBRQASTLDHSGHGG -p tcp -m comment --comment "default/nginx-testing:" -m tcp -j DNAT --to-destination 10.1.6.8:80
-A KUBE-SERVICES -d 10.2.0.112/32 -p tcp -m comment --comment "default/nginx-testing: cluster IP" -m tcp --dport 80 -j KUBE-SVC-ZPXYYOVZD4M2SOHU
-A KUBE-SVC-ZPXYYOVZD4M2SOHU -m comment --comment "default/nginx-testing:" -m statistic --mode random --probability 0.10000000009 -j KUBE-SEP-5HHRXC36TQYT3V7I
-A KUBE-SVC-ZPXYYOVZD4M2SOHU -m comment --comment "default/nginx-testing:" -m statistic --mode random --probability 0.11110999994 -j KUBE-SEP-DJNYZU23GIKSBVTB
-A KUBE-SVC-ZPXYYOVZD4M2SOHU -m comment --comment "default/nginx-testing:" -m statistic --mode random --probability 0.12500000000 -j KUBE-SEP-7ZC4G5V3JOJRA5Z6
-A KUBE-SVC-ZPXYYOVZD4M2SOHU -m comment --comment "default/nginx-testing:" -m statistic --mode random --probability 0.14286000002 -j KUBE-SEP-766ZW5IWV7AXNVNR
-A KUBE-SVC-ZPXYYOVZD4M2SOHU -m comment --comment "default/nginx-testing:" -m statistic --mode random --probability 0.16667000018 -j KUBE-SEP-MNRSVYFBLJ5VFYFZ
-A KUBE-SVC-ZPXYYOVZD4M2SOHU -m comment --comment "default/nginx-testing:" -m statistic --mode random --probability 0.20000000019 -j KUBE-SEP-QYBRQASTLDHSGHGG
-A KUBE-SVC-ZPXYYOVZD4M2SOHU -m comment --comment "default/nginx-testing:" -m statistic --mode random --probability 0.25000000000 -j KUBE-SEP-2CHMA5NPKCPMZARL
-A KUBE-SVC-ZPXYYOVZD4M2SOHU -m comment --comment "default/nginx-testing:" -m statistic --mode random --probability 0.33332999982 -j KUBE-SEP-7V5CJWJTRYEHKAYC
-A KUBE-SVC-ZPXYYOVZD4M2SOHU -m comment --comment "default/nginx-testing:" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-HFYA3ZSN6FJNJFLJ
-A KUBE-SVC-ZPXYYOVZD4M2SOHU -m comment --comment "default/nginx-testing:" -j KUBE-SEP-LCRN3NFZ4AYC4F43
```

My service and deployment config:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-testing
spec:
  ports:
  - port: 80
    nodePort: 30000
  type: "NodePort"
  selector: 
    "dev": "true"
    "app": "nginx"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-static-deployment
spec: 
  replicas: 10
  template:
    metadata:
      name: nginx-testing
      labels:
        "dev": "true"
        "app": "nginx"
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
```
 
**Anything else do we need to know**:

I tried every k8s 1.5.x version on qualy, updated flannel from 0.6.2 to 0.7.0.
I also tried to disable calico, and I tied another Image (nginx:alpine, self build apache + php image)

Reinstalling each node results in the same problem (the "slow" node sometime changes. YES, I will try to investigate the VMware infrastructure as soon as I can.) 

kubelet config:
```
systemctl cat kubelet
# /etc/systemd/system/kubelet.service
[Service]
ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
ExecStartPre=/usr/bin/mkdir -p /var/log/containers
Environment=KUBELET_VERSION=v1.5.2_coreos.1
Environment="RKT_OPTS=--volume var-log,kind=host,source=/var/log \
  --mount volume=var-log,target=/var/log \
  --volume dns,kind=host,source=/etc/resolv.conf \
  --mount volume=dns,target=/etc/resolv.conf \
  --volume ssl-alien,kind=host,source=/etc/ssl/alien,readOnly=true \
  --mount volume=ssl-alien,target=/etc/ssl/alien \
  --set-env=ETCD_CA_CERT_FILE=/etc/ssl/alien/alien-chain.cert.pem \
  --set-env=ETCD_CERT_FILE=/etc/ssl/alien/alien4.cert.pem \
  --set-env=ETCD_KEY_FILE=/etc/ssl/alien/alien4.key.pem"
ExecStart=/usr/lib/coreos/kubelet-wrapper \
  --api-servers=https://111.169.1.131 \
  --network-plugin-dir=/etc/kubernetes/cni/net.d \
  --network-plugin=cni \
  --register-node=true \
  --allow-privileged=true \
  --config=/etc/kubernetes/manifests \
  --hostname-override=111.169.1.134  \
  --cluster-dns=10.2.0.2 \
  --cluster-domain=cluster.local \
  --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
  --tls-cert-file=/etc/ssl/alien/alien4.cert.pem \
  --tls-private-key-file=/etc/ssl/alien/alien4.key.pem
Restart=always
RestartSec=10
[Install]
WantedBy=multi-user.target
```
kube-proxy config:
```
cat /etc/kubernetes/manifests/kube-proxy.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: quay.io/coreos/hyperkube:v1.5.2_coreos.1
    command:
    - /hyperkube
    - proxy
    - --master=https://111.169.1.131
    - --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml
    - --proxy-mode=iptables
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /etc/ssl/certs
        name: "ssl-certs"
      - mountPath: /etc/kubernetes/worker-kubeconfig.yaml
        name: "kubeconfig"
        readOnly: true
      - mountPath: /etc/ssl/alien
        name: "etc-kube-ssl"
        readOnly: true
  volumes:
    - name: "ssl-certs"
      hostPath:
        path: "/usr/share/ca-certificates"
    - name: "kubeconfig"
      hostPath:
        path: "/etc/kubernetes/worker-kubeconfig.yaml"
    - name: "etc-kube-ssl"
      hostPath:
        path: "/etc/ssl/alien"
```

**What you expected to happen**:
Each node should be "fast"

_I am very sorry, this is a bunch of information, but I don't know where to dig..._
