### ISSUE TITLE
Kubernetes API certificates for Heat deploy script

### ISSUE THREAD

**Issue by daniel-yavorovich** [kubernetes/kubernetes#40741]
Dear Sirs/Madams,

I found problem with setup Kubernetes 1.6 + Openstack.

After setup kubernetes API can't start because use undefined certificate:

File: /var/log/kube-apiserver.log
`F0131 16:12:36.513227       5 master.go:273] Error building core storage: open /srv/kubernetes/kubeapiserver.cert: no such file or directory`

Kubernetes API use path to cert /srv/kubernetes/kubeapiserver.cert, but this file is not found:

File: /srv/salt/kube-apiserver/kube-apiserver.manifest
```
{% set cert_file = "--tls-cert-file=/srv/kubernetes/server.cert" -%}
{% set key_file = "--tls-private-key-file=/srv/kubernetes/server.key" -%}
{% set kubelet_cert_file = "--kubelet-client-certificate=/srv/kubernetes/kubeapiserver.cert" -%}
{% set kubelet_key_file = "--kubelet-client-key=/srv/kubernetes/kubeapiserver.key" -%}
```

This file is not generated:
```
# ls /srv/kubernetes/kubeapiserver.cert
ls: cannot access /srv/kubernetes/kubeapiserver.cert: No such file or directory
```

Salt generated only server.cert and server.key files

File: /srv/salt/generate-cert/init.sls
```
kubernetes-cert:
  cmd.script:
    - unless: test -f /srv/kubernetes/server.cert
    - source: salt://generate-cert/{{certgen}}
{% if cert_ip is defined %}
    - args: {{cert_ip}} {{master_extra_sans}}
    - require:
      - pkg: curl
{% endif %}
    - cwd: /
    - user: root
    - group: root
    - shell: /bin/bash
    - require:
      - pkg: openssl
```

What is the best solution? User server.cert and server.key in kubernetes api or add config for generate kubernetes api cert in /srv/salt/generate-cert/init.sls?

Thank you.
