### ISSUE TITLE
After enabling RBAC, api-server no longer loads certificates from OIDC discovery URL

### ISSUE THREAD

**Issue by mlbiam** [kubernetes/kubernetes#40750]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug Report

**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: KVM
- **OS** (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- **Kernel** (e.g. `uname -a`): Linux kubemaster.tremolo.lan 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**: kubeadm
- **Others**:

**What happened**:

I have 2 instances of an identity provider on the same host.  One is OpenUnison and one is the commercial version of Unison.  Prior to enabling RBAC I was able to switch between each instance by restarting the API server.  They share the same TLS certificate for HTTPS, but the certificates for signing JWTs are different.  I enabled RBAC on the API server with the commercial Unison running, and k8s worked as expected with OIDC.  When I switch to the OpenUnison instance, I get the following error when presenting a JWT:

```
I0131 18:51:14.563001       1 jwt.go:239] Signature error (key 0): crypto/rsa: verification error
I0131 18:51:14.563452       1 authorization.go:52] Forbidden: "/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/", Reason: 
I0131 18:51:14.563492       1 panics.go:76] GET /api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/: (924.305µs) 403 [[Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0] 192.168.2.197:45998]
```

Here's the JWT:
```
eyJraWQiOiJDTj1vaWRjaWRwLnRyZW1vbG8ubGFuLCBPVT1EZW1vLCBPPVRybWVvbG8gU2VjdXJpdHksIEw9QXJsaW5ndG9uLCBTVD1WaXJnaW5pYSwgQz1VUy1DTj1rdWJlLWNhLTEyMDIxNDc5MjEwMzYwNzMyMTUyIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL29pZGNpZHAudHJlbW9sby5sYW46ODQ0My9hdXRoL2lkcC9PaWRjSWRQIiwiYXVkIjoia3ViZXJuZXRlcyIsImV4cCI6MTQ4NTg4ODgxMiwianRpIjoidTVxTV9YczhEX1lKOUZ5VjdVSFVVUSIsImlhdCI6MTQ4NTg4ODc1MiwibmJmIjoxNDg1ODg4NjMyLCJzdWIiOiI0YWViMzdiYS1iNjQ1LTQ4ZmQtYWIzMC0xYTAxZWU0MWUyMTgifQ.pVuL2jTVXSqIF8LtoO5dL7ii20SuLAvQUKtvm4_CvIxMQzD2dmyEboj0Mro5-An7cLPxRG4xntuqZa64qBgoicYpPCu_kMgxZqVNwNrU4U4OniefXX3XgOGOaqpGWvyGa6L3d7uz-7EIaQ97iF4A_w58IIJwP_-xzfQSyA6DV0EMesGNmcUpFsB1PUf58XbCtlfyAVjEKyW_UELpePLINtupAt0U9nxkYO8GGonapopGSZclVJpFBgADQKluEKUveBv7uRM1LtZfGBT_3ZZjcgDJmjhUPEvDdZfYGM4TOmX17mH5hQJS-xMsx_KeNcZg9t2rkp_p8lkDV0DPvSEFQQ
```

Here's the certificate URL:
```json
{"keys":[{"kty":"RSA","kid":"CN=oidcidp.tremolo.lan, OU=Demo, O=Trmeolo Security, L=Arlington, ST=Virginia, C=US-CN=kube-ca-12021479210360732152","use":"sig","alg":"RS256","n":"1fAIG0i_sCen8o6p71vKTbVn0SBt_rOlVJ426uD-c0wJ6lqIm4dXk88veDes134PjaSvkiqbDEGP_isqOiAMfJD2M8bNv_yENrTB1ZrEr-fD0RftuIEke132MuqU5J41X02aYHoK7tUGI26OD_7U9_XUCimjY4Ykm3SWEx-kTbC0zJ5Clb-Z_yxM28q5bYoYdDDSTK8hGrbouy3YrLZb4T99paDCeXrV472gdP0mcaRJkROvNGvPF7s4xRCPdPhY-gNbIMpp1Ruqebt9T633eWmRoT_uJcR-2xWbRfmTgiy6Q98R1mKj8rnJHny7GTaDwG6zje9SSo4MPVMaXasrhw","e":"AQAB"}]}
```

The only difference between the OpenUnison instance thats failing and the Unison instance thats working is the signing certificate for the JWTs for OpenUnison is the same as the TLS connection, where as for Unison its a self-signed certificate.

**What you expected to happen**:

Since the jwt is valid, it should be allowed in.

**How to reproduce it** (as minimally and precisely as possible):

1.  Setup OIDC with K8S, no RBAC
2. Change the JWT key
3. Attempt accessing K8S services

**Anything else do we need to know**:

cc @ericchiang @liggitt

**Comment by liggitt** [comment]
the signature error log is unrelated... that's the service account token authenticator failing the validate the JWT (which is expected)

you are getting a 403, which is an authorization error.

**Comment by liggitt** [comment]
what claim are you using as the username? if `sub`, do you have an RBAC binding that allows `4aeb37ba-b645-48fd-ab30-1a01ee41e218` to access the dashboard?

**Comment by mlbiam** [comment]
@liggitt yep, i just assumed it was an issue with signature validation.  I tried adding the openunison user to my role bindings but found I needed to add the idp prefix which got it working

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin-resource-role
rules:
- apiGroups: ["*"]
  verbs: ["*"]
  resources: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin-resource-binding
subjects:
- kind: Group
  name: k8s-admins
- kind: ServiceAccount
  name: default
  namespace: kube-system
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: unison
- kind: ServiceAccount
  name: unison
  namespace: default
- kind: User
  name: kubernetes-admin
- kind: User
  name: https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP#4aeb37ba-b645-48fd-ab30-1a01ee41e218
roleRef:
  kind: ClusterRole
  name: admin-resource-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin-role
rules:
- verbs: ["*"]
  nonResourceURLs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: admin-binding
subjects:
- kind: Group
  name: k8s-admins
- kind: ServiceAccount
  name: default
  namespace: kube-system
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: unison
- kind: User
  name: kubernetes-admin
- kind: User
  name: https://oidcidp.tremolo.lan:8443/auth/idp/OidcIdP#4aeb37ba-b645-48fd-ab30-1a01ee41e218
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
```
