### ISSUE TITLE
Environment variables not interpolated with exec probes

### ISSUE THREAD

**Issue by ahawkins** [kubernetes/kubernetes#40846]
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T07:30:54Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- Minikube

**What happened**:

Environment variable interpolation `$()` does not work with exec probes.

**What you expected to happen**:

Environment variables would be interpolated like they are for container commands.

**How to reproduce it** (as minimally and precisely as possible):

Here is a snippet of a failing probe:

```
    - name: mysql
      image: mysql
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: kubernetes
        - name: MYSQL_DATABASE
          value: foo
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 5
        timeoutSeconds: 1
      readinessProbe:
        exec:
          command:
            - "mysql"
            - "--password=$(MYSQL_ROOT_PASSWORD)"
            - "-D"
            - "$(MYSQL_DATABASE)"
            - "-e"
            - "SHOW TABLES;"
```

Replacing the `$()` with hard coded values makes the probe pass.

**Anything else we need to know**:

If environment variables are not supported then I'm happy to make a PR to update the docs.
