### ISSUE TITLE
RBAC: user with view role able to impersonate user with write role

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#40899]
I was able to send a request as `user:admin` (which has clusterrole: `view`) to impersonate as `user:kubecfg` (which has clusterrole: `cluster-admin`). Based on the docs, it looks like this should not be possible.
Filling this to clarify the expected behavior.

Steps:
I first ran:
```
curl https://<master-ip>/api/v1/namespaces/default/pods --insecure -H "Authorization: Bearer <token>" -H "Impersonate-User: kubecfg"
```
and got error: `User "admin" cannot impersonate users at the cluster scope.` which is as expected. I then found clusterrolebinding `user:admin` to clusterrole `view` and cluster role `view` did not have impersonation ability.
I edited the cluster role to add:
```
apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - users
    verbs:
    - impersonate
```
and then running the same command as above worked fine. I got:
```
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces/default/pods",
    "resourceVersion": "5447584"
  },
  "items": null
}
```
I expected an error saying `admin` cannot impersonate `kubecfg`.

Ref https://docs.google.com/document/d/1h3ULIc65gzv-9i-Pi6akBC_rt9QlNtHDqKCIc06gVV8/edit?disco=AAAAA7pKljo

cc @ericchiang @liggitt

**Comment by liggitt** [comment]
You added the ability to impersonate all users to the view role?

**Comment by nikhiljindal** [comment]
Yes I added the following, which I assume gives the ability to impersonate all users?
```
apiGroups:
    - ""
    attributeRestrictions: null
    resources:
    - users
    verbs:
    - impersonate
```
Is there a way to restrict it to allow impersonating only a particular user or allow impersonating users which have permissions lower than this user?
