### ISSUE TITLE
Unpredictable wait time for PVC to be bound on GCE

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#40972]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
GKE

**What happened**:

We create PVC via dynamic provisioning (storage class) on GCE.
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
...
provisioner: kubernetes.io/gce-pd
```
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: etcd-backup-gce-pd
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  labels:
    app: etcd
    etcd_cluster: etcd-cluster-with-backup
  name: etcd-cluster-with-backup-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
```

The time from PVC is created to PVC is bound usually takes < 4s. Sometimes this goes up > 20s.
This is unpredictable, and very long.
Is this expected? Is there expected p99 for this?

**What you expected to happen**:
I want to know p99 for the time PVC to be bound.

**How to reproduce it** (as minimally and precisely as possible):
The process is quite simple.
- create storage class of provisioner `kubernetes.io/gce-pd`
- repeat (have 4 concurrently)
  - create a PVC
  - wait for PVC to be bound
  - delete the PVC

Will see some wait time to be very long. I can provide a script if needed.
