### ISSUE TITLE
Kubelet failure to umount glusterfs mount points

### ISSUE THREAD

**Issue by corlettb** [kubernetes/kubernetes#41141]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
glusterfs, umount
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release): ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Linux hostname 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: terraform/ansible
- **Others**:

**What happened**: 
Kubernetes allows users to delete a glusterfs pvc before it is has been umounted from all kubelets. This leaves orphaned mount points on the kubelet boxes and the kubelets looping trying and remove them.

**What you expected to happen**:
The kubelet should successfully remove the mountpoints.

**How to reproduce it** (as minimally and precisely as possible):

Example deployment with with a heketi/glusterfs storageclass.

gluster-test.yml:
```
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "test"
  annotations:
    volume.beta.kubernetes.io/storage-class: "gluster"

spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "4Gi"

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: test
spec:
  replicas: 10
  selector:
    role: test
  template:
    metadata:
      labels:
        role: test
    spec:
      containers:
      - name: server
        image: nginx
        volumeMounts:
          - mountPath: /var/lib/www/html
            name: test
      volumes:
        - name: test
          persistentVolumeClaim:
            claimName: test
```

To reproduce :

kubectl create -f gluster-test.yml
<wait for all containers to come up>
kubectl delete -f gluster-test.yml

This will cause heketi to remove the glusterfs volume before some of the pods have umounted it. All mount points still online will error with: 'transport endpoint is not connected'

These can still be umounted, however the way the code is written it will try to "stat" the mount point before trying the umount. This will error with something like the following:

```
Feb 08 16:00:50 hostname hyperkube[20686]: E0208 16:00:50.484167   20686 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/glusterfs/7915ad66-ee16-11e6-b43a-0a6fac4f1177-pvc-78f6b82d-ee16-11e6-b43a-0a6fac4f1177\" (\"7915ad66-ee16-11e6-b43a-0a6fac4f1177\")" failed. No retries permitted until 2017-02-08 16:01:06.484141794 +0000 GMT (durationBeforeRetry 16s). Error: UnmountVolume.TearDown failed for volume "kubernetes.io/glusterfs/7915ad66-ee16-11e6-b43a-0a6fac4f1177-pvc-78f6b82d-ee16-11e6-b43a-0a6fac4f1177" (volume.spec.Name: "test") pod "7915ad66-ee16-11e6-b43a-0a6fac4f1177" (UID: "7915ad66-ee16-11e6-b43a-0a6fac4f1177") with: Error checking if path exists: stat /mnt/secure/kubelet-root-dir/pods/7915ad66-ee16-11e6-b43a-0a6fac4f1177/volumes/kubernetes.io~glusterfs/pvc-78f6b82d-ee16-11e6-b43a-0a6fac4f1177: transport endpoint is not connected
```
This will prevent the umount and pod cleanup.

**Anything else we need to know**:

The code looks something like this:

```
func UnmountPath(mountPath string, mounter mount.Interface) error {
	if pathExists, pathErr := PathExists(mountPath); pathErr != nil {
		return fmt.Errorf("Error checking if path exists: %v", pathErr)
	} else if !pathExists {
		glog.Warningf("Warning: Unmount skipped because path does not exist: %v", mountPath)
		return nil
	}

	notMnt, err := mounter.IsLikelyNotMountPoint(mountPath)
	if err != nil {
		return err
	}
	if notMnt {
		glog.Warningf("Warning: %q is not a mountpoint, deleting", mountPath)
		return os.Remove(mountPath)
	}
	...
```

```
// PathExists returns true if the specified path exists.
func PathExists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	} else if os.IsNotExist(err) {
		return false, nil
	} else {
		return false, err
	}
}
```
```
func (mounter *Mounter) IsLikelyNotMountPoint(file string) (bool, error) {
	return IsNotMountPoint(file)
}

func IsNotMountPoint(file string) (bool, error) {
	stat, err := os.Stat(file)
	if err != nil {
		return true, err
	}
	rootStat, err := os.Lstat(file + "/..")
	if err != nil {
		return true, err
	}
	// If the directory has a different device as parent, then it is a mountpoint.
	if stat.Sys().(*syscall.Stat_t).Dev != rootStat.Sys().(*syscall.Stat_t).Dev {
		return false, nil
	}

	return true, nil
}
```

I realise the importance of checking to see if a mountpoint is still up before removing it.

My first thoughts were to restrict the stat checks to only error if the mount point didn't actually exist.

Also checking /proc/mounts seems like a more reliable method for checking if something is mounted on linux.
