### ISSUE TITLE
Job spec: restartPolicy defaults to invalid value

### ISSUE THREAD

**Issue by antoineco** [kubernetes/kubernetes#41194]
**Is this a request for help?**: No.

**What keywords did you search in Kubernetes issues before filing this one?**: "supported values"

ref #35131

---

**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Kubernetes version**: 1.5.2

**Environment**: not relevant for that issue

**What happened**:
* I created a Job **without** a `restartPolicy` (`spec.template.spec.restartPolicy`)
* The job was created with `restartPolicy` defaulting to `Always`
* `restartPolicy` does not accept the value `Always`, so the creation failed with `The Job "platform-init" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: OnFailure, Never`

**What you expected to happen**:
* `restartPolicy` defaults to `Never` (at least a valid value, not `Always`)
*or*
* `restartPolicy` is a required value (eg. `spec.template.spec.containers.image`) 

**How to reproduce it** (as minimally and precisely as possible):
```yaml
---

apiVersion: batch/v1
kind: Job

metadata:
  name: platform-init

spec:

  template:

    metadata:

      labels:
        tier: backend
        service: platform
        role: init

    spec:

      containers:

      - name: platform
        image: tianon/true
        imagePullPolicy: Always
```
