### ISSUE TITLE
Validation error: "found invalid field optional for v1.SecretVolumeSource"

### ISSUE THREAD

**Issue by DreadPirateShawn** [kubernetes/kubernetes#41520]
**Kubernetes version**:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS**: Ubuntu precise (12.04.4 LTS)
- **Kernel**: Linux dev 3.13.0-55-generic #92~precise1-Ubuntu SMP Sun Jun 14 18:32:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: N/A
- **Others**: N/A

**What happened**:

Using the "optional" flag specified in https://kubernetes.io/docs/user-guide/secrets/#optional-secrets-as-files-from-a-pod results in a validation error:

```
kubectl --namespace=mynamespace create --filename=template_myservice_20170215-233624.yaml --record
    error: error validating "template_myservice_20170215-233624.yaml": error validating data: found invalid field optional for v1.SecretVolumeSource; if you choose to ignore these errors, turn validation off with --validate=false
```

Template file: **template_myservice_20170215-233624.yaml**
```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: myservice
  name: myservice-20170215-233624
  namespace: mynamespace
spec:
  replicas: 1
  selector:
    name: myservice
    version: 20170215-233624
  template:
    metadata:
      labels:
        name: myservice
        version: 20170215-233624
    spec:
      containers:
      - command:
        - /start.sh
        volumeMounts:
        - mountPath: /etc/foo
          name: fooconfig
          readOnly: true
      volumes:
      - name: fooconfig
        secret:
          optional: true
          secretName: foosecret
```

Worth noting, the api docs do not include the "optional" key that's described in the user guide -- https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_secretvolumesource

**What you expected to happen**:

Example in the user guide should be valid. :-)
