### ISSUE TITLE
Rolling upgrades using Deployments should have an option of waiting for the old pod to terminate completely

### ISSUE THREAD

**Issue by buchireddy** [kubernetes/kubernetes#41596]
**Is this a request for help?**

No

**What keywords did you search in Kubernetes issues before filing this one?** 

kubernetes deployment rolling upgrade wait old pod terminate completely

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request.

**Kubernetes version** (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
The default `minikube` based installation on a Macbook.

**What happened**:
For an example, I've used the following Deployment to bring up 3 replicas of nginx and tried a rolling upgrade.

```
buchibusireddy:tmp/ $ cat nginx.yaml                                     
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.5
        ports:
        - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command: ["bash", "-c", "sleep 180"]
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
```

Then I've changed the image to `nginx:1.10.3` and did `kubectl apply -f nginx.yaml` to do a rolling upgrade of the deployment. Here is what I see:

```
nginx-deployment-2232286402-5nbxc      1/1       Running       0          15s
nginx-deployment-2232286402-pnq4h      1/1       Running       0          26s
nginx-deployment-2232286402-shnr0      1/1       Running       0          26s
nginx-deployment-3191471262-f1bwr      1/1       Terminating   0          2m
nginx-deployment-3191471262-sc2bd      1/1       Terminating   0          2m
nginx-deployment-3191471262-w9hhw      1/1       Terminating   0          2m```

Here, I can see that the pods from old RS haven't terminated completely but all the pods from new RS have come up already. If the old pods are still serving the traffic, this leaves double the pods than I what expected. It also means the surge isn't exactly 1, as I used in the configuration.

**What you expected to happen**:

I expected to have some control/parameter so that there is always only one extra pod (maxSurge) and the rolling upgrade waits for the old pod to terminate completely before it brings up new pods. I understand the rolling upgrade could take more time, but I'm fine with that.

**How to reproduce it** (as minimally and precisely as possible):
You can use the config given above to trigger a rolling upgrade.

**Anything else we need to know**:
I've checked for all parameters from v1 and v1beta1 APIs but I didn't see any parameters to get this behavior. It's possible that there is a way to get the behavior that I'm looking for already but it's just not documented. Feel free to call that out and I'll test it out.
