### ISSUE TITLE
New deployment sometimes leaves old ReplicaSet with active replicas

### ISSUE THREAD

**Issue by edevil** [kubernetes/kubernetes#41641]
**Is this a request for help?**
No.

**What keywords did you search in Kubernetes issues before filing this one?**
dangling ReplicaSet

---

**Is this a BUG REPORT or FEATURE REQUEST?**
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T07:31:07Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Azure A1
- **OS** (e.g. from /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1235.9.0
VERSION_ID=1235.9.0
BUILD_ID=2017-02-02-0235
PRETTY_NAME="Container Linux by CoreOS 1235.9.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
- **Kernel** (e.g. `uname -a`): Linux node-3-vm 4.7.3-coreos-r2 #1 SMP Thu Feb 2 02:26:10 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz GenuineIntel GNU/Linux
- **Install tools**: own
- **Others**:

**What happened**:

Created new deployment by altering the image tag of the deployment descriptor and using kubectl apply -f "ds.yaml". Noticed that one container of the previous deployment stayed there.

**What you expected to happen**:

All containers from the previous deployment should have been terminated.

**How to reproduce it** (as minimally and precisely as possible):

I cannot reliably trigger this, I do several deployments per hour and sometimes this problem manifests itself.

**Anything else we need to know**:

```
> kubectl get pods --namespace=tvifttt
NAME                                 READY     STATUS    RESTARTS   AGE
...
tviftttapp-3058473571-c0v2k          1/1       Running   0          1h <------------
tviftttapp-4232354410-c1m13          1/1       Running   0          25m
tviftttapp-4232354410-hr7b4          1/1       Running   0          25m
```

```
✗ kubectl get rs --namespace=tvifttt
NAME                           DESIRED   CURRENT   READY     AGE
...
tviftttapp-1055562301          0         0         0         6d
tviftttapp-1076664945          0         0         0         4d
tviftttapp-1162123786          0         0         0         9d
tviftttapp-1333959179          0         0         0         9d
tviftttapp-1334680075          0         0         0         8d
tviftttapp-146905007           0         0         0         10d
tviftttapp-1506515468          0         0         0         7d
tviftttapp-1585617524          0         0         0         8d
tviftttapp-1655740915          0         0         0         9d
tviftttapp-1870895682          0         0         0         9d
tviftttapp-2074515880          0         0         0         7d
tviftttapp-208247352           0         0         0         8d
tviftttapp-2088802728          0         0         0         10d
tviftttapp-2154994192          0         0         0         9d
tviftttapp-2321390097          0         0         0         9d
tviftttapp-2343410193          0         0         0         7d
tviftttapp-2389416336          0         0         0         6d
tviftttapp-2421529002          0         0         0         3d
tviftttapp-2612435423          0         0         0         9d
tviftttapp-2656999955          0         0         0         8d
tviftttapp-2714737223          0         0         0         3h
tviftttapp-2782697952          0         0         0         9d
tviftttapp-3058473571          1         1         1         1h    <--------------------
tviftttapp-3129580002          0         0         0         9d
tviftttapp-3322845719          0         0         0         8d
tviftttapp-3336608305          0         0         0         8d
tviftttapp-3338181169          0         0         0         3h
tviftttapp-3499661874          0         0         0         7d
tviftttapp-3560282726          0         0         0         9d
tviftttapp-3695024691          0         0         0         2d
tviftttapp-397973892           0         0         0         8d
tviftttapp-4008876597          0         0         0         7d
tviftttapp-4101544605          0         0         0         6d
tviftttapp-4232354410          2         2         2         26m
tviftttapp-461281746           0         0         0         7d
tviftttapp-461478561           0         0         0         8d
tviftttapp-732207675           0         0         0         2h
tviftttapp-835623432           0         0         0         2d
tviftttapp-875534908           0         0         0         7d
```

Deployment descriptor:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tviftttapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tviftttapp
        tier: frontend
    spec:
      containers:
      - name: tviftttapp
        image: XXX:TTT
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /tv/
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /tv/
            port: 80
          timeoutSeconds: 1
      imagePullSecrets:
      - name: brpxprivate
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  minReadySeconds: 2
```
