### ISSUE TITLE
ReplicaSet controller failed to update its status after scaling down 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#41697]
**Kubernetes version** (use `kubectl version`): 1.5.2 

**What happened**:

100% reproducible on the cluster.

```console
$ kubectl delete deployment foo
error: timed out waiting for "foo-123456789" to be synced

$ kubectl get rs foo-123456789                
NAME            DESIRED   CURRENT   READY     AGE
foo-123456789   0         1         1         21h

$ kubectl get deploy foo
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
foo       0         1         1            0           21h

$ kubectl get pods 
No resources found.
```

**My theory about the cause:**

1. When `kubectl delete` a deployment, kubectl scales down its replicaset.
2. (root cause) There's some bug in the replicaset controller, and replicaset controller failed to update status.availableReplicas after scaling down replicas 
3. Deployment controller calculates status based on replicaset status and replicaset spec.replicas
4. Because of 2+3, deployment has an erroneous status.unavailableReplicas=-1, and kept failing (because replicaset controller never update the status to the correct state), see lots of the following log in controller manager log:
```
E0218 19:54:58.087450       9 deployment_controller.go:303] Deployment.extensions "foo" is invalid: status.unavailableReplicas: Invalid value: -1: must be greater than or equal to 0
I0218 19:54:58.087479       9 deployment_controller.go:304] Dropping deployment "default/foo" out of the queue: Deployment.extensions "foo" is invalid: status.unavailableReplicas: Invalid value: -1: must be greater than or equal to 0
```
5. `kubectl delete deployment` thought that scaling down replicaset never succeeds (because of replicaset status), and timed out.

**Logs:**

1. There's no pod from deployment "foo" in the system now. 

2. ReplicaSet "foo-123456789":
```
...
  generation: 2
spec:
  replicas: 0
status:
  availableReplicas: 1
  fullyLabeledReplicas: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
```

3. Deployment "foo":
```
...
  generation: 2
spec:
  paused: true
  replicas: 0
status:
  conditions:
  - lastTransitionTime: 2017-02-17T23:01:28Z
    lastUpdateTime: 2017-02-17T23:01:28Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```

@kargakis @kubernetes/sig-apps-bugs
