### ISSUE TITLE
Sometimes a deployment never completes because Kubernetes falsely believes that some of the pods are unavailable

### ISSUE THREAD

**Issue by gg7** [kubernetes/kubernetes#41762]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report.

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: 4 bare-metal servers (x86_64)
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- **Kernel** (e.g. `uname -a`): 4.4.0-*-generic
- **Install tools**: Custom deployment from scratch (3 masters in HA mode)
- **Docker**: 1.11.2 with aufs driver on zfs

**What happened**:

I have the following deployment in my "harry" repository:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: harry
spec:
  revisionHistoryLimit: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: 0
  replicas: 2
  template:
    metadata:
      labels:
        app: harry
    spec:
      nodeSelector:
        network_speed: 10g
      containers:
      - name: harry
        image: docker.local/harry:latest
        imagePullPolicy: Always
        env:
        - name: whatever
          valueFrom:
            configMapKeyRef:
              name: harry
              key: whatever
        volumeMounts:
          - name: "ssl"
            mountPath: "/etc/apache2/client-certs/"
            readOnly: true
        resources:
          requests:
            cpu: 0.25
            memory: 512Mi
          limits:
            cpu: 2
            memory: 1.5Gi
        readinessProbe:
          httpGet:
            path: /health/
            port: 80
            httpHeaders:
            - name: Host
              value: localhost
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/
            port: 80
            httpHeaders:
            - name: Host
              value: localhost
          initialDelaySeconds: 40
          timeoutSeconds: 15
          periodSeconds: 30
      - name: harryrpc
        image: docker.local/harry:latest
        imagePullPolicy: Always
        command:
          - python
          - /harry/harryrpc/harryrpc.py
          - --host
          - 127.0.0.1
        resources:
          requests:
            cpu: 0.01
            memory: 150Mi
          limits:
            cpu: 1
            memory: 500Mi
      - name: reconserver
        image: docker.local/harry:latest
        imagePullPolicy: Always
        command:
          - python
          - /harry/recon_server/recon_server.py
        resources:
          requests:
            cpu: 0.01
            memory: 50Mi
          limits:
            cpu: 1
            memory: 500Mi
      - name: mail
        image: docker.local/mail
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.01
            memory: 10Mi
          limits:
            cpu: 1
            memory: 250Mi
      volumes:
        - name: ssl
          secret:
            secretName: harry
            items:
              - key: ssl_key
                path: key.private
              - key: etc
                path: etc
```

It has been deployed for quite a while and is working fine:

```
root@master:~# kubectl get pods -n harry-prod
NAME                     READY     STATUS    RESTARTS   AGE
harry-1884263832-fsc22   4/4       Running   0          1h
harry-1884263832-ss56n   4/4       Running   0          2m

root@master:~# kubectl get rs -n harry-prod
NAME               DESIRED   CURRENT   READY     AGE
harry-1207867050   0         0         0         2h
harry-1720027597   0         0         0         4d
harry-1884263832   2         2         2         1h
harry-2086310016   0         0         0         7h
harry-2910164104   0         0         0         1h
harry-3011941544   0         0         0         2h
harry-370446428    0         0         0         6h
harry-4054290512   0         0         0         2d
harry-4082272181   0         0         0         3d
harry-4101543632   0         0         0         1h
harry-4157376809   0         0         0         3d

root@master:~# kubectl get deployment -n harry-prod
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
harry     2         2         2            2           10d
```

My CI script replaces `:latest` with `2017-02-20-e1ccae54` (current deployment is using `2017-02-20-d6ff2966`) and runs `kubectl apply -f` against a yaml file containing a service, configmap, and a deployment (seen above). Here's my deployment script: https://gist.github.com/gg7/3d632e77476235c020d9c434908accb1#my-way

Most of the time this works fine. Kubernetes starts 2 extra pods and if they pass their health checks it will remove the 2 old pods.

However, sometimes Kubernetes forgets to scale down the previous replica set to 0 and my deployment scripts get stuck:

```
19:55:26 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:27 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:28 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:29 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:30 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:31 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:32 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:33 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:34 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:36 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:37 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:38 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:39 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:40 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:41 desired:  2; present:  4; available:  2; updated:  2; unavailable:  2
19:55:42 desired:  2; present:  3; available:  2; updated:  2; unavailable:  1
19:55:43 desired:  2; present:  3; available:  2; updated:  2; unavailable:  1
19:55:44 desired:  2; present:  3; available:  2; updated:  2; unavailable:  1
19:55:45 desired:  2; present:  3; available:  2; updated:  2; unavailable:  1
19:55:47 desired:  2; present:  3; available:  2; updated:  2; unavailable:  1
19:55:48 desired:  2; present:  3; available:  2; updated:  2; unavailable:  1
[...]
20:05:23 desired:  2; present:  3; available:  2; updated:  2; unavailable:  1
20:05:24 desired:  2; present:  3; available:  2; updated:  2; unavailable:  1
20:05:25 desired:  2; present:  3; available:  2; updated:  2; unavailable:  1
20:05:26 desired:  2; present:  3; available:  2; updated:  2; unavailable:  1
Timed out!
```

For some reason the deployment thinks one of the pods isn't ready, even though the replica sets think all pods are ready:

```
root@master:~# kubectl describe deployment -n harry-prod harry
Name:                   harry
Namespace:              harry-prod
CreationTimestamp:      Fri, 10 Feb 2017 15:40:30 +0000
Labels:                 app=harry
Selector:               app=harry
Replicas:               2 updated | 2 total | 2 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        5
RollingUpdateStrategy:  0 max unavailable, 100% max surge
Conditions:
  Type          Status  Reason
  ----          ------  ------
  Available     True    MinimumReplicasAvailable
OldReplicaSets: harry-1884263832 (1/1 replicas created)
NewReplicaSet:  harry-4101543632 (2/2 replicas created)
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  1h            21m             3       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled up replica set harry-1884263832 to 2
  1h            21m             2       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled down replica set harry-4101543632 to 1
  21m           21m             1       {deployment-controller }                        Normal          DeploymentRollback      Rolled back deployment "harry" to revision 41
  1h            21m             2       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled down replica set harry-4101543632 to 0
  1h            5m              3       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled up replica set harry-4101543632 to 2
  1h            4m              3       {deployment-controller }                        Normal          ScalingReplicaSet       Scaled down replica set harry-1884263832 to 1
```

But the pods appear to be ready:

```
root@master:~# kubectl get pods -n harry-prod
NAME                     READY     STATUS    RESTARTS   AGE
harry-1884263832-fsc22   4/4       Running   0          1h
harry-4101543632-h66t7   4/4       Running   0          6m
harry-4101543632-ng38t   4/4       Running   0          6m

root@master:~# kubectl describe pod -n harry-prod harry-1884263832-fsc22 | grep -i ready
    Ready:              True
    Ready:              True
    Ready:              True
    Ready:              True
  Ready         True
root@master:~# kubectl describe pod -n harry-prod harry-4101543632-h66t7 | grep -i ready
    Ready:              True
    Ready:              True
    Ready:              True
    Ready:              True
  Ready         True
root@master:~# kubectl describe pod -n harry-prod harry-4101543632-ng38t | grep -i ready
    Ready:              True
    Ready:              True
    Ready:              True
    Ready:              True
  Ready         True
```

Here are the replica sets:

```
root@master:~# kubectl get rs -n harry-prod
NAME               DESIRED   CURRENT   READY     AGE
harry-1207867050   0         0         0         2h
harry-1720027597   0         0         0         4d
harry-1884263832   1         1         1         2h
harry-2086310016   0         0         0         7h
harry-2910164104   0         0         0         2h
harry-3011941544   0         0         0         2h
harry-370446428    0         0         0         6h
harry-4054290512   0         0         0         2d
harry-4082272181   0         0         0         3d
harry-4101543632   2         2         2         1h
harry-4157376809   0         0         0         3d
```

**What you expected to happen**:

I expected that Kubernetes would be able to handle a rolling deployment 100% of the time, not 80%.

Am I doing something wrong?

**How to reproduce it** (as minimally and precisely as possible):

It occurs randomly on my cluster and I don't know how to reliably reproduce it. Sometimes if I manually delete the old replica set my CI script succeeds. Otherwise the deployment gets rolled back.
