### ISSUE TITLE
Unable to mount NFS volume in docker container

### ISSUE THREAD

**Issue by tobegit3hub** [kubernetes/kubernetes#41867]
**Kubernetes version** (use `kubectl version`):

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.4.19899+2aa99337bd8dd4", GitCommit:"2aa99337bd8dd43ec378ba1df6570df214828548", GitTreeState:"clean", BuildDate:"2017-01-16T01:36:45Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.4.19899+2aa99337bd8dd4", GitCommit:"2aa99337bd8dd43ec378ba1df6570df214828548", GitTreeState:"clean", BuildDate:"2017-01-16T01:36:45Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: CPU only
- **OS** (e.g. from /etc/os-release): CentOS 7.0
- **Kernel** (e.g. `uname -a`): 3.10.0-123.13.2.el7.x86_64
- **Install tools**:
- **Others**:

**What happened**:

We try to mount the NFS for the pod with the following YAML file.
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.9
    ports:
    - containerPort: 80
    securityContext:
      privileged: true
    volumeMounts:
      - name: nfs
        mountPath: "/nfs_demo/"
  volumes:
  - name: nfs
    nfs:
      server: x.x.x.x
      path: /home/tobe/temp/nfs_demo/
```

Now the pod and the nginx container can start normally. The NFS volume is mounted in the kubelet server successfully. And I can see the volume when `docker inspect` the container.

```
        {
            "Source": "/var/lib/kubelet/pods/415dde9b-f815-11e6-899e-38d54701b14f/etc-hosts",
            "Destination": "/etc/hosts",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/var/lib/kubelet/pods/415dde9b-f815-11e6-899e-38d54701b14f/containers/dev/46be3947",
            "Destination": "/dev/termination-log",
            "Mode": "",
            "RW": true
        },
        {
            "Source": "/var/lib/kubelet/pods/415dde9b-f815-11e6-899e-38d54701b14f/volumes/kubernetes.io~nfs/nfs",
            "Destination": "/nfs_demo",
            "Mode": "",
            "RW": true
        }
```

However, we could not access the NFS files in `/nfs_demo` which should be mounted in the host while `docker exec` in container.

**What you expected to happen**:

We should sync the NFS folder across the host and the container.
