### ISSUE TITLE
Show confused pod status from `oc get pod` when using a opposite volume dir.

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#41879]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 
all-in-one volume

**Kubernetes version** (use `kubectl version`):
v1.7.0-alpha.0.2+7d6eba69848528

**What happened**:
Show confused pod status from `oc get pod` when using a opposite volume dir.

**How to reproduce it** (as minimally and precisely as possible):
1. Create secret and configmap
```
# cat secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  data-1: dmFsdWUtMQ0K
  data-2: dmFsdWUtMg0KDQo=

# cat configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
  special.how: very
  special.type: charm
```

2. Create a pod with a opposite volume dir `all-in-one/test`
```
# cat allinone-negative-pod-3.yaml
apiVersion: v1
kind: Pod
metadata:
  name: all-in-one-negative-2
spec:
  containers:
  - name: all-in-one-negative-2
    image: redis
    volumeMounts:
    - name: all-in-one
      mountPath: "all-in-one/test"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: test-secret
          items:
            - key: data-1
              path: mysecret/my-username
            - key: data-2
              path: mysecret/my-passwd
      - configMap:
          name: special-config
          items:
            - key: special.how
              path: myconfigmap/shared-config
            - key: special.type
              path: myconfigmap/private-config
```
3. Check pod status by `oc get pod all-in-one-negative-2` and `oc describe pod all-in-one-negative-2`

**Actual results**:
Show confused pod status from `oc get pod all-in-one-negative-2`
```
# kc get pod all-in-one-negative-2
NAME                    READY     STATUS                                                                                                                                                                                                                                                                                                         RESTARTS   AGE
all-in-one-negative-2   0/1       rpc error: code = 2 desc = Error response from daemon: {"message":"Invalid bind mount spec \"/var/lib/kubelet/pods/c2cb3318-f8dc-11e6-9fa7-0e2b0fd0fb86/volumes/kubernetes.io~projected/all-in-one:all-in-one/test:ro,Z\": Invalid volume destination path: 'all-in-one/test' mount path must be absolute."}   0          12m
```

**Expected results**: 
Should show pod real state in pod status, should not display the detail error info in pod status. That should same with the result in `oc describe pod all-in-one-negative-2`

```
# kc describe pod all-in-one-negative-2
Name:		all-in-one-negative-2
Namespace:	default
Node:		127.0.0.1/127.0.0.1
Start Time:	Wed, 22 Feb 2017 03:56:12 -0500
Labels:		<none>
Status:		Pending
IP:		172.17.0.4
Controllers:	<none>
Containers:
  all-in-one-negative-2:
    Container ID:	
    Image:		redis
    Image ID:		
    Port:		
    State:		Waiting
      Reason:		rpc error: code = 2 desc = Error response from daemon: {"message":"Invalid bind mount spec \"/var/lib/kubelet/pods/c2cb3318-f8dc-11e6-9fa7-0e2b0fd0fb86/volumes/kubernetes.io~projected/all-in-one:all-in-one/test:ro,Z\": Invalid volume destination path: 'all-in-one/test' mount path must be absolute."}
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4jk46 (ro)
      all-in-one/test from all-in-one (ro)
    Environment Variables from:	<none>
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  all-in-one:
  <unknown>
  default-token-4jk46:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-4jk46
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath				Type		Reason		Message
  ---------	--------	-----	----			-------------				--------	------		-------
  13m		13m		1	default-scheduler						Normal		Scheduled	Successfully assigned all-in-one-negative-2 to 127.0.0.1
  13m		13m		1	kubelet, 127.0.0.1						Normal		SandboxReceived	Pod sandbox received, it will be created.
  12m		15s		59	kubelet, 127.0.0.1	spec.containers{all-in-one-negative-2}	Normal		Pulling		pulling image "redis"
  12m		15s		59	kubelet, 127.0.0.1	spec.containers{all-in-one-negative-2}	Normal		Pulled		Successfully pulled image "redis"
  12m		15s		59	kubelet, 127.0.0.1	spec.containers{all-in-one-negative-2}	Warning		Failed		Failed to create container with error: rpc error: code = 2 desc = Error response from daemon: {"message":"Invalid bind mount spec \"/var/lib/kubelet/pods/c2cb3318-f8dc-11e6-9fa7-0e2b0fd0fb86/volumes/kubernetes.io~projected/all-in-one:all-in-one/test:ro,Z\": Invalid volume destination path: 'all-in-one/test' mount path must be absolute."}
  12m		15s		59	kubelet, 127.0.0.1						Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "all-in-one-negative-2" with rpc error: code = 2 desc = Error response from daemon: {"message":"Invalid bind mount spec \"/var/lib/kubelet/pods/c2cb3318-f8dc-11e6-9fa7-0e2b0fd0fb86/volumes/kubernetes.io~projected/all-in-one:all-in-one/test:ro,Z\": Invalid volume destination path: 'all-in-one/test' mount path must be absolute."}: "Create Container Failed"
```

**Anything else do we need to know**:
None
