### ISSUE TITLE
add srcPath argument to volumeMount

### ISSUE THREAD

**Issue by proppy** [kubernetes/kubernetes#4201]
It would be nice if `volumeMount` had a `srcPath` attribute, that would allow to mount a subdirectory of the given volume instead of the root.

This could be useful when different subdirectory of the same volume need to be shared between multiple containers of the same pod or mounted in different place in the same container.

Example:
```
      volumeMounts:
      - name: markdown
        srcPath: contrib/git-sync/demo/blog/
        mountPath: /src
```
