### ISSUE TITLE
kubelet unable to authenticate to a private docker registry with basic http auth

### ISSUE THREAD

**Issue by jamonation** [kubernetes/kubernetes#42137]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
```
System Info:
 Machine ID:			064a8fc022f64093b7149850d00ccf1f
 System UUID:			D35B502D-895A-489F-8457-574DBD9860C5
 Boot ID:			b77221b9-6577-4755-af9d-01feda8b4612
 Kernel Version:		4.4.0-63-generic
 OS Image:			Ubuntu 16.04.2 LTS
 Operating System:		linux
 Architecture:			amd64
 Container Runtime Version:	docker://1.12.3
 Kubelet Version:		v1.5.1
 Kube-Proxy Version:		v1.5.1
ExternalID:			juju-a622f6-default-1
Non-terminated Pods:		(4 in total)
```

**What happened**:
I have setup a cluster with a private docker registry with basic htpasswd based authentication. It is using a signed TLS certificate from a major vendor.

I can `docker login` to the registry and push/pull images locally, and I can do the same from any of the nodes in the cluster.

However, I cannot create a pod that uses an image from the private registry.

Inspecting the HTTP traffic that ends up on the registry docker container shows that the kubelet invoked version of the request is not passing the correct `Authorization: Basic` header.

Whereas a normal `docker pull/login/push` shows this:

```
Authorization: Basic <snipped base64 creds>
```

The failing requests look like this (the base64 data is a single encoded `:` character:
```
Authorization: Basic Og==
```

Additionally, the kubelet version of the traffic does not appear to respond to the registry HTTP 401 challenge on the correct URL.

Valid requests look like this:
```
GET /v2/busybox/manifests/latest HTTP/1.1
```

Whereas the kubernetes request ends up being to this URL:
```
/v1/repositories/busybox/images
```

**What you expected to happen**:
The pod should be provisioned using an image pulled from the private registry with basic http auth.

**How to reproduce it** (as minimally and precisely as possible):
1. Setup a registry with basic http auth and tls
2. docker login and push an image from a node or another host with access to the registry
3. define a pod that references the image
4. kubectl create/apply and watch docker registry logs for failed pulls

**Anything else we need to know**:

Here are definitions for the registry pod, secrets, service & replication controller:

```
apiVersion: v1
kind: Secret
metadata:
  name: registry-tls-data
type: Opaque
data:
  tls.crt: <snip>
  tls.key: <snip>
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-auth-data
type: Opaque
data:
  htpasswd: <snip>
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry-v0
  labels:
    k8s-app: kube-registry
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-registry
    version: v0
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: registry:latest
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: basic_realm
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        - name: auth-dir
          mountPath: /auth
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: image-store
        hostPath:
          path: /srv/registry
      - name: auth-dir
        secret:
          secretName: registry-auth-data
---
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry
  type: LoadBalancer
  ports:
  - name: registry
    port: 5000
    protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-access
data:
  .dockercfg: <snip>
type: kubernetes.io/dockercfg
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry-ing
spec:
  tls:
  - hosts:
    - kubernetes-registry
    secretName: registry-tls-data
  rules:
  - host: kubernetes-registry
    http:
      paths:
      - backend:
          serviceName: kube-registry
          servicePort: 5000
        path: /
```

Also note that I've tried both styles of `.dockercfg` credentials, the `{"auths": {....` wrapped version, and the non-wrapped version.
