### ISSUE TITLE
Kube-proxy CPU Usage Regression in 1.6 

### ISSUE THREAD

**Issue by freehan** [kubernetes/kubernetes#42210]
When there is high number of services, there is a significant difference in cpu usage between 1.5 and 1.6 branch. 

My environments has 3 nodes, 3000 services targeting the same 20 backend pods. 

On a node with 1.5 kube-proxy:
```
$ps -p 4466 -o %cpu,%mem    
%CPU %MEM
31.4  6.8
```

On a node with kube-proxy in HEAD:
```
$ ps -p 1579 -o %cpu,%mem    
%CPU %MEM
 125  9.6
```
@kubernetes/sig-network-misc

**Comment by freehan** [comment]
I would say even the case with 30% cpu is still pretty bad.

**Comment by bowei** [comment]
Can you post how to repro?

**Comment by dcbw** [comment]
Also, any way to figure out where the overhead is coming from?  Is it coming from pkg/proxy/iptables/proxier.go or is it coming from the generic code that actualyl delivers the OnEndpointsUpdate()/OnServicesUpdate() code that #42108 might help?

**Comment by freehan** [comment]
Yes. It helps. But still pretty bad. 
```
%CPU %MEM
92.3  4.6
```

**Comment by freehan** [comment]
Here is how to reproduce:

I ran 20 replicas of `serve_hostname` pod.
```
$ k run hostname --image=gcr.io/google_containers/serve_hostname:v1.4
```

And create 3000 services to point to them. 

```
apiVersion: v1
kind: Service
metadata:
  name: hostnamesvc-$i
  labels:
    run: hostname
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9376
  selector:
    run: hostname 
```
