### ISSUE TITLE
Confusing events for short living pod.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/kubernetes#42387]
Whenever we create a short-living pod which runs to complete. After a while, we'll have these confusing events:
```
default   36s       36s       1         test                   Pod                                               Warning   FailedSync    {kubelet e2e-test-lantaol-minion-group-h0br}   Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"test". list of unattached/unmounted volumes=[default-token-6kb2s]
```

The way to reproduce:
* Create a short living pod, for example:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  restartPolicy: OnFailure
  containers:
  - name: test
    image: busybox
    command:
    - ls
```
* Wait for it to complete.
* Check events:
```
$ kubectl get events --all-namespaces | grep FailedSync
default   8m        8m        1         test                   Pod                                               Warning   FailedSync    {kubelet e2e-test-lantaol-minion-group-h0br}   Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"test". list of unattached/unmounted volumes=[default-token-6kb2s]
```

/cc @kubernetes/sig-storage-bugs
