### ISSUE TITLE
taint fields: timeAdded not set

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#42394]
I set taints on a node using the kubelet, but the timeAdded field was not set:

```
 taints:
  - effect: NoSchedule
    key: dedicated
    timeAdded: null
    value: master
```

In addition, I think we prefer to omit null fields.
