### ISSUE TITLE
GPU allocation failed after container in Pod restart 

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#42412]
We found a bug about GPU allocation failed with upstream code. 
If the container with GPU in a `Pod` dead and restart, the GPU is still occupied by the old container so that the new container can not get GPU anymore. You can replay the bug by the script below:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu
  labels:
    name: gpu
spec:
  containers:
  - name: gpu
    image: nvidia/cuda:jian
    command: ["/bin/sh", "-c"]
    args: ["sleep 10"]
    resources:
      limits:
        cpu: 0.5
        memory: 128Mi
        alpha.kubernetes.io/nvidia-gpu: 4
    ports:
    - containerPort: 6379 
```
After we created the pod, we can see the output as below:
```
root@slave2:/home/zhangjian/testK8s# kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
gpu       1/1       Running   0          7s
root@slave2:/home/zhangjian/testK8s# kubectl get pods
NAME      READY     STATUS      RESTARTS   AGE
gpu       0/1       Completed   0          20s
root@slave2:/home/zhangjian/testK8s# kubectl get pods
NAME      READY     STATUS                                                             RESTARTS   AGE
gpu       0/1       requested number of GPUs unavailable. Requested: 4, Available: 0   0          36s
```
After container completed, `Pod` try to restart a new container. But the new container can not get GPU because GPU is still unreleased by the fisrt container. Depolyment and RC controller have the same problem.
