### ISSUE TITLE
PVC creation with selectors is hard in 1.6

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#42503]
Given PV:

```
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "pv0001"
  labels:
    volume-type: "gold"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "hekumar-mo"
```

Create a PVC that matches it via selector:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selectors:
    matchLabels:
      volume-type: "gold"
```

Creating the PVC fails with:

```
Failed to provision volume with StorageClass "default": claim.Spec.Selector is not supported for dynamic provisioning on GCE
```

CC @kubernetes/sig-storage-bugs  @jsafrane 

So far the only workaround I know is binding PV and PVC via volumeName in PVC and claim and claimref in PV
