### ISSUE TITLE
KubeDNS + gci doesn't work together (it seems)

### ISSUE THREAD

**Issue by NiclasHedam** [kubernetes/kubernetes#42636]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): gci, container-vm, kubedns, dns

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug

**Kubernetes version** (use `kubectl version`): 1.5.3

**Environment**:
GKE with Alpha-features

**What happened**:
I booted my cluster up with the gci image in GKE. My pods are reporting that `redis.default.svc.cluster.local` is not found, even though `dig A redis.default.svc.cluster.local` returns an IP and the redis service and pods are working perfectly fine.

After removing the cluster, applying the exact same properties and configs in a new cluster but using container-vm, everything works perfectly fine.

**What you expected to happen**:
N/A

**How to reproduce it** (as minimally and precisely as possible):
Boot up a 1.5.3 cluster with gci and use the local domain names with KubeDNS.

**Anything else we need to know**:

**Comment by bowei** [comment]
Some questions:
* How did you run dig (from a new pod, existing pod)?
* What are the contents of your /etc/resolv.conf from the pods that can't resolve the names?
* What is the /etc/resolv.conf from the node (outer host) that hosts the pods?

**Comment by NiclasHedam** [comment]
The first cluster was also quite new - only a few hours old - but the dig command was run within an existing pod on the new cluster.

The first cluster is removed now, since it was in conflict with the replacement cluster. The pod image deployed on the cluster are the same though, and the pods /etc/resolv.conf looks like this:
```
search default.svc.cluster.local svc.cluster.local cluster.local c.xxx-xxx--xx.internal. google.internal.
nameserver 10.3.240.10
options ndots:5
```

**Comment by bowei** [comment]
How was the non-dig query done (the one that fails)? Was it via a gethostbyname() equivalent or a DNS client library? If it was via the libc call, which libc are you using (glibc, musl, uclibc, ...)

**Comment by NiclasHedam** [comment]
It was failing both as a redis (https://github.com/nrk/predis) and mysql (https://github.com/illuminate/database) connection in php, which I assume is using
`string gethostbyname ( string $hostname )` (http://php.net/manual/en/function.gethostbyname.php).

I can also share that the cluster configuration and Dockerfiles are approx. 6 months months old, and we have never had this issue before today. Even when using gci.

No significant changes where made in the configurations or pods when changing between clusters. (We have to recreate the cluster every month, since we are using alpha features)

**Comment by bowei** [comment]
Which alpha features do you have enabled?

**Comment by bowei** [comment]
Yes, please post the cluster configuration/Dockerfiles.

**Comment by NiclasHedam** [comment]
We are using scheduledjob / cronjobs.

The relevant configs are posted below as well as one of the affected dockerfiles:

Redis service:
```
apiVersion: "v1"
kind: "Service"
metadata:
  name: "redis"
  labels:
    app: "redis"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: "redis"
```

Redis deployment: (official redis docker image)
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: "redis"
    spec:
      containers:
        - name: "redis"
          image: "redis"
          env:
          - name: GET_HOSTS_FROM
            value: env
          command: ["redis-server", "/data/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-persistence
              mountPath: "/data"
      volumes:
          - name: redis-persistence
            gcePersistentDisk:
              pdName: redis-persistence
              fsType: ext4
```

Worker pod deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  revisionHistoryLimit: 1
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: IMAGE_URL
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            memory: 300Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
```
Worker dockerfile:
```
FROM ubuntu:16.04
MAINTAINER Niclas Hedam <niclas@pandiweb.dk>
ARG COMMIT

ENV     VERSION ${COMMIT}
ENV     TERM xterm

RUN     dpkg-divert --local --rename --add /sbin/initctl && \
        ln -sf /bin/true /sbin/initctl && \
        ln -sf /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime

RUN     apt-get update
RUN     apt-get install -y python-software-properties software-properties-common
RUN     LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
RUN     LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php-qa
RUN     apt-get update

RUN     apt-get -y install mysql-client build-essential wget nano curl git-all zip unzip supervisor php7.0 php7.0-fpm php7.0-common php7.0-cli php-pear php7.0-dom php7.0-curl php7.0-gd php7.0-gmp php7.0-intl php7.0-imap php7.0-json php7.0-ldap php7.0-opcache php7.0-mbstring php7.0-mcrypt php7.0-mysql php7.0-ps php7.0-soap php7.0-readline php7.0-tidy php7.0-xmlrpc php7.0-xsl

RUN     curl -o /usr/bin/composer https://getcomposer.org/composer.phar && \
        chmod +x /usr/bin/composer

COPY    . /var/www

RUN     cd /var/www && \
        mv /var/www/.env.production /var/www/.env && \
        composer install -n && \
        chown -Rf www-data:www-data /var/www && \
        chmod -R 755 /var/www/storage

COPY    resources/server/start.sh /start.sh

COPY    resources/server/worker-supervisord.conf /etc/supervisord.conf

RUN     chmod 755 /start.sh

CMD ["/bin/bash", "/start.sh"]
```
