### ISSUE TITLE
Flocker volume plugin does not work anymore since version 1.5.1

### ISSUE THREAD

**Issue by eddytruyen** [kubernetes/kubernetes#42720]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

Yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Flocker, Flocker fails
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Kubernetes version** (use `kubectl version`):
1.5.1

**Environment**:
- **Cloud provider or hardware configuration**:
Private Openstack cloud version liberty but not using --cloud-provider=openstack option
- **OS** (e.g. from /etc/os-release):
ubuntu trusty
- **Kernel** (e.g. `uname -a`): 
3.13.0-62-generic
- **Install tools**:
https://github.com/kubernetes/kube-deploy/tree/master/docker-multinode
- **Others**:
I made a small extension to the docker-multinode project such that Flocker works:
https://github.com/eddytruyen/kube-deploy/tree/master/docker-multinode

**What happened**:
I get an error from kubelet when mounting flocker volumes using hyperkube:1.5.1
When using hyperkube:1.4.8 everything workes fine.
I do not use dynamic volume provisioning (I.e.I created flocker volume first using flockerctl)

Kube Setup: 
Ubuntu trusty nodes
I am using my own extension to docker-multinode that integrates with flocker: https://github.com/eddytruyen/kube-deploy/tree/master/docker-multinode

Flocker Setup: 1.15
Datasetprovider: Cinder (openstack)

Error log when deploying mysql: https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-wordpress-pd. (I changed the volume YAML file such that a localhost volume is changed into a flocker dataset):

```
  11m           1m              13      {kubelet k8-worker-1}                 
Warning          FailedMount     MountVolume.SetUp failed for volume "kubernetes.io/flocker/38b02b01-dfb5-11e6-83a8-fa163ef52647-local-pv-1" (spec.Name: "local-pv-1") pod "38b02b01-dfb5-11e6-83a8-fa163ef52647" (UID: "38b02b01-dfb5-11e6-83a8-fa163ef52647") with: mount failed: exit status 32
Mounting command: mount
Mounting arguments: /flocker/286d6e19-e715-49e8-9eab-489b325a7d9c /var/lib/kubelet pods/38b02b01-dfb5-11e6-83a8-fa163ef52647/volumes/kubernetes.io~flocker/local-pv-1  [bind]
Output: mount: special device /flocker/286d6e19-e715-49e8-9eab-489b325a7d9c does not exist
```

**What you expected to happen**:
I checked if the /flocker/286d6e19-e715-49e8-9eab-489b325a7d9c dir existed and it does exist. 
I would expect that the mount succeeds

**How to reproduce it** (as minimally and precisely as possible):
Install kubernetes and flocker as described in https://github.com/eddytruyen/kube-deploy/tree/master/docker-multinode. Created manual flocker volumes using flockerctl as described in the same webpage

Test application: mysql: https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-wordpress-pd. (I changed the volume YAML file such that a localhost volume is changed into a flocker dataset)

data provider configuration of flocker for cinder volumes on openstack cloud release liberty with both Cinder volumeV1 and Cinder volume V2 running:

```
"version": 1
"control-service":
   "hostname": "172.17.13.43"
   "port": 4524

# The dataset key below selects and configures a dataset backend (see below: aws/openstack/etc).
# All nodes will be configured to use only one backend

dataset:
   backend: "openstack"
   region: "RegionOne"
   verify_peer: false
   auth_plugin: "password"
   auth_url: ""
   username: "eddy"
   password: ""
   tenant_name: "eddy"
network: ""
```
**Anything else we need to know**:
