### ISSUE TITLE
Deprecate / remove alpha.kubernetes.io/fluentd-ds-ready annotation

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#42840]
PR #32088 introduced an annotation for fluentd migration from static pod to the daemonset to avoid two instances of fluentd on a single node during the transition stage. I didn't read the pr carefully, but based on the code at https://github.com/kubernetes/kubernetes/pull/32088/files#diff-6b0808bd1afb15f9f77986f4459601c2R199, every node object has one label be default: 
"alpha.kubernetes.io/fluentd-ds-ready". I think this is wrong. 1) Not everyone use fluentd as the logging agent. 2) It is hard-coded in Kubelet code as part of kubelet_node_status. No matter running fluentd as a static pod or a daemonset on the node, Kubelet shouldn't treat it different from other pods. The right approach is introducing an external controller to apply this cloud-provider / kubernetes vendor (i.e. GKE) specific label to the node. 

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    scheduler.alpha.kubernetes.io/taints: '[]'
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2017-02-25T01:50:12Z
  labels:
    alpha.kubernetes.io/fluentd-ds-ready: "true"                                                        <======================
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: n1-standard-8
    beta.kubernetes.io/os: linux
...
```

cc/ @kubernetes/sig-node-bugs @mikedanese
