### ISSUE TITLE
`kubectl get all` do not return `ingress`, `daemonset` resource etc.

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#42941]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
1) My yaml template
```
[root@bd002 nodeport-ingress]# cat test.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mynginx
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mynginx.com
    http:
      paths:
      - path: /v1
        backend:
          serviceName: my-nginx
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: my-nginx
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: my-nginx
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - image: gyliu/nginxv1:1.0
        imagePullPolicy: IfNotPresent
        name: my-nginx
        ports:
        - containerPort: 80
          protocol: TCP
```

2) Create and get all, from `create`, we can see `ingress` was created, but `get all` do not include `ingress`.
```
[root@bd002 nodeport-ingress]# kubectl create -f ./test.yaml
ingress "mynginx" created
service "my-nginx" created
deployment "my-nginx" created
[root@bd002 nodeport-ingress]# kubectl get all
NAME                           READY     STATUS    RESTARTS   AGE
po/my-nginx-1427292677-8502t   1/1       Running   0          4s
po/my-nginx-1427292677-ggs3r   1/1       Running   0          4s
po/my-nginx-1427292677-mdhld   1/1       Running   0          4s

NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
svc/kubernetes   10.0.0.1     <none>        443/TCP        6d
svc/my-nginx     10.0.0.206   <nodes>       80:30857/TCP   4s

NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/my-nginx   3         3         3            3           4s

NAME                     DESIRED   CURRENT   READY     AGE
rs/my-nginx-1427292677   3         3         3         4s
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
