### ISSUE TITLE
Kubernetes Problem with With Petsets.

### ISSUE THREAD

**Issue by Venkat-Sudharsanam** [kubernetes/kubernetes#42955]
Hi Guys,

I'm using Kubernetes 1.5.I working on a Ubuntu VM on my machine.
I was going through the documentation in the official website for petset.

https://kubernetes.io/docs/user-guide/petset/

I tried to launch a PetSet which was given in the example section, but im getting the below error:

```
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  # *.nginx.default.svc.cluster.local
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

I'm getting the below error when launching it,

```
kubectl create -f pet.yaml
service "nginx" created
error: unable to recognize "pet.yaml": no matches for apps/, Kind=PetSet
```

**Comment by kargakis** [comment]
PetSets are renamed to StatefulSets in 1.5.

**Comment by Venkat-Sudharsanam** [comment]
Thanks,

after creating a statefulset, the pod is in pending status,

```
vi state.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```


```
kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
web-0     0/1       Pending   0          6m
```
