### ISSUE TITLE
Second AZ not added to ELB on AWS

### ISSUE THREAD

**Issue by pettair** [kubernetes/kubernetes#42963]
**Kubernetes version**
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
AWS
- **Install tools**:
kube-aws v0.9.4

 
Im creating my cluster on AWS with kube-aws v0.9.4 using the following configuration:
```
controller:
  autoScalingGroup:
    minSize: 1
    maxSize: 3
    rollingUpdateMinInstancesInService: 2
  subnets:
    - name: ManagedPublicSubnet1
worker:
  nodePools:
    - name: nodepool1
      count: 1
      subnet:
      - name: ManagedPrivateSubnet1
      autoScalingGroup:
        minSize: 1
        maxSize: 3
        rollingUpdateMinInstancesInService: 2
    - name: nodepool2
      count: 1
      subnet:
      - name: ManagedPrivateSubnet2
      autoScalingGroup:
        minSize: 1
        maxSize: 3
        rollingUpdateMinInstancesInService: 2
subnets:
  - name: ManagedPublicSubnet1
    availabilityZone: us-east-1a
    instanceCIDR: "10.0.100.0/24"
    routeTable:
      id: <existing_route_table_id>
  - name: ManagedPrivateSubnet1
    private: true
    availabilityZone: us-east-1a
    instanceCIDR: "10.0.101.0/24"
    natGateway:
      id: <existing_nat_gateway_id>
  - name: ManagedPrivateSubnet2
    private: true
    availabilityZone: us-east-1b
    instanceCIDR: "10.0.102.0/24"
    natGateway:
      id: <existing_nat_gateway_id>
```

After the cluster setup completes, I used the [MySQL and WordPress on Kubernetes](https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-wordpress-pd) service example for testing.

I found that the pods are dployed to all of two AZs, but the instance in the second AZ are marked unhealthy in the ELB
```sh
aws elb describe-instance-health --load-balancer-name a83c1f356071e11e7a2ef0a85d083008
```
```json
{
    "InstanceStates": [
        {
            "InstanceId": "i-0768b4671e258002d", 
            "ReasonCode": "N/A", 
            "State": "InService", 
            "Description": "N/A"
        }, 
        {
            "InstanceId": "i-0e2a649e8db4f6b35", 
            "ReasonCode": "Instance", 
            "State": "OutOfService", 
            "Description": "Instance is in the EC2 Availability Zone for which LoadBalancer is not configured to route traffic to."
        }, 
        {
            "InstanceId": "i-0e9ac5b71dbb639e0", 
            "ReasonCode": "N/A", 
            "State": "InService", 
            "Description": "N/A"
        }
    ]
}
```
From further investigation it seems like not all subnets are added to ELB
```sh
aws elb describe-load-balancers  --load-balancer-names a83c1f356071e11e7a2ef0a85d083008
```
```json
{
    "LoadBalancerDescriptions": [
        {
            "Subnets": [
                "subnet-1c58b554"
            ], 
            "CanonicalHostedZoneNameID": "Z35SXDOTRQ7X7K", 
            "CanonicalHostedZoneName": "a83c1f356071e11e7a2ef0a85d083008-2093657804.us-east-1.elb.amazonaws.com", 
            "ListenerDescriptions": [
                {
                    "Listener": {
                        "InstancePort": 32743, 
                        "LoadBalancerPort": 80, 
                        "Protocol": "TCP", 
                        "InstanceProtocol": "TCP"
                    }, 
                    "PolicyNames": []
                }
            ], 
            "HealthCheck": {
                "HealthyThreshold": 2, 
                "Interval": 10, 
                "Target": "TCP:32743", 
                "Timeout": 5, 
                "UnhealthyThreshold": 6
            }, 
            "VPCId": "vpc-cf9e1da9", 
            "BackendServerDescriptions": [], 
            "Instances": [
                {
                    "InstanceId": "i-0e2a649e8db4f6b35"
                }, 
                {
                    "InstanceId": "i-0e9ac5b71dbb639e0"
                }, 
                {
                    "InstanceId": "i-0768b4671e258002d"
                }
            ], 
            "DNSName": "a83c1f356071e11e7a2ef0a85d083008-2093657804.us-east-1.elb.amazonaws.com", 
            "SecurityGroups": [
                "sg-31bc7f4e"
            ], 
            "Policies": {
                "LBCookieStickinessPolicies": [], 
                "AppCookieStickinessPolicies": [], 
                "OtherPolicies": []
            }, 
            "LoadBalancerName": "a83c1f356071e11e7a2ef0a85d083008", 
            "CreatedTime": "2017-03-12T12:22:11.570Z", 
            "AvailabilityZones": [
                "us-east-1c"
            ], 
            "Scheme": "internet-facing", 
            "SourceSecurityGroup": {
                "OwnerAlias": "482532884737", 
                "GroupName": "k8s-elb-a83c1f356071e11e7a2ef0a85d083008"
            }
        }
    ]
}
```
If I add the second subnet manually it works as expected. Also it would be nice if the "Cross-Zone Load Balancing" would be enabled on ELBs with multiple AZ
