### ISSUE TITLE
NodePort service failed quite a lot when scale down application

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#43046]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
1) First deploy an application with 50 replica with a `NodePort` service
2) Start `ab` to test the performance of the `NodePort` service
3) Scale down the deployment
4) Check the final `ab` test result, there are some failed request.

Seems the `NodePort` service do not  have some logic as `retry` etc, so there maybe cases that the request failed.

Does anyone have some experience in handling such case in large scale cluster with kube proxy? Thanks in advance!

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by gyliu513** [comment]
The `readinessProbe` can help such case, but it will impact the speed for service discovery.

```yaml
    readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
```

**Comment by rata** [comment]
Does it happen with the readiness probe too?

**Comment by gyliu513** [comment]
Yes, the `readiness probe` can only help for scale up, but does not help when scale down.

**Comment by xiangpengzhao** [comment]
A preStop hook might help for scaling down.

**Comment by gyliu513** [comment]
Does there are any reference that I can take for the `preStop` hook? @xiangpengzhao

**Comment by xiangpengzhao** [comment]
@gyliu513 See https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-details

**Comment by rata** [comment]
@gyliu513 you might be failing to answer in flight requests. Using a pre-stop hook, as @xialonglee suggested, can help. For example, in pods that have nginx I have:

```
        lifecycle:
         preStop:
          exec:
             command: ["nginx", "-s", "quit"]
```

That command tells nginx to stop accepting new requests and finish in-flight request procesing and then just stop.

Something like this might do the trick
