### ISSUE TITLE
Node's allocatable resource always equals to its capacity

### ISSUE THREAD

**Issue by wenlxie** [kubernetes/kubernetes#43045]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No, report a bug.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):

1.5.1
**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
CentOS Linux release 7.2.1511 (Core)
- **Kernel** (e.g. `uname -a`):
3.10.0-327.36.3.el7.x86_64
- **Install tools**:
- **Others**:

**What happened**:
I use 
**'kubectl get nodes **** -o yaml'**  to get the node's informations.
Then I find the allocatable resource and it's capacity are always the same.
I have some  pods running on that pod and created with resource request and resource limit configure.

```
 allocatable:
    alpha.kubernetes.io/nvidia-gpu: "0"
    cpu: "40"
    memory: 131801312Ki
    pods: "110"
  capacity:
    alpha.kubernetes.io/nvidia-gpu: "0"
    cpu: "40"
    memory: 131801312Ki
    pods: "110"
```

```
 nodeInfo:
    architecture: amd64
    bootID: xxxxxxxxxxxxxxxxxxx
    containerRuntimeVersion: docker://1.11.2
    kernelVersion: 3.10.0-327.36.3.el7.x86_64
    kubeProxyVersion: v1.5.1
    kubeletVersion: v1.5.1
    machineID: xxxxxxxxx
    operatingSystem: linux
    osImage: CentOS Linux 7 (Core)
    systemUUID: xxxxxxxxxxx
```

**What you expected to happen**:

The allocatable resource should less than the capacity.

**How to reproduce it** (as minimally and precisely as possible):

Just get the node status

**Anything else we need to know**:
