### ISSUE TITLE
Unable to provision vSphere volume if PVC's requested size does not have unit

### ISSUE THREAD

**Issue by childsb** [kubernetes/kubernetes#43319]
The other provisioners allow a number only size for provisioning and assumes a default (usually gigs).  This doesn't work in vsphere provisioned volumes.

StorageClass:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: 5aezi-8ead3w8h
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/vsphere-volume
```

PVC:
```json
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "vsphere2",
    "annotations": {
        "volume.beta.kubernetes.io/storage-class": "5aezi-8ead3w8h"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": 1
      }
    }
  }
}
```
