### ISSUE TITLE
Kubectl PodSpec Validation fails

### ISSUE THREAD

**Issue by johscheuer** [kubernetes/kubernetes#43347]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

` kubectl validation`, `kubectl`, `kubectl hostpid `
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-08T02:50:34Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-08T02:50:34Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**:
AWS with custom deployment (Ansible)
- **OS** (e.g. from /etc/os-release):
CentOS 7 (Server)
MacOS (Client)

**What happened**:
The option `hostPID: true` had a wrong intend (2 spaces to much) and kubectl created the Pod anyway (without the option).

**What you expected to happen**:
An error `PodSpec validation error/YAML malformed` (or something similar)

**How to reproduce it** (as minimally and precisely as possible):
Use a YAML file with the wrong intend at hostPID (should be at pod level not container level):

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        image: ubuntu:16.04
        command:
          - /bin/sh
          - -xec
          - |
            sleep 99999999
        securityContext:
          privileged: true
        hostPID: true
```

correct yaml:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        image: ubuntu:16.04
        command:
          - /bin/sh
          - -xec
          - |
            sleep 99999999
        securityContext:
          privileged: true
      hostPID: true
```

**Anything else we need to know**:

I didn't tried if this behaviour also appears for other resources than DaemonSets (but I would assume that the error is in the `PodSpec` validation step (which probably should be independent from the parent resource.
