### ISSUE TITLE
Kubernetes do not support publish all exposed ports to random ports

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#43564]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Currently in Kubernetes, if I want to enable the docker host port mapping, I have to write the `hostPort` explicitly in the yaml template and kubernetes cannot publish the host ports to random ports like docker does in `docker run -P`.

```yaml
    ports:
    - containerPort: 2381
      hostPort: 2381
      name: serverport
      protocol: TCP
    - containerPort: 4002
      hostPort: 4002
      name: clientport
      protocol: TCP
```

This is not convenient for some customers who want to use docker's port mapping feature as the end user need to set the `hostPort` by themselves and this may cause some port conflict especially when scale up a pod on same node. Yes, we can workaround the scale up issue with `pod anti affinity` feature, but it is not convenient to let end user write those `hostPorts` for a large deployment with many exposed `hostPort`.  

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
