### ISSUE TITLE
Lost requests when doing a rolling update

### ISSUE THREAD

**Issue by foxylion** [kubernetes/kubernetes#43576]
**Kubernetes version** (use `kubectl version`): 1.5.2

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS**: Debian GNU/Linux 8 (jessie)
- **Kernel**: `Linux ip-10-234-53-65 4.4.26-k8s #1 SMP Fri Oct 21 05:21:13 UTC 2016 x86_64 GNU/Linux`
- **Install tools**: kops
- **Others**: -

**What happened**:
When I update a deployment behind a service (type `NodePort`) for a short time requests are lost.

**What you expected to happen**:
There shouldn't be any request getting lost.

**How to reproduce it** (as minimally and precisely as possible):
1. Use `kubectl apply`
```
kind: Service
apiVersion: v1
metadata:
  name: zero-downtime-test
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: zero-downtime-test
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zero-downtime-test
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: zero-downtime-test
    spec:
      containers:
      - name: backend
        image: nginx:1.11
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        ports:
        - containerPort: 80
          protocol: TCP
```
2. Now do constantly request the node port and check if response is a valid 200 status code. (e.g. with JMeter and ~60 req/second)
3. Modify the deployment so that a rolling update is triggered.
4. For a few milliseconds requests won't be answered.

**Anything else we need to know**:
When adding the following to my deployment it works fine.
```
    lifecycle:
      preStop:
        exec:
          command: ["sleep, "1"]
```
Therefore I think this might be a timing issue where the pod gets the termination signal before it is removed from the service load balancing.
