### ISSUE TITLE
Initcontainer with only a cat command gets stuck

### ISSUE THREAD

**Issue by jonathan-kosgei** [kubernetes/kubernetes#43582]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): container os
- **Kernel** (e.g. `uname -a`): 
- **Install tools**:
- **Others**:

**What happened**:

I have an etcd statefulset with the following initcontainer declaration that gets stuck even though it's a very simple cat command

```
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  ports:
  - name: etcd
    port: 2376
  clusterIP: None
  selector:
    app: etcd

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: etcd
  namespace: default
spec:
  serviceName: etcd
  replicas: 3
  template:
    metadata:
      labels:
        name: etcd
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "busybox",
            "image": "busybox",
            "command": ["bash", "-c", "
            cat <<\"EOF\" > /mnt/scripts/etcd.sh\n
            #!/bin/sh\n
            [[ `hostname` =~ -([0-9]+)$ ]] || exit 1\n
            ordinal=${BASH_REMATCH[1]}\n
            for ord in $(seq 0 $ordinal);\n
            do\n
                peers+=etcd$ord=http://etcd-$ord:2380,;\n
            done\n
            peers=${peers: : -1}\n
            etcd --name=etcd0 --advertise-client-urls=http://`hostname`:2379 --listen-client-urls=http://0.0.0.0:2379 --listen-peer-urls=http://0.0.0.0:2380 --data-dir=/var/lib/etcd/data --wal-dir=/var/lib/etcd/wal --election-timeout=1000 --heartbeat-interval=100 --snapshot-count=1000 --max-snapshots=5 --max-wals=5 --initial-advertise-peer-urls=http://`hostname`:2380 --initial-cluster=$peers --initial-cluster-state=new\n
            EOF\n
            "],
            "volumeMounts": [
              {"name": "etcd-persistent-storage", "mountPath": "/mnt/scripts"}
            ]
          }]'
      name: etcd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: etcd
        image: quay.io/coreos/etcd
        command: ["./var/lib/etcd/etcd.sh"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports: 
          - containerPort: 2379
            name: etcd
        volumeMounts:
        - name: etcd-persistent-storage
          mountPath: /var/lib/etcd
      volumes:
      - name: etcd-persistent-storage
        persistentVolumeClaim:
          claimName: gluster-etcd
```

**What you expected to happen**:

The initcontainer to start and complete promptly as expected.

**How to reproduce it** (as minimally and precisely as possible):

Create a stateful set with the above spec
**Anything else we need to know**:
