### ISSUE TITLE
GCE Storage class auto-provisioning SchedulerPredicates failed due to PersistentVolumeClaim is not bound

### ISSUE THREAD

**Issue by jonathan-kosgei** [kubernetes/kubernetes#43629]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): container os
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I have the following Storageclass:
```
jonathan@ubuntu ~/P/k8wp> kubectl describe storageclass fast
Name:		fast
IsDefaultClass:	Yes
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"kind":"StorageClass","apiVersion":"storage.k8s.io/v1beta1","metadata":{"name":"fast","creationTimestamp":null,"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"}},"provisioner":"kubernetes.io/gce-pd","parameters":{"type":"pd-ssd","zone":"us-central1-a"}},storageclass.beta.kubernetes.io/is-default-class=true
Provisioner:	kubernetes.io/gce-pd
Parameters:	type=pd-ssd,zone=us-central1-a
No events.
```
With that I create the following statefulset:
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: percona
  namespace: default
spec:
  serviceName: percona
  replicas: 1
  template:
    metadata:
      labels:
        app: percona
      name: percona
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: percona
        image: percona/percona-xtradb-cluster
        volumeMounts:
        - name: percona
          mountPath: /var/lib/mysql
          subPath: mysql
  volumeClaimTemplates:
  - metadata:
      name: percona
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
```

However the pod doesn't come up and gives the error:
```
FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "percona-percona-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "percona-percona-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "percona-percona-0", which is unexpected.
```
**What you expected to happen**:
An ssd persistent disk to be created on GKE and mounted to the percona pod. Currently the pvc looks like this, stuck in pending:
```
jonathan@ubuntu ~/P/k8wp> kubectl describe pvc percona-percona-0
Name:		percona-percona-0
Namespace:	default
StorageClass:	
Status:		Pending
Volume:		
Labels:		app=percona
Capacity:	
Access Modes:	
No events.
```

**How to reproduce it** (as minimally and precisely as possible):
Create the above stated resources.

**Anything else we need to know**:
