### ISSUE TITLE
Manual upgrade of HPA (Horizonatal Pod Autoscaler) for v1.6

### ISSUE THREAD

**Issue by anhowe** [kubernetes/kubernetes#43638]
V1.6 Blocking 

A manual upgrade test to verify HPA is required.

**Horizontal pod autoscaler Instructions**
1. Use the HPA demo: https://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/

2. Create a Job:
```
Appendix: Job
apiVersion: batch/v1
kind: Job
metadata:
  name: long
spec:
  template:
    metadata:
      name: long
    spec:
      containers:
      - name: c
        image: busybox
        command: ["/bin/sh",  "-c", "sleep 1800"]
      restartPolicy: Never
  parallelism: 3
  completions: 3
```

3. Verify that job finishes successfully, upgrading master does not affect pods, pods get re-created after node upgrade, “kubectl get jobs” shows SUCCESSFUL == DESIRED

4. Various events get generated automatically, so just make sure you see the same events after the upgrade as before (plus whatever new ones should have been generated)

cc: @pwittrock
