### ISSUE TITLE
How can i test init-container

### ISSUE THREAD

**Issue by chinakevinguo** [kubernetes/kubernetes#43789]
Hi guys:
           see my rc file. 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      initContainers:
      - name: install
        image: busybox
        command:
        - mv
        - "-f"
        - "/configfile/index.html"
        - "/usr/local/tomcat/webapps/ROOT/"
        volumeMounts:
        - name: indexhtml
          mountPath: /configfile
        volumes:
        - name: indexhtml
          configMap:
            name: webapp-config
      containers:
      - name: webapp
        image: tomcat
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/tomcat/logs
          name: logfile
      volumes:
      - hostPath:
          path: /tomcat-logs
        name: logfile
                            
```

I used command `kubectl create -f rc.yaml`
I got this error 
```
error: error validating "webapp-rc.yaml": error validating data: found invalid field initContainers for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

maybe my kubernetes version is wrong ?
my version is 1.5.2
