### ISSUE TITLE
Error when deleting pvc (Error: Volume has no class annotation)

### ISSUE THREAD

**Issue by z1oy** [kubernetes/kubernetes#43929]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-beta.4", GitCommit:"b202120be3a97e5f8a5e20da51d0b6f5a1eebd31", GitTreeState:"clean", BuildDate:"2017-03-17T17:54:01Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0+coreos.0", GitCommit:"8031716957d697332f9234ddf85febb07ac6c3e3", GitTreeState:"clean", BuildDate:"2017-03-29T04:33:09Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):CoreOS
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: Im createing sc:
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://1.1.1.1:8080"
  restauthenabled: "false"
```
When create pvc:
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "storage"
spec:
  storageClassName: storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

```
It's ok. pvc work fine. But... if try delete it:
`E0331 21:41:05.571085       1 goroutinemap.go:164] Operation for "delete-pvc-445baf6f-1658-11e7-b0dd-005056ab5e09[47add018-1658-11e7-b0dd-005056ab5e09]" failed. No retries permitted until 2017-03-31 21:43:05.571044995 +0000 UTC (durationBeforeRetry 2m0s). Error: Volume has no class annotation`

This was due to the fact that:
1. https://github.com/kubernetes/kubernetes/pull/35051 
`
className, found := pv.Annotations["volume.beta.kubernetes.io/storage-class"]
if !found {
return nil, fmt.Errorf("Volume has no class annotation")
}
`
2. controller-manager create pv:
```
Name:           pvc-f3a7ac9b-1563-11e7-88b3-005056ab5e09
Labels:         <none>
Annotations:    pv.beta.kubernetes.io/gid=5000
                pv.kubernetes.io/bound-by-controller=yes
                pv.kubernetes.io/provisioned-by=kubernetes.io/glusterfs
StorageClass:   storage
Status:         Bound
Claim:          kube-system/pvc
Reclaim Policy: Delete
Access Modes:   RWO
Capacity:       1Gi
Message:
Source:
    Type:               Glusterfs (a Glusterfs mount on the host that shares a pod's lifetime)
    EndpointsName:      glusterfs-dynamic-pvc
    Path:               vol_649c33c97b1926d6952aa78568d8becf
    ReadOnly:           false
Events:                 <none>
```
As you can see, there is no annotation:
`volume.beta.kubernetes.io/storage-class: "storage"`
If I add annotation to the created pv, then deletion ends with success
