### ISSUE TITLE
No access to resources due to new auth strategy by kubeadm

### ISSUE THREAD

**Issue by silentred** [kubernetes/kubernetes#43935]
**Kubernetes version** (use `kubectl version`):
kubeadm v1.6.0

**Environment**:
- **OS** (e.g. from /etc/os-release):

NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.10"
VERSION_ID="16.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="http://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=yakkety
UBUNTU_CODENAME=yakkety

Linux tokyo-02 4.8.0-41-generic #44-Ubuntu SMP Fri Mar 3 15:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:
I use this config file(https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml) for scrape apiserve, nodes and services. It seems kubeadm use a new auth mode. How can I change auth mode to "AlwaysAllow"?

```
time="2017-04-01T03:27:55Z" level=error msg="github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Node: the server does not allow access to the requested resource (get nodes)" component="kube_client_runtime" source="kubernetes.go:73"

time="2017-04-01T03:27:56Z" level=error msg="github.com/prometheus/prometheus/vendor/k8s.io/client-go/1.5/tools/cache/reflector.go:109: Failed to list *v1.Service: the server does not allow access to the requested resource (get services)" component="kube_client_runtime" source="kubernetes.go:73"
```

It seems because kubeadm uses RBAC as auth strategy instead of static token. So the prometheus config `bearer_token_file` does not work under the condition. Is there any work around for this?

**Comment by liggitt** [comment]
The bearer token file authentication can still be valid, but permission must be given to the user the token identifies.

**Comment by liggitt** [comment]
Granting permissions to API users with kubectl commands is described in https://kubernetes.io/docs/admin/authorization/rbac/

**Comment by liggitt** [comment]
You can give a specific user (like the one the Prometheus token identifies) superuser permissions by binding the `cluster-admin` role to them

**Comment by silentred** [comment]
@liggitt Thanks. Still learning all the concepts. There are a lot. This role-binding config works for me. 
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin-binding
subjects:
- kind: Group
  name: admin
- kind: ServiceAccount
  name: default
  namespace: kube-system
# - kind: ServiceAccount
#   name: hello
#   namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```

**Comment by fcgravalos** [comment]
I'd just add what it requires: list and get nodes and services. cluster-admin would allow reading other namespaces secrets or other resources.

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prometheus-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
```
```
kind: ClusterRoleBinding
roleRef: 
     kind: Role
     name: pod-reader
     apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: prometheus #Assuming you created a namespace for it.
```
