### ISSUE TITLE
Docker registry addon produces a non-functional proxy foor the registry

### ISSUE THREAD

**Issue by ChipmunkV** [kubernetes/kubernetes#43986]
This registry guide is probably outdated or nor sufficiently self-contained:

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/registry/README.md

**Kubernetes version**:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **OS**: Ubuntu 16.04.2 LTS (Xenial Xerus)
- **Install**: `kubeadm init` and weave: https://github.com/weaveworks/weave/releases/download/latest_release/weave-daemonset-k8s-1.6.yaml

There are two nodes. I've followed the registry guide https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/registry/README.md

It promises that at the end there will be a port on localhost of each node to access the registry.

But the `nmap -p 5050 localhost` on any node shows that it's closed on all nodes.

**State**:
```
$ kubectl get pods
NAME                        READY     STATUS    RESTARTS   AGE
kube-registry-proxy-plx03   1/1       Running   0          15m
kube-registry-v0-07b4g      1/1       Running   0          1h
$ kubectl get service kube-registry
NAME            CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kube-registry   10.107.139.82   <none>        5050/TCP   19m
```

**Config to reproduce:**
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry-v0
  namespace: default
  labels:
    k8s-app: kube-registry
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-registry
    version: v0
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: registry:2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5050
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
        - containerPort: 5050
          name: registry
          protocol: TCP
      volumes:
      - name: image-store
        emptyDir: {}
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: default
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry
  ports:
  - name: registry
    port: 5050
    protocol: TCP
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-registry-proxy
  namespace: default
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    version: v0.4
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        kubernetes.io/name: "kube-registry-proxy"
        kubernetes.io/cluster-service: "true"
        version: v0.4
    spec:
      containers:
      - name: kube-registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.4
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: kube-registry.default.svc.cluster.local
        - name: REGISTRY_PORT
          value: "5050"
        ports:
        - name: registry
          containerPort: 80
          hostPort: 5050
```
