### ISSUE TITLE
Persistent volume claim ignores  storage request and claims full size, leaving other requests pending

### ISSUE THREAD

**Issue by EVODelavega** [kubernetes/kubernetes#43991]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
Persistent volume claim request storage full size persistent volume (any variation/combination of these words....)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version**:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- AWS (c4.xlarge, t2.large)
- terraform, ansible, Jenkins pipelines, ECR, docker, ... the usual suspects

**What happened**:

I basically needed some nodes to have some extra disk space because they were processing large files. Nothing to do with state, but I just needed to get the load on kubernetes down a bit. Because AWS EBS only allows RWO mounts, I thought creating a single PV with multiple claims would do the job. A bit more cumbersome than I'd hoped, but it would work. I basically followed the simplest documented example: https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

To my surprise, I found that the first PVC I created went ahead to claim the *full* 20 Gi of the PV, even though I specified a request of 5Gi. On closer inspection I noticed that the documentation contains the output of `kubectl get pvc task-pv-claim`: 

```
NAME            STATUS    VOLUME           CAPACITY   ACCESSMODES   AGE
task-pv-claim   Bound     task-pv-volume   10Gi       RWO           5s
```

Even though the requested storage is only 3Gi.

Things I tried to get the desired result include:

* Setting up a PV, and 1 PVC, using the same PVC to mount 3 chunks (ie 3 * 3Gb of a 10Gb EBS volume) - This did not work
* I tried adding limits to my PVC's to ensure the claim wouldn't exceed a certain size. Rather than getting errors, or warnings, it just didn't seem to make any difference at all. The first PVC still claims the full 20G.
* All sorts of silly things really
* Eventually accepted that the only solution I could think of was to create 1 EBS volume per mount I need. This is less than ideal, of course.

**What you expected to happen**:

I expect to be able to specify, in PVC's the amount of storage to request from the PV, and be able to specify how much space should be claimed.

**How to reproduce it** 

Here's the files I used in the process (in their current form):

storageclass.yaml

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: "foobar" # comes from env, too
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: "{{ AWS_ZONE }}" # comes from env var
```
persistent-volume.yaml

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-volume-name
  annotations:
    volume.beta.kubernetes.io/storage-class: "foobar"
spec:
  capacity:
    storage: 20Gi # EBS volume exists, is 20Gb and available
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: "vol-123abc" # ,,, redacted obviously
    readOnly: false

```

One of the PVC's:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-name-foobar1
  annotations:
    volume.beta.kubernetes.io/storage-class: "foobar"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    ## Limits bit was added at a later stage
    limits:
      storage: 5Gi
    requests:
      storage: 5Gi
```

There's 2 more PVC files, each identical apart from the name (`pvc-name-foobar{1,2,3}` essentially).

For completeness' sake, I mount the volumes like so:

```yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    run: my-stuff
  name: my-stuff
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      run: my-stuff
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: my-stuff
    spec:
      containers:
      - env:
        - name: TCP_PROMETHEUS
          value: ":9090"
        image: local.container.repo/stuff:latest
        name: my-stuff
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          httpGet:
            path: '/metrics'
            port: 9090
        volumeMounts:
          - name: my-stuff-volume
            mountPath: "/stuff"
      volumes:
        - name: my-stuff-volume
          persistentVolumeClaim:
            claimName: pvc-name-foobar1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "9090"
  labels:
    run: my-stuff
  name: my-stuff
spec:
  ports:
  - protocol: TCP
    port: 9090
  selector:
    run: my-stuff

```

After all the things I tried, the best output I got for `kubectl get pvc` on the relevant namespace was this:

```
NAME                 STATUS     VOLUME             CAPACITY   ACCESSMODES   AGE
pvc-name-foobar1     Bound      pv-my-volume-name  20Gi       RWO           27m
pvc-name-foobar2     Pending                                                27m
pvc-name-foobar3     Pending                                                27m
```

What I expected was

```
NAME                 STATUS     VOLUME             CAPACITY   ACCESSMODES   AGE
pvc-name-foobar1     Bound      pv-my-volume-name  5Gi        RWO           27m
pvc-name-foobar2     Bound      pv-my-volume-name  5Gi        RWO           27m
pvc-name-foobar3     Bound      pv-my-volume-name  5Gi        RWO           27m
```

**Anything else we need to know**:

I'm currently left with no other option than to create a new EBS volume, add it (PV), add a claim (PVC), each time I want to ensure I'm not maxing out the disk space. This is possible, but very tedious, cumbersome, and doesn't allow me to horizontally scale (replicate X twice, and it won't be able to mount the volume thanks to RWO). I know some of the issues are caused by AWS being a PITA, but surely... if you can specify the resoure request in a PVC, it's not right for it to be completely ignored.

I'm submitting this as a bug report because the documentation clearly shows a claim for *less* than the PV's size, and yet the PVC shows the full size (not even a multiple of the PVC size). I tried with a PVC of 3 Gb, on a volume of 10Gb (expecting to see 3, or perhaps 9).

Besides, the linked page quite clearly states:

> ## The next step is to create a PersistentVolumeClaim. Pods use PersistentVolumeClaims to request physical storage. In this exercise, you create a PersistentVolumeClaim that requests a volume of at least three gibibytes that can provide read-write access for at least one Node.

It seems to me that this is not possible. Or at least not following the documentation I found.

**Comment by wongma7** [comment]
There is a 1:1 mapping between PV & PVC. An ebs disk can only be attached to one node at a time, it wouldn't make sense to allow multiple PVs/PVCs to represent one disk when the pods that consume the PVCs could be on different nodes. RE: capacity mismatch, this is intended as well, kube is simply doing its best to satisfy your claim: give it at least what it asks for. All this is detailed here https://kubernetes.io/docs/concepts/storage/persistent-volumes/

The solution to the tedium of creating every EBS+PV is to use dynamic provisioning: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#aws.

Since all this behavior is expected I wold open an issue at https://github.com/kubernetes/kubernetes.github.io to improve+clarify the docs

**Comment by shanmugakarna** [comment]
This is same with NFS PV also. NFS supports RWX and should be able to slice the size in PVCs

nfs-pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: "Delete"
  nfs:
    server: 10.0.0.1
    path: "/export"
```

nfs-pvc.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
```

The `spec.requests.storage` is ignored here. and it allocates all resources to `data` pvc

**Version Info:**
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}```
