### ISSUE TITLE
vsphere volume: Datastore cluster

### ISSUE THREAD

**Issue by moserke** [kubernetes/kubernetes#44007]
With version 1.4.7 I could use a datastore that is in a cluster as a vsphere volume as ```volumePath: "[datastore] path/to/file"```.  When I upgraded to 1.6.0, this same exact path does not work and throws a ```datastore 'datastore' not found``` error.  I'm struggling to find what changed, but am guessing it's difference in how the datastore is being looked up in vcenter.

Has anyone had luck with this?

**Comment by divyenpatel** [comment]
We have verified creating pod using static PV and dynamic provisioning, both works fine with
`Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.1-beta.0.12+018a96913f57f9"`

Can you post /etc/kubernetes/vsphere.conf  here? 

cc: @BaluDontu

**Comment by moserke** [comment]
Did that include using a datastore that was in a datastore cluster?  That seemed to be working before because the datastore previously (before 1.5) was read out of the global config, which supported datastore path with cluster name.

But post 1.5 datastore is parsed from the ```[datastore] path/to/file``` entry, which if you include the path to the cluster it gets you past the datastore lookup, but then when you go to add the disk it fails because that is not valid to vCenter.  It's kind of this weird mixed mode, because to look up the datastore you need the path including the cluster, but to create the file you need the path without the cluster.

I presume the PV is working because they use the cloud config values?  I was not using a PV but putting a volumePath directly in my deployment yaml.  Should I be using a PV to do this?  If the deployment is deleted and re-created how do I guarantee that my pod would get the same PV claim?  That was why I did not go down that path originally.  I'm pretty sure I have narrowed down where in the provider this is happening, but didn't see a good path to get it to work.  I have, admittantly, not tried PV/PVCs yet, due to the concern raised above, but could try those to see.

The pertinent part of the deployment yaml:

```
securityContext:
  fsGroup: 1000
volumes:
  - name: mount
    vsphereVolume:
      volumePath: "[datastore] path/to/file"
      fsType: ext4
containers:
  - name: name
    image: image
    imagePullPolicy: Always
    volumeMounts:
      - name: mount
        mountPath: /var/mount
```

The cloud config:

```
[Global]
user = username
password = password
server = vcenter_server
port = 443
insecure-flag = true
datacenter = datacenter
datastore = datastore_cluster/datastore
working-dir = path/to/folder

[Disk]
scsicontrollertype = pvscsi
```
