### ISSUE TITLE
hostPID doesn't seem to work on Kubernetes 1.6

### ISSUE THREAD

**Issue by unclejack** [kubernetes/kubernetes#44041]
*Kubernetes version** (use `kubectl version`):
1.6.1, 1.6.0 (both run into this issue)

**Environment**:
- **Cloud provider or hardware configuration**: VirtualBox 5.1.18 VM
- **OS**: 16.04.2 LTS (Xenial Xerus)
- **Kernel**: `4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` 
- **Install tools**: kubeadm

**What happened**:
A pod scheduled using hostPID wasn't using the host's PID namespace.

I've investigated this issue together with @neelimamukiri.

**What you expected to happen**:
I expected `"PidMode": "host",` in the Docker container's config.
Instead, the scheduled pod's container had `"PidMode": "",`

**How to reproduce it**:
Use this config to get a pod running a Docker container:
```
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: busybox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: busybox
subjects:
- kind: ServiceAccount
  name: busybox
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: busybox
  namespace: kube-system
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups: [""]
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups: ["extensions"]
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: busybox
  namespace: kube-system

---


kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: busybox
  namespace: kube-system
  labels:
    k8s-app: busybox
spec:
  selector:
    matchLabels:
      k8s-app: busybox
  template:
    metadata:
      labels:
        k8s-app: busybox
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: busybox
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - "3600"
          securityContext:
            privileged: true
--- 
```
Use `docker inspect` on the running container and check whether PidMode is set to host or not.

**Anything else we need to know**:
This was working properly on Kubernetes 1.5.3.
