### ISSUE TITLE
vSphere cloud provider returns IP addresses from all kernel interfaces

### ISSUE THREAD

**Issue by dcbw** [kubernetes/kubernetes#44075]
See https://bugzilla.redhat.com/show_bug.cgi?id=1433236:

```
status:
  addresses:
  - address: 10.128.0.1
    type: ExternalIP
  - address: fe80::6083:bfff:febf:db75
    type: ExternalIP
  - address: 10.66.146.29
    type: InternalIP
  - address: 2620:52:0:4292:250:56ff:fe9f:b058
    type: InternalIP
  - address: fe80::250:56ff:fe9f:b058
    type: InternalIP
  - address: 172.17.0.1
    type: ExternalIP
  - address: fe80::42:2eff:fe71:6bcd
    type: ExternalIP
  - address: master.c.vsphere.local
    type: Hostname
```

In this example, 172.17.0.1 is 'docker0', 10.128.0.1 is 'tun0' (a non-routable interface created by OpenShift), and 10.66.146.29 is 'ens192' which is the actual routable interface for this VM.

I don't think the vSphere cloud provider is using the same criteria for ExternalIP and InternalIP that other cloud providers are, and that makes it hard for network plugins to work with different cloud providers.  Admittedly, NodeInternalIP and NodeExternalIP are not really specified in any way in pkg/api/*, there's only convention to go on.  And conventions are:

- AWS and GCE define ExternalIPs as the public Internet IP address (if any) that the node can be reached at.  They define InternalIPs as non-public IP addresses that the node can be reached by any other node on the same network.
- Azure only returns InternalIPs using the "PrivateIPAddress" of the "Primary" interface.
- OpenStack returns 'floating' or 'public' IPs (typically used for outside-the-cluster access) as ExternalIP, all others are InternalIP.

By these definitions I would expect vSphere to use 'public-network' to select a specific NIC to present as InternalIP, and all other IP addresses would be ignored.  PublicNetwork is defined as "PublicNetwork is name of the network the VMs are joined to." which is almost exactly what GCE, AWS, and OpenStack define InternalIP as.

vSphere would not define any ExternalIP unless it could prove that IP address was publicly exposed outside of the cluster.  Perhaps add another cloud-init parameter for "ExternalNetwork" or something?

@kubernetes/rh-networking @kubernetes/sig-network-bugs @eparis @knobunc
