### ISSUE TITLE
fsGroup in not used for azureFile

### ISSUE THREAD

**Issue by avaranovich** [kubernetes/kubernetes#44085]
If I look at the code of azureFile plugin, it has _fsGroup_ as an argument, but don't see its usage anywhere
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_file/azure_file.go#L196

I also don't see anywhere explicitely stated that azureFile volume supports fsGroup.

**Comment by dadicool** [comment]
For those landing here, a separate path to get the mount point to have the right permissions is to add this annotation to the PV metadata: 

```
annotations:
  # Set the uid,gid to be used to mount the volume
  volume.beta.kubernetes.io/mount-options: "uid=UID,gid=GID"
```

This makes the plugin mount the volume in the Pod under those UID,GID. Obviously, this implies that one knows what those are for their workload in the container ...

**Comment by avaranovich** [comment]
@dadicool  If i create a PV like this, still mounted with the default root used into POD.

StorageClass
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  location: westeurope
  storageAccount: myaccount
```

PV

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  annotations:
    # Set the uid,gid to be used to mount the volume
    volume.beta.kubernetes.io/mount-options: "uid=1000,gid=100"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  azureFile:
    secretName: azure-secret
    shareName: jupyter
    readOnly: false
  claimRef:
    namespace: default
    name : az-files-01
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: az-files-01
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
    volume.beta.kubernetes.io/mount-options: "uid=1000,gid=100"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

**Comment by karataliu** [comment]
/remove-lifecycle stale

cc @andyzhangx  Let's check whether `volume.SetVolumeOwnership` works for azure file.

**Comment by andyzhangx** [comment]
`mountOptions` is another way to set groupid(gid)
While according to this [doc](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/), we also need to support `securityContext`
```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: gcr.io/google-samples/node-hello:1.0
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
```

Here is the code [reference](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L481) about setting fsgroup from securityContext.

I will enable this feature and do a test, it should be 3 lines of code.
/assign
