### ISSUE TITLE
kubernetes 1.6 use pod affinity/anti-affinity in deployment yaml  don't work,and use pod yaml is ok.

### ISSUE THREAD

**Issue by strugglingyouth** [kubernetes/kubernetes#44128]
**$ kubectl version**
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**$ etcdctl version**
etcdctl version: 3.1.3
API version: 3.1

I set six tor,each tor more than one machine, first create deployment distributed in the tor1 and tor6,and use label test-zk ,then use  follow yaml to create four pod,which uses the anti-affinity rule to label test-zk , but not in the remaining four tor, and some are still allocated in the tor1 and tor 6,I have tested many times that this rule does not take effect, But using pod yaml files one by one to create pod is correct,is my problem?

**pod yaml  as follow:**

```
apiVersion: v1
kind: Pod
metadata:
    name: with-pod-affinity-test22
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - test-zk
        topologyKey: tor
  containers:
  - name: with-pod-affinity
    image: zk.3.5.2:stable
    imagePullPolicy: IfNotPresent
```

**deployment yaml  as follow:**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: zk
spec:
  replicas: 4
  template:
    metadata:
      labels:
          app: zk
      annotations:
        affinity:  >
          {
            "podAntiAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": [
                {
                  "labelSelector": {
                    "matchExpressions": [
                      {
                        "key": "app",
                        "operator": "In",
                        "values": ["test-zk"]
                      }
                    ]
                  },
                  "topologyKey": "tor"
                }
              ]
             }
          }
    spec:
      containers:
      - name: zk
        image: zk.3.5.2:stable
        imagePullPolicy: IfNotPresent
```
