### ISSUE TITLE
Unable to use kubectl to manage cluster in terminal other than the one that runs "kubeadm init"

### ISSUE THREAD

**Issue by jzhu077** [kubernetes/kubernetes#44130]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
Yes and No (I cannot use Troubleshooting documentation in my case)

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
kubectl and Kubeadm init
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
v1.6.1

**Environment**: VM
- **Cloud provider or hardware configuration**: VM on local machine
- **OS** (e.g. from /etc/os-release): ubuntu 16.04LTS
- **Kernel** (e.g. `uname -a`):4.8.0-36-generic
- **Install tools**: virtualbox
- **Others**:
4GB of memory

**What happened**:
Unable to use kubectl in terminal other than the one that runs "kubeadm init". 

e.g. I setup my cluster using terminal tab 1 (everything works in that tab)
When I open a new terminal tab and try to run kubectl get pod or kubectl cluster-info
```
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**What you expected to happen**:
After I spin up my cluster I should be able to use kubectl to manage it from any terminal window inside my VM or ssh from host.

**How to reproduce it** (as minimally and precisely as possible):
Setup a VM that runs ubuntu 16.04 LTS and follow [https://kubernetes.io/docs/getting-started-guides/kubeadm/](url) step 1,2,3 for a single-node cluster. 
Open a new terminal tab or window and try to run ```kubectl get pods --all-namespaces```

**Anything else we need to know**:
```~/.kube/config``` does not exist
```kubectl config view``` in the working window (the one that runs kubeadm init) gives
```
 apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://192.168.178.61:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

```kubectl config view``` in other tabs/windows gives
```
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

I tried to manually set ```~/.kube/config ``` to the same as the configuration output in working window . Other tabs/windows are now able to see the same output from ```kubectl config view```, but when I run 
```kubectl get pods --all-namespaces``` it gives an error
```
error: tls: failed to find any PEM data in certificate input
```

Output of ```kubectl get pods --all-namespaces```  in the working window is 

```
kube-system   etcd-j-virtualbox                      1/1       Running            0          1h
kube-system   kube-apiserver-j-virtualbox            1/1       Running            0          1h
kube-system   kube-controller-manager-j-virtualbox   1/1       Running            1          1h
kube-system   kube-dns-3913472980-g9w6s              3/3       Running            0          1h
kube-system   kube-proxy-mrlkp                       1/1       Running            0          1h
kube-system   kube-scheduler-j-virtualbox            1/1       Running            1          1h
kube-system   weave-net-d9f4n                        2/2       Running            0          1h
```
