### ISSUE TITLE
PVC does not work correctly when deploy is installed on Azure ACS agent that runs Windows

### ISSUE THREAD

**Issue by minherz** [kubernetes/kubernetes#44146]
**What keywords did you search in Kubernetes issues before filing this one?** `windows` `azure`

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`): `Linux k8s-master-E95B113C-0 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: Azure portal
- **Others**: Configuration includes 1 master and 2 agents that run Windows (preview).

**What happened**: 
When installing a deployment that use volume from PVC the deployment fails. The K8S dashboard shows the following errors:
Node Details Events:
 `invalid capacity 0 on device "" at mount point ""`

ReplicaSet Events:
 `Failed to create docker container "windowswebserver" of pod "win-webserver-3479639405-r8tvb_default(2d9821b4-1abe-11e7-a9a9-000d3a14200c)" with error: Error response from daemon: {"message":"invalid bind mount spec \"c:/var/lib/kubelet/pods/2d9821b4-1abe-11e7-a9a9-000d3a14200c/volumes/kubernetes.io~azure-disk/pvc-e5f7a9ef-1abd-11e7-a9a9-000d3a14200c:c:/volume\": invalid volume specification: 'c:/var/lib/kubelet/pods/2d9821b4-1abe-11e7-a9a9-000d3a14200c/volumes/kubernetes.io~azure-disk/pvc-e5f7a9ef-1abd-11e7-a9a9-000d3a14200c:c:/volume': invalid mount config for type \"bind\": bind source path does not exist"}`

 `Error syncing pod, skipping: failed to "StartContainer" for "windowswebserver" with RunContainerError: "runContainer: Error response from daemon: {\"message\":\"invalid bind mount spec \\\"c:/var/lib/kubelet/pods/2d9821b4-1abe-11e7-a9a9-000d3a14200c/volumes/kubernetes.io~azure-disk/pvc-e5f7a9ef-1abd-11e7-a9a9-000d3a14200c:c:/volume\\\": invalid volume specification: 'c:/var/lib/kubelet/pods/2d9821b4-1abe-11e7-a9a9-000d3a14200c/volumes/kubernetes.io~azure-disk/pvc-e5f7a9ef-1abd-11e7-a9a9-000d3a14200c:c:/volume': invalid mount config for type \\\"bind\\\": bind source path does not exist\"}"`

Pod Created by Error:
 `Failed to create docker container "windowswebserver" of pod "win-webserver-3479639405-r8tvb_default(2d9821b4-1abe-11e7-a9a9-000d3a14200c)" with error: Error response from daemon: {"message":"invalid bind mount spec \"c:/var/lib/kubelet/pods/2d9821b4-1abe-11e7-a9a9-000d3a14200c/volumes/kubernetes.io~azure-disk/pvc-e5f7a9ef-1abd-11e7-a9a9-000d3a14200c:c:/volume\": invalid volume specification: 'c:/var/lib/kubelet/pods/2d9821b4-1abe-11e7-a9a9-000d3a14200c/volumes/kubernetes.io~azure-disk/pvc-e5f7a9ef-1abd-11e7-a9a9-000d3a14200c:c:/volume': invalid mount config for type \"bind\": bind source path does not exist"}
Error syncing pod, skipping: failed to "StartContainer" for "windowswebserver" with RunContainerError: "runContainer: Error response from daemon: {\"message\":\"invalid bind mount spec \\\"c:/var/lib/kubelet/pods/2d9821b4-1abe-11e7-a9a9-000d3a14200c/volumes/kubernetes.io~azure-disk/pvc-e5f7a9ef-1abd-11e7-a9a9-000d3a14200c:c:/volume\\\": invalid volume specification: 'c:/var/lib/kubelet/pods/2d9821b4-1abe-11e7-a9a9-000d3a14200c/volumes/kubernetes.io~azure-disk/pvc-e5f7a9ef-1abd-11e7-a9a9-000d3a14200c:c:/volume': invalid mount config for type \\\"bind\\\": bind source path does not exist\"}"`

**What you expected to happen**:
The deployment succeed

**How to reproduce it** (as minimally and precisely as possible):

1. Install azure storage class by executing
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: azure-slow
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: Standard_LRS
```
 2. Setup PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  annotations:
    volume.alpha.kubernetes.io/storage-class: azure-slow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```
3. Setup deployment (taken from Kubernetes on Windows example and updated just with a volume)
```
apiVersion: v1
kind: Service
metadata:
 name: win-webserver
 labels:
   app: win-webserver
spec:
 ports:
   # the port that this service should serve on
 - port: 80
   targetPort: 80
 selector:
   app: win-webserver
 type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 labels:
   app: win-webserver
 name: win-webserver
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app: win-webserver
     name: win-webserver
   spec:
     containers:
     - name: windowswebserver
       image: microsoft/windowsservercore
       command:
       - powershell.exe
       - -command
       - "<#code used from https://gist.github.com/wagnerandrade/5424431#> ; $$listener = New-Object System.Net.HttpListener; $$listener.Prefixes.Add('http://*:80/'); $$listener.Start() ; $$callerCounts = @{} ; Write-Host('Listening on port 80 at all interfaces{0}...') ; while ($$listener.IsListening) { ;$$context = $$listener.GetContext() ;$$requestUrl = $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;$$count = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f $$_,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer = [System.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close() ;$$responseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ; "
       volumeMounts:
       - mountPath: "c:/volume"
         name: blobdisk01
     volumes:
     - name: blobdisk01
       persistentVolumeClaim:
         claimName: pvc1
     nodeSelector:
       beta.kubernetes.io/os: windows
```

**Anything else we need to know**:
Do not assemble all above configurations into a single YAML file since it takes a time to Azure to execute the configuration which seems not happening when all configurations are deployed as a single file.
Give 0,5 - 1 minute delays between the scripts.

I had communicated the issue to Microsoft support and they turned me here and advised to engage @brendandburns on the matter.
