### ISSUE TITLE
VolumeMount for ConfigMap fails to be remounted - Nested mountPoints

### ISSUE THREAD

**Issue by shlompy** [kubernetes/kubernetes#44214]
Hi.

I'm keep getting "device or resource is busy" errors when kubernetes tries to re-mount volumes which are based on configMap.
I've seen several threads regarding volume mounting failures but they doesn't seem to be related to the failure I'm seeing.

I'm using Kubernetes v1.4.1

The error I'm seeing is for specific configMap 'hekad-common-config'

/var/log/messages is full of the following logs:
```
MountVolume operation started for volume "kubernetes.io/configmap/c4d620be-1ac3-11e7-a48d-fa163e70f679-hekad-common-config" (spec.Name: "hekad-common-config") to pod "c4d620be-1ac3-11e7-a48d-fa163e70f679" (UID: "c4d620be-1ac3-11e7-a48d-fa163e70f679"). Volume is already mounted to pod, but remount was requested.
pod lbeta/infrabridge-kube2consul-4287528991-obzn3 volume hekad-common-config: error pruning old user-visible path component: remove /var/lib/origin/openshift.local.volumes/pods/c4d620be-1ac3-11e7-a48d-fa163e70f679/volumes/kubernetes.io~configmap/hekad-common-config/component: device or resource busy
pod lbeta/infrabridge-kube2consul-4287528991-obzn3 volume hekad-common-config: error removing old visible symlinks: remove /var/lib/origin/openshift.local.volumes/pods/c4d620be-1ac3-11e7-a48d-fa163e70f679/volumes/kubernetes.io~configmap/hekad-common-config/component: device or resource busy                                                                                                                                                                                  
Error writing payload to dir: remove /var/lib/origin/openshift.local.volumes/pods/c4d620be-1ac3-11e7-a48d-fa163e70f679/volumes/kubernetes.io~configmap/hekad-common-config/component: device or resource busy                                                                      
Operation for "\"kubernetes.io/configmap/c4d620be-1ac3-11e7-a48d-fa163e70f679-hekad-common-config\" (\"c4d620be-1ac3-11e7-a48d-fa163e70f679\")" failed. No retries permitted until 2017-04-07 16:57:09.001834524 +0000 UTC (durationBeforeRetry 2m0s). Error: MountVolume.SetUp failed for volume "kubernetes.io/configmap/c4d620be-1ac3-11e7-a48d-fa163e70f679-hekad-common-config" (spec.Name: "hekad-common-config") pod "c4d620be-1ac3-11e7-a48d-fa163e70f679" (UID: "c4d620be-1ac3-11e7-a48d-fa163e70f679") with: remove /var/lib/origin/openshift.local.volumes/pods/c4d620be-1ac3-11e7-a48d-fa163e70f679/volumes/kubernetes.io~configmap/hekad-common-config/component: device or resource busy

```
And it just keeps re-trying re-mounting the volume every 2 minutes.

From what I’ve been able to understand, Kubernetes keeps re-mounting volumes which are based on ConfigMaps. (I guess this is to keep the mount content updated in case the configMap has been updated)
There are several volumes of configMaps which are set to pods, but I think I understand the reason specific failures are seen to hekad-common-config.

Note the it tries to re-mount the volume for hekad-common-config, which is mounted to /etc/heka-config.d
But the device is busy error is for hekad-common-config/component, which is from hekad-component-config configMap.

In the pod template:
```
      volumeMounts:
        - name: hekad-component-config
          mountPath: /etc/heka-config.d/component
        - name: hekad-common-config
          mountPath: /etc/heka-config.d

```
So my question here, could it be the root cause of the issue is that there are 2 VolumeMounts on the same path (Where one of them is in a sub-directory of another mountPath)

My only guess is that device busy errors for '/etc/heka-config.d' may happen if it has files within this path which are still in use by the system - In this case /etc/heka-config.d/component may be mounted and causing a failure when trying to un-mount /etc/heka-config.d.

If this is the cause, then I think Kubernetes should fail creation of such pods which have multiple volumes which are being mounted to the same base paths.

**Comment by neermitt** [comment]
I am also seeing similar issue, in my installation.

kubelet.log entry begins with this error
atomic_writer.go:444] pod mimir-test/mimir-np-master-2244465049-ki1d8 volume myConfig: error pruning old user-visible path policies: remove /var/lib/kubelet/pods/e5eb5c94-1b05-11e7-bda7-0025b500003f/volumes/kubernetes.io~configmap/myConfig/policies: device or resource busy

**Comment by chepurko** [comment]
I have the same deal with a similar setup. I have an `nginx` directory with `nginx/nginx-conf-d` and two other subdirectories inside. This seems to happen on and off but I'm not sure. Is there some order to the way ConfigMaps mount?

**Comment by chepurko** [comment]
Well, this was a real pain in the butt, but I basically had to make non-recursive directories in the pods in order to make this work. So the `volumeMounts` section in my Deployment looks like this now:

```yaml
volumeMounts:
        - name: wp-persistent-storage
          mountPath: /var/www/html
        - name: nginx
          mountPath: /etc/nginx
        - name: nginx-conf-d
          mountPath: /etc/nginx-conf/conf.d
        - name: nginx-global
          mountPath: /etc/nginx-conf/global
        - name: nginx-html
          mountPath: /etc/nginx-conf/html
```

You can't change the `/etc/nginx` directory because that's a built-in compilation flag to NGINX. So you have to put all the original NGINX subdirectories into a different directory under `/etc`. In this case, `/etc/nginx-conf`. 

On top of that, you also obviously have to go through all your NGINX configuration files and update your `include` directives to point to `/etc/nginx-conf`.

It's not ideal but I need this to work on my production LEMP stack running on Kube. ConfigMaps provide a more easy and modular way of injecting configurations than using Volumes.

Not sure if this inability to mount subdirectories inside mounted ConfigMap directories is a bug or the intended functionality.

**Comment by shlompy** [comment]
I've already done something similar byb using non-recursive directories for volumeMounts, then using a script in the container which copies all the relevant files from the mounts to the relevant destination.

Would have been nice if K8s will fail such pod when trying to create it, as nested volumeMounts can easily be identified as part of the values in the .yaml file.

**Comment by chepurko** [comment]
I haven't done comprehensive testing, so this is basically just assumption, but I _may_ have started experiencing this after upgrading my cluster to Kube Server v1.6. What version is everyone using here?

I'm on:
```bash
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by shlompy** [comment]
I'm on v1.4.1

I think the mount errors are pretty clear (device or resource busy). The mount cannot be unmounted if there are files inside it which are still being used by the system (In that case - the nested mount is still mounted when it tries to mount the parent path).

Usually in such cases, a user can force unmount, but that might not be healthy and I'm not expecting such a fix.
Technically, if a user sets nested mount points without knowing the consequences, the only proper fix I can think of is modifying K8s to fail such pod creation if there is no way around that. (I don't think remount can be disabled for specific pods, so such remount errors will probably be reproducible on every version)

**Comment by yadzhang** [comment]
I have met the same problem. I have a configmap named specail-config, which have 3 configamp items : HELLO, game-config, yad-asa.
And I mount configmap items to pod like this:
```
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: HELLO
            path: HELLO
          - key: game-config
            path: game-config
          name: special-config
        name: configmap-volume-0
      - configMap:
          defaultMode: 420
          items:
          - key: yad-asa
            path: yad-asa
          name: special-config
        name: configmap-volume-1
```
VolumeMounts like this:
```
 volumeMounts:
        - mountPath: /etc/config
          name: configmap-volume-0
        - mountPath: /etc/config/yad-asa
          name: configmap-volume-1
          subPath: yad-asa

```

Warningreport like this：
`
MountVolume.SetUp failed for volume "kubernetes.io/configmap/06aa9c83-467b-11e7-8b07-54899875df6a-configmap-volume-0" (spec.Name: "configmap-volume-0") pod "06aa9c83-467b-11e7-8b07-54899875df6a" (UID: "06aa9c83-467b-11e7-8b07-54899875df6a") with: remove /var/lib/kubelet/pods/06aa9c83-467b-11e7-8b07-54899875df6a/volumes/kubernetes.io~configmap/configmap-volume-0/yad-asa: device or resource busy`

Volume configmap-volume-0 does not have item " yad-asa", why report this warning?
