### ISSUE TITLE
why not divide requiredDuringSchedulingIgnoredDuringExecution into 2 items

### ISSUE THREAD

**Issue by dove-young** [kubernetes/kubernetes#44259]
**Kubernetes version** (use `kubectl version`):
1.6

As mentioned in this blog, http://blog.kubernetes.io/2017/03/advanced-scheduling-in-kubernetes.html, 

```
 affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
        - matchExpressions:
          - key: "failure-domain.beta.kubernetes.io/zone"
            operator: In
            values: ["us-central1-a"]
```

_“IgnoredDuringExecution” means that the pod will still run if labels on a node change and affinity rules are no longer met. There are future plans to offer requiredDuringSchedulingRequiredDuringExecution which will evict pods from nodes as soon as they don’t satisfy the node affinity rule(s)._

Don't you think the item key **requiredDuringSchedulingIgnoredDuringExecution** is awkful? And since you are going to add another similar item **requiredDuringSchedulingRequiredDuringExecution** in near future, why not to divide them into 2 Boolean items?

For example, divide **requiredDuringSchedulingIgnoredDuringExecution**  into this way

```
  affinity:
    nodeAffinity:

        nodeSelectorTerms:
          requiredDuringScheduling: true
          requiredDuringExecution: false
          - matchExpressions:
              - key: "failure-domain.beta.kubernetes.io/zone"
                operator: In
                values: ["us-central1-a"]
```

And divide **requiredDuringSchedulingRequiredDuringExecution** into this way

```
  affinity:
    nodeAffinity:

        nodeSelectorTerms:
          requiredDuringScheduling: true
          requiredDuringExecution: true
          - matchExpressions:
              - key: "failure-domain.beta.kubernetes.io/zone"
                operator: In
                values: ["us-central1-a"]
```
