### ISSUE TITLE
Critical pod does not work

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#44265]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1004+a7c805b28f650e-dirty", GitCommit:"a7c805b28f650e66bc06b65c8b3588f73ca0a8ff", GitTreeState:"dirty", BuildDate:"2017-03-09T06:09:42Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.1.195+eed7d11255032e", GitCommit:"eed7d11255032ee3b56cf43596e37cc29ff35d16", GitTreeState:"clean", BuildDate:"2017-04-10T02:16:59Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

1) Three nodes with k8s001 as master node and also have `rescheduler` running on master node.
```
root@k8s001:/var/log# kubectl get nodes --show-labels
NAME      STATUS    AGE       VERSION                              LABELS
k8s001    Ready     4d        v1.7.0-alpha.0.2091+0f10d6ccf297ff   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=k8s001,role=master
k8s003    Ready     3d        v1.7.0-alpha.1.195+eed7d11255032e    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=k8s003,role=ko
k8s004    Ready     4d        v1.7.0-alpha.1.195+eed7d11255032e    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=k8s004,role=ok
```

```
root@k8s001:/var/log# kubectl get pods --namespace=kube-system -owide | grep resch
rescheduler-v0.3.0                          1/1       Running   0          23m       192.168.56.11     k8s001
```

2) Create a deployment to consume up all of the resources on k8s004
```
apiVersion: v1
kind: Service
metadata:
  labels:
    run: k8s004-nginx
  name: k8s004-nginx
  namespace: kube-system
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: k8s004-nginx
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: k8s004-nginx
  name: k8s004-nginx
  namespace: kube-system
spec:
  replicas: 5
  selector:
    matchLabels:
      run: k8s004-nginx
  template:
    metadata:
      labels:
        run: k8s004-nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - ok
      containers:
      - image: nginx:1.8.1
        imagePullPolicy: IfNotPresent
        name: k8s004-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 32Mi
```

```
root@k8s001:/var/log# kubectl get pods --namespace=kube-system -owide
NAME                                        READY     STATUS    RESTARTS   AGE       IP                NODE
calico-policy-controller-2003006622-q475h   1/1       Running   0          7h        192.168.56.11     k8s001
k8s004-nginx-546842239-80vh3                1/1       Running   0          20m       192.168.124.132   k8s004
k8s004-nginx-546842239-clmq4                1/1       Running   0          20m       192.168.124.130   k8s004
k8s004-nginx-546842239-f87sr                1/1       Running   0          20m       192.168.124.131   k8s004
k8s004-nginx-546842239-sm1n5                1/1       Running   0          20m       192.168.124.129   k8s004
k8s004-nginx-546842239-wn810                0/1       Pending   0          1h        <none>
kube-dns-v20-886799370-563p7                3/3       Running   0          7h        192.168.191.10    k8s001
rescheduler-v0.3.0                          1/1       Running   0          22m       192.168.56.11     k8s001
```

3) Create a critical pod on k8s004
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: k8s004-critical-pod
  name: k8s004-critical-pod
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      run: k8s004-critical-pod
  template:
    metadata:
      labels:
        run: k8s004-critical-pod
    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - ok
      containers:
      - image: nginx:1.8.1
        imagePullPolicy: IfNotPresent
        name: k8s004-critical-pod
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 32Mi
```

**What happened**:
After 3), the critical pod keeps pending.
```
root@k8s001:/var/log# kubectl get pods --namespace=kube-system -owide | grep critical
k8s004-critical-pod-1462853210-xl948        0/1       Pending   0          23m       <none>
```
The scheduler keeps reporting
```
E0410 17:59:11.863627   19748 factory.go:520] Error scheduling kube-system k8s004-critical-pod-1462853210-xl948: No nodes are available that match all of the following predicates:: Insufficient cpu (1), MatchNodeSelector (2).; retrying
I0410 17:59:11.863671   19748 factory.go:597] Updating pod condition for kube-system/k8s004-critical-pod-1462853210-xl948 to (PodScheduled==False)
I0410 17:59:11.863892   19748 event.go:217] Event(v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"k8s004-critical-pod-1462853210-xl948", UID:"dff0030d-1dd0-11e7-9b30-08002759511a", APIVersion:"v1", ResourceVersion:"166037", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' No nodes are available that match all of the following predicates:: Insufficient cpu (1), MatchNodeSelector (2).
```
**What you expected to happen**:
After 3), the critical pod should be able to trigger eviction of some pods and finally the critical pods can start up.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by piosz** [comment]
@gyliu513 can you show logs from rescheduler?

**Comment by gyliu513** [comment]
@piosz it is strange that there is no log in rescheduler, do you have any comments for how to debug this?

**Comment by gyliu513** [comment]
@piosz 

No log for rescheduler.
```
root@k8s001:/var/log# ls -l rescheduler.log
-rwxrwxrwx 1 root root 0 Apr 10 17:01 rescheduler.log
root@k8s001:/var/log#
```

The critical pod keeps pending.
```
root@k8s001:~# kubectl get pods --namespace=kube-system -owide
NAME                                        READY     STATUS    RESTARTS   AGE       IP                NODE
calico-policy-controller-2003006622-q475h   1/1       Running   1          10h       192.168.56.11     k8s001
k8s004-critical-pod-1462853210-bpt7d        0/1       Pending   0          21s       <none>
k8s004-nginx-546842239-0w220                0/1       Pending   0          1h        <none>
k8s004-nginx-546842239-1f6rx                1/1       Running   0          2h        192.168.124.143   k8s004
k8s004-nginx-546842239-81n3w                1/1       Running   0          1h        192.168.124.139   k8s004
k8s004-nginx-546842239-lz5n2                1/1       Running   0          1h        192.168.124.136   k8s004
k8s004-nginx-546842239-n1n5b                1/1       Running   0          1h        192.168.124.137   k8s004
kube-dns-v20-886799370-563p7                3/3       Running   3          10h       192.168.191.11    k8s001
rescheduler-v0.3.0                          1/1       Running   1          2h        192.168.56.11     k8s001
```

Critical pod event
```
root@k8s001:~# kubectl describe pods k8s004-critical-pod-1462853210-bpt7d --namespace=kube-system
Name:		k8s004-critical-pod-1462853210-bpt7d
Namespace:	kube-system
Node:		/
Labels:		pod-template-hash=1462853210
		run=k8s004-critical-pod
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"k8s004-critical-pod-1462853210","uid":"eedcf878-1dd5-11e7-9b...
Status:		Pending
IP:
Controllers:	ReplicaSet/k8s004-critical-pod-1462853210
Containers:
  k8s004-critical-pod:
    Image:	nginx:1.8.1
    Port:	80/TCP
    Requests:
      cpu:		1
      memory:		32Mi
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wwjst (ro)
Conditions:
  Type		Status
  PodScheduled 	False
Volumes:
  default-token-wwjst:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-wwjst
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	CriticalAddonsOnly=:Exists
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  2m		57s		8	default-scheduler			Warning		FailedScheduling	No nodes are available that match all of the following predicates:: Insufficient cpu (1), MatchNodeSelector (1).
```

**Comment by piosz** [comment]
Ups, that's bad. Can you please ssh to rescheduler and its logs should be in /tmp directory.

Also Rescheduler is triggered by pods with condition [PodReasonUnschedulable](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1921) which seems to be not set here.

cc @davidopp

**Comment by piosz** [comment]
@gyliu513 can you please show result of the following command:
```
 kubectl get pods k8s004-critical-pod-1462853210-bpt7d --namespace=kube-system -o yaml
```

**Comment by gyliu513** [comment]
@piosz 

```
root@k8s001:~# kubectl get pods k8s004-critical-pod-1462853210-bpt7d --namespace=kube-system -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"k8s004-critical-pod-1462853210","uid":"eedcf878-1dd5-11e7-9b30-08002759511a","apiVersion":"extensions","resourceVersion":"171623"}}
  creationTimestamp: 2017-04-10T12:21:41Z
  generateName: k8s004-critical-pod-1462853210-
  labels:
    pod-template-hash: "1462853210"
    run: k8s004-critical-pod
  name: k8s004-critical-pod-1462853210-bpt7d
  namespace: kube-system
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: k8s004-critical-pod-1462853210
    uid: eedcf878-1dd5-11e7-9b30-08002759511a
  resourceVersion: "172271"
  selfLink: /api/v1/namespaces/kube-system/pods/k8s004-critical-pod-1462853210-bpt7d
  uid: 41079e46-1de8-11e7-adaa-08002759511a
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - ok
  containers:
  - image: nginx:1.8.1
    imagePullPolicy: IfNotPresent
    name: k8s004-critical-pod
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: "1"
        memory: 32Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wwjst
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  volumes:
  - name: default-token-wwjst
    secret:
      defaultMode: 420
      secretName: default-token-wwjst
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-04-10T12:21:41Z
    message: 'No nodes are available that match all of the following predicates::
      Insufficient cpu (1), MatchNodeSelector (1).'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

**Comment by gyliu513** [comment]
@piosz This is the log message for rescheduler.

```
Log file created at: 2017/04/10 12:16:36
Running on machine: k8s001
Binary: Built with gc go1.7.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0410 12:16:36.448917       6 rescheduler.go:88] Running Rescheduler
I0410 12:18:36.460192       6 rescheduler.go:231] Removing all annotation taints because they are no longer supported.
```

**Comment by piosz** [comment]
I can't see critical annotation in your pod:
```
annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"k8s004-critical-pod-1462853210","uid":"eedcf878-1dd5-11e7-9b30-08002759511a","apiVersion":"extensions","resourceVersion":"171623"}}
 ```
It should be defined in pod template rather than for the deployment itself. See (heapster-controller.yaml)[https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/google/heapster-controller.yaml] for reference

**Comment by gyliu513** [comment]
Ah, my bad, I was adding the `critical annotation` in `Deployment metadata`, after switch to `podSpec`, it is working well! Thanks again for @piosz 

```
root@k8s001:~/cases/priority# cat critical-pod.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: k8s004-critical-pod
  name: k8s004-critical-pod
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: k8s004-critical-pod
  template:
    metadata:
      labels:
        run: k8s004-critical-pod
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - ok
      containers:
      - image: nginx:1.8.1
        imagePullPolicy: IfNotPresent
        name: k8s004-critical-pod
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 32Mi
```
