### ISSUE TITLE
Kubectl logs -f keeps blocking even when tailed pod stops since 1.6 upgrade

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#44340]
**BUG REPORT**

In order to tail logs from pods generated by a job until completion I run the following command:

`kubectl logs podname -f`

This automatically stopped tailing when the pod stopped. Since upgrading our GKE server this hangs indefinitely. It's something on the cluster side, because using the same 1.6.0 version of kubectl against a 1.5.6 GKE cluster stops as soon as the job is done.

**Kubernetes version**

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5
", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5
", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment:**

```
clusterIpv4Cidr: 10.248.0.0/14
createTime: '2016-11-14T19:26:49+00:00'
currentMasterVersion: 1.6.0
currentNodeCount: 14
currentNodeVersion: 1.6.0
endpoint: **REDACTED**
initialClusterVersion: 1.4.5
instanceGroupUrls:
- **REDACTED**
locations:
- europe-west1-c
loggingService: logging.googleapis.com
masterAuth:
  clientCertificate: **REDACTED**
  clientKey: **REDACTED**
  clusterCaCertificate: **REDACTED**
  password: **REDACTED**
  username: **REDACTED**
monitoringService: monitoring.googleapis.com
name: development-europe-west1-c
network: development
nodeConfig:
  diskSizeGb: 250
  imageType: COS
  machineType: n1-highmem-8
  oauthScopes:
  - https://www.googleapis.com/auth/compute
  - https://www.googleapis.com/auth/devstorage.read_only
  - https://www.googleapis.com/auth/service.management
  - https://www.googleapis.com/auth/servicecontrol
  - https://www.googleapis.com/auth/logging.write
  - https://www.googleapis.com/auth/monitoring
  serviceAccount: default
nodeIpv4CidrSize: 24
```

**What happened**:

`kubectl logs podname -f` keeps blocking even after the pod has stopped. For tailing a job from a build pipeline this is particularly inconvenient.

**What you expected to happen**:

The command to finish as soon as the pod terminates.

**How to reproduce it** (as minimally and precisely as possible):

- start a job in a GKE 1.6.0 cluster that runs long enough to tail the pod
- find the pod belonging to the job
- run `kubectl logs -f <pod name>`
- wait or the pod to stop and verify the kubectl command still blocks
