### ISSUE TITLE
mounted /var/log file link is visible but not accessible

### ISSUE THREAD

**Issue by gajus** [kubernetes/kubernetes#44355]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

* var log
* symlink
* "No such file or directory"

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:

GKE

**What happened**:

```
root@filebeat-640t9:/# ll /var/log/containers/proxy-gateway-1156926256-w4k8c_default_forward-proxy-3ba13fed97b9ff5d08aeaf754485c763bdea42673726711c3b33e5fb3d3b6a4d.log
lrwxrwxrwx 1 root root 70 Apr 11 18:15 /var/log/containers/proxy-gateway-1156926256-w4k8c_default_forward-proxy-3ba13fed97b9ff5d08aeaf754485c763bdea42673726711c3b33e5fb3d3b6a4d.log -> /var/log/pods/b9f53c9f-1ee2-11e7-bef7-42010af00197/forward-proxy_0.log
root@filebeat-640t9:/# tail /var/log/containers/proxy-gateway-1156926256-w4k8c_default_forward-proxy-3ba13fed97b9ff5d08aeaf754485c763bdea42673726711c3b33e5fb3d3b6a4d.log
tail: cannot open '/var/log/containers/proxy-gateway-1156926256-w4k8c_default_forward-proxy-3ba13fed97b9ff5d08aeaf754485c763bdea42673726711c3b33e5fb3d3b6a4d.log' for reading: No such file or directory
```

**What you expected to happen**:

I expected to be able to read the file.

**How to reproduce it** (as minimally and precisely as possible):

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: efk
  labels:
    app: filebeat
spec:
  template:
    metadata:
      labels:
        app: filebeat
      name: filebeat
    spec:
      containers:
      - name: filebeat
        image: apsops/filebeat-kubernetes:v0.3
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
        env:
          - name: LOGSTASH_HOSTS
            value: logstash:5000
          - name: LOG_LEVEL
            value: info
        volumeMounts:
        - name: varlog
          mountPath: /var/log/containers
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/containers
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```

**Anything else we need to know**:

This is required to make filebeat/ fluentd work.
