### ISSUE TITLE
[Deployment]pause a fail deployment will cause the running pod disappear when maxUnavailable=replicas-1

### ISSUE THREAD

**Issue by wanghaoran1988** [kubernetes/kubernetes#44436]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1902+7543bac56342fd", GitCommit:"7543bac56342fddaaadcfe555ad500a19dabf611", GitTreeState:"clean", BuildDate:"2017-04-13T08:50:28Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.1902+7543bac56342fd", GitCommit:"7543bac56342fddaaadcfe555ad500a19dabf611", GitTreeState:"clean", BuildDate:"2017-04-13T08:50:28Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
pause a fail deployment will cause the running pod disappear when maxUnavailable=replicas-1

**What you expected to happen**:
The only running pod should keep running

**How to reproduce it** (as minimally and precisely as possible):
1. Create a deployment with two replicas, maxSurge=1, maxUnavailabe=1
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-openshift
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift
        ports:
        - containerPort: 80
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
```
2. Update the image to a not exist image
cluster/kubectl.sh set image deployment/hello-openshift hello-openshift=openshift/noexist
```
➜  kubernetes git:(master) ✗ cluster/kubectl.sh get rs                  
NAME                         DESIRED   CURRENT   READY     AGE
hello-openshift-2382698553   1         1         1         1h
hello-openshift-4118353202   2         2         0         1h
➜  kubernetes git:(master) ✗ cluster/kubectl.sh get pod
NAME                               READY     STATUS             RESTARTS   AGE
hello-openshift-2382698553-w7zsl   1/1       Running            0          1h
hello-openshift-4118353202-71qjn   0/1       ImagePullBackOff   0          1h
hello-openshift-4118353202-81tqn   0/1       ImagePullBackOff   0          1h

```
3. pause the deployment
```
cluster/kubectl.sh rollout pause deployment/hello-openshift
deployment "hello-openshift" paused
➜  kubernetes git:(master) ✗ cluster/kubectl.sh get pod                                 
NAME                               READY     STATUS             RESTARTS   AGE
hello-openshift-2382698553-w7zsl   0/1       Terminating        0          1h
hello-openshift-4118353202-71qjn   0/1       ImagePullBackOff   0          1h
hello-openshift-4118353202-81tqn   0/1       ImagePullBackOff   0          1h
cluster/kubectl.sh get rs 
NAME                         DESIRED   CURRENT   READY     AGE
hello-openshift-2382698553   0         0         0         1h
hello-openshift-4118353202   2         2         0         1h
```
