### ISSUE TITLE
fluentd-elasticsearch addon: Upgrade the elasticsearch-logging ReplicationController to a Deployment

### ISSUE THREAD

**Issue by everett-toews** [kubernetes/kubernetes#44454]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**What happened**:

Currently the elasticsearch-logging controller of the fluentd-elasticsearch addon uses a `ReplicationController` for deployment. See https://github.com/kubernetes/kubernetes/blob/85378ad34fc5cd33aceb2ee0a4d7c1772ad2a816/cluster/addons/fluentd-elasticsearch/es-controller.yaml#L2

**What you expected to happen**:

[Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) are the next-generation `ReplicationController` and I'd expect the elasticsearch-logging controller would want to make use of these.

**Comment by everett-toews** [comment]
I took a quick stab at this using the following manifest for the `es-controller.yaml`

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-logging-v1
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
    spec:
      containers:
      - image: gcr.io/google_containers/elasticsearch:v2.4.1-2
        name: elasticsearch-logging
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: es-persistent-storage
        emptyDir: {}
```

However when I did a `kubectl apply -f es-controller.yaml` I get the following error in the elasticsearch-logging-v1 pod.

```
[elasticsearch-logging-v1-1371606566-t7jxl] [2017-04-13 15:40:08,394][WARN ][discovery.zen.ping.unicast] [elasticsearch-logging-v1-1371606566-t7jxl] failed to send ping to [{#zen_unicast_1#}{127.0.0.1}{127.0.0.1:9300}]
[elasticsearch-logging-v1-1371606566-t7jxl] SendRequestTransportException[[][127.0.0.1:9300][internal:discovery/zen/unicast]]; nested: NodeNotConnectedException[[][127.0.0.1:9300] Node not connected];
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:340)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPingRequestToNode(UnicastZenPing.java:440)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:426)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.ping(UnicastZenPing.java:240)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.discovery.zen.ping.ZenPingService.ping(ZenPingService.java:106)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.discovery.zen.ping.ZenPingService.pingAndWait(ZenPingService.java:84)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:945)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:360)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.discovery.zen.ZenDiscovery.access$4400(ZenDiscovery.java:96)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1296)
[elasticsearch-logging-v1-1371606566-t7jxl] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[elasticsearch-logging-v1-1371606566-t7jxl] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[elasticsearch-logging-v1-1371606566-t7jxl] at java.lang.Thread.run(Thread.java:745)
[elasticsearch-logging-v1-1371606566-t7jxl] Caused by: NodeNotConnectedException[[][127.0.0.1:9300] Node not connected]
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.transport.netty.NettyTransport.nodeChannel(NettyTransport.java:1141)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.transport.netty.NettyTransport.sendRequest(NettyTransport.java:830)
[elasticsearch-logging-v1-1371606566-t7jxl] at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:329)
[elasticsearch-logging-v1-1371606566-t7jxl] ... 12 more
```

A little bit of diagnostic info

```
$ kubectl exec elasticsearch-logging-v1-1371606566-rkh6g -it -n kube-system -- bash
root@elasticsearch-logging-v1-1371606566-rkh6g:/# curl http://localhost:9200/_cluster/health?pretty=true
{
  "error" : {
    "root_cause" : [ {
      "type" : "master_not_discovered_exception",
      "reason" : null
    } ],
    "type" : "master_not_discovered_exception",
    "reason" : null
  },
  "status" : 503
}
```

It _seems_ to be related to how ElasticSearch discovers its master nodes on port 9300 not playing well with a `Deployment`.

At this point I don't have any good ideas on why this would work for a `ReplicationController` vs a `Deployment`.
