### ISSUE TITLE
Using 'generateName' with Jobs

### ISSUE THREAD

**Issue by ankon** [kubernetes/kubernetes#44501]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 'job generateName' (also checked via google.com)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`):
~~~~
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-04-07T20:43:50Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
~~~~

**Environment**:
- **Cloud provider or hardware configuration**: minikube 0.18.0 on Linux
- **Install tools**: kubectl

**What happened**:

I'm trying to create a Job resource with a auto-generated name:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: tool-job-
spec:
  template:
    spec:
      containers:
      - name: tool
        image: "busybox"
        command:
        - sh
        args:
        - -c
        - echo "hello, world"
      restartPolicy: OnFailure
```

Applying this with kubectl gives:
~~~~
$ kubectl apply -f job-template.yml 
error: error when retrieving current configuration of:
&{0xc420a1fa40 0xc4202871f0 development  job-template.yml 0xc420497f20 0xc420497f20  false}
from server for: "job-template.yml": resource name may not be empty
~~~~

Adding metadata.name makes the job work, but obviously now with a fixed name.

**What you expected to happen**:
A job with the name 'tool-job-SOMETHING' is created, and a pod tool-job-SOMETHING-ELSE is used to execute the job.

**How to reproduce it** (as minimally and precisely as possible):
`kubectl apply -f job-template.yml`
