### ISSUE TITLE
New pods fail when scaling up or redeploying deployment while service is running 

### ISSUE THREAD

**Issue by studyingMole** [kubernetes/kubernetes#44559]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report (I think) ... if it's not a bug then It would be a nice feature!

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GKE and Minikube 0.18.0 (Windows 10, VirtualBox 5.1.18)
- **OS** (e.g. from /etc/os-release): Container-Optimized OS from Google, Windows 10 for Minikube
- **Kernel** (e.g. `uname -a`): 4.4.21+ (on GKE node)
- **Install tools**:
- **Others**:

**What happened**:
I created a deployment from a config file, then created the corresponding service. This part works fine. When I patch the deployment to use a new image, or when scaling up the deployment, the patched or new pods fail to start due to a port error (or at least appears to look like a port error). The deployments have a single Node.js 6.9.2 based container which throws "Error: listen EACCES tcp://10.0.0.114:5600".

This happens on both GKE and Minikube.

If I delete the service, then try to patch or scale the deployment, then I don't get the any issues with the pods. That means I need to create another service though.

**What you expected to happen**:
Patching or scaling up the deployment creates pods normally, without needing to delete the deployment's service first.

**How to reproduce it** (as minimally and precisely as possible):
Create deployment, then create service, then attempt to scale the deployment. The new pods in the deployment will fail to start.

**Anything else we need to know**:
***Deployment Config:***
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: asia.gcr.io/substiteach-development/user:latest
          ports:
          - containerPort: 5600
      imagePullSecrets:
        - name: gcr-pull
```
***Service Config:***
```
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  ports:
  - port: 5600
    targetPort: 5600
  selector:
    app: user
```

**Comment by kargakis** [comment]
Services need to exist prior to their pods, can you try creating the service first, then the deployment, and see if you get the same error back?

**Comment by studyingMole** [comment]
I tried spinning up a new cluster on GKE, creating the service first, then creating the deployment, and the same error occurs.

If I delete the service, then try to scale the deployment, all the pods are able to start properly, even the pod that originally failed, restarts and begins working correctly.

**Comment by kargakis** [comment]
@kubernetes/sig-network-bugs

**Comment by studyingMole** [comment]
Well, I got the deployment pods to start after starting the service first ... turns out the cluster didn't like something being called "user".

I changed the service name from "user" to "user-service", and deployment label from "app: user" to "app: user-svc", and updated the selector on the service to match:

```
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
  - port: 5600
    targetPort: 5600
  selector:
    app: user-svc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
        - name: user
          image: asia.gcr.io/substiteach-development/user:latest
          ports:
          - containerPort: 5600
      imagePullSecrets:
        - name: gcr-pull
```
Now services and deployments are working, I was also able to put all the config into a single yaml file.
