### ISSUE TITLE
Downward API does not support gpu resource

### ISSUE THREAD

**Issue by Yancey0623** [kubernetes/kubernetes#44552]
I can not fetch the GPU limit resource by downward API using YAML like :
```yaml
          valueFrom:
            resourceFieldRef:
              resource: limits.alpha.kubernetes.io/nvidia-gpu
```

The errror message:
```yaml
The Job "gpu-job" is invalid: spec.template.spec.containers[0].env[4].valueFrom.resourceFieldRef.resource: Unsupported value: "limits.alpha.kubernetes.io/nvidia-gpu": supported values: limits.cpu, limits.memory, requests.cpu, requests.memory
```
