### ISSUE TITLE
initContainer - image not updated?

### ISSUE THREAD

**Issue by gytisgreitai** [kubernetes/kubernetes#44676]
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?**

- initContainers

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT 

**Kubernetes version** :

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE

**What happened**:

Initial template `b2b.yaml`:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: b2b-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: b2b
    spec:
      initContainers:
        - name: b2b-liquibase
          image: eu.gcr.io/project/b2b-liquibase:master-3
          imagePullPolicy: Always
          <...>
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        <...>
      - name: b2b
        image: eu.gcr.io/project/b2b:master-3
        imagePullPolicy: Always
        <...>
```

after doing `kubectl -n dev apply -f b2b.yaml`:

```
$ kubectl -n dev describe deployment b2b-deployment
Name:			b2b-deployment
Namespace:		dev
CreationTimestamp:	Wed, 19 Apr 2017 20:25:23 +0300
Labels:			name=b2b
Annotations:		deployment.kubernetes.io/revision=1
			kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"b2b-deployment","namespace":"dev"},"spec":{"replicas":1,"te...
Selector:		name=b2b
Replicas:		1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
Pod Template:
  Labels:	name=b2b
  Init Containers:
   b2b-liquibase:
    Image:	eu.gcr.io/porject/b2b-liquibase:master-3
    <...>
  Containers:
   cloudsql-proxy:
    Image:	gcr.io/cloudsql-docker/gce-proxy:1.09
    <...>
   b2b:
    Image:	eu.gcr.io/tripcreatorcom/b2b:master-3
    <...>
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	True	MinimumReplicasAvailable
OldReplicaSets:	b2b-deployment-3574832072 (1/1 replicas created)
NewReplicaSet:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  18s		18s		1	deployment-controller			Normal		ScalingReplicaSet	Scaled up replica set b2b-deployment-3574832072 to 1
```

Now lets update both the `initContainer` and `container` image tag, so that `b2b.yaml` would look like this:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: b2b-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: b2b
    spec:
      initContainers:
        - name: b2b-liquibase
          image: eu.gcr.io/tripcreatorcom/b2b-liquibase:master-52-768e8feb8
          imagePullPolicy: Always
          <...>
      containers:
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.09
        <...>
      - name: b2b
        image: eu.gcr.io/tripcreatorcom/b2b:master-52-768e8feb8
        imagePullPolicy: Always
       <...>
```
And lets check our deployment:

```
$ kubectl -n dev describe deployment b2b-deployment
Name:			b2b-deployment
Namespace:		dev
CreationTimestamp:	Wed, 19 Apr 2017 20:25:23 +0300
Labels:			name=b2b
Annotations:		deployment.kubernetes.io/revision=2
			kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"b2b-deployment","namespace":"dev"},"spec":{"replicas":1,"te...
Selector:		name=b2b
Replicas:		1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
Pod Template:
  Labels:	name=b2b
  Init Containers:
   b2b-liquibase:
    Image:	eu.gcr.io/project/b2b-liquibase:master-3
   <...>
  Containers:
   cloudsql-proxy:
    Image:	gcr.io/cloudsql-docker/gce-proxy:1.09
   <...>
   b2b:
    Image:	eu.gcr.io/project/b2b:master-52-768e8feb8
    <...>
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	True	MinimumReplicasAvailable
OldReplicaSets:	b2b-deployment-3370688208 (1/1 replicas created)
NewReplicaSet:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  12m		12m		1	deployment-controller			Normal		ScalingReplicaSet	Scaled up replica set b2b-deployment-3574832072 to 1
  11m		11m		1	deployment-controller			Normal		ScalingReplicaSet	Scaled up replica set b2b-deployment-3370688208 to 1
  11m		11m		1	deployment-controller			Normal		ScalingReplicaSet	Scaled down replica set b2b-deployment-3574832072 to 0
```
As you can see image for `b2b` has been updated to `master-52-768e8feb8` but for `initContainer` `b2b-liquibase` the image is still at `master-3`

[According to docs](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/):

> Changes to the Init Container spec are limited to the container image field. 

Or does this imply that image tag changes are ignored?

**What you expected to happen**:

`initContainer` `b2b-liquibase` tag should be `master-52-768e8feb8`
