### ISSUE TITLE
error validating data: found invalid field initContainers for v1.PodSpec

### ISSUE THREAD

**Issue by jeremywu0127** [kubernetes/kubernetes#44715]
I met the error like
```
root@ip-10-0-52-104:~/k8s-manifest# kubectl create -f !$
kubectl create -f /tmp/t.yml
error: error validating "/tmp/t.yml": error validating data: found invalid field initContainers for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
the file is 
```
root@ip-10-0-52-104:~/k8s-manifest# cat !$
cat /tmp/t.yml
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://kubernetes.io
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
```
my k8s version is like
```
root@ip-10-0-52-104:~/k8s-manifest# kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:54:20Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
