### ISSUE TITLE
secret mount:  Invalid specification: destination can't be '/'

### ISSUE THREAD

**Issue by hiscal2015** [kubernetes/kubernetes#44759]
I want to mount a secret value to /nginx.conf but failed with error "Invalid specification: destination can't be '/'", how can I do? Thanks for the help.

Kubernetes version: 1.5.4
here's part of deployment:

```
      - name: nginx-ldap-kibana
        volumeMounts:
          - name: secret-volume-nginx-ldap-globalconf
            mountPath: /

      volumes:
        - name: secret-volume-nginx-ldap-globalconf
          secret:
            secretName: kibana-secret
            items:
            - key: nginxglobalconf
              path: nginx.conf
              mode: 0644

```
