### ISSUE TITLE
Pod not removed from the API server after deletion with grace period

### ISSUE THREAD

**Issue by hasbro17** [kubernetes/kubernetes#44777]
**Problem Statement**:
The kubernetes [pod docs](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods) state:
```
Once the grace period has expired the KILL signal is sent to those processes and the pod is then deleted from the API server.
```
However deleting a pod with the `--grace-period` flag does not ensure it's removal from the API server within the specified time.

**Environment**:
- Kubernetes version : 1.6.1
- Cloud provider: GKE

**How to reproduce it**:

Run a sample pod like:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-server
    image: nginx
    ports:
    - containerPort: 80
```
```
$ kubectl create -f nginx-pod.yaml
```

Watch the pod
```
$ kubectl get pod nginx -w
```

Delete the pod with a grace period of 1 second:
```
$ kubectl delete pod nginx --grace-period=1
```

The watch output should show the pod status being returned by the API server even after 1 second has passed:
```
$ kubectl get pod nginx -w
NAME      READY     STATUS    RESTARTS   AGE
nginx     1/1       Running   0          2s
nginx     1/1       Terminating   0         11s
nginx     0/1       Terminating   0         11s
nginx     0/1       Terminating   0         14s
``` 

Periodically querying the pod via `kubectl get pod nginx -o yaml` while the pod is being terminated (from a different run) [shows](https://gist.github.com/hasbro17/9de253a461311085f5aa0d9583f15170) the API server repeatedly returning the pod spec after the grace period has expired.
