### ISSUE TITLE
Provide documentation for fluentd cluster addon RBAC

### ISSUE THREAD

**Issue by xrl** [kubernetes/kubernetes#44778]
**Kubernetes version** (use `kubectl version`): 1.6.1

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Kops ubuntu
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**: I was trying to rerun my fluentd YAMLs on a newly minted kops-managed cluster and my fluentd ds pods were flapping. Turns out they use a service account to scan for namespaces and pods. I spent some time figuring out what rules it needs and I want to have a discussion here for their suitability.

**What you expected to happen**: I expected things to blow up when upgrading.

**How to reproduce it** (as minimally and precisely as possible): Run the current fluentd YAMLs against a 1.6.1 cluster.

**Anything else we need to know**:

What do people think of this ClusterRole/ClusterRoleBinding config for enabling a fluentd daemonset?

```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: logs
  name: fluentd-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
---
# This role binding allows "system:serviceaccount:logs:default" to read pods in the "default" namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd-service-account
  namespace: logs
subjects:
- kind: ServiceAccount
  name: default
  namespace: logs
roleRef:
  kind: ClusterRole
  name: fluentd-role
  apiGroup: rbac.authorization.k8s.io
```
