### ISSUE TITLE
configmap file mount path results in command not found error

### ISSUE THREAD

**Issue by pmcgrath** [kubernetes/kubernetes#44815]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): command not found configmap kubernetes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):
Client Version: v1.6.1 GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e"
Server Version: v1.6.0 GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): host is ubuntu 16.04
- **Kernel** (e.g. `uname -a`): host is Linux dev1 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
- **Others**: Running from within minikube version: v0.18.0

**What happened**:
When I try to create a deployment with a configmap file that is mounted into the same directory as the entry point , the container fails to start with the following error
 "Error response from daemon: Container command '/app/app.sh' not found or does not exist."
The pod spec includes a configmap which is mounted into the same directory as the entrypoint 

Seems the entry point script is lost after mounting the volume for the config map in the same directory
If I mount the configmap file into a sub directory all works as expected

**What you expected to happen**:
I expected the config map file to be created in the directory without effecting the existing directory content which in this case contains an entrypoint script

**How to reproduce it** (as minimally and precisely as possible):

Docker file - note the entry point
```
FROM busybox:latest

RUN        mkdir /app
COPY       app.sh /app

ENTRYPOINT ["/app/app.sh"]
```

Entry point script - infinite loop
```
#!/bin/sh
seq=1
while [[ true ]]; do
	echo "${seq} $(date) working"
	sleep .5s	
	let seq=$((seq + 1))
done
```

k8s configmap and deployment file
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    product: k8s-demo
  name: demo
data:
  settings.json: |
    {
      "store": {
        "type": "InMemory",
    }

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    product: k8s-demo
  name: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
        product: k8s-demo
    spec:
      containers:
      - name: demo
        image: pmcgrath/shellloop:1
        imagePullPolicy: Always
        volumeMounts:
          - name: demo-config
            mountPath: /app
      volumes:
        - name: demo-config
          configMap:
            name: demo
            items:
              - key: settings.json
                path: settings.json 
```

When I run the kubectl apply -d k8s.yaml and look at the pod I can see the following error

rpc error: code = 2 desc = failed to start container "f9e0112c80ebba568d4b508f99ffb053bf1ae5a4f095ce7f45bff5f38900b617": Error response from daemon: Container command '/app/app.sh' not found or does not exist.

**Anything else we need to know**:
If I change the mountPath for the volume to any other directory it works as expected 

I did test this directly with docker on my host (17.03.0-ce) and it worked as expected 

```
touch settings.json
docker container run -ti -v $(pwd)/settings.json:/app/settings.json pmcgrath/shellloop:1
```

**Comment by zhouhaibing089** [comment]
@pmcgrath 

Checkout [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1237).

it seems I understand your issue. I have the same question before, but there is an answer actually in your situation.

To brief your case, you have a configmap(`settings.json: blahblah`), and want to mount into a folder `/app`. The below is what you need to know:

1.  Once you mount a volume(no matter it is configmap or others), it overrides the `mountPath`, so in your case, the `/app` folder will only contain `settings.json`.
1.  I know it is not what you expected, so you have to specify the `mountPath: /app/settings.json`, only that way, the original content in `/app` folders won't be affected.
1.  well, when you do the second step, you remember that configmap is actually a list of key-value pairs, you only need one of the keys(though you actually have only one as well), so you need to tell the volume mounts to use a subpath from you configmap.

This is something that you will get eventually:

```yaml
containers:
- volumeMounts:
  - name: demo-config
    mountPath: /app/settings.json
    subPath: settings.json
volumes:
- name: demo-config
  configMap:
    name: demo
```
