### ISSUE TITLE
Error volumeclaim is not bound, but it actually bound (rbd storageclass)

### ISSUE THREAD

**Issue by Dm3Ch** [kubernetes/kubernetes#44821]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
 volumeclaim is not bound

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
3 baremetal servers
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
`Linux Dm3Ch-Server-Node1 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
kubeadm
- **Others**:

**What happened**:
When I have created pod with volume claim I got:
```
  13m           13m             2       default-scheduler                               Warning         FailedScheduling        [SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "gitlab-data-pvc", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "gitlab-data-pvc", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "gitlab-data-pvc", which is unexpected.]
  13m           13m             1       default-scheduler                               Normal          Scheduled               Successfully assigned gitlab-deployment-1322383956-tw6b5 to dm3ch-server-node2
  13m           1m              14      kubelet, dm3ch-server-node2                     Warning         FailedMount             MountVolume.SetUp failed for volume "kubernetes.io/rbd/d204dcfd-2858-11e7-baad-0019996b57b2-pvc-d204edaf-2858-11e7-baad-0019996b57b2" (spec.Name: "pvc-d204edaf-2858-11e7-baad-0019996b57b2") pod "d204dcfd-2858-11e7-baad-0019996b57b2" (UID: "d204dcfd-2858-11e7-baad-0019996b57b2") with: rbd: image kubernetes-dynamic-pvc-d20e7600-2858-11e7-b9c0-0019996b57b2 is locked by other nodes
  11m           21s             6       kubelet, dm3ch-server-node2                     Warning         FailedMount             Unable to mount volumes for pod "gitlab-deployment-1322383956-tw6b5_gitlab(d204dcfd-2858-11e7-baad-0019996b57b2)": timeout expired waiting for volumes to attach/mount for pod "gitlab"/"gitlab-deployment-1322383956-tw6b5". list of unattached/unmounted volumes=[data]
  11m           21s             6       kubelet, dm3ch-server-node2                     Warning         FailedSync              Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "gitlab"/"gitlab-deployment-1322383956-tw6b5". list of unattached/unmounted volumes=[data]
```

PVC describe:
```
Name:           gitlab-data-pvc
Namespace:      gitlab
StorageClass:   rbd
Status:         Bound
Volume:         pvc-d204edaf-2858-11e7-baad-0019996b57b2
Labels:         <none>
Annotations:    pv.kubernetes.io/bind-completed=yes
                pv.kubernetes.io/bound-by-controller=yes
                volume.beta.kubernetes.io/storage-class=rbd
                volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Capacity:       10Gi
Access Modes:   RWO
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------   --------        ------                  -------
  14m           14m             1       persistentvolume-controller                     Normal          ProvisioningSucceeded   Successfully provisioned volume pvc-d204edaf-2858-11e7-baad-0019996b57b2 using kubernetes.io/rbd

```

**What you expected to happen**:
I expexted to got working pod with mounted volumeclaim

**How to reproduce it** (as minimally and precisely as possible):
My yaml files:

RBD storage class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rbd
provisioner: kubernetes.io/rbd
parameters:
    monitors: 10.31.0.1:6789, 10.31.0.2:6789, 10.31.0.3:6789
    adminId: admin
    adminSecretName: ceph-secret-admin
    adminSecretNamespace: "kube-system"
    pool: kubernetes
    userId: kubernetes
    userSecretName: ceph-secret
```

PVC: 
```kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-data-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "rbd"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

Deployment:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gitlab-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: gitlab
      labels:
        name: gitlab
    spec:
      containers:
      - name: gitlab
        image: sameersbn/gitlab:9.0.6
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: gitlab-data-pvc
```
**Anything else we need to know**:
I've got RBD storage class
