### ISSUE TITLE
k8s v1.6 GPU not isolated

### ISSUE THREAD

**Issue by weiwei04** [kubernetes/kubernetes#44834]
I use k8s v1.6 try to run some GPU workloads, my test yaml file request 1 GPU device, but in the container, I can see all 8 GPU devices.

**Kubernetes version** (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: bare metal with 8 Tesla K80 GPU Devices
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): 4.4.0-72-generic
- **Install tools**: kubeadm
- **Others**:

**What happened**:

my test yaml file

```
apiVersion: batch/v1
kind: Job
metadata:
  name: tf-gpu-test
  labels:
    name: tf-gpu-test
spec:
  template:
    metadata:
      labels:
        name: tf-gpu-test
    spec:
      containers:
      - name: tf-gpu-test
        image: tensorflow/tensorflow:1.1.0-devel-gpu-py3
        args:
        - sleep
        - "3600"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          requests:
            alpha.kubernetes.io/nvidia-gpu: 1
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia
          name: lib
          readOnly: true
      volumes:
      - name: lib
        hostPath:
          path: /var/lib/nvidia-docker/volumes/nvidia_driver/375.51
      restartPolicy: Never
```

**What you expected to happen**:

the docker inspect output was right, only 1 GPU device was mount into the container,

```
            "Devices": [
                {
                    "PathOnHost": "/dev/nvidia2",
                    "PathInContainer": "/dev/nvidia2",
                    "CgroupPermissions": "mrw"
                },
                {
                    "PathOnHost": "/dev/nvidiactl",
                    "PathInContainer": "/dev/nvidiactl",
                    "CgroupPermissions": "mrw"
                },
                {
                    "PathOnHost": "/dev/nvidia-uvm",
                    "PathInContainer": "/dev/nvidia-uvm",
                    "CgroupPermissions": "mrw"
                },
                {
                    "PathOnHost": "/dev/nvidia-uvm-tools",
                    "PathInContainer": "/dev/nvidia-uvm-tools",
                    "CgroupPermissions": "mrw"
                }
            ],
```

but if I log into the container, I can see all 8 gpu devices under /dev

```
~~~@~~~:~~~~~~# docker exec -it d37dabb82393 ls -l /dev/nvidia*
crw-rw-rw- 1 root root 241,   0 Apr 24 05:48 /dev/nvidia-uvm
crw-rw-rw- 1 root root 241,   1 Apr 24 05:48 /dev/nvidia-uvm-tools
crw-rw-rw- 1 root root 195,   0 Apr 24 05:48 /dev/nvidia0
crw-rw-rw- 1 root root 195,   1 Apr 24 05:48 /dev/nvidia1
crw-rw-rw- 1 root root 195,   2 Apr 24 05:48 /dev/nvidia2
crw-rw-rw- 1 root root 195,   3 Apr 24 05:48 /dev/nvidia3
crw-rw-rw- 1 root root 195,   4 Apr 24 05:48 /dev/nvidia4
crw-rw-rw- 1 root root 195,   5 Apr 24 05:48 /dev/nvidia5
crw-rw-rw- 1 root root 195,   6 Apr 24 05:48 /dev/nvidia6
crw-rw-rw- 1 root root 195,   7 Apr 24 05:48 /dev/nvidia7
crw-rw-rw- 1 root root 195, 255 Apr 24 05:48 /dev/nvidiactl
```
