### ISSUE TITLE
Pod on standalone kubelet never enters "Running", even though containers are up

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubernetes#44955]
**Kubernetes version** (use `kubectl version`):
- v1.7.0-alpha.2

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu 17.04
- **Kernel** (e.g. `uname -a`): 4.10.0-19-generic

**What happened**:
I want to use a standalone kubelet to bring up a pod from a static manifest. Specifically I'm trying to use kubelet to replace docker-compose in my tests.

**What you expected to happen**:
After starting the kubelet, it brings up the pods but the the /pods endpoint still shows the pod as "Pending". It never reached the "Running" state.

**How to reproduce it** (as minimally and precisely as possible):
Assuming this manifest in `/tmp/test/test.yaml`:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    # Create postgres, database and load fixtures
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: foobar23
```
And running the kubelet like this:
```
kubelet --pod-manifest-path /tmp/test/
```
Will bring up the pod with postgres container. The kubelet api (http://localhost:10255/pods) will still show phase "Pending". It never reaches "Running".

**Anything else we need to know**:
I suspect this is due to it not talking with the apiservers. Is it possible that it only enters running scale once it synced with the cluster? If so, can we make kubelet not wait for this when no apiservers are configured?
