### ISSUE TITLE
Resource name is not part of request attributes available to the authorizer for create operations

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#44978]
Authorization doesn't have access to the request body, so it can't know the name of the resource being created. For example, the following role doesn't work as expected.

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: create-a-secret
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
  resourceNames: ["my-secret"]
```

At the worst we need to document this. At best we can plead with API machinery to let us do something to make it work.

cc @kubernetes/sig-auth-misc
