### ISSUE TITLE
Does fluentd-elasticsearch grow disk space forever?

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kubernetes#44985]
I was wondering if `fluentd-elasticsearch` would keep using disk space and if so, how do I clear old logs in order to reclaim disk space. Is there any setting to delete logs older than X days?

**Comment by zetaab** [comment]
you can use curator to clean logs older than x days https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-curator.yaml https://github.com/pires/kubernetes-elasticsearch-cluster/blob/master/es-curator-config.yaml

**Comment by olalonde** [comment]
Thanks. I actually ended up writing something similar:

```yaml
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: elasticsearch-curator
  namespace: kube-system
spec:
  # daily
  # schedule: "0 0 * * *"
  # every minute (for debugging)
  # schedule: "*/1 * * * *"
  schedule: "0 0 * * *"
  # schedule: "*/1 * * * *"
  # Oops, limits only in k8s 1.6
  # For now, can manually delete if it becomes issue
  #successfulJobsHistoryLimit: 10
  #failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-curator
            image: olalonde/curator:latest
            command: ["bash"]
            args:
            - "-c"
            - |
              set -e
              es_host=${ES_HOST:-http://elasticsearch-logging:9200}
              older_than_in_days=${RETENTION_IN_DAYS:-30}

              filter_list=$(cat <<EOF
              [
                {
                  "filtertype":"age",
                  "source":"creation_date",
                  "direction":"older",
                  "unit":"days",
                  "unit_count": "${older_than_in_days}"
                },
                {
                  "filtertype":"pattern",
                  "kind":"prefix",
                  "value":"logstash"
                }
              ]
              EOF
              )

              curator_cli \
                --host "${es_host}" \
                --dry-run \
                delete_indices \
                --ignore_empty_list \
                --filter_list "${filter_list}"
            env:
            - name: RETENTION_IN_DAYS
              value: "30"
            - name: ES_HOST
              value: "http://elasticsearch-logging:9200"
          restartPolicy: OnFailure
```
