### ISSUE TITLE
Mount ConfigMap with Volumes as File

### ISSUE THREAD

**Issue by ashernevins** [kubernetes/kubernetes#45000]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Currently, it is possible to mount a single file from a host volume as a single file in a container.

```
containers:
  volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/nginx.conf

volumes:
  - name: nginx-config
    hostPath:
      path: /path/to/my/nginx.conf
```

However, when using a ConfigMap, this isn't possible. ConfigMaps must be mounted as directories
```
containers:
  volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx

volumes:
  - name: nginx-config
    configMap:
      name: nginx
      items:
        - key: NGINX_CONF
          path: nginx.conf
```

If `mountPath: /etc/nginx/nginx.conf` is specified, the following errors occurs:
```Error response from daemon: rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: not a directory"```

In the above example, we are mounting to `/etc/nginx`, which means all other contents of that directory in the container are gone.

While it is possible to work around some issues like these by restructuring directories, I believe that mounts from ConfigMaps should have the same abilities as hostPath mounts to point to a specific file.

If this is already possible with some special syntax, it would be great to see that in the documentation.
