### ISSUE TITLE
initContainers ignored with mixed versions of kubectl and server

### ISSUE THREAD

**Issue by emperorcezar** [kubernetes/kubernetes#45009]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
initContainers

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-04-07T20:46:46Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
**Environment**:
- **Cloud provider or hardware configuration**:
Minikube
- **OS** (e.g. from /etc/os-release):
OS X El Capitan
- **Kernel** (e.g. `uname -a`):
Darwin osx-cezar 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
- **Install tools**:
- **Others**:

**What happened**:
When using kubectl v1.5.x mixed with a server version of v1.6.x and a podspec with initContainers, the initContainers are ignored after initial run.

**What you expected to happen**:
The `initContainers` would start and run before the containers in the `containers` section of the spec.

**How to reproduce it** (as minimally and precisely as possible):
Use kubectl v1.5.x with a server v1.6.x and the below pod spec.

```
apiVersion: v1
kind: Pod
metadata:
  name: init-demo-bug
  labels:
      environment: local
      app: testing
spec:
  containers:
  - name: run
    image: busybox
    ports:
    - containerPort: 8000
      hostPort: 8000
    command: ["/bin/sleep"]
    args: ["11111111"]
    env:
      - name: TEST_DB_IP
        value: "10.0.2.2"
      - name: SOME_BOOLEAN
        value: "true"
      - name: OTHER_SETTINGS
        value: "testing"
    imagePullPolicy: Always
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - /bin/sleep
    - "11111"
  dnsPolicy: Default
```

Delete the pod and start it again. In the vast majority of cases the init will not run.

**Anything else we need to know**:
