### ISSUE TITLE
invalid field failedJobsHistoryLimit 

### ISSUE THREAD

**Issue by olalonde** [kubernetes/kubernetes#45011]
Getting the following error when trying to create the resource below:

```
error: error validating "staging/kubectl/logging/curator.yml": error validating data: [found invalid field successfulJobsHistoryLimit for v2alpha1.CronJobSpec, found invalid field failedJobsHistoryLimit for v2alpha1.CronJobSpec]; if you choose to ignore these errors, turn validation off with --validate=false
```

```yaml
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: elasticsearch-curator
  namespace: kube-system
spec:
  # daily
  # schedule: "0 0 * * *"
  # every minute (for debugging)
  # schedule: "*/1 * * * *"
  schedule: "0 0 * * *"
  # schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-curator
            image: olalonde/curator:latest
            command: ["bash"]
            args:
            - "-c"
            - |
              set -e
              es_host=${ES_HOST:-http://elasticsearch-logging:9200}
              older_than_in_days=${RETENTION_IN_DAYS:-30}

              filter_list=$(cat <<EOF
              [
                {
                  "filtertype":"age",
                  "source":"creation_date",
                  "direction":"older",
                  "unit":"days",
                  "unit_count": "${older_than_in_days}"
                },
                {
                  "filtertype":"pattern",
                  "kind":"prefix",
                  "value":"logstash"
                }
              ]
              EOF
              )

              curator_cli \
                --host "${es_host}" \
                --dry-run \
                delete_indices \
                --ignore_empty_list \
                --filter_list "${filter_list}"
            env:
            - name: RETENTION_IN_DAYS
              value: "30"
            - name: ES_HOST
              value: "http://elasticsearch-logging:9200"
          restartPolicy: OnFailure
```

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T23:37:53Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
