### ISSUE TITLE
move group approver to use a subject access review

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#45030]
Right now the group approver is configured with a static group name to allow provisioning of kubelet client certificates. The group approver should move to using a subject access review. We need 3 verbs to auto approve the full kubelet flow:

1. `csr/nodeclientcert` which if granted indicates the group approver should approve any kubelet client shaped certificate requested.
1. `csr/selfnodeclientcert` which if granted indicates the group approver should approve a kubelet client shaped certificate requested if the username of the csr creating user matches the subject of the csr.
1. `csr/selfnodeservercert` which if granted indicates the group approver should approve a kubelet server shaped certificate requested if the username of the csr creating user matches the subject of the csr.

Names of the verbs are a rough draft. Existence of 1 allows for a preshared cluster wide bootstrap identity that can be rotated and invalidated. Existence of 2 allows a kubelet to rotate it's own client credentials. Existence of 2 allows a kubelet to request and rotate it's own server certificate. 

I'm capturing a slack conversation with @liggitt so let me know if i got something wrong.

**Comment by mikedanese** [comment]
@jcbsmpsn @pipejakob

**Comment by luxas** [comment]
@mikedanese This requires RBAC being enabled, and the right Roles/RoleBindings should be created, right?
In order to make the groupapprover approve csrs from an individual user, should a RoleBinding be created?

@mikedanese @jcbsmpsn Could you provide a short list of the implications/work items for kubeadm so we can make sure we'll get that into kubeadm v1.7?

**Comment by liggitt** [comment]
It does not require RBAC, subject access reviews will use whatever authorizer is configured.

If you are using RBAC, I would expect a role for each of the individual permissions, which could be bound to bootstrap users, individual node users, or the entire node group.

**Comment by mikedanese** [comment]
We will need to add an rbac role for rbac enabled kubeadm. The change should be small.

**Comment by luxas** [comment]
So the RBAC role would look something like this then?
```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: approve-node-csrs-for-<token-id>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:csrapproval:nodeclientcert
subjects:
- kind: User
  name: system:bootstrap:<token-id>
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: system:csrapproval:nodeclientcert
rules:
- apiGroups:
  - authorization.k8s.io/v1
  resources:
  - subjectaccessreviews
  resourceName:
  - csr/nodeclientcert
  verbs:
  - create
```

I'm confused whether `csr/nodeclientcert` will be the resource, subresource or just in `.spec.resourceAttributes` of the SAR.

I guess we want to lock things down on a token (user)-level, to only let the generated-by-default-token do the TLS bootstrap and nobody else.

**Comment by liggitt** [comment]
Probably rules something more like this (where the different categories manifest as subresources of the certificatesigningrequests resource):

In a role bound to the bootstrapper:
```yaml
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/nodeclient"]
  verbs: ["create"]
```

In a role to enable kubelets to rotate their own client certs (would need more thought about how to cut off a compromised node):
```yaml
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/selfnodeclient"]
  verbs: ["create"]
```

In a role bound to enable kubelets to bootstrap/rotate their serving certs (would need more thought about how to verify the CN/SANs in the cert belong to that node, and how to cut off a compromised node):
```yaml
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/selfnodeserver"]
  verbs: ["create"]
```

**Comment by ericchiang** [comment]
Are the second two roles bound to the bootstrapper? I'd imagine they'd be tied to the node themselves, which would give a good way to revoke follow-up access.

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: approve-node-client-renewal-for-<node-id>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:csrapproval:selfnodeclient
subjects:
- kind: User
  name: system:node:<node-id>
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: system:csrapproval:selfnodeclient
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/selfnodeclient"]
  verbs: ["create"]
```
