### ISSUE TITLE
FsGroup support for Local Persistent Volumes

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#45053]
Once #44897 is in, proper fsGroup support should be added.  The current implementation just sets the volume's fsGroup to the one supplied, but it doesn't check if it could be conflicting with other pods.  This could cause problems if multiple pods use the same PVC, but have different fsGroup settings.  Tests should also be added.

@kubernetes/sig-storage-bugs

**Comment by ddysher** [comment]
@msau42 looking at this one

**Comment by ddysher** [comment]
At which layer do we want to solve the problem? If at scheduling time, then we want to make `fsGroup` part of the resources managed by scheduler, which I don't know if it is desirable (e.g. kubernetes explicitly doesn't want to manage port as a resource). If at pod startup time, one option is to refuse new pods from using different `fsGroup`, but this does mean we give higher 'priority' to the first pod, which is IMO is a little bit biased.

@msau42 WDYT?

**Comment by msau42** [comment]
I think enforcing at mount time would work.  I think it is ok because if two pods are sharing a volume, then they should be coordinating together anyway.

**Comment by ddysher** [comment]
Sounds good.
> if two pods are sharing a volume, then they should be coordinating together anyway.  

Then the workflow would be: if at mount time, we see different fsGroup, then kubelet will reject following pods.  But this means we'll make sure scheduler knows the decision from kubelet and doesn't repeatedly schedule the pod back.  In kubelet eviction oom case, i think we added a new condition to Node.  Since this condition is volume specific, I think we can have kubelet add some information to PVC (though label or annotation) for scheduler to make better decision, e.g. 

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotation:
    scheduler.kubernetes.io/conflicting-fsgroup: node-1,node-3
spec:
  storageClassName: local-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```
