### ISSUE TITLE
Pulling an Image from a  Docker hub Private Registry : failed

### ISSUE THREAD

**Issue by akdj** [kubernetes/kubernetes#45086]
Hi! 
I want to make a deployment of one docker image on my kubernetes cluster
I followed this post : [Pulling an Image from a Private Registry](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)
I only modifed the final step : instead of create juste a pod, I create a deployment : 

with this yaml config : 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockerimage-deployment
  namespace: dockerimage-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myserv
    spec:
      containers:
      - name: myserv
        image: dockerusername/dockerprivateregistry:myserv
        ports:
            -
              name: web3001
              containerPort: 3001
              protocol: TCP
            -
              name: web4001
              containerPort: 4001
              protocol: TCP
            -
              name: dbgapp
              containerPort: 8080
              protocol: TCP
            -
              name: debug
              containerPort: 5858
              protocol: TCP
        env:
            -
              name: KUBERNETES_NAMESPACE
              valueFrom: { fieldRef: { apiVersion: v1, fieldPath: metadata.namespace } }
            -
              name: NODE_CONFIG_DIR
              value: /opt/app/node/config
            -
              name: NODE_ENV
              value: nodejsconfigname
            -
              name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
      imagePullSecrets:
        - name: regsecret
```

And I have always : 

```
Failed to pull image "dockerusername/dockerprivateregistry:myserv": rpc error: code = 2 desc = net/http: request canceled
Error syncing pod, skipping: failed to "StartContainer" for "myserv" with ErrImagePull: "rpc error: code = 2 desc = net/http: request canceled"
```
