### ISSUE TITLE
Add `kubectl config rename-context`

### ISSUE THREAD

**Issue by hostirosti** [kubernetes/kubernetes#45131]
Getting a kubectl context/credentials through e.g. GKE creates an entry in ~/.kubeconfig with a lengthy name: gke_projectname_zone_cluster-name.

It would be amazing to be able to rename the context via kubectl instead of manually in .kubeconfig 
Before:
```
CURRENT   NAME   CLUSTER AUTHINFO NAMESPACE
* gke_projectname_zone_cluster-name gke_projectname_zone_cluster-name gke_projectname_zone_cluster-name gke_projectname_zone_cluster-name
```
--> `kubectl config rename-context k8s-is-awesome-cluster`

After:
```
CURRENT   NAME   CLUSTER AUTHINFO NAMESPACE
* k8s-is-awesome-cluster gke_projectname_zone_cluster-name gke_projectname_zone_cluster-name gke_projectname_zone_cluster-name
```
@kubernetes/kubectl

**Comment by hostirosti** [comment]
Found a work around if anyone is interested (currently requires 3 steps):

1. Get context information (you need the CLUSTER name and AUTHINFO for the next step):
```
kubectl config get-contexts <old-context-name>
```
1. Create new context:
```
kubectl config set-context <new-context-name> --cluster <cluster-from-old-context> --user <auth-info-from-old-context>
```

1. Delete old context:
```
kubectl delete-context <old-context-name>
```

**Comment by d-Pixie** [comment]
I had my config in `~/.kube/config`. In that file you will find entries such as:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/name/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/name/.minikube/apiserver.crt
    client-key: /Users/name/.minikube/apiserver.key
```

Simply edit the context's name under `contexts.context.name` and save the file.
