### ISSUE TITLE
The APIService should be able to consume the CA from a ConfigMap

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#45144]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Kubernetes version** (use `kubectl version`):

HEAD

Currently, a typical APIService resource looks like this:
```yaml
apiVersion: apiregistration.k8s.io/v1alpha1
kind: APIService
metadata:
  name: v1alpha1.custom-metrics.metrics.k8s.io
spec:
  #insecureSkipTLSVerify: true
  caBundle: <ca blob>
  group: custom-metrics.metrics.k8s.io
  priority: 150
  service:
    name: api
    namespace: custom-metrics
  version: v1alpha1
```

It would be much easier to maintain if the `caBundle` instead could point to a Secret inside of the cluster, like the `service` field.

I think we could add a new field `caSecretRef` that would optionally point to a Secret inside of the cluster like this:
```go
// SecretReference holds a reference to Secret.k8s.io
type SecretReference struct {
	// Namespace is the namespace of the secret
	Namespace string `json:"namespace,omitempty" protobuf:"bytes,1,opt,name=namespace"`
	// Name is the name of the secret
	Name string `json:"name,omitempty" protobuf:"bytes,2,opt,name=name"`
        // Key is the key of the secret to use when consuming the secret
        Key string `json:"key,omitempty" protobuf:"bytes,3,opt,name=key"`
}
```

This way we could:
a) Generate the CA and the certs in beforehand and create them as Secrets in the cluster before registering the `APIService`
b) Dynamically rotate the CA easily when needed
c) Avoid templating the `caBundle` field => the less templating we do, the better

`caBundle` could have higher priority and be left for bootstrapping purposes or more advanced usages for instance

I think this would be important for the ease-of-use of API Aggregation, and something we should consider doing before beta (v1.7)

**EDIT:** Think `s/Secret/ConfigMap/` when reading the above

cc @kubernetes/sig-api-machinery-feature-requests @kubernetes/sig-api-machinery-api-reviews @deads2k @liggitt
