### ISSUE TITLE
On Minikube pause image is always pulled from internet and proxy setting doesn't work

### ISSUE THREAD

**Issue by Rev1408** [kubernetes/kubernetes#45226]
I am using Minikube, my server is behind a proxy, this is my pod yaml file

```
root@server1:~/sample/nginx_kube_example# cat nginx_pod.yaml
piVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80

root@server1:~/sample/nginx_kube_example# kubectl create -f nginx_pod.yaml
```
I pre downloaded the nginx and pause images

```
root@server1:~/sample/nginx_kube_example# docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
nginx                                  latest              46102226f2fd        6 days ago          109 MB
alpine                                 latest              4a415e366388        8 weeks ago         3.99 MB
gcr.io/google_containers/echoserver    1.4                 a90209bb39e3        11 months ago       140 MB
gcr.io/google_containers/pause-amd64   3.0                 99e59f495ffa        12 months ago       747 kB

```

But still starting the pods fails, my pods are always in 'ContainerCreating' status and this is the error in the events, looks like its trying to pull pause image from internet, even though i specified imagePullPolicy: Never in my yaml file, but i specified it for ngnix image, not sure how to specify for pause image

`  22s	22s	1	kubelet, minikube		Warning	FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "nginx-s2z0m_default(5c81955f-2f27-11e7-a15f-525400db09ca)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-s2z0m_default(5c81955f-2f27-11e7-a15f-525400db09ca)\" failed: rpc error: code = 2 desc = unable to pull sandbox image \"gcr.io/google_containers/pause-amd64:3.0\": Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on xxx:53: read udp yyy:33016->xxx:53: i/o timeout"
`
and the other issue is, i had set the proxy correctly and docker pull works fine, but not sure why when kubernetes tries to pull image it fails, with the above error
