### ISSUE TITLE
Scheduling fails with "Insufficient Memory" until restart of apiserver/master

### ISSUE THREAD

**Issue by Spindel** [kubernetes/kubernetes#45237]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):  No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
memory scheduler / memory scheduling

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-25T14:48:12Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+coreos.0", GitCommit:"9212f77ed8c169a0afa02e58dce87913c6387b3e", GitTreeState:"clean", BuildDate:"2017-04-04T00:32:53Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:  Custom/mixed
- **OS** (e.g. from /etc/os-release):  CoreOS 1353.7.0 (stable)
- **Kernel** (e.g. `uname -a`): Linux coreos04.kub.do.modio.se 4.9.24-coreos #1 SMP Wed Apr 26 21:44:23 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2650L v3 @ 1.80GHz GenuineIntel GNU/Linux

- **Install tools**: Manual guide / ansible
- **Others**:

**What happened**:
Scheduling pods which have a memory limit slowly fails after a few pod deployments, until the master node is restarted, upon which it starts working again.

Pods are configured with:
```
          resources:
            limits:
                memory: "1Gi"
                cpu: "1"
            requests:
                cpu: "100m"
                memory: "30Mi"

```
While the node ouputs:
```
    Capacity:
     cpu:		2
     memory:	2052872Ki
     pods:		110
    Allocatable:
     cpu:		2
     memory:	1950472Ki
     pods:		110

```
And further down:
```
    Allocated resources:
      (Total limits may be over 100 percent, i.e., overcommitted.)
      CPU Requests	CPU Limits	Memory Requests	Memory Limits
      ------------	----------	---------------	-------------
      150m (7%)	1 (50%)		12Mi (0%)	128Mi (6%)
Events:
```

The numbers don't add up, and manually stepping through sizes show that up to ~300Mi the nodes schedule, after that they fail. This behaviour appears consistently for us.

[node.description.txt](https://github.com/kubernetes/kubernetes/files/971603/node.description.txt)
[pod.description.txt](https://github.com/kubernetes/kubernetes/files/971602/pod.description.txt)

**What you expected to happen**:
Requirements limiting the jobs on the machine to ~3  due to memory pressure

**How to reproduce it** (as minimally and precisely as possible):
Schedule a Lot of pods with memory limits and  delete them / let them complete.

For us, this is a giblab CI runner which connects to create pods for us, and after a while all our build machines stand empty, and jobs wait in scheduling tempo forever.

**Anything else we need to know**:
pass.

**Comment by k82cn** [comment]
kube-scheduler will use `request` for scheduler, but according to the node, pod description, there's still enough resource for more pods.

let me try it to see what happened.

```
Non-terminated Pods:		(2 in total)
  Namespace			Name						CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ---------			----						------------	----------	---------------	-------------
  default			zabbix-agent-wkhgf				150m (7%)	1 (50%)		12Mi (0%)	128Mi (6%)
  kube-system			kube-proxy-coreos04.kub.do.modio.se		0 (0%)		0 (0%)		0 (0%)		0 (0%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
  150m (7%)	1 (50%)		12Mi (0%)	128Mi (6%)
```

/cc @kubernetes/sig-scheduling-misc

**Comment by xiangpengzhao** [comment]
Similar issues: #33777 #34920 (with `Insufficient CPU`)

**Comment by k82cn** [comment]
@Spindel , can you share scheduler's log?

**Comment by xiangpengzhao** [comment]
Two other resource related issues: #45213 #45220

**Comment by k82cn** [comment]
failed to reproduce in local cluster :(. I keep create & delete pods by following commands:

Create Pods:
```
kc create -f pod.yaml
```

Delete Running Pods:

```
kc delete pods $(kc get pods | grep Running | cut -f 1 -d " ")
```

**Comment by Spindel** [comment]
@k82cn Here are the logs from the scheduler, it doesn't look as much.

kubectl logs --namespace=kube-system kube-scheduler-coreos01.kub.do.modio.se --timestamps=true > scheduler.txt

[scheduler.txt](https://github.com/kubernetes/kubernetes/files/972739/scheduler.txt)

**Comment by Spindel** [comment]
Most pods here are created by the GitlabCI multi runner with the [kubernetes executor](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/executors/kubernetes.md)  

My local reproduction case was starting "busybox" with a sleep command, and that showed the same problem though, so it wasn't CI-specific.

**Comment by Spindel** [comment]
If there is anything else I can do to help debug this, it would be really nice. 
Our workaround is for now to not use resource limits at all on our containers, not in the CI or otherwise. This feels suboptimal.

Anything further would be welcome.

**Comment by tacy** [comment]
@Spindel  I can't reproduce it, use command:
`kubectl run busybox1 --image=busybox --requests="cpu=100m,memory=1Gi" --limits="cpu=1,memory=2Gi" --replicas=1 --restart=Never --command -- sleep 60`

**Comment by Spindel** [comment]
I had to add a Node Selector as well to make it match, so the final yaml looks like this

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: busybox1
spec:
  containers:
  - command:
    - sleep
    - "60"
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox1
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 1Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  nodeSelector:
    gitlab: "true"

status: {}

```
Attaching log of "describe" on one of the nodes and the pod / creation,  including timestamps.
[commandlog.txt](https://github.com/kubernetes/kubernetes/files/975431/commandlog.txt)
