### ISSUE TITLE
Scaling or deleting statefulset in 1.5 cluster with 1.6 kubectl fails

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#45287]
**BUG REPORT**

When running either `kubectl delete statefulset <statefulset name>` or `kubectl scale statefulset <statefulset name> --replicas=<count>` with kubectl 1.6.2 against a GKE cluster 1.5.6 it fails with an error like the following.

```
error: Scaling the resource failed with: StatefulSet.apps "<statefulset name>" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas' are forbidden.; Current resource version 100392498
```

This happened the other way around as well with kubectl 1.5.x against a GKE 1.6.x cluster.

For scaling there's a working alernative by running `kubectl patch statefulsets <statefulset name> -p '{"spec":{"replicas":'<count>'}}'`. Unfortunately I haven't found a workaround yet for deleting the statefulset.

**Kubernetes version**:

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Google Container Engine 1.6.2 with cos image**:
- **OS** (e.g. from /etc/os-release):

```
BUILD_ID=9000.84.2
NAME="Container-Optimized OS"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=56
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=56
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```

- **Kernel** (e.g. `uname -a`):

```
Linux gke-production-europe-we-auto-scaling-917da0af-zzzj 4.4.21+ #1 SMP Fri Feb 17 15:34:45 PST 2017 x86_64 Intel(
R) Xeon(R) CPU @ 2.50GHz GenuineIntel GNU/Linux
```

**What happened**:

- `kubectl delete statefulset <statefulset name>` failed with `updates to statefulset spec for fields other than 'replicas' are forbidden` error
- `kubectl scale statefulset <statefulset name> --replicas=<count>` failed with `updates to statefulset spec for fields other than 'replicas' are forbidden` error

**What you expected to happen**:

Both actions to succeed

**How to reproduce it** (as minimally and precisely as possible):

- Create a statefulset in a GKE 1.5.6 cluster
- Run the above commands with kubectl 1.6.2

**Anything else we need to know**:

Happens for kubectl 1.5.x with GKE 1.6.x as well.

**Comment by xiangpengzhao** [comment]
Can the actions succeed with the same version of kubectl and cluster?

**Comment by JorritSalverda** [comment]
@xiangpengzhao yes that works fine.

**Comment by JorritSalverda** [comment]
Deleting them through the dashboard works fine, so I have a workaround without downgrading my kubectl version :)

**Comment by xiangpengzhao** [comment]
cc @foxish

**Comment by foxish** [comment]
@kubernetes/sig-apps-bugs

**Comment by foxish** [comment]
@crimsonfaith91 This may be a good issue to look into.

**Comment by foxish** [comment]
@JorritSalverda, can you post your manifest file? Would be interesting to try and reproduce this. 
We think this might be due to the scale-down request that first goes out from kubectl, which should be using a PATCH, in place of using a PUT. 

cc @kow3ns

**Comment by crimsonfaith91** [comment]
@foxish noted! i will prioritize this issue. :)

**Comment by JorritSalverda** [comment]
One of the statefulsets where this fails has the following manifest:

```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch-logging-master
  namespace: logging
  labels:
    app: elasticsearch-logging
    team: tooling
    role: master
spec:
  serviceName: "elasticsearch-logging-master"
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch-logging
        team: tooling
        role: master
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "Always",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
        scheduler.alpha.kubernetes.io/affinity: >
            {
              "podAntiAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [{
                  "weight": 100,
                  "labelSelector": {
                    "matchExpressions": [{
                      "key": "app",
                      "operator": "In",
                      "values": ["elasticsearch-logging"]
                    },{
                      "key": "role",
                      "operator": "In",
                      "values": ["master","data"]
                    }]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }]
              }
            }
    spec:
      serviceAccount: elasticsearch-logging
      containers:
      - name: elasticsearch-logging-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.3.0
        imagePullPolicy: Always
        env:
        - name: "KUBERNETES_CA_CERTIFICATE_FILE"
          value: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "NODE_NAME"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "elasticsearch-logging"
        - name: "NODE_MASTER"
          value: "true"
        - name: "NODE_DATA"
          value: "false"
        - name: "NODE_INGEST"
          value: "false"
        - name: "HTTP_ENABLE"
          value: "true"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch-logging-discovery"
        - name: "NUMBER_OF_MASTERS"
          value: "2"
        - name: "ES_JAVA_OPTS"
          value: "-Xms1024m -Xmx1024m"
        resources:
          requests:
            cpu: 75m
            memory: 1536Mi
          limits:
            cpu: 500m
            memory: 1536Mi
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: elasticsearch-logging-master
      volumes:
      - name: elasticsearch-logging-master
        persistentVolumeClaim:
          claimName: elasticsearch-logging-master
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-logging-master
      namespace: logging
      annotations:
        volume.beta.kubernetes.io/storage-class: "standard"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

The error is indeed the same for deleting the _statefulset_ as when scaling it up/down. For scaling the stafefulset `kubectl patch` works around the error. However even if it's already scaled down to 0 `kubectl delete` internally tries to do the same again, I guess, and fails doing that.

**Comment by erictune** [comment]
/assign @foxish 
who is helping @crimsonfaith91

**Comment by crimsonfaith91** [comment]
i am able to reproduce the bugs when running `kubectl delete` and `kubectl scale`. i will explore the codebase to identify the problem.

**Comment by lcjlcj** [comment]
Any update on this issue? I also just hit this problem and it's blocking us. Thank you!

**Comment by crimsonfaith91** [comment]
We are still working on this issue, and will get back to you later.

**Comment by crimsonfaith91** [comment]
@JorritSalverda What is the Kubernetes minor version that you used for kubectl 1.5.x against GKE 1.6.x cluster?

**Comment by JorritSalverda** [comment]
@crimsonfaith91 it was the last 1.5.x kubectl bundled with gcloud before it got updated to 1.6.x

If I look at the release notes at https://cloud.google.com/sdk/docs/release-notes#15000_2017-04-05 it must have been 1.5.4:

> Updated Google Container Engine's kubectl from version 1.5.4 to 1.6.0.

Container Engine had just been upgraded to 1.6.0 at that time, looking at the release notes at https://cloud.google.com/container-engine/release-notes#april_4_2017

**Comment by crimsonfaith91** [comment]
@JorritSalverda 
I am able to reproduce the error for v1.6.2 client and v1.5.6 server, but not able to do so for v.1.5.4 client and v1.6.0 server.

Did you mean the versions below?

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-05-11T17:00:38Z", GoVersion:"go1.8.1.typealias", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by crimsonfaith91** [comment]
@JorritSalverda @lcjlcj 
I added `"terminationMessagePath": "/dev/termination-log",` into init container annotation syntax, and then restart the server. It fixed the issue on my machine. I will continue working on a better way to fix the issue, but this may be a quick fix.

```
pod.alpha.kubernetes.io/init-containers: '[
          {
          "name": "sysctl",
            "image": "busybox",
            "imagePullPolicy": "Always",
	    "terminationMessagePath": "/dev/termination-log",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
```

**Comment by crimsonfaith91** [comment]
@lcjlcj 
If the issue still blocks you, you may consider using kubectl v1.5. Tell me if you need any help. Thanks!

**Comment by smarterclayton** [comment]
Sanity check - are stateful sets using the scale endpoint?  If not... that's what we should be fixing.  The scale endpoint is allowed to do more efficient things, but fundamentally all edits are going to result in some defaulting.

**Comment by crimsonfaith91** [comment]
@smarterclayton The statefulsets are not using the scale endpoint. i will fix this. :)

**Comment by alledm** [comment]
@crimsonfaith91 @lcjlcj kubectl 1.5.7 works

> `curl -O https://storage.googleapis.com/kubernetes-release/release/v1.5.7/bin/linux/amd64/kubectl && chmod +x kubectl`

**Comment by crimsonfaith91** [comment]
@smarterclayton We had a discussion about this, and think that using patch is a better option than fixing scale endpoint for now. We need to backport the change, and there is currently no scale subresource for statefulsets. The idea is to use the scale subresource if it is available, and fall back to patch if it is not. To resolve this issue, using patch (short-term fix) is more suitable compared to fixing the endpoint (long-term fix).

We will come back to fix the endpoint when the scale subresource is implemented. Does this sound reasonable to you? :)

**Comment by smarterclayton** [comment]
Sure, putting a hack in to a beta feature is ok.  But it's a requirement for GA anyway

**Comment by crimsonfaith91** [comment]
For future reference, the problem is due to immutability of `InitContainers` and `Affinity` pod spec that fails validation check. It can be fixed by:
(1) using same version of client and server
(2) using newer version of Kubernetes

As there are 2 convenient fixes, I think it is not justified to work on backporting the change to v1.5. The scale endpoint will be fixed and rolled out in future releases. Please refer this issue (work in progress) for more information: https://github.com/kubernetes/kubernetes/issues/46005

**Comment by fatih** [comment]
We also encountered this on our recent test cluster which we upgraded to 1.7.0. Here is the `kubectl version` output:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T10:00:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

and here is the error message:

```
$ kubectl delete statefulset/mysql
error: Scaling the resource failed with: StatefulSet.apps "mysql" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.; Current resource version 188916
```

Here is the declaration of the statefuleset that I've used to create it (and now can't be deleted anymore)

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
              name: server
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: do-block
      spec:
        storageClassName: do-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
```
