### ISSUE TITLE
Error creating: pods "" is forbidden: SecurityContext.SupplementalGroups is forbidden

### ISSUE THREAD

**Issue by hiscal2015** [kubernetes/kubernetes#45324]
Hi, all

I'm trying to deploy Jenkins with Kubernetes, Jenkins container will be running as GID 1000 and UID 1000, and I use glusterfs as storage backend.

Here is my part of deployment config:
```
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      restartPolicy: Always
      securityContext:
        supplementalGroups: [1000]
        runAsUser: 1000
      containers:
      - name: devops-jenkins
       
```

I got error: 
Error creating: pods "" is forbidden: SecurityContext.supplementalGroups is forbidden 
Error creating: pods "" is forbidden: SecurityContext.RunAsUser is forbidden 

How to fix it? Thanks.
