### ISSUE TITLE
kubelet iptables performance issue with --make-iptables-util-chains=true

### ISSUE THREAD

**Issue by rtheis** [kubernetes/kubernetes#45385]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): v1.5.3

**Environment**:
- **Cloud provider or hardware configuration**: Vagrant environment
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2
- **Kernel** (e.g. `uname -a`): 4.4.0-62-generic
- **Install tools**: ansible
- **Others**:

**What happened**:
After creating 25 nginx pods and 400 services for the nginx deployment, kubelet updates iptables every 60 seconds at 100% CPU even with no changes to the system.

`kubectl run --image=nginx --replicas=25 --port=80 d3`

```
#!/bin/bash
for i in $(seq 400); do
    kubectl create -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  labels:
    run: d3
  name: d3-$i
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: d3
  sessionAffinity: None
  type: ClusterIP
EOF
done
```

**What you expected to happen**:
kubelet skips iptables updates when there aren't any changes.

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else we need to know**:
Setting `--make-iptables-util-chains=false` circumvents the problem.
