### ISSUE TITLE
AWS ELB hostname and https -> https configuration

### ISSUE THREAD

**Issue by abrass** [kubernetes/kubernetes#45417]
Is this a request for help? : yes, but could not find any guidance in the troubleshooting

What keywords did you search in Kubernetes issues before filing this one?: Alot with kombination of: aws elb, kubernetes, https, annotation. Found lot of issues and information, but have no idea how to solve my problems.

If have generally two questions adressing the automatically created AWS ELB

1. Is it possible to set the DNS name of a generated AWS ELB ? 
E.g. set a readable name like "service.namespace....eu-central-1...."
instead of the automatically generated one: "ab624e70d1f....eu-central-1.elb.amazonaws.com"

2. We have an application that is hosted on a TomEE that has a http and https listener. I want to call https over the ELB and route the request as a https request to the TomEE. 

What works is receiving an https in the ELB and call the http-Port of TomEE. 

The TomEE has an self-signed certificate. Using AWS directly, we can define, that any certificate is trusted. 

Is there an annotation (or other way) to configure the same over kubernetes?

My configuration of the ELB is like this:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    elb: my-app-elb
  name: my-app-elb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol=https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert=arn:aws:acm:eu-central-1:xyz:certificate/1234-312321-4242-312321-31234554
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports=443
spec:
  ports:
  - name: https
    port: 443
    targetPort: app-ssl-port
    protocol: TCP
  selector:
    app: my-app
  type: LoadBalancer
```

The call of https -> https just not reach the TomEE application.

Thx for any help! :)
