### ISSUE TITLE
[GKE] Ingress does not connect to NodePort Service

### ISSUE THREAD

**Issue by riturajtiwari** [kubernetes/kubernetes#45438]
**Is this a request for help?**: No

**What keywords did you search in Kubernetes issues before filing this one?** : `is:issue is:open gke `

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Kubernetes version** (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE

**What happened**: Hitting the static IP assigned to my `Ingress` results in an `HTTP 502`

**What you expected to happen**: `200 OK`

**How to reproduce it** (as minimally and precisely as possible):
I followed steps adapted from [here](https://github.com/kelseyhightower/ingress-with-static-ip).

I have a service that looks like this:
```
kind: Service
apiVersion: v1
metadata:
  name: myapp-service
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      targetPort: 5000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: myapp-web
  type: NodePort
```

And an Ingres that looks like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "myapp-qa-staticip"
spec:
  backend:
    serviceName: myapp-service
    servicePort: 80
```

The static IP is a global static IP assigned via GCP Networking.

When I create the `Service` and the `Ingress`, I keep getting a `502` despite giving GCP upto an hour to provision whatever it needs to provision.
**Anything else we need to know**:
If I change service type from `NodePort` to `LoadBalancer` and use the ephemeral static IP, my app comes up beautifully.

**Comment by riturajtiwari** [comment]
@cblecker This is related to previous issue https://github.com/kubernetes/kubernetes/issues/44521

What was a 10 minute delay in getting the `Ingress` connected has turned into a complete inability for `Ingress` and `NodePort Service` to talk. I have worked around this by discontinuing use of `Ingress` and pointing my DNS at the ephemeral public IP assigned to my `LoadBalancer Service`, but would like to use the proper `Ingress` route if at all possible.

**Comment by nicksardo** [comment]
@riturajtiwari You don't provide much data to go on. Are there any events for the ingress object? Describe the object and print everything out here. Do you see any resources in the networking tab of the GCP console? Forwarding rules, backend services, etc? Does the static ip "myapp-qa-staticip" exist?

**Comment by riturajtiwari** [comment]
Hi Nick:
Thanks for the response. Yes, the static IP exists. I first encountered this issue as https://github.com/kubernetes/kubernetes/issues/44521 where the `Ingress` would connect after a 10 minute delay. The exact same k8s config files with a new 1.6.2 cluster do not work. Let me create some dummy resources and send you the info you requested.

**Comment by riturajtiwari** [comment]
So, I followed this guide step by step: https://github.com/kelseyhightower/ingress-with-static-ip
My `Ingress` definition is different as it uses my allocated public IP:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ap-qa"
spec:
  backend:
    serviceName: nginx
    servicePort: 80
```

My GCP Console Networking shows:
```
$ gcloud compute addresses list
NAME   REGION  ADDRESS        STATUS
ap-qa          35.186.xxx.xx  IN_USE
```

Forwarding rule for the static IP is:
```
{
  "kind": "compute#forwardingRule",
  "id": "647926000568xxxx",
  "creationTimestamp": "2017-04-17T10:47:18.017-07:00",
  "name": "k8s-fw-default-ap-qa--cec45215e3xxxx",
  "description": "",
  "IPAddress": "35.186.xxx.xx",
  "IPProtocol": "TCP",
  "portRange": "80-80",
  "target": "projects/xxx/global/targetHttpProxies/k8s-tp-default-ap-qa--cec45215e3fxxxx",
  "selfLink": "projects/xxx/global/forwardingRules/k8s-fw-default-ap-qa--cec45215e3fxxxx",
  "loadBalancingScheme": "EXTERNAL"
}

```
What is the best way to filter StackDriver logs on GCP to give me ingress logs?

**Comment by nicksardo** [comment]
@riturajtiwari Still need more data
```shell
kubectl describe svc/XYZ
kubectl describe ingress/XYZ
```

That forwarding rule shows the name of ingress is "ap-qa", but that's the static ip name (I would expect the ingress name myapp-ingress) . Also, you show the nginx ingress with name "nginx", so I have no constant information to help.

**Comment by nicksardo** [comment]
Here's my full working example. I just tested it and it took ~3 minutes to start returning.
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-echo-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echoserver
        image: nicksardo/echoserver:latest
        imagePullPolicy: Always
        env:
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: podname
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-echo-svc
  labels:
    app: echo
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: my-http-port
  selector:
    app: echo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-echo-ingress
spec:
  backend:
    serviceName: my-echo-svc
    servicePort: my-http-port
```
