### ISSUE TITLE
podAntiAffinity namespace defaults to all, not current as documented

### ISSUE THREAD

**Issue by erikgrinaker** [kubernetes/kubernetes#45484]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): podAntiAffinity namespaces

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Kubernetes version** (use `kubectl version`): 1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): cos 57 build 9202.64.0
- **Kernel** (e.g. `uname -a`): 4.4.35
- **Install tools**:
- **Others**:

**What happened**:

Created two deployments with same podAntiAffinity rules in different namespaces. Did not specify `namespaces` field for affinity rules. Pods in second namespace failed to schedule due to conflicts with pods in first namespace. Had to explicitly set `namespaces` field to allow scheduling.

**What you expected to happen**:

The `namespaces` field should default to the current namespace, as [documented](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature). Instead, it defaults to all namespaces.

**How to reproduce it** (as minimally and precisely as possible):

Consider the following deployment, which runs 2 Nginx pods that may not be scheduled onto the same node:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app 
                operator: In
                values: [nginx]
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

Create a cluster with 3 nodes, and apply the above manifest to two namespaces:

```sh
$ gcloud container clusters create --cluster-version 1.6.2 -m n1-standard-1 --num-nodes 3 test
$ kubectl apply -f nginx.yaml
$ kubectl create namespace other
$ kubectl -n other apply -f nginx.yaml
```

One of the pods in the second namespace will fail to be scheduled, even though the pod anti-affinity rules should only apply within the current namespace by default:

```sh
$ kubectl -n other get pods
NAME                     READY     STATUS    RESTARTS   AGE
nginx-2407780625-15jkz   0/1       Pending   0          1m
nginx-2407780625-8m7h2   1/1       Running   0          1m

$ kubectl -n other describe pod nginx-2407780625-15jkz
[...]
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  8m		15s		34	default-scheduler			Warning		FailedScheduling	No nodes are available that match all of the following predicates:: MatchInterPodAffinity (3).
```

**Anything else we need to know**:

There is an open issue for this in the documentation repo:

https://github.com/kubernetes/kubernetes.github.io/issues/2676

However, I believe this is a bug with the implementation, as the code also states that it should default to current namespace:

https://github.com/kubernetes/kubernetes/blob/e443277d58e3ff1f0701ab97a1f4932389c27847/pkg/api/types.go#L1904-L1906
