### ISSUE TITLE
podsecuritypolicy with rbac does not work as expected

### ISSUE THREAD

**Issue by ghao-ooyala** [kubernetes/kubernetes#45612]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
podsecuritypolicy rbac volume
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.6.2

**Environment**:
- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release): core-os
- **Kernel** (e.g. `uname -a`): 4.9.9-coreos-r1 #1 SMP Tue Feb 28 00:06:10 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz GenuineIntel GNU/Linux
- **Install tools**: 
- **Others**:

**What happened**:
I was trying to setup psp with rbac, here is what I wanted to achieve:
1. for regular authenticated users, they are not allowed to mount hostPath volume
1. allow dev-ops team member to mount hostPath volume into pod (for example, we run sumologic as daemonset and it need to mount hostPath in order to access logs from other containers)

Mostly I followed instruction at https://github.com/kubernetes/kubernetes/blob/master/examples/podsecuritypolicy/rbac/README.md 

We have enabled authentication (using a homemade webhook), rbac; the controller-manager is setup to talks to apiserver on secure port;

Following psp, clusterrole and clusterrolebinding are created for restricted users:
```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: volume-restricted
spec:
  volumes:
    - 'secret'
    - 'configMap'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'emptyDir'
    - 'awsElasticBlockStore'
    - 'nfs'
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: restricted-psp-user
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - volume-restricted
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
    name: restricted-psp-user
subjects:
- kind: Group
  name: system:authenticated
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: restricted-psp-user
```
And following are created for privileged users:
```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: volume-privileged
spec:
  volumes:
    - 'secret'
    - 'configMap'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'emptyDir'
    - 'awsElasticBlockStore'
    - 'nfs'
    - 'hostPath'
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: privileged-psp-user
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - volume-privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
    name: privileged-psp-user
subjects:
- kind: Group
  name: opsTeam    <== opsTeam group is from our webhook authenticator
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: privileged-psp-user
```
So after all these setups,  I tried to do a test deployment as follow:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-deployment-v1
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /test-pd
          name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          path: /etc
```
```
>kubectl create -f nginx-v.yaml
deployment "nginx-deployment-v1" created
>kubectl get deployments
NAME                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment-v1   1         0         0            0           50s
```
pods are not created,  for both regular user and opsTeam members; it looks like psp volume-privileged is not getting used

====Additional info=====:
Here is apiserver parameters used to start apiserver:
```
containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:v1.6.2_coreos.0
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --insecure-bind-address=0.0.0.0
    - --etcd-servers=http://etcd:2379
    - --allow-privileged=true
    - --cloud-provider=aws
    - --enable-swagger-ui
    - --service-cluster-ip-range=172.16.0.0/16
    - --secure-port=443
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,PodSecurityPolicy
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --runtime-config=extensions/v1beta1=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/podsecuritypolicy=true
    - --authorization-mode=RBAC
    - --anonymous-auth=true
    - --authentication-token-webhook-cache-ttl=30m0s
    - --authentication-token-webhook-config-file=/etc/kubernetes/webhook.yaml
    - --experimental-bootstrap-token-auth=true
```
Here is the parameter used to launch controller-manager:
```
containers:
  - name: kube-controller-manager
    image: quay.io/coreos/hyperkube:v1.6.2_coreos.0
    command:
    - /hyperkube
    - controller-manager
    - --master=https://127.0.0.1
    - --leader-elect=true
    - --cloud-provider=aws
    - --service-account-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --root-ca-file=/etc/kubernetes/ssl/ca.pem
    - --controllers=*,tokencleaner,bootstrapsigner
    - --use-service-account-credentials=true
    - --kubeconfig=/etc/kubernetes/ssl/kube-config.yaml
```
**What you expected to happen**:
regular user are not allowed to do a deployment with hostPath volume
ops team members are able to do a deployment with hostPath volume

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
