### ISSUE TITLE
Pods in StatefulSets cannot resolve each other by expected hostnames

### ISSUE THREAD

**Issue by dlmiddlecote** [kubernetes/kubernetes#45779]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): Yes

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): StatefulSets, DNS (Found some issues, but all with resolutions I have tried)

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```
$ uname -a
Linux motest-7 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 
```
- **Install tools**:
- **Others**:

**What happened**:
Created StatefulSet with 2 replicas, and a headless service to allow access to them. The Pods have the expected hostname, but they are unable to resolve each others hostnames.

Here is the StatefulSet and Service definitions:
```
apiVersion: v1
kind: Service
metadata:
  name: oklog-store
  labels:
    app: oklog-store
spec:
  ports:
    - name: store-api
      port: 12050
      targetPort: 12050
      protocol: TCP
    - name: store-cluster
      port: 12059
      targetPort: 12059
      protocol: TCP
  clusterIP: None
  selector:
    app: oklog-store
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: oklog-store
spec:
  serviceName: "oklog-store"
  replicas: 2
  template:
    metadata:
      labels:
        app: oklog-store
    spec:
      containers:
        - name: oklog-store
          image: docker.registry.lohs.geneity/dmiddlec/oklog-dmiddlec:test
          imagePullPolicy: Always
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - "/bin/sh"
            - "-c"
            - |
              exec oklog store -debug -cluster tcp://$POD_IP:12059 \
                -api tcp://0.0.0.0:12050 \
                -peer oklog-ingest-0.oklog-ingest.$POD_NAMESPACE.svc.cluster.local:12059 \
                -peer oklog-ingest-1.oklog-ingest.$POD_NAMESPACE.svc.cluster.local:12059 \
                -peer oklog-ingest-2.oklog-ingest.$POD_NAMESPACE.svc.cluster.local:12059 \
                -peer oklog-ingest-3.oklog-ingest.$POD_NAMESPACE.svc.cluster.local:12059 \
                -peer oklog-store-0.oklog-store.$POD_NAMESPACE.svc.cluster.local:12059 \
                -peer oklog-store-1.oklog-store.$POD_NAMESPACE.svc.cluster.local:12059
          ports:
            - name: store-api
              containerPort: 12050
            - name: store-cluster
              containerPort: 12059
      terminationGracePeriodSeconds: 10
      nodeSelector:
        oklog: not-active
```
Note: `clusterIP: None` (this seems to be the resolution to this issue in all the other found cases).

Inside oklog-store-0
```
root@oklog-store-0:/# hostname -f
oklog-store-0.oklog-store.ci.svc.cluster.local
root@oklog-store-0:/# nslookup oklog-store.ci.svc.cluster.local
Server:         192.168.0.10
Address:        192.168.0.10#53

Name:   oklog-store.ci.svc.cluster.local
Address: 172.16.81.9
Name:   oklog-store.ci.svc.cluster.local
Address: 172.16.29.13
root@oklog-store-0:/# nslookup oklog-store-1.oklog-store.ci.svc.cluster.local
Server:         192.168.0.10
Address:        192.168.0.10#53

** server can't find oklog-store-1.oklog-store.ci.svc.cluster.local: NXDOMAIN

root@oklog-store-0:/# nslookup oklog-store-1
Server:         192.168.0.10
Address:        192.168.0.10#53

** server can't find oklog-store-1: SERVFAIL
root@oklog-store-0:/# nslookup -q=SRV oklog-store.ci.svc.cluster.local
Server:         192.168.0.10
Address:        192.168.0.10#53

oklog-store.ci.svc.cluster.local        service = 10 50 0 12c78c01.oklog-store.ci.svc.cluster.local.
oklog-store.ci.svc.cluster.local        service = 10 50 0 4749ebd6.oklog-store.ci.svc.cluster.local.
root@oklog-store-0:/# nslookup 12c78c01.oklog-store.ci.svc.cluster.local
Server:         192.168.0.10
Address:        192.168.0.10#53

Name:   12c78c01.oklog-store.ci.svc.cluster.local
Address: 172.16.29.13

root@oklog-store-0:/# nslookup 4749ebd6.oklog-store.ci.svc.cluster.local
Server:         192.168.0.10
Address:        192.168.0.10#53

Name:   4749ebd6.oklog-store.ci.svc.cluster.local
Address: 172.16.81.9
```
Note: `nslookup 'domain'` returns both records as expected.
Note: The pods are available, just with unexpected hostnames.
**What you expected to happen**:

`nslookup oklog-store-1.oklog-store.ci.svc.cluster.local` to resolve to the correct IP address.

**How to reproduce it** (as minimally and precisely as possible):
Use the given versions, and use the given `.yaml` to load a StatefulSet and a 'headless' Service.

**Anything else we need to know**:

**Comment by kargakis** [comment]
@kubernetes/sig-apps-bugs

**Comment by dlmiddlecote** [comment]
Solved: running an old version of kube-dns

**Comment by dlmiddlecote** [comment]
Solved: running an old version of kube-dns

**Comment by isaldarriaga** [comment]
I'm experiencing exactly the same problem. 
- Deployed on GKE. 
- Client: Ubuntu 16.04 LTS

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl describe po kube-dns --namespace=kube-system | grep Image:

Image:		gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1
Image:		gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.1
Image:		gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.1
...

So the kube-dns 1.14.1 is running.

Looking into that [repo](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/k8s-dns-kube-dns-amd64) there is a new version available: 1.14.2

How can be upgraded? and did 1.14.2 solve your problem @dlmiddlecote ?.

Thanks.

**Comment by isaldarriaga** [comment]
SOLVED:
The spec.serviceName field in the statefulSet manifest was wrong. It should match the metadata.name field in the headless service definition.

For anyone interested on debugging kube-dns; https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by yevgeniyo** [comment]
hi, is it possible upgrade just kube-dns?
does 1.14.2 resolved this issue?

**Comment by thedodd** [comment]
I am running into this issue on GKE @ `1.8.5-gke.0`. StatefulSet's `spec.serviceName` matches the service's `metadata.name`. No other issues. Simply can not resolve specific statefulset memeber's DNS name.

```
# This works:
root@rabbitmq-1:/# nslookup rabbitmq
Server:		10.120.240.10
Address:	10.120.240.10#53

Name:	rabbitmq.default.svc.cluster.local
Address: 10.120.248.234

# This does not:
root@rabbitmq-1:/# nslookup rabbitmq-0
Server:		10.120.240.10
Address:	10.120.240.10#53

** server can't find rabbitmq-0: NXDOMAIN
```

```bash
# Pods:
kubectl get pods
NAME                                     READY     STATUS    RESTARTS   AGE
rabbitmq-0                               1/1       Running   0          9m
rabbitmq-1                               1/1       Running   0          9m
```

**Comment by kuznero** [comment]
Same here, fields match, but DNS still does not work

**Comment by alahijani** [comment]
@thedodd @kuznero

The service has to be headless (`clusterIP: None`) for the pod DNS entries to work.
Check https://github.com/kubernetes/kubernetes/issues/39197

**Comment by geigev** [comment]
@thedodd @kuznero @alahijani 

I had the exact same issue with `clusterIP: None` set. Turned out my issue was that I had my service selector wrong i.e

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    name: nginx
```
should have been

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
```

Might want to check that.

**Comment by jonasdkhansen** [comment]
I'm having similar issues with statefulset and headless service with clusterip: none, on Kubernetes 1.10.1. I can get the pods to resolve on pod-0.service.namespace.svc.cluster.local, but they will not listen to pod-0, only if it's inside pod-0. So i can't use the short hostnames execpt inside them selves.

**Comment by jnicholls** [comment]
Just FYI an upgrade from 1.10.1 to 1.10.6 did not help.

**Comment by detohm** [comment]
@jnicholls please ensure you specify the correct `spec.selector` in the headless service definition. 

I myself got the same issue and found out that the culprit was the missing `spec.selector` in headless service definition. Even all the pods were up but it could not reach other pod via hostname with service name. (Ex. pod-0.headless-service-name.default.svc.cluster.local)

**Comment by jonasdkhansen** [comment]
@jnicholls did spec.selector fix the problem ?

**Comment by PicoCreator** [comment]
Note this does not seem to be working in `1.11` either - checked `spec.selector` and `clusterIP`.

Side note - is it a regression on the following? : https://github.com/kubernetes/kubernetes/issues/57671

**Comment by jnicholls** [comment]
@jonasdkhansen No it did not :( both spec.selector and spec.clusterIP are set properly in my headless service definition.

**Comment by jnicholls** [comment]
@jonasdkhansen Nope I lied, it works fine. Ugh.

**Comment by MPV** [comment]
I'm getting this issue too using the `incubator/etcd` chart (`v0.4.1`):
https://github.com/helm/charts/tree/master/incubator/etcd

I've checked:
✅ Service is headless: has [`clusterIP: None`](https://github.com/helm/charts/blob/dc67b78/incubator/etcd/templates/service.yaml#L19).
✅ Service [`spec.selector`](https://github.com/helm/charts/blob/dc67b78/incubator/etcd/templates/service.yaml#L20-L22) matches StatefulSet [`metadata.labels`](https://github.com/helm/charts/blob/dc67b785bfd7608515c6e494d99c147d9860b04b/incubator/etcd/templates/statefulset.yaml#L5-L9).

**Comment by jnicholls** [comment]
@MPV The `metadata.name` of the headless service also needs to match the `spec.serviceName` of the StatefulSet.

**Comment by MPV** [comment]
@jnicholls Thanks. 

Yep, as you noticed:
✅ The Service [`metadata.name`](https://github.com/helm/charts/blob/dc67b78/incubator/etcd/templates/service.yaml#L7) matches the StatefulSet [`spec.serviceName`](https://github.com/helm/charts/blob/dc67b785bfd7608515c6e494d99c147d9860b04b/incubator/etcd/templates/statefulset.yaml#L11).

**Comment by jaceq** [comment]
I had same issue, in my case selector on headless service was wrong. Do you guys see all pods in headless service?

**Comment by Freyert** [comment]
### Solved

Turns out I had the FQDN pattern incorrect. (Not only can you get the Service, and the Service Selector wrong, but you can also do this.)

I was using: `hidden-secondary-mongo-hidden-secondary-0.hidden-secondary.svc.cluster.local`

Which is the pattern: `<pod>-<N>.<namespace>.svc.cluster.local`

When I should have used:

`hidden-secondary-mongo-hidden-secondary-0.hidden-secondary-mongo-hidden-secondary.hidden-secondary.svc.cluster.local`

Which is the pattern:

`<pod>-<N>.<statefulSetName>.<namespace>.svc.cluster.local`


The table found [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) can be tremendously helpful.

Suffice to say, some names will become shorter.

**Comment by hustshawn** [comment]
> ### Solved
> Turns out I had the FQDN pattern incorrect. (Not only can you get the Service, and the Service Selector wrong, but you can also do this.)
> 
> I was using: `hidden-secondary-mongo-hidden-secondary-0.hidden-secondary.svc.cluster.local`
> 
> Which is the pattern: `<pod>-<N>.<namespace>.svc.cluster.local`
> 
> When I should have used:
> 
> `hidden-secondary-mongo-hidden-secondary-0.hidden-secondary-mongo-hidden-secondary.hidden-secondary.svc.cluster.local`
> 
> Which is the pattern:
> 
> `<pod>-<N>.<statefulSetName>.<namespace>.svc.cluster.local`
> 
> The table found [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) can be tremendously helpful.
> 
> Suffice to say, some names will become shorter.

The official example in this [doc](url) just not work

**Comment by AlexProfi** [comment]
What version of kubernetes have fixed it? I used 1.11.5 And it works correct when I set
redis-cluster-1.redis-cluster.default.svc.cluster.local
with redis-cluster-1 it doesn't work

**Comment by matti** [comment]
for me `redis-cluster-1.redis-cluster` works, but not `redis-cluster-1`

**Comment by xpetoox** [comment]
Hello guys, same issue here. K8s version 1.11.5 and also 1.12.6, StatefulSet with headless service can resolve long hostnames but can't resolve the short one. Is this a bug, feature or can be a problem with configuration?
Any help appreciated.. Need this to work (or workaround) for one of the Oracle apps (running on Docker it self just fine, issues only on K8s). Thank you.

Peter

**Comment by matti** [comment]
@xpetoox what is a "short one"

**Comment by jnicholls** [comment]
For me, I think the resolution for the shorthand format (no namespace.svc.cluster.local) only worked inside of pods within the statefulset, not pods outside of it. I could be mistaken as it’s been months since I’ve had similar issues and am only recalling off the top of my head.

**Comment by xpetoox** [comment]
> 
> 
> @xpetoox what is a "short one"

I mean, it can resolve the long hostname (example: web-0.nginx.foo.svc.cluster.local) but can't resolve the short hostname (example: web-0).

**Comment by xpetoox** [comment]
> 
> 
> For me, I think the resolution for the shorthand format (no namespace.svc.cluster.local) only worked inside of pods within the statefulset, not pods outside of it. I could be mistaken as it’s been months since I’ve had similar issues and am only recalling off the top of my head.

Yes, this is how it's behave right now. But my application need also short hostname resolvable between different pods. How can I achieve that?

P.

**Comment by matti** [comment]
you have to use `podname-0.namespace`, `podname-0` won't resolve (by design)

**Comment by xpetoox** [comment]
> 
> 
> you have to use `podname-0.namespace`, `podname-0` won't resolve (by design)

..and that's the problem that I have.. application that I try to run in k8s use combination of FDQN and hostname by design.. I can't change this behavior so I need to figure out how k8s can support this requirement..

**Comment by matti** [comment]
custom dns record? a service with endpoints?

**Comment by whs-dot-hk** [comment]
Hi, the environment variable HOSTNAME is the pod name e.g. nifi-0

makes it impossible to resolve similarly pods of the same statefulset with just the HOSTNAME e.g. nifi-1 can't access nifi-0 pod by it's HOSTNAME nifi-1

It would be more helpful to make the HOSTNAME nifi-0.nifi-headless and nifi-1.nifi-headless

where nifi-headless is their common headless service name

**Comment by xxwassyxx** [comment]
So this is actually what I ended up doing. I have the same situation where my app saw the hostname, being the shortname not FQDN. When I tried to join the nodes, being 3, it complained that the dns I told it to use was a FQDN, yet the hostname is not and denied joining. My resolution was as follows

```
- name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOSTNAME
              value: {{ printf "$(MY_POD_NAME).%s.%s.svc.cluster.local" .Release.Name .Release.Namespace }}
```
Keep in mind mine is actually using helm and thats why you see the code for interpolation. Basically from what I found is setting an env variable MY_POD_NAME worked, but bash could not expand it? Even tho if I literally copy pasted the same thing it would work. I then found that if you use round brackets k8 would actually expand the variable and hey presto the hostname was now the FQDN and my app was happy.

**Comment by jerem991** [comment]
You can resolve this issue specifying in your configuration a **dnsConfig** with a **search** entry:
rabbit-service.your_namespace.svc.cluster.local

**Comment by tsuz** [comment]
You need set `serviceName` so that it's the same name as the `kind: Service`

```
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: myapp
---
# curl myapp-0.myapp.test.svc.cluster.local
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  serviceName: "myapp"
```

Full yaml file:


<summary>Full file</summary>

<details>

```
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: myapp
---
# curl myapp-0.myapp.test.svc.cluster.local
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp
spec:
  serviceName: "myapp"
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/data/stream
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: my-sc
      resources:
        requests:
          storage: 20Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
reclaimPolicy: Delete
# reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

```

</details>
