### ISSUE TITLE
AzureFile doesn't mount in pod.

### ISSUE THREAD

**Issue by chrismcv** [kubernetes/kubernetes#45827]
**Kubernetes version** (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform
:"linux/amd64"}
```

**Environment**:
- Azure ACS: default install
```
az acs create --orchestrator-type=kubernetes \
              --resource-group my-test-group \
              --name my-test-k8s-cluster \
              --dns-prefix my-test-k8s-cluster \
              --generate-ssh-keys
```

**What happened**:
Azure File Volume mounts don't work.

**What you expected to happen**:
A mount with my files from Azure Files

**How to reproduce it** (as minimally and precisely as possible):
(Assumes you have the azure cli)

Create storage
```
az storage account create -n teststorageaccount -g my-test-group -l northeurope --sku Standard_LRS
az storage share create --name az-files--account-name teststorageaccount 
```
Create a secret: (check `$name`) for trailing `=` being missing
```
name=$(echo teststorageaccount | base64 -w 0)
key=$(az storage account keys list --account-name=teststorageaccount -g my-test-group --output tsv --query "[1].value" | base64 -w 0)

cat  << EOF
{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "azure-files-secret"
  },
  "type": "Opaque",
  "data": {
    "azurestorageaccountname": "$name",
    "azurestorageaccountkey": "$key"
  }
}
EOF
```

Build PV/PVC/Pod
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: azure-files-secret
    shareName: az-files
    readOnly: false
  claimRef:
    namespace: default
    name: az-files
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: az-files
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; ls /mnt; done;" ]
    volumeMounts:
      - mountPath: "/mnt"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: az-files
```

Error:
```
MountVolume.SetUp failed for volume "kubernetes.io/azure-file/254274c6-397e-11e7-8027-000d3ab0e16a-pv001" (spec.Name: "pv001") pod "254274c6-397e-11e7-8027-000d3ab0e16a" (UID: "254274c6-397e-11e7-8027-000d3ab0e16a") with: mount failed: exit status 32 Mounting command: mount Mounting arguments: //teststorageaccount.file.core.windows.net/az-files /var/lib/kubelet/pods/254274c6-397e-11e7-8027-000d3ab0e16a/volumes/kubernetes.io~azure-file/pv001 cifs [vers=3.0,username=teststorageaccount,password=Removed ,dir_mode=0777,file_mode=0777] Output: mount error(13): Permission denied Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"ubuntu". list of unattached/unmounted volumes=[mypd]
```

If I navigate to 
`/var/lib/kubelet/pods/254274c6-397e-11e7-8027-000d3ab0e16a/volumes/kubernetes.io~azure-file/` on the appropriate agent vm. The folder `pv001` doesn't exist, I manually created it (as `su`) and then I tried to mount. It succeeded. I think either the mount point is not being created by the azure file plugin, or the permissions on it are incorrect.

**Comment by imogenthomson** [comment]
I'm having the same to you.

However when I create the folder manually, it does not succeed. Were there any other steps you took to get it to succeed manually?

**Comment by erictune** [comment]
@kubernetes/sig-node-bugs can you please file another issue based on above to not log the error message that includes a password=blah in it.

**Comment by gjoris** [comment]
Any progress or workaround for this? Bumped into this too ...

**Comment by chrismcv** [comment]
Not really... I'm currently using a Ubuntu VM and sharing an NFS folder out from it, and then rsync-ing to AzureFiles mounted in the same VM. Pretty rubbish workaround. (You can't share the AzureFiles out over NFS directly.) I've a ticket open with Microsoft, but I don't think they've tried to reproduce it themselves yet, as the questions I've received imply they still don't quite believe me.

**Comment by jpoon** [comment]
Hmm, I just deployed a cluster and attached an AFS without issues. The only difference is I did:

`echo -n <my-storage-account> | base64`  and the same for the account key.

**Comment by chrismcv** [comment]
I'm using the following `sh` script to generate my secret.... That would be doing the same thing as you?

```
source ../globals.sh
name=$(echo $storage| base64 -w 0)
key=$(az storage account keys list --account-name=$storage -g $group --output tsv --query "[1].value" | base64 -w 0)

cat  << EOF
{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "azure-vpn-files-secret"
  },
  "type": "Opaque",
  "data": {
    "azurestorageaccountname": "$name",
    "azurestorageaccountkey": "$key"
  }
}
EOF
```

**Comment by jpoon** [comment]
I mean, the `-n` flag is the difference in my case. Can you try with that? `echo -n $storage`.

**Comment by chrismcv** [comment]
sorry - pasted wrong script in... yes, tried `-n` no luck.

**Comment by gjoris** [comment]
I'm with @chrismcv , also tried the ```echo -n```, but no luck at all. 

And it must be a Kubernetes thing: I'm running an Elastic Stack in Kubernetes, and the azure-repository plugin for Elasticsearch works perfectly: it can write without any issue to the Azure File storage. FYI, I'm running on Kubernetes 1.5.3 on Azure.

**Comment by jpoon** [comment]
Tried on a 1.5.3 cluster and it works fine for me.

1. Deployed 1.5.3 using ACS 
```
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", 
GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", 
GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", 
GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
2. Created an azure storage account and a new file share titled `testFileShare`
3. Created the k8s secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: <name> 
  azurestorageaccountkey: <key>
```

where the <name/key> values were generated from `echo -n <name/key> | base64`

4. Created a Pod that used the fileshare

```
apiVersion: v1
kind: Pod
metadata:
 name: nginx
spec:
 containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
 volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: testFileShare
          readOnly: false
```

5. I see that the pod runs successfully and after with `kubectl exec -it nginx bash`, I see `/mnt/azure` and files that I add there I see on the portal (aka. it works).
