### ISSUE TITLE
Add multipath iscsi support for multiple initiator logins

### ISSUE THREAD

**Issue by mleklund** [kubernetes/kubernetes#46041]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**Kubernetes version** (use `kubectl version`):v1.6.3

**Environment**:
- **Cloud provider or hardware configuration**:Bare metal
- **OS** (e.g. from /etc/os-release):Ubuntu 16.04
- **Kernel** (e.g. `uname -a`):4.4.0-78-generic
- **Install tools**: kubeadm
- **Others**:

**What happened**:
My Iscsi equipment expects to load balance connections for you, so multipath is handled with multiple interface connections on the client side.  It appears the iscsi go code is calling iscsiadm with specific interface options which connect to the single portal with a single interface.

**What you expected to happen**:
I would like the option of having iscsi commands to make calls either omitting the interface (-I option) completely, in which case open iscsi does the right thing, or allow for iscsi commands run against multiple interfaces

allowing something like this:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: X.X.X.X:3260
      iscsiInterface: [eno3,eno4]
      iqn: iqn.2001-05.com.equallogic:X-XXXXXX-XXXXXXXXX-XXXXXXXXXXXXXXXX-kubetesting
      lun: 0
      fsType: ext4
      readOnly: false
```
or 
```
---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: X.X.X.X:3260
      iscsiInterface: none
      iqn: iqn.2001-05.com.equallogic:X-XXXXXX-XXXXXXXXX-XXXXXXXXXXXXXXXX-kubetesting
      lun: 0
      fsType: ext4
      readOnly: false
```
where none some better named keyword would cause the omission of the -I option

**Comment by mleklund** [comment]
as a work around I have done this:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: X.X.X.X:3260
      iscsiInterface: eno3
      iqn: iqn.2001-05.com.equallogic:X-XXXXXX-XXXXXXXXX-XXXXXXXXXXXXXXXX-kubetesting
      lun: 0
      fsType: ext4
      readOnly: false
  - name: iscsipd-2-rw
    iscsi:
      targetPortal: X.X.X.X:3260
      iscsiInterface: eno4
      iqn: iqn.2001-05.com.equallogic:X-XXXXXX-XXXXXXXXX-XXXXXXXXXXXXXXXX-kubetesting
      lun: 0
      fsType: ext4
      readOnly: false
```

but am having the logout issue from https://github.com/kubernetes/kubernetes/issues/45394

**Comment by humblec** [comment]
` It appears the iscsi go code is calling iscsiadm with specific interface options which connect to the single portal with a single interface.` -> this is not correct. Atm, iscsi code use the multiple target Ips and login to those to achieve multipathing.

**Comment by mleklund** [comment]
True that is badly worded.  iscsi code expects that in the case of multipath you would have multiple targets on separate networks, not multiple connections to the same network.  My particular iscsi equipment expects the latter, and expects that you will make multiple connections to the same portal.  The equipment then load balances these connections to other interfaces. 

To the point, the iscsiadm calls are being called either with `-I iface` which directs the initiator to log into a portal with a single interface, either `default` or a specified interface.  In my case I need to make multiple connections to a single portal with multiple interfaces.  So I either need iscsiInterface to be an array, or I need the ability to omit the `-I iface` from the iscsiadm call.

**Comment by mleklund** [comment]
Multiple interface connections is also used, at times for increased bandwidth.

**Comment by fabiand** [comment]
Isn't this bug fixed by https://github.com/kubernetes/kubernetes/commit/332e26dc8c09cd4cb9777fee881c49f258522355 ?

**Comment by mleklund** [comment]
No that bug fix allows for connections to multiple portals on differning network segments from multiple interfaces on corresponding network segments.  What I need to be able to do is connect to a single portal with multiple interfaces on the same network segment. 

This is needed to work with equallogic san equipment.

**Comment by mtanino** [comment]
@mleklund @humblec @rootfs 

This seems interesting feature but needs design discussion.
From above example, volume yaml specifies physical interface name enX directly into the iscsiInterface but actually user doesn't know what kind of network interface can be available on the worker node.
I think we shouldn't permit this kind of parameter for user.

There is ongoing effort to discover host devices such as NIC, GPUs etc, we might apply this device discovery feature to this PR.
https://github.com/kubernetes/community/pull/695/files

Any thought?

**Comment by mleklund** [comment]
In the case of the equallogic equipment, it is also viable to not specify an interface when logging in.  The kubernetes code is using a provided interface name, or `default`.  With openiscsi it is perfectly legal to not specify an interface at all, and openiscsi will login to the portal will all available interfaces on the same network segments as the portal.  This means discoveries and logout should also be run without an interface specification.  Something like the following would also work for my case:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/mnt/iscsipd"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: X.X.X.X:3260
      sendInterface: false
      iqn: iqn.2001-05.com.equallogic:X-XXXXXX-XXXXXXXXX-XXXXXXXXXXXXXXXX-kubetesting
      lun: 0
      fsType: ext4
      readOnly: false
```

It seems to me that if someone is using iscsi on kubernetes the networking requirements are going to have to be met at the time of node setup, and someone running on those nodes will have to have some understanding of underlying architectures. These things are physical components in the physical world and sometimes cannot be abstracted out.
