### ISSUE TITLE
GKE Pod can't ping instance on AWS VPC wired by VPN

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/kubernetes#46170]
Hi,

I have a VPN between my GKE VPC and a AWS VPC, the vpn uses BGP.
I'm trying to connect from a pod inside GKE to a elasticsearch running on AWS side.

From my tests:

* curl from GKE kubernetes node to elasticsearch node on AWS works
* curl from GKE Pod running on same node to elasticsearch node on AWS does not work (neither ping)
* ping from gke pod to ec2 instance can be seen if I ```tcpdump -n icmp``` inside aws instance, i guess what's not working is the trip back to the container
* ping from aws instance to pod ip does not reach pod's host instance on GKE (nothing on tcpdump -n icmp)

there are no ip range overlaps:
aws vpc is on 10.0.0.0/16
gke vpc is on 10.128.0.0/16
gke pod ip range is on 10.4.0.0/14

may this is related to #6545?

**edit:**

so, taking a better look on #6545, if I add
```
sudo iptables -t nat -A POSTROUTING ! -d 10.4.0.0/14 -o eth0 -j MASQUERADE
```
in the node, it works! (pod can ping instance on amazon VPC and receive reply from it) still it seems a little "dirty" to inject such thing in the node.

are there any better options?

**Comment by felipejfc** [comment]
I ended up solving it using iptables + daemonset.

if anyone is interested in the solution, take a look: https://github.com/felipejfc/loop-script

**Comment by romankonz** [comment]
Hi,

i've used a solution similar to the solution of @felipejfc.
The daemonset container runs the iptables rule, and also recognizes that the rule is applied.

But on the node, the rule is not visible/does not work.
Do i need any additional security-context?

Configuration:
```yaml
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: gcp-firewall-fix
  namespace: kube-system
  labels:
    app: gcp-firewall-fix
spec:
  template:
    metadata:
      labels:
        app: gcp-firewall-fix
    spec:
      hostPID: true
      containers:
        - name: gcp-firewall-fix
          image: gcr.io/myproject-production/k8s-daemon-sets-firewall-fixer:master-latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
```

Bash Scrpt:
```bash
#!/bin/bash
while true
do
    iptables -t nat -C POSTROUTING ! -d 10.24.0.0/14 -o eth0 -j MASQUERADE
    if [ $? -ne 0 ]; then
        echo "fixing routing with iptables -t nat -A POSTROUTING ! -d 10.24.0.0/14 -o eth0 -j MASQUERADE"
        iptables -t nat -A POSTROUTING ! -d 10.24.0.0/14 -o eth0 -j MASQUERADE
    fi
	sleep 10
done
```
