### ISSUE TITLE
Identify original service port in a pod

### ISSUE THREAD

**Issue by minherz** [kubernetes/kubernetes#46180]
It is possible to define multiple ports for a single service e.g.:
```
ports:
      - name: gate1
        protocol: TCP
        port: 4040
        targetPort: 9100
      - name: gate2
        protocol: TCP
        port: 4041
        targetPort:9101
```
Given that I configure my pods that are matched to the service to run in a port range 9100:9199, is it possible to learn that the communication arrived at port 4040 (gate1) or 4041 (gate2)?
