### ISSUE TITLE
GlusterFS volumes don't remount into pods

### ISSUE THREAD

**Issue by cjyar** [kubernetes/kubernetes#46253]
**Is this a request for help?**:

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kubernetes glusterfs "Transport endpoint is not connected"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0", GitCommit:"8996efde382d88f0baef1f015ae801488fcad8c4", GitTreeState:"clean", BuildDate:"2017-05-19T21:11:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: bare metal, 3 controller nodes and 5 workers
- **OS** (e.g. from /etc/os-release): Container Linux 1353.7.0
- **Kernel** (e.g. `uname -a`): 4.9.24-coreos
- **Install tools**:
- **Others**:
  - GlusterFS 3.10.1
  - Heketi v4.0.0-8-g9372c22-release-4
  - Running kubectl from systemd, without `KillMode=process`.

**What happened**:
When kubelet restarts, GlusterFS fuse processes are killed by systemd. Kubelet restarts them, but the volumes become inaccessible inside their pods.

**What you expected to happen**:
If a volume is inaccessible, any pods that require it should be terminated. Conversely, if a pod is running, all its volumes should be accessible.

**How to reproduce it** (as minimally and precisely as possible):
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: test1
  name: test1
spec:
  template:
    metadata:
      labels:
        run: test1
    spec:
      containers:
      - image: debian
        name: test1
        stdin: true
        tty: true
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: myclaim
```

Use `kubectl exec $POD -- df -h /data` to diagnose whether the filesystem is visible inside the pod. Watch for "Transport endpoint is not connected."

1. `systemctl restart kubelet` on the node. Watch the glusterfs process disappear, then get re-created. Test with df inside the pod, and see it fail.
2. `kubectl exec $POD -- kill 1` to restart the pod. Test again with df, and see it succeed.

**Anything else we need to know**:

See #13511 for related info on systemd killing glusterfs processes along with kubelet.
