### ISSUE TITLE
Federation cluster scripts accidentally delete PV's.

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/kubernetes#46380]
We have a PVC that uses the alpha annotation to dynamically provision a GCE PD/PV. Sometimes in our test environment, the dynamically provisioned PV gets automatically deleted by the PV controller without any of us deleting the PVC. I am attaching the controller manager logs here: [kube-controller-manager.log-20170523-1495580401.gz](https://github.com/kubernetes/kubernetes/files/1026899/kube-controller-manager.log-20170523-1495580401.gz)

Interesting bits in the logs start at:

```
I0523 22:08:01.117123       5 gce_util.go:122] Successfully created GCE PD volume jenkins-us-central1-f--pvc-4723f163-4004-11e7-a75a-42010a80000a
```

The namespaced name of the claim is `f8n-system-agent-pr-93-0/e2e-f8n-agent-pr-93-0-apiserver-etcd-claim`

Here is the deployment yaml

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    federation.alpha.kubernetes.io/federation-name: e2e-f8n-agent-pr-93-0
  labels:
    app: federated-cluster
  name: e2e-f8n-agent-pr-93-0-apiserver
  namespace: f8n-system-agent-pr-93-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: federated-cluster
      module: federation-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        federation.alpha.kubernetes.io/federation-name: e2e-f8n-agent-pr-93-0
      creationTimestamp: null
      labels:
        app: federated-cluster
        module: federation-apiserver
      name: e2e-f8n-agent-pr-93-0-apiserver
    spec:
      containers:
      - command:
        - /hyperkube
        - federation-apiserver
        - --admission-control=NamespaceLifecycle
        - --advertise-address=104.154.166.121
        - --basic-auth-file=/etc/federation/apiserver/basicauth.csv
        - --bind-address=0.0.0.0
        - --client-ca-file=/etc/federation/apiserver/ca.crt
        - --etcd-servers=http://localhost:2379
        - --secure-port=8443
        - --tls-cert-file=/etc/federation/apiserver/server.crt
        - --tls-private-key-file=/etc/federation/apiserver/server.key
        - --token-auth-file=/etc/federation/apiserver/token.csv
        - --v=4
        image: gcr.io/k8s-jkns-pr-bldr-e2e-gce-fdrtn/hyperkube-amd64:v1.7.0-alpha.4.362_c5319821fe72fa
        imagePullPolicy: IfNotPresent
        name: apiserver
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        - containerPort: 8080
          name: local
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/federation/apiserver
          name: e2e-f8n-agent-pr-93-0-apiserver-credentials
          readOnly: true
      - command:
        - /usr/local/bin/etcd
        - --data-dir
        - /var/etcd/data
        image: gcr.io/google_containers/etcd:3.0.17
        imagePullPolicy: IfNotPresent
        name: etcd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/etcd
          name: etcddata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: e2e-f8n-agent-pr-93-0-apiserver-credentials
        secret:
          defaultMode: 420
          secretName: e2e-f8n-agent-pr-93-0-apiserver-credentials
      - name: etcddata
        persistentVolumeClaim:
          claimName: e2e-f8n-agent-pr-93-0-apiserver-etcd-claim
```

cc @kubernetes/sig-storage-bugs @saad-ali @kubernetes/sig-federation-bugs

**Comment by madhusudancs** [comment]
PVC

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    federation.alpha.kubernetes.io/federation-name: e2e-f8n-agent-pr-93-0
    volume.alpha.kubernetes.io/storage-class: "yes"
  labels:
    app: federated-cluster
  name: e2e-f8n-agent-pr-93-0-apiserver-etcd-claim
  namespace: e2e-f8n-agent-pr-93-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```
