### ISSUE TITLE
How to let pods spread by IDC(like label in idc1,idc2,idc3...,but must in idc1/idc2/idc3 at the same time)

### ISSUE THREAD

**Issue by jmzwcn** [kubernetes/kubernetes#46568]
Dear all,

Please help/advice. Anybody know how to let pods within a deployment spread by IDC(e.g label in idc1,idc2,idc3...)?

Expected result is we must have pods in different IDCs.

Regards,

**Comment by k82cn** [comment]
@jmzwcn , we have `SelectorSpreadPriority` which will try to place Pod cross nodes; but it's not hard restrictions. And DaemonSet can help to start one node on each hosts (with conditions).

> Expected result is we must have pods in different IDC.

Do you mean each IDC must have some pods, e.g. at least 3 Pods in each IDC? Is it a exactly number or a range?

@kubernetes/sig-scheduling-feature-requests

**Comment by gyliu513** [comment]
I think this is a new feature request: AntiAffinity for a deployment.

Even though the `daemonset` is kind of anti-affinity, but there are two issues for daemonset.
1) When a new node joined, the daemonset will automatically create new pod which is not expected. As for the application developer, I only want my application have anti affinity at deploy time and do not want to scale the application when new node joins.
2) daemonset is only host level resource and we cannot define different level for daemonset, such as rack, zone etc.

Also, the current inter-pod affinity/anti-affinity also cannot fill this requirement, as it only works for new pods with current exist pods. i.e. I can create pods which have affinity/anti-affinity relationship with current existing pods.

**Comment by jmzwcn** [comment]
SelectorSpreadPriority should to be based on node(spread by nodes), but we need it spread by IDC(a group node label). The aim is we have one pod in each IDC at least.

**Comment by k82cn** [comment]
yes; both `SelectorSpreadPriority` and `DaemonSet` are node level. And here are the options in my mind:

1. Pod AntiAffinity: the first pod will start on one IDC, the second will select other IDC because of anti-affinity, then the third one in different IDC with previous two Pods .... The issue of that option is: there's at most one Pod in IDC; there's an open PR (#41718) to make more than one pod in IDC (topologyKey).
1. `SelectorSpreadPriority`, if there's enough Pods, it may select other IDC after fullfill the first one, but it's not guaranteed as it's preferred (priority) not restriction (predicates); and we can enhance it to be IDC (topologyKey) level
1. `DaemonSet`, it'll start one Pod on each host (with conditions), so each IDC will have at least one Pods. But as you said, your case may prefer to deployment, right?

**Comment by jmzwcn** [comment]
My thought is we could enhence nodeAffinity's IN operation, such as introducing  'AND', means this deployment must be placed into IDC1 and IDC2 and IDC3...

**Comment by k82cn** [comment]
Would you try Pod AntiAffinity firstly? :).

**Comment by jmzwcn** [comment]
No, enhancement to SelectorSpreadPriority and nodeAffinity's IN(will be changed AND) operation. any suggestion?

**Comment by gyliu513** [comment]
The `IN` already support array, but it still cannot guarantee the anti affinity.

```yaml
requiredDuringSchedulingIgnoredDuringExecution:
  nodeSelectorTerms:
  - matchExpressions:
    - key: kubernetes.io/e2e-az-name
      operator: In
      values:
      - e2e-az1
      - e2e-az2
```

+1 to enhance node affinity to support the anti affinity for a whole deployment.

**Comment by k82cn** [comment]
`SelectorSpreadPriority` is kind of "preferred", it will not guarantee each IDC has Pods; the scheduler will calculate priority of Node and assign Pods to the Node with highest priority, "SelectorSpreadPriority" is only one of priority factor.

`nodeAffinity's label in(AND)`, it's hard for k8s to decide how many Pods should be placed in IDC if the number of replicas & IDC is different. Round-robin? I think that back to a kind of Pod Anti-Affinity that: if this IDC has "more" Pods, place Pod to next IDC.

Any block case for you to try Pod AntiAffinity? One case I can image is that: if replicas is bigger than number of IDC, Pod AntiAffinity will make some Pods pending after all IDC has pods.

**Comment by kevin-wangzefeng** [comment]
Actually Pod AntiAffinity has a soft option, see "podAntiAffinity" and "preferredDuringSchedulingIgnoredDuringExecution" in https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/node-selection/pod-with-pod-affinity.yaml.
And to make sure the pods are spread appropriately as expected, you may indicate a really high weight of the algorithm "InterPodAffinityPriority".
see also https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduler_extender.md

**Comment by k82cn** [comment]
wow, yes, as kevin-wangzefeng@ said, "soft Pod AntiAffinti" + "heigh enough weight" should meet this requirement :).

**Comment by gyliu513** [comment]
@kevin-wangzefeng With `Pod AntiAffinity`, I think it only works with current existing pod. i.e. I have a pod running in node1, then I can use `Pod AntiAffinity` to make sure other pods will not run on node1 any more.

But the question from @jmzwcn is he want to make the `anti affinity` in a global level, such as I have a deployment with 4 pods, and I want to those 4 pods to be deployed to 4 different IDCs. Seems we cannot achieve this for now. Comments?

**Comment by jmzwcn** [comment]
@gyliu513, yes, our requirement is exactly what you said.

**Comment by k82cn** [comment]
>  I think it only works with current existing pod. i.e. I have a pod running in node1, then I can use Pod AntiAffinity to make sure other pods will not run on node1 any more.

Yes; and you can anti-affinity to "yourself" in Pod template: the Pod template has label (e.g. `label_1`), and there's Pod anti-affinity in Pod template for the label; so when it running, the first Pod will run in IDC, e.g. (`IDC1`), when running the second Pod, there's a existing Pod in `IDC1` matched anti-affinity.

**Comment by jmzwcn** [comment]
By read more, I don't think pod-anti-affinity could meet our requirement. IDC label only exists in nodes. pod affinity don't care node actually.

**Comment by k82cn** [comment]
> pod affinity don't care node actually.

Pod Anti-Affinity/Affinity's term has `topologyKey` which can help to map to nodes.

**Comment by kevin-wangzefeng** [comment]
@jmzwcn well, that what the field topologyKey designed for.

Say you have nodes in IDCs like this:
 idc | nodes | common labels 
-- | -- | --
idc1 | node11, node12, node13 | idc=idc1
idc2 | node21, node22, node23 | idc=idc2

and when you setting up pod AntiAffinity rules, you may configure like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-anti-affinity
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: pod-label-to-spread
              operator: In
              values:
              - some-value
          topologyKey: idc
  containers:
  - name: with-pod-affinity
    image: gcr.io/google_containers/pause:2.0
```

For spreading pods from different deployments, you can just make the pods have common labels i.e. "pod-label-to-spread=some-value"

**Comment by jmzwcn** [comment]
In principle, the topologyKey can be any legal label value. However, for performance reasons, only a limited set of topology keys are allowed. By default the allowed topology keys are:

    kubernetes.io/hostname
    failure-domain.beta.kubernetes.io/zone
    failure-domain.beta.kubernetes.io/region

reference from https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

**Comment by kevin-wangzefeng** [comment]
yeah, that's enforced by an admission controller, you can either reuse the key "failure-domain.beta.kubernetes.io/zone" for indicating idc, or you can modify the admission controller, to make it allow your own label key. Actually it is implemented configurable, so you don't even need to change any code, IIRC.

**Comment by gyliu513** [comment]
@kevin-wangzefeng What @jmzwcn want is *one* deployment to spread pods cross different idc, but not *many* deployments, I think we cannot achieve this for now.

**Comment by jmzwcn** [comment]
back to our basic requirement, we care pods within one deployment, NOT across deployments, let them spread in different IDCs. I think @gyliu513 understand what I said.

**Comment by kevin-wangzefeng** [comment]
@gyliu513 that's ok either you are trying to spread pods from one deployment or many deployments, because the pod affinity is configured in the spec of pod (or podTemplate in this case)

**Comment by gyliu513** [comment]
@kevin-wangzefeng shall we move to slack? I show up as @gyliu513 there

**Comment by kevin-wangzefeng** [comment]
Sure, we can have a quick discussion on slack, if you guys would like to. My handle is @kevin-wangzefeng

**Comment by jmzwcn** [comment]
Great, hope to have a better solution, then we could implement it as a feature request.

**Comment by kevin-wangzefeng** [comment]
Just a side note here, maybe we can improve the document, it seems not quite easy to understand, and I've explained it to many guys several times.

**Comment by gyliu513** [comment]
Thanks @kevin-wangzefeng for the explanation, will have a try and check code for this.

@jmzwcn , can you please have a try first with following template? If you have 4 pods in one deployment, then this should help spread your pods to 4 different nodes. I do not have such environment now and cannot do the test for now, but can help when got a environment later.

You can use following:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: spread
            operator: In
            values:
            - anti
        topologyKey: kubernetes.io/hostname
  containers:
  - name: with-pod-affinity
    image: gcr.io/google_containers/pause:2.0
```
Make sure  the pods have common labels i.e. "spread=anti".
