### ISSUE TITLE
Tolerations are not applied to Heapster

### ISSUE THREAD

**Issue by devent** [kubernetes/kubernetes#46618]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):

```kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3+coreos.0", GitCommit:"70bc0937018d89b0d529d428eed8c444d8e7729a", GitTreeState:"clean", BuildDate:"2017-05-11T18:15:57Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **OS** (e.g. from /etc/os-release):

```cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- **Kernel** (e.g. `uname -a`):

```uname -a
Linux andrea-master-0.muellerpublic.de 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.25-1~bpo8+1 (2017-05-19) x86_64 GNU/Linux
```

**What happened**:

Try to apply the manifest with `kubectl apply -f FILE`. The tolerations are not set.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-v1.3.0
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v1.3.0
    robobeerun.com/group: cluster-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
      version: v1.3.0
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.3.0
        robobeerun.com/group: cluster-monitoring
    spec:
      containers:
        - image: gcr.io/google_containers/heapster-amd64:v1.3.0
          name: heapster
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
          command:
            - /heapster
            - --source=kubernetes.summary_api:''
            - --sink=influxdb:http://monitoring-influxdb:8086
        - image: gcr.io/google_containers/heapster-amd64:v1.3.0
          name: eventer
          command:
            - /eventer
            - --source=kubernetes:''
            - --sink=influxdb:http://monitoring-influxdb:8086
        - image: gcr.io/google_containers/addon-resizer:1.7
          name: heapster-nanny
          resources:
            limits:
              cpu: 50m
              memory: 60600Ki
            requests:
              cpu: 50m
              memory: 60600Ki
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=80m
            - --extra-cpu=0.5m
            - --memory=40Mi
            - --extra-memory=25Mi
            - --threshold=5
            - --deployment=heapster-v1.3.0
            - --container=heapster
            - --poll-period=300000
            - --estimator=exponential
        - image: gcr.io/google_containers/addon-resizer:1.7
          name: eventer-nanny
          resources:
            limits:
              cpu: 50m
              memory: 60600Ki
            requests:
              cpu: 50m
              memory: 60600Ki
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=100m
            - --extra-cpu=0m
            - --memory=40Mi
            - --extra-memory=5Mi
            - --threshold=5
            - --deployment=heapster-v1.3.0
            - --container=eventer
            - --poll-period=300000
            - --estimator=exponential
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: robobeerun.com/cluster-monitoring-heapster
                operator: In
                values:
                - required
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: robobeerun.com/cluster-monitoring-heapster
                operator: In
                values:
                - preferred
      tolerations:
      - effect: NoSchedule
        key: node.alpha.kubernetes.io/ismaster
        operator: Equal
```

**What you expected to happen**:

The tolerations are set.

**How to reproduce it** (as minimally and precisely as possible):

Apply the posted manifest.

**Anything else we need to know**:

Applied configuration:

```
{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"k8s-app\":\"heapster\",\"robobeerun.com/group\":\"cluster-monitoring\",\"version\":\"v1.3.0\"},\"name\":\"heapster-v1.3.0\",\"namespace\":\"kube-system\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"k8s-app\":\"heapster\",\"version\":\"v1.3.0\"}},\"template\":{\"metadata\":{\"labels\":{\"k8s-app\":\"heapster\",\"robobeerun.com/group\":\"cluster-monitoring\",\"version\":\"v1.3.0\"}},\"spec\":{\"affinity\":{\"nodeAffinity\":{\"preferredDuringSchedulingIgnoredDuringExecution\":[{\"preference\":{\"matchExpressions\":[{\"key\":\"robobeerun.com/cluster-monitoring-heapster\",\"operator\":\"In\",\"values\":[\"preferred\"]}]},\"weight\":1}],\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"robobeerun.com/cluster-monitoring-heapster\",\"operator\":\"In\",\"values\":[\"required\"]}]}]}}},\"containers\":[{\"command\":[\"/heapster\",\"--source=kubernetes.summary_api:''\",\"--sink=influxdb:http://monitoring-influxdb:8086\"],\"image\":\"gcr.io/google_containers/heapster-amd64:v1.3.0\",\"livenessProbe\":{\"httpGet\":{\"path\":\"/healthz\",\"port\":8082,\"scheme\":\"HTTP\"},\"initialDelaySeconds\":180,\"timeoutSeconds\":5},\"name\":\"heapster\"},{\"command\":[\"/eventer\",\"--source=kubernetes:''\",\"--sink=influxdb:http://monitoring-influxdb:8086\"],\"image\":\"gcr.io/google_containers/heapster-amd64:v1.3.0\",\"name\":\"eventer\"},{\"command\":[\"/pod_nanny\",\"--cpu=80m\",\"--extra-cpu=0.5m\",\"--memory=40Mi\",\"--extra-memory=25Mi\",\"--threshold=5\",\"--deployment=heapster-v1.3.0\",\"--container=heapster\",\"--poll-period=300000\",\"--estimator=exponential\"],\"env\":[{\"name\":\"MY_POD_NAME\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.name\"}}},{\"name\":\"MY_POD_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}}],\"image\":\"gcr.io/google_containers/addon-resizer:1.7\",\"name\":\"heapster-nanny\",\"resources\":{\"limits\":{\"cpu\":\"50m\",\"memory\":\"60600Ki\"},\"requests\":{\"cpu\":\"50m\",\"memory\":\"60600Ki\"}}},{\"command\":[\"/pod_nanny\",\"--cpu=100m\",\"--extra-cpu=0m\",\"--memory=40Mi\",\"--extra-memory=5Mi\",\"--threshold=5\",\"--deployment=heapster-v1.3.0\",\"--container=eventer\",\"--poll-period=300000\",\"--estimator=exponential\"],\"env\":[{\"name\":\"MY_POD_NAME\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.name\"}}},{\"name\":\"MY_POD_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}}],\"image\":\"gcr.io/google_containers/addon-resizer:1.7\",\"name\":\"eventer-nanny\",\"resources\":{\"limits\":{\"cpu\":\"50m\",\"memory\":\"60600Ki\"},\"requests\":{\"cpu\":\"50m\",\"memory\":\"60600Ki\"}}}],\"tolerations\":[{\"effect\":\"NoSchedule\",\"key\":\"node.alpha.kubernetes.io/ismaster\",\"operator\":\"Equal\"}]}}}}\n
```

**Comment by gyliu513** [comment]
@devent how did you check the `tolerations` are not set? Did you set related `taint` on the host?

**Comment by xiangpengzhao** [comment]
@devent  I don't understand what happened and what you expected to happen, either. I can see tolerations in both the manifest and the applied configuration. Could you please explain and provide more info?

might be /sig scheduling ?

**Comment by k82cn** [comment]
@devent , what do you mean `The tolerations are set.` ?

**Comment by rkoval** [comment]
@devent if you change the `valueFrom.fieldRef.fieldPath` from the `MY_POD_NAMESPACE` from `metadata.namespace` to `metadata.name`, will the toleration get added and will the Deployment succeed deploying (despite the underlying application probably not working)?

e.g.:
```yaml
# ...
- name: MY_POD_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
# ...
```
to
```yaml
#...
- name: MY_POD_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.name # this will fix the k8s Deployment but break the underlying addon-resizer
# ...
```

If so, I believe we're having the same issue... In my case, you can also hardcode the env var as a `value` of `kube-system` (which is what it would evaluate to in your config from `valueFrom.fieldRef.fieldPath`), and the Deployment will exhibit the same behavior.

e.g.:
```yaml
# ...
- name: MY_POD_NAMESPACE
  value: kube-system
# ...
```
Let me know if you have the same behavior, and I can potentially provide some extra data-points here. I don't want to hijack the issue anymore than I already have 😅
