### ISSUE TITLE
Mount Propagation (:shared)

### ISSUE THREAD

**Issue by tcf909** [kubernetes/kubernetes#46643]
**Kubernetes version** (use `kubectl version`):
Google Container Engine, using 1.6.2

**Environment**:
- **Cloud provider or hardware configuration**:
Google Container Engine
- **OS** (e.g. from /etc/os-release):
COS image (also tried CONTAINER-VM image with the exact same result)

**What happened**:
When trying to use :shared (mount propagation) on a volume mount the container will not start and throws an error.

The error is:
```
Failed to start container with id 3d5c12f50a26390963f79919c3e4694d992f77906f200f404f8359445a1c434a with error: rpc error: code = 2 desc = failed to start container "3d5c12f50a26390963f79919c3e4694d992f77906f200f404f8359445a1c434a": Error response from daemon: linux mounts: Path /var/lib/kubelet/pods/ac0d45c6-456b-11e7-9165-42010a800158/volumes/kubernetes.io~gce-pd/pvc-fb9f09b4-32c5-11e7-9165-42010a800158/data is mounted on /var/lib/kubelet/pods/ac0d45c6-456b-11e7-9165-42010a800158/volumes/kubernetes.io~gce-pd/pvc-fb9f09b4-32c5-11e7-9165-42010a800158 but it is not a shared mount.
Error syncing pod, skipping: failed to "StartContainer" for "cloud-storage" with rpc error: code = 2 desc = failed to start container "3d5c12f50a26390963f79919c3e4694d992f77906f200f404f8359445a1c434a": Error response from daemon: linux mounts: Path /var/lib/kubelet/pods/ac0d45c6-456b-11e7-9165-42010a800158/volumes/kubernetes.io~gce-pd/pvc-fb9f09b4-32c5-11e7-9165-42010a800158/data is mounted on /var/lib/kubelet/pods/ac0d45c6-456b-11e7-9165-42010a800158/volumes/kubernetes.io~gce-pd/pvc-fb9f09b4-32c5-11e7-9165-42010a800158 but it is not a shared mount.: "Start Container Failed"
```

**What you expected to happen**:
I expect the container to start and any fuse mounts it creates in a volume that exists on other containers in the pod (that are using :slave) are available to those other containers. I currently have a cluster setup in AWS (configured using KOPS with the standard KOPS image) and this is working fine. I'm trying to migrate my services over to Google Cloud, but this is a show stopper.

**How to reproduce it** (as minimally and precisely as possible):
This is a minimal deploy config that provides the error I receive:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  labels:
    name: test
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: test
      annotations:
        version: "1"
    spec:
      containers:
        - name: cloud-storage
          image: tcf909/cloud-storage
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN #This doesn't actually work for now because of something to do with using VolumeMounts to pass /dev/fuse -- require privileged
          ports:
          volumeMounts:
            #FOR RCLONE_MOUNT and #UNION_MOUNT
            - name: fuse
              mountPath: /dev/fuse
            #FOR RCLONE_MOUNT
            - name: data
              mountPath: /data:shared
              subPath: data
        - name: cloud-storage2
          image: tcf909/cloud-storage
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN #This doesn't actually work for now because of something to do with using VolumeMounts to pass /dev/fuse -- require privileged
          ports:
          volumeMounts:
            #FOR RCLONE_MOUNT and #UNION_MOUNT
            - name: fuse
              mountPath: /dev/fuse
            #FOR RCLONE_MOUNT
            - name: data
              mountPath: /data:slave
              subPath: data
      volumes:
        - name: fuse
          hostPath:
            path: /dev/fuse
        - name: data
          persistentVolumeClaim:
            claimName: data
```
