### ISSUE TITLE
Support for envFrom in initContainers

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes/kubernetes#46670]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): 1.6.4

Looks like initContainers which became a key in 1.6 does not support envFrom which makes passing vars from a configMap to init containers painful.

**Comment by k82cn** [comment]
@igoratencompass , just try it in 1.6.4, the init containers can use envFrom with configMap as follow:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  log_level: INFO
```

```
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: ubuntu:16.04
    command: ['env']
    envFrom:
      - configMapRef:
          name: env-config
  initContainers:
  - name: init-env
    image: ubuntu:16.04
    command: ['env']
    envFrom:
      - configMapRef:
          name: env-config
```

```
# kc logs myapp-pod -c init-env | grep log
log_level=INFO
```
