### ISSUE TITLE
configmap as volume doesn't work

### ISSUE THREAD

**Issue by reachlin** [kubernetes/kubernetes#46768]
I created a configmap for a pod's volume, but it's empty:
```
lincai@montana:~/prometheus$ kubectl exec nginx-deployment-2643406053-6t4h8 -- ls -al /etc/prometheus
total 8
drwxr-xr-x  2 root root 4096 Jun  1 10:07 .
drwxr-xr-x 46 root root 4096 Jun  1 10:07 ..
lincai@montana:~/prometheus$ 
```

the configmap create cmd:
```
kubectl create configmap prometheus --from-file=documentation/examples/prometheus-kubernetes.yml
lincai@montana:~/prometheus$ kubectl get configmap
NAME         DATA      AGE
prometheus   1         21m
```

the pod manifest:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      # unlike pod-nginx.yaml, the name is not included in the meta data as a unique name is
      # generated from the deployment name
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
          items:
            - key: prometheus-kubernetes.yml
              path: prometheus.yml
```

**Comment by reachlin** [comment]
fyi, configmap contents:
```
lincai@montana:~/prometheus$ kubectl describe configmap prometheus
Name:		prometheus
Namespace:	default
Labels:		<none>
Annotations:	<none>

Data
====
prometheus-deployment.yaml:
----
apiVersion: v1
kind: Service
metadata:
...
```

**Comment by mtanino** [comment]
Hi,

Which version of kubernetes are you using?
I tried with latest master and it worked as we expected shown in below.

```
% cat configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  special.level: very
  special.type: charm
% k get configmap
NAME             DATA      AGE
special-config   2         1h
% cat config_vol_ex2.yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: ["/bin/sh", "-c"]
      args: [ "ls -la /etc/config; cat /etc/config/keys" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
        items:
        - key: special.level
          path: keys
  restartPolicy: Never
% k create -f config_vol_ex2.yaml
pod "dapi-test-pod" created
% k logs dapi-test-pod
total 12
drwxrwxrwx    3 root     root          4096 Jun  1 20:46 .
drwxr-xr-x    7 root     root          4096 Jun  1 20:46 ..
drwxr-xr-x    2 root     root          4096 Jun  1 20:46 ..6986_01_06_16_46_46.716969719
lrwxrwxrwx    1 root     root            31 Jun  1 20:46 ..data -> ..6986_01_06_16_46_46.716969719
lrwxrwxrwx    1 root     root            11 Jun  1 20:46 keys -> ..data/keys
very
```

**Comment by mtanino** [comment]
In this case, you don't need to specify items.

```
          items:
            - key: prometheus-kubernetes.yml
              path: prometheus.yml
```
Without items, you could see prometheus-kubernetes.yml under /etc/prometheus/.
```
% cat test.yaml                                                                                                                                          [~/sample/storage/configmap]
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      # unlike pod-nginx.yaml, the name is not included in the meta data as a unique name is
      # generated from the deployment name
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
% k create -f test.yaml
deployment "nginx-deployment" created
% k get pod --show-all
NAME                               READY     STATUS    RESTARTS   AGE
nginx-deployment-185217237-ggv69   1/1       Running   0          7s
% k exec -it nginx-deployment-185217237-ggv69 -- head /etc/prometheus/prometheus-kubernetes.yml -n 10
# A scrape configuration for running Prometheus on a Kubernetes cluster.
# This uses separate scrape configs for cluster components (i.e. API server, node)
# and services to allow each to use different authentication configs.
#
# Kubernetes labels will be added as Prometheus labels on metrics via the
# `labelmap` relabeling action.

# Scrape config for API servers.
#
# Kubernetes exposes API servers as endpoints to the default/kubernetes
```
