### ISSUE TITLE
kube-apiserver 1.6.1 bring up relies on localhost not resolving via dns

### ISSUE THREAD

**Issue by tuminoid** [kubernetes/kubernetes#46767]
**Is this a request for help?**
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
localhost, kube-apiserver

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Vagrant
- **OS** (e.g. from /etc/os-release): RHEL 7.3
- **Kernel** (e.g. `uname -a`): `Linux kubemaster1 3.10.0-514.21.1.el7.x86_64 #1 SMP Sat Apr 22 02:41:35 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: kubelet from rpm
- **Others**:

**What happened**:
If `localhost` resolves in your search domains (eg. `localhost.company.foo`), and kube-apiserver uses go resolver as default (search order `dns, files`), kube-apiserver pod fails to come up.
```
Unable to perform initial IP allocation check: unable to refresh the service IP block: Get https://localhost:443/api/v1/services: dial tcp xxx.xxx.xxx.xxx:443: getsockopt: connection refused
```
where `xxx.xxx.xxx.xxx` is not `127.0.0.1`, but actual ip of random machine named `localhost`.

**What you expected to happen**:
`localhost` resolves to `127.0.0.1` via `/etc/hosts`
or
`localhost` is not used in the first place, but kube-apiserver should connect to `127.0.0.1` in the first place.

**How to reproduce it** (as minimally and precisely as possible):
- Have `localhost` resolve to a domain in your network, ie. `localhost.company.xxx` via dns search domains.
- Bring up kube-apiserver pod
Example yaml (shouldn't really matter):
```
...
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: registry.company.xxx:5000/kube-apiserver-amd64:v1.6.1
    command:
    - /usr/local/bin/kube-apiserver
    - --v=0
    - --logtostderr=true
    - --allow-privileged=true
    - --bind-address=0.0.0.0
    - --advertise-address=192.168.10.20
    - --secure-port=443
    - --etcd-servers=http://192.168.10.20:2379
    - --service-cluster-ip-range=10.254.0.0/16
    - --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
    - --service_account_key_file=/etc/kubernetes/ssl/apiserver-key.pem
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --anonymous-auth=false
    - --storage-backend=etcd3
...
```

**Anything else we need to know**:
Resolved issue by setting `GODEBUG=netdns=cgo` environment variable for kube-apiserver pod, forcing search order to be `(files, dns)`.
