### ISSUE TITLE
Failed pods with restart policy=Never should not be in the Endpoints.NotReadyAddresses

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#46776]
If you create a job in which pods are crashing and a service spawning those pods, this may result in generating extremely huge Endpoints object (which will cause different performance issues).
[Based on situation from one of our customers cluster].

After 30m from creating the objects below in my 3 node-cluster I have an endpoint which has almost 1MB of size:
```
wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes$ kubectl get endpoints failed-service -o json > out.txt
wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes$ ls -la out.txt 
-rw-r----- 1 wojtekt eng 891834 Jun  1 14:31 out.txt
```

Example objects which are enough to cause this
1. service:
```
apiVersion: v1
kind: Service
metadata:
  name: failed-service
spec:
  selector:
    app: failed
  ports:
  - protocol: TCP
    port: 80
    targetPort: 12345
```
2. job:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: failed-job2
spec:
  parallelism: 10
  completions: 10
  template:
    metadata:
      name: failed-job2
      labels:
        app: failed
    spec:
      restartPolicy: Never
      containers:
      - name: failed-pod
        image: busybox
        command: [ "/bin/sh", "-c", "sleep 5 && exit 1"]
```

@bowei @kubernetes/sig-network-bugs @kubernetes/sig-scalability-bugs
