### ISSUE TITLE
Found invalid field name for v1.EnvFromSource when using envFrom in Pod

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes/kubernetes#46826]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): v1.EnvFromSource, envFrom

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): 1.6.4

**Environment**: kubernetes-1.6.4
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04.5 LTS
- **Kernel** (e.g. `uname -a`): 3.13.0-116-generic
- **Install tools**: kops-1.6.0
- **Others**: kubectl-1.6.4

**What happened**: I get the following error:
```
error validating data: found invalid field name for v1.EnvFromSource; if you choose to ignore these errors, turn validation off with --validate=false
```
for the following config:
```
apiVersion: v1
kind: Pod
metadata:
  name: encompass-app
  namespace: defaul
  labels:
    app: encompass-app
spec:
  containers:
  - name: encompass-app
    image: radial/busyboxplus:curl
    imagePullPolicy: IfNotPresent
    envFrom:
    - configMapRef:
      name: encompass-app-init
...
```
the `encompass-app-init` configMap has already been created in the same namespace.

**What you expected to happen**: I expect the env vars for the Pod to get populated from the configMap referenced as per the documentation: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-pod-environment-variables

**How to reproduce it** (as minimally and precisely as possible):  You can use the code snippet provided.

**Anything else we need to know**:  I get the same error with the example from your docs: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-pod-environment-variables
```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
        name: special-config
  restartPolicy: Never
```

**Comment by igoratencompass** [comment]
@kubernetes/sig-cli

**Comment by k82cn** [comment]
just check example with master branch, it works; I'm going to check 1.6.x.

**Comment by k82cn** [comment]
@igoratencompass , I think you missed two space before `configMapRef.name`, it should be the following format:

```
    - configMapRef:
        name: special-config
```

**Comment by k82cn** [comment]
@igoratencompass , is that OK now?

**Comment by igoratencompass** [comment]
@k82cn yep that worked, any idea why are those 2 spaces needed though? The yaml should be valid without them too.

**Comment by k82cn** [comment]
/close

The `name` is an sub-item of `configMapRef`, so 2 spaces is necessary :).

**Comment by felixle236** [comment]
Although this article has been closed, in my opinion, two spaces are unnecessary while we have a "-" separator, see the attached image.
![image](https://user-images.githubusercontent.com/28352666/79086502-803f7500-7d66-11ea-93df-8e94a0d3813b.png)

**Comment by lucasgvarela** [comment]
another example where 2 spaces are enough pod.spec.containers.name.image only requires 2 spaces not 4... 
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: nginx
```
