### ISSUE TITLE
subPath = file bug version 1.5.2

### ISSUE THREAD

**Issue by samiaben88** [kubernetes/kubernetes#46839]
Hi,
I deploy kubernetes using ansible on two nodes (1 master and one slave), it brings : version 1.5.2

everything working fine except when I use subpath:

The issue is, I have subPath set to a file in a configmap to map it into the right place in my container. But kubernetes assumes subPath is a directory and always does a mkdir over it. This causes things to fail. 

I already see this issue in (https://github.com/kubernetes/kubernetes/issues/45613 ) but it was about kubernetes version 1.6.3 and the solution was that the update (1.6.4) will correct this.

I'm wondering how can I resolve this, without switching version? and can I use a resent version deployed with ansible ? 

can you help me please

**Comment by samiaben88** [comment]
@kubernetes/sig-storage-bugs

**Comment by gnufied** [comment]
@wongma7 does 1.5.x also suffers from https://github.com/kubernetes/kubernetes/issues/45613 ?

**Comment by wongma7** [comment]
No, I thankfully 😅 did not backport my defective patch to 1.5.x.

I'll look into this later today. If the file exists there should be no problem... If for whatever reason it looks like it doesn't, then *docker* will auto create a directory.

**Comment by wongma7** [comment]
@samiaben88 can you post your pod spec please? It worked for me with the following pod and configmap (adapted from the doc example):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  special.level: very
  special.type: charm
```
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "ls /etc/config/" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config/special.level
        subPath: special.level
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: special-config
  restartPolicy: Never
```
