### ISSUE TITLE
Allow auto-population of environmental variables from secrets.

### ISSUE THREAD

**Issue by 20zinnm** [kubernetes/kubernetes#47016]
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): secrets, envfrom

This is related to #26299

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-beta.2", GitCommit:"0776eab45fe28f02bbeac0f05ae1a203051a21eb", GitTreeState:"clean", BuildDate:"2016-11-24T22:35:03Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): Container-Optimized OS v1.6.4

**What happened**:

Kubernetes seemingly ignored the envFrom entry that introduced the secret.

**What you expected to happen**:

The environment would be auto-populated with keys and values from the secret, as defined in the Kubernetes API Reference Document (https://kubernetes.io/docs/api-reference/v1.6/#podpresetspec-v1alpha1-settings).

**How to reproduce it** (as minimally and precisely as possible):

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  labels:
    app: my-app
type: Opaque
data:
  my_secret: "c3VwZXJfc2VjcmV0"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
    spec:
      containers:
       - name: my-app
         image: "alpine:latest"
         imagePullPolicy: Always
         command: ["/bin/sh", "-c"]
         args: ["echo \"MY_SECRET=$MY_SECRET\"; while [ 1 ]; do sleep 2; done", ]
         envFrom:
          - secretRef:
              name: my-app-secret
              ## To ensure that it wasn't just ignoring keys, I added:
              # optional: false
              ## It still didn't work or fail fast.
```
