### ISSUE TITLE
Daemonset's pods don't restart after deletion

### ISSUE THREAD

**Issue by deimosfr** [kubernetes/kubernetes#47085]
Hi,

I'm encountering issues using DaemonSet. I can deploy only once. If I delete the DaemonSet with the associated nodes, I'm unable anymore to deploy the same DaemonSet config.Also deleting a node don't make it reapar after.

**Environment**:
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): coreos 1353.8.0
- **Kernel** (e.g. `uname -a`): Linux core01.fqdn 4.9.24-coreos #1 SMP Tue May 30 23:12:01 UTC 2017 x86_64 Intel(R) Atom(TM) CPU C2750 @ 2.40GHz GenuineIntel GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
Here is an example, I'm using this:
```yaml
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: hostname-ds
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: hostname-ds
    spec:
      containers:
      - image: gcr.io/google_containers/serve_hostname
        name: hostname-ds
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: port
          containerPort: 9376
```
On the first apply, it works, then if I try to remove a pod it's doesn't restart (here I've got 4 nodes):
```
$ kubectl get po | grep hostname
NAME                                            READY     STATUS    RESTARTS   AGE
hostname-ds-h604g                            1/1       Running   0          3m
hostname-ds-jm6h6                            1/1       Running   0          3m
hostname-ds-pbmzj                            1/1       Running   0          3m
```

The missing one is not restarted. Now if I'm looking at the describe:
```
Name:		hostname-ds
Selector:	name=hostname-ds
Node-Selector:	<none>
Labels:		name=hostname-ds
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"name":"hostname-ds","namespace":"kube-system"},"spec":{"template":{...
Desired Number of Nodes Scheduled: 4
Current Number of Nodes Scheduled: 4
Number of Nodes Scheduled with Up-to-date Pods: 4
Number of Nodes Scheduled with Available Pods: 3
Number of Nodes Misscheduled: 0
Pods Status:	3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:	name=hostname-ds
  Containers:
   hostname-ds:
    Image:	gcr.io/google_containers/serve_hostname
    Port:	9376/TCP
    Limits:
      cpu:	200m
      memory:	30Mi
    Requests:
      cpu:		100m
      memory:		20Mi
    Environment:	<none>
    Mounts:		<none>
  Volumes:		<none>
Events:		<none>
```
I can see there are only 3 of 4 pods running.

If I'm trying to delete the DaemonSet, it takes a long time and I need to add --cascade=false to be sure it's deleted. If I'm trying to push the same config of the Daemonset, nothings happen, I don't see any pods creating.

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4+coreos.0", GitCommit:"8996efde382d88f0baef1f015ae801488fcad8c4", GitTreeState:"clean", BuildDate:"2017-05-19T21:11:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What you expected to happen**:

I'm expecting the DaemonSet to recreate deleted pods and daemonset recreating ok after delete

Thanks
