### ISSUE TITLE
one deployment one schedule policy

### ISSUE THREAD

**Issue by liuliuzi** [kubernetes/kubernetes#47110]
Is this a BUG REPORT or FEATURE REQUEST? (choose one):
FEATURE REQUEST
When I need scale out one deployment,  I want to the pod created  not be bond to the node which existe this type pod. I could develope customize predicate to meet this requiement . But if use this policy，all deployment will comply with this policy，which not I wanted. 
So is there any feature that every deployments can has their own scheduling policy？

**Comment by gyliu513** [comment]
@liuliuzi I think the multiple scheduler can help you: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/ , just use your customized scheduler for each deployment.

**Comment by k82cn** [comment]
Seems Pod Anti-Affinity can help; the following affinity will make not more than one Pod of deployment in a node; if more pod than nodes, they're pending.

```yaml
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: spread
            operator: In
            values:
            - deployment-name <<=== update to deployment name
        topologyKey: kubernetes.io/hostname
```
