### ISSUE TITLE
Services allow duplicate targetPort

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#47222]
It is possible to express a Service where multiple front-side ports target the same back-side port.  This is not very useful and may cause trouble for implementations of Services.

```
apiVersion: v1
kind: Service
metadata:
  name: hostnames-2
spec:
  ports:
  - name: a
    port: 80
    targetPort: 9376
  - name: b
    port: 81
    targetPort: 9376
  selector:
    run: hostnames
````

**Comment by odeke-em** [comment]
@thockin just for the purpose of clarity, are you requesting that duplicate targetPorts
should be rejected or the opposite?
PS: I am new to Kubernetes so please pardon the dumb question :)

**Comment by thockin** [comment]
I think that should probably be rejected at validation unless we have a
good reason WHY we need that.

**Comment by odeke-em** [comment]
Aye aye, thanks for the clarificiation!

**Comment by jhorwit2** [comment]
@thockin what problems did this cause with services? This change broke backwards compatibility for services that depended on this feature. 

For example, lets take the load balancer service
```
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: ssl-certificate-secret
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
```
The load balancer here terminates SSL so the backend is always port 80; however, you want to make sure you support both protocols.
