### ISSUE TITLE
The completed Pods (with initContainers) was restarted

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#47295]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master

```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.538+67730881a6031f-dirty", GitCommit:"67730881a6031f4f6f24054ccab77b0d004f5dbc", GitTreeState:"dirty", BuildDate:"2017-06-11T00:44:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.538+67730881a6031f-dirty", GitCommit:"67730881a6031f4f6f24054ccab77b0d004f5dbc", GitTreeState:"dirty", BuildDate:"2017-06-11T00:44:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`): `Linux k82cn 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:
- **Others**:

**What happened**:
The completed Pods (with initContainers) was restarted.

```
NAME        READY     STATUS      RESTARTS   AGE
myapp-pod   0/1       Completed   2          2m
root@k82cn:~/k8s_test# kc get pods
NAME        READY     STATUS      RESTARTS   AGE
myapp-pod   0/1       Completed   2          2m
root@k82cn:~/k8s_test# kc get pods
NAME        READY     STATUS      RESTARTS   AGE
myapp-pod   0/1       Completed   2          2m
NAME        READY     STATUS             RESTARTS   AGE
myapp-pod   0/1       CrashLoopBackOff   2          3m
root@k82cn:~/k8s_test# kc get pods
NAME        READY     STATUS             RESTARTS   AGE
myapp-pod   0/1       CrashLoopBackOff   2          3m
root@k82cn:~/k8s_test# kc get pods
NAME        READY     STATUS      RESTARTS   AGE
myapp-pod   0/1       Completed   3          3m
root@k82cn:~/k8s_test# kc get pods
NAME        READY     STATUS             RESTARTS   AGE
myapp-pod   0/1       CrashLoopBackOff   3          3m
root@k82cn:~/k8s_test# kc get pods
NAME        READY     STATUS             RESTARTS   AGE
myapp-pod   0/1       CrashLoopBackOff   3          3m
root@k82cn:~/k8s_test# kc get pods
NAME        READY     STATUS             RESTARTS   AGE
myapp-pod   0/1       CrashLoopBackOff   6          8m
root@k82cn:~/k8s_test# kc get pods
NAME        READY     STATUS             RESTARTS   AGE
myapp-pod   0/1       CrashLoopBackOff   6          8m
```

**What you expected to happen**:
The Pod will not restart when it's completed.

**How to reproduce it** (as minimally and precisely as possible):

* Start k8s locally by `./hack/local-cluster-up.sh`
* Create Pods as follow yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: ubuntu:16.04
    command: ['env']
    envFrom:
      - configMapRef:
          name: env-config
  initContainers:
  - name: init-env
    image: ubuntu:16.04
    command: ['env']
    envFrom:
      - configMapRef:
          name: special-config
```

**Anything else we need to know**:

configMap is the example from configMap tutorial.
