### ISSUE TITLE
[iSCSI] Custom Initiator names per volume

### ISSUE THREAD

**Issue by Thoro** [kubernetes/kubernetes#47311]
**FEATURE REQUEST**
**Kubernetes version**: master (1.8.0alpha)

**Proposal**
Since the addition of chap authentication per volume the logical next feature would be the addition of a custom initiator name per persistent volume. This would allow for more fine grained configuration, and remove the need to configure the initiator name on the host (to be the same on all of them).

**Idea**
Define a stable base interface to be used as a parent and clone it's settings to a new interface.

The new interfaces initiator can be set like that:

```
iscsiadm -m iface -I iface_name --op=update -n  iface.initiatorname -v iqn.example.com
```

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Online_Storage_Reconfiguration_Guide/iscsioffload-softwareiscsi.html

**Comment by rootfs** [comment]
@mtanino do you have bandwidth to do this for 1.8?

**Comment by mtanino** [comment]
@rootfs 
Sure. Let me dig more detail. 
Form my quick glance, this requires initiator name per PV, so we need to add "initiatorname" parameter into ISCSIVolumeSource, right?

Like;
```
  - name: iscsivol-1
    iscsi:
      targetPortal: porta-ip-1
      iqn: target-iqn-1
      lun: 0
      fsType: ext4
      readOnly: true
      initiatorName: init-iqn-1
  - name: iscsivol-2
    iscsi:
      targetPortal: portal-ip-2
      iqn: target-iqn-2
      lun: 1
      fsType: ext4
      readOnly: true
      initiatorName: init-iqn-2
```

**Comment by rootfs** [comment]
@mtanino yes, that's the idea. Overlaying the custom iface over the iface provided in iSCSI volume source should do it.

Since this is an API change, you can find how other iSCSI APIs are added. 

Thanks!

**Comment by mtanino** [comment]
@Thoro @rootfs 

I'm currently considering the implementation detail for this feature.
As for the request from @Thoro, he supposes that iface will be created per Persistent Volume.
My quick questions are;
- Does iscaidm support iface clone operation? I couldn't find that command.
- If not, do we need to copy whole iface's parameters from stable one to new one to create per PV iface?
- How can we manage per PV iface.iscsi_ifacename as an unique?

```
iface.iscsi_ifacename = iser
iface.net_ifacename = <empty>
iface.ipaddress = <empty>
iface.hwaddress = <empty>
iface.transport_name = iser
iface.initiatorname = <empty>
iface.state = <empty>
iface.vlan_id = 0
iface.vlan_priority = 0
iface.vlan_state = <empty>
iface.iface_num = 0
iface.mtu = 0
iface.port = 0
iface.bootproto = <empty>
iface.subnet_mask = <empty>
iface.gateway = <empty>
iface.dhcp_alt_client_id_state = <empty>
iface.dhcp_alt_client_id = <empty>
iface.dhcp_dns = <empty>
iface.dhcp_learn_iqn = <empty>
iface.dhcp_req_vendor_id_state = <empty>
iface.dhcp_vendor_id_state = <empty>
iface.dhcp_vendor_id = <empty>
iface.dhcp_slp_da = <empty>
iface.fragmentation = <empty>
iface.gratuitous_arp = <empty>
iface.incoming_forwarding = <empty>
iface.tos_state = <empty>
iface.tos = 0
iface.ttl = 0
iface.delayed_ack = <empty>
iface.tcp_nagle = <empty>
iface.tcp_wsf_state = <empty>
iface.tcp_wsf = 0
iface.tcp_timer_scale = 0
iface.tcp_timestamp = <empty>
iface.redirect = <empty>
iface.def_task_mgmt_timeout = 0
iface.header_digest = <empty>
iface.data_digest = <empty>
iface.immediate_data = <empty>
iface.initial_r2t = <empty>
iface.data_seq_inorder = <empty>
iface.data_pdu_inorder = <empty>
iface.erl = 0
iface.max_receive_data_len = 0
iface.first_burst_len = 0
iface.max_outstanding_r2t = 0
iface.max_burst_len = 0
iface.chap_auth = <empty>
iface.bidi_chap = <empty>
iface.strict_login_compliance = <empty>
iface.discovery_auth = <empty>
iface.discovery_logout = <empty>
```

**Comment by Thoro** [comment]
@mtanino a quick google also didn't reveal anything for me, looks like you need to read out the settings, create a new interface and apply the settings there

PV interface name could just be the portal + pv name (and escaping of not allowed chars) (https://docs.openstack.org/kilo/config-reference/content/iscsi-iface-config.html)

**Comment by mtanino** [comment]
@Thoro 
Thanks, let me investigate further implementation.

**Comment by mtanino** [comment]
@Thoro @rootfs 
Hi, Can you try this POC code?
https://github.com/mtanino/kubernetes/commit/67938bd13ff080e05466658f581295f804414e22

ex.  pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  iscsi:
    targetPortal: 192.168.122.85:3260
    iqn: iqn.2017-05.com.example:test
    lun: 0
    fsType: ext4
    readOnly: true
    iscsiInterface: stable
    initiatorName: iqn.1994-05.com:185ce16b55ad
```
