### ISSUE TITLE
GCP: LoadBalancer service with external IP creates instance with another IP

### ISSUE THREAD

**Issue by qgadrian** [kubernetes/kubernetes#47420]
**Kubernetes version**: 
- 1.6.4

**Environment**:
- **Cloud provider**: Google Cloud Platform (GCP)

**What happened**:
This happens with a previously static IP created in GCP cluster.

When creating a service with an external IP, a service is created with the declared external endpoint but a load balancer instance in Google cloud is created with another IP address.

So, at the end a service in the Kubernetes dashboard is shown with two address and the load balancer instance in GCP has a generated IP instead the external IP specified.

A yml example:

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: gcp-lb-test
  labels:
    app: gcp-lb-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gcp-lb-test
    spec:
      containers:
        - name: gcp-lb-test
          imagePullPolicy: Always
          image: tutum/hello-world
          readinessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 320
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 30
          ports:
            - containerPort: 80
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: gcp-lb-test
  labels:
    app: gcp-lb-test
spec:
  selector:
    app: gcp-lb-test
  type: LoadBalancer
  externalIPs:
    - 1.1.1.1
  ports:
    - name: gcp-lb-test-ui
      port: 80
      protocol: TCP
```

**What you expected to happen**:
Load balancer should be created with the external IP address instead of created a new one and the service should have only the specify IP.

**How to reproduce it** (as minimally and precisely as possible):
Create an static IP in GCP.
Create a Service.
