### ISSUE TITLE
nil pointer in attach detach controller

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#47547]
Was playing around with flex volumes and got my controller-manager to start crash looping:

```
E0614 20:45:01.659766       8 operation_executor.go:572] VerifyVolumesAreAttached: nil spec for volume idmgr/foobarbaz
E0614 20:45:01.659942       8 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/google/home/mikedanese/.cache/bazel/_bazel_mikedanese/6c65a147ac17188f348dcacc7c554ab3/external/go1.8.3.linux-amd64/src/runtime/asm_amd64.s:514
/usr/local/google/home/mikedanese/.cache/bazel/_bazel_mikedanese/6c65a147ac17188f348dcacc7c554ab3/external/go1.8.3.linux-amd64/src/runtime/panic.go:489
/usr/local/google/home/mikedanese/.cache/bazel/_bazel_mikedanese/6c65a147ac17188f348dcacc7c554ab3/external/go1.8.3.linux-amd64/src/runtime/panic.go:63
/usr/local/google/home/mikedanese/.cache/bazel/_bazel_mikedanese/6c65a147ac17188f348dcacc7c554ab3/external/go1.8.3.linux-amd64/src/runtime/signal_unix.go:290
pkg/volume/aws_ebs/aws_ebs.go:83
pkg/volume/plugins.go:384
pkg/volume/util/operationexecutor/operation_generator.go:119
pkg/volume/util/operationexecutor/operation_executor.go:647
pkg/volume/util/operationexecutor/operation_executor.go:616
pkg/controller/volume/attachdetach/reconciler/reconciler.go:131
pkg/controller/volume/attachdetach/reconciler/reconciler.go:122
pkg/controller/volume/attachdetach/reconciler/reconciler.go:115
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
pkg/controller/volume/attachdetach/reconciler/reconciler.go:98
/usr/local/google/home/mikedanese/.cache/bazel/_bazel_mikedanese/6c65a147ac17188f348dcacc7c554ab3/external/go1.8.3.linux-amd64/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2af20b5]
```

/sig storage

**Comment by gnufied** [comment]
Did you restart the controller or something like that in between?

**Comment by gnufied** [comment]
Also, if you can post your PV, PVC and Pod yaml/json. I think this could be either flex only problem or spec being nil (or incomplete). We recently added support for reconstructing the volume spec of attached volumes on controller restart.

**Comment by mikedanese** [comment]
The pod is deleted. I'm not useing a PV or PVC but this looks suspicious in the nodeSpec:
```
  volumesAttached:
  - devicePath: ""
    name: idmgr/mds-XVlBzgbaiC
  volumesInUse:
  - idmgr/mds-XVlBzgbaiC
  - idmgr/foobarbaz
```

**Comment by dchen1107** [comment]
Which release found the issue? Is it a regression? Is it required for 1.7? Release blocker? cc/ @saad-ali Please triage. Thanks!

**Comment by verult** [comment]
@mikedanese Could you post the steps to reproduce this bug?

If idmgr/mds-XVlBzgbaiC is a FlexVolume plugin and devicePath is "", it COULD mean there's an error with your driver's Attach implementation. In your kube-controller-manager.log do you see anything like "Failed to attach volume idmgr/mds-XVlBzgbaiC on node..."?

**Comment by mikedanese** [comment]
My pod spec is:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  nodeName: k-4-minion-group-70hv
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "idmgr"
```
My driver is returning "{"status": "Not supported"}" for attach/detach ops since I don't need them.
