### ISSUE TITLE
Switch to UnixUserID breaks validation for kubectl 1.6 against 1.7 clusters (unexpected type: types.UnixUserID)

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#47560]
**BUG REPORT**

**Kubernetes version** (use `kubectl version`):

```
$ kubectl --kubeconfig=cluster/auth/kubeconfig version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: vagrant
- **OS** (e.g. from /etc/os-release): CoreOS container linux
- **Kernel** (e.g. `uname -a`):
- **Install tools**: bootkube
- **Others**:

**What happened**:

Attempted to create [a deployment](https://gist.github.com/ericchiang/921582485cbb193c37af37dacc54a8e2) that sets the `runAsUser` security context against a 1.7 cluster fails even though the API server validates fine.

This broke bootkube, which uses client-go at version 1.6.

```
$ kubectl --kubeconfig=cluster/auth/kubeconfig create -f cluster/manifests/kube-scheduler.yaml 
error: error validating "cluster/manifests/kube-scheduler.yaml": error validating data: unexpected type: types.UnixUserID; if you choose to ignore these errors, turn validation off with --validate=false
```

It appears the switch to a dedicated type (https://github.com/kubernetes/kubernetes/pull/44714) for unix IDs has caused some issues with kubectl validation.

**What you expected to happen**:

kubectl to create the deployment without validation errors.

**How to reproduce it** (as minimally and precisely as possible):

Use kubectl 1.6 to try to create the following deployment against a 1.7 cluster:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # Fails validation
```

/cc @kubernetes/sig-api-machinery-bugs @jamiehannaford @diegs @kubernetes/sig-cli-bugs
