### ISSUE TITLE
configmap lose container data

### ISSUE THREAD

**Issue by xiaowei0516** [kubernetes/kubernetes#47590]
@kubernetes/sig-<configmap>-misc
/sig  <configmap-api>

hi，
    I  have a question in using configmap.   
 
    ```
       containers:                                                                                                                                                 
        - name:  mysql
          image:  10.21.1.151/quicksilver/opsfisher_mysql:latest          ports:
            - containerPort: 3306        - name:  supervisor
          image: 10.21.1.151/quicksilver/opsfisher_supervisor:1.1          volumeMounts:
            - name: config-volume1              mountPath:  /tmp/
            - name: config-volume2
              mountPath:  /etc/supervisord.d/

          ports:            - containerPort: 80
              hostPort: 28888        - name:  grafana
          image: 10.21.1.151/quicksilver/grafana-quicksilver:V1.0          ports:
            - containerPort: 3000              hostPort: 28889
      volumes:
        - name: config-volume1          configMap:
            name: opsfisher-conf            items:
                - key: nginx.conf                  path: nginx.conf
        - name: config-volume2          configMap:
            name: opsfisher-conf            items:
                - key: nginx.ini                  path: nginx.ini

    ```

   The above is my RC  configuration file .  then  i create RC `kubectl  create -f   test.yaml`, RUN success.then i enter docker  `docker exec -it   c61789df3020`, result:

   ```
 #ls   /etc/supervisord.d/
  nginx.ini
   ```

my other file lose!!!
