### ISSUE TITLE
[upgrade test failure] Several network partition test failing 

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#47820]
After we fixed upgrade test infra issue (https://github.com/kubernetes/kubernetes/issues/47379#issuecomment-309912047), now we get better signals on real failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1-6-1-7-upgrade-cluster/55 The following Network Partition tests are failed: 

```
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [Job] should create new pods when node is partitioned
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should eagerly create replacement pod during network partition when termination grace is non-zero
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should recreate pods scheduled on the unreachable node AND allow scheduling of pods on a node after it rejoins the cluster
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [StatefulSet] should come back up if node goes down [Slow] [Disruptive]
[k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [StatefulSet] should not reschedule stateful pods if there is a network partition [Slow] [Disruptive]
```

**Comment by janetkuo** [comment]
cc @foxish

**Comment by janetkuo** [comment]
Errors look like this:

```
Node xxx did not become not-ready within 2m0s
```

**Comment by foxish** [comment]
Looking into this

**Comment by foxish** [comment]
Not a real failure.
The upgrade cluster is bootstrapping the kubelet in a different way when compared with other e2e clusters.

```
ramanathana@bootstrap-e2e-minion-group-93zx:~$ sudo cat /var/lib/kubelet/kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca-certificates.crt
    server: https://bootstrap-e2e-master 
  name: default-cluster
contexts:
...
```

The **server** is typically (in every other cluster I inspected) the external IP address of the master in all other clusters. Here, it is using the DNS name, which resolves to the internal IP address.
The iptables rule injections don't take effect due to that difference.

cc @krousey @kubernetes/test-infra-maintainers
