### ISSUE TITLE
Default garbage collection for a resource can cause partial orphaning

### ISSUE THREAD

**Issue by jwforres** [kubernetes/kubernetes#47843]
Seeing this in v1.6.1.

1. Create a Deployment and a Service

```
---
apiVersion: v1
kind: Service
metadata:
  name: hello-openshift
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-openshift 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift
        ports:
        - containerPort: 80
```

2. On the Deployment add an ownerRef that points back to the Service
3. kubectl delete the Service

The Service and the Deployment are deleted, but the ReplicaSet and pods remain.  This is neither Orphan nor Foreground/Background policy. This behavior should never happen.

Note: if I make a delete call to the API with propagationPolicy set explicitly then things behave as expected, so this only occurs when the resource's default propagation policy is being used.
