### ISSUE TITLE
Upgrade test cluster inconsistency

### ISSUE THREAD

**Issue by foxish** [kubernetes/kubernetes#47882]
When the upgrade tests are performed, the kubelets in the upgraded cluster are bootstrapped in a different manner than those in e2e clusters.

Context: https://github.com/kubernetes/kubernetes/issues/47820#issuecomment-310201338
Looks like it may be related to: https://github.com/kubernetes/kubernetes/pull/40760

Upgraded 1.6->1.7 cluster
```
ramanathana@bootstrap-e2e-minion-group-93zx:~$ sudo cat /var/lib/kubelet/kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca-certificates.crt
    server: https://bootstrap-e2e-master  #<--- this resolves to the internal IP
  name: default-cluster
contexts:
...
```

Typical 1.7 e2e cluster:

```
ramanathana@bootstrap-e2e-minion-group-93zx:~$ sudo cat /var/lib/kubelet/kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca-certificates.crt
    server: https://<external-ip>
  name: default-cluster
contexts:
...
```

/assign mikedanese
