### ISSUE TITLE
pod with emptyDir will always fail on upgrading pod image

### ISSUE THREAD

**Issue by hongchaodeng** [kubernetes/kubernetes#47933]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
**BUG REPORT**

**Kubernetes version** (use `kubectl version`):
1.6.4

**Environment**:
- **Cloud provider or hardware configuration**:
GKE

**What happened**:

create pod using yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fun
spec:
  containers:
  - name: fun
    command:
    - /bin/sh
    - -c
    - "echo hehe > /var/haha/hehe; sleep 60000"
    image: nginx:1.12.0
    volumeMounts:
    - mountPath: /var/haha
      name: haha
  restartPolicy: Never
  volumes:
  - name: haha
    emptyDir: {}
```
Do
```
$ kubectl create -f pod.yaml
```
Then upgrade nginx image from 1.12.0 -> 1.13.1 .

The nginix pod _failed_ to upgrade and its state becomes error.

The result
```
$ kubectl get po -w
NAME      READY     STATUS              RESTARTS   AGE
fun       0/1       ContainerCreating   0          2s
fun       1/1       Running   0         6s
fun       1/1       Running   0         2m
fun       0/1       Error     0         2m
fun       0/1       Error     0         2m
```

**What you expected to happen**:

pod should endure upgrade and keep the same data in emptyDir volume.
