### ISSUE TITLE
kubectl not using correct schema version

### ISSUE THREAD

**Issue by dminkovsky** [kubernetes/kubernetes#47937]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig cli

**What happened**:

Tried to create a `Deployment` with `apiVersion: apps/v1beta1`. Got error:

> error: error validating "deployment.yaml": error validating data: unexpected end of JSON input; if you choose to ignore these errors, turn validation off with --validate=false

The create succeeded after I changed `apiVersion` to `extensions/v1beta1`. This was unexpected because the [`Deployment` docs](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) say to use `apps/v1beta1` for version > 1.6.0. I am on 1.6.4.

**What you expected to happen**:

I expected the `Deployment` to be created.

**How to reproduce it (as minimally and precisely as possible)**:

Create a new cluster on GKE. Attempt to create a deployment with `apiVersion: apps/v1beta1`.

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:

GKE cluster created with `gcloud container create`

- OS (e.g. from /etc/os-release):

```
$ cat /etc/os-release
BUILD_ID=9202.64.0
NAME="Container-Optimized OS"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=57
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=57
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```

- Kernel (e.g. `uname -a`):

```
Linux gke-cluster-0-default-pool-dfb79334-l0b6 4.4.35+ #1 SMP Wed Apr 5 13:00:57 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```

- Install tools:

gcloud container create

- Others:

**Comment by dminkovsky** [comment]
@kubernetes/sig-cli

**Comment by kargakis** [comment]
Likely a YAML error on your side...

**Comment by dminkovsky** [comment]
@kargakis Right that's exactly what I thought but all I did to get it working was change `apps/v1beta1` to `extensions/v1beta1`. And here is the entirety of the deployment:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "gcr.io/google-samples/hello-frontend:1.0"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
```

which is copy/paste from from https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/#creating-the-frontend. I looked for a long time and couldn't find an error.
