### ISSUE TITLE
Add pod's subdomain to the resolv.conf search list

### ISSUE THREAD

**Issue by dgageot** [kubernetes/kubernetes#48019]
**FEATURE REQUEST**

/kind feature
@kubernetes/sig-network

**What happened**:

I created two pods in the same subdomain and a headless service for that subdomain. Pods can't find each other by their hostname.

**What you expected to happen**:

I expect a pod (`busybox-1`) in a subdomain (`default-subdomain`) to be able to lookup any other pod (`busybox-2`) in the same subdomain, just using its hostname and not a qualified dns name.

Since the subdomain is not injected in the pods' `/etc/resolv.conf, there's no way it will work. To ping a `busybox-2` from `busybox-1`, I can't ping `busybox-2`. I have to ping `busybox-2.default-subdomain`.

**How to reproduce it**:

Create 2 pods and a headless service with:

```
apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: busybox
  clusterIP: None
  ports:
    - name: foo # Actually, no port is needed.
      port: 1234
      targetPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    name: busybox
spec:
  hostname: busybox-1
  subdomain: default-subdomain
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    name: busybox
spec:
  hostname: busybox-2
  subdomain: default-subdomain
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: busybox
```

Not working:

```
kubectl exec -ti busybox1 -- nslookup busybox-2
Server:    10.27.240.10
Address 1: 10.27.240.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'busybox-2'
```

Working:

```
kubectl exec -ti busybox1 -- nslookup busybox-2.default-subdomain
Server:    10.27.240.10
Address 1: 10.27.240.10 kube-dns.kube-system.svc.cluster.local

Name:      busybox-2.default-subdomain
Address 1: 10.24.7.63 busybox-2.default-subdomain.default.svc.cluster.local
```

**Other information**

Clearly, `/etc/resolv.conf` does not contain the subdomain.
```
kubectl exec -ti busybox1 -- cat /etc/resolv.conf
nameserver 10.27.240.10
search default.svc.cluster.local svc.cluster.local cluster.local google.internal c.my-project.internal
options ndots:5
```

When I add `default-subdomain.default.svc.cluster.local` to the list, everything works as I expect.

I know that the list is limited to 6 entries... So maybe we need a way to add it on-demand or remove it on-demand.

**Environment**:
- Kubernetes version 1.6.4 running on GKE
