### ISSUE TITLE
3-way strategic patch merge should treat empty and nil collections equivalently.

### ISSUE THREAD

**Issue by diegs** [kubernetes/kubernetes#48164]
/kind bug

**What happened**:

`strategicpatch.CreateThreeWayMergePatch()` is unable to create patches where one downstream item deletes the last key in a map but the other other downstream leg has added additional keys (see repro steps).

**What you expected to happen**:

The function should be able to compute a patch for this case successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Call https://godoc.org/k8s.io/apimachinery/pkg/util/strategicpatch#CreateThreeWayMergePatch with the following inputs:

`original`:
```
  name: app-name
  namespace: app-namespace
  annotations:
    upstream-annotation: ""
```

`modified`:
```
  name: app-name
  namespace: app-namespace
  annotations:
```
(or you can leave the "annotations" map off, since it carries the `json:"omitempty"` annotation)

`current`:
```
  name: app-name
  namespace: app-namespace
  annotations:
    upstream-annotation: ""
    custom-annotation: ""
```

`datastruct`: one of these: https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#ObjectMeta

`overwrite`: `false`

This should create a patch that removes the `upstream-annotation` key from the `annotations` map. Instead, it fails with a conflict, saying that it is unable to delete the `annotations` map.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: AWS, GCE, Bare Metal
- OS (e.g. from /etc/os-release): NixOS 17.09pre109180.0d4431cfe9 (Hummingbird)
- Kernel (e.g. `uname -a`): Linux xps13 4.9.32 #1-NixOS SMP Wed Jun 14 13:06:16 UTC 2017 x86_64 GNU/Linux
- Install tools:
- Others:
