### ISSUE TITLE
Feature Request: Finer grained pod statuses

### ISSUE THREAD

**Issue by mikebryant** [kubernetes/kubernetes#48188]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

/kind feature

**Request**:
Finer grained statuses in `Pod.status.containerStatuses.state`

I want to be able to alert on having any pods that are in `ImagePullBackOff`, but only if that's because of an error other than the image not being found

In particular I'd like a field in the API, as the latest status for the Pod. The information is there in the events api in human readable text, but that's fragile to parse, and it's also hard to know if that's still the current status.

**Background: What happened**:

I have some containers in `ImagePullBackOff`
e.g.
```
status:
  containerStatuses:
  - containerID: docker://28863442ae00960a38d8a63f839ec4613720d5430baa8e0d396c7fe5fb7ed761
    image: mirror-internal.docker.tech.lastmile.com/log-aggregation/kafka-topics-docker:e96fc1de7c8dbb6c463a8106786d9df20c3ff80d
    imageID: docker-pullable://mirror-internal.docker.tech.lastmile.com/log-aggregation/kafka-topics-docker@sha256:f65a6025b3b9f93e16b8cae172860bdb0af61667c71c5fb938d9dc80c2e3550c
    name: kafka-topic-mgr
    ready: false
    restartCount: 8
    state:
      waiting:
        message: Back-off pulling image "mirror-internal.docker.tech.lastmile.com/log-aggregation/kafka-topics-docker:e96fc1de7c8dbb6c463a8106786d9df20c3ff80d"
        reason: ImagePullBackOff
```

Events from describe:
```
  1h		1m		24	kubelet, kubernetes-cit-kubernetes-cr2-4-1497286299						Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kafka-topic-mgr" with ErrImagePull: "rpc error: code = 2 desc = Error response from daemon: {\"message\":\"Get https://mirror-internal.docker.tech.lastmile.com/v1/_ping: x509: certificate signed by unknown authority\"}"

  1h	<invalid>	424	kubelet, kubernetes-cit-kubernetes-cr2-4-1497286299	spec.containers{kafka-topic-mgr}	Normal	BackOff		Back-off pulling image "mirror-internal.docker.tech.lastmile.com/log-aggregation/kafka-topics-docker:e96fc1de7c8dbb6c463a8106786d9df20c3ff80d"
```

Speaking as a cluster operator, some of our containers are in `ImagePullBackOff` for "legitimate" reasons. Say, a user has configured the wrong image tag, and it can't find it. This I should ignore, it's not my problem to fix, and I don't want to be alerted on it.

If we've broken our internal docker mirrors (that we host on the same Kubernete cluster), or the x509 cert is missing on that node, or the kube-proxy has broken and isn't forwarding traffic correctly.. Any of these conditions I want to be alerted on. (Yes there should be alerts on root causes, but I also want alerts for anything unanticipated that ends up being a user-visible problem)
