### ISSUE TITLE
scope the resource names 

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#48195]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

 /kind feature

scope the resource name to the same format (e.g. foo_x foo_y), and reserve some special name for administrator.
for instance, user need to create  a pod named "foo_something" and can not create a configmap named "system:configmap"
```
apiVersion: extensions/v1beta1
kind: ResourceNamePolicy
metadata:
  name: test
spec:
  pod:
    rule: "foo_.*"
  configmap:
    reserve: "system:configmap"
```
