### ISSUE TITLE
Multi port service has kube-proxy iptables that send traffic to wrong pod 

### ISSUE THREAD

**Issue by renewooller** [kubernetes/kubernetes#48240]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
bug
> /kind feature

**What happened**:
Requests from within a pod, to another pod that was behind a service, were only working intermittently, around 30% of the time. EG from within a busybox pod, I could run:

```
[ root@curl-57077659-61tm8:/ ]$ curl -v nl-services-gateway:9200
```
Sometimes I would get:
```
* Failed to connect to nl-services-gateway port 9200: Connection refused
curl: (7) Failed to connect to nl-services-gateway port 9200: Connection refused
```
Other times I would get the expected response:

```
 GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: nl-services-gateway:9200
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Content-Length: 317
< 
{
  "name" : "Primevil",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.4.0",
    "build_hash" : "ce9f0c7394dee074091dd1bc4e9469251181fc55",
    "build_timestamp" : "2016-08-29T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
``` 

I sshed into the node that was running the service and had a look at the iptables. Here is a summary of the relevant chain (masks omitted for clarity):

```
-A KUBE-NODEPORTS -p tcp -m comment --comment "dev/nl-services-gateway:es" -m tcp --dport 31137 -j KUBE-SVC-D63FDK4HYU7SWL3R
-A KUBE-SVC-D63FDK4HYU7SWL3R -m comment --comment "dev/nl-services-gateway:es" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-N65IEWE5LC4RFQA6
-A KUBE-SVC-D63FDK4HYU7SWL3R -m comment --comment "dev/nl-services-gateway:es" -j KUBE-SEP-2LDNQG7KFKVNLFY5
-A KUBE-SEP-N65IEWE5LC4RFQA6 -p tcp -m comment --comment "dev/nl-services-gateway:es" -m tcp -j DNAT --to-destination 10.41.248.1:9200
-A KUBE-SEP-2LDNQG7KFKVNLFY5 -p tcp -m comment --comment "dev/nl-services-gateway:es" -m tcp -j DNAT --to-destination 10.41.248.2:9200
```

The above means that 50% of the requests will go to 10.41.248.1:9200, the other 50% will go to 10.41.248.2:9200.

This is a problem, because 10.41.248.2:9200 actually relates to a completely different app (RMQ), which isn't listening on that port, as shown here (other apps omitted for clarity):

```
ubuntu[~] : kubectl get po -o wide
NAME                                READY     STATUS    RESTARTS   AGE       IP            NODE
nl-es-1593651464-92c86              1/1       Running   0          4h        10.41.248.1   ip-10-20-40-39.us-west-1.compute.internal
nl-rmq-1919382859-xflb1             1/1       Running   0          7d        10.41.248.2   ip-10-20-40-39.us-west-1.compute.internal
```

**What you expected to happen**:

I expect that iptables for a particular port to only route to the pod that is listening on that port. IE, if the ports for a pod are 5672 and15672 but not 9200, it should never be forwarded traffic that is destined to 9200.

**How to reproduce it (as minimally and precisely as possible)**:

Set up a multi port service:
```
apiVersion: v1
kind: Service
metadata:
  name: nl-services-gateway
  labels:
    app: nl-services-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    protocol: TCP
    name: es
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: rmq-http
  - port: 5672
    protocol: TCP
    name: rmq-amqp
  selector:
    svc: nl-services-gateway
```

Set up the elasticsearch app:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nl-es
  labels:
    app: nl-es
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nl-es
  template:
    metadata:
      labels:
        app: nl-es
        svc: nl-services-gateway
    spec:
      containers:
      - name: nl-es
        image: <redacted>
        volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          name: nl-es-vol
        ports:
        - containerPort: 9200
          hostPort: 9200
        - containerPort: 9300
          hostPort: 9300
      volumes:
      - name: nl-es-vol
        persistentVolumeClaim:
          claimName: nl-es-pvc
      nodeSelector:
        type: services 
```

Set up the RMQ app:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nl-rmq
  labels:
    app: nl-rmq
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nl-rmq
  template:
    metadata:
      labels:
        app: nl-rmq
        svc: nl-services-gateway
    spec:
      hostname: nl-rmq
      containers:
      - name: nl-rmq
        image: <redacted>
        volumeMounts:
        - mountPath: "/var/lib/rabbitmq"
          name: nl-rmq-vol
        ports:
        - containerPort: 5672
          hostPort: 5672
        - containerPort: 15672
          hostPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: <redacted>
        - name: RABBITMQ_DEFAULT_PASS
          value: <redacted>
      volumes:
      - name: nl-rmq-vol
        persistentVolumeClaim:
          claimName: nl-rmq-pvc
      nodeSelector:
        type: services
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
AWS t2.smalls (nodes), m3.medium (master)
- OS (e.g. from /etc/os-release):
kops default
- Kernel (e.g. `uname -a`):
kops default
- Install tools:
kops default
- Others:

**Comment by xiangpengzhao** [comment]
Can you please show what the endpoint list of your service is?

Try to modify this 

```
  ports:
  - port: 9200
    protocol: TCP
    name: es
```

to be 

```
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: es
```

**Comment by renewooller** [comment]
```

**Comment by renewooller** [comment]
Setting the target port explicitly has no effect.

**Comment by renewooller** [comment]
The problem actually is in the iptables set up by kube-proxy.

**Comment by renewooller** [comment]
Note: I've since also tried:
1. removing 'hostPort' from the container port specs. 
2. adding a readiness probe.

eg, now the config is like:
```

**Comment by cmluciano** [comment]
@renewooller  In the rmq app you have this label
```
  template:
    metadata:
      labels:
        app: nl-rmq
        svc: nl-services-gateway
```

Your Loadbalancer config targets this label 
```
apiVersion: v1
kind: Service
metadata:
  name: nl-services-gateway
  labels:
    app: nl-services-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 9200
    protocol: TCP
    name: es
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: rmq-http
  - port: 5672
    protocol: TCP
    name: rmq-amqp
  selector:
    svc: nl-services-gateway```
