### ISSUE TITLE
kube-proxy with --kubeconfig flag does not find kubeconfig.yml

### ISSUE THREAD

**Issue by narunask** [kubernetes/kubernetes#48258]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
/sig network
/area kube-proxy

**What happened**:
```
$ kubectl -n kube-system logs kube-proxy-10.44.1.192
Error: stat /var/lib/kubelet/kubeconfig.yml: no such file or directory
Error: stat /var/lib/kubelet/kubeconfig.yml: no such file or directory
```

**What you expected to happen**:
`kube-proxy` connected to the API server

**How to reproduce it (as minimally and precisely as possible)**:
```
k8s-2 ~ # ls -l /var/lib/kubelet/kubeconfig.yml
-rw-r--r--. 1 root root 977 Jun 28 15:41 /var/lib/kubelet/kubeconfig.yml
```

```
k8s-2 ~ # cat /etc/kubernetes/manifests/kube-proxy.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: kube-proxy
      image: quay.io/coreos/hyperkube:v1.6.6_coreos.1
      command:
        - /hyperkube
        - proxy
        - --kubeconfig=/var/lib/kubelet/kubeconfig.yml
        - --proxy-mode=iptables
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
  volumes:
    - hostPath:
        path: /usr/share/ca-certificates
      name: ssl-certs-host
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6+coreos.1", GitCommit:"42a5c8b99c994a51d9ceaed5d0254f177e97d419", GitTreeState:"clean", BuildDate:"2017-06-21T01:10:07Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
hardware

- OS (e.g. from /etc/os-release):
```
k8s-2 ~ # cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.5.0
VERSION_ID=1409.5.0
BUILD_ID=2017-06-22-2222
PRETTY_NAME="Container Linux by CoreOS 1409.5.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- Kernel (e.g. `uname -a`):
```
k8s-2 ~ # uname -a
Linux k8s-2 4.11.6-coreos-r1 #1 SMP Thu Jun 22 22:04:38 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5345 @ 2.33GHz GenuineIntel GNU/Linux
```

**Comment by narunask** [comment]
It seems that the following manifest works fine, but it means that I have to mount files from the host on to the pod. Is this expected?

```
apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: kube-proxy
      image: quay.io/coreos/hyperkube:v1.6.6_coreos.1
      command:
        - /hyperkube
        - proxy
        - --kubeconfig=/var/lib/kubelet/kubeconfig.yml
        - --hostname-override=10.44.1.192
        - --cluster-cidr=10.20.0.0/16
        - --proxy-mode=iptables
      securityContext:
        privileged: true
      volumeMounts:
        - name: ssl-certs-host
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: kubeconfig
          mountPath: /var/lib/kubelet/kubeconfig.yml
          readOnly: true
        - name: kube-ssl
          mountPath: /etc/kubernetes/ssl
          readOnly: true
  volumes:
    - name: ssl-certs-host
      hostPath:
        path: /usr/share/ca-certificates
    - name: kubeconfig
      hostPath:
        path: /var/lib/kubelet/kubeconfig.yml
    - name: kube-ssl
      hostPath:
        path: /etc/kubernetes/ssl
```

**Comment by xiangpengzhao** [comment]
If you reference https://coreos.com/kubernetes/docs/latest/deploy-workers.html, yes.

See the chapter `Set Up the kube-proxy Pod`
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: quay.io/coreos/hyperkube:v1.6.1_coreos.0
    command:
    - /hyperkube
    - proxy
    - --master=${MASTER_HOST}
    - --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: "ssl-certs"
    - mountPath: /etc/kubernetes/worker-kubeconfig.yaml
      name: "kubeconfig"
      readOnly: true
    - mountPath: /etc/kubernetes/ssl
      name: "etc-kube-ssl"
      readOnly: true
  volumes:
  - name: "ssl-certs"
    hostPath:
      path: "/usr/share/ca-certificates"
  - name: "kubeconfig"
    hostPath:
      path: "/etc/kubernetes/worker-kubeconfig.yaml"
  - name: "etc-kube-ssl"
    hostPath:
      path: "/etc/kubernetes/ssl"
```
