### ISSUE TITLE
API documentation (kubectl explain) for readinessProbe.httpGet.port is misleading

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#48290]
Client/server version: v1.6.4

```
$ kubectl explain deployment.spec.template.spec.containers.readinessProbe.httpGet

...

   port	<string> -required-
     Name or number of the port to access on the container. Number must be in
     the range 1 to 65535. Name must be an IANA_SVC_NAME.
```

Note the `<string>` tag.

When I try to use this as the following in YAML:

```yaml
        readinessProbe:
          initialDelaySeconds: 2
          httpGet:
            path: "/"
            port: "80"
```

and pass it to `kubectl apply`, I get error:

```
$ kubectl apply -f deployment.yaml
The Deployment "hello-web" is invalid:
* spec.template.spec.containers[0].readinessProbe.httpGet.port: Invalid value: "80": must contain at least one letter or number (a-z, 0-9)
```

When I remove quotes and send to API as `port: 80` (as integer), it works.

It looks like the type information for this field is misleading. Maybe we should have a better error message for intorstring fields.

/sig api-machinery
