### ISSUE TITLE
Kubernetes does not delete pods within a deleted deployment

### ISSUE THREAD

**Issue by nils2504** [kubernetes/kubernetes#48385]
**BUG REPORT **:

> /kind  

**What happened**:
Deleting a deployment deletes the replica set as excepted but not the pods within this deployments. 

**What you expected to happen**:
The pods should be deleted as well.

**How to reproduce it (as minimally and precisely as possible)**:
Running on AWS (with kops) and Kubernetes v1.6.6

**Anything else we need to know?**:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  ports:
    - 
      port: 80
      targetPort: 10000
  selector:
    service: helloworld
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      service: helloworld
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: helloworld
    spec:
      containers:
      - 
        name: helloworld
        image: 'my.service.io/service/helloworld:latest'
        imagePullPolicy: Always
        ports:
        - containerPort: 10000
        command:
        - node
        args:
        - "app.js"
      imagePullSecrets:
      - name: my-screts
      restartPolicy: Always
      terminationGracePeriodSeconds: 30`
```

**Environment**:
- running on aws
- Debian GNU/Linux 8 (jessie)
- Kernel 4.4.65-k8s
- Install tools: kops
- Kuberentes v1.6.6
- Docker 1.12.6

@kubernetes/area workload-api/deployment
