### ISSUE TITLE
Azure File doesn't work in Windows agents

### ISSUE THREAD

**Issue by minherz** [kubernetes/kubernetes#48395]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Trying to use [azure_file](https://github.com/kubernetes/kubernetes/tree/master/examples/volumes/azure_file) volume as it is displayed worked when defining **beta.kubernetes.io/os:** `linux` and doesn't for `windows`. In case of the `windows` the folder is empty while for `linux` it contains files and folders that were imported into the share.

**What you expected to happen**:
The expected behavior should be same regardless of the **beta.kubernetes.io/os**

**How to reproduce it (as minimally and precisely as possible)**:
Create Azure File storage and update secret to match storage account and key like it is defined in the tutorial. Place some content into `k8stest` share to be able to validate the problem.

The example from the tutorial can be used to reproduce the valid behavior for **beta.kubernetes.io/os:** `linux`.

Use the following pod manifest to see that the folder is empty for `windows`.
```
apiVersion: v1
kind: Pod
metadata:
  name: azure-win
spec:
spec:
 containers:
  - image: kubernetes/pause
    name: azure-win
    volumeMounts:
      - name: azure
        mountPath: c:/mnt/azure
 volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: k8stest
          readOnly: false
 nodeSelector:
  beta.kubernetes.io/os: windows
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
`Azure`

- OS (e.g. from /etc/os-release):
`Windows 2016 Datacenter`

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
Kubernetes cluster was created using ACS wizard with 1 master and 2 Windows agents
