### ISSUE TITLE
When deleting rbd PVCs, corresponding PV goes into failed state

### ISSUE THREAD

**Issue by BastiPaeltz** [kubernetes/kubernetes#48471]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I first created a RBD StorageClass. Mounting and using this works fine. However when I delete a PVC and check the corresponding PV, it says `released` for a few seconds before going into `failed` state.
Example:

```
$ kubectl describe pv pvc-b7f4ef92-60be-11e7-8bb1-fa163e97a37e

Name:		pvc-b7f4ef92-60be-11e7-8bb1-fa163e97a37e
Labels:		<none>
StorageClass:	
Status:		Failed
Claim:		default/datadir-zk-hadoop-alpha-0
Reclaim Policy:	Delete
Access Modes:	RWO
Capacity:	7Gi
Message:	exit status 1
Source:
    Type:		RBD (a Rados Block Device mount on the host that shares a pod's lifetime)
    CephMonitors:	[192.168.0.180:6789 192.168.0.181:6789 192.168.0.182:6789]
    RBDImage:		kubernetes-dynamic-pvc-b7fc6578-60be-11e7-9ae1-fa163e97a37e
    FSType:		
    RBDPool:		kubernetes
    RadosUser:		admin
    Keyring:		/etc/ceph/keyring
    SecretRef:		&{ceph-secret}
    ReadOnly:		false
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  10m		10m		1	{persistentvolume-controller }			Warning		VolumeFailedDelete	exit status 1
```
I tried to get this working since I started using RBD on Kubernetes. First I ran into [this](https://github.com/kubernetes/kubernetes/issues/44206) bug which then got fixed. I tried again and saw `exit status 1` immeadiately after deleting the PVC. I then checked the Kubelet logs and saw similar logs as [here](https://github.com/kubernetes/kubernetes/issues/42701), so I waited until this was included in a stable release and tried again. It now, like I mentioned, at least shows `released` for a few seconds.

**What you expected to happen**:
I expected the PV to get released successfully.

**How to reproduce it (as minimally and precisely as possible)**:
You have to have a working ceph cluster in place.

1. Create a rbd StorageClass
```
# Created the secret with :
# kubectl create secret generic ceph-secret --type="kubernetes.io/rbd" --from-literal=key='MY_CEPH_ADMIN_CLIENT_KEY' --namespace=kube-system

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kube-system
  name: standard
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.0.180:6789,192.168.0.181:6789,192.168.0.182:6789 # all monitors nodes, comma-delimited
  adminSecretName: ceph-secret                              
  adminSecretNamespace: kube-system
  pool: kubernetes                                            # created with 'ceph osd pool create kubernetes 32 32'
  userSecretName: ceph-secret
```
2. Create a PVC
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim-1
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```
3. Create a pod that will use the PVC
```
# sample volume claim
apiVersion: v1
kind: ReplicationController
metadata:
  name: test-pvc-nginx
spec:
  replicas: 1
  selector:
    role: test-pvc-nginx
  template:
    metadata:
      labels:
        role: test-pvc-nginx
    spec:
      containers:
      - name: test1
        image: nginx
        volumeMounts:
          - mountPath: /var/lib/www/html
            name: nginx-pvc
      volumes:
        - name: nginx-pvc
          persistentVolumeClaim:
            claimName: myclaim-1
```
4. Delete the PVC
```
$ kubectl delete pvc myclaim-1
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0+coreos.0", GitCommit:"8c1bf133b4129042ef8f7d1ffac1be14ee83ed10", GitTreeState:"clean", BuildDate:"2017-06-30T17:46:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**: Bare Metal 
- OS (e.g. from /etc/os-release): 
```NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux kubernetes-5 3.10.0-327.36.2.el7.x86_64 #1 SMP Mon Oct 10 23:08:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: Kargo/Kubespray
- Others:
Kubelet docker container:
```
/usr/bin/docker
run
--net=host
--pid=host
--privileged
--name=kubelet
--restart=on-failure:5
--memory=512M
--cpu-shares=100
-v/dev:/dev:rw
-v/etc/cni:/etc/cni:ro
-v/opt/cni:/opt/cni:ro
-v/root/.docker:/root/.docker:ro
-v/etc/ssl:/etc/ssl:ro
-v/etc/resolv.conf:/etc/resolv.conf
-v/etc/pki/tls:/etc/pki/tls:ro
-v/etc/pki/ca-trust:/etc/pki/ca-trust:ro
-v/lib/modules:/lib/modules:ro
-v/sys:/sys:ro
-v/var/lib/docker:/var/lib/docker:rw
-v/var/log:/var/log:rw
-v/var/lib/kubelet:/var/lib/kubelet:shared
-v/var/lib/cni:/var/lib/cni:shared
-v/var/run:/var/run:rw
-v/etc/kubernetes:/etc/kubernetes:ro
-v/etc/os-release:/etc/os-release:ro
quay.io/coreos/hyperkube:v1.7.0_coreos.0
./hyperkube
kubelet
--v=2
--address=192.168.0.179
--hostname-override=kubernetes-5
--allow-privileged=true
--pod-manifest-path=/etc/kubernetes/manifests
--pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0
--kube-reserved
cpu=100m,memory=512M
--node-status-update-frequency=10s
--cgroups-per-qos=False
--enforce-node-allocatable=
--cluster-dns=10.233.0.3
--cluster-domain=cluster.local
--resolv-conf=/etc/resolv.conf
--kubeconfig=/etc/kubernetes/node-kubeconfig.yaml
--require-kubeconfig
--node-labels=node-role.kubernetes.io/node=true
--network-plugin=cni
--network-plugin-dir=/etc/cni/net.d
--cni-bin-dir=/opt/cni/bin
```
