### ISSUE TITLE
service resource support set-based selector

### ISSUE THREAD

**Issue by aloisio31** [kubernetes/kubernetes#48528]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What you expected to happen**:
As the [doc][1] says:

> Newer resources, such as Job, Deployment, Replica Set, and Daemon Set, support set-based requirements as well.

  [1]: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

I want to get _endpoints_ by _service_ that select _pods_ with **key** = **v1** or **v2**. Is there any way to do so?

/sig api-machinery

**Comment by aloisio31** [comment]
@kubernetes/sig-api-machinery-*

**Comment by caseydavenport** [comment]
I wonder if there is a plan floating around for how to move from old-style selectors to the newer syntax. Anyone have a link?

Sounds like a worthwhile improvement - folks can create Deployments with selectors which can't be expressed on a Service today, which isn't great.

**Comment by lavalamp** [comment]
Reverse label selector queries is a longstanding request. #1348.

**Comment by caseydavenport** [comment]
Perhaps I misunderstood, but I didn't think this was a request for reverse-label selector queries. 

I interpreted this to be "Add [set-based label selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement) support to Services"

**Comment by aloisio31** [comment]
@lavalamp My issue has nothing to do with _reverse label selector_. I mean **create** a _service_ which has [set-based label selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement). @caseydavenport knows clearly.

**Comment by zegelin** [comment]
@lavalamp Can we re-open this issue? As @aloisio31 and @caseydavenport mentioned, this request has nothing to do with reverse label selector queries. Instead it's about allowing Services to support the newer set-based selector syntax, similar to Jobs and Deployments.

I stumbled onto this issue after I realised that Services don't support this. I'm trying to create a headless service for Cassandra seed node discovery. Ideally, the seeds Service should only return a subset of Pods, e.g., the first 3 Pods out of a 9 Pod StatefulSet.

For example, given this Service, which currently will discover _all_ Cassandra nodes.
```
apiVersion: v1
kind: Service
metadata:
...
spec:
  clusterIP: None
  ports:
  - name: internode
    port: 7000
    protocol: TCP
    targetPort: 7000
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/managed-by: com.instaclustr.cassandra-operator
    cassandra-operator.instaclustr.com/datacenter: test-dc
  sessionAffinity: None
  type: ClusterIP
```

It would be nice to have the `selector` instead be:

```
selector:
  matchLabels:
    app.kubernetes.io/managed-by: com.instaclustr.cassandra-operator
    cassandra-operator.instaclustr.com/datacenter: test-dc
  matchExpressions:
    - {key: statefulset.kubernetes.io/pod-name, operator: In, values:[cassandra-test-dc-0, cassandra-test-dc-1, cassandra-test-dc-2]}
```

to only select the first 3 Pods in the StatefulSet.

**Comment by lavalamp** [comment]
Sorry, I read the OP as looking up endpoints belonging to services whose selector selected given pods, I still think that's a pretty reasonable way to read that sentence :)

This is between sig network and api reviewers.

/remove-sig api-machinery

**Comment by wwftw** [comment]
@lavalamp Do you expect this to be on the road map soon? If not, we have a use case that requires this change and I'd like to contribute when I get time. I assume this would be a passive change which requires the service object schema uplifts and corresponding endpoints controller, is there a guideline to propose such API changes/additions?

**Comment by wwftw** [comment]
bump

**Comment by XanderStrike** [comment]
@lavalamp we're still interested in this feature. Has it been implemented and I just can't find it anywhere? This shouldn't be closed if the outcome hasn't been accomplished.

**Comment by lavalamp** [comment]
/reopen

This is up to SIG Network, not me. Added the triage-needed label.

**Comment by thockin** [comment]
This requires evolving the Service API.  The problem is backwards compat.  It has always been the case that a service with an empty `selector` means `manual`.  I am not sure that adding a second field would be compatible with that, but I (or someone) will have to think through the various ways this can be used.  It might be doable.

A heavier approach would be to treat this like pluralization - intercept REST operations and divine the user's intention.  This will require more careful thought and a KEP.  E.g. If an update changes `selector` but `newSelector` is non-empty, automatically clear `newSelector`.

@khenidak for thoughts

**Comment by hnhbwlp** [comment]
@lavalamp  We still have demand for this feature. We have a scenario where the traffic of a specified pod needs to be arbitrarily removed. Of course, this requirement can be completed through labels, but because pod is created through workload, and the business needs to modify the workload to keep unanimous of workload templete and pod  , which may cause pod reconstruction, which is not what we expect.

**Comment by lavalamp** [comment]
@hnhbwlp Please take this to SIG Network. I'm not blocking this, but I won't have time to work on it either.

**Comment by thockin** [comment]
I acknowledge the desire for this, but we have to think carefully about how
to represent it in a compatible way.

**Comment by antoineozenne** [comment]
Another use case: simplify static analysis of resources. For example, we use kyverno to control which labels are used in all resources selectors. Currently, we have to do that differently for services.

**Comment by dprotaso** [comment]
Is there a KEP for this issue?

**Comment by thockin** [comment]
No KEP that I know of.

**Comment by YashJainSC** [comment]
@zegelin I am also having similar requirement as your's for a headless service, have you figured out any another solution for it ?

**Comment by khenidak** [comment]
I have put together a high level proposal here: https://docs.google.com/document/d/1cXvMOvZOA4aN0bXmr8-8uW54l6z4tCpj7WqgX6-RY6A/edit?usp=sharing

The doc is WIP and will eventually make it to KEP and follow the process. The doc is meant to set the tone gain early high level consensus and to understand the complexity of that particular change

**Comment by FillZpp** [comment]
Hi @khenidak , how is this going? We also have demand for this feature. I'd like to submit a KEP mostly based on your proposal if you don't have enough time to work on this :)

**Comment by khenidak** [comment]
@FillZpp  (apologies, was away on a long sabbatical) - Yes lets start the process a kep will help align people around the best approach.

**Comment by uablrek** [comment]
The `matchExpressions` statement can be used. Is that enough?

Examples:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [app-1]}
  replicas: 6
  template:
    metadata:
      labels:
        app: app-1
        group: a
    spec:
      containers:
      - name: mserver
        imagePullPolicy: IfNotPresent
        image: registry.nordix.org/cloud-native/mserver:latest
        ports:
        - containerPort: 5001
        securityContext:
          privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: [app-2]
  replicas: 6
  template:
    metadata:
      labels:
        app: app-2
        group: a
    spec:
      containers:
      - name: mserver
        imagePullPolicy: IfNotPresent
        image: registry.nordix.org/cloud-native/mserver:latest
        ports:
        - containerPort: 5001
        securityContext:
          privileged: true
```

**Comment by ghalib5000** [comment]
the matchExpressions doesn't work with Service, it would be nice if we get something like that for services

**Comment by uablrek** [comment]
No, but it _can_ be used to define a service that selects endpoints from _many_ deployments/daemonsets.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: app-1
spec:
  selector:
    app: app-1
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: app-2
spec:
  selector:
    app: app-2
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
---
apiVersion: v1
kind: Service
metadata:
  name: group-a
spec:
  selector:
    group: a
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
```
In this example the first service will get endpoints from the first deployment, the second from the second, but the third will _get endpoints from both deployments_. I assumed that was what you wanted.
