### ISSUE TITLE
Updating service to NodePort type gets port lost

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#48579]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig network
/cc @thockin @smarterclayton @freehan 
/assign

**What happened**:

1. Create a ClusterIP type service
```
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: ClusterIP
  ports:
  - port: 53
    name: port-tcp
    protocol: TCP
    targetPort: 6502
  selector:
    bar: baz
```

```
# kubectl describe svc foo 
Name:			foo
Namespace:		default
Labels:			<none>
Annotations:		<none>
Selector:		bar=baz
Type:			ClusterIP
IP:			192.168.100.251
Port:			port-tcp	53/TCP
Endpoints:		<none>
Session Affinity:	None
Events:			<none>
```

2. Edit the service. Change it's type to NodePort and add a Port. 
Note: the new port has same port number but protocol with the existing Port.
```
spec:
  clusterIP: 192.168.100.251
  ports:
  - name: port-tcp
    port: 53
    protocol: TCP
    targetPort: 6502
  ports:
  - name: port-udp
    port: 53
    protocol: UDP
    targetPort: 6502
  selector:
    bar: baz
  sessionAffinity: None
  type: NodePort
```

3. See the updated service. **The TCP Port was eaten.**
```
# kubectl describe svc foo 
Name:			foo
Namespace:		default
Labels:			<none>
Annotations:		<none>
Selector:		bar=baz
Type:			NodePort
IP:			192.168.100.251
Port:			port-udp	53/UDP
NodePort:		port-udp	31494/UDP
Endpoints:		<none>
Session Affinity:	None
Events:			<none>
```

**What you expected to happen**:
The updated service has both TCP and UDP ports.

**How to reproduce it (as minimally and precisely as possible)**:
See the step above.

**Anything else we need to know?**:
If I create a NodePort service with the above two ports, it works.
```
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: NodePort
  ports:
  - port: 53
    name: port-tcp
    protocol: TCP
    targetPort: 6502
  - port: 53
    name: port-udp
    protocol: UDP
    targetPort: 6502
  selector:
    bar: baz
```

```
# kubectl describe svc foo 
Name:			foo
Namespace:		default
Labels:			<none>
Annotations:		<none>
Selector:		bar=baz
Type:			NodePort
IP:			192.168.100.74
Port:			port-tcp	53/TCP
NodePort:		port-tcp	30680/TCP
Endpoints:		<none>
Port:			port-udp	53/UDP
NodePort:		port-udp	30680/UDP
Endpoints:		<none>
Session Affinity:	None
Events:			<none>
```

I write a test case to verify this case. I got a panic.
```
--- FAIL: TestUpdateNodePort (0.00s)
panic: duplicate node port [recovered]
	panic: duplicate node port

goroutine 116 [running]:
testing.tRunner.func1(0xc42022ca90)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x143d0c0, 0xc420064c90)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/pkg/registry/core/service.(*REST).updateNodePort(0xc4202bee10, 0xc4201cde00, 0xc420304f00, 0xc420051e38, 0x0, 0x0)
	/home/cloud/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/core/service/rest.go:616 +0x262
k8s.io/kubernetes/pkg/registry/core/service.TestUpdateNodePort(0xc42022ca90)
	/home/cloud/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/core/service/rest_test.go:1566 +0x1f2b
testing.tRunner(0xc42022ca90, 0x16e9718)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
FAIL	k8s.io/kubernetes/pkg/registry/core/service	0.130s
make: *** [test] Error 1
```

The root cause is as below. _We should take another look at this logic._
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/service/rest.go#L614-L617
```GO
// Detect duplicate node ports; this should have been caught by validation, so we panic
if contains(newNodePorts, nodePort) {
	panic("duplicate node port")
}
```

BTW: #46197 changed some related code but it doesn't change the logic here. So I believe this bug is not introduced by #46197. I also tested this on v1.5.1, it has the same issue.

**Environment**:
- Kubernetes version (use `kubectl version`): HEAD a9bf44101b3ec13a3e94df926c95ba5384d18e28
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiangpengzhao** [comment]
I will be OOO the next week. Since this bug is not so urgent, I will fix it ASAP when I'm back. Folks who are interested in this can take it :) BTW, I can join in the discussion from my phone.

**Comment by cblecker** [comment]
I'm not sure this is a bug. In the first configuration yaml, you're defining the ports array twice. I'm the second, you're only defining it once. The ports array should only be defined once.

**Comment by xiangpengzhao** [comment]
@cblecker Did you mean the below yaml by `the first configuration yaml`? 
```yaml
spec:
  clusterIP: 192.168.100.251
  ports:
  - name: port-tcp
    port: 53
    protocol: TCP
    targetPort: 6502
  ports:
  - name: port-udp
    port: 53
    protocol: UDP
    targetPort: 6502
  selector:
    bar: baz
  sessionAffinity: None
  type: NodePort
```

Please note that the two ports have same port number but different protocols. This is allowed.

**Comment by cblecker** [comment]
Yes, that's the one I meant. But note you have "ports:" twice.

**Comment by xiangpengzhao** [comment]
Ah, thanks for pointing it out! This might be the cause. But I remembered I also tested the case without the second `ports` line, it had the same issue. I can't verify this now. Will test it when I'm back to my keyboard.

**Comment by xiangpengzhao** [comment]
I try the case without the second `ports` line, the issue also exists. So I believe there IS a bug here.
Seems like there might be two issues here:
- a port is lost as is described in this issue.
- we shouldn't allow to configure two `ports` lines in the manifest. i.e. we should add validation for this case.

**Comment by cblecker** [comment]
@xiangpengzhao can you please provide (or edit) example YAMLs then to allow for attempts at duplication?

**Comment by xiangpengzhao** [comment]
Update: reproducing without the extra `ports` line.

1. Create a ClusterIP type service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: ClusterIP
  ports:
  - port: 53
    name: port-tcp
    protocol: TCP
    targetPort: 6502
  selector:
    bar: baz
```
```
# kubectl describe svc foo
Name:			foo
Namespace:		default
Labels:			<none>
Annotations:		<none>
Selector:		bar=baz
Type:			ClusterIP
IP:			192.168.100.100
Port:			port-tcp	53/TCP
Endpoints:		<none>
Session Affinity:	None
Events:			<none>
```

2. Edit the service (`kubectl edit svc foo`). Change it's type to NodePort and add a Port which has the same port number but different protocol with the existing Port.
```yaml
spec:
  clusterIP: 192.168.100.100
  ports:
  - name: port-tcp
    port: 53
    protocol: TCP
    targetPort: 6502
  - name: port-udp
    port: 53
    protocol: UDP
    targetPort: 6502
  selector:
    bar: baz
  sessionAffinity: None
  type: NodePort
```

3. Describe the updated service. We can see that the UDP Port was not created.
```
# kubectl describe svc foo
Name:			foo
Namespace:		default
Labels:			<none>
Annotations:		<none>
Selector:		bar=baz
Type:			NodePort
IP:			192.168.100.100
Port:			port-tcp	53/TCP
NodePort:		port-tcp	32257/TCP
Endpoints:		<none>
Session Affinity:	None
Events:			<none>
```

I have dug into the code and will send a patch to fix it.

@cblecker
