### ISSUE TITLE
Should not support HPA for DaemonSet

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#48588]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig apps

**What happened**:
I can create a HPA policy for DaemonSet, this is not right as the DaemonSet do not have `replicas` and the HPA should validate this when create the HPA policy.

**What you expected to happen**:
The HPA should have some validation to make sure we cannot create HPA policy for DaemonSet.

**How to reproduce it (as minimally and precisely as possible)**:
1. HPA file as following:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscale
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: DaemonSet
    name: mysql
  targetCPUUtilizationPercentage: 10
```

2. Create the policy.
```
root@pc001:~/cases/ss# kubectl create -f ./hpa.yaml
horizontalpodautoscaler "autoscale" created
root@pc001:~/cases/ss# kubectl get hpa
NAME        REFERENCE         TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
autoscale   DaemonSet/mysql   <unknown> / 10%   2         5         0          7s
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
