### ISSUE TITLE
skydns/kube2sky replication controller doesn't bind volumes and starts only one container out of two

### ISSUE THREAD

**Issue by sokoow** [kubernetes/kubernetes#48596]
/kind bug
/sig api-machinery
@kubernetes/sig-api-machinery-*

**What happened**:
When trying to mount hostPath to skydns/kube2sky replication controller, it's not being mounted at all. Also, when volume/volumeMount sections of yaml are added to kube2sky, 2nd container in replication controller which is skydns never starts.

**What you expected to happen**:
I should be able to add hostPath volume to replication controller and both containers should be running inside it.

**How to reproduce it (as minimally and precisely as possible)**:
use the following manifest:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v11
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v11
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 3
  selector:
    k8s-app: kube-dns
    version: v11
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v11
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.15
        resources:
          limits:
            cpu: 100m
            # Kube2sky watches all pods.
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
        args:
        - --domain=cluster.local
        - --kubecfg-file=/etc/kubernetes/kube2sky.kubeconfig3
        - --etcd-server=http://10.255.13.246:2379
       volumeMounts:
        - mountPath: /etc/kubernetes
          name: etcvol
      volumes:
      - hostPath:
          path: /etc/kubernetes
        name: etcvol
     

          - name: skydns
            image: gcr.io/google_containers/skydns:1.0
            resources:
              limits:
                cpu: 100m
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 50Mi
            args:
            - -machines=http://10.255.13.246:2379
            - -addr=0.0.0.0:53
            - -ns-rotate=false
            - -domain=cluster.local.
            ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          volumes:
          - name: etcd-storage
            emptyDir: {}
          dnsPolicy: Default  # Don't use cluster DNS.

``` 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"a55267932d501b9fbd6d73e5ded47d79b5763ce5", GitTreeState:"clean", BuildDate:"2017-04-14T13:36:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`): 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: ansible
- Others:

**Comment by sokoow** [comment]
It helped when I split the manifest into two replication controllers:

```
piVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v11-kube2sky
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v11
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 3
  selector:
    k8s-app: kube-dns
    version: v11
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v11
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.15
        resources:
          limits:
            cpu: 100m
            # Kube2sky watches all pods.
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
        args:
        - --domain=cluster.local
        - --kubecfg-file=/etc/kubernetes/kube2sky.kubeconfig
        - --etcd-server=http://10.255.12.33:2379
        volumeMounts:
        - mountPath: /etc/kubernetes
          name: etcvol
      volumes:
      - hostPath:
          path: /etc/kubernetes
        name: etcvol
```

and


```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v11-skydns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v11
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 3
  selector:
    k8s-app: kube-dns
    version: v11
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v11
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: skydns
        image: gcr.io/google_containers/skydns:1.0
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 50Mi
        args:
        - -machines=http://10.255.12.33:2379
        - -addr=0.0.0.0:53
        - -ns-rotate=false
        - -domain=cluster.local.
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      volumes:
      - name: etcd-storage
        emptyDir: {}
      dnsPolicy: Default  # Don't use cluster DNS.
```
