### ISSUE TITLE
kube-proxy 1.7.0: health check server bind to 127.0.0.1 despite set 0.0.0.0 via --healthz-bind-address 

### ISSUE THREAD

**Issue by r0bj** [kubernetes/kubernetes#48600]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
kube-proxy DaemonSet:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    component: kube-proxy
    k8s-app: kube-proxy
    kubernetes.io/cluster-service: "true"
    name: kube-proxy
    tier: node
  name: kube-proxy
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: kube-proxy
        k8s-app: kube-proxy
        kubernetes.io/cluster-service: "true"
        name: kube-proxy
        tier: node
    spec:
      containers:
      - command:
        - kube-proxy
        - --kubeconfig=/var/lib/kube-proxy/kubeconfig
        - --proxy-mode=iptables
        - --healthz-bind-address=0.0.0.0
        - --v=2
        image: gcr.io/google_containers/kube-proxy-amd64:v1.7.0
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kubeconfig
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kube-proxy
        name: kubeconfig
```

Note option `--healthz-bind-address=0.0.0.0`

Despite option `--healthz-bind-address=0.0.0.0` kube-proxy bind port 10249 to `127.0.0.1`:

```
# docker ps -qf "label=io.kubernetes.container.name=kube-proxy" | xargs docker inspect --format '{{.State.Pid}}'
3859
# nsenter -t 3859 -n netstat -pant |grep -i listen
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      2123/bird
tcp        0      0 127.0.0.1:8500          0.0.0.0:*               LISTEN      729/consul
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      905/dnsmasq
tcp        0      0 10.14.30.110:53         0.0.0.0:*               LISTEN      905/dnsmasq
tcp        0      0 10.14.30.110:22         0.0.0.0:*               LISTEN      786/sshd
tcp        0      0 127.0.0.1:8600          0.0.0.0:*               LISTEN      729/consul
tcp        0      0 10.14.30.110:5666       0.0.0.0:*               LISTEN      792/xinetd
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      1307/kubelet
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      3859/kube-proxy
tcp        0      0 10.14.30.110:8301       0.0.0.0:*               LISTEN      729/consul
tcp6       0      0 :::10256                :::*                    LISTEN      3859/kube-proxy
tcp6       0      0 ::1:53                  :::*                    LISTEN      905/dnsmasq
tcp6       0      0 :::4194                 :::*                    LISTEN      1307/kubelet
tcp6       0      0 :::10250                :::*                    LISTEN      1307/kubelet
tcp6       0      0 :::10255                :::*                    LISTEN      1307/kubelet
```

Note:
```
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      3859/kube-proxy
```

**What you expected to happen**:

kube-proxy should bind port 10249 (health check server) to 0.0.0.0.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): Ubuntu 14.04
- Kernel (e.g. `uname -a`):
Linux dev-k8s-deployer-p1 4.4.0-34-generic #53~14.04.1-Ubuntu SMP Wed Jul 27 16:56:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
