### ISSUE TITLE
Broken symlinks when mounting a subPath of a configMap volume

### ISSUE THREAD

**Issue by glennschmidt** [kubernetes/kubernetes#48656]
/kind bug

When I create any of the data mapping volume types (configMap, secret, projected), I can create an arbitrary directory hierarchy inside the volume using the 'path' option. However, if I try to mount one of these subdirectories (using the 'subPath' mount option) I get a mount that just contains broken symlinks.

This might be an accepted limitation rather than a bug, but if so it should probably be mentioned in the Volumes documentation. Currently it doesn't mention the fact that symlinks are used in these volumes, or that you need to always mount the root of the volume to prevent the symlinks from breaking.
https://kubernetes.io/docs/concepts/storage/volumes/

**What happened**:
1. I configured a volume containing items from a configMap projected at different paths.
2. I configured a container to mount a subpath of the volume.
3. The files in the mounted volume were inaccessible (broken symlinks).

**What you expected to happen**:
The files in the mounted volume contained the relevant configMap data.

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod with a configMap volume like:
```yaml
      volumes:
        - name: configs
          configMap:
            name: dev-app-1
            items:
            - key: db.conf
              path: database/db.conf
```
And a container with a volume mount like:
```yaml
        volumeMounts:
        - mountPath: /etc/db
          name: configs
          subPath: database
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.6
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): 4.4.65-k8s
