### ISSUE TITLE
Downward API support in volume subPath

### ISSUE THREAD

**Issue by fiatala** [kubernetes/kubernetes#48677]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

We would like a way to dynamically generate host paths when mounting volumes. The `subPath` feature creates directories on demand, but the names assigned to those directories are static.

Supporting the downward API variables would provide a good way to share storage and avoid collisions.
Centralized log storage is one use case.

For example, 

```
        volumeMounts:
        - mountPath: /var/log/mysql
          name: logs
          subPathFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: logs
        hostPath:
          path: /mnt/log-repo
```

Another option,

```
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /var/log/mysql
          name: logs
          subPath: $(NAME)
      volumes:
      - name: logs
        hostPath:
          path: /mnt/log-repo
```

Over time, the host storage would look something like this, and the containers would not need to change any of their logging logic.

```
/mnt/log-repo/mysql-1174854418-p8t02
/mnt/log-repo/mysql-1174854418-plsf8
/mnt/log-repo/mysql-3521978760-ns129
/mnt/log-repo/mysql-3521978760-s1m6x
/mnt/log-repo/mysql-3957873462-k4gg7
/mnt/log-repo/mysql-3957873462-rqsr1
```

**Comment by mtaufen** [comment]
I'm not sure I understand what you gain by using `$(NAME)` instead of `metadata.name` directly.

**Comment by fiatala** [comment]
To use `metadata.name` you need the extra scaffolding to support a map instead of a string - note that the key was changed from `subPath` to `subPathFrom` to align with ENV `value` and `valueFrom` pattern.
If you support `$(NAME)`, then it's still a string and can use the variable substitution work that is already in place for other sections of the file.

**Comment by mtaufen** [comment]
Ah, I see. I misread your example as saying that `subPathFrom` was the existing solution and you wanted to move to `subPath` with an env var.

**Comment by mtaufen** [comment]
Are there other cases where we plumb pod env vars to pod spec fields today?
@lavalamp wdyt about this? I'm wary of accidentally creating a templating solution.

**Comment by kevtaylor** [comment]
You can use expanded env vars in command line and args lines only. So that's how you can create a  unique subpath using an init container with a command line symbolic link but that solution is messy.

**Comment by mtaufen** [comment]
I'd rather not selectively allow env var expansion depending on the subfield of a config, that would be pretty confusing to users. I'd prefer the subPathFrom solution (downward api based) if you just want this for subPaths. Ofc we'd have to caution users not to reference fields that don't contain valid filenames.

**Comment by redbaron** [comment]
@mtaufen , `$()` expansion is already implemented for args and env vars, how expanding it for another field makes it confusing?

`subPathFrom` doesn't work very well as it doesn't allow things like:

`subPath: $(POD_NAMESPACE)/$(POD_NAME).dir` which is a real use case and pain point at least for us

**Comment by mtaufen** [comment]
If you only extend it to work in the subPath case, people will expect it to work everywhere and be confused that it doesn't. It would be interesting to have env var expansion work in arbitrary fields of the container spec, and I think it's worth discussing with a larger audience. I'd recommend writing a brief design doc in a PR against the community repo (see https://github.com/kubernetes/community/tree/master/contributors/design-proposals). It is a significant API decision, IMO.

General templating has been discussed a lot before, and we still don't have an implemented solution: 
- https://github.com/kubernetes/kubernetes/issues/11492
- https://github.com/kubernetes/community/blob/master/contributors/design-proposals/templates.md
- https://github.com/kubernetes/features/issues/35

But since this is a far more specific use-case, and you're only resolving variables for containers, it might get more traction.

**Comment by kevtaylor** [comment]
By adding the subpath doesnt in my opinion make it more confusing because it is already very restricted to only 2 elements. The current way of using an init container is much more confusing for an end user

**Comment by mtaufen** [comment]
@thockin @lavalamp @smarterclayton @devin-donnelly thoughts?

**Comment by rajasaur** [comment]
Im trying to do the same as what this issue is talking about.

But I dint understand @kevtaylor's comments about using an init-container to solve this. I have a init-container that can reference the pod's name(using env) and create a subdirectory in NFS specific to the pod , but how do I mount that subdirectory into my container. Should I use a postStart script to symlink the directory?

**Comment by kevtaylor** [comment]
@rajasaur `      - name: prep-logs
        image: alpine:3.5
        command:
        - /bin/sh
        - -xc
        - >
          LOGDIR=/logs/${POD_NAMESPACE}/${POD_NAME};
          mkdir -p ${LOGDIR}
          && ln -sfv ${LOGDIR} /workdir/logs
          && chmod -R ugo+wr ${LOGDIR}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /logs
          name: logs
        - mountPath: /workdir
          name: workdir`

**Comment by rajasaur** [comment]
Thanks @kevtaylor . I tried a similar approach earlier which led to an error of "file already exists" because the "Trick" that you mentioned wasnt happening in my case , i.e. once the symlink was created in the init container, when actually doing the volumemount subPath, it tried to create a path called "logs" (the subPath argument) and failed with "File already exists" error. Ill retry with your configuration and see what happens.

I worked around it with a postScript that does something like
```
        lifecycle:
           postStart:
              exec:
                 command: ["/bin/sh", "-c", "ln -s /workdir/logs/$PODNAME /container/logs"]
```
and exposing PODNAME as env variable.
