### ISSUE TITLE
Kubernetes persistentvolume capacity not work

### ISSUE THREAD

**Issue by killy001** [kubernetes/kubernetes#48701]
### the file pv.yaml like this:
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
```

### the file pvc.yaml like this:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 5Mi
    requests:
      storage: 5Mi
```

### the file pvpod.yaml like this:
```
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: docker.io/nginx:latest
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: task-pv-storage

```

When the hostpath /tmp/data or container path /usr/share/nginx/html size more than 5Mi, there is nothing happened. The shared volume size should less than 5Mi. I think the capacity does not work. Why?
