### ISSUE TITLE
podSecurityPolicy missing documentation for creating pod-creating objects

### ISSUE THREAD

**Issue by strowi** [kubernetes/kubernetes#49024]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Setting up PSP with RBAC after following the [docs](https://github.com/kubernetes/examples/blob/master/staging/podsecuritypolicy/rbac/README.md), i'm unable to create daemonsets/deployments.

**What you expected to happen**:
- privileged users should be able to run daemonsets/deployments etc.
- unprivileged users should be restricted

**How to reproduce it (as minimally and precisely as possible)**:
1. Followed https://github.com/kubernetes/examples/blob/master/staging/podsecuritypolicy/rbac/README.md, modified only policies:
```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  privileged: true
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  hostPorts:
  - min: 30000
    max: 65535
  volumes:
  - 'emptyDir'
  - 'gitRepo'
  - 'secret'
  - 'nfs'
  - 'persistentVolumeClaim'
  - 'downwardAPI'
  - 'configMap'
  - 'projected'
```

2.  created the following rolebindings for namespace 'test':
```
# create rolebindings granting admin within the namespace for
#  - ck-admin-restricted
#  - ck-admin-privileged
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: test-ck-admin
  namespace: test
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: ck-admin-restricted
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: ck-admin-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: test-ck-admin-privileged
  namespace: test
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: ck-admin-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: test-ck-admin-restricted
  namespace: test
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: ck-admin-restricted
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: ck-admin-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-psp-user
```

- failed Daemonset:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
```

Error-Message:
```2017-07-17 15:49:32 +0200 CEST   2017-07-17 15:44:04 +0200 CEST   48        node-exporter   DaemonSet             Warning   FailedCreate   daemon-set   Error creating: pods "node-exporter-" is forbidden: unable to validate against any pod security policy: [spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 9100: Host port 9100 is not allowed to be used.  Allowed ports: [] spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 9100: Host port 9100 is not allowed to be used.  Allowed ports: [{30000 65535}]]```

**Anything else we need to know?**:
Creating a single privileged pod works just fine.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.6
- Cloud provider or hardware configuration**: bare-metal
- OS (e.g. from /etc/os-release): coreos-1409.6.0
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig sig/auth
