### ISSUE TITLE
hpa scales below MinReplicas if desiredReplicas is zero

### ISSUE THREAD

**Issue by johanneswuerbach** [kubernetes/kubernetes#49028]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

hpa scales to `1` if desiredReplicas is zero

**What you expected to happen**:

hpa scales to MinReplicas if desiredReplicas is zero

**How to reproduce it (as minimally and precisely as possible)**:

Create a hpa with minReplicas set. E.g.

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec:
  minReplicas: 15
  maxReplicas: 60
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: api
  targetCPUUtilizationPercentage: 25
```

Create an `api` deployment with zero cpu usage. The deployment will start endlessly scaling between 1 and 15. With the following events logged:

```
2h        59s        22    horizontal-pod-autoscaler            Normal        SuccessfulRescale    New size: 1; reason: All metrics below target
2h        29s        22    horizontal-pod-autoscaler            Normal        SuccessfulRescale    New size: 15; reason: Current number of replicas below Spec.MinReplicas
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
