### ISSUE TITLE
allow multiple floatingnetworkids in openstack loadbalancer

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#49147]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

/kind feature

**What happened**: Currently we have kubernetes cluster installed, in node machines we have one subnet and two routers attached. One router for external network and one router for internal network. However, when we create type: loadbalancer services in kubernetes, we have to hardcode floatingnetwork id to only one of those (external or internal). 

**What you expected to happen**: I except that I could define from which floatingnetwork loadbalancer is taking its floating ip address in each service. One possible solution could be that if floatingnetworkid is defined like currently - that networkid is default one. Then we could have possibility to override that in each service configuration. 

Like if we do not want use default floating-pool we could change it:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
  name: redis
spec:
  type: LoadBalancer
  floating-poolid: <idhere>
  ports:
    - port: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis
```

I do not know does this even work in openstack, it might need some manual route settings in lbaas.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6
- Cloud provider or hardware configuration**: openstack
- OS (e.g. from /etc/os-release): centos

cc @anguslees @k8s-sig-openstack-feature-requests
