### ISSUE TITLE
resource quota doesn't handle resource with slash

### ISSUE THREAD

**Issue by ddysher** [kubernetes/kubernetes#49199]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I'm not sure if this is work as intended or we just haven't look into this; It's possible to create a resource quota with meaningless resource type, e.g.

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resources
spec:
  hard:
    requests.cpu: 2
    requests.storage: 10Gi
    abc/abc: 2
```

I'm working on local storage request/limit, which is the first standard resource type with slash. If this is work as intended, then it's hard to catch errors.

**What you expected to happen**:

Return error.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.116+ed724ee4aec1ca", GitCommit:"ed724ee4aec1ca3c881ec7b9af53fbaa2a066d34", GitTreeState:"clean", BuildDate:"2017-07-14T05:44:43Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}          
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2.432+defbe45397eb4c-dirty", GitCommit:"defbe45397eb4cc98b487326ce9622535e323cfd", GitTreeState:"dirty", BuildDate:"2017-07-19T10:32:10Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}    
```
