### ISSUE TITLE
Wrong HPA condition - ScalingLimited

### ISSUE THREAD

**Issue by chengzhang1016** [kubernetes/kubernetes#49256]
**What happened**:
Wrong HPA condition - ScalingLimited
1. I have one rc with 1 replica(current have 1 pod)
2. I have one hpa with spec.minReplicas=1 and spec.maxReplicas=10
HPA condition ScalingLimited is true and described by below, I expect ScalingLimited=false at that time.
```
  ScalingLimited    True    TooFewReplicas        the desired replica count was less than the minimum replica count
```

**What you expected to happen**:
I expect ScalingLimited=false at above time

**How to reproduce it (as minimally and precisely as possible)**:
1. Start kubernetes with DNS
2. Start api server with --runtime-config="api/all=true"
3. Build binaries and images, deploy heapster, influxdb and grafana in kubernetes
4. Create a rc
```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: hello-hpa-cpu
  name: hello-hpa-cpu
spec:
  replicas: 2
  selector:
    run: hello-hpa-cpu
  template:
    metadata:
      labels:
        run: hello-hpa-cpu
    spec:
      containers:
      - image: docker.io/ocpqe/hello-hpa:latest
        imagePullPolicy: IfNotPresent
        name: hello-hpa
        resources:
          requests:
            cpu: 200m
      restartPolicy: Always
```
5. Create a v2 hpa
```
apiVersion: autoscaling/v2alpha1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-resource-metrics-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: ReplicationController
    name: hello-hpa-cpu
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
```
6. Check hpa conditions by `kubelet describe hpa`
```
# kc describe hpa
Name:							hpa-resource-metrics-cpu
Namespace:						default
Labels:							<none>
Annotations:						<none>
CreationTimestamp:					Wed, 19 Jul 2017 05:58:14 -0400
Reference:						ReplicationController/hello-hpa-cpu
Metrics:						( current / target )
  resource cpu on pods  (as a percentage of request):	0% (0) / 50%
Min replicas:						1
Max replicas:						10
ReplicationController pods:				1 current / 1 desired
Conditions:
  Type			Status	Reason			Message
  ----			------	------			-------
  AbleToScale		True	ReadyForNewScale	the last scale time was sufficiently old as to warrant a new scale
  ScalingActive		True	ValidMetricFound	the HPA was able to succesfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited	True	TooFewReplicas		the desired replica count was less than the minimum replica count
```
I expect ScalingLimited of hpa conditions should be:
```
ScalingLimited    False    DesiredWithinRange    the desired replica count is within the acceptible range
```

**Addition info**:
```
# kubelet get hpa
NAME                       REFERENCE                             TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
hpa-resource-metrics-cpu   ReplicationController/hello-hpa-cpu   0% / 50%   1         10        1          2m
# kubelet get rc
NAME            DESIRED   CURRENT   READY     AGE
hello-hpa-cpu   1         1         1         44s
# kubelet get pod
NAME                  READY     STATUS    RESTARTS   AGE
hello-hpa-cpu-97qpb   1/1       Running   0          49s
```
