### ISSUE TITLE
"kubectl edit svc foo" fails to update ports

### ISSUE THREAD

**Issue by xiangpengzhao** [kubernetes/kubernetes#49295]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig cli
/cc @deads2k @fabianofranz 

**What happened**:
#48579 describes an issue about updating service to NodePort type gets port lost (Repro steps: https://github.com/kubernetes/kubernetes/issues/48579#issuecomment-316324543). Service update has a bug associated with this issue and PR #49258 is trying to fix it. 

When I verify #49258 on my env, unfortunately the issue still exists. However, the e2e test succeeds:
 https://github.com/kubernetes/kubernetes/pull/49258/files#diff-20a4e2095b63ecd60dd25e78bcd67372.

So, seems like `kubectl edit svc foo` has an issue in this case. It will get port lost after editing.

**What you expected to happen**:
`kubectl edit svc foo` makes the service have the added UDP port.

**How to reproduce it (as minimally and precisely as possible)**:
In order to get more evidence, I simply add below printing at https://github.com/xiangpengzhao/kubernetes/blob/26ad3007c1ed857d7bfdce2945b035b67b4fcb97/pkg/registry/core/service/rest.go#L374

```go
       glog.Errorf("After converting obj to service, port info:")
       for _, svcPort := range service.Spec.Ports {
               glog.Errorf("Name: %s, protocol: %s, port: %d, nodeport: %d", svcPort.Name, svcPort.Protocol, svcPort.Port, svcPort.NodePort)
       }
```

Then I follow the repro steps: https://github.com/kubernetes/kubernetes/issues/48579#issuecomment-316324543. After `kubectl edit svc foo` and saving, I get the result printing:

```
After converting obj to service, port info:
Name: port-tcp, protocol: TCP, port: 53, nodeport: 0
```
_Note that there isn't the added UDP port info._ Seems like `kubectl edit svc foo` doesn't save the new UDP port info.

**Anything else we need to know?**:
If I edit an existing NodePort service to add a port with same port number but different protocols, it still fails.

```yaml
spec:
  clusterIP: 192.168.100.44
  externalTrafficPolicy: Cluster
  ports:
  - name: port-tcp
    nodePort: 31147
    port: 53
    protocol: TCP
    targetPort: 6502
  selector:
    bar: baz
  sessionAffinity: None
  type: NodePort
```
edit to:
```yaml
spec:
  clusterIP: 192.168.100.44
  externalTrafficPolicy: Cluster
  ports:
  - name: port-tcp
    nodePort: 31147
    port: 53
    protocol: TCP
    targetPort: 6502
  - name: port-udp
    nodePort: 31147
    port: 53
    protocol: UDP
    targetPort: 6502
  selector:
    bar: baz
  sessionAffinity: None
  type: NodePort
```

I get the result print. The added UDP port also gets lost.
```
After converting obj to service, port info:
Name: port-tcp, protocol: TCP, port: 53, nodeport: 31147
```

**Environment**:
- Kubernetes version (use `kubectl version`): HEAD
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by deads2k** [comment]
@kubernetes/sig-cli-bugs

**Comment by xiangpengzhao** [comment]
Furthermore, if I add a UDP port with different port number by `kubectl edit`, it works!

```yaml
spec:
  clusterIP: 192.168.100.44
  externalTrafficPolicy: Cluster
  ports:
  - name: port-tcp
    nodePort: 31147
    port: 53
    protocol: TCP
    targetPort: 6502
  - name: port-udp
    nodePort: 31147
    port: 55                 ------------->note the different number here
    protocol: UDP
    targetPort: 6502
  selector:
    bar: baz
  sessionAffinity: None
  type: NodePort
```

result printing:
```
After converting obj to service, port info:
Name: port-tcp, protocol: TCP, port: 53, nodeport: 31147
Name: port-udp, protocol: UDP, port: 55, nodeport: 31147
```

```
#kubectl describe svc foo 
Name:			foo
Namespace:		default
Labels:			<none>
Annotations:		<none>
Selector:		bar=baz
Type:			NodePort
IP:			192.168.100.44
Port:			port-tcp	53/TCP
NodePort:		port-tcp	31147/TCP
Endpoints:		<none>
Port:			port-udp	55/UDP
NodePort:		port-udp	31147/UDP
Endpoints:		<none>
Session Affinity:	None
Events:			<none>
```
