### ISSUE TITLE
Issue with array type descriptions in OpenAPI Schema

### ISSUE THREAD

**Issue by garethr** [kubernetes/kubernetes#49325]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Validating a description of a deployment with a null `args` value against the JSON Schema from the OpenAPI document throws a validation error.

**What you expected to happen**:

Validating a description of a deployment with a null `args` value against the JSON Schema from the OpenAPI document does not throw a validation error.

**How to reproduce it (as minimally and precisely as possible)**:

Save the following as `valid-deployment.yaml`. This code sample is taken from the dashboard documentation at https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml.

```yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
    spec:
      containers:
      - name: kubernetes-dashboard
        image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.1
        ports:
        - containerPort: 9090
          protocol: TCP
        args:
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          # - --apiserver-host=http://my-address:port
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
      serviceAccountName: kubernetes-dashboard
      # Comment the following tolerations if Dashboard must not be deployed on master
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
```

To use a simple jsonschema tool we need to convert this to JSON with the following oneliner.

```
python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' < valid-deployment.yaml > valid-deployment.json
```

Grab the latest deployment schema. These are the same contents from the Kubernetes OpenAPI specification. More details at https://www.morethanseven.net/2017/06/26/schemas-for-kubernetes-types/.

```
wget https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/master-standalone/deployment.json
```

The install the Python jsonschema client https://github.com/Julian/jsonschema and try and validate the document.

```
pip install jsonschema
jsonschema -i valid-deployment.json deployment.json
None: None is not of type u'array'
```

**Anything else we need to know?**:

This issue came up with the following `kubeval` issue report: https://github.com/garethr/kubeval/issues/14

Enquiring about this on SIG API Machinery @deads2k said:

> When we introduced protobuf, the ability to distinguish between null and empty arrays was lost. 
> We ended up compromising and treating the two the same, empty as I recall.
> The behavior of all arrays in the API should be consistent.

I think this applies to any arrays described in the openapi document at https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json, (for instance deployment args which raised the original issue https://github.com/garethr/kubernetes-json-schema/blob/master/master-standalone/deployment.json#L2720-L2726) 

instead of them being:

```
"type": "array"
```

It should be:

```
"type": [ "array", "null" ]
```
