### ISSUE TITLE
"an empty namespace may not be set when a resource name is provided"

### ISSUE THREAD

**Issue by humblec** [kubernetes/kubernetes#49376]
Noticed below error message in logs with latest kube and glusterfs plugin.

```
E0721 12:42:10.108878    6212 glusterfs.go:150] glusterfs: failed to get endpoints pvc-1983190d-6de1-11e7-ad35-c85b7636c232[an empty namespace may not be set when a resource name is provided]

E0721 12:42:10.109019    6212 reconciler.go:367] Could not construct volume information: MountVolume.NewMounter failed for volume "kubernetes.io/glusterfs/d8a5cdc1-6de1-11e7-ad35-c85b7636c232-pvc-1983190d-6de1-11e7-ad35-c85b7636c232" (spec.Name: "pvc-1983190d-6de1-11e7-ad35-c85b7636c232") pod "d8a5cdc1-6de1-11e7-ad35-c85b7636c232" (UID: "d8a5cdc1-6de1-11e7-ad35-c85b7636c232") with: an empty namespace may not be set when a resource name is provided

````
~~~
[root@localhost demo]# kubectl get ep,svc
NAME                           ENDPOINTS                                                    AGE
ep/glusterfs-dynamic-claim11   172.17.0.1:1,192.168.10.100:1,192.168.10.101:1 + 1 more...   36m
ep/kubernetes                  192.168.43.105:6443                                          37m

NAME                            TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
svc/glusterfs-dynamic-claim11   ClusterIP   10.0.0.120   <none>        1/TCP     36m
svc/kubernetes                  ClusterIP   10.0.0.1     <none>        443/TCP   37m
[root@localhost demo]# kubectl get pod
NAME           READY     STATUS    RESTARTS   AGE   
gluster-pod2   1/1       Running   0          31m
[root@localhost demo]#
~~~
The subjected code path is :

https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/glusterfs/glusterfs.go#L150

I failed to get  how come a pod namespace can become empty  or the reason for this error message.

Any thoughts on this ?

**Comment by humblec** [comment]
@kubernetes/sig-storage

**Comment by humblec** [comment]
@rootfs @jsafrane Any thoughts on the possibility of this error ?

**Comment by rootfs** [comment]
Is the `gluster-pod` using the endpoint? Can you post pod yaml and `kubecctl describe pod` ?

**Comment by humblec** [comment]
```
[root@localhost demo]# cat nginx1.yaml 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    name: gluster-pod2
  name: gluster-pod2
spec: 
  containers: 
    - 
      image: "gcr.io/google_containers/nginx-slim:0.8"
      name: gluster-pod2
      ports: 
        - 
          containerPort: 80
          name: web
      securityContext: 
        privileged: true
      volumeMounts: 
        - 
          mountPath: /usr/share/nginx/html
          name: gluster-vol1
  volumes: 
    - 
      name: gluster-vol1
      persistentVolumeClaim: 
        claimName: claim11
```

@rootfs this pod use claim11 which has `glusterfs-dynamic-claim11` as its endpoint.  I was able to run this pod successfully. So I am in doubt that, this error comes somewhere in pod lifecycle, but wondering in which state it can say POD dont have a namespace.
