### ISSUE TITLE
DNS can not resolve service name in pod

### ISSUE THREAD

**Issue by justlooks** [kubernetes/kubernetes#49482]
> Environment:
> 
> Kubernetes version (use kubectl version): v1.7.0
> Cloud provider or hardware configuration**:
> OS (e.g. from /etc/os-release): CentOS 7
> Kernel (e.g. uname -a): Linux k8s-master 3.10.0-514.6.2.el7.x86_64
> Install tools: Kubeadm
> Others:
> docker version : Docker version 1.12.6,
> My RPM version :
> docker-1.12.6-16.el7.centos.x86_64.rpm
> kubectl-1.7.0-0.x86_64.rpm
> kubernetes-cni-0.5.1-0.x86_64.rpm
> kubeadm-1.7.0-0.x86_64.rpm
> kubelet-1.7.0-0.x86_64.rpm
> 

```
> > [root@k8s-master ~]#  kubectl get svc,rc,pod --namespace=kube-system -o wide
> > NAME                       CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE       SELECTOR
> > svc/heapster               10.110.5.9       <none>        80/TCP          3h        k8s-app=heapster
> > svc/kube-dns               10.96.0.10       <none>        53/UDP,53/TCP   4h        k8s-app=kube-dns
> > svc/kubernetes-dashboard   10.109.61.86     <nodes>       80:30725/TCP    3h        k8s-app=kubernetes-dashboard
> > svc/monitoring-grafana     10.103.214.165   <nodes>       80:31136/TCP    1h        k8s-app=grafana
> > svc/monitoring-influxdb    10.101.54.21     <none>        8086/TCP        3h        k8s-app=influxdb
> > 
> > NAME                                       READY     STATUS    RESTARTS   AGE       IP              NODE
> > po/etcd-k8s-master                         1/1       Running   0          4h        10.132.41.234   k8s-master
> > po/heapster-2994581613-7ppn7               1/1       Running   0          3h        172.16.2.6      k8s-node2
> > po/kube-apiserver-k8s-master               1/1       Running   0          4h        10.132.41.234   k8s-master
> > po/kube-controller-manager-k8s-master      1/1       Running   0          4h        10.132.41.234   k8s-master
> > po/kube-dns-2425271678-cqm2n               3/3       Running   0          4h        172.16.0.2      k8s-master
> > po/kube-flannel-ds-18dr4                   2/2       Running   0          4h        10.132.41.234   k8s-master
> > po/kube-flannel-ds-vpkpb                   2/2       Running   0          3h        10.165.97.219   k8s-node1
> > po/kube-flannel-ds-x3n24                   2/2       Running   0          3h        10.161.233.80   k8s-node2
> > po/kube-proxy-2xhn9                        1/1       Running   0          4h        10.132.41.234   k8s-master
> > po/kube-proxy-7hmmx                        1/1       Running   0          3h        10.165.97.219   k8s-node1
> > po/kube-proxy-h1gmc                        1/1       Running   0          3h        10.161.233.80   k8s-node2
> > po/kube-scheduler-k8s-master               1/1       Running   0          4h        10.132.41.234   k8s-master
> > po/kubernetes-dashboard-2209332821-038fw   1/1       Running   0          3h        172.16.1.2      k8s-node1
> > po/monitoring-grafana-1850655027-vwzcw     1/1       Running   0          3h        172.16.2.5      k8s-node2
> > po/monitoring-influxdb-1870447071-vx3md    1/1       Running   0          3h        172.16.1.3      k8s-node1
> 
```

> when i use following command ,no output
`
[root@k8s-master ~]# kubectl exec monitoring-influxdb-1870447071-vx3md --namespace kube-system --  ping monitoring-influxdb.kube-system.svc.cluster.local
`
```
[root@k8s-master ~]# cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CGROUP_ARGS=--cgroup-driver=systemd"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_EXTRA_ARGS --v=6

```

```
[root@k8s-master ~]\# cat kube-flannel-ds.yml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true
      }
    }
  net-conf.json: |
    {
      "Network": "172.16.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-system
  labels:
    tier: node
    app: flannel
spec:
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: flannel
      containers:
      - name: kube-flannel
        image: quay.io/coreos/flannel:v0.8.0-amd64
        command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr" ]
        securityContext:
          privileged: true
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: run
          mountPath: /run
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      - name: install-cni
        image: quay.io/coreos/flannel:v0.8.0-amd64
        command: [ "/bin/sh", "-c", "set -e -x; cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-flannel.conf; while true; do sleep 3600; done" ]
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: flannel-cfg
          configMap:
            name: kube-flannel-cfg

```

and my ifconfig output

master :
```
cni0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.16.0.1  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 0a:58:ac:10:00:01  txqueuelen 1000  (Ethernet)
        RX packets 45976  bytes 10392042 (9.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 47468  bytes 10569531 (10.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.0.1  netmask 255.255.240.0  broadcast 0.0.0.0
        ether 02:42:e4:2b:7c:b9  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.132.41.234  netmask 255.255.240.0  broadcast 10.132.47.255
        ether 00:16:3e:02:46:27  txqueuelen 1000  (Ethernet)
        RX packets 4913195  bytes 491965104 (469.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5217083  bytes 4942467754 (4.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 121.199.31.235  netmask 255.255.252.0  broadcast 121.199.31.255
        ether 00:16:3e:02:40:c1  txqueuelen 1000  (Ethernet)
        RX packets 657621  bytes 152541447 (145.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 285900  bytes 655389400 (625.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.16.0.0  netmask 255.255.255.255  broadcast 0.0.0.0
        ether da:0a:e6:fc:d2:05  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11  bytes 708 (708.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 54995952  bytes 16862088063 (15.7 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 54995952  bytes 16862088063 (15.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethfe49f061: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        ether da:93:34:77:f0:62  txqueuelen 0  (Ethernet)
        RX packets 45976  bytes 11035706 (10.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 47468  bytes 10569531 (10.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

node1
```
cni0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.16.1.1  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 0a:58:ac:10:01:01  txqueuelen 1000  (Ethernet)
        RX packets 13138  bytes 3121040 (2.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8761  bytes 919600 (898.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.0.1  netmask 255.255.240.0  broadcast 0.0.0.0
        ether 02:42:65:e5:b8:28  txqueuelen 0  (Ethernet)
        RX packets 8  bytes 536 (536.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.165.97.219  netmask 255.255.248.0  broadcast 10.165.103.255
        ether 00:16:3e:00:4f:9b  txqueuelen 1000  (Ethernet)
        RX packets 3823489  bytes 2550852585 (2.3 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2720245  bytes 253995691 (242.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 120.26.55.113  netmask 255.255.252.0  broadcast 120.26.55.255
        ether 00:16:3e:00:79:42  txqueuelen 1000  (Ethernet)
        RX packets 544207  bytes 162588507 (155.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 334262  bytes 509328415 (485.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.16.1.0  netmask 255.255.255.255  broadcast 0.0.0.0
        ether da:70:39:4f:32:9a  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 54  bytes 3450 (3.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 11  bytes 588 (588.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 11  bytes 588 (588.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth08c06463: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        ether 16:c7:5b:ab:45:63  txqueuelen 0  (Ethernet)
        RX packets 4819  bytes 466336 (455.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 97  bytes 4074 (3.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth7c94115f: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        ether ca:04:26:7e:44:5e  txqueuelen 0  (Ethernet)
        RX packets 8319  bytes 2838636 (2.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8674  bytes 916258 (894.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```
node 2

```
cni0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.16.2.1  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 0a:58:ac:10:02:01  txqueuelen 1000  (Ethernet)
        RX packets 11316  bytes 6085621 (5.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2731  bytes 284327 (277.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.0.1  netmask 255.255.240.0  broadcast 0.0.0.0
        ether 02:42:70:1f:0f:d4  txqueuelen 0  (Ethernet)
        RX packets 23938  bytes 1309705 (1.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 26407  bytes 67583194 (64.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.161.233.80  netmask 255.255.240.0  broadcast 10.161.239.255
        ether 00:16:3e:02:45:5f  txqueuelen 1000  (Ethernet)
        RX packets 3807178  bytes 2607319846 (2.4 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2647377  bytes 250536187 (238.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 114.215.201.87  netmask 255.255.252.0  broadcast 114.215.203.255
        ether 00:16:3e:02:18:af  txqueuelen 1000  (Ethernet)
        RX packets 773128  bytes 505574215 (482.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 628468  bytes 543293128 (518.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.16.2.0  netmask 255.255.255.255  broadcast 0.0.0.0
        ether e6:ef:f3:a5:c3:1b  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10157  bytes 781648 (763.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 1614  bytes 80700 (78.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1614  bytes 80700 (78.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethd43ad814: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        ether 76:49:89:1c:79:5f  txqueuelen 0  (Ethernet)
        RX packets 2882  bytes 2151748 (2.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 879  bytes 81480 (79.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vethdd6d8d6e: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        ether 42:cb:f9:df:18:46  txqueuelen 0  (Ethernet)
        RX packets 4673  bytes 439030 (428.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 262  bytes 11232 (10.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```
what's problem ? i set wrong DNS?

/sig dns
