### ISSUE TITLE
Portworx volume provisioner does not support many volume parameters

### ISSUE THREAD

**Issue by harsh-px** [kubernetes/kubernetes#49525]
**BUG REPORT**:
/kind bug

**What happened**:
When creating Portworx volumes using their command line utility `pxctl`, many parameters like `io_priority`, `io_profile`, `scale` etc can be given. There are documented in detail [here](https://docs.portworx.com/control/volume.html#pxctl-volume-create).

The current Portworx volume driver handles only a subset of these paramters specified through the StorageClass. For certain parameters like `io_priority`, a bug in the driver in k8s source causes the value specified by end-user to be dropped and always create a low priority volume.

**What you expected to happen**:
All volume parameters that are supported by the [pxctl cli](https://docs.portworx.com/control/volume.html#pxctl-volume-create) should be supported and parsed correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Create a PersistentVolumeClaim with following storage class.
```
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-test-sc
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   io_priority: "high"
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-test-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: px-test-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
```
Now use `/opt/pwx/bin/pxctl volume list` on any node in the Portworx cluster and observe that the volume has a io priority of low. This should have been high.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6 and above
- Cloud provider or hardware configuration**: Any
- OS (e.g. from /etc/os-release): Any
- Kernel (e.g. `uname -a`): Any
- Install tools: Any
