### ISSUE TITLE
the pods of node Capacity and Allocatable is 110, but have some pod on the node

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/kubernetes#49606]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
kubectl describe node1 
**What you expected to happen**:
```
Capacity:
 cpu:		2
 memory:	3882324Ki
 pods:		110
Allocatable:
 cpu:		2
 memory:	3779924Ki
 pods:		110
```
but it already some pod running in the node1

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.6.3
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):centos7.2
- Kernel (e.g. `uname -a`):3.10.0-514.21.1.el7.x86_64
- Install tools:kubeadm
- Others:
