### ISSUE TITLE
preStop hook gets killed during execution with "did not complete in 0 seconds" UnfinishedPreStopHook events

### ISSUE THREAD

**Issue by ligc** [kubernetes/kubernetes#49626]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
Defined the preStop hook for a replicaset/deployment, when I delete the replicaset/deployment, the prestop hook gets killed during the execution and could not be finished properly. We are running a relatively old version Kubernetes 1.5.6, but we could not update the Kubernetes version for our production environment.

**What you expected to happen**:

preStop hook should be finished correctly

**How to reproduce it (as minimally and precisely as possible)**:

yaml file
```
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: housekeeping
  labels:
    app: housekeeping
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: housekeeping
    spec:
      containers:
      - name: housekeeping
        image: nginx:1.8.1
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo `date` postStart handler >> /tmp/tmp/postStart"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "for i in `seq 1 15`; do echo $i `date` preStop handler  >> /tmp/tmp/preStop; sleep 1; done"]
        ports:
        - containerPort: 80
          hostPort: 7080
        volumeMounts:
        - mountPath: /tmp/tmp
          name: test-volume
      volumes:
      - name: test-volume
        hostPath:
         # directory location on host
         path: /tmp/tmp
```

2. kubectl create -f test.yaml
3. kubectl get pods -o wide to determine which nodes the POD is scheduled to
4. kubectl delete rs housekeeping
5. Login the node that the POD was scheduled to, check the /tmp/tmp/preStop, you will see something like:
```
1 Wed Jul 26 10:42:34 UTC 2017 preStop handler
1 Wed Jul 26 10:42:34 UTC 2017 preStop handler
2 Wed Jul 26 10:42:35 UTC 2017 preStop handler
2 Wed Jul 26 10:42:35 UTC 2017 preStop handler
```
We cold see that the prestop script seems to be called in two parallel processes, and was killed in 2 - 3 seconds.

In the Kubernetes events, will get some UnfinishedPreStopHook warning message:

```
preStop hook for container "c515df39bd7bf7155669ca1615d5a823b8344c90ba5fd543052d1546bfca1613" housekeeping default/housekeeping-pj6rj did not complete in **0** seconds
```

The point is "did not complete in 0 seconds".

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Kubernetes 1.5.6
- Cloud provider or hardware configuration**: on-prem VMs
- OS (e.g. from /etc/os-release): SLES 12
- Kernel (e.g. `uname -a`): 3.12.28-4-default
- Install tools: binary + systemd configuration files
- Others:
