### ISSUE TITLE
kubectl set image deployment is ignoring --selector

### ISSUE THREAD

**Issue by Firehed** [kubernetes/kubernetes#49695]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
I have two deployments with different names running the same image and sharing a label (they differ in replica count and some environment variables). I am trying to update both deployments with kubectl using the `--selector` flag instead of naming the deployment explicitly, and instead of getting the desired behavior I'm observing that only one deployment would be affected (the first one alphabetically, but that may be a coincidence)

```
$ kubectl set image \
	deployments \
	--namespace=some-namespace \
	--dry-run \
	--selector app=worker \
	worker=my/image:newtag

NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
add-stories-worker   1         1         1            1           3d
```

I've also tried `--all` instead of the `--selector` line, which also does not work. Substituting either worker name on that line has the expected result, but of course does not impact all of the deployments.

**What you expected to happen**:
All of the deployments matching the label are affected by the command:
```
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
add-stories-worker   1         1         1            1           3d
pull-worker          3         3         3            3           3d
```
**How to reproduce it (as minimally and precisely as possible)**:
Create two deployments that are nearly identical:
```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: add-stories-worker
spec:
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: nginx:1.13.2-alpine
          name: worker
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pull-worker
spec:
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: nginx:1.13.2-alpine
          name: worker
```
then run the command noted above (remove the namespace line, or modify the above yaml to put the deployments in one), substituting a different image (e.g. `worker=nginx:1.13.3-alpine`) 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.1-gke.0", GitCommit:"841411e511bfb1ccd78e76bf8633d4515061e18b", GitTreeState:"clean", BuildDate:"2017-07-14T17:52:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: GKE
