### ISSUE TITLE
enabled ResourceQuota, but didn't return the rejection message

### ISSUE THREAD

**Issue by jianzhangbjz** [kubernetes/kubernetes#49691]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
I enabled the `ResourceQuota` by special `--admission-control=LimitRanger,ResourceQuota` in `api-server`, and created a namespace(`jian`), as the below:
```
root@slave2:/home/zhangjian/testK8s# kubectl get ns
NAME          STATUS    AGE
default       Active    49m
jian          Active    43m
kube-public   Active    49m
kube-system   Active    49m
```
Created a quota yaml.
```yaml
Name:		jian
Labels:		<none>
Annotations:	<none>
Status:		Active

Resource Quotas
 Name:			compute-resources
 Resource		Used	Hard
 --------		---	---
 limits.cpu		0	1
 limits.memory		0	1Gi
 pods			0	4
 requests.cpu		0	500m
 requests.memory	0	512Mi

No resource limits.
```
Setting resource quota by `kubectl create -f quota.yaml --namespace=jian`, description as the below:
```
root@slave2:/home/zhangjian/testK8s# kubectl describe ns jian
Name:		jian
Labels:		<none>
Annotations:	<none>
Status:		Active

Resource Quotas
 Name:			compute-resources
 Resource		Used	Hard
 --------		---	---
 limits.cpu		0	1
 limits.memory		0	1Gi
 pods			0	4
 requests.cpu		0	500m
 requests.memory	0	512Mi

No resource limits.
``` 
But, when created a pod which 2 cpu(exceed the resource quota in that namespace), I didn't get any the rejection message. 
```
root@slave2:/home/zhangjian/testK8s# kubectl create -f ns_jian.yaml 
replicationcontroller "withgpu" created
root@slave2:/home/zhangjian/testK8s# kubectl get pods --all-namespaces
No resources found.
root@slave2:/home/zhangjian/testK8s# kubectl describe ns jian
Name:		jian
Labels:		<none>
Annotations:	<none>
Status:		Active

Resource Quotas
 Name:			compute-resources
 Resource		Used	Hard
 --------		---	---
 limits.cpu		0	1
 limits.memory		0	1Gi
 pods			0	4
 requests.cpu		0	500m
 requests.memory	0	512Mi

No resource limits.
```
And, re-created it, got the following errors, I couldn't find this Pod in any where.
```
root@slave2:/home/zhangjian/testK8s# kubectl create -f ns_jian.yaml 
Error from server (AlreadyExists): error when creating "ns_jian.yaml": replicationcontrollers "withgpu" already exists
```
My pod request like this:
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: withgpu
  namespace: jian
spec:
  replicas: 1
  selector:
    app: withgpu
  template:
    metadata:
      name: withgpu
      labels:
        app: withgpu
    spec:
      containers:
      - name: withgpu1
        image: nvidia/cuda:jian
        command: ["/bin/sh", "-c"]
        args: ["tail -f /dev/null"]
        #args: ["sleep 20"]
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 0
            cpu: 2
            memory: 512Mi
        ports:
        - containerPort: 80
```
**What you expected to happen**:
I hope get the rejection info(or errors) when my pod request exceed the Resource Quota.

**How to reproduce it (as minimally and precisely as possible)**:
The steps on the above.

**Anything else we need to know?**:
Node info:
```
Capacity:
 alpha.kubernetes.io/nvidia-gpu:	1
 cpu:					2
 memory:				3883540Ki
 pods:					110
```
**Environment**:
- Kubernetes version (use `kubectl version`): release-1.7
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):Ubuntu 14.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
