### ISSUE TITLE
Initializers can't be cleared with a PATCH request

### ISSUE THREAD

**Issue by jkinkead** [kubernetes/kubernetes#49814]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I configured an [initializer](https://kubernetes.io/docs/admin/extensible-admission-controllers/#initializers) to apply to all new pods & all new jobs.

New pods and jobs end up marked with the initializer. I can retrieve the uninitialized items using the `includeUninitialized` parameter.

My initializer is the only initializer in the system. In order to conform to [the API](https://kubernetes.io/docs/api-reference/v1.7/#initializers-v1-meta), I must set the `initializers` field to nil before updating the object in the system. The API server correctly enforces this rule.

When I use a `PATCH` request to update the object in-place with the nil `initializers` field, the object retains my other changes, but comes back with `initializers.pending` set to the initializer I just cleared.

When I use a `PUT` request to update the object by replacing it with a new instance with a nil `initializers` list, the object retains all changes, and is considered initialized.

**What you expected to happen**:

`PATCH` and `PUT` both allow for initializers to be cleared.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a initializer that applies to jobs:

  ```yaml
  apiVersion: admissionregistration.k8s.io/v1alpha1
  kind: InitializerConfiguration
  metadata:
    name: repro-patch-bug
  initializers:
    - name: repro.patch.bug
      rules:
        - apiGroups:
            - "*"
          apiVersions:
            - "*"
          resources:
            - jobs
  ```
2. Create any job. It will be uninitialized.
3. Fetch the job using `includeUninitialized=true`.
4. Update the job by setting `metadata.initializers` to nil.
5. Issue a `PATCH` request to update this job.

Follow steps 1-4 above, but issue a `PUT` request at the end instead.

Observe the differences in the resulting `metadata.initializers` object.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T22:55:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
AWS / kops
