### ISSUE TITLE
Pod failure due to lack of system resources is directly visible in CLI.

### ISSUE THREAD

**Issue by gposcidonio** [kubernetes/kubernetes#49896]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug Report

/kind bug

**What happened**: When a Pod fails to initialize due to lack of system resources, none of the Conditions say anything about the reason the Pod failed to initialize. Instead, an Event is emitted with a plain english description of the error. For manual `kubectl` execution, this description is fine. But for interaction programmatically, via something like `client-go`, this seems fragile.

**What you expected to happen**: As per the description on the [kubernetes/autoscaler FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md):

> A pod is unschedulable when the Kubernetes scheduler is unable to find a node that can accommodate the pod. For example, a pod can request more CPU [than] is available on any of the cluster nodes. Unschedulable pods are recognized by their PodCondition. Whenever a kubernetes scheduler fails to find a place to run a pod it sets "schedulable" PodCondition to false and reason to "unschedulable".

Basically, I was hoping for any kind of definitive error code or something in the Pod's Conditions that told me why the Pod failed to start. This is important to me as I'm trying to define some custom scaling logic for when there aren't enough system resources.

**How to reproduce it (as minimally and precisely as possible)**:  In a relatively low-power Kubernetes cluster (I used the default settings in GKE), create a deployment as follows:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: mult
spec:
    replicas: 100
    template:
        metadata:
            labels:
                app: mult
        spec:
            containers:
                - name: mult
                  image: gposcidonio/mult
```

Feel free to use any image with high CPU usage (the one I listed there is an image I built that just multiplies two random numbers together over and over again). Upon doing so, you will see that some of the created Pods enter a `Running` state, but most of them remain in `Pending`.

Issue a `kubectl describe pod` on one of the `Pending` Pods and you will see that the Pod's Conditions simply state:
```
Conditions:
  Type          Status
  PodScheduled  False
```

At the bottom, you will see an event that says something like:

```
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                    -------------   --------        ------                  -------
  24m           0s              89      default-scheduler                       Warning         FailedScheduling        No nodes are available that match all of the following predicates:: Insufficient cpu (3).
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**: Google Container Engine
- OS (e.g. from /etc/os-release): Google Container-optimized OS

**Comment by wanghaoran1988** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by timothysc** [comment]
@gposcidonio Could you show the full ```kubectl describe pod``` output and what you would like to see?

**Comment by gposcidonio** [comment]
@timothysc Sure thing. I can't seem to replicate the `OutOfCpu` status that i mentioned above, which is disconcerting to say the least. In any case, here is the output of `kubectl describe` for one of the `Pending` Pods:

```
Name:		mult-3431549876-zxjb2
Namespace:	default
Node:		/
Labels:		app=mult
		pod-template-hash=3431549876
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"mult-3431549876","uid":"bd86c086-77cb-11e7-8fde-42010a8000fb","a...
		kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container mult
Status:		Pending
IP:		
Controllers:	ReplicaSet/mult-3431549876
Containers:
  mult:
    Image:	gposcidonio/mult
    Port:	
    Requests:
      cpu:		100m
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6pwqw (ro)
Conditions:
  Type		Status
  PodScheduled 	False 
Volumes:
  default-token-6pwqw:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-6pwqw
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  51s		19s		7	default-scheduler			Warning		FailedScheduling	No nodes are available that match all of the following predicates:: Insufficient cpu (3).
```

Under `Conditions` I would love to have a reason there when the system is out of resources that tells me so. For example:

```
Conditions:
  Type		Status
  PodScheduled 	False
  Reason        OutOfCPU
```

Also the `Reason` field already exists, but I haven't been able to find any documentation as to the possible values it could hold. Is this field intentionally left vague? If so, how can I guarantee that if something like this were implemented that I could reliably check the `Reason` field for the phrase `OutOfCPU`?

**Comment by timothysc** [comment]
So if you do a ```kubectl get pod PodName -n YourNamespace -o yaml``` there should be a PodStatus.Message filed that should contain the reason.  

There is also a PodCondition.Message that may contain more detail. 

I think the CLI on describe could use some love here to output those messages.  

If you're looking for an enumerated list of errors, there currently isn't any, but we've talked about standardizing it and flushing that out.

**Comment by gposcidonio** [comment]
So I did what you suggested (and included the full output of `kubectl get pod PodName -o yaml` at the end of this comment) and received the following relevant output:

```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-08-04T15:38:10Z
    message: 'No nodes are available that match all of the following predicates::
      Insufficient cpu (3).'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
```

So this actually looks pretty close to what I want. The only thing that worries me is if the reason `Unschedulable` could be used for something which, for example, adding a new node to my cluster could not solve. In a perfect world, I wouldn't have to parse the `message` above for the phrase "insufficient cpu" or something similar.

All that being said, I'm going to bank on the `Unschedulable` reason being what I need, for now.

Also, here's the full output I mentioned above, for reference:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"mult-3431549876","uid":"eb4eeacf-792a-11e7-8fde-42010a8000fb","apiVersion":"extensions","resourceVersion":"206330"}}
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      mult'
  creationTimestamp: 2017-08-04T15:38:10Z
  generateName: mult-3431549876-
  labels:
    app: mult
    pod-template-hash: "3431549876"
  name: mult-3431549876-zn9zb
  namespace: default
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mult-3431549876
    uid: eb4eeacf-792a-11e7-8fde-42010a8000fb
  resourceVersion: "206436"
  selfLink: /api/v1/namespaces/default/pods/mult-3431549876-zn9zb
  uid: ebb7346d-792a-11e7-8fde-42010a8000fb
spec:
  containers:
  - image: gposcidonio/mult
    imagePullPolicy: Always
    name: mult
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-6pwqw
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.alpha.kubernetes.io/notReady
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.alpha.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-6pwqw
    secret:
      defaultMode: 420
      secretName: default-token-6pwqw
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-08-04T15:38:10Z
    message: 'No nodes are available that match all of the following predicates::
      Insufficient cpu (3).'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
```

**Comment by timothysc** [comment]
I'm reopening to address the CLI - look & feel.

**Comment by k82cn** [comment]
@jinzhejz , please try this one :). ping me offline if any question.

**Comment by davidopp** [comment]
@bsalamat who is also interested in scheduler user experience

**Comment by bsalamat** [comment]
Thanks, @gposcidonio for reporting detailed information about this issue. What you described makes a lot of sense and it will be very useful to expose a reliable error code which is not going to change arbitrarily in future versions. We should address this.

**Comment by dims** [comment]
@bsalamat @timothysc @davidopp @k82cn Can we please drop 1.8 milestone?

**Comment by bsalamat** [comment]
We have made a couple of improvements to the `unschedulable` message of pods that should make it much more readable. The changes are available in Kubernetes 1.10 (and partly in 1.9).

**Comment by gajus** [comment]
I am on v1.12 and I do not understand the message:

```yaml
status:
  conditions:
  - lastProbeTime: "2019-06-15T10:53:58Z"
    lastTransitionTime: "2019-06-15T10:44:23Z"
    message: '0/10 nodes are available: 10 node(s) didn''t match node selector, 4
      Insufficient cpu.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable

```

Here is the affinity definition:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: applaudience.com/role
            operator: In
            values:
              - secondary-infrastructure

```

Resource requirements:

```yaml
resources:
  requests:
    memory: '100Mi'
    cpu: '100m'
  limits:
    memory: '250Mi'
    cpu: '250m'

```

Here is the node pool definition:

<img width="473" alt="Screenshot 2019-06-15 at 11 56 40" src="https://user-images.githubusercontent.com/973543/59550654-24009e80-8f65-11e9-88b6-27ca6e97ec91.png">

What is the reason it cannot be scheduled?
