### ISSUE TITLE
[Feature Request]: Support time period based hpa

### ISSUE THREAD

**Issue by zjzhangkui** [kubernetes/kubernetes#49931]
Is this a BUG REPORT or FEATURE REQUEST?: FEATURE REQUEST

/kind feature

Request:
For some kind bussiness, the service is heavy during a certain time period, like 9:00am-10:00am in every workday, much more http requests than other time, if hpa support to upscale pods to a absolute value set by user during this period and downscale after period, it will be very useful for this scenario.

**Comment by huangjiasingle** [comment]
@zjzhangkui  l agree with you,  in my project, l write some code to support the same function.  like the crontab's functions

**Comment by zjzhangkui** [comment]
@huangjiasingle If there are multiple rules for autoscale, like cpu and qps at same, we can not separate them each to caculate the desired replicas right? There should be a controller considering all of the rules to caculate one result desired replicas. I'm trying to write my own controller with tpr since current autoscale version is alpha.

**Comment by huangjiasingle** [comment]
@zjzhangkui  yes , when the multiple rule , my project not support.  it's a good idea.

**Comment by gyliu513** [comment]
The Kubernetes only support auto scaling based on CPU and some other [customized metrics](https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/run-application/horizontal-pod-autoscale.md#support-for-custom-metrics) now, the problem is that in a production environment, most customers do not want to use metrics based autoscaling as it is not safe: Sometimes the high CPU/Memory utilization may not caused by real workload but may be a bug in the application sometime, for this case, the application scale up may use up all of the resources in the clusters.

Most customers prefer auto scaling based on time windows, as they actually know when their applications will have a high workload. Such as for some mobile applications, the customers know that they will need more resources by the end of each month as they need to do some billing checkpoint etc; For some e-Commerce applications, the customers know that they need more resources when they are promoting some products on Black Friday etc.

So what they want is Time-Based Auto Scaling for Applications.

There are two solutions for this:

Solution 1) Leverage `CronJob` in Kubernetes, we may need to build a image which include `kubectl` binary, and use `kubectl` to scale the application. The following is an example, it means the application of nginx will be scaled to 3 replicas every day at 8am. This is simple and straightforward. The problem is that each application need a cronjob and the Kubernetes may have many jobs if we want to scale many applications.

```
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: scale-up
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scale
            image: siji/kubectl:v1.5.2
            command:
            - kubectl.sh
            - kubectl
            - scale
            - --replicas=3
            - deployment/nginx
          restartPolicy: OnFailure
```

Solution 2) Similar as [Calico policy controller for Kubernetes](https://github.com/projectcalico/k8s-policy), develop a new controller for time based auto scaling. This is a clean solution but need more effort.

/sig apps

**Comment by gyliu513** [comment]
@kubernetes/sig-autoscaling-feature-requests

**Comment by gyliu513** [comment]
From @DirectXMan12 

> Option 3: Neither of the above.
> Add an implementation of the custom metrics API for that provides the a fake "time-based" metric, and use the existing HPA.

**Comment by gyliu513** [comment]
Thanks @DirectXMan12 , let us trace the time based auto scaling here:

Do you mean as following:

The customer metrics API only get current time and treat time as metrics
Use existing HPA policy taking time as monitor metrics
Suppose the threshold is 8:00AM and 8:00PM, If time exceeds 8:00 AM, scale up; if time exceeds 8:00PM, scale down?

**Comment by zjzhangkui** [comment]
@gyliu513 Thanks for you proposal solution.
I had once considering treating time as metrics, but when I had checked the source code in kubernetes1.6,   the cusom metric value should be number value type to caculate usageRatio , time is not supported. Besides, the target replica count is caculated based on current replicas,  as the current replicas is not fixed value, may be have other scale metric like tps at same.  So it's hard to provide a custom metric value to calculate a fixed value of replicas. 
Attached custom metric calculating source code as below:

	utilization, timestamp, err = c.metricsClient.GetObjectMetric(metricName, namespace, objectRef)
	if err != nil {
		return 0, 0, time.Time{}, fmt.Errorf("unable to get metric %s: %v on %s %s/%s", metricName, objectRef.Kind, namespace, objectRef.Name, err)
	}
	usageRatio := float64(utilization) / float64(targetUtilization)
	if math.Abs(1.0-usageRatio) <= tolerance {
		// return the current replicas if the change would be too small
		return currentReplicas, utilization, timestamp, nil
	}
	return int32(math.Ceil(usageRatio * float64(currentReplicas))), utilization, timestamp, nil

**Comment by gyliu513** [comment]
Thanks @zjzhangkui , I also have the same finding with you, @DirectXMan12 , what do you think for this?

**Comment by bes** [comment]
This feature would be really useful.

**Comment by ericuldall** [comment]
For anyone still looking for this functionality I have a working version built using CRD. It allows you to modify the min/max pods of your HPA at different times. Currently it's only tested in GKE, but I'm happy to take any PR's if the community is interested in expanding its capabilities.

Check it out here: https://github.com/k8s-restdev/scheduled-scaler

**Comment by DirectXMan12** [comment]
Neat!  Thanks.  I may offer some suggestions in comments, but I love that CRDs have enabled projects like that.

**Comment by ericuldall** [comment]
@DirectXMan12 Are you referring to:
```
scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: php-apache
```
?

**Comment by DirectXMan12** [comment]
yeah, so you'd end up with something like

```
target:
  kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v1
  name: foobar
```

or

```
target:
  kind: InstanceGroup
  apiVersion: autoscaling.k8s-restdev.io/v1
  name: foobar
```

It's mostly cosmetic ;-)
