### ISSUE TITLE
Plumb the proxy dialer to the webhook admission plugin

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#49987]
Currently webhoook admission plugin doesn't have a dialer: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/webhook/admission.go#L260

Probably we need to plumb the dialer to the client like aggregator does: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go#L213. Otherwise the plugin won't be able to work in gke.

cc @mandarjog @cheftako

**Comment by mandarjog** [comment]
On GKE 1.7.2
```
W0801 14:00:18.957110       4 admission.go:174] Failed calling webhook pod-image.k8s.io: failed calling admission webhook "pod-image.k8s.io": Post https://10.40.0.5:8000/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
E0801 14:00:18.957140       4 admission.go:175] failed calling admission webhook "pod-image.k8s.io": Post https://10.40.0.5:8000/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
API server attempts to open direct connections to endpoints.

**Comment by caesarxuchao** [comment]
I'll look into the issue this week.

**Comment by mandarjog** [comment]
There is a workaround.
1. Deploy webhook as a `LoadBalancer` type service and get an external IP.
2. Deploy webhookExternal like so
```
apiVersion: v1
kind: Service
metadata:
  name: webhookExternal
spec:
  externalIPs:
  - 35.193.46.50
  ports:
    - port: 443
      protocol: TCP
```

Create and endpoint object named `webhookExternal`
```
apiVersion: v1
kind: Endpoints
metadata:
  name: webhookExternal
  namespace: default
subsets:
- addresses:
  - ip: 35.193.46.50
  ports:
  - port: 443
    protocol: TCP
```

Then use `webhookExternal` in the validator definition.
