### ISSUE TITLE
Define host based on svc, namespace, and domain in ingress

### ISSUE THREAD

**Issue by sean-krail** [kubernetes/kubernetes#50003]
/kind feature

**Feature**:
Ability to reference an ingress' `metadata.namespace` in its `spec.rules[].host` property.

**Use case**:
Original request I found was posted at kubernetes/ingress#713

I have a dev k8s cluster with many namespaces for different feature branches and workspaces all running the same services and exposing more than one of them. I'd like to expose services in each namespace with their own ingress and have the host auto-generated like:
```YAML
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
spec:
  rules:
  - host: a-svc.<namespace>.devk8s.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: a-svc
          servicePort: 8080
  - host: b-svc.<namespace>.devk8s.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: b-svc
          servicePort: 8080
```
Where `<namespace>` would be replaced with `dev` if that was the namespace that the ingress was created in. The namespace is not hard-coded so that the ingress file can be applied to any namespace.
