### ISSUE TITLE
K8s Service fails to create GCE internal load balancer

### ISSUE THREAD

**Issue by Markbnj** [kubernetes/kubernetes#50034]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

@kubernetes/sig-network-bugs

**What happened**:

Created a service of type "LoadBalancer" with the following manifest: 

```
kind: Service                                                                                                                                                                                                 
apiVersion: v1                                                                                                                                                                                                
metadata:                                                                                                                                                                                                     
  name: linkerd                                                                                                                                                                                       
  annotations:                                                                                                                                                                                                
    cloud.google.com/load-balancer-type: "internal"                                                                                                                                                           
spec:                                                                                                                                                                                                         
  selector:                                                                                                                                                                                                   
    deployment: linkerd                                                                                                                                                                               
  type: LoadBalancer                                                                                                                                                                                          
  ports:                                                                                                                                                                                                      
  - name: admin-http                                                                                                                                                                                          
    protocol: TCP                                                                                                                                                                                             
    port: 9990
  - name: thrift
    protocol: TCP
    port: 7033
```

**What you expected to happen**:

Expected the internal load balancer to be provisioned with an internal IP.

**How to reproduce it (as minimally and precisely as possible)**:

Create the service above then:
```
$ kubectl describe svc linkerd
Name:                   linkerd
Namespace:              default
Annotations:            cloud.google.com/load-balancer-type=internal
Selector:               deployment=linkerd
Type:                   LoadBalancer
IP:                     10.3.xxx.xxx
Port:                   admin-http      9990/TCP
NodePort:               admin-http      31154/TCP
Endpoints:
Port:                   thrift     7033/TCP
NodePort:               thrift     31210/TCP
Endpoints:
Session Affinity:       None
Events:
  FirstSeen     LastSeen        Count   From                    SubObjectPath   Type            Reason                          Message
  ---------     --------        -----   ----                    -------------   --------        ------                          -------
  32m           2m              12      service-controller                      Normal          CreatingLoadBalancer            Creating load balancer
  32m           1m              12      service-controller                      Warning         CreatingLoadBalancerFailed      Error creating load balancer (will retry): Failed to create load balancer for service default/linkerd: googleapi: Error 400: Invalid value for field 'resource.subnetwork': ''. Network interface must specify a subnet if the network resource is in custom subnet mode., invalid
```

**Anything else we need to know?**:

This appears to be similar/related to https://github.com/kubernetes/kubernetes/issues/49577

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.1-gke.0", GitCommit:"841411e511bfb1ccd78e76bf8633d4515061e18b", GitTreeState:"clean", BuildDate:"2017-07-14T17:52:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}```
- Cloud provider or hardware configuration**:
GCE/GKE
- OS (e.g. from /etc/os-release):
COS
- Kernel (e.g. `uname -a`):
- Install tools:
Helm 2.5.0
- Others:
