### ISSUE TITLE
No documentation about kube-proxy ConfigFile

### ISSUE THREAD

**Issue by hanikesn** [kubernetes/kubernetes#50041]
/kind bug

kube-proxy in Kubernetes 1.7 outputs the following warning:
```
WARNING: all flags other than --config, --write-config-to, and --cleanup-iptables are deprecated. Please begin using a config file ASAP.
```

But there is zero documentation about this config file to be found. Digging into the code I found KubeProxyConfiguration:
https://github.com/kubernetes/kubernetes/pull/34727/files#diff-ed3df710e9af7cd30a185896a60897d9R694
and subsequently:
https://stackoverflow.com/questions/45438254/need-a-example-about-kube-proxy-config-file

I think this is related to the fact that on https://kubernetes.io/docs/home/ there's no documentation about ComponentConfigs.

**Comment by ncdc** [comment]
This is a bit tricky... the docs for components like kube-proxy are autogenerated. I have a local branch that modifies the generated doc to include documentation for the config file, as well as a sample config file with all the defaults filled in. I will try to submit a PR for this tomorrow.

**Comment by ncdc** [comment]
I can do something that looks like this: https://gist.github.com/ncdc/b53d5540fba4fb309b8c4c9b26fad487. WDYT?

https://github.com/kubernetes/kubernetes/compare/master...ncdc:kube-proxy-config-docs

cc @timothysc @bradamant3 @abiogenesis-now @liggitt @deads2k @sttts

**Comment by abiogenesis-now** [comment]
@ncdc Some nits/questions:

1. The transition from "Usage" to a previously unmentioned "default config file" is sort of abrupt. I know it can be inferred, but it might be smoother from the reader's perspective to see something like:

    > "kube-proxy network defaults are set in a config file (path specified via flag, scroll down for details). The default config file contains these values: ..."

2. It's a bit unclear to me: is the config file provided just a hardcoded sample? Or is it somehow populating the help response with the actual config file that `--config` currently points to?

3. Is the list of configuration fields pulled from somewhere or is actually a text block? Either way, for readability, it would be nice to format it into two columns (Name and Description), separated by spaces. (similar to how flags are formatted)

**Comment by ncdc** [comment]
@abiogenesis-now yeah, this so far has just been a prototype to see if I could get this information automatically generated from the code. We will certainly clean up the prose and transitions.

The config file is the current set of default values for each field.

The list of configuration fields is pulled from the `.go` file where they are defined. I'm tempted to try to display the sample config file with `#` comments interleaved, like this (just showing the first few lines):

```yaml
The default config file contains these values:

apiVersion: componentconfig/v1alpha1
# bindAddress is the IP address for the proxy server to serve on (set to 0.0.0.0 for all interfaces)
bindAddress: 0.0.0.0
clientConnection:
  # acceptContentTypes defines the Accept header sent by clients when connecting to a server, overriding the default value of 'application/json'. This field will control all connections to the server used by a particular client.
  acceptContentTypes: ""
```

WDYT?
