### ISSUE TITLE
PSP: provide a simple way to allow all Linux capabilities

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#50055]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

Currently when user tries to create a super privileged PSP, it will require cluster admin to list all Linux capabilities in PSP `defaultAddCapabilities` field. It would be boring to get all the Linux capabilities and put them in PSP spec.

**What you expected to happen**:
Just like `volumes` field in PSP. Can we specify `*` to allow all Linux capabilities?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liqlin2015** [comment]
Just like docker https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities. Can we specify `--cap-add=ALL --cap-drop=MKNOD` to allow all capabilities?

**Comment by liqlin2015** [comment]
`One of the (many!) features of Docker 0.6 is the new “privileged” mode for containers. It allows you to run some containers with (almost) all the capabilities of their host machine, regarding kernel features and device access.` Cited from docker doc. I think "privileged" container has all the Linux capabilities of the host. However it's true in Kubernetes.

**Comment by dims** [comment]
@liqlin2015 : is this request different from the add/drop already in pods? 

- https://www.weave.works/blog/container-capabilities-kubernetes/ 
- https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container

**Comment by gyliu513** [comment]
area/security
sig/apps

**Comment by php-coder** [comment]
> Currently when user tries to create a super privileged PSP, it will require cluster admin to list all Linux capabilities in PSP defaultAddCapabilities field. It would be boring to get all the Linux capabilities and put them in PSP spec.

Docker expects that the list of capabilities will be supplied during container creation. Currently, Kubernetes don't do much here and just passes the list that has been specified by a cluster admin in the `defaultAddCapabilities` field. If we change that then Kubernetes will be responsible for expanding `*` to the list of real capabilities. This list is changing over time and depends on the kernel version, for example. This means that Kubernetes would should have some sophisticated logic to decide which capabilities can be used on which node. This also means that PSP could work differently on the cluster with different nodes.

As far I understand, Kubernetes tries to be agnostic and don't do any assumptions/restrictions to low-level stuff like that. That's why this decision was moved to the cluster admin shoulders.

CC @pweil- and @liggitt who know more details and may correct me.

> Just like volumes field in PSP. Can we specify * to allow all Linux capabilities?

"volumes" field is a bit different because it doesn't modify a pod spec (in contrast to `defaultAddCapabilities` that adds capabilities). "volumes" is close to the "allowedCapabilities" by its meaning.

In OpenShift this field have exactly this behavior (see https://github.com/openshift/origin/pull/12875): a cluster admin may specify `*` as a value for the "allowedCapabilities" field. In this case, any capabilities that were requested by a pod will be allowed.

Is it what are you asking? Would it work for you?

> Can we specify --cap-add=ALL --cap-drop=MKNOD to allow all capabilities?

Have you tried it? I haven't but I think that it should work because Kubernetes will pass these values as-is to Docker.

**Comment by pweil-** [comment]
Capabilities in the PSP are dependent on the runtime being used as it's passed as a runtime value and that runtime can allow whatever special values it wants.  In the case of Docker, `ALL` is allowed.  The `ALL` value can be listed in the allowed capabilities or default capabilities and it will be added. 

As @php-coder mentioned, it would also be possible to have a `*` wildcard in the allowed capabilites field that would mean "you're allowed to ask for anything you want, up to and including the `ALL` value".

Are you not able to do that for some reason?  If so, please comment on what issues you're seeing.

**Comment by php-coder** [comment]
@gyliu513 The commands weren't applied because they should start with a slash.

**Comment by liqlin2015** [comment]
yea. The openshift implementation is exactly what I want. 

As for `ALL` capabilities, here is my result.
```
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: false
      containers:
      - name: nginx
        image: nginx:1.13.1
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          capabilities:
            add: ['ALL']
        ports:
        - protocol: TCP
          containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
```
```
piVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  allowedCapabilities:
  - ALL
  defaultAddCapabilities:
  - ALL
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 1
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
```

```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  8s		3s		11	replicaset-controller			Warning		FailedCreate	Error creating: pods "nginx-278314814-" is forbidden: unable to validate against any pod security policy: [capabilities.add: Invalid value: "ALL": capability may not be added]
```

Since privileged container already has **ALL** the capabilities, can we just skip validating capabilities in PSP admission controller plugin if `privileged` is `true`?
