### ISSUE TITLE
Should allow external service with no port definition

### ISSUE THREAD

**Issue by wzhliang** [kubernetes/kubernetes#50079]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
When deploying a service with either `exteralIPs` or `externalName`, API server rejects the request if there is no port definition. This is not ideal. As these affects DNS records only, kubernetes should allow such service without port definition.

**What you expected to happen**:
Creating service where either `externalIPs` or `externalName` are defined should ignore port definition.

**How to reproduce it (as minimally and precisely as possible)**:

Create the following objects:

```
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: ext1
  spec:
    externalIPs:
    - 192.168.88.1
    - 192.168.88.2
    - 192.168.88.3
- apiVersion: v1
  kind: Service
  metadata:
    name: ext2
  spec:
    externalName: foo.com
kind: List
```

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.7.2
- Cloud provider or hardware configuration**: baremetal
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`): Linux dev-1 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux 
- Install tools: kubeadm
- Others:
