### ISSUE TITLE
Failed DaemonSet pods not (re)starting when DS YAML corrected

### ISSUE THREAD

**Issue by dmayo3** [kubernetes/kubernetes#50313]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Some DaemonSet pods were in a failed state (looking for an undefined secretKeyRef).

The pods would not (re)start without manual intervention after correcting the YAML file.

Workaround was to delete the failed pods.

**What you expected to happen**:

Failed pods would be (re)started with the new settings.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Secret
2. Create a DaemonSet YAML config
3. Create an environment variable with `secretKeyRef.name` set to the name of the Secret
4. Set `secretKeyRef.key` to a key that does not exist in the secret
5. Apply the DaemonSet config
6. The pods' statuses should say "Couldn't find key &lt;key&gt; in Secret &lt;secret&gt;"
7. Correct the DaemonSet config and reapply

**Anything else we need to know?**:

N/A

**Environment**:
- Cloud provider or hardware configuration**:
GCP / GKE
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by xiangpengzhao** [comment]
/sig apps
and maybe
/sig cli
also

**Comment by yastij** [comment]
cc @lukaszo

**Comment by lukaszo** [comment]
Can you show your yaml file? Did you enable RollingUpdate https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/ ?

**Comment by dmayo3** [comment]
@lukaszo 

We haven't enabled RollingUpdate, I'll make a note to do that at some point.

Redacted YAML file:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: foobar
spec:
  template:
    metadata:
      labels:
        app: foobar
      name: foobar
    spec:
      containers:
      - image: bazquux
        imagePullPolicy: Always
        name: foobar
        ports:
          - containerPort: 1234
            name: myport
        env:
          - name: SOME_SECRET
            valueFrom:
                secretKeyRef:
                  name: mysecrets
                  key: THIS_KEY_DOES_NOT_EXIST
          - name: KUBERNETES
            value: "yes"
          - name: SD_BACKEND
            value: docker
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
```
