### ISSUE TITLE
ConfigMaps and Secrets mounted with subPath do not update when changed

### ISSUE THREAD

**Issue by thesandlord** [kubernetes/kubernetes#50345]
/kind bug

**What happened**:

I wanted to mount a ConfigMap and a Secret directly as a file and didn't want to mount it as a full directory, so I used subPath to do so:

```yaml
        volumeMounts:
          - name: my-config
            mountPath: /usr/src/app/config/config.json
            subPath: config.json
          - name: my-secret
            mountPath: /usr/src/app/secret/secret.json
            subPath: secret.json
      volumes:
      - name: my-config
        configMap:
          name: my-config
      - name: my-secret
        secret:
          secretName: my-secret
```
When the pod is created, it mounts the ConfigMap and Secret correctly. However, if I change them, the updates are not projected into the currently running pods. New pods get the updated file. According to the [documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically), changes to a ConfigMap should be automatically propagated to running containers that mount them.

However, if I don't use subPath and instead mount the ConfigMap and Secret as a directory:
```yaml
        volumeMounts:
          - name: my-config
            mountPath: /usr/src/app/config
          - name: my-secret
            mountPath: /usr/src/app/secret
      volumes:
      - name: my-config
        configMap:
          name: my-config
      - name: my-secret
        secret:
          secretName: my-secret
```
Then the files are updated inside the container when the underlying ConfigMap and Secret are updated and everything works as expected.

**Anything else we need to know?**:

In both cases, the files are being updated on the host VM. @kelseyhightower and I tried to debug this, and the only conclusion we could come up with is that subPath is using a different method to mount the files (I think it is using symlinks), and these either aren't or can't be updated for whatever reason.

**Action**:
The behavior that files mounted with subPath don't get updated needs to be documented, or it needs to be fixed so that subPath mounts are updated when the underlying ConfigMap or Secret changes.

**Environment**: GKE
- Kubernetes version (use `kubectl version`): 1.6.7
- Cloud provider or hardware configuration**: GKE n1-standard-1
- OS (e.g. from /etc/os-release): Container-Optimized OS 59 9460.64.0
- Kernel (e.g. `uname -a`): 4.4.52+

**Comment by wongma7** [comment]
Yes, symlinks are involved. Atomic writer relies on symlinks to update configmaps, secrets and such: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/atomic_writer.go. On the host, the pod volume directory looks something like this:
```
$ pwd
/var/lib/kubelet/pods/uuid/volumes/kubernetes.io~configmap/my-config
$ tree -a
.
├── ..8988_09_08_14_21_15.788262705
│   └── secret.json
├── ..data -> ..8988_09_08_14_21_15.788262705
└── secret.json -> ..data/secret.json
```
When you subPath the secret file, that secret.json file is bind mounted into the container. But secret.json is actually a symlink to another secret.json in a timestamped folder (..8988_09_08_14_21_15.788262705). When the secret gets updated, the symlinks get changed around but the file bind mounted into the container remains the same.

Not sure what the solution is. Hope this helps somebody else think of one though :)

**Comment by supereagle** [comment]
@thesandlord Maybe your use case is [Add ConfigMap data to a specific path in the Volume](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-specific-path-in-the-volume).

I follow the documentation, and it works as expected.
**My configmap:**
```
apiVersion: v1
data:
  config.json: |
    {
      "special.level": "good",
      "special.type": "charm"
    }
kind: ConfigMap
metadata:
  creationTimestamp: 2017-08-10T01:21:28Z
  name: my-config
  namespace: test
  resourceVersion: "2368592"
  selfLink: /api/v1/namespaces/test/configmaps/my-config
  uid: 3bde7d2d-7d6a-11e7-9d4a-fa163ed438e9
```
**My pod.yaml:**
```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  namespace: test
spec:
  containers:
    - name: test-container
      image: nginx:latest
      volumeMounts:
      - name: config-volume
        mountPath: /usr/src/app/config
  volumes:
    - name: config-volume
      configMap:
        name: my-config
        items:
        - key: config.json
          path: config.json
  restartPolicy: Never
```

**Comment by kfox1111** [comment]
@supereagle that is not the same thing. sometimes you want to merge in a few config files into a magic config dir, like, /etc/condor/config.d, but leave the rest of the dir open for other things to drop things in. subPath is the right way to do that I think. but should be able to get updates still.

**Comment by scheng1** [comment]
@scheng1

**Comment by Boxx** [comment]
Bump

**Comment by QiuMike** [comment]
Any update for this issue? 
When I create a volume using hostPath with a file, it also has this problem.
That is: modified the host file, Pod's doesn't changed.

apiVersion: v1
kind: ReplicationController
metadata:
   name: cloud52
   namespace: kube-system
spec:
  replicas: 1
  selector:
     name: cloud52
  template:
    metadata:
     labels:
       name: cloud52
    spec:
      volumes:
      - name: hosts-volume
        hostPath:
          path: /root/k8s/hosts
      hostname: cloud52
      subdomain: cloud52
      containers:
      - image: DockerRegistry:5000/centos
        command:
          - sleep
          - "3600"
        name: cloud52
        volumeMounts:
        - name: hosts-volume
          mountPath: /etc/hosts
---
apiVersion: v1
kind: Service
metadata:
  name: cloud52
  namespace: kube-system
spec:
  selector:
    name: cloud52
  ports:
  - name: foo # Actually, no port is needed.
    port: 23
    targetPort: 23

**Comment by liggitt** [comment]
cc @kubernetes/sig-storage-bugs

**Comment by jberkus** [comment]
@maeb do you see this getting done in the next 5 days for 1.10?

**Comment by jberkus** [comment]
This issue and its related PRs will be removed from 1.10 at Code Freeze on Monday, unless they are all updated with status/approved-for-milestone and with a progress update.  If that's fine, do nothing; if you are still targeting 1.10, please let us know what's going on and update the labels.  Thanks!

**Comment by jberkus** [comment]
As a reminder, this issue is about to be kicked out of 1.10 tracking in 6 hours, because it doesn't have the required labels.  If this is actually an 1.10 issue, please update it!  @maeb @thesandlord

**Comment by msau42** [comment]
I think we just need to document this as a known limitation.

Because subpaths are bind mounted by docker, if it was a symlink, then it gets resolved to the actual path during the bindmount.

**Comment by tpepper** [comment]
@msau42 if that's the decision, please remove v1.10 milestone designation

**Comment by msau42** [comment]
This is a known limitation of using subpath with atomic volume types and has been documented.  There is no fix planned.

**Comment by kundralaci** [comment]
@mingfang  you are right.

This configMap / items works great, it's a symlink, so it get updated when the ConfigMap updates.
However, it does not solve the other problem: let's say if I want to mount nginx.conf to /etc/nginx/nginx.conf the directory /etc/nginx becomes empty (removing all other default configs), and will only contain this (finally symlinked) nginx.conf :(

I would love to have a solution that combines symlinks (for hot reload), and keeping original directory contents...

**Comment by vincbe** [comment]
@kundralaci it seems to be now possible , look at that : https://github.com/kubernetes/kubernetes/issues/44815#issuecomment-297077509
I've just tested a few minutes ago and seems working great.

**Comment by ptemmer** [comment]
I bumped into this issue because I was having the same frustraing problem.
However, I think the following could be a legit workaround:

Designate a folder where you will mount your desired configmaps, for example:

`/configmaps/`

Make the mountPath of each configmap (or secret) a subfolder of this folder.
Going further on previous examples with nginx, your mount would look like this:

`
 - name: nginx-configmap   # contains nginx.conf
    mountPath: /configmaps/nginx
`
Now, to tie this all together, create a symlink from /etc/nginx/nginx.conf to /configmaps/nginx/nginx.conf. This symlink can exist before the configmap is even mounted.

Whenever you update the configmap, the /configmap/nginx folder is remounted, and your symlink is now pointing to the updated version.

**Comment by jnicholls** [comment]
@ptemmer It's a decent workaround no doubt. Just more boilerplate to handle on container start.

**Comment by jeff-1amstudios** [comment]
@ptemmer

**Comment by ptemmer** [comment]
@jeff-1amstudios In the Dockerfile of the image

**Comment by wanghaibo** [comment]
we do it like this:
`      initContainers:
      - name: init-myservice
        image: openresty:1.13.6.1
        volumeMounts:
        - mountPath: /tmpconfig
          name: tmpconfig
        - mountPath: /configmap/usr/local/openresty/nginx/conf/
          name: nginx-conf
        command: ['sh', '-c', 'mkdir /tmpconfig/test; cp /usr/local/openresty/nginx/conf/* /tmpconfig/test;ln -sf  /configmap/usr/local/openresty/nginx/conf/* /tmpconfig/test/;']
      containers:
      - image: openresty:1.13.6.1
        name: openresty
        command: ['sleep', '100000']
        volumeMounts:
        - mountPath: /usr/local/openresty/nginx/conf/
          name: tmpconfig
          subPath: test
        - mountPath: /configmap/usr/local/openresty/nginx/conf/
          name: nginx-conf
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: openresty-nginx.conf
            path: nginx.conf
          name: nginxconf
        name: nginx-conf
      - emptyDir: {}
        name: tmpconfig`

it work for us but not clean enough

**Comment by ptagr** [comment]
+1 just saw this issue with nginx configmap as well. k8s 1.10.x

**Comment by rally25rs** [comment]
Any way that this issue can be reopened?
I ran into it with AWS EKS, and mounting a ConfigMap like

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
  ...
data:
  site_config.yml: |
    ...some raw config string...

---

apiVersion: apps/v1
kind: Deployment

spec:
  ...
  template:
    ...
    spec:
      containers:
        ...
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/site_config.yml
              subPath: site_config.yml
      volumes:
      - name: config-volume
        configMap:
          name: site-config
```

You can update the `ConfigMap`, then wait some time (I waited 30min).
Then `kubectl exec -ti {pod} -- bash` into the running pod, `cat /usr/src/app/site_config.yml` and still see the old ConfigMap value.

Deleting the pod to force recreation results in having the correct file contents mounted.
