### ISSUE TITLE
 "cannot join network of a non running container" failed to start a container

### ISSUE THREAD

**Issue by barathjoeee** [kubernetes/kubernetes#50356]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by idvoretskyi** [comment]
@barathjoeee there's no exact information at the issue body (together with empty issue description).

Please, update the issue description by filling the template before someone may assist you.

**Comment by kenden** [comment]
Not enough information, no updates, I suggest to close.

**Comment by willstudy** [comment]
I met this problem too.

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
kubectl describe po redis-0
```
 5m		5m		1	default-scheduler				Normal		Scheduled		Successfully assigned redis-0 to node2-evm1
  5m		5m		1	kubelet, node2-evm1				Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-1tlsx" 
  5m		5m		2	kubelet, node2-evm1				Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "pvc-f2d2a9df-db27-11e7-ad3c-fa163e1b9497" 
  3m		3m		1	kubelet, node2-evm1	spec.containers{redis}	Normal		Pulled			Container image "index-dev.qiniu.io/kelibrar/redis:3.2.8" already present on machine
  3m		3m		1	kubelet, node2-evm1	spec.containers{redis}	Normal		Created			Created container
  3m		3m		1	kubelet, node2-evm1	spec.containers{redis}	Warning		Failed			Error: failed to start container "redis": Error response from daemon: {"message":"cannot join network of a non running container: ccd1f187281f0802c254942c0fd3844e8d780184d88dff255479d2ea2e556377"}
  5m		4s		45	kubelet, node2-evm1				Warning		FailedSync		Error syncing pod
  5m		4s		44	kubelet, node2-evm1				Normal		SandboxChanged		Pod sandbox changed, it will be killed and re-created.
```
statefulsets.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
  labels:
    name: redis
spec:
  serviceName: redis
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: hub.c.163.com/lecury/redis:3.2.8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: key
        volumeMounts:
        - name: redis-volume
          mountPath: /data
      imagePullSecrets: 
        - name: registry-secret
  volumeClaimTemplates:
  - metadata:
      name: redis-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph
      resources:
        requests:
          storage: 10Gi
```
