### ISSUE TITLE
Kubelet TLS Bootstrap issued certificate is not valid for hostName of node

### ISSUE THREAD

**Issue by christianhuening** [kubernetes/kubernetes#50371]
/kind bug

**What happened**:
I am trying to use api-server kubelet-client certificate creation as per the TLS Bootstrap guide for the Kubelet TLS Bootstrap feature (https://github.com/kubernetes/features/issues/43). While the node join and certificate handshake works fine, it seems that the certificate does not get created correctly.
After the node successfully joined the cluster I get a
´´´certificate is valid for system:node:<nodename>, not for <nodename>´´´
when trying to issue any command on a pod running on that node (i.e. kubectl logs or kubectl exec).
What is missing from the CNF, I think, is a proper alt-name for the hostname as it only has the CN set as system:node.

**What you expected to happen**:
The nodes joins and I can issue kubectl commands perfectly fine.

**How to reproduce it (as minimally and precisely as possible)**:
I am using these kubelet.service definitions:
```shell
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
ExecStart=/usr/bin/kubelet \
  --allow-privileged=true \
  --cluster-dns=10.32.0.10,10.32.0.11,10.32.0.12 \
  --cluster-domain=cluster.local \
  --container-runtime=docker \
  --pod-manifest-path=/etc/kubernetes/manifests \
  --require-kubeconfig \
  --bootstrap-kubeconfig=/var/lib/kubelet/bootstrap.kubeconfig \
  --network-plugin=cni \
  --kubeconfig=/var/lib/kubelet/worker-kubeconfig.yaml \
  --serialize-image-pulls=false \
  --register-node=true \
  --tls-cert-file=/var/lib/kubernetes/kubelet-client.crt \
  --tls-private-key-file=/var/lib/kubernetes/kubelet-client.key \
  --cert-dir=/var/lib/kubernetes \
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```
And my API Servers start like that:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:v1.7.2_coreos.0
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --apiserver-count=3
    - --audit-log-maxage=30
    - --audit-log-maxbackup=3
    - --audit-log-maxsize=100
    - --audit-log-path=/var/lib/audit.log
    - --enable-swagger-ui=true
    - --authorization-mode=RBAC
    - --etcd-cafile=/etc/kubernetes/ssl/ca.pem
    - --etcd-certfile=/etc/kubernetes/ssl/kubernetes.pem
    - --etcd-keyfile=/etc/kubernetes/ssl/kubernetes-key.pem
    - --etcd-servers=<MultipleIPs>
    - --allow-privileged=true
    - --service-cluster-ip-range=10.32.0.0/24
    - --secure-port=443
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
    - --kubelet-certificate-authority=/etc/kubernetes/ssl/ca.pem
    - --kubelet-client-certificate=/etc/kubernetes/ssl/apiserver.pem
    - --kubelet-client-key=/etc/kubernetes/ssl/apiserver-key.pem
    - --service-account-key-file=/etc/kubernetes/ssl/ca-key.pem
    - --tls-ca-file=/etc/kubernetes/ssl/ca.pem
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/ca.pem
    - --authentication-token-webhook-config-file=/etc/kubernetes/ssl/ldap-webhook-config.yaml
    - --authentication-token-webhook-cache-ttl=30m0s
    - --runtime-config=authentication.k8s.io/v1beta1=true
    - --token-auth-file=/etc/kubernetes/ssl/token.csv
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /var/lib/kubernetes/
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2+coreos.0", GitCommit:"c6574824e296e68a20d36f00e71fa01a81132b66", GitTreeState:"clean", BuildDate:"2017-07-24T23:28:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: Bare-Metal / On-Prem
- OS (e.g. from /etc/os-release):
Nodes running Ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`):  4.10.0-20-generic
- Install tools: Puppet
- Others:

**Comment by christianhuening** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by christianhuening** [comment]
Found I had to activate ```--feature-gates=RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true``` on Kubelet and controller manager

**Comment by jcrowthe** [comment]
@christianhuening I have an identical issue to what you experienced here. In adding the feature flag as suggested, I now see the kubelet submitting a CSR, but it is not being auto-approved. If I manually approve the CSR, `kubectl logs|exec` works as desired. I'm looking to see if you are specifying some auto-approver other than roles and bindings for the following?

`system:certificates.k8s.io:certificatesigningrequests:selfnodeclient`
`system:certificates.k8s.io:certificatesigningrequests:nodeclient`

**Comment by christianhuening** [comment]
@jcrowthe I also added RBAC rules and roleBindings:

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: icc-nodes-client-cert-renewal
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: approve-node-client-renewal-csr
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: icc-nodes-server-cert-renewal
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: approve-node-server-renewal-csr
  apiGroup: rbac.authorization.k8s.io
```
and
```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auto-approve-csrs-for-group
subjects:
- kind: User
  name: kubelet-bootstrap
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: approve-node-client-csr
  apiGroup: rbac.authorization.k8s.io
```

and
```yaml
# A ClusterRole which instructs the CSR approver to approve a user requesting
# node client credentials.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: approve-node-client-csr
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/nodeclient"]
  verbs: ["create"]
---
# A ClusterRole which instructs the CSR approver to approve a node renewing its
# own client credentials.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: approve-node-client-renewal-csr
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/selfnodeclient"]
  verbs: ["create"]
---
# A ClusterRole which instructs the CSR approver to approve a node requesting a
# serving cert matching its client cert.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: approve-node-server-renewal-csr
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/selfnodeserver"]
  verbs: ["create"]
```
