### ISSUE TITLE
oidc with kubernetes gives : You must be logged in to the server error

### ISSUE THREAD

**Issue by spnzig** [kubernetes/kubernetes#50432]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**:
I have configured oidc with kubernetes. But when i try `kubectl --user=spnzip@gmail.com get nodes` i get `error from server (Forbidden): User "system:anonymous" cannot list nodes at the cluster scope. (get nodes)
`

**What you expected to happen**:
The command should authenticate user and display the nodes 

**How to reproduce it (as minimally and precisely as possible)**:
1. Install single node kubernetes cluster with kubeadm
2. Obtain client secrets with the k8s-oidc-helper tool
k8s-oidc-helper -c <path where user's client id and secret is stored)
3. copy paste the code generated to ~/.kube/config file
```
- name: spnzig@gmail.com
  user:
    auth-provider:
      config:
        client-id: xxxxxxxxxx-xxxxxxx.apps.googleusercontent.com
        client-secret: xxxxxxxxxxxxxxxxxxxxxxx
        id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMTdkOTM1MWQ1Y .... njZaIWlMaAFEfIrGPy-49TQ
        idp-issuer-url: https://accounts.google.com
        refresh-token: 1/3XPbQPD...g8PuNPs
      name: oidc
```

4. Set the context for the new user in ~/.kube/config file
```
- context:
    cluster: kubernetes
    user: spnzig@gmail.com
  name: spnzig@kubernetes
```

5. Switch context from admin to new user
`kubectl config use-context spnzig@kubernetes `
 
6. Run kubectl --user=spnzig@gmail.com get nodes to see the error 
`kubectl --user=spnzig@gmail.com get nodes`

**Anything else we need to know?**:
I have installed kubernetes on Ubuntu 16.04LTS.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.3
- Cloud provider or hardware configuration**: hardware 
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Install tools: kubeadm, kubernetes, k8s-oidc-helper, go
