### ISSUE TITLE
NetworkPolicy Egress with CIDRSelector and DNSSelector

### ISSUE THREAD

**Issue by mccormd** [kubernetes/kubernetes#50453]
/kind feature

**What happened**:
In 1.7 NetworkPolicy only supports ingress (although some cni providers like Calico claim to be able to also support egress).

No doubt that egress is already on the roadmap, but I'd like to state a requirement for a couple of selectors that we'll need in order for the egress functionality to be useful in enterprise environments.

1) CIDRSelector 

We need to be able to define egress rules from cluster pods to external services.  As these are external they lack both a namespace and any labels.  For something analogousness to traditional firewalling, it would be useful to define NetworkPolicy rules that allows egress to a number of network CIDRS or hosts. e.g.

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-rule-for-logging
  namespace: backend
spec:
  podSelector:
    matchLabels:
      run: pod
  egress:
  - to:
    - CIDRSelector:
      - 192.168.0.0/16
      - 10.0.*
      - 192.169.0.12
    ports:
    - port: 80
```

2) DNSSelector

As more services are more dynamically IP'd (e.g. consul or an ELB etc.) it becomes hard to pinpoint an external service by CIDR without being too general.  In the same kind of vein as the ExternalCNAME on services it would be very useful to be able to create a egress rule that uses a DNS query to populate a list of IP Addresses in the rule (and to keep them updated by performing the dns check on a regular interval).  They could look something like this,,,

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-rule-for-domaincontrollers
  namespace: backend
spec:
  podSelector:
    matchLabels:
      run: pod
  egress:
  - to:
    - DNSSelector:
      -  adfs.mycompanyforrest.ad.mycompany.com
    ports:
    - port: 636
```
In this example the dns query adfs.mycompanyforrest.ad.mycompany.com can be enumerated into a number of host ip addresses and egress allowed to this list only.  This would allow the IT team to add/remove servers at will without having to maintain a brittle egress rule.

**What you expected to happen**:
I'd like to see NetworkPolicy grow to include egress with new selectors that help ease the job of infrastructure developers defining rules for their infrastructure.

**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8?
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): CoreOS
- Kernel (e.g. `uname -a`): Linux
- Install tools:
- Others:

/sig network
