### ISSUE TITLE
Finalizers are broken for CRDs in 1.7

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#50528]
Create a CRD (`kubectl create -f`):

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: databases.example.com
spec:
  group: example.com
  version: v1
  names:
    kind: Database
    plural: databases
    scope: Namespaced
```

and a CR  (`kubectl create -f`):
```
apiVersion: example.com/v1
kind: Database
metadata:
  name: wordpress
spec:
  user: wp
  password: secret
  encoding: unicode
```

Then add a finalizer: ```kubectl edit database wordpress``` by changing it to:
```
apiVersion: example.com/v1
kind: Database
metadata:
  name: wordpress
  ...
  finalizers:
  - foo
spec:
  ...
```

Delete the resource:
```
$ kubectl delete database wordpress
```

The resource is gone, but shouldn't.
