### ISSUE TITLE
Time-Based Auto Scaling for Applications

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#50569]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:

The Kubernetes only support auto scaling based on CPU and some other [customized metrics](https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/run-application/horizontal-pod-autoscale.md#support-for-custom-metrics) now, the problem is that in a production environment, most customers do not want to use metrics based autoscaling as it is not safe: Sometimes the high CPU/Memory utilization may not caused by real workload but may be a bug in the application sometime, for this case, the application scale up may use up all of the resources in the clusters.

Most customers prefer auto scaling based on time windows, as they actually know when their applications will have a high workload. Such as for some mobile applications, the customers know that they will need more resources by the end of each month as they need to do some billing checkpoint etc; For some e-Commerce applications, the customers know that they need more resources when they are promoting some products on Black Friday etc.

So what they want is Time-Based Auto Scaling for Applications.

There are two solutions for this:

Solution 1) Leverage `CronJob` in Kubernetes, we may need to build a image which include `kubectl` binary, and use `kubectl` to scale the application. The following is an example, it means the application of nginx will be scaled to 3 replicas every day at 8am. This is simple and straightforward. The problem is that each application need a cronjob and the Kubernetes may have many jobs if we want to scale many applications.

```
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: scale-up
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scale
            image: siji/kubectl:v1.5.2
            command:
            - kubectl.sh
            - kubectl
            - scale
            - --replicas=3
            - deployment/nginx
          restartPolicy: OnFailure
```

Solution 2) Similar as [Calico policy controller for Kubernetes](https://github.com/projectcalico/k8s-policy), develop a new controller for time based auto scaling. This is a clean solution but need more effort.

/sig apps
