### ISSUE TITLE
dynamically provision EBS persistent volumes with XFS filesystem

### ISSUE THREAD

**Issue by d-shi** [kubernetes/kubernetes#50648]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**: I would like to use PVCs to dynamically provision XFS volumes on AWS EBS. This example document implies that it would be possible to create a storage class using the aws-ebs provisioner that has fsType be xfs: https://github.com/kubernetes/examples/blob/master/staging/persistent-volume-provisioning/README.md

I tried creating the following storage class and PVC, but the resulting PVC just gets stuck in pending state:

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: xfs-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  fsType: xfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: xfs-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: xfs-storage-class
  resources:
    requests:
      storage: 200Gi
```

I also tried to `fsType: ext4` with the same result, so it seems like `fsType` is not actually a valid parameter.

**What you expected to happen**: A persistent EBS volume should be created and mounted to the pod that requests the PV as an XFS filesystem.

**How to reproduce it (as minimally and precisely as possible)**: See above config example.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): 
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
`Linux 4.4.65-k8s #1 SMP Tue May 2 15:48:24 UTC 2017 x86_64 GNU/Linux`
- Install tools: custom
- Others:
