### ISSUE TITLE
apiserver panic on 1.7.3  --admission-control=NamespaceLifecycle

### ISSUE THREAD

**Issue by karlvlam** [kubernetes/kubernetes#50661]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Trying to upgrade from 1.6.7 to 1.7.3, using hyperkube api-server with the same configuration hit this error:

```
2017-08-15 06:25:19.419583 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-15 06:25:19.419727 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-15 06:25:19.419759 I | proto: duplicate proto type registered: google.protobuf.Timestamp
I0815 06:25:19.462371       1 server.go:112] Version: v1.7.3+coreos.0
I0815 06:25:19.462685       1 aws.go:806] Building AWS cloudprovider
I0815 06:25:19.462737       1 aws.go:769] Zone not specified in configuration file; querying AWS metadata service
I0815 06:25:19.603659       1 tags.go:76] AWS cloud filtering on ClusterID: mycluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x16653e6]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle.(*lifecycle).SetExternalKubeInformerFactory(0xc42079dd40, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go:203 +0x26
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/initializer.pluginInitializer.Initialize(0x8fcc9a0, 0xc420775600, 0x0, 0x0, 0x8f7c760, 0xc420eb81e0, 0x8f86160, 0xc42079dd40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/initializer/initializer.go:49 +0x112
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/initializer.(*pluginInitializer).Initialize(0xc420ce0d80, 0x8f86160, 0xc42079dd40)
	<autogenerated>:1 +0x70
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.PluginInitializers.Initialize(0xc420ec22a0, 0x2, 0x2, 0x8f86160, 0xc42079dd40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugins.go:180 +0x5d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.(*PluginInitializers).Initialize(0xc420ec22c0, 0x8f86160, 0xc42079dd40)
	<autogenerated>:18 +0x73
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.(*Plugins).InitPlugin(0xc4202aae10, 0xc420409580, 0x12, 0x0, 0x0, 0x8f7c620, 0xc420ec22c0, 0x413390, 0xc420ec22a0, 0xc420ec2260, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugins.go:155 +0x20c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.(*Plugins).NewFromPlugins(0xc4202aae10, 0xc42043b5e0, 0x7, 0x7, 0x8f7c660, 0xc42079d200, 0x8f7c620, 0xc420ec22c0, 0x0, 0xc420cd8480, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugins.go:129 +0x126
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options.(*AdmissionOptions).ApplyTo(0xc420cf5470, 0xc42088ca80, 0xc420ec2260, 0x2, 0x2, 0x8fc5300, 0xc420f60900)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options/admission.go:84 +0x453
k8s.io/kubernetes/cmd/kube-apiserver/app.BuildGenericConfig(0xc420483c00, 0x0, 0x0, 0x0, 0x2, 0x1, 0x0, 0x1, 0xc420d39d60, 0xc420d7cbd0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:448 +0x1150
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateKubeAPIServerConfig(0xc420483c00, 0x0, 0x0, 0x8f76ba0, 0xc42024d860, 0x0, 0x6d17640, 0x28, 0x6cf0bcc, 0x5, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:254 +0xa9
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc420483c00, 0xc4200560c0, 0xc420ce99f8, 0xc4200ccff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:119 +0x143
main.NewKubeAPIServer.func1(0xc42014c660, 0xc420799140, 0x0, 0xc, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/kube-apiserver.go:36 +0x36
main.(*HyperKube).Run(0xc420204a20, 0xc4200100f0, 0xc, 0xc, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:177 +0x3ec
main.(*HyperKube).RunToExit(0xc420204a20, 0xc4200100e0, 0xe, 0xe)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:187 +0x59
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/main.go:47 +0x847
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
start apiserver with `NamespaceLifecycle`, it panic:
```
--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds
```

after removing `NamespaceLifecycle`, it works:
```
--admission-control=LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds
```

**Anything else we need to know?**:
The pod startup script:
/etc/kubernetes/manifests/kube-apiserver.yml
```yml
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:v1.7.3_coreos.0 
    command:
    - /hyperkube
    - apiserver
    - --cloud-provider=aws
    - --insecure-bind-address=0.0.0.0
    - --insecure-port=8080
    - --anonymous-auth=false
    - --secure-port=0
    - --apiserver-count=3 
    - --etcd-servers=http://etcd-cluster:2379
    - --allow-privileged=true
    - --service-cluster-ip-range=10.123.0.0/16
    - --advertise-address=10.0.233.106
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds
    - --runtime-config=extensions/v1beta1=true,extensions/v1beta1/networkpolicies=true
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local

```

**Environment**:
- Kubernetes version (use `kubectl version`):
 docker image -> quay.io/coreos/hyperkube:v1.7.3_coreos.0

- Cloud provider or hardware configuration**: AWS

- OS ( /etc/os-release):
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1409.7.0
VERSION_ID=1409.7.0
BUILD_ID=2017-07-19-0005
PRETTY_NAME="Container Linux by CoreOS 1409.7.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`):
Linux ip-10-0-233-106.ec2.internal 4.11.11-coreos #1 SMP Tue Jul 18 23:06:59 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
- Install tools:
 custom setup
