### ISSUE TITLE
Flexvolume nfs volume unavailable for pod after reboot the node

### ISSUE THREAD

**Issue by heartlock** [kubernetes/kubernetes#50677]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
Here is my deployment spec  deployment.yaml.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flexvolume-nfs-nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: flexvolume-nfs-nginx
        image: nginx
        volumeMounts:
            - name: "alicloud-nas"
              mountPath: "/var/lib"
      volumes:
      - name: "alicloud-nas"
        flexVolume:
            driver: "k8s/nfs"
            fsType: "nfs"
            options:
                server: "376ffgftd0-urw79.cn-hangzhou.nas.aliyuncs.com"
                share: "/"
```
Then run deployment.yaml:
```
# kubectl create -f deployment.yaml

# kubectl get pod -owide
NAME                                               READY     STATUS    RESTARTS   AGE       IP            NODE
flexvolume-nfs-nginx-deployment-3069379837-gzr0g   1/1       Running   0          5s       172.16.1.72   izbp1hf1zvue77szjqf15bz
http-svc-ntxzk                                     1/1       Running   0          4d        172.16.0.6    izbp1hg1tn43gjnfnl6nhpz
http-svc-s27mj                                     1/1       Running   0          4d        172.16.0.3    izbp1hg1tn43gjnfnl6nhpz

# kubectl exec -it flexvolume-nfs-nginx-deployment-3069379837-gzr0g sh
      
(insidepod)# ls var/lib
(insidepod) luke
```
since file "luke"(in alicloud-nas) exist in var/lib, flexvolume nfs volume is available.

Next I reboot node  izbp1hf1zvue77szjqf15bz

```
# kubectl get pod -owide
NAME                                               READY     STATUS    RESTARTS   AGE       IP            NODE
flexvolume-nfs-nginx-deployment-3069379837-gzr0g   1/1       Running   1          15m       172.16.1.72   izbp1hf1zvue77szjqf15bz
http-svc-ntxzk                                     1/1       Running   0          4d        172.16.0.6    izbp1hg1tn43gjnfnl6nhpz
http-svc-s27mj                                     1/1       Running   0          4d        172.16.0.3    izbp1hg1tn43gjnfnl6nhpz

# kubectl exec -it flexvolume-nfs-nginx-deployment-3069379837-gzr0g sh
(insidepod)# ls var/lib
(insidepod) 

(izbp1hf1zvue77szjqf15bz)# mountpoint /var/lib/kubelet/plugins/kubernetes.io/flexvolume/k8s/nfs/mounts/alicloud-nas/
/var/lib/kubelet/plugins/kubernetes.io/flexvolume/k8s/nfs/mounts/alicloud-nas/ is not a mountpoint

(izbp1hf1zvue77szjqf15bz)# mountpoint /var/lib/kubelet/pods/5a6ba0a2-81ac-11e7-8a1b-00163e0dfa64/volumes/k8s~nfs/alicloud-nas/
/var/lib/kubelet/pods/5a6ba0a2-81ac-11e7-8a1b-00163e0dfa64/volumes/k8s~nfs/alicloud-nas/ is not a mountpoint
```

After reboot node, flexvolume nfs volume become unavailable.

**What you expected to happen**:
I'm looking for help to fix this reboot node issue.  I fixed this issue by modify code of flexvolume as below: 
```
--- a/pkg/volume/flexvolume/plugin.go
+++ b/pkg/volume/flexvolume/plugin.go
@@ -164,6 +164,12 @@ func (plugin *flexVolumePlugin) NewDetacher() (volume.Detacher, error) {

 // ConstructVolumeSpec is part of the volume.AttachableVolumePlugin interface.
 func (plugin *flexVolumePlugin) ConstructVolumeSpec(volumeName, mountPath string) (*volume.Spec, error) {
+       mounter := plugin.host.GetMounter()
+       pluginDir := plugin.host.GetPluginDir(plugin.GetPluginName())
+       _, err := mounter.GetDeviceNameFromMount(mountPath, pluginDir)
+       if err != nil {
+               return nil, err
+       }
        flexVolume := &api.Volume{
                Name: volumeName,
                VolumeSource: api.VolumeSource{
```
I think it is necessary to check mountPath whether is a mountpoint when sync volume spec from disk.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+$Format:%h$", GitCommit:"62e6e969c5b6a6685ff96ab323275454ec9f4233", GitTreeState:"clean", BuildDate:"2017-07-14T05:53:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+$Format:%h$", GitCommit:"62e6e969c5b6a6685ff96ab323275454ec9f4233", GitTreeState:"clean", BuildDate:"2017-07-14T05:42:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:  alicloud

- OS (e.g. from /etc/os-release): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

- Kernel (e.g. `uname -a`): 
Linux izbp1hf1zvue77szjqf15bz 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: 
Custom Implementation

/cc  @resouer  @feiskyer  @chakri-nelluri
