### ISSUE TITLE
Kubelet fails to delete glusterfs-volume

### ISSUE THREAD

**Issue by LarsKumbier** [kubernetes/kubernetes#50772]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When using heketi and glusterfs to provision persistent volumes (PVs), the created pvs are not deleted despite a ReclaimPolicy of `Delete` and remain in the status `Failed`.

**What you expected to happen**:

The PVs to be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a cluster with heketi and register an appropriate StorageClass (e.g. `glusterfs`) for it in kubernetes - it is helpful to have access to the heketi-server-logs and crank up the [log-level to debug](https://github.com/heketi/heketi/wiki/Running-the-server)
* Create a PersistentVolumeClaim:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterfs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```
* Make sure that an appropriate and dynamically provisioned PersistentVolume is created with a ReclaimPolicy of `Delete` by running `kubectl get pv`
* Also observe that the heketi-server-log will show the appropriate REST-calls needed to create the glusterfs-volumes
* Now delete the pvc: `kubectl delete pvc example`

**Expected result**

* The heketi-server should show some communication from kubernetes, but does *not*
* Check that the PV is now gone (*expected*): `kubectl get pvc`
* Observe that the PVC is not gone but stays in the Status `Failed` via `kubectl get pv` instead of *being deleted*

```
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                      STORAGECLASS   REASON    AGE
pvc-5ac9a25a-794a-11e7-9040-c8600054be05   2Gi        RWO           Delete          Failed    default/example            glusterfs                1h
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.0
- Heketi version: 4.0
- Cloud provider or hardware configuration**: baremetal
- OS (e.g. from /etc/os-release): ubuntu-16.04
- Kernel (e.g. `uname -a`): 4.8.0-58-generic #63~16.04.1-Ubuntu
- Install tools: kubeadm
