### ISSUE TITLE
Selenium containers in Kubernetes with browsermob

### ISSUE THREAD

**Issue by bdshibly** [kubernetes/kubernetes#50774]
We are trying to deploy the selenium containers in Kubernetes on AWS (we are using m4.xlarge for kubernetes nodes). We deployed browsermob on separate EC2 instance as browsermob opens a rang of ports. When we are running any test, the proxy test is taking long time to initiate. But when we are running the same test on selenium which are configured on EC2 instance, it is instantly initiating the proxy test. 

Here are our deployment scripts

```
Selenium Hub:

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: selenium-hub-debug
  namespace: selenium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: selenium-hub-debug
        environment: prod
        department: qa
    spec:
      containers:
      - name: selenium-hub-debug
        image:  selenium/hub:2.53.1
        ports:
          - containerPort: 4444
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
      nodeSelector:
        selenium: grid
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
```
```
Selenium chrome grid

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: selenium-node-chrome-debug-1
  namespace: selenium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: selenium-node-chrome-debug-1
        environment: prod
        department: qa
    spec:
      containers:
      - name: selenium-node-chrome-debug-1
        image:  selenium/node-chrome-debug:2.53.1
        ports:
          - name: chrome-debug
            containerPort: 5900
        resources:
          limits:
            memory: "1000Mi"
            cpu: "3"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: HUB_PORT_4444_TCP_ADDR
            value: "selenium-hub-debug"
          - name: HUB_PORT_4444_TCP_PORT
            value: "4444"
          - name: NODE_MAX_INSTANCES
            value: "5"
          - name: NODE_MAX_SESSION
            value: "5"
      nodeSelector:
        selenium: node
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
```
Any help will be appreciated.

Cheers
Ferdous Shibly
