### ISSUE TITLE
The ScaleIO volume plugin is not applying `fsGroup`  value properly

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#50794]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
The ScaleIO volume plugin is not applying `fsGroup`  value properly.

**What you expected to happen**:
When `fsGroup` value is specified in the spec, the mounted volume does not reflect the expected value of the `fsGroup`.

**How to reproduce it (as minimally and precisely as possible)**:
Set fsGroup value in a spec:
```
apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
...
```
After pod is deployed, the mounted directory for the volume does not reflect the fsGroup value.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.x and lower
