### ISSUE TITLE
websockets and sessionAffinity do not seem to be working in Google Container Engine (GKE)

### ISSUE THREAD

**Issue by briangruber** [kubernetes/kubernetes#50866]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:
I'm using Google Container Engine and the Node pool version is currently 1.7.0
I'm trying to get websockets to load balancer to the same pod. If I have a yaml file like below for a `LoadBalancer` then it does seem to send me to the same pod if I go directly to the loadBalancerIP using standard http(s). But as soon as websockets kick in, the pod is random every time. 
```
---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: realtime-deployment
spec:
  replicas: 20
  minReadySeconds: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: realtime
    spec:
      containers:
      - name: realtime
        image: us.gcr.io/example/realtime:{{VERSION}}
        ports:
        - name: http-port
          containerPort: 8080
        - name: https-port
          containerPort: 8081
        resources:
          requests:
            cpu: 1
            memory: 2.5Gi
          limits:
            cpu: 4
            memory: 2.5Gi
        livenessProbe:
          httpGet:
            path: /
            scheme: HTTPS
            port: https-port
          initialDelaySeconds: 300
          timeoutSeconds: 5
          periodSeconds: 100
        readinessProbe:
          httpGet:
            path: /
            scheme: HTTPS
            port: https-port
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30     

---
# Service to load balance to pod
apiVersion: v1
kind: Service
metadata:
  name: realtime-service
  labels:
    app: realtime
spec:
  sessionAffinity: ClientIP
  externalTrafficPolicy: "Local"
  type: LoadBalancer
  loadBalancerIP: 123.45.67.8
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-port
    - name: https
      protocol: TCP
      port: 443
      targetPort: https-port
  selector:
    app: realtime
```

**What you expected to happen**:
Websockets should take me to the same pod on reloading the page.

**How to reproduce it (as minimally and precisely as possible)**:
Create a LoadBalancer as above with a deployment. Personally, I created a node script for the deployment that will respond to the websocket requests and send the internal ip of the pod. Did the same thing for a basic http route to get the internal ip. Keep reloading the page in browser and for the basic http route the internal ip will be the same, for the websocket it will change. Ensure you have many pods running.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.1-gke.0", GitCommit:"841411e511bfb1ccd78e76bf8633d4515061e18b", GitTreeState:"clean", BuildDate:"2017-07-14T17:52:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
` Google Container Engine`
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
