### ISSUE TITLE
Unable to provision SSD using volumeClaimTemplates  volume.beta.kubernetes.io/storage-class: ssd

### ISSUE THREAD

**Issue by bw2** [kubernetes/kubernetes#50983]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

StatefulSet unable to provision persistant SSD disk:

```
$ kubectl get pods
es-data-0                    0/1       Pending   0          6m
```
The pod stays pending indefinitely, and 'describe pods' shows `SchedulerPredicates failed due to PersistentVolumeClaim is not bound`
```
$ kubectl describe pods es-data-0
Name:		es-data-0
Namespace:	default
Node:		<none>
Labels:		component=elasticsearch
		deployment=gcloud-dev
		name=es-data
		role=data
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"default","name":"es-data","uid":"1a34e6a3-85dc-11e7-b7ef-42010af000fb","apiVersi...
		kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container es-data; cpu request for init container init-sysctl
		pod.beta.kubernetes.io/hostname=es-data-0
		pod.beta.kubernetes.io/subdomain=elasticsearch-data
Status:		Pending
IP:
Created By:	StatefulSet/es-data
Controlled By:	StatefulSet/es-data
Init Containers:
  init-sysctl:
    Image:	busybox
    Port:	<none>
    Command:
      sysctl
      -w
      vm.max_map_count=262144
    Requests:
      cpu:		100m
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7tx77 (ro)
Containers:
  es-data:
    Image:	quay.io/pires/docker-elasticsearch-kubernetes:5.5.1
    Port:	9300/TCP
    Requests:
      cpu:	100m
    Environment:
      NAMESPACE:		default (v1:metadata.namespace)
      NODE_NAME:		es-data-0 (v1:metadata.name)
      CLUSTER_NAME:		myesdb
      NODE_MASTER:		false
      NODE_INGEST:		false
      HTTP_ENABLE:		true
      ES_JAVA_OPTS:		-Xms2g -Xmx2g
      ES_PLUGINS_INSTALL:	mapper-size
    Mounts:
      /data from storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7tx77 (ro)
Conditions:
  Type		Status
  PodScheduled 	False
Volumes:
  storage:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	storage-es-data-0
    ReadOnly:	false
  default-token-7tx77:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-7tx77
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1m		3s		8	default-scheduler			Warning		FailedScheduling	[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "storage-es-data-0", which is unexpected.]
```

The StatefulSet config I'm deploying is:
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: {{ ES_DATA_NUM_PODS }}
  template:
    metadata:
      labels:
        name: es-data
        deployment: {{ DEPLOY_TO }}
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.5.1
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms2g -Xmx2g"
        - name: "ES_PLUGINS_INSTALL"
          value: "mapper-size"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: ssd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi
```

**What you expected to happen**:

new disk to be created

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Deployment of this StatefulSet works if I change the storage class from `ssd` to  `standard` 

This may be related to 
https://github.com/kubernetes/kubernetes/issues/42844

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**: MacBook Pro
- OS (e.g. from /etc/os-release): MacOSX
- Kernel (e.g. `uname -a`): 
Darwin wmd2b-dec 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64
- Install tools:
- Others:

**Comment by bw2** [comment]
I'm not sure why this is the case,  but the only way I can get SSD provisioning to work is by 1st creating a StorageClass:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ssd-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: us-central1-b
```
then manually creating a single SSD disk:
```
gcloud compute disks create elasticsearch-disk-%d  --type=pd-ssd --zone=us-central1-b --size=220Gb
```
and creating a PersistentVolume for it:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-disk-0
spec:
  capacity:
    storage: 220G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-storage-class
  gcePersistentDisk:
    fsType: ext4
    pdName: elasticsearch-disk-0
```
before deploying the StatefulSet.

Then, the 1st StatefulSet replica pod attaches to the manually-created disk, and the other 5 replicas automatically provision new SSDs:

![image](https://user-images.githubusercontent.com/6240170/29500131-9db473a8-85eb-11e7-8396-79fe33e21d8f.png)

SSD provisioning doesn't work (eg. StatefulSet pod 0 remains pending indefinitely) if I don't manually create the first disk for it to claim.
