### ISSUE TITLE
config map deletes existing files and sub directory at mount point

### ISSUE THREAD

**Issue by anurag-saran** [kubernetes/kubernetes#51165]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
I am trying to add environment specific xml files to a pod. The location where I want to update these xml files have few other xml files with sub directories at this location. I only want to update two files using configmap.

**What you expected to happen**:
Once I configure the configmap, the files and subdirectories are all deleted with my configmap files and only the files that are part of the config map show up in the pod at the mountpoint.
I want to only update the specific xml files i.e configured with configmap and still, want to see the other files and subdirectories at the mount point in the pod. 
**How to reproduce it (as minimally and precisely as possible)**:
Create a config map and mount it to the pod at a location where there are no of files and a sub directory. Using subPath also did not help.

**Anything else we need to know?**:
          volumeMounts:
        - mountPath: /deployments/websocket-chat/WEB-INF/web.xml
          name: volume-ju4m3
          subPath: web.xml
          
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: web.xml
            path: web.xml
          name: fromfile1-configmap
        name: volume-ju4m3
**Environment**:
- Kubernetes version (use `kubectl version`):
1.5
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): Rhel 7
- Install tools:
- Others:

/sig apps

**Comment by hzxuzhonghu** [comment]
currently， configmap/secret volumeMount use use empty dir, when configmap/secret update a new empty dir is created , so files and subpaths in the mounted path are lost.
```
root# ls -al /var/lib/kubelet/pods/bf802099-8331-11e7-8d70-286ed488fa01/volumes/kubernetes.io~configmap/flannel-cfg/
total 12
drwxrwxrwx 3 root root 4096 Aug 23 16:02 .
drwxr-xr-x 3 root root 4096 Aug 17 17:52 ..
drwxr-xr-x 2 root root 4096 Aug 23 16:02 ..8988_23_08_16_02_53.970622661
lrwxrwxrwx 1 root root   31 Aug 23 16:02 ..data -> ..8988_23_08_16_02_53.970622661
lrwxrwxrwx 1 root root   20 Aug 17 17:52 cni-conf.json -> ..data/cni-conf.json
lrwxrwxrwx 1 root root   20 Aug 17 17:52 net-conf.json -> ..data/net-conf.json
```

**Comment by anurag-saran** [comment]
I tried the same approach with the host file under /etc/.  This worked but not under WEB-INF. All the files in the container under /etc/ were not deleted. 
The only difference between both the dir was:
All directories, files belong to root:root under /etc
All files belong to jboss:root under WEB-INF.

**Comment by egeland** [comment]
See https://github.com/dshulyak/kubernetes.github.io/commit/d58ba7b075bb4848349a2c920caaa08ff3773d70

**Comment by Martinho0330** [comment]
@anurag-saran hihi, I have come across this issue too...Have you resolved it yet? How's the progress?

**Comment by sprutner** [comment]
I found an answer here: https://stackoverflow.com/questions/33415913/whats-the-best-way-to-share-mount-one-file-into-a-pod

**Comment by atheiman** [comment]
this works for mounting one or more files to an existing dir and keeping existing files alongside the files from the configmap

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  file1: file 1 contents
  file2: file 2 contents
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/nginx
      command: [ "/bin/sh", "-c", "sleep 1000" ]
      volumeMounts:
      - name: cm
        mountPath: /var/www/html/file1
        subPath: file1
  volumes:
    - name: cm
      configMap:
        name: test-cm
  restartPolicy: Never
```

```shell
$ kubectl apply -f cm-pod.yaml
$ kubectl exec -it test-pod /bin/sh
# cd /var/www/html
# ls -alh
total 16K
drwxr-xr-x 2 root root 4.0K Jan 10 19:39 .
drwxr-xr-x 3 root root 4.0K Mar 20  2015 ..
-rw-r--r-- 1 root root   15 Jan 10 19:39 file1
# -rw-r--r-- 1 root root  867 Mar 20  2015 index.nginx-debian.html
```
