### ISSUE TITLE
kubectl deployment of nginx with secrets fails with spurious "No such file or directory:fopen /etc/nginx/ssl/nginx.crt"

### ISSUE THREAD

**Issue by mxmberlin** [kubernetes/kubernetes#51164]
/kind bug

**What happened**:
I attempted to deploy the following deployment using kubectl 1.7.0

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      containers:
      - name: nginxhttps
        image: mylabel/nginx-demo:latest
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
```

where mylabel/nginx-demo was defined as follows 
```
# Dockerfile
FROM nginx:stable

# Set the work directory
WORKDIR /

# Install app dependencies
COPY etc/ /etc/
COPY var/ /var/

# Expose the port
EXPOSE 80 443 

# Allow the instance to catch relevant SIGNALs
STOPSIGNAL SIGTERM

# Start the app
CMD ["nginx", "-g", "daemon off;"]
```

Running `ls -l /etc/nginx/ssl` returns:
```
-rw-r--r-- 1 root root 1143 Aug 22 23:26 nginx.crt
-rw------- 1 root root 1708 Aug 22 23:26 nginx.key
```

This deployment fails with 

`nginx-demo-2723709651-kgd5t     0/1       CrashLoopBackOff   8          2m`

Where `kubectl logs ...` for the failed Pod reported:
`
nginx: [emerg] BIO_new_file("/etc/nginx/ssl/nginx.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/nginx.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
`

I can run the exact same Docker container on my local machine or otherwise outside kubernetes without this error - the container actually starts up nginx without error or other incident. 

**What you expected to happen**:
I expect this deployment to just work, not to fail with this spurious error. Nginx on my lone Docker container can read the required nginx.crt file. I really don't understand why this doesn't work in k8.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a docker image using the above Dockerfile and self-generated nginx.crt and nginx.key. 
2. Test the docker image locally to see it working as expected.
3. Attempt to deploy this image into a k8 namespace as follows:
kubectl create -f ./nginx-demo.yaml

Where nginx.yaml contains:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-demo
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      containers:
      - name: nginxhttps
        image: my-repo/nginx-demo
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
```

4. Watch `nginx-demo` fail to run with `CrashLoopBackOff` error

5. Check logs with `'kubectl logs <pod id> -p  to reveal:
`nginx: [emerg] BIO_new_file("/etc/nginx/ssl/nginx.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/nginx.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.0
- Cloud provider or hardware configuration**: AWS EC2
- OS (e.g. from /etc/os-release): 14.04.5 LTS, Trusty Tahr
- Kernel (e.g. `uname -a`): 3.13.0-125-generic #174-Ubuntu
- Install tools:
- Others:
