### ISSUE TITLE
Allow filtering of TokenController-managed secrets

### ISSUE THREAD

**Issue by radeksimko** [kubernetes/kubernetes#51328]
As [documented](https://kubernetes.io/docs/admin/service-accounts-admin/#token-controller), the Token Controller is responsible for automatically creating secrets to allow API access. While this is often useful for the user it may confuse tools which allow users to manage K8S resources. 

More specifically [Terraform K8S provider](https://github.com/terraform-providers/terraform-provider-kubernetes) allows users to [manage Service Account](https://www.terraform.io/docs/providers/kubernetes/r/service_account.html) and define their own secrets for such Service Account. One of the main Terraform's features is to generate a dry-run [plan](https://www.terraform.io/docs/commands/plan.html) (diff between reality and user-defined config).

It would be incredibly helpful when computing such diff if we could reliably tell the difference between a user-defined secret and a TokenController-managed one.

This is why I'm proposing the Token Controller to add an extra annotation to those secrets, e.g.

```
kubernetes.io/service-account.controller-managed-secret: true
```

------

The current solution I implemented doesn't seem very elegant: https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/resource_kubernetes_service_account.go#L85-L106 and I'd be grateful for getting a chance of cleaning it up. 🙂

I'm willing to look into the implementation side of this - but I'm soliciting some feedback on this proposal before diving into code.

-----

/kind feature

/sig api-machinery

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-feature-requests

**Comment by liggitt** [comment]
the type field on the secret object indicates it is a service account token with the value `kubernetes.io/service-account-token`. all service account tokens are managed by the token controller.

**Comment by radeksimko** [comment]
Hi @liggitt 
I think there may be little bit of misunderstanding - let me try to explain the situation with an example below.

The main confusion (at least for me) comes from the fact that anybody can create a custom token and attach it to a service account:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: custom-secret-not-managed
  annotations:
    kubernetes.io/service-account.name: hello-kubernetes
data:
  one: Zmlyc3Q=
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-kubernetes
secrets:
- name: custom-secret-not-managed
---
apiVersion: v1
kind: Pod
metadata:
  name: explorer
spec:
  serviceAccountName: hello-kubernetes
  automountServiceAccountToken: true
  containers:
    - name: explorer
      image: gcr.io/google_containers/explorer:1.0
      args: ["-port=8080"]
      ports:
        - containerPort: 8080
          protocol: TCP
```
```sh
$ kubectl create -f example.yaml
secret "custom-secret-not-managed" created
serviceaccount "hello-kubernetes" created
pod "explorer" created
```
```
$ kubectl get -o=json sa hello-kubernetes | jq .secrets[]
{
  "name": "custom-secret-not-managed"
}
{
  "name": "hello-kubernetes-token-brq4h"
}

$ kubectl get -o=json pod explorer | jq .spec.volumes[]
{
  "name": "hello-kubernetes-token-brq4h",
  "secret": {
    "defaultMode": 420,
    "secretName": "hello-kubernetes-token-brq4h"
  }
}

$ kubectl get -o=json pod explorer | jq .spec.containers[].volumeMounts[]
{
  "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
  "name": "hello-kubernetes-token-brq4h",
  "readOnly": true
}
```

While both secrets (`custom-secret-not-managed` & `hello-kubernetes-token-brq4h`) are deleted along with the associated ServiceAccount, they don't behave the same otherwise.

Specifically only the one created & managed by TokenController (`hello-kubernetes-token-brq4h`) is the one which is mounted as volume to a pod using the Service Account.

----

Are you suggesting that managing service account tokens outside of Token Controller is discouraged pattern and users should _never_ do that? If that's the case then I'm happy to take that as an answer too.
