### ISSUE TITLE
Setting pending initializers to empty in deployment/replicaset/daemonset pod template is ignored in pods

### ISSUE THREAD

**Issue by catherinetcai** [kubernetes/kubernetes#51485]
/kind bug

**What happened**:
I created an initializer that applies to pod resources. Then, I created a deployment, and under the pod template, set pending initializers to an empty array as follows:
```
spec:
  template:
    metadata:
      initializers:
        pending: []
```
The deployment created a replicaset that fails with the following error message: `Error creating: Timeout: request did not complete within allowed duration`.

The pod is created in the uninitialized stage, and examining it shows that that the initializer has been applied to it, so it's completely ignored what was set in the pod template spec on the deployment.

**What you expected to happen**:
The deployment creates a pod successfully, because setting the pending initializers to empty on the metadata allows it to bypass the initializer.

**How to reproduce it (as minimally and precisely as possible)**:
Create an initializer:
```
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: example-initializer
  namespace: default
initializers:
  - name: example.initializer.io
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - v1
        resources:
          - pods
    failurePolicy: "Ignore"
```

Create a deployment with pending initializers set to empty:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: example-app
  name: example-app
spec:
  replicas: 1
  template:
    metadata:
      initializers:
        pending: []
    spec:
      containers:
        - name: example
          image: nginx
```

**Anything else we need to know?**: N/A

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.4
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): 
```PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`): Linux ip-10-12-2-233 4.4.78-k8s #1 SMP Fri Jul 28 01:28:39 UTC 2017 x86_64 GNU/Linux
- Install tools: kops
- Others:
