### ISSUE TITLE
PodSecurityPolicy bypass through ReplicaSets/Deployments/DaemonSets

### ISSUE THREAD

**Issue by gogene** [kubernetes/kubernetes#51529]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When I create a DaemonSet or a Deployment as a unprivileged User or an unprivileged ServiceAccount (RBAC & PodSecurityPolicy) the PodSecurityPolicies are beeing ignored, so it is possible to bypass the PSP to create privileged Pods from DaemonSets, Deployments etc..

**What you expected to happen**:
The creation of the privileged Pods through Deployments, DaemonSets etc. should be denied for unprivileged Users/ServiceAccounts by a Forbidden message.

**How to reproduce it (as minimally and precisely as possible)**:
### PSP ###
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: PodSecurityPolicy
  metadata:
    name: privileged
    namespace: ""
  spec:
    fsGroup:
      rule: RunAsAny
    hostNetwork: true
    hostPID: true
    hostPorts:
    - max: 65535
      min: 1
    privileged: true
    runAsUser:
      rule: RunAsAny
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
    - '*'
- apiVersion: extensions/v1beta1
  kind: PodSecurityPolicy
  metadata:
    name: restricted
    namespace: ""
  spec:
    fsGroup:
      rule: RunAsAny
    runAsUser:
      rule: RunAsAny
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
    - emptyDir
    - secret
    - configMap
kind: List
metadata: {}
resourceVersion: ""
```

### ClusterRole ###
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: restricted-user
rules:
- apiGroups:
  - extensions
  resourceNames:
  - restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use
```

### ClusterRoleBinding ###
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: restricted-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restricted-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user
- namespace: default
  kind: ServiceAccount
  name: default
```

### Test Deployment ###
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-privileged
  labels:
    app: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccount: default
      serviceAccountName: default
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
```

**Anything else we need to know?**:
The restricted PSP works as expected in normal Pod creation by "restricted" users:
"Error from server (Forbidden): error when creating "nginx-priv.yml": pods "nginx" is forbidden: unable to validate against any pod security policy: [spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]"

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.6
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 1409.7.0 (Ladybug)
- Kernel (e.g. `uname -a`): 4.11.11-coreos
- Install tools:
- Others:
