### ISSUE TITLE
audit policy: a policy with 0 rules should return an error, kind and apiVersion now required

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#51565]
/sig auth
/kind bug

If an audit policies is supplied and there are no rules detected, the API server should error.

Over the last release, a change was made so audit policies now require kind and apiVersion fields to be parsed. So the following policy __doesn't work__:

```yaml
# Log all requests at the Metadata level.
rules:
- level: Metadata
```

However this doesn't error, it just spits out:

```
I0829 15:03:48.359580   14374 reader.go:52] Loaded 0 audit policy rules from file /tmp/audit-policy.yaml
```

This should result in an error. Parsing a file with 0 rules should indicate there's some configuration failure.

BTW, the correct audit policy is:

```yaml
kind: Policy
apiVersion: audit.k8s.io/v1beta1
rules:
  - level: Metadata
``` 

We also need to update docs to reflect this new requirement, since kubernetes.io doesn't use "kind" or "apiVersion" for the policy docs.

/cc @sttts @soltysh @CaoShuFeng @tallclair @crassirostris
