### ISSUE TITLE
CronJob.spec.FailedJobsHistoryLimit dosnt work

### ISSUE THREAD

**Issue by imiskolee** [kubernetes/kubernetes#51581]
**Is this a BUG REPORT**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

my yaml

```yaml
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: -----
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 
```

but ,that  successfulJobsHistoryLimit  and failedJobsHistoryLimit not work.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
- Google Cloud Container Engine Beta
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
