### ISSUE TITLE
Pods in replica set not getting created in a federated cluster

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#51591]
Created a federated cluster on AWS using kops as explained at:

https://github.com/arun-gupta/kubernetes-federated-cluster

Deployed a ReplicaSet using the definition: https://github.com/arun-gupta/kubernetes-federated-cluster/blob/master/rs.yml

Expecting 3 pods to be spread on two clusters each but the status does not change:

```
kubectl --context=interstellar get -w rs
NAME       DESIRED   CURRENT   READY     AGE
frontend   6         0         0         15m
```
 
May be related to: https://github.com/kubernetes/kubernetes/issues/51578

/sig federation
/sig aws

**Comment by arun-gupta** [comment]
The command to delete a resource does not return back to prompt:

```
kubectl --context=interstellar delete -f rs.yml
```

**Comment by arun-gupta** [comment]
Created a service definition as:

```
kubectl --context=interstellar create -f svc.yml
```

The definition is at: https://github.com/arun-gupta/kubernetes-federated-cluster/blob/master/svc.yml. External IP is pending even after 5 mins:

```
kubectl --context=interstellar get -w svc
NAME            CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
nginx-service                <pending>     80/TCP    5m
```

**Comment by arun-gupta** [comment]
Creating a Deployment using:

```
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
      - containerPort: 80
```

and getting the error:

```
error: error validating "deployment.yml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
```
