### ISSUE TITLE
Cannot list custom objects defined by CRD with non-conventional pluralization

### ISSUE THREAD

**Issue by ayj** [kubernetes/kubernetes#51639]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

`kubectl get route-rules.config.istio.io` fails and prints "the server doesn't have a resource type "route-rules" in group "config.istio.io" with the following CRD.

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: route-rules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    plural: route-rules
    singular: routerule
  version: v1alpha2
```

**What you expected to happen**:

`kubectl get route-rules.config.istio.io` should return the list of custom objects defined by the `route-rules.config.istio.io` CRD or `No resources found` if no objects have been created yet.

**How to reproduce it (as minimally and precisely as possible)**:

### Non-working example
```
$ cat bad.yaml 
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: route-rules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    plural: route-rules
    singular: routerule
  version: v1alpha2

$ kubectl apply -f bad.yaml 
customresourcedefinition "route-rules.config.istio.io" created

$ kubectl get route-rules.config.istio.io
the server doesn't have a resource type "route-rules" in group "config.istio.io"
```

**Anything else we need to know?**:

The following CRD _does_ work as expected.

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routerules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    plural: routerules
    singular: routerule
  version: v1alpha2

$ kubectl get routerules.config.istio.io
No resources found
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GKE 1.7.3 ALPHA
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ayj** [comment]
/cc @lavalamp, @mandarjog, @kyessenov

ref https://github.com/istio/pilot/issues/1107

**Comment by lavalamp** [comment]
@mbohlool @pwittrock

**Comment by alindeman** [comment]
I poked at this a bit, and I think it may be more of a CLI UI/UX issue.

While the CLI reports `"customresourcedefinition "routerules.config.istio.io" created"`, `kubectl get` looks up based on _kind_ (not singular _or_ plural name).

Specifically, if we change `kind` to something completely arbitrary like `Noodle`:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routerules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: Noodle
    plural: routerules
    singular: routerule
  version: v1alpha2
```

And apply it:

```
$ kubectl apply -f noodle.yml
customresourcedefinition "routerules.config.istio.io" created
```

We get the expected `NotFound` when listing `noodle.config.istio.io` or `noodles.config.istio.io`:

```
$ kubectl get noodle.config.istio.io
Error from server (NotFound): Unable to list "noodles" ...
$ kubectl get noodles.config.istio.io
Error from server (NotFound): Unable to list "noodles" ...
```

```
$ kubectl get routerules.config.istio.io
the server doesn't have a resource type "routerules" in group "config.istio.io"
```
