### ISSUE TITLE
gcloud service of type loadbalancer: on service deletion the forwarding rule is destroyed but the associated target pool is leaked

### ISSUE THREAD

**Issue by davidegrohmann** [kubernetes/kubernetes#51701]
/kind bug

**What happened**:

We configure several services with type load balancer as entry points for connections from the outside world.  On deletion of those services (and actually everything else pods, deployments, and so on) the target pool associated of one of them is constantly leaked and never removed, even though the related forwarding rule is correctly deleted.  There is no obvious difference between the service configuration that could suggest a different behaviour when deleting the service.  The configuration looks like the following:

```
kind: Service
apiVersion: v1
metadata:
  name: APP_NAME-public
spec:
  selector:
    app: APP_NAME
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: APP_NAME
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: APP_NAME
      annotations:
        config-update-trigger: "0"
    spec:
      containers:
        - name: CONTAINER_NAME
          image: IMAGE_ID
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
```

**What you expected to happen**:

The target pools should be correctly deleted and not leaked.

**How to reproduce it (as minimally and precisely as possible)**:

In my case create services as described above and delete them with all other components produces a leak of a target pool.

The delete command looks like the following:

```
kubectl delete daemonsets --all
kubectl delete all --all
gcloud --quiet deployment-manager deployments delete "${deployment}"
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.7
- Cloud provider or hardware configuration**: Google cloud
