### ISSUE TITLE
NetworkPolicy: consider defining empty `from` as "none"

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#51726]
Covered in #51351 comments.

What we SHOULD HAVE DONE, perhaps, is define an empty NetworkPolicyPeer (no podSelector or namespaceSelector or ipBlock) as "none". Perhaps we should do that now, and update docs to say:

Default-deny ingress:

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: foobar
spec:
  policyTypes: [ "Ingress" ]
  ingress:
  - from: [{}]
```

Default-deny egress:

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: foobar
spec:
  policyTypes: [ "Egress" ]
  egress:
  - to: [{}]
```

Default-deny everything:

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: foobar
spec:
  policyTypes: ["Ingress", "Egress" ]
  ingress:
  - from: [{}]
  egress:
  - to: [{}]
```

Why?

1) future rollbacks where a `from` field was newly added will default to fail-closed rather than undefined

2) If we normalize and document this syntax, we have an opportunity in v2 to get rid of the `policyTypes` field and the weird "ingress:[] means deny-all, but ingress:{from:[]} means allow all" semantics.
