### ISSUE TITLE
Feature: Azure Storage Persistent volume can mount to any resource group storage

### ISSUE THREAD

**Issue by marceldempers** [kubernetes/kubernetes#51752]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> kind feature

**What happened**:
Creating an Azure Persistent Volume and PVC to Azure File Share, there is currently a limitation where you can only mount to a storage account that resides in the same resource group as the cluster when kubernetes runs in Azure on container services

**What you expected to happen**:
Can this resource group restriction be lifted ? Allowing a PV to mount to a storage account outside of the resource group of the cluster ?

**How to reproduce it (as minimally and precisely as possible)**:
Create an Azure container services running Kubernetes
Create a storage account in in the same resource group as the cluster
Create a storage account in a different resource group as the cluster.

In Kubernetes, deploy two Persistent volumes, one that points to each of the above created storage accounts.
You will see that the PV fails for the storage account that resides in a different resource group as the cluster 

**Anything else we need to know?**:
I am not sure if this is the correct repo to request the feature enhancement ?
If not, I apologise, please point me in the right direction :)

I mentioned this to Mr @brendandburns and remember he mentioned that the restriction could be lifted.
We're quite keen to use this feature on production for Azure data access to multi-region clusters in H/A data centres and think this "limitation lift" would be extremely beneficial 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
Azure Container Services

**Comment by marceldempers** [comment]
@kubernetes/sig-azure-<group-suffix>

**Comment by marceldempers** [comment]
I tested this on ACS with Kubernetes 1.5. Tried using ACS-Engine and deploying Kubernetes 1.7+ and see this has been addressed in the newer version of Kubernetes so I'll be closing this for now. I can now mount a PV from any resource group in any region. Amazing :+1:

**Comment by jcharlytown** [comment]
@marceldempers, can you elaborate on how you achieved this? According to the kubernetes doc (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#new-azure-disk-storage-class-starting-from-v172) storage accounts are created within the same resource group as the cluster (for "managed" it actually says nothing specific though). However, I can confirm that the storage accounts (initially one premium, one standard) get created in the same resource group.

I deployed the cluster using acs-engine, kubernetes version 1.7.7, storageProfile set to "ManagedDisks".

Thanks!

**Comment by marceldempers** [comment]
@jcharlytown  I'll give you an overview of my issue and how I solved it. We're running a Jenkins container which relies on keeping its configuration on disk. Our Kubernetes cluster lives in a resource group that we consider as "immutable" as we have multiple Kubernetes clusters, when we want to upgrade K8, we simply destroy everything our resource group and add a new K8 installation (all scripted). This means we want our data in another resource group for Jenkins (external from K8). Hope that makes sense ?

So I have a specific resource group for Jenkins data, inside that I have a storage account with an Azure file share. So its not inside the resource group where K8 is.

In my Jenkins YAML manifest I do a simple volume mount:

```
volumeMounts:
            - name: jenkins
              mountPath: /var/jenkins_home
```
And I define a persistent volume claim:

```
volumes:
        - name: jenkins
          persistentVolumeClaim:
            claimName: jenkins-pvc
```

I deploy another YAML manifest that has the persisted volume and claim:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  annotations: 
    pv.beta.kubernetes.io/gid: 1000
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: jenkins-secret
    shareName: jenkins
    readOnly: false
  claimRef:
    name: jenkins-pvc
    namespace: jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

Note that you will need a secret with the storage acc details:

```
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: jenkins
type: Opaque
data:
  azurestorageaccountname: $base64_user
  azurestorageaccountkey: $base64_password
```
Once all is deployed, your PVC should be "green" in the K8 dashboard.
If not, you can see error details by looking at kubernetes controller logs under `kube-system` namespace.

Initial trouble was I was getting a `storage account not found` error in kubernetes controller pod logs, but since I updated to newer version, the issue was solved.
In K8 codebase I could see the fileshare discovery for azure PVC was not searching by resource group so it works now

I hope this helps you :)
