### ISSUE TITLE
[Bug] Kubectl describe shows error for valid YAML

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#51778]
Hi,
We are creating Voyager Ingress TPR object like below:
```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: testingress
  namespace: default
spec:
  backend:
    serviceName: test-server
    servicePort: '80'
  rules:
    - host: test.demo.internal
      http:
        paths:
        - backend:
            serviceName: test-server
            servicePort: '80'
            headerRule:
            - 'X-Forwarded-Host %[base]'
```

`kubectl apply` runs without any error but if I do `kubectl describe ingress.voayger.appscode.com` I see an error like below:
```
Name:		testingress
Namespace:	default
Labels:		<none>
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"voyager.appscode.com/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"testingress","namespace":"default"},"spec":{"backend...
API Version:	voyager.appscode.com/v1beta1
Kind:		Ingress
Metadata:
  Creation Timestamp:	2017-09-01T07:21:26Z
  Resource Version:	1315
  Self Link:		/apis/voyager.appscode.com/v1beta1/namespaces/default/ingresses/testingress
  UID:			2a7c5d8e-8ee6-11e7-a030-080027504fc8
Spec:
  Backend:
    Service Name:	test-server
    Service Port:	80
  Rules:
    Host:	test.demo.internal
    Http:
      Paths:
        Backend:
          Header Rule:
            X-Forwarded-Host %!
(BADINDEX)          Service Name:	test-server
          Service Port:			80
Events:					<none>
```
On the other hand `kubectl get ingress.voyager.appscode.com -o yaml` is working ok.

I tested against minikube 1.7.0 cluster. I see this error with 1.7.x kubectl. I __don't__ see this error with 1.6.2 kubectl .

@kubernetes/sig-cli-bugs
