### ISSUE TITLE
v1.7.4 - Daemonset DESIRED 0 (for node-exporter)

### ISSUE THREAD

**Issue by hartmut-pq** [kubernetes/kubernetes#51785]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
```
NAME            DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE-SELECTOR   AGE
node-exporter   0         0         0         0            0           <none>          43m
```

**What you expected to happen**:
We have 9 nodes running and therefore would expect 
`Desired Number of Nodes Scheduled: 9`

**How to reproduce it (as minimally and precisely as possible)**:
We haven't had time to try to reproduce on a fresh cluster - but we can reproduce by applying the manifest below to our cluster for any namespace incl. `kube-system` with the same result of 0 desired nodes scheduled.

Note: We have 3 other daemonsets which are working just fine - but no noticeable difference to this one.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.4
- Cloud provider or hardware configuration**: AWS via kops

- manifest:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - image:  quay.io/prometheus/node-exporter:v0.14.0
        args:
        - "-collector.procfs=/host/proc"
        - "-collector.sysfs=/host/sys"
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: proc
          readOnly:  true
          mountPath: /host/proc
        - name: sys
          readOnly: true
          mountPath: /host/sys
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
```

Just in case I restarted `kube-controller-manager` pods and deleted/reapplied the manifest. Didn't help.

How could I debug or get any log / information why the daemonset won't be scheduled for our nodes?

**Comment by hartmut-pq** [comment]
I hope @kubernetes/sig-scheduling-bugs is the correct choice?!?

**Comment by hartmut-pq** [comment]
Note: we just upgraded to `v1.7.5` and everything is back healthy - the daemonset adapted smoothly to each new 1.7.5 node joining the cluster.
So unsure if I should close or if anyone would still like to have a look or bring some light into the cause?!?

**Comment by resouer** [comment]
This is no longer a bug, will close it. Feel free to re-open it whenever you encounter same issue again. Thanks!

**Comment by zapman449** [comment]
On my v1.7.10, I can replicate this behavior with `kubectl apply -f file.yaml` with the following:

```
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry-proxy
  namespace: pd-system
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: registry-proxy
      name: registry-proxy
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - name: registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.3
        resources:
          requests:
            cpu: 50m
            memory: 25Mi
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: registry.pd-system.svc.cluster.local
        - name: REGISTRY_PORT
          value: "5000"
        - name: FORWARD_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 5000
          hostPort: 5000
```

If I do `kubectl edit ds registry-proxy` and delete the `last-applied-configuration` annotation, the pods will spawn.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T17:13:44Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T16:31:49Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
