### ISSUE TITLE
NFS volume not mounting and pods are stuck at `ContainerCreating`

### ISSUE THREAD

**Issue by MansoorMajeed** [kubernetes/kubernetes#51853]
I have mounted two directories using subpath from the same pvc, like this.
```
      volumes:
        - name: test-volume-1
          persistentVolumeClaim:
            claimName: nfs
        - name: volume-2
          persistentVolumeClaim:
              claimName: nfs
```

When I'm trying to update a pod, it is stuck at `containercreating` status
```
Events:
  FirstSeen	LastSeen	Count	From						SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----						-------------	--------	------			-------
  16m		16m		1	default-scheduler						Normal		Scheduled		Successfully assigned nginx-3187521063-rgpfh to gke-test1-pool-1-177ee66c-1rjg
  16m		16m		1	kubelet, gke-test1-pool-1-177ee66c-1rjg			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-2n5p7"
  16m		16m		1	kubelet, gke-test1-pool-1-177ee66c-1rjg			Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "nfs"
  14m		39s		7	kubelet, gke-test1-pool-1-177ee66c-1rjg			Warning		FailedMount		Unable to mount volumes for pod "nginx-3187521063-rgpfh_default(c2095448-8fb1-11e7-a71a-42010a80009e)": timeout expired waiting for volumes to attach/mount for pod "default"/"nginx-3187521063-rgpfh". list of unattached/unmounted volumes=[volume-2]
  14m		39s		7	kubelet, gke-test1-pool-1-177ee66c-1rjg			Warning		FailedSync		Error syncing pod
```
