### ISSUE TITLE
NetworkPolicy: NodeSelector for Ingress/Egress rules

### ISSUE THREAD

**Issue by mccormd** [kubernetes/kubernetes#51891]
/kind feature

**What happened**:

When defining NetworkPolicy, could we also have a nodeSelector so that we can define policy for pods/containers which run in the net=host network namespace on certain nodes?  This would allow us to define rules for access from pods such as ingress containers to pods on the nodes that they service.  Whilst it would be possible to set an NetworkCIDR rule it would be hard to support multi-tenant without putting different customers in their own subnets (which would be complex and harder to scale/change).

By being able to define certain nodes by labels we would be able to create rules that target certain kubernetes nodes by label for ingress/egress.

**What you expected to happen**:

nodeSelector matches against node labels and allows us to create a NetworkPolicy with the node ip as the target.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: application
  ingress:
  - from:
    - nodeSelector:
        matchLabels:
          customer: a
    ports:
    - protocol: TCP
      port: 8080
```

The above rule would allow ingress access to pods with label "role: application" from the ipaddresses of nodes matching the label "customer: a".

An alternative to this might be to extend the podSelector mechanism to automatically handle pods running on the host network namespace.

Thanks

**Comment by dixudx** [comment]
> When defining NetworkPolicy, could we also have a nodeSelector so that we can define policy for pods/containers which run in the net=host network namespace on certain nodes?

@mccormd why not add `hostNetwork=true` to podSpec when creating new pods. 

> An alternative to this might be to extend the podSelector mechanism to automatically handle pods running on the host network namespace.

Current k8s does provide an alternative. You can start your own [initializer controller](https://kubernetes.io/docs/admin/extensible-admission-controllers/) to handle such changes automatically, e.g. adding `hostNetwork=true` to podSpec. You only need to append below metadata to your spec. Or create an `initializerconfiguration` for specified `apiGroups`, `apiVersions` and `resources`, then `xxx.yours.initializer` will be appended to the `metadata.initializers.pending` field of newly created resources.

```yaml
metadata:
  initializers:
    pending:
    - name: xxx.yours.initializer
```

While I'm open for adding `NodeSelector` to `NetworkPolicy`.

**Comment by mccormd** [comment]
thanks @dixudx - my issue isn't being able to get to run pods with hostNetwork=true, it's that NetworkPolicy does not work with them.  Ideally, I'd like to be able to create network policy rules for pods such as ingress controllers so we can restrict which pods they are allowed to route to.

**Comment by cmluciano** [comment]
@kubernetes/sig-network-feature-requests 

/assign

**Comment by danwinship** [comment]
>     ingress:
>     - from:
>       - nodeSelector:
>           matchLabels:
>             customer: a

Hm... that feels to me like it says "allow connections from any pod on a node with `customer=a`", not "allow connections from the IP address of any node with `customer=a`"...

I was going to suggest that we could just say that `spec.podSelector` can select `hostNetwork` pods, but that doesn't really work well since it would let you say things like "`hostNetwork` pod A on node X accepts all connections but `hostNetwork` pod B on node X doesn't" which would not be very fun to implement. We probably need to clarify in the docs that NetworkPolicies don't affect `hostNetwork` pods.

**Comment by geekofalltrades** [comment]
I would love some attention on this issue.

We'd like to firewall all of our pods with network policies, but we have custom Kubernetes controller pods that need to talk to the kube-apiserver. kube-apiserver runs as static pods on the master nodes in the host network namespace. This means that in order to write network policy which allows egress to the apiserver, we have to write egress rules that allow egress to the IP address of each master node.

```yaml
  egress:
    - to:
        - ipBlock:
            cidr: 172.20.x.x/32
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 172.20.y.y/32
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 172.20.z.z/32
      ports:
        - protocol: TCP
          port: 443
```

We could alternatively just allow egress to all nodes. That would be less fragile, since we wouldn't be responsible for making sure that the master node IPs are always up-to-date in the network polic. But it's also less secure.

```yaml
  egress:
    - to:
        - ipBlock:
            cidr: 172.20.32.0/19
      ports:
        - protocol: TCP
          port: 443
```
