### ISSUE TITLE
Alternating rolling update order for StatefulSets

### ISSUE THREAD

**Issue by notxcain** [kubernetes/kubernetes#51907]
/kind feature

Currently Kubernetes performs rolling updates for `StatefulSet`s in reverse ordinal order.
There are clustered systems (like [Akka](http://doc.akka.io/docs/akka/2.5/java/cluster-singleton.html)) that keep leaders on the oldest cluster node. 
For such systems it's essential to perform rolling update from youngest to oldest nodes, to avoid unnecessary leader migration.
In Kubernetes this could be achieved by alternating the update order for each consequent rolling update.

What I propose is to add `updateOrder` to `StatefulSet` object definition:
```yaml
spec.updateStrategy:
  type: RollingUpdate
  updateOrder: Alternating # default is ReverseOrdinal
```

Does it make sense, or it would introduce some unwanted state management?
