### ISSUE TITLE
Static IP for Service resource should be configurable "by name" and via annotation

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#51957]
## Problem

For Kubernetes clusters set up with cloud providers, `Ingress` resource allows users to assign a reserved (static) public IP address to the load balancer created, **by name** of the IP resource via an annotation (see Example 1). However, `Service` resource which is very similar can only use static IP address resource by specifying **the value** of IP address in the `loadBalancerIP` field (see Example 2).

This creates an asymmetry (use name in annotation for `Ingress` vs. use IP address in a field for `Service`) and it makes it more difficult to use the `Service` resource. For example, a Kubernetes tutorial can tell user to create an IP resource named `foo-ip` but the user must still update Service manifest file with the _actual_ IP address value to make it work; Ingress doesn't need anything as such.

#### Example 1: Setting up an _Ingress_ with static IP

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "my-test-ip"
    ...
```

#### Example 2: Setting up a _Service_ with static IP

```yaml
apiVersion: v1
kind: Service
spec:
  loadBalancerIP: "YOUR.IPADDRESS.VALUE.HERE"
  ...
```

## Proposal

Introduce an annotation (e.g. `kubernetes.io/service.static-ip-name`) that accepts the name for the IP resource, and therefore does not require the user to specify a `loadBalancerIP` field manually with the actual IP address.

/sig network
/kind bug

-----
<small>(I'm not sure if this is the right repository to open this proposal, if kubernetes/features is a better place to discuss this, I'm happy to move it there.)</small>
