### ISSUE TITLE
Allow to set the image name in deployment defenitions via a config map. 

### ISSUE THREAD

**Issue by Reifier** [kubernetes/kubernetes#51983]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
I can't set the image name in my deployment.yaml via a config map.

**What you expected to happen**:
I expect the image name to be set (just like env variable) from my configMap defenition. 

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-map-testing
  namespace: myspace
data:
  my.image: my-image
---
image:
  valueFrom:
    configMapKeyRef:
      name: my-map-testing
      key: my.image
```
`Error: for field spec.template.spec.containers[0].image, got map;`
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
GCP
- OS (e.g. from /etc/os-release):
GCP cloud
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
