### ISSUE TITLE
Feature: Azure bind existing IP in another resource group to K8 service of type LoadBalancer

### ISSUE THREAD

**Issue by marceldempers** [kubernetes/kubernetes#52129]
Not sure if this is a bug or intended behaviour

**What happened**:
I deploy a kubernetes service pointing to an exiting IP in another resource group

```
spec:
  type: LoadBalancer
  loadBalancerIP: XX.XX.XX.XXX
```
When i do `kubectl get svc my-service` my service is stuck with EXTERNAL-IP in <pending> status.
When I describe service I see it cannot find the IP:

Error creating load balancer (will retry): Failed to create load balancer for service NAMESPACE/my-service: user supplied IP Address XX.XX.XX.XXX was not found

My IP is in another resource group.

**What you expected to happen**:
When i do `kubectl get svc my-service` I expect service to be created with EXTERNAL-IP column populated with my provided IP, however it gets stuck in <PENDING> status

**How to reproduce it (as minimally and precisely as possible)**:

Create Azure ACS cluster with ACS-Engine K8 version 1.7.1
Create Azure Public IP address in another resource group.
Try deploy yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-ns
spec:
  type: LoadBalancer
  loadBalancerIP: XX.XX.XX.XXX
  selector:
    app: some-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```
Wait a couple seconds and try describe:
kubectl describe svc --namespace=my-ns my-service

**Anything else we need to know?**:

**Environment**:
Azure ACS using ACS-Engine
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Might be related to this https://github.com/Azure/ACS/issues/44

Thanks in advance for any information regarding this :)
