### ISSUE TITLE
Multiple matchExpressions in nodeSelectorTerms works unexpectedly

### ISSUE THREAD

**Issue by wzhliang** [kubernetes/kubernetes#52141]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
Having a cluster of 4 nodes, I tried to schedule 2 pods with the following limitation:

```
  spec:
    replicas: 2
    template:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - dev-4
              - matchExpressions:
                - key: test
                  operator: NotIn
                  values:
                  - foo
```

`dev-1` has the `test` label. 
However, the 2 pods are scheduled onto `dev-1` and `dev-4`.

**What you expected to happen**:

As the `matchExpressions` are supposed to be `Anded`, the pods should avoid those 2 nodes.

**How to reproduce it (as minimally and precisely as possible)**:

Create a deployment with two `matchExpressions` that has 
1. different key name and value
2. with `NotIn` operator

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  1.7.2
- Cloud provider or hardware configuration**: bare metal
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): Linux dev-4 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm based
- Others:
