### ISSUE TITLE
No nodes are available that match all of the following predicates:: NodeUnderMemoryPressure (1).

### ISSUE THREAD

**Issue by abitrolly** [kubernetes/kubernetes#52166]
/kind bug
/sig scheduling

**What happened**:
Pod was Pending or in CrashLoopBackOff container state. Not clear why until `kubectl get pod -o yaml` revealed this status:

```
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2017-09-07T11:43:02Z
      message: 'No nodes are available that match all of the following predicates::
        NodeUnderMemoryPressure (1).'
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: BestEffort
```
But the message is confusing.

**What you expected to happen**:
Expected message to say something like "failed to find nodes not under memory pressure. So maybe rename predicate to NodeNotUnderMemoryPressure (1) ?

**How to reproduce it (as minimally and precisely as possible)**:
Run any cluster on machine with limited memory, such as 8Gb.

**Environment**:
- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: minikube
- OS (e.g. from /etc/os-release): Fedora 26
- Kernel (e.g. `uname -a`):  4.12.9-300.fc26.x86_64
- Install tools:
- Others:
