### ISSUE TITLE
kubectl logs is kafkaesque

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#52218]
Seriously, I need it to draw some kind of truth table or something about what's allowed.

Why do we have so many restrictions?

```console
% kc logs -f -nsonobuoy -lsonobuoy-plugin=e2e     
error: only one of follow (-f) or selector (-l) is allowed
See 'kubectl logs -h' for help and examples.

% kc logs -nsonobuoy -lsonobuoy-plugin=e2e    
Error from server (BadRequest): a container name must be specified for pod sonobuoy-e2e-job-533c18a33be34f79, choose one of: [e2e sonobuoy-worker]

% kc logs -nsonobuoy -lsonobuoy-plugin=e2e  -c e2e
error: a container cannot be specified when using a selector (-l)
See 'kubectl logs -h' for help and examples.
# OK, this one is fixed at head
```

And this works just fine, so it really strike me as strange that kubectl won't do it for me.

```console
% kc logs -nsonobuoy -f $(kc get pod -oname -nsonobuoy -lsonobuoy-plugin=e2e)  -c e2e
```

/kind feature
@kubernetes/sig-cli-feature-requests

**Comment by andor44** [comment]
Presumably `-l` and `-c` don't work together because `-l` can match both pods that have a container specified by `-c` and also ones that don't. What do you do in that case? I've been using https://github.com/wercker/stern to augment `kubectl logs` that takes the more liberal approach to matching pods and containers, e.g. it shows all containers in a pod, etc. `kubectl logs` could learn a thing or two from there.

**Comment by dmick** [comment]
me too.  If the resulting containers can't be logged, then error at that point, but if all pods selected by labels have the selected container name, I don't see why they can't be -f'ed.  If that's a problem for some reason, seems like we could at least allow the case of one-pod-match.

**Comment by mcfedr** [comment]
Would be really great if I could use `-f and `-l`, this feels really limiting

**Comment by m1kola** [comment]
I would like to work on this. I'll try to implement combination of `-l` and `-f`. I'll, probably, have a look at `-c` separately to keep PRs simple. As a first step, we will need to fix #67314 (I already submitted a PR for this).

I'm new to the project and I'm working on it in my spare time, so It might take a while for me to fix it. Please, bear with me :)

**Comment by tnsasse** [comment]
+1 for combining -f and -l. For debugging we need to be able to look at logs holistically from all running instances of a pod.

**Comment by gauravagrwl** [comment]
+1 it would be great if -f and -l are combined together.

**Comment by lucasantarella** [comment]
Me as well. This is definitely needed!

**Comment by ramnes** [comment]
I guess this issue can be closed since #67573 just got merged in. :tada:

**Comment by dmick** [comment]
#67573 still doesn't allow -c; please don't close this one

**Comment by ramnes** [comment]
@dmick I'm not sure which MR allowed this, but I can definitely use `-c` with both `-f` and `-l`!

**Comment by m1kola** [comment]
@ramnes @dmick it looks like I *unintentionally* allowed to use `-c` with `-f` and `-l` in #67573, but It will only work if all pods matching a selector provided in `-l` will contain a container with a name specified in `-c`. See the example below, but it's basically how it was described in https://github.com/kubernetes/kubernetes/issues/52218#issuecomment-328510265 and https://github.com/kubernetes/kubernetes/issues/52218#issuecomment-371712704

It's probably not a good idea to rely on this behaviour because it's not documented and there are no tests to cover this.

Do people think that this behaviour is what we want? If so, I'll be happy to add some tests and update help text for `kubectl log` with an example.

---

Example of how kubectl currently (v1.14) works.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logging-test-be
  labels:
    app: logging_test
    kind: be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logging_test
      kind: be
  template:
    metadata:
      labels:
        app: logging_test
        kind: be
    spec:
      containers:
      - name: logging-container-1
        image: logging_test:latest
      - name: logging-container-2
        image: logging_test:latest

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logging-test-fe
  labels:
    app: logging_test
    kind: fe
spec:
  selector:
    matchLabels:
      app: logging_test
      kind: fe
  template:
    metadata:
      labels:
        app: logging_test
        kind: fe
    spec:
      containers:
      - name: logging-container-1
        image: logging_test:latest
```

Assuming that `logging_test:latest` runs something that produces logs. So the following will work:

```
kubectl logs -lapp=logging_test -f -c logging-container-1
```


This:

```
kubectl logs -lapp=logging_test -f -c logging-container-2
```

will not work because the pod `logging-test-fe` doesn't have a container with name `logging-container-2`. It will produce an errors similar to this:

```
error: container logging-container-2 is not valid for pod logging-test-fe-76c4dd7659-9b9ng
```
