### ISSUE TITLE
Unable to access file in the volume populated with data stored in a ConfigMap

### ISSUE THREAD

**Issue by mfaizanse** [kubernetes/kubernetes#52274]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I am working with windows containers. I created a configmap from file using the --from-file flag and then I populate a volume with data stored in a ConfigMap in a pod. The yaml file for this pod is:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ms-datalocation
  name: ms-datalocation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-datalocation
      name: ms-datalocation
    spec:
      containers:
      - name: datalocationmicroservice
        image: _<image path>_
        volumeMounts:
        - name: config-volume
          mountPath: c:/prom
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-kube
      nodeSelector:
        beta.kubernetes.io/os: windows
```

Then I exec powershell into that pod to verify the volume. I can see the file in that volume but I cannot access it. The error was:
![image](https://user-images.githubusercontent.com/9897945/30275775-dba0cdf6-971b-11e7-8e60-d7d7ad3ef425.png)

**What you expected to happen**:
It should print the contents of the file and the file length should not be 0.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a configmap from file.
2. Deploy a windows container in a pod with a volume populated with the config map.
3. Run powershell in the pod.
4. Try to access the file.

**Anything else we need to know?**:

**Environment**:
Kubernetes with windows worker nodes
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
Azure Container Service
- OS (e.g. from /etc/os-release):
Master Node OS: Linux
Worker Nodes OS: Windows Server
- Kernel (e.g. `uname -a`):
Linux Master:
`Linux k8s-master-EAD988D1-0 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:
