### ISSUE TITLE
Grafana can't connect service influxdb datasource

### ISSUE THREAD

**Issue by Maellooou** [kubernetes/kubernetes#52277]
/kind bug
/sig  area/monitoring

**What happened**:

Hello all, 

I try to deploy grafana/influxdb/heapster on my kubernetes 1.6.6 from this offical files  https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-monitoring/influxdb

I have issue link to the service monitoring-influxdb.

My grafana container can't access to service influxdb. I have the following error :

```
2017/09/11 12:44:09 http: proxy error: dial tcp 10.254.231.135:8086: i/o timeout
2017/09/11 12:44:58 http: proxy error: dial tcp 10.254.231.135:8086: i/o timeout
t=2017-09-11T12:44:58+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/query status=502 remote_addr="172.12.96.0, 172.12.96.0" time_ms=30005 size=0 referer=https://10.226.227.238/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/datasources/edit/1
2017/09/11 12:54:15 http: proxy error: dial tcp 10.254.231.135:8086: i/o timeout
t=2017-09-11T12:54:15+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/query status=502 remote_addr="172.12.96.0, 172.12.96.0" time_ms=30003 size=0 referer=https://10.226.227.238/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/datasources/edit/1
```

The ip is well the ip of service monitoring-influxdb.
Here is my pod configuration : 

```
        - image: gcr.io/google_containers/heapster-grafana-amd64:v4.4.3
          name: grafana
          env:
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            # This variable is required to setup templates in Grafana.
            - name: INFLUXDB_SERVICE_URL
              value: http://monitoring-influxdb:8086
              # The following env variables are required to make Grafana accessible via
              # the kubernetes api-server proxy. On production clusters, we recommend
              # removing these env variables, setup auth for grafana, and expose the grafana
              # service using a LoadBalancer or a public IP.
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_SERVER_ROOT_URL
              value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
          volumeMounts:
          - name: grafana-persistent-storage
            mountPath: /var
      volumes:
      - name: influxdb-persistent-storage
        emptyDir: {}
      - name: grafana-persistent-storage
        emptyDir: {}
```

I tested on k8s 1.7.5, and the issue is the same...

On grafana GUI, I have an error on datasource when I try "Save and test" 

![capture d ecran 2017-09-11 a 16 26 11](https://user-images.githubusercontent.com/26655020/30279628-0b1075d6-970e-11e7-89c3-d63ab70c2a95.png)

**What you expected to happen**:

Grafana should be capable to access to influxdb datasource and see metrics on dashboard

**How to reproduce it (as minimally and precisely as possible)**:

Deploy suite heaspter/influxdb/grafana as it is on repository

**Anything else we need to know?**:

**Environment**:
- Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider : Openstack
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux kubemaster 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
