### ISSUE TITLE
Bad mount option when using emptyDir volume plugin with HugePages medium.

### ISSUE THREAD

**Issue by PiotrProkop** [kubernetes/kubernetes#52337]
/kind bug

**What happened**:
When using emptyDir with hugepages medium:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - image: ubuntu
    command:
    - sleep
    - inf
    name: example
    volumeMounts:
    - mountPath: /hugepages
      name: hugepage
    resources:
      requests:
        hugepages-2Mi: 100Mi
      limits:
        hugepages-2Mi: 100Mi
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
```

I got following error in dmesg:
```
hugetlbfs: Bad mount option: "pageSize=2Mi"
```

**What you expected to happen**:
I expected Kubernetes to mount a hugetlbfs backed volume inside pod.

**How to reproduce it (as minimally and precisely as possible)**:
Run above manifest `kube-apiserver` has to be launched with `--feature-gates="HugePages=true"` and k8s node has to have available at least 50 pages of size 2Mi.

**Anything else we need to know?**:

It is caused because there is a typo instead of `pageSize` it should be `pagesize`.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.9.0-alpha.0.525+99b2ee16977b45-dirty`
- Cloud provider or hardware configuration**:  `OpenStack`
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`): `Linux hugepages 4.4.0-57-generic`
