### ISSUE TITLE
Re-run initContainers in a Deployment when containers exit on error

### ISSUE THREAD

**Issue by aisengard** [kubernetes/kubernetes#52345]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**: Container in a Deployment exits on error, container is restarted without first re-running the initContainer. 

**What you expected to happen**: Container in a Deployment exits on error, initContainer is re-run before restarting the container.

**How to reproduce it (as minimally and precisely as possible)**: 

Sample spec:
```
kind: "Deployment"
apiVersion: "extensions/v1beta1"
metadata:
  name: "test"
  labels:
    name: "test"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "test"
  template:
    metadata:
      name: "test"
      labels:
        name: "test"
    spec:
      initContainers:
        - name: sleep
          image: debian:stretch
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - 1s
      containers:
        - name: test
          image: debian:stretch
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - exit 1

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"db809c0eb7d33fac8f54d8735211f2f3a8fc4214", GitTreeState:"clean", BuildDate:"2017-09-11T19:46:47Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"db809c0eb7d33fac8f54d8735211f2f3a8fc4214", GitTreeState:"clean", BuildDate:"2017-09-11T19:46:47Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release): 
```Debian GNU/Linux 9 (stretch)```
- Kernel (e.g. `uname -a`): 
```Linux aleinung 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux```

Implementation Context:

I have an initContainer that waits for a service running in `Kubernetes` to detect its existence via pod annotations, and send it an HTTP request, upon which it writes this value to disk. The main container then reads this value upon startup and "unwraps" it via another service, upon which it stores the unwrapped value in memory. 

The value that is written to disk by the initContainer is a one-time read value, in that once it is used the value is then expired. The problem is that if the main container ever restarts due to fatal error, it loses that unwrapped value and upon startup tries to unwrap the expired value again, leading to an infinite crashing loop until I manually delete the pod, upon which a new pod is created, the initContainer runs, and all is again well. 

I desire a feature that restarts the entire pod upon container error so that this workflow can function properly.

**Comment by hzxuzhonghu** [comment]
Good catch, When use init container to acquire certificate or token, containers may remove it after read to cache. Then containers may re-run repeatedly after once panic.

**Comment by surajssd** [comment]
@aisengard  I think the use-case you are talking about can be simulated by sharing volume between container and init-container, isn't it?

I have updated the config to include volumeMount that is shared between container and init-container.
```yaml
kind: "Deployment"
apiVersion: "extensions/v1beta1"
metadata:
  name: "test"
  labels:
    name: "test"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "test"
  template:
    metadata:
      name: "test"
      labels:
        name: "test"
    spec:
      initContainers:
        - name: sleep
          image: debian:stretch
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - 'echo "create by init-container" > /dir/file'
          volumeMounts:
            - mountPath: /dir
              name: shared
      containers:
        - name: test
          image: debian:stretch
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - "cat /dir/file && sleep 99999s"
          volumeMounts:
            - mountPath: /dir
              name: shared
      volumes:
        - name: shared
          emptyDir: {}
```

running it:

```bash
$ k create -f file.yml 
deployment "test" created
$ k get pods
NAME                    READY     STATUS    RESTARTS   AGE
test-3165636750-b497p   1/1       Running   0          4s
$ k logs test-3165636750-b497p
create by init-container
```
