### ISSUE TITLE
Using taints/tolerations, statefulset volume created in wrong AWS AZ

### ISSUE THREAD

**Issue by xrl** [kubernetes/kubernetes#52357]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

/kind bug

**What happened**: I used Kops to create an instance group of size 3 with node-labels for itsecmon.purpose/itsecmon.role so I could have some dedicated resources for Elasticsearch. I created a statefulset of size 3 set to use those labels. Only 1 of the 3 pods is created, the 2nd is pending because the storage volume has been created in the wrong AZ.

**What you expected to happen**: I expected all 3 pods to be created.

**How to reproduce it (as minimally and precisely as possible)**:

1) Create an instance group with Kops:

```
---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-07-26T21:11:20Z
  labels:
    kops.k8s.io/cluster: kube.town
  name: elasticsearch-master
spec:
  nodeLabels:
    itsecmon.purpose: "elasticsearch"
    itsecmon.role: "master"
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: m4.4xlarge
  maxSize: 3
  minSize: 3
  role: Node
  subnets:
  - us-west-2c
```

Check its metadata with `kubectl get nodes --show-labels`:

```
$ kubectl get nodes --show-labels | grep itsecmon
ip-10-43-91-102.us-west-2.compute.internal   Ready     30m       v1.7.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.4xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2c,itsecmon.purpose=elasticsearch,itsecmon.role=master,kubernetes.io/hostname=ip-10-43-91-102.us-west-2.compute.internal,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-10-43-91-119.us-west-2.compute.internal   Ready     30m       v1.7.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.4xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2c,itsecmon.purpose=elasticsearch,itsecmon.role=master,kubernetes.io/hostname=ip-10-43-91-119.us-west-2.compute.internal,kubernetes.io/role=node,node-role.kubernetes.io/node=
ip-10-43-91-121.us-west-2.compute.internal   Ready     30m       v1.7.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=m4.4xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-west-2,failure-domain.beta.kubernetes.io/zone=us-west-2c,itsecmon.purpose=elasticsearch,itsecmon.role=master,kubernetes.io/hostname=ip-10-43-91-121.us-west-2.compute.internal,kubernetes.io/role=node,node-role.kubernetes.io/node=
```

Then create a statefulset to use the `itsecmon.purpose` and `itsecmon.role`:

```
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-master
  namespace: prod3
spec:
  serviceName: es-master
  replicas: 3
  template:
    metadata:
      labels:
        app: es
        role: es-master
        cluster: prod3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: itsecmon.purpose
                operator: In
                values:
                - elasticsearch
              - key: itsecmon.role
                operator: In
                values:
                - master
      containers:
      - name: es
        imagePullPolicy: Always
        image: 123.dkr.ecr.us-west-2.amazonaws.com/elasticsearch:v5.5.1-alpine
        resources:
          requests:
            memory: "30Gi"
            cpu: "4"
          limits:
            memory: "30Gi"
            cpu: "4"
        ports:
        - containerPort: 9200
          name: restapi
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: datadir
          mountPath: /data
        env:
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms20g -Xmx20g"
        - name: DISCOVERY_SERVICE
          value: es
        - name: CLUSTER_NAME
          value: prod3
        - name: MINIMUM_MASTER_NODES
          value: "3"
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # command: ["sleep", "300000"]
        securityContext:
          privileged: true
          # runAsUser: 105
          # fsGroup: 108
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 40Gi
```

And now wait a bit, see the 2nd pod is pending:

```
(env) LP-XLANGE-OSX:elasticsearch-prod3 xlange$ k --namespace=prod3 describe pod es-master-1
Name:		es-master-1
Namespace:	prod3
Node:		<none>
Labels:		app=es
		cluster=prod3
		controller-revision-hash=es-master-3541045895
		role=es-master
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"prod3","name":"es-master","uid":"8ae64d1a-97f5-11e7-961b-062f5d9a4086","apiVersi...
Status:		Pending
IP:
Created By:	StatefulSet/es-master
Controlled By:	StatefulSet/es-master
Containers:
  es:
    Image:	455567940957.dkr.ecr.us-west-2.amazonaws.com/elasticsearch:v5.5.1-alpine
    Ports:	9200/TCP, 9300/TCP
    Limits:
      cpu:	4
      memory:	30Gi
    Requests:
      cpu:	4
      memory:	30Gi
    Environment:
      NODE_MASTER:		true
      NODE_DATA:		false
      ES_JAVA_OPTS:		-Xms20g -Xmx20g
      DISCOVERY_SERVICE:	es
      CLUSTER_NAME:		prod3
      MINIMUM_MASTER_NODES:	3
      NAMESPACE:		prod3 (v1:metadata.namespace)
    Mounts:
      /data from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7ddfx (ro)
Conditions:
  Type		Status
  PodScheduled 	False
Volumes:
  datadir:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	datadir-es-master-1
    ReadOnly:	false
  default-token-7ddfx:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-7ddfx
    Optional:	false
QoS Class:	Guaranteed
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  3m		3m		2	default-scheduler			Warning		FailedScheduling	PersistentVolumeClaim is not bound: "datadir-es-master-1" (repeated 17 times)
  3m		28s		13	default-scheduler			Warning		FailedScheduling	No nodes are available that match all of the following predicates:: Insufficient cpu (1), Insufficient memory (1), MatchNodeSelector (14), NoVolumeZoneConflict (15), PodToleratesNodeTaints (1).
```

Take a look at the AWS web console I can see that the drive is not in the expected AZ, it's in `us-west-2a`. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T19:06:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**: `kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02`
- OS (e.g. from /etc/os-release):

```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`): `Linux ip-10-43-91-106 4.4.78-k8s #1 SMP Fri Jul 28 01:28:39 UTC 2017 x86_64 GNU/Linux`
- Install tools: Kops
- Others:

**Comment by xrl** [comment]
@kubernetes/sig-storage

**Comment by xrl** [comment]
This is a known problem, but I didn't quite get what the fix would be. Since I know I am using us-west-2c, I can just create dedicated storage classes pinned there. Until this scheduling/storage bug is worked out.

My volumeClaimTemplate for the statefulset:

```
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: aws-us-west-2c-gp2
      resources:
        requests:
          storage: 40Gi
```

Then the storage class:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-us-west-2c-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-west-2c
```

Hope this helps someone.
