### ISSUE TITLE
"No networks found in /etc/cni/net.d" cause master in NotReady status

### ISSUE THREAD

**Issue by justlooks** [kubernetes/kubernetes#52389]
```
[root@k8s-node2 calico]# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
[root@k8s-node2 calico]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@k8s-node2 calico]# rpm -qa|grep kube
kubernetes-cni-0.5.1-0.x86_64
kubelet-1.7.5-0.x86_64
kubeadm-1.7.5-0.x86_64
kubectl-1.7.5-0.x86_64
```
 /kind bug

hi, i build 2-node k8s cluster with kubeadm,and add network plugin "calico" on my cluster
due to kubeadm start etcd on 127.0.0.1:2379 ,calico on another node can not talk with master's etcd ,so i modified the file "/etc/kubernetes/manifests/etcd.yaml" ,it seems calico pods run no problem on cluster,but i find master on NotReady status,and "/etc/cni/net.d" is empty,is it a bug?

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --listen-client-urls=http://127.0.0.1:2379,http://10.161.233.80:2379
    - --advertise-client-urls=http://10.161.233.80:2379
    - --data-dir=/var/lib/etcd
    image: gcr.io/google_containers/etcd-amd64:3.0.17
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2379
        scheme: HTTP
......

```

/var/log/message
```
Sep 13 14:21:38 k8s-node2 kubelet: W0913 14:21:38.198570    2151 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Sep 13 14:21:38 k8s-node2 kubelet: E0913 14:21:38.198848    2151 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Sep 13 14:21:43 k8s-node2 kubelet: W0913 14:21:43.247643    2151 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Sep 13 14:21:43 k8s-node2 kubelet: E0913 14:21:43.247844    2151 kubelet.go:2136] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

```
[root@k8s-node2 calico]# kubectl get node
NAME        STATUS     AGE       VERSION
k8s-node1   Ready      23h       v1.7.5
k8s-node2   NotReady   23h       v1.7.5
[root@k8s-node2 calico]# ls /etc/cni/net.d

[root@k8s-node1 ~]#  ls /etc/cni/net.d
10-calico.conf  calico-kubeconfig  calico-tls

[root@k8s-node2 calico]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                        READY     STATUS    RESTARTS   AGE
kube-system   calico-node-11kvm                           2/2       Running   0          21h
kube-system   calico-policy-controller-1906845835-1nqjj   1/1       Running   0          21h
kube-system   calicoctl                                   1/1       Running   0          21h
kube-system   etcd-k8s-node2                              1/1       Running   1          21h
kube-system   kube-apiserver-k8s-node2                    1/1       Running   1          21h
kube-system   kube-controller-manager-k8s-node2           1/1       Running   2          21h
kube-system   kube-dns-2425271678-2mh46                   3/3       Running   0          23h
kube-system   kube-proxy-qlmbx                            1/1       Running   1          23h
kube-system   kube-proxy-vwh6l                            1/1       Running   0          23h
kube-system   kube-scheduler-k8s-node2                    1/1       Running   2          21h
kube-system   kubernetes-dashboard-2209332821-gnqp5       1/1       Running   0          20h
monitoring    alertmanager-1345290433-h46l8               1/1       Running   0          20h
monitoring    grafana-core-277836579-bqpsg                1/1       Running   0          20h
monitoring    kube-state-metrics-458253108-2d71z          1/1       Running   0          20h
monitoring    kube-state-metrics-458253108-6z6vh          1/1       Running   0          20h
monitoring    node-directory-size-metrics-fc4zk           2/2       Running   0          20h
monitoring    prometheus-core-3823466589-nx8g2            1/1       Running   0          20h
monitoring    prometheus-node-exporter-lt49m              1/1       Running   0          20h
```
