### ISSUE TITLE
Symlink for ca.crt & token files are broken on windows containers 

### ISSUE THREAD

**Issue by mfaizanse** [kubernetes/kubernetes#52419]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I am trying to deploy prometheus on windows container inside a pod. I was getting the error that it cannot read the ca.crt and token files placed by kubernetes at 'C:\var\run\secrets\kubernetes.io\serviceaccount'. Detailed error is:
![image](https://user-images.githubusercontent.com/9897945/30375086-b5b269a2-98a0-11e7-8483-08d92cf2584a.png)

Then I exec powershell inside that pod and further explored the 'C:\var\run\secrets\kubernetes.io\serviceaccount' directory and found that the ca.crt and token files are based on symlink. But if I 'Get-Content ca.crt' then it fails to print the contents of the file giving the following error:
![image](https://user-images.githubusercontent.com/9897945/30375269-5ef55ab0-98a1-11e7-95f2-3aa8c9ab190e.png)

Then I queried the symlink target of ca.crt file using 'Get-ChildItem ca.crt | Format-List' which is '{..data\ca.crt}' 
```
PS C:\var\run\secrets\kubernetes.io\serviceaccount> Get-ChildItem ca.crt | Format-List


    Directory: C:\var\run\secrets\kubernetes.io\serviceaccount



Name           : ca.crt
Length         : 0
CreationTime   : 9/13/2017 8:02:07 AM
LastWriteTime  : 9/13/2017 8:02:07 AM
LastAccessTime : 9/13/2017 8:02:07 AM
Mode           : -a---l
LinkType       : SymbolicLink
Target         : {..data\ca.crt}
VersionInfo    : File:             C:\var\run\secrets\kubernetes.io\serviceaccount\ca.crt
                 InternalName:
                 OriginalFilename:
                 FileVersion:
                 FileDescription:
                 Product:
                 ProductVersion:
                 Debug:            False
                 Patched:          False
                 PreRelease:       False
                 PrivateBuild:     False
                 SpecialBuild:     False
                 Language:

```
But when I cd to the '..data' directory and tried to list the content using dir command, it returned the following error:
```
dir : Could not find a part of the path 'C:\var\run\secrets\kubernetes.io\serviceaccount\..data'.
At line:1 char:1
+ dir
+ ~~~
    + CategoryInfo          : ReadError: (C:\var\run\secr...eaccount\..data:String) [Get-ChildItem], DirectoryNotFoundException
    + FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemCommand

```
But if I cd to the '..9989_13_09_08_02_06.402707801' folder and list the contents using dir, it shows me the ca.crt and token files and I can print the content of these files using Get-Content.
```
PS C:\var\run\secrets\kubernetes.io\serviceaccount> dir


    Directory: C:\var\run\secrets\kubernetes.io\serviceaccount


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        9/13/2017   8:02 AM                ..9989_13_09_08_02_06.402707801
d----l        9/13/2017   8:02 AM                ..data
-a---l        9/13/2017   8:02 AM              0 ca.crt
-a---l        9/13/2017   8:02 AM              0 namespace
-a---l        9/13/2017   8:02 AM              0 token


PS C:\var\run\secrets\kubernetes.io\serviceaccount>
PS C:\var\run\secrets\kubernetes.io\serviceaccount> cd .\..9989_13_09_08_02_06.402707801
PS C:\var\run\secrets\kubernetes.io\serviceaccount\..9989_13_09_08_02_06.402707801> dir


    Directory: C:\var\run\secrets\kubernetes.io\serviceaccount\..9989_13_09_08_02_06.402707801


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/13/2017   8:02 AM           1182 ca.crt
-a----        9/13/2017   8:02 AM              7 namespace
-a----        9/13/2017   8:02 AM            846 token


```

So, it means that there is some issue with the symlinks. Due to this issue I am currently unable to deploy prometheus server.

**What you expected to happen**:
Doing the 'Get-Content ca.crt' in 'C:\var\run\secrets\kubernetes.io\serviceaccount' directory should print the contents of the file. And the file should be accessible to prometheus server.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy a windows container in a pod.
2. Exec powershell in that pod.
3. cd to 'C:\var\run\secrets\kubernetes.io\serviceaccount' directory.
4. Run 'Get-Content ca.crt' 

**Anything else we need to know?**:
**Apart**, I also mounted a kubernetes volume with a windows container and populated this volume with kubernetes configmaps, it placed the file in the volume using symlink as well and the same issue is there as well. The actual file is in the ..9999xxx named directory but the symlink is not working.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
Azure Container Service
- OS (e.g. from /etc/os-release):
Kubernetes with linux master and windows worker nodes.
- Kernel (e.g. `uname -a`):
Linux Master:
`Linux k8s-master-EAD988D1-0 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by mfaizanse** [comment]
/sig azure
/area platform/azure
@colemickens See if this issue is due in azure container service.

**Comment by andyzhangx** [comment]
This is becuase in linux, it's using relative symlink, while in windows, it's using absolute symlink, in linux, it's like following:
`
root@k8s-master-C3EE7EE1-0:/var/lib/kubelet/pods/0ac99e1a-4c29-11e7-bc9e-000d3a35d0d5/volumes/kubernetes.io~secret/default-token-fv1fh# ll
total 4
drwxrwxrwt 3 root root  140 Jun  8 09:01 ./
drwxr-xr-x 3 root root 4096 Jun  8 09:01 ../
drwxr-xr-x 2 root root  100 Jun  8 09:01 ..6986_08_06_09_01_21.807714095/
lrwxrwxrwx 1 root root   13 Jun  8 09:01 ca.crt -> ..data/ca.crt
lrwxrwxrwx 1 root root   31 Jun  8 09:01 ..data -> ..6986_08_06_09_01_21.807714095/
lrwxrwxrwx 1 root root   16 Jun  8 09:01 namespace -> ..data/namespace
lrwxrwxrwx 1 root root   12 Jun  8 09:01 token -> ..data/token
`

So now serect of type "kubernetes.io/service-account-token" is broken in windows now

**Comment by andyzhangx** [comment]
It's related to the docker bug:
Unable to read a symlink in a mounted volume from inside a Windows Container (https://github.com/moby/moby/issues/28401)

**Comment by jdumars** [comment]
@mfaizanse has this been verified as still happening since subsequent releases?  If not, we may want to close this issue.

**Comment by andyzhangx** [comment]
@jdumars @mfaizanse I have just tried on latest Windows 1709, it still does not work. Mounting with relative symlinks does not work well on Windows Conatiner. @PatrickLang for awareness, this is the blocking issue for k8s secrect on Windows.
```
C:\var\run\secrets\kubernetes.io\serviceaccount>dir
 Directory of C:\var\run\secrets\kubernetes.io\serviceaccount
12/22/2017  05:47 AM    <DIR>          .
12/22/2017  05:47 AM    <DIR>          ..
12/22/2017  05:47 AM    <DIR>          ..129812_22_12_05_47_03.093348059
12/22/2017  05:47 AM    <SYMLINKD>     ..data [..129812_22_12_05_47_03.093348059]
12/22/2017  05:47 AM    <SYMLINK>      ca.crt [..data\ca.crt]
12/22/2017  05:47 AM    <SYMLINK>      namespace [..data\namespace]
12/22/2017  05:47 AM    <SYMLINK>      token [..data\token]
               3 File(s)              0 bytes
               4 Dir(s)  14,256,812,032 bytes free

PS C:\var\run\secrets\kubernetes.io\serviceaccount> Get-Content ca.crt
Get-Content : Could not find a part of the path 'C:\var\run\secrets\kubernetes.io\serviceaccount\ca.crt'.
At line:1 char:1
+ Get-Content ca.crt
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\var\run\secr...eaccount\ca.crt:String) [Get-Content], DirectoryNotFoundException
    + FullyQualifiedErrorId : GetContentReaderDirectoryNotFoundError,Microsoft.PowerShell.Commands.GetContentCommand
```

**Comment by CindyXing** [comment]
What's the plan for this bug? We hit the same in our lab. Thanks!

**Comment by PatrickLang** [comment]
I have someone looking into it but need to check back next week on status.

**Comment by alexbrand** [comment]
Adding @bsteciuk and @michmike.

**Comment by bsteciuk** [comment]
Volume mounting secrets is currently a documented known limitation at the moment https://kubernetes.io/docs/getting-started-guides/windows/ .  @PatrickLang glad to hear somebody is looking into it, that's great news!

**Comment by taylorb-microsoft** [comment]
The operating system change @PatrickLang referenced above (MS 14651051) has been fixed and will be included in the next release (Windows Server version 1803), Windows insiders can test that change now!

**Comment by PatrickLang** [comment]
I'm checking if the Windows Server Insider build 17101 has this change

**Comment by andyzhangx** [comment]
Need to mention that volume mount with ConfigMap has same issue

**Comment by dnascimento** [comment]
@PatrickLang  May you confirm if this issue is fixed in Windows 1803?

**Comment by andyzhangx** [comment]
@dnascimento @PatrickLang @mfaizanse @taylorb-microsoft @CindyXing
After trying with latest  windows image `Datacenter-Core-1803-with-Containers-smalldisk` deployed by latest acs-engine, I could confirm that this issue has been fixed.

Thanks all guys for the reporting & fixing work, finally we made it!

```
PS C:\var\run\secrets\kubernetes.io\serviceaccount> dir


    Directory: C:\var\run\secrets\kubernetes.io\serviceaccount


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        5/17/2018   1:02 PM                ..2018_05_17_13_02_31.265180714
d----l        5/17/2018   1:02 PM                ..data
-a---l        5/17/2018  12:41 PM              0 ca.crt
-a---l        5/17/2018  12:41 PM              0 namespace
-a---l        5/17/2018  12:41 PM              0 token


PS C:\var\run\secrets\kubernetes.io\serviceaccount> Get-Content token
eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJ
ZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tbWM0ajUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsuCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjBlMGJjZWIyLTU5Y
```

**Comment by feiskyer** [comment]
> After trying with latest windows image Datacenter-Core-1803-with-Containers-smalldisk deployed by latest acs-engine, I could confirm that this issue has been fixed.

Cool 👍Is there any docker version requirements for the fix?

**Comment by andyzhangx** [comment]
@feiskyer built-in docker version works:
```
PS F:\> docker version
Client:
 Version:       17.06.2-ee-10
 API version:   1.30
 Go version:    go1.8.7
 Git commit:    66261a0
 Built: Fri Apr 27 00:42:30 2018
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-10
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   66261a0
  Built:        Fri Apr 27 00:54:58 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

I will close this issue, just let me know if you have any question, thanks.
/close

**Comment by michmike** [comment]
excellent work everyone at Msft!

**Comment by PatrickLang** [comment]
w00t! 

Tested with Kubernetes v1.10.1, Windows Server version 1803 (build 17134.1)

```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: win-webserver
  name: win-webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: win-webserver
      name: win-webserver
    spec:
      containers:
      - name: windowswebserver
        image: microsoft/windowsservercore:1803
        imagePullPolicy: IfNotPresent
        command:
        - powershell.exe
        - -command
        - "<#code used from https://gist.github.com/wagnerandrade/5424431#> ; $$listener = New-Object System.Net.HttpListener ; $$listener.Prefixes.Add('http://*:80/')
stener.Start() ; $$callerCounts = @{} ; Write-Host('Listening at http://*:80/') ; while ($$listener.IsListening) { ;$$context = $$li       stener.GetContext() ;$$reque
 $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;
 = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$ip=(Get-NetAdapter | Get-NetIpAd
 $$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f
].IPAddress,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer =
.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close(
sponseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ; "
        volumeMounts:
        - name: shh-secrets
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: shh-secrets
        secret:
          secretName: mysecret
      nodeSelector:
        beta.kubernetes.io/os: windows
```


```
$ kubectl -n patrick apply -f secret.yaml
secret "mysecret" created

$ kubectl -n patrick apply -f app-secret.yaml
service "win-webserver" unchanged
deployment.extensions "win-webserver" created

$ kubectl -n patrick get po
NAME                             READY     STATUS              RESTARTS   AGE
win-webserver-56c65b7688-8k9vj   0/1       ContainerCreating   0          9s

$ kubectl -n patrick get po -w
NAME                             READY     STATUS    RESTARTS   AGE
win-webserver-56c65b7688-8k9vj   1/1       Running   0          13s

$ kubectl -n patrick exec -i win-webserver-56c65b7688-8k9vj powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> cd \secrets
cd \secrets
dPS C:\secrets> ir
dir


    Directory: C:\secrets


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        5/18/2018   8:57 PM                ..2018_05_18_20_57_19.24403189
                                                 9
d----l        5/18/2018   8:57 PM                ..data
-a---l        5/18/2018   8:57 PM              0 password
-a---l        5/18/2018   8:57 PM              0 username


PS C:\secrets> cat username
cat username
admin
PS C:\secrets> cat password
cat password
1f2d1e2e67df
```
