### ISSUE TITLE
API server service proxy does not use HTTPS

### ISSUE THREAD

**Issue by floreks** [kubernetes/kubernetes#52490]
**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.5
- Install tools: kubeadm
- OS:  Ubuntu 17.04

**Is this a BUG REPORT or FEATURE REQUEST?**: Possibly a bug
/kind bug
/sig auth

**What happened**:

While trying to access application's HTTPS endpoint through api server service proxy I got an error:
```
Error: 'malformed HTTP response ...
Trying to reach: 'http://<pod-ip>:8443'
```

I'm using simple service:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: some-service
spec:
  selector:
    app: MyApp
  ports:
  - name: http
    port: 80
    targetPort: 9090
  - name: https
    port: 443
    targetPort: 8443
```

Then trying to access `https` port:
`https://<master-ip>:6443/api/v1/namespaces/kube-system/services/some-service:https/proxy`

Is there a way to force it to access `https://<pod-ip>:8443` instead of `http://...`?

**NOTE:** I am able to access my application if I expose it using `NodePort` on `https://<node-ip>:<node-port>`

**Comment by liggitt** [comment]
Use `https://<master-ip>:6443/api/v1/namespaces/kube-system/services/https:some-service:https/proxy`

**Comment by floreks** [comment]
Awesome, thanks! Is it documented somewhere? I think, I have looked through whole k8s official documentation, but did not see that.

**Comment by floreks** [comment]
I guess section `Manually constructing apiserver proxy URLs` in [this](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/) guide should be updated to mention this.

**Comment by floreks** [comment]
@liggitt is it possible to also access https endpoint if it is default and only endpoint of service without name?

```yaml
kind: Service
apiVersion: v1
metadata:
  name: some-service
spec:
  selector:
    app: MyApp
  ports:
  - port: 443
    targetPort: 8443
```
