### ISSUE TITLE
Can't create a resource with imagePullSecrets on apiVersion: extensions/v1beta1

### ISSUE THREAD

**Issue by unixhat** [kubernetes/kubernetes#52530]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
Can't create a resource by yaml file with imagePullSecrets on apiVersion: extensions/v1beta1.

kubectl create -f unixhat.yml
error: error validating "unixhat.yml": error validating data: found invalid field imagePullSecrets for v1.Container; if you choose to ignore these errors, turn validation off with --validate=false

cat unixhat.yml
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: unixhat-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: unixhat
    spec:
      containers:
      - name: unixhat
        image: heriyanto/unixhat
        ports:
        - name: unixhat-port
          containerPort: 80
          hostPort: 80
        volumeMounts:
        - mountPath: /tmp
          name: unixhatvol
        imagePullSecrets:
         - name: regsecret
      volumes:
      - name: unixhatvol
        awsElasticBlockStore:
          volumeID: vol-006d137d3b79b1f3a
```

**What you expected to happen**:
Should be same result with Kind: Pod

**How to reproduce it (as minimally and precisely as possible)**:
Just use apiVersion: extensions/v1beta1 with imagePullSecrets:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:48:59Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}

- Cloud provider or hardware configuration**:
AWS

- OS (e.g. from /etc/os-release):
k8s-1.7-debian-jessie-amd64-hvm-ebs-2017-07-28 (ami-be1ef5c7)

- Install tools:
Kops

**Comment by ncdc** [comment]
@unixhat it looks like you have `imagePullSecrets` indented so that it's part of the `unixhat` container. The `imagePullSecrets` field is actually part of the pod spec, and this is why you're getting this error. If you outdent `imagePullSecrets`, it should work. Like this:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: unixhat-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: unixhat
    spec:
      containers:
      - name: unixhat
        image: heriyanto/unixhat
        ports:
        - name: unixhat-port
          containerPort: 80
          hostPort: 80
        volumeMounts:
        - mountPath: /tmp
          name: unixhatvol
      imagePullSecrets:
       - name: regsecret
      volumes:
      - ...
```
