### ISSUE TITLE
kubernetes 1.8-beta.1  kubelet  nodes is forbidden: User

### ISSUE THREAD

**Issue by jicki** [kubernetes/kubernetes#52711]
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-beta.1", GitCommit:"8c025bc2f23a3be059bf9a7d05867a8cb6f52ea8", GitTreeState:"clean", BuildDate:"2017-09-08T01:23:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-beta.1", GitCommit:"8c025bc2f23a3be059bf9a7d05867a8cb6f52ea8", GitTreeState:"clean", BuildDate:"2017-09-08T01:06:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl get csr
NAME                                                   AGE       REQUESTOR           CONDITION
node-csr-2whynz0prDr_xOvKT_5AReXvJSRs73-wLjAhzr6E02Q   1h        kubelet-bootstrap   Approved,Issued
node-csr-DhurW92EfaP0oIMmJDEDT7U4mqpUQpo5SsoiNQ__j9o   1h        kubelet-bootstrap   Approved,Issued
node-csr-VTMKxnTiaEnO2OTzT4AAVe5dagO7X9drb2RP5R-pjlI   1h        kubelet-bootstrap   Approved,Issued

```

```
kubectl get nodes
No resources found.

```

```
journalctl -f -t kubelet
-- Logs begin at 二 2017-09-19 19:54:59 CST. --
9月 19 17:08:24 k8s-master-25 kubelet[8979]: E0919 17:08:24.982773    8979 eviction_manager.go:238] eviction manager: unexpected err: failed to get node info: node '172.16.1.25' not found
9月 19 17:08:25 k8s-master-25 kubelet[8979]: E0919 17:08:25.396197    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: pods is forbidden: User "system:node:172.16.1.25" cannot list pods at the cluster scope.
9月 19 17:08:25 k8s-master-25 kubelet[8979]: E0919 17:08:25.396923    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:411: Failed to list *v1.Service: services is forbidden: User "system:node:172.16.1.25" cannot list services at the cluster scope.
9月 19 17:08:25 k8s-master-25 kubelet[8979]: E0919 17:08:25.397874    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:420: Failed to list *v1.Node: nodes is forbidden: User "system:node:172.16.1.25" cannot list nodes at the cluster scope.
9月 19 17:08:26 k8s-master-25 kubelet[8979]: E0919 17:08:26.397968    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: pods is forbidden: User "system:node:172.16.1.25" cannot list pods at the cluster scope.
9月 19 17:08:26 k8s-master-25 kubelet[8979]: E0919 17:08:26.398638    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:411: Failed to list *v1.Service: services is forbidden: User "system:node:172.16.1.25" cannot list services at the cluster scope.
9月 19 17:08:26 k8s-master-25 kubelet[8979]: E0919 17:08:26.399732    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:420: Failed to list *v1.Node: nodes is forbidden: User "system:node:172.16.1.25" cannot list nodes at the cluster scope.
9月 19 17:08:26 k8s-master-25 kubelet[8979]: I0919 17:08:26.515129    8979 kubelet_node_status.go:276] Setting node annotation to enable volume controller attach/detach
9月 19 17:08:26 k8s-master-25 kubelet[8979]: I0919 17:08:26.517605    8979 kubelet_node_status.go:83] Attempting to register node 172.16.1.25
9月 19 17:08:26 k8s-master-25 kubelet[8979]: E0919 17:08:26.518896    8979 kubelet_node_status.go:107] Unable to register node "172.16.1.25" with API server: nodes is forbidden: User "system:node:172.16.1.25" cannot create nodes at the cluster scope.
9月 19 17:08:27 k8s-master-25 kubelet[8979]: E0919 17:08:27.399348    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: pods is forbidden: User "system:node:172.16.1.25" cannot list pods at the cluster scope.
9月 19 17:08:27 k8s-master-25 kubelet[8979]: E0919 17:08:27.400363    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:411: Failed to list *v1.Service: services is forbidden: User "system:node:172.16.1.25" cannot list services at the cluster scope.
9月 19 17:08:27 k8s-master-25 kubelet[8979]: E0919 17:08:27.401495    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:420: Failed to list *v1.Node: nodes is forbidden: User "system:node:172.16.1.25" cannot list nodes at the cluster scope.
9月 19 17:08:28 k8s-master-25 kubelet[8979]: E0919 17:08:28.400778    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: pods is forbidden: User "system:node:172.16.1.25" cannot list pods at the cluster scope.
9月 19 17:08:28 k8s-master-25 kubelet[8979]: E0919 17:08:28.401667    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:411: Failed to list *v1.Service: services is forbidden: User "system:node:172.16.1.25" cannot list services at the cluster scope.
9月 19 17:08:28 k8s-master-25 kubelet[8979]: E0919 17:08:28.402810    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:420: Failed to list *v1.Node: nodes is forbidden: User "system:node:172.16.1.25" cannot list nodes at the cluster scope.
9月 19 17:08:29 k8s-master-25 kubelet[8979]: E0919 17:08:29.402208    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: pods is forbidden: User "system:node:172.16.1.25" cannot list pods at the cluster scope.
9月 19 17:08:29 k8s-master-25 kubelet[8979]: E0919 17:08:29.403177    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:411: Failed to list *v1.Service: services is forbidden: User "system:node:172.16.1.25" cannot list services at the cluster scope.
9月 19 17:08:29 k8s-master-25 kubelet[8979]: E0919 17:08:29.404217    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:420: Failed to list *v1.Node: nodes is forbidden: User "system:node:172.16.1.25" cannot list nodes at the cluster scope.
9月 19 17:08:30 k8s-master-25 kubelet[8979]: E0919 17:08:30.403541    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: pods is forbidden: User "system:node:172.16.1.25" cannot list pods at the cluster scope.
9月 19 17:08:30 k8s-master-25 kubelet[8979]: E0919 17:08:30.404556    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:411: Failed to list *v1.Service: services is forbidden: User "system:node:172.16.1.25" cannot list services at the cluster scope.
9月 19 17:08:30 k8s-master-25 kubelet[8979]: E0919 17:08:30.405601    8979 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:420: Failed to list *v1.Node: nodes is forbidden: User "system:node:172.16.1.25" cannot list nodes at the cluster scope.

```

pls help me `!

**Comment by jicki** [comment]
who can help me ~pls~

**Comment by ericchiang** [comment]
@jicki it's unclear how you've configured your kubelet or cluster. Do you have some reproducible steps to create this error condition? It appears that you're using the CSR endpoints but there's no details on how you configured the kubelet. Did you use a tool like kubeadm? Is this issue exclusive to the 1.8 beta or does it also impact 1.7?

**Comment by somejfn** [comment]
@ericchiang I have the same issue bumping the hyperkube version from v1.7.2 to v1.8.0-rc.1.   The 1.7.2 cluster works without issue.  
```
kubelet-wrapper[1551]: E0928 00:55:37.516523    1551 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: pods is forbidden: User "system:nodes" cannot list pods at the cluster scope
```
My setup is a nested k8s control plane (K8sOnK8s) you can find manifest here: https://github.com/somejfn/k8s-on-k8s

**Comment by liggitt** [comment]
are you starting with a clean etcd store or upgrading an existing cluster that previously ran 1.7.x?

what authorization mode are you using in your cluster?

if you are using RBAC, starting in 1.8, you must either enable the `Node` authorizer mode as well, *or* grant the `system:node` role to your nodes yourself. See the release note associated with https://github.com/kubernetes/kubernetes/pull/49638

**Comment by somejfn** [comment]
Thanks @liggitt.  This must be the problem.  The cluster is setup with a fresh etcd cluster.    Now I did a quick test changing the APIserver to `--authorization-mode=Node,RBAC` and I get the same error.... do I need to create a CRB for the _system:nodes_ group on top of that ?  Im not up 2 speed on how to use the new Node authorizer.

**Comment by liggitt** [comment]
there's more info at https://kubernetes.io/docs/admin/authorization/node/

to be authorized by the node authorizer, your node credentials should have group `system:nodes` and username `system:node:<nodeName>`

**Comment by somejfn** [comment]
Will do my homework.  Thanks again !

**Comment by KeithTt** [comment]
hi, @liggitt how to modify the `node credentials` and add the customized username the `system:nodes` group?

**Comment by liggitt** [comment]
Node credentials are passed to the node in the --kubeconfig file. Typically it should reference an x509 client cert with CN=system:node:$NODE_NAME and O=system:nodes

**Comment by KeithTt** [comment]
Resoved by creating a CRB, and approved the csr.

```
# kubectl get no --show-labels
NAME      STATUS    ROLES     AGE       VERSION   LABELS
uy05-13   Ready     master    12h       v1.8.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=uy05-13,node-role.kubernetes.io/master=
uy08-07   Ready     master    9h        v1.8.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=uy08-07,node-role.kubernetes.io/master=
uy08-08   Ready     node      12h       v1.8.2    beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/hostname=uy08-08,node-role.kubernetes.io/node=
```

**Comment by KeithTt** [comment]
@liggitt if I generate the cert for another master or node manually:

```
openssl genrsa -out kubelet.key 2048
openssl req -new -key kubelet.key -out kubelet.csr -subj "/O=system:nodes/CN=system:node:$(hostname)" -config kubelet-openssl.cnf
openssl x509 -req -set_serial $(date +%s%N) -in kubelet.csr -CA ca.crt -CAkey ca.key -out kubelet.crt -days 365 -extensions v3_req -extfile kubelet-openssl.cnf
```

then, should I add reference the cert like this:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFM01URXhPREEyTURJME1Wb1hEVEkzTVRFeE5qQTJNREkwTVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkI4Cjk2aW5KZStNKzliZktDcm4rM1pvTUlHY1JyZWFQMGRkeUVIYWdSZzZ3TTRPZTFTdFB1NjliVGZQOWdJMlhqcXkKTXdWT1NiaW9GWXQ1SDdFeXJqZ3RpRE9vVFJOekRGSXR6NDZEajk4SkZrZnkybWNKWTV0SXdESTMxenhCRG53TgpITmxBdHJzREcvbUJRZzYxVkl6MTgybitib1dOOEpqWTkyOTUxSGZJamNsQXBxUzRSRDJFRWsxWkUrVjhkUjBVCmwyTXRSSE43b3dLRlFoOVlENWJFZTJXc3lSV21RektkK21KaEhlekhZQUJtRVlmQTA0WEwrYmFPQmVwWnV2ZUwKS2M0TjZ4MlJIR3dwS3JOVkNaV09LWWpiNVlRODk5c0pEQ2hNYmZRL0lNUFQ0dklWaitsMVkzRTVMdU12Q3lHTAoxVzJuMUphTE44YWF6R1NTMEpVQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHTmVOKzVXYy9DT1dIUkZWK2dadU1EajhJU3kKaU8xbU9BUXhnL3ZIalZXZjRnTmw4aVBOSVpUckw2cC9Wb2NiK0Z5UzdDVThScXZKTTRmaGFMRC95ZXJIU2ZaeAorNDJjN015aERlU3llVlRoN2lpN1IrYVk3TXlNem9MNXFKZzNxYitRV2dTQzlGQkcrT1BEUk9CMlVWcExNUlBRCm1mT21CYnZPRVVjd2R5NVNZMVRRMGlKZE1xUHJKMFFxY3ZRZEdHeHE1Y3Z0ZlpjejVCaGNZUGF4SHpCWjdiWUsKQ0hZNU50SGM2V2ZtMUFxbzF6VVd5RG1sYzFMT2VqaGJKS1Z0RXZJOG1OQkdudXhhdGEzZGsvTXBDc0ExSzJFTgo0eEY5WG5tdm05eXU5WDU3RGoyaUNLMElCZmtnUEF3NFJzR1oxL1F2WTRYT3k4VG1PZ3c5Tm1QUTZ3OD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.5.42:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:node:uy05-13
  name: system:node:uy05-13@kubernetes
current-context: system:node:uy05-13@kubernetes
kind: Config
preferences: {}
users:
- name: system:node:uy05-13
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4ekNDQWR1Z0F3SUJBZ0lJVXRJK2ZmdlJTbE13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB4TnpFeE1UZ3dOakF5TkRGYUZ3MHhPREV4TVRnd05qQXlORFZhTURVeApGVEFUQmdOVkJBb1RESE41YzNSbGJUcHViMlJsY3pFY01Cb0dBMVVFQXhNVGMzbHpkR1Z0T201dlpHVTZkWGt3Ck5TMHhNekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMNHBvRjRHOUpua2RiLzkKZTJOYTFiem1Mc2FER2E5L05ySWlzR1N4akpldHI1SVhKN3lEWlBFTUN2UTJoMzR4VGMrdjhKcDZPZm9LNUNpMgpFRHZEMVc3aHB6RytjbjNlKzIvZEovN1A3QUdsUDZnbFo0NGN5VzRNN1V1NlRXdTU4RlB2bjlhNlRNTjVxNjNICnZMMkhrZHJ2dHNISS9xK2NnYjZOSlVtQ0FxQU1vRjd6RHlrWjcyb0hvTUw5WTNhS25WWlJ4Z2dWOFIzQ1A2NGIKdEV4c3hXZ2JiWlJra2UraE1GakRyVGpJSDN1M0hKNWZlTGwrMTJCVjB3d3JzVTRpRllwNHFTVEtLbXBFNFlVawowZnhRRjJuKzd6bmlSbnFBUnBXUnQ2cDU3bS93MDhRZ2Zuc2RrNmN5YUo3T0t5Z3Q0OFlMVEhFSDlaRXN3eTdMClphVWlMMHNDQXdFQUFhTW5NQ1V3RGdZRFZSMFBBUUgvQkFRREFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUYKQndNQ01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQW5mN3JKeEwvWDhlTUNiUHZKNzdmU011N3NtS0xIUCsrRwpnN21xdzI0VHhPSm5XeEFFbnN2T3drSWU2VzdKejBVOW1jaVV2OVJDYnB3M05LT2hLa0Q2dXR4bnB5Ylg5TE1EClpSWTBPYWJOZ3Jxdm9VM0VITm5VNnlsWGIzdHkxTVBsU3QzN201b1poTUJSNGc0ZURPVTI4dEJ5dWtvV1MrRzgKcXd0RjQwYk9EeWMzM0ErdmpuNmlHYXpPV3F5bUpUc2haczg1YU5OOFZKaTJ2ZCtmVlh0VWdnNFpaTjZJUGtmcQpwazViUTZaZjBzNXVOZks4VE9nMlE4aThHclJhNllCR2trUkxORlJrQmIrK3RQRzJHRGV0ejFBZXdpVDQ5WXJ6ClE2U3BTUE1EMmJMRVU5V01XQmoyZUdaUzdzRmxmY3l6eEhZTStVL2VwTndJL0pMcElYbysKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdmltZ1hnYjBtZVIxdi8xN1kxclZ2T1l1eG9NWnIzODJzaUt3WkxHTWw2MnZraGNuCnZJTms4UXdLOURhSGZqRk56Ni93bW5vNStncmtLTFlRTzhQVmJ1R25NYjV5ZmQ3N2I5MG4vcy9zQWFVL3FDVm4Kamh6SmJnenRTN3BOYTdud1UrK2YxcnBNdzNtcnJjZTh2WWVSMnUrMndjaityNXlCdm8wbFNZSUNvQXlnWHZNUApLUm52YWdlZ3d2MWpkb3FkVmxIR0NCWHhIY0kvcmh1MFRHekZhQnR0bEdTUjc2RXdXTU90T01nZmU3Y2NubDk0CnVYN1hZRlhUREN1eFRpSVZpbmlwSk1vcWFrVGhoU1RSL0ZBWGFmN3ZPZUpHZW9CR2xaRzNxbm51Yi9EVHhDQisKZXgyVHB6Sm9uczRyS0MzanhndE1jUWYxa1N6RExzdGxwU0l2U3dJREFRQUJBb0lCQUR2dmdzd2dCUmc4R2FEWgprL3BNdHZGQzI1dFYxdEtwbGVPdmEwbFJiSzZoMzZSOEI5b3l6NjNwemNvTEpjbHdZTVlFL2lDeVJYTzUydys1CjBvUUR4VkdkYmNVUDhhWWFrY1ZBUDByZzNkSG04NWxic0xmcCt0TGs0Q1h1SWxqQjBpMmlhUTZVeVgwUzdEbHAKcXVOUngzYnA5d0E5Q1lqd0d6U2o2QXl6SFlDejdrYVc4M0pWVW90Q2xaWlBDWGM1L3JZWHN3clpHZUMxUUV5SApheTlrcG5pSHNkd2lBUVVDQ2lQakZ6QVRkaTNZRXBocmZzSjlxNXMxY3EwSThPZVpWOWtFOHBIWms1NTA5VjlQCklnblVha2puUldTSEVFdGVRTldUdjJEMjdvQU9pbU82d0IvQ013TTJwYVBQWk5yMzR2eFZaK2o3b1hrZG1HR3gKdE44d0VRRUNnWUVBOUgzcVdsNU5EMnozZDhnMDVUR2hJcko1c3hQRXc1UUZLV2lGV29XY1dETWpqYThTL2IxNQpEN2N2UWs3ZzJrOG9tZVJDVHUvdXdNUjR6YWVXaGNaMTRVSTIzV3N3NHpzdGxLNWVNRG5yVnlvZ1ZNR3BXZVpLCk5CZXg4RFAxRnVZdkxBNjdhSFlKWStMWktDTjc4M21ZTTNEZzBoZTJhZjh6QzhpS24rb2dkWU1DZ1lFQXh4ME4KaWdzalJZSkJJUEFFbEdhVVZpY0pWaVVsUzhGNGR0SGltVmhkaW1RdmQ0dHhWMjR6MW1VaVFwN1F5UVpPcDJmWQpRL3pFZGthVlE2Q0Z1bjZmVW1UWjhZUG9oMVVPdWRsTVJFQTdRWkpYWXYrenpzM3U3bHE0RHYxSUs0ZHA0UHpxCmZjdncyd2NOL081My9CQ1ZVVXZ3dUtJL1h1VVNydUdxbEwyRi9Ka0NnWUFpTksraC93bUcrL2JQY2xvOEtxcGgKb1ZpM2ZpK01NVnhiZzcwTWdoN3lsQTBJV0pNdW51Q2VHMEhvWkFLL2FFM0U0aE9JMmJhc2o1QmJMWFE0dVNCcQo2SW1taHNXck5POVdtdUtnbXFuYll4QnM2ejlYVFluYUtlcUNNYks3aG03WkdpS01KZCtBY3c5d3R5NHpUVExICkY2Yk1uZmF1Yzc3Zmlpb2kzMjIxSXdLQmdGTDRRMFVMb1JYODBnRFVvMFBuZnRacmk5TnV4UnpOTU5KcVlUOCsKK0RPTHpjL0Z0bVFWVXRwNjZBelV1dkdaaERyejVjVm0xY0xuWkpsNmtWOEdGb094N0xOY0lSQUxuSWhMQ1NIRApsaTJidW5oUlR1N1ZGMFFSWDNNM2pkUTlxQndOcC9UbGY2YjFTSm5tRU85alJhVkx2TEpqUVg3Y2U2Mk44WlByCmFhSzVBb0dCQUsxei9xMWFoVlM2ZmF5SHJoQi9zZ2NscnJqVFZtMWlwWUFKMUlrand3U2JKRlM3OVlQL3NLK0wKRmt3by9zMXh4bTlpZi85VTE2VU5hQ2NlVWhpcXZ1cXVZd3ZqS1Fvby9Ua004WEEvcWllcGFib0hqbjR4emRJYgpyNEZQRkdmQ2xWUzVVU0V2T1JHUnNjZElhYkwwdkRxRmZ4WlJGS21iK3pjYklXRU9HeHpICi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

- name: system:node:uy08-07
  user:
    client-certificate-date: $(cat kubelet.crt| base64 -w 0)
    client-key-data: $(cat kubelet.key| base64 -w 0)
```
