### ISSUE TITLE
Feature: Support using environment variables inside deployment yaml file

### ISSUE THREAD

**Issue by mahdix** [kubernetes/kubernetes#52787]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

/kind feature

**What happened**: When you write a deployment yaml file, everything must be specified statically. In cases where something is not specified at time of writing, the only choice is using a 3rd-party tool and use yaml file as a template which will later be processed by the tool to replace some markers with actual values. This is not efficient.

**What you expected to happen**: Deployment yaml file format should support some kind of marker which specifies values which will be provided at the time of deployment via command line arguments (e.g. `kubectl create -f myfile.ymml --var1=DATA --var2=gcr.io/image121212`) or feed values from environment variables.

**How to reproduce it (as minimally and precisely as possible)**:
Example (just a suggestion, actual implementation could be different):
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      # unlike pod-nginx.yaml, the name is not included in the meta data as a unique name is
      # generated from the deployment name
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{IMAGE_URL}}
        ports:
        - containerPort: 80
```
Then run: `kubectl create -f file.yaml --IMAGE_URL=nginx.1.9`

**Anything else we need to know?**: This will make life easier for DevOps.

**Environment**:
- Kubernetes version (use `kubectl version`): Latest
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): OS X
- Kernel (e.g. `uname -a`): Darwin
- Install tools:
- Others:

**Comment by mahdix** [comment]
@kubernetes/sig-cli-feature-request

**Comment by resouer** [comment]
I am not sure about this. Sounds more like a PaaS layer feature to me ...

**Comment by zjj2wry** [comment]
@mahdix `kubectl create command` now just add image, because we want it enough simple. but now 1.8 support `kubectl set env command`. you can use `kubectl create deploy a --image=xxx --dry-run -o yaml | kubectl set env --local -f - 'env=prod' -o yaml `. hope this can help you

**Comment by fengh0409** [comment]
Hey, I like this feature,and I had met this situation actually.How is this going?

**Comment by hex0cter** [comment]
I would absolutely love it.

**Comment by kminehart** [comment]
Nobody has mentioned `envsubst`.

For a small project I put everything in a folder, `kubernetes/`.

Anything ending in `.yaml` is ignored, and anything ending in `.tmpl` is 

```
###############################################################################
# Build Kubernetes yaml files
###############################################################################
BUILD_DIR = ./bin
K8S_DIR = ./kubernetes
K8S_TMPL := $(notdir $(wildcard $(K8S_DIR)/*.tmpl))
build_yaml:
ifneq ("","$(wildcard $(K8S_DIR))")
	@mkdir -p $(BUILD_DIR)/kubernetes
	@cp $(K8S_DIR)/*.yaml $(BUILD_DIR)/kubernetes
	$(info $(M) building yaml...)
	for tmpl in $(K8S_TMPL); do \
		VERSION=$(VERSION) envsubst < $(K8S_DIR)/$$tmpl > $(BUILD_DIR)/kubernetes/"$${tmpl/.tmpl/}" ; \
	done
endif

deploy: build_yaml
ifneq ("","$(wildcard $(K8S_DIR))")
	$(info $(M) deploy...)
	kubectl apply -f $(BUILD_DIR)/kubernetes
endif
```

And in my `deployment.yaml.tmpl`:

```
        image: example/image:${VERSION}
```

**Comment by daniel-kun** [comment]
I face a similar problem with yaml template files that include CPU architecture, such as amd64. I often had to change those manually to arm when deploying on a raspberry pi for testing purposes. One popular example is metrics-server, where amd64 is hard-coded in the yaml:
https://github.com/kubernetes-incubator/metrics-server/blob/master/deploy/metrics-server-deployment.yaml

**Comment by kminehart** [comment]
@daniel-kun I'm going to assume that you're using Go, but i guess that doesn't have to be true for this to work.

`envsubst` is a great tool here, especially since you're already compiling your code using `$GOOS` if you're using Go.

Template:

```
apiVersion: extensions/v1beta1
kind: Deployment
# ...
    architecture: ${GOOS}
```

```
GOOS=amd64 envsubst < mytemplate.tmpl > mydeployment.yaml
```

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
# ...
    architecture: amd64
```

I think there are plenty of tools available for this; it doesn't have to be embedded into `kubectl`. :)
