### ISSUE TITLE
Projected volumes should handle `path` for all items projected

### ISSUE THREAD

**Issue by rocketraman** [kubernetes/kubernetes#52847]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

Projected volumes are very useful for combining config and secrets. However, a basic use case is missing. I have a secret that contains many items in it e.g. database name -> password mappings, which change frequently.

I have a config which contains only one item (a file).

I want to project these into a directory structure like this:

```
config                                                                                                                                                                                                                             
├── app-config.json
└── credentials
    ├── db1
    └── db2
    └── ...
    └── dbn
```

Currently, in order to produce this structure, the projected volume needs to define every single item in the credentials list, which is hard to maintain and means the container has to be updated every time this list changes:

```
      volumes:
      - name: config
        projected:
          sources:
          - secret:
              name: db-credentials
              items:
                - key: db1
                  path: credentials/db1
                - key: db2
                  path: credentials/db2
                [...]
                - key: dbn
                  path: credentials/dbn
          - configMap:
              name: app-config
```

A simple solution would be to allow specification of `path` at the `secret` level to avoid having to list every item, and have every secret named be handled within that path, which would be consistent behavior with a direct secret volume mount:

```
      volumes:
      - name: config
        projected:
          sources:
          - secret:
              name: db-credentials
              path: credentials
          - configMap:
              name: app-config
```

I believe the same concept could apply to other projected items like configmaps and downward API items, but I have not considered those extensively.

**Anything else we need to know?**: No

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.5
