### ISSUE TITLE
use ingress proxy the kibana

### ISSUE THREAD

**Issue by kuops** [kubernetes/kubernetes#52850]
env
```
kubernets: 1.7.6
install method: kubeadm
```
ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: kube-system
  name: kube-system-ingress
spec:
  rules:
  - host: kibana.k8s.com
    http:
      paths:
      - backend:
          serviceName: kibana-logging
          servicePort: 5601
  - host: grafana.k8s.com
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
  - host: dashboard.k8s.com
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 80
```
grafana change the env `GF_SERVER_ROOT_URL`  can access

the kibana change SERVER_BASEPATH pod logs have error
```
 env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging:9200
          - name: SERVER_BASEPATH
            value: /
            #value: /api/v1/proxy/namespaces/kube-system/services/kibana-logging
          - name: XPACK_MONITORING_ENABLED
            value: "false"
          - name: XPACK_SECURITY_ENABLED
            value: "false"
```
log error
```
FATAL { ValidationError: child "server" fails because [child "basePath" fails because ["basePath" with value "&#x2f;" fails to match the start with a slash, don't end with one pattern]]
    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:181:19)
    at _validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:651:31)
    at root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:121:23)
    at Config._commit (/usr/share/kibana/src/server/config/config.js:114:35)
    at Config.set (/usr/share/kibana/src/server/config/config.js:84:10)
    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:57:10)
    at _lodash2.default.each.child (/usr/share/kibana/src/server/config/config.js:46:14)
    at arrayEach (/usr/share/kibana/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/share/kibana/node_modules/lodash/index.js:3345:13)
    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:45:31)
    at new Config (/usr/share/kibana/src/server/config/config.js:36:10)
    at Function.withDefaultSchema (/usr/share/kibana/src/server/config/config.js:29:12)
    at KbnServer.module.exports (/usr/share/kibana/src/server/config/setup.js:13:39)
    at /usr/share/kibana/src/server/kbn_server.js:156:20
    at next (native)
    at step (/usr/share/kibana/src/server/kbn_server.js:77:191)
  isJoi: true,
  name: 'ValidationError',
  details: 
   [ { message: '"basePath" with value "&#x2f;" fails to match the start with a slash, don\'t end with one pattern',
       path: 'server.basePath',
       type: 'string.regex.name',
       context: [Object] } ],
  _object: 
   { pkg: 
      { version: '5.5.1',
        branch: '5.x',
        buildNum: 15405,
        buildSha: '32ff80dbccdff23911015425bfaf4ae32ea0c0c1' },
     dev: { basePathProxyTarget: 5603 },
     pid: { exclusive: false },
     cpu: { cgroup: [Object] },
     cpuacct: { cgroup: [Object] },
     server: { name: 'kibana', host: '0', basePath: '/' } },
  annotate: [Function] }
```
if dont  modify the SERVER_BASEPATH ，the ingress rewrite to the 
```
http://kibana.k8s.com:30080/api/v1/proxy/namespaces/kube-system/services/kibana-logging/app/kibana
```
