### ISSUE TITLE
Useful labels missing from Prometheus node_exporter in 1.7.x

### ISSUE THREAD

**Issue by ericuldall** [kubernetes/kubernetes#52858]
/kind bug

**What happened**: I upgraded my GKE cluster to 1.7.x and lost a bunch of helpful labels from the prometheus node_exporter

**What you expected to happen**: I expected my metrics to continue working as before

**How to reproduce it (as minimally and precisely as possible)**:
Install prometheus node_exporter on GKE 1.7.x cluster and query for node_cpu

**Here's how the data looked before update:**
```
node_cpu{beta_kubernetes_io_arch="amd64",beta_kubernetes_io_instance_type="n1-standard-2",beta_kubernetes_io_os="linux",cloud_google_com_gke_nodepool="default-pool",cpu="cpu1",failure_domain_beta_kubernetes_io_region="europe-west1",failure_domain_beta_kubernetes_io_zone="europe-west1-b",instance="my-cluster-default-pool-3cbb3136-22jh",job="kubernetes-node-exporter",kubernetes_io_hostname="my-cluster-default-pool-3cbb3136-22jh",mode="system"}
```

**Here's how the data looks after update:**
```
node_cpu{app="node-exporter",cpu="cpu1",instance="10.128.0.25:9100",job="kubernetes-service-endpoints",kubernetes_name="node-exporter",mode="system",name="node-exporter"}
```

**Environment**:
- Kubernetes version: 1.7.5
- Cloud provider or hardware configuration**: Google Cloud (GCE)

**Reference to issue on  prometheus github (closed):** https://github.com/prometheus/node_exporter/issues/678

**Comment by frodenas** [comment]
@ericuldall Those labels came from the [Prometheus Kubernetes Service Discovery](https://prometheus.io/docs/operating/configuration/#<kubernetes_sd_config>) and added to the metrics using [relabelling](https://prometheus.io/docs/operating/configuration/#<relabel_config>) via a `labelmap` action. Have you tried opening an issue at the [prometheus github repo](https://github.com/prometheus/prometheus)?

**Comment by ericuldall** [comment]
Yes. I posted the reference to an issue they closed at the bottom of my initial comment.

**Comment by frodenas** [comment]
That issue was for the [node_exporter github repo](https://github.com/prometheus/node_exporter). I believe the [prometheus github repo](https://github.com/prometheus/prometheus) has different maintainers.

**Comment by ericuldall** [comment]
I'll certainly open an issue there and see if they have more insight.

**Comment by MarcoGlauser** [comment]
@ericuldall did you find a solution to this? It would be very nice to get the node poll with the node_cpu metric.

**Comment by ericuldall** [comment]
@MarcoGlauser I haven't yet addressed this in our stack. The prometheus metrics, while useful, are not my highest priority :( I think there may have been some good suggestions in the other tickets I opened, which ultimately ended me here: https://groups.google.com/forum/#!topic/prometheus-users/2njYh6SucJ8

**Comment by MarcoGlauser** [comment]
I think this is related to the problem encountered here https://github.com/prometheus/prometheus/issues/2916. 
I replaced the "kubernetes-service-endpoints" scraping job with this one:
```yaml
      - job_name: 'kubernetes-node-exporter'

        # Default to scraping over https. If required, just disable this or change to
        # `http`.
        scheme: https

        # This TLS & bearer token file config is used to connect to the actual scrape
        # endpoints for cluster components. This is separate to discovery auth
        # configuration because discovery & scraping are two separate concerns in
        # Prometheus. The discovery auth config is automatic if Prometheus runs inside
        # the cluster. Otherwise, more config options have to be provided within the
        # <kubernetes_sd_config>.
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          # If your node certificates are self-signed or use a different CA to the
          # master CA, then disable certificate verification below. Note that
          # certificate verification is an integral part of a secure infrastructure
          # so this should only be disabled in a controlled environment. You can
          # disable certificate verification by uncommenting the line below.
          #
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
          - role: node

        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}:9100/proxy/metrics
```
The key is to add the port 9100 on this line `replacement: /api/v1/nodes/${1}:9100/proxy/metrics`. This way the scaper scrapes from the kubernetes api and also gets the meta information.
YMMV but since the GKE labels are more important than the other labels, this works for me.
