### ISSUE TITLE
kubectl set resource can not update multi resource in local

### ISSUE THREAD

**Issue by zjj2wry** [kubernetes/kubernetes#52994]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
my yaml:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: first-rc
spec:
  replicas: 1
  selector:
    app: mock
  template:
    metadata:
      labels:
        app: mock
    spec:
      containers:
      - name: mock-container
        image: gcr.io/google-containers/pause:2.0
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: second-rc
spec:
  replicas: 1
  selector:
    app: mock
  template:
    metadata:
      labels:
        app: mock
    spec:
      containers:
      - name: mock-container
        image: gcr.io/google-containers/pause:2.0
```
exec kubectl set resources command,just update first object:
```
admindeMacBook-Pro-2:kubectl admin$ ./kubectl set resources -f ../../test/fixtures/pkg/kubectl/cmd/set/multi-resource-yaml.yaml --limits=cpu=200m,memory=512Mi --local -o yaml
apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    app: mock
  name: first-rc
  namespace: default
spec:
  replicas: 1
  selector:
    app: mock
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mock
    spec:
      containers:
      - image: gcr.io/google-containers/pause:2.0
        imagePullPolicy: IfNotPresent
        name: mock-container
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
