### ISSUE TITLE
daemonset wrongly reports unavailable pods

### ISSUE THREAD

**Issue by guoshimin** [kubernetes/kubernetes#53023]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
kubectl rollout status on a daemonset sometimes is stuck forever. The daemonset's status reports unavailable pods even when all pods are running and ready.

```
$ kubectl -n monitoring rollout status ds <redacted>
Waiting for rollout to finish: 1 of 2 updated pods are available...
```
Here's the status section of the daemonset:
```
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 2
  numberUnavailable: 1
  observedGeneration: 1
  updatedNumberScheduled: 2
```

Here's the status sections of the pods:
```
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2017-09-25T21:13:05Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2017-09-25T21:16:14Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2017-09-25T21:14:24Z
      status: "True"
      type: PodScheduled
```

```
 status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2017-09-25T21:13:04Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2017-09-25T21:16:02Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2017-09-25T21:14:28Z
      status: "True"
      type: PodScheduled
```

```
$ date
Mon Sep 25 22:18:39 UTC 2017
```

**What you expected to happen**:
kubectl rollout status should exit successfully when the rollout is complete. The daemonset should report all pods as available.

**How to reproduce it (as minimally and precisely as possible)**:
Can't reproduce it reliably, but it happened with this simple daemonset:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations: <redacted>
  name: <redacted>
  namespace: <redacted>
spec:
  minReadySeconds: 30
  template:
    metadata:
      annotations: <redacted>
      labels: <redacted>
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: NotIn
                values:
                - <redacted>
      containers:
      - args: <redacted>
        image: <redacted>
        imagePullPolicy: Always
        name: <redacted>
        ports: <redacted>
        resources: {}
        volumeMounts: <redacted>
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
        name: podinfo
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 3
    type: RollingUpdate
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`):
- Install tools: GKE
- Others:

**Comment by jhorwit2** [comment]
/reopen
/remove-lifecycle rotten

I run into this fairly often but also can't reliably reproduce it or see what's actually wrong.

**Comment by jhorwit2** [comment]
/reopen

Third times the charm?

**Comment by jhorwit2** [comment]
cc @kubernetes/sig-apps-bugs

**Comment by saj** [comment]
I have encountered the same problem.

Symptoms presented when the last `readinessProbe` was removed from a `DaemonSet`.  Like in the opening message, the `DaemonSet` was still configured with a `minReadySeconds`.  Deleting the `DaemonSet` and creating it again (with the same configuration -- without any `readinessProbe`s but with a `minReadySeconds`) resulted in the same problem.

Removing `minReadySeconds` seemed to help.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T16:16:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5+coreos.0", GitCommit:"b8e596026feda7b97f4337b115d1a9a250afa8ac", GitTreeState:"clean", BuildDate:"2017-12-12T11:01:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by justinwalz** [comment]
I just observed this on one of our clusters as well. To add some context to potentially help reproduce, the daemonset was applied before a config, so all pods were in `CreateContainerConfigError`. I then applied the config, and all containers transitioned to `Running`. However it seems like the DS status didn't quite catch onto this from a "availability" perspective, but it did on a "ready" one. 

```
kubectl -n $NS get daemonsets $NAME -o json | jq .status
{
  "currentNumberScheduled": 5,
  "desiredNumberScheduled": 5,
  "numberAvailable": 1,
  "numberMisscheduled": 0,
  "numberReady": 5,
  "numberUnavailable": 4,
  "observedGeneration": 1,
  "updatedNumberScheduled": 5
}
```

We also use a livenessProbe and minReadySeconds spec if that helps too.

Deleting the DS and reapplying it seems to fix things, now both available and ready show 5.

**Comment by VegarM** [comment]
Observed in one of our clusters as well, where the reported number of available/ready pods seems to be wrong.

This happened to 2 other DaemonSets running in this cluster as well. We "fixed" one of them by changing the DaemonSet pod spec which triggered a rolling update. After the update the counts were correct. We've not been able to find any misbehaving node or other signs that indicate something is wrong with the cluster.

The DaemonSet has been in this state for 3-4 hours now.


some information:
```
$ kubectl get ds rook-agent
NAME         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
rook-agent   38        38        37      38           37          <none>          521d
```


```
$ kubectl get po -l app=rook-agent
NAME               READY   STATUS    RESTARTS   AGE
rook-agent-2mt2k   1/1     Running   5          28d
rook-agent-4bmp8   1/1     Running   5          28d
rook-agent-4c6sv   1/1     Running   9          68d
rook-agent-4sljf   1/1     Running   5          28d
rook-agent-4sr27   1/1     Running   23         384d
rook-agent-56xxw   1/1     Running   9          68d
rook-agent-589vv   1/1     Running   9          68d
rook-agent-5t9dc   1/1     Running   5          28d
rook-agent-7bl2w   1/1     Running   9          69d
rook-agent-9wwhj   1/1     Running   9          69d
rook-agent-b7qb9   1/1     Running   13         149d
rook-agent-c5w5z   1/1     Running   13         149d
rook-agent-dhfzd   1/1     Running   9          68d
rook-agent-ff28t   1/1     Running   5          28d
rook-agent-fmlcs   1/1     Running   23         417d
rook-agent-gpk6b   1/1     Running   9          68d
rook-agent-jt5vv   1/1     Running   26         384d
rook-agent-jtx9v   1/1     Running   9          69d
rook-agent-kpzmp   1/1     Running   9          68d
rook-agent-m2kqn   1/1     Running   9          69d
rook-agent-mtdmr   1/1     Running   13         149d
rook-agent-mvhgp   1/1     Running   9          69d
rook-agent-mw42l   1/1     Running   9          68d
rook-agent-ndd68   1/1     Running   5          28d
rook-agent-pqkhk   1/1     Running   9          69d
rook-agent-q2xbp   1/1     Running   5          28d
rook-agent-ssnm2   1/1     Running   9          68d
rook-agent-tvwj2   1/1     Running   23         417d
rook-agent-tzxhj   1/1     Running   9          68d
rook-agent-v2hds   1/1     Running   14         149d
rook-agent-v4l58   1/1     Running   9          68d
rook-agent-v8htx   1/1     Running   5          28d
rook-agent-w9qmc   1/1     Running   9          68d
rook-agent-x7t4d   1/1     Running   9          68d
rook-agent-xjgm6   1/1     Running   9          69d
rook-agent-zczhh   1/1     Running   9          69d
rook-agent-zvb28   1/1     Running   9          69d
rook-agent-zvqsh   1/1     Running   9          69d
```

```
$ kubectl get po -l app=rook-agent --no-headers | wc -l
38
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl describe ds rook-agent
Name:           rook-agent
Selector:       app=rook-agent
Node-Selector:  <none>
Labels:         app=rook-agent
Annotations:    deprecated.daemonset.template.generation: 2
Desired Number of Nodes Scheduled: 38
Current Number of Nodes Scheduled: 38
Number of Nodes Scheduled with Up-to-date Pods: 38
Number of Nodes Scheduled with Available Pods: 37
Number of Nodes Misscheduled: 0
Pods Status:  38 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=rook-agent
  Service Account:  rook-agent
  Containers:
   rook-agent:
    Image:      rook/rook:v0.7.1
    Port:       <none>
    Host Port:  <none>
    Args:
      agent
    Environment:
      POD_NAMESPACE:   (v1:metadata.namespace)
      NODE_NAME:       (v1:spec.nodeName)
    Mounts:
      /dev from dev (rw)
      /flexmnt from flexvolume (rw)
      /lib/modules from libmodules (rw)
      /sys from sys (rw)
  Volumes:
   flexvolume:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/volumeplugins
    HostPathType:
   dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:                                                                                                                                                                                                                                                                               sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:
   libmodules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
Events:            <none>
```

Please tell me if I can provide any more information.

**Comment by christianhuening** [comment]
i have the exact same here. K8s `1.15.3`.
I can fix every DaemonSet with that issue by running `kubectl rollout restart ds <DaemonSetName>`. It then get's rerolled and all is fine.

**Comment by tnozicka** [comment]
Is status.observedGeneration matching the metadate.generation when you see a mismatch? I can't tell from the partial dumps.

**Comment by varuzam** [comment]
I have the similar problem.
```
~$ kubectl get ds -n logging
NAME         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
fluent-bit   21        21        19      18           19          <none>          147d

~$ kubectl get pod -n logging
NAME               READY   STATUS    RESTARTS   AGE
fluent-bit-45dlw   1/1     Running   0          9d
fluent-bit-4kcrz   1/1     Running   0          9d
fluent-bit-7bc47   1/1     Running   0          9d
fluent-bit-8xgmj   1/1     Running   0          9d
fluent-bit-b6kzj   1/1     Running   0          9d
fluent-bit-bh8x7   1/1     Running   0          9d
fluent-bit-f7r8x   1/1     Running   0          9d
fluent-bit-g2f85   1/1     Running   0          9d
fluent-bit-g8d2z   1/1     Running   0          9d
fluent-bit-jbw5s   1/1     Running   0          9d
fluent-bit-jq66t   1/1     Running   0          9d
fluent-bit-jvxpp   1/1     Running   0          9d
fluent-bit-k7kxp   1/1     Running   0          9d
fluent-bit-kdvtq   1/1     Running   0          9d
fluent-bit-q85qp   1/1     Running   1          9d
fluent-bit-sgb9h   1/1     Running   0          9d
fluent-bit-sprzd   1/1     Running   0          9d
fluent-bit-t7hk8   1/1     Running   0          9d
fluent-bit-vj9x2   1/1     Running   0          9d
fluent-bit-whj8m   1/1     Running   0          9d
fluent-bit-zhdwg   1/1     Running   0          9d

~$ kubectl get pod -n logging --no-headers |wc -l
21
```

status.observedGeneration = metadata.generation if it helps

**Comment by tnozicka** [comment]
says desired 21, up to date 18, so it seems like some pods may have older podspec? (Rolling update is in progress or maybe you have OnDelete strategy.) Can you get the full yaml for the DS and matching DS controller logs?

Likely one of the new pods didn't become available and the rollout is waiting. fluent-bit-q85qp seems to be restarting.

**Comment by varuzam** [comment]
@tnozicka 
No rollout update is in progress. Yes, the DS has OnDelete strategy. But how can it cause the problem?
When the problem happened a while ago I restarted all the pods and everything became good. But then the mismatching desired/available/ready pods happened again without any external interventions. I mean No one has touched the DS since it became OK.  The only thing I have found that some nodes became NotReady sometimes, because kubelet could not connect to API server due to some network issues. but it can not clarify why the DS reports some pods is not ready if they are actually ready.
is there a way to determine which pods a DS considers not-ready?
the DS's yaml
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      serviceAccountName: fluent-bit
      tolerations:
      - key: dedicated
        operator: Exists
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.1.3
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        envFrom:
        - configMapRef:
            name: fluent-bit-env
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
```
