### ISSUE TITLE
openstack: Service LoadBalancer no longer defaults to external

### ISSUE THREAD

**Issue by lblackstone** [kubernetes/kubernetes#53078]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Creating a service with `type: LoadBalancer` created a load balancer without a floating IP.

**What you expected to happen**:
Load balancer should have a floating IP assigned by default.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    k8s-app: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    k8s-app: nginx
```
Deploy this manifest on a `1.8.0-rc.1` cluster and check the resulting load balancer. No floating IP will be assigned.

**Anything else we need to know?**:
The default behavior changed from k8s 1.7.x. It appears that 9bdf2cc0 added an annotation that will add a floating IP, but the default should not have changed without warning.

This also breaks the `kubectl expose` workflow. For example:
```
$ kubectl run nginx --image nginx --replicas 3
deployment "nginx" created

$ kubectl expose deployment/nginx --port=80 --type=LoadBalancer
service "nginx" exposed

$ kubectl get svc nginx
NAME      CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
nginx     10.3.32.166   10.0.0.19     80:30985/TCP   1m

$ kubectl describe svc nginx
Name:			nginx
Namespace:		default
Labels:			run=nginx
Annotations:		<none>
Selector:		run=nginx
Type:			LoadBalancer
IP:			10.3.32.166
LoadBalancer Ingress:	10.0.0.19
...
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.0-rc.1+coreos.0
- Cloud provider or hardware configuration**: openstack
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 1520.4.0 (Ladybug)
- Kernel (e.g. `uname -a`): 4.13.3-coreos
- Install tools:
- Others:
