### ISSUE TITLE
Volume umounted after kubelet restart

### ISSUE THREAD

**Issue by valentin2105** [kubernetes/kubernetes#53246]
**What happened**:

When upgrading k8s on the 1.7.x branch, (1.7.4 to 1.7.6 exactly), every Kubernetes services can be restarted without problems except for Kubelet that cause volumes get umounted in pods.

I use GlusterFS volumes and when I restart Kubelet the volume is unmounted and it case a crash of the applications.

```
        volumeMounts:
        - name: db-folder
          mountPath: /var/lib/mysql
      volumes:
        - name: db-folder
          glusterfs:
            endpoints: glusterfs-cluster
            path: website-db
            readOnly: false
```

```
root@website-db-3276445667-gl5nv:/# df -h
df: /var/lib/mysql: Transport endpoint is not connected
root@nwebsite-db-3276445667-gl5nv:/# cd /var/lib/mysql
bash: cd: /var/lib/mysql: Transport endpoint is not connected
```
**What you expected to happen**:
Kubelet need to be able to restart without this issue. 

**How to reproduce it (as minimally and precisely as possible)**:
- Use external volumes (GlusterFS but other can be impacted? ),

- Go on the worker where your pod run, 

- Restart Kubelet,

- Check if your application is still up. 

Kubernetes version (use `kubectl version`):

1.7.6

Cloud provider or hardware configuration**:

Debian 9, multi nodes, IPv4/6 with Calico, on premise. 

/kind bug
