### ISSUE TITLE
CronJob jobs should be named after their job spec, not the cronjob

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/kubernetes#53347]
/kind feature

Example cronjob:

```
---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: "mycronjob-foo"
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: "mycronjob-bar"
        spec:
          containers:
          - name: nginx
            image: nginx
            command: ["/bin/echo", "hi"]
          restartPolicy: Never
```

Note that I named the CronJob "mycronjob-foo" and I named the job "mycronjob-bar" in the spec.

Here's what this produces:

```
$ kubectl get cronjobs
NAME                 SCHEDULE    SUSPEND   ACTIVE    LAST-SCHEDULE
mycronjob-foo        * * * * *   False     0         Mon, 02 Oct 2017 21:15:00 +0000

$ kubectl get jobs
NAME                            DESIRED   SUCCESSFUL   AGE
mycronjob-foo-1506978900        1         1            22s
```

I would expect the job to be named `mycronjob-bar-1506978900` instead, since I went out of my way to name the job spec as such.

I almost filed this as a bug but it seems that the naming behavior isn't explicitly documented anywhere so I am filing it as a feature request.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.0
