### ISSUE TITLE
AWS: Tagging the security group of ELB created for LoadBalancer or Ingress 

### ISSUE THREAD

**Issue by sbuliarca** [kubernetes/kubernetes#53367]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
@kubernetes/sig-aws-feature-requests
/sig aws

**What happened**:
In k8s 1.7, when creating a service of type LoadBalancer, K8S creates the ELB and a Security Group for it. For these resources, it adds a tag, constructed dynamically, containing the cluster id: "kubernetes.io/cluster/${cluster_id}" with the value "true" 

**What you expected to happen**:
We'd like to have also a statically named tag , as it was in 1.5 ("KubernetesCluster") with the value of the cluster id.  

**How to reproduce it (as minimally and precisely as possible)**:
Running on AWS cloud provider, create a service of type LoadBalancer.

**Anything else we need to know?**:
The reason for what we expect is that we have tight security constraints that require us to fine tune the IAM policies for the Instance profiles that the controllers use.   
With a statically named tag we were able, in 1.5, to restrict the permissions in the IAM policy to act only on the k8s managed resources (ELBs, security groups). Here is the relevant part of the IAM policy:
```
         - Action:
            - ec2:AuthorizeSecurityGroupIngress
            - ec2:DeleteSecurityGroup
            - ec2:RevokeSecurityGroupIngress
            Effect: Allow
            Resource:
            - "*"
            Condition:
              StringLike:
                ec2:ResourceTag/KubernetesCluster: "*"
```
With a dynamically named tag we are not able to do this any more as AWS IAM doesn't support something like:
```
Condition:
  StringLike:
     kubernetes.io/cluster/*: "*"
``` 
We are sharing the Instance Profiles among different k8s clusters, hence the "*" in the value of the tag.
**Environment**:
- Kubernetes version (use `kubectl version`):
``` 
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4+coreos.0", GitCommit:"4bb697e04f7c356347aee6ffaa91640b428976d5", GitTreeState:"clean", BuildDate:"2017-08-22T08:43:47Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.8.0
VERSION_ID=1465.8.0
BUILD_ID=2017-09-20-2237
PRETTY_NAME="Container Linux by CoreOS 1465.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```Linux ip-xxxxxxxxx.eu-west-1.compute.internal 4.12.14-coreos #1 SMP Wed Sep 20 22:20:05 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz GenuineIntel GNU/Linux```
- Install tools: kube-aws
- Others:
