### ISSUE TITLE
upgrading to 1.8 broke Service backwards compatibility by not allowing the same target port multiple times

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#53526]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig api
/sig network

**What happened**:

Prior to 1.8 it was possible to specify the same targetPort in the service definition multiple times. In 1.8, validation was added that prohibited this. 

**What you expected to happen**:
I expect backwards compatibility for GA resources, so having the same targetPort multiple times should be allowed. This is a valid use case IMO for target ports. If you take the example below, the load balancer terminates SSL, so that manifest allows the nginx pods to receive http on port 80 while the load balancer serves traffic on 80 & 443. 

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl apply -f - <<EOF 
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: ssl-certificate-secret
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
EOF
```

**Anything else we need to know?**:

Original ticket for validation: https://github.com/kubernetes/kubernetes/issues/47222

**Comment by jhorwit2** [comment]
cc @thockin @xiangpengzhao

**Comment by xiangpengzhao** [comment]
Sounds reasonable. @thockin WDYT?

**Comment by cmluciano** [comment]
@kubernetes/sig-network-api-reviews

**Comment by fwynyk** [comment]
Hi, same problem here. Trying to create a service with helm, both 80 and 443 ports using same targetPort, and got this error:

`Error: UPGRADE FAILED: failed to create resource: Service "#####" is invalid: spec.ports[1].targetPort: Duplicate value: intstr.IntOrString{Type:0, IntVal:8000, StrVal:""}`

**Comment by caseydavenport** [comment]
Feels reasonable, and it seems this is impacting enough people to warrant reverting the original change.

@thockin WDYT?

**Comment by tamalsaha** [comment]
Given Service objects are `v1`, how can a breaking change like this was accepted?

**Comment by etiennetremel** [comment]
For the one looking for a temporary way to fix it you have to mix named port with value, see below:

```
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: 80
```
