### ISSUE TITLE
Failure count of liveness probe is not reset by restart

### ISSUE THREAD

**Issue by joelittlejohn** [kubernetes/kubernetes#53530]
/kind bug

I'm investigating a problem that causes pods to become permanently broken whenever the container in the pod fails its livenessProbe and needs to be restarted. The container from this point always fails to start, and the pod eventually becomes stuck in CrashLoopBackOff after many attempted restarts.

I have a theory about why this is happening based on my observations and the k8s source code, but welcome other opinions.

**What happened**:

When a new pod creates a new container that has a livenessProbe, the probe worker waits `initialDelaySeconds` seconds then runs the livenessProbe. By default, it requires that there are three consecutive failures of the livenessProbe (`failureThreshold`) before marking the container unhealthy. This means that as long as your app boots and becomes healthy within `initialDelaySeconds + (2 x periodSeconds)` then your app will come up successfully.

If your app becomes unhealthy whilst running, and fails `failureThreshold` (default 3) probes in a row, the container will be marked as unhealthy and restarted. Unfortunately, when your container now starts, the [probe worker's resultRun](https://github.com/kubernetes/kubernetes/blob/5cc95fbf277583dbd6b4b40610a92eb856bd9a7b/pkg/kubelet/prober/worker.go#L64) will still be 3, so when the container launches, just one failed livenessProbe will cause the container to be restarted.

The upshot of this is that the time allowed for your app to boot is different depending on the context:

* When your app is initially deployed, you have `initialDelaySeconds + (2 x periodSeconds)` seconds to boot
* If your app is later restarted by k8s, you have only `initialDelaySeconds` seconds to boot

So it's very easy to deploy an app that starts successfully when the pods is created, but this app is a time-bomb because Kubernetes will fail to restart it if it ever needs to restart. If Kubernetes needs to restart the pod, it will get stuck in a restart loop and ultimately end up in CrashLoopBackOff.

**What you expected to happen**:

I expect that a fresh (newly restarted) container will have its own liveness probe worker, or at least the worker's `resultRun` value will be reset when a container is restarted. It doesn't make sense to me that failures from the previous container would be counted against the new container.

**How to reproduce it (as minimally and precisely as possible)**:
I _think_ this spec reproduces the problem:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - image: gcr.io/google_containers/busybox
    args:
    - /bin/sh
    - -c
    - "sleep 10; touch /tmp/healthy; while true; do sleep 86400; done"
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
```

When you deploy this pod initially, it is given `initialDelaySeconds + (2 x periodSeconds)`, or `5 + (2 x 10) = 20` seconds to start.

Once this pod is running and healthy, exec onto it and delete /tmp/healthy. The livenessProbe will begin to fail, and after 3 failures the container will be restarted. Now the container will be stuck in a permanent restart loop until it enters CrashLoopBackOff.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.5.4+coreos.0
- Cloud provider or hardware configuration**: AWS/EC2
- OS (e.g. from /etc/os-release): CoreOS 1185.5.0
- Kernel (e.g. `uname -a`): 4.7.3-coreos-r3
