### ISSUE TITLE
[Feature Request] Pod Lifecycle

### ISSUE THREAD

**Issue by tushar00jain** [kubernetes/kubernetes#53633]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:

**What you expected to happen**:
Have a use case when containers in a pod need to be killed in some predefined order. Will in be possible to add a pod-level lifecycle as there is for container lifecycle. For example, something like kill `Container 2` if `Container 1` has shut down, where both containers are in the same pod.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dixudx** [comment]
> Have a use case when containers in a pod need to be killed in some predefined order.

> For example, something like kill Container 2 if Container 1 has shut down, where both containers are in the same pod.

@tushar00jain  Why not using [liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) for `Container 1` when starting `Container2`.

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: container1
    image: xxx
    args:
    - xxx
  - name: container2
    image: yyy
    args:
    - yyy
    livenessProbe:
      exec:
        command:
        - "ping -c 3 -t 2"
        - container1
      initialDelaySeconds: 5
      periodSeconds: 5
```
