### ISSUE TITLE
podSecurityPolicyPlugin must not modify pod data

### ISSUE THREAD

**Issue by ryarnyah** [kubernetes/kubernetes#53797]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: When you set SecurityContextDeny after PodSecurityPolicy in admission-control for apiserver, this error happend : "SecurityContext.SupplementalGroups is forbidden"

**What you expected to happen**: No error

**How to reproduce it (as minimally and precisely as possible)**:
* Create psp on the cluster

```bash
$ kubectl get psp
service-policy      false     []                          RunAsAny   MustRunAsNonRoot   RunAsAny   RunAsAny   true             [emptyDir secret configMap hostPath]
```
* Set admission-control with SecurityContextDeny after PodSecurityPolicy. ex:
```bash
--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,PodSecurityPolicy,SecurityContextDeny,DenyEscalatingExec
```
* Create a pod with no security context
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  namespace: default
spec:
    containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginx
      ports:
      - containerPort: 80
        name: http
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 100m
          memory: 50Mi
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 1
        periodSeconds: 5
        failureThreshold: 15
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 5
        failureThreshold: 15
```
* You will see 
```bash
$ kubectl apply -f nginx.yml
Error from server (Forbidden): error when creating "nginx.yml": pods "nginx" is forbidden: SecurityContext.SupplementalGroups is forbidden
```

**Anything else we need to know?**:
* If you set SecurityContextDeny before PodSecurityPolicy, no error is throw.
* In plugin/pkg/admission/security/podsecuritypolicy/admission.go the pod from admission.Attributes is updated in assignSecurityContext (it may be the problem?):
```go
func (c *podSecurityPolicyPlugin) Admit(a admission.Attributes) error {
...
pod, ok := a.GetObject().(*api.Pod)
...
if errs := assignSecurityContext(provider, pod, field.NewPath(fmt.Sprintf("provider %s: ", provider.GetPSPName()))); len(errs) > 0 {
...
func assignSecurityContext(provider psp.Provider, pod *api.Pod, fldPath *field.Path) field.ErrorList {
...
pod.Spec.SecurityContext = psc
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.8
- Cloud provider or hardware configuration**: VirtualBox
- OS (e.g. from /etc/os-release): Centos 7.3
- Kernel (e.g. `uname -a`): Linux controller1 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubectl
- Others:
