### ISSUE TITLE
StatefulSet deletion delayed when using limit ranges

### ISSUE THREAD

**Issue by karanthukral** [kubernetes/kubernetes#53807]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug

**What happened**:
- Stateful set deletion is delayed, sometimes by hours when using alongside limit ranges in the namespace
- The `deletionTimestamp` field for the statefulset is set correctly but the actual deletion is still delayed

**What you expected to happen**:
- Without limit ranges, the deletion is instantaneous 

**How to reproduce it (as minimally and precisely as possible)**:
```
# test in new  namespace is important
$ kubectl create namespace test-statefulset-limitrange
namespace "test-statefulset-limitrange" created

$ kubectl config set-context $(kubectl config current-context) --namespace=test-statefulset-limitrange
Context "" set.

$ kubectl apply -f nginx.yml
statefulset "web" created

$ kubectl get all,limitrange
NAME       READY     STATUS    RESTARTS   AGE
po/web-0   1/1       Running   0          6s

NAME               DESIRED   CURRENT   AGE
statefulsets/web   1         1         7s

# Create limitrange when pod is running
$ kubectl apply -f limitrange.yml
limitrange "custom-limit-ranges" created

$ kubectl get all,limitrange
NAME       READY     STATUS    RESTARTS   AGE
po/web-0   1/1       Running   0          17s

NAME               DESIRED   CURRENT   AGE
statefulsets/web   1         1         18s

NAME                                AGE
limits/custom-limit-ranges   5s

$ kubectl delete --cascade=false statefulsets/web
statefulset "web" deleted

# statefulsets/web still present and can take hours to get deleted
$ kubectl get all,limitrange
NAME       READY     STATUS    RESTARTS   AGE
po/web-0   1/1       Running   0          29s

NAME               DESIRED   CURRENT   AGE
statefulsets/web   1         1         30s

NAME                                AGE
limits/custom-limit-ranges   17s

# deletionTimestamp is set correctly
$ kubectl get statefulsets/web -o yaml | grep deletionTimestamp
deletionTimestamp: 2017-10-12T14:15:28Z

# 5 minutes later
$ kubectl get all,limitrange
NAME       READY     STATUS    RESTARTS   AGE
po/web-0   1/1       Running   0          6m

NAME               DESIRED   CURRENT   AGE
statefulsets/web   1         1         6m

NAME                                AGE
limits/custom-limit-ranges   6m
```

**K8S Templates Used**
**Limit Range**
```
apiVersion: v1
kind: LimitRange
metadata:
  name: custom-limit-ranges
spec:
  limits:
  - default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: 200m
      memory: 1Gi
    type: Container
```

**StatefulSet**
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.6
- Cloud provider or hardware configuration**: gke
- OS (e.g. from /etc/os-release): gke cos
- Install tools: gcloud components install kubetcl
