### ISSUE TITLE
test can not create statefulset using statefulset_utils.go when apiversion is set to apps/v1beta2

### ISSUE THREAD

**Issue by divyenpatel** [kubernetes/kubernetes#53847]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Test Panicked when statefulset is created using `apiVersion: apps/v1beta2`
Test is using kubernetes/test/e2e/framework/statefulset_utils.go
Same test with `apiVersion: apps/v1beta1`, works fine.

```
Test Panicked
  reflect: call of reflect.Value.IsNil on int64 Value
  /usr/local/go/src/runtime/panic.go:489

  Full Stack Trace
  	/usr/local/go/src/runtime/panic.go:489 +0x2cf
  reflect.Value.IsNil(0x32ba7c0, 0xc420e65bb8, 0x186, 0x5b69200)
  	/usr/local/go/src/reflect/value.go:995 +0x106
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).defaultConvert(0xc4202f49a0, 0x32ba7c0, 0xc420e65bb8, 0x186, 0x3163120, 0xc420e64fb8, 0x196, 0xc4203d5270, 0x0, 0x0)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:636 +0x12b9
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert(0xc4202f49a0, 0x32ba7c0, 0xc420e65bb8, 0x186, 0x3163120, 0xc420e64fb8, 0x196, 0xc4203d5270, 0x412300, 0x0)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:577 +0x821
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convertKV(0xc4202f49a0, 0x5b48b20, 0xc4202b6720, 0x5b48b20, 0xc4202b6840, 0xc4203d5270, 0x4, 0x32e2f7e)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:836 +0x6c0
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).defaultConvert(0xc4202f49a0, 0x3ac9f00, 0xc420e65bb8, 0x199, 0x3ac9a00, 0xc420e64fb8, 0x199, 0xc4203d5270, 0x0, 0x0)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:621 +0xf1f
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert(0xc4202f49a0, 0x3ac9f00, 0xc420e65bb8, 0x199, 0x3ac9a00, 0xc420e64fb8, 0x199, 0xc4203d5270, 0x0, 0x0)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:577 +0x821
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convertKV(0xc4202f49a0, 0x5b48b20, 0xc420db0e20, 0x5b48b20, 0xc420db10c0, 0xc4203d5270, 0x1, 0x2)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:836 +0x6c0
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).defaultConvert(0xc4202f49a0, 0x3914200, 0xc420e65800, 0x199, 0x3913be0, 0xc420e64c00, 0x199, 0xc4203d5270, 0x0, 0x0)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:621 +0xf1f
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).convert(0xc4202f49a0, 0x3914200, 0xc420e65800, 0x199, 0x3913be0, 0xc420e64c00, 0x199, 0xc4203d5270, 0xc420159e01, 0xc4203d5270)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:577 +0x821
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).(k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.convert)-fm(0x3914200, 0xc420e65800, 0x199, 0x3913be0, 0xc420e64c00, 0x199, 0xc4203d5270, 0x1, 0x411ac2)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:480 +0x7d
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc4202f49a0, 0x3bf76a0, 0xc420e65800, 0x3bf6260, 0xc420e64c00, 0x8, 0xc420db0d60, 0xc420ce5c48, 0x0, 0xc420ce5ce8)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:517 +0x2d0
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.(*Converter).Convert(0xc4202f49a0, 0x3bf76a0, 0xc420e65800, 0x3bf6260, 0xc420e64c00, 0x8, 0xc420db0d60, 0x3bf76a0, 0x5dbdf01)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/converter.go:480 +0xbf
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).Convert(0xc4203f20c0, 0x3bf76a0, 0xc420e65800, 0x3bf6260, 0xc420e64c00, 0x35b9fe0, 0x5dba040, 0x5b69200, 0x3bf76a0)
  	<autogenerated>:112 +0x87
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode(0xc4202ebb80, 0xc421570a00, 0x26f, 0x48b, 0x0, 0x5b291a0, 0xc420e64c00, 0x0, 0xc4203f20c0, 0xc4203b3340, ...)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/manifest/manifest.go:99 +0x168
  k8s.io/kubernetes/test/e2e/framework.(*StatefulSetTester).CreateStatefulSet(0xc4201ad300, 0x3cf23f0, 0x2c, 0xc420d3c450, 0x23, 0x0)
  	/root/divyenp/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/statefulset_utils.go:100 +0x190
```

```
# cat statefulset.yaml 
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.beta.kubernetes.io/storage-class: nginx-sc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

**What you expected to happen**:
statefulset_utils.go should support creating statefulset with API version `apps/v1beta2` 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):" v1.8.1
- Cloud provider or hardware configuration**: vsphere cloud provider
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

cc: @janetkuo @foxish
