### ISSUE TITLE
Create 2 crd with  the same crdgroup, fail to watch one crd with error "404 not found". 

### ISSUE THREAD

**Issue by loadwiki** [kubernetes/kubernetes#53882]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
Create 2  crds(custom resource definition) with  the same crd group, different name, kind. 
Failed to watch one kind of crd with http error status "404 not found"
**What you expected to happen**:
In k8s 1.7.3 environment,  the watch request to both crds successed.
In k8s 1.7.4 environment,  one of the watch requests failed with 404 not found.
**How to reproduce it (as minimally and precisely as possible)**:
Just  do it as above.

**Anything else we need to know?**:
The k8s 1.7.4 environment is updated from 1.6.x somedays ago.
I'm not sure the issue is caused by version change or environment change.
**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
physical server
- OS (e.g. from /etc/os-release):
CentOS Linux release 7.2.1511
- Kernel (e.g. `uname -a`):
3.10.0-327.el7.x86_64
- Install tools:
- Others:

**Comment by liggitt** [comment]
cannot recreate on 1.7.4 or on master

crd.yaml:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: noxus.mygroup.example.com
spec:
  group: mygroup.example.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: noxus
    singular: noxu
    kind: Noxu
    listKind: NoxuList
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: boxus.mygroup.example.com
spec:
  group: mygroup.example.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: boxus
    singular: boxu
    kind: Boxu
    listKind: BoxuList
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: doxus.mygroup.example.com
spec:
  group: mygroup.example.com
  version: v1alpha2
  scope: Namespaced
  names:
    plural: doxus
    singular: doxu
    kind: Doxu
    listKind: DoxuList
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foxus.mygroup.example.com
spec:
  group: mygroup.example.com
  version: v1alpha3
  scope: Namespaced
  names:
    plural: foxus
    singular: foxu
    kind: Foxu
    listKind: FoxuList
```

resource.yaml:
```yaml
apiVersion: mygroup.example.com/v1alpha1
kind: Noxu
metadata:
  name: alfa-noxu
spec:
  key: value
---
apiVersion: mygroup.example.com/v1alpha1
kind: Boxu
metadata:
  name: alfa-boxu
spec:
  key: value
---
apiVersion: mygroup.example.com/v1alpha2
kind: Doxu
metadata:
  name: alfa-doxu
spec:
  key: value
---
apiVersion: mygroup.example.com/v1alpha3
kind: Foxu
metadata:
  name: alfa-foxu
spec:
  key: value
```

```sh
$ kubectl version --output json | jq .
{
  "clientVersion": {
    "major": "1",
    "minor": "7",
    "gitVersion": "v1.7.4",
    "gitCommit": "793658f2d7ca7f064d2bdf606519f9fe1229c381",
    "gitTreeState": "clean",
    "buildDate": "2017-10-13T16:45:40Z",
    "goVersion": "go1.8.3",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "7",
    "gitVersion": "v1.7.4",
    "gitCommit": "793658f2d7ca7f064d2bdf606519f9fe1229c381",
    "gitTreeState": "clean",
    "buildDate": "2017-10-13T16:45:40Z",
    "goVersion": "go1.8.3",
    "compiler": "gc",
    "platform": "darwin/amd64"
  }
}

$ kubectl create -f crd.yaml 
customresourcedefinition "noxus.mygroup.example.com" created
customresourcedefinition "boxus.mygroup.example.com" created
customresourcedefinition "doxus.mygroup.example.com" created
customresourcedefinition "foxus.mygroup.example.com" created

$ kubectl create -f resource.yaml 
noxu "alfa-noxu" created
boxu "alfa-boxu" created
doxu "alfa-doxu" created
foxu "alfa-foxu" created

$ kubectl get boxu 
NAME        KIND
alfa-boxu   Boxu.v1alpha1.mygroup.example.com

$ kubectl get boxu -w
NAME        KIND
alfa-boxu   Boxu.v1alpha1.mygroup.example.com
^C

$ kubectl get noxu
NAME        KIND
alfa-noxu   Noxu.v1alpha1.mygroup.example.com

$ kubectl get noxu -w
NAME        KIND
alfa-noxu   Noxu.v1alpha1.mygroup.example.com
^C

$ kubectl get foxu
NAME        KIND
alfa-foxu   Foxu.v1alpha3.mygroup.example.com

$ kubectl get foxu -w
NAME        KIND
alfa-foxu   Foxu.v1alpha3.mygroup.example.com
^C

$ kubectl get doxu
NAME        KIND
alfa-doxu   Doxu.v1alpha2.mygroup.example.com

$ kubectl get doxu -w
NAME        KIND
alfa-doxu   Doxu.v1alpha2.mygroup.example.com
^C
```
