### ISSUE TITLE
Unable create v1.Service with duplicate targetPort after upgrade to v1.8

### ISSUE THREAD

**Issue by MikaelCluseau** [kubernetes/kubernetes#53949]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig network

**What happened**:

The following service definition was valid in Kubernetes 1.7:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http1
    port: 80
    protocol: TCP
    targetPort: 80
  - name: http2
    port: 81
    protocol: TCP
    targetPort: 80
```

In Kubernetes 1.8 I have this error:
```
$ kubectl create -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http1
    port: 80
    protocol: TCP
    targetPort: 80
  - name: http2
    port: 81
    protocol: TCP
    targetPort: 80
EOF
The Service "nginx" is invalid: spec.ports[1].targetPort: Duplicate value: intstr.IntOrString{Type:0, IntVal:80, StrVal:""}
```

**What you expected to happen**:

Duplicate targetPort shouldn't be problematic. Or there should be a note somewhere (I searched the changelog with no success).

**How to reproduce it (as minimally and precisely as possible)**:

See command above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.1
- Cloud provider or hardware configuration**: self hosted
- OS (e.g. from /etc/os-release): CoreOS Container Linux stable
- Kernel (e.g. `uname -a`): Linux kube-3 4.13.5-coreos-r2 #1 SMP Thu Oct 12 03:21:09 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz GenuineIntel GNU/Linux
- Install tools: N/A
- Others:
