### ISSUE TITLE
Selector on DaemonSet is not filled automatically

### ISSUE THREAD

**Issue by jchanam** [kubernetes/kubernetes#53976]
/kind bug
/sig apps

**What happened**:
When creating a DaemonSet via kubectl, it returns an error:
``` `selector` does not match template `labels` ```
This happened on kubernetes 1.8.1 with the api `apps/v1beta2`

**What you expected to happen**:
The DaemonSet to be created without errors. The selector should be automatically filled with the pod labels as it says on the [documentation](https://kubernetes.io/docs/api-reference/v1.8/#daemonsetspec-v1beta2-apps):

> If empty, defaulted to labels on Pod template.

**How to reproduce it (as minimally and precisely as possible)**:
Create a DaemonSet:
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: my-ds
  labels:
    version: v0.9
    k8s-app: myapp
spec:
  template:
    metadata:
      name: my-ds
      labels:
        version: v0.9
        k8s-app: myapp
    spec:
      hostNetwork: true
      containers:
      - name: mypod
        image: debian
        command:
          - "/bin/bash"
          - "-c"
          - "--"
        args:
          - "tail -f /dev/null"
```
Run:
```kubectl create -f daemonset.yaml```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.1
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): Debian 9 (kops)
- Kernel (e.g. `uname -a`): Linux version 4.4.78-k8s (gcc version 4.9.2 (Debian 4.9.2-10) )
- Install tools: kops 1.8.0-alpha.1
- Others:
