### ISSUE TITLE
loadBalancerSourceRanges + lots of ranges

### ISSUE THREAD

**Issue by terinjokes** [kubernetes/kubernetes#54021]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
To configure a Load Balancer firewall, the only option right now is to use the Service's `loadBalancerSourceRanges` to define the ranges that should be allowed. If you have lots of disjointed ranges to include, you have to include the entire list for each service.

**What you expected to happen**:

There should be a way to reference ranges defined elsewhere by name. This would also allow cluster administrators to update all relevant services easily.

**How to reproduce it (as minimally and precisely as possible)**:

Let's say you're serving HTTP traffic, and expect all traffic to come through Cloudflare, right now you'll define a Service like so:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
  - port: 443
    targetPort: 9376
  selector:
    app: example
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 103.21.244.0/22
  - 103.22.200.0/22
  - 103.31.4.0/22
  - 104.16.0.0/12
  - 108.162.192.0/18
  - 131.0.72.0/22
  - 141.101.64.0/18
  - 162.158.0.0/15
  - 172.64.0.0/13
  - 173.245.48.0/20
  - 188.114.96.0/20
  - 190.93.240.0/20
  - 197.234.240.0/22
  - 198.41.128.0/17
```

If those pesky folks at Cloudflare add another range, you're now responsible for updating the source ranges for every service.

As an alternative, if you had the ability to reference configuration elsewhere in the cluster:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
  - port: 443
    targetPort: 9376
  selector:
    app: example
  type: LoadBalancer
  loadBalancerSourceRanges:
  - valueFrom:
      configMapKeyRef:
        name: cf-edge
        key: ranges
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cf-edge
  namespace: default
data:
  ranges:
  - 103.21.244.0/22
  - 103.22.200.0/22
```

(It doesn't have to be a ConfigMap, but it seems natural and similar to configuring a Pod)

Now the cluster administrators only need to update the ranges in one place, and cluster users have an easier experience using the cluster.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
