### ISSUE TITLE
CRD NamesAccepted condition has null for lastTransitionTime

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#54148]
/kind bug

**What happened**: the `lastTransitionTime` for a CRDs `NamesAccepted` condition is always null

**What you expected to happen**: it should have a timestamp

**How to reproduce it (as minimally and precisely as possible)**: create a CRD and then examine its yaml/json. For example:
```yaml
status:
  acceptedNames:
    kind: Backup
    listKind: BackupList
    plural: backups
    singular: backup
  conditions:
  - lastTransitionTime: null
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: 2017-10-16T15:49:15Z
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): commit a6625085f5091bc5ed5b7d0f5153e662ea7fd5d1
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@kubernetes/sig-api-machinery-bugs @deads2k @sttts
