### ISSUE TITLE
"kubeadm init" on offline environment 

### ISSUE THREAD

**Issue by khj809** [kubernetes/kubernetes#54188]
Hi. I'm trying to set up kubernetes cluster on my private network. 
All machines are RHEL 7.3 and use latest kubernetes version (v1.8.1) with docker-ce 17.03.2.
I thought that everything I need is some packages(kubeadm, kubectl, kubelet, kubernetes-cni and dependencies) and images (starts with gcr.io/google_containers/... and pod network images), so I prepared and installed them. But when I run "kubeadm init", it still requires internet connection with following messages.

`Unable to get URL "https://dl.k8s.io/release/stable-1.8.txt": Get https://dl.k8s.io/release/stable-1.8.txt: dial tcp: lookup dl.k8s.io on [::1]:53: read udp [::1]:54829->[::1]:53: read: connection refused`

What should I do anything else?

**Comment by wackxu** [comment]
@khj809 you can a flag `--kubernetes-version=v1.8.1`  then it will skip request the URL

**Comment by khj809** [comment]
@wackxu Thanks! It works!

**Comment by geostant** [comment]
Doesn't work on v1.10 offline mode with the statement -> --kubernetes-version=stable-1.10

**Comment by nsulek** [comment]
you can try with 

> kubeadm init --kubernetes-version=v1.10.0

it works for me

**Comment by geostant** [comment]
@nsulek - You can't run kubeadm init offline without stating explicit the version, so obviously I did so.

**Comment by antonputra** [comment]
You can create config.yaml file, for example
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 10.44.70.201
networking:
  podSubnet: 192.168.0.0/16
kubernetesVersion: 1.10.5
```
and run `kubeadm init --config=kubeadm-config.yaml`
