### ISSUE TITLE
Failed to use kubectl top command

### ISSUE THREAD

**Issue by shun-miyoshi-com** [kubernetes/kubernetes#54194]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I created kubernetes cluster by kubeadm, and I created heapster v1.4.3
Then I used kubectl top command, but I got following error message.

```

[root@miyoshi-dev ~]# kubectl top node
error: failed to unmarshall heapster response: invalid character '\x15' looking for beginning of value


```

Here is my pods status.

```

[root@miyoshi-dev ~]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                           READY     STATUS    RESTARTS   AGE
kube-system   heapster-6499c9776f-lj96k                      1/1       Running   0          4m
kube-system   kube-apiserver-miyoshi-dev.fcxlocal            1/1       Running   0          2h
kube-system   kube-controller-manager-miyoshi-dev.fcxlocal   1/1       Running   0          2h
kube-system   kube-dns-545bc4bfd4-snkz6                      3/3       Running   0          2h
kube-system   kube-flannel-ds-l7pcb                          2/2       Running   1          2h
kube-system   kube-proxy-x5zhf                               1/1       Running   0          2h
kube-system   kube-scheduler-miyoshi-dev.fcxlocal            1/1       Running   0          2h
kube-system   monitoring-influxdb-67f8d587dd-lwjqc           1/1       Running   0          4m


```

**What you expected to happen**:
use kubectl top command successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.1
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): CentOS 7.4
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Others:
  heapster: v1.4.3

**Comment by shun-miyoshi-com** [comment]
Sorry, I can run kubectl top command by removing http-proxy setting of /etc/kubernetes/manifests/kube-apiserver.yaml

Prev:

```
...
spec:
  containers:
  - command:
    - kube-apiserver
    ...
    env:
    - name: http_proxy
      value: <my-proxy-info>
    - name: https_proxy
      value: <my-proxy-info>
    - name: no_proxy
      value: <my-proxy-info>
    ...
...

```

After:

```
...
spec:
  containers:
  - command:
    - kube-apiserver
    ...
#    env:
#    - name: http_proxy
#      value: <my-proxy-info>
#    - name: https_proxy
#      value: <my-proxy-info>
#    - name: no_proxy
#      value: <my-proxy-info>
    ...
...

```

But why I can run kubectl command by removing proxy setting?
