### ISSUE TITLE
Uniqueness of named ports within a pod isn't validated

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#54213]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

/kind bug

**What happened**:

Applied a pod spec where multiple containers within a pod have the same name for their named ports.  The spec was accepted but the docs say that it should have been forbidden:

```
If specified, this must be an IANA_SVC_NAME and unique within the pod. Each named port in a pod must have a unique name. Name for the port that can be referred to by services.
```

**What you expected to happen**:

Should be rejected with a clear error message (or doc should be fixed).

**How to reproduce it (as minimally and precisely as possible)**:

- Create a pod with 2 containers.
- Include a TCP port in each container with the same name but different port number.
- Apply the pod spec.

**Anything else we need to know?**:

There are such pod specs in the wild.  kubeadm's kube-proxy spec, for example defines more than one metrics port.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Others:

**Comment by wackxu** [comment]
I think the doc is a little confused. From code
https://github.com/kubernetes/kubernetes/blob/release-1.8/pkg/api/validation/validation.go#L2199, it should be  `Each named port in a container of pod must have a unique name`

**Comment by fasaxc** [comment]
What about Services, seems odd to load balance between two ports in the same pod, is that allowed?

**Comment by caseydavenport** [comment]
/label for-new-contributors

Does anyone have any opinions on whether it's the code or the docs that are wrong? Off the top of my head I'm not sure what Service behavior you'll get when you do this.

**Comment by wackxu** [comment]
@fasaxc @caseydavenport  I have verify ` service`  that using the same port name in two containers of the pod, there is nothing wrong, I think the doc are wrong.

**Comment by wackxu** [comment]
@caseydavenport @fasaxc I think the code is wrong. I deploy a pod with two same port name as follows
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
spec:
  containers:
    - name: master
      image: kubernetes/redis:v1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
          name: port1
      resources:
        limits:
          cpu: "0.5"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
    - name: sentinel
      image: kubernetes/redis:v1
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379
          name: port1
  volumes:
    - name: data
      emptyDir: {}
```
 Then I want to expose my pod through service that targetPort use port name so that we do not aware of the change of port, but it always use the first port as the endpoint and the second is always not be visited by this way.
```
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    name: redis
  ports:
  - protocol: TCP
    port: 80
    targetPort: port1
```
`kubectl describe svc`
```
Name:              my-service
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          name=redis
Type:              ClusterIP
IP:                10.105.39.53
Port:              <unset>  80/TCP
TargetPort:        port1/TCP
Endpoints:         192.168.166.154:6379
Session Affinity:  None
Events:            <none>
```
I will commit a pr to fix it.

**Comment by liggitt** [comment]
What endpoints get populated for that service?

Tightening validation for existing objects (especially ones with known instances of data in the wild) is fraught. It can prevent deletion, migration, and status updates. 

@thockin is this a bug in validation or in the API docs?

**Comment by wackxu** [comment]
@liggitt If you use tow same port name in the different container of pod, when you expose as service, only the first container that meet the service targetPort as endpoints get populated for that service
you can see from here, the second is never exposed.
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/pod/util.go#L28-L50

**Comment by smarterclayton** [comment]
That seems pretty reasonable.  Ports are first come, first serve on a shared IP.

Given this could be in the wild tightening validation here is potentially breaking.

**Comment by wackxu** [comment]
If user want to expose the second container as service in this way, he never get what he want, I think we should prevent user from using same portName in all container of pod.

**Comment by liggitt** [comment]
> If user want to expose the second container as service in this way, he never get what he want

As long as that pod util function continues to return a single port number for a single port name, you are correct, routing this way won't work.

It is possible, API-wise, to make the endpoints controller propagate both ports to the Endpoints object, though I'm not sure whether the networking layer would be happy routing that way (one service IP:port routing to multiple ports on the same pod IP)... I'll let @thockin weigh in on that.

Numeric routing still works fine with the subsequent container ports. Creating this:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: busy
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: http
    name: named-port
  - port: 123
    protocol: TCP
    targetPort: 80
    name: numbered-port-80
  - port: 234
    protocol: TCP
    targetPort: 81
    name: numbered-port-81
  selector:
    service: busy
---
apiVersion: v1
kind: Pod
metadata:
  generateName: busybox-
  labels:
    service: busy
spec:
  containers:
  - command: ["sh", "-c", "sleep 100000"]
    image: busybox
    name: busybox
    ports:
    - containerPort: 81
      name: http
      protocol: TCP
  - command: ["sh", "-c", "sleep 100000"]
    image: busybox
    name: busybox2
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
```

results in endpoints with:

```yaml
subsets:
- addresses:
  - ip: 172.17.0.3
    nodeName: 127.0.0.1
    targetRef:
      kind: Pod
      name: busybox-8kfwq
      namespace: default
      resourceVersion: "1743"
      uid: d55696c9-bde5-11e7-810e-08002711a3cf
  - ip: 172.17.0.4
    nodeName: 127.0.0.1
    targetRef:
      kind: Pod
      name: busybox-kdqdq
      namespace: default
      resourceVersion: "1752"
      uid: d6618426-bde5-11e7-810e-08002711a3cf
  ports:
  - name: numbered-port-81
    port: 81
    protocol: TCP
  - name: named-port
    port: 81
    protocol: TCP
  - name: numbered-port-80
    port: 80
    protocol: TCP
```

As you point out, the named port only routes to the first pod port, but both numeric ports route as expected.

> I think we should prevent user from using same portName in all container of pod.

If this were green-field, I'd agree with you, but since it doesn't break anything, invalidating known existing data and all the known problems that causes is not worth the change.
