### ISSUE TITLE
kubelet: lifecycle hooks can't write to termination message file

### ISSUE THREAD

**Issue by stevekuznetsov** [kubernetes/kubernetes#54247]
**What happened**:
I wrote a `preStop` hook and wanted to see the output of it, even if it succeeded. I therefore set the `pod.spec.containers.terminationMessagePath` to a file and wrote to that file in the hook.

**What you expected to happen**:
I expected what I wrote to the file to be exposed in the pod status message once it terminated.

**How to reproduce it (as minimally and precisely as possible)**:

Create this pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - command:
    - /bin/sh
    args:
    - -c
    - 'echo command > /tmp/log'
    image: busybox
    name: test
    terminationMessagePath: /tmp/log
    terminationMessagePolicy: File
    lifecycle:
      preStop:
        exec:
          command:
          - '/bin/sh'
          - '-c'
          - 'echo hook > /tmp/log'
  restartPolicy: Never
```

Run this:
```sh
$ kubectl create -f /tmp/pod.yaml
pod "test" created
$ kubectl get pod test -o jsonpath='{.status.containerStatuses[?(@.name=="test")].state.terminated.message}'
command
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0+695f48a16f", GitCommit:"d2e5420", GitTreeState:"clean", BuildDate:"2017-08-31T19:30:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0+695f48a16f", GitCommit:"d2e5420", GitTreeState:"clean", BuildDate:"2017-08-30T13:35:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug
/cc @smarterclayton 
/sig node

**Comment by stevekuznetsov** [comment]
Alternatively @vishh @kargakis we need a way to see the output of hooks even if they don't fail. Otherwise using them is pretty frustrating.

**Comment by smarterclayton** [comment]
Did you try to write to /dev/stdout?

Not sure if that will work in a prestop

I expected the write to work, it's possible we're gathering the termination
message too early.



On Oct 19, 2017, at 7:35 PM, Steve Kuznetsov <notifications@github.com>
wrote:

Alternatively @vishh <https://github.com/vishh> @kargakis
<https://github.com/kargakis> we need a way to see the output of hooks even
if they don't fail. Otherwise using them is pretty frustrating.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/54247#issuecomment-337981238>,
or mute the thread

**Comment by stevekuznetsov** [comment]
Using:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - command:
    - /bin/sh
    args:
    - -c
    - 'echo command'
    image: busybox
    name: test
    lifecycle:
      preStop:
        exec:
          command:
          - '/bin/sh'
          - '-c'
          - 'echo hook > /dev/stdout'
  restartPolicy: Never
```

```sh
$ kubectl create -f /tmp/pod.yaml
pod "test" created
$ kubectl logs pod/test
command
```

**Comment by stevekuznetsov** [comment]
Unless you meant to use `/dev/stdout` as the termination message path...


```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - command:
    - /bin/sh
    args:
    - -c
    - 'echo command > /dev/stdout'
    image: busybox
    name: test
    terminationMessagePath: /dev/stdout
    terminationMessagePolicy: File
    lifecycle:
      preStop:
        exec:
          command:
          - '/bin/sh'
          - '-c'
          - 'echo hook > /dev/stdout'
  restartPolicy: Never
```

```sh
$ kubectl create -f /tmp/pod.yaml
pod "test" created
$ kubectl get pod test -o jsonpath='{.status.containerStatuses[?(@.name=="test")].state.terminated.message}'
command
```

**Comment by stevekuznetsov** [comment]
@kubernetes/sig-node-bugs

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale
@kubernetes/sig-node-bugs

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale
@kubernetes/sig-node-bugs

**Comment by erkolson** [comment]
Stumbled upon this today.  Very surprised to see that stdout from the hook does not end up in the pods log stream?

**Comment by Nilubkal** [comment]
i cant get a the message even if write to /dev/termination-log ?

**Comment by stevekuznetsov** [comment]
/remove-lifecycle stale
@kubernetes/sig-node-bugs

**Comment by AlexanderYastrebov** [comment]
> Alternatively @vishh @kargakis we need a way to see the output of hooks even if they don't fail. Otherwise using them is pretty frustrating.
> Did you try to write to /dev/stdout?

`/dev/stdout` is a symlink to `/proc/self/fd/1` which would be `sh` stdout.

Redirect into PID 1 stdout ends up in the application logs:
```yaml
lifecycle:
  preStop:
    exec:
      command:
      - sh
      - -c
      - echo hook 1>/proc/1/fd/1
```
