### ISSUE TITLE
Authentication for webhook admission to heterogenous authentication domains

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#54404]
Like other existing webhooks in kubernetes, the admission webhooks need to be able to authenticate to systems in different authentication domains.  This is true for all API servers, kube-apiserver and extension apiserver alike.  Here's a picture.

![img_20171023_070323](https://user-images.githubusercontent.com/8225098/31887687-4c6ef8b6-b7c7-11e7-8d59-cdd1cea79fbe.jpg)

To achieve this and maintain consistency with our other webhooks like authentication and authorization, we can produce a kubeconfig file with authentication stanza names that are patterns.  `foo.bar.svc` matches `foo.bar.svc`.  `*.b.svc` matches `a.b.svc` and `c.d.svc`.  `*` is effectively the default for everything.  This creates a file like this which any server can use to configure how it will authenticate to webhooks.

```yaml
apiVersion: v1
users:
- name: *
- name: kubernetes.default.svc
  user:
    token: SA-token or other in cluster config
- name: *.b.svc
  user:
    token: differet-token
- name: foo.bar.svc
  user:
    client-certificate-data: <data>
    client-key-data: <data>
```

@kubernetes/sig-auth-api-reviews @deads2k @ericchiang @liggitt  in particular
@kubernetes/sig-api-machinery-pr-reviews @lavalamp @caesarxuchao @sttts @cheftako
