### ISSUE TITLE
Incorrect/missing SELinux labeling when using ConfigMap subPath

### ISSUE THREAD

**Issue by thoraxe** [kubernetes/kubernetes#54487]
/kind bug

**What happened**:
https://github.com/openshift/origin/issues/16951

##### Version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server XXX
openshift v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7

##### Steps To Reproduce
1. Create a configMap: 
  ```
  apiVersion: v1
  data:
    hello.txt: This is a test file
  kind: ConfigMap
  metadata:
    name: myconfig
  ```          
2. Deploy a test pod, e.g. redis, and edit the deploymentConfig yaml to have:
  ```
  volumes:
    - configMap:
        name: myconfig
      name: myconfig
  ....
  containers:
    - volumeMounts:
      - mountPath: /var/lib/hello.txt
        name: myconfig
        subPath: hello.txt
  ```
3. `oc rsh` into the pod and `cd /var/lib/` and notice how hello.txt can't be read:
  ```
  ls -lah                                                                                                                                                           
  ls: cannot access hello.txt: Permission denied       
  ```

**What you expected to happen**:
File access should be permitted.

**How to reproduce it (as minimally and precisely as possible)**:
See the "what happened".

**Anything else we need to know?**:
This appears to also be an issue with Origin 3.7 (I experienced), but I have not tried to reproduce with pure kube.

Looking at https://github.com/openshift/origin/issues/16951#issuecomment-338747116 it appears that there is an issue with either the way the ConfigMap file is labeled on the host, or how that label is passing through into the container.

cc: @rhatdan @pweil-
