### ISSUE TITLE
Pods moving from Succeeded to Pending

### ISSUE THREAD

**Issue by sjenning** [kubernetes/kubernetes#54499]
After https://github.com/kubernetes/kubernetes/pull/53233, we observed pods moving from phase `Succeeded` to `Pending`.  Presents on master and release-1.8 as it was picked in https://github.com/kubernetes/kubernetes/pull/53422

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - command:
    - bash
    - -c
    - trap 'excode=$?; trap "" EXIT; cmd; echo $excode' EXIT HUP INT QUIT PIPE TERM;
      sleep 5
    env:
    image: centos:centos7
    imagePullPolicy: IfNotPresent
    name: test-container 
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
```
test script
```
kubectl create -f pod.yaml; sleep 3; kubectl delete -f pod.yaml
```
`oc` has an `observe` command for basically doing a CLI watch
```
oc observe pods --output=gotemplate -a '{{.}}' | grep phase
```
or you can look in the kubelet log to see the phase transition from `Succeeded` to `Pending`

Thanks to @joelsmith @frobware for helping isolate this :+1: 

@dashpole @derekwaynecarr @smarterclayton 

/sig node
