### ISSUE TITLE
`livenessProbe` need support multiple `httpGet`

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#54547]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
I can only define `livenessProbe` with one `httpGet`, but sometimes I need to check multiple ports to make sure my app is running, so it is better enable `livenessProbe` can support multiple `httpGet`.

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: gcr.io/google_containers/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: X-Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
```

I know that I can call the cmd of `curl url1 && curl url2 && curl url3` to check the liveness of my app, but I cannot guarantee that there always have `curl` in the container.

/sig api-machinery

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
