### ISSUE TITLE
kubectl describe svc print wrong format of targetPort

### ISSUE THREAD

**Issue by wackxu** [kubernetes/kubernetes#54546]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

 when using  `kubectl describe svc `, the TargetPort is wrong 

```
TargetPort  %!d(*string=port1)/TCP
```

**What you expected to happen**:

if the targetPort is string, show the name correctly.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by grodrigues3** [comment]
@kubernetes/sig-cli-bugs

**Comment by tianshapjq** [comment]
@wackxu could you paste more details about the Kubernetes Version and the yaml you used to create the service? I tried to reproduce this error but it worked fine in my environment.

**Comment by wackxu** [comment]
@tianshapjq use the master branch.

yaml
```
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    name: redis
  ports:
  - protocol: TCP
    port: 80
    targetPort: port1
```
output
```
Name:              my-service
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          name=redis
Type:              ClusterIP
IP:                10.105.39.53
Port:              <unset>  80/TCP
TargetPort:        %!d(string=port1)/TCP
Endpoints:         192.168.166.154:6379
Session Affinity:  None
Events:            <none>
```
