### ISSUE TITLE
Statefulset with storage should select PVCs existed rather than only dynamic provide

### ISSUE THREAD

**Issue by wangxinxu411** [kubernetes/kubernetes#54555]
> Uncomment only one, leave it on its own line: 
>
> /kind bug
 /kind feature

**What happened**:
create a Statefulset : 
```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: appname
  labels:
    ekos-application: aaaa
    ekos-service: fdsafdsa
    log-ignore: "false"
    stateful: exclusive
    type: service
spec:
  replicas: 2
  selector:
    matchLabels:
      ekos-application: aaaa
      ekos-service: fdsafdsa
      type: service
  serviceName: dfsdfs
  template:
     metadata:
       name: dfsdfsdd
       labels:
        ekos-application: aaaa
        ekos-service: fdsafdsa
        log-ignore: "false"
        type: service
        version: "1"
     spec:
      containers:
      - image: registry.ekos.local/library/hello:latest
        imagePullPolicy: Always
        name: containername
        resources:
          limits:
            cpu: 125m
            memory: 64M
          requests:
            cpu: 62m
            memory: 32M
        volumeMounts:
            - name: vctname
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: appname
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Mi
      #selector:
       #matchLabels:
          #foo: foo
      storageClassName: test
```
Accoding to the instruction that we only use volumeClaimTemplates direction if we want to use storage of statefulset pod.No matter use storageClassName to dynamic provide PV or use selector matchLabels,k8s always create a PVC
**What you expected to happen**:
use PVCs existed rather than only dynamic provide
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
