### ISSUE TITLE
azureFile volume mode too strict for container with non root user

### ISSUE THREAD

**Issue by lrills** [kubernetes/kubernetes#54610]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Using azureFile volume after 1.8.x mount the share onto host with both dir_mode and file_mode options set to 0700, which was changed in this commit.
https://github.com/kubernetes/kubernetes/commit/4378c7ae8eb94b47db31b9846bf72a0e2e020270#diff-b99f7ac20a1bc605e253dfde484cee68

This disallow any container run with non root user (which is the suggested way to run app) to access the contents.

**What you expected to happen**:

The mode should at least set to 755 or even 777, which seem to be fine since we can still configure `accessMode` of volume or `readOnly` of volumeMount.

**How to reproduce it (as minimally and precisely as possible)**:

Use azureFile at 1.8.x up versions.

**Anything else we need to know?**:

https://github.com/kubernetes/kubernetes/pull/45337 might solve this too, but closed :(

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Bare metal on Azure VM
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2
- Kernel (e.g. `uname -a`): Linux  #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by andyzhangx** [comment]
I would like to set the mode as 777, @cosmincojocar let me know your concern about this, thx.

**Comment by cosmincojocar** [comment]
@andyzhangx Should any user from the container have full `rwx` access by default to the volume? I think is a bit too permissive. The default value could be concisely overwritten by the `mountOptions` when the permissions are too strict. Also the `readOnly` option is set by default to false if not specified. 

In general, I would go by default with `least privileged access`, and provide the option to increase the privileges when required.

**Comment by andyzhangx** [comment]
@rootfs does storage class support mountOptions in v1.8?
From the doc: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options-1
it's already supported, but I never make it work for azure disk and azure file, below is my config:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hdd
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: Standard_LRS
  kind: Shared
  mountOptions: "dir_mode=0777,file_mode=0750"
```

**Comment by rootfs** [comment]
apparently no :)

Need to get mount options by calling MountOptionFromSpec [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_dd/azure_dd.go#L178)
and join to PV options [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_dd/azure_mounter.go#L95-L109)

**Comment by andyzhangx** [comment]
while for azure file, it's already joining:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_file/azure_file.go#L229

point is it says **invalid** for `volume plugin kubernetes.io/azure-file`

```
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  ProvisioningFailed  4s    persistentvolume-controller  Failed to provision volume with StorageClass "azurefile": invalid option "mountOptions" for volume plugin kubernetes.io/azure-file

```

**Comment by andyzhangx** [comment]
sorry, correct format should be like this, azure file is provisioned successfully:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0750"
parameters:
  skuName: Standard_LRS
  location: westus2
```

**Comment by andyzhangx** [comment]
@rootfs so currently azure file/disk does not support mountMounts, I would create a task to support it, seems like it's only a little code change. :)

**Comment by andyzhangx** [comment]
@lrills @dixudx I have a #54674 for this, use mount options in storage class, below is an example:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0377
  - file_mode=0350
parameters:
  skuName: Standard_LRS
  location: westus2
```

**Comment by kontainerschiff** [comment]
IT's a real show-stopper using Azurefile! Like any rails app using non-root uid will not be able to Access root-only mounts (like phusion / passenger). 

I hope this get's fixed soon to add fsgroup properly! It's also very weird that also chown within container is not able to Change ownership of an azure file cifs mount Point!

**Comment by andyzhangx** [comment]
Hi @kontainerschiff, fsgroup could be set by k8s security context, is that what you want?
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod

**Comment by kontainerschiff** [comment]
Thanks for the hint, but this ist not working for azurefiles Volume, because it's not a usual PVC and a dedicated Volume mount Parameter, without the possible of fsgroup and fsuid. Would be trivial to fix, because it's a regular cifs 3.0 mount in the Background...

**Comment by andyzhangx** [comment]
@kontainerschiff you can set uid, gid in mountOptions, the code is already in v1.9.0, you can set file_mode and dir_mode in mountOptions too, see below example:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
```

**Comment by kontainerschiff** [comment]
Thanks a lot. But this storage class is not used..
volumes:
      - name: azure
        azureFile:

**Comment by andyzhangx** [comment]
I have cherry-pick this mountOptions feature to v1.8, see: https://github.com/kubernetes/kubernetes/pull/56384
Seems you are using azure file static provisioning, here is an example:
https://github.com/andyzhangx/Demo/blob/master/linux/azurefile/azurefile-mountoptions.md#set-mountoptions-in-static-provisioning-for-azure-file-support-from-v150
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: k8stest
    readOnly: false
  mountOptions:
    - dir_mode=0731
    - file_mode=0724
    - uid=1000
    - gid=1000
```

BTW, set the dir_mode & file_mode as 0700 is really too strict, customers complain this a lot. I am planing to change it, which value would you suggest 0744? Thanks.

**Comment by kontainerschiff** [comment]
AWESOME, working perfectly now!! I really appreciate your immediate Feedback.
I owe you a beer, next time you visit Germany (Hamburg) ! :-)
I'd the challenge to set set uid & guid to 0777 to my share that the rails app was working properly, which I've to figure out. 
I'd recommend to go with 0744 as Default Settings!

GREAT COMMUNITY SUPPORT, thanks a lot!!
Rgds, Gerald aka Kontainerschiff

**Comment by andyzhangx** [comment]
@kontainerschiff I am happy that it works on your side. Your encourage would be my power!! Germany is in my traveling list :-)

**Comment by Ilyes-Hammadi** [comment]
Same problem here, still get dir_mode=0700 and file_mode0700 when using K8s storage class with azure file. When inspecting the PV I see that the storage class has passed the correct mountOptions that are dir_mode=0777 and file_mode=0777, but when the volume is mounted, it's being mounted with dir_mode=0700 and file_mode0700.

### Environment:
- `kubectl version 1.8.3`
- Cloud provider `Azure`
- Service `aks`

**Comment by andyzhangx** [comment]
Hi @Ilyes-Hammadi , I just did a check, PR https://github.com/kubernetes/kubernetes/pull/56384/ has already into v1.8, while it's not in v1.8.3 or v1.8.4, I guess it would be into v1.8.5

**Comment by andyzhangx** [comment]
@Ilyes-Hammadi and in v1.8.3, azure file code would ignore mountOptions in strorage class,  mountOptions would be really used from v1.8.5

**Comment by Ilyes-Hammadi** [comment]
@andyzhangx Thanks for the info, that's good to know so that I can skip using Azure file plugin for now. 😄👍

**Comment by mcops** [comment]
It#s really a mess. I just upgraded to 1.8.4 and file_mode only mounts 0700 instead of necessary 0777.
I'm on Azure Container Services,so now 1.8.5 upgrade possibility :-(

**Comment by mcops** [comment]
I'm in production in 1.8.4 and have to switch back...this is a nightmare...

**Comment by mcops** [comment]
BTW: 1.8.2 was working !

**Comment by andyzhangx** [comment]
@mcops 1.8.2 is working? I have checked the code, it's still using 0700, If you are using v1.8.x, I would suggest you to use v1.8.5, it would support mountOptions. 0700 is really too restrict, I have created a [PR](https://github.com/kubernetes/kubernetes/pull/56551) to set as 0755.

**Comment by mcops** [comment]
well..1.8.5 still not available for ACS-engine ...therefore no upgrade on my cluster.

**Comment by tamxdx** [comment]
I'm using azureFile in my deployment yaml, but it does not have symbolic link support. I've read that I need to include "mfsymlinks" in my CIFS mount command..  

sudo mount -t cifs //<your-storage-acc-name>.file.core.windows.net/<storage-file-share-name> /media/shared -o vers=3.0,username=<storage-account-name>,password='<storage-account-key>',dir_mode=0777,file_mode=0777,mfsymlinks

so how would I define this under mountOptions? Or ???

**Comment by andyzhangx** [comment]
- for dyanmic provisioning, using:
https://github.com/andyzhangx/demo/blob/master/pv/storageclass-azurefile-mountoptions.yaml
 - for static provisioning, using:
https://github.com/andyzhangx/demo/blob/master/pv/pv-azurefile-mountoptions.yaml

mount options support of azure file is available from **v1.8.5**

**Comment by tamxdx** [comment]
thanks andyzhangx! that did it.

**Comment by andyzhangx** [comment]
hi guys, I am thinking add `mfsymlinks` as default mountoptions into azurefile mount, thus to support symbolic link in azurefile mount, let me know your thoughts, thx
@jdumars

**Comment by jdumars** [comment]
@khenidak PTAL ^^

**Comment by andyzhangx** [comment]
@arsalans looks like I need to document this somewhere, you still need to use PV/PVC to set mountOptions:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: k8stest
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: pv-azurefile  
---
kind: Pod
apiVersion: v1
metadata:
  name: azure
spec:
  containers:
  - image: kubernetes/pause
    name: azure
    volumeMounts:
    - name: azure
      mountPath: /mnt/azure
  volumes:
  - name: azure
    persistentVolumeClaim:
      claimName: pvc-azurefile
```

**Comment by andyzhangx** [comment]
@neilpeterson would you add the above doc? Thanks.

**Comment by arsalans** [comment]
@andyzhangx Hi, I was wondering, what does this size mean in kubernetes?

```
 resources:
     requests:
       storage: 5Gi
```

I created a 5TB file share on Azure, should this need to match and it should be 5TB or 5Ti?

**Comment by andyzhangx** [comment]
@arsalans if you are using PVC/PV matching, storage size is only for matching in PVC bounding process, the actual size could be different than `resources.requests.storage`; while if you use dynamic provision of azure file, k8s will create a 5TB file share for you.

**Comment by zffocussss** [comment]
> @arsalans if you are using PVC/PV matching, storage size is only for matching in PVC bounding process, the actual size could be different than `resources.requests.storage`; while if you use dynamic provision of azure file, k8s will create a 5TB file share for you.

@andyzhangx ,Hi andy,I come from AKS documents.I have a question like @arsalans .please see the below configuration
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: aksshare
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi

```
If I have set up an azure file share which quota is 1G on azure storage service,how much capacity should I specify in the PV defination or storage in PVC.I am confusing about the actual size of mount data.
there are three size.
1. the real size(quota) in azure file share
2.capacity in PV
3.storage in PVC

please help me understand.
