### ISSUE TITLE
kubectl apply view-last-applied incorrectly parses %s in the output and replaces with %!s(MISSING)

### ISSUE THREAD

**Issue by gburiola** [kubernetes/kubernetes#54645]
**BUG REPORT**:
/kind bug

**What happened**:

`kubectl apply view-last-applied deploy NAME` is incorrectly parsing `%s` in the output and replacing it with `%!s(MISSING)`

This only happens with `kubectl apply view-last-applied`.
`kubectl describe` and `kubectl get` correctly show `%s`

**How to reproduce it (as minimally and precisely as possible)**:

Apply manifest below:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app
        args:
          - -random_flag=%s@domain.com
```

Notice the `%s` in the `args` field.

```
$ kubectl apply -f /tmp/deploy.yaml
deployment "app-deployment" configured
```

Viewing the args with `kubectl get` works fine:

```
$ kubectl get deploy app-deployment -o json | \
  jq .spec.template.spec.containers[].args
[
  "-random_flag=%s@domain.com"
]
```

Using `get` to view `last-applied-configuration` also shows the right thing:

```
kubectl get deploy app-deployment -o json | \
  jq -r .metadata.annotations.'"kubectl.kubernetes.io/last-applied-configuration"' | \
  jq .spec.template.spec.containers[].args
[
  "-random_flag=%s@domain.com"
]
```

Using `kubectl apply view-last-applied` incorrectly replaces `%s` in the output with `%!s(MISSING)`

```
$ kubectl apply view-last-applied deploy app-deployment
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations: {}
  name: app-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - args:
        - -random_flag=%!s(MISSING)@domain.com
        image: app
        name: app
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
GKE running v1.7.6
