### ISSUE TITLE
API server accepts invalid api versions for resources

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#54697]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

/area api 
/area apiserver 
/kind bug 
/sig api-machinery

**What happened**:

I was able to apply a daemonset (works for others as well) with an invalid api version
```
kind: DaemonSet
apiVersion: extensions/v2beta1
```

```
kind: DaemonSet
apiVersion: extensions/v2beta2
```

**What you expected to happen**:

An error should be returned. 

**How to reproduce it (as minimally and precisely as possible)**:

Apply an update to a resource with an incorrect version like above.

**Anything else we need to know?**:

The api version on the object stored is correct but this could cause problems down the road if you accidentally start using a newer version when it becomes available.
```
$ kubectl -n kube-system get ds canal -oyaml
apiVersion: extensions/v1beta1
kind: DaemonSet
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.x

**Comment by lavalamp** [comment]
What exact commands did you use? Did you use kubectl or call the api directly?

cc @jennybuckley

**Comment by lavalamp** [comment]
Also, what (exact) version of kubectl and apiserver?

**Comment by liggitt** [comment]
To recreate:

1. `kubectl apply -f ...` a normal extensions/v1beta1 DaemonSet. The object is created:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"DaemonSet","metadata":{"annotations":{},"name":"prometheus-node-exporter","namespace":"default"},"spec":{"template":{"metadata":{"labels":{"daemon":"prom-node-exp"},"name":"prometheus-node-exporter"},"spec":{"containers":[{"image":"prom/prometheus","name":"c","ports":[{"containerPort":9090,"hostPort":9090,"name":"serverport"}]}]}}}}
  creationTimestamp: 2017-10-31T05:01:33Z
...
```

2. `kubectl apply -f ...` the same file edited to be a bogus `extensions/v1beta2`. The object is fetched from the server at
```
/apis/extensions/v1beta1/namespaces/default/daemonsets/prometheus-node-exporter
```
This patch is sent by kubectl and accepted by the API server:
```
{"apiVersion":"extensions/v1beta2","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"extensions/v1beta2\",\"kind\":\"DaemonSet\",\"metadata\":{\"annotations\":{},\"name\":\"prometheus-node-exporter\",\"namespace\":\"default\"},\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"daemon\":\"prom-node-exp\"},\"name\":\"prometheus-node-exporter\"},\"spec\":{\"containers\":[{\"image\":\"prom/prometheus\",\"name\":\"c\",\"ports\":[{\"containerPort\":9090,\"hostPort\":9090,\"name\":\"serverport\"}]}]}}}}\n"}}}
```

There's at least a couple bugs here:

1. `kubectl apply` fetches a different version for comparing with the on-disk version. I'd expect it to fetch the version specified in the file and fail when the server reports that version is not available - @kubernetes/sig-cli-bugs 
2. I would not expect the API server to accept a patch that changes the kind or apiVersion of an object (since the type is already known in the API server patch handler, the kind and apiVersion are just getting decoded, ignored, then overwritten when getting converted back into the serialized form for etcd)
