### ISSUE TITLE
Stateful set miscalculates used quota

### ISSUE THREAD

**Issue by mishamo** [kubernetes/kubernetes#54789]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Statefulset cluster does not complete deployment

**What you expected to happen**:
Statefulset cluster to roll out successfully

**How to reproduce it (as minimally and precisely as possible)**:
 - Quota set up on a namespace with a hard limit of 300m cpu (and 3900Mi memory).
 - Apply the following minimal statefulset:
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: somename
  namespace: somenamespace
spec:
  serviceName: "someservice"
  replicas: 3
  template:
    metadata:
      labels:
        app: somename
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: someservice
        image: alpine:3.6 
        command:
        - /bin/sh
        - -c
        - |
          echo "Do nothing"
          while true; do
            sleep 1
          done
        resources:
          requests:
            cpu: 100m
            memory: 1300Mi
          limits:
            memory: 1300Mi
```
 - Sometimes this rolls out successfully, but most times it will stop after the first or second pod and send out the following event: 
```
forbidden: exceeded quota: quota, requested: requests.cpu=100m, used: requests.cpu=300m, limited: requests.cpu=300m
```

**Anything else we need to know?**:
 - It seems that this can be manually fixed by deleting one of the pods; the deployment then continues with reclaimed resources.
 - `--show-all` does not show any extra pods using resources.

**Environment**:
- Kubernetes version (use `kubectl version`): Reproduced with `1.6.9` and `1.7.8`
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): 
```
/etc # cat os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.6.2
PRETTY_NAME="Alpine Linux v3.6"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```
- Kernel (e.g. `uname -a`): `/ # uname -a
Linux kafka-0 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 Linux`
- Install tools: Custom Ansible
- Others:
