### ISSUE TITLE
Unable to delete Job with initContainers

### ISSUE THREAD

**Issue by mattmoor** [kubernetes/kubernetes#54816]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

See: https://groups.google.com/forum/#!topic/kubernetes-users/YVmUgktoqtI

**What you expected to happen**:

The Job to be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

I was using an initContainer to `git clone` a repo.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:35:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:  Container Engine
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by matthiasr** [comment]
Was this job created with the same combination of versions? Can you reproduce the issue or was it a one-off? 

If you can reproduce it with these versions, can you is you upgrade the client to the newest 1.7.x? With upgrading the client to 1.8.x? If you can, with both server and client upgraded? (with minikube?)

**Comment by mattmoor** [comment]
I haven't touched the cluster/client since, so definitely those version.  It happened twice (before I switched to `gitRepo` volumes).

I believe I'm on the latest version of the cluster Container Engine supports, but given that I couldn't delete these previously I wasn't exactly eager to fill my cluster with them! :)

I can post back once GKE is on 1.8.x, or if I have a chance to put together a portable `yaml` you can just `curl ... | kubectl create -f -` to reproduce.

**Comment by mattmoor** [comment]
This was enough for me to repro it (perhaps it can be reduced further):
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: undeletable
spec:
  template:
    metadata:
      name: undeletable
    spec:
      restartPolicy: Never
      initContainers:
      - name: foo
        image: busybox
        command: ['/bin/sh', '-c', 'echo foo']
        workingDir: /workspace/
        volumeMounts:
        - mountPath: /workspace
          name: workspace
      containers:
      - name: bar
        image: busybox
        command: ['/bin/sh', '-c', 'echo bar']
        workingDir: /workspace/
        volumeMounts:
        - mountPath: /workspace
          name: workspace
      volumes:
      - name: workspace
        emptyDir: {}
```

The volumes are necessary, without them it deletes just fine.

**Comment by lavalamp** [comment]
/assign @mml 

...to verify it's not api machinery (we think it's not).

**Comment by yliaog** [comment]
cc @yliaog

**Comment by mml** [comment]
I can't reproduce this on master `v1.7.11-gke.1` (using a kubectl from head).

/sig apps
/cc @erictune 
/cc @janetkuo 
/unassign

**Comment by janetkuo** [comment]
Copying from the thread https://groups.google.com/forum/#!topic/kubernetes-users/YVmUgktoqtI:
> `error: Scaling the resource failed with: Job.batch "build-app" is invalid: spec.template: Invalid value: api.PodTemplateSpec...`

@mattmoor would you paste the full error message? It's crucial for debugging.

**Comment by darend** [comment]
We are also running into this issue with **1.8.7**

**Kubernetes Version**
```sh
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Job Spec**
```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: init-job-test-app
    job: init-job-test
  name: init-job-test-app
  namespace: sagan
spec:
  template:
    metadata:
      name: init-job-test
    spec:
      containers:
      - args:
        - ls
        - -l
        image: alpine
        imagePullPolicy: Always
        name: no-op
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      initContainers:
      - args:
        - ls
        -  -l
        image: alpine
        imagePullPolicy: Always
        name: init-ls
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
```

**Error** when deleting job

> ~ $ kubectl delete job init-job-test-app
> error: Scaling the resource failed with: Job.batch "init-job-test-app" is invalid: spec.template: Invalid value: api.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"init-job-test", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"controller-uid":"413ea864-0524-11e8-b476-02133ca1ad94", "job-name":"init-job-test-app"}, Annotations:map[string]string{"pod.alpha.kubernetes.io/init-containers":"[{\"name\":\"init-ls\",\"image\":\"alpine\",\"args\":[\"ls\",\"-l\"],\"resources\":{},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"Always\"}]", "pod.beta.kubernetes.io/init-containers":"[{\"name\":\"init-ls\",\"image\":\"alpine\",\"args\":[\"ls\",\"-l\"],\"resources\":{},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\",\"imagePullPolicy\":\"Always\"}]"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), InitContainers:[]api.Container{api.Container{Name:"init-ls", Image:"alpine", Command:[]string(nil), Args:[]string{"ls", "-l"}, WorkingDir:"", Ports:[]api.ContainerPort(nil), EnvFrom:[]api.EnvFromSource(nil), Env:[]api.EnvVar(nil), Resources:api.ResourceRequirements{Limits:api.ResourceList(nil), Requests:api.ResourceList(nil)}, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.Probe)(nil), ReadinessProbe:(*api.Probe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"Always", SecurityContext:(*api.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, Containers:[]api.Container{api.Container{Name:"no-op", Image:"alpine", Command:[]string(nil), Args:[]string{"ls", "-l"}, WorkingDir:"", Ports:[]api.ContainerPort(nil), EnvFrom:[]api.EnvFromSource(nil), Env:[]api.EnvVar(nil), Resources:api.ResourceRequirements{Limits:api.ResourceList(nil), Requests:api.ResourceList(nil)}, VolumeMounts:[]api.VolumeMount(nil), LivenessProbe:(*api.Probe)(nil), ReadinessProbe:(*api.Probe)(nil), Lifecycle:(*api.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"Always", SecurityContext:(*api.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc424935d18), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc42630df80), ImagePullSecrets:[]api.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*api.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]api.Toleration(nil), HostAliases:[]api.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil)}}: field is immutable; Current resource version 691714
>
