### ISSUE TITLE
I want to connect my service..

### ISSUE THREAD

**Issue by dockerPractice** [kubernetes/kubernetes#54832]
/kind bug
/sig kubernetes
/sig node

**What happened**:
It can't be connected to be made my service on Web browser.

**What you expected to happen**:
Connect to my service

**How to reproduce it (as minimally and precisely as possible)**:
First, I made 'my-deploy.yaml' like this.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: my-deploy-name
spec:
 replicas: 3
 template:
  metadata:
   labels:
    app: my-deploy
  spec:
   containers:
   - name: mycontainer
     image: alicek106/composetest:balanced_web
     ports:
     - containerPort: 80
```
And then, I made 'my-service.yaml' like this
```
apiVersion: v1
kind: Service
metadata:
 name: my-service-name
spec:
 ports:
  - name: my-deploy-svc
    port: 8080
    targetPort: 80
 type: LoadBalancer
 externalIPs:
  - 104.196.161.33
 selector:
  app: my-deploy
```
So, I created the deployment and service,
```
NAME              TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)          AGE
kubernetes        ClusterIP      10.96.0.1       <none>           443/TCP          6d
my-service-name   LoadBalancer   10.106.31.254   104.196.161.33   8080:32508/TCP   5d
```
```
NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
my-deploy-name     3         3         3            3           6d
```
 and try to connect 104.196.161.33:8080 , 104.196.161.33:32508 on Chrome Browser. But It doesn't work.
What should I do?

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: VM on ubuntu 16.04.LTS

- OS (e.g. from /etc/os-release): ubuntu 16.04.LTS

- Kernel (e.g. `uname -a`): Linux master 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: Docker-CE v17.06
- Others:
```
# kubectl get node
NAME      STATUS    ROLES     AGE       VERSION
master    Ready     master    6d        v1.8.1
node1     Ready     <none>    6d        v1.8.1
node2     Ready     <none>    6d        v1.8.1
```

```
# ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:ba:93:a2:f2
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ens160    Link encap:Ethernet  HWaddr 00:50:56:80:ab:14
          inet addr:39.119.118.176  Bcast:39.119.118.255  Mask:255.255.255.128
          inet6 addr: fe80::250:56ff:fe80:ab14/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9581474 errors:0 dropped:473 overruns:0 frame:0
          TX packets:4928331 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1528509917 (1.5 GB)  TX bytes:4020347835 (4.0 GB)

flannel.1 Link encap:Ethernet  HWaddr c6:b5:ef:90:ea:8f
          inet addr:10.244.0.0  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:184 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:44750027 errors:0 dropped:0 overruns:0 frame:0
          TX packets:44750027 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:13786966091 (13.7 GB)  TX bytes:13786966091 (13.7 GB)
```

※ P.S : Could you recommend the Web service example on docker & kubernetes to me?
