### ISSUE TITLE
kube-apiserver crashes when patching a NodePort service with two ports

### ISSUE THREAD

**Issue by tristanpemble** [kubernetes/kubernetes#54898]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Re-applying a NodePort service that has two ports fails and crashes the API server:

```
λ kubectl apply -f repro.yaml
deployment "hello-world" created
service "hello-world" created

λ kubectl apply -f repro.yaml
deployment "hello-world" configured
error: error when applying patch:
{}
to:
&{0xc420f01380 0xc420273ce0 default hello-world repro.yaml 0xc420f4a480 0xc420f4a698 1051 false}
for: "repro.yaml": Patch https://192.168.99.100:8443/api/v1/namespaces/default/services/hello-world: unexpected EOF
```

**What you expected to happen**:

Do not crash, service is configured correctly.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: tutum/hello-world
          ports:
            - name: web
              containerPort: 80
              protocol: UDP
            - name: web-tcp
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - name: web
      protocol: UDP
      port: 80
      nodePort: 31234
    - name: web-tcp
      protocol: TCP
      port: 80
      nodePort: 31234
```

```bash
kubectl apply -f ./repro.yaml
kubectl apply -f ./repro.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-11-01T00:49:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `minikube version: v0.23.0` on VBox provider in macOS
- OS (e.g. from /etc/os-release): macOS/Minikube
- Kernel (e.g. `uname -a`): `Linux minikube 4.9.13 #1 SMP Thu Oct 19 17:14:00 UTC 2017 x86_64 GNU/Linux`
- Install tools:
- Others:
