### ISSUE TITLE
[feature] for GPU and hugepages, default must match defaultRequest in LimitRange if both are specified

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/kubernetes#54917]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature request

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
As far, GPU and hugepages are particular resources which reqiure limits must equal to requests.
But this rule may be broken when creating LimitRange, LimitRange with different values in default and defaultRequest can be created successfully, which would cause error in creating pods afterwards.
We should not leave this error to pod creation but tell the users when creating the LimitRange.

**What you expected to happen**:
Validate if values are proper for GPU and hugepages when creating LimitRange.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create LimitRange with the following yaml:
```
apiVersion: v1
kind: LimitRange
metadata:
  name: default-test
spec:
  limits:
   default:
      hugepages-2Mi: 40Mi
      alpha.kubernetes.io/nvidia-gpu: 3
    defaultRequest:
      hugepages-2Mi: 30Mi
      alpha.kubernetes.io/nvidia-gpu: 2
    type: Container
```

2. Create pods with the following yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
   image: tomcat_java:v10.0
    command:
     /home/test.sh
    name: example
    volumeMounts:
     mountPath: /hugepages
      name: hugepage
  volumes:
   name: hugepage
    emptyDir:
      medium: HugePages
```

3. It would prompt error like:
```
The Pod "test" is invalid:
spec.containers[0].resources.requests: Invalid value: "2": must be equal to alpha.kubernetes.io/nvidia-gpu limit
spec.containers[0].resources.requests: Invalid value: "30Mi": must be equal to alpha.kubernetes.io/nvidia-gpu limit
```
maybe we should let this error happen in creating LimitRange.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.1879+d9459270770143", GitCommit:"d94592707701438fece7ab7e49ea9e6a90fe7993", GitTreeState:"clean", BuildDate:"2017-11-01T07:53:05Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.1879+d9459270770143", GitCommit:"d94592707701438fece7ab7e49ea9e6a90fe7993", GitTreeState:"clean", BuildDate:"2017-11-01T07:50:07Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @derekwaynecarr @vishh would this a possible feature?
