### ISSUE TITLE
not able to create a pods out of the replication controller

### ISSUE THREAD

**Issue by satyamsah** [kubernetes/kubernetes#54944]
I followed  kubenetes deployment from

https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

http-rc .yml is replicaiton controller file:

```
apiVersion: v1

kind: ReplicationController

metadata:

name: http-rc

spec:

replicas: 7

selector:

app: hello-world
template:

metadata:

  labels:

app: hello-world

spec:

  containers:

  - name: hello-ctr

    image: httpd

    ports:

    - containerPort: 8080

```
and started as : kubectl create -f rc.yml

output is :
`replicationcontroller "http-rc" created`

But even after few minutes , I am getting no preogres:

NAME DESIRED CURRENT READY AGE
http-rc       7               0         0        3m
