### ISSUE TITLE
Cluster autoscaler scales up too much

### ISSUE THREAD

**Issue by kevincvlam** [kubernetes/kubernetes#54959]
/kind bug
**What happened**:
I created a Alpha Google Container Engine cluster with two nodepools. One of the nodepools uses an instance-template that has a Tesla K80 GPU and installs nvidia drivers using a start-up script. 

The nodepool with the GPU, (GPU Nodepool) had auto-scaling enabled, with a minimum number of nodes of 1 and maximum of 3.

I had 1 node up from the GPU nodepool and scheduled 2 pods requesting 1 GPU each. The autoscaler brought up 2 addition nodes for the GPU nodepool, instead of just one. 

**What you expected to happen**:
The autoscaler brought up extra nodes for the GPU nodepool, this is bad because it costs money and any extra nodes are only brought down after 10+ minutes.

**How to reproduce it (as minimally and precisely as possible)**:
Create an Alpha Google Container Engine cluster with a GPU-enabled nodepool. The nodepool should use an instance group with a GPU and a start-up script that installs drivers and makes the GPU available as kubernetes resource, eg.

```
curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
dpkg -i cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
apt-get update && apt-get install cuda -y
NVIDIA_GPU_NAME=$(nvidia-smi --query-gpu=gpu_name --format=csv,noheader --id=0 | sed -e 's/ /-/g')
source /etc/default/kubelet
KUBELET_OPTS="$KUBELET_OPTS --node-labels='alpha.kubernetes.io/nvidia-gpu-name=$NVIDIA_GPU_NAME'"
echo "KUBELET_OPTS=$KUBELET_OPTS" > /etc/default/kubelet
systemctl restart kubelet.service
```

Enable auto-scaling on the nodepool and set the min=1 and max=4. Create only one instance of the instance group and schedule trigger scaling-up with a tensorflow deployment:

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorflow-gpu
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tensorflow-gpu
    spec:
      volumes:
      - hostPath:
          path: /usr/lib/nvidia-384/bin
        name: bin
      - hostPath:
          path: /usr/lib/nvidia-384
        name: lib
      containers:
      - name: tensorflow
        image: tensorflow/tensorflow:latest-gpu
        ports:
        - containerPort: 8888
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
---
apiVersion: v1
kind: Service
metadata:
  name: tensorflow-gpu-service
  labels:
    app: tensorflow-gpu
spec:
  selector:
    app: tensorflow-gpu
  ports:
  - port: 8888
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer
--- 
```

Should observe that the auto-scaler creates more nodes than needed. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Google Container Engine

- OS (e.g. from /etc/os-release):
ubuntu-gke-1604-lts

- Kernel (e.g. `uname -a`):
Linux gke-my-gpu-cluster-gpu-pool-7cb293cd-31tz 4.4.0-1027-gke #27-Ubuntu SMP Thu Aug 10 13:13:08 UTC 2017 x86_64 x
