### ISSUE TITLE
StatefulSet pulls image from docker hub instead of internal registry

### ISSUE THREAD

**Issue by dsfranzi** [kubernetes/kubernetes#55003]
/kind bug

**What happened**:

I'm using Kubernetes 1.5 in OpenShift.
I pushed all my customized docker images to OpenShift's internal registry. When using a DeploymentConfig, everything works fine, kubernetes pulls the right image.

When using a StatefulSet, Kubernetes won't find my docker image in the internal registry and instead pulls an image from docker hub.

My StatefulSet:

```
        spec:
          containers:
            - image: zookeeper:latest
              args:
                - bin/zkServer.sh
                - 'start-foreground'
```

It would work when i put the internal registry URL in front of the image name like this:

`image: 172.30.158.156:5000/<projectname>/zookeeper:latest`

But when I'm working with multiple clusters, this isn't practical (and again, it works with DeploymentConfigs)

**What you expected to happen**:

I expected the same behavior as with DeploymentConfigs: That kubernetes would pull the image from the internal registry.

**How to reproduce it (as minimally and precisely as possible)**:

Change a `DeploymentConfig` using an internal image to a `StatefulSet`.

**Environment**:

```
$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://master.*********:443
openshift v1.5.0
kubernetes v1.5.2+43a9be4
```
