### ISSUE TITLE
container hostname not set properly for Pods using hostNetwork

### ISSUE THREAD

**Issue by filipnowakswissre** [kubernetes/kubernetes#55404]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

For Pods using hostNetwork container names are set to the hostname of the node itself.
I observed this behavior for "bare" Pods and StatefulSets.

**What you expected to happen**:

In case of StatefulSet, even with hostNetwork feature being in use, I would expect the containers to have hostname matching: $(statefulset name)-$(ordinal) (as advertised here: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id).

hostname of the container would preserve its identity, and it would be possible to resolve it to the IP (in my case external) of the node at the same time.

If this is expected behavior, good thing would be to have a note in StatefulSet documentation (or / and hostNetwork feature maybe), and something like "canonical workaroud" for it.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  hostNetwork: true
```
or
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
```
Those are basically examples from the k8s documentation, slightly tweaked (nginx stripped from the volume mount / claim) and with hostNetwork set to true.

**Anything else we need to know?**:

In the dump of the configuration (in case of StatefulSet), "hostname" in "spec" has proper value, in case of nginx manifest I shared above: "web-0"

My use-case or final effect I am searching for is similar or even the same as described here:

https://github.com/kubernetes/kubernetes/issues/52084

I can work-around this problem currently, but it might be a problem later.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0+coreos.0", GitCommit:"a65654ef5b593ac19fbfaf33b1a1873c0320353b", GitTreeState:"clean", BuildDate:"2017-09-29T21:51:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0+coreos.0", GitCommit:"a65654ef5b593ac19fbfaf33b1a1873c0320353b", GitTreeState:"clean", BuildDate:"2017-09-29T21:51:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}  
- Cloud provider or hardware configuration:
bare-metal / VMs
- OS (e.g. from /etc/os-release):
Ubuntu 16.04.3 LTS
- Kernel (e.g. `uname -a`):
Linux xxxxx 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
Kubespray (current version, as of Thu Nov 9)
- Others:

/area stateful-apps
/sig apps
