### ISSUE TITLE
Network policy for allowing access only to public internet

### ISSUE THREAD

**Issue by itajaja** [kubernetes/kubernetes#55406]
Kubernetes version: 1.8

I am using kubernetes to run third party untrusted code in isolation. I'd like these pods to only have access to the public internet. in order to do so, I have an Egress network policy with the following rule:

```yml
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.16.0.0/16  # block access to VPC CIDR
          - 100.64.0.0/10  # block access to kubernetes non masquerade CIDR
```

The problem with this is that I can't resolve public addresses like `google.com` because the pod doesn't have access to kube-dns. One approach would be to whitelist the kubedns pod but It doesn't look like that's enough (address doesn't get resolved anyway). another workaround would be to change the `/etc/resolv.conf` to point to a public dns (eg 8.8.8.8). I'd like to go with the former, but I am not sure how to make it work, and if that's possible at all. Since this seems to me like a very common use case for network policies, it might be worthwile to expand the docs with whatever solution comes out of this discussion.

**Comment by itajaja** [comment]
cc @kubernetes/sig-network-proposals

**Comment by caseydavenport** [comment]
@itajaja yeah, I think what you want to be able to do is allow to kubedns.

I think the best you could do right now is add another rule which allows DNS traffic to the kube-system namespace.

i.e.

Label your kube-system namespace:
```
kubectl label ns kube-system kube-system=true
```

Add another egress rule like this to your policy:

```
- namespaceSelector:
    matchLabels: {"kube-system": "true"}
  ports:
  - protocol: UDP
    port: 53
```

Note that this will allow DNS traffic to all pods in the kube-system namespace.

**Comment by caseydavenport** [comment]
This is another use-case for https://github.com/kubernetes/kubernetes/issues/50451, which would allow specifying both a `namepaceSelector` AND a `podSelector`

**Comment by itajaja** [comment]
I'd rather avoid that, since that would unnecessarily expose other kube-system services. Right now I am doing something like this in my pod definition:

```
  volumes:
  - name: job-dns-config
    configMap:
      name: job-dns-config

...
    volumeMounts:
    - mountPath: /etc/resolv.conf
      subPath: resolv.conf
      name: job-dns-config
```

where job-dns-config is a configmap which contains `resolv.conf='nameserver 8.8.8.8'`. It's not pretty but it's more restricting than the alternative. are there downsides to this?
