### ISSUE TITLE
Pod without an explicit CPU resource should not be created when ResourceQuota is enforced

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#55433]
/kind bug
/sign node

**What happened**:

Pod without any explicit cpu request/limit could be created when ResourceQuota define CPU and memory constraints.

**What you expected to happen**:

Pod creation should fail and ask for explicit CPU resources. It seems a default CPU resource of `100m` is assigned to the Pod, and that's likely allowing the Pod creation to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

Use this configuration file to create a ResourceQuota:

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
spec:
  hard:
    cpu: "10"
    memory: 6G
    pods: "12"
    replicationcontrollers: "3"
    services: "5"
    configmaps: "5"
```

The details are:

```
$ kubectl describe quota
Name:                   quota
Namespace:              default
Resource                Used  Hard
--------                ----  ----
configmaps              0     5
cpu                     0     10
memory                  0     6G
pods                    0     12
replicationcontrollers  0     3
services                1     5
```

Create a pod using this configuration file:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
```

Kubectl rightly gives the error:

```
Error from server (Forbidden): error when creating "templates/pod.yaml": pods "nginx-pod" is forbidden: failed quota: quota: must specify memory
```

Updated the configuration file to:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "200m"
      requests:
        memory: "100m"
    ports:
    - containerPort: 80
```

And now the pod could be successfully created.

Kubectl should ask for a CPU resource to be specified as well.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

AWS

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by arun-gupta** [comment]
This is still true even if `requests.cpu` is mentioned in the ResourceQuota. Seems like the default value of `spec.containers[].resources.requests.cpu` allows a Pod to be created without an explicit value.

This is contradictory to what is mentioned in the text at https://kubernetes.io/docs/concepts/policy/resource-quotas/#requests-vs-limits.

**Comment by lichuqiang** [comment]
The issue seems fixed in latest version.

I tried to create pod with the template without resource request and got:
```
Error from server (Forbidden): error when creating "quota-pod.yaml": pods "nginx-pod" is forbidden: failed quota: quota: must specify cpu,memory
```
and  template with resource request of memory:
```
Error from server (Forbidden): error when creating "quota-pod-withmem.yaml": pods "nginx-pod" is forbidden: failed quota: quota: must specify cpu
```

**Comment by arun-gupta** [comment]
The cluster was created using:

```
kops create cluster   \
--name example.cluster.k8s.local   \
--master-count 1   \
--node-count 3 \
--kubernetes-version 1.8.3  \
--zones $AWS_AVAILABILITY_ZONES   \
--yes
```

This is explained at https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/cluster-install#create-a-gossip-based-kubernetes-cluster.

More details about the cluster:

```
$ kubectl get nodes
NAME                             STATUS    ROLES     AGE       VERSION
ip-172-20-102-241.ec2.internal   Ready     node      6m        v1.8.3
ip-172-20-135-222.ec2.internal   Ready     node      6m        v1.8.3
ip-172-20-39-81.ec2.internal     Ready     master    8m        v1.8.3
ip-172-20-45-147.ec2.internal    Ready     node      6m        v1.8.3
```

I could still create the pod, and more details about the pod are at:

```
$ kubectl describe pods/nginx-pod2
Name:         nginx-pod2
Namespace:    default
Node:         ip-172-20-45-147.ec2.internal/172.20.45.147
Start Time:   Mon, 13 Nov 2017 13:06:30 -0800
Labels:       name=nginx-pod
Annotations:  kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container nginx
Status:       Running
IP:           100.96.3.3
Containers:
  nginx:
    Container ID:   docker://078c63f3d391c453963d9346b2fbc60169fd10fd3361e37b7cd5aec54dac3724
    Image:          nginx:latest
    Image ID:       docker-pullable://nginx@sha256:9fca103a62af6db7f188ac3376c60927db41f88b8d2354bf02d2290a672dc425
    Port:           80/TCP
    State:          Running
      Started:      Mon, 13 Nov 2017 13:06:35 -0800
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  200Mi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bl72g (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  default-token-bl72g:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-bl72g
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age   From                                    Message
  ----    ------                 ----  ----                                    -------
  Normal  Scheduled              1m    default-scheduler                       Successfully assigned nginx-pod2 to ip-172-20-45-147.ec2.internal
  Normal  SuccessfulMountVolume  1m    kubelet, ip-172-20-45-147.ec2.internal  MountVolume.SetUp succeeded for volume "default-token-bl72g"
  Normal  Pulling                1m    kubelet, ip-172-20-45-147.ec2.internal  pulling image "nginx:latest"
  Normal  Pulled                 1m    kubelet, ip-172-20-45-147.ec2.internal  Successfully pulled image "nginx:latest"
  Normal  Created                1m    kubelet, ip-172-20-45-147.ec2.internal  Created container
  Normal  Started                1m    kubelet, ip-172-20-45-147.ec2.internal  Started container
```

Where would I look for presets?

**Comment by MCLDG** [comment]
This seems to be fixed. With the following podspec I receive an error message asking to specify cpu:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "100Mi"
    ports:
    - containerPort: 80
```

> Error from server (Forbidden): error when creating "pod-memory.yaml": pods "nginx-pod" is forbidden: failed quota: quota: must specify cpu

With an updated podspec specifying cpu, the pod is created successfully:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
    ports:
    - containerPort: 80
```

> pod "nginx-pod" created

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
