### ISSUE TITLE
Interpolation of pod environment variable in args of another pod

### ISSUE THREAD

**Issue by pycaster** [kubernetes/kubernetes#55452]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> kind bug
> /kind feature

**What happened**:

I have jenkins service deployed to a it's own namespace. I have jnlp service deployed to it's own namespace as well but when I am trying to interpolate the kubernetes generated env variables of jenkins service in deployment (args) of jnlp, the interpolation is not behaving as expected.

**What you expected to happen**:

The args supplied to the container must interpolate variables.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy pod A.
2. In deployment of pod B, where the args are defined for the containers entrypoint, get kubernetes generated env variables of pod A.

**Anything else we need to know?**:

This is the deployment of jnlp pod,

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dp-jnlp
  namespace: jnlp
  labels:
    app: slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
      annotations:
        description: Deploy jnlp service to Kubernetes
        tags: slave
    spec:
      imagePullSecrets:
        - name: quay
      containers:
        - name: jnlp
          imagePullPolicy: Always
          image: quay/jenkins-jnlp:latest
          args: ["-master http://${SVC_JENKINS_SERVICE_HOST}:${SVC_JENKINS_SERVICE_PORT} -tunnel ${SVC_JNLP_SERVICE_HOST}:${SVC_JNLP_SERVICE_PORT} -executors 0 -username 'xxx' -password 'xxx'"]
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jnlp-slave-data
      volumes:
        - name: jnlp-slave-data
          emptyDir: {}
```

Here are the env variables seen inside jenkins pod,

```
JENKINS_SLAVE_AGENT_PORT=50000
SVC_JENKINS_SERVICE_HOST=10.233.17.99
SVC_JENKINS_PORT=tcp://10.233.17.99:80
LANG=C.UTF-8
HOSTNAME=dp-jenkins-6df5dbfb9b-9jq7x
JENKINS_UC=https://updates.jenkins.io
VAULT_TOKEN=xxxxxxxx
JAVA_HOME=/docker-java-home
TINI_SHA=6c41ec7d33e857d4779f14d9c74924cab0c7973485d2972419a3b7c7620ff5fd
TINI_VERSION=0.14.0
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.233.0.1
JAVA_VERSION=8u151
SVC_JENKINS_SERVICE_PORT_HTTP=80
KUBERNETES_PORT=tcp://10.233.0.1:443
PWD=/
HOME=/var/jenkins_home
COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
JENKINS_REF=/usr/share/jenkins/ref
JENKINS_HOME=/var/jenkins_home
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PORT=443
SVC_JENKINS_SERVICE_PORT=80
CA_CERTIFICATES_JAVA_VERSION=20170531+nmu1
SVC_JENKINS_PORT_80_TCP_PROTO=tcp
JAVA_DEBIAN_VERSION=8u151-b12-1~deb9u1
KUBERNETES_PORT_443_TCP=tcp://10.233.0.1:443
SVC_JENKINS_PORT_80_TCP_PORT=80
TERM=xterm
VAULT_ADDR=http://vault.example.com
SHLVL=1
KUBERNETES_SERVICE_PORT=443
SVC_JENKINS_PORT_80_TCP_ADDR=10.233.17.99
JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
JENKINS_VERSION=2.63
KUBERNETES_SERVICE_HOST=10.233.0.1
SVC_JENKINS_PORT_80_TCP=tcp://10.233.17.99:80
_=/usr/bin/env
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1+coreos.0", GitCommit:"59359d9fdce74738ac9a672d2f31e9a346c5cece", GitTreeState:"clean", BuildDate:"2017-10-12T21:53:13Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
vsphere
```

- OS (e.g. from /etc/os-release):
```
Ubuntu 16.04
```

- Kernel (e.g. `uname -a`):
```
Linux dp-jenkins-6df5dbfb9b-9jq7x 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 GNU/Linux
```

- Install tools:
- Others:
