### ISSUE TITLE
error: unable to decode "STDIN": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by roffe** [kubernetes/kubernetes#55464]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I ran `kubectl auth reconcile` on a yaml I have that contains the following snippet:

```yaml
...
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```
error: unable to decode "STDIN": no kind "APIService" is registered for version "apiregistration.k8s.io/v1beta1"

**What you expected to happen**:
Nothing on that specific part, but a reconcile on the roles above the --- (redacted from this post)

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl auth reconcile (-f) <file or stdin containing APIService above>`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
vm's in KVM
- OS (e.g. from /etc/os-release):
Container Linux by CoreOS stable (1520.8.0)
- Kernel (e.g. `uname -a`):
Linux 4.13.9-coreos #1 SMP Thu Oct 26 03:21:00 UTC 2017 x86_64 Common KVM processor GenuineIntel GNU/Linux
- Install tools:
- Others:
