### ISSUE TITLE
failed to register collectors for "/kubepods/podxxx/2b8ff9a3da84482d33e7cd7ce3xxx": failed to read config file "xxx" for config "xxx" : file "xxx" does not exist.

### ISSUE THREAD

**Issue by ikaven1024** [kubernetes/kubernetes#55526]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
i'm using k8s v1.8.1. and i want to collect custom metric by cadvisor. From source, i know i shall label the pod and put in a config file in the container.

i add a label  to my DaemonSet: 
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gpu-monitor-agent
spec:
  template:
    metadata:
      labels:
        io.cadvisor.metric.testing: "cadvisor_config.json"
    spec:
      containers:
      - name: agent
        image: gpu-monitor-agent:v0.1
        ...
```
and put a `cadvisor_config.json` in the container `/cadvisor_config.json`. But after i create it, kubelet reports:
```
failed to register collectors for "/kubepods/podxxx/2b8ff9a3da84482d33e7cd7ce3xxx": failed to read config file "xxx" for config "xxx" : file "xxx" does not exist.
```
i inspect the docker containers, and find no my labels in agent container, but it exists in pause container.
kublet is reading config file in pause container!

i don't known if i had done some wrong. help me,plz.

**What you expected to happen**:
collect custom metrics successfully.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.1
- Cloud provider or hardware configuration: VirtualMachine
- OS (e.g. from /etc/os-release): centos 7.2
- Kernel (e.g. `uname -a`): Linux yjh-dev 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others: docker 17.09.0-ce
