### ISSUE TITLE
mountPath mitigation in Linux pod

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#55540]
When user specify a windows mountPath, e.g. `D:`, there should be mitigation in pod when it's running on Linux otherwise pod mount would fail.
Below is an example, mountPath `D:` could be turned into `/D/` in linux pod

```
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-azuredisk
spec:
  containers:
  - image: nginx
    name: nginx-azuredisk
    volumeMounts:
    - name: disk01
      mountPath: 'D:'
  volumes:
  - name: disk01
    persistentVolumeClaim:
      claimName: pvc-azuredisk
```

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign
