### ISSUE TITLE
controller-manager panic when creating GCP service LBs

### ISSUE THREAD

**Issue by osoriano** [kubernetes/kubernetes#55544]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I created a service (type LoadBalancer) on a 1.8.3 cluster.

**What you expected to happen**:
A load balancer to be deployed to GCP

**How to reproduce it (as minimally and precisely as possible)**:
On a v1.8.3 cluster with GCP integration, deploy a service type LoadBalancer. The controller-manager was started with `--cloud-provider=gce`. However, `--cloud-config` was not specified. 

Example service:
```
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: ingress-nginx
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
```

**Anything else we need to know?**:
Stack trace captured in gist:
https://gist.github.com/osoriano/02977b3e47c08e1bbde625e2a498d75b

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.3
- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release): Ubuntu16
- Kernel (e.g. `uname -a`): 4.10.0-38-generic
- Install tools: Kubernetes-the-hard-way
- Others:
