### ISSUE TITLE
StatefulSet deletion leaves an orphan pod if the pod label has been changed

### ISSUE THREAD

**Issue by at1984z** [kubernetes/kubernetes#55559]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
1. StatefulSet at scale 3 is created with with a label defined in /spec/template/metadata/labels.
2. The label is changed to a different value for one of the StatefulSet pods.
3. StatefulSet is deleted with delete operation default options.
4. All pods are deleted save the one whose label was changed.
5. The orphan pod stays running forever.

**What you expected to happen**:
1. All pods will be deleted.

**How to reproduce it (as minimally and precisely as possible)**:
1. Define StatefulSet and the associated service in file sset.yaml:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "false"
  name: sset-svc
  labels:
    app: sset-svc
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: sset
  clusterIP: None
  selector:
    app: sset
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sset
spec:
  serviceName: sset-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: sset
        typ: a
    spec:
      containers:
      - name: a
        image: debian:jessie-slim
        command: ["/bin/bash", "-c", "sleep infinity"]
```
2. kubectl create -f sset.yaml
3. kubectl edit pod sset-2
4. change label "typ=b"
5. kubectl delete -f sset.yaml
6. observe that pod sset-2 keeps running.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.4
- Cloud provider or hardware configuration: Virtual machines with Vagrant 2.0.0 and VirtualBox 5.1.28-117968 on Intel(R) Xeon(R) CPU E5-2690 v3 24 cores with Ubuntu 16.04 LTS
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS (VM)
- Kernel (e.g. `uname -a`): 4.4.0-96-generic (VM)
- Install tools: kubeadm 1.7.4-00
- Others:
