### ISSUE TITLE
SELinux labels for new host devices are wrong

### ISSUE THREAD

**Issue by lorenz** [kubernetes/kubernetes#55756]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I ran an unprivileged pod with a HostPath CharDevice passthrough for `/dev/kvm` to run unprivileged accelerated VMs in there, but due to SELinux labeling issues QEMU can't access that device.

```
ls -lZ /dev/kvm
crw-rw----. 1 root 78 system_u:object_r:kvm_device_t:s0 10, 232 Nov  7 14:06 /dev/kvm
```

**What you expected to happen**:
Using Docker's `--device /dev/kvm` option, the following labels are applied and unprivileged access works:
```
ls -lZ /dev/kvm
crw-rw----. 1 root 78 system_u:object_r:svirt_lxc_file_t:s0:c448,c733 10, 232 Nov 15 02:49 /dev/kvm
```

**How to reproduce it (as minimally and precisely as possible)**:

Kubernetes 1.8+: 
```
kind: Job
apiVersion: batch/v1
metadata:
  name: kvm-test-job
spec:
  template:
    spec:
      containers:
      - name: kvm-test
        image: ubuntu:17.04
        command: ["/bin/ls", "-lZ","/dev/kvm"]
        volumeMounts:
        - name: kvm
          mountPath: /dev/kvm
      volumes:
      - name: kvm
        hostPath:
          path: /dev/kvm
          type: CharDevice
      restartPolicy: OnFailure
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2+coreos.0", GitCommit:"4c0769e81ab01f47eec6f34d7f1bb80873ae5c2b", GitTreeState:"clean", BuildDate:"2017-10-25T16:24:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
3 Bare-Metal nodes, Wireguard + OSPF Networking
- OS (e.g. from /etc/os-release): Container Linux by CoreOS 1520.8.0 (Ladybug)
- Kernel (e.g. `uname -a`): 4.13.9-coreos
- Install tools: DIY
- Others:
