### ISSUE TITLE
Azure disk: storage class should support the sku if the storage accout support it

### ISSUE THREAD

**Issue by weherdh** [kubernetes/kubernetes#55774]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Now for storage class only support skuName with Premium_LRS and Standard_LRS
Met error if the storage account was created with other sku. But actually it can work well without setting it

**What you expected to happen**:
skuName should support others if the storage account support it

**How to reproduce it (as minimally and precisely as possible)**:
Create a storage account which is using Standard_RAGRS sku. Create storage class as below:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scazure
parameters:
  location: eastus
  skuName: Standard_RAGRS
  storageAccount: storage
provisioner: kubernetes.io/azure-disk
```
Create pvc as below
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: scazure
  name: azpvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
PVC would never bind with below error:
Failed to provision volume with StorageClass "scazure": azureDisk - Standard_RAGRS is not supported sku/storageaccounttype. Supported values are [Premium_LRS Standard_LRS]

But if I remove the skuName parameter, the pvc could be bound 
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scazure
parameters:
  location: eastus
  storageAccount: storage
provisioner: kubernetes.io/azure-disk
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-11-12T02:22:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-11-12T02:22:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):  RHEL7
- Install tools: ansible
