### ISSUE TITLE
kube-proxy "panic: non-positive interval for NewTicker" when using ipvs mode & default values

### ISSUE THREAD

**Issue by roffe** [kubernetes/kubernetes#55886]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig network

**What happened**:
Default values for kube-proxy after saving values with --write-config-to are not sane and causes panic with stack trace on startup of kube-proxy

I discovered this after some initial trouble in https://github.com/kubernetes/kubernetes/issues/55864

here is the output of "kube-proxy --write-config-to"

```
apiVersion: componentconfig/v1alpha1
bindAddress: 0.0.0.0
clientConnection:
  acceptContentTypes: ""
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: ""
  qps: 5
clusterCIDR: ""
configSyncPeriod: 15m0s
conntrack:
  max: 0
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
enableProfiling: false
featureGates: ""
healthzBindAddress: 0.0.0.0:10256
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  minSyncPeriod: 0s
  scheduler: ""
  syncPeriod: 0s
kind: KubeProxyConfiguration
metricsBindAddress: 127.0.0.1:10249
mode: ""
oomScoreAdj: -999
portRange: ""
resourceContainer: /kube-proxy
udpTimeoutMilliseconds: 250ms
````
As we can see on iptables.syncPeriod it has a default of 30.
If one uses the default values and tries to enable IPVS mode kube-proxy will crash with a panic if the ipvs.syncPeriod is not adjusted to a positive number.

change values to 
```
featureGates:  SupportIPVSProxyMode=true
mode: ipvs
```
then try to start with --config pointing to that file.

**What you expected to happen**:
A warning that a zero value is not accepted and that the user should raise ` ipvs.syncPeriod` instead of a panic and stack trace.

**How to reproduce it (as minimally and precisely as possible)**:
Use default values for kube-proxy from `--write-config-to` with changes abobe and try to use ipvs mode.

````
I1116 12:50:34.062455       1 config.go:202] Starting service config controller
panic: non-positive interval for NewTicker

goroutine 46 [running]:
time.NewTicker(0x0, 0x8)
	/usr/local/go/src/time/tick.go:23 +0x1b4
k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).SyncLoop(0xc420a68f20)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:736 +0x33
k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run(0xc4208f9400, 0xc4208bb600, 0xc420208200)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:547 +0x480
k8s.io/kubernetes/cmd/kube-proxy/app.(*Options).Run(0xc420a37600, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:229 +0xa0
k8s.io/kubernetes/cmd/kube-proxy/app.NewProxyCommand.func1(0xc420314240, 0x9e02d70, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:344 +0x80
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420314240, 0xc420913fe0, 0x0, 0x2, 0xc420314240, 0xc420913fe0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420314240, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420314240, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.NewKubeProxy.func1(0xc42079d5c0, 0xc420913fe0, 0x0, 0x2, 0xc42014b020, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/kube-proxy.go:50 +0x68
main.(*HyperKube).Run.func1(0xc42079d680, 0xc42079d5c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:184 +0x6d
created by main.(*HyperKube).Run
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:185 +0x588
```

**Anything else we need to know?**:
Keep up the awesome work

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: virtual machines in proxmox
- OS (e.g. from /etc/os-release): Container Linux by CoreOS stable (1520.8.0)
- Kernel (e.g. `uname -a`): Linux kubemaster01 4.13.9-coreos #1 SMP Thu Oct 26 03:21:00 UTC 2017 x86_64 Common KVM processor GenuineIntel GNU/Linux
- Install tools: manual kubernetes deploy
- Others:
