### ISSUE TITLE
How to set "tokenTTL: <time duration>" in the kubeadm config file, num 0 do not permit?

### ISSUE THREAD

**Issue by KeithTt** [kubernetes/kubernetes#55962]
I followed these two pages:

https://kubernetes.io/docs/reference/generated/kubeadm/#config-file

https://kubernetes.io/docs/reference/generated/kubeadm/#manage-tokens

```
# kubeadm init --config=kubeadm-config.yml
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
unable to decode config from "kubeadm-config.yml" [v1alpha1.MasterConfiguration: TokenTTL: unmarshalerDecoder: time: invalid duration , parsing 416 ...okenTTL":0... at {"api":{"advertiseAddress":"192.168.5.105"},"apiServerCertSANs":["uy05-13","uy08-07","uy08-08","127.0.0.1","192.168.5.42","192.168.5.104","192.168.5.105"],"apiVersion":"kubeadm.k8s.io/v1alpha1","etcd":{"endpoints":["http://192.168.5.42:2379","http://192.168.5.104:2379","http://192.168.5.105:2379"]},"kind":"MasterConfiguration","kubernetesVersion":"v1.8.2","networking":{"podSubnet":"192.168.122.0/24"},"tokenTTL":0}]
```

Here is my configuration:
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: "192.168.5.105"
etcd:
  endpoints:
  - "http://192.168.5.42:2379"
  - "http://192.168.5.104:2379"
  - "http://192.168.5.105:2379"
kubernetesVersion: "v1.8.2"
apiServerCertSANs:
- uy05-13
- uy08-07
- uy08-08
- 127.0.0.1
- 192.168.5.42
- 192.168.5.104
- 192.168.5.105
tokenTTL: 0
networking:
  podSubnet: 192.168.122.0/24
```
