### ISSUE TITLE
Admin granted with privileged PodSecurityPolicy failed to create deployment in a namespace other than default

### ISSUE THREAD

**Issue by luckyfengyong** [kubernetes/kubernetes#55973]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
An admin user is granted with privileged PodSecurityPolicy which is defined as follow. The policy is also granted to the service accounts of the namespace of `default` as well. 

```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  allowedCapabilities:
    - AUDIT_CONTROL
    - AUDIT_WRITE
    - BLOCK_SUSPEND
    - CHOWN
    - DAC_OVERRIDE
    - DAC_READ_SEARCH
    - FOWNER
    - FSETID
    - IPC_LOCK
    - IPC_OWNER
    - KILL
    - LEASE
    - LINUX_IMMUTABLE
    - MAC_ADMIN
    - MAC_OVERRIDE
    - MKNOD
    - NET_ADMIN
    - NET_BIND_SERVICE
    - NET_BROADCAST
    - NET_RAW
    - SETGID
    - SETFCAP
    - SETPCAP
    - SETUID
    - SYS_ADMIN
    - SYS_BOOT
    - SYS_CHROOT
    - SYS_MODULE
    - SYS_NICE
    - SYS_PACCT
    - SYS_PTRACE
    - SYS_RAWIO
    - SYS_RESOURCE
    - SYS_TIME
    - SYS_TTY_CONFIG
    - SYSLOG
    - WAKE_ALARM
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
    -
      max: 65535
      min: 1
  privileged: true
  readOnlyRootFilesystem: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
- "*"
```

The admin user successfully create a deployment whose pod template requires `privileged: true` in `securityContext` into the namespace of `default`, however failed to create the deployment into the namespace of `test`. 

Following error messages are found in log file of kubernetes apiserver.

```
{"log":"I1117 06:21:55.766781       1 admission.go:128] getting pod security policies for pod  (generate: ma-myloggingg-ibm-icplogging-master-67cdbb666c-)\n","stream":"stderr","time":"2017-11-17T06:21:55.766955458Z"}
{"log":"I1117 06:21:55.766893       1 rbac.go:116] RBAC DENY: user \"system:serviceaccount:kube-system:replicaset-controller\" groups [\"system:serviceaccounts\" \"system:serviceaccounts:kube-system\" \"system:authenticated\"] cannot \"use\" resource \"podsecuritypolicies.extensions\" named \"privileged\" in namespace \"test\"\n","stream":"stderr","time":"2017-11-17T06:21:55.766977501Z"}
{"log":"I1117 06:21:55.766954       1 rbac.go:116] RBAC DENY: user \"system:serviceaccount:test:default\" groups [\"system:serviceaccounts\" \"system:serviceaccounts:test\"] cannot \"use\" resource \"podsecuritypolicies.extensions\" named \"privileged\" in namespace \"test\"\n","stream":"stderr","time":"2017-11-17T06:21:55.770097185Z"}
{"log":"I1117 06:21:55.767003       1 admission.go:344] validating pod  (generate: ma-myloggingg-ibm-icplogging-master-67cdbb666c-) against providers: default\n","stream":"stderr","time":"2017-11-17T06:21:55.770125296Z"}
{"log":"I1117 06:21:55.767080       1 admission.go:170] unable to validate pod  (generate: ma-myloggingg-ibm-icplogging-master-67cdbb666c-) against any pod security policy: [spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: \"IPC_LOCK\": capability may not be added]\n","stream":"stderr","time":"2017-11-17T06:21:55.770134035Z"}
```

It seems kubernetes is using the user account of `system:serviceaccount:kube-system:replicaset-controller` and `system:serviceaccount:test:default` to validate the PSP policy, instead of the user account who issue the kubernetes API.

The behavior is different from when user create pod directly. At that time, the user's account who issue the kubernetes API is used to validate the PSP policy

**What you expected to happen**:

Admin user should be able to deploy deployment in any namespace. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
