### ISSUE TITLE
Update to StatefulSet fails if size of PVC in volumeClaimTemplates == 1024Gi

### ISSUE THREAD

**Issue by josephglanville** [kubernetes/kubernetes#55982]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

Updating a StatefulSet with `kubectl apply -f statefulset.yaml` fails if the size of a PVC contained in `volumeClaimTemplates` is equal to `1024Gi`. Validation fails on DeepEquals as k8s has converted the value to `1Ti`.

**What you expected to happen**:
The update to succeed with no validation errors as `1024Gi` was the original value supplied.

**How to reproduce it (as minimally and precisely as possible)**:
Create a StatefulSet with `volumeClaimTemplates` like so:
```
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1024Gi
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.2
- Cloud provider or hardware configuration: GKE
