### ISSUE TITLE
Wired Problem with "NodePort" configuration

### ISSUE THREAD

**Issue by vistalba** [kubernetes/kubernetes#56017]
I'm trying to use squid and squidguard in kubernetes.

My config look as follwos:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: squidguard
    namespace: proxy
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: squidguard
        spec:
            volumes:
            - name: custom-config
              hostPath:
                path: "/path/squidguard/config"
            - name: log
              hostPath:
                path: "/path/squidguard/log"
            containers:
            - name: squidguard
              image: muenchhausen/docker-squidguard:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 3128
              - containerPort: 80
              volumeMounts:
              - mountPath: "/custom-config"
                name: custom-config
              - mountPath: "/var/log/squid3"
                name: log
              env:
              - name: SQUID_UID
                value: "1000"
              - name: SQUID_CONFIG_SOURCE
                value: "/custom-config"
              - name: UPDATE_BLACKLIST_URL
                value: "http://www.shallalist.de/Downloads/shallalist.tar.gz"
---
apiVersion: v1
kind: Service
metadata:
    name: squidguard
    namespace: proxy
spec:
    ports:
    - name: http
      port: 80
      targetPort: 80
    selector:
      app: squidguard
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: squidguard
    namespace: proxy
spec:
    rules:
    - host: proxy.internal.domain.com
      http:
        paths:
        - path: /
          backend:
            serviceName: squidguard
            servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: squidguard-np
  namespace: proxy
spec:
  type: NodePort
  ports:
    - port: 3128
      targetPort: 3128
      nodePort: 31280
  selector:
    name: squidguard
```

I use weave as overlay network. All other services working fine. One with "hostNetwork = true" and others over the traefik ingress controller on port 80 and 443.

Also my squidguard deployment is running and http (port 80) over ingress controller ist working fine.
If I try to connect to port 31280 it can't connect at all. 

Checked with tcpdump:

on cluster (physical interface): Can see my traffic to port 31280.
inside the pod: no traffic to port 31280 is comming.. see only traffic to port 80.

Someone has any idea? Maybe a misconfiguration on my yaml file?
Already "kubeadm reset" and "kubeadm init" to get a clean install. This doesn't help to solve the issue.

I'm sure someone here can give me a hint to solve my issue... :) Thanks a lot.
