### ISSUE TITLE
Pending pods with affinity rules looking for non-existing node

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kubernetes#56057]
/kind bug

**What happened**:

I upgraded a Kubernetes Engine cluster from 1.7.2 to 1.8.3-gke.0. All pods for deployments and statefulsets using a `podAntiAffinity` rule with `requiredDuringSchedulingIgnoredDuringExecution` stay pending with the following message

```
Warning  FailedScheduling  14s (x13037 over 2d)  default-scheduler  node 'gke-development-euro-auto-scaling-pre-33198d65-jtwt' not found
```

This node actually doesn't exist. And all pending pods show this same node name for the reason it's still pending.

As soon as I remove the affinity rules from a deployment or statefulset the pods are updated and running in no time.

One of the affinity settings I removed looked as follows:

```
     affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - grafana
            topologyKey: kubernetes.io/hostname            
```

After removing the affinity and getting the pods to run, adding the affinity rules again leads to pending pods again.

**What you expected to happen**:

Affinity rules to be respected and pods to be scheduled. The cluster has 13 n1-highmem-8 nodes, which is more then enough to schedule the pending pods.

```
NAME                                                  STATUS    ROLES     AGE       VERSION
gke-development-euro-auto-scaling-pre-33198d65-0jsc   Ready     <none>    1h        v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-22fq   Ready     <none>    5h        v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-23lq   Ready     <none>    16h       v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-365l   Ready     <none>    8h        v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-5prt   Ready     <none>    9h        v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-6n4k   Ready     <none>    4h        v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-8l69   Ready     <none>    4h        v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-8vz0   Ready     <none>    12h       v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-9qnb   Ready     <none>    9h        v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-d7pr   Ready     <none>    4h        v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-lgcq   Ready     <none>    41m       v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-wm6l   Ready     <none>    1h        v1.8.3-gke.0
gke-development-euro-auto-scaling-pre-33198d65-wxl2   Ready     <none>    12h       v1.8.3-gke.0
```

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure as I have other clusters running `1.8.3-gke.0` that don't exhibit the same issue.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
1.8.3-gke.0
```
- Cloud provider or hardware configuration: 
```
Google Cloud, zone europe-west1-c
```
- OS (e.g. from /etc/os-release):
```
BUILD_ID=9592.90.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=c0dda75c2c06905ff4a2e8b41de27d4f2d773856
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=60
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=60
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```
- Kernel (e.g. `uname -a`):
```
Linux gke-development-euro-auto-scaling-pre-33198d65-0jsc 4.4.64+ #1 SMP Wed Aug 30 20:27:36 PDT 2017 x86_64 In
tel(R) Xeon(R) CPU @ 2.50GHz GenuineIntel GNU/Linux
```

**Comment by bsalamat** [comment]
@JorritSalverda Have you enabled any alpha features in your cluster?

**Comment by bsalamat** [comment]
Could you also provide as much of your pods' config as possible?

**Comment by JorritSalverda** [comment]
The cluster has no alpha features enabled. It's going to be hard to provide config as the cluster is running 273 deployments, 8 statefulsets and 4 daemonsets.

However all of the pending applications have `podAntiAffinity` rules similar to:

```yaml
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - <app name>
        topologyKey: kubernetes.io/hostname
```
