### ISSUE TITLE
configmap cannot be mounted as a file

### ISSUE THREAD

**Issue by funkydorian** [kubernetes/kubernetes#56060]
/kind bug
/sig GCP
/area/configmap-api

**What happened**:
I have a configmap, but cannot map it as file to the container.

I have found similar issues #45000 #44815 #29297 but seems not helping my case...

Configmap:

kubectl get configmaps uploads-ini -o yaml

```
apiVersion: v1
data:
  uploads.ini: |-
    file_uploads = On
    memory_limit = 64M
    upload_max_filesize = 64M
    post_max_size = 64M
    max_execution_time = 600
kind: ConfigMap
metadata:
  creationTimestamp: 2017-11-16T10:48:09Z
  name: uploads-ini
  namespace: default
  resourceVersion: "1338"
  selfLink: /api/v1/namespaces/default/configmaps/uploads-ini
  uid: a2af8e4f-cabb-11e7-896b-42010a9a0157
```

Deploy YAML:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kloiacom-wpress
  labels:
    app: kloiacom-wpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kloiacom-wpress
  template:
    metadata:
      labels:
        app: kloiacom-wpress
    spec:
      containers:
        - image: wordpress
          name: kloiacom-wpress
          env:
          - name: WORDPRESS_DB_HOST
            value: mysql:3306
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
          - name: WORDPRESS_DB_NAME
            value: kloiacom
          ports:
            - containerPort: 80
              name: kloiacom-wpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            - name: uploads-ini
              mountPath: /usr/local/etc/php/conf.d/uploads.ini
              subPath: uploads.ini
      volumes:
        - name: wordpress-persistent-storage
          gcePersistentDisk:
            pdName: kloiacom-wordpress-disk
            fsType: ext4
        - name: uploads-ini
          configMap:
            name: upload-ini

```
Pod describe:

kubectl describe po kloiacom-wpress-3349396449-v1fth

```
Name:		kloiacom-wpress-3349396449-v1fth
Namespace:	default
Node:		gke-wpress-cluster-1-default-pool-28078aa6-83hw/10.154.0.4
Start Time:	Fri, 17 Nov 2017 17:13:46 +0000
Labels:		app=kloiacom-wpress
		pod-template-hash=3349396449
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"kloiacom-wpress-3349396449","uid":"ac05bb78-cbba-11e7-896b-42010...
		kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container kloiacom-wpress
Status:		Pending
IP:
Controllers:	ReplicaSet/kloiacom-wpress-3349396449
Containers:
  kloiacom-wpress:
    Container ID:
    Image:		wordpress
    Image ID:
    Port:		80/TCP
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Requests:
      cpu:	100m
    Environment:
      WORDPRESS_DB_HOST:	mysql:3306
      WORDPRESS_DB_PASSWORD:	<set to the key 'password' in secret 'mysql'>	Optional: false
      WORDPRESS_DB_NAME:	kloiacom
    Mounts:
      /usr/local/etc/php/conf.d/uploads.ini from uploads-ini (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c3qjg (ro)
      /var/www/html from wordpress-persistent-storage (rw)
Conditions:
  Type		Status
  Initialized 	True
  Ready 	False
  PodScheduled 	True
Volumes:
  uploads-ini:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	upload-ini
    Optional:	false
  wordpress-persistent-storage:
    Type:	GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:	kloiacom-wordpress-disk
    FSType:	ext4
    Partition:	0
    ReadOnly:	false
  default-token-c3qjg:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-c3qjg
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From								SubObjectPathType		Reason		Message
  ---------	--------	-----	----								---------------------	------		-------
  2d		2m		1995	kubelet, gke-wpress-cluster-1-default-pool-28078aa6-83hw			Warning		FailedMount	MountVolume.SetUp failed for volume "uploads-ini" : configmaps "upload-ini" not found
  2d		1m		1784	kubelet, gke-wpress-cluster-1-default-pool-28078aa6-83hw			Warning		FailedMount	Unable to mount volumes for pod "kloiacom-wpress-3349396449-v1fth_default(ac07e716-cbba-11e7-896b-42010a9a0157)": timeout expired waiting for volumes to attach/mount for pod "default"/"kloiacom-wpress-3349396449-v1fth". list of unattached/unmounted volumes=[uploads-ini]
  2d		1m		1784	kubelet, gke-wpress-cluster-1-default-pool-28078aa6-83hw			Warning		FailedSync	Error syncing pod
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

you can refer to https://github.com/kloia/wpress

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.8-gke.0
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release):  1.7.8-gke.0
- Kernel (e.g. `uname -a`): 1.7.8-gke.0
- Install tools: 1.7.8-gke.0
- Others:
