### ISSUE TITLE
Cannot connect different node's pod when using NetworkPolicy in weave-net

### ISSUE THREAD

**Issue by shun-miyoshi-com** [kubernetes/kubernetes#56133]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
I would like to control the communication to block communication from outside into special namespace.
So, I created the following network policy.

Default: Deny
Allow from 'type: local' to 'allow: local'
Allow from '*' to 'allow: public'

user.yaml
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: user1
  annotations:
    net.beta.kubernetes.io/network-policy: |
      {
        "ingress": {
          "isolation": "DefaultDeny"
        }
      }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-user1-local
  namespace: user1
spec:
  podSelector:
    matchLabels:
      allow: "local"
  ingress:
  - from:
    - podSelector:
        matchLabels:
          type: "local"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-user1-public
  namespace: user1
spec:
  podSelector:
    matchLabels:
      allow: "public"
  ingress:
  - {}
```

Then, I tested the connection, but it was failed.
The test process is follows.

I created nginx pod in node01.node.local which allow from 'type: local'
I created access-test pod in both node01 and node02.node.local.
Access test from node01.node.local is successful, but access test from node02.node.local was failed.
(PodInitializing was not finished.)

test.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: user1
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: user1
  labels:
    app: nginx
    allow: "local"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: node01.node.local
---
apiVersion: v1
kind: Pod
metadata:
  name: access-test-1
  namespace: user1
  labels:
    type: "local"
spec:
  initContainers:
  - name: access-test
    image: busybox
    command: ['sh', '-c', 'until wget nginx.user1.svc.cluster.local -O - > /dev/null; do sleep 5; done']
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  nodeSelector:
    kubernetes.io/hostname: node01.node.local
---
apiVersion: v1
kind: Pod
metadata:
  name: access-test-2
  namespace: user1
  labels:
    type: "local"
spec:
  initContainers:
  - name: access-test
    image: busybox
    command: ['sh', '-c', 'until wget nginx.user1.svc.cluster.local -O - > /dev/null; do sleep 5; done']
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  nodeSelector:
    kubernetes.io/hostname: node02.node.local
```

```
[root@kubemaster ~]# kubectl get pods -o wide -n user1
NAME            READY     STATUS     RESTARTS   AGE       IP          NODE
access-test-1   1/1       Running    0          38m       10.47.0.2   node01.node.local
access-test-2   0/1       Init:0/1   0          38m       10.44.0.6   node02.node.local
nginx           1/1       Running    0          38m       10.47.0.1   node01.node.local
```

When I removed this network policy(*1), both access test(node01 and node02) were successful(*2).
*1) edit nginx pod label [allow: "local"] to [allow: "public"]
*2) Pod was created successfully, but I found some points that I am concerned about.
    Pod access-test-1 is Running soon, but Pod access-test-2 takes time for Running.

```
[root@kubemaster ~]# kubectl get pods -o wide -n user1
NAME            READY     STATUS    RESTARTS   AGE       IP          NODE
access-test-1   1/1       Running   0          5m        10.47.0.2   node01.node.local
access-test-2   1/1       Running   0          5m        10.44.0.6   node02.node.local
nginx           1/1       Running   0          5m        10.47.0.1   node01.node.local

```

I don't know why such an error occurred, and I have no idea to solve this problem. 
I need your help.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS 7.4
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Others: network plugin: weave-net: 2.0.5

Thank you,

**Comment by shun-miyoshi-com** [comment]
Please help me to solve this issue.

**Comment by cmluciano** [comment]
cc @bboreham

**Comment by bboreham** [comment]
Weave Net 2.0.5 did not implement the `networking.k8s.io/v1` NetworkPolicy; that was added in 2.1.

Latest version is 2.1.3

**Comment by shun-miyoshi-com** [comment]
Thanks comment.
I upgraded weave-net from 2.0.5 to 2.1.3, but I still have this error.

**Comment by shun-miyoshi-com** [comment]
I encountered a strange issue..

I successfully access to nginx pod when I use IP address of nginx service instead of domain name(nginx.user1.svc.cluster.local)
Is this kube-dns bug? or CNI bug?

* yaml file
```
apiVersion: v1
kind: Pod
metadata:
  name: access-test-2
  namespace: user1
  labels:
    type: "local"
spec:
  initContainers:
  - name: access-test
    image: busybox
    command: ['sh', '-c', 'until wget 10.104.72.186 -O - > /dev/null; do sleep 5; done']
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  nodeSelector:
    kubernetes.io/hostname: node02.node.local
```

* result
```
[root@kubemaster ~]# kubectl get pods -n user-test -o wide
NAME            READY     STATUS    RESTARTS   AGE       IP           NODE
access-test-1   1/1       Running   0          22s       10.44.0.14   node01.node.local
access-test-2   1/1       Running   0          22s       10.36.0.3    node02.node.local
nginx           1/1       Running   0          58s       10.44.0.1    node01.node.local
```
