### ISSUE TITLE
Json Parse Error

### ISSUE THREAD

**Issue by bainim** [kubernetes/kubernetes#56215]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
Deploy nginx service using kubernetes
**What you expected to happen**:
I got this error:

Failed to download OpenAPI (the server could not find the requested ressource),falling back to swagger couldn't get version/kind ;json parse error: json: cannot unmarshal string into Go value of type struct* { APIVersion string "json:\"apiVersion,omitempty\"";kind string "json:\"kind,omitempty\""}

**How to reproduce it (as minimally and precisely as possible)**:
I execute this cmd:
*kubectl create -f nginx-pod.yaml*

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"xxxxxxxxxxxxx", GitTreeState:"clean", BuildDate:"xxxxxxxxx", GoVersion:"", Compiler:"", Plateform:""}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-rancher-1, GitCommit:"xxxxxxxxxxxx", GitTreeState:"clean", BuildDate:"xxxxxxxxx", GoVersion:"", Compiler:"", Plateform:""}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by knightXun** [comment]
I meet this error too. I use online yaml tools to validate my yaml, it parsed.
here is my yaml content:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwRENDQW95Z0F3SUJBZ0lVWm4vMVFid1FNSnFUWFd6b0t4elJwclA3eXA4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FqRUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVVTUJJR0ExVUVDeE1MWTJ4dmRXUnVZWFJwZG1VeEV6QVJCZ05WCkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1UY3dPREUyTURNeU5EQXdXaGNOTWpJd09ERTFNRE15TkRBd1dqQnEKTVFzd0NRWURWUVFHRXdKRFRqRVFNQTRHQTFVRUNCTUhRbVZwU21sdVp6RVFNQTRHQTFVRUJ4TUhRbVZwU21sdQpaekVNTUFvR0ExVUVDaE1EYXpoek1SUXdFZ1lEVlFRTEV3dGpiRzkxWkc1aGRHbDJaVEVUTUJFR0ExVUVBeE1LCmEzVmlaWEp1WlhSbGN6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtXUHdBOHcKVDU4R08rOU1nKzkrYkwydncvN3cwaFRQMFowa3hhbmcwR0dYdVNGVFR3SUVBWTlOQ2M5aWQvRk12SThyNFhsTgpDU0o1UHJYVDJUMW5yQlAycUZ5NkptRWo0K0IyUkFMZmpMY0pRZGk4Yk56K2RldG8yWGZONnpkYTdMVmdBY1RPCnpzYWovTjdPRldDaEc2RDdybm1INHUvU3pSYzl5STc0TitEWXZUanpMV1VWelNBMzV0QTFGNEhGaEt1ekM5RDgKcCtjdUhOdDFPaE8xS0FvRXdqdVlPZHY0THZLa2tmUWRwdmkzdXcxd0o4b3RSQUpHa094WkJMUE9vbkJQbFlPUApIeGc1SVNZQTN1cEZDaC9HNFBETmtDQXVtUUJsUzM4Y1c0WnRTM0ZvT1FydC9XME9NTTRPSjZVWUJMT0VuL3k2Cmw5L3NZQmxwa3RrWlhJOENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdIUVlEVlIwT0JCWUVGSnloYmFISkJyaXFrZUlkbnpCSTF2RzU3aUluTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQkx3bTVadkdONzNHSDN5VFhlSnpacU5CM3I1Y0RsWVg0OHg1V1I1N2NhbGh1NjA3V0ttS0VhCms1SklQL3F2M0JHMHhNYzB2b0RWalhndWRMSVliZEtzY3RsdHVxS3N5U3pCNytLV0l3eXFwUUNWV2dDajJXRkYKWkRyN2hqdFZ2RlJrQVJibU1pY0xoUE0wQnhMbkl2ZFJ3bmxWN3RFMTYvUS91Q1hZdG05bisyajRGazlrUlpOaAowMS9IL2syR3JrVWROSVpnMElXT1lHSHoxS2tkWllPbisrQzMzbGhYL0tDUmlGUDlUK3dLZUppQnJNS004V0N1CmwvWWJGcHlNSk0ySi9GSTFnRlgwSDg3NEhJSjNlRzlZWVZCbU5ScUpuWUQ5QWhZL2dBZ1dUS2NzOVp3YTZmYlUKUXV1YVFLMTdGZ1dGR1o2bUFyZ0Frd1R1cWY2c01oQk4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: http://10.1.1.23:8080
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:node:17.2.3.16
  name: system:node:17.2.3.16@kubernetes
current-context: system:node:17.2.3.16@kubernetes
kind: Config
preferences: {}
users:
- name: system:node:17.5.3.16
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ4VENDQXRtZ0F3SUJBZ0lVRUpoK3ZjV3R3NEgvUkpjNHhxT0ZLdjFSK2ZBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FqRUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVVTUJJR0ExVUVDeE1MWTJ4dmRXUnVZWFJwZG1VeEV6QVJCZ05WCkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1UY3dPREUyTVRFME16QXdXaGNOTWpjd09ERTBNVEUwTXpBd1dqQjYKTVFzd0NRWURWUVFHRXdKRFRqRVFNQTRHQTFVRUNCTUhRbVZwU21sdVp6RVFNQTRHQTFVRUJ4TUhRbVZwU21sdQpaekVWTUJNR0ExVUVDaE1NYzNsemRHVnRPbTV2WkdWek1SUXdFZ1lEVlFRTEV3dGpiRzkxWkc1aGRHbDJaVEVhCk1CZ0dBMVVFQXhNUmMzbHpkR1Z0T201dlpHVTZibTlrWlRFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEU3FFcHVFVGloQjYvMHg3VnRKWUM0aEpBenRMTmRxTkd0M1JySnVzREdpa0Z2clRWZgoraUl0VEZmREd6eGdyWHhobjYvWW50cTNzZ1QwaXJpNVdxZlZWZHQ1MTRxTFlmRlpqa0lwVGs1UzhISjQ4MnBiCmpzK1czaVQvS2tpeDI3MHRMOG4vakxhQmsweHRqWTBmR3hXcHdVeHFVekZITTl2KzEwbzVWU0k1cUFXVVdYNXQKZUhmZWNlcFg3MlIvcUlHMjYrWktldWQrcnRVUEMwTGhvdFJCYm1sOXF3WmRVOVMvVWJ6SnVVQ1AvVE1NSmpLaAplbnF1Tk9qTTJtTnJFdDlCQURHc2VtT29vQzR1ckVUdXJaTVZkN3VESjZGT0l5SzVPRGNhMWFNczQ2SDhGNldJCjRMN05rRUk2K1liOFhTWTBtY1RIWlAxQ0lKcjQ4cHdubnREcEFnTUJBQUdqZnpCOU1BNEdBMVVkRHdFQi93UUUKQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJdwpBREFkQmdOVkhRNEVGZ1FVdTV3U2s2WUpla3BUV3RKbS9xbHJzNVFnV0lJd0h3WURWUjBqQkJnd0ZvQVVuS0Z0Cm9ja0d1S3FSNGgyZk1Falc4Ym51SWljd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDRVdxNG11OHZRZWIwbmMKV3loaGIyUGtxSEk3ckRMbUpoVWRZcm1vaTF0aHVjb3dQWERTWlErMlpDYWdIMUpRL1dmOGxUOEMyRFF6RFZUaQowdDJxd242UFY2RllFNUVPYy8vUDJpbGNFRXcvWHA2bmx3YmtIaEJucmhaeFRwbldoeTU1ZjVSRE9rZ3k5MFMyCkhFd0NGZFdpVGFuTHpDNEprQS9QS3NwS3RCOC82TEpSSlpYaTBkRzZEeUE5bnZTS2J0aE11cHBVVkVLNUlZbkIKaFZIVXNUS0xUdkMxTTc4WHV5VEdteURvVFpnckI4S24vNmRTWEtEV1dzN0s0OHBxekFmRjdXTFUvbGVRZldUSQpHNVpZUVhEK3NrZlV1ck4vcVY3TXZ0OWtsNVpPNE84dDlSTGhNcEdLeUNGQ1BsbFdKV0FrdjJjTEN3QUlvQ3R3CmNDeUpMejA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMHFoS2JoRTRvUWV2OU1lMWJTV0F1SVNRTTdTelhhalJyZDBheWJyQXhvcEJiNjAxClgvb2lMVXhYd3hzOFlLMThZWit2Mko3YXQ3SUU5SXE0dVZxbjFWWGJlZGVLaTJIeFdZNUNLVTVPVXZCeWVQTnEKVzQ3UGx0NGsveXBJc2R1OUxTL0ovNHkyZ1pOTWJZMk5IeHNWcWNGTWFsTXhSelBiL3RkS09WVWlPYWdGbEZsKwpiWGgzM25IcVYrOWtmNmlCdHV2bVNucm5mcTdWRHd0QzRhTFVRVzVwZmFzR1hWUFV2MUc4eWJsQWovMHpEQ1l5Cm9YcDZyalRvek5wamF4TGZRUUF4ckhwanFLQXVMcXhFN3EyVEZYZTdneWVoVGlNaXVUZzNHdFdqTE9PaC9CZWwKaU9DK3paQkNPdm1HL0YwbU5KbkV4MlQ5UWlDYStQS2NKNTdRNlFJREFRQUJBb0lCQVFDRTRWdHg2ck1LQU10aApZTWgwdlA5aFpWMkJBQzlVbVRVS3N6bytuZXNVVWduTTVEbVMvVG1wMFVwYTdFYzl4TEY4OHpuOUx0ZFFvSjYzCmt2bkxFZ0JrZGZBbi8ycUpXWkxncHZmZERtUWh0VUxBUU91S0xaK016endQS1NFSjhFNTR2bmh4RnRYWkRvMWIKWGJyek1DYU9HanlWcFR5a2FYWVFYc1dYUExpR0hPMTRoMC9JRGlmaVFtQkl2TFMvNDhqV3MxbU40Z3V4Q1IvYgp5UnBqMytvbnRvUmhWemZubjVJTUF1bStpa1ppSWtINkRDZitVdUlFZm16NHl1RzJvYTJxZmRYaGVQOU5oU0ZoCjcwN01GNmk4SUQwcDhrUWZZM1VMTmYzRjJmY2V5d3dzOWlvazZJLzlQS09HaTRadXNnNHlGNUs0NzA0Tnh2T3AKTnhjTzRCbkJBb0dCQU4xYUxoNThESS9qZ1EzM3ljMGVTb0Jlb3Y5ZitQamc0TVNtdlk0a1ZwcEV4V01aWU43QwpqQlhJaGpSbXUweUt4c3FLckZXTHZqL0JUVnhzOVZERUhlNzNUZkhrK2cwSUxIK0Y0bTU1eFc3ZFZIUmlabm5JCmdNWHRGZnR1dnpGM2g2UWNvc0RheDJvOTNjdTZNck04c1lnbGRnN0xNM09sRE13MjRXMmwxL3dOQW9HQkFQT2gKamk1aHZndG1LRFRjTnZJdko1cjZvS0x3WVd5QkYxcURwTldIZFRWb0lreWR1L2RQVlY4aGQ5a2c1NjNZQnhpeAp2V3lRTk1LRmRoM1VmVEltaHU2dFFEUndWNGw5T2RuRDZGTkhCR1l2QkM3cDkyTm45azVYQUYyN2NtS1lDdk15ClpjT2tjbEwzQW4yZC9KS0tNRUdkcUFEakZyZTZuenJ0c2ZhYytzVk5Bb0dCQUlvcC92MkNPcWtadlhWRmhJM20KNldQbExtS3V1ZzVHOTZWbjJvdTl2TnpBTG1EajkyWTBFeEtKdnRNNGlKS0hVUHdkd09JSXZ2QzJySjRUV0xCWQpLY0wrVklXM2dpamVRRUE5QnBBa3JBcStWamZyTDhHMldFS3k4UFNuTk9vZ2pPYndCTnJSOUlVcEpxZENpdUQ3CjhtaGowYVA4VEJwVUhIL2ZoYWhXUzFHRkFvR0JBT0JaUHhMYkV5UndHRXBGRjV3QmJGazh2andOVzhtTlBySXQKVTljRi9Cc0lINzJwNnZPY2JLTkRzSmVUdzRURTBCUWZhSzNXUlo5elF3ZkpLdGpKdmF1QWd3VkhCblVuaWVSTQprVjVPb1hCdmoweWNTeUdSRkxHalVFVUFYaDhJbjl5LzVoSTVGc1hyakxHY2tIOXBIWEx1K1V5SDBkMnl6dnAyCjlGQ0MwakpwQW9HQVY4b0F4aXQ5bGg0bzB1SEM3VEMzUDRkbTRudWtTdjdXdk10Mk91c2NNdkpuSVorQjkvR1MKRXNhZnhrY3JhbmY0aGJOMUg0ZkJrTXJRcS9Gdy9IcTR0OFQycmV0OVorcUZ1ek9wYVphbGY0YmZkRHVoZmhqYQp4S0VTbnI4UzJkMG9RcTVxN1hUaDkzM0pFTUs3TE9Pa25CL29tMGhYb0R6dS9RSndoL25ucXlnPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

```
