### ISSUE TITLE
some doubts about hostpath checking when subpath exist

### ISSUE THREAD

**Issue by lcfang** [kubernetes/kubernetes#56339]
Pod will not run correctly  when I creat a pod like below:
**pod-test.yaml**
```
apiVersion: v1
kind: Pod
metadata:
  name: volum-subpath-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-extend
    volumeMounts:
    - mountPath: /test-volume
      name: extend-volume
      subPath: subpath
  volumes:
  - name: extend-volume
    hostPath:
      path: /tmp/test_extend/
```
 Here, the hostPath of `/tmp/test_extend/` is not exist in my host, and `subPath `is not empty, when I run `kubectl create -f pod-test.yaml`, the pod will not be created correctly.

`kubectl get pod--all-namespaces`
```
NAMESPACE     NAME                        READY     STATUSRESTARTS   AGE
default       volum-subpath-pd            0/1       CreateContainerConfigError0          2s
```

`kubectl describe pod volum-subpath-pd`
```
Events:
  Type     Reason                 Age              From                Message
  ----     ------                 ----             ----                -------
  Normal   Scheduled              2m               default-scheduler   Successfully assigned volum-subpath-pd to 127.0.0.1
  Normal   SuccessfulMountVolume  2m               kubelet, 127.0.0.1  MountVolume.SetUp succeeded for volume "extend-volume"
  Normal   SuccessfulMountVolume  2m               kubelet, 127.0.0.1  MountVolume.SetUp succeeded for volume "default-token-tkk47"
  Warning  Failed                 1m (x7 over 2m)  kubelet, 127.0.0.1  Error: lstat /tmp/test_extend/: no such file or directory
  Normal   Pulling                1m (x8 over 2m)  kubelet, 127.0.0.1  pulling image "gcr.io/google_containers/test-webserver"
  Normal   Pulled                 1m (x8 over 2m)  kubelet, 127.0.0.1  Successfully pulled image "gcr.io/google_containers/test-webserver"
```

In pkg/kubelet_pods.go, it will judge the hostpsth's existing if the subpath is not empty, and an error will  return if the hostpath is't exist.

We have authorized Docker to create hostpath if it is't exist, so I think the judgement here may not be reasonable because it will incur the bug like above, and also the handle of `os.MkdirAll(hostPath, perm)` in kubelet_pods.go. 

Three idear here I think:(1) authorize kubelet to create hostpath if it is't exist no matter the subpath empty or not (2)do the judgement either the subpath empty or not ,and return erro if hostpath is't exist (3)discard the judgement  here.

Environment:
- Kubernetes version : 1.9 (latest)
- OS: Ubuntu 14.04
- Docker version: 17.07.0
