### ISSUE TITLE
CR is stuck with "orphan" finalizer

### ISSUE THREAD

**Issue by rmohr** [kubernetes/kubernetes#56348]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

I have a CRD which is backed by a controller which creates and deletes other CRDs. The dependent CRDs have a controller owner reference set. If I delete the controller object with --cascade=true, everything works as expected and the resources are cleaned up. If I use --cascade=false, I see that an "orpan" finalizer is added. No owner references on one of the dependents is removed and the main object gets never deleted.

**What you expected to happen**:

I would have expected that the garbage collector removes the owner reference and then removes the "orphan" finalizer afterwards from the object, before finally deleting it.

Is that expected and the controller has to  remove the references and the "orphan" finalizer itself, or should the garbage collector do that? Do I have to set blockOrphanDeletion to false?

**How to reproduce it (as minimally and precisely as possible)**:

I delete it like this:
```
cluster/kubectl.sh delete mycrdcontroller mycrdinstance --cascade=false
```

The metadata of the controller object then looks like this:

```
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachineReplicaSet
metadata:
  creationTimestamp: 2017-11-24T12:44:54Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2017-11-24T12:45:02Z
  finalizers:
  - orphan
  name: testreplicaset2
  namespace: default
  resourceVersion: "24789"
  selfLink: /apis/kubevirt.io/v1alpha1/namespaces/default/virtualmachinereplicasets/testreplicaset2
  uid: 4555ee8e-d115-11e7-9842-525400c2f26a

```

Owner references are still there on the dependants:

```
apiVersion: kubevirt.io/v1alpha1
  kind: VirtualMachine
  metadata:
    creationTimestamp: 2017-11-24T12:57:04Z
    generateName: test1
    labels:
      kubevirt.io/nodeName: node0
      myvm: myvm2
    name: test1vxl5h
    namespace: default
    ownerReferences:
    - apiVersion: v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: VirtualMachineReplicaSet
      name: testreplicaset2
      uid: 4555ee8e-d115-11e7-9842-525400c2f26a
```

and nothing happens.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
