### ISSUE TITLE
Support process substitution for config set-cluster --certificate-authority

### ISSUE THREAD

**Issue by drnic** [kubernetes/kubernetes#56372]
/kind bug

**What happened**:

I attempted to use process substitution to pass my root certificate as a file descriptor to `--certificate-authority` flag:

```
kubectl config set-cluster "${deployment_name}" --server="$address" --certificate-authority=<(bosh int <(credhub get -n "${director_name}/${deployment_name}/tls-kubernetes" --output-json) --path=/value/ca) --embed-certs=true
```

But I think its quietly being ignored and not placed in `~/.kube/config`.

Instead, I had to create a temporary file on the local disk and store the certificate value in it, then pass that path to `--certificate-authority=${ca_tmp_path}`.

**What you expected to happen**:

The value of the process substitution (available via a file descriptor) is placed in `~/.kube/config` within `certificate-authority-data:` property.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl config set-cluster foobar-name --server=xyz --certificate-authority=<(echo "foobar") --embed-certs=true
```

```
cat ~/.kube/config
```

The file does not include `foobar` as the certificate:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: xyz
  name: foobar-name
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

Instead, the file should contain `certificate-authority-data: foobar`

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: foobar
    server: xyz
  name: foobar-name
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.4
- OS (e.g. from /etc/os-release): Ubuntu 14.04
- Kernel (e.g. `uname -a`): Linux ed3ee945-8f69-4048-7238-e045c9d9a804 4.4.0-72-generic #93~14.04.1-Ubuntu SMP Fri Mar 31 15:05:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
