### ISSUE TITLE
GCP: Security w/ Internal Load Balancer Firewall

### ISSUE THREAD

**Issue by icereval** [kubernetes/kubernetes#56371]
/kind bug

**What happened**:

GCP Internal Load Balancer configures a firewall exception w/ source ip of `0.0.0.0/0` by default. This allows internet traffic to attempt connections to these ports on the internal k8s host machines.

**What you expected to happen**:

The service configures an Internal Load Balancer would specify firewall rules for the current VPC (or error and require the user to input a `loadBalancerSourceRanges`), and/or require the user to explicitly set **extremely** open ranges like `0.0.0.0/0`.

**How to reproduce it (as minimally and precisely as possible)**:

Create an a service w/ the internal load balancer annotation using GKE (do NOT specify `loadBalancerSourceRanges`).

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T19:11:02Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.3-gke.0", GitCommit:"86d3ac5eaf57223302c95e7d9fc1aeff55fb0c15", GitTreeState:"clean", BuildDate:"2017-11-08T21:42:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
Google Kubernetes Engine
```
- OS (e.g. from /etc/os-release):
```
COS
```
- Kernel (e.g. `uname -a`):
```
Linux gke-data-1-default-pool-014f29ab-g5lq 4.4.64+ #1 SMP Wed Aug 30 20:27:36 PDT 2017 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools:
```
GKE
```
- Others:
N/A

/cc @binoculars

**Comment by icereval** [comment]
@kubernetes/sig-gcp-bugs

**Comment by nicksardo** [comment]
Unfortunately, this isn't limited to internal load balancers. You could have two external network load balancers, serving traffic on the same port, with different loadBalancerSourceRanges. The generated GCP firewalls wouldn't be specific enough to respect the individual service's source ranges. Thankfully, iptables matches services via the destination LB IP/port and applies the respective loadBalancerSourceRanges rules again. In the case of ILB, only traffic with the ILB as the destination IP will be able to hit the K8s service. Therefore, I don't see this as a major security flaw.  Please confirm that you were never able to actually access your ILB service via a node's external IP.

I agree that the firewall rules should be stronger; however, I don't think it should done by changing the default source ranges. Kubernetes.io documents that the default range will be 0.0.0.0/0 - changing this for a specific cloud and LB type could be confusing. For GCP users with VPNs, peerings, etc., limiting traffic to the local subnet would result in unexpected traffic loss. Defaulting to all RFC 1918 CIDRs is another idea, but I'm not sure if that would be sufficient for some advanced users. In the end, we would still have this problem for external load balancers - an even more common use case. 

Solving this problem for both types of LB will require GCP changes, so I'll raise this issue internally. 

/cc @freehan @MrHohn @thockin 
/area platform/gce

**Comment by icereval** [comment]
@nicksardo 

* Create the Internal Load Balancer

  `service.yml`
  ```yaml
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/load-balancer-type: Internal
    name: internal-lb-test
  spec:
    type: LoadBalancer
    ports:
      - port: 1234
        targetPort: 4321
  ```

* Retrieve the IP of the K8S Hosts

  ```bash
  $ gcloud compute instances list --filter="name=gke-temp-1-default-pool-3bdd1873-36kd" 
  NAME                                   ZONE        MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP      STATUS
  gke-temp-1-default-pool-3bdd1873-36kd  us-east1-d  n1-standard-1  true         10.0.64.6    104.196.176.186  RUNNING
  ```

* SSH into the K8s Host and simulate a running process, which listens on the Internal Load Balancer Port `1234`.

  ```bash
  $ gcloud compute ssh --zone us-east1-d gke-temp-1-default-pool-3bdd1873-36kd
  $ socat - TCP-LISTEN:1234
  ```

* Telnet the K8s Host's listening internal load balancer port from the internet and send it a message.

  ```bash
  $ telnet 104.196.176.186 1234
  not good... (hit enter)
  ```

* NOTE: A connection is established, and are able to communicate with the host's `socat` server.

  ![openport](https://user-images.githubusercontent.com/3111541/34654671-1d28e43a-f3cd-11e7-8066-5999120c254f.gif)

**Comment by nicksardo** [comment]
I was asking you to confirm that you cannot access the actual K8s service.

**Comment by gottwald** [comment]
@nicksardo we ran into this problem a while ago and today I finally had a chance to reproduce it in our sandbox.

But our use-case is rather special. We have a dedicated GKE node pool for a certain software that runs as a DaemonSet and uses host ports that are the same as the service uses for the internal GCE LB.
In that scenario the firewall rule exposes the host ports from the DaemonSet on the public IPs of the nodes.

We caught it early because we have monitoring on our FW ruleset, but still it was surprising that deploying a service with internal LB could have this unfortunate side effect.

**Comment by rfevang** [comment]
We were just bitten by this as well. We have a service defined (Kafka) that also needs to be individually addressable. After a client connects, the container gives the client the addresses to the other containers, so to enable this the container definition declares hostPort.

The service is exposed outside the cluster using an internal load balancer:
```
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.132.0.100
  ports:
  - port: 9092
    name: client
  selector:
    app: kafka
```
It was a real surprise that this caused the port to be externally accessible, the only reason we found out was that a different service declared hostPort unnecessarily, and we noticed external port scan probes in its logs.

**Comment by rfevang** [comment]
Adding
```
loadBalancerSourceRanges:
- 10.132.0.0/20
```
to the service definition seems to have worked. It's a little surprising that isn't implied by the internal annotation, but I guess that might be a GKE issue?

**Comment by teodor-pripoae** [comment]
The workaround above doesn't work for external load balancers.

**Comment by teodor-pripoae** [comment]
Let's see the following case.

I'm having ssh to gke nodes disabled from gce firewall. I want to deploy a pod with a service with external ip, to allow ssh from outside into container. Doing this will expose port 22 on all nodes in my gke cluster.

**Comment by teodor-pripoae** [comment]
/remove-lifecycle stale

Any updates regarding this security issue ?

**Comment by benmizrahi** [comment]
Any updates for solving this issue?
We also get the same results as described above

**Comment by rstrazza** [comment]
I found something slightly related to this topic from the Security standpoint. We created the internal load balancer to access ES within the same VPC as the GKE cluster:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-ilb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    component: elasticsearch
    role: ilb
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.150.0.0/20
  ports:
  - name: search
    port: 9200
    protocol: TCP
  selector:
    component: elasticsearch
    role: client
```

It created the Service ILB as expected:

```bash
NAME                TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
elasticsearch-ilb   LoadBalancer   10.109.2.43   10.150.0.75   9200:32329/TCP   16h
```

ILB works well within the VPC and communication works as expected.

**The problem (maybe I'm missing a basic step in the setup process?):**

1. Go to the GKE Service and identify the serving pod
2. Go to the VM where the pod is running. Copy the public IP address
3. Try to access the VM public IP address using the Node Port (32329) and the service is externally open

I'm running on GKE: 1.11.6-gke.2 with VPC Enabled.

Please let me know if you have any questions. Appreciate any feedback.
