### ISSUE TITLE
Object definitions in OpenAPI schema are incorrect

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#56428]
The definitions of the API resources in the OpenAPI schema lack the `type: object` property. For example, the definition of the `PersistentVolumeSpec` is this:
```
   "io.k8s.api.core.v1.PersistentVolumeClaimSpec": {
    "description": "PersistentVolumeClaimSpec describes the common attributes of storage devices and allows a Source for provider-specific attributes",
    "properties": { ...
    }
   },
```
NOTE there's no `type: object` field.

The definition of `PersistentVolume` references `PersistentVolumeClaimSpec` like this:
```
     "spec": {
      "description": "Spec defines a specification of a persistent volume owned by the cluster. Provisioned by an administrator. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistent-volumes",
      "$ref": "#/definitions/io.k8s.api.core.v1.PersistentVolumeSpec"
     },
```

Because there's no `type: object` constraint in the `PersistentVolumeClaimSpec` definition, the end effect is that the schema basically says that the following are valid PVCs (when they obviously aren't):
```
kind: PersistentVolumeClaim
metadata: ...
spec: "any string"

kind: PersistentVolumeClaim
metadata: ...
spec: 5

kind: PersistentVolumeClaim
metadata: ...
spec:
- anyObjectHere:
    anyProperty: anyValue
- anyObjectHere:
    anyProperty: anyValue
```

For more information, see:
- https://stackoverflow.com/questions/47374980/schema-object-without-a-type-attribute-in-swagger-2-0
- https://github.com/OAI/OpenAPI-Specification/issues/1388#issuecomment-339061316

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.8556+d1e067be1f3065-dirty", GitCommit:"d1e067be1f30654867769ae9dd9aaa2e30513c21", GitTreeState:"dirty", BuildDate:"2017-11-15T21:38:13Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"g
