### ISSUE TITLE
service backup selector

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/kubernetes#56440]
/kind feature

**What happened**:
I would like to be able to have two sets of deployments behind a Service. The primary normally would be scaled out and receive all the traffic. If no primaries are available, kube-proxy would use the backup selector to select available pods to enter service. If any primaries come back on, the backups would be removed from service.

This would allow for important services to be loaded on kube controllers or other important reserved hardware that normally would be busy doing other things, but could be used still automatically during disasters to try and continue to keep the system running.

**Comment by kfox1111** [comment]
@kubernetes/sig-network

**Comment by kfox1111** [comment]
Ping

**Comment by thockin** [comment]
This seems like something service topology could address, if you can describe the backup nodes as a different label.

**Comment by kfox1111** [comment]
I hadn't bumped into the service topology feature before and missed your email thockin. I'll take a closer look. At a glance, it looks like it could indeed solve the issue. Thanks. 

/reopen
/remove-lifecycle rotten

**Comment by rikatz** [comment]
@kfox1111 As Service Topology reached [alpha](https://kubernetes.io/docs/concepts/services-networking/service-topology/) had you got some chance to test it and see if this deals with the required feature?

Also it would be nice to test and provide some feedback :)

**Comment by kfox1111** [comment]
I have not yet. I'll try and make some time in the next few days. Thanks for the reminder.

**Comment by thockin** [comment]
The argument I heard for this was "my service is down, handle it better
than black-hole".

I am not 100% convinced but it was plausible ..

**Comment by thockin** [comment]
But those backup pods need to be in the same namespace, which makes me
question the utility of this overall.

**Comment by kfox1111** [comment]
Why would being in the same namespace be a problem?

**Comment by thockin** [comment]
I guess only because it makes this N-ary -- every namespace that wants such behavior has to define their own pods.  Thinking through failure modes, I guess that is reasonable.

I do not think topology is a great fit for this any more, but we would want a KEP to think it through

**Comment by rikatz** [comment]
So being in this same way, there's another issue that deals with similar situation: https://github.com/kubernetes/kubernetes/issues/85395

In my opinion they try to solve the same problem: effectively allowing kube-proxy, ingress and others to do weighted load balance.

As I see, issue #85395 would help in situations where you have two deployments, with different labels and want them to answer in the same service but with different weights (blue/green deployment as an example). So you can define in ingresses controllers backends based in their weight.

And in this case, imagine a deployment (or a selector) gets a weight of 0 (and maybe -1 meaning it's disabled) and only receiving traffic if the other services without value 0 fails.

@thockin does this seems something we want? In my opinion both can be part of the same KEP and it would be really useful for ingress controllers and also internal communications (kube-proxy). And this modification may not have bigger impacts, as it just might add a new 'weights' struct inside the Service definition, with selector and the weight value.

Thanks!!

**Comment by kfox1111** [comment]
+1 to a joint kep. It does sound similar and could maybe be solved with some/all of the same pluming.

@thockin 's use case from above could also maybe be handled as a third use case with the same kep. Maybe the kep would allow both selector's and an external endpoints with very low weight to be specified so that traffic could be redirected to some other site if no local options are available.

**Comment by rikatz** [comment]
Well, will wait @thockin feedback on this.

If this is good enough count me in to contribute in this KEP :)

**Comment by thockin** [comment]
Looking at older issues, I realize this got lost.  I am not against exploring something here, but the use-cases need to be crystal clear

**Comment by sftim** [comment]
Overall: can we make this possible using [Gateway](https://gateway-api.sigs.k8s.io/), and without adding complexity into core Kubernetes (ie Service)?

If we can, then I think we should try that first. One idea of mine was to have a single thing visible to consumers, backed by 2 internal Services that have different selectors.

**Comment by thockin** [comment]
We don't (yet) have a Gateway model for ClusterIPs (but we need one). Since this seems to be all about endpoint selection, it seems plausible that this could be in gateway, yes.  I'd lump that into "exploring something here", but I agree with the sentiment - the less we depend on Service changes, the better.

**Comment by aojea** [comment]
> We don't (yet) have a Gateway model for ClusterIPs (but we need one)

I've done this exercise some weeks ago after talking with @robscott and these are some notes, example https://github.com/kubernetes-sigs/gateway-api/blob/main/examples/experimental/basic-tcp.yaml

- Gateway requires to configure at least 2 objects, something to consider for users that right now only have to configure one and use a selector 
- Gateway `TCPRoute/UDPRoute` usually reference Services, but it can be any other objects, we can use EndpointSlices but we need something to generated them, Rob suggested using Deployments/statefulset that makes more sense to me (complexity will go to the controller though)

With that in mind, I think that it should relatively easy to implement this kind of features, I'm thinking in something like

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: my-tcp-gateway
spec:
  gatewayClassName: Kubernetes-ClusterIP
  listeners:
  - name: foo
    protocol: TCP
    port: 8080
    allowedRoutes:
      kinds:
      - kind: TCPRoute
  - name: bar
    protocol: TCP
    port: 8090
    allowedRoutes:
      kinds:
      - kind: TCPRoute
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcp-app-1
spec:
  parentRefs:
  - name: my-tcp-gateway
    sectionName: foo
  rules:
  - backendRefs:
    - name: my-foo-service
      port: 6000
      weight: 100
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcp-app-2
spec:
  parentRefs:
  - name: my-tcp-gateway
    sectionName: bar
  rules:
  - backendRefs:
    - name: my-
      port: 6000
      weight: 0
```

**Comment by thockin** [comment]
> Gateway TCPRoute/UDPRoute usually reference Services, but it can be any other objects, we can use EndpointSlices but we need something to generated them, Rob suggested using Deployments/statefulset that makes more sense to me (complexity will go to the controller though)

I had a discussion a while back (but have not had a chance to actually write a KEP or anything) about decomposing Service further.  The core of a Service is a selector.  I see an increasing number of things that want approximately a selector, but without all the other Service stuff.  Why couldn't we have that as an API?

The ugly problem I haven't worked through is ports and port mapping.  EndpointSlice isn't just a list of IPs, it's also the result of service->pod port-mapping (including named ports).  I was thinking maybe the API looks like:

```
apiGroup: core/v1
kind: PodSelector
metadata:
  name: my-selector
  namespace: my-app
selector:
  matchLabels:
    foo: bar
ports:
  - name: http
    portNumber: 8000
  - name: https
    portNumber: 8443
  - name: optional
    portName: admin
```

This generates EPSlices, but instead of a label `kubernetes.io/service-name` it gets `kubernetes.io/pod-selector-name`.
