### ISSUE TITLE
When using 'custom metrics', the number of scaled pods is more than the value returned by the 'custom metrics' itself

### ISSUE THREAD

**Issue by rsd35410** [kubernetes/kubernetes#56485]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig autoscaling

**What happened**:
When using 'custom metrics', the number of scaled pods is more than the value returned by the 'custom metrics' itself. It always go to the MaxReplicas.

```
NAME                 REFERENCE               TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
hpa/fileapp-pu-hpa   Deployment/fileapp-pu   2 / 1     1         6         6          1h

NAME                                 READY     STATUS    RESTARTS   AGE
po/fileapp-pu-7c9b8c897d-b6rnj       1/1       Running   0          18s
po/fileapp-pu-7c9b8c897d-gkhvn       1/1       Running   0          18s
po/fileapp-pu-7c9b8c897d-m5qfn       1/1       Running   0          58s
po/fileapp-pu-7c9b8c897d-rxqhb       1/1       Running   0          23m
po/fileapp-pu-7c9b8c897d-z65lq       1/1       Running   0          38s
po/fileapp-pu-7c9b8c897d-zz4nq       1/1       Running   0          38s
po/job-metrics-app-594c6b798-zsbsb   1/1       Running   0          1h

```
**What you expected to happen**:
Having the number of scaled pods inline with the 'custom metrics' value.
So, I'm expecting to have the number of replicas equel to 2.

**How to reproduce it (as minimally and precisely as possible)**:
I'm using a 'custom metrics' named 'nb_jobs' and use the HPA definition describe above:

```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: fileapp-pu-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: fileapp-pu
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: job-metrics-app
      metricName: nb_jobs
      targetValue: 1
```

As you can see, 'nb_jobs' is exposed by a different service (job-metrics-app) than the one I want to scale (fileapp-pu).
I also change the 'kube-controller-manager.yaml' to reduce the autoscaler delays to 15s. I add these two lines:
- --horizontal-pod-autoscaler-downscale-delay=15s
- --horizontal-pod-autoscaler-upscale-delay=15s

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.8.5
