### ISSUE TITLE
Rolling upgrade of deployment has conflict with pod anti-affinity policy

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#56539]
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
> /kind bug

**What happened**:
I have a kube-dns deployment to create multiple dns pods on each node. Use pod anti-affinity policy to make sure dns pods can be spreaded over cluster nodes.

```
  selector:
    matchLabels:
      k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - kube-dns
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: kubedns
```

Then I want to upgrade my kube-dns to the latest version `1.14.4`. The new pod is in `Pending` state forever because of no node is selected for the pod because of pod anti-affinity policy.

**What you expected to happen**:
The rolling upgrade process of kube-dns deployment should be completed as expected.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create deployment with pod anti-affinity set.
2. Upgrade the deployment.

**Anything else we need to know?**:

**Environment**: None
- Kubernetes version (use `kubectl version`): v1.8.3
- Cloud provider or hardware configuration: None
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools: self-defined
- Others:
