### ISSUE TITLE
kube-dns pod restarts every 2 minutes in IPv6-only cluster

### ISSUE THREAD

**Issue by leblancd** [kubernetes/kubernetes#56543]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature
/area ipv6
/sig network

**What happened**:
When a Kubernetes cluster is instantiated in IPv6-only mode via kubeadm, using the latest master code base, then the kube-dns pod is restarted approximately every 2 minutes.

Examination of the kube-dns sidecar logs shows that in an IPv6-only cluster, the liveness probes used for kube-dns are set to use the server IP:port values of "::1:53" and "::1:10053". These are invalid, and the correct IP:port strings should use brackets around the IPv6 address, e.g. "[::1]:53" and "[::1]:10053". 

Similarly, examination of the kube-dns deployment YAML configuration shows the liveness probes using IP:port values of "::1:53" and "::1:10053" rather than "[::1]:53" and "[::1]:10053".

**What you expected to happen**:
The kube-dns pod should stay up indefinitely in an IPv6-only cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Use Kubernetes binaries and docker images built from the latest master. Then start up an IPv6-only cluster using 'kubeadm init ...' with the following kubeadm configuration (where unifiedControlPlaneImage points to the hyperkube image built from latest master):
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: 1.10.0
api:
  advertiseAddress: fd00::100
networking:
  serviceSubnet: fd00:1234::/110
unifiedControlPlaneImage: diverdane/hyperkube-amd64:v1.9_code_freeze
tokenTTL: 0s
nodeName: kube-master
```
After the kubernetes master node comes up, you will see the kube-dns pod restarted every 2 minutes or so.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0-alpha.0.633+02a7c12cbd0dd3-dirty (latest master)
- Cloud provider or hardware configuration: VirtualBox cluster, Ubuntu 16.04.1 host, CentOS 7 guests
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
