### ISSUE TITLE
 kubenetes svc endpoints are not updated when one of API is down (when running HA api)

### ISSUE THREAD

**Issue by calvix** [kubernetes/kubernetes#56584]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
We are running HA k8s api (3x API)  and when one of the k8s api is down, we got issues with accessing k8s api when using in-cluster config (that means via kubernetes service created in the default namespaces).

API are running on IPs `10.10.0.101, 10.10.0.102, 10.10.0.103`
```
14a32b2b9 ~ $ kubectl get svc
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   172.18.192.1   <none>        443/TCP   117d
14a32b2b9 ~ $ kubectl describe svc kubernetes
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                172.18.192.1
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         10.143.29.101:6443,10.143.29.102:6443,10.143.29.103:6443
Session Affinity:  ClientIP
Events:            <none>

14a32b2b9 ~ $ kubectl get ep 
NAME         ENDPOINTS                                                  AGE
kubernetes   10.10.0.101:6443,10.10.0.102:6443,10.10.0.103:6443   117d
```

When one of our API is offline,  the endpoint list is still same and kube-proxy is creating rules with forwarding to the offline API which result in failure.

We run k8s-api as pod via manifest folder  in kubelet.
```
containers:
  - name: k8s-apiserver
    image: quay.io/giantswarm/hyperkube:v1.7.5_coreos.0
    command:
    - /hyperkube
    - apiserver
    - --apiserver-count=3
    - --allow-privileged=true
    - --secure-port=6443
    - --runtime-config=api/all=true
    - --insecure_bind_address=127.0.0.1
    - --insecure_port=8080
    - --kubelet_https=true
    - --bind-address=10.10.0.101
    - --etcd-prefix=k8s
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota
    - --service-cluster-ip-range=172.31.0.1/16
    - --etcd-servers=https://10.10.0.101:2379
    - --etcd-cafile=/etc/kubernetes/ssl/apiserver-ca.pem
    - --etcd-certfile=/etc/kubernetes/ssl/apiserver.pem
    - --etcd-keyfile=/etc/kubernetes/ssl/apiserver-key.pem
    - --advertise-address=10.10.0.101
    - --logtostderr=true
    - --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem
    - --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem
    - --client-ca-file=/etc/kubernetes/ssl/apiserver-ca.pem
    - --service-account-key-file=/etc/kubernetes/ssl/sa_private_key.pem
    - --audit-log-path=/var/log/apiserver/audit.log
    - --audit-log-maxage=30
    - --audit-log-maxbackup=10
    - --audit-log-maxsize=100
```

**What you expected to happen**:
I would expect that there is some kind of control check that ensure that only healthy APIs are listed in the `kubernetes` endpoint resource.

**How to reproduce it (as minimally and precisely as possible)**:
* Spawn k8s cluster with 6 nodes - 3 masters with k8s api + kubelet and 3x worker node with kubelet
* Wait until cluster is initialized and fully working
* Shut down one of the api node
* Test access to kubernetes in-cluster service from worker nodes. Some of them will work and some of them will fail due to  1 out of 3 offline APIs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5+coreos.0", GitCommit:"070d238cd2ec359928548e486a9171b498573181", GitTreeState:"clean", BuildDate:"2017-08-31T21:28:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: baremetal
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1465.8.0
VERSION_ID=1465.8.0
BUILD_ID=2017-09-20-2237
PRETTY_NAME="Container Linux by CoreOS 1465.8.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux 00008df14a32b2b9 4.12.14-coreos #1 SMP Wed Sep 20 22:20:05 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2637 v2 @ 3.50GHz GenuineIntel GNU/Linux
```
- Install tools: selfhosted
- Others:
