### ISSUE TITLE
How to enable external traffic in in-house VM based installation

### ISSUE THREAD

**Issue by az-z** [kubernetes/kubernetes#56590]
Hello,
I'm running a POC for kubernetes in the in-house datacenter. I have a set of RedHat7 Vms .
I deployed nginx images and can communicate with them on the cluster's "PublicIP"/port.
The problem i'm facing is with external traffic NOT reaching those apps.

Use case:
 deploy images into the cluster and have internal (enterprise wide) traffic to hit those apps.

The objective is to have a single IP:port to publish to the service catalog for the application. I imply the load balancing and seamless scalability.
thank you 

@kubernetes/sig-onprem-misc

**Comment by az-z** [comment]
@kubernetes/sig-onprem-misc

**Comment by dixudx** [comment]
@az-z You should try [Kubernetes ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/).

**Comment by az-z** [comment]
Is it a separate install/rpm?

**Comment by az-z** [comment]
@dixudx 
Di,
 thank you for pointing out.

I spent the entire day today in a futile attempt to get the issue resolved.
Here are the steps and configurations i made. 
i'd appreciate anyone guidance.
1. create deployments with nginx
```
cat nginx_dep.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
      matchLabels:
        app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

kubectl  get pods -o wide
NAME                    READY     STATUS    RESTARTS   AGE       IP          NODE
nginx-75f4785b7-ghvwz   1/1       Running   0          56m       10.44.0.2   kb-w1
nginx-75f4785b7-xdmp6   1/1       Running   0          56m       10.44.0.1   kb-w1
```

2. create service - ClusterIP
```
cat nginx_service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginxservice
  name: nginxservice
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    app: nginx

kubectl get services -o wide
NAME           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE       SELECTOR
kubernetes     ClusterIP   10.96.0.1      <none>        443/TCP   1h        <none>
nginxservice   ClusterIP   10.99.231.26   <none>        80/TCP    55m       app=nginx
```

3. create ingress controller
```
cat ing_contr.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-controller
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.11
        name: nginx-ingress-controller
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - containerPort: 80
          hostPort: 80
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
```
4. create ingress resource
```
cat basic-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    serviceName: nginxservice
    servicePort: 80
```
5. Expect to see the non empty value in the ExternalIP
```
 kubectl get ing -o wide
NAME            HOSTS     ADDRESS   PORTS     AGE
basic-ingress   *                   80        3h
```
Appreciate.
