### ISSUE TITLE
Link one service to another service in Kubernetes

### ISSUE THREAD

**Issue by akhisharma-DevOps** [kubernetes/kubernetes#56636]
I have individual kubernetes containers up and running. Can someone please help me how to link them? I have worked on docker compose and there it works like this:

![image](https://user-images.githubusercontent.com/25716046/33439327-2f03503c-d613-11e7-8607-938927f9cecf.png)

But when coming to kubernetes, I have no clue how to proceed. I have service and deployment files created after using kompose but it actually broke the links between the code.

**Service file:**

![image](https://user-images.githubusercontent.com/25716046/33439370-49c0843a-d613-11e7-83f5-df44b57c9caf.png)

**And my deployment file is**:

![image](https://user-images.githubusercontent.com/25716046/33439416-5e531b56-d613-11e7-9b80-6a3675d2ad2f.png)

**Comment by jhorwit2** [comment]
@akhisharma-DevOps In order to get you help in a timely manner I'd suggest commenting on the [related issue in the kompose repo](https://github.com/kubernetes/kompose/issues/859) and/or joining the #kompose channel on [Kubernetes slack](https://kubernetes.slack.com/). 

/assign
/close

**Comment by akhisharma-DevOps** [comment]
@jhorwit2 this is not related to kompose. I guess you misunderstood the issue. What I'm asking is how to link services in kubernetes as we do in docker.
You just saw annotations of kompose as it converted docker-compose to kubernetes manifest files. But my real question is something else.

**Comment by vinayus** [comment]
Maybe this can help you to link containers. Simple example:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-centos-pod
spec:
  containers:
  - name: my-nginx
    image: nginx
  - name: my-centos
    image: centos
    command: ["/bin/sh", "-c", "while : ;do curl http://localhost:80/; sleep 3; done"]
```
