### ISSUE TITLE
[e2e node] Pause pod created in GPUDevicePlugin test by makeCudaPauseImage() will be `CrashLoopBackOff` forever

### ISSUE THREAD

**Issue by ScorpioCPH** [kubernetes/kubernetes#56695]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug maybe

**What happened**:

Container running in this pod will exec a command then `exit`, so this pod's status will be `CrashLoopBackOff` and it will restart periodically.
Maybe `restartCount` checking in the following steps seem like useless.

```go
// Retrieves the gpu devices created in the user pod.
// Note the nvidia device plugin implementation doesn't do device id remapping currently.
// Will probably need to use nvidia-smi if that changes.
Command: []string{"sh", "-c", "devs=$(ls /dev/ | egrep '^nvidia[0-9]+$') && echo gpu devices: $devs"},
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

- create a pod use the following yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sh
      - "-c"
      - "devs=$(ls /tmp/ | egrep '^Dev-[0-9]+$') && echo stub devices: $devs"
    imagePullPolicy: IfNotPresent
    name: busybox
```
- check this pod status, it will be `CrashLoopBackOff` and it will restart periodically.

**Anything else we need to know?**:

I am not very sure whether this is a bug, please correct me if i'm wrong.

/sig node
/assign @jiayingz @vishh WDYT?
