### ISSUE TITLE
Unable to mount volumes for pod "mypod_default(0d57f079-d709-11e7-94c9-00163e30bcc9)": timeout expired waiting for volumes to attach/mount for pod "default"/"mypod"

### ISSUE THREAD

**Issue by noprom** [kubernetes/kubernetes#56735]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
I am using Aliyun Kubernetes service to create my cluster, first of all, I created a NAS on the cloud provider, and the path is: 188864a977-ojm24.cn-beijing.nas.aliyuncs.com
Then, I use the following file to create my PesistentVolume:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /
    server: 188864a977-ojm24.cn-beijing.nas.aliyuncs.com
```
And I got the right result:
```
[root@k8s-master03 nas]# kubectl get pv
NAME      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM             STORAGECLASS   REASON    AGE
jenkins   5Gi        RWX            Retain           Bound     default/myclaim                            12h
```

Then I created a PersistentVolumeClaim using this file:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
```
Then I got:
```
[root@k8s-master03 nas]# kubectl get pvc
NAME      STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
myclaim   Bound     jenkins   5Gi        RWX                           12h
```
However, when I create a pod to use the pvc using this file:
```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: registry.aliyuncs.com/spacexnice/netdia:latest
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: jenkins
```
I got the error: the pod can not be created because of timeout
```
[root@k8s-master03 nas]# kubectl describe pod mypod
Name:         mypod
Namespace:    default
Node:         cn-beijing.i-2ze1cixer8tpoeadz8l4/192.168.153.136
Start Time:   Sat, 02 Dec 2017 10:32:33 +0800
Labels:       <none>
Annotations:  <none>
Status:       Pending
IP:
Containers:
  myfrontend:
    Container ID:
    Image:          registry.aliyuncs.com/spacexnice/netdia:latest
    Image ID:
    Port:           <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gqstb (ro)
      /var/www/html from mypd (rw)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  mypd:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  jenkins
    ReadOnly:   false
  default-token-gqstb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gqstb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                From                                        Message
  ----     ------                 ----               ----                                        -------
  Normal   Scheduled              31m                default-scheduler                           Successfully assigned mypod to cn-beijing.i-2ze1cixer8tpoeadz8l4
  Normal   SuccessfulMountVolume  31m                kubelet, cn-beijing.i-2ze1cixer8tpoeadz8l4  MountVolume.SetUp succeeded for volume "default-token-gqstb"
  Warning  FailedMount            1m (x13 over 29m)  kubelet, cn-beijing.i-2ze1cixer8tpoeadz8l4  Unable to mount volumes for pod "mypod_default(0d57f079-d709-11e7-94c9-00163e30bcc9)": timeout expired waiting for volumes to attach/mount for pod "default"/"mypod". list of unattached/unmounted volumes=[mypd]
  Warning  FailedSync             1m (x13 over 29m)  kubelet, cn-beijing.i-2ze1cixer8tpoeadz8l4  Error syncing pod
```
But I was able to mount the nfs server:
```
[root@k8s-master03 ~]# df -h | grep aliyuncs
188864a977-mlr25.cn-beijing.nas.aliyuncs.com:/  1.0P     0  1.0P   0% /nfs
```
**What you expected to happen**:

The pod mount my pvc successfully.

**How to reproduce it (as minimally and precisely as possible)**:
The steps are clearly described in the **What happened** part.
**Anything else we need to know?**:
Nothing else.
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.1-alicloud", GitCommit:"19408ab2a1b736fe97a9d9cf24c6fb228f23f12f", GitTreeState:"clean", BuildDate:"2017-10-19T04:05:24Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Cloud provider: Aliyun
- OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`): Linux k8s-master03 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by davidz627** [comment]
Hi nopom@, I noticed in your pod spec you have:

```
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: jenkins
```

the claimName needs to be the name of your PVC. In this case you have used the name of your PV.
"jenkins" should be "myclaim".
