### ISSUE TITLE
kubectl config view --minify=true fails for kubeconfig without current context

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#56747]
Separate cluster kubeconfig files can have unnamed contexts, e.g.

```
apiVersion: v1
kind: Config
clusters:
- name: cluster-8f18
  cluster:
    server: https://foo.bar
users:
- name: admin
  user:
contexts:
- context:
    cluster: cluster-8f18
    user: admin
```

Then `kubectl config view --minify=true` complains that no context is set.

Meanwhile:
```
$ kubectl config get-contexts
CURRENT   NAME      CLUSTER        AUTHINFO   NAMESPACE
*                   cluster-8f18   admin
```

and

```
$ kubectl config current-context
error: current-context is not set
```

and

```
$ kubectl config use-context ""
error: you must specify a current-context
```

All not very consistent.
