### ISSUE TITLE
flexVolume parameters parsing incorrect

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#56777]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
When I try to set up a flex volume PV by following config:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-flex-lvm 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: foo/lvm
    fsType: ext4
    readOnly: true
    options: 
      fooServer: 192.168.0.1:1234
      fooVolumeName: bar
```
Then I run `kubectl describe pv pv-flex-lvm`, the output would be as following in which `driver`, `fsType` is parsing incorrect, I tried on both v1.8, v1.9 k8s cluster, got same situation:

```
Name:            pv-flex-lvm
Labels:          <none>
Annotations:     <none>
StorageClass:
Status:          Available
Claim:
Reclaim Policy:  Retain
Access Modes:    RWO
Capacity:        1Gi
Message:
Source:
    Type:    FlexVolume (a generic volume resource that is provisioned/attached using an exec based plugin)
    Driver:      Options:  %v

    FSType:                                                                                      foo/lvm
    SecretRef:                                                                                   ext4
    ReadOnly:                                                                                    <nil>
%!(EXTRA bool=true, map[string]string=map[fooServer:192.168.0.1:1234 fooVolumeName:bar])Events:  <none>
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8, v1.9
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig storage

**Comment by stewart-yu** [comment]
I will help fix it

**Comment by andyzhangx** [comment]
To simplify this issue, I used following config to create a flex volume PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-flex-lvm 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: foo/lvm
```

And also got same error output (`driver` field is incorrect in output, `driver` field value moved to `FSType` filed!!!)
```
Name:            pv-flex-lvm2
Labels:          <none>
Annotations:     <none>
StorageClass:
Status:          Available
Claim:
Reclaim Policy:  Retain
Access Modes:    RWO
Capacity:        1Gi
Message:
Source:
    Type:    FlexVolume (a generic volume resource that is provisioned/attached using an exec based plugin)
    Driver:      Options:  %v

    FSType:                                           foo/lvm
    SecretRef:
    ReadOnly:                                         <nil>
%!(EXTRA bool=false, map[string]string=map[])Events:  <none>
```
