### ISSUE TITLE
hardcode in Url format in httpGet handler of container lifecycle 

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes/kubernetes#56770]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
the url is hard code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/handlers.go#L126) in httpGet handler of container lifecycle.
Thus, I have a pod definition like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
  labels:
    name: test-pod-applied1
spec:
  containers:
  - name: kubernetes-pause
    image: gcr.io/google-containers/nginx
    lifecycle:
      postStart:
        httpGet:
          scheme: HTTPS
          path: /healthz
          port: 8080
```

and the output url looks like this:
```
E1204 14:11:47.181785  116382 handlers.go:128] ----------url: http://172.17.0.3:8080//healthz  
```
The scheme in definition did not take effect, and we got a redundant "/" in path

**What you expected to happen**:
Take advantage of "net/url" package to validate and format the url, instead of hard code.
