### ISSUE TITLE
networkpolicies - allow / deny cidrs

### ISSUE THREAD

**Issue by zetaab** [kubernetes/kubernetes#56776]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE
 /kind feature

Currently it looks like network policies supports only ipblocks, but there is no possibility to define is that ipblock allowed or denied. This means that it is impossible to make advanced models of which ip is allowed and which not. https://kubernetes.io/docs/concepts/services-networking/network-policies/

I suggest that we should take example of what openshift is doing here, because that model is pretty nice https://docs.openshift.com/container-platform/3.6/admin_guide/managing_networking.html#admin-guide-limit-pod-access-egress 

#### Example of two use-cases:

I want allow egress traffic to few ip addresses like, 192.168.0.1, 10.0.0.1, 8.8.8.8 and deny others. How I do this currently in kubernetes or is that possible?

In openshift this is (please note that order in these rules matter):

```
apiVersion: v1
kind: EgressNetworkPolicy
metadata:
  name: default
spec:
  egress:
  - to:
      cidrSelector: 192.168.0.1/32
    type: Allow
  - to:
      cidrSelector: 10.0.0.1/32
    type: Allow
  - to:
      cidrSelector: 8.8.8.8/32
    type: Allow
  - to:
      cidrSelector: 0.0.0.0/0
    type: Deny
```

I want deny cidr 192.168.40.0/24 but allow others

In openshift it is (please note that order in these rules matter):

```
apiVersion: v1
kind: EgressNetworkPolicy
metadata:
  name: default
spec:
  egress:
  - to:
      cidrSelector: 192.168.40.0/24
    type: Deny
  - to:
      cidrSelector: 0.0.0.0/0
    type: Allow
```

So I am kind of asking, should we add `type` here https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/types.go#L151-L160 which defines is it allowed or denied.

**Comment by Rafaesp** [comment]
I think you could write:
```
egress:
  - to:
      - ipBlock:
        cidr: 192.168.0.1/32
  - to:
      - ipBlock:
        cidr: 10.0.0.1/32
  - to:
      - ipBlock:
        cidr: 8.8.8.8/32
```
```
egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
          except: 192.168.40.0/24
```

All traffic that doesn't match, will be denied.

Could anybody confirm this, please?
