### ISSUE TITLE
Allow to use configmaps or secrets as valueFrom for TLS hosts in ingress spec

### ISSUE THREAD

**Issue by honi** [kubernetes/kubernetes#56795]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**NGINX Ingress controller version**:
0.9.0-beta.17

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.8-gke.0", GitCommit:"a7061d4b09b53ab4099e3b5ca3e80fb172e1b018", GitTreeState:"clean", BuildDate:"2017-10-10T18:48:45Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
Google Container Engine
Running [kube-lego](https://github.com/jetstack/kube-lego) for automatic certificate provisioning.

**What you expected to happen**:
I have qa/staging/production namespaces running exactly the same resources. I reuse the resource yaml files and adjust any environment specific configurations through secrets or configmaps which have the same name in all namespaces.

I wanted to do the same thing with an ingress that has tls enabled. But it seems that I need to explicitly define the hosts in the resource definition.

It would be great if one could obtain the host value from a configmap, same way you can do it for env vars in a container spec. Something like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
      valueFrom:
        configMapKeyRef:
          name: web-hosts
          key: host
    secretName: web-tls
  rules:
  - host:
      valueFrom:
        configMapKeyRef:
          name: web-hosts
          key: host
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 80
```

I originally posted this in kubernetes/ingress-nginx#1773
