### ISSUE TITLE
matchLabels from NetworkPolicy's podSelector not working as expected

### ISSUE THREAD

**Issue by Rafaesp** [kubernetes/kubernetes#56847]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When I create a NetworkPolicy that matches two different pod labels, the resulting NetPol only matches the last label
**What you expected to happen**:
The resulting NetworkPolicy should match both labels

**How to reproduce it (as minimally and precisely as possible)**:
1. Create namespace
```kubectl create ns policy-demo```
2. Create NetPol:
```
kubectl create -f - <<EOF
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-nginx
  namespace: policy-demo
spec:
  podSelector:
    matchLabels:
      run: nginx
      run: nginx2
  policyTypes:
  - Ingress
  - Egress
EOF
```
3. Read created NetPol
```kubectl get netpol access-nginx -npolicy-demo -oyaml```
4. Verify that the NetPol only matches `run: nginx2` but no `run: nginx`

**Anything else we need to know?**:
As a workaround, I can do:
```
kubectl create -f - <<EOF
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-nginx
  namespace: policy-demo
spec:
  podSelector:
    matchExpressions:
    - {key: run, operator: In, values: [nginx, nginx2]}
  policyTypes:
  - Ingress
  - Egress
EOF
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
```Linux rafa-MS-7817 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```
- Install tools:
- Others:
