### ISSUE TITLE
Azure Load Balancer Health Probe not configured correctly

### ISSUE THREAD

**Issue by rfranzke** [kubernetes/kubernetes#56898]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/area cloudprovider
/sig azure

**What happened**:
I've created a service of type `LoadBalancer` in a Kubernetes cluster created via the ACS Engine. The load balancer has been created correctly after some time and a random NodePort (at this time `32330`) has been allocated. However, in the Azure Portal I'm seeing that the health probe of that load balancer is pointing to port `30764` which does not exist in the whole Kubernetes system at all. Because of that wrongly configured health probe the load balancer is not reachable (i/o timeout).

**What you expected to happen**:
The health probe would have been configured to NodePort `32330`.

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, it does not behave always like this but only occasionally. In some cases the health probe gets configured correctly, but in others not. I've used the following manifest:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mypod
  name: mypod
  namespace: default
spec:
  ports:
  - name: mypod
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mypod
  type: LoadBalancer
```

**Anything else we need to know?**:
When updating the health probe manually to the correct NodePort in the Azure portal, the load balancer starts to work properly.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.5
- Cloud provider or hardware configuration: Azure
- Install tools: ACS Engine
- Others: -
