### ISSUE TITLE
daemonSet pod with 'hostNetwork: true' has no route to service net

### ISSUE THREAD

**Issue by gintautassulskus** [kubernetes/kubernetes#56934]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
A daemonSet with `hostNetwork: true` has no route to Kubernetes service net.

**What you expected to happen**:
I expected daemonSet pods to be able to reach Kubernetes services.
In order to reach the services, I have to add a static route within the daemonSet pod:  
`ip route add 11.0.0.0/16 via 6.0.9.1`
where `11.0.0.0` is the service net and `6.0.9.1` is `docker.0` interface address in the flannel network.
The route -n output shows there are no routes for the service net:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.172.0.1     0.0.0.0         UG    0      0        0 eth1
6.0.9.0         6.0.9.0         255.255.255.0   UG    0      0        0 flannel.1
6.0.13.0        6.0.13.0        255.255.255.0   UG    0      0        0 flannel.1
6.0.25.0        6.0.25.0        255.255.255.0   UG    0      0        0 flannel.1
6.0.26.0        6.0.26.0        255.255.255.0   UG    0      0        0 flannel.1
6.0.28.0        6.0.28.0        255.255.255.0   UG    0      0        0 flannel.1
6.0.36.0        6.0.36.0        255.255.255.0   UG    0      0        0 flannel.1
6.0.83.0        6.0.83.0        255.255.255.0   UG    0      0        0 flannel.1
6.0.88.0        6.0.88.0        255.255.255.0   UG    0      0        0 flannel.1
6.0.93.0        0.0.0.0         255.255.255.0   U     0      0        0 docker0
6.0.94.0        6.0.94.0        255.255.255.0   UG    0      0        0 flannel.1
192.172.0.0     0.0.0.0         255.255.255.0   U     0      0        0 eth1
#The one below has been added manually. Not a copy-paste thus might be not entirely accurate:
#11.0.0.0        6.0.9.1        255.255.0.0     UG    0      0        0 docker.0
```

Typical pod route table with `hostNetwok: false` routes everything via `6.0.9.1 `, including the service net:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         6.0.9.1        0.0.0.0         UG    0      0        0 eth0
6.0.9.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: curl
  labels:
    k8s-app: curl
spec:
  template:
    metadata:
      labels:
        k8s-app: curl
    spec:
      hostNetwork: true
      containers:
      - image: tutum/curl
        name: curl
        command:
         - "/bin/bash"
         - "-c"
         - "--"
        args :
         - 'sleep infinity'
```

**Environment**:
- Kubernetes version (use `kubectl version`): hyperkube 1.8.4
- OS (e.g. from /etc/os-release): coreos lates to date
