### ISSUE TITLE
Azure LB Service resource report error when updating service

### ISSUE THREAD

**Issue by lazzarello** [kubernetes/kubernetes#56977]
/kind bug

**What happened**:

Created Service template looking like

```
apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: bar
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: bar
    release: {{ .Release.Name }}
```

I created a [static IP resource as documented](https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer). Ran `kubectl edit service <name>`. Added a static IP address with the following line in the spec
```
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: bar
    release: {{ .Release.Name }}
```

The service was not updated. The system output the following error

```
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason				Message
  ---------	--------	-----	----			-------------	--------	------				-------
  35m		35m		1	service-controller			Normal		LoadbalancerIP			 -> 52.165.145.62
  1h		5m		13	service-controller			Normal		CreatingLoadBalancer		Creating load balancer
  35m		5m		12	service-controller			Warning		
Error creating load balancer (will retry): Failed to create load balancer for service default/flippant-bunny-lexapi: user supplied IP Address 52.165.145.62 was not found
```

**What you expected to happen**:

The old service would be destroyed and the new service would be created

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Deployment with a container listening on a network port (like nginx port 80)
1. Associate a Service of type LoadBalancer
1. Create static IP resource in Azure
1. Update Service with static IP

**Anything else we need to know?**:

**Environment**:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-15T08:51:09Z", GoVersion:"go1.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: Azure EKS (Managed Kubernetes)
- Install tools: Helm, azure-cli
