### ISSUE TITLE
kube-controller-manager create rbd failed

### ISSUE THREAD

**Issue by MengZn** [kubernetes/kubernetes#56990]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig volume

**What happened**:
When I operate the following files
```
kubectl apply -f ceph-sc.yml -f rbc-pvc.yml -f  rbd-mount-pod.yml
```
I want to get ab rbd volume witch be created by  StorageClass to be mounted into my pod.

ceph-sc.yml
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.0.10:6789
  adminId: admin
  adminSecretName: ceph-admin-secret
  pool: rbd
  userId: admin
  userSecretName: ceph-admin-secret
```

rbc-pvc.yml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rbd-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ceph
```
 rbd-mount-pod.yml
```
kind: Pod
apiVersion: v1
metadata:
  name: rbd-mount-pod
spec:
  containers:
  - name: mount-pod
    image: busybox
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESS; while :; do sleep 3600; done"
    volumeMounts:
      - name: pvc
        mountPath: "/mnt/"
  restartPolicy: "Never"
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: rbd-pvc
```

**What you expected to happen**:
But I got a pedding status
```
NAME         STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
rbd-pvc      Pending                                       ceph           32m
```
When I check the status of this pvc get this message
```
Events:
  Type     Reason              Age                 From                         Message
  ----     ------              ----                ----                         -------
  Warning  ProvisioningFailed  4m (x122 over 34m)  persistentvolume-controller  Failed to provision volume with StorageClass "ceph": failed to create rbd image: executable file not found in $PATH, command output:
```
So I checked again that the controller manager got other messages
```
W1209 20:32:24.798551       1 rbd_util.go:395] failed to create rbd image, output
E1209 20:32:24.798577       1 rbd.go:367] rbd: create volume failed, err: failed to create rbd image: executable file not found in $PATH, command output:
W1209 20:32:39.775899       1 rbd_util.go:395] failed to create rbd image, output
E1209 20:32:39.775931       1 rbd.go:367] rbd: create volume failed, err: failed to create rbd image: executable file not found in $PATH, command output:
```

**Anything else we need to know?**:
This seems to represent the controller manager is not installed ceph common.
This bothers me for a long time. Can anyone help me?

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:

- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux osd-k8s 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
kubeadm
```
- Others:
```
ceph Jewel
```
