### ISSUE TITLE
Is podAntiAffinity feature available in StatefulSets?

### ISSUE THREAD

**Issue by gmflau** [kubernetes/kubernetes#57002]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Tried to use podAntiAffinity with my StatefulSets implementation but failed.  My K8 cluster allows pods to deploy on the same K8 host/node.

**What you expected to happen**:
K8 cluster should not allow that to happen.

**How to reproduce it (as minimally and precisely as possible)**:
Try to deploy a StatefulSets with "podAntiAffinity" specification.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): GCP Alpha K8 cluster
- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jhorwit2** [comment]
/kind bug 
/sig apps

@gmflau thanks for the report. Could you please post some more information like the manifest for your stateful set.

**Comment by gmflau** [comment]
Here you go below!

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dse
spec:
  serviceName: "dse"
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dse
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: [dse]
              topologyKey: kubernetes.io/hostname
      containers:
        - name: dse
          image: gmflau/dse-server:5.1.5
          resources:
            requests:
              cpu: "2"
              memory: "4000Mi"
          env:
          - name: DS_LICENSE
            value: accept
          - name: SEEDS
            value: dse-0.dse
          - name: NUM_TOKENS
            value: "64"
          ports:
          - containerPort: 7000
            name: intra-node-port
          - containerPort: 7001
            name: tls-intra-node
          - containerPort: 7199
            name: jmx-port
          - containerPort: 8609
            name: inter-node-msg
          - containerPort: 9042
            name: cql-port
          - containerPort: 9160
            name: thrift-port
          - containerPort: 8983
            name: solr-port
          - containerPort: 8984
            name: solr-int-node
          - containerPort: 4040
            name: spark-app-port
          - containerPort: 7077
            name: spark-int-node
          - containerPort: 7080
            name: spark-m-web
          - containerPort: 7081
            name: spark-w-web
          - containerPort: 8090
            name: spark-job
          - containerPort: 9999
            name: spark-job-jmx
          - containerPort: 18080
            name: spark-histor
          - containerPort: 8182
            name: gremlin-port
          - containerPort: 5598
            name: dsefs-public
          - containerPort: 5599
            name: dsefs-private
          - containerPort: 61621
            name: ds-agent-port
          volumeMounts:
          - name: dse-data
            mountPath: /dse-data
          livenessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 10
  volumeClaimTemplates:
  - metadata:
      name: dse-data
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 40Gi

**Comment by gmflau** [comment]
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dse
spec:
  serviceName: "dse"
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dse
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: [dse]
              topologyKey: kubernetes.io/hostname
      containers:
        - name: dse
          image: gmflau/dse-server:5.1.5
          resources:
            requests:
              cpu: "2"
              memory: "4000Mi"
          env:
          - name: DS_LICENSE
            value: accept
          - name: SEEDS
            value: dse-0.dse
          - name: NUM_TOKENS
            value: "64"
          ports:
          - containerPort: 7000
            name: intra-node-port
          - containerPort: 7001
            name: tls-intra-node
          - containerPort: 7199
            name: jmx-port
          - containerPort: 8609
            name: inter-node-msg
          - containerPort: 9042
            name: cql-port
          - containerPort: 9160
            name: thrift-port
          - containerPort: 8983
            name: solr-port
          - containerPort: 8984
            name: solr-int-node
          - containerPort: 4040
            name: spark-app-port
          - containerPort: 7077
            name: spark-int-node
          - containerPort: 7080
            name: spark-m-web
          - containerPort: 7081
            name: spark-w-web
          - containerPort: 8090
            name: spark-job
          - containerPort: 9999
            name: spark-job-jmx
          - containerPort: 18080
            name: spark-histor
          - containerPort: 8182
            name: gremlin-port
          - containerPort: 5598
            name: dsefs-public
          - containerPort: 5599
            name: dsefs-private
          - containerPort: 61621
            name: ds-agent-port
          volumeMounts:
          - name: dse-data
            mountPath: /dse-data
          livenessProbe:
            tcpSocket:
              port: 9042
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 10
  volumeClaimTemplates:
  - metadata:
      name: dse-data
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 40Gi
```
