### ISSUE TITLE
Hpa cannot get metrics from heapster

### ISSUE THREAD

**Issue by charlesakalugwu** [kubernetes/kubernetes#57009]
I am having troubles getting horizontal pod autoscaling to work on my k8s cluster on aws as it seems it is unable to retrieve metrics from heapster

```yaml
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:27:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

I have heapster deployed and powering the kubernetes dashboard without issues. This is the heapster k8s manifest i have deployed

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: heapster-binding
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
---
# Heapster's pod_nanny monitors the heapster deployment & its pod(s), and scales
# the resources of the deployment if necessary.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: system:pod-nanny
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heapster-binding
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:pod-nanny
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.4.0
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes.summary_api:''
        - --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    k8s-app: heapster
```

I have deployed an application with horizontal pod autoscaling. However I can see from the `describe hpa` command for that deployment that there are issues  with the HPA unable to get resource metrics as shown below:

```yaml
$ kubectl describe hpa --namespace=staging avro-schema-registry-hpa 
Name:                                                     avro-schema-registry-hpa
Namespace:                                                staging
Labels:                                                   app=avro-schema-registry
                                                          confluent-version=3.3.1
                                                          env=staging
                                                          version=0.11.0.1
Annotations:                                              kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app":"avro-schema-registry","confluent-ver...
CreationTimestamp:                                        Thu, 30 Nov 2017 10:18:12 +0100
Reference:                                                Deployment/avro-schema-registry
Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):  <unknown> / 90%
  resource cpu on pods  (as a percentage of request):     <unknown> / 90%
Min replicas:                                             3
Max replicas:                                             7
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource memory: failed to get pod resource metrics: an error on the server ("Error: 'dial tcp 10.40.0.8:8082: getsockopt: connection timed out'\nTrying to reach: 'http://10.40.0.8:8082/apis/metrics/v1alpha1/namespaces/staging/pods?labelSelector=app%3Davro-schema-registry%2Cconfluent-version%3D3.3.1%2Cenv%3Dstaging%2Cversion%3D0.11.0.1'") has prevented the request from succeeding (get services http:heapster:)
Events:
  Type     Reason                        Age               From                       Message
  ----     ------                        ----              ----                       -------
  Warning  FailedGetResourceMetric       30s (x4 over 1h)  horizontal-pod-autoscaler  unable to get metrics for resource memory: failed to get pod resource metrics: an error on the server ("Error: 'dial tcp 10.40.0.8:8082: getsockopt: connection timed out'\nTrying to reach: 'http://10.40.0.8:8082/apis/metrics/v1alpha1/namespaces/staging/pods?labelSelector=app%3Davro-schema-registry%2Cconfluent-version%3D3.3.1%2Cenv%3Dstaging%2Cversion%3D0.11.0.1'") has prevented the request from succeeding (get services http:heapster:)
  Warning  FailedComputeMetricsReplicas  30s (x4 over 1h)  horizontal-pod-autoscaler  failed to get memory utilization: unable to get metrics for resource memory: failed to get pod resource metrics: an error on the server ("Error: 'dial tcp 10.40.0.8:8082: getsockopt: connection timed out'\nTrying to reach: 'http://10.40.0.8:8082/apis/metrics/v1alpha1/namespaces/staging/pods?labelSelector=app%3Davro-schema-registry%2Cconfluent-version%3D3.3.1%2Cenv%3Dstaging%2Cversion%3D0.11.0.1'") has prevented the request from succeeding (get services http:heapster:)
```

I can curl some those URLs from the k8s worker machines e.g. 

```yaml
$ curl -vvv http://10.40.0.8:8082/apis/metrics/v1alpha1/namespaces/staging/pods?labelSelector=app%3Davro-schema-registry%2Cconfluent-version%3D3.3.1%2Cenv%3Dstaging%2Cversion%3D0.11.0.1
*   Trying 10.40.0.8...
* Connected to 10.40.0.8 (10.40.0.8) port 8082 (#0)
> GET /apis/metrics/v1alpha1/namespaces/staging/pods?labelSelector=app%3Davro-schema-registry%2Cconfluent-version%3D3.3.1%2Cenv%3Dstaging%2Cversion%3D0.11.0.1 HTTP/1.1
> Host: 10.40.0.8:8082
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Mon, 11 Dec 2017 02:00:33 GMT
< Content-Length: 1535
< 
{
  "metadata": {},
  "items": [
   {
    "metadata": {
     "name": "avro-schema-registry-6b5475fdcd-9x8gb",
     "namespace": "staging",
     "creationTimestamp": "2017-12-11T02:00:33Z"
    },
    "timestamp": "2017-12-11T02:00:00Z",
    "window": "1m0s",
    "containers": [
     {
      "name": "avro-schema-registry",
      "usage": {
       "cpu": "1m",
       "memory": "561496Ki"
      }
     },
     {
      "name": "istio-proxy",
      "usage": {
       "cpu": "30m",
       "memory": "40064Ki"
      }
     }
    ]
   },
   {
    "metadata": {
     "name": "avro-schema-registry-6b5475fdcd-cwgnt",
     "namespace": "staging",
     "creationTimestamp": "2017-12-11T02:00:33Z"
    },
    "timestamp": "2017-12-11T02:00:00Z",
    "window": "1m0s",
    "containers": [
     {
      "name": "avro-schema-registry",
      "usage": {
       "cpu": "1m",
       "memory": "551252Ki"
      }
     },
     {
      "name": "istio-proxy",
      "usage": {
       "cpu": "31m",
       "memory": "40236Ki"
      }
     }
    ]
   },
   {
    "metadata": {
     "name": "avro-schema-registry-6b5475fdcd-d78gx",
     "namespace": "staging",
     "creationTimestamp": "2017-12-11T02:00:33Z"
    },
    "timestamp": "2017-12-11T02:00:00Z",
    "window": "1m0s",
    "containers": [
     {
      "name": "avro-schema-registry",
      "usage": {
       "cpu": "1m",
       "memory": "542496Ki"
      }
     },
     {
      "name": "istio-proxy",
      "usage": {
       "cpu": "32m",
       "memory": "41296Ki"
      }
     }
    ]
   }
  ]
* Connection #0 to host 10.40.0.8 left intact
 }

```

However it doesnt work when I try from within another pod in the cluster

```yaml
root@kafka-connect-564599bcc9-4pqjg:/# curl -vvv http://10.40.0.8:8082/apis/metrics/v1alpha1/namespaces/staging/pods?labelSelector=app%3Davro-schema-registry%2Cconfluent-version%3D3.3.1%2Cenv%3Dstaging%2Cversion%3D0.11.0.1
* Hostname was NOT found in DNS cache
*   Trying 10.40.0.8...
* Connected to 10.40.0.8 (10.40.0.8) port 8082 (#0)
> GET /apis/metrics/v1alpha1/namespaces/staging/pods?labelSelector=app%3Davro-schema-registry%2Cconfluent-version%3D3.3.1%2Cenv%3Dstaging%2Cversion%3D0.11.0.1 HTTP/1.1
> User-Agent: curl/7.38.0
> Host: 10.40.0.8:8082
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Mon, 11 Dec 2017 02:00:45 GMT
* Server envoy is not blacklisted
< server: envoy
< content-length: 0
< 
* Connection #0 to host 10.40.0.8 left intact
```

You can find the logs for my heapster deployment here: https://gist.github.com/charleslieferando/2a4768ce832a902a958e8dff6aba7113

Does someone know what might be the issue?
