### ISSUE TITLE
`volumes.emptyDir.sizeLimit` field is silently dropped

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#57058]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

`volumes.emptyDir.sizeLimit` cannot be set.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the following deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx
        name: nginx
      volumes:
      - name: foo
        emptyDir:
          sizeLimit: "300Mi"
```
2. Get the resource back 
```console
$ kubectl get deployment test -o yaml 
[...]
      volumes:
      - emptyDir: {}
        name: foo
```

**Anything else we need to know?**: #50163 might be related 
cc @liggitt @kow3ns @k8s-mirror-api-machinery-bugs 

**Environment**:
- Kubernetes version (use `kubectl version`): HEAD
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
