### ISSUE TITLE
stateful set feature requests 

### ISSUE THREAD

**Issue by TaChao** [kubernetes/kubernetes#57083]
1. Every pod have their own unique lable like name. So selector can select one pod .
2. Ingress support headless service
Eg:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        backend:
          serviceName: s1
          podName:app-0
          servicePort: 80
      - path: /bar
        backend:
          serviceName: s1
          podName:app-1
          servicePort: 80
```
