### ISSUE TITLE
CSI internal driver: mounter not passing fsGroup

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#57115]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When `fsGroup` is specified in a `securityContext`, the value of the fsGroup is not passed to the CSI driver to properly setup ownership. 

**What you expected to happen**:
The value of the `fsGroup` should be applied to the mounted path.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a Pod similar to the following 
```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    fsGroup: 2000
```
