### ISSUE TITLE
Allow referencing a TLS certificate / secret (secretName) residing in another namespace

### ISSUE THREAD

**Issue by frittentheke** [kubernetes/kubernetes#57325]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:

I tried to reference a TLS certificate / key with the _secretName_ variable of an ingress resource.

**What you expected to happen**:

One can use, and this is quite common, a single ingress controller for ingress of multiple namespaces.

Unfortunately the ingress resource may only reference a TLS certificate which resides in the own namespace in the secretName variable. Especially when using wildcard certificates or just a common hostname for multiple services in different namespaces this means the certificate (secret) needs to be duplicated in all namespaces which use it.

Apart from untidy duplication of things this gives (depending on your RBAC policies) the namespace admin access to the private key.

Enabling the ingress controller to reference a certificate which is located in another namespace (i.e. one only containing certificates) would allow for easier management of this shared piece of data and even protect it more.

**How to reproduce it (as minimally and precisely as possible)**:

```
 [...]
spec:
  tls:
    - hosts:
      - myhost.example.com
      secretName: anothernamespace/wildcard-for-example-com-tls
  rules:
    - host: myhost.example.com
      http:
        paths:
        - path: /
          backend:
            serviceName: myservice
            servicePort: 8080
[...] 
```

Referencing a secret inside i.e. _**anothernamespace**_  simply does not work...

**Anything else we need to know?**:

I opened this issue as https://github.com/kubernetes/ingress-nginx/issues/1829 towards the ingress-nginx project before.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS Container Linux
