### ISSUE TITLE
Issues with private Docker Cloud repos and the 1.9.0 CLI

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/kubernetes#57427]
/kind bug

We're having trouble retrieving images from a private registry on DockerCloud. For nearly a year the following has worked flawlessly. Last Friday I pulled down the 1.9.0 CLI (via brew) and since then have not been able to access any image in a private registry on DockerCloud. I've tried this on 10+ brand new clusters created with kops v1.8.0. The Kubernetes cluster version have been 1.8.0, 1.8.4, 1.8.5 and 1.9.0 (which is not supported by kops yet) and all exhibit the same problem.

We create the secret as such:
```
kubectl create secret docker-registry dockerclouduser \
    --docker-server=https://index.docker.io/v1/ \
    --docker-username={my-username} \
    --docker-password={my-password} \
    --docker-email={my-email}
```

And verify it using:
```
kubectl get secret dockerclouduser --output=json | jq --raw-output '.data | .".dockercfg"' | base64 -D | python -m json.tool
```

Which yields:
```
{
    "auths": {
        "https://index.docker.io/v1/": {
            "auth": "{what-appears-to-be-a-token}",
            "email": "{my-email}",
            "password": "{my-password}",
            "username": "{my-username}"
        }
    }
}
```

And create a test service with `kubectl create -f` with these contents:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-service
    spec:
      containers:
      - name: test-service
        image: {my-org}/{my-repo-name}:{my-tag}
        imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerclouduser
```

The pod fails immediatly with: 
```
Failed to pull image "{my-org}/{mmy-repo-name}:{my-tag}": rpc error: code = Unknown desc = Error response from daemon: repository {my-org}/{mmy-repo-name} not found: does not exist or no pull access
```

I've reviewed the 1.9.0 release notes and nothing jumps out as the root cause.

For reference I've tried putting quotes around the `{my-password}` value when creating the secret to no avail.

I've also tried prefixing the `spec.template.spec.containers.[0].image` value with `index.docker.io`, so the full value would read: `image: index.docker.io/{my-org}/{my-repo-name}:{my-tag}` also to no avail.

**Environment**:
Kubernetes version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:16:50Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud provider and installation info:
* AWS cluster built with Kops 1.8.0, using (to isolate this issue) nearly the default settings for everything.
