### ISSUE TITLE
flexvolume driver with `:` in name breaks

### ISSUE THREAD

**Issue by cpuguy83** [kubernetes/kubernetes#57510]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

When installing a flexvolume driver that has a name like `apple/banana:orange` (note the `:` in the name... because reasons) in the path `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/apple~banana:orange/banana:orange`, the kubelet is able to initialize this driver.
However, if I try to use it with a volume in a pod spec the kubelet logs are flooded with:

> desired_state_of_world_populator.go:288] Failed to add volume "test" (specName: "test") for pod "71652f74-e536-11e7-9f16-0242ac110002" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "test" err=no volume plugin matched

Unfortunately bumping up the kubelet logs doesn't help here.
Removing the `:` from the the driver name (and installing a new driver into the path with the changed name) works immediately.

**What you expected to happen**:

Pod should be able to attach to a volume from this driver.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install a example driver into `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/apple~banana:orange/banana:orange`
2. Create pod with this spec:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: testflexvolume
  namespace: default
spec:
  containers:
  - name: testflexvolume
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "apple/banana:orange"
      fsType: "nfs"
```

**Anything else we need to know?**:

This appears to either be from either
1. An issue converting the driver path into a driver name in kubelet
2. An issue converting the volume driver name from the pod spec into a volume spec

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.5", GitCommit:"cce11c6a185279d037023e02ac5249e14daa22bf", GitTreeState:"clean", BuildDate:"2017-12-07T18:09:00Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.2-docker.118+1239d98159da55", GitCommit:"1239d98159da5589eebab3f39f98409a8e424368", GitTreeState:"clean", BuildDate:"2017-12-14T20:04:42Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
AWS, t2

- OS (e.g. from /etc/os-release):
Ubuntu 16.04.2 LTS

- Kernel (e.g. `uname -a`):
> Linux bgoff-testkit-DB0747-ubuntu-0 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
Custom

- Others:
