### ISSUE TITLE
ResourceQuota admission controller fails to read AdmissionConfiguration

### ISSUE THREAD

**Issue by vikaschoudhary16** [kubernetes/kubernetes#57586]
/kind bug

**What happened**:
Tried to pass the following configuration to the kube-apiserver using  **--admission-control-config-file**

```
apiVersion: apiserver.k8s.io/v1alpha1
kind: AdmissionConfiguration
plugins:
- name: "ResourceQuota"
  configuration:
  - apiVersion: resourcequota.admission.k8s.io/v1alpha1
    kind: Configuration
    limitedResources:
    - resource: pods
```
Kube-apiserver fails to start with the following error:
> failed to initialize admission: no kind is registered for the type runtime.Unknown

**What you expected to happen**:
Expected kube-apiserver to start normally

**How to reproduce it (as minimally and precisely as possible)**:
* Just past above configuration in a yml file.
* Start kube-apiserver with the flag **--admission-control-config-file** set to the yml file name

**Anything else we need to know?**:
Investigated a bit on this. `AdmissionConfiguration` api object is:
```
// AdmissionPluginConfiguration provides the configuration for a single plug-in.
type AdmissionPluginConfiguration struct {
        // Name is the name of the admission controller.
        // It must match the registered admission plugin name.
        Name string

        // Path is the path to a configuration file that contains the plugin's
        // configuration
        // +optional
        Path string

        // Configuration is an embedded configuration object to be used as the plugin's
        // configuration. If present, it will be used instead of the path to the configuration file.
        // +optional
        Configuration runtime.Object
}
```
[When yaml file is read into memory](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/config.go#L70), `Configuration` object gets decoded as type `runtime.Unknown` .
Code flow then tries to [serialize it here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/config.go#L134) for getting an `io.Reader` . Here it returns the error message which is reported by kube-apiserver

**Work-Around**
Use two yaml files and pass first file name to the **--admission-control-config-file** flag and pass second file's name as `Path` in the first yaml, as shown below:
```
# cat /home/vikas/rq_adm_config.yaml 
apiVersion: apiserver.k8s.io/v1alpha1
kind: AdmissionConfiguration
plugins:
- name: "ResourceQuota"
  path: "rq-config.yaml"

# cat /home/vikas/rq-config.yaml 
apiVersion: resourcequota.admission.k8s.io/v1alpha1
kind: Configuration
limitedResources:
- resource: pods
  matchScopes:
  - "ResourceQuotaScopePriorityClassExists"
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersi}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.0.1424+f3024879423e61-dirty", GitCommit:"f3024879423e618ac1e6ff37e095ba218cb32450", GitTreeState:"dirty", Buil}
- Cloud provider or hardware configuration:
Baremetal
- OS (e.g. from /etc/os-release):
Red Hat Enterprise Linux Server release 7.3 (Maipo)
- Kernel (e.g. `uname -a`):
3.10.0-514.21.1.el7.x86_64
- Install tools:
- Others:

**Comment by vikaschoudhary16** [comment]
/cc @nikhita 
@kubernetes/sig-api-machinery-bugs 
/sig node

**Comment by hzxuzhonghu** [comment]
@vikaschoudhary16 I think it's because ` resourcequota.admission.k8s.io/v1alpha1` apiResource is not enabled, can you try to enable it with `--runtime-config=resourcequota.admission.k8s.io/v1alpha1`?

**Comment by vikaschoudhary16** [comment]
@hzxuzhonghu Please take a look at `work-around` in the issue description. `resourcequota.admission.k8s.io/v1alpha1` works if configuration is break into two files. Therefore i dont think api is disabled.

**Comment by hzxuzhonghu** [comment]
I find your yaml is wrong, configuration is not an array.
```
apiVersion: apiserver.k8s.io/v1alpha1
kind: AdmissionConfiguration
plugins:
- name: "ResourceQuota"
  configuration:
    apiVersion: resourcequota.admission.k8s.io/v1alpha1
    kind: Configuration
    limitedResources:
    - resource: pods
```
