### ISSUE TITLE
Moving deployment from v1beta1 to v1beta2 inconsistent validation

### ISSUE THREAD

**Issue by Stono** [kubernetes/kubernetes#57606]
I have been upgrading some of my Deploymens from `apps/v1beta1` to `apps/v1beta2` on kubernetes `1.8.4` and seem to have differences in yaml validation which mean my upgrades are inconsistent with fresh deployments (ie the upgrade works fine, but if we needed to rebuild, it'd fail).

Take the following `v1beta1` yaml, with no `spec.selector.matchLabels`, in v1beta1 these were calculated if omitted.
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
```

**Observed behaviour**
If I was to simply make a single change to this yaml file to switch to `v1beta2`, which is actually **invalid**, as `spec.selector.matchLabels` is required in >= v1beta2 

```
apiVersion: apps/v1beta2
kind: Deployment
...
```

The apply is accepted by the server:
```
❯ kubectl apply -f test.yaml
deployment "nginx-deployment" configured
```

However if I was to delete that deployment, and try and recreate it, it would (correctly) error:

```
❯ kubectl delete deployment nginx-deployment
deployment "nginx-deployment" deleted

❯ kubectl apply -f test.yaml
The Deployment "nginx-deployment" is invalid:
* spec.selector: Required value
* spec.template.metadata.labels: Invalid value: map[string]string{"app":"nginx"}: `selector` does not match template `labels`
```

**Expected behaviour**
I believe the yaml file presented in using an `apply` in an upgrade scenario should be validated in the same way in which it would be in a create.

It *feels* like the validation for an apply is being done after a computed merge with what is already deployed, in a "upgrade" case, the matchLabels were pre-computed, but in a create case, they're not. 

I hope you can see how this would leave me in a slightly uncomfortable position because I had been presuming that if a yaml file could be `applied` then it was valid, and should we ever need to rebuild  or fresh deploy (for example the first time an app is promoted to a new environment) then those yaml files would not work.

At the least I feel this validation should be documented / explained so others don't get caught out!
