### ISSUE TITLE
PersistentVolume and PersistentVolumeClaim confusing behaviour

### ISSUE THREAD

**Issue by Mulkave** [kubernetes/kubernetes#57608]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

/sig storage

**What happened**:
Creating a deployment with one container mounting a volume using persistent volume claim, the template includes a `PersistentVolume` kind. The end result is two volumes being created and the claim being mounted to the "generated" one and not the one included in the template.

**What you expected to happen**:
The volume claim to bound to the volume specified in the template and not create a new volume.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl apply -f template.yml`

```yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: neo4j
  labels:
    alias: neo4j
spec:
  selector:
    matchLabels:
      alias: neo4j
  template:
    metadata:
      labels:
        alias: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j
        ports:
        - containerPort: 7474
        - containerPort: 7687
        volumeMounts:
        - name: neo4j-persistent-storage
          mountPath: /data
      volumes:
      - name: neo4j-persistent-storage
        persistentVolumeClaim:
          claimName: neo4j-storage-claim
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-data-volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/neo4j
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo4j-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```

**Anything else we need to know?**:

The following screenshot explains the end result of applying the template.

![screen shot 2017-12-24 at 11 45 29 pm](https://user-images.githubusercontent.com/2647333/34329327-9b27ae9e-e904-11e7-9c26-c710fdde7d74.png)

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:16:50Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: *minikube* (local)
- OS (e.g. from /etc/os-release): macOS High Sierra version 10.13.2 (17C88)
- Kernel (e.g. `uname -a`): `Darwin mulkave 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64`
- Install tools: Minikube
- Others:

**Comment by linyouchong** [comment]
Do you have a default storageclass in cluser?

**Comment by Mulkave** [comment]
@linyouchong i'm new to this area, how can i check this? If no default then no, i haven't created one myself. And what difference would it make?

**Comment by Mulkave** [comment]
After reading the docs here: http://blog.kubernetes.io/2017/03/dynamic-provisioning-and-storage-classes-kubernetes.html

> If there are no StorageClass objects marked with the default annotation, then PersistentVolumeClaim objects (without a StorageClass specified) will not trigger dynamic provisioning. They will, instead, fall back to the legacy behavior of binding to an available PersistentVolume object.

I was able to force the use of the mentioned volume by adding an empty `storageClassName` in the claim which will fallback to what's mentioned earlier. Feels like a workaround rather than a solution though, is there a best practice for this?

Here's the final version that worked.

```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-data-volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/neo4j
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo4j-storage-claim
  namespace: dev
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```

As I understood from the docs about `StorageClass`
