### ISSUE TITLE
kube-dns should support custom tolerations

### ISSUE THREAD

**Issue by JeanMertz** [kubernetes/kubernetes#57659]
/kind feature

(note: we're not using the latest Kubernetes version yet, but I couldn't find any changes related to this in the latest updates, so please close this if I simply updating will fix this for us)

Currently, when you edit a kube-dns deployment, some changes are persisted (f.e. adding a `nodeAffinity` config block), while others are reverted (f.e. adding a second toleration to the already existing `CriticalAddonsOnly` toleration).

The last example is problematic for us (running on GKE).

We have two node pools:

- a regular node pool with a taint applied to the nodes to only allow pods to run on them that we manually approve
- a preemptible node pool without any taints

We want `kube-dns` (and any other critical pods) to run on the regular nodes for better uptime (see also: https://github.com/kubernetes/kubernetes/issues/41125), so we update its deployment with the following blocks:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: type
          operator: In
          values:
          - regular
```

```yaml
tolerations:
- key: CriticalAddonsOnly # this one is already present by default
  operator: Exists
- key: dedicated # we add this one to allow scheduling on the tainted regular nodes
  operator: Equal
  value: regular
  effect: NoSchedule
```

After saving this change, for a brief moment, the pods are scheduled as expected, but moments after, the change is reverted, and specifically the added toleration is removed, the nodeAffinity is still there however.

Can we make toleration changes persistent and not be reverted by the API itself?

**Environment**:

- Kubernetes version (use `kubectl version`):

    ```
    Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:08:42Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.3-gke.0", GitCommit:"86d3ac5eaf57223302c95e7d9fc1aeff55fb0c15", GitTreeState:"clean", BuildDate:"2017-11-08T21:42:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
    ```

- Cloud provider or hardware configuration: GKE
