### ISSUE TITLE
PVC pending Failed to get GCE GCECloudProvider with error <nil>

### ISSUE THREAD

**Issue by YDD9** [kubernetes/kubernetes#57725]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

1. Created a Dynamic StorageClass Fast in k8s cluster
2. Make StorageClass Fast as default
3. Create a PVC bind with StorageClass Fast

error:
 Failed to provision volume with StorageClass "fast": Failed to get GCE GCECloudProvider with error <nil>

**What you expected to happen**:
PVC is created correctly and bind with StorageClass Fast

**How to reproduce it (as minimally and precisely as possible)**:
Cluster is setup with kubeadm, so no SC is created.

DynamicSC.yaml to create SC
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
```
Make SC fast as cluster default
```
$ kubectl patch storageclass fast -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

$ kubectl get sc
NAME             PROVISIONER            AGE
fast (default)   kubernetes.io/gce-pd   28m
```

DynamicPVC.yaml used to create PVC
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 1Gi
  VolumeName: mysql-persistent-storage
```

```
$ kubectl describe pvc
Name:          mysql-pv-claim
...
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  ProvisioningFailed  12s   persistentvolume-controller  Failed to provision volume with StorageClass "fast": Failed to get GCE GCECloudProvider with error <nil>
```

**Anything else we need to know?**:
error found on node:
332 desired_state_of_world_populator.go:273] Error processing volume "mysql-persistent-storage" for pod "mysql-544bbdcd6f-zhzmd_default(868bf823-ef3a-11e7-8bf0-0800274f1ac0)": error processing PVC "default"/"mysql-pv-claim": PVC default/mysql-pv-claim has non-bound phase ("Pending") or empty pvc.Spec.VolumeName ("")

stackoverflow answers
https://stackoverflow.com/questions/37421540/container-vm-image-with-gpd-volumes-fails-with-failed-to-get-gce-cloud-provider

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
DELL5520  win10, VirtualBox5.2
Not in Cloud

- OS (e.g. from /etc/os-release): 
Debian9.3 stretch
One master, one node

- Kernel (e.g. `uname -a`):
Linux node40 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

- Install tools:
kubeadm1.9

- Others:
