### ISSUE TITLE
$(HOSTNAME) not replaced in args

### ISSUE THREAD

**Issue by prestonvanloon** [kubernetes/kubernetes#57726]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Given the following pod configuration: 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["/bin/echo"]
    args: ["$(HOSTNAME)"]
  restartPolicy: OnFailure
```

This pod echoed literately `$(HOSTNAME)`.

**What you expected to happen**:

The pod to echo `command-demo` (the pod name).

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl apply -f pod.yaml
kubectl logs command-demo
```

**Anything else we need to know?**:

This works for other environment variables such as `KUBERNETES_SERVICE_HOST`.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: `minikube version: v0.21.0`
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```
- Kernel (e.g. `uname -a`):
`Linux naydra 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by prestonvanloon** [comment]
I'm not 100% sure on the label...
@kubernetes/sig-scheduling-bug

**Comment by cjcaj** [comment]
You could use the downward API to expose the pod name:
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

**Comment by prestonvanloon** [comment]
@cjcaj Thanks for the tip. I think this is still a valid issue because you can access HOSTNAME as the environment variable (i.e. `printenv HOSTNAME`), but cannot pass it as an argument.

My current workaround is to execute the command from bash as such:

```
       command: 
           - "/bin/bash"
           - "-c"
           - "echo $HOSTNAME"
```

**Comment by cristifalcas** [comment]
I would like to use this also. HOSTNAME to be replaced in arguments

**Comment by Ochir** [comment]
I also vote for this feature request

**Comment by prestonvanloon** [comment]
@discordianfish my specific use case is to use the hostname of a pod created by some deployment. 

Does the downward API provide this as a command line argument or simply making it available as an environment variable? If the case is the latter, then I'm in the same spot. I can already access the HOSTNAME via environment variable, but I can't intuitively provide it as a command argument.

**Comment by discordianfish** [comment]
@prestonvanloon It makes it available as env variable *and* available for templating. Just try setting HOSTNAME via the downward api and you should be able to refer to it in your args like you do, e.g:

```
apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["/bin/echo"]
    args: ["$(NODE_NAME)"]
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
```

**Comment by discordianfish** [comment]
Can this be closed?

If anything this is a documentation issue. I see how it's confusing that these arg variable references look like environment variables although they are not.

**Comment by cristifalcas** [comment]
This is not true for provider aws. In this case it will put the internal aws name of the instance, not the hostname

**Comment by discordianfish** [comment]
@cristifalcas It will pull in the kubernetes node name. Is there a reason for having a different name there than your hostname? Not sure what exact setup you run on AWS, but I'd argue the node name should ideally be the same as the hostname.

**Comment by cristifalcas** [comment]
It's a bug in k8s: https://github.com/kubernetes/kubernetes/issues/54482

**Comment by prestonvanloon** [comment]
@discordianfish Please look at my original example, I need the pod's name, not the node's name.

**Comment by discordianfish** [comment]
@prestonvanloon Then use the pod name instead? Did you read the docs? https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#capabilities-of-the-downward-api

**Comment by prestonvanloon** [comment]
@discordianfish Thanks! That would work for me. 

It is not as ideal as using the $HOSTNAME, but it would solve my problem. 

I'll go ahead and close this as my issue has a workaround with the downward API.

**Comment by gertcuykens** [comment]
Just want to add this for completion because it took me some time to figure out
```
    env:
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
```
