### ISSUE TITLE
kube-dns fails to restart conditionally

### ISSUE THREAD

**Issue by DaiHao** [kubernetes/kubernetes#57753]
> /kind bug

**What happened**:
I build the fault scene by injecting file handle, then kube-dns pod fails to start and stays in CrashLoopBackOff state. 

Here is kube-dns's config file and my kubernetes version is 1.5.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    version: v17
  name: kube-dns-v17
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      podaffinity: kube-dns-pod
      version: v17
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      enable: true
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"
        podaffinity: kube-dns-pod
        version: v17
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /kube-dns --domain=cluster.local.
          --dns-port=10053
        image: cfe-kubedns-amd64:2.12.27
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: kubedns
        ports:
        - containerPort: 10053
          name: dns-local
          protocol: UDP
        - containerPort: 10053
          name: dns-tcp-local
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
      - command:
        - /bin/sh
        - -c
        - /usr/sbin/dnsmasq --keep-in-foreground
          --port=5353 --cache-size=1000 --no-resolv --server=127.0.0.1#10053
        image: cfe-kube-dnsmasq-amd64:2.12.27
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: dnsmasq
        ports:
        - containerPort: 5353
          name: dns
          protocol: UDP
        - containerPort: 5353
          name: dns-tcp
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
      - command:
        - /bin/sh
        - -c
        - /exechealthz -cmd='nslookup -po=5353
          kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null' -port=8080 -quiet
        image: cfe-exechealthz-amd64:2.12.27
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: healthz
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 20Mi
          requests:
            cpu: 50m
            memory: 20Mi
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
      dnsPolicy: Default
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
```
      

**How to reproduce it (as minimally and precisely as possible)**:
It occurs Conditionally.

**Anything else we need to know?**:
There is a circular dependency in this pod. It likes the containers died one after another. One container starts but its dependency have not started, then it dies.  

**Environment**:
- Kubernetes version (use `kubectl version`):
1.5

**Comment by nkwangleiGIT** [comment]
@DaiHao you can try by removing the livenessProbe blow first to see if it's restarting due to health check.

```
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
```
