### ISSUE TITLE
Seccomp feature broken?

### ISSUE THREAD

**Issue by gertdetlef** [kubernetes/kubernetes#57787]
/kind bug
@kubernetes/sig-api-machinery-bugs
/sig api-machinery

I tried to set up the seccomp chmod prevention example (https://blog.jetstack.io/blog/kubernetes-1-3-hidden-gems/) and was unable to let it run.

I used the following profile file /var/lib/kubelet/seccomp/prevent-chmod:
```
{
  "defaultAction": "SCMP_ACT_ALLOW",
  "syscalls": [
    {
      "name": "chmod",
      "action": "SCMP_ACT_ERRNO"
    }
  ]
}
```
I used the following POD config:
```
apiVersion: v1
kind: Pod
metadata:
  name: chmod-prevented
  annotations:
    container.seccomp.security.alpha.kubernetes.io/chmod: localhost/prevent-chmod
    #seccomp.security.alpha.kubernetes.io/pod: localhost/prevent-chmod DOESN'T WORK either
spec:
  containers:
  - name: chmod
    image: busybox
    command:
      - "chmod"
    args:
      - "666"
      - /etc/hostname
  restartPolicy: Never
```
When using "docker/default" or "unconfined", it is working fine. But neither the POD nor the container annotation work – both result in:
```
... localkube[1261]: E0103 10:31:29.955160    1261 remote_runtime.go:187] CreateContainer in sandbox "b864575cf9858462ae260cefeebaa7ee4c45a6e4c7e69c0ab5c078507626b1c4" from runtime service failed: rpc error: code = Unknown desc = failed to generate security options for container "chmod": failed to generate seccomp security options for container: unknown seccomp profile option: /var/lib/kubelet/seccomp/prevent-chmod
... localkube[1261]: E0103 10:31:29.955282    1261 kuberuntime_manager.go:714] container start failed: CreateContainerError: failed to generate security options for container "chmod": failed to generate seccomp security options for container: unknown seccomp profile option: /var/lib/kubelet/seccomp/prevent-chmod
```

While trying to find my error, I came accross https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/helpers_linux.go that raises this error message here:
```
func getSeccompDockerOpts(seccompProfile string) ([]dockerOpt, error) {
	if seccompProfile == "" || seccompProfile == "unconfined" {
		// return early the default
		return defaultSeccompOpt, nil
	}

	if seccompProfile == "docker/default" {
		// return nil so docker will load the default seccomp profile
		return nil, nil
	}

	if !strings.HasPrefix(seccompProfile, "localhost/") {
		return nil, fmt.Errorf("unknown seccomp profile option: %s", seccompProfile)
        }
        ...
```
It looks to me that the localhost was cut-off somewhere before...

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"f0efb3cb883751c5ffdbe6d515f3cb4fbe7b7acd", GitTreeState:"clean", BuildDate:"2017-11-08T18:39:33Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Sufficient:-)
- OS (e.g. from /etc/os-release): Ubuntu 17.04
- Kernel (e.g. `uname -a`): Linux laptop-p51 4.10.0-42-generic #46-Ubuntu SMP Mon Dec 4 14:38:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: minicube
- Others:
