### ISSUE TITLE
Error when trying to reference metadata.name as persistentVolumeClaim.claimName

### ISSUE THREAD

**Issue by arongu** [kubernetes/kubernetes#57837]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig apps

**What happened**:
Unable to get `meta.name` field as `string` for `persistentVolumeClaim.claimName` using downward api.
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka-nfs-test
  namespace: kafka
spec:
  serviceName: "kafka-service-test"
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu-test
    spec:
      containers:
      - image: ubuntu:latest
        name: ubuntu
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]        
      volumes:
      - name: storage
         persistentVolumeClaim:
           claimName:
             fieldRef:
               fieldPath: metadata.name
```

```
error validating data: ValidationError(StatefulSet.spec.template.spec.volumes[0].persistentVolumeClaim.claimName): invalid type for io.k8s.kubernetes.pkg.api.v1.PersistentVolumeClaimVolumeSource.claimName: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:
According to `kubectl explain:`

`kubectl explain StatefulSet.spec.template.metadata.name`
`FIELD: name <string>`

`kubectl explain StatefulSet.spec.template.spec.volumes.persistentVolumeClaim.claimName`
`FIELD: claimName <string>`

I would expect the downward api would resolve the field `metadata.name` for the `claimName` as a string. Instead it returns a map.

**How to reproduce it (as minimally and precisely as possible)**:
Reference the field `metadata.name` as `claimName` for a `persistentVolumeClaim`.

**Environment**:
- Kubernetes version (use `kubectl version`): ```kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.7-rancher1", GitCommit:"a1ea37c6f6d21f315a07631b17b9537881e1986a", GitTreeState:"clean", BuildDate:"2017-10-02T21:33:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}```
