### ISSUE TITLE
Cannot scale down statefulset if pods keep CrashLoopBackOff

### ISSUE THREAD

**Issue by harryge00** [kubernetes/kubernetes#57865]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
1. Create a statefulset which will never be running:
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: failss
spec:
  serviceName: "failss"
  replicas: 2
  selector:
    matchLabels:
      app: failss
  template:
    metadata:
      labels:
        app: failss
    spec:
      containers:
      - name: failss
        image: debian:7.8
        args:
        - "1"
        command:
        - exit
```
2. Scale down it
```
kubectl scale statefulset failss --replicas=0
```
3. check the pods
```
# kubectl get statefulset
NAME      DESIRED   CURRENT   AGE
failss          0         0         35m
# kubectl get pods
NAME                                          READY     STATUS             RESTARTS   AGE
failss-0                                     0/1       CrashLoopBackOff   11         35m
```
4. It seems like only running pods will be deleted. And CrashLoopBackOff pods are not included into "CURRENT" pod.

**What you expected to happen**:
I guess the failss-0 should be deleted after replicas set to 0, but it doesn't.
Is such behavior designed by purpose?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Change `statefulset` to `replicationcontrollers`, and it can be scaled down...
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: failrc
spec:
  replicas: 1
  selector:
    app: failrc
  template:
    metadata:
      name: failrc
      labels:
        app: failrc
    spec:
      containers:
      - name: failrc
        image: debian:7.8
        ports:
        - containerPort: 80
        args:
        - "1"
        command:
        - exit
```
```
# kubectl scale replicationcontroller failrc --replicas=0
# kubectl get pods
```
Now the crashloopbackoff pods got deleted...

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.7-beta.0+$Format:%h$", GitCommit:"bb053ff0cb25a043e828d62394ed626fda2719a1", GitTreeState:"dirty", BuildDate:"2017-08-26T09:34:19Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.7-beta.0+$Format:%h$", GitCommit:"a8687ef052b367fee6f94de533940eccaf7890cd", GitTreeState:"clean", BuildDate:"2017-09-06T08:32:34Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):  debian
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
