### ISSUE TITLE
loadBalancerSourceRanges service spec should allow service Tag strings

### ISSUE THREAD

**Issue by djsly** [kubernetes/kubernetes#57914]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
When using the loadBalancerSourceRanges property of a service in a manifest, we are force to use a CIDR block.

This was discovered while debugging the following issue. https://github.com/kubernetes/kubernetes/issues/56086

**What you expected to happen**:
Azure allows us to use Service Tags (e.g. VirtualNetwork, Internet, etc) WE should be able to specify them form a k8s service manifest.

**How to reproduce it (as minimally and precisely as possible)**:

```
spec:
{%- if cloud_provider == 'azure' %}
  type: LoadBalancer
{%- if kubemaster_subnet_cidr and kubenode_subnet_cidr %}
  loadBalancerSourceRanges:
    - {{ kubemaster_subnet_cidr }}
    - {{ kubenode_subnet_cidr }}
    - VirtualNetwork
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.11
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): centOS 7.3
- Kernel (e.g. `uname -a`): 3.10
- Install tools:
- Others:
