### ISSUE TITLE
Can't mount configmap with files as a folder, the POD starts and the folder is empty

### ISSUE THREAD

**Issue by jryberg** [kubernetes/kubernetes#57972]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Can't mount configmap as folder, the folder is empty, no error messages.

**What you expected to happen**:
Each file in the configmap should be files in the folder

**How to reproduce it (as minimally and precisely as possible)**:
Using Kubernetes own examples on Google Kubernetes Engine
https://kubernetes-v1-4.github.io/docs/user-guide/configmap/
ConfigMaps can also be consumed in volumes. Returning again to our example ConfigMap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  special.how: very
  special.type: charm
```

We have a couple different options for consuming this ConfigMap in a volume. The most basic way is to populate the volume with files where the key is the filename and the content of the file is the value of the key:

```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "cat /etc/config/special.how" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  restartPolicy: Never
```

In this example, /etc/config does not exist and the container does not echo "very". 

I was trying somewhat different when I noticed this issue and started to look for the solution. The main difference is that I'm creating the configmap --from-file instead of key-values in the example but both Kubernetes example and my own POD definition behaves the same.  

> kubectl create configmap config-files --from-file=/tmp/config-files

It simply don't populate the folder with files.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.5-gke.0
- Cloud provider or hardware configuration: Google Kubernetes Engine
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3
- Kernel (e.g. `uname -a`): Linux gke-k8s-engine-default-pool-650ecd7a-lxsb 4.4.0-1027-gke #27-Ubuntu SMP Thu Aug 10 13:13:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
