### ISSUE TITLE
CRDs merge-patch failing with "unable to find api field in struct Unstructured for the json field "metadata""

### ISSUE THREAD

**Issue by dulek** [kubernetes/kubernetes#58017]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Under heavy load (~50 similar request going into API simultaneously) I'm starting to sometimes get:

```
1 status.go:64] apiserver received an error that is not an metav1.Status: unable to find api field in struct Unstructured for the json field "metadata"
1 wrap.go:42] PATCH /apis/openstack.org/v1/kuryrports/5a114c6b-0f24-4202-b1ae-3669286416a1: (5.793432ms) 500
```

when trying to do an update on my CRD:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kuryrports.openstack.org
spec:
  group: openstack.org
  version: v1
  scope: Cluster
  names:
    plural: kuryrports
    singular: kuryrport
    kind: KuryrPort
    shortNames:
    - kp
```

The update is in a form of ``application/merge-patch+json`` and its content look like this:

```
{
  "metadata": {
    "annotations": {
      "podName": ""
    },
    "resourceVersion": 123
  }
}
```

On failure the requests are repeated in 1 second intervals, if I wait long enough (few repeats of each) all of them will eventually succeed.

**What you expected to happen**:

I expect request to either succeed or get ``409 Conflict`` if something else updated the resource before me.

**How to reproduce it (as minimally and precisely as possible)**:

I don't have a synthetic example, but I think _What happened_ section describes the situation.

**Anything else we need to know?**:

API client is implemented in Python using requests library.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

QEMU VM on libvirt.

- OS (e.g. from /etc/os-release):

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

- Kernel (e.g. `uname -a`):

```
Linux localhost 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:

kuryr-kubernetes DevStack plugin (hyperkube in a container).

- Others:

**Comment by liggitt** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/42644#issuecomment-354934280

**Comment by liggitt** [comment]
actually, not quite a duplicate. #42644 means conflict cases are hit more often then they should be, but in legitimate conflict cases, this issue would still occur. When a patch conflict occurs, the server assumes it can compute strategic merge patches for the server side and submitted changes to detect overlapping patch content. That assumption is incorrect for CRDs

**Comment by dulek** [comment]
@liggitt: Just a note - this is **not** a strategic merge. Strategic merge on CRDs is failing immediately with information that it is not supported - which is nice. :)

**Comment by dulek** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
> this is not a strategic merge. Strategic merge on CRDs is failing immediately with information that it is not supported - which is nice. :)

understood... it's the fallback to use strategic merge patches internally that is causing problems:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go#L266-L306

**Comment by mattfarina** [comment]
FYI, Helm recently upgraded to client-go and api-machinery for k8s 1.9. Helm users are now starting to experience this bug. For example, it's impacting istio users. There are some details on kubernetes/helm#3382.

It may be worth noting that this impacts projects like istio that are used with Kubernetes. Istio uses CRDs today.

While the issue is in SIG API Machinery it's already starting to impact SIG Apps because of those running workloads in k8s.

**Comment by Stono** [comment]
It's also worth noting that the original issue above mentioned "under load".  I can confirm the issues in the linked helm issue occur consistently and load is not a factor

**Comment by liggitt** [comment]
> I can confirm the issues in the linked helm issue occur consistently and load is not a factor

If you are encountering this issue outside of load situations where frequent patches are being done on the same object, then you are observing a different issue

**Comment by Stono** [comment]
@liggitt could you have a quick read of https://github.com/kubernetes/helm/issues/3382 please and advise if you want a separate issue raising then?

**Comment by nikhita** [comment]
I haven't tried the example given inhttps://github.com/kubernetes/helm/issues/3382#issuecomment-363151748 with Helm but it works for me with kubectl:

1. Create the CRD

```yaml
$ cat crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: routerules.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: RouteRule
    listKind: RouteRuleList
    plural: routerules
    singular: routerule
  version: v1alpha2

$ kubectl create -f crd.yaml
customresourcedefinition "routerules.config.istio.io" created
```

2. Create the custom resource.

```yaml
$ cat cr.yaml
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: some-service-policy
  labels:
    another: label
    app: at-consumer-platform
    chart: helm-at-consumer-platform-0.1.184
    heritage: Tiller
    release: at-consumer-platform
    version: 23
spec:
  destination:
    name: some-service
  httpReqRetries:
    simpleRetry:
      attempts: 1
  httpReqTimeout:
    simpleTimeout:
      timeout: 1

$ kubectl apply -f cr.yaml
routerule "some-service-policy" created

$ kubectl get routerule some-service-policy -o jsonpath="{.metadata.labels.version}"
23
```

3. Change `.metadata.labels.version` to 24 and apply again:

```sh
$ kubectl apply -f cr.yaml
routerule "some-service-policy" configured

$ kubectl get routerule some-service-policy -o jsonpath="{.metadata.labels.version}"
24
```
