### ISSUE TITLE
[1.9 bug] v1.List error: unable to recognize apps/v1, Kind=DaemonSet: no matches for apps/, Kind=DaemonSet

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#58179]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:

```
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    ...
  - apiVersion: extensions/v1beta1
    # BUG(harry): can not use apps/v1 here since v1.List does not support apps/v1. It should be fixed in upstream.
    kind: DaemonSet
```

**What you expected to happen**:

Should be able to use `- apiVersion: apps/v1` in` v1.List` object.

**How to reproduce it (as minimally and precisely as possible)**:

Create a v1.List in 1.9 cluster with DaemonSet

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Kubernetes 1.9.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: scripts
- Others:

**Comment by liggitt** [comment]
cannot recreate this:

list.yaml:
```yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sa
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: ds
  spec:
    selector:
      matchLabels:
        foo: bar
    template:
      metadata:
        name: ds-pod
        labels:
          foo: bar
      spec:
        containers:
        - name: c
          image: busybox
```

```sh
$ kubectl version -o json
{
  "clientVersion": {
    "major": "1",
    "minor": "9",
    "gitVersion": "v1.9.0",
    "gitCommit": "925c127ec6b946659ad0fd596fa959be43f0cc05",
    "gitTreeState": "clean",
    "buildDate": "2018-01-13T07:11:58Z",
    "goVersion": "go1.9.2",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "9",
    "gitVersion": "v1.9.0",
    "gitCommit": "925c127ec6b946659ad0fd596fa959be43f0cc05",
    "gitTreeState": "clean",
    "buildDate": "2018-01-13T07:11:58Z",
    "goVersion": "go1.9.2",
    "compiler": "gc",
    "platform": "darwin/amd64"
  }
}

$ kubectl create -f list.yaml --v=6
I0113 02:15:01.363925   99357 decoder.go:224] decoding stream as YAML
I0113 02:15:01.384853   99357 round_trippers.go:436] POST https://localhost:6443/api/v1/namespaces/default/serviceaccounts 201 Created in 16 milliseconds
serviceaccount "sa" created
I0113 02:15:01.412270   99357 round_trippers.go:436] POST https://localhost:6443/apis/apps/v1/namespaces/default/daemonsets 201 Created in 23 milliseconds
daemonset "ds" created
```
