### ISSUE TITLE
CSI - fsType is not being passed to driver

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#58183]
/kind bug

**What happened**:
Unable to specify fsType from a CSI PV.  The fsType is currently hardcoded to ext4.

**What you expected to happen**:
Being able to specify fsType when creating a CSI PV
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manually-created-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: com.example.team/csi-driver
    volumeHandle: existingVolumeName
    readOnly: false
    fsType: ext4
```
