### ISSUE TITLE
Mount Options not honored for Persistent Volume Claim Tempaltes

### ISSUE THREAD

**Issue by Stono** [kubernetes/kubernetes#58239]
Hi,
I am trying to mount a persistent volume in a statefulset with some custom options.  This does not appear to be working.

Kubernetes 1.8.5 on GKE.
 
I have the following StatefulSet:
```
...
  volumeClaimTemplates:
  - metadata:
      name: ssd0
      annotations:
        volume.beta.kubernetes.io/mount-options: "discard"
    spec:
      storageClassName: elastic-ssd
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 150Gi
```

Which creates the following pvc, with my annotations:
```
❯ k describe pvc ssd0-karl-0
Name:          ssd0-karl-0
Namespace:     default
StorageClass:  elastic-ssd
Status:        Bound
Volume:        pvc-e2d5a0af-f86e-11e7-8a0c-42010a9a017c
Labels:        app=karl
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
               volume.beta.kubernetes.io/mount-options=discard
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/gce-pd
Capacity:      150Gi
Access Modes:  RWO
```

Which creates the following pv (without the volume.beta.kubernetes.io/mount-options):
```
❯ k describe pv pvc-fb742a60-f86f-11e7-8a0c-42010a9a017c
Name:            pvc-fb742a60-f86f-11e7-8a0c-42010a9a017c
Labels:          failure-domain.beta.kubernetes.io/region=europe-west2
                 failure-domain.beta.kubernetes.io/zone=europe-west2-a
Annotations:     kubernetes.io/createdby=gce-pd-dynamic-provisioner
                 pv.kubernetes.io/bound-by-controller=yes
                 pv.kubernetes.io/provisioned-by=kubernetes.io/gce-pd
StorageClass:    elastic-ssd
Status:          Bound
Claim:           default/ssd0-karl-0
Reclaim Policy:  Delete
Access Modes:    RWO
Capacity:        150Gi
Message:
Source:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     gke-elastic-dev-429310-pvc-fb742a60-f86f-11e7-8a0c-42010a9a017c
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
Events:         <none>
```

Which in turn does not mount my disk with the options i expected:
```
❯ k exec -it karl-0 /bin/sh
/ # mount
/dev/sdb on /data/ssd0 type ext4 (rw,relatime,data=ordered)
```
