### ISSUE TITLE
privileged container can't see custom mapping device name inside the container

### ISSUE THREAD

**Issue by wenlxie** [kubernetes/kubernetes#58251]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
Now k8s start to support raw block device.
When I start to run a pod like:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-volume-mode
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "360000"
    image: ubuntu
    imagePullPolicy: Always
    name: busybox
    volumeDevices:
    - devicePath: /dev/vda
      name: myclaim
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
      priviledged: true
  serviceAccount: default
  serviceAccountName: default
  volumes:
  - name: myclaim
    persistentVolumeClaim:
      claimName: pvc-1
```
The container is run as `--priviledged`, but I can't see the device /dev/vda when exec to the container.
When I run the following command to start a container via  docker directly:
`docker run -it --device=/dev/sdc4:/dev/vda --privileged ubuntu /bin/bash`
The `/dev/vda` is also not exists.

I create an issue to moby: https://github.com/moby/moby/issues/35991
This is what docker works now.

For k8s, the host device is abstracted as a `PersistentVolume`, users don't know the host device name, they only know the custom mapping device name. So when they want to start a --priviledged container, the custom mapping device name missed will make the users doesn't know where to get the host  device name.
