### ISSUE TITLE
Bug v1:Endpoint - Required value: must specify `addresses` or `notReadyAddresses`

### ISSUE THREAD

**Issue by BrianBlandKY** [kubernetes/kubernetes#58369]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Unable to create Endpoint on v1.

**What you expected to happen**:
Create an Endpoint

**How to reproduce it (as minimally and precisely as possible)**:
See YAML below

```
apiVersion: v1
kind: Endpoints
metadata:
  name: example-endpoint
subsets:
  - addresses:
    - ip: 10.0.0.10
  - ports:
    - name: http
      port: 80
      protocol: TCP
```
Result:
```
Endpoints "example-endpoint" is invalid: subsets[1]: Required value: must specify `addresses` or `notReadyAddresses`
```
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Bare Metal
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux 3.10.0-693.11.6.el7.x86_64
```
- Install tools:
kubeadm
flannel

My apologies if this has already been reported. My quick search on the issue did not have any results.

**Comment by BrianBlandKY** [comment]
Please ignore. I'm an idiot. 

Solution:
```
apiVersion: v1
kind: Endpoints
metadata:
  name: example-endpoint
subsets:
  - addresses:
    - ip: 10.0.0.10
    ports:
    - name: http
      port: 80
      protocol: TCP
```
