### ISSUE TITLE
Pods that run as restartPolicy=Always can't set activeDeadlineSeconds

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#58370]
I've noticed that for many simple logical loop behaviors having a pod that runs to completion, exits, and is restarted (after some sleep interval) is a pretty normal sanity check / reconciliation loop.  I.e.:

```
kind: Pod
spec:
  restartPolicy: Always
  containers:
  - name: do-something
     image: centos:7
     command:
     - /bin/bash
     - -c
     - |
       #!/bin/bash
       # run some stuff, exit if failure
       sleep 60
       # exit with success
```

This works pretty well for things like config appliers, host checks, sanity checking, etc.  

I kind of expected to be able to use `activeDeadlineSeconds` with a restartPolicy=Always flag.  Derek remembers us having this originally and maybe changing it later.  We've discussed in sig-auth being able to use this to upper bound how long a pod can run with a specific set of credentials (to prevent containers from running for unbounded duration, or to actually use the activeDeadlineSeconds as the service account token expiration).

I don't think we have a really concrete reason not to allow activeDeadlineSeconds.  Right now fails with 

```
The StatefulSet "application-liveness" is invalid: spec.spec.activeDeadlineSeconds: Invalid value: 300: must not be specified
```

(which also has a bug in doubling up spec - should be `spec.template.spec.activeDeadlineSeconds`)

1.9 @derekwaynecarr @kubernetes/sig-apps-feature-requests  @kubernetes/sig-node-feature-requests
