### ISSUE TITLE
nginx-ingress redirect not working

### ISSUE THREAD

**Issue by kc004** [kubernetes/kubernetes#58382]
**Is this a BUG REPORT or FEATURE REQUEST?**:
kind bug
> /kind feature

**Cloud provider or hardware configuration:** bare metal
**OS (e.g. from /etc/os-release):** Ubuntu 16.04.3 LTS xenial
**Kernel (e.g. uname -a):** Linux 4.4.0-83-generic

**What happened:** Nginx-ingress not forwarding the request to my application. so. I reach my application through Nginx port forwarding and Socket. but this solution is not feasible to use in production. I am using below example to test ingress.
 @kubernetes/sig-onprem
/sig onprem
/sig network
/sig node
```
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: echoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - name: http
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: echoserver
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: echoserver
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: root-ingress
  annotations:
    "ingress.kubernetes.io/rewrite-target": "/"
spec:
  rules:
  - host: "example.com"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: echoserver
          servicePort: http
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: path-ingress
spec:
  rules:
  - host: "example.com"
    http:
      paths:
      - path: "/path"
        backend:
          serviceName: echoserver
          servicePort: http
```

**What you expected to happen:**
Nginx-ingress LB should redirect to my application.

Kubernetes Version: 1.9.1
