### ISSUE TITLE
Azure Internal Load Balancer Only works with one agent pool

### ISSUE THREAD

**Issue by xtophs** [kubernetes/kubernetes#58410]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT 

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
curl'ed internal load balancer front ending an nginx deployment.

curl: (7) Failed to connect to 10.240.0.220 port 80: Connection timed out

**What you expected to happen**:
See the nginx index page

**How to reproduce it (as minimally and precisely as possible)**:
* provision a kubernetes cluster with 2 agent pools in Azure using apimodel.json files in examples/networkpolicy
* deploy nginx pods into agentpool2 using the attached nginx.yaml
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
      nodeSelector:
        agentpool: agentpool2
```

* deploy an internal loadbalancer using the svc.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-load-balancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    run: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
```

* wait for the internal load balancer to come up, i.e. it has an external-IP address
* curl the external-IP address

**Anything else we need to know?**:
**pods are running on nodes in agentpool2:**

$ kubectl get pods -o wide
2018-01-17 19:08:13.057282 I | proto: duplicate proto type registered: google.protobuf.Any
2018-01-17 19:08:13.057341 I | proto: duplicate proto type registered: google.protobuf.Duration
2018-01-17 19:08:13.057365 I | proto: duplicate proto type registered: google.protobuf.Timestamp
NAME                                READY     STATUS    RESTARTS   AGE       IP             NODE
nginx-deployment-2949220902-0tcm5   1/1       Running   0          2h        10.240.0.44    k8s-agentpool2-26116965-1
nginx-deployment-2949220902-cskbv   1/1       Running   0          2h        10.240.0.127   k8s-agentpool2-26116965-2
nginx-deployment-2949220902-jlb6s   1/1       Running   0          2h        10.240.0.17    k8s-agentpool2-26116965-0

**nginx is running**
$ curl 10.240.0.44
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>

** Load Balancer's Backendpool only shows agentpool1 nodes, not agentpool2**
$ az network lb address-pool list -g xtoph-delete-k8sazurenet --lb-name xtoph-netazure-internal --query [].backendIpConfigurations[].id
[
  "/subscriptions/3fee811e-11bf-4b5c-9c62-a2f28b517724/resourceGroups/xtoph-delete-k8sazurenet/providers/Microsoft.Network/networkInterfaces/k8s-agentpool1-26116965-nic-0/ipConfigurations/ipconfig1",
  "/subscriptions/3fee811e-11bf-4b5c-9c62-a2f28b517724/resourceGroups/xtoph-delete-k8sazurenet/providers/Microsoft.Network/networkInterfaces/k8s-agentpool1-26116965-nic-2/ipConfigurations/ipconfig1",
  "/subscriptions/3fee811e-11bf-4b5c-9c62-a2f28b517724/resourceGroups/xtoph-delete-k8sazurenet/providers/Microsoft.Network/networkInterfaces/k8s-agentpool1-26116965-nic-1/ipConfigurations/ipconfig1"
]

**Environment**:
- Kubernetes version (use `kubectl version`):
1.7.9

- Cloud provider or hardware configuration:
Azure

- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"

- Kernel (e.g. `uname -a`):
Linux 4.11.0-1016-azure #16-Ubuntu SMP Tue Dec 5 22:52:08 UTC 2017

- Install tools:
acs-engine

- Others:
