### ISSUE TITLE
Enable selector in pvc for Azure

### ISSUE THREAD

**Issue by ritazh** [kubernetes/kubernetes#58413]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
Getting this warning when using `selector` for creating new pvc: 

`claim.Spec.Selector is not supported for dynamic provisioning on Azure disk`

As a result, when pv with label is not found, it does not create new pv.

code is here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_dd/azure_provision.go#L74

**What you expected to happen**:
Be able to create a new pvc using an existing pv with label selector if pv exists, if not, create new pv.

**How to reproduce it (as minimally and precisely as possible)**:
Using ACS
kubectl v1.7.3
kubernetes v1.7.9

```bash
kubectl create -f pvc.yaml
```

pvc.yaml

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    provisioner: kubernetes.io/azure-disk
    storageclass.beta.kubernetes.io/is-default-class: 'true'
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  name: testclaim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: managed-premium
  selector:
    matchLabels:
      release: "staging"
```
cc @khenidak @noelbundick @sauryadas
