### ISSUE TITLE
We have no way to simultaneously enable ImagePolicyWebhook and MutatingAdmissionWebhook admission plugins

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#58426]
/kind bug

**What happened**:

When I want to enable both plugins by passing below flag, as they both need config file, and I find I donot know what to set `--admission-control-config-file`
```
--admission-control=ImagePolicyWebhook,MutatingAdmissionWebhook
```

If I set  `--admission-control-config-file=admission-config.json`, then I get an error in apiserver
`Error: failed to initialize admission: failed to read plugin config: couldn't get version/kind; json parse error: invalid character '/' looking for beginning of object key string`
```bash
root@SZX1000353068:/mnt/go/src/k8s.io/kubernetes# cat admission-config.json
{
  "imagePolicy": {
     "kubeConfigFile": "path/to/kubeconfig/for/backend",
     "allowTTL": 50,
     "denyTTL": 50, 
     "retryBackoff": 500, 
     "defaultAllow": true
  }
}
```

**Comment by liggitt** [comment]
first, you can't put comments in json. the error was complaining about your embedded comments. this would let the server start:

imagepolicy.json:
```json
{
  "imagePolicy": {
     "kubeConfigFile": "/path/to/file",
     "allowTTL": 50,
     "denyTTL": 50, 
     "retryBackoff": 500,
     "defaultAllow": true
  }
}
```

second, the docs are really, really, not right (opened https://github.com/kubernetes/website/pull/7007/files with fixes).

if you want to specify config for multiple plugins, `--admission-control-config-file` should point to a config that references individual config files for each plugin (which there's a bug in loading... fixed in https://github.com/kubernetes/kubernetes/pull/58439):

```yaml
kind: AdmissionConfiguration
apiVersion: apiserver.k8s.io/v1alpha1
plugins:
- name: ImagePolicyWebhook
  path: /path/to/imagepolicy.json
- name: MutatingAdmissionWebhook
  path: /path/to/webhookconfig.yaml
...
```

example webhookconfig.yaml:
```yaml
kind: WebhookAdmission
apiVersion: apiserver.config.k8s.io/v1alpha1
kubeConfigFile: /path/to/webhook.kubeconfig
```
