### ISSUE TITLE
No service access when exposing externally

### ISSUE THREAD

**Issue by felixPG** [kubernetes/kubernetes#58450]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
I have a kubernetes cluster **1.8.5+debian stretch + docker 1.13 (overlay2)**
I have problems exposing a service as part of a deployment of a private docker registry.
If I create the container using docker, the service work like a charm:
```
docker run --rm -p 5000:5000 myrepo/privateregistry 

Logs from the container: curl 192.168.133.17:5000/v2

time="2018-01-18T10:59:43Z" level=info msg="response completed" go.version=go1.7.6 http.request.host="192.168.133.17:5000" http.request.id=e2efdf78-1c5c-46ee-8a59-0bfacd841e2e http.request.method=GET http.request.remoteaddr="192.168.133.18:39472" http.request.uri="/v2" http.request.useragent="curl/7.52.1" http.response.duration="117.851µs" http.response.status=301 http.response.written=39 instance.id=5efe3b3b-4aae-4a00-9861-ca6507e40231 version=v2.6.2
192.168.133.18 - - [18/Jan/2018:10:59:43 +0000] "GET /v2 HTTP/1.1" 301 39 "" "curl/7.52.1"
```
When I try to create the deployment exposing the service as external IP in the same IP  (192.168.133.17) the service ONLY work if I make the request from the same machine (192.168.133.17) that the service are exposed and NOT if I make a request from other machine p.e: 192.168.133.18

```
NAME            TYPE        CLUSTER-IP     EXTERNAL-IP      PORT(S)         AGE
kube-dns        ClusterIP   10.96.0.10     <none>           53/UDP,53/TCP   17h
kube-registry   ClusterIP   10.111.50.53   192.168.133.17   5000/TCP        11s
```
I have another cluster with **debian jessie+docker 1.13 (aufs) +kubernetes 1.8.5** where the same deployment work like a charm as a kubernetes deployment. Is the same definition of the deployment and services.

The service WORK in "production" cluster **debian jessie (kernel 3.16)+docker 1.13(aufs)+kubernetes 1.8.5**, but  DOES NOT WORK in a test cluster **debian stretch (kernel 4.9)+docker 1.13(overlay2)+kubernetes 1.8.5**, but If I launch only the container with docker command the service work like a charm here.

In both cluster are the same configuration: weave as network plugin, kubernetes 1.8.5, the unique difference is that one cluster has **debian jessie (kernel 3.16) + docker 1.13 AUFS**, and the other has **debian stretch (kernel 4.9) + docker 1.13 OVERLAY2**

The deployment is as follow:

```
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-system
  annotations:
    prometheus.io/probe: "true"
  labels:
    k8s-app: kube-registry-upstream
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry-upstream
  ports:
  - name: registry
    port: 5000
    protocol: TCP
  externalIPs:
    - 192.168.133.17

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-registry-v0
  namespace: kube-system
  labels:
    k8s-app: kube-registry-upstream
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kube-registry-upstream
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: inecocity/registry
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
        securityContext:
          privileged: true

```

Could anyone help me to resolve this big headache??
**What you expected to happen**:

Service work as expected like in a "production cluster"

**How to reproduce it (as minimally and precisely as possible)**:

Apply the deployment to an environment like "test cluster": debian stretch (kernel 4.9)+docker 1.13(overlay2)+kubernetes 1.8.5
