### ISSUE TITLE
readinessProbe keeps active together with livenessProbe while container is already started

### ISSUE THREAD

**Issue by vdboor** [kubernetes/kubernetes#58452]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Both the `readinessProbe` and `livenessProbe` remained active in the container.

The `readinessProbe` was used to check whether the application was started, and it could connect to all it's backends (postgres, redis, etc..). This check runs every 10 seconds to ensure it helps with a quick startup.

The `livenessProbe` was used to check *only* whether the pod itself was still running (an empty page that returns a simple http 200). This check ran every minute with more relaxed timeouts, because it concerned a low-traffic site. (for test websites I'm even using a timeout of 5 minutes)

On connectivity issues with kube-dns and postgres, all web application pods were found unhealthy, because their strict `readinessProbe` was still running every 10 seconds. Kubernetes thus restarted all pods that run web sites, applications and for the next few minutes the whole cluster returned the "404 - default backend".

**What you expected to happen**:

That the `livenessProbe` keeps running, but the `readinessProbe` stops once the container is ready.

Looking at the docs at https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ it looks like the main purpose of a `readinessProbe` is to see whether an expensive start-up was completed. Once it's ready, it seems like the `readinessProbe` fulfilled it's duty, and the `livenessProbe` can take over.

**How to reproduce it (as minimally and precisely as possible)**:

Define both probes in a deployment. For example:

```yaml
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: localhost
            path: /api/check-all/  # connects to backends
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: localhost
            path: /api/ping/  # just returns http 200
            port: 8080
            scheme: HTTP
          periodSeconds: 300
          timeoutSeconds: 60
```

**Environment**:

Everything was upgraded to the current version: Using kubectl v1.9.1, kubernetes v1.9.1 on a private VPS cluster (followed the kubeadm "bare metal" setup). Debian 9 (Stretch), kernel 4.14.0-0.bpo.3-amd64.
