### ISSUE TITLE
Cannot create ILB when a Global HTTP LB Exists

### ISSUE THREAD

**Issue by fastest963** [kubernetes/kubernetes#58500]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
After creating a GCE Global LB (using ingress-gce), `k8s-ig--NAME` instance groups were made for all zones. This now prevents us from having network or internal load balancers because when `type: LoadBalancer` is specified for a service, a `v1.compute.regionBackendServices.insert` call is made with the `k8s-ig--NAME` but without specifying a BalancingMode (as seen here https://godoc.org/google.golang.org/api/compute/v1#Backend) and the default is "UTILIZATION". An error is returned when creating the backend service:
```
Invalid argument (HTTP 400): Validation failed for instance 'link-to-instance': instance may belong to at most one load-balanced instance group.
```

**What you expected to happen**:
I expected the network/internal load balancer to be created.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create an L7 load balancer with https://github.com/kubernetes/ingress-gce
2) Create an L4 load balancer by making a service with `type: LoadBalancer`. It can be internal or not.

**Anything else we need to know?**:
When you use the Console GUI to create an internal LB using the same `k8s-ig--NAME` instance groups it uses a BalancingMode of "CONNECTION" and the load balancer is created successfully. This is the "solution" to the problem specified: https://github.com/kubernetes/ingress-nginx/issues/112

I'm not sure if "UTILIZATION" as the default even makes sense in a container environment since kube-proxy is migrating away all the connections anyways to an instance that isn't necessarily the instance the gclb thinks it's going to.

It looks like all we have to change is adding the `BalancingMode` to `backendsFromGroupLinks` inside `pkg/cloudprovider/providers/gce/gce_loadbalancer_internal.go` but I thought I'd file a bug first before making a PR. We'd have to know inside of that whether it was internal or not so we knew which mode to use.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.5-gke.0 on the server and 1.8.5 on the client
- Cloud provider or hardware configuration: GKE with 3 regional clusters

**Comment by nicksardo** [comment]
Hi @fastest963 

The BalancingMode isn't defined in the ILB code because the default is 'CONNECTION' when the backend service is INTERNAL (see further down that comment in godoc). Usually when that kind of error occurs, it'll say something about being "mixed mode".  The error message you posted occurs when an instance exists in multiple instance groups and a user tries to point multiple LBs to the different groups. Can you attempt reproduction on a new cluster in the same project? If that still is problematic, could you try a different project?

I just spun up a 1.8.5 cluster on GKE and created an ingress followed by an ILB, but I couldn't reproduce an error.  The ingress' backendService was correctly mode=RATE and the ILB backendService was correctly CONNECTION (as queried via gcloud).

/assign
/cc @bowei

**Comment by fastest963** [comment]
@nicksardo Thanks for the quick reply! I've investigated a bit more after your comment and I might've misdiagnosed the problem. It appears the second LB was created with a different set of instance groups. The Global HTTP LB was created with `k8s-ig--072821c5fb804c3d` and when I try to make the ILB it made a new instance group  `k8s-ig--645888a836618cf3`. So it looks like the instance group name is incorrect when the ILB is made or the ingress made the wrong instance groups?

Here's where I guess the ingress gets the name?
```
kubectl --context=europe-west1-1 --namespace=kube-system get configmaps ingress-uid -o yaml
apiVersion: v1
data:
  provider-uid: 645888a836618cf3
  uid: 072821c5fb804c3d
kind: ConfigMap
metadata:
  creationTimestamp: 2018-01-04T00:51:03Z
  name: ingress-uid
  namespace: kube-system
  resourceVersion: "2405"
  selfLink: /api/v1/namespaces/kube-system/configmaps/ingress-uid
  uid: 56d89d37-f0e9-11e7-b08e-42010a840035
```

Here's the existing backend service:
```
gcloud compute backend-services describe k8s-be-30080--072821c5fb804c3d
affinityCookieTtlSec: 0
backends:
- balancingMode: RATE
  capacityScaler: 1.0
  description: ''
  group: https://www.googleapis.com/compute/v1/projects/-/zones/europe-west1-b/instanceGroups/k8s-ig--072821c5fb804c3d
  maxRatePerInstance: 1.0
- balancingMode: RATE
  capacityScaler: 1.0
  description: ''
  group: https://www.googleapis.com/compute/v1/projects/-/zones/europe-west1-c/instanceGroups/k8s-ig--072821c5fb804c3d
  maxRatePerInstance: 1.0
- balancingMode: RATE
  capacityScaler: 1.0
  description: ''
  group: https://www.googleapis.com/compute/v1/projects/-/zones/europe-west1-d/instanceGroups/k8s-ig--072821c5fb804c3d
  maxRatePerInstance: 1.0
```

But yet when I try and create the ILB here's the error:
![image](https://user-images.githubusercontent.com/112555/35149719-355fc2aa-fce5-11e7-8298-55e4c539f52f.png)

Is there another spot where the ILB creation gets the name that I could change to make the same as the `ingress-uid`?
