### ISSUE TITLE
Improve kubectl cp, so it doesn't require the tar binary in the container

### ISSUE THREAD

**Issue by luksa** [kubernetes/kubernetes#58512]
> Uncomment only one, leave it on its own line: 

> /kind feature

**What happened**:
Kubectl cp currently requires the container we're copying into to include the tar binary. This is problematic when the container image is minimal and only includes the main binary run in the container and nothing else. 

**What you expected to happen**:
Docker now has `docker cp`, which can copy files into a running container without any prerequisites on the container itself. Kubectl cp could use that mechanism. Obviously, this will require introducing a new feature into CRI, so it's not a small task.

**Comment by dims** [comment]
@luksa : did you figure out which Docker API is to be used? 

/sig node

**Comment by luksa** [comment]
Copy from container: `GET /containers/(id or name)/archive`
Copy into container: `PUT /containers/(id or name)/archive`

This is from https://docs.docker.com/engine/api/v1.20/

**Comment by cyphar** [comment]
Ideally we would add a CRI method that allows the kubelet (and thus Kubernetes) to fetch the stream of an archive of a given path inside a container and to extract a stream of an archive to a path inside a container -- so that `cri-o` could support this improved `kubectl cp` just as well.

It should be noted though that (in my experience) the semantics of "what path to output to" (especially for single-file copy operations) are a little bit odd. Docker made a few mistakes historically with this, so I'd prefer to not repeat them in Kubernetes.

**Comment by talolierwork** [comment]
+1

**Comment by yue9944882** [comment]
@kubernetes/sig-node-feature-requests

**Comment by yujuhong** [comment]
@luksa will the WIP "debug container" feature satisfy your use case? https://github.com/kubernetes/features/issues/277

/cc @verb

**Comment by vielmetti** [comment]
As noted in https://www.twistlock.com/labs-blog/disclosing-directory-traversal-vulnerability-kubernetes-copy-cve-2019-1002101/ analysis of CVE-2019-1002101.

**Comment by markzhang0928** [comment]
`kubectl cp` requires the container to be running by encapsulating the exec command depending on the `tar binary`. we can implement this function without it.

Some people are really looking forward to this feature,

https://github.com/kubernetes/kubectl/issues/454
https://github.com/kubeflow/pipelines/issues/1213
Sync does not work in containers without the tar command #1814
Can not copy configuration files to NFS #1

Is there anyone actively working on this? I would really like to start contributing on it .
is this feature on track ?  @kubernetes/sig-cli-feature-requests

cc /@luksa

**Comment by BenTheElder** [comment]
moving to distroless in more places is going to make this more painful FYI @yuwenma

**Comment by markzhang0928** [comment]
> moving to distroless in more places is going to make this more painful FYI @yuwenma

Yes, definitely understood;  `[Bug 1096726](https://bugzilla.suse.com/show_bug.cgi?id=1096726)` makes docker hit the headline again. 

There are two ways to solve this problem. One way is to fix it like [#39292] (https://github.com/moby/moby/pull/39292), pass root to chroot to for chroot Tar/Untar. 
Another way is to implement `kubectl cp` by using a  [`ephemeral container`](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190212-ephemeral-containers.md) to exchange data with target container . While it may have quite a little bit long time to wait.

**Comment by markzhang0928** [comment]
Yes, definitely understood; Bug 1096726
<https://bugzilla.suse.com/show_bug.cgi?id=1096726> makes docker hit the
headline again.

There are two ways to solve this problem.
One way is to fix it like [#39292
<https://github.com/kubernetes/kubernetes/issues/39292>] (moby/moby#39292
<https://github.com/moby/moby/pull/39292>), pass root to chroot to for
chroot Tar/Untar.
Another way is to implement kubectl cp by using a ephemeral container
<https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20190212-ephemeral-containers.md>
to
exchange data with target container . While it may have quite a little bit
time to wait. #227 <https://github.com/kubernetes/enhancements/issues/277>



Benjamin Elder <notifications@github.com> 于2019年6月1日周六 上午4:11写道：

**Comment by denysvitali** [comment]
Since Traefik's container doesn't include the `/bin/tar`command, I solved my problem by using a Pod that runs `alpine:latest` and shares a volume with Traefik's pods.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: traefik-cp-pod
  namespace: kube-system
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["tail", "-f", "/dev/null"]
      volumeMounts: 
      - name: traefik-data-volume
        mountPath: /mnt/data
  volumes:
    - name: traefik-data-volume
      persistentVolumeClaim:
        claimName: traefik-data-claim
---
apiVersion: v1
kind: Pod
metadata:
  name: traefik-cp-pod
  namespace: kube-system
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["tail", "-f", "/dev/null"]
      volumeMounts: 
      - name: traefik-data-volume
        mountPath: /mnt/data
  volumes:
    - name: traefik-data-volume
      persistentVolumeClaim:
        claimName: traefik-data-claim
```

Then I use `kubectl --namespace=kube-system cp data.toml traefik-cp-pod:/mnt/data/` to copy file to / from Traefik's volume.
  
Obviously by fixing this issue I'll be able to remove Alpine's overhead.
