### ISSUE TITLE
expose and reconcile etcd service and endpoints objects

### ISSUE THREAD

**Issue by brancz** [kubernetes/kubernetes#58614]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

### Description

The Kubernetes API allows discovering almost everything that runs in your Kubernetes cluster, as well as the underlying Kubernetes components themselves. One of the few exceptions today is the etcd cluster(s) used. This is unfortunate, as for example in order to monitor every target from cluster components to workload running on Kubernetes can be treated the same, except for etcd.

I propose to add a Service and Endpoints object similar to the `kubernetes` Service in the `default` namespace. I imagine these object to be in the `kube-system` namespace called `etcd`. This may get slightly more complicated with the `--etcd-servers-overrides` flag, but my suggestion would be to use the path sanitized to fit a Kubernetes object name as a suffix for separate/multiple clusters. The objects would be updated based on their TTL of the DNS entries if the etcd servers are specified as DNS names. If they are IPs then these objects are just updated and reconciled in a static interval.

An open question I have is whether we should try to discover the etcd members through etcd itself as well or just assume an operator has provided the apiserver flag with all expected members?

If you believe this requires a full design doc I'm more than happy to write one up, otherwise just implement it.

Thoughts?

/cc @kubernetes/sig-instrumentation-feature-requests

**Comment by liggitt** [comment]
Nothing except the API servers should be talking to etcd. Exposing the apiserver storage to other cluster members is a non-goal.

See https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#securing-etcd-clusters:

> Access to etcd is equivalent to root permission in the cluster so ideally only the API server should have access to it.

**Comment by brancz** [comment]
I generally agree with the security argument, only that would mean we're not monitoring etcd at all, which is also unreasonable. I believe one needs to take special caution in order to monitor etcd. For example segregate the network access. Only let monitoring nodes have network access to the etcd nodes metrics port (https://github.com/coreos/etcd/issues/8060) and validate via mTLS and enable etcd authZ (https://coreos.com/etcd/docs/latest/op-guide/authentication.html).

I had a quick discussion with @sttts, I understand that this may not be something everyone is interested in, furthermore it may be tempting for developers of aggregated APIs to use the same etcd cluster, which of course is not what we want.

**Comment by lavalamp** [comment]
1) Eventually, we should be running etcd in the cluster like we run anything else, and then it should be available for monitoring, etc.

2) etcd is meant only for apiserver. No one else in the cluster should be able to talk to it. Ideally the monitoring port is separate so we wouldn't even have to trust the monitoring system.

3) I'm adamantly against trying to do something special to publish etcd endpoints. The control plane is a system of micro-services; our users run systems of micro-services on Kubernetes. We should not build two copies of something, which invariably ends up looking like a nice one for our users and a crappy one for us. This is a need that we solve for users. Any effort we want to spend on solving it for us should go into making us run things like we tell our users to run things rather than building something special-purpose.

**Comment by astub** [comment]
@brancz Whats the best way to monitor the etcd endpoints if they are not defined? Are your hard coding into the prometheus scrape config?

**Comment by mindw** [comment]
@brancz @astub , We are monitoring ETCD using the k8s proxy (this needs some TLSing though):
```
      - job_name: kube-etcd
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
          - role: node

        relabel_configs:
          - source_labels: [__meta_kubernetes_node_label_NodeType]
            action: keep
            regex: master
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}:2379/proxy/metrics
```

**Comment by mindw** [comment]
We are successfully monitoring ETCD via the k8s proxy:
```
      - job_name: kube-etcd
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

        kubernetes_sd_configs:
          - role: node

        relabel_configs:
          - source_labels: [__meta_kubernetes_node_label_NodeType]
            action: keep
            regex: master
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}:2379/proxy/metrics
```
Prometheus RBAC:
```
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
```
