### ISSUE TITLE
Kubectl applying yaml with tolerations not working

### ISSUE THREAD

**Issue by CodeJjang** [kubernetes/kubernetes#58703]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature
/sig api-machinery

**What happened**:
I'm trying to apply a yaml file of a `Deployment`, which contains pod tolerations in its Pod Spec section.  
Everything works fine, Deployment, ReplicaSet and Pods are created according the yaml, `Kubectl` doesn't return any error, but the tolerations are just not being added.  
I tried apply to an existing / new Deployment, but neither work.  
The yaml is in the following form (replaced the irrelevant values):
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: some_name
  namespace: my_ns
  labels:
    app: my_app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my_app
    spec:
      nodeSelector:
        key: value
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "my_user"
        effect: "NoSchedule"
      - key: "some_key"
        operator: "Equal"
        value: "some_value"
        effect: "NoSchedule"
      containers:
      - image: my_image
        name: some_name
        ...etc
```
I noticed however that posting the tolerations manually via Kubernetes UI in the edit section inside the Deployment does work, the tolerations are added to the Deploymeny, and the Pods are scheduled to the matching tainted node.  
Also, editing the yaml using `kubectl edit deployments <deployment_name>` and adding the tolerations there ALSO works, or even using `kubectl create`.  

**What you expected to happen**:
I expect that applying the above yaml with `kubectl` would apply the new tolerations to the created / existing Pods.

**How to reproduce it (as minimally and precisely as possible)**:
Create a tainted node, even with 1 taint, then try to `kubectl apply` some yaml in the above form, with new tolerations in its Pod Spec section.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client - v1.5.4, Server - v1.8.5 (-rancher1)
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-28-generic
- Install tools: n/a
- Others:
