### ISSUE TITLE
CronJob with Forbid policy keeps creating Jobs

### ISSUE THREAD

**Issue by adam-sandor** [kubernetes/kubernetes#58748]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Created a CronJob with the `Forbid` concurrency policy. The Pod it was trying to run failed to pull its image. The CronJob kept creating new Jobs on every run but they could never execute so just kept piling up. The result is I had to manually delete all jobs as deleting the Pod and the CronJob didn't help in resolving the issue.

**What you expected to happen**:
Whenever the CronJob decides to skip a run because a previous run is still active it should not create a Job even if the previous run is stuck on an error like pulling the image.

**How to reproduce it (as minimally and precisely as possible)**:
Create this CronJob:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: testjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: testjob
              image: busybox:unexistingtag
          restartPolicy: Never
```

After it tries to start the first Pod which hangs on image pull error, update the CronJob with a definition that it pointing to an existing container:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: testjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: testjob
              image: busybox
          restartPolicy: Never
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): GKE cos
- Kernel (e.g. `uname -a`): GKE cos
