### ISSUE TITLE
azure  load balancer created with wrong backend port

### ISSUE THREAD

**Issue by r7vme** [kubernetes/kubernetes#58759]
/kind bug

**What happened**:
azure load balancer created with wrong backend port.

I'm creating load balancer from:
```
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
```

My nginx pods
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-worker1
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

Finally in Azure portal i see that everything is fine except "backend port", which is set to 80.

**What you expected to happen**:
Load balancer will have "backend port" set to node port, which in my case was selected to `32451`.

**How to reproduce it (as minimally and precisely as possible)**:
1) deploy kubernetes 1.9.0 on Azure
2) create resources above (service and deployment)
3) check load balancer settings in azure portal

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.0
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): coreos 1465.7.0
- Kernel (e.g. `uname -a`): 4.12.10-coreos
- Install tools: https://github.com/giantswarm/azure-operator
- Others:
