### ISSUE TITLE
How to get the DNS name of a service in google cloud platform?

### ISSUE THREAD

**Issue by mappedinn** [kubernetes/kubernetes#58792]
Hi,

In this repository [https://github.com/mappedinn/kubernetes-nfs-volume-on-gke](https://github.com/mappedinn/kubernetes-nfs-volume-on-gke) I am trying to share a volume through NFS service on GKE. The NFS file sharing is successful if hard coded IP address is used. 

But, in my point of view, it would be better to use DNS name in stead of hard coded IP address.

Below is the declaration of the NFS service being used for sharing a volume in Google Cloud Platform:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
```

Below is the definition of the PersistentVolume with hard coded IP address:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp01-pv-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.247.248.43 # with hard coded IP, it works
    path: "/"
```

Below is the definition of the PersistentVolume with DNS name:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp01-pv-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server:  nfs-service.default.svc.cluster.local # with DNS, it does not works
    path: "/"
```

I am using this [https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) for getting the DNS of the service. Is there any thing missed?

Thanks

**Comment by mappedinn** [comment]
@kubernetes/sig-network-bug @kubernetes/sig-gcp-bug

**Comment by munnerz** [comment]
I think this is because the kubernetes nodes in GKE are not configured to use kube-dns to resolve DNS queries (only the containers created on that node are).

There's not really a clean way around this, so I'd say your best bet is to set a static clusterIP in your nfs-server service:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  clusterIP: 10.247.248.43
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
```

and then set up a DNS A record to resolve to `10.247.248.43` and use that.

**Comment by mappedinn** [comment]
Thank @munnerz for your answer.

I tried many IP addresses, but I am always getting the same error message: **The Service "nfs-server" is invalid: spec.clusterIP: Invalid value: "10.247.248.43": provided IP is not in the valid range**

Any advice? Or any link for a documentation...

**Comment by mappedinn** [comment]
With a cluster of version `v1.8.6-gke.0`, the error message became better and I got finally a correct IP address for the service.

For that IP address, I tried to use a DNS A record as follows:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  clusterIP: 10.3.240.20
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
#  type: "LoadBalancer"
```

and for the PersistentVolume, it is defined as follows:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXED: Use internal DNS name
    server: 10-3-240-20.default.svc.cluster.local
    path: "/"
```

And actually, the error I am getting is:

**MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 1 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/b238c31e-029c-11e8-b23e-42010a8e0fc4/volumes/kubernetes.io~nfs/nfs --scope -- /home/kubernetes/containerized_mounter/mounter mount -t nfs 10-3-240-20.default.svc.cluster.local:/ /var/lib/kubelet/pods/b238c31e-029c-11e8-b23e-42010a8e0fc4/volumes/kubernetes.io~nfs/nfs Output: Running scope as unit: run-re4c0f06ddadb4a25a98d90c618f9e5f0.scope Mount failed: Mount failed: exit status 32 Mounting command: chroot Mounting arguments: [/home/kubernetes/containerized_mounter/rootfs mount -t nfs 10-3-240-20.default.svc.cluster.local:/ /var/lib/kubelet/pods/b238c31e-029c-11e8-b23e-42010a8e0fc4/volumes/kubernetes.io~nfs/nfs] Output: mount.nfs: Failed to resolve server 10-3-240-20.default.svc.cluster.local: Name or service not known**

Something missed?

**Comment by munnerz** [comment]
So you've done the first half of what I suggested (setting a static IP on the service), however you've missed the second half:

```
I think this is because the kubernetes nodes in GKE are not configured to use kube-dns to resolve DNS queries (only the containers created on that node are).

and then set up a DNS A record to resolve to 10.247.248.43 and use that.
```

Because it is the *node* that mounts the NFS volume, and because the *node* is not configured to use kube-dns to resolve hostnames, it is unable to resolve `.cluster.local` addresses. You need to configure a DNS entry in an *upstream* (or public) DNS zone to resolve to your *private* IP address (in this case, `10.3.240.20`). Because the DNS record will then be public, it will be resolvable by the kubernetes nodes/hosts, thus it should work.

**Comment by mappedinn** [comment]
Could you please tell me which version kubectl are you using?

I solved the problem by just upgrading kubectl of my GKE cluster from the version `1.7.11-gke.1` to `1.8.6-gke.0`.

```
kubectl version
# Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
# Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.6-gke.0", GitCommit:"ee9a97661f14ee0b1ca31d6edd30480c89347c79", GitTreeState:"clean", BuildDate:"2018-01-05T03:36:42Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Actually, this the final version of yaml files:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  # clusterIP: 10.3.240.20
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
#  type: "LoadBalancer"
```

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXED: Use internal DNS name
    server: nfs-server.default.svc.cluster.local 
    path: "/"
```
Anyway, I still interested on how to configure that DNS entry in an upstream DNS zone to get my private IP resolved. So can you please give me more details?

Thanks...
