### ISSUE TITLE
Unable to Dynamic Provision PVC with XFS

### ISSUE THREAD

**Issue by tatchiuleung** [kubernetes/kubernetes#58826]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Unable to dynamic provision PVC with XFS

**What you expected to happen**:
Successfully attach/mount/allocate PVC with XFS fsType

**How to reproduce it (as minimally and precisely as possible)**:
1. Create storage class
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: slow
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-east-1a, us-east-1c, us-east-1e
  fsType: xfs
```
2. Create PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 100Gi
```
3. Create Deployment
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: jenkinsci/blueocean:1.4.0
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        - name: JENKINS_OPTS
          valueFrom:
            secretKeyRef:
              name: jenkins
              key: options
        - name: JAVA_OPTS
          value: '-Xmx1400m'
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
```
4. Deployment created successfully, but kubelet log shows:
```
I0125 19:54:58.813608    1059 mount_linux.go:469] Disk "/dev/xvdbz" appears to be unformatted, attempting to format as type: "xfs" with options: [/dev/xvdbz]
E0125 19:54:58.813748    1059 mount_linux.go:476] format of disk "/dev/xvdbz" failed: type:("xfs") target:("/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/us-east-1a/vol-0eb2d0c5a75b8e7ba") options:(["defaults"])error:(executable file not found in $PATH)
```

**Anything else we need to know?**:
Replace "xfs" with "ext4" works
```
I0125 19:59:35.155107    1059 mount_linux.go:469] Disk "/dev/xvdbq" appears to be unformatted, attempting to format as type: "ext4" with options: [-F /dev/xvdbq]
I0125 19:59:36.748593    1059 mount_linux.go:473] Disk successfully formatted (mkfs): ext4 - /dev/xvdbq /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/us-east-1a/vol-0e816fb8e9944e8b5
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-rancher1", GitCommit:"6cb179822b9f77893eac5612c91a0ed7c0941b45", GitTreeState:"clean", BuildDate:"2017-12-11T17:40:37Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS EC2 m4.large, EBS 8GB ext4 at /, EBS 100GB xfs at /var/lib/docker
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux ip-10-2-1-222 4.4.0-1049-aws #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
Rancher 1.6.14
- Others:
