### ISSUE TITLE
Selflink of custom resource objects with Cluster scope is wrong

### ISSUE THREAD

**Issue by pekura** [kubernetes/kubernetes#58875]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

I created a custom resource definition with -this is important - scope "Cluster". Then I created an element of that kind. Then I fetched the element and saw that the "metadata.selfLink" attribute had an incorrect value. The path did not contain the custom resource name. Trying to fetch the element using API results in 404 response.

**What you expected to happen**:
The "metadata.selfLink" of an instance of a custom resource should be correct.

**How to reproduce it (as minimally and precisely as possible)**:

Prepare a custom resource definition with scope: Cluster (important! with scope Namespaced the selfLink is correct) in a file resourcedefinition.yaml:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: crontabs.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: crontabs
    # singular name to be used as an alias on the CLI and for display
    singular: crontab
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CronTab
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ct
```
(slightly modified standard example from here: https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/)

Create it:

```kubectl create -f resourcedefinition.yaml```

Now prepare a custom object in a file my-crontab.yaml with this content:

```yaml
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
```

And create it:

```kubectl create -f my-crontab.yaml```

Now get the custom object list:

```kubectl get ct -o yaml```

The result is:

```yaml
apiVersion: v1
items:
- apiVersion: stable.example.com/v1
  kind: CronTab
  metadata:
    clusterName: ""
    creationTimestamp: 2018-01-26T13:26:21Z
    name: my-new-cron-object
    namespace: ""
    resourceVersion: "575"
    selfLink: /apis/stable.example.com/v1/my-new-cron-object
    uid: 7f84cda9-029c-11e8-8032-0800275515f6
  spec:
    cronSpec: '* * * *'
    image: my-awesome-cron-image
    replicas: 15
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

As you can see the selfLink is `apis/stable.example.com/v1/my-new-cron-object`. This is wrong, it should be `apis/stable.example.com/v1/crontabs/my-new-cron-object`. Using the selfLink as it is causes 404 when fetching the resource via API. 

**Anything else we need to know?**:

This only happens when the custom resource definition has scope: Cluster.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.2
- Cloud provider or hardware configuration: 2017 Macbook Pro 
- OS (e.g. from /etc/os-release): macOS High Sierra 10.13.3
- Kernel (e.g. `uname -a`):  Darwin Kernel Version 17.4.0
- Install tools: minikube 0.24.1
