### ISSUE TITLE
Passing an invalid resource to `apply --force` deletes the target server resource

### ISSUE THREAD

**Issue by ironcladlou** [kubernetes/kubernetes#58984]
It's possible to cause a resource to be deleted during `kubectl apply` when the updated resource being applied is invalid (or results in other server side errors).

### Steps to reproduce
1. Create an [example replication controller](https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/)

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

2. Create a local file containing a patched version of the replication controller to update `spec.template.labels[app]=junk` (to cause a selector mismatch)

```
kubectl get rc/nginx -o yaml > /tmp/nginx.yaml
```

3. Use `apply` to update the replication controller from the local file:

```
kubectl apply --overwrite --force -f /tmp/nginx.yaml
```

### What happens

Output:

```
The ReplicationController "nginx" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"junk"}: `selector` does not match template `labels`
```

And the `nginx` replication controller is deleted.

### Expectations

From the `--force` flag docs:

```
--force=false: Delete and re-create the specified resource, when PATCH encounters conflict and has retried for 5
times.
```

In this case the server side error doesn't seem to be a conflict (in terms of a merge conflict, or a resource version conflict). It's a validation error. Given the resource failed validation, I didn't expect the apply target on the server side to be deleted.

### Research/discussion

The [relevant patch code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply.go#L668) looks suspicious: if `--force=true` and *any non-conflict error is encountered*, it seems the command will delete the target unconditionally and then try to create.

Discussion starter: should `apply` exit with an error (and no-op) if a non-conflict error is encountered during the patch attempt?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10 (`HEAD`)
- OS (e.g. from /etc/os-release): darwin/amd64

/kind bug
@kubernetes/sig-cli-bugs
