### ISSUE TITLE
Custom labels can't be added to PVC using StatefulSet.Spec.VolumeClaimTemplates

### ISSUE THREAD

**Issue by ateleshev** [kubernetes/kubernetes#58987]
Are labels could be merged here?

https://github.com/kubernetes/kubernetes/blob/3a1c9449a956b6026f075fa3134ff92f7d55f812/pkg/controller/statefulset/stateful_set_utils.go#L152

for example:
```
if claim.Labels == nil {
  claim.Labels = make(map[string]string)
}
for k, v := range set.Spec.Selector.MatchLabels  {
  claim.Labels[k] = v
}
```

**Comment by ateleshev** [comment]
@kubernetes/sig-storage-misc

**Comment by msau42** [comment]
cc @janetkuo @kow3ns

**Comment by MoriTanosuke** [comment]
I stumbled upon this issue while making my first steps into k8s, volume claims and a custom controller. I tried to create a `StatefulSet` and wanted to use `volumeClaimTemplates` to create persistent volumes for my instances.

My controller would watch all volume claims for a specific label and then create cronjobs with custom commands on the volumes.

Here's my YAML for the `StatefulSet`

````yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myname
  namespace: mynamespace
spec:
  serviceName: myname
  replicas: 2
  selector:
    matchLabels:
      name: myname
      security-group: backend
      # we have to specify the cleanup label here, but then both volumeClaimTemplates get the keyword
      custom-label: "True"
  volumeClaimTemplates:
    - metadata:
        name: claim1
        #labels:
        #  custom-label: "True"
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: claim2
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 1Gi
  template:
...
````

If I understand this issue, I can not specify my `custom-label` for the first claim, but not for the second because currently the labels from the `StatefulSet.Spec.Selector.MatchLabels` are used exclusively. Is that correct?
