### ISSUE TITLE
Can't delete a deployment containing an Azure Managed Disk volume

### ISSUE THREAD

**Issue by noelbundick** [kubernetes/kubernetes#59000]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**: 

I have a deployment with a volume pointing to a pre-existing Managed Disk. The pod runs and correctly mounts the volume. When I try to delete the deployment, I receive the following validation error:

```
The Deployment "busybox" is invalid:
* spec.template.spec.volumes[0].azureDisk.diskURI: Unsupported value: "/subscriptions/***/resourceGroups/MC_trash1-aks_destination_eastus/providers/Microsoft.Compute/disks/source-trash1-eastus-6c1f4fmgmt-dy-pvc-146baa2e-051c-11e8-a3d6-000d3a191f45": supported values: https://{account-name}.blob.core.windows.net/{container-name}/{disk-name}.vhd
* spec.template.spec.containers[0].volumeMounts[0].name: Not found: "disk1"
```

**What you expected to happen**: 

I expect the deployment to be deleted

**How to reproduce it (as minimally and precisely as possible)**: 

* Create a managed disk
* Apply the following deployment, replacing the diskName and diskURI with your own

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: busybox-with-disks
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox-with-disks
  template:
    metadata:
      labels:
        run: busybox-with-disks
    spec:
      containers:
      - args:
        - sleep 60000
        command:
        - /bin/sh
        - -c
        - --
        image: busybox
        name: noel-busybox
        volumeMounts:
        - mountPath: /data1
          name: disk1
      volumes:
      - name: disk1
        azureDisk:
          diskName: source-trash1-eastus-6c1f4fmgmt-dy-pvc-146baa2e-051c-11e8-a3d6-000d3a191f45
          kind: Managed
          diskURI: /subscriptions/6c1f4f3b-f65f-4667-8f9e-b9c48e09cd6b/resourceGroups/MC_trash1-aks_destination_eastus/providers/Microsoft.Compute/disks/source-trash1-eastus-6c1f4fmgmt-dy-pvc-146baa2e-051c-11e8-a3d6-000d3a191f45
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: azure
