### ISSUE TITLE
conntrack table for UDP to vanished pod not flushed

### ISSUE THREAD

**Issue by thkoch2001** [kubernetes/kubernetes#59033]
/kind bug

**What happened**:
1. A server pod exposes UDP host port.
2. A client sends packets to the server pod thru the host port. This creates a conntrack entry.
3. The server pod's IP changs due to whatever reason, such as pod gets recreated.
4. Due to the nature of UDP and conntrack, new request from the same client to the host port will keep hitting the stale conntrack entry.
5. Client observes traffic black hole.

**What you expected to happen**:
After recreation of the server pod (with the same host port), UDP packets reach the new server pod.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: test-udp-server
  namespace: default
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-udp-server
      name: test-udp-server
    spec:
      hostNetwork: true
      containers:
      - image: SEE_DOCKERFILE
        name: test-udp-server
        ports:
          - name: udp
            containerPort: 8125
            hostPort: 8125
            protocol: UDP
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: REVISION
          value: "R1"
        command:
        - "bash"
        - "-c"
        - |
          set -x
          socat - UDP4-RECVFROM:8125,fork
        livenessProbe:
          exec:
            command:
            - "bash"
            - "-c"
            - |
              echo "Liveness probe: $(date)" | socat - UDP4-DATAGRAM:$(hostname -i):8125
          initialDelaySeconds: 60
          periodSeconds: 60
```

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-udp-client
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: test-udp-client
    spec:
      containers:
      - image: SEE_DOCKERFILE
        name: test-udp-client
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
        - "bash"
        - "-c"
        - |
          set -x
          socat - UDP4-DATAGRAM:$HOST:8125 < <(while true ; do echo "From $(hostname): $(date)"; sleep 1 ; done)
```

```
FROM debian:stretch

RUN apt-get -y update
RUN apt-get -y --no-upgrade install socat tcpdump
```

1. Create the above daemonset and deployment.
2. kubectl attach to the daemon pod on the same node as the client, see output
3. change revision in daemonset, kubectl apply it.
4. kubectl attach again, see no output.

**Environment**: GKE 1.8.x
