### ISSUE TITLE
Clearly document postStart hook behavior

### ISSUE THREAD

**Issue by asarkar** [kubernetes/kubernetes#59161]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
The relationship between `postStart` and readiness/liveness is not defined. The [docs](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) say

> if the hook takes too long to run or hangs, the Container cannot reach a running state.

What does this mean? How exactly does a hung `postStart` prevent a container from reaching a running state, since the ENTRYPOINT and hook fire asynchronously.

> If a PostStart or PreStop hook fails, it kills the Container.

Does timeout count as a failure? How is the timeout set?

**What you expected to happen**:
Document answers to the above questions.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
No

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.6

**Comment by php-coder** [comment]
BTW it's better to submit docs issues to their own repository: https://github.com/kubernetes/website/issues

**Comment by yelled3** [comment]
@asarkar 
> How is the timeout set?

From doing some code reading, I found that when running an exec command (not sure for http command) the timeout is not set at all.

this runs the `postStart` lifecycle hook:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L167-L181

and then calls the following:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/handlers.go#L58-L59

```output, err := hr.commandRunner.RunInContainer(containerID, handler.Exec.Command, 0)```
not that `0` is passed for a the timeout - which means no timeout limit.

I tested it with a long (5m) running script - and seems like there is indeed no timeout.
```yaml
lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  echo 'before' > before.txt;
                  sleep 5m;
                  echo 'after' > after.txt;
```

can someone else confirm this is correct? 
or is there another timeout limit I'm missing here?

Thanks
