### ISSUE TITLE
Dynamic volume provisioning multiple EBS volumes for same pod creates in different AZs

### ISSUE THREAD

**Issue by mightyguava** [kubernetes/kubernetes#59326]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I tried to provision source graph on an AWS multi-az cluster

```
# Create a single-server deployment named sourcegraph using the latest Sourcegraph Server Docker image.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sourcegraph
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sourcegraph
    spec:
      containers:
      - name: sourcegraph
        image: sourcegraph/server:latest
        ports:
        - containerPort: 7080
        volumeMounts:
        - mountPath: /etc/sourcegraph
          name: config
        - mountPath: /var/opt/sourcegraph
          name: data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sourcegraph-config
      - name: data
        persistentVolumeClaim:
          claimName: sourcegraph-data
---
# Create a LoadBalancer service to expose the deployment on port 80.
apiVersion: v1
kind: Service
metadata:
  name: sourcegraph
  labels:
    app: sourcegraph
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 7080
    protocol: TCP
  selector:
    app: sourcegraph
---
# Create a 1GB persistent volume to hold Sourcegraph Server configuration data.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sourcegraph-config
  labels:
    app: sourcegraph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Create a 500GB persistent volume to hold Sourcegraph cloned repositories, code intelligence metadata, and all other persistent metadata.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sourcegraph-data
  labels:
    app: sourcegraph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
```

**What you expected to happen**:

Expected the 2 volumes to be provisioned in the same zone.

**How to reproduce it (as minimally and precisely as possible)**:

They got provisioned in different zones. The pod can't schedule since the 2 disks it needs are in different zones.

```
Name:            pvc-4d445832-09d6-11e8-ad5d-06118a22e07e
Labels:          failure-domain.beta.kubernetes.io/region=us-west-2
                 failure-domain.beta.kubernetes.io/zone=us-west-2c
Annotations:     kubernetes.io/createdby=aws-ebs-dynamic-provisioner
                 pv.kubernetes.io/bound-by-controller=yes
                 pv.kubernetes.io/provisioned-by=kubernetes.io/aws-ebs
StorageClass:    gp2
Status:          Bound
Claim:           default/sourcegraph-config
Reclaim Policy:  Delete
Access Modes:    RWO
Capacity:        1Gi
Message:
Source:
    Type:       AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:   aws://us-west-2c/vol-04c7250c8f37bf2b9
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
Events:         <none>
```

```
Name:            pvc-4d59a4a6-09d6-11e8-ad5d-06118a22e07e
Labels:          failure-domain.beta.kubernetes.io/region=us-west-2
                 failure-domain.beta.kubernetes.io/zone=us-west-2b
Annotations:     kubernetes.io/createdby=aws-ebs-dynamic-provisioner
                 pv.kubernetes.io/bound-by-controller=yes
                 pv.kubernetes.io/provisioned-by=kubernetes.io/aws-ebs
StorageClass:    gp2
Status:          Bound
Claim:           default/sourcegraph-data
Reclaim Policy:  Delete
Access Modes:    RWO
Capacity:        100Gi
Message:
Source:
    Type:       AWSElasticBlockStore (a Persistent Disk resource in AWS)
    VolumeID:   aws://us-west-2b/vol-03cb0503b9e5306a4
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
Events:         <none>
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
