### ISSUE TITLE
How to use RBAC to binding the spec user?

### ISSUE THREAD

**Issue by jianglingxia** [kubernetes/kubernetes#59397]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
I add --authorization-mode=RBAC to apiserver and restart kube-apiserver then create a role and rolebinding following

[root@controller:/home/ubuntu/RBAC]$ cat role.yaml
```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: rbac
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
```

[root@controller:/home/ubuntu/RBAC]$ cat rolebinding.yaml

```yaml
# This role binding allows "jane" to read pods in the "default" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: rbac
subjects:
- kind: User
  name: jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```

but how can I create many user in k8s cluster? I command with: kubectl get  no type user? maybe I cannot understand the Kind:User thanks
https://v1-8.docs.kubernetes.io/docs/admin/authorization/rbac/
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.8
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
