### ISSUE TITLE
azure-file volume ignores mountOptions (dir_mode, file_mode)

### ISSUE THREAD

**Issue by srudenko** [kubernetes/kubernetes#59435]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**:
I attempted to setup Azure File Volume using azureFile with mountOptions: dir_mode=0777, file_mode=0777.  The volume was successfully mounted, however file_mode and dir_mode contains default values (https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv#mount-options)  file_mode=0755,dir_mode=0755 for v1.9.1

**What you expected to happen**:
It should use the given values dir_mode=0777, file_mode=0777

**How to reproduce it (as minimally and precisely as possible)**:

StorageClass, PersistentVolume, PersistentVolumeClaim as the following

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
```

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: wp-pv
  namespace: wp-backend
spec:
  storageClassName: azurefile
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: wp-azure-secret
    shareName: wordpress
    readOnly: false
  claimRef:
    name: wp-az-files
    namespace: wp-backend
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-az-files
  namespace: wp-backend
  labels:
    app: wordpress
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

All components have been successfully created and available in Kubernetes Dashboard.
The deployment was created using the following yaml:

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  namespace: wp-backend
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.9.2-php5.6-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: wp-mysql-secret
              key: host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wp-mysql-secret
              key: dbname
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wp-mysql-secret
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-mysql-secret
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-az-files
```

The `mount` command confirms that the volume was mounted with file_mode=0755,dir_mode=0755, ignoring settings from the StorageClass

`//xxxxxxx.file.core.windows.net/wordpress on /var/www/html type cifs (rw,relatime,vers=3.0,cache=strict,username=xxxxxx,domain=,uid=0,noforceuid,gid=0,noforcegid,addr=191.239.203.12,file_mode=0755,dir_mode=0755,persistenthandles,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)`

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: Azure AKS
- OS (e.g. from /etc/os-release): PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
- Kernel (e.g. `uname -a`): Linux wordpress-5b486654cf-7b7sg 4.11.0-1016-azure #16-Ubuntu SMP Tue Dec 5 22:52:08 UTC 2017 x86_64 GNU/Linux
- Install tools:
- Others:

@kubernetes/sig-azure-bugs

/sig azure

**Comment by andyzhangx** [comment]
@srudenko I have tried azure file mountOptions on v1.9.1, it works well.
One possible reason why your k8s dose not work is that you are using `azurefile` storage class, while there is a built-in `azurefile` storage class which could not be overwritten by `kubectl` command, that is if you delete old  `azurefile` and create your new one, after about 2min, the new class will be overwritten by old one.

**Comment by andyzhangx** [comment]
and you could use `kubectl get sc azurefile -o yaml` to check whether azurefile class is overwritten.

**Comment by srudenko** [comment]
Thank for getting back.

There is the content of my azurefile yaml:

```

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"azurefile","namespace":""},"mountOptions":["dir_mode=0777","file_mode=0777","uid=1000","gid=1000"],"parameters":{"skuName":"Standard_LRS"},"provisioner":"kubernetes.io/azure-file"}
  creationTimestamp: 2018-02-06T20:06:11Z
  name: azurefile
  resourceVersion: "3354489"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/azurefile
  uid: 2d382e5c-0b79-11e8-9cce-0a58ac1f1484
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=1000
- gid=1000
parameters:
  skuName: Standard_LRS
provisioner: kubernetes.io/azure-file
reclaimPolicy: Delete
```


I have checked on another cluster (v1.8.7) and there is no azurefile StorageClass.

I have renamed the storage class to 
```

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wp-storage
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
```

and updated PersistentVolumeClaim, PersistentVolume as
```
spec:
  storageClassName: wp-storage

```

Still volume has been mounted using `file_mode=0755,dir_mode=0755,persistenthandles` ....

Could you please provide your yaml that mounts with 0777?

When the 'azurefile' storage class was introduced?  My cluster was updated from 1.7.7 > 1.8.7 > 1.9.1 Can this cause a problem?
Should I try to create a new cluster using 1.9.1 version?

**Comment by srudenko** [comment]
I have finally got this solved.

mountOptions must be specified in PersistentVolume and StorageClass (found in your code here: https://github.com/andyzhangx/Demo/blob/master/pv/pv-azurefile-mountoptions.yaml)


The working solution is:

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wp-storage
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS

```
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: wp-pv
  namespace: wp-backend
spec:
  storageClassName: wp-storage
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: wp-azure-secret
    shareName: wordpress
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000    
  claimRef:
    name: wp-az-files
    namespace: wp-backend
```
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-az-files
  namespace: wp-backend
  labels:
    app: wordpress
spec:
  storageClassName: wp-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

I would suggest to update the official documentation: https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv#mount-options
