### ISSUE TITLE
Pods in StagefulSet with initContainers stuck in Terminating status for roughly one minute.

### ISSUE THREAD

**Issue by hoffer2github** [kubernetes/kubernetes#59456]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
When my sts has initContainers in it's pods, i found it alway updates very slow. Pod stucked in Terminating state for about a minute when its init containers are waiting for recycled. I check the kubelet log and find that init containers are always removed by container garbage collector, which runs every minute.

```
[root@k8s-node-2 vagrant]# journalctl --since "2018-02-07 10:04:08" > 132.log
[root@k8s-node-2 vagrant]# grep -E 'SyncLoop|garbage' 132.log
2月 07 10:04:08 k8s-node-2 kubelet[22020]: I0207 10:04:08.801943   22020 kubelet.go:1852] SyncLoop (DELETE, "api"): "test-001-0_default(fbbe124d-0baa-11e8-8e0a-080027dd486f)"
2月 07 10:04:09 k8s-node-2 kubelet[22020]: I0207 10:04:09.150437   22020 kubelet.go:1881] SyncLoop (PLEG): "test-001-0_default(fbbe124d-0baa-11e8-8e0a-080027dd486f)", event: &pleg.PodLifecycleEvent{ID:"fbbe124d-0baa-11e8-8e0a-080027dd486f", Type:"ContainerDied", Data:"218039c51194775d6ff32b2a2c73fc84fa411404155c5e66d64107b318c404d4"}
2月 07 10:04:09 k8s-node-2 kubelet[22020]: I0207 10:04:09.150561   22020 kubelet.go:1881] SyncLoop (PLEG): "test-001-0_default(fbbe124d-0baa-11e8-8e0a-080027dd486f)", event: &pleg.PodLifecycleEvent{ID:"fbbe124d-0baa-11e8-8e0a-080027dd486f", Type:"ContainerDied", Data:"6df0f7c90dd35a7bc400c61511392326c9b33f7135fc3c85d58dd65c8f68aa7f"}
2月 07 10:04:09 k8s-node-2 kubelet[22020]: I0207 10:04:09.164478   22020 kubelet.go:1849] SyncLoop (RECONCILE, "api"): "test-001-0_default(fbbe124d-0baa-11e8-8e0a-080027dd486f)"
2月 07 10:04:09 k8s-node-2 kubelet[22020]: I0207 10:04:09.286548   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:11 k8s-node-2 kubelet[22020]: I0207 10:04:11.287436   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:13 k8s-node-2 kubelet[22020]: I0207 10:04:13.287539   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:15 k8s-node-2 kubelet[22020]: I0207 10:04:15.287774   22020 kubelet.go:1900] SyncLoop (SYNC): 1 pods; kube-dns-6c857864fb-qxmn8_kube-system(728b8ede-f4e1-11e7-950e-080027dd486f)
2月 07 10:04:15 k8s-node-2 kubelet[22020]: I0207 10:04:15.287834   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:17 k8s-node-2 kubelet[22020]: I0207 10:04:17.287087   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:19 k8s-node-2 kubelet[22020]: I0207 10:04:19.287630   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:21 k8s-node-2 kubelet[22020]: I0207 10:04:21.287579   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:23 k8s-node-2 kubelet[22020]: I0207 10:04:23.287300   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:25 k8s-node-2 kubelet[22020]: I0207 10:04:25.286845   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:27 k8s-node-2 kubelet[22020]: I0207 10:04:27.286858   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:29 k8s-node-2 kubelet[22020]: I0207 10:04:29.286809   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:31 k8s-node-2 kubelet[22020]: I0207 10:04:31.286678   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:33 k8s-node-2 kubelet[22020]: I0207 10:04:33.288859   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:35 k8s-node-2 kubelet[22020]: I0207 10:04:35.286929   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:37 k8s-node-2 kubelet[22020]: I0207 10:04:37.287847   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:39 k8s-node-2 kubelet[22020]: I0207 10:04:39.287469   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:41 k8s-node-2 kubelet[22020]: I0207 10:04:41.287472   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:43 k8s-node-2 kubelet[22020]: I0207 10:04:43.287488   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:45 k8s-node-2 kubelet[22020]: I0207 10:04:45.286993   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:47 k8s-node-2 kubelet[22020]: I0207 10:04:47.286942   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:49 k8s-node-2 kubelet[22020]: I0207 10:04:49.287022   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:51 k8s-node-2 kubelet[22020]: I0207 10:04:51.287372   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:52 k8s-node-2 kubelet[22020]: I0207 10:04:52.286866   22020 kubelet.go:1900] SyncLoop (SYNC): 1 pods; domain-544f9fcfb5-5fhlv_operator(92a6a853-0726-11e8-8e0a-080027dd486f)
2月 07 10:04:53 k8s-node-2 kubelet[22020]: I0207 10:04:53.105116   22020 kubelet.go:1285] Image garbage collection succeeded
2月 07 10:04:53 k8s-node-2 kubelet[22020]: I0207 10:04:53.287210   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:53 k8s-node-2 kubelet[22020]: I0207 10:04:53.434724   22020 kubelet.go:1263] Container garbage collection succeeded
2月 07 10:04:55 k8s-node-2 kubelet[22020]: I0207 10:04:55.286945   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:57 k8s-node-2 kubelet[22020]: I0207 10:04:57.286907   22020 kubelet.go:1923] SyncLoop (housekeeping)
2月 07 10:04:57 k8s-node-2 kubelet[22020]: I0207 10:04:57.307852   22020 kubelet.go:1852] SyncLoop (DELETE, "api"): "test-001-0_default(fbbe124d-0baa-11e8-8e0a-080027dd486f)"
2月 07 10:04:57 k8s-node-2 kubelet[22020]: I0207 10:04:57.314251   22020 kubelet.go:1846] SyncLoop (REMOVE, "api"): "test-001-0_default(fbbe124d-0baa-11e8-8e0a-080027dd486f)"
2月 07 10:04:57 k8s-node-2 kubelet[22020]: I0207 10:04:57.335687   22020 kubelet.go:1836] SyncLoop (ADD, "api"): "test-001-0_default(4344becd-0bab-11e8-8e0a-080027dd486f)"
2月 07 10:04:57 k8s-node-2 kubelet[22020]: I0207 10:04:57.359048   22020 kubelet.go:1849] SyncLoop (RECONCILE, "api"): "test-001-0_default(4344becd-0bab-11e8-8e0a-080027dd486f)"
2月 07 10:04:58 k8s-node-2 kubelet[22020]: I0207 10:04:58.448012   22020 kubelet.go:1881] SyncLoop (PLEG): "test-001-0_default(4344becd-0bab-11e8-8e0a-080027dd486f)", event: &pleg.PodLifecycleEvent{ID:"4344becd-0bab-11e8-8e0a-080027dd486f", Type:"ContainerDied", Data:"b06276b9538b203fed9358dd3f1334b4373863c87c52b4c7997f494e8f706c50"}
2月 07 10:04:58 k8s-node-2 kubelet[22020]: I0207 10:04:58.448094   22020 kubelet.go:1881] SyncLoop (PLEG): "test-001-0_default(4344becd-0bab-11e8-8e0a-080027dd486f)", event: &pleg.PodLifecycleEvent{ID:"4344becd-0bab-11e8-8e0a-080027dd486f", Type:"ContainerStarted", Data:"ed5156ae9c19dfaf2e9275953a052879d03dd6ba70df11bb3e72af317e7960a1"}
2月 07 10:04:58 k8s-node-2 kubelet[22020]: I0207 10:04:58.462237   22020 kubelet.go:1849] SyncLoop (RECONCILE, "api"): "test-001-0_default(4344becd-0bab-11e8-8e0a-080027dd486f)"
2月 07 10:04:59 k8s-node-2 kubelet[22020]: I0207 10:04:59.287056   22020 kubelet.go:1923] SyncLoop (housekeeping)
```

**What you expected to happen**:
If the init containers are removed when killing pods, the sts updates may be much faster, as no need to wait for container garbage collector period.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: v1
kind: Service
metadata:
  name: "test-001"
  labels:
    app-relay-seq: "001"
spec:
  ports:
  clusterIP: None
  selector:
    app-relay-seq: "001"
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: "test-001"
spec:
  selector:
    matchLabels:
      app-relay-seq: "001"
  podManagementPolicy: "Parallel"
  serviceName: "test-001"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        app: test-relay
        app-relay-seq: "001"
        version: "1"
    spec:
      terminationGracePeriodSeconds: 1
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: test-relay-runner
        image: nginx
        imagePullPolicy: "IfNotPresent"
        env:
        - name: TEST_VERSION
          value: "135"
      initContainers:
      - name: echo
        image: busybox
        imagePullPolicy: "IfNotPresent"
        command: ["echo", "hello"]
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
[vagrant@k8s-master-1]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):

```
[vagrant@k8s-master-1]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`):
`Linux k8s-master-1 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:
