### ISSUE TITLE
Namespaced CRD cannot used label selector

### ISSUE THREAD

**Issue by rmb938** [kubernetes/kubernetes#59451]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When listing a namespaced CRD with a valid label selector no results are returned

**What you expected to happen**:

Results returned

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a namespaced CRD.
2. Create a resource with that CRD with labels
3. List the resources with a valid label selector

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`

**Test Resources**:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: volumes.sandwichcloud.com
spec:
  group: sandwichcloud.com
  names:
    kind: Volume
    listKind: VolumeList
    plural: volumes
    singular: volume
  scope: Namespaced
  version: v1alpha1
---
apiVersion: sandwichcloud.com/v1alpha1
kind: Volume
metadata:
  finalizers:
  - delete.sandwichcloud.com
  labels:
    sandwichcloud.com/attached_to: null
    sandwichcloud.com/id: 9f52f5b2-559a-475e-95f1-c7b8f0067116
    sandwichcloud.com/name: vol1
    sandwichcloud.com/region: e7444046-fc8b-4c40-81e2-357a5c80168a
    sandwichcloud.com/zone: 88f97cb1-6375-4a13-b9ea-bfd013a33bbd
  name: 9f52f5b2-559a-475e-95f1-c7b8f0067116
spec:
  backingId: 892a404d-60f8-4263-9c5a-5eb45906eb06
  clonedFrom: null
  size: 10
status:
  errorMessage: ""
  state: Created
  task:
    kwargs: {}
    name: null
```

Run `kubectl get volumes -l sandwichcloud.com/name=vol1` and it will return no results.

```
I0206 19:26:04.343321   11513 loader.go:357] Config loaded from file kubeconfig.yml
I0206 19:26:04.365620   11513 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json" -H "User-Agent: kubectl/v1.9.2 (linux/amd64) kubernetes/5fa2db2" http://localhost:8081/apis/sandwichcloud.com/v1alpha1/namespaces/e7a3017c-36fb-466f-97f6-d7079b31e5aa/volumes?labelSelector=sandwichcloud.com%2Fname%3Dvol1&limit=500
I0206 19:26:04.375805   11513 round_trippers.go:436] GET http://localhost:8081/apis/sandwichcloud.com/v1alpha1/namespaces/e7a3017c-36fb-466f-97f6-d7079b31e5aa/volumes?labelSelector=sandwichcloud.com%2Fname%3Dvol1&limit=500 200 OK in 7 milliseconds
I0206 19:26:04.377152   11513 round_trippers.go:442] Response Headers:
I0206 19:26:04.377662   11513 round_trippers.go:445]     Content-Type: application/json
I0206 19:26:04.378014   11513 round_trippers.go:445]     Date: Wed, 07 Feb 2018 01:26:04 GMT
I0206 19:26:04.378400   11513 round_trippers.go:445]     Content-Length: 229
I0206 19:26:04.379130   11513 request.go:873] Response Body: {"apiVersion":"sandwichcloud.com/v1alpha1","items":[],"kind":"VolumeList","metadata":{"continue":"","resourceVersion":"2574","selfLink":"/apis/sandwichcloud.com/v1alpha1/namespaces/e7a3017c-36fb-466f-97f6-d7079b31e5aa/volumes"}}
No resources found.
```

**Comment by chentao1596** [comment]
According to my test, this Volume is not create correctly, i thought this is the real reason.
```
-bash-4.2# kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
```
-bash-4.2# kubectl apply -f crd_test.yaml 
customresourcedefinition "volumes.sandwichcloud.com" created
error: unable to recognize "crd_test.yaml": no matches for sandwichcloud.com/, Kind=Volume
```

**Comment by rmb938** [comment]
It doesn't seem like you waited after creating the CRD before applying the actual resource. CRDs take like 5 seconds to become "active" before the api recognizes them.

**Comment by chentao1596** [comment]
You are right, i try to split them into different files, and the Volume can be created.
I create them in the different version(1.8.5 and 1.9.2), different result show,such as(1.8.5):
```
-bash-4.2# kubectl describe volumes 9f52f5b2-559a-475e-95f1-c7b8f0067116
Name:         9f52f5b2-559a-475e-95f1-c7b8f0067116
Namespace:    default
Labels:       sandwichcloud.com/id=9f52f5b2-559a-475e-95f1-c7b8f0067116
              sandwichcloud.com/name=vol1
              sandwichcloud.com/region=e7444046-fc8b-4c40-81e2-357a5c80168a
              sandwichcloud.com/zone=88f97cb1-6375-4a13-b9ea-bfd013a33bbd
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"sandwichcloud.com/v1alpha1","kind":"Volume","metadata":{"annotations":{},"finalizers":["delete.sandwichcloud.com"],"labels":{"sandwichcl...
API Version:  sandwichcloud.com/v1alpha1
Kind:         Volume
Metadata:
  Cluster Name:                   
  Creation Timestamp:             2018-02-07T02:36:43Z
  Deletion Grace Period Seconds:  <nil>
  Deletion Timestamp:             <nil>
  Finalizers:
    delete.sandwichcloud.com
  Resource Version:  3503045
  Self Link:         /apis/sandwichcloud.com/v1alpha1/namespaces/default/volumes/9f52f5b2-559a-475e-95f1-c7b8f0067116
  UID:               bbd35669-0baf-11e8-97b2-fa163ec3d74f
Spec:
  Backing Id:   892a404d-60f8-4263-9c5a-5eb45906eb06
  Cloned From:  <nil>
  Size:         10
Status:
  Error Message:  
  State:          Created
  Task:
    Kwargs:
    Name:  <nil>
Events:    <none>
```
and(1.9.2)
```
-bash-4.2# kubectl describe volumes 9f52f5b2-559a-475e-95f1-c7b8f0067116
Name:         9f52f5b2-559a-475e-95f1-c7b8f0067116
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"sandwichcloud.com/v1alpha1","kind":"Volume","metadata":{"annotations":{},"finalizers":["delete.sandwichcloud.com"],"labels":{"sandwichcl...
API Version:  sandwichcloud.com/v1alpha1
Kind:         Volume
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-02-07T03:35:14Z
  Finalizers:
    delete.sandwichcloud.com
  Generation:        0
  Resource Version:  545611
  Self Link:         /apis/sandwichcloud.com/v1alpha1/namespaces/default/volumes/9f52f5b2-559a-475e-95f1-c7b8f0067116
  UID:               e87e15ec-0bb7-11e8-a31f-fa163e0f3f99
Spec:
  Backing Id:   892a404d-60f8-4263-9c5a-5eb45906eb06
  Cloned From:  <nil>
  Size:         10
Status:
  Error Message:  
  State:          Created
  Task:
    Kwargs:
    Name:  <nil>
Events:    <none>
```

I thought this is because of the labels not set correctly.
Do you working for it? If not, i will happy to do it.

**Comment by rmb938** [comment]
I currently do not have a PR open to fix this issue and I wouldn't really know where to start. If you know of a fix feel free to do it.

**Comment by chentao1596** [comment]
ok, i try to do it, ^_^!

**Comment by nikhita** [comment]
Labelselectors work fine for custom resources in general. It fails here because of `sandwichcloud.com/attached_to: null` (if you remove this label, everything will work fine).

In 1.9, we introduced:

https://github.com/kubernetes/kubernetes/blob/11104d75f15e43ac41aa5d7226837f8a81523572/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go#L152-L168

This sees that there is a non-string value in the map and gives an error. But we swallow the error here:

https://github.com/kubernetes/kubernetes/blob/11104d75f15e43ac41aa5d7226837f8a81523572/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go#L307-L310

So `List` gets an empty map for `labels` and hence everything fails.

In 1.8, we didn't add the key if it was a non-string value:

https://github.com/kubernetes/kubernetes/blob/2f73858c9e6ede659d6828fe5a1862a48034a0fd/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go#L242-L253

Now, we could probably avoid adding the key if it is a `nil` value.

@sttts @ash2k thoughts?

**Comment by nikhita** [comment]
Btw for native resources, nil values are allowed:

```yaml
$ cat deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    foo: null
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

```sh
$ kubectl create -f deployment.yaml
deployment "nginx-deployment" created

$ kubectl get deployments -l app=nginx
NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment   3         3         3            3           6s
