### ISSUE TITLE
kubectl apply will not add protocols to services that already exist

### ISSUE THREAD

**Issue by BookOfGreg** [kubernetes/kubernetes#59482]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

I have an existing TCP service, when I try to add UDP to it, it will report success but nothing changes.
My `kubectl get services` 

will show `hello-world      ClusterIP      10.0.96.64     <none>          8301/TCP`

**What you expected to happen**:

I expect `kubectl get services`

to show `hello-world      ClusterIP      10.0.113.37    <none>          8301/TCP,8301/UDP`

**How to reproduce it (as minimally and precisely as possible)**:

If I `kubectl apply -f bug-report.yml` as seen below.
```yml
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      io.kompose.service: hello-world
    name: hello-world
  spec:
    ports:
      - name: serflan-tcp
        protocol: "TCP"
        port: 8301
    selector:
      io.kompose.service: hello-world
  status:
    loadBalancer: {}
kind: List
metadata: {}
```
And then modify the file and I `kubectl apply -f bug-report.yml` below.
```yml
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      io.kompose.service: hello-world
    name: hello-world
  spec:
    ports:
      - name: serflan-tcp
        protocol: "TCP"
        port: 8301
      - name: serflan-udp
        protocol: "UDP"
        port: 8301
    selector:
      io.kompose.service: hello-world
  status:
    loadBalancer: {}
kind: List
metadata: {}
```
Then I expect to see UDP and TCP but I only see TCP.

If I If I `kubectl destroy -f bug-report.yml` and then `kubectl apply -f bug-report.yml` then I can see TCP and UDP.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Azure AKS managed K8s, I don't get to choose the K8s version.
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T19:59:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"clean", BuildDate:"2017-09-28T23:56:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g. from /etc/os-release): MacOs 10.12.6
