### ISSUE TITLE
RBAC wrongly denies API requests

### ISSUE THREAD

**Issue by jryberg** [kubernetes/kubernetes#59558]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
**What happened**:
I'm running calico-controllers-node and the docker are not allowed to access the API

> Feb  8 10:08:45 ip-192-168-208-13 kube-apiserver[4455]: I0208 10:08:45.133516    4455 rbac.go:116] RBAC DENY: user "system:serviceaccount:kube-system:default" groups ["system:serviceaccounts" "system:serviceaccounts:kube-system" "system:authenticated"] cannot "list" resource "networkpolicies.extensions" cluster-wide

Log from docker calico-kube-controllers
> E0208 10:50:56.487360       1 reflector.go:205] github.com/projectcalico/kube-controllers/pkg/controllers/networkpolicy/policy_controller.go:147: Failed to list *v1beta1.NetworkPolicy: networkpolicies.extensions is forbidden: User "system:serviceaccount:kube-system:default" cannot list networkpolicies.extensions at the cluster scope

This is the role and rolebinding
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-kube-controllers
rules:
  - apiGroups:
    - ""
    - extensions
    resources:
      - pods
      - namespaces
      - networkpolicies
      - nodes
    verbs:
      - watch
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-kube-controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-kube-controllers
subjects:
- kind: ServiceAccount
  name: calico-kube-controllers
  namespace: kube-system
```

Configured clusterrole
```
host:~$ kubectl describe clusterrole calico-kube-controllers
Name:         calico-kube-controllers
Labels:       <none>
Annotations:  <none>
PolicyRule:
  Resources                   Non-Resource URLs  Resource Names  Verbs
  ---------                   -----------------  --------------  -----
  namespaces                  []                 []              [watch list]
  namespaces.extensions       []                 []              [watch list]
  networkpolicies             []                 []              [watch list]
  networkpolicies.extensions  []                 []              [watch list]
  nodes                       []                 []              [watch list]
  nodes.extensions            []                 []              [watch list]
  pods                        []                 []              [watch list]
  pods.extensions             []                 []              [watch list]
host:~$
```

Configured clusterrolebindings
```
host:~$ kubectl describe clusterrolebindings calico-kube-controllers
Name:         calico-kube-controllers
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  calico-kube-controllers
Subjects:
  Kind            Name                     Namespace
  ----            ----                     ---------
  ServiceAccount  calico-kube-controllers  kube-system
host:~$
```

POD running in correct namespace
```
host:~$ kubectl get pods -n kube-system
NAME                                       READY     STATUS    RESTARTS   AGE
calico-kube-controllers-6bd48cc598-df59l   1/1       Running   0          1h
kube-dns-6c857864fb-tg2h8                  3/3       Running   0          19h
host:~$
```

**What you expected to happen**:

I expect this request to pass RBAC 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS

- OS (e.g. from /etc/os-release):
Ubuntu 16.04.3 LTS

- Kernel (e.g. `uname -a`):
Linux ip-192-168-192-10 4.4.0-1049-aws #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
Manual

- Others:

**Comment by jryberg** [comment]
@kubernetes/sig-auth-bugs

**Comment by jryberg** [comment]
Oh, 

I thought I read everything not only twice but three times.

I just realized that the clusterrole was incorrect

It was:
```
subjects:
- kind: ServiceAccount
  name: calico-kube-controllers
  namespace: kube-system
```

Need to be:
```
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
```
