### ISSUE TITLE
Allow limiting adding/removing finalizers

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#59591]
/kind feature
@kubernetes/sig-auth-feature-requests 
@kubernetes/sig-api-machinery-feature-requests 

**What happened**:

As a namespace-constrained user, I am able to manually add/remove finalizers added by system components:
* garbage collection finalizers
* pv/pvc protection finalizers
* service catalog deprovisioning finalizers
* etc...

**What you expected to happen**:

As a cluster admin, I expected to be able to control what finalizers can be added/removed by end users, so they can be relied on by system components and controllers for gating deletion

**Comment by mikedanese** [comment]
@ihmccreery

**Comment by ihmccreery** [comment]
+1

I've noticed this deficiency as well.  More specifics:

The `finalize` command as it exists today takes a complete namespace object and, as far as I can tell, removes any finalizers from the API object that don't appear in the request object.

This makes fine-grained authorization impossible, which is especially important for namespace-constrained users.  I want to write an authorization rules like: "only service account Y can modify finalizer X (on all namespaces)" (it might also be nice to specify "user Z can modify all finalizers on their namespace _except_ X or W" but that seems like a nice-to-have for which I'm not sure there are many use cases).

Additionally to the multi-tenancy concerns above, bugs are just easy to write and hard to protect against right now.  If I write a namespace controller that accidentally deletes _all_ finalizers, instead of just the one I intend to modify, that's a large blast radius.

My first pass at this would be to define finalizers as first-class subresources on a namespace?

Xref https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/namespaces.md#finalizers.

**Comment by ihmccreery** [comment]
I _think_ we could do this in a backward-compatible way, even, by making the current `finalize` call an alias for the subresource-based, correctly authorized call, where the apiserver computes what finalizers are being deleted and delegates to the subresource endpoint.

**Comment by zhouhaibing089** [comment]
We've been thinking about this, too. Besides finalizers, we also want to take care of annotations and init containers(where those annotations and init containers are added by third-party systems).

Basically, we are trying to setup new RBAC clusterroles for finalizers, and checking authorization during admission(just like PodSecurityPolicy checks the `use` permission on podsecuritypolicies).

**Comment by zhouhaibing089** [comment]
Does this require a KEP? I am interested to work on this.

**Comment by lavalamp** [comment]
If you want to change core kubernetes for this, then yes, it needs a KEP.

If you want to write a general admission controller that solves the problem, I don't think you need a KEP. I'm not 100% sure off the top of my head that we pass enough information about the user to the webhook admission controllers; so you may end up asking for more features there.

**Comment by zhouhaibing089** [comment]
I think a general admission + RBAC should suffice:

Briefly, we can define a virtual resource `<resource>/finalizers`, cluster administrators can create proper RBAC rules for it, for example, we can give GC controller permissions to remove finalizers `orphan`:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orphan-finalizer
rules:
- apiGroups:
  - "*"
  resources:
  - "*/finalizers"
  resourceNames:
  - "orphan"
  verbs:
  - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orphan-finalizer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: orphan-finalizer
subjects:
- kind: ServiceAccount
  name: generic-garbage-collector
  namespace: kube-system
```

During admission time, we get the user info, and:

1. All the new added finalizers.
1. Finalizers which are removed.

We send a call to authorizer to check whether that finalizer can be added or not.

I can think of two problems:

1. As also stated in the example, `*/finalizers` indicates finalizers on any resources, this is natively supported(I assume), since we do not wildcard like this way.
1. Potential performance penalty, it needs to set a number of authorization request.

Can I get some feedback here?
