### ISSUE TITLE
DevicePlugin is not working correct when the limit set to 0

### ISSUE THREAD

**Issue by pineking** [kubernetes/kubernetes#59629]
/kind bug
/sig node
/area hw-accelerators
/cc @vishh @jiayingz @vikaschoudhary16 @RenaudWasTaken 

**What happened**:
we can see all GPUs in container (`nvidia-smi`) when the limit of "nvidia.com/gpu" set to 0
also, `ls /dev/nvidia*` in container can see all GPU device files.

**What you expected to happen**:
`ls /dev/nvidia*` in container shows nothing when the limit of "nvidia.com/gpu" set to 0

**How to reproduce it (as minimally and precisely as possible)**:

yaml file:
```
apiVersion: v1
kind: Pod
metadata:
    name: fff
spec:
  containers:
  - name: fff
    image: nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
    resources:
      limits:
        nvidia.com/gpu: "0"
      requests:
        nvidia.com/gpu: "0"
    command: ["/bin/sh", "-c"]
    args: ["sleep 10d;"]
    imagePullPolicy: IfNotPresent
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
