### ISSUE TITLE
Unable to connect to SQL-lite db mounted on AzureFile/AzureDisks [SQLITE_BUSY: database is locked]

### ISSUE THREAD

**Issue by mfaizanse** [kubernetes/kubernetes#59755]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
/azure
/storage
> /kind feature

**What happened**:
I have a application which uses SQL-lite db to store/retrieve data inside the container. For providing persistent storage for this db file I tried Azure File and also Azure Disks using the storage classes for these. The problem is that the application fails to connect/query the SQL-lite db file throwing error 500. If I remove the Persistent Volume then the application works fine. The mounted volume is ReadWriteOnce.

One of my sample application works with a simple text file for storing data and it works fine. So, I think the issue is specific to a SQL-lite db file.

**What you expected to happen**:
The application should be able to connect/query the SQL-lite db file on Azure File/Disks mounted volume.

**How to reproduce it (as minimally and precisely as possible)**:
Run a application which generates a SQL-lite db file on mount volume and try to connect/query it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.1
- Cloud provider or hardware configuration: Azure Kubernetes Service
- OS (e.g. from /etc/os-release): linux
- Kernel (e.g. `uname -a`): linux
- Install tools: AKS
- Others:

**Comment by mfaizanse** [comment]
I have tried with a sample application (nodejs) using sqlite3. The exception get when i try to run a query is:
`Error: SQLITE_BUSY: database is locked`

**Comment by andyzhangx** [comment]
could you write to azure file/disk in pod, sounds like it's a app config issue.

**Comment by raphaelquati** [comment]
I think my problem is similar to this

I've created an Azure Storage, and try to run this:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testApache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testApache
    spec:
      containers:
      - name: testApache
        image: my/testApache:latest
        ports:
          - containerPort: 80
        volumeMounts:
          - name: testApache-data
            mountPath: /var/www/html
      volumes:  
      - name: testApache-data
        azureFile:
          secretName: azure-secret
          shareName: testApacheStorage
          readOnly: false
```
So, apache runs with user 'www-data', and azure-file mount the filesystem with 755:

```
~# mount | grep cifs
//xxxxxxxxxxxxxxxxxx.file.core.windows.net/dokuwikishare on /var/www/html type cifs (rw,relatime,vers=3.0,cache=strict,username=xxxxx,domain=,uid=0,noforceuid,gid=0,noforcegid,addr=1.1.1.1,file_mode=0755,dir_mode=0755,persistenthandles,nounix,serverino,mapposix,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1)
~# 
```
azure-file doesn't have option to set file_mode and dir_mode. So apache user (www-data) cannot write to any file at mount point.

**Comment by andyzhangx** [comment]
@raphaelquati here is the example how to set file_mode & dir_mode in azure file mountOptions:
https://github.com/andyzhangx/demo/blob/master/linux/azurefile/azurefile-mountoptions.md

**Comment by raphaelquati** [comment]
Yes. I know. But with kubernetes volume (not using persistent volume) (https://docs.microsoft.com/en-us/azure/aks/azure-files-volume), it doesn't work

**Comment by andyzhangx** [comment]
@raphaelquati Here is the working solution for you, it's using pv/pvc:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: testApacheStorage
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-azurefile
  storageClassName: ""
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapache
    spec:
      containers:
      - name: testapache
        image: my/testApache:latest
        ports:
          - containerPort: 80
        volumeMounts:
          - name: testapache-data
            mountPath: /var/www/html		
      volumes:  
      - name: testapache-data
        persistentVolumeClaim:
          claimName: pvc-azurefile	  
```

**Comment by raphaelquati** [comment]
Thanks. 

As I've said before: using persistent volume it works (and I'm using it). Using  kubernet volume, it doesn't work.

**Comment by andyzhangx** [comment]
@mfaizanse for this issue, you could set `nobrl` parameter in azure file mountOptions, you could follow by https://github.com/andyzhangx/demo/blob/master/linux/azurefile/azurefile-mountoptions.md, and this issue is duplicated to https://github.com/kubernetes/kubernetes/issues/61767

**Comment by andyzhangx** [comment]
close this issue since nobrl parameter could be set in azure file mountOptions, let me know if you have any question
/close

**Comment by andyzhangx** [comment]
@codefetcher you could use `volume.beta.kubernetes.io/mount-options` in v1.7.x and `volume.beta.kubernetes.io/mount-options` is only supported in PV, which means it only supports static provisioning(use exisiting file share)

Below is an example:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
  annotations:
    volume.beta.kubernetes.io/mount-options: "nobrl"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: k8stest
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: pv-azurefile
```
