### ISSUE TITLE
Pod resolve ::1 on internet hosts.

### ISSUE THREAD

**Issue by rvojcik** [kubernetes/kubernetes#59804]
**What happened**:
We just initialized new fresh kubernetes cluster version 1.8.8.
We are using kube-router 0.0.20 as network addon. 
When doing apt-get update or curl on remote hosts DNS resolve ::1 adress.

```
root@debug:/# apt-get update
Err:1 http://security.debian.org stretch/updates InRelease
  Could not connect to security.debian.org:80 (::1). - connect (111: Connection refused)
```
I tried ping, works fine. Traceroute, looks ok. 
I tried curl on same website and works when I used IPv4 ip address.

Seems like some issue with IPv6 and kube-DNS, maybe.

**How to reproduce it (as minimally and precisely as possible)**:
I used basic debian:stretch image
```
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: default
spec:
  containers:
  - name: debug
    image: debian
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
Then 
```
kubectl exec -ti -n default debug bash
apt-get update

```

**Anything else we need to know?**:

**Environment**: Debian Stretch
- Kubernetes version (use `kubectl version`): 1.8.8.
- Cloud provider or hardware configuration: Dell R610, 64GB RAM
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`):  4.4.112-ls-3
- Install tools: kubeadm
- Others:
