### ISSUE TITLE
Use `propagationPolicy: Foreground` in kubectl by default

### ISSUE THREAD

**Issue by nilebox** [kubernetes/kubernetes#59850]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
When I delete the owner object with child objects depending on it, some objects left orphaned and untouched. This is due to `kubectl` using a deprecated `orphanDependents: false` option instead of `propagationPolicy: Foreground`, and has incomplete deletion behavior in GC.

**What you expected to happen**:
All dependent objects should be either deleted immediately or marked with `deletionTimestamp` (if there is a finalizer). If children has finalizers (preventing deletion), their owner should not be deleted when `ownerReference` is marked with `blockOwnerDeletion: true` flag.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create 3 objects and set `ownerReference` with `blockOwnerDeletion: true` flag set, i.e. `root` <- `middle` <- `leaf`.
2. Add a custom finalizer (e.g. `nilebox/test-block-deletion`) on the `middle` object, which should prevent deletion of the `root`.
```
---
apiVersion: v1
kind: Secret
metadata:
  name: root
  namespace: sctest
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: middle
  namespace: sctest
  finalizers: # should block deletion of parent
  - nilebox/test-block-deletion
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Secret
    name: root
    # replace UID with the actual id of "root" object
    uid: 8c9ed2c3-109c-11e8-ba18-0a517c7aa8f4
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: leaf
  namespace: sctest
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Secret
    name: middle
    # replace UID with the actual id of "middle" object
    uid: 8cba4a7a-109c-11e8-ba18-0a517c7aa8f4
type: Opaque
```
3. Delete the `root` object using `kubectl` command:
```bash
delete secret root
secret "root" deleted
```
4. Result: `root` object is deleted, `middle` object is marked with `deletionTimestamp`, `leaf` is **NOT** marked with `deletionTimestamp`. 
Expected Result: `root` object is marked with `deletionTimestamp`, `middle` object is marked with `deletionTimestamp`, `leaf` is deleted.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.1
