### ISSUE TITLE
Can't delete statefulsets

### ISSUE THREAD

**Issue by carlosperezepfl** [kubernetes/kubernetes#59867]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Can't delete a statefulsets and I get an error
error: error when stopping "workers.yml": no kind "GetOptions" is registered for version "apps/v1"
```sh
$ kubectl auth can-i get  statefulsets
yes
$ kubectl auth can-i create  statefulsets
yes
$ kubectl auth can-i delete  statefulsets
yes
```

**What you expected to happen**:
statefulsets will be delete

**How to reproduce it (as minimally and precisely as possible)**:
Create a statefulsets and try to delete it
```sh
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
spec:
  serviceName: "experience1"
  replicas: 4
  selector:
    matchLabels:
      app: experience1
  template:
    metadata:
      labels:
        app: experience1
    spec:
      containers:
      - name: ssh
        image: ..... 
```

**Anything else we need to know?**:
It works with a "cluster-admin" role

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Bare metal
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):
Linux 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
GPUs Daemonsets
- Others:

**Comment by ecebuzz** [comment]
Is there any workaround for this bug?

**Comment by phsiao** [comment]
Just ran into something similar on 1.9.2.  Deleting the statefulset would timeout, and error messages in controller-manager log regarding the timeout.   Restarting controller manager fixed that for me in that instance.

**Comment by STVKRAO** [comment]
I ran into similar issue on 1.9.2. While deleting the statefulset, i am getting the error message:
error: no kind "GetOptions" is registered for version "apps/v1"

When ran with verbosity, see the below messages:

I0215 17:19:34.467985   25462 request.go:606] Error in request: no kind "GetOptions" is registered for version "apps/v1"
F0215 17:19:34.468031   25462 helpers.go:120] error: no kind "GetOptions" is registered for version "apps/v1"

versions are:

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by phsiao** [comment]
@carlosperezepfl @STVKRAO let's see if we can get more precise description of the issue together so the issue can be investigated.

I think it would be important to gather the following:

1. how to reproduce it.  I think at minimal the a yaml file that you use to apply/delete to demonstrate the problem, server/client version.
2. what actually broke in addition to the error message regarding "GetOptions".

In my case, the user ran into this with his production workload so I will need to work with him to reproduce it for 1., and in his case kubectl delete -f sts.yaml hangs and the statefulset was not deleted.  I looked into the controller-manager log and found timeout error on deleting, but restarting controller-manager fixed it.

**Comment by phsiao** [comment]
@carlosperezepfl 

> "message": "error when stopping \"mpich.yml\": services \"experience1\" not found",

From this log, it appears the "GetOptions" error is generated when it tries to GET the corresponding service but could not find it.   It is not clear what the sequence of events are, and whether this stops it from continuing on to delete the statefulset.

**Comment by phsiao** [comment]
I was able to reproduce it with a very simple yaml file.

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-59867
  namespace: sandbox
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-59867
  namespace: sandbox
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx-59867"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
```

Using 1.8.2 client to apply it works fine, using 1.8.2 client to delete show the error, but my verbose log is different

```
I0215 08:08:30.065697   99490 round_trippers.go:417] curl -k -v -XDELETE  -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: kubectl-1.8/v1.8.2 (darwin/amd64) kubernetes/bdaeafa" https://xxx:443/api/v1/namespaces/sandbox/services/nginx-59867
I0215 08:08:30.198982   99490 round_trippers.go:436] DELETE https://xxx:443/api/v1/namespaces/sandbox/services/nginx-59867 200 OK in 133 milliseconds
I0215 08:08:30.199014   99490 round_trippers.go:442] Response Headers:
I0215 08:08:30.199022   99490 round_trippers.go:445]     Date: Thu, 15 Feb 2018 13:08:30 GMT
I0215 08:08:30.199028   99490 round_trippers.go:445]     Audit-Id: e08e3efb-3382-41bb-9fe5-9c2bd8940ac3
I0215 08:08:30.199035   99490 round_trippers.go:445]     Content-Type: application/json
I0215 08:08:30.199041   99490 round_trippers.go:445]     Content-Length: 80
I0215 08:08:30.199085   99490 request.go:836] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Success","code":200}
I0215 08:08:30.207558   99490 request.go:606] Error in request: no kind "GetOptions" is registered for version "apps/v1"
F0215 08:08:30.207637   99490 helpers.go:120] error: error when stopping "59867.yaml": no kind "GetOptions" is registered for version "apps/v1"
```

Using 1.9.2 client to delete the yaml applied using 1.8.2 I don't see the same issue.   This might be a CLI version compatibility bug, and not an app bug.

/sig cli
