### ISSUE TITLE
Jobs - takes a while to update job status if job succeeds after retrying many times

### ISSUE THREAD

**Issue by csrwng** [kubernetes/kubernetes#59918]
/kind bug

**What happened**:

Create a job that will fail many times, but eventually succeeds.

After the job's pod succeeds, it takes a long time to update the job status.

**What you expected to happen**:

After the job's pod succeeds, the job's status is updated immediately.

**How to reproduce it (as minimally and precisely as possible)**:

Create a simple configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: result
data:
  result: failure
```

Create a job that runs a pod that fails based on the value of the configmap:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  backoffLimit: 100
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - command:
        - sh
        - -c
        - if [ "${RESULT}" = "failure" ]; then exit 1; fi
        image: busybox
        imagePullPolicy: IfNotPresent
        name: testjob
        env:
        - name: RESULT
          valueFrom:
            configMapKeyRef:
              name: result
              key: result
```

Let the job fail a few times
After about a minute or so, edit the configmap and change the value of its `result` key:

```
kubectl edit cm/result
```

Wait for the job to launch a pod that succeeds
```
kubectl get pods -w
```

Wait for the job to be updated based on the success of the pod
```
kubectl get jobs -w
```

There is about a 5 min wait between the time the pod succeeds and the job's status is updated.

**Anything else we need to know?**:

The job controller immediately gets a pod updated event, which results in the `enqueueController` method getting called.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L263

The `enqueueController` method applies a backoff based on how many times the job has been retried:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L352-L361

This seems wrong. The backoff should be applied to pod creation and not to handling an update event from an existing pod.
