### ISSUE TITLE
Image mismatch when an image have multiple tags

### ISSUE THREAD

**Issue by stackexpress-kushal** [kubernetes/kubernetes#60031]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.5
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools: 
- Others:

I have a deployment running with 2 pods I noticed a images mismatch in these 2 replicas. I have an image with different tags. 

Image-1 - xxxxxxxxxxxxxxxxxxxxxxxxx/api:157 (digest - api@sha256:9e85f778b89d7a65c9045216xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd38216a6)
Image-2 - xxxxxxxxxxxxxxxxxxxxxxxxx/api:158 (digest - api@sha256:9e85f778b89d7a65c9045216xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd38216a6)

I have deployed the image with  updated  tag (xxxxxxxxxxxxxxxxxxxxxxxxx/api:158) of same digest.

deployment yaml seems like :- 

```
image: xxxxxxxxxxxxxxxxxxxxxxxxx/api:158
 imagePullPolicy: Always
 lifecycle:
   preStop:
     exec:
       command:
       - bash
       - -c
       - sleep 120
```

 But both the replicas are running with same image with different tags, which seems a abnormal behavior. I think container image name should be the same (xxxxxxxxxxxxxxxxxxxxxxxxx/api:158) as deployed if same images have multiple tags.

Two different containers of a deployment with same image but different tags

```
containerStatuses:
 - containerID: docker://bf3b4546c332271e2275e1422fa3ab6ab71ccfef3659a939a890394969115e66
   image: xxxxxxxxxxxxxxxxxxxxxxxxx/api:157
   imageID: docker-pullable://xxxxxxxxxxxxxxxxxxxxxxxxx/api@sha256:9e85f778b89d7a65c9045216xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd38216a6
   lastState: {}
   name: api
   ready: true
   restartCount: 0
   state:
     running:

containerStatuses:
 - containerID: docker://b743751247580809aa8d175ab1010a21e9301a083d6de23952b55ccc1f4d7b40
   image: xxxxxxxxxxxxxxxxxxxxxxxxx/api:158
   imageID: docker-pullable://xxxxxxxxxxxxxxxxxxxxxxxxx/api@sha256:9e85f778b89d7a65c9045216xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd38216a6
   lastState: {}
   name: api
   ready: true
   restartCount: 0
   state:
     running:
```
