### ISSUE TITLE
Allow to use envs in manifest

### ISSUE THREAD

**Issue by sebarys** [kubernetes/kubernetes#60138]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
As a developer I want to have possibility to use envs provided from Secrets and CofigMaps in other places in manifest.

**What you expected to happen**:
Could use envs e.g. in liveness/rediness probes section, or use one env as a interpolation of other envs.

**How to reproduce it (as minimally and precisely as possible)**:
I want to use my env BASICAUTH value in livenessProve header value. Example manifest:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /server
  - name: BASICAUTH
    valueFrom:
      secretKeyRef:
        name: basicauth
        key: BASICAUTH
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Authorization
          value: $(BASICAUTH)
      initialDelaySeconds: 3
      periodSeconds: 3

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Client: v1.7.12, Server: v1.7.9+coreos.0
- Cloud provider or hardware configuration: AWS instances
- OS (e.g. from /etc/os-release): Ubuntu
