### ISSUE TITLE
Volume from a remote archive

### ISSUE THREAD

**Issue by fkorotkov** [kubernetes/kubernetes#60146]
/kind feature

**What happened**:

Right now it's possible to have `gitRepo` volume which is nice. It mounts an empty directory and clones a git repository into it for a pod to use

**What you expected to happen**:

It will be wonderful to be able to have a volume from a remote archive. Kubernetes can mount an empty directory, download an archive by URL and unarchive it for a pod to use. Config can look like this:

```
volumes:
  - name: archive-volume
    remoteArchive:
      url: "https://github.com/me/my-repo/archive/v1.0.0.tar.gz"
      format: "TarGz"
      shaSum: "22f1d8406d464b0c0874075539c1f2e96c253775"
```

It can support different formats like Tar, TarGz and Zip.
