### ISSUE TITLE
IPVS not working with hostPort ingress controller

### ISSUE THREAD

**Issue by ryarnyah** [kubernetes/kubernetes#60305]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: use kube-proxy with ipvs enable, deploy traefik ingress controller daemonset with hostPort(same as apiserver service port). Traefik can't contact kube-apiserver on 100.64.0.1:443.
```
# ipvsadm -l
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  100.64.0.1:443 rr persistent 10800
  -> master1:6443           Masq    1      0          0
  -> master2:6443           Masq    1      2          0
  -> master3:6443           Masq    1      0          0
```

When i tried to curl 100.64.0.1:443 from host, it connect to traefik 443.
```
# curl -k https://100.64.0.1
404 page not found (traefik)
# curl -k https://master1:6443
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

**What you expected to happen**: Traefik and my curl must contact the apiserver

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-certificates-secret
  namespace: default
type: Opaque
data:
  server.cert: ...
  server.key: ...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: default
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    checkNewVersion = false
    RootCAs = ["/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"]

    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
      [entryPoints.https]
      address = ":443"
      compress = true
        [entryPoints.https.tls]
        minVersion = "VersionTLS12"
        cipherSuites = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA","TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA","TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256","TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA","TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA","TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"]
          [[entryPoints.https.tls.certificates]]
          CertFile = "/etc/ssl/certs/server.cert"
          KeyFile = "/etc/ssl/certs/server.key"
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-controller
  namespace: default
  labels:
    k8s-app: traefik-ingress-lb
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      nodeSelector:
        kubernetes.io/role: lb
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:1.5.2
          name: traefik-ingress-lb
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/config"
              name: "config"
            - name: ca-certificates
              mountPath: /etc/ssl/certs
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
            - containerPort: 8080
          args:
            - --configfile=/config/traefik.toml
            - --web
            - --web.metrics.prometheus
            - --kubernetes
            - --logLevel=INFO
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      volumes:
        - name: config
          configMap:
            name: traefik-conf
        - name: ca-certificates
          secret:
            secretName: traefik-certificates-secret
```

**Anything else we need to know?**: traefik is installed on a node tagged "kubernetes.io/role: lb". RBAC configuration not included on example.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: Virtualbox
- OS (e.g. from /etc/os-release): Centos 7.3
- Kernel (e.g. `uname -a`): Linux controller1 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: hard way
- Others:
