### ISSUE TITLE
#2 Cannot reach Kube DNS from pod

### ISSUE THREAD

**Issue by ivantichy** [kubernetes/kubernetes#60315]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Creating new issue as the original one was closed without solution, more people announced the problem and there was no response on Closed issue thread.
Cannot reach kube dns (e.g. nslookup kubernetes.default) from busybox test pod.

Details here: 
https://github.com/kubernetes/kubernetes/issues/57558

I would prefer reopening the old issue.

**Comment by dgabrysch** [comment]
Is this a kubeadm cluster? If yes, check your systemd kubelet.conf.d/10-kubeadm.conf, there should be an entry with DNS pointing to the service IP of your kube-dns service.

**Comment by ivantichy** [comment]
```
cat ./etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS

```

**Comment by xguerin** [comment]
I'm having the same issue here. It seems to only happen when the container gets scheduled on a worker node. When scheduled on the master node, it works fine. Here is my job configuration:

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: n0
spec:
  template:
    spec:
      containers:
      - name: node
        image: busybox
        imagePullPolicy: Always
        command: ["sh", "-c", "sleep 3600"]
      restartPolicy: Never
  backoffLimit: 1
...
```

I then connect to the container:

```
/ #  nslookup n0
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'n0'
/ #
```

I am using `calico` so it might be a problem with that. I used `kubeadm` and checked that all my configuration matched.
