### ISSUE TITLE
device name change due to azure disk host cache setting

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#60344]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
From v1.7, default host cache setting changed from `None` to `ReadWrite`, this would lead to device name change after attach multiple disks on azure vm, finally lead to disk unaccessiable from pod.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Following statefulset with 8 replicas will always fail due to dev name change.

```
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: myvm
spec:
  selector:
    matchLabels:
      app: myvm # has to match .spec.template.metadata.labels
  serviceName: "myvm"
  replicas: 8
  template:
    metadata:
      labels:
        app: myvm 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ubuntu
        image: ubuntu:xenial
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        livenessProbe:
          exec:
            command:
            - ls
            - /mnt/data
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
        volumeMounts:
        - name: mydata
          mountPath: /mnt/data
  volumeClaimTemplates:
  - metadata:
      name: mydata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 1Gi
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7 - v1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign
