### ISSUE TITLE
Issues with mapping TLS client cert OU to group

### ISSUE THREAD

**Issue by joejulian** [kubernetes/kubernetes#60351]
/kind bug
/sig auth

**What happened**:
When using mTLS authentication, the cn is mapped to the username and the ou is mapped to the group. The standard method for delegating the authority to create users within an ou is to use intermediate certificates (see https://joejulian.name/post/vault-pki-for-kubernetes/ for an example). If the intermediate certificate authority creates a certificate within its ou with a username that has cluster role bindings (eg admin), that user is not restricted to roles allowed by the group and is, instead, authorized as just that user. This allows a sub-authority to gain admin privileges to the entire cluster.

**What you expected to happen**:
Group role, when specified, should take precedence over user roles.

**How to reproduce it (as minimally and precisely as possible)**:
See https://joejulian.name/post/vault-pki-for-kubernetes/ for the steps needed to create an ou assigned user.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.3

**Comment by ericchiang** [comment]
Just to clarify. This is an issue with the differences in how vault and kubernetes handle the OU field, not an actual bug in the validation? E.g. you may disagree in with the way we handle OU, but you're not reporting that our implementation of that handling logic is broken.

**Comment by liggitt** [comment]
there are many varieties of mapping schemes from x509-encoded identity to username and group membership. some embed data in the certificate (in various ways), some rely on external system lookups.

to support alternate mappings of x509 data to username/groups, you can use an authenticating proxy that verifies the client certificate, transforms into user/groups as you wish, and passes that info to the apiserver via headers, secured with mTLS. See https://kubernetes.io/docs/admin/authentication/#authenticating-proxy for more information.

/close

**Comment by joejulian** [comment]
No, they field is being mapped just fine. If there is no user rbac role defined, the group role is applied. If there *is* a user role it is applied. This allows the user to override the group.

**Comment by liggitt** [comment]
I'm having a hard time understanding what you are proposing. Can you provide a concrete example of an x509 cert, and how you would like to see the API server handle it differently than it does today?

> If there is no user rbac role defined, the group role is applied. If there is a user role it is applied. 

That sounds like mixing the authorization and authentication layers, which are intentionally separated today.

> This allows the user to override the group.

User and group RBAC grants are additive, and there are no plans to change that. It is unexpected that granting a role to a user would result in them having fewer effective permissions.

**Comment by joejulian** [comment]
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: accounting
  name: accounting-pods
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","pods/log"]
  verbs: ["get", "watch", "list"]
```
Apply that role to the accounting group
```
# This role binding allows "jane" to read pods in the "default" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: accounting
subjects:
- kind: Group
  name: accounting
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: accounting-pods
  apiGroup: rbac.authorization.k8s.io
```
A user authenticates as user: john, group: accounting
John can list pods in the accounting namespace and access the logs of those pods. He cannot do anything in any other namespace.

Next, a user authenticates as user: admin, group: accounting
This user has access to the entire cluster because they get the admin ClusterRole bound to the username admin.
