### ISSUE TITLE
cronjob history limit ineffective

### ISSUE THREAD

**Issue by HYmian** [kubernetes/kubernetes#60403]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I create a cronjob with   
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 3
but my all job history exist always
and my controller-manager have error log: Error syncing job: Operation cannot be fulfilled on jobs.batch "curator-1519625280": the object has been modified; please apply your changes to the latest version and try again

when I delete the cronjob, jobs created by the cronjob don't deleted

**What you expected to happen**:
get 4 history at most

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f clear.yml
and this my yaml file
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator
spec:
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 60
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 30
      template:
        spec:
          containers:
          - name: clear
            env:
            - name: LOG_LEVEL
              value: DEBUG
            image: ymian/curator:latest
            imagePullPolicy: Always
          restartPolicy: Never
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
no Cloud provider
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux dev-7 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
kubeadm
- Others:
