### ISSUE TITLE
kubeadm cannot work with external cloudprovier under selfhosting mode

### ISSUE THREAD

**Issue by aoxn** [kubernetes/kubernetes#60410]
> /kind bug

> /sig cluster-lifecycle

## Problem describe
kubeadm.cfg
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
cloudProvider: external
imageRepository: registry.cn-hangzhou.aliyuncs.com/acs
featureGates:
  selfHosting: true
networking:
  dnsDomain: cluster.local
  serviceSubnet: 172.19.0.0/20
  podSubnet: 172.16.0.0/16
apiServerCertSANs:
  - 192.168.110.109
  - 127.0.0.1
token: cdca7c.3e8035f5959f0da6
nodeName: cn-hongkong.i-j6cal2nyrssnrcz2mju7
kubernetesVersion: v1.9.3
```

kubeadm init --config kubeadm.cfg

```
[self-hosted] Creating self-hosted control plane.
[apiclient] Found 0 Pods for label selector k8s-app=self-hosted-kube-apiserver
error creating self hosted control plane: timed out waiting for the condition
```

**error creating self hosted control plane: timed out waiting for the condition** Error occured.

```
kubectl get no -o yaml 

  spec:
    externalID: cn-hongkong.i-j6cal2nyrssnrcz2mju7
    podCIDR: 172.16.0.0/24
    providerID: cn-hongkong.i-j6cal2nyrssnrcz2mju7
    taints:
    - effect: NoSchedule
      key: node.cloudprovider.kubernetes.io/uninitialized
      value: "true"
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
```

## Fix 

kubelet will taint node with ```node.cloudprovider.kubernetes.io/uninitialized``` on node initializing. kubeadm should take care of this taint by adding a toleration on control panel pod when bootstrap a cluster.

A PR to fix this will be submitted soon.
