### ISSUE TITLE
Unexplicit alert when scale up pods with persistant volume

### ISSUE THREAD

**Issue by Vskilet** [kubernetes/kubernetes#60652]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
When you scale a deployment that contains a persistent volume which is configure in accessMode : ReadWriterOnce, there is no disclaimer when you want to scale the pod in the web interface. In fact we have errors from vSphere because kubernetes can't attach this type of volume at to pods.

**What you expected to happen**:
Maybe the interface should alert us when we trying to scale up this type of deployments.

![image](https://user-images.githubusercontent.com/7677567/36855951-1b19ad4c-1d75-11e8-8f63-4ca6e5769406.png)

**How to reproduce it (as minimally and precisely as possible)**:
I tried to deploy drupal with helm, so in the config file, we can see that configuration for mariadb : 
```
 # Source: drupal/charts/mariadb/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: quarrelsome-sheep-mariadb
  labels:
    app: quarrelsome-sheep-mariadb
    chart: "mariadb-1.0.5"
    release: "quarrelsome-sheep"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
```

**Anything else we need to know?**:
Kubernetes was deploy by BOSH on vSphere infrastructure with vSan.

**Environment**:
- Kubernetes version :
````
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"269f928217957e7126dc87e6adfa82242bfe5b1e", GitTreeState:"clean", BuildDate:"2017-06-06T13:19:52Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
````
- Cloud provider or hardware configuration: VM in vSphere provide with Bosh (https://docs-cfcr.cfapps.io/)
- OS (e.g. from /etc/os-release): ``Redhat 7.4``
- Kernel (e.g. `uname -a`): ``Linux ClientDocker 3.10.0-693.11.1.el7.x86_64 #1 SMP Fri Oct 27 05:39:05 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux``
- Install tools: BOSH
- Others: vSan

**Comment by prashima** [comment]
@kubernetes/vmware

**Comment by prashima** [comment]
@Vskilet couple of questions regarding the proposed disclaimer:

- Do you want a better failure message in Kubernetes dashboard?
- Is the request for better event messaging?

To understand failure better:
- Was this a one time failure or is your deployment still not up and running?
- Is the deployment is still in error state, can you please share the event message for ```kubectl describe deployment <your deployment>```?

**Comment by Vskilet** [comment]
@prashima 
- It's request for better messaging which include to be better in the dashboard.
- Deployment still not up.
- The deployment is with helm

```
# Source: drupal/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: undercooked-puma-drupal
  labels:
    app: undercooked-puma-drupal
    chart: "drupal-0.11.8"
    release: "undercooked-puma"
    heritage: "Tiller"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: undercooked-puma-drupal
    spec:
      containers:
      - name: undercooked-puma-drupal
        image: "bitnami/drupal:8.4.5-r1"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_HOST
          value: undercooked-puma-mariadb
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: DRUPAL_DATABASE_NAME
          value: "bitnami_drupal"
        - name: DRUPAL_DATABASE_USER
          value: "bn_drupal"
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: undercooked-puma-mariadb
              key: mariadb-password
        - name: DRUPAL_USERNAME
          value: "user"
        - name: DRUPAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: undercooked-puma-drupal
              key: drupal-password
        - name: DRUPAL_EMAIL
          value: "user@example.com"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /user/login
            port: http
          initialDelaySeconds: 120
          
        readinessProbe:
          httpGet:
            path: /user/login
            port: http
          initialDelaySeconds: 30
          
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          
        volumeMounts:
        - name: drupal-data
          mountPath: /bitnami/drupal
        - name: apache-data
          mountPath: /bitnami/apache
      volumes:
      - name: drupal-data
        persistentVolumeClaim:
          claimName: undercooked-puma-drupal-drupal
      - name: apache-data
        persistentVolumeClaim:
          claimName: undercooked-puma-drupal-apache
```
