### ISSUE TITLE
Specifying Subnet for Internal LoadBalancer in GCE

### ISSUE THREAD

**Issue by cholick** [kubernetes/kubernetes#60665]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:

Created a service of type "LoadBalancer" using the `cloud.google.com/load-balancer-type` internal annotation, I would like to also explicitly specify the subnet.

This is an option in some other cloud providers, see:
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L41

**What you expected to happen**:

I expected to be able to specify the subnet as an annotation (my cluster is deployed in a networking setup with multiple subnets).

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    cloud.google.com/load-balancer-subnet: "my-subnet"
  labels:
    app: my-app
spec:
  type: LoadBalancer
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: my-app
```

Where I would like for `cloud.google.com/load-balancer-subnet` to be an annotation.

**Anything else we need to know?**:

Azure [does support this](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L41):

The changes would be scoped to the GCE specific provider implementation, likely touching:
* [cloudprovider/providers/gce/gce_loadbalancer_internal.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce_loadbalancer_internal.go)
* [cloudprovider/providers/gce/gce_loadbalancer.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce_loadbalancer.go)
* [cloudprovider/providers/gce/gce_annotations.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce_annotations.go)

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.9.2`
- Cloud provider or hardware configuration: gce

cc @jshah-pivotal

**Comment by nicksardo** [comment]
cc @bowei

**Comment by darkstarmv** [comment]
it is impossible to create GCE internal load balancer without specifying subnet when there is no default subnetwork in the project:
```
Events:
  Type     Reason                      Age                From                Message
  ----     ------                      ----               ----                -------
  Normal   EnsuringLoadBalancer        12s (x3 over 37s)  service-controller  Ensuring load balancer
  Warning  CreatingLoadBalancerFailed  11s (x3 over 28s)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service kube-system/ambassador: googleapi: Error 404: The resource 'projects/XXXXXX/regions/us-XXXXX/subnetworks/default' was not found, notFound
```

**Comment by ffilippopoulos** [comment]
I managed to create an internal load balancer by specifying network and subnet in kube-controller configuration.
My conf is a file with just:
```
multizone = true
network-name=<network-name>
subnetwork-name=<subnet-name>
```
and I pass it to `kube-controller-manager` as `--cloud_config=<path-to-file>`.
That does the trick:
```
NAME           TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
grafana        LoadBalancer   10.5.40.88    10.22.22.2    3000:32068/TCP   9d
```
my manifest is:
```
 apiVersion: v1
 kind: Service
 metadata:
  name: grafana
   namespace: sys-mon
   labels:
     name: grafana
   annotations:
     cloud.google.com/load-balancer-type: "Internal"
 spec:
   type: LoadBalancer
   selector:
     app: grafana
   ports:
   - name: grafana
     protocol: TCP
     port: 3000
```
hope that helps!
