### ISSUE TITLE
Failed to allocate requested HealthCheck NodePort, provided port is already allocated

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes/kubernetes#60749]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
Service of type LoadBalancer in AWS fails to get created when using `healthCheckNodePort` with value of one of the node ports in a multi-port Service. **Im trying to set a specific heath check port in the ELB created by the Service otherwise it picks up the first one in the list by default**. The service can see it is it's own port so what is the problem here? The Node ports in the example are for sure not used till the moment the manifest was run.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
The relevant part of the Service manifest:

```
...
spec:
  ports:
  - name: app
    nodePort: 32103
    port: app-port
    protocol: TCP
    targetPort: app-port
  - name: hc
    nodePort: 30989
    port: hc-port
    protocol: TCP
    targetPort: hc-port
  selector:
    app: my-app
  sessionAffinity: None
  type: LoadBalancer
  healthCheckNodePort: 30989
  externalTrafficPolicy: Local
```

**Anything else we need to know?**:
Using `kube-proxy` in iptables mode.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.5
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
