### ISSUE TITLE
[feature requirements] specify hw devices in container

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#60748]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
The previous discussion happened in #5607, which is pretty old and with no background of CRI, no to mention Device Plugin. Also, I believe the original requirement in #5607 should have already been fixed by Device Plugin.

While new requirements showing up is: **how to specify devices in container by user, or per DP requirement**? And how can we make this work with current DP design. 
```yaml
containers:
  - name: demo2
    image: sfc-dev-plugin:latest
    # I am not proposing this API, just to clarify the use case
    hostDevices:
    - /dev/foo1
    - /dev/foo2
```

This is actually needed during implementing many Device Plugins. One example is RDMA: https://github.com/hustcat/k8s-rdma-device-plugin, in which case,`/dev/infiniband/rdma_cm` should be passed in all container which use RDMA device for run RDMA application in container.

@hustcat Please correct me if I mis-understood sth.

Others devices including:  `/dev/dri/renderD128` `/dev/infiniband` etc. 

**What you expected to happen**:

We may need to collect user requirements first, and re-visit DP to see how to support this.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

cc @RenaudWasTaken @vikaschoudhary16 @derekwaynecarr @vishh @jiayingz 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
