### ISSUE TITLE
Kubernetes silently discards annotations if one is invalid

### ISSUE THREAD

**Issue by gwkunze** [kubernetes/kubernetes#60843]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
(Although also maybe bit of a usability feature)

**What happened**:
I created an ingress rule in a yaml file with a couple of annotations, one of the annotations had the value `yes`. Kubernetes accepted the resource but a check with `kubectl get ingress my-ingress-rule -o yaml` showed none of the annotations.

It turns out that yaml sees the string `yes` as a boolean and it seems that while annotations should be a string value, kubectl/kube-api silently accepts invalid annotations without showing any error and *also* discards any other valid annotations

**What you expected to happen**:
I'd expect kubectl or kube-api to complain about malformed annotations.

**How to reproduce it (as minimally and precisely as possible)**:
With the following YAML file called `test.yml`:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress-rule
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    test.com/foo: yes
spec:
  rules:
  - host: my-service.com
    http:
      paths:
      - path: /
        backend:
          serviceName: my-service
          servicePort: 80
```
Run
```bash
kubectl apply -f test.yml && kubectl get ingress my-ingress-rule -o yaml && kubectl delete -f test.yml
```

Note that the annotations are not present.

**Anything else we need to know?**:

**Environment**:
Tested on minikube (k8s 1.9) and a cluster on AWS provisioned by kops (k8s 1.8)

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Minikube and AWS/Kops
- OS (e.g. from /etc/os-release):
CentOS for the AWS cluster
- Kernel (e.g. `uname -a`):
3.10.0-693.11.6.el7.x86_64
- Install tools:
Kops
- Others:
N/A afaict
