### ISSUE TITLE
kubeadm: specifying controllerManagerExtra arg did not take precedence 

### ISSUE THREAD

**Issue by tmjd** [kubernetes/kubernetes#60896]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I was specifying `node-cidr-mask-size` in a kubeadm config file under `controllerManagerExtraArgs` to set the flag. kube-controller-manager was started with 2 instances of `--node-cidr-mask-size` being passed to it.  The 2nd instance was the default that kubeadm adds and overrode the value I was attempting to set.

**What you expected to happen**:
kube-controller-manager should have been started with one instance of `--node-cidr-mask-size` or at least the one I specified would be the 2nd so that it would take precedence.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run `kubeadm init --config=myconfig.yaml` with the following as the contents of the file myconfig.yaml
  ```
  apiVersion: kubeadm.k8s.io/v1alpha1
  kind: MasterConfiguration
  api:  
    advertiseAddress: "fd10::101"
  networking:
    serviceSubnet: fd30::0/110   
    podSubnet: "fd20:0::/120"    
  controllerManagerExtraArgs:
    node-cidr-mask-size: "120" 
  ```
2. Check the flags that kube-controller-manager is started with.

**Anything else we need to know?**:
This was an issue for me when trying to use kubeadm to setup an IPv6 cluster and specify a podSubnet.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.3
- Cloud provider or hardware configuration: VirtualBox
- OS (e.g. from /etc/os-release): 
  ```
  NAME="Container Linux by CoreOS"
  ID=coreos
  VERSION=1576.4.0
  VERSION_ID=1576.4.0
  BUILD_ID=2017-12-06-0449
  PRETTY_NAME="Container Linux by CoreOS 1576.4.0 (Ladybug)"
  ANSI_COLOR="38;5;75"
  HOME_URL="https://coreos.com/"
  BUG_REPORT_URL="https://issues.coreos.com"
  COREOS_BOARD="amd64-usr"
  ```
- Kernel (e.g. `uname -a`): `Linux k8s-master 4.13.16-coreos-r2 #1 SMP Wed Dec 6 04:27:34 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz GenuineIntel GNU/Linux`
- Install tools:
- Others:
