### ISSUE TITLE
Job restarted despite "restartPolicy: Never"

### ISSUE THREAD

**Issue by sylr** [kubernetes/kubernetes#60930]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

We launched a Job with :

```
spec:
  activeDeadlineSeconds: 30
  completions: 1
  parallelism: 1
  template:
    ...
    spec:
      ...
      restartPolicy: Never
```

It failed and it got restarted.

**What you expected to happen**:

We expected to not get restarted if failed.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.10
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ShualLiu** [comment]
I found it was fixed in 
```
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.8", GitCommit:"2f73858c9e6ede659d6828fe5a1862a48034a0fd", GitTreeState:"clean", BuildDate:"2018-02-09T21:23:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sylr** [comment]
@ShualLiu I did not find any mention of this is the 1.8.8 release note.

How did you find out ?

**Comment by ShualLiu** [comment]
I'm sorry for that. Do you mean this situation?
```
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: countdown
    spec:
      activeDeadlineSeconds: 3000
      completions: 1
      parallelism: 1
      template:
        metadata:
          name: countdown
        spec:
          containers:
          - name: counter
            image: registry.ek.ekos.local/ekos/bb
            command:
             - "exit -1"
          restartPolicy: Never
```

```
[root@master2 ~]# kubectl describe job countdown 
Name:                     countdown
Namespace:                default
Selector:                 controller-uid=358b0eea-266d-11e8-8670-001a4a180005
Labels:                   controller-uid=358b0eea-266d-11e8-8670-001a4a180005
                          job-name=countdown
Annotations:              <none>
Parallelism:              1
Completions:              1
Start Time:               Tue, 13 Mar 2018 11:18:32 +0800
Active Deadline Seconds:  3000s
Pods Statuses:            0 Running / 0 Succeeded / 7 Failed
Pod Template:
  Labels:  controller-uid=358b0eea-266d-11e8-8670-001a4a180005
           job-name=countdown
  Containers:
   counter:
    Image:  registry.ekos.local/ekos/bb
    Port:   <none>
    Command:
      exit -1
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason                Age   From            Message
  ----     ------                ----  ----            -------
  Normal   SuccessfulCreate      17m   job-controller  Created pod: countdown-k9wl4
  Normal   SuccessfulCreate      17m   job-controller  Created pod: countdown-pmddw
  Normal   SuccessfulCreate      16m   job-controller  Created pod: countdown-z8fnz
  Normal   SuccessfulCreate      16m   job-controller  Created pod: countdown-fvs8d
  Normal   SuccessfulCreate      16m   job-controller  Created pod: countdown-bjt26
  Normal   SuccessfulCreate      15m   job-controller  Created pod: countdown-p5x8h
  Normal   SuccessfulCreate      14m   job-controller  Created pod: countdown-qwsjk
  Warning  BackoffLimitExceeded  11m   job-controller  Job has reach the specified backoff limit

```
