### ISSUE TITLE
"CreateContainerConfigError: failed to prepare subPath for volumeMount" error with configMap volume

### ISSUE THREAD

**Issue by Silvenga** [kubernetes/kubernetes#61076]
/kind bug

**Fix status:**
- [x] merged in master in https://github.com/kubernetes/kubernetes/pull/61080, will be in 1.10.0-rc.1
- [x] merged in release-1.9 branch in https://github.com/kubernetes/kubernetes/pull/61107, in [v1.9.5](https://github.com/kubernetes/kubernetes/releases/tag/v1.9.5)
- [x] merged in release-1.8 branch in https://github.com/kubernetes/kubernetes/pull/61108, in [v1.8.10](https://github.com/kubernetes/kubernetes/releases/tag/v1.8.10)
- [x] merged in release-1.7 branch in https://github.com/kubernetes/kubernetes/pull/61109, in [v1.7.15](https://github.com/kubernetes/kubernetes/releases/tag/v1.7.15)

**What happened**:
Upgraded from v1.9.2 to v1.9.4. I began to bring up the cluster (still messing with different strategies on upgrade) and noticed that every pod that would mount a configMap via subPath would throw a similar error to the one below:

```
Mar 12 22:30:27 node02 kubelet[1124]: E0312 22:30:27.537327    1124 kubelet_pods.go:248] failed to prepare subPath for volumeMount "config" of container "mumble": subpath "/var/lib/kubelet/pods/66fa673c-266d-11e8-8ebf-00155d00a406/volumes/kubernetes.io~configmap/config/..2018_03_13_03_19_55.572152209/mumble.ini" not within volume path "/var/lib/kubelet/pods/66fa673c-266d-11e8-8ebf-00155d00a406/volumes/kubernetes.io~configmap/config"
Mar 12 22:30:27 node02 kubelet[1124]: E0312 22:30:27.537452    1124 kuberuntime_manager.go:734] container start failed: CreateContainerConfigError: failed to prepare subPath for volumeMount "config" of container "mumble"
Mar 12 22:30:27 node02 kubelet[1124]: E0312 22:30:27.537548    1124 pod_workers.go:186] Error syncing pod 66fa673c-266d-11e8-8ebf-00155d00a406 ("mumble-74798bc4c-xjwrn_default(66fa673c-266d-11e8-8ebf-00155d00a406)"), skipping: failed to "StartContainer" for "mumble" with CreateContainerConfigError: "failed to prepare subPath for volumeMount \"config\" of container \"mumble\""
```

**What you expected to happen**:
To mount the configMap.

_Existing behavior:_ 
https://stackoverflow.com/questions/48561338/how-to-correctly-mount-configmap-with-subpath-in-kubernetes-not-update-configs
https://stackoverflow.com/questions/44325048/kubernetes-configmap-only-one-file

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: mumble-config
data:
  mumble.ini: |
    # Murmur configuration file.
```

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mumble
  labels:
    app: mumble
spec:
  template:
    metadata:
      labels:
        app: mumble
    spec:
      containers:
      - image: custom-image
        name: mumble
        volumeMounts:
        - name: config
          mountPath: /data/mumble.ini
          subPath: mumble.ini
      volumes:
      - name: config
        configMap:
          name: mumble-config
```

**Anything else we need to know?**:

Looking further into it it looks like a possible regression caused by #60813?

https://github.com/kubernetes/kubernetes/pull/61045/files#diff-16665fc8caff20aa7d63896dc4e3dd7fR295

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Self-hosted - 3 VM's - 1 master, two nodes.
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux master 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

**Comment by Silvenga** [comment]
Downgraded to v1.9.3, the problem does not appear to exist.

**Comment by andreimc** [comment]
I had the same issue, I am not sure if this behaviour is intended and we should use Pod Security Policies to allow the mounting of config maps ?

**Comment by liggitt** [comment]
@kubernetes/sig-storage-bugs 
/assign @jsafrane @msau42

**Comment by liggitt** [comment]
> it looks like a possible regression caused by #60813?

thanks for the report. yes, it is related to the fix for #60813 and a backstep detection function that hits a false positive with the directory structure used by configmap/secret volumes

a fix is in progress in https://github.com/kubernetes/kubernetes/pull/61080

**Comment by andyzhangx** [comment]
Need to mention that this issue also exists in Windows, and the PR also covers for windows.

**Comment by jberkus** [comment]
@liggitt if this is a 1.9.4 issue, why the 1.10 milestone?

**Comment by liggitt** [comment]
it's a recently introduced regression that is release blocking and needs cherry picking to 1.7.x, 1.8.x, and 1.9.x

**Comment by dims** [comment]
@jberkus this problem was triggered by the change made for the CVE yesterday (which had patch for 1.10/master which was backported to 1.9,1.8,1.7 branches). when we shipped 1.9.4, someone noticed it. So this problem exists in v.1.10/master as well. So we start here and then do backports again (i believe @liggitt has filed backports already)

**Comment by joelsmith** [comment]
It's nice that we're fixing this, but we probably ought to document that configMap and secrets don't work especially well with subPaths since any update to the underlying API object will cause the file to disappear from the view of the container.  Since the subPath mount will cause the container runtime to mount only the version of the file or directory that exists when the container starts, any atomic update of the data will remove the old version and create a new version that the subPath can't see.

I think we should:
1. Update documentation to direct people to (a) mount the entire volume, then (b) symlink their desired subPath to that mounted volume. For example, this bug reporter might mount at `/mnt/config` and have a symlink from `/data/mumble.ini` to `/mnt/config/mumble.ini`.
2. Consider adding some kind of no-update flag to configMap/secret/downwardAPI/projected volumes for those that don't need the atomic update feature.  Any containers mounting subPaths would not have to worry about the file disappearing on update, but would require a pod restart to get a data refresh.

**Comment by saitejar** [comment]
Is there a workaround for this issue?

**Comment by liggitt** [comment]
> Is there a workaround for this issue?

There is not.

**Comment by liggitt** [comment]
keeping this open until release branches are fixed as well

**Comment by liggitt** [comment]
@jberkus fix merged into master, moving this back to the v1.9 milestone as this issue is no longer release blocking

**Comment by Joseph-Irving** [comment]
Hi. I've upgrade to the fixed version of 1.9.4 which has solved the configmap subpath problem but I'm encountering the same issue when using subPaths with an emptyDir. 
```
Warning  Failed                 1m (x2 over 2m)  kubelet, ip-172-23-10-171.eu-west-1.compute.internal  Error: failed to prepare subPath for volumeMount "flannel-net-conf" of container "kube-flannel"
```
where the volume looks like:
```
volumes:
- emptyDir: {}
   name: flannel-net-conf
```
and the volume mount is this
```
 volumeMounts:
  - mountPath: /etc/kube-flannel/net-conf.json
     name: flannel-net-conf
     subPath: net-conf.json
```
This works fine on 1.9.3. Should I open a new issue about this?

**Comment by jsafrane** [comment]
@Joseph-Irving, I can't reproduce the issue. This pod starts and creates an empty directory `/etc/kube-flannel/net-conf.json` in the container.

```
apiVersion: v1
kind: Pod
metadata:
  name: volumetest
spec:
  containers:
  - name: container-test
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - mountPath: /etc/kube-flannel/net-conf.json
      name: flannel-net-conf
      subPath: net-conf.json

  volumes:
  - emptyDir: {}
    name: flannel-net-conf
```

`net-conf.json` is a directory because subPath `net-conf.json` does not exists in emptydir and it is assumed that's a directory. Do you have an init container that fills net-conf.json before the real container starts? Can you please start a new issue and post full pod spec that can reproduce the issue there so we can track it separately?
