### ISSUE TITLE
No error reported when PVC is missing.

### ISSUE THREAD

**Issue by cypherfox** [kubernetes/kubernetes#61174]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Createted a StatefullSet with a PVC that did not exist by calling `kubectl apply -f log-viewer.yaml` (given below), the declaration of the StatefulSet will be accepted, but the resultant pod will remain in the status `ContainerCreating` for ever.

```
kind: Service
apiVersion: v1
metadata:
  name: blocked-log-viewer
  labels:
    role: blocked-log-viewer
spec:
  type: ClusterIP
  selector:
    role: blocked-log-viewer
  ports:
    - name: www
      port: 80
    - name: ssh
      port: 22

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blocked-log-viewer
spec:
  serviceName: "blocked-log-viewer"
  selector:
    matchLabels:
      role: blocked-log-viewer
  template:
    metadata:
      labels:
        role: blocked-log-viewer
    spec:
      containers:
      - name: log-viewer
        image: hub.docker.com/nginx
        ports:
          - containerPort: 80
          - containerPort: 22
        env:
        volumeMounts:
          - name: log-space
            mountPath: /var/www/html
      volumes:
        - name: log-space
          persistentVolumeClaim:
            claimName: i-do-not-exist
```

**What you expected to happen**:
Either a) report that a PVC of the name given is not found when the StatefulSet is declared. Alternatively b) place an appropriate notification event into the pod when the attempt to mount the volume fails.

IMHO (a) would be better, as it fails faster and makes fault discovery easier.

**How to reproduce it (as minimally and precisely as possible)**:

apply resource description above to any namespace that does not have a PVC with the name `i-do-no-exist`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4+coreos.0", GitCommit:"5e73e0769e5c4ac497235e2817868b1a37032fba", GitTreeState:"clean", BuildDate:"2018-03-12T20:05:58Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
