### ISSUE TITLE
Admission control webhook with self-signed CA in "caBundle" is not trusted

### ISSUE THREAD

**Issue by johanot** [kubernetes/kubernetes#61171]
/kind bug

**What happened**:

I have compiled and deployed the test admission webhook here: https://github.com/kubernetes/kubernetes/tree/master/test/images/webhook
.. into my cluster.

I've added a ValidatingWebhookConfiguration to my cluster intercepting namespace creation, just for initial testing:

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission
webhooks:
- name: pod.admission.cloud
  rules:
  - apiGroups:
    - "*"
    apiVersions:
    - "*"
    operations:
    - "*"
    resources:
    - namespaces
  failurePolicy: Fail
  clientConfig:
    caBundle: MIIDSjCCAjKgAwIBAgIUWxmj40l+TDVJq98Xy7c6Leo3np8wDQYJKoZIhvcNAQELBQAwPTELMAkGA1UEBhMCeHgxCjAIBgNVBAgTAXgxCjAIBgNVBAcTAXgxCjAIBgNVBAoTAXgxCjAIBgNVBAsTAXgwHhcNMTgwMjAyMTIzODAwWhcNMjMwMjAxMTIzODAwWjA9MQswCQYDVQQGEwJ4eDEKMAgGA1UECBMBeDEKMAgGA1UEBxMBeDEKMAgGA1UEChMBeDEKMAgGA1UECxMBeDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANHkqOmVf23KMXdaZU2eFUx1h4wb09JINBB8x/HL7UE0KFJcnOoVnNQB0gRukUopiYCzrzMFyGWWmB/pAEKool+ZiI2uMy6mcYBDtOi4pOm7U0TQQMV6L/5Yfi65xRz3RTMd/tYAoFi4aCZbJAGjxU6UWNYDzTy8E/cP6ZnlNbVHRiA6/wHsoWcXtWTXYP5yn9cf7EWQi1hOBM4BWmOIyB1f6LEgQipZWMOMPPHO3hsuSBn0rk7jovSt5XTlbgRrtxqAJiNjJUykWzIF+lLnZCioippGv5vkdGvE83JoACXvZTUwzA+MLu49fkw3bweqkbhrer8kacjfGlw3aJN37eECAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFKXcb52bv6oqnD+D9fTNFHZL8IWxMA0GCSqGSIb3DQEBCwUAA4IBAQADvKvv3ym0XAYwKxPLLl3Lc6sJYHDbTN0donduG7PXeb1dhuukJ2lfufUYp2IGSAxuLecTYeeByOVp1gaMb5LsIGt2BVDmlMMkiH29LUHsvbyi85CpJo7A5RJG6AWW2VBCiDjz5v8JFM6pMkBRFfXH+pwIge65CE+MTSQcfb1/aIIoQ226P7E/3uUGX4k4pDXG/O7GNvykF40v1DB5y7DDBTQ4JWiJfyGkT69TmdOGLFAmjwxUjWyvEey4qJex/EGEm5RQcMv9iy7tba1wK7sykNGn5uDELGPGIIEAa5rIHm1FUFOZZVoELaasWS559wy8og39Eq21dDMynb8Bndn/
    service:
      name: admission
      namespace: default
```

When trying to create a namespace, admission-control fails with PKI-error (seen below), although the server cert is indeed signed with the certificate given in "caBundle":

> Mar 14 11:45:15 control-plane-p01 kube-apiserver[25281]: W0314 11:45:15.177435   25281 admission.go:257] Failed calling webhook, failing closed pod.admission.cloud: failed calling admission webhook "pod.admission.cloud": Post https://admission.default.svc:443/: x509: certificate signed by unknown authority

Admission webhook log:
> 2018/03/14 11:48:42 http: TLS handshake error from 172.20.32.11:33616: remote error: tls: bad certificate

**What you expected to happen**:
apiserver should see my x509-chain as valid.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a self-signed CA-certificate
* Create and server certificate and sign it with your own CA-cert
* Deploy https://github.com/kubernetes/kubernetes/tree/master/test/images/webhook with server cert
* Add the CA-cert to the clientConfig.caBundle of the ValidatingWebhookConfiguration
* Try requesting a change that triggers the admission controller

**Anything else we need to know?**:

Checking the cert chain with OpenSSL s_client works fine:

> openssl s_client -connect admission.default.svc:443 -CAfile ca.pem
> ...
> Verify return code: 0 (ok)

.. by the way.. Shouldn't I be able to add multiple certificates to the caBundle? If yes, how?

**Environment**:
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
> 
> Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

Self hosted. Kubernetes build from source on Nix 17.09.

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
> Linux container-p01 4.15.7 #1-NixOS SMP Wed Feb 28 09:21:39 UTC 2018 x86_64 GNU/Linux
- Install tools:
- Others:
> go version go1.9.2 linux/amd64
