### ISSUE TITLE
CreateContainerConfigError: Error: failed to prepare subPath for volumeMount when using an emptyDir and the subPath is a file

### ISSUE THREAD

**Issue by Joseph-Irving** [kubernetes/kubernetes#61178]
/kind bug

**Fix status:**
- [x] cleanup issue fixed in master in https://github.com/kubernetes/kubernetes/pull/58433, will be in 1.10.0-rc.1
- [x] cleanup issue fixed in release-1.9 branch in https://github.com/kubernetes/kubernetes/pull/61193, in [v1.9.5](https://github.com/kubernetes/kubernetes/releases/tag/v1.9.5)
- [x] cleanup issue fixed in release-1.8 branch in https://github.com/kubernetes/kubernetes/pull/61194, in [v1.8.10](https://github.com/kubernetes/kubernetes/releases/tag/v1.8.10)
- [x] cleanup issue fixed in release-1.7 branch in https://github.com/kubernetes/kubernetes/pull/61196, in [v1.7.15](https://github.com/kubernetes/kubernetes/releases/tag/v1.7.15)

**What happened**:
When I upgraded to 1.9.4 I noticed all my calico nodes were stuck in `CreateContainerConfigError` state. 

Describing the pods revealed this:
```
 Warning  Failed                 42s                kubelet, ip-172-23-12-44.eu-west-1.compute.internal  Error: failed to start container "kube-flannel": Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/var/lib/kubelet/pods/e8034482-2792-11e8-9748-0affda8a2e44/volume-subpaths/flannel-net-conf/kube-flannel/2\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/36167ba83c2a384d84bb046533fc00ea7f2ba1a21ce7bf6b297bc64f90645eb8/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/36167ba83c2a384d84bb046533fc00ea7f2ba1a21ce7bf6b297bc64f90645eb8/merged/etc/kube-flannel/net-conf.json\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
```
and
```
Warning  Failed                 41s                kubelet, ip-172-23-12-44.eu-west-1.compute.internal  Error: failed to prepare subPath for volumeMount "flannel-net-conf" of container "kube-flannel"
```
**What you expected to happen**:
The containers would be able to mount the subPath and start up
**How to reproduce it (as minimally and precisely as possible)**:
By creating a deployment where an init container creates a file in an emptydir and then the container tries to mount this file as a subpath will reproduce it.
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: subpath
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: subpath
    spec:
      initContainers:
        - name: init
          image: busybox
          command:
            - touch
            - /mount/test
          volumeMounts:
            - name: mount
              mountPath: /mount
      containers:
      - name: subtest
        image: busybox
        command:
          - ls
          - -l
          - /mount/test
        volumeMounts:
          - name: mount
            mountPath: /mount/test
            subPath: test
      volumes:
      - name: mount
        emptyDir: {}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4+coreos.1", GitCommit:"40e53b58ddba86824d91a268bcba1c7cfc619d9d", GitTreeState:"clean", BuildDate:"2018-03-13T22:34:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.2.1
VERSION_ID=1632.2.1
BUILD_ID=2018-02-01-2053
PRETTY_NAME="Container Linux by CoreOS 1632.2.1 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-172-23-10-171 4.14.16-coreos #1 SMP Thu Feb 1 20:38:35 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools:
- Others:

**Comment by liggitt** [comment]
what version of docker and storage driver are you using as well?

**Comment by jsafrane** [comment]
It must be related to coreos or overlay2 in some way. Exactly the same pod works well on CentOS 7.4 (with docker 1.12.6 + device mapper)

**Comment by carlosedp** [comment]
Same error here but I'm not using EmptyDir, mounting the ConfigMap directly to a subpath:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:21:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/arm64"}
```

```
 docker version
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:12:26 2018
 OS/Arch:       linux/arm64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:10:35 2018
  OS/Arch:      linux/arm64
  Experimental: false
```
My ConfigMap:
```
cat grafana-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  config.ini: |
    [database]
    path = /data/grafana.db

    [paths]
    data = /data
    logs = /data/log
    plugins = /data/plugins
.....
```
Deployment:


```
....
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      - name: grafana
        image: carlosedp/monitoring-grafana:latest
        volumeMounts:
        - name: grafana-config
          mountPath: /grafana/conf/config.ini
          subPath: config.ini
....
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-config

```

Worked fine in 1.9.3.

**Comment by liggitt** [comment]
@carlosedp the configmap+subpath issue is different, tracked in https://github.com/kubernetes/kubernetes/issues/61076 with a known fix scheduled for 1.9.5

**Comment by carlosedp** [comment]
Oh, thanks.. and sorry about the noise.

**Comment by jsafrane** [comment]
I switched to overlay, still works. I am installing coreos.

**Comment by jsafrane** [comment]
Reproduced on coreos 1702.1.0 and today's release-1.9 HEAD:

```
I0314 17:26:19.969333   11325 kubelet_pods.go:175] container: default/voltest/subtest podIP: "172.18.0.2" creating hosts mount: true
I0314 17:26:19.969548   11325 mount_linux.go:692] doBindSubPath "/var/lib/kubelet/pods/c4f95a3f-27ac-11e8-b9db-08002745c782/volumes/kubernetes.io~empty-dir/mount/test", full subpath "/var/lib/kubelet/pods/c4f95a3f-27ac-11e8-b9db-08002745c
782/volumes/kubernetes.io~empty-dir/mount/test" for volumepath "/var/lib/kubelet/pods/c4f95a3f-27ac-11e8-b9db-08002745c782/volumes/kubernetes.io~empty-dir/mount"
I0314 17:26:19.969638   11325 mount_linux.go:712] doBindSubPath() failed for "/var/lib/kubelet/pods/c4f95a3f-27ac-11e8-b9db-08002745c782/volume-subpaths/mount/subtest/0", cleaning up subpath
I0314 17:26:19.969660   11325 mount_linux.go:834] Cleaning up subpath mounts for subpath 0
E0314 17:26:19.969692   11325 mount_linux.go:714] Failed to clean subpath "/var/lib/kubelet/pods/c4f95a3f-27ac-11e8-b9db-08002745c782/volume-subpaths/mount/subtest/0": error checking /var/lib/kubelet/pods/c4f95a3f-27ac-11e8-b9db-08002745c782/volume-subpaths/mount/subtest/0 for mount: lstat /var/lib/kubelet/pods/c4f95a3f-27ac-11e8-b9db-08002745c782/volume-subpaths/mount/subtest/0/..: not a directory
E0314 17:26:19.969716   11325 kubelet_pods.go:248] failed to prepare subPath for volumeMount "mount" of container "subtest": error checking path /var/lib/kubelet/pods/c4f95a3f-27ac-11e8-b9db-08002745c782/volume-subpaths/mount/subtest/0 for mount: lstat /var/lib/kubelet/pods/c4f95a3f-27ac-11e8-b9db-08002745c782/volume-subpaths/mount/subtest/0/..: not a directory
E0314 17:26:19.969777   11325 kuberuntime_manager.go:734] container start failed: CreateContainerConfigError: failed to prepare subPath for volumeMount "mount" of container "subtest"
E0314 17:26:19.969881   11325 pod_workers.go:186] Error syncing pod c4f95a3f-27ac-11e8-b9db-08002745c782 ("voltest_default(c4f95a3f-27ac-11e8-b9db-08002745c782)"), skipping: failed to "StartContainer" for "subtest" with CreateContainerConfigError: "failed to prepare subPath for volumeMount \"mount\" of container \"subtest\""
I0314 17:26:19.969936   11325 server.go:231] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"voltest", UID:"c4f95a3f-27ac-11e8-b9db-08002745c782", APIVersion:"v1", ResourceVersion:"255", FieldPath:"spec.containers{subtest}"}): type: 'Warning' reason: 'Failed' Error: failed to prepare subPath for volumeMount "mount" of container "subtest"
```


Interesting is that the pod flips between "Completed" and "CrashLoopBackOff".

**Comment by jsafrane** [comment]
I did **not** reproduce it, the container is in CrashLoopBackOff because it finished successfully and its restart policy keeps restarting it and gives up eventually. I did **not** see

```
starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/var/lib/kubelet/pods/e8034482-2792-11e8-9748-0affda8a2e44/volume-subpaths/flannel-net-conf/kube-flannel/2\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/36167ba83c2a384d84bb046533fc00ea7f2ba1a21ce7bf6b297bc64f90645eb8/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/36167ba83c2a384d84bb046533fc00ea7f2ba1a21ce7bf6b297bc64f90645eb8/merged/etc/kube-flannel/net-conf.json\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n
```

**Comment by Joseph-Irving** [comment]
@jsafrane sorry if my initial report was a bit misleading. the whole `container init caused \\\"rootfs_linux.go:53: mounting ` part I did not reproduce with that example deployment. That just reproduced the `container start failed: CreateContainerConfigError: failed to prepare subPath for volumeMount "mount" of container "subtest"`.

**Comment by jsafrane** [comment]
I finally reproduced this error:

```
Warning  Failed                 41s                kubelet, ip-172-23-12-44.eu-west-1.compute.internal  Error: failed to prepare subPath for volumeMount "flannel-net-conf" of container "kube-flannel"
```

Just run the deployment in 1.9.4 (not master!) and wait enough for the container to be restarted several times, the error will eventually show up. It's because one of the cleanup fails, leaving the bind-mounted test file there. Following Setup will check if the directory is mounted and `IsLikelyNotMountPoint` will fail too, because it does `lstat("/var/lib/kubelet/pods/c4f95a3f-27ac-11e8-b9db-08002745c782/volume-subpaths/mount/subtest/0/..") where "subtest/0" is not a directory, it's bind-mounted test file.

We need to pick https://github.com/kubernetes/kubernetes/pull/58433 into 1.9 - both cleanup and doBindSubPath indirectly use `IsLikelyNotMountPoint` to check for existing mount and `IsLikelyNotMountPoint` must therefore work with bind-mounted files.


I still have no clue what `starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting ` means.

We did not notice this error in e2e tests because we did not check for cleanup success (or other errors in logs) in 1.9 and master has `IsLikelyNotMountPoint` already fixed.

**Comment by msau42** [comment]
@jsafrane, do you know why the subpath cleanup failed? Did it succeed many times before failing?

**Comment by msau42** [comment]
cc @tallclair

**Comment by jsafrane** [comment]
>  do you know why the subpath cleanup failed

Because cleanup does `lstat(file + "../")` when file is really a file.

**Comment by liggitt** [comment]
- [x] cleanup issue fixed in master in https://github.com/kubernetes/kubernetes/pull/58433, will be in 1.10.0-rc.1
- [x] cleanup issue fixed in release-1.9 branch in https://github.com/kubernetes/kubernetes/pull/61193, in [v1.9.5](https://github.com/kubernetes/kubernetes/releases/tag/v1.9.5)
- [x] cleanup issue fixed in release-1.8 branch in https://github.com/kubernetes/kubernetes/pull/61194, in [v1.8.10](https://github.com/kubernetes/kubernetes/releases/tag/v1.8.10)
- [x] cleanup issue fixed in release-1.7 branch in https://github.com/kubernetes/kubernetes/pull/61196, in [v1.7.15](https://github.com/kubernetes/kubernetes/releases/tag/v1.7.15)

/close

**Comment by Joseph-Irving** [comment]
@jsafrane Thanks this fixed the unable to create subPath error, I've now managed to reproduce the `starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53` part. 

So it seems to be related to the fact I've mounted a configmap as directory and then I've added the file from the emptydir as a subpath to the same directory.

e.g:
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: subpath
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: subpath
    spec:
      initContainers:
        - name: init
          image: busybox
          command:
            - touch
            - /mount/test
          volumeMounts:
            - name: mount
              mountPath: /mount
      containers:
      - name: subtest
        image: busybox
        command:
          - ls
          - -l
          - /mount/test
        volumeMounts:
          - name: mount
            mountPath: /mount/test
            subPath: test
          - name: config
            mountPath: /mount
      volumes:
      - name: mount
        emptyDir: {}
      - name: config
        configMap:
          name: mount
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mount
  namespace: kube-system
data:
  hello.txt: |
    hello
```
```
Error: failed to start container "subtest": Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/var/lib/kubelet/pods/3388d7bb-2db3-11e8-9508-02209aaf5ea8/volume-subpaths/mount/subtest/0\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/6ee7d34a4f5415e77c0ba2b33a6d263791a9acba7d18989b90b5998f27ee77c2/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/6ee7d34a4f5415e77c0ba2b33a6d263791a9acba7d18989b90b5998f27ee77c2/merged/mount/test\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
```
