### ISSUE TITLE
link volume from existing container to another container in a pod

### ISSUE THREAD

**Issue by oba11** [kubernetes/kubernetes#6120]
I have 2 containers in a pod.
I have some files in `container a` that needs to be accessed by `container b`
I'm not sure how I can achieve this.

```
containers:
  - name: conatainer-a
    volumeMounts:
      - name: www-data
        mountPath: /data
  - name: conatainer-b
    volumeMounts:
      - name: www-data
        mountPath: /data/shared
        readOnly: true
volumes:
  - name: www-data
```

The contents of `/data` in `container a` becomes empty which has the content to be shared.
