### ISSUE TITLE
[pvresize]Display of pvc capacity did not make corresponding changes when pv resized

### ISSUE THREAD

**Issue by taoyu27** [kubernetes/kubernetes#61259]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
Display of pvc capacity did not make corresponding changes when pv resized

**What you expected to happen**:
display of pvc capacity did make corresponding changes when pv resized

**How to reproduce it (as minimally and precisely as possible)**:
1. create pvc, request storage: 1Gi
```
apiVersion: v1
metadata:
  name: helloworld-claim-demo
  annotations:
    volume.beta.kubernetes.io/storage-class: "rbd-demo"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd-demo
  resources:
    requests:
      storage: 1Gi

kubectl get pvc
NAME                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
helloworld-claim-demo   Bound     pvc-0da06c71-2832-11e8-8857-fa163e4e23c0   1Gi        RWO            rbd-demo       18h
```
2. kubectl edit pvc, make request storage 4Gi
```
update pvc.yaml file
apiVersion: v1
metadata:
  name: helloworld-claim-demo
  annotations:
    volume.beta.kubernetes.io/storage-class: "rbd-demo"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd-demo
  resources:
    requests:
      storage: 4Gi


kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                           STORAGECLASS   REASON    AGE
pvc-0da06c71-2832-11e8-8857-fa163e4e23c0   4Gi        RWO            Delete           Bound     default/helloworld-claim-demo   rbd-demo                 18h
```

3. check the display of pvc capacity
```
kubectl get pvc
NAME                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
helloworld-claim-demo   Bound     pvc-0da06c71-2832-11e8-8857-fa163e4e23c0   1Gi       RWO            rbd-demo       18h
```

the display of pvc capacity is still 1Gi...

**Environment**:
- Kubernetes version (use `kubectl version`): 
  1.10 bata 4
- OS (e.g. from /etc/os-release): 
  centos 7.2
- Kernel (e.g. `uname -a`):
  3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- Others:
