### ISSUE TITLE
nginx permission denied when updated kubernetes version 1.8.7-gke.0 to 1.9.4-gke.1

### ISSUE THREAD

**Issue by hiratamasato** [kubernetes/kubernetes#61335]
/kind bug

**What happened**:
I updated kubernetes version 1.8.7-gke.0 -> 1.9.4-gke.1 then simple nginx application errored.
this application on 1.8.7-gke.0 had worked.
I cannot understand whether or not this is bug.

my dockerfile
```
FROM nginx
ADD ./server.conf /etc/nginx/conf.d/default.conf
ADD ./public /root/public
RUN mkdir /root/logs
RUN chmod 755 -R /root
CMD ["nginx", "-g", "daemon off;"]
```

and nginx error log. all pages returned 403.
```
10.36.1.1 - - [19/Mar/2018:06:46:33 +0000] "HEAD /css/grayscale.css HTTP/1.1" 403 0 "-" "curl/7.35.0"
2018/03/19 06:46:33 [error] 5#5: *7 open() "/root/public/css/grayscale.css" failed (13: Permission denied), client: 10.36.1.1, server: localhost, request: "HEAD /css/grayscale.css HTTP/1.1", host: "35.189.152.153"
2018/03/19 06:46:33 [info] 5#5: *7 client 10.36.1.1 closed keepalive connection
```

But once I touch public directory with like below command, I can access those files via blowser.
```
kubectl exec [pod's name] -n [namespace] -- ls -la /root/public
```
this is caused by selinux?

**Anything else we need to know?**:
I can see below nginx logs when I access my page.
I concerned about status 304(not modified)...

```
10.36.1.1 - - [19/Mar/2018:07:35:44 +0000] "GET / HTTP/1.1" 200 46344 "http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
10.36.1.1 - - [19/Mar/2018:07:35:44 +0000] "GET /css/bootstrap.min.css HTTP/1.1" 304 0 "http://35.189.152.153/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36"
```

**Environment**:
- Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.4-gke.1", GitCommit:"10e47a740d0036a4964280bd663c8500da58e3aa", GitTreeState:"clean", BuildDate:"2018-03-13T18:00:36Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
Do you have the pod spec used to launch this pod?

**Comment by hiratamasato** [comment]
Thank you for reply.
my pods deployment and service .yaml is here.
```
apiVersion: v1
kind: Service
metadata:
  name: frontpage
  namespace: [namespace]
  labels:
    app: frontpage
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: frontpage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontpage
  namespace: [namespace]
spec:
  replicas: 1
  # Deployment ammount of history to keep
  revisionHistoryLimit: 3
  template:
    metadata:
      namespace: [namespace]
      labels:
        app: frontpage
        version: latest
    spec:
      containers:
      - name: frontpage
        image: [ image ]
        ports:
        - containerPort: 3000
```
my application have worked with one pod, and allocated memory to this pod is 2.598Mi.
Is amount of memory too low?
