### ISSUE TITLE
container lifecycle  postStart and preStop hooks https schema does not take effect

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes/kubernetes#61336]
If we define a pod like this below, the pod will never become ready. 
```
apiVersion: v1
kind: Pod
metadata:
  name: test-lifecycle
spec:
  containers:
    - name: test-lifecycle
      image: nginx
      lifecycle:
        postStart:
          httpGet:
            command:
              path: "pods"
              port: 10250
              host: 127.0.0.1
              scheme: https
```

kubectl describe pod got this event 
```
Warning  FailedPostStartHook    2m (x4 over 3m)  kubelet, 127.0.0.1  Http lifecycle hook (pods) for Container "test-lifecycle" in Pod "test-lifecycle_default(fdd42c35-2b4c-11e8-b8c0-286ed488d02a)" failed - error: Get http://127.0.0.1:10250/pods: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02", message: ""
```
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
