### ISSUE TITLE
New requirement to set default pod container

### ISSUE THREAD

**Issue by zhangtbj** [kubernetes/kubernetes#61333]
**Is this a BUG REPORT or FEATURE REQUEST?**:
New FEATURE REQUEST

> Uncomment only one, leave it on its own line: 
> /kind feature

**What happened**:
Right now, when we configure multiple containers in one pod, the first container will be the default container of this pod. when we execute `kubectl exec -it <pod name>` kube will enter the first default pod.

**What you expected to happen**:
But for some reason, we have to patch the pod to add some additional sidecar container, but the sidecar container will replace and be at the top of container tab of pod, so it will become the default container.

**How to reproduce it (as minimally and precisely as possible)**:
In any multiple containers pod.

**Anything else we need to know?**:
We would like to know, if there is a new feature can set the default container of pod explicitly instead of configure by the first one in container tab of pod, then we can have better control of the container.
like below: `default-container: nginx-container2`
```
spec:
  template:
    spec:
      default-container: nginx-container2
      containers:
      - name: nginx-container
        image: nginx
        volumeMounts:
        - name: shared-data
           mountPath: /usr/share/nginx/html
      - name: nginx-container2
        image: nginx
        volumeMounts:
        - name: shared-data
           mountPath: /usr/share/nginx2/html
```

Thanks!
