### ISSUE TITLE
Scheduling Policy on ConfigMap breaks without the --policy-configmap-namespace flag set

### ISSUE THREAD

**Issue by waldman** [kubernetes/kubernetes#61368]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
When trying to use the Scheduler Policy on a ConfigMap the `kube-scheduler` will not work giving the following error message:
```
F0319 19:21:47.831522       1 helpers.go:119] error: couldn't get policy config map /scheduler-policy: an empty namespace may not be set when a resource name is provided
```

As per the documentation (https://kubernetes.io/docs/reference/generated/kube-scheduler/) `kube-scheduler` should work without the need to a namespace being passed:
```
      --policy-configmap-namespace string        The namespace where policy ConfigMap is located. The system namespace will be used if this is not provided or is empty.
```

Here is the command that I'm using to start the scheduler:
```
  - command:
    - /bin/sh
    - -c
    - mkfifo /tmp/pipe; (tee -a /var/log/kube-scheduler.log < /tmp/pipe & ) ; exec
      /usr/local/bin/kube-scheduler --kubeconfig=/var/lib/kube-scheduler/kubeconfig
      --leader-elect=true --policy-configmap=scheduler-policy --v=2 > /tmp/pipe 2>&1
    image: gcr.io/google_containers/kube-scheduler:v1.9.3
```

And here is the ConfigMap that I had on this cluster:
```
Name:         scheduler-policy
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Data
====
policy:
----
kind: Policy
apiVersion: v1
predicates:
- name: MatchInterPodAffinity
- name: NoDiskConflict
- name: CheckNodeDiskPressure
- name: MaxEBSVolumeCount
- name: MaxGCEPDVolumeCount
- name: GeneralPredicates
- name: PodToleratesNodeTaints
- name: CheckNodeMemoryPressure
- name: NoVolumeZoneConflict
priorities:
- name: BalancedResourceAllocation
  weight: 1
- name: NodePreferAvoidPodsPriority
  weight: 1
- name: NodeAffinityPriority
  weight: 1
- name: TaintTolerationPriority
  weight: 1
- name: SelectorSpreadPriority
  weight: 10
- name: InterPodAffinityPriority
  weight: 1
- name: LeastRequestedPriority
  weight: 1
- name: ServiceSpreadingPriority
  weight: 4
```

Speaking on the #sig-scheduling slack channel I was informed that on 1.9 the namespace flag become mandatory making this Issue a simple documentation fix.

**What you expected to happen**:
I was expecting that the `kube-scheduler` was to check for the config map into the `kube-system` namespace by default if the flag `--policy-configmap-namespace` wasn't specified.

**How to reproduce it (as minimally and precisely as possible)**:
Create the config map and set the flag `--policy-configmap` accordingly without setting the `--policy-configmap-namespace` flag.

**Anything else we need to know?**:
You guys rocks! o/

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): Linux ip-10-250-1-201 4.4.115-k8s #1 SMP Thu Feb 8 15:37:40 UTC 2018 x86_64 GNU/Linux
- Install tools: Kops
- Others:
