### ISSUE TITLE
PSP： How to combine authenticated users with PSP users (non-service accounts) in deployments or daemonsets

### ISSUE THREAD

**Issue by AnberLu** [kubernetes/kubernetes#61399]
### How to combine authenticated users with PSP users in deployments or daemonsets

```
1）In my cluster, the client user is an RBAC authenticated user, and the user is also bound to the PSP.

2）When I create a pod, it works  fine

3) But when I create a deployments, it prompts me to create failure!
```

### problem:
```
1)  In PSP mode, do we must specify the service account in deployment ? can we  using User  in deployment? if we must use  service account ,What is the user's function? Just do authentication and authorization at the beginning?

2) In Kubernetes, how do we achieve continuous correspondence between User and service account in authentication and authorization (including psp authorization)?

3) In the future, will kubernetes weaken the notion of User and strengthen the concept of ServiceAccount?

```

### My file:

pod
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.10.0
    ports:
    - containerPort: 80
```

deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.10.0
        ports:
        - containerPort: 80
```
the deployment result:
```
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment   2         0         0            0           1h
```
