### ISSUE TITLE
hostPath volumes used with subPath volume mounts don't support reconstruction

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#61446]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
Normally this isn't a problem, but if you use subpath with hostpath volumes, then that means the subpath mounts will not get cleaned up during the reconstruction window (a pod is force deleted while kubelet is down)

**Comment by msau42** [comment]
Noticed this issue while working on https://github.com/kubernetes/kubernetes/pull/61373

**Comment by liggitt** [comment]
How is this different than https://github.com/kubernetes/kubernetes/issues/61372?

**Comment by msau42** [comment]
#61372 affects reconstruction for PVCs

**Comment by msau42** [comment]
/remove-lifecycle stale

We intend to address this by redesigning the volume reconstruction feature to use kubelet checkpointing.

**Comment by neujie** [comment]
Better practice:   
* kill or delete pod   
* clear the pod's all `subpath`   
**otherwise a lot of useless dir will be left**

**Comment by dobsonj** [comment]
The in-tree hostPath driver makes no attempt to unmount:
https://github.com/kubernetes/kubernetes/blob/6c96ac04ff970809d815c871958be702d3065db1/pkg/volume/hostpath/host_path.go#L266-L274
Once that is fixed, these skips need to be removed:
https://github.com/kubernetes/kubernetes/blob/6c96ac04ff970809d815c871958be702d3065db1/test/e2e/storage/testsuites/subpath.go#L347-L350
https://github.com/kubernetes/kubernetes/blob/6c96ac04ff970809d815c871958be702d3065db1/test/e2e/storage/testsuites/subpath.go#L359-L362

**Comment by dobsonj** [comment]
> The in-tree hostPath driver makes no attempt to unmount

So it's not really the TearDown code I quoted above, the subpaths would normally be cleaned up here:
https://github.com/kubernetes/kubernetes/blob/2e55595d3baeedcab09745355824f38a60cf6d08/pkg/volume/util/operationexecutor/operation_generator.go#L825-L830

But we never make any attempt to call UnmountVolume in this scenario.
https://github.com/kubernetes/kubernetes/blob/2e55595d3baeedcab09745355824f38a60cf6d08/pkg/kubelet/volumemanager/reconciler/reconciler.go#L185-L187

`unmountVolumes` loops over `rc.actualStateOfWorld.GetAllMountedVolumes()`, but if we're just using a hostPath (type = Directory), there won't be a mount point, and it won't be listed as a mounted volume. But the subpaths still use bind mounts, and those never get unmounted.

For future reference it can be reproduced manually with:
```
kind: Pod
apiVersion: v1
metadata:
  name: my-intree-inline-app
spec:
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-inline-vol
      - mountPath: "/data/subpath1"
        name: my-inline-vol
        subPath: subpath1
      - mountPath: "/data/subpath2"
        name: my-inline-vol
        subPath: subpath2
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-inline-vol
      hostPath:
        path: /tmp/dir1
        type: Directory
```
1) create pod with spec above, check mountpoints
2) kill kubelet
3) force delete pod
4) start kubelet again
5) check mount points and kubelet.log
