### ISSUE TITLE
Container Can not Run: oci runtime error: container_linux.go: not a directory. When mounting Configmaps and a subpath in the same directory

### ISSUE THREAD

**Issue by Joseph-Irving** [kubernetes/kubernetes#61545]
/kind bug

**What happened**:
After upgrading to 1.94 (now on 1.9.6) I could not run my flannel container

The error is 
```
invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/var/lib/kubelet/pods/d1d414bd-2db0-11e8-a1f1-024f81364208/volume-subpaths/flannel-net-conf/kube-flannel/2\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/9a9befa0846d036e5da22e8bb9eaca6ce313aed97671629a96dc79323df4127c/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/9a9befa0846d036e5da22e8bb9eaca6ce313aed97671629a96dc79323df4127c/merged/etc/kube-flannel/net-conf.json\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
```

**What you expected to happen**:
The container would be created and run
**How to reproduce it (as minimally and precisely as possible)**:
Using this deployment I could reproduce it, the important part being that I'm mounting the configmap as directory and then mounting a file from the emptyDir as a SubPath in the same directory.
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: subpath
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: subpath
    spec:
      initContainers:
        - name: init
          image: busybox
          command:
            - touch
            - /mount/test
          volumeMounts:
            - name: mount
              mountPath: /mount
      containers:
      - name: subtest
        image: busybox
        command:
          - sleep
          - "300"
        volumeMounts:
          - name: mount
            mountPath: /mount/test
            subPath: test
          - name: config
            mountPath: /mount
      volumes:
      - name: mount
        emptyDir: {}
      - name: config
        configMap:
          name: mount
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mount
  namespace: kube-system
data:
  hello.txt: |
    hello
```
**Anything else we need to know?**:

**Environment**::
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6+coreos.0", GitCommit:"c2aac694c2c7373dfe3ad81f47fc3cbc70a5a8fa", GitTreeState:"clean", BuildDate:"2018-03-21T21:54:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.2.1
VERSION_ID=1632.2.1
BUILD_ID=2018-02-01-2053
PRETTY_NAME="Container Linux by CoreOS 1632.2.1 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-172-23-10-171 4.14.16-coreos #1 SMP Thu Feb 1 20:38:35 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools:
- Others:
Docker:
```
docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   d9ad3fc
 Built:        Thu Feb  1 20:40:03 2018
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.7.6
 Git commit:   d9ad3fc
 Built:        Thu Feb  1 20:40:03 2018
 OS/Arch:      linux/amd64
```
Storage driver is overlay2
