### ISSUE TITLE
apiserver returns 500 when it cannot query DNS

### ISSUE THREAD

**Issue by phsiao** [kubernetes/kubernetes#61558]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

We did a schedule maintenance of our DNS resolvers used by apiserver, and apiserver becomes not healthy and get killed by health check.

```
18m         55m          32        kube-apiserver-6vbybx1.151e516520b95ea7                     Pod         spec.containers{kube-apiserver}            Warning   Unhealthy               kubelet, 6vbybx1     Liveness probe failed: HTTP probe failed with statuscode: 500
```

with this liveness probe

```
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 443
        scheme: HTTPS
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
```

**What you expected to happen**:

apiserver remains healthy while DNS server is not available.  We actually have two resolvers in resolv.conf with these options

```
options ndots:15 timeout:1 attempts:5
```

and that still leads to this undesirable outcome.

**How to reproduce it (as minimally and precisely as possible)**:

Just observed this, have not tried to reproduce this yet.  I assume doing an iptables drop can reproduce this and will confirm that.

**Anything else we need to know?**:

N/A

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.6
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release):  CentOS Linux release 7.4.1708 (Core) 
- Kernel (e.g. `uname -a`): 4.14.15-1.el7.elrepo.x86_64
- Install tools: custom
- Others:
