### ISSUE TITLE
EncryptionConfig: use standard method for parsing config file

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#61599]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig auth

**What happened**:
Currently encryption config parsing uses a non-standard parsing method that pays no attention to the version of the config:

https://github.com/kubernetes/kubernetes/blob/dce1b881284a103909f5cfa969ff56e5e0565362/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go#L67-L79

**What you expected to happen**:
- the types must change to use standard methods for including kind/apiVersion (inlining metav1.TypeMeta like all other objects)
- define a versioned config (we can promote straight to v1beta1 if we don't require any structural changes)
- parsing must require well-formed config files

**Anything else we need to know?**:
Requested by @liggitt and extracted from https://github.com/kubernetes/kubernetes/pull/61592#issuecomment-375655819

Steps to be done:
- [ ] fix type definition to actually be a runtime object, inline TypeMeta, etc
- [ ] define v1beta1 API types, generate conversions/defaults
- [ ] define scheme/codecs that have the external (v1beta1) and internal (existing) types registered
- [ ] use that scheme/codec to load the config (handles decoding the v1beta1 version, conversion to internal version)

CC @marrrvin

**Comment by php-coder** [comment]
@kubernetes/sig-auth-feature-requests 

> define v1beta1 API types, generate conversions/defaults

That's not so clear to me.. API types should belong to some API Group, correct? What API group should we use for that config?

Right now the config is:
```yaml
apiVersion: v1
kind: EncryptionConfig
resources:
  - resources:
	- secrets
	providers:
	- identity: {}
```
How it will look like after this change?
```yaml
apiVersion: apiserver.config.k8s.io/v1beta1
kind: EncryptionConfiguration
resources:
  - resources:
	- secrets
	providers:
	- identity: {}
```
