### ISSUE TITLE
Enhance validation for "ExternalName" type Service

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#61623]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement
/sig network

**What happened**:
According to the definition of ["ExternalName" type Service](https://kubernetes.io/docs/concepts/services-networking/service/#without-selectors), it should not have selectors. But currently in k8s, users are able to create an "ExternalName" type Service with selectors, which is confusing as the selectors in fact have no effect (no endpoint will be created).

It would be clearer to users if we reject creating an "ExternalName" type Service with selectors.

**How to reproduce it (as minimally and precisely as possible)**:
Try this yaml:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-cname
spec:
  selector:
    app: my-app
  type: ExternalName
  externalName: www.example.com
```
