### ISSUE TITLE
 kubectl auth reconcile output is too long

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#61703]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The object output is far beyond human-readable in `kubectl auth reconcile` command.
For example:
1. Create a role by xiaomi-role.yaml
xiaomi-role.yaml:
```
  kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: xiaomi
  rules:
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
```
2. Here's another yaml file xiaomi-modify,yaml
```
  kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: xiaomi
  rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "replicasets", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
```
3. execute `kubectl auth reconcile -f xiaomi-modify.yaml --output=yaml
`
Output of this command is 600+ lines, which is obvious too long to use.

**What you expected to happen**:
Squash the output
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
