### ISSUE TITLE
readOnly field does not work in  FlexVolume  PV

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#61758]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Below `readOnly` field in flexvolume never works in all k8s versions, the actual `readOnly` will always be `false` even user set `flexVolume.readOnly` as `true`

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dysk-flexvol
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/dysk"
    readOnly: false
    fsType: ext4
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7-v1.11
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign
/sig storage

**Comment by mlmhl** [comment]
It seems that this is not a special case for FlexVolume, other volume plugins also ignore `PersistentVolume.Spec.<PersistentVolumeSource>.ReadOnly`.

At present, we allow two approaches to set PVC's `ReadOnly` attribute: specified by `Pod.Spec.Volumes.PersistentVolumeClaim.ReadOnly`, or specified by `PersistentVolume.Spec.<PersistentVolumeSource>.ReadOnly`, but when we try to get the `ReadOnly` attribute from `volume.Spec` for a PVC volume, we only consider `volume.Spec.ReadOnly`, which only comes from `Pod.Spec.Volumes.PersistentVolumeClaim.ReadOnly`, see [AWS](https://github.com/kubernetes/kubernetes/blob/76ffe9e832710383d4f94723eb8b95dbb2ebb407/pkg/volume/aws_ebs/aws_ebs.go#L193) as an example.

Need we to fix this issue for all volume plugins? Or we just allow one approach(specified by `Pod.Spec.Volumes.PersistentVolumeClaim.ReadOnly`) to make things simple?

cc @saad-ali

**Comment by andyzhangx** [comment]
@mlmhl thanks, according to your comments, I have figured out the working way to set readOnly as true could only be in pod, like following config:
```
piVersion: v1
kind: Pod
metadata:
  name: nginx-flex-dysk-pvc
spec:
  containers:
  - name: nginx-flex-dysk
    image: nginx
    volumeMounts:
    - name: flexvol-mount
      mountPath: /data
  volumes:
  - name: flexvol-mount
    persistentVolumeClaim:
      claimName: pvc-dysk-flexvol
      readOnly: true
```

It's a little tricky even I have already set readOnly in PV, it does not work
