### ISSUE TITLE
Allow nobrl parameter like docker to use sqlite over network drive

### ISSUE THREAD

**Issue by athertahir** [kubernetes/kubernetes#61767]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
 **kind feature**

**What happened**:
I want to use sqlite with azure file as a persistent volume. But when I try to do write operations I get "database is locked"

**What you expected to happen**:
I got the same issue using azure file with sqlite on my local VM but when I passed **nobrl** parameter while mounting it then it worked fine. Docker also allows to pass nobrl paramter.
https://github.com/docker/for-win/issues/11
https://linux.die.net/man/8/mount.cifs

**How to reproduce it (as minimally and precisely as possible)**:
Try to do write operations on a sqlite file using azure file as a persistent volume.

**Environment**:
- Kubernetes version :  v1.7.9
- Cloud provider or hardware configuration: AKS
- Kernel : 4.13.0-1007-azure
- Others: Azure FIle

**Comment by andyzhangx** [comment]
@athertahir you could use azure file mountOptions, here is the guide:
https://github.com/andyzhangx/demo/blob/master/linux/azurefile/azurefile-mountoptions.md

**Comment by andyzhangx** [comment]
@athertahir BTW, azure file mountOptions feature is supported from v1.8.5

**Comment by andyzhangx** [comment]
close this issue since `nobrl` parameter could be set in azure file mountOptions, let me know if you have any question
/close

**Comment by LucaPrete** [comment]
Guys, @andyzhangx I'm still struggling with the lock issue.

FYI I've the Azurefile SC declared as following:

```
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-standard
reclaimPolicy: Retain
provisioner: kubernetes.io/azure-file
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS
  kind: Managed
```

But still, sqlite returns the same lock error mentioned above. I'm running on AKS and using k8s 1.14.8.

I've also proof that with azure disks everything works, but this is a pain for rolling updates....

Do you have any suggestion?

Thanks!
