### ISSUE TITLE
Containerized kubelet won't start pods with host path volumes that contains type field

### ISSUE THREAD

**Issue by danlenar** [kubernetes/kubernetes#61801]
<!-- This form is for bug reports and feature requests ONLY! 

If you're looking for help check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) and the [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/).
-->

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug


**What happened**:

Containerized kubelet running with the containerized flag can't start any pods with host path volumes that contains the type field such as DirectoryOrCreate

```
volumes:
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: ca-certs-etc-pki
```

Stracing the kubelet revealed that stat from nsenter_mount.go returned unrecognized option

Actual:
```
stat -L "--printf \"%F\"" /etc/kubernetes/pki
stat: unrecognized option '--printf "%F"'
Try 'stat --help' for more information.
```
Expected:
```
stat -L --printf=%F /etc/kubernetes/pki                                                                                                                                                                                                                                                                                         
directory
```

**Environment**:
- Kubernetes version: 1.10.0
- Bare-metal
- CentOS Linux release 7.4.1708 (Core)
- 3.10.0-693.17.1.el7.x86_64
