### ISSUE TITLE
[1.10] kube-apiserver/kubelet dynamicConfigDir

### ISSUE THREAD

**Issue by gfrntz** [kubernetes/kubernetes#61993]
/kind bug

**What you expected to happen**:
DynamicConfigDir can't work in k8s 1.10 kube-apiserver without enabled ```--feature-gate =DynamicKubeletConfig=true```. But now this feature doesnt alpha and will be enable by default. Whats wrong?

**How to reproduce it**:
* Install kubernetes 1.10.0.
* Run kube-apiserver without ```--feature-gate =DynamicKubeletConfig=true```
* kubectl node edit `some_node` and add 
```
  configSource:
    configMapRef:
      name: kubelet-config-d676c6m8t2
      namespace: kube-system
      uid: e31ac41f-34e4-11e8-9296-fa163ead82df
```
After you close redactor this parameter gone away. 

**Bug with kubelet**
Run command:
```/usr/local/bin/kubelet --dynamic-config-dir=/etc/kubernetes/dynamic-kubelet-config --config=/etc/kubernetes/init-kubelet-config/kubelet.yaml --bootstrap-kubeconfig=/etc/kubernetes/kubeconfig-bootstrap.yaml --cert-dir=/etc/kubernetes/ssl --kubeconfig=/etc/kubernetes/kubelet.yaml```

Only works after this patch https://github.com/kubernetes/kubernetes/pull/61992

**How to reproduce it**:
* run kubelet 1.10.0
* add --dynamic-config-dir=/etc/kubernetes/dynamic-kubelet-config
* you can see error about feature-gate DynamicConfigDir
* Enable this and you can see error about deprecated `--feature-gates` option. Looks like a deadlock.
