### ISSUE TITLE
Reject IPv6 address from openstack nodes

### ISSUE THREAD

**Issue by kartoch** [kubernetes/kubernetes#62163]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The openstack of the cloud provider automatically creates an IPv4 and an IPv6 addresses for new compute instances.

When a node is attached to openstack (via `cloud.conf`), both addresses appears in the `spec` section of node info, for instance:

```
  status:
    addresses:
    - address: 2001:41d0:302:1100::a:1720
      type: InternalIP
    - address: 54.38.91.250
      type: InternalIP
    - address: k8s-worker-1
      type: Hostname
```

For some operations, it now fails because IPv6 is not configured in nodes and openstack filter rules drop IPv6 packets. For instance kubectl to a pod in worker returns a tcp error "cannot connect to [IPV6 address]"

It seems that kubernetes takes the first address from the status entry. As it is not possible to reject the IPv6 address from the openstack side, is there a way to not use on the kubernetes side ?

**What you expected to happen**:

Kubernetes does not use IPv6 addresses because it is not configured.

**How to reproduce it (as minimally and precisely as possible)**:

Use a default openstack network with an IPv4 and IPv6 addresses.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration: openstack on OVH
- OS (e.g. from /etc/os-release):

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1632.3.0
VERSION_ID=1632.3.0
BUILD_ID=2018-02-14-0338
PRETTY_NAME="Container Linux by CoreOS 1632.3.0 (Ladybug)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- Kernel (e.g. `uname -a`):

```
Linux k8s-master-0 4.14.19-coreos #1 SMP Wed Feb 14 03:18:05 UTC 2018 x86_64 Intel Core Processor (Haswell, no TSX) GenuineIntel GNU/Linux
```

- Install tools: kubeadm

**Comment by dims** [comment]
cc @leblancd @zioproto

**Comment by pmichali** [comment]
One thought may be to have it prioritize using IPv4 address over IPv6 address, when both are present.

/area ipv6

**Comment by leblancd** [comment]
@dims - Can the openstack cloud provider plugin drop (or ignore) the IPv6 addresses, at least until Kubernetes supports dual-stack?

**Comment by kartoch** [comment]
Thank your for your feedbacks.

@leblancd that the conclusion I have at the present time.

Something fun: it really depends of the first address in the spec section. For instance:

```
  status:
    addresses:
    - address: 2001:41d0:302:1100::a:1720
      type: InternalIP
    - address: 54.38.91.250
      type: InternalIP
```

Give the IPv6 address but:


```
  status:
    addresses:
    - address: 17.3.5.6
      type: InternalIP
    - address: 2001:41d0:302:1100::a:1720
      type: InternalIP
```

Returns the IPv4 address, so it sort the address based on the string comparison ?

My idea for the moment the alternative way I'm testing is ti have two interfaces, one public on the provider network and one on a private IPv4 network.  with a CIDR starting with 10, thus I will be sure that the private address will be the first of the spec section.
