### ISSUE TITLE
kubectl dry run no longer outputs the apiVersion and kind

### ISSUE THREAD

**Issue by jhorwit2** [kubernetes/kubernetes#62207]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/area kubectl
/sig cli

**What happened**:

`kubectl create configmap --dry-run` previously output the apiVersion and kind, which allowed you to pipe it into an apply later. It no longer does as of kubectl 1.10

```
kubectl create configmap test --dry-run -o yaml
metadata:
  creationTimestamp: null
  name: test
```

**What you expected to happen**:

I expect the apiVersion and kind to still be included like it does with kubectl from 1.9.6. 

```
./kubectl create configmap test --dry-run -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: test
```

**How to reproduce it (as minimally and precisely as possible)**:

Run the command above with a 1.10.0 kubectl and notice hte difference from a 1.9.6 kubectl. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}```
