### ISSUE TITLE
cannot ping some pod ip from host but ping another pod ip successfully

### ISSUE THREAD

**Issue by tingweiwu** [kubernetes/kubernetes#62310]
<!-- This form is for bug reports and feature requests ONLY! 

If you're looking for help check [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes) and the [troubleshooting guide](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/).
-->

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
i install  HA master with kubeadm follow this https://v1-9.docs.kubernetes.io/docs/setup/independent/high-availability/

3 master and 1 worknode
 kubectl get nodes
NAME               STATUS    ROLES     AGE       VERSION
host-10-31-3-107   Ready     master    16h       v1.9.3
host-10-31-3-202   Ready     master    17h       v1.9.3
host-10-31-3-240   Ready     master    18h       v1.9.3
host-10-71-0-169   Ready     <none>    16h       v1.9.3

 kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE       IP            NODE
default       rc-centos-7lpdr                            1/1       Running   0          11h       10.244.3.3    host-10-31-3-107
default       rc-centos-gpzf7                            1/1       Running   1          13h       10.244.4.15   host-10-71-0-169
default       rc-centos-ppqj6                            1/1       Running   0          12h       10.244.4.16   host-10-71-0-169
kube-system   canal-74v8v                                3/3       Running   1          17h       10.31.3.202   host-10-31-3-202
kube-system   canal-hxfzn                                3/3       Running   1          16h       10.31.3.107   host-10-31-3-107
kube-system   canal-vp9pm                                3/3       Running   0          9h        10.71.0.169   host-10-71-0-169
kube-system   canal-zdvqz                                3/3       Running   1          17h       10.31.3.240   host-10-31-3-240
kube-system   kube-apiserver-host-10-31-3-107            1/1       Running   0          16h       10.31.3.107   host-10-31-3-107
kube-system   kube-apiserver-host-10-31-3-202            1/1       Running   0          17h       10.31.3.202   host-10-31-3-202
kube-system   kube-apiserver-host-10-31-3-240            1/1       Running   0          18h       10.31.3.240   host-10-31-3-240
kube-system   kube-controller-manager-host-10-31-3-107   1/1       Running   0          16h       10.31.3.107   host-10-31-3-107
kube-system   kube-controller-manager-host-10-31-3-202   1/1       Running   0          17h       10.31.3.202   host-10-31-3-202
kube-system   kube-controller-manager-host-10-31-3-240   1/1       Running   0          18h       10.31.3.240   host-10-31-3-240
kube-system   kube-dns-6f4fd4bdf-924z6                   3/3       Running   0          12h       10.244.1.2    host-10-31-3-202
kube-system   kube-dns-6f4fd4bdf-qfqw9                   3/3       Running   0          12h       10.244.3.2    host-10-31-3-107
kube-system   kube-dns-6f4fd4bdf-wdxz8                   3/3       Running   0          18h       10.244.0.2    host-10-31-3-240
kube-system   kube-proxy-6j74p                           1/1       Running   0          17h       10.31.3.202   host-10-31-3-202
kube-system   kube-proxy-fqtkh                           1/1       Running   0          18h       10.31.3.240   host-10-31-3-240
kube-system   kube-proxy-gxtnq                           1/1       Running   0          16h       10.31.3.107   host-10-31-3-107
kube-system   kube-proxy-qpvz7                           1/1       Running   4          16h       10.71.0.169   host-10-71-0-169
kube-system   kube-scheduler-host-10-31-3-107            1/1       Running   0          16h       10.31.3.107   host-10-31-3-107
kube-system   kube-scheduler-host-10-31-3-202            1/1       Running   0          17h       10.31.3.202   host-10-31-3-202
kube-system   kube-scheduler-host-10-31-3-240            1/1       Running   0          18h       10.31.3.240   host-10-31-3-240

**in node host-10-31-3-107,  i can ping pod ip 10.244.3.2  but cann't ping pod ip 10.244.3.3**

PING 10.244.3.2 (10.244.3.2) 56(84) bytes of data.
64 bytes from 10.244.3.2: icmp_seq=1 ttl=64 time=0.039 ms
64 bytes from 10.244.3.2: icmp_seq=2 ttl=64 time=0.033 ms
64 bytes from 10.244.3.2: icmp_seq=3 ttl=64 time=0.038 ms
64 bytes from 10.244.3.2: icmp_seq=4 ttl=64 time=0.040 ms
64 bytes from 10.244.3.2: icmp_seq=5 ttl=64 time=0.027 ms

PING 10.244.3.3 (10.244.3.3) 56(84) bytes of data.
From 10.31.3.107 icmp_seq=1 Destination Host Unreachable
From 10.31.3.107 icmp_seq=2 Destination Host Unreachable
From 10.31.3.107 icmp_seq=3 Destination Host Unreachable
From 10.31.3.107 icmp_seq=4 Destination Host Unreachable
From 10.31.3.107 icmp_seq=5 Destination Host Unreachable
From 10.31.3.107 icmp_seq=6 Destination Host Unreachable
From 10.31.3.107 icmp_seq=7 Destination Host Unreachable

but from pod(10.244.3.3) inside  it can ping host-10-31-3-107

kubectl exec -it rc-centos-7lpdr /bin/bash
[root@rc-centos-7lpdr /]# ping 10.31.3.107                                                                                                                                                                                                                                   
PING 10.31.3.107 (10.31.3.107) 56(84) bytes of data.
64 bytes from 10.31.3.107: icmp_seq=5 ttl=64 time=1008 ms
64 bytes from 10.31.3.107: icmp_seq=6 ttl=64 time=7.99 ms
64 bytes from 10.31.3.107: icmp_seq=7 ttl=64 time=0.028 ms
64 bytes from 10.31.3.107: icmp_seq=8 ttl=64 time=0.034 ms
64 bytes from 10.31.3.107: icmp_seq=9 ttl=64 time=0.035 ms

**What you expected to happen**:

when k8s cluster installed sucesslly and all needed pod is running , pod ip should be reachable from any host in k8s cluser 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
[root@host-10-31-3-107 ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.31.3.121     0.0.0.0         UG    0      0        0 eth0
10.0.0.0        10.31.3.1       255.0.0.0       UG    0      0        0 eth0
10.31.3.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0
10.244.0.0      10.244.0.0      255.255.255.0   UG    0      0        0 flannel.1
10.244.1.0      0.0.0.0         255.255.255.0   U     0      0        0 docker0
10.244.3.2      0.0.0.0         255.255.255.255 UH    0      0        0 cali38d075e6956
10.244.3.3      0.0.0.0         255.255.255.255 UH    0      0        0 cali14c560cb979
10.244.4.0      10.244.4.0      255.255.255.0   UG    0      0        0 flannel.1
169.254.169.254 10.31.3.1       255.255.255.255 UGH   0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-b8f5bc4d511f


[root@rc-centos-7lpdr /]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         169.254.1.1     0.0.0.0         UG    0      0        0 eth0
169.254.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 eth0

[root@rc-centos-7lpdr /]# ifconfig
eth0      Link encap:Ethernet  HWaddr 16:97:22:16:CD:87  
          inet addr:10.244.3.3  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3930 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3587 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:35802506 (34.1 MiB)  TX bytes:210678 (205.7 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)


addtional
when i ping 10.244.3.3 from 10.31.3.107 , i run tcpdump -i eth0 in pod(10.244.3.3) and see this 
1	0.000000	ee:ee:ee:ee:ee:ee	Broadcast	ARP	42	Who has 10.244.3.3?  Tell 10.31.3.107
.....




15	18.008023	ee:ee:ee:ee:ee:ee	Broadcast	ARP	42	Who has 10.244.3.3?  Tell 10.31.3.107

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}


- Cloud provider or hardware configuration:

- OS (e.g. from /etc/os-release):
cat /etc/os-release
NAME="EulerOS"
VERSION="2.0 (SP2)"
ID="euleros"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.0"
PRETTY_NAME="EulerOS 2.0 (SP2)"
ANSI_COLOR="0;31"

- Kernel (e.g. `uname -a`):
uname -a
Linux host-10-31-3-240 3.10.0-327.59.59.46.h44.x86_64 #1 SMP Tue Jan 9 11:27:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubeadm
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Others:

**Comment by tingweiwu** [comment]
here is the network canal define yaml 
cat canal.yaml
```
# Canal Version v3.0.3
# https://docs.projectcalico.org/v3.0/releases#v3.0.3
# This manifest includes the following component versions:
#   calico/node:v3.0.3
#   calico/cni:v2.0.1
#   coreos/flannel:v0.9.1

# This ConfigMap can be used to configure a self-hosted Canal installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: canal-config
  namespace: kube-system
data:
  # The interface used by canal for host <-> host communication.
  # If left blank, then the interface is chosen using the node's
  # default route.
  canal_iface: ""

  # Whether or not to masquerade traffic to destinations not within
  # the pod network.
  masquerade: "true"

  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
        "name": "k8s-pod-network",
        "cniVersion": "0.3.0",
        "plugins": [
            {
                "type": "calico",
                "log_level": "info",
                "datastore_type": "kubernetes",
                "nodename": "__KUBERNETES_NODE_NAME__",
                "ipam": {
                    "type": "host-local",
                    "subnet": "usePodCidr"
                },
                "policy": {
                    "type": "k8s",
                    "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
                },
                "kubernetes": {
                    "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
                    "kubeconfig": "__KUBECONFIG_FILEPATH__"
                }
            },
            {
                "type": "portmap",
                "capabilities": {"portMappings": true},
                "snat": true
            }
        ]
    }

  # Flannel network configuration. Mounted into the flannel container.
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }

---

# This manifest installs the calico/node container, as well
# as the Calico CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: canal
  namespace: kube-system
  labels:
    k8s-app: canal
spec:
  selector:
    matchLabels:
      k8s-app: canal
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: canal
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      serviceAccountName: canal
      tolerations:
        # Tolerate this effect so the pods will be schedulable at all times
        - effect: NoSchedule
          operator: Exists
        # Mark the pod as a critical add-on for rescheduling.
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      # Minimize downtime during a rolling upgrade or deletion; tell Kubernetes to do a "force
      # deletion": https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods.
      terminationGracePeriodSeconds: 0
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: quay.io/calico/node:v3.0.3
          env:
            # Use Kubernetes API as the backing datastore.
            - name: DATASTORE_TYPE
              value: "kubernetes"
            # Enable felix logging.
            - name: FELIX_LOGSEVERITYSYS
              value: "info"
            # Don't enable BGP.
            - name: CALICO_NETWORKING_BACKEND
              value: "none"
            # Cluster type to identify the deployment type
            - name: CLUSTER_TYPE
              value: "k8s,canal"
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Period, in seconds, at which felix re-applies all iptables state
            - name: FELIX_IPTABLESREFRESHINTERVAL
              value: "60"
            # Disable IPV6 support in Felix.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            # Wait for the datastore.
            - name: WAIT_FOR_DATASTORE
              value: "true"
            # No IP address needed.
            - name: IP
              value: "autodetect"
            - name: IP_AUTODETECTION_METHOD
              value: "can-reach=10.31.3.1"
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            - name: FELIX_HEALTHENABLED
              value: "true"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9099
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9099
            periodSeconds: 10
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: quay.io/calico/cni:v2.0.1
          command: ["/install-cni.sh"]
          env:
            - name: CNI_CONF_NAME
              value: "10-calico.conflist"
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: canal-config
                  key: cni_network_config
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
        # This container runs flannel using the kube-subnet-mgr backend
        # for allocating subnets.
        - name: kube-flannel
          image: quay.io/coreos/flannel:v0.9.1-amd64
          command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr" ]
          securityContext:
            privileged: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FLANNELD_IFACE
              valueFrom:
                configMapKeyRef:
                  name: canal-config
                  key: canal_iface
            - name: FLANNELD_IP_MASQ
              valueFrom:
                configMapKeyRef:
                  name: canal-config
                  key: masquerade
          volumeMounts:
          - name: run
            mountPath: /run
          - name: flannel-cfg
            mountPath: /etc/kube-flannel/
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        # Used by flannel.
        - name: run
          hostPath:
            path: /run
        - name: flannel-cfg
          configMap:
            name: canal-config


# Create all the CustomResourceDefinitions needed for
# Calico policy-only mode.
---

apiVersion: apiextensions.k8s.io/v1beta1
description: Calico Felix Configuration
kind: CustomResourceDefinition
metadata:
   name: felixconfigurations.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: FelixConfiguration
    plural: felixconfigurations
    singular: felixconfiguration

---

apiVersion: apiextensions.k8s.io/v1beta1
description: Calico BGP Configuration
kind: CustomResourceDefinition
metadata:
  name: bgpconfigurations.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: BGPConfiguration
    plural: bgpconfigurations
    singular: bgpconfiguration

---

apiVersion: apiextensions.k8s.io/v1beta1
description: Calico IP Pools
kind: CustomResourceDefinition
metadata:
  name: ippools.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: IPPool
    plural: ippools
    singular: ippool

---

apiVersion: apiextensions.k8s.io/v1beta1
description: Calico Cluster Information
kind: CustomResourceDefinition
metadata:
  name: clusterinformations.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: ClusterInformation
    plural: clusterinformations
    singular: clusterinformation

---

apiVersion: apiextensions.k8s.io/v1beta1
description: Calico Global Network Policies
kind: CustomResourceDefinition
metadata:
  name: globalnetworkpolicies.crd.projectcalico.org
spec:
  scope: Cluster
  group: crd.projectcalico.org
  version: v1
  names:
    kind: GlobalNetworkPolicy
    plural: globalnetworkpolicies
    singular: globalnetworkpolicy

---

apiVersion: apiextensions.k8s.io/v1beta1
description: Calico Network Policies
kind: CustomResourceDefinition
metadata:
  name: networkpolicies.crd.projectcalico.org
spec:
  scope: Namespaced
  group: crd.projectcalico.org
  version: v1
  names:
    kind: NetworkPolicy
    plural: networkpolicies
    singular: networkpolicy

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: canal
  namespace: kube-system
```

cat rbac.yaml 
```
# Calico Roles
# Pulled from https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods/status
    verbs:
      - update
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups: [""]
    resources:
      - services
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - endpoints
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups: ["extensions"]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - globalfelixconfigs
      - felixconfigurations
      - bgppeers
      - globalbgpconfigs
      - bgpconfigurations
      - ippools
      - globalnetworkpolicies
      - networkpolicies
      - clusterinformations
    verbs:
      - create
      - get
      - list
      - update
      - watch

---

# Flannel roles
# Pulled from https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel-rbac.yml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: flannel
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
---

# Bind the flannel ClusterRole to the canal ServiceAccount.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: canal-flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: canal
  namespace: kube-system

---

# Bind the calico ClusterRole to the canal ServiceAccount.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: canal-calico
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico
subjects:
- kind: ServiceAccount
  name: canal
  namespace: kube-system

```
