### ISSUE TITLE
kubectl apply doesn't update Deployment container ports correctly

### ISSUE THREAD

**Issue by jethrogb** [kubernetes/kubernetes#62366]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When `kubectl apply`ing a configuration that changes the container ports in a pod template of a deployment, the final updated configuration is incorrect.

**What you expected to happen**:

I expected the active spec after `kubectl apply` to be the same as the spec specified in the file.

**How to reproduce it (as minimally and precisely as possible)**:

[d1.yml.txt](https://github.com/kubernetes/kubernetes/files/1897011/d1.yml.txt)
[d2.yml.txt](https://github.com/kubernetes/kubernetes/files/1897012/d2.yml.txt)

```
$ tail -n5 d2.yml
        ports:
        - containerPort: 4443
          hostPort: 443
        - containerPort: 4443
          hostPort: 4443
$ kubectl apply -f d2.yml
$ tail -n3 d1.yml
        ports:
        - containerPort: 4443
          hostPort: 443
$ kubectl apply -f d1.yml
$ kubectl get deploy -oyaml
...
      spec:
        containers:
        - command:
          - /bin/sh
          - -c
          - while true; do sleep 1000; done
          image: busybox:latest
          imagePullPolicy: Always
          name: b1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
...
```

Note that there are no container ports at all in the active configuration.

You can also reverse the application of `d1.yml` and `d2.yml` and then the ports are not updated at all.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: VirtualBox
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): Linux node2 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

I also tried with version 1.10 that's currently available on Katacoda, same issue.

**Comment by jethrogb** [comment]
I don't know what the right SIG is.

/sig api-machinery

**Comment by wenjiaswe** [comment]
cc @jennybuckley

**Comment by jennybuckley** [comment]
This is a general issue with the current implementation of apply. If a list is allowed to have multiple entries with the same value for their patchMergeKey, then this behavior is expected. We are working on changing the apply implementation so the merging is done on the server side, rather than by kubectl.

In this specific case, [containerPort is the patchMergeKey](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L1967). So to fix this in the short term, either the patchmergekey should be changed to include both containerPort and hostPort, the mergeStrategy should be changed, or the validation for ports should be changed so that any containerPort can only be present in one element of the list.
/sig apps

Related: #58477, #59119

**Comment by akolosov-a** [comment]
The issue is obviously also affects the cases when same container port number is used for different protocols (TCP/UDP), so the `protocol` field should also be taken into account during merging. Example:

port-merge-issue1.yml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: port-merge-issue
  name: port-merge-issue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: port-merge-issue
  template:
    metadata:
      labels:
        app: port-merge-issue
    spec:
      containers:
        - image: k8s.gcr.io/pause:3.1
          name: container
          ports:
          - containerPort: 1111
            name: tcp-port
            protocol: TCP
          - containerPort: 1111
            name: udp-port
            protocol: UDP
```

port-merge-issue2.yml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: port-merge-issue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: port-merge-issue
  template:
    metadata:
      labels:
        app: port-merge-issue
    spec:
      containers:
        - image: k8s.gcr.io/pause:3.1
          name: container
          ports:
          - containerPort: 1112
            name: tcp-port
            protocol: TCP
          - containerPort: 1112
            name: udp-port
            protocol: UDP
```
The only change between two manifests is replacing port 1111 with 1112.

After applying the newer version over the original one the UDP port disappears from pod's spec:
```sh
$ kubectl apply -f port-merge-issue1.yml
deployment.apps/port-merge-issue created

$ kubectl get pod -l app=port-merge-issue -o json | jq '.items[0].spec.containers[0].ports'
[
  {
    "containerPort": 1111,
    "name": "tcp-port",
    "protocol": "TCP"
  },
  {
    "containerPort": 1111,
    "name": "udp-port",
    "protocol": "UDP"
  }
]

$ kubectl apply -f port-merge-issue2.yml
deployment.apps/port-merge-issue configured

$ kubectl get pod -l app=port-merge-issue -o json | jq '.items[0].spec.containers[0].ports'
[
  {
    "containerPort": 1112,
    "name": "tcp-port",
    "protocol": "TCP"
  }
]
```
