### ISSUE TITLE
Backoff Limit for Job does not work on Kubernetes 1.10.0

### ISSUE THREAD

**Issue by keimoon** [kubernetes/kubernetes#62382]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**: 

`.spec.backoffLimit` for a Job does not work on Kubernetes 1.10.0

**What you expected to happen**:

`.spec.backoffLimit` can limit the number of time a pod is restarted when running inside a job

**How to reproduce it (as minimally and precisely as possible)**:

Use this resource file:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: error
spec:
  backoffLimit: 1
  template:
    metadata:
      name: job
    spec:
      restartPolicy: Never
      containers:
        - name: job
          image: ubuntu:16.04
          args:
            - sh
            - -c
            - sleep 5; false
```

If the job was created in Kubernetes 1.9, it will soon fail:

```
....
status:
    conditions:
    - lastProbeTime: 2018-04-11T10:20:31Z
      lastTransitionTime: 2018-04-11T10:20:31Z
      message: Job has reach the specified backoff limit
      reason: BackoffLimitExceeded
      status: "True"
      type: Failed
    failed: 2
    startTime: 2018-04-11T10:20:00Z
...
```

While creating the job in Kubernetes 1.10, it will be restarted infinitely:

```
...
status:
  active: 1
  failed: 8
  startTime: 2018-04-11T10:37:48Z
...
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): `Linux`
- Install tools: Kubeadm
- Others:

**Comment by jangrewe** [comment]
We just updated to 1.10 and seem to be affected by this, too.

**Comment by CallMeFoxie** [comment]
Can confirm with 1.10.1

**Comment by ceshihao** [comment]
It seems to be introduced by #60985

cc @soltysh

**Comment by foxish** [comment]
Cause appears to be that the `syncJob` method gets exactly one attempt to update the status with the failed condition and if it fails due to resource conflict, it never adds the condition. The controller code seems to use requeues to track failures, but if a sync loop executes successfully, it would lose track of the failed item ever having been requeued.

**Comment by foxish** [comment]
Looking at [job_controller.go#L249](https://github.com/kubernetes/kubernetes/blob/139309f798176378f7acf182f4378c287c7baa3b/pkg/controller/job/job_controller.go#L249), we force an immediate resync when we see a pod that has failed which also clears the key in our queue, but that in turn makes us lose state of the number of requeues.

**Comment by drdivano** [comment]
This bug killed my test cluster over the long weekend. Luckily we don't yet use CronJobs in prod.

**Comment by nerumo** [comment]
killed my cluster too :( still existing in kubernetes 1.10.2

**Comment by hanikesn** [comment]
This issue also can't be mitigated as terminated are not part of the resource quota: https://github.com/kubernetes/kubernetes/issues/51150

**Comment by nyxi** [comment]
This is a pretty terrible bug and it definitely still exists in v1.10.2

**Comment by soltysh** [comment]
Looking right now...

**Comment by soltysh** [comment]
I've opened #63650 to address the issue. Sorry for the troubles y'all.

**Comment by CallMeFoxie** [comment]
@soltysh pulled the patch into current 1.10.2 release and it works! Thanks :)

**Comment by janetkuo** [comment]
@soltysh 
I filed #63990 (with #63650 and a test for backoffLimit). The test exposes some other problems:

1. Job never retries ([log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63990/pull-kubernetes-e2e-gce/36171/)): the code uses `NumRequeues` to see the number of retries. However, the job can failed to be synced just because of a update conflict (`the object has been modified; please apply your changes to the latest version and try again`). That shouldn't be seen as a retry.
https://github.com/kubernetes/kubernetes/blob/77a08ee2d774d1785670677d4d4b7d1a1739c12c/pkg/controller/job/job_controller.go#L463-L464
2. Job retries more than needed ([log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63990/pull-kubernetes-e2e-kops-aws/89277)): Job controller creates more pods than needed because it doesn't realize itself has failed and exceeded backoffLimit earlier. This may be due to stale cache or that the job status failed to be updated earlier. 

I think Job backoffLimit is still broken.

**Comment by arikkfir** [comment]
FWIW,(assuming I'm not missing something) I can confirm on GKE 1.10.2-gke.3 (latest as of Jun 2nd) the `backoffLimit` is still broken. The following job spec endlessly creates pods:
```
apiVersion: batch/v1
kind: Job
metadata:
  namespace: jobs
  name: failer
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: job
          image: debian
          command: ["bash","-c","sleep 3 && exit 1"]
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 100Mi
      restartPolicy: Never    
      tolerations:
        - key: role
          operator: Equal
          value: jobs
          effect: NoExecute
```
