### ISSUE TITLE
K8s can't pull images from a private gcr.io repository

### ISSUE THREAD

**Issue by walteraa** [kubernetes/kubernetes#62393]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I am trying  to deploy an app which the image is saved in the Google Container Registry, but I am getting the following error:

`Warning  Failed                 11s               kubelet, gke-cluster-1-default-pool-32ed223c-0vsv  Failed to pull image "gcr.io/potent-zodiac-172621/teste-app:latest": [rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/potent-zodiac-172621/teste-app/manifests/latest: unknown: Unable to parse json key., rpc error: code = Unknown desc = error pulling image configuration: error parsing HTTP 400 response body: invalid character '<' looking for beginning of value: "<?xml version='1.0' encoding='UTF-8'?><Error><Code>UserProjectMissing</Code><Message>Bucket is a requester pays bucket but no user project provided.</Message></Error>"]`

**What you expected to happen**:
I expect that my google k8s instance could access my private repositories in gcr.io, but it doen't happened.

**How to reproduce it (as minimally and precisely as possible)**:

The were the steps I followed:

- I built and pushed the app in gcr.io as a private repository

- Create an service account by running the following script:
```
# create a GCP service account; format of account is email address
SA_EMAIL=$(gcloud iam service-accounts --format='value(email)' create k8s-gcr-auth-ro)
# create the json key file and associate it with the service account
gcloud iam service-accounts keys create k8s-gcr-auth-ro.json --iam-account=$SA_EMAIL
# get the project id
PROJECT=$(gcloud config list core/project --format='value(core.project)')
# add the IAM policy binding for the defined project and service account
gcloud projects add-iam-policy-binding $PROJECT --member serviceAccount:$SA_EMAIL --role roles/storage.objectViewer
```

-  I've created the secret by running it:

```
SECRETNAME=grcio-credentials

kubectl create secret docker-registry $SECRETNAME \
  --docker-server=https://gcr.io \
  --docker-username=_json_key \
  --docker-email=user@example.com \
  --docker-password="$(cat k8s-gcr-auth-ro.json)"
```

- After that, I added `imagePullSecrets` in my deployment file as you can see below:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: app
          image: gcr.io/potent-zodiac-172621/teste-app:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: 127.0.0.1:3306
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: DB_DATABASE
              value: admin_teste
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=potent-zodiac-172621:southamerica-east1:teste-instance=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      imagePullSecrets:
        - name: gcrio-credentials
```

- Then I performed a `kubectl create -f` using the yaml file above.

Then pod keep stucked in `ImagePullBackOff` because it can pull my private image.

**Anything else we need to know?**:
- Both(k8s and gcr) are in the same project.
- I didn't find nothing about pulling private images in the GKE, it looks like once both are in the same project, it should works automatically.

**Environment**:
- Kubernetes version (use `kubectl version`): *v1.9.1*
- Cloud provider or hardware configuration: *GCE*
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
