### ISSUE TITLE
ValidatingAdmissionWebhook Appears Incapable of Listening for apps/v1 Deployments

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#62404]
/kind bug

**What happened**: ValidatingAdmissionWebhook was configured to listen to creates and updates on apps/v1 Deployments. A submitted apps/v1 Deployment was not passed through to the web hook.

**What you expected to happen**: I expect AdmissionControl to send the apps/v1 Deployment to admission control.

**How to reproduce it (as minimally and precisely as possible)**:

Create a ValidatingAdmissionWebhook with the following rule and pass it to a web hook that will reject all Deployments.

```
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
```

Use `kubectl create -f` to create a Deployment with `apiVersion: apps/v1` specified. The deployment will not pass to the web hook and will be allowed.

Simply altering this to listen for `extensions/v1beta1` Deployments will result in a rejected call.

**Anything else we need to know?**:

I discovered this while running into #62402 

**Environment**:
- 1.9.x
- bare metal
- CentOS 7
