### ISSUE TITLE
Container is blasted rapidly with readiness probes, despite longer configured interval

### ISSUE THREAD

**Issue by bw** [kubernetes/kubernetes#62426]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

We have liveness and readiness probes configured for a Node container running inside a Deployment/Pod. These are configured with generous timeouts and failure thresholds:

```yaml
readinessProbe:
  httpGet:
    path: /route/to/healthcheck?ready
  initialDelaySeconds: 15
  timeoutSeconds: 15
  periodSeconds: 17
  failureThreshold: 8
livenessProbe:
  httpGet:
    path: /route/to/healthcheck?live
  initialDelaySeconds: 60
  timeoutSeconds: 15
  periodSeconds: 37
  failureThreshold: 8
```

For some reason, these would regularly fail due to "Request canceled (Client.Timeout exceeded while awaiting headers)" with no logs from inside the Node container indicating that any request had timed out.

While debugging this issue (which, by the way, if you have any help I would greatly appreciate) I noticed that despite the configured period of 17 seconds on the readiness probe, the actual container is being hit with many more readiness probes than configured.

On average it looks like we get one every few seconds, usually 4-5 at a time in rapid succession (milliseconds apart). Sometimes we get 8-10 in the span of less than 50ms. Our Node server is responding to all of these probes successfully and very fast-- with 200 codes in less than half a millisecond.

**What you expected to happen**:

That we will only receive one probe per configured period, unless a probe fails, after which we expect Kubernetes will send additional probes until the failure threshold is reached or a successful response is seen. (At least, this is my understanding of the documentation).

**How to reproduce it (as minimally and precisely as possible)**:

Use the configuration described above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.2-gke.1 (v1.9.2)
- Cloud provider or hardware configuration: Google Kubernetes Engine
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
