### ISSUE TITLE
Pods with PVCs take a long time to start

### ISSUE THREAD

**Issue by afong94** [kubernetes/kubernetes#62480]
/kind bug

**What happened**:
Upon deploying a workload with uses PVCs on vSphere, it takes about 4-5 minutes for each pod to be created.

**What you expected to happen**:
Persistent volumes should not take as long to mount

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a vsphere storage class, e.g.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ci-storage
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: zeroedthick
```

Deploy a statefulset workload that uses this storage class, e.g. 
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sample-statefulset
spec:
  serviceName: "pv-ex-svc"
  replicas: 3
  template:
    metadata:
      labels:
        app: pv-ex
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pv-ex
        image: pcfkubo/persistent-example
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: www
          mountPath: /usr/share/pv-ex
        env:
        - name: LOG_FILE
          value: /usr/share/pv-ex/log.txt
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ci-storage
      resources:
        requests:
          storage: 1Gi
```

**Anything else we need to know?**: The slowness is observed on both thick and thin provisioned storage-class definitions.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2
- Cloud provider or hardware configuration: vsphere
- OS (e.g. from /etc/os-release): ubuntu 14.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig vmware
