### ISSUE TITLE
Add support of multiple subnets in Azure cloud provider

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#62514]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Azure cloud provider won't able to create LB for multiple subnets. Refer https://github.com/Azure/acs-engine/issues/2476.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.X
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by feiskyer** [comment]
cc @ritazh Please post the results here when you got results.

**Comment by ritazh** [comment]
Confirming this issue cannot be reproduced on v1.11+
Using aks-engine to create a cluster with 2 agentPools `agent1` and `agent2`, with `primaryAvailabilitySetName` set to agent1 availability set. This will result in agent1 availability set to be added to backend pool of the loadbalancer, as expected.

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.11",
      "kubernetesConfig": {
         "privateCluster": {
	    "enabled" : true
	 }
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_DS2_v2",
      "vnetSubnetId": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Network/virtualNetworks/myvnet/subnets/master",
      "firstConsecutiveStaticIP": "10.239.255.239",
      "vnetCidr": "10.239.0.0/16"
    },
    "agentPoolProfiles": [
      {
        "name": "agent1",
        "count": 1,
        "vnetSubnetId": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Network/virtualNetworks/myvnet/subnets/agent1",
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet"
      },
      {
        "name": "agent2",
        "count": 1,
        "vnetSubnetId": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Network/virtualNetworks/myvnet/subnets/agent2",
        "vmSize": "Standard_DS2_v2",
        "availabilityProfile": "AvailabilitySet"
      }

    ],
    "linuxProfile": {
      "adminUsername": "",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

Test deployment/svc yaml:
```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
      nodeSelector:
        agentpool: agent2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-load-balancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    run: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
```

This forces the pod to be deployed on a node in agentPool `agent2`.
```sh
kubectl get po -o wide
NAME                                READY     STATUS    RESTARTS   AGE       IP            NODE                    NOMINATED NODE
nginx-deployment-6b648c6fd9-wzqch   1/1       Running   0          13m       10.239.1.26   k8s-agent2-42982342-0   <none>

kubectl get svc
NAME                           TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)          AGE
nginx-internal-load-balancer   LoadBalancer   10.0.241.38   10.239.255.35   8080:30711/TCP   1m
```
curl works

```sh
curl 10.239.255.35
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...
```
This still works if we deploy the pods across all nodes in the cluster. Also this works with vmss and standard LB.
