### ISSUE TITLE
devicePath for block volumes is not honored

### ISSUE THREAD

**Issue by stu-gott** [kubernetes/kubernetes#62560]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Specified `devicePath: /dev/pvcname` for a volumeDevice, but it was not present in container.

**What you expected to happen**:
/dev/pvcname should exist inside container.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-volume-mode
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "360000"
    image: ubuntu
    imagePullPolicy: Always
    securityContext:
      privileged: true
    name: busybox
    volumeDevices:
    - devicePath: /dev/pvcname
      name: pvcvolume
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  schedulerName: default-scheduler
  serviceAccount: default
  serviceAccountName: default
  volumes:
    - name: pvcvolume
      persistentVolumeClaim:
        claimName: disk-cirros-block
```

**Anything else we need to know?**:
This is quite possibly related to https://github.com/kubernetes/kubernetes/issues/58251 but what we're seeing is slightly different. With the above pod spec, we see these devices:

```
autofs           dm-11  dm-20  dm-3   fd            loop1               nvram     sda       snd              tty11  tty20  tty3   tty39  tty48  tty57  tty9     vcs1   vcsa4        vhost-net
bsg              dm-12  dm-21  dm-30  full          loop2               oldmem    sdb       sr0              tty12  tty21  tty30  tty4   tty49  tty58  ttyS0    vcs2   vcsa5        zero
btrfs-control    dm-13  dm-22  dm-4   fuse          mapper              parport0  sdc       stderr           tty13  tty22  tty31  tty40  tty5   tty59  ttyS1    vcs3   vcsa6
core             dm-14  dm-23  dm-5   hpet          mcelog              port      sg0       stdin            tty14  tty23  tty32  tty41  tty50  tty6   ttyS2    vcs4   vda
cpu              dm-15  dm-24  dm-6   hwrng         mem                 ppp       sg1       stdout           tty15  tty24  tty33  tty42  tty51  tty60  ttyS3    vcs5   vda1
cpu_dma_latency  dm-16  dm-25  dm-7   input         mqueue              ptmx      sg2       termination-log  tty16  tty25  tty34  tty43  tty52  tty61  uhid     vcs6   vda2
crash            dm-17  dm-26  dm-8   kmsg          net                 pts       sg3       tty              tty17  tty26  tty35  tty44  tty53  tty62  uinput   vcsa   vda3
dm-0             dm-18  dm-27  dm-9   kvm           network_latency     random    sg4       tty0             tty18  tty27  tty36  tty45  tty54  tty63  urandom  vcsa1  vfio
dm-1             dm-19  dm-28  dri    loop-control  network_throughput  raw       shm       tty1             tty19  tty28  tty37  tty46  tty55  tty7   usbmon0  vcsa2  vga_arbiter
dm-10            dm-2   dm-29  fb0    loop0         null                rtc0      snapshot  tty10            tty2   tty29  tty38  tty47  tty56  tty8   vcs      vcsa3  vhci
```

Since `/dev` is bind mounted, we also tried `/mnt/pvcname` as a devicePath--and it still was not present.

~~`/dev/vda` is present, and is the PersistentVolume we expected: we just expected a link or symlink named /dev/pvcname.~~

Trying the above in unprivileged mode also does not result in `/dev/pvcname` being present.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
```Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

EDIT: redacted comment about /dev/vda being preset

**Comment by fabiand** [comment]
Maybe related to #58251

**Comment by stu-gott** [comment]
Not sure if it helps, but here's the PV and PVC manifests we used:

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-disk-cirros-block
  labels:
    kubevirt.io: ""
    os: "cirros-block"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  iscsi:
    iqn: iqn.2017-01.io.kubevirt:sn.42
    lun: 3
    targetPortal: "127.0.0.1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-cirros-block
  labels:
    kubevirt.io: ""
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      os: "cirros-block"
```
