### ISSUE TITLE
kube-apiserver denying CSRs with empty reason on v1.10.1

### ISSUE THREAD

**Issue by seanknox** [kubernetes/kubernetes#62585]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**: The bootstrap token is validated but kube-apiserver is denying CSRs with an empty reason: 

```
Apr 14 16:38:37 k8scontroller2 kube-apiserver[47830]: I0414 16:38:37.124286   47830 authorization.go:60] Forbidden: "/apis/certificates.k8s.io/v1beta1/certificatesigningrequests", Reason: ""
```

On the kubelet:
```
Apr 14 16:38:37 node1 kubelet[43732]: I0414 16:38:37.058572   43732 bootstrap.go:58] Using bootstrap kubeconfig to generate TLS client cert, key and kubeconfig file
Apr 14 16:38:37 node1 kubelet[43732]: F0414 16:38:37.127290   43732 server.go:233] failed to run Kubelet: cannot create certificate signing request: certificatesigningrequests.certificates.k8s.io is forbidden: User "system:bootstrap:4dfd2f" cannot create certificatesigningrequests.certificates.k8s.io at the cluster scope
```

**What you expected to happen**: I'm using [bootstrap tokens](https://kubernetes.io/docs/admin/bootstrap-tokens/) to join nodes to a cluster. RBAC roles and bootstrap secret are configured on the API server, and kubelet is configured to bootstrap. 

**How to reproduce it (as minimally and precisely as possible)**:

Relevant RBAC role on API server:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeadm:node-autoapprove-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:certificates.k8s.io:certificatesigningrequests:nodeclient
subjects:
- kind: Group
  name: system:bootstrappers:kubeadm:default-node-token
```
Bootstrap secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: bootstrap-token-4dfd2f
  namespace: kube-system

type: bootstrap.kubernetes.io/token
stringData:
  description: "The default bootstrap token generated by 'kubeadm init'."
  token-id: 4dfd2f
  token-secret: 27b420c2b58982c3

  usage-bootstrap-authentication: "true"
  usage-bootstrap-signing: "true"

  auth-extra-groups: system:bootstrappers:worker,system:bootstrappers:ingress
```

Kubelet bootstrap config:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CR ...
    server: https://10.0.128.250:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: tls-bootstrap-token-user
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: tls-bootstrap-token-user
  user:
    token: 4dfd2f.27b420c2b58982c3
```

**Anything else we need to know?**:

**Environment**: Linux
- Kubernetes version (use `kubectl version`): v1.10.1
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu 17.10
- Kernel (e.g. `uname -a`): `Linux k8scontroller2 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Manual (with Terraform)
- Others:

**Comment by seanknox** [comment]
cc @kubernetes/sig-auth-bugs @kubernetes/sig-api-machinery-bugs

**Comment by liggitt** [comment]
Your rolebinding grants to the group system:bootstrappers:kubeadm:default-node-token but that group is not part of your bootstrap token

**Comment by seanknox** [comment]
Thanks @liggitt, totally missed that despite staring at it for hours.

**Comment by seanknox** [comment]
For posterity, the fix was updating the `auth-extra-groups` field in the secret to include the `system:node-bootstrapper` group referenced in the ClusterRoleBinding. Changed:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: bootstrap-token-${TOKEN_ID}
  namespace: kube-system

type: bootstrap.kubernetes.io/token
stringData:
  description: "The default bootstrap token generated by 'kubeadm init'."
  token-id: ${TOKEN_ID}
  token-secret: ${TOKEN_CONTENT}

  usage-bootstrap-authentication: "true"
  usage-bootstrap-signing: "true"

  auth-extra-groups: system:bootstrappers:worker,system:bootstrappers:ingress
```

to:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: bootstrap-token-${TOKEN_ID}
  namespace: kube-system

type: bootstrap.kubernetes.io/token
stringData:
  description: "The default bootstrap token generated by 'kubeadm init'."
  token-id: ${TOKEN_ID}
  token-secret: ${TOKEN_CONTENT}

  usage-bootstrap-authentication: "true"
  usage-bootstrap-signing: "true"

  auth-extra-groups: system:bootstrappers:kubeadm:default-node-token
```

Thanks again @liggitt.
