### ISSUE TITLE
Bug: `Kubectl get pod` - Pod is running and has two Containers. Container 1 exits with success.

### ISSUE THREAD

**Issue by hochuenw** [kubernetes/kubernetes#62588]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
When one pod is running and has two Containers. Container 1 exits with success and container 2 is running.
`kubectl get test -o=json` gives correct info -  the pod status is `Running`. 
However, `kubectl get pod test -o=wide`, the pod status is `Completed`.

**What you expected to happen**:
`kubectl get pod test -o=wide`, the pod status is `Running`.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: test
spec:
  restartPolicy: Never
  containers:
  - name: test1
    image: busybox
    command: ["sh", "-c", "echo hello"]
  - name: test2
    image: busybox
    command: ["sh", "-c", "sleep 10000"]
```

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
