### ISSUE TITLE
statefulSet: Cannot ping pods in init container

### ISSUE THREAD

**Issue by hochuenw** [kubernetes/kubernetes#62604]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
for a statefulset using headless service, though the hostname is indexed, it can not ping the other pod through the dns name.

**What you expected to happen**:
Init container can ping each other through hostname.

**How to reproduce it (as minimally and precisely as possible)**:
1. create one statefulset with one init container
```
 apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  podManagementPolicy: Parallel 
  serviceName: "nginx"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'sleep 1000']
      containers:
      - name: nginx
        image: busybox
        command: ["sh", "-c", "sleep 1000"]
        ports:
        - containerPort: 80
```

2. try to ping the other pod
```
$ kubectl get pods
NAME      READY     STATUS     RESTARTS   AGE
web-0     0/1       Init:0/1   0          55s
web-1     0/1       Init:0/1   0          55s

[centos:/home/centos/batchd at 23:59:14 on 15/04/2018]
$ kubectl exec -it web-0 -c init-myservice sh
/ # ping web-1.nginx
ping: bad address 'web-1.nginx'
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
