### ISSUE TITLE
statefulSet: check external dns entry is created before running command

### ISSUE THREAD

**Issue by hochuenw** [kubernetes/kubernetes#62605]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:

given this yaml:

```
 apiVersion: v1
 kind: Service
 metadata:
   name: nginx
   labels:
     app: nginx
 spec:
   ports:
   - port: 80
     name: web
   clusterIP: None
   selector:
     app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  podManagementPolicy: Parallel 
  serviceName: "nginx"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: busybox
        command: ["sh", "-c", "ping web-0.nginx; sleep 3; ping web-0.nginx"]
        ports:
        - containerPort: 80```
```

log is:
```
ping: bad address 'web-0.nginx'
PING web-0.nginx (10.244.0.78): 56 data bytes
64 bytes from 10.244.0.78: seq=0 ttl=64 time=0.031 ms
64 bytes from 10.244.0.78: seq=1 ttl=64 time=0.041 ms
64 bytes from 10.244.0.78: seq=2 ttl=64 time=0.038 ms
64 bytes from 10.244.0.78: seq=3 ttl=64 time=0.071 ms
64 bytes from 10.244.0.78: seq=4 ttl=64 time=0.045 ms
64 bytes from 10.244.0.78: seq=5 ttl=64 time=0.059 ms
```
The first ping failed. but after 3 seconds, it works. My guess is that pod is addressable through the headless service, and the external dns entry just need some time to be created..
So in order to ping the other with success, I have to add `sleep 3` before all commands.
Can a statefulSet have some logic like `until nslookup 'web-0.nginx'; do echo waiting for myservice; sleep 2; done;` ?

**What you expected to happen**:
statefulSet have some logic like `until nslookup 'web-0.nginx'; do echo waiting for myservice; sleep 2; done;`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
