### ISSUE TITLE
GlusterFS volume always mounts first endpoint instead of random endpoint

### ISSUE THREAD

**Issue by pkdetlefsen** [kubernetes/kubernetes#62637]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When mounting dynamically provisioned GlusterFS volumes in your deployments the first IP in the Endpoints object will always be used. 

**What you expected to happen**:

According to [this example](https://github.com/kubernetes/examples/blob/master/staging/volumes/glusterfs/README.md) a random endpoint should be picked.

> endpoints is the name of the Endpoints object that represents a Gluster cluster configuration. kubelet is optimized to avoid mount storm, it will randomly pick one from the endpoints to mount. If this host is unresponsive, the next Gluster host in the endpoints is automatically selected.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup [GlusterFS cluster with Heketi](https://github.com/gluster/gluster-kubernetes) for dynamic provisioning

2. Create StorageClass

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: gfs-cluster-storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://x.x.x.x:port"
  restuser: "admin"
  secretNamespace: "default"
  secretName: "heketi-secret"
allowVolumeExpansion: true
```

3. Create PVC

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "gfs-cluster-storage"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
```

4. This creates an Endpoints object like this

```
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: 2018-04-16T07:08:19Z
  labels:
    gluster.kubernetes.io/provisioned-for-pvc: my-claim
  name: glusterfs-dynamic-my-claim
  namespace: default
  resourceVersion: "27144006"
  selfLink: /api/v1/namespaces/default/endpoints/glusterfs-dynamic-my-claim
  uid: f151641d-4144-11e8-8a1b-42010a9c0067
subsets:
- addresses:
  - ip: 10.0.0.1
  - ip: 10.0.0.2
  - ip: 10.0.0.3
  ports:
  - port: 1
    protocol: TCP
```

5. Mount the PVC in any deployment or similar

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: my-vol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: my-vol
        persistentVolumeClaim:
          claimName: my-claim
```

6. Execute bash/sh on one of the pods and run `mount` or `df -h` to check which endpoint was mounted

`kubectl exec -it nginx-deployment-xxxx sh`
`df -h`

7. Notice that the first IP is always used as a mount point for all pods

In this case 10.0.0.1 is always used as endpoint because it's the first IP in the Endpoints object.

**Anything else we need to know?**:

By manually editing the Endpoints object I could change which IP was listed first and use that to control which endpoint was mounted in the containers. To do that I had to assign different ports to each IP like this:

```
subsets:
- addresses:
  - ip: 10.0.0.1
  ports:
  - port: 999
    protocol: TCP
- addresses:
  - ip: 10.0.0.2
  ports:
  - port: 55
    protocol: TCP
- addresses:
  - ip: 10.0.0.3
  ports:
  - port: 1
    protocol: TCP

```

It still didn't make it select a random endpoint though.

I found [issue #13125](https://github.com/kubernetes/kubernetes/issues/13125), which looks similar but was closed long ago.

It also mentions [PR #13807](https://github.com/kubernetes/kubernetes/pull/13807/), which changed how endpoints are selected. 

I suspect that the code which finds a suitable endpoint always iterates through the list of possible endpoints in the same order.

**Environment**:
- Kubernetes version (use `kubectl version`): Tested on servers running 1.9.4 + 1.9.6

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-27T00:13:02Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.0", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-03-21T19:01:20Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: Google Cloud
- OS (e.g. from /etc/os-release): Container-Optimized OS 

```
BUILD_ID=10323.12.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=2d7de0bde20ae17f934c2a2e44cb24b6a1471dec
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=65
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=65
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```

- Kernel (e.g. `uname -a`): 

```
Linux gke-dev-cluster-pool-dev-129010f4-2z63 4.4.111+ #1 SMP Thu Feb 1 22:06:37 PST 2018 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
```
