### ISSUE TITLE
Unable to create a deployment with NGC's images

### ISSUE THREAD

**Issue by DeNgKee** [kubernetes/kubernetes#62687]
/kind bug

**What happened**:
I succeed to deploy a deployment when i used the image of  gcr.io/tensorflow/tensorflow:latest-gpu, but i failed with the image of nvcr.io/nvidia/tensorflow:18.03-py3.
For the second condition ,my pod created the container and started the container when i created a deployment, but it back-off restarting failed conatiner after  a few sec.

```
Events:
  Type     Reason                 Age                     From               Message
  ----     ------                 ----                    ----               -------
  Normal   Scheduled              1m                      default-scheduler  Successfully assigned tf-notebook-58754b4c9-lcnhl to node1
  Normal   SuccessfulMountVolume  10s                     kubelet, node1     MountVolume.SetUp succeeded for volume "mnist-storage"
  Normal   SuccessfulMountVolume  10s                     kubelet, node1     MountVolume.SetUp succeeded for volume "default-token-lt4vm"
  Normal   Pulled                 <invalid> (x4 over 9s)  kubelet, node1     Container image "nvcr.io/nvidia/tensorflow:18.03-py3" already present on machine
  Normal   Created                <invalid> (x4 over 9s)  kubelet, node1     Created container
  Normal   Started                <invalid> (x4 over 9s)  kubelet, node1     Started container
  Warning  BackOff                <invalid> (x7 over 7s)  kubelet, node1     Back-off restarting failed container
```
the YAML file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow
  labels:
    app: tensorflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow
  template: 
    metadata:
      labels:
        app: tensorflow
    spec:
      containers:
      - name: tensorflow
        image: 'nvcr.io/nvidia/tensorflow:18.03-py3'
        command: ["/bin/bash"]
        volumeMounts:
         - name: mnist-storage
           mountPath: /pred_res/
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: mnist-storage
        hostPath:
          path: /pred_res
```

**What you expected to happen**:
I expect that after my pod started the container ,i can use command 'kubectl exec' to manipulate the container .
**How to reproduce it (as minimally and precisely as possible)**:
Create the deployment  with my YAML file.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.10.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):ubuntu16.04
- Kernel (e.g. `uname -a`):4.4.0-116-generic
- Install tools:
- Others:
