### ISSUE TITLE
HTTP liveness and readiness probe failed on multiple replicas

### ISSUE THREAD

**Issue by xiaolanz** [kubernetes/kubernetes#62798]
/kind bug

**What happened**:
I create probes in my GCP endpoints deployment. The containers start properly when replica is set 1. However, when replica is > 1. Some pods failed with connection to probes: 

  Warning  Unhealthy              9m    kubelet, gke-joy-test-default-pool-cf9a73c3-gc8b  Liveness probe failed: Get http://10.44.5.14:9001/healthz: dial tcp 10.44.5.14:9001: getsockopt: connection refuse

My full yaml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-hello-probe
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: grpc-hello-probe
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9000",
          "--http_port=9001",
          "--backend=grpc://127.0.0.1:50051",
          "--service=hellogrpc.endpoints.xiaolan-api-codelab.cloud.goog",
          "--version=2018-03-23r0",
          "--healthz=healthz",
        ]
        ports:
          - containerPort: 9000
          - containerPort: 9001
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9001
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9001
      - name: java-grpc-hello
        image: gcr.io/xiaolan-api-codelab/java-grpc-hello:1.0
        ports:
          - containerPort: 50051
```

**What you expected to happen**:
Expect all pods should succeed with probes.

**How to reproduce it (as minimally and precisely as possible)**:
Create a deployment like the above. Make sure to replace images.

**Anything else we need to know?**:
No.

**Environment**:
GKE
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.4-gke.1", GitCommit:"10e47a740d0036a4964280bd663c8500da58e3aa", GitTreeState:"clean", BuildDate:"2018-03-13T18:00:36Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
GCP
- OS (e.g. from /etc/os-release):

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xiaolanz** [comment]
Pods are well after a few minutes. It's due to bootstrap unavailability. 
adding initialDelaySeconds resolves the problem

**Comment by sbsends** [comment]
@xiaolanz please help!!! I would like to use ESP behind GCE-Ingress (cert-manager and Let's Encrypt). I have spent hours trying to diagnose the problem.

@freeformz @brosner @gnufied 

## Ingress
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tensortask-web
  annotations:
    kubernetes.io/ingress.global-static-ip-name: api-ip
  labels:
    app: tensortask-api
spec:
  backend:
    serviceName: tensortask-service
    servicePort: 8080
```
## Service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: tensortask-service
  labels:
    app: tensortask-api
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: tensortask-api
    tier: web
```
## Deployment
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensortask-web
  labels:
    app: tensortask-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tensortask-api
        tier: web
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9000",
          "-a", "grpc://127.0.0.1:8000",
          "-s", "api.tensortask.com",
          "--rollout_strategy", "managed",
          "--healthz="
          ]
        ports:
          - containerPort: 9000

      - name: server
        image: gcr.io/tensortask/server:latest
        ports:
          - containerPort: 8000
```
