### ISSUE TITLE
kubelet times-out when mounting a volume

### ISSUE THREAD

**Issue by venilnoronha** [kubernetes/kubernetes#62817]
/kind bug

**What happened**:
On creating a stateful-set, the `kubelet` times-out while mounting a volume. The volume is attached and PVC bounded; however, `VolumesInUse` and `VolumesAttached` aren't populated.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Use the following yml configuration to create a StorageClass.
```yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ci-storage
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: zeroedthick
```
Use the following configuration to create a StatefulSet.
```yml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sample-statefulset
spec:
  serviceName: "pv-ex-svc"
  replicas: 1
  template:
    metadata:
      labels:
        app: pv-ex
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pv-ex
        image: pcfkubo/persistent-example
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: www
          mountPath: /usr/share/pv-ex
        env:
        - name: LOG_FILE
          value: /usr/share/pv-ex/log.txt
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ci-storage
      resources:
        requests:
          storage: 1Gi
```

**Anything else we need to know?**:

`kubelet describe pods` warns about a mount failure:
```
Warning  FailedMount            7m    kubelet, kubernetes-node3  Unable to mount volumes for pod "sample-statefulset-0_default(db123759-434f-11e8-8cb0-00505691a640)": timeout expired waiting for volumes to attach/mount for pod "default"/"sample-statefulset-0". list of unattached/unmounted volumes=[www]
```

The [controller-manager](https://github.com/vmware/kubernetes/blob/ss-logs/logs/kube-controller-manager_0.log), [kubelet](https://github.com/vmware/kubernetes/blob/ss-logs/logs/8e47a8f1073f3d67a65d8e51fe9a85083a4d8a2085ac3548cc551e6d873c5634-json.log) and other logs can be found [here](https://github.com/vmware/kubernetes/tree/ss-logs/logs).

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.7-beta.0.113+dd5e1a2978fd0
- Cloud provider or hardware configuration: vsphere
- OS (e.g. from /etc/os-release): VMware Photo 1.0
- Kernel (e.g. `uname -a`): 4.4.8-esx
- Install tools: 
- Others:
