### ISSUE TITLE
kubectl port-forward service/<service-name> with --pod-running-timeout option doesn't work as expected

### ISSUE THREAD

**Issue by pragyamehta** [kubernetes/kubernetes#62821]
I am running 
kubectl port-forward service/servicename localPort:remotePort --pod-running-timeout=5m
on a newly created service.

**Expectation** : I would expect that the call would hang and "wait" till at least one pod is in Running state till a period of 5 minutes and then attempt to port forward. If after 5 minutes, no pod is "Running", the call will fail.

**Observation** : The call returns almost immediately with the below error
error: unable to forward port because pod is not running. Current status=Pending

My understanding is that --pod-running-timeout is not working as expected

**kubectl version output**: 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Repro** : An easy way to reproduce this would be on a clean cluster since I have noticed that the very first pod takes longer to reach "running state" than subsequent ones.

**Comment by pragyamehta** [comment]
@kubernetes/sig-cli-bugs

**Comment by MHBauer** [comment]
/remove-lifecycle stale
/lifecycle froze
This flag in combination with this command needs clarification.

**Comment by hacst** [comment]
@MHBauer Clarification would definitely be helpful.

Documentation says:
```
$ kubectl help port-forward
...
Options:
    ...
     --pod-running-timeout=1m0s: The length of time (like 5s, 2m, or 3h, higher than zero) to wait until at least one pod is running
...
```
But when I try to use it with a pending pod:
```
$ kubectl get all
NAME           READY   STATUS    RESTARTS   AGE
pod/mytest   0/1     Pending   0          104s
```
```
$ time kubectl port-forward --pod-running-timeout=10m mytest 1234:1234
error: unable to forward port because pod is not running. Current status=Pending

real	0m0,374s
```
No waiting is done.

**Comment by nneram** [comment]
@MHBauer This flag is used by kubectl for timeout when their is no pod at all. It's calling a function that is attaching a pod given an object (here pod name I guess), but if the pod doesn't exist their is a timeout with a default value:

https://github.com/kubernetes/kubernetes/blob/f06baf9f36a5d973ad84779bbca44f2fb4a93483/staging/src/k8s.io/kubectl/pkg/cmd/portforward/portforward.go#L97

https://github.com/kubernetes/kubernetes/blob/f06baf9f36a5d973ad84779bbca44f2fb4a93483/staging/src/k8s.io/kubectl/pkg/cmd/portforward/portforward.go#L321

https://github.com/kubernetes/kubernetes/blob/f06baf9f36a5d973ad84779bbca44f2fb4a93483/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/attachablepodforobject.go#L32

So if a pod exist the attachment is working fine otherwise it's waiting for a pod until timeout. Then you have the exit when the pod is in pending state: 
https://github.com/kubernetes/kubernetes/blob/f06baf9f36a5d973ad84779bbca44f2fb4a93483/staging/src/k8s.io/kubectl/pkg/cmd/portforward/portforward.go#L394-L396

But the option `--pod-running-timeout` is not link to that state and work as expected: 
Here a service without running pod : 
```
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  clusterIP: 10.96.141.131
  clusterIPs:
  - 10.96.141.131
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: test
    app.kubernetes.io/name: test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
You will have: 

```
/usr/bin/time -p kubectl -n default port-forward svc/test 8001:3000 --pod-running-timeout=5s
error: timed out waiting for the condition
Command exited with non-zero status 1
real 5.61
user 0.17
sys 0.08
```

All that to say that it will be nice to have a new flag for the pending state like `--pod-running-timeout` :)
