### ISSUE TITLE
Add new properties to Kubernetes Volume

### ISSUE THREAD

**Issue by wenhaocs** [kubernetes/kubernetes#62869]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

> Uncomment only one, leave it on its own line:
>
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

I intend to add new properties to Kubernetes Volume so I can specify the storage requirements and scheduler my pods according to those requirements.
For example, my new yaml may look like this:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: test-volume
  volumes:
  - name: test-volume
    **MYVOLUME**
      **Capacity: 10GB**
      **Bandwidth: 100MB/s**
      **Sharable: true**
      ...
```
When scheduling a pod, I should be able to get the exact value of these properties from the **pod.Spec.Volumes** struct, so that I can define my new predicate and priority functions to scheduler that pod according to these new properties. 

Can anybody shed a light on what the general process of adding new properties to k8s volume is? Which components should I modify?

@kubernetes/sig-storage-feature-requests
