### ISSUE TITLE
How to prevent DaemonSet pods being evicted from nodes which have disk pressure?

### ISSUE THREAD

**Issue by mdianjun** [kubernetes/kubernetes#63005]
How to prevent DaemonSet pods being evicted from nodes which have disk pressure?
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: centos-daemon
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: centos-daemon
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''  //HERE
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoExecute
        key: node.kubernetes.io/disk-pressure   //HERE
        operator: Exists
      nodeSelector:
        kubernetes.io/hostname: kc-bcc-pod24-10-196-108-11.hadoop.jd.local
      terminationGracePeriodSeconds: 0
      priorityClassName: system-cluster-critical   //HERE
      containers:
      - name: centos
        image: repo.jd.local/centos/centos-mdj:1.2
        command: ["sleep", "1000000000"]
        ports:
        - name: ssh
          containerPort: 22
        - name: web
          containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 512Mi
```

I had tried 3 ways:

1. critical pod
2. TaintBasedEvictions=true,TaintNodesByCondition=true
3. priorityClass

Feature gates had been configured on apiserver, controller-manager, scheduler, kubelet:
`ExperimentalCriticalPodAnnotation=true,LocalStorageCapacityIsolation=true,PersistentLocalVolumes=true,MountPropagation=true,VolumeScheduling=true,CustomPodDNS=true,PodPriority=true,TaintBasedEvictions=true,TaintNodesByCondition=true`

But all of them were useless.

**Comment by cu12** [comment]
Facing the same issue with the same things tried. 

@mdianjun did you find the solution?

**Comment by Huang-Wei** [comment]
@mdianjun @cu12 which k8s version are you running? and which feature-gates did you enable, on which components?

**Comment by Huang-Wei** [comment]
By default, deamonset pods would be applied with following 2 `NoExecute` tolerations:

```yaml
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
```

@k82cn nodelifecyclemanger doesn't apply `disk-pressure/NoExecute` (only `disk-pressure/NoSchedule`) taint to node, does it?
