### ISSUE TITLE
StatefulSets Endpoint  remove delayed   when delete one pod

### ISSUE THREAD

**Issue by piaoyu** [kubernetes/kubernetes#63087]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**: StatefulSets Endpoint remove delayed when delete one pod

**What you expected to happen**: StatefulSets Endpoint  remove immediately  when delete one pod

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f  nginx-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-stateful
  namespace: test
spec:
  ports:
    - name: export-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: "nginx-stateful"
  clusterIP: 192.168.1.30
```  

kubectl apply -f  nginx-stateful.yaml
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: nginx-stateful
  name: nginx-stateful
  namespace: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-stateful
  serviceName: nginx-stateful
  template:
    metadata:
      labels:
        app: nginx-stateful
    spec:
        #automountServiceAccountToken: false
      containers:
      - image: docker-hub.ucweb.com:5000/test/nginx:1.7.9
        imagePullPolicy: IfNotPresent
        name: nginx-stateful
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
      - image: docker-hub.ucweb.com:5000/busybox:0.1
        imagePullPolicy: IfNotPresent
        name: busy
        args:
          - sleep
          - "10000000"
```          

#kubectl delete pods  nginx-stateful-0 -n test
pod "nginx-stateful-0" deleted

#kubectl get pods -n test
NAME               READY     STATUS        RESTARTS   AGE
nginx-stateful-0   2/2       Terminating   0          1h
nginx-stateful-1   2/2       Running       0          1h
nginx-stateful-2   2/2       Running       0          1h
nginx-stateful-3   2/2       Running       0          1h
nginx-stateful-4   2/2       Running       0          1h

[root@sz-kpi-s3-252 /etc/kubernetes/manifests]
#kubectl get ep  -n test --watch
NAME             ENDPOINTS                                                       AGE
nginx-stateful   10.151.98.21:80,10.151.99.181:80,10.151.99.182:80 + 2 more...   1h

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
#kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2018-04-24T22:14:26Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2018-04-24T22:14:26Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 7.2
- Kernel (e.g. `uname -a`):
[root@sz-kpi-s3-252 /etc/kubernetes/manifests]
#uname -a
Linux sz-kpi-s3-252 3.10.0-327.ali2010.rc7.alios7.x86_64 #1 SMP Thu Jun 29 21:45:21 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: hypekube 
- Others:
