### ISSUE TITLE
Can not mount flex volumes in origin 3.9

### ISSUE THREAD

**Issue by mlbiam** [kubernetes/kubernetes#63175]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

I'm trying to deploy a cifs flex volume (https://github.com/andyzhangx/kubernetes-drivers/blob/master/flexvolume/cifs/cifs) into Origin 3.9 on CentOS 7.  Once deployed the node didn't recognize it with the following error (on level 8):

```
Apr 25 21:33:55 node origin-node: W0425 21:33:55.420302    1460 driver-call.go:145] FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs/azure-cifs, args: [init], error: fork/exec /usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs/azure-cifs: no such file or directory, output: ""
Apr 25 21:33:55 node origin-node: E0425 21:33:55.420351    1460 plugins.go:548] Error dynamically probing plugins: Error creating Flexvolume plugin from directory azure-cifs, skipping. Error: unexpected end of JSON input
```

 until it was copied from ```/usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs/cifs``` to ```/usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs/azure-cifs```.  The node still refused to mount the volume however

**What you expected to happen**:

The flex driver to be recognized and the mount to be created

**How to reproduce it (as minimally and precisely as possible)**:

On the worker node
```
$ mkdir /usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs
$ cd /usr/libexec/kubernetes/kubelet-plugins/volume/exec/azure-cifs
$ wget -O cifs https://raw.githubusercontent.com/andyzhangx/kubernetes-drivers/master/flexvolume/cifs/cifs
$ chmod a+x cifs
```

Create a persistent volume referencing the flex volume:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cifs-flexvol
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/cifs"
    secretRef:
      name: cifscreds
    options:
      source: "//adfs.ent2k12.domain.com/mmosley-share"
      mountOptions: "vers=3.0,dir_mode=0777,file_mode=0777"
```

Create the required secret

Create the PVC in the project
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cifs-flexvol
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-cifs-flexvol
  storageClassName: ""
```

Create pod referencing persistent volume claim

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-04-11T20:47:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-04-11T20:47:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
VMs on KVM
- OS (e.g. from /etc/os-release): ```CentOS Linux release 7.4.1708 (Core) ```
- Kernel (e.g. `uname -a`): ```Linux node.horizon.lan 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```
- Install tools: ansible
- Others:
