### ISSUE TITLE
Pods on different nodes mount Ceph RBD PVC stuck on ContainerCreating

### ISSUE THREAD

**Issue by xiaoxubeii** [kubernetes/kubernetes#63183]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
When use ceph as storageclass, i set accessModes:  ReadOnlyMany, and create pods using the claim, only one pod would be running and the others on different nodes would get stuck on ContainerCreating. But if the pods are all on same node, it works fine. 

**What you expected to happen**:
Pods on different nodes can mount ceph rbd volume.

**How to reproduce it (as minimally and precisely as possible)**:

```
# cat pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ceph-claim
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.2
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): 3.10.0-327.18.2.el7.x86_64
- Kernel (e.g. `uname -a`): CentOS Linux release 7.2.1511 (Core)
- Install tools: kubeadm
- Others:
