### ISSUE TITLE
/run/secrets/kubernetes.io/serviceaccount is not exited in docker container

### ISSUE THREAD

**Issue by lwsbox** [kubernetes/kubernetes#63389]
**Kubernetes version** : V1.9.1
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

**Docker image**: centos:7.3.1611 （the official image）
You can found in https://hub.docker.com/_/centos/

**Yaml:** 
---
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test1
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: test1
    spec:
      nodeSelector:
        node: "1"
      hostname:
        compute4
      hostNetwork: true
      containers:
      - name: test-service-account
        image: centos:7.3.1611
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - ALL
          privileged: true
        env:
        - name: container
          value: docker
        command:
          - "/usr/sbin/init"
        volumeMounts:
          - name: sys-ctl
            mountPath: /sys/fs/cgroup
            readOnly: true
      volumes:
      - name: sys-ctl
        hostPath:
         path: /sys/fs/cgroup
```

**kubectl  describe:**
```
Name:           test1-8564b59998-xn2jl
Namespace:      default
Node:           compute4/172.18.135.2
Start Time:     Thu, 03 May 2018 05:40:44 +0000
Labels:         app=test1
                pod-template-hash=4120615554
Annotations:    <none>
Status:         Running
IP:             172.18.135.2
Controlled By:  ReplicaSet/test1-8564b59998
Containers:
  test-service-account:
    Container ID:  docker://e781f9bb84bf13ee953cf8437ecf746fb7b9719034b72f3f108f451f3bb6993c
    Image:         centos:7.3.1611
    Image ID:      docker://sha256:66ee80d59a68047e6eac9fc10cbe698f15bd369bd8bbd512857bdd65cdecf601
    Port:          <none>
    Command:
      /usr/sbin/init
    State:          Running
      Started:      Thu, 03 May 2018 05:40:47 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      container:  docker
    Mounts:
      /sys/fs/cgroup from sys-ctl (ro)
      **/var/run/secrets/kubernetes.io/serviceaccount from default-token-z8kp8 (ro)**
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  sys-ctl:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/cgroup
    HostPathType:  
  default-token-z8kp8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-z8kp8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  node=1
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age   From               Message
  ----    ------                 ----  ----               -------
  Normal  Scheduled              5m    default-scheduler  Successfully assigned test1-8564b59998-xn2jl to compute4
  Normal  SuccessfulMountVolume  5m    kubelet, compute4  MountVolume.SetUp succeeded for volume "sys-ctl"
  Normal  SuccessfulMountVolume  5m    kubelet, compute4  MountVolume.SetUp succeeded for volume "default-token-z8kp8"
  Normal  Pulled                 5m    kubelet, compute4  Container image "centos:7.3.1611" already present on machine
  Normal  Created                5m    kubelet, compute4  Created container
  Normal  Started                5m    kubelet, compute4  Started container

```

[ kubectl get serviceaccount]
NAME      SECRETS   AGE
default   1         6d

We enter the container（docker exec -it conatinerID bash）, found that /var/run/secrets/kubernetes.io/serviceaccount is not existed.

Is this the centos image's problem?
