### ISSUE TITLE
`kubectl config set-credentials` do not support using certificate data and key data

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#63435]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind feature

**What happened**:

```
root@gyliu-ubuntu-1:~/multicluster# kubectl config set-credentials --help
Sets a user entry in kubeconfig

Specifying a name that already exists will merge new fields on top of existing values.

  Client-certificate flags:
  --client-certificate=certfile --client-key=keyfile

  Bearer token flags:
    --token=bearer_token

  Basic auth flags:
    --username=basic_user --password=basic_password

Bearer token and basic auth are mutually exclusive.

Examples:
  # Set only the "client-key" field on the "cluster-admin"
  # entry, without touching other values:
  kubectl config set-credentials cluster-admin --client-key=~/.kube/admin.key

  # Set basic auth for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --username=admin --password=uXFGweU9l35qcif

  # Embed client certificate data in the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --client-certificate=~/.kube/admin.crt --embed-certs=true

  # Enable the Google Compute Platform auth provider for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --auth-provider=gcp

  # Enable the OpenID Connect auth provider for the "cluster-admin" entry with additional args
  kubectl config set-credentials cluster-admin --auth-provider=oidc --auth-provider-arg=client-id=foo
--auth-provider-arg=client-secret=bar

  # Remove the "client-secret" config value for the OpenID Connect auth provider for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --auth-provider=oidc --auth-provider-arg=client-secret-

Options:
      --auth-provider='': Auth provider for the user entry in kubeconfig
      --auth-provider-arg=[]: 'key=value' arguments for the auth provider
      --client-certificate='': Path to client-certificate file for the user entry in kubeconfig
      --client-key='': Path to client-key file for the user entry in kubeconfig
      --embed-certs=false: Embed client cert/key for the user entry in kubeconfig
      --password='': password for the user entry in kubeconfig
      --token='': token for the user entry in kubeconfig
      --username='': username for the user entry in kubeconfig

Usage:
  kubectl config set-credentials NAME [--client-certificate=path/to/certfile] [--client-key=path/to/keyfile]
[--token=bearer_token] [--username=basic_user] [--password=basic_password] [--auth-provider=provider_name]
[--auth-provider-arg=key=value] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

From above, we can see I have to use file name for certificate and key.
```
--client-certificate='': Path to client-certificate file for the user entry in kubeconfig
--client-key='': Path to client-key file for the user entry in kubeconfig
```

If I want to use content string of the certificate and key, I have to update `$HOME/.kube/config` manually by changing `client-certificate` to `client-certificate-data`, and change `client-key` to `client-key-data`.

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://9.111.255.21:8001
  name: myistio.icp
contexts:
- context:
    cluster: myistio.icp
    namespace: default
    user: admin
  name: myistio.icp-context
current-context: myistio.icp-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    as-user-extra: {}
    client-certificate-data: <xxxx>
    client-key-data: <xxxx>
```

/sig security
