### ISSUE TITLE
kube-dns deployment keeps being reset by some means

### ISSUE THREAD

**Issue by chrissound** [kubernetes/kubernetes#63443]
dns.yaml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-dns
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: kube-dns
  template:
    spec:
      containers:
      - name: dnsmasq
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
      - name: kubedns
        resources:
          requests:
            cpu: 100m
```

If I patch the kube-dns deployment with:
`kubectl patch --namespace=kube-system deployment kube-dns --patch "$(cat dns.yaml)"`

This works, new pods get scheduled with the updated resources.

However after a while the deployment seems to reset to the previous resource constraints. Is there any way I can disable this? 

I appreciate messing around with the resource requirements of kube-dns can be risky - but I'm willing to investigate this. As it'll allow me to run more pods on a small 2 node cluster. As a work around  I can potentially lower the cpu requests of my own pods, but this potentially means schedule too many pods on a node if I decide to scale up to a larger cluster size...

I'd just like to understand where this behavior is coming from. Maybe GCP?
