### ISSUE TITLE
Getting delete request of 'empty' resources when a namespace is deleted

### ISSUE THREAD

**Issue by the-redback** [kubernetes/kubernetes#63529]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**: When a namespace is deleted, it sends delete requests to `empty` object of CRD in that namespace. By `empty` resource I meant, the name of the resource is empty. Although, there is no CRD object in that namespace.

In details, I have implemented a Validating webhook for a CRD. When I delete any namespace, the webhook is getting delete requests of `""` item in that namespace. The requests body I received while deleting namespace `demo`:

```yaml
{
   "uid": "e68f60b0-5286-11e8-a844-08002799670e",
   "kind": {
      "group": "kubedb.com",
      "version": "v1alpha1",
      "kind": "MongoDB"
   },
   "resource": {
      "group": "kubedb.com",
      "version": "v1alpha1",
      "resource": "mongodbs"
   },
   "namespace": "demo",
   "operation": "DELETE",
   "userInfo": {
      "username": "system:serviceaccount:kube-system:namespace-controller",
      "uid": "68d94cdd-51d1-11e8-9220-08002799670e",
      "groups": [
         "system:serviceaccounts",
         "system:serviceaccounts:kube-system",
         "system:authenticated"
      ]
   },
   "object": null,
   "oldObject": null
}
```
At other times, the general request body is: 

```yaml
{
   "uid": "e51c6d1f-2117-11e8-a0a8-080027af2d87",
   "kind": {
      "group": "kubedb.com",
      "version": "v1alpha1",
      "kind": "MongoDB"
   },
   "resource": {
      "group": "kubedb.com",
      "version": "v1alpha1",
      "resource": "mongodbs"
   },
   "name": "mongo-demo",
   "namespace": "demo",
   "operation": "DELETE",
   "userInfo": {
      "username": "minikube-user",
      "groups": [
         "system:masters",
         "system:authenticated"
      ]
   },
   "object": null,
   "oldObject": null
}
```

**What you expected to happen**: When there is no object in that namespace, *no delete requests of `empty` objects*?

**How to reproduce it (as minimally and precisely as possible)**:
- Create a Validating webhook for a CRD.
- Print the request body.
- Create a namespace `demo`
- Now delete the namespace `demo`
- There should a delete request of `empty` resources.

**Anything else we need to know?**: 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `Desktop PC, Ram: 16GB, Processor: Intel® Core™ i3-4150 CPU @ 3.50GHz × 4 `
- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`): `Linux AppsCode 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `minikube`
- Others:
```yaml
$ minikube version
minikube version: v0.26.1
```
