### ISSUE TITLE
externalName

### ISSUE THREAD

**Issue by drmillan** [kubernetes/kubernetes#63543]
/kind feature

While configuring a Service with ExternalName, I expected it could be possible to use a value from a config map for the externalName property, but it expects only a string, forcing a hardcoded value.

What I think that could be a nice feature
```yaml
apiVersion: "v1"
kind: "Service"
metadata:
  name: rds-service
spec:
  type: ExternalName
  externalName: 
    valueFrom:
      configMapKeyRef:
        name: config
        key: endpoint.name
```
