### ISSUE TITLE
kind:deployment securitycontext and Ceph PVC

### ISSUE THREAD

**Issue by hbajaj2** [kubernetes/kubernetes#63555]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
securityContext attribute is not available for kind:deployment, requirement is to claim Ceph hosted PVC on a non-root container.
**What you expected to happen**:
non-root user should be able write on a volume claim, at the moment fsGroup feature of securityContext is only confined to kind:Pod
**How to reproduce it (as minimally and precisely as possible)**:
Use kind: deployment and securityContext doesn't work under containers, tried using it for fsGroup and kubectl create fails.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.9.2
- Cloud provider or hardware configuration:on-premise Kubernetes setup
- OS (e.g. from /etc/os-release):RHEL 7
- Kernel (e.g. `uname -a`):3.10.0-693.17.1
- Install tools:
- Others:

**Comment by liggitt** [comment]
the securityContext attribute is part of deployment... it is possible you have it at the wrong level in your deployment manifest. can you include your deployment manifest?

```
$ kubectl explain deployment.spec.template.spec.securityContext
KIND:     Deployment
VERSION:  extensions/v1beta1

RESOURCE: securityContext <Object>

DESCRIPTION:
     SecurityContext holds pod-level security attributes and common container
     settings. Optional: Defaults to empty. See type description for default
     values of each field.

     PodSecurityContext holds pod-level security attributes and common container
     settings. Some fields are also present in container.securityContext. Field
     values of container.securityContext take precedence over field values of
     PodSecurityContext.

FIELDS:
   fsGroup	<integer>
     A special supplemental group that applies to all containers in a pod. Some
     volume types allow the Kubelet to change the ownership of that volume to be
     owned by the pod: 1. The owning GID will be the FSGroup 2. The setgid bit
     is set (new files created in the volume will be owned by FSGroup) 3. The
     permission bits are OR'd with rw-rw---- If unset, the Kubelet will not
     modify the ownership and permissions of any volume.

...
```

**Comment by dreadnautxbuddha** [comment]
Hi @liggitt , securityContext isn't working for my deployments either. Here's the spec:

**Deployment:**
```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: apiserver
  namespace: development
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
      tier: apiserver
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        tier: apiserver
    spec:
      containers:
      - name: php-app
        image: dockerfile-update:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Never
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html"
            name: local-volume
      imagePullSecrets:
        - name: dockercred
      volumes:
      - name: local-volume
        persistentVolumeClaim:
          claimName: local-pv-claim
      securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
```

**PV**
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  annotations:
    pv.beta.kubernetes.io/uid: "1000"
    pv.beta.kubernetes.io/gid: "1000"
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
#   claimRef:
#     namespace: development
#     name: local-pv-claim
  storageClassName: local-storage
  local:
    path: <my app path>
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
```

**PVC**
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pv-claim
spec:
  storageClassName: local-storage
  volumeName: local-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
```

**StorageClassName**
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

Originally, I was trying to setup permissions for my hostPath volume, but this is where I am now
