### ISSUE TITLE
kube-proxy cannot get real ip of client

### ISSUE THREAD

**Issue by y0299** [kubernetes/kubernetes#63581]
kube-proxy cannot get real ip of client. follow the reference : 
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/
my service config like that:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: haproxy-filebeat-service
  namespace: dop-v2
  annotations:
   service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  selector:
    app: haproxy-filebeat
  ports:
    - name: http
      protocol: TCP
      port: 8001
    - name: https
      protocol: TCP
      port: 443
    - name: stats
      protocol: TCP
      port: 1936
  type: NodePort
```
**but i also get the load-balancer ip, not the real ip  of client. Does some configuration wrong in my environment?**

**Environment**:
- Kubernetes version (use `kubectl version`): 
   v1.8.4
- Cloud provider or hardware configuration: 
   no
- OS (e.g. from /etc/os-release):
```yaml
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
  Linux node39 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
