### ISSUE TITLE
Using ceph storageclass can't create PersistentVolumeClaim 

### ISSUE THREAD

**Issue by Tizeen** [kubernetes/kubernetes#63648]
**What happened**:

When i use ceph rbd storageclass create persistent volume claim, it always in `pending` status, `kubectl describe ` get follow event:

```
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  ProvisioningFailed  9s    persistentvolume-controller  Failed to provision volume with StorageClass "ceph-storage": failed to create rbd image: exit status 1, command output: 2018-05-10 08:33:15.897889 7fad4ac81780 -1 did not load config file, using default settings.
rbd: extraneous parameter --image-feature
```

ceph-storageclass-secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: ceph-storageclass-secret
type: kubernetes.io/rbd
data:
  key: QVFBOEt1QmE3Qm0vSGhBQWtFQlFZSkFKQmxYcFZoeXJSdTM2Vnc9PQ==
```

storageclass yaml config:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-storage
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.244.4.148:6789,10.244.4.136:6789,10.244.4.143:6789
  adminId: admin
  adminSecretName: ceph-storageclass-secret
  pool: rbd
  userId: admin
  userSecretName: ceph-storageclass-secret
```

ceph-storage-pvc yaml:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

**Environment**:
- Kubernetes version: v1.8.2+coreos.0
- OS: CentOS 7.4
- Kernel: 3.10.0-693.11.6.el7.x86_64
- Install tools: kubespray

Thanks guys.
