### ISSUE TITLE
Pod restartPolicy is Never

### ISSUE THREAD

**Issue by yph152** [kubernetes/kubernetes#63645]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

**What happened**:

My configuration file is as follows：
```
apiVersion: v1
kind: Pod
metadata:
  name: kubeflow-watch
  namespace: kube-system
spec:
  restartPolicy: Never
  containers:
  - image: kubeflow-admin:watch
    name: kubeflow-admin
    command:
    - /bin/sh
    - -c
    - /kubeflow-ad
    env:
    - name: STORAGE_MANAGER
      value: "http://192.168.21.165:30301"
    resources:
       limits:
         cpu: "1"
         memory: "1024Mi"
       requests:
         cpu: "0.1"
         memory: "100Mi"
```
The restartPolicy I set is Never, but when it's done failed, use kubectl to display：
```
kubeflow-watch                                                    0/1       Error      0          41m
```
When I use 1.8, it is invisible
```
[root@c720v197]:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
