### ISSUE TITLE
Managed ca-certs

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#63726]
/kind feature

**What happened**:

A common requirement of container base images is to provide ca-certs. For example, many of our addons are based on alpine purely to install the `ca-certificates` package.

I believe this is an anti-pattern:

- Revoking or adding new ca-certificates requires rebuilding & redeploying all workloads (that need it)
- If my organization wants to add our internal CA, or decides we don't trust a "standard" CA, we need to build our own images.
- There is poor visibility into which ca-certs are trusted across the cluster.

A related problem is how to mount the Kubernetes root CA into pods. See https://github.com/kubernetes/community/pull/1973 for a discussion.

**What you expected to happen**:

There is an opportunity for Kubernetes to provide some value-add here with support for cluster-managed root CA bundles. This is already feasible to some extent by putting the `ca-certificates.crt` bundle in a config map and mounting it into containers at `/etc/ssl/`, but there are some shortcomings to this approach:

1. No cross-namespace config map references, so the CM needs to be cloned into every namespace
2. Every pod-spec needs to be modified to mount the ca-certs.
3. Lack of standardization means most containers will still build in the certs

An ideal solution would:

1. Have a single cluster-scoped copy of the ca-cert data
2. Custom certs could easily be added as additional resources or k-v pairs
3. Certs are automatically injected (optionally disabled, a la automountServiceAccountToken)
4. Clusters include ca-certs by default (either Kubernetes provides a bundle, or load the master's host ca-certificates on startup)

I'm not sure whether a new resource type (or CRD) is necessary here, or if ConfigMaps (either via x-namespace references or a new ClusterConfigMap) would be sufficient.

WDYT?

/sig auth

**Comment by tallclair** [comment]
@kksriram I was thinking more about the general case, where an application needs the ability to connect to an arbitrary set of servers on the public internet. It may be the case that this is actually a relatively small use case, in which case the discussion of cluster-level config maps & automounting doesn't make sense. Perhaps we don't need to make any changes, and just promote ca-certs through namespace-level config maps as a best practice?

**Comment by mikedanese** [comment]
Since we want these to be global, can we consider a dedicated type in the certificates.k8s.io API Group? Strawman:

In certificates.k8s.io:
```go
type CertificateBundle struct {
  // Certificates is an array of DER encoded certificates that make up the bundle.
  Certificates [][]byte
}
```

Then create a VolumeProjection:
```go
type CertificateBundleProjection string {
  Path string
  CertificateBundles []string
}
```

To construct the volume, kubelet PEM encodes all certificates in all referenced certificate bundles and coalesces them into a single file at `Path`. I could see a GKE cluster wanting a bundles for:
* The cluster root CA only to replace the old service account secrets
* Roots used for Google APIs to distribute to our logging and monitoring components that only need to talk to googleapis.com
* A bundle for Istio
* A bundle containing all public roots trusted by ChromeOS

**Comment by yuko11** [comment]
@tallclair isn't it a good idea to add your internal company's CA certificate into underlying host CA certificate bundle file and mount it into each POD? It would allow you to get public CA updates with underlying host OS update, and you can easily manage internal company's CA (except of you need to recreate all cluster hosts to change it). Having Public CA bundle + internal CA certs in configmaps would lead to never update Public CA bundle.

**Comment by mleneveut** [comment]
Any update on this ?

I need my pods to trust a self-signed certificate for our dev environments. I tried to add the ca-cert to my pod and run update-ca-certificates but I can't make it work.

Any help would be appreciated :)

```
kind: Deployment
metadata:
  name: bff
  namespace: ci
spec:
  template:
    spec:
      initContainers:
      - command:
        - sh
        - -c
        - |
          mkdir /etc/ssl/certs
          cp -f /tmp/ssl/* /usr/local/share/ca-certificates
          update-ca-certificates
        image: my-image
        name: add-certs
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /tmp/ssl
          name: is4-cacerts
        - mountPath: /etc/ssl
          name: shared-ca-certificate-vol
      containers:
        image: my-image
        name: bff
      volumes:
      - configMap:
          name: is4-cacerts
        name: is4-cacerts
      - emptyDir: {}
        name: shared-ca-certificate-vol
```

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: is4-cacerts
  namespace: ci
data:
  kubernetes.crt: |-
    -----BEGIN CERTIFICATE-----
    MIID
    ...
    q4Neg/JZ
    -----END CERTIFICATE-----
```

In the Node's log I got these errors when calling an https request to a service in the same namespace : 
```
Error: self signed certificate in certificate chain
```

**Comment by fabianotessarolo** [comment]
@mleneveut which distro is based your image? Have you checked its location?

https://blog.confirm.ch/adding-a-new-trusted-certificate-authority/

**Comment by mleneveut** [comment]
@fabianotessarolo It' ubuntu 16.

I already tried to put the cert in /usr/local/shared/ca-certificates and run the update-ca-certificates, but my trouble was to do this before the container's main process (nodejs or dotnet run) starts.

I ended up to put the .crt file in /usr/shared/ca-certificates directory of every Kubernetes node, copy it to /usr/local/shared/ca-certificates with a volumeMount and modify the ENTRYPOINT of my Dockerfile with a CMD : 

```
CMD["sh", "-c", "update-ca-certificates && npm start"]
```

It's not ideal, but working. If we could put the .crt file in the CA cert of Kubernetes and automatically inherits it in the pods, it would be better.

```
        volumeMounts:
        - mountPath: /usr/local/share/ca-certificates
          name: ca-certificates
      volumes:
      - name: ca-certificates
        hostPath:
          path: /usr/share/ca-certificates
```
