### ISSUE TITLE
Unable to expose pod IP using Downward API EnvVar in Windows containers

### ISSUE THREAD

**Issue by david-jarman** [kubernetes/kubernetes#63825]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

Created a pod based on the pod definition shown in the [Expose Pod Information to Containers Through Environment Variables](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables). 

**What you expected to happen**:

Expected there to be an environment variable called "MY_POD_IP" in the container

**How to reproduce it (as minimally and precisely as possible)**:

Save pod definition to a file:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-fieldref
spec:
  nodeSelector:
    beta.kubernetes.io/os: windows
  containers:
    - name: test-container
      image: microsoft/windowsservercore:ltsc2016
      command: [ "powershell.exe", "-c"]
      args: ["while ($true) { Write-Output \"Node name: $($env:MY_NODE_NAME)\"; Write-Output \"Pod Name: $($env:MY_POD_NAME)\"; Write-Output \"Pod IP: $($env:MY_POD_IP)\"; Start-Sleep -Seconds 10; }"]
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
  restartPolicy: Never
```

```kubectl create -f saved_pod_def.yaml```

```kubectl logs dapi-envars-fieldref```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.7
- Cloud provider or hardware configuration: Azure (virtual machines)
- OS (e.g. from /etc/os-release): Windows Server 2016
- Kernel (e.g. `uname -a`): n/a
- Install tools: acs-engine
- Others:
