### ISSUE TITLE
dashboard not working with RBAC

### ISSUE THREAD

**Issue by beatlejuse** [kubernetes/kubernetes#63854]
/kind bug

**What happened**:
i deploy kube dashboard from tag v1.10.2
https://github.com/kubernetes/kubernetes/tree/v1.10.2/cluster/addons/dashboard
sign in with kubernetes-dashboard-token.
and see this error: "nodes is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list nodes at the cluster scope"

**What you expected to happen**:
list of cluster nodes in dashboard

**How to reproduce it (as minimally and precisely as possible)**:
deploy kube dashboard from tag v1.10.2

**Anything else we need to know?**:
no

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.6
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): coreos 1632.3.0 / 4.14.19-coreos #1 SMP Wed Feb 14 03:18:05 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz GenuineIntel GNU/Linux
- Install tools: flannel
- Others: RBAC on

sig/auth
area/security

**Comment by beatlejuse** [comment]
I solved this problem by adding a cluster role:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-dashboard
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rook-operator
  namespace: rook-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-dashboard
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
```
