### ISSUE TITLE
Unable to register Master with API server

### ISSUE THREAD

**Issue by iponnam** [kubernetes/kubernetes#63899]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
We have initiated 1 Master and 6 Nodes using Kubeadm around March 30th 2018. Everything is working fine until last weekend. kubernetes control-plane pods were down and when trying to restart , the etcd & api-server pods are restarting. And kubelet is unable to register the **MASTER** with API Server. 

```
Unable to register node "azwushubqaadmmaster01" with API server
```

The etcd logs [Attached] doesn't throw any error except that it is receiving kill signal from kubelet after it is up for about 2-3 minutes.

Attaching etcd, api-server and kubelet logs.
 
**What you expected to happen**:
Master Node to register with API Server.
**How to reproduce it (as minimally and precisely as possible)**:
Install 1 master and 6 nodes. Harden kubelet, api-server and etcd as follows:

kubelet config:
```
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"
Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki --tls-cert-file=/var/lib/kubelet/pki/kubelet-server.crt --tls-private-key-file=/var/lib/kubelet/pki/kubelet-server.key --feature-gates=RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true"
Environment="KUBELET_EXTRA_ARGS=--v=6"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS
```
etcd.yaml
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --debug=true
    - --listen-client-urls=https://127.0.0.1:2379
    - --advertise-client-urls=https://127.0.0.1:2379
    - --client-cert-auth=true
    - --cert-file=/etc/kubernetes/pki/etcd/etcd-server.crt
    - --key-file=/etc/kubernetes/pki/etcd/etcd-server.key
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --auto-tls=false
    - --data-dir=/var/lib/etcd/DataDir/
    - --wal-dir=/var/lib/etcd/walDir/
    - --max-wals=0
    image: gcr.io/google_containers/etcd-amd64:3.1.12
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt
          --cert=/etc/kubernetes/pki/etcd/etcd-client.crt --key=/etc/kubernetes/pki/etcd/etcd-client.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
      timeoutSeconds: 30
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd/DataDir/
      name: etcd
    - mountPath: /var/lib/etcd/walDir/
      name: wal
    - mountPath: /etc/kubernetes/pki/etcd/
      name: etcd-certs
  hostNetwork: true
  volumes:
  - hostPath:
      path: /var/lib/etcd/DataDir/
      type: DirectoryOrCreate
    name: etcd
  - hostPath:
      path: /var/lib/etcd/walDir/
      type: DirectoryOrCreate
    name: wal
  - hostPath:
      path: /etc/kubernetes/pki/etcd/
      type: DirectoryOrCreate
    name: etcd-certs
status: {}
```
kube-apiserver.yaml
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --anonymous-auth=false
    - --requestheader-group-headers=X-Remote-Group
    - --runtime-config=rbac.authorization.k8s.io/v1alpha1,admissionregistration.k8s.io/v1alpha1
    - --service-account-lookup=true
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota,AlwaysPullIm
ages,SecurityContextDeny,DenyEscalatingExec,PodSecurityPolicy
    - --requestheader-allowed-names=front-proxy-client
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --secure-port=6443
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --allow-privileged=true
    - --kubelet-https=true
    - --request-timeout=3m0s
    - --repair-malformed-updates=false
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --service-cluster-ip-range=10.96.0.0/12
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-bootstrap-token-auth=true
    - --requestheader-username-headers=X-Remote-User
    - --advertise-address=10.248.66.21
    - --kubelet-certificate-authority=/etc/kubernetes/pki/ca.crt
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --insecure-port=0
    - --authorization-mode=Node,RBAC
    - --etcd-servers=https://127.0.0.1:2379
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/etcd/etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/etcd/etcd-client.key
    - --profiling=false
    - --audit-policy-file=/etc/kubernetes/apiserverconfig/audit-policy.yaml
    - --audit-log-format=json
    - --audit-log-path=/mnt/logs/k8s/audit/kube-audit
    - --audit-log-maxage=30
    - --audit-log-maxbackup=10
    - --audit-log-maxsize=100
    - --feature-gates=AdvancedAuditing=true
    - --experimental-encryption-provider-config=/etc/kubernetes/apiserverconfig/encrypt-config.yaml
    - --v=6
    image: gcr.io/google_containers/kube-apiserver-amd64:v1.9.5
    livenessProbe:
      tcpSocket:
        port: 6443
      initialDelaySeconds: 15
      periodSeconds: 20
    name: kube-apiserver
    resources:
      requests:
        cpu: 500m
    volumeMounts:
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/kubernetes/apiserverconfig
      name: apiserverconfig
      readOnly: true
    - mountPath: /mnt/logs/k8s/
      name: logs
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/kubernetes/apiserverconfig
      type: DirectoryOrCreate
    name: apiserverconfig
  - hostPath:
      path: /mnt/logs/k8s/
      type: DirectoryOrCreate
    name: logs
status: {}

```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux azwushubqaadmmaster01 4.13.0-1016-azure #19-Ubuntu SMP Thu May 3 17:29:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: KUBEADM
[logs.zip](https://github.com/kubernetes/kubernetes/files/2007166/logs.zip)

- Others:
