### ISSUE TITLE
Support EIP Allocations with AWS NLB

### ISSUE THREAD

**Issue by pho-enix** [kubernetes/kubernetes#63959]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature
/sig aws

**Anything else we need to know?**:

AWS NLBs support static IP addresses by associating an EIP per AZ. An already allocated EIP can be supplied with the [subnetMapping](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_SubnetMapping.html).

A user can then supply EIP allocation IDs in the service definition of kubernetes. By that the service will be available via those static IPs.

**Comment by gregkeys** [comment]
eip's for white listing are really important in the enterprise, we need this feature now, as a result we have to manually create nlb's, would really like to see this added

**Comment by chrissnell** [comment]
This is also important for hosting providers, who might have huge numbers of apex domain DNS `A` records pointed at EIPs.  Associating an already-allocated EIP with a new Kubernetes-generated NLB would be huge!

**Comment by 2rs2ts** [comment]
This feature would save us weeks of work reimplementing the cloud controller just so we can preserve a special ELB that has static IP addresses... I really wish it was available

**Comment by brooksgarrett** [comment]
I'd like to contribute time to working on this. Is anyone else actively working on adding support?

**Comment by pho-enix** [comment]
@brooksgarrett That's awesome news. Thanks for working on this.

Do you need assistance in testing this in an AWS environment? I might help out with that ...

**Comment by brooksgarrett** [comment]
Sure, the PR has been approved for testing so the binaries are available. I'm moving the code into our soak environment to get it some more exposure this week.

**Comment by pho-enix** [comment]
I've been trying with:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-060029855176d9d52,eipalloc-0167919bfcb1170c2,eipalloc-094a0864e3e10becb"
```
But I only go a NLB without the EIPs deployed. Didn't find any errors in the logs.

Do I have to enable a feature flag for it or kind of?
