### ISSUE TITLE
envFrom: configMapRef load the enviroment variables only with busybox image

### ISSUE THREAD

**Issue by stefanosirplay** [kubernetes/kubernetes#64103]
/kind bug

**What happened**:

envFrom: configMapRef not load the enviroment variables. 

this is my deployment yaml:
```
apiVersion: extensions/v1
kind: Deployment
metadata:
  name: test
  namespace: default
  labels:
    app: test
    version: latest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test
        version: latest
      name: test
    spec:
      containers:
        - name: test
          image: ubuntu
          command: [ "sleep", "50000" ]
          envFrom:
          - configMapRef:
              name: endpoints
          - configMapRef:
              name: nameofconfigmap-properties
```

when i exec in pod: `sh -c env` not list me the variables from configmap

**What you expected to happen**:
the config map data in enviroment variables. 

**How to reproduce it (as minimally and precisely as possible)**:
simple use the yaml attached

**Anything else we need to know?**:
**VERY INTERESSING!!!!!!**
if i use a image: `busybox` work fine, if i use `ubuntu`, `alpine `or other not work

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.8-gke.0", GitCommit:"6e5b33a290a99c067003632e0fd6be0ead48b233", GitTreeState:"clean", BuildDate:"2018-02-16T18:26:58Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: kubernetes engine (google cloud platform)
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dangarthwaite** [comment]
I'm using busybox:glibc and not seeing environment variables.

**Comment by steveLiuu** [comment]
@stefanosirplay 
try edit `configMapRef:` into `configMapKeyRef:`

**Comment by praaxe** [comment]
If anyone still has this issue like me I found a solution, I think it's an issue with the parsing of the file ...
I transformed
```
  - envFrom:
    - configMapRef:
        name: config-env
    - secretRef:
        name: secret-env
```
By
```
  - envFrom:
    - configMapRef: { name: config-env }
    - secretRef: { name: secret-env }
```
Don't know why but it works
