### ISSUE TITLE
kubectl apply when reading multiple files should order CRUD operations properly

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/kubernetes#64203]
/kind bug

**What happened**:

When I `kubectl apply -R  -f test/` and I have several numerous k8s objects in different files. It could fail to apply due to the file ordering.

**What you expected to happen**:

All the objects should be created.

**How to reproduce it (as minimally and precisely as possible)**:

Create a `test` directory containing two files

```
test/pod.yml
test/z-namespace.yml 
```

pod.yml contains

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
```

z-namespace.yml contains
```
apiVersion: v1
kind: Namespace
metadata:
  name: test
```

Then try to create the objects:

```
$  kubectl apply -R -f test
namespace "test" created
Error from server (NotFound): error when creating "test/pod.yml": namespaces "test" not found
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:12Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.1", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-04-07T22:06:59Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
gke1.9.6
