### ISSUE TITLE
user shouldn't  grant extra privileges

### ISSUE THREAD

**Issue by carlory** [kubernetes/kubernetes#64207]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

A user grant extra privileges 

**What you expected to happen**:

A user shouldn't  grant extra privileges

**How to reproduce it (as minimally and precisely as possible)**:

YAML:  test.yaml

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - cluster-admin
  resources:
  - clusterroles
  verbs:
  - '*'
```

1. the `test` user cannot list pods
```shell 
kubectl --as test get po

Error from server (Forbidden): pods is forbidden: User "test" cannot list pods in the namespace "default"
```
2. create role and binding

```shell
kubectl create -f test.yaml

kubectl create clusterrolebinding test --clusterrole test --user test
```

3. try listing pods

```shell
kubectl --as test get po

Error from server (Forbidden): pods is forbidden: User "test" cannot list pods in the namespace "default"
```

4. bind cluster-admin

```shell
kubectl --as test create clusterrolebinding test-extra-privileges --clusterrole cluster-admin --user test
```

5.  try listing pods

```shell
kubectl --as test get po

No resources found.
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
the test role grants all verbs on the cluster-admin clusterrole resource:
```
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - cluster-admin
  resources:
  - clusterroles
  verbs:
  - '*'
```

that includes the `bind` verb, which is checked when the user attempts to bind the cluster-admin clusterrole

from https://kubernetes.io/docs/admin/authorization/rbac/#privilege-escalation-prevention-and-bootstrapping:

> A user can only create/update a role binding if they already have all the permissions contained in the referenced role (at the same scope as the role binding) or if they’ve been given explicit permission to perform the bind verb on the referenced role. For example, if “user-1” does not have the ability to list secrets cluster-wide, they cannot create a ClusterRoleBinding to a role that grants that permission. To allow a user to create/update role bindings:
>
> 1. Grant them a role that allows them to create/update RoleBinding or ClusterRoleBinding objects, as desired.
> 2. Grant them permissions needed to bind a particular role:
>     * implicitly, by giving them the permissions contained in the role.
>     * explicitly, by giving them permission to perform the bind verb on the particular role (or cluster role).

if you don't want the user to be able to bind the cluster-admin role, do not grant them all verbs on that resource

/close
