### ISSUE TITLE
security group rule will change back to 0.0.0.0 by k8s after I changed it. (AWS ELB)

### ISSUE THREAD

**Issue by johnzheng1975** [kubernetes/kubernetes#64259]
security group rule will change back to 0.0.0.0 by k8s after I changed it. (AWS ELB)

*k8s 1.9
*kubespray 2.4
*AWS

Steps:
1 I created a service with Loadbalancer type
2 I find the security group of elb is open to worldwide 0.0.0.0
3 I changed the security group rule to my company ip xx.xx.xx.xx/8
4 After some time, I checked the security group rule, it is 0.0.0.0 again.
5 From cloud trail, it showed aws role (for aws cluster) changed it automatically.

Expect result:
I want to change and keep security group rule to xx.xx.xx.xx/8

Real result:
It always change back to 0.0.0.0.

Note:
For my other k8s cluster, it do not change it for some time.

**Comment by johnzheng1975** [comment]
@kubernetes/sig-bugs

**Comment by Bizzelicious** [comment]
Hi, you can use `loadBalancerSourceRanges` in the service manifest to whitelist IPs in your SG. With this option the IPs will be whitelisted when the service creates your load balancer. No need to whitelist afterwards.
```
kind: Service
apiVersion: v1
metadata:
  name: foo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "True"
spec:
  loadBalancerSourceRanges: 
    - x.x.x.x.x/32
    - y.y.y.y.y/32
  type: LoadBalancer
  selector:
    app: foo
  ports:
  - name: foo
    protocol: TCP
    port: 9000
    targetPort: 9000
```
