### ISSUE TITLE
"kubectl describe cronjobs" can't find resource (wrong api version)

### ISSUE THREAD

**Issue by hal58th** [kubernetes/kubernetes#64348]
/sig cli
**Is this a BUG REPORT or FEATURE REQUEST?**:
> kind bug

**What happened**:
The command `kubectl describe cronjobs` always results in "the server could not find the requested resource".

**What you expected to happen**:
The command should successfully find the cronjobs.

**How to reproduce it (as minimally and precisely as possible)**:
You can create any cronjob but you can use the example in the help guide. Then run `kubectl describe cronjobs`.
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

**Anything else we need to know?**:
I believe I know the exact reason it's doing this. kubectl is calling the wrong version of the batch api. While using debug --v=8, you can see it calling `GET https://{IP_ADDRESS}:8443/apis/batch/v1/namespaces/default/cronjobs/hello` but it should be calling the "v1beta1" api version.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Using minikube with Virtualbox.

- OS (e.g. from /etc/os-release): 
NAME=Buildroot
VERSION=2017.11
ID=buildroot
VERSION_ID=2017.11
PRETTY_NAME="Buildroot 2017.11"

- Kernel (e.g. `uname -a`): Linux minikube 4.9.64 #1 SMP Fri Mar 30 21:27:22 UTC 2018 x86_64 GNU/Linux

- Install tools: NULL
- Others: NULL
