### ISSUE TITLE
When launching a Pod referencing existing EBS the pod does not get launched on the node where the EBS gets attached

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes/kubernetes#64373]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
When launching a Pod referencing existing EBS the pod does not get launched on the node where the EBS gets attached. I have to kill that one and new one gets created this time on the right node. Initially the EBS is in `available` state and k8s does the right thing and attaches the volume to the the node running in the same AZ (there is only single node per each zone). But then it launches the Pod on a wrong node, one that the EBS is not attached to. During consecutive killing of the Pod I have observed random results, sometimes it gets launched on the correct node where the EBS is and stays attached and sometime does not.

**What you expected to happen**:
Pod should always get launched on the node where the EBS gets/was attached.

**How to reproduce it (as minimally and precisely as possible)**:
Create an EBS volume in an AZ and launch a pod with:
```
...
        volumeMounts:
          - mountPath: /mnt
            name: my-ebs
      volumes:
      - name: my-ebs
        awsElasticBlockStore:
          volumeID: vol-xxxxxx
```
and observe on which node the Pod gets created. It should be the one to which k8s attaches the EBS volume but that's not always the case.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.7
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8.10 (jessie)
- Kernel (e.g. `uname -a`): 4.4.115-k8s
- Install tools: Kops
- Others:
