### ISSUE TITLE
kubectl create CustomResourceDefinition and new kind resource in one single file

### ISSUE THREAD

**Issue by johackim** [kubernetes/kubernetes#64391]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

I have two resources in one single file : 

```yaml
# crontab.yaml

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
      - ct

---
apiVersion: stable.example.com/v1
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
  replicas: 3
```

I want create this resources in one single command `kubectl create` : 

```
customresourcedefinition.apiextensions.k8s.io "crontabs.stable.example.com" created (dry run)
error: unable to recognize "crontab.yaml": no matches for kind "CronTab" in version "stable.example.com/v1"
```

**What you expected to happen**:

```
customresourcedefinition.apiextensions.k8s.io "crontabs.stable.example.com" created (dry run)
crontab.stable.example.com "my-new-cron-object" created (dry run)
```

**How to reproduce it (as minimally and precisely as possible)**:

```bash
kubectl --dry-run=true create -f crontab.yaml
```

**Anything else we need to know?**:
 
Helm hooks doesn't work either : 

- https://pastebin.com/raw/gZQ3xWhZ
- https://pastebin.com/raw/KaMpAjjy

**Environment**:
- Kubernetes version:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- OS:  Arch Linux
- Kernel: Linux arch 4.16.11-1-ARCH
- Install tools: minikube

/sig cli
