### ISSUE TITLE
specify resource group for azure file PVC dynamic creation

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#64428]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
specify `resourcegroup` in azure file storage class so that user could specify external resource group

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  storageaccount: EXISTING_STORAGE_ACCOUNT
  resourcegroup: RESOURCE_GROUP_NAME
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign
