### ISSUE TITLE
Reconciliation strategy of port/IP allocation collisions is flawed

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/kubernetes#64466]
/kind bug

**What happened**:
If you see an event like this on a service:
```
Events:
  Type     Reason                Age   From                             Message
  ----     ------                ----  ----                             -------
  Warning  PortAlreadyAllocated  4s    portallocator-repair-controller  Port 32457 was assigned to multiple services; please recreate service
```

You will attempt to rectify the situation by deleting and recreating the service in hopes it'll be assigned a non-conflicting port. However, on service deletion, ports are blindly released from the allocator without regard to it being allocated by another service.

Therefore, until the repair controller runs (every three minutes), it's possible to create a service and be allocated the same nodeport. This is reproducible by manually specifying the nodeport on the service at recreation. 

cc @bowei @MrHohn

**Comment by nicksardo** [comment]
sig/network

**Comment by bowei** [comment]
What are the affected versions?

**Comment by nicksardo** [comment]
All versions.

**Comment by xiaoxubeii** [comment]
@nicksardo Do you know in what scenario will cause two svcs to have the same port?

**Comment by nicksardo** [comment]
https://github.com/kubernetes/kubernetes/issues/63617 at the very least - I wouldn't be surprised if there are other holes.

**Comment by sergey-safarov** [comment]
> Do you know in what scenario will cause two svcs to have the same port?

Example SIP server. They use port 5060 for TCP and UDP transport.
Need to publish. In this case issue is reproduced.
```yaml
apiVersion: v1
kind: Service
metadata:
  name: proxy-dc0-0
spec:
  externalTrafficPolicy: Local
  ports:
  - name: sip-tcp
    port: 5060
    protocol: TCP
    targetPort: 5060
  - name: sip-udp
    port: 5060
    protocol: UDP
    targetPort: 5060
  selector:
    statefulset.kubernetes.io/pod-name: proxy-dc0-0
  type: NodePort
```
