### ISSUE TITLE
[PodSecurityPolicy] All authenticated tokens can use a PSP assigned to "system:serviceaccounts:kube-system" RBAC Group

### ISSUE THREAD

**Issue by KashifSaadat** [kubernetes/kubernetes#64479]
/kind bug
/sig auth

**What happened**:
- When creating a deployment with an authenticated token in a custom namespace `test`, the pod had an annotation `kubernetes.io/psp=privileged`. The token used only has access to `use` the `default` PSP (both of which exist and have relevant bindings in place).

**What you expected to happen**:
- The annotation on the pod should be `kubernetes.io/psp=default`

**How to reproduce it (as minimally and precisely as possible)**:
- Create a Kubernetes Cluster on v1.10.1 (I built with kops in this instance, admission controls: `Initializers, MutatingAdmissionWebhook, NamespaceLifecycle, LimitRanger, ServiceAccount, PersistentVolumeLabel, DefaultStorageClass, PodSecurityPolicy, ResourceQuota, DefaultTolerationSeconds, ValidatingAdmissionWebhook`)
- Define PodSecurityPolicies:
```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default
spec:
  privileged: false
  fsGroup:
    rule: RunAsAny
  hostPID: false
  hostIPC: false
  hostNetwork: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - gitRepo
  - persistentVolumeClaim
  - projected
  - secret
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  fsGroup:
    rule: RunAsAny
  hostPID: true
  hostIPC: true
  hostNetwork: true
  hostPorts:
  - min: 1
    max: 65536
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
```
- [Cluster]Roles:
```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: psp:default
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - default
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: psp:privileged
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
```
- And [Cluster]RoleBindings:
```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: psp:default
roleRef:
  kind: ClusterRole
  name: psp:default
  apiGroup: rbac.authorization.k8s.io
subjects:
# every authenticated user can use default PSP
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
# every service account can use default PSP
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: psp:privileged
roleRef:
  kind: ClusterRole
  name: psp:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
# everyone in the system:masters group can use privileged PSP
- kind: Group
  name: system:masters
  apiGroup: rbac.authorization.k8s.io
# every serviceaccount in the kube-system namespace can use privileged PSP
- kind: Group
  name: system:serviceaccounts:kube-system
  apiGroup: rbac.authorization.k8s.io
```

- Create a new namespace for testing, and a token with access to it (or use the default SA within that namespace, granting it relevant access to create deployments etc).
  - **Don't** add it to the ClusterRoleBindings mentioned above, or add the `system:masters` / `system:serviceaccounts:kube-system` groups
- Using this new token, create a deployment / pod within your test namespace and then check the annotations on it (you should see `kubernetes.io/psp=privileged`)
- Delete the last group assignment `system:serviceaccounts:kube-system` on the ClusterRoleBinding for `psp:privileged`, then update / re-create your deployment with the token created earlier. You should now see the annotation `kubernetes.io/psp=default`

So it seems that if a role binding has the Group `system:serviceaccounts:kube-system` specified, then any token (I've tried with user and service-account) is able to use any PodSecurityPolicy resources associated with it, regardless of whether it is in this group/namespace or not. Is this expected, or are there any silly mistakes I've made in the specs above?

**Environment**:
- Kubernetes version: v1.10.1
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS v1688.5.3
- Kernel (e.g. `uname -a`): 4.14.32-coreos
- Install tools: kops (v1.9.0+)
