### ISSUE TITLE
2 Ingress Controllers ignoring namespaces  when forwarding traffic to Ingress Resource

### ISSUE THREAD

**Issue by maephisto666** [kubernetes/kubernetes#64485]
/kind bug

**What happened**:
I am using Kubernetes on AWS (I installed it with KOPS). I am able to create Deployments, Services, etc. I have 2 namespace env-staging and env-live. In both namespace there is a service called registry with different details. I installed 2 ingress controllers with

```
helm install --namespace env-staging --name nginx-ingress-staging stable/nginx-ingress
helm install --namespace env-live --name nginx-ingress-live stable/nginx-ingress
```
and I defined 2 ingress resources in each namespace

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: env-staging
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /registry
        backend:
          serviceName: registry
          servicePort: 8080
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  namespace: env-live
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /registry
        backend:
          serviceName: registry
          servicePort: 8080
```

AWS creates automatically 2 Load Balancers (under EC2 services) with different IP addresses. When I try to access one load balancer http://<balancer_A_address>/registry I see the details from the registry deployed in one of the two namespaces. When I hit the second balancer http://<balancer_B_address>/registry i see the same service. It is like 2 the two ingress controllers (corresponding to the 2 load balancers) can go cross-namespace, without limiting the scope to the namespace they are living in.

**What you expected to happen**:
I expected that each Ingress controller is able to manage JUST the Ingress resources in ITS OWN namespace, without "crossing the boundaries" between the namespaces.

**Anything else we need to know?**:
I know that there are other discussions #17088 but at the moment this behaviour does not seem right to me. 

By the way I tried something more complex, putting 2 different entries on Route 53 to address the two Load Balancer on AWS BUT changing the Ingress resource putting there the Host label, right before the http part. This thing worked (the host is used against the Host Header of the request) but I simply do not understand if this is currently a bug or is the attended behaviour (but it really sounds strange to me, 2 controllers deployed on different namespaces that mix 2 ingress resource each on a separate namespace).

**Environment**:
- Kubernetes version (use `kubectl version`): version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AWS (kops installation one master 3 nodes)
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): Linux ip-172-20-41-108 4.4.115-k8s #1 SMP Thu Feb 8 15:37:40 UTC 2018 x86_64 GNU/Linux
- Install tools: KOPS
- Others:
