### ISSUE TITLE
Ingress and Service not working correctly

### ISSUE THREAD

**Issue by stefanthorpe** [kubernetes/kubernetes#64497]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
/kind bug
**What happened**:
Ingress backend reporting unhealthy when it's actually healthy. Hence I can't connect to it via the ingress.

I was able to connect to the service via the local busybox.

**What you expected to happen**:
Expected to be able to connect to the backend server via port 80.

**How to reproduce it (as minimally and precisely as possible)**:
The follow is the YAML is the exact config.

```
kind: Service
apiVersion: v1
metadata:
  name: marketing
spec:
  ports:
  - protocol: TCP
    port: 80
  selector: {}
  type: NodePort
---
kind: Endpoints
apiVersion: v1
metadata:
  name: marketing
subsets: 
  - addresses:
    - ip: 52.91.62.189
    ports:
    - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: marketing-temp
spec:
  backend:
    serviceName: marketing
    servicePort: 80
---
# Temp pod for testing
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: odise/busybox-curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
```
**Anything else we need to know?**:
The aim of the task is to setup a permanent ingress that connects to a temporary service. Once the service is containerized and relocated to the cluster the select will be updated and the legacy server shutdown.

**Environment**:
- Kubernetes version 1.9.6:
- Cloud provider or hardware configuration: GCP
