### ISSUE TITLE
Garbage collector doesn't delete 'exited' containers. As result we get nodes in 'NotReady' status

### ISSUE THREAD

**Issue by argusua** [kubernetes/kubernetes#64507]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
After upgrade to from 1.8 to 1.9, we found that after some time node became NotReady, because of docker service down and kubernetes doesn't try run pods from this node on other nodes (it try just restart them). After some investigation, we found that docker daemon doesn't respond. Also, it has 33212 containers (calculated by `find /var/lib/docker/containers/ -maxdepth 1 -type d | wc -l`) and only ~20 in running state (total pods in cluster is 202, containers 150).

**What you expected to happen**:
We expect that GC will clean up exited and failed containers. Also, we found parameter for kubelet `--maximum-dead-containers-per-container` but it deprecated now.

**How to reproduce it (as minimally and precisely as possible)**:
We have a lot of jobs and sometimes bad pods constantly restarting.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
`Aws/Kops`

- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Kernel (e.g. `uname -a`):
`Linux ip-172-20-50-12 4.4.115-k8s #1 SMP Thu Feb 8 15:37:40 UTC 2018 x86_64 GNU/Linux`

- Install tools:
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:09:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:09:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- Others:
Disk space used:
`/dev/xvda1      120G   12G  104G  10% /`

**Comment by argusua** [comment]
Now looks ok. Added ` --restart no` to hook:
```
  hooks:
  - manifest: |
      Type=oneshot
      ExecStart=/usr/bin/docker run --net host --restart no quay.io/sergioballesteros/check-aws-tags
      ExecStartPost=/bin/systemctl restart kubelet.service
    name: ensure-aws-tags.service
    requires:
    - docker.service
    roles:
    - Node
```
