### ISSUE TITLE
cannot create an external load balancer with mix protocols

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#64545]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind feature

I was trying to create a loadbalancer service with mix protocols but it failed to create with error `cannot create an external load balancer with mix protocols`, what is the reason that we cannot create an external load balancer with mix protocols?

```
[root@gyliu-icp-1 mc]# cat test.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot-ilb-1
  namespace: istio-system
  labels:
    istio: pilot
spec:
  type: LoadBalancer
  loadBalancerIP: 9.111.255.5
  ports:
  - name: https-pilot-1
    port: 15003
    protocol: TCP
  - name: https-pilot-2
    port: 15005
    protocol: TCP
  - name: https-pilot-3
    port: 15007
    protocol: TCP
  - name: https-pilot-4
    port: 15010
    protocol: TCP
  - name: https-pilot-5
    port: 15011
    protocol: TCP
  - port: 8080
    name: http-pilot-6
    protocol: TCP
  - name: https-pilot-7
    port: 9093
    protocol: UDP
  selector:
    istio: pilot
```

```
[root@gyliu-icp-1 mc]# kubectl apply -f test.yaml
The Service "istio-pilot-ilb-1" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"https-pilot-1", Protocol:"TCP", Port:15003, TargetPort:intstr.IntOrString{Type:0, IntVal:15003, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-pilot-2", Protocol:"TCP", Port:15005, TargetPort:intstr.IntOrString{Type:0, IntVal:15005, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-pilot-3", Protocol:"TCP", Port:15007, TargetPort:intstr.IntOrString{Type:0, IntVal:15007, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-pilot-4", Protocol:"TCP", Port:15010, TargetPort:intstr.IntOrString{Type:0, IntVal:15010, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-pilot-5", Protocol:"TCP", Port:15011, TargetPort:intstr.IntOrString{Type:0, IntVal:15011, StrVal:""}, NodePort:0}, core.ServicePort{Name:"http-pilot-6", Protocol:"TCP", Port:8080, TargetPort:intstr.IntOrString{Type:0, IntVal:8080, StrVal:""}, NodePort:0}, core.ServicePort{Name:"https-pilot-7", Protocol:"UDP", Port:9093, TargetPort:intstr.IntOrString{Type:0, IntVal:9093, StrVal:""}, NodePort:0}}: cannot create an external load balancer with mix protocols
```
