### ISSUE TITLE
RBD block device missed after docker/kubelet restart 

### ISSUE THREAD

**Issue by wenlxie** [kubernetes/kubernetes#64557]
In our env, restart docker will caused kubelet and container restart.

I start a pod with following pod yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: default
  name: mybb-volume-mode
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: ubuntu
    imagePullPolicy: Always
    name: busybox
    volumeDevices:
    - devicePath: /dev/vda
      name: myclaim
    securityContext:
      capabilities:
        add:
          - SYS_ADMIN
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  schedulerName: default-scheduler
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: myclaim
    persistentVolumeClaim:
      claimName: pvc-raw-test
```
It use PVC's block volume mode and the device will be mapped to `/dev/vda` inside the container

After I create the pod, everything is fine. I can see the device inside the container.
But after I restart docker, as I mentioned, kubelet and all of the container will be restart.

After all of the container up again. I find that I can't see dev `/dev/vda` inside the container.
I inspect the container, and find that {"HostConfig":{"Devices": [],}} is empty. 
Then I did some debug, and find that https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L113 
The volName is "" ,  so the `islinkExist` will be false. 
It should be caused by volume spec not have name at : https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/rbd/rbd.go#L425
PR for this issue is: https://github.com/kubernetes/kubernetes/pull/64555

This issue can be reproduced by following steps:
1. Container is up, you can see the RBD block device inside your container
2. Restart kubelet
3. Kill the container
4. Wait for the container restart and then you can't see the RBD block device inside your container
