### ISSUE TITLE
JSON decoders should be case sensitive

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#64612]
Our current json decoders are case-insensitive. Creating a deployment with a field `spec.replicAs: 3` will fail kubectl validation with:

```
error: error validating "deployment.yaml": error validating data: ValidationError(Deployment.spec): unknown field "replicAs" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

If we use `--validate=false`, the deployment configuration is accepted and the json decoder unmarshals it as `spec.replicas: 3`.

IMO we should not allow wrongly named fields even if they differ only in case sensitivity. Also, custom resources validation differs from native resources validation here because the CRD validation specs are case sensitive.

I checked for the current master, 1.10, 1.9 and 1.8. This issue persists for all of them. We started using json-iter instead of ugorji in 1.9 (https://github.com/kubernetes/kubernetes/pull/48287) so it doesn't look related to that.

Go's `json.Unmarshal`, by default, is case insensitive. From https://golang.org/pkg/encoding/json/#Unmarshal,

> To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal (either the struct field name or its tag), preferring an exact match but also accepting a case-insensitive match. 

I suspect this is the underlying mechanism used in our json decoders which causes it to be case-insensitive. 

Wanted to make sure there is consensus in decoders being case sensitive before attempting a fix.

/cc @liggitt @thockin @sttts 
/sig api-machinery
/kind bug

**Comment by liggitt** [comment]
> I checked for the current master, 1.10, 1.9 and 1.8. This issue persists for all of them. We started using json-iter instead of ugorji in 1.9 (#48287) so it doesn't look related to that.

Actually, we switched to json-iter in 1.8:
```
$ git log v1.8.0 --format=oneline | grep json-iter
6a845c67f097cd76f9d90ab3c9c5b5603c70afe4 Merge pull request #48287 from thockin/json-iterator
86ef9d00f831bff4012878818db6f198e0e15dcf Add json-iterator dep, remove ugorji dep
5728b1970a2bed2207a2c63c1cfee86e52437d25 Use json-iterator for JSON, kill off codecgen

$ git tag --contains 6a845c67f097cd76f9d90ab3c9c5b5603c70afe4 | grep -v - | grep \\.0
v1.10.0
v1.8.0
v1.9.0
```

checking against 1.7, ugorji was case-sensitive:
```
$ curl http://localhost:8080/version
{
  "major": "1",
  "minor": "7+",
  "gitVersion": "v1.7.17-beta.0.1+347f652944cc23",
  "gitCommit": "347f652944cc2348d59b1c815007e21e062fe597",
  "gitTreeState": "clean",
  "buildDate": "2018-06-02T02:19:27Z",
  "goVersion": "go1.8.7",
  "compiler": "gc",
  "platform": "darwin/amd64"
}

$ curl -X POST http://localhost:8080/api/v1/namespaces -H "Content-Type: application/json" \
  --data '{"KIND":"Namespace","APIVERSION":"v1","METADATA":{"NAME":"foo"}}'
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Namespace \"\" is invalid: metadata.name: Required value: name or generateName is required",
  "reason": "Invalid",
  "details": {
    "kind": "Namespace",
    "causes": [
      {
        "reason": "FieldValueRequired",
        "message": "Required value: name or generateName is required",
        "field": "metadata.name"
      }
    ]
  },
  "code": 422
}
```

and json-iter in 1.8 is not:
```
$ curl http://localhost:8080/version
{
  "major": "1",
  "minor": "8+",
  "gitVersion": "v1.8.14-beta.0.8+bbe9159a96c1c6",
  "gitCommit": "bbe9159a96c1c631b3b81562b758eb63b61b8b58",
  "gitTreeState": "clean",
  "buildDate": "2018-06-02T02:27:20Z",
  "goVersion": "go1.8.7",
  "compiler": "gc",
  "platform": "darwin/amd64"
}

$ curl -X POST http://localhost:8080/api/v1/namespaces -H "Content-Type: application/json" \
  --data '"KIND":"Namespace","APIVERSION":"v1","METADATA":{"NAME":"foo"}}'
{
  "kind": "Namespace",
  "apiVersion": "v1",
  "metadata": {
    "name": "foo",
    "selfLink": "/api/v1/namespaces/foo",
    "uid": "f45db532-660c-11e8-8235-acbc32c1ca87",
    "resourceVersion": "228",
    "creationTimestamp": "2018-06-02T02:30:46Z"
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  },
  "status": {
    "phase": "Active"
  }
}
```

**Comment by liggitt** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by nikhita** [comment]
To clarify: we'll need to fix this on our side, right? Asking the upstream maintainer to support case-sensitivity when Go's `Unmarshal` doesn't - seems too much to ask. :)

**Comment by lavalamp** [comment]
Just saw this for the first time. We have to fix this ASAP, otherwise people will depend on in and we'll never be able to fix it.

**Comment by lavalamp** [comment]
It may already be too late if this has been in two releases.

**Comment by sttts** [comment]
We found this some days ago because the client-side OpenAPI validation rejected the manifest, but the server accepted it. So at least for the kubectl based use-cases we should be fine.

**Comment by lavalamp** [comment]
/assign @caesarxuchao 

Let's fix this ASAP.

Let's double check that we re-emitted all json before storage so we won't have a problem with unparseable stored data. Was this used for CRs?

**Comment by nikhita** [comment]
> Was this used for CRs?

CRs are `Unstructured` so they will accept the json data. For validation against the schema, it **is** case-sensitive. _However_, if a field with wrong case sensitivity is provided, it will store it because we don't prune right now.

Example:

This is my CRD.

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  validation:
    openAPIV3Schema:
      properties:
        spec:
          # cronSpec is required
          required:
          - cronSpec
          properties:
            cronSpec:
              type: string
              pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
```
This is my CR.

```yaml
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  # bad case!
  CRONSpec: "* * * *"
  image: my-awesome-cron-image
```

- If I don't mark `cronSpec` as required in the schema, the CR is created without any errors and persists the bad case field.
- If I mark `cronSpec` as required in the schema, the CR will not be created because `cronSpec` is not present in the CR (even though `CRONSpec` is).
