### ISSUE TITLE
'Timeout expired waiting for volumes to attach/mount for pod'

### ISSUE THREAD

**Issue by huang-jy** [kubernetes/kubernetes#64653]
/kind bug

**What happened**:
I created a deployment on a AWS k8s cluster, and that is using a PVC to a PV that is attached to an already-existing 3TB EBS volume

The cluster mounts the volume onto the worker node successfully and I can `cd` into the directory successfully (i.e. it's a clean disk and doesn't require fsck). However, k8s returns a timeout attaching it into the pod

If I delete the deployment, the disk remains attached to the node and is not released. Force-detaching it from the node via the AWS console allows it to be reused, but kubelet on that worker starts spamming error messages in the log after that, as the disk has been yanked and normally requires a restart to fix.

**What you expected to happen**:
The disk to be mounted into the pod successfully

**How to reproduce it (as minimally and precisely as possible)**:
Here's my yamls

pv and pvc:
```
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: tempdisk
  namespace: testing
spec:
  capacity:
    storage: 3000G
  awsElasticBlockStore:
    volumeID: aws://eu-west-1a/vol-xxxxxxxxx
    fsType: ext4
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: testing
  name: tempdisk-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3000G
  storageClassName: gp2

```

deploy:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: testing
  labels:
    app: testing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-app
  template:
    metadata:
      labels:
        app: testing-app
    spec:
      securityContext:
        runAsUser: 9999
        fsGroup: 999
      containers:
      - name: main
        image: docker-host/image:latest
        command: [ "bash","-c","sleep 24h"]
        ports:
        - containerPort: 80
        - containerPort: 8080

      volumes:
      - name: temp-disk
        persistentVolumeClaim:
          claimName: tempdisk-claim
```

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
AWS using kops (have posted this issue on that subproject too in case it's a kops issue)

- OS (e.g. from /etc/os-release):
Ubuntu Artful

- Kernel (e.g. `uname -a`):
`4.13.0-43-generic`

- Install tools:
`Kops`

- Others:
N/A
