### ISSUE TITLE
Add cli support to "exec" auth plugin

### ISSUE THREAD

**Issue by Fedosin** [kubernetes/kubernetes#64751]
Now it's possible to configure third-party auth providers using `kubectl config set-credentials` command with `--auth-provider` option.

It's nice to have the same possibility for the recently added `exec` [plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins). 
Example: To specify the executable path we can run `kubectl config set-credentials k8s_user --exec-command="/path/to/the/executable"`

This will generate a new config for the user:

```
apiVersion: v1
kind: Config
users:
- name: k8s_user
  user:
    exec:
      command: "/path/to/the/executable"
      apiVersion: "client.authentication.k8s.io/v1alpha1"
```

Various auxiliary configuration options are also could be added. For instance: 
- `--exec-arg` to define an argument for the executable;
- `--exec-env` to set an environment variable;
- `--exec-api-version` to specify a desired API version.

/kind feature
