### ISSUE TITLE
Feature: Specify groups on ServiceAccounts

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#64807]
/kind feature

User accounts can specify which groups they are in when using the PKI CSR flow (using the org field of the subject), but the ServiceAccount API doesn't seem to have a groups field.

AFAICT, the only way to add ServiceAccounts to groups would be using an auth proxy, which seems like overkill for something that is available elsewhere in the API.

Suggested API:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${account_name}
  namespace: ${namespace}
groups:
- groupA
- groupB
```
