### ISSUE TITLE
When mounting a key from ConfigMap under /root the whole /root volume becomes read-only

### ISSUE THREAD

**Issue by igoratencompass** [kubernetes/kubernetes#64825]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When mounting a key from ConfigMap under `/root` the whole `/root` path becomes read-only.

**What you expected to happen**:
Only the specific mount point `/root/config.json` to be read-only.

**How to reproduce it (as minimally and precisely as possible)**:
When using the following config:
```
  containers:
    - name: test-container
      image: nginx:latest
      volumeMounts:
      - name: config-volume
        mountPath: /root
  volumes:
    - name: config-volume
      configMap:
        name: my-config
        items:
        - key: config.json
          path: config.json
```
that the whole `/root` becomes read only instead of just the `/root/config.json` where I'm actually mounting. The pods complain with:
```
Error: EROFS: read-only file system, mkdir '/root/.pm2
```
I'm aware of the security patch for `subPath` but is this expected in this case?

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.13
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: kops
- Others:

**Comment by liggitt** [comment]
this is working as designed.
* specifying `mountPath: /root` shadows whatever other content exists at `/root`
* configmap volume mounts are read-only

if you want to mount a specific file from the config map, and leave the rest of the /root folder writeable, you can do this:

```yaml
  containers:
    - name: test-container
      image: nginx:latest
      volumeMounts:
      - name: config-volume
        mountPath: /root/config.json
        subPath: config.json
  volumes:
    - name: config-volume
      configMap:
        name: my-config
```
