### ISSUE TITLE
feature request: eviction priority within same priority class

### ISSUE THREAD

**Issue by xiang90** [kubernetes/kubernetes#64843]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:

Let's assume we have two teams managing production services and batch-jobs respectively. This case is artificial, but it can still demonstrate the problem well. 

### We want to ensure the production team can:
preempt the batch jobs when there is no enough resources

To achieve this, we can define two priority class as below

```YAML
apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: Production
value: 1000000
globalDefault: true
description: "This priority class should be used for production service pods only."
```

```YAML
apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: batch-job
value: 10
globalDefault: false
description: "This priority class should be used for batch-job pods only."
```

### We also want to ensure the batch job team can:
define the order of eviction of the batch jobs they launch when there is no enough resources for production services
avoid preemption within the batch jobs. In another word, no batch job can evict any other batch job. The reason of 2 is to avoid cascading eviction.

**However, there is no way to achieve both of them with today's Kubernetes functionality.**

To achieve 1), we have to define more priority classes with the right value ordering for the batch jobs. However, once we define different priority classes for the batch jobs, the higher priority ones might preempt the lower ones, which violates 2).

To solve this problem, we need to have a finer grained preemption control for pods within the same priority class.

/cc @kubernetes/sig-scheduling-feature-requests @resouer @bsalamat @k82cn

**Comment by bsalamat** [comment]
@xiang90 so you are saying that "all batch jobs are equal, but some batch jobs are more equal!" :wink:

What you are suggesting is to introduce another level of priority which is incapable of preempting other Pods, but specifies the order of preemption for victims within the same priority level. One problem that I can see with such an approach is that it will be hard to predicate the state of the cluster and behavior of priority and preemption. In order to explain the problem, let's call this second level of priority: sub-priority. Now, imagine this scenario: a batch job with sub-priority 10 is running. Let's call it Batch Job A, another batch job with sub-priority 100 arrives. Let's call it Batch Job B. Batch Job B cannot preempt Batch Job A, although it is "kind of" more important than Batch Job A. Now if we add a Production Job C to the mix, then the order of the creation of these jobs matters a lot in determining the correct state of the cluster. Here are some examples assuming that the cluster has enough capacity to run only 2 jobs:

Order of creation:
1. Batch Job A
2. Batch Job B
3. Production Job C
Expected state:
A: pending (preempted by C), B: running, C: running

Order of creation:
1. A
2. C
3. B
Expected state:
A: running, B: pending (arrived late), C: running

Order of creation:
1. C
2. A
3. B
Expected state:
A: running, B: pending (arrived late), C: running

As you can see the order of batch job creation changes the expected state of the cluster and determines which batch job should run. In other words, the cluster state cannot be determined from the specification of pods. In fact, the second scenario in the above examples is counter intuitive, because the specification of the pods would indicate that B is "kind of" more important, but yet B is pending, maybe because B was created a fraction of a second later than A. This is confusing for users in my opinion.
Do you have a real scenario where such "sub-priority" would be useful?

**Comment by xiang90** [comment]
> As you can see the order of batch job creation changes the expected state of the cluster and determines which batch job should run.

Isnt this already the case today? If you have 3 pods with the same priority class, and the cluster can only hold 2 pods. The order of submission matters.

> Do you have a real scenario where such "sub-priority" would be useful?

There are some batch jobs that are more important than others. For example, a tensorflow job with 10 trainers is more important than a video encoding job, since if we disrupt one of the tensorflow trainers the entire job will be affected. 

And as I mentioned, we do not want to create separate priority class to avoid cascading eviction within one catalog, say non-production batch jobs. And we do not want our named priority to become "numerical".

**Comment by xiang90** [comment]
> the pods would indicate that B is "kind of" more important, but yet B is pending, maybe because B was created a fraction of a second later than A. This is confusing for users in my opinion.

I would assume that if users start to control the in class priority, they will need to understand this behavior. If they do not care, they will not specify it. Also we can find a better naming for it, `sub-priority` is somewhat confusing I agree.

**Comment by bsalamat** [comment]
> Isnt this already the case today? If you have 3 pods with the same priority class, and the cluster can only hold 2 pods. The order of submission matters today.

In the new approach the order of creation relative to an unrelated high priority job matters too. If you compare the 3 examples that I gave above, you will see that the order of creation of A and B is the same, but the state of the cluster is different, because an unrelated job C has arrived in a different order relative to A and B. This adds quite a bit to the confusion.

> There are some batch jobs that are more important than others. For example, a tensorflow job with 10 trainers is more important than a video encoding job, since if we disrupt one of the tensorflow trainers the entire job will be affected.

If preemption could calculate the cost of preempting one of the 10 TF trainers correctly, it would know that the cost of preempting one is equal to killing all the 10 tasks. So, between killing 10 and killing 2 pods of another batch job, it would choose another batch job. This can be addressed by gang scheduling (@k82cn).

**Comment by xiang90** [comment]
> In the new approach the order of creation relative to an unrelated high priority job matters too. If you compare the 3 examples that I gave above, you will see that the order of creation of A and B is the same, but the state of the cluster is different, because an unrelated job C has arrived in a different order relative to A and B. 

I wont say C is unrelated, it does change the cluster state and the scheduler state if you view a scheduling decision depends on (incoming pod, cluster state). I can provide many more cases where the ordering does matter due to randomization, packing strategy, scoring strategy, etc..

My general feeling is that the scheduling decision will not be purely orthogonal to all the dimensions. 

> If preemption could calculate the cost of preempting one of the 10 TF trainers correctly, it would know that the cost of preempting one is equal to killing all the 10 tasks. 

There are other cases too. I am not sure if we should push this to the scheduler, which requires the understand a lot of cases. I feel it is better for the user or the application controller to give the hints (thus the eviction priority) to the scheduler.

**Comment by xiang90** [comment]
> This adds quite a bit to the confusion.

As I mentioned in https://github.com/kubernetes/kubernetes/issues/64843#issuecomment-395594562, I feel the confusion will come from the naming instead of the "nondeterministic" from the ordering perspective. And we can find a way to solve the naming issue if we agree this is something we want to support.

**Comment by k82cn** [comment]
This's a kind of `PriorityClass` level preemption flag: disable preemption for batch job, but keep priority feature (high priority has more chance to run and less chance to be killed). So the configuration maybe something as following.

```yaml
apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  name: Production
value: 1000000
globalDefault: true
description: "This priority class should be used for production service pods only."
```

```yaml
apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  annotation: "alpha.k8s.io/preemptor=false"
  name: high-pri-batch-job
value: 100
globalDefault: false
description: "This priority class should be used for batch-job pods only."
```

```yaml
apiVersion: scheduling.k8s.io/v1alpha1
kind: PriorityClass
metadata:
  annotation: "alpha.k8s.io/preemptor=false"
  name: low-pri-batch-job
value: 10
globalDefault: false
description: "This priority class should be used for batch-job pods only."
```

In our batch system (LSF/Symphony), preemption is **not** always enabled; it's controlled by parameter: LSF is Queue level, Symphony is Job/Session level.

There maybe more requests on fine-grained preemption, e.g. PriorityClass_1 can only preempt PriorityClass_2. But prefer to control the scope right now, and use annotation for further enhancement.
