### ISSUE TITLE
Portworx volume plugin panics when a PVC is created using a  StorageClass with empty parameters

### ISSUE THREAD

**Issue by harsh-px** [kubernetes/kubernetes#64894]
**BUG REPORT**:

Portworx volume plugin when a PVC is created using a  StorageClass with empty parameters

/kind bug

**What happened**:

Create a StorageClass using empty parameters and then create a PVC using that storage class. The  PVC will remain in pending state. On inspecting the logs of the controller manager, we find that the portworx volume plugin is panicing.

```
Jun 06 23:59:57 mr85p00it-inhi03170901.rock.apple.com kube-controller-manager[24757]: I0606 23:59:57.341660   24757 portworx_util.go:55] Creating Portworx volume for PVC: postgres-data-dse2
Jun 06 23:59:57 mr85p00it-inhi03170901.rock.apple.com kube-controller-manager[24757]: E0606 23:59:57.341867   24757 goroutinemap.go:150] Operation for "provision-default/postgres-data-dse2[40c3e7f3-69e4-11e8-9d8b-6c92bf4db11e]" failed. No retries permitted until 2018-06-06 23:59:57.841769551 +0000 UTC m=+1380488.336954143 (durationBeforeRetry 500ms). Error: "recovered from panic \"assignment to entry in nil map\". (err=<nil>) Call stack:\n/code/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72\n/code/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:155\n/usr/local/go/src/runtime/asm_amd64.s:509\n/usr/local/go/src/runtime/panic.go:491\n/usr/local/go/src/runtime/hashmap_fast.go:776\n/code/_output/local/go/src/k8s.io/kubernetes/pkg/volume/portworx/portworx_util.go:92\n/code/_output/local/go/src/k8s.io/kubernetes/pkg/volume/portworx/portworx.go:365\n/code/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go:1429\n/code/_output/local/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go:1326\n/code/_output/local/go/src/k8s.io/kubernetes/pkg/util/goroutinemap/goroutinemap.go:115\n/usr/local/go/src/runtime/asm_amd64.s:2337\n"
```

**What you expected to happen**: PVC should have been created successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Create following storage class and PVC
```
##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
    name: px-nginx-sc
provisioner: kubernetes.io/portworx-volume
parameters:
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-nginx-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: px-nginx-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi

```

**Anything else we need to know?**: 

**Environment**: N/A
- Kubernetes version (use `kubectl version`): 1.9.7, 1.10.1, 1.8.8
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
