### ISSUE TITLE
The CPU soared when k8s created depolyment

### ISSUE THREAD

**Issue by braveCS** [kubernetes/kubernetes#64914]
At begining k8s create deployment is fast, load average is 0.xx, 0.xx,0.xx.  But when with 20+pod in cluster, load average is 20+ in the deployment creating phase, and load average calm down to 0.xx,0.xx,0.xx after about 10min.  

the deployement declare just include base metadata and image : 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edi-bdio
  namespace: dev-v3
  labels:    
    app: edi-bdio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edi-bdio
  template:
    metadata:
      labels:
        app: edi-bdio
    spec:
      containers:
      - name: edi-bdio
        imagePullPolicy: Never 
        image: 192.168.52.7/open/edi-bdio:v4.4.008
        env:
        - name: environmentName
          valueFrom:
            configMapKeyRef:
              name: dev-v3-env
              key: environmentName
        - name: zookeeperUrl
          valueFrom:
            configMapKeyRef:
              name: dev-v3-env
              key: zookeeperUrl
        - name: applicationName
          valueFrom:
            configMapKeyRef:
              name: dev-v3-env
              key: edi-bdio.applicationName
        - name: port
          valueFrom:
            configMapKeyRef:
              name: dev-v3-env
              key: edi-bdio.port
        ports:
        - containerPort: 31006
```

0.  no other processes  run when k8s creating deployment. 
1.  just use `docker run `to deployment application image, the load average also  0.xx, 0.xx, 0.xx
2.  whatever the image is on cloud or in local, the result is all the same
3. kubelet , docker-engine , 'docker process in pod'  cost the  average 100+%cpu in the special time.
4. kubelet log just print some mount log, no error no warning 

Environment:
- k8s version: 1.9.3
- docker version : 1.12.5
- 192.168.52.7:  memory: 4G, 2G*4cpu,  linux 3.10.0 ,  master+harbor+etcd
- 192.168.52.8:  memory: 4G, 2G*4cpu,  linux 3.10.0 ,  node
- 192.168.52.9:  memory: 4G, 2G*4cpu,  linux 3.10.0 ,  node

/sig node
