### ISSUE TITLE
container OOM cause kubelet NotReady

### ISSUE THREAD

**Issue by weiwei04** [kubernetes/kubernetes#64975]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

container OOMKilled cause docker stuck and kubelet become NotReady

**What you expected to happen**:

kubelet recreate OOMKilled container

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```yaml
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from /etc/os-release):

- Kernel (e.g. `uname -a`):

Linux hostname 4.4.131-1.el7.elrepo.x86_64 #1 SMP Wed May 2 13:09:02 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

kubeadm

- Others:

docker version
```yaml
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

[dmesg](https://gist.github.com/weiwei04/7e0bafe11a13615f86b1ebf4a2815e62) shows the pod's container got killed due to oom

containerd stacktrace shows containerd hold the [m.monitor.Lock()](https://github.com/docker/containerd/blob/v0.2.3/supervisor/monitor_linux.go#L103) stuck at a [syscall.Read(fd, buf)](https://github.com/docker/containerd/blob/v0.2.3/runtime/container.go#L669) cause containerd can't create new container(wait at [m.montor.Lock](https://github.com/docker/containerd/blob/v0.2.3/supervisor/worker.go#L59))

I just't don't know why the syscall.Read will stuck, since this fd is wake up from a epoll_wait.
