### ISSUE TITLE
static pods can mount pvc *sometimes*

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#65004]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
Not very sure about this, but it's behavior is not so good to me.

> /kind feature

**What happened**:
Static pods can mount pvc when a normal pod with the same pvc is scheduled to the same node.

**What you expected to happen**:
The behavior should be consistent.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a pvc
2. create a normal pod and mount the pvc in step 1
```
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: myclaim
  containers:
    - name: example
      image: busybox
      command: ["sleep", "10000"]
      volumeMounts:
        - name: nfsvol
          mountPath: /nfs
          subPath: container-example/pod-example
```
3. Check where the normal pod is scheduled.
4. In the node where the previous pod is scheduled, we create a static pod, mount the nfsvol pvc again:
```
kind: Pod
apiVersion: v1
metadata:
  name: my-test-pod
  namespace: default
spec:
  volumes:
  - name: nfsvol
    persistentVolumeClaim:
      claimName: myclaim
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - sleep
        - "36000"
  volumeMounts:
  - name: nfsvol
    mountPath: /nfs
  restartPolicy: Always
```
5. check the running containers with command `docker ps`, we can see the container runs successfully.

**Anything else we need to know?**:
The static pod and normal pod should be in the same namespace.

**Environment**:
community master
