### ISSUE TITLE
Cannot disable healthz port on kube-proxy when using config file

### ISSUE THREAD

**Issue by wsong** [kubernetes/kubernetes#65118]
**What happened**:

If I use a `KubeProxyConfiguration` file with `kube-proxy` an pass in the `--config` flag, I can't disable the healthz port. My `KubeProxyConfiguration` looks like this:

```
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clusterCIDR: "<cluster CIDR>"
healthzBindAddress: ""
iptables:
  masqueradeBit: 30
clientConnection:
  kubeconfig: "<kube config file>"
```

Even though `healthzBindAddress` is set to an empty string, `kube-proxy` still starts a healthz server on port 10256.

**What you expected to happen**:
The kube-proxy binary would not expose a healthz port

**How to reproduce it (as minimally and precisely as possible)**:
Start `kube-proxy` with `--config <config file path>` with the above config file.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.11.0-beta.0
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
Ubuntu 16.04
- Kernel (e.g. `uname -a`):
`Linux wsong-testkit-C24B51-ubuntu-0 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
