### ISSUE TITLE
Auto convert int to string

### ISSUE THREAD

**Issue by PureWhiteWu** [kubernetes/kubernetes#65112]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When I want to run a command like this:
```
...
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - 3600 
...
```
It will fail with this information:
```
error: deployments "busybox" could not be patched: cannot convert int64 to string
You can run `kubectl replace -f /var/folders/8d/0bh4wdr93g50cf_xwtx12gr80000gn/T/kubectl-edit-kxlm5.yaml` to try this update again.
```
If I use this instead, it works well:
```
...
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - "3600"
...
```

**What you expected to happen**:

Kubernetes should auto convert the int to string

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - 3600
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.4
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release): osx
- Kernel (e.g. `uname -a`): Darwin Pure-White-mbp.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
- Install tools: minikube
- Others:
