### ISSUE TITLE
Why host access and IP access are different certificates?

### ISSUE THREAD

**Issue by j2eegis** [kubernetes/kubernetes#65146]
**Why host access and IP access are different certificatesT?**:
/kind bug
/sig ingress
/cc @aledbf 
nginx-ingress.yaml file
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  tls:
  - secretName: ingress-secret
  rules:
  - host: a.b.com
    http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: 8080
```
**The IP of a.b.com is 192.168.1.12, when a.b.com is accessed, the certificate returned is "ingress-secret" correct.  when 192.168.1.12 is accessed, the certificate returned is default incorrect. why ? How to set it to the same?**
this is a.b.com access
![domain](https://user-images.githubusercontent.com/4994809/41477609-662a863c-70f7-11e8-9def-731cc0964dd8.jpg)

this is ip access
![ip](https://user-images.githubusercontent.com/4994809/41477620-6cdd487a-70f7-11e8-8912-a1853447ddb5.jpg)
