### ISSUE TITLE
ClusterRole aggregation ignore own rules

### ISSUE THREAD

**Issue by MasayaAoyama** [kubernetes/kubernetes#65171]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/kind feature

**What happened**:
for example, we cannot get "pods" rule at sample-aggregated-role.

```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sub-clusterrole1
  labels:
    app: sample-rbac
rules:
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["get"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sub-clusterrole2
  labels:
    app: sample-rbac
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sample-aggregated-role
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      app: sample-rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
```

after that,
```
$ kubectl get clusterrole sample-aggregated-role -o yaml
...
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
```

**What you expected to happen**:
I think we need pods rules.

```
$ kubectl get clusterrole sample-aggregated-role -o yaml
...
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
```

**How to reproduce it (as minimally and precisely as possible)**:
any

**Anything else we need to know?**:
This is specification?
I think this is a bug. But if it is specification, I would like to add this function.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.4
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
