### ISSUE TITLE
How get stateful ordinal index when work in hostNetwork ?

### ISSUE THREAD

**Issue by fananchong** [kubernetes/kubernetes#65213]
for example:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  selector:
    matchLabels:
      app: service-b
  replicas: 3
  template:
    metadata:
      labels:
        app: service-b
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: service-b
        image: busybox
        command: ["sleep", "36000000"]

---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  ports:
    - port: 3456
  clusterIP: None
  selector:
    app: service-b
```

run shell:
```shell
kubectl exec service-b-0 -- sh -c 'hostname'
```
it show node‘s name, not stateful pod's name: service-b-0
