### ISSUE TITLE
how to communicate with daemon pods by service

### ISSUE THREAD

**Issue by jiuchongxiao** [kubernetes/kubernetes#65268]
how to communicate with daemon pods by service,not endpoint method.
as offical said 
`Create a service with the same Pod selector, and use the service to reach a daemon on a random node. (No way to reach specific node.)`
 
i test as below,but it did not work.

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  selector:
    matchLabels:
      name: my-nginx
  template:
    metadata:
      labels:
        name: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

```

```

apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  clusterIP: 10.43.181.60
  selector:
    run: my-nginx

```
