### ISSUE TITLE
StatefulSet: how to set Pod from Statefulset to node.

### ISSUE THREAD

**Issue by alnikyur** [kubernetes/kubernetes#65267]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:r
Hello to everyone! I tried to found solution how to point on concrete `Pod` from `StatefulSet` to concrete `Node`. For example,  we have 3 nodes, each node has labels node-0, node-1, node-2 and StatefulSet has 3 Pods with labels app-0, app-1, app-2 (this is just for example). My question is - how to select concrete Pod from StatefulSet (for example with label app-0) and assign it to Node with label node-0. In official and unofficial docs of kubernetes i didn't find how to solve this issue. If this functionality is not implemented yet  - it will be very great if it is implemented in next releases.

**What you expected to happen**:
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
/sig scalability

**Comment by jiaxuanzhou** [comment]
this is an interesting scenario, but currently k8s does not support it, but we could implement it by configure the nodeSelector key and value from podName(like envFrom) and target nodeName, but this could change the core api.

**Comment by alnikyur** [comment]
@jiaxuanzhou Thanks for your fast reply. It will be nice if this functionality will be implement in next release!

**Comment by nikhilk** [comment]
Would this ability to map pods to nodes work by specifying node selector, or toleration metadata on the pod spec template within a StatefulSet? Or does that not work when using StatefulSets?

**Comment by jiaxuanzhou** [comment]
@nikhilk Is does not work just set the nodeSelector in template of StatefulSet, as the nodeSelector is just specify the nodes not for the case of specific  pod to one node:
`pod app-0 to node0
pod app-1 to node 1
pod app-2 to node-2`

**Comment by gabrielfsousa** [comment]
i would luv to have this feature ....
any workaround ?

**Comment by shurshun** [comment]
I'm too. It's really useful for bare metal installations with local volumes.

**Comment by gabrielfsousa** [comment]
i post it here a solution, is working, but isnt not perfect, i will make a init container to not start if the pod isnt on the right host.

https://github.com/gabrielfsousa/zookeeper-kafka-kubernetes

**Comment by Pingan2017** [comment]
ping  @@kubernetes/sig-apps-feature-requests @@kubernetes/sig-scheduling-feature-requests Can someone take a look ?

**Comment by nerumo** [comment]
@bsalamat yes, that's my scenario. I know that storages shouldn't be handled that way, but I can't afford to build a storage cluster

**Comment by k82cn** [comment]
for such a statefulset, does each node equal with each other?

**Comment by sftim** [comment]
(it's an old issue; recently, some similar issues got raised)
If someone makes a CustomResourceDefinition to implement this, that could work. Maybe an Add-on?

Also, I hope the CRD gets called _StatefulPet_. :wink:

**Comment by 2qif49lt** [comment]
any progress?  
there are many scenes need this "feature". 
like: hdfs's datanode with local host data folder,  as clickhouse and minio which perfer to handle data locally.

**Comment by jsalatiel** [comment]
It would be nice to have this. Storage specificities.

**Comment by rad1k4l** [comment]
You can use the following [KubeMod](https://github.com/kubemod/kubemod) ModRule:

``` YML
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: statefulset-pod-node-affinity
spec:
  type: Patch

  match:
    # Select pods named myapp-xxx.
    - select: '$.kind'
      matchValue: Pod
    - select: '$.metadata.name'
      matchRegex: myapp-.*

  patch:
    # Patch the selected pods such that their node affinity matches nodes that contain a label with the name of the pod.
    - op: add
      path: /spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution
      value: |-
        nodeSelectorTerms:
          - matchExpressions:
            - key: accept-pod/{{ .Target.metadata.name }}
              operator: In
              values:
                - 'true'
```
