### ISSUE TITLE
Big Bug

### ISSUE THREAD

**Issue by qiyongxiao** [kubernetes/kubernetes#65261]
In docker, there is some containers for kubernetes, I create some service, it doesn't to work.For this:
kubernetes-dashboard.yaml and dashboard service.
```
[root@master2 ~]# docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy-amd64                   v1.10.4             3f9ff47d0fca        13 days ago         97.1 MB
k8s.gcr.io/kube-scheduler-amd64               v1.10.4             6fffbea311f0        13 days ago         50.4 MB
k8s.gcr.io/kube-apiserver-amd64               v1.10.4             afdd56622af3        13 days ago         225 MB
k8s.gcr.io/kube-controller-manager-amd64      v1.10.4             1a24f5586598        13 days ago         148 MB
k8s.gcr.io/heapster-amd64                     v1.5.3              f57c75cd7b0a        7 weeks ago         75.3 MB
k8s.gcr.io/etcd-amd64                         3.1.12              52920ad46f5b        3 months ago        193 MB
docker.io/qiqisa/kubernetes-dashboard-amd64   v1.8.3              0c60bcf89900        4 months ago        102 MB
k8s.gcr.io/kubernetes-dashboard-amd64         v1.8.3              0c60bcf89900        4 months ago        102 MB
k8s.gcr.io/pause-amd64                        3.1                 da86e6ba6ca1        6 months ago        742 kB
k8s.gcr.io/heapster-influxdb-amd64            v1.3.3              577260d221db        9 months ago        12.5 MB
k8s.gcr.io/heapster-grafana-amd64             v4.4.3              8cb3de219af7        9 months ago        152 MB

 kubectl create -f kubernetes-dashboard.yaml 
```
```
# ------------------- Dashboard Secret ------------------- #

apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard-certs
  namespace: kube-system
type: Opaque

---
# ------------------- Dashboard Service Account ------------------- #

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system

---
# ------------------- Dashboard Role & Role Binding ------------------- #

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-dashboard-minimal
  namespace: kube-system
rules:
  # Allow Dashboard to create 'kubernetes-dashboard-key-holder' secret.
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
  # Allow Dashboard to create 'kubernetes-dashboard-settings' config map.
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]
  # Allow Dashboard to get, update and delete Dashboard exclusive secrets.
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["kubernetes-dashboard-key-holder", "kubernetes-dashboard-certs"]
  verbs: ["get", "update", "delete"]
  # Allow Dashboard to get and update 'kubernetes-dashboard-settings' config map.
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["kubernetes-dashboard-settings"]
  verbs: ["get", "update"]
  # Allow Dashboard to get metrics from heapster.
- apiGroups: [""]
  resources: ["services"]
  resourceNames: ["heapster"]
  verbs: ["proxy"]
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames: ["heapster", "http:heapster:", "https:heapster:"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-dashboard-minimal
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-dashboard-minimal
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system

---
# ------------------- Dashboard Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
    spec:
      containers:
      - name: kubernetes-dashboard
        image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.3
        ports:
        - containerPort: 8443
          protocol: TCP
        args:
          - --auto-generate-certificates
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          # - --apiserver-host=http://my-address:port
        volumeMounts:
        - name: kubernetes-dashboard-certs
          mountPath: /certs
          # Create on-disk volume to store exec logs
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /
            port: 8443
          initialDelaySeconds: 30
          timeoutSeconds: 30
      volumes:
      - name: kubernetes-dashboard-certs
        secret:
          secretName: kubernetes-dashboard-certs
      - name: tmp-volume
        emptyDir: {}
      serviceAccountName: kubernetes-dashboard
      # Comment the following tolerations if Dashboard must not be deployed on master
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

---
# ------------------- Dashboard Service ------------------- #

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
```

Then show the pods status----------dashboard always display ContainerCreating
```
[root@master2 ~]# kubectl   get pods --all-namespaces -o wide
NAMESPACE     NAME                                    READY     STATUS              RESTARTS   AGE       IP               NODE
kube-system   kube-apiserver-master1                  1/1       Running             27         2h        192.168.83.128   master1
kube-system   kube-apiserver-master2                  1/1       Running             30         2h        192.168.83.129   master2
kube-system   kube-controller-manager-master1         1/1       Running             13         2h        192.168.83.128   master1
kube-system   kube-controller-manager-master2         1/1       Running             14         2h        192.168.83.129   master2
kube-system   kube-scheduler-master1                  1/1       Running             13         2h        192.168.83.128   master1
kube-system   kube-scheduler-master2                  1/1       Running             15         2h        192.168.83.129   master2
kube-system   kubernetes-dashboard-6f4d97b9b8-2bwqh   0/1       ContainerCreating   0          5m        <none>           master2
```
And I see the docker log:
```
Jun 20 16:18:55 master2 oci-umount[19696]: umounthook <debug>: prestart container_id:558fcddddce9 rootfs:/var/lib/docker/overlay2/df42eed3d4a8f95a51076a4bb2f941c0345266dac958393eb36de45fa58e4329/merged
Jun 20 16:18:55 master2 dockerd-current[116453]: Shutting down, got signal: Terminated
Jun 20 16:18:55 master2 dockerd-current[116453]: time="2018-06-20T16:18:55.374562257+08:00" level=error msg="containerd: deleting container" error="exit status 1: \"container 558fcddddce90a0a59295e9cff11bb673e81711f666aba2aaf74b79a4f6d5919 does not exist\\none or more of the container deletions failed\\n\""
Jun 20 16:18:55 master2 dockerd-current[116453]: time="2018-06-20T16:18:55.390732037+08:00" level=warning msg="558fcddddce90a0a59295e9cff11bb673e81711f666aba2aaf74b79a4f6d5919 cleanup: failed to unmount secrets: invalid argument"
Jun 20 16:18:56 master2 dockerd-current[116453]: time="2018-06-20T16:18:56.107284237+08:00" level=error msg="Handler for POST /v1.26/containers/558fcddddce90a0a59295e9cff11bb673e81711f666aba2aaf74b79a4f6d5919/stop returned error: Container 558fcddddce90a0a59295e9cff11bb673e81711f666aba2aaf74b79a4f6d5919 is already stopped"
```

How did Why?
