### ISSUE TITLE
Pod not using Deployment imagePullPolicy setting

### ISSUE THREAD

**Issue by y325A** [kubernetes/kubernetes#65305]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Pod created from a Deployment has the imagePullPolicy property set to "Always" - whereas the Deployment has the property set to "IfNotPresent"

When pods are started from these deployments, there is a spike of network traffic and disk activity on the host - I'm running on Windows so this makes the situation worse as the images are bigger and take longer to pull.

**What you expected to happen**:
Pods to respect the Deployment imagePullPolicy.

**How to reproduce it (as minimally and precisely as possible)**:
Deployment YAML:
```
apiVersion: extensions/v1beta1
kind: Deployment
** SNIP **
spec:
** SNIP **
      containers:
** SNIP **
        imagePullPolicy: IfNotPresent
        name: myapplication
        resources:
          limits:
            cpu: 100m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 1000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: Default
      imagePullSecrets:
      - name: containerregistry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
** SNIP **
```

Pod scheduled from Deployment YAML:
```
apiVersion: v1
kind: Pod
** SNIP **
spec:
** SNIP **
  containers:
** SNIP **
    image: myreg/image:5481-release-5.10
    imagePullPolicy: Always
** SNIP **
```

**Anything else we need to know?**:
All deployments have the image tag set using a specific version (not using latest).

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10.3
- Cloud provider or hardware configuration:
acs-engine 0.17.1
- OS (e.g. from /etc/os-release):
Windows 2016 1803

**Comment by PatrickLang** [comment]
@y325A - is this a Windows-only problem, or do you see a network traffic spike on Linux as well?

**Comment by PaulCharlton** [comment]
Hey - I am seeing the exact same issue on Ubuntu nodes deployed with Azure CNI.  The pods are showing "imagePullPolicy: Always" even when the deployment is showing "imagePullPolicy: IfNotPresent"

**Comment by CecileRobertMichon** [comment]
@PaulCharlton @y325A is it possible that you have `AlwaysPullImages` set in your admission controller? https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages

**Comment by PaulCharlton** [comment]
@CecileRobertMichon thanks for writing -- yep -- that's what we found a few days ago and already patched the acs confit -- apologies for not updating my comment

**Comment by benmoss** [comment]
This sounds like more of an acs-engine issue than a kubernetes one, but it sounds like it's more just a case of some surprising defaults.

**Comment by alexfouche** [comment]
Well, as now in 2023 with Kubernetes 1.25, i am still seeing this same issue, and logs that image is pulled nevertheless. Kubernetes might not be really pulling the image given the timings, bit it is confusing a lot: 

`kubectl describe pod/graphhopper-wip-6cd76b8d55-wdwkh` :
```
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  5m4s   default-scheduler  Successfully assigned graphhopper-wip/graphhopper-wip-6cd76b8d55-wdwkh to k8s-platform1-np01-node-c40c2f
  Normal  Pulling    5m2s   kubelet            Pulling image "curlimages/curl:7.87.0"
  Normal  Pulled     5m1s   kubelet            Successfully pulled image "curlimages/curl:7.87.0" in 644.823033ms
  Normal  Created    5m1s   kubelet            Created container download-data
  Normal  Started    5m1s   kubelet            Started container download-data
  Normal  Pulling    5m     kubelet            Pulling image "israelhikingmap/graphhopper:6.2"
  Normal  Pulled     4m59s  kubelet            Successfully pulled image "israelhikingmap/graphhopper:6.2" in 690.093251ms
  Normal  Created    4m59s  kubelet            Created container graphhopper-wip
  Normal  Started    4m59s  kubelet            Started container graphhopper-wip
```

The deployment definition is as follow:

```yaml
kind: Deployment
# (...)
spec:
  template:
    # (...)
    spec:
      containers:
        image: israelhikingmap/graphhopper:6.2
        imagePullPolicy: IfNotPresent
      initContainers:
        image: curlimages/curl:7.87.0
        imagePullPolicy: IfNotPresent
# (...)
```

The resulting pod shows an `imagePullPolicy: Always`

```yaml
# k get  pod/graphhopper-wip-6cd76b8d55-wdwkh -o yaml
spec:
  automountServiceAccountToken: true
  containers:
    image: israelhikingmap/graphhopper:6.2
    imagePullPolicy: Always
  initContainers:
    image: curlimages/curl:7.87.0
    imagePullPolicy: Always
```
