### ISSUE TITLE
Init container security context extended to containers

### ISSUE THREAD

**Issue by sylr** [kubernetes/kubernetes#65314]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Created a deployment with an `initContainer` which has a privileged security context and this privileged context extended to the container of the deployment.

**What you expected to happen**:

That the security context defined for initContainers does not extend to containers.

**How to reproduce it (as minimally and precisely as possible)**:

Deployment

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app: docker-elasticsearch
    release: docker-elasticsearch
    storage: docker-elasticsearch
  name: docker-elasticsearch
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: docker-elasticsearch
      release: docker-elasticsearch
      storage: docker-elasticsearch
  serviceName: internal
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docker-elasticsearch
        release: docker-elasticsearch
        storage: docker-elasticsearch
    spec:
      containers:
      - image: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/docker-elasticsearch:0.0.0.12
        imagePullPolicy: Always
        name: pod
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/data
          name: data
        - mountPath: /data/logs
          name: log
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/docker-elasticsearch:0.0.0.12
        imagePullPolicy: Always
        name: init-pod
        resources: {}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-docker-elasticsearch
      - name: log
        persistentVolumeClaim:
          claimName: log-docker-elasticsearch
  updateStrategy:
    type: OnDelete
```

```shell
$ kubectl exec docker-elasticsearch-0 -it bash
Error from server (Forbidden): pods "docker-elasticsearch-0" is forbidden: cannot exec into or attach to a privileged container
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.2
- Cloud provider or hardware configuration: Azure 
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Install tools: acs-engine

**Comment by php-coder** [comment]
> Error from server (Forbidden): pods "docker-elasticsearch-0" is forbidden: cannot exec into or attach to a privileged container

Are you sure that "docker-elasticsearch-0" is the name of your pod? Your containers should have names like `pod-0` as far I can see.

**Comment by sylr** [comment]
> Are you sure that "docker-elasticsearch-0" is the name of your pod? Your containers should have names like pod-0 as far I can see.

Yes that's the name of the pod (This pod is part of a `StatefulSet` instead of a `Deployment` hence the name) and there is only one container in it besides the initContainer.

**Comment by kichristensen** [comment]
I have the same issue I'll post the details when I get back to my computer. In this case it is the istio sidecar that uses a privileged init container, a pod without the sidecar doesn't have this issue

**Comment by kichristensen** [comment]
Here is the details.

I'm running Kubernetes 1.10.3.

My deployment looks like this:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: echo
  name: echo-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: XXX/echo:2.0
        imagePullPolicy: Always
        name: echo-container
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: simcorp-registry
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

Because of the automatic Istio sidecar injection the the resulting pod, looks like this, as you can see the init container is privileged:
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/status: '{"version":"55c9e544b52e1d4e45d18a58d0b34ba4b72531e45fb6d1572c77191422556ffc","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
  labels:
    app: echo
  name: echo-deployment-57d5c75958-prtsp
  namespace: default
spec:
  containers:
  - image: XXXX/echo:2.0
    imagePullPolicy: Always
    name: echo-container
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-8x5xs
      readOnly: true
  - args:
    - proxy
    - sidecar
    - --configPath
    - /etc/istio/proxy
    - --binaryPath
    - /usr/local/bin/envoy
    - --serviceCluster
    - echo
    - --drainDuration
    - 45s
    - --parentShutdownDuration
    - 1m0s
    - --discoveryAddress
    - istio-pilot.istio-system:15007
    - --discoveryRefreshDelay
    - 10s
    - --zipkinAddress
    - zipkin.telemetry:9411
    - --connectTimeout
    - 10s
    - --statsdUdpAddress
    - istio-statsd-prom-bridge.istio-system:9125
    - --proxyAdminPort
    - "15000"
    - --controlPlaneAuthPolicy
    - NONE
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: ISTIO_META_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    image: docker.io/istio/proxyv2:0.8.0
    imagePullPolicy: IfNotPresent
    name: istio-proxy
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /etc/certs/
      name: istio-certs
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: simcorp-registry
  initContainers:
  - args:
    - -p
    - "15001"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - '*'
    - -x
    - ""
    - -b
    - 80,
    - -d
    - ""
    image: docker.io/istio/proxy_init:0.8.0
    imagePullPolicy: IfNotPresent
    name: istio-init
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeName: k8s-linuxpool-30369698-2
  nodeSelector:
    beta.kubernetes.io/os: linux
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-8x5xs
    secret:
      defaultMode: 420
      secretName: default-token-8x5xs
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - name: istio-certs
    secret:
      defaultMode: 420
      optional: true
      secretName: istio.default
```

When I try to exec into the pod:
```
> kubectl exec -it echo-deployment-57d5c75958-prtsp /bin/sh
Defaulting container name to echo-container.
Use 'kubectl describe pod/echo-deployment-57d5c75958-prtsp -n default' to see all of the containers in this pod.
Error from server (Forbidden): pods "echo-deployment-57d5c75958-prtsp" is forbidden: cannot exec into or attach to a privileged container
```

Also if I try to specify the specific container:
```
> kubectl exec -it echo-deployment-57d5c75958-prtsp -c echo-container /bin/sh
Error from server (Forbidden): pods "echo-deployment-57d5c75958-prtsp" is forbidden: cannot exec into or attach to a privileged container
```
