### ISSUE TITLE
Unexpected pod CPU requests when only limits is set in Deployment

### ISSUE THREAD

**Issue by zihaoyu** [kubernetes/kubernetes#65347]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I have a `Deployment` with container's `resources.limits.cpu = 200m`. However the pods have both `limits` and `requests` set to `200m`.
```
$ kubectl get deploy nginx-ingress -n default -o jsonpath='{.spec.template.spec.containers[0].resources}'
map[limits:map[cpu:200m]]

$ kubectl get pod nginx-ingress-79b566d498-bd948 -n default -o jsonpath='{.spec.containers[0].resources}'
map[limits:map[cpu:200m] requests:map[cpu:200m]]
```

**What you expected to happen**:

Pod's `requests` is not set just like the `Deployment`'s template. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Apply the following YAML
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        resources:
          limits:
            cpu: 200m
```
2. Observe the new pods 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.3
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS 1688.5.0
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
