### ISSUE TITLE
Extract environment variables from a file

### ISSUE THREAD

**Issue by jeusdi** [kubernetes/kubernetes#65352]
I'd like to know whether I'm able to propagate environment variables from a file.

Guess I have a file like this:

    ENV_VARIABLE_USERNAME: username
    ENV_VARIABLE_PASSWORD: password

I'd like this content file is propagated as environment variables.

Is it possible?

**Comment by CaoShuFeng** [comment]
```
kubectl create configmap my-config --from-env-file=a.config
```

And in the pod spec:
```
  containers:
    - name: example
      image: busybox
      envFrom:
        - configMapRef:
            name: my-config
```

FYI: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
