### ISSUE TITLE
Resource Quota Manager missed caculating Uninitialized pods

### ISSUE THREAD

**Issue by DylanBLE** [kubernetes/kubernetes#65378]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
Resource Quota Manager missed caculating Uninitialized pods.

**What you expected to happen**:
Resource Quota Manager takes Uninitialized pods into account.
The quota used status should record Uninitialized pods.

**How to reproduce it (as minimally and precisely as possible)**:
### 1. create a resource quota
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-quota
spec:
  hard:
    cpu: "1"
    memory: 500Mi
    pods: "5"
    resourcequotas: "1"
```
### 2. create an uninitialized pod
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  initializers:
    pending:
    - name: podtest.example.com
spec:
  containers:
    - name: redis
      image: redis:3.0.5
      resources:
        requests:
          cpu: "0.5"
          memory: 500Mi
        limits:
          cpu: "0.5"
          memory: 500Mi
```
APIServer will return a 504 error but pod has already created, you can list pods with "IncludeUninitialized=true" option.
### 3. view quota usage
At first, quota usage is as expected.
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-quota
  namespace: default
spec:
  hard:
    cpu: "1"
    memory: 500Mi
    pods: "5"
    resourcequotas: "1"
status:
  hard:
    cpu: "1"
    memory: 500Mi
    pods: "5"
    resourcequotas: "1"
  used:
    cpu: "0.5"
    memory: 500Mi
    pods: "1"
    resourcequotas: "1"
```
Unfortunately, after a while , the quota usage changed as follows.
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-quota
  namespace: default
spec:
  hard:
    cpu: "1"
    memory: 500Mi
    pods: "5"
    resourcequotas: "1"
status:
  hard:
    cpu: "1"
    memory: 500Mi
    pods: "5"
    resourcequotas: "1"
  used:
    cpu: "0"
    memory: 0
    pods: "0"
    resourcequotas: "1"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
 v 1.9.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
