### ISSUE TITLE
cant connect to mysql with service name

### ISSUE THREAD

**Issue by zong400** [kubernetes/kubernetes#65430]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I can telnet 3306 port ,but cant connect to mysql with service name.
is happen when the mysql client and mysql server in same node.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
root@mysqlclient-k8s-dev-node2:/bin# telnet 10.22.0.39 3306
Trying 10.22.0.39...
Connected to 10.22.0.39.
Escape character is '^]'.
J
5.7.22BM%uhiS%@q 
                  kmg\
                      mysql_native_password

^CConnection closed by foreign host.
root@mysqlclient-k8s-dev-node2:/bin# 
root@mysqlclient-k8s-dev-node2:/bin# 
root@mysqlclient-k8s-dev-node2:/bin# telnet wbyb-rds-dev 3306
Trying 192.168.10.206...
Connected to wbyb-rds-dev.bxr-dev.svc.k8sdev.local.
Escape character is '^]'.
J
5.7.22Cv'GMS3<%*L(U`{k0^mysql_native_password

^CConnection closed by foreign host.
root@mysqlclient-k8s-dev-node2:/bin# 
root@mysqlclient-k8s-dev-node2:/bin# mysql -h wbyb-rds-dev -u banxiaoer -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'banxiaoer'@'172.31.0.165' (using password: YES)
root@mysqlclient-k8s-dev-node2:/bin# 
```
172.31.0.165 is mysqlclient-k8s-dev-node2 pod's ip

**Anything else we need to know?**:
mysql is a static pod
```
apiVersion: v1
kind: Pod
metadata:
  name: dev-mysql
  namespace: bxr-dev
  labels:
    app: mysql
spec:
  hostNetwork: true 
  containers:
  - name: mysql
    image: mysql:5.7
    ports:
    -  containerPort: 3306
    volumeMounts:
    -  name: data
       mountPath: /var/lib/mysql
    -  name: mysqldconf
       mountPath: /etc/mysql/mysql.conf.d
  volumes:
  - name: data
    hostPath:
      path: /data/dev-mysql
  - name: mysqldconf
    hostPath:
      path: /etc/mysql/mysql.conf.d
```
nslookup is ok
```
root@filebeat-bxr-7dd85f588f-xhglg:/# nslookup wbyb-rds-dev
Server:         192.168.10.2
Address:        192.168.10.2#53

Name:   wbyb-rds-dev.bxr-dev.svc.k8sdev.local
Address: 192.168.10.14
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
ubuntu16.04
- Kernel (e.g. `uname -a`):
Linux k8s-dev-m1 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:
