### ISSUE TITLE
Bug: non-existent secrets are mounted as a 777 mode directory

### ISSUE THREAD

**Issue by mrak** [kubernetes/kubernetes#65452]
**BUG REPORT**:

/kind bug

**What happened**:

Mounting non-existent `data` objects from a `Secrets` object into a container produces a directory at the mount point with 777 permissions. 

**What you expected to happen**:

The Pod to fail to start due to missing mounts from the secrets object.

**How to reproduce it (as minimally and precisely as possible)**:

The secret `data` object in question is `my-file` being mounted to `/secrets/my-file` within a container.

Apply the following configuration:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-delete-me
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
  namespace: test-delete-me
data: {}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test-delete-me
  namespace: test-delete-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-delete-me
  template:
    metadata:
      labels:
        app: test-delete-me
      name: test-delete-me
      namespace: test-delete-me
    spec:
      volumes:
        - name: test-secrets
          secret:
            secretName: test-secrets
            defaultMode: 0600
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: test-secrets
              readOnly: true
              mountPath: /secrets/my-file
              subPath: my-file
```

Then examine the files mounted within the container:

```
$ kubectl exec -it -n test-delete-me test-delete-me-<hash>-<hash> -- ls -l /secrets
total 0
drwxrwxrwt 2 root root 40 Jun 25 22:04 my-file
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `1.10.5`
- Cloud provider or hardware configuration: AWS VPC
- OS (e.g. from /etc/os-release): Debian (jessie)
- Kernel (e.g. `uname -a`): `4.4.0-1-amd64`
- Install tools:
- Others:
