### ISSUE TITLE
Invalid regex in OpenAPI validation crashes API server

### ISSUE THREAD

**Issue by kivoli** [kubernetes/kubernetes#65470]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Created custom resource definition with invalid regex validation and custom resource. During creation of custom resource the API server crashes (and is successfully restarted, luckily) due to the invalid regex.

```
% kubectl apply -f /tmp/boom.yaml    
error: error when creating "/tmp/boom.yaml": Post https://k8s.invalid:6443/apis/k8s.invalid/v1/namespaces/default/booms: unexpected EOF; some request body already written
```
API pod log:
```
runtime.go:66] Observed a panic: "regexp: Compile(`+`): error parsing regexp: missing argument to repetition operator: `+`" (regexp: Com
pile(`+`): error parsing regexp: missing argument to repetition operator: `+`)
```

**What you expected to happen**:

Server reporting meaning full error, ideally during creation of custom resource definition. In any case: Do not panic and crash.

**How to reproduce it (as minimally and precisely as possible)**:

Create a custom resource definition:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: booms.k8s.invalid
spec:
  group: k8s.invalid
  version: v1
  scope: Namespaced
  names:
    plural: booms
    singular: boom
    kind: Boom
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            boom:
              type: string
              pattern: '+'
```

Then create a custom resource:
```yaml
apiVersion: "k8s.invalid/v1"
kind: Boom
metadata:
  name: boomerang
spec:
  boom: boom
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Debian Stretch
- Kernel (e.g. `uname -a`): 
`Linux <fqdn> 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux`
- Install tools: kubeadm
- Others: Using containerd via CRI
