### ISSUE TITLE
Scheduler does not respect clientConnection of KubeSchedulerConfiguration in 1.11

### ISSUE THREAD

**Issue by rfranzke** [kubernetes/kubernetes#65483]
/kind bug
/sig scheduling

**What happened**:
kube-scheduler `v1.11.0-rc.2` that is pointed to a `KubeSchedulerConfiguration` componentconfig file having
```yaml
clientConnection:
  kubeconfig: /var/lib/kube-scheduler/kubeconfig
```
ignores that it should use this kubeconfig file. Instead, it uses the in-cluster config (as `--kubeconfig` is neither provided).

**What you expected to happen**:
The kube-scheduler should respect the kubeconfig provided in the `KubeSchedulerConfiguration`.

**How to reproduce it (as minimally and precisely as possible)**:
Starting `hyperkube` image `v1.11.0-rc.2` with `/hyperkube scheduler --config=config.yaml --v=2` whereby the content of `config.yaml` looks like this:
```yaml
apiVersion: componentconfig/v1alpha1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /var/lib/kube-scheduler/kubeconfig
leaderElection:
  leaderElect: true
```
makes the scheduler logging `W0626 13:18:22.399724       1 options.go:269] Neither --kubeconfig nor --master was specified. Using default API client. This might not work.`

The exact same configuration as above works with `release-1.10` branch. Seems like abc8c98e35a291e03775cd4fc8808a33dc58b7d7 has introduced the behaviour. The kube clients are created [here](https://github.com/kubernetes/kubernetes/blob/release-1.11/cmd/kube-scheduler/app/options/options.go#L201) but the componentconfig file is loaded [later here](https://github.com/kubernetes/kubernetes/blob/release-1.11/cmd/kube-scheduler/app/options/options.go#L228).

/cc @sttts 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.0-rc.2
