### ISSUE TITLE
Pods that have a deadline exceeded lose container status

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#65493]
Was running a pod with an activeDeadlineSeconds on a 1.10 cluster.  The pod reached the deadline, but the pod status did *not* contain the latest state of the pod containers (pod containersStatus was empty).  The status only had the following fields:

```
status:
  phase: Failed
  reason: DeadlineExceeded
  message: ...
  startTime: ...
```

The statuses were there immediately prior to the deadline being reached.

This broke API clients that were looking at container status.
