### ISSUE TITLE
PreStop is not preventing pod to be killed

### ISSUE THREAD

**Issue by vojbarzz** [kubernetes/kubernetes#65496]
/kind bug

**What happened**:
I have defined a preStop handler that waits for 5 minutes and even that the pod is killed after default 30 seconds of grace period.

**What you expected to happen**:
Take 5 minutes to terminate the pod (preStop should be blocking)

**How to reproduce it (as minimally and precisely as possible)**:
`handler definition:`
``` yaml
        lifecycle:
          preStop:
            exec:
              command: ["/shutdown.sh"]
```
`shutdown.sh:`
``` console
#!/bin/sh

for i in 1 2 3 4 5 6 7 8 9 10
do
        echo "Shutdown $i " `date`  >> /data/shutdown.log
        sleep 30
done
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  GitVersion:"v1.10.3-2+c8f1f59d8d233c", GitCommit:"c8f1f59d8d233c6e9a10cedd8aad4f43ad9ef5c7"
- Cloud provider or hardware configuration: bluemix
- OS (e.g. from /etc/os-release): any
