### ISSUE TITLE
Unable to mount volumes for pod: timeout expired waiting for volumes to attach or mount

### ISSUE THREAD

**Issue by jiashenC** [kubernetes/kubernetes#65500]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I successfully create **PersistentVolume** and **PersistentVolumeClaim** on **AWS**, but the pod is not able to mount to those volumes. The error message thrown by the **k8s** is 
> Warning  FailedMount            58s (x19 over 41m)  kubelet, ip-xxx-xxx-xxx-xxx  Unable to mount volumes for pod "master-deployment-5979f94fc6-sf9br_default(28fddeda-797a-11e8-907e-0e594759e784)": timeout expired waiting for volumes to attach or mount for pod "default"/"master-deployment-5979f94fc6-sf9br". list of unmounted volumes=[mysql-volume]. list of unattached volumes=[mysql-volume elasticsearch-volume default-token-2tfjn]

This is my config file.
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: master-volume
spec:
  storageClassName: local-storage
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-volume"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: master-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 64Gi
  storageClassName:
    local-storage
---
kind: Deployment
...
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: master-volume
      - name: elasticsearch-volume
        persistentVolumeClaim:
          claimName: master-volume
...
```

**What you expected to happen**:
All pods and the deployment start successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure how to reproduce. The images I use are private. I share part of my config file which could be related to the persistent volume issue.

**Anything else we need to know?**:
- Use **kubeadm** to create a cluster on multiple instances, and trying to create a deployment with **Persistent Volume** and **Persistent Volume Claim**. 
- I am using **m4.xlarge** AWS instance, which should have correct support for `kubernetes`.

**Environment**:
- **Kubernetes version (use `kubectl version`)**:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
```
AWS
```
- **OS (e.g. from /etc/os-release)**:
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel (e.g. `uname -a`)**:
```
Linux k8s 4.4.0-1060-aws #69-Ubuntu SMP Sun May 20 13:42:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
