### ISSUE TITLE
Getting new CRD with short name/category will occur error

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#65517]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind feature

**What happened**:

When I created a crd e.g.:

```yam
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: crontabs.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: crontabs
    # singular name to be used as an alias on the CLI and for display
    singular: crontab
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CronTab
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ct
    categories:
    - testcat
```
Then I used `kubectl get testcat`. I found that the first time the result will be with an error:

> error: the server doesn't have a resource type "testcat"

And as for the second time it will be normal:

> No resources found. 

And it can be stably reproduced every time I created a new CRD.

**What you expected to happen**:

kubectl returns `No resources found. ` the first time I requested the new CRD instead of an error.

**Anything else we need to know?**:

I also found that requesting short name e.g. `kubectl get ct` will be the same. It returns an error the first time but becomes normal the second time.😲

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by CaoShuFeng** [comment]
Confirmed that `error: the server doesn't have a resource type` could show up even the crd has status `Established`

/assign

**Comment by nikhita** [comment]
/sig api-machinery

> Confirmed that error: the server doesn't have a resource type could show up even the crd has status Established

@CaoShuFeng Haven't looked into the problem yet but could be related: https://github.com/kubernetes/kubernetes/issues/57042

**Comment by CaoShuFeng** [comment]
Looks like this happens because cache file in .kube/http-cache/ or .kube/cache/ is not synced with kube-apiserver.

delete all files under .kube/http-cache/ and .kube/cache/ will cause a sync and the error will not show up.

This looks like a cli issue.

**Comment by nikhita** [comment]
fyi @sttts

**Comment by CaoShuFeng** [comment]
Tried to fix in cli:
https://github.com/kubernetes/kubernetes/pull/65527

**Comment by soltysh** [comment]
@juanvallejo this seems similar to https://github.com/openshift/origin/issues/20226

**Comment by yue9944882** [comment]
Even though this bug looks small, it might involve larger changes both in fixing and refactoring.. A typical corner case😳
/shrug

**Comment by sttts** [comment]
> Even though this bug looks small, it might involve larger changes both in fixing and refactoring.. A typical corner case it is😳

Can you put this into words? What's the actual issue?

**Comment by yue9944882** [comment]
>> Even though this bug looks small, it might involve larger changes both in fixing and refactoring.. A typical corner case it is😳
>Can you put this into words? What's the actual issue?

@sttts SRY, I should have put it clearer.. I just mean that this issue is sort of fundamental and obviously have been existing for a long time.

**Comment by yue9944882** [comment]
/reopen
/remove-lifecycle rotten

ouch..

**Comment by yuchengwu** [comment]
encountered same issue, as @CaoShuFeng  suggested `delete all files under .kube/http-cache/` the error will not show up.

**Comment by cofyc** [comment]
any progress?

**Comment by brianpursley** [comment]
Here is a little more info, and here is how I am able to reproduce it (kubectl version 1.18.0 and cluster version 1.19.0-beta.2):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-beta.2-78-g1112abd470a5ba.dev-1592428154-dirty", GitCommit:"1112abd470a5ba787d463931c14902caee992c4a", GitTreeState:"dirty", BuildDate:"2020-06-17T21:09:46Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl apply -f <(cat << EOF
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
  scope: Namespaced
  names:
    plural: foos
    singular: foo
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Foo
    shortNames:
    - fo
EOF
)

# First time, it returns... error: the server doesn't have a resource type "fo"
kubectl get fo

# Second time, it returns... No resources found in default namespace.
kubectl get fo

kubectl delete CustomResourceDefinition foos.stable.example.com
```

A couple interesting things i noted...
* If I deleted by `~/.kube/http-cache` and re-ran it, I could not reproduce it. It is only the first time the short name was EVER used that this occurs. I only tried from one client machine, so I'm not sure this is cluster-specific or client-specific. If I used a different short name, like 'fo2' and re-ran the example, then it reproduces the problem.

* You can also run `kubectl api-resources` after creating the CRD and it has the same effect as deleting your `~/.kube/http-cache`.
