### ISSUE TITLE
Init containers cannot use downward API volumes

### ISSUE THREAD

**Issue by ImJasonH** [kubernetes/kubernetes#65597]
**What happened**:

Define a Pod with an `initContainer` that mounts a volume backed by the downward API to expose its CPU request to the container.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod

spec:
  initContainers:
  - name: init
    image: ubuntu
    args: ['cat', '/etc/podinfo/cpu']
    resources:
      requests:
        cpu: '.25'
      limits:
        cpu: '.25'
    volumeMounts:
    - name: podinfo-init
      mountPath: /etc/podinfo

  containers:
  - name: real
    image: ubuntu
    args: ['echo', 'hello']

  volumes:
  - name: podinfo-init
    downwardAPI:
      items:
      - path: 'cpu'
        resourceFieldRef:
          containerName: 'init'
          resource: 'requests.cpu'
```

When I start this pod, I see it in `Init 0/1` and `kubectl describe pod pod` shows:

```
MountVolume.SetUp failed for volume "podinfo-init" : container init not found
```

**What you expected to happen**:

The pod starts, runs the init container with volume mounted to print the mounted file, then the real container, then finishes.

**How to reproduce it (as minimally and precisely as possible)**:

See the YAML above, more repro cases [here](https://gist.github.com/ImJasonH/6a0d8e0c0b11cda095f30c4890072d73)

**Anything else we need to know?**:

I suspect this might be because the container name `init` is ambiguous between init containers and a pod's "real" containers. If so, is there some way to reference the init container specifically in the `containerName` field?

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.2-gke.3", GitCommit:"d2c7a2bd41036f9474287579a725dc54c904e92d", GitTreeState:"clean", BuildDate:"2018-05-23T00:19:39Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

GKE

```sh
$ gcloud container clusters list
cluster-1                                us-east1-b  1.10.2-gke.3    <IP>  n1-standard-4  1.10.2-gke.3  3          RUNNING

```

- OS (e.g. from /etc/os-release):

```sh
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Kernel (e.g. `uname -a`):

```
$ uname -a
Linux <hostname> 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
```

**Comment by warmchang** [comment]
Try changing containerName to initContainerName:

```
  volumes:
  - name: podinfo-init
    downwardAPI:
      items:
      - path: 'cpu'
        resourceFieldRef:
          initContainerName: 'init'
          resource: 'requests.cpu'
```
