### ISSUE TITLE
Pod restart multiple times

### ISSUE THREAD

**Issue by icowan** [kubernetes/kubernetes#65695]
# Pod restart multiple times

I have a question...

- Kubernetes version: 1.10.4

### Question 1:

- Environment variables: 
- key: POD_XXX_KEY value: helloworld

my application start code:

```go
if key := os.Getenv("POD_XXX_KEY"); key == "" {
	panic("POD_XXX_KEY not found.")
}
fmt.println("biubiuibu...")
```

so.. Then pod at start
0 start: POD_XXX_KEY is null, panic POD_XXX_KEY not found.
1 start: POD_XXX_KEY is null, panic POD_XXX_KEY not found.
2 start: POD_XXX_KEY is 282ecd65-222f-e22c1aa8986b

deployment yaml:

```
env:
- name: POD_XXX_KEY
  valueFrom:
    configMapKeyRef:
      name: myservice
      key: hellokey
```

configmap yaml:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myservice
data:
  hellokey: 282ecd65-222f-e22c1aa8986b
```

No problem at 1.10.0 But 1.10.4 has the question.

What is the reason?

![](https://ofbudvg4c.qnssl.com/images/k8s/WechatIMG2274.jpeg)
