### ISSUE TITLE
When multiple pods are on the same node, only one pod is successfully started, and all others fail.

### ISSUE THREAD

**Issue by icowan** [kubernetes/kubernetes#65697]
# When multiple pods are on the same node, only one pod is successfully started, and all others fail.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.10.4
- OS : centos 7.4

create a Endpoints:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-test
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-test
subsets:
  - addresses:
    - ip: 10.106.146.8
    ports:
      - port: 3306
        protocol: TCP
---
```

![](https://ofbudvg4c.qnssl.com/images/k8s/WechatIMG2275.jpeg)

my application code:

```go
var user = "root"
var password = "root"
var host = mysql-test.default
var port = 3306
var database = "hello"

var dataSource = fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8&parseTime=true&loc=Local&timeout=20m&collation=utf8mb4_unicode_ci", user, password, host, port, database)

db, err = sql.Open("default", dataSource)
if err != nil {
	panic(err)
}
```

When multiple pods are on the same node, only one pod is successfully started, and all others fail.

the error is: panic Database connection error

Distributed on different nodes does not have this problem.
