### ISSUE TITLE
the status of volumeClaimTemplates was pending even if the pvc was created already

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#65706]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
I create a statefulset with volumeClaimTemplates defined, after the statefulset finish creation, check the status of volumeClaimTemplates, find it's still pending like below:
```
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: mongodbdir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: mongodb-storage
    status:
      phase: Pending
```

but actually, the pvc have created:
```
root@hchenxa-1:~# kubectl  get pvc -n kube-system  | grep mongodb-storage
mongodbdir-icp-mongodb-0        Bound     mongodb-9.111.255.15             20Gi       RWO            mongodb-storage            4d
mongodbdir-icp-mongodb-1        Bound     mongodb-9.111.255.131            20Gi       RWO            mongodb-storage            4d
mongodbdir-icp-mongodb-2        Bound     mongodb-9.111.255.45             20Gi       RWO            mongodb-storage            4d
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.0
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
