### ISSUE TITLE
Question: PodSecurityPolicy doesn't allow Pods created by custom MutatingWebhookController that injects sidecar without securityContext.allowPrivilegeEscalation

### ISSUE THREAD

**Issue by davidxia** [kubernetes/kubernetes#65716]
/kind bug

### What happened:

I have a cluster in which I run a custom MutatingWebhookController that injects sidecar containers. This was working fine. When I created Deployments, the Pods that were created had the sidecar containers. After I enabled the PodSecurityPolicy admission controller and applied this PodSecurityPolicy, I was unable to create Deployments in namespaces my custom controller acted on.

**Is this the expected behavior? If so, are there docs that would help me understand this?**

My PSP

```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: backend-service
spec:
  privileged: false
  allowPrivilegeEscalation: false
  hostIPC: false
  hostNetwork: false
  hostPID: false
  allowedHostPaths:
  - pathPrefix: "/dev/null"
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-service
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - backend-service
  verbs:
  - use
---
# allow all authenticated users to use this PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-service
roleRef:
  kind: ClusterRole
  name: backend-service
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: authenticated
```

### What you expected to happen:

I expected the Pods to be able to match the backend-service PSP above.

### How to reproduce it (as minimally and precisely as possible):

Here's my custom controller's MutatingWebhookConfiguration.

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: my-controller
webhooks:
- name: podpreset.admission.mycompany.com
  namespaceSelector:
    matchLabels:
      my-controller: "enabled"
  failurePolicy: "Fail"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  clientConfig:
    service:
      name: my-controller
      namespace: my-system-namespace
      path: /v1beta1/mutate
    caBundle: $cabundle
```

Here's the sidecar container it injects to every pod.

```yaml
        image: "gcr.io/my-project/sidecar:fa268611-20180110T102551"
        name: "sidecar"
        resources:
            limits:
                cpu: "500m"
                memory: "512M"
            requests:
                cpu: "250m"
                memory: "256M"
```

Here's an example Deployment that fails with error message was `pods "dxia-nginx-85d4d97665-x6dqw" is forbidden: unable to validate against any pod security policy: [].`

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: dxia-nginx
  namespace: the-who
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx2
        resources:
          limits:
            cpu: "1"
            memory: 2G
          requests:
            cpu: "1"
            memory: 2G
```

When I applied the above Deployment to a namespace that my-controller didn't act on, I noticed the resulting Pod resource had `spec.containers.securityContext.allowPrivilegeEscalation: false` ([full Pod
YAML here][gist1]).

Then I edited the ConfigMap of my-controller to explicitly have `allowPrivilegeEscalation: false` for the sidecar container it injected. The same Pod that failed before was able to run ([full Pod YAML][gist2]).

I'm not sure why the injected containers need `spec.containers.securityContext.allowPrivilegeEscalation: false` explicitly. The [docs][securitycontext-docs] don't say what the default allowPrivilegeEscalation setting is if omitted.

  [gist1]: https://gist.github.com/davidxia/0851facbeaddd91370bb019c759c2ec5#file-gistfile1-txt
  [gist2]: https://gist.github.com/davidxia/0851facbeaddd91370bb019c759c2ec5#file-gistfile2-txt
  [securitycontext-docs]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#securitycontext-v1-core

### Anything else we need to know?:

A theory of what's happening:

The PodSecurityPolicyPlugin implements both the [MutationInterface](https://github.com/kubernetes/apiserver/blob/97f7e8b3e9485f43fdaaf07dc3790559170325b0/pkg/admission/interfaces.go#L78) and [ValidationInterface](https://github.com/kubernetes/apiserver/blob/97f7e8b3e9485f43fdaaf07dc3790559170325b0/pkg/admission/interfaces.go#L86). 

The plugin will mutate the pod and the containers within that pod to set the default [securityContext](https://github.com/kubernetes/kubernetes/blob/f73101066ac9a92a97c18bc05c9f017d68e04115/pkg/security/podsecuritypolicy/provider.go#L171). If my-controller runs after the PodSecurityPolicyPlugin the containers injected by my-controller will not have a default securityContext set.

What ends up happening is that the validation will fail as our unset securityContext will not match any PodSecurityPolicy. Validation happens after mutation (I believe that is true for plugins as well as webhooks):
![image](https://user-images.githubusercontent.com/480621/42173081-e9464d52-7deb-11e8-9404-e1236dfe70fc.png)
[source](https://kubernetes.io/blog/2018/01/extensible-admission-is-beta/).

### Environment:
- Kubernetes version (use `kubectl version`):

```
Client Version:version.Info{
  Major:"1",
  Minor:"9",
  GitVersion:"v1.9.7",
  GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92",
  GitTreeState:"clean",
  BuildDate:"2018-04-19T00:05:56Z",
  GoVersion:"go1.9.3",
  Compiler:"gc",
  Platform:"darwin/amd64"
}Server Version:version.Info{
  Major:"1",
  Minor:"10+",
  GitVersion:"v1.10.4-gke.2",
  GitCommit:"eb2e43842aaa21d6f0bb65d6adf5a84bbdc62eaf",
  GitTreeState:"clean",
  BuildDate:"2018-06-15T21:48:39Z",
  GoVersion:"go1.9.3b4",
  Compiler:"gc",
  Platform:"linux/amd64"
}
```

- Cloud provider or hardware configuration:
GKE

- OS (e.g. from /etc/os-release):
[Google COS](https://cloud.google.com/container-optimized-os/docs/)

- Kernel (e.g. `uname -a`):
Linux gke-testing-europe-west-default-pool2-1ced2d7f-p4rs 4.14.22+ #1 SMP Wed May 30 13:49:27 PDT 2018 x86_64 Intel(R) Xeon(R) CPU @ 2.60GHz GenuineIntel GNU/Linux
