### ISSUE TITLE
rbac error messages are incomprehensible and not helpful

### ISSUE THREAD

**Issue by ensonic** [kubernetes/kubernetes#65804]
/kind bug

**What happened**:
```
kubectl create -f clusterrole.yaml
```
```yaml
# https://github.com/kubernetes/helm/blob/master/docs/rbac.md
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: installer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tiller-user
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["", "extensions"]
  resources: ["configmaps", "deployments", "pods", "services"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller-user-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tiller-user
subjects:
- kind: ServiceAccount
  name: installer
  namespace: default
```
The error I am getting is a large blob of unformatted text (not even json or yaml):
```
[PolicyRule{Resources:["pods/portforward"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["delete"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["delete"]}] user=&{ensonic@google.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```

**What you expected to happen**:
It to work or to give a concise error message. I am running this as a user who is cluster owner, so how can I not have the right privileges for anything?

**Environment**:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.1", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-04-07T22:06:59Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
running on GKE (Master version: 1.9.6-gke.1, Node version: 1.9.6-gke.1)
