### ISSUE TITLE
pod crashes if /run/secrets is used as a mount target

### ISSUE THREAD

**Issue by trondhindenes** [kubernetes/kubernetes#65835]
/kind bug

**What happened**:
After upgrading from 1.9.0 to 1.10.2 / 1.10.5 (tried both), we started to get multiple containers in crash loop. This turned out to be caused by the fact that we usually map Kubernetes secrets to the container path `/run/secrets` and use company-internal libraries to populate application config from these secrets. I don't know what the change is from 1.9.0 to 1.10.x (the order of which the mounts are happening maybe?)

**What you expected to happen**:
The pod should start

**How to reproduce it (as minimally and precisely as possible)**:
create a Secret, mount it into `/run/secrets` on a pod

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.2
- Cloud provider or hardware configuration: aws (custom)
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS
- Kernel (e.g. `uname -a`): 4.4.0-1057-aws
- Install tools: custom
- Others: docker://1.13.1

log output from `kubectl logs`:
```
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/kubelet/pods/63a4bfea-7fa3-11e8-9f7b-06589ff22a28/volumes/kubernetes.io~secret/ansiblejobservice-token-dsbdf\\\" to rootfs \\\"/dockerdata/overlay2/ece45c15fd86a5676d99ac0dae3559f7bda882d7f7b0f9862d572f2ad52949a3/merged\\\" at \\\"/dockerdata/overlay2/ece45c15fd86a5676d99ac0dae3559f7bda882d7f7b0f9862d572f2ad52949a3/merged/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"mkdir /dockerdata/overlay2/ece45c15fd86a5676d99ac0dae3559f7bda882d7f7b0f9862d572f2ad52949a3/merged/run/secrets/kubernetes.io: read-only file system\\\"\""
```

**Comment by AntonFriberg** [comment]
Same thing happens on 1.11 using minikube. In the dashboard I get the following error.
```
Error: failed to start container "nginx": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/d4985098-9b01-11e8-8db0-e4d73345faa0/volumes/kubernetes.io~secret/default-token-8rljs\\\" to rootfs \\\"/var/lib/docker/overlay2/8a6e4af24d92cc67f21557faf9fd2c859a83b89447fc558f82fb8096977c8ee4/merged\\\" at \\\"/var/lib/docker/overlay2/8a6e4af24d92cc67f21557faf9fd2c859a83b89447fc558f82fb8096977c8ee4/merged/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"mkdir /var/lib/docker/overlay2/8a6e4af24d92cc67f21557faf9fd2c859a83b89447fc558f82fb8096977c8ee4/merged/run/secrets/kubernetes.io: read-only file system\\\"\"": unknown
```
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by AntonFriberg** [comment]
Same error on 1.11.1
```
Error: failed to start container "nginx": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/218bb5c1-9b03-11e8-bace-147d087924c9/volumes/kubernetes.io~secret/default-token-c6hd9\\\" to rootfs \\\"/var/lib/docker/overlay2/777f449879659e641fcc7a650f6305adfe04273ff11375dbd1e32e7c6d5d16f9/merged\\\" at \\\"/var/lib/docker/overlay2/777f449879659e641fcc7a650f6305adfe04273ff11375dbd1e32e7c6d5d16f9/merged/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"mkdir /var/lib/docker/overlay2/777f449879659e641fcc7a650f6305adfe04273ff11375dbd1e32e7c6d5d16f9/merged/run/secrets/kubernetes.io: read-only file system\\\"\"": unknown
Back-off restarting failed container
```
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by AntonFriberg** [comment]
This is my configuration
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  test: TS1oeUtKYkNrQWdZYlBZSGlnWF9kcWRNZUFiME9IdWlxN0xQTjFHWG9oUQo=
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-volume
          mountPath: "/run/secrets"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: test-secret
          items:
          - key: test
            path: test
```

**Comment by AntonFriberg** [comment]
I think I found the reason for the crash. Since 1.9.4 secrets and configMaps will be mounted as read-only volumes. Since kubernetes needs to place its own secrets in `/run/secrets/kubernetes.io/serviceaccount/` it is unable to place them as `/run/secrets` is read-only. The result is that the pod crashes. This also explains why mounting my secrets in `/run/secrets/test` works but not `/run`.

I have been unable to find a workaround since `readOnly: false` does not work.  

#60814

**Comment by AntonFriberg** [comment]
Ok I have found a workaround using "subPath"

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  test: TS1oeUtKYkNrQWdZYlBZSGlnWF9kcWRNZUFiME9IdWlxN0xQTjFHWG9oUQo=
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-volume
          mountPath: "/run/secrets/tmp"
          subPath: ..secrets
      volumes:
      - name: secret-volume
        secret:
          secretName: test-secret
          items:
          - key: test
            path: "secrets/test"
```
