### ISSUE TITLE
failed to load Kubelet config file /var/lib/kubelet/config.yaml after kubelet update

### ISSUE THREAD

**Issue by Xyrion** [kubernetes/kubernetes#65863]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
/var/lib/kubelet/config.yaml got removed after kubelet update.

**What you expected to happen**:
kubelet update without /var/lib/kubelet/config.yaml being removed.

**How to reproduce it (as minimally and precisely as possible)**:
Yum update kubeadm.x86_64 0:1.11.0-0 kubectl.x86_64 0:1.11.0-0  kubelet.x86_64 0:1.11.0-0
Restart kubelet

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-862.6.3.el7.x86_64
- Install tools:
- Others:

**Comment by Shinerrs** [comment]
+1

**Comment by jamesddube** [comment]
+1

**Comment by liggitt** [comment]
Are you using the dynamic kubelet config feature, or just specifying --config?

Did the file get removed after an OS reboot or a simple kubelet upgrade? If after an OS reboot, is that location on a tmpfs-backed filesystem?

**Comment by wh211212** [comment]
how to solve these problems, I have some errors...

**Comment by Keyur1729** [comment]
Am facing same issue.
Am not able to start kubelet service on the minion nodes. 
`Jul 06 10:56:02 worker-node1 systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Jul 06 10:56:03 worker-node1 kubelet[1487]: I0706 10:56:03.087376    1487 feature_gate.go:230] feature gates: &{map[]}
Jul 06 10:56:03 worker-node1 kubelet[1487]: F0706 10:56:03.087489    1487 server.go:190] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib
Jul 06 10:56:03 worker-node1 systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Jul 06 10:56:03 worker-node1 systemd[1]: Unit kubelet.service entered failed state.
Jul 06 10:56:03 worker-node1 systemd[1]: kubelet.service failed.`

I was able to run `kubeadm join` on the master node, but when I ran the `kubeadm join ...` command on minions, it gave below error:
`[discovery] Successfully established connection with API Server "192.xxx.xxx.xxx:6443"
[kubelet] Downloading configuration for the kubelet from the "kubelet-config-1.11" ConfigMap in the kube-system namespace
**Unauthorized**`

That led me to checking kubelet status.

I have created total 3 CentOS VMs on my Mac using VMware fusion. The master node is on DVD version of centos, while the other 2 minions are on minimal version of centos.
`CentOS Linux release 7.5.1804 (Core)`
`Kubectl version 1.11`

Appreciate any help from the community.

**Comment by wssiqi** [comment]
Face the same problem.

I am just want to install k8s on a  clean Centos7.
Follow the guideline https://kubernetes.io/docs/tasks/tools/install-kubeadm/

kubelet could not start and logs as below:
Jul 06 14:56:05 localhost.localdomain kubelet[2478]: F0706 14:56:05.038955    2478 server.go:190] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var
Jul 06 14:56:05 localhost.localdomain systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Jul 06 14:56:05 localhost.localdomain systemd[1]: Unit kubelet.service entered failed state.
Jul 06 14:56:05 localhost.localdomain systemd[1]: kubelet.service failed.

**Comment by WisWang** [comment]
I upgrade my cluster from 1.10.3 to 1.11.0 with kubeadm. I also met this issue, I use this to generate the kubelet config file `kubeadm upgrade  node config  --kubelet-version v1.11.0`, and `systemctl daemon-reload&&systemctl restart kubelet`, I also changed the `cgroupDriver`  in `/var/lib/kubelet/config.yaml` , My cluster all `cgroupDriver` both docker and kubelet is `systemd`, Now the node looks like ok.
```
[root@m-30-3 kubelet]# kubectl get node
NAME      STATUS    ROLES     AGE       VERSION
m-30-1    Ready     master    29d       v1.11.0
m-30-2    Ready     <none>    29d       v1.10.3
m-30-3    Ready     <none>    24d       v1.11.0
```

**Comment by dnavre** [comment]
Same happened to me.

**Comment by mateobur** [comment]
I pasted my `config.yaml` from another similar cluster and then followed @WisWang procedure, and my cluster came back to life.

Posting the conf here in case it is useful for somebody else, obviously, it may not match your cluster conf.

```
address: 0.0.0.0
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: cgroupfs
cgroupsPerQOS: true
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
containerLogMaxFiles: 5
containerLogMaxSize: 10Mi
contentType: application/vnd.kubernetes.protobuf
cpuCFSQuota: true
cpuManagerPolicy: none
cpuManagerReconcilePeriod: 10s
enableControllerAttachDetach: true
enableDebuggingHandlers: true
enforceNodeAllocatable:
- pods
eventBurst: 10
eventRecordQPS: 5
evictionHard:
  imagefs.available: 15%
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
evictionPressureTransitionPeriod: 5m0s
failSwapOn: true
fileCheckFrequency: 20s
hairpinMode: promiscuous-bridge
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 20s
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m0s
iptablesDropBit: 15
iptablesMasqueradeBit: 14
kind: KubeletConfiguration
kubeAPIBurst: 10
kubeAPIQPS: 5
makeIPTablesUtilChains: true
maxOpenFiles: 1000000
maxPods: 110
nodeStatusUpdateFrequency: 10s
oomScoreAdj: -999
podPidsLimit: -1
port: 10250
registryBurst: 10
registryPullQPS: 5
resolvConf: /etc/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: 2m0s
serializeImagePulls: true
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
volumeStatsAggPeriod: 1m0s
```
