### ISSUE TITLE
Add ability to add/remove persistent volumes for StatefulSet

### ISSUE THREAD

**Issue by nazarenkoff** [kubernetes/kubernetes#65870]
**FEATURE REQUEST**:

Please add ability to add/remove persistent volumes for StatefulSet by editing volumeClaimTemplates

/kind feature

**What happened**:
I'm trying to add new persistent volume to existing StatefulSet by adding metadata to volumeClaimTemplates and getting error 
> The StatefulSet "statefulSetWithPvc" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.

**What you expected to happen**:
New persistent volume created for added claim

**How to reproduce it (as minimally and precisely as possible)**:
1. Create  StatefulSet with volumeClaimTemplates:
```
volumeClaimTemplates:
  - metadata:
      name: pvc1
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
```
2. Add new claim:
```
volumeClaimTemplates:
  - metadata:
      name: pvc1
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
 - metadata:
      name: pvc2
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
```

**Environment**:
- Kubernetes version :
> Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.7+coreos.0", GitCommit:"768e049ab5230010251f30475e0e785e2e999566", GitTreeState:"clean", BuildDate:"2018-01-18T00:17:18Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
