### ISSUE TITLE
Ingress externalips stopped working after 1.11 upgrade

### ISSUE THREAD

**Issue by vetm73** [kubernetes/kubernetes#65875]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
I think it's a bug ( or configuration issue )

**NGINX Ingress controller version**:
0.16.2

**Kubernetes version** (use `kubectl version`):
1.11.0

**Environment**:
arm

- **Cloud provider or hardware configuration**:
Raspberry Pi 3
- **OS** (e.g. from /etc/os-release):
Raspbian Stretch
- **Kernel** (e.g. `uname -a`):
Linux PI01 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux
- **Install tools**:
flannel 
- **Others**:

**What happened**:
On 1.10.2 I have the following ingress-nginx service to get external traffic from 192.168.1.201 port 80 to my pod.

```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: ingress-nginx
  externalIPs:
  - 192.168.1.201
```

After upgrading to 1.11.0 this configuration does not work. The page timed out or gets a connection refused.

**What you expected to happen**:
Traffic for port 80 is send to my pod

**How to reproduce it** (as minimally and precisely as possible):
Install 1.11.0 flannel ingress-nginx with service above. Pod must show website on port 80.

**Anything else we need to know**:
My cluster is running on PI hardware. Ingress from the pod:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: the-ingress
  namespace: the-namespace
spec:
  rules:
  - host: my-host.com
    http:
      paths:
      - backend:
          serviceName: web-server
          servicePort: http
```
