### ISSUE TITLE
SMB mount on Windows does not support subPath

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#65890]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
azure file mount on Windows does not support subPath after security fix: https://github.com/kubernetes/kubernetes/issues/60813, root cause is `filepath.EvalSymlinks(hostPath)` will return error for azure file mount path, the error message would be like following:
```
cannot read link c:\var\lib\kubelet\pods\38d3deb5-80e9-11e8-89c5-000d3a06c0c8\volumes\kubernetes.io~azure-file\pvc-0307eaf1-8018-11e8-95ea-000d3a06c0c8: The system cannot find the file specified.
```

Related k8s code:
https://github.com/kubernetes/kubernetes/blob/86b9a53226b1c9f9dce3ffb0133482f14709418b/pkg/util/mount/mount_windows.go#L253-L255

It's a issue that go func `filepath.EvalSymlinks` does not support azure file share mount, need to find a way to workaround this or wait for go func `filepath.EvalSymlinks` fixed? 

Related k8s config:
```
---
kind: Pod
apiVersion: v1
metadata:
  name: aspnet-azurefile
spec:
  containers:
  - image: microsoft/aspnet:4.7.2-windowsservercore-1803
    name: aspnet-azurefile
    volumeMounts:
    - name: azurefile01
      mountPath: '/mnt/azure'
      subPath: xyz
  volumes:
  - name: azurefile01
    persistentVolumeClaim:
      claimName: pvc-azurefile
```

Affected version:

| k8s version | broken version |
| ---- | ---- |
| v1.7 | 1.7.14 by #61047 |
| v1.8 | 1.8.9 by 61046 |
| v1.9 | 1.9.4 by 61045 |
| v1.10 | 1.10.0 |

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10, v1.11
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/sig storage
/sig windows
