### ISSUE TITLE
PersistenVolume requires volume type?

### ISSUE THREAD

**Issue by dusansusic** [kubernetes/kubernetes#65903]
I have k8s 1.10.3 provisioed on AWS with kops.

I defined PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 80Gi
```

```bash
$ kubectl get storageclass
NAME            PROVISIONER             AGE
default         kubernetes.io/aws-ebs   31d
gp2 (default)   kubernetes.io/aws-ebs   31d

```

Applying this PV results with an error:
```
The PersistentVolume "data" is invalid: spec: Required value: must specify a volume type
```
but volume is created (EBS).

Am I missing something or this is kind of a bug?
/kind bug

- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
two different things are going on here...

1. your manually created PV is invalid, because it is missing a type, as the error describes
2. you have a default storage class, which means that PVC objects that request storage can have a PV auto-provisioned for them. that is likely what is resulting in the created PV object.

/sig storage
/close

**Comment by Asgoret** [comment]
@liggitt 
1) And what's the storage type? In k8s go client there is no any reference for type....and error is useless. What type is missing?

**Comment by liggitt** [comment]
The PV must define one of the supported volume source types within it's `spec` stanza. See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#persistentvolumespec-v1-core for the supported volume source types (awsElasticBlockStore, azureDisk, azureFile, cephfs, cinder, csi, fc, flexVolume, flocker, gcePersistentDisk, glusterfs, hostPath, iscsi, local, nfs, photonPersistentDisk, quobyte, rbd, scaleIO, storageos, or vsphereVolume)

**Comment by nevetS** [comment]
This popped up in my google search about the error and I wanted to provide a little more information for the next guy.

For EBS volumes, the documentation is here:  https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore

In order to use an EBS volume as a PV, you have to create it first, either using the console or `aws ec2 create-volume`.  Then at the very minimum, your spec needs to include the volumeID of the created volume.

```yaml
  awsElasticBlockStore:
    volumeID: <theVolumeID>
```

PVCs can create EBS volumes dynamically, but they by default will have their reclaim policy set to "Delete".  You can change that by 

```sh
kubectl patch pv <pvid from kubectl get pv> -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'
```

**Comment by devopsenggineer** [comment]
how to make persistent volume claim retain or gets attached to previously dynamically provisioned persistent volume using below Kubernetes resource files.

Storageclass file
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  fstype: ext4
  replication-type: none
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
```
PersistentVolumeClaim file
```
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: fx-postgres-pv
#  labels:
#    type: gcePersistentDisk
#    app: fx-postgres
#spec:
#  storageClassName: manual
#  storageClassName: "premium-rwo"
#  storageClassName: "fast-ssd"
#  capacity:
#    storage: 15G
#  accessModes:
#    - ReadWriteOnce
 # gcePersistentDisk:
 #   fsType: ext4
#  hostPath:
#    path: "/fxcloud/postgres/pgdata"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fx-postgres
  name: fx-postgres-pv-claim
spec:
#  storageClassName: manual
#  storageClassName: "premium-rwo"
  storageClassName: "fast-ssd"
  accessModes:
  - ReadWriteOnce
  reclaimPolicy: Retain
  resources:
    requests:
      storage: 15G

```
