### ISSUE TITLE
POD IP isn't released when node dies

### ISSUE THREAD

**Issue by mshaverdo** [kubernetes/kubernetes#65943]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When node shuts down,  IP address of pods on this node still "assigned", i.e. we can' t re-use this IP to start pod with the same IP on other node (in case of manually assigned IP). Also, it leads to IP address leakage, and, potentially, to IP pool exhaustion.

**What you expected to happen**:
IP should be released and available for further usage.

**How to reproduce it (as minimally and precisely as possible)**:

1. On multi-node kubernetes cluster with calico network create deployment:

```
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: nginx-0
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv4pools: "[\"10.48.0.0/16\"]"
        cni.projectcalico.org/ipAddrs: "[\"10.48.0.1\"]"
      labels:
        app: "nginx"
        serial: "0"
    spec:
      hostname: nginx-0
      containers:
        - name: nginx
          image: nginx:1.7.9
```

2. power off node with pod `nginx-0-XXXXXXXXXX-XXXX`
3. wait about 1 minute to kubernetes detect that node down and deployment controller will try to recreate pod on alive node. 
4. newly created pod will stuck in `ContainerCreating` state, because calico can't assign IP `10.48.0.1` to it's container due to this IP still 'assigned'.

**Anything else we need to know?**:
The problem is that network management (and IP release) is carried out by kubelet, placed on dead machine. 
I think, that it isn't very logical: network is a cluster-wide entity, but it managed by node-specific process. Maybe, someone from @kubernetes/sig-network-misc or @kubernetes/sig-network-feature-requests has mention about it?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.10
- Cloud provider or hardware configuration: virtualbox
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS
- Kernel (e.g. `uname -a`): 4.14.35-041435-generic
- Install tools: 
- Others:
