### ISSUE TITLE
Dynamic provisioned cinder PVs have not a region label at the time of creation

### ISSUE THREAD

**Issue by sngchlko** [kubernetes/kubernetes#65977]
Cinder-based dynamic PVs don't have a region label at the time of creation.
But PersistentVolumeLabelController in the cloud-controller-manager labels the PVs based on their region.
Cinder plugin should add the region label to the PVs at the time of creation regardless of cloud-controller-manager.

**What happened**:
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cinder-pv
  labels:
    failure-domain.beta.kubernetes.io/zone: nova
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
```
**What you expected to happen**:
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cinder-pv
  labels:
    failure-domain.beta.kubernetes.io/zone: nova
    failure-domain.beta.kubernetes.io/region: RegionOne
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
```

/kind bug
/sig openstack
