### ISSUE TITLE
kubectl create dry run does not respect multiple yaml documents

### ISSUE THREAD

**Issue by dohnto** [kubernetes/kubernetes#66017]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

If using `kubectl create --dry-run --output=yaml`, kubectl does not respect multiple yaml documents separated by "---" and outputs a single yaml file.

**What you expected to happen**:

Generate multiple YAMLs.

**How to reproduce it (as minimally and precisely as possible)**:

1. Lets suppose we have a document `input.yaml`

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: a
---
apiVersion: v1
kind: Namespace
metadata:
  name: b
```

2. Run
```yaml
# kubectl create -f input.yaml --dry-run --output=yaml
apiVersion: v1
kind: Namespace
metadata:
  name: a
  namespace: ""
apiVersion: v1
kind: Namespace
metadata:
  name: b
  namespace: ""
```
Note, that there are missing the hyphens and therefore the produced yaml contains all root level keys duplicated.

Expected output would be 

```yaml
# kubectl create -f input.yaml --dry-run --output=yaml
apiVersion: v1
kind: Namespace
metadata:
  name: a
  namespace: ""
--- # <----- I expect 3 hyphens here
apiVersion: v1
kind: Namespace
metadata:
  name: b
  namespace: ""
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
I tried both
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
and
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
