### ISSUE TITLE
Container-level usage of field "serviceAccountName"

### ISSUE THREAD

**Issue by juv** [kubernetes/kubernetes#66020]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The field `spec.serviceAccountName` is currently assigned to all containers as well as initContainers. 

**What you expected to happen**:
I expect the field `spec.serviceAccountName` to be defined on a container-level rather than a deployment-level, so that the containers and initContainers are able to use different service accounts in the same deployment. 

For example, my deployment contains several initContainers of [k8s-wait-for](https://github.com/groundnuty/k8s-wait-for) to make sure dependent deployments are up and running before bootstrapping the "main container" of my deployment. In these initContainers, I want to use a serviceAccount that has limited roles, tailored for the usage with k8s-wait-for (`["get", "watch", "list"]` on resource `["pods"]` to be specific). The main container is using another serviceAccount that has access to different roles. 

A workaround which injects a service account token from a secret into the main container is viable but can get messy quickly if we have a few containers that use different service accounts in a single deployment. Imho, a container-level definition of the field `spec.serviceAccountName` would be really useful for several usecases.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.1 (`GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc"`)

**Comment by liggitt** [comment]
/sig auth

@mikedanese a possible future extension to ServiceAccountTokenProjection could be to allow specifying the service account name

**Comment by WanLinghao** [comment]
@liggitt @mikedanese I am glad to take on this job if you guys don't mind

**Comment by mikedanese** [comment]
This needs some thought before we follow through. I haven't had time to write up my concerns yet. I think there might be better ways to achieve the same result.

**Comment by mikedanese** [comment]
We discussed this on the original TokenRequest proposal:

https://github.com/kubernetes/community/pull/1973#discussion_r178581137

Some thoughts:

* I'm worried about breaking the API contract of PodSecurityPolicy where a pod running as a specific service account must run in a specific context. This is especially important as we start to use the kube service account to authenticate to services inside and outside the cluster.
* [Sub-pod isolation](https://docs.google.com/document/d/1fe7lQUjYKR0cijRmSbH_y0_l3CYPkwtQa5ViywuNo8Q/edit) is deprioritized. What guarantees can we make about the presenter of a token, even when we employ sandboxing?
* Pod level service identity is more consistent with the existing Kubernetes abstraction. Pods are made up of multiple cooperating processes that form the single unit of service. It doesn't make sense to me conceptually that a single unit of service should run with multiple service identities.

That is not to say that attenuating a credential would not be useful. If we had the capability to apply an ABAC expression to a role binding, adding a "container" assertion to the authentication context would be preferable IMO. This approach would fulfill the stated needs.

**Comment by WanLinghao** [comment]
@mikedanese  
Do you mean we should insist current model that containers on same pod share same ServiceAccount but providing more info about which pod-container pair it bounded  in serviceaccount token? On other words, each container share same serviceacccount name but NOT the token itself.

**Comment by mikedanese** [comment]
Yes, I think I would like that. Unfortunately it's not useful with RBAC right now.

**Comment by WanLinghao** [comment]
Currently,  namespace-serviceaccount pair is all we need to know when do authorization. After your solution applied, the information we need to know in authorization becomes namespace-serviceaccount-pod-container. I worried about this based on following reasons:

- The namespace-pod-container determines the only container the request comes from,  it feels awkward since the serviceaccount becomes dispensable actually in authorization
-  If we introduce pod-container pair in authorization, say RBAC, how should we guarantee the persistence of rules? For example, for a pod created by deployment,  it could be killed and then recreated due to many reasons. During this, Its name  also changes.  For new-created pod, we should keep its authority unchanged because it functions the same with old one. For other words, each time the Deployment rolls , we need to update corresponding RBAC rules. 

> insist current model that containers on same pod share same ServiceAccount but providing more info about which pod-container pair it bounded in serviceaccount token

**Comment by WanLinghao** [comment]
I propose a new model to attenuate serviceaccount credential:
- Introduce a new concept called serviceaccount-level. User could launch serviceaccount token request with different level. The token which server generates would contain the serviceaccount-level info, and it will be used in authorization stage.
- All the serviceaccount with different level index composes a serviceaccount family.  Serviceaccount with level-0 is special since it shared by all the other serviceaccounts in same family when do authorization.
- For some special case when all the containers in same pod must share same authority like PodSecurityPolicy. We limit it only could use level-0 serviceaccount.
- In this proposal, we only take RBAC as a example to illustrate how it works. For other authorizers, we need further thinking.

For example, in a cluster, users create a pod with three containers, and user wants to assign each container different authority. He could do like this:

1.Create a pod:
```
...
serviceAccountName: foo-sa
....
  volumes:
      - name: level1
        projected:
          sources:
          - serviceAccountToken:
              path: tokenPath
              expirationSeconds: 6000
              audience: foo-audiences
              level: 1
      - name: level2
        projected:
          sources:
          - serviceAccountToken:
              path: tokenPath
              expirationSeconds: 6000
              audience: foo-audiences
              level: 2
      - name: level3
        projected:
          sources:
          - serviceAccountToken:
              path: tokenPath
              expirationSeconds: 6000
              audience: foo-audiences
              level: 3
```



2. Create three RoleBinding Object corresponding three level serviceaccount, we take level-1 serviceaccount as an example here.
subjects:
```
- kind: ServiceAccount
  name: foo-sa
  level: 1
  apiGroup: rbac.authorization.k8s.io

```

3. Bounds each RoleBinding with different Role which gives them different authority.

4. For some case which do authorization taking  pod as a whole like PodSecurityPolicy. User could bounds its role with level-0 serviceaccount . On this way , all level serviceaccount share this policy. 

@mikedanese  WDYT
