### ISSUE TITLE
FlexVolue (1.10.4): err=no volume plugin matched

### ISSUE THREAD

**Issue by de1m** [kubernetes/kubernetes#66021]
/kind bug

**What happened**:
I've a example pod and will mount a smb mount
```
apiVersion: batch/v1
kind: Pod
metadata:
  name: plop
spec:
  spec:
    containers:
      - name: plop
        image: "alpine:latest"
        command: ["/bin/ls", "-lah", "/mnt"]
        volumeMounts:
        - mountPath: /mnt
          name: video
    restartPolicy: Never
    volumes:
      - name: video
        flexVolume:
          driver: "hodique.info/cifs"
          secretRef:
            name: "volume-secret"
          options:
            source: "//192.168.40.158/surveillance"
            mountOptions: "dir_mode=0755,file_mode=0644,noperm"
---
apiVersion: v1
kind: Secret
metadata:
  name: volume-secret
data:
  username: bW9ssb3RpeA==
  password: c3VydsspbGxhbmNlNEFESVRP
```
### kubelet.env
```
ceku@ceku1 ~> cat /etc/kubernetes/kubelet.env
# logging to stderr means we get it in the systemd journal
KUBE_LOGTOSTDERR="--logtostderr=true"
KUBE_LOG_LEVEL="--v=2"
# The address for the info server to serve on (set to 0.0.0.0 or "" for all interfaces)
KUBELET_ADDRESS="--address=0.0.0.0 --node-ip=192.168.49.201"
# The port for the info server to serve on
# KUBELET_PORT="--port=10250"
# You may leave this blank to use the actual hostname
KUBELET_HOSTNAME="--hostname-override=ceku1"

KUBELET_ARGS="--pod-manifest-path=/etc/kubernetes/manifests \
--cadvisor-port=0 \
--pod-infra-container-image=gcr.io/google_containers/pause-amd64:3.0 \
--node-status-update-frequency=10s \
--docker-disable-shared-pid=True \
--client-ca-file=/etc/kubernetes/ssl/ca.pem \
--tls-cert-file=/etc/kubernetes/ssl/node-ceku1.pem \
--tls-private-key-file=/etc/kubernetes/ssl/node-ceku1-key.pem \
--anonymous-auth=false \
--read-only-port=0 \
--cgroup-driver=cgroupfs \
--cgroups-per-qos=True \
--max-pods=110 \
--fail-swap-on=True \
--authentication-token-webhook \
--enforce-node-allocatable=""  --cluster-dns=10.233.0.3 --cluster-domain=k8s-cluster.internal --resolv-conf=/etc/resolv.conf --kubeconfig=/etc/kubernetes/node-kubeconfig.yaml --kube-reserved cpu=200m,memory=512M --node-labels=node-role.kubernetes.io/master=true,node-role.kubernetes.io/node=true  --feature-gates=Initializers=False,PersistentLocalVolumes=False,VolumeScheduling=False,MountPropagation=True  "
KUBELET_NETWORK_PLUGIN="--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"

KUBELET_VOLUME_PLUGIN="--volume-plugin-dir=/var/lib/kubelet/volume-plugins"

# Should this cluster be allowed to run privileged docker containers
KUBE_ALLOW_PRIV="--allow-privileged=true"
KUBELET_CLOUDPROVIDER=""

PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

```

**What you expected to happen**:
I've copy in the folder /var/lib/kubelet/volume-plugins/exec the project from https://github.com/sigma/cifs_k8s_plugin/blob/master/cifs.sh
and now I get the error:
```
Jul 10 11:27:39 ceku3 kubelet[1866]: E0710 11:27:39.721945    1866 desired_state_of_world_populator.go:293] Failed to add volume "video" (specName: "video") for pod "1c3475e0-8434-11e8-af15-ac1f6b664c4c" to desiredStateOfWorld.     err=failed to get Plugin from volumeSpec for volume "video" err=no volume plugin matched
```
I've tested also with another FlexVolume pluging, but I get the same behaviour.
### Folder content /var/lib/kubelet/volume-plugins/exec
```
/var/lib/kubelet/volume-plugins/exec/hodique.info~cifs/:
total 12K
drwxr-xr-x 2 root root 4,0K Jul 10 11:19 ./
drwxr-xr-x 6 root root 4,0K Jul 10 11:19 ../
-rwxr-xr-x 1 root root 3,3K Jul 10 11:19 cifs*
```
**Anything else we need to know?**:
I've installed the kubernetes with kubespray

**Environment**: 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
bare metall installation
- OS (e.g. from /etc/os-release):
`
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
`
- Kernel (e.g. `uname -a`):
`Linux ceku1 4.15.0-24-generic #26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
/sig bug
