### ISSUE TITLE
PVC does not have all the labels when created from volumeClaimTemplate in StatefulSet.

### ISSUE THREAD

**Issue by juris** [kubernetes/kubernetes#66119]
/kind bug

**What happened**:
PVC does not have all the labels when created from volumeClaimTemplate in StatefulSet.

For example, if I define the following claim template as a part of STS manifest:
```
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
        volume.beta.kubernetes.io/storage-class: gp2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      selector:
        matchLabels:
           app: "grafana"
           project: "mint"

```

It produces the following PVC:
```
$ kubectl describe pvc datadir-grafana-0                                                                                                                                                                                                                          
Name:          datadir-grafana-0
Namespace:     default
StorageClass:  gp2
Status:        Bound
Volume:        grafana-001
Labels:        app=grafana
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
               volume.beta.kubernetes.io/storage-class=gp2
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/aws-ebs
Finalizers:    []
Capacity:      1Gi
Access Modes:  RWO
```

Two labels defined. Only one label present :(

**What you expected to happen**:
I expect PVC to have both labels.

**How to reproduce it (as minimally and precisely as possible)**:
Create STS with volumeClaimTemplate which has more than 1 label. Then try to describe it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version                                                                                                                                                                                                                        
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-22T05:40:33Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.8", GitCommit:"c138b85178156011dc934c2c9f4837476876fb07", GitTreeState:"clean", BuildDate:"2018-05-21T18:53:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.5.0
VERSION_ID=1745.5.0
BUILD_ID=2018-05-31-0701
PRETTY_NAME="Container Linux by CoreOS 1745.5.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux ip-10-113-86-196 4.14.44-coreos-r1 #1 SMP Thu May 31 06:04:02 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools:
kops
- Others:
