### ISSUE TITLE
1.10.0 ProgressDeadlineSeconds default added to v1beta1 deployment

### ISSUE THREAD

**Issue by dturn** [kubernetes/kubernetes#66135]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When I create a deployment with `apiVersion: extensions/v1beta1 ` and no `progressDeadlineSeconds` set, the resource is actually created with `"progressDeadlineSeconds": 600`. This does not happen in 1.9.x versions of Kubernetes.

**What you expected to happen**:

I expect the resource to not have a `progressDeadlineSeconds` added, since the [docs](https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#on-compatibility) say that its not acceptable to change the default values.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a minimal deployment example in a 1.10.0 cluster

example_deployment.yml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-example
spec:
  template:
    metadata:
      labels:
        app: deployment-example
    spec:
      containers:
      - name: sidecar
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["tail", "-f", "/dev/null"]
```

kubectl -v8 --context minikube -n test create -f  example_deployment.yml

**Anything else we need to know?**:

I don't have any evidence but am wondering if this bug is related to: https://github.com/kubernetes/kubernetes/pull/61419 

**Environment**:
- Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:54:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`minikube version: v0.28.0`
- OS (e.g. from /etc/os-release):` OSX 10.13.6`
- Kernel (e.g. `uname -a`): 
```
17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```
- Install tools:
- Others:
