### ISSUE TITLE
can we support create extended-resources with yaml ?

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes/kubernetes#66204]
/kind feature
/sig node

In really world,many resources have been limited.
such as elastic network interface, which only can be created 8 or less, it's limited by `qemu`.

I found that we can create a extended-resources to describe the limit, however, 
the `curl` is not producted method.

can we imporve this ? 
example
```
curl --header "Content-Type: application/json-patch+json" \
--request PATCH \
--data '[{"op": "add", "path": "/status/capacity/pod.alpha.kubernetes.io~1opaque-int-resource-eni", "value": "8"}]' \
http://127.0.0.0.1:60001/api/v1/nodes/10.0.0.22/status
``` 

```yaml
apiVersion: v1
kind: Extended-resources
metadata:
  name: eni-nr
spec:
  nodeSelector:
    kubernetes.io/hostname: 10.0.0.22
 value:
    pod.alpha.kubernetes.io/opaque-int-resource-eni:  8
```

and we can modify the nodeSelector to create the extern resource, is that easy to use ?
