### ISSUE TITLE
kubectl convert removes .metadata.namespace since v1.11.0

### ISSUE THREAD

**Issue by dohnto** [kubernetes/kubernetes#66276]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

`kubectl convert` version **v1.11.0** started to remove `.metadata.namespace` field from my manifests.

**What you expected to happen**:

Keep `.metadata.namespace` as in previous versions.

**How to reproduce it (as minimally and precisely as possible)**:

First let me present the behaviour using kubectl v.1.10

```yaml
$ cat rq.yaml 
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: kube-public    #  <<<< note that there is a namespace specified
spec:
  hard:
    pods: 10
$ kubectl-1.10.0 version --client
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl convert --filename=rq.yaml --output=yaml --local 
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: compute-resources
  namespace: kube-public   # <<< note that this field is still present
spec:
  hard:
    pods: "10"
status: {}
```

Now the new `kubectl` version
```yaml
$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl convert --filename=rq.yaml --output=yaml --local 
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: compute-resources    # <<< note that there is no .metadata.namespace field anymore
spec:
  hard:
    pods: "10"
status: {}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yue9944882** [comment]
confirmed this BUG.

/assign

**Comment by yue9944882** [comment]
hi @dohnto I'm afraid you have to run with `--local=false`, or `kubectl` doesn't know if the converting resource is namespaced or not. Does it solve your problem?

/unassign

**Comment by dohnto** [comment]
No.

```bash
$ kubectl-1.11.0 version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
```yaml
$ kubectl-1.11.0 convert --filename=rq.yaml --output=yaml 
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: compute-resources
spec:
  hard:
    pods: "10"
status: {}
```
