### ISSUE TITLE
mount: wrong fs type, bad option, bad superblock

### ISSUE THREAD

**Issue by jiuchongxiao** [kubernetes/kubernetes#66325]
i use cephfs directly by pod,my pod detail is as below:

```
apiVersion: v1
kind: Pod
metadata:
  name: ceph-pod2-with-secret
spec:
  containers:
  - name: ceph-ubuntu2
    image: ubuntu:14.04
    command: ["tail", "-f", "/var/log/bootstrap.log"]
    volumeMounts:
    - name: ceph-vol2
      mountPath: /mnt/cephfs/data
      readOnly: false
  volumes:
  - name: ceph-vol2
    cephfs:
      monitors:
      - 192.168.181.93:6789
      user: admin
      secretFile: "/data/cephfs/admin.secret"
      readOnly: false
```
my admin.secret file as below:
AQDirEhbxggJAhAAHtsEZJlRQZGT9+4YGMkMyQ==
![image](https://user-images.githubusercontent.com/13093730/42856275-1220cd00-8a77-11e8-86a9-e6ebf2330c9f.png)

kubectl describe pod ceph-pod2-with-secret
```
Mounting arguments: -t ceph -o name=admin,secretfile=/data/cephfs/admin.secret 192.168.181.93:6789:/ /var/lib/kubelet/pods/488936de-8a2b-11e8-a44a-000c29cc5e76/volumes/kubernetes.io~cephfs/ceph-vol2
Output: mount: wrong fs type, bad option, bad superblock on 192.168.181.93:6789:/,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

```
my cephfs is well,the follow is the detail
![image](https://user-images.githubusercontent.com/13093730/42855080-6e1bc9bc-8a71-11e8-9ba7-c0abe9198517.png)

ceph info
```
[root@node93 ceph]# ceph -s
  cluster:
    id:     20631ce0-4c16-4b5e-9f45-759943951a45
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum node93,node94,node95
    mgr: node93(active), standbys: node94, node95
    mds: test_fs-1/1/1 up  {0=node95=up:active}, 2 up:standby
    osd: 3 osds: 3 up, 3 in
    rgw: 3 daemons active
 
  data:
    pools:   9 pools, 241 pgs
    objects: 437 objects, 521 MB
    usage:   4087 MB used, 299 GB / 303 GB avail
    pgs:     241 active+clean
 
  io:
    client:   0 B/s rd, 9206 B/s wr, 0 op/s rd, 1 op/s wr
```
kubernetes version info 
```
[root@node128 cephfs]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
