### ISSUE TITLE
Annotation content mangled in mounted file

### ISSUE THREAD

**Issue by calind** [kubernetes/kubernetes#66375]
/kind bug

**What happened**:
Annotation content mangled in mounted file

**What you expected to happen**:
The content of the file to match exactly the annotation

**How to reproduce it (as minimally and precisely as possible)**:
The content of `buggy-pod.yaml`:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: buggy-pod
  annotations:
    nginx-conf: |
      upstream php {
        server 127.0.0.1:9000;
      }
spec:
  restartPolicy: Never
  volumes:
    - name: nginx-conf
      downwardAPI:
        items:
          - path: "default.conf"
            fieldRef:
              fieldPath: metadata.annotations['nginx-conf']
  containers:
    - name: busybox
      image: busybox
      args: ['cat', '/etc/nginx/default.conf']
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/
```
```
# kubectl apply -f buggy-pod.yaml
# kubectl logs buggy-pod

  server 127.0.0.1:9000;
upstream php {
}
```

The expected output would be:
```
upstream php {
  server 127.0.0.1:9000;
}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: docker-for-mac 18.05.0-ce-mac67 (25042)
- OS (e.g. from /etc/os-release): Docker for MAC
- Kernel (e.g. `uname -a`): `Linux linuxkit-025000000001 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 Linux`
- Install tools:
- Others:
