### ISSUE TITLE
Endpoints have stopped working with GKE version 1.8.11

### ISSUE THREAD

**Issue by psandhu79** [kubernetes/kubernetes#66384]
/kind bug

**What happened**:
Using Endpoints with Kubernetes 1.8.11-gke.0 has stopped working version 1.8.10-gke.0 works fine.

**What you expected to happen**:
 Our app should be able to use the service name to access the endpoint

**How to reproduce it (as minimally and precisely as possible)**:

```
kind: Service
apiVersion: v1
metadata:
 namespace: wonderland
 name: point
spec:
 ports:
 - port: 80
   targetPort: 80
---
kind: Endpoints
apiVersion: v1
metadata:
 namespace: wonderland
 name: point
subsets:
 - addresses:
     - ip: 10.132.0.10
   ports:
     - port: 80
```
**Anything else we need to know?**:

The file above works with 1.8.10-gke.0 but not with 1.8.11-gke.0 and tested 1.10.5-gke.0 does not work either
