### ISSUE TITLE
`kubectl apply` failed to update resources in different namespaces

### ISSUE THREAD

**Issue by ashi009** [kubernetes/kubernetes#66401]
/kind bug

**What happened**:
When applying a config file with resources in multiple namespaces, the first namespace will be applied to all other resources.

**What you expected to happen**:
resources created in their own namespaces.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: v1
kind: List
items:
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ingress-production
      namespace: production
    spec:
      rules:
        - host: a.test.com
          http:
            paths:
              - backend:
                  serviceName: a-production
                  servicePort: http
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ingress-dev
      namespace: dev
    spec:
      rules:
        - host: a-dev.test.com
          http:
            paths:
              - backend:
                  serviceName: a-dev
                  servicePort: http
```

**Anything else we need to know?**:
-

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.2", GitCommit:"f199298d18103a59db32d97a92072fbb17b1175a", GitTreeState:"clean", BuildDate:"2018-07-10T02:37:32Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
cc @kubernetes/sig-cli-bugs

**Comment by ardaguclu** [comment]
@ashi009 after creating `prod` and `dev` namespaces,I applied this;

```
apiVersion: v1
kind: List
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-prod
      namespace: prod
    spec:
      defaultBackend:
        service:
          name: test
          port:
            number: 80
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-dev
      namespace: dev
    spec:
      defaultBackend:
        service:
          name: test
          port:
            number: 80
```
and it returns as expected;

```
cluster/kubectl.sh get ingresses --all-namespaces
NAMESPACE   NAME           CLASS    HOSTS   ADDRESS   PORTS   AGE
dev         ingress-dev    <none>   *                 80      12s
prod       ingress-prod   <none>   *                 80      12s
```

I think we can close this issue.
