### ISSUE TITLE
Pod Volume Mount with subPath causes container creation to fail

### ISSUE THREAD

**Issue by BrendanThompson** [kubernetes/kubernetes#66583]
/kind bug

**What happened**:

When creating a pod based off of the below spec, I receive `CreateContainerConfigError`. In `kubectl describe pod/pod_name` the following message is shown:

```
Error: stat /logs/pods/: no such file or directory
```

The following is the Deployment spec:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myapp-web-inf
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        role: web
        tier: frontend
        env: inf
        app_ver: 7.3.0
        dci_ver: 1.0.4
    spec:
      containers:
      - name: myapp-web
        image: image
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_HOST
          value: ""
        - name: JMX_SERVER_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: logs
          mountPath: /logs
          subPath: $(POD_NAME)
      imagePullSecrets:
      - name: cicdacr
      volumes:
      - name: logs
        hostPath:
          path: /logs/pods/
```

**What you expected to happen**:

I expect the pod to mount a volume thats linked back to a directory of the pods hostname on the host.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
| App | Version |
| --- | --- |
| Kubernetes | `v1.11.1` |
| Docker | `v1.13.1` |
| Ubuntu | `16.04.4` |
| Kernel | `4.15.0-1013-azure` |

Cloud Provider: Azure
Install Tools: [ACS-engine](https://github.com/Azure/acs-engine)

This is linked to: #61076

//cc @msau42

**Comment by msau42** [comment]
Ah I think the issue is the hostPath doesn't exist, and subPath processing now requires that the base volume already exists.

To fix this issue, you should specify `type: DirectoryOrCreate` in your hostpath specification, so that the directory is created by Kubernetes, instead of the container runtime:
```
      volumes:
      - name: logs
        hostPath:
          path: /logs/pods
          type: DirectoryOrCreate
```
