### ISSUE TITLE
k8s + Flannel + Vagrant => DNS problem: "Name or service not known"

### ISSUE THREAD

**Issue by huyqut** [kubernetes/kubernetes#66654]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

/kind bug

**What happened**:

I setup a Kubernetes mini-cluster (1 master - 1 node) using Vagrant. CNI is Flannel. Everything is set and both master and node are ready. No problem whatsoever with kube-system pods.

However, when I try a simple deploy: 
```
kubectl run centos --image=centos:7 --command -- sleep infinity
````
and try to exec into it. DNS cannot be looked up:
```
$ ping google.com
ping: google.com: Name or service not known
$ ping kubernetes
ping: kubernetes: Name or service not known
```

Nothing works. If I try to deploy on production (real live servers), it works normally.
```
[root@centos-6f6d998c5c-c94f9 /]# ping google.com
PING google.com (216.58.197.110) 56(84) bytes of data.
64 bytes from hkg12s01-in-f14.1e100.net (216.58.197.110): icmp_seq=1 ttl=50 time=38.9 ms
64 bytes from hkg12s01-in-f14.1e100.net (216.58.197.110): icmp_seq=2 ttl=50 time=38.8 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
```

**What you expected to happen**:

`ping` should be ok.

**How to reproduce it (as minimally and precisely as possible)**:
1. `vagrant up` CentOS 7 boxes
1. Install `iptables`, `docker`, `docker-compose`, `kubeadm`, `kubelet`, `kubectl`
1. Whitelist iptables on master (node is the same cause it is only a subnet of this):
```
-A INPUT -p tcp --dport 5353 -j ACCEPT
-A INPUT -p tcp --dport 6443 -j ACCEPT
-A INPUT -p tcp --dport 6782 -j ACCEPT
-A INPUT -p tcp --dport 6783 -j ACCEPT
-A INPUT -p tcp --dport 6784 -j ACCEPT
-A INPUT -p tcp --dport 2379:2380 -j ACCEPT
-A INPUT -p tcp --dport 10250 -j ACCEPT
-A INPUT -p tcp --dport 10251 -j ACCEPT
-A INPUT -p tcp --dport 10252 -j ACCEPT
-A INPUT -p udp --dport 8285 -j ACCEPT
-A INPUT -p udp --dport 8472 -j ACCEPT
```
1. Sysctl:
```
net.bridge.bridge-nf-call-ip6tables=1
net.bridge.bridge-nf-call-iptables=1
net.bridge.bridge-nf-call-arptables=1
net.ipv4.ip_forward=1
```
1. Swap off: `swapoff -a`
1. Disable SELinux: `setenforce 0`
1. Initialize local etcd with `docker-compose`:
```
version: '3'

services:
  etcd:
    image: gcr.io/etcd-development/etcd
    network_mode: host
    entrypoint: /usr/local/bin/etcd
    command:
      - --config-file=/etcd.conf.yml
    volumes:
      - ./data:/etcd-data
      - ./etcd.conf.yml:/etcd.conf.yml
```
1. Initialize master with the following config file:
```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.0
api:
 advertiseAddress: 192.168.101.91
nodeRegistration:
 name: k8s-master
etcd:
 external:
   endpoints:
     - http://localhost:2379
networking:
 podSubnet: 10.244.0.0/16
```
1. Apply Flannel network from `https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/`
1. Join node

**Anything else we need to know?**:

All nodes are ready.
All `kube-system` is running. No restarts, CrashLoopBackOff, or Error.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration: Bare Metal
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): `Linux k8s-master 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `kubeadm`
- Others:
