### ISSUE TITLE
kube-proxy: node-port ipv6 port open on v4 cluster 

### ISSUE THREAD

**Issue by NeilW** [kubernetes/kubernetes#66766]
/kind bug

**What happened**:

When creating a node port application (in this case the example guestbook) on a host server that is dual stacked and has AAAA and A DNS entries, the node port on the v6 address is open to kube-proxy and hangs. 

**What you expected to happen**:

The v6 address would refuse the connection and the client would fall back onto the v4 address which would connect correctly.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
clusterName: kubernetes
api:
  advertiseAddress: <ipv4 address>
networking:
  dnsDomain: cluster.local
  podSubnet: 192.168.0.0/16
  serviceSubnet: 172.30.0.0/16
bootstrapTokens:
  - token: v315ij.jrg9nu08ayho78q7
kubeProxy:
  config:
    mode: ipvs
    ipvs:
      scheduler: lc
```

kubeadm init with the above, and join in some workers. Then install the guestbook application https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

Obtain the node port with `kubectl get services frontend` and telnet to one of the servers on that port from a dual stacked client. The client will connect and refuse to respond to 'GET /'

telnet directly to the IPv4 address of the server on the port and all works as expected. 

**Anything else we need to know?**:

kube-proxy is noted as listening on the port. 

```
ubuntu@srv-jidtj:~$ sudo ss -l -t -p | grep 31759
LISTEN   0         128                       *:31759                   *:*       users:(("kube-proxy",pid=2268,fd=7))
```

**Environment**:
- Kubernetes version (use `kubectl version`):
ubuntu@srv-jidtj:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Brightbox
- OS (e.g. from /etc/os-release):
Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`):
Linux srv-jidtj 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm 1.11
- Others:
