### ISSUE TITLE
Cannot create Internal loadbalancer on Reserved GCE ip

### ISSUE THREAD

**Issue by ffilippopoulos** [kubernetes/kubernetes#66762]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

/sig gcp

**What happened**:
Trying to create an internal loadbalancer using kubernetes services of `type: LoadBalancer` and specifying `loadBalancerIP` on a kube cluster running on gcp. This ip was already reserved (but not in use) in order to be able to create a dns record for it.
```
my-ip-address       europe-west2  10.22.22.8      RESERVED
```
kube-controller was unable to create the load balancer throwing the following:
```
I0730 08:28:20.779176       1 event.go:221] Event(v1.ObjectReference{Kind:"Service", Namespace:"sys-ingress-priv", Name:"internal-ingress-proxy", UID:"1ed6abda-931f-11e8-a620-42010a16160b", APIVersion:"v1", ResourceVersion:"7257872", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): failed to ensure load balancer for service sys-ingress-priv/internal-ingress-proxy: GCE 200 - IP_IN_USE_BY_ANOTHER_RESOURCE: IP '10.22.22.8' is already being used by another resource. 
```
which is basically not true since the ip is just reserved but not in use.

Digging a bit more into it, it looks that the error might be coming from here: https://github.com/kubernetes/kubernetes/blob/28b6fb5f7d4ec9fc0be2843d61543ef70b748e70/pkg/cloudprovider/providers/gce/gce_loadbalancer_internal.go#L98 as it looks like it is trying to reserve the ip that is passed to `loadBalancerIP`.

In fact if I try this with another free/unreserved ip I see kube temporarily reserving it:
```
a1ed6abda931f11e8a62042010a16160         europe-west2  10.22.22.100    RESERVED
```
and then releasing it after creating successfully creating my loadbalancer.

**What you expected to happen**:

This scenario (first reserving an ip and then passing it to the lb service) is working for external ip addresses and I would expect it to work for internal ones the same way.
There are use cases where we need to rely on an internal ip being reserved and linked with a dns record.

**How to reproduce it (as minimally and precisely as possible)**:
Reserve an internal ip from gcp console and then try to create a load balancer that uses it, like:
```
 apiVersion: v1
 kind: Service
 metadata:
   name: my-service
   annotations:
     cloud.google.com/load-balancer-type: "Internal"
 spec:
   selector:
     app: my-app
   type: LoadBalancer
   loadBalancerIP: 10.x.x.x
   ports:
   - name: http
     port: 80
     nodePort: 30080
   selector:
     k8s-app: my-app
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
gce
- OS (e.g. from /etc/os-release):
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1745.7.0
VERSION_ID=1745.7.0
BUILD_ID=2018-06-14-0909
PRETTY_NAME="Container Linux by CoreOS 1745.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux worker-k8s-exp-1-4q8t.c.uw-dev.internal 4.14.48-coreos-r2 #1 SMP Thu Jun 14 08:23:03 UTC 2018 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
```

**Comment by furlongce** [comment]
Any update on this?

**Comment by ffilippopoulos** [comment]
We have tried the same experiment as described in the description on kube `v1.16.2` and looks like it works fine now.

So after creating an `google_compute_address` of type `INTERNAL` via terraform we can apply a service like the following:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  name: my-svc
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: <ip-goes-here>
  ports:
  - name: web
    nodePort: 30380
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-app
  type: LoadBalancer
```
and kube was able to create the load balancer and use the specified ip.

As a result I am closing this issue as fixed with version 1.16.2 (at least)
