### ISSUE TITLE
kubelet increased number of HTTP 404 errors

### ISSUE THREAD

**Issue by p0lyn0mial** [kubernetes/kubernetes#66775]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I'm observing increased number of HTTP `404` errors (kubernetes API server) when scheduling my `CronJob`s to run every 2 minutes. The metric I'm observing `rest_client_requests_total` is coming from kubelet `/metrics` endpoint.

**What you expected to happen**:
Scheduling my `CronJob`s to run every 2 minutes doesn't increase the number of HTTP 404 errors.

**How to reproduce it (as minimally and precisely as possible)**:
Just create the following `CronJob` and read the api server logs.

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"creationTimestamp":null,"name":"etcd-backup-p95cd5wffg","namespace":"kube-system","selfLink":"/apis/batch/v1beta1/namespaces/kube-system/cronjobs/etcd-backup-p95cd5wffg"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":1,"jobTemplate":{"metadata":{"creationTimestamp":null},"spec":{"template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"command":["/bin/sh","-c","/bin/true\n"],"env":[{"name":"CLUSTER","value":"p95cd5wffg"}],"image":"ubuntu","imagePullPolicy":"IfNotPresent","name":"store-container","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","initContainers":[{"command":["/bin/sh","-c","/bin/true\n"],"env":[{"name":"ETCDCTL_API","value":"3"}],"image":"ubuntu","imagePullPolicy":"IfNotPresent","name":"backup-creator","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"restartPolicy":"OnFailure","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}},"schedule":"@every 1m","successfulJobsHistoryLimit":0,"suspend":false},"status":{}}
  creationTimestamp: null
  name: etcd-backup-p95cd5wffg
  selfLink: /apis/batch/v1beta1/namespaces/kube-system/cronjobs/etcd-backup-p95cd5wffg
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - |
              sleep 20s
            env:
            - name: CLUSTER
              value: p95cd5wffg
            image: ubuntu
            imagePullPolicy: IfNotPresent
            name: store-container
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 0
  schedule: '@every 2m'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
```

**Anything else we need to know?**:
I'm attaching some logs from `api-server` and `kubelet`

`kube-api-server`
51:I0730 12:29:29.011232       1 wrap.go:42] GET /api/v1/namespaces/default/pods/etcd-backup-p95cd5wffg-1532953378-t4sxr: (3.718666ms) 404 [[kubelet/v1.10.5 (linux/amd64) kubernetes/32ac1c9]]
75:I0730 12:29:29.581947       1 wrap.go:42] GET /api/v1/namespaces/default/pods/etcd-backup-p95cd5wffg-1532953378-t4sxr: (1.960296ms) 404 [[kubelet/v1.10.5 (linux/amd64) kubernetes/32ac1c9]]
2122:I0730 12:31:29.581988       1 wrap.go:42] GET /api/v1/namespaces/default/pods/etcd-backup-p95cd5wffg-1532953498-b2j6t: (1.873793ms) 404 [[kubelet/v1.10.5 (linux/amd64) kubernetes/32ac1c9]]
7993:I0730 12:39:31.750073       1 wrap.go:42] GET /api/v1/namespaces/default/pods/etcd-backup-p95cd5wffg-1532953978-q794g: (1.378595ms) 404 [[kubelet/v1.10.5 (linux/amd64) kubernetes/32ac1c9]]
11301:I0730 12:43:33.401057       1 wrap.go:42] GET /api/v1/namespaces/default/pods/etcd-backup-p95cd5wffg-1532954218-j6bcp: (69.161781ms) 404 [[kubelet/v1.10.5 (linux/amd64) kubernetes/32ac1c9]]
20873:I0730 12:55:28.808045       1 wrap.go:42] GET /api/v1/namespaces/default/pods/etcd-backup-p95cd5wffg-1532954938-2n6sb: (2.16757ms) 404 [[kubelet/v1.10.5 (linux/amd64) kubernetes/32ac1c9]]
20887:I0730 12:55:29.580998       1 wrap.go:42] GET /api/v1/namespaces/default/pods/etcd-backup-p95cd5wffg-1532954938-2n6sb: (2.016323ms) 404 [[kubelet/v1.10.5 (linux/amd64) kubernetes/32ac1c9]]

`kubelet`
1723:Jul 30 12:49:06 pqd44 kubelet[10710]: I0730 12:49:06.008408   10710 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-ck49c" (UniqueName: "kubernetes.io/secret/f191dcfb-93f6-11e8-b226-a68ab041e8ef-default-token-ck49c") pod "etcd-backup-p95cd5wffg-1532954938-2n6sb" (UID: "f191dcfb-93f6-11e8-b226-a68ab041e8ef")
1724:Jul 30 12:49:06 pqd44 kubelet[10710]: 2018-07-30 12:49:06.476 [INFO][2138] calico.go 87: Extracted identifiers ContainerID="bc5207a17c42a137528fd4c9b89bf21dfc45a76399e43209069dc4f029d2185b" Node="pqd44" Orchestrator="k8s" Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb"
1726:Jul 30 12:49:06 pqd44 kubelet[10710]: t { Key string "json:\"key\""; Value string "json:\"value\"" }(nil)}}}}, EtcdScheme:"", EtcdKeyFile:"", EtcdCertFile:"", EtcdCaCertFile:""} Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb"
1727:Jul 30 12:49:06 pqd44 kubelet[10710]: 2018-07-30 12:49:06.478 [INFO][2138] utils.go 250: Configured environment: [CNI_COMMAND=ADD CNI_CONTAINERID=bc5207a17c42a137528fd4c9b89bf21dfc45a76399e43209069dc4f029d2185b CNI_NETNS=/proc/2108/ns/net CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=etcd-backup-p95cd5wffg-1532954938-2n6sb;K8S_POD_INFRA_CONTAINER_ID=bc5207a17c42a137528fd4c9b89bf21dfc45a76399e43209069dc4f029d2185b CNI_IFNAME=eth0 CNI_PATH=/opt/calico/bin:/opt/cni/bin PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt KUBELET_CADVISOR_ARGS=--cadvisor-port=0 KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki KUBELET_EXTRA_ARGS=  --authentication-token-webhook=true --hostname-override=pqd44 --read-only-port 0   --cluster-dns=10.10.10.10 --cluster-domain=cluster.local DATASTORE_TYPE=kubernetes KUBECONFIG=/etc/cni/net.d/calico-kubeconfig K8S_API_ENDPOINT=https://10.10.10.1:443 K8S_API_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjYW5hbC10b2tlbi1jMjR0cCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjYW5hbCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjIzMTM1MTQyLTkzZTctMTFlOC1iMjI2LWE2OGFiMDQxZThlZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpjYW5hbCJ9.is7kSNBVo0OjY1HTKg_GlyZoSXxcQTr21wTcEWFJ_R_GZuuVsHBEA4Gs4BchyilwoaMPFx_Y30GF2QVi8zh1Twy9_O5Q97A
1731:Jul 30 12:49:06 pqd44 kubelet[10710]: 2018-07-30 12:49:06.505 [INFO][2138] k8s.go 67: Extracted identifiers for CmdAddK8s Node="pqd44" Orchestrator="k8s" Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb"
1733:Jul 30 12:49:06 pqd44 kubelet[10710]: 2018-07-30 12:49:06.512 [INFO][2138] k8s.go 100: Fetched podCidr Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb" podCidr="172.25.0.0/24"
1735:Jul 30 12:49:06 pqd44 kubelet[10710]: 2018-07-30 12:49:06.520 [INFO][2138] k8s.go 264: Populated endpoint Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb" endpoint=WorkloadEndpoint(Node=pqd44, Orchestrator=k8s, Workload=default.etcd-backup-p95cd5wffg-1532954938-2n6sb, Name=eth0)
1737:Jul 30 12:49:06 pqd44 kubelet[10710]: 2018-07-30 12:49:06.533 [INFO][2138] k8s.go 288: Added Mac, interface name, and active container ID to endpoint Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb" endpoint=WorkloadEndpoint(Node=pqd44, Orchestrator=k8s, Workload=default.etcd-backup-p95cd5wffg-1532954938-2n6sb, Name=eth0, ActiveInstanceID=bc5207a17c42a137528fd4c9b89bf21dfc45a76399e43209069dc4f029d2185b)
1738:Jul 30 12:49:06 pqd44 kubelet[10710]: 2018-07-30 12:49:06.564 [INFO][2138] k8s.go 296: Wrote updated endpoint to datastore Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb"
1742:Jul 30 12:49:27 pqd44 kubelet[10710]: 2018-07-30 12:49:27.378 [INFO][2510] calico.go 315: Extracted identifiers ContainerID="bc5207a17c42a137528fd4c9b89bf21dfc45a76399e43209069dc4f029d2185b" Node="pqd44" Orchestrator="k8s" Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb"
1743:Jul 30 12:49:27 pqd44 kubelet[10710]: 2018-07-30 12:49:27.379 [INFO][2510] utils.go 250: Configured environment: [CNI_COMMAND=DEL CNI_CONTAINERID=bc5207a17c42a137528fd4c9b89bf21dfc45a76399e43209069dc4f029d2185b CNI_NETNS=/proc/2108/ns/net CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=etcd-backup-p95cd5wffg-1532954938-2n6sb;K8S_POD_INFRA_CONTAINER_ID=bc5207a17c42a137528fd4c9b89bf21dfc45a76399e43209069dc4f029d2185b CNI_IFNAME=eth0 CNI_PATH=/opt/calico/bin:/opt/cni/bin PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt KUBELET_CADVISOR_ARGS=--cadvisor-port=0 KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki KUBELET_EXTRA_ARGS=  --authentication-token-webhook=true --hostname-override=pqd44 --read-only-port 0   --cluster-dns=10.10.10.10 --cluster-domain=cluster.local DATASTORE_TYPE=kubernetes KUBECONFIG=/etc/cni/net.d/calico-kubeconfig K8S_API_ENDPOINT=https://10.10.10.1:443 K8S_API_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjYW5hbC10b2tlbi1jMjR0cCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjYW5hbCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjIzMTM1MTQyLTkzZTctMTFlOC1iMjI2LWE2OGFiMDQxZThlZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpjYW5hbCJ9.is7kSNBVo0OjY1HTKg_GlyZoSXxcQTr21wTcEWFJ_R_GZuuVsHBEA4Gs4BchyilwoaMPFx_Y30GF2QVi8zh1Twy9_O5Q97A
1747:Jul 30 12:49:27 pqd44 kubelet[10710]: 2018-07-30 12:49:27.408 [INFO][2510] k8s.go 346: Endpoint deletion will be handled by Kubernetes deletion of the Pod. Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb" endpoint=WorkloadEndpoint(Node=pqd44, Orchestrator=k8s, Workload=default.etcd-backup-p95cd5wffg-1532954938-2n6sb, Name=eth0)
1749:Jul 30 12:49:27 pqd44 kubelet[10710]: 2018-07-30 12:49:27.409 [INFO][2510] utils.go 94: Using a dummy podCidr to release the IP Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb" podCidr="0.0.0.0/0"
1751:Jul 30 12:49:27 pqd44 kubelet[10710]: 2018-07-30 12:49:27.425 [INFO][2510] k8s.go 367: Teardown processing complete. Workload="default.etcd-backup-p95cd5wffg-1532954938-2n6sb"
1752:Jul 30 12:49:27 pqd44 kubelet[10710]: E0730 12:49:27.591405   10710 kuberuntime_container.go:65] Can't make a ref to pod "etcd-backup-p95cd5wffg-1532954938-2n6sb_default(f191dcfb-93f6-11e8-b226-a68ab041e8ef)", container store-container: selfLink was empty, can't make reference

**Environment**:
Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
