### ISSUE TITLE
MasterConfigurarion used in kubeadm init does not apply to join

### ISSUE THREAD

**Issue by thdrnsdk** [kubernetes/kubernetes#66951]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

i'm install k8s in my labtop  use kubeadm.

$ kubeadm init --config=master.yaml

```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
api:
  advertiseAddress: 192.168.10.102
kubernetesVersion: 1.11.1
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
nodeName: mst1
imageRepository: MyPrivateRegistry
nodeRegistration:
  kubeletExtraArgs:
    pod-infra-container-image: MyPrivateRegistry/pause-amd64:3.1
kubeletConfiguration:
  baseConfig:
    cgroupDriver: systemd
    runtimeCgroups: "/systemd/system.slice"
    kubeletCgroups: "/systemd/system.slice"
    authentication:
      anonymous:
        enabled: true
      webhook:
        enabled: true
    authorization:
      mode: Webhook
    hostnameOverride: mst1
    readOnlyPort: 0
    eventQps: 0
etcd:
  local:
    image: MyPrivateRegistry/etcd-amd64:3.2.18
apiServerCertSANs:
```

so init completed. and use MyPrivateRegistry pause Image.

Master's KUBELET_KUBEADM_ARGS is (/var/lib/kubelet/kubeadm-flags.env)
```
KUBELET_KUBEADM_ARGS=--pod-infra-container-image=MyPrivateRegistry/pause-amd64:3.1 --cgroup-driver=systemd --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --network-plugin=cni
```

and join my node.

join cmd is complete but node's KUBELET_KUBEADM_ARGS is not eqal Master

Node's KUBELET_KUBEADM_ARGS is (/var/lib/kubelet/kubeadm-flags.env)
```
KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --network-plugin=cni
```

it does not contain "pod-infra-container-image" options.

**What you expected to happen**:

master's KUBELET_KUBEADM_ARGS is same to nodes

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.1
- Cloud provider or hardware configuration: local
- OS (e.g. from /etc/os-release):  CentOS 7.3
- Kernel (e.g. `uname -a`): Linux thdrnsdk 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm

/sig kubeadm
/kind bug

**Comment by neolit123** [comment]
i'm having trouble understanding the issue, but i don't think this is a bug.

the joining node configuration for v1alpha2 should use this:
https://github.com/kubernetes/kubernetes/blob/release-1.11/cmd/kubeadm/app/apis/kubeadm/v1alpha2/types.go#L234

```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    pod-infra-container-image: MyPrivateRegistry/pause-amd64:3.1
```

for further questions please try our support channels:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

#kubadm on slack and stack overflow.

/close
