### ISSUE TITLE
ELB cross zone load balancer annotation appears to break internal load balancer

### ISSUE THREAD

**Issue by thewire247** [kubernetes/kubernetes#66972]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig aws

**What happened**:
I added the annotation 
`service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled`
to a LoadBalancer service which has the following annotation to make it internal:
`service.beta.kubernetes.io/aws-load-balancer-internal:  0.0.0.0/0`
This then caused the load balancer to be destroyed and an external one put in its place. It also prevented our external dns service (registry.opensource.zalan.do/teapot/external-dns:v0.5.3) from being able to create the route53 records. 

**What you expected to happen**:
Cross zone load balancing to be enabled on the existing load balancer (we woudn't have minded if a replacement internal load balancer was created also)

**How to reproduce it (as minimally and precisely as possible)**:
```
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
  annotations:
    prometheus.io/scrape: 'true'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    external-dns.alpha.kubernetes.io/hostname: blah.com
    service.beta.kubernetes.io/aws-load-balancer-internal:  0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: blah
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: web
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
    external-dns.alpha.kubernetes.io/ttl: '60'
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 443
      targetPort: 82
      name: web
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: blah
```
Replace blah above with real values. 

**Anything else we need to know?**:
The above is intended to create a load balancer with an SSL TCP listener, not HTTPS

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration: AWS EC2 (not EKS)
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)  (centos 7.4)
- Kernel (e.g. `uname -a`): 4.9.77-31.58.amzn1.x86_64  (yes that is correct)
- Install tools: yum
- Others:
