### ISSUE TITLE
volumeClaimTemplates prefixes volumes with pvc instead of pv

### ISSUE THREAD

**Issue by gertcuykens** [kubernetes/kubernetes#66994]
kubernetes 1.10
![image](https://user-images.githubusercontent.com/863731/43690044-01efb1bc-9904-11e8-865b-7eb002fff042.png)

It confuses half of the population of plannet earth becuase pvc-d89ae164-98f1-11e8-98a0-025000000001 is a persistent volume

/sig storage

**Comment by liggitt** [comment]
volumeClaimTemplates creates PVC objects, so prefixing pvc is ok. It sounds like the dynamic provisioner might copy the pvc name for the pv

**Comment by gertcuykens** [comment]
correct, it shouldn't do that to confuse noobs like me
![image](https://user-images.githubusercontent.com/863731/43690736-b1503f7c-990f-11e8-945d-ea9bc3b0cd82.png)

**Comment by liggitt** [comment]
The provisioner isn't required to copy the name… which one are you using?

**Comment by gertcuykens** [comment]
the build in kuberentes one (mac osx docker for mac)
![image](https://user-images.githubusercontent.com/863731/43690796-b1538c30-9910-11e8-9a29-97c97517adbe.png)
I just apply this
```
---
kind: ConfigMap
apiVersion: v1
data:
  config: |
    [client]
    default-character-set = utf8

    [server]
    character-set-server = utf8
    collation-server = utf8_general_ci
    log_warnings=0
    binlog-format=ROW
    server-id=1
    log-slave-updates=ON
    log-bin=master

metadata:
  name: mariadb

---
kind: Service
apiVersion: v1
metadata:
  name: database
spec:
  type: NodePort
  ports:
  - name: sql
    port: 3306
    targetPort: 3306
    protocol: TCP

---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: database

spec:
  replicas: 1
  revisionHistoryLimit: 3
  serviceName: database
  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb

    spec:
      containers:
      - name: mariadb
        image: mariadb:10.1.29
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: centraldb
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - "ping"
            - "-hlocalhost"
            - "-uroot"
            - "-proot"
            - "--silent"
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: config
          mountPath: /etc/mysql/conf.d
        - name: pvc
          mountPath: /var/lib/mysql

      volumes:
      - name: config
        configMap:
          name: mariadb

      nodeSelector:

  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: hostpath
      resources:
        requests:
          storage: 1Gi

```
