### ISSUE TITLE
 Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:default:default\" cannot list endpoints in the namespace \"default\"" level=error ts=2018-08-05T15:57:36.310855162Z caller=main.go:221 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270:

### ISSUE THREAD

**Issue by Josbrafe** [kubernetes/kubernetes#66991]
Kindly, assist.
As I am trying get my test prometheus to work with a defined clusterrole and clusterbinding:
kubernetes version: 1.11.1

kubectl logs --namespace=default prometheus-prometheus-0 -c prometheus
Errors:
level=info ts=2018-08-05T16:08:06.381854063Z caller=main.go:225 msg="Starting Prometheus" version="(version=2.2.0-rc.0, branch=HEAD, revision=1fe05d40e4b2f4f7479048b1cc3c42865eb73bab)"
level=info ts=2018-08-05T16:08:06.381938127Z caller=main.go:226 build_context="(go=go1.9.2, user=root@f7abb25edc70, date=20180213-11:40:47)"
level=info ts=2018-08-05T16:08:06.381959036Z caller=main.go:227 host_details="(Linux 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 prometheus-prometheus-0 (none))"
level=info ts=2018-08-05T16:08:06.381978329Z caller=main.go:228 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2018-08-05T16:08:06.385777041Z caller=main.go:502 msg="Starting TSDB ..."
level=info ts=2018-08-05T16:08:06.386746127Z caller=web.go:383 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-08-05T16:08:06.399857408Z caller=main.go:512 msg="TSDB started"
level=info ts=2018-08-05T16:08:06.39994456Z caller=main.go:588 msg="Loading configuration file" filename=/etc/prometheus/config/prometheus.yaml
level=info ts=2018-08-05T16:08:06.400976783Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2018-08-05T16:08:06.402005438Z caller=main.go:489 msg="Server is ready to receive web requests."
level=error ts=2018-08-05T16:08:06.42462453Z caller=main.go:221 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: services is forbidden: User \"system:serviceaccount:default:default\" cannot list services in the namespace \"default\""
level=error ts=2018-08-05T16:08:06.424726599Z caller=main.go:221 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:default:default\" cannot list pods in the namespace \"default\""
level=error ts=2018-08-05T16:08:06.424779339Z caller=main.go:221 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:268: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:default:default\" cannot list endpoints in the namespace \"default\""
level=error ts=2018-08-05T16:08:07.426361841Z caller=main.go:221 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: pods is forbidden: User \"system:serviceaccount:default:default\" cannot list pods in the namespace \"default\""

serviceacccount:

[root@kubeletmaster kube]# cat serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus

clusterrole:

[root@kubeletmaster kube]# cat clusterrole.yaml
``` 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: prometheus
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
  resources: ["configmaps"]
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
``` 

clusterrolebinding:

root@kubeletmaster kube]# cat clusterrolebinding.yaml 
``` 
apiVersion: rbac.authorization.k8s.io/v1
kind: clusterrolebinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
``` 
 
[root@kubeletmaster kube]# cat servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi

[root@kubeletmaster kube]# cat prometheus_nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus

Kind Regards,
Joseph
