### ISSUE TITLE
Support "Preprocessing" MutatingWebhook

### ISSUE THREAD

**Issue by mlbiam** [kubernetes/kubernetes#67050]
> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

**What happened**:

When I submit a pod to be processed by a mutating webhook that will update the service account and securitycontext I'm finding that my webhook has to take much more into account then updating a single spot because the other admission plugins have already been run so I not only have to update the service account and runasuser, but also update the mounted service account.  Example, here's the incoming pod definition:

```
apiVersion: v1
kind: Pod
metadata:
  name: krbtest
  labels:
    name: krbtest
  annotations:
    com.tremolosecurity.openshift: krb5_sidecar
spec:
  containers:
    - resources:
      image: mlbiam/krbdonothing
      name: motorcycle
```
but the definition that comes is from the webhook is:
```
---
request:
  uid: fed8d290-999e-11e8-bac5-525400887c40
  userInfo:
    injectedIdentity: eyJraWQiOiJDTj1qd3Qtc2lnLCBPVT1kZXYsIE89ZGV2LCBMPWRldiwgU1Q9ZGV2LCBDPWRldi1DTj1qd3Qtc2lnLCBPVT1kZXYsIE89ZGV2LCBMPWRldiwgU1Q9ZGV2LCBDPWRldi0xNTI4Njg0NDk0MTI5IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL3VuaXNvbi1vcGEudW5pc29uLnN2Yy5jbHVzdGVyLmxvY2FsIiwiYXVkIjoiaHR0cHM6Ly9vcGEudW5pc29uLnN2YyIsImV4cCI6MTUzMzU3Njk0MywianRpIjoibko1bFlPN2RLN0ZMb3Uta1Y0RDdEZyIsImlhdCI6MTUzMzU3Njg4MywibmJmIjoxNTMzNTc2ODIzLCJub25jZSI6IjI2ZTUyOTMwLWI0NjctNDkwYy1hN2Y2LTc0YTk0MmQ5MzA0NyIsInN1YiI6ImZyZWVpcGEzQGVudDJrMTIuZG9tYWluLmNvbSIsInJvbGVzIjpbIk9wZW5TaGlmdCAtIGFkbWluaXN0cmF0b3JzLWZyZWVpcGEzLXByb2plY3QiLCJPcGVuU2hpZnQgLSBlZGl0b3ItZnJlZWlwYTMtcHJvamVjdCIsIkZyZWVJUEEgLSBhcHBsaWNhdGlvbnMtb3BlbnNoaWZ0IiwiRnJlZUlQQSAtIGFwcGxpY2F0aW9ucy1vcGVuc2hpZnQta2V5dGFicyJdLCJ1aWRudW1iZXIiOiIxNjA4MTI0NTAiLCJzYS10b2tlbiI6InJ1bi1hcy11c2VyLXRva2VuLWdidGNnIiwic2EtZG9ja2VyY2ZnIjoicnVuLWFzLXVzZXItZG9ja2VyY2ZnLWpwazZ0In0.iimMdoi_njgqLK7uPtKqs9WSd-lpxfGBbJP2u1ff1cYRKMHjmfiQ9RvI5LigTZGLWeiAcSFkIciTqvwx2UCcQKHPA4_dRanP7ch0exy8XxCDAxRRZDY4q_Wda3npYmwQPcWtxE7EtXAjNujCJYXz2J9HQxg08WQb0pitqcWHSMLEve6VdAqDjveVk2qnE9mRs2EB-jgPFW2kUDc4q-yx0Veq9oA-EfT9RC7UbmLLOMDIuAko_jjTsuAUzE9miZ0PV6sDrP_TomnGl0-_fsTiVp7odskC6wZ5aYKYuyGeEle2OOuaBHNnRXcE7QlL6y6d7dXnuMF2sDw194_K6qBr_Q
    uid: 8e804b18-7e5f-11e8-acd7-525400887c40
    extra:
      scopes.authorization.openshift.io:
      - user:full
    groups:
    - administrators-freeipa3-project
    - editor-freeipa3-project
    - system:authenticated:oauth
    - system:authenticated
    username: freeipa3@ent2k12.domain.com
  resource:
    resource: pods
    version: v1
    group: ''
  kind:
    kind: Pod
    version: v1
    group: ''
  namespace: freeipa3-project
  oldObject: 
  operation: CREATE
  object:
    metadata:
      name: krbtest
      namespace: freeipa3-project
      creationTimestamp: 
      annotations:
        com.tremolosecurity.openshift: krb5_sidecar
        openshift.io/scc: restricted
      labels:
        name: krbtest
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      serviceAccountName: default
      imagePullSecrets:
      - name: default-dockercfg-6zz7j
      volumes:
      - name: default-token-s6d2l
        secret:
          secretName: default-token-s6d2l
      containers:
      - image: mlbiam/krbdonothing
        imagePullPolicy: Always
        terminationMessagePolicy: File
        terminationMessagePath: "/dev/termination-log"
        name: motorcycle
        resources: {}
        securityContext:
          runAsUser: 1000300000
          capabilities:
            drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        volumeMounts:
        - mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
          name: default-token-s6d2l
          readOnly: true
      serviceAccount: default
      securityContext:
        seLinuxOptions:
          level: s0:c17,c14
        fsGroup: 1000300000
      restartPolicy: Always
      schedulerName: default-scheduler
      nodeSelector:
        node-role.kubernetes.io/compute: 'true'
    status: {}
apiVersion: admission.k8s.io/v1beta1
kind: AdmissionReview
```
the service accounts are set, secrets are mounted, etc so I need to not only inject the securityconectext and serviceaccount name, but update all the secret token volume mounts.

**What you expected to happen**:

It would be good to have the ability to run a "pre processing" webhook that lets me make changes to a pod definition BEFORE the standard admission plugins so that I can inherit the security processing of the standard admission plugins.   It would vastly simplify this use case (and probably others).  If I received the former (simpler) definition then I would need to make two patch updates instead of a half dozen that require knowing the name of secrets for a service account to do correctly.

I originally opened this request on openshift (https://github.com/openshift/origin/issues/20543), but was told it was a k8s design decision so i opened a feature request here. 

**How to reproduce it (as minimally and precisely as possible)**:

1.  Deploy a mutating webhook for pods
2.  Deploy a pod

**Anything else we need to know?**:

Reproduced with OpenShift Origin (okd) 3.9

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+cbc5b49", GitCommit:"cbc5b49", GitTreeState:"clean", BuildDate:"2018-05-30T14:04:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.1+a0ce1bc657", GitCommit:"a0ce1bc", GitTreeState:"clean", BuildDate:"2018-04-11T20:47:54Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
bare metal+kvm vms
- OS (e.g. from /etc/os-release):
`CentOS Linux release 7.5.1804 (Core)`
- Kernel (e.g. `uname -a`):
`Linux os.XXXXX.lan 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
origin-ansible
- Others:
Webhook is a combination of Tremolo Security Unison and Open Policy Agent
