### ISSUE TITLE
Restoring PersistentVolumeClaim with dynamic storage after it's cluster is deleted

### ISSUE THREAD

**Issue by avielb** [kubernetes/kubernetes#67138]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Currently, I have the following setup in place:
2 pods with shared volume, the volume is provided from a PersistentVolumeClaim object that provided by dynamic allocation that is backed up by a StorageClass object based on aws-efs provisioner. 
This architecture is seemed to be working well for me as I don't need to manage by myself the PersistentVolume allocation as the dynamic allocation takes care of it by itself. 

But consider the following scenario:
The entire kubernetes cluster is deleted and all I got left is the EFS. When working with static storage allocation I can apply the app's *.yaml files at the newly created kubernetes cluster and the app will have its lost storage all set up. When working with dynamic storage allocation after deploying a new cluster,  how will I be able to automatically connect the pods to the right persistent volumes?

I would like to be clear that my questing is about how a dynamic storage allocation is useful when considering all kubernetes cluster is lost and all is left is the persistent storage.  

The pods:
```
 ---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: airflow
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: airflow
   template:
     metadata:
       labels:
         app: airflow
     spec:
       containers:
       - name: airflow
         image: puckel/docker-airflow
         volumeMounts:
         - name: efs-airflow-pvc
           mountPath: "/usr/local/airflow/dags"
       volumes:
       - name: efs-airflow-pvc
         persistentVolumeClaim:
           claimName: efs-airflow-pvc
``` 
  The storage class:
```
 ---
 kind: StorageClass
 apiVersion: storage.k8s.io/v1
 metadata:
   name: aws-efs
 provisioner: example.com/aws-efs
reclaimPolicy: Retain
```

the PVC:
```
 ---
 kind: PersistentVolumeClaim
 apiVersion: v1
 metadata:
   name: efs-airflow-pvc
   namespace: airflow
   annotations:
     volume.beta.kubernetes.io/storage-class: "aws-efs"
 spec:
   accessModes:
   - ReadWriteMany
   resources:
     requests:
       storage: 50Mi
```
**What you expected to happen**:
To have some way to automatically manage the connections between the new kubernetes cluster and the already existing PVs on the EFS.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
create a cluster, deploy a pod with PVC, the PVC is dynamically managed with EFS provisioner StorageClass, delete the cluster and try to restore the connection between the newly deployed pod and the existing PV on the EFS. 
**Environment**:
- Kubernetes version - AWS AKS - latest
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
