### ISSUE TITLE
create azure disk PVC failed due to account creation failure

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes/kubernetes#67234]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
create azure disk PVC failed due to account creation failure, this bug is similar to https://github.com/kubernetes/kubernetes/issues/65845, it's also caused by azure-sdk-for-go upgrade from v1.11.0

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```
azureuser@k8s-master-17140924-0:/tmp$ kubectl describe pvc
Name:          pvc-azuredisk
Namespace:     default
StorageClass:  hdd
Status:        Bound
Volume:        pvc-a843e58f-9c48-11e8-992d-000d3a04338c
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/azure-disk
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
Events:
  Type     Reason                 Age                From                         Message
  ----     ------                 ----               ----                         -------
  Warning  ProvisioningFailed     31m                persistentvolume-controller  Failed to provision volume with StorageClass "hdd": Create Storage Account: ds10e15ed89c5811e8a0a70, error: storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="AccountPropertyIsInvalid" Message="Account property kind is invalid for the request."

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11, v1.12
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign

**Comment by andyzhangx** [comment]
This issue only happens on k8s version: 1.11.0 ~1.11.2
**workaround**:
1. create a V2 storage account with Standard_LRS or Premium_LRS (depends on `storageAccountType` in azure file storage class)
2. use azure file storage class:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: EXISTING_STORAGE_ACCOUNT
  skuName: Standard_LRS  #available values: Standard_LRS, Standard_GRS, Standard_RAGRS, (and Premium_LRS are supported from k8s v1.13.0)
```
