### ISSUE TITLE
Init-containers are restarting with no reason after completion.

### ISSUE THREAD

**Issue by theobolo** [kubernetes/kubernetes#67261]
/kind bug

Hello everyone,

I'm facing a very strange issue on AKS and Kubernetes 1.10.5, about init-containers.
I found that even after a clean completion, an init-container restarts randomly, even when the `restartPolicy` flag is set to `Never`.

I made a very simple deployment file : 

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: init-container-test
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: test-container
    spec:
      initContainers:
      - name: init-sysctl
        securityContext:
          privileged: true
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
      containers:
      - name: test-container
        image: nginx
        ports:
        - containerPort: 80
          name: http
```
When i start this deployment everything is running fine, the init-container starts the `systemctl` command and exit with 0 : 

![image](https://user-images.githubusercontent.com/7281773/43968628-098f7606-9cc8-11e8-99d4-c13f0c9d0889.png)

After few minutes, i can see that the init-container has restarted, by describing the pod : 

![image](https://user-images.githubusercontent.com/7281773/43968893-c597da00-9cc8-11e8-91e3-a99490679992.png)

More than 3 times over 44m ! 

I tried on 3 AKS clusters and it's always the same result, the init-container is restarting after few minutes without any reason. 

**What you expected to happen**:

I except that the init-container stay alive as long as the pod is alive. 

There is no limits on the Pod, no MemoryPressure or DiskPressure on the k8s worker. It's very strange the init-container should just stay at the `Completed` state but it's not and it restarts randomly.

**How to reproduce it (as minimally and precisely as possible)**:

Just `kubectl -apply -f https://raw.githubusercontent.com/theobolo/k8s-init-container-test/master/pod-with-init-container.yaml` on your cluster and wait more than 30min. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:

`AKS Cluster with 3 nodes `

- OS (e.g. from /etc/os-release):

`Ubuntu`

- Kernel (e.g. `uname -a`):

`Linux aks-agentpool-46734215-1 4.15.0-1019-azure #19~16.04.1-Ubuntu SMP Thu Jul 26 20:41:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools:

`Azure Kubernetes Service`

**@kubernetes/sig-azure-bug
@kubernetes/sig-apps-bugs
/sig apps**
