### ISSUE TITLE
Read Only persistentVolume mounts gcePersistentDisk in Read/Write mode

### ISSUE THREAD

**Issue by goodhoko** [kubernetes/kubernetes#67313]
**Is this a BUG REPORT or FEATURE REQUEST?**: bug
 /kind bug

**What happened**:
I created a gcePersistentDisk to back a persistentVolume with following manifest:
```yml
apiVersion: v1
kind: PersistentVolume
metadata:
    name: map-service-pv
spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadOnlyMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: ssd
    gcePersistentDisk:
      pdName: map-service-data
      readOnly: true
      fsType: ext4
```
Which is used in persistentVolumeClaim like so:
```yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: map-service-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: "ssd"
  resources:
    requests:
      storage: 25Gi
  volumeName: map-service-pv
```
Which is used in 2 pods in a deployment. These pods each run on different node. Each of these nodes are in a same zone as the gcePD. This should not be a problem because [gcePD allows](https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes) to be mounted to more VM instances as long as it is mounted as Read Only.

However after I apply these manifests, the gcePD gets mounted to eh first node in Read/Write mode:
![image](https://user-images.githubusercontent.com/16712262/44001796-978e5370-9e38-11e8-8ef6-c7d24261c24a.png)
(it's the map-service-data disk)

This prevents the second pod running on a different node from attaching it with following error event:
```
Warning  FailedAttachVolume     1m (x21 over 29m)  attachdetach-controller                           AttachVolume.Attach failed for volume "map-service-pv" : googleapi: Error 400: The disk resource 'projects/goout-cloud/zones/europe-west1-b/disks/map-service-data' is already being used by 'projects/goout-cloud/zones/europe-west1-b/instances/gke-testing-master-pool-1-9b8db895-vgt2'
```

Also when I manually change mode of the gcePD in the Cloud Console to Read Only, the second pod is still unable to attach the volume with this error event:
```
Warning  FailedMount            1m (x15 over 32m)  kubelet, gke-testing-master-pool-1-9b8db895-v927  Unable to mount volumes for pod "map-service-6576445d74-lrfv7_default(3b6493c8-9e17-11e8-a1d7-42010a840150)": timeout expired waiting for volumes to attach or mount for pod "default"/"map-service-6576445d74-lrfv7". list of unmounted volumes=[map-service-data]. list of unattached volumes=[map-service-data default-token-c
```

**What you expected to happen**:
I expect that with these manifests the gcePD will get mounted as Read Only to all nodes with pods using this PVC.
I also expect, that when changing manually the mode in GC Console to Read Only the yet non-attached volumes will get attached.

**How to reproduce it (as minimally and precisely as possible)**:
Create a gcePersistendDisk:
```shell
gcloud compute disks create map-service-data --size 25 --type ssd
```
Create PV, PVC and Deployment:
```yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: map-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: map-service
  template:
    metadata:
      labels:
        name: map-service
    spec:
      volumes:
      - name: map-service-data
        persistentVolumeClaim:
          claimName: map-service-pvc
      containers:
        - name: map-service
          image: IMAGE_TAG
          resources:
            requests:
              memory: 512Mi
              cpu: 10m
            limits:
              memory: 2G
              cpu: 1
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: "/data"
            name: map-service-data
            readOnly: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: map-service-pv
spec:
    capacity:
      storage: 25Gi
    accessModes:
      - ReadOnlyMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: ssd
    gcePersistentDisk:
      pdName: map-service-data
      readOnly: true
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: map-service-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: "ssd"
  resources:
    requests:
      storage: 25Gi
  volumeName: map-service-pv
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.4", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-08-04T03:47:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): 
```
BUILD_ID=10452.101.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=0e35e889986f5c894db31275ad389ea56171faec
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=66
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=66
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```
- Kernel (e.g. `uname -a`):
```
Linux gke-testing-master-pool-1-9b8db895-v927 4.14.22+ #1 SMP Wed May 30 13:49:27 PDT 2018 x86_64 Intel(R) Xeon(R) 
CPU @ 2.60GHz GenuineIntel GNU/Linux
```

**Comment by saad-ali** [comment]
In your pod template, make sure that you set `spec.volumes.persistentVolumeClaim.readOnly` to true.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: map-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: map-service
  template:
    metadata:
      labels:
        name: map-service
    spec:
      volumes:
      - name: map-service-data
        persistentVolumeClaim:
          claimName: map-service-pvc
          readonly: true         <-- This ensure the volume is attached as readonly
      containers:
```
