### ISSUE TITLE
Generate CertificateSigningRequest with expiry value for use in kubeconfig generation

### ISSUE THREAD

**Issue by marcel-dempers** [kubernetes/kubernetes#67324]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
My high level goal is to generate a kubeconfig that will expire (Without having access to the API CA cert).
I am trying to create a certificate signing request with an expiry value (hours or days). When I do this via documentation steps, i am able to generate one and then build a kubeconfig out of it, which is great.
However, the certificate is always set to expire after 1 year, no matter how I generate the CSR (openssl\cfssl) .I am not able to influence the expiry date through a ca-config. I might be misunderstanding how to do this or this could end up being a useful feature for people wanting to generate kubeconfigs with expiry on it.

**What you expected to happen**:
I am hoping there is a feature available where I can set expiry (in days or hours) on the K8 `CertificateSigningRequest` object. I  know  its possible to sign my own certs if I use the masters API cert for signing. In this case I do not have access to the master nodes, hence I cannot use the API server CA certificate as its a managed kubernetes control plane. I have full admin access tho. (Azure AKS)

**How to reproduce it (as minimally and precisely as possible)**:

See script below

```
USER_NAME=test
NAMESPACE=test
GUID=$(date +"%Y%m%d%H%M%S")
TARGET_FOLDER=/tmp/kube
mkdir -p $TARGET_FOLDER

#Using CFSSL
 cat <<EOF > ${TARGET_FOLDER}/csr-config.json
 {"CN":"${USER_NAME}","hosts":[""],"key":{"algo":"rsa","size":2048}}
 EOF

#Generate CSR
cat ${TARGET_FOLDER}/csr-config.json \
 | cfssl genkey - | cfssljson -bare ${TARGET_FOLDER}/${USER_NAME}
```

I then use API server to generate a `CertificateSigningRequest` object
```
echo "
  apiVersion: certificates.k8s.io/v1beta1
  kind: CertificateSigningRequest
  metadata:
    name: user-request-${USER_NAME}-${GUID}
  spec:
    groups:
    - system:authenticated
    request: $(cat ${TARGET_FOLDER}/${USER_NAME}.csr | base64 | tr -d '\n') 
    usages:
    - digital signature
    - key encipherment
    - client auth
  " | kubectl apply -f -
```

I approve my cert 
`kubectl certificate approve user-request-${USER_NAME}-${GUID}`

Download it
`kubectl get csr user-request-${USER_NAME}-${GUID} -o jsonpath='{.status.certificate}' | base64 -d > ${TARGET_FOLDER}/${USER_NAME}.crt`

Check its expiry
`openssl x509 -text -in /tmp/kube/test.crt`

See validity section in output always set to 1 year

```
Validity
            Not Before: Aug 13 05:12:00 2018 GMT
            Not After : Aug 13 05:12:00 2019 GMT
```
**Anything else we need to know?**:
Nope

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A
