### ISSUE TITLE
Deployment resource appear as in "apps" instead of "extensions" API group

### ISSUE THREAD

**Issue by g3rzi** [kubernetes/kubernetes#67439]
Hi,

I think there is a wrong information in the documentation in the [Kubernetes API documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#list-deployment-v1-apps) (This is only version 1.11 that I checked).  

The `deployment` resource appears under the `apps` group but when I created a Role to list deployments:  
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: sa-run-pod-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
  resourceNames: []

```
 
It didn't work, only when I used the `extensions` API group like that:  
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: sa-run-pod-role
rules:
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "list"]
  resourceNames: []
```

I need the documentation should be updated.  

@kubernetes/sig-docs-bugs

**Comment by xiaoxubeii** [comment]
Can you try:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: sa-run-pod-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
  resourceNames: []
```
I think api version `rbac.authorization.k8s.io/v1` or `rbac.authorization.k8s.io/v1beta2` can work.
