### ISSUE TITLE
pods with hostNetwork are not scheduled correctly

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#67453]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

In some specific scenario (see following yaml), pods are not scheduled properly. Instead, pods get scheduled unstoppingly, in a increasing manner.

**What you expected to happen**:

Pods are scheduled properly, without additional replicas.

**How to reproduce it (as minimally and precisely as possible)**:

1. Spin up a 10-node cluster
2. Create following yaml (change image from "pause" to "nginx" can also trigger)
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
    name: pause
    spec:
    replicas: 11
    selector:
        matchLabels:
        app: pause
    template:
        metadata:
        labels:
            app: pause
        spec:
        nodeSelector:
            beta.kubernetes.io/arch: amd64
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        affinity:
            podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                    matchExpressions:
                    - key: app
                    operator: In
                    values:
                    - pause
                topologyKey: kubernetes.io/hostname
                weight: 100
        containers:
        - name: pause
            image: k8s.gcr.io/pause
            ports:
            - containerPort: 80
            hostPort: 80
    ```
3. Everything looks fine
4. Kill all pods via `k delete po -l app=pause`
5. Pods pop up infinitely. (sometime needs several running of step 4 to reproduce)
    ```
    NAME                     READY     STATUS             RESTARTS   AGE
    pause-6dfd84c5fd-282vw   1/1       Running            0          18s
    pause-6dfd84c5fd-2fwk6   0/1       PodFitsHostPorts   0          9s
    pause-6dfd84c5fd-2ltx4   0/1       PodFitsHostPorts   0          7s
    pause-6dfd84c5fd-2pw4j   1/1       Running            0          19s
    pause-6dfd84c5fd-2xfwj   0/1       PodFitsHostPorts   0          14s
    pause-6dfd84c5fd-427wb   0/1       PodFitsHostPorts   0          2s
    pause-6dfd84c5fd-44n78   1/1       Running            0          18s
    pause-6dfd84c5fd-46cq8   1/1       Running            0          19s
    pause-6dfd84c5fd-4gbmk   0/1       PodFitsHostPorts   0          6s
    pause-6dfd84c5fd-4lt6w   0/1       PodFitsHostPorts   0          18s
    pause-6dfd84c5fd-4pgnf   0/1       PodFitsHostPorts   0          8s
    ......
    pause-6dfd84c5fd-m7ldl   0/1       PodFitsHostPorts   0          15s
    pause-6dfd84c5fd-md9hk   0/1       PodFitsHostPorts   0          6s
    pause-6dfd84c5fd-mgs4k   0/1       PodFitsHostPorts   0          12s
    pause-6dfd84c5fd-n4vkg   0/1       PodFitsHostPorts   0          5s
    pause-6dfd84c5fd-ncw6h   0/1       PodFitsHostPorts   0          11s
    pause-6dfd84c5fd-ndd29   0/1       PodFitsHostPorts   0          18s
    pause-6dfd84c5fd-pkbnh   0/1       PodFitsHostPorts   0          8s
    pause-6dfd84c5fd-psp9s   0/1       PodFitsHostPorts   0          7s
    pause-6dfd84c5fd-q5cgb   0/1       PodFitsHostPorts   0          14s
    pause-6dfd84c5fd-qhkt6   0/1       PodFitsHostPorts   0          0s
    pause-6dfd84c5fd-qn5xl   0/1       PodFitsHostPorts   0          11s
    pause-6dfd84c5fd-r2mzl   0/1       PodFitsHostPorts   0          6s
    pause-6dfd84c5fd-rx2qd   0/1       PodFitsHostPorts   0          2s
    ......
    pause-6dfd84c5fd-wn5cg   1/1       Running            0          8s
    pause-6dfd84c5fd-wn66d   0/1       PodFitsHostPorts   0          2s
    pause-6dfd84c5fd-wqw5l   0/1       PodFitsHostPorts   0          8s
    pause-6dfd84c5fd-wzx7n   0/1       PodFitsHostPorts   0          10s
    pause-6dfd84c5fd-xc9jq   0/1       Pending            0          0s
    pause-6dfd84c5fd-xd96g   0/1       PodFitsHostPorts   0          1s
    pause-6dfd84c5fd-xj4p4   0/1       PodFitsHostPorts   0          2s
    pause-6dfd84c5fd-xrml2   1/1       Running            0          19s
    pause-6dfd84c5fd-z2j9j   0/1       PodFitsHostPorts   0          10s
    pause-6dfd84c5fd-zprb9   0/1       PodFitsHostPorts   0          11s
    pause-6dfd84c5fd-zvvm5   0/1       PodFitsHostPorts   0          13s
    pause-6dfd84c5fd-zx8tw   0/1       PodFitsHostPorts   0          3s
    ```
6. But deployment status looks good
    ```
    NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
    pause     11        11        11           10          6m36s
    ```

**Anything else we need to know?**:

- This issue can be reproduced on any k8s version >= 1.10.
- Enable/Disable `PodPriority` can both trigger this issue.
- _Might_ be due to same cause of #66568.

**Environment**:
- Kubernetes version (use `kubectl version`): >= 1.10
- Cloud provider or hardware configuration: kubeadm
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Others:
