### ISSUE TITLE
duplicate container volumeMounts not validated

### ISSUE THREAD

**Issue by bradfitz** [kubernetes/kubernetes#67477]
I accidentally included a duplicate `volumeMounts:` line below, and validation did not fail. I expected this to fail:

```
apiVersion: v1
kind: Pod
metadata:
  name: bugtest
spec:
  restartPolicy: Never
  containers:
    - image: debian:stretch
      name: rbd-rw
      command: ["bash", "-c", "cat /proc/mounts | grep /mnt"]
      volumeMounts:
      - name: foo
        mountPath: /mnt/foo
      volumeMounts:
      - name: bar
        mountPath: /mnt/bar
  volumes:
    - name: foo
      emptyDir: {}
    - name: bar
      emptyDir: {}
```

But nope, no error on apply, and only one of the volumes shows up:

```
dev:~ $ kubectl apply -f test.yaml
pod/bugtest created
dev:~ $ kubectl logs bugtest
/dev/mapper/debvg-root /mnt/bar ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
```

Reproduced with client+server Kubernetes 1.11.2, and also with the kubectl client at git tip (cffa2aed0e4f3a3723d1cf977e3386dbeb1aa046):

```
dev:~ $ kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"devel +015873c153 Mon Aug 13 04:48:19 2018 +0000", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Do we just need to set the YAML package's [Decoder.SetStrict](https://godoc.org/gopkg.in/yaml.v2#Decoder.SetStrict) to true?

I see no references to SetStrict in the git repo.

Will investigate later. Filing before I forget.

/cc @lavalamp
