### ISSUE TITLE
vSphere volume class/pvc: no volume plugin matched

### ISSUE THREAD

**Issue by narkarum** [kubernetes/kubernetes#67674]
/kind bug

What happened:

When trying to deploy a storage class, with the 'Vmware Vsphere Volume' provisioner, I can't seem to add a PVC to it, it fails with the following message:

`Type Reason Age From Message

Events:

  Type     Reason              Age              From                         Message
  ----     ------              ----             ----                         -------
  Warning  ProvisioningFailed  4s (x2 over 4s)  persistentvolume-controller  no volume plugin matched
`

I've also tried to follow the following tutorial and adding it manually, which results in the same error: https://github.com/kubernetes/examples/blob/master/staging/volumes/vsphere/README.md

**Comment by narkarum** [comment]
```
kubx-kubectl devstor-cr13   describe  sc fast
Name:            fast
IsDefaultClass:  Yes
Annotations:     storageclass.beta.kubernetes.io/is-default-class=true
Provisioner:     kubernetes.io/vsphere-volume
Parameters:      datastore=vsanDatastore,diskformat=thin,fstype=ext4
Events:          <none>
```

**Comment by narkarum** [comment]
```
cat vsphere-volume-sc-fast3.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: fast
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters: 
  datastore: vsanDatastore
  diskformat: thin
  fstype: ext4

```

**Comment by narkarum** [comment]
```
 cat vsphere-volume-sc-fast3.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: fast
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters: 
  datastore: vsanDatastore
  diskformat: thin
  fstype: ext4
root@Carrier-1-Master-01:~# cat vsphere-volume-pvcsc3.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcsc003
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

```
