### ISSUE TITLE
Kubelet sets incomplete group permissions when using fsGroup

### ISSUE THREAD

**Issue by mxey** [kubernetes/kubernetes#67814]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

I am using Persistent Local Volumes. The mountpoints for it are set up with 0700 permissions. When running a pod with a user other than root, and with fsGroup to allow access to the volume, the permissions are wrong and the pod cannot use the volume. The permissions are changed from 0700 to 2760.

**What you expected to happen**:

fsGroup makes the volume usable for the group by setting the permissions to 2770.

**How to reproduce it (as minimally and precisely as possible)**:

You need a cluster with local volumes whose permissions are set to 0700.

pv-permission-bug.yaml:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-permission-bug
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

kind: Pod
apiVersion: v1
metadata:
  name: pv-permission-bug
spec:
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: pv-permission-bug
  containers:
  - name: pv-permission-bug
    image: nginx
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: test
  securityContext:
    fsGroup: 2000
```

```
$ kubectl apply  -f pv-permission-bug.yaml
$ kubectl exec -n provid-mag-pv-permission-bug pv-permission-bug -it -- stat /usr/share/nginx/html
  File: /usr/share/nginx/html
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fd03h/64771d	Inode: 2           Links: 2
Access: (2760/drwxrwS---)  Uid: (    0/    root)   Gid: ( 2000/ UNKNOWN)
Access: 2018-08-24 09:22:43.084058182 +0000
Modify: 2018-08-23 16:09:52.330157563 +0000
Change: 2018-08-24 09:22:43.084058182 +0000
 Birth: -
```

As you can see, the permissions are 2760. Since the execute bit is missing for the group, the directory cannot be used. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.2
- Cloud provider or hardware configuration: libvirt/QEMU
- OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:
