### ISSUE TITLE
Jobs with a container config error will never complete

### ISSUE THREAD

**Issue by pvanderlinden** [kubernetes/kubernetes#67828]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
A job with a config error (pod: `Warning  Failed                 22m (x8 over 24m)  kubelet, minikube  Error: container has runAsNonRoot and image will run as root`), will never complete, the job will not have any success or fail status, and will have an 'activate' forever.

**What you expected to happen**:
This should count as a failure. And take into account restartPolicy and backoffLimit.

**How to reproduce it (as minimally and precisely as possible)**:
Make a job like this:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: default
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      containers:
      - name: test
        image: busybox
        command:
          - echo
        args:
          - 'hello'
          - 'world'
      restartPolicy: Never
  backoffLimit: 0
```

**Anything else we need to know?**:
I'm trying to start a job on demand and then monitor for fail/success by monitoring the job object (with code), the script currently looks at 'completion_time' to see if it succeeded, and `conditions` to see if it failed. I also can't add a deadline (activeDeadlineSeconds), as these jobs are possibly taking a lot of time (online ML training in the first use case for us).

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.5
- Cloud provider or hardware configuration: minikube
