### ISSUE TITLE
Windows: kube-proxy errors programming a service

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#67827]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

* Set up a 2-Windows 2-Linux node cluster in Azure using latest ACS engine.
* Installed a prometheus pod and service on the linux nodes
* Noticed errors in the kubeproxy log on Windows.
* Service only works on linux nodes, not on windows.
* Other services seem to work on Windows even if their pods are on linux nodes.

Error in the kube-proxy log:
```
I0824 13:31:46.684045    4740 proxier.go:111] Endpoint resource found, (*winkernel.endpointsInfo)(0xc042b3a780)({
 ip: (string) (len=10) "10.244.1.5",
 port: (uint16) 9090,
 isLocal: (bool) false,
 macAddress: (string) (len=17) "00:11:22:33:44:55",
 hnsID: (string) (len=36) "1f9faa27-8c8b-41ac-ab95-82a54590767b",
 refCount: (uint16) 338
})
I0824 13:31:46.684045    4740 proxier.go:1010] Associated endpoints [([]hcsshim.HNSEndpoint) (len=1 cap=1) {
 (hcsshim.HNSEndpoint) {
  Id: (string) (len=36) "1f9faa27-8c8b-41ac-ab95-82a54590767b",
  Name: (string) (len=8) "Ethernet",
  VirtualNetwork: (string) (len=36) "e11838f9-bf86-4789-b5f8-c3899da0f861",
  VirtualNetworkName: (string) (len=8) "l2bridge",
  Policies: ([]json.RawMessage) (len=1 cap=4) {
   (json.RawMessage) (len=23 cap=32) {
    00000000  7b 20 22 54 79 70 65 22  20 3a 20 22 4c 32 44 72  |{ "Type" : "L2Dr|
    00000010  69 76 65 72 22 20 7d                              |iver" }|
   }
  },
  MacAddress: (string) (len=17) "00:11:22:33:44:55",
  IPAddress: (net.IP) (len=16 cap=16) 10.244.1.5,
  DNSSuffix: (string) "",
  DNSServerList: (string) "",
  GatewayAddress: (string) "",
  EnableInternalDNS: (bool) false,
  DisableICC: (bool) false,
  PrefixLength: (uint8) 0,
  IsRemoteEndpoint: (bool) true
 }
}
] for service [calico-monitoring/calico-node-prometheus:web]
E0824 13:31:46.744110    4740 proxier.go:1034] Policy creation failed: HNS failed with error : The provided policy configuration is invalid or missing parameters.
```

**What you expected to happen**:

No error, service should work on both types of node.

**How to reproduce it (as minimally and precisely as possible)**:

Dump of my service spec (I noticed that it's a NodePort type and it has a named port as target, maybe one of those is the issue?):

```
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: calico-node-prometheus
  namespace: calico-monitoring
spec:
  clusterIP: 10.0.67.66
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    nodePort: 30909
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: calico-node-prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration: ACS-engine
- OS (e.g. from /etc/os-release): Windows 1803 with August patches applied
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:
