### ISSUE TITLE
Backofflimit 0 with restartPolicy: OnFailure does not start pods in 1.10.x

### ISSUE THREAD

**Issue by jlzhao27** [kubernetes/kubernetes#67848]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

If you have a JobSpec and set `backoffLimit: 0` with `restartPolicy: OnFailure` in 1.9.x, then the job will start a pod and never restart it regardless of success of failure.

In 1.10.x, a job spec with `backoffLimit: 0` and `restartPolicy: OnFailure`, k8s does not start any pods at all. We had to set `backoffLimit: 1` in order to get the pod to run.

The wording in the docs suggest that `backoffLimit` should only take effect when the pod is finished/or failed. It shouldn't cap starting the initial pod.

**How to reproduce it (as minimally and precisely as possible)**:
Run the following job spec in 1.9.x and 1.10.x:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-timeout
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: OnFailure
```

**Anything else we need to know?**:

The docs links this existing ticket saying `backofflimit` is ineffective with `restartPolicy: OnFailure`, but the ticket talks about restarting too many times, not never starting a pod.

https://github.com/kubernetes/kubernetes/issues/54870

Given this issue was slightly different, I originally did not think it was a backoffPolicy bug.

**Environment**:
- Kubernetes version (use `kubectl version`):
Tested on 1.9.7 and 1.10.6
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from /etc/os-release):
Fedora 28
