### ISSUE TITLE
annotations not being applied to ingress and no subsequently no events

### ISSUE THREAD

**Issue by dick-twocows** [kubernetes/kubernetes#67966]
/kind bug

**What happened**:

Applied ingress with annotations and the annotations are ignored.

**What you expected to happen**:

The annotations to be applied and visible when describing the ingress.

**How to reproduce it (as minimally and precisely as possible)**:

Apply this;

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ydos-ingress
  namespace: ydos
  annotations:
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1M
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "YDOS-SESSION-EX"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "ydos/wildcard-yellowdog-tech-secret"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
spec:
  tls:
  - hosts:
    - service.yellowdog.tech
    secretName: wildcard-yellowdog-tech-secret
  rules:
  - host: service.yellowdog.tech
    http:
      paths:
      - path: /ydos
        backend:
          serviceName: ydos-svc
          servicePort: 80
```

Describe the ingress;

`$ kubectl describe ingress ydos-ingress -n ydos
Name:             ydos-ingress
Namespace:        ydos
Address:          130.61.9.241
Default backend:  default-http-backend:80 (<none>)
TLS:
  wildcard-yellowdog-tech-secret terminates service.yellowdog.tech
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  service.yellowdog.tech
                          /ydos   ydos-svc:80 (<none>)
Annotations:
Events:  <none>
`

**Anything else we need to know?**:

This is being deployed into a kubernetes ingress-nginx environment. The nginx controller is being updated but no annotations are being applied by kubernetes so affinity is not being configured in the nginx pod.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1+2.1.5.el7", GitCommit:"ea4c95b07dd46d5563e4f6851ede13157bf04266", GitTreeState:"archive", BuildDate:"2018-03-23T02:54:15Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.1-2+e49fe6296d12ea", GitCommit:"e49fe6296d12ea823430bb7bda457d1201b17277", GitTreeState:"clean", BuildDate:"2018-07-24T14:24:53Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
NAME           STATUS    ROLES     AGE       VERSION   EXTERNAL-IP    OS-IMAGE                  KERNEL-VERSION                  CONTAINER-RUNTIME
130.   Ready     node      8d        v1.11.1   130.61.33.85   Oracle Linux Server 7.5   4.1.12-124.18.5.el7uek.x86_64   docker://18.3.1
130.    Ready     node      8d        v1.11.1   130.61.74.1    Oracle Linux Server 7.5   4.1.12-124.18.5.el7uek.x86_64   docker://18.3.1
130.   Ready     node      8d        v1.11.1   130.61.95.73   Oracle Linux Server 7.5   4.1.12-124.18.5.el7uek.x86_64   docker://18.3.1

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
