### ISSUE TITLE
Undocumented postStart hook timeout limit

### ISSUE THREAD

**Issue by yelled3** [kubernetes/kubernetes#68013]
In the docs, it says
>  if the **hook takes too long to run** or hangs, the Container cannot reach a running state.
from: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution

But it doesn't specify what's the timeout limit.

From doing some code reading, I found that when running an exec command (not sure for http command) the timeout is not set at all.

this runs the `postStart` lifecycle hook:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L167-L181

and then calls the following:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/handlers.go#L58-L59

```output, err := hr.commandRunner.RunInContainer(containerID, handler.Exec.Command, 0)```
not that `0` is passed for a the timeout - which means no timeout limit.

I tested it with a long (5m) running script - and seems like there is indeed no timeout.
```yaml
lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  echo 'before' > before.txt;
                  sleep 5m;
                  echo 'after' > after.txt;
```

can someone else confirm this is correct? 
or is there another timeout limit I'm missing here?

Thanks
