### ISSUE TITLE
Network policy not properly blocking GKE metadata IP

### ISSUE THREAD

**Issue by hgascoigne** [kubernetes/kubernetes#68078]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I'm attempting to configure a network policy on GKE with "Network policy for nodes" and "Metadata concealment proxy" enabled. My goal is simple: I want to block access to the metadata endpoint at `169.254.169.254` while allowing all other egress traffic. I cannot get the network policy to block access to that IP.

**What you expected to happen**:
I would expect that setting an ip in the `except` field would block that IP while allowing all other traffic. This works fine with other IP addresses I have tried, but not for `169.254.169.254`.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: metadata-restriction-policy
  namespace: default
spec:
  podSelector: {}
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
  policyTypes:
  - Egress
```

**Anything else we need to know?**:
As a side question, do network policies only work when accessing an IP directly, but not through a domain name? In another test I was able to block an IP when accessed directly, but as soon as I used a domain name that pointed to the same IP it was allowed.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.11.1
Server Version: v1.10.6-gke.2
```
- Cloud provider or hardware configuration: GKE
