### ISSUE TITLE
NLB fails to create when ELB exists targeting same resource

### ISSUE THREAD

**Issue by xrl** [kubernetes/kubernetes#68111]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig aws

**What happened**: I created a NLB object to compare with a classic ELB but none of the NLB targets went healthy. When I describe the ELB:

```
$ k describe svc nginx-nlb
Name:                     nginx-nlb
Namespace:                nginx-ingress
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/aws-load-balancer-type=nlb
Selector:                 name=nginx-ingress-controller
Type:                     LoadBalancer
IP:                       100.69.106.162
LoadBalancer Ingress:     ae90f70edacc911e88d4b06fe9349b72-123.elb.eu-central-1.amazonaws.com
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  32150/TCP
Endpoints:                <none>
Port:                     https  443/TCP
TargetPort:               443/TCP
NodePort:                 https  31836/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     32508
Events:
  Type     Reason                      Age                From                Message
  ----     ------                      ----               ----                -------
  Warning  CreatingLoadBalancerFailed  28m                service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service nginx-ingress/nginx-nlb: Error adding tags after creating Load Balancer: "ValidationError: Only one resource can be tagged at a time\n\tstatus code: 400, request id: e9bc5d70-acc9-11e8-a6e0-dfee3d0149ec"
  Normal   EnsuringLoadBalancer        27m (x2 over 28m)  service-controller  Ensuring load balancer
  Normal   EnsuredLoadBalancer         27m                service-controller  Ensured load balancer
```

**What you expected to happen**: The NLB should have behaved just like an ELB, routing traffic to the backend pods.

**How to reproduce it (as minimally and precisely as possible)**:

Create a nginx-ingress daemonset and then expose it two ways: by ELB and NLBs:

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      serviceAccountName: nginx-ingress
      containers:
      - image: nginx/nginx-ingress:1.2.0-alpine
        name: nginx-ingress
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443 
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -default-server-tls-secret=staging/wildcard-cert
          # - -v=3 # Enables extensive logging. Useful for trooublshooting.
        volumeMounts:
        - mountPath: /var/run/secrets/mysite.com
          name: httpauth
          readOnly: true
      volumes:
      - name: httpauth
        secret:
          secretName: httpauth
```

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  selector:
    name: nginx-ingress-controller
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
```

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-nlb
  namespace: nginx-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    name: nginx-ingress-controller
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T09:56:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

My VPC:

```
$ aws ec2 describe-vpcs
{
    "Vpcs": [
        {
            "CidrBlock": "172.20.0.0/16",
            "DhcpOptionsId": "dopt-7ff51116",
            "State": "available",
            "VpcId": "vpc-89ef61e1",
            "InstanceTenancy": "default",
            "CidrBlockAssociationSet": [
                {
                    "AssociationId": "vpc-cidr-assoc-a50db4cc",
                    "CidrBlock": "172.20.0.0/16",
                    "CidrBlockState": {
                        "State": "associated"
                    }
                }
            ],
            "IsDefault": false,
            "Tags": [
                {
                    "Key": "aws:cloudformation:stack-name",
                    "Value": "SharedVPC"
                },
                {
                    "Key": "kubernetes.io/cluster/k.mysite.com",
                    "Value": "shared"
                },
                {
                    "Key": "aws:cloudformation:stack-id",
                    "Value": "arn:aws:cloudformation:eu-central-1:1234:stack/SharedVPC/5678"
                },
                {
                    "Key": "aws:cloudformation:logical-id",
                    "Value": "shared"
                },
                {
                    "Key": "Name",
                    "Value": "SharedVPC"
                }
            ]
        }
    ]
}
```

my subnets:

```
{
    "Subnets": [
        {
            "AvailabilityZone": "eu-central-1b",
            "AvailableIpAddressCount": 9,
            "CidrBlock": "172.20.1.16/28",
            "DefaultForAz": false,
            "MapPublicIpOnLaunch": false,
            "State": "available",
            "SubnetId": "subnet-b51c55cf",
            "VpcId": "vpc-89ef61e1",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": [],
            "Tags": [
                {
                    "Key": "aws:cloudformation:logical-id",
                    "Value": "PostgresEC2Subnet2b"
                },
                {
                    "Key": "aws:cloudformation:stack-id",
                    "Value": "arn:aws:cloudformation:eu-central-1:1234:stack/EncryptedPostgresDB/d0fdda80-6d9d-11e7-a29e-50a68ad4f2fe"
                },
                {
                    "Key": "aws:cloudformation:stack-name",
                    "Value": "EncryptedPostgresDB"
                }
            ]
        },
        {
            "AvailabilityZone": "eu-central-1b",
            "AvailableIpAddressCount": 8174,
            "CidrBlock": "172.20.64.0/19",
            "DefaultForAz": false,
            "MapPublicIpOnLaunch": false,
            "State": "available",
            "SubnetId": "subnet-d9a137a3",
            "VpcId": "vpc-89ef61e1",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": [],
            "Tags": [
                {
                    "Key": "KubernetesCluster",
                    "Value": "k.mysite.com"
                },
                {
                    "Key": "SubnetType",
                    "Value": "Public"
                },
                {
                    "Key": "kubernetes.io/role/elb",
                    "Value": "1"
                },
                {
                    "Key": "kubernetes.io/cluster/k.mysite.com",
                    "Value": "owned"
                },
                {
                    "Key": "Name",
                    "Value": "eu-central-1b.k.mysite.com"
                }
            ]
        },
        {
            "AvailabilityZone": "eu-central-1a",
            "AvailableIpAddressCount": 8175,
            "CidrBlock": "172.20.32.0/19",
            "DefaultForAz": false,
            "MapPublicIpOnLaunch": false,
            "State": "available",
            "SubnetId": "subnet-480c4420",
            "VpcId": "vpc-89ef61e1",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": [],
            "Tags": [
                {
                    "Key": "Name",
                    "Value": "eu-central-1a.k.mysite.com"
                },
                {
                    "Key": "kubernetes.io/role/elb",
                    "Value": "1"
                },
                {
                    "Key": "SubnetType",
                    "Value": "Public"
                },
                {
                    "Key": "KubernetesCluster",
                    "Value": "k.mysite.com"
                },
                {
                    "Key": "kubernetes.io/cluster/k.mysite.com",
                    "Value": "owned"
                }
            ]
        },
        {
            "AvailabilityZone": "eu-central-1a",
            "AvailableIpAddressCount": 9,
            "CidrBlock": "172.20.1.0/28",
            "DefaultForAz": false,
            "MapPublicIpOnLaunch": false,
            "State": "available",
            "SubnetId": "subnet-849d91ec",
            "VpcId": "vpc-89ef61e1",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": [],
            "Tags": [
                {
                    "Key": "aws:cloudformation:logical-id",
                    "Value": "PostgresEC2Subnet2a"
                },
                {
                    "Key": "aws:cloudformation:stack-name",
                    "Value": "EncryptedPostgresDB"
                },
                {
                    "Key": "aws:cloudformation:stack-id",
                    "Value": "arn:aws:cloudformation:eu-central-1:1234:stack/EncryptedPostgresDB/d0fdda80-6d9d-11e7-a29e-50a68ad4f2fe"
                }
            ]
        },
        {
            "AvailabilityZone": "eu-central-1a",
            "AvailableIpAddressCount": 10,
            "CidrBlock": "172.20.0.0/28",
            "DefaultForAz": false,
            "MapPublicIpOnLaunch": false,
            "State": "available",
            "SubnetId": "subnet-3330785b",
            "VpcId": "vpc-89ef61e1",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": [],
            "Tags": [
                {
                    "Key": "aws:cloudformation:stack-name",
                    "Value": "PostgresDB"
                },
                {
                    "Key": "aws:cloudformation:stack-id",
                    "Value": "arn:aws:cloudformation:eu-central-1:1234:stack/PostgresDB/37aa96b0-20dc-11e7-a1de-500c52a6ce9a"
                },
                {
                    "Key": "aws:cloudformation:logical-id",
                    "Value": "PostgresEC2Subnet2a"
                }
            ]
        },
        {
            "AvailabilityZone": "eu-central-1c",
            "AvailableIpAddressCount": 8174,
            "CidrBlock": "172.20.96.0/19",
            "DefaultForAz": false,
            "MapPublicIpOnLaunch": false,
            "State": "available",
            "SubnetId": "subnet-b68319fb",
            "VpcId": "vpc-89ef61e1",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": [],
            "Tags": [
                {
                    "Key": "kubernetes.io/cluster/k.mysite.com",
                    "Value": "owned"
                },
                {
                    "Key": "kubernetes.io/role/elb",
                    "Value": "1"
                },
                {
                    "Key": "Name",
                    "Value": "eu-central-1c.k.mysite.com"
                },
                {
                    "Key": "KubernetesCluster",
                    "Value": "k.mysite.com"
                },
                {
                    "Key": "SubnetType",
                    "Value": "Public"
                }
            ]
        },
        {
            "AvailabilityZone": "eu-central-1b",
            "AvailableIpAddressCount": 10,
            "CidrBlock": "172.20.0.16/28",
            "DefaultForAz": false,
            "MapPublicIpOnLaunch": false,
            "State": "available",
            "SubnetId": "subnet-d77fe9ad",
            "VpcId": "vpc-89ef61e1",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": [],
            "Tags": [
                {
                    "Key": "aws:cloudformation:logical-id",
                    "Value": "PostgresEC2Subnet2b"
                },
                {
                    "Key": "aws:cloudformation:stack-id",
                    "Value": "arn:aws:cloudformation:eu-central-1:1234:stack/PostgresDB/37aa96b0-20dc-11e7-a1de-500c52a6ce9a"
                },
                {
                    "Key": "aws:cloudformation:stack-name",
                    "Value": "PostgresDB"
                }
            ]
        }
    ]
}
```

- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Kernel (e.g. `uname -a`): `Linux ip-172-20-70-0 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux`
- Install tools: Kops 1.10
- Others:
