### ISSUE TITLE
Service annotations for AWS ELB randomly does not "take"

### ISSUE THREAD

**Issue by cjohansen** [kubernetes/kubernetes#68227]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Defined the nginx ingress controller service like so:

```
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: '...'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 'https'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'http'
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: true
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: 5
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: 'my-bucket'
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: 'ingress-elb'
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: http
```

**What you expected to happen**:

A new ELB with TLS certificate on port 443, no TLS certificate on port 80, and access logs sent to S3 bucket "my-bucket".

The load balancer is created, TLS certificate is attached as expected, no access logging is configured. Furthermore, changing the annotations and re-applying the spec has non-deterministic results. I removed the annotations regarding the logging setup, and the TLS certificate was eventually removed from my load balancer. I had to destroy it and re-create it for it to exist again.

I am also unable to confirm whether or not the annotations are actually created. Listing the service with either `kubectl get service -n ingress-nginx ingress-nginx -o json` or `kubectl describe service` shows only one annotation, `kubectl.kubernetes.io/last-applied-configuration`.

**How to reproduce it (as minimally and precisely as possible)**:

Create a service with the above annotations, observe that no logging is set up.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): OSX
- Kernel (e.g. `uname -a`): 16.7.0
- Install tools: kops
