### ISSUE TITLE
MySQL StatefulSet not kill abnormal pod when RollingUpdate

### ISSUE THREAD

**Issue by polym** [kubernetes/kubernetes#68340]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

MySQL StatefulSet not kill abnormal pod when RollingUpdate.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. don't set env MYSQL_ROOT_PASSWORD  in below yaml, and kubectl apply -f
2. as MYSQL_ROOT_PASSWORD is not set,  mysql container in pod can't start up.
3. set env MYSQL_ROOT_PASSWORD, then kubectl apply -f again

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        image: mysql:5.7
        imagePullPolicy: Always
        name: mysql-1
        ports:
        - containerPort: 3306
          name: port1
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 107374182400m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data-vol
        - mountPath: /etc/localtime
          name: tz-config
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockercfgjson
      initContainers:
      - args:
        - -c
        - rm -rf /tmp/data*/lost+found
        command:
        - sh
        image: busybox
        imagePullPolicy: Always
        name: storage-lost-found-cleaner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/data0
          name: mysql-data-vol
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
          type: ""
        name: tz-config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: mysql-data-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: ceph-rbd
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):

```
Linux k8s-test 4.10.1-1.el7.elrepo.x86_64 #1 SMP Sun Feb 26 19:47:48 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
- Others:
