### ISSUE TITLE
Pods in StatefulSets doesn't have DNS A record if service is non-headless

### ISSUE THREAD

**Issue by lystor** [kubernetes/kubernetes#68352]
/kind bug

Hello

Pods in StatefulSets doesn't have DNS A record if ClusterIP service is non-headless (see test1).

If ClusterIP service is headless pods have A records (see test2).

Kubernetes 1.10.3
```
cat << EOF > test1.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
EOF
```
```
cat << EOF > test2.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
EOF
```
```
$ kubectl create namespace test1
$ kubectl create namespace test2

$ kubectl -n test1 apply -f test1.yaml
$ kubectl -n test2 apply -f test2.yaml
```
```
$ kubectl run dnsutils --rm -it --image=tutum/dnsutils bash

# dig +short web-0.nginx.test1.svc.cluster.local
<nxdomain>

# dig +short web-0.nginx.test2.svc.cluster.local
10.1.0.145
```
```
$ kubectl -n test1 describe service nginx
Name:              nginx
Namespace:         test1
Labels:            app=nginx
Selector:          app=nginx
Type:              ClusterIP
IP:                10.99.231.26
Port:              <unset>  80/TCP
TargetPort:        80/TCP
Endpoints:         10.1.0.143:80,10.1.0.144:80,10.1.0.146:80
Session Affinity:  None

$ kubectl -n test2 describe service nginx
Name:              nginx
Namespace:         test2
Labels:            app=nginx
Selector:          app=nginx
Type:              ClusterIP
IP:                None
Port:              <unset>  80/TCP
TargetPort:        80/TCP
Endpoints:         10.1.0.145:80,10.1.0.147:80,10.1.0.148:80
Session Affinity:  None
```
Please fix the bug.

Thank you

**Environment**:
- Kubernetes version: 1.10.3
- Cloud provider: Docker for Windows 18.06.1
