### ISSUE TITLE
Pods in StatefulSets don't have DNS A record if service is NodePort

### ISSUE THREAD

**Issue by lystor** [kubernetes/kubernetes#68356]
Hello

Pods in StatefulSets don't have DNS A record if ClusterIP service is NodePort.

Kubernetes 1.10.3
```
# cat << EOF > test.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 8888
    name: http
  selector:
    app: nginx
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
EOF
```
```
$ kubectl create namespace test
$ kubectl -n test apply -f test.yaml
```
```
$ kubectl run dnsutils --rm -it --image=tutum/dnsutils bash

# dig web-0.nginx.test.svc.cluster.local
<nxdomain>

# dig nginx.test.svc.cluster.local
nginx.test.svc.cluster.local. 8 IN      A       10.98.89.75
```
```
$ kubectl -n test describe service nginx
Name:                     nginx
Namespace:                test
Labels:                   app=nginx
Selector:                 app=nginx
Type:                     NodePort
IP:                       10.98.89.75
LoadBalancer Ingress:     localhost
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  8888/TCP
Endpoints:                10.1.0.156:80,10.1.0.158:80,10.1.0.159:80
Session Affinity:         None
External Traffic Policy:  Cluster
```

Please fix the bug.
Thank you

/kind bug
/sig network
@kubernetes/sig-network
