### ISSUE TITLE
PodAntiAffinity do not support anti affinity based on groups

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#68398]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind feature

Suppose I have two AZ, and want to create 4 pods with each 2 as a group, and I want those two groups has anti-affinity policy, so that each AZ can create two pods.

But the current PodAntiAffinity can only support anti-affinity with one pod as unit, any workaround to enable this?

/cc @kevin-wangzefeng 

/sig scheduling

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by k82cn** [comment]
Similar to https://github.com/kubernetes/kubernetes/issues/40358 , but we do not support more than one pod by anti-affinity now.

**Comment by gyliu513** [comment]
Good to know, this is same requirement, let me close this one.

**Comment by Huang-Wei** [comment]
@gyliu513 are the 4 pods created by 2 deployments? If so, I think one workaround is to combinely use PodAffinity and PodAntiAffinity:

- deploy1

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pause1
  template:
    metadata:
      labels:
        app: pause1
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pause1
            topologyKey: zone
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pause2
            topologyKey: zone
      containers:
      - name: pause
        image: k8s.gcr.io/pause:2.0
```

- deploy2

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pause2
  template:
    metadata:
      labels:
        app: pause2
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pause2
            topologyKey: zone
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pause1
            topologyKey: zone
      containers:
      - name: pause
        image: k8s.gcr.io/pause:2.0
```
