### ISSUE TITLE
share out 1 pod for each node group

### ISSUE THREAD

**Issue by mcortinas** [kubernetes/kubernetes#68415]
Let me add an example in order to be clear.  

This is the sceneraio : 
- 1 k8s cluster with 100 nodes 
- 3 different node groups, we add a label with key "nodepool" with possible values one,two and three in order to do this grouping  p.e.: nodepool={one|two|three}

My deployment has 3 replicas and I like some constraint rule in order to share out 1 pod in a DIFFERENT nodepool using the label "nodepool" added in each node

Could be possible?

**Comment by Huang-Wei** [comment]
@mcortinas PodAntiAffinity would help:

```yaml
......
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: foo
                operator: Exists
            topologyKey: nodepool
......
```

You can change the `matchExpressions` based on the labels of your deployment.
