### ISSUE TITLE
Daemonset controller rapidly deleting pods

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/kubernetes#68432]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

On a 1.11.1 cluster the daemonset controller is deleting pods for a single daemonset just about immediately after creating them on a variety of hosts (approx. 5/18 hosts). This happens continually. This happens accross restarts or controller. The delete line is logged [here](https://github.com/kubernetes/kubernetes/blob/v1.11.1/pkg/controller/daemon/daemon_controller.go#L1041)
Looking at the controllerrevisions backing the daemonset, there are two controller revisions that are getting updated very frequently and their revision count is continually increasing. What happens is something like this:

## Daemonset sync loop 1
* daemonset controller considers controller revision A to match the DS and [calls it a current controller revision](https://github.com/kubernetes/kubernetes/blob/v1.11.1/pkg/controller/daemon/update.go#L109)
* daemonset controller considers controller revision B to *not* match the DS and [calls it an old controller revision](https://github.com/kubernetes/kubernetes/blob/v1.11.1/pkg/controller/daemon/update.go#L111)
* daemonset controller increments the revision of A to the revision of B plus 1, and ensures all pods have controller revision A as their controller revision, deleting those that do not.

## Daemonset sync loop 2 (order of <1s later)
* daemonset controller considers controller revision A to *not* match the DS and [calls it an old controller revision](https://github.com/kubernetes/kubernetes/blob/v1.11.1/pkg/controller/daemon/update.go#L111)
* daemonset controller considers controller revision B to match the DS and [calls it an current controller revision](https://github.com/kubernetes/kubernetes/blob/v1.11.1/pkg/controller/daemon/update.go#L109)
* daemonset controller increments the revision of B to the revision of A plus 1, and ensures all pods have controller revision B as their controller revision, deleting those that do not.

And so on and so on, the daemonset controller will forever switch which controllerrevision it thinks is the current one, continually triggering a rolling update of the pods. I verified this by [deploying a fork of the kube-controller-manager with a bunch of logging](https://github.com/ryanmcnamara/kubernetes/tree/rm/debug-ds) based off of v1.11.1

Also with that logging I was able to figure out that the reason the daemonset controller considers the daemonset equal to A one sync loop and equal to B in another sync loop is that the daemonset being obtained [here](https://github.com/ryanmcnamara/kubernetes/blob/rm/debug-ds/pkg/controller/daemon/daemon_controller.go#L1180) has a different node affinity in its pod spec than it does in the previous iteration. I verified this by printing the bytes of the daemonset [several lines later](https://github.com/ryanmcnamara/kubernetes/blob/rm/debug-ds/pkg/controller/daemon/daemon_controller.go#L1194).

In sync loop 1 the bytes are something like this (redacted):
```
{
  "metadata": {
     ...
  },
  "spec": {
    "selector": {
      ...
    },
    "template": {
      "metadata": {
        ...
      },
      "spec": {
        "affinity": {
          "nodeAffinity": {
            "requiredDuringSchedulingIgnoredDuringExecution": {
              "nodeSelectorTerms": [
                {
                  "matchExpressions": [
                    {
                      "key": "com.palantir.rubix/resource-group",
                      "operator": "In",
                      "values": [
                        "a",
                        "b",
                        "c",
                        "d",
                      ]
                    }
                  ]
                }
              ]
            }
          }
        },
      }
    },
    ...
  },
  "status": {
    ...
  }
}
```
And in sync loop 2 the bytes are something like this (redacted)
```
{
  "metadata": {
    ...
  },
  "spec": {
      ...
    },
    "template": {
      "metadata": {
        ...
      },
      "spec": {
        "affinity": {
          "nodeAffinity": {
            "requiredDuringSchedulingIgnoredDuringExecution": {
              "nodeSelectorTerms": [
                {
                  "matchExpressions": [
                    {
                      "key": "com.palantir.rubix/resource-group",
                      "operator": "In",
                      "values": [
                        "a",
                        "b",
                        "d",
                        "c"
                      ]
                    }
                  ]
                }
              ]
            }
          }
        },
      }
    },
  },
  "status": {
    ...
  }
}
```

As you can see the order of the values of the node selector have changed (a,b,c,d vs a,b,d,c). In sync loop 1, they match controllerrevision A, in sync loop 2 they match controllerrevision B

If I get the daemonset bytes myself (using kubectl, it matches the sync loop 2 bytes printed *always*)

Naturally, I thought something was inconsistently updating the daemonset, but looking through the kube-apiserver-audit logs, I found that nothing was updating the daemonset. I also looked through the logs of an authorization webhook we have configured and saw the same thing.

I don't know what to think then, it would appear that on different daemonset sync loops the daemonset is read from the DB differently

Would appreciate some advice on how to debug this further. Thank you!

**What you expected to happen**:

I expect the daemonset to be read from the DB the same if it isn't updated

**How to reproduce it (as minimally and precisely as possible)**:

No idea, I have not seen this happen on a daemonset before. I have a suspicion it has something to do with the daemonset being persisted with an unsorted node selector values

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.1
- Cloud provider or hardware configuration: aws

**Comment by Huang-Wei** [comment]
@ryanmcnamara could you check if `nodeSelectorTerms.matchExpressions.values` in your **original yaml** is ordered alphabetically? If it's not ordered, it sounds like an unknown bug.

**Comment by ryanmcnamara** [comment]
Great!

The daemonset manifest we use to create the daemonset does in fact have a values array that is *not* sorted alphabetically, so it does sound like the issue you linked could be the root cause

**Comment by ryanmcnamara** [comment]
Hey @Huang-Wei @kow3ns 
I'm still able to reproduce this on v1.11.3
I found a minimal daemonset that reproduces the issue (assuming two nodes tagged with `a: a`
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
  name: daemonset-test
  namespace: default
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      daemonset-test: daemonset-test
  template:
    metadata:
      annotations:
        a: b
      creationTimestamp: null
      labels:
        daemonset-test: daemonset-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: a
                operator: In
                values:
                - b
                - a
      containers:
      - command:
        - /bin/sh
        - -c
        - sleep 100000000
        image: busybox
        name: daemonset-test
```
can we reopen this?

**Comment by Huang-Wei** [comment]
Can you check the daemonset pod holds matchExpressions with order [b, a], or [a, b]?

If it's [b, a], looks like the fix has been effective.

If it's [a, b], try to delete and recreate the daemonset to see if it works?

**Comment by ryanmcnamara** [comment]
Confirmed it was `[a, b]`

Deleting and recreating the daemonset consistently repros, as does changing the daemonset to `[a, ab]` (which doesn't cause the controllerrevisions to be incremented) and then changing back to `[b, a]`

**Comment by Huang-Wei** [comment]
with following yaml, I can't reproduce on v1.11.3:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pause
spec:
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - wei-k8s-worker3 <== this doesn't exist
                - wei-k8s-worker1
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1
```

```console
$ k version --short
Client Version: v1.11.3
Server Version: v1.11.3
k get no
NAME                           STATUS    ROLES     AGE       VERSION
wei-k8s-master                 Ready     master    97d       v1.11.3
wei-k8s-worker1                Ready     <none>    97d       v1.11.3
wei-k8s-worker2                Ready     <none>    97d       v1.11.3
```

And the pause pod show consistent matchExpression order as original yaml:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 192.168.1.122/32
  creationTimestamp: 2018-10-15T18:52:09Z
  generateName: pause-
  labels:
    app: pause
    controller-revision-hash: "433697934"
    pod-template-generation: "1"
  name: pause-6vb87
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: pause
    uid: 6b9422b0-d0ab-11e8-9609-00163e01f37e
  resourceVersion: "11170183"
  selfLink: /api/v1/namespaces/default/pods/pause-6vb87
  uid: 6b9840ca-d0ab-11e8-9609-00163e01f37e
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - wei-k8s-worker3
            - wei-k8s-worker1
```
