### ISSUE TITLE
Port forward not working for dual ports

### ISSUE THREAD

**Issue by leeadh** [kubernetes/kubernetes#68445]
I am trying to test running websphere onto kubernetes. Currently this is the

```
docker run --name test -h test -p 9043:9043 -p 9443:9443 -d \
  ibmcom/websphere-traditional:install
```
I deployed it with my deployment.yaml and my service.yaml as shown below

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: websphere
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: websphere
    spec:
      containers:
      - name: websphere
        image: ibmcom/websphere-traditional:install
        ports:
        - containerPort: 9043
        - containerPort: 9443
        resources:
          requests: 
            memory: 500Mi
            cpu: 0.5
          limits:
            memory: 500Mi
            cpu: 0.5
        imagePullPolicy: Always
```

```

apiVersion: v1
kind: Service
metadata:
  name: websphere
  labels:
    app: websphere
spec:
  type: NodePort #Exposes the service as a node ports
  ports:
  - port: 9043
    name: db
    protocol: TCP
    targetPort: 9043
    nodePort: 30043
  - port: 9443
    name: ap
    protocol: TCP
    targetPort: 9443
    nodePort: 30443
  selector:
    app: websphere
```

I tried to do a port forward to port kubectl port-forward websphere-7874884868-ntz54 9043:9043 9443:9443 but an error E`0910 00:49:06.156200   19468 portforward.go:331] an error occurred forwarding 9043 -> 9043: error forwarding port 9043 to pod 7e184665bf11f95ee02d07d40224a52368aa6b50240f0c7faf1a335d5b87a86e, uid : exit status 1: 2018/09/09 16:49:06 socat[1668] E connect(5, AF=2 127.0.0.1:9043, 16): Connection refused`

The port forward is working for my other node js app and I am able to access my app: `kubectl port-forward mynodejsapp-67cffbd59b-clxbd 3000:3000` so im pretty sure is not the socat installation issue. 

Does anyone know what's wrong?
