### ISSUE TITLE
Is it possible to schedule the pods on the a worker node until it uses all the GPU resources?

### ISSUE THREAD

**Issue by asispatra** [kubernetes/kubernetes#68547]
@kubernetes/sig-scheduling-misc

In a kubernetes environment I have two worker node. while i am running two pods(Each pod requested for 1 GPU) it is getting scheduled on two different node by default. This is how the kubernetes default scheduler works.

Is it possible that the pods can be scheduled on the a worker node until it uses all the GPU resources?

**Comment by asispatra** [comment]
@kubernetes/sig-scheduling-misc
/sig-scheduling

**Comment by k82cn** [comment]
how about pod affinity ?

**Comment by asispatra** [comment]
Hi @k82cn ,

I am new to this. I have tried pod affinity as below, but that does not work. If you help me to correct it, would help.
```
  affinity:
    podAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
     -  topologyKey: "kubernetes.io/hostname"
```
