### ISSUE TITLE
AWS classic loadbalancer is not cleaned on apply

### ISSUE THREAD

**Issue by matti** [kubernetes/kubernetes#68605]
/kind bug

**What happened**:

Applied this in AWS:

```
kind: Service
apiVersion: v1
metadata:
  namespace: lolcats
spec:
  type: LoadBalancer
...
```

---> got a classic loadbalancer.

Changed to this

```
kind: Service
apiVersion: v1
metadata:
  namespace: lolcats
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
...
```

And after apply got an NLB, but the classic loadbalancer is still there.

**What you expected to happen**:

Not to get billed by AWS for $20/month for nothing

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): coreos
- Kernel (e.g. `uname -a`): stable
- Install tools: kontena pharos
- Others: beer
