### ISSUE TITLE
Is Azure disk zone aware? 

### ISSUE THREAD

**Issue by paphillon** [kubernetes/kubernetes#68723]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
Created Storage class, pvc for dynamic provisioning with binding mode Immediate. The volume is created as expected. However, as pod scheduled on vmss node remains in a pending state due to volume is not zone aware.

az show disk command confirmed the zones field was empty
kubectl describe pv/pvc had not zone label information 

````
cannot be attached to the VM because it is not in zone '2'."
````

Tried various settings as suggested in https://github.com/kubernetes/community/blob/master/keps/sig-azure/0018-20180711-azure-availability-zones.md#storageclass

Most of the settings like zoned, zones do not work, maybe not yet implemented. Binding mode WaitForFirstConsumer has just made the PVC bind wait forever even though a pod is scheduled. Not sure, what is supported and what is not.

**What you expected to happen**:
Disks should be provisioned as per the requested zone.

**How to reproduce it (as minimally and precisely as possible)**:
Create Storage class, pvc as per 

````
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
  name: managed-premium
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
````
````
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
````
Schedule a pod that uses the above pvc on vmss node

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Azure
- OS (e.g. from /etc/os-release):
CentOS Linux 7
- Kernel (e.g. `uname -a`):
Linux xxx.corp.yyy.com 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
/sig azure
/sig cloud-provider
