### ISSUE TITLE
Cannot PATCH via Kubernetes API

### ISSUE THREAD

**Issue by danhlee329** [kubernetes/kubernetes#68861]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
When making a PATCH request, getting error "json: cannot unmarshal object into Go value of type jsonpatch.Patch"

**What you expected to happen**:
Have successful PATCH request

**How to reproduce it (as minimally and precisely as possible)**:
> `curl --request PATCH https://{clusterHostName.com}/apis/apps/v1/namespaces/{currentNamespace}/deployments/{name} --data {data} --cacert {serviceAccountCertificate} -H "Authorization: Bearer {serviceAccountbearerToken}" -H  "Content-Type: application/json-patch+json" -H 'Accept: application/json'`

Response:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "json: cannot unmarshal object into Go value of type jsonpatch.Patch",
  "code": 500
}
```
**Anything else we need to know?**:
- Confirmed permissions check of service account as an admin via kubectl auth can-i:

``` yaml
apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: {name}
    namespace: {namespace}
  rules:
  - apiGroups:
    - apps
    - extensions
    resources:
    - deployments
    verbs:
    - get
    - patch
```
- Making separates calls above using '--request GET' and '--request POST' returns expected responses (Status Code 200 and 403, respectively)

**Environment**:
- Kubernetes version (use `kubectl version`):
> Client Version: v1.11.3
> Server Version: v1.11.2
- Cloud provider or hardware configuration:
> Azure (AKS)
- OS (e.g. from /etc/os-release):
> macOS v10.13.6
- Kernel (e.g. `uname -a`):
> Darwin Kernel Version 17.7.0
- Install tools:
- Others:

@kubernetes/sig-api-machinery-bugs
