### ISSUE TITLE
Kubernetes 1.11.2 use ingress-nginx bug?

### ISSUE THREAD

**Issue by qq12157138** [kubernetes/kubernetes#68867]
1. 
```
[root@lab1 ~]# kubectl get nodes
NAME      STATUS     ROLES     AGE       VERSION
lab1      Ready      master    6m        v1.11.2
lab2      Ready      master    3m        v1.11.2
lab3      Ready      master    1m        v1.11.2
lab4      Ready     <none>    7s        v1.11.2
```
When I created the following service, my cluster crashed.
The following four IPs correspond to my four cluster nodes.
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  externalIPs:
  - 192.168.63.131
  - 192.168.63.148
  - 192.168.63.149
  - 192.168.63.153
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: ingress-nginx
```
Finally like this....
```
[root@lab1 ingress-nginx]# kubectl get node
No resources found.
Unable to connect to the server: unexpected EOF
```

I remember that when I used kube-proxy's iptables mode, it was successful. When I switched to ipvs, I have never succeeded. I don't know what happened.
