### ISSUE TITLE
Node affinity for even spread of pods across multiple availability zones

### ISSUE THREAD

**Issue by raravena80** [kubernetes/kubernetes#68981]
/kind feature
/sig scheduling

**What happened**:

Currently, nodeAffinity allows you to select multiple av zones to schedule your pods but there's no guarantee that you will have a pod in at least one availability zone. Or if the algorithm inherently does this, it doesn't seem to be documented.

More information here:

https://stackoverflow.com/questions/52457455/multizone-kubernetes-cluster-and-affinity-how-to-distribute-application-per-zon

**What you expected to happen**:

To have NodeAffinity support spread your pods across different availability zones.

Perhaps a key like this:

```
    affinity:
      NodeAffinity:
        preferedDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-name
            operator: In
            values:
            - e2e-az1
            - e2e-az2
          spreadPodsEvently: "true" <=== HERE
```

**How to reproduce it (as minimally and precisely as possible)**:

Standard NodeAffinity case:

```
    affinity:
      NodeAffinity:
        preferedDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-name
            operator: In
            values:
            - e2e-az1
            - e2e-az2
```

In this case there are no guarantees that the scheduler will schedule pods like this (as required or prefered methods):

* 4 pods:
   * 2 pods in e2e-az1
   * 2 pods in e2e-az2

* 5 pods:
   * 3 pods in e2e-az1
   * 2 pods in e2e-az2

Because of that you could end up in situation like this:

* 4 pods
  * 3 pods in e2e-az1
  * 1 pod in e2e-az2

* 4 pods
  * 0 pods in e2e-az1
  * 4 pods in e2e-az2

or just the podAntiAffinity try described [here](https://stackoverflow.com/questions/52457455/multizone-kubernetes-cluster-and-affinity-how-to-distribute-application-per-zon)

```
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
           matchExpressions:
           - key: component
              operator: In
              values:
              - app
         topologyKey: failure-domain.beta.kubernetes.io/zone
```

Where there's a chicken an egg problem, when doing re-deploys. It works initially but it doesn't work in subsequent deployments due to the fact that pods with the same label already exist in the given availability zone.

**Anything else we need to know?**:

This could also be a feature in podAntiAffinity that allows you to schedule in different availability zones.

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration: AWS, GCP, Azure, etc.
- OS (e.g. from /etc/os-release): Any
- Kernel (e.g. `uname -a`): Any that supports k8s.
- Install tools:
- Others:

**Comment by achalshant** [comment]
Hey, I'd like to work on this. What are my next steps?

**Comment by embano1** [comment]
Please see the following issues/KEP for similar questions. It's probably not that easy to implement as day 2 (scale up/down/rolling update) also have to be considered here and scheduler is not always involved (e.g. delete some replicas during scale down) which IMHO is based on a timestamp (could be wrong, did not check the code).

https://github.com/kubernetes/kubernetes/issues/4301
https://github.com/kubernetes/kubernetes/issues/40358
https://github.com/kubernetes/kubernetes/issues/41394
https://github.com/kubernetes/community/pull/2045

**Comment by Huang-Wei** [comment]
@raravena80 as you and @embano1 mentioned, "rolling update" is the key issue here:

> Where there's a chicken an egg problem, when doing re-deploys. It works initially but it doesn't work in subsequent deployments due to the fact that pods with the same label already exist in the given availability zone.

If rolling or not is not a concern of you, maybe strategy type `recreate` is a better fit:
 
```yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
...
  strategy:
    type: Recreate
...
```

For the case that number of replicas == number of topology domains (e.g. 2 replicas in 2 zones), I'm pretty confident that `Recreate` + {nodeAffinity|podAntiAffinity} + **required**DuringSchedulingIgnoredDuringExecution would work.

But if number of replicas != number of topology domains (e.g. 4 replicas in 2 zones), we have to use {nodeAffinity|podAntiAffinity} + **preferred**DuringSchedulingIgnoredDuringExecution. In this case, I'm _not that sure_ if/how existing replicas in a topology domain weights in scheduler Prioritize phase. Maybe it ends up with 3 pods / 1 pod, or 4 pods / 1 pod or evenly. Please give a try and let me know.
