### ISSUE TITLE
activeDeadlineSeconds is Not Able to be Updated to Greater Value

### ISSUE THREAD

**Issue by colinbjohnson** [kubernetes/kubernetes#69009]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind feature

**What happened**:
When updating the `activeDeadlineSeconds` value from 3600 to 3601 the following error message was returned: `Pod "cjohnson-shell-1537822011" is invalid: spec.activeDeadlineSeconds: Invalid value: 3601: must be less than or equal to previous value`

**What you expected to happen**:
I expected the value of activeDeadlineSeconds to be updated from 3600 to 3601.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a pod with `activeDeadlineSeconds` specified:
```
apiVersion: v1
kind: Pod
metadata:
  name: shell-with-timeout
spec:
  activeDeadlineSeconds: 60
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: [ "tail", "-f", "/dev/null" ]
  restartPolicy: Never
```
2. Run this pod: `kubectl apply -f pod.yaml`
3. Modify this pod specification to increase the `activeDeadlineSeconds` value:
```
apiVersion: v1
kind: Pod
metadata:
  name: shell-with-timeout
spec:
  activeDeadlineSeconds: 90
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: [ "tail", "-f", "/dev/null" ]
  restartPolicy: Never
```
4. Apply this update: `kubectl apply -f pod.yaml`
5. The return of `kubectl apply -f pod.yaml` is `The Pod "shell-with-timeout" is invalid: spec.activeDeadlineSeconds: Invalid value: 90: must be less than or equal to previous value`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`): `Linux minikube 4.15.0 #1 SMP Mon Jul 16 20:23:29 UTC 2018 x86_64 GNU/Linux`
- Install tools: NA
- Others: NA
