### ISSUE TITLE
Bug: Variables coming from Config/Secret aren't expanded

### ISSUE THREAD

**Issue by glerchundi** [kubernetes/kubernetes#69113]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Tried to use the variable expansion feature by using an environment in a `ConfigMap` by using  `envFrom` thing.

**What you expected to happen**:

Expand variable.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a `Secret` with a data key `DB_PASSWORD: xxxx`
2. Create a `ConfigMap` with a data key `DB_URL: postgres://user:$(DB_PASSWORD)`
3. Create a pod with an `envFrom` with both the `Secret` and the `ConfigMap`

You will see that `DB_URL` is not expanded.

**Anything else we need to know?**:

This is working if I use `env` instead of `envFrom`:

```
[...]
              env:
                - name: DATABASE_URL
                  value: postgres://hydra:$(DB_PASSWORD)@cockroachdb-public.database-system.svc.cluster.local:26257/hydra?sslmode=require
              envFrom:
                - configMapRef:
                  name: myconfigmap
[...]
```

**Environment**:

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.1", GitCommit:"7221ffe8776f399448d61b4dc9edb5c69232aece", GitTreeState:"clean", BuildDate:"2018-08-29T23:11:12Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

GKE
