### ISSUE TITLE
k8s 1.11.3 sysctl can't work for deployment

### ISSUE THREAD

**Issue by slpcat** [kubernetes/kubernetes#69213]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug
/sig node

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-web
  namespace: default
  labels:
    app: example-web
..........
        securityContext:
          capabilities: {}
          privileged: false
          sysctls:
          - name: kernel.msgmax
            value: "65536"
          - name: net.ipv4.tcp_syncookies
            value: "0"
          - name: net.ipv4.ip_local_port_range
            value: "1024 65535"
          - name: net.core.somaxconn
            value: "65535"

kubectl create --dry-run -f example-deploy2.yml
error: error validating "example-deploy2.yml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "sysctls" in io.k8s.api.core.v1.SecurityContext; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by dims** [comment]
@slpcat specifying it with Pod(s) work fine?

**Comment by dims** [comment]
Also, please share the full yaml file

**Comment by slpcat** [comment]
yes, it works with POD
cat pod.yml 
apiVersion: v1
kind: Pod
metadata:
  name: sysctl-example
spec:
  containers:
    - image: tomcat
      name: tomcat
  securityContext:
    sysctls:
      - name: net.ipv4.tcp_syncookies
        value: "0"
      - name: net.ipv4.ip_local_port_range
        value: "1024 65535"
      - name: net.core.somaxconn
        value: "65535"

and in pod:
root@sysctl-example:/usr/local/tomcat# sysctl -a|grep maxconn
net.core.somaxconn = 65535

but deployment can't work

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-web
  namespace: default
  labels:
    app: example-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-web
  template:
    metadata:
      labels:
        app: example-web
    spec:
      containers:
      - name: example-web
        image: tomcat
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 2048Mi
        securityContext:
          capabilities: {}
          privileged: false
          sysctls:
          - name: net.ipv4.tcp_syncookies
            value: "0"
          - name: net.ipv4.ip_local_port_range
            value: "1024 65535"
          - name: net.core.somaxconn
            value: "65535"
        env:
          - name: PROFILE
            value: "test"
        ports:
          - name: http
            containerPort: 8080

**Comment by WanLinghao** [comment]
@slpcat I have test your example in v1.13.0-alpha and no error occurs.

**Comment by slpcat** [comment]
> @slpcat I have test your example in v1.13.0-alpha and no error occurs.

in my test 1.11.3 and 1.12.0 can‘t work， I don’t have v1.13.0-alpha

**Comment by slpcat** [comment]
it can work now , this is the yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-web
  namespace: default
  labels:
    app: example-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-web
  template:
    metadata:
      labels:
        app: example-web
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.tcp_syncookies
          value: "0"
        - name: net.ipv4.ip_local_port_range
          value: "1024 65535"
        - name: net.core.somaxconn
          value: "65535"
      containers:
      - name: example-web
        image: tomcat
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 2048Mi
        env:
          - name: PROFILE
            value: "test"
        ports:
          - name: http
            containerPort: 8080

**Comment by zzvara** [comment]
It does not work for me.

```
spec:
      securityContext:
        sysctls:
        - name: net.ipv4.ip_forward
          value: "1"
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/etc/openvpn/setup/configure.sh"]
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: openvpn
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
          privileged: true
        resources:
          requests:
```

I have to use privileged and go in manually to change it. `kubelet.env` contains the allowance for this unsafe `sysctl` namaspace. What else has to be done?

**Comment by grealish** [comment]
So I've hit this issue recently and it's not solved, please reopen the issue as it's blocking allot of people can costing allot of money on a client. 
Does anyone form the CNCF have any advise on esulcating this issue?

**Comment by jeffdesc** [comment]
Any update here? If I set the sysctls value it's still not working:
```
apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test
  spec:
    replicas: 1
    template:
      spec:
        securityContext:
          sysctls:
            - name: net.ipv4.ip_forward
              value: "1"
```

Of course my kubelet allows `net.ipv4.ip_forward` and the PSP is configured for this.

However yet ip_forward is still 0:
```
user@test-d90fdsfd:/$ cat /proc/sys/net/ipv4/ip_forward
0
```

What's going wrong here?
