### ISSUE TITLE
Support maxUnavailable in RollingUpdate for StatefulSet

### ISSUE THREAD

**Issue by ObviousDWest** [kubernetes/kubernetes#69307]
/kind feature
@kubernetes/sig-cluster-lifecycle-feature-requests

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", Goion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", Goion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
AWS, running a KOPS-installed cluster, with mostly defaults.

I'd like to do something like the following...
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: event-router
spec:
  selector:
    matchLabels:
      app: event-router # has to match .spec.template.metadata.labels
  serviceName: "event-router"
  replicas: 20
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  template:
...
```
This is for a springboot webservice, that has local persistence (Artemis) to manage long-running jobs, thus the need for a statefulset (and persistent volumes -- not shown). When updating the image, RollingUpdate takes down exactly one pod, then brings it back up with the new version. I'd like to be able to control how many, or what percentage of instances are being restarted at a time. Perhaps with something like maxUnavailable, which works for a Deployment. Shutdown times are lengthy (e.g. 30s) because we use keep-alive and corresponding server.connection.timeout (e.g. 15s) that closes idle connections enough before the shutdown time that we avoid late requests that we'd have to kill in flight. And of course startup is not instantaneous either. We also use connection:close in response headers when the ContextClosedEvent occurs and we make the app un-Ready. This all makes for nice clean shutdowns, as clients will then open a new connection, and the load balancer will direct them to a Ready instance. All this to explain that it can take > 1 minute to cycle each instance. Its no fun waiting 20 minutes to cycle through all those replicas.

So it would be very nice having some kind of control of how many or what fraction of the instances are being worked on simultaneously during an update. I'm aware of Partition, but that is pretty "manual", compared to maxUnavailable. I don't think maxSurge makes sense for StatefulSet, since not all "named" instances would come back, nor do you want two instances with the same "name" simultaneously, due to assumptions about sharing resources. But I think it would be fine to have N instances shutting down and restarting simultaneously, instead of the current assumption of 1.
