### ISSUE TITLE
Windows: Service does not work if targetPort is string

### ISSUE THREAD

**Issue by KnicKnic** [kubernetes/kubernetes#69336]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Tried to create a service using targetPort as a string referencing the name of the pod port. Traffic was not routed to pod.

**What you expected to happen**:
Service to route traffic to pod

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: kube-system
  labels:
    k8s-app: kibana-logging
    kubernetes.io/name: "Kibana"
spec:
  type: NodePort
  ports:
  - name: kibana-outside
    port: 5601
    protocol: TCP
    targetPort: ui
    nodePort: 30010
  selector:
    k8s-app: kibana-logging
```
See line targetPort

**Anything else we need to know?**:
Link that describes how this feature is supposed to work https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T16:55:41Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
WindowsBuildLabEx                                       : 18249.1000.amd64fre.rs_prerelease.180925-1413
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

@daschott
@dineshgovindasamy 
@kubernetes/sig-windows
