### ISSUE TITLE
Using HPA with burstable services

### ISSUE THREAD

**Issue by weeco** [kubernetes/kubernetes#69418]
**Is this a BUG REPORT or FEATURE REQUEST?**:

kind feature

**What happened**:

I am using burstable services with values like these:

```yml
resources:
    requests:
        cpu: 100m
        memory: 200Mi
    limits:
        cpu: 1000m
        memory: 500Mi
```

I'd like to use a Horizontal Pod Autoscaler with percentaged CPU target values based on the resoruce **limits** rather than resource requests.
