### ISSUE TITLE
Can Not Create an Empty Ingress

### ISSUE THREAD

**Issue by dtaniwaki** [kubernetes/kubernetes#69422]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature request.

/kind feature

**What happened**:

I can't create an ingress without service and rules.

**What you expected to happen**:

I want to create an empty ingress so I can dynamically add and remove rules by json patch by requests to my application.

**How to reproduce it (as minimally and precisely as possible)**:

Create an empty ingress.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"9e4010d067ee4d799330980e62830b06a07296bd", GitTreeState:"clean", BuildDate:"2018-04-26T04:07:23Z", GoVersion:"go1.10.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

N/A

- OS (e.g. from /etc/os-release):

N/A

- Kernel (e.g. `uname -a`):

N/A

- Install tools:

N/A

- Others:

N/A
