### ISSUE TITLE
Add an autoscaling step before cool off number for replicas in an hpa

### ISSUE THREAD

**Issue by raravena80** [kubernetes/kubernetes#69428]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig autoscaling

**What happened**:

Would like to have an autoscaling step for replicas in an HPA. So basically you define an HPA like this:

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
```
and would like to have a `stepReplicas` option to say scale 2 at a time before cool off.

Kubernetes 1.12 removed the need for the `--horizontal-pod-autoscaler-upscale-delay` in the kube-controller-manager but users may still want to configure a step.

**What you expected to happen**:

Would like to have something like this:

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  stepReplicas: 2 <== here
  targetCPUUtilizationPercentage: 50
```

**How to reproduce it (as minimally and precisely as possible)**:

Create an HPA

**Anything else we need to know?**:

More background [here](https://stackoverflow.com/questions/52646462/horizontalpodautoscaler-multiple-replica-upscale)

**Environment**:
- Kubernetes version (use `kubectl version`): All
- Cloud provider or hardware configuration: All
- OS (e.g. from /etc/os-release): Any
- Kernel (e.g. `uname -a`): All
- Install tools:
- Others:
