### ISSUE TITLE
`kubectl create role` creates deployment with apiGroups as `extensions`

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kubernetes#69488]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

```
kubectl create role foobar --verb="*" --resource=deployment --dry-run -o yaml
```

This command creates `deployment` with old `apiGroups`, `extensions`.

**What you expected to happen**:

This should have created new `apiGroups`, `apps`.

**How to reproduce it (as minimally and precisely as possible)**:

When using the following imperative command:

```yaml
$ kubectl create role foobar --verb="*" --resource=deployment --dry-run -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: foobar
rules:
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - '*'
```

The `apiGroups` auto created for `deployment` is `extensions`, which rather should be `apps`. This is causing problem with permissions later on.

**Problem due to wrong version**:

Here we are creating a `namespace` called `examplefoobar` with `ServiceAccount` `fake-user`, then we create a `Role` `deppy` which has all permissions on resource `deployment`. And then we bind it to the `ServiceAccount` we created before.

```bash
kubectl create namespace examplefoobar
kubectl create serviceaccount -n examplefoobar fake-user

alias kubectl-user='kubectl --as=system:serviceaccount:examplefoobar:fake-user -n examplefoobar'
alias kubectl-admin='kubectl -n examplefoobar'

kubectl-admin create role deppy --verb="*" --resource=deployment
kubectl-admin create rolebinding fake-user-deppy --role=deppy --serviceaccount=examplefoobar:fake-user
```

Now the above steps should allow us to create a deployment, without any problems, but following command fails.

```console
$ kubectl-user run web --image nginx
Error from server (Forbidden): deployments.apps is forbidden: User "system:serviceaccount:examplefoobar:fake-user" cannot create deployments.apps in the namespace "examplefoobar"
```

This failed because the `deployment` generated by imperative command `kubectl run ...` generated `deployment` with `apiVersion` `apps/v1beta1`. While the `Role` had permissions on `apiGroups` `extensions`.

**Environment**:

- Kubernetes version:

```yaml
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-08-07T23:17:28Z
  compiler: gc
  gitCommit: bb9ffb1654d4a729bb4cec18ff088eacc153c239
  gitTreeState: clean
  gitVersion: v1.11.2
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-09-09T17:53:03Z
  compiler: gc
  gitCommit: a4529464e4629c21224b3d52edfe0ea91b072862
  gitTreeState: clean
  gitVersion: v1.11.3
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
```

- Install tools:

```bash
$ minikube version
minikube version: v0.29.0
```

- minikube start command

```bash
minikube start \
--kubernetes-version v1.11.3 \
--cpus 3 --memory 3000  \
--extra-config=apiserver.authorization-mode=RBAC \
--extra-config=apiserver.enable-admission-plugins=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota \
--v 10
```
