### ISSUE TITLE
nodeAffinity for the volumes should be mutable

### ISSUE THREAD

**Issue by kvaps** [kubernetes/kubernetes#69528]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature
/sig storage

**What happened**:

I use `nodeAffinity` for describe nodes where my volume is connected to.

After long time I may want to reassign this volume to another nodes.
There is no way for change `nodeAffinity` for the existing persistentVolume after it is already created.

```
kubectl apply -f /tmp/pv-00001-volume.yaml
The PersistentVolume "pv-00001" is invalid: nodeAffinity: Invalid value: core.VolumeNodeAffinity{Required:(*core.NodeSelector)(0xc439e294a0)}: field is immutable
```

**What you expected to happen**:
Updated `VolumeNodeAffinity` for the PersistentVolume

**How to reproduce it (as minimally and precisely as possible)**:
Create volume with:
```
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["node1", "node2", "node3", "node4", "node5"]
```
Try to update targeted hostnames for the volume.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version **v1.12.0**
- Cloud provider or hardware configuration: **baremetal**
