### ISSUE TITLE
Service.Spec.ExternalIPs should not allow duplication

### ISSUE THREAD

**Issue by squeed** [kubernetes/kubernetes#69599]
/kind feature

**What happened**: Accidentally created two distinct services with the same `externalip:port` combination. This creates a race where one of the services, on a per-node basis, becomes unavailable.

**What you expected to happen**: An error from the service validation, same as trying to allocate a duplicate `clusterIP`

**How to reproduce it (as minimally and precisely as possible)**: Create two services with a duplicate port and service ip:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  externalIPs: ["172.17.0.1"]
  ports:
    - name: web
      port: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
spec:
  type: ClusterIP
  externalIPs: ["172.17.0.1"]
  ports:
    - name: web
      port: 80
  selector:
    app: nginx
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.1
