### ISSUE TITLE
ClusterRole AggregationRule circular reference bug

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#69652]
/kind bug

For aggregation clusterrole, in some cases, circular dependency could exist between them, which may cause wired behaviours.
For example, if  we create clusterroles as follow:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agg1 
  labels:
    rbac.example.com/point: "point1"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.example.com/point: "point2"
rules: [] 

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agg2 
  labels:
    rbac.example.com/point: "point2"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.example.com/point: "point3"
rules: [] 

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agg3
  labels:
    rbac.example.com/point: "point3"
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.example.com/point: "point1"
rules: [] 
```

Then we create some non-aggregation clusterrole:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: child1 
  labels:
    rbac.example.com/point: "point1"
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
```

All three aggregation clusterroles would look like:
```

kubectl describe clusterrole agg1
Name:         agg1
Labels:       rbac.example.com/point=point1
Annotations:  <none>
PolicyRule:
  Resources  Non-Resource URLs  Resource Names  Verbs
  ---------  -----------------  --------------  -----
  endpoints  []                 []              [get list watch]
  pods       []                 []              [get list watch]
  services   []                 []              [get list watch]
```

Then we delete clusterrole child1, all three agg-clusterroles would keep unchanged with the rules from child1. However, the aggregation clusterrole is designed to aggregate rules from other clusterrole,  I think it should not keep the rules after the child1 been deleted.
This is just a example which shows circular dependency aggregation clusterroles would cause some wired behaviours. I think it  may cause some other bugs or potential security risk. So we need to avoid the circular dependency between agg-clusterroles.
