### ISSUE TITLE
PodPreset does not apply to Job pods

### ISSUE THREAD

**Issue by mitar** [kubernetes/kubernetes#69721]
> /kind bug

**What happened**:

I tried to use `PodPreset` to configure a Job pod.

**What you expected to happen**:

A volume configured in `PodPreset` would be available to the Job pod.

**How to reproduce it (as minimally and precisely as possible)**:

I tried:

```yml
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: tests-configuration
spec:
  selector:
    matchLabels:
      role: tests
  volumes:
  - name: test-results
    hostPath:
      path: /tmp/ci/results
      type: Directory
```

And:

```yml
apiVersion: batch/v1
kind: Job
metadata:
  name: simple-tests
spec:
  template:
    metadata:
      labels:
        role: tests
    spec:
      restartPolicy: Never
      containers:
      - name: tests
        image: tests:latest
        imagePullPolicy: Always
        command: ["npm", "run", "test-ci"]
        volumeMounts:
        - name: test-results
          mountPath: /tests/cypress/results
          readOnly: false
  backoffLimit: 0
```

But it failed with and error that `test-results` volume is not available. But it is defined in the preset.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.3
- Cloud provider or hardware configuration: custom server
- OS (e.g. from /etc/os-release): Ubuntu 17.10
- Kernel (e.g. `uname -a`): 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
