### ISSUE TITLE
Can we remove check for container waiting state to determine volume unmounting?

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#69831]
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
Volume manager calls [isPodTerminated](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/util/util.go#L873) to check if we should unmount a volume.  In it, it's checking if the Pod deletion timestamp is set and if all the containers are in terminated or waiting state.

I don't think we should actually check for waiting state because it indicates that the container is trying to be started.  This could manifest as a race condition where we end up unmounting a volume while the container is being started up for a deleted pod.

This check was added as part of https://github.com/kubernetes/kubernetes/pull/41456.  It took the `notRunning` util function from pod status manager and made a copy of it in the volume manager.  Checking for waiting state may make sense for pod status manager, but not necessarily for how volume manager uses it.

**What you expected to happen**:
We should only unmount the volume if we are sure there's no chance of the container running.

**Comment by msau42** [comment]
@kubernetes/sig-node-bugs 
cc @dashpole @yujuhong

**Comment by mjaow** [comment]
Yeah, we should not check `status.State.Waiting == nil ` in notRunning method

**Comment by msau42** [comment]
@Random-Liu will help check the kubelet state machine to see if it's possible for a container to leave terminated state even if the pod deletion timestamp is set.

In the meantime, there are [other volume controllers](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes/kubernetes%24+IsPodTerminated) that are using this check. I will evaluate if those controllers may have issues too.

**Comment by saad-ali** [comment]
> @Random-Liu will help check the kubelet state machine to see if it's possible for a container to leave terminated state even if the pod deletion timestamp is set.

I have no objection to removing the check for waiting state `isPodTerminated`. It's a safe change in my head, because at worst it will slow down unmount. The only concern would be if a container is stuck forever in waiting state would that prevent unmount? And it sounds like @Random-Liu will double check that.

**Comment by msau42** [comment]
When @Random-Liu investigated previously, he said removing the check could cause other races and result in unmount never happening.

**Comment by msau42** [comment]
Fixing this may require adding a new state to the container

**Comment by gaocegege** [comment]
Is there any progress here? Still have the problem.

**Comment by jingxu97** [comment]
cc @Jiawei0227

**Comment by Jiawei0227** [comment]
> I don't think we should actually check for waiting state because it indicates that the container is trying to be started. This could manifest as a race condition where we end up unmounting a volume while the container is being started up for a deleted pod.

Exactly what one of our customer is facing. It can be easily reproduced by the following manifest
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-timeout
  namespace: job-deadline
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 1
  template:
    spec:
      containers:
      - name: pi
        image: ubuntu
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        volumeMounts:
        - mountPath: /tmp/dummy-secret
          name: test-secret
      volumes:
      - name: test-secret
        secret:
          secretName: test-secret
      restartPolicy: Never
---
apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  name: test-secret
type: Opaque
```
The pod is still pulling image and the job exceeds deadline so it deleted the pod. While the startContainer goroutine has already try to start the container.

It will lead to the following event for the job pod. Because by the time image download finish, the pod has already being deleted and the resources has been released(volume being unmounted)
```
Message:             MountVolume.SetUp failed for volume "test-secret" : secret "test-secret" not foun
```
