### ISSUE TITLE
Environment variable is not getting inside container code

### ISSUE THREAD

**Issue by splnanthakumar** [kubernetes/kubernetes#69934]
> /kind bug
> /sig scalability

i have deployment.yaml file which as below

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels: {appid: 1234, groupid: default, app: signup,
    version: 1.1.0-29}
  name: signup-uwsgi-deployment
  namespace: signup
spec:
  replicas: 1
  selector:
    matchLabels: {app: signup}
  template:
    metadata:
      labels: {app: signup, version: 1.1.0-29}
    spec:
      containers:
      - args: [signup]
        image: ---------
        imagePullPolicy: IfNotPresent
        name: signup
        ports:
        - {containerPort: 1000}
        resources:
          limits: {memory: 750Mi}
          requests: {memory: 750Mi}
        env:
        - name: APP_CONTEXT
          value: "platform_context"
      hostAliases:
      - hostnames: [foo.local, bar.local]
        ip: 127.0.0.1
      - hostnames: [host]
        ip: **.**.**.**
      imagePullSecrets:
      - {name: XXX.io}
```

i have deployed this (kubectl apply -f deployment.yaml). and i am using circus to manage process. 
after entering into the container i am able to see the env variable .

```
core@host*** ~ $ kubectl exec -it signup-uwsgi-deployment-66d8db6597-4bx6n -n signup bash
root@signup-uwsgi-deployment-66d8db6597-4bx6n:/# printenv | sort
APP_CONTEXT=platform_context
```

inside container i have python web application . i have tried to get the same environmental variable but it is not getting.

`app_context = os.environ.get('APP_CONTEXT')`

the above code gives me "none" value.

please find the circus file as below,
```
[watcher:signup]
autostart = True
cmd = uwsgi
args = -H ENV --yaml uwsgi.yml:signup
working_dir = /opt/my_dir/apps/signup
hooks.before_start = ******

[env:orders-signup]
PYTHON_EGG_CACHE = /tmp
PATH =  /opt/my_dir/apps/signup/ENV/bin:$PATH
PYTHONPATH =  /opt/my_dir/apps/lib:/opt/my_dir/apps/signup:$PYTHONPATH
```

please find the process info of container;
```
root@signup-uwsgi-deployment-66d8db6597-4bx6n:/etc# ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ssl    0:00 /usr/bin/python /usr/local/bin/circusd /etc/circus/circusd.ini
  112 ?        Ss     0:00 bash
  138 ?        Ss     0:02 uwsgi -H ENV --yaml uwsgi.yml:signup
  152 ?        S      0:00 uwsgi -H ENV --yaml uwsgi.yml signup
  154 ?        R+     0:00 ps ax
```

**Anything else we need to know?**:   
1). why it is showing after getting into the container?
2) How do i get the same env variable via python code. 

**Environment**:
- Kubernetes version:
 Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"-------", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3+coreos.0", GitCommit:"------", GitTreeState:"clean", BuildDate:"2018-05-21T17:27:17Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:  AWS
- OS (e.g. from /etc/os-release):
- Kernel . :  Linux signup-uwsgi-deployment-66d8db6597-4bx6n 4.9.24-coreos #1 SMP Tue May 30 23:12:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:  - 
- Others:  -
