### ISSUE TITLE
CSI plugin_watcher does not report missing socket, gives opaque error message

### ISSUE THREAD

**Issue by mattsmithdatera** [kubernetes/kubernetes#69992]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/sig storage
> /kind feature

**What happened**:
I received this error when starting my CSI driver without correctly setting up the socket with kubelet
```
I1018 15:45:18.043702       1 node_register.go:63] CSI driver node ID: "tlx200"
I1018 15:45:18.043797       1 node_register.go:86] Starting Registration Server at: /registration/io.daterainc.csi.dsp-reg.sock
I1018 15:45:18.043924       1 node_register.go:93] Registration Server started at: /registration/io.daterainc.csi.dsp-reg.sock
I1018 15:45:18.044654       1 main.go:111] Received GetInfo call: &InfoRequest{}
I1018 15:45:18.051561       1 main.go:121] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:plugin registration failed with err: error updating CSI node info in the cluster: error adding CSI driver node info: driverNodeID must not be empty,}
E1018 15:45:18.051653       1 main.go:123] Registration process failed with error: plugin registration failed with err: error updating CSI node info in the cluster: error adding CSI driver node info: driverNodeID must not be empty, restarting registration container.
```
**What you expected to happen**:
I expected the error to tell me that the socket was not found.  Instead it tells me that GetNodeInfo's NodeId attribute is empty.  I see in the logs that GetNodeId is called just fine.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ kubectl -f create my-plugin.yaml
```
The yaml file is shown below.  This yaml will only function with a Datera storage backend available, so the CSI driver should be switched out for a hostpath driver.  The driver itself doesn't matter for reproduction.
```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-node
  template:
    metadata:
      labels:
        app: csi-node
    spec:
      serviceAccount: csi-node
      hostNetwork: true
      containers:
        - name: driver-registrar
          image: quay.io/k8scsi/driver-registrar:v0.4.1
          args:
            - "--v=5"
            - "--csi-address=$(DAT_SOCKET)"
            - "--kubelet-registration-path=$(REG_SOCKET)"
          env:
            - name: DAT_SOCKET
              #value: unix:///var/lib/csi/io.daterainc.csi.dsp/csi.sock
              value: /csi/csi.sock
            - name: REG_SOCKET
              value: /var/lib/kubelet/plugins/io.daterainc.csi.dsp/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: dat-csi-plugin-node
          image: dateraiodev/dat-csi-plugin:latest
          env:
            - name: DAT_TYPE
              value: nodeident
            - name: DAT_SOCKET
              value: unix:///csi/csi.sock
            - name: DAT_MGMT
              value: 172.19.1.41
            - name: DAT_USER
              valueFrom:
                  secretKeyRef:
                      name: datera-secret
                      key: username
            - name: DAT_PASS
              valueFrom:
                  secretKeyRef:
                      name: datera-secret
                      key: password
            - name: DAT_TENANT
              value: /root
            - name: DAT_API
              value: "2.2"
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: mounts
              mountPath: /mnt
            - name: etc-iscsi
              mountPath: /etc/iscsi
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: mounts
          hostPath:
            path: /mnt
        - name: etc-iscsi
          hostPath:
            path: /etc/iscsi
        - name: devices
          hostPath:
            path: /dev
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins/

```
The main reproduction key is ensuring that volumes.socket-dir is not a valid location for kubelet.
Then check the logs for the driver-registrar container

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Minikube bare-metal
- OS (e.g. from /etc/os-release):
Ubuntu 16-04
- Kernel (e.g. `uname -a`):
```
Linux tlx200 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
