### ISSUE TITLE
data lost after update on CRD resource

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes/kubernetes#70069]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
We have a CRD resource named ClusterIngress in knative, which is quite similar to Ingress in k8s:
```
type ClusterIngress struct {
        ......
	Status IngressStatus `json:"status,omitempty"`
}
```

```
type IngressStatus struct {
	......
	LoadBalancer *LoadBalancerStatus `json:"loadBalancer,omitempty"`
}
```

```
type LoadBalancerStatus struct {
	Ingress []LoadBalancerIngressStatus `json:"ingress,omitempty"`
}

```

```
type LoadBalancerIngressStatus struct {
	......
	DomainInternal string `json:"hostname,omitempty"`
}

```

During an update, I specify an `Ingress` item in the `LoadBalancer`, whose `DomainInternal` field is specified. After update, there is still an item in the `Ingress` array, but value of `DomainInternal` got lost. And no abnormal in other fields of the resource. Here is related log info:
```
"---------------loadbalancer before update: &{[{  knative-ingressgateway.istio-system.svc.cluster.local}]}"
"---------------loadbalancer after update: &{[{  }]}"
```

**What you expected to happen**:
The resource got updated as expected.

**Anything else we need to know?**:

The cluster is set up with latest code of master branch.

/sig api-machinery
/assign @nikhita @sttts

**Comment by sttts** [comment]
Can you produce a CRD yaml and an example CR to demonstrate the issue?

**Comment by lichuqiang** [comment]
Sorry I didn't describe the scenario clearly.
When updating the resource with kubectl manually (i.e. with the patch method), it behaviors well.
And we met the issue when updating resources in controller code, with the `Update` interface of generated kube client (c.ServingClientSet.NetworkingV1alpha1().ClusterIngresses().Update(existing)).

input crd looks like this:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusteringresses.networking.internal.knative.dev
spec:
  group: networking.internal.knative.dev
  version: v1alpha1
  names:
    kind: ClusterIngress
    plural: clusteringresses
    singular: clusteringress
    categories:
    - all
    - knative-internal
    - networking
  scope: Cluster
```

and CR input looks like this:
```
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterIngress
metadata:
  name: lcq-test1
spec:
  rules:
  - hosts:
    - helloworld-go.default.example.com
    - helloworld-go.default.svc.cluster.local
    - helloworld-go.default.svc
    - helloworld-go.default
    - helloworld-go
    http:
      paths:
      - appendHeaders:
          knative-serving-namespace: default
          knative-serving-revision: helloworld-go-00001
        retries:
          attempts: 3
          perTryTimeout: 1m0s
        splits:
        - Backend:
            serviceName: activator-service
            serviceNamespace: knative-serving
            servicePort: 80
          percent: 100
        timeout: 1m0s
```
Controller is supposed to watch the resource and fill its status.
