### ISSUE TITLE
Group binding `system:serviceaccounts:kube-system` binds to all serviceaccounts clusterwide

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kubernetes#70095]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I am creating a ClusterRoleBinding which binds to all the namespaces across cluster.

**What you expected to happen**:

It should only bind to ServiceAccount in `kube-system` namespace.

**How to reproduce it (as minimally and precisely as possible)**:

- Start cluster with admission plugin `PodSecurityPolicy`

- Create user

I have created an user certs following the blog: https://brancz.com/2017/10/16/kubernetes-auth-x509-client-certificates/

The user has following permissions:

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: normal-user
rules:
- apiGroups:
  - ""
  - "apps"
  - "extensions"
  resources:
  - pods
  - namespaces
  - deployments
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: normal-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: normal-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  # this is my user name
  name: suraj
```

- Create a PodSecurityPolicy and corresponding ClusterRole and ClusterRoleBinding

```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: privileged-psp
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - privileged
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: privileged-psp-cluster-admins
roleRef:
  kind: ClusterRole
  name: privileged-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccount:kube-system
  apiGroup: rbac.authorization.k8s.io
```

In above example see that the PSP is bound to group `system:serviceaccount:kube-system` which means that the ServiceAccounts in `kube-system` namespace will get bound to the PSP defined above.

- Test this by running pods

```bash
$ kubectl --kubeconfig kubeconfig create ns psp-testing
namespace/psp-testing created

$ kubectl --kubeconfig kubeconfig -n psp-testing run web --image httpd
kubectl run --generator=deployment/apps.v1beta1 is DEPRECATED and will be removed in a future version. Use kubectl create instead.
deployment.apps/web created

$ kubectl --kubeconfig kubeconfig -n psp-testing get deployment web -o jsonpath='{.status.conditions[-1:].message}'
pods "web-7998c657dd-" is forbidden: no providers available to validate pod request
```

This failed as expected.

- Update the ClusterRoleBinding by changing the Group name to `system:serviceaccounts:kube-system`, added a `s` to `serviceaccount`.

```yaml
echo "
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: privileged-psp-cluster-admins
roleRef:
  kind: ClusterRole
  name: privileged-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:kube-system
  apiGroup: rbac.authorization.k8s.io
" | kubectl apply -f -
```

This permission spills over to other namespaces.

- Try to run the pods

```bash
$ kubectl --kubeconfig kubeconfig create ns psp-testing2
namespace/psp-testing2 created

$ kubectl --kubeconfig kubeconfig -n psp-testing2 run web --image httpd
kubectl run --generator=deployment/apps.v1beta1 is DEPRECATED and will be removed in a future version. Use kubectl create instead.                                                                                                    
deployment.apps/web created

$ kubectl --kubeconfig kubeconfig -n psp-testing2 get pods
NAME                   READY   STATUS              RESTARTS   AGE
web-7998c657dd-rd9gk   0/1     ContainerCreating   0          2s
```

**The above pod should not have started but it did. Which means that the permission got spilled.**

- If you want to re-create this setup in a single script then run this https://gist.github.com/surajssd/49366480c7c82eafef810ed598542a7f, make sure you have user created and permissions given to user as above and the cluster has admission controller `PodSecurityPolicy` enabled.

**Environment**:
- Kubernetes version:

```yaml
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-10-05T16:46:06Z
  compiler: gc
  gitCommit: 4ed3216f3ec431b140b1d899130a69fc671678f4
  gitTreeState: clean
  gitVersion: v1.12.1
  goVersion: go1.10.4
  major: "1"
  minor: "12"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-10-05T16:36:14Z
  compiler: gc
  gitCommit: 4ed3216f3ec431b140b1d899130a69fc671678f4
  gitTreeState: clean
  gitVersion: v1.12.1
  goVersion: go1.10.4
  major: "1"
  minor: "12"
  platform: linux/amd64
```

- Install tools:

```bash
$ minikube version
minikube version: v0.30.0
```

**Comment by jek-a** [comment]
Shouldn't you use 'Role' instead of 'ClusterRole'?
Here is the difference:
A Role can only be used to grant access to resources within a single namespace.
A ClusterRole can be used to grant the same permissions as a Role, but because they are cluster-scoped, they can also be used to grant access to:

cluster-scoped resources (like nodes)
non-resource endpoints (like “/healthz”)
namespaced resources (like pods) across all namespaces (needed to run kubectl get pods --all-namespaces, for example)

See: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by surajssd** [comment]
If I create a RoleBinding `privileged-psp-cluster-admins` then the permission is contained to that namespace and does not go beyond that.

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: privileged-psp-cluster-admins
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: privileged-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: system:serviceaccounts:kube-system
  apiGroup: rbac.authorization.k8s.io
```

But ClusterRoleBinding should also have worked, technically.
