### ISSUE TITLE
When Node is out of Extended Resource, the Pod still gets scheduled on that Node

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/kubernetes#70116]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
Specified an extended resource on node A as follows:-
```
  allocatable:
    mydomain.net/my-resource: "25"
  capacity:
    mydomain.net/my-resource: "25"
```
 Created a Deployment requesting the resource as follows:-
```
 resources:
            limits:
              mydomain.net/my-resource: "1"
            requests:
              mydomain.net/my-resource: "1"
```
Pod gets scheduled on Node A but fails with the following error:-

```
...
nodeName: A
status:
  message: 'Pod Node didn't have enough resource: mydomain.net/my-resource, requested:
    1, used: 0, capacity: 0'
  phase: Failed
  reason: OutOfmydomain.net/my-resource
```

**What you expected to happen**:
 I expected the pod to remain Pending when the node was out of extend resource.

**How to reproduce it (as minimally and precisely as possible)**:
This happens sometimes and not always, but eventually the pod get scheduled

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.7
- Cloud provider or hardware configuration: Centos, baremetal
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
