### ISSUE TITLE
Introduce ClusterSecret for (among others) wildcard certificates

### ISSUE THREAD

**Issue by sheerun** [kubernetes/kubernetes#70147]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Details**

In cert managers developers are [struggling to deploy](https://github.com/jetstack/cert-manager/issues/494) wildcard certificates that can be shared among applications in different namespaces. A natural solution to this would be introduction of `ClusterSecret` in similar spirit to `ClusterIssuer` or `ClusterRole`.

This is an alternative to cross-namespace secret referencing rejected in https://github.com/kubernetes/kubernetes/issues/57325

Another use case is defining `kubernetes.io/dockercfg` so deployments in different namespaces can access shared private docker repository with secret managed in one place

Feature of ClusterSecret could include:

- ability ot expose secrets to all namespaces
- ability to expose secrets to some namespaces with `matchLabels` or `matchExpressions`
- seamless integration with Secret resource where it can be used 

**Example definition of clustersecret that is visible to namespaces with `domain: example.com` label**

```
apiVersion: v2
kind: ClusterSecret
type: kubernetes.io/tls
metadata:
  name: default-wildcard-certifiate
matchLabels:
  domain: example.com 
data:
  tls.crt: ...
  tls.key: ...
```

Example usage:

```
...
spec:
  tls:
    - hosts:
      - myhost.example.com
      secretName: default-wildcard-certifiate
...
```

**Example definition of docker credentials shared to all namespaces:**

```
apiVersion: v1
kind: ClusterSecret
type: kubernetes.io/dockercfg
metadata:
  name: private-docker-registry
data:
  .dockercfg: ...
```

Example usage:

```
...
imagePullSecrets:
  - name: private-docker-registry
...
```

/sig auth
