### ISSUE TITLE
cpumanager: kubelet won't start with static policy when using minikube

### ISSUE THREAD

**Issue by ndesh26** [kubernetes/kubernetes#70161]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
kubelet does not start when the cpumanager policy is set to static

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
I am using minikube to run a single node cluster. 

**Anything else we need to know?**:
The error in kubelet logs:
Oct 24 02:14:39 minikube kubelet[8371]: I1024 02:14:39.133367    8371 cpu_manager.go:113] [cpumanager] detected CPU topology: &{2 2 1 map[0:{0 0} 1:{0 1}]}
Oct 24 02:14:39 minikube kubelet[8371]: E1024 02:14:39.133407    8371 container_manager_linux.go:291] failed to initialize cpu manager: [cpumanager] unable to determine reserved CPU resources for static policy
Oct 24 02:14:39 minikube kubelet[8371]: F1024 02:14:39.133437    8371 server.go:261] failed to run Kubelet: [cpumanager] unable to determine reserved CPU resources for static policy
Oct 24 02:14:39 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Oct 24 02:14:39 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-alpha.1", GitCommit:"8418cccaf6a7307479f1dfeafb0d2823c1c37802", GitTreeState:"clean", BuildDate:"2018-10-15T21:19:40Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
minikube v0.30.0
- Others:

cc @ConnorDoyle @balajismaniam 

Please let if know if any more details are required. I am interested in contributing to kubernetes but I am a newbie. Please let me know if I can help out in any way.

Thanks

**Comment by ndesh26** [comment]
Hi Connor,

It is working now. Though I am still seeing some errors with kubelet but they are not that critical. The docs mention it clearly that static should only be used with kube-reserved so no changes are required there. I am not about the error string though. We can add a line that --kube-reserved was not specified. What do you think?

Thanks

**Comment by linericyang** [comment]
@ndesh26 I believe cpu_manager will show a [error message](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/cpu_manager.go#L117) if --kube-reserved  or --system-reservedwas not specified.

**Comment by Davidrjx** [comment]
@ndesh26 how did you specify --kube-reserved or/and --system-reserved, especially for cgroup?

**Comment by ndesh26** [comment]
@Davidrjx You need to specify those options when starting kubelet. I hope that helps.

**Comment by Davidrjx** [comment]
@ndesh26 options specified in kubeletconfiguration seems invalid. in my case, config looks like
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cpuManagerPolicy: static
#cgroupDriver: "systemd"
podPidsLimit: 10240
#failSwapOn: false
enforceNodeAllocatable:
- "pods"
- "kube-reserved"
- "system-reserved"
systemReserved:
  cpu: "2"
  memory: "4Gi"
  ephemeral-storage: "2Gi"
systemReservedCgroup: "/system.slice"
kubeReserved:
  cpu: "2"
  memory: "4Gi"
  ephemeral-storage: "2Gi"
kubeReservedCgroup: "/system.slice/kubelet.service"
```
