### ISSUE TITLE
config map vs secret to store credentials for Postgres deployment

### ISSUE THREAD

**Issue by AndriiOmelianenko** [kubernetes/kubernetes#70241]
**What happened**:
When I tried to reference credentials stored in a secret's values to Postgres - it didn't worked properly. 

1. create a secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: dGVzdAo= # test
  POSTGRES_USER: dGVzdAo= # test
  POSTGRES_PASSWORD: dGVzdAo= # test
```

2. Reference those secrets as environment variables in Postgres deployment:
```yaml
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
```

3. try to connect to DB from container:
```bash
root@postgres-84968677c9-c4z8q:/# env | grep POSTGRES
POSTGRES_DB=test
POSTGRES_PASSWORD=test
POSTGRES_USER=test
root@postgres-84968677c9-c4z8q:/# psql -U test
psql: FATAL:  role "test" does not exist
root@postgres-84968677c9-c4z8q:/# psql -U test -d test
psql: FATAL:  role "test" does not exist
```
As you can see - the user weren't created.

**What you expected to happen**:
Please take a look at the same flow, but for Config Map (it is working as expected):

1. create a config map:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: test
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
```

2. reference in deployment:
```yaml
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
```
3. try to connect:

```bash
root@postgres-5d95457659-gpwgz:/# env | grep POSTGRES
POSTGRES_DB=test
POSTGRES_PASSWORD=test
POSTGRES_USER=test
root@postgres-5d95457659-gpwgz:/# psql -U test -d test
psql (11.0 (Debian 11.0-1.pgdg90+2))
Type "help" for help.

test=#
```

Success!

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.6", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-16T21:33:47Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/king bug
