### ISSUE TITLE
Job's backoffLimit needs to take number of failed pods into account

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#70251]
Job controller uses [`NumRequeues`](https://github.com/kubernetes/kubernetes/blob/b6fd5d93b2048ae19cbcf21bafdd5cd7249d1f33/pkg/controller/job/job_controller.go#L465-L466) of the Job workqueue to calculate backoffLimit. This makes backoffLimit unpredictable especially when a job with parallelism larger than 1 and when its restartPolicy is `Never`. 

Take this job for example:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: error
spec:
  backoffLimit: 10
  parallelism: 10
  template:
    metadata:
      name: job
    spec:
      restartPolicy: Never
      containers:
        - name: job
          image: busybox
          args:
            - /bin/sh
            - -c
            - exit 1
```

The job will eventually fail after it creates 64 failed pods, instead of 10 failed pods. 
```yaml
  [...]
  status:
    conditions:
    - lastProbeTime: "2018-10-25T18:12:06Z"
      lastTransitionTime: "2018-10-25T18:12:06Z"
      message: Job has reached the specified backoff limit
      reason: BackoffLimitExceeded
      status: "True"
      type: Failed
    failed: 64
```

If restartPolicy is set to `OnFailure`, total number of container restarts count will be taken into account. This seems more predictable. However, if we change the restartPolicy of the same Job to `OnFailure`, all the failed Pods will be deleted when they are restarted: https://github.com/kubernetes/kubernetes/blob/b6fd5d93b2048ae19cbcf21bafdd5cd7249d1f33/pkg/controller/job/job_controller.go#L520

The job will fail when its creates 10 failed pods, but will end up with 0 pods. 

@kubernetes/sig-apps-bugs @soltysh @kow3ns 

/king bug
