### ISSUE TITLE
null vs. empty array issues in json patch

### ISSUE THREAD

**Issue by jnummelin** [kubernetes/kubernetes#70281]
**What happened**:
```
$ kubectl patch deployment myapp --type='json' -p='[{"op": "add", "path":"/spec/tolerations", "value":[]}]'
deployment.extensions/myapp patched

$ kubectl patch deployment myapp --type='json' -p='[{"op": "replace", "path":"/spec/tolerations", "value":[]}]'
Error from server: jsonpatch replace operation does not apply: doc is missing key: /spec/tolerations
```

**What you expected to happen**:
The last patch to work. If the first patch is a success, I'd expect I can run the the later too.

Yes, I know that running the latter does not really make any sense functionality wise.

I'd expect that the client should not need to know about `null` and an empty array (and possibly many other things) being the same thing on the API side and resulting in the object not actually setting the given key at all.

So maybe a `replace` operation should/could be handled as in `add` for a missing key on server side? 

**How to reproduce it (as minimally and precisely as possible)**:

Create a deployment with:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      tolerations:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80
```
Notice that `tolerations` is being defined as `null` on purpose.

Then try to patch the tolerations as outlined above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:19:47Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: DO
- OS (e.g. from /etc/os-release): Ubuntu 
- Kernel (e.g. `uname -a`): 
```
root@pharos-worker-0:~# uname -a
Linux pharos-worker-0 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: Kontena Pharos
- Others:

/sig api-machinery

/kind bug
