### ISSUE TITLE
Cadvisor exposes redundant metrics with different labels

### ISSUE THREAD

**Issue by tiwalter** [kubernetes/kubernetes#70365]
**What happened**:
I scraped metrics from cadvisor with a Prometheus scrape job and stored them.

**What you expected to happen**:
Every metric for a single pod is stored once.

**How to reproduce it (as minimally and precisely as possible)**:
Add a scrape job in Prometheus with the following config:
```
- job_name: kubernetes-cadvisor
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - api_server: null
    role: node
    namespaces:
      names: []
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: false
  relabel_configs:
  - separator: ;
    regex: __meta_kubernetes_node_label_(.+)
    replacement: $1
    action: labelmap
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: kubernetes.default.svc:443
    action: replace
  - source_labels: [__meta_kubernetes_node_name]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    action: replace
```
Then monitor "container_cpu_usage_seconds_total" on the Prometheus UI especially for a running Pod on your cluster. Example query:  container_cpu_usage_seconds_total{pod_name="your-pod-name"}.
Then you can see, there are redundant metrics.

The difference between the two redundant metrics are only the labels. 
The "id" in the first metric is longer than in the second. In addition to that, the second metric has no "container_name",  "image" and "name" label.

**Anything else we need to know?**:

Prometheus version: 2.3.1

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.0

/kind bug
