### ISSUE TITLE
Support set subtraction or complement for Cluster Aggregated Roles

### ISSUE THREAD

**Issue by raravena80** [kubernetes/kubernetes#70387]
**What would you like to be added**:

Currently, [Cluster Aggregated Roles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles) represents a [set union](https://en.wikipedia.org/wiki/Union_(set_theory)) of all the roles that have been labeled. But what if somebody would like to use a 'Master' role and would but just subtract some permissions from that role and assign it another ClusterRole name? 
We would have to have a mechanism to possibly do [set complement or subtraction](https://en.wikipedia.org/wiki/Complement_(set_theory)).

Note: Set intersection might be another use case.

**Why is this needed**:

This would be a nice-to-have to avoid writing long Roles with a long set of rules.

More background [here](https://stackoverflow.com/questions/53053029/kubernetes-rbac-cluster-admin-without-secret-reading-permission)

/kind feature
/sig auth
/sig api-machinery

**Comment by Sharma-Rajat** [comment]
I agree, I am currently going through this. my roles are getting ridiculously long because I can't have cluster administrators look into tenant namespace secrets.

see example below of one of my roles.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-operator
rules:
  - apiGroups:
      - "*"
    resources:
      - bindings
      - componentstatuses
      - configmaps
      - endpoints
      - events
      - limitranges
      - namespaces
      - namespaces/finalize
      - namespaces/status
      - nodes
      - nodes/proxy
      - nodes/status
      - persistentvolumeclaims
      - persistentvolumeclaims/status
      - persistentvolumes
      - persistentvolumes/status
      - pods
      - pods/attach
      - pods/binding
      - pods/eviction
      - pods/exec
      - pods/log
      - pods/portforward
      - pods/proxy
      - pods/status
      - podtemplates
      - replicationcontrollers
      - replicationcontrollers/scale
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
      - serviceaccounts
      - services
      - services/proxy
      - services/status
      - apiservices
      - apiservices/status
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/rollback
      - deployments/scale
      - deployments/status
      - ingresses
      - ingresses/status
      - networkpolicies
      - podsecuritypolicies
      - replicasets
      - replicasets/scale
      - replicasets/status
      - replicationcontrollers
      - replicationcontrollers/scale
      - controllerrevisions
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/scale
      - deployments/status
      - replicasets
      - replicasets/scale
      - replicasets/status
      - statefulsets
      - statefulsets/scale
      - statefulsets/status
      - events
      - tokenreviews
      - localsubjectaccessreviews
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
      - horizontalpodautoscalers
      - horizontalpodautoscalers/status
      - jobs
      - jobs/status
      - certificatesigningrequests
      - certificatesigningrequests/approval
      - certificatesigningrequests/status
      - networkpolicies
      - poddisruptionbudgets
      - poddisruptionbudgets/status
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
      - storageclasses
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
      - customresourcedefinitions
      - customresourcedefinitions/status
      - connectors
      - refreshtokens
      - authrequests
      - signingkeies
      - authcodes
      - oauth2clients
      - offlinesessionses
      - passwords
      - meshpolicies
      - policies
      - rbacconfigs
      - servicerolebindings
      - serviceroles
      - servicecontrolreports
      - signalfxs
      - apikeys
      - authorizations
      - httpapispecbindings
      - reportnothings
      - fluentds
      - kubernetesenvs
      - quotaspecbindings
      - servicecontrols
      - circonuses
      - adapters
      - listcheckers
      - listentries
      - deniers
      - instances
      - attributemanifests
      - rbacs
      - rules
      - stdios
      - edges
      - redisquotas
      - metrics
      - handlers
      - logentries
      - opas
      - memquotas
      - templates
      - solarwindses
      - bypasses
      - tracespans
      - checknothings
      - noops
      - httpapispecs
      - stackdrivers
      - statsds
      - quotas
      - kuberneteses
      - quotaspecs
      - prometheuses
      - destinationrules
      - virtualservices
      - gateways
      - serviceentries
      - envoyfilters
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
```
