### ISSUE TITLE
Daemonset pods with node selector get stuck in start/termination loop

### ISSUE THREAD

**Issue by S-Chan** [kubernetes/kubernetes#70458]
**What happened**:
When a new daemonset is created with the following affinity in pod template:
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: foo
                operator: In
                values:
                - bar2
                - bar1
```
any new pods scheduled for the daemonset are immediately terminated.

**What you expected to happen**:
Daemonset pods to run without getting terminated.

**How to reproduce it (as minimally and precisely as possible)**:
1. label node A with foo=bar1
2. label node B with foo=bar2
3. create a daemonset with the above affinity

**Anything else we need to know?**:
The ordering of the nodeAffinity selector values are important. Creating a daemonset with 
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: foo
                operator: In
                values:
                - bar1
                - bar2
```
doesn't result in the issue.

After creating the daemonset, there are two corresponding ControllerRevision objects. On the ControllerRevision with the smaller revision, the serialized daemonset pod template is:
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: foo
                operator: In
                values:
                - bar2
                - bar1
```
whereas the ControllerRevision with the larger revision is:
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: foo
                operator: In
                values:
                - bar1
                - bar2
```
.
Additionally, the revisions of the two ControllerRevisions constantly increase, so something is regularly creating the ControllerRevision with the original ordering, which is immediately overridden by a sorted ordering. As a result, the Daemonset controller never ends up creating pods which match the latest controller revision.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"7eab6a49736cc7b01869a15f9f05dc5b49efb9fc", GitTreeState:"clean", BuildDate:"2018-09-14T15:54:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
```

- Kernel (e.g. `uname -a`):
```
Linux i-08d35c904744f7d91 4.4.0-137-generic #163~14.04.1-Ubuntu SMP Mon Sep 24 17:14:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

/kind bug
