### ISSUE TITLE
allowedHostPaths isn't getting applied.

### ISSUE THREAD

**Issue by zmsp** [kubernetes/kubernetes#70513]
**What happened**: We are trying to apply allowedHostPaths via PodSecurityPolicy. However the user account isn't honoring the policy. I was still allowed to create pod with a directory mounted that wasn't on the allowedHostPaths list. 

* End result: After Exec into the pod shows that files were mounted on /host-volume.

**What you expected to happen**: The pod should error out during creation and files should not be accessible on the host mount.

**How to reproduce it (as minimally and precisely as possible)**:

Create the following config:
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restrict-host-path
spec:
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedHostPaths:
    - pathPrefix: `/opt`

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:restrict-host-path
rules:
- apiGroups:
  - policy
  resourceNames:
  - restrict-host-path
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

```
* Create the namespace and the user account 
 -- `kubectl create namespace  k8s-test`
 -- `kubectl create sa k8s-test -n support`

* Apply the ClusterRole to a user account: `kubectl create rolebinding test1 --clusterrole psp:restrict-host-path --serviceaccount support:k8s-test--namespace k8s-test`
* Switch to the context/namespace via kube/config that was generated via script
* Create this pod: 
```
apiVersion: v1
kind: Pod
metadata:
  name: test-root-mount-pod
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /host-volume
      name: host-volume
    resources:
      requests:
         memory: 5Gi
         cpu: 2
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp
```
* Run ```kubectl exec test-root-mount-pod ls /host-volume
Outputs:
lost+found
file1```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version: v1.11.3
- Cloud provider or hardware configuration: bare metal/2X32 Core intel cpu, 512 GB ram
- OS: ubuntu 16.04.4
- Kernel: 4.13.0-45-generic
- Install tools: kubespray
- Others: RBAC and PodSecurityPolicy enabled

/kind bug
