### ISSUE TITLE
rollingUpdate strategy instantly killed all PODs in replicaSet

### ISSUE THREAD

**Issue by b3zn0gim** [kubernetes/kubernetes#70570]
**What happened**:
I was editing my deployments and adding pod anti-affinity section as well as additional env var to dozens of my deployments files and recently found that sometimes when I apply new deployments, Kubernetes terminates all of the PODs in replicaSet of the deployment even tho I have
```
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
```

Right now I was able to reproduce this only with replicaSets of 2 replicas. So, both PODs in replicaset is being terminated resulting in application downtime.

**What you expected to happen**:
Kubernetes should have terminate one POD, launch new replicaSet, wait at least one POD of new replicaSet is ready and then terminate another POD.

**How to reproduce it (as minimally and precisely as possible)**:
Here's deployment I have for this application:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appname
  labels:
    name: appname

spec:
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        name: appname
        serviceVendor: example

    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - appname
              topologyKey: kubernetes.io/hostname
      containers:
      - image:  gitlab.example.com:4567/example/artifacts/appname:26.5-33782-g57cedf2613a
        name: appname
        imagePullPolicy: IfNotPresent

        # Limits
        resources:
          requests:
            cpu: "100m"
            memory: "400M"

          limits:
            cpu: "500m"
            memory: "500M"

        # Wait for version
        livenessProbe:
          httpGet:
            path: /self-test
            port: 9046
            scheme: HTTPS
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 12

        # Wait for self-test
        readinessProbe:
          httpGet:
            path: /self-test
            port: 9046
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 60
          successThreshold: 1

        # Environment variables
        env:
        - name:  RESTART_
          value:  "1541077075"

        # SERVICE_MAX_MEM is used by startup script to set Xmx
        - name:  SERVICE_MAX_MEM
          value:  200m

        - name: EXAMPLE_HIVE
          value: us-vir1

        - name: CONTAINER_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: 1m
              resource: limits.cpu

        - name: CONTAINER_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: 1M
              resource: limits.memory

        # Exposed ports
        ports:
        - containerPort: 9046
          name: appname

        # Volumes
        volumeMounts:
        - mountPath: /opt/service-conf
          name: config-data

        - mountPath: /opt/service-conf/appname.keystore
          name: appname-keystore
          subPath: data

        - mountPath: /opt/appname/logs
          name: example-logs

      ########################################
      # Log delivery side-car
      ########################################
      - image: gitlab.example.com:4567/ops/overmind/nydus:latest
        name:  nydus
        imagePullPolicy: Always

        resources:
          requests:
            cpu: "10m"
            memory: "100M"

        # Volumes
        volumeMounts:
        - mountPath: /example_logs
          name: example-logs

        - mountPath: /etc/syslog-ng/additional
          name: syslog-ng-conf-dir

      ########################################
      # init containers
      ########################################
      initContainers:
      - name: infestor
        image: gitlab.example.com:4567/ops/overmind/infestor:stable
        imagePullPolicy: Always

        # Environment variables
        env:
        - name: example_infestor_properties_secret_file_path
          value: /opt/service-conf/properties-secret/data

        - name: example_infestor_syslog_conf_dir
          value: /syslog-ng_conf

        - name: example_infestor_consul_host
          value: consul0.example.com

        resources:
          requests:
            cpu: "20m"
            memory: "300M"

        volumeMounts:
        - mountPath: /opt/service-conf
          name: config-data

        - mountPath: /opt/service-conf/properties-secret
          name: appname-properties

        - mountPath: /syslog-ng_conf
          name: syslog-ng-conf-dir

      # Volumes
      volumes:
      - name: config-data
        emptyDir: {}

      - name: example-logs
        emptyDir: {}

      - name: syslog-ng-conf-dir
        emptyDir: {}

      - name: appname-keystore
        secret:
          secretName: star.example.com.keystore

      - name: appname-properties
        secret:
          secretName: appname-properties

      - name: s3up-properties
        secret:
          secretName: s3up-properties

      restartPolicy: Always

      imagePullSecrets:
        - name: gitlab-example-com-registry-secret
```
What I was doing in adding these two sections to deployment:
```
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - appname
              topologyKey: kubernetes.io/hostname
```
and this
```
        - name:  RESTART_
          value:  "1541077075"
```

and applying it with:
```
kubectl apply -f file.yaml
```

**Anything else we need to know?**:
One thing I've noticed that one of the PODs had status:
```
Status:                    Terminating (lasts <invalid>)
```
while another had 
```
Status:                    Terminating (lasts 0s)
```
I've checked kubelet logs and it looks like second POD was terminated ~200 ms after another:
```
Nov  1 19:09:55 ip-172-16-1-136 kubelet[1183]: I1101 19:09:55.059725    1183 kubelet.go:1877] SyncLoop (DELETE, "api"): "appname-75456b5c5-r6z7v_default(3e9d25b4-ddf1-11e8-9bac-06e356fdade4)"
```

```
Nov  1 19:09:55 ip-172-16-0-140 kubelet[1210]: I1101 19:09:55.208422    1210 kubelet.go:1877] SyncLoop (DELETE, "api"): "appname-75456b5c5-7nrlw_default(3eab1d3e-ddf1-11e8-9bac-06e356fdade4)"
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
AWS EC2. 
I have ~160 PODs across 8 m4.large nodes

- OS (e.g. from /etc/os-release):
```
root@ip-172-16-1-136:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

- Kernel (e.g. `uname -a`):
```
root@ip-172-16-1-136:~# uname -a
Linux ip-172-16-1-136 4.4.121-k8s #1 SMP Sun Mar 11 19:39:47 UTC 2018 x86_64 GNU/Linux
```

- Install tools:
kops
Version 1.10.0

- Others:
none

/kind bug

**Comment by xiaoxubeii** [comment]
I cannot reproduce your problem following your description:
1. create deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appname
  labels:
    name: appname
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: appname
    spec:
      containers:
      - image:  nginx:1.9
        name: appname
        imagePullPolicy: IfNotPresent
```
2. add pod antiAffinity
```
affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - appname
              topologyKey: kubernetes.io/hostname
```

What I observed is there is always one pod running. Did I miss something? 

My cluster is: 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
