### ISSUE TITLE
Allow forcing a put even when metadata.resourceVersion mismatches

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#70674]
atm when the resourceVersion mismatches kubectl pulls the latest and then retries, which is pointless since it just does the same request after
our usecase is similar, using the api to PUT the expected state, not caring for what the cluster thinks it is ... but we still get `metadata.resourceVersion: Invalid value` errors which is annoying and means we have to do a round-trip to get the latest version which might fail again if someone else updated the resource

... so support `?force=true` or `?noResourceVersion` to disable this

**Comment by zjj2wry** [comment]
The resource version is used to avoid multiple requests to update the same object at the same time. I think there should be some way to force the update, such as not passing the resource version in the update. i will investigate this.

/assign

**Comment by grosser** [comment]
not passing the version works for Deployments, but for many newer objects
like ApiService it does not work

**Comment by zjj2wry** [comment]
read the code https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/strategy.go, seems crd does not have a GuaranteedUpdate mechanism

**Comment by irvifa** [comment]
Hi, I'm just wondering given the fact that I already create a kubernetes service and the re-apply `kubectl apply -f service.yaml` command, I'll get the following error:

```
* metadata.resourceVersion: Invalid value: "": must be specified for an update
* spec.clusterIP: Invalid value: "": field is immutable
```

is this expected?

**Comment by alewitt** [comment]
just fyi: i also am having this issue when trying to force apply my crds

**Comment by bentatham** [comment]
I am having the same issue with ClusterIssuer (`certmanager.k8s.io/v1alpha1` to be specific)

**Comment by Asgoret** [comment]
Same issue with deployment config via ansible k8s...any workarounds? I need automatically update deployment if i change config map >.<

**Comment by irvifa** [comment]
@Asgoret how you perform the update?

**Comment by Asgoret** [comment]
@irvifa 
I deploy configmap, then notify for deploy again, then start deploy task. So, for example: 1 (running) -> 2 (aborted) -> 3 (running). Here is ansible tasks:
```
  - name: Check exist of deployment config
    k8s_facts:
      verify_ssl: "{{ verify_ssl }}"
      api_key: "{{ deploy_token }}"
      host: "{{ master_api }}"
      api_version: v1
      kind: DeploymentConfig
      name: "{{ service_name }}"
      namespace: "{{ namespace }}"
    register: deployments

  - name: Rollout pod with new config
    k8s:
      verify_ssl: "{{ verify_ssl }}"
      api_key: "{{ deploy_token }}"
      host: "{{ master_api }}"
      state: "{{ state }}"
      definition: "{{ lookup ('template', 'deploymentconfig.yaml.j2')}}"
    when: deployments.resources is defined
```
