### ISSUE TITLE
Replicaset . can not use ActiveDeadlineSeconds in pod spec

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#70790]
**What happened**: kubectl create apply -f test.yaml.
The ReplicaSet "replicaset-example" is invalid: spec.template.spec.activeDeadlineSeconds: Invalid value: 10: must not be specified

test.yaml is as below:

```
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: replicaset-example
spec:
  replicas: 3
  template:
    metadata:
      labels:
        test: aa
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: mpi-worker-aa
        ports:
        - containerPort: 2022
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: 30000
          timeoutSeconds: 1
      restartPolicy: Always
      activeDeadlineSeconds: 10
      terminationGracePeriodSeconds: 10

```
**What you expected to happen**:
Successfully create a rs and 3 pod.

**How to reproduce it (as minimally and precisely as possible)**:
set up a k8s cluster and use my test.yaml to set up a rs

**Anything else we need to know?**:
Error Info: The ReplicaSet "replicaset-example" is invalid: spec.template.spec.activeDeadlineSeconds: Invalid value: 10: must not be specified
**Environment**: 
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOs 7.1
- Kernel (e.g. `uname -a`):  3.10.0-862.6.3.el7.x86_64
- Install tools:
- Others:

/kind bug
