### ISSUE TITLE
修改configmap后apply daemonset配置没有生效

### ISSUE THREAD

**Issue by vperson** [kubernetes/kubernetes#70853]
在一个已经运行的集群中，保证服务不中断的情况下，对traefik 的configmap做了修改，修改后马上对其进行了更新：
```
$ kubectl apply -f traefik-configmap.yaml
```

查看到了配置已经更新到了最新：
```
$ kubectl -n kube-system describe  configmap traefik-conf
Name:         traefik-conf
Namespace:    kube-system
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","data":{"traefik.toml":"defaultEntryPoints = [\"http\",\"https\"]\n[entryPoints]\n  [entryPoints.http]\n  address = \":...

Data
====
traefik.toml:
----
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/xiaomai5.pem"
      KeyFile = "/ssl/xiaomai5.key"
```

并且执行了如下命令：
````
$ kubectl apply -f traefik-ds.yaml
serviceaccount/traefik-ingress-controller unchanged
daemonset.extensions/traefik-ingress-controller unchanged
service/traefik-ingress-service unchanged
```

daemonset 已经设置了滚动更新,滚动更新配置如下：
```
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        configMap:
          name: traefik-conf
      - name: ssl
        secret:
          secretName: taefik-cert
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8080
          hostPort: 8080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --configfile=/config/traefik.toml
        volumeMounts:
        - mountPath: "/config"
          name: "config"
        - mountPath: "/ssl"
```

问题：
在不delete traefik ds 后apply traefik ds 集群的情况下，configmap修改后，traefik没有使用最新的configmap的配置？？？？如何使配置更新并重启traefik。
