### ISSUE TITLE
Loadbalancer targetPort not forwarding to daemonset hostPort if port not same as hostPort

### ISSUE THREAD

**Issue by tom932** [kubernetes/kubernetes#70949]
**What happened**:

A loadbalancer with 2 open ports should  point to an ingress controller as daemonset, running in a gcp-kubernetes-cluster. The forwarding via using a named `targetPort` to the ports of the ingresscontroller only works when `port` matches the `hostPort`, otherwise not. Please see the example below, which I tried to make as easy and short as possible.

**What you expected to happen**:

Calling the loadbalancer on both ports (in example 444 and 445) should both deliver the same result, otherwise target port makes no sense.

**How to reproduce it (as minimally and precisely as possible)**:

My current configuration shows the problem, at least in my environment:
```
apiVersion: v1
kind: Service
metadata:
  name: lb
  namespace: ns
  labels:
    app: lb
spec:
  type: LoadBalancer
  loadBalancerIP: x.x.x.x
  ports:
      - name: test1
        port: 445
        targetPort: test

      - name: test2
        port: 444
        targetPort: test
  selector:
    k8s-app: ingress-controller
```

Here is the daemonset for the ingress-controller:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ingress-controller
  namespace: ns
  labels:
    k8s-app: ingress-controller
spec:
  selector:
    matchLabels:
      app: ingress-controller
  template:
    metadata:
      labels:
        app: ingress-controller
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: ingress-controller
          image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.15
          resources:
            requests:
              memory: "0.3Gi"
              cpu: "0.3"
            limits:
              memory: "0.5Gi"
              cpu: "0.5"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          ports:
            - name: test
              hostPort: 444
              containerPort: 443
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - /nginx-ingress-controller
            - --ingress-class=public
            - --default-backend-service=ns/default-http-backend
            - --v=2
```
The ingress then points to a plain nginx, for test purposes.

Now I encounter the following problem:

When I call the domain for the loadbalancer with the port 444 (test.mydomain.com:444), I successfully receive the nginx-default index page.

However, when I call the domain with the port 445 (test.mydomain.com:445), I would expect to get the same result, since the target port of the load-balancer block is the same, but it doesn't work.

So it seems, that the port and hostPort have to match.

It seems, that targetPort in the loadbalancer doesn't work as expected, it somehow only forwards port of lb to hostPort of ingress controller.

I already tried several things, for example configuring the ingress-controller without a hostPort, use a completely different port for hostPort, use numeric ports etc., but I never got the expected result. I've seen working examples in the internet without using hostPort, however, they never used daemonsets, but only deployments.

I also posted the question on https://serverfault.com/questions/939015/loadbalancer-targetport-not-forwarding-to-daemonset-hostport-if-port-not-same-as?noredirect=1#comment1219675_939015 in case it is not a bug but a usage question, but it seems to be a bug, or maybe an example or documentation is missing.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.6-gke.9", GitCommit:"6191a1d5adb87b656a6e14a9344267ccbfe4abc2", GitTreeState:"clean", BuildDate:"2018-11-02T23:33:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: google cloud engine

/kind bug

**Comment by thockin** [comment]
Can you please simplify further?

1) Get rid of the HostPort  (or use a totally different number that does not overlap with the service ports).
2) Use numbered targetPorts rather than named.
3) Set type=ClusterIP and test via that

Then 1-by-1 bring them back.

I can demonstrate that it works for in my cluster

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hostnames
spec:
  selector:
    matchLabels:
      run: hostnames
  template:
    metadata:
      labels:
        run: hostnames
    spec:
      containers:
      - image: k8s.gcr.io/serve_hostname:v1.4
        name: hostnames
        ports:
        - containerPort: 9376
          hostPort: 12345
          name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: hostnames
spec:
  ports:
  - name: a
    port: 80
    targetPort: backend
  - name: b
    port: 81
    targetPort: backend
  selector:
    run: hostnames
  type: LoadBalancer
```
