### ISSUE TITLE
Downward API does not provide value for spec.nodeName

### ISSUE THREAD

**Issue by tomkerkhove** [kubernetes/kubernetes#70979]
**What happened**: Downward API does not provide value for `spec.nodeName` & `metadata.labels['<label>']` for a Deployment.

**What you expected to happen**: Values to be passed as environment values

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy the following manifest

<details>
<summary>Manifest</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-sandbox
  labels:
    service: claims
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      service: claims
  template:
    metadata:
      name: sample-sandbox-pod
      labels:
        service: claims
    spec:
      containers:
      - name: sample-sandbox-myservice
        image: busybox
        command:
          - sleep
          - "3600"
        env:
        - name: Kubernetes_Service_Name
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service']
        - name: Kubernetes_Node_Name
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: Kubernetes_Pod_Name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: Kubernetes_Namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```
</details>

<br />

**Anything else we need to know?**:

- I'm not sure if this is a bug or a change in supported features but this used to work in the past for us but now it no longer does.
	- If this is no longer supported, we should update [these docs](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/).

- A while back we migrated from `beta/v1` to `apps/v1` which introduced the `selector` approach:
```yaml
selector:
    matchLabels:
      service: claims
```
	- Not sure if this is related.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Linux

/kind bug
