### ISSUE TITLE
DNS entries not exposed for StatefulSet and headless service in Kubernetes 1.12.2

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubernetes#70977]
**What happened**:
I followed https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/ However, dns lookup doesn't work at all.
**What you expected to happen**:
nslookup of web-0.nginx-service should resolve the IP
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.2
- Cloud provider or hardware configuration: localhost
- OS (e.g. from /etc/os-release): Ubuntu 18.10
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-service
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None # Headless
  selector:
    app: nginx-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx-service"
  podManagementPolicy: "Parallel" # Default is OrderedReady
  replicas: 1 # Default is 1
  selector:
    matchLabels:
      app: nginx-service # Has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: nginx-service # Has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-service
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nginx-service-volume
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: nginx-service-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```

@kubernetes/sig-Network-bugs

/kind bug
