### ISSUE TITLE
Make HostAliases write aliases for an IP on the same line in /etc/hosts

### ISSUE THREAD

**Issue by bill-warshaw** [kubernetes/kubernetes#71044]
**What would you like to be added**:

* Currently, specifying multiple aliases for a single host using `HostAliases` results in a line for each alias in `/etc/hosts`.
* Example:

```
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "foo.local"
    - "bar.local"
```

leads to an `/etc/hosts` file containing something like 

```
127.0.0.1 foo.local
127.0.0.1 bar.local
``` 

**Why is this needed**:

* Having multiple entries for the same IP address in `/etc/hosts` can break DNS resolution for some software.  See https://unix.stackexchange.com/questions/102660/hosts-file-is-it-incorrect-to-have-the-same-ip-address-on-multiple-lines for more details

/kind feature
