### ISSUE TITLE
Published CRD openapi schema does not include kind, apiVersion, metadata fields

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#71159]
**What happened**:

From https://github.com/kubernetes/kubernetes/pull/67205#issuecomment-439530024

> ValidationError(CSINodeInfo): unknown field "apiVersion" in csi.storage.k8s.io.v1alpha1.CSINodeInfo, ValidationError(CSINodeInfo): unknown field "kind" in csi.storage.k8s.io.v1alpha1.CSINodeInfo, ValidationError(CSINodeInfo): unknown field "metadata" in csi.storage.k8s.io.v1alpha1.CSINodeInfo; if you choose to ignore these errors, turn validation off with --validate=false

This indicates that the required `kind`, `apiVersion`, `metadata` fields are not present in the published openapi schema for the custom type

/assign @roycaihw 

/kind bug

**Comment by roycaihw** [comment]
Yes we definitely should include the meta fields. I'm working on a refactored version of https://github.com/kubernetes/kubernetes/pull/67205 which will included the fix. 

Thinking of reusing some pattern in the [built-in restful.WebService construction](https://github.com/kubernetes/kubernetes/blob/3ea3cfc3bea08c425593a25533bf14c703f90420/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L166-L867) this time, instead of filling a template.

**Comment by nikopen** [comment]
-tracking comment-

this will be closed soon as #71192 merges

**Comment by soggiest** [comment]
Hello!
1.14 code freeze is coming in about 3 days, will #71192 be merged in the next week?

**Comment by mingfang** [comment]
This is sometimes still a problem when the CRD does not have openAPIV3Schema then the kind, apiVersion, and metadata.
For example, if crd.yaml looks like this
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: v1
    served: true
    storage: true
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```
Then this shows the problem
```sh
>kubectl explain crontabs
KIND:     CronTab
VERSION:  stable.example.com/v1

DESCRIPTION:
     <empty>
```

However this works
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: v1
    served: true
    storage: true
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            cronSpec:
              type: string
              pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
            replicas:
              type: integer
              minimum: 1
              maximum: 10
```
```sh
>kubectl explain crontabs
KIND:     CronTab
VERSION:  stable.example.com/v1

DESCRIPTION:
     <empty>

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds

   metadata	<Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata

   spec	<>
```
