### ISSUE TITLE
Mounted ConfigMap volume is not served entirely

### ISSUE THREAD

**Issue by edbighead** [kubernetes/kubernetes#71257]
**What happened**:
ASP.NET Core SPA with external config in wwwroot/config/config.json

Contents of config.json:
```
{
  "termsAndConditionsLink": "https://some-dev-url.with/legal/terms/"
}
```

When the file is **not being overwritten by a ConfigMap**, it works fine and I am able to get the full content of file.
```
curl https://www.dev-app.com/config/config.json
{
  "termsAndConditionsLink": "https://some-dev-url.with/legal/terms/"
}
```

  

When ConfigMap data is mounted to a this path with Volume, it is not returned entirely.
```
curl https://www.dev-app.com/config/config.json
{
  "termsAndCon
```

The file is present in pod:

```
pwd
/app/wwwroot/config

ls -la
total 12
drwxrwxrwx 3 root root 4096 Nov 20 08:48 .
drwxr-xr-x 6 root root 4096 Nov 20 08:46 ..
drwxr-xr-x 2 root root 4096 Nov 20 08:48 ..2018_11_20_08_48_02.390652870
lrwxrwxrwx 1 root root   31 Nov 20 08:48 ..data -> ..2018_11_20_08_48_02.390652870
lrwxrwxrwx 1 root root   18 Nov 20 08:48 config.json -> ..data/config.json

cat config.json
{
  "termsAndConditionsLink": "https://some-dev-url.with/legal/terms/"
}
```

**ConfigMap.yaml**
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-config
data:
  config.json: |-
    {
      "termsAndConditionsLink": "https://some-dev-url.with/legal/terms/"
    }
```

**Deployment.yaml**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  labels:
	...
spec:
  template:
    metadata:
      labels:
		...
    spec:
      containers:
		...
          volumeMounts:
            - name: my-volume
              mountPath: /app/wwwroot/config
      volumes:
        - name: my-volume
          configMap:
            name: my-config
```

**What you expected to happen**:
`
curl https://www.dev-app.com/config/config.json
`  should return the full contents of mounted file.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
This is issue is resolved when specifying subpath.
```
...
	volumeMounts:
            - name: my-volume
              mountPath: /app/wwwroot/config/config.json
              subPath: config.json
      volumes:
        - name: my-volume
          configMap:
            name: my-config
```
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.18", GitCommit:"5796233393d7bc034428de15191ad3d2eaff95fb", GitTreeState:"clean", BuildDate:"2018-11-08T20:49:08Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`GKE` 
- OS (e.g. from /etc/os-release):
`Ubuntu 16.04.5 LTS`

/sig gcp

/kind bug
