### ISSUE TITLE
Hpa cpu detection java application appears to start the highest number of pod

### ISSUE THREAD

**Issue by lyy910203** [kubernetes/kubernetes#71255]
Hpa settings are as follows
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-app-gateway-hpa
  namespace: regress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-app-gateway-deploy 
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
```

Since the application is java, when the java application is started, the cpu is occupied very high, and each release version will start 3 pods.
There is a way to control the pod when it starts, not to detect
thanks
