### ISSUE TITLE
kubectl port-forward not working on grpc

### ISSUE THREAD

**Issue by zjb0807** [kubernetes/kubernetes#71348]
**What happened**:
```
kubectl -n blockchains port-forward grpc-k8s-test-server-0 50051:50051
```
then:
```
./greeter_client
2018/11/22 12:04:15 could not greet: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:50051: connect: connection refused"
```

**What you expected to happen**:
```
$ greeter_client
2018/11/22 12:17:43 Greeting: Hello world
```

**How to reproduce it (as minimally and precisely as possible)**:
Dockerfile
```
FROM golang:1.11-alpine

RUN apk add git
RUN go get -u google.golang.org/grpc/examples/helloworld/greeter_server
ENTRYPOINT ["greeter_server"]
```
k8s:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grpc-k8s-test-server
  namespace: blockchains
spec:
  selector:
    matchLabels:
      app: grpc-k8s-test-server # has to match .spec.template.metadata.labels
      tier: blockchain
      ver: v1
      type: node
  serviceName: grpc-k8s-test-server
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-k8s-test-server
        tier: blockchain
        ver: v1
        type: node
    spec:
      containers:
      - name: grpc-k8s-test-server
        image: zjb0807/grpc_k8s_test
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 200Mi
        #tty: true
        #command:
        #  - sh
        #  - -c
        #  - |
        #    trap exit TERM
        #    sleep 10000 &
        #    wait $!
        ports:
          - name: rpc
            containerPort: 50051
```

then:
```
$ go get -u google.golang.org/grpc/examples/helloworld/greeter_client
$ greeter_client
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
