### ISSUE TITLE
configmap file as executable script 

### ISSUE THREAD

**Issue by FritschAuctores** [kubernetes/kubernetes#71356]
**What would you like to be added**:

A configmap file as executable script into a pod

`apiVersion: v1
kind: ConfigMap
metadata:
  name: test-script
data:
  test.sh: |
   #!/bin/bash
   echo "Hello World"
 `

Pod:
` 
...
       volumeMounts:
        - name: test-script
          mountPath: /script/test.sh
          subPath: test.sh
      - name: test-script
        configMap:
          name: test-script
...
`
Inside the Pod:

From

-rw-r--r--  1 root root 1.3K Nov 22 15:32 test.sh
`
To
`
-rwxr-xr-x  1 root root 1.3K Nov 22 15:41 test.sh
`

**Why is this needed**:

It is easier to create a flexible Pod

/kind feature

**Comment by FritschAuctores** [comment]
@kubernetes/sig-feature-requests

**Comment by tossmilestone** [comment]
@FritschAuctores It's already supported in k8s to specify the file permissions of mounted configmap files. You can reference the usage in secret https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod.

**Comment by FritschAuctores** [comment]
Thank you, this works:

Pod:

```yml
...
       volumeMounts:
        - name: test-script
          mountPath: /script/test.sh
          subPath: test.sh
      - name: test-script
        configMap:
          name: test-script
          defaultMode: 0777
...
```
