### ISSUE TITLE
Shared volume of 1 container into another container in Kubernates

### ISSUE THREAD

**Issue by sivaprasad222** [kubernetes/kubernetes#71388]
I am stuck on a scenario where I have to get the log folder of container 1 into 2nd container. I have found a solution in which we will create a emptyDir directory.

```
spec:
  containers:
  - name: app
    image: app-image
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: logs
      mountPath: /var/log/app/
  - name: uf
    image: splunk/splunkuniversalforwarder
    ...
    volumeMounts:
    - name: logs
      mountPath: /var/log/app/
  volumes:
  - name: logs
    emptyDir: {}
```
However, in my circumstance I need to share/usr/var/log/tomcat/of first compartment into/var/log/message. This is on the grounds that [splunk](https://tekslate.com/installation-overview-splunk-add-cyberark/)UF picture will screen/var/log/application/. so I need to share the log envelope of various applications, be it/var/log/application/tomcat or/var/log/messages however at one same area with splunk holder/var/log/application/. 

I can run duplicate direction to get the log 1 time however how to get the logs consistently?
Any help is appreciated here.
@k8s-publishing-bot 
Source:stackoverflow
