### ISSUE TITLE
Admission controller fails on timeout when failurePolicy set to Ignore

### ISSUE THREAD

**Issue by omri86** [kubernetes/kubernetes#71508]
Trying to set up a validating admission webhook on my GKE cluster using the following yaml:

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: test-admission-webhook
webhooks:
  - name: my-admission-webhook.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        operations:
          - "CREATE"
        resources:
          - "pods"
    failurePolicy: Ignore
    clientConfig:
      url: "https://192.168.99.1:8080"
      caBundle: %%TEST_BUNDLE%%
```

And my server is still down, I can't run any pod on my cluster, getting the following error:

```
Error creating: Timeout: request did not complete within allowed duration
```

Even when I removed the `failurePolicy` field from my yaml file (which is supposed to default to `Ignore` as mentioned in the [official doc](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#webhook-v1beta1-admissionregistration-k8s-io)) and I'm getting the same error.

/sig api-machinery
/kind bug
