### ISSUE TITLE
Specifying Name for LoadBalancer in GCE

### ISSUE THREAD

**Issue by bluemalkin** [kubernetes/kubernetes#71577]
/kind feature

**What would you like to be added**:
Ability to specify a name for the load balancer created on GCE through an annotation something like `cloud.google.com/load-balancer-name`. Currently it generates a long hash e.g. `a08653530f3b811e89c8642010a5a020`

Example:
```
apiVersion: v1
kind: Service
metadata:
  name: my-lb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    cloud.google.com/load-balancer-name: "my-lb"
  labels:
    app: my-app
spec:
  type: LoadBalancer
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: my-app
```
