### ISSUE TITLE
mounted xfs system on /dev/sdb but /dev/sdb does not exist

### ISSUE THREAD

**Issue by miltosc** [kubernetes/kubernetes#71633]
**What happened**:

I created the following:

```
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: dev-pv-mongo-1
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    fsType: xfs
    pdName: dev-mongo-disk-1


---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dev-mongod
spec:
  serviceName: dev-mongodb-service
  replicas: 3
  template:
    metadata:
      labels:
        role: dev-mongo
        environment: dev
        replicaset: MainRepSet
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - MainRepSet
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      volumes:
        - name: dev-secrets-volume
          secret:
            secretName: dev-shared-bootstrap-data
            defaultMode: 256
      containers:
        - name: dev-mongod-container
          image: mongo:3.6
          command:
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.25"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
            - "--auth"
            - "--clusterAuthMode"
            - "keyFile"
            - "--keyFile"
            - "/etc/secrets-volume/internal-auth-mongodb-keyfile"
            - "--setParameter"
            - "authenticationMechanisms=SCRAM-SHA-1"
          resources:
            requests:
#in production cpu: 1
#              cpu: 1
              #cpu: 200m
              #memory: 2Gi

          ports:
            - containerPort: 27017
          volumeMounts:
            - name: dev-secrets-volume
              readOnly: true
              mountPath: /etc/secrets-volume
            - name: dev-mongodb-persistent-storage-claim
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: dev-mongodb-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]

---

apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: dev-pv-mongo-1
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    fsType: xfs
    pdName: dev-mongo-disk-1

```

when i login to the pod i want to enlarge the xfs disk.

```
mount |grep xfs
/dev/sdb on /data/db type xfs (rw,relatime,attr2,inode64,noquota)
```
BUT
```
ls /dev

core  fd  full  mqueue  null  ptmx  pts  random  shm  stderr  stdin  stdout  termination-log  tty  urandom  zero
```

there is NO /dev/sdb so the xfs_growfs command does not work it says not mounted xfs disk

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.11", GitCommit:"dc4f6dda6a08aae2108d7a7fdc2a44fa23900f4c", GitTreeState:"clean", BuildDate:"2018-11-10T20:22:02Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64

- Cloud provider or hardware configuration:
google cloud

- OS (e.g. from /etc/os-release):
/etc/os-release
root@lw-dev-mongod-0:/# cat  /etc/os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux lw-dev-mongod-0 4.15.0-1017-gcp #18~16.04.1-Ubuntu SMP Fri Aug 10 13:26:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

/kind bug
