### ISSUE TITLE
k/k is the canonical source of all build artifacts.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#71677]
xref: https://github.com/kubernetes/kubernetes/issues/71530

The release-repo contains aspects of the release that we know it should not own.  For example, it owns the publishing of .deb and .rpm artifacts and they are not properly maintained and versioned.  This has been the state of affairs for far too long. 

This issue exists as a tracking/umbrella issue to factor out the build artifacts such that k/k contains all the necessary tools+scripts+etc in order to build these artifacts.  Signing and publishing should likely still be a separate step.  

The following are aspirational requirements that we will need to support this effort
- [x] Investigate simplified build tooling that supports both rpm+.deb artifact building from a single conf-file (https://github.com/goreleaser/nfpm) 
- [ ] Create a builder container w/Dockerfile that can be used as part of the build.
- [ ] decouple bazel to strictly function as a variable override for a smaller set of kubernetes specific steps.  (the current state is conflating and pathological) 
    - For Example:
        - 1. conf step - nfpm.yaml.in -> bazel -> nfpm.yaml(out) 
        - 2. build step - nfpm.yaml -> (Builder Container) -> .debs & rpms. (could be linked to bazel as a separate step) 
- [ ] Update release repo to remove artifact building but to consume artifacts from the build process 
- [ ] BONUS: - Create a meta-installer container which host the rpm/deb repo to allow for a local install via local script on entry:  `e.g. docker run kubeadmer`

There are several more possible steps we could do, but this is an MVP to decouple.  

/kind feature

**Comment by timothysc** [comment]
![image](https://user-images.githubusercontent.com/169553/49409383-0cc73580-f726-11e8-923a-3411f224b7fd.png)

**Comment by mauilion** [comment]
linking https://github.com/kubernetes/kubernetes/pull/71686

**Comment by ixdy** [comment]
Is there actually any documentation on nfpm? the README is extremely sparse and doesn't really indicate how to use it or what it does or doesn't support.

**Comment by ixdy** [comment]
I installed nfpm and ran `nfpm init` and the generated `nfpm.yaml` looks nothing like that:
```yaml
# nfpm example config file
name: "foo"
arch: "amd64"
platform: "linux"
version: "v${MY_APP_VERSION}"
section: "default"
priority: "extra"
replaces:
- foobar
provides:
- bar
depends:
- foo
- bar
# recommends on rpm packages requires rpmbuild >= 4.13
recommends:
- whatever
# suggests on rpm packages requires rpmbuild >= 4.13
suggests:
- something-else
conflicts:
- not-foo
- not-bar
maintainer: "John Doe <john@example.com>"
description: |
  FooBar is the great foo and bar software.
    And this can be in multiple lines!
vendor: "FooBarCorp"
homepage: "http://eaxmple.com"
license: "MIT"
bindir: "/usr/local/bin"
files:
  ./foo: "/usr/local/bin/foo"
  ./bar: "/usr/local/bin/bar"
config_files:
  ./foobar.conf: "/etc/foobar.conf"
overrides:
  rpm:
    scripts:
      preinstall: ./scripts/preinstall.sh
      postremove: ./scripts/postremove.sh
  deb:
    scripts:
      postinstall: ./scripts/postinstall.sh
      preremove: ./scripts/preremove.sh
```

(some parts are kinda similar, but things are different enough to be worrying)
