### ISSUE TITLE
What is the difference between kube-controller-manager and kube-scheduler to use kubeconfig and config file，there is a strange error

### ISSUE THREAD

**Issue by gosoon** [kubernetes/kubernetes#71707]
Kubernetes v1.8.1
kube-controller-manager and kube-scheduler use  /etc/kubernetes/config,the config is:
```
###
# kubernetes system config
#
# The following values are used to configure various aspects of all
# kubernetes services, including
#
#   kube-apiserver.service
#   kube-controller-manager.service
#   kube-scheduler.service
#   kubelet.service
#   kube-proxy.service
# logging to stderr means we get it in the systemd journal
KUBE_LOGTOSTDERR="--logtostderr=false"

# journal message level, 0 is debug
KUBE_LOG_LEVEL="--v=3"

# Should this cluster be allowed to run privileged docker containers
KUBE_ALLOW_PRIV="--allow-privileged=true"

# How the controller-manager, scheduler, and proxy find the apiserver
KUBE_MASTER="--master=http://x.x.x.x:6443 --log-dir=/var/log/kubernetes --stderrthreshold=3"
```
And the cluster have errors. kube-controller-manager and scheduler log error is :
```
leaderelection.go:252] error retrieving resource lock kube-system/kube-controller-manager: Get https://xxxx:6443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: x509: certificate signed by unknown authority
```
Then I test kubec-controller-manager and scheduler use kubeconfig file,the  kubeconfig file is:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://xxx:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: controller-manager
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: controller-manager
  user:
    client-certificate-data: xxx
    client-key-data: xxx
```
And the cluster is ready.

/sig auth

**Comment by yue9944882** [comment]
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    certificate-authority-data: xxx
    server: https://xxx:6443
```

you can bypass server certificate verification via `insecure-skip-tls-verify: true`

/close
