### ISSUE TITLE
PullImage method in remote CRI receive PodSandboxConfig with a nil value

### ISSUE THREAD

**Issue by jorgesece** [kubernetes/kubernetes#71745]
**What happened**:
PullImage method in remote Container Runtime Interface (CRI) receives always PullImageRequest which contains the SandboxConfig object with a nil value.
 type PullImageRequest struct {
    	// Spec of the image.
    	Image *ImageSpec `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
    	// Authentication configuration for pulling the image.
    	Auth *AuthConfig `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
    	// Config of the PodSandbox, which is used to pull image in PodSandbox context.
    	SandboxConfig *PodSandboxConfig `protobuf:"bytes,3,opt,name=sandbox_config,json=sandboxConfig" json:"sandbox_config,omitempty"`
    }
**What you expected to happen**:
SandboxConfig object must contain the sandbox configuration object.
**How to reproduce it (as minimally and precisely as possible)**:
Create job by using kubectl create -f job.yaml
```
apiVersion: batch/v1
kind: Job
metadata:
  name: job-perl-docker
spec:
  template:
    metadata:
      labels:
        name: job-docker-template
    spec:
      containers:
      - name: job-docker-container
        image: perl
        command: ["sleep", "60"]
      restartPolicy: Never
      nodeSelector:
        beta.kubernetes.io/arch: amd64
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.0
- Cloud provider or hardware configuration: minikube --vm-driver=none
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): Linux 4.13.0-16 x86_64
- Install tools:
- Others:

/kind bug
