### ISSUE TITLE
Cronjob leaves behind pods after jobs are deleted

### ISSUE THREAD

**Issue by andrewsav-datacom** [kubernetes/kubernetes#71772]
**What happened**:

There seems to be a regression after 1.13 release. A Cronjob with default settings does not clean up completed pods. The job themselves are getting deleted as expected, but the pods are left behind. This seems to be related to https://github.com/kubernetes/kubernetes/pull/70872 @juanvallejo 

**What you expected to happen**:

Expected the pods for now non-existent child jobs  of a cronjob to be cleaned up. This is the way it used to work prior to 1.13/

**How to reproduce it (as minimally and precisely as possible)**:

run `kubectl apply` on this manifest:

```yaml
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: cjtest
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: cjtest
          labels:
            app: cjtest
        spec:
          restartPolicy: "Never"
          containers:
          - name: cjtest
            image: hello-world
```
Wait, more than 3 minutes, observe, that while only 3 successful jobs are present, the pods from now deleted jobs are left behind and never get deleted.

**Anything else we need to know?**:

@liggitt pointed out the following relevant places in the code base:

https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/batch/job/strategy.go#L53
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cronjob/injection.go#L121

>deleting a job orphans pods by default and the cronjob controller doesn't do anything different than the default when deleting

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.0
- Cloud provider or hardware configuration: ubuntu VM in vSphere
- OS (e.g. from /etc/os-release): 16.04.5 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): 4.4.0-135-generic 
- Install tools: kubeadm

/kind bug
