### ISSUE TITLE
how to remote debug kubernetes process

### ISSUE THREAD

**Issue by AtomWyq** [kubernetes/kubernetes#71773]
how to remote debug kubernetes process, such as using ide in windows to debug the kube-apiserver running on linux

/triage support

**Comment by myonlyzzy** [comment]
> how to remote debug kubernetes process, such as using ide in windows to debug the kube-apiserver running on linux
> 
> /triage support

you can run kube-apiserver by dlv .
` dlv --listen=":40000" --headless=true --api-version=2 exec kube-apiserver  -- --etcd-servers=http://127.0.0.1:2379 -- --insecure-port=8070 `  
if you run kube-apiserver in a container you need add  below 
```
  securityContext:
      capabilities:
        add:
          SYS_PTRACE
```
then you can create a remote debug in idea.
