### ISSUE TITLE
The Azure Cloud Controller Manager was unable to create an Internet exposed Load Balancer

### ISSUE THREAD

**Issue by marc-sensenich** [kubernetes/kubernetes#71789]
**What happened**:
The Azure Cloud Controller Manager was unable to create an Internet exposed Load Balancer with `type: LoadBalancer` without any additional source addresses

Error encountered
```
E1205 22:27:36.049674       1 azure_backoff.go:348] processHTTPRetryResponse: backoff failure, will retry, err=network.SecurityGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Origina
l Error: Code="SecurityRuleParameterContainsUnsupportedValue" Message="Security rule parameter SourceAddressPrefix for rule with Id /subscriptions/sub-id/resourceGroups/my-resource-group/providers/Microsoft.Network/networkSecurityGroups/my-nsg/securityRules/abc123-TCP-80 cannot specify existin
g VIRTUALNETWORK, INTERNET, AZURELOADBALANCER, '*' or system tags. Unsupported value used: Internet." Details=[]
```

**What you expected to happen**: 
The Azure Cloud Controller Manager should create an Internet exposed Load Balancer with `type: LoadBalancer`

**How to reproduce it (as minimally and precisely as possible)**:

In an Azure enabled cluster run the following: `kubectl apply -f nginx.yaml`

**nginx.yaml** 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```

**Anything else we need to know?**:

My initial guess is that it is related to sending `sourceAddressPrefixes: [ "Internet" ]` as a list with only the value `Internet` instead of sending `sourceAddressPrefix: "Internet"` based on https://docs.microsoft.com/en-us/rest/api/virtualnetwork/securityrules/createorupdate#request-body.

Lines of code:
- https://github.com/kubernetes/kubernetes/blob/809eaa7025119712ca82c6f4dfa73a4a544ad7ec/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L1041
- https://github.com/kubernetes/kubernetes/blob/809eaa7025119712ca82c6f4dfa73a4a544ad7ec/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L997

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

Cloud Controller Manager is running at commit https://github.com/kubernetes/kubernetes/tree/809eaa7025 due to https://github.com/kubernetes/kubernetes/pull/71736

/kind bug
/sig azure
