### ISSUE TITLE
Unboundable PV if `.spec.claimRef.namespace` key is null

### ISSUE THREAD

**Issue by prometherion** [kubernetes/kubernetes#71843]
**What happened**:

Seems that the key `.spec.claimRef.namespace` is not mandatory and can break the PV _claim_ reference.

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: my-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    name: my-pv
  hostPath:
    path: /tmp
    type: ""
  persistentVolumeReclaimPolicy: Delete
```

After creating the resources I get wrong _claim_ and obviously unbounded PVC due to `pending` state.

```
➜  ~ k get pv
NAME    CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                                                 STORAGECLASS   REASON    AGE
my-pv   10Gi       RWX            Delete           Available   /my-pv                                                                                         2s
➜  ~ k get pvc
NAME            STATUS    VOLUME          CAPACITY   ACCESS MODES   STORAGECLASS   AGE
my-pvc          Pending   my-pv           0                         standard       13s
```

**What you expected to happen**:

I expect to see applied the current namespace or the `default` one or a validation error during the creation phase.

```sh
NAME    CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                                                 STORAGECLASS   REASON    AGE
my-pv   10Gi       RWX            Delete           Available   default/my-pv                                                                                         2s
```

**How to reproduce it (as minimally and precisely as possible)**:

```sh
$: minikube start
$: echo '
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: my-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    name: my-pv
  hostPath:
    path: /tmp
    type: ""
  persistentVolumeReclaimPolicy: Delete
' | kubectl create -f -
$: kubectl get pv
$: kubectl get pvc
```

**Anything else we need to know?**:

Nope

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.0
- Cloud provider or hardware configuration: minikube, bare cluster
- OS (e.g. from /etc/os-release): minikube, Container Linux by CoreOS 1911.4.0 (Rhyolite)
- Kernel (e.g. `uname -a`): 4.15.0, 4.14.81-coreos
- Install tools: custom Ansible playbooks
- Others: none

/kind bug
