### ISSUE TITLE
cluster/kube-up.sh failed while waiting for the API to be reachable

### ISSUE THREAD

**Issue by oke-py** [kubernetes/kubernetes#71908]
**What happened**:

Following the document, [Running Kubernetes on Google Compute Engine](https://kubernetes.io/docs/setup/turnkey/gce/), `cluster/kube-up.sh` failed.

```
$ cluster/kube-up.sh
... Starting cluster in us-central1-b using provider gce
... calling verify-prereqs
... calling verify-kube-binaries
... calling verify-release-tars
... calling kube-up
.
.
.
Using master: kubernetes-master (external IP: 35.224.164.246)
Waiting up to 300 seconds for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This may time out if there was some uncaught error during start up.

........................................................................................................................................Cluster failed to initialize within 300 seconds.
Last output from querying API server follows:
-----------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 35.224.164.246 port 443: Connection refused
-----------------------------------------------------
```

Error logs below were written on kubernetes-master instance.

```
$ grep ^error /var/log/kube-apiserver.log 
error: error while parsing encryption provider configuration file "/etc/srv/kubernetes/encryption-provider-config.yml": key key1 has no provided secret
```
Secret value is null.
```yaml
$ cat /etc/srv/kubernetes/encryption-provider-config.yml
kind: EncryptionConfiguration
apiVersion: apiserver.config.k8s.io/v1
resources:
  - resources:
    - secrets
    providers:
    - aesgcm:
        keys:
        - name: key1
          secret: 
```

**What you expected to happen**:

Referring to [cluster/gce/config-default.sh#L221-L232](https://github.com/kubernetes/kubernetes/blob/396271cf52af70bc96ed378dd9ce1a865cc99647/cluster/gce/config-default.sh#L221-L232), `encryption-provider-config.yml` should be like this.

```yaml
kind: EncryptionConfiguration
apiVersion: apiserver.config.k8s.io/v1
resources:
  - resources:
    - secrets
    providers:
    - aesgcm:
        keys:
        - name: key1
          secret: +c6JL+0CBPoUhP2Ply9smxBrm+jH18feXmDEMh+gj+8=
```

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ curl -sS https://get.k8s.io | bash
$ cd kubernetes
$ cluster/kube-up.sh
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.0
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release
BUILD_ID=10323.64.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=94bdaa2af49562e7aba0168cae050911d105f5cb
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=65
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=65
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux kubernetes-master 4.4.111+ #1 SMP Wed Mar 28 13:44:38 PDT 2018 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools: `cluster/kube-up.sh`
- Others:

/kind bug
