### ISSUE TITLE
Podstatus becomes MatchNodeSelector after reboot management nodes

### ISSUE THREAD

**Issue by mysunshine92** [kubernetes/kubernetes#71907]
**What happened**:
```
[root@node1:~]$ kubectl get pod --all-namespaces -o wide
NAMESPACE   NAME                                READY     STATUS              RESTARTS   AGE       IP             NODE
default     iag-node1                           1/1       Running             655        104d      9999::106      node1
network     nwrfpod1544149758-pod-0-1-nh7p4     1/1       Running             0          1m        172.20.2.131   node2
network     nwrfpod1544149758-pod-0-1-xx4g7     0/1       MatchNodeSelector   0          6m        <none>         node1
nwtest      nwtestpod1544148681-pod-0-1-h84p5   1/1       Running             0          24m       172.20.2.130   node2
```

I have  1 management nodes + 1 worker nodes，node1 is  the management nodes
After reboot node1, Podstatus becomes MatchNodeSelector and rc create one new pod which status is Running
after reboot, I check node1's label matches pod‘s nodeAffinity

**What you expected to happen**:
after reboot, podstatus is also Running

**How to reproduce it (as minimally and precisely as possible)**:

in bare metal environment，Create a RC and assign it to management nodes based on user defined labels，then reboot the node
Here is our configuration:
```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: privilege
            operator: In
            values:
            - "true"
```

```
[root@node1:~]$ kubectl get node --show-labels
NAME      STATUS    ROLES     AGE       VERSION     LABELS
node1     Ready     <none>    104d      v1.10.0-4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,cnrmtest=true,flavor=flavor_node,ip_combination=true,kubernetes.io/hostname=node1,privilege=true
node2     Ready     <none>    104d      v1.10.0-4   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,flavor=flavor_node,ip_combination=true,kubernetes.io/hostname=node2,privilege=true
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version : 1.10.0
- Cloud provider or hardware configuration:
Bare metal 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig node
