### ISSUE TITLE
error: unable to recognize "mysql-rc.yaml": no matches for /, Kind=ReplicationController

### ISSUE THREAD

**Issue by jaffrey007** [kubernetes/kubernetes#71985]
kubernetes: version: 1.5.2
when I run: kubectl create -f mysql-rc.yaml. it throws error as title.
The yaml file of RC  is :
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql                #metadata of resource  
spec:                        # spec(properties) of resource
  replicas: 1                #number of resource to be created
  selector:                  # define a unique pod identifier
    app: mysql
  template:                 #template of pod
    metadata:
      labels:
        app: mysql
    spec:                   #which container belonged to pod
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
~

**Comment by tanshanshan** [comment]
the content you paste does not be formatted  ,I format it and it is ok , 
and you should write your Environment info such as  kubernetes version

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql #metadata of resource
spec: # spec(properties) of resource
  replicas: 1 #number of resource to be created
  selector: # define a unique pod identifier
   app: mysql
  template: #template of pod
    metadata:
      labels:
        app: mysql
    spec: #which container belonged to pod
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
```
