### ISSUE TITLE
volumeclaim in statefulset not mounting with non-root permission

### ISSUE THREAD

**Issue by viveksaiaws** [kubernetes/kubernetes#72085]
I have solr statefulset that runs, non-root user and have two volumeClaim for sts one is for data(`s3`) and one is for data backup (`s3fs`) mounted to solr-pod

I have problem with volumeClaim with `s3fs`, basically it is for backup data collection and filesystem created on pods looks like below
```
solr@solr-master-0:/tmp$ ls -la 
total 25
drwxrwxrwt 1 root root 4096 Dec 16 03:09 .
drwxr-xr-x 1 root root 4096 Dec 16 03:05 ..
drwxrwxr-x 1 root root    0 Jan  1  1970 solr
```

i want to `volumeClaim` that mount with non-root (`solr`) or `777 permissions`
**expected**
```
solr@solr-master-0:/tmp$ ls -la 
total 25
drwxrwxrwt 1 root root 4096 Dec 16 03:09 .
drwxr-xr-x 1 root root 4096 Dec 16 03:05 ..
drwxrwxr-x 1 solr solr    0 Jan  1  1970 solr
```
or
```
solr@solr-master-0:/tmp$ ls -la 
total 25
drwxrwxrwt 1 root root 4096 Dec 16 03:09 .
drwxr-xr-x 1 root root 4096 Dec 16 03:05 ..
drwxrwxrwx 1 root root    0 Jan  1  1970 solr
```

**StatefulSet**
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solr
  namespace: default
spec:
  selector:
    matchLabels:
      app: solr 
  serviceName: "solr"
  replicas: 3
  template:
    metadata:
      labels:
        app: solr
    spec:
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 10
      containers:
      - name: solr
        image: solr
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: mypvc
          mountPath: /tmp/solr
  volumeClaimTemplates:
  - metadata:
      name: mypvc
      annotations:
        ibm.io/auto-create-bucket: "true"
        ibm.io/auto-delete-bucket: "true"
        ibm.io/bucket: "mybucket"
        ibm.io/secret-name: mysecret
        volume.beta.kubernetes.io/storage-class: ibmc-s3fs-standard-perf-cross-region
        volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-s3fs
    spec:
      # securityContext:
      #   fsGroup: 1000
      #   runAsNonRoot: true
      #   runAsUser: 1000
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "ibmc-s3fs-standard-perf-cross-region"
      resources:
        requests:
          storage: 1Gi
```
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5+IKS", GitCommit:"93ab2680ca982746b1cc0827f59bb53143ebfc08", GitTreeState:"clean", BuildDate:"2018-12-03T21:32:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `IBM cloud`
- OS (e.g. from /etc/os-release): 
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
`Linux solr-master-0 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 GNU/Linux
`
- Install tools: `solr`
- Others: `solr starts with non-root, pod runs on non-root user, docker image has user solr`

/kind bug
@kubernetes/sig-storage-bugs
@kubernetes/sig-storage-api-reviews
/sig storage
