### ISSUE TITLE
SCTP doesnot work with Ubuntu 16.04

### ISSUE THREAD

**Issue by tuanqle** [kubernetes/kubernetes#72121]
**What happened**:
SCTP pod doesnot receive SCTP packets.

**What you expected to happen**:
SCTP server inside pod should receive and response to the INIT packets
**How to reproduce it (as minimally and precisely as possible)**:
1. Create a pod,sctp-server, with ncat listening on SCTP port 1000. 
2. Create service, sctp-service, to export port 1000. 
3. Start SCTP connection by using ncat from external host to the sctp-service port 1000.

**Anything else we need to know?**:
Tested with CentOS and it works fine.

TCPDUMP on the worker node shows SCTP packet get dropped with [ABORT] message.
```
WORKER TRACE        ===> WORKER DOESNOT FORWARD to container
vagrant@kube-worker:~$ sudo tcpdump -vvv -ni eth1 port 30487

tcpdump: listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes

18:46:58.446716 IP (tos 0x2,ECT(0), ttl 64, id 0, offset 0, flags [DF], proto SCTP (132), length 92)
    10.10.10.1.47606 > 10.10.10.11.30487: sctp
	1) [INIT] [init tag: 3344689091] [rwnd: 106496] [OS: 10] [MIS: 65535] [init TSN: 3907000884]
18:46:58.446783 IP (tos 0x2,ECT(0), ttl 64, id 0, offset 0, flags [DF], proto SCTP (132), length 36)
    10.10.10.11.30487 > 10.10.10.1.47606: sctp
	1) [ABORT]
18:47:01.501873 IP (tos 0x2,ECT(0), ttl 64, id 0, offset 0, flags [DF], proto SCTP (132), length 92)
    10.10.10.1.47606 > 10.10.10.11.30487: sctp
	1) [INIT] [init tag: 3344689091] [rwnd: 106496] [OS: 10] [MIS: 65535] [init TSN: 3907000884]
18:47:01.502081 IP (tos 0x2,ECT(0), ttl 64, id 0, offset 0, flags [DF], proto SCTP (132), length 36)
    10.10.10.11.30487 > 10.10.10.1.47606: sctp
	1) [ABORT]
```
**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.3-1+fee411aca93f0e", GitCommit:"fee411aca93f0e786995cc125cf8f9783484f958", GitTreeState:"clean", BuildDate:"2018-12-04T06:49:44Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.3-1+fee411aca93f0e", GitCommit:"fee411aca93f0e786995cc125cf8f9783484f958", GitTreeState:"clean", BuildDate:"2018-12-04T06:45:24Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
``` vagrant```
- OS (e.g. from /etc/os-release):
```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
uname -a
Linux kube-master 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
Configuration:
```
cat sctp-service.yml
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-server
  labels:
    app: sctp-server-app
spec:
  containers:
  - name: sctp-server
    image: <private_registry>/tester:0.3.10
    imagePullPolicy: Never
    command: ["ncat"]
    args: ["--sctp", "-k", "-l", "-p", "1000", "-c", 'i=0; while true; do read line; i=$(expr $i + 1);  echo "REQ ID: $i PONG: $line"; done']
    ports:
    - protocol: SCTP
      containerPort: 1000
      hostPort: 1000
---
kind: Service
apiVersion: v1
metadata:
  name: sctp-service
spec:
  type: NodePort
  selector:
    app: sctp-server-app
  ports:
  - protocol: SCTP
    port: 1000
    targetPort: 1000
```

/kind bug

**Comment by tuanqle** [comment]
Additional information:
Tried with docker 17.03.2-ce and also with docker 18.06.1-ce with no success.

**Comment by thockin** [comment]
I have no real experience with SCTP, and can't offer much help at the moment.  You say you see it being received but aborted?  Is the kernel module compiled in?

@janosi for consult

A possibly more useful repro:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-server
  labels:
    app: sctp-server-app
spec:
  containers:
  - name: sctp-server
    image: ubuntu
    command: ["bash"]
    args: [
        "-c",
        "apt update && apt -y install libsctp-dev lksctp-tools && sctp_darn -H 0 -P 9376 -l",
    ]
    ports:
    - protocol: SCTP
      containerPort: 9376
      hostPort: 9376
---
kind: Service
apiVersion: v1
metadata:
  name: sctp-service
spec:
  type: NodePort
  selector:
    app: sctp-server-app
  ports:
  - protocol: SCTP
    port: 9376
    targetPort: 9376
```
