### ISSUE TITLE
CSI Partial StagingPath Creation During NodeStageVolume Request

### ISSUE THREAD

**Issue by mattsmithdatera** [kubernetes/kubernetes#72207]
**What happened**: Created an application with a CSI PVC volume and the CSI
plugin attachment fails due to partial path creation of the staging target path
in the NodeStageVolume request.  This occurred on a 3-node kubernetes cluster

**What you expected to happen**:
I expected the staging target path in the CSI request to be fully created by
the CO based on the CSI spec shown here:
https://github.com/container-storage-interface/spec/blob/master/lib/go/csi/csi.pb.go#L3485

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a 3-node k8s cluster (1 master, 2 workers)
2. Install a CSI plugin that performs only Node attachments.  The yaml for my
CSI driver is here: https://gist.github.com/mattsmithdatera/f38609620339571353da4784a374abc7

3. Create a PVC with the CSI plugin using the following yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: dat-block-storage
```

4. Create an application with the following yaml
```
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app
spec:
  containers:
    - name: my-app-image
      image: alpine
      volumeMounts:
      - mountPath: "/data"
        name: my-app-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-app-volume
      persistentVolumeClaim:
        claimName: csi-pvc
```

5. The mount step will fail because of an issue in NodeStageVolume.

**Anything else we need to know?**:

Here is the NodeStageVolume request payload:
```
2018-12-19T18:31:28Z INFO GRPC -- request: /csi.v1.Node/NodeStageVolume -- volume_id:"CSI-pvc-41f41734-03b7-11e9-9568-003048f5d8a0" staging_target_path:"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-41f41734-03b7-11e9-9568-003048f5d8a0/globalmount" volume_capability:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:"storage.kubernetes.io/csiProvisionerIdentity" value:"1545242059107-8081-dsp.csi.datera.io" > 
```
You can see the full `staging_target_path` value.  At this point the CO should
have created the full path on the target attachment node.

Here are the relevant mount logs:
```
2018-12-19T18:33:23Z DEBUG Running command: [mkfs.ext4 /dev/dm-18]
2018-12-19T18:33:23Z DEBUG mke2fs 1.43.7 (16-Oct-2017)
Creating filesystem with 2621440 4k blocks and 655360 inodes
Filesystem UUID: 0d1ca2c1-49c4-4c52-b510-a53f1c860c2b
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done

2018-12-19T18:33:23Z DEBUG Mount invoked for CSI-pvc-41f41734-03b7-11e9-9568-003048f5d8a0
2018-12-19T18:33:23Z DEBUG Running command: [mount /dev/dm-18 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-41f41734-03b7-11e9-9568-003048f5d8a0/globalmount]
2018-12-19T18:33:23Z DEBUG mount: mounting /dev/dm-18 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-41f41734-03b7-11e9-9568-003048f5d8a0/globalmount failed: Invalid argument
```

The mount fails because the mount destination is only partially created at this
point.  We can verify this by looking at each of the nodes

```
# The full path doesn't exist
[root@tlx19cp ~]# ls /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-41f41734-03b7-11e9-9568-003048f5d8a0/globalmount
ls: cannot access /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-41f41734-03b7-11e9-9568-003048f5d8a0/globalmount: No such file or directory
# But this path does
[root@tlx19cp ~]# ls /var/lib/kubelet/plugins/kubernetes.io/csi/pv/                                         

# Even the truncated path doesn't exist on the master and non-target worker nodes
[root@tlx29cp ~]# ls /var/lib/kubelet/plugins/kubernetes.io/csi/pv/ 
ls: cannot access /var/lib/kubelet/plugins/kubernetes.io/csi/pv/: No such file or directory

[root@tlx15cp ~]# ls /var/lib/kubelet/plugins/kubernetes.io/csi/pv/ 
ls: cannot access /var/lib/kubelet/plugins/kubernetes.io/csi/pv/: No such file or directory
```
The plugin being used is for an iscsi-based storage vendor, but we can see that
the device `dm-18` is being created correctly since it successfully formats
in the logs above.  It fails to mount because the mount command does not
automatically create the directory structure for the destination argument.

Since the CSI spec says this should be created by the CO, this means there is
a bug in the Kubernetes CO for CSI plugins that is causing the destination to
not be fully created before it is passed to the plugin during the CSI
NodeStageVolume plugin request.

The kubelet is running with --enable-controller-attach-detach=true

kube-apiserver config: https://gist.github.com/mattsmithdatera/58ef3520afd77b31a2e3365a172d61df

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: Bare-metal 3-node kubeadm cluster
- OS (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`): `Linux tlx29cp 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `kubeadm`
- Others:

 /kind bug

**Comment by hoyho** [comment]
I think you should mount the PV path or its parent folder into the plugin container.
for example: [aws](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/f8da6ccf3aa506f1a4b88970c3a49d256f168800/deploy/kubernetes/node.yaml#L83)

```yaml
      containers:
        - name: ebs-plugin
          securityContext:
            privileged: true
          image: amazon/aws-ebs-csi-driver:latest
...other values...
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
...other values...
      volumes:
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory

```
after redeploy the plugin, problem solved
