### ISSUE TITLE
Get "more than one authentication method" error with --kubeconfig and --token options

### ISSUE THREAD

**Issue by davidmichaelkarr** [kubernetes/kubernetes#72247]
/sig bugs

I already posted a question about this on StackOverflow, which got one question about what version I'm using, and that's all. I'll include the version info here.

We have a situation where we can consistently get errors like this:
```
% kubectl --namespace ... --server ... --insecure-skip-tls-verify=true --token ... --kubeconfig default.config get pods
error: more than one authentication method found for tier-two-user; found [token basicAuth], only one is allowed
```
Our "default.config" file looks something like this:
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: ...
  name: metrics
- cluster:
    insecure-skip-tls-verify: true
    server: ...
  name: target
contexts:
- context:
    cluster: target
    user: tier-two-user
  name: ...
- context:
    cluster: metrics
    user: ...
  name: metrics
current-context: ...
kind: Config
preferences: {}
users:
- name: ...
  user:
    token: ...
- name: tier-two-user
  user:
    password: ...
    username: ...
```
From the context of the config file and our parameters, it makes it seem like kubectl thinks the "--token" parameter is a continuation of the "user" block in the config file.

It appears that using a config file with a different structure avoids the problem, but I'm uncomfortable with that situation. We need a definitive solution for this that doesn't involve guessing.

% kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5+coreos.0", GitCommit:"b8e596026feda7b97f4337b115d1a9a250afa8ac", GitTreeState:"clean", BuildDate:"2017-12-12T11:01:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
