### ISSUE TITLE
[ERROR] use podpreset to inject dnsPolicy into the pod

### ISSUE THREAD

**Issue by KylinVnne** [kubernetes/kubernetes#72293]
**What happened**:
I want to use podpreset to inject dnsPolicy into the pod, but I get an error.

context:
error: error validating "podpreset.yml": error validating data: ValidationError(PodPreset.spec): unknown field "hostAliases" in io.k8s.api.settings.v1alpha1.PodPresetSpec; if you choose to ignore these errors, turn validation off with --validate=false

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): mac ox 10.13
- Install tools:
- Others:

```
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-dns-policy
  namespace: prod
spec:
  selector:
    matchLabels:
    
  hostAliases:
  - ip: "172.16.0.100"
    hostnames:
    - "a.b.cn"
```

/kind bug
