### ISSUE TITLE
admission webhook namespace selector work not correct 

### ISSUE THREAD

**Issue by lovejoy** [kubernetes/kubernetes#72310]
**What happened**:
Created  a ValidatingWebhookConfiguration 
```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: lovejoy
webhooks:
- name: podimage.k8s.io
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - {key: tier, operator: In, values: [cache]}
  rules:
  - apiGroups:
    - "*"
    apiVersions:
    - "*"
    operations:
    - "*"
    resources:
    - "namespaces"
  ```
And use the demo webhook in https://github.com/kubernetes/kubernetes/blob/v1.10.2/test/images/webhook/main.go
Always Deny to log all the request
found some cluster-scoped object not match the selector appears
```
{"kind":"AdmissionReview","apiVersion":"admission.k8s.io/v1beta1","request":{"uid":"5749bd3b-075a-11e9-a92a-e83935bc3934","kind":{"group":"apiregistration.k8s.io","version":"v1","kind":"APIService"},"resource":{"group":"apiregistration.k8s.io","version":"v1","resource":"apiservices"},"subResource":"status","name":"v1.networking.k8s.io","operation":"UPDATE","userInfo":{"username":"system:apiserver","uid":"10c8b539-e3fe-43d8-9a36-f8a93463a0d6","groups":["system:masters"]},"object":{"metadata":{"name":"v1.networking.k8s.io","selfLink":"/apis/apiregistration.k8s.io/v1/apiservices/v1.networking.k8s.io","uid":"eb88549d-a50f-11e8-9e47-e83935bc3934","resourceVersion":"273670143","creationTimestamp":"2018-08-21T07:00:42Z","labels":{"kube-aggregator.kubernetes.io/automanaged":"onstart"}},"spec":{"service":null,"group":"networking.k8s.io","version":"v1","caBundle":null,"groupPriorityMinimum":17200,"versionPriority":15},"status":{"conditions":[{"type":"Available","status":"True","lastTransitionTime":"2018-08-21T07:00:42Z","reason":"Local","message":"Local APIServices are always available"}]}},"oldObject":{"metadata":{"name":"v1.networking.k8s.io","uid":"eb88549d-a50f-11e8-9e47-e83935bc3934","resourceVersion":"273670143","creationTimestamp":"2018-08-21T07:00:42Z","labels":{"kube-aggregator.kubernetes.io/automanaged":"onstart"}},"spec":{"service":null,"group":"networking.k8s.io","version":"v1","caBundle":null,"groupPriorityMinimum":17200,"versionPriority":15},"status":{"conditions":[{"type":"Available","status":"True","lastTransitionTime":"2018-08-21T07:00:42Z","reason":"Local","message":"Local APIServices are always available"}]}}}}
````

**What you expected to happen**:
this object shouldn't  appear

**How to reproduce it (as minimally and precisely as possible)**:
do what like upper

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
