### ISSUE TITLE
Gpu allocation fails after initContainer finishes

### ISSUE THREAD

**Issue by svuong-dev** [kubernetes/kubernetes#72486]
**What happened**:
This bug is similar to #42412
When creating a pod spec with an init container that requests all the available gpus on a node, if both the initContainer and normal container request that max amount, the init container will run fine but the normal container hits 
```
  Warning  Failed                 8m (x6 over 9m)   kubelet, 10.176.86.186  Error: Requested number of GPUs unavailable. Requested: 2, Available: 0
```

**What you expected to happen**:
The init container should release the gpu and it should be available for subsequent containers to use.

**How to reproduce it (as minimally and precisely as possible)**:
You can run
```
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "10"
    resources:
      requests:
        alpha.kubernetes.io/nvidia-gpu: 4
        cpu: "2"
        memory: 4Gi
      limits:
        alpha.kubernetes.io/nvidia-gpu: 4
        cpu: "2"
        memory: 4Gi
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'sleep 200']
    resources:
      requests:
        alpha.kubernetes.io/nvidia-gpu: 4
        cpu: "2"
        memory: 4Gi
      limits:
        alpha.kubernetes.io/nvidia-gpu: 4
        cpu: "2"
        memory: 4Gi
  restartPolicy: Never
```

Sample event
```
Events:
  Type     Reason                 Age               From                    Message
  ----     ------                 ----              ----                    -------
  Normal   Scheduled              13m               default-scheduler       Successfully assigned busybox to 10.176.86.186
  Normal   SuccessfulMountVolume  13m               kubelet, 10.176.86.186  MountVolume.SetUp succeeded for volume "default-token-xvj8k"
  Normal   Pulling                13m               kubelet, 10.176.86.186  pulling image "busybox"
  Normal   Pulled                 13m               kubelet, 10.176.86.186  Successfully pulled image "busybox"
  Normal   Created                13m               kubelet, 10.176.86.186  Created container
  Normal   Started                13m               kubelet, 10.176.86.186  Started container
  Warning  Failed                 8m (x6 over 9m)   kubelet, 10.176.86.186  Error: Requested number of GPUs unavailable. Requested: 2, Available: 0
  Normal   Pulled                 8m (x7 over 9m)   kubelet, 10.176.86.186  Successfully pulled image "busybox"
  Normal   Pulling                3m (x30 over 9m)  kubelet, 10.176.86.186  pulling image "busybox"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
