### ISSUE TITLE
TestValidateOnlyStatus flakes with `apiVersion: Invalid value`

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#72493]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1135464872302088192
```
--- FAIL: TestValidateOnlyStatus (1.61s)
I0102 19:03:43.523081  125200 establishing_controller.go:84] Shutting down EstablishingController
I0102 19:03:43.523219  125200 secure_serving.go:156] Stopped listening on 127.0.0.1:46393
I0102 19:03:43.523225  125200 naming_controller.go:295] Shutting down NamingConditionController
I0102 19:03:43.523093  125200 crd_finalizer.go:254] Shutting down CRDFinalizer
I0102 19:03:43.523081  125200 customresource_discovery_controller.go:214] Shutting down DiscoveryController
testserver.go:141: runtime-config=map[api/all:true]
testserver.go:142: Starting apiextensions-apiserver on port 36085...
testserver.go:160: Waiting for /healthz to be ok...
subresources_test.go:531: unexpected error: WishIHadChosenNoxu.mygroup.example.com "foo" is invalid: apiVersion: Invalid value: "mygroup.example.com/v1beta1": must be mygroup.example.com/v1
```

cc @mbohlool @sttts

**Comment by tallclair** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72761/pull-kubernetes-integration/40842/

**Comment by liggitt** [comment]
adding to the milestone for investigation

**Comment by liggitt** [comment]
still one of the top 3 integration flakes:
http://storage.googleapis.com/k8s-metrics/flakes-latest.json

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestValidateOnlyStatus

**Comment by liggitt** [comment]
the status strategy stomps whatever comes from the incoming object with the objectmeta and non-status fields here:
https://github.com/kubernetes/kubernetes/blob/3cd41a5a0bc4bbdf156bf925316713a1c41d634a/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go#L35-L54

it then validates the resulting object here:
https://github.com/kubernetes/kubernetes/blob/3cd41a5a0bc4bbdf156bf925316713a1c41d634a/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go#L56-L59
https://github.com/kubernetes/kubernetes/blob/3cd41a5a0bc4bbdf156bf925316713a1c41d634a/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/validator.go#L115-L117
https://github.com/kubernetes/kubernetes/blob/3cd41a5a0bc4bbdf156bf925316713a1c41d634a/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/validator.go#L140-L142

if that fails, I *think* that means oldObject is not in the same version as the incoming request, which is significant problem

**Comment by liggitt** [comment]
> if that fails, I think that means oldObject is not in the same version as the incoming request, which is significant problem

The error (`Invalid value: "mygroup.example.com/v1beta1": must be mygroup.example.com/v1`) seems to match that.

**Comment by liggitt** [comment]
Found a consistent reproducer:

1. Create a CRD with two versions and a status subresource (this also gives write permission anonymously so curl works easily):
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  scope: Namespaced
  versions:
  - name: v1
    storage: true
    served: true
  - name: v2
    storage: false
    served: true
  subresources:
    status: {}
  names:
    singular: foo
    plural: foos
    kind: Foo
    listKind: FooList
---
apiVersion: example.com/v1
kind: Foo
metadata:
  name: foo
spec:
  specValue: true
status:
  specValue: true
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: foo-role
rules:
- apiGroups: ["example.com"]
  resources: ["foos", "foos/status"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: foo-role-binding
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: foo-role
subjects:
- kind: Group
  name: system:authenticated
- kind: Group
  name: system:unauthenticated
```

2. Set up two loops, each patching the status subresource as fast as they can, each on a different version

tab 1:
```sh
for i in $( seq 1 1000 ); do
    echo $i
    v1result=$(curl -s -X PATCH https://localhost:6443/apis/example.com/v1/namespaces/default/foos/foo/status -H "Content-Type: application/merge-patch+json" --data '{"status":{"v1":"'$i'"}}' -k)
    echo "${v1result}"
    if [[ "${v1result}" == *"422"* ]]; then
        break
    fi
done
```

tab 2:
```
for i in $( seq 1 1000 ); do
    echo $i
    v2result=$(curl -s -X PATCH https://localhost:6443/apis/example.com/v2/namespaces/default/foos/foo/status -H "Content-Type: application/merge-patch+json" --data '{"status":{"v2":"'$i'"}}' -k)
    echo "${v2result}"
    if [[ "${v2result}" == *"422"* ]]; then
        break
    fi
done
```

very quickly, this is triggered from one of the tabs, complaining about the opposite version:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Foo.example.com \"foo\" is invalid: apiVersion: Invalid value: \"example.com/v1\": must be example.com/v2",
  "reason": "Invalid",
  "details": {
    "name": "foo",
    "group": "example.com",
    "kind": "Foo",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "Invalid value: \"example.com/v1\": must be example.com/v2",
        "field": "apiVersion"
      }
    ]
  },
  "code": 422
}
```
