### ISSUE TITLE
hostPort intercept LoadBalancer traffic (ipvs)

### ISSUE THREAD

**Issue by champtar** [kubernetes/kubernetes#72522]
**What happened**:

Trying to use `nodePort: 8080` and LoadBalancer (with port 8080), request to the Loadbalancer ip go to the nodePort containers, ie:
```
curl loadbalancerip:8080
=> response from a nodeport pod
```

**What you expected to happen**:
```
curl loadbalancerip:8080
=> response from loadbalancer service pod
```

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/metallb.yaml

kubectl apply -f - <<'EOF'
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: tests-ip-space
      protocol: layer2
      addresses:
      - 1.2.3.4/32
EOF

kubectl apply -f - <<'EOF'
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: echoheaders-std-ds
spec:
  selector:
    matchLabels:
      app: echoheaders-std
  template:
    metadata:
      labels:
        app: echoheaders-std
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.10
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoheaders-std
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoheaders-std
  type: LoadBalancer
  externalTrafficPolicy: Cluster
EOF

kubectl apply -f - <<'EOF'
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: echoheaders-hostport-ds
spec:
  selector:
    matchLabels:
      app: echoheaders-hostport
  template:
    metadata:
      labels:
        app: echoheaders-hostport
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.10
        ports:
        - name: http
          containerPort: 8080
          hostPort: 8080
EOF
```
(you of course need to replace the IPs)

**Anything else we need to know?**:
If I use `hostNetwork: true` (after `kubectl delete svc/echoheaders-hostport-ds`)
```
kubectl apply -f - <<'EOF'
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: echoheaders-hostnet-ds
spec:
  selector:
    matchLabels:
      app: echoheaders-hostnet
  template:
    metadata:
      labels:
        app: echoheaders-hostnet
    spec:
      hostNetwork: true
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.10
        ports:
        - name: http
          containerPort: 8080
EOF
```
request to the loadbalancerIP end up on a `echoheaders-std-*` pod, which is what I expect

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Test cluster deployed with kubespray, kube-proxy: IPVS, CNI: calico, CentOS 7.6

- OS (e.g. from /etc/os-release):
```
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`):
```
# uname -a
Linux kubespray1 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
kubespray

- Others:
Not that I can think of

/kind bug
