### ISSUE TITLE
StatefulSet podAntiAffinity not working if not enough nodes are available yet

### ISSUE THREAD

**Issue by antalm** [kubernetes/kubernetes#72565]
**What happened**:
Tried to use podAntiAffinity in a StatefulSet, but some pods were scheduled onto the same Kubernetes node if the number of available nodes was less than the number of replicas in the StatefulSet. In this example web-node-1 was down (kubelet service was stopped on purpose).

```
# kubectl get pods -o wide | grep web
web-0                                                1/1     Running                           0          11m    <none>          web-node-2     <none>
web-1                                                1/1     Running                           0          11m    <none>          web-node-0     <none>
web-2                                                0/1     CrashLoopBackOff                  9          11m    <none>          web-node-2     <none>
```

**What you expected to happen**:
Pods are in Pending state until there are enough nodes to schedule them.

**How to reproduce it (as minimally and precisely as possible)**:
Temporarily stop kubelet service on some nodes so that the number of available nodes is less than the number of replicas in the statefulset. Then try to deploy a StatefulSet with "podAntiAffinity" configured as seen below.

**Anything else we need to know?**:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: kubernetes.io/hostname
      nodeSelector:
        nodetype: web
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"archive", BuildDate:"2018-10-18T09:03:52Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"archive", BuildDate:"2018-10-08T12:08:58Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Private OpenStack cloud, 2-core, 8 GB RAM, 40 GB storage

- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"

- Kernel (e.g. `uname -a`):
Linux web-node-0 .el7.elrepo.x86_64 #1 SMP Sat Oct 20 11:33:06 EDT 2018 x86_64 x86_64 x86_64 

GNU/Linux
- Install tools:
- Others:

/kind bug
