### ISSUE TITLE
Can't create PodTemplate: "error: unable to recognize "STDIN": no matches for kind "PodTemplate" in version "core/v1"

### ISSUE THREAD

**Issue by mydockergit** [kubernetes/kubernetes#72616]
**What happened**:
I tried to create `PodTemplate` object with the following YAML: 
```
apiVersion: core/v1
kind: PodTemplate
metadata:
  name: pod-test
  namespace: default
spec:
  selector:
    matchLabels:
      name: selector
  template:
    metadata:
      labels:
        name: selector
    spec:
      containers:
      - name: container
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "echo \"hello\""]
```
I received an error:

> error: unable to recognize "STDIN": no matches for kind "PodTemplate" in version "core/v1"

**What you expected to happen**:
To have it created successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Run this:
```
kubectl apply -f - <<EOF
apiVersion: core/v1
kind: PodTemplate
metadata:
  name: pod-test
  namespace: default
spec:
  selector:
    matchLabels:
      name: selector
  template:
    metadata:
      labels:
        name: selector
    spec:
      containers:
      - name: container
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "echo \"hello\""]
EOF
```

**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
[node1 ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
https://labs.play-with-k8s.com
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux node1 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
Nothing.
- Others:

@kubernetes/sig-api-machinery-bugs

**Comment by mydockergit** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by mydockergit** [comment]
I needed to run use `v1` in the `apiVersion` and remove the `spec`:
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: PodTemplate
metadata:
  name: pod-test
  namespace: default
template:
  metadata:
    labels:
      name: selector
  spec:
    containers:
    - name: container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "echo \"hello\""]
EOF
```
Now it works.
