### ISSUE TITLE
kubectl patch cannot patch a json list of items, only a single item

### ISSUE THREAD

**Issue by natalysheinin** [kubernetes/kubernetes#72663]
**What happened**: I am applying a patch to an existing pod. This patch is an add operation of type json with includes a list of items to add. Example:

```
kubectl patch pod alpine-correct --type='json' -p='[{"op":"add","path":"/metadata/annotations", "value":{"testone.annotation.io":"test-one"}},{"op":"add","path":"/metadata/annotations","value":{"testtwo.annotation.io":"test-two"}},{"op":"add","path":"/metadata/annotations","value":{"testthree.annotation.io":"test-three"}}]'
```
Results in: `pod/alpine-correct patched`
I ran `kubectl describe pod alpine-correct`

Before the patch there were 0 annotations, now there was 1: `testthree.annotation.io":"test-three"`

**What you expected to happen**:
I expected all three annotations to get added.

**How to reproduce it (as minimally and precisely as possible)**: 

1. Create an alpine pod (`kubectl apply -f alpine-correct.yaml`)
2. Run the patch above
3. Kubectl describe the pod and observe

The alpine pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: alpine-correct
spec:
  containers:
  - image: alpine:3.2
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always
```
**Anything else we need to know?**: 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13
- Cloud provider or hardware configuration: GCP
