### ISSUE TITLE
When the deployment is created using the yaml file post request, 400 is returned.

### ISSUE THREAD

**Issue by zqdlove** [kubernetes/kubernetes#72773]
**What happened**:
### curl -X POST -H 'Content-Type: application/yaml' -d '@centos7-deploy.yaml'     http://127.0.0.1:8001/apis/apps/v1/namespaces/default/deployments
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "the object provided is unrecognized (must be of type Deployment): yaml: mapping values are not allowed in this context (61706956657273696f6e3a20617070732f76316b696e643a204465706c6f ...)",
  "reason": "BadRequest",
  "code": 400

### cat centos7-deploy.yaml 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: centos7
  name: centos7
spec:
  replicas: 1
  selector:
    matchLabels:
      name: centos7
  template:
    metadata:
      labels:
        name: centos7
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - top -b
        image: centos
        imagePullPolicy: Always
        name: centos7
```

**What you expected to happen**:
return 200
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux ctl-nm-hhht-yxxya6-k8s-003.cdnyf.io 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
Binary Installation Package
- Others:
