### ISSUE TITLE
HPA does not support AverageValue for Object metrics

### ISSUE THREAD

**Issue by arjunrn** [kubernetes/kubernetes#72824]
**What happened**: Specifying the `averageValue` for an `Object` type metric in the HPA has no effect.

**What you expected to happen**: The target scaled based on the number of replicas.

**How to reproduce it (as minimally and precisely as possible)**:
Create an HPA with custom metric scaling on an object, for example an ingress like so:
```yaml
 - type: Object
    object:
      metric:
        name: requests-per-second|sample-custom-metrics-autoscaling-master-7
      describedObject:
        apiVersion: extensions/v1beta1
        kind: Ingress
        name: sample-custom-metrics-autoscaling
      target:
        type: AverageValue
        averageValue: 5
```
And describe the created HPA. The metrics status is always shown as `0` because the value displayed is the target value which is never specified.

**Anything else we need to know?**:
The feature is describe in the [docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics) but has not been implemented in the code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L323). Only the `Value` is used for calculating the replicas and the `AverageValue` is never used.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.4
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS
