### ISSUE TITLE
defining environment variables with - in name is not complained about and does not work

### ISSUE THREAD

**Issue by KlavsKlavsen** [kubernetes/kubernetes#72888]
**What happened**:
I defined this for a deployment:
        env:
        - name: persona-app-key
          valueFrom:
            secretKeyRef:
              name: persona-app
              key: key

**What you expected to happen**:
persona-app-key should be available in env output. It was not.
if I do: 
```
env "persona-app-key=ole" bash
env
```
I can define such a variable so IT IS possible.

It DOES work - if I simply use persona_app_key.

If this is not allowed in k8s - atleast it should complain about one using an invalid env. var name.

**How to reproduce it (as minimally and precisely as possible)**:
Set this in any deployment/pod definition:
        env:
        - name: persona-app-key
          valueFrom:
            secretKeyRef:
              name: persona-app
              key: key

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.11.3

- OS (e.g. from /etc/os-release):
Ubuntu 18.04

- Kernel (e.g. `uname -a`):
4.15.0-20-generic

**Comment by liggitt** [comment]
envvars with dashes did work when I tried them locally... can you provide the full deployment manifest and (scrubbed of confidential values) secret object?

**Comment by KlavsKlavsen** [comment]
This is it.. All it does is expose secrets as env vars in the init-container.. and when I then did 'env' in the init container - the variables weren't there :(

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "php-service.name" . }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "php-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "php-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: nginx-config
      - name: logs
      - name: application
      - name: application-config
{{- range .Values.mountconfigs }}
      - name: {{ . }}
        configMap:
          name: {{ . }}
{{- end }}
#Loop over .Values.mountsecrets - and expose under /secrets mount
{{- range .Values.mountsecrets }}
      - name: {{ . }}
        secret:
          secretName: {{ . }}
{{- end }}
      initContainers:
      - name: service-init
        image: dockerreg01.example.idk:443/k8s/init-container:latest
        env:
        - name: DOCROOT
          value: {{ required "docroot must be set" .Values.docroot }}
        - name: SRCPKGNAME
          value: {{ required "applicationPackageName must be set" .Values.applicationPackageName }}
        - name: SRCPKGVERS
          value: {{ required "applicationPackageVersion must be set" .Values.applicationPackageVersion }}
        - name: EXTRAPACKAGE1NAME
          value: {{ required "applicationPackageName must be set" .Values.extrapackage1name }}
        - name: EXTRAPACKAGE1VERSION
          value: {{ .Values.extrapackage1version }}
        - name: SRCREPO
          value: {{ required "srcrepo must be set" .Values.srcrepo }}
        - name: url
          value: "{{ .Release.Name }}-{{ .Values.global.namespace }}.{{ .Values.tld }}"
#Loop over .Values.envsecrets - and set env. variables with those secrets
{{- range $key, $value := .Values.envsecrets }}
  {{- range $value }}
        - name: {{ regexReplaceAll "-" $key "_" }}_{{ . }}
          valueFrom:
            secretKeyRef:
              name: {{ $key }}
              key: {{ . }}
  {{- end }}
{{- end }}
```
