### ISSUE TITLE
volumeMount to user volume cause error

### ISSUE THREAD

**Issue by whs-dot-hk** [kubernetes/kubernetes#72960]
Docker image: https://hub.docker.com/r/apache/nifi/

docker compose not work also

```
$ kubectl logs nifi-0 -f
replacing target file  /opt/nifi/nifi-current/conf/nifi.properties
sed: can't read /opt/nifi/nifi-current/conf/nifi.properties: No such file or directory
```

**What happened**:
Error as above

**What you expected to happen**:

Can start nifi

**How to reproduce it (as minimally and precisely as possible)**:
nifi-statefulset.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: nifi-headless
  labels:
    app: nifi
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None
  selector:
    app: nifi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
spec:
  selector:
    matchLabels:
      app: nifi
      tier: backend
      track: stable
  serviceName: nifi-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: nifi
        tier: backend
        track: stable
    spec:
      containers:
        - name: nifi
          image: apache/nifi:latest
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: conf
              mountPath: /opt/nifi/nifi-current/conf
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: conf
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "default"
        resources:
          requests:
            storage: 1Gi
```

docker-compose.yaml
```
version: '3'
services:
  nifi:
    image: apache/nifi:latest
    ports:
    - 8080:8080
    volumes:
    - ./conf:/opt/nifi/nifi-current/conf
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: AKS
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
