### ISSUE TITLE
Pod containerPort does not match Service targetPort, but application still works properly

### ISSUE THREAD

**Issue by danielmapar** [kubernetes/kubernetes#73049]
**What happened**: I created a `Pod` with `containerPort: 9999` and a `Service` with `targetPort: 3000`. On that note, my application inside my `Pod` should not work, but I can access it normally.

**What you expected to happen**: Not be able to access the application inside my `Pod`

**How to reproduce it (as minimally and precisely as possible)**:
`client-pod.yaml`:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers: 
    - name: client
      image: stephengrider/multi-client
      ports:
        - containerPort: 9999
```
`client-node-port.yaml`:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 3000
      nodePort: 31515
  selector:
    component: web
```

```bash
kubectl apply -f .\client-node-port.yaml
kubectl apply -f .\client-pod.yaml
minikube ip 
Access minikubeIp:31515
```

**Anything else we need to know?**:

By running `kubectl describe pods` you will be able to see:

```yaml
Containers:
  client:
    Container ID:   docker://b515215033f9a7c223a4cb4727f8e1acced6f455ad02acd2f604e13809301ea3
    Image:          stephengrider/multi-client
    Image ID:       docker-pullable://stephengrider/multi-client@sha256:855452509d6d9f13dbe1cd34fa3a21d7f6e7d1f0fafb38d1e715dda8e3d17f46
    Port:           9999/TCP
```
and by running `kubectl descrive services` you will see:
```yaml
Name:                     client-node-port
Namespace:                default
Labels:                   <none>
Annotations:              kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"client-node-port","namespace":"default"},"spec":{"ports":[{"nodePort":31515,"p...
Selector:                 component=web
Type:                     NodePort
IP:                       10.108.209.125
Port:                     <unset>  3050/TCP
TargetPort:               3000/TCP
NodePort:                 <unset>  31515/TCP
Endpoints:                172.17.0.4:3000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

**Environment**:
- Kubernetes version (use `kubectl version`): 
```json
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Not a server
- OS (e.g. from /etc/os-release): Windows 10 64 bits + Hyper V (10.0.17763.1) + Minikube v0.32.0
- Kernel (e.g. `uname -a`):
```bash
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
```
- Install tools: `choco install minikube` and `choco install kubernetes-cli`
- Others: Created minikube vm by running: `minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"`. More details can be found [here](https://medium.com/@JockDaRock/minikube-on-windows-10-with-hyper-v-6ef0f4dc158c)
