### ISSUE TITLE
kubectl version 1.13.2 can't describe hpa resource

### ISSUE THREAD

**Issue by freevatar** [kubernetes/kubernetes#73182]
**What happened**:
`kubectl version 1.13.2` can't describe `hpa` resource but it works as expected in `kubectl version 1.11.5`
```
$ kubectl --namespace=NAMESPACE_NAME describe hpa HPA_NAME
Error from server (NotFound): the server could not find the requested resource
```
**What you expected to happen**:
```
$ kubectl --namespace=NAMESPACE_NAME describe hpa HPA_NAME
Name:                                                  HPA_NAME
Namespace:                                             NAMESPACE_NAME
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Tue, 22 Jan 2019 15:02:51 -0500
Reference:                                             Deployment/DEPLOYMENT_NAME
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  2% (29m) / 60%
Min replicas:                                          1
Max replicas:                                          10
Deployment pods:                                       1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    the last scale time was sufficiently old as to warrant a new scale
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:
  Type     Reason                        Age              From                       Message
  ----     ------                        ----             ----                       -------
  Warning  FailedGetResourceMetric       6m (x2 over 7m)  horizontal-pod-autoscaler  unable to get metrics for resource cpu: no metrics returned from resource metrics API
  Warning  FailedComputeMetricsReplicas  6m (x2 over 7m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
```
**How to reproduce it (as minimally and precisely as possible)**:
```
hpa.yaml
apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: HPA_NAME
    namespace: NAMESPACE_NAME
  spec:
    maxReplicas: 10
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: DEPLOYMENT_NAME
    targetCPUUtilizationPercentage: 60
```
**Anything else we need to know?**:
It works as a charm in `kubectl version 1.11.5`

**Environment**:
- Kubernetes version: `v1.13.2`
- Cloud provider or hardware configuration: `GKE`
- OS (e.g. from /etc/os-release): `Ubuntu 14.04.5 LTS`
- Kernel: `4.4.0-141-generic`
