### ISSUE TITLE
Pods sharing a PVC on a single node cluster fail to schedule

### ISSUE THREAD

**Issue by tuminoid** [kubernetes/kubernetes#73216]
/kind bug
/sig scheduling

**What happened**:
I run 50 Nginx containers on a single node cluster via Deployment with 50 replicas. Those containers have a volumemount via PVC backed by HostPath (`/data/kubernetes/tokens`). Sometimes `kube-scheduler` leaves some pods in `Pending` state, while some get to `Running` state. Error is that it PVC is not bound, yet describing said PVC, it is bound and used by said Pod (and 49 others).

Deleting pod in question helps (new copy gets scheduled), and so does restarting scheduler container, leading to conclusion that it is a bug in scheduler itself.

**What you expected to happen**:
All 50 containers always schedule successfully.

**How to reproduce it (as minimally and precisely as possible)**:
EDIT: Reproduced with minikube: https://github.com/kubernetes/kubernetes/issues/73216#issuecomment-457204530

Nginx deployment.yaml used: https://gist.github.com/tuminoid/56f939e5a06a16be72bbd155ecc75b2f

**Anything else we need to know?**:
Logs, describes etc: https://gist.github.com/tuminoid/5e6367070eb95d45c0d59550b888cd0e

Sometimes all pods come up, sometimes only some, and in this example, it got stuck after it had scheduled only one. Getting stuck after one is very special case, but maybe underlines the issue that it is somehow random/racy.

Maybe relevant issues/PRs?
#72045,  #71551

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
Reproduces on 1.13.1+, 1.12.4+ and 1.14.0-alpha1.

- Cloud provider or hardware configuration: Minikube / self-rolled VM
- OS (e.g. from /etc/os-release): Minikube / RHEL 7.6
- Kernel (e.g. `uname -a`): `Linux kubesingle 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Minikube (kubeadm) / manual
- Others:

**Comment by tuminoid** [comment]
This is reproducible on `minikube` as well, with basically any container (since its about scheduling, not the pod itself):

```
NAME                  READY   STATUS    RESTARTS   AGE     IP            NODE       NOMINATED NODE
bb-5697d46cdd-4tqkb   1/1     Running   0          2m35s   172.17.0.21   minikube   <none>
bb-5697d46cdd-5cf4g   0/1     Pending   0          2m34s   <none>        <none>     <none>
bb-5697d46cdd-5tml5   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-6gzgj   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-6ktfz   1/1     Running   0          2m35s   172.17.0.20   minikube   <none>
bb-5697d46cdd-6wf7m   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-7ffj2   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-7r7vt   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-8zc6m   0/1     Pending   0          2m35s   <none>        <none>     <none>
bb-5697d46cdd-95kpw   1/1     Running   0          2m34s   172.17.0.9    minikube   <none>
bb-5697d46cdd-9xqd4   1/1     Running   0          2m35s   172.17.0.19   minikube   <none>
...
```

with YAML of:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb
spec:
  replicas: 50
  strategy: {}
  selector:
    matchLabels:
      service: bb
  template:
    metadata:
      labels:
        service: bb
    spec:
      containers:
        - image: busybox:latest
          command: ['/bin/sh', '-c', '/bin/tail -f /dev/null']
          name: bb
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
          volumeMounts:
            - mountPath: /tokens
              name: pv-vault-proxy
      volumes:
        - name: pv-vault-proxy
          persistentVolumeClaim:
            claimName: pvc-vault-ro
      restartPolicy: Always
      automountServiceAccountToken: false

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-vault-ro
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: sc-vault-ro

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vault-ro
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-vault-ro
  hostPath:
    path: "/tmp"
```

Reason being `unbound immediate PersistentVolumeClaims`:
```
Name:               bb-5697d46cdd-cvpqc
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             pod-template-hash=5697d46cdd
                    service=bb
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/bb-5697d46cdd
Containers:
  bb:
    Image:      busybox:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -c
      /bin/tail -f /dev/null
    Limits:
      memory:  32Mi
    Requests:
      cpu:        10m
      memory:     16Mi
    Environment:  <none>
    Mounts:
      /tokens from pv-vault-proxy (rw)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  pv-vault-proxy:
    Type:        PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:   pvc-vault-ro
    ReadOnly:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  4m2s (x3 over 4m12s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims
```

PV and PVC:
```
$ kubectl get pvc
NAME           STATUS   VOLUME        CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-vault-ro   Bound    pv-vault-ro   10Mi       ROX            sc-vault-ro    5m47s
$ kubectl get pvc,pv
NAME                                 STATUS   VOLUME        CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/pvc-vault-ro   Bound    pv-vault-ro   10Mi       ROX            sc-vault-ro    5m50s

NAME                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                  STORAGECLASS   REASON   AGE
persistentvolume/pv-vault-ro   10Mi       ROX            Retain           Bound    default/pvc-vault-ro   sc-vault-ro             5m50s
