### ISSUE TITLE
k8s 1.13.2 + weave 2.5.0 + cri-o v1.13.1dev connect host network pods on wrong IP 

### ISSUE THREAD

**Issue by ghglza** [kubernetes/kubernetes#73276]
/sig network

**What happened**:
I have set up a k8s v1.13.2 cluster via kubeadm on CentOS 7.6 provisioned VirtualBox VMs.
I use Weave 2.5.0 as CNI plugin, and CRI-O (commit 1fecbd3cd built from source) as runtime.

The VMs have the standard NAT IP interface as eth0 on 10.0.2.15, and a VirtualBox host-only NIC configured on 192.168.99.x
kubelet node IP is set to an 192.168.99.x address via dynamic kubelet configuration (see kubeadm input below)

**What you expected to happen**:
Static pods in the kube-system namespace should be connected to the private 192.168.99 network, but are instead reported by kubectl to have the 10.0.2.15 IP.
When I use docker as container runtime, this works as expected w/o any additional configuration.

**How to reproduce it (as minimally and precisely as possible)**:
Set up cluster w/ components as described above, and kubeadm input as follows:

```
apiVersion: kubeadm.k8s.io/v1beta1
clusterName: k8m.qs0-t2att3oc.internal.com
controlPlaneEndpoint: 192.168.99.10
imageRepository: docker.internal.com:5000/k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.13.2
networking:
  dnsDomain: qs0-t2att3oc.internal.com
  podSubnet: 172.18.0.0/16
  serviceSubnet: 172.19.0.0/16
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clusterCIDR: 172.18.0.0/16
kind: KubeProxyConfiguration
---
apiVersion: kubelet.config.k8s.io/v1beta1
clusterDomain: qs0-t2att3oc.internal.com
cgroupDriver: systemd
clusterDNS:
- 172.19.0.10
evictionHard:
  imagefs.available: 5%
  nodefs.available: 5%
evictionSoft:
  imagefs.available: 5%
  nodefs.available: 5%
evictionSoftGracePeriod:
  imagefs.available: 10h
  nodefs.available: 10h
evictionPressureTransitionPeriod: 10h
hairpinMode: hairpin-veth
kind: KubeletConfiguration
podCIDR: 172.18.0.0/16
---
apiVersion: kubeadm.k8s.io/v1beta1
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  kubeletExtraArgs:
    node-ip: 192.168.99.10
    address: 192.168.99.10
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.99.10
```
**Anything else we need to know?**:
A strange effect is that when I observe the static pods during cluster startup w/ kubectl, they are reported to be connected to the 192.168.99 network for an instance, but then seem to be reconfigured (by either Weave or CRI-O?) to the wrong NAT IP.

**Environment**:
- Kubernetes version (use `kubectl version`): GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def"
- Cloud provider or hardware configuration: VirtualBox 5.2.20 r125813 VMs under Windows 7
- OS (e.g. from /etc/os-release): CentOS Linux release 7.6.1810 (Core)
- Kernel (e.g. `uname -a`):  3.10.0-957.1.3.el7.x86_64 
- Install tools: kubeadm v1.13.2
- Others: Weave 2.5.0 CNI plugin, CRI-O version 1.13.1-dev commit: "1fecbd3cd457e2cbf30ad4e7791a79ebcf9b3972" runtime
