### ISSUE TITLE
Support TLS termination with AWS NLB

### ISSUE THREAD

**Issue by meringu** [kubernetes/kubernetes#73297]
**What would you like to be added**:

AWS has announced TLS termination for network load balancers: https://aws.amazon.com/blogs/aws/new-tls-termination-for-network-load-balancers/

It would be amazing if Kuberentes could support this! The annotations are all defined, we would need to hook up the cloud provisioner.

```yaml
service.beta.kubernetes.io/aws-load-balancer-type: nlb
service.beta.kubernetes.io/aws-load-balancer-ssl-cert: `arn:...`
```

**Why is this needed**:

ACM can only be used with AWS Load balancers, so supporting TLS with NLBs means we will be able to leverage ACM and support http2 and WebSockets without using alb-ingress. This would resolve my need for ALBs in Kubernetes: https://github.com/kubernetes/kubernetes/issues/30518. For example it would make running nginx-ingress with http2 and WebSocket support possible with ACM.

**Comment by davidxjohnson** [comment]
In addition to certificate ARN, a TLS policy and TLS protocol should be attached to the NLB listener. Without this, [API GW (using PrivateLink)](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/vpc-endpoints.html) will throw errors.

Perhaps a more complete implementation would look like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn: ...
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: TLS
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
```

**Comment by rodlogic** [comment]
@davidxjohnson What about Elastic IPs that go with the NLB?

**Comment by davidxjohnson** [comment]
What about them? (elaborate)

**Comment by Stocco** [comment]
also wanting this one /support

**Comment by M00nF1sh** [comment]
will provide support for this in early next week

**Comment by swarupdonepudi** [comment]
+1

**Comment by lelabo-marc** [comment]
I hope to see the associate PR merged soon, we discovered that NLB provide much more performances with Gunicorn for handling a large amount of request / secs.

**Comment by M00nF1sh** [comment]
Hi, sorry for late update, I will push some internal forks to get this merged :D

**Comment by albeldas** [comment]
@M00nF1sh Any update regarding this issue?

**Comment by jkassis** [comment]
merge merge.

**Comment by mariusmitrofan** [comment]
Was this ever implemented...?

**Comment by jayco** [comment]
Hi guys :) 

I am using this at the moment and its working as expected, except that the annotation `service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm` is not setting the certificate for the NLB (works for the classic as expected). Just wondering if this is a know issue?
e.g:
```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <my acm arn>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
```

**Comment by mariusmitrofan** [comment]
Same for me. I had to add to modify the listeners and add it manually

**Comment by meringu** [comment]
What version of Kubernetes are you using? Looks like it made it into v1.15

**Comment by jayco** [comment]
Ahh ok - looks like 1.14, thanks for the heads up @meringu

**Comment by tettusud** [comment]
> Hi guys :)
> 
> I am using this at the moment and its working as expected, except that the annotation `service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm` is not setting the certificate for the NLB (works for the classic as expected). Just wondering if this is a know issue or am I not configuring it correctly?
> e.g:
> 
> ```
> apiVersion: v1
> kind: Service
> 
> metadata:
>   name: guestbook
>   labels:
>     app: guestbook
>   annotations:
>     service.beta.kubernetes.io/aws-load-balancer-type: nlb
>     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
>     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <my acm arn>
>     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
> spec:
>   ports:
>     - name: http
>       port: 80
>       targetPort: guestbook
>     - name: https
>       port: 443
>       targetPort: guestbook
>   selector:
>     app: guestbook
>   type: LoadBalancer
> ```

Is that creating a listener of port type **TLS**

**Comment by iusergii** [comment]
AWS NLB now support SNI and we can have multiple TLS here. Filed a new features request - 86881.

**Comment by tettusud** [comment]
@iusergii but k8 supports only port of type tcp (default one as well). with this I cannot make an https call until I change it to TLS manually. Any idea?

**Comment by scottlackey** [comment]
On version 1.15 I'm still getting `* spec.ports[1].protocol: Unsupported value: "TLS": supported values: "SCTP", "TCP", "UDP"`

```
ports:
    - name: https
      port: 443
      protocol: TLS
      targetPort: https
```

**Comment by davidxjohnson** [comment]
The current values for the annotation are thus (according to the k8s documentation):
`service.beta.kubernetes.io/aws-load-balancer-backend-protocol (http|https|ssl|tcp)`

I recall in the back-channel conversations for this feature that `ssl` was going to be used in the annotation, even though the NLB itself uses the value `TLS`. I recall that there was no desire to create a new value for the annotation and that the specific implementation of NLB would be obscured - i.e. implemented as `TLS` on the NLB listener even though `ssl` is used as the k8s annotation value.

Perhaps you can conduct an experiment by setting the annotation to `ssl` in k8s and checking the NLB to see what the backend protocol is used for the listeners?

**Comment by acumartini** [comment]
@tettusud The ssl-ports annotation needs to be 443:

annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<arn>"

**Comment by NZenitram** [comment]
Does terraform support this in the same format?

**Comment by denismoret** [comment]
I've tried to have this feature working using a NLB without success. However it does work using a Classic Load Balancer 

I am using a EKS cluster, K8s version 1.14

I followed the following steps : [AWS doc](https://aws.amazon.com/premiumsupport/knowledge-center/terminate-https-traffic-eks-acm/)

As soon as I add the annotation : `service.beta.kubernetes.io/aws-load-balancer-type: "nlb"`
The NLB listener for port 443 do not get the certificate attached.

Anyone had more luck ?

**Comment by mariusmitrofan** [comment]
@denismoret wait for EKS to release version 1.15

After that happens, upgrade it and it will. For now, we're stuck with manual change in AWS console or some workaround bash scripts :)

**Comment by mercantiandrea** [comment]
Just tested, with EKS 1.15 (released today) the annotation for the certificate works also with nlb

**Comment by mercantiandrea** [comment]
But there is a problem with ssl-redirect, if you use "force-ssl-redirect" you will go in 308 redirect loop

**Comment by stevelacy** [comment]
Just upgraded to 1.15, the following works correctly:

```yaml
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${AWS_SSL_CERT}"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```

**Comment by mikael-vertikal** [comment]
@mercantiandrea Try with

`service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"`

That fixed it for me.
From https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws: "TCP and SSL selects layer 4 proxying: the ELB forwards traffic without modifying the headers."

**Comment by robincher** [comment]
Running on EKS 1.17 , and somehow i am unable to register a 443 TLS listener for NLB.

Anybody facing the same issue?

```
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert:  "${cert_arn}"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
```

**Comment by stevelacy** [comment]
@robincher 
This is what I have on EKS 1.17 (recent install)
```
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${AWS_SSL_CERT}"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```
Note: Quote the values

**Comment by robincher** [comment]
Hi @stevelacy ,thanks i tried that and still getting only the default Listener on port 80.

I suspect that my EKS cluster are having issue reading the acm.

May i know , if you are using AWS certificate manager, do you attached any specific IAM policies to EKS the node or cluster IAM role?

**Comment by nicolasappdirect** [comment]
Hey everyone, I was trying to deploy a NLB terminating TLS on it and for myself, I could make it work:

-  By understanding that there is 2 different usages of the service.beta.kubernetes.io/aws-load-balancer-ssl-ports. Either you can use `service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"` if the Port is 443 (it could be any port on which you want to terminate the TLS) OR `service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https" BUT https represents the target name so in the below example, I should put `service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https-port"` and not https.

```
Port:                        https-port  443/TCP
TargetPort:                  8200/TCP
NodePort:                    https-port  31264/TCP
Endpoints:                   10.101.0.208:8200
```

- Also I noticed if you start to create the service with the bad config on service.beta.kubernetes.io/aws-load-balancer-ssl-ports, if you modify the service after, it doesn't update correctly the NLB, so you need to recreate the service

At the end end I can have:

```
annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443" (or the name of the target, it's as you want)
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:[Region]:[ID]:certificate/[CERT]
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
```

Hope that can help !

**Comment by guanzo** [comment]
> For example it would make running nginx-ingress with http2 and WebSocket support possible with ACM.

True but it [breaks nginx support](https://trac.nginx.org/nginx/ticket/816) for HTTP/1.1, which is unacceptable.

My NLB terminates TLS and sends the request to nginx-ingress on port 8000, which is configured as `listen 8000 proxy_protocol http2`. HTTP/2 requests work, but when I send an HTTP/1.1 it doesn't. 

Are there any workarounds for this issue?

**Comment by encryptblockr** [comment]
> **What would you like to be added**:
> 
> AWS has announced TLS termination for network load balancers: https://aws.amazon.com/blogs/aws/new-tls-termination-for-network-load-balancers/
> 
> It would be amazing if Kuberentes could support this! The annotations are all defined, we would need to hook up the cloud provisioner.
> 
> ```yaml
> service.beta.kubernetes.io/aws-load-balancer-type: nlb
> service.beta.kubernetes.io/aws-load-balancer-ssl-cert: `arn:...`
> ```
> 
> **Why is this needed**:
> 
> ACM can only be used with AWS Load balancers, so supporting TLS with NLBs means we will be able to leverage ACM and support http2 and WebSockets without using alb-ingress. This would resolve my need for ALBs in Kubernetes: #30518. For example it would make running nginx-ingress with http2 and WebSocket support possible with ACM.

this is NOT true and does not work, these 2 annotations alone do not work
why is everyone giving thumbs up to this when it does NOT work?

**Comment by RiddlerKnight** [comment]
This work for me with using RESTApi request.
```yaml
proxy:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp" # only tcp or ssl
      service.beta.kubernetes.io/aws-load-balancer-alpn-policy: None
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: |-
        preserve_client_ip.enabled=true
      service.beta.kubernetes.io/aws-load-balancer-name: "kong-pvt-eks-infra-pgd"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      
      # ssl setting
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:..."
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-FS-1-2-2019-08
    
    http:
      enabled: true

    tls:
      enabled: true

env:
  trusted_ips: 0.0.0.0/0,::0
  proxy_listen: "0.0.0.0:8000 proxy_protocol, 0.0.0.0:8443 proxy_protocol"
  real_ip_header: proxy_protocol
```

```
curl -i "https://web-kong-ex.abc.com/api/v1/SendMessage?message=abc"
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Date: Fri, 09 Jun 2023 14:50:14 GMT
Server: Kestrel
api-supported-versions: 1
X-Kong-Upstream-Latency: 3
X-Kong-Proxy-Latency: 1
Via: kong/3.3.0

{"message":"received: abc"}
```

but it's not work when using grpc through 443 which tls terminating on NLB.
