### ISSUE TITLE
Need NodePort test for mixed-OS clusters

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#73327]
We need a test case that will verify that NodePort works on all nodes in the cluster for a Windows application.

Here's an example manual test:

Run `kubectl create -f` with this yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis-2019
  labels:
    app: iis-2019
spec:
  replicas: 1
  template:
    metadata:
      name: iis-2019
      labels:
        app: iis-2019
    spec:
      containers:
      - name: iis
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        resources:
          limits:
            cpu: 1
            memory: 800m
          requests:
            cpu: .1
            memory: 300m
        ports:
          - containerPort: 80
      nodeSelector:
        "beta.kubernetes.io/os": windows
  selector:
    matchLabels:
      app: iis-2019
---
apiVersion: v1
kind: Service
metadata:
  name: iis
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: iis-2019
```

Once the pod is running, get the nodeport and make sure it's accessible on each node IP for that port.

```
$ kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
iis          NodePort    10.0.88.64   <none>        80:30220/TCP   10m
kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP        10d
azureuser@k8s-master-30163644-0:~$ kubectl get node -o wide
NAME                        STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                    KERNEL-VERSION   CONTAINER-RUNTIME
3016k8s010                  Ready    agent   10d   v1.13.2   10.240.0.35   <none>        Windows Server Datacenter   10.0.17763.253
                            docker://18.9.0
3016k8s011                  Ready   agent   10d   v1.13.2   10.240.0.96   <none>   Windows Server Datacenter   10.0.17763.253
                            docker://18.9.0
k8s-linuxpool1-30163644-0   Ready   agent    10d   v1.13.2   10.240.0.4     <none>   Ubuntu 16.04.5 LTS   4.15.0-1036-azure   docker://3.0.1
k8s-linuxpool1-30163644-1   Ready   agent    10d   v1.13.2   10.240.0.127   <none>   Ubuntu 16.04.5 LTS   4.15.0-1036-azure   docker://3.0.1
k8s-master-30163644-0       Ready   master   10d   v1.13.2   10.255.255.5   <none>   Ubuntu 16.04.5 LTS   4.15.0-1036-azure   docker://3.0.1
azureuser@k8s-master-30163644-0:~$ curl -s -o /dev/null -w "%{http_code}" http://10.240.0.35:30220
200azureuser@k8s-master-30163644-0:~$ curl -s -o /dev/null -w "%{http_code}" http://10.240.0.96:30220
200azureuser@k8s-master-30163644-0:~$ curl -s -o /dev/null -w "%{http_code}" http://10.240.0.4:30220
200azureuser@k8s-master-30163644-0:~$ curl -s -o /dev/null -w "%{http_code}" http://10.240.0.127:30220
200
```

/good-first-issue
/kind test
/sig windows

**Comment by adelina-t** [comment]
Something is wierd here:

What I did:

Fresh environment, 2 linux nodes agents, 2 windows agents, deployed with aks-engine v.29.1.
Using k8s 13.2.

```
NAME                        STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                    KERNEL-VERSION   CONTAINER-RUNTIME
2923k8s010                  Ready    agent   15m   v1.13.2   10.240.0.66   <none>        Windows Server Datacenter   10.0.17763.253
                            docker://18.9.0
2923k8s011                  Ready   agent   14m   v1.13.2   10.240.0.97   <none>   Windows Server Datacenter   10.0.17763.253
                            docker://18.9.0
k8s-linuxpool1-29232129-0   Ready   agent    21m   v1.13.2   10.240.0.4     <none>   Ubuntu 16.04.5 LTS   4.15.0-1036-azure   docker://3.0.1
k8s-linuxpool1-29232129-1   Ready   agent    21m   v1.13.2   10.240.0.35    <none>   Ubuntu 16.04.5 LTS   4.15.0-1036-azure   docker://3.0.1
k8s-master-29232129-0       Ready   master   21m   v1.13.2   10.255.255.5   <none>   Ubuntu 16.04.5 LTS   4.15.0-1036-azure   docker://3.0.1
```

I used the exact spec you indicated:

```
kubectl get pods -o wide
NAME                      READY   STATUS    RESTARTS   AGE     IP             NODE         NOMINATED NODE   READINESS GATES
iis-2019-c5d48d8c-p9ldf   1/1     Running   0          9m29s   10.240.0.108   2923k8s011   <none>           <none>
```

As you can see, it is assigned to the node: **2923k8s011**. This is the first ever pod ( other than kube-system, that don't land on windows ) created on the windows nodes.

```
kubectl get service
NAME         TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
iis          NodePort    10.0.220.26   <none>        80:32236/TCP   11m
kubernetes   ClusterIP   10.0.0.1      <none>        443/TCP        26m
```

CURL on the first windows node:

```
curl -s -o /dev/null -w "HTTP_CODE: %{http_code}\n" http://10.240.0.66:32236
HTTP_CODE: 000

( full message: curl: (7) Failed to connect to 10.240.0.66 port 32236: Connection refused )
```

Curl on the other cluster nodes works:

```
azureuser@k8s-master-29232129-0:~$ curl -s -o /dev/null -w "HTTP_CODE: %{http_code}\n" http://10.240.0.97:32236
HTTP_CODE: 200
azureuser@k8s-master-29232129-0:~$ curl -s -o /dev/null -w "HTTP_CODE: %{http_code}\n" http://10.240.0.4:32236
HTTP_CODE: 200
azureuser@k8s-master-29232129-0:~$ curl -s -o /dev/null -w "HTTP_CODE: %{http_code}\n" http://10.240.0.35:32236
HTTP_CODE: 200
```

kubeproxy logs on the first node only contain this:

```
Waiting for Network [azure] to be created . . .
Waiting for Network [azure] to be created . . .
Waiting for Network [azure] to be created . . .
Waiting for Network [azure] to be created . . .
Waiting for Network [azure] to be created . . .
```

After I create a bunch of other pods, to make sure one gets scheduled on the windows node, **the initial pod will be accessible via nod port** from the first node as well.

```
azureuser@k8s-master-29232129-0:~$ curl  -s -o /dev/null -w "HTTP_CODE: %{http_code}\n" http://10.240.0.66:32236
HTTP_CODE: 200
```

**Comment by adelina-t** [comment]
Cc @patricklang

**Comment by PatrickLang** [comment]
per @dineshgovindasamy - Azure-CNI only creates the network when a pod is scheduled. Kube-proxy waits for the network to be created. Therefore if no pod has been scheduled, kube-proxy won't be active on that node.

This won't affect Flannel or OVN deployments because they have a daemon already running that creates the network.

**Comment by PatrickLang** [comment]
@immuzz is going to take a look
cc @neolit123

**Comment by huxiaoliang** [comment]
NodePort  service doesn't work on my mixed-OS clusters (1 k8s linux master + 1 k8s linux worker + 1 windows worker) as well. I depends on https://kubernetes.io/docs/getting-started-guides/windows/#host-gateway-topology as network solution for windows node, other linux node use calico for networking.  all works well except accept access NodePort  service on windows node, it seems the Port 31858 is not get stared on windows node, anyone who get to get more info for this issue, please let me know, thanks
```
[root@linuxmaster flannel]# kubectl get svc
NAME           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
aspnetapp      ClusterIP   10.0.249.154   <none>        80/TCP         18h
aspnetappsvc   NodePort    10.0.15.35     <none>        80:31858/TCP   8m14s
kubernetes     ClusterIP   10.0.0.1       <none>        443/TCP        6d18h
[root@linuxmaster flannel]# kubectl get node
NAME              STATUS   ROLES                                 AGE     VERSION
192.168.122.151   Ready    worker                                6d18h   v1.12.4+icp-ee
192.168.122.154   Ready    etcd,management,master,proxy,worker   6d18h   v1.12.4+icp-ee
winwork01         Ready    <none>                                25h     v1.12.4
[root@linuxmaster flannel]# curl -s -o /dev/null -w "%{http_code}" 192.168.122.154:31858
200[root@linuxmaster flannel]# curl -s -o /dev/null -w "%{http_code}" 192.168.122.151:31858
200[root@linuxmaster flannel]# curl -s -o /dev/null -w "%{http_code}" winwork01:31858
[root@linuxmaster flannel]# ping winwork01
PING winwork01 (192.168.122.156) 56(84) bytes of data.
64 bytes from winwork01 (192.168.122.156): icmp_seq=1 ttl=128 time=0.650 ms
^C
--- winwork01 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.650/0.650/0.650/0.000 ms
[root@linuxmaster flannel]# curl -s -o /dev/null -w "%{http_code}" 192.168.122.156:31858
000[root@linuxmaster flannel]#
```

**Comment by huxiaoliang** [comment]
@immuzz  I am waiting your feedback, thanks in advance.

**Comment by huxiaoliang** [comment]
this message show in the kube-proxy logs periodically.

```
I0222 00:53:35.640977    4284 healthcheck.go:235] Not saving endpoints for unknown healthcheck "default/aspnetapp"
I0222 00:53:35.640977    4284 proxier.go:930] syncProxyRules took 97.9995ms
I0222 00:53:35.641980    4284 bounded_frequency_runner.go:221] sync-runner: ran, next possible in 0s, periodic in 30s
```

**Comment by dineshgovindasamy** [comment]
@huxiaoliang please send us the debug logs.

https://github.com/Microsoft/SDN/blob/master/Kubernetes/windows/debug/Debug.md

@madhanrm

**Comment by huxiaoliang** [comment]
@dineshgovindasamy  thanks, below is my log, please take a look, 
[fwboqyja.egw.zip](https://github.com/kubernetes/kubernetes/files/2896606/fwboqyja.egw.zip)

**Comment by dineshgovindasamy** [comment]
@huxiaoliang i looked at the logs i dont see any LB Policy programmed in HNS for the IP aspnetappsvc   NodePort    10.0.15.35     <none>        80:31858/TCP   8m14s.

Could you please confirm that this is the nodeport we are looking to debug?

In the log files you collected please look @ policy.txt and see if the policy you were trying to program is there or not. if its there and it doesnt work then its an HNS issue.

if the policy is not there in that file then its a KubeProxy issue where the policy itself is not programmed in HNS. Then look at Kubeproxy to see why its failing to plumb the policy.

**Comment by huxiaoliang** [comment]
@dineshgovindasamy  thanks for the  your suggestion, i will retry it and append the result here.

**Comment by huxiaoliang** [comment]
Below is my retest full steps and output:
```
[root@linuxmaster flannel]# cat asp-deployment.yaml 
---
kind: Service
apiVersion: v1
metadata:
  name: aspnetapp
spec:
  selector:
    app: aspnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aspnetapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": "windows"
        "kubernetes.io/hostname" : "winwork01"
      tolerations:
      - key: "windows"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: aspnetapp
        image: microsoft/dotnet-samples:aspnetapp 
        ports:
        - containerPort: 80
```
```
[root@linuxmaster flannel]# kubectl get po -o wide
NAME                                    READY   STATUS    RESTARTS   AGE     IP            NODE              NOMINATED NODE
aspnetapp-deployment-676fcb6647-8n4z8   1/1     Running   0          31s     10.1.140.22   winwork01         <none>
busybox-6c5586d46f-stlp2                1/1     Running   189        7d19h   10.1.120.76   192.168.122.151   <none>
nginx-deployment-677956c6fb-7nl5d       1/1     Running   2          34h     10.1.120.77   192.168.122.151   <none>
```

```
[root@linuxmaster flannel]# wget 10.1.140.22
--2019-02-26 21:45:03--  http://10.1.140.22/
Connecting to 10.1.140.22:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: â€˜index.htmlâ€™

    [ <=>                                                                                       ] 9,656       --.-K/s   in 0.001s  

2019-02-26 21:45:04 (9.07 MB/s) - â€˜index.htmlâ€™ saved [9656]
```
```
[root@linuxmaster flannel]# kubectl get svc
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
aspnetapp    ClusterIP   10.0.188.149   <none>        80/TCP    4m43s
kubernetes   ClusterIP   10.0.0.1       <none>        443/TCP   11d
my-service   ClusterIP   10.0.20.15     <none>        80/TCP    34h
```

```
[root@linuxmaster flannel]# kubectl expose service aspnetapp --type=NodePort --name=aspnetappsvc
service/aspnetappsvc exposed
[root@linuxmaster flannel]# kubectl get svc
NAME           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
aspnetapp      ClusterIP   10.0.188.149   <none>        80/TCP         5m22s
aspnetappsvc   NodePort    10.0.140.250   <none>        80:32332/TCP   3s
kubernetes     ClusterIP   10.0.0.1       <none>        443/TCP        11d
my-service     ClusterIP   10.0.20.15     <none>        80/TCP         34h
[root@linuxmaster flannel]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.122.154 linuxmaster
192.168.122.153 linuxwork01
192.168.122.151 linuxwork03
192.168.122.155 winwork02
192.168.122.156 winwork01
192.168.122.154 mycluster.icp
[root@linuxmaster flannel]# wget 192.168.122.151:32332
--2019-02-26 21:50:26--  http://192.168.122.151:32332/
Connecting to 192.168.122.151:32332... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: â€˜index.htmlâ€™

    [ <=>                                                                                       ] 9,656       --.-K/s   in 0.001s  

2019-02-26 21:50:26 (8.92 MB/s) - â€˜index.htmlâ€™ saved [9656]

[root@linuxmaster flannel]#
```

it seems the ip of   aspnetapp and aspnetappsvc not in policy.txt, but I don't see any error in kube-proxy logs except https://github.com/kubernetes/kubernetes/issues/73327#issuecomment-466323299

Any comments ?   I need more debug on kube-proxy according to your suggestion

[ub1lebx0.dft.zip](https://github.com/kubernetes/kubernetes/files/2908396/ub1lebx0.dft.zip)
