### ISSUE TITLE
Projected Volumes for secrets/configmaps with multi-level paths does not work on Windows

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#73321]
**What happened**:
The example for **Projection of secret keys to specific paths** in kubernetes.io document does not work. The problem seems caused by giving subpath for the target of key. If only one level of directory is given, then it is working fine for windows. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Just create secret and pod with the given example

```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
stringData:
  username: administrator
```
```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      items:
      - key: username
        path: my-group/my-username
```

**Anything else we need to know?**:
Supsect there is some problem in automic_writer code when createUserVisibleFiles because Path.Join only use "/" as path seperator. Should change it to use filepath.Join

**Environment**:
Windows
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
