### ISSUE TITLE
Mount in windows does not check the source path exist or not

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#73332]
/sig-windows

**What happened**:

In testing local volume on Windows, notice that if the local volume path does not exist, the mount function in mount_windows does not check it and mount will succeeded. But pod will be stuck in CreateContainer phase since the pod volume will be linked to an non-exist path. 

**What you expected to happen**:
mount operation should fail and log the error message if local volume path does not exist.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
I will take a look at this issue

**Comment by jingxu97** [comment]
@andyzhangx thanks for your help!

**Comment by michmike** [comment]
thanks @yujuhong . we will track this for GA

**Comment by andyzhangx** [comment]
@jingxu97 could you provide more details?

I tried with following example: https://github.com/andyzhangx/demo/blob/master/windows/local, if specify a not existing dir:
```
  local:
    path: `c:\notexists`
```

I will get following error, is that error what we are expecting on Windows?
```
Events:
  Type     Reason       Age                 From                 Message
  ----     ------       ----                ----                 -------
  Normal   Scheduled    95s                 default-scheduler    Successfully assigned default/aspnet-local to 2423k8s000
  Warning  FailedMount  92s (x25 over 95s)  kubelet, 2423k8s000  MountVolume.NewMounter initialization failed for volume "pv-local" : path "c:\\notexists" does not exist
```

**Comment by jingxu97** [comment]
@andyzhangx In the path, I used \noexist or /noexist without a letter. From the log the MountVolume operation succeeded and I can see a local volume directory is created. 
However, the event of the pod does give an error message: Error: CreateFile c:\var\lib\kubelet\pods\e0b06368-258f-11e9-8a95-42010a280002\volumes\kubernetes.io~local-volume\example-local-pv-noexist: The system cannot find the file specified.
Also after I deleted this pod, the pod directory still exist, it is not getting cleaned up.


I also tried with your example to add a disk letter in the Path, the log shows that the MountVolume operation failed, but the cause of the failure is not very clear  "MountVolume.SetUp failed for volume \"example-local-pv-noexist\" (UniqueName: \"kubernetes.io/local-volume/1d1ecdce-258e-11e9-8a95-42010a280002-example-local-pv-noexist\") pod \"local-noexist-pod2\" (UID: \"1d1ecdce-258e-11e9-8a95-42010a280002\") : exit status 1" 
In this case, the pod directory can be cleaned up after pod is deleted.

**Comment by brusMX** [comment]
@jingxu97 just tested this scenario on kubernetes `v1.14.0-alpha.2` and it seems to be working properly now.
I have created the following `pv.yaml`:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-local
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /noexist  # use c:\ after path translation or `c:\dir`
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 1865k8s000
```

And in the pod I get the following pod description:

```yaml
Name:               aspnet-local
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               1865k8s000/10.240.0.4
Start Time:         Thu, 28 Feb 2019 19:42:02 +0000
Labels:             <none>
Annotations:        <none>
Status:             Pending
IP:
Containers:
  aspnet-local:
    Container ID:
    Image:          microsoft/aspnet:4.7.2-windowsservercore-1803
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from data-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2c4v6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pvc-local
    ReadOnly:   false
  default-token-2c4v6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2c4v6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=windows
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
  Type     Reason       Age                   From                 Message
  ----     ------       ----                  ----                 -------
  Normal   Scheduled    6m53s                 default-scheduler    Successfully assigned default/aspnet-local to 1865k8s000
  Warning  FailedMount  16s (x11 over 6m28s)  kubelet, 1865k8s000  MountVolume.NewMounter initialization failed for volume "pv-local" : path "\\noexist" does not exist
  Warning  FailedMount  15s (x3 over 4m50s)   kubelet, 1865k8s000  Unable to mount volumes for pod "aspnet-local_default(eb809a4d-3b90-11e9-924b-000d3af3f915)": timeout expired waiting for volumes to attach or mount for pod "default"/"aspnet-local". list of unmounted volumes=[data-volume]. list of unattached volumes=[data-volume default-token-2c4v6]
```

Which seems to be the right behavior.  I also tried `\noexists` and other stuff.
