### ISSUE TITLE
Missing PodTemplate documentation on usage

### ISSUE THREAD

**Issue by mydockergit** [kubernetes/kubernetes#73343]
Hi,

I saw [here ](https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#pod-templates)that there is a PodTemplate object.  
I created one:  
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: PodTemplate
metadata:
  name: pod-test
  namespace: default
template:
  metadata:
    name: pod-template
  spec:
    containers:
    - name: container
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "echo \"blabla\"; sleep 100"]
EOF
```

But how can I link it to DaemonSet or other object that will create this Pod?  
The documentation doesn't specify exactly how to use it.  

Can you please advise how to use it to create a Pod?  
Because I don't see what is the reason for this object to be created if it doesn't do anything.
