### ISSUE TITLE
AWS NLB with externalTrafficPolicy: Local: Health check defaults take 90s to remove node

### ISSUE THREAD

**Issue by kellycampbell** [kubernetes/kubernetes#73362]
**What happened**:

A Service with `externalTrafficPolicy: Local` and AWS NLB load balancer is very slow to recognize that a node fails health checks.

I created a DaemonSet and a Service with 

```
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
```

When one of the pods is restarted, the NLB still allows traffic to it (which is dropped causing connect timeout) for a minimum of 3 * 30s with the default health check settings.

**What you expected to happen**:

Preferably, the load balancer could recognize the failed node or pod sooner.

The minimum settings for NLB are documented here: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.7
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): 4.9.0-7-amd64
- Install tools: kops 1.11.0
- Others:
