### ISSUE TITLE
Need Windows CronJob tests

### ISSUE THREAD

**Issue by PatrickLang** [kubernetes/kubernetes#73415]
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

There aren't any tests available for this yet on Windows, and they're not in the conformance suite. We need a new test added or adapted to test this on Windows. It's mostly just a scheduling feature so I don't expect there to be any code work needed, just an e2e test.

/milestone v1.14
/sig windows

**Comment by benmoss** [comment]
I manually verified this with this:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: mcr.microsoft.com/windows/servercore:1803
            args:
            - powershell.exe
            - -command
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
          nodeSelector:
            beta.kubernetes.io/os: windows
          tolerations:
          - effect: NoSchedule
            key: windows
            operator: Equal
            value: "1803"
```

**Comment by benmoss** [comment]
Job is another api object that I tested too, super similar:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: mcr.microsoft.com/windows/servercore:1803
        args:
        - powershell.exe
        - -command
        - date; echo Hello from the Kubernetes cluster
      restartPolicy: OnFailure
      nodeSelector:
        beta.kubernetes.io/os: windows
      tolerations:
      - effect: NoSchedule
        key: windows
        operator: Equal
        value: "1803"
```
