### ISSUE TITLE
Cannot access service from within a pod

### ISSUE THREAD

**Issue by jiashenC** [kubernetes/kubernetes#73481]
**What happened**:
I have a simple Kubernetes Service standup and it is backed by a single Pod. I go inside the docker container for that Pod by `docker exec -it k8s_test_test-deployment-58b575b599-zlpb5_default_4cc8f312-23e1-11e9-acf6-0800273e509f_0 bash`. I try to `curl test` to access the Service, but it receives connection timeout error. I also test by `curl <Pod IP>:8080`, which works without any issue. 

**What you expected to happen**:
`curl test` or `curl <service name>` also works without any issue inside the container. 

**How to reproduce it (as minimally and precisely as possible)**:
I use `minikube` on MacOS to test the Kubernetes setup. Below are my k8s config file and docker file. You can build a very simple test image `docker build --tag=test .` and test it in your environment. 

`config.yml`
```yaml
kind: Service
apiVersion: v1
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: test
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
```

`Dockerfile`
```Dockerfile
FROM ubuntu

WORKDIR /server

COPY . /server

RUN apt-get update && apt-get install -y build-essential \
    python \
    python-dev \
    python-pip \
    curl \
    telnet \
    traceroute


EXPOSE 8080

CMD python -m SimpleHTTPServer 8080
```

**Anything else we need to know?**:
I use `nslookup test`, and it returns the correct Service IP attached to `test`. I don't think this issue has anything to do with DSN service. 

`curl -v test` prints out the following error.
> Rebuilt URL to: test/
Trying 10.105.63.204...
TCP_NODELAY set
connect to 10.105.63.204 port 80 failed: Connection timed out
Failed to connect to test port 80: Connection timed out
Closing connection 0
curl: (7) Failed to connect to test port 80: Connection timed out

Here is my original post on [StackOverflow](https://stackoverflow.com/questions/54408291/kubernetes-service-not-able-to-curl-itself-inside-docker). 

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
```
MacOS Mojave 10.14.2
```
- Kernel (e.g. `uname -a`): 
```
Darwin Jiashens-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```
- Install tools: 
```
brew install kubernetes-cli
```
- Others:
