### ISSUE TITLE
Prevent ingress from using TLS v1.2

### ISSUE THREAD

**Issue by snwfdhmp** [kubernetes/kubernetes#73579]
Hi,

I'm building an authentication system using a chipcard and card reader to log into my application.
For this intent, I need to use Client SSL Certificate Validation for 1. transmitting the CA to the client browser 2. the browser asks the user for his certificate 3. the browser connects using user's certificate.

I've noticed that Chrome (at least Chrome 71 and below) are not asking for Client's certificate when using TLS v1.2, therefore I'm trying to prevent ingress's nginx to use TLS v1.2.

Here is my configuration:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "mycompanyname-cryptocard-ingress"
  namespace: "mycompanyname-staging"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/auth-tls-verify-client: "on"
    ingress.kubernetes.io/auth-tls-secret: "mycompanyname-staging/cryptocard-certificate"
    ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    ingress.kubernetes.io/auth-tls-verify-depth: "4"
    ingress.kubernetes.io/server-snippet: |
      ssl_protocols TLSv1.1;
      ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:AES256+EDH;
  labels:
    name: "cryptocard-test.mycompanyname.fr"
spec:
  tls:
    - hosts:
        - "cryptocard-test.mycompanyname.fr"
      secretName: "wildcard.mycompanyname.fr"
  rules:
  - host: "cryptocard-test.mycompanyname.fr"
    http:
      paths:
      - path: /
        backend:
          serviceName: "mycompanyname-api-main"
          servicePort: 8765
```

This is unfortunately not working : even if `ssl_protocols TLSv1.1;` suggests that I'm wanting to use only TLSv1.1, this is what I receive from `curl -v https://cryptocard-test.mycompanyname.fr`

```
*   Trying 71.22.13.57...
* TCP_NODELAY set
* Connected to cryptocard-test.mycompanyname.fr (71.22.13.57) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=FR; L=CITY; O=MYCOMPANYNAME; OU=MYCOMPANYNAME; CN=*.mycompanyname.fr
*  start date: Feb 26 00:00:00 2018 GMT
*  expire date: Feb 26 12:00:00 2020 GMT
*  subjectAltName: host "cryptocard-test.mycompanyname.fr" matched cert's "*.mycompanyname.fr"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=Thawte RSA CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f8303000400)
> GET / HTTP/2
> Host: cryptocard-test.mycompanyname.fr
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 404 
< server: nginx/1.15.5
< date: Thu, 31 Jan 2019 10:07:56 GMT
< content-type: application/json
< content-length: 77
< strict-transport-security: max-age=15724800; includeSubDomains
< 
```

You can see that TLSv1.2 is used anyway.

I don't what the cause is, however I tried to downgrade nginx to the latest version that does not support TLSv1.2, that is `nginx/1.13.5`. My current (you can check above) was `nginx/1.15.5` (current official used on GKE).

This is the result :

```
* Rebuilt URL to: https://cryptocard.mycompanyname.fr/
*   Trying 91.347.232.3...
* TCP_NODELAY set
* Connected to cryptocard.mycompanyname.fr (91.347.232.3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.1 (IN), TLS handshake, Certificate (11):
* TLSv1.1 (IN), TLS handshake, Server key exchange (12):
* TLSv1.1 (IN), TLS handshake, Request CERT (13):
* TLSv1.1 (IN), TLS handshake, Server finished (14):
* TLSv1.1 (OUT), TLS handshake, Certificate (11):
* TLSv1.1 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.1 (OUT), TLS change cipher, Client hello (1):
* TLSv1.1 (OUT), TLS handshake, Finished (20):
* TLSv1.1 (IN), TLS change cipher, Client hello (1):
* TLSv1.1 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.1 / ECDHE-RSA-AES256-SHA
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=FR; L=CITY; O=MYCOMPANYNAME; OU=MYCOMPANYNAME; CN=*.mycompanyname.fr
*  start date: Feb 26 00:00:00 2018 GMT
*  expire date: Feb 26 12:00:00 2020 GMT
*  subjectAltName: host "cryptocard.mycompanyname.fr" matched cert's "*.mycompanyname.fr"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=Thawte RSA CA 2018
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: cryptocard.mycompanyname.fr
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Server: nginx
< Date: Thu, 31 Jan 2019 10:14:38 GMT
< Content-Type: text/html
< Content-Length: 246
< Connection: close
< Strict-Transport-Security: max-age=15724800; includeSubDomains;
< 
```

You can see that nginx is downgrading protocol from TLSv1.2 to TLSv1.1.

My questions is: since annotations are not doing the job, how to disable TLSv1.2 usage without downgrading nginx (which is a **terrible** practice !) ?

Thank you for your time
