### ISSUE TITLE
Ingress IP does match with the service ip of the Nginx ingress controller

### ISSUE THREAD

**Issue by sooryamanian91** [kubernetes/kubernetes#73591]
Deployed a ingress-controller-service using the following yaml
```
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https

---
```
```
kubectl get svc -n ingress-nginx
NAME            TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                      AGE
ingress-nginx   LoadBalancer   10.71.244.45   35.188.238.102   80:30540/TCP,443:31954/TCP   38m
```
The ingress is supposed to identify the external ip of the ingress-controller, which in the above case `35.188.238.102` , but it is grabbing some random ip.
```
kubectl get ingress
NAME      HOSTS     ADDRESS          PORTS     AGE
nginx     *         35.244.177.229   80, 443   18m
```

```
kubectl get nodes -o wide
NAME                                           STATUS    ROLES     AGE       VERSION         EXTERNAL-IP     OS-IMAGE                             KERNEL-VERSION   CONTAINER-RUNTIME
cluster-default-pool-46cc3182-f8mv   Ready     <none>    93d       v1.11.5-gke.5   35.245.123.89   Container-Optimized OS from Google   4.14.65+         docker://17.3.2
```
