### ISSUE TITLE
Secret can be deleted when referenced by Ingress

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes/kubernetes#73615]
**What happened**:
The tls secret can be deleted without any validation when it's referenced by an Ingress.

**What you expected to happen**:
Deletion should not allowed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a secret 
```
k create secret generic ingress-tls --from-file=tls.crt=/home/ubuntu/certs/ca.crt --from-file=tls.key=/home/ubuntu/certs/ca.key
```

2. Create an Ingress using the secret as TLS certs.
```
cat <<EOF > ~/test_ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-octavia-ingress
  annotations:
    kubernetes.io/ingress.class: "openstack"
spec:
  tls:
  - hosts:
      - ingress.example.com
    secretName: ingress-tls
  rules:
  - host: ingress.example.com
    http:
      paths:
      - path: /ping
        backend:
          serviceName: hostname-server
          servicePort: 8080
EOF
kubectl apply -f ~/test_ingress.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: OpenStack
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`):
`Linux test-k8s-master 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Kubeadm
- Others:
