### ISSUE TITLE
NodePort quota also disallows services of type ClusterIP

### ISSUE THREAD

**Issue by Semoar** [kubernetes/kubernetes#73628]
**What happened**:
We deployed resource quotas to disallow services of type NodePort. Some teams had already deployed services with NodePorts/LoadBalancer. So they are above their limit. Now if we try to deploy a service of type ClusterIP, this is forbidden, although that is not restricted by resource quotas.

**What you expected to happen**:
I expect for a resource quota for NodePorts to only disallow NodePorts and have no influence on other services.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the following file:
```
apiVersion: v1
kind: Namespace
metadata:
  name: resource-quota
---
kind: Service
apiVersion: v1
metadata:
  name: nodeport
  namespace: resource-quota
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: foo
  type: NodePort
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default
  namespace: resource-quota
spec:
  hard:
    services.nodeports: 0
---
kind: Service
apiVersion: v1
metadata:
  name: clusterip
  namespace: resource-quota
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: foo
  type: ClusterIP
```

CLI Output is then:
```
namespace/resource-quota created
service/nodeport created
resourcequota/default created
Error from server (Forbidden): error when creating "resource-quota/example.yaml": services "clusterip" is forbidden: exceeded quota: default, requested: services.nodeports=0, used: services.nodeports=1, limited: services.nodeports=0
```

**Anything else we need to know?**: No

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"archive", BuildDate:"2018-12-19T11:31:06Z", GoVersion:"go1.11.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Tested on local setup (Vagrant). Discovered with older Kubernetes version on AWS
- OS (e.g. from /etc/os-release): Ubuntu respectively CoreOS
- Install tools: kubeadm respectively kops
