### ISSUE TITLE
Error resizing Azure Disk

### ISSUE THREAD

**Issue by stevenimle-honeywell** [kubernetes/kubernetes#73644]
**What happened**:
Tried to resize an Azure Disk PV and got an error. The Azure Disk type is Shared (so in a storage account) but the error was not that it could not be done, but:
```
Error expanding volume "<namespace>/<name>" of plugin kubernetes.io/azure-disk : invalid disk URI: https://<storage-account>.blob.core.windows.net/vhds/kubernetes-dynamic-pvc-<guid>.vhd
``` 

**What you expected to happen**:
Disk to be resized.

**How to reproduce it (as minimally and precisely as possible)**:
In an Azure based cluster with VMs spun up with Docker Machine (no specific configuration necessary here, basic will do) create a storage class like below:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: attached-hdd
parameters:
  kind: shared
  storageaccounttype: Standard_LRS
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Create a something that uses this storage class, then try to resize it.

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu 16.04.5 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): Linux <machine-name> 4.15.0-1036-azure #38~16.04.1-Ubuntu SMP Fri Dec 7 03:21:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: docker-machine + rke
- Others:
