### ISSUE TITLE
container's port specific hostIP is ignored, listens on all host's IPs instead

### ISSUE THREAD

**Issue by zerthimon** [kubernetes/kubernetes#73702]
**What happened**:
Followed https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#containerport-v1-core to configure container ports
```
        ports:
        - containerPort: 80
          hostIP: 10.20.20.1
          hostPort: 80
          name: http
          protocol: TCP
```
The settings `hostIP: 10.20.20.1` is ignored, container answers on all host's IPs
Services listening on port 80 on other IPs get overridden by container.

**What you expected to happen**:
Container answers only on `10.20.20.1`, services bound to other IPs with the same port continue answering.

**How to reproduce it (as minimally and precisely as possible)**:
I'm running nginx-ingress-controller daemonset with ports configured as above. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.2
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.4.0-141-generic
- Install tools: kubeadm
- Others:
