### ISSUE TITLE
Undocumented buggy EBS volume ID format

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes/kubernetes#73730]
**What happened**:
When defining persistence volume for EBS using static provisioning, there are two EBS volume ID formats that could be put in the pv spec:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: aws://us-east-1/vol-0d9ea1b8a5c318c12
    fsType: ext4
```

The `awsElasticBlockStore.volumeID` could be either be `aws://us-west-1/vol-035c45314fab68972` or `vol-035c45314fab68972`. And the first ID format is undocumented and buggy where:
1. It causes confusion where people could use problematic IDs and the volume still works. The following IDs both work:
   * `aws://us-west-1/vol-0d9ea1b8a5c318c12` <- volume is created in us-east-1, but identified as us-west-1 as part of the volume ID
   * `aws://unknown/vol-0d9ea1b8a5c318c12` <- using random string as region
1. The slash in the volume ID breaks global volume path by creating extra sub directories along the volume path:
   * Using the example spec, the global path of the volume will be `/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/aws/unknown/vol-0d9ea1b8a5c318c12`. There are two more directories (`aws` and `unknown`) created under `mount` directory. And a sane global path should be like `/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/mounts/vol-0d9ea1b8a5c318c12` when the second volume ID format is used.

**What you expected to happen**:
This is not causing any functional issue or misbehave. But the result of this behavior could cause confusing user experience and potential security issue when paths are interpreted/created unintentionally. 

This also have an impact on CSI migration on whether should this behavior be migrated to support both volume ID formats. 

Since the format is undocumented use case (correct me if im wrong), I suggest to not support volume ID in the format of `aws://{region}/{volumeID}` to prevent user confusing and unexpected directories in volume global path for static and dynamic provisioning. And CSI migration for EBS will only support `{volumeID}` as the only ID format

**How to reproduce it (as minimally and precisely as possible)**:
Creating the PV using above pv spec. And consume the pv using follow specs:
pvc:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100
```
pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: claim1
```
**Anything else we need to know?**:
The first ID format is also used by dynamic provisioning.

**Environment**:
- Kubernetes version (use `kubectl version`):v1.13
- Cloud provider or hardware configuration:aws
- Install tools:kops
- Others:

/cc @ddebroy @davidz627
