### ISSUE TITLE
Operations on custom resources with multiple versions fails when validating and mutating web hooks are configured on it

### ISSUE THREAD

**Issue by parhamdoustdar** [kubernetes/kubernetes#73752]
**What happened**:

Here is a brief explanation of my environment (I'll explain how to reproduce it in the relevant section below):

I'm on the latest stable 1.13, which is 1.13.2. I'm using `microk8s` to be able to test this on multiple versions.

I have both a ValidationWebHookConfiguration and mutatingWebHookConfiguration defined.

ValidatingWebhookConfiguration:
```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: application-validation-webhook-configuration
webhooks:
- clientConfig:
    caBundle: YXBpVmVyc2lvbjogYWRtaXNzaW9ucmVnaXN0cmF0aW9uLms4cy5pby92MWJldGExCmtpbmQ6IE11dGF0aW5nV2ViaG9va0NvbmZpZ3VyYXRpb24KbWV0YWRhdGE6CiAgbmFtZTogYXBwbGljYXRpb24tbXV0YXRpb24td2ViaG9vay1jb25maWd1cmF0aW9uCndlYmhvb2tzOgotIGNsaWVudENvbmZpZzoKICAgIGNhQnVuZGxlOiBhCiAgICBzZXJ2aWNlOiBudWxsCiAgICB1cmw6IGh0dHBzOi8vMTI3LjAuMC4xOjg0NDMvdjEvbXV0YXRlLWFwcGxpY2F0aW9ucwogIGZhaWx1cmVQb2xpY3k6IElnbm9yZQogIG5hbWU6IGFwcGxpY2F0aW9uCiAgcnVsZXM6CiAgLSBhcGlHcm91cHM6CiAgICAtICcqJwogICAgYXBpVmVyc2lvbnM6CiAgICAtICcqJwogICAgb3BlcmF0aW9uczoKICAgIC0gQ1JFQVRFCiAgICAtIFVQREFURQogICAgcmVzb3VyY2VzOgogICAgLSBhcHBsaWNhdGlvbnMK
    service: null
    url: https://127.0.0.1:8443/v1/validate-applications
  name: applications.shipper.booking.com
  failurePolicy: Ignore
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications

```

MutatingWebhookConfiguration:

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: application-mutation-webhook-configuration
webhooks:
- clientConfig:
    caBundle: YXBpVmVyc2lvbjogYWRtaXNzaW9ucmVnaXN0cmF0aW9uLms4cy5pby92MWJldGExCmtpbmQ6IE11dGF0aW5nV2ViaG9va0NvbmZpZ3VyYXRpb24KbWV0YWRhdGE6CiAgbmFtZTogYXBwbGljYXRpb24tbXV0YXRpb24td2ViaG9vay1jb25maWd1cmF0aW9uCndlYmhvb2tzOgotIGNsaWVudENvbmZpZzoKICAgIGNhQnVuZGxlOiBhCiAgICBzZXJ2aWNlOiBudWxsCiAgICB1cmw6IGh0dHBzOi8vMTI3LjAuMC4xOjg0NDMvdjEvbXV0YXRlLWFwcGxpY2F0aW9ucwogIGZhaWx1cmVQb2xpY3k6IElnbm9yZQogIG5hbWU6IGFwcGxpY2F0aW9uCiAgcnVsZXM6CiAgLSBhcGlHcm91cHM6CiAgICAtICcqJwogICAgYXBpVmVyc2lvbnM6CiAgICAtICcqJwogICAgb3BlcmF0aW9uczoKICAgIC0gQ1JFQVRFCiAgICAtIFVQREFURQogICAgcmVzb3VyY2VzOgogICAgLSBhcHBsaWNhdGlvbnMK

    service: null
    url: https://127.0.0.1:8443/v1/mutate-applications
  failurePolicy: Ignore
  name: applications.shipper.booking.com
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
```

I also have a CRD, which defines multiple versions. `v1` is the older version which we were using before Kubernetes supported versioning. Now that Kubernetes allows us to define multiple versions, we want to move to `v1alpha1`. That's why you will see the object being _served_ as `v1`, but not _stored_ as `v1`:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.shipper.booking.com
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  conversion:
    strategy: None
  group: shipper.booking.com
  names:
    categories:
    - all
    - shipper
    kind: Application
    listKind: ApplicationList
    plural: applications
    shortNames:
    - app
    singular: application
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            template:
              properties:
                clusterRequirements:
                  properties:
                    capabilities:
                      items:
                        type: string
                      type: array
                    regions:
                      items:
                        type: object
                      type: array
                  required:
                  - regions
                  type: object
                strategy:
                  properties:
                    steps:
                      items:
                        properties:
                          capacity:
                            properties:
                              contender:
                                maximum: 100
                                minimum: 0
                                type: integer
                              incumbent:
                                maximum: 100
                                minimum: 0
                                type: integer
                            required:
                            - incumbent
                            - contender
                            type: object
                          name:
                            type: string
                          traffic:
                            properties:
                              contender:
                                minimum: 0
                                type: integer
                              incumbent:
                                minimum: 0
                                type: integer
                            required:
                            - incumbent
                            - contender
                            type: object
                        required:
                        - name
                        - traffic
                        - capacity
                        type: object
                      type: array
                  required:
                  - steps
                  type: object
                values:
                  type: object
              required:
              - clusterRequirements
              - strategy
              - values
              type: object
          required:
          - template
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  - name: v1
    served: true
    storage: false
```

Now, if you create an Application like this:

```
  apiVersion: shipper.booking.com/v1alpha1
  kind: Application
  metadata:
    name: super-server
  spec:
    revisionHistoryLimit: 3
    template:
      chart:
        name: nginx
        repoUrl: https://storage.googleapis.com/shipper-demo
        version: 0.0.1
      clusterRequirements:
        regions:
        - name: local
      strategy:
        steps:
        - capacity:
            contender: 1
            incumbent: 100
          name: staging
          traffic:
            contender: 0
            incumbent: 100
        - capacity:
            contender: 100
            incumbent: 0
          name: full on
          traffic:
            contender: 100
            incumbent: 0
      values:
        replicaCount: 3
```

Now, if you restart the server and try to edit this application with `kubectl edit app super-server` (noting that the file you're editing has the version as `v1` and not `v1alpha1`), you will get an error like this:

```
Internal error occurred: no kind "Application" is registered for version "shipper.booking.com/v1" in scheme "k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:52"
```

Now, if you do the same edit, but change the version to `v1alpha1` by hand, all subsequent patches to this object will work without a problem, until the next restart.

The restart is very important: this problem is 100% reproducable after a restart. We have observed it happening in production as well, but the way to reproduce it without waiting for it to happen is to restart `kube-apiserver` and edit the application with `kubectl edit app super-server`.

Here is what we've found through our testing:

1. As I said before, this happens 100% after a restart.
2. Changing the version to `v1alpha1` by hand while editing causes `kubectl` to send a patch to the `v1alpha1` endpoint instead of the `v1` endpoint, and from then on there won't be any problems interacting with this object.
3. Step number 2 works per object only. In other words, if you do step 2 for `app1` and not `app2`, `app1` will not have a problem but `app2` will have problems.
4. If you add `namespaceSelectors` to the ValidatingWebhookConfiguration and MutatingWebhookConfiguration so that they don't apply to your Application objects anymore, it will solve the problem for all the objects in this cluster. This issue will not occur again for an indeterminable amount of time if you remove the `namespaceSelectors`. In other words, if you remove the `namespaceSelectors`, we've observed that the issue will happen, but within weeks or days.

Note that step 4 will fix the issue for *all* Applications, while step 2 will fix it for *only one* Application object.

**What you expected to happen**:

Sending a patch request to the `v1` endpoint should convert the object to `v1alpha1` and store it as `v1alpha1` instead of throwing an error about the version not defined. Also, having a ValidatingWebhookConfiguration and MutatingWebhookConfiguration shouldn't cause this to happen.

**How to reproduce it (as minimally and precisely as possible)**:

1. Use microk8s to get the latest Kubernetes version.
2. Download the attached tarball and untar it with `tar -xzf v1alpha1.tar.gz`
3. `cd` into the directory, and set up your environment by running the following commands:
    
    ```
    $ kubectl apply -f v.yaml
    $ kubectl apply -f m.yaml
    $ kubectl apply -f app-crd.yaml
    ```
    
4. Run the script called `test-kubernetes-application-bug.sh` which will reproduce the problem for you. Basically, you can also create an Application object with whatever version you like, restart the server, and edit it with `kubectl` to add a label.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.2
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64
- Install tools: microk8s
[v1alpha1.tar.gz](https://github.com/kubernetes/kubernetes/files/2832903/v1alpha1.tar.gz)
