### ISSUE TITLE
Kubectl does not update resource

### ISSUE THREAD

**Issue by corey-aloia-sap** [kubernetes/kubernetes#73785]
I am not sure if this is a bug with Istio, helm, or kubernetes. I originally noticed this with helm, but when trying to apply the file without using helm, I would expect my changes to be applied, but they aren't. Thanks!

**What happened**:
I installed istio using helm. I then went to update the Out of the box Metrics. I used `kubectl apply -f my-metrics.yaml`. It says it was configured, but nothing changed.

**What you expected to happen**:
I expected my changes to be visible when running `kubectl get metric tcpbytereceived -n istio-system -o yaml`

**How to reproduce it (as minimally and precisely as possible)**:
1) install istio using helm
2) apply the following yaml (adjust the namespace accordingly):
```
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: tcpbytereceived
  namespace: istio-system
spec:
  value: connection.received.bytes | 0
  dimensions:
    # reporter: conditional((context.reporter.kind | "inbound") == "outbound", "source", "destination")
    source_workload: source.workload.name | "unknown"
    # source_workload_namespace: source.workload.namespace | "unknown"
    # source_principal: source.principal | "unknown"
    # source_app: source.labels["app"] | "unknown"
    # source_version: source.labels["version"] | "unknown"
    destination_workload: destination.workload.name | "unknown"
    # destination_workload_namespace: destination.workload.namespace | "unknown"
    # destination_principal: destination.principal | "unknown"
    # destination_app: destination.labels["app"] | "unknown"
    # destination_version: destination.labels["version"] | "unknown"
    # destination_service: destination.service.name | "unknown"
    # destination_service_name: destination.service.name | "unknown"
    # destination_service_namespace: destination.service.namespace | "unknown"
    # connection_security_policy: conditional((context.reporter.kind | "inbound") == "outbound", "unknown", conditional(connection.mtls | false, "mutual_tls", "none"))
  monitored_resource_type: '"UNSPECIFIED"'
```
3) now run `kubectl get metric tcpbytereceived -n istio-system -o yaml` and observe that the file hasn't been change
4) apply the file again and notice that k8 says `metric.config.istio.io/tcpbytereceived unchanged`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): `Debian GNU/Linux 8 (jessie)`
- Kernel (e.g. `uname -a`): `Linux ptms-798799d878-phx97 4.14.96-coreos #1 SMP Mon Jan 28 05:16:10 -00 2019 x86_64 GNU/Linux`
- Install tools: helm
- Others:
