### ISSUE TITLE
Run command namespace issue with --dry-run and -o yaml 

### ISSUE THREAD

**Issue by rajeshdeshpande02** [kubernetes/kubernetes#73781]
**What happened**:
Below run command does consider namespace. It creates and save configuration without namespace in output file. 
    `kubectl run test-nginx --image=nginx --namespace=dev --dry-run -o yaml >> test-nginx.yaml`

If without checking output file someone create resource using create or apply command, resource always get created in default namespace.

**What you expected to happen**:
Run command when used with `–dry-run` and redirected yaml output to file, it should also save namespace if it is provided in command.

**How to reproduce it (as minimally and precisely as possible)**:

1.	Run below command:
`kubectl run test-nginx --image=nginx --namespace=dev --dry-run -o yaml >> test-nginx.yaml`
2.	check output file:
cat test-nginx.yaml
3.	you will not see namespace: dev in output file.

The output file looks like this:

Test-nginx.yaml
``` yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: test-nginx
  name: test-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: test-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: test-nginx
    spec:
      containers:
      - image: nginx
        name: test-nginx
        resources: {}
status: {}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-2
0T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-gke.3", GitCommit:"04ad69a117f331df6272a343b5d8f9e2aee5ab0c", GitTreeState:"clean", BuildDate:"20
19-01-10T00:39:15Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
