### ISSUE TITLE
Mixed protocols for Azure LoadBalancer is working as expected

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#73849]
**What happened**:

Mixed protocols LoadBalacer services are not supported by apiserver. It will decline those services with error "cannot create an external load balancer with non-TCP/UDP ports". Hence #67986 added another annotation `service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"` for this purpose. e.g.

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
  name: web
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer
```

However, this is still not working. The UDP LB rule is still not created by the above service.

**What you expected to happen**:

Both TCP and UDP rules created for the service.

**How to reproduce it (as minimally and precisely as possible)**:

Create a service with above annotation.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.1
- Cloud provider or hardware configuration:  azure
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/kind bug
/assign
