### ISSUE TITLE
Allocate PVC by selector

### ISSUE THREAD

**Issue by GeorgeLung** [kubernetes/kubernetes#73886]
**What would you like to be added**:
The ability to provider a selector for specifying a PersistentVolumeClaim as an alternative to claimName like below:
````
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: example-statefulset
      namespace: eap
    spec:
      replicas: 3
      template:
        metadata:
          labels:
            app: example-pod
        spec:
          containers:
          - name: example
            image: ...
            volumeMounts:
            - name: logs-dir
               mountPath: /var/log/container_logs
            volumes:
            - name: logsdir
               persistentVolumeClaim:
                selector:
                  matchLabels:
                     volume-type: logs
````
**Why is this needed**:
Example use case is mounting a local volume within multiple pods. Currently I have to create one PVC per node and reference this directly per node in each pod/template. This suggestion would enable pods/templates to be dynamically scheduled taking into account the availability of the PVCs.
