### ISSUE TITLE
HPA should work when configured multiple metrics but some of the metrics cannot be get

### ISSUE THREAD

**Issue by luoyan35714** [kubernetes/kubernetes#74052]
/sig autoscaling

HPA should work when configured multiple metrics but some of the metrics cannot be get.

The HPA supported multiple metrics, so i deployed like this 
```
metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  - type: Object
    object:
      metricName: http_requests
      target:
        kind: Service
        name: some-sample-app
      targetValue: 100
```

The cpu utilization metric depend on the metrics server, the http_requests metric depend on the custom metrics server.
But if one of the metrics server or custom metrics server not works, then the hpa will cannot get the metrics, and the whole hpa will not work. That doesn't make sense.

I know the HorizontalPodAutoscaler will calculate proposed replica counts for each metric, and then choose the one with the highest replica count.

So what i expected is if failed to get some of the metric then mark the replica for that metric to zero, and go on calculate  process. That means if part of the metrics not work, the rest of the metrics still work for the HPA.

Is there any configuration to support for this?
