### ISSUE TITLE
Watch not terminated on CRD deletion

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#74105]
Reproduced on 1.11.7 as well as master-ish (a92729a301c8928d8e108418e6e4625a9e0d6733)

Deleting a CRD doesn't seem to cause the API server to terminate watches referencing the corresponding CRs, but the watches also don't properly resume if the CRD is created again, meaning that you have to wait for watch timeouts to actually get new watch events.

We should probably kill open watches on CRD deletion, so that clients are notified and are forced to re-watch.  Either that, or seamlessly resume watches if a CRD is recreated.

### Minimal reproducer:

<details>
<summary>crd.yaml</summary>

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testcrds.metamagical.io
spec:
  group: metamagical.io
  version: v1
  names:
    kind: TestCRD
    plural: testcrds
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            count: {type: integer}
```

</details>
<details>
<summary>cr.yaml</summary>

```yaml
apiVersion: metamagical.io/v1
kind: TestCRD
metadata:
  name: testcr
spec:
  count: 3
```

</details>

1. Create the above CRD: `kubectl create -f crd.yaml`
2. Create the above CR: `kubectl create -f cr.yaml`
3. (elsewhere) `kubectl proxy`
4. `curl localhost:8001/apis/metamagical.io/v1/testcrds` and grab a resource version
5. (elsewhere) `curl localhost:8001/apis/metamagical.io/v1/testcrds?watch=1&resourceVersion=<above>`
6. `kubectl delete -f cr.yaml`
7. `kubectl delete -f crd.yaml`
8. `kubectl create -f crd.yaml`
9. `kubectl create -f cr.yaml`
10. Observe the lack of watch events

After watches time out, things can re-establish, but that can be a while.
