### ISSUE TITLE
RoleBinding not respected if talking to the kubelet directly

### ISSUE THREAD

**Issue by cespo** [kubernetes/kubernetes#74188]
**What happened**:
I am trying to retrieve container logs via the kubelet API but get a 403 'Forbidden'

`curl -k -H "Authorization: Bearer ${TOKEN}" https://<NODE-IP>:10250/containerLogs/<NAMESPACE>/<POD>/<CONTAINER>`

> Forbidden (user=system:serviceaccount:test-namespace:default, verb=get, resource=nodes, subresource=proxy)

This is my ClusterRole

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:node:proxy
rules:
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
```

And this is the RoleBinding
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:node:proxy
  namespace: test-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node:proxy
subjects:
- kind: ServiceAccount
  name: default
  namespace: test-namespace
```

Kubelet logs
```
[1785]: I0217 21:58:49.615095    1785 auth.go:111] Node request attributes: attrs=authorizer.AttributesRecord{User:(*user.DefaultInfo)(0xc4217ffe80), Verb:"get", Namespace:"", APIGroup:"", APIVersion:"v1", Resource:"nodes", Subresource:"proxy", Name:"ip-xxx-xxx-xxx-xxx.us-west-2.compute.internal", ResourceRequest:true, Path:"/containerLogs/test-namespace/php-apache-7854c9d7bb-w68qb/php-apache"}
[1785]: I0217 21:58:49.615187    1785 server.go:248] Forbidden (user=system:serviceaccount:test-namespace:default, verb=get, resource=nodes, subresource=proxy)
[1785]: I0217 21:58:49.615256    1785 server.go:799] GET /containerLogs/test-namespace/php-apache-7854c9d7bb-w68qb/php-apache: (197.611µs) 403
[1785]: goroutine 12551 [running]:
[1785]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc420872cb0, 0x193)
[1785]:         /workspace/anago-v1.12.3-beta.0.34+435f92c719f279/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:204 +0xd2
[1785]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc420872cb0, 0x193)
[1785]:         /workspace/anago-v1.12.3-beta.0.34+435f92c719f279/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:183 +0x35
[1785]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader(0xc4217926c0, 0x193)
[1785]:         /workspace/anago-v1.12.3-beta.0.34+435f92c719f279/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:201 +0x41
[1785]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc4217926c0, 0x193, 0xc421c00e00, 0x67, 0x4, 0xc421c00e00)
[1785]:         /workspace/anago-v1.12.3-beta.0.34+435f92c719f279/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:181 +0x46
[1785]: k8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0xc4217646f0, 0xc4217926c0, 0xc421764780)
[1785]:         /workspace/anago-v1.12.3-beta.0.34+435f92c719f279/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:249 +0x4a0
[1785]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc421764780, 0xc4217646f0, 0xc4217926c0)
[1785]:         /workspace/anago-v1.12.3-beta.0.34+435f92c719f279/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
[1785]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4209339e0, 0x44080c0, 0xc420872cb0, 0xc421bf5800)
[1785]:         /workspace/anago-v1.12.3-beta.0.34+435f92c719f279/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:274 +0x7eb
[1785]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x44080c0, 0xc420872cb0, 0xc421bf5800)
[1785]:         /workspace/anago-v1.12.3-beta.0.34+435f92c719f279/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
[1785]: net/http.HandlerFunc.ServeHTTP(0xc420cbba30, 0x44080c0, 0xc420872cb0, 0xc421bf5800)
[1785]:         /usr/local/go/src/net/http/server.go:1947 +0x44
[1785]: net/http.(*ServeMux).ServeHTTP(0xc42098b740, 0x44080c0, 0xc420872cb0, 0xc421bf5800)
[1785]:         /usr/local/go/src/net/http/server.go:2340 +0x130
[1785]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc4209339e0, 0x44080c0, 0xc420872cb0, 0xc421bf5800)
[1785]:         /workspace/anago-v1.12.3-beta.0.34+435f92c719f279/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:292 +0x4d
[1785]: k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc421263f40, 0x44080c0, 0xc420872cb0, 0xc421bf5800)
[1785]:         /workspace/anago-v1.12.3-beta.0.34+435f92c719f279/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:798 +0x104
[1785]: net/http.serverHandler.ServeHTTP(0xc420a508f0, 0x4408980, 0xc4212cdb20, 0xc421bf5800)
[1785]:         /usr/local/go/src/net/http/server.go:2697 +0xbc
[1785]: net/http.(*conn).serve(0xc420654e60, 0x4412540, 0xc4217ffb00)
[1785]:         /usr/local/go/src/net/http/server.go:1830 +0x651
[1785]: created by net/http.(*Server).Serve
[1785]:         /usr/local/go/src/net/http/server.go:2798 +0x27b
[1785]: logging error output: "Forbidden (user=system:serviceaccount:test-namespace:default, verb=get, resource=nodes, subresource=proxy)"
[1785]:  [curl/7.47.0 10.32.2.67:33734]
```

If I convert the RoleBinding in a ClusterRoleBinding the curl command works

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:node:proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node:proxy
subjects:
- kind: ServiceAccount
  name: default
  namespace: test-namespace
```

**What you expected to happen**:
Read container logs only for containers in my namespace

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl -n test-namespace exec -it <CONTAINER_NAME> bash

export TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`

curl -k -H "Authorization: Bearer ${TOKEN}" https://<NODE-IP>:10250/containerLogs/test-namespace/<POD>/<CONTAINER>
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.3
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS Stable
- Kernel (e.g. `uname -a`): Linux 4.14.96-coreos #1 SMP Mon Jan 28 05:16:10 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
- Install tools: Terraform
- Others:

@kubernetes/sig-api-machinery
