### ISSUE TITLE
ConfigMap in Ingress

### ISSUE THREAD

**Issue by fungiboletus** [kubernetes/kubernetes#74247]
**What would you like to be added**:

I would like to deploy an Ingress with configurations settings stored inside a ConfigMap.

**Proposed Solution:**

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host:
    valueFrom:
      configMapKeyRef:
        name: ingress-config
        key: INGRESS_HOST
  - http:
      paths:
      - path:
        valueFrom:
          configMapKeyRef:
            name: ingress-config
            key: INGRESS_PATH
        backend:
          serviceName: test
          servicePort: 80
```

**Why is this needed**:

I would like to share the same configurations for my various environments (testing, stage, production,…). Today I have to manually maintain a set of files or use a template system such as Helm. It would be nice to have such a feature in Kubernetes.

*This is a copy of #74201 because the discussion went off topic*.
