### ISSUE TITLE
Kubernetes loadbalancer with dedicated servers

### ISSUE THREAD

**Issue by rafalix1337** [kubernetes/kubernetes#74255]
I have a problem with setting kubernetes loadbalancer/ingress(under port 80 for example). I don't use with any cloud, just vps servers with only one ip per server. I'm was trying install traefik but i dont get external-ip - stuck on pending.

I have read that I need something what simulating loadbalancer so I installed MetalLB but it more dedicated from local network no vps servers and didn't work for me or i can't configure it. My config-map for MetalLB:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - node1_ip
      - node2_ip
      - node3_ip

```
What I should do to on that cluster to be able to expose websites under normal port type 80, or can using reverse proxy like traefik.
