### ISSUE TITLE
LoadBalncer Ingress: IP_address does not exist

### ISSUE THREAD

**Issue by rowshan** [kubernetes/kubernetes#74303]
Hi, I am trying to create a kafka service where I should be able to see the loadbalancer ingress ip but it is not there. here is my yaml file:
```
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: LoadBalancer


```

and here is the output.
```
$ kubectl create -f kafka-service.yml   
    service/kafka-service created   
 ```
``` 
$ kubectl describe  service kafka-service    

Name:                     kafka-service
Namespace:                default
Labels:                   app=kafka
                          name=kafka
Annotations:              <none>
Selector:                 app=kafka,id=0
Type:                     LoadBalancer
IP:                       10.103.120.110
Port:                     kafka-port  9092/TCP
TargetPort:               9092/TCP
NodePort:                 kafka-port  32244/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```
So from the above out put 
LoadBalancer Ingress: ip_address  is not exist

Even though the service is created but for the deployment I want to use this ip as KAFKA_ADVERTISED_HOST_NAME
Any idea what could be the solution.
