### ISSUE TITLE
Admission Webhook Review Requests Don't Include GVK in Raw Object

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#74373]
The admission webhook review requests seem not to include a GVK in the raw object.  It's included elsewhere in the review request, so it's generally not an issue, except that the unstructured codec *requires* GVKs to be present (it's not a technical requirement AFAICT, just a check done in the codec logic).  This means that trying to use `codec.Decode` or `json.Unmarshal` on an Unstructured fails.

A workaround in the mean time is to use `json.Unmarshal(data, &unstructuredObj.Object)`, but it would be nice if this just worked properly (fixes to the review request logic *and* the unstructured codec logic.

### Reproducer

<details>
<summary>server.go</summary>

```go
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
)

func main() {
	http.HandleFunc("/review", func(resp http.ResponseWriter, req *http.Request) {
		defer resp.WriteHeader(http.StatusInternalServerError)
		bodyRaw, err := ioutil.ReadAll(req.Body)
		if err != nil {
			panic(err)
			return
		}
		fmt.Println(string(bodyRaw))
	})

	fmt.Println("starting serving at /review")
	if err := http.ListenAndServeTLS("127.0.0.1:8675", "/tmp/serving.crt", "/tmp/serving.key", nil); err != nil {
		panic(err)
	}
}
```

</details>

<details>
<summary>hook.yaml</summary>

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: testcase
webhooks:
- name: testcase.metamagical.io
  rules:
  - apiGroups: ["*"]
    apiVersions: ["*"]
    operations: ["*"]
    resources: ["*"]
  clientConfig:
    caBundle: <ca here>
    url: "https://localhost:8675/review"
```

</details>

1. create serving CA and certs (at serving.crt and serving.key)
2. `go run server.go`
3. edit webhook with CA bundle
4. `kubectl create -f hook.yaml
5. Observe that the output object doesn't have GVK in the `object` field
6. Observe https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go#L324

**Environment**:
- Kubernetes version (use `kubectl version`): master-ish (a92729a301c8928d8e108418e6e4625a9e0d6733)

/sig api-machinery
