### ISSUE TITLE
CABundle in Webhook ClientConfig should be able to be referenced instead of a string

### ISSUE THREAD

**Issue by prometherion** [kubernetes/kubernetes#74409]
**What would you like to be added**:

Actually we got this spec:

```yaml
  - name: my-name.tld
    clientConfig:
      service:
        name: my-name
        namespace: my-namespace
        path: "/my-path"
      caBundle: BASE64ENCODEDSTRING
```

In my humble opinion, better to handle with a `secretRef`:

```yaml
  - name: my-name.tld
    clientConfig:
      service:
        name: my-name
        namespace: my-namespace
        path: "/my-path"
      caBundleSecretRef:
        name: secret-name
        namespace: secret-namespace
        key: "ca.tls"
```

**Why is this needed**:

Essentially I'm using `cert-gen` to handle with ease certificates and I faced some difficulties to handle webhook configuration with Helm due to certificates management: I have to pass an input value in order to fill correctly the `caBundle` field and it means multiple Helm executions, working with hooks and it's not so linear.
