### ISSUE TITLE
Daemon Set Pod can't be auto-recover after the node becomes schedulable

### ISSUE THREAD

**Issue by zrss** [kubernetes/kubernetes#74469]
**What happened**:

We `cordon` some nodes for updating the driver of device, and there is a Daemon Set A controlls pods running on all nodes

but some container of pods of daemon sets exit  during the updating process

and finally, we `uncordon` the updated nodes, but it ends with the `Unschedulable` status and can't be auto-recover

```
agent-2mz7w                       0/0       Unschedulable   0          4d        <none>           192.168.42.172   <none>
agent-47lpl                       0/0       Running         0          4d        192.168.42.143   192.168.42.143   <none>
agent-4krlm                       0/0       Running         0          3d        192.168.42.144   192.168.42.144   <none>
agent-4p62m                       0/0       Unschedulable   0          4d        <none>           192.168.42.185   <none>
```

ds update strategy is

```
  updateStrategy:
    type: OnDelete
```

**What you expected to happen**:

pods of ds can be auto-recover or is it that we aim to do like this

**How to reproduce it (as minimally and precisely as possible)**:

kill the container of pods of ds

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Major:"1", Minor:"9+", GitVersion:"v1.9.10"

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

CentOS

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zrss** [comment]
and the status of ds

```
status:
  currentNumberScheduled: 51
  desiredNumberScheduled: 51
  numberAvailable: 49
  numberMisscheduled: 0
  numberReady: 49
  numberUnavailable: 2
  observedGeneration: 1
  updatedNumberScheduled: 51
```
