### ISSUE TITLE
Azure internal loadbalaner is pending forever if subnet annotation is set to empty string

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#74497]
**What happened**:

When service is set with ILB annotation and empty string subnet, e.g.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: internal-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: ""
spec:
  type: LoadBalancer
  ...
```

The service would be pending forever with following error:

```sh
network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"MissingJsonReferenceId","message":"Value for reference id is missing. Path properties.frontendIPConfigurations[0].properties.subnet."}]
```

**What you expected to happen**:

ILB should be provisioned successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/kind bug
/assign
