### ISSUE TITLE
[sig-network] DNS configMap nameserver [IPv4] tests failing

### ISSUE THREAD

**Issue by smourapina** [kubernetes/kubernetes#74543]
**Which jobs are failing**:
* [gce-new-master-upgrade-master](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master)
* [gce-new-master-upgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster)

**Which test(s) are failing**:

Job | Test 
--- | --- 
[gce-new-master-upgrade-master](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master) | [DNS configMap nameserver [IPv4] Change stubDomain should be able to change stubDomain configuration [Slow][Serial]](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/2255)
[gce-new-master-upgrade-master](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master) | [DNS configMap nameserver [IPv4] Forward PTR lookup should forward PTR records lookup to upstream nameserver [Slow][Serial]](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/2255)	
[gce-new-master-upgrade-master](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master)	| [DNS configMap nameserver [IPv4] Forward external name lookup should forward externalname lookup to upstream nameserver [Slow][Serial]](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/2255)	
[gce-new-master-upgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster) |	[DNS configMap nameserver [IPv4] Change stubDomain should be able to change stubDomain configuration [Slow][Serial]](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2809)	
[gce-new-master-upgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster) | [DNS configMap nameserver [IPv4] Forward PTR lookup should forward PTR records lookup to upstream nameserver [Slow][Serial]](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2809) 
[gce-new-master-upgrade-cluster](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster)| [DNS configMap nameserver [IPv4] Forward external name lookup should forward externalname lookup to upstream nameserver [Slow][Serial]](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2809) 

**Reason for failure**:
```
dig result did not match: []string{";; connection timed out; no servers could be reached"}
```

**Since when has it been failing**:
- `gce-new-master-upgrade-master`: since 2019-02-21
- `gce-new-master-upgrade-cluster`: since 2019-02-23

**Anything else we need to know**:
- `gce-new-master-upgrade-master`: Coincides with k/k commit [96043d91a](https://github.com/kubernetes/kubernetes/commit/96043d91a).
- `gce-new-master-upgrade-cluster`: Coincides with k/k commit [96043d91a](https://github.com/kubernetes/kubernetes/commit/96043d91a)

cc @mortent @kacole2 @alejandrox1 @mariantalla

/kind failing-test
/priority important-soon
/sig network
/milestone 1.14

**Comment by mariantalla** [comment]
Related to 1.14:
/milestone v1.14

**Comment by mariantalla** [comment]
Hey @kubernetes/sig-network-bugs - could you help with this one please? It's failing in release blocking upgrade tests at the moment, which is concerning as we approach code freeze.

**Comment by mariantalla** [comment]
Example (and first) failure: [build 2255](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/2255).

**Comment by bowei** [comment]
cc: @prameshj @bowei

**Comment by prameshj** [comment]
Are these tests expected to pass? From looking at test grid, I can't see any successful runs.
https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master&width=5

This is modifying configmap to include a coredns Corefile.
@fturib @johnbelamaric

**Comment by fturib** [comment]
@rajansandeep : can you have a look here ? I thought these failing UT were fixed

**Comment by rajansandeep** [comment]
@bowei @fturib @prameshj 
There were similar failures for https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-serial and the tests were fixed via https://github.com/kubernetes/kubernetes/pull/74371.

I went through the logs of the current test failures in https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-master&width=5 and it seems like the PR changes which fixed the above issue in `gci-gce-serial` hasn't been applied.

**Comment by fturib** [comment]
I understand these failing tests are build fron the 1.14 branch. Maybe we should cherry pick in that branch the fix that was committed in master (#74371)

**Comment by bowei** [comment]
Nevermind :-) I'm assuming you guys will be investigating

**Comment by fturib** [comment]
@bowei : investigation is done.
* these 2 failing e2e test are running from the branch v1.14.
* We had those same test failing in Master earlier last week.
* It was fixed in master last week by @rajansandeep - see #74371 

**We need that this PR to be ported in the branch v1.14.**

@smourapina - who can do the cherrypick of #74371 into branch v1.14 ?

**Comment by mariantalla** [comment]
Interesting; because it's the v1.14 branch, the daily fast forward from master should have picked it up. I'll look through history for commits forwarded to the v1.14 branch.

**Comment by fturib** [comment]
@rajansandeep : can you double check, now if I open the [e2e test in v1.14 branch](https://github.com/kubernetes/kubernetes/blob/release-1.14/test/e2e/network/dns_configmap.go), the expected change is in (I mean the `health` plugin in the config)

see : https://github.com/kubernetes/kubernetes/blob/e5777aab95e5c48f6645044f822e891ccbc2dcea/test/e2e/network/dns_configmap.go#L69

**Comment by rajansandeep** [comment]
@fturib @mariantalla Yes, I see that the changes for the fix are there in the v1.14 branch, but when I see the logs of the (latest) failed tests, the changes aren't reflected.
Maybe I missing something here.

**Comment by MrHohn** [comment]
@rajansandeep @fturib I recalled that these jobs are actually running 1.13 tests against 1.14 cluster. The procedure for `gce-new-master-upgrade-master` is something like:
1. Create a cluster using HEAD (this is 1.14 now)
2. Run upgrade test which will upgrade the master (and some other sanity checks in parallel).
3. After the uprade test is done, run 1.13 tests against the upgraded cluster. **<- This is failing**

For this upgrade job to pass, we may need to backport #74371 to 1.13 (if that makes sense)?

**Comment by MrHohn** [comment]
Sorry messed up some numbers in previous comment, edited now.

**Comment by fturib** [comment]
I have several questions to clarify:
1- What is the upgrade happening here ? I mean: I understand the upgrade of code for kubelet, kube-proxy etc, but I would not think it change the CoreDNS deployment. (unless we use `kbeadm upgrade` process maybe ..)
2- if the cluster is now in v 1.14, why are we running the v1.13 tests instead of the v1.14 tests ? 
3- if we backport the change in v1.13 ... these changes needs to be compatible with the deployment of v1.13 - because v1.13 is still alive and the CI still running everyday.  (in current case I think we are). But what will happen if it is not ?

**Comment by MrHohn** [comment]
> 1\. What is the upgrade happening here ? I mean: I understand the upgrade of code for kubelet, kube-proxy etc, but I would not think it change the CoreDNS deployment. (unless we use `kbeadm upgrade` process maybe ..)

For this specific master upgrade job, upgrade means turning down the 1.13 master and bringing up a new 1.14 master with the downloaded k8s bundle. As coredns deployment is included in the bundle, it will be upgraded by the addon manager.

> 2\. if the cluster is now in v 1.14, why are we running the v1.13 tests instead of the v1.14 tests ?

Not sure what the official answer would be, my quick thought is we are trying to ensure the old stuffs still work after upgrade. Note that we have a separate set of upgrade jobs that do the opposite --- running 1.14 tests against 1.14 cluster (e.g. [gce-new-master-upgrade-cluster-new](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new)).

> 3\. if we backport the change in v1.13 ... these changes needs to be compatible with the deployment of v1.13 - because v1.13 is still alive and the CI still running everyday.  (in current case I think we are). But what will happen if it is not ?

Yeah that is correct, if these changes are not compatible, we should figure out other ways instead of backporting those.

**Comment by fturib** [comment]
I agree with description of @MrHohn . 
After diving in the infra-test

- k8s-stable1 : release-1.13
- using 2 extracts (the execution will happen in second one, unless the option "--skew" is provided. Which is not the case here.
      - --extract=ci/latest
      - --extract=ci/k8s-stable1

```
- interval: 2h
  name: ci-kubernetes-e2e-gce-new-master-upgrade-cluster
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      # TODO: This is pinned to the 1.8 version of etcd. 1.9 was changed to
      # 3.1.x. ETCD doesn't downgrade minor versions. So for downgrades, we
      # pin this to the lower version. The long term fix is to change
      # downgrade/upgrade to not upgrade/downgrade etcd.
      - --env=TEST_ETCD_VERSION=3.0.17
      # In 1.11 influxdb is no longer deployed by default.
      - --env=KUBE_ENABLE_CLUSTER_MONITORING=standalone
      - --extract=ci/latest
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Slow\]|\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/latest
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190220-615bdbe2e-master
```
