### ISSUE TITLE
kubectl: need to opt into deleting with propagationPolicy: Foreground

### ISSUE THREAD

**Issue by phillipao** [kubernetes/kubernetes#74609]
blockOwnerDeletion did not block owner deletion.

gc.sh:
```
#!/bin/bash
set -euo pipefail

foo="cmfoo"
crname="cr"

main() {
  local cmfooyaml
  cmfooyaml="$(sed -e "s/NAME/${foo}/" cmfoo.yaml)"
  echo "$cmfooyaml" | kubectl apply -f -

  local uid
  uid=$(kubectl get clusterrole ${foo} -ojsonpath='{.metadata.uid}')

  local cryaml
  local end=64
  for i in $(seq 1 $end); do
    cryaml="$(sed -e "s/NAME/${crname}$i/" -e "s/FOOREF/${foo}/" -e "s/UID/${uid}/" cr.yaml)"
    echo "$cryaml" | kubectl apply -f -
  done

  kubectl delete clusterrole $foo --wait
  kubectl get clusterrole cr1 -oyaml && exit 1 || :

  for i in $(seq 1 $end); do
    kubectl delete clusterrole ${crname}${i} --ignore-not-found
  done
}

main
```

cmfoo.yaml:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: NAME
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
```

cr.yaml:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: NAME
  ownerReferences:
    - kind: ConfigMap
      apiVersion: v1
      name: FOOREF
      uid: UID
      blockOwnerDeletion: true
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
```

This is creating 64 ClusterRoles and giving them `ownerReference` to another ClusterRole ("cmfoo"). Then it deletes the owning ClusterRole. Then it tries to get one of the dependents, and expects the command to fail (because their owner was deleted).

But the script fails. It's able to get the dependent. When you try to get the ClusterRole by hand right after, it's gone. If you set `$end` to a smaller value (4), it passes. So it looks like this delete is happening asynchronously, though it's supposed to be synchronous.

**Environment**:
- Kubernetes version (use `kubectl version`): client: 1.13.3. server: 1.11.6-gke.2
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): debian
- Kernel (e.g. `uname -a`): 4.17
