### ISSUE TITLE
kubectl can't create Deployment "already exists" but can't delete Deployment "not found"

### ISSUE THREAD

**Issue by chadschommer** [kubernetes/kubernetes#74619]
**What happened**:
Unexpected results creating and deleting a deployment

commands as below:

```
$ kubectl get deployments
No resources found.

$ kubectl create -f deployment.yaml
Error from server (AlreadyExists): error when creating "deployment.yaml": deployments.apps "myapp" already exists

$ kubectl delete deployment myapp
Error from server (NotFound): deployments.extensions "myapp" not found

$ kubectl get deployments
No resources found.
```

kubectl does not find any deployments yet `kubectl create` fails saying the deployment already exists.  Upon attempting to delete the deployment kubectl fails saying that deployment is not found.

**What you expected to happen**:
If deployment already exists, delete should succeed. If deployment doesn't exist, create should succeed. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The errors appear to have a mismatch of apiGroups:
on create: `deployments.apps`
on delete: `deployments.extensions`

In a similar previous deployment I used `apiVersion: extensions/v1beta1` instead of the below `apiVersion`

deployments.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: architecture
  labels:
    tier: frontend
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - key: tier
        operator: In
        values:
          - frontend
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      imagePullSecrets:
        - name: mysecrets
      containers:
      - name: mycontainer
        image: myrepo:8082/myfolder/myapp:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
```
**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `AWS EKS`
- OS (e.g: `cat /etc/os-release`): `macOS 10.14.3`
- Kernel (e.g. `uname -a`): 
```
local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```
- Install tools:
- Others:
