### ISSUE TITLE
Metadata validation for CustomResources

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/kubernetes#74620]
We allow CRD authors to write [validation for CustomResources](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/customresources-validation.md). Currently we don't restrict writing validation for `metadata`, which means people can have [additive validation constraints to `metadata` after the built-in validation](https://github.com/kubernetes/kubernetes/blob/74036c082aeec92c196a887460d2aec0c060cd8e/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/validator.go#L55-L64).  

For example, people can have additive name constraints (require CR `metadata.name` to be `default`) with the following schema:

```
  validation:
   openAPIV3Schema:
     description: Foo CRD for Testing
     properties:
       metadata:
         description: Metadata of Foo
         properties:
           name:
             description: Name of Foo
             pattern: default
             type: string
```

This brings us two questions: 

1. how do we [publish CR validation schema](https://github.com/kubernetes/kubernetes/pull/71192) if "metadata" is included in the schema: 
  - simplest option is to publish standard metav1.ObjectMeta schema info, and use any CRD-specified "metadata" properties as additive validation (just like in-tree types do, publishing standard ObjectMeta schema info, and implementing type-specific name validation internally)
  - alternatively, we can try merging user-specified metadata schema with the standard one. Technically people should only add extra validation to existing metadata properties (adding new fields to metadata won't work since they will be pruned by built-in validation first), but it's unclear to me how arbitrary people may want the metadata validation to be

2. longer term question is whether to allow people specifying metadata validation at all, or just allow a subset (like name validation) in CRD v1

/sig api-machinery
/area custom-resources
cc @apelisse @lavalamp @liggitt @mbohlool @smarterclayton @sttts
