### ISSUE TITLE
Statefulset pods not rescheduled when node is powered off

### ISSUE THREAD

**Issue by srinathkotu** [kubernetes/kubernetes#74689]
**What happened**:
When node is powered off, statefulset pods go into terminating state but the pods don't get delete (which is the expected action according to @Huang-Wei in https://github.com/kubernetes/kubernetes/issues/72226) and those pods don't get rescheduled on another ready node.
**What you expected to happen**:
When node is powered off, the pods of a statefulset should be reschedule to another ready node.
**How to reproduce it (as minimally and precisely as possible)**:
Create a statefulset using the below yaml file
```yml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
```
Stop/delete one of the nodes running one/more of the pods
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux ip-10-96-24-27 4.4.0-1075-aws #85-Ubuntu SMP Thu Jan 17 17:15:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:
```
Have seen couple of issues "similar" to this issue on github regarding this but nothing of them seem to have been resolved, only closed without resolution due to inactivity(in most cases): 
https://github.com/kubernetes/kubernetes/issues/57838
https://github.com/kubernetes/kubernetes/issues/61263
```
