### ISSUE TITLE
dnsConfig rejects searches which have trailing period

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#74685]
**What happened**:

When I create a pod with specified dnsConfig, the validation says my spec is invalid.

```yaml
dnsConfig:
  nameservers:
  - 10.121.201.115
  - 10.127.219.115
  searches:
  - "example.com."
```

And the error is like below:

```
* spec.template.spec.dnsConfig.searches[0]: Invalid value: "example.": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**What you expected to happen**:

The spec should be accepted as it is totally fine to have trailing period.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.3
