### ISSUE TITLE
apiserver pod exist when first etcd node is down in externel etcd cluster

### ISSUE THREAD

**Issue by liaolinrong** [kubernetes/kubernetes#74718]
**What happened**:
I deploy a kubernetes cluster with kubeadm，use  external etcd cluster.
When first etcd node in the etcd cluster is down，apiserver pod exit.

**What you expected to happen**:
apiserver pod does not exit when first etcd node in the etcd cluster is down

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a 3 node etcd cluster.
Deploy kubernetes cluster use kubeadm with the etcd cluster.
Kill fist etcd node in the etcd cluster, then apiserver in all nodes will exit.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.13.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
CentOS 7.3.1611
```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
CentOS 
- Kernel (e.g. `uname -a`):
```
uname -a
Linux k8s1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
kubeadm
- Others:
Docker version: 
1.13.1-91

**Comment by tanshanshan** [comment]
could you paste apiserver config and whether etcd cluster is healthy

**Comment by liucimin** [comment]
Hi would you like to show us the api-server exit log or error log?

**Comment by liaolinrong** [comment]
> could you paste apiserver config and whether etcd cluster is healthy

/etc/kubernetes/manifests/kube-apiserver.yaml 
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --service-node-port-range=1-65535
    - --enable-aggregator-routing=true
    - --authorization-mode=Node,RBAC
    - --advertise-address=192.168.48.201
    - --allow-privileged=true
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/etcd/pki/ca.pem
    - --etcd-certfile=/etc/etcd/pki/client.pem
    - --etcd-keyfile=/etc/etcd/pki/client-key.pem
    - --etcd-servers=https://192.168.48.201:2379,https://192.168.48.202:2379,https://192.168.48.203:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    image: 192.168.48.204/kubernetes/kube-apiserver:v1.13.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 192.168.48.201
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /etc/etcd/pki
      name: etcd-certs-0
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /etc/etcd/pki
      type: DirectoryOrCreate
    name: etcd-certs-0
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
status: {}
```

etcd is healthy:
```
# etcdctl --endpoints=https://[192.168.48.202]:2379 --ca-file=/etc/etcd/pki/ca.pem --cert-file=/etc/etcd/pki/client.pem --key-file=/etc/etcd/pki/client-key.pem cluster-health
member 12cc60bd24046487 is healthy: got healthy result from https://192.168.48.203:2379
member 5f33758b28347f74 is healthy: got healthy result from https://192.168.48.202:2379
failed to check the health of member 6aa654c32e54e25f on https://192.168.48.201:2379: Get https://192.168.48.201:2379/health: dial tcp 192.168.48.201:2379: getsockopt: connection refused
member 6aa654c32e54e25f is unreachable: [https://192.168.48.201:2379] are all unreachable
cluster is healthy
```
