### ISSUE TITLE
Pod is deleted after failed Job when used with "restartPolicy: OnFailure"

### ISSUE THREAD

**Issue by r0bj** [kubernetes/kubernetes#74848]
**What happened**:

Pod is deleted after failed Job when used with `restartPolicy: OnFailure`. So there is no way to eg. check for errors, debug logs.

**What you expected to happen**:

Job failed but Pod is still present to be able to check for errors, debug logs, etc.

**How to reproduce it (as minimally and precisely as possible)**:

CronJob manifest:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cron-job
            image: alpine
            command:
            - /bin/sh
            - -c
            - exit 1
```

Job events:
```
Events:
  Type     Reason                Age                From            Message
  ----     ------                ----               ----            -------
  Normal   SuccessfulCreate      5m56s              job-controller  Created pod: test-1551540600-kb4lm
  Normal   SuccessfulDelete      10s                job-controller  Deleted pod: test-1551540600-kb4lm
  Warning  BackoffLimitExceeded  10s (x2 over 10s)  job-controller  Job has reached the specified backoff limit
```

Pod `test-1551540600-kb4lm` was deleted.

**Anything else we need to know?**:

Using `restartPolicy: Never` works as expected - failed Pods are still available after failed Job.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.5-gke.5", GitCommit:"2c44750044d8aeeb6b51386ddb9c274ff0beb50b", GitTreeState:"clean", BuildDate:"2019-02-01T23:53:25Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
