### ISSUE TITLE
StatefulSet's PersistentVolumeClaims have incorrect labels

### ISSUE THREAD

**Issue by llamasoft** [kubernetes/kubernetes#74916]
**What happened**:  
When creating a StatefulSet that uses volumeClaimTemplates, the resulting PersistentVolumeClaims have incorrect labels.  Instead of using the labels defined in their metadata, they use the labels from the StatefulSet's selector.

**What you expected to happen**:
I expect the created PersistentVolumeClaims to have the labels defined in their metadata.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: v1
kind: Service
metadata:
  name: bugdemo-service
  labels:
    app: bugdemo-service
    extraLabel: fromService
spec:
  ports:
    - name: nginx
      targetPort: 80
      port: 80
  clusterIP: None
  selector:
    app: bugdemo-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bugdemo-statefulset
  labels:
    app: bugdemo-statefulset
    extraLabel: fromStatefulSet
spec:
  selector:
    matchLabels:
      app: bugdemo-pod
  serviceName: bugdemo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: bugdemo-pod
        extraLabel: fromPodTemplate
    spec:
      containers:
      - name: bugdemo-nginx
        image: nginx:stable
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-data
            mountPath: /var/log/dummy
  volumeClaimTemplates:
    - metadata:
        name: nginx-data
        # In the resulting PersistentVolumeClaim, these
        # labels are replaced with the StatefulSet's selector
        labels:
          app: bugdemo-volumeclaim
          extraLabel: fromVolumeClaimTemplate
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: "1Gi"
```

Resulting PersistentVolumeClaim:

```
$ kubectl get pvc --show-labels
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE   LABELS
nginx-data-bugdemo-statefulset-0   Bound    pvc-7917ee4f-3ec7-11e9-917f-42010aXXXXXX   1Gi        RWO            standard       1m    app=bugdemo-pod
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.4", GitCommit:"618716cbb236fb7ca9cabd822b5947e298ad09f7", GitTreeState:"clean", BuildDate:"2019-02-05T19:22:29Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GKE
- Install tools: `kubectl`
- Others:

@kubernetes/sig-apps-apps . 
/sig apps
