### ISSUE TITLE
vSphere Cloud Provider fails to provision volumes when using tag based SPBM policy

### ISSUE THREAD

**Issue by mylesagray** [kubernetes/kubernetes#75040]
**What happened**:

When deploying PVCs against a StorageClass that uses a tag-based placement SPBM policy, volume provisioning fails with the following message:

```
kubectl describe pvc
Name:          hardy-ladybird-mongodb
Namespace:     default
StorageClass:  vmware-default
Status:        Pending
Volume:
Labels:        app=mongodb
               chart=mongodb-5.7.0
               heritage=Tiller
               release=hardy-ladybird
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/vsphere-volume
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type       Reason              Age               From                         Message
  ----       ------              ----              ----                         -------
  Warning    ProvisioningFailed  4s (x2 over 13s)  persistentvolume-controller  Failed to provision volume with StorageClass "vmware-default": default resource pool resolves to multiple instances, please specify
Mounted By:  hardy-ladybird-mongodb-7c8bf9b784-d2f9z
```

**What you expected to happen**:

Volume should be created on (one of) the Datastores that match the tag-based SPBM policy rule.

**How to reproduce it (as minimally and precisely as possible)**:

Tag a datastore with a tag group and tag as below:
![Datastore tag](https://dl.dropbox.com/s/l0wevj5a4vsz3rz/Screenshot%202019-03-06%2013.44.39.png)

Create a tag-based SPBM policy as below with the tag defined from the last step:
![SPBM Policy](https://dl.dropbox.com/s/joi5eugewq3zp6g/Screenshot%202019-03-06%2013.42.15.png?dl=0)

Datastores compliant with the above policy:
![Datastore compliance](https://dl.dropbox.com/s/aykyxil8tih0zx7/Screenshot%202019-03-06%2013.42.26.png?dl=0)

Datastore accessible from all hosts in all clusters:
![Datastore accessibility](https://dl.dropbox.com/s/he6zp4v14sm2g21/Screenshot%202019-03-06%2013.54.15.png?dl=0)

StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vmware-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters:
    storagePolicyName: "Container-Volumes"
```

**Anything else we need to know?**:

This environment is provisioned by PKS and is multi-AZ, the datastore in question is accessible by all hosts in each AZ. However, I don't believe this is a multi-AZ problem as when I change the StorageClass to the below it works (note, the datastore is the exact same one as in the tag-based SPBM policy):

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vmware-default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters:
    datastore: "iscsi-ds-0"
```

Perhaps it is a combination of multiple vSphere clusters and tag-based placement changes the datastore path that govmomi receives?

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: `VCP embedded in v1.12.5 as installed by PKS`

- OS (e.g: `cat /etc/os-release`): `Ubuntu 16.04.5 LTS`
- Kernel (e.g. `uname -a`): `4.15.0-42-generic`
- Install tools: `PKS`
- Others: runtime: `docker://18.6.3`

@kubernetes/sig-vmware-bug
