### ISSUE TITLE
error converting LeaderElectionConfiguration from external to internal type

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#75188]
**What happened**:

@pohly reported on slack that he is seeing this in the scheduler logs:
```
F0308 11:30:12.839840       1 server.go:65] unable to initialize command options: converting
(v1alpha1.LeaderElectionConfiguration) to (config.LeaderElectionConfiguration): type names
don't match (, bool), and no conversion 'func (*bool, bool) error' registered.
```

`LeaderElect` under `LeaderElectionConfiguration` seems to have a version with and without pointer in the external / internal types.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/config/types.go#L45

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/config/v1alpha1/types.go#L31

googling, i see traces of this problem going back to 2017:
https://groups.google.com/forum/#!msg/kubernetes-sig-api-machinery-pr-reviews/lGX1vtBYxuk/-VcgPXXECgAJ

/kind bug
/priority important-longterm
/sig api-machinery
@kubernetes/sig-api-machinery-bugs 
@kubernetes/wg-component-standard

**Comment by BenTheElder** [comment]
cc

**Comment by neolit123** [comment]
although i tried reproducing the problem myself and couldn't:
https://kubernetes.slack.com/team/U83J4CS3S

```
kind: Config
apiVersion: kind.sigs.k8s.io/v1alpha2
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta1
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "feature-gates": "VolumeSnapshotDataSource=true,BlockVolume=true,CSIBlockVolume=true"
    controllerManager:
      extraArgs:
        "feature-gates": "VolumeSnapshotDataSource=true,BlockVolume=true,CSIBlockVolume=true"
    scheduler:
      extraArgs:
        "feature-gates": "VolumeSnapshotDataSource=true,BlockVolume=true,CSIBlockVolume=true"
  - |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    metadata:
      name: config
    featureGates:
      VolumeSnapshotDataSource: true
      BlockVolume: true
      CSIBlockVolume: true
  - |
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    metadata:
      name: config
    featureGates:
      VolumeSnapshotDataSource: true
      BlockVolume: true
      CSIBlockVolume: true
```


```
NAMESPACE     NAME                                         READY   STATUS    RESTARTS   AGE
kube-system   coredns-ff8f79c87-5f7sb                      1/1     Running   0          116s
kube-system   coredns-ff8f79c87-79dm6                      1/1     Running   0          116s
kube-system   etcd-kind-control-plane                      1/1     Running   0          62s
kube-system   kube-apiserver-kind-control-plane            1/1     Running   0          44s
kube-system   kube-controller-manager-kind-control-plane   1/1     Running   0          65s
kube-system   kube-proxy-dnjcz                             1/1     Running   0          115s
kube-system   kube-scheduler-kind-control-plane            1/1     Running   0          67s
kube-system   weave-net-g42jd                              2/2     Running   1          115s
```

```
kind-control-plane   Ready    master   4m21s   v1.15.0-alpha.0.1081+583ff363fa1d2e-dirty
```

@pohly could you please provide more details for the ticket?
