### ISSUE TITLE
[Azure] controller-manager is stuck in deleting LB because it's unable to delete a failed service referencing a non-existent IP

### ISSUE THREAD

**Issue by weinong** [kubernetes/kubernetes#75198]
**What happened**:
controller-manager is stuck in deleting an incorrectly configured LB type service. it cannot be recovered until restarted.

**What you expected to happen**:
controller-manager should recover. At least it should allow us to create the service without restarting it.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "foobar"
spec:
  type: LoadBalancer
  loadBalancerIP: "51.145.136.123"
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: nginx-ingress
```
put a random IP in above yaml and make sure the resource group doen't exist.

```
kubectl apply -f svc.yaml
kubectl delete -f svc.yaml

kubectl get svc,event

NAME                    TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
service/kubernetes      ClusterIP      10.0.0.1      <none>        443/TCP                      10d
service/nginx-ingress   LoadBalancer   10.0.147.35   <pending>     80:32005/TCP,443:31028/TCP   14m

LAST SEEN   TYPE      REASON                       KIND      MESSAGE
16m         Normal    EnsuringLoadBalancer         Service   Ensuring load balancer
16m         Warning   CreatingLoadBalancerFailed   Service   Error creating load balancer (will retry): failed to ensure load balancer for service default/nginx-ingress: network.PublicIPAddres
sesClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<redacted>' with object id '<redacted>' does not have authorization to perform action 'Microsoft.Network/publicIPAddresses/read' over scope '/subscri
ptions/<redacted>/resourceGroups/foobar/providers/Microsoft.Network'."
3m40s       Normal    DeletingLoadBalancer         Service   Deleting load balancer
3m40s       Warning   DeletingLoadBalancerFailed   Service   Error deleting load balancer (will retry): network.PublicIPAddressesClient#List: Failure responding to request: StatusCode=403 -- O
riginal Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '<redacted>' with object id '<redacted>' does not have authorization to perform action 'Microsoft.Network/publicIPAddresses/read' over scope '/subscriptions/<redacted>/resourceGroups/foobar/
providers/Microsoft.Network'."
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.4
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
