### ISSUE TITLE
Kube Proxy IPVS Mode with ExternalIP resulting in disconnected workers (with itself loopback)

### ISSUE THREAD

**Issue by SeniuuS** [kubernetes/kubernetes#75290]
**What happened**:
I am using Kubernetes in my project to deploy and access my multiple backend API components. I installed it with kubeadm and kubectl. I have one master (192.168.101.7) and two nodes (192.168.101.4, 192.168.101.6). Everything is working fine with the default proxy mode of kube-proxy : iptables. I have deployed nginx-ingress and my API. The service for nginx-ingress is of type ExternalIPs (with 192.168.101.7) so I can access my API through a specific address : 192.168.101.7/api/ (where path is specific for each differents api component) and it is working. I am using flannel for the networking.

I wanted to set the kube-proxy mode to IPVS in order to have a real load balancing algorithm : round robin. (because iptables is using random and needs liveness/probeness to check if pods are alive)

I correctly enabled all the kernel mods and "ipvsadm" is working fine. Everything works fine when I use service of type nodeport : I can access my pods with a correct load balancing. (and ipvsadm is showing correctly the rules)

But when I try to deploy a service with ExternalIPs (nginx-ingress or my backend components) my nodes get disconnected from the master and I have a odd problem : From the nodes when I try to access the master it returns back to itself. That is when I do "ssh 192.168.101.7" from 192.168.101.4 and correctly login I arrive on 192.168.101.4 (itself) instead of 192.168.101.7. There seems to have a loopback to itself on each node after the deployment of the service with externalIPs.

I thought maybe it was caused by Flannel so I tried with WeaveWorks but it does the same.

The final result is that my nodes are disconnected from the master and I can't access my service anymore.

**What you expected to happen**:
I expected my nodes not being redirected to themselves.
And I expected to access my service from the externalIP of the master with the load balancing specified in ipvs.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
        advertiseAddress: 192.168.101.7
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
networking:
        podSubnet: 10.244.10.0/16
        serviceSubnet: 10.96.0.0/12
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
featureGates:
        SupportIPVSProxyMode: true
mode: ipvs
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.3
- OS (e.g: `cat /etc/os-release`): Debian 9
