### ISSUE TITLE
kube-controller-manager is stucking in deleting Azure LB because of wrong idle timeout set

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#75356]
**What happened**:

When the Idle Timeout annotation was set to "3" which isn't a supported case, kube-controller-manager is stuck in deleting Azure LB. New service with the same name couldn't be created again even without the annotation.

**What you expected to happen**:

New service should be created successfully.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: nginx
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "3"
spec:
  type: LoadBalancer
  loadBalancerIP: "51.145.136.123"
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app: nginx
```

```sh
kubectl create -f nginx.yaml
kubectl get svc

kubectl delete -f nginx.yaml
kubectl get svc

kubectl create -f nginx.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/kind bug
