### ISSUE TITLE
ScaleIO - SDC nodes never found

### ISSUE THREAD

**Issue by etrikp** [kubernetes/kubernetes#75409]
**What happened**:
ScaleIO Storage driver never finds any ScaleIO SDC nodes when attempting to mount a volume. All kubelets that can be SDC nodes are tagged with label.sdcGuid and a *capitalized* GUID of the sdc node. The issue appears to be using the attribute name SdcGUID instead of sdcGuid when parsing the response from the ScaleIO gateway.

**What you expected to happen**:
SDC nodes can be properly discovered so volumes can be mounted.

**How to reproduce it (as minimally and precisely as possible)**:
With a working ScaleIO cluster and ScaleIO gateway installed: Apply the following to 

Setup ScaleIO storage class:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: sio-secret 
type: kubernetes.io/scaleio 
data:
  username: 
  password: 

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: scaleio 
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/scaleio
parameters:
  gateway: https://0.0.0.0/api
  system: aln-vc01-cluster 
  protectionDomain: aln-vc01-pd 
  storagePool: aln-vc01-pool 
  secretRef: sio-secret
  fsType: ext4
```

Create PVC using ScaleIO
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sio-small
spec:
  storageClassName: scaleio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```
Use PVC in a POD
```
---
kind: Pod
apiVersion: v1
metadata:
  name: pod-sio-small
spec:
  containers:
    - name: pod-sio-small-container
      image: k8s.gcr.io/test-webserver
      volumeMounts:
      - mountPath: /test
        name: test-data
  volumes:
    - name: test-data
      persistentVolumeClaim:
        claimName: pvc-sio-small
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
VMWare 8cpu 16gb
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```Linux iops-k8s-control-0003 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux```
- Install tools:
- Others:
