### ISSUE TITLE
Kubernetes is not scaling up when volume node affinity requires a node in specific AZ (AWS)

### ISSUE THREAD

**Issue by fcappi** [kubernetes/kubernetes#75402]
**What happened**:

**K8s cluster:**
- 1 master (us-west-2a) not schedulable
- 1 node (us-west-2c)

**Node labels**
```
Roles:              node
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=m5.xlarge
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=us-west-2
                    failure-domain.beta.kubernetes.io/zone=us-west-2c
                    kubernetes.io/role=node
                    node-role.kubernetes.io/node=
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true

```
**volume node affinity (us-west-2a)**
```
Node Affinity:     
  Required Terms:  
    Term 0:        failure-domain.beta.kubernetes.io/zone in [us-west-2a]
                   failure-domain.beta.kubernetes.io/region in [us-west-2]

```

**Issue restoring volume (us-west-2a)**
```bash
Events:
  Type     Reason             Age               From                Message
  ----     ------             ----              ----                -------
  Warning  FailedScheduling   3s (x7 over 28s)  default-scheduler   0/2 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 1 node(s) had volume node affinity conflict.
  Normal   NotTriggerScaleUp  2s (x3 over 24s)  cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added)
```

As we can see the volume node affinity requires a node running on us-west-2a AZ, but there is only one node running on us-west-2c.

The cluster auto-scaler is not creating a new node at  us-west-2a to satisfy the node affinity conditions.

**What you expected to happen**:
A new node to be created at us-west-2a, so the volume could be attached to it.

**How to reproduce it (as minimally and precisely as possible)**:
I'm using Heptio Velero to backup the cluster.
So in a cluster defined as below, I create a backup using velero:
- 1 master (us-west-2a) not schedulable
- 1 node (us-west-2a)

Then I delete the cluster and create a new one where the node AZ is different from the previous cluster (but the region is the same).
- 1 master (us-west-2a) not schedulable
- 1 node (us-west-2c)

Then I use Velero to restore the backup, and kubernetes is not able schedule a node to attach the volume

**This is the resources that were backed up and restored.**
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example
  labels:
    app: nginx

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-logs
  namespace: nginx-example
  labels:
    app: nginx
spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        pre.hook.backup.velero.io/container: fsfreeze
        pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/var/log/nginx"]'
        post.hook.backup.velero.io/container: fsfreeze
        post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/var/log/nginx"]'
    spec:
      volumes:
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: nginx-logs
      containers:
      - image: nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/var/log/nginx"
          name: nginx-logs
          readOnly: false
      - image: gcr.io/heptio-images/fsfreeze-pause:v0.11.0
        name: fsfreeze
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/var/log/nginx"
          name: nginx-logs
          readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx
  namespace: nginx-example
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer

```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): UBUNTU
- Kernel (e.g. `uname -a`): Linux lnxcit016980 4.8.0-41-generic #44~16.04.1-Ubuntu SMP Fri Mar 3 17:11:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
