### ISSUE TITLE
Network policies should be distributed on the order of creation

### ISSUE THREAD

**Issue by saiyan86** [kubernetes/kubernetes#75435]
**What would you like to be added**:

Network policies should be distributed on the order of creation. With this change, Kubernetes will remember the order of network policy events and distribute them to clients in a FIFO order.

**Why is this needed**:

On restart events, network policies will be distributed to informers on a random order. This is unfavorable behavior for network policy clients, since users apply network policies in certain orders to reflect their desired state of the network.

For example, users tend to apply a deny-all policy first, and then whitelist some traffic with subsequent network policies.

This policy is usually applied first:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```
And some whitelisting network policy is applied later:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-some-cidr
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 1.2.3.4/32
```
Like said before, on client restart events, the network policies will be distributed to clients in a random order, and does not reflect the original user intent.
