### ISSUE TITLE
An extra sandbox container created after job pod succeed

### ISSUE THREAD

**Issue by frost1990** [kubernetes/kubernetes#75441]
/sig node
/area kubelet

@dchen1107
@derekwaynecarr 

**What happened**:

I created a cronjob in a kubernetes cluster(version 1.13.1),  the configuration is shown  below:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

```
Every  minute kubernetes will create a job pod. But  when a job pod completes, sometimes I can find an extra sandbox container which runs the pause program. Here is an example,  job pod hello-1552914120-qvkpr created another sandbox container after the main container busybox completed and it's initial sandbox container was killed.

```
[root@10-9-187-57 ~]# docker ps -a
CONTAINER ID        IMAGE                                                                                       COMMAND                  CREATED             STATUS                       PORTS               NAMES
d69f9a0aac47        uhub.service.ucloud.cn/google_containers/pause-amd64:3.0                                    "/pause"                 4 seconds ago       Exited (137) 1 second ago                        k8s_POD_hello-1552914120-qvkpr_default_0920a1ff-497e-11e9-8aae-525400fa7819_1
cc527083a48f        docker.io/busybox@sha256:061ca9704a714ee3e8b80523ec720c64f6209ad3f97c0ff7cb9ec7d19f15149f   "/bin/sh -c 'date;..."   5 seconds ago       Exited (0) 4 seconds ago                         k8s_hello_hello-1552914120-qvkpr_default_0920a1ff-497e-11e9-8aae-525400fa7819_0
0abe74d2aa0f        uhub.service.ucloud.cn/google_containers/pause-amd64:3.0                                    "/pause"                 19 seconds ago      Exited (0) 4 seconds ago                         k8s_POD_hello-1552914120-qvkpr_default_0920a1ff-497e-11e9-8aae-525400fa7819_0
```
What's worse is that after the second sandbox container killed by kubelet, the CNI plugin cannot get the correct NETNS Path(/proc/$pausepid/net/ns) when it tries to tear down the network which is created for the extra second sandbox container. That will definitely result in IP leakage when the relationships between pod ip and pod name, namespace as well as sandbox container id,  are not stored in somewhere else.

**What you expected to happen**:

When a regular job pod completes and becomes Succeeded, no more extra sandbox containers will be created.

**How to reproduce it (as minimally and precisely as possible)**:

Just deploy an cronjob like this:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
And perform `docker ps -a` command on a node which is sheduled to run a single job.
You are likely to find the extra sandbox of the job pod.

**Anything else we need to know?**:
After some investigation, I suppose that something is wrong when SyncPod function starts.
https://github.com/kubernetes/kubernetes/blob/v1.13.1/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L585

It ignores the fact that the pod's status is completed,  becomes SUCCEEDED, and still creates an extra sandbox containers after the first sandbox is killed and related PLEG is activated.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux 10-9-29-155 4.4.169-1.el7.elrepo.x86_64 #1 SMP Fri Dec 21 09:54:06 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
- Others:
