### ISSUE TITLE
Restarting the pause container fails

### ISSUE THREAD

**Issue by akarasik** [kubernetes/kubernetes#75477]
**What happened**:
I run the kube-api server as a pod from a yaml file the kubelet manifests directory.
I configured it to run on the bridge network by setting `hostNetwork: false`, and I have port mapping from host's 6443 to containers 6443.
When updating this file, the pod could not be recreated.
In fact I can see many pause containers created, and being removed for that pod.
In the kubelet logs I can see those messages correlated with the pause containers creation:
> CreatePodSandbox for pod "kube-apiserver-mykubehost3.mycompany.com_kube-system(e447570a11168f7cb144ce1c48aee69f)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-apiserver-mykubehost3.mycompany.com": Error response from daemon: Address already in use

> Error syncing pod e447570a11168f7cb144ce1c48aee69f ("kube-apiserver-mykubehost3.mycompany.com_kube-system(e447570a11168f7cb144ce1c48aee69f)"), skipping: failed to "CreatePodSandbox" for "kube-apiserver-mykubehost3.mycompany.com_kube-system(e447570a11168f7cb144ce1c48aee69f)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-apiserver-mykubehost3.mycompany.com_kube-system(e447570a11168f7cb144ce1c48aee69f)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"kube-apiserver-mykubehost3.mycompany.com\": Error response from daemon: Address already in use"

When trying to pinpoint the issue, the simplest example to see the issue is when restarting a working pause container:
```
# docker ps | grep api
e592e679f351        gcr.io/google_containers/kube-apiserver-amd64                     "kube-apiserver --ap…"   8 minutes ago       Up 8 minutes                                 k8s_kube-apiserver_kube-apiserver-mykubehost3.mycompany.com_kube-system_e447570a11168f7cb144ce1c48aee69f_0
d25ca108c6b7        k8s.gcr.io/pause:3.1                                              "/pause"                 8 minutes ago       Up 8 minutes        0.0.0.0:6443->6443/tcp   k8s_POD_kube-apiserver-mykubehost3.mycompany.com_kube-system_e447570a11168f7cb144ce1c48aee69f_0
# docker restart d25ca108c6b7
Error response from daemon: Cannot restart container d25ca108c6b7: Address already in use
```

It created the following log lines in the for kubelet:
> <30>Mar 19 08:02:43 mykubehost3 kubelet[89518]: E0319 08:02:43.743872   89518 reflector.go:322] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to watch *v1.Service: Get https://1.2.3.4:6443/api/v1/services?resourceVersion=17119393&timeoutSeconds=430&watch=true: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:43 mykubehost3 kubelet[89518]: E0319 08:02:43.743872   89518 reflector.go:322] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to watch *v1.Node: Get https://1.2.3.4:6443/api/v1/nodes?fieldSelector=metadata.name%3Dmykubehost3.mycompany.com&resourceVersion=17120323&timeoutSeconds=373&watch=true: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:43 mykubehost3 kubelet[89518]: E0319 08:02:43.743872   89518 reflector.go:322] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to watch *v1.Pod: Get https://1.2.3.4:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dmykubehost3.mycompany.com&resourceVersion=17119518&timeoutSeconds=548&watch=true: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:44 mykubehost3 kubelet[89518]: E0319 08:02:44.744447   89518 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Get https://1.2.3.4:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:44 mykubehost3 kubelet[89518]: E0319 08:02:44.745270   89518 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Get https://1.2.3.4:6443/api/v1/nodes?fieldSelector=metadata.name%3Dmykubehost3.mycompany.com&limit=500&resourceVersion=0: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:44 mykubehost3 kubelet[89518]: E0319 08:02:44.746354   89518 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://1.2.3.4:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dmykubehost3.mycompany.com&limit=500&resourceVersion=0: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:44 mykubehost3 kubelet[89518]: W0319 08:02:44.926901   89518 docker_sandbox.go:372] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/kube-apiserver-mykubehost3.mycompany.com through plugin: invalid network status for
<30>Mar 19 08:02:44 mykubehost3 kubelet[89518]: W0319 08:02:44.929363   89518 pod_container_deletor.go:75] Container "d25ca108c6b7a7bee630fce1d12e0875330eea4faa1c5b3f33b495b088b7717e" not found in pod's containers
<30>Mar 19 08:02:45 mykubehost3 kubelet[89518]: E0319 08:02:45.062173   89518 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "mykubehost3.mycompany.com": Get https://1.2.3.4:6443/api/v1/nodes/mykubehost3.mycompany.com?resourceVersion=0&timeout=10s: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:45 mykubehost3 kubelet[89518]: E0319 08:02:45.062384   89518 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "mykubehost3.mycompany.com": Get https://1.2.3.4:6443/api/v1/nodes/mykubehost3.mycompany.com?timeout=10s: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:45 mykubehost3 kubelet[89518]: E0319 08:02:45.062586   89518 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "mykubehost3.mycompany.com": Get https://1.2.3.4:6443/api/v1/nodes/mykubehost3.mycompany.com?timeout=10s: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:45 mykubehost3 kubelet[89518]: E0319 08:02:45.062797   89518 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "mykubehost3.mycompany.com": Get https://1.2.3.4:6443/api/v1/nodes/mykubehost3.mycompany.com?timeout=10s: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:45 mykubehost3 kubelet[89518]: E0319 08:02:45.062997   89518 kubelet_node_status.go:391] Error updating node status, will retry: error getting node "mykubehost3.mycompany.com": Get https://1.2.3.4:6443/api/v1/nodes/mykubehost3.mycompany.com?timeout=10s: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:45 mykubehost3 kubelet[89518]: E0319 08:02:45.063011   89518 kubelet_node_status.go:379] Unable to update node status: update node status exceeds retry count
<30>Mar 19 08:02:45 mykubehost3 kubelet[89518]: E0319 08:02:45.230279   89518 event.go:212] Unable to write event: 'Post https://1.2.3.4:6443/api/v1/namespaces/kube-system/events: dial tcp 1.2.3.4:6443: connect: connection refused' (may retry after sleeping)
<30>Mar 19 08:02:45 mykubehost3 kubelet[89518]: E0319 08:02:45.745012   89518 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Get https://1.2.3.4:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:45 mykubehost3 kubelet[89518]: E0319 08:02:45.745920   89518 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Get https://1.2.3.4:6443/api/v1/nodes?fieldSelector=metadata.name%3Dmykubehost3.mycompany.com&limit=500&resourceVersion=0: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:45 mykubehost3 kubelet[89518]: E0319 08:02:45.746983   89518 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://1.2.3.4:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dmykubehost3.mycompany.com&limit=500&resourceVersion=0: dial tcp 1.2.3.4:6443: connect: connection refused
<30>Mar 19 08:02:46 mykubehost3 kubelet[89518]: E0319 08:02:46.268141   89518 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-apiserver-mykubehost3.mycompany.com": Error response from daemon: Address already in use
<30>Mar 19 08:02:46 mykubehost3 kubelet[89518]: E0319 08:02:46.268193   89518 kuberuntime_sandbox.go:56] CreatePodSandbox for pod "kube-apiserver-mykubehost3.mycompany.com_kube-system(e447570a11168f7cb144ce1c48aee69f)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-apiserver-mykubehost3.mycompany.com": Error response from daemon: Address already in use
<30>Mar 19 08:02:46 mykubehost3 kubelet[89518]: E0319 08:02:46.268208   89518 kuberuntime_manager.go:646] createPodSandbox for pod "kube-apiserver-mykubehost3.mycompany.com_kube-system(e447570a11168f7cb144ce1c48aee69f)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-apiserver-mykubehost3.mycompany.com": Error response from daemon: Address already in use
<30>Mar 19 08:02:46 mykubehost3 kubelet[89518]: E0319 08:02:46.268304   89518 pod_workers.go:186] Error syncing pod e447570a11168f7cb144ce1c48aee69f ("kube-apiserver-mykubehost3.mycompany.com_kube-system(e447570a11168f7cb144ce1c48aee69f)"), skipping: failed to "CreatePodSandbox" for "kube-apiserver-mykubehost3.mycompany.com_kube-system(e447570a11168f7cb144ce1c48aee69f)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-apiserver-mykubehost3.mycompany.com_kube-system(e447570a11168f7cb144ce1c48aee69f)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"kube-apiserver-mykubehost3.mycompany.com\": Error response from daemon: Address already in use"
<30>Mar 19 08:02:46 mykubehost3 kubelet[89518]: W0319 08:02:46.272334   89518 pod_container_deletor.go:75] Container "1793d7d0e0921577dbe14c38ce152381c289402d918988a778a125519672c0e0" not found in pod's containers

and the following for docker:

> <30>Mar 19 08:02:43 mykubehost3 dockerd[89229]: time="2019-03-19T08:02:43-04:00" level=info msg="shim reaped" id=d25ca108c6b7a7bee630fce1d12e0875330eea4faa1c5b3f33b495b088b7717e module="containerd/tasks"
<30>Mar 19 08:02:43 mykubehost3 dockerd[89229]: time="2019-03-19T08:02:43.741662635-04:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
<30>Mar 19 08:02:44 mykubehost3 dockerd[89229]: time="2019-03-19T08:02:44.862590008-04:00" level=warning msg="error locating sandbox id f98e7a998578659cba5d7e14541785b78f6a03ab41786e777e1b0484c899d0e0: sandbox f98e7a998578659cba5d7e14541785b78f6a03ab41786e777e1b0484c899d0e0 not found"
<30>Mar 19 08:02:44 mykubehost3 dockerd[89229]: time="2019-03-19T08:02:44.864240095-04:00" level=error msg="d25ca108c6b7a7bee630fce1d12e0875330eea4faa1c5b3f33b495b088b7717e cleanup: failed to delete container from containerd: no such container"
<30>Mar 19 08:02:44 mykubehost3 dockerd[89229]: time="2019-03-19T08:02:44.904564270-04:00" level=error msg="Handler for POST /v1.37/containers/d25ca108c6b7/restart returned error: Cannot restart container d25ca108c6b7: Address already in use"
<30>Mar 19 08:02:45 mykubehost3 dockerd[89229]: time="2019-03-19T08:02:45-04:00" level=info msg="shim reaped" id=e592e679f351a666ccec201de996c2deebfa964a9649f6cb0ad6d9b44103b8ea module="containerd/tasks"
<30>Mar 19 08:02:45 mykubehost3 dockerd[89229]: time="2019-03-19T08:02:45.344876959-04:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
<30>Mar 19 08:02:46 mykubehost3 dockerd[89229]: time="2019-03-19T08:02:46.267641507-04:00" level=error msg="1793d7d0e0921577dbe14c38ce152381c289402d918988a778a125519672c0e0 cleanup: failed to delete container from containerd: no such container"
<30>Mar 19 08:02:48 mykubehost3 dockerd[89229]: time="2019-03-19T08:02:48.316315539-04:00" level=error msg="8184d182f96daec4ece50d824108e074e970f25719c02206519287d3c2c12477 cleanup: failed to delete container from containerd: no such container"

**What you expected to happen**:
I expect the kube-apiserver pod to be restarted with the new config.

**How to reproduce it (as minimally and precisely as possible)**:
Create the following yaml in the kubelet manifets directory:
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  priorityClassName: system-node-critical
  terminationGracePeriodSeconds: 0
  containers:
  - command:
    - kube-apiserver
    - --apiserver-count=3
    - --endpoint-reconciler-type=master-count
    - --allow-privileged=true
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --secure-port=6443
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
    - --storage-backend=etcd3
    - --requestheader-allowed-names=front-proxy-client
    - --service-cluster-ip-range=10.96.0.0/12
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --enable-bootstrap-token-auth=true
    - --requestheader-username-headers=X-Remote-User
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --authorization-mode=RBAC
    - --advertise-address=1.2.3.4
    - --etcd-servers=http://<ETCD1>:2379,http://<ETCD2>:2379,http://<ETCD3>:2379
    image: gcr.io/google_containers/kube-apiserver-amd64:v1.11.6
    livenessProbe:
      failureThreshold: 3
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 5
      periodSeconds: 5
    ports:
      - containerPort: 6443
        hostPort: 6443
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: k8s
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: certs
    - mountPath: /etc/pki
      name: pki
  hostNetwork: false
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: k8s
  - hostPath:
      path: /etc/ssl/certs
    name: certs
  - hostPath:
      path: /etc/pki
    name: pki
status: {}
```

This will create the kube-apiserver pod.
Then update the priorityClassName: system-node-critical to priorityClassName: system-cluster-critical, which will cause a recreation of that pod.
**Anything else we need to know?**:
When I get the "Address already in use" error, I can't see anything listening on 6443 port.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:39:52Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Bare-metal host
- OS (e.g: `cat /etc/os-release`):
Ubuntu 16.04
- Kernel (e.g. `uname -a`):
Linux mykubehost3.mycompany.com 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm
- Others:
docker version 18.03.1-ce
kubelet 1.11.6

**Comment by neolit123** [comment]
hello, 1.11 is going out of support later this month when 1.14 is released.
you are going to have to upgrade.

> I expect the kube-apiserver pod to be restarted with the new config.

to do that you just have to change the config file and wait.
the kubelet should re-create the Pod automatically.


> Create the following yaml in the kubelet manifets directory:

plus

> Install tools:
kubeadm

are you using kubeadm or manually managing your kube-apiserver?

**Comment by akarasik** [comment]
@neolit123 
>to do that you just have to change the config file and wait.
the kubelet should re-create the Pod automatically.

Thats the issue. When I change the config file, kubelet tries to recreate it.
It removed the old container, but fails on creating the new pause container, and therefore the new apiserver container itself doesn' created at all.

I use kubeadm to install the cluster (which creates the manifests files).
After I have a running cluster, I make changes to the existing manifest yaml files.

**Comment by neolit123** [comment]
@akarasik 

> It removed the old container, but fails on creating the new pause container, and therefore the new apiserver container itself doesn' created at all.

i'm sorry but i cannot reproduce the problem with 1.12.6.
you can also try removing all your containers and images from this node and try again.

here is what i did:

1) obtained the kubeadm and kubelet from 1.12.6.
2) created a single node control-plane cluster using kubeadm
`sudo kubeadm init --ignore-preflight-errors=all --kubernetes-version=stable-1.12`
3) all pods started fine
4) made a small change to the `/etc/kubernetes/manifests/kube-apiserver.yaml`.
5) the kubelet picket up the static pod change and the api server restarted in about 20 seconds.

i'm going to have to close this issue as 1.11.x is going out of support in about one week, but feel free to re-open if you see the same problem once you upgrade to at least 1.12.

/close
/remove-sig cluster-lifecycle

**Comment by akarasik** [comment]
@neolit123 The issue happens only when running in bridge mode, with port mapping.
Try to adding this to the kube-apiserver container:
```
    ports:
      - containerPort: 6443
        hostPort: 6443
```
and setting this in the spec:
```
hostNetwork: false
```

**Comment by neolit123** [comment]
> Try to adding this to the kube-apiserver container:

still works for me:
```
...
spec:
  hostNetwork: true
  containers:
  - ports:
      - containerPort: 6443
        hostPort: 6443
    command:
    - kube-apiserver
...
```

```
NAMESPACE     NAME                                 READY   STATUS    RESTARTS   AGE
kube-system   coredns-576cbf47c7-qpp7p             1/1     Running   0          22m
kube-system   coredns-576cbf47c7-r6g5h             1/1     Running   0          22m
kube-system   etcd-luboitvbox                      1/1     Running   0          21m
kube-system   kube-apiserver-luboitvbox            1/1     Running   0          27s
kube-system   kube-controller-manager-luboitvbox   1/1     Running   3          21m
kube-system   kube-proxy-l8f87                     1/1     Running   0          22m
kube-system   kube-scheduler-luboitvbox            1/1     Running   3          20m
kube-system   weave-net-bzbmk                      2/2     Running   1          22m

```
