### ISSUE TITLE
resizing dynamic pvc

### ISSUE THREAD

**Issue by Mnbill** [kubernetes/kubernetes#75476]
Hello,

I have a saturated pvc, i want to resize it (from 20GB to 30GB)
My kubernetes version V1.9.3
my pvc in an AWS EBS

I tried this methode  https://github.com/kubernetes/kubernetes/issues/35941#issuecomment-328028093

i resize my ebs, pv

but when i try to apply my pvc file i have this erreor:
The PersistentVolumeClaim "pvc-claim1" is invalid: spec: Forbidden: field is immutable after creation

my pvc config:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim1
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
```

/need help
/help
