### ISSUE TITLE
Unable to configure Azure load balancer idle timeout with annotation

### ISSUE THREAD

**Issue by slack** [kubernetes/kubernetes#75527]
**What happened**:

Created a Service, type LoadBalancer with the following spec:
```
apiVersion: v1
kind: Service
metadata:
  name: basic-service-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: 20
  labels:
    app: basic-service-lb-app
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 180
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: basic-service-lb-app
```

The load balancer was provisioned but the idle timeout was still configured as the default of 4 minutes. 

**What you expected to happen**:

Idle timeout for the provisioned load balancer should match the annotation of 20. 

**How to reproduce it (as minimally and precisely as possible)**:

Service gist + basic deployment available https://gist.github.com/slack/6256e1bc1af1b714f2123569afa45aee

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AKS

/sig azure
/kind bug
