### ISSUE TITLE
lifecycle hooks weird behavior

### ISSUE THREAD

**Issue by nerusnayleinad** [kubernetes/kubernetes#75589]
I am making tests with lifecycle hooks, and there is this behavior that makes no sense to us that I would like to find out what is that. So I have the following deployment:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lifecycle
spec:
  replicas: 1
  template:
    metadata:
      name: lifecycle
      labels:
        lifecycle: example
    spec:
      containers:
      - name: nginx
        image: nginx
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh 
              - -c
              - echo "Hello at" `date` > /usr/share/post-start
          preStop:
            exec:
              command:
              - /bin/sh 
              - -c
              - echo "Goodbye at" `date` > /usr/share/pre-stop
        volumeMounts:
        - name: hooks
          mountPath: /usr/share/
      volumes:
      - name: hooks
        hostPath:
          path: /usr/hooks/
```

Simple. Every time I kill the pod, and it gets re-created, it will generate 'post-start' and 'pre-stop'  files with the message hello or goodbye with the date. So it works, but not as expected. When I first create the deployment, it created the file with the right date, but after that every time I do any change that would trigger the hooks, it does with the same date.

```
omega_monkey@gke-demo-cluster-62037557-nrq2:/usr/hooks$ ls -l
total 8
-rw-r--r-- 1 root root 342 Mar 22 09:51 post-start
-rw-r--r-- 1 root root 320 Mar 22 09:51 pre-stop
```

But if I check the message that got generated, it makes no sense.

```
Hello at Fri Mar 22 09:39:55 UTC 2019
Goodbye at Fri Mar 22 09:39:55 UTC 2019
```

So, 9:39 is the time I created the deployment. The fact that post-start and pre-stop dates are the same is already weird. There should be at least a second of difference. And now every time I kill the pod, it prints the same old date.

I SSHed into the node, and deleted the files as well, then I killed the pod again, but it got created with the old date too.

If I access into the pod, and run `date` command, and it works fine. Looks like it retrieves this info from somewhere that I am not getting. Any idea what's happening?
