### ISSUE TITLE
Egress rule does not work - Weave

### ISSUE THREAD

**Issue by vinsguru** [kubernetes/kubernetes#75676]
Egress rules do not seem to work as expected. Lets follow the steps to replicate this issue.

Lets run 2 different nginx deployments

```
kubectl run nginx1 --image=nginx --port=80
kubectl run nginx2 --image=nginx --port=80
```

Lets expose them as 2 different services

```
kubectl expose deploy/nginx1 --target-port=80
kubectl expose deploy/nginx2 --target-port=80
```

Lets create a simple pod to play with our deployment

`kubectl run alpine --image=alpine --restart=Never --command 'sleep' '3600'`

Lets create a network policy as shown here for the alpine we had just created.
As per the policy, alpine can talk to **nginx2**. but not **nginx1**

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: alpine
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          run: nginx2
    ports:
    - protocol: TCP
      port: 80
```
Access the alpine container

`kubectl exec alpine -it sh`

Install curl

`apk add curl`

Run the below commands one by one.

```
curl nginx1
curl nginx2
```

**What happened**:

Able to get response from both services successfully. 

**What you expected to happen**:
Allow the egress only for **nginx2**. not for **nginx1**.

**How to reproduce it (as minimally and precisely as possible)**:
Just follow the above steps.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
local cluster

- Others:
CNI - Weave
