### ISSUE TITLE
Persistent volume subpath data loss on a "kubeadm reset"

### ISSUE THREAD

**Issue by emfmesquita** [kubernetes/kubernetes#75688]
**What happened**:
Files from a subpath of a host path persistent volume were deleted after a "kubeadm reset".

**What you expected to happen**:
No changes on persistent volume files after a "kubeadm reset".

**How to reproduce it (as minimally and precisely as possible)**:
 1. Start a single node cluster with NoSchedule removed using kubeadm init.
 2. Create a dir inside another dir:
```bash
sudo mkdir -p /test/subpath
```
 3. Create a file inside it:
```bash
sudo bash -c "echo test >> /test/subpath/file"
```
 4. Create a PV, PVC and deploy using the file dir as a volume using subpath:
```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/test"
    type: DirectoryOrCreate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      volumes:
      - name: test-pv
        persistentVolumeClaim:
          claimName: test-pv-claim
      containers:
        - image: busybox
          command: [ "/bin/sh", "-c", "tail -f /dev/null" ]
          name: test
          volumeMounts:
            - name: test-pv
              mountPath: /test
              subPath: subpath
```
5. Check that file is still there and mounted on pod:
```bash
ls /test/subpath
kubectl exec test-566d959698-plk7c -- ls /test
```
6. Run kubeadm reset:
```bash
sudo kubeadm reset
```
7. Check that file is **NOT** there anymore:
```bash
ls /test/subpath
```

**Anything else we need to know?**:
Unfortunatelly this caused data loss. This does not happen if the deploy/pod is deleted beforehand.

**Environment**:
- Kubernetes version: v1.13.4
- Hardware configuration: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz, 16GB RAM
- OS: CentOS Linux 7
- Kernel: 3.10.0-693.2.2.el7.x86_64
- Install tools: Binaries by yum install. Cluster by kubeadm init.
- Docker version:  18.06.1-ce
- Docker Storage Driver: overlay2
