### ISSUE TITLE
Support scheduler policy file in YAML format

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#75852]
Kubernetes scheduler enables you to overwrite default Predicates/Priorities as well as configuring extenders in a "scheduler policy".

In latest scheduler componentconfig API (v1alpha1), it can be a file or a configmap: https://github.com/kubernetes/kubernetes/blob/91f40aec8ad5b992d8057b4fab0fa287ee6bdee9/pkg/scheduler/apis/config/types.go#L104-L111

However, if you defines a scheduler config file and specify a YAML policy file:

```yaml
apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/run/kubernetes/scheduler.kubeconfig"
algorithmSource:
  policy:
    file:
      path: "/root/config/scheduler-extender-policy.yaml" <-- doesn't work
      # path: "/root/config/scheduler-extender-policy.json" <-- works
```

It doesn't work.

It's because only JSON is supported: https://github.com/kubernetes/kubernetes/blob/91f40aec8ad5b992d8057b4fab0fa287ee6bdee9/pkg/scheduler/api/latest/latest.go#L45-L46

It'd nice to enhance it with an UniversalSerilizer so as to support both JSON and YAML.

/sig scheduling
/help
/priority important-longterm
