### ISSUE TITLE
Replicaset controller bug: continuously creating pod to tainted nodes

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/kubernetes#75913]
**What happened**:
 When replicaset want to assign its pods to one specific node(`rs.Spec.Template.Spec.NodeName != ""`),if that node was tainted, vicious circle would happen:
    Replicaset controller keeps creating pods. Taint manager keeps deleted thosee pods.

**How to reproduce it (as minimally and precisely as possible)**:
Creating a Deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodep
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      nodeName: foo-node
      containers:
      - name: php-redis
        image: nginx
```
Then taint the foo-node
`kubectl taint nodes foo-node foo=foo:NoExecute`

Watching that pods was continuously created and killed
