### ISSUE TITLE
incorrect result of auth can-i for namespaces

### ISSUE THREAD

**Issue by jtnord** [kubernetes/kubernetes#75970]
```
> kubectl auth can-i list namespaces --as=system:serviceaccount:jx:jtnord
yes

> kubectl get namespaces --as=system:serviceaccount:jx:jtnord
Error from server (Forbidden): namespaces is forbidden: User "system:serviceaccount:jx:jtnord" cannot list resource "namespaces" in API group "" at the cluster scope
```

**What you expected to happen**:

if `auth can-i` returns true I expect to be able to perform the action without issue.

Note in this case my service user has a rolebinding in a single namespace (and that is also what my kubecontext is set to.)  if I change my default to a different namespace then the command returns false

**How to reproduce it (as minimally and precisely as possible)**:

* create a namespace (test)
* create a service account in that namespace
* create a role that gives get list and watch permissions to
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    description: yada yada
    title: myrole
  name: myrole
  namespace: test
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - extensions
  - apps
  - rbac.authorization.k8s.io
  - batch
  resources:
  - '*'
  verbs:
  - list
  - get
  - watch
```
* create a rolebinding from that role to the service account.

**Anything else we need to know?**:

this is special because namespaces are not scoped to a namespace.

if you replace the command with
`kubectl auth can-i list namespaces --all-namespaces --as=system:serviceaccount:jx:jtnord`
then you get the exepcted result `no - no RBAC policy matched`  however this breaks the path of least suprise.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.5-gke.5", GitCommit:"2c44750044d8aeeb6b51386ddb9c274ff0beb50b", GitTreeState:"clean", BuildDate:"2019-02-01T23:53:25Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
GKE
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
