### ISSUE TITLE
Modifying pod timezone with podpreset failed

### ISSUE THREAD

**Issue by tangjiaxing669** [kubernetes/kubernetes#76056]
Kubernetes installed with kubespray-2.8.3：

```shell
[root@node1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```

After completion, there will be a lot of pods generated:

```shell
[root@node1 ~]# kubectl get pod -n kube-system
NAME                                    READY   STATUS    RESTARTS   AGE
coredns-788d98cc7b-7qrnq                1/1     Running   2          4d3h
coredns-788d98cc7b-cbthj                1/1     Running   2          4d3h
dns-autoscaler-6866b5d486-97j64         1/1     Running   2          4d3h
kube-apiserver-node1                    1/1     Running   2          4d3h
kube-apiserver-node2                    1/1     Running   1          4d3h
kube-controller-manager-node1           1/1     Running   2          4d3h
kube-controller-manager-node2           1/1     Running   2          4d3h
...
```

Now I want to modify the timezone of all pods with podpreset. I turned on the podpreset admission controller and set `--runtime-config=admissionregistration.k8s.io/v1alpha1,settings.k8s.io/v1alpha1=true`

podpreset YAML config:

```yaml
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: tz-modify
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: flannel
  volumeMounts:
    - name: timezone
      mountPath: /etc/localtime
  volumes:
    - name: timezone
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
```

When I applied the YAML file, nothing changed.

```shell
[root@node1 ~]# kubectl get podpreset -n kube-system
NAME        CREATED AT
tz-modify   2019-04-02T20:58:18Z
[root@node1 ~]# kubectl describe podpreset tz-modify -n kube-system
Name:         tz-modify
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>
API Version:  settings.k8s.io/v1alpha1
Kind:         PodPreset
Metadata:
  Creation Timestamp:  2019-04-02T20:58:18Z
  Generation:          1
  Resource Version:    1966535
  Self Link:           /apis/settings.k8s.io/v1alpha1/namespaces/kube-system/podpresets/tz-modify
  UID:                 0abdf995-558a-11e9-819f-000c29b075d3
Spec:
  Selector:
    Match Labels:
      K 8 S - App:  flannel         # This may be a display issue, as shown in the xshell terminal.
  Volume Mounts:
    Mount Path:  /etc/localtime
    Name:        timezone
  Volumes:
    Host Path:
      Path:  /usr/share/zoneinfo/Asia/Shanghai
      Type:  
    Name:    timezone
Events:      <none>
```

And the time zone in the pod is still the default utc0.

Is there any other place with errors?
