### ISSUE TITLE
The presence of admission webhooks on /scale breaks /scale

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#76107]
Adding a validating admission webhook targeting deployments/scale (or any other /scale) breaks all such scale operations when the dynamic webhook admission plugin attempts to serve the plugin, and convert `Deployment` to `Scale` when trying to prepare the old object.

Reproducer:
1. register a webhook targetting `deployments/scale` (you don't need a backing hook)

  <details>

  <summary>whconfig.yaml</summary>

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: test-repro
webhooks:
- name: test-repro.test.k8s.io
  clientConfig:
    url: https://localhost:8675/hook
    caBundle: <your CA bundle>
  rules:
  - apiGroups: ["*"]
    apiVersions: ["*"]
    operations: ["*"]
    resources: ["deployments/scale"]
```

  </details>

2. `kubectl scale deploy/<some-deployment> --replicas=2`

3. observe that you get an InternalServerError with an error about converting `Deployment` to `Scale`

The line responsible for the error is https://github.com/kubernetes/kubernetes/blob/cebb4ee2ac9e19fe90f78c3285978e585e67a3ac/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/generic/webhook.go#L177-L181

Kubernetes version: 8af1bf313efeeafb94c01ce04965ad8fe9cea21a and also v1.11.3
