### ISSUE TITLE
Share Process Namespace for Deployments

### ISSUE THREAD

**Issue by geekodour** [kubernetes/kubernetes#76138]
**What would you like to be added**:
Trying to
[Share Process Namespace](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/) using Deployments. The example refers to a Pod definition using apiversion `v1` I am not sure why this is not working as expected.

example config
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depname
spec:
  replicas: 1
  template:
    metadata:
      namespace: myn
    spec:
      serviceAccountName: mysa
      shareProcessNamespace: true
      containers:
      - name: shell
        image: busybox
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        stdin: true
        tty: true
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      - name: myapp
        image: docker.io/geekodour/app:latest
      volumes:
      - name: scripts
        configMap:
          name: scriptsconfig
          defaultMode: 0744
      nodeSelector:
        cloud.google.com/gke-nodepool: mynodepool
```

**Why is this needed**:
I think this only works for Pod declarations, make it work on deployments (`apps/v1`). I will be happy to work on this if really is an issue because I am not sure If I am doing this right.
