### ISSUE TITLE
kube-proxy fails to retrieve services and endpoints in Vagrant/Virtualbox cluster

### ISSUE THREAD

**Issue by markllama** [kubernetes/kubernetes#7622]
Possibly related to https://github.com/GoogleCloudPlatform/kubernetes/pull/7303

On simply starting a Vagrant/Virtualbox cluster and examining the journalctl results for the kube-proxy startup on minion-1:

    [vagrant@kubernetes-minion-1 ~]$ journalctl --unit kube-proxy | head 
    -- Logs begin at Tue 2015-02-24 15:05:10 UTC, end at Fri 2015-05-01 14:59:21 UTC. --
    May 01 13:51:38 kubernetes-minion-1 systemd[1]: Starting Kubernetes Kube-Proxy Server...
    May 01 13:51:38 kubernetes-minion-1 systemd[1]: Started Kubernetes Kube-Proxy Server.
    May 01 13:51:38 kubernetes-minion-1 kube-proxy[3231]: I0501 13:51:38.155272    3231 server.go:86] Running in resource-only container "/kube-proxy"
    May 01 13:51:38 kubernetes-minion-1 kube-proxy[3231]: I0501 13:51:38.157258    3231 proxier.go:336] Setting Proxy IP to 10.0.2.15
    May 01 13:51:38 kubernetes-minion-1 kube-proxy[3231]: I0501 13:51:38.157285    3231 proxier.go:341] Initializing iptables
    May 01 13:51:38 kubernetes-minion-1 kube-proxy[3231]: E0501 13:51:38.211881    3231 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
    May 01 13:51:38 kubernetes-minion-1 kube-proxy[3231]: E0501 13:51:38.216027    3231 api.go:108] Unable to load services: the server has asked for the client to provide credentials (get services)
    May 01 13:52:58 kubernetes-minion-1 kube-proxy[3231]: E0501 13:52:58.077294    3231 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
    May 01 13:53:07 kubernetes-minion-1 kube-proxy[3231]: E0501 13:53:07.874594    3231 api.go:108] Unable to load services: the server has asked for the client to provide credentials (get services)

It appears that the kube-proxy initialization process is not authenticating to the server correctly:

    systemctl status kube-proxy | cat
    kube-proxy.service - Kubernetes Kube-Proxy Server
        Loaded: loaded (/usr/lib/systemd/system/kube-proxy.service; enabled)
       Active: active (running) since Fri 2015-05-01 13:51:38 UTC; 1h 16min ago
         Docs: https://github.com/GoogleCloudPlatform/kubernetes
     Main PID: 3231 (kube-proxy)
        CGroup: /system.slice/kube-proxy.service
                └─3231 /usr/local/bin/kube-proxy --master=https://10.245.1.2 --kubeconfig=/var/lib/kube-proxy/kubeconfig --v=2

    May 01 15:02:06 kubernetes-minion-1 kube-proxy[3231]: E0501 15:02:06.687631    3231 api.go:108] Unable to load services: the server has asked for the client to provide credentials (get services)
    May 01 15:02:52 kubernetes-minion-1 kube-proxy[3231]: E0501 15:02:52.509411    3231 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
    ....

````
sudo cat /var/lib/kube-proxy/kubeconfig
apiVersion: v1
kind: Config
users:
- name: kube-proxy
  user:
    token: UUalZjWmetMofOkoQNZhIqxzWA7X82mR
clusters:
- name: local
  cluster:
     insecure-skip-tls-verify: true
contexts:
- context:
    cluster: local
    user: kube-proxy
  name: service-account-context
current-context: service-account-context
````
