### ISSUE TITLE
ipvs excludeCIDRs seems not work

### ISSUE THREAD

**Issue by fanux** [kubernetes/kubernetes#76267]
**What happened**:
When I config kube-proxy with excludeCIDRs, kube-proxy still try to delete my ipvs rules.

**What you expected to happen**:
kube-proxy not delete excludeCIDRs virturl server.

**How to reproduce it (as minimally and precisely as possible)**:
```
[root@iZrj9fs8mk0inonl9l6j26Z ~]# cat kubeadm-config.yaml 
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.14.0
controlPlaneEndpoint: "apiserver.cluster.local:6443" # apiserver DNS name
apiServer:
        certSANs:
        - 127.0.0.1
        - apiserver.cluster.local
        - 172.20.241.205
        - 172.20.241.206
        - 172.20.241.207
        - 172.20.241.208
        - 10.103.97.1          # virturl ip
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
        excludeCIDRs: ["10.103.97.1/32"]
```
kubeadm init --config=kubeadm-config.yaml --experimental-upload-certs

Then add a ipvs on node:
```
ipvsadm -Ln
TCP  10.103.97.1:6443 rr
  -> 172.20.241.207:6443          Masq    1      2          0
```
Then join the node, you can see kube-proxy log:
```
graceful_termination.go:160] Trying to delete rs: 10.103.97.1:6443/TCP/172.20.241.207:6443
```
If don't have an active connection, the ipvs will removed.

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.14.0
- OS (e.g: `cat /etc/os-release`):
centos7.4
- Kernel (e.g. `uname -a`):
3.10
- Install tools:
kubeadm
