### ISSUE TITLE
pod with `requiredDuringSchedulingIgnoredDuringExecution` behave incorrectly after kubelet restart

### ISSUE THREAD

**Issue by gaorong** [kubernetes/kubernetes#76322]
**What happened**:
we have a pod with `spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution` and running peacefully at specific node, let's say node1, when node1's label changed and mismatched pod's constraint specified by node affinity, the pod will run continually as the `IgnoredDuringExecution` semantic.  However if we restart the kubelet agent, this pod will be killed with  `MatchNodeSelector`  status, and another pod will create by owner deployment to meet deployment's replicas num.

after digging into kubelet's code, I found when kubelet restart, it will get all pods belonging to this node from apiserver,  and execute `handler.HandlePodAdditions`  function, then kubelet will check if this pod is admitted; if not, reject it. In the checking process, `predicates.GeneralPredicates`  will fail to admit pod.

**What you expected to happen**:
After kubelet restart, don't kill pods and lets it running as before during execution even though this node doesn't match pod's affinity label.
the restart of kubelet shouldn't break `IgnoredDuringExecution` semantics.

**How to reproduce it (as minimally and precisely as possible)**:
1. add a label to specificy node, let's say 'node1' :
```yaml
kubectl label node node1 test=test
```
2. create a deployment  with `spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution` as  bellow:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    resource_name: nginx
spec:
  selector:
    matchLabels:
      resource_name: nginx
  template:
    metadata:
      labels:
        resource_name: nginx 
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: test
                operator: In
                values:
                - test
      containers:
      - image: nginx
        name: nginx
```
a nginx pod will create by this deployment.
3. remove node1's lable
```yaml
kubectl label node node1 test-
```
till now, everything is ok since  `requiredDuringSchedulingIgnoredDuringExecution` indicates that label changing should affect this pod.
```
[root@k8s-test-master01 test]# kubectl get pods
NAME                   READY   STATUS    RESTARTS   AGE
nginx-7cbbd59c-6xjmn   1/1     Running   0          9m32s
```

4. restart kubelet agent:
```
systemctl restart kubelet
```
After kubelet restart, this pod will be killed by kubelet as below,  another pod will recreate on another node.
```
[root@k8s-test-master01 test]# kubectl get pods
NAME                   READY   STATUS              RESTARTS   AGE
nginx-7cbbd59c-6xjmn   0/1     MatchNodeSelector   0          10m
nginx-7cbbd59c-w9t2c   0/1     Running             0          9s
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
bare metal
- OS (e.g: `cat /etc/os-release`):
CentOS Linux 7
- Kernel (e.g. `uname -a`):
Linux k8s-test-master01 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
