### ISSUE TITLE
kube-proxy configmap invalid after cluster upgrade 1.11.9 - 1.14.1

### ISSUE THREAD

**Issue by discostur** [kubernetes/kubernetes#76329]
**What happened**:
I upgraded my k8s cluster from 1.11.9 to 1.14.1 and kube-proxy was not able to start on the worker nodes.

It seems that the kube-proxy configmap gets not updated correctly, because it hat some feature flags within wich should not be there:

kube-proxy docker logs:
```
F0409 09:41:04.965443       1 server.go:463] failed complete: unrecognized feature gate: MountPropagation
```

kubectl -n kube-system get cm kube-proxy -o yaml
```
kubectl -n kube-system get cm kube-proxy -o yaml
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 5
    clusterCIDR: 10.244.0.0/16
    configSyncPeriod: 15m0s
    conntrack:
      max: null
      maxPerCore: 32768
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    enableProfiling: false
    featureGates:
      MountPropagation: true
      PersistentLocalVolumes: true
      VolumeScheduling: true
...
```

After removing the feature gates from the configmap kube-proxy was able to start up.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g: `cat /etc/os-release`):
```
CentOS Linux release 7.6.1810 (Core) 
``` 

- Kernel (e.g. `uname -a`):
```
Linux  3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
