### ISSUE TITLE
Empty PSPs are treated as any other normally named PSP

### ISSUE THREAD

**Issue by iamrz1** [kubernetes/kubernetes#76366]
We recently came across a problem related to empty PSP while upgrading [kubeDB](https://github.com/kubedb). If a pod's role has an empty resourceName ("") as podsecuritypolicy, our kubeDB operator (superset of the pod) needs to have an empty resourceName ("") alongside other normally named resourceNames as podsecuritypolicy in it's (operator) clusterrole as well. 
In Pod:
```
- apiGroups:
  - policy
  resourceNames:
  - ""
  -psp-for-db-1
  resources:
  - podsecuritypolicies
  verbs:
  - use
```
In operator:
```
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs: ["use"]
  resourceNames:
  - "" (wont work without this)
  - psp-for-db-1
  - psp-for-db-2
  ...
```
In short, it means that empty PSPs are treated as any other normally named PSP.

We expect that an empty resourceName in policy should not be treated as a normally and purposefully named PSP resource. Is there any functional reason why it is how it is? 

Reproduce: kubedb/project#481
