### ISSUE TITLE
"runAsUser" parameter of "securityContext" doesn't reflect assigned value inside container

### ISSUE THREAD

**Issue by virendra-sharma** [kubernetes/kubernetes#76380]
**What happened**:
Assigned permission to containers of pod by using "runAsUser" & "runAsGroup" parameter of securitycontext module, but after getting shell prompt of running container of pod, I can see only userID gets updated and groupID remains as root(0).

**What you expected to happen**:
Inside pod container should get userID & groupID as per assigned ID while creating pod. It should be visible in container after executing "ID" command from container bash.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Tried assigning of runAsUser, runAsGroup & fsGroup but except groupID other two were visible.
Please find below used YAML's for reference.
```
cat pv-test.yml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test
spec:
    capacity:
      storage: 35Gi
    accessModes:
    - ReadWriteOnce
    flexVolume:
      driver: hpe.com/hpe
      options:
        name: VOLUME1

cat pvc-test.yml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

cat pod-test.yml
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 2000
  containers:
  - name: minio
    image: minio/minio:latest
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
    securityContext:
      allowPrivilegeEscalation: false
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: pvc-test
```
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:

- OS (e.g: `cat /etc/os-release`):
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"
```
- Kernel (e.g. `uname -a`):
```
Linux cld6b12 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

@kubernetes/sig-contributor-experience-bugs
