### ISSUE TITLE
Persistent Volume Fails Silently if Using v1beta1 format

### ISSUE THREAD

**Issue by aronchick** [kubernetes/kubernetes#7641]
When using this from the example (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/mysql-wordpress-pd/mysql.yaml) with Google Cloud Engine:

```yaml
    volumes:
      - name: mysql-persistent-storage
        source:
          # emptyDir: {}
          persistentDisk:
            # This GCE PD must already exist.
            pdName: mysql-disk
            fsType: ext4
```

The persistent disk does not mount, and does not tell the user anything.  The correction is here:

```yaml
      volumes:
        - name: mysql-persistent-storage
          gcePersistentDisk:
            pdName: mysql-disk
            fsType: ext4
```

Additionally, when mounting anything, logs are not being written to kubelet.log

Expected:
* Alert the user that the mount is invalid or will not result in what they expect (an unmounted directory/disk).
* Log more information to kubelet.log to help indicate what's going on.
