### ISSUE TITLE
Add transparent corporate proxy support

### ISSUE THREAD

**Issue by lersouza** [kubernetes/kubernetes#76447]
**What would you like to be added**:

Add, maybe in Endpoint object, support for making requests through a corporate proxy.
This would allow service in the cluster to disregard corporate proxy. One could configure an external service by using a Service object and an Endpoint object with corporate proxy information.

**Example**:
```yaml
kind: Endpoints
apiVersion: v1
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 1.2.3.4
    ports:
      - port: 9376
    proxy:
      - host: my.proxy.com
        port: 8080
```

**Why is this needed**:

Many companies host in-house K8s clusters and also use corporate proxies to access external services. This way, we should enable our application to use proxies on every service/container for access to external services, but we should bypass local k8s addresses.

If this feature were available, we could control better which external services we use and how to access them from the cluster.
