### ISSUE TITLE
kubelet doesn't restart static pods after eviction

### ISSUE THREAD

**Issue by namreg** [kubernetes/kubernetes#76598]
**What happened**:
Kubelet does not restart static pods after eviction.

**What you expected to happen**:
Kubelete restarts static pods when eviction condition has not already met.

**How to reproduce it (as minimally and precisely as possible)**:
Create a static pod in the pod manifests folder with the following spec:
```yml
---
apiVersion: v1
kind: Pod
metadata:
  name: test-static-pod
  namespace: kube-system
  labels:
    app: test-static-pod
spec:
  restartPolicy: Always
  containers:
    - name: pause
      image: "nginx"
      imagePullPolicy: IfNotPresent
```

Then, for example, emulate DiskPressure node condition:
```bash
fallocate -l 100G /test
```
Make sure `test-static-pod` was evicted:
```bash
kubectl get pods test-static
```

After that, address DiskPressure condition by removing test file:
```bash
rm -f /test
```

Make sure DiskPressure condition is disappeared from node:
```bash
kubectl describe node nodename -o yaml | grep -A5 Conditions
```
Check `test-static-pod` status:
```bash
kubectl get pods test-static-pod
```
The pod still has status `Evicted`

**Anything else we need to know?**:
Similar issue https://github.com/kubernetes/kubernetes/issues/71134

**Environment**:
- Kubernetes version (use `kubectl version`):
1.13.5
- Cloud provider or hardware configuration:
virtualbox
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux P20B-VR3-R1-K8S-N1 4.19.30.1 #0 SMP Wed Mar 20 12:42:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:
