### ISSUE TITLE
Notifications API

### ISSUE THREAD

**Issue by grzesiek** [kubernetes/kubernetes#76597]
**What would you like to be added**:

High-level Notifications API, where a notification is a Kubernetes resource:

```yaml
apiVersion: v1alpha1
kind: Notification
metadata:
  name: service-notification
  labels:
    app: my-app-example
spec:
  watch: Deployment
  selector:
    matchLabels:
      - my-deployment
  rules:
    - [TBD ... similar to admission webhooks]
  notify:
    webhook: https://my-service.example/k8s
    secret: my-opaque-secret
    payload: v1alpha1
```

This is a little bit different than admission webhooks, because there is no need to mutate / validate an operation on a resource. Also, the notification is being triggered after persisting a resource in etcd, instead of executing the webhook before that happens.

This is similar to Docker Distribution notifications :arrow_right: https://docs.docker.com/registry/notifications/

**Why is this needed**:

We would like to integrate a few of our services with Kubernetes.

Currently we are using API polling to populate the service with a cluster state. We are considering creating an in-cluster controller along with a few other options, but having first-class, high-level notifications in Kubernetes might be an interesting, generic solution for this problem.

I might be missing something and perhaps we can already achieve something like this with Kubernetes, please let me know if something like this already exists.

If this feature seems to be as useful to a wider community, I'm willing to spend some time working on it.

Thanks for the input in advance :)
