### ISSUE TITLE
"No cloud provider specified" kube-controller-manager

### ISSUE THREAD

**Issue by jvoeller** [kubernetes/kubernetes#76701]
**What happened**: While trying to provision a volume for my Windows cluster I ran into the following issue. When I want to create Pod with the following yaml file 

```
apiVersion: v1
kind: Pod
metadata:
 name: backend
 labels:
   app: backend
spec:
 containers:
 - image: backend:7.0
   name: backend   
   volumeMounts:
   - name: disk01
     mountPath: 'D:'
 nodeSelector:
  beta.kubernetes.io/os: windows	  	 
 volumes:
 - name: disk01
   azureDisk:
     kind: Managed
     diskName: database
     diskURI: /subscriptions/{subcription_id}/resourceGroups/{resource_group}/providers/Microsoft.Compute/disks/database
```
the kubelet gives the following error:

> E0417 09:50:32.905898    3824 azure_dd.go:218] failed to get azure cloud in NewAttacher, plugin.host : workernode, err:AzureDisk -  failed to get Azure Cloud Provider. GetCloudProvider returned <nil> instead
> E0417 09:50:56.547252    3824 remote_runtime.go:204] CreateContainer in sandbox "c5bba865ea02e7282b918bde665392fff5fc8b61aeab10c532f4edf58e153f35" from runtime service failed: rpc error: code = Unknown desc = Error response from daemon: invalid volume specification: 'c:\var\lib\kubelet\pods\3db0323e-60f6-11e9-b16a-000d3a238919\volumes\kubernetes.io\~azure-disk\disk01:D:': invalid mount config for type "bind": bind source path does not exist: c:\var\lib\kubelet\pods\3db0323e-60f6-11e9-b16a-000d3a238919\volumes\kubernetes.io~azure-disk\disk01
> E0417 09:50:56.691491    3824 kuberuntime_manager.go:780] container start failed: CreateContainerError: Error response from daemon: invalid volume specification: 'c:\var\lib\kubelet\pods\3db0323e-60f6-11e9-b16a-000d3a238919\volumes\kubernetes.io\~azure-disk\disk01:D:': invalid mount config for type "bind": bind source path does not exist: c:\var\lib\kubelet\pods\3db0323e-60f6-11e9-b16a-000d3a238919\volumes\kubernetes.io\~azure-disk\disk01
> E0417 09:50:56.691491    3824 pod_workers.go:190] Error syncing pod 3db0323e-60f6-11e9-b16a-000d3a238919 ("backend_default(3db0323e-60f6-11e9-b16a-000d3a238919)"), skipping: failed to "StartContainer" for "backend" with CreateContainerError: "Error response from daemon: invalid volume specification: 'c:\\var\\lib\\kubelet\

The kube-controller-manager logs also say that no cloud provider has been specified.
> plugins.go:103] No cloud provider specified.
> core.go:175] configure-cloud-routes is set, but no cloud provider specified. Will not configure cloud provider routes.

I passed the cloud-config flag to to kube-controller-manager and specified `"cloud": "AzurePublicCloud"`

**What you expected to happen**:
It should recognize Azure as the cloud provider and provision a disk.
**How to reproduce it (as minimally and precisely as possible)**:
I set up the cluster with kubeadm and use flannel in host-gw mode as a networking solution.
Then I created a managed disk with azure CLI and tried to create a pod with the aforementioned yaml file.
  
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): 18.04.2 LTS (Bionic Beaver) on master and windows server build 17763
- Kernel (e.g. `uname -a`): Linux masterNode 4.18.0-1014-azure #14~18.04.1-Ubuntu SMP Mon Mar 18 16:15:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm, flannel
- Others:

**Comment by liggitt** [comment]
can you provide your full kubelet and controller-manager invocations?

**Comment by jvoeller** [comment]
i'm sorry, do you mean their yaml definition / arguments from the powershell scripts? 

kube-controller-manager
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=10.244.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --use-service-account-credentials=true
    - --cloud-config=/etc/kubernetes/azure.json
    image: k8s.gcr.io/kube-controller-manager:v1.14.0
    imagePullPolicy: IfNotPresent
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/ca-certificates
      name: etc-ca-certificates
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /usr/local/share/ca-certificates
      name: usr-local-share-ca-certificates
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/ca-certificates
      type: DirectoryOrCreate
    name: etc-ca-certificates
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /usr/local/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-local-share-ca-certificates
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
status: {}
```

kubelet


```
$kubeletArgs = @(
    "--hostname-override=$(hostname)"
    '--v=6'
    '--pod-infra-container-image=kubeletwin/pause'
    '--resolv-conf=""'
    '--allow-privileged=true'
    '--enable-debugging-handlers'
    "--cluster-dns=10.96.0.10"
    '--cluster-domain=cluster.local'
    '--kubeconfig=c:\k\config'
    '--hairpin-mode=promiscuous-bridge'
    '--image-pull-progress-deadline=20m'
    '--cgroups-per-qos=false'
    "--log-dir=c:\k"
    '--logtostderr=false'
    '--enforce-node-allocatable=""'
    '--network-plugin=cni'
    '--cni-bin-dir="c:\k\cni"'
    '--cni-conf-dir="c:\k\cni\config"'
    "--node-ip=182.182.0.5"
)

```
