### ISSUE TITLE
provided port is already allocated？？？？

### ISSUE THREAD

**Issue by mengxifl** [kubernetes/kubernetes#76764]
HI  
I have one problem 

I have two slave nodes. I have three services like this

A node  | A service -- Nodeport--use port 123
B node  | B service -- Nodeport -- use port 123

i want to client access A service this is A app and access B service this is B app and client user app add Different host address. like this yaml

apiVersion: v1
```
kind: Service
metadata:
  name: pdns-master-svc
  namespace: default
spec: 
  type: NodePort
  externalIPs:
  - 172.16.254.80
  externalTrafficPolicy: Local
  selector:
    app: dns
    role: master
  ports:
  - name: dnsport
    protocol: UDP
    nodePort: 53 
    port: 53
    targetPort: 53
```

B service 
```
apiVersion: v1
kind: Service
metadata:
  name: dns-recursor-svc
  namespace: default
spec: 
  type: NodePort
  externalIPs:
 - 172.16.254.81
  externalTrafficPolicy: Local
  selector:
    app: dns-recursor
 ports:
  - name: recursor-port
    protocol: UDP
    nodePort: 53 
    port: 53
    targetPort: 53

```
Is there a way？ Or maybe I configured it wrong？
