### ISSUE TITLE
Support customizing kubectl describe response for CRDs

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#76789]
We develop a database operator project called kubedb.com. Using CRDs, users can deploy databases on Kubernetes. One of the things we would like to do is show more useful information to the user when `kubectl describe` command is used. Currently we have built a separate cli for this. It will be better for UX if kubectl describe could be customized. Here is an example of extra information we show:

![kubedb-describe](https://user-images.githubusercontent.com/94814/56387268-b93b1d00-61d8-11e9-84d1-fdde2d077371.png)

I could see 2 ways to do this:

Option 1: Support shadowing kubectl built-in commands. It is my understanding that this is not supported currently. There are various security implications of doing this.

Option 2: Support customization options via CRD spec similar to how `additionalPrinterColumns` works. In this approach, we could specify in the CRD the additional types of resources to show.

```
spec:
  additionalDescription:
  - apiVersion: apps/v1
    kind: StatefulSet
    selectorKeys: ["kubedb.com/kind", "kubedb.com/name"]
  - apiVersion: v1
    kind: Service
    selectorKeys: ["kubedb.com/kind", "kubedb.com/name"]
  - apiVersion: v1
    kind: Secret
    selectorKeys: ["kubedb.com/kind", "kubedb.com/name"]
  - apiVersion: kubedb.com/v1alpha1
    kind: Snapshot
    selectorKeys: ["kubedb.com/kind", "kubedb.com/name"]
```

One interesting question is how to differentiate between things to be shown as single item vs table? For example, if you look at the screen shot, we show 2 services as separate details but snapshots as table. In case of tables the `additionalPrinterColumns` of the resource type can be used.

Does the option 2 sounds reasonable? If so, we are interested in exploring KEP etc.
