### ISSUE TITLE
Kubernates Ingress deploy Angular assets(image) not show

### ISSUE THREAD

**Issue by khanghyxda** [kubernetes/kubernetes#76802]
I use Docker to package the Angular project(Container use Nginx). When running on Docker, the image show ok, but when deploying Kubernates using Ingress, all images in assets folder does not appear.

Content-Type running on Docker. It' OK.
![image](https://user-images.githubusercontent.com/5491573/56399908-e1d01f00-628b-11e9-8dd6-adc71873e98b.png)

But when running on Kubernates. Content type always is text/html.
![image](https://user-images.githubusercontent.com/5491573/56399895-bbaa7f00-628b-11e9-9108-9e5631dfe9ea.png)

Config Ingress Kubernates. Service name ssite.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: abc-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "swing-static-ip"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.gcp.kubernetes.io/pre-shared-cert: "abc,xyz"
spec:
  rules:
  - host: abc.com
    http:
      paths:
      - backend:
          serviceName: sservice
          servicePort: 8000
  - host: xyz.com
    http:
      paths:
      - path : /
        backend:
          serviceName: ssite
          servicePort: 80
      - path : /*
        backend:
          serviceName: ssite
          servicePort: 80
```
