### ISSUE TITLE
Bug exist in  Pod Priority and Preemption

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#76836]
**What happened**:

I set up a cluster with 2 nodes. I used 2 rs to test preemption.  2  yamls of rs are as flow:

```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
  name: webcritial1
  namespace: default
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginxcritial1
  template:
    metadata:
      labels:
        app: nginxcritial1
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginxcritial1
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
``` 
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
  name: webcritial
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginxcritial
  template:
    metadata:
      labels:
        app: nginxcritial
    spec:
      priorityClassName: system-node-critical
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginxcritial
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

1. I first created  the rs webcritial.
2. created  the rs webcritial1.

results are like this:

![image](https://user-images.githubusercontent.com/12230714/56435685-f5bb6580-630b-11e9-824c-cf350dae8571.png)

![image](https://user-images.githubusercontent.com/12230714/56435482-277ffc80-630b-11e9-937e-2d5b68bcaec1.png)

![image](https://user-images.githubusercontent.com/12230714/56435607-a6753500-630b-11e9-8703-5b61338dd2e5.png)

webcritial with high priority can not creatiepod successfully.

**What you expected to happen**:

webcritial with high priority can create pod successfully. pods of webcritial1 would be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

write the yaml as I pasted and run it.

**Anything else we need to know?**:

When set the priority directly,  preemption can work which use priorityClass can not work

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
