### ISSUE TITLE
RollingUpdate daemonset got stucked

### ISSUE THREAD

**Issue by DaiHao** [kubernetes/kubernetes#77203]
**What happened**:

RollingUpdate daemonset got stucked, leaves a few pod not updated. 

Daemonset's status are as follows:
```yaml
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 2
  numberUnavailable: 1
  observedGeneration: 12
  updatedNumberScheduled: 2
```

```
NAME           DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
foo-daemonset   2         2         2         2            1           <none>          3d2h
```

**What you expected to happen**:

All pods managed by daemonset upgrade succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1. config minReadySeconds for deamonset
2. daemon-controller's clock time is a little slower than node. 

**Anything else we need to know?**:
related issue #41641 and pr #42097

**Environment**:
the latest k8s version also has this bug
