### ISSUE TITLE
Persistence Volume Resize doesn't work for block volume

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes/kubernetes#77294]
**What happened**:
I created a block EBS volume using dynamic provisioning. Then I resized the volume from 10GB to 20 GB. Both PV and block volume reflects the change, but the PVC's capacity is still 10GB.

```sh
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                 STORAGECLASS   REASON   AGE
pvc-e4171b0e-6bd3-11e9-8a17-0ae1b2749708   20Gi       RWO            Delete           Bound      default/block-claim   ebs-sc                  3m50s
```
```sh
sh-4.2# lsblk
NAME    MAJ:MIN   RM    SIZE RO TYPE MOUNTPOINT
loop0     7:0      0     10G  0 loop
xvda    202:0      0    128G  0 disk
|-xvda1 202:1      0 1007.5K  0 part
`-xvda2 202:2      0    128G  0 part /etc/hosts
xvdci   202:22016  0     20G  0 disk
```

```sh
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
block-claim   Bound    pvc-e4171b0e-6bd3-11e9-8a17-0ae1b2749708   10Gi       RWO            ebs-sc         4m7s
```

This could be caused by in-tree resize put the PVC condition under `FileSystemResizePending` state, but no one is acting on the condition since it is block volume:
```sh
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 10Gi
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2019-05-01T05:50:31Z"
      message: Waiting for user to (re-)start a pod to finish file system resize of
        volume on node.
      status: "True"
      type: FileSystemResizePending
    phase: Bound
```
/cc @gnufied @msau42 @saad-ali @davidz627 
/sig storage

**What you expected to happen**:
PVC's capacity should be updated to 20GB

**How to reproduce it (as minimally and precisely as possible)**:
Easy to reproduce using following specs:

StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: kubernetes.io/aws-ebs 
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

Claim:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: ebs-sc 
  resources:
    requests:
      storage: 10Gi
```

Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: app 
spec:
  containers:
  - name: app 
    image: amazonlinux:2 
    command: ["/bin/sh", "-c"]
    args: ["tail -f /dev/null"]
    volumeDevices:
    - name: data
      devicePath: /dev/xvda
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: block-claim
```

**Anything else we need to know?**:
This will affect whether CSI migration should handle migration scenario for block volume resizing.

**Environment**:
- Kubernetes version (use `kubectl version`):1.13
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: kops
- Network plugin and version (if this is a network-related bug):
- Others:
