### ISSUE TITLE
Ignoring the PVC error when not using storageClass correctly

### ISSUE THREAD

**Issue by mauilion** [kubernetes/kubernetes#77404]
**What happened**:
When working with an nfs pv,pvc as specified here:

pv-volume.yaml
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/shared
    server: "172.17.0.1"
  persistentVolumeReclaimPolicy: Retain
```
pv-claim.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  selector:
    matchLabels:
      type: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: "task-pv-volume"
```
pod.yaml
```
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
```
I get an error in the logs:

```
Warning    ExternalExpanding  35s   volume_expand  Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
Mounted By:  task-pv-pod
```

**What you expected to happen**:
This same set of manifests worked prior to the introduction of the code outputting the error.
[expand_controller.go](https://github.com/kubernetes/kubernetes/blob/6c31101257bfcd47fa53702cea07fe2eedf2ad92/pkg/controller/volume/expand/expand_controller.go)
```
volumePlugin, err := expc.volumePluginMgr.FindExpandablePluginBySpec(volumeSpec)
if err != nil || volumePlugin == nil {
    err = fmt.Errorf("didn't find a plugin capable of expanding the volume; " +
        "waiting for an external controller to process this PVC")
 ```
This is tricky thing cause nfs doesn't support resizing. 

**How to reproduce it (as minimally and precisely as possible)**:
Bring up a 1.13.5 cluster with a default storage class defined.
Then apply the above manifests.

**Anything else we need to know?**:
To work around this issue I was able to introduce an arbitrary storageClassName
Fixed Manifests:
```
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume2
  labels:
    type: local2
spec:
  storageClassName: manual2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/shared
    server: "172.17.0.1"
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim2
spec:
  storageClassName: manual2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod2
spec:
  volumes:
    - name: task-pv-storage2
      persistentVolumeClaim:
       claimName: task-pv-claim2
  containers:
    - name: task-pv-container2
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage2
```
**Environment**:
- Kubernetes version (use `kubectl version`):
 kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-20T16:54:39Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
bare metal
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04.1 LTS 
- Kernel (e.g. `uname -a`): 4.18.0-16-generic
- Install tools: kind, kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:
