### ISSUE TITLE
ReplicaSet leaves inactive pod not counted in its replicas

### ISSUE THREAD

**Issue by yuchengwu** [kubernetes/kubernetes#77597]
**What happened**:
ReplicaSet leaves inactive pod not counted in its replicas

**What you expected to happen**:
ReplicaSet should count all matched pods with its selector

**How to reproduce it (as minimally and precisely as possible)**:
It will be reliably reproduced if somebody can make step 2 happen
step 1. create a deployment with replicas=x 
step 2. make some pods created from step 1 inactive, take some method to make them status phase to `Succeeded` or `Failed`, e.g. we have 1 failed pod owned by rs 
step 3. rs replicas=x, though actually we have x+1 matched pod

Below is a example observed from our product environment
1. rs `hbasersjsxgj-4180831554` replicas=3, 
![Selection_128](https://user-images.githubusercontent.com/13599124/57381620-dbbfc500-71dd-11e9-93f1-4ee1eb78541a.png)
2. All of its 3 replicas pod are up and running, got one extra pod `hbasersjsxgj-4180831554-v80jr` 
![Selection_129](https://user-images.githubusercontent.com/13599124/57381769-2f321300-71de-11e9-8dca-c0adf0f0712e.png)
3. we check rs hbasersjsxgj-4180831554  label selector, pod hbasersjsxgj-4180831554-v80jr label and ownerReference, confirm that this pod is owned by this rs
3.1 this is rs label selector
![Selection_130](https://user-images.githubusercontent.com/13599124/57381963-964fc780-71de-11e9-9e63-1cd1ea1d1a76.png)
3.2 this is pod label and ownerRererence
[hbasersjsxgj-4180831554-v80jr.yaml.txt](https://github.com/kubernetes/kubernetes/files/3157804/hbasersjsxgj-4180831554-v80jr.yaml.txt)

 
```
...
  labels:
    pod-template-hash: "4180831554"
    transwarp.alias: hyperbase_cmsdm
    transwarp.install: 44pl8
    transwarp.meta.app.id: "33"
    transwarp.meta.app.name: hyperbase
    transwarp.meta.app.version: "5.1"
    transwarp.name: hbaseregionserver
  name: hbasersjsxgj-4180831554-v80jr
  namespace: cmsdm
  ownerReferences:
  - apiVersion: extensions/v1beta1
    controller: true
    kind: ReplicaSet
    name: hbasersjsxgj-4180831554
    uid: 10a80413-08f3-11e9-90a7-e8611f1e0772
...
```

**Anything else we need to know?**:
RS will ignore inactive pod
https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/controller/controller_ref_manager.go#L62-L66
https://github.com/kubernetes/kubernetes/blob/f35802d3a00b37a32476451266af05ce9760fec0/pkg/controller/controller_ref_manager.go#L62-L66

That's probably why we have one extra pod because pod `hbasersjsxgj-4180831554-v80jr` .status.phase is Failed and treated as a inactive pod, RS ignored it.
https://github.com/kubernetes/kubernetes/blob/release-1.5/pkg/controller/controller_utils.go#L724-L728
https://github.com/kubernetes/kubernetes/blob/f35802d3a00b37a32476451266af05ce9760fec0/pkg/controller/controller_utils.go#L724-L728

**Environment**:
production environment

- Kubernetes version (use `kubectl version`):
release-1.5
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
