### ISSUE TITLE
Allows configmap to reference existing configmap

### ISSUE THREAD

**Issue by hero-zhanghao** [kubernetes/kubernetes#77632]
**What would you like to be added**:
For example, I have an existing configmap, configured like this:

`
apiVersion: v1
kind: ConfigMap
metadata:
  name: a-config
data:
  application.properties: |-
    test.name=aaa
`
Then, in the subsequent operation, a new project is added. The required configmap is as follows:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: b-config
data:
  application.properties: |-
    test.nikename=aaa
```
It can be seen that their keys are different, but the values are the same. In b-config, it is hoped that:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: b-config
data:
  application.properties: |-
    test.nikename=${a-config}.${test.name}
```

**Why is this needed**:

When using configmap, sometimes the same value will be configured to different keys and applied in different pod. If the definition is changed for many times, it is easy to miss a certain value when it needs to be changed.
