### ISSUE TITLE
pods scheduled to nodes having a high number of mounting points take long time to startup

### ISSUE THREAD

**Issue by oulydna** [kubernetes/kubernetes#77637]
**What happened**:
pods scheduled to nodes having a high number of mounting points take long time to startup

**What you expected to happen**:
The number of existing mount points on the node shouldn't affect new pod's starting up time that terribly (at all).

**How to reproduce it (as minimally and precisely as possible)**:
Make a couple of nodes in your cluster have different numbers of mounting points. 
In mine, the problematic node has around 400 mounting points ( `df | wc -`), the other has only 200. Then schedule a pod requesting an emptyDir volume (or from configMap, as long as there is a volume request) to different nodes. It should be noticed pods scheduled to the node with the highest number of mounting points have the highest starting up time. An example pod manifest can be:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume
  labels:
    slowness: test
spec:
  containers:
  - args:
    - sleep
    - "3600"
    name: test-pod
    image: ubuntu:18.04
    imagePullPolicy: IfNotPresent
  volumes:
  - name: home
    emptyDir: {}
  nodeName: node-0
```

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`):
1.12.8
- Cloud provider or hardware configuration:
Bare metal. 
- OS (e.g: `cat /etc/os-release`):
CentOS 7
- Kernel (e.g. `uname -a`):
4.9.40
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:
