### ISSUE TITLE
BoundServiceAccountTokenVolume: kube-proxy doesn't reload ServiceAccount tokens

### ISSUE THREAD

**Issue by yanniszark** [kubernetes/kubernetes#77651]
**What happened**:

This all happened in a `GKE 1.13.5-gke.10` alpha cluster.

1. `kube-proxy` stopped working and inspecting the logs showed messages like:
```
E0509 02:05:11.750695       6 reflector.go:125] k8s.io/client-go/informers/factory.go:132: Failed to list *v1.Service: Unauthorized
E0509 02:05:11.755213       6 reflector.go:125] k8s.io/client-go/informers/factory.go:132: Failed to list *v1.Endpoints: Unauthorized
```
2. Upon inspection of the kube-proxy Pod, I saw it was using the `BoundServiceAccountTokenVolume` feature. Notice that the expirationSeconds is 1 hour. This is exactly how much time kube-proxy was working correctly before it started throwing errors, which I confirmed from the logs.
```yaml
volumeMounts:                                                                                                                                                                                                                                                                                                                                                                                         
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount                                                                                                                                                     
      name: kube-api-access-7mbbq                                                                                                                                                                                  
      readOnly: true

volumes:
- name: kube-api-access-7mbbq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3600
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

3. Recreating the Pod (deleting and letting DaemonSet create it again) fixed the problem, which indicated that `kube-proxy` is not reloading the ServiceAccount token.

There could also be problems with other controllers.
I just didn't happen to stumble upon them.

**What you expected to happen**:

I would expect `kube-proxy` to work.
The observed behaviour is possibly due to `kube-proxy` not reloading the ServiceAccount token.

**How to reproduce it (as minimally and precisely as possible)**:

Generally, you need a K8s 1.13 Cluster with the BoundServiceAccountTokenVolume Feature Gate enabled. I will use GKE as this is the environment I was using when stumbling upon this.

1. Create a `GKE 1.13.5-gke.10` alpha cluster (public preview) (any 1.13 cluster should work).
2. Wait for 1 hour (confirm that kube-proxy's SA token expires in 3600 seconds).
3. SSH into the node and view kube-proxy logs: `cat /var/log/kube-proxy.log`

**Anything else we need to know?**:

This was reported in the Kubernetes Slack, in the #gke channel.
@mikedanese was very helpful, managed to reproduce the issue and has filed #77613 which could be a fix.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.5-gke.10", GitCommit:"f5949b3427099d4e410ef96d6e0fea3cd4794e10", GitTreeState:"clean", BuildDate:"2019-04-10T19:05:37Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GKE 1.13.5-gke.10
- OS (e.g: `cat /etc/os-release`): 18.04.2 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): 4.15.0-1029-gcp
- Install tools: GKE
- Network plugin and version (if this is a network-related bug): 
- Others:
