### ISSUE TITLE
Liveness/Readiness check for external Endpoints Services

### ISSUE THREAD

**Issue by MartinEmrich** [kubernetes/kubernetes#77738]
**What would you like to be added**:

Liveness/Readiness checks for external Endpoints.

As I understand, kube-proxy does load-balancing over `Endpoints` with multiple targets like

```
apiVersion: v1
kind: Endpoints
metadata:
  name: someClusterOfAServiceOutsideOfTheKubernetesCluster
subsets:
- addresses:
  - ip: 10.32.123.456
  - ip: 10.32.234.567
  - ip: 10.32.345.678
  ports:
  - port: 1234
```

But the documentation is not clear (to me) what happens if one of these three backends does not work, but I assume that addresses with the `port` closed are excluded from load balancing? But what about retry intervals or check intervals?

**Why would this be nice**:

Adding liveness/readiness probes to `Endpoints` would make this configurable, e.g. to check either simple reachability (TCP) or periodically calling a liveness route (e.g. HTTP call to /myservice/alive an checking for `200 OK`).

This might look like:

```
apiVersion: v1
kind: Endpoints
metadata:
  name: someClusterOfAServiceOutsideOfTheKubernetesCluster
subsets:
- addresses:
  - ip: 10.32.123.456
  - ip: 10.32.234.567
  - ip: 10.32.345.678
  ports:
  - port: 1234
  readinessProbe:
    httpGet:
      path: /myservice/alive
    periodSeconds: 15
```

Maybe this would be out of scope for Kubernetes (and best practice would be to use a loadbalancer like haproxy in a small pod), but maybe the Idea is not bad?
