### ISSUE TITLE
AWS ELB configuration changed

### ISSUE THREAD

**Issue by MilanDasek** [kubernetes/kubernetes#77813]
Hello,

I experienced weird situation where AWS classic ELB was changed.

I have this annotations on service (ingress service)
```
Annotations:
  service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: *
  service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:redacted:certificate/redacted
  service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
```

which effectively creates ELB with settings that HTTP and HTTPS ports are set to backend ports (which are dynamic like   
![image](https://user-images.githubusercontent.com/12279315/57626482-441ff500-7596-11e9-9054-aac589652c58.png)

BUT Instance port for HTTPS is set to service nodePort 30864
```
    - name: kong-proxy-tls
      nodePort: 30864
      port: 443
      protocol: TCP
      targetPort: 8443
```

so I have changed HTTPS port manually to the same port as HTTP (I want decrypt SSL on ELB and send HTTP to EKS/Kong ingress) and it worked for 20 days.

After those 20 days, it has been changed back to HTTPS port (internal dynamic one).

I don't know why it was initiated.

Can you please help?

The best way would be to make sure it will stay like I want. Maybe somehow tell kube that it should ignore any changes?

Thank you
