### ISSUE TITLE
NFS volume is not writable for non-root user 

### ISSUE THREAD

**Issue by nkkashyap** [kubernetes/kubernetes#77986]
**What happened**:
A pod running as non-root user (with `securityContext` set) is not able to create a directory under NFS Volume. The `mkdir` cmd is throwing `Permission denied`
`mkdir: cannot create directory '/mnt/nfsvol/userdata': Permission denied`

**What you expected to happen**:
With with securityContext set (`runAsUser: 2020` and  `fsGroup: 2020`) the POD should be able to create and write to a file under NF Volume

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster in IBM Cloud Kubernetes Service(IKS)
2. Create a PVC using `ibmc-file-silver` storage-class
3. Create a POD with security context
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-devtest
  namespace: nkashyap
spec:
  volumes:
    - name: nsf-vol
      persistentVolumeClaim:
        claimName: pvc-nfs  
  securityContext:
    runAsUser: 2020
    fsGroup: 2020
  containers:
    - name: devtest-perf
      image: gcr.io/google-samples/node-hello:1.0
      imagePullPolicy: Always
      volumeMounts:
      - name: nsf-vol
        mountPath: /mnt/nfsvol
```

**Anything else we need to know?**:
In one of the use case, shared volume is required in production environment. And because of security policy restriction the POD cannot run with root user. We have to set securityContext set (`runAsUser: 2020` and  `fsGroup: 2020`). But with this non-root user is not able to create a directory under or write a file under NFS Volume.
This issue is getting fixed for us when we enabled `fsGroup` for NFS Driver
```
root@nkdev01:~/kubernetes# git diff
diff --git a/pkg/volume/nfs/nfs.go b/pkg/volume/nfs/nfs.go
index 588687c..4a297eb 100644
--- a/pkg/volume/nfs/nfs.go
+++ b/pkg/volume/nfs/nfs.go
@@ -20,7 +20,7 @@ import (
        "fmt"
        "os"
        "runtime"
-
+       "syscall"
        "github.com/golang/glog"
        "k8s.io/api/core/v1"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
@@ -277,6 +277,10 @@ func (b *nfsMounter) SetUpAt(dir string, fsGroup *int64) error {
                os.Remove(dir)
                return err
        }
+       fileInfo, _ := os.Stat(b.GetPath())
+       if (fileInfo.Sys().(*syscall.Stat_t).Gid) != uint32(*fsGroup){
+               volume.SetVolumeOwnership(b, fsGroup)
+       }
        return nil
 }
```

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.12.7`
- Cloud provider or hardware configuration: `IKS`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 18.04.2 LTS`
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nkkashyap** [comment]
@kubernetes/sig-Storage

**Comment by gustavovalverde** [comment]
This doesn't allow to use GKE with NFS Filestore in Google; as a non-root user 

P.D.: Who runs their containers as root?

**Comment by CamelCaseNotation** [comment]
I've seen multiple issues around volumes being created as root user such that non-root Pods are not able to read or write to them once mounted. All the issues I've found around this have been open. Why is this a problem that is being ignored by the kubernetes community? Could someone provide examples of best practices such that this does not happen? People should not be expected to run their containers as root.

**Comment by zoltan-nz** [comment]
@CamelCaseNotation Had the same issue and found [this discussion](https://stackoverflow.com/questions/35213589/docker-container-with-non-root-user-deployed-in-google-container-engine-can-not/35235370). 

Adding `fsGroup` property to the pod specification solved the issue:
```
    spec:
      securityContext:
        fsGroup: 1024
```

An example with using a standard volume in Google Kubernetes Engine.

In `Dockerfile`:
```Dockerfile
...
RUN mkdir /home/app
RUN addgroup --gid 1024 app-group
RUN useradd --uid 1024 --gid 1024 --non-unique --comment "" --home-dir /home/app app
RUN chown 1024:1024 /home/app
RUN chmod 775 /home/app
RUN chmod g+s /home/app
WORKDIR /home/app
USER app

# Create a directory for the database and expose as a volume for persistence
RUN mkdir /home/app/db
RUN chown 1024:1024 /home/app/db
VOLUME /home/app/db
...
```

In `deployment.yaml`

```yaml
...
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1M

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      securityContext:
        fsGroup: 1024
      containers:
        - name: demo-app
          image: some-image
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: /home/app/db
              name: db
      initContainers:
        - name: demo-app-init
          image: some-image
          command: ['touch', '/home/app/db/some.txt']
          volumeMounts:
            - mountPath: /home/app/db
              name: db
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: demo-persistent-volume-claim

---
...
```
