### ISSUE TITLE
balancerWrapper always in kube-apiserver logs

### ISSUE THREAD

**Issue by boxuan666** [kubernetes/kubernetes#78067]
i'm using kubeadm to installed k8s cluster.
the kubeadm and k8s version is 1.14.1.

my kubeadm-config file config like this:
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.14.1

clusterName: k8s-platform
controlPlaneEndpoint: "k8s-pf1-lb:6000"
imageRepository: myRepository

dns:
  type: CoreDNS

etcd:
  local:
    dataDir: /var/lib/etcd

scheduler:
  extraArgs:
    address: 0.0.0.0

controllerManager:
  extraArgs:
    bind-address: 0.0.0.0

networking:
  dnsDomain: cluster.local
  podSubnet: "172.23.128.0/17"
  serviceSubnet: "172.23.112.0/20"

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: "lc"
  syncPeriod: 30s
mode: "ipvs"
```

After the installation is complete, everything works fine, but the 
```
asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
```
is repeated in the apiserver log.

Is this a bug? I see that it is info level log message, how can I block it?
