### ISSUE TITLE
HostPath PV is stuck at terminating when claimed from StatefulSet

### ISSUE THREAD

**Issue by ganchandrasekaran** [kubernetes/kubernetes#78106]
**What happened**:
Trying to delete the deployment, but the PV is stuck at Terminating status forever. However claims made from Kind: Deployment and the PV claimed for it doesn't have any problem terminating successfully. 

**What you expected to happen**:
All pods, services and PV disappear after terminating. 

**How to reproduce it (as minimally and precisely as possible)**:
```
# kubectl describe pv elasticsearch-data-001
Name:            elasticsearch-data-001
Labels:          <none>
Annotations:     pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    esdata
Status:          Terminating (lasts <invalid>)
Claim:           abc/data-elasticsearch-data-0
Reclaim Policy:  Delete
Access Modes:    RWO
VolumeMode:      Filesystem
Capacity:        2Gi
Node Affinity:   <none>
Message:
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /mnt/k8s-pv/es-data-001
    HostPathType:
Events:            <none>
```
Make a claim for it from StatefulSet
```
kind: StatefulSet
...
  volumeClaimTemplates:
  - metadata:
      name: abc
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: esdata
      resources:
        requests:
          storage: 1Gi
```
**Anything else we need to know?**:
Ofcourse as suggested in [bugReport](https://github.com/kubernetes/kubernetes/issues/69697) solves the issue. 
```
kubectl patch pvc db-pv-claim -p '{"metadata":{"finalizers":null}}'
kubectl patch pod db-74755f6698-8td72 -p '{"metadata":{"finalizers":null}}'
```
But this creates two problem. 
1, I am not able to redploy the same chart without manually deleting these PVs as the chart produces the same PV names. 
2, After I manually delete the PVs, I change the name of PV on the chart and redeploy. But the Kubernetes assigns the OLD PV that doesn't exist anymore to my Claim. THIS MEANS THAT THE ABOVE STEP DOESN'T REMOVE THE PV COMPLETELY. 

Any insight would be appreciated! Thanks

@saad-ali 
@childsb
