### ISSUE TITLE
Unstable DNS response after startup of pod

### ISSUE THREAD

**Issue by fin-ger** [kubernetes/kubernetes#78128]
**What happened**:

I am using this config to debug why a domain cannot be resolved after startup of my application:

```
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  clusterIP: None
  ports:
  - name: test
    port: 1337
  selector:
    app.kubernetes.io/name: test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-set
spec:
  serviceName: test-service
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
    spec:
      containers:
        - name: dns-debug
          image: googlecontainer/dnsutils
          command:
            - /bin/bash
            - -c
            - |-
              while true; do echo nslookup $ADDRESS:; nslookup $ADDRESS; sleep 1; done
          env:
            - name: ADDRESS
              value: test-set-0.test-service
          ports:
             - name: test
               containerPort: 1337
               protocol: TCP
```

When deploying this, the following logs are produced:

```
$ kubectl logs test-set-0 
nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

** server can't find test-set-0.test-service: REFUSED

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	test-set-0.test-service.default.svc.cluster.local
Address: 172.17.0.8

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
Name:	test-set-0.test-service.default.svc.cluster.local
Address: 172.17.0.8

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
Name:	test-set-0.test-service.default.svc.cluster.local
Address: 172.17.0.8

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
Name:	test-set-0.test-service.default.svc.cluster.local
Address: 172.17.0.8

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

** server can't find test-set-0.test-service: REFUSED

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

** server can't find test-set-0.test-service: REFUSED

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

** server can't find test-set-0.test-service: NXDOMAIN

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

** server can't find test-set-0.test-service: NXDOMAIN

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

** server can't find test-set-0.test-service: NXDOMAIN

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

** server can't find test-set-0.test-service: REFUSED

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
Name:	test-set-0.test-service.default.svc.cluster.local
Address: 172.17.0.8

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

** server can't find test-set-0.test-service: NXDOMAIN

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
Name:	test-set-0.test-service.default.svc.cluster.local
Address: 172.17.0.8

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

** server can't find test-set-0.test-service: REFUSED

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
Name:	test-set-0.test-service.default.svc.cluster.local
Address: 172.17.0.8

nslookup test-set-0.test-service:
Server:		10.96.0.10
Address:	10.96.0.10#53
```

Which means that during the first ~30 seconds of the pod, the domain could only be resolved *sometimes*...

**What you expected to happen**:
I expect the domain to be resolvable directly after startup.

**How to reproduce it (as minimally and precisely as possible)**:
Use the above config and run:

```
$ kubectl apply -f test.yaml
$ kubectl logs test-set-0
```

**Anything else we need to know?**:
This was tested on a fresh minikube setup.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.1 (client and server)
- I am using minikube v1.0.1
