### ISSUE TITLE
HPA not respecting lifecycle podStart

### ISSUE THREAD

**Issue by gd-jroberts** [kubernetes/kubernetes#78142]
**What happened**:
When our WordPress pod with two containers (nginx and php-fpm) autoscaled via the HPA, the lifecycle podStart command does not apply the same as in the original deployment, resulting in the php-fpm container writing files as the root user instead of www-data.

**What you expected to happen**:
I expected the podStart container lifecycle hook to chown the target directory for the www-data user. It did not, which I think means that the target directory will retain the user permissions under which it was mounted, which means root instead of www-data. 

**How to reproduce it (as minimally and precisely as possible)**:

Create two busybox init containers that copy code into a shared volume for nginx and php-fpm. Then trigger the HPA to autoscale. Our developers' themes create a theme-styles.css file in wp-content/uploads when the file does not exist and the WordPress loop is triggered. This file is being written by the root user on HPA autoscaled instances, but on the original pod it is being written by the www-data user.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: wordpress
  name: wordpress
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
        date: "1558110630"
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - envsubst '\$STORAGE_BUCKET' < /etc/nginx/conf.d/uploads.template > /etc/nginx/conf.d/uploads.conf
          && exec nginx -g 'daemon off;'
        env:
        - name: STORAGE_BUCKET
          value: gcs-dev-assets
        image: nginx:1.14.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz.php
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: nginx
        ports:
        - containerPort: 80
          name: wordpress
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz.php
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 40m
            memory: 20Mi
          requests:
            cpu: 20m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: code
        - mountPath: /var/run/nginx-fastcgi-cache
          name: nginx-fastcgi-cache
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config-volume
          subPath: nginx.conf
        - mountPath: /etc/nginx/conf.d/aliases.conf
          name: nginx-aliases-config-volume
          subPath: aliases.conf
        - mountPath: /etc/nginx/conf.d/redirects.conf
          name: nginx-redirects-config-volume
          subPath: redirects.conf
        - mountPath: /etc/nginx/conf.d/uploads.template
          name: nginx-config-volume
          subPath: uploads.template
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/run/secret/cloud.google.com/secret
        - name: DB_HOST
          value: mysql-sqlproxy-gcloud-sqlproxy.cloudsql-proxy.svc.cluster.local
        - name: DB_NAME
          value: db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials
        - name: DB_PREFIX
          value: wpgd_
        image: php-fpm:7.3
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - mkdir -p /var/www/html/web/app/wflogs && chown -R 101:101 /var/www/html/web/app
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 2
        name: php-fpm
        ports:
        - containerPort: 9000
          name: php-fpm
          protocol: TCP
        resources:
          limits:
            cpu: 1500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: code
        - mountPath: /var/www/html/web/app/nginx-fast-cgi-cache
          name: nginx-fastcgi-cache
        - mountPath: /usr/local/etc/php/conf.d/custom.ini
          name: php-fpm-config-volume
          subPath: custom.ini
        - mountPath: /usr/local/etc/php-fpm.d/www.conf
          name: php-fpm-config-volume
          subPath: www.conf
        - mountPath: /var/run/secret/cloud.google.com
          name: storage-auth-credentials
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gcr-object-viewer
      initContainers:
      - command:
        - cp
        - -r
        - /app/.
        - /srv
        image: private-registry-busybox-code-container:label
        imagePullPolicy: Always
        name: init-core
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /srv
          name: code
      - command:
        - cp
        - -r
        - /app/.
        - /srv
        image: private-registry-busybox-code-container:label
        imagePullPolicy: Always
        name: init-custom
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /srv
          name: code
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: code
      - emptyDir: {}
        name: nginx-fastcgi-cache
      - configMap:
          defaultMode: 420
          name: nginx-config
        name: nginx-config-volume
      - configMap:
          defaultMode: 420
          name: nginx-aliases-config
        name: nginx-aliases-config-volume
      - configMap:
          defaultMode: 420
          name: nginx-redirects-config
        name: nginx-redirects-config-volume
      - configMap:
          defaultMode: 420
          name: php-fpm-config
        name: php-fpm-config-volume
      - name: sql
        secret:
          defaultMode: 420
          secretName: sql
      - name: storage-auth-credentials
        secret:
          defaultMode: 420
          secretName: storage-auth-credentials
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```json
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.10", GitCommit:"8d9b8641e72cf7c96efa61421e87f96387242ba1", GitTreeState:"clean", BuildDate:"2019-04-12T22:59:24Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

Any insight would be appreciated.

- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): COS
- Kernel (e.g. `uname -a`): 4.14.106+
- Install tools:
- Network plugin and version (if this is a network-related bug): Calico
- Others:
