### ISSUE TITLE
Incorrect error message when creating StatefulSets

### ISSUE THREAD

**Issue by thatreguy** [kubernetes/kubernetes#78203]
**What happened**:
cat file.yaml
```
Tried to a StatefulSet:
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  labels:
    app: nginx
spec:
  serviceName: "nginx"
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        imagePullPolicy: Always
status: {}
```

kubectl apply -f file.yaml
```
error: error validating "remote-terminal-deployment.yml": error validating data: ValidationError(StatefulSet.status): missing required field "replicas" in io.k8s.api.apps.v1.StatefulSetStatus; if you choose to ignore these errors, turn validation off with --validate=false

```
**What you expected to happen**:
Useful error message like:
status: {} is not supported

**How to reproduce it (as minimally and precisely as possible)**:
Simply take the above yaml and `kubectl apply -f .`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
digitalocean
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
- Kernel (e.g. `uname -a`):
Linux ubuntu-s-2vcpu-4gb-blr1-01 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by draveness** [comment]
I reproduced this on my laptop. But I'm not sure whether it is intentional or a bug?

**Comment by Joseph-Irving** [comment]
I don't think this is a bug, the error message is fairly clear, if you want to create an object with the status field you need to set replicas as that is a required field.
So if you applied the following yaml it would work:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  labels:
    app: nginx
spec:
  serviceName: "nginx"
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        imagePullPolicy: Always
status:
  replicas: 1
```
