### ISSUE TITLE
Error Forbidden: unknown while running kubectl wait

### ISSUE THREAD

**Issue by brycecr** [kubernetes/kubernetes#78227]
**What happened**:
I gave a user (user@example.com) very limited permissions in the kube-system namespace, specifically:
```
- apiGroups: ["extensions"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "update"]
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["list", "get"]

```
I then ran:
`kubectl -n kube-system scale deployment my-deployment --replicas=0 --as user@example.com && kubectl wait -n kube-system --for=delete pods -l k8s-app=my-deployment --as user@example.com
`

This was the output:
```
deployment.extensions/my-deployment scaled
Error from server (Forbidden): unknown
```

**What you expected to happen**:
I would have expected the Forbidden error to describe what permission I lack in order to run the kubectl wait command. In particular this is "watch" on pods, I discovered through trial and error.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the following roles/rolebindings:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: deployment-scaler
rules:
- apiGroups: ["extensions"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "update"]
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-deployments
  namespace: kube-system
subjects:
- kind: User
  name: user@example.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-scaler
  apiGroup: rbac.authorization.k8s.io
```

Create a deployment in kube-system called my-deployment with 1 available replica.
Then run
`kubectl -n kube-system scale deployment my-deployment --replicas=0 --as user@example.com && kubectl wait -n kube-system --for=delete pods -l k8s-app=my-deployemnt --as user@example.com`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.17", GitCommit:"b1adfec15b29a53b3dcf4af600952861b5819ede", GitTreeState:"clean", BuildDate:"2019-05-01T18:59:13Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
GKE 1.12.7, 3 node cluster
- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Kernel (e.g. `uname -a`):
Linux 4.19.28-2rodete1-amd64 #1 SMP Debian 4.19.28-2rodete1 (2019-03-18 > 2018) x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by brycecr** [comment]
@kubernetes/sig-cli

**Comment by pswica** [comment]
I can confirm, on test, that this issue exists. It ends up being pretty difficult, in my opinion. 

As stated above, it only affects pods and not deployments. 

Error is caused here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L1142

When I tested, I got `r.err == nil` and `!errors.IsUnexpectedServerError(r.err)`. Even if I forced to the next block, I had issues decoding `r.body`. 

This was the error message:  `no kind "PodList" is registered for version "v1" in scheme "k8s.io/client-go/dynamic/scheme.go:29" `

**Comment by caarlos0** [comment]
any workarounds?

**Comment by lexsys27** [comment]
I see this issue in `1.18.8` for `nodes`.

SA has following permissions:

```
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
```

Script should wait until node is ready:

```
kubectl wait --for=condition=Ready node -l dedicated=true --timeout 120s
```

Instead I get `Error from server (Forbidden): unknown` message. It is doesn't say what permissions `kubectl` miss so is not very helpful.

I believe this issue should be reopened.
