### ISSUE TITLE
 unable to create/update the DNS service: Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.96.0.10": field is immutable

### ISSUE THREAD

**Issue by parkjunhyo** [kubernetes/kubernetes#78235]
This is my environment (I used Ubuntu 16.04)
~# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

At first, I ran "sudo kubeadm init --config=kubeadm-config.yaml --experimental-upload-certs" with configuration below, In fact, I want to change Cluster IP range. So I added "serviceSubnet: 192.168.0.0/16"

apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 147.75.94.251
  bindPort: 6443

apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.14.1
clusterName: crenet-cluster
controlPlaneEndpoint: 147.75.94.251:6443
networking:
  serviceSubnet: 192.168.0.0/16
  podSubnet: 10.244.0.0/16
controllerManager:
  extraArgs:
    deployment-controller-sync-period: "50s"
etcd:
    external:
        endpoints:
        - https://147.75.92.69:2379
        caFile: /etc/kubernetes/pki/etcd/ca.crt
        certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
        keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd

After then, I have found some error. I think "serviceSubnet: 192.168.0.0/16" could be reason. So I delete this value on the configuration file. 

~# kubeadm reset
~# sudo kubeadm init --config=kubeadm-config.yaml --experimental-upload-certs

I have this error messages

error execution phase addon/coredns: unable to create/update the DNS service: Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.96.0.10": field is immutable

How can I solve this issue

/sig bug
/sig scheduling

**Comment by ihciah** [comment]
`podSubnet: 10.244.0.0/16` will cause:
```error execution phase addon/coredns: unable to create/update the DNS service: Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.96.0.10": field is immutable```.
I've tried adding the following config to disable CoreDNS:
```
dns:
  type: "kube-dns"
```
And the error was still the same.

To reproduce, use this config to init:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.10.22
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: master
  taints:
  - effect: PreferNoSchedule
    key: node-role.kubernetes.io/master
---
apiVersion: kubeadm.k8s.io/v1beta2
imageRepository: gcr.azk8s.cn/google_containers
kind: ClusterConfiguration
kubernetesVersion: v1.15.2
networking:
  podSubnet: 10.244.0.0/16
```
By the way, my kubeadm version is `1.15.2`.

**Comment by skoef** [comment]
I had the same issue, but it was solved when I explicitly set `serviceSubnet` in my `ClusterConfiguration`:

```yaml
kind: ClusterConfiguration
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
```
