### ISSUE TITLE
Cannot specify multiple node names for DaemonSet in matchFields selector

### ISSUE THREAD

**Issue by irony1692** [kubernetes/kubernetes#78238]
**What happened**:
An error occured when DaemonSets are created on multiple nodes with `matchFields` node selector.

**What you expected to happen**:
DaemonSet can be deployed on some specified nodes by their names. 

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl create -f sample-daemonset.yaml` like below,
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sample-daemonset
  labels:
    app: sample-daemonset-app
spec:
  selector:
    matchLabels:
      app: sample-daemonset-app
  template:
    metadata:
      labels:
        app: sample-daemonset-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchFields:
              - key: metadata.name
                operator: In
                values:
                - x.x.x.x
                - y.y.y.y
      containers:
      - name: sample-daemonset-python
        image: "python:3.6.8"
        imagePullPolicy: IfNotPresent
```
Then this error will occur.
```
The DaemonSet "sample-daemonset" is invalid: spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchFields[0].values: Required value: must be only one value when `operator` is 'In' or 'NotIn' for node field selector
```

**Anything else we need to know?**:
Corresponding codes are [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L3074-L3078) .

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6+IKS", GitCommit:"ac5f7341d5d0ce8ea8f206ba5b030dc9e9d4cc97", GitTreeState:"clean", BuildDate:"2019-05-09T13:26:51Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
`IBM Cloud Public (IKS)`
- OS (e.g: `cat /etc/os-release`):
`Ubuntu 18.04.2 LTS`
- Kernel (e.g. `uname -a`):
`4.15.0-47-generic`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
