### ISSUE TITLE
I need a statefulset that is also a daemonset - Proposal for a DaemonStatefulSet

### ISSUE THREAD

**Issue by johnjjung** [kubernetes/kubernetes#78256]
**What would you like to be added**: DaemonStatefulSet type, Automatic Node Labels

**Why is this needed**:

I have a situation where I need the numbered pod states that come from a statefulset, but is also one per node. Pretty much each pod needs a `process_number` argument so pod-1 needs to put in `process_number=1`, pod-2 needs to put in `process_number=2`.

Currently the way I accomplish this is:

```
clitool --process_num $(expr $(hostname | grep -o
          "[[:digit:]]*$"))
```

The Problem: is that occasionally enough, I get 2 pods in the same node

For each statefulset, because the hostname says `pod-1`, I'm able to use this as a unique process_number

It would be great if each of the nodes were automatically labeled AND if the statefulset had an option to have a podaffinity for each unique node by the process number.

It would be even more kickass if you had a entirely new type called a `DaemonStatefulSet`, that would just blow my mind

If anyone else knows how to accomplish with the current kubernetes system, thank you kindly~

**Comment by johnjjung** [comment]
@kubernetes/sig-scheduling-feature-requests

**Comment by resouer** [comment]
The DaemonSet + StatefulSet requirement actually makes sense to me.

**Comment by johnjjung** [comment]
I'm just wondering if any progress has been made on this, otherwise I think I'll have to do a workaround using some node-affinity and lots of labeling and yaml files for each process #

**Comment by johnjjung** [comment]
Just and update:

I was able to resolve my issue using an pod anti affinity

https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#tolerating-node-failure

Here is an example:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx 
  serviceName: "nginx"
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - nginx
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
```
