### ISSUE TITLE
httpGet postStart hook should retry on connection refused/timeout

### ISSUE THREAD

**Issue by mdavis-ciena** [kubernetes/kubernetes#78286]
**What would you like to be added**: Execution of the HTTP type postStart container lifecycle hook should be considered to have failed after connecting succeeds and a non-success HTTP status code is returned or a post-connection failure occurs such as premature closing of the TCP connection.  Failure to connect should _not_ be considered a failure of the hook itself, and the request should be re-attempted periodically until either the connection completes or some kind of appropriate delay has passed.

**Why is this needed**:  Consider the following test config:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hooktest
  labels:
    app: hooktest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hooktest
  template:
    metadata:
      labels:
        app: hooktest
    spec:
      containers:
      - name: app
        image: busybox:1.28
        command:
        - /bin/sh
        - -c
        - |
          sleep 0.1
          echo -e 'HTTP/1.1 204 No Content\n\n' | nc -l -p 8080 >/dev/null
          while true
          do
            sleep 1
          done
        lifecycle:
          postStart:
            httpGet:
              port: 8080
              path: /
```

Pods started by this Deployment on a generally non-busy system will fail.  The `kubectl get pod -l app=hooktest` command will report a status like:

    PostStartHookError: Get http://<pod-ip>:8080//: dial tcp <pod-ip>:8080: connect: connection refused

and `kubectl describe pod -l app=hooktest` will report an event like:

    Warning  FailedPostStartHook  <age>  kubelet, <node-name>  Http lifecycle hook (/) for Container "app" in Pod "hooktest-<hash>_<namespace>(<pod-uid>)" failed - error: Get http://<pod-ip>:8080//: dial tcp <pod-ip>:8080: connect: connection refused, message: ""

Only one HTTP request is made to the specified `postStart` hook, it is made immediately, and since the 0.1 second delay prior to the listen on port 8080 has not yet elapsed, the connection will be refused.  This delay simulates a small amount of startup time that a web server might require to e.g. initialize a runtime environment and/or process configuration before it can respond to HTTP requests.

If the `sleep 0.1` line is commented out or removed, the pod will start normally.

There seems to be no way to account for even a very minor delay in startup.  As reported in [issue 27114](https://github.com/kubernetes/kubernetes/issues/27114), execution of the `postStart` hook is not related to container liveness or readiness or their delays, and testing various liveness and readiness configurations seems to confirm this.  Despite the fact that describing the container reports the `FailedPostStartHook` event almost immediately, the pod's status is reported as `ContainerCreating` for a number of seconds in any case, indicating there is already a period during which the connection attempt could reasonably be repeated until giving up.

This has been tested in kubernetes 1.13.6, and I can find no issues or changelogs or other indications that this has been changed since.  In any case, the above configuration (with the sleep period increased to a couple seconds) should provide an easy to execute, bare minimum acceptance test for either new versions or completion of the enhancement.
