### ISSUE TITLE
Pods not selected by headless service

### ISSUE THREAD

**Issue by younglee1** [kubernetes/kubernetes#78290]
I defined a headless service with spec:
```
spec:
  clusterIP: None
  selector:
    app: elasticsearch
    role: master
  ports:
    - port: 9300
      name: node-to-node
```
And the pods it should select have readiness probe:
```
readinessProbe:
  httpGet:
    path: /
    port: 9200
  initialDelaySeconds: 30
  timeoutSeconds: 5
  periodSeconds: 60
```
Thus got error when describe service:
![image](https://user-images.githubusercontent.com/11716601/58321134-e7eb8980-7e4f-11e9-8b9f-1b9bada6d005.png)

So my question is: Can a pod be selected by a service before first readiness check pass? Should I change my readinessProbe of these pods?
