### ISSUE TITLE
Pod is incorrectly terminated at the beginning of the last retry

### ISSUE THREAD

**Issue by cliu-splunk** [kubernetes/kubernetes#78377]
**What happened**:
With the backofflimit set to N and OnFailure set as the retry policy, the Nth retry was terminated at the beginning of that retry after whatever value is set for terminationGracePeriodSeconds.

**What you expected to happen**:
I expected the Nth retry should work as normal. That said, I expected to have (N + 1) runs.

**How to reproduce it (as minimally and precisely as possible)**:
Simply apply this job's yaml:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: chen-test-job
  labels:
    name: chen-test-job
    version: v1.0.0
spec:
  backoffLimit: 2
  parallelism: 1
  template:
    metadata:
      annotations:
        description: Chen testing jobs
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - name: test-container
        image: bash:4.4
        imagePullPolicy: IfNotPresent
        args:
        - -c
        - date && sleep 10 && echo "finish sleeping" && exit 1
        command:
        - sh
      restartPolicy: OnFailure
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-18T14:14:00Z", GoVersion:"go1.9.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): MacOS
- Kernel (e.g. `uname -a`):
```Darwin cliu-MBP-CBD58 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
