### ISSUE TITLE
[Gcloud] ERROR in command precedence: Gcloud dashboard/ Gcloud compute update Vs kubectl apply -f 

### ISSUE THREAD

**Issue by marius-cristian** [kubernetes/kubernetes#78407]
**What happened**:
I have a backendservice yaml file that :

```
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: slave-backend-config
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 30
  sessionAffinity:
    affinityType: "GENERATED_COOKIE" #"Client_IP" #ClientIP or NONE
    affinityCookieTtlSec: 86400
```
When i edit the timeout value eitther from the dashboard for the backend service or by the command:
```
gcloud compute backend-services update ID --timeout=7200
```

the update succeds, but shortly after 5-10 minutes, it reverts to the default value in the yaml.
for example:

after the update,
gcloud compute backend-services describe ID

displays nicely ```timeoutSec: 7200``

but after some time the same description displays: ```timeoutSec: 30```
 

```
kubectl get backendconfig slave-backend-config -o yaml
```
the tiemoutSec value is 30.

**What you expected to happen**:
I would expect for the update to be propagated and persistent for both web interface edits and gcloud compute commands; not only for when i use ```kubectl apply -f file.yaml```

**How to reproduce it (as minimally and precisely as possible)**:
you should be able to reproduce it using an ingress resource of class gce, and a backend service, that uses the above backendconfig file
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.10", GitCommit:"7a578febe155a7366767abce40d8a16795a96371", GitTreeState:"clean", BuildDate:"2019-05-01T04:14:38Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
gcloud version
Google Cloud SDK 247.0.0
alpha 2019.05.17
bq 2.0.43
core 2019.05.17
gsutil 4.38
kubectl 2019.05.17

- OS (e.g: `cat /etc/os-release`):

- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig cloud-provider
/sig cli
