### ISSUE TITLE
The env of statefulset's container is incorrectly upgrade when deleting a pod and scaling the statefulset simultaneously

### ISSUE THREAD

**Issue by tcmichael** [kubernetes/kubernetes#78420]
**What happened**:
After deleting a pod and scaling up the statefulset  with different valid envs in the same container simultaneously, then the output events of executing the command `kubectl describe sts <statefulset>` is below:
```
  Warning  FailedCreate      15s (x16 over 73s)  statefulset-controller  create Pod test-0 in StatefulSet test failed error: Pod "test-0" is invalid: spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when `value` is not empty
``` 

**What you expected to happen**:
update successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a statefulset.  
apply this statefulset's yaml:
```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: test
  namespace: default
spec:
  serviceName: "test-demo"
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      hostNetwork: true
      containers:
      - name: sts
        env:
        - name: KEY1
          value: Value1
        image: bash:4.4
        command:
        - "/bin/sleep"
        - "36000"
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
```
After a while, execute `kubectl get pods`, and the pod is running
```shell
$ kubectl get pods
NAME     READY   STATUS              RESTARTS   AGE
test-0   1/1     Running             0          34s
```

2. prepare a new stateful's yaml, which a new env key and more replicas.
```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: test
  namespace: default
spec:
  serviceName: "test-demo"
  replicas: 2
  template:
    metadata:
      labels:
        app: test
    spec:
      hostNetwork: true
      containers:
      - name: sts
        env:
        - name: KEY2
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: KEY1
          value: Value1
        image: bash:4.4
        command: 
        - "/bin/sleep"
        - "36000"
  updateStrategy:
    rollingUpdate:
      partition: 1
    type: RollingUpdate
```

3. delete the pod `test-0` and apply a new stateful's yaml
```shell
$ kubectl delete pod test-0 & kubectl apply -f statefulset2.yaml 
[1] 3580
pod "test-0" deleted
statefulset.apps/test configured
[1]+  Done                    kubectl delete pod test-0
```

4. describe the statefulset
```
$ kubectl describe sts test
Name:               test
Namespace:          default
CreationTimestamp:  Tue, 28 May 2019 15:09:31 +0800
Selector:           app=test
Labels:             app=test
Annotations:        kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"apps/v1beta1","kind":"StatefulSet","metadata":{"annotations":{},"name":"test","namespace":"default"},"spec":{"replicas":2,"...
Replicas:           824633983536 desired | 1 total
Update Strategy:    RollingUpdate
  Partition:        824633984396
Pods Status:        0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=test
  Containers:
   sts:
    Image:      bash:4.4
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sleep
      36000
    Environment:
      KEY2:      (v1:status.hostIP)
      KEY1:     Value1
    Mounts:     <none>
  Volumes:      <none>
Volume Claims:  <none>
Events:
  Type     Reason            Age                 From                    Message
  ----     ------            ----                ----                    -------
  Normal   SuccessfulCreate  8m8s                statefulset-controller  create Pod test-0 in StatefulSet test successful
  Warning  FailedCreate      15s (x16 over 73s)  statefulset-controller  create Pod test-0 in StatefulSet test failed error: Pod "test-0" is invalid: spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when `value` is not empty
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
