### ISSUE TITLE
PDB fails to show status in some cases

### ISSUE THREAD

**Issue by TheKangaroo** [kubernetes/kubernetes#78427]
**What happened**:
The status of a poddisruptionbudget is shown as
```
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              0
    Total:                0
``` 
(all 0)
under the following circumstances:
The PDB uses a label that matches a replicaset and two single pods (without controller). Both pods are completed (e.g. not ready) and the disruption limit is set to 2. As soon as I delete the completed pods, the status is shown as expected.

**What you expected to happen**:
The PDB should show the correct status.

**How to reproduce it (as minimally and precisely as possible)**:
Described above.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.4
- Cloud provider or hardware configuration: on-prem
- OS (e.g: `cat /etc/os-release`): Container Linux 1967.4.0
- Kernel (e.g. `uname -a`): 4.14.96-coreos
- Install tools: vanilla k8s

**Comment by Joseph-Irving** [comment]
Can you show the PDB you're using `kubectl get pdb <pdb name> -o yaml`?

**Comment by TheKangaroo** [comment]
It's the pdb for a redis cluster rendered from here (https://github.com/helm/charts/tree/master/stable/redis-ha) but I'm not quiet sure if it is from latest version of the helm chart. Anyways this is the spec of the PDB:
```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: redis-ha
    chart: redis-ha-3.3.3
    heritage: Tiller
    release: app-intranet
  name: app-intranet-redis-ha-pdb
  namespace: app-intranet-dev
spec:
  maxUnavailable: 2
  selector:
    matchLabels:
      app: redis-ha
      release: app-intranet
status:
  currentHealthy: 5
  desiredHealthy: 3
  disruptionsAllowed: 2
  expectedPods: 5
  observedGeneration: 1
```

**Comment by Joseph-Irving** [comment]
Thanks, I think I follow, so when you have no pods that match the PDB you're seeing something like: 
```
Name:             app-intranet-redis-ha-pdb
Namespace:        app-intranet-dev
Max unavailable:  2
Selector:         app=redis-ha,release=app-intranet
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              0
    Total:                0
Events:
  Type    Reason  Age                From               Message
  ----    ------  ----               ----               -------
  Normal  NoPods  28s (x4 over 83s)  controllermanager  No matching pods found
```
This is expected behaviour, Desired = Current - MaxUnavailable, e.g if you have 5 pods the desired is 3 as you can tolerate 2 being unavailable. If you have 0 pods then Desired = 0 - 2, which equals -2 but you can't have a negative so it's 0. 

If you were using MinAvailable instead of MaxUnavailable you would see:
```
ame:           app-intranet-redis-ha-pdb
Namespace:      app-intranet-dev
Min available:  2
Selector:       app=redis-ha,release=app-intranet
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              2
    Total:                0
Events:
  Type    Reason  Age              From               Message
  ----    ------  ----             ----               -------
  Normal  NoPods  8s (x2 over 8s)  controllermanager  No matching pods found
```
This is because with MinAvailable you're setting the bottom threshold of availability so Desired = MinAvailable

**Comment by TheKangaroo** [comment]
That's right, but in my case I do have pods which match the bdb. But two of them are not ready, so kubernetes behaves correct, when it won't delete an additional pod. But in this case the status is shown as
```
	Allowed disruptions:  0
    Current:              0
    Desired:              0
    Total:                0
```
when in fact it should be something like
```
	Allowed disruptions:  2
    Current:              5
    Desired:              7
    Total:                7
```
Or am I missing something about the meaning of the status fields? 🤔

**Comment by Joseph-Irving** [comment]
Right ok, I understand the problem now, to reproduce

create a pdb
```
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: foo
  name: mypdb
spec:
  maxUnavailable: 2
  selector:
    matchLabels:
      app: foo
```
create a job that matches (could be static pod)
```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","10"]
      restartPolicy: Never
```
status appears as 
```
Name:             mypdb
Namespace:        default
Max unavailable:  2
Selector:         app=foo
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              0
    Total:                0
```
Create a deployment that matches the pdb
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-foo
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
        - name: container
          image: nginx
```
status still wrong
```
Name:             mypdb
Namespace:        default
Max unavailable:  2
Selector:         app=foo
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              0
    Total:                0
```
Delete the job pod `kubectl delete myjob`, status is what you would expect
```
Name:             mypdb
Namespace:        default
Max unavailable:  2
Selector:         app=foo
Status:
    Allowed disruptions:  2
    Current:              5
    Desired:              3
    Total:                5
```
