### ISSUE TITLE
Dose it support multiple commands in readiness health check

### ISSUE THREAD

**Issue by dyoung23** [kubernetes/kubernetes#78436]
I want to start a Pod after checking some service is running already.But I try many methods but can't make it.
Here is my yaml file:
```
apiVersion: v1
kind: Pod
metadata:
  name: myweb
  labels:
    name: myweb
  namespace: edl
spec:
  containers:
  - name: myweb
    image: kubeguide/tomcat-app:v1
    ports:
    - containerPort: 8080
    env:
    - name: MYSQL_SERVICE_HOST
      value: 'mysql'
    - name: MYSQL_SERVICE_PORT
      value: '3306'
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - "curl http://ambassador:80/hello/ > /tmp/result" 
        - ; 
        - cat /tmp/result | grep "Hello World!!"
      initialDelaySeconds: 1
      periodSeconds: 1
      failureThreshold: 1
```
I try many format like above.But the exit code of `sh -c` always is 0 no matter I input anything wrong in it.

And I try in this way
```
   readinessProbe:
      exec:
        command:
        - curl 
        - http://ambassador:80/hello/ > /tmp/result
        - ; 
        - cat /tmp/result | grep "Hello World!!"
      initialDelaySeconds: 1
      periodSeconds: 1
      failureThreshold: 1
``` 
But get a result 
```
Events:
  Type     Reason     Age                 From                    Message
  ----     ------     ----                ----                    -------
  Normal   Scheduled  54s                 default-scheduler       Successfully assigned edl/myweb to 192.168.13.64
  Normal   Pulled     52s                 kubelet, 192.168.13.64  Container image "kubeguide/tomcat-app:v1" already present on machine
  Normal   Created    52s                 kubelet, 192.168.13.64  Created container
  Normal   Started    51s                 kubelet, 192.168.13.64  Started container
  Warning  Unhealthy  29s (x22 over 50s)  kubelet, 192.168.13.64  Readiness probe failed:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (6) Could not resolve host: cat
```

So I need some help. Thanks!

**Comment by gaorong** [comment]
try:  `curl -s http://ambassador:80/hello/ > /tmp/result && cat /tmp/result | grep "Hello World"`

**Comment by dyoung23** [comment]
@gaorong Thanks for you comment.
I tried this, but it doesn't work.
```
...
spec:
  containers:
  - name: myweb
    image: kubeguide/tomcat-app:v1
    ports:
    - containerPort: 8080
    env:
    - name: MYSQL_SERVICE_HOST
      value: 'mysql'
    - name: MYSQL_SERVICE_PORT
      value: '3306'
    readinessProbe:
      exec:
        command:
        - curl -s http://ambassador:80/hello/ > /tmp/result && cat /tmp/result | grep "Hello World"
      initialDelaySeconds: 1
      periodSeconds: 1
      failureThreshold: 1
```

```
.....
Events:
  Type     Reason     Age              From                    Message
  ----     ------     ----             ----                    -------
  Normal   Scheduled  12s              default-scheduler       Successfully assigned edl/myweb to 192.168.13.64
  Normal   Pulled     11s              kubelet, 192.168.13.64  Container image "kubeguide/tomcat-app:v1" already present on machine
  Normal   Created    10s              kubelet, 192.168.13.64  Created container
  Normal   Started    10s              kubelet, 192.168.13.64  Started container
  Warning  Unhealthy  6s (x2 over 6s)  kubelet, 192.168.13.64  Readiness probe failed: OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"curl -s http://ambassador:80/hello/ > /tmp/result && cat /tmp/result | grep \\\"Hello World\\\"\": stat curl -s http://ambassador:80/hello/ > /tmp/result && cat /tmp/result | grep \"Hello World\": no such file or directory": unknown
```

**Comment by RainbowMango** [comment]
@justaugustus 

I see you marded `help wanted` tag to some issues. I guess you may misunderstand the meaning of `help wanted`.

This tag for contributor select task. An issue with `help wanted` normally means have been specially groomed for new contributors.

More details please refer: 
https://github.com/kubernetes/community/blob/master/contributors/guide/help-wanted.md

**Comment by andy108369** [comment]
> @gaorong Thanks for you comment. I tried this, but it doesn't work.
> 
> ```
> ...
> spec:
>   containers:
>   - name: myweb
>     image: kubeguide/tomcat-app:v1
>     ports:
>     - containerPort: 8080
>     env:
>     - name: MYSQL_SERVICE_HOST
>       value: 'mysql'
>     - name: MYSQL_SERVICE_PORT
>       value: '3306'
>     readinessProbe:
>       exec:
>         command:
>         - curl -s http://ambassador:80/hello/ > /tmp/result && cat /tmp/result | grep "Hello World"
>       initialDelaySeconds: 1
>       periodSeconds: 1
>       failureThreshold: 1
> ```
> 
> ```
> .....
> Events:
>   Type     Reason     Age              From                    Message
>   ----     ------     ----             ----                    -------
>   Normal   Scheduled  12s              default-scheduler       Successfully assigned edl/myweb to 192.168.13.64
>   Normal   Pulled     11s              kubelet, 192.168.13.64  Container image "kubeguide/tomcat-app:v1" already present on machine
>   Normal   Created    10s              kubelet, 192.168.13.64  Created container
>   Normal   Started    10s              kubelet, 192.168.13.64  Started container
>   Warning  Unhealthy  6s (x2 over 6s)  kubelet, 192.168.13.64  Readiness probe failed: OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"curl -s http://ambassador:80/hello/ > /tmp/result && cat /tmp/result | grep \\\"Hello World\\\"\": stat curl -s http://ambassador:80/hello/ > /tmp/result && cat /tmp/result | grep \"Hello World\": no such file or directory": unknown
> ```


This should work:

```
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - |
                curl -so - http://ambassador:80/hello/ | grep -q "Hello World"
```
