### ISSUE TITLE
Windows pods don't support dnsConfig.searches

### ISSUE THREAD

**Issue by DavidSimner** [kubernetes/kubernetes#78565]
**What happened**:
I started a Windows pod that specified `dnsConfig.searches` in the pod spec but that setting seemed to be silently ignored.

Running:
```
kubectl logs hello-6ddb6d69b-87j87
```
Gave:
```
Resolve-DnsName : dns : DNS name does not exist
At line:1 char:17
+ Start-Sleep 60; Resolve-DnsName -Name 'dns' -Type 'A'; Start-Sleep 36 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (dns:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName
```
FYI, the initial sleep of 60 seconds before making the DNS request is to work around https://github.com/kubernetes/kubernetes/issues/78479 and that workaround succeeded because the error above is *not* a timeout, but an error indicating that the DNS search suffix wasn't used.

Whereas in Docker this works perfectly:
```
PS C:\k> docker run --rm -it --dns-search msftncsi.com mcr.microsoft.com/windows:10.0.17763.437 powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> Resolve-DnsName -Name 'dns' -Type 'A'

Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
dns.msftncsi.com                               A      30    Answer     131.107.255.255
```

**What you expected to happen**:
I expect that `dnsConfig.searches` applies to Windows pods.

**How to reproduce it (as minimally and precisely as possible)**:
Here's the `.yaml` file that I used:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hello
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      dnsConfig:
        searches:
          - msftncsi.com
      containers:
        - name: hello-container
          image: mcr.microsoft.com/windows:10.0.17763.437
          command:
            - powershell.exe
            - -Command
            - Start-Sleep 60; Resolve-DnsName -Name 'dns' -Type 'A'; Start-Sleep 3600
```

**Anything else we need to know?**:
- On-premise install of k8s
- The Windows nodes all have the following feature gates enabled:
  - WinOverlay
  - WindowsGMSA

**Linux master**:
- OS (e.g. `cat /etc/os-release`): `Ubuntu 18.10 (Cosmic Cuttlefish)`
```
 Kernel Version:             4.18.0-18-generic   #19-Ubuntu   Tue Apr 2 18:13:16 UTC 2019
 OS Image:                   Ubuntu 18.10
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.5
 Kubelet Version:            v1.14.1
 Kube-Proxy Version:         v1.14.1
```

**Windows worker**:
```
 Kernel Version:             10.0.17763.437
 OS Image:                   Windows Server 2019 Standard
 Operating System:           windows
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.5
 Kubelet Version:            v1.14.1
 Kube-Proxy Version:         v1.14.1
```
```
NetworkMode: overlay
```
```
.\flanneld.exe -version
v0.11.0
```

If you need any more information then please let me know.
