### ISSUE TITLE
Windows pods: binaries run from GMSA network shares have no network

### ISSUE THREAD

**Issue by DavidSimner** [kubernetes/kubernetes#78577]
**What happened**:
I started a Windows pod and ran an application located on a network share (using a GMSA for authentication), and the application started successfully but it had no access to make any network requests (even DNS requests that don't need authentication).

**What you expected to happen**:
I expect that all applications running within a container have access to the networking stack, and it doesn't matter if the binary is located locally or on a network share.

**How to reproduce it (as minimally and precisely as possible)**:
Firstly, you'll need to follow the instructions to create a GMSA: https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/

Then here's the `.yaml` file that I used to create the deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hello
      annotations:
        pod.alpha.windows.kubernetes.io/gmsa-credential-spec-name: hello-credspec
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: hello-container
          image: mcr.microsoft.com/windows:10.0.17763.437
          command:
            - powershell.exe
            - -Command
            - Start-Sleep 3600
```

Once the pod was running, to connect to it I ran:
```
kubectl exec -it hello-5fc586cd8b-znggj -- cmd.exe
```
Then to test that the GMSA had worked I ran:
```
nltest.exe /parentdomain
```
Which showed the domain name letting me know that everything was fine with the GMSA.

Then for a minimal repro you can use `curl` which you can download from: https://curl.haxx.se/windows/ and once you've downloaded it, then you need to put `curl.exe` on a network share accessible to the container.

To demonstrate the bug simply run `curl.exe` from that network share from within the container:
```
C:\>\\myServer.example.net\myShare\myFolder\curl.exe www.google.com
curl: (6) Could not resolve host: www.google.com
```

As you can see there is no network access when it is run from the network share, but if you copy the `curl.exe` binary to the local disk, then it works just fine:
```
C:\>copy \\myServer.example.net\myShare\myFolder\curl.exe .
        1 file(s) copied.

C:\>curl.exe www.google.com
<!doctype html><html ...
```

Even though I'm demonstrating this bug with `curl.exe` for this minimal repro, the results are the same for other binaries.

**Anything else we need to know?**:
- On-premise install of k8s
- The Windows nodes all have the following feature gates enabled:
  - WinOverlay
  - WindowsGMSA

**Linux master**:
- OS (e.g. `cat /etc/os-release`): `Ubuntu 18.10 (Cosmic Cuttlefish)`
```
 Kernel Version:             4.18.0-18-generic   #19-Ubuntu   Tue Apr 2 18:13:16 UTC 2019
 OS Image:                   Ubuntu 18.10
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.5
 Kubelet Version:            v1.14.1
 Kube-Proxy Version:         v1.14.1
```

**Windows worker**:
```
 Kernel Version:             10.0.17763.437
 OS Image:                   Windows Server 2019 Standard
 Operating System:           windows
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.5
 Kubelet Version:            v1.14.1
 Kube-Proxy Version:         v1.14.1
```
```
NetworkMode: overlay
```
```
.\flanneld.exe -version
v0.11.0
```

If you need any more information then please let me know.
