### ISSUE TITLE
Windows nodePort doesn't work when it's the same as the service port

### ISSUE THREAD

**Issue by DavidSimner** [kubernetes/kubernetes#78574]
**What happened**:
I created a service where the `nodePort` was the same as the `port`, and having done so, then the `nodePort` was *not* accessible externally on the Windows node where the pod was running (it was, however, accessible on the Linux master).  When I changed either the `port` or the `nodePort` so that they were different then the service was accessible on the Windows node.

**What you expected to happen**:
I expect `NodePort` services to work when the `nodePort` and the `port` are the same value.

**How to reproduce it (as minimally and precisely as possible)**:
Here's the `.yaml` file that I used:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/component: hello
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: hello-container
          image: mcr.microsoft.com/windows:10.0.17763.437
          command:
            - powershell.exe
            - -Command
            - "<#code used from https://gist.github.com/wagnerandrade/5424431#> ; $$listener = New-Object System.Net.HttpListener ; $$listener.Prefixes.Add('http://*:80/') ; $$listener.Start() ; $$callerCounts = @{} ; Write-Host('Listening at http://*:80/') ; while ($$listener.IsListening) { ;$$context = $$listener.GetContext() ;$$requestUrl = $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;$$count = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$ip=(Get-NetAdapter | Get-NetIpAddress); $$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f $$ip[1].IPAddress,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer = [System.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close() ;$$responseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ; "
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: hello-service
spec:
  selector:
    app.kubernetes.io/component: hello
  type: NodePort
  ports:
    - nodePort: 31234
      port: 31234
      targetPort: 80
```
Then, in a web browser on my desktop machine, I visited the `nodePort` on both the Linux master's IP address, and then in a different tab, using the `nodePort` again, the IP address of the Windows worker node where that pod was scheduled.  It only worked using the IP address of the Linux master.  The tab using the Windows worker node's IP address did not load.

Then, I changed either the `port` or the `nodePort` so that they were different values, and when they were different, it worked using the `nodePort` of both the Linux master's IP address and the IP address of the Windows worker node where that pod was scheduled.

**Anything else we need to know?**:
- On-premise install of k8s
- The Windows nodes all have the following feature gates enabled:
  - WinOverlay
  - WindowsGMSA

**Linux master**:
- OS (e.g. `cat /etc/os-release`): `Ubuntu 18.10 (Cosmic Cuttlefish)`
```
 Kernel Version:             4.18.0-18-generic   #19-Ubuntu   Tue Apr 2 18:13:16 UTC 2019
 OS Image:                   Ubuntu 18.10
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.5
 Kubelet Version:            v1.14.1
 Kube-Proxy Version:         v1.14.1
```

**Windows worker**:
```
 Kernel Version:             10.0.17763.437
 OS Image:                   Windows Server 2019 Standard
 Operating System:           windows
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.5
 Kubelet Version:            v1.14.1
 Kube-Proxy Version:         v1.14.1
```
```
NetworkMode: overlay
```
```
.\flanneld.exe -version
v0.11.0
```

If you need any more information then please let me know.
