### ISSUE TITLE
Check conformance tests call GA APIs only

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#78605]
**What is a problem**:

This is a part of https://github.com/kubernetes/kubernetes/issues/74432

We have defined the requirements of conformance tests as https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements
And the first requirement is `it tests only GA, non-optional features or APIs (e.g., no alpha or beta endpoints, no feature flags required, no deprecated features)`
Now we need to check this requirement manually when promoting e2e test to conformance test during review process.
That is hard burden against reviewers, so we need to have some automatic check way for this requirement.

**What can be a possible solution**:

`pull-kubernetes-conformance-image-test` job seems to be kicked if a conformance test change.
And the artifacts contains `e2e.log`, but the log doesn't contain API operations.

So the first thing we need to do is to enable the API operation log in `e2e.log` and the second is to create the script for checking the `e2e.log` doesn't contain non-GA APIs  (like alpha, beta).

**Comment by oomichi** [comment]
Enable the API operation log in e2e.log on pull-kubernetes-conformance-image-test
---------------------------------------------------------------------------------------------
The job definition: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-testing/conformance-e2e.yaml#L4
1. It kicks `./../test-infra/experiment/kind-conformance-e2e.sh`.
2. `kind-conformance-e2e.sh` kicks `./conformance-e2e.sh`.
3. `kubectl create -f conformance-e2e.yaml`

conformance-e2e.yaml:
```
spec:
  containers:
  - name: conformance-container
    image: k8s.gcr.io/conformance-amd64:v1.14
    imagePullPolicy: IfNotPresent
    env:
    - name: E2E_FOCUS
      value: "\\[Conformance\\]"
    - name: E2E_SKIP
      value: ""
    - name: E2E_PROVIDER
      value: "skeleton"
    - name: E2E_PARALLEL
      value: "false"
```
