### ISSUE TITLE
kube-proxy with mode iptables can not work correctly, when deployment repleaces is 2

### ISSUE THREAD

**Issue by lovingcodesk** [kubernetes/kubernetes#78685]
- kube-proxy with mode iptables can not lead traffic to each pod randomly, when deployment repleaces is 2

- I have made some tests that request 1000 times one by one, when deployment repleaces is 2,but only the first pod get the all requests, the second pod can not get any request,
this is my serivce yml template:
```
apiVersion: v1
kind: Service
metadata:
  name: xxxx
  namespace: xxxx
  labels:
    run: xxxx
spec:
  ports:
  - port: 8764
    targetPort: 8764
  selector:
    run: xxxx
```

- I don't know whether it is a bug ,or anyone can tell me why ?
- I found k8s document says,
```
kube-proxy with mode iptables  When a client connects to the VIP the iptables rule kicks in. A backend is chosen (either based on session affinity or randomly) and packets are redirected to the backend
```
so is it related to session affinity?
