### ISSUE TITLE
Some CRDs that duplicate built-in group/version/kinds reap built-in etcd data on deletion

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#78707]
**What happened**:

Created a CRD:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  scope: Namespaced
  version: v1
  names:
    singular: foo
    plural: foos
    kind: Foo
    listKind: FooList
```

Created another CRD defining an overlapping type with CustomResourceDefinition:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customresourcedefinitions.apiextensions.k8s.io
spec:
  group: apiextensions.k8s.io
  version: v1beta1
  scope: Cluster
  names:
    plural: customresourcedefinitions
    singular: customresourcedefinition
    kind: CustomResourceDefinition
    listKind: CustomResourceDefinitionList
  validation:
    openAPIV3Schema:
      type: object
      properties:
        readonly:
          type: boolean
```

Verify both exist:
```
$ kubectl get crds
NAME                                             CREATED AT
customresourcedefinitions.apiextensions.k8s.io   2019-06-04T19:37:46Z
foos.example.com                                 2019-06-04T19:48:35Z
```

Deleted the one overlapping with the in-tree CRD type:
```
kubectl delete crd/customresourcedefinitions.apiextensions.k8s.io --wait=false
```

Verify only the overlapping CRD remains:
```
$ kubectl get crd
NAME                                             CREATED AT
customresourcedefinitions.apiextensions.k8s.io   2019-06-04T19:37:46Z
```
and is stuck deleting:
```
$ kubectl get crd -o yaml
...
  status:
    conditions:
    ...
    - lastTransitionTime: "2019-06-04T19:49:40Z"
      message: CustomResource deletion is in progress
      reason: InstanceDeletionInProgress
      status: "True"
      type: Terminating
```

**What you expected to happen**:

Creation and deletion of the overlapping type CRD would have no effect on the in-tree data.

**Anything else we need to know?**:

The only types in the kube-apiserver (currently) that store data under a group prefix are:
* APIService (`<prefix>/apiregistration.k8s.io/apiservices/...`)
* CustomResourceDefinition (`<prefix>/apiextensions.k8s.io/customresourcedefinitions/...`)
* Custom resources (`<prefix>/<group>/<pluralResource>/...`)

When a CRD is deleted, all instances of the type it defines are first removed. That means that defining and deleting a CustomResourceDefinition that defines an overlapping APIService or CustomResourceDefinition type will remove existing APIService or CustomResourceDefinition data.

We can special-case these two resources in the CRD deletion code, but we need a more robust solution before CRD v1.

/cc @sttts @deads2k @jpbetz 
/sig api-machinery
/priority important-soon
/area custom-resources
