### ISSUE TITLE
Some CRDs that duplicate built-in group/version/kinds show up in openapi

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#78706]
**What happened**:
Created a CRD with a group/version/kind that defines a CustomResourceDefinition type overlapping with the in-tree kubernetes type (**WARNING**: do not create this CRD on a cluster you care about, see https://github.com/kubernetes/kubernetes/issues/78707)

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customresourcedefinitions.apiextensions.k8s.io
spec:
  group: apiextensions.k8s.io
  version: v1beta1
  scope: Cluster
  names:
    plural: customresourcedefinitions
    singular: customresourcedefinition
    kind: CustomResourceDefinition
    listKind: CustomResourceDefinitionList
  validation:
    openAPIV3Schema:
      type: object
      properties:
        readonly:
          type: boolean
```

Note that two definitions for the group/version/kind appear in openapi:

```sh
kubectl get --raw /openapi/v2 | \
  jq '.definitions["io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition"]'
```

> ```json
> {
>   "description": "CustomResourceDefinition represents a resource that should be exposed on the API server.  Its name MUST be in the format <.spec.name>.<.spec.group>.",
>   "type": "object",
>   "required": [
>     "spec"
>   ],
>   "properties": {
>     "apiVersion": {
>       "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
>       "type": "string"
>     },
>     "kind": {
>       "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
>       "type": "string"
>     },
>     "metadata": {
>       "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
>     },
>     "spec": {
>       "description": "Spec describes how the user wants the resources to appear",
>       "$ref": "#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec"
>     },
>     "status": {
>       "description": "Status indicates the actual state of the CustomResourceDefinition",
>       "$ref": "#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus"
>     }
>   },
>   "x-kubernetes-group-version-kind": [
>     {
>       "group": "apiextensions.k8s.io",
>       "kind": "CustomResourceDefinition",
>       "version": "v1beta1"
>     }
>   ]
> }
> ```

```sh
kubectl get --raw /openapi/v2 | \
  jq '.definitions["io.k8s.apiextensions.v1beta1.CustomResourceDefinition"]'
```

```json
{
  "type": "object",
  "properties": {
    "apiVersion": {
      "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
      "type": "string"
    },
    "kind": {
      "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
      "type": "string"
    },
    "metadata": {
      "description": "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
      "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
    },
    "readonly": {
      "type": "boolean"
    }
  },
  "x-kubernetes-group-version-kind": [
    {
      "group": "apiextensions.k8s.io",
      "kind": "CustomResourceDefinition",
      "version": "v1beta1"
    }
  ]
}
```

Because both specify a `x-kubernetes-group-version-kind`, and do not overlap in their generated definition type name, both are published in openapi (even though the handler for the CRD-defined one is not actually used to serve that group/version/kind)

**What you expected to happen**:

published openapi only includes the in-tree type, which has precedence

/cc @sttts @roycaihw 
/area custom-resources
/priority important-soon
/sig api-machinery
