### ISSUE TITLE
Unexpected behavior with networkpolicies and service type loadbalancer

### ISSUE THREAD

**Issue by TheKangaroo** [kubernetes/kubernetes#78729]
_I recognized that the networkpolicies behave in an unexpected way in an edge case. I filled an issue at the project calico (https://github.com/projectcalico/calico/issues/2635) about it, but it seems like the unexpected behavior happens in the kube-proxy component._

**What happened**:
Following the description from the calico ticket:

I deployed an app to kubernetes and published it as service type loadbalancer. The service listens on 443 and the pods behind on 6443. Ingress on this service is allowed for anyone.
I expected to

* deploy a network policy to another namespace which allows egress 443 and can access the external IP on port 443.
* deploy a network policy to a namespace in another cluster which allows egress 443 and can access the external IP between clusters on port 443.

**What you expected to happen**:
To access the app between clusters I can deploy a networkpolicy with egress 443 and everything works as expected.
To access the app from the same cluster I need to deploy a networkpolicy with egress 6443 (the pod port) which is unexpected.

**How to reproduce it (as minimally and precisely as possible)**:

1.
Deploy a service to a namespace, e.g. an ingress:
```
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 6443
    protocol: TCP    
  selector:
    app: ingress-nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
```
and add the according deployment/pods

2.
Add a NetPol to a diffrent Namespace:
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  labels:
    app: myapp
  name: allow-ingress access
  namespace: nottheingressnamespace
spec:
  egress:
  - ports:
    - port: 443 (<- works only if you are in a diffrent cluster,
                 needs to be 6443 for the same cluster)
      protocol: TCP
  podSelector:
    matchLabels:
      app: myapp
  policyTypes:
  - Egress
```
3.

run pod with label `app: myapp` and try to access the ingress from within the pod.

**Anything else we need to know?**:

I dug a bit into kubernetes iptables rules, and I think the root cause is the KUBE-SERVICES chain in the OUTPUT chain which directly maps the external ip to the internal service ip and then to the pod service ip and the port 443 to the pod port 6443.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.4
- Cloud provider or hardware configuration: bare-metal/vm's
- OS (e.g: `cat /etc/os-release`):CoreOS 1855.5.0
- Install tools: vanilla kubernetes
- Network plugin and version (if this is a network-related bug): Calico version v3.4.0
