### ISSUE TITLE
pod with readinessProbe will be not ready when kubelet restart

### ISSUE THREAD

**Issue by wybzju** [kubernetes/kubernetes#78733]
**What happened:**
pod with readinessProbe will be not ready a little while when kubelet restart, and then the endpoint will changed.
**What you expected to happen:**
When kubelet restart, the ready status of the pod should be true rather than false.
**How to reproduce it (as minimally and precisely as possible):**
1 start a pod with readinessProbe
2 kubectl get po <podName> -o yaml --watch      watch the pod status
3 service kubelet restart       restart the kubelet
4 you will see below (for example)
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: <time>
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: <time>
    message: 'containers with unready status: [kubedns]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: <time>
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: <containerID>
    image:<image>
    imageID: <imageID>
    name: <kubedns>
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: <time>
```

**Anything else we need to know?:**
No
**Environment:**
Kubernetes v1.10.2
