### ISSUE TITLE
Allow following logs for a deployment if pods are creating

### ISSUE THREAD

**Issue by Davio** [kubernetes/kubernetes#78755]
**What would you like to be added**:
If I use a command like `kubectl logs -f --tail=100 -l app=<my-app>` it will only follow the logs if all pods in the deployments are created and running.

If one or more pods are still starting, the command exits with the message:
> Error from server (BadRequest): container "<my-container>" in pod "<my-app>-12345678-abcdef" is waiting to start: ContainerCreating

**Why is this needed**:
I would like to be able to follow the logs of already existing pod(s) and have the logs of the new pod(s) be added to the output automatically when they are created and running.

@kubernetes/CLI-feature-requests
/sig CLI

**Comment by pswica** [comment]
I've been testing this, and I don't think I'm running into this issue. What I do:

```
kubectl create deployment --image=chentex/random-logger logger
kubectl logs -f --tail 100 -l app=logger
kubectl scale deployment --replicas=10 logger
```

Can you let me know a bit more about the environment you are running kubernetes in?

**Comment by almiche** [comment]
Hi there I can replicate this error by creating a statefulset (since it takes a bit longer than a deployment to boot up). Right after creating the statefulset if I attempt to run `kubectl logs statefulset/<name>` I end up with exactly that error 

> Error from server (BadRequest): container "elasticsearch" in pod "web-0" is waiting to start: ContainerCreating

For reference here is my statefulset's yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.1.1
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/elasticsearch/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi
```
I've run into this issue quite a bit when booting up large StatefulSets which can take sometimes minutes to appropriate all the required resources.

I wouldn't mind taking this on as a first contribution if anyone thinks it's worthwhile adding in.
