### ISSUE TITLE
kubelet didn't renew certificate when the certificate was expired

### ISSUE THREAD

**Issue by konghui** [kubernetes/kubernetes#78758]
**What happened**:
I has a kubernetes cluster. When the certificate was expired. All the node became not ready. And kubelet didn't renew a new certificate. I am sure I was enable the bootstrap feature. 

**What you expected to happen**:
kubelet will auto renew a new certificate

**How to reproduce it (as minimally and precisely as possible)**:
enable the bootstrap feature, add option to the kubelet config file.
```
RotateKubeletClientCertificate: true
RotateKubeletServerCertificate: true
```

**Anything else we need to know?**:
my kubelet config file.
```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: x.x.x.x
enableControllerAttachDetach: false
resolvConf: "/etc/resolv.conf"
clusterDomain: k8s.test.com
RotateCertificates: true
clusterDNS:
- x.x.x.x
featureGates:
  RotateKubeletClientCertificate: true
  RotateKubeletServerCertificate: true
  VolumeSubpathEnvExpansion: true
authentication:
  x509:
    clientCAFile: "/etc/kubernetes/ssl/ca.pem"
  anonymous:
    enabled: false
maxPods: 500
enforceNodeAllocatable:
- pods
- system-reserved
- kube-reserved
kubeReserved:
  memory: 2Gi
  cpu: "1"
systemReserved:
  memory: 4Gi
  cpu: "4"
systemReservedCgroup: /system-reserved
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
