### ISSUE TITLE
x-kubernetes-embedded-resource behavior is not working as specified

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#78784]
**What happened**:

Created a CRD using the new `x-kubernetes-embedded-resource` extension:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  version: v1
  scope: Namespaced
  names:
    plural: foos
    singular: foo
    kind: Foo
    listKind: FooList
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            template:
              type: object
              x-kubernetes-embedded-resource: true
              x-kubernetes-preserve-unknown-fields: true
              properties:
                spec:
                  type: object
        metadata:
          type: object
          properties:
            name:
              type: string
```

Checked the published OpenAPI spec:
```
$ kubectl get --raw /openapi/v2 | jq '.definitions["com.example.v1.Foo"]'
```
```json
{
  "type": "object",
  "properties": {
    "apiVersion": {
      "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
      "type": "string"
    },
    "kind": {
      "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
      "type": "string"
    },
    "metadata": {
      "description": "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
      "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
    },
    "spec": {
      "type": "object",
      "properties": {
        "template": {
          "type": "object",
          "properties": {
            "spec": {
              "type": "object"
            }
          },
          "x-kubernetes-embedded-resource": true,
          "x-kubernetes-preserve-unknown-fields": true
        }
      }
    }
  },
  "x-kubernetes-group-version-kind": [
    {
      "group": "example.com",
      "kind": "Foo",
      "version": "v1"
    }
  ]
}
```

Created an instance of the resource:
foo.yaml:
```yaml
kind: Foo
apiVersion: example.com/v1
metadata:
  name: myfoo
  labels:
    a: b
spec:
  template:
    #apiVersion: foo/v1
    #kind: Sub
    metadata:
      name: subobject
      bogus: fields
      labels:
        a: b
        b: [true,false]
        c: "a value"
    spec:
      readonly: true
```
```
kubectl create -f foo.yaml
kubectl get foo/myfoo -o yaml
```
```yaml
apiVersion: example.com/v1
kind: Foo
metadata:
  annotations:
  creationTimestamp: "2019-06-07T03:16:48Z"
  generation: 6
  labels:
    a: b
  name: myfoo
  namespace: default
  resourceVersion: "493"
  selfLink: /apis/example.com/v1/namespaces/default/foos/myfoo
  uid: fd5a311d-b318-490d-a127-82b916dde188
spec:
  template:
    metadata:
      bogus: fields
      labels:
        a: b
        b:
        - true
        - false
        c: "a value"
      name: subobject
    spec: {}
```

**What you expected to happen**:

1. kind, apiVersion, and metadata to be added to the schema for the `x-kubernetes-embedded-resource` object
2. `kind` and `apiVersion` to be required to be present, non-empty, and apiVersion to pass `ParseGroupVersion`
3. `metadata` to be schema-checked (fail on the array value under labels), pruned (dropped the `bogus` field), and validated (fail on the invalid label value for "c")
4. If kind, apiVersion, or metadata properties were defined in the schema, they would further restrict the allowed values, but the built-in validation would still occur as well
5. if pruning is enabled on the CRD, the kind/apiVersion/metadata fields should be preserved (and metadata should be pruned according to the fields supported by objectmeta)
6. if pruning is not enabled on the CRD, metadata should be pruned according to the fields supported by objectmeta

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

From the API doc:
```
	// x-kubernetes-embedded-resource defines that the value is an
	// embedded Kubernetes runtime.Object, with TypeMeta and
	// ObjectMeta. The type must be object. It is allowed to further
	// restrict the embedded object. kind, apiVersion and metadata
	// are validated automatically. x-kubernetes-preserve-unknown-fields
	// is allowed to be true, but does not have to be if the object
	// is fully specified (up to kind, apiVersion, metadata).
```

/milestone v1.15
/sig api-machinery
/area custom-resources
/priority critical-urgent
/assign @sttts
