### ISSUE TITLE
x-kubernetes-int-or-string behavior is not working as specified

### ISSUE THREAD

**Issue by sttts** [kubernetes/kubernetes#78817]
The server-side validation does not check the type of values with `x-kubernetes-int-or-string`.

Create a CRD like:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: foos
    singular: foo
    kind: Foo
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        intorstr:
          x-kubernetes-int-or-string: true
```

Then create a CR:
```yaml
apiVersion: stable.example.com/v1
kind: Foo
metadata:
  name: instance
intorstr: true
```
It is not rejected, but should because `intorstr` must not be a boolean.
