### ISSUE TITLE
vSphere Volume not placed as per pod's selected node without allowedTopolgies

### ISSUE THREAD

**Issue by subramanian-neelakantan** [kubernetes/kubernetes#78841]
**What happened**:
In a vCenter environment with more than one vSAN cluster where we want to treat each cluster as a zone by itself, the Volume gets placed on a vSAN datastore that is not the same cluster as the pod. Here are the details of the yamls.
Storage class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: zeroedthick
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - az-1
    - az-2
    - az-3
```
StatefulSet:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.beta.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```
Once I deploy the statefulset, one of the pods is scheduled in zone az-1, but VCP creates a PV in zone az-3. VCP does not take the pod's 'selectedNode' into account when placing the PV dynamically under the `WaitForFirstConsumer` volume binding mode.

**What you expected to happen**:
VCP should place the Volume in the same zone as the pod.

**How to reproduce it (as minimally and precisely as possible)**:
As described above.

**Anything else we need to know?**:
It is due to the known issue #78514 that the Volume gets placed on a wrong zone. But fixing that issue alone is not sufficient since that would end up failing the Volume provisioning with a "No shared datastore found" error. The current issue is raised so that VCP honors the `selectedNode` correctly during Volume provisioning and places the Volume in the same zone as the pod under the `WaitForFirstConsumer` volume binding mode.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14
- Cloud provider or hardware configuration: vSphere

/sig vmware
/sig cloud-provider
/assign skarthiksrinivas
