### ISSUE TITLE
Support for "oneOf" validation if status subresource is enabled

### ISSUE THREAD

**Issue by antonlisovenko** [kubernetes/kubernetes#78852]
**What happened**:
Cannot create a CRD if both `validation.openAPIV3Schema.oneOf` and `subresources.status` are specified
**What you expected to happen**:
We use `oneOf` for validation but this blocks from using `subresources.status` in the same time

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: tests.test.test
spec:
    group: test.test
    version: v1
    scope: Namespaced
    names:
        kind: Test
        plural: tests
        shortNames:
            - tst
        singular: test
    subresources:
        status: {}
    validation:
        openAPIV3Schema:
            oneOf:
                - properties: # Standalone schema
                      spec:
                          properties:
                              type:
                                  type: string
                                  pattern: "^Standalone$"
                - properties: # ReplicaSet schema
                      spec:
                          properties:
                              type:
                                  type: string
                                  pattern: "^ReplicaSet$"
```

results in the following exception:
`The CustomResourceDefinition "tests.test.test" is invalid: spec.validation.openAPIV3Schema: Invalid value: apiextensions.JSONSchemaProps{...}: must only have "properties", "required" or "description" at the root if the status subresource is enabled`

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-07T09:55:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
restructure this to define the properties and types, then define oneOf pattern validation for a particular property:

```yaml
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          properties:
            type:
              type: string
          oneOf:
          - properties: # Standalone schema
              type:
                pattern: "^Standalone$"
          - properties: # ReplicaSet schema
              type:
                pattern: "^ReplicaSet$"
        status:
          type: object
          ...
```
