### ISSUE TITLE
Endpoints without service get removed on controller leader acquire

### ISSUE THREAD

**Issue by CallMeFoxie** [kubernetes/kubernetes#78933]
Hi
**What happened**:
We run a several "fake" services in our cluster -- just endpoints, **WITHOUT** the Service resource available. However when leader election for controller-manager happens the Endpoints resource is deleted.

**What you expected to happen**:
Keep the Endpoints resource.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create v1.Endpoints resource with several endpoints WITHOUT creating a Service alongside it
2. Change elected leader for controller-manager
3. Observe the Endpoints resource gone

**Anything else we need to know?**:
Happens on 1.13.5, 1.13.7, 1.14.1 and 1.14.3 (other versions not tested)

sample v1.Endpoints resource:
```
apiVersion: v1
kind: Endpoints
metadata:
  name: kupitest
  namespace: ftxt-hint
subsets:
- addresses:
  - ip: 10.57.10.152
    nodeName: foo1.com
  - ip: 10.57.10.153
    nodeName: foo2.com
  ports:
  - name: hint
    port: 4234
    protocol: TCP
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.x, 1.14.x
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): Debian stretch & buster
- Kernel (e.g. `uname -a`): unrelated
- Install tools: custom
- Network plugin and version (if this is a network-related bug): unrelated
