### ISSUE TITLE
Permission to "pods/*" should work

### ISSUE THREAD

**Issue by Sakib37** [kubernetes/kubernetes#78936]
@kubernetes/sig-Auth-feature-requests

**What would you like to be added**:
When creating role I restrict user permission to a namespace, I tried to add "pods/*" in rules but it does not work. However, it works for services. 
current working role is 

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myrole
  namespace: default
rules:
- apiGroups: ["", "metrics.k8s.io"]
  resources:
    - "bindings"
    - "configmaps"
    - "endpoints"
    - "events"
    - "persistentvolumeclaims"
    - "pods"
    - "pods/attach"
    - "pods/exec"
    - "pods/log"
    - "pods/portforward"
    - "serviceaccounts"
    - "services"
    - "services/*"
  verbs: ["*"]
```

expected role: 

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: myrole
  namespace: default
rules:
- apiGroups: ["", "metrics.k8s.io"]
  resources:
    - "bindings"
    - "configmaps"
    - "endpoints"
    - "events"
    - "persistentvolumeclaims"
    - "pods"
    - "pods/*"
    - "serviceaccounts"
    - "services"
    - "services/*"
  verbs: ["*"]
```
**Why is this needed**:
Accessing all sub resources with wildcard(*) is much cleaner than individually writing all subresources.
