### ISSUE TITLE
HPA is too sensitive for some applications. Can we average over time?

### ISSUE THREAD

**Issue by max-rocket-internet** [kubernetes/kubernetes#78988]
For some applications the HPA is too sensitive. This is due to [the design](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/):

> For per-pod resource metrics (like CPU), the controller fetches the metrics from the resource metrics API for each pod...The controller then takes the mean of the utilization or the raw value (depending on the type of target specified) across all targeted pods, and produces a ratio used to scale the number of desired replicas.

For many applications this causes too much scaling activity. For example:

- Spiky workloads that vary a lot in the short term
- Java applications that are slow to start and use max CPU during startup

It would be great if we could simply specify an evaluation period of time over which the metric values are averaged. Or a set number of the controller manager’s HPA sync periods over which to average.

It needs to be configurable in the `HorizontalPodAutoscaler` resource as many users are using k8s-as-a-service (GKE, EKS, AKS etc). Maybe something like this with a new `targetEvaluationPeriodSeconds` attribute:

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app1
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: extensions/v1beta1
    name: app1
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 45
  targetEvaluationPeriodSeconds: 600
```

Related issues:
https://github.com/kubernetes/kubernetes/issues/41159
https://github.com/kubernetes/kubernetes/issues/39090#issuecomment-466398426
