### ISSUE TITLE
PVC DataSource doesn't check for nil APIGroup

### ISSUE THREAD

**Issue by j-griffith** [kubernetes/kubernetes#78996]
**What happened**:
While implementing the new VolumePVCDataSource feature I discovered that even though the we don't use APIGroup (the appropriate setting is `""`) if the APIGroup is omitted it results in a nil pointer exception on the API server.

**What you expected to happen**:
APIGroup should be able to be omitted from the spec 

**How to reproduce it (as minimally and precisely as possible)**:
Create a spec to create a clone of a PVC with out the APIGroup parameter in the DataSource spec:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hp-pvc-clone
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: src-hp-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
The result will be an nil pointer exception during the verification of the datasource field.

Adding the APIGroup entry will address this as a work-around:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hp-pvc-clone
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: src-hp-pvc
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.1.33084+d873167e8f816f-dirty", GitCommit:"d873167e8f816f5f83846bc4587c3047452293bd", GitTreeState:"dirty", BuildDate:"2019-06-12T22:12:02Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Install tools:

local-up-cluster.sh
