### ISSUE TITLE
HandlePodCleanups() pass nil to APIPod

### ISSUE THREAD

**Issue by fankangbest** [kubernetes/kubernetes#79010]
**What happened**:
We have customized killContainer() function. We need to get something from pod's annotations in killContainer(). But we find we can't get pod's annotations correctly in the below scenario.

The pod may be killed by HandlePodCleanups() in some cases such as we delete pod at the time we just create the pod. However, in HandlePodCleanups(), nil is passed to APIPod.
```
       for _, pod := range runningPods {
                if _, found := desiredPods[pod.ID]; !found {
                        kl.podKillingCh <- &kubecontainer.PodPair{APIPod: nil, RunningPod: pod}
                }
        }
```
So in killContainer()，pod param is nil.
```
func (m *kubeGenericRuntimeManager) killContainer(pod *v1.Pod, containerID kubecontainer.ContainerID, containerName string, reason string, gracePeriodOverride *int64) error
```
However, the restoreSpecsFromContainerLabels() in killContainer() won't reconstruct many fields in pod such as annotations.

So there is a risk that the behavior of killContainer() called by HandlePodCleanups()  is different from normal kill procedure because the value of pod.

**What you expected to happen**:
Pass the pod defined in podmanager to APIPod in HandlePodCleanups().

**How to reproduce it (as minimally and precisely as possible)**:
Step 1:
create the pod, replace <image> with your own image.
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  containers:
  - name: container
    image: <image>
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "sleep 1000"]
    resources:
      limits:
        cpu: "50m"
        memory: 256Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: "50m"
        memory: 256Mi
        ephemeral-storage: 1Gi
```
Step 2:
delete pod 20s later.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  
v1.14.3

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
Linux ubuntu 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
