### ISSUE TITLE
k8s api doesn't support the --device args which support by the docker api。

### ISSUE THREAD

**Issue by warlice** [kubernetes/kubernetes#79090]
**I want mount a char device into container，but not grant privilege to the container**:
1. I use hostpath binding a char device to container。
2. if i doesn't grant privilege to the container， i can't open the char device in the docker container。
3.  if i grant privilege to the container， char device can open in the docker container。

**Docker command client support --device，but i can't find this api in k8s。**

**Comment by peter-wangxu** [comment]
Give a try, add following cap for your contain
```yaml
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
```
