### ISSUE TITLE
kubelet down, delete the pod on the node, restart kubelet, the pod is terminating forever

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/kubernetes#79155]
**What happened**:
l create a pod and secret in the yaml, the pod dependec the secret,  l action kubectl delete -f yam when the kubelet down which the node running on,  the pod terminating. when l found the kubelet down, l restart the kubelet. the pod status terminating forever. 
**What you expected to happen**:
l expected the volummanager use the secret and configmap manager to check the pod depence secret and cm when add the ActualStateOfWorld of the pod, if the depnece resource not found , should do some thing.  but now I don't know what to do.
**How to reproduce it (as minimally and precisely as possible)**:
define a pod and secret in a yaml file, and apply. when the po is running. stop the kebelet which the pod running on. and delete -f yaml
**Anything else we need to know?**:
l read the code of the pkg/kubelet/volumemanager , l analysis the code，the result is like this：

when the kubelet was down, l delete -f yaml. the pod was market delete(the deletetimestamp not nil), the secret was delete successful from etcd. when the kubelet restart, all pod belong to the node was readd the kubelet, the terminated pod is still on the node, volum manger will do remount  retach opeartion, but the secret not found ,so the operation will do forever. but the kubelet syncpod found the pod is market delete,  it will call canbedelete func, and the check the pod dependec resource reclaim success.  if recaliam ,call apiserver delete pod (grace-period=0), if not, do nothing.  when check the dependence resource reclaim incude volume.  the logic like this:  
1. pod exist in pod manger or not,  
2. ActualStateOfWorld exsit the pod volumemount or not

the actual is the pod stiil in pod manager, but the volume mount info not exsit in the actualstateofworld. so the resource reclaim check was not success.

if l delete the po --grace-period , the po can be delelete from etcd. but the kubelet will do mount.setup of the ophan pod forever.
**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):
Linux k8s-master 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm 
- Network plugin and version (if this is a network-related bug):
flannel:v0.11.0
- Others:

**Comment by mattjmcnaughton** [comment]
Hi @huangjiasingle ! Thanks for filing this issue :)

Would you mind sharing the yaml files you were using and also a sequence of bash commands to replicate the problem? That will be helpful for debugging/testing.

**Comment by huangjiasingle** [comment]
@mattjmcnaughton ok, the yaml like this :

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: apiserver
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 20Mi
    volumeMounts:
    - mountPath: /apiserver.local.config/certificates
      name: test
      readOnly: true
  volumes:
  - name: test
    secret:
      defaultMode: 420
      secretName: etcd-apiextensions

---

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: test
  labels:
    api: test
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURWakNDQWo0Q0NRQ0taWFNNaDl5R0dEQU5CZ2txaGtpRzl3MEJBUVVGQURCeU1Rc3dDUVlEVlFRR0V3SjEKYmpFTE1Ba0dBMVVFQ0F3Q2MzUXhDakFJQmdOVkJBY01BV3d4Q2pBSUJnTlZCQW9NQVc4eEN6QUpCZ05WQkFzTQpBbTkxTVRFd0x3WURWUVFERENobGRHTmtMV0Z3YVdWNGRHVnVjMmx2Ym5NdFkyVnlkR2xtYVdOaGRHVXRZWFYwCmFHOXlhWFI1TUI0WERURTVNRFl4TXpFeE1EQTFPRm9YRFRJd01EWXhNakV4TURBMU9Gb3dhREVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURW5NQ1VHQTFVRUF3d2VaWFJqWkMxaGNHbGxlSFJsYm5OcGIyNXpMbVJsWm1GMWJIUXVjM1pqCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBOFc3MUIvVWE5R05sakRUZ2Q5ekUKUzNCY1dyZndKU0twTHNtUmFHNElTdnNUa3F0Y1JqUVlQYjhEdHZmSGY3VTFEenozdWg4K0o2Y0thWmRnY3NVdQpaVGhEa0hhbXJLMUxMbHp2RGVRQkVsNWhBYnVsTjZWRmkvUnV2aWhnL0I1bVdPZnM3bERmSGpFNU05VHlvdnA1ClYrTkVLN1B6Wno2VHl2bjRuVjhpam0waVo2THhJZTA4b1dKMVhtTGlpbXozQ0Q1dzVDRnh0Q3FoeEk0VlJVYTUKdWViQWs0TWsreHg1VUxxVkRBbmRHa0dha3Q4RkhXekRkWE9LczNwdERzUG92M1lRR0xqR0VJN3VKM2o1TmJtUAp1OUVqMTVlMDBvNkg0U0kwRGRBNXk0UGxzT24zQk85OWJ1L25hRUwyU25iNXgyb3BIWjRvZTM1d1h1ZkNkeUZTCm13SURBUUFCTUEwR0NTcUdTSWIzRFFFQkJRVUFBNElCQVFCNVBlY1BsK1lsMHZNSDlIeEhkK0dnbDRRNlpOZ0wKZ2dpTEFwQzNvQTJTa1kzaHA4d050NE1Ld0N6eUxHUWVFRDdzamE1Zkk2dHNkWWttZXorSzFwVmtqcjRYMmwzMgpkdlRyVHBBRDlGZzJ1em0zUE1ZRm9zemlOM29uRUhRcFlxSGQ3dlFEcW5RV1MwcjdiZjdtN0FVdWxSZWNQSHVGCmF6VGw1WFN0V09OajdDOGNEenMvSTVjZ3hLb2xoNVJoR002KzNwMUVvMXpsdWVnWmJydlJtL3V6dDFVZm9vSHEKd0dQc0lLd2ZnN0N5THJxb1ZJcCtZVUxnRjBrcTcrKzBKaEYzckgzZTlzWFRXZWJrVTVOVGlMaFJ0c3cvZTFmZAp3NG9ONFF4dktMcDRlY3pPK0dJa0ZJQm80ZmdsYWplUnJoZzFHUVFtU1lUQUUzYitKeUN0NDRlRQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRHhidlVIOVJyMFkyV00KTk9CMzNNUkxjRnhhdC9BbElxa3V5WkZvYmdoSyt4T1NxMXhHTkJnOXZ3TzI5OGQvdFRVUFBQZTZIejRucHdwcApsMkJ5eFM1bE9FT1FkcWFzclVzdVhPOE41QUVTWG1FQnU2VTNwVVdMOUc2K0tHRDhIbVpZNSt6dVVOOGVNVGt6CjFQS2krbmxYNDBRcnMvTm5QcFBLK2ZpZFh5S09iU0pub3ZFaDdUeWhZblZlWXVLS2JQY0lQbkRrSVhHMEtxSEUKamhWRlJybTU1c0NUZ3lUN0hIbFF1cFVNQ2QwYVFacVMzd1VkYk1OMWM0cXplbTBPdytpL2RoQVl1TVlRanU0bgplUGsxdVkrNzBTUFhsN1RTam9maElqUU4wRG5MZytXdzZmY0U3MzF1Nytkb1F2Wktkdm5IYWlrZG5paDdmbkJlCjU4SjNJVktiQWdNQkFBRUNnZ0VBWmlJV0xnT1dINFJjMU84WmRodENQdGVOZWlNTngrZmR3aGtyRmc1V0c4SVQKQ1p6TU1EYWhlcDF2cU5zdzNlbCtSSy81N0JhRGFLclZVTTNrMHlodTlBclZLaXZIWG8wQW5PQmJrSGkvcTFHWgpuKzROZW5qRDd1eThYRjBnaWdjaUxNSVFETkRSVWlob2xuQ2pKQ2JwWmpDU0NocmFBUGNMOW5YQW9uSTRZQjhnCmNVdWtqU0xsRFV3Vm1Hd0xoZXpjVFRSb0w5WDdGZnFLakk4aDF1elZ1RjFvUVRtSEhGYVZrcXU4V0hTeE02NDkKdEpQZy9BSG9mNmsvS3ZMVzJJcDFRMlFpNC9kZTVYclRWYnc5TTQrQUZUT3NOOWFXR1ZMVU94VGtHWGN5SHB0Swo0WEora0dJTDIydWxndnRNbnVUakdoSm1iWmdjQVRQZWJ1cytVSGFXZ1FLQmdRRDYxTkVKZmhFTkMvaEtERGJsCldpbjhDZ1ovbk9CeHpaN2k2NXd6RGFnQ3JqYmIxT3FLM0cxRmlhRjY4VDBTaVRKQ0tLMGxPUXh1ZTRxQ01aczQKcytMUFAwZjJHRlRSWkE5MWN5YkZVdDEwb3ZtRlBZMGorM2tDU091dmx1U0l5L2piWjdkaGJzc1ZWMWcrdGpIeQpUa2Y3bi9hT2xWMTRhMjZodFNUbGkrWFBpd0tCZ1FEMmFKQ2ZiSWtyN040VlJBd2RPdmdxWExyZHMwVXU2M3J2CldpRTJmQzg4MmhjN3ZZSXQyRHVUazZ2M2RSa0N4MjhrcmRpV1I5cVZjM3hoT1g4bjF1OEI5S2xvZlJCWUloOGkKM0cvZktIQ1hBbG5OMk1UUVM5UWh0QTFPRXQ1dmRUNVpMR0FOUkpVK0M4Y1RWMDcxeUJjd0did1JCWHBCWkZBVQpFMzMzZytEck1RS0JnSHpKTzJXWmppb0xkbTZBUFI5RkIvWVhscndOODZzcVBJMXY0Ym1VWmExUHRvTVBIZEFQCmNWMVM1ejhlbk4rSDJiVUlQM3R4TWpvVXhBZVpYanVMWXA3d1FJQ3lBaUJadzBjUERvN0VkdC83NUY3aERFS0cKYk9FeUhlNnhCdWozY01yV2dtaTZrZFlBS2lxb3daaG1VWEZoVjJ2LzZ3eHBoaFIwNWZJODh3dVpBb0dBVU1YSQpHcXB1Y0xxdHRoVGZUN21qM2VjVnpsVFVxZVBCSWJMT3psaDQ5NTZhSFJnckV6SWRuV3U3NUZzN1BxRDNldk9OCjJ2MWsxcmJMbitkRUdtQW5hdUd6b3EvVWFyK01xMVhOU2o2c1lhUUFvaXlibjVncnlueUdIQUN0YjZYa01VRU4KbjJ2SzdGTGFDQ29IbFNQcERmaHhvTGJGODZlWlpHdGJVSWFuZFJFQ2dZRUE5M2pQYzQzbTNYaEN5SENpdllTZwpPME80cHR2b0ZNREtjNmU3NUFKTkFmeld3ZkxRTk51ZlVSWlc5ZzNTK0RCSGliSENEMjBOcTBUeVBTeEsxMjJpCldjamJuNjBiSjF0L1R6SUdzOFdPS1p4N0d5WFpsR1NzWExjUkFWdkZHV1l5bFUzT1JjdWFlR0krK3NqVGpXeGYKUmlMcjI0UmwvSFl3b1B4S05PYnpTWE09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
```
you can replace the secret of any those key or value  or type.
