### ISSUE TITLE
Set StatefulSet's Pods' Labels & Affinities based on Ordinal

### ISSUE THREAD

**Issue by Kent-H** [kubernetes/kubernetes#79175]
I would like if it were possible, when using a StatefulSet, to set:

* pod labels
* pod affinities

based on the ordinal of the pod.

This could behave similarly to the downward API (though it runs earlier in the deployment process).

This becomes most useful if simple math operators are permitted. (`+`, `-`, `/`, `*`, `%`, `(`...`)`)

For example, the pod would include:
``` yaml
metadata:
  labels:
    ...
  labelsFromOrdinal:
    example-label-group: "ordinal / 3"
    example-label-group-id: "ordinal % 3"
```

As well as:
``` yaml
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      matchExpressions:
      - key: example-label-group
        operator: In
        valueFromOrdinal: "ordinal / 3"
```
(This example would divide the pods into groups of 3, and spread pods that are in the same group.  It also labels pods with an in-group ID.)

With this, arbitrary grouping & spreading of pods is possible, in a scalable manner.

This is useful when:
* HA is a requirement.  (in this example, 3-node failover)
* Scalability is a requirement.
* K8s does not have a built-in resource for the particular scale / spread requirements, but a custom resource type is overkill.

I'm not committed to this particular implementation, though it helps to demonstrate the desired capabilities.
