### ISSUE TITLE
Windows SecurityContext GMSA Validation Fails

### ISSUE THREAD

**Issue by rhockenbury** [kubernetes/kubernetes#79240]
**What happened**:
I'm trying apply the following manifest with a gMSA specified in the securityContext `windowsOptions`:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: gmsa-deployment
  namespace: test
spec:
  nodeSelector:
    beta.kubernetes.io/os: windows
  containers:
  - image: mcr.microsoft.com/windows/servercore:ltsc2019
    name: servercore
    command: ["powershell", "Start-Sleep", "-s", "1000"]
  securityContext:
    WindowsOptions:
      GMSACredentialSpecName: gmsa-nweb
      GMSACredentialSpec: '<credentialspec>'
```

It fails with the error: `error: error validating \"/etc/kubernetes/gmsa-ds.yml\": error validating data: [ValidationError(Pod.spec.securityContext.windowsOptions): unknown field \"GMSACredentialSpec\" in io.k8s.api.core.v1.WindowsSecurityContextOptions, ValidationError(Pod.spec.securityContext.windowsOptions): unknown field \"GMSACredentialSpecName\" in io.k8s.api.core.v1.WindowsSecurityContextOptions]; if you choose to ignore these errors, turn validation off with --validate=false", "stderr_lines": ["error: error validating \"/etc/kubernetes/gmsa-ds.yml\": error validating data: [ValidationError(Pod.spec.securityContext.windowsOptions): unknown field \"GMSACredentialSpec\" in io.k8s.api.core.v1.WindowsSecurityContextOptions, ValidationError(Pod.spec.securityContext.windowsOptions): unknown field \"GMSACredentialSpecName\" in io.k8s.api.core.v1.WindowsSecurityContextOptions]; if you choose to ignore these errors, turn validation off with --validate=false"`

**What you expected to happen**:
The manifest to pass APIServer validation given that they appear to be valid fields - https://github.com/kubernetes/api/blob/master/core/v1/types.go#L5386. 

**How to reproduce it (as minimally and precisely as possible)**:
Enable the gmsa feature gate, set up gMSA, generate the credential spec, then apply the manifest from above.

**Anything else we need to know?**:
The feature gate for WindowsGMSA is enabled. 

If I pass the `--validate=false` flag, the properties under `WindowsOptions` just get pruned so the credentialSpec are not set on the in-cluster pod object, and then the kubelet is unable to set the credentials in the registry / pass them to Docker.

**Environment**:
- Kubernetes version (use `kubectl version`):
1.15.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
Windows Server 2019
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
