### ISSUE TITLE
what is the pod conditions lastProbeTime？

### ISSUE THREAD

**Issue by AlawnWong** [kubernetes/kubernetes#79402]
What is the pod conditions lastProbeTime？
     The pod-lifecycle doc say，The lastProbeTime field provides a timestamp for when the Pod condition was last probed.  
     Is it livenessProbe or readinessProbe time?
     however，i use this command （kubectl get po xxx -o yaml），the  lastProbeTime always null.
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-06-21T02:46:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-06-25T11:40:05Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-06-25T11:40:05Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-06-21T02:46:06Z"
    status: "True"
    type: PodScheduled
```
    
    Which condition the lastProbeTime will not null ?

K8S version : 1.13.5
