### ISSUE TITLE
kubernetes 1.8 cannot support Apparmor and sshfs ?

### ISSUE THREAD

**Issue by ChenLong2014** [kubernetes/kubernetes#79401]
I open OS config :
`cat /sys/module/apparmor/parameters/enabled : Y`

Open k8s config :
--feature-gates=AppArmor=true,DevicePlugins=true

I write a simple Apparmor local file :
```
apparmor_parser -q << EOF
#include <tunables/global>
profile docker-fuse6 flags=(attach_disconnected) {
  #include <abstractions/base>
  /dev/fuse ux,
  /bin/** ux,
  sleep ux,
  /usr/** ux,
}
EOF
```

When I use docker run : 
`docker run -it --cap-add SYS_ADMIN  --device /dev/fuse --security-opt apparmor=docker-fuse6 ubuntu-sshfs`
It is ok to use sshfs to mount a remote file.

But when I use k8s yaml, it doesn`t work.

```
apiVersion: v1
kind: Pod
metadata:
  name: capacity-hippojava-deployment
  annotations:
    container.apparmor.security.beta.kubernetes.io/capacity-hippojava: localhost/docker-fuse6
spec:
  containers:
  - name: capacity-hippojava
    image: 192.168.1.1/library/manu/ubuntu-sshfs:1
    command:
    - /bin/sh
    - -ec
    - |
      sleep 30000
    ports:
    - containerPort: 80
    securityContext:
      capabilities:
        add:
          - SYS_ADMIN
          - MKNOD
    volumeMounts:
    - mountPath: /dev/fuse
      name: fuse
  volumes:
  - hostPath:
      path: /dev/fuse
    name: fuse
```

Cloud any one help me? I have no idea with it.

**Comment by mattjmcnaughton** [comment]
Hi @ChenLong2014 

Just to confirm, this failure is occurring on a k8s 1.8 cluster?

Would it be possible for you to upgrade to a supported k8s version as a first step in debugging? 1.13, 1.14 and 1.15 are the currently supported versions.

**Comment by ChenLong2014** [comment]
Hi mattjmcnaughton,
I got
 `fuse: failed to open /dev/fuse: Operation not permitted`

yes, My k8s version is 1.8. 

OK, I will update the k8s version to test this.  And I still have a problem.

1ST,
Is my YAML is correct?  
Especially the annotation of the yaml~~~
```
apiVersion: v1
kind: Pod
metadata:
  name: capacity-hippojava-deployment
  annotations:
    container.apparmor.security.beta.kubernetes.io/capacity-hippojava: localhost/docker-fuse6
spec:
```

2ND,
What EVN or CONFIG I have to open and config?
APPARMOR enable ?
APISERVER : --feature-gates=AppArmor=true

I find a lot of reference about this. But it seems everyone is right. I have no idea about.
Finally I tried podsecuritypolicy, it doesn`t work.

If I want use K8S of APPARMOR, what kind of ENV or CONFIG I need to do.

I hope you can help me with what kind of ENV or CONFIG I need to do.

 I will try with high level K8S later, I will check it.
