### ISSUE TITLE
Endpoint is accessible, but service is not. Only occurs on one app's service.

### ISSUE THREAD

**Issue by xiaozhongliu** [kubernetes/kubernetes#79419]
**What happened**:
Endpoint is accessible, but service is not.

**What you expected to happen**:
If Endpoint is accessible, service should also be normal.

**How to reproduce it (as minimally and precisely as possible)**:
I don't know. This issue stably happens on one of our apps, the other apps are normal.

**Anything else we need to know?**:
```sh
[hangzhou:prod-hangzhou]➜  ~ k get ep/bd-college-model
NAME               ENDPOINTS         AGE
bd-college-model   172.18.1.4:3333   81m

[hangzhou:prod-hangzhou]➜  ~ k exec -it bd-college-model-7598fdf65f-drv8s sh
sh-4.2# curl 172.18.1.4:3333  # returns normally
sh-4.2# curl bd-college-model # hangs on
```

On the target server where the pod locates:
```sh
[root@iZbp1gfvwtes9lxuonwoguZ ~]# iptables-save | grep bd-college-model
-A KUBE-SERVICES ! -s 172.18.0.0/16 -d 172.19.1.66/32 -p tcp -m comment --comment "prod-hangzhou/bd-college-model: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 172.19.1.66/32 -p tcp -m comment --comment "prod-hangzhou/bd-college-model: cluster IP" -m tcp --dport 80 -j KUBE-SVC-IECE6NNADMMUT5PG
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"01a904e", GitTreeState:"", BuildDate:"2019-02-28T13:54:16Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
Alibaba Cloud ACK
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux iZbp1gfvwtes9lxuonwoguZ 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
One key installation
```
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sack0k** [comment]
Please attach svc and pod yaml.

**Comment by xiaozhongliu** [comment]
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bd-college-model
spec:
  selector:
    matchLabels:
      app: bd-college-model
  revisionHistoryLimit: 3
  minReadySeconds: 5
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: bd-college-model
        region: hangzhou
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: bd-college-model
          image: xxx/xxx/bd-college-model:0.0.1-release
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          env:
            - name: NODE_ENV
              value: prod
            - name: SERVER_ENV
              value: prod
            - name: EGG_SERVER_ENV
              value: prod
            - name: EGG_WORKERS
              value: '2'
            - name: REGION
              value: hangzhou
            - name: ENTRY_FILE
              value: ./main.js
            - name: TYPE
              value: meteor
            - name: TZ
              value: Asia/Shanghai
            - name: LANG
              value: C.UTF-8
            - name: ENV_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: bd-college-model-config
                  key: startup.prod.sh
          volumeMounts:
            - mountPath: /root/logs/bd-college-model
              name: log-volume
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 1000m
              memory: 500Mi

          livenessProbe:
            httpGet:
              path: /
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3333
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 5
      volumes:
        - name: log-volume
          hostPath:
            path: /var/log/app/bd-college-model
      nodeSelector:
        usage: app

---

apiVersion: v1
kind: Service
metadata:
  name: bd-college-model
  labels:
    app: bd-college-model
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3333
  selector:
    app: bd-college-model
    region: hangzhou
```
