### ISSUE TITLE
Stateful set scaling causes SecurityContext loss

### ISSUE THREAD

**Issue by aroundthecode** [kubernetes/kubernetes#79478]
**What happened**:
Scaling a StatefulSet causes SecurityContext reset to default

**What you expected to happen**:
SecurityContext should be preserved upon scaling

**How to reproduce it (as minimally and precisely as possible)**:
deploy a StatefulSet set with

```
      securityContext:
        sysctls:
        - name: net.ipv4.tcp_fin_timeout
          value: "10"
        - name: net.ipv4.tcp_tw_reuse
          value: "1"
        - name: net.ipv4.tcp_keepalive_time
          value: "600"
        - name: net.ipv4.tcp_keepalive_intvl
          value: "60"
        - name: net.ipv4.tcp_keepalive_probes
          value: "20"
        - name: net.ipv4.tcp_retries2
          value: "8"
```
first Pod correctly gets securityContext values.

Scaling to 2 reset StatefulSet securityContext to {}
```
 securityContext: {}
```

 Second Pod is therefore deployed without properties and finally first pod is re-deployed to remove properties to align with new StatefulSet configuration

**Anything else we need to know?**:
* This happen scaling both from kubedashboard or kubectl scale cli
* Using Edit and setting replicas to 2 or deploying StatefulSet directly to 2 doesn't rise the issue and properties are correctly preserved on both pods

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.6
- Cloud provider or hardware configuration: on-premise cluster
- OS (e.g: `cat /etc/os-release`): CentOs 7.6.1810
- Kernel (e.g. `uname -a`): 4.20.13
- Install tools: kubeadm on custom ansible
- Network plugin and version (if this is a network-related bug): 
- Others:

**Comment by tedyu** [comment]
Was PodSecurityContext involved ?

Thanks

**Comment by aroundthecode** [comment]
here is an exctract of the helm chart deployng statefulset:

```
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: RELEASE-NAME
  labels:
    chart: db-couchbase-2.0.0
    release: RELEASE-NAME
    heritage: Tiller
    app: db-couchbase
    profile: staging
spec:
  serviceName: "couchbase"
  replicas: 2
  selector:
    matchLabels:
      chart: db-couchbase-2.0.0
      release: RELEASE-NAME
      heritage: Tiller
      app: db-couchbase
      profile: staging
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        chart: db-couchbase-2.0.0
        release: RELEASE-NAME
        heritage: Tiller
        app: db-couchbase
        profile: staging
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.tcp_fin_timeout
            value: "10"
          - name: net.ipv4.tcp_tw_reuse
            value: "1"
          - name: net.ipv4.tcp_keepalive_time
            value: "600"
          - name: net.ipv4.tcp_keepalive_intvl
            value: "60"
          - name: net.ipv4.tcp_keepalive_probes
            value: "20"
          - name: net.ipv4.tcp_retries2
            value: "8"
          
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: com.mycompany.couchbase
                  operator: In
                  values:
                    - staging
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: com.mycompany.couchbase
                    operator: In
                    values:
                     - staging
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: RELEASE-NAME
          image: 'docker.mycompany.int/devops/couchbase:community-6.0-cluster'
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 6Gi
            requests:
              memory: 6Gi
            
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: rest
            timeoutSeconds: 5
            
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: rest
            timeoutSeconds: 5
            

          ports:
            - containerPort: 8091
              name: "rest"
              protocol: "TCP"

          env:
            - name: "SSET_NAME"
              value: "RELEASE-NAME"

          volumeMounts:
            - name: pvc
              mountPath: /opt/couchbase/var
```
