### ISSUE TITLE
Multiple LimitRange objects can have conflicting values in the same namespace

### ISSUE THREAD

**Issue by akanso** [kubernetes/kubernetes#79496]
Within the same namespace, we can create two conflicting LimitRange objects that can block the creation of any pod

**What happened**:

For a given resource, e.g. `memory`, if the `min` specified in the first LimitRange is `greater than` the `max` specified in the second LimitRange, then we would be blocked from creating any pod. 

**What you expected to happen**:

The second LimitRange object should be rejected, since, for a given resource, it conflicts with an existing LimitRange. 

The rule would be that for a given resource no `min` should be `>` max specified in another LimitRange in the same namespace (or `max < min`)

**How to reproduce it (as minimally and precisely as possible)**:

create two conflicting LimitRange:

```
kubectl apply -f- <<EOF
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "1000m"
      memory: "1Gi"
    min:
      cpu: "200m"
      memory: "200Mi"
    default:
      cpu: "700m"
      memory: "700Mi"
    defaultRequest:
      cpu: "250m"
      memory: "250Mi"
    type: Container
EOF

kubectl apply -f- <<EOF
apiVersion: v1
kind: LimitRange
metadata:
  name: another-limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "100m"
      memory: "100Mi"
    min:
      cpu: "50m"
      memory: "50Mi"
    default:
      cpu: "75m"
      memory: "75Mi"
    defaultRequest:
      cpu: "60m"
      memory: "60Mi"
    type: Container
EOF
```

then try to create a pod:

```
kubectl apply -f- <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: no-limits-or-requests
spec:
  containers:
  - name: no-limits-or-requests
    image: nginx
EOF

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
```
- Kernel (e.g. `uname -a`):
```
Linux worker-node1 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x
```

/sig api-machinery
