### ISSUE TITLE
'kubectl apply' failed when change the number of the volumeMounts

### ISSUE THREAD

**Issue by zqzzq** [kubernetes/kubernetes#79510]
**What happened**:
in my cluster I have a deployment with 5 volumeMounts and 5 volumes : 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 12
  labels:
    app: istio-ingressgateway
    chart: gateways-1.0.4
    heritage: Tiller
    istio: ingressgateway
    release: istio-ingressgateway
  name: istio-ingressgateway
  namespace: istio-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: istio-ingressgateway
        istio: ingressgateway
    spec:
      containers:
      - args:
        - proxy
        - router
        - -v
        - "2"
        - --discoveryRefreshDelay
        - 1s
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --connectTimeout
        - 10s
        - --serviceCluster
        - istio-ingressgateway
        - --zipkinAddress
        - zipkin:9411
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - NONE
        - --discoveryAddress
        - istio-pilot:8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: registry.icp.com:5000/library/istio/docker.io/istio/proxyv2:1.0.4
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/certs
          name: istio-certs
          readOnly: true
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          readOnly: true
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          readOnly: true
        - mountPath: /etc/istio/ingressgateway-inspurcloud-certs
          name: ingressgateway-inspurcloud-certs
          readOnly: true
        - mountPath: /etc/istio/ingressgateway-inspurcloudapi-certs
          name: ingressgateway-inspurcloudapi-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: istio-ingressgateway-service-account
      serviceAccountName: istio-ingressgateway-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - name: istio-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: istio.istio-ingressgateway-service-account
      - name: ingressgateway-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: istio-ingressgateway-certs
      - name: ingressgateway-ca-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: istio-ingressgateway-ca-certs
      - name: ingressgateway-inspurcloud-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: istio-ingressgateway-inspurcloud-certs
      - name: ingressgateway-inspurcloudapi-certs
        secret:
          defaultMode: 420
          optional: true
          secretName: istio-ingressgateway-inspurcloudapi-certs
```
then I used ‘ kubectl apply -f ’ to change the number of the volumeMounts and volumes to 3, the new deployment is: 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    chart: gateways
    heritage: Tiller
    release: istio
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  template:
    metadata:
      labels:
        chart: gateways
        heritage: Tiller
        release: istio
        app: istio-ingressgateway
        istio: ingressgateway
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: istio-ingressgateway-service-account
      containers:
        - name: istio-proxy
          image: "registry.icp.com:5000/library/plover/istio/proxyv2:lc_v1.1.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 15090
              protocol: TCP
              name: http-envoy-prom
          args:
          - proxy
          - router
          - --domain
          - $(POD_NAMESPACE).svc.cluster.local
          - --log_output_level
          - 'info'
          - --drainDuration
          - '45s' #drainDuration
          - --parentShutdownDuration
          - '1m0s' #parentShutdownDuration
          - --connectTimeout
          - '10s' #connectTimeout
          - --serviceCluster
          - istio-ingressgateway
          - --zipkinAddress
          - zipkin:9411
          - --proxyAdminPort
          - "15000"
          - --statusPort
          - "15020"
          - --controlPlaneAuthPolicy
          - NONE
          - --discoveryAddress
          - istio-pilot:15010
          resources:
            requests:
              cpu: 10m 
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: ISTIO_META_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: ISTIO_META_CONFIG_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ISTIO_META_ROUTER_MODE
            value: sni-dnat
          volumeMounts:
          - name: istio-certs
            mountPath: /etc/certs
            readOnly: true
          - name: ingressgateway-certs
            mountPath: "/etc/istio/ingressgateway-certs"
            readOnly: true
          - name: ingressgateway-ca-certs
            mountPath: "/etc/istio/ingressgateway-ca-certs"
            readOnly: true
      volumes:
      - name: istio-certs
        secret:
          secretName: istio.istio-ingressgateway-service-account
          optional: true
      - name: ingressgateway-certs
        secret:
          secretName: "istio-ingressgateway-certs"
          optional: true
      - name: ingressgateway-ca-certs
        secret:
          secretName: "istio-ingressgateway-ca-certs"
          optional: true
``` 
but I get an error:
```
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"istio-ingressgateway\",\"chart\":\"gateways\",\"heritage\":\"Tiller\",\"istio\":\"ingressgateway\",\"release\":\"istio\"},\"name\":\"istio-ingressgateway\",\"namespace\":\"istio-system\"},\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"scheduler.alpha.kubernetes.io/critical-pod\":\"\",\"sidecar.istio.io/inject\":\"false\"},\"labels\":{\"app\":\"istio-ingressgateway\",\"chart\":\"gateways\",\"heritage\":\"Tiller\",\"istio\":\"ingressgateway\",\"release\":\"istio\"}},\"spec\":{\"affinity\":{\"nodeAffinity\":{\"preferredDuringSchedulingIgnoredDuringExecution\":[{\"preference\":{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"amd64\"]}]},\"weight\":2},{\"preference\":{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"ppc64le\"]}]},\"weight\":2},{\"preference\":{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"s390x\"]}]},\"weight\":2}],\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"beta.kubernetes.io/arch\",\"operator\":\"In\",\"values\":[\"amd64\",\"ppc64le\",\"s390x\"]}]}]}}},\"containers\":[{\"args\":[\"proxy\",\"router\",\"--domain\",\"$(POD_NAMESPACE).svc.cluster.local\",\"--log_output_level\",\"info\",\"--drainDuration\",\"45s\",\"--parentShutdownDuration\",\"1m0s\",\"--connectTimeout\",\"10s\",\"--serviceCluster\",\"istio-ingressgateway\",\"--zipkinAddress\",\"zipkin:9411\",\"--proxyAdminPort\",\"15000\",\"--statusPort\",\"15020\",\"--controlPlaneAuthPolicy\",\"NONE\",\"--discoveryAddress\",\"istio-pilot:15010\"],\"env\":[{\"name\":\"POD_NAME\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.name\"}}},{\"name\":\"POD_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.namespace\"}}},{\"name\":\"INSTANCE_IP\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"status.podIP\"}}},{\"name\":\"ISTIO_META_POD_NAME\",\"valueFrom\":{\"fieldRef\":{\"apiVersion\":\"v1\",\"fieldPath\":\"metadata.name\"}}},{\"name\":\"ISTIO_META_CONFIG_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}},{\"name\":\"ISTIO_META_ROUTER_MODE\",\"value\":\"sni-dnat\"}],\"image\":\"registry.inspurcloud.cn/library/plover/istio/proxyv2:lc_v1.1.2\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"istio-proxy\",\"ports\":[{\"containerPort\":80},{\"containerPort\":443},{\"containerPort\":31400},{\"containerPort\":15029},{\"containerPort\":15030},{\"containerPort\":15031},{\"containerPort\":15032},{\"containerPort\":15443},{\"containerPort\":15020},{\"containerPort\":15090,\"name\":\"http-envoy-prom\",\"protocol\":\"TCP\"}],\"readinessProbe\":{\"failureThreshold\":30,\"httpGet\":{\"path\":\"/healthz/ready\",\"port\":15020,\"scheme\":\"HTTP\"},\"initialDelaySeconds\":1,\"periodSeconds\":2,\"successThreshold\":1,\"timeoutSeconds\":1},\"resources\":{\"requests\":{\"cpu\":\"10m\"}},\"volumeMounts\":[{\"mountPath\":\"/etc/certs\",\"name\":\"istio-certs\",\"readOnly\":true},{\"mountPath\":\"/etc/istio/ingressgateway-certs\",\"name\":\"ingressgateway-certs\",\"readOnly\":true},{\"mountPath\":\"/etc/istio/ingressgateway-ca-certs\",\"name\":\"ingressgateway-ca-certs\",\"readOnly\":true}]}],\"serviceAccountName\":\"istio-ingressgateway-service-account\",\"volumes\":[{\"name\":\"istio-certs\",\"secret\":{\"optional\":true,\"secretName\":\"istio.istio-ingressgateway-service-account\"}},{\"name\":\"ingressgateway-certs\",\"secret\":{\"optional\":true,\"secretName\":\"istio-ingressgateway-certs\"}},{\"name\":\"ingressgateway-ca-certs\",\"secret\":{\"optional\":true,\"secretName\":\"istio-ingressgateway-ca-certs\"}}]}}}}\n"},"labels":{"chart":"gateways","release":"istio"}},"spec":{"replicas":null,"template":{"metadata":{"labels":{"chart":"gateways","heritage":"Tiller","release":"istio"}},"spec":{"$setElementOrder/containers":[{"name":"istio-proxy"}],"$setElementOrder/volumes":[{"name":"istio-certs"},{"name":"ingressgateway-certs"},{"name":"ingressgateway-ca-certs"}],"containers":[{"$setElementOrder/env":[{"name":"POD_NAME"},{"name":"POD_NAMESPACE"},{"name":"INSTANCE_IP"},{"name":"ISTIO_META_POD_NAME"},{"name":"ISTIO_META_CONFIG_NAMESPACE"},{"name":"ISTIO_META_ROUTER_MODE"}],"$setElementOrder/ports":[{"containerPort":80},{"containerPort":443},{"containerPort":31400},{"containerPort":15029},{"containerPort":15030},{"containerPort":15031},{"containerPort":15032},{"containerPort":15443},{"containerPort":15020},{"containerPort":15090}],"$setElementOrder/volumeMounts":[{"mountPath":"/etc/certs"},{"mountPath":"/etc/istio/ingressgateway-certs"},{"mountPath":"/etc/istio/ingressgateway-ca-certs"}],"args":["proxy","router","--domain","$(POD_NAMESPACE).svc.cluster.local","--log_output_level","info","--drainDuration","45s","--parentShutdownDuration","1m0s","--connectTimeout","10s","--serviceCluster","istio-ingressgateway","--zipkinAddress","zipkin:9411","--proxyAdminPort","15000","--statusPort","15020","--controlPlaneAuthPolicy","NONE","--discoveryAddress","istio-pilot:15010"],"env":[{"name":"ISTIO_META_CONFIG_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"ISTIO_META_ROUTER_MODE","value":"sni-dnat"}],"image":"registry.inspurcloud.cn/library/plover/istio/proxyv2:lc_v1.1.2","name":"istio-proxy","ports":[{"containerPort":15029},{"containerPort":15032},{"containerPort":15443},{"containerPort":15020}],"readinessProbe":{"failureThreshold":30,"httpGet":{"path":"/healthz/ready","port":15020,"scheme":"HTTP"},"initialDelaySeconds":1,"periodSeconds":2,"successThreshold":1,"timeoutSeconds":1}},{"$patch":"delete","name":"ingressgateway"}],"volumes":[{"$patch":"delete","name":"ingressgateway-inspurcloud-certs"}]}}}}
to:
&{0xc4200d0e40 0xc42087f260 istio-system istio-ingressgateway istio_1.1.2_lc.yaml 0xc423b1e140 69250241 false}
for: "istio_1.1.2_lc.yaml": Deployment.apps "istio-ingressgateway" is invalid: spec.template.spec.containers[0].volumeMounts[3].name: Not found: "ingressgateway-inspurcloud-certs"
```
I don't quite understand about 
```
"volumes":[{"$patch":"delete","name":"ingressgateway-inspurcloud-certs"}]
```
How did this error happen?

**What you expected to happen**:
The deployment successful update
**Environment**:
- Kubernetes version (use `kubectl version`):v1.10.4
