### ISSUE TITLE
kubectl wait stucks if YAML declaration contains different resource types

### ISSUE THREAD

**Issue by nikkatalnikov** [kubernetes/kubernetes#79607]
**What happened**:

The following YAML

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: cp-schema-registry-external
  labels:
    app: cp-schema-registry
spec:
  type: NodePort
  ports:
    - name: schema-registry-external
      targetPort: 8081
      port: 8081
      nodePort: 32081
  selector:
    app: cp-schema-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-schema-registry
  labels:
    app: cp-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-schema-registry
  template:
    metadata:
      labels:
        app: cp-schema-registry
    spec:
      containers:
        - name: cp-schema-registry-server
          image: "confluentinc/cp-schema-registry:5.1.2"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: schema-registry
              containerPort: 8081
              protocol: TCP
```

does not work for

```
 kubectl wait -f schema-registry.yaml --for condition=available
``` 

it simply stucks. However, 

```yaml
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: cp-schema-registry-external
#  labels:
#    app: cp-schema-registry
#spec:
#  type: NodePort
#  ports:
#    - name: schema-registry-external
#      targetPort: 8081
#      port: 8081
#      nodePort: 32081
#  selector:
#    app: cp-schema-registry
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: cp-schema-registry
#  labels:
#    app: cp-schema-registry
#spec:
#  ports:
#    - name: http
#      port: 8081
#  selector:
#    app: cp-schema-registry
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-schema-registry
  labels:
    app: cp-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-schema-registry
  template:
    metadata:
      labels:
        app: cp-schema-registry
    spec:
      containers:
        - name: cp-schema-registry-server
          image: "confluentinc/cp-schema-registry:5.1.2"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: schema-registry
              containerPort: 8081
              protocol: TCP
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-broker-0.kafka-headless.default.svc.cluster.local:9092
            - name: SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID
              value: minikube
            - name: SCHEMA_REGISTRY_MASTER_ELIGIBILITY
              value: "true"
            - name: SCHEMA_REGISTRY_HEAP_OPTS
              value: "-Xms256M -Xmx256M"
            - name: SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL
              value: "none"
```

works as expected

**Why is that needed?**:

I think it will simplify devops' life not to care about how YAMLs are composed from kubectl prospective, but rather compose them from logical prospective (for humans).
