### ISSUE TITLE
kube-scheduler in CrashLoopBackoff Error after passing custom scheduling policy 

### ISSUE THREAD

**Issue by zsl3203** [kubernetes/kubernetes#79632]
**What happened**:

I'm trying to pass a custom policy configuration to the scheduler but some error occurred, the k8s 
deployment failed and the kube-scheduler CrashLoopBackOff.

**What you expected to happen**:

Run well

**How to reproduce it (as minimally and precisely as possible)**:

I'm trying the pass the conf to scheduler through kubeadm init
```
kubeadm init --conf scheduler.yaml
```
where scheduler.yaml is as following
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.15.0
scheduler:
  extraArgs:
    policy-config-file: /summer/conf.json
```
And the conf.json is the example scheduler policy conf file provided here https://github.com/kubernetes/kubernetes/blob/release-1.1/examples/scheduler-policy-config.json
```
{
"kind" : "Policy",
"apiVersion" : "v1",
"predicates" : [
	{"name" : "PodFitsPorts"},
	{"name" : "PodFitsResources"},
	{"name" : "NoDiskConflict"},
	{"name" : "MatchNodeSelector"},
	{"name" : "HostName"}
	],
"priorities" : [
	{"name" : "LeastRequestedPriority", "weight" : 1},
	{"name" : "BalancedResourceAllocation", "weight" : 1},
	{"name" : "ServiceSpreadingPriority", "weight" : 1},
	{"name" : "EqualPriority", "weight" : 1}
	]
}
```
Then error occur
```
kubectl get nodes
NAME                                      STATUS     ROLES    AGE    VERSION
master.test.shield-pg0.utah.cloudlab.us   NotReady   master   154m   v1.15.0

kubectl get pods --all-namespaces
NAMESPACE     NAME                                                              READY   STATUS             RESTARTS   AGE
kube-system   coredns-5c98db65d4-6zvs8                                          0/1     Pending            0          155m
kube-system   coredns-5c98db65d4-9n8qc                                          0/1     Pending            0          155m
kube-system   etcd-master.test.shield-pg0.utah.cloudlab.us                      1/1     Running            0          154m
kube-system   kube-apiserver-master.test.shield-pg0.utah.cloudlab.us            1/1     Running            0          154m
kube-system   kube-controller-manager-master.test.shield-pg0.utah.cloudlab.us   1/1     Running            0          154m
kube-system   kube-proxy-rcdf2                                                  0/1     Pending            0          155m
kube-system   kube-scheduler-master.test.shield-pg0.utah.cloudlab.us            0/1     CrashLoopBackOff   35         155m
kube-system   weave-net-w9949                                                   0/2     Pending            0          155m
```

**Anything else we need to know?**:

/etc/kubernetes/manifests/kube-scheduler.yaml
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    - --policy-config-file=/summer/conf.json
    image: k8s.gcr.io/kube-scheduler:v1.15.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status: {}
```
How I deploy the k8s cluster
```
apt-get update -y
swapoff -a

apt-get update && apt-get install apt-transport-https ca-certificates curl software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"

apt-get update && apt-get install docker-ce=18.06.2~ce~3-0~ubuntu

cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
EOF

mkdir -p /etc/systemd/system/docker.service.d

systemctl daemon-reload
systemctl restart docker

apt-get update && apt-get install -y apt-transport-https curl

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

cat << EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF

apt-get update
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl

kubeadm init --conf scheduler.yaml

mkdir -p $HOME/.kube
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
chown $(id -u):$(id -g) $HOME/.kube/config

kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

kubectl taint nodes --all node-role.kubernetes.io/master-

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: CloudLab
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux master.scheduler.shield-pg0.utah.cloudlab.us 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by fishercht1995** [comment]
You can try to build a scheduler in a pod.

**Comment by SataQiu** [comment]
I guess you need to mount `/summer/conf.json` for kube-scheduler container.
Try to edit `/etc/kubernetes/manifests/kube-scheduler.yaml`, add `volumeMounts` and `volumes` :
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
    ...
    volumeMounts:
    - mountPath: /summer/conf.json
      name: kube-scheduler-policy
      readOnly: true
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /summer/conf.json
      type: File
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
```
