### ISSUE TITLE
CSI expanding persistent volume does not call csi.ControllerExpandVolume

### ISSUE THREAD

**Issue by Ntr0** [kubernetes/kubernetes#79716]
**What happened**:
Deployed a csi driver with volume expansion capability (online). Defined following storage class:

```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: ionos-enterprise-hdd
parameters:
  type: HDD
provisioner: cloud.ionos.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
Created a pvc:
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName:  ionos-enterprise-hdd
```
Increasing the requested storage parameter in the pvc works as expected: First ControllerExpandVolume is called, then NodeExpandVolume.
But increasing the storage size in the underlying pv has the effect, that only NodeExpandVolume is called, (which of course does not work, since ControllerExpandVolume is required beforehands).
**What you expected to happen**:
If it is actually allowed to change the persistent volume, than ControllerExpandVolume must be called.

**How to reproduce it (as minimally and precisely as possible)**:

* use a csi driver that supports expand volume
* adopt provided config yamls for the csi driver
* apply configs
* increase the capactity.storage property of the created pv

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.0
- Cloud provider or hardware configuration: Ionos Enterprise Cloud
- OS (e.g: `cat /etc/os-release`): CentOS 7 
- Kernel (e.g. `uname -a`): 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
