### ISSUE TITLE
Cluster port name used as implicit endpoint selector

### ISSUE THREAD

**Issue by wdec** [kubernetes/kubernetes#79732]
**What happened**:

When running a cluster service and manually created endpoints, the port name set on the cluster definition acts as an implicit selector - suitable end-points do not get mapped to the cluster service. 

**What you expected to happen**:
Port name shouldn't be an implicit selector.

**How to reproduce it (as minimally and precisely as possible)**:
Using the following spec file "spec.yaml":

```
apiVersion: v1
kind: Service
metadata:
  name: &cluster_name pgname
  labels:
    app: pgname
    cluster-name: *cluster_name
spec:
  type: ClusterIP
  ports:
    - port: 5432
      #name: foobar
      targetPort: 5432

---
apiVersion: v1
kind: Endpoints
metadata:
  name: &cluster_name pgname
  labels:
    app: pgname
    cluster-name: *cluster_name
subsets:
  -
    addresses:
      -
        ip: "19.1.1.1"
    ports :
      -
        port: 5432

---
```

1. Run kubectl create -f spec.yaml, then describe the service. Output shows the endpoint as being correctly mapped

```
root@172-25-87-82-master:/home/cw-admin# kubectl describe service pgname   
Name:              pgname
Namespace:         default
Labels:            app=pgname
                   cluster-name=pgname
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.102.97.50
Port:              <unset>  5432/TCP
TargetPort:        5432/TCP
Endpoints:         19.1.1.1:5432
Session Affinity:  None
Events:            <none>
```

Now run kubectl delete -f spec.yaml

2. Edit the spec.yaml and uncomment the _name: foobar_
Re-run the kubectl create -f spec.yaml. command. Now, checking the service gives the output below (end point isn't mapped):

```
root@172-25-87-82-master:/home/cw-admin# kubectl create -f test-service.yaml 
service/pgname created
endpoints/pgname created
root@172-25-87-82-master:/home/cw-admin# kubectl describe service pgname
Name:              pgname
Namespace:         default
Labels:            app=pgname
                   cluster-name=pgname
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP:                10.103.242.211
Port:              foobar  5432/TCP
TargetPort:        5432/TCP
Endpoints:         
Session Affinity:  None
Events:            <none>
```

**Anything else we need to know?**:

Adding the _name: foobar_ to the endpoint definition makes the end point to be mapped again into the cluster. I.e. there is an implicit matching of the end-point and cluster port definitions. This is either a bug or a very surprising and undocumented feature

**Environment**:

kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

root@172-25-87-82-master:/home/cw-admin# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"

- Kernel (e.g. `uname -a`):

uname -a
Linux 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
