### ISSUE TITLE
HPA condition status is incorrectly reported

### ISSUE THREAD

**Issue by ankilosaurus** [kubernetes/kubernetes#79773]
What happened:
HPA status condition and result seems out of sync. 
```
Min replicas:                                                 36
Max replicas:                                                 45
Deployment pods:                                              36 current / 36 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from external metric XXX
  ScalingLimited  True    TooFewReplicas    the desired replica count is more than the maximum replica count
Events:           <none>
```

What you expected to happen:
ScalingLimited should have message in sync with reason "TooFewReplicas" 
```
ScalingLimited  True    TooFewReplicas    the desired replica count is more than the maximum replica count
```

**How to reproduce it (as minimally and precisely as possible)**:
Create deployment with desired replica count less than HPA Min replicas
```
spec:
  maxReplicas: 45
  minReplicas: 36
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: X
status:
  currentReplicas: 36
  desiredReplicas: 36
  lastScaleTime: 2019-07-03T21:22:41Z 
```

Environment:
- Kubernetes version (use `kubectl version`): v1.12.8
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
```

- Kernel (e.g. `uname -a`): 4.4.0-1081-aws #91-Ubuntu SMP Tue Apr 16 08:21:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
