### ISSUE TITLE
[Umbrella Issue] Apiserver flow-control API model tracker

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#79776]
/sig api-machinery

- Flow-schemas should be applied to a set of namespaces https://github.com/kubernetes/kubernetes/pull/77048#discussion_r293007047
- Setting queueLengthLimit of a PL to zero executes the inbound requests immediately https://github.com/kubernetes/kubernetes/pull/77048#discussion_r300041647

**Comment by MikeSpreitzer** [comment]
Regarding setting the queueLengthLimit of a priority level to zero, my proposal is not that it grants anything exceptional; rather it is merely treated uniformly with other values: zero is the limit on the length of a queue.  So I might reword the above to something more like "Allow zero queue length limit".

**Comment by MikeSpreitzer** [comment]
I made a PR for the object namespace issue: #81637

**Comment by MikeSpreitzer** [comment]
Another issue is that the currently implemented models are not expressive enough to identify leader elections for system controllers.  The KEP currently has this syntax:
```
  - and: # leader elections for system controllers
    - patternMatch:
      field: user
      pattern: system:controller:.*
    - inSet:
      field: resource
      set: [ "endpoints", "configmaps", "leases" ]
    - equals:
      field: namespace
      value: kube-system
```

But currently there is nothing like that `*` implemented.

**Comment by MikeSpreitzer** [comment]
Another issue is that the currently implemented models can not express "any service account".  The KEP currently calls for that, along with negation (whose lack we can work around with higher-precedence matching of the complement):
```
kind: FlowSchema
meta:
  name: workload-high
spec:
  requestPriority:
    name: workload-high
  flowDistinguisher:
    source: namespace
    # no transformation in this case
  match:
  - and: # users using kubectl
    - notPatternMatch:
      field: user
      pattern: system:serviceaccount:.*
```
(The idea is that earlier flow schemas have matched everything except workload, which consists of users using kubectl and controllers using service accounts.)

**Comment by MikeSpreitzer** [comment]
/cc @yliaog 
/cc @aaron-prindle 
/cc @lavalamp 
/cc @deads2k 
@mars1024

**Comment by MikeSpreitzer** [comment]
Another issue is that the models can not currently express discrimination on the namespace of the object that the request seeks to manipulate.  This was an accidental oversight; in our initial enthusiasm for adopting data types from rbac we did not notice that rbac discriminates on object namespace in a fairly idiosyncratic way that is not reflected in the datatypes we copied.

Object namespace is a major feature of the kube API object system, and we agreed from the start that this feature should be able to discriminate on it.  For example, the KEP exercises that ability in two rules for the `system-high` FlowSchema (https://github.com/kubernetes/enhancements/blob/aba897e14b2663c2a479c1c60654a57887e236d1/keps/sig-api-machinery/20190228-priority-and-fairness.md#example-configuration):
```
  - and: # kubelet and kube-proxy ops on system objects
    - superSet:
      field: groups
      set: [ "system:nodes" ]
    - equals:
      field: namespace
      value: kube-system
  - and: # leader elections for system controllers
    - patternMatch:
      field: user
      pattern: system:controller:.*
    - inSet:
      field: resource
      set: [ "endpoints", "configmaps", "leases" ]
    - equals:
      field: namespace
      value: kube-system
```
