### ISSUE TITLE
Ambiguous error message when creating Binding (error: object does not implement the Object interfaces)

### ISSUE THREAD

**Issue by akanso** [kubernetes/kubernetes#79801]
**Issue:**

Ambiguous error message when using `kubectl apply` to create a `Binding` to assign a pod to a node.

Using `kubectl create` solves the issue.

I understand that `Binding` is a special K8s resource that can only be `created`. However the error message is ambiguous. A better message is to issue a `warning` about using `apply` on an immutable resource. 

**Behavior, and to replicate:**

```
kubectl apply -f- <<EOF
apiVersion: v1
kind: Binding
metadata:
  name: test-pod
  namespace: default
target:
  apiVersion: v1
  kind: Node
  name: worker-node2
EOF
```

the binding is created successfully, however, it is followed by an error message:

```
error: object does not implement the Object interfaces
```

**System:**

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

/sig api-machinery
