### ISSUE TITLE
Unable to create PVC using a storage class with vSphere storage policy defined (secure connection to vCenter)

### ISSUE THREAD

**Issue by paemason** [kubernetes/kubernetes#79809]
Expectation-
We should be able to create PVCs via a storageclass with storagePolicyName defined while using a singed ca cert for secure communications with vCenter. 

Bug-
The PVC created with a storageclass with storagePolicyName defined fails with a `x509: certificate signed by unknown authority` error when PVCs created with a storageclass without the storagPolicyName work against the same vCenter and datastore.

Scenario:
Utilizing the vSphere in-tree plugin on kubernetes 1.12.7.
Utilizing secure communication with vSphere (signed ca cert imported into the cluster)
We are able to create PVCs with the following storage class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc1
provisioner: kubernetes.io/vsphere-volume
parameters:
  datastore: datastore1
```

However, if we include a storagePolicyName we receive a failure:
`  Warning  ProvisioningFailed  0s (x3 over 29s)  persistentvolume-controller  Failed to provision volume with StorageClass "sc1": Post https://[redacted].com:443/pbm/sdk: x509: certificate signed by unknown authority`

Here is the yaml for our sc1 storage class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc1
provisioner: kubernetes.io/vsphere-volume
parameters:
  storagePolicyName: storageclass1
  datastore: datastore1
```
/sig vmware
