### ISSUE TITLE
Kubernetes Pod environment variables integrated with key-value store database.

### ISSUE THREAD

**Issue by mk811** [kubernetes/kubernetes#79810]
**What would you like to be added**:
Integrating key-value store (let's say consul) with Kubernetes. 
Inject environment variable to POD by calling API of the key-value store when the POD is deployed.
What I want to request is adding to `apiKeyRef` as a way to inject environment variable.

Let's say, we have a Key-Value store. 
The response of its API to get some key is as below:
```json
# curl -X GET http://0.0.0.0:8500/v1/kv/sample_env_var_key
{
    "Status": "Success",
    "Message": {
        "Key": "sample_env_var_key",
        "Value": "sample_env_var_value"
    }
}
```

To Get the value from the Key-Value store, Kubernetes Manifest would be:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
  - name: sample
    image: some/image/name:v1
    env:
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
  - name: env-var-test
    image: some/image/name:v1
    env:
    - name: API_TOKEN
      secretKeyRef:
        name: secret
        key: api_token
    - name: SAMPLE_ENV_VAR
      apiKeyRef:
        key: sample_env_var_key
        endpoint: http://0.0.0.0:8500/v1/kv/SAMPLE_ENV_VAR_KEY
        reqHeader: "Token: $(API_TOKEN)"
        respBody: .Message.Value
```

**Why is this needed**:
To reduce costs to maintaining environment variables.
Currently we use ConfigMap or Secret to share Key-Value configurations across PODs.
In our case, even though we just want to update one key-value, we need update ConfigMap by itself, which is kinda risk.

On the other hand, I've seen several companies have own key value store to manage application configurations / environment variables.
Those databases assigne a context to a value, a single key can have multiple values, each with a unique context signature, such as prod/stg/qa/dev.
I think it would be a good idea to leverage this kind of key-value store to inject environment variables to POD.
