### ISSUE TITLE
Different Webhook with same name have same label-value in metric webhook_admission_duration_seconds

### ISSUE THREAD

**Issue by answer1991** [kubernetes/kubernetes#79832]
**What happened**:

Different Webhook with same name have same label-value in metric `webhook_admission_duration_seconds`. For now, we can add two or more Webhooks using the same name. Webhooks with same name will get the same label-value in metric `webhook_admission_duration_seconds` and record different Webhooks into the same label-value metric.

**What you expected to happen**:

Difference Webhooks which have same name using their AdmissionConfiguration(MutatingWebhookConfiguration or ValidatingWebhookConfiguration) name. Add a new label `configuration_name` to metric `webhook_admission_duration_seconds`.

**How to reproduce it (as minimally and precisely as possible)**:

Create two MutatingWebhookConfiguration which have same Webhook name like the flowing codes:

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-a
webhooks:
  - name: mutating-pod.k8s.io
...
---

apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-b
webhooks:
  - name: mutating-pod.k8s.io
...
```

**Anything else we need to know?**:

Nothing yet.

**Environment**:

No cares about that.
