### ISSUE TITLE
APIService backed by service that 404s on / fails on clusters with v1.15

### ISSUE THREAD

**Issue by Pothulapati** [kubernetes/kubernetes#79838]
**What happened**:
[smi-metrics](https://github.com/deislabs/smi-metrics/blob/master/chart/templates/apiservice.yaml) runs as a APIService but it fails with `Failed Discovery Check` and the endpoint returns `service unavailable` on kubernetes clusters with v1.15. It works with all previous cluster versions perfectly but gives the following status on v1.15 but I also don't see any changes in Releasing notes that effects APIService
```
  conditions:
  - lastTransitionTime: "2019-06-28T16:20:22Z"
    message: 'failing or missing response from https://10.100.82.130:443: bad status
      from https://10.100.82.130:443: 404'
    reason: FailedDiscoveryCheck
    status: "False"
    type: Available
```

**What you expected to happen**:

APISerice should run correctly and the endpoint should be responding.

**How to reproduce it (as minimally and precisely as possible)**:

Linkerd dosent have to be installed to check this, and discovery happens directly at the `/` url without any communication with the underlying mesh.

In the repo, running this generates the required certs and applies the config to the cluster

`helm template chart -f dev.yaml -f linkerd.yaml --name dev | kubectl apply -f -`

To check the status of the APIService,
`kubectl get apiservice v1alpha1.metrics.smi-spec.io -o yaml` can be used

**Anything else we need to know?**:
I did check with clean 1.15 clusters and its the same. I also don't see any changes in 1.15 release notes that effects APIServices. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:41:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
 Testing is done on kind but its the same with minikube
