### ISSUE TITLE
How to run K8 pods with multiple docker daemons?

### ISSUE THREAD

**Issue by rohanricky** [kubernetes/kubernetes#79839]
I am creating multiple docker daemons each with a different partition to host the images. 

```
sudo dockerd \
        -H unix:///var/run/docker.sock\
        -p /var/run/docker-bootstrap.pid \
        --iptables=false \
        --ip-masq=false \
        --bridge=none \
        --data-root=/mnt/sdb/ \
        --exec-root=/var/run/docker-bootstrap
```
To run a container from specific image I specify -H for docker like:
`docker -H unix:///var/run/custom_docker.sock pull image`

How to specify `-H` host location in the pod.yaml to run the container inside the pod?

I tried mounting the docker.sock and doing a docker run via the command argument in the pod.yaml. But does this approach help in the pod maintainence?

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 6orke23r
spec:
  replicas: 1
  template:
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      initContainers:
      - name: init-python
        image: docker
      containers:
      - name: python
        image: docker
        command: ["/bin/sh', '-c', 'docker run -H unix:///var/run/docker.sock -i -d --shm-size 8G ubuntu:march2019"]
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersock1234
      volumes:
      - name: dockersock1234
        hostPath:
         path: /var/run/docker.sock
``` 

Will I have any problems with the K8 management of my container? What is the better approach to specify the host like docker?
