### ISSUE TITLE
Mapping Atlas MongoDB timed out

### ISSUE THREAD

**Issue by dwctua** [kubernetes/kubernetes#79855]
**What happened**:
Follow [instruction](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-mapping-external-services) to map Mongo DB(Atlas) as external service, but getting error:
{ "message": "context deadline exceeded" }

**What you expected to happen**:
The service should be able to redirect the request to Atlas

**How to reproduce it (as minimally and precisely as possible)**:
1. Create service as the following.
```
apiVersion: v1
kind: Service
metadata:
 name: mongodb
spec:
 ports:
 - port: 27017
   targetPort: 27017
---
apiVersion: v1
kind: Endpoints
metadata:
 name: mongodb
subsets:
 - addresses:
     - ip: 3.214.123.70
     - ip: 3.220.123.150
     - ip: 3.86.1.169
   ports:
     - port: 27017
```
2.  Create an account at cloud.mongodb.com
3. Connect to Mongo DB with uri as `mongodb://user:passwd@mongodb/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority `

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
minikube
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
