### ISSUE TITLE
Kubeflow three pods stuck that persistent volume claims stuck in pending state for NFS persistent volumes

### ISSUE THREAD

**Issue by edowson** [kubernetes/kubernetes#79867]
**What happened**: I installed `kubeflow` on kubernetes and there are three pods that have their persistent volume claims stuck in a pending state even though I've created the required pv.

Here are the pvc claims:
```bash
kubectl -n kubeflow get pvc -o custom-columns='name:{.metadata.name},storage:{.spec.resources.requests.storage}'
name             storage
katib-mysql      10Gi
minio-pvc        20Gi
mysql-pv-claim   20Gi
```

Create persistent volumes that meet pvc requirements:
```bash
sudo nano k8s-nfs-pv-volume1.yaml
```

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume3
spec:
  storageClassName:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.252.56
    path: "/volume1/pv/pv-volume3"
```

```bash
sudo nano k8s-nfs-pv-volume2.yaml
```
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume2
spec:
  storageClassName:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.252.56
    path: "/volume1/pv/pv-volume2"
```

```bash
sudo nano k8s-nfs-pv-volume3.yaml
```

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume3
spec:
  storageClassName:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.252.56
    path: "/volume1/pv/pv-volume3"
```

Create persistent volumes:
```bash
kubectl apply -f ./k8s-nfs-pv-volume1.yaml
kubectl apply -f ./k8s-nfs-pv-volume2.yaml
kubectl apply -f ./k8s-nfs-pv-volume3.yaml
```

```bash
kubectl get pv

NAME         CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
pv-volume1   10Gi       RWX            Retain           Available           standard                12s
pv-volume2   20Gi       RWX            Retain           Available           standard                10s
pv-volume3   20Gi       RWX            Retain           Available           standard                8s
```
Check PVC status:
```bash
kubectl -n kubeflow get pvc

NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
katib-mysql      Pending                                                     9m18s
minio-pvc        Pending                                                     8m44s
mysql-pv-claim   Pending                                                     8m44s
```

**What you expected to happen**: I expected the PVCs to be satisfied by the PVs.

**How to reproduce it (as minimally and precisely as possible)**:

Install k8s, create the PVs, and then do a basic install of kubeflow onto kubernetes v.1.14.3

```bash
export KFAPP=my-kubeflow
# Default uses IAP.
kfctl init ${KFAPP}
cd ${KFAPP}
kfctl generate all -V
kfctl apply all -V
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.3
- Cloud provider or hardware configuration: Intel Xeon-D 8-core, 16GB RAM, 480GB SSD, NFS drive.
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): 4.18.0-25-generic
- Install tools: none
- Network plugin and version (if this is a network-related bug): na
- Others: none

@kubernetes/sig-storage-bugs

**Comment by edowson** [comment]
@kubernetes/sig-storage-bugs

**Comment by msau42** [comment]
Your PV and PVC storageclass names don't seem to match.  

Also to help with future debugging, it's helpful to check the events on PVC and pod.

**Comment by edowson** [comment]
@msau42 If you notice, I didn't specify a `StorageClass` for the `pv` as indicated in the official troubleshooting documentation. It automatically sets `Standard` by default.

However, I think the issue is with my `pv` `accessModes`  set to `ReadWriteMany`. I think the three pods require it to be `ReadWriteSingle`. Once I created three `pv` with `accessModes` set to `ReadWriteSingle`, the `pvc` works.

**Comment by msau42** [comment]
The [default storageclass admission controller](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/storage/storageclass/setdefault/admission.go) only sets a default storageclass for PVC, not PV.

But your output of `kubectl get pv` shows a non-empty storageclass on the PV object.  I'm not sure what else could be setting a storageclass for your PV.

**Comment by msau42** [comment]
NFS volumes should be able to support `ReadWriteMany`.   I suspect you still have some issue binding to the wrong PV, and it's binding to a cloud disk instead of your NFS PVs.

**Comment by edowson** [comment]
@msau42 The config files for the pv that I posted in the bug report are the ones that I used to setup the three `pv`s. I do not have a cloud disk. I setup an on-premise k8s cluster, connected to a local NFS drive.

I decided to switch to a local SSD folder for the `pv`s, as show below, and the three pods were able to bind their `pvc`s to the `pv`s.

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume1
spec:
  storageClassName:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/pv/pv-volume1"
```

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume2
spec:
  storageClassName:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/pv/pv-volume2"
```

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume3
spec:
  storageClassName:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/pv/pv-volume3"
```

If I have to try it again using the NFS mounts, then I'd have to tear down the entire k8s cluster and try again. For example, when I deleted the `kubeflow` app, and reinstalled it again, the `pvc`s did not bind to the `pv`s

The k8s infrastructure seems fragile and is not very robust to repeated changes in basic configuration settings.

Additionally, due to API level changes between versions, things don't quite work as intended. For example, I started out trying k8s v1.15.0-00, and discovered that kubeflow doesn't work with that version. 

There was also a pull request that's pending for updating the troubleshooting guide, mentioning that one pv has to be 10Gi and the other two 20Gi, but no one has applied it so far.
