### ISSUE TITLE
image gc was still trigged even set high threshhold 100

### ISSUE THREAD

**Issue by liqlin2015** [kubernetes/kubernetes#79929]
**What happened**:

image gc was still triggered even set image gc high threshhold 100
```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
  imagefs.available: "0%"
  memory.available: "100Mi"
  nodefs.available: "0%"
  nodefs.inodesFree: "0%"
imageGCHighThresholdPercent: 100
imageGCLowThresholdPercent: 100
```

From this code
```
	usagePercent := 100 - int(available*100/capacity)
	if usagePercent >= im.policy.HighThresholdPercent {
		amountToFree := capacity*int64(100-im.policy.LowThresholdPercent)/100 - available
		klog.Infof("[imageGCManager]: Disk usage on image filesystem is at %d%% which is over the high threshold (%d%%). Trying to free %d bytes down to the low threshold (%d%%).", usagePercent, im.policy.HighThresholdPercent, amountToFree, im.policy.LowThresholdPercent)
		freed, err := im.freeSpace(amountToFree, time.Now())
```

We can see image gc was triggered even `amountToFree` was a negative value. Should we check value of `amountToFree` before we invoke `im.freeSpace(amountToFree, time.Now())` ?

**What you expected to happen**:
image gc should not be triggered when set high threshhold to 100.

**How to reproduce it (as minimally and precisely as possible)**:
1. Have this kubelet config
```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
evictionHard:
  imagefs.available: "0%"
  memory.available: "100Mi"
  nodefs.available: "0%"
  nodefs.inodesFree: "0%"
imageGCHighThresholdPercent: 100
imageGCLowThresholdPercent: 100
```

2. Try to full fill image fs to 100%.

3. Monitor unused images on the node. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.7
- Cloud provider or hardware configuration: None
- OS (e.g: `cat /etc/os-release`): ubuntu
- Kernel (e.g. `uname -a`):
- Install tools: None
- Network plugin and version (if this is a network-related bug): 
- Others:
