### ISSUE TITLE
iSCSI storage plugin not cleaning up dir

### ISSUE THREAD

**Issue by bertinatto** [kubernetes/kubernetes#79973]
**What happened**:

When creating a block volume, the iSCSI storage plugin stores volume-related data in different directories:

```console
# tree /var/lib/kubelet/plugins/kubernetes.io/iscsi
/var/lib/kubelet/plugins/kubernetes.io/iscsi
`-- volumeDevices
    |-- iface-127.0.0.1:3260:pv1
    |   `-- 127.0.0.1:3260-iqn.2003-01.io.k8s:e2e.volume-1-lun-2
    |       `-- iscsi.json
    `-- iface-default
        `-- 127.0.0.1:3260-iqn.2003-01.io.k8s:e2e.volume-1-lun-2
            `-- 9c205fba-730a-430e-8b48-5f53dba9a7db -> /dev/sdc

5 directories, 2 files
```
As a result, some data is not cleaned up once the volume is detached:

```console
# tree /var/lib/kubelet/plugins/kubernetes.io/iscsi
/var/lib/kubelet/plugins/kubernetes.io/iscsi
`-- volumeDevices
    |-- iface-127.0.0.1:3260:pv1
    |   `-- 127.0.0.1:3260-iqn.2003-01.io.k8s:e2e.volume-1-lun-2
    |       `-- iscsi.json
    `-- iface-default

4 directories, 1 file
```
**How to reproduce it (as minimally and precisely as possible)**:

These are the objects I used to reproduce this issue:

claim.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: ""
  resources:
    requests:
      storage: 50Mi
```

pod-block.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-block
  labels:
    name: test
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  tolerations:
    - key: node.kubernetes.io/network-unavailable
  containers:
    - image: gcr.io/google_containers/busybox
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do date; sleep 1; done"
      name: busybox
      volumeDevices:
        - name: vol
          devicePath: /mnt/test
  volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: claim1
```

pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv1
spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Mi
    iscsi:
      fsType: ext4
      iqn: iqn.2003-01.io.k8s:e2e.volume-1
      iscsiInterface: default
      lun: 2
      targetPortal: 127.0.0.1:3260
      initiatorName: "iqn.1994-05.com.redhat:2a3ac65b173"
    persistentVolumeReclaimPolicy: Delete
    volumeMode: Block
```

/sig storage
CC @jsafrane, @msau42, @bswartz, @j-griffith
