### ISSUE TITLE
service yaml enchantment for SIP servers

### ISSUE THREAD

**Issue by sergey-safarov** [kubernetes/kubernetes#80111]
**What would you like to be added**:
I want publish StateFulSet via service and cloud `LoadBalancer` for SIP servers. To get it working properly i found some issues that requires some of kubernetes enchantments:
1) [public IP limits](https://github.com/kubernetes/kubernetes/issues/80110)
2) [static IP for Amazon cloud](https://github.com/kubernetes/kubernetes/issues/80107)
3) [UDP for Amazon NLB](https://github.com/kubernetes/kubernetes/issues/79523)

Could you add support of yaml files like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: proxy-dc0-0
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: proxy
  type: LoadBalancerPeerPod
  loadBalancerIP:
  - 34.211.156.102
  - 54.149.51.189
  - 35.165.172.1
  - 34.211.156.102
  externalTrafficPolicy: Local
  ports:
  - name: sip
    protocol:
    - TCP
    - UDP
#    - SCTP
    port: 5060
    targetPort: 5060
  - name: sip-alg
    protocol:
    - TCP
    - UDP
    port: 7000
    targetPort: 7000
```

*Enchantment 1*
```
type: LoadBalancerPeerPod
```
Details at [public IP limits](https://github.com/kubernetes/kubernetes/issues/80110)

*Enchantment 2*
```
  loadBalancerIP:
  - 34.211.156.102
  - 54.149.51.189
  - 35.165.172.1
  - 34.211.156.102
```
For published service I can specify several IP. As example for SteteFulSet of 5 SIP server replicas. In example I can specify 4 static IP, one for each replica, and one dynamic IP for last server.

*Enchantment 3*
```
    protocol:
    - TCP
    - UDP
```

For services that use some port over several transport protocols i want specify protocols as array.

**Why is this needed**:
This required to properly publish services that use public IP at application level (L7 OSI).
As example for SIP servers that use public IP in call signaling.

/sig network

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by thockin** [comment]
Regarding multiple LB IPs:  A service is a single IP.  You want a service per replica.

regarding multi-protocol LBs:  We specifically didn't allow this because on some providers it costs more money.  We allow it for ClusterIP services but not LoadBalancer.  I am open to reconsidering this.  https://github.com/kubernetes/kubernetes/issues/23880

**Comment by sergey-safarov** [comment]
> Regarding multiple LB IPs: A service is a single IP. You want a service per replica.

Why not create `ServiceTemplate` and use it `StateFulSet` like?
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy
spec:
  serviceName: proxy
  replicas: 4
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: kamailio/kamailio-ci:5.1.6
  ServiceTemplates:
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    spec:
      app: proxy
      ports:
      - protocol: TCP
        port: 5060
        targetPort: 5060
```

> regarding multi-protocol LBs: We specifically didn't allow this because on some providers it costs more money. We allow it for ClusterIP services but not LoadBalancer. I am open to reconsidering this.

Such providers may check now many protocols specified in yaml file. If more then one, then generate error message like `"cloud provider XXX do not support multi-protocol 'Loadbalancer' services"`.
