### ISSUE TITLE
Add limit of used zones/IP for service cloud LoadBalancer

### ISSUE THREAD

**Issue by sergey-safarov** [kubernetes/kubernetes#80110]
**What would you like to be added**:
I want publish SIP service for external Internet. To do this recommended use service with type `LoadBalancer`. In my case to get it working properly need assign only one IP for each `pod:port`.
In current implementation `LoadBalancer` created over several zones and one `private` IP matched to several `public` IP.
Example

yaml file
```yaml
apiVersion: v1
kind: Service
metadata:
  name: proxy-dc0-0
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    statefulset.kubernetes.io/pod-name: proxy-dc0-0
  type: LoadBalancer
  ports:
  - name: sip
    port: 5060
    protocol: TCP
    targetPort: 5060
```
service status
```sh
[safarov@safarov-dell kube]$ kubectl describe service proxy-dc0-0
Name:                     proxy-dc0-0
Namespace:                ippbx
Labels:                   <none>
Annotations:              service.beta.kubernetes.io/aws-load-balancer-type: nlb
Selector:                 statefulset.kubernetes.io/pod-name=proxy-dc0-0
Type:                     LoadBalancer
IP:                       10.100.5.33
LoadBalancer Ingress:     abd45deeea4d911e98d500a4e92bef38-62dd1831e110ee07.elb.us-west-2.amazonaws.com
Port:                     sip  5060/TCP
TargetPort:               5060/TCP
NodePort:                 sip  32755/TCP
Endpoints:                
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age    From                Message
  ----    ------                ----   ----                -------
  Normal  EnsuringLoadBalancer  3m20s  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   3m17s  service-controller  Ensured load balancer
```
public IP
```sh
[safarov@safarov-dell kube]$ nslookup abd45deeea4d911e98d500a4e92bef38-62dd1831e110ee07.elb.us-west-2.amazonaws.com
Server:		192.168.100.1
Address:	192.168.100.1#53

Non-authoritative answer:
Name:	abd45deeea4d911e98d500a4e92bef38-62dd1831e110ee07.elb.us-west-2.amazonaws.com
Address: 54.149.51.189
Name:	abd45deeea4d911e98d500a4e92bef38-62dd1831e110ee07.elb.us-west-2.amazonaws.com
Address: 35.165.172.1
Name:	abd45deeea4d911e98d500a4e92bef38-62dd1831e110ee07.elb.us-west-2.amazonaws.com
Address: 52.37.24.89
Name:	abd45deeea4d911e98d500a4e92bef38-62dd1831e110ee07.elb.us-west-2.amazonaws.com
Address: 35.155.206.55
```

Could you add ability publish service using cloud `LoadBalancer` via not more one IP for each pod:port. Like
```yaml
apiVersion: v1
kind: Service
metadata:
  name: proxy-dc0-0
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    statefulset.kubernetes.io/pod-name: proxy-dc0-0
  type: LoadBalancerPeerPod
  ports:
  - name: sip
    port: 5060
    protocol: TCP
    targetPort: 5060
```

**Why is this needed**:
This required for services that use public IP at application level (L7 OSI).
Example SIP servers use public IP in call signaling.

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by thockin** [comment]
What you're asking for is a change in the way Amazon handles load-balancing.  ELB is a DNS name.  For counter-example, GCP is a single IP.

/sig aws

I will note that it looks like you want an NLB but are getting an ELB, maybe your annotation is wrong.

Regardless this is not something that Service can control - it is an artifact of the provider.

**Comment by sergey-safarov** [comment]
Hello @thockin 
Annotations is correct
```yaml
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
```
I also checked via AWS console and via tcpdump I can see sender L3 IP address.

Issue reopened at [`cloud-provider-aws`](https://github.com/kubernetes/cloud-provider-aws/issues/47)
