### ISSUE TITLE
Static IP for pod

### ISSUE THREAD

**Issue by sergey-safarov** [kubernetes/kubernetes#80122]
**What would you like to be added**:
Requested ability to specify static IP for pod. like
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kamailio
spec:
  publicIP: 34.211.156.102
  containers:
  - image: kamailio/kamailio-ci:5.1.6
    command:
      - sleep
      - "3600"
    name: kamailio
```
And StateFulSet
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kamailio
spec:
  serviceName: kamailio
  replicas: 4
  selector:
    matchLabels:
      app: kamailio
  PublicIPPool:
  - 34.211.156.102
  - 54.149.51.189
  - 35.165.172.1
  PublicIPFailback: dinamic
  template:
    metadata:
      labels:
        app: kamailio
    spec:
      containers:
      - name: kamailio
        image: kamailio/kamailio-ci:5.1.6
```
If StateFulSet create replicas more than public IP available or specified IP used by other service and `PublicIPFailback` have `dynamic` value, then assign dynamic IP.
If `PublicIPFailback` have `none` value, then pod will not start until one of IP specified in `PublicIPPool` array is available.

*How it can be done for Amazon cloud*
I can add Elastic IP for NIC and then specify pod IP. Screenshot attached.
![pod-static-ip](https://user-images.githubusercontent.com/2562241/61168859-e63f6780-a55c-11e9-9ed0-4449d38ea451.png)

**Why is this needed**:
SIP servers use random port to create outbound connection via TCP transport protocol. If SIP server is already published using `service` with type `LoadBalancer` and use load balancer public IP in application layer (call signaling), then it lead to mismatch with info at network layer. At application layer used `LoadBalancer` public IP, at network layer (IP for Internet hosts) used pod dynamic IP.

*Second case*
Customers may use firewall for security reasons. When cloud server use one IP via load balancer (static or semi static IP) and second dynamic IP for pod outbound connections, then no chance to pass on firewall connection from pod to customer equipment after pod recreation.

/sig network

**Comment by sergey-safarov** [comment]
Addition about cloud firewall.
If pods have list of `ports`, then need to be sure this ports allowed on firewall.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kamailio
spec:
  publicIP: 34.211.156.102
  containers:
  - image: kamailio/kamailio-ci:5.1.6
    name: kamailio
    ports:
    - containerPort: 5060
      protocol: TCP
    - containerPort: 5060
      protocol: UDP
#    - containerPort: 5060
#      protocol: SCTP
```

**Comment by dgunjetti** [comment]
Is this typical case of SIP behind NAT, in which case SIP device behind NAT is configured to use external IP in SIP headers. NAT device opens range of ports as specified in rtp.conf to handle multiple simultaneous calls. I think here it drops to supporting port-range in service than static ip for pods. There is long standing PR "Support port ranges in services #23864" does anyone know its current state.

**Comment by sergey-safarov** [comment]
Ticket 23864 cannot be resolved until `docker` daemon will be able publish port ranges without thousand iptables rules.

But more important next info.
Usage case  `publishing via service` is more complex then `publishing pod directly`.
Reasons:
1) used double NAT. First at Amazon cloud, second at kebernetes instances.
2) real SIP servers not ready to work with double NAT configuration. They wrote for one NAT configuration. FreeSwitch as example.

Publishing POD directly simplify SIP usage inside Kubernetes. And allow RTP ranges without docker daemon modification. Just need to link additional cloud ACL rule with Kubernetes node.
But your clarification important.
For FreeSwitch daemon need add ACL rules with port ranges like
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: FreeSwitch
spec:
  publicIP: 34.211.156.102
  containers:
  - image: safarov/freeswitch:1.8.5
    name: freeswitch
    ports:
    - containerPort: 5060
      protocol:
      - TCP
      - UDP
#      - SCTP
    - containerPort: 16384-32768
      protocol:
      - UDP
```

**Comment by dgunjetti** [comment]
to avoid double bounce we can set  "service.spec.externalTrafficPolicy: OnlyLocal" in which case packet is delivered to local pod on VM.

**Comment by sergey-safarov** [comment]
In this case I can see SIP device L3 IP address on server side.
But this not solves requirements use during a call one External IP on servers side for call delivered via `Cloud Load Balancer` and other External IP for call created from SIP server to SIP device.
That is stuck for Kamailio and FreeSwitch that I use.

**Comment by dgunjetti** [comment]
at Kamailio, can we configure external ip to be LB IP address, so that only one external ip address is used.

**Comment by sergey-safarov** [comment]
Please look #80110 
At present time in `service yaml` file I cannot specify how many IP need use on NLB.

That is response for your question.
But how expect four outbound call from Kamailio to phone via same NLB?
NLB designed to accept call from internet to server. But how to make call in reverse direction?

**Comment by dgunjetti** [comment]
ok.. the scenario is single private ip is mapped by multiple external ip. In a non-k8s scenario do you configure multiple virtual IPs on SIP server, virtual IPs being same as multiple NLB? if so, then [Multus CNI](https://github.com/intel/multus-cni) needs to explored which allows creation of multiple interfaces in a pod.

**Comment by sergey-safarov** [comment]
On our case we create two statefulset of kamailio:
1) for public internet clients (equpment);
2) for VPN connected equipment (private IP range used).

**Comment by sergey-safarov** [comment]
You pointed me to important moment.
For call via Amazon VPN we also need static `privateIP`. Static IP via `kubernetes service` also not useful here.
Because `one to one` mapping will be more complex than simple IP assignments to Pod. Also NAT rules need to maintain on kubenetes host.

May be create kubernetes entity `ippull` like
```yaml
apiVersion: v1
kind: IPpool
metadata:
  name: freeswitch
spec:
  IPv4public:
    - 34.211.156.102
    - 54.149.51.189
    - subnet-0b59ea0b349d43697
  IPv4private:
    - 192.168.1.1
    - 192.168.2.4/30
    - subnet-03de97fef0dd10f27
    - 192.168.3.17-192.168.3.33
  IPv6public:
    - 2a05:ddc0::2:a
    - 2a05:ddc0::2:a/112
    - subnet-38853c4e
  IPv6private:
    - fd35:08df:24b5:fd7a::0
    - fd35:08df:24b5:fd7a::/120
    - subnet-79707631
```
Where IP address or IP network may be specified directly or via cloud provider id like `subnet-79707631`.

Later this `IPpool` may be used from pod.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: FreeSwitch
spec:
  IPpool: freeswitch
  containers:
  - image: safarov/freeswitch:1.8.5
    name: freeswitch
    ports:
    - containerPort: 5060
      protocol:
      - TCP
      - UDP
#      - SCTP
    - containerPort: 16384-32768
      protocol:
      - UDP
```

**Comment by dgunjetti** [comment]
Pod's IP address allocation is handled by network plugin, usually the ip range for pods is specified in network plugin configuration, creating a kubernetes object will not work. and dual stack support of ipv4/ipv6 is still in implementation phase AFAIK. 

I think we need to explore more on possibilities of solving this via service. For one-to-one nat mapping of cluster-ip to pod-ip, I can provide code changes, with 1:1nat port translation is avoided and all ports on cluster-ip gets opened for pods, so RTP traffic can flow in/out of cluster-ip.

**Comment by sergey-safarov** [comment]
Hi Deepack @dgunjetti
> Pod's IP address allocation is handled by network plugin

In this case I spoke not about docker IP pool that managed by network plugin.
I spoke about kubernetes or service IP address pool.
This pools used during pods (or service) creations for `--ip` option value of `docker run` command.
**Example**
```
docker run --network xxxxxx \
           --ip 192.168.1.25 \
           safarov/freeswitch:1.8.5
```
Here we just request network plugin to assign IP. We not try to do it be self.
As example we have docker network `192.168.10.0/24` and here for SIP pods we want use 4 IP `192.168.10.16`, `192.168.10.17`, `192.168.10.18`, `192.168.10.19`. To create IP pool request i expect prepare yaml file like
```yaml
apiVersion: v1
kind: IPpool
metadata:
  name: freeswitch
spec:
  IPv4public:
    - 34.211.156.102
    - 54.149.51.189
  IPv4private:
    - 192.168.10.16/30
```
