### ISSUE TITLE
SRV record not created for named port of service without selector

### ISSUE THREAD

**Issue by irozzo-1A** [kubernetes/kubernetes#80175]
**What happened**:
I created a headless service without selector for an external service in order to be able to do an SRV lookup as explained [here](https://github.com/kubernetes/dns/blob/1.11.0/docs/specification.md#242---srv-records)

**What you expected to happen**:
I expected to have an SRV record matching the following format: `_my-port-name._my-port-protocol.my-svc.my-namespace.svc.cluster-domain.example` but it was not present. I tried with another headless service, with selector this time, and in this case the SRV record was there.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the service
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: srvtest
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: srvtest
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb
  namespace: srvtest
subsets:
  - addresses:
      - ip: 192.168.2.2
      - ip: 192.168.2.3
      - ip: 192.168.2.4
    ports:
      - port: 27017
EOF
```
2. Try to retrieve the SRV record
```
dig _mongodb._tcp.mongodb.srvtest.svc.cluster.local SRV

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> _mongodb._tcp.mongodb.srvtest.svc.cluster.local SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 56056
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_mongodb._tcp.mongodb.srvtest.svc.cluster.local. IN SRV

;; AUTHORITY SECTION:
cluster.local.		30	IN	SOA	ns.dns.cluster.local. hostmaster.cluster.local. 1563210605 7200 1800 86400 30

;; Query time: 0 msec
;; SERVER: 10.100.0.10#53(10.100.0.10)
;; WHEN: Mon Jul 15 17:13:13 UTC 2019
;; MSG SIZE  rcvd: 169
```

**Anything else we need to know?**:

Format `my-svc.my-namespace.svc.cluster-domain.example` works as expected:
```
# dig mongodb.srvtest.svc.cluster.local SRV

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> mongodb.srvtest.svc.cluster.local SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19525
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 4

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mongodb.srvtest.svc.cluster.local. IN	SRV

;; ANSWER SECTION:
mongodb.srvtest.svc.cluster.local. 5 IN	SRV	0 33 27017 192-168-2-2.mongodb.srvtest.svc.cluster.local.
mongodb.srvtest.svc.cluster.local. 5 IN	SRV	0 33 27017 192-168-2-3.mongodb.srvtest.svc.cluster.local.
mongodb.srvtest.svc.cluster.local. 5 IN	SRV	0 33 27017 192-168-2-4.mongodb.srvtest.svc.cluster.local.

;; ADDITIONAL SECTION:
192-168-2-2.mongodb.srvtest.svc.cluster.local. 5 IN A 192.168.2.2
192-168-2-3.mongodb.srvtest.svc.cluster.local. 5 IN A 192.168.2.3
192-168-2-4.mongodb.srvtest.svc.cluster.local. 5 IN A 192.168.2.4

;; Query time: 1 msec
;; SERVER: 10.100.0.10#53(10.100.0.10)
;; WHEN: Mon Jul 15 17:16:06 UTC 2019
;; MSG SIZE  rcvd: 539
```
**Environment**:
- Kubernetes version (use `kubectl version`): `v1.11.8-eks-7c34c0`
- Cloud provider or hardware configuration: AWS

**Comment by irozzo-1A** [comment]
@kubernetes/sig-network-bugs

**Comment by prameshj** [comment]
Is this using CoreDNS or kube-dns?

**Comment by chrisohaver** [comment]
I suspect this is kube-dns, since it's k8s 1.11.  Nevertheless with CoreDNS, it works if you fully specify complete port info in the endpoints object.  I suspect the behavior is similar with kube-dns. e.g. 

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: srvtest
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: srvtest
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb
  namespace: srvtest
subsets:
  - addresses:
      - ip: 192.168.2.2
      - ip: 192.168.2.3
      - ip: 192.168.2.4
    ports:
      - name: mongodb
        port: 27017
        protocol: TCP
EOF
```
