### ISSUE TITLE
PodTemplateSpec metadata behaves differently within CronJob vs Deployment

### ISSUE THREAD

**Issue by jflatow** [kubernetes/kubernetes#80330]
**What happened**:

According to the docs, these are both PodTemplateSpec (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#podtemplatespec-v1-core), however in one case it seems that the metadata applies to the Pod (Deployment) and the other to the Pod template (CronJob). The former seems more useful, but they shouldn't be different I think.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template: # PodTemplateSpec
    metadata:
      labels:
        my-label: pod-label
```

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cron-job
spec:
  jobTemplate:
    spec:
      template: # PodTemplateSpec
        metadata:
          labels:
            my-label: pod-spec-label
```

**What you expected to happen**:

I expected the CronJob JobTemplateSpec JobSpec PodTemplateSpec metadata to work the same as the Deployment PodTemplateSpec metadata.

**How to reproduce it (as minimally and precisely as possible)**:

See the yaml above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-beta.0", GitCommit:"bde05a518c62656c7d368e55bb70dcf41a6ec074", GitTreeState:"clean", BuildDate:"2019-06-14T21:17:43Z", GoVersion:"devel +b5be877ba4 Mon Feb 4 20:20:15 2019 +0000", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

I upgraded GKE to the latest available version and it is still like this.

- Cloud provider or hardware configuration: GCP/GKE
