### ISSUE TITLE
The StorageClass "test" is invalid: parameters: Forbidden: updates to parameters are forbidden.

### ISSUE THREAD

**Issue by zgfh** [kubernetes/kubernetes#80472]
**What happened**:
when I update csi parameters of test StorageClass,it return error
```
# kubectl apply -f storageclass.yaml
The StorageClass "csi-rbd-k8setcdbackup" is invalid: parameters: Forbidden: updates to parameters are forbidden.
```
**What you expected to happen**:
we should allow update storageclass
**How to reproduce it (as minimally and precisely as possible)**:
```
cat > test-sc.yaml <<-EOF
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-rbd-dem2
  namespace: kube-system
parameters:
  adminid: admin
  csiNodePublishSecretName: csi-rbd-secret
  csiNodePublishSecretNamespace: kube-system
  csiProvisionerSecretName: csi-rbd-secret
  csiProvisionerSecretNamespace: kube-system
  imageFeatures: layering
  imageFormat: "2"
  monitors: 127.0.0.2:6789
  pool: k8spool
  userid: admin
provisioner: csi-rbdplugin
reclaimPolicy: Delete
volumeBindingMode: Immediate
EOF
kubectl apply -f test-sc.yaml
sed -i 's/127.0.0.2/127.0.0.1/g' test-sc.yaml
kubectl apply -f test-sc.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.0
- OS (e.g: `cat /etc/os-release`):  centos 7
