### ISSUE TITLE
kubeadm join control plane with config errors out

### ISSUE THREAD

**Issue by PI-Victor** [kubernetes/kubernetes#80483]
**What happened**:

```bash
$ kubeadm join --config kubeadm-master-join.yaml
[preflight] Running pre-flight checks
        [WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.0. Latest validated version: 18.09
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
error execution phase preflight:
One or more conditions for hosting a new control plane instance is not satisfied.

failure loading certificate for CA: couldn't load the certificate file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory

Please ensure that:
* The cluster has a stable controlPlaneEndpoint address.
* The certificates that must be shared among control plane instances are provided.
```
**What you expected to happen**:
I have a HA setup and after i bootstrap the initial node, i need to join the rest of the control plane nodes as well. Since `--config` and other join flags cannot be used together, i need to have everything in a config file. I do this because i need extra args passed to the kubelet, see below the yaml.

```yaml
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: removed
    apiServerEndpoint: $KEEPALIVED_IP
    caCertHashes:
    - sha256:removed
nodeRegistration:
  kubeletExtraArgs:
    dynamic-config-dir: "/etc/kubernetes/dynconf"
controlPlane:
  localAPIEndpoint:
    advertiseAddress: $LOCAL_IP
    bindPort: 6443
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates:
  DynamicKubeletConfig: true
```
Here's what i think should happen, and please correct me if i'm missing something:
As covered in the docs, i'd expect `localAPIEndpoint` to signal a new control plane bootstrap,
where the certificates are pulled from the specified `apiServerEndpoint` (which is the initial node) and new manifests are being generated locally by kubeadm and then the bootstrap process begins as it should with a normal 
`  kubeadm join $KEEPALIVED_IP:6443 --token removed --discovery-token-ca-cert-hash removed --control-plane`

Here's what i think happens:
The bootstrap process begins before the certificates are pulled from the initial control plane node, hence the `failure loading certificate for CA: couldn't load the certificate file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory`.
Could some please advise if i'm doing this wrong or if it's an actual bug?

**How to reproduce it (as minimally and precisely as possible)**:
Use the YAML above after bootstrapping the initial control plane node, fill in the token and ca-cert-hash and api endpoint and try to join a new control plane node.

**Anything else we need to know?**:
The initial kubeadm cluster config for posterity, use to bootstrap the initial node
```yaml
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    dynamic-config-dir: "/etc/kubernetes/dynconf"
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "$KEEPALIVED_IP:6443"
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
  - 192.168.54.20 
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates:
  DynamicKubeletConfig: true
```
l.e.: i'm aware it says
```Please ensure that:
* The certificates that must be shared among control plane instances are provided.
```
and that i could copy the cert, but i'd expect the bootstrap process to work just as it does from passing flags to `kubeadm join`.

**Environment**:
- Kubernetes version (use `kubectl version`): kubeadm v1.15.1
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04
- Kernel (e.g. `uname -a`): 
- Install tools: 
- Network plugin and version (if this is a network-related bug): flannel cni
- Others:
