### ISSUE TITLE
pod stuck on CrashLoopBackOff

### ISSUE THREAD

**Issue by shenlanse** [kubernetes/kubernetes#80507]
**What happened**:

damonset pod stuck on CrashLoopBackOff:

```
$ kubectl -n kube-system get pods | grep node-problem-detector
node-problem-detector-2v5nb                               1/1       Running            2          15d
node-problem-detector-526q8                               1/1       Running            0          15d
node-problem-detector-5n5n2                               1/1       Running            0          15d
node-problem-detector-7lbz8                               1/1       Running            2          15d
node-problem-detector-dnmgs                               0/1       CrashLoopBackOff   289        15d
node-problem-detector-fkdfc                               1/1       Running            0          5d
node-problem-detector-h2flx                               1/1       Running            0          15d
node-problem-detector-hdzqg                               1/1       Running            0          5d
node-problem-detector-kl7gs                               1/1       Running            0          5d
node-problem-detector-l4hjp                               1/1       Running            0          15d
node-problem-detector-l58tl                               1/1       Running            0          5d
node-problem-detector-m9mnn                               1/1       Running            0          5d
node-problem-detector-nmqxn                               1/1       Running            1          15d
node-problem-detector-p4xz2                               1/1       Running            1          15d
node-problem-detector-pxn4m                               1/1       Running            0          15d
node-problem-detector-ssfcg                               1/1       Running            1          15d

```

```
$ kubectl -n kube-system logs node-problem-detector-dnmgs
failed to open log file "/var/log/pods/3a2cb62d-a166-11e9-aedd-fa163e147b6e/node-problem-detector/272.log": open /var/log/pods/3a2cb62d-a166-11e9-aedd-fa163e147b6e/node-problem-detector/272.log: no such file or directory

```

kubelet log:
```
W0723 06:38:46.927150    4484 docker_container.go:216] Cannot create symbolic link because container log file doesn't exist!
E0723 06:38:46.927309    4484 remote_runtime.go:209] StartContainer "00d684802ab283cd2888b55fd484897f10c3a9e37cc574afa78a2de12abb3b0c" from runtime service failed: rpc error: code = Unknown desc = failed to start container "00d684802ab283cd2888b55fd484897f10c3a9e37cc574afa78a2de12abb3b0c": Error response from daemon: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists
E0723 06:38:46.927404    4484 kuberuntime_manager.go:733] container start failed: RunContainerError: failed to start container "00d684802ab283cd2888b55fd484897f10c3a9e37cc574afa78a2de12abb3b0c": Error response from daemon: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists
E0723 06:38:46.927462    4484 pod_workers.go:186] Error syncing pod 3a2cb62d-a166-11e9-aedd-fa163e147b6e ("node-problem-detector-dnmgs_kube-system(3a2cb62d-a166-11e9-aedd-fa163e147b6e)"), skipping: failed to "StartContainer" for "node-problem-detector" with RunContainerError: "failed to start container \"00d684802ab283cd2888b55fd484897f10c3a9e37cc574afa78a2de12abb3b0c\": Error response from daemon: error while creating mount source path '/etc/localtime': mkdir /etc/localtime: file exists"
E0723 06:39:01.444861    4484 pod_workers.go:186] Error syncing pod 3a2cb62d-a166-11e9-aedd-fa163e147b6e ("node-problem-detector-dnmgs_kube-system(3a2cb62d-a166-11e9-aedd-fa163e147b6e)"), skipping: failed to "StartContainer" for "node-problem-detector" with CrashLoopBackOff: "Back-off 40s restarting failed container=node-problem-detector pod=node-problem-detector-dnmgs_kube-system(3a2cb62d-a166-11e9-aedd-fa163e147b6e)"


```

**daemonset.yaml:**
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: node-problem-detector
  name: node-problem-detector
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      containers:
      - command:
        - /node-problem-detector
        - --logtostderr
        - --system-log-monitors=/config/kernel-monitor.json
        - --custom-plugin-monitors=/config/network-problem-monitor.json
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: hub.c.163.com/combk8s/node-problem-detector:v0.6.3-1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: 20256
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: node-problem-detector
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: log
          readOnly: true
        - mountPath: /dev/kmsg
          name: kmsg
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /config
          name: config
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: node-problem-detector
      serviceAccountName: node-problem-detector
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log/
          type: ""
        name: log
      - hostPath:
          path: /dev/kmsg
          type: ""
        name: kmsg
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - configMap:
          defaultMode: 365
          items:
          - key: kernel-monitor.json
            path: kernel-monitor.json
          - key: docker-monitor-filelog.json
            path: docker-monitor-filelog.json
          - key: kernel-monitor-filelog.json
            path: kernel-monitor-filelog.json
          - key: network-problem-monitor.json
            path: network-problem-monitor.json
          - key: network_problem.sh
            path: network_problem.sh
          name: node-problem-detector-config
        name: config
  templateGeneration: 1
```

**What you expected to happen**:

pod should be in running state.

**How to reproduce it (as minimally and precisely as possible)**:

Perhaps our operator reboot this node. I don't know how to reproduce it.

**Anything else we need to know?**:

**Environment**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

$ uname -a
Linux   4.9.65 #1 SMP Thu Jul 11 17:32:39 CST 2019 x86_64 GNU/Linux

$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
