### ISSUE TITLE
kubeadm can't join control plane using JoinConfiguration

### ISSUE THREAD

**Issue by JrCs** [kubernetes/kubernetes#80582]
I can't create (join) a new control plane node to a cluster using a JoinConfiguration file (with ControlPlane informations in it).

**What happened**:
I'm using this JoinConfiguration:
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "10.0.0.1:6443"
    token: "3a08jv.c0izixklcxtmnze7"
    unsafeSkipCAVerification: true
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "external"
ControlPlane:
  localAPIEndpoint:
    advertiseAddress: "10.0.0.2"
    bindPort: 6443
  certificateKey: "e6a2eb8381237ab72a4fa94f30285ec12a9694d750b9785706a83bfcbbbd2204"
```
and try to join the cluster with the command
```shell
kubeadm join --config=join-config.yaml

[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet-start] Downloading configuration for the kubelet from the "kubelet-config-1.15" ConfigMap in the kube-system namespace
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Activating the kubelet service
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...

This node has joined the cluster:
* Certificate signing request was sent to apiserver and a response was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the control-plane to see this node join the cluster.

```
**What you expected to happen**:
I expected to have a new **control plane** node configured but kubeadm only configure a **worker** node (not a control plane node)

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.0
- Cloud provider or hardware configuration: external (openstack)
- OS (e.g: `cat /etc/os-release`): Container Linux by CoreOS 2023.4.0 (Rhyolite)
- Kernel (e.g. `uname -a`): 4.19.23-coreos-r1
- Install tools: kubeadm 1.15.0

@kubernetes/sig/cluster-lifecycle-bugs
