### ISSUE TITLE
Incomplete `details.causes` When Creating Invalid Custom Resource 

### ISSUE THREAD

**Issue by alecmerdler** [kubernetes/kubernetes#80718]
**What happened**:

When attempting to create an instance of a custom resource which fails to meet the requirements in the CRD's `spec.validation` (like missing required field), receive an incomplete response error object:
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Test.example.coreos.com \"example\" is invalid: []: Invalid value: map[string]interface {}{\"apiVersion\":\"example.coreos.com/v1\", \"kind\":\"Test\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-07-29T15:27:59Z\", \"generation\":1, \"name\":\"example\", \"namespace\":\"test-sajzi\", \"uid\":\"7294f624-b215-11e9-80b9-8e07407f4319\"}, \"spec\":map[string]interface {}{}}: validation failure list:\nspec.password in body is required",
  "reason": "Invalid",
  "details": {
    "name": "example",
    "group": "test.tectonic.com",
    "kind": "App",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "Invalid value: map[string]interface {}{\"apiVersion\":\"test.tectonic.com/v1\", \"kind\":\"App\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-07-29T15:27:59Z\", \"generation\":1, \"name\":\"example\", \"namespace\":\"test-sajzi\", \"uid\":\"7294f624-b215-11e9-80b9-8e07407f4319\"}, \"spec\":map[string]interface {}{}}: validation failure list:\nspec.password in body is required",
        "field": "[]"
      }
    ]
  },
  "code": 422
}
```
Notice `"field": "[]"` in `causes`. This should be `spec.password`.

**What you expected to happen**:

Error response contains correct `details.causes` fields. Below is the response from a bad `Pod` creation attempt:
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Pod \"example\" is invalid: spec.containers[0].ports[0].containerPort: Required value",
  "reason": "Invalid",
  "details": {
    "name": "example",
    "kind": "Pod",
    "causes": [
      {
        "reason": "FieldValueRequired",
        "message": "Required value",
        "field": "spec.containers[0].ports[0].containerPort"
      }
    ]
  },
  "code": 422
}
```
Notice that `field` is correct in `causes` here.

**How to reproduce it (as minimally and precisely as possible)**:

Create CRD with a required field:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tests.example.coreos.com
spec: 
  group: example.coreos.com
  version: v1
  names:
    kind: Test
    listKind: Tests
    plural: tests
    singular: test
  validation:
    openAPIV3Schema:
      properties:
        spec:
          maximum: 4
          minimum: 2
          type: integer
```
Attempt to create invalid instance of custom resource (missing required field) using HTTP API and inspect response object:
```yaml
apiVersion: example.coreos.com/v1
kind: Test
spec: {}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: **Digital Ocean Kubernetes**
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): n/a
- Others: n/a
