### ISSUE TITLE
Failed to update stats for container "/system.slice/kubelet.service" - coreos

### ISSUE THREAD

**Issue by cann0nf0dder** [kubernetes/kubernetes#80807]
**What happened**:

There's a lot of errors in the logs (one each minute):
```
Jul 31 10:18:30 kubelet-wrapper[110562]: W0731 10:18:30.338623  110562 container.go:523] Failed to update stats for container "/system.slice/kubelet.service": stat failed on  with error: no such file or directory, continuing to push stats
Jul 31 10:19:39 kubelet-wrapper[110562]: W0731 10:19:39.809025  110562 container.go:523] Failed to update stats for container "/system.slice/kubelet.service": stat failed on  with error: no such file or directory, continuing to push stats
Jul 31 10:20:46  kubelet-wrapper[110562]: W0731 10:20:46.599710  110562 container.go:523] Failed to update stats for container "/system.slice/kubelet.service": stat failed on  with error: no such file or directory, continuing to push stats
```

**Anything else we need to know?**:
Related to #63804, #56850, looks like it should have been fixed in the past but it's not?

**Environment**:
- Kubernetes version (use `kubectl version`):

Some clusters on K8S 1.13.7 & some on 1.14.4

```
[root@atl1vmtk8sb5n001 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:46:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
OS:
```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2135.5.0
VERSION_ID=2135.5.0
BUILD_ID=2019-07-01-1959
PRETTY_NAME="Container Linux by CoreOS 2135.5.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
Linux atl1vmtk8sb5n001 4.19.50-coreos-r1 #1 SMP Mon Jul 1 19:07:03 -00 2019 x86_64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz GenuineIntel GNU/Linux

```
I believe both kubelet and docker running cgroups driver cgroupfs, unless we should be running systemd? 

`kubelet-wrapper[814]: I0709 21:54:03.567571     814 docker_service.go:269] Setting cgroupDriver to cgroupfs`

**Comment by mattjmcnaughton** [comment]
Can you post the command line arguments with which you are running `kubelet`?

**Comment by cann0nf0dder** [comment]
@mattjmcnaughton here it is, thanks!
```
ExecStart=/usr/lib/coreos/kubelet-wrapper \
  --config=/etc/kubernetes/config/kubelet.yaml \
  --cni-conf-dir=/etc/cni/net.d \
  --exit-on-lock-contention \
  --kubeconfig=/etc/kubernetes/kubeconfig \
  --lock-file=/var/run/lock/kubelet.lock \
  --network-plugin=cni
```
kubelet.yaml:
```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
  webhook:
    enabled: false
    cacheTTL: 2m0s
  anonymous:
    enabled: false
authorization:
  mode: AlwaysAllow
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
clusterDomain: cluster.local
clusterDNS:
- 10.3.0.10
staticPodPath: "/etc/kubernetes/manifests"
imageGCLowThresholdPercent: 50
imageGCHighThresholdPercent: 70
readOnlyPort: 10255
```
