### ISSUE TITLE
Cannot change containerPort with server side apply

### ISSUE THREAD

**Issue by felixfbecker** [kubernetes/kubernetes#80914]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

I use `kubectl apply -f` to deploy this deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: pskubectltest
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: strm/helloworld-http@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
```

Next, I use a server-side apply with `fieldManager=kubectl` to change the `containerPort` from `80` to `8080`:

```http
PATCH https://192.168.99.100:8443/apis/apps/v1/namespaces/pskubectltest/deployments/hello-world?fieldManager=kubectl
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: pskubectltest
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: strm/helloworld-http@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # this is changed from 80
              protocol: TCP
              name: http
```

I would expect this to succeed, as the port should be keyed by the name, and therefor the containerPort updated.

Instead, this fails with `Invalid: Deployment.apps "hello-world" is invalid: spec.template.spec.containers[0].ports[1].name: Duplicate value: "http"`

Meanwhile, applying this modified deployment with `kubectl apply` (with client side apply) works just fine.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.7", GitCommit:"b6001a5d99c235723fc19342d347eee4394f2005", GitTreeState:"clean", BuildDate:"2019-06-24T19:37:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

- Cloud provider or hardware configuration: Minikube
- OS (e.g: `cat /etc/os-release`): macOS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
