### ISSUE TITLE
Provide documentation on autoscaling memory metric

### ISSUE THREAD

**Issue by vkuznet** [kubernetes/kubernetes#80963]
**What would you like to be added**:
I'm trying to understand how memory metric is used for autoscaling. So far I found no documentation on this subject. In particular, the `staging/src/k8s.io/api/autoscaling/v2beta2` codebase mentions memory metric for autoscaling along with CPU but does not provide any details how it is calculated. It would be nice if such documentation will be provided. 

**Why is this needed**:
For instance, I created the following spec
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: myapp
```
and successfully deployed it to k8s. But when I check the hpa status I see currentAverageUtilization is 39 on my pod (I think it is percentage). But if I login to the pod I see that it is almost idle, i.e. the MEM from top or ps commands show all zeros. Therefore I am puzzled how memory usage is calculated.

**Comment by zouyee** [comment]
https://github.com/kubernetes-incubator/metrics-server

**Comment by oxddr** [comment]
/sig autoscaling
/remove-sig scalability

scalability != autoscaling :)

**Comment by mumutu66** [comment]
similar problem  want to know how `currentAverageUtilization ` calculated .  I got a weired value when change `heapster`  to `prometheus-k8s-adapter `  on only one HPA 

```
68-callback-core-service-test   callback-consumer-a7aff-api-hpa         Deployment/callback-consumer-a7aff         -246124544%/100%, 0%/400%      1         1         1          15d


```

```

Name:                                                     callback-consumer-a7aff-api-hpa
Namespace:                                                68-callback-core-service-test
Labels:                                                   <none>
Annotations:                                              <none>
CreationTimestamp:                                        Sat, 12 Oct 2019 16:16:58 +0800
Reference:                                                Deployment/callback-consumer-a7aff
Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):  -246124544% (856358912) / 100%
  resource cpu on pods  (as a percentage of request):     0% (3m) / 400%
Min replicas:                                             1
Max replicas:                                             1
Deployment pods:                                          1 current / 1 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  the last scale time was sufficiently old as to warrant a new scale
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas    the desired replica count is more than the maximum replica count
Events:           <none>


```

since the memory value is valid from prometheus

```

kubectl get --raw "/apis/metrics.k8s.io/v1beta1/namespaces/68-callback-core-service-test/pods?labelSelector=choerodon.io%2Frelease%3Dcallback-consumer-a7aff" |jq
{
  "kind": "PodMetricsList",
  "apiVersion": "metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/metrics.k8s.io/v1beta1/namespaces/68-callback-core-service-test/pods"
  },
  "items": [
    {
      "metadata": {
        "name": "callback-consumer-a7aff-645b94469f-hlzfv",
        "namespace": "68-callback-core-service-test",
        "selfLink": "/apis/metrics.k8s.io/v1beta1/namespaces/68-callback-core-service-test/pods/callback-consumer-a7aff-645b94469f-hlzfv",
        "creationTimestamp": "2019-10-28T03:59:36Z"
      },
      "timestamp": "2019-10-28T03:59:36Z",
      "window": "2m0s",
      "containers": [
        {
          "name": "",
          "usage": {
            "cpu": "3m",
            "memory": "836280Ki"
          }
        }
      ]
    }
  ]
}


```
and the resource is valid 

```
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 512m

```

I don't know if this is a kind of bug ..

**Comment by dinvlad** [comment]
It seems that GCP [docs](https://cloud.google.com/kubernetes-engine/docs/how-to/horizontal-pod-autoscaling) document this as such:
```yaml
- type: Resource
    resource:
      name: memory
      targetAverageValue: 100Mi
```
which is much more preferable over %, imo.
