### ISSUE TITLE
0/x nodes are available: 1 node(s) had volume node affinity conflict

### ISSUE THREAD

**Issue by berk-can** [kubernetes/kubernetes#81020]
I have a pv, a pvc and a pod which mounts pv, it gives my error while creating pod
0/5 nodes are available: 1 node(s) had volume node affinity conflict, 4 node(s) didn't match node selector

my pv:
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gamelanguage-log-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: "/backoffice-logs/gamelanguage-svc"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node4
```

my pvc:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gamelanguage-log-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
```

and my pod:
```
kind: Pod
apiVersion: v1
metadata:
  name: gamelanguage-svc
  labels:
    role: gamelanguage-svc
    environment: test
spec:
  volumes:
    - name: gamelanguage-log-storage
      persistentVolumeClaim:
        claimName: gamelanguage-log-pvc
  containers:
    - name: gamelanguage-svc
      image: ubuntu
      command: ["/bin/bash", "-ec", "do stuff"]
      volumeMounts:
        - mountPath: "/logs/gamelanguage-svc"
          name: gamelanguage-log-storage
  restartPolicy: Never
  nodeSelector:
    "kubernetes.io/hostname": node2
```

I am using manual StorageClass and I have cluster created by kubespray on 5 ubuntu machines, what might be the reason?
I've read answers about setting different zones might be the problem but I am not using GKE or AWS so I dont think I've problem about region
