### ISSUE TITLE
Enabling PodSecurityPolicy triggers OS Signals to volume mounts

### ISSUE THREAD

**Issue by latchmihay** [kubernetes/kubernetes#81025]
**What happened**:
When I have PodSecurityPolicy enabled on my Kube 1.14.x cluster, the mounted volume constantly gets CHMOD signal.

**What you expected to happen**:
When PodSecurityPolicy is not enabled, there is no such behavior as described above. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable PodSecurityPolicy on apiserver
Edit `/etc/kubernetes/manifests/kube-apiserver.yaml` and add 
```    - --enable-admission-plugins=DenyEscalatingExec,NamespaceLifecycle,ServiceAccount,PodSecurityPolicy```
2. Apply PSP
```
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  name: restricted
spec:
  allowPrivilegeEscalation: false
  forbiddenSysctls:
  - '*'
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
```

3. Start pod with a mount
```
      volumes:
        - name: config-volume
          configMap:
            name: botkube-configmap
```
```
          volumeMounts:
            - name: config-volume
              mountPath: "/config"
```
```
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
             drop: ["all"]
            readOnlyRootFilesystem: false
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001    
```

4. Test
I have wrote .a small go app utilizing "github.com/fsnotify/fsnotify" to help me with the troubleshooting.
[![Watch the video](https://img.youtube.com/vi/1AVzb4RVbP0/maxresdefault.jpg)](https://youtu.be/1AVzb4RVbP0)

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: On premise
- OS (e.g: `cat /etc/os-release`):
```
$ cat /etc/os-release .
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux ldkub335 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: Kubespray
