### ISSUE TITLE
Not able to change the permission of a directory mounted as subPath to use with a non-root container

### ISSUE THREAD

**Issue by rakeshvanga** [kubernetes/kubernetes#81095]
**What happened**:
Mounting an Azure file share along with subPath to mount only a particular directory under that share and changing the permissions of that mounted path (using an initContainer) for a non-root container. The non-root container is still seeing the owner as root and the owner set by initContainer. 

**What you expected to happen**:
The owner of the mounted path should be the one set by initContainer

**How to reproduce it (as minimally and precisely as possible)**:
Use a `volumeMounts` as below:
```
- name: file-share
              mountPath: /app/root
              subPath: /a/b/c /*this directory structure already exisits on the file share */
              readOnly: false
```
Use the `volumes:` as below:
```
name: file-share
          azureFile:
            secretName: secret-a
            shareName: someShare
            readOnly: false
```
Use a initContainer to your non-root container which runs alpine image and runs a command `chown -R 1001:1001 /app/root`.
The `/app/root` is the same directory which is used by the non-root directory.

**Anything else we need to know?**:

**Environment**:
On Azure Kubernetes Service.
