### ISSUE TITLE
LabelSelectorRequirement should not matched if the label key does not exist 

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#81149]
**What happened**:

We have a below config MutatingWebhookConfiguration.

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: abc-example
  namespace: ""
webhooks:
- clientConfig:
    caBundle: "xxxx"
    service: ""
    url: https://abc.example.svc.test.com:12345/mutating
  failurePolicy: Fail
  name: abc.example.svc.test.com
  namespaceSelector:
    matchExpressions:
    - key: someLabelKey
      operator: NotIn
      values:
      - "value1"
      - "value2"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: Unknown
```

After deploying to the cluster, we found the webhook did mutate pods from other namespaces. But those namespaces did not contain such label `someLabelKey`.

**What you expected to happen**:

Indeed we could add extra `Exists`,

```yaml
  namespaceSelector:
    matchExpressions:
    - key: someLabelKey
      operator: NotIn
      values:
      - "value1"
      - "value2"
    - key: someLabelKey
      operator: Exists
``` 
 or match exact key.
```yaml
  namespaceSelector:
    matchLabels:
      someLabelKey: "value3"
```

But using matchLabels is quite inconveniecent if we got multiple keys here. 

matchExpressions `NotIn` is a little bit misleading. Users need to set `Exists`, together with `NotIn`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
