### ISSUE TITLE
Taints not working as expected with policy-config-file

### ISSUE THREAD

**Issue by tingweiwu** [kubernetes/kubernetes#81155]
**What happened**:
I've added taint to one worker node
```
kubectl taint nodes node1 gpu=false:NoSchedule
```
when I create pod without tolerations it is sheduled to node1.

I have try to remove policy-config-file in kube-scheduler.yaml. the taints worker well.

```
 containers:
  - command:
    - kube-scheduler
    - --address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    #- --use-legacy-policy-config=true
    #- --policy-config-file=/etc/kubernetes/scheduler-policy-config.json

```

do i have some wrong with `scheduler-policy-config.json`? here is my `scheduler-policy-config.json`
```
{
"kind" : "Policy",
"apiVersion" : "v1",
"predicates" : [
	{"name" : "PodFitsHostPorts"},
	{"name" : "PodFitsResources"},
	{"name" : "NoDiskConflict"},
	{"name" : "NoVolumeZoneConflict"},
	{"name" : "MatchNodeSelector"},
	{"name" : "HostName"},
        {"name" : "PodToleratesNodeTaints"}
	],
"priorities" : [
        {"name" : "MostRequestedPriority", "weight" : 1},
	{"name" : "ServiceSpreadingPriority", "weight" : 1},
	{"name" : "EqualPriority", "weight" : 1},
        {"name" : "SelectorSpreadPriority", "weight" : 10},
        {"name" : "TaintTolerationPriority", "weight" : 1}
	],
"hardPodAffinitySymmetricWeight" : 10,
"alwaysCheckAllPredicates" : false
}
```
I have search previous issue #62100  but not solved with its config

**What you expected to happen**:
 pods will not be run on the node with taint, if they don't have tolerations

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.11.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

- Kernel (e.g. `uname -a`):
3.10.0-327.59.59.46.h38.x86_64 #1 SMP Mon Dec 11 19:34:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by draveness** [comment]
Thanks for raising the issue, but kubernetes 1.11 has no longer maintained by the community after 1.14 released. Please upgrade to the latest version.

**Comment by tingweiwu** [comment]
@draveness we have no plans to upgrade as it is running online. but taints works well in issue #62100  with kubernetes 1.8. where can I get help if I should running with kubernetes 1.11?

**Comment by tingweiwu** [comment]
I add `TaintTolerationPriority` and `PodToleratesNodeTaints` into `scheduler-policy-config.json`
and restart kube-scheduler pod. 
but the `scheduler-policy-config.json` in the pod didn't update as expect.

thus,solved this issue by edit the config in the pod and restart.

I don't know why it doesn't update as the config is mounted into pod

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    - --v=5
    - --use-legacy-policy-config=true
    - --policy-config-file=/etc/kubernetes/scheduler-policy-config.json
    image: k8s.gcr.io/kube-scheduler-amd64:v1.11.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/kubernetes/scheduler-policy-config.json
      name: scheduler-policy
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /etc/kubernetes/scheduler-policy-config.json
      type: FileOrCreate
    name: scheduler-policy
status: {}

```

```
