### ISSUE TITLE
Headless Service IP Problem

### ISSUE THREAD

**Issue by hollywater** [kubernetes/kubernetes#81216]
**Environment**:
- Kubernetes version: **"v1.15.1",**
- OS : **ubuntu 16.04**
- Others:
**6 machine(m1-m6) in 1VM and 1 physical machine(m0), totally 7.
m2 is k8s master node, m1 install ceph version 10.2.11  ,the others is k8s work nodes**

### 1. Follow this page to build MySQL cluster:
https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/

### 2. Result:
_**Pod: mysql0 and mysql1 go up, while Pod: mysql-2 falls down.**_

And I found that  initContainers:"**clone-mysql**" failed to copy db from mysql-1 to mysql-2, but successfully from mysql-0(master) to mysql-1.

It seems Headless service allocate wrong ip segment.

### 3.See the log in machine-m4 which run mysql-2
Ncat Connection refused
```
[root@m4(10.2.31.85):var]$ cd /var/log/pods/mysql-ns_mysql-2_b97caaa2-3ac8-41df-bd4f-ec5a850f3fb5/clone-mysql
[root@m4(10.2.31.85):clone-mysql]$ vim 25.log 


{"log":"+ [[ -d /var/lib/mysql/mysql ]]\n","stream":"stderr","time":"2019-08-09T07:25:46.418707931Z"}
{"log":"++ hostname\n","stream":"stderr","time":"2019-08-09T07:25:46.418733126Z"}
{"log":"+ [[ mysql-2 =~ -([0-9]+)$ ]]\n","stream":"stderr","time":"2019-08-09T07:25:46.418736105Z"}
{"log":"+ ordinal=2\n","stream":"stderr","time":"2019-08-09T07:25:46.418737969Z"}
{"log":"+ [[ 2 -eq 0 ]]\n","stream":"stderr","time":"2019-08-09T07:25:46.418750018Z"}
{"log":"+ xbstream -x -C /var/lib/mysql\n","stream":"stderr","time":"2019-08-09T07:25:46.418751882Z"}
{"log":"+ ncat --recv-only mysql-1.mysql 3307\n","stream":"stderr","time":"2019-08-09T07:25:46.418753759Z"}
{"log":"Ncat: Connection refused.\n","stream":"stderr","time":"2019-08-09T07:25:46.42725192Z"}
{"log":"+ xtrabackup --prepare --target-dir=/var/lib/mysql\n","stream":"stderr","time":"2019-08-09T07:25:46.42727079Z"}
{"log":"xtrabackup version 2.4.4 based on MySQL server 5.7.13 Linux (x86_64) (revision id: df58cf2)\n","stream":"stderr","time":"2019-08-09T07:25:46.434620217Z"}
{"log":"xtrabackup: cd to /var/lib/mysql\n","stream":"stderr","time":"2019-08-09T07:25:46.434633767Z"}
{"log":"xtrabackup: Error: cannot open ./xtrabackup_checkpoints\n","stream":"stderr","time":"2019-08-09T07:25:46.434636059Z"}
{"log":"xtrabackup: error: xtrabackup_read_metadata()\n","stream":"stderr","time":"2019-08-09T07:25:46.434637961Z"}
{"log":"xtrabackup: This target seems not to have correct metadata...\n","stream":"stderr","time":"2019-08-09T07:25:46.434639703Z"}
{"log":"InnoDB: Number of pools: 1\n","stream":"stderr","time":"2019-08-09T07:25:46.434641487Z"}
{"log":"InnoDB: Operating system error number 2 in a file operation.\n","stream":"stderr","time":"2019-08-09T07:25:46.434643203Z"}
{"log":"InnoDB: The error means the system cannot find the path specified.\n","stream":"stderr","time":"2019-08-09T07:25:46.434644979Z"}
{"log":"xtrabackup: Warning: cannot open ./xtrabackup_logfile. will try to find.\n","stream":"stderr","time":"2019-08-09T07:25:46.434646747Z"}
{"log":"InnoDB: Operating system error number 2 in a file operation.\n","stream":"stderr","time":"2019-08-09T07:25:46.434648535Z"}
{"log":"InnoDB: The error means the system cannot find the path specified.\n","stream":"stderr","time":"2019-08-09T07:25:46.434650268Z"}
{"log":"  xtrabackup: Fatal error: cannot find ./xtrabackup_logfile.\n","stream":"stderr","time":"2019-08-09T07:25:46.434652023Z"}
{"log":"xtrabackup: Error: xtrabackup_init_temp_log() failed.\n","stream":"stderr","time":"2019-08-09T07:25:46.434653779Z"}
```

### 4.Enter  the Container xtrabackup of  Pod mysql-1 
**_Ping mysql-0 is OK_**
``` 
[root@m2(10.2.31.83):m2]$ kubectl exec -it mysql-1 -n mysql-ns --container xtrabackup -- /bin/bash
root@mysql-1:/# ping mysql-0.mysql
PING mysql-0.mysql.mysql-ns.svc.cluster.local (10.244.1.80): 56 data bytes
64 bytes from 10.244.1.80: icmp_seq=0 ttl=62 time=1.472 ms
64 bytes from 10.244.1.80: icmp_seq=1 ttl=62 time=1.160 ms
```

### 5.Enter the Container xtrabackup of  Pod mysql-0 
**_Ping mysql-1 is unreachable_**
```  
[root@m2(10.2.31.83):m2]$ kubectl exec -it mysql-0 -n mysql-ns --container xtrabackup -- /bin/bash 

root@mysql-0:/# ping mysql-1.mysql
PING mysql-1.mysql.mysql-ns.svc.cluster.local (172.17.0.2): 56 data bytes
92 bytes from 172.17.0.1: Destination Host Unreachable
92 bytes from 172.17.0.1: Destination Host Unreachable`
```

### 6.Cannot  enter Pod mysql-2 
Because it failed in 'clone-mysql' part, and  container 'init-mysql' terminate ,  container 'clone-mysql' is  'Waiting' with Reason of 'CrashLoopBackOff' for a longlong time.

### 7.See headless service describe:
``` 
[root@m2(10.2.31.83):m2]$ kubectl describe svc mysql -n mysql-ns
Name:              mysql
Namespace:         mysql-ns
Labels:            app=mysql
Annotations:       <none>
Selector:          app=mysql
Type:              ClusterIP
IP:                None
Port:              mysql  3306/TCP
TargetPort:        3306/TCP
Endpoints:         10.244.1.80:3306,172.17.0.2:3306
Session Affinity:  None`
```

### 8. My yaml:
``` 
#1.命名空间
apiVersion: v1
kind: Namespace
metadata:
  name: mysql-ns
---
#2. ceph rbd secret
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: mysql-ns
data:
  key: QVFCcDVrZGR5UFFmRmhBQXpoTzdkcWI4QmZOTnZ3VU9SeFNtZ3c9PQo=
---
#3.pv/pvc定义
#3.1 master
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-mysql-0
  namespace: mysql-ns
  labels:
    pv: db-mysql-0
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  rbd: 
    monitors: 
      - 10.2.31.81:6789
    pool: rbd
    image: mysql-master
    user: admin
    fsType: ext4
    readOnly: false
    secretRef:
      name: ceph-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-0
  namespace: mysql-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: db-mysql-0
---

#3.2 slave1
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-mysql-1
  namespace: mysql-ns
  labels:
    pv: db-mysql-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  rbd:
    monitors:
      - 10.2.31.81:6789
    pool: rbd
    image: mysql-slave1
    user: admin
    fsType: ext4
    readOnly: false
    secretRef:
      name: ceph-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-1
  namespace: mysql-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: db-mysql-1
---

#3.3 slave2
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-mysql-2
  namespace: mysql-ns
  labels:
    pv: db-mysql-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  rbd:
    monitors:
      - 10.2.31.81:6789
    pool: rbd
    image: mysql-slave2
    user: admin
    fsType: ext4
    readOnly: false
    secretRef:
      name: ceph-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-2
  namespace: mysql-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: db-mysql-2
---
#4.service定义
#4.1 master
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql
---
#4.2 slave
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
---
#5. 创建mysql（一主两备，备只读）
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: mysql-ns
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql-ns
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers: 
      - name: init-mysql
        image: mysql:5.7
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Generate mysql server-id from pod ordinal index.
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          echo [mysqld] > /mnt/conf.d/server-id.cnf
          # Add an offset to avoid reserved server-id=0 value.
          echo server-id=$((100 + $ordinal)) >> /mnt/conf.d/server-id.cnf
          # Copy appropriate conf.d files from config-map to emptyDir.
          if [[ $ordinal -eq 0 ]]; then
            cp /mnt/config-map/master.cnf /mnt/conf.d/
          else
            cp /mnt/config-map/slave.cnf /mnt/conf.d/
          fi
        volumeMounts:
        - name: conf
          mountPath: /mnt/conf.d
        - name: config-map
          mountPath: /mnt/config-map
      - name: clone-mysql
        image: gcr.io/google-samples/xtrabackup:1.0
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Skip the clone if data already exists.
          [[ -d /var/lib/mysql/mysql ]] && exit 0
          # Skip the clone on master (ordinal index 0).
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          [[ $ordinal -eq 0 ]] && exit 0
          # Clone data from previous peer.
          ncat --recv-only mysql-$(($ordinal-1)).mysql 3307 | xbstream -x -C /var/lib/mysql
          # Prepare the backup.
          xtrabackup --prepare --target-dir=/var/lib/mysql
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 10
      - name: xtrabackup
        image: gcr.io/google-samples/xtrabackup:1.0
        ports:
        - name: xtrabackup	  
          containerPort: 3307
        command:
        - bash
        - "-c"
        - |
          set -ex
          cd /var/lib/mysql

          # Determine binlog position of cloned data, if any.
          if [[ -f xtrabackup_slave_info && "x$(<xtrabackup_slave_info)" != "x" ]]; then
            # XtraBackup already generated a partial "CHANGE MASTER TO" query
            # because we're cloning from an existing slave. (Need to remove the tailing semicolon!)
            cat xtrabackup_slave_info | sed -E 's/;$//g' > change_master_to.sql.in
            # Ignore xtrabackup_binlog_info in this case (it's useless).
            rm -f xtrabackup_slave_info xtrabackup_binlog_info
          elif [[ -f xtrabackup_binlog_info ]]; then
            # We're cloning directly from master. Parse binlog position.
            [[ `cat xtrabackup_binlog_info` =~ ^(.*?)[[:space:]]+(.*?)$ ]] || exit 1
            rm -f xtrabackup_binlog_info xtrabackup_slave_info
            echo "CHANGE MASTER TO MASTER_LOG_FILE='${BASH_REMATCH[1]}',\
                  MASTER_LOG_POS=${BASH_REMATCH[2]}" > change_master_to.sql.in
          fi

          # Check if we need to complete a clone by starting replication.
          if [[ -f change_master_to.sql.in ]]; then
            echo "Waiting for mysqld to be ready (accepting connections)"
            until mysql -h 127.0.0.1 -e "SELECT 1"; do sleep 1; done

            echo "Initializing replication from clone position"
            mysql -h 127.0.0.1 \
                  -e "$(<change_master_to.sql.in), \
                          MASTER_HOST='mysql-0.mysql', \
                          MASTER_USER='root', \
                          MASTER_PASSWORD='', \
                          MASTER_CONNECT_RETRY=10; \
                        START SLAVE;" || exit 1
            # In case of container restart, attempt this at-most-once.
            mv change_master_to.sql.in change_master_to.sql.orig
          fi

          # Start a server to send backups when requested by peers.
          exec ncat --listen --keep-open --send-only --max-conns=1 3307 -c \
            "xtrabackup --backup --slave-info --stream=xbstream --host=127.0.0.1 --user=root"
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: mysql
  volumeClaimTemplates:
  - metadata:
      name: db
      namespace: mysql-ns
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
#6. 定义HPA，是的mysql集群可以弹性伸缩
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mysql-as
  namespace: mysql-ns
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mysql
  targetCPUUtilizationPercentage: 80
```

### 9. I have to change clone-db always from mysql-0
And success. 
```
          # Clone data from previous peer.
          ncat --recv-only mysql-0.mysql 3307 | xbstream -x -C /var/lib/mysql
```

But why? **Is that A BUG?** Or something wrong?

```
[root@m2(10.2.31.83):mysql]$ kubectl get po -n mysql-ns
NAME      READY   STATUS    RESTARTS   AGE
mysql-0   2/2     Running   0          2m48s
mysql-1   2/2     Running   0          2m3s
mysql-2   2/2     Running   0          71s
```

@kubernetes/sig-node-bugs
