### ISSUE TITLE
Service Continues Forwarding to Old Nodes after Selector Patched

### ISSUE THREAD

**Issue by Kent-H** [kubernetes/kubernetes#81225]
**What I did**: 
Patched the spec.selector field of a service, using:
```
kubectl patch svc "$SERVICE" --type=json --patch='[{"op": "replace", "path": "/spec/selector", "value":{"proxy":"unique-tag"}}]'
```

**What happened**:
The service continues to forward new tcp connections to previously selected pods, no traffic is sent to newly selected pods.

**What you expected to happen**:
After patching the spec.selector field, service should forward new tcp connections to newly selected pods.

**How to reproduce**:
1. Create a service that directs traffic to a pod.
1. Patch the service's spec.selector so that it should forward to a different pod.
1. Attempt to use the service, and see which pod receives the traffic.

For reference, the service I was attempting to patch:
```
apiVersion: v1
kind: Service
metadata:
  name: voltha-api
  serviceAccountName: {{ .Values.serviceaccount }}
spec:
  serviceAccountName: {{ .Values.serviceaccount }}
  ports:
    - name: grpc
      port: 55555
      targetPort: 55555
  selector:
    app: voltha-api-server
```

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:41:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: kind(k8s-in-docker) cluster
- OS: MacOS Mojave
- Kernel: Darwin ONM-KHAGERMA-01 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
