### ISSUE TITLE
Pod with a volume used only in initContainers can't start

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#81343]
**What happened**:
This dummy pod uses a volume only in `initContainer` and the pod does not start:

```
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    name: test
spec:
  initContainers:
    - image: gcr.io/google_containers/busybox
      command:
        - "date"
      name: busybox-init
      volumeMounts:
        - name: vol
          mountPath: /mnt/test
  containers:
    - image: gcr.io/google_containers/busybox
      command:
        - "/bin/sleep"
        - "99999"
      name: busybox
  volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: myclaim
```

Kubelet emits event `Error: cannot find volume "vol" to mount into container "busybox-init"` and the pod enters `Init:CreateContainerConfigError` status.

**What you expected to happen**:
The pod starts

**Anything else we need to know?**:
VolumeManager / DesiredStateOfWorldPopulator observes only `pod.spec.containers` and not `.initContainers`:
https://github.com/kubernetes/kubernetes/blob/ac2295a24d3a8087a1129ff832a42b0ad74f94fc/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L631-L651

Found during review of  https://github.com/kubernetes/kubernetes/pull/81163

**Environment**:
- Kubernetes version (use `kubectl version`): today's master, ac2295a24d3a8087a1129ff832a42b0ad74f94fc

/sig storage
/priority important-soon
/assign
