### ISSUE TITLE
Restrict service account token usage to CIDR IP range

### ISSUE THREAD

**Issue by atheiman** [kubernetes/kubernetes#81362]
**What would you like to be added**: I'd like to restrict service account token usage to certain IP ranges.

**Why is this needed**: We use a cluster-admin token for GitLab to integrate with Kubernetes (deploys resources to cluster, views pod logs, displays resources in namespaces). Unfortunately GitLab allows this token to be retrieved from the GitLab UI and then the token can be used from anywhere. If we could annotate a service account to say only allow token usage from a specified cidr range, that would prevent this vulnerability.

For example, this service account would only allow usage of its token from `32.23.45.54/32`, and `67.76.89.98/32`

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/restrict-token-cidr: 32.23.45.54/32,67.76.89.98/32
  name: gitlab-integration
```
