### ISSUE TITLE
Absent root element type will fail CRD publishing

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#81445]
/kind bug
/sig api-machinery
/area custom-resources

for now CRD validation allows `.spec.validation.openAPIV3Schema.type` to be either empty/unspecified or an "object" type. and openapi publishing will be failing in the former case, it will be published as unstructral regardless of all the specified openapi properties. not sure why the validation allows empty root type in the first place, but we can at least make the publishing working w/ either empty or "object" b/c they don't really make a difference..

@liggitt @roycaihw @sttts 

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object  # crd validation allows absent root element type
      properties:
        spec:
          type: object
          properties:
            cronSpec:
              type: string
            image:
              type: string
            replicas:
              type: integer
```

**Comment by liggitt** [comment]
only schemas that fully specify types will publish openapi (see [structural schemas](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190425-structural-openapi.md)). v1 CRDs will require structural schemas (see https://github.com/kubernetes/kubernetes/pull/79604).

/close

**Comment by yue9944882** [comment]
> only schemas that fully specify types will publish openapi (see structural schemas).

if that's the expected behavior, the CRD validation should forbid non-empty `properties` fields on empty type at root, is it? for now, users from kubebuilder will be using generated yaml in that form, and they will be hitting this issue when publishing.

**Comment by liggitt** [comment]
by "fully specified types", I mean "specify a type for every property, including the root". validation will require that in v1, but we cannot tighten validation in v1beta1.

the schema in the description would not pass validation if the top-level type attribute was removed:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      # type: object  # crd validation allows absent root element type
      properties:
        spec:
          type: object
          properties:
            cronSpec:
              type: string
            image:
              type: string
            replicas:
              type: integer
```
produces:
```
The CustomResourceDefinition "crontabs.stable.example.com" is invalid: spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root
```

/close
