### ISSUE TITLE
Containers startup is blocked by postStart lifecycle hook

### ISSUE THREAD

**Issue by monester** [kubernetes/kubernetes#81450]
**What happened**:

Containers startup is blocked by postStart lifecycle hook.

**What you expected to happen**:

All containers starting asynchronously.

**How to reproduce it (as minimally and precisely as possible)**:

This pod would never reach `running` state

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "apt update; apt install -y netcat; while ! nc -z localhost 80; do sleep 1; done"]
    command: ['sh', '-c', 'sleep 6600']
  - name: nginx
    image: nginx
```

**Anything else we need to know?**:

In documentation on page https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution  said that "Hook handler calls are synchronous". I assume it means that container isn't going to running state until hook completes. There is no mentioning that when there is postStart hooks all containers are starting synchronously.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.5
- Cloud provider or hardware configuration: private cloud
- OS (e.g: `cat /etc/os-release`): Fedora release 30 (Thirty)
- Kernel (e.g. `uname -a`):  5.1.20-300.fc30.x86_64
- Install tools: rancher-2.2
- Network plugin and version (if this is a network-related bug): calico

**Related issues**:

#37805
#59161

Initial issue to workaroud this behaviour in application:
helm/charts#16201
