### ISSUE TITLE
pod priority is different the office article

### ISSUE THREAD

**Issue by mingzhuyang** [kubernetes/kubernetes#81596]
i use kubernetes version 1.15， i am trying pod priority,but i found same question.
1.I created a globalDefault priority A, but the pod I created that does not display the declaration priorityClassName does not use priority A.

This is different [priorityclass](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass)

2. I defined a pod that references a priorityClassName that does not exist. I actually succeeded when I executed the create command to create a pod. The official documentation shows that the api server should reject the request.

This is different [pod-priority](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#pod-priority)

**Comment by mingzhuyang** [comment]
up

**Comment by k82cn** [comment]
/sig scheduling

@mingzhuyang , would you share related log & yaml file?

**Comment by mingzhuyang** [comment]
```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: secondary-service-priority
value: 100000
globalDefault: true
preemptionPolicy: Never
 
description: "This priority class should be used for secondary service pods only."
```

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
```
but nginx pod not PriorityClass 

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: high-priority
```
i not have  high-priority  ,but i create nginx-2 success
