### ISSUE TITLE
AWS NLB service doesn't remove Security Group rules on delete

### ISSUE THREAD

**Issue by gmorse-gd** [kubernetes/kubernetes#81610]
**What happened**: 
Created a service with k8s v1.12 with NLB annotation and loadBalancerSourceRanges, then deleted it. The security group rules created for the NLB didn't get deleted.

**What you expected to happen**:
The Security group rules for NLB should have been removed. (I don't see any errors in the kubernetes-controller-manager log)

**How to reproduce it (as minimally and precisely as possible)**:
Create a new service

```yaml
kind: Service
apiVersion: v1
metadata:
  name: nginx-nlb
  namespace: testing
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
  - 8.8.8.8/32
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app: nginx-test
```

Then delete the service.

**Anything else we need to know?**:
I don't see any lower level logs in relation to deleting ingress rules.
Seems like this fix didn't fully work maybe?:
ref:
Old Issue: https://github.com/kubernetes/kubernetes/issues/57568
Old pr: https://github.com/kubernetes/kubernetes/pull/57569

**Environment**:
- Kubernetes version: v1.12.10-eks-2e569f
- Cloud provider or hardware configuration: AWS
