### ISSUE TITLE
There seems to be no way of setting permissions on the mount path

### ISSUE THREAD

**Issue by jeffsaremi** [kubernetes/kubernetes#81676]
I have posted this to StackOverflow (https://stackoverflow.com/questions/57566773/how-to-change-the-umask-when-mounting-volumes-in-kubernetes-pods) however, I think there is something missing in the design and as such it should be posted here.

I have tried this in Kubernetes 1.5
Given a `SecurityContext` for a pod, a volume to mount and a nested path as the mount point one can clearly see that the intermediate folders in the mount path are left to their own devices as far as permissions are concerned. Allow me to demonstrate:

```
pod security context:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000

volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/storage/mount/demo

volumes:
  - name: sec-ctx-vol
    emptyDir: {}
```
Resulting folder permissions:
```
$kubectl exec perm-demo -n play -- ls -lR /data
/data:
total 4
drwxr-xr-x    3 root     root          4096 Aug 20 17:45 storage

/data/storage:
total 4
drwxr-xr-x    3 root     root          4096 Aug 20 17:45 mount

/data/storage/mount:
total 4
drwxrwsrwx    2 root     2000          4096 Aug 20 17:45 demo

/data/storage/mount/demo:
total 0
```
As you can see other than the final folder (demo) all other folders are still owned by root:root in a way that my pod/container user will have no write permissions to them.

So if my pod/container user were to say create a folder like `/data/storage/folder2` this would fail since neither `runAsGroup` nor `root` groups have any kind of write permissions to that path!

**Comment by jeffsaremi** [comment]
There seems to be at least one way to avoid this problem.

I went back to the same spec and this time added a top-level mount point as well as a deeper one.
Now all the intermediate folders got their permissions from the desirable top one:

pod.yaml (checkout data2 and where it's mounted):
```
apiVersion: v1
kind: Pod
metadata:
  name: perm-pod
  namespace: play
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
    fsGroup: 2000
  containers:
  - name: permtest
    image: ubuntu:16.04
    command: [ 'sh', '-c', 'sleep 1h' ]
    volumeMounts:
    - name: data2
      mountPath: /data
    - name: data
      mountPath: /data/storage/sample/one
  volumes:
  - name: data
    emptyDir: {}
  - name: data2
    emptyDir: {}
```

After applying and running a query I get:
```
$ kubectl exec perm-pod -n play -- sh -c " ls -ld /data; ls -lR /data"
drwxrwsrwx 3 root 2000 4096 Aug 22 01:59 /data
/data:
total 4
drwxr-sr-x 3 root 2000 4096 Aug 22 01:59 storage

/data/storage:
total 4
drwxr-sr-x 3 root 2000 4096 Aug 22 01:59 sample

/data/storage/sample:
total 4
drwxrwsrwx 2 root 2000 4096 Aug 22 01:59 one

/data/storage/sample/one:
total 0
```

As you can see the "storage" and "sample" also got their permissions inherited from the top-most level (/data)
