### ISSUE TITLE
Restart For Containers With Liveness Probing Failure

### ISSUE THREAD

**Issue by fengyu10** [kubernetes/kubernetes#81713]
**What happened**:
When a new pod creates a new container that has a livenessProbe, the probe worker waits initialDelaySeconds seconds then runs the livenessProbe
The container restart behavior, time intervals are not fixed， describe pod logs is "Liveness probe failed: dial tcp 172.16.35.65:8866: i/o timeout"
But I can guarantee the pod is alive, Why this happens???

kubectl describe po logs :
![image](https://user-images.githubusercontent.com/31887880/63415175-e3734480-c42f-11e9-825c-4475053d75c1.png)

yaml as follows:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2019-08-20T07:18:16Z"
  generation: 4
  name: cnntest
  namespace: tensorflow-serving-test
spec:
  replicas: 2
  selector:
    matchLabels:
      modelname: cnntest
      taskid: "69"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        modelname: cnntest
        taskid: "69"
    spec:
      containers:
      - image: harbor.58corp.com/ailab/tensorflow-serving.hadoop:1.12.0-devel
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 1
          initialDelaySeconds: 135
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8866
          timeoutSeconds: 2
        name: cnntest
        ports:
        - containerPort: 8866
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 8866
            timeoutSeconds: 2
        resources:
          limits:
            cpu: "5"
            memory: 20Gi
          requests:
            cpu: "5"
            memory: 20Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
Four times in 50 minutes to restart behavior, place about 15 minutes, according to the yaml livenessProbe definition, once every 10 seconds will detect, if the network impassability, so a reboot behavior should be 10 seconds.Amend the failureThreshold into 3, also can appear pod restarted.
I guess it should be some point between kubelet and pod network impassability lead to check will fail three times, livenessProbe failure, leading to pod to restart.
But now I don't know how to check and solve this problem.

I try to livenessProbe tcpSocket change into the exec mode, pod restart behavior did not happen.
yaml as follows:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cnntest
  namespace: tensorflow-serving
spec:
  replicas: 0
  selector:
    matchLabels:
      modelname: cnntest
      taskid: "69"
  template:
    metadata:
      labels:
        modelname: cnntest
        username: chenxingzhen
    spec:
      containers:
      - image: harbor.58corp.com/ailab/tensorflow-serving.hadoop:1.12.0-devel-nc
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - nc -z -v 127.0.0.1 8866
          failureThreshold: 1
          initialDelaySeconds: 150
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: cnntest
        ports:
        - containerPort: 8866
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 8866
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        usage: online
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
 I have to use kubernetes v1.6.1 cluster, did not appear this kind of situation.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.2
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):Linux tjtx162-10-89.58os.org 4.18.7-1.el7.elrepo.x86_64 #1 SMP Sun Sep 9 09:02:34 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:kubeadm
- Network plugin and version (if this is a network-related bug): calico v3.8.1
- Others:
The calico ip pool segment is 192.168.0.0/16
