### ISSUE TITLE
Give the proper reason for killing pods

### ISSUE THREAD

**Issue by andreib1** [kubernetes/kubernetes#81723]
Add the reason the pod was killed, e.g. exceeded memory limit, liveness probe, readiness probe...

Kubelet outputs
"Killing container with id docker://your-example-application:Need to kill Pod"
Reason: "Killing"

This message is unhelpful when it comes to diagnosing why the pod was killed, and can be improved with the reason from Kubelet to aid debugging.

**Comment by andreib1** [comment]
@kubernetes/sig-node

**Comment by mattjmcnaughton** [comment]
Hi @andreib1 ! Thanks for posting - could you please share the version of k8s you're using?

**Comment by mattjmcnaughton** [comment]
Also, I'm looking at https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/ and wondering if something such as `kubectl get pod POD_NAME -o go-template="{{range .status.containerStatuses}}{{.lastState.terminated.message}}{{end}}"` could meet your use case.

**Comment by andreib1** [comment]
Hi, My client is currently using Kubernetes 1.12.8-gke.10

My use case is to use Stackdriver Monitoring to alert me as to pods getting terminated due to pods failing liveness/readiness, or pods exceeding memory limits.  At the moment the only application component that has that information responsibility is Kubelet.  Kubelet does output the fact that it killed a pod, but doesn't give any proper reason why it did so, just {"reason": "killing"}.  Therefore, I can't tell whether it was killed naturally due to a deployment, due to failing a constraint, or rescale etc.

It would be great if I could create some metric which describes the pods that we have assigned memory limits to, and where they have exceeded those limits.  Also good to see pods that died of unnatural causes.

**Comment by mattjmcnaughton** [comment]
On Sat, Aug 24, 2019 at 07:24:25AM -0700, Andrei wrote:
> Hi, My client is currently using Kubernetes 1.12.8-gke.10
> 
> My use case is to use Stackdriver Monitoring to alert me as to pods getting terminated due to pods failing liveness/readiness, or pods exceeding memory limits.  At the moment the only application component that has that information responsibility is Kubelet.  Kubelet does output the fact that it killed a pod, but doesn't give any proper reason why it did so, just {"reason": "killing"}.  Therefore, I can't tell whether it was killed naturally due to a deployment, due to failing a constraint, or rescale etc.
> 
> It would be great if I could create some metric which describes the pods that we have assigned memory limits to, and where they have exceeded those limits.  Also good to see pods that died of unnatural causes.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/issues/81723#issuecomment-524554073

Hmm, I am a little surprised that this type of information isn't already
available. I'm going to see if any other community members know how to access it
of the top of their heads. If no one responds in a couple of days, can you ping
me and I'll try and look into the source code.

If this info truly isn't available at all, then I'm inclined to agree with you
that it should be accessible in some form. I'd be interested for input from the
community on the best way to do that.

**Comment by andreib1** [comment]
It looks like no-one has the answer to this one.  Is there a chance you can have a look please @mattjmcnaughton ?  As you say it is surprising that I can't get this from the logs.

**Comment by andreib1** [comment]
This has gone a bit cold - does anyone have any information that I can feed back to my client?

**Comment by krmayankk** [comment]
oomkilled, liveness failed, etc are all available through kubernetes events, which is a good tool for debugging. I am not sure if they are available through kubelet logs though

**Comment by andreib1** [comment]
Thanks.  I know those events are available, and you are right, they are very useful.  When it comes to cluster monitoring though, I want to be able to see why my pods are being turned over.  Kublet knows the reason, and it generates a log to tell me it killed the pod.  But at the moment it's hiding this reason.  This should be surfaced so that I can then get a metric of pods being killed due to OOM and pods being killed for other reasons.  Surely I am not the only one who is interested in this metric.  Google Stackdriver monitoring and alerting would benefit from this as well.

**Comment by shikloshi** [comment]
+1

**Comment by DangAnhDung** [comment]
@andreib1  So can you share what is the root caurse of your case that Pod being Killed , I am interesting about this problems
Thanks you

**Comment by medsadokmtir** [comment]
+1

**Comment by tedyu** [comment]
There is already code recording related event.
e.g. in eviction_manager.go 
```
                c.recorder.Eventf(pod, v1.EventTypeWarning, events.PreemptContainer, message)
                // this is a blocking call and should only return when the pod and its containers are killed.
                err := c.killPodFunc(pod, status, nil)
```
Is the request here to add new event which records similar information ?

**Comment by medsadokmtir** [comment]
The problem is that we do not get the reason for the kill. I can see with `k get events` only killing events without the reason: 
`32m         Normal    Killing                 Pod        Killing container with id docker://containerId:Need to kill Pod`

**Comment by andreib1** [comment]
Typical causes could be OOMkilled, Rolling-update etc.

Another field with the cause of death would be great, I guess another event would work, although it would mean extra work to tie them together.

**Comment by medsadokmtir** [comment]
It is deployment in my Case with a  `replicas: 1` and according to the official doc [Example states](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#example-states), the node is only deleted when a disk dies or node is segmented out. So it could not be an OOMkilled.

**Comment by andreib1** [comment]
OK, that makes sense.  In that case where can I get the cause of death for containers by pod in a single place, including rolling updates, OOMKilled etc.

**Comment by jdomag** [comment]
Same here, pod just died and the only thing i can see in the event log is: 
"Killing container with id docker://dnsmasq:Need to kill Pod"

K8s 1.11

**Comment by blockjon** [comment]
Same problem here - we use pods to run CI jobs and many were failing yesterday with this cryptic message "Need to kill Pod" and I have no idea what the problem is or how to fix.

**Comment by dlangerenken** [comment]
same issues. no explanation to why the pod had to be killed.

**Comment by casidiablo** [comment]
This does not seem like a crazy request... in fact, it should have been an obvious feature.

Is this hard to implement or something? I bet this is something a core member can knock in a couple of hours.

**Comment by poros** [comment]
It would be nice to have this kind of information for my company, too :)

**Comment by cn-mayank** [comment]
We would also benefit a lot from this information, struggling with gke without this at the moment

**Comment by vsbus** [comment]
We are importing k8s events into BQ and would be really happy to know more details about kill reason to analyze our cluster loads at scale.

**Comment by bertreyking** [comment]
+1

**Comment by vmandale** [comment]
+1

**Comment by drzdbd1** [comment]
+1 this is a must have feature

**Comment by amirs-kov** [comment]
+1

**Comment by panicbit** [comment]
# Please don't comment "+1". Use the reaction feature instead.

**Comment by andreib1** [comment]
I have come to the conclusion that this is deemed unimportant as it has been here for over a year with no sign of remedy or workaround.

**Comment by panicbit** [comment]
If that were the case, I would expect the issue to be closed with a rationale.

**Comment by victorhugojt** [comment]
I'm doing performance testing over a microservices deployment cluster and I have the same problem. I don't know how this pods arr being killed if the CPU and memory looks ok. I am agree that more information it would be very useful.

**Comment by jeuniii** [comment]
A bunch of calico pods in my GKE cluster have been killed

```
k get events -n kube-system | grep "Stopping container calico-node"
14m         Normal    Killing             pod/calico-node-26rmv                                     Stopping container calico-node
29m         Normal    Killing             pod/calico-node-2bz2c                                     Stopping container calico-node
10m         Normal    Killing             pod/calico-node-2mjkt                                     Stopping container calico-node
26m         Normal    Killing             pod/calico-node-2srrt                                     Stopping container calico-node
34m         Normal    Killing             pod/calico-node-2vwz9                                     Stopping container calico-node
23m         Normal    Killing             pod/calico-node-4fqdf                                     Stopping container calico-node
31m         Normal    Killing             pod/calico-node-4hj2h                                     Stopping container calico-node
14m         Normal    Killing             pod/calico-node-4w9fr                                     Stopping container calico-node
7m          Normal    Killing             pod/calico-node-56ns7                                     Stopping container calico-node
10m         Normal    Killing             pod/calico-node-5mxjh                                     Stopping container calico-node
32m         Normal    Killing             pod/calico-node-65zmr                                     Stopping container calico-node
7m38s       Normal    Killing             pod/calico-node-66bnz                                     Stopping container calico-node
19m         Normal    Killing             pod/calico-node-66kx4                                     Stopping container calico-node
32m         Normal    Killing             pod/calico-node-6bctr                                     Stopping container calico-node
38m         Normal    Killing             pod/calico-node-6gq9b                                     Stopping container calico-node
29m         Normal    Killing             pod/calico-node-6hjk5                                     Stopping container calico-node
15m         Normal    Killing             pod/calico-node-6kn67                                     Stopping container calico-node
27m         Normal    Killing             pod/calico-node-6q6cp    
```

Thats all that I see. No OOM errors. It would be nice if I got to know why the pods are being killed :(

**Comment by hadimansuri** [comment]
It's an obvious requirement

**Comment by krafts** [comment]
Just ran into this myself with gitlab runners, and it was not obvious. Took an hour of debugging to find out it was because of OOM.

**Comment by m-yosefpor** [comment]
I think the `Killing` event should have a context about `State.Reason` which is only available via describing/viewing pod status. Since the pods are ephemeral and when a pod is already deleted, we can not find the reason for which it has been terminated in its status. Or at least kubelet should emit another event when updating pod status when terminating it.

**Comment by ryanpeach** [comment]
Please lets get this done.

**Comment by ryanpeach** [comment]
In case anyone needs a temporary solution to logging pod statuses, for example to a log server for later investigation, this is what I've done:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pod-status-logger-cronjob
  labels:
    app: pod-status-logger
spec:
  # Run every 10th minute
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-status-logger-sa
          containers:
          - name: pod-status-logger
            image: bitnami/kubectl
            imagePullPolicy: IfNotPresent
            command:
              - sh
              - "-c"
            args:
              - |
                NOW=$(date +%s)
                X_MINUTES_AGO=$(expr $NOW - 900)  # 15 minutes ago, a little longer than the cronjob runs
                kubectl get pods -o json | jq "select(.items[].status.conditions[-1].lastTransitionTime | fromdateiso8601 > $X_MINUTES_AGO) | {name: .items[].metadata.name, labels: .items[].metadata.labels, status: .items[].status}"
          restartPolicy: OnFailure
----
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-status-logger-clusterrole
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
----
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-status-logger-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: pod-status-logger-sa
roleRef:
  kind: ClusterRole
  name: pod-status-logger-clusterrole
  apiGroup: rbac.authorization.k8s.io
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-status-logger-sa
```
