### ISSUE TITLE
why deployment.spec.template.metadata.initializers.pending=[] has no effective

### ISSUE THREAD

**Issue by Kevin-fqh** [kubernetes/kubernetes#81823]
**What would you like to be added**:

### Solution 1:  when the InitializerConfiguration's resource is `deployment`

```yaml
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: test-testservice-initializer
initializers:
  - name: testservice.test.initializer.kubernetes.io
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - deployments
```

I create a deploy.yaml as follow，my app `kube-initializer` is such as [envoy-initializer](https://github.com/kelseyhightower/kubernetes-initializer-tutorial/tree/master/envoy-initializer)

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  initializers:
    pending: [] # skip the deployment itself go into stuck state，it can effective
  labels:
    app: kube-initializer
  name: kube-initializer
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      ...
      ...
```

### Solution 2:  when the InitializerConfiguration's resource is `pod`

```yaml
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: test-testservice-initializer
initializers:
  - name: testservice.test.initializer.kubernetes.io
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - pods
```

we also use deployment to run the `initializers`

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kube-initializer
  name: kube-initializer
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      initializers:
        pending: [] # we hold this can be effictive, but it is not
      labels:
        app: kube-initializer
      name: kube-initializer
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      automountServiceAccountToken: true
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      ...
      ...
```

#### why `deployment.spec.template.metadata.initializers.pending=[]` has noeffect

deploymentcontroller transform deployment.yaml to rs.yaml,  the`pending=[]` is still exist, but when convert rs.yaml into pod.yaml, the`pending=[]` is `lost`

```go
# pkg/controller/controller_utils.go

func GetPodFromTemplate(template *v1.PodTemplateSpec, parentObject runtime.Object, controllerRef *metav1.OwnerReference) (*v1.Pod, error) {
	desiredLabels := getPodsLabelSet(template)
	desiredFinalizers := getPodsFinalizers(template)
	desiredAnnotations := getPodsAnnotationSet(template)
	accessor, err := meta.Accessor(parentObject)
	if err != nil {
		return nil, fmt.Errorf("parentObject does not have ObjectMeta, %v", err)
	}
	prefix := getPodsPrefix(accessor.GetName())

	pod := &v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Labels:       desiredLabels,
			Annotations:  desiredAnnotations,
			GenerateName: prefix,
			Finalizers:   desiredFinalizers,
		},
	}
	if controllerRef != nil {
		pod.OwnerReferences = append(pod.OwnerReferences, *controllerRef)
	}
	pod.Spec = *template.Spec.DeepCopy()
	return pod, nil
}
```

the `func GetPodFromTemplate`, it ignore the `initializers` in `template *v1.PodTemplateSpec`

suggest we can add a func such as `desiredInitializers := getPodInitializers(template) ` to let `deployment.spec.template.metadata.initializers.pending=[]` become effective

**Why is this needed**:

1. we use deployment to run our initializer server
2. the InitializerConfiguration's resource is `pod`, such as `soloution 2`
