### ISSUE TITLE
Cannot expose long array of ports because of 262144 characters limitation in annotation

### ISSUE THREAD

**Issue by skwokie** [kubernetes/kubernetes#81852]
**What happened**:
Exposing 10000 (TCP and UDP) + 1 ports in a service is being blocked by the 262144 characters limitation for annotation.

Error message:
$ kubectl apply -f dev-svc-nodeport-svr.yaml
The Service "svr" is invalid: metadata.annotations: Too long: must have at most 262144 characters

YAML file size: 1.8M

**What you expected to happen**:
Service created successfully regardless of the port array size.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: v1
kind: Service
metadata:
  name: svr
  labels:
    app: svr
    env: dev
spec:
  type: NodePort
  selector:
    app: svr
    env: dev
ports:
  - targetPort: 443
    port: 443
    nodePort: 443
    name: https
    protocol: TCP
  - targetPort: 10000
    port: 10000
    nodePort: 10000
    name: t0
    protocol: TCP
  - targetPort: 10000
    port: 10000
    nodePort: 10000
    name: u0
    protocol: UDP
...
  - targetPort: 20000
    port: 20000
    nodePort: 20000
    name: t10000
    protocol: TCP
  - targetPort: 20000
    port: 20000
    nodePort: 20000
    name: u10000
    protocol: UDP
```

**Anything else we need to know?**:
Please feel free to let me know if there is a smarter way to declare the array of ports.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Mac (docker desktop)

- OS (e.g: `cat /etc/os-release`):
macOS, version: 10.14.6 (18G87)

- Kernel (e.g. `uname -a`):
Darwin skwok-mbp.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
