### ISSUE TITLE
bug in pr#71114：if i use ipvs mode on node with linux 3.10，kube-proxy will not work

### ISSUE THREAD

**Issue by ivan-cai** [kubernetes/kubernetes#82065]
**What happened**:
when I use ipvs mode on node with linux 3.10，my kube-proxy can not work.

**What you expected to happen**:
when I use ipvs mode on node with linux 3.10，my kube-proxy can work.

**How to reproduce it (as minimally and precisely as possible)**:
prepare a node with linux 3.10（<4.1），install k8s，and start kube-proxy with ipvs mode(/kube-proxy --proxy-mode=ipvs)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10.5 1.12.4
- Kernel (e.g. `uname -a`):
Linux VM_32_219_centos 3.10.107

**test**:
- use ipvs mode
```
/kube-proxy --kubeconfig=/etc/kubernetes/kubeproxy-kubeconfig --hostname-override=172.21.240.111 --v=2 --proxy-mode=ipvs --ipvs-min-sync-period=1s --ipvs-sync-period=5s --ipvs-scheduler=rr --masquerade-all=true
```
- service.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
```
- curl ${CLUSTER-IP}
    - compare with kube-proxy before and after bugfix
