### ISSUE TITLE
insecure-skip-tls-verify doesn't work for 'exec'

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#8211]
Trying to use the 'kubectl exec' command and it failes with the following error

```
Error: Error sending request: Get https://mydomain.com:6443/api/v1beta3/proxy/nodes/node3.c.my-project.internal/exec/default/myserver-522124b-3kgs5/rest-server?command=%2Fbin%2Fbash&error=1&output=1: x509: certificate is valid for 10.240.125.40@1431531404, not mydomain.com
```

Using kubelet, kube-apiserver and kubectl 0.16 and this is run on CoreOS 675.0.0 and GCE.

**Comment by vmarmol** [comment]
@danielnorberg do any other kubectl commands work?

**Comment by danielnorberg** [comment]
@vmarmol wrong daniel =)

**Comment by vmarmol** [comment]
@danielnorberg  sorry :) GitHub doesn't always pick the right one the first time.

@danielschonfeld see above

**Comment by danielschonfeld** [comment]
@vmarmol yes everything else works.  including `log` and `log -f`

**Comment by yujuhong** [comment]
@danielschonfeld, could you post the command you ran and how you used `insecure-skip-tls-verify`?

**Comment by danielschonfeld** [comment]
@yujuhong here's my config in `~/.kube/config`

```
apiVersion: v1
clusters:
- cluster:
    api-version: v1beta3
    insecure-skip-tls-verify: true
    server: https://master.myproject.com:6443
  name: myproject
contexts:
- context:
    cluster: myproject
    user: prod-user
  name: mycontext
current-context: mycontext
kind: Config
preferences: {}
users:
- name: prod-user
  user:
    password: hard-password
    username: awesome-user
```

And the command ran was

`$ kubectl exec -p kube-dns-m3be9 -c etcd -- etcdctl ls /`
