### ISSUE TITLE
Add ability to create empty ingress

### ISSUE THREAD

**Issue by ejez** [kubernetes/kubernetes#82203]
**What would you like to be added**:
Ability to create empty ingresses

**Why is this needed**:
Empty ingresses will be patched later by scripts/apps to add/update/delete rules dynamically as needed.

Note: I am using the described strategy with configmaps/secrets as k8s allows creating empty configmaps/secrets.

This might be achieved by removing the check for empty rules in [file](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/validation/validation.go#L215) `pkg/apis/networking/validation/validation.go`
```go
else if len(spec.Rules) == 0 {
		allErrs = append(allErrs, field.Invalid(fldPath, spec.Rules, "either `backend` or `rules` must be specified"))
	}
```

See #69422
/sig network

**Comment by cmluciano** [comment]
@kubernetes/sig-network-misc Is this something that should be supported? I assume since we validate this as such, then it is intentional.

cc @aledbf @bowei

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by bowei** [comment]
It seems like you can workaround this by inserting a dummy domain/service?

**Comment by ejez** [comment]
> It seems like you can workaround this by inserting a dummy domain/service?

That is what I am doing now in my project, I added an unnecessary rule and explained in a comment that this is because k8s does not allow empty ingresses, but this is a workaround not a solution and feels llike a hacky way, this is why I reported it.

**Comment by bowei** [comment]
I think this makes sense for configmap/secrets as they are just data (which could be empty).

Ingress resource is more like other controller mediated resources that have substantial synchronous validation and the our current thoughts are to have more synchronous validation rather than less (people like knowing their config is not going to do anything sooner rather than later)

Is the use of patch something RBAC related (in that you are only allowing patch rather than create).

**Comment by ejez** [comment]
I prefer to have a single object (configmap/secret/ingress ...etc) for all the projects/apps inside the cluster rather than having one per project/app. Having too many small objects might put pressure on the k8s api server.
For example one nginx configmap that contains configuration for all websites (each website having its key/value inside the same configmap) rather than having too many configmaps, one per website.

Here is my implementation now for the ingress resource:
Initial setup:
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  # Because k8s does not allow creating empty ingresses, we provide this dummy
  # rule. Additional rules will be added when new projects are created.
  # issue: https://github.com/kubernetes/kubernetes/issues/82203
  tls:
  - hosts:
    - dummy-tls-host
    secretName: dummy-tls-secret
  rules:
  - host: dummy-host
    http:
      paths:
      - path: /
        backend:
          serviceName: ingress-default-backend
          servicePort: 8080
```
When a website is added:

```bash
kubectl patch ingress my-ingress --type json --patch '[{"op": "add", "path": "/spec/rules/-", "value": "coming from template ... " }]'

kubectl patch ingress my-ingress --type json  --patch '[{"op": "add", "path": "/spec/tls/-", "value": "coming from template ... " }]'
```

When a website is deleted, similarly:
a patch with "op": "remove" will be executed

I can live with the dummy host definition, but a fix would be preferable.

**Comment by aledbf** [comment]
> Having too many small objects might put pressure on the k8s api server.

Why do you think that?

> For example one nginx configmap that contains configuration for all websites (each website having its key/value inside the same configmap) rather than having too many configmaps, one per website.

Actually, you should prefer the many configmaps approach. Remember that k8s objects have a size limit. The one configmap map approach will reach that limit eventually.

> I can live with the dummy host definition, but a fix would be preferable.

The issue I see with your request is, what are you trying to say defining an empty object, from an L7 point of view? I would not use your dummy-host approach and only create the ingress object once I get all the dependency in place and ready to serve traffic. Keep in mind that you get charged in some implementations when you create an ingress rule.

**Comment by ejez** [comment]
Thanks for your reply Manuel,

> 
>     Having too many small objects might put pressure on the k8s api server.
> 
> Why do you think that?

> Actually, you should prefer the many configmaps approach. Remember that k8s objects have a size limit. The one configmap map approach will reach that limit eventually.

I'm not familiar with the inner working of k8s, but this is what I found in the k8s doc which pushes me to try to reduce the number of resource objects. For my use case, this won't result in very large objects as each app/project will have a tiny config inside the k8s object.

https://kubernetes.io/docs/concepts/policy/resource-quotas/
> Too many secrets in a cluster can actually prevent servers and controllers from starting! 

https://kubernetes.io/docs/concepts/configuration/secret/
> ...However, creation of many smaller secrets could also exhaust memory

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
> Finished Jobs are usually no longer needed in the system. Keeping them around in the system will put pressure on the API server.

https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/
> Custom resources consume storage space in the same way that ConfigMaps do. Creating too many custom resources may overload your API server’s storage space.

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#job-patterns
> One Job object for each work item, vs. a single Job object for all work items. The latter is better for large numbers of work items. The former creates some overhead for the user and for the system to manage large numbers of Job objects.

================================
> I would not use your dummy-host approach and only create the ingress object once I get all the dependency in place and ready to serve traffic

You are right, I think I'll remove the dummy ingress and change the website creation script to check first if the ingress exists and creates it if not, however this will make the script longer/complex.

**Comment by bowei** [comment]
For ordinary objects, we haven't seen number of etcd objects become a problem until you get in the order of millions. Not clear on what is specifically different about secrets though.

**Comment by thockin** [comment]
Do we have further thoughts here?  Keep this open as plan-to-support or close it?

**Comment by cmluciano** [comment]
There is an [open PR](https://github.com/kubernetes/kubernetes/pull/82219) for this but I'm not sure if this feature should be implemented in the current API. I believe there were thoughts about making the backend mandatory instead of loosening conditions.

**Comment by bowei** [comment]
I'm going to close this for now as there is a workaround. Reopen if needed.
/close

**Comment by nicolas-vivot** [comment]
Hey,

I know this is out of your scope, but since such use case exists it might be worse to have a look at it.

I'm using AWS EKS, with ALB as ingress controller. When using the "alb" ingress class, 1 Ingress resource will create by default 1 ALB.
Probably under the pressure of users, they created the group notion so that you can group multiple Ingress resource under the same ALB resource.

I'm currently reviewing my EKS cluster organisation in term of ingresses/ALB and here is what i'm going to organize it:

- Create a dedicated namespace "ingresses" to setup the "master" Ingress resources representing 1 ALB each. These master Ingress resources defines main annotation regarding security, authentication, group name, priority.
- Create 1 or more Ingress resources into my applications namespace : these Ingress only do the following: refers to the group they have to join and defines the routing rules specific to the application they handles.
- All Ingress resource's rules are automatically merged into a single rules definition at the ALB level (with priority management in case of override between Ingress definition)

In such configuration, it make sense that the master Ingress resources are not serving anything but defining the main settings, and the specific application Ingress resources defines the rules.
But currently, we have to setup fakes defaultBackend or rules in the master Ingress resources for nothing.

**Comment by MartinEmrich** [comment]
Another use case: Adding additional certificates (for additional DNS domains) to existing Ingresses on AWS. This would work well with ingress groups, but because of this, each of these ingress objects still needs a dummy rule.

Example:
````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: just-another-certificate
  annotations:
    alb.ingress.kubernetes.io/group.name: my-existing-ingress-group
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:000000000000:certificate/1234-5678-1234-5678-1234567890whatever
    alb.ingress.kubernetes.io/actions.dummy: >
      {"type":"fixed-response", "fixedResponseConfig": { "contentType": "text/plain", "statusCode": "404", "messageBody": "x"}}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /some-randomness-never-used-FahjooB1ushug0ea5tiaquahsoMookee
            pathType: Exact
            backend:
              service:
                name: dummy
                port:
                  name: use-annotation
````

(Will ask on *aws-load-balancer-controller* if there's a better solution to achieve this, but I still find the generic use case of adding annotations/configuration to ingress groups or the Ingress controller itself without rules a valid one.
