### ISSUE TITLE
hpa.v2beta2.autoscaling starts scaling up when only half of target is reached

### ISSUE THREAD

**Issue by Morriz** [kubernetes/kubernetes#82217]
**What happened**:
given hpa values:
```
spec:
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
```
We notice scaling up happens when either target passes 40%

**What you expected to happen**:
scaling up to happen when 80% is passed

**How to reproduce it (as minimally and precisely as possible)**:
increase load on deployment deployed onto k8s 1.12.8 with above settings

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.8
- Cloud provider or hardware configuration: GKS
