### ISSUE TITLE
why the contianer memory limit in cgroup not accurate 

### ISSUE THREAD

**Issue by wu0407** [kubernetes/kubernetes#82230]
The container set resource limit：
```
resources:
      limits:
        cpu: "1"
        memory: 1G
      requests:
        cpu: "1"
        memory: 1G
```
the cgroup memory limit:
```
cat /sys/fs/cgroup/memory/kubepods.slice/kubepods-podaace5b66_c7d0_11e9_ba2a_dcf401d01e81.slice/memory.limit_in_bytes 
999997440
``` 
1GB= 1*1024*1024*1024=1,073,741,824B
k8s version:1.14.4
docker version:  docker-ce-18.09.6
/sig node

**Comment by maikebertpsc** [comment]
I was also confused lately about this, but it's afaik totally correct.

You specify the memory in Gigabyte, so in thousands of bytes.
If you want to have your expected result you need to configure the memory in GiB (Gigibytes).

Have a look here: https://en.wikipedia.org/wiki/Gibibyte

**Comment by wu0407** [comment]
1 Giga is 1000000000，but 999997440. why?

**Comment by zq-david-wang** [comment]
Are you using qos reserved feature, or something else alike? Could you list your kubelet configuration?

**Comment by wu0407** [comment]
kubelet running command
```
/usr/local/kubernetes/bin/kubelet --config=/etc/kubernetes/kubelet-config.yaml --network-plugin=cni --v=2 --logtostderr=false --log-dir=/var/log/kubernetes --kubeconfig=/etc/kubernetes/kubelet.kubeconfig
```
/etc/kubernetes/kubelet.kubeconfig
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /usr/local/kubernetes/pki/ca/ca.pem
    server: https://192.168.0.13
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: system:node:test
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: system:node:test
  user:
    client-certificate: /usr/local/kubernetes/pki/kubelet/admin.pem
    client-key: /usr/local/kubernetes/pki/kubelet/admin-key.pem
```
