### ISSUE TITLE
Choose permissions on secret mounted volume

### ISSUE THREAD

**Issue by tmonguillon** [kubernetes/kubernetes#82263]
**What would you like to be added**:

Just like the `defaultMode` parameter that allows setting permissions on files contained into a mounted secret volume, we should be able to have a parameter that allows setting permissions on the mounted point.

**Why is this needed**:

A pod is created with a given security context [1] and the application which is executed into uses tokens which are generated in a secret volume with specific permissions [2].

Despite the fact the mounted secret volume and the files generated into have the correct ownship permissions on the mount point does not reflect permissions of the files contained into [3].

For some security reasons an applications using files stored in the secret volume could complain about too lax permissions on the folder containing this files (aka the mountpoint).

[1]
```
      securityContext:
        runAsUser: 42425
        runAsGroup: 42425
        fsGroup: 42425

```

[2]
```
      volumes:
        - name: keystone-fernet-keys
          secret:
            secretName: keystone-fernet-keys
            defaultMode: 416
        [...]
      containers:
        [...]
          volumeMounts:
            - name: keystone-fernet-keys
              mountPath: /etc/keystone/fernet-keys
              readOnly: true
            [...]

```
[3]
```
[ampere - root@m1-foremansible.mgmt.oiaas:kubernetes]# kubectl -n  openstack exec keystone-admin-api-7dd74d4b96-s2mfk -- ls -laR /etc/keystone/fernet-keys
/etc/keystone/fernet-keys:
total 0
drwxrwsrwt. 3 root keystone 180 Sep  3 08:01 .
drwxrwsrwx. 4 root keystone 166 Aug 28 15:06 ..
drwxr-sr-x. 2 root keystone 140 Sep  3 08:01 ..2019_09_03_08_01_27.181100898
lrwxrwxrwx. 1 root keystone  31 Sep  3 08:01 ..data -> ..2019_09_03_08_01_27.181100898
lrwxrwxrwx. 1 root root       8 Aug 28 15:06 0 -> ..data/0
lrwxrwxrwx. 1 root keystone   9 Sep  2 20:01 32 -> ..data/32
lrwxrwxrwx. 1 root keystone   9 Sep  3 00:01 33 -> ..data/33
lrwxrwxrwx. 1 root keystone   9 Sep  3 04:00 34 -> ..data/34
lrwxrwxrwx. 1 root keystone   9 Sep  3 08:01 35 -> ..data/35

/etc/keystone/fernet-keys/..2019_09_03_08_01_27.181100898:
total 20
drwxr-sr-x. 2 root keystone 140 Sep  3 08:01 .
drwxrwsrwt. 3 root keystone 180 Sep  3 08:01 ..
-rw-r-----. 1 root keystone  44 Sep  3 08:01 0
-rw-r-----. 1 root keystone  44 Sep  3 08:01 32
-rw-r-----. 1 root keystone  44 Sep  3 08:01 33
-rw-r-----. 1 root keystone  44 Sep  3 08:01 34
-rw-r-----. 1 root keystone  44 Sep  3 08:01 35
[ampere - root@m1-foremansible.mgmt.oiaas:kubernetes]# 
```
