### ISSUE TITLE
Large CRDs go over size limits (e.g. those with embedded podspecs)

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/kubernetes#82292]
Over in KubeBuilder land, we've started to see issues around very large validation blocks going over size limits.  Thus far, it's mainly just been the client-size-apply-induced annotation limit, but I worry that when we've start getting multiple versions -- we might go over the 1M limit.  For instance, see https://github.com/kubernetes-sigs/kubebuilder/issues/962, which has  single-version 700k CRD, due to the large validation schema.

So far, we've mostly been able to solve the issues by partially or fully truncating the field descriptions, but this seems suboptimal, since you're basically saying "you don't get API docs now".

From what I've seen so far, the issues are usually hit with things like PodSpec (e.g. we hit the client-side-apply annotation limit with our conversion of CronJob in our tutorial, when we introduced a new version).

Worst comes to worst, we can add more pruning in controller-tools/kubebuilder, but I was wondering if some folks had better ideas or more discussion upstream.

Refs (https://github.com/kubernetes/kubernetes/issues/62872) could help alleviate this a bit in the case of multiple podspecs, but don't solve the problem entirely (unless we get cross-object refs, which have previously been rejected).

Increasing the object size avoids the issue we *haven't* hit yet, but won't solve the client-side-apply annotation limit issue.  Practically even though SSA will get here eventually, folks are going to be using pre-SSA kubectls for a while, I expect.

**TL;DR:** Pod spec validation makes CRDs large, any suggestions?

/sig apimachinery

**Comment by yue9944882** [comment]
@sttts we can probably lessen the CRD size by supporting `$ref` declarative from the OpenAPI schema..

**Comment by erictune** [comment]
The `$ref` option seems like it will help with the problem of including pod templates (while also changing the behavior of the CRD when the core kubernetes version is upgraded).

It doesn't seem like it would help with the problem where descriptions are simply too long, but where you want to include the rest of the 

Since `$ref` replaces all the properties at its level, you can't replace the value of a `description` tag with a URL (which would be convenient).  The `$ref` could point to all the levels, but then the user's authoring experience in GoIDL is compromised, and the API Server is obliged to fetch all the `$ref` links.

As a hack, verbose descriptions could be by convention replaced with short links, like this:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
# ...
spec:
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          # ...
          spec:
            properties:
              replicas:
                description: |- 
                  How many replicas.  See http://bitly.com/w34kjkj. 
```

But, this isn't ideal for tools that need to further process the CRD like docs generators or the API Server itself when it converts them to `/openapi/v2`.  When should they inline the linked-to content, and when should it be re-fetched, for example.
