### ISSUE TITLE
Environment variable from secret pass in different way than from plain text

### ISSUE THREAD

**Issue by AdamWyzgol** [kubernetes/kubernetes#82327]
**What happened**:
When using secret to pass DB_PASSWORD to jboss/keycloak container, application fail to start with wrong password error, when password is passed using value as plain text everything is working fine

**What you expected to happen**:
It should working the same, both using value and valueFrom secret.

**How to reproduce it (as minimally and precisely as possible)**:
Error occured when try to run Deployment of jboss/keycloak using postgresql database, my env looks like:
```
        env:
          - name: DB_VENDOR
            value: postgres
          - name: DB_ADDR
            value: keycloak-postgresq
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: keycloak-postgres
          - name: DB_PASSWORD
#            value: PlaintextPassword
            valueFrom:
              secretKeyRef:
                key: password
                name: keycloak-postgres
```
On service keycloak-postgresq I have running postgresql with the same secret as credentials, on postgres should be created keycloak database before run of keycloak pod. 
When I comment valueFrom and uncomment value everything is working fine

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.3
- Cloud provider or hardware configuration: vmware virtual machine 
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-957.27.2.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
