### ISSUE TITLE
ELB tags will overwrite tags on existing Security group

### ISSUE THREAD

**Issue by kverstr** [kubernetes/kubernetes#82369]
**What happened**:
Creating this Service created a LB in AWS, which is what we want.
But we added the service.beta.kubernetes.io/aws-load-balancer-extra-security-groups annotation to add an existing SG to this LB. This also works, but because we specified tags for our LB, it overwrites the existing tags on the SG with these tags. And that's not something that should happen.

```
apiVersion: v1
kind: Service
metadata:
  name: public-nginx-ingress
  namespace: default
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Name=foo,Environment=bar"
      service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-aaabbbccc
  labels:
    app: public-nginx-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  selector:
    app: public-nginx-ingress-controller
```

**What you expected to happen**:

We expected that the SG would remain unchanged since it's an existing one and this SG is widely used between AWS services.

**How to reproduce it (as minimally and precisely as possible)**:
- create a service as shown above
- use an existing SG to add to the LB
- check the tags on the SG after creation of the LB

**Anything else we need to know?**:
**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
AWS
- OS (e.g: `cat /etc/os-release`):
`NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2191.4.1
VERSION_ID=2191.4.1
BUILD_ID=2019-08-26-2152
PRETTY_NAME="Container Linux by CoreOS 2191.4.1 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"`
- Kernel (e.g. `uname -a`):
`Linux ip-10-34-123-35 4.19.66-coreos #1 SMP Mon Aug 26 21:06:50 -00 2019 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux`
