### ISSUE TITLE
Duplicate containerPorts not allowed across different address families

### ISSUE THREAD

**Issue by xcelsion** [kubernetes/kubernetes#82373]
**What happened**:
I tried to create a deployment with duplicate containerPorts with hostIPs of two different address families. Only the first mapping was provided as input into my CNI plugin chain. Also, a log message from kubelet warning about a duplicate containerPort was created.

**What you expected to happen**:
Both mappings to be provided as input into my CNI plugins. No log messages should be created.

**How to reproduce it (as minimally and precisely as possible)**:
Create this deployment:
```
kubectl create -f - <<EOF
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      nodeSelector:
        kubernetes.io/hostname: w-02
      containers:
        - name: ubuntu
          image: ubuntu:18.04
          command:
            - tail
            - -f
            - /dev/null
          ports:
            - containerPort: 80
              hostIP: 142.93.228.87
              hostPort: 80
            - containerPort: 80
              hostIP: 2a03:b0c0:2:f0::b1:2001
              hostPort: 80
EOF
```

Then grab kubelet logs on the host e.g:
```
# journalctl -u kubelet | grep 'Port name conflicted'
Sep 03 21:27:32 w-02 kubelet[984]: W0903 21:27:32.889457     984 helpers.go:328] Port name conflicted, "ubuntu-TCP:80" is defined more than once
```

**Anything else we need to know?**:
This issue here provides some context as to how I ran into this issue:
https://github.com/containernetworking/plugins/pull/379

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15.1
- Cloud provider or hardware configuration: DigitalOcean, custom setup
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux w-02 5.2.9-050209-generic #201908160940 SMP Fri Aug 16 09:42:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: None
- Network plugin and version (if this is a network-related bug): Cilium v1.6.0 and Portmap v0.8.2
- Others: N/A

I've already identified the problem and will submit a PR which fixes this shortly.

/sig network
