### ISSUE TITLE
how to use 'kubectl explain' to crd's substance.

### ISSUE THREAD

**Issue by qiyongxiao** [kubernetes/kubernetes#82407]
Hi, dear authors:
     I have an enhancement request of kubernetes's cli-->kubectl explain. Recently, I deploy to k8s clusters called master1 and master2. And has deployed the federation v2.
    Now I want to see the federation's kinds like FederatedDeployment's substance. Just like this
```
[root@master1 Desktop]# kubectl explain deployment.spec --recursive
KIND:     Deployment
VERSION:  extensions/v1beta1
RESOURCE: spec <Object>
DESCRIPTION:
     Specification of the desired behavior of the Deployment.
     DeploymentSpec is the specification of the desired behavior of the
     Deployment.
FIELDS:
   minReadySeconds	<integer>
   paused	<boolean>
   progressDeadlineSeconds	<integer>
   replicas	<integer>
   revisionHistoryLimit	<integer>
   rollbackTo	<Object>
      revision	<integer>
   selector	<Object>
      matchExpressions	<[]Object>
         key	<string>
         operator	<string>
         values	<[]string>
........
```
While I excute this kinds of command to show the resource federatedDeployment, it show:
```
[root@master1 Desktop]# kubectl explain federateddeployment --recursive
error: Couldn't find resource for "types.kubefed.io/v1beta1, Kind=FederatedDeployment"
```
Please tell me how to show the custom-resource-definitions apiservice like federation's federateddeployment or istio's virtualservice and gateway, each of them's substance for write some configuration to yaml file to deploy it with "kubectl apply -f"

Sometimes ago, I see the gitcommit messages says: "it support to use kubectl explain" to show crd. And is this functionality implemented now?

**Comment by liggitt** [comment]
starting in v1.15.0, custom resource definitions that [specify structural schemas](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) will [publish OpenAPI schema documentation](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2), which is what `kubectl explain` uses.

/close

**Comment by qiyongxiao** [comment]
> starting in v1.15.0, custom resource definitions that [specify structural schemas](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) will [publish OpenAPI schema documentation](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2), which is what `kubectl explain` uses.
> 
> /close

It is empty?
```
[root@master1 ~]# kubectl explain federateddeployments
KIND:     FederatedDeployment
VERSION:  types.kubefed.io/v1beta1

DESCRIPTION:
     <empty>
[root@master1 ~]# 
```

**Comment by liggitt** [comment]
check the CRD API object status to see if there is a non-structural condition that needs to be corrected before openapi will be published

**Comment by wonderflow** [comment]
Some issue here, I did't see any non-structural condition.

```
status:
  acceptedNames:
    categories:
    - crossplane
    - oam
    kind: ManualScalerTrait
    listKind: ManualScalerTraitList
    plural: manualscalertraits
    singular: manualscalertrait
  conditions:
  - lastTransitionTime: "2020-05-07T08:54:19Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-05-07T08:54:26Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
```

But get nothing:

```
kubectl explain manualscalertraits
KIND:     ManualScalerTrait
VERSION:  core.oam.dev/v1alpha2

DESCRIPTION:
     <empty>
```
