### ISSUE TITLE
CRD with a single element in spec.versions is not allowed

### ISSUE THREAD

**Issue by bengadbois** [kubernetes/kubernetes#82443]
**What happened**:
Attempt to create a CRD with only one version in the new versions field (see example below)

**What you expected to happen**:
I expected this would be pass validation

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply the following:
```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testcrs.foo.bar.com
spec:
  scope: Namespaced
  group: foo.bar.com
  names:
    kind: testcr
    plural: testcrs
    singular: testcr
  versions:
    - name: v1
      storage: true
      served: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                fooproperty:
                  type: string
```
This is rejected with:
```
The CustomResourceDefinition "testcrs.foo.bar.com" is invalid: spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1", Served:true, Storage:true, Schema:(*apiextensions.CustomResourceValidation)(0xc000ba6d08), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: per-version schemas may not all be set to identical values (top-level validation should be used instead)
```

**Anything else we need to know?**:
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#overview notes that `Note: Earlier iterations included a version field instead of versions. The version field is deprecated and optional, but if it is not empty, it must match the first item in the versions field.`. This means that once `Version` is removed, all versions must be specified via `Versions`, which will break for all CRDs with only one version.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.3
- Cloud provider or hardware configuration: bare metal
- OS (e.g: `cat /etc/os-release`): Linux
- Kernel (e.g. `uname -a`): 4.15.0-50-generic
- Install tools:
- Network plugin and version (if this is a network-related bug): N/A
- Others:
