### ISSUE TITLE
High system load/CPU utilization with trivial liveness and readiness probes

### ISSUE THREAD

**Issue by danbeaulieu** [kubernetes/kubernetes#82440]
**What happened**:
Using trivial probes significantly contributes to CPU/system load.

**What you expected to happen**:
Trivial probes should be performant

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster (minimal reproduction done on an m5.large ec2 instance, creating a single node cluster via kubeadm with a deployment specifying a 2 pod replica scheduled on the single node. Reproduction steps are available for more complex setups)
2. Measure system load/CPU utilization
3. Deploy the following deployment
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: diagnostic
  name: diagnostic
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: diagnostic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: diagnostic
    spec:
      containers:
      - name: diagnostic
        image: ubuntu:18.04 
        command:
        - /bin/bash
        - -c
        - touch /tmp/healthy; sleep 3600
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 120

        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          initialDelaySeconds: 10
          periodSeconds: 2 
          failureThreshold: 120
      restartPolicy: Always
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - operator: "Exists"
```
4. Remeasure system load/CPU utilization

**Anything else we need to know?**:
Included is a screenshot. The beginning shows the node in "steady state" without the deployment running. This is at about 10% utilization. The first blip is deploying a similar deployment with no probes specified, still at 10%. The second blip is deploying a similar deployment but with just the livenessprobe specified, this is about 17%. The third blip is deploying the provided deployment with both liveness and readiness probes specified, this is about 34%. 

![probe-cpu-util](https://user-images.githubusercontent.com/902943/64458045-4a485d00-d0c2-11e9-81ab-70b8ae5ca0b9.png)

Further testing shows that CPU utilization is maxed out and system load extremely high with 4 pods in the deployment.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.3
- Cloud provider or hardware configuration: AWS (m5.large)
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3
- Kernel (e.g. `uname -a`): 5.0.0-25-generic
- Install tools: kubeadm 1.15.3
- Network plugin and version (if this is a network-related bug): VPC CNI v1.5.3 (reproduced with kuberouter as well)
- Others: Docker 18.09.2
