### ISSUE TITLE
Initial check for container being ready in a pod

### ISSUE THREAD

**Issue by alitoufighi** [kubernetes/kubernetes#82482]
**What would you like to be added**:
I had the issue mentioned here: https://github.com/kubernetes/kubernetes/issues/37450

My applications take some time to be ready for serving traffic after creation, and I thought `readinessProbe` must be the solution to keep them `NotReady` until they're actually ready. But I only need this in the beginning of the lifecycle of my container. Using readinessProbe caused me experiencing a heavy CPU load which is not proper at all.

If there was something like `initialReadinessDelay` that I could say `Wait for 2 minutes before bringing down old pods and replacing new ones`, or using a `initialReadinessProbe` to check for availability of my containers, or adding some features to existing `readinessProbe` to set for this purpose, I would be happy experiencing a real zero downtime update.

**Why is this needed**:
Aside `readinessProbe` and `livenessProbe` that monitor healthiness of Pods, sometimes your containers are not such complicated. They only at their startup, need some time before they're really up and ready, and then they do their job. Then if something wrong happened, they simply crash and get restarted by their Deployment. Limiting running a `readinessProbe` only once prevents excess usage of resources.

**Note:** The `readinessProbe` I was using was this simple one:
```YAML
readinessProbe:
  exec:
    command:
    - echo
    - '0'
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1
```
Because I only needed 60 seconds before Kubelet checks my container as `Ready`.
