### ISSUE TITLE
Statefullset does not honor podManagementPolicy=OrderedReady when restarting failed pods

### ISSUE THREAD

**Issue by Benjamin-Riefenstahl-mecom** [kubernetes/kubernetes#82529]
**What happened**:

We have a Statefullset with `podManagementPolicy=OrderedReady`.  For testing I throw away all PODs using `kubectl delete --force --grace-period=0`.  Kubernetes restarts the PODs all at the same time, i.e. in parallel.

**What you expected to happen**:

The PODs should be restarted one by one.  The PODs rely on that, which is why we use `OrderedReady`.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

If there is another method to achieve what we want, please tell.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.12", GitCommit:"c757b93cf034d49af3a3b8ecee3b9639a7a11df7", GitTreeState:"clean", BuildDate:"2018-12-19T11:04:29Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Self-hosted
- OS (e.g: `cat /etc/os-release`):
Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`):
4.4.0-140-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Joseph-Irving** [comment]
I've tried reproducing this on kubernetes v1.10.12 but I could not get the same behaviour
I created a basic sample statefulset
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 80
          name: web
```
Deleted all the pods
```
kubectl delete pods -l app=nginx --force --grace-period=0
```
Pods start getting recreated
```
kubectl get pods
NAME    READY   STATUS              RESTARTS   AGE
web-0   0/1     ContainerCreating   0          2s
```
Pods were being recreated in order as expected
```
kubectl get pods
NAME    READY   STATUS    RESTARTS   AGE
web-0   1/1     Running   0          20s
web-1   0/1     Running   0          2s
```

Can you show your statefulset manifest `kubectl get statefulset <statefulset name> -o yaml` ?

Also worth noting that kubernetes v1.10.12 is EOL, the current supported versions of kubernetes are 1.13, 1.14 and 1.15. So it might be worth upgrading to see if that fixes your issue.
