### ISSUE TITLE
AWS: Network Load Balancer ignores annotations upon creation

### ISSUE THREAD

**Issue by alx13** [kubernetes/kubernetes#82595]
**What happened**:
Code for handling annotations for load balancer is executed only upon load balancer modification, not creation in all versions including master branch.

So, for example, it's not possible to enable cross-zone load balancing upon creation. Only create-then-update process works.
- [1.14.6](https://github.com/kubernetes/kubernetes/blob/v1.14.6/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L344)
- [1.15.3](https://github.com/kubernetes/kubernetes/blob/v1.15.3/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L326)
- [master](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L336)

**What you expected to happen**:
Annotations  should be parsed both upon creation and update of load balancer

Code, that parses annotations should be moved outside `else` block
- [1.14.6](https://github.com/kubernetes/kubernetes/blob/v1.14.6/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L179)
- [1.15.3](https://github.com/kubernetes/kubernetes/blob/v1.15.3/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L164)
- [master](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/aws/aws_loadbalancer.go#L174)

or duplicated in `if` block

**How to reproduce it (as minimally and precisely as possible)**:
1. create `Service.spec.type.LoadBalancer` with:
```yaml
annotations:
  service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
```
 cross-zone load balancing will be off

2. modify something in `Service` definition — CZLB will be on

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0—1.14.6, 1.15.0—1.15.3, master
- Cloud provider or hardware configuration: AWS

**Comment by jwm** [comment]
I experienced this recently with 1.14.9 on EKS. A newly created NLB ignored `service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled`.

**Comment by ckdarby** [comment]
Experienced this with EKS 1.15 on EKS.

```YAML
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tensorflow-serving.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "tensorflow-serving.chart" . }}
    app: {{ template "tensorflow-serving.name" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: grpc-service-port
      port: {{ .Values.grpcServicePort }}
      targetPort: grpc-port
    - name: http-service-port
      port: {{ .Values.restServicePort }}
      targetPort: http-port
  selector:
    release: {{ .Release.Name | quote }}
    app: {{ template "tensorflow-serving.name" . }}
```
