### ISSUE TITLE
The statefulset have duplicate revision after resource was updated.

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#82613]
**What happened**:

I create a statefulset with below content:
```
---
apiVersion: v1
kind: Service
metadata:
  name: test-sts
  labels:
    app: test-sts
spec:
  ports:
  - port: 80
    name: test-sts
  clusterIP: None
  selector:
    app: test-sts
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: StatefulSet
metadata:
  name: test-sts
spec:
  serviceName: test-sts
  replicas: 2
  selector:
    matchLabels:
      app: test-sts
  template:
    metadata:
      labels:
        app: test-sts
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2-alpine
        ports:
        - containerPort: 80
          name: test-sts
  updateStrategy:
    type: RollingUpdate

```

Then I update the image with command:
`kubectl patch statefulset test-sts -n ${NAMESPACE} --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"nginx:1.15.8-alpine"}]'`

Checking the rollout history, find the have duplicate revision 0 in the list:
```
hchenxa@hchenxadembp:~/Documents/hchenxa/src/ICP/icp-sert-bats$ kubectl rollout history sts/test-sts -n sert-workns
statefulset.apps/test-sts
REVISION
0
0
1
2

```

**What you expected to happen**:

actually, `0` should not be a valid revision number.

**How to reproduce it (as minimally and precisely as possible)**:
See as above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
