### ISSUE TITLE
Kubectl diff panic when one port has not containerPort port

### ISSUE THREAD

**Issue by evilrussian** [kubernetes/kubernetes#82863]
**What happened**:
kubectl diff crushing if i add new port in manifest of existing statefulset without containerPort and will make diff
```
$ kubectl diff -f /tmp/StatefulSet.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10ceda7]
```

**What you expected to happen**:
I expected error for incorrect manifest. Or default values of containerPort field 

**How to reproduce it (as minimally and precisely as possible)**:
For example, i have this StatefulSet in my kubernetes cluster:
```
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: myapp
  serviceName: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: myregistry.mysite.ru/myproject/myapp:v1.3.8
        name: myapp
        resources:
          limits:
            memory: 1024Mi
            cpu: "1000m"
          requests:
            memory: 256Mi
            cpu: "200m"
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/application
      volumes:
      - name: config-volume
        configMap:
          name: myapp`
```
It's applied and works fine. If i add new port in my manifest without containerPort, for example:
```
        ports:
        - name: http
          containerPort: 80
        - name: grpc
        volumeMounts:
```
and make kubectl diff, i will receive panic.

**Anything else we need to know?**:

If where is not statefullset (not applied) in kubernetes, kubectl diff will show default value "0" of containerPort
```
+        - containerPort: 80
+          name: http
+          protocol: TCP
+        - containerPort: 0
+          name: grpc
+          protocol: TCP
```

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
```
- OS: mac os x 10.14.6
