### ISSUE TITLE
StatefulsetController dose not delete pod after statefulset updated 

### ISSUE THREAD

**Issue by hakur** [kubernetes/kubernetes#82925]
## What happened ?
I have made a test, first I created a statefulset with wrong container image, so pod gets wrong.
I updated container image to ```nginx``` , but pod still in ErrImagePull state, and I saw container image not changed.

According to this line : https://github.com/kubernetes/kubernetes/blob/release-1.11/pkg/controller/statefulset/stateful_set_control.go#L428 pod will not be deleted when any pod is not health which under this statefulset (check code still on master branch)

But when I changed statefulset ```podManagementPolicy: Parallel```, it work fine, pods were deleted and ignored pods health state.

So I and my workmates are confused, **why can't just delete pods when container image has changed**

(By the way, my leader dose not wants to change podManagementPolicy to  Parallel :sob: )

## Environment
  * kubernetes version : v1.11
  statefulset yaml
```
kind: Service
apiVersion: v1
metadata:
  name: sts
spec:
  selector:
    app: sts
  ports:
  - port: 80
    targetPort: 80

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: sts
spec:
  serviceName: sts
  replicas: 1
  selector:
    matchLabels:
      app: sts
  template:
    metadata:
      labels:
        app: sts
    spec:
      containers:
      - image: aaa
        name: kkkk
  updateStrategy:
    type: RollingUpdate
```

## What do you want?
Need some documents to make a explain to our customer, to explain why statefulset can't recover from wrong state after fix  

Thanks :pray: :pray: :pray:
