### ISSUE TITLE
Add support for "Specification Extensions" in openAPIV3Schema to CRDs

### ISSUE THREAD

**Issue by rhuss** [kubernetes/kubernetes#82942]
**What happened**:

When using a CRD like in the example below which uses [specification extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#specificationExtensions), then an error is thrown

<details>
  <summary>A sample GitHub Event Source CRD from Knative Eventing</summary>
 
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: githubsources.sources.eventing.knative.dev
spec:
  group: sources.eventing.knative.dev
  names:
    categories:
    - all
    - knative
    - eventing
    - sources
    kind: GitHubSource
    plural: githubsources
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            accessToken:
              properties:
                secretKeyRef:
                  # Name of a cli option mapping to this field
                  x-cli-option: "access-token"
                  # Type which triggers a special treatment of the option to
                  # create the embedded opject with a `key:` and `name:` field
                  x-cli-type: "map-selector"
                  # Help message which can be used by a CLI on the help page
                  x-cli-help: "GitHub access token. The value of this option is the name of a secret and key within secret to GitHub access, dot separated (e.g. --secret-token=mygithubsecret.mykey) "
                  type: object
              type: object
            eventTypes:
              items:
                enum:
                - create
                - team
                - team_add
                - watch
                type: string
              minItems: 1
              x-cli-option: "event-type"
              x-cli-help: "GitHub events to watch for. This is a comma separated list of options. Alternatively this option can be provided multiple times."
              type: array
            ownerAndRepository:
              x-cli-option: "owner"
              minLength: 1
              type: string
            secretToken:
              properties:
                secretKeyRef:
                  x-cli-option: "secret-token"
                  x-cli-type: "map-selector"
                  x-cli-help: "GitHub secret token. The value of this option is the name of a secret and key within secret to GitHub access, dot separated (e.g. --secret-token=mygithubsecret.mykey) "
                  type: object
              type: object
            serviceAccountName:
              x-cli-option: "service-account"
              x-cli-help: "Service account"
              type: string
            sink:
              type: object
          required:
          - ownerAndRepository
          - eventTypes
          - accessToken
          - secretToken
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    # we use a string in the stored object but a wrapper object
                    # at runtime.
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
            webhookIDKey:
              type: string
          type: object
  version: v1alpha1
```

</details>

Error Message:

```
error: error validating "github-source-with-cli.yml": error validating data: [ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.accessToken.properties.secretKeyRef): unknown field "x-cli-help" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.accessToken.properties.secretKeyRef): unknown field "x-cli-option" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.accessToken.properties.secretKeyRef): unknown field "x-cli-type" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.eventTypes): unknown field "x-cli-help" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.eventTypes): unknown field "x-cli-option" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.ownerAndRepository): unknown field "x-cli-option" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.secretToken.properties.secretKeyRef): unknown field "x-cli-help" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.secretToken.properties.secretKeyRef): unknown field "x-cli-option" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.secretToken.properties.secretKeyRef): unknown field "x-cli-type" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.serviceAccountName): unknown field "x-cli-help" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.serviceAccountName): unknown field "x-cli-option" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps]; if you choose to ignore these errors, turn validation off with --validate=false
```

</details>

**What you expected to happen**:

According to the OpenAPIV3 Spec, the [schema object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object) is allowed to carry "Specification Extensions":

> This object MAY be extended with Specification Extensions.

where Specification Extensions are defined as

Field Pattern | Type | Description
-- | -- | --
^x- | Any | Allows extensions to the OpenAPI Schema. The field name MUST begin with x-, for example, x-internal-id. The value can be null, a primitive, an array or an object. Can have any valid JSON format value.

IMO `MAY` here means that those extensions can be specified by everybody and gets just ignored by Kubernetes if given (but still stored).

For us (Knative) it would be super benficient to add some extra meta data to the schema to allow a mapping from flat CLI option to an object within a CR (like the mapping `kn create source github --event-type=watch` to map to the object property in the schema), without "misusing" other existing fields (like 'example' or 'default')

**How to reproduce it (as minimally and precisely as possible)**:

Just apply the given CRD in the example above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:

```
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
```
- OS (e.g: `cat /etc/os-release`):

macOS

**Comment by liggitt** [comment]
> IMO MAY here means that those extensions can be specified by everybody and gets just ignored by Kubernetes if given (but still stored).

Kubernetes currently only stores/serves info in the schema it understands. Preserving/serving arbitrary vendor extensions could be considered. Doing so would allow published openapi schemas to diverge from built-in schemas in arbitrary ways, which doesn't seem great, but it would be good to hear more potential use cases.

cc @sttts

**Comment by rhuss** [comment]
The main use cases I see is for UI and tooling metadata which makes sense only in the context of this tooling (which would have some kind of fallback if the custom extensions are not given):

* Helping Web-UI with hints for the ui layout (`x-web-dropbox`, `x-web-radiobutton`, ...)
* Clustering parts of the schema to a single managed element, like the typical specification for resources with a special (combined) UI element as in 

```yaml
         resources:
              x-ui-type: resource-box
              properties:
                limits:
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                  type: object
                requests:
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                  type: object
              type: object
```
* Allow a flat mapping for CLI options to deeply nested elements within the schema, and adding extra meta-data which is helpful for the CLI tool, like CLI specific help messages (that's our use case):

```yaml
secretToken:
  x-cli-option: "secret-token"
  x-cli-type: "map-selector"
  x-cli-help: "GitHub secret token. The value of this option is the name of a secret and key within secret to GitHub access, dot separated (e.g. --secret-token=mygithubsecret.mykey) "
  type: object
```

* Options how to output certain fields. E.g. `additionalPrinterColumns` could have been easily implemented with kubectl custom attributes, too, like `x-kubectl-column-description`, `x-kubectl-column-format`, `x-kubectl-column-name`, ... The benefit would be that you don't have to calculate a JSON path (which might be fragile because might forget to update it if a property moves within the schema) but just put these annotations directly where the properties are defined. It's also much nicer for a user to see that column definition directly on those fields.
* Meta processing instructions for tooling in general, like the one for kubectl which is now hardcoded with `additionalPrinterColumns` but available for any tooling.
