### ISSUE TITLE
Liveness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by deepaksood619** [kubernetes/kubernetes#82987]
**What happened**:
I am getting `Liveness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded` error using execAction liveness probe Also the container is not restarted when this fails.
```
livenessProbe:
            exec:
              command:
                - curl
                - -XGET
                - http://10.8.0.1:9101/
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
```

**What you expected to happen**:
Liveness probe failed after failureThreshold and pod restarted

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: zenalytix
  name: zenalytix
  namespace: zenalytix
spec:
  serviceName: zenalytix
  replicas: 1
  selector:
    matchLabels:
      name: zenalytix
  template:
    metadata:
      labels:
        name: zenalytix
    spec:
      containers:
        - name: zenalytix
          image: gcr.io/archiver/test:0.0.1
          imagePullPolicy: IfNotPresent
          workingDir: /root/zenalytix
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          command:
            - /bin/bash
            - -c
            - |
              mkdir -p /dev/net && mknod /dev/net/tun c 10 200 && chmod 600 /dev/net/tun && openvpn --config Docker/OpenVPN/mqtt-driver.ovpn & disown &&
              gunicorn zenalytix.wsgi -b 0.0.0.0:9104 --workers 2 -k gthread --threads 16 --timeout 300 --log-level info --limit-request-line 8190 --access-logfile -
          ports:
            - containerPort: 9104
          envFrom:
            - configMapRef:
                name: zenalytix-configmap
          volumeMounts:
            - mountPath: /root/zenalytix
              name: zenalytix-data
          livenessProbe:
            exec:
              command:
                - curl
                - -XGET
                - http://10.8.0.1:9101/
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
      volumes:
        - name: zenalytix-data
          persistentVolumeClaim:
            claimName: zenalytix-pvc
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Managed Azure Kubernetes Service (AKS) - 1.14.6
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux zenalytix-0 4.15.0-1052-azure #57-Ubuntu SMP Tue Jul 23 19:07:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ealebed** [comment]
We have the same situation with ANY liveness command kind, but not with liveness HTTP request (!!!!!).

E.g., with 
```
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl http://localhost:8080/services/timeout
          failureThreshold: 5
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
```
in logs:
```
...
Oct 11 12:15:52 lpm-rtb-055 containerd[2943]: time="2019-10-11T12:15:52.750175916Z" level=error msg="ExecSync for \"e8c5a50d8910a6fa64367be2b7a1e972086cb304436edcf4bbfc923ba61c5ec0\" failed" error="rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 5s exceeded: context deadline exceeded"
Oct 11 12:15:52 lpm-rtb-055 kubelet[24706]: E1011 12:15:52.750354   24706 remote_runtime.go:351] ExecSync e8c5a50d8910a6fa64367be2b7a1e972086cb304436edcf4bbfc923ba61c5ec0 '/bin/sh -c curl http://localhost:8080/services/timeout' from runtime service failed: rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 5s exceeded: context deadline exceeded
Oct 11 12:15:52 lpm-rtb-055 containerd[2943]: time="2019-10-11T12:15:52.750621068Z" level=info msg="ExecSync for \"e8c5a50d8910a6fa64367be2b7a1e972086cb304436edcf4bbfc923ba61c5ec0\" with command [/bin/sh -c curl http://localhost:8080/services/timeout] and timeout 5 (s)"
Oct 11 12:15:56 lpm-rtb-055 containerd[2943]: time="2019-10-11T12:15:56.598590028Z" level=info msg="ExecSync for \"c307c74027f93dd8ee1a333dac58b3010381d47900bdbf147784d0b81073a548\" with command [cilium status --brief] and timeout 5 (s)"
Oct 11 12:15:56 lpm-rtb-055 containerd[2943]: time="2019-10-11T12:15:56.642762294Z" level=info msg="Finish piping \"stdout\" of container exec \"52099a96bd6c5ee436d55430081f0c70926ab7a46ffbf3f1861f8780c64bc92a\""
Oct 11 12:15:56 lpm-rtb-055 containerd[2943]: time="2019-10-11T12:15:56.642830099Z" level=info msg="Finish piping \"stderr\" of container exec \"52099a96bd6c5ee436d55430081f0c70926ab7a46ffbf3f1861f8780c64bc92a\""
Oct 11 12:15:56 lpm-rtb-055 containerd[2943]: time="2019-10-11T12:15:56.643353886Z" level=info msg="Exec process \"52099a96bd6c5ee436d55430081f0c70926ab7a46ffbf3f1861f8780c64bc92a\" exits with exit code 0 and error <nil>"
Oct 11 12:15:56 lpm-rtb-055 containerd[2943]: time="2019-10-11T12:15:56.651292451Z" level=info msg="ExecSync for \"c307c74027f93dd8ee1a333dac58b3010381d47900bdbf147784d0b81073a548\" returns with exit code 0"
Oct 11 12:15:57 lpm-rtb-055 containerd[2943]: time="2019-10-11T12:15:57.765087326Z" level=info msg="Timeout received while waiting for exec process kill \"4960584d1ab7137d9b8ec1cda7027d5eb9631c316df550febd14d8274fceaf7a\" code 137 and error <nil>"
...
```

or with:
```
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - cat /tmp/live  && /opt/java/openjdk/bin/jcmd 1 VM.version
          failureThreshold: 5
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
```
in log:
```
Oct 10 11:02:17 lpm-rtb-011 containerd[2929]: time="2019-10-10T11:02:17.197069769Z" level=error msg="ExecSync for \"9653ce99f2077028784b7da866f74cf3ac82e5f02720698eb7598f3456ad2aa1\" failed" error="rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 3s exceeded: context deadline exceeded"
Oct 10 11:02:17 lpm-rtb-011 kubelet[19143]: E1010 11:02:17.197213   19143 remote_runtime.go:351] ExecSync 9653ce99f2077028784b7da866f74cf3ac82e5f02720698eb7598f3456ad2aa1 '/bin/sh -c cat /tmp/live && /opt/java/openjdk/bin/jcmd 1 VM.version' from runtime service failed: rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 3s exceeded: context deadline exceeded
Oct 10 11:02:17 lpm-rtb-011 containerd[2929]: time="2019-10-10T11:02:17.197478679Z" level=info msg="ExecSync for \"9653ce99f2077028784b7da866f74cf3ac82e5f02720698eb7598f3456ad2aa1\" with command [/bin/sh -c cat /tmp/live && /opt/java/openjdk/bin/jcmd 1 VM.version] and timeout 3 (s)"
Oct 10 11:02:18 lpm-rtb-011 containerd[2929]: time="2019-10-10T11:02:18.222720588Z" level=info msg="Timeout received while waiting for exec process kill \"c260445a9ac301fe2cbd8484690496c66a16543e084b31fea31c6481e05ba1b7\" code 137 and error <nil>"
Oct 10 11:02:20 lpm-rtb-011 containerd[2929]: time="2019-10-10T11:02:20.230159197Z" level=info msg="Timeout received while waiting for exec process kill \"94db1a1c60c7c5ad0aef46949b42c219991522efcd388efe0107959ae195d71b\" code 137 and error <nil>"
```

but with:
```
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
```

all works fine

**Comment by ealebed** [comment]
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
```
uname -a
Linux lpm-rtb-055 5.3.1-050301-generic #201909210632 SMP Sat Sep 21 06:34:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by gaopeiliang** [comment]
I also met this problem ,  read this source code , I have found the different between exec probe and http  probe
```
1.   exec probe handle command error, command timeout (exception when exec ) as error probe ,  ignore the result , POD status never change in this  situation

2.  http, tcp  probe handle every error as failed probe ,  change POD status when some error occured 

```
walk around exec command:

1. add timeout in command ,  and command exec timeout must < timeoutSeconds

**Comment by AntonOfTheWoods** [comment]
@deepaksood619 , any chance you could re-open this, a few of us seem to still be having issues

**Comment by jrivers96** [comment]
I'm seeing this too on v1.15.12 EKS.

**Comment by PeteE** [comment]
@jrivers96 - We just had this issue on EKS 1.17 with docker version 19.03.13 (from amazon linux 2 repo).  Reverting back to docker 19.03.6 fixed it for us.  It has something to do with the unix sockets being leaded when `kubelet` uses to talk to `dockerd` to do `exec` probes.

**Comment by gohmc** [comment]
This seems to happen often to pod running on node that was shutdown and restart. Delete and let deploy/ds re-create the pod seems to put probe back on track.

**Comment by jrivers96** [comment]
This is my development cluster and we have a mix of k8s node versions on it, v1.15.11 and v1.15.12

```
This is the v1.15.12-eks
 docker version
Client:
 Version:           19.03.6-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        369ce74
 Built:             Fri May 29 04:01:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       369ce74
  Built:            Fri May 29 04:01:57 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.0
  GitCommit:        09814d48d50816305a8e6c1a4ae3e2bcc4ba725a
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
  
This is the v1.15.11-eks

Client:
 Version:           19.03.6-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        369ce74
 Built:             Fri May 29 04:01:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       369ce74
  Built:            Fri May 29 04:01:57 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by jrivers96** [comment]
I'm noticing that my oldest v1.15.12 boxes have around 5000 sockets while the youngest v1.15.12 boxes  have 1k sockets. That does look like a leak to me.

**Comment by antonakv** [comment]
I have the same issue with k8s v1.15.11 on CentOS Linux 7 (Core) 3.10.0-1127.el7.x86_64. It happens when k8s node virtual machine snapshot is in progress on hypervisor level.

**Comment by antonakv** [comment]
@deepaksood619 please reopen the issue

**Comment by JacobHenner** [comment]
For AWS users who are using Amazon's EKS AMI, it looks like this is due to a containerd compatibility issue. See https://github.com/awslabs/amazon-eks-ami/issues/563 for details.

**Comment by antonakv** [comment]
@JacobHenner I'm using Proxmox with kvm for virtualization. Own cloud. And the case is the same.

**Comment by antonakv** [comment]
This issue is affecting a lot of users and I see a lot of duplicate issues like that are closed without resolution. Come on! Stop doing that.

**Comment by AntonOfTheWoods** [comment]
@antonakv , duplicates of this issue or in general? If this issue, I'd like to know when it gets fixed so I can undo my hack, can you link to a few?

Maybe one of us should create a new "follow-up" ticket?

**Comment by antonakv** [comment]
@AntonOfTheWoods Here you are exactly the same k8s bug. I guess it's related to Golang threading algorithm  https://github.com/kubernetes/kubernetes/issues/54381
and
https://github.com/kubernetes/kubernetes/issues/42164
and external
https://github.com/cri-o/cri-o/issues/1228
and the same in Vmware: https://github.com/vmware/vic/issues/6390

All of them related to VM freeze for taking snapshots.

And keyword in code: https://github.com/kubernetes/kubernetes/search?q=context+deadline+exceeded

**Comment by jrivers96** [comment]
The socket leak I was seeing was related to a containerd version. There is an issue for EKS. This was resolved for us by downgrading containerd. 

https://github.com/awslabs/amazon-eks-ami/issues/563

**Comment by ehashman** [comment]
/reopen
/remove-lifecycle rotten

@jackfrancis to provide more details

**Comment by jackfrancis** [comment]
I can repro this on a cluster running in Azure, using a spec like this:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: five-second-liveness-probe
spec:
  containers:
  - name: five-second-liveness-probe
    image: busybox:1.31.1
    args:
    - /bin/sh
    - -c
    - while true; do sleep 600; done
    livenessProbe:
      exec:
        command: ['sh', '-c', 'sleep 5 && exit 0']
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2
  nodeSelector:
    kubernetes.io/os: linux
```

In other words, we set the timeout (2 seconds above) to be lower than the time the probe command will take (`sleep 5` will always take 5 seconds).

What I observe is that the timeouts are being engaged regularly:

```
$ kubectl describe pod five-second-liveness-probe | grep 'Events:' -A 7
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  107s               default-scheduler  Successfully assigned default/five-second-liveness-probe to k8s-agentpool1-30342830-vmss000001
  Normal   Pulled     106s               kubelet            Container image "busybox:1.31.1" already present on machine
  Normal   Created    106s               kubelet            Created container five-second-liveness-probe
  Normal   Started    106s               kubelet            Started container five-second-liveness-probe
  Warning  Unhealthy  5s (x16 over 95s)  kubelet            Liveness probe errored: command "sh -c sleep 5 && exit 0" timed out
```

But that the pod is never actually restarted as a result of the probe timing out:

```
$ kubectl describe pod five-second-liveness-probe | grep 'Restart Count:'
    Restart Count:  0
```

**Comment by jackfrancis** [comment]
Here is some relevant kubelet bootstrap log data describing the configuration of the cluster that produced the above repro:

https://gist.github.com/jackfrancis/36cdf5bce70abb6e38cb729aff9f79dc

**Comment by gohmc** [comment]
> I can repro this on a cluster running in Azure, using a spec like this:
> 
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   labels:
>     test: liveness
>   name: five-second-liveness-probe
> spec:
>   containers:
>   - name: five-second-liveness-probe
>     image: busybox:1.31.1
>     args:
>     - /bin/sh
>     - -c
>     - while true; do sleep 600; done
>     livenessProbe:
>       exec:
>         command: ['sh', '-c', 'sleep 5 && exit 0']
>       initialDelaySeconds: 5
>       periodSeconds: 5
>       timeoutSeconds: 2
>   nodeSelector:
>     kubernetes.io/os: linux
> ```
> 
> In other words, we set the timeout (2 seconds above) to be lower than the time the probe command will take (`sleep 5` will always take 5 seconds).
> 
> What I observe is that the timeouts are being engaged regularly:
> 
> ```
> $ kubectl describe pod five-second-liveness-probe | grep 'Events:' -A 7
> Events:
>   Type     Reason     Age                From               Message
>   ----     ------     ----               ----               -------
>   Normal   Scheduled  107s               default-scheduler  Successfully assigned default/five-second-liveness-probe to k8s-agentpool1-30342830-vmss000001
>   Normal   Pulled     106s               kubelet            Container image "busybox:1.31.1" already present on machine
>   Normal   Created    106s               kubelet            Created container five-second-liveness-probe
>   Normal   Started    106s               kubelet            Started container five-second-liveness-probe
>   Warning  Unhealthy  5s (x16 over 95s)  kubelet            Liveness probe errored: command "sh -c sleep 5 && exit 0" timed out
> ```
> 
> But that the pod is never actually restarted as a result of the probe timing out:
> 
> ```
> $ kubectl describe pod five-second-liveness-probe | grep 'Restart Count:'
>     Restart Count:  0
> ```

try return a non-zero value, this should trigger kubelet to terminate and restart according to the restartPolicy.

```
livenessProbe:
    exec:
       command: ['sh', '-c', 'sleep 5 && exit 0']  <=== exit 1
```

**Comment by jackfrancis** [comment]
@gohmc Whether or not you `exit 0` or `exit 1` after the five second sleep, it doesn't actually matter. The point is that a 2 second timeout will interrupt the livenessProbe command *before it is allowed to finish*. I in fact observe that when I use your suggestion:

```
$ k describe pod five-second-liveness-probe | grep 'Events:' -A 8
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  2m56s                 default-scheduler  Successfully assigned default/five-second-liveness-probe to k8s-agentpool1-30342830-vmss000000
  Normal   Pulling    2m56s                 kubelet            Pulling image "busybox:1.31.1"
  Normal   Pulled     2m54s                 kubelet            Successfully pulled image "busybox:1.31.1" in 2.210580034s
  Normal   Created    2m54s                 kubelet            Created container five-second-liveness-probe
  Normal   Started    2m54s                 kubelet            Started container five-second-liveness-probe
  Warning  Unhealthy  39s (x21 over 2m39s)  kubelet            Liveness probe errored: command "sh -c sleep 5 && exit 1" timed out
```

Again, the probe timeout is firing (before we ever get to the `&& exit 1` conditional execution), but the pod is not being restarted:

```
$ k describe pod five-second-liveness-probe | grep 'Restart Count:'
    Restart Count:  0
```

If it's not clear, the nastiest side-effect of this behavior is that any nominal monitoring would not detect that anything interesting is going on with that pod:

```
$ k get pods
NAME                         READY   STATUS    RESTARTS   AGE
five-second-liveness-probe   1/1     Running   0          4m20s
```

In fact, the packaged livenessProbe is continually invalidating the health of that container environment (by timing out), but the kubelet is not doing what it's supposed to do (which is to kill that pod + container, and then to request that the scheduler schedule a new pod).

**Comment by gohmc** [comment]
do this and you will get your pod terminate as expected:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: five-second-liveness-probe
spec:
  containers:
  - name: five-second-liveness-probe
    image: busybox:1.31.1
    args:
    - /bin/sh
    - -c
    - while true; do sleep 600; done
    livenessProbe:
      exec:
        command: ['sh', '-c', 'sleep 5 && exit 0']
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2
      **failureThreshold: 3**
  nodeSelector:
    kubernetes.io/os: linux
```

**Comment by jackfrancis** [comment]
@gohmc that is what I did:

```
$ k describe pod five-second-liveness-probe | grep 'Events:' -A 8
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  19m                    default-scheduler  Successfully assigned default/five-second-liveness-probe to k8s-agentpool1-30342830-vmss000000
  Normal   Pulling    19m                    kubelet            Pulling image "busybox:1.31.1"
  Normal   Pulled     19m                    kubelet            Successfully pulled image "busybox:1.31.1" in 2.210580034s
  Normal   Created    19m                    kubelet            Created container five-second-liveness-probe
  Normal   Started    19m                    kubelet            Started container five-second-liveness-probe
  Warning  Unhealthy  4m13s (x148 over 18m)  kubelet            Liveness probe errored: command "sh -c sleep 5 && exit 1" timed out
```

(note the `exit 1` there at the end)

Also:

```
$ k describe pod five-second-liveness-probe | grep 'Liveness:'
    Liveness:       exec [sh -c sleep 5 && exit 1] delay=5s timeout=2s period=5s #success=1 #failure=3
```

**Comment by gohmc** [comment]
Here's the final spec used; reduced time for speedier test to see if the pod actually was terminated:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: five-second-liveness-probe
spec:
  containers:
  - name: five-second-liveness-probe
    image: busybox:1.31.1
    args:
    - /bin/sh
    - -c
    - while true; do sleep 600; done
    livenessProbe:
      exec:
        command: ['sh', '-c', 'sleep 3 && exit 0']
      initialDelaySeconds: 3
      periodSeconds: 3
      timeoutSeconds: 2
      failureThreshold: 1
  nodeSelector:
    kubernetes.io/os: linux
```

Here's a dump of kubectl describe; it was terminated as expected.

```
Name:         five-second-liveness-probe
Namespace:    default
Priority:     0
Node:         <masked>
Start Time:   Wed, 10 Mar 2021 11:18:04 +0800
Labels:       test=liveness
Annotations:  cni.projectcalico.org/podIP: 10.10.58.242/32
              cni.projectcalico.org/podIPs: 10.10.58.242/32
Status:       Running
IP:           10.10.58.242
IPs:
  IP:  10.10.58.242
Containers:
  five-second-liveness-probe:
    Container ID:  docker://dfa7e855c9fce538449caf9c0c6201a908fcd08d034af114ccc0f5c9f94a42b2
    Image:         busybox:1.31.1
    Image ID:      docker-pullable://busybox@sha256:95cf004f559831017cdf4628aaf1bb30133677be8702a8c5f2994629f637a209
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
      -c
      while true; do sleep 600; done
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Wed, 10 Mar 2021 11:22:28 +0800
      Finished:     Wed, 10 Mar 2021 11:23:04 +0800
    Ready:          False
    **Restart Count:  6**
    Liveness:       exec [sh -c sleep 3 && exit 0] delay=3s timeout=2s period=3s #success=1 #failure=1
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-hphlt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-hphlt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-hphlt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  6m21s                  default-scheduler  Successfully assigned default/five-second-liveness-probe to <masked>
  Normal   Pulled     3m55s (x5 over 6m19s)  kubelet            Container image "busybox:1.31.1" already present on machine
  Normal   Created    3m55s (x5 over 6m19s)  kubelet            Created container five-second-liveness-probe
  Normal   Started    3m55s (x5 over 6m18s)  kubelet            Started container five-second-liveness-probe
  Warning  Unhealthy  3m49s (x5 over 6m13s)  kubelet            Liveness probe failed:
  Normal   Killing    3m49s (x5 over 6m13s)  kubelet            Container five-second-liveness-probe failed liveness probe, will be restarted
  Warning  BackOff    67s (x7 over 3m19s)    kubelet            Back-off restarting failed container
```

You probably need to report this to Azure.

**Comment by jackfrancis** [comment]
This does not repro on 1.20.0:

```
    Liveness:       exec [sh -c sleep 5 && exit 0] delay=1s timeout=2s period=3s #success=1 #failure=1
```

```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  28m                   default-scheduler  Successfully assigned default/five-second-liveness-probe to k8s-agentpool1-21281628-vmss000001
  Normal   Pulling    28m                   kubelet            Pulling image "busybox:1.31.1"
  Normal   Pulled     28m                   kubelet            Successfully pulled image "busybox:1.31.1" in 2.264198623s
  Warning  Unhealthy  26m (x4 over 28m)     kubelet            Liveness probe failed:
  Normal   Created    25m (x5 over 28m)     kubelet            Created container five-second-liveness-probe
  Normal   Started    25m (x5 over 28m)     kubelet            Started container five-second-liveness-probe
  Normal   Killing    25m (x5 over 28m)     kubelet            Container five-second-liveness-probe failed liveness probe, will be restarted
  Normal   Pulled     7m57s (x11 over 27m)  kubelet            Container image "busybox:1.31.1" already present on machine
  Warning  BackOff    3m16s (x89 over 25m)  kubelet            Back-off restarting failed container
```

Next step: observe the first released version where this fails.

**Comment by jackfrancis** [comment]
O.K., so after a little break I revisited my test matrix and concluded that this is only happening when the kubelet feature gate `ExecProbeTimeout=false` is configured. So, in other words, what I'm seeing is the previous buggy behavior prior to this fix:

https://github.com/kubernetes/kubernetes/pull/94115

I've done cursory confirmation that the `ExecProbeTimeout=false` configuration seems to just "ignore" timeout enforcement entirely (which is what we want).

For example, a spec like this produces a container that is resilient to the implicit (1 second default) timeout enforcement:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: five-second-liveness-probe
spec:
  containers:
  - name: five-second-liveness-probe
    image: busybox:1.31.1
    args:
    - /bin/sh
    - -c
    - echo hi > /tmp/output.txt; while true; do sleep 10 && echo hi >> /tmp/output.txt; done
    livenessProbe:
      exec:
        command: ['sh', '-c', 'sleep 5 && exit 0']
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2
  nodeSelector:
    kubernetes.io/os: linux
```

As I'd expect, when hopping into that pod container I see a continually growing /tmp/output.txt:

```
$ k exec -it five-second-liveness-probe -- sh
/ # wc -l /tmp/output.txt
88 /tmp/output.txt
/ # sleep 20 && wc -l /tmp/output.txt
91 /tmp/output.txt
/ # 

```

It's annoying/misleading to see this in the pod event logs, but that's clearly why this was fixed!:

```
Warning  Unhealthy  19s (x298 over 15m)  kubelet            Liveness probe errored: command "sh -c sleep 5 && exit 0" timed out
```

I'm going to re-close this issue as I don't think the symptoms I'm observing correlate with the issue originally described 18 or so months ago.
