### ISSUE TITLE
How to use pod overhead in runtimeclass

### ISSUE THREAD

**Issue by liangxianlong** [kubernetes/kubernetes#83054]
I read these links
https://kubernetes.io/docs/concepts/configuration/pod-overhead/
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/
https://github.com/kubernetes/kubernetes/pull/78484

but i also don't know how to use pod overhead in runtimeclass or kata-containers
@egernst
who can give me a yaml file about pod overhead??

**Comment by egernst** [comment]
@liangxianlong -- I am happy to add more documentation, though am wondering if it makes sense as a blog post, showcasing examples? For defining the RuntimeClass, you'll want something like the following:
```
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1beta1
metadata:
    name: kata-qemu
handler: kata-qemu
overhead:
    podFixed:
        memory: "1024"
        cpu: "3"
```

To succeed in registering this, however, you'll need to make sure you enable the feature gate for PodOverhead for kubelet, api-server and the scheduler. When I test locally, I end up modifying the  static manifests for api-server and scheduler, adding the equivalent to the components startup command :
api-server:
```bash
<     - --feature-gates=PodOverhead=true
19c18
<     - --enable-admission-plugins=NodeRestriction,RuntimeClass
---
>     - --enable-admission-plugins=NodeRestriction
```  

scheduler:
```
15d14
<     - --feature-gates=PodOverhead=true
``` 

I usually utilize kubeadm, so for setting the feature gate for kubelet, I do it through a kubeadm config file.  Example:
```---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
-featureGates:
-  PodOverhead: true
```

**Comment by tedyu** [comment]
A blog post on this subject would be helpful.

**Comment by liangxianlong** [comment]
my config.yaml
```yaml
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  kubeletExtraArgs:
    allowed-unsafe-sysctls: "kernel.msg*,kernel.shm.*,net.*"
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.16.0
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
-featureGates:
  -  PodOverhead: true
```
And the i execute
```shell
kubeadm --config config.yaml
```
the results:
```shell
W0925 10:08:31.529562    7005 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubelet.config.k8s.io", Version:"v1beta1", Kind:"KubeletConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "-featureGates"
[init] Using Kubernetes version: v1.16.0
```
Any Suggestion?
@egernst

**Comment by tedyu** [comment]
unknown field "-featureGates"

Have you tried with featureGates without dash ?

**Comment by liangxianlong** [comment]
How to use dash?@tedyu

**Comment by tedyu** [comment]
```
featureGates:
    PodOverhead: true
```

**Comment by liangxianlong** [comment]
```yaml
overhead:
    podFixed:
        memory: "1024"
        cpu: "3"
```
Does this means that the pod can maximum useuse 1024Mb memory  and 3 cpu?
@egernst @tedyu

**Comment by liangxianlong** [comment]
My kata-containers config:
```toml
# if enabled, the runtime will add all the kata processes inside one dedicated cgroup.
# The container cgroups in the host are not created, just one single cgroup per sandbox.
# The sandbox cgroup is not constrained by the runtime
# The runtime caller is free to restrict or collect cgroup stats of the overall Kata sandbox.
# The sandbox cgroup path is the parent cgroup of a container with the PodSandbox annotation.
# See: https://godoc.org/github.com/kata-containers/runtime/virtcontainers#ContainerType
sandbox_cgroup_only=true
```
The runtimeclass yaml:
```yaml
apiVersion: node.k8s.io/v1beta1  # RuntimeClass is defined in the node.k8s.io API group
kind: RuntimeClass
metadata:
  name: kata-containers  # The name the RuntimeClass will be referenced by
  # RuntimeClass is a non-namespaced resource
handler: kata
overhead:
    podFixed:
        memory: "1024"
        cpu: "3"
```
The kubelet,kube-apiserver,and kube-scheduler
```shell
kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2019-09-25 11:27:28 CST; 5h 23min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 17941 (kubelet)
    Tasks: 27
   Memory: 48.5M
   CGroup: /system.slice/kubelet.service
           └─17941 /usr/bin/kubelet --kubeconfig=/etc/kubernetes/kubelet.conf --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --cert-dir=/etc/kubernetes/pki --feature-gates=PodOverhead=true --pod-manifest-path=/etc/kubernetes/manifests --pod-infra-container-image=k8s.gcr.io/pause:3.1 --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock
```
```shell
kube-apiserver --feature-gates=PodOverhead=true --enable-admission-plugins=NodeRestriction,RuntimeClass --enable-admission-plugins=NodeRestriction --advertise-address=10.74.121.69 --allow-privileged=true --authorization-mode=Node,RBAC --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
```
```shell
kube-scheduler --feature-gates=PodOverhead=true --authentication-kubeconfig=/etc/kubernetes/scheduler.conf --authorization-kubeconfig=/etc/kubernetes/scheduler.conf --bind-address=127.0.0.1 --kubeconfig=/etc/kubernetes/scheduler.conf --leader-elect=true
```
My pod yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-two
spec:
  runtimeClassName: kata-containers
  containers:
  - name: busybox-1
    image: busybox
    stdin: true
    tty: true
    imagePullPolicy: IfNotPresent
  - name: busybox-2
    image: busybox
    stdin: true
    tty: true
    imagePullPolicy: IfNotPresent
```
When i execute ```kubectl apply -f busybox-two.yaml```, i don't see any changes in cpu cgroup and memory cgroup?
@egernst @tedyu
