### ISSUE TITLE
kubectl wait on arbitrary jsonpath

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#83094]
kubectl currently can `wait` on `condition` or `delete`
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/wait/wait.go#L110-L111

In addition to the above, can we please add the ability to wait on high level summary that we have `phase`?
https://cs.k8s.io/?q=Phase%20.*json%3A%22phase&i=nope&files=&repos=kubernetes/kubernetes

why? Looks like we are not adding conditions anymore, so CRD(s) seem to have picked up the `phase` at least. Will help avoid having to write loops like this ( from https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/175/files )
```
  # Wait till all machines are running (bail out at 30 mins)
  attempt=0
  while true; do
    kubectl get machines --kubeconfig=$(kind get kubeconfig-path --name="clusterapi")
    read running total <<< $(kubectl get machines --kubeconfig=$(kind get kubeconfig-path --name="clusterapi") \
      -o json | jq -r '.items[].status.phase' | awk '/running/ {count++} END{print count " " NR}') ;
    if [[ $total == "5" && $running == "5" ]]; then
      return
    fi
    timestamp=$(date +"[%H:%M:%S]")
    if [ $attempt -gt 180 ]; then
      echo "cluster did not start in 30 mins ... bailing out!"
      exit 1
    fi
    echo "$timestamp Total machines : $total / Running : $running .. waiting for 10 seconds"
    sleep 10
    attempt=$((attempt+1))
  done
```

Another example is : https://github.com/kubernetes-incubator/kube-aws/blob/master/contrib/cluster-backup/restore.sh#L80-L86

**Comment by liggitt** [comment]
> Looks like we are not adding conditions anymore

The reports of conditions' death have been greatly exaggerated :)

Rather than a specific phase field, a jsonpath evaluation and expected value might be interesting

**Comment by dims** [comment]
something like the following?

```
wait --for='jsonpath={.status.phase == "Running"'} 
wait --for='jsonpath='{.items..status.phase == "Ready"}
```

**Comment by dims** [comment]
guess what i want to see is ... wait until all the items reached the phase (or) wait until the single item reached the phase i specified. right?

**Comment by dims** [comment]
cc @hpandeycodeit

**Comment by dims** [comment]
@deads2k Can you please suggest some command lines that will be useful for a "generic wait"?

**Comment by deads2k** [comment]
Conditions are generally better than phase.  Phases were a mistake in our original pod implementation because they implied a single unified state machine, but we found that instead we had multiple orthogonal states that are better represented as separate conditions.

You could try `kubectl wait --for=jsonpath=.status.phase=wish-i-was-a-condition`

**Comment by aparedero** [comment]
@deads2k But how can you capture when a pod is up and running, but not ready?
Just a small example with [Hashicorp Vault](https://github.com/hashicorp/vault) Helm and  this being managed with Ansible.

Putting Ansible aside this helm manifest deploys a pod with Vault but it won't be ready until the application has been configured; so is 0/1 but in running state (due to a readiness probe).

```bash
NAME      READY   STATUS    RESTARTS   AGE
vault-0   0/1     Running   0          3m55s
```
Currently tt's required to execute some kubectl exec commands into this pod to become ready.

As I'm automating the process with Ansible I've tried creating a task with the bare command 
 `kubectl wait --for=condition=Initialized pod/vault-0 --timeout=90s` but its not working because the initalized state does not reflect the pod is still being created, so the "phase" is the most accured state to wait.  

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-11-04T10:54:55Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-11-04T10:54:55Z"
    message: 'containers with unready status: [vault]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-11-04T10:54:55Z"
    message: 'containers with unready status: [vault]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-11-04T10:54:55Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: vault:1.2.2
    imageID: ""
    lastState: {}
    name: vault
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: ContainerCreating
  hostIP: 172.16.16.97
  phase: Pending
  qosClass: BestEffort
  startTime: "2019-11-04T10:54:55Z"
```
As a workaround, I'm handling the error of not ready adding retries in Ansible, but I think it could be interesting having more control from K8s
