### ISSUE TITLE
Ephemeral storage doesn't account for deleted files with open handles

### ISSUE THREAD

**Issue by aermakov-zalando** [kubernetes/kubernetes#83107]
**What happened**:

A pod that creates large files in the ephemeral storage (either in an explicit `emptyDir` volume or just by writing to the container's filesystem) and then deletes them while keeping an open file handle will cause serious stability issues on the node while making it very hard for an operator to find out that it's the root cause. From kubelet's perspective the pod's `ephemeral-storage` usage will be close to zero, so it'll go and evict other pods first while the offending pod continues using more and more disk space. None of the reported metrics (e.g. cadvisor's container_fs_usage_bytes) will report this pod's usage correctly, so the only way to even find it is manually running `lsof -a +L1` on the node. This also prevents Ephemeral Storage limits from working correctly, making it impossible for cluster operators to use those to protect nodes from faulty applications.

**What you expected to happen**:

A pod's filesystem usage is accounted for correctly, even if disk space is used by deleted files. When the node runs out of disk space, the offending pod is evicted.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a pod that'll create large files, delete them while still keeping the handle open and writing no logs or any other data. Wait until the node runs out of disk space. Observe that `kubelet` tries to evict all other pods instead (since they'll consume non-zero space for their logs), then gives up and the node dies completely.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Cloud provider or hardware configuration: [kubernetes-on-aws](https://github.com/zalando-incubator/kubernetes-on-aws/)
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`): 4.15.0-1048-aws

**Comment by aermakov-zalando** [comment]
@kubernetes/sig-node-bug

**Comment by aermakov-zalando** [comment]
@kubernetes/sig-node-bugs

**Comment by psimaj** [comment]
I will look into this issue.

**Comment by RobertKrawitz** [comment]
See https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20180906-quotas-for-ephemeral-storage.md (which is currently in alpha). This uses XFS quotas (which also work on suitably enabled ext4fs filesystems) to monitor storage for emptydir volumes.  I'd like to graduate this to beta, if for no other reason than this.

Extending this beyond emptydir volumes will probably require similar changes to cAdvisor.

**Comment by aermakov-zalando** [comment]
@RobertKrawitz This happens with the Docker writable layer as well, and I don't think that one even supports limits.

**Comment by Ottovsky** [comment]
I created PoC for this bug https://github.com/Ottovsky/keep-open-deleted , I am surprised how important the impact it can have on the node, the pods are actually randomly evicted from it.

**Comment by ehashman** [comment]
/remove-lifecycle frozen

need someone to confirm this still affects HEAD and then we can triage

**Comment by szuecs** [comment]
@ehashman at least it is also in v1.20.8, that we run (@aermakov-zalando and @mikkeloscar are in the same team like me)

**Comment by ehashman** [comment]
/remove-lifecycle rotten
as this was confirmed on a supported version, 1.20.x

/help

**Comment by ehashman** [comment]
Updated KEP link from above: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1029-ephemeral-storage-quotas

**Comment by BenTheElder** [comment]
cc @pacoxu seems like the related keep is ongoing? https://github.com/kubernetes/enhancements/issues/1029#issuecomment-1004592859

**Comment by pacoxu** [comment]
> cc @pacoxu seems like the related keep is ongoing? [kubernetes/enhancements#1029 (comment)](https://github.com/kubernetes/enhancements/issues/1029#issuecomment-1004592859)

The feature is still alpha. I think with the LocalStorageCapacityIsolationFSQuotaMonitoring enabled, user will meet less problems like this. I may try to reproduce it with https://github.com/Ottovsky/keep-open-deleted to check if the feature is stable.

/assign

**Comment by pacoxu** [comment]
I tried the yaml below. The pod can be evicted by the eviction manager.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2022-04-12T07:10:26Z"
  generation: 7
  labels:
    app: keepopendeleted
  name: keepopendeleted
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keepopendeleted
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keepopendeleted
    spec:
      containers:
      - args:
        - -location
        - /tmp
        image: ottovsky/keepopendeleted
        name: keepopendeleted
        resources:
          limits:
            ephemeral-storage: 4Gi
          requests:
            ephemeral-storage: 2Gi
        volumeMounts:
        - mountPath: /tmp
          name: ephemeral
      volumes:
      - emptyDir: {}
        name: ephemeral
```
If the feature gate is enabled, the eviction will happen immediately. 
```
keepopendeleted-546f764df4-s547p   1/1     Running                  0          5s
keepopendeleted-546f764df4-s547p   1/1     Evicted                  0          33s
keepopendeleted-546f764df4-ck85n   0/1     Pending                  0          0s
keepopendeleted-546f764df4-ck85n   0/1     Pending                  0          0s
keepopendeleted-546f764df4-ck85n   0/1     ContainerCreating        0          0s
keepopendeleted-546f764df4-ck85n   0/1     ContainerCreating        0          1s
keepopendeleted-546f764df4-s547p   1/1     Evicted                  0          35s
keepopendeleted-546f764df4-s547p   0/1     ContainerCreating        1          36s
keepopendeleted-546f764df4-s547p   0/1     ContainerStatusUnknown   1          36s
keepopendeleted-546f764df4-ck85n   1/1     Running                  0          6s
keepopendeleted-546f764df4-ck85n   1/1     Evicted                  0          24s
keepopendeleted-546f764df4-pmz9v   0/1     Pending                  0          0s
keepopendeleted-546f764df4-pmz9v   0/1     Pending                  0          0s
keepopendeleted-546f764df4-pmz9v   0/1     ContainerCreating        0          0s
keepopendeleted-546f764df4-ck85n   1/1     Evicted                  0          25s
keepopendeleted-546f764df4-pmz9v   0/1     ContainerCreating        0          1s
keepopendeleted-546f764df4-ck85n   0/1     ContainerCreating        1          26s
keepopendeleted-546f764df4-ck85n   0/1     ContainerStatusUnknown   1          26s
keepopendeleted-546f764df4-pmz9v   1/1     Running                  0          6s
keepopendeleted-546f764df4-pmz9v   1/1     Evicted                  0          33s
keepopendeleted-546f764df4-m4h2c   0/1     Pending                  0          0s
keepopendeleted-546f764df4-m4h2c   0/1     Pending                  0          0s
keepopendeleted-546f764df4-m4h2c   0/1     ContainerCreating        0          0s
keepopendeleted-546f764df4-m4h2c   0/1     ContainerCreating        0          2s
keepopendeleted-546f764df4-pmz9v   1/1     Evicted                  0          35s
keepopendeleted-546f764df4-pmz9v   0/1     Completed                0          35s
keepopendeleted-546f764df4-m4h2c   1/1     Running                  0          5s
```

If the feature gate is disabled, the eviction will happen about 3 minutes later.
```
keepopendeleted-546f764df4-tcpk2   1/1     Running             0          11s
keepopendeleted-546f764df4-tcpk2   1/1     Evicted             0          3m25s
keepopendeleted-546f764df4-tcpk2   1/1     Evicted             0          3m27s
keepopendeleted-546f764df4-tcpk2   0/1     Completed           0          3m27s
``` 

@aermakov-zalando would you try the LocalStorageCapacityIsolationFSQuotaMonitoring=true in kubelet config.yaml?
