### ISSUE TITLE
DNS resolution fails when EndpointSlice is enabled on 1.16

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#83212]
**What happened**:

When I run kubernetes 1.16, everything is working well:

```
kind create cluster --image gcr.io/istio-testing/kind-node:v1.16.0
<inside a pod>
$ curl google.com
 ... Success ...
$ nslookup google.com
... Success ...
```

Then I try to enable EndpointSlice:

```
kind create cluster --image gcr.io/istio-testing/kind-node:v1.16.0 --config endpointslice.yaml
$ curl google.com
curl: (6) Could not resolve host
$ curl other-service.default.svc
curl: (6) Could not resolve host
```

and DNS resolution seems to break

where `endpointslice.yaml` is 

<details>

```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "EndpointSlice=true"
      "runtime-config": "discovery.k8s.io/v1alpha1=true"
  controllerManager:
    extraArgs:
      "controllers": "*,-endpoint,endpointslice"
```
</details>

**What you expected to happen**:

DNS resolution to work with EndpointSlice

**How to reproduce it (as minimally and precisely as possible)**:

Repro given above

**Anything else we need to know?**:

It is very possible that I just configured things wrong. If this is the case pointers on the right way to get this setup are appreciated

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration: kind
