### ISSUE TITLE
Scheduler does not prioritize volume sizes

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#83323]
**What happened**:
With `volumeBindingMode: WaitForFirstConsumer`, scheduler does not take PV sizes into account when scheduling a Pod that can run anywhere and PVC that can find several available pre-provisioned PVs with various sizes.

**What you expected to happen**:
Scheduler tries to find as small PV as possible.

**How to reproduce it (as minimally and precisely as possible)**:
Let's have these PVs (each on a different node):
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /srv/vol1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-10-0-134-206

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /srv/vol2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-10-0-169-29
```

A PVC asking for 1GiB is randomly bound to `vol1` or `vol2`. It should prefer `vol2`.

**Anything else we need to know?**:
[Volume topology scheduling design](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/volume-topology-scheduling.md)  mentions `PrioritizeVolumes` priority function, it seems it has never been implemented.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.1
