### ISSUE TITLE
NetworkPolicy: Admin-defined bounds on NetworkPolicy (was: Egress policy for all namespaces)

### ISSUE THREAD

**Issue by jceresini** [kubernetes/kubernetes#83400]
**What would you like to be added**:
I would like to be able to define a cluster-wide NetworkPolicy for egress traffic.

**Why is this needed**:
This would simplify things like blocking containers from accessing services, ports, etc. without blocking the traffic for the nodes. An example use case (the one I'm interested in) is a universal way to prevent containers in a cluster from talking to the cloud metadata service. GKE has a way to block traffic to the metadata service (or at least conceal some data), EKS recommends specific IPTables rules.

I realize some features require access to the metadata service (ex: GKE Workload Identity), but I'm still interested in having the ability to block it entirely using something like this:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-cloud-metadata-service
  namespace: some-namespace # but I'd like to apply it cluster-wide
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except: [ 169.254.169.254/32 ]
```

Related docs:
GKE: https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata
EKS: https://docs.aws.amazon.com/eks/latest/userguide/restrict-ec2-credential-access.html
