### ISSUE TITLE
In Windows, configMap or Secret volumes might overwrite existing dir in container

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#83511]
When mounting configMap or secret volumes into containers, if the mountPath points to an existing dir in container image, the resulting behavior is different between Linux and Windows

- In linux, if the mountPath is an existing dir, container will fail to start

- In windows, container can start successfully, and the existing dir will be overwritten by configMap or secret volume 

The following is an example of yaml file

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  config: |
    labels:
      - "app"
      - "owner"

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod222
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
      - name: config-volume
        mountPath: /var
  volumes:
    - name: config-volume
      configMap:
        name: test-config
```
