### ISSUE TITLE
increased the pvc from 1G to 2G，but it seams the storage still not enough

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#83600]
```
[root@dev7 ~]# kubectl get pvc -n harbor
NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-harbor-harbor-redis-0               Bound    pvc-c122ef23-5555-4c60-b8be-4e98e4743760   1Gi        RWO            rook-block     19d
database-data-harbor-harbor-database-0   Bound    pvc-3d165940-52ee-45d4-acad-9b4531a17c76   2Gi        RWO            rook-block     19d
harbor-harbor-chartmuseum                Bound    pvc-48ce7253-dfea-4b8e-8163-21b48c10e1b4   5Gi        RWO            rook-block     19d
harbor-harbor-jobservice                 Bound    pvc-e177fe36-24b2-4c20-8362-4b9d81da7f8d   1Gi        RWO            rook-block     19d
harbor-harbor-registry                   Bound    pvc-453f1db3-f36b-4d2f-92a0-a211cdfbb068   5Gi        RWO            rook-block     19d
[root@dev7 ~]# kubectl logs harbor-harbor-database-0 -n harbor
FATAL:  could not write lock file "postmaster.pid": No space left on device
```

how can I mount the pv to my local directory,to see the content in the pv

```
volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        app: harbor
        chart: harbor
        heritage: Helm
        release: harbor
      name: database-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: rook-block
      volumeMode: Filesystem
    status:
      phase: Pending

here in the statefulset the storage is still 1G,bug I cannot change this value
```

I delete the statefulset，chang the capacity ，still show the same error？
how to solve this，anynoe can help？

I have manually resize the ceph rbd size ，still have problem

```
root@rook-tools:/# rbd diff  replicapool/pvc-3d165940-52ee-45d4-acad-9b4531a17c76   | awk '{ SUM += $2 } END { print SUM/1024/1024 " MB" }'         
1009.54 MB
root@rook-tools:/# rbd  info replicapool/pvc-3d165940-52ee-45d4-acad-9b4531a17c76                                                                     
rbd image 'pvc-3d165940-52ee-45d4-acad-9b4531a17c76':
        size 4096 MB in 1024 objects
        order 22 (4096 kB objects)
        block_name_prefix: rbd_data.107d643c9869
        format: 2
        features: layering
        flags: 
        create_timestamp: Wed Sep 18 07:01:39 2019
```
