### ISSUE TITLE
SELinux Volumes not relabeled in 1.16, test coverage of volume relabeling is lacking

### ISSUE THREAD

**Issue by shanesiebken** [kubernetes/kubernetes#83679]
**What happened**:
After upgrading from kubelet 1.15 -> 1.16, volumes are no longer relabeled as container_file_t for selinux, causing most pods to fail.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
* Run a kubernetes cluster on 1.15.[0-3]. 
* Create a pod with a secret, configmap, or with provisioned storage (ebs-csi-driver). 
* Find that file on disk of the node, and observe it is labeled with the file type container_file_t and the pod is able to read it.
* Upgrade the kubelet to 1.16
* Delete the pod, and observe it fail on launch. Find the file on disk and see it labeled tmpfs_t or unlabeled_t for configmap/secret and provisioned volumes, respectively.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15 / 1.16
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): RHEL 7.7
- Kernel (e.g. `uname -a`): 3.10.0-1062.1.1.el7.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): N/A
- Others:

**Comment by shanesiebken** [comment]
@kubernetes/sig-storage-bugs

**Comment by gnufied** [comment]
Is selinux enabled for docker?  Can you paster output of :

```docker info | grep 'Security Options'```

also `docker version`

**Comment by gnufied** [comment]
Also please paste YAML of one or more pods which are affected by this. Thank you!

**Comment by shanesiebken** [comment]
Security Options -
```
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
```
Perhaps of note here, we do *not* change the  /etc/docker/seccomp.json installed by docker, and `rpm --verify docker` confirms we don't make changes to that file.

Docker version:
```
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.x86_64
 Go version:      go1.10.8
 Git commit:      7f2769b/1.13.1
 Built:           Fri Aug  2 10:19:53 2019
 OS/Arch:         linux/amd64
```
Client and server blocks match.

Pod yaml incoming

**Comment by shanesiebken** [comment]
To clarify, do you want a runnable "minimum reproducible" pod.yaml, or is it more informational? If the latter, I have a pod that breaks and I'm working on the yaml for that, removing sensitive information, etc. If the former, I'll need to spend a few minutes getting a minimal reproduction with busybox or somesuch.

**Comment by gnufied** [comment]
I need full pod's yaml that is not working. i.e - generated full YAML.

**Comment by shanesiebken** [comment]
Hi, I'm sorry I haven't had a chance to follow up with this ticket. I will get some pod yaml attached early next week. Thank you for following up.

**Comment by superseb** [comment]
I think I'm seeing the same thing, to reproduce, use the following resource YAML:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm
---
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: ubuntu
      command: [ "/bin/sh", "-c", "ls -laZ /etc/config/" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: special-config
  restartPolicy: Never
```

On k8s v1.15.5 (hyperkube)

```
$ kubectl logs -f dapi-test-pod
total 0                                              
drwxrwxrwx. 3 root root system_u:object_r:container_file_t:s0:c292,c738 100 Oct 25 12:15 .
drwxr-xr-x. 1 root root system_u:object_r:container_file_t:s0:c292,c738  20 Oct 25 12:15 ..
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0:c292,c738  47 Oct 25 12:15 ..2019_10_25_12_15_51.148820422
lrwxrwxrwx. 1 root root system_u:object_r:container_file_t:s0:c292,c738  31 Oct 25 12:15 ..data -> ..2019_10_25_12_15_51.148820422
lrwxrwxrwx. 1 root root system_u:object_r:container_file_t:s0:c292,c738  20 Oct 25 12:15 SPECIAL_LEVEL -> ..data/SPECIAL_LEVEL
lrwxrwxrwx. 1 root root system_u:object_r:container_file_t:s0:c292,c738  19 Oct 25 12:15 SPECIAL_TYPE -> ..data/SPECIAL_TYPE
```

On k8s 1.16.2 (hyperkube)

```
$ kubectl logs -f dapi-test-pod
ls: cannot access '/etc/config/SPECIAL_LEVEL': Permission denied
ls: cannot access '/etc/config/SPECIAL_TYPE': Permission denied
ls: cannot access '/etc/config/..data': Permission denied
total 0
drwxrwxrwx. 3 root root system_u:object_r:container_var_lib_t:s0       100 Oct 25 12:18 .
drwxr-xr-x. 1 root root system_u:object_r:container_file_t:s0:c67,c625  20 Oct 25 12:18 ..
drwxr-xr-x. 2 root root system_u:object_r:container_var_lib_t:s0        47 Oct 25 12:18 ..2019_10_25_12_18_44.181623127
l?????????? ? ?    ?                                                 0   ?            ? ..data
l?????????? ? ?    ?                                                 0   ?            ? SPECIAL_LEVEL
l?????????? ? ?    ?                                                 0   ?            ? SPECIAL_TYPE
```

@shanesiebken Are you in Enforcing mode (`getenforce`) ?
