### ISSUE TITLE
VolumeMount MountPath does not accept colon character

### ISSUE THREAD

**Issue by militarpancho** [kubernetes/kubernetes#83781]
**What happened**:

Using volumeMounts with a mountPath to a folder  with a colon character is not allowed, in spite of the fact that docker allows doing it via --mount syntax

**What you expected to happen**:

A mountPath should contain this type of characters 

**How to reproduce it (as minimally and precisely as possible)**:

Reproducing it is possible puting a colon in the mountPath field of a volumeMount

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by militarpancho** [comment]
@kubernetes/sig-storage-bugs

**Comment by zouyee** [comment]
Please supply manifest to reproduce the issue.

**Comment by militarpancho** [comment]
This is an example manifest
`apiVersion: v1
kind: Pod
metadata:
  name: test-volume
spec:
  containers:
  - image: docker:19.03-dind
    name: dind
    volumeMounts:
    - mountPath: /etc/docker/certs.d/registry.local:5000
      name: registry-certs
  volumes:
  - name: registry-certs
    secret:
      secretName: registry-certs
`

**Comment by zouyee** [comment]
cc @justinsb

**Comment by gnufied** [comment]
This is a known issue and stems from the issue with CRI (at least initially) not supporting volumes with `:` in it, because `:` is used to separate volumes -  https://github.com/moby/moby/issues/8604

The current solution seems to be to use explicit `source=` and `destination=` fields but we have to verify if this works for all container-runtimes and is not just docker thing.

**Comment by militarpancho** [comment]
Okey, thanks for the clarification!, is there a pr or workaround coming for this issue, or it's not contemplated in the roadmap?

**Comment by artificial-aidan** [comment]
For anyone who runs into this issue. Here is the workaround I found.

```
    volumes:
    - name: certs
      secret:
        items:
        - key: ca.crt
          path: my-registry:443/ca.crt
        secretName: registry-ca
    volumeMounts:
    - mountPath: /etc/docker/certs.d
      name: certs
      readOnly: true
```
