### ISSUE TITLE
PriorityQueue is far from FIFO for same priority Pods

### ISSUE THREAD

**Issue by yqwang-ms** [kubernetes/kubernetes#83834]
**What happened**:
By default, user Pod does not have priority (i.e. 0), so usually, they expect **FIFO** scheduling in this case, even if for the PriorityQueue.
In this requirement, the **FI(First In)** should be determined by the [Pod CreationTimestamp instead of last queued time](https://github.com/kubernetes/kubernetes/issues/83826), i.e. the **user expect longest Pending Pod since creation should be scheduled first in most cases**.
However, we found that the PriorityQueue is far from FIFO, i.e. >40% Pods cut in line, see **How to reproduce it** for more details.

**What you expected to happen**:
The PriorityQueue should be **near FIFO** for same priority Pods, i.e. <5% Pods cut in line.

**How to reproduce it (as minimally and precisely as possible)**:
1. Cluster Setup: 7 Nodes each has 4 total free GPUs
2. Submit ReplicaSet RSX, which contains 28 Pods, and each Pod request 1 GPU and just sleep forever in its command.
3. Wait all Pods in RSX is running.
4. Submit Job JA, which contains 200 Pods to run to complete, and each Pod request 1 GPU and just sleep 20s in its command.
5. Wait all Pods in JA is queued in scheduler. (Because no free GPUs, so all Pods in JA are pending)
6. Submit Job JB, which has the same spec with JA except for its name JB is different with JA. (Here, we ensures JB is totally later than JA)
7. Delete ReplicaSet RSX, so JA and JB will compete to schedule.

We obeserves below result consistently:
| Timestamp (normalized) | JA completed Pods | JB completed Pods| Pods cut in line rate|
|:---- |:---- |:---- |:---- |
| 1 | 72 | 56 | 56/200 |
| 2 | 108 | 76 | 76/200 |
| 3 | 138 | 101 | 101/200 |
| 4 | 169 | 131 | 131/200 |
| 5 | 182 | 153 | 153/200 |
In avarage, >40% Pods cut in line.

**Anything else we need to know?**:
This issue can be fixed, i.e. cut in line rate decreased <5%, after we used the **Pod creation time instead of the last queued time to sort Pod for the same priority**, as suggested in https://github.com/kubernetes/kubernetes/issues/83826, and fixed by https://github.com/kubernetes/kubernetes/pull/83835.

After the fix https://github.com/kubernetes/kubernetes/pull/83835, we obeserves below result consistently (for the same repro steps above):
| Timestamp (normalized) | JA completed Pods | JB completed Pods| Pods cut in line rate|
|:---- |:---- |:---- |:---- |
| 1 | 160 | 1| 1/200 |
| 2 | 181 | 1| 1/200 |
| 3 | 191 | 3| 3/200 |
| 4 | 194 | 21| 21/200 |
In avarage, <5% Pods cut in line.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Scheduler Spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - image: gcr.io/google_containers/kube-scheduler:v1.14.2
    name: kube-scheduler
    command:
    - /usr/local/bin/kube-scheduler
    - --master
    - 10.151.41.16:8080
    - --leader-elect=false
    - --feature-gates=PodPriority=true
    - --v=4
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1
    resources:
      requests:
        memory: "1Gi"
        cpu: "2000m"
```
- Cloud provider or hardware configuration:
`on-premise
`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

```
- Kernel (e.g. `uname -a`):
`Linux stcal-177 4.15.0-1060-azure #65-Ubuntu SMP Wed Sep 18 08:55:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
