### ISSUE TITLE
Kubernetes 1.10.11 or Kubernetes 1.15.3 service.spec.externalTrafficPolicy does not get real client IP

### ISSUE THREAD

**Issue by mbelchin** [kubernetes/kubernetes#83900]
**What happened**:

Kubernetes 1.10.11 does not display on my nginx pod the source client IP only displays the internal cluster IP.

I've used the new `service.spec.externalTrafficPolicy: Local` on my Service yaml.

**What you expected to happen**:

Shows the source client IP.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 443
    nodePort: 30443
    protocol: TCP
    name: https
  selector:
    app: nginx

``` 

**Anything else we need to know?**:

In a previous version, Kubernetes 1.6.1 the same Service yaml but with the old fashion annotations `service.beta.kubernetes.io/external-traffic: OnlyLocal` worked perfectly for the same nginx pod. I used nginx version 1.11 for my pod image.

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 443
    nodePort: 30443
    protocol: TCP
    name: https
  selector:
    app: nginx

```

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
``` 

- Cloud provider or hardware configuration:

Not using any cloud provider like AWS or GKE. Just hosting our own clusters and we're pointing traffic directly to NodePort 30080 or 30443 ports.

- OS (e.g: `cat /etc/os-release`):

```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
``` 

- Kernel (e.g. `uname -a`):

`Linux mstr-ulb0 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

- Network:

For old Kubernetes cluster 1.6.1 I was using: quay.io/calico/cni:v1.6.2 and 
quay.io/calico/node:v1.1.0
For the new cluster v1.10.11 I'm using docker.io/weaveworks/weave-kube:2.3.0

- Others:  

I've followed everything described here:
 - https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport
- https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

without success.

Also investigated some StackOverflow similar issues without success:

- https://stackoverflow.com/questions/42475987/how-to-preserve-source-ip-from-traffic-arriving-on-a-clusterip-service-with-an-e
- https://stackoverflow.com/questions/48215498/kubernetes-ingress-nginx-preserve-source-ip
- https://stackoverflow.com/questions/56656103/preserve-client-source-ip-for-kubernetes-ingress
- https://stackoverflow.com/questions/32112922/how-to-read-client-ip-addresses-from-http-requests-behind-kubernetes-services

Thanks in advance

/sig network
/sig architecture
