### ISSUE TITLE
kubectl apply failed when configmap is big

### ISSUE THREAD

**Issue by asaushkin** [kubernetes/kubernetes#83955]
**What happened**:

I have created configmap with a set of libraries that I want use inside a pod. Content of this configmap looks like that:

```
kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: 2019-10-15T14:48:58.174514Z
  name: jars
  namespace: default
binaryData:
  kotlin-stdlib-jdk8-1.3.41.jar: UEsDBAoAAAgIAHmd404A... (much more symbols here)
  aws-java-sdk-core-1.11.253.jar: UEsDBAoAAAAAAPsDlUsA... (much more symbols here)
  aws-java-sdk-s3-1.11.253.jar: UEsDBAoAAAAAALYElUsA... (much more symbols here)
  aws-java-sdk-kms-1.11.253.jar: UEsDBAoAAAAAALMElUsA... (much more symbols here)
  joda-time-2.8.1.jar: UEsDBAoAAAgAAB16z0YA... (much more symbols here)
  aws-java-sdk-dynamodb-1.11.253.jar: UEsDBAoAAAAAAAkFlUsA... (much more symbols here)
  kotlin-stdlib-jdk7-1.3.41.jar: UEsDBAoAAAgIAHmd404A... (much more symbols here)
  httpclient-4.5.2.jar: UEsDBAoAAAAAAKaIVUgA... (much more symbols here)
  jackson-annotations-2.6.0.jar: UEsDBBQACAgIAHSI8EYA... (much more symbols here)
  ion-java-1.0.2.jar: UEsDBBQACAgIAHy/R0oA... (much more symbols here)
  kotlin-stdlib-1.3.41.jar: UEsDBAoAAAgIAISc404A... (much more symbols here)
  httpcore-4.4.4.jar: UEsDBAoAAAgAABSSWkcA... (much more symbols here)
  commons-codec-1.9.jar: UEsDBAoAAAAAACW3lEMA... (much more symbols here)
  jackson-databind-2.6.7.1.jar: UEsDBBQACAgIAIGp6koA... (much more symbols here)
  fds-common-dynamodb-1.0-SNAPSHOT.jar: UEsDBAoAAAgIAOKDT08A... (much more symbols here)
  jackson-dataformat-cbor-2.6.7.jar: UEsDBBQACAgIAEl1xUgA... (much more symbols here)
  commons-logging-1.2.jar: UEsDBAoAAAAAAHyh5UQA... (much more symbols here)
  annotations-13.0.jar: UEsDBAoAAAAAAFKBkUMA... (much more symbols here)
  jmespath-java-1.11.253.jar: UEsDBAoAAAAAAA0ElUsA... (much more symbols here)
  kotlin-stdlib-common-1.3.41.jar: UEsDBAoAAAgIAGec404A... (much more symbols here)
  jackson-core-2.6.7.jar: UEsDBBQACAgIAM5wxUgA... (much more symbols here)
```

Total size of this file is 

```
ll configMap.yaml 
-rw-r--r-- 1 ags ags 12131884 окт 15 17:29 configMap.yaml
```

When I execute `kubectl apply` I got
 
```
$ kubectl apply -f configMap.yaml 
The ConfigMap "jars" is invalid: 
* metadata.annotations: Too long: must have at most 262144 characters
* []: Too long: must have at most 1048576 characters
```

**What you expected to happen**:

Run this command without any issues

**How to reproduce it (as minimally and precisely as possible)**:

Create a configMap with pretty big size

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-825e5d", GitCommit:"825e5de08cb05714f9b224cd6c47d9514df1d1a7", GitTreeState:"clean", BuildDate:"2019-08-18T03:58:32Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS EKS 
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 5.1.16-050116-lowlatency
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig cli
