### ISSUE TITLE
Patching stateful set not updating statefulset

### ISSUE THREAD

**Issue by Office-Manager** [kubernetes/kubernetes#84096]
**What happened:**
Patching a statefulset results in no change being registered and no update takes place

**What you expected to happen:**
After running the `kubectl patch` command for the sts to be updated with the new parameters

**How to reproduce it (as minimally and precisely as possible):**
```
kubectl -n test-delete apply -f https://raw.githubusercontent.com/mhausenblas/mehdb/master/app.yaml
kubectl -n test-delete  patch statefulsets.apps mehdb --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/", "value": {"args":[ "sleep","9999"]}}]'
```

Results in 
`statefulset.apps/mehdb patched (no change)`

Expected result would be 
```
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mehdb
  serviceName: mehdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mehdb
    spec:
      containers:
      - args:
        - sleep
        - "9999"
        env:
        - name: MEHDB_DATADIR
          value: /mehdbdata
```

actual result 
```
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mehdb
  serviceName: mehdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mehdb
    spec:
      containers:
      - env:
        - name: MEHDB_DATADIR
          value: /mehdbdata
```
**Anything else we need to know?:**

Running a `kubectl edit sts` works as expected updating the sts with the args 

Changing the command used to 
```
kubectl -n test-delete  patch statefulsets.apps mehdb --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0", "value": {"args":[ "sleep","9999"]}}]'
```
Will successfully patch the sts but it will add it as a new item in the list rather than appending to the existing container at 0 index 
```
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mehdb
  serviceName: mehdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mehdb
    spec:
      containers:
      - args:
        - sleep
        - "9999"
        imagePullPolicy: IfNotPresent
        name: ""
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: MEHDB_DATADIR
          value: /mehdbdata
```
