### ISSUE TITLE
crd validation fails to take effect for the below definition

### ISSUE THREAD

**Issue by sudeeptoroy** [kubernetes/kubernetes#84112]
**What happened**:
Here is how I defined my CRD
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: foos
    singular: foo
    kind: Foo
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            vc:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  address:
                    type: string
                required:
                - name
```
This is correct custom resource and gets executed.
```yaml
apiVersion: "stable.example.com/v1"
kind: Foo
metadata:
  name: foo-ok
spec:
  vc:
  - address: "bar"
    name: foo
```
However I don’t expect this to pass but it does.

```yaml
apiVersion: "stable.example.com/v1"
kind: Foo
metadata:
  name: foo-bad
spec:
- vc:			# vc is array
  - address: "bar"
    name: foo
```
is this expected?

**What you expected to happen**:
"foo-bad" should have failed.

**How to reproduce it (as minimally and precisely as possible)**:
mentioned above
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
