### ISSUE TITLE
Referencing containerPorts by name as targetPort for "Service" resource, does not generate endpoints when proto is UDP

### ISSUE THREAD

**Issue by abstrask** [kubernetes/kubernetes#84160]
**What happened**:
Created a "Service" resource for Pihole deployment, specifying a port, referencing a containerPort by name ("dns") as targetPort. No endpoints are created, when protocol is UDP.

Replacing the named port with the numeric port number (53) works as expected. Using named targetPort also works as expected when protocol is TCP.

**What you expected to happen**:
Endpoints being created according to the service spec.

**How to reproduce it (as minimally and precisely as possible)**:
Pod spec specifying a named containerPort ("dns"):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  containers:
  - name: pihole
    image: pihole/pihole:latest
    ports:
    - name: dns
      containerPort: 53
```

Service spec (**UDP**, **named** targetPort) - produces **no** endpoint:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp-named
spec:
  selector:
    app: pihole
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: dns
```

Service spec (**UDP**, **numeric** targetPort) - **produces** endpoint:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp-numeric
spec:
  selector:
    app: pihole
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
```

Service spec (**TCP**, **named** targetPort) - **produces** endpoint:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp-named
spec:
  selector:
    app: pihole
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: dns
```

**Anything else we need to know?**:
No?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.1 and 1.16.0
- Cloud provider or hardware configuration: AWS EKS/EC2 and Lenovo ThinkCentre M92p respectively
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by zouyee** [comment]
https://github.com/kubernetes/kubernetes/pull/80470

**Comment by busser** [comment]
@abstrask, by default ports specified in a pod spec use the TCP protocol.

With the yaml you gave as an example above, you get the following endpoints:

```
NAME                 ENDPOINTS             AGE
pihole-tcp-named     172.17.0.10:53        46s
pihole-udp-named     <none>                46s
pihole-udp-numeric   172.17.0.10:53        46s
```

You could add the UDP protocol to the pod spec like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  containers:
    - name: pihole
      image: pihole/pihole:latest
      ports:
        - name: dns
          containerPort: 53
          protocol: UDP
```

Which would give the following endpoints:

```
NAME                 ENDPOINTS             AGE
pihole-tcp-named     <none>                3m17s
pihole-udp-named     172.17.0.10:53        3m17s
pihole-udp-numeric   172.17.0.10:53        3m17s
```

You could specify both TCP and UDP protocols as two separate ports with the same number in the pod spec:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  containers:
    - name: pihole
      image: pihole/pihole:latest
      ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
```

Assuming you edited your services to match the new port names, you would get the following endpoints:

```
NAME                 ENDPOINTS             AGE
pihole-tcp-named     172.17.0.10:53        12m
pihole-udp-named     172.17.0.10:53        12m
pihole-udp-numeric   172.17.0.10:53        12m
```

The reason the `pihole-udp-numeric` service results in endpoints as you expect is that ports don't actually need to be specified in the pod spec for them to be used in endpoints. The fact that you specified a port number in your service, and not a port name, gave the endpoint controller enough information to do its job.

The [Kubernetes API reference for pods](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#container-v1-core) is clear that this is intentional behavior and not a bug:

> Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed.

I hope this clears things up for you. The behavior you are seeing is not the result of a bug :)
