### ISSUE TITLE
Pod with container with failed StartupProbe stays in Ready: false.

### ISSUE THREAD

**Issue by odinuge** [kubernetes/kubernetes#84178]
**What happened**:

Pod with container with failed `StartupProbe` stays in `Ready: false`.

**What you expected to happen**:

Pod/container should be killed and restarted and eventually enter `CrashLoopBackOff`.

**How to reproduce it (as minimally and precisely as possible)**:

Start cluster with feature gate `StartupProbe=true`.

Deploy pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-pod
spec:
  containers:
    - image: fedora
      command:
        - sleep
        - inf
      name: example1
      readinessProbe:
        exec:
          command:
            - "true"
        failureThreshold: 2
        periodSeconds: 2
      livenessProbe:
        exec:
          command:
            - "true"
        failureThreshold: 2
        periodSeconds: 2
      startupProbe:
        httpGet:
          path: /healthz
          port: 8080
        failureThreshold: 2
        periodSeconds: 2
```

Watch output:

```
> kubectl get pod
NAME                READY   STATUS    RESTARTS   AGE
startup-probe-pod   0/1     Running   0          3m28s
> kubectl describe pod
Name:         startup-probe-pod                                                                                                                                             
Namespace:    default                                                                                                                                                       
Priority:     0                                                                                                                                                             
Node:         kind-control-plane/172.17.0.2                                                                                                                                 
Start Time:   Tue, 22 Oct 2019 09:54:33 +0200                                                                                                                               
Labels:       <none>                                                                                                                                                        
Annotations:  kubectl.kubernetes.io/last-applied-configuration:                                                                                                             
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"startup-probe-pod","namespace":"default"},"spec":{"containers":[{"com...               
Status:       Running                                                                                                                                                       
IP:           10.244.0.2                                                                                                                                                    
IPs:                                                                                                                                                                        
  IP:  10.244.0.2                                                                                                                                                           
Containers:                                                                                                                                                                 
  example1:                                                                                                                                                                 
    Container ID:  containerd://8451c1b089635e2fde65e59a8b00813db728cb7ad8942bf1a81ab0279496b4d9                                                                            
    Image:         fedora                                                                                                                                                   
    Image ID:      docker.io/library/fedora@sha256:8a91dbd4b9d283ca1edc2de5dbeef9267b68bb5dae2335ef64d2db77ddf3aa68                                                         
    Port:          <none>                                                                                                                                                   
    Host Port:     <none>                                                                                                                                                   
    Command:                                                                                                                                                                
      sleep
      inf
    State:          Running
      Started:      Tue, 22 Oct 2019 09:54:54 +0200
    Ready:          False
    Restart Count:  0
    Liveness:       exec [true] delay=0s timeout=1s period=2s #success=1 #failure=2
    Readiness:      exec [true] delay=0s timeout=1s period=2s #success=1 #failure=2
    Startup:        http-get http://:8080/healthz delay=0s timeout=1s period=2s #success=1 #failure=2
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-s8pdb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-s8pdb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-s8pdb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                    From                         Message
  ----     ------            ----                   ----                         -------
  Warning  FailedScheduling  <unknown>              default-scheduler            0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
  Normal   Scheduled         <unknown>              default-scheduler            Successfully assigned default/startup-probe-pod to kind-control-plane
  Normal   Pulling           3m54s                  kubelet, kind-control-plane  Pulling image "fedora"
  Normal   Pulled            3m36s                  kubelet, kind-control-plane  Successfully pulled image "fedora"
  Normal   Created           3m33s                  kubelet, kind-control-plane  Created container example1
  Normal   Started           3m33s                  kubelet, kind-control-plane  Started container example1
  Warning  Unhealthy         3m30s (x2 over 3m32s)  kubelet, kind-control-plane  Startup probe failed: Get http://10.244.0.2:8080/healthz: dial tcp 10.244.0.2:8080: connect
: connection refused

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.0-alpha.1", GitCommit:"0960c74c3788b1724bd7e7b9933bc49c7e5b5afa", GitTreeState:"clean", BuildDate:"20
19-10-02T23:24:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-16T
07:13:29Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `kind`
- OS (e.g: `cat /etc/os-release`): `Arch linux
- Kernel (e.g. `uname -a`): `Linux xps13 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux`
- Install tools: `kind`
```yaml
# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "StartupProbe=true"
  scheduler:
    extraArgs:
      "feature-gates": "StartupProbe=true"
  controllerManager:
    extraArgs:
      "feature-gates": "StartupProbe=true"
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "StartupProbe=true"
# 1 control plane node and 3 workers
nodes:
- role: control-plane
```
- Network plugin and version (if this is a network-related bug): 
- Others:
