### ISSUE TITLE
The subpath folder is created with unexpected group id when the volume is shared by multiple pods

### ISSUE THREAD

**Issue by ywk253100** [kubernetes/kubernetes#84219]
The steps to reproduce this issue is as following:
1. Create PV:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: yinw-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /opt/test
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - host1.test.com
```
2. Create PVC:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yinw-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: yinw-pv
```
3. Create two pods, the first one:
```yaml
kind: Pod
apiVersion: v1
metadata: { name: "yinw-test" }
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: "yinw-pvc"
  securityContext:
    fsGroup: 10000
  containers:
    - image: alpine:latest
      name: show1
      command: ["/bin/sh", "-c", "id && ls -dl /mnts/*"]
      volumeMounts:
        - name: "data"
          mountPath: "/mnts/a"
          subPath: a
```
The second one:
```yaml
kind: Pod
apiVersion: v1
metadata: { name: "yinw-test-2" }
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: "yinw-pvc"
  securityContext:
    fsGroup: 900
  containers:
    - image: alpine:latest
      name: show1
      command: ["/bin/sh", "-c", "id && ls -dl /mnts/*"]
      volumeMounts:
        - name: "data"
          mountPath: "/mnts/b"
          subPath: b
```

The two pods share the same volume but with different `subPath`(`a` and `b` ) and different `fsGroup`(`10000` and `900`)

When I checking the permission of directories on the host, I got:
```shell
[yinw@harbor-prd-a2 ~]$ ls -al /opt/
total 56
drwxr-xr-x. 11 root root   4096 Oct 23 01:16 .
dr-xr-xr-x. 20 root root   4096 Oct 10 04:57 ..
drwxrwsr-x   4 root 10000  4096 Oct 23 01:19 test

[yinw@harbor-prd-a2 ~]$ ls -al /opt/test/
total 16
drwxrwsr-x   4 root 10000 4096 Oct 23 01:19 .
drwxr-xr-x. 11 root root  4096 Oct 23 01:16 ..
drwxrwsr-x   2 root 10000 4096 Oct 23 01:19 a
drwxrwsr-x   2 root 10000 4096 Oct 23 01:19 b
```
The group IDs of `/opt/test`, `/opt/test/a` and `/opt/test/b` are all 10000, what I expect is that the group ID of `/opt/test/b` should be `900` as specified in `fsGroup` of the second pod. 

If I create the pod `yinw-test-2` first and then create the pod `yinw-test`, I got:
```shell
[yinw@harbor-prd-a2 ~]$ ls -l /opt/
total 48
drwxrwsr-x   2 root  900  4096 Oct 23 01:25 test

[yinw@harbor-prd-a2 ~]$ ls -l /opt/test/
total 8
drwxrwsr-x 2 root 900 4096 Oct 23 01:25 a
drwxrwsr-x 2 root 900 4096 Oct 23 01:25 b
```

Is this the expected behavior? How can I get the result that I expect?
