### ISSUE TITLE
CustomResourceDefinition with deletionTimestamp is not removed after patching its finalizers

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#84354]
**What happened**:
CRD with deletionTimestamp and `customresourcecleanup.apiextensions.k8s.io` finalizer is not deleted (removed from the store) after removing the finalizer.

**What you expected to happen**:
I would expect after removing the finalizer the CRD to be removed from the store.

**How to reproduce it (as minimally and precisely as possible)**:
1. Apply crd
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: crontabs.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: crontabs
    # singular name to be used as an alias on the CLI and for display
    singular: crontab
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CronTab
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ct
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            cronSpec:
              type: string
            image:
              type: string
            replicas:
              type: integer
```

2. Apply crd object with finalizer
```yaml
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
  finalizers:
  - foo/bar
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
```

3. Delete the crd 
```
$ k delete crd crontabs.stable.example.com
```
4. Patch the `customresourcecleanup.apiextensions.k8s.io` finalizer
```
$ k patch crds crontabs.stable.example.com --type merge -p '{"metadata":{"finalizers": []}}'
```

5. Ensure that the crd is not removed and one more delete request is needed to delete it

**Anything else we need to know?**:
The CRD is removed from the store after patching the finalizer in v1.16.
Resources like Deployments and etc. are also removed from the store the right after patching their finalizers.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ k version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: minikube
- Network plugin and version (if this is a network-related bug):
- Others:
