### ISSUE TITLE
To build and apply a high performant, unified expression engine for K8s?

### ISSUE THREAD

**Issue by brightzheng100** [kubernetes/kubernetes#84417]
**What would you like to be added**:

It's always a pain while looking at this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-name
            operator: In
            values:
            - e2e-az1
            - e2e-az2
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
```

Should we consider, or are we considering, to build a unified expression engine for overall K8s so things may become much easier, like this?

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - expression: 'key("kubernetes.io/e2e-az-name") in ("e2e-az1", "e2e-az2")'
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
        - expression: 'key("another-node-label-key") in ("another-node-label-value")'
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
```

**Why is this needed**:

It's verbose, or sometimes confusing, while expressing some expression "logic" for some conditions using pure YAML syntax.
You may list down a few which may use different "operations" while constructing the logic.
It definitely would help if we could have a high performant, unified expression engine with a consistent syntax.

What do you think?
