### ISSUE TITLE
how to get imageID in container

### ISSUE THREAD

**Issue by zqzzq** [kubernetes/kubernetes#84492]
**What happened**:
I want to get imageID in container, so I used status.containerStatuses[0].imageID in env, but it got failed with error message:
```
spec.template.spec.containers[0].env[0].valueFrom.fieldRef.fieldPath: Invalid value: "status.containerStatuses[0].imageID": error converting fieldPath: field label not supported: status.containerStatuses[0].imageID
```
is there a way to get imageID in container?
**What you expected to happen**:
get imageID in container
**How to reproduce it (as minimally and precisely as possible)**:
```
- env:
  - name: IMAGE_ID
    valueFrom
      fieldRef:
        apiVersion: v1
        fieldPath: status.containerStatuses[0].imageID
```
**Environment**:
- Kubernetes version (use `kubectl version`):1.11
