### ISSUE TITLE
Feature request: K8s API support for filtering Jobs by the CronJob that owns them

### ISSUE THREAD

**Issue by jceresini** [kubernetes/kubernetes#84493]
**What would you like to be added**:
The ability to filter (on the API-side) for a list of Jobs that belong to a given CronJob. I'm creating CronJobs using `generateName`, so at the time of creation I don't know the full CronJob name. But I want to be able to get a list of Jobs that were run as part of that CronJob. Here's a simplified version of an example CronJob:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  generateName: backup-job-
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: worker
            args:
            - echo
            - backup-starting
            image: busybox
          restartPolicy: Never
  schedule: "0 5 * * *"
```
And a Job that runs as a result (stripped down version):

```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    controller-uid: 53136963-15e7-4437-a7a3-d5750e24d27b
    job-name: backup-job-qh7m5-1572314820
  name: backup-job-qh7m5-1572314820
  namespace: default
  ownerReferences:
  - apiVersion: batch/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: backup-job-qh7m5
    uid: 47d699d1-5a4e-46d2-ac5d-6cee8b247b0b
  uid: 53136963-15e7-4437-a7a3-d5750e24d27b
spec:
  template:
    metadata:
      labels:
        controller-uid: 53136963-15e7-4437-a7a3-d5750e24d27b
        job-name: backup-job-qh7m5-1572314820
    spec:
      containers:
      - args:
        - echo
        - backup-starting
        image: busybox
        name: worker
      schedulerName: default-scheduler
```
If I could use the metadata.ownerReferences.uid as a fieldSelector it would solve my issue. If there is another way to accomplish this using the built-in relationship data (meaning without add my own labels to the JobSpec) thats really all I'm looking for.

**Why is this needed**:
Finding all Jobs associated with a CronJob seems like a reasonable thing to want to do. There's already a relationship created via the `ownerReferences` fields. If the API allowed Job's to be filtered by the fields available there (or just `metadata.ownerReferences.uid`) it would be easy to get the past (or current) Jobs for a given CronJob, without client-side filtering, or having to add redundant information to support filtering.

**Possible workarounds**
I realize I could generate a name for the cronjob, and include that in the JobSpec as a label, and then filter by the label. That is what I plan to do for now, but I'd like to take advantage of `generateName` and I think it makes sense to be able to filter by ownerReferences or something that achieves the same without adding the labels to the jobs myself.

It's also been suggested that I filter by the prefix of the Job name, because the Job's name ends up being the CronJobs name followed by a hyphen and some identifier. I'd prefer something more exact.
