### ISSUE TITLE
NodePort dont response on guest node.

### ISSUE THREAD

**Issue by 2qif49lt** [kubernetes/kubernetes#84577]
**What happened**:
i have 5nodes clutser, and the service with type NodePort and `externalTrafficPolicy: Local` that to acquire source IP. the deplotment selected by this service  is  assigned with `nodeSelector`   to a fixed node.

request is ok through the fixed work node, but  dont work from any other guest nodes.
is a feature？

**What you expected to happen**:

guest nodes should be ok also.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rnmaster
  namespace: roadnetrt
  labels:
    run: master
spec:
  type: NodePort
  ports:
  - port: 8181
    targetPort: 8181
    protocol: TCP
    name: http
  selector:
    run: master
  externalTrafficPolicy: Local
```

```yaml
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rnmaster
  namespace: roadnetrt
  labels:
    run: master
spec:
  selector:
    matchLabels:
      run: master
  replicas: 1
  template:
    metadata:
      labels:
        run: master
    spec:
      containers:
      - name: rnmaster
        image: images.abcde.local:5000/rnmaster:0.1.4
        args: ["-maps=:8081/xodr/", "-worker=images.abcde.local:5000/roadnetrt:0.1.0", "-nodes=cloud/ivt:4u"]
        ports:
          - containerPort: 8181
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      nodeSelector:
        cloud/ivt: 4u
      imagePullSecrets:
      - name: roadnetrt-image
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
centos 7
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
