### ISSUE TITLE
Kubectl drops all annotations when one is not a valid string.

### ISSUE THREAD

**Issue by paulgmiller** [kubernetes/kubernetes#84759]
**What happened**:'
Kubectl drops all annotations when one is not a valid string.  for example true/false/on/off

**What you expected to happen**:
EIther warn on bad annoations or fail on the first one. 

**How to reproduce it (as minimally and precisely as possible)**:

Take this foo.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    foobar: on
    bar: avalidstring
  name: panaji-ing
  namespace: shared
  labels:
    msftkube/app: panaji-ing
spec:
  rules:
  - host: some-host.foo.com
    http:
      paths:
      - backend:
          serviceName: some-service
          servicePort: grpc
```
kubectl apply --dry-run -f .\foo.yaml -o yaml

The output will not contain the annotation. (just last-applied)

More relistic exmples might be these nginx annotations
```
   nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/auth-tls-verify-client: on
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.7
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): windows
- Kernel (e.g. `uname -a`): win10
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
