### ISSUE TITLE
cpumanager: cpu manager state checkpoint file validate failed after node crash or kubelet down

### ISSUE THREAD

**Issue by whypro** [kubernetes/kubernetes#84783]
**What happened**:

Currently, static policy in cpumanager validate state checkpoint file when kubelet starts if cpu binding feature is enabled. If the validation is failed, a panic will be triggerred and cpu manager will refuse to restart. The error log shows that we must remove this state file `/var/lib/kubelet/cpu_manager_state` and restart kubelet again.

As we observed in production environment, the checkpoint file sometimes keep a wrong state after node crash or kubelet down. In this case, kubelet cannot restart properly unless someone manually delete that state file.

We finally figure out to root cause for the broken state file.

There are two operations in `AddContainer`, `SetDefaultCPUSet` and `SetCPUSet`. The former is removing cpu cores info from defaultCPUSet and the latter is adding cpu cores info to assignmentCPUSet. 

- https://github.com/kubernetes/kubernetes/blob/3e5f6bdaa48723a91a208650e8d2d601fc1a55a9/pkg/kubelet/cm/cpumanager/policy_static.go#L285

- https://github.com/kubernetes/kubernetes/blob/3e5f6bdaa48723a91a208650e8d2d601fc1a55a9/pkg/kubelet/cm/cpumanager/policy_static.go#L229

- https://github.com/kubernetes/kubernetes/blob/3e5f6bdaa48723a91a208650e8d2d601fc1a55a9/pkg/kubelet/cm/cpumanager/state/state_checkpoint.go#L162

The problem is, each operation invoke `storeStorage` and write to state file separately, so this file may be written twice in single `AddContainer` call. If node crash or kubelet down between the two writing operation incidently, the state in checkpoint file will be broken. `RemoveContainer` has the same problem.

**What you expected to happen**:

1. cpumanager/static policy would automatically regenerate cache and write correct state back to broken checkpoint file after node crash or kubelet down.

2. cpumanager/static policy ensures atomic operation of writing to checkpoint for `AddContainer` and `RemoveContainer`.

**How to reproduce it (as minimally and precisely as possible)**:

1. enabled static cpu manager policy for kubelet.

2. create cronjobs which spawns a pod sleeping random seconds periodically to simulate many pod create/delete actions in prodution env.

the more cronjobs, the easiler to reproduce.

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cpuset-1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ubuntu:xenial
            command:
            - /bin/bash
            - -c
            - "sleep $[ ( $RANDOM % 60 )  + 1 ]"
            resources:
              limits:
                cpu: 1
                memory: 10Mi
          restartPolicy: Never


---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cpuset-2
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ubuntu:xenial
            command:
            - /bin/bash
            - -c
            - "sleep $[ ( $RANDOM % 60 )  + 1 ]"
            resources:
              limits:
                cpu: 1
                memory: 10Mi
          restartPolicy: Never
```

3. kill kubelet periodically
```
crontab -e
*/1 * * * * sleep 30 && pkill -9 kubelet
```

4. wait for hours, the case would occur

`/var/lib/kubelet/cpu_state_manager ` would keep a wrong state and kubelet would not restart properly agian which is already described in https://github.com/kubernetes/kubernetes/issues/84703

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
kvm
```
- OS (e.g: `cat /etc/os-release`):
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS
```
- Kernel (e.g. `uname -a`):
```
Linux ubuntu 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
```
# lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Socket(s):             4
NUMA node(s):          1
Model name:            QEMU Virtual CPU version 2.5+
NUMA node0 CPU(s):     0-3
```
