### ISSUE TITLE
Source IPs are not preserved for UDP services on Azure

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#84800]
**What happened**:

Refer https://github.com/Azure/AKS/issues/1295, health probes are not associated for UDP services on Azure, hence source IPs are not preserved for UDP services on Azure.

**What you expected to happen**:

When `externalTrafficPolicy` is set to `Local` for UDP services,  source IPs should be preserved and the health probe should be associated with UDP load balancer rule.

Per the [Azure Load Balancer health probes docs](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-custom-probe-overview), the health probe only supports TCP, HTTP and HTTPS. UDP is not supported as the probing protocol, hence we can’t enable the health probes for UDP services.

However, when the externalTrafficPolicy is Local, Kubernetes would open an HTTP endpoint for UDP services, hence it’s actually supported on Azure. So, should associate the probes on externalTrafficPolicy=Local cases.

**How to reproduce it (as minimally and precisely as possible)**:

Create a UDP service with `externalTrafficPolicy: Local`:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: udpserver
spec:
  externalTrafficPolicy: Local
  selector:
    app: udpserver
  type: LoadBalancer
  ports:
  - protocol: UDP
    port: 3000
    targetPort: 3000
```

Then check the source IPs.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/sig cloud-provider
/area provider/azure
