### ISSUE TITLE
Property names "items" in OpenAPISchema for CRD not handled correctly

### ISSUE THREAD

**Issue by cliveseldon** [kubernetes/kubernetes#84880]
**What happened**:
 Created a CRD with OpenAPISchema containing an array which itself contains objects which have a property names "items". This already exists in [DownwardAPI volume source](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#downwardapivolumesource-v1-core).

Creating a resource with this CRD fails with:
`The Foo "test" is invalid: type: Required value`

**What you expected to happen**:

It would succeed CRD validation.

**How to reproduce it (as minimally and precisely as possible)**:
kind create cluster --image kindest/node:v1.16.2
Kubectl apply the following CRD:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: foos
    singular: foo
    kind: Foo
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            volumes:
              type: array
              items:
                type: object
                properties:
                  downwardAPI:
                    properties:
                      items:
                        items:
                          properties:
                            path:
                              type: string
                          required:
                          - path
                          type: object
                        type: array
                    type: object
```

Then kubectl apply the following

```
apiVersion: stable.example.com/v1
kind: Foo
metadata:
  name: test
spec:
  volumes:
  - downwardAPI:
      items:
        - path: annotations
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-11-05T23:58:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

This issue was meant to be fixed by https://github.com/go-openapi/validate/pull/107
However, there is a discussion: https://github.com/go-openapi/validate/issues/108#issuecomment-540532114
