### ISSUE TITLE
version:1.11.8 failed to upgrade to version:1.12.0 

### ISSUE THREAD

**Issue by kiddingl** [kubernetes/kubernetes#85126]
**What happened**:
```
[root@master ~]# kubeadm upgrade plan --config=/tmp/kubeadm-config.yml
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration options from a file: /tmp/kubeadm-config.yml
could not read manifests from: /etc/kubernetes/manifests, error: failed to check if etcd pod implements TLS: failed to read manifest for "/etc/kubernetes/manifests/etcd.yaml": open /etc/kubernetes/manifests/etcd.yaml: no such file or directory

```
My etcd cluster is setup by yum installing and is not pod running on k8s. My  cluster don't have /etc/kubernetes/manifests/etcd.yaml
**What you expected to happen**:
successfully upgrade to version 1.12.0

**How to reproduce it (as minimally and precisely as possible)**:
You should setup etcd cluster with yum installing 

**Anything else we need to know?**:
My kubeadm-config.yml（Some sensitive fields have been deleted by me.）:
```
api:
    advertiseAddress: 172.16.41.1
    bindPort: 6443
    controlPlaneEndpoint: 172.16.48.48:6445
apiServerCertSANs:
- 172.16.48.48
- kubernetes
- master.kubernetes
- master1.kubernetes
- master2.kubernetes
- master3.kubernetes
apiServerExtraArgs:
    endpoint-reconciler-type: lease
apiVersion: kubeadm.k8s.io/v1alpha2
etcd:
    caFile: /etc/pki/etcd/ca.crt
    certFile: /etc/pki/etcd/client.crt
    endpoints:
    - https://172.16.41.1:2379
    - https://172.16.42.1:2379
    - https://172.16.43.1:2379
    keyFile: /etc/pki/etcd/client.key
featureGates:
    CoreDNS: true
kind: MasterConfiguration
kubeProxy:
    config:
        featureGates:
            SupportIPVSProxyMode: true
        mode: ipvs
kubeletConfiguration:
    cgroupDriver: cgroupfs
    clusterDomain: cluster.local
    kubeletCgroups: /systemd/system.slice
    resolvConf: /etc/kubernetes/resolv.conf
kubernetesVersion: 1.12.0
networking:
    dnsDomain: cluster.local
    podSubnet: 172.16.0.0/12
nodeName: vm41
nodeRegistration:
    criSocket: /run/containerd/containerd.sock
```
**Environment**:
- os: centos7
- Kubernetes version (use `kubectl version`):
kuctl version 1.11.8
k8s version 1.11.8
- Kernel (e.g. `uname -a`):
4.14.56-1.el7.x86_64

**Comment by neolit123** [comment]
your etcd config does not seem correct:
```
etcd:
    caFile: /etc/pki/etcd/ca.crt
    certFile: /etc/pki/etcd/client.crt
    endpoints:
    - https://172.16.41.1:2379
    - https://172.16.42.1:2379
    - https://172.16.43.1:2379
    keyFile: /etc/pki/etcd/client.key
```

it should look like:
```
etcd:
    external:
        caFile: /etc/pki/etcd/ca.crt
        certFile: /etc/pki/etcd/client.crt
        endpoints:
        - https://172.16.41.1:2379
        - https://172.16.42.1:2379
        - https://172.16.43.1:2379
        keyFile: /etc/pki/etcd/client.key
```

notice the "external" part, look at the go types for more details:
https://github.com/kubernetes/kubernetes/blob/release-1.12/cmd/kubeadm/app/apis/kubeadm/v1alpha2/types.go#L195

if you do the above this should not fail:
> could not read manifests from: /etc/kubernetes/manifests, error: failed to check if etcd pod implements TLS: failed to read manifest for "/etc/kubernetes/manifests/etcd.yaml": open /etc/kubernetes/manifests/etcd.yaml: no such file or directory

/triage support
/remove-kind bug
/area kubeadm
/sig cluster-lifecycle

i'm going to have to close this as 1.12 is out of support.
with the release of 1.17 soon, try moving to 1.15 as your minimal version.
