### ISSUE TITLE
HorizontalPodAutoscaler misbehaving when using a custom metric

### ISSUE THREAD

**Issue by davidmogar** [kubernetes/kubernetes#85206]
**What happened**:

The HorizontalPodAutoscaler is scaling unnecessarily and removing pods leaving the system in an unstable status.

**More info**:

I have an HorizontalPodAutoscaler defined like this:
```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
[...]
spec:
  maxReplicas: 15
  metrics:
    - type: Object
      object:
        metric:
          name: avg_cpu_load_10m
        describedObject:
          kind: Namespace
          name: playground
        target:
          type: Value
          value: 800m
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: puppetserver
```
Here I'm using a custom metric provided by Prometheus Adapter. The configmap contains this configuration for the metric:
```yaml
- seriesQuery: '{__name__="container_cpu_usage_seconds_total",container_name="puppetserver"}'
      resources:
        overrides:
          namespace:
            resource: namespace
      name:
        as: "avg_cpu_load_10m"
      metricsQuery: avg(rate(<<.Series>>{<<.LabelMatchers>>,container_name="puppetserver"}[10m])) by (<<.GroupBy>>)
```
Basically I'm collecting the usage across all the pods in a namespace in a time window of 10 minutes.

The configuration seems to be fine according to the next output:
```bash
$ kubectl -n playground describe hpa puppetserver
Name:                                                         puppetserver
Namespace:                                                    playground
Labels:                                                       app.kubernetes.io/instance=puppetserver
                                                              app.kubernetes.io/managed-by=Helm
                                                              app.kubernetes.io/name=puppetserver
                                                              app.kubernetes.io/version=5.3.6
                                                              helm.sh/chart=puppetserver-0.1.0
Annotations:                                                  <none>
CreationTimestamp:                                            Fri, 08 Nov 2019 17:14:28 +0100
Reference:                                                    Deployment/puppetserver
Metrics:                                                      ( current / target )
  "avg_cpu_load_10m" on Namespace/playground (target value):  486m / 800m
Min replicas:                                                 1
Max replicas:                                                 15
Deployment pods:                                              2 current / 2 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from Namespace metric avg_cpu_load_10m
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:
  Type    Reason             Age                  From                       Message
  ----    ------             ----                 ----                       -------
  Normal  SuccessfulRescale  35m (x67 over 2d4h)  horizontal-pod-autoscaler  New size: 1; reason: All metrics below target
  Normal  SuccessfulRescale  10m (x68 over 2d5h)  horizontal-pod-autoscaler  New size: 2; reason: Namespace metric avg_cpu_load_10m above target
```
So if the value of the metric goes above **800m** I expect the Deployment to scale up and if it goes below, to scale down. All of this taking into account the toleration for which I have the default value.

In the next image you can see three plots:
- The first one shows moments in which the metric was above the 800m (80%) target value.
- The second one shows in green the number of pods and in red the actual value of the metric at different points.
- Finally, the third image shows the different pods in the namespace and their status (yellow for not ready and green for ready).

![image](https://user-images.githubusercontent.com/1498203/68765511-39b1e700-061d-11ea-9560-ed0fb2c7d7e4.png)

As you can see, there are 5 moments in which the metric was above the target value and in all those moments, the deployment scaled up (even if only briefly). But, in the second plot you can see moments in which the deployment also scaled up when it wasn't needed (the value for the metric is below the target at 11:45 for example).

This is a problem as the pods take a while to start and be ready (around 2 minutes). It also take them several requests to work efficiently. This leads me to the second problem here. Taking for example the period of time between 11:35 and 11:55 you can see the next:

![image](https://user-images.githubusercontent.com/1498203/68765916-310de080-061e-11ea-87f9-383f808f515a.png)

Here, a pod was running and ready when the HPA decided (wrongly) that it was needed to scale up, so it created a pod. Immediately (less than a minute) it decided to scale down, removing the ready pod and leaving the one that was still starting. In these moments, my cluster cannot process any traffic so the HAProxy in front is returning gateway timeouts.

**What you expected to happen**:

Here I expect three things:
- Only scale up based in the actual value of the metric, which seems not to be the case.
- Not to scale down immediately after creating a pod.
- Not to remove pods leaving the system in an unstable state (no pods ready).
- Ideally, and this is actually **very important** for our application, delete newer pods and keep running the oldest ones as those perform better.

**How to reproduce it (as minimally and precisely as possible)**:

Create an HPA using a custom metric like the shown above and send traffic.

**Environment**:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"2019-06-18T20:40:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
- Cloud provider or hardware configuration:
In house using OpenStack Magnum
- OS (e.g: `cat /etc/os-release`):
```
NAME=Fedora
VERSION="29.20181126.0 (Atomic Host)"
ID=fedora
VERSION_ID=29
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29.20181126.0 (Atomic Host)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Atomic Host"
VARIANT_ID=atomic.host
OSTREE_VERSION=29.20181126.0
```
- Kernel (e.g. `uname -a`):
```
Linux p9s-minion 4.19.3-300.fc29.x86_64 #1 SMP Wed Nov 21 15:27:25 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
