### ISSUE TITLE
Unable to manage multiple clusters with same user but different token

### ISSUE THREAD

**Issue by juanbaio10** [kubernetes/kubernetes#85271]
Hi all,

I´m not able to configure kubeconfig to manage multiple kubernetes clusters with same user.
I followed [kubernetes documentation](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/) but my use case is a little bit different.
-I have 2 kubernetes clusters(v1.13.5 and v1.15.5).
-In both of them I have the same username(same display name and same local id) created to access to kubernetes resources.
-I have the below kubeconfig but doesn´t work with two different tokens and same userid:

```
apiVersion: v1
clusters:
- cluster:
    server: https://<cluster1>/k8s/clusters/local
  name: production
- cluster:
    server: https://<cluster2>/k8s/clusters/c-xr82h
  name: preproduction
contexts:
- context:
    cluster: production
    namespace: default
    user: <userid>
  name: context-production
- context:
    cluster: preproduction
    namespace: default
    user: <userid>
  name: production
current-context: production
kind: Config
preferences: {}
users:
- name: <userid>
  user:
    token: <token-user-production>
    token: <token-user-preproduction>
```

**Comment by juanbaio10** [comment]
@kubernetes/sig-cluster-ops-<group-suffix>

**Comment by juanbaio10** [comment]
@kubernetes/sig-cluster-ops

**Comment by liggitt** [comment]
The name of the user stanza only carries meaning in the local kubeconfig file. It is not sent to the server, and can be any string you want. Think of the users section as a map of name to config stanza. 

This is the config you would use to accomplish what you want:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://<cluster1>/k8s/clusters/local
  name: production
- cluster:
    server: https://<cluster2>/k8s/clusters/c-xr82h
  name: preproduction
contexts:
- context:
    cluster: production
    namespace: default
    user: <userid>-production
  name: context-production
- context:
    cluster: preproduction
    namespace: default
    user: <userid>-preproduction
  name: production
current-context: production
kind: Config
preferences: {}
users:
- name: <userid>-production
  user:
    token: <token-user-production>
- name: <userid>-preproduction
  user:
    token: <token-user-preproduction>
```
