### ISSUE TITLE
headless service configurable priority and weight values

### ISSUE THREAD

**Issue by sergey-safarov** [kubernetes/kubernetes#85395]
**What would you like to be added**:
I want have more control about SRV records created for headless service.
In my case need to create SRV records like
```
_sip._udp.kamailio.namespace.svc.cluster.local 300 IN SRV 10 200 5060 172-21-2-11.kamailio.namespace.svc.cluster.local.
_sip._udp.kamailio.namespace.svc.cluster.local 300 IN SRV 20 300 5060 172-21-2-12.kamailio.namespace.svc.cluster.local.
_sip._udp.kamailio.namespace.svc.cluster.local 300 IN SRV 30 400 5060 172-21-2-13.kamailio.namespace.svc.cluster.local.
_sip._udp.kamailio.namespace.svc.cluster.local 300 IN SRV 40 500 5060 172-21-2-14.kamailio.namespace.svc.cluster.local.
```
Here I want control `priority` and `weight` values of created SRV records.
I suggest to create this service using yaml file like
```yaml
apiVersion: v1
kind: Service
metadata:
  name: kamailio
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: sip
    protocol: UDP
    port: 5060
  selectorSets:
  - priority: 10
    weight: 200
    selector:
      statefulset.kubernetes.io/pod-name: kamailio-0
  - priority: 20
    weight: 300
    selector:
      statefulset.kubernetes.io/pod-name: kamailio-1
  - priority: 30
    weight: 400
    selector:
      statefulset.kubernetes.io/pod-name: kamailio-2
  - priority: 40
    weight: 500
    selector:
      statefulset.kubernetes.io/pod-name: kamailio-3
```

**Why is this needed**:
This allow manage traffic distribution for application that actively use SRV records.
As example SIP call application.
