### ISSUE TITLE
Scheduler performs deeper validation than when pod is admitted

### ISSUE THREAD

**Issue by mlowery** [kubernetes/kubernetes#85428]
Note: This looks like the same as https://bugzilla.redhat.com/show_bug.cgi?id=1760807 but I didn't see an issue for it in this repository.

**What happened**:

All new pods stuck in `Pending` with the following event:

```
Warning  FailedScheduling  2m54s (x258 over 63m)  default-scheduler         invalid label value: "-1": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

**What you expected to happen**:

No scheduling error.

**How to reproduce it (as minimally and precisely as possible)**:

Submit a pod spec with this excerpt. All subsequent pods will be stuck in Pending.

```
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: someKey
              operator: In
              values:
              - "-1"
          topologyKey: kubernetes.io/hostname
        weight: 50
```

**Anything else we need to know?**:

Regarding why the invalid label was admitted, it appears there is no value check when the pod is validated:

https://github.com/kubernetes/kubernetes/blob/ff4e1f3592bfd51aea3018ed7e0a8579e5c0eea1/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go#L46-L48

https://github.com/kubernetes/kubernetes/blob/aaa91ef4121a6236186c07e127decddb6e99c7fe/pkg/apis/core/validation/validation.go#L3437

Contrast this validation to that performed by the scheduler:

https://github.com/kubernetes/kubernetes/blob/652baf18601eecf42521a1361a8815576bc8eb55/pkg/scheduler/algorithm/priorities/interpod_affinity.go#L55

https://github.com/kubernetes/kubernetes/blob/5a23bffd422e4b2a6056a68034d01f1942fbf856/staging/src/k8s.io/apimachinery/pkg/labels/selector.go#L171

**Environment**:
- Kubernetes version (use `kubectl version`):

v1.12

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
