### ISSUE TITLE
kubeadm parameter node-cidr-mask-size repeated

### ISSUE THREAD

**Issue by yuchunyun** [kubernetes/kubernetes#85492]
**What happened**:
I use the following configuration file
```
...
controllerManager:
  extraArgs:
    cluster-cidr: 10.100.0.0/16,fc00::/48
    service-cluster-ip-range: 10.200.0.0/16,fc00:bb::/112
    node-cidr-mask-size-ipv4: "24"
    node-cidr-mask-size-ipv6: "96"
featureGates:
  IPv6DualStack: true
...
```
the last generation of`/etc/kubernetes manifests/kube-controller-manager` ,There are three parameters in yaml
```
...
    - --node-cidr-mask-size=24
    - --node-cidr-mask-size-ipv4=24
    - --node-cidr-mask-size-ipv6=96
...
```
which looks like ` - --node-cidr-mask-size=24` default. The result is that the kube-controller cannot start. When I delete it, the kube-controller will work fine
**What you expected to happen**:
In this case, the default parameter should not be added

**Anything else we need to know?**:
kubeadm version
```
kubeadm version: &version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.0-beta.2", GitCommit:"c97baa339b5043424522dc7932fc3891f15543cb", GitTreeState:"clean", BuildDate:"2019-11-20T04:05:45Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
 kubectl version
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.0-beta.2", GitCommit:"c97baa339b5043424522dc7932fc3891f15543cb", GitTreeState:"clean", BuildDate:"2019-11-20T04:28:16Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
