### ISSUE TITLE
node-cidr-mask-size-ipv6 can not work

### ISSUE THREAD

**Issue by yuchunyun** [kubernetes/kubernetes#85491]
**What happened**:
I used dual-stack and set the parameter of kube-controller to --node-cidr-mask-size-ipv4=24 --node-cidr-mask-size-ipv6=96, but the podCidr my node got was still a /64 mask
```
 ps -ef | grep kube-co
root     31173 31148  4 08:44 ?        00:00:03 kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf --bind-address=127.0.0.1 --client-ca-file=/etc/kubernetes/pki/ca.crt --cluster-cidr=10.100.0.0/16,fc00::/48 --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt --cluster-signing-key-file=/etc/kubernetes/pki/ca.key --controllers=*,bootstrapsigner,tokencleaner --feature-gates=IPv6DualStack=true --kubeconfig=/etc/kubernetes/controller-manager.conf --leader-elect=true --node-cidr-mask-size-ipv4=24 --node-cidr-mask-size-ipv6=96 --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --root-ca-file=/etc/kubernetes/pki/ca.crt --service-account-private-key-file=/etc/kubernetes/pki/sa.key --service-cluster-ip-range=10.200.0.0/16,fc00:bb::/112 --use-service-account-credentials=true
```
```
kubectl get nodes k8s02-01 -o go-template --template='{{range .spec.podCIDRs}}{{printf "%s\n" .}}{{end}}'
10.100.0.0/24
fc00::/64
```
**What you expected to happen**:
The mask the node gets should be the /96 I set
**How to reproduce it (as minimally and precisely as possible)**:
Deploy the cluster using kubeadm, which is configured as follows。And modify the network-plugin of kubelet to be kubenet。
```
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: 6zjer1.8vjotkfp4c7ihtf8
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 202.173.9.10
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: k8s02-01
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager:
  extraArgs:
    cluster-cidr: 10.100.0.0/16,fc00::/48
    service-cluster-ip-range: 10.200.0.0/16,fc00:bb::/112
    node-cidr-mask-size-ipv4: "24"
    node-cidr-mask-size-ipv6: "96"
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
featureGates:
  IPv6DualStack: true
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.17.0-beta.2
networking:
  dnsDomain: cluster.local
  podSubnet: 10.100.0.0/16,fc00::/48
  serviceSubnet: 10.200.0.0/16,fc00:bb::/112
scheduler: {}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
featureGates:
  SupportIPVSProxyMode: true
  IPv6DualStack: true
mode: ipvs
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.0-beta.2", GitCommit:"c97baa339b5043424522dc7932fc3891f15543cb", GitTreeState:"clean", BuildDate:"2019-11-20T04:28:16Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
KVM virtual machine
- OS (e.g: `cat /etc/os-release`):
VERSION="18.04.2 LTS (Bionic Beaver)"
- Kernel (e.g. `uname -a`):
Linux k8s02-01 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
