### ISSUE TITLE
networkpolicy doens't work, only refuese request, cannot accept request from white list

### ISSUE THREAD

**Issue by xieyanker** [kubernetes/kubernetes#85539]
**What happened**:

The networkpolicy doesn't work, only refuese request, cannot accept request from white list.

**What you expected to happen**:

The networkpolicy should refuese other request, and accept request from white list.

**How to reproduce it (as minimally and precisely as possible)**:

```shell
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl create ns test1 
namespace/test1 created
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl create ns test2
namespace/test2 created
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl get ns|grep test
test1             Active   8s
test2             Active   5s
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl label ns test1 ns=test1
namespace/test1 labeled
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl get ns --show-labels|grep test
test1             Active   55s   ns=test1
test2             Active   52s   <none>
```
Create the `pod`'s yaml file as follows: 
```yaml
---
kind: Pod
apiVersion: v1
metadata:
  namespace: test1
  name: test-nginx1
  labels:
    app: test-nginx1
spec:
  nodeSelector:
    kubernetes.io/hostname: master1
  containers:
  - name: test-nginx1
    image: nginx
  tolerations:
  - key: pro
    operator: Equal
    value: master
    effect: NoSchedule
---
kind: Pod
apiVersion: v1
metadata:
  namespace: test2
  name: test-nginx2
  labels:
    app: test-nginx2
spec:
  nodeSelector:
    kubernetes.io/hostname: master2
  containers:
  - name: test-nginx2
    image: nginx
  tolerations:
  - key: pro
    operator: Equal
    value: master
    effect: NoSchedule
```
```shell
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl apply -f nginx_pod_nwp.yaml 
pod/test-nginx1 created
pod/test-nginx2 created
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl get pod -ntest1 -owide --show-labels
NAME          READY   STATUS    RESTARTS   AGE     IP              NODE      NOMINATED NODE   READINESS GATES   LABELS
test-nginx1   1/1     Running   0          2m54s   10.151.162.25   master1   <none>           <none>            app=test-nginx1
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl get pod -ntest2 -owide --show-labels
NAME          READY   STATUS    RESTARTS   AGE     IP              NODE      NOMINATED NODE   READINESS GATES   LABELS
test-nginx2   1/1     Running   0          2m57s   10.151.208.54   master2   <none>           <none>            app=test-nginx2
```
ping `test-nginx2` from `test-nginx1`, it's connected.
```
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl exec -it test-nginx1   sh -ntest1
# apt-get update
# apt-get install iputils-ping
# ping  10.151.208.54 
PING 10.151.208.54 (10.151.208.54): 56 data bytes
64 bytes from 10.151.208.54: icmp_seq=0 ttl=62 time=0.463 ms
^C--- 10.151.208.54 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.463/0.463/0.463/0.000 ms
# exit
```
Then, create the `networkpolicy`'s yaml file as follows:
```yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: test-nginx-policy
  namespace: test2
spec:
  podSelector:
    matchLabels:
      app: test-nginx2
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: test-nginx1
      namespaceSelector:
        matchLabels:
          ns: test1
```
```shell
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl apply -f nwp.yaml 
networkpolicy.extensions/test-nginx-policy created
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl get networkpolicy -A 
NAMESPACE   NAME                POD-SELECTOR      AGE
test2       test-nginx-policy   app=test-nginx2   4m57s
root@inspurtest14-wxhqn85ukg-master-1:~# 
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl get networkpolicy -A -oyaml
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: NetworkPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"extensions/v1beta1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"test-nginx-policy","namespace":"test2"},"spec":{"ingress":[{"from":[{"namespaceSelector":{"matchLabels":{"ns":"test1"}},"podSelector":{"matchLabels":{"app":"test-nginx1"}}}]}],"podSelector":{"matchLabels":{"app":"test-nginx2"}}}}
    creationTimestamp: "2019-11-22T09:42:38Z"
    generation: 1
    name: test-nginx-policy
    namespace: test2
    resourceVersion: "5402343"
    selfLink: /apis/extensions/v1beta1/namespaces/test2/networkpolicies/test-nginx-policy
    uid: 6be5f206-0d0c-11ea-a748-fa163e59946d
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            ns: test1
        podSelector:
          matchLabels:
            app: test-nginx1
    podSelector:
      matchLabels:
        app: test-nginx2
    policyTypes:
    - Ingress
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
Only one `networkpolicy` in the cluster. However I cannot ping `test-nginx2` connect from `test-nginx1` any more.
```shell
root@inspurtest14-wxhqn85ukg-master-1:~# kubectl exec -it  test-nginx1 sh -ntest1
# ping 10.151.208.54
PING 10.151.208.54 (10.151.208.54): 56 data bytes
^C--- 10.151.208.54 ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
```
**Environment**:
- Kubernetes version (use `kubectl version`):
```shell
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"$Format:%H$", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
```shell
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```shell
Linux inspurtest14-wxhqn85ukg-master-1 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Network plugin and version (if this is a network-related bug):
My Network plugin is calico v3.8.0
```shell
Client Version:    v3.8.0
Git commit:        c84e9f21
Cluster Version:   v3.8.0
Cluster Type:      kubespray,bgp,k8s
```
