### ISSUE TITLE
OpenAPIV3Schema validation for password field

### ISSUE THREAD

**Issue by sniranjan** [kubernetes/kubernetes#85578]
I am trying to create a new CRD with a password field as shown below

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tests.abc.com
spec:
  group: abc.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: tests
    singular: test
    kind: Test
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            user:
              type: string
            password:
              type: password
  additionalPrinterColumns:
    - name: User
      type: string
      description: The user who created this object
      JSONPath: .spec.user
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
```
When I try to create a new object

```
apiVersion: abc.com/v1
kind: Test
metadata:
  name: test
spec:
  user: john
  password: aGVsbG93b3JsZA==

```

**What happened**:

When I try to do `kubectl apply -f test.yaml`

I get the below error

```
The Test "test" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"abc.com/v1", "kind":"Test", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"abc.com/v1\",\"kind\":\"Test\",\"metadata\":{\"annotations\":{},\"name\":\"test\"},\"spec\":{\"password\":\"MWYyZDFlMmU2N2Rm\",\"user\":\"john\"}}\n"}, "creationTimestamp":"2019-11-24T01:24:24Z", "generation":1, "name":"test", "uid":"267b100d-0e59-11ea-8341-42010a80018e"}, "spec":map[string]interface {}{"password":"aGVsbG93b3JsZA==", "user":"john"}}: validation failure list:
spec.password in body must be of type password: "string"
```

Am I missing something? My understanding was any string I provide should now be treated as a password and not exposed in kubectl get and describe commands but it returns me an error saying it should be on type password. Can someone pls clarify?

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.17", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-13T20:47:11Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`):

**Comment by liggitt** [comment]
"password" is not a valid type. When trying to create custom resources, the type validation fails. 

this validation was improved in the v1 CRD API, and would reject creation of the CRD with a more useful error message

/close

**Comment by liggitt** [comment]
Type must be one of the following types:
string
number
integer
boolean
array
object

**Comment by sniranjan** [comment]
Thank you @liggitt. I am trying to hide the password field from displaying in kubectl describe command. After reading your comment, I realized I am using the wrong type and updated it as below

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tests.abc.com
spec:
  group: abc.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: tests
    singular: test
    kind: Test
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            user:
              type: string
            password:
              type: string <------- Updated this
              format: password <------- Updated this

  additionalPrinterColumns:
    - name: User
      type: string
      description: The user who created this object
      JSONPath: .spec.user
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
```

Reference- https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#format. 
I am now able to create the object but I am still able to see the password field when I describe on it. 

```
niranjan@macbook tests % kubectl describe tests/test
Name:         test
Namespace:
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"abc.com/v1","kind":"Test","metadata":{"annotations":{},"name":"test"},"spec":{"password":"aGVsbG93b3JsZA==","use...
API Version:  abc.com/v1
Kind:         Test
Metadata:
  Creation Timestamp:  2019-11-24T05:34:22Z
  Generation:          1
  Resource Version:    10614051
  Self Link:           /apis/abc.com/v1/tests/test
  UID:                 119decbd-0e7c-11ea-8341-42010a80018e
Spec:
  **Password:  aGVsbG93b3JsZA==**
  User:      john
Events:      <none>
```
