### ISSUE TITLE
startTime on pod is misleading with preemptible nodes

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#85579]
**What happened**:
I turned on pre-emptible nodes in GKE. After 24hr my pods restart as expected. However, the `startTime` of the pods does not.

A snippet from the pod status showing this:
```yaml
  initContainerStatuses:
  - containerID: docker://8c650d761a5955f624cddfcc6e22522a57dcb11c51f1f3bedb7d37fbab88d48c
    image: istio/proxyv2:1.4.0
    imageID: docker-pullable://istio/proxyv2@sha256:9ba9de87d660767a2147f786040a8fe29ebb3b335742d3c95257ab82a33b8415
    lastState: {}
    name: istio-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://8c650d761a5955f624cddfcc6e22522a57dcb11c51f1f3bedb7d37fbab88d48c
        exitCode: 0
        finishedAt: "2019-11-23T16:14:35Z"
        reason: Completed
        startedAt: "2019-11-23T16:14:35Z"
  phase: Running
  podIP: 10.28.2.3
  qosClass: Burstable
  startTime: "2019-11-21T16:27:17Z"
```

You can see the startTime is 2 days before the initContainer started, because it was restarted.

This makes it super hard to understand what is going on. I spent hours debugging because I saw the time was old so I "knew" it had not restarted.

**What you expected to happen**:

startTime is reset when pod is restarted, or this is documented somewhere if this is desired for whatever reson

**How to reproduce it (as minimally and precisely as possible)**:

Enable preemptible nodes on GKE and wait a day. I tried to simulate this directly but I couldn't figure out exactly what GKE is doing to get this behavior.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.8-gke.17
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): COS
