### ISSUE TITLE
How to mount a storage volume with Windows 10 Docker Desktop k8s

### ISSUE THREAD

**Issue by wxq851685279** [kubernetes/kubernetes#85593]
```
 volumes:
  - name: test-volume
    hostPath:
      path: D:/test-data
      type: Directory
```

This can't be written, how should I write it?
