### ISSUE TITLE
Deployments provide wrong observedGeneration when serviceaccount doesn't exist

### ISSUE THREAD

**Issue by willthames** [kubernetes/kubernetes#85591]
**What happened**:
Updated a deployment that still referenced a deleted service account

**What you expected to happen**:
The deployment would not increase observedGeneration to match generation. 

Some obvious mechanism of detecting this failure in the default output of `kubectl get pods` (e.g. `ContainerCreating`) 

**How to reproduce it (as minimally and precisely as possible)**:

* Run in the following two manifests using `kubectl apply -f`
* Run `kubectl get pods -n sa-test`
* Run `kubectl delete serviceaccount kuard -n sa-test`
* Update the second manifest (e.g. change `0.10.0-green` to `0.10.0-purple`) and remove the ServiceAccount definition (but keep `serviceAccountName` in the pod spec)
* Run the second manifest in again
* Run `kubectl get pods -n sa-test` - the result should be the same as previously
* Run `kubectl get deploy -n sa-test kuard -o yaml` - `observedGeneration` will have increased even though the new replicaset is not available at all

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sa-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuard
  namespace: sa-test
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  namespace: sa-test
spec:
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      serviceAccountName: kuard
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:v0.10.0-green

```

**Anything else we need to know?**:
I rely on the observedGeneration matching the generation to validate that deployments have been correctly updated. If there is a better way of doing this, and I'm doing it wrong, let me know 

This is coded into Ansible's k8s module for example:
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/k8s/raw.py#L466-L471
so I'd be keen to correct that if I've coded it wrong (that logic works in every other scenario that I've come across previously)

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`):
This is a custom kernel patched with the scheduling fix in #67577 , but I'm pretty sure that's unrelated to this issue
```
Linux ip-172-22-14-143.us-west-2.compute.internal 5.3.1 #1 SMP Tue Oct 1 01:15:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: terraform
- Network plugin and version (if this is a network-related bug):
- Others:
