### ISSUE TITLE
volumeDevices mapping ignored when container is privileged

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#85624]
**What happened**:
When using the raw block PV feature, if your container is privileged, then the volumeDevices.devicePath specified in the Pod spec are silently ignored by the container runtime since all host devices are mapped into the container at /dev.

This is an issue with the raw block feature since its inception and impacts all volume plugins and most runtimes (docker, containerd to name a few)

**What you expected to happen**:
At least when the container's devicePath is non-conflicting with the host (ie not in /dev), it should be mapped correctly. 

I'm on the fence about what should happen if the devicePath is "/dev". Disallowing "/dev" entirely would be a breaking change (even though it's pretty non-functional today).  Overriding "/dev" could also be a breaking change?

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: v1
kind: Pod 
metadata:
  name: test
spec:
  containers:
  - image: debian:latest
    imagePullPolicy: IfNotPresent
    name: nginx
    command: ["/bin/sh"]
    args:
      - "-c"
      - "while true; do sleep 10;done"
    securityContext:
      privileged: true
    volumeDevices:
    - devicePath: /my-disk
      name: disk1
  volumes:
  - name: disk1
    persistentVolumeClaim:
      claimName: disk1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk1
spec:
  volumeMode: Block
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi 
```

**Anything else we need to know?**:
Current workaround for this issue is to have an unprivileged init container that copies the devices to an emptydir shared with the privileged container.

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs @kubernetes/sig-node-bugs

**Comment by msau42** [comment]
cc @jsafrane @Random-Liu

**Comment by pohly** [comment]
I agree, paths outside `/dev` should be there. I just hit that issue and I had intentionally chosen `/dax-dev` (i.e. a path elsewhere) to ensure that the host's `/dev` can be made available without running into conflicts.

**Comment by pohly** [comment]
> Current workaround for this issue is to have an unprivileged init container that copies the devices to an emptydir shared with the privileged container.

That workaround may or may not work:
```
sh-5.0# ls -l /dax-dev 
brw-rw-rw- 1 root root 252, 0 Dec  3 11:08 /dax-dev
sh-5.0# cp -a /dax-dev /data
cp: cannot create special file '/data/dax-dev': Operation not permitted
sh-5.0# touch /data/testfile
Try 'mknod --help' for more information.
sh-5.0# mknod /data/dax-dev b 252 0              
mknod: /data/dax-dev: Operation not permitted
```

`dev-dax` is the block device here, `/data` is a writable empty dir.

I have seen this work with a different Linux kernel (Fedora) and runtime (Docker instead of cri-o), so it all depends on how strict the container runtime restricts potentially problematic operations (like creating a device node) inside a non-privileged container.

**Comment by akhilerm** [comment]
> so it all depends on how strictly the container runtime restricts potentially problematic operations (like creating a device node) inside a non-privileged container.

@pohly  It works only if the container has CAP_MKNOD capability. If by default the container-runtime gives this CAP, then copying the device file may work.

**Comment by akhilerm** [comment]
Another workaround that I got from [Moby](https://dockercommunity.slack.com/archives/C50QFMRC2/p1575402291070700) is using the `-v` flag to get the device node inside the container. In k8s terms, that will translate to using `volumeMounts` with `/dev/sdX` instead of `volumeDevices`. Since the container is privileged it will be possible to perform all operations on the blockdevice similar to in the case of using `--device`

**Comment by akhilerm** [comment]
This issue has been fixed in docker in PR [#40291](https://github.com/moby/moby/pull/40291)

**Comment by dims** [comment]
@akhilerm is this just a docker only issue? what happens when someone uses containerd as the CRI directly?

**Comment by msau42** [comment]
/remove-lifecycle stale
That's great news! And yes, we should make sure it gets fixed in containerd too.

**Comment by akhilerm** [comment]
@dims the issue was with how docker builds the container spec from docker daemon. I will check with containerd to see how it is handled.

**Comment by msau42** [comment]
@akhilerm did you get a chance to followup with containerd?
/remove-lifecycle stale

**Comment by akhilerm** [comment]
@msau42 Sorry for the delay. 

I tried with creating a container directly with containerd and was not able to hit the issue.

containerd version: 1.3.7

**Comment by MrAmbiG** [comment]
This still fails if the block is rwx (readwritemany).

**Comment by qiutongs** [comment]
@akhilerm Can you share how you checked this issue with containerd?

**Comment by qiutongs** [comment]
I looked into containerd code and reproduced the issue. So I believe containerd also suffers this problem and we should apply similar fix as docker. 

## Containerd Code

From containerd cri code, it will add all host devices in privileged mode, only if PrivilegedWithoutHostDevices config is set to false. Otherwise, it will only add configured device mapping. 

https://github.com/containerd/containerd/blob/b3f2402062e9ea23cd8f7994982ffa77c4440e26/pkg/cri/server/container_create_linux.go#L216-L221

Regarding PrivilegedWithoutHostDevices, it is a containerd cri config: https://github.com/containerd/containerd/blob/master/docs/cri/config.md. And its default value is false.

## Local Verification

I created a PersistentVolume, PersistentVolumeClaim and Pod, similarly as [this](https://github.com/kubernetes/kubernetes/issues/85624#issue-528452717). I verified when PrivilegedWithoutHostDevices is false, all host devices are in container and the volumeDevices is ignored in privileged mode; when PrivilegedWithoutHostDevices is true, no host devices are in container but the volumeDevices is honored. 

```
# PrivilegedWithoutHostDevices is true:

$  cluster/kubectl.sh exec --stdin --tty test -- /bin/sh
# ls /dev
core  fd  full	mqueue	null  ptmx  pts  random  shm  stderr  stdin  stdout  termination-log  tty  urandom  zero
# ls /my-disk
/my-disk
```

My take is that PrivilegedWithoutHostDevices is a nice feature but doesn't solve the problem in this issue.

**Comment by akhilerm** [comment]
> Can you share how you checked this issue with containerd?

@qiutongs I tested by manually creating a container using containerd, same way it was tested with docker. Think I missed something there.

**Comment by xigifty** [comment]
Still facing this issue, any help is much appreciated.  

**securityContext:
privileged: true**
I had that above attribute, if its set to true, the blockMount is not visible.. 

sh-4.2# cd /mnt/ 
sh-4.2# ls
fileMount  nbcfg  nbdata  nblogs. **MISSING blockMount when its privileged on**
**securityContext:
privileged: false**
kubectl exec -it pod-gke-initial -n abcd1 /bin/sh
sh-4.2# cd /mnt/
sh-4.2# ls
blockMount  fileMount  nbcfg  nbdata  nblogs **FOUND blockMount when privileged off**.  Attaching the entire spec file, and the pod logs with this feature on or off, the logs are still same stating its created successful. 

```
---
kind: Namespace
apiVersion: v1
metadata:
  name: abcd1
  labels:
    name: abcd1

---
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-pool-cluster-x1
  namespace: openebs
spec:
  pools:
   - nodeSelector:
       kubernetes.io/hostname: "k8sworkernode02.x"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-3c50e05a4909ab19732458394da6ddeb"
     poolConfig:
       dataRaidGroupType: "stripe"
   - nodeSelector:
       kubernetes.io/hostname: "k8sworkernode01.x"
     dataRaidGroups:
       - blockDevices:
           - blockDeviceName: "blockdevice-e61a27669014189472062dfeea372cb1"
     poolConfig:
       dataRaidGroupType: "stripe"


---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cstor-storage-class-x1
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"          
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: cstor
  # cstorPoolCluster should have the name of the CSPC
  cstorPoolCluster: cstor-pool-cluster-x1
  # replicaCount should be <= no. of CSPI
  replicaCount: "2"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gke-block
  namespace: abcd1
spec:
  storageClassName: cstor-storage-class-x1
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gke-file
  namespace: abcd1
spec:
  storageClassName: cstor-storage-class-x1
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi


---
apiVersion: v1
kind: Pod
metadata:
  name: pod-gke-initial
  namespace: abcd1
spec:
  volumes:
    - name: pod-gke-file-vol
      persistentVolumeClaim:
        claimName: pvc-gke-file
    - name: pod-gke-block-vol
      persistentVolumeClaim:
        claimName: pvc-gke-block
  containers:
  - name: nbu-client
    image: ubuntu
    command:
      - "/bin/bash"
      - "-c"
      - "sleep infinity"
    securityContext:
      privileged: true
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /mnt/fileMount
        name: pod-gke-file-vol
        readOnly: false
    volumeDevices:
      - devicePath: /mnt/blockMount
        name: pod-gke-block-vol
```

**Comment by unix-way** [comment]
Facing same issue - block persistent volumes are ignored when a pod is running in privileged mode. Currently using GKE 1.21.9. Host device availability inside the pod can't be relied upon for obvious reasons, one being that device "mounts" inside `/dev` are not guaranteed to be the same when persistent volumes get re-attached to another node.

**Comment by jingxu97** [comment]
@unix-way could you put more details about the issue you are seeing?

**Comment by unix-way** [comment]
@jingxu97 

Suppose we have the following manifest

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: ubuntu:20.04
    securityContext:
      privileged: true
    command:
      - /usr/bin/sleep
    args:
      - infinity
    name: test-container
    volumeDevices:
    - devicePath: /disks/ssd1
      name: ssd1
    volumeMounts:
    - mountPath: /disks/nvme0n1
      name: nvme0n1
  volumes:
  - name: ssd1
    persistentVolumeClaim:
      claimName: ssd1
  - name: nvme0n1
    hostPath:
      path: /dev/disk/by-id/google-local-ssd-0
      type: BlockDevice

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd1
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
```

When I then run `kubectl exec test-pod -- ls -l /disks` I get
```
total 0
brw-rw---- 1 root disk 8, 16 Apr  5 23:13 nvme0n1
```

So `ssd1` mount is ignored in privileged mode and the device is instead available directly at `/dev/sdf`, which is completely arbitrary - next time it may be `/dev/sdg` or `/dev/sdh`, depending on what other PVs are attached to the pod.

```
➜  ~ kubectl exec test-pod -- lsblk
NAME    MAJ:MIN RM    SIZE RO TYPE MOUNTPOINT
loop0     7:0    0      1G  0 loop
sda       8:0    0      1T  0 disk
|-sda1    8:1    0 1019.9G  0 part /etc/resolv.conf
|-sda2    8:2    0     16M  0 part
|-sda3    8:3    0      2G  0 part
|-sda4    8:4    0     16M  0 part
|-sda5    8:5    0      2G  0 part
|-sda6    8:6    0    512B  0 part
|-sda7    8:7    0    512B  0 part
|-sda8    8:8    0     16M  0 part
|-sda9    8:9    0    512B  0 part
|-sda10   8:10   0    512B  0 part
|-sda11   8:11   0      8M  0 part
`-sda12   8:12   0     32M  0 part
sdb       8:16   0    375G  0 disk
sdc       8:32   0    375G  0 disk
sdd       8:48   0    375G  0 disk
sde       8:64   0    375G  0 disk
sdf       8:80   0      1G  0 disk
➜  ~ kubectl exec test-pod -- ls -l /dev/sdf
brw-rw---- 1 root disk 8, 80 Apr  7 01:43 /dev/sdf
```

However if I change `privileged` to **false**, `ssd1` is mounted successfully
```
➜  ~ kubectl exec test-pod -- ls -l /disks
total 0
brw-rw---- 1 root disk 8, 16 Apr  5 23:13 nvme0n1
brw-rw---- 1 root disk 8, 80 Apr  7 01:35 ssd1
```

But in this case I can't do anything with `nvme0n1` because unprivileged pods are not allowed to write to block devices mounted as a hostPath (naturally, I need both devices writable).

**Comment by msau42** [comment]
It looks like this issue has been fixed in both docker, and containerd (v1.6.0)

**Comment by mattcary** [comment]
I've done a little local testing and it seems 1.5.11 (as present in GKE 1.23) is sufficient. The following simpler repro works in 1.23+, but /disks/ doesn't appear in 1.22.

```
apiVersion: v1
kind: Pod
metadata:
  name: block-ssd
spec:
  containers:
  - image: busybox
    securityContext:
      privileged: true
    command:
      - sleep
    args:
      - infinity
    name: busy
    volumeDevices:
    - devicePath: /disks/ssd
      name: ssd
  volumes:
  - name: ssd
    persistentVolumeClaim:
      claimName: ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd
spec:
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi
```
