### ISSUE TITLE
Incorrect validation result of NetworkPolicy PolicyTypes 

### ISSUE THREAD

**Issue by tnqn** [kubernetes/kubernetes#85746]
**What happened**:
Create a NetworkPolicy with one typo PolicyType and a correct one.
The apiserver will report error but will also say the correct one is unsupported.
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: typo-policy
spec:
  podSelector:
    matchLabels:
      run: nginx
  policyTypes:
  - Ingress
  - Egres
```
Output:
```
The NetworkPolicy "typo-policy" is invalid: 
* spec.policyTypes[0]: Unsupported value: "Ingress": supported values: "Ingress", "Egress"
* spec.policyTypes[1]: Unsupported value: "Egres": supported values: "Ingress", "Egress"
```
It says `Ingress` is unsupported.

**What you expected to happen**:
It shouldn't say the correct policyType `Ingress` is unsupported.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the above yaml.

**Anything else we need to know?**:
It's because an excess nested loop is added to validation function: https://github.com/kubernetes/kubernetes/blob/cf16e4988f58a5b816385898271e70c3346b9651/pkg/apis/networking/validation/validation.go#L124-L131

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
