### ISSUE TITLE
Server type: NodePort can't be accessed outside cluster

### ISSUE THREAD

**Issue by lucasOliveira91** [kubernetes/kubernetes#85757]
I've seen a lot answers with subject seems like that but nothing can help me.
I've configured the cluster kubernetes in three servers, i can do deploy through jenkins my apps are started without errors.
Into the server master i can run curl <my ipserver>:30000 and this way i can see the application is up.
but when i try to access outside the server, it's occurs connection time out.

My deployment.yaml:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: postalis-online-frontend
  labels:
    app: postalis-online-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: postalis-online-frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postalis-online-frontend-deployment
  labels:
    app: postalis-online-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postalis-online-frontend
  template:
    metadata:
      labels:
        app: postalis-online-frontend
    spec:
      containers:
        - name: postalis-online-frontend
          image: "foguetinho.postalis.org.br:5001/postalis-online-frontend:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: my-secret
```
My deployed applications, there are two with two instances each one.

![image](https://user-images.githubusercontent.com/38402354/69890605-6deffd80-12d5-11ea-81e3-63549e6bdcfd.png)

my iptables, i realized that it's missing chain for the kubernetes
![image](https://user-images.githubusercontent.com/38402354/69890648-a099f600-12d5-11ea-82ef-f780c442a144.png)

I think can be something simple that i forgot to configure
I need help i've tried to solve this a lot over the internet through searches
