### ISSUE TITLE
How to mount a storage volume with Windows 10 Docker Desktop k8s

### ISSUE THREAD

**Issue by wxq851685279** [kubernetes/kubernetes#85842]
**What happened**:
windows10 mount storage volume unsuccessful
**What you expected to happen**:
windows10 mount storage volume
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.15.5
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): windows10 1903
- Kernel (e.g. `uname -a`): 
- Install tools: Docker for Desktop
- Network plugin and version (if this is a network-related bug):
- Others:

```
 volumes:
  - name: test-volume
    hostPath:
      path: D:/test-data
      type: Directory
```

This can't be written, how should I write it?

**Comment by athenabot** [comment]
/sig windows

These SIGs are my best guesses for this issue. Please comment `/remove-sig <name>` if I am incorrect about one.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by khs1994** [comment]
```yaml
 volumes:
  - name: test-volume
    hostPath:
      path: /D/test-data
      type: Directory
```
