### ISSUE TITLE
preStop does not work with a cronJob

### ISSUE THREAD

**Issue by fahedouch** [kubernetes/kubernetes#85884]
**What happened**:
I want to use life cycle hook `preStop` with cronjob. But the cronJob dosen't run at all

this is the spec :
````
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: release-name-box-reload-setting
  labels:
    app.kubernetes.io/name: box-reload-setting
    helm.sh/chart: box-reload-setting-0.1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
spec:
  concurrencyPolicy: Forbid
  schedule: "0/1 * * ? *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: box-reload-setting
            app.kubernetes.io/instance: release-name
        spec:
          containers:
            - name: box-reload-setting
              image: xxxxxx/box-reload-setting-batch:BOX_RELOAD_SETTING_VERSION
              lifecycle:
                preStop:
                exec:
                  command: ["/bin/sh", "-c", "touch /tmp/pod/terminated"]
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: release-name-box-reload-setting-envs
              resources:
                limits:
                  cpu: 2
                  memory: 2Gi
                requests:
                  cpu: 250m
                  memory: 1500Mi
              volumeMounts:
                - mountPath: /tmp/pod
                  name: tmp-pod
                - name: app-logs
                  mountPath: /app-logs
                - name: app-config
                  subPath: bootstrap.yml
                  mountPath: /opt/box-reload-setting/conf/bootstrap.yml
                - name: app-config
                  subPath: log4j2.xml
                  mountPath: /opt/box-reload-setting/conf/log4j2.xml
            - name: box-reload-setting-fluent-shipper
              image: xxxxxx/fluent-bit:1.2.2
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
              - |
                (while true; do if [[ -f "/tmp/pod/terminated" ]]; then kill $$; echo "Killed $$ because the main container terminated."; fi; sleep 1; done)
              env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: BACKDOOR_PORT
                  value: "6666"
              volumeMounts:
                - mountPath: /tmp/pod
                  name: tmp-pod
                - name: fluent-config
                  mountPath: /fluent-bit/etc
                - name: app-logs
                  mountPath: /app-logs
          volumes:
          - name: app-config
            configMap:
              name: release-name-box-reload-setting-config
          - name: tmp-pod
            emptyDir: {}
          - name: app-logs
            emptyDir: {}
          - name: fluent-config
            configMap:
              name: release-name-box-reload-setting-fluent
          restartPolicy: Never
`````

**What you expected to happen**:
execute the touch command whitin the graceful shutdown period.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
In perfect world, to garantie the execution of preStop hook we should have this :
``t(containerProcess)  < t(preStopProcess) < t(TerminationGracePeriod)``
I think that in the cronJob  object the TerminationGracePeriod is not effective, so the preStop script doesn't have time to be executed..

Waiting for your opinions.. 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.10-gke.17
- Cloud provider or hardware configuration: google cloud
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
