### ISSUE TITLE
Service of type "LoadBalancer" accessible from within the pod, but not accessible from outside the cluster

### ISSUE THREAD

**Issue by sahilmalav** [kubernetes/kubernetes#85902]
I have deployed a service on Kubernetes using the below yaml : 

```
kind: Service
apiVersion: v1
metadata:
  name: dt-infer
  labels:
    app: dt-infer
    service: dt-infer
spec:
  ports:
    - name: default
      port: 5000
  selector:
    app: dt-infer
  type: LoadBalancer
```

The service runs a flask server on port 5000 at entrypoint and does predictions for incoming requests at the route '/predict'. Below is the output of "kubectl describe ... " :  

```
Name:                     dt-infer
Namespace:                rossman-sales-project
Labels:                   app=dt-infer
                          service=dt-infer
Annotations:              <none>
Selector:                 app=dt-infer
Type:                     LoadBalancer
IP:                       10.108.43.206
Port:                     default  5000/TCP
TargetPort:               5000/TCP
NodePort:                 default  31240/TCP
Endpoints:                10.244.1.54:5000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

```

When I make curl requests from within the pod, I get expected results. 
```
curl -X POST   http://localhost:5000/predict   -H 'Content-Type: application/json'   -H 'Postman-Token: 6367b442-6b8b-458e-aa6f-b388c4427aef'   -H 'cache-control: no-cache'   -d '{"input": [1.2410, 1, 2, 3, 1]}'
{"message":"success","results":[9537.232421875]}
```

But when I do the same from outside the cluster, it fails. (172.16.3.51 is my cluster IP)
```
curl -X POST   172.16.3.51:31240/predict   -H 'Content-Type: application/json'   -H 'Postman-Token: 6367b442-6b8b-458e-aa6f-b388c4427aef'   -H 'cache-control: no-cache'   -d '{"input": [1.2410, 1, 2, 3, 1]}'
curl: (52) Empty reply from server
```
I've checked everything thoroughly and things seem alright to me. What is the reason for this behaviour? Am I missing something?
