### ISSUE TITLE
Migrate OWNERS file to apply the area/provider/gcp label, not sig/gcp

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#85919]
Some owners files attempt to auto apply the no longer existing `sig/gcp` label, which is now `area/provider/gcp`:

https://github.com/kubernetes/test-infra/pull/13677

This is present in 4 owners files:

https://github.com/kubernetes/kubernetes/search?q=%22sig%2Fgcp%22&unscoped_q=%22sig%2Fgcp%22

/assign @MrHohn @tallclair @x13n @mtaufen 

/area oncall-hotlist

```yaml
{
 insertId: "f9t4b6g2q7sd4z"  
 jsonPayload: {
  author: "pjh"   
  component: "hook"   
  event-GUID: "2efce600-16e1-11ea-9d2c-aeed2c99d7e8"   
  event-type: "pull_request"   
  file: "prow/plugins/owners-label/owners-label.go:119"   
  func: "k8s.io/test-infra/prow/plugins/owners-label.handle"   
  level: "warning"   
  msg: "Unable to add nonexistent labels: ["sig/gcp"]"   
  org: "kubernetes"   
  plugin: "owners-label"   
  pr: 85466   
  repo: "kubernetes"   
  url: "https://github.com/kubernetes/kubernetes/pull/85466"   
 }
 labels: {…}  
 logName: "projects/k8s-prow/logs/hook"  
 receiveTimestamp: "2019-12-04T22:00:00.566786830Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-12-04T21:59:55Z"  
}
```
