### ISSUE TITLE
kubectl get pods doesnt show apiserver pod after enabling PodSecurityPolicy plugin

### ISSUE THREAD

**Issue by Purushotham233** [kubernetes/kubernetes#85952]
**What happened**:
kubectl get pods doesnt show apiserver pod after enabling PodSecurityPolicy plugin

**What you expected to happen**:
Kubectl to list apiserver pod.

**How to reproduce it (as minimally and precisely as possible)**:
- Create the pod security pod as below. 
- Then enable the plugin by modifying /etc/kubernetes/manifests/kube-apiserver.yaml
- Check for apiserver pod.

```
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: 200-psp
spec:
  allowedCapabilities:
  - '*'
  allowPrivilegeEscalation: true
  fsGroup:
    rule: 'RunAsAny'
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - min: 0
    max: 65535
  privileged: false
  readOnlyRootFilesystem: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  volumes:
  - '*'
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration: VM in Private cloud, 8G & 4-cores.
- OS (e.g: `cat /etc/os-release`): debian/stretch
- Kernel (e.g. `uname -a`):Linux <host-name> 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
- Install tools: kubeadm

**Anything else we need to know?**:
Docker ps shows both the pause and apiserver containers running.
`
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS               NAMES

3abeb60641a1        201c7a840312                        "kube-apiserver --ad…"   32 minutes ago      Up 32 minutes                           k8s_kube-apiserver_kube-apiserver-sparrow-k8s-master-meta-cluster-1569916_kube-system_121a302d11a369848ff03f4e6ed12c83_0

a0822e656140        10.47.2.76:80/pause:3.1             "/pause"                 32 minutes ago      Up 32 minutes                           k8s_POD_kube-apiserver-sparrow-k8s-master-meta-cluster-1569916_kube-system_121a302d11a369848ff03f4e6ed12c83_0
`
