### ISSUE TITLE
Add Support to Deny RBAC Rules

### ISSUE THREAD

**Issue by diranged** [kubernetes/kubernetes#85963]
(_I am opening this ticket on behalf of the author of https://github.com/kubernetes/community/issues/4061 - because we are also having the same problem and it's problematic for us. The text in this ticket is a direct copy and paste_)

**What would you like to be added**:
Add `Kind: <Allow/Deny>` to the RBAC `Rules` key. Default to `Allow. Example:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ns
  name: role
rules:
  - kind: Allow
    apiGroups:
      - ''
      - apps
      - extensions
    resources:
      - '*'
    verbs:
      - '*'
  - kind: Deny
    apiGroups:
      - ''
    resources:
      - 'secrets'
    verbs:
      - 'get'
      - 'watch'
      - 'list'
```

**Why is this needed**:
The absence of denial rules in K8s makes it difficult or impracticable to restrict access while being permissive.

Some use cases would be:

Allow user to perform all actions that do not involve kube-system namespace. Including being able to create new namespaces and automatically have access granted to perform actions on it.
Prevent secrets from being accessed by some subject in a namespace and have access to custom resources without having to list all of them manually.

**Comment by diranged** [comment]
@kubernetes/sig-auth-feature-requests

**Comment by liggitt** [comment]
> The absence of denial rules in K8s makes it difficult or impracticable to restrict access while being permissive.

Something to keep in mind is that the presence of deny rules makes it difficult or impractical to add new resources or capabilities to the API, because a "* - something" approach presumes to know everything included in "*". The fact that something is being excluded indicates that the role is not intended to be a superuser role, but it is possible (even likely) that some resource or capability will be added in the future to "*" that is as powerful as the thing being excluded. That makes it unsafe to upgrade Kubernetes versions or adding new resources without auditing all new resources/capabilities and all roles containing deny rules.

**Comment by reubit** [comment]
I'm also very keen for this feature. I'm actually very surprised that there hasn't been more noise around this since RBAC was released. I've run into countless situations with RBAC rules where the ability to deny would have made things much easier. It's common place in other RBAC systems to provide deny rules (E.g. AWS IAM Policies).  I find it frustratingly unacceptable that the K8S docs simply say:
> Permissions are purely additive (there are no “deny” rules)

That's great.... but why?

The `allow all except kube-system` use-case in the description is definitely a good example. Another example that I'm facing at the moment is creating a role for the k8s-dashboard that has the effect of `allow all - deny kube-system read/write - deny secrets read/write - deny pod/exec`. Without the ability to define Deny rules, this gets frustratingly tricky, and your role ends up becoming ridiculously verbose.

@liggitt Whilst I understand the risk you are highlighting, I think it should be the responsibility of the admin to make sure you're covered as new resources/capabilities are released. However in the case where you want to create permissive roles, and only deny a small set of specific permissions, I think in most cases will probably want your `allow "*"` rules to automatically include the new resources/capabilities.

**Comment by mooperd** [comment]
+1 - I really need to be able to restrict access to the `kube-system`namespace.

**Comment by mitom** [comment]
Also here looking at the `kube-system` use-case.

@liggitt raises a very good point though - while deny permissions give use a lot of options, they introduce a lot of potential conflict as well. As a compromise, how about introducing a `ClusterRoleBinding` which would operate on selectors rather than exact namespace configuration, rather than a deny?

As an example:
```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-rolebinding
subjects:
- kind: User
  name: some-user
  apiGroup: rbac.authorization.k8s.io
namespaceSelector:
  team: my-team
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
```

which would operate on namespace labels, e.g it would provide access to all namespaces with a matching label:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: user-accessible-namespace
  labels:
    team: my-team
```

**Comment by enj** [comment]
@mitom that is pretty easy to build on top of kube using controllers to sync the role bindings, see https://github.com/FairwindsOps/rbac-manager#dynamic-namespaces-and-labels

**Comment by mooperd** [comment]
That would be a bit rough because it would mean a quite different user experience on locked down clusters. Anyone trying to deploy a helm template which includes a namespace would the thwarted as their new namespaces would not include the label. 

I think the ability to explicitly deny users access to namespaces such as kube-system or ingress-nginx is extremely important to ensuring that Kubernetes can thrive in more complex environments.

**Comment by PaulWBrassard** [comment]
+1 for kube-system use-case

To me, it seems very reasonable that `allow *` includes new resources and `deny` would need to be explicit on which resources are denied.

**Comment by iFreeon** [comment]
This would save a lot of time in administration overhead. 

In lower environments I want to empower development teams by giving them access to do everything except specific namespaces and secrets.  That usually translates into two use cases

I want to give a user:
1. Access to all namespaces except kube-system and the ingress controller namespace. 
2. In all namespaces (not restricted above) I don’t want the user to have access to specific secrets. For example Regcred.

Like others have mentioned, I’m puzzled why more people have not requested this and wonder if the answer is because many groups just give full admin to everyone.

**Comment by enj** [comment]
>     1. Access to all namespaces except kube-system and the ingress controller namespace.
>     2. In all namespaces (not restricted above) I don’t want the user to have access to specific secrets. For example Regcred.

Even if RBAC supported deny rules to allow you to express that, it would not matter because the Kubernetes API itself lacks any mechanism to return partial lists based on authorization.

**Comment by PaulWBrassard** [comment]
@enj This cannot be true based on the ability to write RBAC with allow rules for specifically named resources.
Source - https://kubernetes.io/docs/reference/access-authn-authz/rbac/
```
You can also refer to resources by name for certain requests through the resourceNames list. When specified, requests can be restricted to individual instances of a resource. Here is an example that restricts its subject to only get or update a ConfigMap named my-configmap:

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: configmap-updater
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing ConfigMap
  # objects is "configmaps"
  resources: ["configmaps"]
  resourceNames: ["my-configmap"]
  verbs: ["update", "get"]
```
