### ISSUE TITLE
Scheduler framework cannot disable default Predicate function

### ISSUE THREAD

**Issue by angao** [kubernetes/kubernetes#85986]
**What happened**:

scheduler framework cannot disable default in-tree `Predicate` function:
I create the config file as follows:
```
apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
schedulerName: sample
plugins:
  filter:
    disabled:
    - name: "NodeResourcesFit"
```
I found the `NodeResourcesFit` FilterPlugin is also effective and not disabled by config.

**What you expected to happen**:

 I want to know how to disable the in-tree framework plugins, include filter, scoring

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.0-rc.02
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
