### ISSUE TITLE
kubectl describe shows "<unset>" for Port

### ISSUE THREAD

**Issue by sdarwin** [kubernetes/kubernetes#86014]
**What happened**:

After creating a service with a specified port, the "kubectl describe" command shows it as:

```
Port:              <unset>  80/TCP
```

Why "unset"?  It was set in the yaml file.  
( this might be a question, and not a bug. :-)   )     

**What you expected to happen**:

```
Port:              80/TCP
```

**How to reproduce it (as minimally and precisely as possible)**:

test.yaml:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: echoserver
```

```
kubectl apply -f test.yaml
```

```
# kubectl describe service/echoserver -n echoserver
Name:              echoserver
Namespace:         echoserver
Labels:            <none>
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"echoserver","namespace":"echoserver"},"spec":{"ports":[{"port":80...
Selector:          app=echoserver
Type:              ClusterIP
IP:                100.70.11.181
Port:              <unset>  80/TCP
TargetPort:        8080/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-18T14:56:51Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:  AWS
- OS (e.g: `cat /etc/os-release`):
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
```
- Kernel (e.g. `uname -a`):
```
# uname -a
Linux jenkins 4.15.0-1056-aws #58-Ubuntu SMP Tue Nov 26 15:14:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools: kops

- Network plugin and version (if this is a network-related bug):
- Others:
