### ISSUE TITLE
allow the name of a secret/configmap to be retrieved/derived from an env variable

### ISSUE THREAD

**Issue by grozan** [kubernetes/kubernetes#86079]
**What would you like to be added**:

I would like to be able to have more flexibility with regards to choosing which configmap or secret to make available in a pod. Today the declaration of such a volume looks like

``` yaml
...
volumes:
- name: from-secret
  secret:
    secretName: my-secret
- name: from-configmap
  configMap:
    name: my-configmap
...
```
so the name of the secret/configmap are completely static. I'd like to be able to say something like

```
...
env:
- name: ENV1
  value: val1
- name: ENV2
  value: something-$(ENV1)
volumes:
- name: from-secret
  secret:
    secretName: $(ENV1)
- name: from-configmap
  configMap:
    name: foo-$(ENV2)
...
```

Today I can expand an env variable in another one (ENV2=something-val1) but I cannot use those ENV variables to dynamically mount different secrets or configmaps

**Why is this needed**:

My first use-case is as follows
I have a statefulset with 3 replicas. the pods are called `mything-0`, `mything-1` and `mything-2`. I want every pod to have its own set of secrets (certificates in my case). So I want to create 3 secrets, called like my pods, and automatically mount the right secret in the right pod.
I'd like something like

```
env:
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
volumes:
- name: my-certs
  secret:
    secretName: $(POD_NAME)
```

Besides the use-case of statefulset, and their stable pod identities that could be leveraged to mount pod-specific secrets, I think it generally would make it more flexible and easier in many other use-cases as well.

Like for example allow to easily switch between different configurations, at runtime, based on a `classification` ENV variable you set. 

```
env:
- name: classification
  value: prod
volumes:
- name: my-config-file
  configMap:
    name: $(classification)
```
