### ISSUE TITLE
RoleBinding doesn't accept a single letter ServiceAccount

### ISSUE THREAD

**Issue by nerusnayleinad** [kubernetes/kubernetes#86123]
I've been struggling with this error for almost an hour, until I realized you just can't bind a role to a service account with 1 letter.

So, for testing purposes, I sometimes create a namespace called `n`. This time I did the same with the service account, which got created with no problem:

```
root@master:~/rbac# kubectl get sa -nn
NAME      SECRETS   AGE
default   1         44m
n         1         44m
```

But later; when I was trying to create a `Role` and a `RoleBinding`, I was getting this error:

```
root@master:~/rbac# kubectl create -f rb.yaml 
Error from server (BadRequest): error when creating "rb.yaml": RoleBinding in version "v1beta1" cannot be handled as a RoleBinding: v1beta1.RoleBinding.Subjects: []v1beta1.Subject: v1beta1.Subject.Name: ReadString: expects " or n, but found f, error found in #10 byte of ...|","name":false,"name|..., bigger context ...|er"},"subjects":[{"kind":"ServiceAccount","name":false,"namespace":false}]}
|...
```

that I couldn't interpret. Finally, I added some more letters to the service account name (made it `nanana`), and it worked.

I believe it's a bug.

**Comment by nerusnayleinad** [comment]
@kubernetes/sig-api-machinery

**Comment by nerusnayleinad** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by tedyu** [comment]
The error seems to come from:
vendor/github.com/json-iterator/go/iter_str.go

Can you paste the contents of rb.yaml ?

Thanks

**Comment by nerusnayleinad** [comment]
Well, actually it fails with a 1 letter namespace too. So, 
**this one fails:**

```
$ kubectl create ns demo
$ kubectl create sa n -n demo
```

role.yaml

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cm-getter
rules:
- apiGroups: ["v1"]
  resources: ["configmaps"]
  verbs: ["get"]
```
`$ kubectl create -f role.yaml -nn`

> role.rbac.authorization.k8s.io/cm-getter created

rb.yaml

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cm-getter-binding
subjects:
- kind: ServiceAccount
  name: n
  namespace: demo
roleRef:
  kind: Role
  name: cm-getter
  apiGroup: ""
```

`$ kubectl create -f rb.yaml -nn`

> Error from server (BadRequest): error when creating "rb.yaml": RoleBinding in version "v1beta1" cannot be handled as a RoleBinding: v1beta1.RoleBinding.Subjects: []v1beta1.Subject: v1beta1.Subject.Name: ReadString: expects " or n, but found f, error found in #10 byte of ...|","name":false,"name|..., bigger context ...|er"},"subjects":[{"kind":"ServiceAccount","name":false,"namespace":"demo"}]}
> |...

**This one fails too:**

```
$ kubectl create ns n
$ kubectl create sa demo -nn
```
-> same Role

rb.yaml

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cm-getter-binding
subjects:
- kind: ServiceAccount
  name: demo
  namespace: n
roleRef:
  kind: Role
  name: cm-getter
  apiGroup: ""
```

$ kubectl create -f rb.yaml -nn
> Error from server (BadRequest): error when creating "rb.yaml": RoleBinding in version "v1beta1" cannot be handled as a RoleBinding: v1beta1.RoleBinding.Subjects: []v1beta1.Subject: v1beta1.Subject.Namespace: ReadString: expects " or n, but found f, error found in #10 byte of ...|mespace":false}]}
> |..., bigger context ...|kind":"ServiceAccount","name":"demo","namespace":false}]}
> |...

And if you make them both (service account and namespace) to be demo (for example), it works fine.

```
root@master:~/rbac# kubectl version --short
Client Version: v1.16.1
Server Version: v1.15.1
```
