### ISSUE TITLE
LivenessProbe keep checking on port 80 instead of 8081

### ISSUE THREAD

**Issue by iamcryptoki** [kubernetes/kubernetes#86121]
### **WHAT HAPPENED**:

**1. Defined a _Deployment_ with a container exposing the port 8081 :** It works. Pod gets ready and Wordpress is available.
2. **Added liveness/readiness probes to Deployment:** Pod never gets ready. Probes seem to check port 80 instead of 8081.
3. **Pod events:**
```
Containers:
...
    Port:           8081/TCP
...
    Liveness:   http-get http://:8081/index.php delay=15s timeout=10s period=30s #success=1 #failure=5
    Readiness:  http-get http://:8081/index.php delay=15s timeout=10s period=30s #success=1 #failure=5

...

Events:
  Type     Reason     Age        From                        Message
  ----     ------     ----       ----                        -------
  Warning  Unhealthy  <invalid>  kubelet, k8s02-worker01  Readiness probe failed: Get http://10.244.2.69/: dial tcp 10.244.2.69:80: connect: connection refused
  Warning  Unhealthy  <invalid>  kubelet, k8s02-worker01  Liveness probe failed: Get http://10.244.2.69/: dial tcp 10.244.2.69:80: connect: connection refused
```

**WHAT YOU EXPECTED TO HAPPEN:**

Probes to check port 8081 and Pod ready.

**HOW TO REPRODUCE IT:**

**Dockerfile**
```
FROM wordpress:5.2.4-apache

RUN sed -i 's/Listen 80/Listen 8081/g' /etc/apache2/ports.conf;
RUN sed -i 's/:80/:8081/g' /etc/apache2/sites-enabled/000-default.conf;

EXPOSE 8081

CMD ["apache2-foreground"]
```

**Liveness/Readness probes (Deployment):**
```
[...]
ports:
  - name: liveness-port
    containerPort: 8081
readinessProbe:
  initialDelaySeconds: 15
  httpGet:
    path: /index.php
    port: 8081
  timeoutSeconds: 10
  periodSeconds: 15
  failureThreshold: 5
livenessProbe:
  initialDelaySeconds: 15
  httpGet:
    path: /index.php
    port: 8081
  timeoutSeconds: 10
  periodSeconds: 15
  failureThreshold: 5
[...]
```

**ENVIRONMENT**:
- Kubernetes version (use `kubectl version`): `v1.16.3`

- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`): `Linux k8s02-master01 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by qq690388648** [comment]
who am i

**Comment by iamcryptoki** [comment]
I figured out what the issue was... Wordpress issue, not Kubernetes.

**Comment by iamcryptoki** [comment]
For anyone interested I've managed to solve this issue.

I was getting a 301 redirect response from Wordpress due to Wordpress forcing my domain name example.com. Solved this issue by disabling Wordpress canonical redirection feature for the specific request **http://POD_IP:8080/index.php**.

**Here's how:**

Added the Pod IP address as an environment variable:

```
- name: K8S_POD_IP
   valueFrom:
     fieldRef:
       fieldPath: status.podIP
```

Created a Wordpress plugin with a custom **redirect_canonical** filter that prevents Wordpress from redirecting **http://POD_IP:8080/index.php**:

```
<?php
/**
    * Plugin Name: Kubernetes Liveness Probe Exception
    */

add_filter('redirect_canonical', function($redirect_url, $requested_url) {
    $K8S_POD_IP = getenv('K8S_POD_IP');
    $LIVENESS_URL = "http://" . $K8S_POD_IP . ":8080/index.php";
    
    if ($requested_url == $LIVENESS_URL) {
        return $requested_url;
    }
    
    return $redirect_url;
}, 10, 2);
```
