### ISSUE TITLE
Ingress: RegExp and capture group in host entry, usable to target headless services

### ISSUE THREAD

**Issue by suvl** [kubernetes/kubernetes#86132]
Coming from #41881, I have a further complicated need for using ingress rules.

I have some `StatefulSet` that is accessible through a headless service. Then I want to target each specific instance of that service (clients would know what service from a redirect request). That service would have N instances at any given time.

It's something like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myservice
  namespace: somens
spec:
  rules:
  - host: ~^baseaddr-(?<srv_host>\d+)\.example\.com$
    http:
      paths:
      - backend:
          serviceName: myservice-$srv_host.myservice.somens
          servicePort: 80
```

I ended up just changing the `nginx-template` and added hard-coded `server` entries for all my cases, but it feels quite hacky.
