### ISSUE TITLE
Service config validation error: "spec:ports" ...

### ISSUE THREAD

**Issue by alexei-led** [kubernetes/kubernetes#8619]
Running `kubectl -f some-service.yaml` (or JSON) file, fails with following error:
> Service "some-service" is invalid: spec.ports: required value

I have two config files. One for **pod** and other for **service**. I'm able to deploy **pod** without any problem.

**pod:** `rabbitmq-pod.yaml`
``` yaml
apiVersion: v1beta3
kind: Pod
metadata:
  labels:
    mq: rabbit
    role: master
  name: rabbitmq-pod
spec:
  containers:
    - name: rabbitmq
      image: tutum/rabbitmq
      ports:
        - containerPort: 5672
          name: main-port
          protocol: tcp
        - containerPort: 15672
          name: admin-port
          protocol: tcp
```
**service:** `rabbitmq-service.yaml`
``` yaml
apiVersion: v1beta3
kind: Service
metadata:
  name: rabbitmq-service
spec:
  ports:
    - port: 5672
      name: main-port
      targetPort: 5672
      protocol: tcp
    - port: 15672
      name: admin-port
      targetPort: 15672
      protocol: tcp
  selector:
    name: rabbitmq-pod
```

The error is reproducible with `kubectl` 0.17.0 and Mac OS X.
