### ISSUE TITLE
CSI: Resizing a PVC shows a misleading error message /sig storage

### ISSUE THREAD

**Issue by rodrigc** [kubernetes/kubernetes#86200]
**How to reproduce it (as minimally and precisely as possible)**:

1.  Create a PVC with this storage class:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-csi-test-repl-2
parameters:
  group: test
  io_priority: high
  io_profile: sequential
  repl: "2"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

2.  Resize the PVC

3.  I saw that the PVC resized properly, but I saw a warning message which I describe below.

**What happened**:

I did a `kubectl describe` on the PVC, and saw:

```
Events:
  Type     Reason                  Age    From                               Message
  ----     ------                  ----   ----                               -------
  Warning  ExternalExpanding       3m26s  volume_expand                      Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing                3m26s  external-resizer pxd.portworx.com  External resizer is resizing volume pvc-5ff93e98-0d69-4dcc-9af6-1a99b4aff86a
  Normal   VolumeResizeSuccessful  3m23s  external-resizer pxd.portworx.com  Resize volume succeeded
```

**What you expected to happen**:

The warning message `Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.`  seems confusing and unnecessary.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.15.5
- Cloud provider or hardware configuration:     bare metal
- OS (e.g: `cat /etc/os-release`):  Centos 7
- Kernel (e.g. `uname -a`): Linux craig-dev-1 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others: Portworx version 2.2.0, installed with CSI driver
