### ISSUE TITLE
Undocumented fsType parameter for gce storage provisioner

### ISSUE THREAD

**Issue by zuozp8** [kubernetes/kubernetes#86246]
**What happened**:
Documentation doesn't mention `fsType` parameter for `gce-pd` storage provisioner
https://kubernetes.io/docs/concepts/storage/storage-classes/#gce-pd

Accepted values are `ext4` and `xfs`, it's also worth noting that you need for `xfs` you need support on host OS

**How to reproduce it**:
On gke (with node image type `ubuntu` rather then `cos`) apply:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd-xfs
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  fsType: xfs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "ssd-xfs"
        resources:
          requests:
            storage: 1Gi
```
and run `kubectl exec web-0 -- df -Th` to see that attached volume is `xfs`.
