### ISSUE TITLE
Kubernetes v1.16.0 CPU manager fuctionality fails when Pod has initContainer 

### ISSUE THREAD

**Issue by joshshn** [kubernetes/kubernetes#86255]
**What happened**:
CPU manager functionality is enabled by adding the below environment variable to the kubelet startup argument. Functionality is verified by creating a sample pod with Guaranteed Qos.

Environment="KUBELET_CPUMANAGER_ARGS=--cpu-manager-policy=static  --kube-reserved=cpu=1000m,memory=1024Mi"

```apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: ubuntu
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    resources:
      limits:
        memory: "200Mi"
        cpu: "2"
      requests:
        memory: "200Mi"
        cpu: "2"
  nodeSelector:
  kubernetes.io/hostname: worker2
```

Functionality is verified by checking the cpu_manager_state file that cores are assigned to pod.

```admin1@worker2:~$ sudo cat /var/lib/kubelet/cpu_manager_state
{"policyName":"static","defaultCpuSet":"0-2,4-26,28-47","entries":{"ab9940917010576bd755870dab91e2cd2fc531a04ac362d44a62950aaa41c527":"3,27"},"checksum":1300288133}
```

Same pod is brought up with initContainer defined in the manifest:

```
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  initContainers:
  - name: init-sysctl
    image: ubuntu
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "echo hello"]
  containers:
  - name: myapp-container
    image: ubuntu
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    resources:
      limits:
        memory: "200Mi"
        cpu: "2"
      requests:
        memory: "200Mi"
        cpu: "2"
  nodeSelector:
   kubernetes.io/hostname: worker2
```

**What you expected to happen**:

Cores are assigned to pod and verified in the cpu_manager_state file. Instead no cores are assigned to the pod and uses shared pool.

```admin1@worker2:~$ sudo cat /var/lib/kubelet/cpu_manager_state
{"policyName":"static","defaultCpuSet":"0-47","checksum":990655235}
```

Kubelet logs have the below information:
```
Dec 13 17:41:11 worker2 kubelet[11909]: W1213 17:41:11.609902   11909 cpu_manager.go:244] [cpumanager] reconcileState: skipping container; ID not found in status (pod: myapp-pod, container: init-sysctl, error: unable to find ID for container with name init-sysctl in pod status (it may not be running))
Dec 13 17:41:11 worker2 kubelet[11909]: W1213 17:41:11.609944   11909 cpu_manager.go:244] [cpumanager] reconcileState: skipping container; ID not found in status (pod: myapp-pod, container: myapp-container, error: unable to find ID for container with name myapp-container in pod status (it may not be running))
```

**How to reproduce it (as minimally and precisely as possible)**:

Enable cpu manager functionality and bring up a sample pod (manifest above) with initContainer information and verify  the file /var/lib/kubelet/cpu_manager_state.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.0
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3 LTS 
- Kernel (e.g. `uname -a`): Linux Master 5.0.0-050000-generic #201903032031
- Other: Baremetal Hardware setup

**Comment by tedyu** [comment]
Related:
```
commit ef27f5f1a5587c75316c440490c6df39417d1c4a
Author: Kevin Klues <kklues@nvidia.com>
Date:   Sat Apr 27 05:57:03 2019 -0700

    Add ability to find init Container IDs in cpumanager reconcileState()
```
It seems the ContainerID was empty at the time of the check:
```
		if container.Name == name && container.ContainerID != "" {
```

**Comment by ipuustin** [comment]
I tried your yaml file, and your pod is in QoS class Burstable. It means that cpu manager won't give it exclusive CPUs. In order to make your pod Guaranteed, you need to assign matching limit-request pairs to all containers in the pod, for example like this:

```
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  initContainers:
  - name: init-sysctl
    image: ubuntu
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "echo hello"]
    resources:
      limits:
        memory: "100Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "1"
  containers:
  - name: myapp-container
    image: ubuntu
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    resources:
      limits:
        memory: "200Mi"
        cpu: "2"
      requests:
        memory: "200Mi"
        cpu: "2"
```

The cpu manager will then give your container dedicated cores.
