### ISSUE TITLE
Accessing non-sensitive data of Secrets

### ISSUE THREAD

**Issue by rubenhak** [kubernetes/kubernetes#86268]
/sig api-machinery

Secrets hold sensitive data. There is a need to allow certain programs to access Configuration part of secrets, yet restricting access to the sensitive data. Such capability would allow tools to validate correctness of configuration without worrying that the sensitive data can be leaked.

The plan is to query sanitized version of Secrets:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-name
  namespace: my-namespace
data:
  my-key-1: ***
  my-key-2: ***
  my-key-3: ***
```

One solution could be an introduction of additional API and RBAC verbs "get-sanitized" and "watch-sanitized".
