### ISSUE TITLE
Connection refused during rolling upgrade of deployment

### ISSUE THREAD

**Issue by vmalloc** [kubernetes/kubernetes#86280]
**What happened**:

I am running two pods, one is exposed via a service, and the other communicates with it to make
requests.

The main service lookes more or less like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ...
  labels: ...
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    ...
  template:
    metadata:
      labels:
        app: my-backend
        ...
      annotations:
        ...
    spec:
      containers:
        - ...
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/v3/status
              port: 8000
          readinessProbe:
            httpGet:
              path: /api/v3/status
              port: 8000
            timeoutSeconds: 300
```

The service is defined like this:

```yaml
apiVersion: v1
kind: Service
metadata:
    name: my-backend
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: my-backend
```

The other pod just periodically sends HTTP traffic to `http://my-backend:8000`.

I use helm to upgrade the deployment, running:

```
helm upgrade --wait --namespace production my-backend ./helm-charts/my-backend --debug --set ingress.enabled=true --set-string deploy_timestamp=20191215-105358+0000
```

(I use the set-string trick to force pods to get recreated through the rolling update strategy).

**When I run this, the internal pod trying to communicate with `http://my-backend:8000` gets a
"connection refused" error momentarily.**

**What you expected to happen**:
I expected the rolling update to make sure that requests inside the cluster get drained properly and
redirected to the newly created pods, thus not creating a momentary situation in which the internal
service does not accept connections

**How to reproduce it (as minimally and precisely as possible)**:

See above scenario. I'm running on EKS (I'm not sure if this is crucial to reproduce it but this is
where it reproduces for me)

**Anything else we need to know?**:
Not sure -- I'd be very happy to provide more specific details if needed

**Environment**:
- Kubernetes version (use `kubectl version`):

```Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b8860f", GitCommit:"b8860f6c40640897e52c143f1b9f011a503d6e46", GitTreeState:"clean", BuildDate:"2019-11-25T00:55:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}```

- Cloud provider or hardware configuration: AWS (through EKS), running on 4 t3.medium nodes
