### ISSUE TITLE
My K8s-Cluster cannot access Service-IP(clusterIP) 

### ISSUE THREAD

**Issue by robinwangrubin** [kubernetes/kubernetes#86471]
Hello,
It's my first time trying K8s cluster. The embarrassing thing is when i did the first task, i failed.

Here is the thing.

I followd official documents to create a web deployment.
I can access my pod in my cluster node.
And then i created a service to link my pod. So i got the service IP.
The official documents told me that i could access my service ip in my cluser node.
But it seems like there is something wrong.

![image](https://user-images.githubusercontent.com/24934186/71235694-de6bc680-2337-11ea-902c-da9f2a242978.png)

Here is my yaml file
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  labels:
    app: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: containous/whoami:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-whoami
spec:
  selector:
    app: whoami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```
