### ISSUE TITLE
Pod Probes doesn't work if host = 0.0.0.0

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#86504]
**What happened**:

When configuring the host field of a probe with the 0.0.0.0 address it fails

**What you expected to happen**:

There is controversy on what should expect to happen, you can follow the discussion here:

https://github.com/kubernetes/kubernetes/pull/86493#discussion_r360595011

personally ,and after checking the code, I think that a good option will be replacing the host field by the pod IP, as it seems it's being doing for an empty host field

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster:

`kind create cluster`

Create a pod with a probe using 0.0.0.0 as host:
`kubectl apply`

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        host: 0.0.0.0
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
```

Check the pod status

```
Events:
  Type     Reason     Age                 From                         Message
  ----     ------     ----                ----                         -------
  Normal   Scheduled  109s                default-scheduler            Successfully assigned default/liveness-http to kind-control-plane
  Normal   Pulled     73s (x3 over 100s)  kubelet, kind-control-plane  Successfully pulled image "k8s.gcr.io/liveness"
  Normal   Created    72s (x3 over 99s)   kubelet, kind-control-plane  Created container liveness
  Normal   Started    72s (x3 over 99s)   kubelet, kind-control-plane  Started container liveness
  Normal   Pulling    63s (x4 over 108s)  kubelet, kind-control-plane  Pulling image "k8s.gcr.io/liveness"
  Warning  Unhealthy  63s (x9 over 96s)   kubelet, kind-control-plane  Liveness probe failed: Get http://0.0.0.0:8080/healthz: dial tcp 0.0.0.0:8080: connect: connection refused
  Normal   Killing    63s (x3 over 90s)   kubelet, kind-control-plane  Container liveness failed liveness probe, will be restarted
```

and seems that the probe fails when using 0.0.0.0 as host

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
