### ISSUE TITLE
sessionAffinityConfig did not take affect

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#86522]
```
[root@master01 service]# vi nginx-clusterIp-svc-sessionAffinityConfig.yaml 
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-svc-sessionaffinityconfig
spec:
 selector:
   app: nginx
 type: ClusterIP
 sessionAffinity: ClientIP
 sessionAffinityConfig:
   clientIP:
     timeoutSeconds: 2
 ports:
 -  name: http
    port: 8000
    targetPort: 80
```
```
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
nginx-03
[root@master01 service]# curl 10.68.205.91:8000
```
