### ISSUE TITLE
apiserver Feature Gates enable VolumeSubpathEnvExpansion but no effect

### ISSUE THREAD

**Issue by yinwenqin** [kubernetes/kubernetes#86579]
**What happened**:

I would like to use subPath with expanded environment variables in order to prevent pods(with replicas) writing on same file. 

So I turn on the VolumeSubpathEnvExpansion option by modify `/etc/kubernetes/manifests/kube-apiserver.yaml`, like this:

```
spec:
  containers:
  - command:
    - kube-apiserver
    ...
    - --feature-gates=VolumeSubpathEnvExpansion=true
```

Then every apiserver instance auto reboot, the new process contains this new option:
```
# ps -ef | grep apiserver
root      330353  330235  2 15:44 ?        00:00:50 kube-apiserver --advertise-address=192.168.8.15 --allow-privileged=true --authorization-mode=Node,RBAC --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/etcd/ssl/ca.pem --etcd-certfile=/etc/etcd/ssl/etcd.pem --etcd-keyfile=/etc/etcd/ssl/etcd-key.pem --etcd-servers=https://192.168.8.19:2379,https://192.168.8.20:2379,https://192.168.8.21:2379 --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-cluster-ip-range=10.112.0.0/12 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key --feature-gates=VolumeSubpathEnvExpansion=true
```

I create a new sts for test:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: redis-test
    scene: product
  name: redis-test
  namespace: default
spec:
  updateStrategy:
    type:
      RollingUpdate 
  serviceName: "redis-test"
  replicas: 4
  selector:
    matchLabels:
      app: redis-test
  template:
    metadata:
      labels:
        app: redis-test
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - /run.sh
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: redis:v4.0.14
        imagePullPolicy: Always
        name: redis-test
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: '2'
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
          subPathExpr: $(POD_NAME)/data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: redis-test
```

but pod report **CreateContainerConfigError: volume subpath expansion is disabled**:

```

# kubectl get pods -o wide --all-namespaces | grep redis-test
default       redis-test-0                                            0/1     CreateContainerConfigError   0          49s     172.36.5.54      yksp020144   <none>           <none>

# kubectl describe pod redis-test-0
...

Events:
  Type     Reason     Age               From                 Message
  ----     ------     ----              ----                 -------
  Normal   Scheduled  58s               default-scheduler    Successfully assigned default/redis-test-0 to yksp020144
  Normal   Pulling    2s (x6 over 58s)  kubelet, yksp020144  Pulling image "registry.youkeshu.com:5000/redis:v4.0.14tmp"
  Normal   Pulled     2s (x6 over 58s)  kubelet, yksp020144  Successfully pulled image "registry.youkeshu.com:5000/redis:v4.0.14tmp"
  Warning  Failed     2s (x6 over 58s)  kubelet, yksp020144  Error: volume subpath expansion is disabled
```
All apiserver process contains **--feature-gates=VolumeSubpathEnvExpansion=true** option, but it still do not work, how can I do for it ?

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
