### ISSUE TITLE
ReadWriteOnce makes no effect: multiple nodes can write to the volume

### ISSUE THREAD

**Issue by renpengzhang** [kubernetes/kubernetes#86694]
**What happened**:
I created a PV and PVC using AccessMode as "ReadWriteOnce", and then I create a deployment containing 3 replicas all using the same above PVC. BTW, I have checked that those 3 replicas did spread in different nodes. The problem is I found that all 3 replicas can write to the same mounted volume.

**What you expected to happen**:
As the AccessMode is "ReadWriteOnce" for PV and PVC, only 1 node should be allowed to write to the volume.

**How to reproduce it (as minimally and precisely as possible)**:
PV template:

> apiVersion: v1
> kind: PersistentVolume
> metadata:
>   name: azurefile
> spec:
>   capacity:
>     storage: 5Gi
>   accessModes:
>     - ReadWriteOnce
>   storageClassName: azurefile
>   azureFile:
>     secretName: ***
>     shareName:***
>     readOnly: false
>   mountOptions:
>   - dir_mode=0777
>   - file_mode=0777
>   - uid=1000
>   - gid=1000
>   - mfsymlinks
>   - nobrl

PVC template:

> apiVersion: v1
> kind: PersistentVolumeClaim
> metadata:
>   name: azurefile
> spec:
>   accessModes:
>     - ReadWriteOnce
>   storageClassName: azurefile
>   resources:
>     requests:
>       storage: 5Gi

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Choi-Sung-Hoon** [comment]
It seems that your problem happens because of statefulSet.

I guess that you distributed replicas to 3 nodes via statefulSet and that's why the nodes can access to the PV.

If you provide the template for your deployment it should be moer helpful.

**Comment by renpengzhang** [comment]
Actually, I created Deployment to use the PV.
The Deployment template is as following:

> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: ***
>   labels:
>     app: ***
> spec:
>   replicas: 3
>   selector:
>     matchLabels:
>       app: ***
>   template:
>     metadata:
>       labels:
>         app: ***
>     spec:
>       containers:
>       - name: ***
>         image: ***
>         ports:
>         - containerPort: 8000
>         resources:
>           requests:
>             cpu: 100m
>         volumeMounts:
>           - name: media
>             mountPath: /media
>       volumes:
>       - name: media
>         persistentVolumeClaim:
>           claimName: media

**Comment by Choi-Sung-Hoon** [comment]
Could you provide a better template with indentations please?
It's ambiguous and hard for me to understand what you intended.

**Comment by renpengzhang** [comment]
PV Template:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  azureFile:
    secretName: azure-file-secret
    shareName: fileshare
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
```
PVC Template:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
  volumeName: "media"
```


Deployment Template
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ***
  labels:
    app:***
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ***
  template:
    metadata:
      labels:
        app: ***
    spec:
      containers:
      - name: ***
        image: ***
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
        volumeMounts:
          - name: media
            mountPath: /media
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
```
