### ISSUE TITLE
Kubectl scale cluster-wide custom resource

### ISSUE THREAD

**Issue by Kafei59** [kubernetes/kubernetes#86746]
**What happened**:

I try to scale a cluster-wide custom resource using kubectl but everytime I try so, I got an error telling me:

> an empty namespace may not be set when a resource name is provided

**What you expected to happen**:

I expected the custom resource to be scaled to the correct amount of replicas.

**How to reproduce it (as minimally and precisely as possible)**:

Here is all the information to reproduce.

_Custom Resource Definition_:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: myfancykind.mygroup.com
spec:
  group: mygroup.com
  names:
    kind: MyFancyKind
    listKind: MyFancyKindList
    plural: myfancykinds
    singular: myfancykind
  versions:
  - name : v1
    served: true
    storage: true
  scope: Cluster
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            replicas:
              type: integer
        status:
          type: object
          properties:
            replicas:
              type: integer
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
  additionalPrinterColumns:
    - name: Replicas
      type: integer
      description: The number of replicas
      JSONPath: .spec.replicas
```

_Custom Resource_:

```yaml
apiVersion: mygroup.com/v1
kind: MyFancyKind
metadata:
  name: test-scale
spec:
  replicas: 3
```

_Scale command_:

```bash
➜ kubectl scale --replicas=4 myfancykinds/test-scale
error: an empty namespace may not be set when a resource name is provided
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
➜ kubectl version                                   
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: OVH cloud provider
- OS (e.g: `cat /etc/os-release`): macOS Mojave Version 10.14.6
- Kernel (e.g. `uname -a`):
```bash
Darwin LAPTOP984242.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```
