### ISSUE TITLE
label type error when kubectl apply

### ISSUE THREAD

**Issue by tontinme** [kubernetes/kubernetes#86772]
**What happened**:

I have test.yaml like this

```
# cat test.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: "1e003"
  name: test001
spec:
  containers:
  - args:
    image: registry.umstor.io:5050/vendor/busybox:1.26.2
    imagePullPolicy: IfNotPresent
    name: test001

# cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - test.yaml
```
after `kustomize build . > test02.yaml`, double quote of 1e003 removed by kustomize

```
# cat test02.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: 1e003
  name: test001
spec:
  containers:
  - args:
    image: registry.umstor.io:5050/vendor/busybox:1.26.2
    imagePullPolicy: IfNotPresent
    name: test001
```
then, kubectl apply -f test02.yaml cause error:

```
# kubectl apply -f test02.yaml
Error from server (BadRequest): error when creating "test.yaml": Pod in version "v1" cannot be handled as a Pod: v1.Pod.ObjectMeta: v1.ObjectMeta.Labels: ReadString: expects " or n, but
 found 1, error found in #10 byte of ...|:{"test":1000},"name|..., bigger context ...|\",\"name\":\"test001\"}]}}\n"},"labels":{"test":1000},"name":"test001","namespace":"default"},"spe
c|...
```

as you can see, 1e003 has been converted to 1000, which type is numeric, lead to type error.

**What you expected to happen**:

1. double quote reversed by kustomize
or 
2. why 1e003 be converted to 1000,  Is this the expected behavior？ e001 =>0, e002 =>00, e003 => 000 

**How to reproduce it (as minimally and precisely as possible)**:

as i mentioned above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
kubernetes
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
kustomize
Version: {KustomizeVersion:v3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:Wed Aug  7 09:36:08 UTC 2019 GoOs:linux GoArch:amd64}
- Cloud provider or hardware configuration: baremetal
- OS (e.g: `cat /etc/os-release`): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`): 
Linux u3 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
