### ISSUE TITLE
metav1.Time fails CRD validation

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#86811]
**What happened**:

One of my CRD has a metav1.Time field (this is an embedded partial ObjectMeta)

```
// +optional
CreationTimestamp metav1.Time `json:"creationTimestamp,omitempty"`
```

I am using Kubebuilder to generate CRD yaml. So, it generated the following schema:
https://github.com/kubernetes-sigs/controller-tools/blob/a5fa7b956b85a6e792bc7086fedf7107d62452b1/pkg/crd/known_types.go#L34-L37

Now, if the user does not provide the timestamp (which is common in my case), metav1.Time generates `null` in json format.

https://github.com/kubernetes/apimachinery/blob/4d9f99a835264546b4624ab7cbefc29588b1ed3a/pkg/apis/meta/v1/time.go#L144-L147

This is causing CRD validation failure with a following error message:

```
spec.backend.file.volumeClaimTemplate.metadata.creationTimestamp in body must be of type string: "null"
```

YAML used:

```
apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  replicas: 1
  version: "1.2.3"
  serviceTemplate:
    spec:
      type: NodePort
  backend:
    file:
      path: "/test/data"
      volumeClaimTemplate:
        metadata:
          name: vault-pvc
        spec:
          accessModes: 
          - "ReadWriteOnce"
          storageClassName: standard
          resources:
            requests:
              storage: 1Gi
  unsealer:
    secretShares: 4
    secretThreshold: 2
    mode:
      kubernetesSecret:
        secretName: vault-keys
```

How do we fix this?
