### ISSUE TITLE
Old master-leases not removed from ETCD after restore from backup

### ISSUE THREAD

**Issue by chaudyg** [kubernetes/kubernetes#86812]
**What happened**:

After restoring ETCD from backup, old master endpoints are returned, even if the master nodes are long gone.

The screenshot bellow summarises the issues: 3 master nodes running on the cluster, but 5 endpoints are being returned. The additional 2 comes from master nodes from before restoring the cluster.
![image](https://user-images.githubusercontent.com/7817963/71728461-0d546300-2e35-11ea-9428-16b51e853bdd.png)

Deleting the kubernetes endpoint or the kubernetes service using `kubectl` does not solve the issue (kubernetes recreates the service with the wrong list of endpoints) . The only way we found to clean-up the additional incorrect endpoints was to delete the masterlease object directly from etcd using the following command.
```
export ETCDCTL_API=3
etcdctl --insecure-skip-tls-verify --cert=$CACERT --key=$CAKEY --endpoints $ENDPOINTS del "/registry/masterleases/172.17.123.456"
```

If that helps, here is an example of a correct/incorrect masterlease object in ETCD:
```
# incorrect
etcdctl get /registry/masterleases/172.18.224.115 --hex
\x2f\x72\x65\x67\x69\x73\x74\x72\x79\x2f\x6d\x61\x73\x74\x65\x72\x6c\x65\x61\x73\x65\x73\x2f\x31\x37\x32\x2e\x31\x38\x2e\x32\x32\x34\x2e\x31\x31\x35
\x6b\x38\x73\x00\x0a\x0f\x0a\x02\x76\x31\x12\x09\x45\x6e\x64\x70\x6f\x69\x6e\x74\x73\x12\x2b\x0a\x13\x0a\x00\x12\x00\x1a\x00\x22\x00\x2a\x00\x32\x00\x38\x8b\x58\x42\x00\x7a\x00\x12\x14\x0a\x12\x0a\x0e\x31\x37\x32\x2e\x31\x38\x2e\x32\x32\x34\x2e\x31\x31\x35\x1a\x00\x1a\x00\x22\x00
# correct
etcdctl get /registry/masterleases/172.18.224.54 --hex
\x2f\x72\x65\x67\x69\x73\x74\x72\x79\x2f\x6d\x61\x73\x74\x65\x72\x6c\x65\x61\x73\x65\x73\x2f\x31\x37\x32\x2e\x31\x38\x2e\x32\x32\x34\x2e\x35\x34
\x6b\x38\x73\x00\x0a\x0f\x0a\x02\x76\x31\x12\x09\x45\x6e\x64\x70\x6f\x69\x6e\x74\x73\x12\x2a\x0a\x13\x0a\x00\x12\x00\x1a\x00\x22\x00\x2a\x00\x32\x00\x38\xce\x35\x42\x00\x7a\x00\x12\x13\x0a\x11\x0a\x0d\x31\x37\x32\x2e\x31\x38\x2e\x32\x32\x34\x2e\x35\x34\x1a\x00\x1a\x00\x22\x00
```

**What you expected to happen**:

Old masterleases should expired, and the number of kubernetes endpoints should eventually match the number of kubernetes nodes.

**How to reproduce it (as minimally and precisely as possible)**:
Managed to reproduce this multiple times.
* Backup etcd
* Delete the master nodes
* Recover ETCD from backup
* run `kubectl get nodes`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.9
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): AWS linux AMI 2
- Kernel (e.g. `uname -a`):
- Install tools: KOPS
- Network plugin and version (if this is a network-related bug): lyftcni
- Others: Used the kops etcdmanager for backup and recovery of etcd.

**Comment by liggitt** [comment]
@jpbetz does an etcd restore restore ttls on keys?

**Comment by jpbetz** [comment]
> Joe Betz does an etcd restore restore ttls on keys?

Yes, a restore does restore the ttls that existed at the time the backup was saved.

The ttls will be no shorter in duration then they were when the backup was saved. E.g. if there was a ttl of 5 minutes at the time the backup was saved, it will be no less than 5 minutes when restored.

**Comment by liggitt** [comment]
@jpbetz and that's true for leases (etcd v3) as well?

@chaudyg when you have an etcd cluster in this state, what does the following output:

```
export ETCDCTL_API=3
etcdctl get --prefix -w json /registry/masterleases | jq .
etcdctl lease list | tail -n +2 | xargs -n 1 etcdctl lease -w json timetolive | jq .
etcdctl get --prefix -w json /registry/masterleases | jq .
etcdctl lease list | tail -n +2 | xargs -n 1 etcdctl lease -w json timetolive | jq .
```

**Comment by jpbetz** [comment]
> @jpbetz and that's true for leases (etcd v3) as well?

Yes, actually, I only tested v3 leases. I don't know what v2 ttls do. But v3 leases are definitely restored.

**Comment by jpbetz** [comment]
I don't know if this helps, but here are the master lease objects decoded to yaml:

incorrect:

```
printf "%b" "\x2f\x72\x65\x67\x69\x73\x74\x72\x79\x2f\x6d\x61\x73\x74\x65\x72\x6c\x65\x61\x73\x65\x73\x2f\x31\x37\x32\x2e\x31\x38\x2e\x32\x32\x34\x2e\x31\x31\x35\x6b\x38\x73\x00\x0a\x0f\x0a\x02\x76\x31\x12\x09\x45\x6e\x64\x70\x6f\x69\x6e\x74\x73\x12\x2b\x0a\x13\x0a\x00\x12\x00\x1a\x00\x22\x00\x2a\x00\x32\x00\x38\x8b\x58\x42\x00\x7a\x00\x12\x14\x0a\x12\x0a\x0e\x31\x37\x32\x2e\x31\x38\x2e\x32\x32\x34\x2e\x31\x31\x35\x1a\x00\x1a\x00\x22\x00" | auger decode
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  generation: 11275
subsets:
- addresses:
  - ip: 172.18.224.115
```
correct:

```
printf "%b" "\x2f\x72\x65\x67\x69\x73\x74\x72\x79\x2f\x6d\x61\x73\x74\x65\x72\x6c\x65\x61\x73\x65\x73\x2f\x31\x37\x32\x2e\x31\x38\x2e\x32\x32\x34\x2e\x35\x34\x6b\x38\x73\x00\x0a\x0f\x0a\x02\x76\x31\x12\x09\x45\x6e\x64\x70\x6f\x69\x6e\x74\x73\x12\x2a\x0a\x13\x0a\x00\x12\x00\x1a\x00\x22\x00\x2a\x00\x32\x00\x38\xce\x35\x42\x00\x7a\x00\x12\x13\x0a\x11\x0a\x0d\x31\x37\x32\x2e\x31\x38\x2e\x32\x32\x34\x2e\x35\x34\x1a\x00\x1a\x00\x22\x00" | auger decode
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  generation: 6862
subsets:
- addresses:
  - ip: 172.18.224.54
```
