### ISSUE TITLE
 kubernetes 1.17.0 - kubeadm init - kube-controller-manager status is ContainerCreating

### ISSUE THREAD

**Issue by nsano-rururu** [kubernetes/kubernetes#86961]
**What happened**:

I installed kubernetes with kubeadm, but after executing kubeadm init, the state of kube-controller-manage stopped at ContainerCreating. Also, it seems that deployment has not started with coredns.

```
$ kubectl get all --all-namespaces

NAMESPACE     NAME                                                                           READY   STATUS              RESTARTS   AGE
kube-system   pod/etcd-ip-172-31-16-120.ap-northeast-1.compute.internal                      1/1     Running             0          20m
kube-system   pod/kube-apiserver-ip-172-31-16-120.ap-northeast-1.compute.internal            1/1     Running             0          20m
kube-system   pod/kube-controller-manager-ip-172-31-16-120.ap-northeast-1.compute.internal   0/1     ContainerCreating   0          20m
kube-system   pod/kube-scheduler-ip-172-31-16-120.ap-northeast-1.compute.internal            1/1     Running             0          20m

NAMESPACE     NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  20m
kube-system   service/kube-dns     ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   20m

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
kube-system   daemonset.apps/kube-proxy   0         0         0       0            0           beta.kubernetes.io/os=linux   20m

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   0/2     0            0           20m

$ kubectl describe pod -n kube-system kube-controller-manager-ip-172-31-16-120.ap-northeast-1.compute.internal

Name:                 kube-controller-manager-ip-172-31-16-120.ap-northeast-1.compute.internal
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 ip-172-31-16-120.ap-northeast-1.compute.internal/172.31.16.120
Start Time:           Wed, 08 Jan 2020 17:06:51 +0000
Labels:               component=kube-controller-manager
                      tier=control-plane
Annotations:          kubernetes.io/config.hash: c6a10a2d79537e163e8f69ebf45f818b
                      kubernetes.io/config.mirror: c6a10a2d79537e163e8f69ebf45f818b
                      kubernetes.io/config.seen: 2020-01-08T17:06:50.688112954Z
                      kubernetes.io/config.source: file
Status:               Pending
IP:                   172.31.16.120
IPs:
  IP:           172.31.16.120
Controlled By:  Node/ip-172-31-16-120.ap-northeast-1.compute.internal
Containers:
  kube-controller-manager:
    Container ID:  
    Image:         k8s.gcr.io/kube-controller-manager:v1.17.0
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      kube-controller-manager
      --allocate-node-cidrs=true
      --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
      --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
      --bind-address=127.0.0.1
      --client-ca-file=/etc/kubernetes/pki/ca.crt
      --cluster-cidr=10.244.0.0/16
      --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
      --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
      --controllers=*,bootstrapsigner,tokencleaner
      --kubeconfig=/etc/kubernetes/controller-manager.conf
      --leader-elect=true
      --node-cidr-mask-size=24
      --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
      --root-ca-file=/etc/kubernetes/pki/ca.crt
      --service-account-private-key-file=/etc/kubernetes/pki/sa.key
      --service-cluster-ip-range=10.96.0.0/12
      --use-service-account-credentials=true
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        200m
    Liveness:     http-get https://127.0.0.1:10257/healthz delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:  <none>
    Mounts:
      /etc/kubernetes/controller-manager.conf from kubeconfig (ro)
      /etc/kubernetes/pki from k8s-certs (ro)
      /etc/ssl/certs from ca-certs (ro)
      /usr/libexec/kubernetes/kubelet-plugins/volume/exec from flexvolume-dir (rw)
      /usr/share/ca-certificates from usr-share-ca-certificates (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  ca-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/ssl/certs
    HostPathType:  DirectoryOrCreate
  flexvolume-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/libexec/kubernetes/kubelet-plugins/volume/exec
    HostPathType:  DirectoryOrCreate
  k8s-certs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/pki
    HostPathType:  DirectoryOrCreate
  kubeconfig:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/controller-manager.conf
    HostPathType:  FileOrCreate
  usr-share-ca-certificates:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/share/ca-certificates
    HostPathType:  DirectoryOrCreate
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       :NoExecute
Events:
  Type     Reason       Age                  From                                                       Message
  ----     ------       ----                 ----                                                       -------
  Warning  FailedMount  12m (x2 over 18m)    kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[flexvolume-dir], unattached volumes=[k8s-certs kubeconfig usr-share-ca-certificates ca-certs flexvolume-dir]: timed out waiting for the condition
  Warning  FailedMount  8m34s (x2 over 10m)  kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[flexvolume-dir], unattached volumes=[ca-certs flexvolume-dir k8s-certs kubeconfig usr-share-ca-certificates]: timed out waiting for the condition
  Warning  FailedMount  6m31s (x3 over 16m)  kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[flexvolume-dir], unattached volumes=[kubeconfig usr-share-ca-certificates ca-certs flexvolume-dir k8s-certs]: timed out waiting for the condition
  Warning  FailedMount  4m27s                kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[flexvolume-dir], unattached volumes=[flexvolume-dir k8s-certs kubeconfig usr-share-ca-certificates ca-certs]: timed out waiting for the condition
  Warning  FailedMount  2m24s (x2 over 20m)  kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[flexvolume-dir], unattached volumes=[usr-share-ca-certificates ca-certs flexvolume-dir k8s-certs kubeconfig]: timed out waiting for the condition
  Warning  FailedMount  29s (x19 over 22m)   kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  MountVolume.SetUp failed for volume "flexvolume-dir" : mkdir /usr/libexec/kubernetes: read-only file system
```
**What you expected to happen**:

The state of kube-controller-manager is Running
coredns status is Pending

**How to reproduce it (as minimally and precisely as possible)**:

installed kubernetes with kubeadm

**Anything else we need to know?**:

No

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

AWS EC2 
t3.small

- OS (e.g: `cat /etc/os-release`):

NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2303.3.0
VERSION_ID=2303.3.0
BUILD_ID=2019-12-02-2049
PRETTY_NAME="Container Linux by CoreOS 2303.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Kernel (e.g. `uname -a`):

Linux ip-172-31-16-120.ap-northeast-1.compute.internal 4.19.86-coreos #1 SMP Mon Dec 2 20:13:38 -00 2019 x86_64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz GenuineIntel GNU/Linux

- Install tools:

kubeadm v1.17.0

- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
Have you looked at  kube-controller-manager.log ?

Maybe there is some clue in the log.

**Comment by neolit123** [comment]
hi, did you install a CNI plugin and which one?
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

/remove-kind bug
/triage support

**Comment by neolit123** [comment]
> PRETTY_NAME="Container Linux by CoreOS 2303.3.0 (Rhyolite)"

and

```
  ----     ------       ----                 ----                                                       -------
  Warning  FailedMount  12m (x2 over 18m)    kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[flexvolume-dir], unattached volumes=[k8s-certs kubeconfig usr-share-ca-certificates ca-certs flexvolume-dir]: timed out waiting for the condition
  Warning  FailedMount  8m34s (x2 over 10m)  kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[flexvolume-dir], unattached volumes=[ca-certs flexvolume-dir k8s-certs kubeconfig usr-share-ca-certificates]: timed out waiting for the condition
  Warning  FailedMount  6m31s (x3 over 16m)  kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[flexvolume-dir], unattached volumes=[kubeconfig usr-share-ca-certificates ca-certs flexvolume-dir k8s-certs]: timed out waiting for the condition
  Warning  FailedMount  4m27s                kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[flexvolume-dir], unattached volumes=[flexvolume-dir k8s-certs kubeconfig usr-share-ca-certificates ca-certs]: timed out waiting for the condition
  Warning  FailedMount  2m24s (x2 over 20m)  kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[flexvolume-dir], unattached volumes=[usr-share-ca-certificates ca-certs flexvolume-dir k8s-certs kubeconfig]: timed out waiting for the condition
  Warning  FailedMount  29s (x19 over 22m)   kubelet, ip-172-31-16-120.ap-northeast-1.compute.internal  MountVolume.SetUp failed for volume "flexvolume-dir" : mkdir /usr/libexec/kubernetes: read-only file system

```

do you have an explanation of why `mkdir /usr/libexec/kubernetes` fails?

**Comment by nsano-rururu** [comment]
> hi, did you install a CNI plugin and which one?

I tried to install flanel, but it did not because an error occurred before installation.
When I put Kubernetes 1.16 into CoreOS Container Linux 2303.3.0 at work, the error that occurred this time did not occur. One master node. Operation has been confirmed in six worker node environments.

**Comment by nsano-rururu** [comment]
> Have you looked at kube-controller-manager.log ?
> 
> Maybe there is some clue in the log.

```
$ kubectl logs -n kube-system kube-controller-manager-ip-172-31-16-120.ap-northeast-1.compute.internal

Error from server (BadRequest): container "kube-controller-manager" in pod "kube-controller-manager-ip-172-31-16-120.ap-northeast-1.compute.internal" is waiting to start: ContainerCreating
```

**Comment by neolit123** [comment]
> I tried to install flanel, but it did not because an error occurred before installation.

please try Calico instead of flannel:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

> do you have an explanation of why mkdir /usr/libexec/kubernetes fails?

this error is still puzzling. please try to figure out why.

**Comment by nsano-rururu** [comment]
> > I tried to install flanel, but it did not because an error occurred before installation.
> 
> please try Calico instead of flannel:
> https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

I installed flanel, but there are no pods for flanel. The state of kube-controller-manager and coredns has not changed.

```
$ kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

podsecuritypolicy.policy/psp.flannel.unprivileged created
clusterrole.rbac.authorization.k8s.io/flannel created
clusterrolebinding.rbac.authorization.k8s.io/flannel created
serviceaccount/flannel created
configmap/kube-flannel-cfg created
daemonset.apps/kube-flannel-ds-amd64 created
daemonset.apps/kube-flannel-ds-arm64 created
daemonset.apps/kube-flannel-ds-arm created
daemonset.apps/kube-flannel-ds-ppc64le created
daemonset.apps/kube-flannel-ds-s390x created

$ kubectl get all --all-namespaces

NAMESPACE     NAME                                                                           READY   STATUS              RESTARTS   AGE
kube-system   pod/etcd-ip-172-31-16-120.ap-northeast-1.compute.internal                      1/1     Running             0          21h
kube-system   pod/kube-apiserver-ip-172-31-16-120.ap-northeast-1.compute.internal            1/1     Running             0          21h
kube-system   pod/kube-controller-manager-ip-172-31-16-120.ap-northeast-1.compute.internal   0/1     ContainerCreating   0          21h
kube-system   pod/kube-scheduler-ip-172-31-16-120.ap-northeast-1.compute.internal            1/1     Running             0          21h

NAMESPACE     NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  21h
kube-system   service/kube-dns     ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   21h

NAMESPACE     NAME                                     DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
kube-system   daemonset.apps/kube-flannel-ds-amd64     0         0         0       0            0           <none>                        12s
kube-system   daemonset.apps/kube-flannel-ds-arm       0         0         0       0            0           <none>                        12s
kube-system   daemonset.apps/kube-flannel-ds-arm64     0         0         0       0            0           <none>                        12s
kube-system   daemonset.apps/kube-flannel-ds-ppc64le   0         0         0       0            0           <none>                        12s
kube-system   daemonset.apps/kube-flannel-ds-s390x     0         0         0       0            0           <none>                        12s
kube-system   daemonset.apps/kube-proxy                0         0         0       0            0           beta.kubernetes.io/os=linux   21h

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   0/2     0            0           21h
```
> > do you have an explanation of why mkdir /usr/libexec/kubernetes fails?
> 
> this error is still puzzling. please try to figure out why.

Created a k8s 1.16 environment with AWS EC2 instances added.
After that, I compared /etc/kubernetes/manifests/kube-controller-manager.yaml of 1.16 and 1.17.
The flexvolume-dir setting has increased in 1.17.
The problem is the directory. / CoreOS Usr seems to be a read-only file system (https://stackoverflow.com/questions/37810293/coreos-read-only-file-system)
It seems that an error occurred because trying to create /usr/libexec/kubernetes/kubelet-plugins/ volume/exec failed.
flexvolume-dir's host path The path is not /usr, but another directory. For example, /var/ lib/ kubernetes does not raise an error.

1.16  /etc/kubernetes/manifests/kube-controller-manager.yaml
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=10.244.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --use-service-account-credentials=true
    image: k8s.gcr.io/kube-controller-manager:v1.16.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
status: {}
```

1.17  /etc/kubernetes/manifests/kube-controller-manager.yaml
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=10.244.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --use-service-account-credentials=true
    image: k8s.gcr.io/kube-controller-manager:v1.17.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10257
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-share-ca-certificates
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /usr/share/ca-certificates
      type: DirectoryOrCreate
    name: usr-share-ca-certificates
status: {}
```
