### ISSUE TITLE
ansible module for kuberntes : k8s_scale is getting failed with error: "msg": "Exception reading event stream:

### ISSUE THREAD

**Issue by deepakpal-in** [kubernetes/kubernetes#87078]
**What happened**:

k8s_scale module got failed with error: 

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Exception reading event stream: "}`

I have used the below configuration:

```
- name: Scale deployment up for logstash
  k8s_scale:
    wait_timeout: 600
    api_version: v1
    kind: Deployment
    name: logstash
    namespace: logstash
    current_replicas: 0
    replicas: 1
```

**What you expected to happen**:

scaled-up resources 

**How to reproduce it (as minimally and precisely as possible)**:

```
- name: Scale deployment up for logstash
  k8s_scale:
    wait_timeout: 600
    api_version: v1
    kind: Deployment
    name: logstash
    namespace: logstash
    current_replicas: 0
    replicas: 1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): client and server version 1.14.3
- Cloud provider or hardware configuration: AWS EC2
- OS (e.g: `cat /etc/os-release`): 

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):

Linux cva-builder 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
