### ISSUE TITLE
Enhance discovery of parallel containers via DNS

### ISSUE THREAD

**Issue by kallisti5** [kubernetes/kubernetes#87085]
**What would you like to be added**:

DNS records added to kubedns for various things such as deployments and pods to ease discovery of parallel containers

Example:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coolapp
  namespace: coolnamespace
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: coolapp
        image: app/coolapp:1.0
```

* ```dig coolapp.coolnamespace.deployment.cluster.local```
  * A 10.53.0.12
  * A 10.53.0.45
  * A 10.53.0.64

* ```dig coolapp-324sdf.coolnamespace.pod.cluster.local```
  * A 10.53.0.12
* ```dig coolapp-435asd.coolnamespace.pod.cluster.local```
  * A 10.53.0.45
* ```dig coolapp-3325fsf.coolnamespace.pod.cluster.local```
  * A 10.53.0.64

**Why is this needed**:

* You can launch multiple containers in a deployment (replicas)
* The containers exist within the same network subnet and can communicate
   * Setting replicas to 3.
   * All three IP's can communicate via IP. Finding the IP's of the other nodes is nearly impossible.

Applications can now discover other replicas of themselves by simply checking DNS. No more SRV record hacks for things like etcd, etc.
