### ISSUE TITLE
volumes serviceAccountToken mountVolume.SetUp failed 

### ISSUE THREAD

**Issue by zhengqisong** [kubernetes/kubernetes#87147]
**error message:**        
  Warning  FailedMount  9m54s (x31 over 77m)  kubelet, 192.168.0.2  Unable to mount volumes for pod "sa-token-test_zhen
gqs1(22b45b06-bfca-44cd-96f1-00d8b780f246)": timeout expired waiting for volumes to attach or mount for pod "zhengqs1"/"sa-token-test". list of unm
ounted volumes=[token-vol]. list of unattached volumes=[token-vol default-token-88fzk]                                                             
  Warning  FailedMount  4m36s (x45 over 79m)  kubelet, 192.168.0.2  MountVolume.SetUp failed for volume "token-vol" : f
ailed to fetch token: the server could not find the requested resource

**pod deploy yml**
```
apiVersion: v1
kind: Pod
metadata:
  name: sa-token-test
spec:
  containers:
  - name: container-test
    image: nginx:1.7.9
    volumeMounts:
    - name: token-vol
      mountPath: "/service-account"
      readOnly: true
  volumes:
  - name: token-vol
    projected:
      sources:
      - serviceAccountToken:
          audience: api
          expirationSeconds: 3600
          path: token
```

**kubernetes version:** 1.10.5 upgraded 1.15.4
**os:** centos7
