### ISSUE TITLE
DNS-1123 being enforced on path componentes for auditsink & admission webhook service configuration

### ISSUE THREAD

**Issue by airadier** [kubernetes/kubernetes#87185]
**What happened**:

According to https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#service-reference, I can configure the auditsink webhook to use a service, inside clientConfig spec. The service.path attribute allows to specify the URL path for the service, as:

```
apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
...
spec:
  webhook:
    clientConfig:
      service:
        namespace: my-service-namespace
        name: my-service-name
        path: /my-path
        port: 1234
``` 

However, if any of the path segments is not a valid DNS-1123 name, the validation will fail, as it is being checked in here:

https://github.com/kubernetes/kubernetes/blob/fa6b8e8cac34dba78f374ca9c0940aac1b4b495b/staging/src/k8s.io/apiserver/pkg/util/webhook/validation.go#L98

So I cannot use a path like /my_path (with an underscore).

**What you expected to happen**:

I would expect that path components are not restricted to valid DNS-1123 names.

**How to reproduce it (as minimally and precisely as possible)**:

Try to create an AuditSink resource like:

```
apiVersion: auditregistration.k8s.io/v1alpha1
kind: AuditSink
metadata:
  name: test-auditsink
...
spec:
  webhook:
    clientConfig:
      service:
        namespace: my-service-namespace
        name: my-service-name
        path: /my_path
        port: 1234
``` 

and you get an error like:

Error: AuditSink.auditregistration.k8s.io "test-auditsink" is invalid: spec.webhook.clientConfig.service.path: Invalid value: "/my_path": segment[0]: a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`): 
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:
