### ISSUE TITLE
volume exists，create pod，Error: cannot find volume "default-token-454c5" to mount into container

### ISSUE THREAD

**Issue by OPSTime** [kubernetes/kubernetes#87225]
**version：**
```
$ kubectl  version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**$ cat n7.yml**
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx7
  labels:
    name: nginx
spec:
  containers:
  - name: nginx7
    image: nginx:1.14.2
```

**$ kubectl apply -f n7.yml**
```
pod/nginx7 created
```
**$ kubelet get events**
```
LAST SEEN   TYPE      REASON                   OBJECT            MESSAGE
<unknown>   Normal    Scheduled                pod/nginx7        Successfully assigned default/nginx7 to k8s-node-01
6m3s        Normal    Pulled                   pod/nginx7        Container image "nginx:1.14.2" already present on machine
6m3s        Warning   Failed                   pod/nginx7        Error: cannot find volume "default-token-454c5" to mount into container "nginx7"
```

**$ kubectl get secrets** 
```
NAME                  TYPE                                  DATA   AGE
default-token-454c5   kubernetes.io/service-account-token   3      18d
```

**$ cat n7.yml.new** 
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx7
  labels:
    app: nginx
spec:
  containers:
  - name: nginx7
    image: nginx:1.14.2
```
**$ diff n7.yml n7.yml.new** 
```
6c6
<     name: nginx
---
>     app: nginx
```

`$ kubectl apply -f n7.yml.new`
```
pod/nginx7 created
```
**$ kubelet get events**
```
LAST SEEN   TYPE      REASON                   OBJECT            MESSAGE
<unknown>   Normal    Scheduled                pod/nginx7        Successfully assigned default/nginx7 to k8s-node-01
6m3s        Normal    Pulled                   pod/nginx7        Container image "nginx:1.14.2" already present on machine
6m3s        Warning   Failed                   pod/nginx7        Error: cannot find volume "default-token-454c5" to mount into container "nginx7"
<unknown>   Normal    Scheduled                pod/nginx7        Successfully assigned default/nginx7 to k8s-node-01
6s          Normal    Pulled                   pod/nginx7        Container image "nginx:1.14.2" already present on machine
5s          Normal    Created                  pod/nginx7        Created container nginx7
5s          Normal    Started                  pod/nginx7        Started container nginx7
```

**$ cat n7.yml.new.new** 
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx7
  labels:
    name: test
spec:
  containers:
  - name: nginx7
    image: nginx:1.14.2
```

**diff n7.yml n7.yml.new.new** 
```
6c6
<     name: nginx
---
>     name: test
```
**$ kubectl delete pods nginx7
$ kubectl apply -f n7.yml.new.new**

**$  kubectl get events**
```
LAST SEEN   TYPE      REASON                   OBJECT            MESSAGE
3m22s       Normal    Killing                  pod/nginx7        Stopping container nginx7
<unknown>   Normal    Scheduled                pod/nginx7        Successfully assigned default/nginx7 to k8s-node-01
2m20s       Normal    Pulled                   pod/nginx7        Container image "nginx:1.14.2" already present on machine
2m20s       Normal    Created                  pod/nginx7        Created container nginx7
2m19s       Normal    Started                  pod/nginx7        Started container nginx7
```
