### ISSUE TITLE
kubelet will print csi-plugin register error logs forever even if csi-plugin works well

### ISSUE THREAD

**Issue by k2huang** [kubernetes/kubernetes#87235]
**What happened**:
After we updated our k8s cluster from v1.14.3 to v1.16.3, I noticed that kubelet print below error logs forever, but there was only one same log in v1.14.3. 

```
E0115 15:55:23.150654    4858 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/xxx/csi.sock" failed. No retries permitted until 2020-01-15 15:57:25.150630759 +0800 CST m=+179254.048906300 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/xxx/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
```

**What you expected to happen**:
kubelet don't print above error logs if csi-plugin has worked well as before.

**How to reproduce it (as minimally and precisely as possible)**:
deploy csi node plugin with [below sidecar](https://github.com/kubernetes-csi/node-driver-registrar):
```yaml
      containers:
        - name: csi-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
          args:
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/<drivername.example.com>/csi.sock"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/<plugin> /registration/<drivername.example.com>-reg.sock"]
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/<drivername.example.com>/
            type: DirectoryOrCreate
```
**Anything else we need to know?**:
Maybe this issue was imported by [this commit](https://github.com/kubernetes/kubernetes/commit/5e185544421d5504b0fe2ae32c8ebfb3000a1224)

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
