### ISSUE TITLE
CRD conversion v1beta1 to v1 backup and restore

### ISSUE THREAD

**Issue by jenting** [kubernetes/kubernetes#87231]
**What happened**:

Apply CRD apiVersion `apiextensions.k8s.io/v1beta1` with the non-structural schema to k8s 1.16+, the CRD conversion from v1beta1 to v1.

Then, back up the CRD with yaml manifest, delete CRD and apply backup CRD yaml manifest, the CRD cannot be applied successfully and with validation failed:
```
The CustomResourceDefinition "foos.example.com" is invalid: 
* spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
* spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead
```

**What you expected to happen**:

The CRD could recover from the backup CRD yaml manifest.

**How to reproduce it (as minimally and precisely as possible)**:

- Prepare file `foos.example.com.yaml`
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com
spec:
  group: example.com
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    singular: foo
  version: v1
  scope: ""
```

- Execute commands
```
kubectl apply -f foos.example.com.yaml

kubectl get crd foos.example.com -o yaml > foos.example.com.backup.yaml
kubectl delete crd foos.example.com
kubectl apply -f foos.example.com.backup.yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-12-04T07:23:47Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
  - `kind v0.6.1 go1.13.4 linux/amd64`
- Network plugin and version (if this is a network-related bug):
- Others:
