### ISSUE TITLE
extend EnvVarSource to use data from CRD / ability to extend Secrets in CRD

### ISSUE THREAD

**Issue by bukowa** [kubernetes/kubernetes#87300]
**What would you like to be added**:
Currently [EnvVarSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#envvarsource-v1-core) accepts only:
````
configMapKeyRef | Selects a key of a ConfigMap.
fieldRef | Selects  a field of the pod: supports metadata.name, metadata.namespace,  metadata.labels, metadata.annotations, spec.nodeName,  spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.
resourceField | Selects  a resource of the container: only resources limits and requests  (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu,  requests.memory and requests.ephemeral-storage) are currently supported.
secretKeyRef | Selects a key of a secret in the pod's namespace
````
We could load that data from a CRD.
````yaml
              valueFrom:
                CRD:
                  apiVersion: mycrd.com/v1
                  kind: Account
                  name: example
                  key: data handled by my controller that i couldn't use before
````
Another idea is to be able to extend `secrets` resource in CRD (so we could define custom Secret definition that will re-use existing `secrets` logic.
````yaml
              valueFrom:
                secretKeyRef:
                  # default
                  apiVersion: secrets
                  # default
                  kind: Secret
                  name: example
                  key: data handled by my controller that i couldn't use before
````
````yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accounts.example.com
spec:
  scope: Namespaced
  # something better here
  extends: v1/Secret
  group: example.com
  names:
    plural: accounts
    singular: account
    kind: Account
    shortNames:
      - acc
  versions:
    - name: v1
      served: true
      storage: true
````
**Why is this needed**:
While defining CRD that will be consumed by a custom Controller (for example creating account in a database), POD may need to reuse that data. Giving controller access to secrets may not be a good idea.
