### ISSUE TITLE
Add well-known label for custom endpoint controller as well as "service.kubernetes.io/service-proxy-name"

### ISSUE THREAD

**Issue by s1061123** [kubernetes/kubernetes#87412]
**What would you like to be added**:

Add well-known label at endpoint/endpointslice controller to delegate endpoint/endpointslice control to custom endpoint/endpointslice controllers.

**Why is this needed**:

kube-proxy has well-known label for custom proxy, ["service.kubernetes.io/service-proxy-name"](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/apis/well_known_labels.go#L22) that delegates service control to custom proxy. With the label, kube-proxy does not generate iptables for the service. However endpoint/endpointslice controller does not have similar label, hence the issue address it.

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by uablrek** [comment]
On the [sig-network meeting 2020-02-20](https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit) a work-around using a webhook was mentioned. I have a simpler work-around that may be tested; Define the service without a [selector](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors) then no endpoints will be assigned by kubernetes. Then add the selector as an annotation so your custom endpoint controller can set the endpoints in it's own way. Example;
```
apiVersion: v1
kind: Service
metadata:
  name: mconnect
  labels:
    service.kubernetes.io/service-proxy-name: my-lb-setup
  annotations:
    example.com/selector: mconnect
spec:
  ipFamily: IPv4
  ports:
  - port: 5001
```
