### ISSUE TITLE
Pod fails to connect to volume github due to proxy

### ISSUE THREAD

**Issue by davesargrad** [kubernetes/kubernetes#87465]
I am following the examples in Kubernetes in Action.

I am currently trying to create the following pod:

```
apiVersion: v1
kind: Pod
metadata:
        name: gitrepo-volume-pod
spec:
        containers:
                -       image: nginx:alpine
                        name: web-server
                        volumeMounts:
                        -       name: html
                                mountPath: /usr/share/nginx/html
                                readOnly: true
                        ports:
                        -       containerPort: 80
                                protocol: TCP
        volumes:
                -       name: html
                        gitRepo:
                                repository: https://github.com/luksa/kubia-website-example.git
                                revision: master
                                directory: .
```

The pod fails to connect to github:
![image](https://user-images.githubusercontent.com/48793689/72924491-037c9c00-3d1f-11ea-9f21-29d911c8da0c.png)

I am reasonably sure that this is because of our corporate proxy. 

Docker is configured to use our proxy propertly: see following snippet return from `docker info`
![image](https://user-images.githubusercontent.com/48793689/72924581-31fa7700-3d1f-11ea-94ea-41cc64d977ff.png)

Note the IP address 10.93.97.202 in the above image, is the private docker registry that my pods pull many of their images from (again without any proxy problems). 

My system in general seems to be configured properly for the corporate proxy. I've not had any problems creating applications (replicationcontrollers, cronjobs, replicasets, daemonsets, etc), and the resulting pods. I've also been able to create services to expose the application ip accessible resources.

However this is the first time I've tried to create a pod that must get through the proxy for a gitRepo volume.

What proxy configuration do I need to add (presumably to each k8s node) to allow this deprecated [gitrepo](https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo) volume to be used.?

/sig cluster-lifecycle
/sig usability
