### ISSUE TITLE
CronJob creation fails when using AWS Secret Access key as config key 

### ISSUE THREAD

**Issue by pkaramol** [kubernetes/kubernetes#87486]
**What happened**:

Creation of `CronJob` resource failed

**What you expected to happen**:

Creation of `CronJob` to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

Try to apply the following resource

(the AWS credentials have been scrambled of course, but I think it is the presence of the `+` character causing the issue) 

```
# Source: jenkins/templates/jenkins-backup-cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: myjenkins-backup
  namespace: jenkins
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-1.9.16"
    "app.kubernetes.io/managed-by": "Tiller"
    "app.kubernetes.io/instance": "myjenkins"
    "app.kubernetes.io/component": "jenkins-backup"
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        metadata:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: myjenkins-backup
          containers:
          - name: jenkins-backup
            image: "maorfr/kube-tasks:0.2.0"
            command: ["kube-tasks"]
            args:
            - simple-backup
            - -n
            - jenkins
            - -l
            - app.kubernetes.io/instance=myjenkins
            - --container
            - jenkins
            - --path
            - /var/jenkins_home
            - --dst
            - s3://jenkins-data/backup
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: jenkinsaws
                  key: "AKIADFD435345321B"
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: jenkinsaws
                  key: "123434ufh2040l+5ZEGfJEyULK43423iUYeQkw"
            resources:
              limits:
                cpu: 1
                memory: 1Gi
              requests:
                cpu: 1
                memory: 1Gi
            volumeMounts:
          volumes:
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  topologyKey: "kubernetes.io/hostname"
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - myjenkins
                    - key: release
                      operator: In
                      values:
                      - myjenkins
```

The process fails with the following error:

```
The CronJob "myjenkins-backup" is invalid: spec.jobTemplate.spec.template.spec.containers[0].env[1].valueFrom.secretKeyRef.key: Invalid value: "123434ufh2040l+5ZEGfJEyULK43423iUYeQk": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

**Anything else we need to know?**:

The investigation of this issue was initiated when attempting to install `Jenkins` using the official [helm chart](https://github.com/helm/charts/blob/master/stable/jenkins/templates/jenkins-backup-cronjob.yaml) that creates a `CronJob` as the above.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-gke.8", GitCommit:"39fe6cf6b77a3a0f620bd89db92f5133be67aa91", GitTreeState:"clean", BuildDate:"2019-11-07T19:14:31Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): Client-side execution has been attempted from both in MacOS Catalina and Debian 9.
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A
