### ISSUE TITLE
Port Forwarding Does Not Work If App is Bound to Pod IP Address

### ISSUE THREAD

**Issue by shawnweeks** [kubernetes/kubernetes#87484]
**What happened**:

`E0122 19:58:23.513876   17023 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 718c10d29931044bc5eace4bb2eafc32c522e523e0fe12423996c84ae98156cb, uid : exit status 1: 2020/01/23 01:58:23 socat[38589] E connect(16, AF=2 127.0.0.1:8080, 16): Connection refused`

**What you expected to happen**:

Port forwarding to work and for me to be able to access the Apache NiFi UI

**How to reproduce it (as minimally and precisely as possible)**:

```
helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
helm install --name zookeeper incubator/zookeeper
```

Wait for it to stabilize then deploy this yaml script.

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: .5G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: .5G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data2"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: .5G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data3"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: .5G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data4"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-5
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: .5G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data5"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-6
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: .5G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data6"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi-qa
spec:
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  serviceName: nifi-qa
  selector:
    matchLabels:
      app: nifi-qa
  template:
    metadata:
      labels:
        app: nifi-qa
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - image: apache/nifi:latest
          imagePullPolicy: Always
          name: nifi-qa
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 8443
            - containerPort: 2882
            - containerPort: 7015
            - containerPort: 10000
          volumeMounts:
            - mountPath: "/opt/nifi/nifi-current/logs"
              name: nifiqalogsclaim
            - mountPath: "/opt/nifi/nifi-current/state"
              name: nifiqastateclaim
          env:
            - name: MY_NAME_SPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NIFI_CLUSTER_IS_NODE
              value: "true"
            - name: NIFI_ZK_CONNECT_STRING            
              value: "zookeeper:2181"
            - name: NIFI_ZK_ROOT_NODE
              value: "/nifiqa"
            - name: NIFI_CLUSTER_NODE_PROTOCOL_PORT
              value: "2882"
            - name: "NIFI_ELECTION_MAX_CANDIDATES"
              value: "3"
            - name: "NIFI_FLOW_CONFIGURATION_FILE"
              value: "./state/flow.xml.gz"
            - name: "NIFI_DATABASE_DIRECTORY"
              value: "./state/database_repository"
            - name: "NIFI_CONTENT_REPOSITORY_DIRECTORY_DEFAULT"
              value: "./state/content_repository"
            - name: "NIFI_FLOWFILE_REPOSITORY_DIRECTORY"
              value: "./state/flowfile_repository"
            - name: "NIFI_PROVENANCE_REPOSITORY_DIRECTORY_DEFAULT"
              value: "./state/provenance_repository"
            - name: "NIFI_WEB_HTTP_HOST"
              value: "$(MY_POD_NAME).nifi-qa"
            - name: NIFI_CLUSTER_ADDRESS
              value: "$(MY_POD_NAME).nifi-qa"
            - name: NIFI_REMOTE_INPUT_HOST
              value: "$(MY_POD_NAME).nifi-qa"              
  volumeClaimTemplates:
    - metadata:
        name: nifiqastateclaim
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: manual
        resources:
          requests:
            storage: .5G
        selector:
          matchLabels:
            type: local
    - metadata:
        name: nifiqalogsclaim
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: manual
        resources:
          requests:
            storage: .5G
        selector:
          matchLabels:
            type: local

```

Then run the following and try to access the UI. Which will fail with connection refused.

`kubectl port-forward nifi-qa-0 8080:8080`

If you change this line you'll be able to connect but forcing the host name to 0.0.0.0 breaks things badly.

```
- name: "NIFI_WEB_HTTP_HOST"
  value: "$(MY_POD_NAME).nifi-qa"
```

**Anything else we need to know?**:

**Environment**:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
Darwin Shawns-Mac-mini.weeksconsulting.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
