### ISSUE TITLE
CEPHFS: File exists

### ISSUE THREAD

**Issue by suvl** [kubernetes/kubernetes#87491]
We're experiencing recurring problems with cephfs mounts on cronjobs. A lot of them result in the following kind of errors:
```
    State:          Terminated
      Reason:       ContainerCannotRun
      Message:      error while creating mount source path '/var/lib/kubelet/pods/22f40f9a-8588-4fd7-9ef3-7fec25b48f12/volumes/kubernetes.io~cephfs/cephfs': mkdir /var/lib/kubelet/pods/22f40f9a-8588-4fd7-9ef3-7fec25b48f12/volumes/kubernetes.io~cephfs/cephfs: file exists
      Exit Code:    128
```
The volume is declared as
```
            volumes:
            - cephfs:
                monitors:
                - ceph-mon-01
                - ceph-mon-02
                - ceph-mon-03
                path: /generic/applications/analytics
                secretRef:
                  name: ceph-generic-key
                user: generic
              name: cephfs
```
and the fact is that sometimes this works.

We've ruled out node issues (it works and fails on the same nodes), kubernetes versions (this problem holds in 1.14, 1.15 and 1.16) and ceph versions (holds for v12, v13 and v14). Also happens on deployments, where the fix is simply deleting the pod (even if the pod is recreated on the same node it will successfully mount the folder).

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64
- Install tools: RKE
- ceph version: 14.2.4
