### ISSUE TITLE
unable to reapply statefulset with volumeClaimTemplate/apiVersion

### ISSUE THREAD

**Issue by pgier** [kubernetes/kubernetes#87583]
**What happened**:
I tried to apply the same statefulset twice and on the second apply, the api reported a validation error.

**What you expected to happen**:
I would expect that the same statefulset should apply successfully or fail consistently any number of times.

**How to reproduce it (as minimally and precisely as possible)**:
Apply this stateful set twice.
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
```

The second attempt with fail.
```
The StatefulSet "web" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

**Anything else we need to know?**:
The cause of this appears to be the combination of the api server removing the `apiVersion` and `kind` fields from the applied configuration, and the api server performing validation to see that nothing has changed in the config.  The same issue does not appear in kubernetes v1.16 because even though the `apiVersion` and `kind` fields are removed, the validation is not performed.

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
