### ISSUE TITLE
Remove version from status.storedVersions not possible

### ISSUE THREAD

**Issue by lucky125111** [kubernetes/kubernetes#87691]
**What happened**:

I tried the scenario where I want to remove version from status.storedVersions while Manually upgrading the existing objects to a new stored version.

Attempts to remove old stored version:
1. `kubectl` - I tried to remove the first version by applying new definition crd2.yaml

`kubectl apply -f crd2.yaml`
_crd2.yaml_:
```yaml
    - name: v2
      served: true
      storage: true
```

error:
* spec.version: Invalid value: "v1": must match the first version in spec.versions
* status.storedVersions[0]: Invalid value: "v1": must appear in spec.versions

2. Update spec version via Rest API
I connect to cluster via kubernetes proxy

```bash
curl -d '[{ "op": "replace", "path":"/status/storedVersions", "value": ["v2"] }]' -H "Content-Type: application/json-patch+json" -X PATCH http://localhost:8080/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/$resource_name
```
I get as a response 200 OK, but the version hasn't been removed

3. Golang client

I got the storedVersion removed using this [script](https://github.com/elastic/cloud-on-k8s/issues/2196#issuecomment-560318404)

**What you expected to happen**:

I expected such operation would be possible with kubectl or api not only via go sdk.

**How to reproduce it (as minimally and precisely as possible)**:

here's the resource definitions:
crd1.yaml
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  version: v1
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```

crd12.yaml
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: false
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```

crd2.yaml
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                replicas:
                  type: integer
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```

**First Created dummy resource**
1. First created the resource crd1.yaml

`kubectl apply -f crd1.yaml`
_crd1.yaml_:
```yaml
   versions:
    - name: v1
      served: false
      storage: false
```

2. Update resource with definition of version 2 crd12.yaml
`kubectl apply -f crd12.yaml`

_crd12yaml_:
```yaml
  versions:
    - name: v1
      served: false
      storage: false
    ...
    - name: v2
      served: true
      storage: true
```

3. Confirming that two versions are present

`kubectl get CustomResourceDefinition $resouce_name -o yaml`

```yaml
  versions:
  - name: v1
    served: false
    storage: false
  - name: v2
    served: true
    storage: true
...
  storedVersions:
  - v1
  - v2
```
No you can run the commands I mentioned in bug description

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.11-gke.23
- Cloud provider or hardware configuration: Google cloud platform
- I opened this issue in the documentation repository as well and sugested describing how to solve this issue. But I guess still such case shouldn't happen
