### ISSUE TITLE
kubectl describe pod - structured output appears to contradict event log during deployment startup.

### ISSUE THREAD

**Issue by sleekweasel** [kubernetes/kubernetes#87775]
**What happened**:

I'm deploying a number of containers to a number of nodes that run nothing else. I explicitly delete the previous instance of each node's deployment before re-deploying, and after my tests.

There's one pod per node, I have configured no start/ready probes, no resource allocation (cpu, etc) because the nodes are dedicated. The status/control container within my pod deals with whatever state it finds the other containers to be in when it wakes up.

From starting the deployment, to when I can fetch the IP address to talk to my status/control service usually takes only a minute, but sometimes it exceeds 5 minutes which is the random cut-off time I've decided I don't want to exceed.

In order to try to understand the cause of this occasional 5 minute start-up, my script (which runs a loop to poll 'kubectl get pods' for status==ready) also now records the output of 'kubectl describe pod' for each pod.

In the 'describe' output, the yaml structured output shows the containers as State:Waiting and  Reason:ContainerCreating, but the event output shows some of those containers as 'Started'. Nowhere does the output show quite what it is that everyone else is waiting for.

So please consider this 'CreatING' status below which persists for all calls to 'describe' until app containers abruptly report themselves as 'ready' and the IP address becomes available.
```
  emulator-5554:
    Container ID:   
    Image:          dockerio.dlan/auto/android-avd-10a29v8-emu29_0_11_kuber-snapshot-skin_name-540x1060-hw_lcd_density-240
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
```
and contrast it with the events' listing's 'startED' which says the 'Creating' has very much completed.
```
  Normal  Pulling    15s   kubelet, automation11.dlan  Pulling image "dockerio.dlan/auto/android-avd-10a29v8-emu29_0_11_kuber-snapshot-skin_name-540x1060-hw_lcd_density-240"
  Normal  Pulled     15s   kubelet, automation11.dlan  Successfully pulled image "dockerio.dlan/auto/android-avd-10a29v8-emu29_0_11_kuber-snapshot-skin_name-540x1060-hw_lcd_density-240"
  Normal  Created    15s   kubelet, automation11.dlan  Created container emulator-5554
  Normal  Started    15s   kubelet, automation11.dlan  Started container emulator-5554
```

Have these started or not?

While I could happily ignore the structured output and monitor the event log, the event log is mysteriously truncated at 26 entries - dropping anything later than that - despite our configuration not imposing any such limit.

**What you expected to happen**:

I expected the structured yaml output to match the data in the event log.

I expected there to be some sort of 'starting up' or 'pulling image' or 'waiting for old deployment to terminate' information in the structured yaml output, to give some clue why I'm occasionally sat waiting for 5 minutes. (This issue is not about that unpredictable wait, but about the tools available for investigating it.)

I expected the event log to show the latest events (perhaps truncated to the final few), not only the first 26.

**How to reproduce it (as minimally and precisely as possible)**:

Give a node a label 'pod-agent=mysh' then run this with the file mentioned below:

rm -f /tmp/kmych.*
kubectl delete svc,deploy,pods --grace-period=0 kubulator-mysh-automation11-mlan
kubectl create -f /tmp/thin.yaml
while sleep 1; do
  P=$(kubectl get pods -l pod-agent=mysh | grep -v NAME | grep -v Terminating | cut -f1 -d ' ')
  kubectl get pods -l pod-agent=mysh ; kubectl describe pod $P |
     cat |
     tee $(date +/tmp/kmych.%F.%T.log) |
     grep -i ready |
     uniq -c
done

Eventually all three 'Ready:' fields will simultaneously flip from false to true - this doesn't seem to be related to the termination of the previous pod (and wouldn't be the cause of my 5 minute delay, because I kill them at the end of my test session as well as at the start).

```
...
     19     Ready:          False
      1   Ready             False 
      1   ContainersReady   False 
      1 Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
     19     Ready:          True
      1   Ready             True 
      1   ContainersReady   True 
      1 Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
...
...
```

where /tmp/thin.yml is this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubulator-mysh-automation11-dlan
  labels:
    pod-agent: mysh
spec:
  selector:
    matchLabels:
      run: kubulator-mysh-automation11-dlan
      pod-agent: mysh
  replicas: 1
  template:
    metadata:
      labels:
        run: kubulator-mysh-automation11-dlan
        pod-agent: mysh
    spec:
      nodeSelector:
        kubernetes.io/hostname: automation11.dlan
      volumes:
        - name: dev-kvm
          hostPath:
            path: /dev/kvm
            type: CharDevice
        - name: logs
          emptyDir: {}
      containers:
        - name: cgi-adb-remote
          image: busybox
          args: ['/bin/sh', '-c', 'sleep 6000']
          imagePullPolicy: Always
        - name: twenty or so more of these
```

I have no idea how to track down the occasional 5 minute pause - I expected to be able to diagnose it from 'describe'. If it's doing what it should, could someone point me in a better direction?

**Anything else we need to know?**:

I'm happy to share the config files if it would help, but I'm guessing the start-up phase simply doesn't update the datastructure exposed by 'describe'.

**Environment**:

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-21T22:17:28Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

Bunch of our own Linux server machines? Not quite sure what you want here.

- OS (e.g: `cat /etc/os-release`):

NAME="SLES"
VERSION="12-SP4"
VERSION_ID="12.4"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp4"

- Kernel (e.g. `uname -a`):

Linux automation17 4.14.83-0.1-default #1 SMP PREEMPT Mon Nov 13 14:53:06 UTC 2017 (c152297) x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

zypper/puppet.

- Network plugin and version (if this is a network-related bug):

Not a network bug, so far as I know.

- Others:
