### ISSUE TITLE
cronjob not run command in Kubernetes

### ISSUE THREAD

**Issue by harshul4274** [kubernetes/kubernetes#87846]
Hello All, I just deployed Kind CronJob pod than i check the status pod is error and can't take a backup of MYSQL but i deployed a Kind Pod a succesfully take backup. My issue is i deploy the cronjob but can not properly deploy a pod.

My pod status is
- mysql-backup-1580899560-crqb8                           1/2     Error              0          77s

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "true"
        spec:
          containers:
          - image:###############mysql:5.7.22
            name: mysql-backup
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ###secret
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ###secret
                  key: user
            - name: MYSQL_HOST
              value: "##################"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "##########"
            - name: GCS_BUCKET
              value: "##########"
            volumeMounts:
            - name: backup
              mountPath: /backup
            command: ["/bin/sh"]
            args: ["-c", "mkdir -p /backup && sleep 5 && /usr/bin/mysqldump -u ${MYSQL_USER} -p${MYSQL_ROOT_PASSWORD} -h ${MYSQL_HOST} -P ${MYSQL_PORT} ${MYSQL_DATABASE} > /backup/${MYSQL_DATABASE}_$(date +'%m_%d_%Y').sql && ls -al /backup/*"]
          restartPolicy: Never
          imagePullSecrets:
          - name: ###########-secret
          volumes:
          - name: backup
            hostPath:
              path: /var/data/backup
```

This is describe pod status
------------------------------
Command:
      /bin/bash
    Args:
      -c
      mkdir -p /backup && sleep 5 && /usr/bin/mysqldump -u  -p -h  -P   > /backup/_02_05_2020.sql && ls -al /backup/*
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 05 Feb 2020 10:46:50 +0000
      Finished:     Wed, 05 Feb 2020 10:46:55 +0000
    Ready:          False
    Restart Count:  0
    Environment:
      MYSQL_ROOT_PASSWORD:  <set to the key 'password' in secret 'mysql-secret'>  Optional: false
      MYSQL_USER:           <set to the key 'user' in secret 'mysql-secret'>      Optional: false
      MYSQL_HOST:           ###############
      MYSQL_PORT:           3306
      MYSQL_DATABASE:       ###########
      GCS_BUCKET:           ############

Events:
  Type     Reason     Age                From                        Message
  ----     ------     ----               ----                        -------
  Normal   Scheduled  95s                default-scheduler           Successfully assigned 
  Normal   Pulled     92s                kubelet,  Container image "
  Normal   Created    90s                kubelet,  Created container istio-init
  Normal   Started    89s                kubelet,   Started container istio-init
  Normal   Pulling    85s                kubelet,   Pulling image 
  Normal   Created    53s                kubelet,  Created container mysql-backup
  Normal   Started    52s                kubelet,   Started container mysql-backup
  Normal   Pulled     52s                kubelet,   Container image 
  Normal   Created    49s                kubelet,   Created container istio-proxy
  Normal   Started    48s                kubelet,   Started container istio-proxy
  Warning  Unhealthy  46s (x2 over 48s)  kubelet,  Readiness probe failed: HTTP probe failed with statuscode: 503
