### ISSUE TITLE
Failed to prepare subPath for volumeMount: is there a nesting (depth) limit?

### ISSUE THREAD

**Issue by michaelrath-work** [kubernetes/kubernetes#87888]
**What happened**:

Setting `subPath` to a (deeply) nested folder structure suddenly fails. Is there a (undocumented) limit on how many subfolders can be specified?

**What you expected to happen**:

`subPath` is not limited.

**How to reproduce it (as minimally and precisely as possible)**:

I use the following config:

```yaml
spec:
  containers:
  - name: main
    volumeMounts:
    - name: workspace
      mountPath: /workspace
      readOnly: false
      subPath: micha/a/b/c                    # <- Problem?

  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: nfs-server
```
Running my pod leads to 
   Error: failed to prepare subPath for volumeMount "workspace" of container "main"

The `persistentVolumeClaim` points to a NFS persistent volume. The folder structure `micha/a/b/c` exists on the NFS share, of course. And all the folder have the same permissions.

However, if I change the `subPath` to something shorter (i.e. less levels), no error occurs. The maximum depth seems to be **2**, e.g.

```yaml
subPath: micha/a
```

is the *deepest* level I managed to run.

**Anything else we need to know?**:

**Environment**:
- Client version: 1.17.0
- Server version: 1.15.4
- on premise server (bare metal) running on "Ubuntu 18.04.2 LTS"

/sig storage

**Comment by wawa0210** [comment]
/assign 

I will continue to follow up on this issue, and then timely feedback what I know

**Comment by wawa0210** [comment]
I just tried to reproduce this issue as you described, but subpath works fine

this is my rc yaml from https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-busybox-a
spec:
  replicas: 2
  selector:
    name: nfs-busybox-a
  template:
    metadata:
      labels:
        name: nfs-busybox-a
    spec:
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'while true; do date >> /mnt/micha/a/b/c/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
          - name: nfs
            mountPath: "/mnt"
            subPath: micha/a/b/c
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
```
No error was reported after successful deployment, index.html was written normally.
Can you provide more detailed information

**Comment by michaelrath-work** [comment]
Hi,

thanks for looking into my issue. Here are more details. You already know how I configured my Pod, here are the remaining parts.

This is the `PersistentVolumeClaim`

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace
  namespace: devel
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 12Ti
  selector:
    matchLabels:
      nfs-export: workspace
      nfs-server: my-nfs-server
```

and this the respective `PersistentVolume`

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace
  labels:
    nfs-server: my-nfs-server
    nfs-export: workspace
spec:
  capacity:
    storage: 12Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server:  XXX                          # <- obfuscated
    path: "/workspace"
```

I obfuscated the NFS server address with **XXX**.  This server simply exports the respective folder using the following settings:

- Permission: read/write
- Squash: ROOT_SQUASH

Is there anything else I can provide? E.g. I just posted the error message of my pod using `kubectl describe pod ...` an the message is just `Failed to prepare subPath for volumeMount ...`. How can I get detailed information (logs) why **exactly** the preparation failed, i.e. wrong permissions, none  existing directory etc. ? 
*preparation failed* is really  vaque and could be anything.

Michael
