### ISSUE TITLE
Pod stuck at ContainerCreating status- Unable to attach or mount volumes: unmounted volumes

### ISSUE THREAD

**Issue by AdriseYounis** [kubernetes/kubernetes#87934]
**Goal:**
I am trying to allow my pod to access the azure keyvault to retrieve secret data using key vault flexvolume.

I have used service principal authentication in which will allow minikube to talk to the azure key vault.

The kubernetes service i am using is not deployed to azure but it is running on my local machine. 

`minikube version: v1.6.2`

I have followed the instruction on the below github tutorial. 
- https://github.com/Azure/kubernetes-keyvault-flexvol#getting-started

Each time I deploy my deployment.yaml file I get the bellow failure and the reason is **FailedMount**.

```
NAME                                        READY   STATUS              RESTARTS   AGE
workerservice-deployment-6b89575585-4wszr   0/1     ContainerCreating   0          3s
workerservice-deployment-6b89575585-fz6sr   0/1     ContainerCreating   0          3s
```

`  Warning  FailedMount  19s (x4 over 2m54s)  kubelet, minikube  Unable to attach or mount volumes: unmounted volumes=[kvvolume], unattached volumes=[default-token-72vgw kvvolume]: failed to get Plugin from volumeSpec for volume "kvvolume" err=no volume plugin matched`

kubectl get pods -n kv

```
NAME                        READY   STATUS    RESTARTS   AGE
keyvault-flexvolume-9k5gp   1/1     Running   0          75m

```
Deployment.yaml file 

```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: workerservice-deployment
spec:
  selector:
    matchLabels:
      app: workerservice-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: workerservice-pod
    spec:
      containers:
      - name: ws-container
        image: acr.azurecr.io/workerservice:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        volumeMounts:
        - name: kvvolume
          mountPath: /kv
          readOnly: true
      volumes:
        - name: kvvolume
          flexVolume:
            driver: "azure/kv"
            options:
              keyvaultname: “keyvault-appdemo"              
              keyvaultobjectnames: "dbconnectionstring"    
              keyvaultobjecttypes: secret               
              resourcegroup: "rg-kubernetes"        
              subscriptionid: "<subscriptionid>" //supplied 
              tenantid: "<tenantid>" //supplied 
```

If you require further information please do let me know as I unable to identify the cause of the problem.
