### ISSUE TITLE
ENV files for pods

### ISSUE THREAD

**Issue by tanmaybinaykiya** [kubernetes/kubernetes#8800]
Docker supports a way to push environment variables to the containers using env files. I see that there is a way to push env-variables via the pod creation JSON but I don't see anyway to push env-files for the same. Is there any other way to do this?

**Comment by thockin** [comment]
What is an env file in the context of an API call?  Can you describe the
behavior you expect to see?

On Tue, May 26, 2015 at 12:30 AM, Tanmay Binaykiya <notifications@github.com

**Comment by bgrant0607** [comment]
This is docker run --env-file:
https://docs.docker.com/reference/commandline/cli/#run

For now you could write a simple script to pre-process your json.

**Comment by luebken** [comment]
Seems this can be closed in favour of https://github.com/kubernetes/kubernetes/issues/11492

**Comment by bgrant0607** [comment]
cc @pmorie

**Comment by bgrant0607** [comment]
@luebken This is not a duplicate of #11492. At minimum, we'd need to add another argument to kubectl run in order to surface this capability.

**Comment by Nighthawk22** [comment]
Will this feature be implemented?

**Comment by bgrant0607** [comment]
@Nighthawk22 Nobody has so far volunteered to implement this. PRs are welcome.

Sort of related to #26299

**Comment by dhoer** [comment]
@bgrant0607 I would like to propose the following and get some feedback on it.  

In http://kubernetes.io/docs/user-guide/configmap/:

The _Creating from directories_ section  shows the following:
```yaml
apiVersion: v1
data:
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:34:05Z
  name: game-config
  namespace: default
  resourceVersion: "407"-
  selfLink: /api/v1/namespaces/default/configmaps/game-config
  uid: 30944725-d66e-11e5-8cd0-68f728db1985
```

The _Use-Case: Consume ConfigMap in environment variables_ section shows this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.type
  restartPolicy: Never
```

I would like to propose that the env section be modified so that if key is an array that contains key value pairs, then it will automatically process those key value pairs into environment variables.

Example:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: name-is-ignored-when-key-points-to-array
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: game.properties
        - name: name-is-ignored-when-key-points-to-array2
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: ui.properties
  restartPolicy: Never
```

Let me know your thoughts on this and if it would be accepted as a PR. If it is, then please point me to the code where this change should be made or assign it to someone who could implement the change.  I haven't had to program in go lang yet, but I will take a crack at it, if no one steps up to the plate.  

The reason I think this change is important is because I would like development to use tools like docker and docker-compose with no changes required for devops to implement in k8s.

**Comment by thockin** [comment]
I don't like the "name is ignored" semantic - it feels like a square peg in
a round hole.  That field is required, so it can't be empty.  Making it
non-unique is PROBABLY ok, but is strictly a breaking change....

Can we find a better way to express this?

**Comment by dhoer** [comment]
@thockin What do you propose? Maybe names must match:
```yaml
      env:
        - name: game-config
          valueFrom:
            configMapKeyRef:
              name: game-config
              key: game.properties
```

**Comment by dhoer** [comment]
I really would like a switch of some sort, name and configMap switch:
```yaml
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
        - configMap: game-config
           file: game.properties
```

**Comment by thockin** [comment]
I don't have an immediately better answer.  The env API did not consider
this use case. One DiY way is to project the configmap into a file on disk
and make the entrypoint read it in before launching the main program.

**Comment by dhoer** [comment]
That is one approach. But if you have developers on Windows platform, then you introduce some if the immaturity that docker and docker-compose brings to the table such as; not handling CRLF, and execute permission differences between docker and docker-compose.

Environment properties should be a separation-of-concern. The current solution is too tightly coupled and adds deployment risks and costs because of this. It would be nice to have developers create, update and delete environment settings without the need for updates to deployment files or re-engineering their containers to handle the limitations of k8s. 

I like the idea of using configmap to slurp up environment files into one bucket.  We just need to refactor env to be able to use it.  I threw my suggestions out there, I would like to see other approaches and come to some consensus on what approach would be acceptable.

**Comment by thockin** [comment]
Dennis,

There's always "the right way" which takes time.  I was offering what I
hope is a realistic workaround that works TODAY.  Given the timeline, this
will not land until 1.6, so we have some time to gather ideas, I guess.

**Comment by dhoer** [comment]
I think we are on the same page here.  I'm hoping for a solution for 2nd quarter next year as we open our clusters up to the masses.  

So how do we go about generating input on "the right way" solution?

**Comment by thockin** [comment]
This is a start.  Maybe a better title for this issue.  Maybe getting a SIG
involved to generate traffic - not sure which SIG, though.  email to
kubernetes-dev ?

**Comment by dhoer** [comment]
@thockin Looks like PR https://github.com/kubernetes/kubernetes/pull/36245 would satisfy this use case.  Can that PR be green lighted for 1.5?

**Comment by thockin** [comment]
I think that might be workable as an API, but I don't think it can go for
1.5 - it's just too late in the cycle.

**Comment by thockin** [comment]
We should clarify if this issue is about client-side reading a file and creating env vars in a pod API call, or about a pod late-binding multiple configmap keys into env vars 1-to-1.  The latter is also #26299

**Comment by dhoer** [comment]
@thockin #26299 would get us close enough with configmap flat data, e.g., 
```yaml
data:
  special.how: very
  special.type: charm
```
but having the ability to also point to a specific list pulled in using from-file would be sweeter, e.g., read in game.properties to env from:
```yaml
data:
  game.properties: |-
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice
```

Should the latter be clarified here, tacked on to #26299 requirement under a new issue, or handled in another way?

Finally, 
It would also be nice to have a `--flatten` switch for `configmap create` that would allow `--from-file` to write to the root of data.  Keys repeated in later files would overwrite previous values.  I'm sure this is already written up, if not, I can write that up as well.

**Comment by dhoer** [comment]
@thockin I created https://github.com/kubernetes/kubernetes/issues/37011 to address `--flatten` switch for `configmap create`.

**Comment by bgrant0607** [comment]
@dhoer Please post to kubernetes-sig-apps at googlegroups.com to make others aware of this design discussion.

**Comment by bgrant0607** [comment]
@dhoer You don't imagine creating a ConfigMap with separate keys and values, for which the proposal in #26299 would work?

**Comment by bgrant0607** [comment]
@thockin SIG Apps is the appropriate SIG.

**Comment by dhoer** [comment]
@bgrant0607 I'm not sure what you are asking.

I'm assuming #26299 can't handle nested maps that are created when using --from-file.  Is that a correct assumption? 

I would like for development's environment files to remain the same as they are for docker and docker-compose.  How k8s uses those files is a separation-of-concern.  This frees up developers to add, update and delete environment files without having to communicate those fine grain details. 

Configmap could then be used to pull in one or many environment files.  Unless I'm misunderstanding #26299, it expects the data to be flat.  Configmap makes it easy to pull in env files, but it doesn't pull them in flat but as a nested map. So this can be handled in 2 ways; 1) having the --flatten switch mentioned in #37011 or 2) allow env to point to nested map, e.g., 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: space-simulator
spec:
  containers:
  - name: space-simulator
    image: foo/space-simulator
  - envFrom:
      configMap: game-config/game.properties
  - envFrom:
      configMap: game-config/ui.properties
```
So both game.properties and ui.properties are pulled in.  If ui.properties  had keys matching keys in game.properties, it would overwrite them.

I hope this clears up your question.

**Comment by dhoer** [comment]
@bgrant0607 I posted _ENV files support_ to kubernetes-sig-apps.

**Comment by dhoer** [comment]
I created a script https://github.com/dhoer/k8s-env-gen to make docker env files compatible with k8s.

**Comment by bgrant0607** [comment]
cc @fraenkel

**Comment by deitch** [comment]
Been looking for this for a while, glad I stumbled across it. It looks like https://github.com/kubernetes/kubernetes/pull/36245 was set to address it. Having a hard time finding the final syntax, though. Is it:

```yml
apiVersion: v1
kind: Pod
metadata:
  name: space-simulator
spec:
  containers:
  - name: space-simulator
    image: foo/space-simulator
  - envFrom:
      configMap: game-config/game.properties
  - envFrom:
      configMap: game-config/ui.properties
 ```

Also, is there a targeted release?

**Comment by fraenkel** [comment]
The piece you are missing is https://github.com/kubernetes/kubernetes/pull/38882
If all goes well, it should be 1.6

**Comment by deitch** [comment]
@fraenkel thanks:

> The piece you are missing is #38882

Not so much. I like the idea of being able to build a ConfigMap from a `.env` file - although prefer to reference it from within a ConfigFile `.yml` rather than command line.

The big issue for me isn't _creating_ the ConfigMap data, but _referencing_ it. To have to repeat each var in a pod spec as:

```yml
        env:
        - name: VAR1
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
          value: val1
        - name: VAR2
           valueFrom:
             configMapKeyRef:
               name: special-config
               key: special.how
```

is awful for a large number of repeated vars. 

I was asking (poorly phrased), what the final API is for getting that data, something like?

```yml
        envFrom:
            configMapRef:
              name: myMap
              data: dataList
```

Or something like that (probably got the syntax wrong), so everything in the given map becomes env vars.
