### ISSUE TITLE
K8s EKS Scheduler possibly not respecting node score for nodeAffinity & nodeAnti-Affinity

### ISSUE THREAD

**Issue by martinwoods** [kubernetes/kubernetes#88112]
**What happened**:
node has the following label and taint
`Labels: lifecycle=on-demand`
`Taints: on-demand=true:PreferNoSchedule`

number of stateful apps that we'd PREFER that they run on on-demand, example stateful app could be elasticsearch where the Affinity is as:
```
client:
  tolerations:
    - key: "on-demand"
      operator: "Equal"
      value: "true"
      effect: "PreferNoSchedule"
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: lifecycle
          operator: In
          values:
          - on-demand
        - key: lifecycle
          operator: NotIn
          values:
          - ec2spot 
```
Running 6 on-demand and 6 spot in my EKS cluster

If we reduce the number of on-demand from 6 to 3, we're left with 3 on-demand and 6 spot, which is what we want

But my problem is that some of my stateful apps end up on spot, which is NOT what we want.

**What you expected to happen**:
For the scheduler to see that the node score is higher for the on-demand nodes and bind the stateful pods to those nodes based on the affinity below as per the pods yaml

```
kubectl get pod ???-???-es-elasticsearch-client-??????-????? -o yaml | grep -iA12 'affinity'
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: lifecycle
            operator: In
            values:
            - on-demand
          - key: lifecycle
            operator: NotIn
            values:
            - ec2spot
        weight: 100
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: elasticsearch
              component: client
              release: ???-???-es
          topologyKey: kubernetes.io/hostname
        weight: 1
```

**How to reproduce it (as minimally and precisely as possible)**:
Set taints in terraform config for infra deployment
Config yaml in helm deployment with affinities & tolerations
Use the AWS console to add/remove spot and ondemand nodes via ASG's 

**Anything else we need to know?**:

**Environment**: AWS EKS
- Kubernetes version (use `kubectl version`): 1.14 (This is the latest supported EKS)
- Cloud provider or hardware configuration: AWS
