### ISSUE TITLE
CronJobs should get the labels from their PodTemplateSpec like Deployments do

### ISSUE THREAD

**Issue by onlynone** [kubernetes/kubernetes#88127]
**What would you like to be added**:

`Deployments` seem to pickup the `metadata.labels` from their `PodTemplateSpec` such that if I apply the following yaml:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mything
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 20%
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
        - name: container-a
          image: something
...
```

Then I'll be able to find that deployment later by doing `kubectl get deployment -l foo=bar`. The same is not true for `CronJob`s. They don't get any labels from either their `JobTemplateSpec` nor `PodTemplateSpec`.

**Why is this needed**:

It's very convenient to have the same labels on a controller as the objects it creates. It makes specifying the objects easier and reduces duplication. I also expected this behavior on `CronJob`s when I saw that it worked for `Deployment`s.

**Comment by athenabot** [comment]
/sig apps

These SIGs are my best guesses for this issue. Please comment `/remove-sig <name>` if I am incorrect about one.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by onlynone** [comment]
It looks like this is where that happens for `Deployment`s:

https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/apis/extensions/v1beta1/defaults.go#L75

```
func SetDefaults_Deployment(obj *extensionsv1beta1.Deployment) {
	// Default labels and selector to labels from pod template spec.
	labels := obj.Spec.Template.Labels
```

Can something like that be done for `CronJob`s?

**Comment by onlynone** [comment]
@tedyu awesome. That looks like it would do the trick.

**Comment by liggitt** [comment]
Defaulting one field from another has proven extremely problematic in the past, especially when there are validation requirements between the two fields

Scenario:
1. user submits an object with no selector with labels set to `foo=bar,version=1`
2. the proposed defaulting copies the user value from labels to selector
3. validation ensures the selector overlaps with the labels
4. user updates the object to `foo=bar,version=2`
5. because the selector is already populated, no defaulting occurs
6. validation fails with an error about selector not overlapping with the labels, when the user never actually set the selector

The defaulting this issue refers to was removed in apps/v1

/close

**Comment by onlynone** [comment]
> The deployment defaulting this issue refers to was removed in apps/v1

So, can the reverse be done? Can a `CronJob` create a `Job` with a default set of labels from the `CronJob`, and same for `Job`s to `Pod`s?

**Comment by onlynone** [comment]
@liggitt I'm not sure I totally understand the issue. The scenario you describe seems to be about copying labels to matchLabels within the same object. What I was looking for was defaulting of labels between a controller object and the objects it creates. This would make it so that if a `CronJob` has label: `env=test` then the `Job`s it creates would also have the labels`env=test` (and then the `Pod`s those `Job`s create would also have `env=test`).

That way one can easily find all `CronJob`s in the test environment by running `kubectl get cronjob -l env=test`, and similarly for all other objects created downstream from the cronjob. Without something like this, one would have to specify the exact same set of labels at every level of the spec.

A definition like the following, where the cronjob and job pull up the labels from the pod:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: myjob
spec: # CronJobSpec
  schedule: 0 * * * *
  jobTemplate: # JobTemplateSpec
    spec: # JobSpec
      template: # PodTemplateSpec
        metadata:
          labels:
            env: test            # <- label specified at pod level
        spec: # PodSpec
          containers:
            - name: mycontainer
              image: myimage:1.0
```

or like this, where the cronjob pushes down its labels to the job and the job pushes its labels down to the pod:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: myjob
  labels:
    env: test                    # <- label specified at cronjob level
spec: # CronJobSpec
  schedule: 0 * * * *
  jobTemplate: # JobTemplateSpec
    spec: # JobSpec
      template: # PodTemplateSpec
        spec: # PodSpec
          containers:
            - name: mycontainer
              image: myimage:1.0
```

Would need to become this, where the labels are duplicated at every level:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: myjob
  labels:
    env: test                    # <- label specified at every level
spec: # CronJobSpec
  schedule: 0 * * * *
  jobTemplate: # JobTemplateSpec
    metadata:
      labels:
        env: test                # <- label specified at every level
    spec: # JobSpec
      template: # PodTemplateSpec
        metadata:
          labels:
            env: test            # <- label specified at every level
        spec: # PodSpec
          containers:
            - name: mycontainer
              image: myimage:1.0
```

Is that accurate? Or is there another way to get this done without so much duplication?

**Comment by liggitt** [comment]
> What I was looking for was defaulting of labels between a controller object and the objects it creates. This would make it so that if a CronJob has label: env=test then the Jobs it creates would also have the labelsenv=test (and then the Pods those Jobs create would also have env=test).

I see. Defaulting of labels of a parent object from the child object is generally seen to have been a mistake (and was removed in apps/v1). The labels on the parent/child are unrelated and so should not be defaulted at the API level.

If you simply want to avoid duplication, I've seen approaches like this:
```yaml
kind: StatefulSet
apiVersion: apps/v1
metadata:
  ...
  labels: &labels
    env: test
spec:
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    ...
  ...
```

Since the selector is immutable as of apps/v1, be careful you don't add label values that you expect to ever change in subsequent versions (e.g. version-specific labels)
