### ISSUE TITLE
Pods in `Terminating` status receive incoming requests

### ISSUE THREAD

**Issue by ilirosmanaj** [kubernetes/kubernetes#88236]
**What happened**:
I have a k8s deployment with which I am exposing a Flask application as an endpoint to the outer world.

This endpoint performs some long running tasks (sometimes up to 20 minutes). What I am trying to achieve is that during deployments, the ongoing tasks do not stop and in the meanwhile new incoming requests should be served from the new version of the deployment.

I've added the `terminationGracePeriodSeconds` property and also liveness and readiness probes to my application. I've also added `preStop` hook to the deployment, which will force liveness probe to fail - therefore load balancer to not consider my pod as `ready`.

The issue is that everytime I do a deployment, the old pod moves to status `Terminating` and readiness (0/1), but **still** keps receiving incoming requests, even though the newly deployed pod is ready and running.

**What you expected to happen**:
The pod in `Terminating` state, as mentioned in the docs, should no receive incoming requests, which should be redirected to the newly deployed pod, but just wait for terminationGracePeriodSeconds time and then get killed.

**How to reproduce it (as minimally and precisely as possible)**:

My deployment file:

```
apiVersion: v1
kind: Service
metadata:
  name: service-load-balancer
spec:
  selector:
    app: service-test
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-test
spec:
  selector:
    matchLabels:
      app: service-test
  replicas: 1
  template:
    metadata:
      labels:
        app: service-test
    spec:
      terminationGracePeriodSeconds: 309
      containers:
        - name: service-test
          image: service_test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          lifecycle:
            preStop:
              httpGet:
                path: /shutdown
                port: 5000
          readinessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health-check-426c8618f094
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
```

Whereas my Flask Service would be: 

```
STATUS_NOW = 200
@app.route("/main", methods=['POST'])
def main_endpoint():
    print('Do something')
    # start the long running thread
    return "Life is good", STATUS_NOW

@app.route("/status", methods=['GET'])
def status():
    return 'OK', 200

@app.route("/shutdown", methods=['GET'])
def shutdown():
    global STATUS_NOW = 503
    print(f'I have received a preStop request. Will sleep for {sleep_time} seconds and return 503')
    return "Received", STATUS_NOW


@app.route('/health-check-426c8618f094', methods=['GET'])
def health_check():
   return "Received liveness", STATUS_NOW


if __name__ == '__main__':
    serve(app, host='0.0.0.0', port=5000)
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration:
AWS
