### ISSUE TITLE
The restart policy is not working for deployment

### ISSUE THREAD

**Issue by 1wpro2** [kubernetes/kubernetes#88257]
**What would you like to be added**:
To honor the restart policy values, `Always, OnFailure, and Never`, as documented.
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy
  
**Why is this needed**:
There are valid use cases where a pod could run till termination. Hence the restart policy of `OnFailure and Never` which only restart if it fails, or never restart at all.

However, in current deployment, even though deployment supports this parameter, the only supported value is `Always`.

It's almost equal to not supporting this parameter at all, at the same time added confusion.

for example, this won't work
```
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: example
  name: example
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: example
    spec:
      containers:
      - image: example
      restartPolicy: OnFailure
status: {}

```

```
Error: release failed: Deployment.apps "" is invalid: spec.template.spec.restartPolicy: Unsupported value: "OnFailure": supported values: "Always"
```
