### ISSUE TITLE
One more Warning FailedGetResourceMetric horizontal-pod-autoscaler missing request for cpu

### ISSUE THREAD

**Issue by Marusyk** [kubernetes/kubernetes#88333]
**What happened**:
HPA says

> Warning  FailedComputeMetricsReplicas  40m (x12 over 42m)     horizontal-pod-autoscaler  failed to get memory utilization: missing request for memory

>   Warning  FailedGetResourceMetric       2m49s (x160 over 42m)  horizontal-pod-autoscaler  missing request for memory

**What you expected to happen**:
Working HPA
**How to reproduce it (as minimally and precisely as possible)**:
Deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manifest-job
  namespace: dev
  labels:
    service: manifest-job
spec:
  selector:
    matchLabels:
      service: manifest-job
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        service: manifest-job
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: manifest-job
        image: mycontainerregistry.azurecr.io/manifest-job:0.31.13
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 300Mi
            cpu: 200m
        env:
          - name: Namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: Logging__OutputFormat
            valueFrom:
              configMapKeyRef:
                name: commonconfigs
                key: LoggingOutputFormat
      imagePullSecrets:
        - name: regcred
```

HPA

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: manifest-job-hpa
  namespace: dev
  labels:
    service: manifest-job
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: manifest-job
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 150
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 150
```

**Anything else we need to know?**:
Also tried HPA v2beta1, no success

```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: manifest-job-hpa
  namespace: dev
  labels:
    service: manifest-job
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: manifest-job
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 150
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 120
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.8
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
