### ISSUE TITLE
need to clean up kubeadm init log

### ISSUE THREAD

**Issue by thdrnsdk** [kubernetes/kubernetes#88452]
**What would you like to be added**:
```
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[controlplane] Adding extra host path mount "enc-config" to "kube-apiserver"
[controlplane] Adding extra host path mount "audit-policy" to "kube-apiserver"
[controlplane] Adding extra host path mount "audit-log" to "kube-apiserver"
[controlplane] Adding extra host path mount "timezone" to "kube-apiserver"
[controlplane] Adding extra host path mount "timezone" to "kube-controller-manager"
[controlplane] Adding extra host path mount "timezone" to "kube-scheduler"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[controlplane] Adding extra host path mount "enc-config" to "kube-apiserver"
[controlplane] Adding extra host path mount "audit-policy" to "kube-apiserver"
[controlplane] Adding extra host path mount "audit-log" to "kube-apiserver"
[controlplane] Adding extra host path mount "timezone" to "kube-apiserver"
[controlplane] Adding extra host path mount "timezone" to "kube-controller-manager"
[controlplane] Adding extra host path mount "timezone" to "kube-scheduler"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[controlplane] Adding extra host path mount "enc-config" to "kube-apiserver"
[controlplane] Adding extra host path mount "audit-policy" to "kube-apiserver"
[controlplane] Adding extra host path mount "audit-log" to "kube-apiserver"
[controlplane] Adding extra host path mount "timezone" to "kube-apiserver"
[controlplane] Adding extra host path mount "timezone" to "kube-controller-manager"
[controlplane] Adding extra host path mount "timezone" to "kube-scheduler"
```

when using kubeadm init include config.yaml

```
xxxx
scheduler:
  extraVolumes:
  - name: "timezone"
    hostPath: "/usr/share/zoneinfo/Asia/Seoul"
    mountPath: "/etc/localtime"
controllerManager:
  extraVolumes:
  - name: "timezone"
    hostPath: "/usr/share/zoneinfo/Asia/Seoul"
    mountPath: "/etc/localtime"
apiServer:
  extraVolumes:
  - name: "enc-config"
    hostPath: "/etc/kubernetes/secrets"
    mountPath: "/etc/kubernetes/secrets"
    pathType: "DirectoryOrCreate"
  - name: "audit-policy"
    hostPath: "/etc/kubernetes/audit"
    mountPath: "/etc/kubernetes/audit"
    pathType: "DirectoryOrCreate"
    readOnly: true
  - name: "audit-log"
    hostPath: "/var/log/kubernetes"
    mountPath: "/var/log/kubernetes"
    pathType: "DirectoryOrCreate"
    readOnly: false
  - name: "timezone"
    hostPath: "/usr/share/zoneinfo/Asia/Seoul"
    mountPath: "/etc/localtime"
xxxx
```

**Why is this needed**:

the log only show extra-volumes for that control-plane?

like this

```
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[controlplane] Adding extra host path mount "enc-config" to "kube-apiserver"
[controlplane] Adding extra host path mount "audit-policy" to "kube-apiserver"
[controlplane] Adding extra host path mount "audit-log" to "kube-apiserver"
[controlplane] Adding extra host path mount "timezone" to "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[controlplane] Adding extra host path mount "timezone" to "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[controlplane] Adding extra host path mount "timezone" to "kube-scheduler"
```
