### ISSUE TITLE
Unexpected CRD Generation increments

### ISSUE THREAD

**Issue by mattmoor** [kubernetes/kubernetes#88473]
**What happened**:

I am seeing `metadata.generation` incrementing for non-Spec changes in the CRD.

**What you expected to happen**:

I expect `metadata.generation` to change for ONLY spec changes.

**How to reproduce it (as minimally and precisely as possible)**:

Steps:
1. Install the CRD
2. Install the CR
3. `watch kubectl get foo -oyaml` (note: generation is `1`)
4. Edit the CRD (e.g.  uncomment the specified line) and apply
5. Edit a non-spec field (e.g. `kubectl edit foo` and add `metadata.finalizers = ["foo"]`)

The `watch` should show the generation become `2`.

Repo CRD:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.repro.mattmoor.io
spec:
  group: repro.mattmoor.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
  - name: v1beta1
    served: true
    storage: false
  - name: v1
    served: true
    storage: false
  names:
    kind: Foo
    plural: foos
    singular: foo
    categories:
    - all
    # Uncomment me to repro
    # - sdfkljh
    shortNames:
    - f
  scope: Namespaced
  subresources:
    status: {}
```

Repro CR:
```yaml
apiVersion: repro.mattmoor.io/v1
kind: Foo
metadata:
  name: bar
spec:
  field: value
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.8", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T00:50:57Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:  GKE
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
