### ISSUE TITLE
Improve documentation on POD behavior during OOM event with child processes

### ISSUE THREAD

**Issue by DiCanio** [kubernetes/kubernetes#88522]
**What would you like to be added**:
A section within the documentation regarding a POD's behavior during an OOM event - _especially when running child-processes._

This could be added here:
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-limits-are-run

The following key points should be documented:
* resource limits of a pod are enforced using `cgroups`
* kubernetes sets these limits through the container runtime
* kubernetes does **not** track OOM kill events of child processes (only of the init-process)
-> reason: there are init-processes that can tolerate child process kills
* users have to make sure the init-process is able to recover from a child process being killed
-> otherwise the POD can become a zombie and not get restarted without kubernetes noticing (init-process is still running fine)

Claimed points can easily be validated running the following setup:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-showcase
  labels:
    app: oom-showcase
spec:
  selector:
    matchLabels:
      app: oom-showcase
  template:
    metadata:
      labels:
        app: oom-showcase
    spec:
      containers:
      - name: oom
        image: alpine:3.10.4
        command: ["/bin/sh"]
        args: ["-c", "apk add --no-cache stress-ng && stress-ng --bigheap 1"]
        resources:
          limits:
            cpu: "0.5"
            memory: "1Gi"
```

This will run `stress-ng` which in turn will spawn a child process trying to take up as much memory as possible. When exceeding the set memory limit this child process will be killed by the `oom_reaper` as seen when running `dmesg` in this POD. However, the POD itself is not failing since the init-process didn't get killed.
_In this particular case the POD does not become a zombie since stress-ng just spawns another child process if the other one gets killed. But, this kind of resilience does not necessarily hold for other applications out there._

**Why is this needed**:
There are several filed issues where people reportedly got stung by this not being documented. A selection of those issues:

* https://github.com/kubernetes/kubernetes/issues/50632
* https://github.com/kubernetes/kubernetes/issues/78973

Another benefit would be sensitizing a broader range of people to watch out for this while developing containers and/or resources being scheduled on a kubernetes cluster.
