### ISSUE TITLE
Kubectl config unset behaviour changed (setting value to null)

### ISSUE THREAD

**Issue by Raffo** [kubernetes/kubernetes#88524]
**What happened**:

In kubernetes 1.14, `kubectl config unset "users.${user}"` sets the users field in the `kubeconfig` to `[]` in case there is only one user, but in more recent versions of kubernetes it sets the value to `null`.
It's unclear to me in which version the change was made, but it can potentially break tooling that relies on this feature. For example https://github.com/aws/aws-cli/issues/4843 is exactly due to this.

It seems that the problem is in the conversion between the data structure used for the config and the marshalled yaml. In fact, AuthInfos is a map as in https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/api/types.go#L47 and not a slice. I'm not sure how this is/was marshalled before and being the source code spread between different repositories it isn't easy to find the change. 

It would be great if someone could shed some lights on when this was introduced, how to possible work around it and if it makes sense to address the issues in the related tooling or in kubectl. I wasn't sure what it makes sense to do because I wasn't able to fully understand how the marshalling works and how the map ends as a slice in the YAML file.

**What you expected to happen**:

The behaviour should be consistent between kubectl versions or a breaking change should be documented. I wasn't able to find information of a documented breaking change.

**How to reproduce it (as minimally and precisely as possible)**:

Execute 

`kubectl config unset "users.${user}"` 

 with the following `kubeconfig`:

```
apiVersion: v1
clusters:
- cluster:
    server: https://192.168.99.100:8443
  name: minikube
- cluster:
    server: https://192.168.0.1:3434
  name: my-cluster
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
- context:
    cluster: my-cluster
    user: mu-cluster
  name: my-cluster
current-context: minikube
kind: Config
preferences: {}
users:
- name: user1
  user:
    username: user1
```
