### ISSUE TITLE
Zero-disruption PDB with custom controller emits confusing status/errors

### ISSUE THREAD

**Issue by sethp-nr** [kubernetes/kubernetes#88535]
**What happened**:

We created a PDB targeting Pods managed by a custom controller that looked like this:

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb
spec:
  maxUnavailable: 0%
  selector:
    matchLabels:
      app: custom
```

The Pods matching `app=custom` don't surface an "expected" count (they're not managed by one of the well-known resources, nor does their controlling Kind expose a `scale` sub-resource). When we went to describe the PDB, however, it appeared to not have taken effect: 

```
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              0
    Total:                0
```

Additionally, there were a lot of `CalculateExpectedPodCountFailed` and `NoControllers` warnings that seemed quite dire. Finally, modifying the `minAvailable` to `100%` produced the same situation. 

**What you expected to happen**:

Per the [docs](https://kubernetes.io/docs/tasks/run-application/configure-pdb/):

> If you set maxUnavailable to 0% or 0, or you set minAvailable to 100% or the number of replicas, you are requiring zero voluntary evictions.

Of those four proposed settings, only configuring a `minAvailable` with a large number of replicas produced a status that was "normal." Especially for large stateful applications, a zero disruption PDB that simply checks for some sort of an out-of-band eviction makes a lot of sense, but feels a little like it's working by happenstance.

**How to reproduce it (as minimally and precisely as possible)**:

Create these resources:

```
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb
spec:
  maxUnavailable: 0%
  selector:
    matchLabels:
      app: custom
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: custom
spec:
  containers:
  - name: main
    image: nginx
```

And describe the PDB:

```
...
Events:
  Type     Reason                           Age                    From               Message
  ----     ------                           ----                   ----               -------
  Warning  CalculateExpectedPodCountFailed  49m (x13 over 55m)     controllermanager  Failed to calculate the number of expected pods: found no controller ref for pod "test-pod"
  Warning  NoControllerRef                  3m21s (x101 over 55m)  controllermanager  found no controller ref for pod "test-pod"
```

**Anything else we need to know?**:

At least as far as I could find, the `Allowed disruptions:  0` bit is actually honored:

```
$ k proxy &
[2] 21598
Starting to serve on 127.0.0.1:8001
$ cat >eviction.json <<EOF
{
  "apiVersion": "policy/v1beta1",
  "kind": "Eviction",
  "metadata": {
    "name": "test-pod",
    "namespace": "default"
  }
}
EOF
$ curl -v -H 'Content-type: application/json' localhost:8001/api/v1/namespaces/default/pods/test-pod/eviction -d @eviction.json
...
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Cannot evict pod as it would violate the pod's disruption budget.",
  "reason": "TooManyRequests",
  "details": {
    "causes": [
      {
        "reason": "DisruptionBudget",
        "message": "The disruption budget pdb needs 0 healthy pods and has 0 currently"
      }
    ]
  },
  "code": 429
}
```

so this issue is more about the human feedback than the operation of the machine.

What would you think of modifying the [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/disruption/disruption.go#L596-L609) to handle these edge cases and report "current" even if we can't find the total? It seems that with a min available of 100% or a maxUnavailable of 0/0%, we could simply return `len(pods)` for `desiredHealthy`, and perhaps downgrade the Event from warning to normal?
