### ISSUE TITLE
Doesn't distributed send traffic to pod when using ipvs

### ISSUE THREAD

**Issue by shufanhao** [kubernetes/kubernetes#88580]
**What happened**:
We have one vip, e.g: `test.com`, there are 8 ip behind this vip, these 8 ips are k8s node ip. When access `test.com` will forward traffic to these 8 ips with round robin. It means that 1 by 1. 
```
192.168.2.3
192.168.2.4
......
```
I have deployed 30 nginx pods. And curl vip. Request is as below, looks the number of sending to every pod request is not same. So want to know why ?
```
for i in `seq 1 400`; do curl -s test.com:12100; echo; done | sort | uniq -c
    400
     13 Hello from nginx-548b879b4d-26pfc
     12 Hello from nginx-548b879b4d-2jxbm
     19 Hello from nginx-548b879b4d-4pcnx
     12 Hello from nginx-548b879b4d-685t4
     12 Hello from nginx-548b879b4d-6rd8q
     12 Hello from nginx-548b879b4d-9mz2q
     12 Hello from nginx-548b879b4d-9w7z6
     12 Hello from nginx-548b879b4d-bpg84
     17 Hello from nginx-548b879b4d-chrhk
     12 Hello from nginx-548b879b4d-dwmdp
     12 Hello from nginx-548b879b4d-fp2k8
     12 Hello from nginx-548b879b4d-g5jrj
     12 Hello from nginx-548b879b4d-gkjj2
     12 Hello from nginx-548b879b4d-hk9xb
     12 Hello from nginx-548b879b4d-jbs9g
     12 Hello from nginx-548b879b4d-jjsr7
     12 Hello from nginx-548b879b4d-kqjv2
     12 Hello from nginx-548b879b4d-lkfwn
     12 Hello from nginx-548b879b4d-mgmhm
     18 Hello from nginx-548b879b4d-mnkph
     18 Hello from nginx-548b879b4d-nhvtp
     18 Hello from nginx-548b879b4d-nzlx8
     12 Hello from nginx-548b879b4d-r7r9w
     12 Hello from nginx-548b879b4d-s2r5w
     21 Hello from nginx-548b879b4d-smv66
     12 Hello from nginx-548b879b4d-vl9df
     12 Hello from nginx-548b879b4d-wtcrh
     12 Hello from nginx-548b879b4d-zbzgb
     12 Hello from nginx-548b879b4d-zpcbf
     12 Hello from nginx-548b879b4d-zrs4x
```

**What you expected to happen**:
The request number of sending to every pod should be same. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a vip and set 8 node ips behind of this vip.
2. Deploy nginx server:
```
 apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 30
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: strm/helloworld-http
        ports:
        - containerPort: 80
```
3. Run: for i in `seq 1 400`; do curl -s vip:12100; echo; done | sort | uniq -c

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.13
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): centos7
- Kernel (e.g. `uname -a`):4.14.35-1818.3.3.el7uek.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug): calico
- Others:
