### ISSUE TITLE
Incorrect warning message output when using apiserver extra options (authorization-mode)

### ISSUE THREAD

**Issue by thdrnsdk** [kubernetes/kubernetes#88606]
**What happened**:

when i installed k8s using kubeadm and my custom config like
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: 1.17.3
apiServer:  
  extraArgs:    
    authorization-mode: "Node,RBAC"
```

then output is

```
W0227 07:14:10.425558   16029 manifests.go:214] the default kube-apiserver authorization-mode is "Node,RBAC"; using "Node,RBAC"
```

It is a bug that the default value(Node,RBAC) is entered but a warning message is displayed.

https://github.com/kubernetes/kubernetes/blob/4e79344501bfc5d3bc48caa12c41b9246d90850d/cmd/kubeadm/app/phases/controlplane/manifests.go#L207

A function must be added to compare two string slices.

**What you expected to happen**:

If the default value and custom value are the same, no warning message should be displayed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.17.3
- Install tools:
kubeadm

/area kubeadm
/feature bug
/sig cluster-lifecycle
