### ISSUE TITLE
Container status is shown as running for SIGKILL-ed container

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#88611]
**What happened**:
Container status in the Pod status is shown as running for a SIGKILL-ed container.

**What you expected to happen**:
Pod status to properly reflect that the container is terminated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Apply the following Pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  activeDeadlineSeconds: 30
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: alpine:3.10.3
    imagePullPolicy: IfNotPresent
    name: alpine
  terminationGracePeriodSeconds: 60
```

2. Ensure that after 30s (.spec.activeDeadlineSeconds) the Pod will be with `.status.phase=Failed` and `.status.reason=DeadlineExceeded`. Ensure that the container will receive SIGTERM signal at this point of the time.

3. Ensure that after 60s (.spec.terminationGracePeriodSeconds) from point 2., SIGKILL will be sent to the container and it will be killed. Ensure that the associated docker container on the node no longer exist.

4. Ensure that the Pod status will still report the container as running. See `.status.containerStatuses[0].state`. And the associated container is killed at point 3.
```yaml
$ k get po alpine -o yaml

status:
  containerStatuses:
  - containerID: docker://358bb9e015b4555c5c543b22918ef76995368bae0ef9abb4859130cee01a5a60
    image: alpine:3.10.3
    imageID: # skipped
    lastState: {}
    name: alpine
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: "2020-02-27T10:15:16Z"
  message: Pod was active on the node longer than the specified deadline
  phase: Failed
  podIP: 100.96.1.59
  qosClass: BestEffort
  reason: DeadlineExceeded
  startTime: "2020-02-27T10:15:15Z"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ k version

Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
