### ISSUE TITLE
Wrong ownerReferences.apiversion created by using kubectl create job --from=cronjob command

### ISSUE THREAD

**Issue by d-kuro** [kubernetes/kubernetes#88645]
**What happened**:

`ownerReferences.apiVersion` of Job created by using `kubectl create job --from=cronjob` command will be `apps/v1`.
This apiVersion is wrong.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#cronjob-v1beta1-batch

```shell
$ kubectl create job --from=cronjob/test-cronjob test-job --dry-run -o yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    cronjob.kubernetes.io/instantiate: manual
  creationTimestamp: null
  name: test-job
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: test-cronjob
    uid: bb9bb1cb-695c-4eee-b6d6-1970f809e0da
...
```

**What you expected to happen**:

Set the `batch/v1beta1` to `ownerReferences.apiversion`

**How to reproduce it (as minimally and precisely as possible)**:

CronJob manifest:

<details>

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sleep
            image: alpine
            command: ["sh", "-c"]
            args:
            - |
              sleep 5
          restartPolicy: Never
```

</details>

Apply CronJob and execute command

```shell
$ kubectl create job --from=cronjob/test-cronjob test-job --dry-run -o yaml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:08:14Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
