### ISSUE TITLE
New API Resource: File (or BinaryData)

### ISSUE THREAD

**Issue by toonsevrin** [kubernetes/kubernetes#88709]
**What would you like to be added**:
A new API resource to reference files, something like:
```yaml
apiVersion: apps/v1
kind: File
metadata:
  name: promotheus-config-file
spec:
  type: http
  url: https://raw.githubusercontent.com/prometheus/prometheus/release-2.16/documentation/examples/prometheus.yml
  digest: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
Types: http, s3, git, ipfs...

Potential extensions:
* Encryption
* Optional writing to backends that allow it
* Signature and digest checking

**Why is this needed**:
1.  API resources have a limited size (1MB). This is because masters have to store this data. Sometimes, you may want to store resources (most people hit this limit with configmaps) larger than 1MB, these larger configmaps could then be backed by the file type.

2. Our kubernetes native applications (using CRDs) may want to be able to access data blobs
Example: A kubernetes CI integration service. You upload your artifacts (eg. source code) to s3, ipfs, or any of the supported File backends. You then create a File resource with a reference to this artifact. This file resource can be referenced from the CI Test resource.
