### ISSUE TITLE
Add 'display' filed to the CRD's 'spec.names' to be able advanced display capabilities  

### ISSUE THREAD

**Issue by dmvolod** [kubernetes/kubernetes#88756]
**What would you like to be added**:
It would be nice to have a advanced 'display' filed in the  CRD's 'spec.names'
**Why is this needed**:
Often, the CRD 'kind' or 'singular' names are not enough to deeply display and describe a Custom Resource Definition entity. For some reasons, developers give a very short names for CRD usability in the operator/controller code itself, but would like to display/describe it more details. This advanced field can help them at all.

I'm ready to provide a PR, if this proposal will be approved.
Thanks in advance.

**Comment by liggitt** [comment]
the description field in the top-level schema allows adding a description used by `kubectl describe <type>`:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: descriptions.mygroup.example.com
spec:
  group: mygroup.example.com
  version: v1
  scope: Namespaced
  names:
    plural: descriptions
    singular: description
    kind: Description
    listKind: DescriptionList
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      description: "I'm a description object. I describe things."
      type: object
```

```
$ kubectl explain Description
KIND:     Description
VERSION:  mygroup.example.com/v1

DESCRIPTION:
     I'm a description object. I describe things.

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata	<Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
```
```
