### ISSUE TITLE
preferredDuringSchedulingIgnoredDuringExecution Anti-Affinity rule Doesn't fully distribute pods after `kubectl uncordon <NODE>`

### ISSUE THREAD

**Issue by barucoh** [kubernetes/kubernetes#88809]
**What happened**:
I have 3 nodes on EKS across 3 different AZs in a single region, each coming for a different ASG.
I have a deployment with a single pod and 3 replicas with `podAntiAffinity` configured to prefer pods be scheduled on nodes with different zones:
```
replicas: 3
  template:
    metadata:
      labels:
        app: REDACTED
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: REDACTED-KEY
                      operator: In
                      values:
                        - REDACTED-VALUE
                topologyKey: "failure-domain.beta.kubernetes.io/zone"
```
I drained 2 nodes causing all 3 replicas to run on a single node.
I uncordoned the 2 nodes all 3 replicas kept running on the same node.

**What you expected to happen**:
Expected that Kubernetes would spread 2 replicas back to the recently uncordoned nodes to satisfy the podAntiAffinity rule.

**How to reproduce it (as minimally and precisely as possible)**:
As explained above

**Anything else we need to know?**:
I'm using Cluster-AutoScaler and a PodDisruptionBudget with `MinimumAvailable: 3` for each deployment.

Running `kubectl apply` again with a small change, solves the issue.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-1861c5", GitCommit:"1861c597586f84f1498a9f2151c78d8a6bf47814", GitTreeState:"clean", BuildDate:"2019-09-24T22:12:08Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS, `eks.8`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Install tools:
Terraform `0.12.20`
