### ISSUE TITLE
Container status showing different image from the image in spec

### ISSUE THREAD

**Issue by anshul-harness** [kubernetes/kubernetes#88835]
**What happened**:
Tried to deploy this resource with image tag **0.4.1**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
      - name: test-deployment
        image: registry.hub.docker.com/robotshop/rs-payment:0.4.1
```

However in container status I am seeing following
```
containerStatuses:
  - containerID: docker://e47532ba788942fa9d5979cfad6db7702722d6e8872352390a525c6a2610db80
    image: registry.hub.docker.com/robotshop/rs-payment:0.4.0
    imageID: docker-pullable://registry.hub.docker.com/robotshop/rs-payment@sha256:ed9bd58018712d1aa1d5d159a578cd02b408296e0609a9ffd243f5049dac012c
    lastState: {}
```

One potential reason for this is because both tags **0.4.0** and **0.4.1** are same. Refer below repository for image tags
https://hub.docker.com/r/robotshop/rs-payment/tags

**What you expected to happen**:
Expected to see version **0.4.1** in container status when deploying **0.4.1**
Is this a bug?

**How to reproduce it (as minimally and precisely as possible)**:
Deploy above yaml file.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
