### ISSUE TITLE
HPA selector not respecting matchLabels or matchExpression targeting external Metric

### ISSUE THREAD

**Issue by Alb0t** [kubernetes/kubernetes#88873]
**What happened**: Created a HPA targeting a metric with metricLabels OR/AND metricExpressions but the HPA does not respect the selectors.

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: consumers-bootstrap-hpascaler
spec:
  minReplicas: 5
  maxReplicas: 100
  metrics:
  - type: External
    external:
      metricName: saturationpct
      metricSelector:
        matchLabels:
           asdfadfds: totallyfalselabel
        matchExpressions:
          - key: asdf2rsdaf
            operator: In
            values:
            - asdfasdfsasdfa
      targetValue: 90
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
```

```
$ kubectl describe hpa
Name:                              consumers-bootstrap-hpascaler
Namespace:                         default
Labels:                            <none>
Annotations:                       <none>
CreationTimestamp:                 Thu, 05 Mar 2020 13:17:34 -0700
Reference:                         Deployment/nginx-deployment
Metrics:                           ( current / target )
  "saturationpct" (target value):  182 / 90
Min replicas:                      5
Max replicas:                      100
Deployment pods:                   100 current / 100 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from external metric saturationpct(&LabelSelector{MatchLabels:map[string]string{asdfadfds: totallyfalselabel,},MatchExpressions:[]LabelSelectorRequirement{LabelSelectorRequirement{Key:asdf2rsdaf,Operator:In,Values:[asdfasdfsasdfa],},},})
  ScalingLimited  True    TooManyReplicas   the desired replica count is more than the maximum replica count
Events:           <none>
```

```
$ kubectl get --raw /apis/external.metrics.k8s.io/v1beta1/namespaces/default/saturationpct|jq
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/saturationpct"
  },
  "items": [
    {
      "metricName": "saturationpct",
      "metricLabels": {
        "ConnectionId": "example database",
        "DatabaseName": "Example",
        "QueryName": "foo_saturation",
        "Server": "exampledb",
        "__name__": "saturationpct",
        "job": "metricexporter",
        "role": "metricexporter",
        "type": "consumer_bootstrap_foo_saturation"
      },
      "timestamp": "2020-03-05T19:45:15Z",
      "value": "90"
    },
    {
      "metricName": "saturationpct",
      "metricLabels": {
        "ConnectionId": "example database",
        "DatabaseName": "Example",
        "QueryName": "foo_saturation",
        "Server": "exampledb",
        "__name__": "saturationpct",
        "job": "metricexporter",
        "role": "metricexporter",
        "type": "consumers_foo_saturation"
      },
      "timestamp": "2020-03-05T19:45:15Z",
      "value": "92"
    }
  ]
}
```

**What you expected to happen**: If I apply a matchLabels/matchExpression that doesn't match ANYTHING it shouldn't be able to fetch a metric right? Even if giving it valid labels/key-value pairs (like type=consumers_foo_saturation), it ignores it.

**How to reproduce it (as minimally and precisely as possible)**: Have a metric in api with more than 1 series having the same name but different labels. Try to use a HPA with matchLabels/matchExpressions to scale off the label selectors.

**Anything else we need to know?**: This appears to be the behavior is v1beta1 and v1beta2.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.3
- Cloud provider or hardware configuration: Local sandbox in virtualbox
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): 4.15.0-51-generic
- Install tools: ?
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by archi13** [comment]
Having the same issue.

The case is metric series are coming from prometheus adapter with different namespaces and kafka topics.
spec looks similar:

```  metrics:
  - type: External
    external:
      metric:
        name: kafka_consumergroup_lag
        selector:
          matchLabels:
            topic: topicName
            namespace: qa
      target:
        type: AverageValue
        averageValue: 10

However filtering doesn't happen neither by topic nor namespace.

**Comment by archi13** [comment]
OK, I got it.
The HPA sends requests with the LabelSelector query param to the external API and does nothing more.
So on prometheus adapter side we need to tell how to apply the selectors.

The missing part is propagating the label matchers to the query:
```
 metricsQuery: kafka_consumergroup_lag{<<.LabelMatchers>>}
```

https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/config-walkthrough.md
https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/config.md

**Comment by Alb0t** [comment]
Wait so you got it working?

**Comment by agupta-66** [comment]
> OK, I got it. The HPA sends requests with the LabelSelector query param to the external API and does nothing more. So on prometheus adapter side we need to tell how to apply the selectors.
> 
> The missing part is propagating the label matchers to the query:
> 
> ```
>  metricsQuery: kafka_consumergroup_lag{<<.LabelMatchers>>}
> ```
> 
> https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/config-walkthrough.md https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/config.md
> 
> Besides, namespace selector is not required if we correctly associate the metric series with the namespace resource:
> 
> ```
>       resources:
>         overrides:
>           namespace: {resource: "namespace"}
> ```

@archi13 Could you share the complete working HPA code

**Comment by archi13** [comment]
@agupta-66 
In the Prometheus adapter config (values.yaml)

```
prometheus:
  url: http://prometheus-prometheus-oper-prometheus.monitoring.svc.cluster.local
  port: 9090
  path: ""

rules:
  external:
    - seriesQuery: 'kafka_consumergroup_lag'  # (1)
      resources:
        overrides:
          namespace: {resource: "namespace"}  # (2)
      name:
        matches: "kafka_consumergroup_lag"
        as: "kafka_consumergroup_lag"   # (3)
      metricsQuery: sum by (topic, namespace) (<<.Series>>{<<.LabelMatchers>>})  # (4)
```

1. this is promQL query that tells which metrics are we exporting. 
if this works the metric will appear here:
`$ kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1"`
```
{
	"kind": "APIResourceList",
	"apiVersion": "v1",
	"groupVersion": "external.metrics.k8s.io/v1beta1",
	"resources": [{
		"name": "kafka_consumergroup_lag",
		"singularName": "",
		"namespaced": true,
		"kind": "ExternalMetricValueList",
		"verbs": ["get"]
	}]
}
```
2. this will take the `namespace` from the request and match it with the `namespace` label in the metric (if such label exists)
3. here you can transform the metric name using a regex, which I don't need
4. the metricsQuery field is a Go template that gets turned into a Prometheus query, using input from a particular call to the custom metrics API
in my case:
The kafka_consumergroup_lag is the metric name, which matches <<.Series>> The topic=litigation is the label selector, which matches <<.LabelMatchers>>
`#test
kubectl get --raw /apis/external.metrics.k8s.io/v1beta1/namespaces/qa/kafka_consumergroup_lag?labelSelector=topic%3Dlitigation`

the HPA:
```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployment
  minReplicas: 1  
  maxReplicas: 2
  metrics:
  - type: External
    external:
      metric:
        name: kafka_consumergroup_lag
        selector:
          matchLabels:
            topic: litigation
            # pay attention that the topic name is case sensitive
      target:
        type: AverageValue
        averageValue: 10
```

PS:
take a look at https://keda.sh/ this might provide an easier way to implement what is needed with less boilerplate
