### ISSUE TITLE
Allow user to get node where the local volume has been provisionned

### ISSUE THREAD

**Issue by vfrans** [kubernetes/kubernetes#88900]
**What would you like to be added**:
When using local volumes like this:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: postgres-storageclass
  local:
    path: /db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2
```
in combination with storageclass like this:
```apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storageclass
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
```
I didn't find a way to actually get the worker node that was elected (and matching the matchExpressions) to provision that local volume.

At least, i didn't find a way, looking at the doc :)

**Why is this needed**:
It would be an helpful feature to allow finding the node that host that local volume.
