### ISSUE TITLE
nodeSelector doesn't seem to be working reliably on EKS

### ISSUE THREAD

**Issue by gatos-jd** [kubernetes/kubernetes#89024]
**What happened**:
I have 6 nodes in an EKS cluster.  Each node is labelled with a "layer" label.  There are two each of "label=backend", "label=frontend" and "label=perf".

I'm trying to target these nodes so that the frontend, backend and perf test pods do not compete for the same set of nodes.  However my pods do not seem to respect the nodeSelector->label targeting reliably.

I have 3 deployments/sets in the "backend":
1 - Cassandra:
```
kind: StatefulSet
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 3
...
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: cassandra
        image: gcr.io/google-samples/cassandra:v13
...
      nodeSelector:
        layer: "backend"
```

2 - Kafka:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: kafka
...
    spec:
      containers:
        image: strimzi/kafka:0.11.3-kafka-2.1.0
...
      nodeSelector:
        layer: "backend"
...
```

3 - Zookeeper:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: zookeeper
...
    spec:
      containers:
        image: strimzi/kafka:0.11.3-kafka-2.1.0
...
      nodeSelector:
        layer: "backend"
...
```

When these are launched onto the cluster, I see the following pods:
```
% kubectl get all -o wide
NAME                             READY   STATUS    RESTARTS   AGE     IP             NODE                                         NOMINATED NODE   READINESS GATES
pod/cassandra-0                  1/1     Running   0          9m32s   10.1.150.39    ip-...-27.us-west-2.compute.internal    <none>           <none>
pod/cassandra-1                  1/1     Running   0          7m56s   10.1.100.7     ip-...-252.us-west-2.compute.internal   <none>           <none>
pod/cassandra-2                  1/1     Running   0          6m46s   10.1.150.254   ip-...-27.us-west-2.compute.internal    <none>           <none>
pod/kafka-56dcd8665d-hfvz4       1/1     Running   0          9m32s   10.1.100.247   ip-...-252.us-west-2.compute.internal   <none>           <none>
pod/zookeeper-7f74f96f56-xwjjt   1/1     Running   0          9m32s   10.1.100.128   ip-...-154.us-west-2.compute.internal   <none>           <none>
```

Note - that there are at least 3 different nodes being used, which shouldn't be possible since I only have 2 each of layer=backend, layer=frontend and layer=perf.

Inspecting each of those nodes:
```
> kubectl describe node ip-...-27.us-west-2.compute.internal | grep layer
                    layer=backend
> kubectl describe node ip-...-252.us-west-2.compute.internal | grep layer
                    layer=backend
> kubectl describe node ip-...-154.us-west-2.compute.internal | grep layer
                    layer=perf
```

So for some reason the zookeeper pod got placed onto 154, which is a "perf" node, not a "backend" node.  My understanding of the nodeSelector is that shouldn't happen.  I've deleted everything (including the worker nodes) a couple of times, and it's not always zookeeper, but frequently one or more of the backend pods gets placed on a non-backend node.

As near as I can tell, all of the nodes have plenty of capacity to hold all of the pods.

**What you expected to happen**:

The backend pods are placed only on nodes with the label "layer=backend".

**How to reproduce it (as minimally and precisely as possible)**:

EKS cluster with nodes that have different labels, and several deployments that only target one of the labels with nodeSelector.  One or more of the pods escapes containment.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS / EKS, t3.medium instances used for worker nodes

- OS (e.g: `cat /etc/os-release`):
Amazon Linux

- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
