### ISSUE TITLE
document is not line up on podpreset

### ISSUE THREAD

**Issue by danielzhanghl** [kubernetes/kubernetes#89030]
**What happened**:
try to use podpreset to modify container.spec, failed with:
error: error validating "preset-ephemeral-storage.yaml": error validating data: ValidationError(PodPreset.spec): unknown field "spec" in io.k8s.api.settings.v1alpha1.PodPresetSpec; if you choose to ignore these errors, turn validation off with --validate=false

while document says:
https://kubernetes.io/docs/concepts/workloads/pods/podpreset/
Note: A Pod Preset is capable of modifying the following fields in a Pod spec when appropriate: - The .spec.containers field. - The initContainers field (requires Kubernetes version 1.14.0 or later)

example yaml to create podpreset:
```
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: add-default-ephemeral-storage
  namespace: kube-system
spec:
  selector:
  spec:
    containers:
      resources:
        limits:
          ...
        requests:
          ...
```

**What you expected to happen**:
the podpreset is created.
**How to reproduce it (as minimally and precisely as possible)**:
apply a yaml to create podpreset to modify container.spec
**Anything else we need to know?**:

checked the code, it seems podpreset did not provide capability to modify spec.containers field, need to update the document.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
