### ISSUE TITLE
Deployed image in the container status does not match with image in spec

### ISSUE THREAD

**Issue by anshul-harness** [kubernetes/kubernetes#89075]
Deployed the below yaml file.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container
  template:
    metadata:
      labels:
        app: container
    spec:
      containers:
      - name: image1
        image: nginx:1.7.9
      - name: image2
        image: index.docker.io/library/nginx:stable-alpine-perl
```
and getting below information in the container status

```
status:
  containerStatuses:
  - containerID: docker://abddbc58fc034a4d20d1b703aa2e98edbf356941b7e140a4c5a18f6530d9a947
    image: nginx:1.7.9
    imageID: docker-pullable://nginx@sha256:e3456c851a152494c3e4ff5fcc26f240206abac0c9d794affb40e0714846c451
    name: image1
  - containerID: docker://1e507cf08e56291e0b7d6d9102db5212b966570ee061283cf85d93e7793ba3cf
    image: nginx:stable-alpine-perl
    imageID: docker-pullable://nginx@sha256:0b0c7bdaa09d7fa1cf6492216469f3fbfa11f33ec8992ff0f1bc96c0db1d7566
    name: image2
```
If you compare the image field in the container status for **nginx:stable-alpine-perl**, then it is different from the spec. The prefix is getting truncated **index.docker.io/library/** . Is this expected?
If it is, then what is the rational here?

Also it does not happen always. While using below string in the spec, the container status has the same thing
**image: registry.hub.docker.com/robotshop/rs-shipping:0.2.3**

**What happened**:

**What you expected to happen**:
Expected that **image** in the container status should match with the spec.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the above yaml
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
