### ISSUE TITLE
Add subPath(Expr) under volume for dynamic volume

### ISSUE THREAD

**Issue by antoinetran** [kubernetes/kubernetes#89091]
Hi all,

When binding a volume, whether it is a hostPath or a volume with Pvc, we can express a subPathExpr under it such as (source https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath):

```
apiVersion: v1
kind: Pod
metadata:
  name: my-lamp-site
spec:
    containers:
    - name: mysql
      image: mysql
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: site-data
        subPath: mysql  # <---------------------------- Here
    volumes:
    - name: site-data
      persistentVolumeClaim:
        claimName: my-lamp-site-data
```
but we cannot write subPath under volume itself:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-lamp-site
spec:
    containers:
    - name: mysql
      image: mysql
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: site-data
    volumes:
    - name: site-data
      persistentVolumeClaim:
        claimName: my-lamp-site-data
      subPath: mysql  # <---------------------------- Here
```
**What would you like to be added**:
To add subPath or subPathExpr or hostPathExpr under volume.

**Why is this needed**:
I am deploying OpenLdap that needs data under `/var/lib/openldap`. Not under `/var/lib/openldap/[PodName]`. I use a statefulset for that. So I need a way to define dynamically a directory directly under my volume. Like this:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openldap
  serviceName: 'ldap'
  template:
    metadata:
      labels:
        app: openldap
    spec:
      volumes:
      - name: openldap
        hostPath:
          path: /space/SharedFS/dev/operationaldata/basic/ldap
          type: DirectoryOrCreate
        subPathExpr: $(POD_NAME)
      containers:
      - image: XXX/openldap
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
```
