### ISSUE TITLE
error: unexpected error when reading response body.

### ISSUE THREAD

**Issue by MarkDana** [kubernetes/kubernetes#89107]
**What happened**:
```bash
$ kubectl apply -f storage.yaml 
E0313 17:50:58.313405   29075 request.go:924] Unexpected error when reading response body: context deadline exceeded (Client.Timeout exceeded while reading body)
error: unexpected error when reading response body. Please retry. Original error: context deadline exceeded (Client.Timeout exceeded while reading body)
```

**What you expected to happen**:
get the permanent storage successfully.

**How to reproduce it (as minimally and precisely as possible)**:
I'd like to get the permanent storage on server, `storage.yaml` as:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: markvol  #use your preferred name
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
```
Then run `kubectl apply -f storage.yaml` or `kubectl create -n <myNameSpace> -f storage.yaml`, while both leading to the error. To login with `kubectl create -n <myNameSpace> -f login.yaml` also errors.

**Anything else we need to know?**:
Is it because of network delay? Namespace applied at [Nautilus](https://nautilus.optiputer.net/):

```yaml
$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://th.is.is.ip:add
  name: nautilus
contexts:
- context:
    cluster: nautilus
    namespace: default
    user: http://cilogon.org/serverA/users/xxxxxxxx
  name: nautilus
current-context: nautilus
...
```
I tried `ping https://th.is.is.ip:add` but showing ` ping: cannot resolve https://th.is.is.ip:add: Unknown host`.

**Environment**:
- Kubernetes version (use `kubectl version`): 
*After a few minutes*:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: Get https://cilogon.org/.well-known/openid-configuration: read tcp 192.168.2.101:57495->141.142.149.28:443: read: operation timed out (Client.Timeout exceeded while awaiting headers)
```
- Cloud provider or hardware configuration: [Nautilus](https://nautilus.optiputer.net/)
- OS (e.g: `cat /etc/os-release`): MacOS 10.14
- Kernel (e.g. `uname -a`): `Darwin MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`
- Install tools: `brew install kubectl`
- Network plugin and version (if this is a network-related bug):
- Others:
