### ISSUE TITLE
`kubectl rollout history` command not showing `kubectl apply` history 

### ISSUE THREAD

**Issue by w1593950** [kubernetes/kubernetes#89125]
**What happened**:

`kubectl rollout history` command not showing `kubectl apply` history 

```
➜  ☸️   kubectl rollout history deployment/myapp-deployment
+ kubectl rollout history deployment/myapp-deployment
deployment.apps/myapp-deployment
REVISION  CHANGE-CAUSE
1         kubectl create --filename=deployment-definition.yml --record=true
2         kubectl create --filename=deployment-definition.yml --record=true
3         kubectl create --filename=deployment-definition.yml --record=true
4         kubectl create --filename=deployment-definition.yml --record=true

➜  ☸️  
``` 

**What you expected to happen**:

`kubectl rollout history` command should show `kubectl apply` history along with `kubectl create` commands. 

**How to reproduce it (as minimally and precisely as possible)**:

``` 

➜  ☸️   cat deployment-definition.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 5
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: nginx:1.16.1-perl
          imagePullPolicy: Always
  selector:
    matchLabels:
      app: myapp
➜  ☸️  

Changes are made in the nginx container images: 

➜  ☸️    cat deployment-definition.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 5
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: nginx:1.16.1-alpine
          imagePullPolicy: Always
  selector:
    matchLabels:
      app: myapp
➜  ☸️  

➜  ☸️  kubectl apply -f deployment-definition.yml
deployment.apps/myapp-deployment configured
➜  ☸️  kubectl describe deployment.apps/myapp-deployment | grep -i nginx
    Image:        nginx:1.16.1-alpine
➜  ☸️  


still kubectl rollout history command is not showing kubectl apply instead, it shows kubectl create: 

➜  ☸️    kubectl rollout history deployment/myapp-deployment
deployment.apps/myapp-deployment
REVISION  CHANGE-CAUSE
1         kubectl create --filename=deployment-definition.yml --record=true
2         kubectl create --filename=deployment-definition.yml --record=true
3         kubectl create --filename=deployment-definition.yml --record=true
4         kubectl create --filename=deployment-definition.yml --record=true
5         kubectl create --filename=deployment-definition.yml --record=true

➜  ☸️  

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```

➜  ☸️  kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
➜  ☸️  

```

- Cloud provider or hardware configuration:

local macbook 

- OS (e.g: `cat /etc/os-release`):

```
vagrant@master:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
vagrant@master:~$

```

- Kernel (e.g. `uname -a`):

```
vagrant@master:~$ uname -a
Linux master 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
vagrant@master:~$
```

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
