### ISSUE TITLE
kubectl --prune fails when pruning namespace that is being removed 

### ISSUE THREAD

**Issue by skwasiborski** [kubernetes/kubernetes#89254]
**What happened**:
Using kubctl apply with --prune (and -l flag ) fails if kubernetes tries to prune namespace that is already being removed. This happens for me in CI/CD when multiple pipelines try to prune the same thing.
```
error pruning nonNamespaced object /v1, Kind=Namespace: Operation cannot be fulfilled on namespaces "prune-test-3": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
```
**What you expected to happen**:
I would expect the prune to not fail if it tries to remove namespace (or any other resource) that is already being removed. Since the resource is being removed already there is no need for additional actions on that resource.
**How to reproduce it (as minimally and precisely as possible)**:
One can reproduce the issue by creating following resources:
```
apiVersion: v1
kind: Namespace
metadata:
  name: prune-test
  labels:
    prune-label: prune
---
apiVersion: v1
kind: Pod
metadata:
  namespace: prune-test
  name: busybox1
  labels:
    prune-label: prune
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    name: busybox
```
After one needs to change the name of the namespace (e.g. to `prune-test-2`).
Now one needs to run `kubectl apply -f manifest.yaml --prune -l prune-label=prune` two times e.g. by executing following:
`kubectl apply -f manifest.yaml --prune -l prune-label=prune & kubectl apply -f manifest.yaml --prune -l prune-label=prune`.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Azure Kubernetes Service
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux pl-waw-c-skwa-1 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
