### ISSUE TITLE
CSI inline volumes should support fsGroup

### ISSUE THREAD

**Issue by lujinda** [kubernetes/kubernetes#89290]
**What happened**:
If gid is configured in Pod's securityContext.fsGroup, csi inline will panic. 

log:

E0320 16:50:59.353506   53570 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/af0fca4f-ae1b-4b5c-be91-cc1079862285-dynamic-inline\" (\"af0fca4f-ae1b-4b5c-be91-cc1079862285\")" failed. No retries permitted until 2020-03-20 16:51:31.353427479 +0800 CST m=+601646.388978014 (durationBeforeRetry 32s). Error: "recovered from panic \"runtime error: invalid memory address or nil pointer dereference\". (err=<nil>) Call stack:\ngoroutine 6290406 [running]:\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc001497e70)\n\t/home/t4/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xb5\npanic(0x3b713e0, 0x7bd2050)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\nk8s.io/kubernetes/pkg/volume/csi.(*csiMountMgr).applyFSGroup(0xc0005372c0, 0xc001a2f100, 0x4, 0xc00205ed70, 0x44, 0x0)\n\t/home/t4/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go:396 +0x64\nk8s.io/kubernetes/pkg/volume/csi.(*csiMountMgr).SetUpAt(0xc0005372c0, 0xc000b6cb80, 0x78, 0xc00205ed70, 0x0, 0x0, 0x0)\n\t/home/t4/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go:271 +0x1180\nk8s.io/kubernetes/pkg/volume/csi.(*csiMountMgr).SetUp(0xc0005372c0, 0xc00205ed70, 0x0, 0x0, 0x0)\n\t/home/t4/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go:101 +0x4d\nk8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationGenerator).GenerateMountVolumeFunc.func1(0x8, 0x453f9f8, 0xc001497e70, 0xc0025ba750)\n\t/home/t4/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go:731 +0x4a4\nk8s.io/kubernetes/pkg/volume/util/types.(*GeneratedOperations).Run(0xc0009742a0, 0x452f628, 0xc000d56480, 0xc00135a050, 0x45)\n\t/home/t4/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/util/types/types.go:51 +0xaf\nk8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run.func1(0xc000d56480, 0xc00135a050, 0x45, 0xc001106d50, 0x24, 0xc0009742a0, 0x0, 0x0, 0x0, 0x0)\n\t/home/t4/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:146 +0xcb\ncreated by k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run\n\t/home/t4/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:141 +0x378\n"

code:
```Go
func (c *csiMountMgr) applyFSGroup(fsType string, fsGroup *int64, fsGroupChangePolicy *v1.PodFSGroupChangePolicy) error {
	if fsGroup != nil {
		if fsType == "" {
			klog.V(4).Info(log("mounter.SetupAt WARNING: skipping fsGroup, fsType not provided"))
			return nil
		}

		accessModes := c.spec.PersistentVolume.Spec.AccessModes
		if c.spec.PersistentVolume.Spec.AccessModes == nil 
...
}
```
If using inline volume, **c.spec.PersistentVolume** will be nil

**What you expected to happen**:
fsGroup is successfully applied
 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dobsonj** [comment]
@smileusd ran into this bug recently on v1.18, and I don't see anything that would fix this issue on later releases either.
/reopen
/lifecycle freeze
/assign

**Comment by dobsonj** [comment]
I tested this scenario with the hostpath driver on k8s 1.24 (built from master) on a local VM using a slightly modified version of the examples/csi-app-inline.yaml spec (added fsGroup and fsType):
```
root@ubuntu2110:/workspace/csi-driver-host-path# cat examples/csi-app-inline.yaml
kind: Pod
apiVersion: v1
metadata:
  name: my-csi-app-inline
spec:
  securityContext:
    fsGroup: 1000
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.hostpath.csi/node
            operator: Exists
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      csi:
        driver: hostpath.csi.k8s.io
        fsType: ext4
```
And this does not panic kubelet
```
# grep -i fsgroup /tmp/kubelet.log | tail -1 
I0310 16:49:10.101569 1812079 csi_mounter.go:408] kubernetes.io/csi: mounter.SetupAt Warning: skipping fsGroup permission change, no access mode available. The volume may only be accessible to root users.
```
It does not panic because of this check:
https://github.com/kubernetes/kubernetes/blob/e9af39914797d40766b166e18dac3a441a2bf5d4/pkg/volume/csi/csi_mounter.go#L407-L409
Which was added in https://github.com/kubernetes/kubernetes/pull/102653
However, I do believe we can and should support fsgroup for CSI inline volumes.
Instead of checking the PV spec (which is not set for inline volumes) we could pass the `accessMode` directly into `supportsFSGroup`, which will be RWO for inline volumes.
https://github.com/kubernetes/kubernetes/blob/e9af39914797d40766b166e18dac3a441a2bf5d4/pkg/volume/csi/csi_mounter.go#L122
