### ISSUE TITLE
apiserver accepts podsepc with duplicate keys

### ISSUE THREAD

**Issue by UdayVishwakarma** [kubernetes/kubernetes#89303]
**What happened**:
Kubernetes accepts deployments with duplicate keys within pod spec

deployment.yaml
```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          name: nginx2
          image: nginx:1.14.2
          image: nginx
          ports:
          - containerPort: 80

```

I have name and image keys twice and apiserver simply accepts the last key. when I do `kubectl get deploy nginx-deployment -o yaml` I see `spec.template.spec.containers[0].image=nginx`

**What you expected to happen**:

apiserver/kubectl should through an error stating there are duplicate keys in pod spec

**How to reproduce it (as minimally and precisely as possible)**:

try to deploy the above given `deployment.yaml`

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: docker desktop
- OS (e.g: `cat /etc/os-release`): MacOS
- Kernel (e.g. `uname -a`): Darwin <name> 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
- Install tools: docker desktop
