### ISSUE TITLE
--force and --prune interactions accidentally prune newly created deployments

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#89322]
**What happened**:

```
$ kubectl apply -f /tmp/repro1.yaml -lapp=alpine
deployment.apps/alpine created
$ kubectl apply -f /tmp/repro2.yml -lapp=alpine --prune --force
deployment.apps/alpine configured
deployment.apps/alpine pruned
```

Results in:
* alpine being created
* alpine deployment force replaced with the new one.  The old pod gets killed, and a new one comes up
* Immediately after, the *newly created* deployment is pruned

**What you expected to happen**:

Newly created deployment is not pruned

**How to reproduce it (as minimally and precisely as possible)**:

Use commands above with:

first yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
        foo: bar
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: alpine
        args:
        - sleep
        - "10000000000000000"
        image: alpine
```

second yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  selector:
    matchLabels:
      app: alpine
      foo: bar
  template:
    metadata:
      labels:
        app: alpine
        foo: bar
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: alpine
        args:
        - sleep
        - "100"
        image: alpine
```

The important part of this yaml is that matchLabels, and immutable field, changed.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.22", GitCommit:"9bae7fcacb520dfee658b26cc1a9643bf787dfc3", GitTreeState:"clean", BuildDate:"2020-02-27T18:43:37Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
