### ISSUE TITLE
Configmap does not have the right owner

### ISSUE THREAD

**Issue by felixPG** [kubernetes/kubernetes#89429]
**What happened**:

I have my statefulset with a security context configured:

```
      securityContext:
        runAsUser: 998
        fsGroup: 998
```
So the volumes have to be mounted and the owner should be this user too, but this is wrong:
My volume:

```
        volumeMounts:
        - name: my-conf
          mountPath: /opt/my.conf
          subPath: my.conf
```
Instead this file has owned by root instead of the user with id 998

**What you expected to happen**:

The file has the right owner instead of root

**How to reproduce it (as minimally and precisely as possible)**:

In my case I create an statefulset with security context defined. I specify a configmap to mount as file inside my containers. Is all
