### ISSUE TITLE
Daemonset doesn't properly respect nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubernetes#89476]
**What happened**:

I create `DaemonSet` in the Kubernetes v1.17.2 cluster, i use `NodeAffinity` make pods only running on the node that have specified labels, but it not work. I get the pod information and the affinity have been override.

**What you expected to happen**:

`DaemonSet` node affinity works.

**How to reproduce it (as minimally and precisely as possible)**:

1. write a `DaemonSet`
2. add node affinity like below:
```yaml
affinity:
    nodeAffinity: 
        requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms: 
        - matchExpressions: 
            - key: app
            operator: In
            values: 
            - fluent
```
3. kubectl get pod -oyaml. The pod affinity become:

```yaml
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchFields:
      - key: metadata.name
        operator: In
        values:
        - worker1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

`v1.17.2`

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wawa0210** [comment]
Can you provide the entire contents of your daemonset yaml? I just tested it and nodeAffinity works

**Comment by pytimer** [comment]
I run my daemonset in other cluster, it works. I check the cluster that went wrong, i found a mutate admission webhook add `matchExpressions` in pod `NodeAffinity`, it maybe make nodeAffinity not work and have too many terminating pod in this namespace. I am not sure this problem because of admission webhook.

**Comment by geokb** [comment]
@dims I just experienced this behavior myself, it happens only with daemonsets where the `MatchExpressions` list inside `RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms[]` is overridden with:
```yaml
- matchFields:
          - key: metadata.name
            operator: In
            values:
            - <NODE_NAME>
```

I am not really sure whether I am missing something or node affinity does not work correctly with daemonsets.
