### ISSUE TITLE
Custom deployment spec does not merge VolumeMounts for InitContainers

### ISSUE THREAD

**Issue by tyates-indeed** [kubernetes/kubernetes#89599]
**What happened**:
I created a custom deployment spec for a hello-world function that mounts `emptyDir` to `/tmp` for both `containers` and `initContainers`:

```
---
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: hello-world-python
spec:
  runtime: python3.6
  timeout: "180"
  handler: helloget.foo
  deps: ""
  checksum: sha256:d251999dcbfdeccec385606fd0aec385b214cfc74ede8b6c9e47af71728f6e9a
  function-content-type: text
  function: |
    def foo(event, context):
        return "hello world"
  deployment:
    spec:
      template:
        spec:
          containers:
            - volumeMounts:
                - mountPath: /tmp
                  name: tmpdir1
          initContainers:
            - volumeMounts:
                - mountPath: /tmp
                  name: tmpdir2
          volumes:
            - name: tmpdir1
              emptyDir: {}
            - name: tmpdir2
              emptyDir: {}
```

**What you expected to happen**:
I expect the created function to have the volume mounts correctly merged with my custom deployment spec. The merge works correctly for `containers` but does NOT work for `initContainers`. When I fetch the YAML for the pod that is created I see `tmpdir1` mounted for the `hello-world-python` container, but `tmpdir2` is NOT mounted for the `prepare` init container.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the YAML file posted above and check the YAML of the pod that Kubeless creates. Look at the `volumeMounts` section of the `prepare` init container. You should see that `tmpdir2` is not listed in the mounts even though it is specified in the YAML above.

**Environment**:
Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud provider or hardware configuration:
Tested on both OpenStack and AWS.

OS (e.g: `cat /etc/os-release`):
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
```
