### ISSUE TITLE
How has the apiserver pod run without any apiserver?

### ISSUE THREAD

**Issue by Piknik1990** [kubernetes/kubernetes#89690]
Hello, everybody!

I have been being a non-programing question. When anybody initialize a master-node in a kubernetes-cluster, they are see a generating of apiserver manifest then this pod running.

```
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[apiclient] All control plane components are healthy after 16.002347 seconds
```

Who does apiserver pods starting via manifest (with API) if apiservice is down and a 6643 port is not listened?

The manifest file has the "apiVersion" parameter and apiserver must be up.
```
# cat /etc/kubernetes/manifests/kube-apiserver.yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
...
```
