### ISSUE TITLE
Utilization disapear when setting HPA cpu AverageValue and Utilization both

### ISSUE THREAD

**Issue by zzzkl** [kubernetes/kubernetes#89770]
**What happened**:
when setting cpu AverageValue and Utilization both, the Utilization will disapear. yaml like:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: monitor
spec:
  scaleTargetRef:
    kind: Deployment
    name: php-apache
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: '60'
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
```
i get only:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: monitor
spec:
  scaleTargetRef:
    kind: Deployment
    name: php-apache
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: '60'
```

**What you expected to happen**:
want to get both type.
**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f hpa.yaml
**Anything else we need to know?**:
metric-server: v0.3.6
**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): centos
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
