### ISSUE TITLE
unexpected podIP and hostIP in pod

### ISSUE THREAD

**Issue by mars1024** [kubernetes/kubernetes#89816]
**What happened**:

Unexpected podIP and hostIP in pod, just like
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  ......
status:
  ......
  hostIP: <nil>
  podIP: <nil>
  ......
```

**What you expected to happen**:

This is a host-networking pod, podIP and hostIP in status should be node's internal IP.

**How to reproduce it (as minimally and precisely as possible)**:

Set kubelet's cloud provider to `external`, then set some invalid addresses to node.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.14
