### ISSUE TITLE
Recreated StatefulSet pod stuck in pending state after deleting pvc and pod.

### ISSUE THREAD

**Issue by santhoshs123** [kubernetes/kubernetes#89910]
**What happened**:
1. Created a StatefulSet with 2 replicas and 2 VolumeClaimTemplates.
2. After pods are in Running state, issue command to delete 2 PVCs attached to a pod. PVCs went to Terminating state.
3. Delete the corresponding pod. Both pod and PVCs got deleted.
4. StatefulSet recreated the pod. Pod went into Pending state and stuck there for more than an hour with following events:

```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  33m                default-scheduler  persistentvolumeclaim "nginx-logs-nginx-deployment-1" is being deleted
  Warning  FailedScheduling  4s (x26 over 33m)  default-scheduler  persistentvolumeclaim "nginx-logs-nginx-deployment-1" not found
```

**What you expected to happen**:
I was expecting it to recreate missing PVCs and bring up pod successfully.

If I delete the pod stuck in Pending state, it behaves as expected, ie., it recreates PVCs and brings up pod.
```
Events:
  Type     Reason                  Age                From                                                   Message
  ----     ------                  ----               ----                                                   -------
  Warning  FailedScheduling        30s (x5 over 47s)  default-scheduler                                      pod has unbound immediate PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled               25s                default-scheduler                                      Successfully assigned demo-app-imdt/nginx-deployment-1 to ip-192-168-182-94.us-west-2.compute.internal
  Normal   SuccessfulAttachVolume  24s                attachdetach-controller                                AttachVolume.Attach succeeded for volume "pvc-3220bb3e-783f-11ea-aacd-0a6926f364ba"
  Normal   SuccessfulAttachVolume  23s                attachdetach-controller                                AttachVolume.Attach succeeded for volume "pvc-322219a2-783f-11ea-aacd-0a6926f364ba"
  Normal   Pulled                  8s                 kubelet, ip-192-168-182-94.us-west-2.compute.internal  Container image "nginx:1.7.9" already present on machine
  Normal   Created                 7s                 kubelet, ip-192-168-182-94.us-west-2.compute.internal  Created container nginx
  Normal   Started                 7s                 kubelet, ip-192-168-182-94.us-west-2.compute.internal  Started container nginx
```

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nginx-deployment
  namespace: demo-app-imdt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx
            topologyKey: kubernetes.io/hostname
      containers:
      - image: nginx:1.7.9
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
          - mountPath: "/var/log/nginx1"
            name: nginx-logs1
            readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: nginx-logs
    spec:
      storageClassName: fast
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
  - metadata:
      name: nginx-logs1
    spec:
      storageClassName: fast
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
```

```
$ kc get storageclass fast -o yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"fast"},"parameters":{"type":"gp2"},"provisioner":"kubernetes.io/aws-ebs","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
  creationTimestamp: "2020-03-24T20:16:45Z"
  name: fast
  resourceVersion: "13757"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/fast
  uid: 62769dae-6e0c-11ea-aacd-0a6926f364ba
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Initial setup after creating StatefulSet:
```
$ kc -n demo-app-imdt get pods
NAME                 READY   STATUS    RESTARTS   AGE
nginx-deployment-0   1/1     Running   0          62s
nginx-deployment-1   1/1     Running   0          28s


$ kc -n demo-app-imdt get pvc
NAME                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nginx-logs                       Bound    pvc-d32c9d88-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           68s
nginx-logs-nginx-deployment-0    Bound    pvc-d363f273-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           67s
nginx-logs-nginx-deployment-1    Bound    pvc-e78b5806-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           33s
nginx-logs1                      Bound    pvc-d349c930-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           67s
nginx-logs1-nginx-deployment-0   Bound    pvc-d364767c-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           67s
nginx-logs1-nginx-deployment-1   Bound    pvc-e78c52dc-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           33s
```

Delete 2 PVCs attached to pod nginx-deployment-1:
```
$ kc -n demo-app-imdt delete pvc nginx-logs-nginx-deployment-1 nginx-logs1-nginx-deployment-1 
persistentvolumeclaim "nginx-logs-nginx-deployment-1" deleted
persistentvolumeclaim "nginx-logs1-nginx-deployment-1" deleted


$ kc -n demo-app-imdt get pvc
NAME                             STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nginx-logs                       Bound         pvc-d32c9d88-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           88s
nginx-logs-nginx-deployment-0    Bound         pvc-d363f273-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           87s
nginx-logs-nginx-deployment-1    Terminating   pvc-e78b5806-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           53s
nginx-logs1                      Bound         pvc-d349c930-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           87s
nginx-logs1-nginx-deployment-0   Bound         pvc-d364767c-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           87s
nginx-logs1-nginx-deployment-1   Terminating   pvc-e78c52dc-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           53s
```

Delete pod nginx-deployment-1:
```
$ kc -n demo-app-imdt delete pod nginx-deployment-1
pod "nginx-deployment-1" deleted

$ kc -n demo-app-imdt get pods
NAME                 READY   STATUS        RESTARTS   AGE
nginx-deployment-0   1/1     Running       0          2m2s
nginx-deployment-1   0/1     Terminating   0          88s
```

Pod is stuck in Pending state with PVC not found events:
```
$ kc -n demo-app-imdt get pods
NAME                 READY   STATUS    RESTARTS   AGE
nginx-deployment-0   1/1     Running   0          33m
nginx-deployment-1   0/1     Pending   0          31m


$ kc -n demo-app-imdt describe pod nginx-deployment-1
...
...
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  31m                default-scheduler  persistentvolumeclaim "nginx-logs-nginx-deployment-1" is being deleted
  Warning  FailedScheduling  1s (x25 over 31m)  default-scheduler  persistentvolumeclaim "nginx-logs-nginx-deployment-1" not found
```

Delete the pod stuck in Pending state, pod gets recreated along with the PVCs:
```
$ kc -n demo-app-imdt get pods
NAME                 READY   STATUS    RESTARTS   AGE
nginx-deployment-0   1/1     Running   0          81m
nginx-deployment-1   0/1     Pending   0          79m


$ kc -n demo-app-imdt delete pod nginx-deployment-1
pod "nginx-deployment-1" deleted


$ kc -n demo-app-imdt get pods
NAME                 READY   STATUS    RESTARTS   AGE
nginx-deployment-0   1/1     Running   0          81m
nginx-deployment-1   0/1     Pending   0          2s


$ kc -n demo-app-imdt get pvc
NAME                             STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nginx-logs                       Bound     pvc-d32c9d88-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           81m
nginx-logs-nginx-deployment-0    Bound     pvc-d363f273-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           81m
nginx-logs-nginx-deployment-1    Pending                                                                        fast           5s
nginx-logs1                      Bound     pvc-d349c930-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           81m
nginx-logs1-nginx-deployment-0   Bound     pvc-d364767c-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           81m
nginx-logs1-nginx-deployment-1   Pending                                                                        fast           5s
Events:


$ kc -n demo-app-imdt get pvc
NAME                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nginx-logs                       Bound    pvc-d32c9d88-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           81m
nginx-logs-nginx-deployment-0    Bound    pvc-d363f273-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           81m
nginx-logs-nginx-deployment-1    Bound    pvc-3220bb3e-783f-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           27s
nginx-logs1                      Bound    pvc-d349c930-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           81m
nginx-logs1-nginx-deployment-0   Bound    pvc-d364767c-7833-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           81m
nginx-logs1-nginx-deployment-1   Bound    pvc-322219a2-783f-11ea-aacd-0a6926f364ba   1Gi        RWO            fast           27s


$ kc -n demo-app-imdt get pods
NAME                 READY   STATUS              RESTARTS   AGE
nginx-deployment-0   1/1     Running             0          81m
nginx-deployment-1   0/1     ContainerCreating   0          35s


$ kc -n demo-app-imdt get pods
NAME                 READY   STATUS    RESTARTS   AGE
nginx-deployment-0   1/1     Running   0          82m
nginx-deployment-1   1/1     Running   0          54s

```

**Anything else we need to know?**:

cluster-info dump uploaded to - https://gist.github.com/santhoshs123/5edcb0d70bc007dee7eec328a832b683

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: v1.16.2
Server Version: v1.14.9-eks-502bfb

- Cloud provider or hardware configuration: AWS(EKS cluster)
- OS (e.g: `cat /etc/os-release`): Mac OS
- Kernel (e.g. `uname -a`): Darwin Kernel Version 16.7.0
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
