### ISSUE TITLE
Add feature with dynamically created devices device-cgroup-rule in kubernetes pods

### ISSUE THREAD

**Issue by lysliu** [kubernetes/kubernetes#89939]
**What would you like to be added**:
We want to mount many `volumes` in a pod yaml file like 
```
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: dev-vhost-net
        hostPath:
          path: /dev/vhost-net
      - name: dev-kvm
        hostPath:
          path: /dev/kvm
      - name: dev-vsock
        hostPath:
          path: /dev/vsock
      - name: dev-vhost-vsock
        hostPath:
          path: /dev/vhost-vsock
``` 
Which is a map of docker run command as following:
```
docker run \
    --device-cgroup-rule="c ${major}:* rwm" \
    --cap-add sys_admin \
    --cap-add net_admin \
    --cap-add sys_chroot \
    --cap-add sys_nice \
    --device /dev/vhost-net \
    --device /dev/kvm \
    --device /dev/vsock \
    --device /dev/vhost-vsock \
``` 
This is supported in docker from [here](https://docs.docker.com/engine/reference/commandline/create/#dealing-with-dynamically-created-devices---device-cgroup-rule) by [PR](https://github.com/containers/libpod/pull/5152) Devices available to a container are assigned at creation time. The assigned devices will both be added to the cgroup.allow file and created into the container once it is run. This poses a problem when a new device needs to be added to running container.

**Why is this needed**:
To add a more permissive rule to a container allowing it access to a wider range of devices. For example, supposing our container needs access to a character device with major 42 and any number of minor number (added as new devices appear), the following rule would be added:
```
docker create --device-cgroup-rule='c 42:* rmw' -name my-container my-image
```
Then, a user could ask udev to execute a script that would `docker exec my-container mknod newDevX c 42 <minor>` the required device when it is added.
