### ISSUE TITLE
Incorrect /etc/resolv.conf file inside pod in kubernetes

### ISSUE THREAD

**Issue by reoxey** [kubernetes/kubernetes#89956]
Hi, I have a DNS issue with Kubernetes in GCP.
```
Release channel -> Regular channel
Master version	-> 1.15.9-gke.24
```
The issue is that the` /etc/resolv.conf` file is incorrectly written in some pods.
Pod 1
```
nameserver 169.254.169.254
search us-east1-b.c.xrtb-273005.internal c.xrtb-273005.internal google.internal
```
instead of Pod2:
```
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local us-east1-b.c.xrtb-273005.internal c.xrtb-273005.internal google.internal
options ndots:5
```
Is it a bug? Or am I doing something wrong? This used to never happen before. Could it be this version of K8s?

Here's YAML which caused the issue.

```
# ## redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb 
  labels:
    app: redispod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redispod

  template:
    metadata:
      labels:
        app: redispod
    spec:
      containers:
      - name: redispod
        image: redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379

---
# services

apiVersion: v1
kind: Service
metadata:
  name: redisnova

spec:
  selector:
    app: redispod

  ports:
    - name: redisport
      port: 6379

  type: ClusterIP
```

**Comment by windniw** [comment]
@reoxey Could you show pod1's yaml? It look like Pod1 working in hostNetwork while Pod2 not

**Comment by neolit123** [comment]
/remove-kind bug
/triage support

please, change to bug if confirmed.

**Comment by reoxey** [comment]
@windniw

**Comment by reoxey** [comment]
The issue first occurred to following 2 deployments. But, above `dummy` pod seems to be working fine.
```

##
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app 
  labels:
    app: podgo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podgo

  template:
    metadata:
      labels:
        app: podgo
    spec:
      containers:
      - name: podgo
        image: user/project
        ports:
        - containerPort: 8000
      initContainers:
      - name: install
        image: busybox
        command: ['sh', '-c', 'mkdir -p /work/assets/db; wget -O /work/one.zip "http://domain/db/one.zip"; unzip /work/one.zip -d /work/assets/db']
        volumeMounts:
        - name: workdir
          mountPath: "/work"
      dnsPolicy: Default
      volumes:
      - name: workdir
        emptyDir: {}
      imagePullSecrets:
      - name: nova-secret

---
# ## redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb 
  labels:
    app: redispod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redispod

  template:
    metadata:
      labels:
        app: redispod
    spec:
      containers:
      - name: redispod
        image: redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379

---
# services

apiVersion: v1
kind: Service
metadata:
  name: podgo

spec:
  selector:
    app: podgo

  ports:
    - name: tcp
      port: 80
      targetPort: 8000

  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: redisnova

spec:
  selector:
    app: redispod

  ports:
    - name: redisport
      port: 6379

  type: ClusterIP

```
