### ISSUE TITLE
static-pod cannot be normally registered in the cluster after setting the limitrange

### ISSUE THREAD

**Issue by wawa0210** [kubernetes/kubernetes#90009]
**What happened**:

I configured a static-pod, the example is as follows(At this time, no limitrange rules are set under the default namespaces)

```
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
```
At this time, the static-pod can start normally and successfully registered to the apiserver

Later, limitrange was set under this namespace, and at the same time I modified the resource quota of static-pod，the statid-poc yaml as follows:

```
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 900m
          memory: 1000Mi
```

limitrange yaml as follows :

```
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
      cpu: 128m
      memory: "268435456"
    defaultRequest:
      cpu: 64m
      memory: "268435456"
    maxLimitRequestRatio:
      cpu: "4"
      memory: "1"
    type: Container
```

Because the static-pod resource quota does not meet the limitrange regulations, the static-pod container can be successfully started on the host, but it is intercepted by the admission and cannot be registered in the apiserver。

```
[root@10-7-106-200 manifests]# kubectl get pod
No resources found in default namespace.
[root@10-7-106-200 manifests]# docker ps | grep static-web
ff8ad3acc7d3        nginx                                         "nginx -g 'daemon of…"   8 seconds ago       Up 7 seconds                            k8s_web_static-web-10-7-106-200_default_a8f09782e793c294e7620a05347e4364_0
98c4204afd34        10.7.106.151/kube-system/kube-pause:3.1   "/pause"                 20 seconds ago      Up 19 seconds                           k8s_POD_static-web-10-7-106-200_default_a8f09782e793c294e7620a05347e4364_0
```

The error is as follows:

```
Apr  9 23:34:28 10-7-106-200 kubelet: E0409 23:34:28.326167   72941 kubelet.go:1663] Failed creating a mirror pod for "static-web-10-7-106-200_default(a8f09782e793c294e7620a05347e4364)": pods "static-web-10-7-106-200" is forbidden: [cpu max limit to request ratio per Container is 4, but provided ratio is 9.000000, memory max limit to request ratio per Container is 1, but provided ratio is 10.000000]
```

**What you expected to happen**:

static-pod can be registered to apiserver normally, which is regarded as a mirror-pod.Ignore limitrange rules

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Because many of the system's basic components (apiserver, scheduler, controllermanager) are currently deployed through static-pod, the cluster work after successful deployment. However, if you set limitrange later, it is likely that these basic components will not work properly.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
