### ISSUE TITLE
Wildcard unable to be converted in new ingress objects 

### ISSUE THREAD

**Issue by rikatz** [kubernetes/kubernetes#90005]
**What happened**: Kubernetes 1.18 now supports wildcards into hosts specs. But when using a simple yaml example it raises a json conversion error.

Converting the yaml to json by hand and applying the json works fine

**How to reproduce it (as minimally and precisely as possible)**:

* Create a simple ingress yaml file and then apply it:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - host: *.example.com
    http:
      paths:
      - path: /example
        pathType: Prefix
        backend:
          serviceName: example-service
          servicePort: 80
```

```
kubectl  apply -v 3 -f ingress-1.yaml 
F0409 09:13:46.659695   13849 helpers.go:115] error: error parsing ingress-1.yaml: error converting YAML to JSON: yaml: line 7: did not find expected alphabetic or numeric character
```

Now convert it to json and apply it:
```json
{
    "apiVersion": "extensions/v1beta1",
    "kind": "Ingress",
    "metadata": {
        "name": "example-ingress",
        "namespace": "default"
    },
    "spec": {
        "rules": [
            {
                "host": "*.example.com",
                "http": {
                    "paths": [
                        {
                            "backend": {
                                "serviceName": "example-service",
                                "servicePort": 80
                            },
                            "path": "/example",
                            "pathType": "Prefix"
                        }
                    ]
                }
            }
        ]
    }
}

```
```
kubectl  create -f ingress1.json 
ingress.extensions/example-ingress created
kubectl  get ingress example-ingress
NAME                CLASS    HOSTS           ADDRESS   PORTS   AGE
example-ingress   <none>   *.example.com             80      46s
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T20:56:08Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g: `cat /etc/os-release`): Ubuntu 19.10
- Kernel (e.g. `uname -a`): Linux cartman 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Binary download
- Network plugin and version (if this is a network-related bug): N/A
