### ISSUE TITLE
No matches for kind "Ingress" in version "networking.k8s.io/v1"

### ISSUE THREAD

**Issue by vitalybibikov** [kubernetes/kubernetes#90077]
I want to upgrade my cluster version from 1.15.10 to 1.16.7. 
Prior to that I'm trying to update all the APIs.

Release notes to 1.16.0 state:
The following APIs are no longer served by default:
* All resources under `apps/v1beta1` and `apps/v1beta2` - use `apps/v1` instead
* `daemonsets`, `deployments`, `replicasets` resources under `extensions/v1beta1` - use `apps/v1` instead
* `networkpolicies` resources under ***`extensions/v1beta1` - use `networking.k8s.io/v1` instead***
* `podsecuritypolicies` resources under `extensions/v1beta1` - use `policy/v1beta1` instead

Release notes to 1.18.0 state:
The following deprecated APIs can no longer be served.

**What happened**:
When I change apiVersion in my Ingress from 
`apiVersion: networking.k8s.io/v1beta1`
to
 `apiVersion: networking.k8s.io/v1`

I get:
no matches for kind "Ingress" in version "networking.k8s.io/v1"

**What you expected to happen**:

Actually, I'm a bit of confused, 
as currently **kind: Ingress** can only be served under v1beta1.

A PR https://github.com/kubernetes/kubernetes/pull/88509 states, that some changes had to be done, before graduation of the Ingress to v1.

_So, the question is:_
For now, I guess I should use  --runtime-config apiserver flag to re-enable apis, but later?

How can I upgrade my cluster, if in 1.18.* v1beta1 is already deprecated, while kind:ingress is moved to v1 only in 1.19 (or later)?

Provider: Azure
Cluster Version: 1.15.10
Kubectl version:  "v1.16.8". (tried on 1.15.5 and "v1.18.1") as well
OS: Windows 10 Pro, 1909 (18363.720)

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by liggitt** [comment]
Ingress is not yet available under `networking.k8s.io/v1`, the release note is for NetworkPolicy objects

**Comment by zafercavdar** [comment]
According to [Kubernetes docs](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/), ingress is available at `networking.k8s.io/v1beta1`

**Comment by BorntraegerMarc** [comment]
I'm a bit confused. Doesn't [this official site](https://kubernetes.io/docs/concepts/services-networking/ingress/) say that we should use `networking.k8s.io/v1`?

**Comment by liggitt** [comment]
networking.k8s.io/v1 is availble in Kubernetes v1.19+

**Comment by ryanberger-az** [comment]
networking.k8s.io/v1beta1 == 1.14 to 1.18

networking.k8s.io/v1 = 1.19+

**Comment by yanhuibin315** [comment]
I got the same error . And this is my k8s version:
```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

When I usr apiVersion: networking.k8s.io/v1
I got the error message:
```
error: unable to recognize ".\\dashboard-ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1"
```

And then I change my apiVersion to "networking.k8s.io/v1beta",
I got the error message like that
```
error: error validating ".\\dashboard-ingress.yaml": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend; if you choose to ignore these errors, turn validation off with --validate=false
```

Is that my format wrong？？

**Comment by yanhuibin315** [comment]
> I got the same error . And this is my k8s version:
> 
> ```
> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> When I usr apiVersion: networking.k8s.io/v1
> I got the error message:
> 
> ```
> error: unable to recognize ".\\dashboard-ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1"
> ```
> 
> And then I change my apiVersion to "networking.k8s.io/v1beta",
> I got the error message like that
> 
> ```
> error: error validating ".\\dashboard-ingress.yaml": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend; if you choose to ignore these errors, turn validation off with --validate=false
> ```
> 
> Is that my format wrong？？

my-ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1beta
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kube-dashboard
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /dashboard
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 8080
```

**Comment by fongrx7** [comment]
> > I got the same error . And this is my k8s version:
> > ```
> > Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
> > ```
> > 
> > 
> > When I usr apiVersion: networking.k8s.io/v1
> > I got the error message:
> > ```
> > error: unable to recognize ".\\dashboard-ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1"
> > ```
> > 
> > 
> > And then I change my apiVersion to "networking.k8s.io/v1beta",
> > I got the error message like that
> > ```
> > error: error validating ".\\dashboard-ingress.yaml": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "service" in io.k8s.api.networking.v1beta1.IngressBackend; if you choose to ignore these errors, turn validation off with --validate=false
> > ```
> > 
> > 
> > Is that my format wrong？？
> 
> my-ingress.yaml
> 
> ```yaml
> apiVersion: networking.k8s.io/v1beta
> kind: Ingress
> metadata:
>   name: dashboard-ingress
>   namespace: kube-dashboard
>   annotations:
>     nginx.ingress.kubernetes.io/rewrite-target: /$1
> spec:
>   rules:
>     - http:
>         paths:
>           - path: /dashboard
>             pathType: Prefix
>             backend:
>               service:
>                 name: kubernetes-dashboard
>                 port:
>                   number: 8080
> ```

I have the same problem with 1.18, haven't found a solution yet

**Comment by dem4gus** [comment]
@yanhuibin315  @fongrx7 the correct api version should be `networking.k8s.io/apps/v1beta1`. It appears your yaml is missing the final `1`.

**Comment by seadoherty** [comment]
@fongrx7 sounds like we're in a similar spot.
Was able to get a little further but still wasn't 100% so if it helps...
Getting Version: 1.0.0 on http://172.17.0.3:31995/
Getting Version: 2.0.0 on posts.com/v2 (post.com is in etc/hosts as 172.17.0.3)
Was able to get there by creating a separate Service file

web-serv.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: web-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 8080
      targetPort: 8080
```

example-ingress.yaml:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: posts.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: web-srv
              servicePort: 8080
          - path: /v2
            pathType: Prefix
            backend:
              serviceName: web2
              servicePort: 8080
```
