### ISSUE TITLE
vSphere (CSI) plugin  :Failed to get shared datastores in kubernetes cluster 

### ISSUE THREAD

**Issue by bvivi57** [kubernetes/kubernetes#90130]
/sig cloud-provider
/sig storage

Hi

We are trying to deploy a kubernetes cluster under vSphere with the CSI and CPI plugin.

The test environment is :

- 1 vCenter: v6.7.0 14792544
- 1 ESXi: v6.7.0 14320388
- 2 datastore: (no vSAN)

- Kubernetes: v1.18.1
- 3 master kubernetes
- 1 worker kubernetes 
-  Ubuntu 19.10

Here is the configuration file for the implementation of the cluster and kubeadm

```
apiServer:
  extraArgs:
    cloud-provider: external
    endpoint-reconciler-type: lease
  certSANs:
  - 192.168.10.45
  - kube.coolcorp.priv
apiVersion: kubeadm.k8s.io/v1beta2
controlPlaneEndpoint: kube.coolcorp.priv
controllerManager:
  extraArgs:
    cloud-provider: external
kind: ClusterConfiguration
kubernetesVersion: 1.18.0
networking:
  podSubnet: 10.244.0.0/16`
```

Everything seems functional

```
NAME                                     READY   STATUS    RESTARTS   AGE
coredns-66bff467f8-cs58n                 1/1     Running   0          39m
coredns-66bff467f8-j9s97                 1/1     Running   0          39m
etcd-k8s-master-001                      1/1     Running   0          39m
etcd-k8s-master-002                      1/1     Running   0          39m
etcd-k8s-master-003                      1/1     Running   0          37m
kube-apiserver-k8s-master-001            1/1     Running   0          39m
kube-apiserver-k8s-master-002            1/1     Running   0          39m
kube-apiserver-k8s-master-003            1/1     Running   0          37m
kube-controller-manager-k8s-master-001   1/1     Running   1          39m
kube-controller-manager-k8s-master-002   1/1     Running   0          39m
kube-controller-manager-k8s-master-003   1/1     Running   0          37m
kube-flannel-ds-amd64-crl67              1/1     Running   0          37m
kube-flannel-ds-amd64-nxk6l              1/1     Running   0          37m
kube-flannel-ds-amd64-qk27h              1/1     Running   0          37m
kube-flannel-ds-amd64-rfr84              1/1     Running   0          37m
kube-proxy-bsq6l                         1/1     Running   0          39m
kube-proxy-cpmsb                         1/1     Running   0          38m
kube-proxy-lcwc8                         1/1     Running   0          38m
kube-proxy-qkkmr                         1/1     Running   0          39m
kube-scheduler-k8s-master-001            1/1     Running   1          39m
kube-scheduler-k8s-master-002            1/1     Running   0          39m
kube-scheduler-k8s-master-003            1/1     Running   0          37m
vsphere-cloud-controller-manager-445r2   1/1     Running   0          23m
vsphere-cloud-controller-manager-97d58   1/1     Running   0          23m
vsphere-cloud-controller-manager-rvtpk   1/1     Running   0          23m
vsphere-csi-controller-0                 5/5     Running   0          23m
vsphere-csi-node-p7lgn                   3/3     Running   0          23m
```

We've been trying to provision a volume

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere-dts-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  #storagepolicyname: "VMW_K8S_SSD"
  datastoreurl: ds:///vmfs/volumes/49c9734e-84c4ea9d/
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-psvc-vsphere-nfs
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
  storageClassName: vsphere-dts-nfs
```
 
But we encounter the following errors

_kubectl describe persistentvolumeclaim k8s-psvc-vsphere-nfs_

```
Events:
  Type     Reason                Age               From                                                                                  Message
  ----     ------                ----              ----                                                                                  -------
  Normal   Provisioning          9s (x5 over 24s)  csi.vsphere.vmware.com_vsphere-csi-controller-0_02c24ea2-7e1d-11ea-8e55-ced63ab4b01a  External provisioner is provisioning volume for claim "default/k8s-psvc-vsphere-nfs"
  Warning  ProvisioningFailed    9s (x5 over 24s)  csi.vsphere.vmware.com_vsphere-csi-controller-0_02c24ea2-7e1d-11ea-8e55-ced63ab4b01a  failed to provision volume with StorageClass "vsphere-dts-nfs": rpc error: code = Internal desc = Failed to get shared datastores in kubernetes cluster. Error: Empty List of Node VMs returned from nodeManager
  Normal   ExternalProvisioning  0s (x4 over 24s)  persistentvolume-controller                                                           waiting for a volume to be created, either by external provisioner "csi.vsphere.vmware.com" or manually created by system administrato
```

_kubectl logs vsphere-csi-controller-0 csi-provisioner --namespace=kube-system_

```
W0414 07:25:58.684961       1 topology.go:331] No topology keys found on any node
I0414 07:25:58.701543       1 controller.go:979] Final error received, removing PVC 3eea8c61-5e16-48f5-bf12-a063fba439fa from claims in progress
W0414 07:25:58.701674       1 controller.go:886] Retrying syncing claim "3eea8c61-5e16-48f5-bf12-a063fba439fa", failure 13
E0414 07:25:58.701732       1 controller.go:908] error syncing claim "3eea8c61-5e16-48f5-bf12-a063fba439fa": failed to provision volume with StorageClass "vsphere-dts-nfs": rpc error: code = Internal desc = Failed to get shared datastores in kubernetes cluster. Error: Empty List of Node VMs returned from nodeManager
I0414 07:25:58.701909       1 event.go:209] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"k8s-psvc-vsphere-nfs", UID:"3eea8c61-5e16-48f5-bf12-a063fba439fa", APIVersion:"v1", ResourceVersion:"4079", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "vsphere-dts-nfs": rpc error: code = Internal desc = Failed to get shared datastores in kubernetes cluster. Error: Empty List of Node VMs returned from nodeManager
```

The communication with the vCenter seems to be operational.

_kubectl.exe logs vsphere-csi-controller-0 vsphere-syncer --namespace=kube-system_

```
I0414 06:56:05.136883       1 virtualcentermanager.go:63] Initializing defaultVirtualCenterManager...
I0414 06:56:05.136952       1 virtualcentermanager.go:65] Successfully initialized defaultVirtualCenterManager
I0414 06:56:05.137502       1 virtualcentermanager.go:107] Successfully registered VC "vcenter.coolcorp.priv"
I0414 06:56:05.254999       1 kubernetes.go:56] k8s client using in-cluster config
I0414 06:56:05.256770       1 metadatasyncer.go:60] FullSync: fullSync interval is set to 30 minutes
I0414 06:56:05.261274       1 metadatasyncer.go:159] Initialized metadata syncer
I0414 07:26:05.257018       1 metadatasyncer.go:124] fullSync is triggered
I0414 07:26:05.257230       1 fullsync.go:38] FullSync: start
I0414 07:26:05.261449       1 manager.go:62] Initializing volume.volumeManager...
I0414 07:26:05.261654       1 manager.go:66] volume.volumeManager initialized
W0414 07:26:05.273144       1 virtualcenter.go:255] Creating a new client session as the existing session isn't valid or not authenticated
I0414 07:26:05.504542       1 fullsync.go:97] FullSync: end
```

Thank you for your help

**Comment by bvivi57** [comment]
Hi, I review my configuration and I use this configuration for init my cluster

```
---
apiServer:
  extraArgs:
    cloud-provider: external
    endpoint-reconciler-type: lease
  certSANs:
  - 192.168.10.45
  - kube.coolcorp.priv
apiVersion: kubeadm.k8s.io/v1beta2
controlPlaneEndpoint: kube.coolcorp.priv
controllerManager:
  extraArgs:
    cloud-provider: external
kind: ClusterConfiguration
kubernetesVersion: 1.18.0
networking:
  podSubnet: 10.244.0.0/16
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
bootstrapTokens:
       - groups:
         - system:bootstrappers:kubeadm:default-node-token
         token: y7yaev.9dvwxx6ny4ef8vlq
         ttl: 0s
         usages:
         - signing
         - authentication
nodeRegistration:
  kubeletExtraArgs:

It' OK now
```

**Comment by 0dragosh** [comment]
@bvivi57 What was the problem and how did you fix this exactly?

I'm having the same issue and I'm stuck.

**Comment by bvivi57** [comment]
Sorry, I don't know exactly what the origine of my problem was. I simply recreated my cluster using a new configuration file with kubeadm.

This is the latest version of my file.

```
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: y7yaev.9dvwxx6ny4ef8vlq
  ttl: 0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  kubeletExtraArgs:
    cloud-provider: external
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  certSANs:
  - 192.168.10.45
  - kube.coolcorp.priv
  extraArgs:
    cloud-provider: external
    endpoint-reconciler-type: lease
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: kube.coolcorp.priv:6443
controllerManager:
  extraArgs:
    cloud-provider: external
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: 1.18.2
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}

```
