### ISSUE TITLE
Anti-affinity prevents pod restart with PodDisruptionBudget

### ISSUE THREAD

**Issue by kleimkuhler** [kubernetes/kubernetes#90151]
**What happened**:

An nginx deployment exists with three replicas on a three node cluster. An
anti-affinity policy exists that requires each nginx pod to be on its own
node. A PodDisruptionBudget exists that permits `MinAvailable: 1` for `app:
nginx` label.

After an edit to the nginx deployment's pod template that should trigger a
restart, a new pod initializes but is unable to be assigned a node. This is
due to the fact that none of the existing nginx pods terminate, opening up
their node for the new one.

**What you expected to happen**:

I expected the PDB to allow the pods to restart on a three node cluster since
up to two pods are allowed to terminate. If the pods were to restart, they
would open their node for the new ones being scheduled.

I expected this because the docs on Voluntary and Involuntary disruptions
state that updating a deployment's pod template is a voluntary disruption.

**How to reproduce it (as minimally and precisely as possible)**:

nginx-deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    foo: bar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx
              topologyKey: kubernetes.io/hostname
      containers:
        - name: nginx
          image: nginx:1.16.1
          ports:
            - containerPort: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
    name: nginx-pdb
    labels:
        app: nginx
spec:
    minAvailable: 1
    selector:
        matchLabels:
            app: nginx
```

Create deployment:

```
❯ kubectl apply -f nginx-deployment.yaml
deployment.apps/nginx-deployment created
poddisruptionbudget.policy/nginx-pdb created
```

```
❯ kubectl get pods
NAME                                READY   STATUS    RESTARTS   AGE
nginx-deployment-7f8f5bfd69-76zv6   1/1     Running   0          6s
nginx-deployment-7f8f5bfd69-jhffq   1/1     Running   0          6s
nginx-deployment-7f8f5bfd69-vndtn   1/1     Running   0          6s
```

Edit deployment:

```
❯ cat nginx-deployment.yaml | sed 's/containerPort: 80/containerPort: 81/' | kubectl apply -f -
deployment.apps/nginx-deployment configured
poddisruptionbudget.policy/nginx-pdb unchanged
```

```
❯ kubectl get pods
NAME                                READY   STATUS    RESTARTS   AGE
nginx-deployment-7f8f5bfd69-76zv6   1/1     Running   0          3m17s
nginx-deployment-7f8f5bfd69-jhffq   1/1     Running   0          3m17s
nginx-deployment-7f8f5bfd69-vndtn   1/1     Running   0          3m17s
nginx-deployment-844597d46-2sp56    0/1     Pending   0          30s
```

`pod/nginx-deployment-844597d46-2sp56` stays suck in pending due to: `0/3 nodes are available: 3 node(s) didn't match pod affinity/anti-affinity, 3 node(s) didn't satisfy existing pods anti-affinity rules.`

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.8-gke.8 
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): Container-Optimized OS
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
