### ISSUE TITLE
Pod deletion is very slow

### ISSUE THREAD

**Issue by lalithsuresh** [kubernetes/kubernetes#90195]
**What happened**:
I have a 500 node K8s cluster created using "kubeadm init". The master and worker kubelets are all configured with defaults. I create a single deployment with a large number of pods (~10K), and try to the delete the deployment. The deletes go through at a slow rate of roughly 10 per second.

**What you expected to happen**:
The deletes would go through a lot faster than 10 per second.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the following deployment.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  selector:
    matchLabels:
      app: store
  replicas: 10000
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: store
    spec:
      terminationGracePeriodSeconds: 0
      schedulerName: default-scheduler
      containers:
        - name: xyz
          image: k8s.gcr.io/pause
```

2. kubectl delete deployment cache

3. Observe rate of deletions using `kubectl get pods | wc -l`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:

Master node has 8 CPUs and 32 GB RAM. Workers have 2 CPUs and 2GB RAM (I'm not running any workload in the pods, this is just a setup to study scheduler behavior)

- OS (e.g: `cat /etc/os-release`):

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Kernel (e.g. `uname -a`):

```
Linux ip-172-31-34-97 4.15.0-1057-aws #59-Ubuntu SMP Wed Dec 4 10:02:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
```kubeadm init --pod-network-cidr=10.244.0.0/16```

- Network plugin and version (if this is a network-related bug):

This doesn't look networking related, but I'm using Flannel.

- Others:
