### ISSUE TITLE
Webhook with FailurePolicy: Ignore that applies to controller manager leases breaks clusters

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#90217]
**What happened**:

Create a webhook with:
- `FailurePolicy: Ignore`
- match rule that matches all CREATE and UPDATE operation
- a service that times out

```
  ...
  failurePolicy: Ignore
  ...
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
    scope: '*'
```

The `timeout` field will default `10s` for `v1` admission webhooks (1.16+) and `30s` for pre-GA webhooks (https://github.com/kubernetes/kubernetes/pull/79549).

Register the webhook in a cluster with controller-manager configured with the default lease settings.

The controller-manager will attempt to renew its lease with a request like:

```
PUT /api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s
```

The request times out, the cluster-manager losses its lease, and the cluster becomes degraded.

**What you expected to happen**:

Safe defaults so that `FailurePolicy: Ignore` on a webhook doesn't result in a degraded cluster if the webhook service times out seems needed.

More clarity for webhook authors in documentation also? Eg. providing guidance on how to configure `FailurePolicy: Ignore` for non-critical webhooks to prevent a webhook service failure from resulting in the cluster becoming degraded, incl. guidance on setting timeout.

xref: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy, https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/admissionregistration/v1/types.go

/sig api-machinery
/area extensibility
/cc @roycaihw @liggitt
