### ISSUE TITLE
Ingress with working regular expression fails validation

### ISSUE THREAD

**Issue by dhrp** [kubernetes/kubernetes#90210]
**What happened**:
My (valid) regular expression is being refused.
`The Ingress "myingress" is invalid: spec.rules[0].http.paths[1].path: Invalid value: "/go(?:/|$)(.*)": must be a valid regex`

Specifically, I'm trying to (?:re), a non-capturing group. But I've found other regular expressions, such as a lookahead or lookbehind to show similar behavior.

Here is an example ingress spec, which includes the annotations
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: netbox
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: myhost.customers.greenedge.cloud
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: netbox-nginx
              servicePort: http
          - path: /go(?:/|$)(.*)
            backend:
              serviceName: netbox-extras
              servicePort: http
```

**What you expected to happen**:
I expect the regular expression to be accepted.

**How to reproduce it (as minimally and precisely as possible)**:
Create an ingress following the example above, and notice it will be rejected.

**Anything else we need to know?**:

If you look at [this issue](https://github.com/kubernetes/ingress-nginx/issues/4989), you'd expect that the regular expression is blocked by the ingress validator because it's not in the [re2 spec](https://github.com/google/re2/wiki/Syntax). But it is actually ... You can test it here: https://regex-golang.appspot.com/assets/html/index.html

I also filed the issue for ingress-nginx https://github.com/kubernetes/ingress-nginx/issues/5377, but it should be solved here. 

The validation is here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/validation/validation.go#L382

If the consensus is that this is an issue, and needs fixing, I'm willing to pick it up and contribute.

**Environment**:
- Tried on v1.15.9-gke.24 and kubernetes 17.2

/sig network
