### ISSUE TITLE
ReadinessProbe slowly marks the pod unready

### ISSUE THREAD

**Issue by kiuka** [kubernetes/kubernetes#90238]
**What happened**:
Created a deployment with 2 nginx replicas, which has intense rediness probe. The probe when the pod is running is working well, I can see the requests in the log.

When I kill one of the nodes which has one of the pods I expect the service will route the traffic shortly (after the readinessprobe fails) to one node, but it takes way more longer than it should (concrete numbers below).

**What you expected to happen**:
Stop routing to the dead pod after the readinessprobe fails.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: v1
kind: Service
metadata:
  name: rp-svc
  labels:
    app: rp-test
spec:
  selector:
    app: rp-test
  ports:
  - name: http
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rp-test
  labels:
    app: rp-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rp-test
  template:
    metadata:
      labels:
        app: rp-test
    spec:
      tolerations:
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 30
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 30

      initContainers:
        - name: update-index-html
          image: busybox
          command: ["sh", "-c", "hostname > /webroot/index.html"]
          volumeMounts:
            - name: webroot
              mountPath: "/webroot"

      containers:
        - name: rp-test
          image: nginx

          ports:
            - containerPort: 80
              name: http

          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 2
            successThreshold: 3
            failureThreshold: 2

          volumeMounts:
            - name: webroot
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: webroot
          emptyDir: {}
```

Start it, then kill a node which as one of the pods. 

I expect to become unready after failureTreshold * periodSeconds * timeoutSeconds

But instead its more than 30 seconds:
```
while :; do date; curl "http://10.233.30.139/" -sSf --connect-timeout 1 --max-time 1 || echo "failed"; sleep 1; done
```
```
Fri Apr 17 07:58:29 EDT 2020
rp-test-6cfd945bc6-xwhqr
Fri Apr 17 07:58:30 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:58:31 EDT 2020
curl: (28) Connection timed out after 1003 milliseconds
failed
Fri Apr 17 07:58:33 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:58:34 EDT 2020
curl: (28) Connection timed out after 1001 milliseconds
failed
Fri Apr 17 07:58:36 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:58:37 EDT 2020
curl: (28) Connection timed out after 1001 milliseconds
failed
Fri Apr 17 07:58:39 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:58:40 EDT 2020
curl: (28) Connection timed out after 1001 milliseconds
failed
Fri Apr 17 07:58:42 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:58:43 EDT 2020
curl: (28) Connection timed out after 1001 milliseconds
failed
Fri Apr 17 07:58:45 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:58:46 EDT 2020
curl: (28) Connection timed out after 1001 milliseconds
failed
Fri Apr 17 07:58:48 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:58:49 EDT 2020
curl: (28) Connection timed out after 1000 milliseconds
failed
Fri Apr 17 07:58:51 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:58:52 EDT 2020
curl: (28) Connection timed out after 1001 milliseconds
failed
Fri Apr 17 07:58:54 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:58:55 EDT 2020
curl: (28) Connection timed out after 1001 milliseconds
failed
Fri Apr 17 07:58:57 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:58:58 EDT 2020
curl: (28) Connection timed out after 1001 milliseconds
failed
Fri Apr 17 07:59:00 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:59:01 EDT 2020
curl: (28) Connection timed out after 1002 milliseconds
failed
Fri Apr 17 07:59:03 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:59:04 EDT 2020
curl: (28) Connection timed out after 1001 milliseconds
failed
Fri Apr 17 07:59:06 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:59:07 EDT 2020
rp-test-6cfd945bc6-n4pfs
Fri Apr 17 07:59:08 EDT 2020
rp-test-6cfd945bc6-n4pfs
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Bare metal
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux master1 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
kubespray
- Network plugin and version (if this is a network-related bug):
- Others:
