### ISSUE TITLE
csr generation not working as per doc

### ISSUE THREAD

**Issue by gopukrishnantec** [kubernetes/kubernetes#90240]
Refer: https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#create-a-certificate-signing-request-object-to-send-to-the-kubernetes-api

Doc says :
```
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: hari
spec:
  request: $(cat akshay.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
```
master $ kubectl create -f hari.yaml
Error from server (BadRequest): error when creating "hari.yaml": CertificateSigningRequest in version "v1beta1" cannot be handled as a CertificateSigningRequest: v1beta1.CertificateSigningRequest.Spec: v1beta1.CertificateSigningRequestSpec.Usages: []v1beta1.KeyUsage: Request: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|-d '\\n')","usages":|..., bigger context ...|equest":"$(cat akshay.csr | base64 | tr -d '\\n')","usages":["digital signature","key encipherment",|...
master $

```
[upgrade/versions] Cluster version: v1.16.0
[upgrade/versions] kubeadm version: v1.16.0
I0417 12:20:15.864584   11815 version.go:251] remote version is much newer: v1.18.2; falling back to: stable-1.16
[upgrade/versions] Latest stable version: v1.16.9
[upgrade/versions] Latest version in the v1.16 series: v1.16.9

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT       AVAILABLE
Kubelet     2 x v1.16.0   v1.16.9

Upgrade to the latest version in the v1.16 series:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.16.0   v1.16.9
Controller Manager   v1.16.0   v1.16.9
Scheduler            v1.16.0   v1.16.9
Kube Proxy           v1.16.0   v1.16.9
CoreDNS              1.6.2     1.6.2
Etcd                 3.3.15    3.3.15-0

```
If remove the csr file and replacing it with the value of the base64| tr -d '\n' it works!

master $ cat hari.yaml
```
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: hari
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXk1U1Y2TjFUNDl1RW9TM3VjUkNQUW9nMXZwUmVzMzFxNVhWMk9HUzVqUCszCnREcWd6b3NFVTFsOFljN3NtNkd6NitONnlDRTRzQ1JSVmJxN2ZLVFVIWmNEQjZpVXYxbmdLUjIzNTZzbFI1OVIKc09Fdno0aTJUczl3TGRMQzBteUlpQUhnRm9kbjhxcUZYNHdjUXg4T3hFWE5zSWxrMlNBdS9RNHNmbjRYaTlCKwpLTlo2aDZQbWVKZlQvRGpocTBaWVNEb0JjVnJia2xiWDFTaTJSRytHNitqOGxrY0lxZnJrSGM1Z1lUWUQzRVFBCllGM1hYeEVpeGluaU42TmtlSGIyMVNSbnNTaGxkYlRyblcycTV4bnJTRFpmeDV3SGVlUVo2a0swT2s1Wjh4Y20KV200eXpPTnFMcDNrdXFna0dDenFtMlN1bXpMaHgzQmpJdWNSc0J2enFRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQ1oxdDFwSEI2RHRBUys0Z0psWXc1cjgyTlF1NEx5OVdhN2NGK3A0NXZQQWcyalB0NEx3CjE4L3ZaNS9qTjhMeDZxTEtMQmY1Q3QvL2VjbUV1Y0sySFp0NHc1Ukp5Q3lYSk9LWTY4akgwVGxqTUFzSmpVaVYKY0dYTzA2cTlRK3JCZXlOakxwNWNMb3ExRHpGbDlnZG53N0lhaGpXWnBlRG5STEJPcWpyR2hmQi9ORVcvRFJ3aQpYOWtEcXN0WXRQK0RxRi9Fc3lQRVFtK21oMVFKRnNNYlRmamxsM0dtY0s3M3ZFenJ0eEFYSHkyN0VXQmwrOStvCm1QMExIQUNZeXRmcXhxR2FxOEkwVkgxTlB2Nnkrbm9QeTFOSksyQ0JZV0syZVJQdFJDS2JIWnRYYU1KWUlBYkkKNjNvZ3V5WEsydjJUcE40KzVCeGt1M1dxRVNwY3lUYnZqMEE9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
```
master $ kubectl create -f hari.yaml
certificatesigningrequest.certificates.k8s.io/hari created

**Comment by liggitt** [comment]
Note that the doc is a shell command that generates the file with an embedded base-64 encoded request:

```yaml
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: my-svc.my-namespace
spec:
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
```

That is equivalent to:

```
cat <<EOF > file.yaml
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: my-svc.my-namespace
spec:
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF

kubectl apply -f file.yaml
```
