### ISSUE TITLE
hostpath : MountVolume.SetUp failed for volume "test-volume" : hostPath type check failed: /data is not a directory

### ISSUE THREAD

**Issue by JCzz** [kubernetes/kubernetes#90263]
Adding hostpath example pod [example](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath):

Error in "Events":
`MountVolume.SetUp failed for volume "test-volume" : hostPath type check failed: /data is not a directory`

/sig storage
Update(side question): I dont know how to add a label for SIG?

Pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory

```

```
 kubectl version 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-10T21:53:51Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.3", GitCommit:"71631703d37fb1b4b333abd427deae839aeb2032", GitTreeState:"clean", BuildDate:"2020-03-24T18:54:48Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by wawa0210** [comment]
Can you confirm whether the '/ data' directory exists on the host? When the type is `Directory`, if the directory does not exist on the host, kubelet will not create it for us, it will print error

**Comment by JCzz** [comment]
Thanks

Not sure how to verify if `/data` directory exists on a pod that is not running?

I tried with `DirectoryOrCreate`, then it hangs in `ContainerCreating`

**Comment by wawa0210** [comment]
`/ data` is the directory on the host, not in the pod. When the type is `DirectoryOrCreate`, you can go to check the detailed log of kubelet, there should be related error information

**Comment by JCzz** [comment]
Right :-) I knew that..

I am running on GKE, and kubelet is not available.

I can not find mounted information with `kubectl describe nodes / <NodeName>`

DO you know how?

**Comment by wawa0210** [comment]
Sorry, I do n’t know much about gke

**Comment by srinicrick65** [comment]
Hi Guys I am facing this same issue . I am using the below . For directory i can use DirectoryOrCreate but what about type Socket?
k3d version v4.4.0
k3s version v1.20.4-k3s1 (default)
kubectl version : 1.2.0
helm : 3.0.2 (Using helm for deploying the pod)

Please find my deployment.yaml file

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-agent
  namespace: edge-system
  labels:
    moduleId: edge-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      moduleId: edge-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        moduleId: edge-agent
    spec:
      containers:
      - image: ability.azurecr.io/edge/agent:pocfeature_rebasemaster
        securityContext:
          privileged: true
          runAsUser: 0
        name: edge-agent
        imagePullPolicy: Always
        env:
        - name: DPS_PROVISIONING_HOST
          value: global.azure-devices-provisioning.net
        - name: DPS_ID_SCOPE
          value: 0ne00091CC4
        - name: DEVICE_ID
          value: 8fcb0635-9cc2-4f95-8914-0301668be636
        - name: CERT_FILE
          value: "/var/ability/certs/edgedevice-cert.pem"
        - name: KEY_FILE
          value: "/var/ability/certs/edgedevice-key.pem"
        - name: EDGE_TYPE
          value: "ability.device.edge.shpatil@1"
        - name: EDGEPROXYIMAGE
          value: "ability.azurecr.io/edge/proxy:2.4.12"
        - name: EDGEMQTTIMAGE
          value: "ability.azurecr.io/edge/broker:1.5.8"
        - name: MODULES_VOLUME
          value: "/var/ability/modules"
        - name: MQTT_VOLUME
          value: "/var/ability/mosquitto"
        - name: files_directory
          value: "/var/ability/modules"
        - name: ACL_ALLOWED_SERVER_NAMES
          value: "^.+\\.core\\.windows\\.net$ ^.+\\.azure-devices.net$ ^global\\.azure-devices-provisioning\\.net$"
        - name: SYS_TRAIL_AGGREGATOR_CA_PEM
          value: /etc/rsyslog-ca.pem
        - name: SYS_TRAIL_AGGREGATOR_HOST
          value: ability-edge-development-sys-log-dummy-certificate
        - name: SYS_TRAIL_AGGREGATOR_PORT
          value: "6514"
        - name: BLOCK_INCOMING_CONTACT_ON_IFACE
          value: dum8
        - name: LAYER2_CONNECTIVITY_GATEWAY_IP
          value: "203.0.113.1"
        - name: LAYER2_CONNECTIVITY_SUBNET_CIDR
          value: 203.0.113.0/24
        - name: LAYER2_CONNECTIVITY_CONTAINERS_CIDR
          value: 203.0.113.2/32
        - name: CONTAINER_BRIDGE_IP_CIDR
          value: 172.17.0.1/16
        - name: LAN_ACCESS_NAT_CIDR
          value: 172.19.0.0/16
        - name: INTERNET_ACCESS_NAT_CIDR
          value: 172.20.0.0/16
        - name: EDGENETWORK_EXT
          value: iot-internet
        - name: EDGENETWORK_INT
          value: iot-lan
        - name: EDGENETWORK_MACVLAN
          value: iot-layer2
        - name: LOGGER_LEVEL
          value: silly
        - name: SSL_ENGINE
          value: /var/ability/modules/libSecStoreEngine.so
        - name: DEV_QA_CERT_CHOICE
          value: CommonDevQAPlatform
        - name: HOST_RPC_SERVER_PATH
          value: /var/ability/rpc/socket


        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: cert-volume
          mountPath: /var/ability/certs
        - name: module-volume
          mountPath: /var/ability/modules
        - name: socket-volume
          mountPath: /var/ability/rpc
        - name: mqtt-secret-volume
          mountPath: /var/run/secrets/mqtt/edge-agent
        - name: edge-privatekey
          mountPath: /var/run/secrets/pem/edge-agent-private-key
        - name: edge-publickey
          mountPath: /var/run/secrets/pem/edge-agent-public-key
        - name: mqtt-volume
          mountPath: /var/ability/mosquitto
        - name: mqtt-auth-volume
          mountPath: /var/ability/mqtt_auth


      volumes:
      - name: cert-volume
        hostPath:
          path: /var/ability/certs
          type: Directory
      - name: module-volume
        hostPath:
          path: /var/ability/modules
          type: Directory
      - name: socket-volume
        hostPath:
          path: /var/ability/rpc/socket
          type: Socket
      - name: mqtt-secret-volume
        hostPath:
          path: /var/run/secrets/mqtt/edge-agent
          type: DirectoryOrCreate
      - name: edge-privatekey
        hostPath:
          path: /var/run/secrets/pem/edge-agent-private-key
          type: DirectoryOrCreate
      - name: edge-publickey
        hostPath:
          path: /var/run/secrets/pem/edge-agent-public-key
          type: DirectoryOrCreate
      - name: mqtt-volume
        hostPath:
          path: /var/ability/mosquitto
          type: DirectoryOrCreate
      - name: mqtt-auth-volume
        hostPath:
          path: /var/ability/mqtt_auth
          type: DirectoryOrCreate


      imagePullSecrets:
      - name: abilitycr
```


root@srini-Virtual-Machine:~/Documents/helmcharts-edge/helmcharts-edge# kubectl get events -n edge-system --sort-by='{.lastTimestamp}'
LAST SEEN   TYPE      REASON              OBJECT                            MESSAGE
5m33s       Normal    Scheduled           pod/edge-agent-d8d7f6fb9-lh5k9    Successfully assigned edge-system/edge-agent-d8d7f6fb9-lh5k9 to k3d-k3sedgecluster-server-0
5m34s       Normal    ScalingReplicaSet   deployment/edge-agent             Scaled up replica set edge-agent-d8d7f6fb9 to 1
5m34s       Normal    SuccessfulCreate    replicaset/edge-agent-d8d7f6fb9   Created pod: edge-agent-d8d7f6fb9-lh5k9
4m30s       Warning   FailedMount         pod/edge-agent-d8d7f6fb9-lh5k9    MountVolume.SetUp failed for volume "socket-volume" : hostPath type check failed: /var/ability/rpc/socket is not a socket file
4m30s       Warning   FailedMount         pod/edge-agent-d8d7f6fb9-lh5k9    MountVolume.SetUp failed for volume "module-volume" : hostPath type check failed: /var/ability/modules is not a directory
3m31s       Warning   FailedMount         pod/edge-agent-d8d7f6fb9-lh5k9    Unable to attach or mount volumes: unmounted volumes=[cert-volume module-volume socket-volume], unattached volumes=[mqtt-auth-volume cert-volume edge-privatekey edge-publickey mqtt-volume module-volume socket-volume mqtt-secret-volume default-token-2g7kn]: timed out waiting for the condition
