### ISSUE TITLE
kubelet restarts Init Сontainers when App Containers are running.

### ISSUE THREAD

**Issue by vlad-vinogradov** [kubernetes/kubernetes#90271]
**What happened**:

After creating a Pod, successfully finished Init Containers are not removed from the system and kept in "Exited" state. If we manualy remove finished init container, kubelet will restart it.
This is a very dangerous logical error that can lead to unpredictable consequences for the cluster application.

**What you expected to happen**:

Since the init containers are already executed, they must be removed from the system before running app containers of the Pod.

**How to reproduce it (as minimally and precisely as possible)**:

Start test pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
  - name: www
    emptyDir: {}
  initContainers:
  - name: testinit
    image: busybox:1.28
    resources:
      requests:
        cpu: 5m
        ephemeral-storage: 1Mi        
    volumeMounts:
    - name: www
      mountPath: /var/www
    command:
    - sh
    - -c
    - |
      echo "TIMESTAMP: $( date )" > /var/www/timestamp
  containers:
  - name:  testbox
    image: busybox:1.28
    resources:
      requests:
        cpu: 5m
        ephemeral-storage: 1Mi
    volumeMounts:
    - name: www
      mountPath: /var/www
    command:
    - sh
    - -c
    - |
      while [ 1 ]; do
        cat /var/www/timestamp
        sleep 10
      done
```

SSH to the node, gain root access and remove "exited" init-container:

```
$ sudo -s
# crictl ps -a --state Exited
CONTAINER ID   IMAGE          CREATED         STATE    NAME      ATTEMPT  POD ID
e827eed111bf0  8c811b4aec35f  29 seconds ago  Exited   testinit  0        2fdd2a9f992a6
...
# crictl rm e827eed111bf0
e827eed111bf0
```
Wait a little and refresh exited containers list:

```
# crictl ps -a --state Exited
CONTAINER ID   IMAGE          CREATED         STATE    NAME      ATTEMPT  POD ID
9c6b1a283306e  8c811b4aec35f  7 seconds ago   Exited   testinit  0        2fdd2a9f992a6
```

Pod stdout:
```
$ kubectl logs --follow test-pod
TIMESTAMP: Sun Apr 19 06:39:40 UTC 2020
TIMESTAMP: Sun Apr 19 06:39:40 UTC 2020
TIMESTAMP: Sun Apr 19 06:39:40 UTC 2020
TIMESTAMP: Sun Apr 19 06:39:40 UTC 2020
TIMESTAMP: Sun Apr 19 06:39:40 UTC 2020
TIMESTAMP: Sun Apr 19 06:39:40 UTC 2020
TIMESTAMP: Sun Apr 19 06:39:40 UTC 2020
TIMESTAMP: Sun Apr 19 06:40:51 UTC 2020
TIMESTAMP: Sun Apr 19 06:40:51 UTC 2020
TIMESTAMP: Sun Apr 19 06:40:51 UTC 2020
TIMESTAMP: Sun Apr 19 06:40:51 UTC 2020
...
```
**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.5", GitCommit:"a5bf731ea129336a3cf32c3375317b3a626919d7", GitTreeState:"clean", BuildDate:"2020-03-31T02:49:49Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `GKE`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 18.04.3 LTS (UBUNTU_CONTAINERD)`
- Kernel (e.g. `uname -a`):
`Linux 5.0.0-1022-gke #22~18.04.3-Ubuntu SMP Thu Oct 10 19:41:43 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Others:  
`Container runtime version: containerd://1.2.10`  
`kubelet version: v1.15.11-gke.5`  
`kube-proxy version: v1.15.11-gke.5`
