### ISSUE TITLE
issue with hostPath

### ISSUE THREAD

**Issue by sojoudian** [kubernetes/kubernetes#90363]
I want to setup my kubernetes locally on minikube, and mount a directory from local machine to pod, which this directory has some huge json files, because of their size I can not put them in configMap, this is my configuration:

```
containers:
- args:
  - -config
  - /configs/config.json
  image: docker_registry.io/GoApp
  imagePullPolicy: Always
  name: GoApp
  ports:
  - containerPort: 8808
  - containerPort: 8807
  resources: {}
  volumeMounts:
  - mountPath: /configs
    name: GoApp-map
  - mountPath: /data
    name: data-vol
restartPolicy: Always
serviceAccountName: ""
volumes:
- name: GoApp-map
  configMap:
    name: GoApp-config-map-file
- name: data-vol
  hostPath:
    path: /home/maziar/Documents/templates/data
    type: Directory
status: {}
```

and the error I get is:
`Warning  FailedMount  43s (x8 over 107s)  kubelet, minikube  MountVolume.SetUp failed for volume "data-vol" : hostPath type check failed: /home/maziar/Documents/templates/data is not a directory`

the directory is there, and it is contained the required files! what is wrong is my configuration?
