### ISSUE TITLE
cadvisor output multi result for each container cpu metric

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kubernetes#90398]
I use prometheus 2.15.2 to collect kubernets 1.14.3 cadvisor monitor by following config
```
    - job_name: 'kubernetes-cadvisor'
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - target_label: __metrics_path__
        replacement: /metrics/cadvisor
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
```
But when I want to search single container cpu, there are three results return to me like this:
![telegraf](https://user-images.githubusercontent.com/18571465/80083379-1f931200-8588-11ea-8d60-295f0685dd63.png)

I think this is bug for kubernetes cadvisor, because each query will return multi result and value is different
