### ISSUE TITLE
Services without selectors (bug or feature) ?

### ISSUE THREAD

**Issue by eugene-chernyshenko** [kubernetes/kubernetes#90427]
According to documentation (https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors) I can create services for sending traffic to external ips. 
I have to create an endpoint to do it. 
There is no exact answer to the question "how service maps to endpoints"? 
I suggested it maps by name.
I found one interesting moment with a target port:

So I have an endpoint 
```
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-metrics
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.12.28.52
    ports:
      - port: 15460
        protocol: TCP
        name: metrics
```

and a service

```
apiVersion: v1
kind: Service
metadata:
  name: postgres-metrics
  namespace: monitoring
  labels:
    app: postgres-metrics
spec:
  ports:
    - name: metrics
      port: 15460
      protocol: TCP
      targetPort: 15460
```

If I describe it and I get target port and endpoint port are the same (expected)

```
k describe svc postgres-metrics | grep -A 1 TargetPort
TargetPort:        15460/TCP
Endpoints:         10.12.28.52:15460
```

But if I change target port like (15460 -> 15461 for example)

```
apiVersion: v1
kind: Service
metadata:
  name: postgres-metrics
  namespace: monitoring
  labels:
    app: postgres-metrics
spec:
  ports:
    - name: metrics
      port: 15460
      protocol: TCP
      targetPort: 15461
```

And describe the service I get target port is different than endpoint port (that's partially expected, I didn't change the target)

```
k describe svc postgres-metrics | grep -A 1 TargetPort
TargetPort:        15461/TCP
Endpoints:         10.12.28.52:15460
```

The question is which port should I request now?

Because the previous port is still working, and the new port is not working.

```
curl http://10.31.252.192:15460
<html>
        <head><title>Postgres exporter</title></head>
        <body>
        <h1>Postgres exporter</h1>
        <p><a href='/metrics'>Metrics</a></p>
        </body>
        </html>
```

1) Is it a bug? Does TargetPort make sense in services without selectors?
2) What is the exact rule to map services without selectors to endpoints? Could you update the documentation?
