### ISSUE TITLE
when I delete pods, the pods ip has been changed.but ipvs rule not change, and svc can't visit.

### ISSUE THREAD

**Issue by xishengcai** [kubernetes/kubernetes#90435]
**What happened**:
```
when I delete pods, the pods ip has been changed.but ipvs rule not change, and svc can't visit.
```

**What you expected to happen**:
```
svc can visit success.
ipvs rule changed.
```

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl run nginx --image=nginx
kubectl expose deployment nginx --port=80 --target-port=80
kubectl get pods -o wide
kubectl get svc
ipvsadm -ln
```
```
kubectl delete pods -l run=nginx
kubectl get pods -o wide
ipvsadm -ln
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubernetes - v1.18.0
kubectl- v1.18.0
```

- Cloud provider or hardware configuration:
```
provider: aliCloud 
ecs: 4c8G
one master, one slave
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux i-j6cbbtbe7qsorp5m1g6b 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
kubeadm
```

kubeadm config
```
apiVersion: kubeadm.k8s.io/v1beta1
controlPlaneEndpoint: 47.57.127.34:6443
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: 1.18.0
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
```
- Network plugin and version (if this is a network-related bug):
```
calico 3.8.4
```
- Others:
