### ISSUE TITLE
New type of Service: external SRV record

### ISSUE THREAD

**Issue by yann-soubeyrand** [kubernetes/kubernetes#90444]
**What would you like to be added**:

I'd like a new type of Service, an external SRV record service which would be configured similarly to an external name service, by setting an external DNS record. However, contrary to an external name service which translates to a CNAME to the DNS record, this new service type would continually resolve the SRV record in the background and update the service endpoints with the SRV record targets. It wouldn't handle record priority and would only handle record weights of 0 and 1 (1 meaning to add this target to the endpoints and 0 to ignore this target).

**Why is this needed**:

This service type would be of great help when you have external services like AWS RDS read only replicas and you've an application which can't handle the load balancing between these replicas. With this new service type, the load balancing would be transparent for the application.

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by aojea** [comment]
I'm curious about this use case, but I'm not totally getting it sorry

A service Type ExternalName

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalName
  externalName: my.database.example.com
```
answers a CNAME record with the data provided
````
my-service.prod.svc.cluster.local. 10 IN CNAME my.database.example.com.
```

so far so good, you say 

> ... this new service type would continually resolve the SRV record in the background and update the service endpoints with the SRV record targets. 

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalService
  srvRecord: my.database.example.com???
```

?is this correct?? how does this continue?
what service endpoints are you referring to?

**Comment by yann-soubeyrand** [comment]
@aojea thanks for your curiosity about this use case ;-)

Continuing on your example, let's modify my-service to look like this:

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalService
  srvRecord: my.database.example.com
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
```

Let's say the SRV record for my.database.example.com looks like this:

```
my.database.example.com. 15 IN SRV 1 1 5432 my-db-replica-1.xxxxx.eu-west-1.rds.amazonaws.com.
my.database.example.com. 15 IN SRV 1 1 5432 my-db-replica-2.xxxxx.eu-west-1.rds.amazonaws.com.
my.database.example.com. 15 IN SRV 1 1 5432 my-db-replica-3.xxxxx.eu-west-1.rds.amazonaws.com.
my.database.example.com. 15 IN SRV 1 0 5432 my-db-replica-4.xxxxx.eu-west-1.rds.amazonaws.com.
```

And let's say the the A records corresponding to the targets of the SRV record look like this:

```
my-db-replica-1.xxxxx.eu-west-1.rds.amazonaws.com. 5 IN A 10.0.0.1
my-db-replica-2.xxxxx.eu-west-1.rds.amazonaws.com. 5 IN A 10.0.0.2
my-db-replica-3.xxxxx.eu-west-1.rds.amazonaws.com. 5 IN A 10.0.0.3
my-db-replica-4.xxxxx.eu-west-1.rds.amazonaws.com. 5 IN A 10.0.0.4
```

The priority of 0 for my-db-replica-4.xxxxx.eu-west-1.rds.amazonaws.com indicates that this replica should not receive traffic and so the endpoints for my-service should be set to look like this:

```
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
  namespace: prod
subsets:
- addresses:
  - ip: 10.0.0.1
  - ip: 10.0.0.2
  - ip: 10.0.0.3
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
```

These endpoints would be continually adjusted to reflect what's returned by the DNS resolution of the SRV record.

The result would be that the cluster IP associated with the service would balance load betwen the endpoints.

Why is this new service type needed in the first place? Because in the case of RDS, the only guarantee is for the my-db-replica-x.xxxxx.eu-west-1.rds.amazonaws.com DNS records to always resolve to the IP of the database instances. These IP could change in case the instances had to be moved due to an outage (for example). In this case, an external name service type couldn't help whereas this new service type would.

I hope I've been clearer in my explanations, if not, don't hesitate to tell me ;-)
