### ISSUE TITLE
HPA v2 scales up deployment during rolling updates

### ISSUE THREAD

**Issue by danielgblanco** [kubernetes/kubernetes#90461]
**What happened**:
I have been experiencing some strange behaviour on the HPA v2 on v1.14.9, where it scales up a deployment unnecessarily during rolling updates. The deployment has a `maxSurge` of 1 and a `maxUnavailable` of 0, and while the deployment is completely idle at 1 replica, a rolling update makes it scale up to 4 replicas or more very rapidly, and then scales down gradually. This seems to be related to the fact that it scales on a custom metrics, as the same does not occur when scaling only on CPU. The custom metric that it scales on may not available at Pod startup, as it is generated per Pod with a `rate` function, and the Prometheus scrape interval is 30 seconds.
 
The problem seems to happen when the outdated Pod is deleted, and it gets more exaggerated if the Pod takes longer to shut down. I tried to keep this issue as simple as possible but adding a long `terminationGracePeriodSeconds` increases the Pod count up to 8 or 10 sometimes. 
 
After triggering a rolling update, the deployment scales up to 4:
 
```
$ kubectl get deployment ubuntu --watch
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
ubuntu   1/1     1            1           100m
ubuntu   1/1     0            1           100m
ubuntu   1/1     1            1           100m
ubuntu   2/1     1            2           100m
ubuntu   1/1     1            1           100m
ubuntu   1/2     1            1           100m
ubuntu   1/2     1            1           100m
ubuntu   1/2     1            1           100m
ubuntu   1/2     2            1           100m
ubuntu   2/2     2            2           100m
ubuntu   2/3     2            2           100m
ubuntu   2/3     2            2           100m
ubuntu   2/3     2            2           100m
ubuntu   2/3     3            2           100m
ubuntu   3/3     3            3           100m
ubuntu   3/4     3            3           100m
ubuntu   3/4     3            3           100m
ubuntu   3/4     3            3           100m
ubuntu   3/4     4            3           100m
ubuntu   4/4     4            4           100m
```
 
 The HPA is continuously under target:
 
```
$ kubectl get hpa ubuntu --watch
NAME     REFERENCE           TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
ubuntu   Deployment/ubuntu   782m/3Mi   1         10        1          91m
ubuntu   Deployment/ubuntu   819m/3Mi   1         10        2          91m
ubuntu   Deployment/ubuntu   765m/3Mi   1         10        3          91m
ubuntu   Deployment/ubuntu   765m/3Mi   1         10        4          91m
ubuntu   Deployment/ubuntu   214m/3Mi   1         10        4          92m
ubuntu   Deployment/ubuntu   288m/3Mi   1         10        4          92m
```

 The HPA also seems to identify that the custom metric is above target, which is not possible since all Pods are idle:
 
```
  Type     Reason                        Age                From                       Message
  ----     ------                        ----               ----                       -------
  Normal   SuccessfulRescale             10m                horizontal-pod-autoscaler  New size: 2; reason: pods metric container_network_receive_bytes_total above target
  Normal   SuccessfulRescale             10m                horizontal-pod-autoscaler  New size: 3; reason: pods metric container_network_receive_bytes_total above target
```

 Furthermore, if we compared spec/status replicas in the deployment and current/desired replicas in the HPA we can see the following (removing consecutive repeated values):
 
```
$ while sleep 1; do echo -n `date +%T` "--> " ; kubectl get hpa ubuntu -o=jsonpath='HPA       : current: {.status.currentReplicas}, desired: {.status.desiredReplicas}'; echo; echo -n `date +%T` "--> ";  kubectl get deployment ubuntu -o=jsonpath='Deployment: current: {.status.replicas}, spec: {.spec.replicas}'; echo -e "\n"; done

16:56:23 --> HPA       : current: 1, desired: 1
16:56:23 --> Deployment: current: 1, spec: 1

16:56:24 --> HPA       : current: 1, desired: 1
16:56:24 --> Deployment: current: 2, spec: 1

16:56:29 --> HPA       : current: 1, desired: 1
16:56:29 --> Deployment: current: 1, spec: 1

16:56:31 --> HPA       : current: 1, desired: 2
16:56:32 --> Deployment: current: 2, spec: 2

16:56:46 --> HPA       : current: 2, desired: 3
16:56:46 --> Deployment: current: 3, spec: 3

16:57:02 --> HPA       : current: 3, desired: 4
16:57:02 --> Deployment: current: 4, spec: 4

16:57:16 --> HPA       : current: 4, desired: 4
16:57:17 --> Deployment: current: 4, spec: 4

```

My thoughts are that the following is happening:
 1. One Pod gets created as surge and it comes up (deployment status is 2).
 2. The deployment brings down the old Pod, which takes time to terminate or does not terminate gracefully (deployment spec and status are both 1 again).
 2. The HPA kicks in, and as it does not have metrics yet for the new Pod, it gets assigned [100% of the target as the value](https://github.com/kubernetes/kubernetes/blob/500f5aba80d71253cc01ac6a8622b8377f4a7ef9/pkg/controller/podautoscaler/replica_calculator.go#L204).
 3. As there are 2 Pods running and ceil(0.5111 * 2) = 2, the HPA algorithm returns 2.
 4. The HPA reconciliation compares this value [against the deployment spec](https://github.com/kubernetes/kubernetes/blob/500f5aba80d71253cc01ac6a8622b8377f4a7ef9/pkg/controller/podautoscaler/horizontal.go#L602), which at the time is 1, and the deployment adds one more, to make the deployment spec 2. Now we have 3 Pods running (1 running, 1 starting and 1 terminating). This is why we get a message like `%s above target`
 
This keeps happening until either more Pods start to have metrics (and they bring down the average making the HPA scale down) or until we reach 10 replicas in which case the usage ratio is 0.91 (1 pod underutilised and 9 pods at 100%) and the HPA decides to [return the current deployment replicas](https://github.com/kubernetes/kubernetes/blob/500f5aba80d71253cc01ac6a8622b8377f4a7ef9/pkg/controller/podautoscaler/replica_calculator.go#L227).

I believe the source of the problem is that the Deployment spec is not representing the actual number of running/terminating pods. The HPA reconciliation gets the current replicas from the deployment, but then the algorithm gets the number of Pods from the [podList](https://github.com/kubernetes/kubernetes/blob/500f5aba80d71253cc01ac6a8622b8377f4a7ef9/pkg/controller/podautoscaler/replica_calculator.go#L170).

**What you expected to happen**:
 I would expect the HPA to keep the deployment at the current number of replicas

**How to reproduce it (as minimally and precisely as possible)**:

 1. Create a deployment as follows:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubuntu
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 1; done;" ]
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 20m
            memory: 256Mi
```

 2. Create an HPA for that deployment using one custom metric to scale on:

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ubuntu
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:  
      metric:
        name: container_network_receive_bytes_total
      target:
        averageValue: 3Mi
        type: AverageValue
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: ubuntu
```

 3. With the Pod idle, trigger a rolling update by adding a new label to to the deployment Pod.
 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.9
- Cloud provider or hardware configuration: AWS
