### ISSUE TITLE
Free-form object directive as Map's value type in CRD openapi schema doesn't work

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#90504]
/kind bug
/sig api-machinery
/cc @sttts @kubernetes/sig-api-machinery-misc 

in [OAS's supported data models](https://swagger.io/docs/specification/data-models/dictionaries/), we can represent map structure using `additionalProperties`. and it says there's two official ways plus one CRD's extended way to represent free-form object:
```
#1 
foo: 
  type: object
    additionalProperties: true

#2
foo:
  type: object
  additionalProperties: {} # we can omit it in CRD's openapi schema 

#3
foo:
  type: object
  x-kubernetes-preserve-unknown-fields: true
```

(NOTE: however currently, 1 and 2 are not completely free-form: it allows arbitrary map keys but doesn't allow plain number or string type as the root. but it's not the point i'm trying to make in this issue)

when we represent a map of free-form values, the schema should support all of the following forms:

```
#4
foo:
  type: object
  additionalProperties:
    type: object
    additionalProperties: true

#5
foo:
  type: object
  additionalProperties:
    type: object
    additionalProperties: {} # we can omit it in CRD's openapi schema

#6
foo:
  type: object
  additionalProperties:
    type: object
    x-kubernetes-preserve-unknown-fields: true
```

but sadly the approach 5 doesn't work in CRD's openapi schema. everything written into the map will keep the key but always drop the value silently. e.g.:
```
foo:
   map_key: {} # whatever you put under foo will be dropped except the key
```

**Comment by liggitt** [comment]
> sadly the approach 5 doesn't work in CRD's openapi schema

Can you clarify what you mean by `we can omit it in CRD's openapi schema`?

**Comment by liggitt** [comment]
I would expect approach 6 to be required to preserve unknown properties in object values without them being pruned.

**Comment by yue9944882** [comment]
>> sadly the approach 5 doesn't work in CRD's openapi schema

> Can you clarify what you mean by we can omit it in CRD's openapi schema?

i mean it doesn't make a difference whether we keep the line or not:

```
#5
foo:
  type: object
  additionalProperties:
    type: object
    additionalProperties: {}  # --> removing the line will work the same
```

> I would expect approach 6 to be required to preserve unknown properties in object values without them being pruned.

i agree 6 would be the officially recommended approach. so 4 is actually working but it's not intended? as a matter of fact, most developers learns the openapi schema from the OAS site which doesn't mention the kubernetes' pruning annotation, hence supporting 4&5 would make the CRD's openapi schema more user-friendly. last but not least, the CRDs generated by [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen)/kubebuilder always uses approach 2 to represent "free-form", so there can be folks using 2 to represent "free-form" values of a map i.e. approach 5.

**Comment by liggitt** [comment]
It makes a difference whether pruning is enabled for the CRD. In general, when pruning is on, x-kubernetes-preserve-unknown-fields is required to disable pruning. Are you using v1beta1 or v1 CRD (pruning defaults off in v1beta1, and defaults on in v1)? Do you have the full CRD manifest you are using?

**Comment by liggitt** [comment]
Fields are only dropped when pruning is enabled (by default in v1 CRDs or when spec.preserveUnknownFields=false in v1beta1 CRDs).

When pruning is disabled, unknown fields are always preserved.

When pruning is enabled, I get validation errors trying to create the CRD you describe with `additionalProperties: {}`:

* spec.validation.openAPIV3Schema.properties[b].additionalProperties.type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[f].additionalProperties.additionalProperties.type: Required value: must not be empty for specified object fields

I get the following results with pruning enabled for the various scenarios you describe:

CRD:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: unknowns.example.com
spec:
  preserveUnknownFields: false
  conversion:
    strategy: None
  group: example.com
  names:
    kind: Unknown
    listKind: UnknownList
    plural: unknowns
    singular: unknown
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        a: 
          type: object
          additionalProperties: true
        b:
          type: object
          additionalProperties: {type: object}
        c:
          type: object
        d:
          type: object
          x-kubernetes-preserve-unknown-fields: true
        e:
          type: object
          additionalProperties:
            type: object
            additionalProperties: true
        f:
          type: object
          additionalProperties:
            type: object
            additionalProperties: {type: object}
        g:
          type: object
          additionalProperties:
            type: object
        h:
          type: object
          additionalProperties:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
```

custom resource:
```yaml
apiVersion: example.com/v1
kind: Unknown
metadata:
  name: foo
a:
  foo: true
b:
  foo:
    bar: true
c:
  foo: true
d:
  foo: true
e:
  foo:
    bar: true
f:
  foo:
    bar:
      baz: true
g:
  foo:
    bar: true
h:
  foo:
    bar: true
```

result fetched from API server:
```yaml
apiVersion: example.com/v1
kind: Unknown
metadata:
  name: foo
  ...
a:
  foo: true
b:
  foo: {}
c: {}
d:
  foo: true
e:
  foo:
    bar: true
f:
  foo:
    bar: {}
g:
  foo: {}
h:
  foo:
    bar: true
```

That result matches my expectations:
* additionalProperties preserves arbitrary keys, and prunes any object values according to the schema specified for the additionalProperties
* x-kubernetes-preserve-unknown-fields is required to preserve unknown fields
