### ISSUE TITLE
activeDeadlineSeconds is invalid, job has completed, info is not accurate about status

### ISSUE THREAD

**Issue by xingfeng1234** [kubernetes/kubernetes#90551]
**What happened**:
First,you can create job like below yaml file
```
apiVersion: batch/v1
  kind: Job
  metadata:
    name: job-test-deadline
    namespace: default
  spec:
    completions: 1
    parallelism: 1
    activeDeadlineSeconds: 40
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - command:
          - bin/bash
          - -c
          - sleep 120s
          image: *.*.*.*:30012/library/tomcat:8.5.39
          imagePullPolicy: IfNotPresent
          name: container0
          resources: {}
        restartPolicy: Never
```
Second, activeDeadlineSeconds is not reached, and delete the original  job above, then create job  using the same yaml file above.
You will find activeDeadlineSeconds is invalid. Please wait the job to complete. Util the job is completed.
exec command: kubectl edit job job-test-deadline
```
status:
  conditions:
  - lastProbeTime: "2020-04-28T09:34:40Z"
    lastTransitionTime: "2020-04-28T09:34:40Z"
    message: Job was active longer than specified deadline
    reason: DeadlineExceeded
    status: "True"
    type: Failed
  startTime: "2020-04-28T09:32:38Z"
  succeeded: 1
```
**What you expected to happen**:
info about status like below:
```
status:
  completionTime: "2020-04-28T09:40:21Z"
  conditions:
  - lastProbeTime: "2020-04-28T09:40:21Z"
    lastTransitionTime: "2020-04-28T09:40:21Z"
    status: "True"
    type: Complete
  startTime: "2020-04-28T09:38:19Z"
  succeeded: 1
```
**How to reproduce it (as minimally and precisely as possible)**:
you can reproduce it, follow the steps above.
**Anything else we need to know?**:
Nothing
**Environment**:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
