### ISSUE TITLE
activeDeadlineSeconds is not reached, the original job is regenerated, then activeDeadlineSeconds is invalid

### ISSUE THREAD

**Issue by xingfeng1234** [kubernetes/kubernetes#90550]
**What happened**:
First,you can create job like below yaml file.
```
apiVersion: batch/v1
  kind: Job
  metadata:
    name: job-test-deadline
    namespace: default
  spec:
    completions: 1
    parallelism: 1
    activeDeadlineSeconds: 40
    template:
      metadata:
        creationTimestamp: null
      spec:
        containers:
        - command:
          - bin/bash
          - -c
          - sleep 120s
          image: *.*.*.*:30012/library/tomcat:8.5.39
          imagePullPolicy: IfNotPresent
          name: container0
          resources: {}
        restartPolicy: Never
```
Second, activeDeadlineSeconds is not reached, and delete the original  job, then create job  using the same yaml file above.

You will find that activeDeadlineSeconds is invalid. When activeDeadlineSeconds have reached, the job is still running. I am very confused about this.
**What you expected to happen**:
ActiveDeadlineSeconds is reached, job can be stopped.

**How to reproduce it (as minimally and precisely as possible)**:
you can reproduce it, follow the steps above.
**Anything else we need to know?**:
nothing
**Environment**:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by xingfeng1234** [comment]
The problem has always existed. I use activeDeadlineSeconds in the spec under the template object instead, which can solve our business scenario.

**Comment by xingfeng1234** [comment]
This problem has been repaired . I check the problem in v1.18.3.

**Comment by xingfeng1234** [comment]
Sorry, the problem is still existing in v1.18.3.

**Comment by soltysh** [comment]
The important thing is to create the first job and immediately remove it, and re-create it. This will cause the 2nd job to eventually reached the failed status, but only because the pod finished, not because the `activeDeadlineSeconds` was reached. This is clear from the status I got here:
```
  status:
    conditions:
    - lastProbeTime: "2020-06-03T19:52:50Z"
      lastTransitionTime: "2020-06-03T19:52:50Z"
      message: Job was active longer than specified deadline
      reason: DeadlineExceeded
      status: "True"
      type: Failed
    startTime: "2020-06-03T19:50:47Z"
    succeeded: 1
```
where you clearly see `succeeded: 1`, even the job has failed with `DeadlineExceeded` set.
