### ISSUE TITLE
Preferred inter-pod affinity rarely collocates pods

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [kubernetes/kubernetes#90595]
**What happened**:

Trying to leverage the inter-pod affinity [concept](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity). 

The pod with the affinity property fails almost consistently to collocate with the pod described in the `labelSelector`
 
**What you expected to happen**:

Having the pod with the `affinity` property in its spec, collocated __at least sometimes__ with the pod described / targeted via the `labelSelector`.

**How to reproduce it (as minimally and precisely as possible)**:

Here is a `jenkins` pod on `jenkins` ns.

```
▶ k get pods -n jenkins jenkins-7wrgg -o yaml | grep -i labels -A 9
  labels:
    app: jenkins-master
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins-cd
```

Here is an `nginx` deployment whose pod I am trying to collocate with the above pod.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: default
  annotations:
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              namespaces:
                - all
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - jenkins-master
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1Gi"
            cpu: "100m"
          requests:
            memory: "100Mi"
            cpu: "50m"
```

Here is the status of the GKE node that the `jenkins` pod has been scheduled on

```
gke-mynode
  Resource                   Requests      Limits
  cpu                        701m (17%)    1903m (48%)
  memory                     2268Mi (17%)  3592Mi (26%)
```

I honestly perfomed 7 consecutive times

```
k apply -f nginx.yaml
```

followed by 

```
k delete deployment nginx
```

__All__ 7 times the `nginx` pod was scheduled on a different node than `jenkins-master`

It's as if I had used pod-ANTI-affinity.

Is this an issue or some misconfiguration of mine?

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
▶ k version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:33:14Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.24", GitCommit:"39e41a8d6b7221b901a95d3af358dea6994b4a40", GitTreeState:"clean", BuildDate:"2020-02-29T01:24:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): container optimized os
- Kernel (e.g. `uname -a`): N/A
- Install tools: GKE managed
- Network plugin and version (if this is a network-related bug): N/A
- Others:
