### ISSUE TITLE
NetworkPolicy allow traffic from nodes by label

### ISSUE THREAD

**Issue by nielsole** [kubernetes/kubernetes#90590]
**What would you like to be added**:
I would like the following network policy to be valid:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          project: myproject
    - nodeSelector:
        matchLabels:
          node-role.kubernetes.io/lb: ""
```
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#networkpolicyingressrule-v1-networking-k8s-io
This would mean adding `nodeSelector` as a field to NetworkPolicyPeer as a LabelSelector

**Why is this needed**:
When a pod is using hostNetwork, it cannot be selected by a networkPolicy. As the network policies are whitelist-based, there is no way to whitelist just those nodes except via their IP addresses, which is unfeasible in a dynamic environment.
This is a common use-case when allowing traffic just from an ingress controller.

OpenShift has good documentation on how to solve it on their platform, but I couldn't find any workaround for stock kubernetes: https://docs.openshift.com/container-platform/4.1/networking/configuring-networkpolicy.html
I will solve my problem differently now. I just wanted to document my findings for others.
Cheers
