### ISSUE TITLE
Allow to specify char encoding when mounting ConfigMaps as volumes

### ISSUE THREAD

**Issue by fml2** [kubernetes/kubernetes#90633]
**What would you like to be added**:

As decribed [here](https://kubernetes.io/docs/concepts/configuration/secret/#projection-of-secret-keys-to-specific-paths) and [here](https://kubernetes.io/docs/concepts/storage/volumes/#configmap), it is possible to present a configMap entry or a secret as a file to the application.

ConfigMap entries and textual secrets (not the binary ones) are characters; files are by their nature byte sequences. Hence, when representing ConfigMap entries or textual secrets as files, a char encoding is important. Since, depending on it, the bytes will be different. For example, if I encode he German Umlaut "Ä" as UTF-8, I get 2 bytes. When encoding the same char as ISO-8859-1, I get 1 byte.

It would be cool if there were another attribute for the encoding to use, e.g. like this:

```
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        items:
          - key: log_level
            path: log_level
            charEncoding: ISO-8859-1   <-- the new attribute
```

**Why is this needed**:
If the application expects the file to be encoded with a certaint char encoding in order to work correctly, there is now no way to specify the encoding to use.

My experiments showed that UTF-8 is used. But what if I want/need some other encoding? Besides: I don't know whether UTF-8 is a intended encoding or just e.g. the default one in the current runtime environment. In the latter case the file contents is dependent on the default encoding which is not good IMO.
