### ISSUE TITLE
kube-proxy not respecting metricsBindAddress

### ISSUE THREAD

**Issue by cjreyn** [kubernetes/kubernetes#90641]
**What happened**:
kube-proxy binds on IPv6 address when "metricsBindAddress: 0.0.0.0:10249" is set in its config file

**What you expected to happen**:
Since an IPv4 address has been requested, it should bind on IPv4 address 0.0.0.0:10249

**How to reproduce it (as minimally and precisely as possible)**:
Check the config map named "kube-proxy" in the kube-system namespace. This drives kube-proxy config. By default it contains:

```
[root@cs05r-sc-cloud-31 ~]# kubectl describe cm kube-proxy -n kube-system
Name:         kube-proxy
Namespace:    kube-system
Labels:       app=kube-proxy
Annotations:  <none>

Data
====
config.conf:
----
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
clientConnection:
  acceptContentTypes: ""
  burst: 0
  contentType: ""
  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
  qps: 0
clusterCIDR: ""
configSyncPeriod: 0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 0s
  syncPeriod: 0s
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 0s
kind: KubeProxyConfiguration
metricsBindAddress: ""
mode: ""
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
udpIdleTimeout: 0s
winkernel:
  enableDSR: false
  networkName: ""
  sourceVip: ""
kubeconfig.conf:
----
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://api.pollux.diamond.ac.uk:6443
  name: default
contexts:
- context:
    cluster: default
    namespace: default
    user: default
  name: default
current-context: default
users:
- name: default
  user:
    tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
Events:  <none>
```
Netstat confirms the documented behaviour that the default metric address is 127.0.0.1:10249:

```
[root@cs05r-sc-cloud-31 ~]# netstat -telpn  | grep 10249
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      0          127802996  128011/kube-proxy  

```
When the config map is edited as follows, netstat shows the IPv6 bind:
```
[root@cs05r-sc-cloud-31 ~]# kubectl describe cm kube-proxy -n kube-system
Name:         kube-proxy
Namespace:    kube-system
Labels:       app=kube-proxy
Annotations:  <none>

Data
====
config.conf:
----
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
clientConnection:
  acceptContentTypes: ""
  burst: 0
  contentType: ""
  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
  qps: 0
clusterCIDR: ""
configSyncPeriod: 0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 0s
  syncPeriod: 0s
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 0s
kind: KubeProxyConfiguration
metricsBindAddress: 0.0.0.0:10249
mode: ""
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
udpIdleTimeout: 0s
winkernel:
  enableDSR: false
  networkName: ""
  sourceVip: ""
kubeconfig.conf:
----
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://api.pollux.diamond.ac.uk:6443
  name: default
contexts:
- context:
    cluster: default
    namespace: default
    user: default
  name: default
current-context: default
users:
- name: default
  user:
    tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
Events:  <none>

```
IPv6 Bind:
```
[root@cs05r-sc-cloud-31 ~]# netstat -telpn  | grep 10249
tcp6       0      0 :::10249                :::*                    LISTEN      0          127703909  116995/kube-proxy   
```

**Anything else we need to know?**:
This prevents prometheus-operator from scraping metrics.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.3
- Cloud provider or hardware configuration: On prem: kubeadm
- OS (e.g: `cat /etc/os-release`): Red Hat Enterprise Linux Server 7.7 (Maipo)
- Kernel (e.g. `uname -a`):3.10.0-1062.12.1.el7.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): weave 2.6.0
- Others:
