### ISSUE TITLE
Pod with hostNetwork cannot updated when replicas equal to nodes and one of nodes notReady

### ISSUE THREAD

**Issue by pytimer** [kubernetes/kubernetes#90669]
**What happened**:

Pod with hostNetwork cannot updated when deployment replicas equal to nodes and one of nodes status `NotReady`. I use `RollingUpdate` and `Recreate` strategy, these are the same problem.

**What you expected to happen**:

I hope pod can updated when update the deployment.

**How to reproduce it (as minimally and precisely as possible)**:

- apply deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3  ---> replicas must be equal to nodes number.
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
- shutdown one of nodes.
- modify image `nginx:1.14.2` to `nginx`
- kubectl get pod -owide.  You can see one pod status always `Pending`.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.17.2`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): `flannel`.(But i think this problem not related cni.)
- Others:

**Comment by afrouzMashaykhi** [comment]
Is it a bug? it seems logical to me.
`Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  8s (x2 over 93s)  default-scheduler  0/3 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 2 node(s) didn't have free ports for the requested pod ports.
`

**Comment by Pingan2017** [comment]
port conflict 
Using `Recreate` strategy and delete pod manually

**Comment by pytimer** [comment]
@afrouzMashaykhi @Pingan2017 I hope pod can update automatically, not delete manually. And delete pod should use `kubectl delete pod --force` when using `Recreate`.

**Comment by tnozicka** [comment]
If you have 3 replicas that by definition (hostnetwork+same_port) require 3 nodes and one of the node is down, your deployment is already 1 pod down and to maintain availability it first has to reconcile that pod before continuing the update, otherwise it would be 2 pods down while the default toleration is 1 down. You can tweak it with MaxSurge and MaxUnavailable but I don't see a bug here.

**Comment by pytimer** [comment]
Thanks @tnozicka . Use maxSurge and maxUnavailable solve this issue. 

```yaml
strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 70% 
    type: RollingUpdate
```
