### ISSUE TITLE
Pod affinity with operator "DoesNotExist" does not work

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#90679]
**What happened**:
When creating a pod with `PodAffinity` operator `DoesNotExist`, the pod will always land on a node that it should not. (For example, if PodA is on Node1 with the label `foo`, and PodB is created with a Pod Affinity for `DoesNotExist` against label `foo`, PodB will always be scheduled to Node 1)

Note that this is probably not intended behavior, but could be considered a WONTFIX since Affinity/DoesNotExist is functionally the same as just AnitAffinity and so should not be recommended to use.

This is due to the scheduler's topology map which is used to optimize affinity/anti-affinity calculations ([see here](https://github.com/kubernetes/kubernetes/blob/0bcbe384d866b9cf4b51d0a2905befc538e99db7/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go#L489))

In examples with tracing enabled, I was able to confirm this behavior because every node *except* the expected "unschedulable" node fails filtering with `node(s) didn't match pod affinity/anti-affinity, node(s) didn't match pod affinity rules`

**What you expected to happen**:
The Pod goes on any other node.

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod with a label:
```
apiVersion: v1
kind: Pod
metadata:
  name: s1
  labels:
    security: s1
spec:
  containers:
  - name: ocp
    image: docker.io/ocpqe/hello-pod
```

Create another pod with affinity operator doesnotexist:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-doesnotexist
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: DoesNotExist
        topologyKey: kubernetes.io/hostname
  containers:
  - name: pod-affinity
    image: docker.io/ocpqe/hello-pod
```

Check the scheduling results of the pods, and the second pod will be scheduled to the unexpected node

**Anything else we need to know?**:
This is consistent in a small test environment

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ahg-g** [comment]
The reason the still gets scheduled on the node is because the pod affinity semantics is as follows: there needs to be at least one pod on the node such that the label doesn't exist for the node to be feasible. While ```pod-affinity-doesnotexist``` doesn't meet this criteria, there must be another pod on the node that did.

I think this the behavior is correct.

**Comment by damemi** [comment]
@ahg-g maybe I wasn't clear, but `s1` is created first, and is able to be scheduled onto any node. `pod-affinity-doesnotexist` should then *avoid* `s1`'s node due to the label on `s1` correct? While there may be other pods on the node that *don't* have the label, there are also pods on all of the other nodes that don't have the label, so why does it pick the one that does?

Though it's true that I'm not able to replicate this when I create several pods on each node that don't have the label, it's weird that when I only have the one it attracts to that node.

For example, on a fresh cluster where I haven't created anything else:
```
$ kubectl create -f ~/s1.yaml 
pod/s1 created
$ kubectl create -f ~/affinity-does-not-exist-pod-with-affinity.yaml 
pod/pod-affinity-doesnotexist-sttfp created
$ kubectl get pods -o wide
NAME                              READY   STATUS      RESTARTS   AGE   IP            NODE                           NOMINATED NODE   READINESS GATES
pod-affinity-doesnotexist-sttfp   0/1     Completed   1          5s    10.128.2.12   ip-10-0-139-145.ec2.internal   <none>           <none>
s1                                0/1     Completed   1          11s   10.128.2.11   ip-10-0-139-145.ec2.internal   <none>           <none>
```

To demonstrate this I've created a simple integration test in https://github.com/kubernetes/kubernetes/pull/90849. Given that the node contains a pod which has the label, that node should fail the affinity filtering step right? Please correct me if I'm wrong

**Comment by ahg-g** [comment]
> maybe I wasn't clear, but s1 is created first, and is able to be scheduled onto any node. pod-affinity-doesnotexist should then avoid s1's node due to the label on s1 correct? 

ah, my bad, I switched the pod names :) my point still stand though: the reason pod ```pod-affinity-doesnotexis``` still gets scheduled on the node is because the pod affinity semantics is as I mentioned above: at least one pod on the node needs to satisfy the affinity for the node to be feasible, so while s1 didn't meet this criteria, there must be another pod on the node that did.

**Comment by Huang-Wei** [comment]
@ahg-g's explanation is correct. Suppose we have 2 nodes: node1, node2, the first Pod gets scheduled to node2:

```
$ k get po -o wide
NAME   READY   STATUS    RESTARTS   AGE     IP                NODE    NOMINATED NODE   READINESS GATES
p1     1/1     Running   0          8m55s   192.168.192.168   node2   <none>           <none>
```

When it comes to the second Pod, scheduler first checks if any existing Pod matches its Affinity Term - p1 doesn't fit due to the `DoesNotExist` operator. So what should scheduler do, leave it as pending? Nope. We have a special rule in PodAffinity for this case (no Pod matches its affinity term):

Check if the Pod matches itself on its affinity term.
- If no, leave it as pending
- If yes, schedule to any available Node - it's the case you described as the second Pod doesn't have any label, so it does match itself on its affinity term.

The result you showed is as expected. It's just happened to land on the Node where p1 gets scheduled to.

So we can verify that by adding an additional nodeSelector/nodeAffinity to bypass the node where p1 gets scheduled (in this case it's node2):

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: p2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: foo
            operator: DoesNotExist
        topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - node2
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.2
```

And creating p2 will get it scheduled to another node (node1):

```
$ k apply -f p2.yaml
pod/p2 created
$ k get po -o wide
NAME   READY   STATUS    RESTARTS   AGE    IP                NODE    NOMINATED NODE   READINESS GATES
p1     1/1     Running   0          9m4s   192.168.192.168   node2   <none>           <none>
p2     1/1     Running   0          5s     192.168.192.168   node1   <none>           <none>
```

---

FYI: the p1.yaml.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: p1
  labels:
    foo: bar
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.2
```
