### ISSUE TITLE
time based Pod Disruption Budget

### ISSUE THREAD

**Issue by guilhem** [kubernetes/kubernetes#90765]
**What would you like to be added**:

Set information about time in a PDB. For example it can be:

```yaml
spec:
  window:
    begin: 0 0 13 * 5
    duration: 2h
  cooldown: 1d  
```

- `window`: the moment where a pod can be killed.
- `cooldown` how many times to wait between kills.

**Why is this needed**:

Current Pod Disruption Budget is only based on an "instant" state: how many pods I have running.

In some case (mainly stateful apps), we may have to consider disruption in a period of time and when in time.
