### ISSUE TITLE
kubernetes: failure in a Windows system call: The system cannot find the path specified

### ISSUE THREAD

**Issue by srbhklkrn** [kubernetes/kubernetes#90802]
I'm trying to run the init script before the container starts in the pod, for that, I have created a config map from file and mounted as shown in deployment scripts then simply trying to run the `initscript.ps1` but giving error not sure what am I missing.

`initscript-config-script` is a configMap that I have created from `initscript.ps1` script.

Deployment script:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kubeapp
  namespace: default
  labels:
    app: demo-kubeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kubeapp
  template:
    metadata:
      labels:
        app: demo-kubeapp
    spec:
      containers:
      - name: demo-kubeapp
        image: <private>
        command: ["C:\\scripts\\initscript.ps1"]
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: initscript-configmap
        volumeMounts:
        - name: initscript-config-script
          mountPath: /scripts
      tolerations:
      - key: "windows"
        operator: "Equal"
        value: "2019"
        effect: NoSchedule
      volumes:
      - name: initscript-config-script
        configMap:
          name: initscript-config-script
          defaultMode: 0744
```
Error Stack:

> Warning Failed 11s (x2 over 15s) kubelet, 24f17026-ee31-4d94-8d4a-8b723809be9d Error: failed to start container "demo-kubeapp": Error response from daemon: container demo-kubeapp encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the path specified. (0x3) extra info: {"CommandLine":"C:\scripts\initscript.ps1","WorkingDirectory":"C:\inetpub\wwwroot","Environment":{""},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}

Dockerfile:

```
# escape=`

FROM mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Add-WindowsFeature Web-Server; `
    Add-WindowsFeature NET-Framework-45-ASPNET; `
    Add-WindowsFeature Web-Asp-Net45; `
    Add-WindowsFeature NET-WCF-TCP-Activation45; `
    Add-WindowsFeature NET-WCF-HTTP-Activation45; `
    Remove-Item -Recurse C:\inetpub\wwwroot\*; `
    Invoke-WebRequest -Uri https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe -OutFile C:\ServiceMonitor.exe

WORKDIR /inetpub/wwwroot

COPY . /inetpub/wwwroot

EXPOSE 80 ` 443

ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]
```
