### ISSUE TITLE
Default bandwidth burst is too large

### ISSUE THREAD

**Issue by liuxu623** [kubernetes/kubernetes#90838]
- Create a test pod with kubernetes.io/ingress-bandwidth and kubernetes.io/egress-bandwidth annotations
```
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf3
  annotations:
    kubernetes.io/ingress-bandwidth: 10M
    kubernetes.io/egress-bandwidth: 10M
spec:
  containers:
  - name: iperf3
    image: networkstatic/iperf3
    args: ['-s']
```
- tc qdisc show
```
...
qdisc tbf 1: dev veth20261d7b root refcnt 2 rate 10Mbit burst 256Mb lat 25.0ms
qdisc ingress ffff: dev veth20261d7b parent ffff:fff1 ----------------
qdisc tbf 1: dev bwp201cb4fbd6ef root refcnt 2 rate 10Mbit burst 256Mb lat 25.0ms
```
- iperf3 test
```
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   238 MBytes  1.99 Gbits/sec    0   8.12 MBytes
[  4]   1.00-2.00   sec  21.2 MBytes   178 Mbits/sec    0   8.12 MBytes
[  4]   2.00-3.00   sec  1.25 MBytes  10.5 Mbits/sec    0   8.12 MBytes
[  4]   3.00-4.00   sec  1.25 MBytes  10.5 Mbits/sec    0   8.12 MBytes
[  4]   4.00-5.00   sec  1.25 MBytes  10.5 Mbits/sec    0   8.12 MBytes
[  4]   5.00-6.00   sec  1.25 MBytes  10.5 Mbits/sec    0   8.12 MBytes
[  4]   6.00-7.00   sec  1.25 MBytes  10.5 Mbits/sec    0   8.12 MBytes
[  4]   7.00-8.00   sec  1.25 MBytes  10.5 Mbits/sec    0   8.12 MBytes
[  4]   8.00-9.00   sec   502 KBytes  4.11 Mbits/sec    0   8.12 MBytes
 
 
[  4]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec    0   8.12 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec   267 MBytes   224 Mbits/sec    0             sender
[  4]   0.00-10.00  sec   262 MBytes   220 Mbits/sec                  receiver
```
We can see that burst is too large, bandwidth limit is `10M` but burst can reach `1.99 Gbits/sec`.
