### ISSUE TITLE
Cannot have two secrets mounted at same path

### ISSUE THREAD

**Issue by tokiwinter** [kubernetes/kubernetes#90862]
Hi,

I want to have two secrets mounted at the same path, e.g:
```
/var/tmp/secret_one
/var/tmp/secret_two
```
I've tried doing this by using:
```
apiVersion: v1
kind: Pod
metadata:
  name: [redacted]
spec:
  containers:
  - name: [redacted]
    image: [redacted]
    ports:
    - containerPort: 389
    - containerPort: 443
    - containerPort: 636
    volumeMounts:
    - name: license-secret
      mountPath: /var/tmp
      readOnly: true
    - name: root-secret
      mountPath: /var/tmp
      readOnly: true
  imagePullSecrets:
  - name: stagingregistry
  volumes:
  - name: license-secret
    secret:
      secretName: key.lic
      defaultMode: 256
  - name: root-secret
    secret:
      secretName: root.txt
      defaultMode: 256
```
But the Pod will not start.
```
% kubectl apply -f datasync-pod.yaml
The Pod "datasync" is invalid: spec.containers[0].volumeMounts[1].mountPath: Invalid value: "/var/tmp": must be unique
```
How do I get two secrets files mounted in the same directory?

Thanks
