### ISSUE TITLE
"error building openapi models" error logged serving CRD containing x-kubernetes-int-or-string

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#90902]
extracted from https://github.com/kubernetes/kubernetes/issues/85127#issuecomment-605890538

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: intorstrings.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: intorstrings
    singular: intorstring
    kind: IntOrString
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        intorstr:
          x-kubernetes-int-or-string: true
---
apiVersion: stable.example.com/v1
kind: IntOrString
metadata:
  name: int
intorstr: 1
---
apiVersion: stable.example.com/v1
kind: IntOrString
metadata:
  name: string
intorstr: "string"
```

produces this log line:

```
customresource_handler.go:652] error building openapi models for intorstrings.stable.example.com: ERROR $root.definitions.com.example.stable.v1.IntOrString.properties.intorstr has invalid property: anyOf
```

/sig api-machinery
/assign @apelisse 
/priority important-soon

The message is a no-op, and means server-side apply for that custom resource falls back to "no schema" mode.
