### ISSUE TITLE
Namespace Resources deleted when invalid annotation applied with force flag

### ISSUE THREAD

**Issue by liamkell** [kubernetes/kubernetes#90968]
**What happened**:
When updating a namespace with an invalid namespace via `kubectl apply --force`
the resources within the namespace are deleted

**What you expected to happen**:
Even with the force flag specified I would not expect an invalid annotation
to result in deletion of resources from a namespace.

**How to reproduce it (as minimally and precisely as possible)**:
#### **`setup.yaml`**
``` 
apiVersion: v1
kind: Namespace
metadata:
  name: test 
---
apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: test
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
```
#### **`namespace_update.yaml`**
``` 
apiVersion: v1
kind: Namespace
metadata:
  name: test 
  annotations:
      ns@example.com/abc: "test"
```

1. `kubectl apply --force -f setup.yaml`
2. `kubectl get pods -n test`
3. `kubectl apply --force -f namespace_update.yaml`
4. `kubectl get pods -n test`

Between steps 2 & 4 the pods in the namespace are deleted and error reported about invalid annotation from step 4

Without the force flag just the error is reported

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `kind`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 18.04.4 LTS`
- Kernel (e.g. `uname -a`): `5.3.0-51-generic`
- Install tools: `kind`
