### ISSUE TITLE
Single instance deployment will be unavailable during eviction

### ISSUE THREAD

**Issue by zhiyu0729** [kubernetes/kubernetes#90977]
**What happened**:
When the pod is evicted, the service is unavailable.
```
NAME         ENDPOINTS           AGE
echoserver   10.244.1.219:8080   176m
echoserver   <none>   178m
echoserver   10.244.3.219:8080   178m
```
If use `PodDisruptionBudget`, Pod can't be evicte.
```
error when evicting pod "echoserver-55c6c59dd5-kg4p4" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod echoserver/echoserver-55c6c59dd5-kg4p4
```

**What you expected to happen**:
* When voluntary disruptions occur, old pods should not be evicted from the `Endpoints`  immediately until the new pod is available.
* If there is only one replicas, Pods should be allowed to be evicted until a new Pod is successfully created and ready.

**How to reproduce it (as minimally and precisely as possible)**:
deploy resource:
```
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - image: gcr.io/google_containers/echoserver:1.0
          imagePullPolicy: Always
          name: echoserver
          ports:
            - containerPort: 8080
  strategy:
    rollingUpdate:
      maxUnavailable: 0
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: echoserver
  type: NodePort
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: echoserver
  namespace: echoserver
spec:
  # minAvailable: 1
  maxUnavailable: 0
  selector:
    matchLabels:
      app: echoserver
```
then `kubectl drain node`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:
