### ISSUE TITLE
kubeadm-flags.env not properly downloaded from master when joining cluster from worker node

### ISSUE THREAD

**Issue by impop** [kubernetes/kubernetes#90984]
## What happened

We have created a cluster with Kubeadm in Azure. Master node successfully created and ready with azure provider
![image](https://user-images.githubusercontent.com/16975749/81578464-c22dfc00-93a2-11ea-8aef-2d631c2cc849.png)

When creating the master with `kubeadm init` the config.yaml was:

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "azure"
    cloud-config: "/etc/kubernetes/cloud.conf"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.18.2
clusterName: k8s-devsandbox
apiServer:
  extraArgs:
    runtime-config: storage.k8s.io/v1=true
    cloud-provider: "azure"
    cloud-config: "/etc/kubernetes/cloud.conf"
    advertise-address: ...
  extraVolumes:
  - name: cloud
    hostPath: "/etc/kubernetes/cloud.conf"
    mountPath: "/etc/kubernetes/cloud.conf"
controllerManager:
  extraArgs:
    cloud-provider: "azure"
    cloud-config: "/etc/kubernetes/cloud.conf"
  extraVolumes:
  - name: cloud
    hostPath: "/etc/kubernetes/cloud.conf"
    mountPath: "/etc/kubernetes/cloud.conf"
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/16"
```

And the resulting `kubeadm-flags.env` is:

```
KUBELET_KUBEADM_ARGS="--cgroup-driver=systemd --cloud-config=/etc/kubernetes/cloud.conf --cloud-provider=azure --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2 --resolv-conf=/run/systemd/resolve/resolv.conf"
```

Then in the worker node we used the `kubeadm join` result of the `kubeadm init` command and the output was:

```
W0511 15:36:15.461164   29864 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet-start] Downloading configuration for the kubelet from the "kubelet-config-1.18" ConfigMap in the kube-system namespace
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...

This node has joined the cluster:
* Certificate signing request was sent to apiserver and a response was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the control-plane to see this node join the cluster.
```

The `kubeadm-flags.env` saved file is (notice it's missing cloud parameters)

```
KUBELET_KUBEADM_ARGS="--cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2 --resolv-conf=/run/systemd/resolve/resolv.conf"
```

The worker node joins the master and gets ready but when we deploy a pod that requires an Azure Disk, for instance, the kubelet sends errors saying that it can't get the Azure provider information.

If we manually change the contexts of `kubeadm-flags.env` in the worker node, replacing it with the contents of the same file from the master and restart the kubelet service, it works.

## What you expected to happen

I would have expected the contents of the kubeadm-flags.env fetched in `kubeadm join` to be the same as those in the master node.

##  How to reproduce it (as minimally and precisely as possible)

I tried to explain this as I explained the 'What happened' section but happy to provide more details.

## Anything else we need to know?

**Environment**:
- Kubernetes version (use `kubectl version`): 

  `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: 
   
   Azure
- OS (e.g: `cat /etc/os-release`):
   
   `NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`
- Kernel (e.g. `uname -a`):

   `Linux k8s-master-devsandbox 5.3.0-1020-azure #21~18.04.1-Ubuntu SMP Wed Apr 15 09:35:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:

   Kubeadm
- Network plugin and version (if this is a network-related bug):

   Flannel (https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml)
- Others:
