### ISSUE TITLE
kubelet "failed to initialize top level QOS containers" on cgroup mount leaks

### ISSUE THREAD

**Issue by chrischdi** [kubernetes/kubernetes#91023]
**What happened**:

Sometimes we can see kubelets stuck in a restarting loop and never getting healthy again.

The kubelet at the end fails with
```
May 08 11:44:36.412182 kube-node01 kubelet[6613]: F0508 11:44:36.412096    6613 kubelet.go:1380] Failed to start ContainerManager failed to initialize top level QOS containers: root container [kubepods] doesn't exist
```

The issue seems to be a leak of mount information from our `csi-nodeplugin` pod. 
The issue is that `/proc/self/mountinfo` contains cgroup mount information from the pod which should not be the case. Because of that the kubelet tries to use the path of the leaked mount as root cgroup, which is wrong.
Because of that the pod/container in `Terminating` did leak cgroup mount information to the host.

Some time later the kubelet had a restart and was not able to recover

**What you expected to happen**:

Kubelet restarts and recovers.

**How to reproduce it (as minimally and precisely as possible)**:

On a node:
```
# create target dummy dir
mkdir -p /run/foo/rootfs/sys/fs/cgroup/systemd
# get a container cgroup dir in /sys/fs/cgroup/systemd/kubepods
POD=$(find /sys/fs/cgroup/systemd/kubepods/ -maxdepth 1 -name "pod*" | head -n 1)
SRCDIR="$POD/$(ls -1 $POD | grep -v -E -e '^cgroup|^notify|^tasks' | head -n 1)"
mount -o bind "$SRCDIR" "/run/foo/rootfs/sys/fs/cgroup/systemd"
systemctl restart kubelet
```

Fix afterwards:
```
umount "/run/foo/rootfs/sys/fs/cgroup/systemd"
```

**Anything else we need to know?**:

I was able to "fix" it by unmounting the leaked cgroups:

```
cat /proc/mounts  | grep cgroup | grep containerd | awk '{print $2}' | grep -v 'cgroup$' | xargs umount
cat /proc/mounts  | grep cgroup | grep containerd | awk '{print $2}' | xargs umount
```

* Maybe related to #49835 
* Could get partially fixed similar to https://github.com/google/cadvisor/pull/1792/files in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/helpers_linux.go#L198

  I did already test that but fixing this resulted in a ready kubelet, not able to reconcile pods:
  ```
  Normal   Created           9s (x2 over 10s)         kubelet, kube-node03  Created container coredns
  Warning  Failed            8s (x2 over 10s)         kubelet, kube-node03  Error: failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"cgroup\\\" to rootfs \\\"/run/containerd/io.containerd.runtime.v1.linux/k8s.io/coredns/rootfs\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /run/foo/rootfs/sys/fs/podf4048c8d-fe5f-42e6-8899-8c9923f99c63/coredns: no such file or directory\\\"\"": unknown
  Warning  BackOff           5s (x3 over 8s)          kubelet, kube-node03  Back-off restarting failed container
  ```
  In this case containerd still fails but I think this needs to be addressed in containerd.

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.5-dirty", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"dirty", BuildDate:"2020-04-17T03:37:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration:
  - Openstack
- OS (e.g: `cat /etc/os-release`):
  ```
  root@kube-node01:~# cat /etc/os-release | grep PRETTY
  PRETTY_NAME="Ubuntu 19.10"
  ```
- Kernel (e.g. `uname -a`): `Linux kube-node01 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
  - cinder csi
- Network plugin and version (if this is a network-related bug):
  - calico-node
- Others:
  - we using `cgroupfs`

Example content of non-working content in `/proc/self/mountinfo`:
On healthy nodes there are no entries having `/run/containerd/io.containerd.runtime.v1.linux/` in the paths
```
root@kube-node01:~# cat /proc/self/mountinfo | grep cgroup
30 21 0:26 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,mode=755
31 30 0:27 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime shared:10 - cgroup2 cgroup2 rw
32 30 0:28 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,xattr,name=systemd
35 30 0:31 / /sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,rdma
36 30 0:32 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,cpu,cpuacct
37 30 0:33 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,freezer
38 30 0:34 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,blkio
39 30 0:35 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,pids
40 30 0:36 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,cpuset
41 30 0:37 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,memory
42 30 0:38 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,net_cls,net_prio
43 30 0:39 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:23 - cgroup cgroup rw,hugetlb
44 30 0:40 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:24 - cgroup cgroup rw,perf_event
45 30 0:41 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:25 - cgroup cgroup rw,devices
945 25 0:159 / /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup rw,nosuid,nodev,noexec,relatime shared:606 - tmpfs tmpfs rw,mode=755
979 945 0:28 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,xattr,name=systemd
1471 945 0:31 / /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,rdma
1696 945 0:32 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,cpu,cpuacct
1714 945 0:33 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,freezer
2099 945 0:34 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,blkio
2345 945 0:35 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,pids
2390 945 0:36 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,cpuset
2409 945 0:37 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,memory
2428 945 0:38 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,net_cls,net_prio
2447 945 0:39 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:23 - cgroup cgroup rw,hugetlb
2466 945 0:40 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:24 - cgroup cgroup rw,perf_event
2485 945 0:41 /kubepods/pod2eb4976a-5001-4c2b-b5cf-df562549e3d4/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c /run/containerd/io.containerd.runtime.v1.linux/k8s.io/2e75a956e9db372ddf40ef4c32d148100010386140238c6173ad6e4d45fd8e1c/rootfs/sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:25 - cgroup cgroup rw,devices
```

**Comment by chrischdi** [comment]
Example patch for kubelet similar to cadvisor:
```
diff --git a/pkg/kubelet/cm/helpers_linux.go b/pkg/kubelet/cm/helpers_linux.go
index ce2d9a9670f..1f53aa20cb1 100644
--- a/pkg/kubelet/cm/helpers_linux.go
+++ b/pkg/kubelet/cm/helpers_linux.go
@@ -197,6 +197,10 @@ func getCgroupSubsystemsV1() (*CgroupSubsystems, error) {
        mountPoints := make(map[string]string, len(allCgroups))
        for _, mount := range allCgroups {
                for _, subsystem := range mount.Subsystems {
+                       if _, ok := mountPoints[subsystem]; ok {
+                               // duplicate mount for this subsystem; use the first one we saw
+                               continue
+                       }
                        mountPoints[subsystem] = mount.Mountpoint
                }
        }
```

**Comment by chrischdi** [comment]
> ```
> The issue is that /proc/
> ```
> 
> the sentence seems to be incomplete.

Thank you and sorry for that :-( I've added the missing part :+1:

**Comment by chrischdi** [comment]
I am able to reproduce the problem more often using the following setup (I'm not able to say exactly when it happens):

* csi cinder nodeplugin deployed including livenessprobe
* the problem occurs more often when using csi livenessprobe v1.1.0
* continously delete the csi pod if ready and start-stopping the kubelet for some time.

Example script: (requires kubeconfig and ssh access to the node
```sh
export KUBECONFIG=/etc/kubernetes/admin.conf
NODE=my-nodename
SSH_NODE=user@$NODE
function IsContainerReady {
  #if [[ "$(kubectl get po -n kube-system -l app=csi-nodeplugin-cinderplugin -o json | jq '.items[] | select(.metadata.deletionTimestamp == null) | select(.spec.nodeName == "'${NODE}'") | .status.containerStatuses[] | .ready' | base64)" == "tdHJ1ZQp0cnVlCg==" ]]; then
  if [[ "$(kubectl get po -n kube-system -l app=csi-nodeplugin-cinderplugin -o json | jq '.items[] | select(.metadata.deletionTimestamp == null) | select(.spec.nodeName == "'${NODE}'") | .status.containerStatuses[] | .ready' | base64)" == "dHJ1ZQp0cnVlCnRydWUK" ]]; then
    echo "true"
  else 
    echo "false"
  fi
}

function deletePod {
  kubectl delete po --wait=false -n kube-system $(kubectl get po -n kube-system -l app=csi-nodeplugin-cinderplugin -o wide | grep $NODE | awk '{print $1}')
  kubectl get po -n default -o wide --no-headers | grep test-statefulset | grep ${NODE} | awk '{print $1}' | xargs kubectl delete po -n default --wait=false
}

function loop {
  START=$(date)
  while [[ $(ssh "${SSH_NODE}" sudo cat /proc/self/mountinfo | grep cgroup | grep kubepods | wc -l) -eq 0 ]]; do
    # check if the pod is currently healthy
    if [[ "$(IsContainerReady)" == "true" ]]; then
      echo "deleting the pod"
      deletePod
    fi
    SLEEP_TIMER=22
    echo starting kubelet, sleep $SLEEP_TIMER, stop kubelet
    ssh ${SSH_NODE} -- bash -c "echo ''; sudo systemctl start kubelet; sleep $SLEEP_TIMER; sudo systemctl stop kubelet"
    echo iteration done
  done

  echo "Start: ${START}"
  echo "End:   $(date)"
  echo "  fix via reboot or \`sudo cat /proc/self/mountinfo | grep cgroup | grep containerd | awk '{print $5}'  | xargs sudo umount\`"
}

loop
```

The csi daemonset:
```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-nodeplugin-cinderplugin
  namespace: kube-system
  labels:
    app: csi-nodeplugin-cinderplugin
spec:
  selector:
    matchLabels:
      app: csi-nodeplugin-cinderplugin
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: csi-nodeplugin-cinderplugin
    spec:
      serviceAccount: csi-cinder-node-sa
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      hostNetwork: true
      # hostPID is required to perform systemd-run mount
      hostPID: true
      priorityClassName: system-node-critical
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
          args:
            - "--v=4"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/cinder.csi.openstack.org /registration/cinder.csi.openstack.org-reg.sock"]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/cinder.csi.openstack.org/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              cpu: 100m
              memory: 30Mi
            limits:
              cpu: 100m
              memory: 30Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: csi-nodeplugin-cinder
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: docker.io/k8scloudprovider/cinder-csi-plugin:v1.17.0
          imagePullPolicy: "IfNotPresent"
          args :
            - /bin/cinder-csi-plugin
            - "--v=4"
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--cloud-config=$(CLOUD_CONFIG)"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: CLOUD_CONFIG
              value: /etc/config/cloud.conf
          resources:
            requests:
              cpu: 100m
              memory: 40Mi
            limits:
              cpu: 100m
              memory: 40Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: pods-cloud-data
              mountPath: /var/lib/cloud/data
              readOnly: true
            - name: pods-probe-dir
              mountPath: /dev
              mountPropagation: "HostToContainer"
            - name: etc
              subPath: cloud.conf
              mountPath: /etc/config/cloud.conf
              readOnly: true
            - mountPath: /etc/ssl
              name: etc
              readOnly: true
              subPath: ssl
          ports:
          - containerPort: 9098
            name: healthz
            protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
        # The livenessProbe itself is set on the container with the CSI driver.
        # This way, Kubernetes restarts the CSI driver container when the
        # probe fails. The liveness probe sidecar container only provides the
        # HTTP endpoint for the probe and does not contain livenessProbe 
        # section by itself.
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v1.1.0
          args:
          - --csi-address=/csi/csi.sock
          - --health-port=9098
          - -v=4
          resources:
            requests:
              cpu: 100m
              memory: 15Mi
            limits:
              cpu: 100m
              memory: 15Mi
          volumeMounts:
          - name: socket-dir
            mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/cinder.csi.openstack.org
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: pods-cloud-data
          hostPath:
            path: /var/lib/cloud/data
            type: DirectoryOrCreate
        - name: pods-probe-dir
          hostPath:
            path: /dev
            type: Directory
        - hostPath:
            path: /etc
          name: etc
        - hostPath:
            path: /var/run/dbus
          name: dbus

```
