### ISSUE TITLE
CRD invalid field validations return empty values

### ISSUE THREAD

**Issue by gautierdelorme** [kubernetes/kubernetes#91114]
**What happened**:

I created a custom resource definition with a pattern (regex) validation. Then, I created a custom resource with invalid fields and it failed with an empty value in validation error details.

```
The Foo "foo" is invalid: field: Invalid value: "": field in body should match '[a-z]'
```

**What you expected to happen**:

The creation of custom resources with invalid fields should fail with given (invalid) values in validation error details:

```
The Foo "foo" is invalid: field: Invalid value: "A": field in body should match '[a-z]'
```

**How to reproduce it (as minimally and precisely as possible)**:

- Create a Custom Resource Definition with at least one field validated against a pattern
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.k8s.invalid
spec:
  group: k8s.invalid
  version: v1
  scope: Namespaced
  names:
    plural: foos
    singular: foo
    kind: Foo
  validation:
    openAPIV3Schema:
      properties:
        field:
          type: string
          pattern: '[a-z]'
```
- Create a Custom Resource with an invalid field
```yaml
apiVersion: "k8s.invalid/v1"
kind: Foo
metadata:
  name: foo
field: A
```

**Anything else we need to know?**:

Looking at how we get the value in https://github.com/kubernetes/kubernetes/blob/896b77ed5363259d9d3978664d61a98dc4bdf406/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation.go#L83-L86 it seems like a fix could be done in `go-openapi`:

```diff
diff --git a/github.com/go-openapi/errors/schema.go b/github.com/go-openapi/errors/schema.go
index 14fb2c5f116..4c601bed947 100644
--- a/github.com/go-openapi/errors/schema.go
+++ b/github.com/go-openapi/errors/schema.go
@@ -533,7 +533,7 @@ func TooShort(name, in string, min int64) *Validation {
 
 // FailedPattern error for when a string fails a regex pattern match
 // the pattern that is returned is the ECMA syntax version of the pattern not the golang version.
-func FailedPattern(name, in, pattern string) *Validation {
+func FailedPattern(name, in, pattern string, value interface{}) *Validation {
        var msg string
        if in == "" {
                msg = fmt.Sprintf(patternFailNoIn, name, pattern)
@@ -545,6 +545,7 @@ func FailedPattern(name, in, pattern string) *Validation {
                code:    PatternFailCode,
                Name:    name,
                In:      in,
+               Value:   value,
                message: msg,
        }
 }
```
```diff
diff --git a/github.com/go-openapi/validate/values.go b/github.com/go-openapi/validate/values.go
index 3e644aea868..24748026548 100644
--- a/github.com/go-openapi/validate/values.go
+++ b/github.com/go-openapi/validate/values.go
@@ -141,10 +141,10 @@ func RequiredNumber(path, in string, data float64) *errors.Validation {
 func Pattern(path, in, data, pattern string) *errors.Validation {
        re, err := compileRegexp(pattern)
        if err != nil {
-               return errors.FailedPattern(path, in, fmt.Sprintf("%s, but pattern is invalid: %s", pattern, err.Error()))
+               return errors.FailedPattern(path, in, fmt.Sprintf("%s, but pattern is invalid: %s", pattern, err.Error()), data)
        }
        if !re.MatchString(data) {
-               return errors.FailedPattern(path, in, pattern)
+               return errors.FailedPattern(path, in, pattern, data)
        }
        return nil
 }
```

But I would like to understand what we actually expect from this `Value` field defined in `go-openapi`? Should it really be the value provided by users? If yes, then - for example - why when using a `Minimum` validation the value is set to the integer we match the input against: https://github.com/go-openapi/errors/blob/master/schema.go#L444. If no, then maybe we shouldn't expose the `Value` field that way on the K8s side because it is confusing to users reading the error.

**Environment**:
- Kubernetes version: I was able to reproduce it from `master` and previous versions.
