### ISSUE TITLE
hostAliases not work in Windows pod

### ISSUE THREAD

**Issue by ylhyh** [kubernetes/kubernetes#91132]
**What happened**:
spec.hostAliases do not work in Windows pod

**What you expected to happen**:
It's able to use spec.hostAliases add entry to "c:\windows\system32\drivers\etc\hosts"

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Windows pod with hostAliases settings:
```
apiVersion: v1
kind: Pod
metadata:
  name: hosts-example
  namespace: default
  labels:
    app: hosts-example
...
      hostAliases:
      - hostnames:
        - host.example.com
        ip: 172.16.126.238
...
```
2. Check c:\windows\system32\drivers\etc\hosts in Windows pod, entry "172.16.126.238 host.example.com" not add to hosts file.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.8

- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): 
   - Host: Microsoft Windows [Version 10.0.17763.1158]
   - Container: Microsoft Windows [Version 10.0.17763.1158]
- Kernel (e.g. `uname -a`): Microsoft Windows [Version 10.0.17763.1158]
- Install tools:
- Network plugin and version (if this is a network-related bug): win-bridge 0.8.5
- Others:

**Comment by athenabot** [comment]
/sig windows

These SIGs are my best guesses for this issue. Please comment `/remove-sig <name>` if I am incorrect about one.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by wawa0210** [comment]
The Windows container does not seem to support directly specifying hostalias through the container command

**Comment by tal47** [comment]
Doesn't work on version: v1.18.8 either.

**Comment by vvotekeb** [comment]
it still doesn't work in version 1.21

**Comment by leblancmeneses** [comment]
workaround:

if static add to your Docker image, if dynamic use a lifecycle hook

  ```
          lifecycle:
            postStart:
              exec:
                command: ["powershell", "c:/configmount/on.start.ps1"]
  ```
                
  ```Add-Content -Path $env:windir\System32\drivers\etc\hosts -Value "`n192.168.1.11`txyz.local" -Force; ```
