### ISSUE TITLE
Infinite drain with terminating pod with node affinity and PDB

### ISSUE THREAD

**Issue by balous** [kubernetes/kubernetes#91141]
**What happened**:
I've set up two resources:
- a statefulset with two replicas, node affinity to two nodes and pod antiaffinity to itself. The pods take some time to terminate. 
- a pod distruption budget requiring one replica of the statefulset to be present

(this is just a stripped down scenario of what we observe in production cluster)

Then I've proceeded with two steps:

1) kill one of the pods
2) immediately drain the node it runs on

The drain lasts forever:
```
root@kubernetes-master-bionic:~# kubectl delete pod ss-1
pod "ss-1" deleted
^C
root@kubernetes-master-bionic:~# kubectl drain kubernetes-node1-bionic --ignore-daemonsets --force --delete-local-data
node/kubernetes-node1-bionic cordoned
WARNING: ignoring DaemonSet-managed Pods: kube-system/calico-node-q2p92, kube-system/kube-proxy-d66lz
evicting pod "ss-1"
error when evicting pod "ss-1" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod "ss-1"
error when evicting pod "ss-1" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod "ss-1"
error when evicting pod "ss-1" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
evicting pod "ss-1"
error when evicting pod "ss-1" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
```

**What you expected to happen**:
The drain should finish the same way it would finish without the terminating pod on the node.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
  name: ss
spec:
  podManagementPolicy: Parallel
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ss
  serviceName: ss
  template:
    metadata:
      labels:
        app: ss
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kubernetes-node2-bionic
                - kubernetes-node1-bionic
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ss
            topologyKey: "kubernetes.io/hostname"
      containers:
      - args:
        - -f
        - /dev/null
        command: ["/usr/bin/tail"]
        image: debian
        name: debian
      terminationGracePeriodSeconds: 30
```

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ss-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ss
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
root@kubernetes-master-bionic:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
  - Virtualbox VMs, one master + two nodes, 2 CPUs + 2G ram
  - reproducible also in a cluster where we install official k8s binaries on bare metal servers

- OS (e.g: `cat /etc/os-release`):
```
root@kubernetes-master-bionic:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux kubernetes-master-bionic 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
`kubeadm` - originally installed as 1.14.8, than upgraded up to 1.18.2

- Network plugin and version (if this is a network-related bug):
calico

- Others:
