### ISSUE TITLE
Generalized form of `x-kubernetes-int-or-string` for CRD validation

### ISSUE THREAD

**Issue by alexec** [kubernetes/kubernetes#91153]
**What would you like to be added**:

I'd like to have CRD validation, but one array type can be anything. It seems that this is not allowed.

I don't think that `x-kubernetes-int-or-string`does not work for array types.

```
spec.validation.openAPIV3Schema.properties[spec].properties[templates].items.properties[steps].items.items.properties[withItems].items.type: Required value: must not be empty for specified array items
```

**Why is this needed**:

To allow arbitrary types

**Comment by liggitt** [comment]
here's how you can use x-kubernetes-int-or-string in an array:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arrayintorstrings.example.com
spec:
  group: example.com
  scope: Cluster
  names:
    plural: arrayintorstrings
    singular: arrayintorstring
    kind: ArrayIntOrString
    listKind: ArrayIntOrStringList
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          vars:
            type: array
            items:
              x-kubernetes-int-or-string: true
---
apiVersion: example.com/v1
kind: ArrayIntOrString
metadata:
  name: valid
vars:
- 1
- "a"
---
apiVersion: example.com/v1
kind: ArrayIntOrString
metadata:
  name: invalid
vars:
- 1
- "a"
- true
```

demonstrating the validation is effective:

```
kubectl apply -f array-int-or-string.yaml 
```

```
customresourcedefinition.apiextensions.k8s.io/arrayintorstrings.example.com configured
arrayintorstring.example.com/valid created
The ArrayIntOrString "invalid" is invalid: vars: Invalid value: "boolean": vars in body must be of type integer,string: "boolean"
```

**Comment by liggitt** [comment]
to define an array that allows items to be of any type, you can do this:

```yaml
type: array
items:
  x-kubernetes-preserve-unknown-fields: true
```
