### ISSUE TITLE
TopologySpreadConstraints does not work with non-standard topology keys on Kubernetes 1.18.0.beta-2

### ISSUE THREAD

**Issue by lenhattan86** [kubernetes/kubernetes#91152]
**What happened**:
We cannot limit the number of pods of a statefulset per zone using TopologySpreadConstraints (https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/).

**What you expected to happen**:
we can limit the number of pods on each zone using MaxSkew.

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a single node cluster. Then label the node as zone=1

2) Create a 2-pod statefulset that has https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/ in the pod template.

Example of statefulset: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
We just add topology constraint into the pod template:
```
...
  spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx
     containers:
...
```

Submit the statefulset.

Actual result: 2 pods are running on the same node (zone).
Expected result: 1 pod is running & 1 pod is pending.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.0-beta.2
- Cloud provider or hardware configuration: Kind
- OS (e.g: `cat /etc/os-release`): MacOS 10.14.6
- Kernel (e.g. `uname -a`): Darwin Kernel Version 18.7.0
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
