### ISSUE TITLE
VolumeSource in Kubernetes does not support StorageClass

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#91208]
Based on source code here https://github.com/kubernetes/api/blob/master/core/v1/types.go#L51-L159 , seems I cannot specify a `StorageClass` when using `VolumeSource`.

Like the YAML file as below:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-block-volume
spec:
  containers:
    - name: fc-container
      image: fedora:26
      command: ["/bin/sh", "-c"]
      args: [ "tail -f /dev/null" ]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: block-pvc
```

I was not able to set a `storageclass` for my `persistentVolumeClaim`, any comments for this? Thanks.

/sig storage
