### ISSUE TITLE
kubectl get HPA using autoscaling/v2beta2

### ISSUE THREAD

**Issue by lechen26** [kubernetes/kubernetes#91219]
Hi

i'm having issues to get the right TARGETS fields when using averageValue on HPA.

i have an HPA configured using version autoscaling/v2beta2 which looks like the following:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: rabbitmq_core_queue_messages_ready
        selector: {matchLabels: {queue: test2, namespace: default}}
      describedObject:
        kind: Service
        name: rabbitmq
      target:
        type: AverageValue
        averageValue: 3
```

the sample-app is indeed scaled up/down based on the queue length.
the thing is, the output for `kubect get hpa` is:
```
NAME         REFERENCE               TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
sample-app   Deployment/sample-app   0/0       1         10        1          2m45s
````

while when describing it using `kubectl describe hpa sample-app` i do get the right data:
```
Metrics:                                                                                        ( current / target )
  "rabbitmq_core_queue_messages_ready" on Service/rabbitmq(target average value):  1 / 3
```

when switching to regular value instead of average i do see it on the get command but it doesnt acts as i want it to be.

what am i missing?

thanks,
chen
