### ISSUE TITLE
scheduler: do not respect topology spread constraints even when satisfiable

### ISSUE THREAD

**Issue by llamerada-jp** [kubernetes/kubernetes#91234]
**What happened**:

kube-scheduler gives up too easily to satisfy topology spread constraints
under the following conditions:

- All constraints are `whenUnsatisfiable: ScheduleAnyway`.
- There are some CPU consuming pods already.
- Topology spread constraints can be satisfied.

although the specification clearly says ["whenUnsatisfiable indicates how to deal with a Pod if it doesn’t satisfy the spread constraint"](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#api).

**What you expected to happen**:

kube-scheduler satisfies all topology spread constraints when they can be satisfied.

**How to reproduce it (as minimally and precisely as possible)**:

1. Make a cluster using `kind`(v0.8.1) with the configuration below.
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
```
2. Create a pod that CPU consuming with the manifest below.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: addload
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addload
  template:
    metadata:
      labels:
        app: addload
    spec:
      containers:
      - name: spread-test-ubuntu
        image: ubuntu:latest
        command: ["sleep", "infinity"]
        resources:
          requests:
            cpu: "25" # The place to change according to the number of node CPUs.
```
3. Create target pods with the manifest below.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spread-test-0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spread-test-ubuntu
  template:
    metadata:
      labels:
        app: spread-test-ubuntu
    spec:
      containers:
      - name: spread-test-ubuntu
        image: ubuntu:latest
        command: ["sleep", "infinity"]
      topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - spread-test-ubuntu
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
```

We show the result below at `kind` environment.
- `addload` pod requires 25 for CPU resources.
  - In my environment, node has 28 CPUs.
  - `addload` pod was placed at worker2.
- Two target pods were placed in the same worker, avoiding worker2, as shown below.
```
$ kubectl get pod -o wide
NAME                             READY   STATUS    RESTARTS   AGE     IP           NODE                      NOMINATED NODE   READINESS GATES
addload-7bd85d975b-6tfmc         1/1     Running   0          5m24s   10.244.1.3   spreadtest-kind-worker2   <none>           <none>
spread-test-0-6dfb6d4965-q7tpx   1/1     Running   0          4m56s   10.244.3.4   spreadtest-kind-worker    <none>           <none>
spread-test-0-6dfb6d4965-v8dgj   1/1     Running   0          4m56s   10.244.3.5   spreadtest-kind-worker    <none>           <none>
spread-test-0-6dfb6d4965-vbz7l   1/1     Running   0          4m56s   10.244.2.3   spreadtest-kind-worker3   <none>           <none>
```

- When set `DoNotSchedule` as the value of `whenUnsatisfiable`, the pod was placed in woker2 as follows.

```
$ kubectl get pod -o wide
NAME                            READY   STATUS    RESTARTS   AGE    IP            NODE                      NOMINATED NODE   READINESS GATES
addload-7bd85d975b-6tfmc        1/1     Running   0          18m    10.244.1.3    spreadtest-kind-worker2   <none>           <none>
spread-test-0-9d4ff995b-4kgwf   1/1     Running   0          102s   10.244.1.4    spreadtest-kind-worker2   <none>           <none>
spread-test-0-9d4ff995b-8hwrh   1/1     Running   0          102s   10.244.2.14   spreadtest-kind-worker3   <none>           <none>
spread-test-0-9d4ff995b-jdfvd   1/1     Running   0          102s   10.244.3.11   spreadtest-kind-worker    <none>           <none>
```

**Anything else we need to know?**:

The root cause of this is that kube-scheduler ignores constraints with `ScheduleAnyway` in the predicate filters ([source code](https://github.com/kubernetes/kubernetes/blob/1e2ddd12616064ea406757f58efa4a9a087f4f1d/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L208)).

We created a PoC patch for release-1.17 branch: https://github.com/ymmt2005/kubernetes/commit/b45c2bf5779490225a7aa9a7164703ccb5a24641

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-05-15T07:44:21Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Kind
```
kind v0.8.1 go1.13.9 linux/amd64
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux neco-r640 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Huang-Wei** [comment]
@llamerada-jp This is not a bug.

- `whenUnsatisfiable: ScheduleAnyway` means it's a SOFT requirement. It can be satisfied or not.
- `whenUnsatisfiable: DoNotSchedule` means it's a HARD requirement, it must be satisfied; otherwise the Pod won't be scheduled.
- if you have `M` hard requirements along with `N` soft requirements. `M` hard requirements must be ALL satisfied. After that, `N` soft requirements will be applied and finally come up with a final node to place the pod.

**Comment by llamerada-jp** [comment]
Okay, so it's not a bug, but I think it is very confusing because the
`whenUnsatisfiable` stanza sounds like that the condition will be
applied only when the constraints cannot be satisfied.

Instead of renaming the stanza, I would like to propose an improvement
for kube-scheduler to make it try harder to satisfy soft constraints too.
We made [a proof-of-concept patch](https://github.com/ymmt2005/kubernetes/commit/b45c2bf5779490225a7aa9a7164703ccb5a24641) and verified that the patched kube-scheduler
can spread pods better.

The background is that we saw our pods were really badly scheduled.
We tried to spread pods across 41 nodes.  We could not specify `DoNotSchedule` 
because there are uneven existing workloads.  So, we used `ScheduleAnyway`
hoping that the scheduler would try to satisfy the constraints and if and only
if it could not satisfy them, minimize the skew.

However, the pods were scheduled onto only 4 nodes as shown below.

```
$ kubectl get pods -o wide | grep PODNAME | awk '{ print $7 }' | sort | uniq -c
    5 10.69.0.14
    5 10.69.0.15
    5 10.69.1.133
    5 10.69.1.140
```

We checked the CPU and memory usage of the nodes where the pods are located and those where they are not.
The difference was only a few percents, as shown below.

The node where the pots are located (10.69.0.14):
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests      Limits
  --------           --------      ------
  cpu                24600m (87%)  24 (85%)
  memory             24746Mi (4%)  24846Mi (4%)
  ephemeral-storage  0 (0%)        0 (0%)
```

The node where the pots are not located(10.69.0.18):
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests       Limits
  --------           --------       ------
  cpu                26500m (94%)   26 (92%)
  memory             90212Mi (17%)  90212Mi (17%)
  ephemeral-storage  0 (0%)         0 (0%)
```

We think scheduling as described above is not optimal.

**Comment by Huang-Wei** [comment]
@llamerada-jp Thanks for the feedback.

There are quite a lot of Scoring plugins that work together to score each qualified node (which passed Filtering plugins), so it's likely the PodTopologySpread Score plugin's efforts get diluted - which is not surprising, given that we give each Score plugin a default weight 1.

One option is to try giving a larger weight (e.g., 500) to this plugin - what you need to do is to provide a customized config yaml passing to scheduler binary. You can different ways to configure the weight:
- if you're at k8s version < 1.18, you have to use [scheduling policies](https://kubernetes.io/docs/reference/scheduling/policies/)
- if you're at k8s version >= 1.18, you can use [scheduling profiles](https://kubernetes.io/docs/reference/scheduling/profiles/)

On the other hand, in 1.19, @alculquicondor is optimizing the Score formula of PodTopologySpread to make it more optimal, and also we're considering giving a slightly larger default weight to this plugin. But again, it won't happen until 1.19.

**Comment by alculquicondor** [comment]
All the improvements to PodTopologySpread score are already in master.
We are also doubling the score by default #91258

Any chance you can give a try to this new setup? I did a lot of simulations to make sure the changes were good enough, but real world feedback is very useful.

**Comment by alculquicondor** [comment]
We are also updating the documentation to reflect the true nature of `ScheduleAnyway` parameter, as the current wording is confusing.

**Comment by ahg-g** [comment]
Thanks @llamerada-jp for the feedback. As Aldo and Wei said, we did identify that the original scoring function for topology spread didn't provide enough differentiation between nodes, this should improve in 1.19. Also, increasing the weight significantly should give you the semantics you are looking for.

I agree that the ```ScheduleAnyway``` semantics are confusing, I wish we can change the ```whenUnsatisfiable``` stanza, but I think it is too late, and so the best we can do is clarify in the documentation.

**Comment by llamerada-jp** [comment]
Thank you very much @Huang-Wei @alculquicondor  @ahg-g @draveness .
I'm going to evaluate 1.19 and will feed back.

**Comment by llamerada-jp** [comment]
Hi, @Huang-Wei @alculquicondor @ahg-g

We examined under conditions close to the real environment, but topology spread constraints did not work.
I'm sure it's possible to make adjustments using weight, but I'd like to propose improving it to be as satisfy as possible like [the PoC patch](https://github.com/ymmt2005/kubernetes/commit/b45c2bf5779490225a7aa9a7164703ccb5a24641), or propose adding a new option to schedule like it.

In our actual environment, we set `ScheduleAnyway` as the value of `whenUnsatisfiable` for both zone(We use the zone label to mark racks) and hostname like below.
Other conditions at the experiment are as follows.
- There are 41 nodes.
- Assigned 14 nodes to rack0, 12 nodes to rack1, and 15 nodes to rack2.
- First, we placed 30 pods to load (`addload` pod).
- Next, we placed 20 pods with `topologySpreadConstraints` settings (`spread-test-ubuntu` pod).

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spread-test-0
  namespace: sandbox
spec:
  replicas: 20
  selector:
    matchLabels:
      app: spread-test-ubuntu
  template:
    metadata:
      labels:
        app: spread-test-ubuntu
    spec:
      containers:
      - name: spread-test-ubuntu
        image: quay.io/cybozu/testhttpd:0
      topologySpreadConstraints:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - spread-test-ubuntu
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - spread-test-ubuntu
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
```

The following list is the node where the target(`spread-test-ubuntu`) pods were located.
Avoiding `addload` pods, target pods were not spread for the entire 41 nodes. And multiple pods were placed on the same node.

```
      2 spreadtest-kind-41-worker
      2 spreadtest-kind-41-worker19
      2 spreadtest-kind-41-worker2
      2 spreadtest-kind-41-worker22
      1 spreadtest-kind-41-worker24
      2 spreadtest-kind-41-worker25
      1 spreadtest-kind-41-worker26
      2 spreadtest-kind-41-worker31
      3 spreadtest-kind-41-worker32
      1 spreadtest-kind-41-worker4
      2 spreadtest-kind-41-worker7
```

The following list is the node where the target `addload` pods were located.

```
      1 spreadtest-kind-41-worker10
      1 spreadtest-kind-41-worker11
      1 spreadtest-kind-41-worker12
      1 spreadtest-kind-41-worker13
      1 spreadtest-kind-41-worker14
      1 spreadtest-kind-41-worker15
      1 spreadtest-kind-41-worker16
      1 spreadtest-kind-41-worker17
      1 spreadtest-kind-41-worker18
      1 spreadtest-kind-41-worker20
      1 spreadtest-kind-41-worker21
      1 spreadtest-kind-41-worker23
      1 spreadtest-kind-41-worker27
      1 spreadtest-kind-41-worker28
      1 spreadtest-kind-41-worker29
      1 spreadtest-kind-41-worker3
      1 spreadtest-kind-41-worker30
      1 spreadtest-kind-41-worker33
      1 spreadtest-kind-41-worker34
      1 spreadtest-kind-41-worker35
      1 spreadtest-kind-41-worker36
      1 spreadtest-kind-41-worker37
      1 spreadtest-kind-41-worker38
      1 spreadtest-kind-41-worker39
      1 spreadtest-kind-41-worker40
      1 spreadtest-kind-41-worker41
      1 spreadtest-kind-41-worker5
      1 spreadtest-kind-41-worker6
      1 spreadtest-kind-41-worker8
      1 spreadtest-kind-41-worker9
```

**Comment by llamerada-jp** [comment]
I can submit an elaborated patch if you agree the direction.

**Comment by llamerada-jp** [comment]
By the way, we are trying additional examination to change scoring weight on Kubernetes 1.19.
I applied the following settings for kube-scheduler option, but an error occurred. I would like to ask you how to set it up correctly.

```
apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
  - schedulerName: default-scheduler
    plugins:
      score:
        enabled:
        - name: PodTopologySpread
          weight: 10
```

kube-scheduler terminated with the following log.

```
I0521 07:18:42.268232       1 registry.go:150] Registering EvenPodsSpread predicate and priority function
couldn't create scheduler using provider "DefaultProvider": initializing profiles: creating profile for scheduler name default-scheduler: plugin "PodTopologySpread" already registered as "ScorePlugin"
```

**Comment by alculquicondor** [comment]
> We examined under conditions close to the real environment, but topology spread constraints did not work.

As we already mentioned, the interpretation of `ScheduleAnyway` is wrong and this was on us when choosing the wording 😞 . This is just a score, and there are other scores in play. For example, NodeResourcesLeastAllocated and ImageLocality (although this one should give 0 for this case, given that the image is small). Another one worth considering is BalancedAllocation. Are your nodes homogeneous? I also noticed that your zones are not even. Could you annotate your examples in https://github.com/kubernetes/kubernetes/issues/91234#issuecomment-631919896 with the rack numbers so I can understand better what happened?

Note that the scheduler assumes all scores as roughly equally important. So if it sees that a certain score is particularly high for a node, it will favor it, even if spreading is not satisfied.

I'm actually a bit surprised that you obtained better spreading when having the 30 big pods. Are you using `--algorithm-provider`?

> I can submit an elaborated patch if you agree the direction.

I don't think you can do that since 1.17. We have changed the paradigm of Filters (previously called predicates) in a way that a decision for a node is taken locally. That wouldn't be the case for your proposal.

If you are kind to take a look if it's possible, we can consider it. But we would need a third "whenUnsatisfiable" option, as the change of semantics is radical.

> By the way, we are trying additional examination to change scoring weight on Kubernetes 1.19.
I applied the following settings for kube-scheduler option, but an error occurred. I would like to ask you how to set it up correctly.

You have to disable the existing configuration first.

```
apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
  - schedulerName: default-scheduler
    plugins:
      score:
        disabled:
        - name: PodTopologySpread
        enabled:
        - name: PodTopologySpread
          weight: 10
```
