### ISSUE TITLE
PVs created for StatefulSets don’t obey node affinity rules

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#91299]
**What happened**:

We have created a multizone GKE cluster with 9 nodes (3 per zone). Zones are: us-east1-b, us-east1-c, us-east1-d

Now, we have created a [StatefulSet](https://gist.github.com/lubars/2abb6754b3916665a66fb6fc1644f697#file-iris-data-0-yaml) with the following affinity rules:

```yaml
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - us-east1-b
            - us-east1-c
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              intersystems.com/component: data
              intersystems.com/kind: IrisCluster
              intersystems.com/name: iris
              intersystems.com/role: iris
              intersystems.com/shard: "0"
          namespaces:
          - default
          topologyKey: kubernetes.io/hostname
        weight: 100
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              intersystems.com/component: data
              intersystems.com/kind: IrisCluster
              intersystems.com/name: iris
              intersystems.com/role: iris
              intersystems.com/shard: "0"
          namespaces:
          - default
          topologyKey: failure-domain.beta.kubernetes.io/zone
        weight: 50
```

and volumes

```yaml
  volumes:
  - name: iris-data
    persistentVolumeClaim:
      claimName: iris-data-iris-data-0-1
```

This has created a [PVC](https://gist.github.com/lubars/2abb6754b3916665a66fb6fc1644f697#file-iris-data-iris-data-0-1-yaml) and [PV](https://gist.github.com/lubars/2abb6754b3916665a66fb6fc1644f697#file-pvc-5497dce3-0b5b-4224-8134-c3ffc842d495-yaml). The issue is that the auto generated PV has the following `nodeAffinity` spec:

```yaml
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-east1-d
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-east1
```

The result of this is that the StatefulSet pod fails to start with the following error:

`0/9 nodes are available: 3 node(s) didn't match node selector, 6 node(s) had volume node affinity conflict.`

**What you expected to happen**:

I expected the `nodeAffinity` terms on the PV to use either zone `us-east1-b` or `us-east1-c` as those are the required zones for StatefulSet.

**How to reproduce it (as minimally and precisely as possible)**:

You can see a 3 min youtube video showing the issue: https://youtu.be/lE_Lx_Jn_B4
Here are the YAML files and logs in a Github Gist: https://gist.github.com/lubars/2abb6754b3916665a66fb6fc1644f697

We are able to reproduce this issue reliability on GKE.

**Anything else we need to know?**:
This StatefulSet has 2 replicas. We noticed that the first replica always goes to us-east1-c and starts correctly. The 2nd pod's PV gets created in zone `us-east1-d` and fails to start.

**Environment**:
- Kubernetes version (use `kubectl version`):
We have tested against latest 1.14, 1.15 and 1.17 versions available on GKE.

- Cloud provider or hardware configuration: GKE

- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/sig storage
