### ISSUE TITLE
kubernetes prestop hook is allowed to run only commands

### ISSUE THREAD

**Issue by sshankaregowda** [kubernetes/kubernetes#91326]
I have a deployment template as below. but the prestop hook is never been executed at all. the idea here is set the zookeeper node offline before the pod is terminated.

I am running kubectl rollout to restart the pods. and old pod is when it terminates the prestop is not run. could someone please check whats wrong ?

I looked at the kubectl describe pod but it just shows (Reason: Killing) Message: stopping se and stopping pe-1 . Basically how its prestop executed in case of successful stop ? I need this feature because the zookeeper is involved here and the api connects to zookeeper to send the requests.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcd
  labels:
    app: abcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abcd
  template:
    metadata:
      labels:
        app: abcd
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: se
        image: "xxx"
        lifecycle:
          preStop:
            exec:
              command: ["zookeepercli","--servers","zk-hs", "-c", "set", "$HOSTNAME", "offline"]
        ports:
        - containerPort: 2345
      - name: pe-1
        image: "xxx"
        lifecycle:
          preStop:
            exec:
              command: ["zookeepercli","--servers","zk-hs", "-c", "set", "$HOSTNAME", "offline"]
        ports:
        - containerPort: 2313
``` 

/sig Contributor Experience

**Comment by tedyu** [comment]
Which release of k8s are you using ?

Can you attach kubelet.log around the time Pod was restarted ?

**Comment by sshankaregowda** [comment]
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}


where to find the kubelet.log ?

**Comment by tedyu** [comment]
You can run

journalctl -u kubelet

and save the output in file

**Comment by sshankaregowda** [comment]
please find the logs attached ..
let me know whats your thoughts. the command which I run zookeepercli runs prefectly fine when I run manually inside the pod
[k8s3.tar.gz](https://github.com/kubernetes/kubernetes/files/4665609/k8s3.tar.gz)

**Comment by tedyu** [comment]
```
k8s-worker101.qa.sac: {"log":", message: \"2020-05-22 01:29:16 FATAL zk: node does not exist\\n\"\n","stream":"stderr","time":"2020-05-22T01:29:17.015700747Z"}
k8s-worker101.qa.sac: {"log":"I0522 01:29:17.015499    7630 handlers.go:66] Exec lifecycle hook ([zookeepercli --servers zk-hs -c set /otin/services/otin/policyEngine/policy-$HOSTNAME-2314 thrift://$HOSTNAME:2314/offline]) for Container \"pe-4\" in Pod \"otin-6b69578f55-nnt7l_idev(7f606474-ecff-4130-8ef5-1f5f5847c6ab)\" failed - error: command 'zookeepercli --servers zk-hs -c set /otin/services/otin/policyEngine/policy-$HOSTNAME-2314 thrift://$HOSTNAME:2314/offline' exited with 1: 2020-05-22 01:29:16 FATAL zk: node does not exist\n","stream":"stderr","time":"2020-05-22T01:29:17.015663873Z"}
k8s-worker101.qa.sac: {"log":"E0522 01:29:17.015530    7630 kuberuntime_container.go:490] preStop hook for container \"pe-4\" failed: command 'zookeepercli --servers zk-hs -c set /otin/services/otin/policyEngine/policy-$HOSTNAME-2314 thrift://$HOSTNAME:2314/offline' exited with 1: 2020-05-22 01:29:16 FATAL zk: node does not exist\n","stream":"stderr","time":"2020-05-22T01:29:17.015720224Z"}
k8s-worker101.qa.sac: {"log":"I0522 01:29:17.015583    7630 kuberuntime_container.go:600] Killing container \"docker://c3fac437a04890cb0a3e09e81902e492d0f0580c26f7445f7e7199e58b0d5628\" with 30 second grace period\n","stream":"stderr","time":"2020-05-22T01:29:17.015727701Z"}
```
Can you check that HOSTNAME can be correctly expanded in container ?

**Comment by sshankaregowda** [comment]
yes the HOSTNAME is an env variable and it can be expanded correctly

**Comment by sshankaregowda** [comment]
zookeepercli --servers zk-hs -c set $HOSTNAME-2313 thrift://$HOSTNAME:2313/online

if I run this manually inside container it works fine

**Comment by tedyu** [comment]
Do you have other hook(s) which calls zookeepercli ?
Does other hook run correctly ?
See if more information can be logged if zookeepercli fails.

**Comment by sshankaregowda** [comment]
so how do I echo the $HOSTNAME in the prestop and see the results ?
I can not see it in the logs

**Comment by sshankaregowda** [comment]
I think I found the issue.. although the HOSTNAME is an env variable but its not expanding inside prestop-hook. which I believe is a bug.

**Comment by sshankaregowda** [comment]
command: ["zookeepercli","--servers","zk-hs", "-c", "set", "$(HOSTNAME)", "offline"]
command: ["zookeepercli","--servers","zk-hs", "-c", "set", "${HOSTNAME}", "offline"]

I tried all the combinations but doesnt work, you know how to access the env variable from prestop hook ?

**Comment by rmohta** [comment]
To provide additional info, httpGet works for preStop hook. Haven't been able to get exec work on preStop yet. Have to try some more and read code.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: busybox
    spec:
      containers:
      - image: temp-test:local
        name: busybox
        command: ["httpd"]
        args: ["-p", "8080", "-f", "-v"]
        ports:
          - containerPort: 8080
        lifecycle:
          preStop:
            #httpGet:
              #port: 8080
              #path: "/shutdown"
            exec:
              #command: ["pre-stop.sh"]
              #command: ["sh", "-c", "pre-stop.sh"]
              command: ["/bin/pre-stop.sh"]
        resources: {}
```
