### ISSUE TITLE
Higher level of infrastructure management than Deployment/StatefulSet

### ISSUE THREAD

**Issue by EddieJamsession** [kubernetes/kubernetes#91330]
**What would you like to be added**:

Would be beneficial to have ability to manage infrastructure on a higher level than a Deployment or StatefulSet.

**Why is this needed**:

- Multi-tenancy management, right now we need to generate deployment/set of deployments for each tenant (which are pretty similar) and then delete/create/update them based on the changed requirements, it would be easier to have one place to refer to, that contains only the diffs between environments.

- Environment management (e.g. UAT/Production/Staging/Development/Performance), mostly we duplicate the same deployment/ set of deployment and change only the few lines in each of them to create new environment setup, which leads to lots of code duplication and requires external diff tools to see the diffs for most cases.

Just a simple scratch to get idea across:
```
apiVersion: apps/v1
kind: Infrastructure
metadata:
  name: exporters-infrastructure
spec:
   template:
      - name: kafka-replicator
      - foreach: [hostname, cpu.limit, replicas]
       - values:
	  - some.domain.com, 10, 3
          - some.other.net, 2, 1
	  - some.other2.net, 4, 0
      - name: main-business-app
      - foreach: [env, cpu.limit, replicas, version]
      - values:
         - stage_uat, 10, 1, v10
         - perfomance_testing, 10, 1, v10
         - prod, 23, 3, v1
	 - dev, 23, 3, v2
```
I know there is a Helm and similar tools, but are there plans to have this in a core project some day?
