### ISSUE TITLE
SecurityContext windowsOptions doesn't work on kind:Deployment

### ISSUE THREAD

**Issue by Maellooou** [kubernetes/kubernetes#91414]
**What happened**:
I add podSecurityPolicy on my Kubernetes cluster with the parameter RUNASUSER = MustRunAsNonRoot.
I try to create a Deployment with Windows docker image and the securityContext.windowsOptions.runAsUserName

I used the template here : https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/windows/run-as-username-pod.yaml

It works well, but if I add the deployment object like that :

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-as-username-demo
  namespace: admin-test
spec:
  selector:
    matchLabels:
      app: run-as-username-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: run-as-username-demo
    spec:
      securityContext:
        windowsOptions:
          runAsUserName: "ContainerUser"
      containers:
      - name: run-as-username-demo
        image: mcr.microsoft.com/windows/servercore:ltsc2019
        command: ["ping", "-t", "localhost"]
```

It doesn't work with the following issue : 

`Error: container has runAsNonRoot and image will run as root`

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.4
- Cloud provider or hardware configuration: on premise

Thanks for your help

/sig windows
