### ISSUE TITLE
PodSecurityPolicy rule: 'MustRunAsNonRoot' and windowsOptions: runAsUserName not working

### ISSUE THREAD

**Issue by jfpucheu** [kubernetes/kubernetes#91482]
Hello, 

**What happened**:
When we apply PodSecurityPolicy with rule:

```
runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
```

WIndows containers are still blocked instead we put: 

```
  securityContext:
   windowsOptions:
      runAsUserName: "ContainerUser"
```

the pod is still blocked with logs: 

`  Warning  Failed          1s (x10 over 72s)  kubelet, kubenodewin04  Error: container has runAsNonRoot and image will run as root `

**What you expected to happen**:

the Container should start

**How to reproduce it (as minimally and precisely as possible)**:
Create Psp disableling Root Users:

```
runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
```

Create a pod Windows with runAsUserName:

```
apiVersion: v1
kind: Pod
metadata:
  name: run-as-username-pod-demo
spec:
  securityContext:
    windowsOptions:
      runAsUserName: "ContainerUser"
  containers:
  - name: run-as-username-demo
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command: ["ping", "-t", "localhost"]
  nodeSelector:
    kubernetes.io/os: windows
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.3
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core) / windows server 2019 version 1809
- Kernel (e.g. `uname -a`):  3.10.0-514.10.2.el7.x86_64
- Others:
/sig windows
