### ISSUE TITLE
Compatibility between coredns and kubernetes

### ISSUE THREAD

**Issue by tuananh170489** [kubernetes/kubernetes#91656]
**What happened**:
CoreDNS v1.6.5 do not work properly with k8s v1.17.5
![image](https://user-images.githubusercontent.com/32832301/83472236-f633a300-a4b0-11ea-85cc-4701ef5d713a.png)

**What you expected to happen**:
CoreDNS v1.3.1 work flawlessly with k8s v1.15.11
![image](https://user-images.githubusercontent.com/32832301/83472348-3abf3e80-a4b1-11ea-87e2-b372ed86e0e0.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Bootstrap k8s cluster v1.17.5 with 2 master nodes and 5 worker nodes
2. Deploy CoreDNS v1.6.5
3. Create busybox pod to test CoreDNS
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
```

**Anything else we need to know?**:
See https://github.com/coredns/deployment/blob/master/kubernetes/CoreDNS-k8s_version.md

**Environment**:
- Kubernetes version: v1.17.5
- Cloud provider or hardware configuration: Virtual Machines on bare metal
- OS: Ubuntu 18.04.3
- Kernel: 4.15.0-55-generic
- Install tools:
- Network plugin and version: kube-router v0.4.0
- Others: CoreDNS v1.6.5
