### ISSUE TITLE
`kubectl apply` drops all hostAlias entries when removing a duplicate entry from an existing object

### ISSUE THREAD

**Issue by chandanpasunoori** [kubernetes/kubernetes#91670]
**What happened**:
When applying deployment yaml file with kubectl few out of many host aliases are ignored, only applying partial hostaliases. 

I tried with json also but bahavior is same, tried with kubectl edit again bahavior is same. 
But when I updated directly in GKE console its applying correctly.

**What you expected to happen**:

It should apply all host aliases correctly. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
we have grouped domains based naked domains, all points to single ip. 
changed all hosts to single hostname list and single ip but behaviour is same. 

**Environment**:
GKE
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.9", GitCommit:"e1af17fd873e15a48769e2c7b9851405f89e3d0d", GitTreeState:"clean", BuildDate:"2020-04-06T20:56:54Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
GKE
- OS (e.g: `cat /etc/os-release`):
COS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Do you have the example manifests that aren't working?

**Comment by chandanpasunoori** [comment]
below is the is similar document, hear I only added 2 hostnames entries but  we have 23 and many domains in it, but all points same ip like below.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: <app_name>
  name: <app_name>
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <app_name>
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: <app_name>
    spec:
      containers:
        - name: <app_name>
          image: gcr.io/<gcp_project>/<app_name>:latest          
          resources:
            limits:
              cpu: "1"
              memory: 4G
            requests:
              cpu: "1"
              memory: 4G
          ports:
            - containerPort: 8080
              name: http-port
              protocol: TCP
      hostAliases:
        - hostnames:
            - a1.client.com
            - a2.client.com
            - a3.client.com
            - a4.client.com
            - a5.client.com
            - a6.client.com
          ip: 12.12.12.12
        - hostnames:
            - b1.client.com
            - b2.client.com
            - b3.client.com
            - b4.client.com
            - b5.client.com
            - b6.client.com
          ip: 12.12.12.12
      terminationGracePeriodSeconds: 300
```

**Comment by liggitt** [comment]
> we have 23 and many domains in it, but all points same ip like below

The merge key of the hostAliases list is the IP field, so the IP field of each entry must be unique. If you use the same value, `apply` collapses the duplicate values and only honors one of them.

/close

**Comment by chandanpasunoori** [comment]
as I already mentioned 

> changed all hosts to single hostname list and single ip but behaviour is same.

I did like below too, but still its ignores few entries

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: <app_name>
  name: <app_name>
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <app_name>
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: <app_name>
    spec:
      containers:
        - name: <app_name>
          image: gcr.io/<gcp_project>/<app_name>:latest          
          resources:
            limits:
              cpu: "1"
              memory: 4G
            requests:
              cpu: "1"
              memory: 4G
          ports:
            - containerPort: 8080
              name: http-port
              protocol: TCP
      hostAliases:
        - hostnames:
            - a1.client.com
            - a2.client.com
            - a3.client.com
            - a4.client.com
            - a5.client.com
            - a6.client.com
            - b1.client.com
            - b2.client.com
            - b3.client.com
            - b4.client.com
            - b5.client.com
            - b6.client.com
          ip: 12.12.12.12
      terminationGracePeriodSeconds: 300
```
