### ISSUE TITLE
Propagate pods labels to pods/exec subresource to filter objects on webhooks config side

### ISSUE THREAD

**Issue by sleshchenko** [kubernetes/kubernetes#91732]
**What would you like to be added**:
Propagate pods labels to pods/exec subresource to filter objects on webhooks config side.

**Why is this needed**:
Hello, guys. I'm from Eclipse Che team.

The idea is pretty general: 
there is an ability to match objects(except subresources) by labels for webhook server:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  ...
webhooks:
- admissionReviewVersions:
  - v1beta1
  failurePolicy: Fail
  matchPolicy: Equivalent
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
    - key: my-component.organization.com
      operator: Exists
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
```
 and it's quite logical to propagate pods/exec labels from target pod to subresource to be able to configure admission webhooks in the right way not to process every pods/exec.

It may make sense to object subresources as well, like `DeploymentRollback`
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector

A bit more about Eclipse Che use-case we want to restrict exec access to specific containers for creators only to avoid the leak of user's sensitive data (users access token, ssh keys) we inject.
So, we have a special label to filter our CR related objects (Deployment, Pod, ...)  and webhook server implement needed business logic.
But for pods/exec we have to listen to all `pods/exec`, fetch target pod and after checking label manually - do our additional authorization before letting user exec.
A pretty big drawback of that solution - if our webhooks server is not available for some reason - all pods/exec are locked down on the whole cluster, but actually we need only validate subset.

**Comment by sleshchenko** [comment]
^ Sorry If I chose the wrong sig and feel free to assign the right one.

**Comment by MikeSpreitzer** [comment]
Can you give a concrete example of something you would like to do but cannot, along with what you tried?

Have you noticed https://github.com/kubernetes/api/blob/afb0842feaf5249db565a4843da5a5de6b28544a/admissionregistration/v1/types.go#L40 ?

DeploymentRollback is not a subresource.  It is a deprecated top-level resource.

**Comment by sleshchenko** [comment]
@MikeSpreitzer Here are references for the concrete real our case, we're listening objects(our workspace CR, deployments, pod, ...) changes by label selector here https://github.com/devfile/devworkspace-operator/blob/master/pkg/webhook/workspace/mutating_cfg.go#L72
and we would like to listen also `pod/exec` by the same objects selector but it does not seem to be possible. So we listen to all `pod/exec` https://github.com/devfile/devworkspace-operator/blob/master/pkg/webhook/workspace/validating_cfg.go#L29 and then validate on webhook server if we should skip or process it according to pod check https://github.com/devfile/devworkspace-operator/blob/master/pkg/webhook/workspace/handler/exec.go#L37

@MikeSpreitzer let me know if it makes sense to prepare a simplified example with only needed code and instruction on how to test it.

**Comment by sleshchenko** [comment]
If rephrase the feature request in other words: Add an ability to match pod/exec by parent pod labels for webhooks. 

And the motivation behind it - if webhook server is not available: only related pod/exec must be blocked but not the whole cluster.

Currently, webhook server must listen to all pod execs, grab related pod and analyze their labels. What results to the locked pod/execs to every container on the cluster if webhook server is not available.

It's not possible simply specify ObjectSelector in webhook config, like the following:
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/name: webhook-server
    app.kubernetes.io/part-of: podexec-defender
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: podexec-defender.sleshche.com
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook-server
      namespace: podexec-defender
      path: /validate
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: webhook-server.podexec-defender.svc
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
      - key: exec-defender.sleshche.com
        operator: Exists
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CONNECT
    resources:
    - pods/exec
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
```
