### ISSUE TITLE
Provide a way to specify container image aliases

### ISSUE THREAD

**Issue by cardil** [kubernetes/kubernetes#91770]
**What would you like to be added**:

I propose to add an API that users can use to specify container image aliases. Using it will be optional, but if specified, K8s can use alias if for some reasons base image retrieval is failing.

I propose either to add `ImageAliases` field:

```go
// proposition 1
type Container struct {
  Name         string
  Image        string
  ImageAliases []string
  // [..]
}
```
Or change type of `Image` field to be mixin of array and string, similar to `intstr.IntOrString` type:

```go
// proposition 2
type Container struct {
  Name         string
  Image        strarr.StringOrArray
  // [..]
}
// k8s.io/apimachinery/pkg/util/strarr/strarr.go
type StringOrArray struct {
  Type   Type
  StrVal string
  ArrVal []string
}
```

**Why is this needed**:

Container image is specified by string value. There we can set only one value. 

https://github.com/kubernetes/kubernetes/blob/ca7a906ab793c13f3def2d7ff0357ab88bfecf92/pkg/apis/core/types.go#L2023

In case of image registry outage Kubernetes isn't able to run pods that use that registry. If users got option of specifying image aliases, Kuberenetes can run Pods with alternative image name provided by user.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: image-alias-test
spec:
  containers:
    - name: app
      image: registry.example.io/acme/app:1.1.0
      imageAliases:
        - registry-ro.example.org/acme/app:1.1.0
        - gcr.io/example/acme/app:1.1.0
```
