### ISSUE TITLE
Windows cannot resolve targetport name

### ISSUE THREAD

**Issue by ksubrmnn** [kubernetes/kubernetes#91783]
**What happened**: Windows nodes do not correctly resolve targetport when it is specified as a name

**What you expected to happen**: Window a kube proxy should select the correct port from the port list in the Service object

**How to reproduce it (as minimally and precisely as possible)**: deploy a ClusterIP service where the targetport is specified as the name of a port and not a port number. Loadbalancing will fail when the client is a Windows container regardless of where the service is deployed (Windows or Linux)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Applicable since Windows GA
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Windows 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): n/a
- Others:

**Comment by ksubrmnn** [comment]
@marosset FYI

**Comment by ksubrmnn** [comment]
@JocelynBerrendonner @daschott Can you please assign this issue to someone in core net? This impacted AKS customers. I can explain the fix, it is fairly simple

**Comment by daschott** [comment]
Sure

**Comment by wawa0210** [comment]
![image](https://user-images.githubusercontent.com/7907809/83933374-69535700-a7da-11ea-9d7a-a31a3a7e7614.png)

@ksubrmnn 

I am interested in this issue, can I follow up? I don't know if my steps to reproduce are correct. A deployment of a windows container is created, the containerPort is specified by the name `http`, and then this `http` is used for mapping in the service. Finally, access through nodeip:port. Everything looks normal

**Comment by wawa0210** [comment]
/assign

@ksubrmnn  @MikkelHegn 

I am very confused. The following are my latest and complete test steps, but they have not reproduced

An example of nginx, yaml is as follows:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    component: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
  containers:
  - name: nginx
    image: nginx:1.19
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
        name: http
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: nginx
  name: nginx
spec:
  ports:
  - name: nginx-80
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    component: nginx
  type: ClusterIP
```
It will create a pod running in linux and create a service at the same time, the results are as follows
```
[root@10-7-106-220 ~]# kubectl  apply -f nginx.yaml
pod/nginx created
service/nginx created
[root@10-7-106-220 ~]# kubectl get svc -o wide
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE   SELECTOR
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   8d    <none>
nginx        ClusterIP   10.96.2.54   <none>        80/TCP    6s    component=nginx
[root@10-7-106-220 ~]# kubectl get ep -o wide
NAME         ENDPOINTS            AGE
kubernetes   10.7.106.220:16443   8d
nginx        172.28.0.14:80       11s
[root@10-7-106-220 ~]# kubectl get po -o wide
NAME    READY   STATUS    RESTARTS   AGE     IP            NODE           NOMINATED NODE   READINESS GATES
nginx   1/1     Running   0          5m44s   172.28.0.14   10-7-106-220   <none>           <none>

1.  Test on Linux nodes in the cluster
```
[root@10-7-106-220 ~]# telnet 10.96.2.54 80
Trying 10.96.2.54...
Connected to 10.96.2.54.
Escape character is '^]'.
`` `
test passed

2. Test on Windows nodes in the cluster
```
PS C:\Users\Administrator> Test-NetConnection -Port 80 -ComputerName 10.96.2.54
ComputerName     : 10.96.2.54
RemoteAddress    : 10.96.2.54
RemotePort       : 80
InterfaceAlias   : vEthernet (Ethernet0)
SourceAddress    : 10.7.106.206
TcpTestSucceeded : True
```
test passed

3. Test on independent Windows container on Windows nodes  in the cluster
```
PS C:\Users\Administrator> docker exec -it 398b409d8570 powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\inetpub\wwwroot> Test-NetConnection -Port 80 -ComputerName 10.96.2.54
ComputerName     : 10.96.2.54
RemoteAddress    : 10.96.2.54
RemotePort       : 80
InterfaceAlias   : vEthernet (Ethernet)
SourceAddress    : 172.28.228.12
TcpTestSucceeded : True
```
ps. This is a separate container running via docker run based on asp.net mvc and test passed
----

So far I have not been able to reproduce this issue, have I forgotten any key steps??

I went to study the proxy code and found that the name type targetport has been processed

https://github.com/kubernetes/kubernetes/blob/35fc65dc2c614e57e5a019358a24af78ee1cfc16/pkg/proxy/winkernel/proxier.go#L1200-L1205

I am interested in this issue, can you help me reproduce it together
