### ISSUE TITLE
readiness liveness probe issue with springboot and kubernetes

### ISSUE THREAD

**Issue by shivrajjadhav733** [kubernetes/kubernetes#91879]
What I have

Windows 10
Springboot 2.2.1
docker desktop installed - docker and kubernetes running
openjdk 11

application.yaml in my springboot application

```
server:
  port: 8443
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: '*'
          show-details: always
        liveness:
          include: '*'
          show-details: always

```
On my local when I start springboot application: 
To access health, I go to page - http://localhost:8443/api/actuator/health
This works fine. 

But, when I try to access https://localhost:8443/api/actuator/health/readiness or http://localhost:8443/api/actuator/health/liveness I get error

This localhost page can’t be found. No webpage was found for the web address: http://localhost:8443/api/actuator/health/readiness HTTP ERROR 404

**Question - Is this an expected behaviour? readiness or liveness probe can not be tested with just springboot without deploying springboot application to kubernetes? **
