### ISSUE TITLE
readiness and liveness issue deploying it to EKS 

### ISSUE THREAD

**Issue by shivrajjadhav733** [kubernetes/kubernetes#91880]
What I have

Windows 10
Springboot 2.1.1
kubernetes 1.13 using EKS
openjdk 11
cloud: AWS

application.yaml in my springboot application

```
server:
  port: 8443
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

```

ingress.yaml

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 'my-ingress'
  namespace: 'my-namespace'
  annotations:
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:xxxxxxxxxxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: "EKS-ALB-sg"
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/tags: <ingress-tag>
    alb.ingress.kubernetes.io/load-balancer-attributes: <ingress alb>
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: <host-name>
      http:
        paths:
         - path: /*
           backend:
             serviceName: 'my-service'
             servicePort: 8443

```
deployment.yaml in kubernetes

```
spec:
  template:
    spec:
      containers:
          readinessProbe:
            httpGet:
              port: 8443
              path: api/actuator/health
              scheme: HTTPS
            initialDelaySeconds: 60
            failureThreshold: 2
            periodSeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8443
              path: api/actuator/health
              scheme: HTTPS
            initialDelaySeconds: 120
            failureThreshold: 2
            periodSeconds: 60
            timeoutSeconds: 5

```
My application takes around 30-50 seconds to start, thats why I have kept initialdelayseconds or periodseconds as 60
Please take a look at scheme set as HTTPS

for this configuration when I try to deploy to on EKS cluster, I get error like below:

I see error like below when I describe pod.

```
  Warning  Unhealthy  48s                  kubelet, <ip>.ec2.internal  Readiness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy  44s                  kubelet, <ip>.ec2.internal  Liveness probe failed: HTTP probe failed with statuscode: 503


Warning  Unhealthy  105s (x2 over 2m45s)  kubelet, <ip>.ec2.internal  Readiness probe failed: Get https://<ip>:8443/api/actuator/health: dial tcp <>:8443: connect: connection refused
      Warning  Unhealthy  46s                   kubelet, <ip>.ec2.internal  Liveness probe failed: Get https://<ip>:8443/api/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
      Warning  Unhealthy  40s                   kubelet, <ip>.ec2.internal  Readiness probe failed: Get https://<ip>:8443/api/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)


```
Is it due to ingress taking time to create host? 
Or Is there anything else I might be doing wrong?
Or is it due to springboot 2.1 version? I have tried same with springboot 2.2 as well by updating application.yaml in springboot application as follow:

```
management:
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: '*'
          show-details: always
        liveness:
          include: '*'
          show-details: always
```
