### ISSUE TITLE
HPA does not support multiple deployments in the istio

### ISSUE THREAD

**Issue by kong62** [kubernetes/kubernetes#91900]
**What happened**:
```
# kubectl get hpa -n test001 ;kubectl get po -o wide -n test001 
NAME                REFERENCE                  TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
php-apache-hpa-v1   Deployment/php-apache-v1   0%/50%    1         10        1          3m39s
php-apache-hpa-v2   Deployment/php-apache-v2   0%/50%    1         10        1          3m39s

NAME                                 READY   STATUS    RESTARTS   AGE     IP             NODE    NOMINATED NODE   READINESS GATES
php-apache-v1-7896774598-npc7w       1/1     Running   0          3m39s   10.64.70.243   k8s06   <none>           <none>
php-apache-v2-7896774598-vmfdv       1/1     Running   0          3m39s   10.64.70.37    k8s05   <none>           <none>
```

bech v1 pod:
```
/ # while true; do wget -q -O- http://10.64.70.243; done
OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!^C
```

v1 and v2 all scale up. not only v1
```
# kubectl get hpa -n test001 ;kubectl get po -o wide -n test001 
NAME                REFERENCE                  TARGETS   MINPODS   MAXPODS   REPLICAS   AGE
php-apache-hpa-v1   Deployment/php-apache-v1   67%/50%   1         10        1          4m
php-apache-hpa-v2   Deployment/php-apache-v2   67%/50%   1         10        1          4m

NAME                                 READY   STATUS              RESTARTS   AGE   IP             NODE    NOMINATED NODE   READINESS GATES
php-apache-v1-7896774598-cslm8       0/1     ContainerCreating   0          4s    <none>         k8s08   <none>           <none>
php-apache-v1-7896774598-lj2w9       0/1     ContainerCreating   0          4s    <none>         k8s04   <none>           <none>
php-apache-v1-7896774598-npc7w       1/1     Running             0          4m    10.64.70.243   k8s06   <none>           <none>
php-apache-v2-7896774598-9t8x8       0/1     ContainerCreating   0          4s    <none>         k8s07   <none>           <none>
php-apache-v2-7896774598-pscsq       0/1     ContainerCreating   0          4s    <none>         k8s09   <none>           <none>
php-apache-v2-7896774598-vmfdv       1/1     Running             0          4m    10.64.70.37    k8s05   <none>           <none>
```

**What you expected to happen**:
only v1 pod scale

**How to reproduce it (as minimally and precisely as possible)**:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-v1
  labels:
    app: hpa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: php-apache
      app: hpa-test
  template:
    metadata:
      labels:
        name: php-apache
        app: hpa-test
    spec:
      containers:
      - name: php-apache
        image: mirrorgooglecontainers/hpa-example:latest
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 0.05
            memory: 64Mi
          limits:
            cpu: 0.1
            memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache-v2
  labels:
    app: hpa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: php-apache
      app: hpa-test
  template:
    metadata:
      labels:
        name: php-apache
        app: hpa-test
    spec:
      containers:
      - name: php-apache
        image: mirrorgooglecontainers/hpa-example:latest
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 0.05
            memory: 64Mi
          limits:
            cpu: 0.1
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache-svc
  labels:
    app: hpa-test
spec:
  selector:
    name: php-apache
    app: hpa-test
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa-v1
  labels:
    app: hpa-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache-v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa-v2
  labels:
    app: hpa-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache-v2
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```

**Environment**:
- Kubernetes version (use `kubectl version`):
1.18
1.14

- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux pub-k8s-mgt-prd-50001-ecs 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
