### ISSUE TITLE
readiness and liveness scope restriction

### ISSUE THREAD

**Issue by shivrajjadhav733** [kubernetes/kubernetes#91916]
I have

Windows 10
Springboot 2.1.1
kubernetes 1.13 using EKS
openjdk 11
cloud: AWS

application.yaml in my springboot application

```
server:
  port: 8443
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

```
deployment.yaml in kubernetes

```
spec:
  template:
    spec:
      containers:
          readinessProbe:
            httpGet:
              port: 8443
              path: api/actuator/health
              scheme: HTTPS
            initialDelaySeconds: 120
            failureThreshold: 2
            periodSeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8443
              path: api/actuator/health
              scheme: HTTPS
            initialDelaySeconds: 120
            failureThreshold: 2
            periodSeconds: 60
            timeoutSeconds: 5

```
Considering my application takes around 60-90 seconds to start, are below timeouts. initialdelay correct?

Currently when I go to api/actuator/health I see something like this:

```
{
  "status": "UP",
  "details": {
    "diskSpace": {
      "status": "UP",
      "details": {
        "total": 53674487808,
        "free": 48233635840,
        "threshold": 10485760
      }
    },
    "db": {
      "status": "UP",
      "details": {
        "readDataSource": {
          "status": "UP",
          "details": {
            "database": "Oracle",
            "hello": "Hello"
          }
        },
        "writeDataSource": {
          "status": "UP",
          "details": {
            "database": "Oracle",
            "hello": "Hello"
          }
        }
      }
    },
    "refreshScope": {
      "status": "UP"
    }
  }
}

```
How to add below restriction?
Liveness probe should not include backend setup checks like DB. Only want to restart when app is unhealthy.
Readiness probe should include backend setup like DB.
