### ISSUE TITLE
kubectl output flooded with warnings about aws-iam-authenticator

### ISSUE THREAD

**Issue by snstanton** [kubernetes/kubernetes#91913]
**What happened**:
`kubectl -A describe pods`

Results in a flood of messages like:
`W0608 10:47:22.221620   25245 exec.go:203] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 3825 clients constructed calling "aws-iam-authenticator"`

**What you expected to happen**:

No warnings.

**How to reproduce it (as minimally and precisely as possible)**:
In an EKS environment where aws-iam-authenticator is used to get tokens:
```
users:
- name: myuser
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - dev
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: dev
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`): macos
- Kernel (e.g. `uname -a`): Darwin Kernel Version 19.5.0
