### ISSUE TITLE
Static pods fail preStop because container is not running

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#91923]
I'm trying to make our api servers (which run as static pods) wait 5s before they shut down, so we do not end up with requests going to them when they are down.

```
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "echo PRE-START; /bin/sleep 5; echo PRE-STOP"]
```

I tried:
- moving the file in and out of manifests
- shutting down the node
- kubectl delete pod

but neither of them make the preStop hook run
