### ISSUE TITLE
imagePullPolicy when defined without a value defaults to Always not to IfNotPresent 

### ISSUE THREAD

**Issue by taggelos** [kubernetes/kubernetes#91944]
**What would you like to be added**:

The documentation suggests that "The default pull policy is IfNotPresent"
This is not the case when imagePullPolicy is defined under the spec section in a Pod definition without a specific value. 

Example:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-test
  name: nginx-test
spec:
  containers:
  - image: nginx
    name: nginx-test
  imagePullPolicy:

```
This will result in a Pod having imagePullPolicy as Always.

**Why is this needed**:

This is needed for clarification of the default behaviour.
It is necessary for the appropriate handling of helm charts, in cases that the imagePullPolicy is empty.
