### ISSUE TITLE
DualStack: nodes and hostNetwork pods have only a single IP

### ISSUE THREAD

**Issue by wxdlong** [kubernetes/kubernetes#91940]
**What happened**:

I want to deploy k8s with IPV4/IPv6 dual stack.
But node internal IP always only one either IPV4 or IPV6.
Pod IP can auto assigned IPV4,IPV6 calico,  IPv6 Service also work.
But NodeType only listener at IPV4, not IPV6.

```bash
                "status": {
                "addresses": [
                    {
                        "address": "10.126.20.162",
                        "type": "InternalIP"
                    },
                    {
                        "address": "wxdlong",
                        "type": "Hostname"
                    }
                ],
```

**What you expected to happen**:

As https://kubernetes.io/docs/tasks/network/validate-dual-stack/  said.

```bash
kubectl get nodes k8s-linuxpool1-34450317-0 -o go-template --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}'
Hostname: k8s-linuxpool1-34450317-0
InternalIP: 10.240.0.5
InternalIP: 2001:1234:5678:9abc::5

```

**How to reproduce it (as minimally and precisely as possible)**:
the init config 

```yaml

apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.126.20.162"
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  kubeletExtraArgs:
    node-ip: "10.126.20.162,2001:1b74:88:9400::62:62"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.17.4

```bash
 kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

```bash
# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

```
- Kernel (e.g. `uname -a`):

```bash
# uname -a
Linux wxdlong 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```bash
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:01:11Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Network plugin and version (if this is a network-related bug):
  calico
- Others:

  May be my init config is not correct, Any one can give an full example for IPV4,IPV6 dual stack. Thanks

**Comment by aojea** [comment]
hi @wxdlong your configuration is correct, however, this is a known issue with a cluster that does not have a cloud controller manager handling the node addresses.

There is a KEP addressing this problem
https://github.com/kubernetes/enhancements/pull/1665 , and hopefully it will be solved soon

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by wxdlong** [comment]
> hi @wxdlong your configuration is correct, however, this is a known issue with a cluster that does not have a cloud controller manager handling the node addresses.
> 
> There is a KEP addressing this problem
> [kubernetes/enhancements#1665](https://github.com/kubernetes/enhancements/pull/1665) , and hopefully it will be solved soon

Thanks your quickly reply, If so, do you known that the node port for IPV6 is also can't work. and Inside pod that can't access outside through ipv6?  

Currently that our pod can't access IPV6 outside, i guees it because of K8s node-ip not known the IPV6, so it will not add the route rule or something in IPtable.

**Comment by athenabot** [comment]
@danwinship
If this issue has been triaged, please comment `/remove-triage unresolved`.

If you aren't able to handle this issue, consider unassigning yourself and/or adding the `help-wanted` label.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by Queuecumber** [comment]
So basically dual-stack currently doesn't work at all on bare metal?

**Comment by danwinship** [comment]
Well, as you said, pods are dual-stack, nodes/hostNetwork pods aren't. This is why it's still an alpha feature.

**Comment by Queuecumber** [comment]
I'm not OP. What are the implications of having dual stack pods but not nodes?

**Comment by danwinship** [comment]
mostly just that hostNetwork pods will be single-stack.

**Comment by Queuecumber** [comment]
I used the trick described at https://github.com/kubernetes/kubernetes/issues/42125 to add the second InternalIP to the nodes manually (`--cloud-provider=external' and using curl to add the IP) and this seems to have resolved IPv6 pod-to-pod connectivity issues I was seeing. I think it may be missing routes without this as @wxdlong described above, I still have no IPv6 connectivity to the internet from pods but I think that may simply be missing routes on my routers side since I'm using GUAs for pods.

**Comment by danwinship** [comment]
/retitle DualStack: nodes and hostNetwork pods have only a single IP

**Comment by Trackhe** [comment]
I have the Problem too. on K8s 1.19 bare-metal on arm64 ubuntu 20.04
my init config:
```
apiVersion: kubeadm.k8s.io/v1beta2
featureGates:
  IPv6DualStack: true
kind: ClusterConfiguration
networking:
  podSubnet: 200.200.0.0/16,fd7a:cccc:dddd::/48
  ServiceSubnet: 10.200.0.0/16,fd00:0002:0:0:1::/80
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-ip: "192.168.178.240,fd11:1111:1111:1111:dea6:32ff:fe34:ed61"
```

all https://kubernetes.io/docs/tasks/network/validate-dual-stack/ tests are working but only kubectl get nodes raspnode01 -o go-template --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}' gives me only a ipv4 back. 

I wouldn't care. but I can't create a service in 1.19 with the IPv6 family and I think that's because of that.

to reproduce my problem i have write a manual. : https://github.com/Trackhe/Raspberry64bitKubernetesServerDualstack
