### ISSUE TITLE
kube-proxy leaves IPVS weight == 0 after restarting

### ISSUE THREAD

**Issue by morimoto-cybozu** [kubernetes/kubernetes#92019]
**What happened**:

I'm using kube-proxy in the IPVS mode.  When a back-end Pod for a Service becomes unready once and gets ready again while kube-proxy restarts, kube-proxy sets the IPVS weight for the Pod to 0 and does not resume it to 1.

A more precise sequence is as follows:
1. a back-end Pod becomes unready by some reason
2. kube-proxy sets the IPVS weight for the Pod to 0
3. kube-proxy is stopped, e.g. for upgrading
4. the Pod becomes ready
5. kube-proxy is started
6. kube-proxy DOES NOT set the IPVS weight for the Pod to 1

**What you expected to happen**:

kube-proxy sets the IPVS weight for a ready back-end Pod to 1.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup a k8s cluster by kind with 1 worker node.
2. Edit ConfigMap for kube-proxy to enable the IPVS mode, and restart kube-proxy.
```
kubectl -n kube-system edit configmap kube-proxy
kubectl -n kube-system delete pod -l k8s-app=kube-proxy
```
3. Install `ipvsadm` on the worker node.
```
docker exec -it kind-worker apt-get update
docker exec -it kind-worker apt-get install -y ipvsadm
```
4. Create a Service and a Deployment.  Tweak the readiness probe to ease reproduction.
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        readinessProbe:
          exec:
            command:
            - test
            - "!"
            - -f
            - /tmp/foobar
          failureThreshold: 1
          periodSeconds: 1
EOF
```
5. Access the Service to leave a connection.
```
SERVICE_IP=$(kubectl get service my-nginx -o jsonpath='{.spec.clusterIP}')
docker exec -it kind-worker curl ${SERVICE_IP}
```
6. Make the back-end Pod unready.
```
POD_NAME=$(kubectl get pod -l run=my-nginx -o jsonpath='{.items[0].metadata.name}')
kubectl exec -it ${POD_NAME} touch /tmp/foobar
```
7. Show the IPVS table.  There should be a real server with weight 0.
```
docker exec -it kind-worker ipvsadm -L -n
```
8. Stop kube-proxy by adding an invalid command-line option and deleting Pods.
```
kubectl -n kube-system edit daemonset kube-proxy
kubectl -n kube-system delete pod -l k8s-app=kube-proxy
```
9. Resume the back-end Pod ready.
```
kubectl exec -it ${POD_NAME} rm /tmp/foobar
```
10. Restart kube-proxy by removing the invalid command-line option.
```
kubectl -n kube-system edit daemonset kube-proxy
```
11. Show the IPVS table.  There should still be a real server with weight 0 even though the back-end Pod is ready.
```
docker exec -it kind-worker ipvsadm -L -n
```

**Anything else we need to know?**:

The status whether the IPVS weight is set to 0 is managed in pkg/proxy/ipvs/graceful_termination.go.  It is recorded on memory in kube-proxy process, so it gets forgotten when kube-proxy restarts.  It would be more appropriate to use the weight information retrieved from IPVS in reconciliation.  On-memory statuses are useful for periodic deletion, though.

**Environment**:
- Kubernetes version (use `kubectl version`): Client: v1.17.2, Server: v1.18.2
- Cloud provider or hardware configuration: Docker containers managed by kind
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04 LTS
- Kernel (e.g. `uname -a`): 4.15.0-101-generic
- Install tools: kind
- Network plugin and version (if this is a network-related bug):
- Others:
