### ISSUE TITLE
Support fuse volume in k8s

### ISSUE THREAD

**Issue by Binyang2014** [kubernetes/kubernetes#92114]
**What would you like to be added**:
Similar issue: #7890.
Now k8s support CSI. It's easy to integrate new type of volume to k8s.

But for `fuse` based volume, the fuse daemon is placed in CSI daemon, multi-users share same `fuse daemon`. This will cause some resource competing problems.

We should provide a way to let `fuse` based volume put `fuse daemon` into user pod when using `CSI` and `Volume`. Then the resource consumed by fuse daemon will limited by the user pod.

**Why is this needed**:

Assume pod A is running a I/O intensive job . At the same node, there is a pod B. Process in job B may find the I/O speed is slow due to process A occupy too much resources. Even though Pod A only request 1 CPU, and Pod B request 4 CPU.

The root cause is we don't have a method to put `fuse daemon` into user pod when using `CSI` and `Volume`.
But actually, it's a user space process , should be counted in user pod.

Seems privilege issue is fixed: http://lkml.iu.edu/hypermail/linux/kernel/1806.0/04385.html we may can going on this problem

**Comment by jboero** [comment]
I've always wanted this feature too but have just been doing the FUSE binary as a sidecar. Some K8s users are getting sick of sidecar bloat.  A native FUSE option would be ideal.  :+1:

**Comment by Ark-kun** [comment]
> I've always wanted this feature too but have just been doing the FUSE binary as a sidecar.

Can you please share how you do this?

**Comment by saswatac** [comment]
I have been doing this as follows -
```yaml
containers:
  - name: main
    image: <>
    volumeMounts:
      - name: fuse-volume
        mountPropagation: HostToContainer
        mountPath: /data
        subPath:  gcs-data
  - name: gcs-fuse
    image: <>
    lifecycle:
      preStop:
      exec:
          command: ["/bin/sh","-c","umount -l $MOUNT_DIR;"]
    env:
      - name: MOUNT_DIR
        value: "/mnt/data/gcs-data"
      - name: BUCKET
        value: "gs://bucket"
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /var/secrets/google/key.json
    command:
    - "/bin/bash"
    - "-c"
    - "--"
    args:
    - |
        set -e
        set -x
        umount -l $MOUNT_DIR || true
        mkdir -p $MOUNT_DIR
        chmod 777 $MOUNT_DIR
        gcsfuse -o allow_other --limit-ops-per-sec 100 --implicit-dirs --file-mode 777 --dir-mode 777 $BUCKET $MOUNT_DIR
        sleep infinity
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - name: fuse-volume
      mountPath: /mnt/data
      mountPropagation: Bidirectional
    - name: gcp-service-account
      mountPath: /var/secrets/google
    resources:
    limits:
        memory: 1Gi
    requests:
        memory: 1Gi
volumes:
  - name: gcp-service-account
    secret:
      secretName: gcp-service-account
  - name: fuse-volume
    emptyDir: {}
```

The main container is a notebook. Now I also want users to be able to create pods from the notebooks which would also have access to the buckets, which would mean allowing users to create privileged containers which is not desirable.

I am looking for a solution that allows mounting buckets without privileged permissions.
