### ISSUE TITLE
addon-manager should not be blocked by spec conflicts 

### ISSUE THREAD

**Issue by danielqsj** [kubernetes/kubernetes#92213]
**What happened**:

If any specs in addon folders have conflicts with the runtime specs, the addon-manager will not respect the expected specs which defined in addon folders, and it also not continue execute the prune part.

**What you expected to happen**:

If there are conflicts, the addon-manager should use `replace` instead of `apply`, and then the prune part should always be executed.

**How to reproduce it (as minimally and precisely as possible)**:

1. kubectl create a deployment with the port:\
```
ports:
- containerPort: 8080
  name: portname
  protocol: TCP
```
2. change the spec and add into addon folders
```
ports:
- containerPort: 8081
  name: portname
  protocol: TCP
```
3. watch the addon-manager log:
```
The Deployment "xxx" is invalid: spec.template.spec.containers[0].ports[1].name: Duplicate value: "portname"
```
4. the expected spec will not be applied into cluster

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
/sig cluster-lifecycle
