### ISSUE TITLE
i am getting error while making replicaset

### ISSUE THREAD

**Issue by waeleethecoolboy111** [kubernetes/kubernetes#92255]
And this is my error:

waleed@waleed-Ubuntu:~/Desktop/Kubernetes$ kubectl create -f rs.yaml
error: error parsing rs.yaml: error converting YAML to JSON: yaml: line 7: mapping values are not allowed in this context

and this is my coding in the file

kind: ReplicaSet
apiVersion: apps/v1beta2
metadata:
name: myrs
spec:
replicas:5
selector:
matchlabels:
app: rsexample
template:
metadata:
labels
app:
spec:
container:
- name
image: aamirpinger/helloworld:latest
ports:
- containerPort: 80

**Comment by bcanozter** [comment]
**Example**

```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
```

https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/


If your pasted code actually looks like that in your yaml file then it won't work. You should follow the syntax rules.
