### ISSUE TITLE
AWS LoadBalancer creation fails if loadBalancerSourceRanges contains VPC CIDRs

### ISSUE THREAD

**Issue by SaranBalaji90** [kubernetes/kubernetes#92263]
**What happened**:

Created VPC with 2 CIDRs and wanted to allow traffic from one of the CIDRs. Using loadBalancerSourceRanges to restrict the traffic from one of the CIDR fails the service creation as the healthz ingress rule collides with client ingress rule.

Error seen on the service events:
```
failed to ensure load balancer for service default/example-service-clb: error authorizing security
 group ingress: "InvalidPermission.Duplicate: the specified rule \"peer: 192.168.0.0/16, TCP, 
from port: 32357, to port: 32357, ALLOW\" already exists\n\tstatus code: 400,
 request id: 935e429b-c694-4036-b409-c4d9e3045793"
```

Manifest used

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: example-service-nlb
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: load-balancer-example
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerSourceRanges: 
    - "192.168.0.0/16"
```

**What you expected to happen**:

One of the following to happen
1. Combine all the rule that needs to be applied on the worker node security group and apply all rule once instead of splitting them to avoid "InvalidPermission.Duplicate"

2. handle duplicate ingress permission on the worker node security group.

**How to reproduce it (as minimally and precisely as possible)**:
Create VPC with two CIDRs and specify one of them in loadBalancerSourceRanges

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
aws
- OS (e.g: `cat /etc/os-release`):
Amazon Linux 2   
- Kernel (e.g. `uname -a`):
4.14.154-128.181.amzn2.x86_64

/sig cloud-provider
/sig aws
