### ISSUE TITLE
whitelisted sysctls are silently ignored and not applied

### ISSUE THREAD

**Issue by lostpoint-ru** [kubernetes/kubernetes#92266]
I'm trying to host previously tested on microk8s openvpn deployment, this time on freshly installed vanilla kubernetes and unable to enable net.ipv4.ip_forward sysctl in openvpn pod.

I created a test stand vm to re-check and reproduce the problem.

- took a fresh **Ubuntu 20.04** install
- installed default **docker-ce/containerd/docker-ce-cli/kubeadm/kubecli/kubelet** according to kubernetes.io manual page
- ran **kubeadm init** without any parameters
- applied default **calico** manifest from kubernetes.io manual
- tainted node as per manual
- confirmed that all control-plane pods up and running

Then I created a simple test deployment:

```
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        sysctls:
        - name: net.ipv4.ip_forward
          value: "1"
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

Basically a random network daemon, with attempt to set its **sysctl net.ipv4.ip_forward** to "**1**".

It applied but pod creation fails with a **SysctlForbidden** status and "**forbidden sysctl: "net.ipv4.ip_forward" not whitelisted**" message. 

Just as expected.

Then I edited `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` file, added `--allowed-unsafe-sysctls=net.ipv4.ip_forward` to kubelet arguments string, ran `systemctl daemon-reload` and `service kubelet restart`. 

**What happened**:

The pod created and entered the Running state. It also has **sysctl net.ipv4.ip_forward** value **1** in its manifest. 

From `kubectl edit pod`:

```
spec:
  containers:
  - image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    name: nginx
  ...
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    sysctls:
    - name: net.ipv4.ip_forward
      value: "1"
  serviceAccount: default
  serviceAccountName: default
  ...
```

But inside the pod, sysctl appears to be 0:

```
root@nginx-deployment-654d78d6c7-8g6r6:/# cat /proc/sys/net/ipv4/ip_forward
0
```

And if I add an openvpn deployment with these settings, ip forwarding appears to not working. 

As long as container is created without privileged=true, it's unable to change ip_forward sysctl from inside container as well.

**What you expected to happen**:

I expected either specified sysctl to get applied and enabled ip forwarding, or (in case I'm doing something wrong) pod creation to fail with some meaningful error (as was until I added `--allowed-unsafe-sysctls` to kubelet config file, for example).

**How to reproduce it (as minimally and precisely as possible)**:

Do a fresh Ubuntu install with Calico CNI as per kubernetes.io documentation found at https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/  and https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

Then add a --allowed-unsafe-sysctls=net.ipv4.ip_forward to kubelet arguments, then apply a test manifest mentioned eariler.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.18.4
- ESXi Linux x64 VM, 2 cores, 4 GB ram (test stand)
- OS: Ubuntu 20.04 LTS (Focal Fossa)
- Kernel: 5.4.0-37-generic #41-Ubuntu SMP
- Install tools: apt install, kubectl apply
- Network plugin and version: Calico 3.14 (https://docs.projectcalico.org/v3.14/manifests/calico.yaml)
- Others:

**Comment by tores1** [comment]
I have a similar issue. My environment is similar except for:
- mac virtual box vm 2 cores, 4 gb ram.
- OS: Ubuntu 18.04
- Kernel: 4.15.0-112-generic
- installed using Kubeadm

**Comment by dims** [comment]
@lostpoint-ru is this the same problem as in https://github.com/kubernetes/kubernetes/issues/87198 ?

**Comment by lostpoint-ru** [comment]
@dims Can't say for sure, It looks familiar, but they had securitycontexts, etcs configured, while I was just trying to add net_forward to allowed list and call it a day. I'm not sure I tried to do it right way, but in case I didn't -- why didn't it produce some clarifying error messages?

There's no useful input this far in that ticket as well, looks like nobody really cares. :/

**Comment by dims** [comment]
@lostpoint-ru i know it feels that way, but the truth is there aren't enough hands in the project who know enough to help triage/fix issues in this specific area (sig-node). we are trying to get more people involved, but progress is slow :(

**Comment by tores1** [comment]
It seems to be the same as what I ran into (in a StatefulSet). I set:
```
spec:
  template:
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_forward
            value: "1"
```

I have two nearly identical StatefulSets (helm generated) targeting different nodes. On one I have `--allowed-unsafe-sysctls='net.ipv4.ip_forward'` added to `/var/lib/kubelet/kubeadm-flags.env` on the other I do not. The pod only starts on the node with `--allowed-unsafe-sysctls='net.ipv4.ip_forward'` as expected. However, ipv4 forwarding is actually not enabled in the started pod as seen by:

```
kubectl exec xxxxx-p5g-pgw-a-0 -it -- /bin/bash
root@xxxxx-p5g-pgw-a-0:/# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 0
root@xxxxx-p5g-pgw-a-0:/# sysctl -w net.ipv4.ip_forward=1
sysctl: setting key "net.ipv4.ip_forward": Read-only file system
``` 

As an additional note: the container has its own `securityContext` set;
```
containers:
  - name: pgw
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
```
