### ISSUE TITLE
Updating AWS LoadBalancer service.beta.kubernetes.io/aws-load-balancer-security-groups doesn't clean up old rules

### ISSUE THREAD

**Issue by SaranBalaji90** [kubernetes/kubernetes#92264]
**What happened**:
After updating "service.beta.kubernetes.io/aws-load-balancer-security-groups" to new set of security group, new rules were added as expected but old rules was not removed, thereby leading to unmanaged rules on the worker node SG.

Manifest used
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-06702e822d9857b8b"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: example-service-clb
  labels:
    test: test6
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: load-balancer-example
  sessionAffinity: None
  type: LoadBalancer
```

**What you expected to happen**:
After the new security groups are added to the loadbalancer, we should remove the old security groups that were associated to the worker node security group. One of the reason why this might not have been removed could be because aws cloud provider doesn't know the previous value and must be smart enough to find the security group and remove them from the worker node SecGp and also delete if aws cloud provider created security group initially.

**How to reproduce it (as minimally and precisely as possible)**:
Create LB without "service.beta.kubernetes.io/aws-load-balancer-security-groups" and add "service.beta.kubernetes.io/aws-load-balancer-security-groups" with security groups from VPC.

**Environment**:
Kubernetes version (use kubectl version):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud provider or hardware configuration:
    aws

OS (e.g: cat /etc/os-release):
    Amazon Linux 2

Kernel (e.g. uname -a):
    4.14.154-128.181.amzn2.x86_64

/sig cloud-provider
