### ISSUE TITLE
No configmap and service kind events.

### ISSUE THREAD

**Issue by 928234269** [kubernetes/kubernetes#92284]
kubectl apply -f service.yaml

```
apiVersion: v1
kind: Service
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: code-server
```
kubectl get event |grep service 

k8s env: v1.17.0
