### ISSUE TITLE
iops limit for pod/pvc/pv 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#92287]
**Latest Updated on Nov 2023**

https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3751-volume-attributes-class 
- v1.29: api merged in https://github.com/kubernetes/kubernetes/pull/121104
- v1.30 WIP: https://github.com/kubernetes/kubernetes/pull/118863
- https://github.com/kubernetes-csi/external-provisioner/pull/1068

**Important Status  Updated**

https://github.com/kubernetes/kubernetes/issues/92287#issuecomment-1010723587
> Current status of blockio throttling in container runtimes:
> 
> - CRI-O: support released in v1.22, see https://github.com/cri-o/cri-o/pull/4873.
> - Containerd: a fully compatible https://github.com/containerd/containerd/pull/5490 is open.

See the new proposal at https://github.com/kubernetes/enhancements/pull/3004.

https://github.com/kubernetes/enhancements/issues/3008

The KEP [kubernetes/enhancements#3004](https://github.com/kubernetes/enhancements/pull/3004) only covers CRI.
> @mattcary We are starting a discussion around this on sig-storage. Please join the conversation on our [draft KEP](https://docs.google.com/document/d/1IcVKWIQvE7lqE6SKrfDuD_ZCkXCnptZSex4HOkNu-m8/edit#heading=h.4qp6dw5wum0v). Note the focus is taking advantage of provisioned IO capabilities of volume backends rather than pod-oriented limits or QoS.

kubernetes/enhancements#3780
https://github.com/cri-o/cri-o/pull/6254
https://github.com/containerd/containerd/pull/7418

**What would you like to be added**:
@kubernetes/sig-storage-feature-requests 
/sig storage

Better resource management for iops of devices.
In some senarios, we need to limit PV's iops limit or Pod iops on a device or volum.

Docker provides blkio related params in `docker run` to limit a device's iops and bps. https://docs.docker.com/engine/reference/run/#block-io-bandwidth-blkio-constraint

**Proposal 1: annotation on device of pod**

Current PR in #92068 is cherry pick of #70980 
This PR tried to add annotation named io.kubernetes.container.blkio in Pod spec： 
`io.kubernetes.container.blkio: '{"weight":200,"weight_device":[{"device":"rootfs","value":"200k"}],"device_read_bps":[{"device":"/dev/sda1","value":"20m"}],"device_write_bps":[{"device":"rootfs","value":"20m"}],"device_read_iops":[{"device":"rootfs","value":"200"}]"device_write_iops":[{"device":"rootfs","value":"300"}]}'
`
Docker will use below params to limit device iops.
```
      --device-read-bps value       Limit read rate (bytes per second) from a device (default [])
      --device-read-iops value      Limit read rate (IO per second) from a device (default [])
      --device-write-bps value      Limit write rate (bytes per second) to a device (default [])
      --device-write-iops value     Limit write rate (IO per second) to a device (default [])
```

However it is not a good design in K8S, device is managed by kubelet and pod spec is managed by application user who may not know the device name.  Another propersal would be iops in PVC or Pod Volume like below

1. add iops in capacity/request of PV/PVC

PV's iops limitation is the capacity of the volume.
PVC is similar. We can use PVC's iops request as the iops limit.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv
spec:
  capacity:
    storage: 10Gi
    iops： 500
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  fc:
    targetWWNs: ["50060e801049cfd1"]
    lun: 0
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
      iops: 500
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}
```

2. add iops limit to Pod volume spec

PV may be used 

Kubelet will check which device is using by the PVC and run pod containers with limits.
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-xsky-120
  name: nginx-xsky-120-748d9b79d9-6b5zw
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: piraeus.storage.daocloud.io/satellite
            operator: In
            values:
            - "true"
  containers:
  - image: 10.6.170.180/library/nginx:latest
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: html-root
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-578rp
      readOnly: true
  volumes:
  - name: html-root
    persistentVolumeClaim: 
      claimName: nginx-pvc-xsky-120
      iops: 500
  - name: default-token-578rp
    secret:
      defaultMode: 420
      secretName: default-token-578rp

```

We may use  io.kubernetes.container.blkio annotation to limit specified device's iops at first. 
If CSI and kubelet can check which device does the pvc use,  the iops limit  can apply dynamicly according to PVC name. 

**Why is this needed**:

Many users want this feature in 
https://github.com/kubernetes/kubernetes/issues/70364
https://github.com/kubernetes/kubernetes/issues/27000
https://github.com/kubernetes/kubernetes/pull/70573
https://github.com/kubernetes/kubernetes/issues/70364
https://github.com/kubernetes/kubernetes/pull/70980
https://github.com/kubernetes/kubernetes/pull/92068

**Comment by athenabot** [comment]
/sig storage

These SIGs are my best guesses for this issue. Please comment `/remove-sig <name>` if I am incorrect about one.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by pacoxu** [comment]
**Proposal 2: annotation on pvc iops limit of pod**

Why I think proposal 1 is not good? 
1. Device is not visable from application user. Based on the thought of proposal 1，user may not know the device of pod or pv. 
2. Container Runtime must be docker in proposal 1. Docker is not the only runtime of kubernetes. Container runtime can be rkt or podman,  to ignore the effect of container runtime. 

Proposal 2 details:
After open a feature gate "PVCQos=true", pod qos can be added by annotation like below.
```
annotations:
    storage.k8s.io/qos: "{"pv_name":{"iops":{"read":200,"write":200}}}"
```
Then kubelet can get the mount point of the pvc and the device id. Then we use the cgroup to limit iops and bps of the pod.
We can just edit the cgroup limit files under the pod /sys/fs/cgroup/blkio/kubepods/pod<UID>/<Container_ID>/...
For instance, to limit read iops of a pod 
```
 echo "<block_device_maj:min> <value>" > /sys/fs/cgroup/blkio/kubepods/pod<UID>/blkio.throttle.read_iops_device
```
To manage the QoS of container, it can be supported in the future.


Advantage of Proposal 2:
1. User can use any Container Runtimes. 
2. This is a k8s way, not a docker way. User have to know the pv of the pod.

This is the first/alpha MVP. If this is a suggested way to implement QoS of pvc, we can add iops/bps to container limits like cpu\memory.

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by mattcary** [comment]
I think iops limiting would be a great idea, but I'm not sure if the current cgroups implementation will effectively implement it. For example, with non-direct device access, writes are buffered in the kernel and something like 80% of them will not be accounted to a cgroup (instead they're all aggregated together). I did a little bit of experimentation here: https://gitlab.com/mattcary/blkio_cgroups/-/blob/master/data/blkio_cgroup.md (sorry that the writeup is not very polished).

If all device access is direct, then cgroup blkio limits appear to be effective, do you know if this is the case in practice? (I suspect however that it's not).

**Comment by bingerambo** [comment]
Any update on this issue?

**Comment by pacoxu** [comment]
> If all device access is direct, then cgroup blkio limits appear to be effective, do you know if this is the case in practice? (I suspect however that it's not).

@mattcary Yes, this is the limitation of this proposal. 

However,  the proposal would benifit in below two senarios.

1. Local Storage(local disk devices), better speed:
For instances, I want to use local storage(local device) to gain the storage local speed. 
These PVCs in my cluster are blocking devices.

2. rootfs (preventing being overused by some pods)
Besides, the rootfs is shared by all pods in your node, the limitation will help you make node more stable. When one pod in your node heavily uses rootfs, it may effect other pods on the same node. The limitation would help as well.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/enhancements/pull/1907 the KEP is updated.

Please add some comments if you are interested.

**Comment by pacoxu** [comment]
Some limitations in the KEP as https://github.com/kubernetes/enhancements/pull/1907#discussion_r488976076

Another proposal is like 3 levels
- unlimited
- fair
- priority with weight

New Scenarios in https://github.com/kubernetes/kubernetes/issues/27000#issuecomment-671764960

- big data

**Comment by immanuelfodor** [comment]
Unstale pls

**Comment by nu007a** [comment]
Unstale pls

**Comment by jeremybusk** [comment]
Unstale pls

**Comment by askervin** [comment]
Current status of blockio throttling in container runtimes:
- CRI-O: support released in v1.22, see [blockio PR](https://github.com/cri-o/cri-o/pull/4873).
- Containerd: a fully compatible [blockio PR](https://github.com/containerd/containerd/pull/5490) is open.

In these PRs Kubernetes user annotates a pod with blockio classes that apply to all or selected containers in the pod. The container runtime loads a node-specific [blockio configuration file](https://github.com/intel/goresctrl/blob/main/doc/blockio.md), and converts container's blockio class to [OCI blockio parameters](https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#block-io) that are finally applied by runc.

Annotation example:
```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
  annotations:
    blockio.resources.beta.kubernetes.io/pod: "lowprio"
    blockio.resources.beta.kubernetes.io/container.myconta: "normal"
    blockio.resources.beta.kubernetes.io/container.mycontb: "highprio"
```
This assigns all containers of mypod to the "lowprio" blockio class with two exceptions: the myconta container gets the blockio parameters of the "normal" class, and mycontb of the "highprio" class.

Note that high priority blockio containers, that is those that tweak the I/O scheduler weight of a block device, the I/O scheduler must support weights, like [bfq](https://www.kernel.org/doc/html/latest/block/bfq-iosched.html).

**Comment by pacoxu** [comment]
@askervin if this is merged, we can use the annotation for pod directly if the container runtime is contained or cri-o after upgrading.

It seems that there is no work on the Kubernetes side. However, there are several questions:
- how apiserver knows what `blockio classes` are available on container runtime? kubelet may expose the blockio class names it supported to node labels. 
- can we set the default blockio class on the contained side to make all pods under limitation? However, by default, no blockio should be applied.
- if a wrong blockio class is set for a pod, what is the behavior now?
- Can we save `blockio classes` configuration into a configmap and sync it to `/etc/containers/blockio.yaml` by kubelet or an agent?

The design has some commonalities in design with @mattcary ‘s proposal in https://github.com/kubernetes/enhancements/pull/1907#discussion_r488976076

> unlimited, no restriction on IOPS, which is what we currently do
> 
> fair, all pods using the PVC/volume split IOPS fairly. This does require a pretty complicated controller to track PV usage and update all the nodes with how usage should split, especially if we want to base throttling on actual usage (eg, pods that aren't hammering the device don't get the same share as a more active pod), but this may be what users actually want
> 
> priority, pods with some sort of annotation get unlimited IOPS, all other pods get a fixed share
>

**Comment by askervin** [comment]
> It should be possible to limit ephemeral storage as well.

This will happen, because the block I/O class configuration on a cluster node maps I/O class name (like "high-prio" or "throttled") directly on local block devices available on that node.

> so scheduler should be aware of that just like cpu/memory.

This is excellent point, glad you brought it up. Indeed current pod annotations do not affect scheduling, and therefore pods may be scheduled on nodes where support for I/O classes is not available, or certain classes are missing.

There is [KEP-3008](https://github.com/kubernetes/enhancements/pull/3004) (by @marquiz) that replaces unofficial annotations with well-defined QoS classes, that are recognized by the scheduler, too. Please feel welcome to take a look at the KEP and express concerns, support and participate the discussion!

**Comment by duanmengkk** [comment]
+1

**Comment by d-honeybadger** [comment]
@askervin Would you happen to know if it'd be possible to have dynamic blkio setup? To elaborate on what I mean by that:
In https://github.com/containerd/containerd/pull/5490, containerd lists all available devices at startup. But the way many kubernetes storage providers operate, they would create a new disk device when a volume is mounted in a pod (I was specifically looking at Longhorn and Ceph). So, say, blockio config applies to all `/dev/sd[a-z]` devices and at containerd startup there are only `/dev/sda` and `/dev/sdb`. One creates a pod with persistent volume provisioned by one of those storage providers. That means a new disk device is added, e.g. `/dev/sdc`. This new device isn't covered by blockio settings though and not throttled, so blockio class annotations aren't helping much. _If_ containerd could look up the current list of disks at the time the container is created though, it seems blockio classes might be useful with storage providers other than just local volumes.
I'm likely missing some big potential issues here, but would be curious to know what those are.

**Comment by askervin** [comment]
Hi @d-honeybadger,

When a new container is being created, this patch (re-)reads the blockio configuration file from the system. At that point it matches device wildcards in the file to whatever is in the file system. Therefore the implementation should already apply parameters to new devices under `/dev/`, given that they appear before `CreateContainer` is handled by containerd's CRI plugin. Do you observe different behavior?

**Comment by d-honeybadger** [comment]
> Hi @d-honeybadger,
> 
> When a new container is being created, this patch (re-)reads the blockio configuration file from the system. At that point it matches device wildcards in the file to whatever is in the file system. Therefore the implementation should already apply parameters to new devices under `/dev/`, given that they appear before `CreateContainer` is handled by containerd's CRI plugin. Do you observe different behavior?

:thinking: Hmm yeah. Was running [this nightly build](https://github.com/containerd/containerd/actions/runs/2907917827) with a test blockio class:
```
Classes:
  ThrottledIO:
  - Devices:
      - /dev/sd[c-z]
    ThrottleReadIOPS: 10k
    ThrottleWriteIOPS: 5k
    ThrottleReadBps: 50M
    ThrottleWriteBps: 10M
```
The disks added to `linux.resources.blockIO` were always the ones present during containerd restart. So the one created by Longhorn (it was /dev/sdh 8:112) wasn't throttled. Then I rtried estarting containerd _with_ the deployment that uses that Longhorn disk, and after that 8:112 was added to `linux.resources.blockIO`. Now once that deployment got deleted and the disk gone, it actually started causing RunContainerError's cause it was still trying to to throttle 8:112 which was no longer present.
