### ISSUE TITLE
Configmap mounted with subPath doesn't get reloaded automatically

### ISSUE THREAD

**Issue by kycfeel** [kubernetes/kubernetes#92296]
**What happened**:
The configmap mounted with `subPath` is not getting reloaded automatically. 

**What you expected to happen**:
The configmap change gets updated to a mounted pod automatically.

**How to reproduce it (as minimally and precisely as possible)**:
Mount a file stored as configmap to a pod with `subPath`, make a change at the configmap, and watch the change gets updated to the container.

```
 volumeMounts:
          - name: my-config
            mountPath: /etc/myapp/myconfig.conf
            subPath: myconfig.conf
```

```
volumes:
          - name: my-config
             configMap:
                 name: my-config
```
**Anything else we need to know?**:
The automatic configmap reload works well If I don't use `subPath`.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.2 
- Cloud provider or hardware configuration: DigitalOcean DOKS
- OS (e.g: `cat /etc/os-release`): Debian do-kube-1.16.2-do.1
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
