### ISSUE TITLE
Container image is different from pod spec.

### ISSUE THREAD

**Issue by pckhoi** [kubernetes/kubernetes#92297]
**What happened**:

I updated my deployment with new image (new tag) and the pod run fine but my changes doesn't seem to load. I run `kubectl get pod <pod name> -o yaml` and discovered the container was using an old image despite pod image already updated:

```
...
spec:
  containers:
    - name: "scheduler"
      image: gcr.io/helpful-emitter-237702/wrgl-jobscheduler:dev-1592562956
...
status:
  containerStatuses:
    - containerID: docker://6ab2bcd3a96c3dd2fd18dce9eb2be47c2896ac8864f1d9bef539daeaa6397012
      image: gcr.io/helpful-emitter-237702/wrgl-jobscheduler:dev-1592562051
```

**What you expected to happen**:

Container image should be the same as in pod spec.

**How to reproduce it (as minimally and precisely as possible)**:

I have never seen this happen before so there is no obvious condition for this to happen in my mind. Will update this part as I have more time.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE regular channel
- OS (e.g: `cat /etc/os-release`):
```
BUILD_ID=12371.208.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=9e1168898f7dfad439286058801d5e6135b89ae3
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=77
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=77
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
ID=cos
```
- Kernel (e.g. `uname -a`): 4.19.109+
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
