### ISSUE TITLE
anyOf schema validation doesn't work as expected

### ISSUE THREAD

**Issue by wmuizelaar** [kubernetes/kubernetes#92307]
**What happened**:
I created a CRD: 

```
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: simplethings.example.com
spec:
  group: example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
                  pattern: "^[a-z0-9][a-z0-9\\-]{0,28}[a-z0-9]$"
            spec:
              properties:
                environment:
                  enum:
                    - "one"
                    - "two"
                    - "three"
                  type: "string"
                trustees:
                  items:
                    type: "string"
                  type: "array"
              type: "object"
              anyOf:
                - properties:
                    trustees:
                      items:
                        pattern: "^group:[a-z0-9_\\-]+@example\\.com$"
                - properties:
                    trustees:
                      items:
                        pattern: "^user:[a-z]+@example\\.com$"
              required:
                - environment
  scope: Namespaced
  names:
    plural: simplethings
    singular: simplething
    kind: SimpleThing
```

The special interesting section from this is that the trustees should be an array that can consist of both users and groups, identified by their email address. So when I submit this:

```
---
kind: SimpleThing
apiVersion: example.com/v1alpha1
metadata:
  name: frieps
spec:
  environment: one
  trustees:
    - group:frieps@example.com
``` 
it works fine.

When I submit this:
```
---
kind: SimpleThing
apiVersion: example.com/v1alpha1
metadata:
  name: frieps
spec:
  environment: one
  trustees:
    - user:wmuizelaar@example.com
```
it also works fine.

But when I try to combine both kinds of values:

```
---
kind: SimpleThing
apiVersion: example.com/v1alpha1
metadata:
  name: frieps
spec:
  environment: one
  trustees:
    - group:frieps@example.com
    - user:wmuizelaar@example.com
```
it gives out an error:
```
The SimpleThing "frieps" is invalid:
* : Invalid value: "": "spec" must validate at least one schema (anyOf)
* spec.trustees: Invalid value: "": spec.trustees in body should match '^group:[a-z0-9_\-]+@example\.com$'
```

**What you expected to happen**:
I would expect that the latest given specfile would work as well.

**How to reproduce it (as minimally and precisely as possible)**:
Create the CRD in the issue, and try to apply the last SimpleThing yaml-spec.

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Running on Minikube: 
```
minikube version: v1.11.0
```

**Comment by liggitt** [comment]
This is working properly. Your current schema expresses the following:

`spec` must be validated by any of the following:
1. a `trustees` property whose items all match `^group...`
1. a `trustees` property whose items all match `^user...`

To apply the anyOf rules per-item, you need to put the anyOf attribute inside the items schema definition like this:
```yaml
            spec:
              properties:
                environment:
                  enum:
                    - "one"
                    - "two"
                    - "three"
                  type: "string"
                trustees:
                  items:
                    type: "string"
                    anyOf:
                    - pattern: "^group:[a-z0-9_\\-]+@example\\.com$"
                    - pattern: "^user:[a-z]+@example\\.com$"
                  type: "array"
              type: "object"
              required:
                - environment
```
