### ISSUE TITLE
Delete Pod is stuck at `Terminating`

### ISSUE THREAD

**Issue by l1b0k** [kubernetes/kubernetes#92368]
**What happened**:  Delete Pod is stuck at `Terminating`

**What you expected to happen**:  Delete Pod.

**How to reproduce it (as minimally and precisely as possible)**:

Two main factors
1. time skew 
2. kubelet restarted

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.15

`containerGC` should clean all exited containers when Pod is `Terminating`.
As Pod is expected to be deleted, `gcPolicy` not nessery be respected.

https://github.com/kubernetes/kubernetes/blob/d140769e4d26f3a175d8a59782ea63595a9f4899/pkg/kubelet/kuberuntime/kuberuntime_gc.go#L224-L238

**Comment by tedyu** [comment]
Do you have a test which shows the problem ?

**Comment by l1b0k** [comment]
For now i can not reproduct this.
Here is the Pod info.  
```
  creationTimestamp: "2020-06-19T05:12:33Z"
  deletionTimestamp: "2020-06-17T15:14:03Z" 
  containerStatuses:
  - containerID: docker://
    image: 
    imageID: docker-pullable://
    lastState: {}
    name: 
    ready: false
    restartCount: 0
    state:
      terminated:
        exitCode: 0
        finishedAt: null
        startedAt: null
phase: Running
```

And `Terminating` last several hours  until i manually recoverd.
