### ISSUE TITLE
Move pkg/proxy to k8s.io/kube-proxy

### ISSUE THREAD

**Issue by weiqiangt** [kubernetes/kubernetes#92369]
**What would you like to be added**:

Could you please move pkg/proxy to k8s.io/kube-proxy as an individual module?

**Why is this needed**:

Some CNIs would like to implement their own kube-proxy like component to gain more performance and thus would like to reuse kube-proxy code.  e.g. https://github.com/vmware-tanzu/antrea/pull/772 .

**Comment by athenabot** [comment]
/sig network

These SIGs are my best guesses for this issue. Please comment `/remove-sig <name>` if I am incorrect about one.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by cmluciano** [comment]
I'm also starting to work on the kube-proxy config changes so I can probably help out here if this is something we want to push forward

**Comment by thockin** [comment]
I don't object to this in theory.  I expect it will expose a number of deps
to other k/k packages which will need to either be broken or the targets
will have to be moved up-and-out into leaf repos.  I also want to be
careful about what we claim is a "supported" API.  Today, it's all internal
which gives us a lot of freedom.  If we want to support APIs more widely,
we will need to think hard about the shape of the APIs.

**Comment by uablrek** [comment]
As I think as extending `kube-proxy` with more features or proxiers is a closed path, creating specialized proxiers must be the way forward.

I think there will be more custom-made stand-alone proxiers in the future living side-by-side with `kube-proxy` and selected with the `service.kubernetes.io/service-proxy-name` label;
```
apiVersion: v1
kind: Service
metadata:
  name: special-need-service
  labels:
    service.kubernetes.io/service-proxy-name: custom-proxy
```

I think now people copy code from `kube-proxy` in a kind of "wild-west" manner. IMO the ideal option would be to make the API that the "meta-proxier" uses official and provide the watching of services, endpoint-slices etc as a library.

@sbezverk I think have valuable and fresh experience in this area from the work with https://github.com/sbezverk/nfproxy.

A missing piece I see immediately is initialization/configuration. Here I would like to allow custom-made stand-alone proxiers to use the same config as the regular `kube-proxy` for instance with some section that the regular `kube-proxy` ignores, a bit like the existing `ipvs` and `iptables` sections;
```
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
...
iptables:
  masqueradeAll: false
ipvs:
  excludeCIDRs: null
  scheduler: ""
custom-configs:
  - sctp-proxier:
...
```
The reasons are that some params may me needed also by cutom proxiers (or the proxy library-code) and repeating them is error prone but also this is an indication that custom proxiers is something accepted, like CRI or CNI plugins.

I have a possible example/use-case; The current SCTP load-balancing in `kube-proxy` is insufficient for some applications and I see a possibility to create a custom SCTP-proxier that will *only* handle external services (receiving external traffic).
