### ISSUE TITLE
Terminate Guaranteed pods without changing their cgroup cpuset

### ISSUE THREAD

**Issue by nicolacdnll** [kubernetes/kubernetes#92377]
**What would you like to be added**:

I would like that pods spun with a Guaranteed QoS class stay in this QoS class for their entire lifecycle, including when they are terminating. Or, at least, I would like to have a mechanism to force this. Currently, this is not the case and, right before terminating a pod, Kubernetes ~~changes the QoS class from Guaranteed to Burstable (in my tests)~~ resets the cgroup cpuset of the pod; allowing Guaranteed pods to be scheduled on `SystemReserved` resources.

**Why is this needed**:

One use of the Guaranteed QoS class is to deploy those pods, that are resource hogs, not in `SystemReserved` resources (e.g., a cpuset). However, changing the ~~QoS class~~ cgroup cpuset of these pods allows them to be scheduled on these `SystemReserved` resources for the time needed to shutdown the pods. A time that, in some cases, amounts to 10+ seconds.

I believe that this behavior isn't documented, nor it's intuitive. Or at least it wasn't for me.

**Current workaround**:

So far, the only workaround I've found (see the example that follows) to minimize the effect of this behavior is to use the lifecycle `preStop` hook to kill the hogging processes inside the containers before the pod QoS class gets changed:

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
spec:
  selector:
    matchLabels:
      app: stress
  replicas:  1
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: progrium/stress
        args: ["-c", "15"]
        resources:
          limits:
            cpu: 10
            memory: "1024Mi"
        lifecycle:
          preStop:
            exec: # Workaround
              command: ["/bin/bash","-c","while pkill stress; do sleep 1; done"]
```

/area kubelet
/area app-lifecycle 
/sig node
