### ISSUE TITLE
RoleBinding referring to cluster-admin grants access to privileged psp

### ISSUE THREAD

**Issue by jlacoline** [kubernetes/kubernetes#92373]
**What happened**:

A RoleBinding referring to the `cluster-admin` role grants `use` verb on `privileged` podsecuritypolicy to the user within the current namespace.

**What you expected to happen**:

According to the [documentation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles), in the case of a `RoleBinding` (not `ClusterRoleBinding`), I can expect the user to be granted full access ONLY to resources that are at the namespace scope. Since psp is a cluster-wide resource, the RoleBinding should not give any permission on this kind of resource.

**How to reproduce it (as minimally and precisely as possible)**:

Here is the script I use to reproduce this:

```bash
kubectl delete ns pspthings
kubectl apply -f ./base_sa.yaml

echo "=== Before widlcard ==="
echo "psp in default"
kubectl auth can-i --as=system:serviceaccount:pspthings:some-sa use podsecuritypolicy/privileged -n default
# result: no
echo "psp in pspthings"
kubectl auth can-i --as=system:serviceaccount:pspthings:some-sa use podsecuritypolicy/privileged -n pspthings
# result: no

kubectl apply -f ./wildcard_role.yaml

echo "=== After widlcard ==="
echo "psp in default"
kubectl auth can-i --as=system:serviceaccount:pspthings:some-sa use podsecuritypolicy/privileged -n default
# result: no
echo "psp in pspthings"
kubectl auth can-i --as=system:serviceaccount:pspthings:some-sa use podsecuritypolicy/privileged -n pspthings
# result: yes
```
base_sa.yaml:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: pspthings
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: some-sa
  namespace: pspthings
```
wildcard_role.yaml:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: localwidlcard  # basically the same as cluster-admin but as a local Role
  namespace: pspthings
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: localwidlcard
  namespace: pspthings
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: localwidlcard
subjects:
- kind: ServiceAccount
  name: some-sa
  namespace: pspthings
```

**Anything else we need to know?**:

The script reproduces the issue on a newly created "kind" cluster without any specific configuration 

I cannot explain why the output of `kubectl auth can-i` changes depending on the namespace, since this is about accessing a cluster-wide resource

I could not find any documentation describing a specific behavior of the `use` verb that could explain this

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Bare metal cluster
- OS (e.g: `cat /etc/os-release`): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.13.0-38-generic
- Install tools: kubespray
