### ISSUE TITLE
Dual Stack Caveats

### ISSUE THREAD

**Issue by Queuecumber** [kubernetes/kubernetes#92451]
**What would you like to be added**: Better documentation of the caveats for building a dual stack cluster

**Why is this needed**:

Based on the language at https://kubernetes.io/docs/concepts/services-networking/dual-stack/ dual stack sounds like an alpha, but functional, experience. There are a number of caveats to this, and I think in particular the "Known Issues" section needs to be updated. 

I recently set up a dual stack cluster to test the maturity of dual stack. This is a "bare metal" cluster of VMs set up using kubeadm with calico networking. I found that there are a number of issues.

The first thing that should be documented is that the service cluster cidr for IPv6 is limited to a /112 or fewer (kep reference https://github.com/kubernetes/enhancements/pull/1534). Since /64 is the standard prefix length for IPv6 this is surprising and while not a major problem should be documented because it causes the api server to throw an error and fail to start.

Next it should be documented that dual stack is not fully functional on bare metal (ref https://github.com/kubernetes/kubernetes/issues/91940) unless you are willing to jump through some fairly major hoops (https://github.com/kubernetes/kubernetes/issues/42125#issuecomment-494669638). The docs should state that the current setup only works with a cloud provider that sets both IPv4 and IPv6 InternalIP addresses.

Finally even after resolving those issues, the cluster which I am working with still has two major faults. ~~For one I am unable access the internet from pods, using both IPv4 and IPv6. I have no idea why, and I even added the appropriate GUA routes for the IPv6 network, I'm not convinced this is a dual stack issue yet.~~ (This was a Calico configuration problem see https://github.com/projectcalico/calico/issues/2954 or make sure your pod GUAs are routable)

Next, I seem to be unable to create IPv4 services. Here is an example service definition:

```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: ClusterIP
  ipFamily: IPv4
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
```
And here it is listed after creation: 

```
NAMESPACE              NAME               TYPE           CLUSTER-IP                EXTERNAL-IP        PORT(S)
ingress-nginx          ingress-nginx      ClusterIP      2001:db8:245::23e6   <none>             80/TCP,443/TCP
```

As you can see its address is IPv6 even though I explicitly requested the IPv4 ipFamily. My default service type is IPv6.

Here is the kubeadm configuration I am using for reference:

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: yt289r.cls0m6w4mz5juvjz
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 2001:db8:100::10
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: master_host
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  kubeletExtraArgs:
    cloud-provider: external
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.18.2
apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
certificatesDir: /etc/kubernetes/pki
clusterName: test
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16,2001:db8:245::/64
  serviceSubnet: 2001:db8:245::/112 ,10.245.0.0/16
scheduler: {}
featureGates:
  IPv6DualStack: yes
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
```

Note that I replaced my GUA prefix with 2001:db8::/32 and redacted other sensitive information.

Lastly, it would be nice if that page linked to some sort of overall status document or to each of the individual issues/PRs related to dual stack work. Tracking down all of the various KEPs, issues, and PRs that I needed to piece this together was quite a task. It would be really convenient of there was a one stop place to track the progress of dual stack implementation and it seems like the public documentation for the feature would be a good place for it.

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by Queuecumber** [comment]
As an update, if I switch the order of the service IP cidrs so that Ipv4 is first (and therefor the default) e.g.:

```
serviceSubnet: 10.245.0.0/16,2001:db8:245::/112
```

Then I can make an IPv6 service by requesting it using the `ipFamily` field e.g.: 

```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-6
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  ipFamily: IPv6
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
```

Gives an IPv4 and an IPv6 service:

```
NAME                     TYPE           CLUSTER-IP                EXTERNAL-IP   PORT(S)                     
ingress-nginx            LoadBalancer   10.245.40.193             <pending>     80:30001/TCP,443:32076/TCP   
ingress-nginx-6          LoadBalancer   2001:db8:245::709d   <pending>     80:32533/TCP,443:30482/TCP
```

It's only when the default service type is IPv6 that I cannot create an IPv4 service by requesting it in the `ipFamily` field, so I think this is a bug.
