### ISSUE TITLE
exec probe timeout failures cannot trigger container restart

### ISSUE THREAD

**Issue by tnqn** [kubernetes/kubernetes#92464]
**What happened**:
When using containerd as CRI runtime, a Pod with exec liveness probe cannot be restarted by timeout errors, though the errors were detected and liveness probe events were recorded correctly:
```
  Normal   Created    2m6s                kubelet, k8s-01    Created container test
  Normal   Started    2m6s                kubelet, k8s-01    Started container test
  Warning  Unhealthy  2s (x12 over 112s)  kubelet, k8s-01    Liveness probe errored: rpc error: code = DeadlineExceeded desc = failed to exec in container: timeout 2s exceeded: context deadline exceeded
```
```
Containers:
  test:
    Container ID:  containerd://399a7b6db1b32cc49df9723a9f30217b3d0e9bbc1424272c0a2fdc293ab74bb6
    Image:         nginx
    Image ID:      docker.io/library/nginx@sha256:21f32f6c08406306d822a0e6e8b7dc81f53f336570e852e25fbe1e3e3d0d0133
    Port:          <none>
    Host Port:     <none>
    Command:
      sleep
      3600
    State:          Running
      Started:      Wed, 24 Jun 2020 04:46:06 -0700
    Ready:          True
    Restart Count:  0
    Liveness:       exec [sleep 4] delay=0s timeout=2s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-24hfm (ro)
```

The reason is the errors other than `exec.ExitError` are converted into `Unknown` Result with error returned, causing kubelet throws away the result.
https://github.com/kubernetes/kubernetes/blob/4de511a4cfdb8e49e804be18245911bf3270fb2f/pkg/probe/exec/exec.go#L61-L70

**What you expected to happen**:
Like http and tcp probes, exec timeout errors should be converted as `Failure` Result and should trigger restarting container.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use containerd as CRI
2. Create a Pod and make its exec probe timeout
```
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  restartPolicy: Always
  containers:
  - name: test
    image: nginx
    command:
      - sleep
      - "3600"
    livenessProbe:
      timeoutSeconds: 2
      exec:
        command:
        - sleep
        - "4"
```
The Liveness probe error events will be generated but the container won't be restarted.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: containerd v1.3.4

**Comment by tnqn** [comment]
Created https://github.com/kubernetes/kubernetes/pull/92465 which may fix this.

**Comment by casret** [comment]
Any workarounds?  This is causing one of my pods to fail thousands of checks but stay up `Warning  Unhealthy  2m59s (x11089 over 15h)`

**Comment by tnqn** [comment]
> Any workarounds? This is causing one of my pods to fail thousands of checks but stay up `Warning Unhealthy 2m59s (x11089 over 15h)`

A workaround is using `timeout` to wrap the exec command so that the command can fail with a non-zero exit code which is respected by the kubelet probe code. For example:
```
    livenessProbe:
      timeoutSeconds: 3 # If the desired timeout is greater than 1 second, this value must be specified and greater than the timeout specified in exec command so that that one will fail first.
      exec:
        command:
        - timeout
        - "2"
        - <THE REAL COMMAND>
```

BTW, https://github.com/kubernetes/kubernetes/pull/94115 should fix this.
