### ISSUE TITLE
Want to Upgrade elastissearch version to 7.7 using official elasticsearch docker image instead of custom docker image for upgradation

### ISSUE THREAD

**Issue by akshatailakal** [kubernetes/kubernetes#92541]
I am trying to upgraded pods with 7.7 version of elasticsearch. Unable to do so. below is values.yaml. Referring to here https://www.docker.elastic.co/r/elasticsearch/elasticsearch-oss:7.7.1 for offical docker image
```
cluster:
    name: elastic-x-pack
replicaCount: 
  client: 2
  data: 2
  master: 3
  minimum_master_nodes: 2
image:
  registry: docker.elastic.co
  name: elasticsearch/elasticsearch-oss
  tag: 7.7.1
  pullPolicy: Always
service:
  type: NodePort
  http:
    externalPort: 30000
    internalPort: 9200
  tcp:
    externalPort: 30112
    internalPort: 9300
opts: -Xms256m -Xmx256m
resources: {}

global:
  elasticsearch:
    storage:
      data:
        class: standard
        size: 3Gi
      snapshot:
        class: standard 
        size: 5Gi
        accessModes: [ ReadWriteMany ]
        name: data-snapshot
  cluster:
    features:
      DistributedTracing: test
  ignite:
    registry: test
```
But pods are not running and are in CrashLoopBackOff state. below is the description of the pod

```
Name:           elastic-cluster-elasticsearch-cluster-client-685d698-jf7bb
Namespace:      default
Priority:       0
Node:           ip-172-31-38-123.us-west-2.compute.internal/172.31.38.123
Start Time:     Fri, 26 Jun 2020 09:31:23 +0000
Labels:         app=elasticsearch-cluster
                component=elasticsearch
                pod-template-hash=685d698
                release=elastic-cluster
                role=client
Annotations:    <none>
Status:         Running
IP:             10.233.68.58
Controlled By:  ReplicaSet/elastic-cluster-elasticsearch-cluster-client-685d698
Init Containers:
  init-sysctl:
    Container ID:  docker://d83c3be3f4d7ac1362599d115813d6cd1b1356959a5a2784c1f90f3ed74daa69
    Image:         busybox:1.27.2
    Image ID:      docker-pullable://busybox@sha256:bbc3a03235220b170ba48a157dd097dd1379299370e1ed99ce976df0355d24f0
    Port:          <none>
    Host Port:     <none>
    Command:
      sysctl
      -w
      vm.max_map_count=262144
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 26 Jun 2020 09:31:24 +0000
      Finished:     Fri, 26 Jun 2020 09:31:24 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-d7b79 (ro)
Containers:
  elasticsearch-cluster:
    Container ID:   docker://74822d62d876b798c1518c0e42da071d661b2ccdbeb1fe40487044a9cc07e6f4
    Image:          docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1
    Image ID:       docker-pullable://docker.elastic.co/elasticsearch/elasticsearch-oss@sha256:04f0a377e55fcc41f3467e8a222357a7a5ef0b1e3ec026b6d63a59465870bd8e
    Ports:          9200/TCP, 9300/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    78
      Started:      Fri, 26 Jun 2020 09:32:26 +0000
      Finished:     Fri, 26 Jun 2020 09:32:33 +0000
    Ready:          False
    Restart Count:  3
    Liveness:       tcp-socket :transport delay=300s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http/_cluster/health delay=10s timeout=5s period=10s #success=1 #failure=3
    Environment:
      NAMESPACE:     default (v1:metadata.namespace)
      NODE_NAME:     elastic-cluster-elasticsearch-cluster-client-685d698-jf7bb (v1:metadata.name)
      CLUSTER_NAME:  elastic-x-pack
      ES_JAVA_OPTS:  -Xms256m -Xmx256m
      NODE_DATA:     false
      HTTP_ENABLE:   true
      NETWORK_HOST:  _site_,_lo_
      NODE_MASTER:   false
    Mounts:
      /data from storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-d7b79 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  storage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-d7b79:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-d7b79
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                                                  Message
  ----     ------     ----                ----                                                  -------
  Normal   Scheduled  112s                default-scheduler                 Successfully assigned default/elastic-cluster-elasticsearch-cluster-client-685d698-jf7bb to 
  Normal   Pulled     111s                kubelet, DNS name                 Container image "busybox:1.27.2" already present on machine
  Normal   Created    111s                kubelet, DNS name                 Created container init-sysctl
  Normal   Started    111s                kubelet, DNS name                 Started container init-sysctl
  Normal   Pulled     49s (x4 over 110s)  kubelet, DNS name           Container image "docker.elastic.co/elasticsearch/elasticsearch-oss:7.7.1" already present on machine
  Normal   Created    49s (x4 over 110s)  kubelet,DNS name              Created container elasticsearch-cluster
  Normal   Started    49s (x4 over 110s)  kubelet,DNS name                   Started container elasticsearch-cluster
  Warning  BackOff    5s (x9 over 94s)    kubelet,DNS name                  Back-off restarting failed container
```
