### ISSUE TITLE
Multi Reference Key for ConfigMap and Secret 

### ISSUE THREAD

**Issue by VishalLahane** [kubernetes/kubernetes#92551]
**What would you like to be added**:
Using existing configMap or secrete keys create a new environment variable using multiple keys from configMap or environment variable.

Example:

env:
- name: SEVERHOST_PORT
  valueFrom:
    configMapRef:
      key: SERVER_HOST_NAME:SERVER_HOST_PORT
      name: db-server-details

like this, it should give me **SEVERHOST_PORT=demosever.demodomain.com:7744**

**Why is this needed**:
We wanted a minimum object of Kubernetes to be created over cluster if above is possible then we can pass data to multiple applications whichever format they needed, like above is key3_data=key1_data=key2_data. (So we will have one object serving multiple applications) Here colon can be any separator, for us currently : (colon is required) but if we can make it for any character useful for all users.

My idea is allowing a user to pass it as an array-like 
    key: [$SERVER_HOST_NAME":"$SERVER_HOST_PORT]

I hope the above idea/ requirement makes sense.

**Comment by VishalLahane** [comment]
/sig/architecture
/sig usability
/sig scalability
/sig cli
/sig storage

**Comment by liggitt** [comment]
This can be accomplished by defining the individual envvars, then composing envvars into a new envvar:

```yaml
env:
- name: SERVERHOST
  valueFrom:
  configMapKeyRef:
    name: db-server-details
    key: SERVER_HOST_NAME
- name: SERVERPORT
  valueFrom:
  configMapKeyRef:
    name: db-server-details
    key: SERVER_HOST_PORT
- name: SERVERHOST_PORT
  value: $(SERVERHOST):$(SERVERPORT)
```
