### ISSUE TITLE
kubectl config set-credentials  add exec info error

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#92593]
**What happened**:

[root@master01 .kube]# kubectl api-versions
error: couldn't get available api versions from server: Get https://192.168.198.154:6443/api?timeout=32s: getting credentials: decoding stdout: yaml: line 3: could not find expected ':'
[root@master01 .kube]# 
```
[root@master01 .kube]# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://192.168.198.154:6443
  name: cluster1
- cluster:
    insecure-skip-tls-verify: true
    server: https://1.2.3.4
  name: mycluster
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.pem
    server: https://192.168.198.154
  name: test
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://192.168.198.154
  name: test2
contexts:
- context:
    cluster: cluster1
    user: admin
  name: context-cluster1-admin
current-context: context-cluster1-admin
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - /tmp
      - /root
      command: ls
      env: null
- name: cluster-admin
  user:
    auth-provider:
      config:
        client-id: foo
      name: oidc
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - arg1
      - arg2
      command: /path/to/the/executable
      env:
      - name: key1
        value: val1
      - name: key2
        value: val2
- name: my-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    password: mark-
    username: mark-
```

is this right  apiVersion: client.authentication.k8s.io/v1beta1

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
[root@master01 .kube]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
