### ISSUE TITLE
1000+ services in the same namespace will degrade pod start time & eventually prevent pods from starting

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/kubernetes#92615]
From: https://github.com/kubernetes/kubernetes/issues/92226

**What happened**:

Having a modest number of services in your namespace will eventually degrade pod start time and after a certain number of services pods will fail to start.

**What you expected to happen**:

The number of services in a namespace should not prevent a pod from starting or degrade its start time.

**How to reproduce it (as minimally and precisely as possible)**:

Example here: https://github.com/knative/serving/issues/8498

**Anything else we need to know?**:

The culprit is the large list of env vars on pods coming from service links (which are on by default) 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration:  GKE

**Comment by mattmoor** [comment]
To clarify, 1000 Knative Services currently translates to about 2000 Cluster IP services and 1000 ExternalName services.

**Comment by schweikert** [comment]
One cause for bad performance with a large number of environment variables can be bash. This code seems to scale O(n^2) with number of variables, and is called on bash startup: https://github.com/bminor/bash/blob/d894cfd104086ddf68c286e67a5fb2e02eb43b7b/variables.c#L4197

**Comment by mattmoor** [comment]
Neither of the containers in question use bash as their entrypoint, both are built from `gcr.io/distroless/static:nonroot`

**Comment by hanumanthan** [comment]
@mattmoor @dprotaso I am interested in picking this up and need help.
Can you give a bit more explanation on the issue and point me to the file where this is happening. Will it pick it up from there. Thanks

**Comment by dprotaso** [comment]
@hanumanthan I'm not familiar with the K8s codebase to be able to point you to the right place. I'd probably reach out for help in the K8s slack - https://slack.k8s.io/

**Comment by dims** [comment]
xref https://github.com/kubernetes/kubernetes/issues/93399

**Comment by lingsamuel** [comment]
Could you provide a minimal reproducible example without Knative? @mattmoor @dprotaso 
I create 1000+ ExternalName services and 1500+  ClusterIP services (all ClusterIP svcs point to the same pod, if the problem is env var related, I think it doesn't matter), then start a new Pod, it starts normally and quickly.
I take a quick glance at related code, didn't find any suspicion codepath (maybe I missed something?). And I tried to start a container directly using docker with 2000+ env vars, it starts quickly.

A potential slow startup reason is the container entrypoint trying to manipulate/scan env vars, such as `bitnami/postgresql`, it does start slower than normal.

**Comment by mattmoor** [comment]
Each service is ~8 env vars, typically with long names.  Knative currently creates 2 ClusterIP and 1 ExternalName per service, and things failed for me at around 1200 Knative services.

I don't think there's anything wrong with your repro except the numbers, I'd create 1200 ExternalName and 2400 ClusterIP services.

**Comment by lingsamuel** [comment]
Still can't repro, I have 1400 ExternalName and 2900 ClusterIP now.

A potential slow startup reason is the container entrypoint trying to manipulate/scan env vars, such as `bitnami/postgresql`, it does start slower (0/1 Running to 1/1 Running) than normal. Is your test image do such thing?

**Comment by mattmoor** [comment]
No, this was a pretty trivial Go HTTP server on GKE.

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle frozen

since the issue needs more information, removing the freeze to make sure we are getting traction here.

@mattmoor @dprotaso reading comments I see that the attempt to repro this failed. Can you please provide more information on how to repro this and why you believe the culprit is env variables. Also, what runtime do you use to run containers.

/triage needs-information
/sig scalability

**Comment by dprotaso** [comment]
/lifecycle frozen

Here's an example - with about ~1050 of these services (on a single node kind cluster) causes the deployment's container to fail to start

```yaml
apiVersion: v1
kind: Service
metadata:
  generateName: long-name-name-name-name-long-name-name-name-name-long-name-nam
spec:
  type: ClusterIP
  ports:
    - name: long-name-name-name-name-long-name-name-name-name-long-nam-http
      port: 80
      targetPort: 8080
    - name: long-name-name-name-name-long-name-name-name-name-long-nm-https
      port: 443
      targetPort: 8443
    - name: long-name-name-name-name-long-name-name-name-name-long-xmetricz
      port: 9090
      targetPort: 9090
    - name: long-name-name-name-name-long-name-name-name-name-long-xhealthz
      port: 9091
      targetPort: 9091
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/knative-samples/helloworld-go
        ports:
        - containerPort: 80
```


containerd logs are

```
2021-06-25T01:25:51.427945289Z stderr F standard_init_linux.go:228: exec user process caused: argument list too long
```


If you see the original references issue you can mitigate this by disabling service links - but changing the default wasn't an option so hence I opened this performance tracking issue. Essentially the explosion of env vars causes massive runc configs to be written and you eventually hit some linux limits when starting the process.
