### ISSUE TITLE
kubectl config set error

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#92629]
**What happened**:
```
[root@master01 ~]# kubectl config set users.test5.exec.apiVersion aaa
error: unable to parse one or more field values of users.test5.exec.apiVersion

[root@master01 ~]# kubectl config set users.test4.auth-provider.name aaa
error: unable to parse one or more field values of users.test4.auth-provider.name

[root@master01 ~]# kubectl config set users.test3.client-key aaaa
Property "users.test3.client-key" set.
```
```
[root@master01 ~]# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://192.168.198.154:6443
  name: cluster1
- cluster:
    insecure-skip-tls-verify: true
    server: https://1.2.3.4
  name: mycluster
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.pem
    server: https://192.168.198.154
  name: test
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://192.168.198.154
  name: test2
contexts:
- context:
    cluster: cluster1
    user: admin
  name: context-cluster1-admin
- context:
    cluster: cluster1
    user: my-admin
  name: my-admin-cluster1
- context:
    cluster: cluster1
    user: my-admin2
  name: my-admin2-cluster1
- context:
    cluster: cluster1
    user: test1
  name: mytest
current-context: context-cluster1-admin
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: cluster-admin
  user:
    auth-provider:
      config:
        client-id: foo
      name: oidc
    exec:
      apiVersion: client.authentication.k8s.io/v1beta
      args:
      - arg1
      - arg2
      command: /path/to/the/executable
      env:
      - name: key1
        value: val1
      - name: key2
        value: val2
- name: my-admin
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InRBVTNnSm1WRm1fYm15aDYySEZPUUNNOVdKUWJTeGE5aUx5UVFUNmFJT0UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tbDlqd2oiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjJmNmI0OTQ4LWZmNDgtNDNhNy05MWEzLWU4NTEzMmYxMGRlOCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.fzjDVXK0aS28Nn9p8g8GtXWhknHj5mOgtfWtDf5IWMhsTKB9Dwp24XMynXzFiQ-Au7aPet5OdoGh69CoBtHpHQnHItivvpp776QSK1_xDx7LrPbi6RnX364dSVoEK6IfAmXjdX4MY-NjYtkLPNtWF-37cTNEUdQfV3XNtUt0rHXT3-1nO9jA07Uwg7XhWPy3oj1tuNPNFEdeytrHBGiU3WjCjF1O8xow_F9-ByqAP8qmUPeih9jFdRZYNm_JNhBzE1nOdnWZLbFFiusOkSh8OBfJ-UwtqV0ocxNXNtmcbw3jAJVH0wJcIsHLFRuPFXbvvIJrbnOYPn_WNeUK3ci5WA
- name: my-admin2
  user:
    password: "123456"
    username: mark
- name: test1
  user:
    password: "123456"
    username: mark
- name: test2
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InRBVTNnSm1WRm1fYm15aDYySEZPUUNNOVdKUWJTeGE5aUx5UVFUNmFJT0UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tbDlqd2oiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjJmNmI0OTQ4LWZmNDgtNDNhNy05MWEzLWU4NTEzMmYxMGRlOCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.fzjDVXK0aS28Nn9p8g8GtXWhknHj5mOgtfWtDf5IWMhsTKB9Dwp24XMynXzFiQ-Au7aPet5OdoGh69CoBtHpHQnHItivvpp776QSK1_xDx7LrPbi6RnX364dSVoEK6IfAmXjdX4MY-NjYtkLPNtWF-37cTNEUdQfV3XNtUt0rHXT3-1nO9jA07Uwg7XhWPy3oj1tuNPNFEdeytrHBGiU3WjCjF1O8xow_F9-ByqAP8qmUPeih9jFdRZYNm_JNhBzE1nOdnWZLbFFiusOkSh8OBfJ-UwtqV0ocxNXNtmcbw3jAJVH0wJcIsHLFRuPFXbvvIJrbnOYPn_WNeUK3ci5WA
- name: test3
  user:
    client-certificate: /etc/kubernetes/ssl/admin.pem
    client-key: aaaa
- name: test4
  user:
    auth-provider:
      config:
        test1: aa
        test2: bb
      name: oidc
- name: test5
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - test
      command: test
      env:
      - name: test
        value: test
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
···
[root@master01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2020-05-12T09:28:18Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
···
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
