### ISSUE TITLE
K8s Ingress spec: Headless services routing for StatefulSet pods

### ISSUE THREAD

**Issue by ivanangelov** [kubernetes/kubernetes#92639]
**What would you like to be added:**

K8s Ingress to be able to route external traffic to a specific pod of a StatefulSet which is exposed by a headless Service.

**Example:**
```
- host: <subdomain_1>.<ingress_host> 
  http:
    paths:
    - path: /
      backend:
        serviceName: <pod_name_1>.<headless_service_name>
        servicePort: <headless_service_port>

- host: <subdomain_2>.<ingress_host> 
  http:
    paths:
    - path: /
      backend:
        serviceName: <pod_name_2>.<headless_service_name>
        servicePort: <headless_service_port>
```

**Why is this needed:**

We are implementing a High availability setup for our K8s based solution. We are using a StatefulSet and would like to make use of the Horizontal Pod Autoscaler in order for our pods to be scaled on demand. We are using the NGINX Ingress Controller.

Furthermore, we have a logic that requires external traffic to be routed to a specific stateful pod based on the subdomain (or path) in the ingress host. 

We observed that NGINX Ingress confirmed that if the above-described functionality is included in the K8s Ingress Spec they would implement it. https://github.com/kubernetes/ingress-nginx/issues/3921

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by aojea** [comment]
@aledbf is not this something that is being done as part of https://github.com/kubernetes-sigs/service-apis ?

**Comment by PidgeyBE** [comment]
If you are prepared to use voyager instead of nginx as ingress controller; they seem to support this already:
https://voyagermesh.com/docs/10.0.0/guides/ingress/http/statefulset-pod/#forward-traffic-to-specific-pods-of-a-statefulset

**Comment by robscott** [comment]
Hey @ivanangelov, thanks for filing this issue! I think we may already have added something that would solve this in Kubernetes 1.19 with the option to target any resource, not just a Service, as a backend. I've got a [docs PR](https://github.com/kubernetes/website/pull/21590) that covers those updates and here's a [preview of what those updates will look like](https://5f051ed46cdd84000852e13f--kubernetes-io-vnext-staging.netlify.app/docs/concepts/services-networking/ingress/#resource-backend).

**Comment by ivanangelov** [comment]
Hello @robscott 

Thanks for the suggestion!
Actually, I need to target a backend resource of kind _Pod_ on a specific port. Does this new feature support an explicit definition of the port of the backend resource? If so, would you provide an example?

**Comment by athenabot** [comment]
@robscott
If this issue has been triaged, please comment `/remove-triage unresolved`.

If you aren't able to handle this issue, consider unassigning yourself and/or adding the `help-wanted` label.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by ivanangelov** [comment]
Hello @robscott,

I would kindly ask you to answer my previous question so we could have some clarity about how to proceed forward with the issue.

**Comment by robscott** [comment]
Thanks for the reminder, sorry I missed your follow up question! Although the API will support referencing arbitrary resources, it will depend on implementations to define which resources they want to support targeting. If you're planning on using a specific implementation, it might be good to ask the maintainers if they have plans to support targeting additional resource types in 1.19+. With that said, API config might look like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
spec:
  defaultBackend:
    resource:
      apiGroup: "v1"
      kind: Pod
      name: example
  rules:
    - http:
        paths:
          - path: /example
            pathType: Prefix
            backend:
              resource:
                apiGroup: "v1"
                kind: Pod
                name: example
```

/remove-triage unresolved
