### ISSUE TITLE
how to make readiness probe not skip certificates with HTTPS?

### ISSUE THREAD

**Issue by marybe** [kubernetes/kubernetes#92647]
I'm using readinessProbe on my container and configured it to work on HTTPS with scheme attribute. My server expects the get the certificates. how can I configure the readiness probe to support HTTPS with certificates exchange? I don't want it to skip the certificates

```
      readinessProbe:
        httpGet:
          path: /eh/heartbeat
          port: 2347
          scheme: HTTPS
        initialDelaySeconds: 210
        periodSeconds: 10
        timeoutSeconds: 5
```
