### ISSUE TITLE
Improve user experience of using scheduler policies

### ISSUE THREAD

**Issue by JamesMurkin** [kubernetes/kubernetes#92649]
**What would you like to be added**:

Either:
 - Solid documentation on how to add a policy without disrupting existing Kubernetes scheduler behaviour
 - A way to add a custom partial scheduler policy that is merged with the default

**Why is this needed**:
I'll use a basic use case for describing this issue. I would like the scheduler to fill nodes before scheduling pods on the next node, just bin pack the nodes.

This is achievable with scheduling policy priority:
 - MostRequestedPriority (https://kubernetes.io/docs/reference/scheduling/policies/)
 - RequestedToCapacityRatioPriority (https://kubernetes.io/docs/concepts/configuration/resource-bin-packing/)

So I an make a simple policy that does this, which looks like:

```
{
	"kind" : "Policy",
	"apiVersion" : "v1",
	"priorities" : [
		{"name" : "MostRequestedPriority", "weight" : 1},
	]
}
```

or 

```
{
    "kind" : "Policy",
    "apiVersion" : "v1",
    "priorities" : [
      {
        "name": "RequestedToCapacityRatioPriority",
        "weight": 1,
        "argument": {
          "requestedToCapacityRatioArguments": {
            "shape": [
              {"utilization": 0, "score": 0},
              {"utilization": 100, "score": 10}
            ],
            "resources": [
              {"name": "Cpu", "weight": 1},
              {"name": "Memory", "weight": 1}
            ]
          }
        }
      }
    ]
}
```

However the problem is this removes all Kubernetes default scheduling policies.

Meaning to add one of the above policies, you really need to get the default kubernetes policy and add one of the above to it.

This is quite painful as there doesn't seem to be a good place to find out the defaults. I have seen:
https://github.com/kubernetes/kubernetes/blob/2db6ec1db7505b092c8e50eb8f10cd3a5f9950af/pkg/scheduler/framework/plugins/default_registry.go
https://kubernetes.io/docs/reference/scheduling/policies/

However this is made worse by the fact the code seems to have values the docs don't. Such as predicates GeneralPred or HostNamePred.

If you have to somehow get the kubernetes defaults and then add to them, to do basic things like add bin packing this is very painful as:
 - There is no good place to get the default policy that you can add to
 - It will be brittle as the default may change from version to version

As mentioned above, I feel this needs one of:
 - Good docs that give you the default policy, so you can add to it
 - A way to specify a partial policy (like the above), that'll be merged with the default so you don't need to worry about what the default policies are if you are just enabling a feature, like bin packing.

Please correct me if I have missed some obvious way to do this that is painless.

**Comment by Huang-Wei** [comment]
@JamesMurkin Your understanding is correct, and I feel the pain. It's a design glitch in policy API, at least in UX side.

We have a better-designed scheduler configuration API (1.18+), where it has explicit `Enable` and `Disable` fields. So users can easily accomplish the following requirements:

- enable/disable partial plugins, without modifying defaults
- replace a plugin with another
- rearrange the order of plugins
- simply disable all defaults (using a special `*` character) without naming all of them 

May I know which k8s version you're running on? Is it possible to migrate to Kubernetes 1.18+ to give a try? In 1.18, the API is v1alpha2 and v1beta1 in 1.19.

BTW: Policy API will be deprecated in the future, so we may just maintain it by fixing bugs.

**Comment by JamesMurkin** [comment]
@Huang-Wei  Many thanks for your reply, at least that sounds very hopeful for 1.18+.

We are currently on 1.17 and may be in a position to move to 1.18+ soon and this sounds like another reason to move.

So how would I achieve what I mentioned above in 1.18? 

I.e keep the defaults while also having the scheduler use MostRequestedPriority? A brief example of config and/or docs would be great.

**Comment by Huang-Wei** [comment]
@JamesMurkin Here is an example which wraps 4 profiles inside:

- **default-scheduler:** keeps everything as-is, so workloads which doesn't set their `spec.schedulerName` will be taken over by this profile
- **image-first:** just adjust the weight of Score plugin `ImageLocality`
- **binpack:** guess this is what you want. It **replaces** default "LeastAllocated" priority with "MostAllocated" priority and gives it a huge weight
- **skip-score:** a profile to skip all PreScore/Score plugins. In other words, nodes will be randomly selected after they passed the Filter(predicates) phase.

```yaml
# use v1beta1 in 1.19
apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
leaderElection:
  leaderElect: false
profiles:
- schedulerName: default-scheduler
- schedulerName: image-first
  plugins:
    score:
      enabled:
      - name: ImageLocality
        weight: 50000
      disabled:
      - name: ImageLocality
- schedulerName: binpack
  plugins:
    score:
      enabled:
      - name: NodeResourcesMostAllocated
        weight: 50000
      disabled:
      - name: NodeResourcesLeastAllocated
- schedulerName: skip-score
  plugins:
    preScore:
      disabled:
      - name: "*"
    score:
      disabled:
      - name: "*"
```

**Comment by JamesMurkin** [comment]
@Huang-Wei  Excellent thanks for the example and explanation.

Where do you get the names of the plugins "NodeResourcesMostAllocated" and  "NodeResourcesLeastAllocated". That doesn't seem to correlate with the names I see in the docs.

Or have the names changed in 1.18? If so please link the docs and I'll close this ticket :)

**Comment by Huang-Wei** [comment]
We're supporting two mechanisms of configuring scheduler:

- (legacy) Policy, which consists of Predicates and Priorities (https://kubernetes.io/docs/reference/scheduling/policies/)
- Profile, which consists of plugins (https://kubernetes.io/docs/reference/scheduling/profiles/)

So due to that, their names may diff.

Ref:

- https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/

**Comment by brannondorsey** [comment]
@Huang-Wei the example yaml configuration you shared above is useful indeed. In a case where a scheduler overrides a score plugin that's already configured by default, is it necessary to both `enable` and `disable` the plugin as you do in your example?

```yaml
- schedulerName: image-first
  plugins:
    score:
      enabled:
      - name: ImageLocality
        weight: 50000
      disabled:
      - name: ImageLocality
```

Otherwise will the user supplied value be ignored? I'd imagine this would be enough, but it's useful to learn that perhaps it's not.

```yaml
- schedulerName: image-first
  plugins:
    score:
      enabled:
      - name: ImageLocality
        weight: 50000
```
