### ISSUE TITLE
Completed pod and running pod share the same IP

### ISSUE THREAD

**Issue by FrimIdan** [kubernetes/kubernetes#92697]
**What happened**:
A completed pod and a running pod is sharing the same IP
![image](https://user-images.githubusercontent.com/40820488/86239577-3e291100-bba8-11ea-8d10-6c27f5fb3122.png)

**What you expected to happen**:
While I understand that the completed pod is not running, I think that the expected behavior is to update the completed pod status with an empty IP.

**How to reproduce it (as minimally and precisely as possible)**:
Apply a job and look at the pod IP after it was completed.
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.15", GitCommit:"8ce551a0c972a9f113e326df0537aa3f1798d93e", GitTreeState:"clean", BuildDate:"2020-05-05T18:38:03Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `GKE`
