### ISSUE TITLE
NodeSelector on Namespace 

### ISSUE THREAD

**Issue by Fillo22** [kubernetes/kubernetes#92822]
**What would you like to be added**:
It is necessary to assign a certain NodeSelector to a namespace. 
At the moment this function is not supported except at Pod level. 

**Why is this needed**:
This functionality is necessary to be able to assign workloads to dedicated namespaces, 
that refer to nodes with specific features and functionality.  
For example, if I need to deploy a memory intensive application,  
I want to be able to deploy it on a namespace that's already configured the kind of node to rely on. 

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: workload
  labels:
    name: workload
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            values:
            - highmem            
  finalizers:
    - kubernetes
status:
  phase: Active

```
