### ISSUE TITLE
Add a new metric type `Replicas` for HPA 

### ISSUE THREAD

**Issue by snowplayfire** [kubernetes/kubernetes#92820]
**What would you like to be added**:

HPA has three metric types that are `Resource`, `Pods` and `Object`.

I want to add a new metric type `Replicas` for HPA which stands for direct target replicas. Implemention like:
```
- type: Replicas
  replicas:
    metric:
      name: cron-metric
      selector:
        matchLabels:
          foo: bar
```
Corresponding `replicas-metrics-server` can register with kube-apiserver and output the target replicas for the metric named `cron-metric`.

`Replicas`, `Resource`, `Pods` and `Object` can take effect at the same time. 

Use example:
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
  - type: Replicas
    replicas:
      metric:
        name: cron-metric
        selector:
          matchLabels:
            foo: bar
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
``` 

**Why is this needed**:

User Stories:
1. Before a big sales promotion, I scale up the pods to a target replicas. I hope to add a timed task to do the work  automatically and HPA should take effect at the same time. That is, I want to add the timed replicas as a metric for HPA.

2. Predict system can output a target replicas number. I want to add the predict replicas as a metric for HPA.

We have implemented the proposal. Please review the simplified description and we can contribute details if needed.

/sig apps
