### ISSUE TITLE
podAntiAffinity weights not taken into account when multiple podAffinityTerm are specified

### ISSUE THREAD

**Issue by mvukadinoff** [kubernetes/kubernetes#92864]
**What happened**:

When defining multiple podAffinityTerms only one is taken into account. Changing weights on the second one doesn't seem to affect scheduling when soft rules are applied (preferredDuringSchedulingIgnoredDuringExecution)

Definition of the deployment:
```
...
spec:
  template:
    spec:
      labels:
        app: harbor
        component: core
        componentappname: harbor-core
        release: harbor
...
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - core
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 20
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - core
              topologyKey: kubernetes.io/hostname
            weight: 5

```

When applied for the deployment and we play with the replicas we see that after the zone requirmeent is met the hostname requirement is not taken into account as the same node gets multiple replicas.

```
$ kubectl get pods -n harbor -o wide | grep core
harbor-harbor-core-579d85cf7b-5s2b2            1/1     Running   0          116s   XX.YY.224.106   ip-XX.YY-224-133.ec2.internal   <none>           <none>
harbor-harbor-core-579d85cf7b-87xt2            0/1     Running   0          9s     XX.YY.192.7     ip-XX.YY-192-182.ec2.internal   <none>           <none>
harbor-harbor-core-579d85cf7b-vf4jc            1/1     Running   0          87s    XX.YY.208.141   ip-XX.YY-208-53.ec2.internal    <none>           <none>

# 1 x 1f - 1x133
# 1 x 1b - 1x182
# 1 x 1d - 1x53


$ kubectl get pods -n harbor -o wide | grep core
harbor-harbor-core-579d85cf7b-5s2b2            1/1     Running   0          3m26s   XX.YY.224.106   ip-XX.YY-224-133.ec2.internal   <none>           <none>
harbor-harbor-core-579d85cf7b-87xt2            1/1     Running   0          99s     XX.YY.192.7     ip-XX.YY-192-182.ec2.internal   <none>           <none>
harbor-harbor-core-579d85cf7b-bp78q            0/1     Running   0          4s      XX.YY.224.81    ip-XX.YY-224-133.ec2.internal   <none>           <none>
harbor-harbor-core-579d85cf7b-vf4jc            1/1     Running   0          2m57s   XX.YY.208.141   ip-XX.YY-208-53.ec2.internal    <none>           <none>


# 2 x 1f - 2x133
# 1 x 1b - 1x182
# 1 x 1d - 1x53


$ kubectl get pods -n harbor -o wide | grep core
harbor-harbor-core-579d85cf7b-5s2b2            1/1     Running   0          5m12s   XX.YY.224.106   ip-XX.YY-224-133.ec2.internal   <none>           <none>
harbor-harbor-core-579d85cf7b-87xt2            1/1     Running   0          3m25s   XX.YY.192.7     ip-XX.YY-192-182.ec2.internal   <none>           <none>
harbor-harbor-core-579d85cf7b-bp78q            1/1     Running   0          110s    XX.YY.224.81    ip-XX.YY-224-133.ec2.internal   <none>           <none>
harbor-harbor-core-579d85cf7b-vf4jc            1/1     Running   0          4m43s   XX.YY.208.141   ip-XX.YY-208-53.ec2.internal    <none>           <none>
harbor-harbor-core-579d85cf7b-wkgvv            0/1     Running   0          3s      XX.YY.224.144   ip-XX.YY-224-133.ec2.internal   <none>           <none>

# 3 x 1f - 3x133
# 1 x 1b - 1x182
# 1 x 1d - 1x53



$ kubectl get nodes --show-labels
NAME                            STATUS   ROLES    AGE   VERSION              LABELS
ip-XX-YY-192-182.ec2.internal   Ready    <none>   28d   v1.16.8-eks-e16311   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1b,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-XX-YY-192-182.ec2.internal,kubernetes.io/os=linux,node.kubernetes.io/lifecycle=spot
ip-XX-YY-192-192.ec2.internal   Ready    <none>   28d   v1.16.8-eks-e16311   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1b,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-XX-YY-192-192.ec2.internal,kubernetes.io/os=linux,node.kubernetes.io/lifecycle=spot
ip-XX-YY-208-13.ec2.internal    Ready    <none>   28d   v1.16.8-eks-e16311   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1d,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-XX-YY-208-13.ec2.internal,kubernetes.io/os=linux,node.kubernetes.io/lifecycle=spot
ip-XX-YY-208-53.ec2.internal    Ready    <none>   28d   v1.16.8-eks-e16311   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1d,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-XX-YY-208-53.ec2.internal,kubernetes.io/os=linux,node.kubernetes.io/lifecycle=spot
ip-XX-YY-224-133.ec2.internal   Ready    <none>   15h   v1.16.8-eks-e16311   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1f,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-XX-YY-224-133.ec2.internal,kubernetes.io/os=linux,node.kubernetes.io/lifecycle=spot
ip-XX-YY-224-181.ec2.internal   Ready    <none>   18h   v1.16.8-eks-e16311   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1f,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-XX-YY-224-181.ec2.internal,kubernetes.io/os=linux,node.kubernetes.io/lifecycle=spot
```

**What you expected to happen**:

The weights should sum up. When the higher weight gets satisfied then the lower should make a difference.
If I understand the algorithm correctly.
In theory node 133 should have anti weight: 20 + 5 = 25 as it matches both rules
compared to the second node in the same zone ip-XX-YY-224-181.ec2.internal should have anti-weight of just 20 and should be preferred.
However this doesn't seem to work.

**How to reproduce it (as minimally and precisely as possible)**:

On a cluster with at least 2 nodes per availability zone (4 for 2 AZ or 6 for 3 AZ) apply a deployment resource with 5-7 replicas having the following affinity policy:

```
...
spec:
  template:
    spec:
      labels:
        app: harbor
        component: core
        componentappname: harbor-core
        release: harbor
...
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - core
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 20
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - core
              topologyKey: kubernetes.io/hostname
            weight: 5

```

**Anything else we need to know?**:

We have made multiple attempts to modify the definition it still didn't work, the only way to achieve the required result is to combine  podAntiAffinity with podAffinity and a negated rule. 
Combining with requiredDuringSchedulingIgnoredDuringExecution mode is not an option as the goal is to spread evenly over AZs but not necessarily have just one pod per zone or node. 

A nice feature also would be to sum up if the same rule is matched twice, for example if 2 pods run on the same node the node should get 2 times the weight of the rule. The current design seems to be that a rule can only be matched once, that's the reason we extended with a second rule in the first place. 

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
AWS ( EKS  )

- OS (e.g: `cat /etc/os-release`):
AWS AMI: amazon-eks-node-1.16.8-v*

- Kernel (e.g. `uname -a`):
AWS AMI: amazon-eks-node-1.16.8-v*

- Install tools: 
Terraform 

- Network plugin and version (if this is a network-related bug):
AWS network plugin

- Others:

**Comment by lingsamuel** [comment]
After some tests I believe the podAntiAffinity weights works well in my cluster.

I noticed your yaml looks like:
```yaml
spec:
  template:
    spec:
      labels:
        app: harbor
        component: core
        componentappname: harbor-core
        release: harbor
```
I believe labels shouldn't appear in `spec.template.spec`, it should be in `spec.template.metadata`.
