### ISSUE TITLE
dnsConfig applies RFC-1123 too broadly to searches

### ISSUE THREAD

**Issue by sethev** [kubernetes/kubernetes#92889]
**What would you like to be added**:

RFC-1123 defines restrictions to host names. In Kubernetes, these restrictions are also
applied to object names.

However, for search strings in dnsConfig, names that are perfectly valid according
to [RFC 2181 Section 11](https://tools.ietf.org/html/rfc2181#section-11) are rejected.

An example of this is using underscores in a subdomain:

```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: dns-example
spec:
  containers:
    - name: test
      image: nginx
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 1.2.3.4
    searches:
      - abc_d.example.com
```

Since this is specifying a DNS search string specifically and not the name of an object
in Kubernetes, it seems like this check could be relaxed to allow names that comply with RFC 2181.

Instead this gives the following error:
```
The Pod "dns-example" is invalid: spec.dnsConfig.searches[0]: Invalid value: "abc_d.example.com": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Why is this needed**:

Workloads that rely on short names can take time to change, which is why the dnsConfig is useful. However, in our case most of the names we need in the search have an underscore. Our current work-around is to re-write resolv.conf from inside the pod.
