### ISSUE TITLE
Allow updating volumeClaimTemplates labels

### ISSUE THREAD

**Issue by zopanix** [kubernetes/kubernetes#93115]
**What would you like to be added**:
Hey,

I recently tried to update the labels for an existing volumeClaimTemplate inside a statefulset. Kubernetes errored out with the following message:

```
error: statefulsets.apps "<redacted>" is invalid
```

I honnestly expected to be able to update labels and annotations wherever I put them.

Current change was to fix a typo:
```
 volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        component: sotrage
        environment: <redacted>
        environment-type: <redacted>
        instance: <redacted>
        managed-by: <redacted>
        name: <redacted>
        part-of: <redacted>
```
Obviously, I want to change `sotrage` to `storage`.

**Why is this needed**:
I don't see any technical reason for this not to be possible as labels can be updated on a lot of components and humans make typo's all the time.

**Additional Information**:
```
kubectl version  
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"archive", BuildDate:"2020-07-01T16:28:46Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
As you can see this is an AWS managed EKS cluster running on 1.16
