### ISSUE TITLE
EndpointSlices resource is not created for selector less services

### ISSUE THREAD

**Issue by kvaster** [kubernetes/kubernetes#93157]
**What happened**:
We're using k8s with cilium as CNI backend.
Recently we discovered that cilium will not create any endpoint entries for services without selector.
After investigation we found that endpointslices resource will be not created in case we will create endpoint resource manually.

**What you expected to happen**:
Corresponding endpointslices resource should be created automatically after ednpoints resource creation.

**How to reproduce it (as minimally and precisely as possible)**:

Create simple service without endpoint:

```
---
kind: Service
apiVersion: v1
metadata:
  name: external-service
  namespace: default
spec:
  ports:
    - port: 443
```

Manually create endpoint for the service:

```
kind: Endpoints
apiVersion: v1
metadata:
  name: external-service
  namespace: default
subsets:
  - addresses:
    - ip: 10.118.10.1
    ports:
      - port: 443
```

We can see endpoint, but there will be no endpointslice:

```
k8s-1 /home/kva/k8s/ingress # kubectl get endpoints | grep external-service
external-service       10.118.10.1:443                                         2d23h
k8s-1 /home/kva/k8s/ingress # kubectl get endpointslices | grep external-service
```

As a result CNI plugin (cilium without kubeproxy in our setup) will be not able to make corresponding setup when listening to endpointslices instead of endpoints.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"archive", BuildDate:"2020-07-13T10:27:10Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Bare metal (libvirt vm)

- OS (e.g: `cat /etc/os-release`):
Gentoo

- Kernel (e.g. `uname -a`):
Linux k8s-1 5.7.0-gentoo #1 SMP PREEMPT Wed Jun 3 18:34:14 -00 2020 x86_64 Intel Core Processor (Skylake, IBRS) GenuineIntel GNU/Linux

- Install tools:
kubeadm
