### ISSUE TITLE
A PSP with apparmor annotations does not allow windows pods to be scheduled

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#93165]
**What happened**:
If I have the a psp with apparmor annotations:

```
apiVersion: {{if IsKubernetesVersionGe "1.16.0"}}policy{{else}}extensions{{end}}/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  docker/default
    apparmor.security.beta.kubernetes.io/defaultProfileName:  runtime/default
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
#truncated...
```

and I deploy a windows pod it gets blocked:

```
kubectl create -f- <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: e2eteam/busybox:1.29
    command:
      - sleep
      - "3600"
  restartPolicy: Always
  nodeSelector:
    "kubernetes.io/os": windows
EOF
pod "test" created
```

```
kubectl get pods                    
NAME                 READY   STATUS                       RESTARTS   AGE
test                 0/1     Blocked                      0          9m55s

kubectl describe po test
Name:         test                                                                                                                                         
Namespace:    default                                                                                                                          
Priority:     0                                                                                                                                            
Node:         1309k8s01000000/10.240.0.65                                                                                                                  
Start Time:   Thu, 16 Jul 2020 16:39:52 -0700                                                                                                              
Labels:       <none>                                                                                                                                       
Annotations:  container.apparmor.security.beta.kubernetes.io/test: runtime/default                                                                         
              kubernetes.io/psp: restricted                                                                                                                
              seccomp.security.alpha.kubernetes.io/pod: docker/default                                                                                     
Status:       Pending                                                                                                                                      
Reason:       AppArmor                                                                                                                                     
Message:      Cannot enforce AppArmor: binary not compiled for linux    
```
**What you expected to happen**:
Apparmor check is ignored for windows pods

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know?**:
Should be fixed/documented with work around as per #64801 

**Environment**: 
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T19:51:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): windows/unbuntu
- Kernel (e.g. `uname -a`):
- Install tools: aks-engine
- Network plugin and version (if this is a network-related bug):
- Others:
