### ISSUE TITLE
subPath not working with mountPropagation

### ISSUE THREAD

**Issue by svpace** [kubernetes/kubernetes#93202]
**What happened**:
Using "subPath" to access a mount point mounted by another container in the same pod does not work.
Given a deployment like the following, "server-1" is not able to access the files mounted by "provider".
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugreport
  labels:
    app: bugreport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugreport
  template:
    metadata:
      labels:
        app: bugreport
    spec:
      containers:
        - name: server-1
          image: ...
          volumeMounts:
            - name: bucket
              mountPath: "/mnt"
              subPath: "server-1"
              mountPropagation: HostToContainer
        - name: provider
          image: ...
          securityContext:
            privileged: yes
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: bucket
              mountPath: /mnt
              mountPropagation: Bidirectional
      volumes:
        - name: bucket
          emptyDir: {}
```

**What you expected to happen**:

I expect "server-1/mnt" and provider/mnt/server-1" to share the same files.

**How to reproduce it (as minimally and precisely as possible)**:

see previous deployment
