### ISSUE TITLE
$setElementOrder error encountered updating Deployment removing and reordering multiple env vars with same name

### ISSUE THREAD

**Issue by erharb** [kubernetes/kubernetes#93265]
**What happened**:
We have added a new set of container envs for a Deployment object to grab database user/pass from a Secret. Since the name of the secret can differ if the database is internal or external and they are mutually exclusive since it is not valid to have both the internal and external secrets in same namespace as the Deployment. 

This is allowed out of the box, `spring_datasource_username` and `spring_datasource_password` are declared twice as optional, one for each possibility of using `internal-db-secret` or the `external-db-secret` from this example snippet:
```
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      containers:
      - ...
        env:
        - name: spring_datasource_username
          valueFrom:
            secretKeyRef:
              key: username
              name: internal-db-secret
              optional: true
        - name: spring_datasource_password
          valueFrom:
            secretKeyRef:
              key: password
              name: internal-db-secret
              optional: true
        - name: spring_datasource_username
          valueFrom:
            secretKeyRef:
              key: username
              name: external-db-secret
              optional: true
        - name: spring_datasource_password
          valueFrom:
            secretKeyRef:
              key: password
              name: external-db-secret
              optional: true
```

However, when updating from a previous version of this Deployment object where these properties did not exist (but nothing else much changed other than image version), the apply operation to update fails with the following message:
```
Error from server: error when applying patch:
...
for: "for-science-update-broken.yaml": The order in patch list:
[map[name:spring_datasource_username valueFrom:map[secretKeyRef:map[key:username name:external-db-secret optional:true]]] map[name:spring_datasource_username valueFrom:map[secretKeyRef:map[key:username name:internal-db-secret optional:true]]] map[name:spring_datasource_password valueFrom:map[secretKeyRef:map[key:password name:external-db-secret optional:true]]] map[name:spring_datasource_password valueFrom:map[secretKeyRef:map[key:password name:internal-db-secret optional:true]]]]
 doesn't match $setElementOrder list:
[map[name:application_schema] map[name:spring_datasource_username] map[name:spring_datasource_password] map[name:spring_datasource_username] map[name:spring_datasource_password]]
```

**What you expected to happen**:
Either the update should not fail because this manifest is allowed out of the box, or out of the box should fail to have prevented thinking we could use multiple optional vars using the same name in the first place.

**How to reproduce it (as minimally and precisely as possible)**:
[for-science-update-broken.zip](https://github.com/kubernetes/kubernetes/files/4949969/for-science-update-broken.zip)
Extract the two yaml files from the attached zip then run the following commands (into a clean new namespace if desired), the second command will immediately report the failure message shown above:
```
kubectl apply -f for-science-pre.yaml
kubectl apply -f for-science-update-broken.yaml
```

**Anything else we need to know?**:
To workaround this bug (and another that followed this: #93266) we ended up having to rename both pairs of optional envs so they would be unique by appending either `_internal` or `_external` to the name of the env and having the entrypoint figure out what to do with them based on which gets defined.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16 (client and server)
- Cloud provider or hardware configuration: k8s cluster on 5 openstack VMs (1 main, 4 workers)
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`): WSL Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
