### ISSUE TITLE
Init containers require CPU limit in order for container to be in guaranteed QoS

### ISSUE THREAD

**Issue by cswindle** [kubernetes/kubernetes#93282]
**What happened**:
When using the static CPU allocator in Kubernetes I find that I need to follow the rules about providing CPU and memory limits for init containers as well as containers, if I do not provide these then the QoS Class gets set to burstable.

**What you expected to happen**:
The init containers should not be taken into account when determining the QoS class for the pod.

**How to reproduce it (as minimally and precisely as possible)**:
Set kubelet to use static CPU manager policy, then create a pod with the following spec:
```apiVersion: "v1"
kind: Pod
metadata:
  name: static-with-init
spec:
  containers:
  - name: test
    image: alpine
    command:
    - sleep
    - infinity
    resources:
      limits:
        cpu: "1"
        memory: "100Mi"
  initContainers:
  - name: test2
    image: alpine
    command:
    - sleep
    - "3"
```
When you run kubectl describe on the pod you will see it is set to 'Burstable'.

If I add in CPU resources like below:
```
apiVersion: "v1"
kind: Pod
metadata:
  name: static-test
spec:
  containers:
  - name: test
    image: alpine
    command:
    - sleep
    - infinity
    resources:
      limits:
        cpu: "1"
        memory: "100Mi"
  initContainers:
  - name: test2
    image: alpine
    command:
    - sleep
    - "3"
    resources:
      limits:
        cpu: "1"
        memory: "100Mi"
```
Then the QoS class is set to 'Guaranteed'.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.6
- Cloud provider or hardware configuration: Bare metal
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): 4.15.0-45-generic
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:
