### ISSUE TITLE
Deploy failed due default-token can't be reached 

### ISSUE THREAD

**Issue by toha-tk** [kubernetes/kubernetes#93325]
**What happened**:
We use Helm to deploy our application.
Before the main app deploy, we have a preparation job with initContainers, which waits for the environment correct setup.
That's is the app-prepare config

```
apiVersion: batch/v1
kind: Job
metadata:
  [REDUCTED]
spec:
  activeDeadlineSeconds: 1800
  backoffLimit: 0
  template:
    metadata:
      labels:
        helmChart: {{ .Chart.Name }}
        job: app-prepare
    spec:
      containers:
        - name: php
          image: {{ .Values.images.php }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "/entrypoint/prepare.sh"]
      initContainers:
        - name: wait-alyce-app-internal
          image: busybox:latest
          command: [REDUCTED]
```

What happened exactly:
1. Deployed app-prepare job
2. initContainer started
3. Main container (php) tried to start after initContainer finish and failed.

The only message in the kubernetes events:
`pod/app-prepare-5bfdk                                       Error: cannot find volume "default-token-h8rkg" to mount into container "php"`

But the default token was ok and can be reached.
Simple redeploy helped, but was not able to find same problem in issue trackers/repos/troubleshooting guiedes.

**What you expected to happen**:
There is retry mechanism to find the required token
There is a bit more clear error message (what do to and why it failed to reach secret)

**How to reproduce it (as minimally and precisely as possible)**:
There is no stable steps to reproduce, was caught once on production deploy.

**Anything else we need to know?**:
Got not much info, only error message in the events

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-27T00:36:48Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-gke.15", GitCommit:"8ce551a0c972a9f113e326df0537aa3f1798d93e", GitTreeState:"clean", BuildDate:"2020-05-05T18:38:03Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Google Kubernetes Engine
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04
- Install tools:
Helm
