### ISSUE TITLE
Kubernetes Hostpath allows to HomeDirectory of Worker Node

### ISSUE THREAD

**Issue by WoodProgrammer** [kubernetes/kubernetes#93335]
Hello everyone,

I'm working on k8s cluster version of 1.16 and found some interesting things about HostPath.
Pods can able to access the home directory of the nodes which one pods located on.

This capability allows to change configs like ssh (`allowed_keys`) and etc.
That is the pod.yaml example 

```
apiVersion: v1
kind: Pod
metadata:
  name: example-container
spec:
  containers:
  - image: nginx
    name: example-container
    volumeMounts:
    - mountPath: /opt/
      name: home-volume
  volumes:
  - name: home-volume
    hostPath:
      path: /home/ubuntu
      type: Directory
```

I think this looks a bug and podsecurity policy is handling this issue but some of components like kubeproxy, needs to mount `HostPath` volumes.

Thanks
