### ISSUE TITLE
kube-apiserver livenessProbe needs to be excempt from flowcontrol

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#93359]
on kubernetes 1.18 with flowcontrol enabled

when our api-server is under heavy load for a long time it dies because the livenessProbe fails
this is dangerous since it can lead to etcd compaction never running and then etcd falling over

I did not find a way to configure a serviceaccount for livenessProbe except for exposing the token in the pod config that could then be stolen by any user with pod read access [suggested here](https://github.com/kubernetes/kubernetes/issues/43784)

is it possible to either configure a serviceaccount for the probe or make the livenessProbe itself exempt from flowcontrol / given a higher priority ?

Another way we found was using an exec probe and making that read the service-account token from disk, then giving that token priority, but that's still pretty hacky.

**Comment by MikeSpreitzer** [comment]
So the problem here is that control plane kubelets typically test liveness by hitting the secured port with no credentials, equivalent to this:
```
mspreitz@mjs-dev-1:~$ curl -k https://localhost:6443/healthz
okmspreitz@mjs-dev-1:~$ 
```

With logging turned way up in the apiserver, we see stuff like the following
```
...
I0723 21:55:32.310219  120960 apf_filter.go:130] Handle(RequestDigest{RequestInfo: &request.RequestInfo{IsResourceRequest:false, Path:"/healthz", Verb:"get", APIPrefix:"", APIGroup:"", APIVersion:"", Namespace:"", Resource:"", Subresource:"", Name:"", Parts:[]string(nil)}, User: &user.DefaultInfo{Name:"system:anonymous", UID:"", Groups:[]string{"system:unauthenticated"}, Extra:map[string][]string(nil)}}) => fsName="global-default", distMethod=&v1alpha1.FlowDistinguisherMethod{Type:"ByUser"}, plName="global-default", isExempt=false, queued=true, Finish() => idle=true
...
I0723 21:55:32.310432  120960 httplog.go:89] "HTTP" verb="GET" URI="/healthz" latency="241.160079ms" userAgent="curl/7.58.0" srcIP="127.0.0.1:44796" resp=200
```

So to fix the current emergency we need APF configuration to exempt such requests from limitation.  The down side is that this rips a big hole in the purpose of APF, which is protection from abusive clients.  Longer term we want a way to get those kubelets authenticated and even think about limiting them to an appropriate degree.

I will soon post here APF configuration objects to allow these requests, and prepare a PR to add this to the suggested APF config.

@yue9944882 
@lavalamp 
@deads2k 
@rngy

**Comment by MikeSpreitzer** [comment]
BTW, exactly which paths are the problem here?

**Comment by logicalhan** [comment]
`/healthz`, `/readyz`, `/livez`

**Comment by lavalamp** [comment]
I think the best fix here is for monitoring stuff to get its own account.

**Comment by MikeSpreitzer** [comment]
This will exempt all traffic to those paths:
```
apiVersion: flowcontrol.apiserver.k8s.io/v1alpha1
kind: FlowSchema
metadata:
  name: health-for-all
spec:
  matchingPrecedence: 1000
  priorityLevelConfiguration:
    name: exempt
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - "/healthz"
      - "/livez"
      - "/readyz"
      verbs:
      - "*"
    subjects:
    - kind: Group
      group: 
        name: system:unauthenticated 
    - kind: Group
      group: 
        name: system:authenticated 
```

**Comment by MikeSpreitzer** [comment]
Do we want a fix for this in the 1.19 release?

**Comment by lavalamp** [comment]
Personally, I'd prefer not to rush. People with this problem can manually
add in the configuration you suggested.

I think we don't want to exempt healthz generally, we want people to run
their monitoring infrastructure with some account, and we can exempt
healthz only for that account.

**Comment by MikeSpreitzer** [comment]
Another approach is to handle unauthenticated requests for health by putting them in their own limited priority level; I suspect that would solve the original problem here, which is other work crowding out the health checks.

**Comment by grosser** [comment]
the `health-for-all` sounds like a really good workaround for now 👍

**Comment by lavalamp** [comment]
Well... then someone sending unauthenticated healthz requests (which is
easy) could starve out the monitoring system!

**Comment by grosser** [comment]
yes, not a good solutions for clusters that don't trust their users

**Comment by MikeSpreitzer** [comment]
How about
```
apiVersion: flowcontrol.apiserver.k8s.io/v1alpha1
kind: FlowSchema
metadata:
  name: health-for-all
spec:
  matchingPrecedence: 1000
  priorityLevelConfiguration:
    name: exempt
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - "/healthz"
      - "/livez"
      - "/readyz"
      verbs:
      - "*"
    subjects:
    - kind: Group
      group: 
        name: system:unauthenticated 
```
... which opens the door enough for those unauthenticated kubelets, excluding authenticated users on the grounds that they should get some more discriminating treatment anyway.
