### ISSUE TITLE
Destroying AWS EKS using Terraform does not delete NLB

### ISSUE THREAD

**Issue by tehleet** [kubernetes/kubernetes#93390]
**What happened**:
Create EKS using Terraform modules and provision NLB using k8s service with annotations. Doing Terraform destroy removes cluster, but NLB is not deleted.
**What you expected to happen**:
Did not tried with manual creation of EKS and deleting EKS from the console, but doing terraform destroy on EKS should delete created resources by EKS
**How to reproduce it (as minimally and precisely as possible)**:
It is possible to use public AWS EKS Terraform module with basic configuration
Use below yaml to create NLB and then use terraform destroy
```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-pod
  template:
    metadata:
      labels:
        app: echo-pod
    spec:
      containers:
        - name: echoheaders
          image: k8s.gcr.io/echoserver:1.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "some:arn"
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: echo-pod
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8080
  type: LoadBalancer
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration: AWS EKS
