### ISSUE TITLE
Webhook REST clients cache invalid and possibly not expiring

### ISSUE THREAD

**Issue by raonitimo** [kubernetes/kubernetes#93409]
**What happened**:
Deployed a webhook as a service to a Kubernetes cluster with 2 masters, listening initially on port 8000. 
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: webhook
---
kind: Service
apiVersion: v1
metadata:
  name: webhook
  namespace: webhook
spec:
  selector:
    app: webhook
  ports:
  - name: https
    protocol: TCP
    port: 8000
    targetPort: 443
```

Created a Validating Webhook pointing to port 8000:
```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
webhooks:
- clientConfig:
    caBundle: ...
    service:
      name: webhook
      namespace: webhook
      path: /validate
      port: 8000
  failurePolicy: Fail
...
```

Changed the service to use port 443. As expected, pod creation started to fail with the message (not always though):
```bash
$ kubectl run nginx --image nginx
Error from server (InternalError): Internal error occurred: failed calling webhook "webhook.webhook.svc": Post https://webhook.webhook.svc:443/validate?timeout=30s: no service port 'ὀ' found for service "webhook"
```

The 'ὀ' character was a bug on printing the port number - 8000 in this case - that was [fixed](https://github.com/kubernetes/kubernetes/pull/85558). This is not the issue here.

After fixing the webhook configuration, I started seeing the message:
```bash
$ kubectl run nginx --image nginx
Error from server (InternalError): Internal error occurred: failed calling webhook "webhook.webhook.svc": Post https://webhook.webhook.svc:443/validate?timeout=30s: no service port 'ƻ' found for service "webhook"
```

Consistently when hitting one of the masters, while the Validating Webhook worked as expected when hitting the other master. Again the weird character 'ƻ' represents 443, the .webhooks[].clientConfig.service.port in ValidatingWebhookConfiguration.

The same issue persists after deleting the service, webhook, and recreating with the same names.

**What you expected to happen**:
I expected the Validating Webhook to work on both masters.

**How to reproduce it (as minimally and precisely as possible)**:
Tried reproducing this issue using a different service name, as well as deploying it in another cluster. But the same error didn't happen again, so I believe there was some sort of special condition that caused this problem.

**Anything else we need to know?**:
Digging a bit into this, I suspect it has something to do with the [caching](https://github.com/kubernetes/kubernetes/blob/release-1.15/staging/src/k8s.io/apiserver/pkg/util/webhook/client.go#L117) . I couldn't find a reference to where this cache is cleaned up.

Shouldn't we move to a LRUExpireCache to avoid this?

I'm happy to make a pull request if you think this is the case.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15 (but this code hasn't changed since)
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
