### ISSUE TITLE
TCP socket connection interference on send message

### ISSUE THREAD

**Issue by Placidina** [kubernetes/kubernetes#93435]
I'm creating an application in C that intermediates and manages scheduled applications (NodeJs) to collect informations into MongoDB.

This makes possible the application's scalability and avoid replicated values.

**Problem**

I think that something comming from k8s is intercepting and modifying the message.

- Local tests: OK
- Container tests: Ok
- K8s Minikube tests: scheduled application error in bson parse
- EKS Production tests: scheduled application error in bson parse

```
k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
`minikube.yaml`:
```
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongo-host
subsets:
- addresses:
  - ip: 172.17.0.1
  ports:
  - name: mongo-host
    port: 27017
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-host
spec:
  ports:
  - name: mongo-host
    port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssq
  labels:
    app: ssq
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: ssq
  template:
    metadata:
      labels:
        app: ssq
    spec:
      containers:
      - name: ssq
        image: local/ssq:latest
        imagePullPolicy: Never
        env:
        - name: MONGO_URI
          value: mongodb://mongo-host:27017/
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ssq
  labels:
    app: ssq
spec:
  selector:
    app: ssq
  type: NodePort
  ports:
  - name: ssq
    port: 3145
    nodePort: 31003
```

**Code of C application to send socket message:**
```
static void
ssq_connection_server_handler()
{
    ...

    for (i = 0; i < ssq_max_sockets; i++) {
        sd = ssq_connection->clients[i];
        if (FD_ISSET(sd, &master)) {
            if ((ret = ssq_connection->recv(sd, buffer, SSQ_SERVER_MAX_BUFFER_SIZE)) <= 0) {
                continue;
            }

            buffer[ret] = '\0';
            token = ssq_strtok(buffer, ":");
            opts = ssq_strtok(NULL, ":");

            limit = ssq_atoi(opts, ssq_strlen(opts));
            if (limit == SSQ_ERROR) {
                limit = 10;
            }

            if (ssq_strcmp("next", token) == 0) {
                u_char *tasks;
                size_t len;

                tasks = ssq_mongo_collection_find(limit, ssq_mongo->collection, &len);
                ssq_connection->send(sd, tasks, len);
            }
        }
    }

    ...
}

static ssize_t
ssq_connection_send_handler(int fd, u_char *buf, size_t size)
{
    ssize_t n;
    ssq_err_t err;

    for (;;) {
        n = send(fd, buf, size, 0);

        ssq_log_debug("send: fd:%d %z of %uz", fd, n, size);

        if (n > 0) {
            return n;
        }

        err = ssq_socket_errno;

        if (n == 0) {
            ssq_log_error(SSQ_LOG_ALERT, err, "send() returned zero");
            return n;
        }

        if (err == SSQ_EAGAIN || err == SSQ_EINTR) {
            ssq_log_debug_error(err, "send() not ready");

            if (err == SSQ_EAGAIN) {
                return SSQ_AGAIN;
            }
        } else {
            return SSQ_ERROR;
        }
    }
}
```

**Code in NodeJs to receive message:**
```
const net = require('net');
const { EJSON } = require('bson');

const sock = new net.Socket();

sock.connect(process.env.SSQ_PORT || 3145, process.env.SSQ_HOST || '127.0.0.1', () => {
    console.log('socket connection established');
});

sock.on('data', (data) => {
    try {
        const tasks = EJSON.parse(data);
        console.log(tasks);
        process.exit(0);
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
});

sock.on('error', () => {
    /* void */
});

sock.on('close', () => {
    console.warn('socket connection has been closed');
});

sock.write(Buffer.from('next:10'));
```
