### ISSUE TITLE
Deployment Affinity to a specific node 

### ISSUE THREAD

**Issue by mseewooth** [kubernetes/kubernetes#93451]
Hello all, 

I have  a deployment with k8s v1.18.6 :

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-prod
  namespace: blue-prod
  labels:
    app: blue-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-prod
  template:
    metadata:
      labels:
        app: blue-prod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-node1

    spec:
      volumes:
      - name: blue-prod
        persistentVolumeClaim:
          claimName: blue-prod
      containers:
      - name: blue-prod
        image: repo.treescale.com/XXXX/XXXXX:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        volumeMounts:
        - name: blue-prod
          mountPath: /var/www/XXX
      imagePullSecrets:
      - name: XXX
```
i want 3 containers to in  the worker-node1 but this is not happening : 

```
NAME                        READY   STATUS              RESTARTS   AGE     IP             NODE           NOMINATED NODE   READINESS GATES
blue-prod-c99ccfb6c-fqg5l   0/1     ContainerCreating   0          3s      <none>         worker-node2   <none>           <none>
blue-prod-c99ccfb6c-pmxw5   1/1     Running             0          6m13s   10.244.2.185   worker-node1   <none>           <none>
blue-prod-c99ccfb6c-v2cs8   0/1     ContainerCreating   0          3s      <none>         worker-node2   <none>           <none>
```

Its being replicate on the worker-node2  which is i do not want to because i have a readmanyonce storageclass. 

Does `node afffinity` works with deployment ?
