### ISSUE TITLE
gce-master-scale-correctness OOMing after test pod limits set

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#93506]
**Which jobs are failing**:
gce-master-scale-correctness

**Which test(s) are failing**:
all - whole test set OOMed

**Since when has it been failing**:
2020-07-28

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness

**Reason for failure**:
test pod OOMed after setting 16Gi memory limit
https://github.com/kubernetes/test-infra/pull/18494

**Anything else we need to know**:

**Comment by wojtek-t** [comment]
Not this window :) it was supposed to be for kubernetes/test-infra#18496

**Comment by BenTheElder** [comment]
Looks fixed?

**Comment by wojtek-t** [comment]
Yeah - last run didn't OOM, so I think we can close this one.

**Comment by jkaniuk** [comment]
Another 2 runs OOMed:

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1289169373948284931
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1289531731606507520

```
Terminated (OOMKilled ...
```

```
      resources:
        limits:
          cpu: "6"
          memory: 32Gi
        requests:
          cpu: "6"
          memory: 32Gi
```

/reopen
