### ISSUE TITLE
podAntiAffinity ignored when rollout restart

### ISSUE THREAD

**Issue by bcanozter** [kubernetes/kubernetes#93538]
**What happened**:

I have 2 nodes, master and worker. I wanted to run pods from replicas on each node i.e don't want to schedule two pods on same node.

When I deploy `kubectl apply -f mydeployment.yaml` , it schedules pods to different nodes which is fine. 

Then I execute `rollout restart deployment mydeployment` and pod scheduling is randomized. Two pods are sometimes on the same node.

podAntiAffinity rule ignored when rollout restart deployment is used

**What you expected to happen**:

Expected to see pods scheduled to different nodes after `rollout restart deployment`

**How to reproduce it (as minimally and precisely as possible)**:

1) kubectl apply -f mydeployment.yaml
2) Observe the two pods that they are not on the same node.
3) kubectl rollout restart mydeployment 
4) See that pods are on the same node.

**Anything else we need to know?**:
master-node and worker-node both are labeled as schedule=worker

`kubectl get node -l schedule=worker`
`NAME            STATUS   ROLES    AGE    VERSION`
`master-node     Ready    master   54d    v1.18.3`
`worker-node-1   Ready    <none>   160m   v1.18.3`

```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "schedule"
                operator: In
                values:
                - worker
            topologyKey: "kubernetes.io/hostname"

```

- Kubernetes version (use `kubectl version`): 1.18.3
- OS (e.g: `cat /etc/os-release`): CenOS 7

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#always-co-located-in-the-same-node

Followed this documentation.
