### ISSUE TITLE
DualStack:  The node of kubernetes v1.18.2 has only one ipv4 address. Access to pod via ipv6 is not possible

### ISSUE THREAD

**Issue by Duanzhiwei** [kubernetes/kubernetes#93598]
**What happened**:
I want to use kubeadm to build IPV4/IPv6 dual stack k8s cluster. But node internal IP only shows ipv4. I uses calico network plugin. The pod IP and service can be assgined ipv4 and ipv6. But  the pod cannot be accessed over ipv6 addresses.
**What you expected to happen**:
The cluster nodes have two ip addresses: ipv4 and ipv6. 
Run command: 
`kubectl get nodes k8s-linuxpool1-34450317-0 -o go-template --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}'`
can get the output like this (two ips):
> Hostname: k8s-linuxpool1-34450317-0
> InternalIP: 10.240.0.5
> InternalIP: 2001:1234:5678:9abc::5
> 
Service can be accessed using ipv6

**How to reproduce it (as minimally and precisely as possible)**:
kubeadm init config

```
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
featureGates: 
  IPv6DualStack: true
  clusterCIDR: "10.244.0.0/16,fc00::/108"
  
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.18.2
apiServer:
    certSANs:
    - "apiserver.cn"
    - "192.191.91.14"
    - "192.191.91.15"
    - "192.191.91.16"
    - "ipv6master01"
    - "ipv6master02"
    - "ipv6master03"  
    extraArgs:
        allow-privileged: "true"
        insecure-port: "8080"
        feature-gates: "IPv6DualStack=true"
        insecure-bind-address: "0.0.0.0"
controlPlaneEndpoint: "apiserver.cn:6443"
etcd: 
    local:
        dataDir: /data/etcd
networking:
  dnsDomain: cluster.local
  serviceSubnet: "10.96.0.0/12,fd00::/108"
  podSubnet: "10.244.0.0/16,fc00::/108"
controllerManager:
    extraArgs:
        address: 0.0.0.0
        controllers: "*,bootstrapsigner,tokencleaner"
        feature-gates: "IPv6DualStack=true"
        horizontal-pod-autoscaler-use-rest-clients: "true"
        cluster-cidr: "10.244.0.0/16,fc00::/108"
        service-cluster-ip-range: "10.96.0.0/12,fd00::/108" 
        node-cidr-mask-size-ipv4: "24"
        node-cidr-mask-size-ipv6: "120"
featureGates: 
  IPv6DualStack: true
imageRepository: registry.cn/k8s-1.18

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates: 
  IPv6DualStack: true
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.2
- Cloud provider or hardware configuration: VMware
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
# uname -a
Linux ipv6master01 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:54:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
# kubelet --version
Kubernetes v1.18.2
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```
- Network plugin and version (if this is a network-related bug): calico v3.8.2
- Others:
Kernel configuration
```net.netfilter.nf_conntrack_max = 5120000
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 30
net.netfilter.nf_conntrack_tcp_timeout_fin_wait = 30
net.ipv4.ip_forward = 1
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
net.ipv6.conf.all.forwarding = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
vm.swappiness = 0
```
ipvs configuration
```
#!/bin/bash
modprobe -- ip_vs
modprobe -- ip_vs_rr
modprobe -- ip_vs_wrr
modprobe -- ip_vs_sh
modprobe -- nf_conntrack_ipv4
modprobe -- br_netfilter
modprobe -- ip_conntrack
modprobe -- nf_conntrack_ipv6
````
docker configuretion
```
{
"insecure-registries":[
    "registry.cn",
    "0.0.0.0/0"
],
"graph":"/data/docker",
"exec-opts":["native.cgroupdriver=systemd"],
"log-driver":"json-file",
"log-opts":{
    "max-size":"100m"
},
"ipv6":true,
"fixed-cidr-v6":"2405:3140:3a:5201::910:0/120",
"storage-driver":"overlay2",
"storage-opts":[
    "overlay2.override_kernel_check=true"
]
}
```
calico configuretion
```
"ipam": {
              "type": "calico-ipam",
              "assign_ipv4": "true",
              "assign_ipv6": "true"
          },
# Auto-detect the BGP IP address.
            - name: IP
              value: "autodetect"
            - name: IP6
              value: "autodetect"
            - name: CALICO_IPV4POOL_CIDR
              value: "10.244.0.0/16"
            - name: CALICO_IPV6POOL_CIDR
              value: "fc00::/108"
            - name: FELIX_IPV6SUPPORT
              value: "true"
```

The machine supports both IPv4 and ipv6.  
You can ping ipv6 between nodes using the ping command
May be my init config is not correct.
