### ISSUE TITLE
Process Env then allow Env to replace existing values and Env don't have to guarantee the order

### ISSUE THREAD

**Issue by abhty822** [kubernetes/kubernetes#93668]
**What would you like to be added**:
Process Env then allow Env to replace existing values and Env don't have to guarantee the order
**Why is this needed**:
**For example**：
```
  - env:
    - name: RABBITMQ_NODENAME
      value: rabbit@$(MY_POD_NAME).rabbitmq-ha-discovery.test.svc.cluster.local
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
```
The above example，$(MY_POD_NAME) cant use MY_POD_NAME
I think it can be improved

/sig node
/sig apps
