### ISSUE TITLE
AWS ELB forwards traffic to deleted pod

### ISSUE THREAD

**Issue by jdomag** [kubernetes/kubernetes#93713]
**What happened**:
I have a deployment with 2 pods and LoadBalancer service associated that expose ELB in AWS.
When i do `kubectl delete pod xyz` i see that a pod got removed from list of endpoints however traffic from outside a cluster is still reaching the pod that being deleted (during its gracefull shutdown period).  

**What you expected to happen**:
When the pod gets deleted from endpoint list, new requests/connections are not reaching it any more.

**How to reproduce it (as minimally and precisely as possible)**:
1) Deploy echo app and service
```
---                                                                             
apiVersion: apps/v1                                                             
kind: Deployment                                                                
metadata:                                                                       
  name: echo-deployment                                                         
spec:                                                                           
  replicas: 2                                                                   
  selector:                                                                     
    matchLabels:                                                                
      app: echo-server                                                          
  template:                                                                     
    metadata:                                                                   
      labels:                                                                   
        app: echo-server                                                        
    spec:                                                                       
      containers:                                                               
        - name: echo-server                                                     
          image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2               
          ports:                                                                
            - name: http                                                        
              containerPort: 8080                                               
                                                                                                                                                                                                                                              
---                                                                             
apiVersion: v1                                                                  
kind: Service                                                                   
metadata:                                                                       
  annotations:                                                                  
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http         
  labels:                                                                       
    app: echo                                                                   
  name: echo                                                                    
  namespace: default                                                            
spec:                                                                           
  ports:                                                                        
  - name: http                                                                  
    port: 80                                                                    
    protocol: TCP                                                               
    targetPort: http                                                            
  selector:                                                                     
    app: echo-server                                                            
  type: LoadBalancer                      


```
2) Loop curl request and collect pod name only:
`for i in {1..1000}; do date && curl -s loadbalancer_dns_name:80 | grep Hostname ; done`
3) Kill one of the pod of echo app and observe curl results - after delete "button" is pressed traffic is still reaching the pod for few seconds


**Anything else we need to know?**:
The same test but triggering curl from any other pod within a cluster works fine - deletion of pod removes it from endpoint lists and no new requests are forwarded to it

I'm not sure if this is k8s bug - i know that ELB breaks is somehow, but not sure why. When i expose same service via NLB it works as expected - same, if i do curl directly to the node:port bypassing ELB




**Environment**:
AWS with k8s installed via kops
```
kubectl version                                                                                              
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
