### ISSUE TITLE
Volumes accept anything as volume type without complaining, and defaults to emptyDir

### ISSUE THREAD

**Issue by cristichiru** [kubernetes/kubernetes#93719]
**What happened**:

Created a confirgmap:

```yaml
name: myconfigmap
data:
  "opendkim.conf": |
    InternalHosts 0.0.0.0/0, ::/0
```

Wanted to mount a configmap, but made a small mistake (can you spot it?):

```yaml
 volumes:
 - name: dkim-conf
   configmap:
     name: myconfigmap
```

I was using subPath to mount a specific file instead of a directory:

```yaml
volumeMounts:
- name: dkim-conf
  mountPath: /etc/opendkim.conf
  subPath: opendkim.conf
```

But would fail because:

```
Warning  Failed     8s                kubelet, revo-nuc1  Error: failed to start container "smtp-relay": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/b8d762c9-f549-45aa-9430-dfa1df3a90c0/volume-subpaths/dkim-conf/smtp-relay/1\\\" to rootfs \\\"/home/shared/linux/var/lib/docker/overlay2/72a76ad81f16e0bb7be599d9ce24bdc2fe13310f5185df094638a0d13c0089ff/merged\\\" at \\\"/home/shared/linux/var/lib/docker/overlay2/72a76ad81f16e0bb7be599d9ce24bdc2fe13310f5185df094638a0d13c0089ff/merged/etc/opendkim.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  BackOff    4s (x3 over 22s)  kubelet, revo-nuc1  Back-off restarting failed container
```

Peaking the actual pod yaml, surprise: emptyDir!

```yaml
 volumes:
 - emptyDir: {}
   name: dkim-conf
```

**What you expected to happen**:

- Fail to create the statefulset or deployment, because volume type **configmap** does not exist, configMap (camel case) should be used

**How to reproduce it (as minimally and precisely as possible)**:

- Create any volume and as type put.. whatever you want, literally! Kubernetes will allow you to create the aretfact and default to emptyDir(). If for some reason you map a directory, no complaints!

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: bare metal

- OS (e.g: `cat /etc/os-release`): 
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"

- Kernel (e.g. `uname -a`): Linux revo-nuc2 5.7.12-050712-generic #202007311339 SMP Fri Jul 31 17:42:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubespray 2-13
- Network plugin and version (if this is a network-related bug): calico v3.15.1
- Others:
