### ISSUE TITLE
Limitrange request causes indefinite amount of pods spawned

### ISSUE THREAD

**Issue by dza89** [kubernetes/kubernetes#93750]
**What happened**:
Pods keep spawning indefinitely with OutOfcpu error

**What you expected to happen**:
A single error returned 

**How to reproduce it (as minimally and precisely as possible)**:

Add limitrange:
```
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: "{{ meta.name }}"
spec:
  limits:
  - default:
      cpu: 1
      memory: 512Mi
    defaultRequest:
      cpu: 1
      memory: 256Mi
    type: Container
```

Make sure your nodes have less resources available then 1 CPU (set high for this example)

Do a dummy deployment without any resources set

**Anything else we need to know?**:

My findings:
Since the limits are set on container level, the kubelet receives the requests, then the requestlimit is added and the container cannot be scheduled, the kubelet returns OutOfcpu and the replicaset deploys a new pod. And this starts an endless loop of pod spawning.

**Environment**:
- Kubernetes version 16.1
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 4.14.186-146.268.amzn2.x86_64
- Others:
kubeletVersion: v1.16.13-eks-2ba888
