### ISSUE TITLE
Pending DaemonSet pods should indicate what node they are trying to be scheduled on

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#93934]
We a re trying to schedule a daemonset and 5 pods could not be scheduled, which is fine/expected:
```
  Warning  FailedScheduling   76s (x97 over 26m)   default-scheduler   0/36 nodes are available: 31 node(s) didn't have free ports for the requested pod ports, 5 Insufficient memory.
```

... but there is no nice way of knowing which node this has failed to schedule on since the pod has no nodeSelector or spec.nodeName
under the hood the scheduler knows were it is trying to place the pod, so either setting the nodeSelector or having the target node in the event would improve debuggability.

**Comment by athenabot** [comment]
/sig node
/sig scheduling

These SIGs are my best guesses for this issue. Please comment `/remove-sig <name>` if I am incorrect about one.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by grosser** [comment]
@vllry good bot 🥇

**Comment by ahg-g** [comment]
The scheduler doesn't know if a pod is a DaemonSet pod. DaemonSet controller decides which node a pod should be scheduled on using nodeAffinity:

```
affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - <nodeName>
```

However, as in your case, a node could get filtered even before the scheduler gets to evaluate the NodeAffinity Filter (insufficient memory or host ports).

I don't think there is a pretty way to do what you are asking for, it will have to be special cased.
