### ISSUE TITLE
Pod security policy is is not working as expected

### ISSUE THREAD

**Issue by scardena** [kubernetes/kubernetes#93957]
**What happened**:
I have the following pod security policy in place (it's the only one, as I deleted the rest). I expect this to block all pods that are configured to be created with containers running as root user.
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: eks.restrictive
spec:
  hostNetwork: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
```
I am trying to deploy pods and deployments using the same configurations, but the PSP is failing for both cases. Below is the example of pods and deployments that I am using for this
**What you expected to happen**:
Both pods (single pod, and pod created by the deployment) should be created/scheduled, because they are compliant with the PSP (regardless if they fail to run whatever process inside the containers). Single pod gets created successfully, but the pod created by the deployment fails with the error: `Error creating: pods "web-deployment-5bb97cd969-" is forbidden: unable to validate against any pod security policy: []` (the error can be found when describing the RS created by the deployment)

**How to reproduce it (as minimally and precisely as possible)**:
Single pod definition:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: web
      image: k8s.gcr.io/nginx-slim:0.8
```
Deployment definition:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web-deployment 
  template:
    metadata:
      labels:
        app: web-deployment
    spec:
      containers:
      - name: web-deployment
        image: k8s.gcr.io/nginx-slim:0.8
        securityContext:
          runAsUser: 1000
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AWS EKS 
- OS (e.g: `cat /etc/os-release`): macos catalina
- Kernel (e.g. `uname -a`): Darwin Simons-MBP.hitronhub.home 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
