### ISSUE TITLE
Podpreset is not setting configuration for kube-apiserver

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#94024]
**What happened**:
Trying to change timezone related configuration in pods running in kube-system namespace, all pods working except kube-api server, controller and scheduler.
Deployed kubernetes cluster using kubespray.

**What you expected to happen**:
All pods should come up.

**How to reproduce it (as minimally and precisely as possible)**:
1) apply configuration using podpreset to the pods running in kube-system namespaces
2) check the logs of the apiserver, controller and scheduler.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
Linux demo 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubespray 
- Network plugin and version (if this is a network-related bug):
- Others:
```
podpreset yaml
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: tz-modify1
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: kube-apiserver
  volumeMounts:
    - name: timezone
      mountPath: /etc/localtime
  volumes:
    - name: timezone
      hostPath:
         path: /usr/share/zoneinfo/Asia/Kolkata
```
