### ISSUE TITLE
Downward API does not work inside of list object

### ISSUE THREAD

**Issue by jeffmendoza** [kubernetes/kubernetes#9407]
Trying to use the [Downward API](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/downward_api.md) inside of a list object results in an error when trying to create the objects:

> Error: ReplicationController "backend-rc" is invalid: [spec.template.spec.containers[0].env[0].valueFrom.fieldRef.fieldPath: invalid value 'metadata.name': error converting fieldPath, spec.template.spec.containers[0].env[1].valueFrom.fieldRef.fieldPath: invalid value 'metadata.namespace': error converting fieldPath]

Example:

``` yaml

---
apiVersion: v1beta3
kind: List
items:
- kind: ReplicationController
  metadata:
    name: backend-rc
    labels:
      type: backend-type
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          type: backend-type
      spec:
        containers:
        - name: backend-container
          image: gcr.io/google-samples/env-backend:1.1
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            protocol: TCP
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
- kind: Service
  metadata:
    name: backend-srv
    labels:
      type: backend-type
  spec:
    ports:
    - port: 5000
      protocol: TCP
    selector:
      type: backend-type
```

Taking the replication controller out of the list and running `kubectl create -f` with just the RC works fine:

``` yaml

---
apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: backend-rc
  labels:
    type: backend-type
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: backend-type
    spec:
      containers:
      - name: backend-container
        image: gcr.io/google-samples/env-backend:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```
