### ISSUE TITLE
Using variable expansion with env from podPreset

### ISSUE THREAD

**Issue by yuripastushenko** [kubernetes/kubernetes#94079]
**What would you like to be added**:
I would like to have the ability to inject environment variables that rely (expands) environment variables defined in podPreset.

**Why is this needed**:
Part of our services use consul as key-value storage.
We, as kubernetes cluster administrators, provide pod presets with consul http address environment variable, that is injected in pods/containers.
Because the environment variables from pod presets are added after user defined environment variables in pod manifest - we can't use variable expansion.

For example:
**PodPreset:**
```
kind: PodPreset
apiVersion: settings/v1alpha1
metadata:
  name: consul-env
spec:
  env:
    - name: CONSUL_HTTP_ADDR
      value: https://my-consul.tld
```
**Pod:**
```
kind: Pod
apiVersion: v1
metadata:
  name: my-pod
...
spec:
  containers:
  - env:
    - name: KEY
      value: $(CONSUL_HTTP_ADDR)/v1/key
  ...
```

Created pod have the following resulting manifest:
```
$ kubectl get pod my-pod -o yaml

kind: Pod
apiVersion: v1
metadata:
  name: my-pod
...
spec:
  containers:
  - env:
    - name: KEY
      value: $(CONSUL_HTTP_ADDR)/v1/key
    - name: CONSUL_HTTP_ADDR
      value: https://my-consul.tld
  ...
```

Because the environment variable `CONSUL_HTTP_ADDR` is injected after user defined environment variables, it can't be used in variable `KEY`.

When I run exec in pod and run `echo $KEY` I see `$(SERVICE_ADDR)/v1/KEY`.
I expected to see `https://my-consul.tld/v1/key`.

Would be great if there will be the ability to handle such cases.

**Additional info:**
I read [podPreset design proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/service-catalog/pod-preset.md) and did not find any answers on my case...
