### ISSUE TITLE
ServiceAccount cannot create secret it has access to via rbac `resourceNames`

### ISSUE THREAD

**Issue by alewitt2** [kubernetes/kubernetes#94101]
**What happened**: tried to create a secret via a service account. i had given this serviceaccount only access to create a secret with a specific name.

**What you expected to happen**: it to be able to create the secret with the name specified in `resourceNames`

**How to reproduce it (as minimally and precisely as possible)**:
1. create the rbac:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-cr
rules:
- apiGroups:
  - ""
  resourceNames:
  - my-generic-secret
  resources:
  - secrets
  verbs:
  - get
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-cr
subjects:
- kind: ServiceAccount
  name: my-sa
  namespace: default
```
2. try creating the secret using the rbac: `kubectl --as=system:serviceaccount:default:my-sa create secret generic my-generic-secret -n default`
3. for sanity, i also created the secret as cluster-admin and then verified i could `get` the secret using `--as=system:serviceaccount:default:my-sa` 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2+554af56", GitCommit:"554af56", GitTreeState:"clean", BuildDate:"2020-07-27T23:14:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: IBM IKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
