### ISSUE TITLE
Unable to resize PVC after CSI migration

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#94189]
**What happened**:
I tried to resize PVC which is migrated to CSI but the operation does not succeed.

**What you expected to happen**:
I would expect to be able to resize PVC after migration.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup a kubernetes v1.17.11 cluster with in-tree volume plugins

2. Create PVC

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: default
parameters:
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
```

3. Ensure that the PVC is successfully `Bound` with the in-tree provisioner

```
$ k describe pvc
Name:          ebs-claim
Namespace:     default
StorageClass:  default
Status:        Bound
Volume:        pvc-815ca829-865b-459f-bacc-139d3266128c
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      4Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    app
Events:
  Type    Reason                 Age   From                         Message
  ----    ------                 ----  ----                         -------
  Normal  ProvisioningSucceeded  41s   persistentvolume-controller  Successfully provisioned volume pvc-815ca829-865b-459f-bacc-139d3266128c using kubernetes.io/aws-ebs
```

4. Upgrade to v1.18.8, install aws-ebs-csi-driver and enable the CSI migration

More details on how we perform the CSI migration can be found in this document - https://github.com/gardener/gardener/blob/master/extensions/pkg/controller/csimigration/README.md.

5. Ensure that the PVC is migrated (`pv.kubernetes.io/migrated-to` annotation is set)

```
$ k describe pvc
Name:          ebs-claim
Namespace:     default
StorageClass:  default
Status:        Bound
Volume:        pvc-815ca829-865b-459f-bacc-139d3266128c
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               pv.kubernetes.io/migrated-to: ebs.csi.aws.com
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      4Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    app
Events:
  Type    Reason                 Age    From                         Message
  ----    ------                 ----   ----                         -------
  Normal  ProvisioningSucceeded  8m22s  persistentvolume-controller  Successfully provisioned volume pvc-815ca829-865b-459f-bacc-139d3266128c using kubernetes.io/aws-ebs
```

6. Edit the PVC and try to resize it

7. Ensure that the resize fails with:

```
$ k describe pvc
Name:          ebs-claim
Namespace:     default
StorageClass:  default
Status:        Bound
Volume:        pvc-815ca829-865b-459f-bacc-139d3266128c
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               pv.kubernetes.io/migrated-to: ebs.csi.aws.com
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      4Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    app
Events:
  Type     Reason                 Age               From                         Message
  ----     ------                 ----              ----                         -------
  Normal   ProvisioningSucceeded  9m10s             persistentvolume-controller  Successfully provisioned volume pvc-815ca829-865b-459f-bacc-139d3266128c using kubernetes.io/aws-ebs
  Normal   ExternalExpanding      2s (x11 over 7s)  volume_expand                CSI migration enabled for ebs.csi.aws.com; waiting for external resizer to expand the pvc
  Warning  ExternalExpanding      2s (x11 over 7s)  volume_expand                error getting CSI driver name for pvc default/ebs-claim, with error could not find CSI Driver name for plugin ebs.csi.aws.com
```

Ensure that the annotation `volume.kubernetes.io/storage-resizer` is never set to the PVC.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.17.11 + v1.18.8
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: https://github.com/gardener/gardener + https://github.com/gardener/gardener-extension-provider-aws
- Network plugin and version (if this is a network-related bug):
- Others:
