### ISSUE TITLE
agnhost image mounttest does not work well on Windows

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#94237]
On a K8s Windows cluster, try to run container with agnhost image with following yaml file but failed 

```
apiVersion: v1
kind: Pod
metadata:
  name: pod-test2
spec:
  containers:
  - args:
    - mounttest
    - --new_file_0644=/test-volume/test-file
    - --file_mode=/test-volume/test-file
    image: k8s.gcr.io/e2e-test-images/agnhost:2.20
    imagePullPolicy: IfNotPresent
    name: test-init-subpath-dynamicpv-kmdm
    volumeMounts:
    - mountPath: /test-volume
      name: test-volume
```
Seems like --file_mode does not work well. 
```
error from PowerShell Script: exit status 1, ./filePermissions.ps1 : The term './filePermissions.ps1' is not recognized as 
the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is
```

Windows Server 2019

**Comment by wawa0210** [comment]
I retried the test mentioned in the issue on the latest kubernetes 1.19, but it did not reproduce. Here are my specific steps

the pod yaml 
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-test2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - windows
  containers:
  - args:
    - mounttest
    - --new_file_0644=/test-volume/test-file
    - --file_mode=/test-volume/test-file
    image: claudiubelu/agnhost:2.20
    imagePullPolicy: IfNotPresent
    name: test-init-subpath-dynamicpv-kmdm
    volumeMounts:
    - mountPath: /test-volume
      name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        # directory location on host
        path: /data
        # this field is optional
        type: Directory
```

The pod is running normally, and the directory on the windows node is successfully created

```
kubectl get po -o wide | grep 'pod-test2'
pod-test2                    1/1     Running            7          13m     10.244.3.6   10-7-107-203   <none>           <none>
```

![image](https://user-images.githubusercontent.com/7907809/91640032-50f77f00-ea4d-11ea-9f7a-ee848ae7301c.png)


I am more confused, can you help me see what is inconsistent with your test?

**Comment by jingxu97** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-subpath
  namespace: provisioning-3102
spec:
  containers:
  - args:
    - mounttest
    image: k8s.gcr.io/e2e-test-images/agnhost:2.20
    imagePullPolicy: IfNotPresent
    name: test-container-subpath-dynamicpv-cxcf
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /test-volume
      name: test-volume
      subPath: provisioning-3102
    - mountPath: /probe-volume
      name: liveness-probe-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-kd7dw
      readOnly: true
  - args:
    - mounttest
    - --file_content_in_loop=/test-volume/provisioning-3102/test-file
    - --retry_time=20
    image: k8s.gcr.io/e2e-test-images/agnhost:2.20
    imagePullPolicy: IfNotPresent
    name: test-container-volume-dynamicpv-cxcf
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /test-volume
      name: test-volume
    - mountPath: /probe-volume
      name: liveness-probe-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-kd7dw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - mounttest
    - --new_file_0644=/test-volume/test-file
    - --file_mode=/test-volume/test-file
    image: k8s.gcr.io/e2e-test-images/agnhost:2.20
    imagePullPolicy: IfNotPresent
    name: test-init-subpath-dynamicpv-cxcf
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /test-volume
      name: test-volume
      subPath: provisioning-3102
    - mountPath: /probe-volume
      name: liveness-probe-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-kd7dw
      readOnly: true
  nodeName: e2e-test-jinxu-windows-node-group-2mns
  nodeSelector:
    kubernetes.io/os: windows
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 1
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: gcepdd2hzx
  - emptyDir: {}
    name: liveness-probe-volume
  - name: default-token-kd7dw
    secret:
      defaultMode: 420
      secretName: default-token-kd7dw
```

Could you try this? I copied it from one of the subPath test
