### ISSUE TITLE
Secret volume mount not updated if key is renamed and KeyToPath mounting is used

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes/kubernetes#94279]
**What happened**:

I created a pod deployment which volume mounted a `Secret` using key-to-path bindings (ex: `secret.txt`, contents "Hola Terra"). After creating the `Secret` and `Deployment`, I changed the name of the key referenced key in the `Secret` (ex: `secret.config`). The `Secret` was successfully updated, but the file in the pod remained the same - the file was not removed or truncated.

Next, I restored the original key name, but changed the contents (ex: `secret.txt`, contents "Hello world"). The file in the pod was eventually updated, but after a noticeable delay (at least 50 seconds).

**What you expected to happen**:

I don't know what the correct behavior should be if the key in a `Secret` is renamed and the original key name is referenced in a pod volume mount. Restoring the original key name with new file contents should result in the file being updated in the volume mount. This eventually happens, but after a noticeable delay - at least 50 seconds.

**How to reproduce it (as minimally and precisely as possible)**:

0. Create a `Secret` with the contents in key `file.txt`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  file.txt: SG9sYSBUZXJyYSEK
```

1. Create a deployment which mounts the `Secret` volume with key-to-path bindings:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-key-path
  labels:
    app: test-key-path
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-key-path
  template:
    metadata:
      labels:
        app: test-key-path
    spec:
      containers:
      - name: main
        image: registry.access.redhat.com/ubi8/ubi:latest
        command:
        - "/bin/sh"
        - "-c"
        - |
          trap 'jobs -p | xargs -r kill; echo shutting down; exit 0' TERM
          while [ true ];
          do
            ls -al -R /mounted/secret
            cat /mounted/secret/file.txt
            sleep 10 & wait ${!}
          done
        volumeMounts:
        - name: secret
          mountPath: /mounted
      volumes:
      - name: secret
        secret:
          secretName: test-secret
          items:
          - key: file.txt
            path: secret/file.txt
```

2. Rename the key for the referenced secret to `file.config`.
3. Restore the original key name to `file.txt`, but with different contents:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  file.txt: SGVsbG8gd29ybGQhCg==
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.0-rc.2. Also observed this in 1.18
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Red Hat CoreOS
- Kernel (e.g. `uname -a`):
- Install tools: openshift-install
- Network plugin and version (if this is a network-related bug): N/A
- Others:
