### ISSUE TITLE
Featuregate ExperimentalHostUserNamespaceDefaulting in Kubernetes 

### ISSUE THREAD

**Issue by subrnath** [kubernetes/kubernetes#94296]
/sig API Machinery

I want to activate  the feature gate ExperimentalHostUserNamespaceDefaulting as documented https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/.

I have enabled "User Namespace"  in docker daemon config  

1.systemctl stop docker
2.rm -rf /var/lib/docker
3. Add the following in /etc/docker/daemon.json
"userns-remap": "default"
4. systemctl start docker

I made the config.yaml with featuregate activated 

apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.19.0
kind: ClusterConfiguration
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  extraArgs:
    advertise-address: 172.24.17.100
    feature-gates: ExperimentalHostUserNamespaceDefaultingGate=true

Then running the command - "sudo kubeadm init --config config.yaml". This fails to start the cluster and throws the error as pasted below -

_

> :10248: connect: connection refused.
> 
>         Unfortunately, an error has occurred:
>                 timed out waiting for the condition
> 
>         This error is likely caused by:
>                 - The kubelet is not running
>                 - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
> 
>         If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
>                 - 'systemctl status kubelet'
>                 - 'journalctl -xeu kubelet'
> 
>         Additionally, a control plane component may have crashed or exited when started by the container runtime.
>         To troubleshoot, list all containers using your preferred container runtimes CLI.
> 
>         Here is one example how you may list all Kubernetes containers running in docker:
>                 - 'docker ps -a | grep kube | grep -v pause'
>                 Once you have found the failing container, you can inspect its logs with:
>                 - 'docker logs CONTAINERID'

"systemctl status kubelet" gives the error - "kubelet.go:2183] node "master" not found" 

I tried with the "feature-gates: ExperimentalHostUserNamespaceDefaulting=true" also but same issue. I have tried this with different K8s version 1.19, 1.18.8, 1.18.4 but all throws the same error message. Please help me if anyone is able to make  k8s cluster up with this feature gate.

/sig API Machinery

**Comment by neolit123** [comment]
ExperimentalHostUserNamespaceDefaultingGate seems like a feature gate that is relevant to the kubelet not kubeadm:
https://github.com/kubernetes/kubernetes/search?q=ExperimentalHostUserNamespaceDefaultingGate&unscoped_q=ExperimentalHostUserNamespaceDefaultingGate

when using kubeadm you can set it like so:
```
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.19.0
kind: ClusterConfiguration
networking:
podSubnet: 10.244.0.0/16
apiServer:
  extraArgs:
  advertise-address: 172.24.17.100
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates:
  ExperimentalHostUserNamespaceDefaultingGate: true
```
