### ISSUE TITLE
`kubectl rollout` gives confusing error when invoked with custom resource: “error: unable to decode file”

### ISSUE THREAD

**Issue by prakashshp92** [kubernetes/kubernetes#94332]
I am facing an issue with using the` kubectl rollout status` command with `CRD resource`.

Environment:
 ` Kubernetes version: v1.16.13-gke.1 on GCP-GKE` and 
`kubectl version : v1.19.0`
` `Strimzi version v0.19.0`, [](https://strimzi.io/)`

I am using Strimzi [](https://strimzi.io/) to deploy Kafka on Kubernetes.
Strimzi has Customer Resource definition for Kafka.
After I deploy the custom resource, I try to check if the cluster is ready using `kubectl rollout status` cmd.

I run `$ kubectl apply -f kafka-persistent.yaml` to apply to the custom resource and 
`$ kubectl rollout status -f kafka-persistent.yaml` to wait for the up scaling of replicas, But , I get the following error 
for `kubectl rollout status` cmd

`error: unable to decode "examples/kafka/kafka-persistent.yaml": no kind "Kafka" is registered for version "kafka.strimzi.io/v1beta1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"`

Here is the custom resource file that I used, `kafka-persistent.yaml`:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 7
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}


```
Is this a Kubernetes bug ? Can't I use `kubectl rollout status` with `CRD` resource ?

Can you please help me solve this ?
