### ISSUE TITLE
AWS NLB (UDP): Support sticky sessions

### ISSUE THREAD

**Issue by palsivertsen** [kubernetes/kubernetes#94416]
**What would you like to be added**:
The AWS Network Load Balancer has support for sticky sessions through an [attribute](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#sticky-sessions) on Target Groups that could easily map to the [sessionAffinity](https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#servicespec-v1-core) parameter in the `ServiceSpec`.

**Why is this needed**:
When working with UDP it's often useful to route packets from one client to the same server, especially if the payload is split up between several packets.

**Example spec:**
```
apiVersion: v1
kind: Service
metadata:
  name: example
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    name: example
  sessionAffinity: ClientIP
  ports:
  - protocol: UDP
    port: 5555
    targetPort: 5555
```
