### ISSUE TITLE
Duplicate external metrics specs added to HorizontalPodAutoscaler when diffing with no change

### ISSUE THREAD

**Issue by goodspark** [kubernetes/kubernetes#94420]
**What happened**:

When I ran a diff for a HorizontalPodAutoscaler with external metrics with no change, the diff result showed the same metric being added again to the metrics list. Note that when I apply, the metrics is not added twice as the diff suggests.

**What you expected to happen**:

The diff to show no changes.

**How to reproduce it (as minimally and precisely as possible)**:

`hpa.yml`
```yml
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: spark-hpa-test
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spark-test-app
  metrics:
    - type: External
      external:
        metric:
          name: spark_test.thing
          selector:
            matchLabels:
              env: development
        target:
          type: Value
          value: 5.0
```

```sh
kubectl apply -f hpa.yml
kubectl diff -f hpa.yml
```

```
diff -u -N /tmp/LIVE-740417398/autoscaling.v2beta2.HorizontalPodAutoscaler.default.spark-hpa-test /tmp/MERGED-791756893/autoscaling.v2beta2.HorizontalPodAutoscaler.default.spark-hpa-test
--- /tmp/LIVE-740417398/autoscaling.v2beta2.HorizontalPodAutoscaler.default.spark-hpa-test	2020-09-02 02:27:32.708217388 -0700
+++ /tmp/MERGED-791756893/autoscaling.v2beta2.HorizontalPodAutoscaler.default.spark-hpa-test	2020-09-02 02:27:32.864217748 -0700
@@ -23,6 +23,16 @@
         type: Value
         value: "5"
     type: External
+  - external:
+      metric:
+        name: spark_test.thing
+        selector:
+          matchLabels:
+            env: development
+      target:
+        type: Value
+        value: "5"
+    type: External
   minReplicas: 1
   scaleTargetRef:
     apiVersion: apps/v1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", 
  GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", 
  GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.1503", 
  GitCommit:"fb367de18820fe57bac5d97ad60b7a2cef8765e9", GitTreeState:"clean", BuildDate:"2020-08-18T00:02:15Z", 
  GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`):
  ```
  NAME="Ubuntu"
  VERSION="20.04.1 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
  ```
- Kernel (e.g. `uname -a`): `Linux sam-XPS-15-9500 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
