### ISSUE TITLE
Secrets are accessible even when RBAC for secrets is not allowed

### ISSUE THREAD

**Issue by JakubJecminek** [kubernetes/kubernetes#94469]
**What happened**:
I am trying to setup read-only service account for kubernetes-dashboard that would allow read access to all resources except secrets. 
I used the following configuration:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-role
rules:
  - apiGroups:
      - ""
      - apps
      - core
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
      - services/proxy
    verbs:
      - "get"
      - "list"
      - "watch"
      - "head"
  - nonResourceURLs: ["*"]
    verbs:
      - get
      - watch
      - list
```
**Notice that secrets are not listed in resources section.**
With such role when trying to access secrets through kubectl I correctly receive the error:
`Error from server (Forbidden): secrets is forbidden: User "developer:xxx" cannot list resource "secrets" in API group "" in the namespace "default"`

Assigning this role to service account and accessing dashboard using this account (bearer token added to authorization header) will result in read-only access, which is correct. But I can still access (list) secrets and also see individual secrets values.

**What you expected to happen**:
Accessing secrets sections of dashboard should not be possible (honouring RBAC of assigned role) and also accessing and reading individual secret values should also not be possible. This seems to be problem of K8s API server not actually problem of k8s dashboard.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14
- Cloud provider or hardware configuration: Amazon EKS
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
Dashboard version: 2.0.3
