### ISSUE TITLE
Enable readonly Configmaps in other namespaces

### ISSUE THREAD

**Issue by mapdegree** [kubernetes/kubernetes#94486]
**What would you like to be added**:
Configmaps to be shareable as read only in specified namespaces

**Why is this needed**:
Enable other product teams to be able to share Configmaps cross namespaces in order to prevent duplication

For example, other teams in their namespaces need to share a configmap that will be scraped off (read) by a central application within a dedicated namespace

**Comment by liggitt** [comment]
configmaps from any namespace can be read via the API by service accounts from other namespaces if they have permission. readonly permission can be granted to read particular configmaps. 

You can define a permission like this:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: your-configmap-namespace
  name: your-configmap-reader-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  resourceNames: ["your-configmap-name"]
  verbs: ["get"]
``` 

and then grant it like this:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: your-configmap-reader-binding
  namespace: your-configmap-namespace
subjects:
# You can specify more than one "subject"
# allow serviceaccount sa1 in namespace ns1
- kind: ServiceAccount
  name: sa1
  namespace: ns1
# allow all serviceaccounts in ns2
- kind: Group
  name: system:serviceaccounts:ns2
  apiGroup: rbac.authorization.k8s.io
# allow all serviceaccounts
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: your-configmap-reader-role
  apiGroup: rbac.authorization.k8s.io
```
