### ISSUE TITLE
DualStack: IPv6 service generates EndpointSlice containing IPv4 addresses

### ISSUE THREAD

**Issue by jmillikin-stripe** [kubernetes/kubernetes#94505]
**What happened**:
Given a `Service` resource with `ipFamily: "IPv6"`, selecting dual-stack pods that use IPv6 as their primary IP, the controller manager generates both `Endpoint` and `EndpointSlice` resources. The `Endpoint` resource is being generated correctly (it contains IPv6 IPs), but the corresponding `EndpointSlice` is being generated with IPv4 IPs.

**What you expected to happen**:
I expected the `EndpointSlice` resource to contain IPs in the same address family as the `Service` and the `Endpoint`.

**How to reproduce it (as minimally and precisely as possible)**:
Create an IPv6 service selecting dual-stack pods, which have their PodIPs array containing [ipv6, ipv4] addrs in that order. Fetch the `Endpoint` and `EndpointSlice` resources and inspect their content.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.6
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux v5.4.0
- Install tools: n/a
- Network plugin and version (if this is a network-related bug): Using `bridge` and `host-local` CNI plugins at v0.8.6
- Others:

**Comment by athenabot** [comment]
/triage unresolved

Comment `/remove-triage unresolved` when the issue is assessed and confirmed.

🤖 I am a bot run by vllry. 👩‍🔬

**Comment by robscott** [comment]
Hey @jmillikin-stripe, thanks for reporting this! I believe this was fixed by https://github.com/kubernetes/kubernetes/pull/91399 and the cherry-pick back to 1.18 just got merged in: https://github.com/kubernetes/kubernetes/pull/94119. I'll try to take some time to verify this PR does fix the root issue. 

/remove-triage unresolved

**Comment by jmillikin-stripe** [comment]
Fantastic, thanks. I'll also try verifying that fix on my end by cherry-picking it into our k8s build (probably later next week).

**Comment by jmillikin-stripe** [comment]
I did some testing with the above fixes, but didn't have much success. I added some debugging prints and now suspect the issue isn't in `EndpointSlice` itself -- it seems like the `Service` resource is being persisted incorrectly.

The service YAML is:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: k8s-overlay-testing
  namespace: net-sandbox
spec:
  type: ClusterIP
  clusterIP: None
  ipFamily: IPv6
  ports:
  - name: example-service-port
    port: 4567
  publishNotReadyAddresses: true
  selector:
    example.com/service-name: k8s-overlay-testing
```

but what I get back from `kubectl get service -o yaml` does not have the `ipFamily` field set. This is surprising because there was no error on the creation step -- the field is silently dropped. Due to the missing IP family, `endpointutil.IsIPv6Service()` returns `false` for that service.
```yaml
spec:
  clusterIP: None
  ports:
  - name: example-service-port
    port: 4567
    protocol: TCP
    targetPort: 4567
  publishNotReadyAddresses: true
  selector:
    example.com/service-name: k8s-overlay-testing
  sessionAffinity: None
  type: ClusterIP
```

Looking at the diff, this code that was in the `Endpoint` controller was probably why it was working:
```go
	// api-server service controller ensured that the service got the correct IP Family
	// according to user setup, here we only need to match EndPoint IPs' family to service
	// actual IP family. as in, we don't need to check service.IPFamily
```
