### ISSUE TITLE
Rolling update of a windows container has failures

### ISSUE THREAD

**Issue by brianharwell** [kubernetes/kubernetes#94533]
**What happened**:
I am doing a rolling update and the transition from the old pod to the new pod is not seamless. I am seeing failed requests during the transition.

**What you expected to happen**:
The new pod is up and available so the transition should be seamless.

**How to reproduce it (as minimally and precisely as possible)**:
Step 1: Deploy this deployment. The Windows image has a static index page.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iistest
  name: iistest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iistest
  template:
    metadata:
      labels:
        app: iistest
    spec:
      containers:
      - image: brianharwell/iis-test:v1
        name: iis-test
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iistest
  name: iistest
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: iistest
  type: NodePort
```
Step 2: Run a constant loop hitting the service
```
$url = "http://server:nodeport"

$ProgressPreference = 'SilentlyContinue'

$iter = 0;
$maxIter = 100000;
$delay = 10;
$failed = 0;

while ($iter -lt $maxIter) {
  try {
    $response = iwr -UseBasicParsing -Uri $url

    Write-Host "Iteration: $iter, Response received, Failed: $failed"
  }
  catch {
    $failed++
    Write-Host "Request failed: $_" -ForegroundColor Red
  } 

  Start-Sleep -Milliseconds $delay

  $iter++
}
```
Step 3: Update the image
```
kubectl set image deploy iistest iis-test=brianharwell/iis-test:v2
```

The error I see is
```
Request failed:
Service Unavailable

Service Unavailable
HTTP Error 503. The service is unavailable.
```

It only happens once but it should not happen at all.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client: v1.17.6
Server: v1.18.6

- Cloud provider or hardware configuration:
vSphere. Using Rancher. 1 master, 1 worker, 1 Windows worker.

- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"

- Kernel (e.g. `uname -a`):
Linux sandk8swl-04 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
Rancher v2.4.5

- Network plugin and version (if this is a network-related bug):
Flannel, tried with l2bridge and vxlan mode

- Others:

**Comment by brianharwell** [comment]
I tried adding a startup probe and I get the same result

```
startupProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
```

I do not think the issue is with sending traffic to the new pod. I think traffic is being sent to the old point as it is being terminated.
