### ISSUE TITLE
PVC manually created when DefaultStorageClass is turned on cannot bind to PV

### ISSUE THREAD

**Issue by zxiaozhou** [kubernetes/kubernetes#94592]
**What happened**:
PVC manually created when DefaultStorageClass is turned on cannot bind to PV.
What the PVC log sees is that the SC with the default storage is called to create the PV
1. Not open DefaultStorageClass
![image](https://user-images.githubusercontent.com/62740686/92386894-3c02a600-f147-11ea-9a6c-f7f8d932ad0c.png)

2. open DefaultStorageClass
![image](https://user-images.githubusercontent.com/62740686/92386941-4fae0c80-f147-11ea-9ff0-fd0a5f389faf.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. open DefaultStorageClass
2. create pvc and pv
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cephfs-nginx
  labels:
    ceph: cephfs-nginx
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteMany 
  cephfs:
    monitors:
      - 192.168.56.21:6789
      - 192.168.56.22:6789
      - 192.168.56.23:6789
    user: admin
    path: /web-service
    secretRef:
      name: ceph-admin
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cephfs-nginx
  namespace: web-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      ceph: cephfs-nginx

```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 18.6
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):  CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux node1 3.10.0-1127.19.1.el7.x86_64
