### ISSUE TITLE
Can't use properties with additionalProperties for custom resource validation

### ISSUE THREAD

**Issue by mtsmfm** [kubernetes/kubernetes#94593]
**What happened**:

```
$ cat staging/src/k8s.io/sample-controller/artifacts/examples/crd-validation.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.k8s.io
spec:
  group: samplecontroller.k8s.io
  version: v1alpha1
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
          additionalProperties: false
```

```
$ kubectl apply -f staging/src/k8s.io/sample-controller/artifacts/examples/crd-validation.yaml
The CustomResourceDefinition "foos.samplecontroller.k8s.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].additionalProperties: Forbidden: additionalProperties and properties are mutual exclusive
```

**What you expected to happen**:

`kubectl apply -f staging/src/k8s.io/sample-controller/artifacts/examples/crd-validation.yaml` finishes successufully.

**How to reproduce it (as minimally and precisely as possible)**:

Create the following yaml and apply it. 

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.k8s.io
spec:
  group: samplecontroller.k8s.io
  version: v1alpha1
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
          additionalProperties: false
```

**Anything else we need to know?**:

It seems this validation is implemented in https://github.com/kubernetes/kubernetes/pull/62333.
But additionalProperties can be false to reject unnecessary properties.

> For more information about the properties, see JSON Schema Core and JSON Schema Validation. Unless stated otherwise, the property definitions follow the JSON Schema.

https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/versions/3.0.3.md#schema-object

https://tools.ietf.org/html/draft-wright-json-schema-validation-00#page-10

>  If "additionalProperties" is false, validation succeeds only if the
>   instance is an object and all properties on the instance were covered
>   by "properties" and/or "patternProperties".

Actually openapi's json schema uses `properties` with `additionalProperties`

https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/schemas/v3.0/schema.yaml#L36

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Kernel (e.g. `uname -a`):

```
$ uname -a
Linux DESKTOP-4F3GLEP 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools: Docker for Windows (WSL2)
- Network plugin and version (if this is a network-related bug):
- Others:
