### ISSUE TITLE
new scheduler_perf framework: add a deleteNodes op?

### ISSUE THREAD

**Issue by adtac** [kubernetes/kubernetes#94601]
Note: this issue should be viewed in the context of #93252.

**What would you like to be added**: A `deleteNodes` op in the new scheduler_perf framework would be nice to have.

**Why is this needed**: We can currently create additional nodes in scheduler_perf tests. The opposite direction (decreasing the number of nodes available) isn't supported however. Having this would allow us to test performance that simulates autoscaling-like behaviour.

An initial proposal:

```yaml
workloadTemplate:
- createNodes: 500
- createPods: 200
- deleteNodes: 300  # this
- createPods: 200
```

/sig scheduling
/sig testing
/assign
