### ISSUE TITLE
topologySpreadConstraints ignored when nodeAffinity is configured

### ISSUE THREAD

**Issue by jeid64** [kubernetes/kubernetes#94627]
Hello,

I seem to have hit a bug with topologySpreadConstraints. I am trying to set a topologySpreadConstraints to only schedule a pod onto a node only if there are no other pods on the same node with that label. I also want to set an affinity to only schedule pods onto nodes with a label of "type=kind". I add two workers to my kind cluster, so I would expect only 2 pods would be scheduled.

If I label my nodes with "type=kind" and then set a nodeAffinity to only schedule to nodes with "type=kind", my topologySpreadConstraint is ignored and all 10 of my pods are scheduled to my 2 worker nodes!

**What happened**:
kube-scheduler ignored my topologySpreadConstraint and scheduled all 10 pods onto my 2 worker nodes.

**What you expected to happen**:
kube-scheduler respect my topologySpreadConstraint only allowing 2 pods to be scheduled.

**How to reproduce it (as minimally and precisely as possible)**:
I've tried with 1.18.3, 1.18.8, and 1.19.0.

Add kind-example-config.yaml with contents below.
```
# three node (two workers) cluster config
 kind: Cluster
 apiVersion: kind.x-k8s.io/v1alpha4
 nodes:
 - role: control-plane
   image: kindest/node:v1.19.0
 - role: worker
   image: kindest/node:v1.19.0
 - role: worker
   image: kindest/node:v1.19.0
```

```
./kind create cluster --config kind-example-config.yaml
kubectl label nodes kind-worker type=kind
kubectl label nodes kind-worker2 type=kind
```

Then add this deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: test
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - "kind"
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1
```

You should see all 10 pods are scheduled, ignoring the topologySpreadConstraints field.
```
kubectl get pods -o wide
NAME                    READY   STATUS    RESTARTS   AGE   IP            NODE           NOMINATED NODE   READINESS GATES
test-5b94766dcd-42766   1/1     Running   0          4s    10.244.1.3    kind-worker2   <none>           <none>
test-5b94766dcd-4z287   1/1     Running   0          4s    10.244.2.15   kind-worker    <none>           <none>
test-5b94766dcd-7g5jr   1/1     Running   0          4s    10.244.2.14   kind-worker    <none>           <none>
test-5b94766dcd-8n626   1/1     Running   0          4s    10.244.1.5    kind-worker2   <none>           <none>
test-5b94766dcd-hxxss   1/1     Running   0          4s    10.244.2.17   kind-worker    <none>           <none>
test-5b94766dcd-hzdfc   1/1     Running   0          4s    10.244.1.6    kind-worker2   <none>           <none>
test-5b94766dcd-kmp6g   1/1     Running   0          4s    10.244.1.4    kind-worker2   <none>           <none>
test-5b94766dcd-vkcqn   1/1     Running   0          4s    10.244.2.16   kind-worker    <none>           <none>
test-5b94766dcd-x7m4z   1/1     Running   0          4s    10.244.2.13   kind-worker    <none>           <none>
test-5b94766dcd-xsx9c   1/1     Running   0          4s    10.244.1.7    kind-worker2   <none>           <none>
```

**Anything else we need to know?**:
Just to make sure my topologySpreadConstraints worked, I tested a deployment with a removed affinity section.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: test
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: type
      #           operator: In
      #           values:
      #           - "kind"
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1
```
They ended up working perfectly, you can see that only two pods are scheduled:
```
kubectl get pods -o wide
NAME                    READY   STATUS    RESTARTS   AGE   IP            NODE           NOMINATED NODE   READINESS GATES
test-6ffb6645b7-25pvz   0/1     Pending   0          4s    <none>        <none>         <none>           <none>
test-6ffb6645b7-7whvr   0/1     Pending   0          4s    <none>        <none>         <none>           <none>
test-6ffb6645b7-85vdt   0/1     Pending   0          4s    <none>        <none>         <none>           <none>
test-6ffb6645b7-8zn56   0/1     Pending   0          4s    <none>        <none>         <none>           <none>
test-6ffb6645b7-bs99n   1/1     Running   0          4s    10.244.2.12   kind-worker    <none>           <none>
test-6ffb6645b7-j7x8z   1/1     Running   0          4s    10.244.1.2    kind-worker2   <none>           <none>
test-6ffb6645b7-q2dj8   0/1     Pending   0          4s    <none>        <none>         <none>           <none>
test-6ffb6645b7-tj87m   0/1     Pending   0          4s    <none>        <none>         <none>           <none>
test-6ffb6645b7-ww7c8   0/1     Pending   0          4s    <none>        <none>         <none>           <none>
test-6ffb6645b7-x2pnn   0/1     Pending   0          4s    <none>        <none>         <none>           <none>
```

The documentation for topologySpreadConstraintsexplicitly calls out support for nodeaffinity https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#example-multiple-topologyspreadconstraints but I can't figure out what I might be doing wrong? 

**Environment**:
- Kubernetes version (use `kubectl version`):
1.19.0, 1.18.8, 1.18.3
- Cloud provider or hardware configuration:
kind
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
kind
