### ISSUE TITLE
[CRD] Prunes the fields and validation does not fail

### ISSUE THREAD

**Issue by akartsky** [kubernetes/kubernetes#94690]
Hi, I'm one of the contributors of [amazon-sagemaker-operator-for-k8s](https://github.com/aws/amazon-sagemaker-operator-for-k8s)

**What happened**:
While creating a CR, I specified an optional field at wrong indentation level and the field got pruned and execution continued as if that field wasn't specified at all

**What you expected to happen**:
Expected a validation error 

**How to reproduce it (as minimally and precisely as possible)**:

1. Install our operator : [installer.yaml](https://github.com/aws/amazon-sagemaker-operator-for-k8s/blob/master/release/rolebased/installer.yaml)
    ```
    kubectl apply -f https://raw.githubusercontent.com/aws/amazon-sagemaker-operator-for-k8s/efed5c85c52c6faa7b9c619582939752c9d6f6e8/release/rolebased/installer.yaml
    ```
2. CR file : test_hosting.yaml
    ```
    apiVersion: sagemaker.aws.amazon.com/v1
    kind: HostingDeployment
    metadata:
      name: test-hosting-validation
    spec:
      region: us-east-1
      productionVariants:
        - variantName: AllTraffic
          modelName: test-model
          initialInstanceCount: 1
          instanceType: ml.r5.large
          initialVariantWeight: 1
      models:
        - name: test-model
          executionRoleArn: arn:aws:iam::12345678910:role/some-iam-role
          containers:
            - containerHostname: test
              image: someimage/toy:nop
              somefield: XXXXXXXThisIsAtWrongIndentationLevelXXXXXXX
    ```
3. Create CR
    ```
    $ kubectl apply -f test_hosting.yaml --validate=true
    hostingdeployment.sagemaker.aws.amazon.com/test-hosting-validation created
    ```
    No validation error 👆🏼

4. Describe
    ```
    $ kubectl describe HostingDeployment test-hosting-validation
    .
    .
    .
    Spec:
      Models:
        Containers:
          Container Hostname:  test
          Image:               someimage/toy:nop
        Execution Role Arn:    arn:aws:iam::12345678910:role/some-iam-role
        Name:                  test-model
      Production Variants:
        Initial Instance Count:  1
        Initial Variant Weight:  1
        Instance Type:           ml.r5.large
        Model Name:              test-model
        Variant Name:            AllTraffic
      Region:                    us-east-1
    Status:
      Additional: 
    .
    .
    .
    ```
    `somefield: XXXXXXXThisIsAtWrongIndentationLevelXXXXXXX` is pruned 

**Anything else we need to know?**:
Tried to add `x-kubernetes-preserve-unknown-fields: true` [installer.yaml#L608](https://github.com/akartsky/amazon-sagemaker-operator-for-k8s/blob/8866f32e411c0f6a335c895bda85b666d16ec538/release/rolebased/installer.yaml#L608)
But it still gets pruned 

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Tools: Kubebuilder
