### ISSUE TITLE
Downward API for resource limits

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#9473]
Is it possible inside a container to discover your resource limits, in particular the memory limit.

Apparently this is sometime put under `/sys/fs/cgroup/memory/memory.stat`, but that isn't present.  And /proc/meminfo is the memory of the host (AFAICT)

I would like, for example, to specify memory limits for things like memcache, Java, Node, Postgres, Mysql based on the resource limits given to me.  I could query the k8s API, but that seems very heavy.

**Comment by dchen1107** [comment]
This is discussed in https://github.com/GoogleCloudPlatform/kubernetes/issues/9356#issuecomment-110155706

**Comment by justinsb** [comment]
@dchen1107 - thanks for the link, but I don't think that applies here?  (Unless there's a trick I'm missing, which is not unlikely).  I know I can get the information from the API (via kubectl or curl), I was just hoping for a more direct way.  In my host I have /sys/fs/cgroup/memory/, and apparently this is usually available in Docker containers also, although I don't see it in my Docker k8s containers (on AWS or GCE).

**Comment by bgrant0607** [comment]
We call this "downward API". See also #386. cc @pmorie

**Comment by pmorie** [comment]
@bgrant0607 My bad, I somehow missed being tagged into this.

@justinsb I definitely think this should be available via the downward API.

**Comment by pmorie** [comment]
@justinsb I'm going to take a stab at this today.

**Comment by pmorie** [comment]
@justinsb Let me make sure we're on the same page about what you want before I write code.  It sounds to me like what you're asking for is: if you set the `ResourceRequirements` field of a container, you want to be able to consume that information via the downward API.  Accurate?

**Comment by justinsb** [comment]
@pmorie I think this would be useful for the downwards API.  But: my workaround is to simply list _all_ the pods and match podIP, and get my full pod info that way.  This means that the manifest doesn't require the user to include any additional information (i.e. the downward API mapping).  It's not pretty, and it isn't efficient because we can't currently filter by podIP, but I find it pretty tolerable.

**Comment by pmorie** [comment]
It seems like the biggest challenge to doing this is getting the API right.  Currently, the downward API only supports references to `Pod`-scoped fields, like so:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  restartPolicy: Never
```

With this change we need to expand the scope of the API to container-scoped fields.  There are a couple different facets to consider:

1.  If you're consuming the API in environment variables, it might be natural to have a container-scoped field of the `EnvVarSource`
2.  If you're consuming the API in a volume (see https://github.com/GoogleCloudPlatform/kubernetes/pull/5093, which I hope will be merged soon), the scope in which you specify fields is pod scoped, so if you want to be able to consume resource limits in a volume, we need a way to address a container's resource limits in a `ObjectFieldSelector`

I'm not sure that this value makes a lot of sense to consume in an environment variable.

Any thoughts @smarterclayton @bgrant0607 ?
