### ISSUE TITLE
DELETE API request can delete resource from different API version

### ISSUE THREAD

**Issue by tengqm** [kubernetes/kubernetes#94749]
**What happened**:

I created a `CertificateSigningRequest` in `certificates.k8s.io/v1` as following, named `csr-v1.yaml`:

```yaml
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: testingcsr
spec:
  request: LS0tL...
  signerName: heaven.net/fairy
  usages:
    - client auth
```

and a similar one in the `certificates.k8s.io/v1beta1` group version, named `csr-v1beta1.yaml`.

Then when I tried `kubectl delete -f csr-v1beta1.yaml`. The request is sent via

```
curl -k -v -XGET  -H "Accept: application/json" -H "User-Agent: kubectl/v1.19.0 (linux/amd64) kubernetes/e199641" 'https://10.63.210.224:6443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests?fieldSelector=metadata.name%3Dtestingcsr'
```

And my v1 CSR is deleted!!!

**What you expected to happen**:

My v1 CSR is on a different endpoint. It is never meant to be deleted from the command I issued.

**How to reproduce it (as minimally and precisely as possible)**:

Outlined above.

**Anything else we need to know?**:

I have tried other resources from different API groups. The SAME behavior is observed. You can delete a resource from any API version.
