### ISSUE TITLE
Mounting persistent volume of 1TB fails on nodepool

### ISSUE THREAD

**Issue by mquilling** [kubernetes/kubernetes#94788]
**What happened**:
Creating a AKS cluster nodepool to run cassandra with a 1TB persistent volume works on initial mount.  If the pods are deleted then reinstalled the volume fails to mount with a timeout error.  This **does** work for a 512GB volume

**What you expected to happen**:
Mounting works regardless of size

**How to reproduce it (as minimally and precisely as possible)**:
cassandra.yaml
```
#cassandra.yaml
persistence:
  storageClass: "managed-premium"
  size: 1024Gi
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: agentpool
              operator: In
              values:
                - dbpool
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - cassandra
        topologyKey: "kubernetes.io/hostname"
```
```
export AGENT_POOL_1_NODE_COUNT=6
export DB_POOL_NODE_COUNT=5
export AGENT_POOL_1_NODE_TYPE=Standard_D8_v3
export DB_POOL_NODE_TYPE=Standard_L16s_v2
export RG=test
export CLUSTER_NAME=test
export KUBE_VER=1.18.4
```
```
az aks create --resource-group $RG --name $CLUSTER_NAME --node-count $AGENT_POOL_1_NODE_COUNT \
    --kubernetes-version $KUBE_VER --node-vm-size $AGENT_POOL_1_NODE_TYPE --generate-ssh-keys

az aks nodepool add --resource-group $RG --cluster-name $CLUSTER_NAME --name dbpool --node-vm-size $DB_POOL_NODE_TYPE \
    --kubernetes-version $KUBE_VER --node-count $DB_POOL_NODE_COUNT

az aks get-credentials --resource-group $RG --name $CLUSTER_NAME

brew install helm
helm repo add bitnami https://charts.bitnami.com/bitnami

helm install -f cassandra.yaml cassandra bitnami/cassandra --set cluster.replicaCount=$DB_POOL_NODE_COUNT
```
This should install Cassandra on 5 nodes, then if we wait for pods to be ready, and
```
helm delete cassandra
helm install -f cassandra.yaml cassandra bitnami/cassandra --set cluster.replicaCount=$DB_POOL_NODE_COUNT
```
The volume fails to mount with a timeout, over and over.  512GB **does** work

**Anything else we need to know?**:
There is probably an easier way to repro this issue.  I tried upgrading the VMSS and it got stuck in a upgrading/failed loop and ended up just deleting it

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"8a6cdee2dab2329284444e9448bdf8ab165e1c5c", GitTreeState:"clean", BuildDate:"2020-06-24T18:14:29Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
