### ISSUE TITLE
No access to events if only the API group `events.k8s.io` is specified in a role

### ISSUE THREAD

**Issue by bttger** [kubernetes/kubernetes#94857]
**What happened**: I created a role which should grant access to events. I have only specified the API group `events.k8s.io` because according to the [resource types](https://kubernetes.io/docs/reference/kubectl/overview/#resource-types) this is the right API group to get access to events. The role manifest looked as followed:

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-limited
  namespace: restricted-example
rules:
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["*"]
```

I then associated the Role with the default ServiceAccount of that namespace via RoleBinding. But unfortunately the `kubectl get events` command threw the following error:
```
Error from server (Forbidden): events is forbidden: User "system:serviceaccount:restricted-example:default" cannot list resource "events" in API group "" in the namespace "restricted-example"
```

**What you expected to happen**: To be able to access the events resource type.

**How to reproduce it (as minimally and precisely as possible)**: Create a namespace, the previously defined role and a role binding, like in the following example:
```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: restricted-example
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-limited
  namespace: restricted-example
rules:
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-limited
  namespace: restricted-example
roleRef:
  kind: Role
  name: namespace-limited
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: restricted-example
```
Then create a kubeconfig and run the `kubectl get events` command as the default ServiceAccount of the namespace `restricted-example`.

**Anything else we need to know?**: It's possible to access the events only if specifying the core API group, too (via "" indication). Or by running the `kubectl get events.events.k8s.io` command with the group specified.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-34+1a52fbf0753680", GitCommit:"1a52fbf07536803015220f0a991187db5b42c8ae", GitTreeState:"clean", BuildDate:"2020-09-02T11:33:05Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

and

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-34+1a52fbf0753680", GitCommit:"1a52fbf07536803015220f0a991187db5b42c8ae", GitTreeState:"clean", BuildDate:"2020-09-02T11:33:05Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Single node cluster
- OS (e.g: `cat /etc/os-release`): linux (amd64), Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 4.15.0-117-generic
- Install tools: MicroK8s
- Network plugin and version (if this is a network-related bug):
- Others:
