### ISSUE TITLE
Bug of use clinetset patch namespace

### ISSUE THREAD

**Issue by wenxinnnnn** [kubernetes/kubernetes#94887]
**What happened**:
Initial state:
```
kind: Namespace
apiVersion: v1
metadata:
  name: mynamespace
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
```

Using API patch namespace：
```
patch = `
{
	"metadata": {
		"labels": {
			"test/label": null
		},
		"annotations": {
			"test/annotation": null
		}
	}
}`
_, err := clientSet.CoreV1().Namespaces().Patch(ctx, namespace, types.StrategicMergePatchType, []byte(patch), metav1.PatchOptions{}, "")
```
Results：
```
kind: Namespace
apiVersion: v1
metadata:
  name: mynamespace
  labels:
    test/label: ''
  annotations:
    test/annotation: ''
spec:
  finalizers:
    - kubernetes
status:
  phase: Active

```
**What you expected to happen**:
The result should be the same as the initial value.

**How to reproduce it (as minimally and precisely as possible)**:
use **k8s.io/apimachinery** v0.18.5

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by wenxinnnnn** [comment]
/sig/api-machinery

**Comment by fedebongio** [comment]
/assign @apelisse 
Antoine, could you take a look please?

**Comment by apelisse** [comment]
You can't do that with a strategic merge patch. "null" value won't remove the label.

Maybe I can help, but I need to understand what you're trying to do.

**Comment by wenxinnnnn** [comment]
> You can't do that with a strategic merge patch. "null" value won't remove the label.
> 
> Maybe I can help, but I need to understand what you're trying to do.

The second strategic merge patch I've observed will remove the tag.

**Comment by wenxinnnnn** [comment]
> > You can't do that with a strategic merge patch. "null" value won't remove the label.
> > Maybe I can help, but I need to understand what you're trying to do.
> 
> The second strategic merge patch I've observed will remove the tag.

Initial state:
```
kind: Namespace
apiVersion: v1
metadata:
  name: mynamespace
  labels:
    test/label: ''
  annotations:
    test/annotation: ''
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
```
Using API patch namespace：
```
patch = `
{
	"metadata": {
		"labels": {
			"test/label": null
		},
		"annotations": {
			"test/annotation": null
		}
	}
}`
_, err := clientSet.CoreV1().Namespaces().Patch(ctx, namespace, types.StrategicMergePatchType, []byte(patch), metav1.PatchOptions{}, "")
```
Results：
```
kind: Namespace
apiVersion: v1
metadata:
  name: mynamespace
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
```
