### ISSUE TITLE
MutatingWebhookConfiguration with service on port 8443 ends in no such host 

### ISSUE THREAD

**Issue by nikals99** [kubernetes/kubernetes#94889]
**What happened**:
We tried to register a MutatingWebhookConfiguration with a service running on port 8443. When configured with port 8443 the API-Server fails to resolve the ip of the service:

`W0917 13:36:17.018778 1 dispatcher.go:168] Failed calling webhook, failing open pod-node-selector.k8s.io: failed calling webhook "pod-node-selector.k8s.io": Post https://pod-node-selector.ops.svc:8443/mutate?timeout=5s: dial tcp: lookup pod-node-selector.ops.svc on 127.0.0.1:53: no such host` 

Since API-Server isnt't part of cluster DNS it seems to be odd that the API-Server tries to resolve the DNS name instead of doing another kind of resolution. 

It works just fine when Service and MutatingWebhookConfiguration are configured to use port 443. 

**What you expected to happen**:
MutatingWebhookConfiguration + Service on Port 8443 working instead of it just working when port 443 is used. 

**How to reproduce it (as minimally and precisely as possible)**:
Service with Port 8443:
```
apiVersion: v1
kind: Service
metadata:
  name: pod-node-selector
  namespace: ops
spec:
  clusterIP: XXX.XXX.XXX.XXX
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/instance: pod-node-selector
    app.kubernetes.io/name: pod-node-selector
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
MutatingWebhookConfiguration with port 8443
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-node-selector
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: XXXXXXXXXXXXXX
    service:
      name: pod-node-selector
      namespace: ops
      path: /mutate
      port: 8443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: pod-node-selector.k8s.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - statefulsets
    - statefulsets.apps
    - deployments
    - deployments.apps
    - jobs
    scope: '*'
  sideEffects: None
  timeoutSeconds: 5
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
EKS with managed Nodes
