### ISSUE TITLE
k8s CSR: URI SAN's are not being honored by GKE signer

### ISSUE THREAD

**Issue by shankgan** [kubernetes/kubernetes#95010]
**The problem:**

While testing the K8s CSR API 
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/

I observed that URI SAN's requested in the CSR are never included in the certificate that is generated (under the **X509v3 Subject Alternative Name section**) . Whereas other SAN's (including DNS) requested are added to the certificate.

I am testing some code that needs URI SAN's in the certificate and am blocked on this.

**How to reproduce it (as minimally and precisely as possible)**:
*Create a CSR Request*
If using open-ssl, include both DNS AND URI in a conf file to generate the CSR. 

_Sample CSR Request generated that contains both DNS and URI SAN's_
```
-----BEGIN CERTIFICATE REQUEST-----
MIICpjCCAY4CAQAwCzEJMAcGA1UEChMAMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAtXGOoMjGbugX0xDLwIwlOFrlZdHH522TNskxvwaetgB4xInNYcTh
DywXXC0PVOkS4QZ4m9GJP4wS199FeRBX1jgh1DS0zU7Bq5SBeLorrRZK5o9JZU81
DBT++ouC3I/Ulf/eHZIPkV8CjKzyleIkr/hthtNmv5N9uPByV6gETzyq8L2qm/RA
w0skVHFP+Hv+dD4Mwux/ISFlqlJ037Gw8a/LqappBRFs6zODz7myEi8vbVJfOsIW
8w45ejkZ0izSA5XydCOK2lmdc91EOgDP2N4m1ZA62JKAn/TfQU23tUKCOBbbJLK8
EFctGEZdHN+1nlTPu8M9tZ8dJn5HKPCsgQIDAQABoFYwVAYJKoZIhvcNAQkOMUcw
RTBDBgNVHREBAf8EOTA3hjVzcGlmZmU6Ly9jbHVzdGVyLmxvY2FsL25zL2RlZmF1
bHQvc2EvYm9va2luZm8tZGV0YWlsczANBgkqhkiG9w0BAQsFAAOCAQEAIfYR8wA3
SdL7pgaA3y/vAZ+Nr1luL6FFikjdisH3BLW0BnznJGabOy6n8CZb1ZXG2Z0U6gOV
Dvr25uEtV6HzFq0lfWdAe/3pPHyLgxWhdhrd7V6z8ksp6o5c3K6usYqjMhEFCdSG
lTISI25n1ZVraf6ofNxvbkAc4L5Y/yHpKKWornAFrEuubXT4o61/CKwnkgMV/dBq
pTKbf3s1a662N1LEVlDV1eFM/NgwnGF/1c8bgvf4PQoB+gfed1XyOAZo9Z691+/X
eKQnn4LbvfxSa5JAZ3rHA+GgW5CsWE74ZATqA/+a6YtTog9v34Rokiz4cZ/dEoad
MsVY29J1OFJiig==
-----END CERTIFICATE REQUEST-----
```

**Submit the CSR**

```
cat <<EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: server_csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNwakNDQVk0Q0FRQXdDekVKTUFjR0ExVUVDaE1BTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEENCk1JSUJDZ0tDQVFFQXRYR09vTWpHYnVnWDB4REx3SXdsT0ZybFpkSEg1MjJUTnNreHZ3YWV0Z0I0eEluTlljVGgNCkR5d1hYQzBQVk9rUzRRWjRtOUdKUDR3UzE5OUZlUkJYMWpnaDFEUzB6VTdCcTVTQmVMb3JyUlpLNW85SlpVODENCkRCVCsrb3VDM0kvVWxmL2VIWklQa1Y4Q2pLenlsZUlrci9odGh0Tm12NU45dVBCeVY2Z0VUenlxOEwycW0vUkENCncwc2tWSEZQK0h2K2RENE13dXgvSVNGbHFsSjAzN0d3OGEvTHFhcHBCUkZzNnpPRHo3bXlFaTh2YlZKZk9zSVcNCjh3NDVlamtaMGl6U0E1WHlkQ09LMmxtZGM5MUVPZ0RQMk40bTFaQTYySktBbi9UZlFVMjN0VUtDT0JiYkpMSzgNCkVGY3RHRVpkSE4rMW5sVFB1OE05dFo4ZEpuNUhLUENzZ1FJREFRQUJvRll3VkFZSktvWklodmNOQVFrT01VY3cNClJUQkRCZ05WSFJFQkFmOEVPVEEzaGpWemNHbG1abVU2THk5amJIVnpkR1Z5TG14dlkyRnNMMjV6TDJSbFptRjENCmJIUXZjMkV2WW05dmEybHVabTh0WkdWMFlXbHNjekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBSWZZUjh3QTMNClNkTDdwZ2FBM3kvdkFaK05yMWx1TDZGRmlramRpc0gzQkxXMEJuem5KR2FiT3k2bjhDWmIxWlhHMlowVTZnT1YNCkR2cjI1dUV0VjZIekZxMGxmV2RBZS8zcFBIeUxneFdoZGhyZDdWNno4a3NwNm81YzNLNnVzWXFqTWhFRkNkU0cNCmxUSVNJMjVuMVpWcmFmNm9mTnh2YmtBYzRMNVkveUhwS0tXb3JuQUZyRXV1YlhUNG82MS9DS3dua2dNVi9kQnENCnBUS2JmM3MxYTY2Mk4xTEVWbERWMWVGTS9OZ3duR0YvMWM4Ymd2ZjRQUW9CK2dmZWQxWHlPQVpvOVo2OTErL1gNCmVLUW5uNExidmZ4U2E1SkFaM3JIQStHZ1c1Q3NXRTc0WkFUcUEvK2E2WXRUb2c5djM0Um9raXo0Y1ovZEVvYWQNCk1zVlkyOUoxT0ZKaWlnPT0NCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQ==
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
```

Note that request is the base64 encoding of the CSR generated earlier

** Approve the CSR and request the content of the signed CSR **
```
kubectl certificate approve server_csr
kubectl get csr server_csr -o jsonpath='{.status.certificate}' | base64 -d > server.crt 
```

Note that server.crt does not contain the URI SAN's but DOES contain the DNS SAN's

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.6-gke.3504", GitCommit:"ebdafa7ed3984f94e1ab914221bf04b62a5cd1b8", GitTreeState:"clean", BuildDate:"2020-09-09T02:49:12Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

_Note that the same issue was also observed on GKE 1.16.13 as well_

- Cloud provider or hardware configuration: GKE
- OS (Client OS): MAC-OS-X

**Anything else you should know**
I did see that earlier in earlier versions of k8s (upto 1.17.x), there was dependency from the certificate controller on older version of cfssl which did not encode URI SANS. Refer - https://github.com/cloudflare/cfssl/issues/921
Wondering if the same problem still persists.
