### ISSUE TITLE
Cannot create an external load balancer with mix protocols (TCP/UDP)

### ISSUE THREAD

**Issue by cedricroijakkers** [kubernetes/kubernetes#95029]
This issue has been opened a few times before. The basic problem is, that I have an application that needs to listen of a set of TCP ports on a public load balancer (80, 443, and 4443) and one UDP port on the same load balancer (10000).

I'm running on Azure AKS, with k8s version 1.19.0. The problem was that the Azure load balancer supports mixed protocols, it basically adds a forward rule on all TCP and all UDP ports, for both protocols. In this case, this results in TCP and UDP forwarding rules on ports 80/443/4443/10000 while I only need TCP on 80/443/4443 and UDP on 10000, but this is no big issue. Better have too many forwarding rules than not enough.

Either way, as described in PR https://github.com/kubernetes/enhancements/pull/1438 , there was still a wrong check in the k8s code that did not allow this in kube-proxy. This has been fixed in aforementioned PR, merged into master, and is part of the 1.19 milestone.

So I've updated to 1.19.0, tried to apply my LoadBalancer service, but sadly no dice.

I have a deployment listening on ports 80/443/4443 on TCP and 10000 on UDP, and created the following service manifest:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: testjitsi-web-jvb
  namespace: testjitsi
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: mc_qah-ci-k8s-nonprod_qah-ci-k8s-nonprod_westeurope
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
spec:
  selector:
    name: testjitsi-web-jvb
  type: LoadBalancer
  loadBalancerIP: X.X.X.X
  clusterIP: Y.Y.Y.Y
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: tcpfallback
    port: 4443
    protocol: TCP
    targetPort: 4443
  - name: udpvideo
    port: 10000
    protocol: TCP
    # protocol: UDP
    targetPort: 10000
```

When trying to apply, I get the following error:

```
The Service "testjitsi-web-jvb" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"http", Protocol:"TCP", AppProtocol:(*string)(nil), Port:80, TargetPort:intstr.IntOrString{Type:0, IntVal:80, StrVal:""}, NodePort:32697}, core.ServicePort{Name:"https", Protocol:"TCP", AppProtocol:(*string)(nil), Port:443, TargetPort:intstr.IntOrString{Type:0, IntVal:443, StrVal:""}, NodePort:30270}, core.ServicePort{Name:"tcpfallback", Protocol:"TCP", AppProtocol:(*string)(nil), Port:4443, TargetPort:intstr.IntOrString{Type:0, IntVal:4443, StrVal:""}, NodePort:31077}, core.ServicePort{Name:"udpvideo", Protocol:"UDP", AppProtocol:(*string)(nil), Port:10000, TargetPort:intstr.IntOrString{Type:0, IntVal:10000, StrVal:""}, NodePort:32016}}: cannot create an external load balancer with mix protocols
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.0
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.7 LTS
- Kernel (e.g. `uname -a`): 4.15.0-1093-azure
- Install tools: AKS-managed
- Network plugin and version (if this is a network-related bug): AKS-managed Kube-net
- Others: N/A
