### ISSUE TITLE
precondition check failure for CRDs

### ISSUE THREAD

**Issue by nan-yu** [kubernetes/kubernetes#95050]
**What happened**:

The API server returned the following error when applying the custom resources on a Kubernetes cluster (1.15.12) :
```
precondition failed for: map[apiVersion:marketplace.com/v1]

namespace: videostore
metadata.name: vidrent
group: marketplace.com
version: v1
kind: WebStore
```

**What you expected to happen**:

The object to be applied successfully

**How to reproduce it (as minimally and precisely as possible)**:

I was using Config Sync to automatically apply the resource. I'm not sure how to check the API server errors if applying the resource directly.
Here are the steps to reproduce it:
1. Install Config Sync on a GKE cluster (1.15.12): https://cloud.google.com/anthos-config-management/docs/how-to/installing#deploying
2. Use an SSH key pair for authentication
3. Create a config-management object (config-mangement.yaml)
```
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: csmr-test-15
  enableLegacyFields: true
  enableMultiRepo: true
  git:
    policyDir: root-flat
    proxy: {}
    secretType: ssh
    syncBranch: master
    syncRepo: https://github.com/ekitson/csmr-sample
  sourceFormat: unstructured
```
4. Run `kubectl apply -f config-management.yaml`
5. Check the log to see the error

**Anything else we need to know?**:

**Environment**: GKE stable release
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.20", GitCommit:"0ac5f81eecab42bff5ef74f18b99d8896ba7b89b", GitTreeState:"clean", BuildDate:"2020-09-09T00:48:20Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCP
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
