### ISSUE TITLE
HorizontalPodAutoscaler: Prevent Scale Down based on a separate metric

### ISSUE THREAD

**Issue by WilliamABradley** [kubernetes/kubernetes#95051]
**What would you like to be added**:

Ability to prevent down scaling based on a Condition, this is a feature that is supported in AWS ASGs where you can define a downscale condition.

It could look something like:

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: buildkite-agent-scaler
spec:
  minReplicas: 2
  maxReplicas: 8

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: buildkite-agent

  metrics:
    - type: External
      external:
        metric:
          name: scheduledJobs
        target:
          type: Value
          value: 1

  behavior:
    scaleDown:
      if:
      - type: External
        external:
          metric:
            name: activeJobs
        value: 0
        periodSeconds: 60
```

This would mean: _Scale down if **activeJobs** has been 0 for 60 seconds_

If this is achievable in the upcoming 1.18 release, let me know :)

**Why is this needed**:

I am using a Horizontal Pod Autoscaler to autoscale Devops Agents (For Buildkite). It is upscaling properly using external metrics, however, when it downscales, it tends to kill currently running pods, which isn't great for a devops pipeline, especially for long running tasks, or a Terraform apply.
