### ISSUE TITLE
mysql local persistent volume not working on windows - MountVolume.NewMounter initialization failed for volume "mysql-pv-volume" : path "c:\\mysql-volume" does not exist

### ISSUE THREAD

**Issue by Narayami** [kubernetes/kubernetes#95067]
Hello!

I'm having some problems trying to create a local persistent volume in windows 10.

I was seeing this: https://github.com/kubernetes/kubernetes/issues/73332
And found this: https://github.com/andyzhangx/demo/blob/master/windows/local/pv-local.yaml

But 1-I don't know what is the meaning of "after path translation", and 2-if I try using <``> in the path, I get an error: error parsing .\mysql-pv.yaml: error converting YAML to JSON: yaml: line 20: found character that cannot start any token

I searched and tried a lot of things, but with no success.

here are my yaml's:

mysql-pv.yaml:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
    app: mysql
spec:
  claimRef:
    namespace: default
    name: mysql-pv-claim
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  local:
    path: "c:\\mysql-volume"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
  #hostPath:
   # path: "C:\\mysql-volume"
    #type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    type: local
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      type: local
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```

mysql-deployment.yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - protocol: TCP
    port: 3306
    nodePort: 30001
  selector:        
    app: mysql
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: mysql
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
```
If I edit persistent volume in the dashboard, I can see that the path is ok:
```
  local:
    path: 'c:\mysql-volume'
```
I need this, so when I restart my computer, the databases I create on mysql are still there.

Note: I think I found some bug too, If instead of the local path If I just leave the hostPath and apply, everything is ok, but of course, not persisting, but if after that, I comment the hostPath and uncomment the local path, it doesn't give me the "MountVolume.NewMounter initialization failed for volume "mysql-pv-volume" : path "C:\\mysql-volume" does not exist" but not persisting again and if I remove the deployment, the pv and pvc and apply again, the error appears...

thank you for your time. I don't know what to do anymore.
