### ISSUE TITLE
Adding tag annotations on service manifest for NLB does not trigger update on AWS 

### ISSUE THREAD

**Issue by hiroyuki-kamei** [kubernetes/kubernetes#95106]
**BUG REPORT**:

/kind bug
/sig cloud-provider
/area provider/aws

**What happened**:

_Similar to https://github.com/kubernetes/kubernetes/issues/54642_

Adding this annotation to an existing service: {"metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags":"env=dev"}}} did not trigger an update on AWS NLB (no new tags).

Here is the manifest.
```
kind: Service
apiVersion: v1
metadata:
  name: nlb-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "env=dev"   # Add this annotation
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
```

**What you expected to happen**:

Expected to new tags under the existing NLB: env=dev

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a service without annotation
2. Add the annotation {"metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags":"env=dev"}}}
3. No tags on AWS NLB

**Anything else we need to know?**:

Creating a new service WITH the annotation will create the expected tags on AWS.

**Environment**:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): EKS managed node group. Node AMI Type: AL2_x86_64
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
