### ISSUE TITLE
apiVersion "networking.k8s.io/v1" not supported for "ingress" object in k8s 1.19.1

### ISSUE THREAD

**Issue by fjammes** [kubernetes/kubernetes#95100]
**What happened**:

On k8s v1.19.1, I created an ingress using yaml below:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```
And it created an ingress object based on deprecated apiVersion `extensions/v1beta1`

**What you expected to happen**:

The ingress object should be based on apiVersion `networking.k8s.io/v1`

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl apply -f <above-yaml-file>.yaml
kubectl get ingress minimal-ingress -o yaml | grep apiVersion
apiVersion: extensions/v1beta1
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/rewrite-target":"/"},"name":"minimal-ingress","namespace":"default"},"spec":{"rules":[{"http":{"paths":[{"backend":{"service":{"name":"test","port":{"number":80}}},"path":"/testpath","pathType":"Prefix"}]}}]}}
  - apiVersion: networking.k8s.io/v1
```

**Anything else we need to know?**:

My cluster is based on `kind 0.9.0`

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

Linux-based laptop with 32 GB of memory

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):

Linux clrinfoport18 4.15.0-1097-oem #107-Ubuntu SMP Wed Sep 9 12:29:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

kind-0.ç.0

- Network plugin and version (if this is a network-related bug):

kindnet

- Others:
