### ISSUE TITLE
Svc with specific name affects the running of a pod

### ISSUE THREAD

**Issue by windayski** [kubernetes/kubernetes#95141]
**What happened**:
I created a svc named ckeadm-wait, and a pod run ckeadm (a binary file) with its sub command 'wait'. 

service:
```
root@mgt01:~/wz/ckeadm# cat svc.yaml 
apiVersion: v1
kind: Service
metadata:
  name: ckeadm-wait
spec:
  selector: 
    app: ckeadm-wait
  type: NodePort
  ports:
    - port: 2376
      targetPort: 2376
```

deployment:
```
root@mgt01:~/wz/ckeadm# cat ckeadm-wait.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ckeadm-wait
  name: ckeadm-wait
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckeadm-wait
  template:
    metadata:
      name: ckeadm-wait
      labels:
        app: ckeadm-wait
    spec:
      containers:
      - command: ["/ckeadm"]
        args:
        - wait
        - --port=2376
        - --address=0.0.0.0
        image: cke-admin-amd64:test
        imagePullPolicy: IfNotPresent
        name: ckeadm-wait
        ports:
        - name: log
          containerPort: 2376
      restartPolicy: Always
```

The creation of svc is successful but the deploy failed.
```
root@mgt01:~/wz/ckeadm# kubectl get svc -n kube-system |grep ckeadm
ckeadm-wait     NodePort    100.105.61.240   <none>        2376:32543/TCP           90s
```

```
root@mgt01:~/wz/ckeadm# kubectl get pod -n kube-system |grep ckeadm
ckeadm-wait-6885dc68d8-lsn9m               0/1     Error              0          8s
```

See the log of the pod
```
root@mgt01:~/wz/ckeadm# kubectl logs -n kube-system ckeadm-wait-6885dc68d8-lsn9m -f 
Incorrect Usage: could not parse tcp://100.105.61.240:2376 as int value for flag port: strconv.ParseInt: parsing "tcp://100.105.61.240:2376": invalid syntax

NAME:
   ckeadm wait - Bring the cluster wait for information

USAGE:
   ckeadm wait [command options] [arguments...]
...
```

It's quite strange. It seems to be kubernetes add an invalid args `port=tcp://100.105.61.240:2376` which is the svc ClusterIP and port to the pod command.

When changed the name of the svc,  and recreate the svc and the pod, both of them success. 

Why?

It looks like a svc named ckeadm-wait affects a pod run ckeadm wait command. Change the svc name can solve this problem.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.3
