### ISSUE TITLE
startupProbe readiness state update issues

### ISSUE THREAD

**Issue by Haar** [kubernetes/kubernetes#95140]
**What happened**:

Creating a pod that has a startupProbe and no readinessProbe does not report as `ready` on entering a `running` state, it instead seems to wait for a separate event loop to trigger updating to a `ready` state. 

**What you expected to happen**:

Creating a pod that has no readinessProbe should report as `ready` as soon as it is `running`.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the file `some.yaml` below with `kubectl apply -f some.yaml`:

```
# some.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: startup-without-readiness
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["tail"]
    args: ["-f", "/dev/null"]
    resources:
      requests:
        cpu: "100m"
        memory: "10Mi"
      limits:
        cpu: "100m"
        memory: "10Mi"
    startupProbe:
      exec:
        command:
        - "true"
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
---
apiVersion: v1
kind: Pod
metadata:
  name: startup-with-readiness
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["tail"]
    args: ["-f", "/dev/null"]
    resources:
      requests:
        cpu: "100m"
        memory: "10Mi"
      limits:
        cpu: "100m"
        memory: "10Mi"
    startupProbe:
      exec:
        command:
        - "true"
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      exec:
        command:
        - "true"
      periodSeconds: 5
```

This consistently results in (via `kubectl get pods -w`, with minor variances in timings):

```
startup-without-readiness   0/1     ContainerCreating   0          0s
startup-with-readiness      0/1     ContainerCreating   0          0s
startup-without-readiness   0/1     ContainerCreating   0          1s
startup-with-readiness      0/1     ContainerCreating   0          1s
startup-without-readiness   0/1     Running             0          3s
startup-with-readiness      0/1     Running             0          4s
startup-without-readiness   0/1     Running             0          6s
startup-with-readiness      0/1     Running             0          7s
startup-with-readiness      1/1     Running             0          10s
startup-without-readiness   1/1     Running             0          88s
```

**Anything else we need to know?**:

Creating a pod with an "noop" readinessProbe in addition to the startupProbe causes the readiness state to update quickly, though should not be required.

I think it is potentially off the back of or is related to https://github.com/kubernetes/kubernetes/pull/92196

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider: AWS non-EKS & on-prem
- OS: Fedora CoreOS 32.20200824.3.0
- Kernel: 5.7.16-200.fc32.x86_64
