### ISSUE TITLE
Liveness/Readiness Health Check sometimes failed

### ISSUE THREAD

**Issue by winds6206** [kubernetes/kubernetes#95165]
## What happened:

I have a deployment(replica 6) with Nginx container, then I use Liveness/Readiness Probe, it's working fine.
But sometimes, 6 pods will Liveness/Readiness get unhealth at the same time. 

I have encounter this problem on GKE1.14 & 1.15

```
Liveness probe failed: Get http://10.28.6.19:80/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Readiness probe failed: Get http://10.28.6.19:80/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

How to fix?  I try to deleted the pod, the pod will be fine. 
This problem is like this issue [#89898](https://github.com/kubernetes/kubernetes/issues/89898)

Here is my YAML paragraph
```
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 2
```

Anyone can help thies issue?  
Thanks a lot!

## What you expected to happen:
Successful Readiness/Liveness Probe.

## How to reproduce it (as minimally and precisely as possible):
Can't reproduce, because it will random happen

## Environment:

GKE: 1.15.11-gke.15
