### ISSUE TITLE
controller-manager is throttled by the api-server even when it is excempt via flowcontrol

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#95212]
in the controller-manager logs I can see lots of:
```
request.go:645] Throttling request took 2.098229162s, request: GET:http://127.0.0.1:8080/apis/
```
I checked the audit logs to make sure it has group `system:masters` and that also matches the `excempt` flowschema
```
spec:
  matchingPrecedence: 1
  priorityLevelConfiguration:
    name: exempt
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - group:
        name: system:masters
      kind: Group
```

so I don't understand why it is being throttled (flowschemas works fine for other things in our clusters)

also idk how I would even start debugging that since I cannot see which flowschema (if any) it ends up using
