### ISSUE TITLE
Wrong psp assigned to single pod

### ISSUE THREAD

**Issue by a-b-v** [kubernetes/kubernetes#95249]
**What happened:**
During add a pod from manifest or with "kubectl run" in cluster with psp enabled, pod assigned to wrong psp with allowPrivilegeEscalation: true.

**What you expected to happen:**
Will be assigned psp for system:authenticated group

**How to reproduce it (as minimally and precisely as possible):**
- Enable psp in cluster
- assign psp with next spec to system:authenticated group
```
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - CHOWN
  - DAC_OVERRIDE
  - FSETID
  - FOWNER
  - MKNOD
  - NET_RAW
  - SETGID
  - SETUID
  - SETFCAP
  - SETPCAP
  - NET_BIND_SERVICE
  - SYS_CHROOT
  - KILL
  - AUDIT_WRITE
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
  - awsElasticBlockStore
  - azureDisk
  - azureFile
  - cephFS
  - cinder
  - csi
  - fc
  - flexVolume
  - flocker
  - gcePersistentDisk
  - gitRepo
  - glusterfs
  - iscsi
  - nfs
  - photonPersistentDisk
  - portworxVolume
  - quobyte
  - rbd
  - scaleIO
  - storageos
  - vsphereVolume
```
- create privileged psp with next spec:
```
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - SYS_ADMIN
  allowedHostPaths:
  - pathPrefix: /dev
  - pathPrefix: /run/mount
  - pathPrefix: /sys
  - pathPrefix: /lib/modules
    readOnly: true
  - pathPrefix: /var/lib/kubelet/pods
  - pathPrefix: /var/lib/kubelet/plugins/cephfs.csi.ceph.com
  - pathPrefix: /var/lib/kubelet/plugins_registry
  - pathPrefix: /var/lib/kubelet/plugins
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  hostPID: true
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - hostPath
```
- Apply next manifest with cluster admin sa
```
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: php-apache
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: php-apache
  name: php-apache
spec:
  containers:
  - image: gcr.io/google_containers/hpa-example
    name: php-apache
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 500m
        memory: 500M
  dnsPolicy: ClusterFirst
  restartPolicy: Always
```
- describe pod, in annotation will be
```
metadata:
    annotations:
      kubernetes.io/psp: name_of_privileged_psp
```

**Environment:**
Kubernetes version (use kubectl version)

---
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
