### ISSUE TITLE
Conntrack table not flushed for UDP hostPort when pod deleted

### ISSUE THREAD

**Issue by kinghrothgar** [kubernetes/kubernetes#95258]
**What happened**:
Restart daemonset with UDP hostPort. All UDP traffic to new ds pods from existing pods fails. Flushing conntrack table fixes it. I saw this issue with 1.14 and it seems to be the exact same issue as here https://github.com/kubernetes/kubernetes/issues/66651. It was fixed in 1.15 and now I'm seeing it again in 1.16.

**What you expected to happen**:
hostPorts to work across Pod restarts

**How to reproduce it (as minimally and precisely as possible)**:
Restart daemonset with UDP hostPort. UDP traffic to new pod does not work.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
GKE
- OS (e.g: `cat /etc/os-release`):
COS
- Kernel (e.g. `uname -a`):
Linux 4.19.112+ #1 SMP Fri Sep 4 12:00:04 PDT 2020 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
Vanilla GKE
- Others:

**Comment by aojea** [comment]
@kinghrothgar just to confirm, you are referring to container hostPort only, right? no Service NodePorts.

```
kind: Pod
apiVersion: v1
metadata:
  name: udp
  labels:
    app: udp-app
spec:
  containers:
  - name: container
    image: reg/udpdaemon:1.0
    ports:
    - name: udp
      hostPort: 55555
      containerPort: 80      
      protocol: UDP
```
