### ISSUE TITLE
Pod stuck Terminating after adding new mount on the host path

### ISSUE THREAD

**Issue by trtt** [kubernetes/kubernetes#95310]
/kind bug

**What happened**:
Pod is stuck on Terminating.

**What you expected to happen**:
Pod to terminate cleanly.

**How to reproduce it (as minimally and precisely as possible)**:
1. Make dir to be mounted into container (on the node):
```sh
mkdir /tmp/test
```

2. pod.yaml (image is not important, volume/mounts are):
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /host/tmp/test
        subPath: tmp/test
        name: host-root
  volumes:
    - name: host-root
      hostPath:
        path: /
```
```kubectl create -f pod.yaml```

3. When the pod is started, mount additional fs on the host path (on the node):
```sh
mkdir /tmp/test/newmount
mount -t tmpfs -o size=8m tmpfs /tmp/test/newmount
```

4. Delete Pod:
```sh
kubectl delete pod nginx
```

5. Well, it should be stuck.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.1.290+086b65a0009112-dirty", GitCommit:"086b65a0009112223647f6be2d3b589bffc36759", GitTreeState:"dirty", BuildDate:"2020-10-05T16:07:29Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
  initially tested on 1.17
- Others: systemd as init system (since it ships with shared bind mounts by default)

---

While looking into the problem I tested some changes to fix the issue. I can prepare PR, let me know if it's needed.
