### ISSUE TITLE
Provide a way to perform offline CRD schema validation

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#95407]
**What would you like to be added**:

I have been trying to get an offline CR schema validation working for a couple of weeks now. I have tried many many different ways to do so, and nothing I do matches the API server

Specifically, I would like something along the lines of `ValidateCR(customResourceDefinition, customResource) error`, where the `error` returned will exactly match the result had I applied the CRD and CR against a live api server.

**Why is this needed**:

For testing. We want to validate all of our examples we provide, as well as inputs and outputs of tests to ensure they are all valid. We may also enhance some of our tooling to early-detect invalid resources.

**More info**:

The obvious approach is to use validation.ValidateCustomResource from the apiextensions-apiserver. However, this behavior does not match the behavior in a live cluster. Specifically, when we have array types, if the field is not set in the YAML it will be rejected by `ValidateCustomResource` but allowed in a live cluster.

This can be shown from this PR: 
https://github.com/kubernetes/apiextensions-apiserver/compare/master...howardjohn:test-nullable-array?expand=1

This will give us the error `unexpected validation error for map[field:<nil>]: [field: Invalid value: "null": field in body must be of type array: "null"]`. Applying the same CRD/CR to the cluster:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  name: gateways.networking.istio.io
spec:
  group: networking.istio.io
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    shortNames:
    - gw
    singular: gateway
  scope: Namespaced
  versions:
  - name: v1alpha3
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              servers:
                items:
                  format: string
                  type: string
                nullable: false
                type: array
    served: true
    storage: true
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio
spec:
  servers: ["foo"]
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio
spec: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio
spec:
  servers: []
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio
spec:
  servers: ~
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio
spec:
  servers: [123]
```

You will see all of the CR except the last one pass (the last one fails due to ints in a string list, as expected).

After realizing this was not working out I went down a rabbit hole of trying every combination I could find, creating structural schemas, etc and tried various things here:

https://github.com/istio/istio/blob/aacdfb1866d1e5d5551c99631b04919553f57c48/pkg/config/crd/validator.go#L65

Every option either did not validate enough things (missed invalid configs) or has this nullable issue. Interestingly, I tried copying exactly what `kubectl` is doing: https://github.com/istio/istio/blob/aacdfb1866d1e5d5551c99631b04919553f57c48/pkg/config/crd/validator.go#L105-L135

and it is missing validation (specifically of Enum types). In real usage of kubectl this manifests as passing the early offline validation but then failing on the real `.Create()` call
