### ISSUE TITLE
Allow passing parameters as part of probe requests

### ISSUE THREAD

**Issue by mwhipple** [kubernetes/kubernetes#95403]
(half-baked idea)

**What would you like to be added**:

When defining readiness and liveness probes it could be very helpful to be able to relay in the probe request. This could include replica set information such as the number of active/healthy nodes (or potentially a condensed digest of probe responses). This could be supported by allowing for some dynamically expanded values within the probes such as:

```yaml
  httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: X-Health-Siblings
          value: {{.RSStatus.Healthy}}
        - name: X-Total-Siblings
          value: {{.RSStatus.Size}}
```

**Why is this needed**:

When wiring probes there's often a balancing act between determining the health of an individual node vs. that of the cluster as a whole where any node-specific degradation could ideally be handled without any inadvertently aggravating the problem if the degradation is widespread. The above could offer a potentially simple way to provide developers with some rope.
