### ISSUE TITLE
Pods with a startup probe but without a readiness probe take a long time to become ready

### ISSUE THREAD

**Issue by OvervCW** [kubernetes/kubernetes#95436]
**What happened**:

I created the following deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /?liveness
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /?startup
            port: 80
          failureThreshold: 12
          periodSeconds: 10
```

Both the startup probe and liveness probes succeeded almost immediately after the pod was created, but despite this, it took ~80 seconds for the pod to change its state to Ready. The following requests were made during those 80 seconds:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
10.244.10.1 - - [09/Oct/2020:10:59:18 +0000] "GET /?startup HTTP/1.1" 200 612 "-" "kube-probe/1.18" "-"
10.244.10.1 - - [09/Oct/2020:10:59:27 +0000] "GET /?liveness HTTP/1.1" 200 612 "-" "kube-probe/1.18" "-"
10.244.10.1 - - [09/Oct/2020:10:59:37 +0000] "GET /?liveness HTTP/1.1" 200 612 "-" "kube-probe/1.18" "-"
10.244.10.1 - - [09/Oct/2020:10:59:47 +0000] "GET /?liveness HTTP/1.1" 200 612 "-" "kube-probe/1.18" "-"
10.244.10.1 - - [09/Oct/2020:10:59:57 +0000] "GET /?liveness HTTP/1.1" 200 612 "-" "kube-probe/1.18" "-"
10.244.10.1 - - [09/Oct/2020:11:00:07 +0000] "GET /?liveness HTTP/1.1" 200 612 "-" "kube-probe/1.18" "-"
10.244.10.1 - - [09/Oct/2020:11:00:17 +0000] "GET /?liveness HTTP/1.1" 200 612 "-" "kube-probe/1.18" "-"
10.244.10.1 - - [09/Oct/2020:11:00:27 +0000] "GET /?liveness HTTP/1.1" 200 612 "-" "kube-probe/1.18" "-"
10.244.10.1 - - [09/Oct/2020:11:00:37 +0000] "GET /?liveness HTTP/1.1" 200 612 "-" "kube-probe/1.18" "-"
```

**What you expected to happen**:

I expected the pod to become ready after about 10 seconds.

**How to reproduce it (as minimally and precisely as possible)**:

See the deployment above.

**Anything else we need to know?**:

If I remove the startup probe or extend the deployment with a readiness probe (parameters identical to liveness probe), then the pod *does* become ready within 10 seconds.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.8
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): -
- Kernel (e.g. `uname -a`): -
- Install tools: -
- Network plugin and version (if this is a network-related bug): -
- Others: -
