### ISSUE TITLE
Number of Job retires is different for restartPolicy of OnFailure and Never

### ISSUE THREAD

**Issue by yodarshafrir1** [kubernetes/kubernetes#95433]
**What happened**:
Submitting a job with the same value of `backoffLimit` (as long as `backoffLimit` > 0) will cause different number of retries with different values of `restartPolicy`.
For `restartPolicy=Never` the number of retires is equal to `backoffLimit`. 
For `restartPolicy=OnFailure` the number of retires is equal to `backoffLimit-1`.

**What you expected to happen**:
Both policies should have the same number of retires for the same `restartPolicy`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a job with `restartPolicy=OnFailure` with the following .yaml file:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-1
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["bash", "-c"]
        args:
        - sleep 300 && command-that-doesnt-exist
      restartPolicy: OnFailure
```

After 5 minutes the job will have the following status:

```
status:
    conditions:
    - lastProbeTime: "2020-10-09T08:14:47Z"
      lastTransitionTime: "2020-10-09T08:14:47Z"
      message: Job has reached the specified backoff limit
      reason: BackoffLimitExceeded
      status: "True"
      type: Failed
    startTime: "2020-10-09T08:09:41Z" 
```

According to the `startTime` and `lastTransitionTime` that the job had failed after ~5 minutes, the pod was deleted after 5 minutes.

2. Create a job with `restartPolicy=Never` with the following .yaml file:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-2
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["bash", "-c"]
        args:
        - sleep 300 && command-that-doesnt-exist
      restartPolicy: Never

```
After 10 minutes the job will have the following status:

```
- lastProbeTime: "2020-10-09T08:18:45Z"
    lastTransitionTime: "2020-10-09T08:18:45Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 2
  startTime: "2020-10-09T08:08:18Z"
```

According to the `startTime` and `lastTransitionTime` that the job had failed after ~10 minutes, 2 pods were created and deleted during the 10 minutes).

**Anything else we need to know?**:
This was tested with the fix of: https://github.com/kubernetes/kubernetes/pull/93779 so the number of failures for `restartPolicy=Never` is stable.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.8
