### ISSUE TITLE
Exposing a service as Loadbalancer or NodePort does not work if SessionAffinity is configured (on Docker for Windows)

### ISSUE THREAD

**Issue by MartinKirchner** [kubernetes/kubernetes#95484]
**What happened**:
On Docker for Windows with activated Kubernetes I defined a deployment with a replica set of 5 and a matching service of type `LoadBalancer` (or `NodePort`). The service configures a `SessionAffinity`.
Curl fails with `curl: (52) Empty reply from server`

**What you expected to happen**:

- Service is exposed
- `curl localhost:8080` should return "Hello Kubernetes!"

**How to reproduce it (as minimally and precisely as possible)**:
_reproduceNodePortBug.yaml_
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world
        ports:
        - containerPort: 8080

---
        
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: my-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - targetPort: 8080
    port: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: load-balancer-example
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
  type: LoadBalancer
```

```
$ kubectl -n exposeservice apply -f reproduceNodePortBug.yaml
$ kubectl -n exposeservice get po,svc,ep -owide
NAME                               READY   STATUS    RESTARTS   AGE   IP          NODE             NOMINATED NODE   READINESS GATES
pod/hello-world-7677cdf8dd-4fqmn   1/1     Running   0          31s   10.1.1.73   docker-desktop   <none>           <none>
pod/hello-world-7677cdf8dd-fbwtk   1/1     Running   0          31s   10.1.1.77   docker-desktop   <none>           <none>
pod/hello-world-7677cdf8dd-gqjzl   1/1     Running   0          31s   10.1.1.75   docker-desktop   <none>           <none>
pod/hello-world-7677cdf8dd-gt5fc   1/1     Running   0          31s   10.1.1.74   docker-desktop   <none>           <none>
pod/hello-world-7677cdf8dd-pztdt   1/1     Running   0          31s   10.1.1.76   docker-desktop   <none>           <none>

NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE   SELECTOR
service/my-service   LoadBalancer   10.101.99.16   localhost     8080:30471/TCP   31s   app.kubernetes.io/name=load-balancer-example

NAME                   ENDPOINTS                                                  AGE
endpoints/my-service   10.1.1.73:8080,10.1.1.74:8080,10.1.1.75:8080 + 2 more...   31s

$ curl localhost:8080
curl: (52) Empty reply from server
```

**Anything else we need to know?**:
If I remove this block everything works fine (except that I do not have session affinity):
```
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Docker for Windows 19.03.13
- OS (e.g: `cat /etc/os-release`): Windows 10 2004
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

On Ubuntu 18.04 and Kubernetes v1.19.2 the problem does not exist.
