### ISSUE TITLE
cronJob without restartPolicy results in an invalid restartPolicy: Always

### ISSUE THREAD

**Issue by wilmardo** [kubernetes/kubernetes#95490]
**What happened**:
Deployed an cronJob with an empty `restartPolicy` and it defaulted to `Always` which is an invalid option:
```
spec.jobTemplate.spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: "OnFailure", "Never"
```
Leaving the key out completely has the same result

**What you expected to happen**:
The empty key to default to something valid like `OnFailure` or `Never`. Also document what this default is, my proposal would be to have `Never` as default since some tasks can't be reran easily. But it might be nice to force `OnFailure` as default to enforce the stateless mindset even for crons :)

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: simple-args
              image: "alpine:3.11"
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy:  # can be removed to give the same result
```
**Anything else we need to know?**:

I guess not but I am open for questions :)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.2
