### ISSUE TITLE
MutatingWebhook v1 admissionregistration.k8s.io field failurePolicy not defaulting to Fail

### ISSUE THREAD

**Issue by tarquin-the-brave** [kubernetes/kubernetes#95545]
**What happened**:

I configured a mutating webhook like so:

```yaml
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector
webhooks:
  - name: graviton.sidecar.injector.proto
    admissionReviewVersions: [v1]
    clientConfig:
      service:
        name: sidecar-inject
        namespace: default
        path: /sidecar-inject
    rules:
      - operations: [CREATE]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: [pods]
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled
    sideEffects: None
```

and labelled the default namespace accordingly:

```yaml
$ kubectl describe namespace default
Name:         default
Labels:       sidecar-injector=enabled
Annotations:  <none>
Status:       Active

No resource quota.

No LimitRange resource.
```

I didn't setup anything to server the webhook.

**What you expected to happen**:

WIthout anything to serve the webhook I expected any attempt to create a Pod in the `default` namespace to fail.

The `failurePolicy` field [is documented][doc] as being defaulted to `Fail`.

[doc]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#mutatingwebhook-v1-admissionregistration-k8s-io

**How to reproduce it (as minimally and precisely as possible)**:

Install the above webhook configuration and provide a namespace of your choice the `sidecar-injector: enabled` label.

Attempt to crate a Pod in that namespace.

**Anything else we need to know?**:

Setting `failurePolicy: Fail` in the webhook explicitly brought about the expected behaviour. 

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-14T00:06:38Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: Azure AKS
