### ISSUE TITLE
error: deployment "xxx" exceeded its progress deadline and RolloutStatusTimedout

### ISSUE THREAD

**Issue by ceteongvanness** [kubernetes/kubernetes#95550]
I am new to the kubernetes, may I know which one I should add on or other things?
**Which jobs are failing**:
azure/k8s-deploy@v1.2

**Which test(s) are failing**:
Deployment

**Since when has it been failing**:
After first time of the deployment it fail

```
strategy:  none
/usr/bin/kubectl apply -f /tmp/Deployment_scoutasiacluster-dbd1_1602667425570,/tmp/Service_scoutasiacluster-dbd1_1602667425571 --namespace scoutasiacluster8fce
deployment.apps/scoutasiacluster-dbd1 configured
service/scoutasiacluster-dbd1 unchanged
/usr/bin/kubectl rollout status Deployment/scoutasiacluster-dbd1 --namespace scoutasiacluster8fce
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 out of 2 new replicas have been updated...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 out of 2 new replicas have been updated...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 out of 2 new replicas have been updated...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 out of 2 new replicas have been updated...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 out of 2 new replicas have been updated...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 out of 2 new replicas have been updated...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 out of 2 new replicas have been updated...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
error: deployment "scoutasiacluster-dbd1" exceeded its progress deadline
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "scoutasiacluster-dbd1" rollout to finish: 1 old replicas are pending termination...
Error: Error: error: deployment "scoutasiacluster-dbd1" exceeded its progress deadline
/usr/bin/kubectl describe Deployment scoutasiacluster-dbd1 --namespace scoutasiacluster8fce
Name:                   scoutasiacluster-dbd1
Namespace:              scoutasiacluster8fce
CreationTimestamp:      Wed, 14 Oct 2020 06:09:46 +0000
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 14
Selector:               app=scoutasiacluster-dbd1
Replicas:               2 desired | 2 updated | 3 total | 0 available | 3 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=scoutasiacluster-dbd1
  Containers:
   scoutasiacluster-dbd1:
    Image:        ***.azurecr.io/scoutasiacluster:d4a2078b03d4fa031146c48c83b623735d9b59ee
    Port:         4902/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  scoutasiacluster-dbd1-65c476cfdc (1/1 replicas created)
NewReplicaSet:   scoutasiacluster-dbd1-557f685568 (2/2 replicas created)
Events:
  Type    Reason             Age                  From                   Message
  ----    ------             ----                 ----                   -------
  Normal  ScalingReplicaSet  53m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-55dcbb85cd to 1
  Normal  ScalingReplicaSet  53m                  deployment-controller  Scaled up replica set scoutasiacluster-dbd1-69c78c8dbf to 1
  Normal  ScalingReplicaSet  46m (x2 over 3h13m)  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-55dcbb85cd to 0
  Normal  ScalingReplicaSet  46m                  deployment-controller  Scaled up replica set scoutasiacluster-dbd1-69c78c8dbf to 2
  Normal  ScalingReplicaSet  36m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-d6454856d to 0
  Normal  ScalingReplicaSet  36m                  deployment-controller  Scaled up replica set scoutasiacluster-dbd1-694bdbc585 to 1
  Normal  ScalingReplicaSet  35m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-69c78c8dbf to 1
  Normal  ScalingReplicaSet  35m                  deployment-controller  Scaled up replica set scoutasiacluster-dbd1-694bdbc585 to 2
  Normal  ScalingReplicaSet  34m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-69c78c8dbf to 0
  Normal  ScalingReplicaSet  34m                  deployment-controller  Scaled up replica set scoutasiacluster-dbd1-79798c79c9 to 1
  Normal  ScalingReplicaSet  33m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-694bdbc585 to 1
  Normal  ScalingReplicaSet  33m                  deployment-controller  Scaled up replica set scoutasiacluster-dbd1-5f98b46d6 to 1
  Normal  ScalingReplicaSet  32m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-694bdbc585 to 0
  Normal  ScalingReplicaSet  20m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-79798c79c9 to 0
  Normal  ScalingReplicaSet  20m                  deployment-controller  Scaled up replica set scoutasiacluster-dbd1-7d4c8cf88b to 1
  Normal  ScalingReplicaSet  19m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-5f98b46d6 to 1
  Normal  ScalingReplicaSet  19m                  deployment-controller  Scaled up replica set scoutasiacluster-dbd1-65c476cfdc to 1
  Normal  ScalingReplicaSet  18m                  deployment-controller  Scaled up replica set scoutasiacluster-dbd1-65c476cfdc to 2
  Normal  ScalingReplicaSet  18m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-5f98b46d6 to 0
  Normal  ScalingReplicaSet  18m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-65c476cfdc to 1
  Normal  ScalingReplicaSet  18m                  deployment-controller  Scaled up replica set scoutasiacluster-dbd1-557f685568 to 1
  Normal  ScalingReplicaSet  17m (x2 over 32m)    deployment-controller  (combined from similar events): Scaled up replica set scoutasiacluster-dbd1-557f685568 to 2
  Normal  ScalingReplicaSet  17m                  deployment-controller  Scaled down replica set scoutasiacluster-dbd1-7d4c8cf88b to 0
/usr/bin/kubectl get service/scoutasiacluster-dbd1 -o json --namespace scoutasiacluster8fce
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"scoutasiacluster-dbd1\"},\"name\":\"scoutasiacluster-dbd1\",\"namespace\":\"scoutasiacluster8fce\"},\"spec\":{\"ports\":[{\"name\":\"http\",\"port\":4902,\"protocol\":\"TCP\",\"targetPort\":4902}],\"selector\":{\"app\":\"scoutasiacluster-dbd1\"},\"type\":\"LoadBalancer\"}}\n"
        },
        "creationTimestamp": "2020-10-14T06:09:46Z",
        "finalizers": [
            "service.kubernetes.io/load-balancer-cleanup"
        ],
        "labels": {
            "app": "scoutasiacluster-dbd1"
        },
        "name": "scoutasiacluster-dbd1",
        "namespace": "scoutasiacluster8fce",
        "resourceVersion": "163012",
        "selfLink": "/api/v1/namespaces/scoutasiacluster8fce/services/scoutasiacluster-dbd1",
        "uid": "29cfb024-3cd0-4d48-a032-97ac497bf97c"
    },
    "spec": {
        "clusterIP": "x.x.x.x",
        "externalTrafficPolicy": "Cluster",
        "ports": [
            {
                "name": "http",
                "nodePort": 31494,
                "port": 4902,
                "protocol": "TCP",
                "targetPort": 4902
            }
        ],
        "selector": {
            "app": "scoutasiacluster-dbd1"
        },
        "sessionAffinity": "None",
        "type": "LoadBalancer"
    },
    "status": {
        "loadBalancer": {
            "ingress": [
                {
                    "ip": "x.x.x.x"
                }
            ]
        }
    }
}
ServiceExternalIP scoutasiacluster-dbd1 x.x.x.x
Error: Error: RolloutStatusTimedout
0s
0s
```

```
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: saesvcseasitet.azurecr.io
        username: ${{ secrets.acr_saesvcseasitet_username }}
        password: ${{ secrets.acr_saesvcseasitet_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t saesvcseasitet.azurecr.io/scoutasiacluster:${{ github.sha }}
        docker push saesvcseasitet.azurecr.io/scoutasiacluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_scoutasiacluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep scoutasiacluster8fce | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace scoutasiacluster8fce`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: scoutasiacluster8fce
        container-registry-url: saesvcseasitet.azurecr.io
        container-registry-username: ${{ secrets.acr_saesvcseasitet_username }}
        container-registry-password: ${{ secrets.acr_saesvcseasitet_password }}
        secret-name: scoutasiacludockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: scoutasiacluster8fce
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          saesvcseasitet.azurecr.io/scoutasiacluster:${{ github.sha }}
        imagepullsecrets: |
          scoutasiacludockerauth
```

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: scoutasiacluster-dbd1
  namespace: scoutasiacluster8fce
  selfLink: >-
    /apis/apps/v1/namespaces/scoutasiacluster8fce/deployments/scoutasiacluster-dbd1
  uid: 0b046dbf-90de-4c40-8e26-11ee8f5d804f
  resourceVersion: '218963'
  generation: 16
  creationTimestamp: '2020-10-14T06:09:46Z'
  annotations:
    deployment.kubernetes.io/revision: '16'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"scoutasiacluster-dbd1","namespace":"scoutasiacluster8fce"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"scoutasiacluster-dbd1"}},"template":{"metadata":{"labels":{"app":"scoutasiacluster-dbd1"}},"spec":{"containers":[{"image":"saesvcseasitet.azurecr.io/scoutasiacluster:8b6d5618483648ca6f023dc6b804282ca36f680b","name":"scoutasiacluster-dbd1","ports":[{"containerPort":4902}]}],"imagePullSecrets":[{"name":"scoutasiacludockerauth"}]}}}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scoutasiacluster-dbd1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scoutasiacluster-dbd1
    spec:
      containers:
        - name: scoutasiacluster-dbd1
          image: >-
            saesvcseasitet.azurecr.io/scoutasiacluster:8b6d5618483648ca6f023dc6b804282ca36f680b
          ports:
            - containerPort: 4902
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: scoutasiacludockerauth
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 16
  replicas: 3
  updatedReplicas: 2
  unavailableReplicas: 3
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2020-10-14T09:24:27Z'
      lastTransitionTime: '2020-10-14T09:24:27Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-10-14T12:37:01Z'
      lastTransitionTime: '2020-10-14T12:37:01Z'
      reason: ReplicaSetUpdated
      message: ReplicaSet "scoutasiacluster-dbd1-6fbb8bcf69" is progressing.
```

**Testgrid link**:

**Reason for failure**:
It wait until too long then it cause failure

**Anything else we need to know**:
