### ISSUE TITLE
Kubectl explain fail(only for the first time) for crd

### ISSUE THREAD

**Issue by xpivarc** [kubernetes/kubernetes#95601]
**What happened**:

`k explain ct2`
the server doesn't have a resource type "ct2"

**What you expected to happen**:
See a explain output for ct2.

**How to reproduce it (as minimally and precisely as possible)**:

Create any new `crd`. Example: 
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: crontab2s.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: crontab2s
    # singular name to be used as an alias on the CLI and for display
    singular: crontab2
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CronTab2
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ct2
```

Run `k explain ct2`.
the server doesn't have a resource type "ct2"

<optional>
Run `k explain ct2` for the second time and get the expected output.

**Anything else we need to know?**:
It doesn't occur in 1.18
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
