### ISSUE TITLE
startupProbe is not applied to Pod if serviceAccountName is set.

### ISSUE THREAD

**Issue by Xyaren** [kubernetes/kubernetes#95604]
**What happened**:
When adding `serviceAccountName` and  `startupProbe`to the pod template in my deployment, the resulting pods will not have a startup probe.
When adding only one of both, everything works as expected.
Readiness and liveness probes are not affected and work together with `startupProbe`.
The deployment looks fine on all cases, also does the replicaset (startupProbe is shown here in k9s descibe).
In the pods there is no trace of the configured startup probe. 

**What you expected to happen**:
Serviceaccount should not affect the startup probe behaviour

**How to reproduce it (as minimally and precisely as possible)**:
Create a deployment with `startupProbe` and `serviceAccountName` set.
Deploy using kubectl

**Anything else we need to know?**:
We "just" update to 1.18 on aws so we can use startupProbes.

**Environment**:
- `Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"2020-08-28T23:04:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: aws eks 1.18 (v1.18.8-eks-7cbda)

**Comment by Xyaren** [comment]
Okay I did some more research:
The issue **only** occurs when using the annotation `eks.amazonaws.com/role-arn` on the ServiceAccount.
When I create a service account without that annotation and create the deployment afterwards, the startup probe is applied on the pod.
When I do the same with the annotation applied to the ServiceAccount, the probe will be missing on the pods.

Deployment to replicate the issue:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::XXXXXXXXXXXX:role/xxxxxxxxxxxxxxxxxxx" #replace with real role ARN
  name: experiment-service-account
  namespace: dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: experiment-bug-chaser
  namespace: dev
spec:
  selector:
    matchLabels:
      app: experiment-bug-chaser-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: experiment-bug-chaser-pod
    spec:
      serviceAccountName: experiment-service-account
      containers:
        - name: app-container
          image: brndnmtthws/nginx-echo-headers:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 10
```
