### ISSUE TITLE
Horizontal Pod Autoscaler doesn`t  automatically scale the number of pods correctly

### ISSUE THREAD

**Issue by JoshuaAndrew** [kubernetes/kubernetes#95642]
**What happened**:
if we set SelectPolicy MinPolicySelect on scaleUp behavior or scaleDown behavior, Horizontal Pod Autoscaler does not scale the number of pods correctly.

**What you expected to happen**:
if we set SelectPolicy MinPolicySelect on scaleUp behavior or scaleDown behavior, Horizontal Pod Autoscaler scales the number of pods correctly.

**How to reproduce it (as minimally and precisely as possible)**:

step 1:  deploy nginx service
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
```
```
kubectl  create -f  nginx.yaml
```

step 2: create HPA resource
```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
  namespace: default
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Percent
        value: 80
      selectPolicy: Min
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - periodSeconds: 60
        type: Percent
        value: 50
      - periodSeconds: 60
        type: Pods
        value: 2
      selectPolicy: Min
      stabilizationWindowSeconds: 300
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
```

```
kubectl create -f hpav2.yaml
```

step 3:  generate load for nginx

```
ab -c 100 -n 100000 http://<nginx-svc>:80/
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.17.x  v1.18.x  v1.19.x
- Cloud provider or hardware configuration:  None
- OS (e.g: `cat /etc/os-release`):   CentOS Linux release 7.8.2003 (Core)
- Kernel (e.g. `uname -a`):  Linux k8s-master-1 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:  kubeadm
- Network plugin and version (if this is a network-related bug):  calico
- Others:
