### ISSUE TITLE
Add custom TLS policies for AWS ELB

### ISSUE THREAD

**Issue by barucoh** [kubernetes/kubernetes#95693]
**What would you like to be added**:
When creating a service with type `LoadBalancer` on an AWS environment a default TLS negotiation policy is attached.
It's only possible to assign an already predefined policy as part of the service annotations:
```
 metadata:
      name: my-service
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
```

**Why is this needed**:
Even the latest AWS predefined policies still contain weak cipher suites and we must update them manually with every new service created.

This is related to issue - https://github.com/kubernetes/kubernetes/issues/90677
