### ISSUE TITLE
Deployment gets restarted with old image tag

### ISSUE THREAD

**Issue by ncri** [kubernetes/kubernetes#95703]
**What happened**:

A deployment we have running get's restarted with an old docker image tag. The tag is always the same and not explicitly mentioned in any of our k8s config code. The image with that tag does not exist anymore at the source but is taken from cache.

**What you expected to happen**:

The deployment does not get restarted. And if it get's restarted (for whatever good reason we don't see yet) then the k8s scheduler should respect the image version of the current deployment and not revert to an old one that is cached on the machine.

**How to reproduce it (as minimally and precisely as possible)**:

In our setup we deploy by applying k8 config files with new configurations. Whenever we deploy a new version ist stays for some time (usually at least several hours), then a new deploy (replica set) gets rolled out for no apparent reason, using the old image.

Unfortunately we do not have an example app to reproduce this.

**Anything else we need to know?**:

Our docker images are stored on the google container registry. We have autoscaling switched on on the node.

**Environment**:
- Kubernetes version (use `kubectl version`):  

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:  GKE 
- OS (e.g: `cat /etc/os-release`):

PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`):  Linux app-deployment-85b9f7589d-4nzbd 4.19.112+ #1 SMP Fri Sep 4 12:00:04 PDT 2020 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ahg-g** [comment]
/remove-sig scheduling
/sig node

If you are using the same tag for the image, but the image is changing in the source, then you need to use `imagePullPolicy: Always`: https://kubernetes.io/docs/concepts/configuration/overview/#container-images

**Comment by ncri** [comment]
The image is not changing at the source. The issue is that kubernetes restarts our pods with an old image.

Lets say the current image of the deploy looks like this: 

`eu.gcr.io/.../...:c08a508`

After the deployed pods run some time, they get restarted by kubernetes with an old image, that is cached and it is always the same:

`eu.gcr.io/.../...:01ba54d`

So the question is, if the pods need to get restarted for whatever reason, why does it not load the deployment's image `eu.gcr.io/.../...:c08a508`, but the old one instead? We don't want `imagePullPolicy: Always`, because using a cached image is totally fine. If it is the correct one.

**Comment by ncri** [comment]
Turns out it is not the autoscaler. After some time kubernetes restarts the deployment with the old image, adding a new replica set:

```
kubectl get rs
xxx-deployment-589f75c896                        0         0         0       158m
xxx-deployment-7999489669                        3         3         3       60m
```

Correct replicaset is the first one.

**Comment by troy0820** [comment]
@ncri 
If your **pods** gets deleted, the replicaset recreates the pods with the same image that the replicaset hash in your `kubectl describe deploy`

If you are getting a new replicaset, that means that the image has changed and a new replicaset will be created for that deployment.  _(You can check the history with kubectl rollout history deployment to see)_ 

If a new deployment is happening, something is changing your deployment (and not the restarting of the pods) and can be investigated with `kubectl get events` in the namespace where the deployment lives.

**Comment by ncri** [comment]
Thanks @troy0820, I tried `get events` before, but wasn't able to spot the creation of the new replicaset yet, as events are only listed one hour back as far as I know. And yes, I'm aware that the restarting of the pods is only a side effect of changing the deployment. I still have no idea _why_ the deployment is changed. I will try to catch matching events, which is not easy, as the deployment change doesn't haopen consistently at the same time.

**Comment by krmayankk** [comment]
a repro with exact config of the deployment will help

**Comment by ncri** [comment]
The project is private, so i cannot share the exact config here. The deployment looks like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: eu.gcr.io/xxxxx/xxxxx:c08a508
          resources:
            requests:
              cpu: "0.2"
              memory: "865M"
          command: ["bundle"]
          args: ["exec", "sidekiq", "-q", "mailer,1", "-q", "priority,1", "-q", "default"]
          envFrom:
            - secretRef:
                name: app-secret
            - secretRef:
                name: pg-secret
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-l", "-c", "ps -ef | grep sidekiq | grep busy | grep -v grep | awk '{print $2}'  > $PIDFILE; bundle exec sidekiqctl stop $PIDFILE"]
      nodeSelector:
        node_type: default
```
