### ISSUE TITLE
Fail to find PostFilter extension point

### ISSUE THREAD

**Issue by YanzhaoLi** [kubernetes/kubernetes#95708]
**What happened**:
The [official doc](https://kubernetes.io/docs/reference/scheduling/config/#scheduling-plugins) says: "DefaultPreemption: Provides the default preemption mechanism. Extension points: PostFilter", but the docs only list 10 extension points without the PostFilter. 
And I tested with such a configuration:
 ```      
        apiVersion: kubescheduler.config.k8s.io/v1beta1
        kind: KubeSchedulerConfiguration
        clientConnection:
          kubeconfig: /var/vcap/jobs/kube-scheduler/config/kubeconfig
        profiles:
          - plugins:
              PostFilter:
                disabled:
                - name: DefaultPreemption
```
It failed with `unknown field: PostFilter `:
```
v1beta1.KubeSchedulerConfiguration.Profiles: []v1beta1.KubeSchedulerProfile: v1beta1.KubeSchedulerProfile.Plugins: v1beta1.Plugins.ReadObject: found unknown field: PostFilter, error found in #10 byte of ...|ostFilter":{"disable|..., bigger context ...|onfiguration","profiles":[{"plugins":{"PostFilter":{"disabled":[{"name":"DefaultPreemption"}]}}}]}
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
