### ISSUE TITLE
error: error parsing wordpress-deployment.yaml: error converting YAML to JSON: yaml: line 33: could not find expected ':'

### ISSUE THREAD

**Issue by vpsvpnvip** [kubernetes/kubernetes#95754]
trying to follow kubernetes tutorial[1]Example: Deploying WordPress and MySQL with Persistent Volumes;
run command 'kubectl apply -f wordpress-deployment.yaml' on google kubernetes using cloudshell;
got this error:**error: error parsing wordpress-deployment.yaml: error converting YAML to JSON: yaml: line 33: could not find expected ':'
**wordpress-deployment.yaml**
````apiVersion: v1
kind: Service
metadata:
name: wordpress
labels:
app: wordpress
spec:
ports:
- port: 80
selector:
app: wordpress
tier: frontend
type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: wp-pv-claim
labels:
app: wordpress
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
name: wordpress
labels:
app: wordpress
spec:
selector:
matchLabels:
app: wordpress
tier: frontend
strategy:
type: Recreate
template:
metadata:
labels:
app: wordpress
tier: frontend
spec:
containers:
- image: wordpress:4.8-apache
name: wordpress
env:
- name: WORDPRESS_DB_HOST
value: 34.72.250.151
- name: WORDPRESS_DB_PASSWORD
valueFrom:
secretKeyRef:
name: mysql-pass
key: password
- name: WORDPRESS_DB_USER
valueFrom：
secretkeyRef:
name: mysql-pass
ports:
- containerPort: 80
name: wordpress
volumeMounts:
- name: wordpress-persistent-storage
mountPath: /var/www/html
volumes:
- name: wordpress-persistent-storage
persistentVolumeClaim:
claimName: wp-pv-claim````````

**Comment by troy0820** [comment]
/kind support 
It looks like the indentation of your yaml is incorrect.  Also, you are missing the apiVersion in your service.  

```
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
```
/remove-kind bug

**Comment by neolit123** [comment]
hi,

> converting YAML to JSON: yaml: line 33

this looks like a malformed YAML.

values under spec must be indented properly as YAML is whitespace sensitive:

```
spec:
  selector:
    matchLabels:
     app: wordpress
...
```

please don't open more issues about this in this repository and try the support channels instead:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
