### ISSUE TITLE
PodTopologySpread schedules pods to nodes without topologySpreadConstraints[*].topologyKey

### ISSUE THREAD

**Issue by ChunyiLyu** [kubernetes/kubernetes#95808]
**What happened**:

I was testing out the pod topology spread functionality in a local `1.19` k8s cluster. I noticed that when I set the constraint to be 

```
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: <some label that does not match any in the nodes>
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        foo: bar
```
pods are still successfully scheduled.

**What you expected to happen**:

Reading the documentation on [pod topology spread conventions](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#conventions), I expected pods not to be scheduled since the node should be "bypassed due to the absence of label". Did I miss something here?
 
**How to reproduce it (as minimally and precisely as possible)**:

Create a pod with topologySpreadConstraints[0].topologyKey that does not match to any node labels, and set `whenUnsatisfiable` to `DoNotSchedule`.

**Anything else we need to know?**:

Thank you 😀

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
It's a kind cluster created with image `kindest/node:v1.19.1`.
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
