### ISSUE TITLE
PSP seccomp needs annotations 'runtime/default' in 1.19.x

### ISSUE THREAD

**Issue by YanzhaoLi** [kubernetes/kubernetes#95817]
**What happened**:

In k8s 1.19.2

If the seccomp annotations of psp doesn't contain `runtime/default`, pod with seccomp annotations `seccomp.security.alpha.kubernetes.io/pod: 'docker/default` would not start with error:
```
pods "coredns-7b78847794-vzmmz" is forbidden: PodSecurityPolicy: unable to validate pod: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/coredns]: 
Forbidden: runtime/default is not an allowed seccomp profile. Valid values are docker/default]'
```

psp with `runtime/default` works
```
metadata:
  name: kube-system-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default, docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
```

psp without `runtime/default` doesn't work
```
metadata:
  name: kube-system-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
```

Is this due to https://github.com/kubernetes/kubernetes/pull/90948 ?

**What you expected to happen**:
In k8s 1.18, psp annotations without `runtime/default` works. I think in k8s 1.19, it should also work.
