### ISSUE TITLE
Ability to provide OIDC authentication token to kubectl without leaking the token to the process table

### ISSUE THREAD

**Issue by danielpops** [kubernetes/kubernetes#95815]
**What would you like to be added**:
The ability to pass an OIDC Authentication token via file or environment variable. e.g.

```
$ kubectl --token-file <(get-token client-id) get pods
```

OR 

```
$ KUBE_TOKEN=$(get-token client-id) kubectl get pods
```

**Why is this needed**:
Passing a sensitive string like an OIDC authentication token via the the command line e.g. `kubectl --token foo get pods` results in the sensitive string leaking into the process table, thus making it visible to anybody running `ps(1)` on the system. The password is also leaked into your shell's history file

In theory there is a workaround to configure a `KUBECONFIG` with the token and refer to that in the `kubectl` invocation. At least in my environment, these `KUBECONFIG` files are managed by the infrastructure configuration management and shared among many users, and copying them and dynamically modifying them on the fly to add a whole section like this feels cumbersome and non-ideal
```
users:
- name: the_user
  user:
    auth-provider:
      config:
        client-id: not_actually_used_but_cannot_be_omitted
        id-token: bla
        idp-issuer-url: not_actually_used_but_cannot_be_omitted
      name: oidc
```

**Comment by mattmoyer** [comment]
I think you could also tackle this problem using a [credential plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins). It's a little bit cumbersome because you need to output valid JSON from a shell script, but that isn't too hard with [`jq`](https://stedolan.github.io/jq/manual/):

```yaml
apiVersion: v1
kind: Config
# [...]
users:
- name: the_user
  user:
    exec:
      command: sh
      args:
      - '-c'
      - jq -n --rawfile TOKEN <(get-token client-id) '{"apiVersion":"client.authentication.k8s.io/v1beta1","kind":"ExecCredential","status":{"token": $TOKEN}}'
```

Using this kubeconfig file would result in `kubectl` invoking your `get-token client-id` command, the output of which would be JSON-encoded into the correct ExecCredential format and consumed by `kubectl`.

A related approach would be to adjust your example `get-token` command so that it has a mode that outputs the token as ExecCredential JSON directly. You could then use it more simply like:
```yaml
apiVersion: v1
kind: Config
# [...]
users:
- name: the_user
  user:
    exec:
      command: sh
      args: ["get-token", "client-id", "--output-k8s-exec-credential"]
```

Hopefully this can meet your needs well enough that no additional kubectl flags are required.
