### ISSUE TITLE
How to define wildcard in yaml file

### ISSUE THREAD

**Issue by johnreytanquinco** [kubernetes/kubernetes#95830]
Hello, I am trying to look on how to define a wildcard as host because it is requires to access the application server.
I am getting this error message:
`The host header sent by the client is not allowed`

When I research on the net, it requires to add the wildcard as hostname.
`--webservice-allowed-hostnames=*`

Is there a way to include `*` in my yaml file?
```
...
spec:
  tls:
    - hosts:
      - duplicati.domain
      secretName: duplicati-tls
  rules:
  - host: duplicati.domain
    http:
      paths:
      - path: /
        backend:
          serviceName: duplicati
          servicePort: 80
```
