### ISSUE TITLE
KubeSchedulerConfiguration documentation example fail

### ISSUE THREAD

**Issue by r0bj** [kubernetes/kubernetes#95842]
**What happened**:

Using example for `KubeSchedulerConfiguration` from documentation https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#cluster-level-default-constraints failed with:
```
v1beta1.KubeSchedulerConfiguration.Profiles: []v1beta1.KubeSchedulerProfile: decode slice: expect [ or n, but found {, error found in #10 byte of ...|rofiles":{"pluginCon|..., bigger context ...|"leaderElection":{"leaderElect":true},"profiles":{"pluginConfig":[{"args":{"defaultConstraints":[{"m|...
```

**What you expected to happen**:

Example from documentation works.

**How to reproduce it (as minimally and precisely as possible)**:

config.yaml:
```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: kubeconfig
leaderElection:
  leaderElect: true
profiles:
  pluginConfig:
    - name: PodTopologySpread
      args:
        defaultConstraints:
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
```
```
kube-scheduler --config=config.yaml
```
```
[...]
v1beta1.KubeSchedulerConfiguration.Profiles: []v1beta1.KubeSchedulerProfile: decode slice: expect [ or n, but found {, error found in #10 byte of ...|rofiles":{"pluginCon|..., bigger context ...|"leaderElection":{"leaderElect":true},"profiles":{"pluginConfig":[{"args":{"defaultConstraints":[{"m|...
```

How should `KubeSchedulerConfiguration` configuration look like for `PodTopologySpread`?

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux dev-k8s-deployer-r1 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by alculquicondor** [comment]
/triage accepted

oh, I missed a dash. It should be:

```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration

profiles:
  - pluginConfig:
      - name: PodTopologySpread
        args:
          defaultConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: ScheduleAnyway
```

Would you mind sending a PR to kubernetes/website?
