### ISSUE TITLE
Separate the upscale and downscale configuration of hpa

### ISSUE THREAD

**Issue by DemonsLu** [kubernetes/kubernetes#95861]
**What would you like to be added**:
Separate the upscale and downscale configuration of hpa.

**Why is this needed**:
consider this: 
1. we deployed a deployment which replicas is 4, cpu resource request is 2 core, and hpa's cpu targetAverageUtilization is 100.
2. The current service corresponding to the deployment, the total cpu load is 8.8 core.
3. According to the hpa config, pod targetAverageUtilization is greater than 100%, so pod will upscale to 5
4. Now we have 5 pods, and pod targetAverageUtilization is less than 100%, and it will downscale....

I known I can configure the --horizontal-pod-autoscaler-downscale-stabilization to delay the downscale event, but in my opinion, separate the upscale and downscale configuration of hpa is better than do that.

for example:
```
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 100  # upscale config
        downscaleAverageUtilization: 85 # downscale config
```
