### ISSUE TITLE
nftables do not scale for services

### ISSUE THREAD

**Issue by mskrocki** [kubernetes/kubernetes#96018]
**What happened**:
Can only scale up to ~500 services on a nftables based cluster (CentOS 8+, Debian 10+) with kube-proxy.
With 1000 services, around half fails to work.

**What you expected to happen**:
Tested with same cluster deployment, but on Ubuntu 18.04 (that uses legacy iptables) and managed to reach 2500 services.

**How to reproduce it (as minimally and precisely as possible)**: 
* create a 100 node cluster on OS with nftables enabled (CentOS 8, Debian 10)
* create simple http deployment (nginx) with 200 replicas
* create Load Balancer services (below example): I have used 100 VIPs and 10 Ports/svc
* wait for the cluster to "stabilize"
* try curl to every svcIP:Port

```
apiVersion: v1
kind: Service
metadata:
  name: scale-service-{{.Num}}
spec:
  ports:
{{range .Ports}}
  - port: {{.}}
    protocol: TCP
    targetPort: 8080
    name: sv{{.}}
{{- end}}
  selector:
    app: scale-service
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: {{.IP}}
```

**Anything else we need to know?**:
The iptables-save rules count on nftables reached ~400k lines when some services were unreachable.
For the non-nftables case I was able to see >1m rules.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.6
- Cloud provider or hardware configuration: Deployed on VMs with 4vCPU, 16G mem,  50G disk,
- OS (e.g: `cat /etc/os-release`): CentOS 8.1
- Kernel (e.g. `uname -a`): 4.18
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Cilium 1.8 with kube-proxy present, using metalLB
- Others:
