### ISSUE TITLE
How to block exec into pod

### ISSUE THREAD

**Issue by nagasitaramthigulla** [kubernetes/kubernetes#96298]
I have a user who can install and update pods in cluster.
For secrets management, we are using hashicorp vault, only the admin user has access to the vault secrets.

When vault injects the secrets we are able to see them as plain text when we exec into pod.

So i want to prevent exec to specific users in the k8s cluster.
How can I achieve that using RBAC?

**Comment by troy0820** [comment]
This issue describes what you would like to achieve with blocking exec/attach from pods https://github.com/kubernetes/kubernetes/issues/78741#issuecomment-499236161

**Comment by nagasitaramthigulla** [comment]
@troy0820 
I tried below
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-user
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-user-full-access
  namespace: default
rules:
- apiGroups: [""]
  resources:
  - pods/attach
  - pods/execy
  verbs: [""]
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-user-view
  namespace: default
subjects:
- kind: ServiceAccount
  name: default-user
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-user-full-access
```
but it did not work as expected
```
kubectl auth can-i exec pod
yes
```
