### ISSUE TITLE
Templating for ConfigMaps / Secrets aggregation

### ISSUE THREAD

**Issue by sylr** [kubernetes/kubernetes#96346]
**What would you like to be added**:

A kubernetes API which would allow to mount files in pods based on the values coming from both ConfigMaps and Secrets, e.g.:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  loglevel: debug
  output: stdout
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  dbConnectionString: cG9zdGdyZXM6Ly9wb3N0Z3JlczpteWJhZHBhc3N3ZEBwZzEwL3Bvc3RncmVz
---
apiVersion: v1alpha1
kind: ConfigTemplate
metadata:
  name: my-configtemplate
data:
  config.yaml: |-
    loglevel: {{ .myConfigs.loglevel }}
    output: {{ .myConfigs.output }}
    dbConnectionString: {{ .mySecrets.dbConnectionString }}
spec:
  source:
  - name: myConfigs
    configMap: my-configmap
  - name: mySecrets
    secret: my-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      ...
      volumes:
      - configTemplate:
          defaultMode: 420
          name: my-configtemplate
        name: config-volume
```
**Why is this needed**:

Vast majority of software out there which uses files as configuration only use a single file which contains both normal configurations and credentials.

This force us to use either a ConfigMap or a Secret as configuration source for those software.

Using a ConfigMap is not a good option as storing credentials in ConfigMaps is not a good practice. Using Secrets on the other end is tedious because of the base64 encoding.
