### ISSUE TITLE
Pod Status ImagePullBackoff - Will not delete  

### ISSUE THREAD

**Issue by mojoa** [kubernetes/kubernetes#96350]
**What happened**:
After ```kubectl create -f webapp.yaml```, Pod status from ```kubectl get pod -l app=webapp``` is ImagePullBackoff and ```kubectl delete pod -l app=webapp``` returns pod "webapp-0" deleted, Pod recreates automatically. ```kubectl get deployments --all-namespaces``` shows no mention of webapp. ```kubectl get jobs --all-namespaces``` returns no resources found. ```kubectl get service --all-namespaces``` returns ```default         webapp            ClusterIP      10.101.160.165   <none>        80/TCP                   145m```

**What you expected to happen**:
I would like to be able to ```kubectl delete deployment webapp``` or otherwise remove the webapp deployment.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl create -f webapp.yaml
kubectl get pod -l app=webapp 
kubectl delete pod -l app=webapp 
kubectl get pod -l app=webapp
kubectl get deployments --all-namespaces
kubectl get service --all-namespaces
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Win10-vmware player 16 host - 
- OS (e.g: `cat /etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`):
```
Linux k8y 4.14.200-155.322.amzn2.x86_64 #1 SMP Thu Oct 15 20:11:12 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
```
cat webapp.yaml
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: webapp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webapp
spec:
  serviceName: "webapp"
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - node1
      tolerations:
      - effect: NoSchedule
        operator: Exists   # this will effectively tolerate any taint
      containers:
      - name: webapp
        image: nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
```
