### ISSUE TITLE
How to delete pod but not clear /dev/shm when mount /dev/shm in emptyDir type

### ISSUE THREAD

**Issue by gosoon** [kubernetes/kubernetes#96367]
**What would you like to be added**:

We need to mount /dev/shm in the container, and /dev/shm needs to be restricted by cgroup, but after the emptyDir method is used to mount, /dev/shm will be deleted after the pod is deleted. We don't want the container to be deleted Later, /dev/shm was also deleted. How can I use it? I hope I can get your help.
```
        volumeMounts:
        - mountPath: /dev/shm
          name: cache-volume
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 100Mi
        name: cache-volume
```

**Why is this needed**:
