### ISSUE TITLE
configMap.item.mode: 0400 working on pod but not on deployment

### ISSUE THREAD

**Issue by citananda** [kubernetes/kubernetes#96380]
**What happened**:
When I create a deployment with configMap.item.mode: 0400, the permission file is 0440

**What you expected to happen**:
The file permission should be 0400

**How to reproduce it (as minimally and precisely as possible)**:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: test-conf
data:
  test: |
    test
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: sismics/backupninja:1.4.3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: test
        volumeMounts:
        - mountPath: /etc/backup.d/test
          name: test-conf-file
          subPath: test
      volumes:
      - name: test-conf-file
        configMap:
          defaultMode: 256
          name: test-conf
          optional: false
          items: 
          - key: test
            path: test
            mode: 256
```
With a deployment, the file permission is 0440

**Anything else we need to know?**:
The same with a pod is working (file permission is 0400)
```
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: sismics/backupninja:1.4.3
    ports:
    - containerPort: 80
      name: backupninja
    volumeMounts:
    - mountPath: /etc/backup.d/10-db.mysql
      name: test-conf-file
      subPath: test
  volumes:
  - name: test-conf-file
    configMap:
      defaultMode: 256
      name: test-conf
      optional: false
      items: 
      - key: test
        path: test
        mode: 256
```
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
baremetal server  Intel Xeon-E 2288G - 64GB DDR4 ECC 2666MHz - 3x SSD NVMe 1.92TB Datacenter Class Soft RAID
- OS (e.g: `cat /etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
Linux 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
