### ISSUE TITLE
Limited resource allocation for a container results in volume mount permission issues 

### ISSUE THREAD

**Issue by cloudtrov** [kubernetes/kubernetes#96461]
**What happened**:
   We tried deploying mssql as a stateful with appropriate privileges for both container as well as the fsGroup, but the pod moved to CrashLoopBackOff. The container log shows /usr/bin/find: '/proc/9/map_files': Permission denied . When we increased the resource allocation capacity and redeployed the stateful set, the issue got resolved automatically and the pod moved to running state. Not sure how resource allocation and mount permission are interlinked. 

**How to reproduce it (as minimally and precisely as possible)**:

Below is the YAML file used for deployment. 
```
apiVersion: v1
data:
  ACCEPT_EULA: "Y"
  MSSQL_PID: Developer
  SA_PASSWORD: mssql*123
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-11T10:31:46Z"
  labels:
    servicegroup: mssql-aw3lkihq
  name: mssql-envplain-j2s3r
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  labels:
    family: servicegroup
    app: mssql
    servicegroup: mssql-aw3lkihq
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mssql
  serviceName: mssql
  template:
    metadata:
      name: mssql
      labels:
        app: mssql
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: mssql-envplain-j2s3r
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        name: mssql-ga
        resources:
          limits:
            cpu: 500m
            memory: 500M
          requests:
            cpu: 200m
            memory: 200M
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssqldb
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
      subdomain: mssql
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 1
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: mssqldb
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        limits:
          storage: 8Gi
        requests:
          storage: 4Gi
      storageClassName: mssql-sc-gh13w
      volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  ports:
  - name: "1433"
    nodePort: 30000
    port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    family: servicegroup
    servicegroup: mssql-aw3lkihq
  sessionAffinity: None
  type: NodePort
status:

```
**# kubectl get pod** 
```

NAME                                   READY   STATUS             RESTARTS   AGE
mssql-0                                0/1     CrashLoopBackOff   5          4m53s

```
**# kubectl logs -f mssql-0** 
```
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
This program has encountered a fatal error and cannot continue running at Wed Nov 11 11:13:02 2020
The following diagnostic information is available:

         Reason: 0x00000002
     Parameters: 0x2002af9b0
                  [0] 0xffffffffc0000017
    Stack Trace:
                 file://package4/windows/system32/sqlpal.dll+0x000000000030E7D9
                 file://package4/windows/system32/sqlpal.dll+0x000000000030D996
                 file://package4/windows/system32/sqlpal.dll+0x000000000026708D
                 file://package4/windows/system32/sqlpal.dll+0x0000000000202FE2
                 file://package4/windows/system32/sqlpal.dll+0x0000000000347898
                 file:///windows/system32/ntdll.dll+0x00000000000CB598
                 file:///windows/system32/ntdll.dll+0x00000000000C3771
                 file:///windows/system32/ntdll.dll+0x0000000000076F7B
                 file:///windows/system32/ntdll.dll+0x0000000000076F2E
                 file://package4/windows/system32/sqlpal.dll+0x000000000024D7F7
                 file://package4/windows/system32/sqlpal.dll+0x000000000034ED21
                 <unknown>+0x00000000490D9000
        Process: 9 - sqlservr
         Thread: 22 (application thread 0x28)
    Instance Id: 6badba83-84c7-41df-ad47-fa20dfcb85b9
       Crash Id: cc3be5de-7b8c-47fb-8879-b2edbd34b528
    Build stamp: fd4eb1565f159d8f4b2d49c48e96d5797508c8bc5f222def3def149a28435962
   Distribution: Ubuntu 18.04.5 LTS
     Processors: 2
   Total Memory: 7840256000 bytes
      Timestamp: Wed Nov 11 11:13:02 2020

Ubuntu 18.04.5 LTS
Capturing core dump and information to /var/opt/mssql/log...
/bin/cat: /proc/9/maps: Permission denied
/bin/cat: /proc/9/environ: Permission denied
/usr/bin/find: '/proc/9/map_files': Permission denied
/usr/bin/find: '/proc/9/map_files': Permission denied
/usr/bin/find: '/proc/9/map_files': Permission denied
/usr/bin/find: '/proc/9/map_files': Permission denied
/usr/bin/timeout: failed to run command '/bin/journalctl': No such file or directory
/usr/bin/timeout: failed to run command '/bin/journalctl': No such file or directory
Wed Nov 11 11:13:03 UTC 2020 Capturing program information
Wed Nov 11 11:13:04 UTC 2020 Attempting to capture a dump with paldumper for pid 9
WARNING: Capture attempt failure detected
Attempting to capture a filtered dump with paldumper for pid 9
WARNING: Attempt to capture dump failed.  Reference /var/opt/mssql/log/core.sqlservr.9.temp/log/paldumper-debug.log for details
Wed Nov 11 11:13:04 UTC 2020 Attempting to capture a dump with gdb
Wed Nov 11 11:13:04 UTC 2020 Captured a dump with gdb
Wed Nov 11 11:13:04 UTC 2020 Capturing program binaries
Wed Nov 11 11:13:04 UTC 2020 Compressing the dump files
```

Increasing the resource limits to the below and redeploy the stateful set, moved the Pod to running state.

```
limits:
            cpu: 1000m
            memory: 1000M
```

**Environment**:
  kubeversion:  v1.16.13
  Cloud provider : GKE
