### ISSUE TITLE
privileged PSP is getting applied to all namespaces regardless of RBAC

### ISSUE THREAD

**Issue by abhiTamrakar** [kubernetes/kubernetes#96500]
**What happened**: privileged PSP is getting applied to all namespaces regardless of RBAC

**What you expected to happen**: PSP shall be applied as per defined RBAC policies for individual namespaces

**How to reproduce it (as minimally and precisely as possible)**: Have one privileged PSP and one restricted, with admission controller for PodSecurityPolicy enabled and RBAC to decide the association for PSP on Group: system:serviceaccounts

*Privileged PSP*
```
# Should grant access to very few pods, i.e. kube-system system pods and possibly CNI pods
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  allowedCapabilities:
  - '*'
  allowPrivilegeEscalation: true
  fsGroup:
    rule: 'RunAsAny'
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - min: 0
    max: 65535
  privileged: true
  readOnlyRootFilesystem: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  volumes:
  - '*'
---
# role which grants access to the privileged pod security policy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-role-kube-system
  namespace: kube-system
rules:
- apiGroups:
  - extensions
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-system-psp-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: privileged-role-kube-system
subjects:
# For all service accounts in the kube-system namespace
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
---
# role which grants access to the privileged pod security policy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-role-kubernetes-dashboard
  namespace: kubernetes-dashboard
rules:
- apiGroups:
  - extensions
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-dashboard-psp-binding
  namespace: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: privileged-role-kubernetes-dashboard
subjects:
# For all service accounts in the kubernetes-dashboard namespace
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
```

Resrticted PSP
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/restricted'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/restricted'
  name: restricted
spec:
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  fsGroup:
    rule: 'MayRunAs'
    ranges:
      - min: 1
        max: 65535
  hostIPC: false
  hostNetwork: false
  hostPorts:
  - min: 1
    max: 65535
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MayRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'hostPath'
    - 'nfs'
    - 'cephFS'
    - 'vsphereVolume'
    - 'glusterfs'
  allowedHostPaths:
    - pathPrefix: "/test"
      readOnly: false
    - pathPrefix: "/test2"
      readOnly: true
---

# Cluster role which grants access to the restricted pod security policy
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restricted-psp
rules:
- apiGroups:
  - extensions
  resourceNames:
  - restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use
---

# This applies psp/restricted to all authenticated users
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restricted-psp-binding
subjects:
- kind: Group
  name: system:authenticated # All authenticated users
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:serviceaccounts # All service accounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: restricted-psp # A references to the role above
  apiGroup: rbac.authorization.k8s.io
```

**Anything else we need to know?**: 
The audit log says the PSP field was mutated to use privileged PSP instead of restricted.
```json
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "RequestResponse",
  "auditID": "71744d89-4d89-4d43-b472-56fa6b6ebcec",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/testapp/pods",
  "verb": "create",
  "user": {
    "username": "system:serviceaccount:kube-system:replicaset-controller",
    "uid": "979d6f83-1252-4b16-ad1e-39abf7b4995e",
    "groups": [
      "system:serviceaccounts",
      "system:serviceaccounts:kube-system",
      "system:authenticated"
    ]
  },
  "sourceIPs": [
    "20.223.131.122"
  ],
  "userAgent": "kube-controller-manager/v1.18.10 (linux/amd64) kubernetes/62876fc/system:serviceaccount:kube-system:replicaset-controller",
  "objectRef": {
    "resource": "pods",
    "namespace": "testapp",
    "apiVersion": "v1"
  },
  "responseStatus": {
    "metadata": {},
    "code": 201
  },
  "requestObject": {
    "kind": "Pod",
    "apiVersion": "v1",
    "metadata": {
      "generateName": "testapp-69569dc589-",
      "creationTimestamp": null,
      "labels": {
        "app.kubernetes.io/instance": "testapp",
        "app.kubernetes.io/name": "testapp",
        "app.kubernetes.io/namespace": "testapp",
        "pod-template-hash": "69569dc589"
      },
      "annotations": {
        "kubernetes.io/psp": "restricted"
      },
      "ownerReferences": [
        {
          "apiVersion": "apps/v1",
          "kind": "ReplicaSet",
          "name": "testapp-69569dc589",
          "uid": "a282942f-b901-4844-8251-a79343e20a8e",
          "controller": true,
          "blockOwnerDeletion": true
        }
      ]
    },
    "spec": {
      "containers": [
        {
          "name": "testapp",
          "image": "private-registry/testapp/helloworld:1.0",
          "ports": [
            {
              "name": "http",
              "containerPort": 8080,
              "protocol": "TCP"
            }
          ],
          "resources": {
            "limits": {
              "cpu": "100m",
              "memory": "128Mi"
            },
            "requests": {
              "cpu": "50m",
              "memory": "20Mi"
            }
          },
          "livenessProbe": {
            "tcpSocket": {
              "port": 8080
            },
            "initialDelaySeconds": 30,
            "timeoutSeconds": 15,
            "periodSeconds": 30,
            "successThreshold": 1,
            "failureThreshold": 5
          },
          "readinessProbe": {
            "tcpSocket": {
              "port": 8080
            },
            "initialDelaySeconds": 5,
            "timeoutSeconds": 15,
            "periodSeconds": 5,
            "successThreshold": 1,
            "failureThreshold": 30
          },
          "terminationMessagePath": "/dev/termination-log",
          "terminationMessagePolicy": "File",
          "imagePullPolicy": "IfNotPresent",
          "securityContext": {
            "runAsUser": 101,
            "runAsNonRoot": true
          }
        }
      ],
      "restartPolicy": "Always",
      "terminationGracePeriodSeconds": 30,
      "dnsPolicy": "ClusterFirst",
      "serviceAccountName": "testapp",
      "serviceAccount": "testapp",
      "securityContext": {
        "fsGroup": 101
      },
      "schedulerName": "restricted-scheduler",
      "enableServiceLinks": true
    },
    "status": {}
  },
  "responseObject": {
    "kind": "Pod",
    "apiVersion": "v1",
    "metadata": {
      "name": "testapp-69569dc589-p7z29",
      "generateName": "testapp-69569dc589-",
      "namespace": "testapp",
      "selfLink": "/api/v1/namespaces/testapp/pods/testapp-69569dc589-p7z29",
      "uid": "38c06595-4d86-4f94-835f-7365426f72d3",
      "resourceVersion": "258133",
      "creationTimestamp": "2020-11-12T07:01:08Z",
      "labels": {
        "app.kubernetes.io/instance": "testapp",
        "app.kubernetes.io/name": "testapp",
        "app.kubernetes.io/namespace": "testapp",
        "pod-template-hash": "69569dc589"
      },
      "annotations": {
        "kubernetes.io/psp": "privileged"
      },
      "ownerReferences": [
        {
          "apiVersion": "apps/v1",
          "kind": "ReplicaSet",
          "name": "testapp-69569dc589",
          "uid": "a282942f-b901-4844-8251-a79343e20a8e",
          "controller": true,
          "blockOwnerDeletion": true
        }
      ],
      "managedFields": [
        {
          "manager": "kube-controller-manager",
          "operation": "Update",
          "apiVersion": "v1",
          "time": "2020-11-12T07:01:08Z",
          "fieldsType": "FieldsV1",
          "fieldsV1": {
            "f:metadata": {
              "f:annotations": {
                ".": {},
                "f:kubernetes.io/psp": {}
              },
              "f:generateName": {},
              "f:labels": {
                ".": {},
                "f:app.kubernetes.io/instance": {},
                "f:app.kubernetes.io/name": {},
                "f:app.kubernetes.io/namespace": {},
                "f:pod-template-hash": {}
              },
              "f:ownerReferences": {
                ".": {},
                "k:{\"uid\":\"a282942f-b901-4844-8251-a79343e20a8e\"}": {
                  ".": {},
                  "f:apiVersion": {},
                  "f:blockOwnerDeletion": {},
                  "f:controller": {},
                  "f:kind": {},
                  "f:name": {},
                  "f:uid": {}
                }
              }
            },
            "f:spec": {
              "f:containers": {
                "k:{\"name\":\"testapp\"}": {
                  ".": {},
                  "f:image": {},
                  "f:imagePullPolicy": {},
                  "f:livenessProbe": {
                    ".": {},
                    "f:failureThreshold": {},
                    "f:initialDelaySeconds": {},
                    "f:periodSeconds": {},
                    "f:successThreshold": {},
                    "f:tcpSocket": {
                      ".": {},
                      "f:port": {}
                    },
                    "f:timeoutSeconds": {}
                  },
                  "f:name": {},
                  "f:ports": {
                    ".": {},
                    "k:{\"containerPort\":8080,\"protocol\":\"TCP\"}": {
                      ".": {},
                      "f:containerPort": {},
                      "f:name": {},
                      "f:protocol": {}
                    }
                  },
                  "f:readinessProbe": {
                    ".": {},
                    "f:failureThreshold": {},
                    "f:initialDelaySeconds": {},
                    "f:periodSeconds": {},
                    "f:successThreshold": {},
                    "f:tcpSocket": {
                      ".": {},
                      "f:port": {}
                    },
                    "f:timeoutSeconds": {}
                  },
                  "f:resources": {
                    ".": {},
                    "f:limits": {
                      ".": {},
                      "f:cpu": {},
                      "f:memory": {}
                    },
                    "f:requests": {
                      ".": {},
                      "f:cpu": {},
                      "f:memory": {}
                    }
                  },
                  "f:securityContext": {
                    ".": {},
                    "f:runAsNonRoot": {},
                    "f:runAsUser": {}
                  },
                  "f:terminationMessagePath": {},
                  "f:terminationMessagePolicy": {}
                }
              },
              "f:dnsPolicy": {},
              "f:enableServiceLinks": {},
              "f:restartPolicy": {},
              "f:schedulerName": {},
              "f:securityContext": {
                ".": {},
                "f:fsGroup": {}
              },
              "f:serviceAccount": {},
              "f:serviceAccountName": {},
              "f:terminationGracePeriodSeconds": {}
            }
          }
        }
      ]
    },
    "spec": {
      "volumes": [
        {
          "name": "testapp-token-jcq64",
          "secret": {
            "secretName": "testapp-token-jcq64",
            "defaultMode": 420
          }
        }
      ],
      "containers": [
        {
          "name": "testapp",
          "image": "private-registry/testapp/helloworld:1.0",
          "ports": [
            {
              "name": "http",
              "containerPort": 8080,
              "protocol": "TCP"
            }
          ],
          "resources": {
            "limits": {
              "cpu": "100m",
              "memory": "128Mi"
            },
            "requests": {
              "cpu": "50m",
              "memory": "20Mi"
            }
          },
          "volumeMounts": [
            {
              "name": "testapp-token-jcq64",
              "readOnly": true,
              "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
            }
          ],
          "livenessProbe": {
            "tcpSocket": {
              "port": 8080
            },
            "initialDelaySeconds": 30,
            "timeoutSeconds": 15,
            "periodSeconds": 30,
            "successThreshold": 1,
            "failureThreshold": 5
          },
          "readinessProbe": {
            "tcpSocket": {
              "port": 8080
            },
            "initialDelaySeconds": 5,
            "timeoutSeconds": 15,
            "periodSeconds": 5,
            "successThreshold": 1,
            "failureThreshold": 30
          },
          "terminationMessagePath": "/dev/termination-log",
          "terminationMessagePolicy": "File",
          "imagePullPolicy": "IfNotPresent",
          "securityContext": {
            "runAsUser": 101,
            "runAsNonRoot": true
          }
        }
      ],
      "restartPolicy": "Always",
      "terminationGracePeriodSeconds": 30,
      "dnsPolicy": "ClusterFirst",
      "serviceAccountName": "testapp",
      "serviceAccount": "testapp",
      "securityContext": {
        "fsGroup": 101
      },
      "schedulerName": "default-scheduler",
      "tolerations": [
        {
          "key": "node.kubernetes.io/not-ready",
          "operator": "Exists",
          "effect": "NoExecute",
          "tolerationSeconds": 300
        },
        {
          "key": "node.kubernetes.io/unreachable",
          "operator": "Exists",
          "effect": "NoExecute",
          "tolerationSeconds": 300
        }
      ],
      "priority": 0,
      "enableServiceLinks": true
    },
    "status": {
      "phase": "Pending",
      "qosClass": "Burstable"
    }
  },
  "requestReceivedTimestamp": "2020-11-12T07:01:08.140301Z",
  "stageTimestamp": "2020-11-12T07:01:08.147353Z",
  "annotations": {
    "authorization.k8s.io/decision": "allow",
    "authorization.k8s.io/reason": "RBAC: allowed by ClusterRoleBinding \"system:controller:replicaset-controller\" of ClusterRole \"system:controller:replicaset-controller\" to ServiceAccount \"replicaset-controller/kube-system\"",
    "podsecuritypolicy.policy.k8s.io/admit-policy": "privileged",
    "podsecuritypolicy.policy.k8s.io/validate-policy": "privileged"
  }
}
```

Controller manager does have a log complaining about some mutation.
```
I1112 07:44:08.871501       1 deployment_controller.go:485] Error syncing deployment testapp/testapp: Operation cannot be fulfilled on deployments.apps "testapp": the object has been modified; please apply your changes to the latest version and try again
```
I also checked if I am following the document for PSP and inline with it.
We do have one more PSP for nginx ingress which works well because it is bound to ingress namespace individually, now we are trying the restricted PSP to bound by default to all namespaces and created cluster role and clusterrole binding for that purpose. The pivileged PSP on other hand has no clusterrole but only roles bound to individual namespace that needs it, still when a pod is spun in a new namespace it gets assigned with privileged PSP without RBAC supporting it, so, it seems like the whole authorization part is skipped.
Also, to ensure authorization is not skipped our control plane components runs on secure addresses.

Don't know where else to look into.

**Environment**: DEV
- Kubernetes version (use `kubectl version`): 1.18.10
- Cloud provider or hardware configuration: none
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`):  3.10.0-1127.19.1.el7.x86_64
- Install tools: 
- Network plugin and version (if this is a network-related bug): Calico
- Others:
