### ISSUE TITLE
Implement container log back-pressure mechanism 

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes/kubernetes#96567]
If you have a kubernetes cluster with log collection enabled and you deploy the following:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-fire-hose
  labels:
    app: log-fire-hose
spec:
  replicas: 100
  selector:
    matchLabels:
      app: log-fire-hose
  template:
    metadata:
      labels:
        app: log-fire-hose
    spec:
      containers:
      - name: log-fire-hose
        image: ubuntu:latest
        command:
        - /bin/bash
        - -c
        - yes ciao
```
You will break the log system. If it doesn't break increase the pod count until it does. The point here is that the developer that deployed that app did not do anything illegitimate yet it has the power of taking down part of the system.

So, let's analyse what is going on:

1. an application that creates a fire-hose of logs is deployed. In real life, this is maybe due to a developer leaving the log setting to debug in production or because a malicious agent is trying to mound a DoS attack to the log system. There is no way in Kubernetes today to control the amount of logs created by an app (more about that later). 
2. log collection systems normally are based on a push model. So as logs are produced they are pushed by the nodes to the log collection system. When the aggregated amount of logs being pushed exceeds the ingest capacity of the log collection systems something starts to break.

Push-based systems are generally vulnerable to these kinds of situations where the amount of stuff being pushed exceeds the ingestion capacity of the receiving system and the general solution to this issue is to implement a back pressure mechanism. 

There does not seem to be a standard back pressure mechanism for log collection systems and arguably there never be: When this issue arises a quick solution to this problem is to build a larger log collection system, which is in the interested of the log collection system vendors.

For that reason, I invite this community to design and implement a log back-pressure solution that is agnostic of the log collection system implementation/product.

One possibility could be the illustrated by the following example: Let's say we know the ingest capacity of the log collection system (X) and we have n nodes, the SRE could assign to each node a Y=X/n log production capacity. So, there is a new feature that allows to lock-in the log production capacity of the container runtime (potentially surfaced at the CRI level).
As a developer, I am given the choice to decide what happens to my logs when the node on which my container is running is at capacity. I can chose to wait for the log to be shipped (and slow down my app) or I can chose to drop my log statements.

This would be enough protect the log collection system from the application gone haywire, but still does not protect tenants running on the same node of the application gone haywire.

A further improvement could be to manage the log production capacity as a container resource (same as CPU and memory). Some further analysis would be needed here to map each QoS to a log management behavior (wait or drop).

Some initial work in this space was also discussed here: https://github.com/containers/conmon/issues/84
