### ISSUE TITLE
[Failing Test] [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for CRD preserving unknown fields in an embedded object [Conformance] (ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts)

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#96577]
**Which jobs are failing**:
`ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts`

**Which test(s) are failing**:
`[sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for CRD preserving unknown fields in an embedded object [Conformance]`
There is another issue #96055 for the other failing tests

**Since when has it been failing**:
https://github.com/kubernetes-sigs/cluster-api-provider-gcp/compare/7a53ab5f1...2f98888b6 but that seems unrelated
Nov 12 7AM PST

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-v1alpha3-k8s-master

**Reason for failure**:
Looking at this particular test it looks like #96369 introduces the `"a":null` in [`crd_publish_openapi.go`](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/crd_publish_openapi.go) that this test seems to be struggling with

```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
Nov 12 21:01:53.236: failed to create random CR {"kind":"E2e-test-crd-publish-openapi-1604-crd","apiVersion":"crd-publish-openapi-test-unknown-in-nested.example.com/v1","metadata":{"name":"test-cr"},"spec":{"a":null,"b":[{"c":"d"}]}} for CRD that allows unknown properties in a nested object: error running /home/prow/go/src/k8s.io/kubernetes/_output/bin/kubectl --server=https://34.120.129.82:443 --kubeconfig=/tmp/kubeconfig --namespace=crd-publish-openapi-8616 --namespace=crd-publish-openapi-8616 create -f -:
Command stdout:

stderr:
error: error validating "STDIN": error validating data: unknown object type "nil" in E2e-test-crd-publish-openapi-1604-crd.spec.a; if you choose to ignore these errors, turn validation off with --validate=false

error:
exit status 1
```

**Anything else we need to know**:
Example spyglass links:
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts/1326976422375329792
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts/1327037072438988800
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts/1327340295993430016

/sig api-machinery
/area provider-gcp
/priority important-soon
/cc @kubernetes/ci-signal @gautierdelorme

**Comment by liggitt** [comment]
/sig cluster-lifecycle

The last time I looked at these jobs, they were running tests from `master` against old server versions. That is unlikely to work well. cc @detiber

**Comment by gautierdelorme** [comment]
Yeah, this test is actually expected to fail on pre-1.20 server versions. I would recommend to run test from the branch matching the server version.

**Comment by RobertKielty** [comment]
OK so as far as I can tell from the job configuration in test-infra this should be running against the master branch (I could be wrong on that will return back with evidence either way ) 

@kubernetes/sig-testing do we have a way of selecting / deselecting conformance (or any) tests for inclusion on a run based on the k8s git ref that a CI job is running against?

**Comment by liggitt** [comment]
from the log of a [failed run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts/1328674596487958528):

```
+ echo 'deployed cluster:'
deployed cluster:
+ kubectl --kubeconfig=/tmp/kubeconfig version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.5-rc.0.1+454965f0238c49", GitCommit:"454965f0238c49f8135ea9f27895a0ebfaac52fb", GitTreeState:"clean", BuildDate:"2020-11-11T14:02:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

that indicates it is running tests against a 1.19.x cluster

**Comment by stevekuznetsov** [comment]
@RobertKielty how does this job select the version of e2e tests it's running in the first place? And how does it select the cluster version to run those tests against? I don't see that obviously in the job config:

```yaml
- name: ci-cluster-api-provider-gcp-make-conformance-v1alpha3-k8s-ci-artifacts
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decorate: true
  decoration_config:
    timeout: 3h
  interval: 4h
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-gcp
      base_ref: master
      path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
    - org: kubernetes-sigs
      repo: image-builder
      base_ref: master
      path_alias: "sigs.k8s.io/image-builder"
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
  spec:
    containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20201111-a263fd7-master
        env:
          - name: "BOSKOS_HOST"
            value: "boskos.test-pods.svc.cluster.local"
        command:
          - "runner.sh"
          - "./scripts/ci-e2e.sh"
          - "--use-ci-artifacts"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp, sig-release-master-informing
    testgrid-tab-name: capg-conformance-v1alpha3-k8s-master
    testgrid-alert-email: kubernetes-sig-cluster-lifecycle-cluster-api-alerts@googlegroups.com, release-team@kubernetes.io
    testgrid-num-failures-to-alert: "2"
```
