### ISSUE TITLE
Job not failing after backoffLimit is reached

### ISSUE THREAD

**Issue by yacinelazaar** [kubernetes/kubernetes#96630]
**What happened**:
I have the current job running that randomly fails or succeeds with completions set to 4 and no parallelism. Notice the backoffLimit here is 2:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  backoffLimit: 2
  completions: 4
  parallelism: 1
  template:
    spec:
      containers:
      - name: random-error
        image: busybox
        args:
        - bin/sh
        - -c
        - 'sleep 10; exit $(( ( RANDOM % 2 ) ));'
      restartPolicy: Never
```

So the job create multiple pods then fails:

```
Events:
  Type     Reason                Age    From            Message
  ----     ------                ----   ----            -------
  Normal   SuccessfulCreate      15m    job-controller  Created pod: test-job-cgwhn
  Normal   SuccessfulCreate      14m    job-controller  Created pod: test-job-96x9t
  Normal   SuccessfulCreate      14m    job-controller  Created pod: test-job-tqkmr
  Normal   SuccessfulCreate      13m    job-controller  Created pod: test-job-stzq2
  Normal   SuccessfulCreate      13m    job-controller  Created pod: test-job-z4z77
  Normal   SuccessfulCreate      12m    job-controller  Created pod: test-job-9m8fl
  Normal   SuccessfulCreate      11m    job-controller  Created pod: test-job-nj2ql
  Normal   SuccessfulCreate      10m    job-controller  Created pod: test-job-b82ts
  Normal   SuccessfulCreate      9m51s  job-controller  Created pod: test-job-llzs5
  Normal   SuccessfulCreate      8m22s  job-controller  Created pod: test-job-9mjtp
  Normal   SuccessfulCreate      7m36s  job-controller  Created pod: test-job-z4vnv
  Warning  BackoffLimitExceeded  6m43s  job-controller  Job has reached the specified backoff limit
```

But upon checking the created pods

```
ubuntu@master-0:~/tests$ k get po --sort-by=.metadata.creationTimestamp  
NAME             READY   STATUS      RESTARTS   AGE
test-job-cgwhn   0/1     Error       0          9m39s
test-job-96x9t   0/1     Error       0          9m13s
test-job-tqkmr   0/1     Completed   0          8m31s
test-job-stzq2   0/1     Completed   0          8m3s
test-job-z4z77   0/1     Error       0          7m29s
test-job-9m8fl   0/1     Completed   0          6m58s
test-job-nj2ql   0/1     Error       0          6m22s
test-job-b82ts   0/1     Error       0          5m6s
test-job-llzs5   0/1     Error       0          4m19s
test-job-9mjtp   0/1     Error       0          2m50s
test-job-z4vnv   0/1     Error       0          2m4s
```

I noticed that the job did not fail after making 2 failed retries but 4 (check the last 5 pods)

**What you expected to happen**:
Job to fail after 2 failed retries
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.3
- Cloud provider or hardware configuration: Local KVMs
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.4 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux master-0 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):  Weave
- Others:
