### ISSUE TITLE
Changes in Pod.spec.containers.ports aren't recognized by API server

### ISSUE THREAD

**Issue by Moser-ss** [kubernetes/kubernetes#96714]
**What happened**:

When I add a new port object to Pod.spec.containers.ports list that has the same value in the containerPort field that other port it will not update the Pod in the cluster

**What you expected to happen**:
I expect that a new port object was added to the port because when I create the pod from zero with 2 port objects that contained the same value in the containerPort the pod has the booth ports exposed 

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
#testpod-v1
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    name: testpod
spec:
  containers:
  - name: testpod
    image: nginx
    ports:
    - containerPort: 80
      name: main
```

```yaml
#testpod-v2
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    name: testpod
spec:
  containers:
  - name: testpod
    image: nginx
    ports:
    - containerPort: 80
      name: main
    - name: metrics
      containerPort: 80
```
Create initial pod with one port object
```shell
-> kubectl apply -f testpod-v1.yaml 
pod/testpod created
```
Update ports values 
```shell
->kubectl apply -f testpod-v2.yaml
pod/testpod configured
```
Check ports that are exposed
```shell
kubectl describe -f testpod-v2.yaml
```
**Anything else we need to know?**:
When I do kubectl apply -f testpod-v2.yaml --dry-run=server -o yaml  or kubectl apply -f testpod-v2.yaml --dry-run=client -o yaml the output doesn't show the change in the ports so I am not sure if it is an issue in the API our in the kubectl 
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
- Kernel (e.g. `uname -a`):
4.15.0-43-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by aojea** [comment]
it seems that 2 ports with the same port and different name can be created

```
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: testpod
    ports:
    - containerPort: 80
      name: main
      protocol: TCP
    - containerPort: 80
      name: metrics
      protocol: TCP

```

but if I read the API docs correctly it seems is not possible to be updated

> portsContainerPort arraypatch strategy: mergepatch merge key: containerPort | List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network. Cannot be updated.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#containerport-v1-core

@thockin can you confirm or correct me, please?
