### ISSUE TITLE
Non LoadBalancer Types can set Status.Loadbalancer.Ingress

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#96724]
**What happened**:

I can set the Status.LoadBalancer.Ingress in Services that are not Type LoadBalancer

**What you expected to happen**:

The apiserver should reject the Status update

**How to reproduce it (as minimally and precisely as possible)**:

1. kind create cluster
2. wget https://gist.githubusercontent.com/aojea/94e20cda0f4e4de16fe8e35afc678732/raw/a18045d651232c6d20a790503d1eba88c89cc5bc/lb_ingress.py
3. sudo pip install kubernetes
4. kubectl run test --image httpd --port 80
5. kubectl expose pod test
6. python lb_ingress.py default test 1.1.1.1
7. kubectl get services test -o yaml

```
  selfLink: /api/v1/namespaces/default/services/test
  uid: b799e259-c995-4a8a-aed9-df9bfa458f6f
spec:
  clusterIP: 10.97.81.50
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: test
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer:
    ingress:
    - ip: 1.1.1.1
```
