### ISSUE TITLE
Dynamic readiness probe period time

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#96731]
**What would you like to be added**:

I would like a way to have the readiness probe period more dynamic.

**Why is this needed**:

We have a few use cases were we want extremely aggressive readiness probe times, because pod startup time is critical. In these cases, using an interval over 1s is detrimental. This includes cases where we have a service mesh and do not want to be slower than pods that do not have a sidecar, and cases where we are running integration tests and we want pods to be able to come up extremely quickly to avoid long tests.

Currently, if we add aggressive readiness probes, it impacts the pod for the entire lifetime, adding load on the pod and kubelet. Instead, it would be useful to be able to probe aggressively until we are initially ready, then back off to a more reasonable probing period. I could also see a use case for changing this from "until we are initially ready" to "whenever we are not ready" - either would work.

**What I have tried**

Adding a startup probe:
```yaml
        readinessProbe:
          httpGet:
            path: /get
            port: 80
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        startupProbe:
          httpGet:
            path: /get
            port: 80
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
```

This doesn't impact things, pod still takes 60s to be marked ready

Artificial initial delay:
```
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /get
            port: 80
            scheme: HTTP
          initialDelaySeconds: 4
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
```

In this case, we are always too fast or too slow: if we get ready in under 4s, then we wasted (4-ready time) seconds to get ready. If we happen to take 4.1 seconds to get ready, we miss our window and are stuck not ready for 60 more seconds.

/sig node

**Comment by clarkmcc** [comment]
I'm proposing adding a field `FailedPeriodSeconds` to v1.Probe in #96788 which determine the probing period for any probe (readiness, liveness, or startup) whose previous probe failed. This would solve the OPs problem of an alternate probing period "whenever we are not ready". You'd be able to do something like

```yaml
readinessProbe:
    periodSeconds: 60
    failedPeriodSeconds: 1
```
which would result in checking for readiness every second until the container becomes ready, after which we'll check every 60 seconds. If at any point we fail readiness check, the container is removed from service load balancers and the probe runs every 1 second until the container becomes ready again.

**Comment by howardjohn** [comment]
Fantastic @clarkmcc, to me that seems like the ideal solution.

**Comment by matthyx** [comment]
> This doesn't impact things, pod still takes 60s to be marked ready

@howardjohn this is a bug and your combination of startupProbe and readinessProbe should provide the expected behavior.
Can you please give me the k8s version of your cluster and ensure you have the startupProbe feature enabled?

/assign

**Comment by howardjohn** [comment]
Exact reproducer:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: docker.io/kennethreitz/httpbin
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /get
            port: 80
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        startupProbe:
          httpGet:
            path: /get
            port: 80
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
```

```
$ k version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-rc.2", GitCommit:"27bb2a4a0a5cb8330178d19e57fa61fffa895c98", GitTreeState:"clean", BuildDate:"2020-07-21T17:39:35Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl get pods -w
NAME                       READY   STATUS              RESTARTS   AGE
httpbin-679f89b664-bjdlt   0/1     ContainerCreating   0          2s
httpbin-679f89b664-bjdlt   0/1     Running             0          11s
httpbin-679f89b664-bjdlt   0/1     Running             0          13s
httpbin-679f89b664-bjdlt   1/1     Running             0          67s
```

**Comment by howardjohn** [comment]
No, its not always 60s. I would agree that is likely the cause.

**Comment by matthyx** [comment]
Do you really need the readinessProbe? Its primary use case now that we have the startupProbe is to remove the pod from the pool if it fails...
If you don't specify one, the pod will be `Ready` just after the startupProbe succeeds and thus reachable through the service.

**Comment by howardjohn** [comment]
Yes, I do think we still need it, as its useful to know if the pod becomes not-ready later in life. We just want to probe this every ~60s or so, but probe every 1s at startup

**Comment by matthyx** [comment]
Sure, but what should be done if the probe fails later in life?
If you need to restart the container, better use a livenessProbe.
`Ready` state is also set to false when the pod is stopping... so IMHO you could do without the readinessProbe.
So, again, apart from a scenario where you need to give some breathing time to your container, readinessProbe has little use nowadays.

**Comment by matthyx** [comment]
If you just want to "monitor" your pod status, I suggest you use Prometheus for that...

**Comment by howardjohn** [comment]
I think readiness probe is still pretty useful when a pod may temporarily be unable to serve traffic so we want to remove it from the pool. AFAIK that is the original use case:

> Sometimes, applications are temporarily unable to serve traffic. For example, an application might need to load large data or configuration files during startup, or depend on external services after startup. In such cases, you don't want to kill the application, but you don't want to send it requests either. Kubernetes provides readiness probes to detect and mitigate these situations. A pod with containers reporting that they are not ready does not receive traffic through Kubernetes Services.

**Comment by howardjohn** [comment]
Also, while I feel like this issue is widely applicable, my real use case is for service mesh sidecars, which have vastly different requirements from a normal app pod. Liveness probes are not really viable, as while the sidecar container is getting killed there will be a complete outage on the pod, and monitoring with prometheus does not fill the same niche

**Comment by matthyx** [comment]
Please be aware that pods not ready are still counting in the replicaset... So if all your pods have failed their readinessProbe nobody will answer your requests.
There are other (better) ways to provide real backpressure in your system.

**Comment by howardjohn** [comment]
@matthyx if using readiness probes is wrong, then should the documentation be updated to discourage their usage?

**Comment by matthyx** [comment]
Now that 1.20 is around the corner... Yes I should definitely consider rewriting this part of the documentation, correct.

**Comment by howardjohn** [comment]
SGTM. I would agree for most use cases startup+liveness probe is probably better.

However, I feel that service mesh cases are in a unique position where liveness probes don't make much sense. If we kill the sidecar container, the main app container will experience downtime. In a normal app, it will terminate, so it will stop sending traffic (since its SIGTERM'd) and stop receiving traffic (due to removal from Endpoints).

**Comment by matthyx** [comment]
Yes, side-cars are particular and there is currently a wip document circulating in sig-node about improvements in their lifetime cycles.

**Comment by howardjohn** [comment]
I am familiar with these designs, and I think this issue is actually even more important with the proposed changes, as any delay to the startup of the sidecar will slow the app from starting. So, for example, if we have a 30s readiness probe period, the application container is delayed by `rand * 30s`

**Comment by matthyx** [comment]
@howardjohn do you think something like that could help?
https://github.com/kubernetes/kubernetes/compare/master...matthyx:96731

**Comment by howardjohn** [comment]
I may be misunderstanding, but I think it will end up looking like
```go
jitter := 30s // some random value from 0-60
if jitter > time.Since(w.probeManager.start) { //  is likely very small the first time, so this is true
  sleep(30s)
}
```

So we would see the same behavior? I may be understanding it wrong though.

**Comment by matthyx** [comment]
Yes, right, I wanted to put inside start the startup time of the kubelet, not the probeManager...

**Comment by howardjohn** [comment]
Is that logic hit only after startup probe succeeds or in parallel?

If it's after startup probe then seems viable, as would define 1s startup probe and 30s readiness probe.

**Comment by matthyx** [comment]
@howardjohn that wasn't sufficient because the probe ticker starts with the prober... so we have to wait for the end of the cycle to run the readinessProbe.
I have updated my branch to include a manual run of the readinessProbe just after the `started` state, and it works!
Look at the result on my kind cluster (using exactly your deployment spec):
```
deployment.apps/httpbin created
NAME                       READY   STATUS              RESTARTS   AGE
httpbin-679f89b664-7h9ps   0/1     ContainerCreating   0          0s
httpbin-679f89b664-7h9ps   0/1     Running             0          2s
httpbin-679f89b664-7h9ps   0/1     Running             0          3s
httpbin-679f89b664-7h9ps   1/1     Running             0          3s
```

**Comment by matthyx** [comment]
If that LGTY I can submit a PR and we (hopefully) can see this in the 1.21 release... I am not sure it qualifies for a 1.20 cherrypick though.

**Comment by howardjohn** [comment]
Looks great, that is exactly the behavior I was hoping for!

**Comment by matthyx** [comment]
@howardjohn let's have it merged then 👍

**Comment by cagataygurturk** [comment]
> readinessProbe has little use nowadays.

@matthyx could you elaborate? During the normal lifecycle of a Pod, the Pod may still enter to unready status. Imagine a scenario where readiness probe of the application also checks whether other dependencies (Databases etc.) are also available or not. In fact, we use this readiness signal to trigger an automated failover to other clusters in case there is no ready pod of a replicaset.

**Comment by matthyx** [comment]
@cagataygurturk in general, using external dependencies in a readinessProbe is an antipattern, please check https://learnk8s.io/production-best-practices
If that works for you, that's ok, however it could bite you in some circumstances.
I really think the only valid use case for a readinessProbe is now an application state that could solve itself, and even then it might cause issues as the number of unready pods isn't taken into account in a replicaSet.

**Comment by cagataygurturk** [comment]
With full respect, I think declaring this usage as antipattern is a bold statement. If the folks architecting a system thinks that a Pod shouldn‘t receive traffic when an external dependency of this Pod is not available, let it be so. The use case I have described is exactly what the documentation cited above is also suggesting and I have witnessed so many good scenarios where readiness works very well when they are used together with external dependencies. I would personally not like seeing readiness probe being deprecated one day. (Which is the sentiment I have felt in this thread)

**Comment by matthyx** [comment]
> I would personally not like seeing readiness probe being deprecated one day. (Which is the sentiment I have felt in this thread)

Sorry for the bad communication, no probe is going away, we need the 3 to cover all use cases :-)

I just wanted to highlight that in most cases you should do differently than rely on probe, such as:
- crash the container instead of relying on livenessProbe
- use backpressure instead of relying on readinessProbe to protect a probe from excessive traffic
- use a technology starting instantly instead of relying on startupProbe to wait

**Comment by diemus** [comment]
kubernetes version: v1.17.13

same problem, I need the readinessProbe run immediately after the container has started,  but it's not.
and I also observed another problem, the startupProbe does not work like liveness probe, it wait 60s+ to trigger the the killing process

```yaml
- command:
  - /bin/sh
  - -c
  - sleep 300 && python -m SimpleHTTPServer 8080
  - 2>&1
 livenessProbe:
    failureThreshold: 3
    periodSeconds: 1
    successThreshold: 1
    tcpSocket:
      port: 8080
    timeoutSeconds: 1
  readinessProbe:
    failureThreshold: 3
    periodSeconds: 1
    successThreshold: 1
    tcpSocket:
      port: 8080
    timeoutSeconds: 1
  startupProbe:
    failureThreshold: 3
    periodSeconds: 1
    successThreshold: 1
    tcpSocket:
      port: 8080
    timeoutSeconds: 1
```

Type|Reason|Age|From|Message
-- | -- | -- | -- | --
Normal | Started | 2021/1/13 a2:19:18 | kubelet,xxxx | Started container nginx
Warning | Unhealthy | 2021/1/13 a2:19:20 | kubelet,xxxx | Startup probe failed: dial tcp 10.xxx.xxx.xxx:8080: connect: connection refused
Normal | Killing | 2021/1/13 a2:20:29 | kubelet,xxxx | Container nginx failed startup probe, will be restarted

you could see after the startup probe failed(3s), it wait 69s to trigger the the killing process.
if I remove the startupProbe, the killing process will be trigger as soon as the liveness fail(3s), which works as expected.

Type|Reason|Age|From|Message
-- | -- | -- | -- | --
Normal | Started | 2021/1/13 12:30:28 | kubelet,xxxx | Started container nginx
Warning | Unhealthy | 2021/1/13 12:30:29 | kubelet,xxxx | Readiness probe failed: dial tcp 10.xxx.xxx.xxx:8080: connect: connection refused
Warning | Unhealthy | 2021/1/13 12:30:29 | kubelet,xxxx | Liveness probe failed: dial tcp 10.xxx.xxx.xxx:8080: connect: connection refused
Normal | Killing | 2021/1/13 12:30:31 | kubelet,xxxx | Container nginx failed liveness probe, will be restarted

is this behavior a bug?
