### ISSUE TITLE
Kubelet return error when device plugin set PreStartRequired option true but container request 0 resource.

### ISSUE THREAD

**Issue by fighterhit** [kubernetes/kubernetes#96779]
**What happened**:
When I register a device plugin and set the `PreStartRequired` option in `DevicePluginOptions` true, then when I create a pod and specify this resource as 0 in yaml, an error will be reported. Examples are as follows.

- The request to register the device plugin
```golang
req := &pluginapi.RegisterRequest{
  Version:      pluginapi.Version,
  Endpoint:     SocketPath,
  ResourceName: myResourceName
  Options:      &pluginapi.DevicePluginOptions{PreStartRequired: true},
}
```
- A pod yaml with the resource 0
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  namespace: pod-namespace
spec:
  containers:
    - image: image-name
      name: container-name
      resources:
        limits:
          myResourceName: 0
```
- kubelet return error
```error
no devices found allocated in local cache for pod xxx, container xxx, resource myResourceName ...
```

**What you expected to happen**:

I think when the kubelet calls `callPreStartContainerIfNeeded`, the resource value should be checked. If it is 0, the `PreStartContainer` step should be skipped to avoid errors.

**How to reproduce it (as minimally and precisely as possible)**:

- Register a device plugin which set `PreStartRequired` option is true
- Create a pod with the above resource 0 

**Anything else we need to know?**:

In fact, when the amount of requested resources is 0, devicemanager will get the number of allocated devices as nil, resulting in the internal `podDevices` cache not storing the application resource information corresponding to the container. 
https://github.com/kubernetes/kubernetes/blob/ece591f7226696790cd27a4386b128082b268462/pkg/kubelet/cm/devicemanager/manager.go#L852-L858

But if `PreStartRequired` is set to true at the same time, then devicemanager will check podDevices cache. 
https://github.com/kubernetes/kubernetes/blob/ece591f7226696790cd27a4386b128082b268462/pkg/kubelet/cm/devicemanager/manager.go#L976-L980

The two processing steps contradict each other so it will return an error.
