### ISSUE TITLE
large latency in pod network operations when NodePort services with a lot of ports are created  

### ISSUE THREAD

**Issue by daniel-ke** [kubernetes/kubernetes#96786]
**What happened**:
In an kubadm generated IPV4/IPV6 dual Stack cluster ( 3 control plane nodes with taint removed to allow pod execution - each node has 2 core/16G mem/100G disk)

As required by our use case, created a number of services (21) with 4 services (2 ipv4 and 2 ipv6) each containing 80 nodePorts (with externalTrafficPolicy: Local) as well as associated deployments and daemonsets ( 36 pods across 18 deployments/daemonsets).

For any pods created **after** the deployment of the 4 services -we see significantly increased latency (20 ms) in stateless pod network connections including external access, pod to pod, or localhost access when all 4 services deployed.

If only 2 of the 80 port services are deployed, performance is almost as expected for a pod (which 2 deployed is any combination of the services - i.e. not significant) but of course the system use case is not met as the nodePorts are required for our external load balancer setup.

This occurs in all pods created after the services are created, including pods not associated with the services. It affects access on localhost or external access. 

Ultimately, it results in a slower k8s system compared to an equivalent non containerised setup ( this is how the latency was first discovered ).
  
**What you expected to happen**:

Minimal latency between pods created after service deployment ( localhost access slowdown is particularly surprising ) and a k8s system that performs comparably to the equivalent non containerised setup.

**How to reproduce it (as minimally and precisely as possible)**:

Could reproduce it in a minimal single control plane/worker setup dual stack ipv4/ipv6 by doing this: -

In an 'empty' cluster consisting in this example of a single control plane/worker nodes

Create  2 ipv4 and 2 ipv6 NodePort services with in total lot of ports e.g. at least 320 in total , in the following config style : -
e.g.
```
apiVersion: v1
kind: Service
metadata:
  name: some-name
spec:
  type: NodePort
  selector:
    some-label: some-value
  ports:
  - name: port-<unique name1>
    port: 4708
    targetPort: 4708
    nodePort: 30001
    protocol: TCP

... multiple different ports - at least 80

  externalTrafficPolicy: Local
```
with source ip tracking: -
`externalTrafficPolicy: Local`

Then create a pod with network ability - even an unrelated pod to the service  e.g.
```
apiVersion: v1
kind: Pod
metadata:
  name: centos-latency-test
spec:
  hostNetwork: false
  containers:
  - name: centos
    image: centos:7
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```
connect to the pod and listen on a localhost port
```
$ kubectl exec -it centos-latency-test -- /bin/bash
root@centos-latency-test # yum install -y nc telnet net-tools
root@centos-latency-test # nc -lkv -p 4000
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Listening on :::4000
Ncat: Listening on 0.0.0.0:4000
```
connect on another session and time a telnet (or use an nc call) to the localport. Note: - the 30ms latency (+ additional normal latency) also occurs for any external access also, between pods or to an external network - its just clear there is an issue if localhost is taking 30ms to respond.
```
$ kubectl exec -it centos-latency-test -- /bin/bash
root@centos-latency-test # time telnet localhost 4000 < /dev/null
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

real	0m0.036s
user	0m0.018s
sys	0m0.002s
```

**Anything else we need to know?**:

The issue occurs regardless of whether pods/deployments/daemonsets have resource requests/limits defined.

If the pod is created **before** the large port services are created, the performance is nearer to expectation
```
real	0m0.006s
user	0m0.001s
sys	0m0.002s
```
If we reduce the services to just using 2 of the 80 port services, performance is better
```
real	0m0.013s
user	0m0.007s
sys	0m0.002s
```
If we create two pods in the minimal cluster and leave both deployed, one before creating the services and one after, the first pod performs with low latency and the one created after has high latency. 

The same behaviour was reproduced in our on premises VMWare environment, and on a cluster setup in the AWS EC2 cloud. It was reproduced in a 3 control plane/worker cluster,  a single  control plane/worker cluster, and a cluster with one control plane and 3 separate workers.

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.19.2
- Cloud provider or hardware configuration:
VMWare and AWS EC2
- OS (e.g: `cat /etc/os-release`):
Red Hat Enterprise Linux Server release 7.8 (Maipo) - on VMWare
CentOS Linux 7 (Core) - on AWS EC2
- Kernel (e.g. `uname -a`):
Linux 3.10.0-1127.10.1.el7.x86_64 #1 SMP Tue May 26 15:05:43 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux  (VMWare)
Linux ip-172-31-23-92.eu-west-2.compute.internal 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (AWS ECS)
- Install tools:
kubadm v1.19.2 kubectl v1.19.2
- Network plugin and version (if this is a network-related bug):
calico v3.16.3
- Others:
