### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#96832]
**What happened**:
Run scheduler's integration test [scheduler_perf](https://github.com/kubernetes/kubernetes/tree/master/test/integration/scheduler_perf), create a case for preemption with pod PV, 

e.g. 
```yaml
- name: PreemptionPV
  workloadTemplate:
  - opcode: createNodes
    countParam: $initNodes
  - opcode: createPods
    countParam: $initPods
    podTemplatePath: config/pod-low-priority.yaml
  - opcode: createPods
    countParam: $measurePods
    podTemplatePath: config/pod-high-priority.yaml
    persistentVolumeTemplatePath: config/pv-aws.yaml
    persistentVolumeClaimTemplatePath: config/pvc.yaml
    collectMetrics: true
  workloads:
  - name: 500Nodes
    params:
      initNodes: 500
      initPods: 2000
      measurePods: 500
  - name: 5000Nodes
    params:
      initNodes: 5000
      initPods: 20000
      measurePods: 5000
```

The testcase will corrupt with below exception,

```
fatal error: concurrent map writes

goroutine 132143 [running]:
runtime.throw(0x48d4bd0, 0x15)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0016ab848 sp=0xc0016ab818 pc=0x439792
runtime.mapassign_faststr(0x3ffaec0, 0xc00e505200, 0xc0075b07d4, 0xc, 0x1)
        /usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc0016ab8b0 sp=0xc0016ab848 pc=0x416511
k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding.(*VolumeBinding).Filter(0xc005428db0, 0x50f6ca0, 0xc00629f200, 0xc00dde5890, 0xc01273b000, 0xc01360b290, 0x0)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:209 +0x32b fp=0xc0016ab9a8 sp=0xc0016ab8b0 pc=0x246434b
k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).runFilterPlugin(0xc00448c4e0, 0x50f6ca0, 0xc00629f200, 0x7f88601a25e0, 0xc005428db0, 0xc00dde5890, 0xc01273b000, 0xc01360b290, 0x0)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/framework/runtime/framework.go:556 +0x87 fp=0xc0016aba20 sp=0xc0016ab9a8 pc=0x22d5087
```

Run the test with "-race" will reveal there is data race, 
```
WARNING: DATA RACE
Write at 0x00c00b93b350 by goroutine 1949:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:202 +0x0
  k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding.(*VolumeBinding).Filter()
      /go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:209 +0x6f3
  k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).runFilterPlugin()
      /go/src/k8s.io/kubernetes/pkg/scheduler/framework/runtime/framework.go:556 +0x91
  k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).RunFilterPlugins()
      /go/src/k8s.io/kubernetes/pkg/scheduler/framework/runtime/framework.go:535 +0x12e
  k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*preemptHandle).RunFilterPlugins()
      <autogenerated>:1 +0xa1
  k8s.io/kubernetes/pkg/scheduler/core.PodPassesFiltersOnNode()
      /go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:500 +0x176
  k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.selectVictimsOnNode()
      /go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:629 +0x4f3
  k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.dryRunPreemption.func1()
      /go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:321 +0x208
  k8s.io/client-go/util/workqueue.ParallelizeUntil.func1()
      /go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:90 +0xe7

Previous write at 0x00c00b93b350 by goroutine 1803:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:202 +0x0
  k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding.(*VolumeBinding).Filter()
      /go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:209 +0x6f3
  k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).runFilterPlugin()
      /go/src/k8s.io/kubernetes/pkg/scheduler/framework/runtime/framework.go:556 +0x91
  k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).RunFilterPlugins()
      /go/src/k8s.io/kubernetes/pkg/scheduler/framework/runtime/framework.go:535 +0x12e
  k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*preemptHandle).RunFilterPlugins()
      <autogenerated>:1 +0xa1
  k8s.io/kubernetes/pkg/scheduler/core.PodPassesFiltersOnNode()
      /go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:500 +0x176
  k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.selectVictimsOnNode()
      /go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:629 +0x4f3
  k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.dryRunPreemption.func1()
      /go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:321 +0x208
  k8s.io/client-go/util/workqueue.ParallelizeUntil.func1()
      /go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:90 +0xe7
```

**What you expected to happen**:
sucessfully.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-alsologtostderr=false -logtostderr=false -run=^$$ -benchtime=1ns -bench=BenchmarkPerfScheduling/PreemptionPV/500Nodes/2000InitPods/500PodsToSchedule"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig scheduling
/sig testing
/assign
