### ISSUE TITLE
GCP/GKE/Load Balancer : verify loadBalancerIP format

### ISSUE THREAD

**Issue by tpoindessous** [kubernetes/kubernetes#96909]
**What would you like to be added**:
Hi,

in GKE, I just discovered an error I made : 

```
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  labels:
    k8s-app: ingress-nginx
spec:
  loadBalancerIP: "x.y.x.y "
```

I pasted a whitespace at the end of the IP and I got no error from kubectl and no error from GKE Web Console.
But when I do 
```
kubectl -n ingress-controllers describe services ingress-nginx
Events:
  Type     Reason                  Age                From                Message
  ----     ------                  ----               ----                -------
  Warning  SyncLoadBalancerFailed  11s (x2 over 17s)  service-controller  Error syncing load balancer: failed to ensure load balancer: requested ip "x.y.x.y " is neither static nor assigned to the LB
  Normal   EnsuringLoadBalancer    1s (x3 over 19s)   service-controller  Ensuring load balancer

```
I discovered my error.

**Why is this needed**:
I would like to have : 
* an error when I pushed `kubectl apply`
* or an error on the GKE Web Interface

Thanks !
