### ISSUE TITLE
[Failing Job] periodic-kubernetes-bazel-test-1-20

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#97025]
**Which jobs are failing**:
- periodic-kubernetes-bazel-test-1-20

**Which test(s) are failing**:
- N/A, job is hitting error state with "Pod pending timeout"

**Since when has it been failing**:
- Since the job was created
- First failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-1-20/1333921882407178240
- Latest failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-1-20/1334250456037199872

**Testgrid link**:
- https://testgrid.k8s.io/sig-release-1.20-blocking#bazel-test-1.20

**Reason for failure**:
- TBD

**Anything else we need to know**:

**Comment by spiffxp** [comment]
/sig testing
job owner
/sig release
created the 1.20 jobs

**Comment by spiffxp** [comment]
- sample failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-1-20/1334245926977409024
- "pod pending timeout"
- look at podinfo.json in artifacts: https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-1-20/1334245926977409024/podinfo.json
- search for containerStatuses 
```
'name": "test",
					"state": {
						"waiting": {
							"reason": "ErrImagePull",
							"message": "rpc error: code = Unknown desc = failed to resolve image \"gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:v20201028-8000225-kubernetes-1.20\": no available registry endpoint: gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:v20201028-8000225-kubernetes-1.20 not found"
						}
					},
```
- So `gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:v20201028-8000225-kubernetes-1.20` is missing
- What is in the repo instead?
```
# gcloud container images list-tags gcr.io/k8s-testimages/launcher.gcr.io/google/bazel
2519256e13ca  latest-kubernetes-master,v20201028-8000225-kubernetes-master  2020-10-28T16:34:46
```
- So this image wasn't built. Should it have been? There are no branch-specific tags (other than master)
- Let's compare the 1.20 job config to the 1.19 job config and the master job config for periodic-kubernetes-bazel-test
```
# config/jobs/kubernetes/sig-release/release-branch-jobs/1.19.yaml
command:
      - ../test-infra/hack/bazel.sh
      image: gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:2.2.0-from-0.23.2
# config/jobs/kubernetes/sig-release/release-branch-jobs/1.20.yaml
command:
      - ../test-infra/hack/bazel.sh
      image: gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:v20201028-8000225-kubernetes-1.20
# config/jobs/kubernetes/sig-testing/bazel-build-test.yaml
containers:
    - image: gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:v20201028-8000225-kubernetes-master
```
- I suspect this is config-forker doing a s/master/1.20
- So again, should we have a branch-specific image? What builds this image?
- Looks like kubernetes/test-infra/images/bazel/cloudbuild.yaml
- There is a variants.yaml file
```
kubernetes:
    CONFIG: kubernetes-master # Used by the kubernetes repo master branch
    NEW_VERSION: 3.4.1
    OLD_VERSION: 2.2.0
```
- If we want to make a branch-specific image, here's where
- Looks like all other release-branch jobs use the `2.2.0-from-0.23.2` tag
