### ISSUE TITLE
Pod stuck in terminating when subPath was deleted in azure fileshare

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes/kubernetes#97031]
**What happened**:
I was running the subpath testsuite against Azurefile.
This test failed and can be easily reproduced:
`should be able to unmount after the subpath directory is deleted [LinuxOnly]`

Basically what this test does is:

1. Create a PVC use azurefile
2. Create a pod that has two containers. One of it mounts the volume itself. The second container mounts the subpath of the volume.
3. Delete the subpath dir from the container that has the whole volume
4. Delete the pod, the pod will stuck in terminating status and cannot be cleaned up other than `--force`

**What you expected to happen**:
The pod can be deleted successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create the pvc
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi
```

2. Create the pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-azurefile
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container-parent
    image: docker.io/library/busybox:1.29
    securityContext:
      privileged: true
    command: ['sh', '-c', 'while true; do echo The app is running! && sleep 3600; done']
    volumeMounts:
    - name: test-volume
      mountPath: /test-volume
  - name: myapp-container-subpath
    image: docker.io/library/busybox:1.29
    securityContext:
      privileged: true
    command: ['sh', '-c', 'while true; do echo The app is running! && sleep 3600; done']
    volumeMounts:
    - name: test-volume
      mountPath: /test-volume
      subPath: provisioning
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: test-volume-pvc
```

3. delete the subpath dir from the parent pod
```
$ kubectl exec -it myapp-pod-azurefile --container myapp-container-parent -- /bin/bash rm -r /test-volume/provisioning
```

4. delete the pod
```
$ kubectl delete pod myapp-pod-azurefile
```

**Anything else we need to know?**:
The volume is being formatted as cifs type

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.6
- Cloud provider or hardware configuration: Azurefile-csi-driver 0.9.0
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux nodepool-f985db88-68ff3c05000000 5.4.0-1016-azure #16-Ubuntu SMP Thu Jun 4 22:49:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
