### ISSUE TITLE
Reference Secrets and ConfigMaps from Secret

### ISSUE THREAD

**Issue by vladimirfx** [kubernetes/kubernetes#97062]
**What would you like to be added**:
It would be useful  to have a way to reference Secrets from Secret definition.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: composite-secret
valuesFrom:
    secretKeyRef:
      name: original-secret
      key: username
    configMapKeyRef:
      name: original-config
      key: resourceName
data:
  USER: ${original-secret.username}
  RESOURCe: ${ original-config.resourceName}
  NEW_FIELD: somevalue
```
**Why is this needed**:

Thankfully to broad adoption of Operator pattern and packing tools like Helm operators needs to compose higher level components instead of low level (Deployment, Pods, etc). In such composition is vital ability to map config data from one format to another. For example some operator generates secret for managed database, that secret should be used in Helm release in form of properly formatted secret. Currently there is no way for doing this proper way and no workaround exists. So good practice using cluster internal secrets becoming operational nightmare.
Another use case - there few operators that import external secrets in cluster. Such external secret can can contain username and password info but absent some additional field (e.g. database name) required  by consumer resource.

This issue differ from #79224 in that it not compromise security by exposing sensitive info in insecure form (in ConfigMap).

Such functionality can be implemented in form of operator but IMO it "core" in nature and should be provided by platform itself.
