### ISSUE TITLE
kube-proxy ignores source address preservation with external-traffic-policy: Local and externalIP address

### ISSUE THREAD

**Issue by robertoalcantara** [kubernetes/kubernetes#97073]
**What happened**:
On service with externalTrafficPolicy: Local and type: LoadBalancer or NodePort, ipvs rules (MASQ) are installed on all workers, loadbalacing across all pods IPs, even to PODs that are not running locally on this worker.

**What you expected to happen**:
As iptables modes does, the IPVS rules should to balance only to PODs running on the same worker, avoiding an extra hop and keeping the source IP address. 

**How to reproduce it (as minimally and precisely as possible)**:
Start a service with two PODs, type: LoadBalancer or NodePort, externalTrafficPolicy: Local and externalIPs, at least two workers.
Check the ipvs rules to the externalIP address.

**Environment**:
[root@]# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Running Calico

**Comment by robertoalcantara** [comment]
I found this:

**Comment by uablrek** [comment]
This is a basic function in K8s that is tested constantly, and works. So this is probably some problem with your setup.

Please provide your service manifest.

A possible fault is if you specify `externalIPs`, like;
```
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  externalTrafficPolicy: Local
  selector:
    app: foo
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  type: LoadBalancer
  externalIPs:
  - 10.0.0.99
```
`externalIPs` is not the same as a loadBalancerIP, it is a different function that _does not_ preserve remote address in K8s v1.18.x. My comment that you refer is about `externalIPs`, not loadBalancerIP.

If you use `externalIPs`, remove them from your manifest and assign a loadBalancerIP instead, e.g using https://github.com/Nordix/assign-lb-ip.
