### ISSUE TITLE
Scheduler scheduled the pod with PV without zone enabled to a node with zone enabled

### ISSUE THREAD

**Issue by Shuanglu** [kubernetes/kubernetes#97080]
**What happened**:
I have one cluster and there is one nodepool 'nodepool1' without zone enabled. I created a statefulset with PVC on the "nodepool1" and disks were created without zone enabled. 
Then I added another nodepool 'nodepool2' with zone enabled. I deleted the pod in statefulset and it was scheduled to the new nodepool and failed to mount since the disk doesn't have the zone property but node has
**What you expected to happen**:
the scheduler can filter the node with zone enabled and node without zone enabled to avoid incorrect scheduling like above
**How to reproduce it (as minimally and precisely as possible)**:
1. create an AKS cluster and default nodepool doesn't hv availability zone
2. create a statefulset with pvc template
3. create another nodepool with availability zone
4. cordon the 1st nodepool and delete the pod of the statefulset

**Anything else we need to know?**:
When controller manager provisioned the azure disk, there was no label "failure-domain.beta.kubernetes.io/zone:" but has the label 'failure-domain.beta.kubernetes.io/region' added to the PV(https://github.com/kubernetes/kubernetes/blob/v1.18.10/pkg/volume/azure_dd/azure_provision.go#L269), when there is only 'region' label on the PV, the scheduler only compared the region label between PV and node hence the node with zone enabled also passed the 'filter'. This resulted the unexpected scheduling and pod failed to start since disk cannot be mounted across the zone.   
https://github.com/kubernetes/kubernetes/blob/v1.18.10/pkg/scheduler/framework/plugins/volumezone/volume_zone.go#L148

Maybe we need to add label "failure-domain.beta.kubernetes.io/zone:0" directly on the PV or change the scheduler logic?

I tested via adding the label "failure-domain.beta.kubernetes.io/zone:0" to the PV in aks-engine and the pod always got scheduled on the node without zone enabled. The scheduler image is 'mcr.microsoft.com/oss/kubernetes/kube-scheduler:v1.18.9'

**Environment**:
- Kubernetes version (use `kubectl version`):
1.18.10
- Cloud provider or hardware configuration:
azure
- OS (e.g: `cat /etc/os-release`):
ubuntu 18.04
- Kernel (e.g. `uname -a`):
azure-4.15
- Install tools:
AKS
- Network plugin and version (if this is a network-related bug):
Azure CNI
- Others:

**Comment by Shuanglu** [comment]
@andyzhangx  whether it's possible to add label "failure-domain.beta.kubernetes.io/zone:0" to the PV as well so that scheduler can compare the zone and region value between PV and node? I tested with aks-engine via adding the label and it can avoid the incorrect scheduling.

**Comment by andyzhangx** [comment]
now we would set `failure-domain.beta.kubernetes.io/zone` for zone disk, e.g. `failure-domain.beta.kubernetes.io/zone=eastus-1`, while we cannot set `failure-domain.beta.kubernetes.io/zone` for non-zone disk since for non-zone disk, there should be no restriction in scheduling.

Since user has both zone and non-zoned node pools in one cluster, workaround is set `nodeSelector` to schedule deployment to zone node if pv volume is zoned.

**Comment by andyzhangx** [comment]
Update more details, `nodeAffinity` value would be like following:
 - non-zone cluster:
 ```yaml
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - eastus2
```

 - zone cluster
```yaml
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - eastus2
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - eastus2-3
```

If all node pools are non-zone clusters, there won't be issue in volume scheduling; if all node pools are zoned clusters, customer would hit following error which is expected if there is no `eastus2-3` zone 3 node in `Ready` status:
```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  52s (x6 over 6m46s)  default-scheduler  0/3 nodes are available: 1 node(s) were unschedulable, 2 node(s) had volume node affinity conflict.
```

The issue only exists when there are zone and non-zone node pools, there would be conflict in such case since in non-zone cluster, volume should be scheduled to any node, while in zone node pools, specific volume could only be scheduled to specific zone, AKS cannot support such mixed mode IMO.

**Comment by andyzhangx** [comment]
In mixed node pools scenario(user has both zoned and non-zoned node pools), let's ask user to add affinity to only schedule pod on non-zone node pool on the pod/statefulset/deployoment, below is an example:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-azuredisk
  labels:
    app: nginx
spec:
  podManagementPolicy: Parallel  # default is OrderedReady
  serviceName: statefulset-azuredisk
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - "0"
                      - "1"
                      - "2"
                      - "3"
                      - "4"
      containers:
        - name: statefulset-azuredisk
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 1; done
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/azuredisk
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: managed-csi
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
```
