### ISSUE TITLE
cloud provider AWS NLB can't balance pods' load when externalTrafficPolicy is Local

### ISSUE THREAD

**Issue by chrisliu1995** [kubernetes/kubernetes#97147]
**What happened?**

When we used the aws cloud provider, we found that when a loadbalance type service was created and its externalTrafficPolicy was specified as Local, the backend pod traffic was unbalanced.

I did an experiment to reproduce this problem.

**Experiment description**

- Cluster description:

    - version: kubernetes 1.12.4

    - 2 computing nodes (node1 & node2)

    - service (  type: LoadBalancer & externalTrafficPolicy: Local)

    - service backend: 3 pods (2 in node1 & 1 in node2)

    - Role of pod: Calculate the total number of requests since it was created

- resource yaml:
    
    ```
    apiVersion: v1
    kind: Pod
    metadata:
    labels:
        k8s-app: req-num-count
    name: req-num-count-1
    spec:
    containers:
    - name: req-num-count-1
        image: xxx/xxx/rnc:20201207_release
        args:
        - -port=9876
        - -host=0.0.0.0
        command:
        - reqNumCount
    nodeSelector:
        kubernetes.io/hostname: xxx-xxx-xxx-38
    ---
    apiVersion: v1
    kind: Pod
    metadata:
    labels:
        k8s-app: req-num-count
    name: req-num-count-2
    spec:
    containers:
        - name: req-num-count-2
        image: xxx/xxx/rnc:20201207_release
        args:
        - -port=9876
        - -host=0.0.0.0
        command:
        - reqNumCount
    nodeSelector:
        kubernetes.io/hostname: xxx-xxx-xxx-38
    ---
    apiVersion: v1
    kind: Pod
    metadata:
    labels:
        k8s-app: req-num-count
    name: req-num-count-3
    spec:
    containers:
        - name: req-num-count-3
        image: xxx/xxx/rnc:20201207_release
        args:
        - -port=9876
        - -host=0.0.0.0
        command:
        - reqNumCount
    nodeSelector:
        kubernetes.io/hostname: xxx-xxx-xxx-39
    ---
    apiVersion: v1
    kind: Service
    metadata:
    name: req-num-count
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
    spec:
    type: LoadBalancer
    externalTrafficPolicy: Local
    selector:
        k8s-app: req-num-count
    ports:
        - protocol: TCP
        port: 80
        targetPort: 9876
    ```

- Experimental steps:

    1. Send 1000 requests to the service
    ```
    for((i=1;i<=1000;i++));
    do
    curl http://xxx.elb.amazonaws.com/test
    done
    ```
    2. View the number of requests received by the three pods, respectively.

- Experimental result:

    The number of requests received by the three pods are 257 (pod1 in node1), 260 (pod2 in node1), 483 (pod1 in node2)

**My question**

I know that when the externalTrafficPolicy of the service is Local, node will not do secondary forwarding, but is there any way to avoid this unbalanced load situation?
