### ISSUE TITLE
maxSurge 0 not working

### ISSUE THREAD

**Issue by kong62** [kubernetes/kubernetes#97227]
**What happened**:
I set `maxSurge: 0` in deployment, but it not working, pod will Pending 
```

# kubectl get pod -n traefik 
NAME                           READY   STATUS        RESTARTS   AGE
default-404-7889c7864b-7cldp   1/1     Running       0          92d
traefik-6c6dbfdd7d-9nt79       0/1     Terminating   0          40m
traefik-6c6dbfdd7d-kns8m       1/1     Running       0          40m
traefik-6c6dbfdd7d-lq5kz       1/1     Running       0          41m
traefik-95684858-l9kfg         0/1     Pending       0          15s
```
**What you expected to happen**:
no Pending

**How to reproduce it (as minimally and precisely as possible)**:
```
...
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: system
                operator: In
                values:
                - management
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: NotIn
                values:
                - "true"
              - key: enable-traefik
                operator: In
                values:
                - "true"
        ...        
      dnsPolicy: ClusterFirst
      hostNetwork: true
```

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.16.9
