### ISSUE TITLE
healthCheckNodePort depends on the default iptables chain policy to be accessible externally

### ISSUE THREAD

**Issue by maplain** [kubernetes/kubernetes#97225]
**What happened**:
When the default policy for filter table INPUT chain is DROP, external query on Service's "spec.healthCheckNodePort" is dropped.

**What you expected to happen**:
kube-proxy should manage iptable rules for "spec.healthCheckNodePort" similar to what it does for "NodePort". It also should ensure once "spec.healthCheckNodePport" is allocated, it's accessible regardless of the default policy on chains.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Service with "spec.externalTrafficPolicy" == "Local";
2. manually set the filter table INPUT chain default policy to "DROP"(this currently depends on the Node Image);
```
iptables -t filter -P INPUT DROP
```
3. curl the "spec.healthCheckNodePort" from any other host;

**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+vmware.2", GitCommit:"9d9a7637ad75801f9296a1cebe63120c020305d4", GitTreeState:"clean", BuildDate:"2020-09-22T22:55:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="VMware Photon OS"
VERSION="3.0"
ID=photon
VERSION_ID=3.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
```
- Kernel (e.g. `uname -a`):
``` 
Linux tkg-cluster-wc-743-md-0-8bdb9cc86-z7qwd 4.19.145-2.ph3 #1-photon SMP Wed Sep 23 02:26:04 UTC 2020 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by andrewsykim** [comment]
If I have a default `DROP` policy for the `INPUT` chain and kube-proxy adds rules to allow `nodePorts` but not `healthCheckNodePorts`, that seems like a bug to me. 

I guess this hasn't been a problem before since most nodes would have `ACCEPT` as the default `INPUT` policy. Asking users to change their default policy from `DROP` to `ACCEPT` to use `healthCheckNodePorts` seems like asking too much. I think it would be reasonable if kube-proxy added `-j ACCEPT` rules for each `healthCheckNodePort` so they are allowed even when `INPUT` is `DROP` by default.

**Comment by hanlins** [comment]
Will help @maplain on this one.
/assign @hanlins

**Comment by hanlins** [comment]
Some updates on reproducing the issue. Assuming port `30000` is not taken, this is the spec I used:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        #image: nginx:1.14.2
        image: us.gcr.io/google-containers/nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  healthCheckNodePort: 30000
  externalTrafficPolicy: Local
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
```
From outside, you can access the health check node port:
```
➜  ~ curl 10.182.137.110:30000 --connect-timeout 1
{
	"service": {
		"namespace": "default",
		"name": "nginx"
	},
	"localEndpoints": 1
}%
```
Then after changing the `INPUT` chain policy to `DENY` like @maplain mentioned above:
```
iptables -t filter -P INPUT DROP
```
you won't be able to access the health check node port from outside:
```
➜  ~ curl 10.182.137.110:30000 --connect-timeout 1
curl: (28) Connection timed out after 1000 milliseconds
```

Notice before changing `INPUT` policy, make sure that the `ssh` traffic is accepted if you're testing it on a remote VM. This is what I added:
```
iptables -A INPUT -p tcp --dport ssh -j ACCEPT -m comment --comment "Accept SSH traffic"
```
