### ISSUE TITLE
Provide ServiceAccountTokenProjection migration example

### ISSUE THREAD

**Issue by dcecile** [kubernetes/kubernetes#97256]
**What would you like to be added**:

When switching from old `automountServiceAccountToken` to the new `ServiceAccountTokenProjection`, it would be helpful to have an example of equivalent configuration.

The old automount creates 3 files:

```
/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
/var/run/secrets/kubernetes.io/serviceaccount/token
/var/run/secrets/kubernetes.io/serviceaccount/namespace
```

If [the docs for service account token projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) showed how to create the same 3 files, then migration should be quite simple.

**Why is this needed**:

All 3 of these files all seem important for using a service account inside a pod.

For example, the official Python Kubernetes client [requires both the token and the root CA certificate at those exact locations](https://github.com/kubernetes-client/python-base/blob/2da2b981ca806b25487ad92d01a2164815c18517/config/incluster_config.py#L72-L85) in order to load in-cluster config.

Also, the official `kubectl` CLI client does not support configuration via token file path, and will automatically look for those 3 files (https://github.com/kubernetes/kubectl/issues/927#issuecomment-693483957).

The [docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) currently only give a vault-oriented example, adding audience to the token and skipping the root CA certificate and namespace files:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  serviceAccountName: build-robot
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault
```

Instead maybe change the sample to something like this, which would allow for easier migration:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: service-account
  serviceAccountName: build-robot
  volumes:
    - name: service-account
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 7200
          - configMap:
              name: xyz # TODO
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    fieldPath: metadata.namespace
```

The [original service account token projection proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/svcacct-token-volume-source.md#token-volume-projection) uses this approach, adding `ca.crt` and `namespace` together with `token` in the same projected volume.

The problem here is that I can't figure out a simple way to add the root CA certificate in my GKE cluster.

- The [fix](https://github.com/kubernetes/kubernetes/pull/68812) for #68811 adds a `root-ca-cert-publisher`, but its documentation PR was not merged (https://github.com/kubernetes/website/pull/12963) and it's blocked (https://github.com/kubernetes/kubeadm/issues/1286) by the `BoundServiceAccountTokenVolume` (or [`RootCAConfigMap`](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume)?) alpha feature gate, so I'm not sure if this is the best recommendation?
- `kubeadm init` is [documented to create a `cluster-info` config map](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#create-the-public-cluster-info-configmap) which according to https://github.com/kubernetes/kubeadm/issues/1286#issuecomment-576458208 includes the root CA, but I don't see this config map in GKE
- https://github.com/kubernetes/kubernetes/issues/61572#issuecomment-448487090 suggests `kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'`, but that doesn't seem right to run inside a pod

If the `ca.crt` issue could be solved, would it make sense to document migrating from `automountServiceAccountToken` to  `ServiceAccountTokenProjection`?

**Comment by dcecile** [comment]
@k8s-ci-robot /sig auth

**Comment by ams0** [comment]
Hello! I am from the Bug Triage team! Friendly reminder that code freeze is starting March 9th, 2021 (today!).

As the Issue is tagged for 1.21, but no PR is linked, are we still working on this? It seems like a great documentation addition if not for this cycle, definitely for the next (I've been thru migration to projected tokens, and this seems a reasonable addition).

**Comment by liggitt** [comment]
moved to 1.22, but included in the GA column of https://github.com/orgs/kubernetes/projects/51#card-54493535

**Comment by zshihang** [comment]
to migrate secret-based token volume to projected volume:
1. when BoundServiceAccountTokenVolume is enabled (1.21+), updates to the pod should have the projected volume added by sa admission controller
2. when BoundServiceAccountTokenVolume is not enabled, we need `RootCAConfigMap` to be enabled to manually add the projected volume
    ```yaml
    - name: kube-api-access-xxxxx
      projected:
        defaultMode: 420 # 0644
        sources:
          - serviceAccountToken:
              expirationSeconds: 3600
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
    ```
