### ISSUE TITLE
There is no enough admission validation for pod template specification in StatefulSet.

### ISSUE THREAD

**Issue by shyung** [kubernetes/kubernetes#97309]
**What happened**:

Without enough admission validations, statefulSet can be created in illegal pod template as followed.

```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-test
  namespace: test
spec:
  podManagementPolicy: Parallel
  revisionHistoryLimit: 10
  replicas: 2
  selector:
    matchLabels:
      app: sts-test
  serviceName: "null"
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sts-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: test
                operator: DoesNotExist
                values:
                - ok
      containers:
      - image: busybox:latest
        args:
        - /bin/sh
        - -c
        - while true; do echo hello; sleep 1; done
        imagePullPolicy: IfNotPresent
        name: container-test
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
```

As a consequence, StatefulSet controller cannot create pod due to illegal pod template.

Using `kubectl describe sts`, Warning events can be found as followed.

```
Events:
  Type     Reason        Age                From                    Message
  ----     ------        ----               ----                    -------
  Warning  FailedCreate  2s (x11 over 10s)  statefulset-controller  create Pod sts-test-0 in StatefulSet sts-test failed error: Pod "sts-test-0" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Forbidden: may not be specified when `operator` is 'Exists' or 'DoesNotExist'
```

**What you expected to happen**:

The create operation of StatefulSet with illegal pod template can be blocked by admission validation, just as Deployments do.

**How to reproduce it (as minimally and precisely as possible)**:

Using manifests with illegal pod template to create StatefulSet.

For example, matchExpression value is set non-empty with operator "DoesNotExist" or "Exists" in affinity terms. 

```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: test
          operator: DoesNotExists
          values:
          - ok
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.17.3. 
As far as I know, however, the bug is still existed in Kubernetes up to date.
- OS (e.g: `cat /etc/os-release`):
CentOS release 6.3 (Final)
- Kernel (e.g. `uname -a`):
Linux 3.10.0.514.26.2.el7.x86_64
- Install tools:
Binary.
