### ISSUE TITLE
Update audit policy sample to make it more practical

### ISSUE THREAD

**Issue by oke-py** [kubernetes/kubernetes#97316]
**What would you like to be added**:

It would be helpful if the audit policy below be updated.
https://github.com/kubernetes/kubernetes/blob/release-1.20/cluster/gce/gci/configure-helper.sh#L1091-L1239

idea:
* `discovery.k8s.io` can be added to known api groups.
* EndpointSlice can be handled same as Endpoints. This can be added after [this line](https://github.com/kubernetes/kubernetes/blob/release-1.20/cluster/gce/gci/configure-helper.sh#L1123).
    ```yaml
    - group: "discovery.k8s.io"
      resources: ["endpointslices"]
    ```
* Actions on Lease object are not necessary for logging.
    ```yaml
    - level: None
      # users, verbs fields would be necessary
      resources:
      - group: "coordination.k8s.io"
        resources: ["leases"]
    ```
* GET request to nonResourceURLs like `/livez`, `/readyz` can be ignored.

**Why is this needed**:

The lines have not been updated since 3 years ago.
There are new API Groups and Kinds, and so the policy would result in too many or insufficient logs.

Administrators of on-premise Kubernetes may determine their policy based on this.
If this sample is updated, they can make use of it.
