### ISSUE TITLE
the pod container quickly exited postStart will block forever,then pod keep containerCreating forever

### ISSUE THREAD

**Issue by niuyueyang1996** [kubernetes/kubernetes#97364]
kubelet version is v1.14.3

docker version
Docker version 19.03.1, build 74b1e89e8a

containerd version
containerd containerd.io 1.4.3 269548fa27e0089a8b8278fc4fc781d7f65a939b

i create a pod
there is container info :
```
containers:
        - lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - /root/start.sh
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - /root/stop.sh
          image: 'quick-exit:latest'
          stdin: true
          name: quick-exit
          tty: true
          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
```

image code
```
package main

import "time"

func main()  {
	time.Sleep(time.Millisecond*100)
	panic("exit")
}

```
postStart code
```
mycount=0; while (( $mycount < 10 )); do echo $mycount;sleep 0.3;((mycount=$mycount+1)); done;
```

i find NativeExecHandler.ExecInContainer will block with func client.StartExec(execObj.ID, startOpts, streamOpts)

```
//the func is sync to wait error
err = client.StartExec(execObj.ID, startOpts, streamOpts)
if err != nil {
   return err
}
//never execute this code if StartExec no result
ticker := time.NewTicker(2 * time.Second)
defer ticker.Stop()
count := 0
for {
   inspect, err2 := client.InspectExec(execObj.ID)
   if err2 != nil {
      return err2
   }
   if !inspect.Running {
      if inspect.ExitCode != 0 {
         err = &dockerExitError{inspect}
      }
      break
   }
 
   count++
   if count == 5 {
      glog.Errorf("Exec session %s in container %s terminated but process still running!", execObj.ID, container.ID)
      break
   }
 
   <-ticker.C
}
```
can you make the StartExec async and add a task to check if the exec is available?
