### ISSUE TITLE
Allow for setting pod priority based on custom metrics

### ISSUE THREAD

**Issue by wanderanimrod** [kubernetes/kubernetes#97380]
## What would you like to be added
I would like to be able to set pod priority based on a pod metric (in-built or custom), instead of using statically defined `PriorityClass` objects. 

## Why is this needed
I am running a group of pods that run CI-style build tasks (using a statefulset, but could use a deployment too). The duration of those tasks is unknown until they finish running. I am working on adding pod auto scaling (up and down) to the statefulset. In the down-scaling scenario, I need to make sure that kubernetes doesn't kill pods that are still running build tasks if there are other pods with no or fewer active build tasks. 

### What I have tried so far
I have already set `pod.spec.lifecycle.preStop` to a script that makes the worker pod stop accepting new build tasks. I have also set a `terminationGracePeriodSeconds`, but I can't determine a good number to set it to because I don't know how long any build tasks running on the pod would take to stop running.

### What I'd like to do
In a down-scaling scenario, I'd like to be able to tell kubernetes start by killing pods with the least number of active build tasks. The number of active tasks on a worker pod is exposed as a metric via HTTP.

### My proposal
Expand the `PriorityClass` object to allow for  the `value` field (or another field) to be set to a metric source, just like we do for auto-scaling. Something like:
```yaml
kind: PriorityClass
name: worker-number-of-tasks
metric:
  httpGet: 
    path: metrics/number_of_active_tasks # must return a number
    port: 7629
  higherPriorityWhenMetricIs: higher # {options: higher | lower}
```

Another idea is to allow for the metric to be fetched from any endpoint, for instance a service running in the cluster or outside the cluster.
```yaml
kind: PriorityClass
name: worker-number-of-tasks
metric:
  service: 
    name: my-metrics-service
    httpGet:
      path: metrics/number_of_active_tasks # must return a number
      payload: {workerId: worker1} # custom payload that identifies the pod whose metric we want to get from the metric service
  higherPriorityWhenMetricIs: higher # {options: higher | lower}
```
