### ISSUE TITLE
Separate readinessProbe for Service

### ISSUE THREAD

**Issue by fip-post-cz** [kubernetes/kubernetes#97393]
**What would you like to be added**:

In addition to startupProbe/livenessProbe/readinessProbe add new probe chooseProbe into Pod's definition for usage in Service only.
It will act similar as readinessProbe, however only Service will take it in account. Service should add pod's endpoint if all four probes startupProbe + livenessProbe + readinessProbe + chooseProbe are successfull (or not specified).

**Why is this needed**:

It's the easiest way how to route traffic to pod with applications cluster's master node and this greatly simplifies the deployment of HA applications.

Let's consider StatefulSet with three Pod. One is Master, two are Slave. All are alive and ready, but chooseProbe will enable route traffic to Master pod only.

Traffic routing to master pod can be acomplished with readinessProbe just now, but this unfortunately breaks Pod deploy and RollingUpgrade mechanism, because readinessProbe is not designed for that case. Specifically RollingUpgrade with OrderedReady doesn't work at all, so a new enhancement could be added.

**Comment by fip-post-cz** [comment]
Proposal:

Pod:
apiVersion: v1
kind: Pod
metadata:
  name: ha-node
spec:
  containers:
  - name: ha-node
    image: ha-node:latest
    startupProbe:
      # as usual
    livenessProbe:
      # as usual
    readinessProbe:
      # as usual
    chooseProbe:
      exec:
        command:
        - /probe_is_master.sh
      initialDelaySeconds: 5
      periodSeconds: 3

Service:
No changes in definition, service will route traffic to ha-node with satisfied probes include chooseProbe.

**Comment by jayunit100** [comment]
not 100% sure here but one idea you could do:  is implementi using the `leader election API` , build on ETCD.  In that case, you could do something with init pods, where 

1) Init pod cycled until it got a leader lock based on its IP
2) then the actual pod came up

**Comment by fip-post-cz** [comment]
> Is what you want, a leader election?

No.

> 1. Init pod cycled until it got a leader lock based on its IP
> 2. then the actual pod came up

Not possible. All pods must be running to enable continuous master-slave data replication.

> exact requirement ?

Route traffic from service to selected pod only, not to all running pods.

**Comment by jayunit100** [comment]
Yeah, so this is pretty interesting problem... Never thought about it.

# problem

You need: 
- all pods "p" for service "s" are running
- exactly ONE pod "p" for service "s" recieves traffic at a time.

# solution 

To me it sounds like you have a another possible solution, which is to define a `Service` which is "aware" of this *leadership semantic* which your introducing.   So, how about the following 3 step solution: 

- add a second sidecar container to each pod, which simply makes an api call to k8s (1)  to add a label to its host pod, as soon as that pod becomes leader, and continues to watch/update this state as needed (2) to set the `leader:true` to `leader:false` as soon as the pod STOPS being the leader.  
-  maintain a special label on pods..
   - pod1: `leader:true`, `app:zookeeper`. 
   - pod2: `leader:false`, `app:zookeeper`. 
   - pod3: `leader:false`, `app:zookeeper`. 
- create a service with the following selector:
   - service-lead: `leader:true`, `app:zookeeper`.
   - service-all: `app:zookeeper`.

- Now, the service above will **ALWAYS** load balance to `pod1` until pod 1 changes to `follower`.  
- The service will generally NEVER load balance to any OTHER pod
- The statefulset readiness/liveness probes can continue to be used with the RollingUpgrade/OrderedReady logic, because you are using a very specific label to manage the leader traffic.

It would be cool if there was some kind of a "service-endpoint-elector" operator you could run , generically, that did this for services by, for example, querying a specific endpoint on a specific port of every pod, and then relabelling the pod based on the return of an endpoint.

**Comment by jayunit100** [comment]
In k8s upstream slack in the service-apis room, @hbagdi also mentioned that using a gateway service, w/ the newer service APIs tooling, could solve this.  Can you elaborate on that @hbagdi ?

**Comment by jayunit100** [comment]
So, summarizing, theres actually 3 solutions I think - 1 w/ healthchecks, 2 w/ labels.  harry can clarify the implementation details of the healthchecks one (Which would use the new service apis stuff)  

- healthchecks: use gateway service to be aware (somehow?) of master status  and then magically recalibrate endpoints ?
- labels: use a sidecar w in-cluster kubeclient  to (!1) introspect master status and then (2) update pod labels by talking to apiserver
- labels: use an operator to have custom ‘probe’ logic that figures the master out and then re-labels pods as needed.

**Comment by hbagdi** [comment]
We don't have much in service-apis currently to help here but at some point, we plan on adding healthchecks. These healthchecks will be performed by Gateway on the pods of the service. If one can configure the healthcheck to pass only on the leader pod, then the Gateway would forward traffic to the specific pod only.
xref https://github.com/kubernetes-sigs/service-apis/issues/99
xref https://github.com/kubernetes-sigs/service-apis/issues/97

**Comment by jayunit100** [comment]
i feel like we can close this as, its not supported yet but there are the above workarounds you can follow along.
if you wanna bring this up at sig-network this thrusday let us know ! https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit

**Comment by fip-post-cz** [comment]
jayunit100 & hbagdi: Thank you for your valuable replies, they brought me a solution, this case can be closed.

> Yeah, so this is pretty interesting problem... Never thought about it.

Please note this setup is widely known HA configuration on bare virtual machines, it would be nice if there will be direct support in k8s.

More details about solution without k8s:
Physical_Machine_1: Virtual_Machine_A, Daemon_A, Storage_A.
Physical_Machine_2: Virtual_Machine_B, Daemon_B, Storage_B.
Both machines: Virtual IP managed by Keepalived and IPVS kernel module and VRRP network protocol. Other possibilities are HAProxy etc.
One Daemon acts as Master, second acts as Slave. All work is done by Master, Virtual IP is assigned to Master. Clients are connecting to Virtual IP, not directly to machines IP. Slave is running all the time, there is continuous data replication from Master to Slave.
In case od failure, Slave is promoted to new Master and Virtual IP is reassigned to new Master. This enables switchover to fully working node in seconds and enables full resistance against single node failure.

**Comment by hbagdi** [comment]
> they brought me a solution, this case can be closed.

I'm interested in knowing which solution will you be using for your current problem. It also will be useful for someone else who will end up reading this thread in future.

The solution you describe above is the one I'm familiar with as well but that's much harder to pull of it with kube abstractions.

**Comment by fip-post-cz** [comment]
> which solution will you be using

I've made RBAC+ServiceAccount for my pod, and I'm patching pod's label "app-role" via kubectl directly in readinessProbe, after pod's role change. (I agree that this should be done more precisely and safely with a sidecar).

`kubectl patch pod <pod name> --patch '{"metadata":{"labels":{"app-role":"<app role>"}}}'`

pod1: label app:foo, label app-role:`<dynamic>` e.g. master
pod2: label app:foo, label app-role:`<dynamic>` e.g. slave
pod3: label app:foo, label app-role:`<dynamic>` e.g. slave

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: foo
  namespace: foo
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: foo
  namespace: foo
subjects:
  - kind: ServiceAccount
    name: foo
    namespace: foo
roleRef:
    kind: Role
    name: foo
    apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: foo
  namespace: foo
```

```
kind: Service
apiVersion: v1
metadata:
  name: foo
  namespace: foo
  labels:
    app: foo
spec:
  selector:
    app: foo
    app-role: master
```

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foo
  namespace: foo
  labels:
    app: foo
spec:
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      serviceAccountName: foo
      containers:
        - name: foo
          livenessProbe:
            exec:
              command: ["/dir/liveness_probe"]
          readinessProbe:
            exec:
              command: ["/dir/readiness_probe"] # calls kubectl patch
```
