### ISSUE TITLE
Custom `Namespace` cluster wide resource reports 404 when trying to GET

### ISSUE THREAD

**Issue by richardmcsong** [kubernetes/kubernetes#97397]
**What happened**:
I defined a CRD with a custom group (eg. `test.my.domain`), and a custom version (eg. `v1beta1`), with the Kind set to `Namespace`, and the scope set to `Cluster`. A more detailed CRD definition is [found here](https://gist.github.com/richardmcsong/3380e22ad6b830f601dfe1ac313d865a).

After I applied this CRD, I created a sample resource, and then tried to list and get the resource using `kubectl`.
Results of `kubectl get namespaces.test.my.domain`:
```
$ kubectl get namespaces.test.my.domain 
NAME               AGE
namespace-sample   76m
```

However, when I do a `kubectl get namespaces.test.my.domain namespace-sample`:
```
$ kubectl get namespaces.test.my.domain namespace-sample
Error from server (NotFound): the server could not find the requested resource (get namespaces.test.my.domain namespace-sample)
```

**What you expected to happen**:
It seems like it doesn't break on the other resource name that I tried (`testresource`), which suggests it's specific to an overlap in naming on the `Namespace` keyword. I would expect that the group is enough of a differentiator.

**How to reproduce it (as minimally and precisely as possible)**:
As above.

**Anything else we need to know?**:
- **Why would you want to do this? Sounds like a one-way ticket to confusion!** - We're trying to redesign a drop-in abstraction that most people can use in the same manner as a true Namespace, but it just wraps up a bunch more automation that we have behind the scenes that is appropriate for the ways of working in the company. We understand if the answer is just `don't use Namespace as a cluster-wide resource kind`, but since we were working on this, we figure we'd bring it up as a discussion topic anyway. Our current workaround is to do something like `CompanyNamespace`, but in its long form seems kind of stutter-y: `companynamespaces.company.domain`. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: I built the cluster using `kind`
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): Linux dev 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64 GNU/Linux

**Comment by liggitt** [comment]
what does the trace show (run with --v=6)?

/sig cli

**Comment by richardmcsong** [comment]
I've pasted it here: https://gist.github.com/richardmcsong/fb11a38a5b73349c5b0ed24522eebbaa

**Comment by liggitt** [comment]
Likely caused by this check, which did not consider a cluster-scoped CRD named "namespaces", which confuses the request parser into thinking the request is namespaced: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L292-L295

/triage accepted
/cc @sttts

**Comment by SataQiu** [comment]
It seems a little tricky to determine whether the request is namespaced or cluster-scoped by URL format.
https://github.com/kubernetes/kubernetes/blob/b749a3a421652644bb170b57375ef0cf46c0fa3f/staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go#L179-L192

**Comment by richardmcsong** [comment]
/remove-lifecycle stale
Any thoughts/updates?

**Comment by ytsarev** [comment]
I encountered exactly the same situation.

CRD

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespaces.icanbreakkubernetes.io
spec:
  group: icanbreakkubernetes.io
  names:
    kind: Namespace
    listKind: NamespaceList
    plural: namespaces
    singular: namespace
  scope: Cluster
  versions:
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              test:
                type: string
```

CR:

```yaml
apiVersion: icanbreakkubernetes.io/v1alpha2
kind: Namespace
metadata:
  name: example
spec:
  test: breakme
```
Attempt to `get` or `delete`  fails 
```
k get namespaces.icanbreakkubernetes.io
NAME      AGE
example   4m35s

k get namespaces.icanbreakkubernetes.io example
Error from server (NotFound): the server could not find the requested resource (get namespaces.icanbreakkubernetes.io example)

k delete namespaces.icanbreakkubernetes.io example 
Error from server (NotFound): the server could not find the requested resource (delete namespaces.icanbreakkubernetes.io example)
```
