### ISSUE TITLE
Add the ability to target an IngressClass controller in a specific namespace

### ISSUE THREAD

**Issue by yp28** [kubernetes/kubernetes#97396]
**What would you like to be added**:
Modify IngressClass to use ObjectReference instead of TypedLocalObjectReference.

**Why is this needed**:
Ingress controllers are workloads deployed on a cluster inside a namespace. When using multiple ingress controllers in a cluster, using the ObjectReference allows for better integration with those clusters, by having the means to target an ingress controller in a specific namespace.

**API changes**:
```yaml
apiVersion: "networking.k8s.io/v1"
kind: "IngressClass"
metadata:
  name: "external-lb"
spec:
  controller: "example.com/ingress-controller"
  parameters:
    apiGroup: "k8s.example.com/v1alpha"
    kind: "IngressParameters"
    name: "external-lb"
```
would become:
```yaml
apiVersion: "networking.k8s.io/v1"
kind: "IngressClass"
metadata:
  name: "external-lb"
spec:
  controller: "example.com/ingress-controller"
  parameters:
    apiVersion: "k8s.example.com/v1alpha"
    kind: "IngressParameters"
    name: "external-lb"
    namespace: "example-ns"
```
still allowing for users to refer to non-namespaced objects, but adding the ability to refer to objects within a namespace like Istio Gateways.

/sig network
/sig api-machinery

link: istio/istio#27326
