### ISSUE TITLE
Hope pv/pvc to support ceph rbd snapshot

### ISSUE THREAD

**Issue by lianxmfor** [kubernetes/kubernetes#97402]
**What would you like to be added**:
i hope k8s can support ceph rbd snapshot
**Why is this needed**:
i have a pv/pvc:
``` yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app:  rbd-ssd-dataset@v1
  name:  rbd-ssd-dataset@v1
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1G
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name:  rbd-ssd-dataset@v1
    namespace: mynamespace
  persistentVolumeReclaimPolicy: Retain
  rbd:
    # rbd image: rbd-ssd-dataset, snapshot: v1
    image:  rbd-ssd-dataset@v1
    keyring: /etc/ceph/keyring
    monitors:
    - 10.19.250.45:6789
    pool: ssd-rbd
    readOnly: true
    user: admin
  volumeMode: Filesystem
status:
  phase: Bound
```
now i create a pod use the pvc, but the pod not work, pending long time.
exec rbd showmapped in node:
0 rbd-ssd           rbd-ssd-dataset   v1   /dev/rbd0
1 rbd-ssd           rbd-ssd-dataset   v1   /dev/rbd1
2 rbd-ssd           rbd-ssd-dataset   v1   /dev/rbd2
...
and more and more rbd-ssd-dataset@v1 is mapped in node
i found pkg/volume/rbd/rbd_util.go#getRbdDevFromImageAndPool not work in rbd snapshot
i am so sorry, my english is not good
