### ISSUE TITLE
v1.20.1 still pull k8s.gcr.io/pause:3.1 even if i set my own  imageRepository

### ISSUE THREAD

**Issue by DalekFrog** [kubernetes/kubernetes#97438]
**What happened**:

In my Test environment:
I use comand:`kubeadm init --config kubeadm.yaml` to start a single node k8s.
kubeadm.yaml:
```
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    pod-infra-container-image: "myowndomain.example.com/k8s/pause:3.2"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  certSANs:
  - kubernetes.master
clusterName: kubernetes
dns:
  type: CoreDNS
imageRepository: myowndomain.example.com/k8s
kubernetesVersion: v1.20.1
networking:
  dnsDomain: cluster.local
  podSubnet: 100.64.0.0/16
  serviceSubnet: 100.80.0.0/16

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
imageGCHighThresholdPercent: 90
imageGCLowThresholdPercent: 85
imageMinimumGCAge: 10080m0s
```
when successfully init
```
# crictl images
IMAGE                                              TAG                 IMAGE ID            SIZE
docker.io/calico/cni                               v3.17.1             64e5dfd8d597a       44.1MB
docker.io/calico/kube-controllers                  v3.17.1             278f40d9f3b82       22MB
docker.io/calico/node                              v3.17.1             183b53858d7da       58.4MB
docker.io/calico/pod2daemon-flexvol                v3.17.1             819d15844f0c9       9.33MB
myowndomain.example.com/k8s/coredns                   1.7.0               bfe3a36ebd252       14MB
myowndomain.example.com/k8s/etcd                      3.4.13-0            0369cf4303ffd       86.7MB
myowndomain.example.com/k8s/kube-apiserver            v1.20.1             75c7f71120808       30.4MB
myowndomain.example.com/k8s/kube-controller-manager   v1.20.1             2893d78e47dc3       29.4MB
myowndomain.example.com/k8s/kube-proxy                v1.20.1             e3f6fcd87756e       49.5MB
myowndomain.example.com/k8s/kube-scheduler            v1.20.1             4aa0b4397bbbc       14MB
myowndomain.example.com/k8s/pause                     3.2                 80d28bedfe5de       298kB
k8s.gcr.io/pause                                   3.1                 da86e6ba6ca19       317kB
```

**What you expected to happen**:

***see the last image***
there should be no `k8s.gcr.io/pause:3.1` here.

I was going to setup a Offline Cluster with my own image repository which had already synced image from k8s.gcr.io .
 But the kubelet(or kubeadm maybe) still try to pull `k8s.gcr.io/pause:3.1`

**How to reproduce it (as minimally and precisely as possible)**:
- 1. Delete all container  image about k8s
- 2. Use my command and `kubeadm.yaml` init a cluster 
- 3. When success, see all images

**Environment**:
- Kubernetes version (use `kubectl version`):
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: 
   My own KVM virtual machine 
- OS (e.g: `cat /etc/os-release`):
```
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```
- Kernel (e.g. `uname -a`):
`Linux hostname 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:  `kubeadm`
- others: `containerd.io-1.4.3-3.1.el8.x86_64`
