### ISSUE TITLE
VolumeMount permissions with subpaths are dependent on order in the yaml

### ISSUE THREAD

**Issue by amisevsk** [kubernetes/kubernetes#97460]
**What happened**:

Adding a VolumeMount to a container with a multi-part subpath results in only the leaf directory having 777 permissions. If you define e.g.
```yaml
volumeMounts:
  - name: my-pvc
    mountPath: /tmp/my-pvc
    subPath: dir1/dir2/dir3
```
then within the volume, `dir1` and `dir2` will have `755` permissions, whereas `dir3` will have `777` permissions. This means that if you want to remove `dir1` and `dir2` eventually from within a pod, you will need to use a privileged pod.

If the sub-directories already exist, their permissions are unchanged, and the order in which these subpaths are created appears to be the order in which they appear within the spec -- if we see `dir1/dir2` first, then `dir1` will be created with 755 permissions and `dir1/dir2` will be created with 777 permissions, even if there's another volumeMount for `dir1` further down.

**What you expected to happen**:

Sub-directories created to support a volumeMount should all have the same permissions as the leaf directory.

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl apply -f` the yaml below. The first example has volume mounts so that `dir1` is created before `dir1/dir2`; the second example has volume mounts in reversed order, so `dir1/dir2` is encountered before `dir1`, which results in `dir1` being unwritable.

<details>
  <summary>This pod will complete</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-working
  labels:
    app: pvc-test
spec:
  restartPolicy: "Never"
  containers:
    - image: quay.io/libpod/busybox
      name: pvc-test
      securityContext:
        runAsUser: 1234
      volumeMounts:
        - name: the-pvc
          mountPath: /tmp/the-pvc1
          subPath: dir1 
        - name: the-pvc
          mountPath: /tmp/the-pvc2
          subPath: dir1/dir2
      command: ["/bin/sh"]
      args: 
      - "-c"
      - "touch /tmp/the-pvc1/testfile && touch /tmp/the-pvc2/testfile"
  volumes:
    - name: the-pvc
      persistentVolumeClaim:
        claimName: pvc-test-working
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-working
  labels:
    app: pvc-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
```
</details>

<details>
  <summary>This pod will fail</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-not-working
  labels:
    app: pvc-test
spec:
  restartPolicy: "Never"
  containers:
    - image: quay.io/libpod/busybox
      name: pvc-test
      securityContext:
        runAsUser: 1234
      volumeMounts:
        - name: the-pvc
          mountPath: /tmp/the-pvc2
          subPath: dir1/dir2
        - name: the-pvc
          mountPath: /tmp/the-pvc1
          subPath: dir1 
      command: ["/bin/sh"]
      args: 
      - "-c"
      - "touch /tmp/the-pvc1/testfile && touch /tmp/the-pvc2/testfile"
  volumes:
    - name: the-pvc
      persistentVolumeClaim:
        claimName: pvc-test-not-working
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-not-working
  labels:
    app: pvc-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
```
</details>

**Anything else we need to know?**:

I believe this is the return of https://github.com/kubernetes/kubernetes/issues/41638

**Environment**:

Reproduces on minikube and a (OpenShift) development cluster I have access to
- Kubernetes version (use `kubectl version`):
  - minikube: `Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`
  - OpenShift cluster: `Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+9f84db3", GitCommit:"9f84db336d1a77cba52684ecb51bfb197e9b4533", GitTreeState:"clean", BuildDate:"2020-10-30T09:33:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`
    - `oc version` output:
      ```
      Server Version: 4.6.3
      Kubernetes Version: v1.19.0+9f84db3
      ```
- Cloud provider or hardware configuration: 
  - Minikube: v1.15.1; docker driver; hostpath volumes (all default)
  - OpenShift cluster: AWS, EBS volumes
- OS (e.g: `cat /etc/os-release`): 
  - Minikube: Fedora 32
  - OpenShift cluster: RHEL 8.2
- Kernel (e.g. `uname -a`): 
  - Minikube: `5.9.14-100.fc32.x86_64`
  - OpenShift cluster: `4.18.0-193.14.3.el8_2.x86_64`
- Install tools: minikube v1.15.1 / Not sure
- Network plugin and version (if this is a network-related bug): N/A
- Others:
