### ISSUE TITLE
After restarting all nodes, init container and  normal container are started at the same time

### ISSUE THREAD

**Issue by Bryce-huang** [kubernetes/kubernetes#97512]
**What happened**:

reboot all nodes，initcontainer and normal container are started at the same time.
use `kubectl get pod` , It seems that everything is normal and the initcontainer is starting，but in fact the normal container is also starting
**What you expected to happen**:
The normal container should be started after  initcontainer

**How to reproduce it (as minimally and precisely as possible)**:
1. reboot all nodes
2. use commamd `kubectl logs podname -c normalcontainer`  before initcontainer conpleted. you will see the normal container logs 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.9
- Cloud provider or hardware configuration: vm 
- OS (e.g: `cat /etc/os-release`): centos 7.6
- Kernel (e.g. `uname -a`): Linux kube-master001 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadmin 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
I try to reboot a single node or docker, and the initial container will not start in my env.
```
[root@daocloud ~]# docker inspect ea5f8b2754a5
[
    {
        "Id": "ea5f8b2754a5965d9d818e15b5da919158f0b5cd1b58b27204c5ad34093af674",
        "Created": "2020-12-25T10:40:02.885145684Z",
        "Path": "/opt/cni/bin/install",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-12-25T10:40:03.145375167Z",
            "FinishedAt": "2020-12-25T10:40:05.638823439Z"
        },
        "Image": "sha256:29b6bcc4a8b419bf192e300cfa128902a79d158fad7b076272eb9deec7db3d30",
        "ResolvConfPath": "/var/lib/docker/containers/7fedb0a1ff83d814fcc01a0e9842ecd62dbf99a473e71610fd8c65e9b160b1d0/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/7fedb0a1ff83d814fcc01a0e9842ecd62dbf99a473e71610fd8c65e9b160b1d0/hostname",
        "HostsPath": "/var/lib/kubelet/pods/920f7c02-453e-4561-b97a-347df057fba0/etc-hosts",
        "LogPath": "/var/lib/docker/containers/ea5f8b2754a5965d9d818e15b5da919158f0b5cd1b58b27204c5ad34093af674/ea5f8b2754a5965d9d818e15b5da919158f0b5cd1b58b27204c5ad34093af674-json.log",
        "Name": "/k8s_install-cni_calico-node-pkbjn_calico-system_920f7c02-453e-4561-b97a-347df057fba0_0",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/opt/cni/bin:/host/opt/cni/bin",
                "/etc/cni/net.d:/host/etc/cni/net.d",
                "/var/lib/kubelet/pods/920f7c02-453e-4561-b97a-347df057fba0/volumes/kubernetes.io~secret/calico-node-token-gpcv6:/var/run/secrets/kubernetes.io/serviceaccount:ro,Z",
                "/var/lib/kubelet/pods/920f7c02-453e-4561-b97a-347df057fba0/etc-hosts:/etc/hosts:Z",
                "/var/lib/kubelet/pods/920f7c02-453e-4561-b97a-347df057fba0/containers/install-cni/ad15c0e7:/dev/termination-log:Z"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-size": "100m"
                }
            },
            "NetworkMode": "container:7fedb0a1ff83d814fcc01a0e9842ecd62dbf99a473e71610fd8c65e9b160b1d0",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
```
Can you check the container StartedAt and FinishedAt time as well as RestartPolicy and RestartCount of the initial container as well as the app container ?

**Comment by Bryce-huang** [comment]
I use the initcontainer of statefulset

like this pic :
![image](https://user-images.githubusercontent.com/44901318/103144341-f2c07b80-4762-11eb-84cc-10d04dcf5fa1.png)

This is the situation when I restarted the three master nodes（all nodes）


my test case:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app.kubernetes.io/instance: mariadb-galera
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-5.0.1
  name: mariadb-galera
  namespace: default
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mariadb-galera
      app.kubernetes.io/name: mariadb-galera
  serviceName: mariadb-galera-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mariadb-galera
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mariadb-galera
        helm.sh/chart: mariadb-galera-5.0.1
    spec:
      containers:
      - env:
        - name: MARIADB_ADDRESS
          value: mariadb-galera-headless.default.svc.cluster.local
        - name: NS
          value: default
        - name: REPLICAS
          value: "3"
        - name: MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP
          value: "yes"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: bryce_DEBUG
          value: "false"
        - name: MARIADB_GALERA_CLUSTER_NAME
          value: galera
        - name: MARIADB_GALERA_CLUSTER_ADDRESS
          value: gcomm://mariadb-galera-headless.default.svc.cluster.local
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-root-password
              name: mariadb-galera
        - name: MARIADB_DATABASE
          value: mos_plus
        - name: MARIADB_GALERA_MARIABACKUP_USER
          value: mariabackup
        - name: MARIADB_GALERA_MARIABACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-galera-mariabackup-password
              name: mariadb-galera
        - name: MARIADB_ENABLE_LDAP
          value: "no"
        - name: MARIADB_ENABLE_TLS
          value: "no"
        image: docker.io/bryce-huang/mariadb-init:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - bash
            - -ec
            - |
              exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: mariadb-galera
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        - containerPort: 4567
          name: galera
          protocol: TCP
        - containerPort: 4568
          name: ist
          protocol: TCP
        - containerPort: 4444
          name: sst
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - bash
            - -ec
            - |
              exec mysqladmin status -uroot -p$MARIADB_ROOT_PASSWORD
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/bryce/mariadb/.bootstrap
          name: previous-boot
        - mountPath: /bryce/mariadb
          name: data
        - mountPath: /opt/bryce/mariadb/conf/my.cnf
          name: mariadb-galera-config
          subPath: my.cnf
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - ' for i in $(seq 120 -1 1); do echo -e "$i/s";sleep 1; done'
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        name: init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccount: mariadb
      serviceAccountName: mariadb
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: previous-boot
      - configMap:
          defaultMode: 420
          name: mariadb-galera-configuration
        name: mariadb-galera-config
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mariadb-galera
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mariadb-galera
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 500Gi
      storageClassName: local-storage-db
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: mariadb-galera-5dc99c4bb7
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: mariadb-galera-5dc99c4bb7
  updatedReplicas: 3

```
