### ISSUE TITLE
IPVS: kube-proxy can not deletes old endpoints

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#97586]
**What happened**:
Reboot a master node host(193.116.4.32), kubernetes service ipvs rules can not be deleted, weight is still 1.
```
ipvsadm -ln -t 10.254.0.1:443
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.254.0.1:443 rr
  -> 193.116.4.31:6443            Masq    1      1          0
  -> 193.116.4.32:6443            Masq    1      3          1
```
but, in etcd endpoints only one:
```

/registry/services/endpoints/default/kubernetes
k8s

v1      Endpointsv
O

kubernetesdefault"*$dfe7ec28-831d-4fe4-8123-358133116c8f2▒▒▒z#
193.116.4.31
https 2TCP"

```
```
$ kubectl describe svc kubernetes
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:           #<none>
Type:              ClusterIP
IP:                10.254.0.1
IPFamily:          IPv4
Port:              https  443/TCP
TargetPort:        6443/TCP
Endpoints:         193.116.4.31:6443
Session Affinity:  None
Events:            <none>
```

add some logs in  
https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/pkg/proxy/ipvs/proxier.go#L1911
newEndpoints：
```
newEndpoints: sets.String{"193.116.4.31:6443":sets.Empty{}, "193.116.4.32:6443":sets.Empty{}}
```
There may be problems in this line:
https://github.com/kubernetes/kubernetes/blob/4fb7ed12476d57b8437ada90b4f93b17ffaeed99/pkg/proxy/ipvs/proxier.go#L1932

**What you expected to happen**:
I expected ipvs weight is 0 when a master node host reboot.

newEndpoints is:  sets.String{"193.116.4.31:6443":sets.Empty{}}

**How to reproduce it (as minimally and precisely as possible)**:
reboot master node
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.17.9
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by aojea** [comment]
/remove sig api-machinery
/sig network

can you paste the output of `kubectl get endpoints kubernetes -o yaml`

**Comment by chymy** [comment]
Befor reboot:
```yaml
$ kubectl get endpoints kubernetes -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2020-12-25T09:59:34Z"
  name: kubernetes
  namespace: default
  resourceVersion: "650989"
  selfLink: /api/v1/namespaces/default/endpoints/kubernetes
  uid: dfe7ec28-831d-4fe4-8123-358133116c8f
subsets:
- addresses:
  - ip: 193.116.4.31
  - ip: 193.116.4.32
  ports:
  - name: https
    port: 6443
    protocol: TCP
```
Rebooting(193.116.4.32):
```yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2020-12-25T09:59:34Z"
  name: kubernetes
  namespace: default
  resourceVersion: "651755"
  selfLink: /api/v1/namespaces/default/endpoints/kubernetes
  uid: dfe7ec28-831d-4fe4-8123-358133116c8f
subsets:
- addresses:
  - ip: 193.116.4.31
  ports:
  - name: https
    port: 6443
    protocol: TCP
```

**Comment by uablrek** [comment]
I think this is caused by a mismatch between endpoints and endpointslices. @chymy please try;
```
kubectl get endpointslices kubernetes
```
If I am right you should see both addresses while `endpoints` only have one. This would be a bug in K8s, both endpoints and endpointslices should be altered.

I don't have multiple masters so I have tested using a service without selector;
```
apiVersion: v1
kind: Service
metadata:
  name: mserver-nosel
spec:
  ports:
  - port: 5001
    name: mconnect
```
Then added endpoints and enpointslices;
```
apiVersion: discovery.k8s.io/v1beta1
kind: EndpointSlice
addressType: IPv4
metadata:
  name: mserver-nosel
  labels:
    kubernetes.io/service-name: mserver-nosel
endpoints:
- addresses:
  - 192.168.1.2
  - 192.168.1.3
ports:
- name: mconnect
  port: 5001
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mserver-nosel
subsets:
  - addresses:
      - ip: 192.168.1.3
    ports:
      - port: 5001
        name: mconnect
```
For some reason only the first address of the endpointslices is added but the problem can be seen anyway;
```
$ kubectl describe svc mserver-nosel
Name:              mserver-nosel
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                12.0.93.55
IPs:               12.0.93.55
Port:              mconnect  5001/TCP
TargetPort:        5001/TCP
Endpoints:         192.168.1.3:5001
Session Affinity:  None
Events:            <none>
$ ipvsadm -Ln | grep -A2 12.0.93.55
TCP  12.0.93.55:5001 rr
  -> 192.168.1.2:5001             Masq    1      0          0         
  -> 192.168.1.3:5001             Masq    1      0          0         
```
Two entries are in ipvs but only one endpoint. The other comes from endpointslices.

The behavior is the same for proxy-mode=iptables so this issue should not be unique for ipvs is my assumption is correct.
