### ISSUE TITLE
kubectl-convert cannot convert Ingress objects

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#97729]
**What happened**:

Tried to convert a v1beta1 Ingress object to v1, and received the following error:

```
kubectl-convert -f v1beta1.yaml 
error: unable to decode "v1beta1.yaml": no kind "Ingress" is registered for version "networking.k8s.io/v1beta1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"
```

**What you expected to happen**:

The conversion to work.

**How to reproduce it (as minimally and precisely as possible)**:

v1beta1.yaml:
```yaml
v1beta1.yaml 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example
spec:
  backend:
    serviceName: default-backend
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```

Then run:
```sh
kubectl-convert -f v1beta1.yaml 
```

/sig cli
/assign @soltysh
