### ISSUE TITLE
NewReplicaSet shows <none> when describing deployment

### ISSUE THREAD

**Issue by borgerli** [kubernetes/kubernetes#97750]
Create a deployment as described in `How to reproduce it` section, and run 'kubectl describe deploy/test`

**What happened**:
`NewReplicaSet` shows `<none>`, while `OldReplicaSets` shows the current replicaset infomation
```
OldReplicaSets:  test-857fb4848b (1/1 replicas created)
NewReplicaSet:   <none>
```

**What you expected to happen**:
`NewReplicaSet` shows the current replicaset infomation, while `OldReplicaSets` shows `<none>`
```
OldReplicaSets:  <none>
NewReplicaSet:   test-857fb4848b (1/1 replicas created)
```
**How to reproduce it (as minimally and precisely as possible)**:
Create a deployment as follows, and wait its pod started. Then, run 'kubectl describe deploy/test`

```
cat <<EOF | kubectl create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /tmp/second
          name: second-volume
        - mountPath: /tmp/first
          name: first-volume
      volumes:
      - name: first-volume
        emptyDir: {}
      - name: second-volume
        emptyDir: {}
EOF
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): kubectl of 1.14+(I did not try older versions)
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
