### ISSUE TITLE
Missing NodeSelector to Windows "creating a pod with dnsPolicy="  tests 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#97806]
**What happened**:

Some of our windows tests (in this case `should support configurable pod DNS servers`) dont add enough scheduling metadata to behave predictably in environments where, for example, `nodeSelector` is required to interpret a pods proper location.  A "bug" in EKS CNI actually causes EKS, for example, to not properly label such pods with IP addresses (because it uses an adm controller to add metadata before a pod is created, and that md is sent to eks's cni).  

In any case adding this metadata is a standard in Sig-windows, per conv with @jsturtevant  yesterday, so we'll want to add these in.

As an example of the test failure which results when you *dont* have this selector....  

```
  Warning  FailedCreatePodSandBox  4s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "a5bbadb66354bf873c4cb9a8238529db19fdf245fed3af29aac27fa052b03082" network for pod "e2e-dns-utils": networkPlugin cni failed to set up pod "e2e-dns-utils_dns-9723" network: failed to parse Kubernetes args: pod does not have label vpc.amazonaws.com/PrivateIPv4Address
```

Looking at the pod Spec: 

```
spec:
  containers:
  - args:
    - pause
    image: k8sprow.azurecr.io/kubernetes-e2e-test-images/agnhost:2.21
    imagePullPolicy: IfNotPresent
    name: agnhost-container
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-j4hl4
      readOnly: true
  dnsConfig:
    nameservers:
    - 1.1.1.1
    searches:
    - resolv.conf.local
  dnsPolicy: None
  enableServiceLinks: true
  nodeName: ip-192-168-7-64.us-west-2.compute.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-j4hl4
    secret:
      defaultMode: 420
      secretName: default-token-j4hl4
status:
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
