### ISSUE TITLE
Missing NodeSelector for "functioning NodePort" tests for windows

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#97807]
**What happened**:

Similar to #97805 , were missing the windows nodeselectors for this one...  resulting in failed pod sandboxes due to missing metadata, root cause is easy fix, will issue PR shortly

```
spec:
  volumes:
    - name: default-token-9c9ts
      secret:
        secretName: default-token-9c9ts
        defaultMode: 420
  containers:
    - name: netexec
      image: 'k8sprow.azurecr.io/kubernetes-e2e-test-images/agnhost:2.21'
      args:
        - netexec
        - '--http-port=80'
        - '--udp-port=80'
      resources: {}
      volumeMounts:
        - name: default-token-9c9ts
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readinessProbe:
        httpGet:
          path: /hostName
          port: 80
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 3
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: ip-192-168-7-64.us-west-2.compute.internal
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
```
