### ISSUE TITLE
External IP of externalTrafficPolicy Local service is unreachable from pods within the cluster on GCP

### ISSUE THREAD

**Issue by jatin-pathangi** [kubernetes/kubernetes#97836]
**What happened**:
I have a LoadBalancer type service whose externalTrafficPolicy is set to Local. I cannot reach the external IP address of the service from pods within the cluster that do not run on the same node as one of the service backend pods.  I am using iptables proxying

I can reach the external IP from outside the cluster, I can reach it from all the nodes within the cluster. I can reach it from pods that run on the same node as one of the backend pods.

This only happens on GCP (it works fine on Azure and AWS. i.e all pods can reach the external IP). Cluster is a self managed kubernetes cluster using iptables proxying. 

**When I change externalTrafficPolicy to Cluster, all pods can reach the external IP of the service**

**What you expected to happen**:
To be able to reach the external IP of the service from all pods inside the cluster when externalTrafficPolicy is set to Local

**How to reproduce it (as minimally and precisely as possible)**:
Using the below k8s version, create a simple nginx service that has externalTrafficPolicy set to Local, and try to telnet to the external IP from a pod that runs on a different node to which the nginx pods run on.

```
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: svc-jatin-test
      namespace: jatin-test
    spec:
      externalTrafficPolicy: Local
      loadBalancerSourceRanges:
        - 0.0.0.0/0
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: jatin-http
      selector:
        app: nginx
      type: LoadBalancer
kind: List
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jatin-nginx-deployment
  namespace: jatin-test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.1
          ports:
            - containerPort: 80
              protocol: TCP
              name: jatin-http
```

**Anything else we need to know?**:
This behavior works fine on AWS and Azure. All pods can reach the external IP of a service whose externalTrafficPolicy is Local on Azure and AWS clusters. 

**Environment**:
- Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.12", GitCommit:"17c50ce2d686f4346924935063e3a431360e0db7", GitTreeState:"clean", BuildDate:"2020-06-26T03:41:29Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.12", GitCommit:"17c50ce2d686f4346924935063e3a431360e0db7", GitTreeState:"clean", BuildDate:"2020-06-26T03:33:27Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: GCP

- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux kubernetes-master 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

- Network plugin and version (if this is a network-related bug): Flannel

- Others:

**Comment by aojea** [comment]
> This only happens on GCP (it works fine on Azure and AWS. i.e all pods can reach the external IP). Cluster is a self managed kubernetes cluster using iptables proxying.

@robscott @bowei can you also PTAL, it seems it happens in GCE only

**Comment by prameshj** [comment]
I see the network plugin used is Flannel. Does this happen with kubenet or other plugins as well?


I tried this on a GCE k8s cluster created via kubetest(running k8s from HEAD) and it works. This does not use Flannel.
Copied the yaml you posted above:

```
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: svc-jatin-test
      namespace: jatin-test
    spec:
      externalTrafficPolicy: Local
      loadBalancerSourceRanges:
        - 0.0.0.0/0
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: jatin-http
      selector:
        app: nginx
      type: LoadBalancer
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: jatin-nginx-deployment
      namespace: jatin-test
    spec:
      selector:
        matchLabels:
          app: nginx
      replicas: 1
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx
              image: nginx:1.16.1
              ports:
                - containerPort: 80
                  protocol: TCP
                  name: jatin-http
```

I deployed a test client pod in a different node than the nginx pods from above.

```
kubectl exec -it testclient --  wget -O - http://<externalIP>
Connecting to <externalip> 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>

```
