### ISSUE TITLE
How to avoid frequent refreshing of create-verb audit logs

### ISSUE THREAD

**Issue by njuptlzf** [kubernetes/kubernetes#97889]
I want to capture events `created `by pods/rc/deploy, and I want to see the correspondence between kubelet and pod, so that I can quickly locate the problem.
Kubelet updated the pod information with the `patch`, so I `had to` capture the `patch `request. 
This means that when the pod is repeatedly created for reasons such as `pulling bad images`, the log will be printed `wildly`.
Delete pod/rc also captures kubelet patch requests, which is unnecessary if you only want to capture delete logs

**Can the first `patch `information be disguised as `create` ?**
 I am keen to use the `Metadata `level because its log is much less than `Request`.
My current audit strategy is:
```
  - level: Metadata
    users:
    - system:node:192.168.122.1
    verbs:
    - patch
    resources:
    - group: "" # core
      resources:
      - pods/status
  - level: Metadata
    verbs:
    - create
    - delete
    resources:
    - group: ""
      resources:
      - pods
      - replicationcontrollers
```
If you think the idea is feasible, please guide me
