### ISSUE TITLE
Share PV across namespaces

### ISSUE THREAD

**Issue by tydra-wang** [kubernetes/kubernetes#97908]
**What would you like to be added**:

Share PV across namespaces

**Why is this needed**:

When I want to share a read-only ceph RBD volume across namespace, I found it's so tricky.

1. I can not create two pods with volume source pointing  to the same RBD. 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: rbd-pod-ro
spec:
  volumes:
    - name: test-rbd
      rbd:
        fsType: ext4
        image: 23a3c06e-21df-434b-8ea2-bd9e36b6a013
        keyring: /etc/ceph/keyring
        monitors:
        - 192.168.2.133
        - 192.168.2.134
        - 192.168.2.135
        pool: rbd
        readOnly: true
        secretRef:
          name: ceph
        user: admin
  containers:
  - name: kubia
    image: luksa/kubia
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /mnt/rbd
      name: test-rbd
```

If I set `spec.nodeName` of the second pod to a different node, kubelet failed to create pod:
```
Warning  FailedMount  0s    kubelet  MountVolume.WaitForAttach failed for volume "test-rbd" : rbd image rbd/23a3c06e-21df-434b-8ea2-bd9e36b6a013 is still being used
```

NOTE: I succeeded to create the second pod if it's scheduled to the same node with the first one.

2. I tried to use pv (ReadOnlyMany). It works (two pods mounting one pvc bound to this pv), but I cannot share it across namespace. 
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: fbs
spec:
  volumeName: test-pv
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
```
Maybe I can create two PVs(and PVCs) in two namespace? It's "tricky" when I want to share RBD dynamically among namespaces.
I started to wondering why PV can be bound with only one PVC.  Did I miss some things? Is there some other better way to do it?

some related discussions:
https://stackoverflow.com/questions/35364367/share-persistent-volume-claims-amongst-containers-in-kubernetes-openshift
https://stackoverflow.com/questions/50958765/shared-persistencevolumeclaimpvc-across-namespaces
