### ISSUE TITLE
mutating webhook v1beta1 bad key with server side apply

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#98024]
What I ran:
```
$ kubectl apply -f repro.yml
mutatingwebhookconfiguration.admissionregistration.k8s.io/test created
$ kubectl apply -f repro.yml --server-side
Error from server: failed to create typed patch object: .webhooks: duplicate entries for key [name="my.webhook.io"]
$ kubectl apply -f repro.yml --dry-run=client
mutatingwebhookconfiguration.admissionregistration.k8s.io/test created (dry run)
$ kubectl apply -f repro.yml --dry-run=server
mutatingwebhookconfiguration.admissionregistration.k8s.io/test created (server dry run)
```

With yaml:
```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: test
webhooks:
- name: my.webhook.io
  clientConfig:
    service:
      name: service
      namespace: default
      path: "/inject"
    caBundle: ""
  sideEffects: None
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Fail
  admissionReviewVersions: ["v1beta1", "v1"]
  namespaceSelector:
    matchExpressions:
    - key: something
      operator: In
      values:
      - enabled

- name: my.webhook.io
  clientConfig:
    service:
      name: service
      namespace: default
      path: "/inject"
    caBundle: ""
  sideEffects: None
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Fail
  admissionReviewVersions: ["v1beta1", "v1"]
  namespaceSelector:
    matchExpressions:
    - key: something
      operator: DoesNotExist
```

Two unexpected things here:
* `--dry-run=server` is not giving an error, but the real server side apply fails
* server side apply fails, the real one does not

Note: This is exclusive to the v1beta1 API. When using the `v1` API, its rejected for all modes.

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T22:31:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
