### ISSUE TITLE
Inconsistent garbage collection behavior when any ownerReference is unresolvable and the parent is deleted

### ISSUE THREAD

**Issue by margocrawf** [kubernetes/kubernetes#98040]
**What happened**:

- create a namespaced parent object (for example a `Secret`)
- delete the parent object
- create a cluster-scoped object (for example. an `ApiService`) with the parent as an `ownerReference`, which is unresolvable since the parent is namespaced.
- create a namespaced object (for example another `Secret`) in the same namespace, with the parent as an `ownerReference`, which should be valid.
- The namespaced child and the cluster-scoped child are not garbage collected.

**What you expected to happen**:

The namespaced child should be garbage collected immediately after being created, the cluster-scoped child should not be.

**Reproduction**:

**Setup**:
`kubectl create namespace test-owner-reference`

parent-secret.yaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: parent-secret
  namespace: test-owner-reference
data:
  a: Yg==
```

`kubectl apply -f /path/to/parent-secret.yaml`
`kubectl get secrets/parent-secret -n test-owner-reference -o yaml | grep uid`

cluster-scoped-child.yaml:
```
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cluster-scoped-child
  ownerReferences:
  - apiVersion: v1
     kind: Secret
     name: parent-secret
     uid: <parent uid>
  spec:
   group: cluster-scoped-child
   groupPriorityMinimum: 1000
   versionPriority: 15
   service:
     name: api
     namespace: cluster-scoped-child
   version: v1alpha1
```
namespaced-child.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: namespaced-child
  namespace: test-owner-reference
  ownerReferences:
    - apiVersion: v1
      kind: Secret
      name: parent-secret
      uid: <parent uid>
data:
  a: Yg==
```

**Scenario 1**:
1. In one terminal, run `kubectl get secrets -n test-owner-reference --watch`
2. In another, `run kubectl get apiservice --watch`
3. In a third, run `kubectl delete secrets/parent-secret -n test-owner-reference && kubectl apply -f /path/to/cluster-scoped-child.yaml && kubectl apply -f /path/to/namespaced-child.yaml`

See that the cluster scoped child and namespaced child are both created but not deleted.

**Scenario 2**:
1. In one terminal, run `kubectl get secrets -n test-owner-reference --watch`
3. In another, run `kubectl delete secrets/parent-secret -n test-owner-reference &&  kubectl apply -f /path/to/namespaced-child.yaml`

See that the namespaced child is created and immediately deleted.

My expectation is that the garbage collection of `namespaced-child` should not depend on `cluster-scoped-child`, however scenarios 1 and 2 do not seem consistent.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.0
- Cloud provider or hardware configuration: Kind 1.20.0
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
