### ISSUE TITLE
kube-proxy would not update iptables rules when pod selectors are used for service

### ISSUE THREAD

**Issue by ipatrykx** [kubernetes/kubernetes#98066]
**What happened**:

After deploying pod and service with selector and changing the endpoint using kubectl apply, the endpoint's IP reported by `kubectl get ep` is updated to new value but iptables rules are not being updated. The same operation works if service is deployed without selector.

**What you expected to happen**:

After applying new definition of endpoint I would expect that IP address reported by `kubectl get ep` and iptables rules would be updated to newly applied values.

**How to reproduce it (as minimally and precisely as possible)**:

Simple nginx pod and service with app selector are applied:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
  restartPolicy: Always
```

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
```

The pod, service and endpoint is successfully created:

```
[root@virtual1 ~]# kubectl get pod -o wide
NAME        READY   STATUS    RESTARTS   AGE   IP             NODE       NOMINATED NODE   READINESS GATES
nginx-pod   1/1     Running   0          8m    10.244.0.160   virtual1   <none>           <none>

[root@virtual1 ~]# kubectl get svc
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
kubernetes      ClusterIP   10.96.0.1        <none>        443/TCP   14d
nginx-service   ClusterIP   10.111.147.147   <none>        80/TCP    9m32s

[root@virtual1 ~]# kubectl get ep
NAME            ENDPOINTS             AGE
kubernetes      192.168.122.58:6443   14d
nginx-service   10.244.0.160:9999     9m33s
```

iptables rules are also created by kube-proxy:

```
[root@virtual1 ~]# iptables-save | grep nginx-service
-A KUBE-SEP-FXSJGQ4NBPW72IH6 -s 10.244.0.160/32 -m comment --comment "default/nginx-service" -j KUBE-MARK-MASQ
-A KUBE-SEP-FXSJGQ4NBPW72IH6 -p tcp -m comment --comment "default/nginx-service" -m tcp -j DNAT --to-destination **10.244.0.160**:9999
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.111.147.147/32 -p tcp -m comment --comment "default/nginx-service cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.111.147.147/32 -p tcp -m comment --comment "default/nginx-service cluster IP" -m tcp --dport 80 -j KUBE-SVC-V2OKYYMBY3REGZOG
-A KUBE-SVC-V2OKYYMBY3REGZOG -m comment --comment "default/nginx-service" -j KUBE-SEP-FXSJGQ4NBPW72IH6
```

Now I would like to change the endpoint's address, so I apply endpoint with the same same name as already existing endpoint but with different address (192.0.42.101 instead of 10.244.0.160 in my example):

```
apiVersion: v1
kind: Endpoints
metadata:
  name: nginx-service
subsets:
  - addresses:
      - ip: 192.0.42.101
    ports:
      - port: 9999
```

Right after that I check with `kubectl get ep` if the IP was updated, and it is:

```[root@virtual1 ~]# kubectl get ep
NAME            ENDPOINTS             AGE
kubernetes      192.168.122.58:6443   14d
nginx-service   192.0.42.101:9999     23m
```

However iptables still uses the same address as before (10.244.0.160 here):

```
[root@virtual1 ~]# iptables-save | grep nginx-service
-A KUBE-SEP-FXSJGQ4NBPW72IH6 -s 10.244.0.160/32 -m comment --comment "default/nginx-service" -j KUBE-MARK-MASQ
-A KUBE-SEP-FXSJGQ4NBPW72IH6 -p tcp -m comment --comment "default/nginx-service" -m tcp -j DNAT --to-destination 10.244.0.160:9999
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.111.147.147/32 -p tcp -m comment --comment "default/nginx-service cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.111.147.147/32 -p tcp -m comment --comment "default/nginx-service cluster IP" -m tcp --dport 80 -j KUBE-SVC-V2OKYYMBY3REGZOG
-A KUBE-SVC-V2OKYYMBY3REGZOG -m comment --comment "default/nginx-service" -j KUBE-SEP-FXSJGQ4NBPW72IH6
```

**Anything else we need to know?**:

What I've tried to do, works perfectly well when service is not using selectors, eg, applying:

```
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999

apiVersion: v1
kind: Endpoints
metadata:
  name: test-service
subsets:
  - addresses:
      - ip: 192.0.42.101
    ports:
      - port: 9999

 ```

will result in following iptables:

```
[root@virtual1 ~]# iptables-save | grep test-service
-A KUBE-SEP-UDFPMNWDCHTE2OML -s 192.0.42.101/32 -m comment --comment "default/test-service" -j KUBE-MARK-MASQ
-A KUBE-SEP-UDFPMNWDCHTE2OML -p tcp -m comment --comment "default/test-service" -m tcp -j DNAT --to-destination 192.0.42.101:9999
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.98.159.247/32 -p tcp -m comment --comment "default/test-service cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.98.159.247/32 -p tcp -m comment --comment "default/test-service cluster IP" -m tcp --dport 80 -j KUBE-SVC-AEJ565DT7YN2S3PD
-A KUBE-SVC-AEJ565DT7YN2S3PD -m comment --comment "default/test-service" -j KUBE-SEP-UDFPMNWDCHTE2OML
[root@virtual1 ~]# 
```

Applying new endpoint on top of that:

```
apiVersion: v1
kind: Endpoints
metadata:
  name: test-service
  annotations:
    endpointType: "secondary"
subsets:
  - addresses:
      - ip: 200.0.0.200
    ports:
      - port: 9999
```

results in updated iptables:

```
[root@virtual1 ~]# iptables-save | grep test-service
-A KUBE-SEP-CR74YFSMMWL6MICX -s 200.0.0.200/32 -m comment --comment "default/test-service" -j KUBE-MARK-MASQ
-A KUBE-SEP-CR74YFSMMWL6MICX -p tcp -m comment --comment "default/test-service" -m tcp -j DNAT --to-destination 200.0.0.200:9999
-A KUBE-SERVICES ! -s 10.244.0.0/16 -d 10.98.159.247/32 -p tcp -m comment --comment "default/test-service cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.98.159.247/32 -p tcp -m comment --comment "default/test-service cluster IP" -m tcp --dport 80 -j KUBE-SVC-AEJ565DT7YN2S3PD
-A KUBE-SVC-AEJ565DT7YN2S3PD -m comment --comment "default/test-service" -j KUBE-SEP-CR74YFSMMWL6MICX
```

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.6.1810 (Core) 
- Kernel (e.g. `uname -a`): Linux virtual1 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): n/a
- Others: n/a
