### ISSUE TITLE
Error: client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: connect: connection refused

### ISSUE THREAD

**Issue by ThePieMonster** [kubernetes/kubernetes#98149]
**What happened**:
Created a K8S cluster with 1 control plane node using `kubeadm init --config /home/kube/kubeadmn-config.yaml --upload-certs`

_kubeadmn-config.yaml_
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://10.1.50.250:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

_kubectl get pods --all-namespaces_
```
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-744cfdf676-vf6fw   1/1     Running   0          16h
kube-system   calico-node-plsv4                          1/1     Running   0          16h
kube-system   coredns-74ff55c5b-btdsr                    1/1     Running   0          17h
kube-system   coredns-74ff55c5b-q66c9                    1/1     Running   0          17h
kube-system   etcd-k8s-master-0                          1/1     Running   0          17h
kube-system   kube-apiserver-k8s-master-0                1/1     Running   0          17h
kube-system   kube-controller-manager-k8s-master-0       1/1     Running   0          17h
kube-system   kube-proxy-7jqx9                           1/1     Running   0          17h
kube-system   kube-scheduler-k8s-master-0                1/1     Running   0          17h
```

Attempted to add a second control plane node using `kubeadm join 10.1.50.250:6443 --token v585r6.6ayp6fvu65hmkx7z --discovery-token-ca-cert-hash sha256:bfeeda1d85202e28d4f944b0d40c53c3d3fadb347bca986fb7efa911510f82c7 --control-plane --certificate-key 033d5722def17eca68fa3d83a4aff82112955a06819b32f513be0440ac1d8b4c --v=5`.

Second node failed to add, also broke both nodes.

**What you expected to happen**:
The second control plane node gets added to the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Copy above config file and run the create cluster command. Both control plane nodes run Ubuntu 18.04.

**Anything else we need to know?**:
_etcdctl --version_
> etcdctl version: 3.2.17
> API version: 2

_etcdctl cluster-health_
> cluster may be unhealthy: failed to list members
> Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:4001: connect: connection refused
> ; error #1: EOF
> 
> error #0: dial tcp 127.0.0.1:4001: connect: connection refused
> error #1: EOF

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.1
- Cloud provider or hardware configuration: Bare metal
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.15.0-130-generic
