### ISSUE TITLE
including a ':' in oidc-groups-prefix does not behave as it should for kubelet / kube-apiserver 

### ISSUE THREAD

**Issue by benfiedler** [kubernetes/kubernetes#98148]
Using 'oidc:' in the --oidc-groups-prefix as [suggested by the documentation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server) does not behave well

Relevant parts of kube-apiserver.yaml
```
spec:
  containers:
  - command:
    - kube-apiserver
    - --oidc-issuer-url=https://my.dex.host/api/dex
    - --oidc-client-id=kubernetes
    - --oidc-username-claim=email
    - --oidc-groups-claim=groups
```

The behavior is different depending on how I specify the same string.

### Result: 
Error in kubelet log, api pod cannot start
`kubelet[32173]: E0118 13:02:42.638837   32173 file.go:187] Can't process manifest file "/etc/kubernetes/manifests/kube-apiserver.yaml": /etc/kubernetes/manifests/kube-apiserver.yaml: couldn't parse as pod(v1.Pod.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Command: []string: ReadString: expects " or n, but found {, error found in #10 byte of ...|belogin",{"--oidc-gr|..., bigger context ...|dex.host/api/dex","--oidc-client-id=kubernetes",{"--oidc-groups-prefix=oidc":null},"--oidc-username|...), please check config file`

### Result:
kube-apiserver starts, but an audit shows the result of groups is includes "oidc:"infra , i.e. the value quotes are being added

```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","auditID":"XXX","stage":"ResponseComplete","requestURI":"/api/v1/nodes?limit=500","verb":"list","user":{"username":"some.user@example.com","groups":["\"oidc:\"infra","system:authenticated"]},
```

### Result:
Very similar to previous attempt, but instead of the prefix enclosed in \" it's just ' for the group
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","auditID":"XXX","stage":"ResponseComplete","requestURI":"/api/v1/nodes?limit=500","verb":"list","user":{"username":"some.user@example.com","groups":["'oidc:'infra","system:authenticated"]},
```
This one I can actually get to work with a rolebinding using this monstronsity:
```
subjects:
- kind: Group
  name: "'oidc:'infra"
  apiGroup: rbac.authorization.k8s.io
```

**What you expected to happen**:
In all cases I would expect the group to be identified as as "oidc:infra". None of the other values containing a ":" in the kube-apiserver.yaml need special care / quote encapsulation.

**Environment**:
- Kubernetes 1.18.8
  kubelet.x86_64                    1.18.8-0
  kubectl.x86_64                    1.18.8-0
- OS: CentOS Linux release 7.7.1908 (Core)
- Kernel: 3.10.0-1062.1.1.el7.x86_64 #1 SMP
