### ISSUE TITLE
AzureDisk plugin can't provision "kind: dedicated" volumes

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#98234]
**What happened**:
Using this StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurediskdedicated
provisioner: kubernetes.io/azure-disk
parameters:
  kind: dedicated
  storageaccounttype: Standard_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Volume provisioning fails with:
```
I0120 17:59:27.455266       1 pv_controller.go:1610] failed to save volume "pvc-984f8276-52dc-41a3-9a77-a2ea24139d5d" for claim "default/testclaim": persistentvolumes "pvc-984f8276-52dc-41a3-9a77-a2ea24139d5d" is forbidden: error querying AzureDisk volume jsafrane-1-lkb56-dynamic-pvc-984f8276-52dc-41a3-9a77-a2ea24139d5d: invalid disk URI: https://clusterp1uo5.blob.core.windows.net/vhds/jsafrane-1-lkb56-dynamic-pvc-984f8276-52dc-41a3-9a77-a2ea24139d5d.vhd
```

The error comes from admission plugin that adds / sets labels to PersistentVolume object. It expects that `https://clusterp1uo5....` has a very specific format, which "dedicated" disks don't have:

https://github.com/kubernetes/kubernetes/blob/106bc7e50d6dfdacbaa4be93f35c1af7a946a10d/staging/src/k8s.io/legacy-cloud-providers/azure/azure_managedDiskController.go#L324-L330

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.1

cc @andyzhangx
