### ISSUE TITLE
enhancement: provide a list of images and not a single one to pickup private registry before internet one

### ISSUE THREAD

**Issue by strus38** [kubernetes/kubernetes#98268]
**Current behavior**
In the container section, it is only possible to specify an image from a single registry.
Exemple:
```
containers:
      - name: slurm
        image: strusfr/docker-ubuntu1604-slurmctld:latest
        imagePullPolicy: Always
```

**Proposal**
The idea would be to be able to specify multiple image paths taken in a priority order (first success first pick), so K8S can pull in a private registry before looking on internet for exemple, like this:
```
containers:
      - name: slurm
        image:
            - k8s-master:31320/docker-ubuntu1604-slurmctld:v1.2.0
            - strusfr/docker-ubuntu1604-slurmctld:latest
        imagePullPolicy: Always
```

**Use case:**
I deploy a new cluster, all is coming from internet since my private registry will be deployed on K8S, and it would be empty until I populate it correctly, but once populated, I would like that any further deployment grab the images from the private registry instead of internet to speed things up without updating all my deployment files.

**Impacts**
None, it is compatible with current behavior if only 1 image is specified.

Thanks!

/sig cluster-lifecycle
