### ISSUE TITLE
kube-proxy flags are not respected when using config file together

### ISSUE THREAD

**Issue by borgerli** [kubernetes/kubernetes#98302]
1. With following config file and start kube-proxy with flags `--config=/tmp/kube-proxy.yaml --master=https://localhost:6443 --profiling=true`. 
```
cat <<EOF > /tmp/kube-proxy.yaml
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clientConnection:
  kubeconfig: /var/run/kubernetes/kube-proxy.kubeconfig
hostnameOverride: 127.0.0.1
mode:
featureGates:
  AllAlpha: false
EOF
```

2. Try to access the debug endpoint, you'll get 404
```
curl 127.0.0.1:10249/debug/pprof/
404 page not found

```

Actually, not only the `profiling` flag does not take effect, all other flags which are not set in config file, are all changed to default value and then do not take effect.
