### ISSUE TITLE
Dependent Environment in Configmap

### ISSUE THREAD

**Issue by abprohorov** [kubernetes/kubernetes#98319]
**What happened**:
Dependent environment loaded from configmap not changed.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ cat <<EOF > env.vars
REDIS_HOST=redis
REDIS_PASS=secret
REDIS_ZDSN=redis://$(REDIS_PASS)@$(REDIS_HOST):6379/0
EOF
$ kubectl create cm vars --from-env-file=env.vars
$ cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: web
      image: nginx
      envFrom:
      - configMapRef:
          name: vars
EOF
$ kubectl -n test exec nginx -- env | grep -i redis
REDIS_HOST=redis
REDIS_PASS=secret
REDIS_ZDSN=redis://$(REDIS_PASS)@$(REDIS_HOST):6379/0
```

If I move REDIS_ZDSN variable to manifest its work
```
$ cat <<EOF > env.vars
REDIS_HOST=redis
REDIS_PASS=secret
EOF
$ kubectl create cm new-vars --from-env-file=env.vars
$ cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: new-nginx
spec:
  containers:
    - name: web
      image: nginx
      envFrom:
      - configMapRef:
          name: new-vars
      env:
      - name: REDIS_ZDSN
        value: "redis://$(REDIS_PASS)@$(REDIS_HOST):6379/0"
EOF
$ kubectl -n test exec new-nginx -- env | grep -i redis
REDIS_HOST=redis
REDIS_PASS=secret
REDIS_ZDSN=redis://secret@redis:6379/0
```

What am I doing wrong?

**Environment**:
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by pacoxu** [comment]
```
➜  test cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: new-nginx
spec:
  containers:
    - name: web
      image: nginx-new
      envFrom:
      - configMapRef:
          name: new-vars
      env:
      - name: REDIS_ZDSN
        value: "redis://$(REDIS_PASS)@$(REDIS_HOST):6379/0"
EOF
zsh: command not found: REDIS_PASS
zsh: command not found: REDIS_HOST
pod/new-nginx created
```
indeed, REDIS_PASS is loaded from your bash env.
