### ISSUE TITLE
set limit on how much space an hostpath volume can consume 

### ISSUE THREAD

**Issue by chengzj12** [kubernetes/kubernetes#98397]
I use a volume with hostPath, so I can share files between my local host and the pods. My question is: Is there a way to limit how much sapce an hostpath volume can consume by those pods, like ephemeral storage request/limit? What happens if the container consumed all space on host's local directory?
```
      volumes:
      - hostPath:
          path: "/search/data/app"
        name: app
```
