### ISSUE TITLE
Endpoints of Headless Service disappear after 12 hours when deployed

### ISSUE THREAD

**Issue by pmbibe** [kubernetes/kubernetes#98399]
**What happened**:
When I deployed new Headless Services, which had Endpoints were external server, I mean Servers were not in Kubernetes Cluster. After a day I deployed. Endpoints of this Services became None. So I have to redeploy Endpoints.
**What you expected to happen**:
I do not want these Endpoints disappear and I do not need redeploy Endpoints
**How to reproduce it (as minimally and precisely as possible)**:
**Anything else we need to know?**:
**Environment**:
- Kubernetes version (use `kubectl version`):
```bash
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```bash
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```bash
Linux master1 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
In my Garafana, I saw that, at 5:10a.m, Prometheus can not get any metrics from this server. And at 8:35am, I had to redeploy these Endpoints
![image](https://user-images.githubusercontent.com/53257014/105800449-a1d4ba80-5f8e-11eb-81ce-ade8adf44bf9.png)
File configuration:
+ Endpoints.yaml
```yaml
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: jenkins
    monitoring.coreos.com: "true"
  name: expose-jenkins-metrics
  namespace: cattle-prometheus
subsets:
- addresses:
  - ip: 192.168.67.74
  ports:
  - name: prometheus
    port: 8080
    protocol: TCP
```
+ Service.yaml
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: expose-jenkins-metrics
  namespace: cattle-prometheus
  labels:
    k8s-app: jenkins
    monitoring.coreos.com: "true"
spec:
  clusterIP: None
  ports:
  - name: prometheus
    port: 8080
    protocol: TCP
  selector:
    k8s-app: jenkins
    monitoring.coreos.com: "true"
```
![image](https://user-images.githubusercontent.com/53257014/105800688-3d662b00-5f8f-11eb-94c3-e837e901f2ec.png)
