### ISSUE TITLE
Windows Container stuck in Initializing

### ISSUE THREAD

**Issue by cdavidbrewer** [kubernetes/kubernetes#98444]
**What happened**: This is an AKS (Azure) Cluster. A windows pod has 2 containers. The first container initializes a volume and completes successfully. The second container is a IIS Website which sits in "Initializing" and never starts. 
This happens roughly 4/10 times.
There are no logs from the container.
If we delete the pod, the ReplicaSet creates a new pod which also fails in this way roughly 4/10 times. If the container is still stuck in initializing we can delete the pod again, the third pod always works.

**What you expected to happen**: The second container should start or at least give logs.

**How to reproduce it (as minimally and precisely as possible)**: This only happens in our development cluster. I cannot reproduce it in other clusters. To reproduce, we create a new pod.

**Anything else we need to know?**: There are plenty of resources. We added more nodes and everything is underutilized. We Stopped and then Started the cluster (https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster) which also re-creates all of the nodes. We upgraded the Kubernetes and Nodes Versions to the latest.

This issue occurs with just a single pod, and also if I scale up the number of replicas. If I increase the replicas from 1 to 7, 3 of the pods will get stuck in "initializing" but the other 4 will start successfully.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.3
- Cloud provider or hardware configuration: Azure AKS
- OS (e.g: `cat /etc/os-release`): Windows 2019
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jsturtevant** [comment]
Could you share some kubelet logs and what a sample pod spec looks like?  I've tried to reproduce this in a cluster with a pod spec like the following and was not able to.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-container
  template:
    metadata:
      labels:
        app: init-container
    spec:
      initContainers:
      - name: init-test
        image: e2eteam/busybox:1.29
        command:
        - cmd
        - /c
        - touch
        - c:\shared\somefile.txt
        - '&&'
        - cmd
        - /c
        - sleep
        - "60"
        - '&&'
        - cmd
        - /c
        - IF
        - NOT
        - EXIST
        - c:\shared\folder
        - mkdir
        - c:\shared\folder
        - '&&'
        - cmd
        - /c
        - curl.exe
        - -L
        - https://gist.githubusercontent.com/jsturtevant/a8caf0d86c8f5bf1d7a1800760b8bc95/raw/932a1019735e2b207e69dd057f5c16b5a97d8975/webrequest.ps1
        - -o
        - c:\shared\webrequest.ps1
        - '&&'
        - sleep
        - "40"
        volumeMounts:
          - mountPath: /shared
            name: shared-volume
      containers:
      - image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        name: main-container
        volumeMounts:
          - mountPath: /shared
            name: shared-volume
        lifecycle:
          postStart:
            exec:
              command:
              - cmd
              - /c
              - mklink
              - /d
              - c:\inetpub\wwwroot\testfolder
              - c:\shared\folder
              - '&&'
              - cmd
              - /c
              - mklink
              - c:\inetpub\wwwroot\somefile.txt
              - c:\shared\somefile.txt
              - '&&'
              - Powershell
              - c:\shared\webrequest.ps1
              - -url
              - http://bing.com
      nodeSelector:
        beta.kubernetes.io/os: windows
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: shared-volume
---
apiVersion: v1
kind: Service
metadata:
  name: init-container
  labels:
    app: init-container
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8080
  selector:
    app: init-container
  type: LoadBalancer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shared-volume
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: shared-volume
  resources:
    requests:
      storage: 5Gi
```
