### ISSUE TITLE
NodePort service in ipvs mode depends on INPUT chain policy to be accessible externally

### ISSUE THREAD

**Issue by hanlins** [kubernetes/kubernetes#98465]
**What happened**:
Similar to https://github.com/kubernetes/kubernetes/issues/97225, when `INPUT` chain in `filter` table has policy `DROP`, node port service in `ipvs` mode is not working.

**What you expected to happen**:
`ipvs` mode for `kube-proxy` should have consistent behavior as `iptables` mode. For `iptables` mode, even if we change policy for `INPUT` chain to `DROP`, we can still access the node port service.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure kube-proxy to ipvs mode. My environment was using `iptables` mode during bootstrap so I have to change the proxy mode from `iptables` to `ipvs`. What I did is just change the `mode` field in `kube-proxy` configmap (in `kube-system` namespace) from `""` to `"ipvs"`.

Also, to eliminate the impacts from the `iptables` mode, I have to remove all chains/rules created in that mode. What I did is use `iptables-save > <filename>` to dump the iptable and remove all lines containing `KUBE`, then use `iptables-restore < <filename>` to restore the iptable.
2. Deploy the following service and workload:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: us.gcr.io/google-containers/nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30010
```
3. Change the policy of `INPUT` chain in `filter` table to `DROP`. Notice if you don't have any rule allowing ssh or loopback interface traffic, you'd better add rules to allow them before changing the policy. Here's what I did:
```
iptables -A INPUT -p tcp --dport ssh -j ACCEPT -m comment --comment "Accept SSH traffic"
iptables -A INPUT -i lo -j ACCEPT -m comment --comment "Accept loopback interface traffic"
iptables -P INPUT DROP
```
4. Then curl the node port service at `<node/external/IP>:30010`. Won't be able to access the service. If you switch the `kube-proxy` mode back to `iptables` mode, then it works.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `1.20.2`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): antrea
- Others:
