### ISSUE TITLE
After kubectl taint node, taint time will not be recorded

### ISSUE THREAD

**Issue by wawa0210** [kubernetes/kubernetes#98482]
**What happened**:

When executing `kubectl taint node`, the taint time should not be added to the taints data structure, it is not actually recorded

as example
```
kubectl taint no 10-7-106-201  node-role.kubernetes.io/master:NoExecute
node/10-7-106-201 tainted

[root@10-7-106-201 ~]# kubectl get no 10-7-106-201 -o yaml | grep -5 'NoExecute'
spec:
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
  taints:
  - effect: NoExecute
    key: node-role.kubernetes.io/master
status:
  addresses:
  - address: 10.7.106.201
    type: InternalIP

```
We can see that the taint time is not recorded

**What you expected to happen**:

taint should record the operating time

Normally it should be as follows

```
kubectl taint no 10-7-106-201  node-role.kubernetes.io/master:NoExecute
node/10-7-106-201 tainted

[root@10-7-106-201 ~]# kubectl get no 10-7-106-201 -o yaml | grep -5 'NoExecute'
spec:
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
  taints:
  - effect: NoExecute
    key: node-role.kubernetes.io/master
    timeAdded: "2021-01-27T14:53:30Z"
status:
  addresses:
  - address: 10.7.106.201
    type: InternalIP
```

**How to reproduce it (as minimally and precisely as possible)**:
Execute `kubectl taint node`, then `kubectl describe no`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:
