### ISSUE TITLE
kubelet don't cleanup duplicated running containers

### ISSUE THREAD

**Issue by chenyw1990** [kubernetes/kubernetes#98520]
**What happened**:
In our cluster, a node's docker has some problem. after the node restarts, the docker response is very slow. after all pods become running, we find that a pod on this node has duplicated running containers. 

**What you expected to happen**:
kubelet’s ContainerGC can cleanup duplicated running containers

**How to reproduce it (as minimally and precisely as possible)**:
I simulate the problem scenario by restarting the exited container

1、create a pod on a node, you can use this deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test1
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        command: ["sleep", "1000000"]
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
        ports:
        - containerPort: 81
          name: test
```
2、after pod running, log in to the node where the pod is located, kill the container:
![image](https://user-images.githubusercontent.com/1468240/106120250-1c6d2800-6191-11eb-8008-f6f089a561dc.png)

3, start the exited container:
![image](https://user-images.githubusercontent.com/1468240/106120481-63f3b400-6191-11eb-8f11-a85b4045073c.png)

then, two duplicated containers will running on the node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):v1.20.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):20.04.1 LTS (Focal Fossa)
- Kernel (e.g. `uname -a`):Linux ecs-linux-0008-43ee 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:
