### ISSUE TITLE
need to keep the application running, but require the restart of an entire pod instead of just a container

### ISSUE THREAD

**Issue by PaulCharlton** [kubernetes/kubernetes#98539]
#24725 

**What would you like to be added**:

.spec.template.spec.restartPolicy [pod spec] must allow values other than "Always"

**Why is this needed**:

see #24725

This requirement is especially true for single-container pods.   The pod state [volume mounts, networking] can get corrupted and cause a container restart.   If the pod does not restart, the stale/corrupted state is still present when the container restarts -- rinse, wash, repeat [over and over]

We have this problem with one of our production deployments, where only a manual "rollout restart" or manual deletion of the pods corrects the problem.   Automation would be better than manual remediation,.

**Comment by PaulCharlton** [comment]
/sig architecture
/sig apps
/wg "k8s infra"

relationship of pod lifecycles to container lifecycles

**Comment by gjkim42** [comment]
Could you give us your deployment.yaml ? :)

**Comment by PaulCharlton** [comment]
@gjkim42 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cf-atrius-objects-api-docker.fullname" . }}
  labels:
    {{- include "cf-atrius-objects-api-docker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cf-atrius-objects-api-docker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cf-atrius-objects-api-docker.selectorLabels" . | nindent 8 }}
      {{- if ( or .Values.config.environment .Values.config.secrets ) }}
      annotations:
        {{- if .Values.config.environment }}
        checksum/environment: {{ tpl (toYaml .Values.config.environment) . | sha256sum }}
        {{- end }}
        {{- if .Values.config.secrets }}
        checksum/secrets: {{ tpl (toYaml .Values.config.secrets) . | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
      restartPolicy: 'Always'
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cf-atrius-objects-api-docker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: '{{ template "cf-atrius-objects-api-docker.fullname" . }}-env'
            - secretRef:
                name: '{{ template "cf-atrius-objects-api-docker.fullname" . }}-senv'
          env:
            - name: STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: STATSD_PORT
              value: "8125"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

**Comment by PaulCharlton** [comment]
@gjkim42 

we get the following if we insert the value `Never`

```
LOGGING: Error: UPGRADE FAILED: cannot patch "<redacted>" with kind Deployment: Deployment.apps "<redacted>" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Never": supported values: "Always"
```

**Comment by PaulCharlton** [comment]
see also: https://stackoverflow.com/questions/59301413/set-pod-restart-limit

being able to automatically restart a "pod" is essential for many failure modes.   it happens automatically when a node is drained or goes out of service.    One major point of having N replicas where N is greater than 1 is so that the LB can continue routing to the good pods while something takes care of the bad pod.

**Comment by gjkim42** [comment]
How can we reproduce the case that restarting a container can't address the failure but restarting a corresponding pod can address the failure?
If there is a case, I want to address it.
/assign

**Comment by PaulCharlton** [comment]
@gjkim42 it will be fairly easy to produce a synthetic case that demonstrates the issue.   basically have the container exit with error when it sees a certain file in an ephemeral volume mount on the pod.    inject the file via kubectl exec into that container to trigger the test.   container restart will still see the file, pod restart will clear the file.

**Comment by gjkim42** [comment]
@PaulCharlton 
As you mentioned, we can reproduce the buggy case.

Here is the yaml file.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: watch-file
  name: watch-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: watch-file
  template:
    metadata:
      labels:
        app.kubernetes.io/name: watch-file
    spec:
      containers:
      - image: busybox:latest
        command:
        - /bin/sh
        args:
        - -c
        - while true; do sleep 1; echo "watch /cache/init_file"; if [[ -e /cache/init_file ]]; then exit 1; fi; done
        imagePullPolicy: IfNotPresent
        name: watch-file
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
      restartPolicy: Always
```

1. create deployment
2. `kubectl exec watch-file-xxx -- /bin/sh -c "touch /cache/init_file"`

then, the container inside of the pod will infinitely restart with error until manually restart the pod.
<img width="605" alt="Screen Shot 2021-01-30 at 7 28 45 AM" src="https://user-images.githubusercontent.com/19814047/106333831-cf8e6c00-62cc-11eb-8ae6-e147fab9c49d.png">
