### ISSUE TITLE
Service refuses traffic to endpoints after updating the selected pod label

### ISSUE THREAD

**Issue by CapOM** [kubernetes/kubernetes#98570]
**What happened**:

When the pod label selector is "updated" right after creating the service, the Pod, through the service, is only accessible after the next iptables sync period, which can be between 10s and 1min in GKE.

During this period the client get a "connection refused" whereas when watching the endpoints for the given service it is shown that the endpoints 's "ready" ip address is already present and equal to the pod's ip.

**What you expected to happen**:

The pod should be accessible within a few milliseconds through the service dns"my-service.my-ns.svc.cluster.local" like if the pod had already the final selected label.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a pod with label info=0
2. Create a ClusterIP service with selector info=1
3. Update label of pod to info=1

**Anything else we need to know?**:

If you set info=1 in step 1 then the pod is accessible through the service within milliseconds (so does not rely on the iptables sync period)

In kube-proxy-gke pods the parameters are --iptables-sync-period=1m --iptables-min-sync-period=10s

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.17.14
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04

**Comment by CapOM** [comment]
Here is a more detailed steps to reproduce:

You need 3 files:

busybox-pod.yaml:

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```

nginx-pod.yaml:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app:
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
  restartPolicy: Always
```

nginx-service.yaml:

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
```

Then deploy the nginx pod and busybox pod:

```
kubectl create -f busybox-pod.yaml
kubectl create -f nginx-pod.yaml
```


Then exec into busybox:

`kubectl exec -ti busybox -- /bin/sh`

And run

`while true; do wget -O- http://nginx-service.default.svc.cluster.local:8080; sleep 0.5; done`

Then open a second terminal and run:

```
kubectl create -f nginx-service.yaml; kubectl label pod nginx --overwrite app=nginx; kubectl get endpoints --watch
```

When the endpoints shows an ip then switch back to the first terminal and count the number of following connection refused (ignore the previous ones)

Each connection refused is 1s and plus 0.5s sleep, so around 4*1.5=6s

Also note that if I do the same but except the label change, i.e. where the label of the pod already matches the service's selector, then when creating the service the wget succeeds right away.

**Comment by gjkim42** [comment]
I would like to address this.
/assign

**Comment by gjkim42** [comment]
@CapOM
I have tested this at the k8s v1.20.0 however couldn't reproduce this.
(Launched kube-proxy with arguments `--iptables-min-sync-period=1m --iptables-sync-period=3m`)

**Comment by ns-jisorce** [comment]
Hi @gjkim42 , thanks for trying, any chance you can try on 1.17 ? Just to make sure you can reproduce the problem and there is no other thing preventing the problem to happen.
Also can you share instructions to setup kube-proxy from scratch or any pointer ?

**Comment by gjkim42** [comment]
Hi @ns-jisorce,
I've tested on 1.17.0 as well, but can't reproduce it. The nginx-service's endpoint appears less than 1s after updating label.

<img width="1680" alt="Screen Shot 2021-01-31 at 11 13 35 PM" src="https://user-images.githubusercontent.com/19814047/106386777-f9a17480-6419-11eb-8b1c-a73705dca7b2.png">

My environment,
```bash
root      38440  38428  0 22:56 pts/3    00:00:00 /home1/irteamsu/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/kube-proxy --v=3 --iptables-min-sync-period=10s --iptables-sync-period=1m --config=/tmp/kube-proxy.yaml --master=https://localhost:6443
```

```yaml
# /tmp/kube-proxy.yaml
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clientConnection:
  kubeconfig: /var/run/kubernetes/kube-proxy.kubeconfig
hostnameOverride: 127.0.0.1
mode: 
featureGates:
  AllAlpha: false
```

```bash
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.0-dirty", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"dirty", BuildDate:"2021-01-31T13:55:47Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.0-dirty", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"dirty", BuildDate:"2021-01-31T13:55:47Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
```
