### ISSUE TITLE
Incorrect container status when pod exceeds activeDeadlineSeconds 

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#98718]
**What happened**:
When pod exceeds `activeDeadlineSeconds` we find that,

```
status:
  containerStatuses:
  - containerID: cri-o://e3c8354c818791d37fb6fee96465075344ec2116f95edb5ddb3269d7d5d5f297
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:0415f56ccc05526f2af5a7ae8654baec97d4a614f24736e8eef41a4591f08019
    lastState: {}
    name: test
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: "2021-02-01T12:29:17Z"
  message: Pod was active on the node longer than the specified deadline
  phase: Failed
  podIP: 10.128.2.23
  podIPs:
  - ip: 10.128.2.23
  qosClass: Burstable
  reason: DeadlineExceeded
  startTime: "2021-02-01T12:29:14Z"
  ```
The pod `phase` is correctly states `Failed` with the reason `DeadlineExceeded` but as you can see above the container state is still reported as `running` 

**What you expected to happen**:
Container state should be `Terminated` not `running` because pod has exceeded `activeDeadlineSeconds`

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: test
  spec:
    activeDeadlineSeconds: 200
    terminationGracePeriodSeconds: 300
    containers:
    - args:
      - "600"
      command:
      - sleep
      image: docker.io/library/busybox
      imagePullPolicy: IfNotPresent
      name: test
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
```
Create the pod described above and wait till it exceeds listed `activeDeadlineSeconds`.  Then get the container status using,
`kubectl get -o yaml pod test | grep -A1000 '^status:'` 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `master` 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
