### ISSUE TITLE
Occasional OCI runtime create failed - "no such file or directory: unknown" when mounting multiple subpath volumes

### ISSUE THREAD

**Issue by bcorijn** [kubernetes/kubernetes#98719]
**What happened**:
From time to time, some of my statefulset pods will end up in a crashloop that can only be resolved by deleting the pod so a new one is spawned. I'm not 100% sure at this time what triggers the very first crash, but once it starts restarting it fails to create the container with the following error:
```
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/var/lib/kubelet/pods/705062a4-16a6-419b-8fd1-523bdb7feee8/volume-subpaths/p-003-config-volume/actions/1" to rootfs at "/var/lib/docker/overlay2/698615ea75288dd5622f0bd3a5c45fa31eb8f0bced47dcd5c5d61c0f5b7831b9/merged/etc/m/Actions.json" caused: no such file or directory: unknown
      Exit Code:    128
      Started:      Wed, 03 Feb 2021 09:26:06 +0100
      Finished:     Wed, 03 Feb 2021 09:26:06 +0100
```

**What you expected to happen**:
Pods to be able to start as normal

**How to reproduce it (as minimally and precisely as possible)**:
As said earlier, I'm not sure what is the trigger to get into this restart loop, but I do suspect it is related to my current config of mounting several subpath volumes to the same existing container directory, as followed (condensed to only relevant spec):
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: p-003-actions
spec:
  template:
    spec:
      containers:
      - name: actions
        volumeMounts:
        - mountPath: /etc/m/overrides.json
          name: p-003-config-volume
          subPath: overrides.json
        - mountPath: /etc/m/Actions.json
          name: p-003-config-volume
          subPath: Actions.json
      volumes:
      - name: p-003-config-volume
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: overrides.json
                path: overrides.json
              - key: Actions.json
                path: Actions.json
              name: p-003-config
```
The `/etc/m/` directory exists in the container and has other files, which prevents me from mounting as a directory. 

**Anything else we need to know?**:
This only happens occasionally and unpredictably, so I assume it might be some sort of race condition at play? 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.8, although I've had this issue on 1.17 and 1.16 too
- Cloud provider or hardware configuration: Azure AKS 
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1031-azure
- Install tools: AKS 
- Network plugin and version (if this is a network-related bug): Kubenet
