### ISSUE TITLE
Incorrect nodePort chosen for SSL healthcheck

### ISSUE THREAD

**Issue by sanicheev** [kubernetes/kubernetes#98826]
**What happened**:
Having http and https ports on Service object in conjunction with "service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https" causes healthcheck to send SSL traffic to http port.

**What you expected to happen**:
Either use TCP protocol for tcp listener in case we have backend-protocol set to "https" or choose correct nodePort.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Name=ingress-public
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "30"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "15"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:<ARN>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-public
    app.kubernetes.io/name: ingress-public
  name: ingress-public
  namespace: ingress-public
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31544
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 32591
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-public
    app.kubernetes.io/name: ingress-public
  sessionAffinity: None
  type: LoadBalancer
```
Create service described above and it will configure healthcheck by setting protocol to SSL and will use nodePort from the first listener(HTTP). It will cause healthcheck traffic to use SSL and send it to HTTP port and fail(will mark instance OutOfService).
Healthcheck will be set as: SSL:31544 in our case.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: AWS(EKS)
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
