### ISSUE TITLE
Specifying PodTopologySpreadConstraints has worse outcome than none in 1.18.15

### ISSUE THREAD

**Issue by arcivanov** [kubernetes/kubernetes#98860]
Adding PTSCs results in a worse scheduling outcome than not adding any at all. I cannot understand the reason as kube-scheduler is basically a black box that does not report any decisions. 

**What happened**:

Here are the involved nodes. 

Observe that `10.0.{150,160,170}.0/24` are different subnets in different zones.

```
NAME                           STATUS   ROLES    AGE   VERSION    LABELS
ip-10-0-150-246.ec2.internal   Ready    node     33h   v1.18.15   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t3a.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1a,kops.k8s.io/instancegroup=nodes,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-0-150-246.ec2.internal,kubernetes.io/os=linux,kubernetes.io/role=node,node-role.kubernetes.io/node=,node.kubernetes.io/instance-type=t3a.xlarge,topology.kubernetes.io/region=us-east-1,topology.kubernetes.io/zone=us-east-1a
ip-10-0-160-148.ec2.internal   Ready    node     34h   v1.18.15   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t3a.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1b,kops.k8s.io/instancegroup=nodes,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-0-160-148.ec2.internal,kubernetes.io/os=linux,kubernetes.io/role=node,node-role.kubernetes.io/node=,node.kubernetes.io/instance-type=t3a.xlarge,topology.kubernetes.io/region=us-east-1,topology.kubernetes.io/zone=us-east-1b
ip-10-0-160-55.ec2.internal    Ready    node     33h   v1.18.15   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t3a.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1b,kops.k8s.io/instancegroup=nodes,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-0-160-55.ec2.internal,kubernetes.io/os=linux,kubernetes.io/role=node,node-role.kubernetes.io/node=,node.kubernetes.io/instance-type=t3a.xlarge,topology.kubernetes.io/region=us-east-1,topology.kubernetes.io/zone=us-east-1b
ip-10-0-170-166.ec2.internal   Ready    node     33h   v1.18.15   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t3a.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1c,kops.k8s.io/instancegroup=nodes,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-0-170-166.ec2.internal,kubernetes.io/os=linux,kubernetes.io/role=node,node-role.kubernetes.io/node=,node.kubernetes.io/instance-type=t3a.xlarge,topology.kubernetes.io/region=us-east-1,topology.kubernetes.io/zone=us-east-1c
ip-10-0-170-199.ec2.internal   Ready    node     33h   v1.18.15   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t3a.xlarge,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-1,failure-domain.beta.kubernetes.io/zone=us-east-1c,kops.k8s.io/instancegroup=nodes,kubernetes.io/arch=amd64,kubernetes.io/hostname=ip-10-0-170-199.ec2.internal,kubernetes.io/os=linux,kubernetes.io/role=node,node-role.kubernetes.io/node=,node.kubernetes.io/instance-type=t3a.xlarge,topology.kubernetes.io/region=us-east-1,topology.kubernetes.io/zone=us-east-1c
```

Here are the pods:
```
$ kubectl -n istio-system get po -o wide
NAME                                    READY   STATUS    RESTARTS   AGE     IP                NODE                           NOMINATED NODE   READINESS GATES
istio-cryptogateway-779b74cf76-5nmqg    1/1     Running   0          6h9m    100.104.81.71     ip-10-0-160-55.ec2.internal    <none>           <none>
istio-cryptogateway-779b74cf76-8c9zz    1/1     Running   0          6h5m    100.107.195.197   ip-10-0-150-246.ec2.internal   <none>           <none>
istio-cryptogateway-779b74cf76-ds47k    1/1     Running   0          6h5m    100.126.135.199   ip-10-0-170-166.ec2.internal   <none>           <none>


istio-ingressgateway-6d7b4ff458-cbbkt   1/1     Running   0          67m     100.124.7.141     ip-10-0-160-148.ec2.internal   <none>           <none>
istio-ingressgateway-6d7b4ff458-jljhz   1/1     Running   0          67m     100.104.81.82     ip-10-0-160-55.ec2.internal    <none>           <none>
istio-ingressgateway-6d7b4ff458-lmjmd   1/1     Running   0          67m     100.115.202.133   ip-10-0-170-199.ec2.internal   <none>           <none>
```

1. Observe, that `istio-ingressgateway-6d7b4ff458-cbbkt ` and `istio-ingressgateway-6d7b4ff458-jljhz` ended up in the same availability zone.
2. Observe, that all `istio-cryptogateway` pods are all spread across availability zones with no `topologySpreadConstraints` specified.
3. Removing `topologySpreadConstraints` from `istio-ingressgateway` will lay the pods out on separate nodes in distinct zones just as with `istio-cryptogateway`. Adding PTSCs back schedules zone- and/or node-colocated for at least 2 out of 3 pods.

Here's the `istio-ingressgateway` Deployment (irrelevant parts removed):

```
$ kubectl -n istio-system get deploy istio-ingressgateway -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: dev
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.2
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: istio-ingressgateway
        chart: gateways
        heritage: Tiller
        install.operator.istio.io/owning-resource: unknown
        istio: ingressgateway
        istio.io/rev: default
        operator.istio.io/component: IngressGateways
        release: istio
        service.istio.io/canonical-name: istio-ingressgateway
        service.istio.io/canonical-revision: latest
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
            weight: 2
          - preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - ppc64le
            weight: 2
          - preference:
              matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - s390x
            weight: 2
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            service.istio.io/canonical-name: istio-ingressgateway
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            service.istio.io/canonical-name: istio-ingressgateway
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
```

**What you expected to happen**:

TopologySpreadConstraints are followed strictly when resources permit.

**How to reproduce it (as minimally and precisely as possible)**:

Above.

**Anything else we need to know?**:

Kube-scheduler hasn't been customized. There are no cluster defaults.

**Environment**:

- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AWS non-EKS.
- OS (e.g: `cat /etc/os-release`):  Ubuntu 20.04
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Huang-Wei** [comment]
> 1. Observe, that `istio-ingressgateway-6d7b4ff458-cbbkt ` and `istio-ingressgateway-6d7b4ff458-jljhz` ended up in the same availability zone.

I don't follow this. They're in different zones, aren't they?

```
istio-ingressgateway-6d7b4ff458-cbbkt   1/1     Running   0          67m     100.124.7.141     ip-10-0-160-148.ec2.internal   <none>           <none>
istio-ingressgateway-6d7b4ff458-lmjmd   1/1     Running   0          67m     100.115.202.133   ip-10-0-170-199.ec2.internal   <none>           <none>

ip-10-0-160-148 -> topology.kubernetes.io/zone=us-east-1b
ip-10-0-170-199 -> topology.kubernetes.io/zone=us-east-1c
```

**Comment by arcivanov** [comment]
Wrong pods:

```
istio-ingressgateway-6d7b4ff458-cbbkt   1/1     Running   0          67m     100.124.7.141     ip-10-0-160-148.ec2.internal   <none>           <none>
istio-ingressgateway-6d7b4ff458-jljhz   1/1     Running   0          67m     100.104.81.82     ip-10-0-160-55.ec2.internal    <none>           <none>
```

**Comment by arcivanov** [comment]
@Huang-Wei The point being, the outcome is suboptimal for reasons unknown. What is worse, the outcome is worse than if no PTSC is used at all.

**Comment by Huang-Wei** [comment]
@arcivanov It seems the deployment doesn't have the label `service.istio.io/canonical-name: istio-ingressgateway`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: dev
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.2
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
......
```

 Can you confirm by running: `k get po -l service.istio.io/canonical-name=istio-ingressgateway -n istio-system`?

**Comment by arcivanov** [comment]
Deployment doesn't, but pods do!

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: dev
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.8.2
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: istio-ingressgateway
        chart: gateways
        heritage: Tiller
        install.operator.istio.io/owning-resource: unknown
        istio: ingressgateway
        istio.io/rev: default
        operator.istio.io/component: IngressGateways
        release: istio
***        service.istio.io/canonical-name: istio-ingressgateway ***
        service.istio.io/canonical-revision: latest
```
