### ISSUE TITLE
AdmissionController podNodeSelector crashes api-server

### ISSUE THREAD

**Issue by wurst44** [kubernetes/kubernetes#98862]
**What happened**:
I am trying to install the podNodeSelector as described here: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector

**What you expected to happen**:
api-server/kubelet should accept configuration.

**How to reproduce it (as minimally and precisely as possible)**:
Add this to configuration kube-apiserver.yaml:

```
[...]
- command:
    - kube-apiserver
    - --enable-admission-plugins=PodNodeSelector
    - --admission-control-config-file=/etc/kubernetes/admissionConfiguration.yaml
[...]
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kind-docker:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-17T02:13:01Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
AND same happens on our aws-testcluster:
```
Client Version: v1.20.2
Server Version: v1.18.9
```

- Cloud provider or hardware configuration:
This happens in our **AWS testcluster** (custom kops) and to not destroy it i use the **kind framework** docker-container 
- OS (e.g: `cat /etc/os-release`):
It is **kind-docker** and
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
**kind-docker** and:
`Linux X250 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**PROBLEM:**
This is the AdmissionConfiguration I am using and I edit the /etc/kubernetes/manifest/kube-apiserver.yaml directly, which seems to make a hotreload:

```
[...]
- command:
    - kube-apiserver
    - --enable-admission-plugins=PodNodeSelector
    - --admission-control-config-file=/etc/kubernetes/admissionConfiguration.yaml
[...]
```

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodNodeSelector
  configuration:
    podNodeSelectorPluginConfig:
      clusterDefaultNodeSelector: "nodelabel=testitest"
      kube-system: "nodelabel=testitest"
```

After that the kube-apiserver **crashes with connection refused**.
When I put the admissionConfiguration.yaml directly under /etc/kubernetes/manifests it loads it and outputs this: 

`kind-control-plane kubelet[713]: E0208 07:33:01.682918     713 file.go:187] Can't process manifest file "/etc/kubernetes/manifests/admissionConfiguration.yaml": /etc/kubernetes/manifests/admissionConfiguration.yaml: couldn't parse as pod(no kind "AdmissionConfiguration" is registered for version "apiserver.config.k8s.io/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"), please check config file`

When I remove `- --admission-control-config-file=/etc/kubernetes/admissionConfiguration.yaml` evertyhing is running again.

**Comment by pacoxu** [comment]
/etc/kubernetes/manifests is a path for static pod.

You may put admissionConfiguration.yaml in /etc/kubernetes/.

```
    volumeMounts:
...
    - mountPath: /etc/kubernetes/admissionConfiguration.yaml
      name: k8s-config
      readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
...
  - hostPath:
      path: /etc/kubernetes/admissionConfiguration.yaml
      type: FileOrCreate
    name: k8s-config
```
