### ISSUE TITLE
kubeadm: wrong cluster-info config generation when using external certificates

### ISSUE THREAD

**Issue by kvaps** [kubernetes/kubernetes#98881]
**What happened**:

Hi, I use [kubefarm](https://github.com/kvaps/kubefarm) to spawn the Kubernetes clusters inside the Kubernetes.
Cert-manager is used to generate the certificates.
Certificates mounted into pod as standard secret volume.
This `admin.conf` has no section `client-certificate-data` but use `client-certificate` instead:

```yaml
# cat /etc/kubernetes/admin.conf 
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /pki/admin-client/ca.crt
    server: https://kubernetes-apiserver:6443
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: default
    user: default-auth
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: default-auth
  user:
    client-certificate: /pki/admin-client/tls.crt
    client-key: /pki/admin-client/tls.key
```

During the bootstrap this phase is executed by kubeadm:
```
kubeadm init phase bootstrap-token
```

Which is overriding `cluster-info` config in `kube-public` namespace:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: kube-public
data:
  jws-kubeconfig-1cw7oy: eyJhbGciOiJIUzI1NiIsImtpZCI6IjFjdzdveSJ9..22VLIr9ht4KgzJ4KEYPv4sVN5Ollcz9iFRCtGDVNi-Y
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /pki/admin-client/ca.crt
        server: https://kubernetes-apiserver:6443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
```
In result `cluster-info` has no any CA, which make other nodes not possible to join the cluster:

```
# kubeadm join phase kubelet-start kubernetes-apiserver:6443 --token x85jlf.vrfl3mmvf28qucez     --discovery-token-ca-cert-hash sha256:6781f3767fb7b6bcfc9b3ba81f641c06fc75fcab3ed62622181d7fa18326877c
error execution phase kubelet-start: couldn't validate the identity of the API Server: failed to parse cluster CA from the cluster-info ConfigMap: data does not contain any valid RSA or ECDSA certificates
```

**What you expected to happen**:

- `cluster-info` has correct CA-file
- new nodes are able to join

**How to reproduce it (as minimally and precisely as possible)**:

- put CA into file
- remove certificate-authority-data from `admin.conf`
- describe path to the CA in `certificate-authority` parameter in `admin.conf`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: on-premise
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04.1 LTS`
- Kernel (e.g. `uname -a`): `5.4.0-60-generic`
- Install tools: [kubefarm](https://github.com/kvaps/kubefarm)
- Network plugin and version (if this is a network-related bug):
- Others:
