### ISSUE TITLE
Add webhook requests signing

### ISSUE THREAD

**Issue by pablo-ruth** [kubernetes/kubernetes#98992]
#### What would you like to be added:

Add an option to ValidatingWebhookConfiguration/MutatingAdmissionWebhook to enable api-server requests signing:

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "pod-policy.example.com"
webhooks:
- name: "pod-policy.example.com"
  clientConfig:
    service:
      namespace: "example-namespace"
      name: "example-service"
    caBundle: ""
    signRequest: true
```

#### Why is this needed:

We need to add api-server servers authentication to secure a mutating webhook but we are on a semi-managed cluster where we don't have access to master nodes. The doc to enable authentication (https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers) involves adding a flag and create files on masters. We can't either use a network policy to restrict traffic to the webhook from api-servers as api-servers use host networking.
