### ISSUE TITLE
LimitRange should enforce min/max for request and not only limit

### ISSUE THREAD

**Issue by seb54000** [kubernetes/kubernetes#99096]
#### What would you like to be added:
Enhance LimitRange object/api to be able to set min/max value not only for the limit value of resource but also for request. New LimitRange may look like this in yml :
``` yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-min-max-demo-lr
spec:
  limits:
  - max:
      cpu: "800m"
    min:
      cpu: "200m"
    maxRequest:
      cpu: "100m"
    minRequest:
      cpu: "20m"
    type: Container
```

#### Why is this needed:
We have many namespaces on same cluster owned by multiple clients/tenants. The tend to have bad habits and make high requests which blocks other pods to be scheduled.
When we look at real usage they’re using around 10% of what they request.
We want to help them lower their request while maintaining limits high (so they can share CPU power with other tenants as they are not using it at the same time, especially in DEV/BUILD clusters).
Most of the time, the pod needs full CPU power during startup for a few seconds then go to idle most of the time.

The behavior of LimitRanger / Admission controller I would like is accept a pod like this :
``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: constraints-cpu-demo
spec:
  containers:
  - name: constraints-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        cpu: "800m"
      requests:
        cpu: "100m"
```

But not like that :
``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: constraints-cpu-demo
spec:
  containers:
  - name: constraints-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        cpu: "800m"
      requests:
        cpu: "500m"
```

As of today and following my tests and understanding it is not possible. If I want the first pod to be scheduled I have to set LimitRange with ate least a Max of 800m and this way, the second pod is also schedulable

**Comment by pacoxu** [comment]
LimitRanger supports ratio. In your example, you can set the ratio to be 8 or 10. An example below is from [openshift example](https://docs.openshift.com/container-platform/3.5/admin_guide/limits.html)
```
apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "2" 
      min:
        cpu: "200m" 
    - type: "Container"
      max:
        cpu: "2" 
      min:
        cpu: "100m" 
      default:
        cpu: "300m" 
      defaultRequest:
        cpu: "200m" 
      maxLimitRequestRatio:
        cpu: "10" 
```

- Enforce a ratio between request and limit for a resource in a namespace.
