### ISSUE TITLE
How to allow access to kubernetes api using egress network policy

### ISSUE THREAD

**Issue by yaminisridaran** [kubernetes/kubernetes#99113]
If the matter is security related, please disclose it privately via https://kubernetes.io/security/
-->

#### What happened:
PodA has 3 containers, c1,c2,c3. c1 communicates  to c2 via http://127.0.0.1:6000.
I created  egress network policy for  PodA. "curl -I http://127.0.0.1:6000" fails when  I execute the curl command from c1.

Egress Spec:
```
spec:
  podSelector:
    matchLabels:
      app: goodbye-world-app
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: hello-world-app
  - to:
    - namespaceSelector:
        matchLabels:
          name: fedB
  - to:
    - namespaceSelector:
        matchLabels:
          name: fedC
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.96.0.1/32

```
#### What you expected to happen:
egress network policy should not affect  the  multiple container communication inside pod.

#### Environment:
- Kubernetes version :1.18
