### ISSUE TITLE
Ungraceful termination when running kube-proxy in IPVS mode

### ISSUE THREAD

**Issue by aaronbbrown** [kubernetes/kubernetes#99162]
#### What happened: 

Connections time out from external client when pods are deleted and kube-proxy is in IPVS mode. 

#### What you expected to happen:

Connections should not timeout or be blackholed when pods are deleted in an IPVS-enabled cluster.

#### How to reproduce it (as minimally and precisely as possible):

This configuration should facilitate graceful termination behavior when pods are deleted w/ `kubectl delete`

<details><summary>nginx K8s YAML</summary>

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: nginx
    targetPort: http
  type: NodePort
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
  selector:
    matchLabels:
      app: nginx
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - "sleep 5; /usr/sbin/nginx -s quit"
```

</details>

I verified that requests to an iptables-enabled cluster continued without error while periodically deleting 1 of 10 healthy Pods (using `cyclepods.sh` 👇🏻 ) while a `vegeta attack` was running against the cluster (using `bench.sh` 👇🏻).

<details><summary>bench.sh</summary>

```shell
#!/usr/bin/env bash

set -e

export PATH=$PATH:$HOME/bin
CLUSTER=$1
if [ -z "$CLUSTER" ]; then
  echo "usage: $0 CLUSTER"
  exit 1
fi


kubectl() {
  command kubectl --context "$CLUSTER" -o json "$@"
}

node() {
  kubectl -l kubernetes.github.com/role=node get nodes |
    jq -er '.items[0].metadata.name'
}

serviceport() {
  kubectl -n default get services nginx |
    jq -er '.spec.ports[] | select(.targetPort=="http").nodePort'
}

bench() {
  echo "$1" |
    prlimit -n65535 \
      vegeta attack -duration 5m -keepalive=false -rate '100/1s' -workers 10 |
      vegeta report
}

main() {
  local node=$(node)
  local ip=$(dig +short "$node" | head -1)
  local serviceport=$(serviceport)
  local request="GET http://${ip}:${serviceport}/"

  bench "$request"
}

main
```
</details>

<details><summary>cyclepods.sh</summary>

```shell

#!/usr/bin/env bash

set -e

CLUSTER=$1
if [ -z "$CLUSTER" ]; then
  echo "usage: $0 CLUSTER"
  exit 1
fi

while : ; do
  kubectl --context "$CLUSTER" wait --for=condition=available deployment/nginx
  kubectl --context "$CLUSTER" get pods -l app=nginx -n default --no-headers |
    awk -F' *|/' '$2 == $3 && $4 == "Running" {print $1}' |
    shuf |
    head -1 |
    xargs kubectl --context "$CLUSTER" delete pod
  sleep 0.5
done
```

</details>

Running these script pairs against the iptables-enabled cluster yielded expected results: 100% success.

```console
$ ./bench.sh iptables-cluster
Requests      [total, rate, throughput]         30000, 100.00, 100.00
Duration      [total, attack, wait]             5m0s, 5m0s, 2.622ms
Latencies     [min, mean, 50, 90, 95, 99, max]  1.221ms, 2.433ms, 1.782ms, 3.223ms, 3.964ms, 12.465ms, 85.921ms
Bytes In      [total, mean]                     18360000, 612.00
Bytes Out     [total, mean]                     0, 0.00
Success       [ratio]                           100.00%
Status Codes  [code:count]                      200:30000
Error Set:
```

However, running this against the IPVS-enabled cluster, yielded a lot of timeouts:

```console
$ ./bench.sh ipvs-cluster
Requests      [total, rate, throughput]         30000, 100.00, 79.93
Duration      [total, attack, wait]             5m30s, 5m0s, 29.82s
Latencies     [min, mean, 50, 90, 95, 99, max]  2.597ms, 3.623s, 5.365ms, 30s, 30s, 30s, 30.001s
Bytes In      [total, mean]                     16132932, 537.76
Bytes Out     [total, mean]                     0, 0.00
Success       [ratio]                           87.87%
Status Codes  [code:count]                      0:3639  200:26361
Error Set:
Get "http://10.0.32.39:31641/": dial tcp 0.0.0.0:0->10.0.32.39:31641: connect: connection refused
Get "http://10.0.32.39:31641/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Get "http://10.0.32.39:31641/": read tcp 10.52.122.12:39881->10.0.32.39:31641: read: connection reset by peer
```

#### Anything else we need to know?:

We have the following sysctl's set for Linux Virtual Server:
```
net.ipv4.vs.am_droprate = 10
net.ipv4.vs.amemthresh = 1024
net.ipv4.vs.backup_only = 0
net.ipv4.vs.cache_bypass = 0
net.ipv4.vs.conn_reuse_mode = 0
net.ipv4.vs.conntrack = 1
net.ipv4.vs.drop_entry = 0
net.ipv4.vs.drop_packet = 0
net.ipv4.vs.expire_nodest_conn = 1
net.ipv4.vs.expire_quiescent_template = 1
net.ipv4.vs.ignore_tunneled = 0
net.ipv4.vs.nat_icmp_send = 0
net.ipv4.vs.pmtu_disc = 1
net.ipv4.vs.schedule_icmp = 0
net.ipv4.vs.secure_tcp = 0
net.ipv4.vs.sloppy_sctp = 0
net.ipv4.vs.sloppy_tcp = 0
net.ipv4.vs.snat_reroute = 1
net.ipv4.vs.sync_persist_mode = 0
net.ipv4.vs.sync_ports = 1
net.ipv4.vs.sync_qlen_max = 1028346
net.ipv4.vs.sync_refresh_period = 0
net.ipv4.vs.sync_retries = 0
net.ipv4.vs.sync_sock_size = 0
net.ipv4.vs.sync_threshold = 3	50
net.ipv4.vs.sync_version = 1
```

I have reviewed the following issues and it seems like our sysctls are reasonable:
- https://github.com/kubernetes/kubernetes/issues/81775
- https://github.com/kubernetes/kubernetes/issues/71358

`kube-proxy` is configured with the following parameters:

```
kube-proxy --kubeconfig=/etc/kubernetes/kubelet.conf --cluster-cidr=10.125.0.0/17 --v=4 --proxy-mode=ipvs --ipvs-scheduler=rr --conntrack-max-per-core=0
```

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.2
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Debian Stretch
- Kernel (e.g. `uname -a`): 4.19.160-2~deb9u1
- Install tools:
- Network plugin and version (if this is a network-related bug): canal (Calico v3.16.4, Flannel v0.12.0)
- Others:
