### ISSUE TITLE
v1.18.x invalid: spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by kumparankusumo** [kubernetes/kubernetes#99179]
Error occurs in v1.18.x, Previously there were no errors in Kubernetes v1.13.x.

svc.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {label}
  name: test
  namespace: {namespace}
spec:  
  ports:
  -
    name: rpc
    nodePort: {nodePort}
    port: {port}
    protocol: TCP
    targetPort: {port}
  -
    name: http
    nodePort: {nodePort}
    port: {port}
    protocol: TCP
    targetPort: {port}
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    run: {label_selector}
  sessionAffinity: None
```

how to replicate:
apply with `kubectl apply -f {file.yaml}` twice and i got following error message.
```
The Service "test" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

Expected result:
since there were no errors in Kubernetes v1.13.x, it should be fine in v1.18.x.
