### ISSUE TITLE
Ambiguity about networkpolicy e2e test case: ‘should allow egress access on one named port‘

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#99256]
#### What would you like to be added:
The description of  networkpolicy.spec.egress.to/ports are ambiguous. I think  we should explain this question:

In this networkpolicy:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-client-a-via-named-port-egress-rule
  namespace: network-policy-5043
spec:
  egress:
  - ports:
    - port: serve-80
      protocol: TCP
    - port: 53
      protocol: UDP
  podSelector:
    matchLabels:
      pod-name: client-a
  policyTypes:
  - Ingress
  - Egress
```
what does port: serve-80 mean?   
A port named 'serve-80' which is used by some pods in this cluster. 
or
A port named 'serve-80' which is used by some pods in the namespace of this networkpolicy.

this networkpolicy is exists in the e2e case: ‘should allow egress access on one named port‘ .  It has a distinctive feature:
a egress rule with a named `port` and empty `to` . 

#### Why is this needed:

We need to explain what a named `port` means in a egress rule which has empty `to` .  Include:
1. where to find the real port?
2. does the rule still match all destination address? 
This will affect the implementation of networkpolicy.
