### ISSUE TITLE
All hostaliases will be losed

### ISSUE THREAD

**Issue by vacheli** [kubernetes/kubernetes#99258]
#### What happened:
All hostaliases will be losed
##### Step 1:
```
kubectl apply -f myapp.yaml
cat myapp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: ingress-nginx-check
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      hostAliases:
      - hostnames:
        - "a.google.com"
        ip: 10.2.3.34
```
##### Step 2:
```
kubectl apply -f myapp.yaml
cat myapp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: ingress-nginx-check
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      hostAliases:
      - hostnames:
        - "a.google.com"
        ip: 10.2.3.34
      - hostnames:
        - "b.google.com"
        ip: 10.2.3.34
```
##### Step 3:
```
kubectl apply -f myapp.yaml
cat myapp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: ingress-nginx-check
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      hostAliases:
      - hostnames:
        - "a.google.com"
        - "b.google.com"
        ip: 10.2.3.34
``
#### Anything else we need to know?:

#### Environment:
- Kubernetes version (use `kubectl version`):  v1.18.8
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 18.04.5 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): calico 3.15
- Others:
