### ISSUE TITLE
PV with claim ref and namespace not set cannot be bound to PVC

### ISSUE THREAD

**Issue by amado-saladino** [kubernetes/kubernetes#99266]
I am trying to bind PV to PVC using `pv.spec.clamRef` as mentioned in [this link](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume) But I did not set the field `pv.spec.claimRef.namespace` and was able to create the PV object.

I created a PVC to be bound to this PV by setting the field `pvc.spec.volumeName` as the name of PV.

#### What happened:

- PV cannot be bound to the PVC.
- PVC keeps in `pending` status.
- PV object does not know what PVC it should be bound to - run `kubectl get pv` and notice the `CLAIM` column

#### What you expected to happen:
I expected that the fields `pv.spec.claimRef.namespace` would be mandatory and PV object cannot be created without this field. Or in case of not setting this field, it may get a default value of `default` referring to the default namespace

#### How to reproduce it (as minimally and precisely as possible):

Create the resources from this YAML:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv
spec:
  claimRef:
    name: foo-pvc
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  volumeName: foo-pv
```

[video ](https://www.youtube.com/watch?v=fH9wfL4HDmU)details

#### Environment:
- Kubernetes version (use `1.19`):
- Cloud provider or hardware configuration: Katakoda
- OS (e.g: `Ubuntu 18`):
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug):N/A
- Others:N/A
