### ISSUE TITLE
Invalid YAML was accepted and led to wrong behavior

### ISSUE THREAD

**Issue by schollii** [kubernetes/kubernetes#99286]
#### What happened:

I applied the following invalid yaml (because the `envFrom` appears twice):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todos-api
  name: todos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
        redis-access: "true"
    spec:
      restartPolicy: Always
      containers:
      - image: MY_ECR/team36-todos-api
        name: todos-api
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: todos-api
        envFrom:
        - secretRef:
            name: todos-api
```

This was accepted by API server and the Deployment was created, however the *first* envFrom was ignored so the environment variables from the configmap were absent from the pods. 

#### What you expected to happen:

`kubectl apply -f thefile.yaml` should have failed. 

#### How to reproduce it (as minimally and precisely as possible):

- Create a config map named todos-api
- Save the yaml to a file, replace image by say busybox or such
- kubectl apply -f thefile.yaml

#### Environment:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: n/a (probably kubeadm cluster on AWS)
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Kernel (e.g. `uname -a`):
```
Linux DevSlopGameDay 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
