### ISSUE TITLE
Incorrect cgroup values when pod resources set to just numeric 1

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#99296]
#### What happened:
When the following pod yaml is used,
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: 1
        cpu: "3"
      requests:
        memory: 1
        cpu: "600m"
```
The corresponding cgroup entry reads as, 

```bash
# cat /sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podc8c305d5_1b05_4c14_b7e3_da8a07ba8d42.slice/memory.limit_in_bytes 
0
```

#### What you expected to happen:
value in the file `memory.limit_in_bytes` should have been 1 not 0. 

#### How to reproduce it (as minimally and precisely as possible):
Use the given pod yaml and observe the value in corresponding `memory.limit_in_bytes`

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by harche** [comment]
Not sure if it's related but when I use,

```yaml 
$ cat nginx-demo-bug.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: 1000000
        cpu: "3"
      requests:
        memory: 1000000
        cpu: "600m"
```
The corresponding cgroup entry reads, 
```bash
# cat kubepods-burstable-podffc4d960_872e_49ae_bf58_f4f9f11e62c2.slice/memory.limit_in_bytes 
999424
```
I was expecting it to be 1000000 not 999424.

**Comment by harche** [comment]
Although when I use `MiB` unit,

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "1Mi"
        cpu: "3"
      requests:
        memory: "1Mi"
        cpu: "600m"
```
the corresponding cgroup entry is correctly set, 
```bash
# cat kubepods-burstable-pod61631443_10ad_4ebf_8c9f_2a492c65a9f0.slice/memory.limit_in_bytes 
1048576
```
