### ISSUE TITLE
Error "Socket: Socket is Closed" Occur When Rolling Update

### ISSUE THREAD

**Issue by felirs** [kubernetes/kubernetes#99340]
#### What happened:
We used the aws cloud provider.
When a project is rolling update, API calls may fail by incident especially the old pods are terminating. 
The error message is **Socket: Socket is Closed**.

#### What you expected to happen:
All the API calls are totally success.

#### How to reproduce it (as minimally and precisely as possible):
1. Modify deployment (use kubectl edit deploy XXX or kubectl set image XXX)
2. Call the same API repeatedly and regularly.
3. Observe the result of the call
4. Some APIs will fail and we can get error **Socket: Socket is Closed**.

We choose a API which independent of other services and databases. First, we update our deploy in kubernetes and then,
we call the api repeatedly and regularly. Here are the results and error message:

Repeat Count | Repeat Delay(ms) | Concurrency | Pods Count | Success Count | Error Count | Success Rate
-- | -- | -- | -- | -- | -- | --
10000 | 1000 | 50 | 6 | 10000 | 0 | 100%
10000 | 1000 | 50 | 6 | 9999 | 1 | 99.99%
10000 | 1000 | 50 | 6 | 10000 | 0 | 100%
10000 | 1000 | 50 | 6 | 10000 | 0 | 100%
10000 | 1000 | 50 | 6 | 10000 | 0 | 100%
10000 | 1000 | 100 | 6 | 10000 | 0 | 100%
10000 | 1000 | 100 | 6 | 10000 | 0 | 100%
10000 | 1000 | 100 | 6 | 9955 | 45 | 99.55%
10000 | 1000 | 100 | 6 | 10000 | 0 | 100%
10000 | 1000 | 100 | 6 | 10000 | 0 | 100%
10000 | 1000 | 200 | 6 | 9953 | 47 | 99.53%

error message:
![image](https://user-images.githubusercontent.com/26500370/108800680-cb552600-75ce-11eb-9749-d217dab42c2a.png)

By the way, when this project is running normally, the API calls are totally success.

#### Anything else we need to know?:
We also use istio. An api call will be forwarded to the target service by istio-ingressgateway.

#### Environment:
- Kubernetes version:  v1.16.14
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.14", GitCommit:"d2a081c8e14e21e28fe5bdfa38a817ef9c0bb8e3", GitTreeState:"clean", BuildDate:"2020-08-13T12:33:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
 ```
- Cloud provider: AWS
- AWS eks platform version:  eks.4
- Istio version: 1.4
- Deploy config:
```
apiVersion: apps/v1
kind: Deployment

...

spec:
  progressDeadlineSeconds: 600
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-app
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
```
