### ISSUE TITLE
ValidatingWebhook Equivalent Match Policy fails when apiVersions are conflicting

### ISSUE THREAD

**Issue by QuentinBisson** [kubernetes/kubernetes#99352]
#### What happened:

I configured a validating webhook for ingresses with the default Equivalent match policy and defined overlapping equivalent apiversions:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "resource.default.name" . }}-admission
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
webhooks:
- name: validate.nginx.ingress.kubernetes.io
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1beta1
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions:
    - v1beta1
    - v1
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "resource.default.name" . }}-admission
      path: /networking/v1beta1/ingresses
```
When I create `networking.k8s.io/v1beta1` ingress, they are created successfully but when I created  `networking.k8s.io/v1`, the validation failed with 
`Error from server (InternalError): error when creating "ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding`

#### What you expected to happen:
The `networking.k8s.io/v1` should have been created

#### How to reproduce it (as minimally and precisely as possible):

Define a validating webhook with overlapping apiVersions like the one above

#### Environment:
- Kubernetes version (use `kubectl version`): 
`kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
`

**Comment by neolit123** [comment]
adding sigs for triage.

/sig network
for the networking API.

/sig api-machinery 
for webhooks

**Comment by liggitt** [comment]
I cannot reproduce the error... I registered a validating webhook the same way and my webhook received the following:

applying a v1beta1 Ingress:
```json
{
 "apiVersion": "admission.k8s.io/v1beta1",
 "kind": "AdmissionReview",
 "request": {
  "dryRun": false,
  "kind": {
   "group": "networking.k8s.io",
   "kind": "Ingress",
   "version": "v1beta1"
  },
  "name": "test-v1beta1",
  "namespace": "default",
  "object": {
   "apiVersion": "networking.k8s.io/v1beta1",
   "kind": "Ingress",
   "metadata": {
    "annotations": {
     "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"networking.k8s.io/v1beta1\",\"kind\":\"Ingress\",\"metadata\":{\"annotations\":{},\"name\":\"test-v1beta1\",\"namespace\":\"default\"},\"spec\":{\"rules\":[{\"host\":\"foo.bar.com\",\"http\":{\"paths\":[{\"backend\":{\"serviceName\":\"echoheadersx\",\"servicePort\":80},\"path\":\"/foo\"}]}}]}}\n"
    },
    "creationTimestamp": "2021-03-01T15:29:45Z",
    "generation": 1,
    "managedFields": [
     {
      "apiVersion": "networking.k8s.io/v1beta1",
      "fieldsType": "FieldsV1",
      "fieldsV1": {
       "f:metadata": {
        "f:annotations": {
         ".": {},
         "f:kubectl.kubernetes.io/last-applied-configuration": {}
        }
       },
       "f:spec": {
        "f:rules": {}
       }
      },
      "manager": "kubectl-client-side-apply",
      "operation": "Update",
      "time": "2021-03-01T15:29:45Z"
     }
    ],
    "name": "test-v1beta1",
    "namespace": "default",
    "uid": "3a074476-8a2b-49b9-9b61-31e148c5d4b7"
   },
   "spec": {
    "rules": [
     {
      "host": "foo.bar.com",
      "http": {
       "paths": [
        {
         "backend": {
          "serviceName": "echoheadersx",
          "servicePort": 80
         },
         "path": "/foo",
         "pathType": "ImplementationSpecific"
        }
       ]
      }
     }
    ]
   },
   "status": {
    "loadBalancer": {}
   }
  },
  "oldObject": null,
  "operation": "CREATE",
  "options": {
   "apiVersion": "meta.k8s.io/v1",
   "fieldManager": "kubectl-client-side-apply",
   "kind": "CreateOptions"
  },
  "requestKind": {
   "group": "networking.k8s.io",
   "kind": "Ingress",
   "version": "v1beta1"
  },
  "requestResource": {
   "group": "networking.k8s.io",
   "resource": "ingresses",
   "version": "v1beta1"
  },
  "resource": {
   "group": "networking.k8s.io",
   "resource": "ingresses",
   "version": "v1beta1"
  },
  "uid": "fd45283e-7704-4d88-81dd-09ba285ed54c",
  "userInfo": {
   "groups": [
    "system:masters",
    "system:authenticated"
   ],
   "username": "system:admin"
  }
 }
}
```

applying a v1 ingress:
```json
{
 "apiVersion": "admission.k8s.io/v1beta1",
 "kind": "AdmissionReview",
 "request": {
  "dryRun": false,
  "kind": {
   "group": "networking.k8s.io",
   "kind": "Ingress",
   "version": "v1"
  },
  "name": "test-v1",
  "namespace": "default",
  "object": {
   "apiVersion": "networking.k8s.io/v1",
   "kind": "Ingress",
   "metadata": {
    "annotations": {
     "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"networking.k8s.io/v1\",\"kind\":\"Ingress\",\"metadata\":{\"annotations\":{},\"name\":\"test-v1\",\"namespace\":\"default\"},\"spec\":{\"rules\":[{\"host\":\"foo.bar.com\",\"http\":{\"paths\":[{\"backend\":{\"service\":{\"name\":\"echoheadersx\",\"port\":{\"number\":80}}},\"path\":\"/foo\",\"pathType\":\"Prefix\"}]}}]}}\n"
    },
    "creationTimestamp": "2021-03-01T15:29:45Z",
    "generation": 1,
    "managedFields": [
     {
      "apiVersion": "networking.k8s.io/v1",
      "fieldsType": "FieldsV1",
      "fieldsV1": {
       "f:metadata": {
        "f:annotations": {
         ".": {},
         "f:kubectl.kubernetes.io/last-applied-configuration": {}
        }
       },
       "f:spec": {
        "f:rules": {}
       }
      },
      "manager": "kubectl-client-side-apply",
      "operation": "Update",
      "time": "2021-03-01T15:29:45Z"
     }
    ],
    "name": "test-v1",
    "namespace": "default",
    "uid": "c53593d9-7868-41fc-b3f3-e74e420a6e75"
   },
   "spec": {
    "rules": [
     {
      "host": "foo.bar.com",
      "http": {
       "paths": [
        {
         "backend": {
          "service": {
           "name": "echoheadersx",
           "port": {
            "number": 80
           }
          }
         },
         "path": "/foo",
         "pathType": "Prefix"
        }
       ]
      }
     }
    ]
   },
   "status": {
    "loadBalancer": {}
   }
  },
  "oldObject": null,
  "operation": "CREATE",
  "options": {
   "apiVersion": "meta.k8s.io/v1",
   "fieldManager": "kubectl-client-side-apply",
   "kind": "CreateOptions"
  },
  "requestKind": {
   "group": "networking.k8s.io",
   "kind": "Ingress",
   "version": "v1"
  },
  "requestResource": {
   "group": "networking.k8s.io",
   "resource": "ingresses",
   "version": "v1"
  },
  "resource": {
   "group": "networking.k8s.io",
   "resource": "ingresses",
   "version": "v1"
  },
  "uid": "1871c4a7-66a5-4f77-bf7d-a08cadd3a034",
  "userInfo": {
   "groups": [
    "system:masters",
    "system:authenticated"
   ],
   "username": "system:admin"
  }
 }
}
```

The webhook registration indicates it accepts v1 objects, so v1 Ingress objects will be sent as-is to the webhook. Is your webhook able to decode v1 Ingress objects successfully?

**Comment by liggitt** [comment]
If your webhook only understands v1beta1 Ingress objects, your registration object should look like this:

```yaml
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
```

That would ensure that ingresses are converted to networking.k8s.io/v1beta1 before they are sent to your webhook.

If that resolves the issue, you should also be aware that v1beta1 Ingress objects will no longer be served in 1.22+, so you should work on updating your webhook to understand v1 so you can also register to intercept v1 Ingress objects explicitly.
