### ISSUE TITLE
AWS ELB healtcheck SYN Flood in pod

### ISSUE THREAD

**Issue by ltagliamonte-dd** [kubernetes/kubernetes#99373]
Networking to service/pod when draining config are applied to existent AWS ELB.

**Versions**:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

How to reproduce the issue:
- Create a namespace:
```
kubectl create ns lt-test-ns
```
- `kubectl apply` the following manifests:
```
apiVersion: apps/v1
kind: Deployment
metadata:   
  name: lt-hello-world-web
  namespace: lt-test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      service: lt-hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        service: lt-hello-world
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - lt-hello-world
                - key: app
                  operator: In
                  values:
                  - web
              topologyKey: kubernetes.io/hostname
            weight: 90
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - lt-hello-world
                - key: app
                  operator: In
                  values:
                  - web
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      containers:
      - args:
        - /bin/sh
        - -c
        - python -m SimpleHTTPServer 80
        image: python:2.7.17-buster
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: container-port
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app: web
    service: lt-hello-world
  name: lt-hello-world-web
  namespace: lt-test-ns
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: container-port
  selector:
    app: web
    service: lt-hello-world
  sessionAffinity: None
  type: LoadBalancer
```

Traffic to the pod is healthy all instances attached to the ELB are in Service.
```
kubectl port-forward service/lt-hello-world-web -n lt-test-ns 8080:80 
```
in another shell:
```
while true; do curl 127.0.0.1:8080; sleep 1; done
```
pod is correctly logging the requests in another shell:
```
kubectl -n lt-test-ns logs -f $(kubectl get pods -n lt-test-ns --no-headers | cut -d" " -f1) -c web
```

Let's `kubectl apply` the following change to the ELB:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "300"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app: web
    service: lt-hello-world
  name: lt-hello-world-web
  namespace: lt-test-ns
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: container-port
  selector:
    app: web
    service: lt-hello-world
  sessionAffinity: None
  type: LoadBalancer
```

Restart kubectl port forward as before:
```
kubectl port-forward service/lt-hello-world-web -n lt-test-ns 8080:80 
```
in another shell:
```
while true; do curl 127.0.0.1:8080; sleep 1; done
```
pod will stop logging the requests in another shell:
```
kubectl -n lt-test-ns logs -f $(kubectl get pods -n lt-test-ns --no-headers | cut -d" " -f1) -c web
```

After few seconds (during some test minutes) network will break and no more requests will go through.
All instances attached to the ELB will go `OutOfService` failing health-checks.

Telnet to the listening kube-proxy port on localhost doesn't work as well.

**Comment by ltagliamonte-dd** [comment]
- update:
it breaks also if you start directly with connection draining on the ELB:
```
apiVersion: apps/v1
kind: Deployment
metadata:   
  name: lt-hello-world-web
  namespace: lt-test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      service: lt-hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
        service: lt-hello-world
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - lt-hello-world
                - key: app
                  operator: In
                  values:
                  - web
              topologyKey: kubernetes.io/hostname
            weight: 90
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - lt-hello-world
                - key: app
                  operator: In
                  values:
                  - web
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      containers:
      - args:
        - /bin/sh
        - -c
        - python -m SimpleHTTPServer 80
        image: python:2.7.17-buster
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 80
          name: container-port
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "300"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app: web
    service: lt-hello-world
  name: lt-hello-world-web
  namespace: lt-test-ns
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: container-port
  selector:
    app: web
    service: lt-hello-world
  sessionAffinity: None
  type: LoadBalancer
```
