### ISSUE TITLE
hpa: Scales down despite some metrics being unavailable (since v1.16, #74526)

### ISSUE THREAD

**Issue by mikkeloscar** [kubernetes/kubernetes#99394]
#### What happened:

If you have 2 or more metrics defined on an HPA and one metric is suggesting to scale down and the other metric is unavailable, the HPA will scale down despite missing metrics.

Example:

Imagine the following Horizontal Pod Autoscaler resource:

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
  - type: External
    external:
      metric:
        name: custom-metric
        selector:
          matchLabels:
            custom: "true"
      target:
        averageValue: "10"
        type: AverageValue
```

And the deployment `my-app` is currently scaled to `3` replicas.

If the `cpu` metric is suggesting to scale to 1 AND the `custom-metric` metric is unavailable e.g. HPA can't fetch the metrics. Then it will happily scale down to `1` despite not knowing what the currently unavailable metric would suggest.

#### What you expected to happen:

It's clearly stated in the docs the scale down should not happen if one or more metrics are unavailable: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details

> If multiple metrics are specified in a HorizontalPodAutoscaler, this calculation is done for each metric, and then the largest of the desired replica counts is chosen. **If any of these metrics cannot be converted into a desired replica count (e.g. due to an error fetching the metrics from the metrics APIs) and a scale down is suggested by the metrics which can be fetched, scaling is skipped.** This means that the HPA is still capable of scaling up if one or more metrics give a `desiredReplicas` greater than the current value.

#### How to reproduce it (as minimally and precisely as possible):

Until Kubernetes v1.15.x the behavior was as expected. However with the [introduction of HPA scaling to Zero/#74526](https://github.com/kubernetes/kubernetes/pull/74526). The logic was [changed](https://github.com/kubernetes/kubernetes/pull/74526/files#diff-f1c5a31aa8fb8e3fd64b6aa13d3358b504e6e25030f249f1652e244c105eafc7L275-R285) removing the special handling of stopping scale down in case of unavailable metrics.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/bug
/sig autoscaling
