### ISSUE TITLE
Failed to run the pod with duplicate persistent volumes

### ISSUE THREAD

**Issue by spyyang** [kubernetes/kubernetes#99453]
#### What happened:

Create a pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: nginx
      volumeMounts:
        - name: config-a
          mountPath: /etc/a
          subPath: a
        - name: config-b
          mountPath: /etc/b
          subPath: b
  volumes:
    - name: config-a
      persistentVolumeClaim:
        claimName: test-nfs-claim
    - name: config-b
      persistentVolumeClaim:
        claimName: test-nfs-claim
```

the pod is always `ContainerCreating`, and describes as:

```
Warning FailedMount 4s kubelet Unable to attach or mount volumes: unmounted volumes=[config-a], unattached volumes=[config-a config-b default-token-t2wrn]: timed out waiting for the condition
```

kubelet log:

```
I0225 13:41:14.817380 2005690 desired_state_of_world_populator.go:361] Added volume "config-a" (volSpec="pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9") for pod "64659405-169c-4450-b006-99d00d4018bd" to desired state.
I0225 13:41:14.823159 2005690 desired_state_of_world_populator.go:361] Added volume "config-b" (volSpec="pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9") for pod "64659405-169c-4450-b006-99d00d4018bd" to desired state.
I0225 13:41:14.905775 2005690 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9" (UniqueName: "kubernetes.io/nfs/64659405-169c-4450-b006-99d00d4018bd-pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9") pod "test" (UID: "64659405-169c-4450-b006-99d00d4018bd")
I0225 13:41:15.006182 2005690 reconciler.go:254] Starting operationExecutor.MountVolume for volume "pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9" (UniqueName: "kubernetes.io/nfs/64659405-169c-4450-b006-99d00d4018bd-pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9") pod "test" (UID: "64659405-169c-4450-b006-99d00d4018bd")
I0225 13:41:15.006213 2005690 reconciler.go:269] operationExecutor.MountVolume started for volume "pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9" (UniqueName: "kubernetes.io/nfs/64659405-169c-4450-b006-99d00d4018bd-pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9") pod "test" (UID: "64659405-169c-4450-b006-99d00d4018bd")
I0225 13:41:15.006319 2005690 nfs.go:246] NFS mount set up: /var/lib/kubelet/pods/64659405-169c-4450-b006-99d00d4018bd/volumes/kubernetes.io~nfs/pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9 false stat /var/lib/kubelet/pods/64659405-169c-4450-b006-99d00d4018bd/volumes/kubernetes.io~nfs/pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9: no such file or directory
I0225 13:41:15.006482 2005690 mount_linux.go:171] Mounting cmd (mount) with arguments (-t nfs -o vers=4.1 10.246.250.159:/mnt/nfs/default-test-nfs-claim-pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9 /var/lib/kubelet/pods/64659405-169c-4450-b006-99d00d4018bd/volumes/kubernetes.io~nfs/pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9)
I0225 13:41:15.084139 2005690 operation_generator.go:672] MountVolume.SetUp succeeded for volume "pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9" (UniqueName: "kubernetes.io/nfs/64659405-169c-4450-b006-99d00d4018bd-pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9") pod "test" (UID: "64659405-169c-4450-b006-99d00d4018bd")
```

#### What you expected to happen:

Deny the pod orchestration with duplicate volumes, OR the pod can be running successfully. 

#### How to reproduce it (as minimally and precisely as possible):

Create a pod with the duplicate pvc as above.

#### Anything else we need to know?:

Root cause：

The key of persistent volume info in DSW is `volumeName` named after`pluginName/podUid-persistenVolumeName`, and the  `OuterVolumeSpecName` is a `string`:

https://github.com/kubernetes/kubernetes/blob/27c89b9aec73f66529a497910c460af2b25ab6dd/pkg/kubelet/volumemanager/cache/desired_state_of_world.go#L288-L293

When getting the unmounted volumes, it uses `OuterVolumeSpecName`:

https://github.com/kubernetes/kubernetes/blob/27c89b9aec73f66529a497910c460af2b25ab6dd/pkg/kubelet/volumemanager/volume_manager.go#L435-L441

In our case, `config-b` volume will corve the volume `kubernetes.io/nfs/64659405-169c-4450-b006-99d00d4018bd-pvc-a0b70cdf-ac23-43f2-a7bc-14467138ffa9` in DSW, and the `config-a` volume info is lost in ASW.

Solution:

2 choices:
- Consider it as an invalid request, and deny creating it.
- Construct uniqueVolumeName with `OuterVolumeSpecName` when the volume is a persistent volume.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig apps
/sig node
/sig storage

**Comment by mengjiao-liu** [comment]
I don't think it's common sense to write duplicate volumes, and people don't use them that way, but if you want to achieve the above YAML intent, you can do it this way
```sh
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: nginx
      volumeMounts:
        - name: config-a
          mountPath: /etc/a
          subPath: a
        - name: config-a
          mountPath: /etc/b
          subPath: b
  volumes:
    - name: config-a
      persistentVolumeClaim:
        claimName: myclaim
```

so I think it might be better this way `Consider it as an invalid request, and deny creating it.`

**Comment by spyyang** [comment]
> I don't think it's common sense to write duplicate volumes, and people don't use them that way, but if you want to achieve the above YAML intent, you can do it this way
> 
> ```yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   name: test
> spec:
>   containers:
>     - name: test
>       image: nginx
>       volumeMounts:
>         - name: config-a
>           mountPath: /etc/a
>           subPath: a
>         - name: config-a
>           mountPath: /etc/b
>           subPath: b
>   volumes:
>     - name: config-a
>       persistentVolumeClaim:
>         claimName: myclaim
> ```
> 
> so I think it might be better this way `Consider it as an invalid request, and deny creating it.` if write duplicate volumes

I recognize your point, but I think kubernetes should validate that.

**Comment by mengjiao-liu** [comment]
Yes, I think verification should be added as well

**Comment by mengjiao-liu** [comment]
Yes, I think verification should be added as well

**Comment by mengjiao-liu** [comment]
I'll try to do that

**Comment by mengjiao-liu** [comment]
Then I thought about it again, and I think this YAML might sometimes be used this way
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: nginx
      volumeMounts:
        - name: config-a
          mountPath: /etc/a
          subPath: a
        - name: config-b
          mountPath: /etc/b
          subPath: b
  volumes:
    - name: config-a
      persistentVolumeClaim:
        claimName: test-nfs-claim
    - name: config-b
      persistentVolumeClaim:
        claimName: test-nfs-claim
```

So it may not be a good idea to say no outright

Can you give me some advice   @jingxu97 @jsafrane @saad-ali @msau42

**Comment by mengjiao-liu** [comment]
This seems possible and Thank you for your description of the situation.

**Comment by msau42** [comment]
Does this address your use case?

```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: nginx
      volumeMounts:
        - name: config
          mountPath: /etc/a
          subPath: a
        - name: config
          mountPath: /etc/b
          subPath: b
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: test-nfs-claim
```

**Comment by mengjiao-liu** [comment]
> Does this address your use case?
> 
> ```yaml
> apiVersion: v1
> kind: Pod
> metadata:
>   name: test
> spec:
>   containers:
>     - name: test
>       image: nginx
>       volumeMounts:
>         - name: config
>           mountPath: /etc/a
>           subPath: a
>         - name: config
>           mountPath: /etc/b
>           subPath: b
>   volumes:
>     - name: config
>       persistentVolumeClaim:
>         claimName: test-nfs-claim
> ```

I've tried it and it works https://github.com/kubernetes/kubernetes/issues/99453#issuecomment-790540879

But does this duplicate PV need to take certain measures, verification failed or can be successful ？

**Comment by matthyx** [comment]
This is more a support request rather than a bug... however I am not closing it since it would be good to document this solution:
https://github.com/kubernetes/kubernetes/issues/99453#issuecomment-797630419

/remove-kind bug
/kind support
/triage accepted
/priority backlog
/area documentation
/good-first-issue

**Comment by slayer321** [comment]
Hey @matthyx, I am new to open source and will like to contribute to this project can you guide me on what needs to done.

**Comment by matthyx** [comment]
Welcome @slayer321 ! Sure, so the goal is to document that example of a double mount of the same pv.
I would put it somewhere here: https://kubernetes.io/docs/concepts/storage/volumes/
Which corresponds to this repo: https://github.com/kubernetes/website/blob/3ca34b9a3be454055ba234f1d2ff7d55809b5040/content/en/docs/concepts/storage/volumes.md

**Comment by matthyx** [comment]
If you have another idea about the best page to document it, please make it as you think.

**Comment by rahulii** [comment]
@slayer321 are you taking this up , or should i take?

**Comment by slayer321** [comment]
yes, @rahulii  I am taking this up.

**Comment by matthyx** [comment]
> /remove-kind support
> /kind documentation

Ah documentation is a kind... Makes sense. Thx Elana!

**Comment by slayer321** [comment]
Hii @matthyx, after reading [this](https://kubernetes.io/docs/concepts/storage/volumes/) docs . I think the example of " double mount of the same PV " needs to be added either before `Types of Volumes` or at the end of the page.
what did you say?

And it may look something like this.

Running pods with the duplicate persistent volume,
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: nginx
      volumeMounts:
        - name: config
          mountPath: /etc/a
          subPath: a
        - name: config
          mountPath: /etc/b
          subPath: b
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: test-nfs-claim

```
Example: A container running a web application reads application data from a persistent volume and saves logs to another PV.

as the example was mentioned by @wangyysde
