### ISSUE TITLE
certificatesigningrequests is in a Approved,Failed condition

### ISSUE THREAD

**Issue by jtfogarty** [kubernetes/kubernetes#99504]
#### What happened:
certificatesigningrequests is in a Approved,Failed condition
#### What you expected to happen:
certificatesigningrequests is in a Approved,Issued condition
#### How to reproduce it (as minimally and precisely as possible):

I create this gist https://gist.github.com/jtfogarty/173d46037d7d69b46cbf457cb9d41cc8 with 2 files.  
v1.sh and v1beta1.sh corresponding to the certificatesigningrequests API used.

To test, create a vault namespace as well as the below directory structure

/vault/userconfig/vault-server-tls

then run the script

v1beta1 works as expected
v1 is in an Approved,Failed condition

I'm not able to find a reason for the failure.

#### Anything else we need to know?:

I see this issue on 1.19.4 and 1.20.2

#### Environment:
- Kubernetes version (use `kubectl version`):
Client Version: v1.19.4
Server Version: v1.19.4
- Cloud provider or hardware configuration:
On-prem Intel NUCs
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`):
Linux mf-mstr-01 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jtfogarty** [comment]
version 1.20.4 also results in the Approved,Failed condition

**Comment by liggitt** [comment]
Thanks for the detailed reproduction steps.

When you requested a CSR via the v1beta1 API, you didn't specify a signerName, so the `kubernetes.io/legacy-unknown` signer was used, which places no restrictions on the shape of the submitted CSR.

When you requested a CSR with the v1 API, you specified the `kubernetes.io/kubelet-serving` signer, which places restrictions on the submitted CSR, including:

> Permitted subjects - organizations are exactly ["system:nodes"], common name starts with "system:node:".

The subject of the cert you are requesting did not match that requirement. `kubectl get csr -o yaml` shows the reason signing failed:

```yaml
...
  status:
    conditions:
    ...
    - lastTransitionTime: "2021-02-27T18:18:33Z"
      lastUpdateTime: "2021-02-27T18:18:33Z"
      message: subject organization is not system:nodes
      reason: SignerValidationFailure
      status: "True"
      type: Failed
```


See https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers for more details about the built-in kubernetes signers and the requirements for each.

**Comment by sguidos** [comment]
When  I moved from Kubernetes v1.19 to v1.22 I received the error message:
```no matches for kind "CertificateSigningRequest" in version "certificates.k8s.io/v1beta1"```

The obvious fix is to change the apiVerison of my CertificateSigningRequest yaml from "certificates.k8s.io/v1beta1" to just "certificates.k8s.io/v1".  After that change, I received the error message:
```error validating data: ValidationError(CertificateSigningRequest.spec): missing required field "signerName" in io.k8s.api.certificates.v1.CertificateSigningRequestSpec```

Since my original CSR had a "useages" of "server auth", the only signerName that seemed to fit my needs was "kubernetes.io/kubelet-serving".  So I add this "signerName" attribute to my CSR yaml, giving me a final definition of:
```
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: server_csr
spec:
  groups:
  - system:authenticated
  request: $REQUEST
  usages:
  - digital signature
  - key encipherment
  - server auth
  signerName: kubernetes.io/kubelet-serving
```

Now my "kubectl create csr.yaml" command worked, but the CSR it generated was not approved using openssl.  The .PEM file output by openssl is empty, and I can see the specific error by running:
```kubectl get csr server_csr -o json```

and see in the output:
```
{ ....
    "message": "subject organization is not system:nodes",
    "reason": "SignerValidationFailure",
    "status": "True",
    "type": "Failed"
}
```

The [Kubernetes signers](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers) link mentioned above (https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers) gives clues that:
```
2 - Permitted subjects - organizations are exactly ["system:nodes"], common name starts with "system:node:".
```

After struggling to interpret this, I realized that the "permitted subjects" the documentation is referring to is the "-subj" parameter in the openssl command.   I needed to change the "subject" parameter to literally add "system:node:" in front of my existing Common Name, and also to add an Organization Name of "system:nodes"

Old openssl command:
```
openssl req -new -key "$PrivateKeyFileName" -out "$CsrFileName" -subj '/CN=node-name-here'  ...
```

New openssl command:
```
openssl req -new -key "$PrivateKeyFileName" -out "$CsrFileName" -subj '/CN=system:node:node-name-here;/O=system:nodes'   ...
```

Success!

I hope this helps save time and headaches for whoever else may encounter these issues and error messages   :-)
