### ISSUE TITLE
`kubectl explain crd.spec.versions.schema ` schema should be required

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#99583]
#### What happened:

 We know that `schema` field is optional through `kubectl explain crd.spec.versions.schema `：

```
...
 name <string> -required-
     name is the version name, e.g. “v1”, “v2beta1”, etc. The custom
     resources are served under this version at `/apis/<group>/<version>/...` if
     `served` is true.

   schema       <Object>
     schema describes the schema used for validation, pruning, and defaulting of
     this version of the custom resource.

   served       <boolean> -required-
     served is a flag enabling/disabling this version from being served via REST
     APIs
...
```
I create a `crd` without `schema`:
```yml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
      - ct
```
when I execute `kubectl create -f crd.yml`, it prints the following error:
```
The CustomResourceDefinition "crontabs.stable.example.com" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
```
so schema is required.

#### What you expected to happen:
schema should be show required
`kubectl explain crd.spec.versions.schema `：

```
...
 name <string> -required-
     name is the version name, e.g. “v1”, “v2beta1”, etc. The custom
     resources are served under this version at `/apis/<group>/<version>/...` if
     `served` is true.

   schema       <Object> -required-
     schema describes the schema used for validation, pruning, and defaulting of
     this version of the custom resource.

   served       <boolean> -required-
     served is a flag enabling/disabling this version from being served via REST
     APIs
...
```

#### Environment:
- Kubernetes version (use `kubectl version`):
v1.20
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
