### ISSUE TITLE
kubelet_running_pods metric includes Pending pods 

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#99624]
#### What happened:
kubelet metric `kubelet_running_pods` should only count pods in `Running` state. But it incorrectly reports the sum of pods in `Running` + `Pending` state. 

#### What you expected to happen:
Only pods in `Running` state should be counted. 

#### How to reproduce it (as minimally and precisely as possible):
Create a pod with sample yaml to create a pod that stays in `Pending` state. 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
spec:
  containers:
    - name: dummy-pod
      image: ubuntu
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  restartPolicy: Always 
```
Verify that pod we created is in `Pending` state,

```bash
$ kubectl get pod -A -o go-template='{{range .items}}{{if eq .spec.nodeName "testclustgt1-js74g-worker-a-smjc7"}}{{.status.phase}}{{"\n"}}{{end}}{{end}}'
Pending
Running
Running
Running
Running
Running
Running
Running
Running
Running
Running
Running
Running
Running
Running
```
```bash
$ kubectl get pod dummy-pod -o  go-template='{{.status.phase}}'
Pending
```
Now let's count the total number of pods using `kubectl`
```
$ kubectl get pod -A -o go-template='{{range .items}}{{if eq .spec.nodeName "testclustgt1-js74g-worker-a-smjc7"}}{{.status.phase}}{{"\n"}}{{end}}{{end}}' | wc -l 
15
```
Out of 15, 1 is in `Pending` and rest are in `Running` state.
```bash
kubectl get pod -A -o go-template='{{range .items}}{{if eq .spec.nodeName "testclustgt1-js74g-worker-a-smjc7"}}{{.status.phase}}{{"\n"}}{{end}}{{end}}'|grep Pending|wc -l 
1
```
```bash
$ kubectl get pod -A -o go-template='{{range .items}}{{if eq .spec.nodeName "testclustgt1-js74g-worker-a-smjc7"}}{{.status.phase}}{{"\n"}}{{end}}{{end}}'|grep Running|wc -l 
14
```
But the corresponding metric `kubelet_running_pods{node="testclustgt1-js74g-worker-a-smjc7"}` from Prometheus dashboard returns 15. 

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
