### ISSUE TITLE
Probe port is filled with the name of the UDP port

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/kubernetes#99678]
``` yaml
    ports:
    - name: health-http
      protocol: TCP
      containerPort: 4001
    - name: health-udp
      protocol: UDP
      containerPort: 4002
    livenessProbe:
      httpGet:
          scheme: HTTP
          path: /
          port: health-udp
```

#### What happened:

No warning, a http request to health-udp

#### What you expected to happen:

Expect an alarm to indicate that the probe filled in is not a valid and usable tcp port

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
