### ISSUE TITLE
x-kubernetes-int-or-string changes finalizers behavior

### ISSUE THREAD

**Issue by cbandy** [kubernetes/kubernetes#99730]
I'm seeing the behavior of the `metadata.finalizers` field change when I add an `x-kubernetes-int-or-string` property to my v1 CRD. I believe my schema is structural according to this [CRD documentation about IntOrString](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#intorstring).

> the following is structural:
> ```yaml
> type: object
> properties:
>   foo:
>     x-kubernetes-int-or-string: true
> ```

#### What happened:

When my `apiextensions.k8s.io/v1` CRD has an `x-kubernetes-int-or-string` property, I can no longer server-side apply individual finalizers.

#### What you expected to happen:

I expected finalizers to behave the same regardless of field validation.

#### How to reproduce it (as minimally and precisely as possible):

Files:

```yaml
==> doot-crd.yaml <==
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: doots.example.com
spec:
  group: example.com
  names:
    kind: Doot
    plural: doots
    singular: doot
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion: { type: string }
          kind:       { type: string }
          metadata:   { type: object }
          status:     { type: object }
          spec:
            type: object
    served: true
    storage: true
    subresources:
      status: {}

==> doot-shared-frank.yaml <==
apiVersion: example.com/v1alpha1
kind: Doot
metadata:
  name: shared
  finalizers: [example.com/frank]

==> doot-shared-lisa.yaml <==
apiVersion: example.com/v1alpha1
kind: Doot
metadata:
  name: shared
  finalizers: [example.com/lisa]

==> wonk-crd.yaml <==
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wonks.example.com
spec:
  group: example.com
  names:
    kind: Wonk
    plural: wonks
    singular: wonk
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion: { type: string }
          kind:       { type: string }
          metadata:   { type: object }
          status:     { type: object }
          spec:
            type: object
            properties:
              value:
                x-kubernetes-int-or-string: true
    served: true
    storage: true
    subresources:
      status: {}

==> wonk-shared-frank.yaml <==
apiVersion: example.com/v1alpha1
kind: Wonk
metadata:
  name: shared
  finalizers: [example.com/frank]

==> wonk-shared-lisa.yaml <==
apiVersion: example.com/v1alpha1
kind: Wonk
metadata:
  name: shared
  finalizers: [example.com/lisa]
```

```diff
● diff -u doot-crd.yaml wonk-crd.yaml
--- doot-crd.yaml       2021-02-26 22:39:02.000000000 +0000
+++ wonk-crd.yaml       2021-02-26 22:46:22.000000000 +0000
@@ -1,13 +1,13 @@
 apiVersion: apiextensions.k8s.io/v1
 kind: CustomResourceDefinition
 metadata:
-  name: doots.example.com
+  name: wonks.example.com
 spec:
   group: example.com
   names:
-    kind: Doot
-    plural: doots
-    singular: doot
+    kind: Wonk
+    plural: wonks
+    singular: wonk
   scope: Namespaced
   versions:
   - name: v1alpha1
@@ -21,6 +21,9 @@
           status:     { type: object }
           spec:
             type: object
+            properties:
+              value:
+                x-kubernetes-int-or-string: true
     served: true
     storage: true
     subresources:
```

---

Create the CRDs:

```
● kubectl create -f doot-crd.yaml -f wonk-crd.yaml
customresourcedefinition.apiextensions.k8s.io/doots.example.com created
customresourcedefinition.apiextensions.k8s.io/wonks.example.com created
```

Use server-side apply to set two finalizers by two managers:

```
● kubectl apply --server-side -f doot-shared-frank.yaml --field-manager=frank
doot.example.com/shared serverside-applied

● kubectl apply --server-side -f doot-shared-lisa.yaml --field-manager=lisa
doot.example.com/shared serverside-applied
```

```yaml
● kubectl get -f doot-shared-lisa.yaml -o yaml
apiVersion: example.com/v1alpha1
kind: Doot
metadata:
  creationTimestamp: "2021-02-26T22:50:31Z"
  finalizers:
  - example.com/frank
  - example.com/lisa
  generation: 1
  managedFields:
  - apiVersion: example.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          v:"example.com/frank": {}
    manager: frank
    operation: Apply
    time: "2021-02-26T22:50:31Z"
  - apiVersion: example.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          v:"example.com/lisa": {}
    manager: lisa
    operation: Apply
    time: "2021-02-26T22:50:39Z"
  name: shared
  namespace: default
```

Repeat for a CR that has an `x-kubernetes-int-or-string` field. Notice that instead there is a conflict:

```
● kubectl apply --server-side -f wonk-shared-frank.yaml --field-manager=frank
wonk.example.com/shared serverside-applied

● kubectl apply --server-side -f wonk-shared-lisa.yaml --field-manager=lisa
error: Apply failed with 1 conflict: conflict with "frank": .metadata.finalizers
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See http://k8s.io/docs/reference/using-api/api-concepts/#conflicts
```

```yaml
● kubectl get -f wonk-shared-lisa.yaml -o yaml
apiVersion: example.com/v1alpha1
kind: Wonk
metadata:
  creationTimestamp: "2021-02-26T22:54:22Z"
  finalizers:
  - example.com/frank
  generation: 1
  managedFields:
  - apiVersion: example.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers: {}
    manager: frank
    operation: Apply
    time: "2021-02-26T22:54:22Z"
  name: shared
  namespace: default
```

Cleanup:

```
● kubectl patch -f doot-shared-lisa.yaml -f wonk-shared-lisa.yaml --type=json -p '[{"op":"remove","path":"/metadata/finalizers"}]'
doot.example.com/shared patched
wonk.example.com/shared patched

● kubectl delete -f doot-shared-lisa.yaml -f wonk-shared-lisa.yaml
doot.example.com "shared" deleted
wonk.example.com "shared" deleted

● kubectl delete -f doot-crd.yaml -f wonk-crd.yaml
customresourcedefinition.apiextensions.k8s.io "doots.example.com" deleted
customresourcedefinition.apiextensions.k8s.io "wonks.example.com" deleted
```

#### Anything else we need to know?:

The symptoms seem like structural schema might be involved? #97172 looks related but also claims to have no user-facing change.

/sig api-machinery

#### Environment:

- Kubernetes version (use `kubectl version`):

I see the same behavior on v1.20 and v1.18.

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
