### ISSUE TITLE
Custom resource empty string / null validation broken with go1.16

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#99804]
#### What happened:

Reported by @uablrek in https://github.com/projectcalico/calico/issues/4443

After the switch to go1.16, custom resource clients submitting empty string values for string fields receive the following error:
```
The $Kind "$name" is invalid: $fieldpath: Invalid value: "null": $fieldpath in body must be of type string: "null"
```

#### How to reproduce it (as minimally and precisely as possible):

Create the following crd:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zerovalues.example.com
spec:
  group: example.com
  names:
    kind: ZeroValue
    listKind: ZeroValueList
    plural: zerovalues
    singular: zerovalue
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          a:
            type: string
        type: object
    served: true
    storage: true
```

Try to create the following custom resource:
```yaml
apiVersion: example.com/v1
kind: ZeroValue
metadata:
  name: default
a: ""
```

Building `master` with go1.15.8, this works. Building `master` with go1.16, this fails with:

```
The ZeroValue "default" is invalid: a: Invalid value: "null": a in body must be of type string: "null"
```

/priority critical-urgent
/sig api-machinery
/milestone v1.21
