### ISSUE TITLE
HPA not working with multiple External metrics (v1.17)

### ISSUE THREAD

**Issue by Unibozu** [kubernetes/kubernetes#99832]
Hi!

#### What happened:

I am trying to setup a HPA with multiple External metrics on a GKE Kubernetes cluster running v1.17

* External metrics are provided using Datadog Cluster Agent
* The HPA works properly when I use a single external metric. This applies for ANY of the metrics I try to use - the labels are tested and guaranteed to be right and the right data is coming from the Datadog agent
* Datadog agent is not showing any errors. Note that it shows an error if I use invalid metric labels (which helped me to test my labels and know for sure they are right)
* Using 2 or 8 metrics doesn't change the outcome. It blocks as long as there is more than 1 metric
* Number of replicas doesn't change anything
* If I `kubectl apply` a broken HPA with multiple metrics to only have one of those metrics, then it works. Applying back the version with multiple metrics breaks it again. Deleting/re-creating doesn't change the outcome.
* ⚠️ if I duplicate the same metric multiple times then it works. The two (identical) metrics show the right value in `kubectl describe`. Break again if I change one of the metrics.

Output from `kubectl describe hpa ...`

```
Every 2.0s: kubectl describe hpa/kafka-consumer                                                   OVO6300MB-MacBook-Pro.local: Fri Mar  5 08:40:25 2021

Name:                                           kafka-consumer
Namespace:                                      default
Labels:                                         name=kafka-consumer
Annotations:                                    <none>
CreationTimestamp:                              Thu, 04 Mar 2021 16:09:10 +0000
Reference:                                      Deployment/kafka-consumer
Metrics:                                        ( current / target )
  "kafka.consumer_lag" (target average value):  <unknown> / 200
  "kafka.consumer_lag" (target average value):  <unknown> / 200
Min replicas:                                   1
Max replicas:                                   5
Deployment pods:                                1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric default/kafka.co
nsumer_lag/&LabelSelector{MatchLabels:map[string]string{topic:
 foo1,},MatchExpressions:[]LabelSelectorRequirement{},}: no metrics returned from external metrics API
Events:
  Type     Reason                        Age                   From                       Message
  ----     ------                        ----                  ----                       -------
  Warning  FailedComputeMetricsReplicas  25m (x3761 over 16h)  horizontal-pod-autoscaler  failed to compute desired number of replicas based on listed
metrics for Deployment/default/kafka-consumer: failed to get kafka.consumer_lag external metric: unable to get external metric default/kafk
a.consumer_lag/&LabelSelector{MatchLabels:map[string]string{to
pic: foo1,},MatchExpressions:[]LabelSelectorRequirement{},}: no metrics returned from external metrics API
  Warning  FailedGetExternalMetric       52s (x3860 over 16h)  horizontal-pod-autoscaler  unable to get external metric default/kafka.consumer_la
g/&LabelSelector{MatchLabels:map[string]string{topic: foo1,},MatchExpressions:[]LabelSelectorRequirement{},}: no metrics returned from external metrics API
```

#### What you expected to happen:

HPA to work properly with multiple metrics. More descriptive errors?

#### How to reproduce it (as minimally and precisely as possible):

This it the HPA. Not sure it's worth sharing our datadog agent configuration.

```yaml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-consumer
  namespace: default
  labels:
    name: kafka-consumer
spec:
  maxReplicas: 5
  minReplicas: 1
  metrics:
    - external:
        metric:
          name: "kafka.consumer_lag"
          selector:
            matchLabels:
              topic: "foo1"
        target:
          type: AverageValue
          averageValue: "200"
      type: External
    - external:
        metric:
          name: "kafka.consumer_lag"
          selector:
            matchLabels:
              topic: "foo2"
        target:
          type: AverageValue
          averageValue: "200"
      type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-consumer
```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.17.15-gke.800
- Kubelet Version: v1.17.15-gke.800
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): Container-Optimized OS from Google
- Kernel (e.g. `uname -a`): 4.19.150+
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

Thanks
