### ISSUE TITLE
Support 'patch' files with `kubectl apply -f` 

### ISSUE THREAD

**Issue by dprotaso** [kubernetes/kubernetes#99867]
#### What would you like to be added:

I would like there to be a declarative way to specify a patch which can be applied on a resource with `kubectl apply`.  Currently `kubectl patch` requires a resource type, name and potentially a namespace.

I see `kustomize` allows for `inline` patches when applying to base files:

```yaml
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deploy
  spec:
    template:
      spec:
        containers:
        - name: nginx
          image: nginx:latest
```

It'd be great if `kubectl apply -f` could accept a yaml file that contains the extra metadata to perform the patch

```yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deploy
    namespace: default
    annotations:
      kubectl.k8s.io/patch: true
  spec:
    template:
      spec:
        containers:
        - name: nginx
          image: nginx:latest
```          

In the above `kubectl.k8s.io/patch: true` signals that the resource is to be patched and not applied. This is an example - not a recommendation. 

#### Why is this needed:

This would be for convenience so I could have a directory of resources & patches that I could simply apply with `kubectl apply -Rf somedir/`

I think an edge-case is what happens when a patch file is present when doing `kubectl delete -Rf somedir/`.
